### ISSUE TITLE
请问跳转预览界面需要放开哪些端口？

### ISSUE THREAD

**Issue by Huiguorou12** [langgenius/dify#100]
![image](https://github.com/langgenius/dify/assets/110574680/0e355efc-d2c8-47d3-99ab-74fbfcf96eb9)

**Comment by takatost** [comment]
未额外配置 APP_URL 参数，即为同域

**Comment by Huiguorou12** [comment]
但当跳转到预览页面，会返回404，这是否和我修改了nginx和redis的端口映射有关？因为我在本地部署的另一套（没有修改端口，防火墙已关闭），是可以正常跳转预览界面的

**Comment by takatost** [comment]
和 nginx 端口映射可能有关，需要额外配置 api 容器的 APP_URL 域名，以适配 nginx 不同端口
