### ISSUE TITLE
MP3 upload dinied "file extension not supported"

### ISSUE THREAD

**Issue by FBR65** [langgenius/dify#10009]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Workflow Start-component:

Define variable as File Input.

Choose Audio.

Test Run

### ✔️ Expected Behavior

Upload of MP3 file

### ❌ Actual Behavior

"file extension not supported" is shown in right upper corner of the GUI

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9992
