### ISSUE TITLE
"operation not permitted", execute a os command using python os and subprocess modules

### ISSUE THREAD

**Issue by jiusi9** [langgenius/dify#10002]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

import os, subprocess package, but can not be executed. It always report  "operation not permitted"

```
def main(command):
    import os, subprocess
    cmd = command

    try:
        print(cmd)
        output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
        print("Output:")
        result = output.decode('utf-8')
    except subprocess.CalledProcessError as e:
        result = f"Error executing grpcurl command: {e.output.decode('utf-8')}"

```
![image](https://github.com/user-attachments/assets/159820c6-39a8-4003-9c34-82c8363f2fc5)

Can not allow to execute some OS command?

### ✔️ Expected Behavior

Hope to execute os command on sandbox containers.

**Comment by jiusi9** [comment]
```
def main() -> dict:
    import os
    hostname = os.popen("hostname")
    aaa = os.read(hostname)

    return {
        "result": hostname,
    }
```


![image](https://github.com/user-attachments/assets/d70da077-84ef-416c-9ecb-0690ce4c62b6)

**Comment by crazywoola** [comment]
See dify-sandbox's faq.
