### ISSUE TITLE
Can't pop up the refs for code execution node.

### ISSUE THREAD

**Issue by KevinZhang19870314** [langgenius/dify#10006]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I can't provide the more details for repro, because I follow the [docs](https://docs.dify.ai/zh-hans/guides/workflow/node/variable-assigner), and also do many more modifies and drag & drop and etc.

Here is the screenshot for this issue, you can see there is no "代码执行 2" node in pop up list. I have to export the dsl and copy the id and then paste in it. {{#1730192240873.result#}}
![image](https://github.com/user-attachments/assets/e56ed8bd-445e-4ce1-9d56-a794535470fa)

Provide the dsl. 
[变量赋值test2.yml.txt](https://github.com/user-attachments/files/17554358/test2.yml.txt)

### ✔️ Expected Behavior

Should pop up the code execution node after type '/'

### ❌ Actual Behavior

Not pop up the code execution node after type '/'

**Comment by KevinZhang19870314** [comment]
I am trying to delete and re-add it, but no lucky.

**Comment by crazywoola** [comment]
LLM node accepts the string variables only, but you have object in the code block.

**Comment by KevinZhang19870314** [comment]
@crazywoola Sorry, I am still can't understand your response, and confuse with that. 

1. For the "代码执行 2" node, it accept a Conversation Variables `ai_checklist`, which is a Array object, also output the same obj array;
2. Then the next node is a Direct Reply node;

It seems there are no LLM node related this two nodes. The only LLM node in my workflow is in the vary beginning, it seems there is no object variables in it? I am not sure the LLM node you mentioned ref to what?

**Comment by crazywoola** [comment]
![QQ_1730195490987](https://github.com/user-attachments/assets/40309559-a1ee-44e6-bd73-1e8e28e2f704)

> For the "代码执行 2" node, it accept a Conversation Variables ai_checklist, which is a Array object, also output the same obj array;

You need to use a code block to convert the object to string, otherwise, it can not be selected in Answer node.

**Comment by crazywoola** [comment]
![QQ_1730195606477](https://github.com/user-attachments/assets/7c6e8f48-77b3-4251-8029-2a92fe7b1840)

**Comment by KevinZhang19870314** [comment]
![image](https://github.com/user-attachments/assets/5f1217fc-6b6d-4681-a199-875f2bcefa23)
![image](https://github.com/user-attachments/assets/c32a0046-604c-468b-be8c-05585f0fe163)

Thank you for saving my day! @crazywoola
