### ISSUE TITLE
when use multi file, failed with error "Run failed: sequence item 2: expected str instance, list found"

### ISSUE THREAD

**Issue by zhuqingchao** [langgenius/dify#10000]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

DSL:
[multi_file_error.txt](https://github.com/user-attachments/files/17554046/multi_file_error.txt)
![image](https://github.com/user-attachments/assets/f15165cb-9205-4e67-9054-7ee74015084e)
I found that prompt_template_parser.py line 36. when the inputs contains  array[file] -> array[string] 。 then it failed at line 40.
I don't know if I should type match the array directly to a string here, or convert it elsewhere.

### ✔️ Expected Behavior

propmt template generate success. 

### ❌ Actual Behavior

failed with error

**Comment by zhuqingchao** [comment]
> sys.files is an array, and its output variable is also an array. It cannot be placed directly in the LLM prompt word. You can add LLM to the iteration by connecting an iterator to the document extractor.
got it.  so array[string] should not be choosed in the graph editor.  maybe need to fix this

**Comment by crazywoola** [comment]
It seems you open a new https://github.com/langgenius/dify/issues/10004 here, this can be closed right?

**Comment by zhuqingchao** [comment]
> It seems you open a new #10004 here, this can be closed right?
@crazywoola I think #10004 is another bug.  The current bug refers to the ability to select an array[string] generated by the doc extractor array[file] in the prompt of the LLM node. Another issue is that when the start node changes from a single file to multiple files, the output of the doc extractor is still a string instead of an array[string].
