### ISSUE TITLE
The problem classifier reports an error when using claude and is completely unusable

### ISSUE THREAD

**Issue by sunxiaojia123** [langgenius/dify#10005]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0abf415a-2ccb-4846-8aa9-92a1e860e5d6)
* When I use claude as the engine for the question classifier, this is bound to happen: [bedrock] Error: ValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.
* Previously, using version 0.8.0 was fine
* This problem has appeared since version 0.10.0, and I understand that the previous issue [#9764 ](url) mentioned this problem and was closed. My task has solved this problem, but I upgraded to version 0.10.2 today and it is still not solved.
* I know that openai's engine can solve this problem, but unfortunately, I didn't pay for openai, I only paid for claude from aws

### ✔️ Expected Behavior

Run normally and help me find the results I want

### ❌ Actual Behavior

[bedrock] Error: ValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.

**Comment by crazywoola** [comment]
Duplicated

**Comment by ma77022** [comment]
"A conversation must alternate between user and assistant roles"  ,   I have also encountered this problem, have you solved it?
