### ISSUE TITLE
“Bad Request Error, Error code: 400 - [anthropic] {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: all messages must have non-empty content except for the optional final assistant message'}}”

### ISSUE THREAD

**Issue by MitraSafarinejad** [langgenius/dify#10013]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I’m currently using the Anthropic claude 3.5 Sonnet model in agent mode and encountered this error message:

“Bad Request Error, Error code: 400 - [anthropic] {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: all messages must have non-empty content except for the optional final assistant message'}}”
Interestingly, if I open a new chat, the error disappears temporarily.

Could you please help me understand what might be causing this error and how I could resolve it?

![image](https://github.com/user-attachments/assets/d9f676d4-74f9-4ef0-8f75-0cf3c01da91c)

### ✔️ Expected Behavior

The model should respond to user inputs in agent mode without error, processing each message smoothly.

### ❌ Actual Behavior

The model returns a “Bad Request” error for requests, specifying that all messages must have non-empty content, even though the messages do contain content

**Comment by MitraSafarinejad** [comment]
I appreciate the suggestion; however, I am using the Sonnet model in Chatbot Basic or Agent Mode, which doesn't involve handling UserPromptMessage or SystemPromptMessage parameters directly. This error still occurs under these conditions, and it temporarily resolves if I start a new chat.

Could there be another cause or solution applicable to Agent Mode specifically? Thank you very much for any further guidance you can provide!

**Comment by crazywoola** [comment]
This is a known issue, we haven't fixed it yet. I have already talk to the team regarding your previous issue https://github.com/langgenius/dify/issues/9366

**Comment by MitraSafarinejad** [comment]
Thank you for your message. I just wanted to clarify that this issue is different from #9366. The error in #9366 was related to the number of tools called by the Anthropic models, but this issue is not about tools at all.

I think it might be better to reopen issue #9366 since the two issues are not related. Please let me know if you need any further details to help address this. Thank you!

**Comment by tnfsmith** [comment]
This also happens on AzureOpenAI

**Comment by pru007** [comment]
I am using langgraph, I am facing the same issue there as well. Just wanted to check if this error is specific to Anthropic models.

**Comment by CosplayCookoff** [comment]
Why is this closed?  How is it fixed??  I have this 400 error atleast 5 times per day and it means I have to start a new interation of the api.  I am so very frustrated!

**Comment by laipz8200** [comment]
> Why is this closed? How is it fixed?? I have this 400 error atleast 5 times per day and it means I have to start a new interation of the api. I am so very frustrated!

Because we've fixed it in the main branch, it will work in the next version.

**Comment by mrecek** [comment]
I'm not sure this is fixed. I just updated to the latest version (2025.3.1) but I am receiving the "text content blocks must be non-empty" from my ESP32 S3 Box 3 when using the Claud API. Some commands work, but about half the time I get this error message. I'll also get this error when chatting via text prompts. For example, I'll type "turn off all the lights", it turns them off without errors, then I type "now turn them on" then I get this error message:

Sorry, I had a problem talking to Anthropic: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: text content blocks must be non-empty'}}

**Comment by MitraSafarinejad** [comment]
Hello,

I'm currently using Dify version 1.3.1 and have encountered the same error:

[models] Bad Request Error, Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.1: all messages must have non-empty content except for the optional final assistant message'}}

This occurs when utilizing the Anthropic Claude 4 Opus model in agent mode.
Additionally, I've noticed that when I open the logs, the "Thinking..." timer starts
Although this issue was marked as fixed in [#11238](https://github.com/langgenius/dify/pull/11238), it seems to still be present in the latest version.

![Image](https://github.com/user-attachments/assets/c4b853dc-cd9d-4ef1-9008-d1e47ad8f399)

Could you please provide guidance on how to resolve this?

**Comment by laipz8200** [comment]
Hi @MitraSafarinejad. Since this issue is already closed, you should open a new one for your problem. Claude doesn't support any empty messages in the prompt, you can check your inputs for the LLM in the tracing panel.

**Comment by garyy7811** [comment]
latest version still having same problem :
  ⎿ API Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.13: all messages must have      
    non-empty content except for the optional final assistant message"}}

**Comment by Sarfaraz021** [comment]
this issue still persist even with claude sonnet 4 

<img width="742" height="725" alt="Image" src="https://github.com/user-attachments/assets/2e6d2d40-cb90-49b5-8c35-b2f5313abaa5" />

**Comment by tjallingvds** [comment]
Still have the same issue team

**Comment by lankabhedi** [comment]
Still having this issue.

`  ⎿ API Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.241: all messages must have non-empty content except for 
    the optional final assistant message"},"request_id":"req_011CTQK8MZcoq2ZURLNWL85j"}
`

**Comment by Mono-123** [comment]
Claude Sonnet 4-5 also encountered this issue while using the online platform's agent, and once an error occurs, the subsequent conversation cannot proceed. How should this be handled?

**Comment by shimosaka** [comment]
I am also encountering the same problem. My Dify version is 1.9.2 (the latest).

This is occurring with LLMs other than Claude as well, so it may not be a Claude-specific issue. For me, it happens in an app that generates images when file upload in chat is enabled. It seems that after an image is generated (or displayed), the handling of sys.files breaks, and it becomes empty.

Disabling file upload resolves the issue in my case.
