### ISSUE TITLE
Issues with Document Character Count and Recall Frequency Statistics

### ISSUE THREAD

**Issue by NoobHaoZi** [langgenius/dify#10011]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After the knowledge base completes indexing, modify the original segmented content or add new segments. 

The character count of the document will not be updated. 

Additionally, if the new segmented content passes the recall test or matches through knowledge base retrieval, it will not count towards the recall frequency.
![企业微信截图_17301946715130](https://github.com/user-attachments/assets/fc81d8b9-06b4-40fb-9dbd-c43d16d065e8)

### ✔️ Expected Behavior

Expected Results:

1 When new segments are added or existing segments are modified, the document's character count updates accordingly.
2 When the knowledge base retrieval hits newly added segments, the recall frequency is recorded accurately.

### ❌ Actual Behavior

Actual Results:

1 When new segments are added or existing segments are modified, the document's character count does not update accordingly.
2 When the knowledge base retrieval hits newly added segments, the recall frequency is not recorded.

**Comment by JohnJyong** [comment]
1. the document word count will be fixed later 
2. for retrieval count, it only be counted when you retrieve it  in the chatbot or workflow, retrieve-testing will not be included.
@NoobHaoZi
