### ISSUE TITLE
Token has expired.

### ISSUE THREAD

**Issue by NirvanaProduct** [langgenius/dify#10019]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4e9f68b7-4fd6-4a45-b338-9f74bd9a1207)
![image](https://github.com/user-attachments/assets/5ba7ef0c-79a4-4289-ae98-f558f9bf2ec9)
![image](https://github.com/user-attachments/assets/d5ebec34-d31f-4396-8b57-85c109e0af20)
After updating to 0.10, token expiration occurred very frequently, which was not the case before

### ✔️ Expected Behavior

Keep logged in

### ❌ Actual Behavior

Token has expired

**Comment by crazywoola** [comment]
Please upgrade to v0.10.2 to see if this persists. You need to restart the containers if you edit those values.
