### ISSUE TITLE
ComfyUI tool’s workflow encountered an error when running 'Failed to invoke tool: list index out of range'

### ISSUE THREAD

**Issue by yaojech** [langgenius/dify#10014]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The tool configuration is as follows:
![image](https://github.com/user-attachments/assets/234bc7a4-a8b5-4a62-9a70-62e726c2fb5f)
The error is as follows:
![image](https://github.com/user-attachments/assets/4ce12fc3-430b-4c13-8421-16b3128722eb)
The workflow JSON is as follows:
[flux_api.json](https://github.com/user-attachments/files/17555478/flux_api.json)

**Comment by hjlarry** [comment]
current implementation will find the `Ksample` node of Comfy, then get it's positive and negitive input string and fill it. 
But now I found that there are lot of workflows not use  `Ksample`,  I'll try to implement it with another method later.
