### ISSUE TITLE
Can't retrieve image.url from the Start node

### ISSUE THREAD

**Issue by xfanwu** [langgenius/dify#10027]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Cloud latest

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Set an image as required input at Start node
2. add any sequence block and link to the start node
3. use variable of image.url from the Start node in the added block
4. in the Preview mode, upload any image or paste a url
5. actually the value from input was not passed to the block

### ✔️ Expected Behavior

Get the value from image file.

### ❌ Actual Behavior

The image file return null.

Please see attached for my test.

![WX20241030-022850@2x](https://github.com/user-attachments/assets/70545549-6520-40ed-b7b2-ad4f0652559e)

![WX20241030-022207@2x](https://github.com/user-attachments/assets/2b965c91-acc5-4f6c-8c4a-5689046c8dd3)

**Comment by hjlarry** [comment]
duplicated with https://github.com/langgenius/dify/issues/9567
