### ISSUE TITLE
After successfully deploying Docker locally, it keeps spinning when entering the install.

### ISSUE THREAD

**Issue by lbersl** [langgenius/dify#10024]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

**It has been stuck on this page without moving：**

![image](https://github.com/user-attachments/assets/3c1aaa54-a88d-4fcd-ba84-0fc029269647)

**Comment by danni-cool** [comment]
Windows11 environment，ame problem, and all the fix solutions didn't work for me, and I tried to switch version to 0.10.1, all goes well now. @lbersl

**Comment by ejscribner** [comment]
Seems to be related to https://github.com/langgenius/dify/issues/10023

**Comment by crazywoola** [comment]
Please use the right template to open an issue, this requests docs changes. @lbersl
