### ISSUE TITLE
Help: How to debug front-end

### ISSUE THREAD

**Issue by Erincrying** [langgenius/dify#10020]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I have deployed dify on a Linux server. How can I debug front-end services? Is it done by 'npm run dev’? However, this method may cause delays and errors. Can someone tell me how to debug front-end code correctly？Thank you very much！

**Comment by Erincrying** [comment]
> [<img alt="@Erincrying" width="40" height="40" src="https://avatars.githubusercontent.com/u/65204363?s=80&amp;v=4">](/Erincrying)
> 
> 
> #### Add a comment
@dosu How to interrupt and debug front-end code

**Comment by crazywoola** [comment]
If you would like to request for help, please use discussion instead.
