### ISSUE TITLE
An error occurred while downloading and uploading files in the chat assistant

### ISSUE THREAD

**Issue by Erincrying** [langgenius/dify#10049]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Upload files in the chat assistant
2. Click to download
3. Unable to download, displaying 'The file at' http://xxx:3000/app/5xxx/workflow ' was loaded over an insecure connection.  This file should be served over HTTPS.
![image](https://github.com/user-attachments/assets/f4647a9c-4719-49c7-b503-6ceadbbf5e36)

![image](https://github.com/user-attachments/assets/148b2b7e-e0f9-4f63-ab5d-63ddc9fb045d)
5.Open the downloaded document
![image](https://github.com/user-attachments/assets/782b6912-38ee-42a3-b029-aec9433a858c)

**Comment by crazywoola** [comment]
You need to configure HTTPS then.

**Comment by Erincrying** [comment]
> You need to configure HTTPS then.

Does the source code of 0.10.1 require HTTPS configuration for file download? Is there any documentation related to configuration

**Comment by Erincrying** [comment]
> This is required by browser's security policy, if you want to debug this, you could turn off that settings.

Exporting DSL also generates HTTPS errors, but the content downloaded from the file is correct, while downloading documents from the chat assistant results in downloading HTML content
