### ISSUE TITLE
Error: Response output is missing or does not contain embeddings.

### ISSUE THREAD

**Issue by yinzih** [langgenius/dify#10047]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I create a knowledge base, I get an error when embedding processing.
[tongyi] Error: Response output is missing or does not contain embeddings.
![QQ20241030-095722](https://github.com/user-attachments/assets/de83b52b-6719-4efa-8d0f-22e57160b768)
How can I solve this problem?

**Comment by zyy13579** [comment]
![image](https://github.com/user-attachments/assets/bf5405e8-6ee7-46eb-939a-f84a5a87d643)
I I'm running into this problem as well

**Comment by shisaru292** [comment]
I got the same problem with the version 0.10.1. In the sentry log, it shows that the api key is invalid.

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/ae97dab9-eb4e-49b2-a2bc-883396121e49">

This issue might be related to API key encryption and storage?

<img width="639" alt="image" src="https://github.com/user-attachments/assets/e8ac4862-6b75-4b72-be7e-dec7d2d7f582">

**Comment by shisaru292** [comment]
> I got the same problem with the version 0.10.1. In the sentry log, it shows that the api key is invalid.
> 
> <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/87224749/381809192-ae97dab9-eb4e-49b2-a2bc-883396121e49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjQ4OTIsIm5iZiI6MTczMDM2NDU5MiwicGF0aCI6Ii84NzIyNDc0OS8zODE4MDkxOTItYWU5N2RhYjktZWI0ZS00OWIyLWEyYmMtODgzMzk2MTIxZTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA4NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzNjYmEyODFhNDg2OTExZTk2MWEwNWI3YjI5NTgyZGNhMTNjMWNmMDExN2ZiZTUyMmY2NWU4YTRjN2Q0ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p1QqfKeF80xZjdbFUrZbO1uYjbEmngm68u_Dg380iyo">
> This issue might be related to API key encryption and storage?
> 
> <img alt="image" width="639" src="https://private-user-images.githubusercontent.com/87224749/381810104-e8ac4862-6b75-4b72-be7e-dec7d2d7f582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjQ4OTIsIm5iZiI6MTczMDM2NDU5MiwicGF0aCI6Ii84NzIyNDc0OS8zODE4MTAxMDQtZThhYzQ4NjItNmI3NS00YjcyLWJlN2UtZGVjN2QyZDdmNTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA4NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNTZiNzZjYmMzODAxMmJiMzU2NjQ1NDhmOGE4ZDVkOTBhZGZhYjY3YWJkYTdlZTFlMDgyMGM1NmFkMzM1OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nffvCQ__r7k_-9B1nqrRV7aqCi-Jj7e_D4St7sKH9UM">
> This appears to be caused by using encrypted credentials directly as API key

I reviewed the source code, and during the process of obtaining the API key, it first retrieves historical decrypted results from the Redis cache. The stored data in Redis consists of the encrypted results.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/a8a659db-57ef-44f2-97d3-6103478deed9">

**Comment by shisaru292** [comment]
I obtained the encrypted credentials data and private key from Redis in the environment which has the error and simulated the decryption process locally. An exception was thrown on this line of code:

https://github.com/langgenius/dify/blob/main/api/libs/rsa.py#L76

Error message is: `Incorrect decryption.`

**Comment by shisaru292** [comment]
From the code, it appears that the public key in the db is only written once during tenant creation. If the private key for the same tenant is regenerated afterward, it will lead to an inconsistency. It seems there are no other methods in the code to update the public key. 

One SOLUTION is to use the command provided by Dify to reset the key pair, but be aware that this will invalidate the existing model authentication and require reconfiguration of all providers.

https://github.com/langgenius/dify/blob/main/api/commands.py#L98-L115

**Comment by shisaru292** [comment]
I have submitted a Pull Request(#10210) for your review. Thank you! @crazywoola

**Comment by v-49** [comment]
still happend at v0.12.1
![image](https://github.com/user-attachments/assets/4a566716-ff77-4a95-97e1-b8655581b86d)

**Comment by V7CN** [comment]
This issue tends to occur when the same API key is added multiple times within the Model Provider. In my case, it happened when using Tongyi's API and additionally adding the Deepseek Model provided by Tongyi (while using the same API key). The solution is straightforward: assign a separate API key specifically to the Deepseek Model provided by Tongyi.

**Comment by Rakest** [comment]
<img width="1055" height="638" alt="Image" src="https://github.com/user-attachments/assets/0ddd0420-22e6-435a-9eb4-ac36d100a610" />

hi, may i ask how u got the result on the picture, where can i get it or which command should i use, thanks
