### ISSUE TITLE
Typo in the template for dataset API hit testing

### ISSUE THREAD

**Issue by sacryu** [langgenius/dify#10054]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

This correct url for hit-testing throught API should be: 
`ip:port/v1/datasets/{dataset_id}/hit-testing`

<img width="1148" alt="1730270388879" src="https://github.com/user-attachments/assets/5cd9ff3c-6f74-42f8-81f7-9df21a91d3dd">

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/8501af298fbf89dc9146c3a65bb7f3d518dc786d/api/controllers/console/datasets/hit_testing.py#L24

Yes you are correct, please feel free to open a pr for this.
