### ISSUE TITLE
Recall the knowledge base in the iteration of the workflow and report errors when executing

### ISSUE THREAD

**Issue by wangiii** [langgenius/dify#10057]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Recall the knowledge base in the iteration of the workflow and report errors when executing
<img width="1593" alt="image" src="https://github.com/user-attachments/assets/0955b7ec-d642-4459-9682-ba0de9460643">

### ✔️ Expected Behavior

Expected to run successfully

### ❌ Actual Behavior

Report an error：Run failed: not supported value [[], []]

**Comment by Modas-Li** [comment]
same issue， how?

**Comment by wangiii** [comment]
> same issue， how? 

The fix has been merged into the main branch
https://github.com/langgenius/dify/pull/10060

**Comment by Modas-Li** [comment]
Thank you for your email !您好，你的邮件我已收到，我会尽快给你回复。
