### ISSUE TITLE
It is recommended that the TTS model of the podcast audio generator can be used as a system model

### ISSUE THREAD

**Issue by fsea** [langgenius/dify#10056]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The podcast audio generator can only use OpenAI, not the system model

### 2. Additional context or comments

Hopefully, the podcast audio generator will be able to use the system model

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We have plan to use fish audio later, but currently, it has a different implementation from the system model settings, so they can not be shared in this case.

**Comment by emptinessboy** [comment]
I received error “Invalid OpenAI API key” when I use customid base url in podcast application. (dify version v0.11.1)
