### ISSUE TITLE
Add an environment variable for developers to choose whether to update the inputs value in the same conversation

### ISSUE THREAD

**Issue by huu3301** [langgenius/dify#10055]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In a multi-round conversation, the current design of dify is that when the user passes the conversation_id parameter to the interface, the value of inputs can only be the value of inputs when the conversation is created. 
Can a switch be made or an environment variable be designed so that developers can choose whether to update the value of inputs in the same conversation? 
sometimes custom variables need to be updated in in actual use, such as some parameters of the environment, but currently if I want to update the inputs, I can only create a new conversation.

### 2. Additional context or comments

![image](https://github.com/user-attachments/assets/d18a0a95-3222-43b4-b911-5d9a567656af)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by wy96f** [comment]
We also have similar scenarios where this feature is needed. For example, during a multi-turn conversation, if a user wants to take leave, the API caller can upload an attachment and include it in the input; or if a user applies to go out, the API caller can put the latitude and longitude information in the input (Note: In both of these examples, the final step is to call a tool API, which requires attachments and location information as parameters).
