### ISSUE TITLE
The files parameter of the API /chat-messages is invalid

### ISSUE THREAD

**Issue by Lockeysama** [langgenius/dify#10069]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Upload the file to obtain the file ID.
2. Call the /chat-messages API, input the file ID:
```json
[
    {
      "type":"image", "transfer_method":"local_file","upload_file_id":"0304c8a6-9c83-xxxx-9d1f-db99fa305d97"
    }
]
```
    and ask "What is this?"
3. Initiate the request.

### ✔️ Expected Behavior

1. Respond with content related to the image.

### ❌ Actual Behavior

1. Returned content unrelated to the image.
2. Checked the records in the dify backend and found no image context.

**Comment by crazywoola** [comment]
Please check if the application has turned on the vision or enable file upload feature.

**Comment by Lockeysama** [comment]
> Please check if the application has turned on the vision or enable file upload feature.

Yes, it works fine when I test it on the backend orchestration page, but this problem occurs when using the API.

**Comment by crazywoola** [comment]
Please paste the payload, you should call two api endpoints. So please attach them here.

**Comment by Lockeysama** [comment]
> Please paste the payload, you should call two api endpoints. So please attach them here.

Sorry! I couldn't reproduce it anymore; I deleted the service and redeployed it, and it worked.
