### ISSUE TITLE
modify the admin Email 

### ISSUE THREAD

**Issue by ge2001** [langgenius/dify#10075]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Docker compose deployment of local dify, how to modify the admin Email without the need to reclone

### 2. Additional context or comments

![1730291798413](https://github.com/user-attachments/assets/67d81445-10f6-42ed-9821-71697ca9d6ed)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/878d13ef4215e07ee8da346254e00843a707a361/api/commands.py#L68-L71

**Comment by saendu** [comment]
How can I use this endpoint to change my email account (owner account)?

**Comment by fernvenue** [comment]
Hi @crazywoola, could you pls explain more about how to use it? I just tried to reset the email but nothing happened, no error no warning no output, just nothing...

**Comment by o-smallit** [comment]
@fernvenue You can start the email reset process by running the following command:
```sh
docker exec -it docker-api-1 flask reset-email
```
