### ISSUE TITLE
If the user only uploads a single type of file, such as an image, both the upper and lower parallel processes will be executed. The VL model will return correctly, but the lower document parsing node will return empty content. However, the lower model will also be executed once, and the returned content is not as expected.

### ISSUE THREAD

**Issue by jiaolongxue** [langgenius/dify#10086]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

If the user only uploads a single type of file, such as an image, both the upper and lower parallel processes will be executed. The VL model will return correctly, but the lower document parsing node will return empty content. However, the lower model will also be executed once, and the returned content is not as expected.

<img width="739" alt="3c2e2d401b4d1a725d341c0c7687c39" src="https://github.com/user-attachments/assets/a850a6e1-da95-4a42-b11b-1e1de8754558">

<img width="151" alt="46fe38eb7f35210ad7f52b06b7db25b" src="https://github.com/user-attachments/assets/3d360f5d-2f74-4bfe-b3e9-c3b2c51da5c3">

### ✔️ Expected Behavior

The lower doc LLM will not be executed.

### ❌ Actual Behavior

<img width="151" alt="46fe38eb7f35210ad7f52b06b7db25b" src="https://github.com/user-attachments/assets/3d360f5d-2f74-4bfe-b3e9-c3b2c51da5c3">

**Comment by crazywoola** [comment]
That's why it's parallel. 
If you want to make sure only one branch is executed, please use if/else node instead.
