### ISSUE TITLE
Research on the use of Firecrawl

### ISSUE THREAD

**Issue by starweavingdream** [langgenius/dify#10084]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I was researching Firecrawl, I found that Firecrawl officially provided a standalone deployment version, but in Dify, only the official paid version of Firecrawl was used. Can you extend this component so that it has the option of either using the official paid version or configuring our own Firecrawl?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by hjlarry** [comment]
the firecrawl's config APIKEY panel,  also can set its baseurl,  why can't config your own firecrawl?

**Comment by starweavingdream** [comment]
@hjlarry Sorry, I'm using an old version. After I updated to the new version, I found that it already supports self-hosting.
