### ISSUE TITLE
Hybrid Search Error when using `text-embedding-3-small` for embedding and use the same question to search

### ISSUE THREAD

**Issue by HeMuling** [langgenius/dify#10080]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

According to my test, this should produce:
1. click create knowledge
2. browse, upload a file
3. click next
4. enable `Segmenting in Question & Answer format`
5. choose `text-embedding-3-small` for embedding model
6. choose hybrid search, set top K to 10
7. save & process
8. after finishing, get into the document to see the result
9. find a random question, e.g.: here I choose `该DNA序列的方向是什么？` and `引物在DNA合成中有什么作用？`
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/1d115287-d02f-4809-a6a0-3736d82b956f">
10. use the question for hybrid search, e.g.:
<img width="654" alt="image" src="https://github.com/user-attachments/assets/7e9fb5df-4183-4d6b-bb45-29d7a3127bd6">

This will raise error.

However, if use `text-embedding-3-large` for embedding, there will be no error

### ✔️ Expected Behavior

If you do not use the exact same question generated, e.g.:
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/291ad962-bc13-4c4d-9e7c-6bda27cb897c">
This will get you the correct result

### ❌ Actual Behavior

Raise error: `shapes (3072,) and (1536,) not aligned: 3072 (dim 0) != 1536 (dim 0)`
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/e923c33a-573e-4bc9-af25-672cad6ce8f0">

**Comment by crazywoola** [comment]
If you switch to another embedding model, you will need to wait for a while to make sure the reindex process is completed. Otherwise you will see this error, this is because these 2 different embedding models have different dimensions.

**Comment by HeMuling** [comment]
> If you switch to another embedding model, you will need to wait for a while to make sure the reindex process is completed. Otherwise you will see this error, this is because these 2 different embedding models have different dimensions.

Hi @crazywoola, I'm not following, in which step did I switch the embedding model? It seems that you don't have an option to choose different embedding model in hybrid search. Also I'm wondering why it became correct when I'm not using the same query as question generated.
