### ISSUE TITLE
Performance Issue with Batch Insert in /datasets/{dataset_id}/documents/{document_id}/segments API

### ISSUE THREAD

**Issue by Angelxiaotao** [langgenius/dify#10094]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Use the /datasets/{dataset_id}/documents/{document_id}/segments API to insert a batch of segments.
Attempt to insert more than 200 segments in a single request.
Observe the performance slowdown as the segment count approaches or exceeds 1000 entries.

### ✔️ Expected Behavior

Could you provide guidance on optimizing this process, or consider implementing performance improvements for batch insert operations on this endpoint? Support for higher throughput or more efficient bulk operations would be highly beneficial for users with large datasets.

### ❌ Actual Behavior

Inserting batches of more than 200 segments leads to slow performance, which becomes especially problematic when handling large datasets that require high-volume segment insertions.

**Comment by JohnJyong** [comment]
Please describe clearly what performance degradation refers to, whether it is database processing time, interface return time, or Embedding time.

**Comment by Angelxiaotao** [comment]
@JohnJyong We are currently experiencing a particularly slow response to requests from this interface. Our server is configured with a 4-core CPU, 30GB of memory, 500GB of hard drive, and 16GB of GPU with graphics memory. In this configuration, when inserting more than 200 segments in bulk, the interface response time is significantly prolonged, which affects the processing efficiency of large amounts of data. Do you have any optimization suggestions or further performance improvement plans?
