### ISSUE TITLE
Access API in Studio

### ISSUE THREAD

**Issue by nameIsNoPublic** [langgenius/dify#10091]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Delete Conversation interface
![image](https://github.com/user-attachments/assets/f94ae162-38a6-4317-9861-d3ad0af7910c)

But in my result:
<img width="540" alt="image" src="https://github.com/user-attachments/assets/fead0894-6933-4012-ba40-354bcef294b9">

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9680
