### ISSUE TITLE
is:issue is:open The document cannot be indexed 

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#10097]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I would like to ask if we can add a knowledge base through the DIY API interface in the backend of DIY. However, when calling the interface, we found that the document cannot be indexed. I don't know what caused this and I need some help. Thank you
![图片](https://github.com/user-attachments/assets/f96ab816-9149-4e4b-9b18-367d421105c8)

### ❌ Actual Behavior

![图片](https://github.com/user-attachments/assets/13131b89-3c45-42f3-a920-173a4d2a195c)

**Comment by crazywoola** [comment]
Please provide the container logs.

**Comment by guxiyang** [comment]
Hello, we clicked on the document in the knowledge base and found an error prompt, [tongyi] Error: Response output is missing or
We are not sure if this is a problem with tongyi, as shown in the picture






***@***.***
 
From: dosubot[bot]
Date: 2024-10-31 11:10
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] is:issue is:open The document cannot be indexed (Issue #10097)
I found some relevant information that might help with your issue regarding document indexing in Dify.
Adding a Knowledge Base: You can add a knowledge base through the DIY API interface in the backend of DIY. However, there are several reasons why a document might not be indexed:
The knowledge base might still be initializing or indexing, indicated by the error dataset_not_initialized.
The document might be in the process of being indexed, shown by the error document_indexing.
The document might have already been processed, indicated by document_already_finished.
The operation might only be supported for "high-quality" knowledge bases, as indicated by high_quality_dataset_only.
Ensure that documents or chunks are not disabled or archived, as these will not be indexed [1][2].
Indexing Process: The document indexing process involves several state transitions, such as "parsing", "splitting", and "indexing". If any issues occur, the document's status is set to "error", and the error message is recorded. Ensure that the document is correctly formatted and submitted according to the API's requirements [3][4].
Similar Issues: There is a similar open issue discussing the inability to parse context when using the DIY API interface [5]. Additionally, a closed issue suggests that segments added using the knowledge base API are not automatically indexed and need to be explicitly enabled for indexing [6].
To resolve the issue, ensure that the document is enabled for indexing and check the document's status and error messages for more specific guidance.
To continue talking to Dosu, mention @dosu.
