### ISSUE TITLE
希望openai 的向量接口调用可以支持 OPENAI_API_BASE

### ISSUE THREAD

**Issue by leochen-g** [langgenius/dify#1010]
**Is your feature request related to a problem? Please describe.**
在docker yaml 里设置了OPENAI_API_BASE 后，调用向量化接口 发现用的还是默认的api.openai.com 这个，并不是OPENAI_API_BASE 的值

**Describe the solution you'd like**
希望能够复用 OPENAI_API_BASE，这样在本地或者无法访问外网的服务器也可以调用向量接口

**Comment by JohnJyong** [comment]
The embedding operation is called in the worker service. Please configure the same variables in the worker service.

**Comment by leochen-g** [comment]
My mistake.
