### ISSUE TITLE
Add option for custom API inference in embeddings model provider option .

### ISSUE THREAD

**Issue by ahsan123322** [langgenius/dify#10114]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [ ] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes . I'm finding challenges , I want to use Arabic embedding model but all embedding model provider are either paid or not supporting sentence transformer architecture . 

### 2. Additional context or comments

I wanted to host the model on my PC and use that API option in the embedding provider option as "Custom embedding model" . add server url there and model name and can easily hit then . 

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Have you tried Ollama or Xinference?

**Comment by ahsan123322** [comment]
Ollama have limited embedding models in their registry . and not supporting any sentence transformers architecture models yet . didn't tried Xinference because no integration in Dify yet in model providers section .
