### ISSUE TITLE
Invalid upload file by api

### ISSUE THREAD

**Issue by lem1272536013** [langgenius/dify#10125]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm using the official documentation API for uploading files and upload-based file conversations, but I'm having a problem, and I've made sure that the "usr" is the same, and the app has turned on file uploads, but it should show invalid files. 

### ✔️ Expected Behavior

return success

### ❌ Actual Behavior

{
"code": "invalid_param",
"message": "Invalid upload file",
"status": 400
}

**Comment by lem1272536013** [comment]
I wonder what is the reason for this, is there a problem with my code or some other possible issue

**Comment by crazywoola** [comment]
Please paste your payload as well. This isn't helpful to identify this issue.

**Comment by lem1272536013** [comment]
> Please paste your payload as well. This isn't helpful to identify this issue.

The issue was fixed, it was a problem with my own code, and I didn't notice that the format of the response had also changed, which caused this issue
