### ISSUE TITLE
api bug!'/chat-messages' does not support ' parent_message_id ', resulting in a lack of functionality to modify historical messages in the conversation

### ISSUE THREAD

**Issue by glacierck** [langgenius/dify#10124]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

curl -X POST 'http://192.168.1.210/v1/chat-messages' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "historical message",
    "response_mode": "streaming",
    "conversation_id": "64e25005-442f-41aa-97e3-f3e282e5a918",
    "parent_message_id":"ms-2",
    "user": "abc-123"
}'

### ✔️ Expected Behavior

Restart the conversation from message ID "ms-2".

### ❌ Actual Behavior

Continue the conversation with the last message(id:ms-10) in the conversation.

**Comment by glacierck** [comment]
@dosu Suggest replying with support for 'parent_message_id' and reopening the ability to modify historical messages!

**Comment by crazywoola** [comment]
Please don't open duplicate questions.

**Comment by glacierck** [comment]
@crazywoola Where do you see the same issue? Please take my question seriously and have reviewed your recovery before closing. https://github.com/langgenius/dify/issues/10121 Are you sure you're responding to the question I asked？

**Comment by glacierck** [comment]
@dosu They have turned off 'parent_message_id' in the new version

**Comment by glacierck** [comment]
> #10121 请不要打开重复的问题。如果您继续这样做，我们将禁止您访问此 repo。感谢您的合作。

Your hasty and repetitive closures have annoyed me

**Comment by crazywoola** [comment]
> > #10121 Please don't open duplicate questions. If you continue doing this, we will ban you from this repo. Thanks for your cooperation.
> 
> Your hasty and repetitive closures have annoyed me

We took your issues seriously, please review the issue histories, ddi we solved most of them? And you do not even star us :)

**Comment by Qiuzg** [comment]
Why "parent_message_id" was deleted, I didn't find any explanation
