### ISSUE TITLE
How to regenerate the message if 'parent_message_id' is not supported

### ISSUE THREAD

**Issue by glacierck** [langgenius/dify#10121]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need an API！I need to modify the historical messages in the conversation to generate new answers from the specified historical messages and restart the conversation from the specified message records.

### 2. Additional context or comments

The existing official chat supports this effect, but the API is missing and does not support it.
Message regeneration function:
![image](https://github.com/user-attachments/assets/175d288b-18ba-4b99-b9b4-9c5630f8ffd8)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by glacierck** [comment]
@crazywoolala  Please reopen my issues, your answer is incorrect. https://github.com/langgenius/dify/issues/10124 . This is beneficial in reducing the occurrence of similar issues

**Comment by crazywoola** [comment]
Here are the duplicated questions.

https://github.com/langgenius/dify/issues/10115
https://github.com/langgenius/dify/issues/10124

**Comment by glacierck** [comment]
@crazywoola Thank you for your understanding, I apologize for my recklessness. Upgrading will improve the issue, so I should also close this topic.

**Comment by crazywoola** [comment]
You are welcome. :)

**Comment by cygithub-22** [comment]
> @crazywoola Thank you for your understanding, I apologize for my recklessness. Upgrading will improve the issue, so I should also close this topic.

What‘s the solution to this issue? Upgrading did not work.

**Comment by f1025211271** [comment]
I encountered the same problem. When using the service api v1/chat-messages, there is no "parent_message_id" field, so I cannot ask a question again based on a historical message. I sincerely hope that this function will be added as soon as possible.
