### ISSUE TITLE
Error message received when I upload PDF

### ISSUE THREAD

**Issue by Rain-H** [langgenius/dify#10127]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.10.2 

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I upload a file (a PDF file with picture and text) to knowledge, it will give me the error message like below 
<img width="1462" alt="Screenshot 2024-10-31 at 5 55 31 PM" src="https://github.com/user-attachments/assets/3a38d811-8a0d-44a6-b38a-6ca96328ae45">

### ✔️ Expected Behavior

Preprocess and clean my document. 

### ❌ Actual Behavior

error message

**Comment by JohnJyong** [comment]
thanks for your feedback, this issue will be fixed with the linked pr .
