### ISSUE TITLE
http_request node load json bug

### ISSUE THREAD

**Issue by lyq518** [langgenius/dify#10133]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![1730377529446](https://github.com/user-attachments/assets/0b37d2c7-12c4-4776-9dac-edff5cc5e3f0)
Sometimes an error occurs when the json data contains line breaks, which did not exist in previous versions.

### ✔️ Expected Behavior

![1730377733931](https://github.com/user-attachments/assets/c96c18c4-a9dc-4679-9a7e-219965b29060)

**Comment by nne998** [comment]
+ bug
