### ISSUE TITLE
Dify Workflow Orchestrate can not be load when I update version from 0.7.3 to 0.10.2

### ISSUE THREAD

**Issue by alieninsect** [langgenius/dify#10138]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/295ef7b0-7243-473b-b9e1-18d2d95b98de)

**Comment by crazywoola** [comment]
I think this picture isn't enough to investigate this issue. If you encounter a 400 error, you can paste the call as cURL comand here.

**Comment by alieninsect** [comment]
> I think this picture isn't enough to investigate this issue. If you encounter a 400 error, you can paste the call as cURL comand here.

https://xxxxxxxxx.com/console/api/apps/01965c72-cc1b-4b6d-99db-c150a49919b1/workflows/draft

**Comment by alieninsect** [comment]
![image](https://github.com/user-attachments/assets/3c4e2883-b352-403e-8685-5a17dfa81779)
I found this function return DraftWorkflowNotExit() , and the discription is Draft workflow need to be initialized.  I guess when I create chatflow , and default workflow can not be initialized.

**Comment by crazywoola** [comment]
I think this is related to the version mismatch, this happens when you upgrade from older version to latest version, we will introduce the version check feature later.

**Comment by qqlww1987** [comment]
Version 15.3 also has this problem, how to solve it

**Comment by sunhao222** [comment]
I also have this question
