### ISSUE TITLE
The application released to the outside world cannot be used, prompt:ToolFile None not found

### ISSUE THREAD

**Issue by jaxonister** [langgenius/dify#10149]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/bf68a823-ef27-4a5c-b469-76a723c1b767)
![image](https://github.com/user-attachments/assets/8f00ec4b-423e-426e-ad02-2912c9c69ab2)

url:/api/messages?conversation_id=f23f78db-5f68-4c32-9ee5-6c0d33ad4a29&limit=20&last_id=

{code: "invalid_param", message: "ToolFile None not found", status: 400}

### ✔️ Expected Behavior

Can be used normally

### ❌ Actual Behavior

ToolFile None not found

**Comment by crazywoola** [comment]
Please upgrade to v0.10.2 to see if this persists.

**Comment by crazywoola** [comment]
> Can the update to 0.10.2 solve the problem? What is the reason for the error? @crazywoola

You can try it out. 
If you want to know the reason, you can checkout the commits.
