### ISSUE TITLE
Error using large language model

### ISSUE THREAD

**Issue by zhizhuaa** [langgenius/dify#10147]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Using a large language model to conduct a conversation results in an error, the specific error content is as follows:

![Snipaste_2024-11-01_08-35-54](https://github.com/user-attachments/assets/f765c5fa-d0db-4b02-8249-91aa157f1aad)

**Comment by crazywoola** [comment]
Try to adjust the max_tokens in the configuration panel to a smaller value. :)
