### ISSUE TITLE
azure embedding Too many inputs problem

### ISSUE THREAD

**Issue by CruelFatOtaku** [langgenius/dify#1015]
Update to the newest version and the embedding failed.
I think the bug was fixed before bug it show again. May caused by the change of the folder structure.

<img width="1458" alt="image" src="https://github.com/langgenius/dify/assets/58169901/056b45de-1887-4cb8-b45a-3af914aae9f0">

**Comment by CruelFatOtaku** [comment]
I found this issue but the fix code was lost in the code.
> #522

**Comment by takatost** [comment]
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#embeddings
https://github.com/langgenius/dify/blob/1c114eaef30de0369236fb29f8cc72baf2ad01f3/api/core/model_providers/models/embedding/azure_openai_embedding.py#L27

I've already followed the rule of setting the Azure OpenAI Embedding batch size to 16 on my end. It seems fine. Could you provide more information to help identify the issue?

**Comment by CruelFatOtaku** [comment]
May because of using old version api. I deployed the new version and the error was fixed
