### ISSUE TITLE
[openai] Error: Completions.create() got an unexpected keyword argument 'json_schema' 

### ISSUE THREAD

**Issue by genru** [langgenius/dify#10168]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

LLM node, select gpt-4o-mini mode(azure version) with `json_schema`, setting `response format` as `json_object` as well.

belowing is the schema
```js
{
    "name": "sences",
    "description": "generate sences from scripts",
    "strict": true,
    "schema": {
        "type": "object",
        "properties": {
            "prompts": {
                "type": "array",
                "items": {
                    "name": "prompt",
                    "type": "string",
                    "description": "prompts text"
                }
            }        
        },
        "required": ["prompts"],
        "additionalProperties": false
    }
}
```

when run this node will cause this issue.

i also attached the parameters for your reference.
<img width="370" alt="image" src="https://github.com/user-attachments/assets/ce00d82a-58a1-4f59-81ca-dde800b3b449">

### ✔️ Expected Behavior

run llm node successfully. I noticed the #8451, but this issue seems to remain.

### ❌ Actual Behavior

`[openai] Error: Completions.create() got an unexpected keyword argument 'json_schema' ` displayed.

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/issues/8994#issuecomment-2395359831 as well.

**Comment by hjlarry** [comment]
you should set `response_format` to `json_schema` to make it works.
and if we raise clear error in this situation maybe better

**Comment by genru** [comment]
thanks @crazywoola. yes, i met the same issue, it seems caused by azure? i wonder if there is any solution or workaround for it?

@hjlarry I think I have set `response_format`, as I attached the settings screenshot shows, or I missed anything?

**Comment by hjlarry** [comment]
> @hjlarry I think I have set `response_format`, as I attached the settings screenshot shows, or I missed anything?

in your screenshot,  you set `response_format` to `json_object` not `json_schema`

**Comment by genru** [comment]
@hjlarry thanks so much, you made my day. it's my bad, it works now.

thanks guys. issue closed
