### ISSUE TITLE
In application orchestration, model parameter selection does not take effect

### ISSUE THREAD

**Issue by jlokys** [langgenius/dify#10167]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Parameter selection is not saved
![image](https://github.com/user-attachments/assets/179c74a4-2f90-43b5-956a-cd1f03484ed5)

**Comment by crazywoola** [comment]
If they are not checked, they will be ignored.
