### ISSUE TITLE
Edit Agent Instructions/Prompt After Starting Multiple Conversations

### ISSUE THREAD

**Issue by ketchalegend** [langgenius/dify#10164]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

At the moment, when I start multiple conversations using the API and later edit the agent prompt, it is not updated in the individual conversations. For example, if before the conversation starts with the prompt "You're selling books", I start a conversation and then later on, while I'm in the conversation using the API endpoint, I go back in the instruction and change the prompt to "You're selling shoes". The conversation is not updated to use the new prompt.

The conversation doesn't know about a new prompt; it still uses the old prompt.

### Steps to Reproduce
Start multiple conversations using the API with an initial prompt (e.g., "You're selling books").
Edit the agent prompt to a new prompt (e.g., "You're selling shoes") while the conversations are active.
Observe if the conversations use the new prompt.

### ✔️ Expected Behavior

Active and old conversations should use the updated prompt.

### ❌ Actual Behavior

Active and old conversations continue to use the old prompt, not reflecting the updated instructions.

**Comment by crazywoola** [comment]
The newly edit of prompts and other configurations only applies for the new conversation in this case, things will happen.

**Comment by ketchalegend** [comment]
@crazywoola is there a possibilty to make it apply to older conversations too? Cause that means i will have to delete all users conversations everytime i make changes to the prompt, which will ofcourse mean that the context is gone.
