### ISSUE TITLE
File field _extra_config can not be initialized on constructor

### ISSUE THREAD

**Issue by zhuqingchao** [langgenius/dify#10179]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/31b16199-6e12-416f-b3fe-79f442a5d324)
the _extra_config field can not be rightly initialized with pydantic.
so some extra_config  like the image detail will lose in the file_factory.py. below here:
![image](https://github.com/user-attachments/assets/9c4a877a-ec44-41df-b5e7-a5c7d91cec21)

add a constructor for File class may solve this problem
![image](https://github.com/user-attachments/assets/5b5c41b4-3313-458b-a10c-d3d21ea875cf)
```
def __init__(self, **data):
        super().__init__(**data)
        self._extra_config = data.get("_extra_config")
```

### ✔️ Expected Behavior

rightly initialized

### ❌ Actual Behavior

_extra_config is missing

**Comment by laipz8200** [comment]
Could you share more detailed screenshots of the input and output? From your image, it shows `_extra_config` is explicitly assigned in file_factory.
