### ISSUE TITLE
configure firecrawl and got "Expecting value: line 3 column 1 (char 4)" when crawl

### ISSUE THREAD

**Issue by TChengZ** [langgenius/dify#10171]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/aebba49d-0b95-4ddb-aa58-4a1990ad47b2)
i configure the firecrawl(self-hosted) and start crawling,but got error like above "Expecting value: line 3 column 1 (char 4)" 

### ✔️ Expected Behavior

crawl successful,not error

### ❌ Actual Behavior

"Expecting value: line 3 column 1 (char 4)"

**Comment by crazywoola** [comment]
This version is outdated, please upgrade to our latest version.
