### ISSUE TITLE
Missing Essential Feature: Edit or Delete Conversations for Regeneration

### ISSUE THREAD

**Issue by liuquanqing** [langgenius/dify#10184]
![image](https://github.com/user-attachments/assets/0df96c2e-9552-4568-9f02-69dec8ab7eed)
![image](https://github.com/user-attachments/assets/f405e33f-32b5-444b-9c4a-bc65ab09b286)
![image](https://github.com/user-attachments/assets/3afa4fe6-81d7-4a4d-a6e3-360d40872655)

This need to re-edit the previous input is extremely common. Even simpler solutions support deleting entries, and many lightweight open-source products include this feature. It’s surprising that Dify lacks it. Have you actually held long-term conversations with AI？ Or does every response it generates perfectly meet your needs, making revisions unnecessary?

_Originally posted by @liuquanqing in https://github.com/langgenius/dify/issues/5394#issuecomment-2452286935_

**Comment by crazywoola** [comment]
Please use the template to open the issue.
