### ISSUE TITLE
Run branches in parallel will cause some problem.

### ISSUE THREAD

**Issue by Hope1u** [langgenius/dify#10181]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The normal situation is as follows
![1](https://github.com/user-attachments/assets/81dfeddd-e4fd-4c11-a02e-f5a2037ed2c3)

The error conditions are as follows:
When I add any more node before merging the two branches, after the other branches are completed, the merged node will be taken.
![iShot_2024-11-01_18 17 16](https://github.com/user-attachments/assets/21a48f88-d94d-49fb-8b3f-2a9db9fee66f)

### ✔️ Expected Behavior

There are 3 branches. The entire process should end after completing branch 1.

### ❌ Actual Behavior

There are three branches, branch 1, branch 2 and branch 3. Branch 2 and branch 3 are merged. Normally, it should be over after taking branch 1. However, before branch 2 and branch 3 are merged, if there is any more node, it will As a result, after branch 1 ends, it will automatically jump to the merge node and continue.

**Comment by Hope1u** [comment]
You seem to have misunderstood the meaning. It has nothing to do with the variable aggregator. This problem will occur when any other nodes are added before merging two branches, as follows:
There are three parameters. When test1 is not empty, branch 1 is taken. When q is not empty, branch 2 is taken. When w is not empty, branch 2 is taken. Branch 2 and branch 3 are merged. When testing, I assign test1 to 1, and the q and w parameters are not assigned values.
When there are no redundant nodes before merging nodes, the entire process ends after branch 1 is completed, as follows:
![image](https://github.com/user-attachments/assets/ea17c911-2c21-40ea-b218-c7d7a666c193)

When there is an additional node before the merge node, after completing branch 1, the merge node will continue to be taken, as follows:
![image](https://github.com/user-attachments/assets/a73d46a2-98ac-47ac-aef5-dde08021344b)

As long as you add any more nodes before merging them, this will happen:
For example, there are no redundant nodes before merging nodes.
![image](https://github.com/user-attachments/assets/5f472eb6-7664-46ac-aaf2-40aac6220908)
![image](https://github.com/user-attachments/assets/2d1ab3e4-39ec-41da-8c27-50a68f515fb8)

There are redundant nodes
![image](https://github.com/user-attachments/assets/ba95cf5c-b635-4d7b-8c98-6650c2e20e1c)
In fact, when I assign test1 to 1, branch 1 should be taken. At the same time, q and w are empty, then branch 2 and branch 3, these two conditional judgments should be over, so branch 1 is completed, and the entire process It should all end.

**Comment by yihong0618** [comment]
can you offer your dsl?
