### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by xfanwu** [langgenius/dify#10199]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Cloud latest

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I have no idea what happens.

### ✔️ Expected Behavior

Access to my app.

### ❌ Actual Behavior

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/fffce7c6-d3fb-4151-83ff-d66469e13c32">

here is my app's link if it helps:

https://cloud.dify.ai/app/ee01683d-f4f2-427b-aa9a-9b019c308e49/workflow

Could you please restore my app? I spent days working on it!

**Comment by xfanwu** [comment]
> Please attach the exported DSL here.

@crazywoola Please see attached DSL.

[_Playground.txt](https://github.com/user-attachments/files/17606807/_Playground.txt)

**Comment by songxiaoxiao** [comment]
怎么解决。最新版v0.15.3 也有这个问题

**Comment by Kmozhiren** [comment]
是浏览器问题，换了个版本高的浏览器就可以了

**Comment by hczs** [comment]
Same problem
