### ISSUE TITLE
 Error When Creating Knowledge: "rules" Error Prevents Chunk Preview

### ISSUE THREAD

**Issue by MitraSafarinejad** [langgenius/dify#10204]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am encountering an issue with Dify version 0.10.2 when attempting to create Knowledge. After uploading a file, I receive an error message indicating a "rules" error. Despite the error, the file upload completes successfully. However, the chunk preview does not display as expected. Here are the details of the error:

![image](https://github.com/user-attachments/assets/fc4229f5-d09b-4eb9-8c44-852903585ff1)

Error Message:
`[{"code": "indexing_estimate_error", "message": "'rules'", "status": 500}]`

The relevant logs are:
```
Traceback (most recent call last):
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1         |     rv = self.dispatch_request()
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1         |     resp = resource(*args, **kwargs)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1         |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1         |     resp = meth(*args, **kwargs)
api-1         |   File "/app/api/controllers/console/wraps.py", line 142, in decorated
api-1         |     return view(*args, **kwargs)
api-1         |   File "/app/api/libs/login.py", line 92, in decorated_view
api-1         |     return current_app.ensure_sync(func)(*args, **kwargs)
api-1         |   File "/app/api/controllers/console/wraps.py", line 26, in decorated
api-1         |     return view(*args, **kwargs)
api-1         |   File "/app/api/controllers/console/datasets/datasets.py", line 464, in post
api-1         |     raise IndexingEstimateError(str(e))
api-1         | controllers.console.datasets.error.IndexingEstimateError: 500 Internal Server Error: 'rules'
```

### ✔️ Expected Behavior

After uploading a file, the system should successfully complete the process and display the chunk preview without any errors.

### ❌ Actual Behavior

While the file is uploaded successfully, an error message related to "rules" appears, and the chunk preview is not displayed as it should be

**Comment by JohnJyong** [comment]
fixed by #10258
