### ISSUE TITLE
Knowledge Base Embedding Indexing Process Stops Unexpectedly in Version 0.10.2

### ISSUE THREAD

**Issue by lukefan** [langgenius/dify#10209]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create a new knowledge base.
Upload 300 PDF documents from the internet in one go.
While indexing, add another 300 PDF documents in two separate batches.
Use the SiliconFlow NetEase embedding model for embeddings.
weaviate vector database

### ✔️ Expected Behavior

finish all progress.

### ❌ Actual Behavior

After some time, the indexing process stops. At this point:

Some documents are successfully indexed.
Some documents are skipped.
Others remain in the queue.
If I manually stop and restart the indexing process for documents stuck in the "indexing" status, they complete indexing normally.

**Comment by lukefan** [comment]
Suggested Solution:
Please consider implementing a feature that allows manual management of the document status within the knowledge base. This would help in cases where certain documents get stuck during the indexing process.

**Comment by lukefan** [comment]
I have been using the knowledge base feature and have encountered some issues. After uploading a large number of documents to the knowledge base, especially when multiple people are using it simultaneously, it is difficult to avoid indexing errors.
Currently, although it is possible to pause and resume documents one by one, this is unacceptable for a knowledge base with thousands of documents. I have resorted to using the dify API to read the document status and then use puppeteer to automatically pause and then resume all documents that are pending in the indexing state. However, this process is also unacceptable.
Therefore, I request a status check and reset function for the entire knowledge base. This would greatly improve the usability and efficiency of managing large knowledge bases.
Also, I would like to ask for some advice. What is a good limit for the number of documents in a knowledge base? For example, if there are 10,000 documents, should they be placed in one knowledge base or divided into 10 knowledge bases?
Looking forward to your response and solutions.

**Comment by JohnJyong** [comment]
could you pls provide error logs of the unexpected stop? 
emmm, we have the retry funtion in the knowledge 
![image](https://github.com/user-attachments/assets/dfe67f70-ccff-47d9-8484-f0c7c1b45bc4)
 @lukefan

**Comment by JohnJyong** [comment]
If you have any doubts， pls reopen the issue ， thanks
