### ISSUE TITLE
502 Bad Gateway for brand new installation

### ISSUE THREAD

**Issue by TianzeWang** [langgenius/dify#10227]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.10.2 - Main UTC+8 (Nov.4 12:48PM)

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I followed exactly the same to update the code and initially encountered this error. To exclude the issues of my local configuration, I created a new folder and git cloned a new copy of dify, and same issue still persists.

2. Git clone dify main
3. CD docker, cp .env
4. Mac Desktop Docker updated to latest version
5. docker compose up -d

### ✔️ Expected Behavior

Docker normally start up 

### ❌ Actual Behavior

Docker showed 502 bad gateway 
<img width="829" alt="image" src="https://github.com/user-attachments/assets/e9d9c751-97b3-4c7c-a4a7-16951781ec82">

**Comment by TianzeWang** [comment]
I have repeated the same, same issue still persists.

**Comment by TianzeWang** [comment]
However I noticed that the worker and api shows multiple ip address. Not sure if this is causing the problem.
<img width="578" alt="image" src="https://github.com/user-attachments/assets/d94b6355-9262-4657-b955-44eed8329d95">

**Comment by crazywoola** [comment]
Please check the container logs, we discovered a strange behavior that you need to wait for several minutes to start the container.

**Comment by fivehanz** [comment]
I seem to have same issue, however I am using with docker swarm.

**Comment by Jackytfy** [comment]
> However I noticed that the worker and api shows multiple ip address. Not sure if this is causing the problem.但是，我注意到 worker 和 api 显示多个 IP 地址。不确定这是否是导致问题的原因。 <img alt="image" width="578" src="https://private-user-images.githubusercontent.com/28721734/382643961-d94b6355-9262-4657-b955-44eed8329d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMTk2MzYsIm5iZiI6MTc0MDAxOTMzNiwicGF0aCI6Ii8yODcyMTczNC8zODI2NDM5NjEtZDk0YjYzNTUtOTI2Mi00NjU3LWI5NTUtNDRlZWQ4MzI5ZDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjIwVDAyNDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTU0OTFkZDMyYTU2ODIyOTFmMTYyZTAwNmZjNzQwMTc2ZjJiODFmN2FjMDhmMGIxMzA3NDI0MWUyMjU1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XsUZY_iVaC9UbC9zHGqRipt3K7Srhw7PClwnKOWRcjY">

这中多个的情况是如何解决的？

**Comment by Jackytfy** [comment]
> However I noticed that the worker and api shows multiple ip address. Not sure if this is causing the problem.但是，我注意到 worker 和 api 显示多个 IP 地址。不确定这是否是导致问题的原因。 <img alt="image" width="578" src="https://private-user-images.githubusercontent.com/28721734/382643961-d94b6355-9262-4657-b955-44eed8329d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMTk2MzYsIm5iZiI6MTc0MDAxOTMzNiwicGF0aCI6Ii8yODcyMTczNC8zODI2NDM5NjEtZDk0YjYzNTUtOTI2Mi00NjU3LWI5NTUtNDRlZWQ4MzI5ZDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjIwVDAyNDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTU0OTFkZDMyYTU2ODIyOTFmMTYyZTAwNmZjNzQwMTc2ZjJiODFmN2FjMDhmMGIxMzA3NDI0MWUyMjU1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XsUZY_iVaC9UbC9zHGqRipt3K7Srhw7PClwnKOWRcjY">

这中多个的情况是如何解决的？

> However I noticed that the worker and api shows multiple ip address. Not sure if this is causing the problem. <img alt="image" width="578" src="https://private-user-images.githubusercontent.com/28721734/382643961-d94b6355-9262-4657-b955-44eed8329d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMjE5MTAsIm5iZiI6MTc0MDAyMTYxMCwicGF0aCI6Ii8yODcyMTczNC8zODI2NDM5NjEtZDk0YjYzNTUtOTI2Mi00NjU3LWI5NTUtNDRlZWQ4MzI5ZDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjIwVDAzMjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMjEyZDBmNzU4NWIxYTA3YzJkOGYxOGZlMGE5ZTYxYTVhMThkMjBiZjdmMjkwNDA1Y2EyMWZlMDU2MGU5ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lvDG9eyilvH_XNMACyQLZnHErDZ5iJONdPDAswTB-5M">

这种多个的情况是如何处理的
