### ISSUE TITLE
Add an Edit Message Feature

### ISSUE THREAD

**Issue by MitraSafarinejad** [langgenius/dify#10223]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I would like to request the addition of an **edit message feature** that allows users to edit their messages after sending them to the LLM model, similar to what ChatGPT offers. This would enable users to revise their messages and resend the updated version if they made a mistake or want to change something. Implementing this feature would significantly enhance the user experience by providing more control over their interactions.

### 2. Additional context or comments

![image](https://github.com/user-attachments/assets/9bbd3a4c-33fe-4cc1-a474-ac01d4c7f3b3)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/10186
