### ISSUE TITLE
chat-messages API for file upload

### ISSUE THREAD

**Issue by JiesenSun** [langgenius/dify#10220]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Test the chat-messages api according to the documentation, and invalid_param error always exists. Please see the attached picture.
<img width="1358" alt="image" src="https://github.com/user-attachments/assets/b56ff141-fcc7-4c4f-bd3d-da7e14a4f6f1">
![b](https://github.com/user-attachments/assets/8053febb-b1e6-4f54-acae-84db580ecb62)

**Comment by MitraSafarinejad** [comment]
I am experiencing a similar issue after updating to version 0.10.2. When I attempt to upload an image, I consistently receive the following error message:

```
{
  "code": "unsupported_file_type",
  "message": "File type not allowed.",
  "status": 415
}

```
This error occurs regardless of the image file type I try to upload. I have verified that the images I am attempting to upload are in a supported format (such as .jpg and .png). Despite this, the API rejects my uploads with the unsupported file type error.

Here's my curl command: 
```
curl --location '.../v1/files/upload' \
--header 'Authorization: Bearer ' \
--form 'file=@"/home/Pictures/images.jpeg"'
```

**Comment by JiesenSun** [comment]
> Hey @JiesenSun! 👋 I'm here to help you with bugs, questions, and becoming a contributor. If you need assistance, feel free to ask!
> 
> I found a similar issue regarding the "invalid_param" error when using the chat-messages API for file uploads in Dify version 0.10.2 on a self-hosted Docker setup. To resolve this issue, ensure that you are correctly using the `transfer_method` and providing the necessary parameters based on the method chosen.
> 
> For file uploads, use the `local_file` transfer method and provide the `upload_file_id` obtained from the File Upload API. Here’s a brief guide:
> 
> 1. **Upload the File**: Use the File Upload API with a `multipart/form-data` request, including the file and a unique user identifier.
>    Example cURL command:
>    ```shell
>    curl -X POST '${props.appDetail.api_base_url}/files/upload' \
>    --header 'Authorization: Bearer {api_key}' \
>    --form 'file=@"/path/to/file"' \
>    --form 'user=abc-123'
>    ```
> 2. **Use the File ID**: After uploading, the server returns a file ID. Use this ID in your chat-messages API request.
> 3. **Make the Chat-Messages API Request**: Use the `local_file` transfer method and include the `upload_file_id`.
>    Example JSON payload:
>    ```json
>    {
>        "inputs": {},
>        "query": "What are the specs of the iPhone 13 Pro Max?",
>        "response_mode": "streaming",
>        "conversation_id": "",
>        "user": "abc-123",
>        "files": [
>            {
>                "type": "image",
>                "transfer_method": "local_file",
>                "upload_file_id": "72fa9618-8f89-4a37-9b33-7e1178a24a67"
>            }
>        ]
>    }
>    ```
> 
> Ensure all parameters are correctly set and the file ID is valid. Verify that the `response_mode` is set correctly as either `blocking` or `streaming` [[1]](https://github.com/langgenius/dify/blob/main/web/app/components/develop/template/template_chat.en.mdx)[[2]](https://github.com/langgenius/dify/blob/main/web/app/components/develop/template/template_advanced_chat.en.mdx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

The second method in the attached picture in the original text uses the same method as yours, but still reports an error. My scenario here is a document dialogue, not a picture dialogue.
<img width="689" alt="image" src="https://github.com/user-attachments/assets/ec0214d4-94c7-4fd5-bc44-7b4aa5b2b799">

**Comment by Allamss** [comment]
> I am experiencing a similar issue after updating to version 0.10.2. When I attempt to upload an image, I consistently receive the following error message:
> 
> ```
> {
>   "code": "unsupported_file_type",
>   "message": "File type not allowed.",
>   "status": 415
> }
> ```
> 
> This error occurs regardless of the image file type I try to upload. I have verified that the images I am attempting to upload are in a supported format (such as .jpg and .png). Despite this, the API rejects my uploads with the unsupported file type error.
> 
> Here's my curl command:
> 
> ```
> curl --location '.../v1/files/upload' \
> --header 'Authorization: Bearer ' \
> --form 'file=@"/home/Pictures/images.jpeg"'
> ```

@dosu

**Comment by crazywoola** [comment]
Related https://github.com/langgenius/dify/issues/10327
Should be fixed in https://github.com/langgenius/dify/pull/10353

**Comment by simonlee2** [comment]
thanks for the fix. is there an eta for the next release?

**Comment by crazywoola** [comment]
Maybe in next week @simonlee2
