### ISSUE TITLE
use of the sys.files variable on other nodes

### ISSUE THREAD

**Issue by G81192** [langgenius/dify#10235]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

My issue is similar to #7260. I see that issue #7260 has been closed, but I find that the problem still exists. I am unable to use the sys.files variable on other nodes, and I'm not sure if this is due to my configuration or if this feature is still unsupported.
![image](https://github.com/user-attachments/assets/53020f83-b3a2-42a1-8050-2d6e19e704cf)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by G81192** [comment]
and I’m currently using the latest version (0.10.2)

**Comment by G81192** [comment]
I have a scenario where I need to create a custom tool to recognize QR code information from uploaded images. How can I access the uploaded image file in the tool?

**Comment by crazywoola** [comment]
Currently, I don't think we can do this, all images's preview are presigned and they will be outdated in a very short time. I have already talk to our dev team regarding this issue. I suggest you can use HTTP to upload to other OSS storage and return a url instead.

**Comment by G81192** [comment]
> Currently, I don't think we can do this, all images's preview are presigned and they will be outdated in a very short time. I have already talk to our dev team regarding this issue. I suggest you can use HTTP to upload to other OSS storage and return a url instead.

@crazywoola  Okay, I see that the HTTP request node can use the sys.files variable and upload files, which should solve my problem. Thank you
