### ISSUE TITLE
I can‘t login my local dify!

### ISSUE THREAD

**Issue by jeremygan2021** [langgenius/dify#10231]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

lastest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

My local server of dify right now is unable to access due to the '''Authentication method not configured

Please contact the system admin to add an authentication method.'''

I add my account already， but right now issue
![微信图片_20241104142548](https://github.com/user-attachments/assets/6049b57c-c82b-41c9-a79d-0adcfcdef003)
s that I can't access。I build this projects on docker-compose。

### ✔️ Expected Behavior

it is supposed to show my existing account。

### ❌ Actual Behavior

it shows that ''' Authentication method not configured

Please contact the system admin to add an authentication method.'''

**Comment by crazywoola** [comment]
Please check the environment variables, especially the `VERSION`
