### ISSUE TITLE
How to modify the user name in logs and annotations to a custom user name?

### ISSUE THREAD

**Issue by zhengjianping1010** [langgenius/dify#10232]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Upon reviewing the access log records, it was found that the usernames were randomly generated. This is not convenient for management.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by zhengjianping1010** [comment]
We are using the community version.
After logging in to Dify, the usage record will display the logged in username.
However, in the running Dify webpage, the usage record will display a random username.

**Comment by zhengjianping1010** [comment]
![record](https://github.com/user-attachments/assets/f4bde4b3-3f59-49f7-b8c2-42d51758f0d5)

**Comment by crazywoola** [comment]
This template is meant for feature request, if you have a question please use the discussion instead.
