### ISSUE TITLE
fail on adding gitee.ai provider's token, as when haven't buy the model "Qwen2-7B-Instruct"

### ISSUE THREAD

**Issue by fchange** [langgenius/dify#10242]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

create a totally new acount on gitee.ai, create and copy a new access_token to dify, try to add provider on dify.

### ✔️ Expected Behavior

add provider done

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/e5670e92-bb8f-4ccc-8f06-5985bd19e2e6)

Credentials validation failed with status code 400

**Comment by crazywoola** [comment]
We use this model for validations.

https://github.com/langgenius/dify/blob/0ebd9856725e273621db5c7943a9e18e01991aeb/api/core/model_runtime/model_providers/gitee_ai/gitee_ai.py#L19-L20
