### ISSUE TITLE
There is no tidb database used, but this asynchronous task （create_tidb_serverless_task） will cause tens of millions of keys with the prefix (tidb_serverless_cluster_password:*) in redis, causing redis memory overflow.

### ISSUE THREAD

**Issue by wangiii** [langgenius/dify#10259]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Pull v0.10.2 and run it to reproduce

### ✔️ Expected Behavior

Environments that do not use this database should not perform this task.

### ❌ Actual Behavior

causing redis memory overflow.

**Comment by wangiii** [comment]
![image](https://github.com/user-attachments/assets/4fccd9e6-b83b-421a-846b-dc9c8e1880f8)

**Comment by JohnJyong** [comment]
In fact, we do not provide celery beat service, so celery's scheduled tasks will not be triggered. Of course, we will add task control switches in the next version to solve this problem. @wangiii
