### ISSUE TITLE
I'm using the `webscraper` component in my workflow, but it gives me an error.

### ISSUE THREAD

**Issue by starweavingdream** [langgenius/dify#10250]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm using the `webscraper` component in my workflow, but it gives me an error.The error message is as follows:
Run failed: Failed to invoke tool: 'gbk' codec can't encode character '\u30fb' in position 35658: illegal multibyte sequence.

**Comment by crazywoola** [comment]
Try using Jina.ai instead. If you want to resolve this issue, you may need to modify the code to recognize the GBK character encoding. Our `webscraper` is a lightweight solution which might not support all encodings. [StackOverflow](https://stackoverflow.com/questions/3218014/unicodeencodeerror-gbk-codec-cant-encode-character-illegal-multibyte-sequen)
