### ISSUE TITLE
Which model is qwen-max in the first picture in the second picture?

### ISSUE THREAD

**Issue by dosnshcu** [langgenius/dify#10269]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Which model is qwen-max in the first picture in the second picture?
![image](https://github.com/user-attachments/assets/d68687a0-2263-49c4-9b44-0dd0dcc7c06b)
![image](https://github.com/user-attachments/assets/89ac966c-f56e-4189-beb8-a92cd19ac89c)

**Comment by dosnshcu** [comment]
I need to request a model concurrency limit with the model vendor, but I'm not sure which model this refers to

**Comment by crazywoola** [comment]
Check the files in this folder 
https://github.com/langgenius/dify/blob/ecc951609d4988424bfba58094d6e256ae86144e/api/core/model_runtime/model_providers/tongyi/llm/qwen-coder-turbo-0919.yaml

Please use discussion to ask a question.
