### ISSUE TITLE
Is there any plan to increase the orchestration of front-end components?

### ISSUE THREAD

**Issue by wangzhen38** [langgenius/dify#10271]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to build a long doc writer app, which may need some sub-process being able to interacted with the user.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
How about using chatflow?

**Comment by wangzhen38** [comment]
> How about using chatflow?

Thanks for your suggestion, but all my projects are based on Dify.

**Comment by crazywoola** [comment]
I know, I mean the `Chatflow` in dify. I think you can use a question classifier before each question and let it determine how it should respond.
