### ISSUE TITLE
The questions generated by Follow-up are sometimes in Chinese , sometimes in English and sometimes a mixture of Chinese and English

### ISSUE THREAD

**Issue by wangyingle666** [langgenius/dify#10299]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

first. add Stduio -> Create from Blank -> add Chatbot
second. Features Enabled -> add Manager -> turn on Follow-up
![image](https://github.com/user-attachments/assets/1f723649-1905-4a9c-9689-bf9d4665df24)
Then. Talk to Bot "如何学习英文"
last. you can see it
![image](https://github.com/user-attachments/assets/89e6b8fb-b588-419f-837d-1b79e5077f3a)

please tell me how to solve the promble

**Comment by wangyingle666** [comment]
> To address the issue of Follow-up generating questions in a mixture of Chinese and English, you can ensure that the output language matches the language of the Assistant's latest response. This can be achieved by using the `SUGGESTED_QUESTIONS_AFTER_ANSWER_INSTRUCTION_PROMPT`:
> 
> ```python
> SUGGESTED_QUESTIONS_AFTER_ANSWER_INSTRUCTION_PROMPT = (
>     "Please help me predict the three most likely questions that human would ask, "
>     "and keeping each question under 20 characters.\n"
>     "MAKE SURE your output is the SAME language as the Assistant's latest response"
>     "The output must be an array in JSON format following the specified schema:\n"
>     '["question1","question2","question3"]\n'
> )
> ```
> 
> This prompt ensures that the follow-up questions are generated in the same language as the Assistant's latest response, thereby preventing a mixture of languages in the output [[1]](https://github.com/langgenius/dify/blob/main/api/core/llm_generator/prompts.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

What I mean is that by turning on "follow-up", the questions generated by association will sometimes be in English.

**Comment by crazywoola** [comment]
Duplidated
