### ISSUE TITLE
Object of type File is not JSON serializable

### ISSUE THREAD

**Issue by svcvit** [langgenius/dify#10300]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I would like the uploaded file to create a file.url, which I can then request in the sandbox to retrieve the file and process it through code.

My test code is as follows, mainly aiming to print out the file content.
![Xnip2024-11-05_16-58-50](https://github.com/user-attachments/assets/c10d319d-ada6-4052-9581-f353556eb397)

When I only test the code node and upload the file, this node runs fine.
![Xnip2024-11-05_16-58-26](https://github.com/user-attachments/assets/66940d36-68be-48a2-b672-5d39baac437a)

However, if I click on "Preview" and upload the file, I get an error: Object of type File is not JSON serializable.
![Xnip2024-11-05_16-58-41](https://github.com/user-attachments/assets/9ed099ce-5a8b-4c09-b64f-928ad9617c12)

**Comment by crazywoola** [comment]
Check the actual inputs to the code block.

**Comment by laipz8200** [comment]
`File` typed variable is not allowed in the Code node for now.

**Comment by lovingliferwj** [comment]
hi, I want to process an upload PDF file in Code node and perform OCR recognition by my own. When I pass the file parameter to the Code node,it throws an error 'Object of type File is not JSON serializable'. How can I achieve above function?
