### ISSUE TITLE
Failed to extract text from DOC/DOCX: "no relationship of type 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' in collection"

### ISSUE THREAD

**Issue by congziqi** [langgenius/dify#10305]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Upload the old DOCX format file or the link to the DOCX file.
Document extraction node error:Failed to extract text from DOC/DOCX: "no relationship of type 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' in collection"
![image](https://github.com/user-attachments/assets/e4b7d4b3-e546-4029-92d2-475fccacc75b)

### ✔️ Expected Behavior

no error

**Comment by crazywoola** [comment]
Can. you provide the DSL and the document?
