### ISSUE TITLE
File upload API cannot upload anything other than documents

### ISSUE THREAD

**Issue by fujita-h** [langgenius/dify#10327]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Create simple chatflow app.
2. Set up the start node to enable file upload.
3. Publish app.
4. Enable API access and create api key.
5. Upload image via `/v1/files/upload`.

### ✔️ Expected Behavior

The upload is successful.

### ❌ Actual Behavior

Retrun error:
```
{"code": "unsupported_file_type", "message": "File type not allowed.", "status": 415}
```

**Comment by fujita-h** [comment]
In the Files API, the following is passed to the File Service:
https://github.com/langgenius/dify/blob/d7b4d0756e8a538c582ee4d5a57f0830ec305c93/api/controllers/service_api/app/file.py#L39-L45

The following line will be executed because `source` is `datasets`.
https://github.com/langgenius/dify/blob/d7b4d0756e8a538c582ee4d5a57f0830ec305c93/api/services/file_service.py#L45-L46
This will cause anything other than the document file to be rejected.

These changes are from #9906.

**Comment by silverriver** [comment]
Why？Why not letting user to upload non-document?

> In the Files API, params are passed to the File Service:
> 
> https://github.com/langgenius/dify/blob/d7b4d0756e8a538c582ee4d5a57f0830ec305c93/api/controllers/service_api/app/file.py#L39-L45
> 
> The following line will be executed because `source` is `datasets`.
> 
> https://github.com/langgenius/dify/blob/d7b4d0756e8a538c582ee4d5a57f0830ec305c93/api/services/file_service.py#L45-L46
> 
> 
> This will cause anything other than the document file to be rejected.
> These changes are from #9906.
