### ISSUE TITLE
Workflow fails to function with multiple file-type input fields

### ISSUE THREAD

**Issue by kurokobo** [langgenius/dify#10326]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2, 0.11.0

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

1. Create new Workflow app
2. On the Start node, add new Single File input filed: `file1`
3. On the Start node, add another Single File input field: `file2`
4. Add End node
6. Publish the app
7. Run the app
8. Upload any image into both `file1` and `file2`
9. Press `Execute` button

**Live demo**: https://udify.app/workflow/YBbpT8TziPpIvKjx
**DSL file**: [upload file to workflow.txt](https://github.com/user-attachments/files/17633555/upload.file.to.workflow.txt)

### ✔️ Expected Behavior

Both files are sent to the app, and the workflow returns empty result with success.

### ❌ Actual Behavior

The error `file1 value can not be empty` is displayed and the workflow can not be launched.
**Note**: This issue does not exist on the Test Run in the studio. Only exists on the published app.

![image](https://github.com/user-attachments/assets/80e825ce-7c2e-4e5b-bd17-8074fed8047a)

**Comment by kaito0228** [comment]
I'm experiencing the same bug too!

**Comment by tnfsmith** [comment]
I am reporting this issue on Discord. It shows error on chatflow also. And If-Else also have problems. The selection field must be declared although it does not require at all.

**Comment by git-davi** [comment]
I am experiencing the same bug as well

**Comment by git-davi** [comment]
After a very quick look I see that files are uploaded correctly (see image below).

![image](https://github.com/user-attachments/assets/111f0e54-dc39-484b-89fb-820b6c42eda6)

Maybe the javascript hook/function is not working correctly in the browser and the api call is not updating parameters with the correct file id.
This would explain also why once the execute button is pressed (to launch the workflow) the POST request to the server is not even being sent.

**Comment by kurokobo** [comment]
@git-davi 
I haven't been able to update, but your insight is correct. The upload is complete for all files, but the reason is that only the information from the last upload is used.

@laipz8200 
The issue arises when there are multiple file uploaders, as the Zustand store is shared among the uploaders. In the current implementation, only the information of the last uploaded file is retained.
