### ISSUE TITLE
Error with dify api not receiving messages

### ISSUE THREAD

**Issue by lucaseatp** [langgenius/dify#10329]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I use dify with postgres, but when I made an api connection, very often it breaks and doesn't answer anything.

I looked up and dify doesn't ever get the data, this is the error that I get

File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.

### ✔️ Expected Behavior

no error with the api connection

### ❌ Actual Behavior

api doesn't get any data

**Comment by lucaseatp** [comment]
postgres shows no error, max connections is very high. postgres is accessible. how do I enable SQLAlchemy's connection pool pre-ping?

**Comment by crazywoola** [comment]
Please provide the logs of the api and other containers.

**Comment by MarcIbiza** [comment]
Hello friend, I have the same error, how did you solve it?

I am using image:postgres:14

![Image](https://github.com/user-attachments/assets/84529b72-453b-4d1f-8220-10aa41ba8b21)

![Image](https://github.com/user-attachments/assets/98ea4332-53ee-4241-bd9b-9d1939158ac4)

![Image](https://github.com/user-attachments/assets/01601cb9-0bc1-4310-a76e-c2bb66b8fec0)
