### ISSUE TITLE
Issues After Updating to Dify Version 0.11.0

### ISSUE THREAD

**Issue by ottoradiologia** [langgenius/dify#10336]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Steps to Reproduce
Start Dify after updating to version 0.11.0.
Attempt to execute a query or action in the Dify console.
Wait for the request to be processed.
Include the following screenshots for visual reference:

"Expecting value: line 1 column 1 (char 0)" error when processing a query.
"Internal Server Error" message displayed on the screen.
"Run failed: command not allowed when used memory > 'maxmemory'" error.
"The server encountered an internal error and was unable to complete your request." message.

### ✔️ Expected Behavior

Expected Behavior
Queries and commands in the Dify console should execute without issues, with responses processed correctly and no memory or server response errors.

### ❌ Actual Behavior

Actual Behavior
The following errors occur when executing actions in Dify:

"Expecting value: line 1 column 1 (char 0)" – possibly indicating a JSON parsing error.
"Internal Server Error" – potentially related to server overload or instability.
"Run failed: command not allowed when used memory > 'maxmemory'" – indicating memory limit exceeded.
"The server encountered an internal error and was unable to complete your request." – indicating an internal server error.

![4cfa6ece-0104-4b7d-bb03-1f16476ea873](https://github.com/user-attachments/assets/b2fb3922-bb52-472d-8353-f506067e5850)
![01937964-b506-4300-b8af-dbfdfc09a67e](https://github.com/user-attachments/assets/e25857af-7444-492d-9174-e475789809eb)
![eecfc30e-f205-4d43-a266-2742bf30bae9](https://github.com/user-attachments/assets/7fd12ffd-c237-461b-9d5c-ef308bffa770)
![3faf02cc-90b8-4fb3-b814-22c85c24834e](https://github.com/user-attachments/assets/55191202-ec61-4f62-9013-b73519ed3dcc)
![7368780f-9944-4a90-8a44-47bb2549fb02](https://github.com/user-attachments/assets/c71b0216-edb2-4a40-9119-5b6b9eb29fb7)

**Comment by ottoradiologia** [comment]
![274c50fd-adb7-47a2-890c-bccf71b00304](https://github.com/user-attachments/assets/0d31d5b3-8087-4043-a5d7-409792cf7e2c)

**Comment by crazywoola** [comment]
This should been resolved now.
