### ISSUE TITLE
ollama module extension model type request

### ISSUE THREAD

**Issue by E218PQ** [langgenius/dify#10334]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes, I hope I can fully localize the deployment of all models, including dify and related LLM/TTS/RAG/embedding models. Previously, it was quite complicated with ollama+xinference, but now it seems that ollama supports one click deployment of all gguf format models in huggingface, which will greatly reduce the threshold for model deployment and simplify the model deployment environment. I hope dify can expand the supported model types in the ollama module, such as TTS, RAG, etc

### 2. Additional context or comments

Request to extend the model types of the ollama module in dify, such as TTS, RAG, multimodal, etc

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by liberalchang** [comment]
+1
