### ISSUE TITLE
document word count is incorrent when segment change

### ISSUE THREAD

**Issue by nadirvishun** [langgenius/dify#10335]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Both the `documents` and `document_segments` in the database contain a `word_count` field, but there are issues with both:
- In segments: If it is in `qa` mode, the field `content` is used as the question and the field `answer` as the answer, but when counting words, only `content` is counted, and the word count in `answer` is not included, as shown in the following figure:
  
  ![image](https://github.com/user-attachments/assets/6fa07d60-30e1-4546-91d6-f08036fd19c0)

- In documents: It is only correct at the very beginning. Once segement undergoes create,  batch create, update, delete, there is no associated change in the doucument, as shown in the following figure:
 
  ![image](https://github.com/user-attachments/assets/801a3a8d-658d-4a71-a216-490d4a1ae7f0)

- In datesete: The word count is the sum of all documents, leading to the same issue:
  
  ![image](https://github.com/user-attachments/assets/2a8d59b5-ad85-4ae3-a5ea-667ff6854b8e)

The existing data can be corrected by referring to the following SQL, For reference only:
- First fix the segment
  ```sql
  UPDATE document_segments 
  SET word_count = CHAR_LENGTH ( CONTENT ) + CASE WHEN answer IS NULL THEN 0 ELSE CHAR_LENGTH ( answer ) END;
  ```
- Then fix the document：
  ```sql
  UPDATE documents 
  SET word_count = T.word_count 
  FROM
	  ( SELECT SUM ( word_count ) AS word_count, document_id FROM document_segments GROUP BY document_id ) T 
  WHERE
	  ID = T.document_id;
  ```

### ✔️ Expected Behavior

word count is corrent.

### ❌ Actual Behavior

word count is incorrent.

**Comment by JohnJyong** [comment]
@nadirvishun currently, we only count the query length and it will be improved in next version
@JzoNgKVO If the word count does not reach 1K, the front end displays 0K
