### ISSUE TITLE
The workflow page is not available command + C Copy

### ISSUE THREAD

**Issue by zhangyongcun** [langgenius/dify#10337]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need to copy some information on a workflow page, and I can't use command + c to copy it, I can only use the context menu to select copy. I often get errors when copying, describing information or links, and the code runs.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Do you want to copy within a workflow or across multiple workflows?
