### ISSUE TITLE
[openai] Bad Request Error, Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}

### ISSUE THREAD

**Issue by Moiyu1998** [langgenius/dify#10348]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When setting the maximum tokens with OpenAI's o1 model, an error occurs.
[openai] Bad Request Error, Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}

**Comment by laipz8200** [comment]
The API for the o1 series models is still in preview, with many features not yet supported. I think we should wait for a stable version to be released.

**Comment by Moiyu1998** [comment]
> The API for the o1 series models is still in preview, with many features not yet supported. I think we should wait for a stable version to be released.

This issue should be resolved by simply changing a parameter. According to the error message, for the o1 series models, 'max_tokens' needs to be changed to 'max_completion_tokens'.

**Comment by akazakou** [comment]
In my configuration, I'm not using `max_tokens` or `max_completion_tokens`, but still getting that one error for the `o3-mini` model.
