### ISSUE TITLE
The chatBot's image upload model, using the gpt4o model, cannot recognize images. It was functioning properly before the upgrade.

### ISSUE THREAD

**Issue by GeorgeGalway** [langgenius/dify#10345]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2~0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The chatBot's image upload model, using the gpt4o model, cannot recognize images. It was functioning properly before the upgrade.
![image](https://github.com/user-attachments/assets/23da7983-3007-4314-9c77-cc4f11de16a9)

![image](https://github.com/user-attachments/assets/731c501d-1b1d-4ce1-b5f7-952cca649fea)

### ✔️ Expected Behavior

I hope the model will be able to recognize images normally.

### ❌ Actual Behavior

cannot recognize images

**Comment by laipz8200** [comment]
<img width="871" alt="image" src="https://github.com/user-attachments/assets/32b2cda6-d504-4b7b-a73c-05442f7b064c">

I tested this feature on our Cloud service, and it looks fine.

**Comment by GeorgeGalway** [comment]
I continued testing and found that images pasted using CTRL+V cannot be recognized, while manually uploaded ones can be recognized.
