### ISSUE TITLE
The reranking model has been set up successfully, but it is not taking effect and the original model is still being used.

### ISSUE THREAD

**Issue by zhukefucn** [langgenius/dify#10351]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The reranking model has been set up successfully, but it is not taking effect and the original model is still being used.
 original model is jina，I changed to cohere model , set in two position , one is default rerank model setting , the other is in knowledge base .  

### ✔️ Expected Behavior

new rerank model setting  taking effect correctly

### ❌ Actual Behavior

The reranking model has been set up successfully, but it is not taking effect and the original model is still being used.

**Comment by crazywoola** [comment]
This has been fixed in later version, please upgrade to latest one.

**Comment by zhukefucn** [comment]
How can I change data setting  to slove the problem temporerly ?
