### ISSUE TITLE
The text data in the tables of the Word file cannot be extracted

### ISSUE THREAD

**Issue by naked34501** [langgenius/dify#10359]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

The text data in the tables of the Word file cannot be extracted，
I have already uploaded the attachment.U can try on it
[测试改合同.docx](https://github.com/user-attachments/files/17643257/default.docx)

### ✔️ Expected Behavior

30万元

### ❌ Actual Behavior

-----
——————

**Comment by JohnJyong** [comment]
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/171cf43a-5a0a-4dc6-8617-40db5c8d3a6f">
the tested image attached ， pls comfirm， if any proble,  you can reopen this issue. @naked34501

**Comment by Dongnc1017** [comment]
这个问题有解决吗？我也遇到了。请问是怎么解决的？
