### ISSUE TITLE
When resetting the password on a local installation, I get the message "Account not found."

### ISSUE THREAD

**Issue by angleboy8** [langgenius/dify#10361]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

I did not find it

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After registering the admin account, I went to the login page (http://127.0.0.1/signin) and entered my email and password, but it displayed "Account not found," indicating the account couldn't be found. I followed the official help guide to reset the password (**docker exec -it docker-api-1 flask reset-password**), entered my account email and password, but again received the message "Account not found for email: [my email]." Could you please advise on how to reset my admin account? Thank you.

![1](https://github.com/user-attachments/assets/4f64c2d7-1e2d-4261-86df-26549917ed54)

![1](https://github.com/user-attachments/assets/434820b1-e20c-4932-94b6-9d97de65c66a)

![2](https://github.com/user-attachments/assets/100f2593-aed8-4856-b86c-525522bd1240)

**Comment by crazywoola** [comment]
I think you can use some db client and connect it to see if the data is lost.
You can find your email in `accounts` table.
