### ISSUE TITLE
Can not get data from Http request (form-data) when using upload File List

### ISSUE THREAD

**Issue by mvn-vyvo-dn** [langgenius/dify#10367]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0, 0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. In Node Start: Input Field choose "File List"
2. In Node Http request: choose form-data and input field with value fileArray
3. Test Run 

### ✔️ Expected Behavior

Can not get data from request

### ❌ Actual Behavior

Can get data from request
<img width="1354" alt="Screenshot 2024-11-06 at 3 40 35 PM" src="https://github.com/user-attachments/assets/e101fe8e-3dd3-4615-82d9-3882ee47950b">
<img width="604" alt="Screenshot 2024-11-06 at 3 41 50 PM" src="https://github.com/user-attachments/assets/911cc1f6-b80b-48b3-8296-c600bf658ad9">

**Comment by crazywoola** [comment]
The type of the key is file, but you passed a Array[File]

**Comment by mvn-vyvo-dn** [comment]
@crazywoola Please help me! Can not upload with File List in Http request(form-data), right? How can I upload with multiple files to another server to handle?

**Comment by pendoragon** [comment]
@crazywoola Hi, I have run into the same issue and here is another one https://github.com/langgenius/dify/issues/10018. It turns out that Dify does not actually support POSTing array of files through form data. 
https://github.com/langgenius/dify/blob/3bc4dc58d70a82616d66260c79c6a36ff81533a9/api/core/workflow/nodes/http_request/executor.py#L140-L147
https://github.com/langgenius/dify/blob/3bc4dc58d70a82616d66260c79c6a36ff81533a9/api/core/workflow/entities/variable_pool.py#L170-L174

So when selector selects a `ArrayFileSegment`(e.g. `sys.files` which is `Array[File]`), the `files` will be empty. 
However, POSTing a list of files under one form data key seems to be a perfectly fine thing to do. e.g. in Python you could do something like:
```python
files=[
  ('files',(filename1, filecontent1, mime_type1)),
  ('files',(filename2, filecontent2, mime_type2)),
  ('files',(filename3, filecontent3, mime_type3))
]

response = requests.request("POST", url, headers=headers, data=payload, files=files)
```
I have made changes locally to make it work. And if it sounds reasonable to support passing a `Array[File]` to form data, maybe I can send a PR

**Comment by hxuaj** [comment]
> @crazywoola Hi, I have run into the same issue and here is another one #10018. It turns out that Dify does not actually support POSTing array of files through form data.
> 
> https://github.com/langgenius/dify/blob/3bc4dc58d70a82616d66260c79c6a36ff81533a9/api/core/workflow/nodes/http_request/executor.py#L140-L147
> 
> 
> https://github.com/langgenius/dify/blob/3bc4dc58d70a82616d66260c79c6a36ff81533a9/api/core/workflow/entities/variable_pool.py#L170-L174
> 
> So when selector selects a `ArrayFileSegment`(e.g. `sys.files` which is `Array[File]`), the `files` will be empty. However, POSTing a list of files under one form data key seems to be a perfectly fine thing to do. e.g. in Python you could do something like:
> 
> ```python
> files=[
>   ('files',(filename1, filecontent1, mime_type1)),
>   ('files',(filename2, filecontent2, mime_type2)),
>   ('files',(filename3, filecontent3, mime_type3))
> ]
> 
> response = requests.request("POST", url, headers=headers, data=payload, files=files)
> ```
> 
> I have made changes locally to make it work. And if it sounds reasonable to support passing a `Array[File]` to form data, maybe I can send a PR

Could you specify the changes locally to make dify http request support multiple files? I have the same issue. Thx.

**Comment by pendoragon** [comment]
@hxuaj Below is the git diff. I made this change based on 0.10.2, so it probably does not fit directly to later versions. but you can take it as a reference
```diff
diff --git a/api/core/workflow/entities/variable_pool.py b/api/core/workflow/entities/variable_pool.py
index 3dc3395da..97df6fa6a 100644
--- a/api/core/workflow/entities/variable_pool.py
+++ b/api/core/workflow/entities/variable_pool.py
@@ -7,7 +7,7 @@ from pydantic import BaseModel, Field

 from core.file import File, FileAttribute, file_manager
 from core.variables import Segment, SegmentGroup, Variable
-from core.variables.segments import FileSegment
+from core.variables.segments import FileSegment, ArrayFileSegment
 from factories import variable_factory

 from ..constants import CONVERSATION_VARIABLE_NODE_ID, ENVIRONMENT_VARIABLE_NODE_ID, SYSTEM_VARIABLE_NODE_ID
@@ -164,8 +164,8 @@ class VariablePool(BaseModel):
                 segments.append(variable_factory.build_segment(part))
         return SegmentGroup(value=segments)

-    def get_file(self, selector: Sequence[str], /) -> FileSegment | None:
+    def get_file(self, selector: Sequence[str], /) -> FileSegment | ArrayFileSegment | None:
         segment = self.get(selector)
-        if isinstance(segment, FileSegment):
+        if isinstance(segment, FileSegment | ArrayFileSegment):
             return segment
-        return None
+        return None
\ No newline at end of file
diff --git a/api/core/workflow/nodes/http_request/executor.py b/api/core/workflow/nodes/http_request/executor.py
index 687247829..14ec828d6 100644
--- a/api/core/workflow/nodes/http_request/executor.py
+++ b/api/core/workflow/nodes/http_request/executor.py
@@ -115,7 +115,7 @@ class Executor:
                 case "binary":
                     file_selector = data[0].file
                     file_variable = self.variable_pool.get_file(file_selector)
-                    if file_variable is None:
+                    if file_variable is None or isinstance(file_variable.value, list):
                         raise ValueError(f"cannot fetch file with selector {file_selector}")
                     file = file_variable.value
                     self.content = file_manager.download(file)
@@ -140,13 +140,16 @@ class Executor:
                     }
                     files = {k: self.variable_pool.get_file(selector) for k, selector in file_selectors.items()}
                     files = {k: v for k, v in files.items() if v is not None}
-                    files = {k: variable.value for k, variable in files.items()}
                     files = {
-                        k: (v.filename, file_manager.download(v), v.mime_type or "application/octet-stream")
-                        for k, v in files.items()
-                        if v.related_id is not None
+                        k: variable.value if isinstance(variable.value, list) else [variable.value]
+                        for k, variable in files.items()
                     }
-
+                    files = [
+                        (k, (v.filename, file_manager.download(v), v.mime_type or "application/octet-stream"))
+                        for k, vlist in files.items()
+                        for v in vlist
+                        if v.related_id is not None
+                    ]
                     self.data = form_data
                     self.files = files

@@ -249,9 +252,9 @@ class Executor:
         body = ""
         if self.files:
             boundary = self.boundary
-            for k, v in self.files.items():
+            for k, v in self.files:
                 body += f"--{boundary}\r\n"
-                body += f'Content-Disposition: form-data; name="{k}"\r\n\r\n'
+                body += f'Content-Disposition: form-data; name="{k}"; filename="{v[0]}"\r\n\r\n'
                 body += f"{v[1]}\r\n"
             body += f"--{boundary}--\r\n"
         elif self.node_data.body:
```

**Comment by hxuaj** [comment]
> ```diff
> body += f'Content-Disposition: form-data; name="{k}"; filename="{v[0]}"\r\n\r\n'
> ```

Thank you for the reply, I've tested it in 0.14.2 and it works perfectly.

**Comment by hxuaj** [comment]
@pendoragon Thank you for the reply, I've tested it in 0.14.2 and it works perfectly.
