### ISSUE TITLE
The HTTP request node failed to send form-data parameters

### ISSUE THREAD

**Issue by leoterry-ulrica** [langgenius/dify#10362]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、workflow http request node
![1730879786022](https://github.com/user-attachments/assets/0758b99a-7148-4b7b-a891-00ed7381708b)

2、unable to send form-data parameters to the interface
![1730879729032](https://github.com/user-attachments/assets/8dc4287b-5caf-44d8-be3c-414e37fbbd0a)
![1730882260083](https://github.com/user-attachments/assets/af3bd741-a1a7-48a9-94e6-f789a759b0a8)

3、postman request form-data success
![1730879896529](https://github.com/user-attachments/assets/36fa0af4-4036-4111-9e6a-6beee97cba65)

### ✔️ Expected Behavior

hope to be able to send form-data parameters.
![1730879896529](https://github.com/user-attachments/assets/96b53589-2536-42c6-93f6-00edc9b85490)

**Comment by leoterry-ulrica** [comment]
Additional note, the 0.7.0 version can successfully send form-data parameters.

**Comment by crazywoola** [comment]
Check the sandbox and squid configuration, to see if this host is allowed to be accessed.

**Comment by leoterry-ulrica** [comment]
> Check the sandbox and squid configuration, to see if this host is allowed to be accessed.
Don’t close it so early, please make sure you understand the issue clearly first.

![1730880225792](https://github.com/user-attachments/assets/90585202-394c-4cc0-ace9-e27a07bb94cb)

![1730880182781](https://github.com/user-attachments/assets/553eb0b1-a68d-4445-8f47-77b51182e8f1)

**Comment by leoterry-ulrica** [comment]
@JohnJyong  Your colleague closed this issue too quickly without fully understanding the problem. I reported this issue to your relevant colleague via WeChat yesterday, and they guessed it might be a sandbox problem. I have checked the code of dify and it should not be a sandbox issue, but rather a problem with the code in api/core/workflow/nodes/http_request/executor.py.Could you please check the code for the bug?

**Comment by MWang-TS** [comment]
I've got similar issue with 0.11 's HTTP node, configured as 
![image](https://github.com/user-attachments/assets/14036d12-4b6d-4529-8b04-7ff0ba781c46)
The same configuration is well working with 0.9.2. 
But in 0.11, API received error messages from HTTP node.

I noticed post request format changed with 0.11, suppose to be the problem.
see attachment below: blue 0.11 vs red circle 0.9.2
![9c854786717dda88a70badbd9368ee4](https://github.com/user-attachments/assets/f9577635-5ad0-498f-b892-1cef13eb5a12)

**Comment by leoterry-ulrica** [comment]
> I've got similar issue with 0.11 's HTTP node, configured as ![image](https://private-user-images.githubusercontent.com/76930061/383938536-14036d12-4b6d-4529-8b04-7ff0ba781c46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Nzk0OTMsIm5iZiI6MTczMDk3OTE5MywicGF0aCI6Ii83NjkzMDA2MS8zODM5Mzg1MzYtMTQwMzZkMTItNGI2ZC00NTI5LThiMDQtN2ZmMGJhNzgxYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDExMzMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzgyM2U0YjVlZWMxMDE1NjZmZjY0NWFkZDE5Yjk0MTU5MDFiZGNjN2QwOTZlZmFmMzhhODE5ZDk4NjE4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6RKmsW3niI7JymoWyzuxvAOAOzubOcdV7rnSchsKdWQ) The same configuration is well working with 0.9.2. But in 0.11, API received error messages from HTTP node.
> 
> I noticed post request format changed with 0.11, suppose to be the problem. see attachment below: blue 0.11 vs red circle 0.9.2 ![9c854786717dda88a70badbd9368ee4](https://private-user-images.githubusercontent.com/76930061/383937276-f9577635-5ad0-498f-b892-1cef13eb5a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Nzk0OTMsIm5iZiI6MTczMDk3OTE5MywicGF0aCI6Ii83NjkzMDA2MS8zODM5MzcyNzYtZjk1Nzc2MzUtNWFkMC00OThmLWI4OTItMWNlZjEzZWI1YTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDExMzMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjhjOTVkMzEwZGY4N2U4NzA5MDc2MDM3YmJhNWZkYmIwYWVmNGRkNGExMWQyNGNhZTlkODg2ZjhkNTJlZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GuSDqVD2FUeY84xNSZ5sxjcsCpcI8fK9eAgVau3Wlv0)

It might be a bug; the official developers are already looking into it.

**Comment by leoterry-ulrica** [comment]
There is still a problem.
![1731053005997](https://github.com/user-attachments/assets/637473ee-15d4-409f-a58f-c9f441086aa4)

@crazywoola

**Comment by tridvm** [comment]
I had that problem too. Dify didn't send form-data body via third-party API.
When I upgraded to the latest version (v0.11.1), the bug's still there.

![image](https://github.com/user-attachments/assets/e05e106d-4e7e-4021-8bcb-b4a03e82a11b)
