### ISSUE TITLE
How to increase the Maximum Iterations of an agent to 50.

### ISSUE THREAD

**Issue by seasoncool** [langgenius/dify#10382]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We want to perform click operations on the browser, which requires calling different methods in the tools multiple times, and the current 5 iterations are far from enough.

Can the Maximum Iterations set in the agent currently be modified through environment variables, or does it require modifying the source code?

![image](https://github.com/user-attachments/assets/1b08a007-88e9-40fb-b41e-b5297b375de9)

### 2. Additional context or comments

We have followed the method here to make numerical adjustments, but after docker-compose restart, the value on the webpage did not change from 5 to 50. How should we adjust it?

https://github.com/langgenius/dify/issues/8692#issuecomment-2368774077

![image](https://github.com/user-attachments/assets/ee26d046-ab13-402e-bc3a-85445590b5ef)

![image](https://github.com/user-attachments/assets/6400b26c-87ec-4955-b9f0-07e11ad7660d)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by seasoncool** [comment]
In which of the following Docker containers is this file located?

docker_nginx_1
docker_worker_1
docker_api_1
docker_redis_1
docker_ssrf_proxy_1
docker_sandbox_1
docker_db_1
docker_web_1

**Comment by crazywoola** [comment]
This is a old question, but the answer is you can not do it at this moment.

**Comment by seasoncool** [comment]
Thanks for your reply @crazywoola .
So modifying this file is ineffective, right? Do you know of any workarounds?

**Comment by crazywoola** [comment]
Well, the bot is right, https://github.com/langgenius/dify/blob/main/web/app/components/app/configuration/config/agent/agent-setting/index.tsx
You need to modify this value.

**Comment by seasoncool** [comment]
I changed the number from 5 to 50 in the source code, then ran `docker-compose up` again, but after the service started, the maximum number was still 5. I couldn't find this file in the web container either. Am I making a mistake somewhere? Do you know which container this file is in?

**Comment by crazywoola** [comment]
If you changed the source code, you need to run the build process again, otherwise it won't take effects. `docker compose up -d` just means you can run the old (pulled containers). Please read the docs of docker to understand what's going on underhood.

**Comment by seasoncool** [comment]
thanks，we will try later.

**Comment by rickydata-indexer** [comment]
@seasoncool curious if you had any luck with this in the end

**Comment by seasoncool** [comment]
no luck , we used workflow finally.

**Comment by rickydata-indexer** [comment]
sounds good thank you for the response @seasoncool! What do you mean by "workflow"? Is that a different product?

**Comment by seasoncool** [comment]
You can create a new workflow here and define your own process as many times as needed.
![image](https://github.com/user-attachments/assets/d3440e7b-96a4-4806-a822-9c83c57e2b3c)
