### ISSUE TITLE
Support BM25 for Milvus

### ISSUE THREAD

**Issue by NiuBlibing** [langgenius/dify#10396]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Milvus has already support BM25, I think we can support it in dify by some way.

### 2. Additional context or comments

https://milvus.io/docs/embed-with-bm25.md

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Feel free to open a PR. :)

**Comment by kenwoodjw** [comment]
The mivlus example 
```
from pymilvus.model.sparse.bm25.tokenizers import build_default_analyzer
from pymilvus.model.sparse import BM25EmbeddingFunction

analyzer = build_default_analyzer(language="en")

corpus = [
    "Artificial intelligence was founded as an academic discipline in 1956.",
    "Alan Turing was the first person to conduct substantial research in AI.",
    "Born in Maida Vale, London, Turing was raised in southern England.",
]

tokens = analyzer(corpus[0])
print("tokens:", tokens)
```
```
Parameters:

language (string)

The language of the text to be tokenized. Valid options are en (English), de (German), fr (French), ru (Russian), sp (Spanish), it (Italian), pt (Portuguese), zh (Chinese), jp (Japanese), kr (Korean).
```
Can we use zh as default language? Or how to pass the language option?

**Comment by crazywoola** [comment]
See this for updates. https://github.com/langgenius/dify/issues/11370
