### ISSUE TITLE
The file parameter is not consistance between the conversation and the file upload part.

### ISSUE THREAD

**Issue by KevinZhang19870314** [langgenius/dify#10393]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a chatbot using orchestrate method of chatflow;
2. Add a optional field `file` in the start node;
3. Upload a file;
4. Start to chat "hi";
5. Remove the file in upload list;
6. Say "hi again", check the workflow process;
![image](https://github.com/user-attachments/assets/b53015b2-acec-4676-ac4a-60c5d69ea52b)

### ✔️ Expected Behavior

The workflow process should not show the file object

### ❌ Actual Behavior

The workflow process displayed the file object

**Comment by crazywoola** [comment]
This is a designed behavior, it's not only about the `file` field, you can not change other types as well. We keep the snapshot of all users' inputs after the user starts the conversation, and they will remain the same as long as the user starts a new conversation.

**Comment by KevinZhang19870314** [comment]
@crazywoola Thank you for your response. Then what is the purpose of the "remove uploaded file" operation in the same conversation? And how can I modify a file in the same conversation?

![image](https://github.com/user-attachments/assets/8626a791-27cc-4b63-9dcd-ebc0acb710dd)
