### ISSUE TITLE
The built-in variable `sys.files` not found in params of code node

### ISSUE THREAD

**Issue by KevinZhang19870314** [langgenius/dify#10392]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a chatbot using orchestrate method of chatflow;
2. Add a code node, and connect the start and code node;
3. You can see the dropdown list in code arg1;
![image](https://github.com/user-attachments/assets/3965ae22-7354-4e1c-9aa8-140dfc420103)

### ✔️ Expected Behavior

It should have the sys.files parameter

### ❌ Actual Behavior

No sys.files parameter

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues?q=is%3Aissue+sys.files+is%3Aclosed
Check this  https://github.com/langgenius/dify/issues/10235

**Comment by KevinZhang19870314** [comment]
@crazywoola Thank you for the response. In my scenario, sys.files is more convenient than defining a custom file field. Through the UI, users can easily see the built-in upload button and upload files for each chat.

My suggestion is to make custom-defined file objects more visible in the UI. Is that posible?
