### ISSUE TITLE
AWS Bedrock Claude 3.5 Haiku LLM Block Error: Maximum Tokens Exceeds Model Limit

### ISSUE THREAD

**Issue by masinc** [langgenius/dify#10390]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

When using AWS Bedrock Claude 3.5 Haiku in the LLM block, the following error occurs.

```
Run failed: [bedrock] Error: ValidationException: The maximum tokens you requested exceeds the model limit of 4096. Try again with a maximum tokens value that is lower than 4096.
```

![image](https://github.com/user-attachments/assets/91d301a3-5900-4293-8161-ac1b6e7e9e63)

It seems that the maximum value of the model parameter Max Tokens is different. It works when set to 4096.

![image](https://github.com/user-attachments/assets/4334b16b-1566-476a-a7ce-f2e71679d6ef)

### ✔️ Expected Behavior

The maximum value of Max Tokens is 4096.

**Comment by crazywoola** [comment]
Fixed in (#10286)
