### ISSUE TITLE
下拉选项显示

### ISSUE THREAD

**Issue by dinggithub** [langgenius/dify#104]
下拉选项加了6个，第5个已经显示不全了。用chrome和edge，以及手机显示都这样
![7c72b0dabec67f46f755f15c4f8963a](https://github.com/langgenius/dify/assets/16711606/5601f9a4-b562-4f4d-bdaf-b63196a6f641)

**Comment by iamjoel** [comment]
修复了：https://github.com/langgenius/dify/pull/136
