### ISSUE TITLE
Uploading an xml file returns the error "Invalid upload file" in a docker local deployment of dify.

### ISSUE THREAD

**Issue by zqcing678** [langgenius/dify#10419]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Simply create a workflow and upload a file in xml format at the start node to reproduce this error

### ✔️ Expected Behavior

Correctly read xml format files.

### ❌ Actual Behavior

Returns the error "Invalid upload file".

**Comment by crazywoola** [comment]
Please upgrade to v0.11.0

**Comment by zqcing678** [comment]
> Please upgrade to v0.11.0

I have just upgraded to v0.11.0 and this problem persists.

**Comment by crazywoola** [comment]
> > Please upgrade to v0.11.0
> 
> I have just upgraded to v0.11.0 and this problem persists.

https://github.com/langgenius/dify/issues/10220#issuecomment-2463632550
