### ISSUE TITLE
Update the output length limit of the code execution

### ISSUE THREAD

**Issue by Moiyu1998** [langgenius/dify#10439]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The current upper limit for iterative nodes is 30, which is sometimes not sufficient. Could you add an environment variable that allows users to set the upper limit for iterative nodes during deployment?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/discussions/10436

**Comment by Moiyu1998** [comment]
Sorry, I might have been mistaken. This might not be the iteration node limit, but rather the output length limit of the code execution.In summary, it is possible to set a maximum limit for the length of lists within the workflow.

**Comment by crazywoola** [comment]
Not within the workflow, but you can set those here.
https://github.com/langgenius/dify/blob/12a9e2972a097ccec5608cc8fe1a188af549de90/docker/.env.example#L676-L686
