### ISSUE TITLE
Add user feedback in langfuse message trace

### ISSUE THREAD

**Issue by wy96f** [langgenius/dify#10434]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The operations team wants to view messages about users liking or disliking, incorporate them into the dataset for annotation, and optimize the overall application's response effectiveness.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by ZhouhaoJiang** [comment]
@wy96f Considering that we are currently supporting Langfuse and Langsmith, with plans to integrate more platforms in the future, our primary goal is to track and analyze model usage and consumption, such as token usage and performance metrics. This integration is intended to provide a better understanding of how the models are being used, rather than to support highly specialized or fine-tuned features. As such, we are not considering the integration of features like viewing specific user feedback (likes/dislikes) within the message trace at this time.

**Comment by wy96f** [comment]
> @wy96f Considering that we are currently supporting Langfuse and Langsmith, with plans to integrate more platforms in the future, our primary goal is to track and analyze model usage and consumption, such as token usage and performance metrics. This integration is intended to provide a better understanding of how the models are being used, rather than to support highly specialized or fine-tuned features. As such, we are not considering the integration of features like viewing specific user feedback (likes/dislikes) within the message trace at this time.

@ZhouhaoJiang Got it, thanks for reply. Do you have plans to support phoenix(https://github.com/Arize-ai/phoenix)? It is also a popular open-source project that many people are using.

**Comment by gosailing** [comment]
> [@wy96f](https://github.com/wy96f) Considering that we are currently supporting Langfuse and Langsmith, with plans to integrate more platforms in the future, our primary goal is to track and analyze model usage and consumption, such as token usage and performance metrics. This integration is intended to provide a better understanding of how the models are being used, rather than to support highly specialized or fine-tuned features. As such, we are not considering the integration of features like viewing specific user feedback (likes/dislikes) within the message trace at this time.

Hi Haojing, we have the same question about dify sync data with ops tool like langfuse, understand your goal is to track model usage, while from using dify to develop llm apps, devs may need export 'liked' qa pairs as dify knowledge entry. Do you think it make sense to add 'user rate(like or dislike)' field to message trace info in syncing with ops tools? Thanks
