### ISSUE TITLE
can not install psycopg2-binary:2.9.10

### ISSUE THREAD

**Issue by chzphoenix** [langgenius/dify#10447]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

lastest

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

poetry install

### ❌ Actual Behavior

when update psycopg2-binary from 2.9.9 to 2.9.10，this is an error:
Error: pg_config executable not found.

but when i change the version to "2.9.9"（from “~2.9.6”）, it worked.

is there something i missed?

**Comment by crazywoola** [comment]
I can not reproduce this deps error.

**Comment by chzphoenix** [comment]
> I can not reproduce this deps error.

My postgres is running in docker witch be started by docker-compose.middleware.yaml

**Comment by crazywoola** [comment]
> > I can not reproduce this deps error.
> 
> My postgres is running in docker witch be started by docker-compose.middleware.yaml

Me too, I check out the source code from main branch.

**Comment by chzphoenix** [comment]
I install postgresql local on my mac, and i can install psycopg2-binary:2.9.10 now. 
I guess this version（2.9.10）has some change and can not use pg_config which in the docker.
