### ISSUE TITLE
File is not JSON serializable in '/v1/message' interface

### ISSUE THREAD

**Issue by ChenZixinn** [langgenius/dify#10443]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud, Self Hosted (Source)

### Steps to reproduce

1. Create an app that requires a list of pictures as a param.
![image](https://github.com/user-attachments/assets/6a8fea32-d99c-4600-848d-b8f3b2b2f3a7)
2. Upload images and chat by API, like this
```shell
curl -X POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {
        "pdf_pictures":[{
        "type": "image",
        "transfer_method": "remote_url",
        "url": "https://cloud.dify.ai/logo/logo-site.png"
      }]
    },
    "query": "What are the specs of the iPhone 13 Pro Max?",
    "response_mode": "streaming",
    "conversation_id": "",
    "user": "abc-123",
    "files": [
    ]
}'
```
3. GET `/v1/messages`, it will return **500**. 
```shell
curl -X GET 'https://api.dify.ai/v1/messages?user=abc-123&conversation_id='\
 --header 'Authorization: Bearer {api_key}'
```
4. I debug into, the error is **Object of type File is not JSON serializable**
![image](https://github.com/user-attachments/assets/3cecf032-17ea-4dc2-8ce3-6a0b0ec3e8a0)

### ✔️ Expected Behavior

The result return normally.

### ❌ Actual Behavior

Object of type File is not JSON serializable

**Comment by crazywoola** [comment]
Here are some related issues
- https://github.com/langgenius/dify/issues/10300
- https://github.com/langgenius/dify/issues/10224
