### ISSUE TITLE
v0.10.0,in workflow,get file.url is null 

### ISSUE THREAD

**Issue by h897372063** [langgenius/dify#10448]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

* upload a txt file. then get it's url , but get null .  

![image](https://github.com/user-attachments/assets/736f383c-625b-4bf3-ac17-b4a4112b4347)

### ✔️ Expected Behavior

* get file’s url string

**Comment by crazywoola** [comment]
Please read our existing issues and closed issues.
