### ISSUE TITLE
Run failed: file type video is not supported

### ISSUE THREAD

**Issue by bingbing6** [langgenius/dify#10453]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/5473d2d5-8ede-4a16-b9af-1f8aa3620da6)
ollama——anas/video-llava:test-v2，Video analysis is not supported

### ✔️ Expected Behavior

Can perform video analysis

### ❌ Actual Behavior

Run failed: file type video is not supported

**Comment by hjlarry** [comment]
the video file type just support by this PR https://github.com/langgenius/dify/pull/9828/files
you can try again later, maybe raise other errors
