### ISSUE TITLE
Add entity collection function to enhance the effect of intelligent question and answer

### ISSUE THREAD

**Issue by dajianguo** [langgenius/dify#10468]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

First of all, I am very grateful to the dify team for providing a good basic platform.
We have a customer service scenario requirement. After multiple rounds of verification in the early stage and referring to the other products in the industry, we have made the following design.

Its first version was like this, but it was not smart enough:
![image](https://github.com/user-attachments/assets/39d6db75-e4e5-4f62-ba37-9abf4466723b)
![image](https://github.com/user-attachments/assets/746b30c8-0c05-485f-bfd1-b1c5c7c82bdc)

Therefore, we referred to Baidu Keyue and redesigned the following, and conducted preliminary effect verification.
![image](https://github.com/user-attachments/assets/448b2149-673f-4d8e-aad2-9910c44bc281)
this is the design:
![image](https://github.com/user-attachments/assets/cd772b41-ab72-47ce-8047-b9646c142d13)
![image](https://github.com/user-attachments/assets/d17509b0-c410-42b0-af0f-79bf9a4660db)
![image](https://github.com/user-attachments/assets/493d2144-ec50-4548-bf34-eb4a2913cb91)

We plan to complete the above content this month, and hope to get approval and support according to the requirements in CONTRIBUTING.md.
As part of integrating open source research and development, we plan to provide relevant designs and codes to the community.

### 2. Additional context or comments

[design.docx](https://github.com/user-attachments/files/17676931/design.docx)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please add my wechat: crazypphage.

**Comment by dajianguo** [comment]
> Please add my wechat: crazypphage.

The user is not exitsts....
