### ISSUE TITLE
When uploading a pptx file, it prompts "invalid upload file".

### ISSUE THREAD

**Issue by jiaolongxue** [langgenius/dify#10469]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a chatflow.
2. The additional feature allows file uploads, but only for file types, excluding other types such as images or audio.
3. Upload a pptx file for conversation.
4. It response "invalid upload file".

### ✔️ Expected Behavior

run success

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/10419

https://github.com/langgenius/dify/issues/10220#issuecomment-2463632550
