### ISSUE TITLE
Forget Password use smtp to send email

### ISSUE THREAD

**Issue by bingbing6** [langgenius/dify#10466]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/988fafdd-70bf-4f9a-8d6b-9c7506d686a2)
Follow this configuration and restart docker, no mail received

### ✔️ Expected Behavior

get emails

### ❌ Actual Behavior

Follow this configuration and restart docker, no mail received

**Comment by bingbing6** [comment]
I followed this. I tried 465 and 25, and it didn't work

**Comment by LvDian666** [comment]
Try configuring MAIL_DEFAULT_SEND_FROM in the format of Name <email address>, for example: Jack <123@456.com>. The email address must match the SMTP_USERNAME, otherwise, the email will fail to send.
