### ISSUE TITLE
Request for API Interface to Update Document Segment Information Without File Upload

### ISSUE THREAD

**Issue by yjc980121** [langgenius/dify#10470]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using the Dify API to maintain the knowledge base, I need to update the segment information of a file. Through browser inspection, the request interface should be console/api/datasets/{dataset_id}/documents. However, in the existing API documentation, I did not find an equivalent interface.

The closest interface is POST /datasets/{dataset_id}/document/create-by-file, but this interface requires uploading a file. My requirement is to maintain the document segment information through the API without uploading a file.

Suggestion:

I hope Dify can provide an API interface that does not rely on file upload for directly updating the segment information of documents. This would allow for more flexible management and maintenance of the documents in the knowledge base.

**Comment by crazywoola** [comment]
![QQ_1731067857330](https://github.com/user-attachments/assets/31e82666-d3b7-4bcf-84c5-eadc6783087e)

**Comment by yjc980121** [comment]
> ![QQ_1731067857330](https://private-user-images.githubusercontent.com/100913391/384362586-31e82666-d3b7-4bcf-84c5-eadc6783087e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwOTEzMDksIm5iZiI6MTczMTA5MTAwOSwicGF0aCI6Ii8xMDA5MTMzOTEvMzg0MzYyNTg2LTMxZTgyNjY2LWQzYjctNGJjZi04NGM1LWVhZGM2NzgzMDg3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxODM2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGZkY2NmMjQyZjllNzIzZTE0NGVjYmI2N2M1MTVhZDU4Y2ExNDJkNjkxZmU0MjZlNTFjMzg3NzE3NGMxMzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kpZlK3KphxXoB0pyUyE6-g-BdcbBxudIT3VvxfcHALc) Navigate to knowledge/api, you will see the docs here. You should not use api starts with services, instead, you should use these apis provided in this doc,

I want to re segment instead of update segments, the number of segments will change, modify process_rule
