### ISSUE TITLE
Optional varibles not configured correctly for chatbot

### ISSUE THREAD

**Issue by fdb02983rhy** [langgenius/dify#10489]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[test DSL.yml.zip](https://github.com/user-attachments/files/17686975/test.DSL.yml.zip)

### ✔️ Expected Behavior

User can leave select variables and file variables empty when they are optional(not required).

#### Setting:
![image](https://github.com/user-attachments/assets/bdec4cf8-a28a-4025-9415-c173ea7d8e8e)
#### Result:
![image](https://github.com/user-attachments/assets/1e8e6e21-aec6-4463-8a11-d56a8115e6a8)
---
#### Setting:
![image](https://github.com/user-attachments/assets/c16412f1-97c3-4e4b-a9f1-84629c67a397)
#### Result:
![image](https://github.com/user-attachments/assets/2829947d-a733-4475-9484-07b96925147e)

**Comment by laipz8200** [comment]
I cannot reproduce this issue, could you please try to remove your local docker images and pull them again?
