### ISSUE TITLE
Problem in the workflow conversation

### ISSUE THREAD

**Issue by sandycs-protoss** [langgenius/dify#10484]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

In this multi-turn dialogue workflow, I use the image_file variable to upload image URLs. However, I've noticed that it consistently references the URL of the first uploaded image. In other words, once an image is uploaded, even if I subsequently upload different image URLs, the logs show that it always calls the image URL that was initially provided in this conversation.

My conversation ID is: e5088572-49f7-4f9f-88c1-4d3eed8c1f9f
This is the data I post to API:
{"inputs":{"image_file":{"type":"image","transfer_method":"remote_url","url":"[https://img.calceus.org/wechat/2270171153495604502.jpg?x-oss-process=image/resize,w_1500"}},"query":"请帮我分析这张图片","response_mode":"streaming","conversation_id":"e5088572-49f7-4f9f-88c1-4d3eed8c1f9f","auto_generate_name":false,"user":"wechatbot","files":[{"type":"image","transfer_method":"remote_url","url":"https://img.calceus.org/wechat/2270171153495604502.jpg?x-oss-process=image/resize,w_1500"}]}](https://img.calceus.org/wechat/2270171153495604502.jpg?x-oss-process=image/resize,w_1500%22}},%22query%22:%22%E8%AF%B7%E5%B8%AE%E6%88%91%E5%88%86%E6%9E%90%E8%BF%99%E5%BC%A0%E5%9B%BE%E7%89%87%22,%22response_mode%22:%22streaming%22,%22conversation_id%22:%22e5088572-49f7-4f9f-88c1-4d3eed8c1f9f%22,%22auto_generate_name%22:false,%22user%22:%22wechatbot%22,%22files%22:[{%22type%22:%22image%22,%22transfer_method%22:%22remote_url%22,%22url%22:%22https://img.calceus.org/wechat/2270171153495604502.jpg?x-oss-process=image/resize,w_1500%22}]})

### ✔️ Expected Behavior

It should use the image_url everytime I sent it

### ❌ Actual Behavior

Use the same image_url everytime

**Comment by sandycs-protoss** [comment]
How to send the file url using sys.files via  API?

> I found a similar unsolved discussion regarding issues with uploading images via the Dify API, which might be related to your problem. You can check it out here: [I can't upload the image on dify workflow via api](https://github.com/langgenius/dify/discussions/7482) [[1]](https://github.com/langgenius/dify/discussions/7482).
> 
> Regarding your issue, it seems like the `image_file` variable is not updating as expected in your multi-turn dialogue workflow. In Dify version 0.11.0, there are known issues with the `image_file` variable, as it is marked as `LEGACY` and planned for deprecation. The image upload functionality is being integrated into a more comprehensive "file upload" feature. It's recommended to transition to using custom file variables instead of relying on the `sys.files` variable [[2]](https://github.com/langgenius/dify-docs/blob/main/en/guides/workflow/bulletin.md).
> 
> To address your issue, ensure that you are using the new file upload feature and custom file variables. This should help in correctly updating and referencing the latest image URL in your workflow.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

**Comment by crazywoola** [comment]
This. behavior is expected, since you can not change this `image_file ` once you start the conversation, because you named it as `image_file `. This is not the `sys.files` that you think.

Check the api endpoint

```
curl -X POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "What are the specs of the iPhone 13 Pro Max?",
    "response_mode": "streaming",
    "conversation_id": "",
    "user": "abc-123",
    "files": [
      {
        "type": "image",
        "transfer_method": "remote_url",
        "url": "https://cloud.dify.ai/logo/logo-site.png"
      }
    ]
}'
```

There is a `files` outside the inputs, things in here will go into the `sys.files`, the variable `image_file ` inside the `inputs` is the variable you defined, which you can not change.

**Comment by sandycs-protoss** [comment]
> This. behavior is expected, since you can not change this `image_file ` once you start the conversation, because you named it as `image_file `. This is not the `sys.files` that you think.
> 
> Check the api endpoint
> 
> ```
> curl -X POST 'https://api.dify.ai/v1/chat-messages' \
> --header 'Authorization: Bearer {api_key}' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "inputs": {},
>     "query": "What are the specs of the iPhone 13 Pro Max?",
>     "response_mode": "streaming",
>     "conversation_id": "",
>     "user": "abc-123",
>     "files": [
>       {
>         "type": "image",
>         "transfer_method": "remote_url",
>         "url": "https://cloud.dify.ai/logo/logo-site.png"
>       }
>     ]
> }'
> ```
> 
> There is a `files` outside the inputs, things in here will go into the `sys.files`, the variable `image_file ` inside the `inputs` is the variable you defined, which you can not change.

Sorry, but the files will not go into the sys.files. here is my data
{
  "inputs": {
    
  },
  "query": "帮我分析一下这个图片",
  "response_mode": "blocking",
  "conversation_id": "e5088572-49f7-4f9f-88c1-4d3eed8c1f9f",
  "auto_generate_name": false,
  "user": "wechatbot",
  "files": [
      {
         "type":"image",
    "transfer_method":"remote_url",
    "url":"https://img.calceus.org/wechat/2270171153495604502.jpg?x-oss-process=image/resize,w_1500"
      }
    ]
}

When I check the log in workflow, there is nothing in the sys.files.
