### ISSUE TITLE
When the token expires, refreshing the token can result in an infinite loop.

### ISSUE THREAD

**Issue by wangxm345566462** [langgenius/dify#10494]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/2af80424-627b-4f9b-b109-1ee130858089)
Steps:

Create a new chat.
Configure any custom tool.
Engage in normal conversation.
Wait for some time until the token expires.
Continue the conversation, and the system will start excessively calling the /console/api/apps/4e2a312e-cb06-41b0-a191-a94d42d85523/chat-messages endpoint, resulting in an infinite loop.

### ✔️ Expected Behavior

ok

### ❌ Actual Behavior

loop

**Comment by crazywoola** [comment]
This should been fixed in v0.11.0. If you can reproduce this problem on latest version, please update the version in the description.

**Comment by wangxm345566462** [comment]
![image](https://github.com/user-attachments/assets/852f7339-b0ad-42ff-a1d8-8f74127132aa)
The version I mentioned in my question is actually 0.10.0. I made an error when writing it.

**Comment by wangxm345566462** [comment]
> This should been fixed in v0.11.0. If you can reproduce this problem on latest version, please update the version in the description.

I cannot consistently reproduce the issue either, but it occurred twice in one day during my conversations. The symptom is that a message gets stuck and does not receive a reply, with the backend logs indicating that it entered an infinite loop. Clicking "Stop Output" on the interface will cause the backend loop to exit, and the next message input might then respond normally. I believe this is a potential bug.

**Comment by crazywoola** [comment]
Well, it could be, but we need some details to reproduce this, please keep an eye on this issue, you could open another issue later if you encountered it again, we seems to have some related fixes regarding the tokens.
