### ISSUE TITLE
Unable to retrieve url from file

### ISSUE THREAD

**Issue by XiaoLey** [langgenius/dify#10497]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

![can_not_get_url](https://github.com/user-attachments/assets/4af2f118-1c06-4f3e-83d8-6b2b032d789d)

**Comment by hjlarry** [comment]
this issue is same as https://github.com/langgenius/dify/issues/9567
now the file url of message history problem is already resolved ?

**Comment by XiaoLey** [comment]
> this issue is same as #9567 now the file url of message history problem is already resolved ?

@hjlarry My recent commit was a bit messy, and I am resubmitting a PR.

**Comment by hjlarry** [comment]
> > this issue is same as #9567 now the file url of message history problem is already resolved ?
> 
> @hjlarry My recent commit was a bit messy, and I am resubmitting a PR.

yeah, I mean if this PR resolved,   also can close  https://github.com/langgenius/dify/issues/9567  @crazywoola
