### ISSUE TITLE
Branch merge

### ISSUE THREAD

**Issue by Hope1u** [langgenius/dify#10519]
You seem to have misunderstood the meaning. It has nothing to do with the variable aggregator. This problem will occur when any other nodes are added before merging two branches, as follows:
There are three parameters. When test1 is not empty, branch 1 is taken. When q is not empty, branch 2 is taken. When w is not empty, branch 3 is taken. Branch 2 and branch 3 are merged. When testing, I assign test1 to 1, and the q and w parameters are not assigned values.
When there are no redundant nodes before merging nodes, the entire process ends after branch 1 is completed, as follows:
![image](https://github.com/user-attachments/assets/ea17c911-2c21-40ea-b218-c7d7a666c193)

When there is an additional node before the merge node, after completing branch 1, the merge node will continue to be taken, as follows:
![image](https://github.com/user-attachments/assets/a73d46a2-98ac-47ac-aef5-dde08021344b)

As long as you add any more nodes before merging them, this will happen:
For example, there are no redundant nodes before merging nodes.
![image](https://github.com/user-attachments/assets/5f472eb6-7664-46ac-aaf2-40aac6220908)
![image](https://github.com/user-attachments/assets/2d1ab3e4-39ec-41da-8c27-50a68f515fb8)

There are redundant nodes
![image](https://github.com/user-attachments/assets/ba95cf5c-b635-4d7b-8c98-6650c2e20e1c)
In fact, when I assign test1 to 1, branch 1 should be taken. At the same time, q and w are empty, then branch 2 and branch 3, these two conditional judgments should be over, so branch 1 is completed, and the entire process It should all end.

_Originally posted by @Hope1u in https://github.com/langgenius/dify/issues/10181#issuecomment-2453741183_

**Comment by crazywoola** [comment]
I reopened previous message, because this doesn't fit to our feature request template
