### ISSUE TITLE
cloud.dify.ai conversation records error

### ISSUE THREAD

**Issue by ouni3** [langgenius/dify#10527]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

On cloud.dify.ai, I logged in with the same account, but the account ID is different from the one I had a few days ago, and I am unable to retrieve the conversation records from the previous days.I accessed the bot using my phone and incognito mode and got different chat records, which means the account ID doesn't rely on the Dify account, but on the device, so once the device status changes, the account ID also changes, making it impossible to retrieve previous chat records
![image](https://github.com/user-attachments/assets/8281b1ba-f807-4fcb-af3e-92326298aa5d)

### ✔️ Expected Behavior

When the same account logs into the robot chat interface from a different device, it should have the same chat history.

### ❌ Actual Behavior

I logged in with the same account, but the account ID is different from the one I had a few days ago, and I am unable to retrieve the conversation records from the previous days.

**Comment by crazywoola** [comment]
This is an expected behavior, we do not have a place for chatbot login as well. So, no matter logged in or not, if you change to another browser or use open it in private mode, the conversation id will change for sure.
