### ISSUE TITLE
Handle file by Code Node

### ISSUE THREAD

**Issue by maekawataiki** [langgenius/dify#10528]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

- We would like to handle file by python (i.e. perform pandas groupby to uploaded csv file, pass to iterator then aggregate)
- Currently file cannot be passed to code node. File is handled by Doc Extractor and table data is converted to Markdown Table which is nice feature but lacks flexibility for advanced user.

### 2. Additional context or comments

Is there better way to handle complex data operation in Dify? (i.e. groupby, join, etc.)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by cpwan** [comment]
any updates?

**Comment by cpwan** [comment]
Problem still exists in 0.14.2
Related Issue #11789
![image](https://github.com/user-attachments/assets/11086377-78b9-4bc9-86fb-652facbbc6d9)

**Comment by huynhbaobk** [comment]
I already have the same problem. I think this feature is important for RAG. Sometimes, we need to add special tags or organize the structure of the extracted text, as this has a significant effect on the final answer. The Code Node should be have ability to process the files from upload files. Or the "Doc Extractor" Node should have feature add the custom @crazywoola
