### ISSUE TITLE
When calling the API interface that uses the Claude model (Anthropic), there are some errors that occur relatively frequently.

### ISSUE THREAD

**Issue by yangzxstar** [langgenius/dify#10520]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Errors with status code 400 are reported, which should not be the case since the input query is non-empty. The parameters should be properly encapsulated internally. The specific errors are as follows:

Dify调用异常】：
【ApiKey】: 
【接口】：chat-message
【error-message】: 返回error event，data:{"event": "error", "conversation_id": "81ea49cf-b12e-4c37-a864-208e64421e25", "message_id": "75b6d2cd-7f81-442e-84e0-237204dd862c", "created_at": 1731139300, "code": "completion_request_error", "status": 400, "message": "[anthropic] Bad Request Error, Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.9: all messages must have non-empty content except for the optional final assistant message'}}"}
【data】: {"sseEmitter":{"timeout":null},"userId":650251906,"type":2,"phase":1,"query":"利用验证码与前端建立半长链接，实现用户扫码关注并输入验证码后自动登录系统。\n借助 Redis 的 zet 数据结构实现轻量级的作者白名单，提升优秀作者发布文章的用户体验。\n使用Redis的zset实现用户活跃度排名，并通过先写入MySQL再同步删除Redis数据的策略，确保高并发\n环境下的缓存一致性。\n通过 AOP + TraceID 记录接口访问日志，实现任务的追踪、监控和诊断。\n通过 Canal 框架实现了 MySQL 与 ElasticSearch 的数据同步，确保了实时搜索的准确性。\n将用户评论、点赞、收藏、系统消息发送到 RabbitMQ，实现消息的异步解耦。","apiKey":"app-QSU0YVt3AkTpPrmslXzOpKy3","conversationId":"7cdeab5ced5a4c8591b01e5fe996ef74","apiConversationId":"","answer":null,"radioUrl":null,"videoUrl":null}

### ✔️ Expected Behavior

normal

### ❌ Actual Behavior

400 error

**Comment by crazywoola** [comment]
- Upgrade to

**Comment by yangzxstar** [comment]
> There are 2 things you could do
> 
> * Upgrade to v0.11.0
> * Claude series accept `user` and `assistant` only. So please check the LLM node in the workflow and make sure there is no `system`.

We are using the chatbot model, not the workflow model. I understand that both the system and the assistant are managed by Dify.
