### ISSUE TITLE
postgreSQL read-write separation  unsupported

### ISSUE THREAD

**Issue by huanshare** [langgenius/dify#10521]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I used the cluster version of "PolarDB PostgreSQL" on Alibaba Cloud, I found that the service was unavailable and I had to switch to the standard version. When will PostgreSQL read-write separation be supported?

### ✔️ Expected Behavior

support PostgreSQL read-write separation

### ❌ Actual Behavior

unsupport

**Comment by crazywoola** [comment]
Please post this as a feature request template thanks :)
