### ISSUE TITLE
Fail to get `file.url`, output empty string

### ISSUE THREAD

**Issue by AnoyiX** [langgenius/dify#10526]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![WX20241111-113825](https://github.com/user-attachments/assets/12c697d6-63f8-4f08-ad7c-a045f79fd545)

input a file, and output the file url

### ✔️ Expected Behavior

output the signed file url

### ❌ Actual Behavior

output empty string

**Comment by crazywoola** [comment]
Duplicated

**Comment by yhXu1** [comment]
请问，现在这个问题解决了吗？我在使用mineru插件的过程中，发现“开始”节点存在着文件的url但是在传递给mineru时，这个url就会消失。这个问题好像跟您的这个类似

**Comment by AI-Hao07** [comment]
我也是 从mineru得到的图片链接会失效，存入知识库中 图片并不能返回显示出来
