### ISSUE TITLE
 The input variable cannot be updated in the same session

### ISSUE THREAD

**Issue by liuzixiao666** [langgenius/dify#10522]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0e8e24a3-eb44-40e7-b4c5-8c45958a5849)
As shown in the figure, when I pass in the input variable (with only the 'a' variable inside), only the value of the 'a' variable is determined when creating the conversation. Continuing the conversation afterwards cannot change the value of the 'a' variable no matter what, which is something I don't want to see,
My current scenario is a conversational robot that needs to provide real-time strategic responses based on the current reception time and employee status. However, I do not want to lose the user's short-term memory as employee status is constantly changing
I have also reviewed previous issues and know that dify has a feature called "session variable", but I cannot assign this variable to it in any form as input. It cannot autonomously determine when updates are needed and why the content needs to be updated

### ✔️ Expected Behavior

There can be a variable that will be updated in the workflow as a conversation progresses in real-time, rather than being fixed only when the conversation is created

### ❌ Actual Behavior

Related issues：
[https://github.com/langgenius/dify/issues/4969](url)
[https://github.com/langgenius/dify/issues/8546](url)

**Comment by crazywoola** [comment]
I have checked with our dev team several times, we will remain this behavior. Sorry.

**Comment by liuzixiao666** [comment]
> I have checked with our dev team several times, we will remain this behavior. Sorry.

Is there no way to input variable parameters into the workflow in the conversation？

**Comment by jamesfebin** [comment]
Folks variables by definition has to be varies or updatable, otherwise rename to something like conversation constants. So it's communicated without ambiguity. Because developers make decisions based on the terms you use on document and then you get a surprise.

**Comment by hs354355279** [comment]
I've encountered this situation too. Is there any way to resolve it at the moment?
