### ISSUE TITLE
unsupported_file_type

### ISSUE THREAD

**Issue by FBR65** [langgenius/dify#10531]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![file_upload](https://github.com/user-attachments/assets/a8dabec2-626b-40bb-a09f-18931cc424bf)

I wanted to upload a PNG. I tried PNG and png.

{
  "code": "unsupported_file_type",
  "message": "File type not allowed.",
  "status": 415
}

### ✔️ Expected Behavior

Uploaded File

### ❌ Actual Behavior

Can't upload any kind of file, not only images.

**Comment by FBR65** [comment]
The storage was emptyed before.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues?q=is%3Aissue+unsupported_file_type+is%3Aclosed

**Comment by FBR65** [comment]
The Problem isn't fixed, even if you close my Issue

**Comment by crazywoola** [comment]
> The Problem isn't fixed, even if you close my Issue

Yes, but this is deprecated, we still working on it.

**Comment by laipz8200** [comment]
it's fixed in 0.11.1
