### ISSUE TITLE
ES:Failed to parse mapping: Field [similarity] requires field [index] to be configured

### ISSUE THREAD

**Issue by huanshare** [langgenius/dify#10547]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When using es as the vector library and uploading a file, an error is reported during parsing: BadRequestError(400, 'mapper_parsing_exception', 'Failed to parse mapping: Field [similarity] requires field [index] to be configured').

es version：8.9.1

### ✔️ Expected Behavior

Parsing success

### ❌ Actual Behavior

Field [similarity] requires field [index] to be configured')

I change this,it works
![WX20241111-180101@2x](https://github.com/user-attachments/assets/85ea1b7c-31b9-4555-8dd4-3e2bf836fa73)

**Comment by JohnJyong** [comment]
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/a76749b7-4162-4672-8615-86f98f5f56a7">
emmm, the `index` Parameter is optional in the document
