### ISSUE TITLE
knowledge database shows deprecated sign when workspace rereank model not set and rerank model mode selected in retrieval setting

### ISSUE THREAD

**Issue by AkisAya** [langgenius/dify#10552]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. do not configure workspace rerank model
2. in a knowledge dataset retrieval setting, select rerank model mode

![0zm6b12000gm9l3rw9E68](https://github.com/user-attachments/assets/40115c2a-2a34-48dd-a331-1f0e21d04568)

### ✔️ Expected Behavior

lead user to configure a rerank model just like we do when we want choose a text-embedding model

### ❌ Actual Behavior

just like the image shows

**Comment by AkisAya** [comment]
i figure out that this is a bug.
i think the deprecated hint heres tends to say the the workspace has a default rereak model, but after doing some front-end logic we find current rerank model not enabled, so this current model is deprecated.
![Snipaste_2024-11-11_19-27-58](https://github.com/user-attachments/assets/5091d802-c09b-423d-a2d5-d9a8f28b9550)
but here defaultModel is actually a model struct with all fileds empty string like this
```json
{
 "provider":"",
 "model": ""
}
```
in this situation, the default model is actaully emtpy and not valid.
so here instead of showing the deprecated sign, it's more likely that we tell users to configure at least a rerank model for the workspace like we do for the text-embedding model when it's not set

**Comment by crazywoola** [comment]
Feel free to open a PR for this.

**Comment by johnnashautomation** [comment]
Hi, I had the same issue in Ollama 0.0.5 version. 
In the **Plugins** page if you delete Ollama and Re-Install it. Ollama 0.0.6 will installed (by this message written) 
Then if you open **Settings** page and open **Model Provider** section and you can click on Ollama then you can see the models will appear on there. 
So that you can check your Workspaces everything should be fine.
I hope that helps
