### ISSUE TITLE
Cannot obtain a URL when uploading local file

### ISSUE THREAD

**Issue by gaozhengzhou** [langgenius/dify#10566]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

workflow: 
![image](https://github.com/user-attachments/assets/dad42a6d-3065-477a-9e36-652d1d91d429)
![image](https://github.com/user-attachments/assets/e1a1a2ad-d164-46e3-a92e-3a3027781c72)

upload local file:
![image](https://github.com/user-attachments/assets/0322a2f4-13dd-4436-9027-9b72e9ea43a4)

paste file link: 
![image](https://github.com/user-attachments/assets/7600dac8-5af2-4209-9c64-b868a02c263c)

logs:
![image](https://github.com/user-attachments/assets/fd3e2a05-8329-44e9-92bd-b6e725d81687)
![image](https://github.com/user-attachments/assets/5b757b92-359c-4a02-9e5e-9b06d60b1109)

### ✔️ Expected Behavior

The expectation is that both locally uploaded files and remote linked files can obtain a URL.

### ❌ Actual Behavior

Cannot obtain a URL when uploading local file.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9567
I've pinned this issue.
