### ISSUE TITLE
Node Variable Aggregator not work on version 0.11.0

### ISSUE THREAD

**Issue by KevinZhang19870314** [langgenius/dify#10569]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/48d0bef3-17c2-43eb-8f11-e255e07a35b7)

1. Create a chatflow with this dsl file;
2. Ask for "hi";
[Variable Aggregator.zip](https://github.com/user-attachments/files/17710479/Variable.Aggregator.zip)

### ✔️ Expected Behavior

It should output both Dog and Cat.

### ❌ Actual Behavior

There is one animal mentioned: a cat.

**Comment by KevinZhang19870314** [comment]
Attach the node run details.
![image](https://github.com/user-attachments/assets/14234908-fe48-4acf-aa3b-2266ef35f766)
![image](https://github.com/user-attachments/assets/534c0129-a791-4ad6-9125-fafce5c08de9)
![image](https://github.com/user-attachments/assets/1f126972-e73d-485d-8ab7-deb2b7c3b958)
![image](https://github.com/user-attachments/assets/ebc9e456-8276-4134-9078-7a2d67a08e62)

**Comment by crazywoola** [comment]
Duplicated, the variable aggregator will not merge things together as you expected.  

Please search existing issues. https://github.com/langgenius/dify/issues/8420
