### ISSUE TITLE
Doc Extractor Node it support parsing files with json file?

### ISSUE THREAD

**Issue by BenjaminX** [langgenius/dify#10560]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Doc Extractor node Is there any special consideration for not supporting json files?

### 2. Additional context or comments

support json files?
give me a task.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I think there is a close PR https://github.com/langgenius/dify/pull/9899

**Comment by BenjaminX** [comment]
> I think there is a close PR #9899

I misspoke. Actually, it's the upload file function that doesn't allow uploading JSON files.

**Comment by BenjaminX** [comment]
Other file types
allowed .json
