### ISSUE TITLE
upload document

### ISSUE THREAD

**Issue by af-74413592** [langgenius/dify#10568]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/a820ae27-e890-4daa-9f3a-61ccdf53d8be)
上传之后一直显示解析0%，只有一个文件，排队中，pdf和txt都测试过了。

**Comment by crazywoola** [comment]
- All descriptions should be English
- Please provide the container logs, an image isn't enough to investigate the issue.

**Comment by sweetkey** [comment]
Same thing here, After upgraded to 0.11.1, new uploaded files stay at the status of Queuing. 

By the way, where to find the log file?

**Comment by RollingDonkeyX** [comment]
Same thing here, After upgraded to 0.11.1,

**Comment by negative-crush** [comment]
Same thing here, After upgraded to 0.11.1,
![微信截图_20241113193446](https://github.com/user-attachments/assets/4d0de012-5b40-4f74-be66-7ac93fc3dd4d)

**Comment by negative-crush** [comment]
![Uploading image.png…]()

**Comment by negative-crush** [comment]
![image](https://github.com/user-attachments/assets/c15f2040-0301-49e3-9f1a-7f20e67aceaf)

**Comment by Kevinhuhu** [comment]
Same thing here, After upgraded to 0.11.1
![QQ_1731608406638](https://github.com/user-attachments/assets/6b1259c4-b0ba-438d-8626-05fd3f935640)

**Comment by burnedsyn** [comment]
> Same thing here, After upgraded to 0.11.1 ![QQ_1731608406638](https://private-user-images.githubusercontent.com/7582366/386321899-6b1259c4-b0ba-438d-8626-05fd3f935640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDQ4MDIsIm5iZiI6MTczMTk0NDUwMiwicGF0aCI6Ii83NTgyMzY2LzM4NjMyMTg5OS02YjEyNTljNC1iMGJhLTQzOGQtODYyNi0wNWZkM2Y5MzU2NDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMTU0MTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2NmNDMxMTcyODMzNWFiNWQxNmVmYzc2ZDY5MjA2MDM3MjNjMWQyNmU0MzdiYTY0MDllM2MzZDZjMjhkMDY3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4XxywwQtM759Phqq4tMe1QawKFPFc8v_rJQ0DTrJaxE)

i had the same thing with 0.11.1 just upgraded to 0.11.2 and it work fine
