### ISSUE TITLE
Agent mode needs to support image upload/input

### ISSUE THREAD

**Issue by Modas-Li** [langgenius/dify#10574]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Agent mode needs to support image upload/input

### 2. Additional context or comments

thx

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We do support, please read the docs.

https://docs.dify.ai/guides/workflow/bulletin#for-dify-cloud-users

**Comment by Modas-Li** [comment]
> We do support this feature long time ago, please read the docs.
> 
> https://docs.dify.ai/guides/workflow/bulletin#for-dify-cloud-users

![image](https://github.com/user-attachments/assets/87d70e87-f144-4e3f-bbe4-ae3a71e7122e)
there is no image upload feature in agent mode. my dify version is 0.11.0.
