### ISSUE TITLE
Feishu Spreadsheet Failed to Read Worksheet

### ISSUE THREAD

**Issue by chattor** [langgenius/dify#10570]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When using the node to read row data from a Feishu spreadsheet, a number was input to specify the number of rows to read. However, an error message appeared. The error display is as follows:
![Xnip2024-11-12_11-07-16](https://github.com/user-attachments/assets/84ee93dc-52cf-44ee-a5b4-d8be27a1a368)

### ✔️ Expected Behavior

Reading worksheet row data using the spreadsheet works correctly.

### ❌ Actual Behavior

Reading worksheet row data using the spreadsheet fails to read data correctly.

**Comment by crazywoola** [comment]
@hgnulb Can you take a look at this issue?

**Comment by chattor** [comment]
The starting line number cannot be entered as a variable for now and can only accept numbers. Although this solves the issue of the node being unavailable when reading Lark (Feishu) spreadsheets, it also results in the inability to read data from a long spreadsheet in multiple parts. I hope you can retain the feature that allows variables to be entered for the starting line number. Thank you for your hard work.

**Comment by chattor** [comment]
> @hgnulb Can you take a look at this issue?

The starting line number cannot be entered as a variable for now and can only accept numbers. Although this solves the issue of the node being unavailable when reading Lark (Feishu) spreadsheets, it also results in the inability to read data from a long spreadsheet in multiple parts. I hope you can retain the feature that allows variables to be entered for the starting line number.
