### ISSUE TITLE
File Support For Qwen-long

### ISSUE THREAD

**Issue by TChengZ** [langgenius/dify#10576]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1、add a llm node using Qwen-Long
2、passing a long text into system
![image](https://github.com/user-attachments/assets/60cce233-06f8-458e-8605-a76192ef7615)
3、trigger the node,but fail like 
![image](https://github.com/user-attachments/assets/81340fea-f068-4e6c-843d-1b92a3927883)

since qwen-long support 10000k tokens and like the [doc](https://help.aliyun.com/zh/model-studio/user-guide/long-context-qwen-long?spm=5176.21213303.J_qCOwPWspKEuWcmp8qiZNQ.1.57c22f3dBrFBv0&scm=20140722.S_help@@%E6%96%87%E6%A1%A3@@2846146._.ID_help@@%E6%96%87%E6%A1%A3@@2846146-RL_qwen~DAS~longSingleroundfile~DAS-LOC_llm-OR_ser-V_4-RE_new3@@cardNew-P0_0) 
![image](https://github.com/user-attachments/assets/8b73c33b-1e30-4639-b9d4-10711825aa06)
if the input text longer than 1m token，it will failed,and suggest using file-id mode to enable large tokens,but dify llm node seems not to support this.

### ✔️ Expected Behavior

using Qwen-Long with large tokens running successful

### ❌ Actual Behavior

fail with large tokesn

**Comment by crazywoola** [comment]
There are few things you might misunderstood.
- You don't need the tongyi model to understand file, because the doc extractor will produce things in Array[text].
- You reference the result of the doc extractor twice, which might exceed the length
- Please use `/context` to add things in system prompt. FYI, tongyi doesn't seem to support this role, you can change it to `user` instead.

**Comment by TChengZ** [comment]
> There are few things you might misunderstood.
> 
> * You don't need the tongyi model to understand file, because the doc extractor will produce things in Array[text].
> * You reference the result of the doc extractor twice, which might exceed the length
> * Please use `/context` to add things in system prompt. FYI, tongyi doesn't seem to support this role, you can change it to `user` instead.

i can remove the doc extractor, and i don't understant the /context u said, how to use /context
in offical qwen-long website, i can just upload a file and ask like below
![image](https://github.com/user-attachments/assets/ecc2f7e0-6357-4135-b870-d13d6a4f6b90)
how can i simulate this process in dify

**Comment by TChengZ** [comment]
i use /context in the user, and i am sure the doc is under 10000k tokens，it still exceed the tokens
![image](https://github.com/user-attachments/assets/b91c0068-5e6a-420c-9082-42d71c8d4d6b)
