### ISSUE TITLE
How to use qwen-long support 1000k tokens

### ISSUE THREAD

**Issue by TChengZ** [langgenius/dify#10586]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/6d7b92df-8b0c-4e1b-a017-8d7e726380f4)
for using long context in qwen-long, the offical qwen developer say it must be file upload for 1000k tokens using file-id mode
![image](https://github.com/user-attachments/assets/f0863828-da42-4417-bf02-c14616d7060b)

but in dify when choose llm node using qwen-long，how to use file-id mode
![image](https://github.com/user-attachments/assets/8cebaf7c-04cf-46ee-9cb2-657ceac370db)
i can only see the pure-text mode，this mode only support 9k tokens

### ✔️ Expected Behavior

qwen-long support large tokens

### ❌ Actual Behavior

qwen-long only support pure text mode which only support 9k tokens

**Comment by crazywoola** [comment]
We use doc extractor to make this functionality(file upload) available for all kinds of LLMs. The LLM node accepts the string only, it means it can not read the file directly.
Maybe the agent can accepts this file as an input, but we need to modify the code here.

https://github.com/langgenius/dify/blob/033ab5490bf9b23516edbf1db0aaf7cf61721606/api/core/model_runtime/model_providers/tongyi/llm/llm.py

Hence, if you have a question, please use the discussion instead. This template is bug report only. :)
