### ISSUE TITLE
The Template Transform node has error : operation not permitted

### ISSUE THREAD

**Issue by kkjinping** [langgenius/dify#10585]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. equals string has error
```
{% if text == '1' %}
1
{% endif %}
```
2. join is ok, but join(',') has error
```
{{text | join(','}}
```
3. replace has error, the example from dify doc
```
{{ item.content | replace('\n', '\n\n') }}
```
![1731398471116](https://github.com/user-attachments/assets/37eafdb3-1b35-48c5-be2f-92a67d2d4230)
![1731398475410](https://github.com/user-attachments/assets/49b35a09-80b8-478a-87d0-3eaade51aa2b)

### ✔️ Expected Behavior

no error

**Comment by crazywoola** [comment]
Thanks for reporting this issue, we will take a look at this later.

**Comment by kkjinping** [comment]
0.14 as well

**Comment by kkjinping** [comment]
@crazywoola

**Comment by xuemusi** [comment]
I also have this problem. The current version of dify is 0.14.1. Has it been solved?

**Comment by kkjinping** [comment]
> I also have this problem. The current version of dify is 0.14.1. Has it been solved?

It's not.

**Comment by yihong0618** [comment]
> {% if text == '1' %}
> 1
> {% endif %}

work fine on cloud and my local env

![image](https://github.com/user-attachments/assets/e8257f1e-6b3c-450d-b206-80043454a366)
![image](https://github.com/user-attachments/assets/6faa1315-33cf-46df-91cb-3b5580478b9c)

**Comment by xuemusi** [comment]
The problem I have is that the simple code works. But it won't work if you introduce sdk.

**Comment by kkjinping** [comment]
> > {% if text == '1' %}
> > 1
> > {% endif %}
> 
> work fine on cloud and my local env
> 
> ![image](https://private-user-images.githubusercontent.com/15976103/397602874-e8257f1e-6b3c-450d-b206-80043454a366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzcyOTYsIm5iZiI6MTczNDY3Njk5NiwicGF0aCI6Ii8xNTk3NjEwMy8zOTc2MDI4NzQtZTgyNTdmMWUtNmIzYy00NTBkLWIyMDYtODAwNDM0NTRhMzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA2NDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDZkZTVhYTg3MzM0NmMyNWNjOTM2ZDk1ZTYxMDExYmM1Yzg1MWI5OTY1ZmRkOTAzMThmMzZmZGU4OWMzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t6xy1LGEu6GwN2SBxeBa0VBSP079mYTP5F5e1Y75APM) ![image](https://private-user-images.githubusercontent.com/15976103/397602942-6faa1315-33cf-46df-91cb-3b5580478b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzcyOTYsIm5iZiI6MTczNDY3Njk5NiwicGF0aCI6Ii8xNTk3NjEwMy8zOTc2MDI5NDItNmZhYTEzMTUtMzNjZi00NmRmLTkxY2ItM2I1NTgwNDc4YjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA2NDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YjEyZmYwNzJhYTFiOGM2MWQ4Y2Q1YmY0MmMzOGYxOTAxYTczMjYwZTFjOTc0YjM3OTZjY2E2OTY5ZTI5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HW8gYajRcDe2guygqTnNQfkjc59R1lvX0Ab2PXtuq00)

Cloud is fine. But my local env based on Docker Compose is error.

**Comment by kkjinping** [comment]
## It has been found that the problem can be solved through the following steps:
1. Modify the volumes mapping of the sandbox in docker-compose.yaml, and add "/volumes/sandbox/conf:/conf".
2. Modify the "allowed_syscalls" in /volumes/sandbox/conf/config.yaml, and add "0-500".
