### ISSUE TITLE
iteration node cannot correctly return the file type

### ISSUE THREAD

**Issue by XiaoLey** [langgenius/dify#10596]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

![iter_img_error](https://github.com/user-attachments/assets/29c62910-7aad-49cc-9dcf-5954f2383761)

DSL file (needs to manually change the file extension to yml): 
[test_iter_img.txt](https://github.com/user-attachments/files/17715775/test_iter_img.txt)

**Comment by crazywoola** [comment]
Please remove this node and add it again to see if this is resolved, we have found some issues related to #10421. We will fix it later.

**Comment by XiaoLey** [comment]
@crazywoola The problem still exists and has not been resolved

**Comment by yihong0618** [comment]
> @crazywoola The problem still exists and has not been resolved

try to fix that, can you use my code(branch) to check?
