### ISSUE TITLE
fix: The url output by the list_operator is null

### ISSUE THREAD

**Issue by sunxiaojia123** [langgenius/dify#10590]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Cloud

### I want to use the list operation module to extract the URL of the file file, including the dify cloud and local deployment operations, and the workflow shows that it can be completed. As shown below:
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/c6687fcb-ef58-4dd2-810e-d3fe8811980f">

### However, on the dify cloud, the output is null, and in the local deployment, the output is path, but it does not contain parameters and cannot be used. As shown below:
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/1c3c46cc-f0eb-4ece-8fef-1028f1bed761">

### ✔️ Expected Behavior

image_url,As shown below:
<img width="292" alt="image" src="https://github.com/user-attachments/assets/4015386f-5329-4393-97d1-7d1e496b4447">

### ❌ Actual Behavior

"url": null

**Comment by XiaoLey** [comment]
hi, this issue has been fixed in this PR. just hang tight while it gets merged. 😊

**Comment by laipz8200** [comment]
duplicated with  #9567
