### ISSUE TITLE
访问API返回: {"code": "invalid_param", "message": "not enough....."}

### ISSUE THREAD

**Issue by kokais** [langgenius/dify#106]
调用对话性应用API接口: /v1/chat-messages
请求body `{"query":"你好","response_mode":"streaming","user":"10005","inputs":{}}`
请求Header已设置Authorization
请求返回 `{"code": "invalid_param", "message": "not enough values to unpack (expected 2, got 1)", "status": 400}`，
使用curl请求，返回也是相同的结果:
```
curl --location --request POST 'http://10.17.50.128:8000/v1/chat-messages' \
--header 'Authorization:app-xxxxxxxxxxxxxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "您好",
    "response_mode": "streaming",
    "user": "abc-123"
}'
```
返回:
`{"code": "invalid_param", "message": "not enough values to unpack (expected 2, got 1)", "status": 400}`

**Comment by takatost** [comment]
```
Authorization: Bearer app-xxxxxxxxxxxxx
```

需要加上 Bearer

**Comment by myjimmyzhou** [comment]
curl --location 'https://api.dify.ai/v1/chat-messages' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer app-xxxxxxxx' \
--data '{
    "query": "你好",
    "response_mode": "streaming",
    "user": "10005",
    "inputs": {}
}'
