### ISSUE TITLE
Unable to generate video normally using the cogvideo tool.

### ISSUE THREAD

**Issue by jiaolongxue** [langgenius/dify#10600]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Cogvideo has two tools: one for generating videos and the other for retrieving results. The tool for retrieving results needs to obtain the task status, and only when the task status is SUCCESS can the generated video be retrieved. How can this be accomplished within the workflow?

<img width="129" alt="e200aec1199a95f153e16146794c2a1" src="https://github.com/user-attachments/assets/b754835a-7ccc-489c-ba7d-fa44ab7e0fb5">

<img width="507" alt="9c8b4aa6fdd8c984cf63ba4536beb5e" src="https://github.com/user-attachments/assets/36928852-e157-4f2a-b8b6-43ea5ef83fd6">

### ✔️ Expected Behavior

The video can be successfully generated.

### ❌ Actual Behavior

Unable to generate video normally using the cogvideo tool.

**Comment by crazywoola** [comment]
You can use a code to to sleep 10 seconds.
