### ISSUE TITLE
After upgraded to 0.11.1, new uploaded files stay at the status of Queuing.

### ISSUE THREAD

**Issue by sweetkey** [langgenius/dify#10608]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgraded to 0.11.1, new uploaded files stay at the status of Queuing. 
- checked limits in the OPENAI, all good.
- Last time, the md files were uploaded into the knowledge base was at version 0.10.x. Worked fine.

### ❌ Actual Behavior

All new md files are in QUEUING...

**Comment by 1731563584** [comment]
There is a solution (no need to rollback version): https://github.com/langgenius/dify/discussions/10602

**Comment by sweetkey** [comment]
> There is a solution (no need to rollback version): #10602

Cool! It fixed the problem. Many thanks!

LOG_FILE=/app/logs/server.log

**Comment by sweetkey** [comment]
Refer to the solution https://github.com/langgenius/dify/discussions/10602. Key is to identify a log file

**Comment by gakugaku** [comment]
@sweetkey 
Thank you for sharing workaround.
Since this is clearly a bug, wouldn't it be better to wait for a fix rather than closing it with a workaround ?

**Comment by zhukefucn** [comment]
#10602 hasn't given solution，How can you do ?

**Comment by hxuaj** [comment]
> #10602 hasn't given solution，How can you do ?

Change the LOG_FILE and restart all services by 
```cmd
cd dify/docker
docker compose up -d
```
