### ISSUE TITLE
Can't Access GoogleSearch Results

### ISSUE THREAD

**Issue by weilun-enso** [langgenius/dify#10611]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Create a GoogleSearch Node and put in any input such as "List me the most recent soccer games.", connect it to the answer node and have the node output GoogleSearch's text.
<img width="739" alt="Screenshot 2024-11-12 at 4 01 21 PM" src="https://github.com/user-attachments/assets/b2cae3c4-411c-4871-a249-38b71c6503eb">
<img width="395" alt="Screenshot 2024-11-12 at 4 02 14 PM" src="https://github.com/user-attachments/assets/1ade5e69-cfe4-446b-8b54-2a22c13bac7e">

### ✔️ Expected Behavior

GoogleSearch's text results are shown

### ❌ Actual Behavior

Nothing come out of the answer node even though search results are there in the workflow process.
<img width="395" alt="Screenshot 2024-11-12 at 4 02 45 PM" src="https://github.com/user-attachments/assets/5e4a2914-e415-4e0c-80cd-97d12b4976f8">

**Comment by hjlarry** [comment]
the google search result is in the `json` field, not the `text` field

**Comment by weilun-enso** [comment]
Ok. Thanks. Got it. I needed a code block to receive it. It is resolved for now. Maybe I missed, but I think it needs to be mentioned in the doc or maybe populate the text field with dumped json string or something.

**Comment by zuohaoda** [comment]
> 好的。谢谢。明白了。我需要一个代码块来接收它。现在解决了。也许我错过了，但我认为需要在文档中提及它，或者用转储的 json 字符串或其他东西填充文本字段。

Have you resolved this issue, I am experiencing the same problem, is it possible to share the solution to deal with it, thanks!

**Comment by zuohaoda** [comment]
> Ok. Thanks. Got it. I needed a code block to receive it. It is resolved for now. Maybe I missed, but I think it needs to be mentioned in the doc or maybe populate the text field with dumped json string or something.

Have you resolved this issue, I am experiencing the same problem, is it possible to share the solution to deal with it, thanks!
