### ISSUE TITLE
there is no image upload feature in agent mode and  needs to support image upload/input

### ISSUE THREAD

**Issue by Modas-Li** [langgenius/dify#10616]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/user-attachments/assets/05f709ec-8f25-4380-9f03-78f8f76801af)
there is no image upload feature in agent mode and  needs to support image upload/input

### 2. Additional context or comments

my dify version is 0.11.0.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
The LLM with the eye icon has the ability to read image. Please switch to another model with this ability.
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/f3d3bce3-1345-4f6f-b297-febb3d871336">
