### ISSUE TITLE
Custom node POST request with parameters containing object references; the test interface parameters cannot be drilled down

### ISSUE THREAD

**Issue by docuxu** [langgenius/dify#10615]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After filling out the custom tool schema and preparing to test, I am unable to fill in the request parameters

**Comment by crazywoola** [comment]
This description seems too simple to guess what's going on.

Do you have any other information? Screenshot the schema?

**Comment by docuxu** [comment]
> This description seems too simple to guess what's going on.
> 
> Do you have any other information? Screenshot the schema?

like this
```components:
  schemas:
    UserDetail:
      type: object
      properties:
        address:
          type: string
          description: "用户的居住地址"
        phone:
          type: string
          description: "用户的联系电话"
    User:
      type: object
      required:
        - username
        - password
        - detail
      properties:
        username:
          type: string
          description: "用户名"
        password:
          type: string
          description: "用户密码"
        detail:
          $ref: '#/components/schemas/UserDetail' ```
The 'detail' will be interpreted as a string rather than an object

**Comment by crazywoola** [comment]
Due to the limitation of the current implementation, we do not support nested object for now.
