### ISSUE TITLE
The configuration of the same model was updated on the workbench, but the dialog configuration did not take effect.

### ISSUE THREAD

**Issue by dadastory** [langgenius/dify#10613]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I tried to modify a certain model parameter on the workbench, such as gpt-4o, modify parameters such as temperature or top k, max token, etc. After publishing and updating, the configuration in the dialog did not take effect, and I could only create a new dialog. At this time, configure will take effect

### ✔️ Expected Behavior

After the configuration of the same model is modified or the model is replaced, the historical conversations can be modified and updated synchronously to ensure a better user experience.

### ❌ Actual Behavior

This problem is very unfriendly to users who have preset parameter variables, because they must re-add a new conversation and repeatedly fill in the topic variables of the previous conversation, and modifications to some problematic conversation parameter configurations cannot take effect immediately.

**Comment by crazywoola** [comment]
> I tried to modify a certain model parameter on the workbench, such as gpt-4o, modify parameters such as temperature or top k, max token, etc. After publishing and updating, the configuration in the dialog did not take effect, and I could only create a new dialog. At this time, configure will take effect

Yes the configuration only takes effect for the new conversation. In another word, this is an expected behavior, see this 
 as well https://github.com/langgenius/dify/issues/10599#issuecomment-2470553368
