### ISSUE TITLE
Http requests will be killed.

### ISSUE THREAD

**Issue by hope12122** [langgenius/dify#10618]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

error: timeout error: signal: killed

### ❌ Actual Behavior

If an HTTP request takes too long, it will be killed by the Dify program. The request goes through when I use Python code on my local machine, but it gets killed in the Dify program. The request takes about 2 minutes to return a result.
![request](https://github.com/user-attachments/assets/e42ad462-2f96-4364-a189-26148622bddb)

**Comment by crazywoola** [comment]
Check the env settings in this `docker/.env.example`, and make sure these has been changed in the `.env` as well.

**Comment by hope12122** [comment]
Could u tell me dow to solve it? I have checked 'docker/.env.example' file. But I can't find related configuration and don't know how to modify this .

**Comment by zolgear** [comment]
The following environment variables need to be added manually, as they are not defined in `docker/.env.example` or `docker-compose.yaml`:  

- SSRF_DEFAULT_TIME_OUT  
- SSRF_DEFAULT_CONNECT_TIME_OUT  
- SSRF_DEFAULT_READ_TIME_OUT  
- SSRF_DEFAULT_WRITE_TIME_OUT  
- HTTP_REQUEST_MAX_CONNECT_TIMEOUT  
- HTTP_REQUEST_MAX_READ_TIMEOUT  
- HTTP_REQUEST_MAX_WRITE_TIMEOUT  

(Definitions and default values can be found in `api/.env.example`.)  

Even after setting all these to sufficiently high values, HTTP Request times out after 5 seconds when running long processes...

**Comment by liuzhenghua** [comment]
> * HTTP_REQUEST_MAX_CONNECT_TIMEOUT
How did this magic number 15 come about? I'm currently encountering occasional 15-second timeouts on the code node. My code node has sufficient resources, and I haven’t configured a timeout. Additionally, there’s no default value of 15 seconds in the dify config.
