### ISSUE TITLE
Abnormal CPU usage began to appear in version 0.11.1

### ISSUE THREAD

**Issue by kkjinping** [langgenius/dify#10619]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Since the update to version 0.11.1, there has been abnormal CPU usage even without any access.

0.11 is normal.

![1731467920845](https://github.com/user-attachments/assets/27f796e5-8869-4509-90ca-7d52f71c5918)
![1731467926370](https://github.com/user-attachments/assets/9a0e020e-5018-442a-b990-adc1bcc9ca3a)

### ✔️ Expected Behavior

normal CPU usage

### ❌ Actual Behavior

abnormal CPU usage

**Comment by kkjinping** [comment]
The abnormal CPU usage persists all the time.

**Comment by kurokobo** [comment]
Perhaps related to: https://github.com/langgenius/dify/issues/10555

Your worker container may keep restarting due to the above issue.

**Comment by kkjinping** [comment]
> Perhaps related to: #10555Perhaps related to: #10555 可能与以下相关： #10555
> 
> Your worker container may keep restarting due to the above issue.Your worker container may keep restarting due to the above issue.由于上述问题，您的 worker 容器可能会不断重启。

It's this problem. Thank you.
