### ISSUE TITLE
Added a new tool for Google News from the Rapid API

### ISSUE THREAD

**Issue by Tuyohai** [langgenius/dify#10620]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I have implemented the adaptation of the Google News tool myself, and its provider is rapidapi, which is a relatively well-known one, so it has a great adaptation value.

### 2. Additional context or comments

Please refer to the link for details:[https://rapidapi.com/bfd-id/api/google-news13/playground](url)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Feel free to submit a pull request.
