### ISSUE TITLE
The chat workflow is cluttered with answer nodes in the case of multi-conditional branching

### ISSUE THREAD

**Issue by skywolf123** [langgenius/dify#10638]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

There is a logical error in the chat workflow, and in the case of multiple conditional branches and multiple replies, redundant answers that are not on the branch route will appear.

As shown in the figure, if you only run on one branch, there should only be a final reply, but in fact there will be redundant answers.

![b161f6f955ef860eb89cf17c7c9b414](https://github.com/user-attachments/assets/b21c0d96-a72d-4d41-8d03-4cec26ccb861)

[test.zip](https://github.com/user-attachments/files/17728315/test.zip)

**Comment by crazywoola** [comment]
Duplicated with https://github.com/langgenius/dify/issues/10564
