### ISSUE TITLE
File validation failed when using custon file types in input

### ISSUE THREAD

**Issue by LiuBodong** [langgenius/dify#10637]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

* create a work flow with a start node and a end node.
* create a file list input field in start node.
![图片](https://github.com/user-attachments/assets/a418f8b3-6a11-4ce4-96d7-1b427121a474)

* run the work flow and choose a file, then start the flow.
![图片](https://github.com/user-attachments/assets/e53f2f53-e9fe-47e5-90cc-fd12d5874c0d)

### ✔️ Expected Behavior

upload and validate correctly

### ❌ Actual Behavior

![图片](https://github.com/user-attachments/assets/442859cf-3275-4d5e-b259-0b696b6568cb)

**Comment by crazywoola** [comment]
Why don't you just use the image type?

**Comment by LiuBodong** [comment]
When validate file extensions, the file extension contains a 'dot', such as: '.png', '.jpg'. but the "allowed_extensions" array DO NOT contains the 'dot', it looks like '["png", "jpg"]'

![图片](https://github.com/user-attachments/assets/5a9a89ab-f0f4-4f5a-9173-bfab2cba8dbe)

**Comment by LiuBodong** [comment]
> Why don't you just use the image type?

cause i have to deal with image or a tar binary together

**Comment by crazywoola** [comment]
I think you can check 2 types, image and other.

**Comment by crazywoola** [comment]
We had a fix recently #10111

**Comment by LiuBodong** [comment]
> I think you can check 2 types, image and other.



> When validate file extensions, the file extension contains a 'dot', such as: '.png', '.jpg'. but the "allowed_extensions" array DO NOT contains the 'dot', it looks like '["png", "jpg"]'
> 
> ![图片](https://private-user-images.githubusercontent.com/23203149/385635436-5a9a89ab-f0f4-4f5a-9173-bfab2cba8dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODI3MDksIm5iZiI6MTczMTQ4MjQwOSwicGF0aCI6Ii8yMzIwMzE0OS8zODU2MzU0MzYtNWE5YTg5YWItZjBmNC00ZjVhLTkxNzMtYmZhYjJjYmE4ZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3MjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTg0YWFlZjZjOWMzNjkwODQzNGE5OGU3YTJlMWUwMzdiNjNjYmZlOWQ2ZGE3Zjc1MGJhNGFhYWRjZjNmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h_nvTp1LWBbQGUdI27KqsLp0mgyYv7_04oRDE2D0r9U)

please just check this code and have a test

**Comment by laipz8200** [comment]
We are now processing this issue.

**Comment by qwfy326** [comment]
The bug is still exist if enabled the memory and talked more.
