### ISSUE TITLE
docker-compose up -d  Error response from daemon: failed to create task for container: failed to start shim: start failed:

### ISSUE THREAD

**Issue by sunsijia** [langgenius/dify#10633]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The server cannot pull dify directly
I downloaded the program and image locally and uploaded it to the server
Program decompression, image import
Start docker-compose up -d on the server
Tips
Error response from daemon: failed to create task for container: failed to start shim: start failed:  io.containerd.runc.v2: failed to create temp file:  open  /run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/9cbd9512b23a669c5a6698f99971b28c3bc07d098852680ac90bd75 350384f8c/3094749549: no such file or directory: exit status 1: unknown
![微信截图_20241113142400](https://github.com/user-attachments/assets/c10e221b-55f7-4584-985a-3aee44c4341e)
![image](https://github.com/user-attachments/assets/3621f587-d4e9-4c80-808d-0e22afd834d4)

### ✔️ Expected Behavior

Can display normally

### ❌ Actual Behavior

Error response from daemon: failed to create task for container: failed to start shim: start failed: io.containerd.runc.v2: failed to create temp file: open /run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/9cbd9512b23a669c5a6698f99971b28c3bc07d098852680ac90bd75350384f8c/3094749549: no such file or directory: exit status 1: unknown

**Comment by crazywoola** [comment]
It's unrelated to our project I think, you should google it to resolve this issue.
