### ISSUE TITLE
Approval process setting

### ISSUE THREAD

**Issue by shota-tabara** [langgenius/dify#10649]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

-

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I created [GL-2024-11-00066](https://wd3.myworkday.com/cookpad/d/inst/1$871/873$22171.htmld), approval process did not start and automatic approval was triggered and the journals were posted instead.
<img width="1856" alt="GL-2024-11-00066" src="https://github.com/user-attachments/assets/9f18f442-5e03-457d-800a-dc7030bfdc14">

### ✔️ Expected Behavior

Appropriate approval process is completed.

### ❌ Actual Behavior

Approval process did not start and automatic approval was triggered and the journals were posted instead.

**Comment by crazywoola** [comment]
I am not sure this is related to our project. If you encounter errors, please provider information of version and error logs.
