### ISSUE TITLE
For each node is not correctly counted in token usage

### ISSUE THREAD

**Issue by LeonKalt** [langgenius/dify#10655]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a workflow with a for each loop and a normal LLM node
2. Run Workflow and check the token amount measured via dify and via an external monitoring tool 

### ✔️ Expected Behavior

I expect all tokens to be counted inside a workflow 

### ❌ Actual Behavior

tokens used inside a for each loop is missing from the workflow monitoring inside dify

**Comment by s2terminal** [comment]
I'm having the same problem as this issue. (Dify version 0.12.1)

https://github.com/langgenius/dify/blob/0.12.1/api/core/workflow/nodes/iteration/iteration_node.py#L257-L262

I think the problem is that `total_tokens` is not included in the `metadata` of `run_result`.
