### ISSUE TITLE
Support Keyboard Control for the TTS Player

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#10668]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, the tts feature can only be controlled by manually clicking the play/pause button. 

It would be more intuitive if users can use their keyboard to control the behavior of the audio player.

For example:
- Press the space bar to pause the audio.
- Press the space bar again to resume the audio.
- Press the left arrow key to go back 5 seconds.
- Press the right arrow key to forward 5 seconds.

This can open up many use cases in the context of education.

For example, students can listen to an English audio to practice their English listening comprehension.
- They can press the right arrow key to skip boring parts of the audio.
- They can press the left arrow key to replay the parts that they missed.
- They can press the space bar to pause the audio when they need a break.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I think this is not suitable for the conversation, even with wechat, you can not control the audio message with message.

**Comment by taowang1993** [comment]
> I think this is not suitable for the conversation, even with wechat, you can not control the audio message with the keyboard.

But you can pause the audio by clicking the play/pause button on dify.
Isn't that just like an audio player?
