### ISSUE TITLE
Setup OpenRouter fails with "Credentials validation failed with status code 402"

### ISSUE THREAD

**Issue by LiviaH** [langgenius/dify#10667]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. login to openrouter.ai
2. Create a  Key
3. Copy the Key
4. login to cloud.dify.ai
5. go to Settings -> Model Provider
6. find "OpenRouter" and click "Setup"
7. paste the openrouter key into "API Key" field
8. click "Save"
9. popup with message "Credentials validation failed with status code 402" is shown

### ✔️ Expected Behavior

the API key is accepted and OpenRouter can used with API Key

### ❌ Actual Behavior

error occures, message: "Credentials validation failed with status code 402"

**Comment by LiviaH** [comment]
issue #1526 is not similar, you mix OpenRouter and OpenAI integration which are different cases. I assume the OpenRouter specific implementation needs to reviewed.

**Comment by LiviaH** [comment]
Still the same behavior in dify.ai 14.2.  openrouter is on the list of model providers but is not usable. Adding the API Key is not possible and produces an error with the message "Credentials validation failed with status code 402"

**Comment by shaotianchi** [comment]
I got same issue in latest version of dify.ai also self-host and cloud platform when I add deepseek model

**Comment by guangchen017** [comment]
This issue is still encountered in Dify version 0.15.3, i.e., the OpenRouter API Key cannot be configured, but a single model can be added successfully

**Comment by nilecui** [comment]
I also encountered the same problem

**Comment by LukaBanovic** [comment]
Still encountering the same issue with DeepSeek. @crazywoola

**Comment by Pixel2075** [comment]
Still the same issue with deepseek

**Comment by donnib** [comment]
This issue is still valid, the ticket should be open and not closed

**Comment by Arosy47** [comment]
Still the same issue with deepseek

**Comment by Andy7596183** [comment]
same issue with deepseek

**Comment by xjxtree** [comment]
same errors when setting deepseek API key

**Comment by zismylove** [comment]
现在还是同样的问题

**Comment by Aleegra** [comment]
same errors when setting deepseek API key

**Comment by xjxtree** [comment]
check your deepseek account balance first.

**Comment by fafactx** [comment]
same errors when setting deepseek API key.time: 2025/4/26.

**Comment by cyberjob001** [comment]
I have the same error with openrouter api key in self hosted dify

**Comment by badspider7** [comment]
> I have the same error with openrouter api key in self hosted dify

+1，how to slove this error,this is important for me.

**Comment by fengwang** [comment]
Please reopen this issue. I have this issue with qwen/qwen3-coder:free

**Comment by fengwang** [comment]
@crazywoola Please consider reopening this issue.
