### ISSUE TITLE
LLM Vision Error: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by RyanxLowz** [langgenius/dify#10670]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

enable vision on llm node and upload an image and pass it to llm 

### ✔️ Expected Behavior

llm should be able to receive and understand the image

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/113fcaeb-6d52-4bb3-adc3-d47541a7724b)

An error is shown at the LLM Node: Run failed: argument of type 'NoneType' is not iterable

**Comment by crazywoola** [comment]
Please upgrade to our latest version v0.11.1
