### ISSUE TITLE
Upload PDF prompt: failed: file type document is not supported

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#10672]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Hello, I would like to ask, I am using dify version 0.10.2 and have fully enabled the file upload function. However, I uploaded a PDF file with a file size of only 42.kb. When I tried to upload it, I received an error message: Run failed: file type document is not supported. I don't know what happened. Could you please take a look? As shown in the picture:

### ✔️ Expected Behavior

1>
![image](https://github.com/user-attachments/assets/774528aa-6b36-4d4e-ba9c-3adaff4b3955)
2>
![image](https://github.com/user-attachments/assets/fb87b309-25ad-455b-a496-2d1719581b2c)

**Comment by crazywoola** [comment]
Please upgrade to latest version.
