### ISSUE TITLE
when 1 or 2 external knowledge base are configed, any Dify knowledge base cannot be create successfully. the status is pending on queuing.

### ISSUE THREAD

**Issue by vicoxia** [langgenius/dify#10683]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="822" alt="Screenshot 2024-11-14 at 14 01 18" src="https://github.com/user-attachments/assets/2808484a-fb5c-4cd6-a750-6a5c025595bc">
 the first on is dify KB. the other 2 is bedrock kb and ragflow kb.

<img width="901" alt="Screenshot 2024-11-14 at 14 02 15" src="https://github.com/user-attachments/assets/170cab92-991c-412e-9c7e-844b92e11f16">

it's always pending on queuing.

### ✔️ Expected Behavior

dify kb can be created.

### ❌ Actual Behavior

dify kb is pending

**Comment by crazywoola** [comment]
Please attach the container logs of api and worker.

**Comment by 0xmalina** [comment]
@vicoxia I've also had this issue. I wanted to raise a PR to fix it but unfortunately I don't have access to contribute. Here's the fix that worked for me. Maybe someone can put in a fix if the PR is not already raised. Hope this helps.

### Solution
in `docker/docker-compose.yaml` in the `services.worker.networks` section [here](https://github.com/langgenius/dify/blob/2abacd2a2dea4d8cd29aac7a89f56654f508679e/docker/docker-compose.yaml#L319), the 2 networks (`ssrf_proxy_network` and `default`) should be the other way around.

```diff
networks:
+  - default
   - ssrf_proxy_network
-  - default
```

### Reason
I looked in the `worker` logs and saw an error message saying that the service couldn't resolve hostname `redis`:
`redis.exceptions.ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.`

The networks order matter. Docker uses the first network in the list as the default network for DNS resolution. `ssrf_proxy_network` is defined as an internal network. This means that services connected to this network cannot access external networks or services not connected to this network.

```
networks:
  ssrf_proxy_network:
    driver: bridge
    internal: true
```

Meanwhile, the `redis` service is only connected to the `default` network. Therefore, the worker service cannot resolve redis when using the ssrf_proxy_network because redis is not connected to this network.

```
services:
  redis:
    networks:
      - default
```

**Comment by cp19861214** [comment]
File "/app/api/.venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/app/api/.venv/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/celery.py", line 236, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/worker.py", line 348, in worker
    worker = app.Worker(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 98, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 131, in setup_instance
    self.on_init_blueprint()
  File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 116, in on_init_blueprint
    self._custom_logging = self.setup_logging()
  File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 180, in setup_logging
    return self.app.log.setup(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 63, in setup
    handled = self.setup_logging_subsystem(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 117, in setup_logging_subsystem
    self._configure_logger(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 150, in _configure_logger
    self.setup_handlers(logger, logfile, format,
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 216, in setup_handlers
    handler = self._detect_handler(logfile)
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 226, in _detect_handler
    return WatchedFileHandler(logfile, encoding='utf-8')
  File "/usr/local/lib/python3.10/logging/handlers.py", line 479, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
IsADirectoryError: [Errno 21] Is a directory: '/app/api'
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

**Comment by Cxtsl** [comment]
the same problem.
![api](https://github.com/user-attachments/assets/2861736f-cd0c-4a4d-9638-b108b5f87f59)
![worker](https://github.com/user-attachments/assets/9a7f4e64-7977-4062-b174-953d49b67b4d)

**Comment by 0xmalina** [comment]
@cp19861214 I also encountered this issue before the docker one I mentioned above. The fix for this is, head to your `.env` file (that you generated using `.env.example`) and set the variable `LOG_FILE`. I personally set it to `/app/api/app.log`. That worked for me. Let me know if this worked.
```
# Log file path
LOG_FILE=/app/api/app.log
```

**Comment by cp19861214** [comment]
@

> 0xmalina

I set LOG_FILE=/app/api/app.log  in .env file 
get same error

**Comment by 0xmalina** [comment]
@cp19861214 hmm. that's strange 😂 but can you double check the file was saved? also, I'm assuming you restarted the app using docker compose down and then docker compose up -d again, right? This worked for me and for other people who had the issue so I don't see why it wouldn't work to be honest.

**Comment by cp19861214** [comment]
@0xmalina 
look my .env file  
[env.txt](https://github.com/user-attachments/files/17746186/env.txt)

**Comment by 0xmalina** [comment]
@cp19861214 can you please delete the first line LOG_FILE=/app/api/app.log and instead set it under Server Configuration? I'm afraid that the env variable might be overwritten by that configuration and it's better to have it defined in one place. Like this.
[env.txt](https://github.com/user-attachments/files/17746249/env.txt)

**Comment by cp19861214** [comment]
@0xmalina  ok,I try it

**Comment by cp19861214** [comment]
@0xmalina Thank you ,It works

**Comment by vicoxia** [comment]
> @0xmalina
> 
> I set LOG_FILE=/app/api/app.log in .env file get same error
> 
> File "/app/api/.venv/bin/celery", line 8, in sys.exit(main()) File "/app/api/.venv/lib/python3.10/site-packages/celery/**main**.py", line 15, in main sys.exit(_main()) File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/celery.py", line 236, in main return celery(auto_envvar_prefix="CELERY") File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in **call** return self.main(*args, **kwargs) File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) File "/app/api/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func return f(get_current_context(), *args, **kwargs) File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/base.py", line 135, in caller return f(ctx, *args, **kwargs) File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/worker.py", line 348, in worker worker = app.Worker( File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 98, in **init** self.setup_instance(**self.prepare_args(**kwargs)) File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 131, in setup_instance self.on_init_blueprint() File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 116, in on_init_blueprint self._custom_logging = self.setup_logging() File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 180, in setup_logging return self.app.log.setup( File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 63, in setup handled = self.setup_logging_subsystem( File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 117, in setup_logging_subsystem self._configure_logger( File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 150, in _configure_logger self.setup_handlers(logger, logfile, format, File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 216, in setup_handlers handler = self._detect_handler(logfile) File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 226, in _detect_handler return WatchedFileHandler(logfile, encoding='utf-8') File "/usr/local/lib/python3.10/logging/handlers.py", line 479, in **init** logging.FileHandler.**init**(self, filename, mode=mode, File "/usr/local/lib/python3.10/logging/**init**.py", line 1169, in **init** StreamHandler.**init**(self, self._open()) File "/usr/local/lib/python3.10/logging/**init**.py", line 1201, in _open return open_func(self.baseFilename, self.mode, IsADirectoryError: [Errno 21] Is a directory: '/app/api'

same log

**Comment by 0xmalina** [comment]
@vicoxia are you setting the existing LOG_FILE in the `.env` file or did you create a new variable? can you please let me know how your .env file looks like? (specifically the Server Configuration bit, it should look like this) 

```
# ------------------------------
# Server Configuration
# ------------------------------

# The log level for the application.
# Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
LOG_LEVEL=INFO
# Log file path
LOG_FILE=/app/api/app.log
# Log file max size, the unit is MB
LOG_FILE_MAX_SIZE=20
# Log file max backup count
LOG_FILE_BACKUP_COUNT=5
# Log dateformat
LOG_DATEFORMAT=%Y-%m-%d %H:%M:%S
# Log Timezone
LOG_TZ=UTC
```

also, please double check you saved the changes after changing the file.

**Comment by zhenda-hub** [comment]
LOG_FILE=/app/api/app.log

**Comment by jafrank88** [comment]
S
[dify log 111424.txt](https://github.com/user-attachments/files/17758704/dify.log.111424.txt)
ame issue - self-hosted 0.11.1 in Docker - here is my log -

**Comment by crazywoola** [comment]
This error `IsADirectoryError: [Errno 21] Is a directory: '/app/api'` already has a solution https://github.com/langgenius/dify/discussions/10602.

- https://github.com/langgenius/dify/issues/10683#issuecomment-2475726282
- https://github.com/langgenius/dify/issues/10683#issuecomment-2477382993

These are correct. @cp19861214

**Comment by jafrank88** [comment]
I don't think this is resolved. I have attached .env and still have the issue. 
[env.txt](https://github.com/user-attachments/files/17760635/env.txt)

**Comment by crazywoola** [comment]
> I don't think this is resolved. I have attached .env and still have the issue. [env.txt](https://github.com/user-attachments/files/17760635/env.txt)

You need to restart the containers accordingly.

**Comment by jafrank88** [comment]
I have, I shut down docker and restarted the computer to be sure.

Brought up docker, ollama, and dify.

Still locked at queuing with one 9 chunk document.

Jonathan

**Comment by 0xmalina** [comment]
@jafrank88 can you provide your `docker/docker-compose.yaml` file please?

**Comment by jafrank88** [comment]
I have solved the issue somehow, but here is my file, if it helps.
