### ISSUE TITLE
HTTP Post form-data does not work with file (Could not parse multipart form)

### ISSUE THREAD

**Issue by saendu** [langgenius/dify#10694]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. create a flow with a file param
2. create a HTTP Post node with form-data 
3. attach file to form data
4. try to send multipart form to server

<img width="758" alt="image" src="https://github.com/user-attachments/assets/2557602d-4358-4a06-855d-6489cea6612d">

### ✔️ Expected Behavior

Correct parsing of multipart form. Adding Content-Disposition file to form-data. 

### ❌ Actual Behavior

Form-data is not correctly parsed. Content-Disposition data 'file' is missing. 

`
POST /v1/audio/transcriptions HTTP/1.1 
Host: api.openai.com 
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarymriqkhpjloahvxub 
Authorization: ***************************************************************************************************************************************************************************
 
------WebKitFormBoundarymriqkhpjloahvxub 
Content-Disposition: form-data; name="model" 
 
whisper-1 
------WebKitFormBoundarymriqkhpjloahvxub 
Content-Disposition: form-data; name="" 
 
 
------WebKitFormBoundarymriqkhpjloahvxub-- 

`

Error from server: Could not parse multipart form
"status_code": 400,
  "body": "{\n    \"error\": {\n        \"message\": \"Could not parse multipart form\",\n        \"type\": \"invalid_request_error\",\n        \"param\": null,\n        \"code\": null\n    }\n}\n",

**Comment by crazywoola** [comment]
- Starting from version 0.10.0, we changed the multipart requests to rely on httpx to organize requests instead of assembling them ourselves. However, httpx's behavior is to modify requests to x-www-form-urlencoded when no files are included. I plan to wait for the upstream to resolve this issue.
- The API provider needs to use the x-www-form-urlencoded format in the endpoint.

**Comment by crazywoola** [comment]
This pull request https://github.com/langgenius/dify/pull/10695 can resolve part of you problems, but it still does not fix current behavior.

**Comment by saendu** [comment]
> This pull request #10695 can resolve part of you problems, but it still does not fix current behavior.

Can you specify part of my problem?

**Comment by crazywoola** [comment]
> > This pull request #10695 can resolve part of you problems, but it still does not fix current behavior.
> 
> Can you specify 'part of my problem'?

You can use this new tool to get the transriptions from the OpenAI instead of using the HTTP Node.

**Comment by saendu** [comment]
> > > This pull request #10695 can resolve part of you problems, but it still does not fix current behavior.
> > 
> > 
> > Can you specify 'part of my problem'?
> 
> You can use this new tool to get the transcriptions from the OpenAI instead of using the HTTP Node.

Ok thanks. I guess this will be released with the next release? 
About the HTTP Post form-data. The strange thing about this bug is, it worked a couple of releases ago.

**Comment by laipz8200** [comment]
Hi @saendu. Could you provide a minimal dsl to reproduce this issue? I tried in our Cloud service by sending a text file to `httpbin.org`, and it works well.
