### ISSUE TITLE
error password variable name in docker-compose.yaml for vdb lindorm

### ISSUE THREAD

**Issue by AlwaysBluer** [langgenius/dify#10708]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when using the VDB lindorm in docker, it will connect  failed since the password variable name for lindorm vdb in docker-compose.yaml is LINDORM_USERNAME, not LINDORM_PASSWORD, error variable name.

### ✔️ Expected Behavior

connect vdb lindorm in a success

### ❌ Actual Behavior

connect failed, password is wrong

**Comment by crazywoola** [comment]
Hello Please checkout from our main branch and open this pr again. There are some conflicts.
