### ISSUE TITLE
Chatbot conversation logs with more than 10 messages are not surfaced/loaded/displayed

### ISSUE THREAD

**Issue by custom-prompter** [langgenius/dify#10702]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Open a chatbot app from the Studio.
2. Navigate to Logs & Ann.
3. In Logs, select a conversation with more than 10 messages to view it.
4. No messages are shown in the smaller window.
![Screenshot 2024-11-14 105539](https://github.com/user-attachments/assets/be5a95c9-d84e-41c3-aaec-743d9efeaf95)

### ✔️ Expected Behavior

See the message logs from all conversations, including the ones with more than 10 messages

### ❌ Actual Behavior

A blank window opens up and the messages are not loaded

**Comment by crazywoola** [comment]
Already fixed in https://github.com/langgenius/dify/pull/10119
