### ISSUE TITLE
#dify-chatbot-bubble-button is not adeed to the DOM in Safari

### ISSUE THREAD

**Issue by Borysiuk1** [langgenius/dify#10718]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Open Safari browser and observe that there is no button in the bottom right corner but it exists in Chrome.

### ✔️ Expected Behavior

Chat should work in Safari and #dify-chatbot-bubble-button should be added to the DOM.

### ❌ Actual Behavior

dify script and configs are added but #dify-chatbot-bubble-button is not adeed to the DOM in Safari, in Chrome and Firefox everything works fine, the url is https://lbcmortgage.com/properties/3405-wells-dr-plano-tx-75093-2/. There are no errors in the console.

![IMAGE 2024-11-14 23:50:09](https://github.com/user-attachments/assets/35ea4e60-1530-4164-a10f-1f89e77c9572)

**Comment by oleksandr-borysiuk-hkm** [comment]
Appeared that the problem was that app.dify script was added in <head>, I moved it before the </body> tag and it started working in Safari.

**Comment by Borysiuk1** [comment]
Appeared that the problem was that app.dify script was added in head, I moved it before the /body tag and it started working in Safari.

**Comment by Borysiuk1** [comment]
Appeared that the problem was that app.dify script was added in head, I moved it before the /body tag and it started working in Safari.
