### ISSUE TITLE
Optional Value Error: in input form must be a valid number

### ISSUE THREAD

**Issue by miyagipipi** [langgenius/dify#10727]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I set a optional number variable。
When I run without this variable, dify reports an error and displays "word_num in input form must be a valid number".
Word_num is my number variable name.
My dify version is 0.11.1 and i had read https://github.com/langgenius/dify/pull/10529.
I hope that the unfilled optional variable can be handled correctly here. (ex set it null?)
![20241115-113748](https://github.com/user-attachments/assets/5ba02da1-4ff8-43d4-b4bc-4356121d35d0)
![20241115-113912](https://github.com/user-attachments/assets/a109b8e1-1372-4984-baf1-cd4d5fc3609c)

### ✔️ Expected Behavior

unfilled optional number variable can be set as null or default?

### ❌ Actual Behavior

unfilled optional number variable in input form must be a valid number

**Comment by crazywoola** [comment]
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/1c24b57c-050c-4601-8991-6cf87f58638a">
Can't reproduce.

**Comment by miyagipipi** [comment]
@crazywoola 
I know the reason about this error.
First i input a number in this optional variable, then i delete it and run.
In this case, this error happen, and the variable becomes empty string.
