### ISSUE TITLE
 LLM video understanding

### ISSUE THREAD

**Issue by Dongnc1017** [langgenius/dify#10720]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Version 0.11.1 adds support for LLM video understanding. According to #9828, qwen mode requires users to submit a work order application and only supports urlsend mode. Please tell me how to do this and where to submit a work order?
In addition, what model is used to test qwen that supports video understanding?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by hjlarry** [comment]
the doc is [here](https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-vl-plus-api#63edd303a48qy)

**Comment by hjlarry** [comment]
> What if the qwen-vl model is deployed locally by xinferent?

Not supported yet. Seems xinferent use openAI's API, and openAI not support video yet

**Comment by co3k** [comment]
@guchenhe @crazywoola @GarfieldDai ?
I have a patch to handle video files on the LLM node and process them as multi-modal inputs on the Gemini model. I'd like to submit this patch as a pull request linked to this issue. Could you please let me know if it's okay to open the pull request in this way?
Additionally, I am planning to create a similar patch for Gemini model of the VertexAI. Would it be alright to submit that as a pull request in the same manner?

**Comment by hjlarry** [comment]
@co3k seems this PR https://github.com/langgenius/dify/pull/10679 will process files in the LLM node

**Comment by co3k** [comment]
@hjlarry Thank you for pointing out the pull request. After reviewing it, I found that the implementation for handling video files in the LLM node is more appropriate than my own. I'm looking forward to seeing that pull request merged.
However, regarding the support for Gemini and VertexAI, I believe the patch I have on hand could still be useful. I'd like to discuss this further through a pull request.

**Comment by co3k** [comment]
Oh, I just noticed that the PR has already been approved. In that case, I will submit a separate pull request for the Gemini and VertexAI support.

**Comment by hjlarry** [comment]
> Oh, I just noticed that the PR has already been approved. In that case, I will submit a separate pull request for the Gemini and VertexAI support.

yes, I also notice that Gemini support video in their doc,  but when I tried in an agent app it not work for me. Looking forward your PR.

**Comment by Dongnc1017** [comment]
There are currently solutions to understand videos through locally running models

**Comment by pvoo** [comment]
Looking forward to this option for Gemini as well, seems to not pass the file if its a video currently (mp4),  sends an empty file array to the LLM endpoint.  for images or other docs seems to work fine currently.

**Comment by pvoo** [comment]
@hjlarry  thanks a lot for this contribution
