### ISSUE TITLE
The search function in the studio interface cannot input Chinese.

### ISSUE THREAD

**Issue by Moiyu1998** [langgenius/dify#10734]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The search function in the search function in the studio interface cannot input Chinese, and when attempting to input Chinese, it automatically exits the input.tudio interface cannot input Chinese.

**Comment by crazywoola** [comment]
There are some typos in your description, can you provide some screenshots?

**Comment by Moiyu1998** [comment]
> There are some typos in your description, can you provide some screenshots?

I can't take a screenshot because there's no error message, and I can't input anything.
