### ISSUE TITLE
Answer node did not work as expected

### ISSUE THREAD

**Issue by oDoubleyz** [langgenius/dify#10748]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/8137b37d-dab0-4ea8-a984-b6051d2aec01)
LLM node is running, but the responding node has already output the defined text

### ✔️ Expected Behavior

Wait until the code execution node completes before outputting

**Comment by crazywoola** [comment]
- Check the details in workflow steps
- Please provide a DSL

**Comment by crazywoola** [comment]
<img width="404" alt="image" src="https://github.com/user-attachments/assets/59b4a7a3-0ce1-4597-ac37-8f29b3f8072b">
Can not reproduce this on latest version.

**Comment by Ayushaff** [comment]
Also sometimes nodes do not connect to any block after first time creation of agents they works as expected but after changing the exisiting block to some other it shows unexpected behaviour
