### ISSUE TITLE
Failed to execute code

### ISSUE THREAD

**Issue by ddbbcc** [langgenius/dify#10749]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Failed to execute code

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. 在启用业务服务之前，我们需要先部署 PostgreSQL / Redis / Weaviate（如果本地没有的话），可以通过以下命令启动：
cd docker
cp middleware.env.example middleware.env
docker compose -f docker-compose.middleware.yaml up -d
![image](https://github.com/user-attachments/assets/197ae80f-5700-46f4-a6c8-96d4cd70c9ec)
2.服务端部署  启动 API 服务
flask run --host 0.0.0.0 --port=5001 --debug
3.启动 Worker 服务
celery -A app.celery worker -P gevent -c 1 -Q dataset,generation,mail,ops_trace --loglevel INFO
4.前端页面部署  启动 web 服务
npm run start
执行
![image](https://github.com/user-attachments/assets/87d95c3e-dd48-4aac-9326-1b06df36e98d)
![image](https://github.com/user-attachments/assets/95d826cc-3360-4055-8c38-47803797ff2d)
Failed to execute code, which is likely a network issue, please check if the sandbox service is running. ( Error: Failed to execute code, got status code 403, please check if the sandbox service is running )

### ✔️ Expected Behavior

能够顺利执行code  脚本

### ❌ Actual Behavior

没有执行code

**Comment by chinamerp** [comment]
I encountered the same problem, but I don't know how to solve it.

**Comment by leoncool23** [comment]
> I encountered the same problem, but I don't know how to solve it. The error message is “Failed to execute code, which is likely a network issue, please check if the sandbox service is running. ( Error: timed out )”

I encountered the same problem， how to solve it？？？

**Comment by MrKenknight** [comment]
When you run the service using docker/docker-compose.yaml, carefully check the port configuration and docker/.env file
For example:
I commented out the "SANDBOX_PORT" line in the .env file and it worked
