### ISSUE TITLE
LLM识别不了文档提取器输出的数据

### ISSUE THREAD

**Issue by Vampxgg** [langgenius/dify#10740]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![2fbc8734-b19e-436d-95ab-12d91889126d](https://github.com/user-attachments/assets/cdce886a-4ac0-4f2e-866f-564f3f57234b)

### ✔️ Expected Behavior

文档提取器将PPT的内容提取出来之后流入llm中进行数据处理。

### ❌ Actual Behavior

报了个不知道什么的错误。

**Comment by crazywoola** [comment]
I confirm that I am using English to submit this report (我已阅读并同意 https://github.com/langgenius/dify/issues/1542).
[FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
