### ISSUE TITLE
ChatFlow answer repeating until manually clicking the 'stop responding' button

### ISSUE THREAD

**Issue by jenkin2120** [langgenius/dify#10747]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I talking to chatflow in a conversation，the chator seems crash occasionally, it's answer will repeat output until manually clicking the 'stop responding' button.
 

### ✔️ Expected Behavior

Ask and answer interchangeably.

### ❌ Actual Behavior

![error](https://github.com/user-attachments/assets/8c89b6a7-b9f1-4ed5-8873-ab1b91409397)

**Comment by crazywoola** [comment]
FYI
- Check the model settings, especially the repeat penalty
- Please provide A minimal DSL to reproduce this problem
- Upgrade to latest verssion.

**Comment by jenkin2120** [comment]
@crazywoola,
Thanks!
- Check the model settings, especially the repeat penalty
The repeat penalty parameter is not enabled.
- Please provide A minimal DSL to reproduce this problem
My chatflow is a bit complicated.
Because the problem only occasionally arises, I think it may not be related to the configuration of workflow.

It seems system crashed, and repeats output the last sentence constantly, Just like there is an output requirement for it to do so again and again.
I am certain that such a request has not been made anywhere else.

**Comment by crazywoola** [comment]
We will not output duplicated message if the system is crashed, maybe it's the problem of the LLM side.
