### ISSUE TITLE
file type f.type is not supported while uploading the pdf to gemini 1.5 pro

### ISSUE THREAD

**Issue by akashengine** [langgenius/dify#10757]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1507" alt="Screenshot 2024-11-15 at 6 50 20 PM" src="https://github.com/user-attachments/assets/13cf167c-ce00-45e8-8c17-47b854a98f28">

### ✔️ Expected Behavior

PDF's are not processing to gemini model directly 

### ❌ Actual Behavior

<img width="1509" alt="Screenshot 2024-11-15 at 6 50 13 PM" src="https://github.com/user-attachments/assets/9a27fc63-ec7a-4338-bb5b-2e7cecb6b866">

**Comment by crazywoola** [comment]
See https://docs.dify.ai/guides/workflow/node/doc-extractor

> LLMs cannot directly read or interpret document contents. Therefore, it's necessary to parse and read information from user-uploaded documents through a document extractor node, convert it to text, and then pass the content to the LLM to process the file contents.
