### ISSUE TITLE
optimize log page, make log search easier

### ISSUE THREAD

**Issue by Gaocarri** [langgenius/dify#10753]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Because i have too many logs, i need jump page and search by time range, and if page > 1000, not displayed well.

![image](https://github.com/user-attachments/assets/5ea4bca7-7cb9-4189-8fc4-b1646c367d6f)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We have a related pr before, but it will cause the slow db query, so we didn't merge it. If you are interested in implement this feature, please be aware of this problem. :)

**Comment by Gaocarri** [comment]
> We have a related pr before, but it will cause the slow db query, so we didn't merge it. If you are interested in implement this feature, please be aware of this problem. :)

I'd love to try it if I had time  :), i may add some front-end elements. Does dify have UI specifications that need to be followed?

**Comment by Gaocarri** [comment]
> @Gaocarri #11170 What about this one?

nice
