### ISSUE TITLE
invalid_param：Invalid file url 

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#10764]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Hello, may I ask? I created a workflow in chatflow and initially defined a session variable (documentFiles) of type file list. When I called it through the API interface, an error was reported stating {"code": "invalid_maram", "message": "Invalid file URL", "status": 400}. I don't know where the problem is, could you please take a look.
![image](https://github.com/user-attachments/assets/bfee22c5-16a3-4c69-9d0f-6cf33b111122)
params:
```
{
  "inputs":{
    "documentFiles":[
      {
        "transfer_method":"remote_url",
        "remote_url":"https://pre-resource.kang-boss.com/file/pdf/hvIK6EndcFh50e8f8b9527ff1e2673de954b8c947f92.pdf",
        "extension":".pdf",
        "filename":"hvIK6EndcFh50e8f8b9527ff1e2673de954b8c947f92.pdf",
        "size":43927,
        "mime_type":"application/pdf",
        "type":"document"
      }
    ]
  },
  "query":"解读我上传的文档报告",
  "user":"10086",
  "files":[ ],
  "response_mode":"streaming",
  "conversation_id":""
}
```

response:
```
 Response Body: {"code": "invalid_param", "message": "Invalid file url", "status": 400}
```

thanks;

**Comment by guxiyang** [comment]
> I couldn't find specific validation rules for file URLs in Dify's API, but the "invalid_param" error generally indicates abnormal parameter input [[1]](https://github.com/langgenius/dify/blob/main/web/app/components/develop/template/template_advanced_chat.en.mdx).
> 
> Here are a few things you might want to check or try:
> 
> 1. **URL Accessibility**: Ensure that the URL you are using is publicly accessible and not behind any authentication or firewall that could block access.
> 2. **Correct URL Format**: Double-check that the URL is correctly formatted and points directly to the file.
> 3. **Supported File Types**: Make sure the file type is supported by Dify. For documents, supported types include TXT, MARKDOWN, PDF, HTML, XLSX, XLS, DOCX, CSV, and others [[2]](https://github.com/langgenius/dify-docs/blob/main/en/guides/workflow/file-upload.md).
> 4. **Environment Variables**: Verify that your environment variables are correctly set, especially if you are using any specific configurations for file handling [[3]](https://github.com/langgenius/dify-docs/blob/main/jp/getting-started/install-self-hosted/environments.md).
> 
> If these steps don't resolve the issue, consider checking for any recent changes or updates in Dify version 0.11.1 that might affect file uploads [[4]](https://github.com/langgenius/dify-docs/blob/main/en/guides/workflow/bulletin.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._






Still not working, could you please check if the request parameters are correct,
Request to participate:
{
"inputs":{
"documentFiles":[
{
"transfer_method":"remote_url",
"remote_url":" https://pre-resource.kang-boss.com/file/pdf/hvIK6EndcFh50e8f8b9527ff1e2673de954b8c947f92.pdf ",
"extension":".pdf",
"filename":"hvIK6EndcFh50e8f8b9527ff1e2673de954b8c947f92.pdf",
"size":43927,
"mime_type":"application/pdf",
"type":"document"
}
]
},
Query ":" Interpret the document report I uploaded ",
"user":"10086",
"files":[ ],
"response_mode":"streaming",
"conversation_id":""
}

**Comment by fujita-h** [comment]
Try changing the parameters as follows:
```json
"documentFiles": [
    {
        "type": "document",
        "transfer_method": "remote_url",
        "url": "https://pre-resource.kang-boss.com/file/pdf/hvIK6EndcFh50e8f8b9527ff1e2673de954b8c947f92.pdf"
    }
]
  ```

**Comment by guxiyang** [comment]
Thank you, the problem has been resolved. Indeed, the request URL parameter is incorrect. Just replace it with the correct URL. 
"documentFiles": [ 
{ 
"type": "document", 
"transfer_method": "remote_url", 
"url": " https://pre-resource.kang-boss.com/file/pdf/hvIK6EndcFh50e8f8b9527ff1e2673de954b8c947f92.pdf " 
} 
]


***@***.***
 
发件人： Hiroshi Fujita
发送时间： 2024-11-17 16:04
收件人： langgenius/dify
抄送： 顾夕旸; Author
主题： Re: [langgenius/dify] invalid_param：Invalid file url (Issue #10764)
Try changing the parameters as follows:
"documentFiles": [
    {
        "type": "document",
        "transfer_method": "remote_url",
        "url": "https://pre-resource.kang-boss.com/file/pdf/hvIK6EndcFh50e8f8b9527ff1e2673de954b8c947f92.pdf"
    }
]

**Comment by fernvenue** [comment]
Hi, I have the same issue, and I wanna know what if I upload the files from local instead of using remote files?
