### ISSUE TITLE
Vector database connection error

### ISSUE THREAD

**Issue by lem1272536013** [langgenius/dify#10775]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The DIFY frontend displays "Vector database connection error", and after checking the server docker, it is found that the Weaviate container has been restarting, and the following error is reported in the pull log:
![1731814995399](https://github.com/user-attachments/assets/2f01296b-2bce-422e-8b94-59053d12fc45)
After a quick lookup, it was found that this error indicated that the memberlist initialization of the cluster had failed, and the main reason was that the private IP address required for the cluster members to communicate could not be obtained or not provided.
I deployed directly via docker compose and don't know why this is happening and how I should fix it.
thanks

### ✔️ Expected Behavior

succeed

### ❌ Actual Behavior

failed

**Comment by Houlson** [comment]
Not sure if you have solved your problem, but I encountered the same error and spent two days to figure out that our team restricted the IP address allocated for Docker. Try checking your internal internet config, the problem occurs on the Python package Loki used by weaviate, it presets a list of IP address and banned others so that two sets of IPs don't match at all.
