### ISSUE TITLE
The Chinese font is not available in the chart tool

### ISSUE THREAD

**Issue by luzhiyong1996** [langgenius/dify#10777]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The api/core/tools/provider/builtin/chart/chart.py an error occurred in the set chinese font that could not be obtained
```
def set_chinese_font():
    font_list = [
        "PingFang SC",
        "SimHei",
        "Microsoft YaHei",
        "STSong",
        "SimSun",
        "Arial Unicode MS",
        "Noto Sans CJK SC",
        "Noto Sans CJK JP",
    ]

    for font in font_list:
        if font in fontManager.ttflist:
            chinese_font = FontProperties(font)
            if chinese_font.get_name() == font:
                return chinese_font

    return FontProperties()
```

### ✔️ Expected Behavior

Should be modified as：

```
def set_chinese_font():
    font_list = [
        "PingFang SC",
        "SimHei",
        "Microsoft YaHei",
        "STSong",
        "SimSun",
        "Arial Unicode MS",
        "Noto Sans CJK SC",
        "Noto Sans CJK JP",
    ]
    for font in font_list:
        if font in [fontInfo.name for fontInfo in fontManager.ttflist]:
            chinese_font = FontProperties(font)
            if chinese_font.get_name() == font:
                return chinese_font

    return FontProperties()
```

**Comment by hjlarry** [comment]
You are right, feel free to submit a PR  :)
