### ISSUE TITLE
I encountered an error when importing PDF on an ARM architecture server

### ISSUE THREAD

**Issue by waithahah** [langgenius/dify#10780]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[FATAL:partition_root.cc(863)] Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14)). 
[2024-11-17 15:24:22 +0800] [1] [ERROR] Worker (pid:498) was sent code 133!
[2024-11-17 15:24:22 +0800] [587] [INFO] Booting worker with pid: 587

**Comment by crazywoola** [comment]
Solution: https://github.com/langgenius/dify/discussions/10580
