### ISSUE TITLE
Azure下Model text-embedding-ada-002 provider credentials is not initialized

### ISSUE THREAD

**Issue by eggb4by** [langgenius/dify#1079]
Dify version: Self Host

1.设置好azure的相关模型
![image](https://github.com/langgenius/dify/assets/6998751/d8b2e58d-17ae-4a9f-af5c-f5fa91dd601e)
里面text-embedding-ada-002我做了两个deployment,分别名字是text-embedding-ada-002和text-embedding
2.embedding模型选择是这个
![image](https://github.com/langgenius/dify/assets/6998751/24fd7296-2aaa-4865-a274-ea861c765aca)
![image](https://github.com/langgenius/dify/assets/6998751/c201b566-dc22-454c-9091-827476fe014e)

## The current behavior
问题1.embedding里的Text-Embedding-Ada-002为啥第一字母是大写
问题2.在命中测试的时候提示
![image](https://github.com/langgenius/dify/assets/6998751/7595b919-e31f-4236-9686-b63115fe2ee5)

**Comment by JohnJyong** [comment]
May I ask if your steps were carried out as follows: 
1. Create an azure text-embedding-ada-002 embedding model 
2. Create a dataset 
3. Conduct a hit test

**Comment by eggb4by** [comment]
> May I ask if your steps were carried out as follows:
> 
> 1. Create an azure text-embedding-ada-002 embedding model
> 2. Create a dataset
> 3. Conduct a hit test

I run the environment by docker and kept updating from 0.3.x to 0.3.18 now. Azure-openai is the only model used from the beginning.
Dataset is already created long time ago.
At first, I got this error in my environment so I delete all the azure setting and recreate four model, 2 for embedding(text-embedding-ada-002 and text-embedding pointed to azure embedding model with the same name) and gpt-35-turbo&gpt-4 for completion. But I still got the same error in hit test.
That's all.Thanks

**Comment by eggb4by** [comment]
Ok, I figured out what's wrong
I check the data in database
in "datasets" table
![image](https://github.com/langgenius/dify/assets/6998751/b76bc45b-cb4a-4fda-898d-e30baeb7db31)
the "embedding_model_provider" is "openai" because when I created this dataset, I used Openai as provider and later I changed to Azure, but when I change the setting in "settings", the data in these two columns never changed, so system use openai's text-embedding-ada-002 and get error.
So, I think the final bug is 
Change the model selections in "Settings" never changed the model selection in datasets.

**Comment by eggb4by** [comment]
The red box was manually modified by myself and then it works

**Comment by eggb4by** [comment]
ok, I saw the hints.Thanks!
closed!

**Comment by JohnJyong** [comment]
I understand, this is a bug in our previous version, it has now been fixed online,
for ce version, you may need to do a fix yourself，pls update the database at datasets table
