### ISSUE TITLE
Small text should not be recalled when segmenting the knowledge base

### ISSUE THREAD

**Issue by dadastory** [langgenius/dify#10800]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When knowledge is segmented, many small paragraphs or repeated texts will be generated, which will lead to poor recall quality of the knowledge base.
<img width="1211" alt="bc502e6819bc5ca09cc96899812f0cd" src="https://github.com/user-attachments/assets/4bc56ef7-b601-4732-a188-1acb70fc3703">

### ✔️ Expected Behavior

When customizing segmentation, you should not generate so many repeated paragraphs, such as titles, small questions and other blocks.

### ❌ Actual Behavior

No small repetitive paragraph blocks are generated

**Comment by crazywoola** [comment]
We have custom separator settings, you need to adjust those to fit your needs, or you can preprocess those texts on your own. We offer a way to sync knowledge by maintaining a third party api. https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation

**Comment by dadastory** [comment]
> We have custom separator settings, you need to adjust those to fit your needs, or you can preprocess those texts on your own. We offer a way to sync knowledge by maintaining a third party api. https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation

@crazywoola This problem is caused by custom delimiters, which will produce many small fragmented paragraphs. I am not referring to the problem of automatic segmentation.

**Comment by crazywoola** [comment]
Yes, but it depends on the format of the raw document. Maybe you can use some other delimiters.
