### ISSUE TITLE
It is recommended to add an input node to interrupt the process while the process is executing and prompt the user for input (text or upload a file) before continuing the process

### ISSUE THREAD

**Issue by fsea** [langgenius/dify#10809]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It is recommended to add an input node to interrupt the process anywhere in the process, prompt the user to enter text or upload a file, and then bring the input information into context to continue the process.

### 2. Additional context or comments

Facilitate the production of a step-by-step process

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We have already support form inputs while chatting around. We are still evaluating the file upload in our produce side.

**Comment by fsea** [comment]
![image](https://github.com/user-attachments/assets/2e32f173-e7f8-41be-89d0-a8cecec6fbf6)
Roughly this means that during a process, the user can be asked to enter a specified field, and an inputor can be added anywhere in the process. During process execution, user input can be required to continue. It's not like entering all the values as soon as you enter the chat, because different processes require different information.
