### ISSUE TITLE
The code execution function is too rubbish, please upgrade it

### ISSUE THREAD

**Issue by Vampxgg** [langgenius/dify#10816]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/user-attachments/assets/f023e8ee-b434-4e5e-ba8d-0795dc8e4ce3)
When I am extracting data, I want to extract the links in a list of input URLS links and send them to the subsequent http for access. However, the code execution node requires me to define the output variables. My output should be dynamic, so why does it require it to be defined in advance?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please watch your language, and choose your words wisely.  :)
