### ISSUE TITLE
When I use the Conditional Branch IF/ELSE node, the LLM node connected afterward cannot output in a streaming way.

### ISSUE THREAD

**Issue by ZHUxjj** [langgenius/dify#10812]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/d22289e1-9074-4b6f-8995-4f002f375449)
When I remove the Conditional Branch IF/ELSE node, everything works fine; otherwise, the LLM node cannot output in a streaming way.

### ✔️ Expected Behavior

 I expect the LLM node connected afterward to output in a streaming way

**Comment by crazywoola** [comment]
This should be fixed in v0.11.x series
