### ISSUE TITLE
Documentation Request: Missing Documentation for "Segmenting in Question & Answer Format"

### ISSUE THREAD

**Issue by mamprogr** [langgenius/dify#10813]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I noticed that there is no available documentation for the "Segmenting in Question & Answer format" feature in [create-knowledge-and-upload-documents](https://docs.dify.ai/guides/knowledge-base/create-knowledge-and-upload-documents#id-3-indexing-mode)

**Comment by AllenWriter** [comment]
Hi, you can check this part of content here: https://docs.dify.ai/guides/knowledge-base/create-knowledge-and-upload-documents#id-4-retrieval-settings.

<img width="690" alt="image" src="https://github.com/user-attachments/assets/8005ebff-9d25-43e4-b89e-f27d000d96de">
