### ISSUE TITLE
Uploading knowledge base prompt in queue

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#10834]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello, when I manually created a knowledge base and uploaded some files, I kept getting the message 'in queue' and I don't know what the problem is.

![image](https://github.com/user-attachments/assets/86a04f62-126f-49d2-a5c6-646f3df8e185)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See closed issue.
