### ISSUE TITLE
Please check if your app mode matches the right API route

### ISSUE THREAD

**Issue by guailigirl** [langgenius/dify#10830]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I use the embedded website feature, an error message appears:“Please check if your app mode matches the right API route”
This issue seems to only apply to text generation applications.

### ✔️ Expected Behavior

How to solve the problem of 'Please check if your app mode matches the right API route'

### ❌ Actual Behavior

Please check if your app mode matches the right API route

**Comment by crazywoola** [comment]
I don't think we support embedding text-generation application.

**Comment by opensussex** [comment]
I have this same issue, I'm using the embed code that was generated for the app - is that an issue with the generated code? 

the code is - so not a completion... 

`<iframe
 src="https://udify.app/chatbot/*******"
 style="width: 100%; height: 100%; min-height: 700px"
 frameborder="0"
 allow="microphone">
</iframe>`

**Comment by opensussex** [comment]
OK I see the issue I faced - the generated embed code had `chatbot` but my app was `completion` so changing that in the URL worked for me.

**Comment by Shijian02** [comment]
@opensussex How did you solve the problem?
