### ISSUE TITLE
Empty retriever_resources Node in API Response

### ISSUE THREAD

**Issue by yjc980121** [langgenius/dify#10861]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Endpoint: /v1/messages

Description:
When making a GET request to the /v1/messages endpoint with the following parameters:

user=abc-123

conversation_id=

and including the Authorization: Bearer {api_key} header, the response contains an empty retriever_resources node. This behavior is inconsistent with the documentation, which provides an example response that includes a non-empty retriever_resources node.

Expected Behavior:
The retriever_resources node in the response should contain the expected data, allowing the caller to display the source of the referenced information when viewing the conversation history.

Actual Behavior:
The retriever_resources node in the response is empty, which prevents the caller from displaying the source of the referenced information in the conversation history.

Steps to Reproduce:

Make a GET request to /v1/messages with the query parameters user=abc-123 and conversation_id=.

Include the Authorization: Bearer {api_key} header.

Observe the response, specifically the retriever_resources node.

Impact:
This issue prevents the caller from displaying the source of the referenced information in the conversation history, which is a critical feature for the application.

Request:
Please investigate why the retriever_resources node is empty and update the API to return the expected data as described in the documentation.

### ✔️ Expected Behavior
```
{
  "limit": 20,
  "has_more": false,
  "data": [
    {
      "id": "a076a87f-31e5-48dc-b452-0061adbbc922",
      "conversation_id": "cd78daf6-f9e4-4463-9ff2-54257230a0ce",
      "inputs": {
        "name": "dify"
      },
      "query": "iphone 13 pro",
      "answer": "The iPhone 13 Pro, released on September 24, 2021, features a 6.1-inch display with a resolution of 1170 x 2532. It is equipped with a Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard) processor, 6 GB of RAM, and offers storage options of 128 GB, 256 GB, 512 GB, and 1 TB. The camera is 12 MP, the battery capacity is 3095 mAh, and it runs on iOS 15.",
      "message_files": [],
      "feedback": null,
      "retriever_resources": [
        {
          "position": 1,
          "dataset_id": "101b4c97-fc2e-463c-90b1-5261a4cdcafb",
          "dataset_name": "iPhone",
          "document_id": "8dd1ad74-0b5f-4175-b735-7d98bbbb4e00",
          "document_name": "iPhone List",
          "segment_id": "ed599c7f-2766-4294-9d1d-e5235a61270a",
          "score": 0.98457545,
          "content": "\"Model\",\"Release Date\",\"Display Size\",\"Resolution\",\"Processor\",\"RAM\",\"Storage\",\"Camera\",\"Battery\",\"Operating System\"\n\"iPhone 13 Pro Max\",\"September 24, 2021\",\"6.7 inch\",\"1284 x 2778\",\"Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)\",\"6 GB\",\"128, 256, 512 GB, 1TB\",\"12 MP\",\"4352 mAh\",\"iOS 15\""
        }
      ],
      "created_at": 1705569239
    }
  ]
}
```
### ❌ Actual Behavior
```
{
  "limit": 20,
  "has_more": false,
  "data": [
    {
      "id": "a076a87f-31e5-48dc-b452-0061adbbc922",
      "conversation_id": "cd78daf6-f9e4-4463-9ff2-54257230a0ce",
      "inputs": {
        "name": "dify"
      },
      "query": "iphone 13 pro",
      "answer": "The iPhone 13 Pro, released on September 24, 2021, features a 6.1-inch display with a resolution of 1170 x 2532. It is equipped with a Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard) processor, 6 GB of RAM, and offers storage options of 128 GB, 256 GB, 512 GB, and 1 TB. The camera is 12 MP, the battery capacity is 3095 mAh, and it runs on iOS 15.",
      "message_files": [],
      "feedback": null,
      "retriever_resources": [],
      "created_at": 1705569239
    }
  ]
}
```

**Comment by crazywoola** [comment]
Please check if this retriever_resource switch is enabled.

**Comment by yjc980121** [comment]
the features "Citations and Attributions"  switch is enabled
Endpoint: post /v1/chat-message  is Ok

![1732065383296](https://github.com/user-attachments/assets/7f30ba84-927c-48b2-9db5-f4fc23c996fc)
Endpoint: get /v1/messages   the retriever_resource  is None
![1732065582355](https://github.com/user-attachments/assets/bf2a8768-3452-4246-a2ff-b42dbd23e682)



> Please check if this retriever_resource switch is enabled.

**Comment by yjc980121** [comment]
/v1/chat-messages endpoint
![image](https://github.com/user-attachments/assets/8b1fa07d-4e52-442e-9ab8-f7b1810381c1)

**Comment by JohnJyong** [comment]
![image](https://github.com/user-attachments/assets/2b80d315-5b28-49aa-b64c-06650275ff9a)
![image](https://github.com/user-attachments/assets/39438c3b-a6b0-4f53-b91f-8c2a4c2fb625)
pls mark sure the message have related retrieval resource, if you have any problem, you can reopen this issue, thanks @yjc980121

**Comment by yjc980121** [comment]
> ![图像](https://private-user-images.githubusercontent.com/76649700/387959503-2b80d315-5b28-49aa-b64c-06650275ff9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODgxNzAsIm5iZiI6MTczMjE4Nzg3MCwicGF0aCI6Ii83NjY0OTcwMC8zODc5NTk1MDMtMmI4MGQzMTUtNWIyOC00OWFhLWI2NGMtMDY2NTAyNzVmZjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDExMTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YTJjNDc4NmIzZTE0ODk4Y2VmOTEzZWE0MDdlYmVmOTVmN2NlZTNjY2U3ZmFiYWEyYTVhM2NkMWNhM2YzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K56_fDkVakAeJL3g2iR35DBr-lMGTzaP0D9C2iUWVME) ![图像](https://private-user-images.githubusercontent.com/76649700/387959756-39438c3b-a6b0-4f53-b91f-8c2a4c2fb625.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODgxNzAsIm5iZiI6MTczMjE4Nzg3MCwicGF0aCI6Ii83NjY0OTcwMC8zODc5NTk3NTYtMzk0MzhjM2ItYTZiMC00ZjUzLWI5MWYtOGMyYTRjMmZiNjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDExMTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MmY1NjcwN2VjODdiYTQxYzNlZTdmNWQ4MWI4NzBmMTRjYzljOGYwNzg3MDRjYTZjZDFhNTI4MDQzYTk0MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hCav-Am9RG2BxR0aOi31VjMVJZ4BAJmSTkyPV1HwCug) 请确保该消息有相关的检索资源，如果有任何问题，你可以重新打开这个issue，谢谢@yjc980121

"I deployed the community version using Docker, not a cloud service."
