### ISSUE TITLE
Invalid base64-encoded string: number of data characters (1565) cannot be 1 more than a multiple of 4

### ISSUE THREAD

**Issue by dadastory** [langgenius/dify#10860]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I add a model key, I always get the error Invalid base64-encoded string: number of data characters (1565) cannot be 1 more than a multiple of 4, and cannot load any model.

![image](https://github.com/user-attachments/assets/f501323b-33b8-4dcf-b7a3-2fac03de6bc1)

### ✔️ Expected Behavior

Add normally without error

### ❌ Actual Behavior

get the error Invalid base64-encoded string: number of data characters (1565) cannot be 1 more than a multiple of 4
Not sure what the problem is

**Comment by crazywoola** [comment]
Please provide the container logs and payload as well.

**Comment by dadastory** [comment]
> Please provide the container logs and payload as well.
It's just a Get request, there's no payload, and the logs don't show any errors
![image](https://github.com/user-attachments/assets/9abe13cc-748f-476b-aa63-4da946a68ced)
![image](https://github.com/user-attachments/assets/7871be66-71f6-4114-9246-bad5390f2cdf)

**Comment by dadastory** [comment]
i finally run this command and fix it
```python
flask reset-encrypt-key-pair
```
i have no idea what happen, and i have to set api-key again
