### ISSUE TITLE
GraphQL responses are treated as file

### ISSUE THREAD

**Issue by DavideDelbiancoZucchetti** [langgenius/dify#10870]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Create an HTTP node that executes a POST request to a graphQL endpoint

### ✔️ Expected Behavior

The response should be in the body property and not in file

### ❌ Actual Behavior

Because of a change in PR #8818 a variable name NON_FILE_CONTENT_TYPES was introduced in api/core/workflow/nodes/http_request/entities.py and breaks graphql responses that have content type: "application/graphql-response+json; charset=utf-8"

**Comment by laipz8200** [comment]
Link to #10862
