### ISSUE TITLE
upload file show value can not be empty

### ISSUE THREAD

**Issue by xiaogu-space** [langgenius/dify#10882]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In the "Explore" I have set the img1 file,but show the error "img1 value can not be empty".When I use in the "Studio" is ok, don't show the error.
![image](https://github.com/user-attachments/assets/460f7cde-51b7-4d9e-bb5e-c1bbcca2596c)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Which version are you referring?
