### ISSUE TITLE
Cannot add a Hugging Face Model in the Model Provider settings in Dify.

### ISSUE THREAD

**Issue by doboncho** [langgenius/dify#10885]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 "server_version": "0.11.0"

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I try to add the Hugging Face Model in the Model Provider settings in Dify, I get an error like Model sentence-transformers/multi-qa-mpnet-base-dot-v1 is not a valid task, must be one of feature-extraction.

### ✔️ Expected Behavior

Hugging Face Model can be added in the Model Provider Settings. The model is saved without error.

### ❌ Actual Behavior

Cannot save with the error “Model sentence-transformers/multi-qa-mpnet-base-dot-v1 is not a valid task, must be one of feature-extraction.

**Comment by crazywoola** [comment]
Only supported task types can be added.
- text-generation
- text2text-generation
- feature-extraction
- embeddings.

**Comment by doboncho** [comment]
How do I select the “feature-extraction” task type in the Dify configuration?
