### ISSUE TITLE
数据集使用高质量索引在命中测试时提示未初始化

### ISSUE THREAD

**Issue by charli117** [langgenius/dify#109]
当前使用了Azure OpenAI的接口，在做数据索引命中测试时，提示未初始化，是不是这部分的兼容适配漏掉了啊
![image](https://github.com/langgenius/dify/assets/24435100/a66bf3d8-a013-4f2b-8264-13c28538d945)

**Comment by takatost** [comment]
这个应该是数据集文档还在导入过程中的提示

**Comment by charli117** [comment]
是从经济索引调整成了高质量，做命中测试就会报错。然后用高质量直接导入woker上也会有如下报错
![image](https://github.com/langgenius/dify/assets/24435100/ffffa09e-a0c2-49fa-8521-3a750a91dd0b)

**Comment by takatost** [comment]
@JohnJyong 这边切换的问题看下

**Comment by JohnJyong** [comment]
@charli117 不好意思，这由于数据集切换索引模式，索引未做模式适配引起的，我们会尽快修复。

**Comment by charli117** [comment]
好呢，太感谢了

**Comment by JohnJyong** [comment]
https://github.com/langgenius/dify/pull/177
这个问题已经在这个pr中修复了~

**Comment by JohnJyong** [comment]
这个报错感觉有点像 weaviate 配置有问题，麻烦发一下你的env 并检查一下本地的weaviate 是否启动有问题

**Comment by charli117** [comment]
weaviate配置沿用的缺省，没有调整过
<img width="1678" alt="image" src="https://github.com/langgenius/dify/assets/24435100/a4b5eb4e-f6bd-4020-ab8b-5aae35c87525">

**Comment by JohnJyong** [comment]
> weaviate配置沿用的缺省，没有调整过 <img alt="image" width="1678" src="https://user-images.githubusercontent.com/24435100/240476379-a4b5eb4e-f6bd-4020-ab8b-5aae35c87525.png">

你的env中的 weaviate 的 endpoint 应该配置为 `WEAVIATE_ENDPOINT: http://weaviate:8080` ，请再试试 @charli117

**Comment by charli117** [comment]
开发环境我有把端口发布出来，在host上访问http://localhost:8080是可以正常访问的，另外做命中测试发现报错跟之前不一样了。对了我用的大模型是Azure OpenAI，这个有没有影响呀

<img width="1000" alt="image" src="https://github.com/langgenius/dify/assets/24435100/12e62973-c30e-4ee0-969b-1c7cc3a29fdb">

<img width="1728" alt="image" src="https://github.com/langgenius/dify/assets/24435100/1d6c5275-3146-4348-b8b4-5bfc6152a866">

**Comment by charli117** [comment]
等了很长时间都不行，应该还是高精度索引有问题

**Comment by charli117** [comment]
容器中的报错也不一样了
![image](https://github.com/langgenius/dify/assets/24435100/361d8fbc-38d3-435d-b88a-3f9e48a10c30)

**Comment by JohnJyong** [comment]
AzureOpenAI 的配置看下：
![image](https://github.com/langgenius/dify/assets/76649700/0c9b2634-7b62-4d5a-a2eb-e9c96051a122)
https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq

**Comment by charli117** [comment]
嗯，是否和要求的，用的gpt-35-turbo名称，对话都正常

**Comment by charli117** [comment]
@JohnJyong 定位到问题了，同事给我的key没有加上模型 text-embedding-ada-002，被坑惨了

**Comment by 0utman1** [comment]
> AzureOpenAI 的配置看下： ![image](https://user-images.githubusercontent.com/76649700/240499963-0c9b2634-7b62-4d5a-a2eb-e9c96051a122.png) https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq

部署的模型名称必须跟图中一致吗？不一致的话能mapping么？

**Comment by takatost** [comment]
mapping 暂时还没有哈，之后接提供配置界面
