### ISSUE TITLE
CANNOT set the openai api key and url using api from third-party provider

### ISSUE THREAD

**Issue by WSDzju** [langgenius/dify#10902]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

when setting the openai api key and url using api from third-party provider on the openai model setting page, a long error code comes up.
![image](https://github.com/user-attachments/assets/4d586587-aa68-46e4-a45b-4abeec8c3a41)

**Comment by crazywoola** [comment]
The openai provider is meant to use official keys. If you have 3rd party keys, please use openai compatiable provider instead, we will not fix those incompatible issues in this provider.

**Comment by WSDzju** [comment]
> The openai provider is meant to use official keys. If you have 3rd party keys, please use openai compatiable provider instead, we will not fix those incompatible issues in this provider.

previously, it works. just replacing the offical api url can make it work. I thought this is a typical practice when using openai api
