### ISSUE TITLE
Repeat: Knowledge base stays in queuing mode, nothing happens

### ISSUE THREAD

**Issue by polischool** [langgenius/dify#10918]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Upload documents in knowledge, they do not get processed just keep queuing. I've verified rate limits have not been reached, and since Cloud hosted, cannot try suggestions from other bug reports of the same problem. 

### ✔️ Expected Behavior

Files process and become available.

### ❌ Actual Behavior

Files stuck in Queuing.

**Comment by polischool** [comment]
Cloud Hosted. None of the main suggestions apply and rate limit is not the issue. It's cloud-hosted by Dify.ai, so no control over updates or patches and they have no support team other than this.

**Comment by sugoh** [comment]
@polischool Also seeing issues retrieving data from Dify cloud DB in #10916. Might be related.

**Comment by crazywoola** [comment]
We are looking into this. @sugoh @polischool

**Comment by crazywoola** [comment]
This should be resolved. Sorry for the inconvenience.

**Comment by meng-tsai** [comment]
@crazywoola Could you provide some details about how did you resolve this issue? I am having the same issue on local deployment. Thank you.

**Comment by meng-tsai** [comment]
This issue happens only after 0.11.1
