### ISSUE TITLE
Knowledge Retrieval Testing timing out

### ISSUE THREAD

**Issue by sugoh** [langgenius/dify#10916]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.11.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Use "Knowledge Retreival + Chatbot" template
2. Add a document to the knowledge base
3. Crawl a website with this document
4. Clean embeddings
5. Run retrieval testing. Doesn't matter if you select Vector Search, Full-Text Search, or Hybrid Search. Also doesn't matter if query text has matching terms.

### ✔️ Expected Behavior

Output an array of relevant embeddings that were retrieved

### ❌ Actual Behavior

Worked for a while with an array of relevant embeddings. Subsequently started receiving an error toast notification: `timed out; timed out`

No changes to knowledge base.

**Comment by sugoh** [comment]
We've turned rerank model off but have added a cohere rerank model anyway (following the solution suggested by [issue 3110](https://github.com/langgenius/dify/issues/3110)). This made no difference.

**Comment by xjose97x** [comment]
I'm experiencing this issue as well.

My bot can't retrieve content from the knowledge base.
I also can't upload new documents to the knowledge base.

Could this be a connection issue with the vector database used by Dify Cloud?

**Comment by highhead** [comment]
Expieriencing the same. What I also find interesting is, that it seems as there has been a rollback done for knowledge base files. It is suddenly an older version...

**Comment by crazywoola** [comment]
This should be resolved. Sorry for the inconvenience.

**Comment by xjose97x** [comment]
> This should be resolved. Sorry for the inconvenience.

could we get some details on what the issue was? thx
