### ISSUE TITLE
Password policy conflict with temporary password format in self-hosted environment

### ISSUE THREAD

**Issue by tubone24** [langgenius/dify#10912]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When trying to reset password in self-hosted environment, I encountered an issue with the password policy validation.

- Deploy Dify in self-hosted environment
- Request a password reset
- Receive temporary password via email
- Try to use the temporary password
- Get rejected by password policy validation

![スクリーンショット 2024-11-20 23 05 29](https://github.com/user-attachments/assets/63143222-6e55-4050-849a-5926effe57b6)
![スクリーンショット 2024-11-20 22 55 49](https://github.com/user-attachments/assets/d96f9b69-ed90-40ce-9a5b-1d6c53269d5e)

### ✔️ Expected Behavior

The temporary password format should comply with the password policy requirements, or the policy should be temporarily bypassed during the password reset process.

### ❌ Actual Behavior

- The temporary password sent via email is a 6-digit numeric code
- The password policy requires both letters and numbers, with a minimum length of 8 characters
- This causes the temporary password to be rejected by the system's password policy

**Comment by tubone24** [comment]
@dosu 

> Bypass the Password Policy Temporarily: Implement a mechanism to bypass the password policy validation specifically for the temporary password during the reset process. This would allow the current format to be used without being rejected.

Good Idea. Please explain how to implement it while specifically pointing out the components that need to be modified.

**Comment by crazywoola** [comment]
This is a one time password for validating this account that belongs to you.

You need to input the code here in this step.

<img width="655" alt="image" src="https://github.com/user-attachments/assets/f5abca66-ccdc-4a98-a439-e210c51a9abb">

After that, you can setup your own password which should follow that password policy.

**Comment by tubone24** [comment]
@crazywoola 

Thank you for your response. While I understand this is a one-time password format, after sending the reset link, I'm unsure which screen I should navigate to in order to enter the code (I'm not clear about the screen you introduced).
As shown in the attachment, the reset link sending screen only has a "Return to Sign in" button, and there is no corresponding link in the email content.
I believe I should be able to proceed if I can access the screen at https://github.com/langgenius/dify/blob/82575a7aea904c0c56f8103fe0ceea39e97cf0f4/web/app/signin/check-code/page.tsx#L72, but I'm having trouble because directly accessing the URL results in a 404 error.

![スクリーンショット 2024-11-21 18 37 48](https://github.com/user-attachments/assets/406d77fd-798c-421e-9668-fa67e7ab9a1e)

![スクリーンショット 2024-11-21 18 44 08](https://github.com/user-attachments/assets/34e602a6-0f66-4f3a-9fb8-cfeaa4781e88)
