### ISSUE TITLE
Http request node error "cannot fetch file with selector ['sys','file']" 

### ISSUE THREAD

**Issue by XiangbingZeng** [langgenius/dify#10924]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1098" alt="屏幕截图 2024-11-21 113323" src="https://github.com/user-attachments/assets/bc647f04-a6c1-4072-91bf-1e4a1e4720d6">
<img width="1103" alt="屏幕截图 2024-11-21 112918" src="https://github.com/user-attachments/assets/81eeb786-c5bc-4ad6-8f83-5d22daab6f5d">

**Comment by crazywoola** [comment]
Please use `form-data` instead. For example. 

<img width="640" alt="image" src="https://github.com/user-attachments/assets/82072069-495d-4376-9ed4-8ff008e5894f">

**Comment by lastlastsummer** [comment]
> 请改用`form-data`。例如。
> 
> <img alt="图像" width="640" src="https://private-user-images.githubusercontent.com/100913391/388367970-82072069-495d-4376-9ed4-8ff008e5894f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2Nzk1OTgsIm5iZiI6MTczMjY3OTI5OCwicGF0aCI6Ii8xMDA5MTMzOTEvMzg4MzY3OTcwLTgyMDcyMDY5LTQ5NWQtNDM3Ni05ZWQ0LThmZjAwOGU1ODk0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMzQ4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDc1OWQxNDJiY2RhMjc1YTliNDE0NmI2ZjY1MWNkNDBkZjJjYTNiZTE5MmRhMDZkYmFkODNiYTE5MDY5NjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Br6vRqUiiAnerjTtjYt3bMDNPDVivS0mpEUEgV-fy0k">

I followed your method and tried it as shown in the figure below：
![set](https://github.com/user-attachments/assets/2b1b4d6b-fec5-4a80-a9cd-7d04345e0c7b)
But the request.form.get('files') object received by my API interface is an empty value：
![result](https://github.com/user-attachments/assets/0e623dc9-f7c1-4a00-8c2c-ad1d38ad1fdd)

**Comment by hxuaj** [comment]
same here, any update?

**Comment by FahadAltaf** [comment]
@XiangbingZeng I am also having the same issue

**Comment by Hel5ing** [comment]
same issue

**Comment by cryptowww** [comment]
if you use sys.files variable, and your http node must receive a binary file param, you can use a iterate node to process the scenario.

**Comment by elviswf** [comment]
- I have successfully used it by the form-data method. 
- The key point is use **a list operation to get `file` from `sys.files`**.


![Image](https://github.com/user-attachments/assets/89466b0b-491f-455e-b56f-1481bf2bd53f)

**Comment by sunxuan0419** [comment]
> * 我已经通过表单数据方法成功使用了它。
> * 关键点是使用**列表操作`file`从中`sys.files`**获取。
> * 选择第一个或迭代。
> 
> ![Image](https://github.com/user-attachments/assets/89466b0b-491f-455e-b56f-1481bf2bd53f)

3Q！
