### ISSUE TITLE
knowledge base :  Cannot release a lock that's no longer owned

### ISSUE THREAD

**Issue by IceNiro** [langgenius/dify#10933]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I'm trying to upload a txt file to build a knowledge base, but it's giving me the error: cannot release a lock that's no longer owned。
but it seems that the document is still worked,the  segment status is available。
and I cannot find any error log message in the work server log file

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/ced38fcc-77b5-4b87-821d-9bd70c176cb6">

### ✔️ Expected Behavior

what is the reason for this error ? 
how can I fix the document status to green ?

**Comment by crazywoola** [comment]
This has been resolved in later versions, please upgrade to latest version.

**Comment by boHam-wang** [comment]
> This has been resolved in later versions, please upgrade to latest version.

I have met the same problem in version 0.12.1
![image](https://github.com/user-attachments/assets/862573be-b255-4679-931c-a85fbc83be9c)
how to solve this problem?
