### ISSUE TITLE
Parameter extractor reported an error

### ISSUE THREAD

**Issue by cuihaojie24** [langgenius/dify#10934]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I refer to the documentation, but the result is different from the documentation, the error message is as follows:
Error: 3 validation errors for AssistantPromptMessage content.str Input should be a valid string [type=string_type, input_value=[{'text': '{"query": "2405.10739"}'}], input_type=list] For further information visit https://errors.pydantic.dev/2.9/v/string_type content.list[PromptMessageContent].0.type Field required [type=missing, input_value={'text': '{"query": "2405.10739"}'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.9/v/missing content.list[PromptMessageContent].0.data Field required [type=missing, input_value={'text': '{"query": "2405.10739"}'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by crazywoola** [comment]
Please open this as a bug report. Also we need to check the version you are using.
