### ISSUE TITLE
Where is the admin page?

### ISSUE THREAD

**Issue by unsiao** [langgenius/dify#10948]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

How do I create a new user? How do I delete a user? Where is the admin page?
Why can't I find anything? Should I just use the default user?
![image](https://github.com/user-attachments/assets/532435a9-4bfd-40cd-bb70-93a12eed98a0)

**Comment by crazywoola** [comment]
Well, if you are using self hosted version, only one workspace can be used. For inviting members, you can go to settings -> members.  If. you want to start building something, the default use is good to go.

Next time, please use discussion to ask for help instead. This is not the right template to fire an issue.
