### ISSUE TITLE
How to change the default HTTP port? | 如何修改 默认HTTP端口？

### ISSUE THREAD

**Issue by unsiao** [langgenius/dify#10941]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I tried modifying the following two options in the `.env` file, but it didn't work:

```.env
# HTTP port
NGINX_PORT=80
# SSL settings are only applied when HTTPS_ENABLED is true
NGINX_SSL_PORT=443
```

**Comment by stvogel** [comment]
This works mostly. 
I changed the port and everything is fine.

But if I open a Workflow and go to "Publish" / "Run App" the url is still without a port (so default-port 80).
