### ISSUE TITLE
User Logs Out Within Access Token Expiration Time, Old Access Token Still Used in Request Header Causes Background Interface to Remain Accessible

### ISSUE THREAD

**Issue by 113223** [langgenius/dify#10962]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When the user exits within the expiration time of access_token, but the old access_token is still used in the request header, the background interface can still access the problem
![image](https://github.com/user-attachments/assets/9d059edc-63b5-496a-be35-3c2259a14c6a)

1. first，login  with account
2. second， get **Authorization** from  WebUI
3. third，on WebUI click logout button
4. use **postman** ，the background interface can still access

### ✔️ Expected Behavior

When the user exits within the expiration time of access_token, but the old access_token is still used in the request header, the background interface can not access

**Comment by laipz8200** [comment]
This is how JWT works: it will expire quickly after you log out. More importantly, make sure to keep your token safe and avoid any leaks.

**Comment by 113223** [comment]
> rks: it will expire quickly after you log ou

in fact ， it will not expire quickly after you log out. when i use  AccountService.logout(account=account) function，clear the refresh_token, but access_token is  not  expire  quickly ,the old access_token is still used in the request header, the background interface can still access.

**Comment by laipz8200** [comment]
This is as expected. Please confirm that you are familiar with the JWT authorization.

If you have stricter security requirements, you can shorten the validity period of the JWT by adjusting the ACCESS_TOKEN_EXPIRE_MINUTES. However, it will still be usable until it expires.

**Comment by 113223** [comment]
> This is as expected. Please confirm that you are familiar with the JWT authorization.
> 
> If you have stricter security requirements, you can shorten the validity period of the JWT by adjusting the ACCESS_TOKEN_EXPIRE_MINUTES. However, it will still be usable until it expires.

get it ,thank you
