### ISSUE TITLE
The official API documentation I read should be like this for uploading files. When I use the file list, I can only upload one file. When I use a single file, it reports the following error. Can't the API be written better?

### ISSUE THREAD

**Issue by Vampxgg** [langgenius/dify#10974]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![232f151e-655b-4d4e-bd89-4e40055526c0](https://github.com/user-attachments/assets/349ed977-d536-4188-b6b3-f28646d5ed1d)

### ✔️ Expected Behavior

1

### ❌ Actual Behavior

1

**Comment by crazywoola** [comment]
You can not even choose a right template.

**Comment by Vampxgg** [comment]
![9cd3561c-7f1c-45d4-a7af-a4f79636ea7c](https://github.com/user-attachments/assets/05c41f93-2ad3-4cbb-8846-02804e6f1f1c)
I specified the file list format, but why does it always show that only one file has been uploaded when I test it with apifox? ?
