### ISSUE TITLE
Error about deploying locally a model plugged into the Hosted Inference API on huggingface

### ISSUE THREAD

**Issue by zhizhuaa** [langgenius/dify#10984]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The following error occurred when I followed https://docs.dify.ai/zh-hans/development/models-integration/hugging-face to access the model from the community edition web page deployed via Docker Compose

![image](https://github.com/user-attachments/assets/a32e50cc-eee9-4164-851c-308257700d8c)

Looking forward to your reply.

### ✔️ Expected Behavior

successfully access the model.

### ❌ Actual Behavior

The following error occurred when I followed https://docs.dify.ai/zh-hans/development/models-integration/hugging-face to access the model from the community edition web page deployed via Docker Compose

![image](https://github.com/user-attachments/assets/a32e50cc-eee9-4164-851c-308257700d8c)

Looking forward to your reply.

**Comment by crazywoola** [comment]
Please make sure you can access huggingface endpoint correctly.
