### ISSUE TITLE
即使是只包含三个节点，将用户问题原样返回的工作流，在并发测试60个请求时，初始响应时间达到了4秒，完全响应时间达到8秒

### ISSUE THREAD

**Issue by yg2024** [langgenius/dify#10982]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

即使是只包含三个节点，将用户问题原样返回的工作流，在并发测试60个请求时，初始响应时间达到了4秒，完全响应时间达到8秒

如果只测试一个请求就很快，在一秒左右，但只要同时请求数量一多，即使配置的工作流再简单，也会变慢很多

dify有进行过压测吗？？？

Even with only three nodes, the workflow that returns user questions as they are achieved an initial response time of 4 seconds and a full response time of 8 seconds when testing 60 concurrent requests

If only one request is tested, it will be fast, in about a second, but as long as there are a large number of requests at the same time, even if the configured workflow is simple, it will be much slower

**Comment by crazywoola** [comment]
Well we do have business plan, if you are interested in it. Please feel free to contact our business@dify.ai.

**Comment by yg2024** [comment]
SERVER_WORKER_AMOUNT和CELERY_WORKER_AMOUNT  加大后效果好很多，看样子不能直接使用默认值
