### ISSUE TITLE
feat: Azure AI Document Intelligence provider and extract document tool

### ISSUE THREAD

**Issue by fujita-h** [langgenius/dify#11033]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

If we want to extract document contents that require OCR or layout considerations, the built-in Document Extractor may not provide sufficient results. In such cases, you may be able to solve the problem by using an external advanced extraction tool.

As an advanced tool, we would like to add tools that use Azure AI Document Intelligence.
https://azure.microsoft.com/products/ai-services/ai-document-intelligence

### 2. Additional context or comments

Ref #11008 

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by fujita-h** [comment]
@IHAGI-c 
You can use the plugin https://github.com/fujita-h/dify-plugin-azure-ai-document-intelligence

**Comment by IHAGI-c** [comment]
> [@IHAGI-c](https://github.com/IHAGI-c) You can use the plugin https://github.com/fujita-h/dify-plugin-azure-ai-document-intelligence

Thanks for your reply.
I tried to register the v0.0.8 version from your repository as a plugin but I get a BadRequestError as shown in the following image, do you know any workaround for this?

<img width="374" alt="Image" src="https://github.com/user-attachments/assets/57288318-b9a9-4966-ba0c-cee500be03f7" />

**Comment by fujita-h** [comment]
Check out:
https://docs.dify.ai/learn-more/faq/plugins

If you need to keep your environment secure, sign it yourself.
https://docs.dify.ai/plugins/publish-plugins/signing-plugins-for-third-party-signature-verification
