### ISSUE TITLE
updata default EXPOSE_NGINX_PORT SLL 80 ,443 to 7080,7443, An error is reported when calling an external interface using code execution

### ISSUE THREAD

**Issue by alanOO7** [langgenius/dify#11045]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- update EXPOSE_NGINX_PORT=7080 ,EXPOSE_NGINX_SSL =7443
- run docker compose docker-compose.middle.yml 
- create app
- add code execution ，call xxxxx:5003 api

### ✔️ Expected Behavior

The interface result is returned correctly
![image](https://github.com/user-attachments/assets/1ac4e7f2-c8aa-491e-8586-6bc1a5e91f79)
![image](https://github.com/user-attachments/assets/303f050d-0d45-45f6-97e9-3dabb5f2e1c8)

![image](https://github.com/user-attachments/assets/53a9ee35-2b57-49cd-9928-cdacf7d98457)

### ❌ Actual Behavior

```
module> File "", line 67, in File "", line 57, in main Exception: Error: HTTP Error 503: Service Unavailable urlopen return opener.open(url, data, timeout) File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open response = meth(req, response) File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response response = self.parent.error( File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error return self._call_chain(*args) File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain result = func(*args) File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 503: Service Unavailable During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/var/sandbox/sandbox-python/tmp/990e61f2_6aac_4c2d_a007_4062068e85bb.py", line 48, in File "", line 67, in File "", line 57, in main Exception: Error: HTTP Error 503: Service Unavailable error: exit status 255
```

**Comment by crazywoola** [comment]
Make sure you have read this https://docs.dify.ai/getting-started/install-self-hosted/environments before modify those environment variables.
