### ISSUE TITLE
tool invoke error: Reached maximum retries (3)

### ISSUE THREAD

**Issue by XingWang1234** [langgenius/dify#11062]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have an API  which can generate a talking video using a person's image and audio as input. 
I customized this API into a tool and created an agent that utilizes the tool to generate talking videos.

When the audio input is short, the process works successfully. However, with longer audio inputs, it fails. The agent logs display the following error message:
> "Tool invoke error: Reached maximum retries (3) for URL http://xxxxxxx/generate_video/"

I suspect that within Dify, there is a default time limit for invoking a tool. If the process exceeds this time limit, it retries up to three times before raising the error:
> "Tool invoke error: Reached maximum retries (3) for URL http://xxxxxxx/generate_video/"

if there is default time limit, can you make time limit as parameter when user create a custom tool?
Thanks for your time.

### ✔️ Expected Behavior

The talking portrait video has been generated. You can watch it [here](url for the generated video).

### ❌ Actual Behavior

"Tool invoke error: Reached maximum retries (3) for URL http://xxxxxxx/generate_video/"

**Comment by crazywoola** [comment]
Duplicated, please see this doc https://docs.dify.ai/learn-more/faq/install-faq#id-18.-why-is-ssrf_proxy-needed

**Comment by XingWang1234** [comment]
> https://docs.dify.ai/learn-more/faq/install-faq#id-18.-why-is-ssrf_proxy-needed

Hi, sorry that I cannot get your idea. the doc is about  SSRF_PROXY, can you clarify your point? 
Thank you so much.

**Comment by XingWang1234** [comment]
even by increasing API_TOOL_DEFAULT_READ_TIMEOUT value,  tool calling will temporarily pause the chat process. only once the tool completes its task, we can continue chatting, right? can we make the agent asynchronous process? tool calling itself running in the background, and we can continue chatting with another new question
