### ISSUE TITLE
The application page cannot stay resident in the background for a long time.

### ISSUE THREAD

**Issue by Moiyu1998** [langgenius/dify#11067]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

If the application page stays in the background for a while and then is brought back to use, it gets stuck in a loading state (spinning circle) without producing any results. A refresh is required to use it again. This issue has been present for several versions. I'm not sure if this qualifies as a bug, but the application page cannot stay resident for a long time.

**Comment by crazywoola** [comment]
This has been resolved in later versions.
