### ISSUE TITLE
Web frontend can't fetch customized icon

### ISSUE THREAD

**Issue by fdb02983rhy** [langgenius/dify#11079]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Upgrade to 0.12.0

### ❌ Actual Behavior

<img width="244" alt="image" src="https://github.com/user-attachments/assets/b6086692-38fa-4241-97f6-36d93daa3b63">
<img width="458" alt="image" src="https://github.com/user-attachments/assets/14b5eec1-e3c6-4eae-9c04-bfa20ba173ed">

**Comment by crazywoola** [comment]
<img width="924" alt="image" src="https://github.com/user-attachments/assets/58f56a0c-be5b-437d-b536-18d899c75312">
Can not reproduce it. Can you provide more details?

**Comment by massif-01** [comment]
the same as mine. it showed a yellow button

**Comment by perzeuss** [comment]
> Can not reproduce it. Can you provide more details?

I can reproduce it, see https://github.com/langgenius/dify/issues/11086#issuecomment-2499009768

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/11094
