### ISSUE TITLE
Output custom parameters at the message_end node

### ISSUE THREAD

**Issue by dajianguo** [langgenius/dify#11078]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need to customize the output of some parameters in the streaming interface and non-streaming interface. For example: customized knowledge sources, recommended questions, some flags, etc.

I modified the meesage_end node to output the specified session variable.If allowed I will submit it.

![image](https://github.com/user-attachments/assets/5c69dc23-5f07-4a11-9f89-699ea21c5cb8)
![image](https://github.com/user-attachments/assets/77939d5c-272c-48f9-baab-f8c7d7d69b3f)
![image](https://github.com/user-attachments/assets/b4e39c84-3f2a-45c6-ada4-b501e3070a7c)

![image](https://github.com/user-attachments/assets/bc8c65c4-dc9e-4758-833a-d34156856a74)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by flyhighzy** [comment]
We have encountered the same issue. In fact, we have two requirements regarding the input and output of the LLM:

1. For the input, we hope to support the `tools` parameter to facilitate the invocation of built-in tools from various large model vendors, such as Kimi's web_search tool. Please refer to the API documentation: [API Documentation](https://platform.moonshot.cn/docs/guide/use-web-search#%E5%85%B3%E4%BA%8E%E5%85%BC%E5%AE%B9%E6%80%A7%E7%9A%84%E8%AF%B4%E6%98%8E).

2. For the output of the LLM, we hope that in addition to the answer itself, we can customize other output fields. For example, when retrieving information from the internet, we need to display reference material URLs to the front end, or when retrieving from a knowledge base, we need to include information about reference documents, which is the content related to this issue.

**Comment by laipz8200** [comment]
> when retrieving information from the internet, we need to display reference material URLs to the front end.

Do you mean that you need a JSON output like the workflow, but in the chatflow?

> when retrieving from a knowledge base, we need to include information about reference documents.

We have a `retriever_resources` in the `metadata` in the API response, you can check it in our API documentation.

**Comment by flyhighzy** [comment]
> Do you mean that you need a JSON output like the workflow, but in the chatflow?
> 
> >

We want to have the "LLM" node have custom output field in addition to "text", so that we can get  additional reference URL information from LLM

**Comment by laipz8200** [comment]
> so that we can get additional reference URL information from LLM.

Can this feature only be used in KIMI? Even if we set multi-output fields like in a workflow, it still cannot get the additional info from a specific LLM.

**Comment by flyhighzy** [comment]
> > so that we can get additional reference URL information from LLM.
> 
> Can this feature only be used in KIMI? Even if we set multi-output fields like in a workflow, it still cannot get the additional info from a specific LLM.

hmm, good question, actually maybe yes :(

**Comment by laipz8200** [comment]
Thank you for the suggestion. I’ll make sure to document this issue in our requirements backlog.
