### ISSUE TITLE
Creating an app from a Template causes a 404 error [SELF_HOSTED].

### ISSUE THREAD

**Issue by oakhtar147** [langgenius/dify#11082]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Went through the docs from here https://docs.dify.ai/getting-started/install-self-hosted/docker-compose

Did nothing by myself that could change the deployment.

I have not altered anything e.g. the `.env` file.

### ✔️ Expected Behavior

Creating an app from a template should work.

### ❌ Actual Behavior

Creating an app from a template fails due a 404 error.

`http://<server-ip>/console/api/apps/import` not found (404).

**Comment by poemDead** [comment]
I got the same issue in the Cloud version too.
![image](https://github.com/user-attachments/assets/ff61b73a-4450-4094-a285-a5941557d6ab)

**Comment by minghe36** [comment]
I got the same issue in the Cloud version too.
