### ISSUE TITLE
Can not hide workflow details

### ISSUE THREAD

**Issue by MKingWang** [langgenius/dify#11087]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="497" alt="image" src="https://github.com/user-attachments/assets/72b3059d-80b6-49bb-87c5-2dc018f4ecaa">

### ✔️ Expected Behavior

hide workflow details in WebApp

### ❌ Actual Behavior

cant click the show or hide workflow details in WebApp button

**Comment by perzeuss** [comment]
Hi, I assume you see this in the settings for an Agent? This feature does not work with Agents. Agents don't have workflow logs, they just have tool calls. There is no feature to hide tool calls.
