### ISSUE TITLE
Icons go Blank

### ISSUE THREAD

**Issue by djav1985** [langgenius/dify#11086]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Goto monitoring, settings and upload an icon image.

### ✔️ Expected Behavior

The icon shows up.

### ❌ Actual Behavior

The Icon shows up but when you hit save and go back in its blank, and displays blank on the front end.

**Comment by perzeuss** [comment]
I can confirm that there is an issue with rendering the custom webapp app icon. The frontend passes the image id as emoji id  instead of rendering it as image: `<em-emoji id="4024bfcd-5e82-4c41-9c68-82fd763c593c"></em-emoji>`

@dosu can you find the affected source code?

**Comment by perzeuss** [comment]
@dosu this is a duplicate of https://github.com/langgenius/dify/issues/11086
