### ISSUE TITLE
After upgrading dify to version 0.11.1 and uploading documents to the knowledge base, they have been stuck in the queue. The previously uploaded documents can be used in dialogues, but the new documents remain in the queue. Please help.

### ISSUE THREAD

**Issue by lanqy123** [langgenius/dify#11099]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

After upgrading dify to version 0.11.1 and uploading documents to the knowledge base, they have been stuck in the queue. The previously uploaded documents can be used in dialogues, but the new documents remain in the queue. Please help.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by lanqy123** [comment]
When starting with docker-compose, the following error message appears in the service. Is it related to this? and how to address this?   None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

**Comment by crazywoola** [comment]
- Check the logs of the worker container
- Use a bug report template instead
