### ISSUE TITLE
Batch run workflow report "The content of the uploaded file does not match the structure"

### ISSUE THREAD

**Issue by lfzm** [langgenius/dify#11093]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.12.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When running a workflow in batches, when the variable display name is Chinese, or the variable name and the variable display name are inconsistent, the uploaded file will report "the content of the uploaded file does not match the structure".
Tip:
1. The uploaded file is a template file downloaded.
2. Change the variable display name to English, and you can succeed.

Failure example：
![1732586448994](https://github.com/user-attachments/assets/06d1e967-24eb-4787-8a16-21f8e88d3dab)

**Comment by crazywoola** [comment]
You must keep the headers in your template `风向标内容` & `风向标编号`.

**Comment by lfzm** [comment]
@crazywoola  
There are 风向标内容 & 风向标编号 in the column of the template. I modified the data directly by downloading the template.
