### ISSUE TITLE
Adding New model Success But can't List  and Select the added model.

### ISSUE THREAD

**Issue by AlwaysBluer** [langgenius/dify#11102]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm integrating a new model provider and I have completed the majority of the work. But when I start docker and test, I found it could validate the credentials in a success, but can't store the model information.  The module is a custom model integration.

(Ignore the X inference picture please, the uderlying code is for another model provider)
![image](https://github.com/user-attachments/assets/fef911b1-61fc-4b9e-8a03-5eca817a949f)
![image](https://github.com/user-attachments/assets/e31d5d94-505a-4554-baba-85bd10ecb67d)

this is the console information
![image](https://github.com/user-attachments/assets/c538491d-6b7a-42bb-bcca-a1f6144ed12e)

and these are the files added
![image](https://github.com/user-attachments/assets/2fbb774e-7491-489a-a8ff-51bf1cdd6ee4)

the lindormai.yaml is written according to xinference.yaml
![image](https://github.com/user-attachments/assets/426a03ad-e8c1-402f-bc68-aaaa13a521b8)
![image](https://github.com/user-attachments/assets/e7f26bf9-57e2-431d-afee-76ae1214e4c0)

I'm sure this validate is success since I check it in the backend. So what's my be the reason of my failure? I would appreciate it if you can give me a hand. My 

### ✔️ Expected Behavior

The rerank models should be listed after I added the model

### ❌ Actual Behavior

no models listed
![image](https://github.com/user-attachments/assets/13a06cfd-18c1-4c4b-9062-8f18ed8fdb2a)

**Comment by AlwaysBluer** [comment]
@dousu, how do I check if the database stored the model information or not

**Comment by AlwaysBluer** [comment]
@dosu, do you know what is the entrypoint to persist the model information in dify?

**Comment by crazywoola** [comment]
Please fresh the page to see if this persists.

**Comment by AlwaysBluer** [comment]
I found the problem, it's the missing implementation of function get_customizable_model_schema.
