### ISSUE TITLE
RAG chatbot no retrieve document as it should do

### ISSUE THREAD

**Issue by Kokoabassplayer** [langgenius/dify#11109]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/de2d7cc0-5c74-429a-a699-0dee4420aae9)

### ✔️ Expected Behavior

i should retrieve chunk from document, i work perfectly in last week.

### ❌ Actual Behavior

it generate text with out chunk. it seem it not retrieve chunk at all.

**Comment by Kokoabassplayer** [comment]
![image](https://github.com/user-attachments/assets/57a59420-dfb3-4f24-a1bc-13eb45e9dd1e)
Here is the image of error i get when i test vector search

**Comment by JohnJyong** [comment]
some  inernal network connection error  caused this issue , it has fixed, thanks for your feedback
