### ISSUE TITLE
parallel iteration detail log bug report

### ISSUE THREAD

**Issue by JungHyunMoon** [langgenius/dify#11117]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Receive multiple images from the user.
2. Use the OCR API to extract text from each image.
3. Use the extracted text to perform a knowledge-based search to retrieve related documents.
4. Retrieve 5 related documents (Top-k = 5).
5. Perform masking and relevance judgment (isRelevant) on each of the retrieved documents.
6. In the execution log, the iteration should show 3 iterations for 3 images, and 5 iterations for the 5 retrieved documents.
7. However, when checking the **detailed tracing logs**, the number of iterations is incorrectly **displayed as 8** in the second iteration, where the previous OCR API call count (3) is added, resulting in an incorrect total iteration count.

### ✔️ Expected Behavior

The OCR API should be called once for each input image.
After searching for related documents, 5 documents should be retrieved (Top-k = 5).
The log should show 3 iterations for the 3 images, and 5 iterations for the 5 retrieved documents.

### ❌ Actual Behavior

In the detailed tracing logs, the second iteration incorrectly adds the OCR API call count (3), resulting in a total of 8 iterations instead of 5 for document processing.
This discrepancy does not appear in the preview logs, but it is visible in the tracing logs.
![image](https://github.com/user-attachments/assets/adbd2d4e-b226-41ae-b0cc-e15cc94e517c)

![image](https://github.com/user-attachments/assets/df76787b-88b1-41fe-9ac5-1e0ad7a348dc)

![image](https://github.com/user-attachments/assets/e18ff641-89af-4352-aff0-0a93767a58a6)

![image](https://github.com/user-attachments/assets/dae8a654-f079-4fa5-97ee-eadef4af304a)

**Comment by JungHyunMoon** [comment]
@dosu 
The option for max parallelism is set to 2 for iteration before and 3 for iteration after.

Additional questions: YML files are too large and contain private information, so how do you get them to the author?

**Comment by laipz8200** [comment]
Did any errors occur during the execution process, or are the errors only shown in the logs?

**Comment by JungHyunMoon** [comment]
I suspect it only happens in logs

Attached a screen shot in English for your understanding
![image](https://github.com/user-attachments/assets/b29a5ba5-b294-4b87-8675-7a99a9b20bee)
