### ISSUE TITLE
How to hide the detailed process of agent invocation in webapp

### ISSUE THREAD

**Issue by skywalkerfmc** [langgenius/dify#11121]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In the webapp UI, how to hide the detailed process of agent invocation, just like hiding references to a knowledge base
![image](https://github.com/user-attachments/assets/e4483ede-4443-4fd0-8f86-3c58acaf4835)

### ✔️ Expected Behavior

In the webapp UI, We can hide the detailed process of agent invocation, just like hiding references to a knowledge base

### ❌ Actual Behavior

In the webapp UI, cannot hide the detailed process of agent invocation, just like hiding references to a knowledge base

**Comment by crazywoola** [comment]
No you can not. This is a designed behavior.

**Comment by GeYiPeng** [comment]
这样会泄露隐私数据的
