### ISSUE TITLE
When the knowledge base performs segmentation analysis, pictures in the document are lost

### ISSUE THREAD

**Issue by zlm0001** [langgenius/dify#11134]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When the knowledge base performs segmentation analysis, pictures in the document are lost
![image](https://github.com/user-attachments/assets/2a0eca35-bd9a-467b-8fa9-5272d4696c2b)
![image](https://github.com/user-attachments/assets/a906a5b6-501f-41e2-af30-df90a5165fc3)

### ✔️ Expected Behavior

When the knowledge base performs segmentation parsing, the pictures in the document can be attached to the context, the same position as the original text displayed. In this way, when performing knowledge retrieval, the pictures can also be retrieved as knowledge.

### ❌ Actual Behavior

When the knowledge base was performing segmentation analysis, the pictures in the document were lost and were not stored in the knowledge base

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/11063, currently, we do not parse images in our system.

**Comment by zlm0001** [comment]
[[11063](https://github.com/langgenius/dify/issues/11063)](url)  is to analyze the content in the picture. I want to not parse the content in the picture, but to follow the picture intact in the context of the original text.

We now do knowledge questions and answers. When users do knowledge questions and answers, they hope that the large model can not only return the text, but also hope to return the pictures related to the knowledge questions and answers.

Example: I created a knowledge base related to the user manual, which contains many description of the operation steps and screenshots to assist instructions. When users ask questions and answers to the user manual knowledge base, the large model not only returns the text of the operation steps, but also returns relevant screenshots

**Comment by walawa-inc** [comment]
@zlm0001 大佬，请问你解决这个问题了嘛
