### ISSUE TITLE
When the knowledge base parses the pdf file in sections, it will be garbled.

### ISSUE THREAD

**Issue by zlm0001** [langgenius/dify#11131]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

[GB 15322.2-2019.pdf](https://github.com/user-attachments/files/17917003/GB.15322.2-2019.pdf)

After uploading the【GB15322.2-2019.pdf】file in the knowledge base of the trial environment of dify's official website, select 【Automatic Segmentation and Cleaning】, and the segmentation will be garbled code

![image](https://github.com/user-attachments/assets/10debddc-defd-49bb-815a-ada5020af6a6)
![image](https://github.com/user-attachments/assets/4eeb9442-a16e-4de5-b566-ca7693e8d15b)

![image](https://github.com/user-attachments/assets/87a46366-e4bd-4dcf-87c2-c795ada5a779)

### ✔️ Expected Behavior

The document can be parsed into Chinese normally

![image](https://github.com/user-attachments/assets/987ba594-26f2-4919-822c-8e8bb396893d)

### ❌ Actual Behavior

The parsed content is all garbled
![image](https://github.com/user-attachments/assets/87a46366-e4bd-4dcf-87c2-c795ada5a779)

**Comment by crazywoola** [comment]
See this comment https://github.com/langgenius/dify/issues/10523#issuecomment-2469377015

I have try to download the file and tried to copy into browser 
It will get something like `#$ !`
