### ISSUE TITLE
Error in Conditional Workflow When Code Executor Handles Different Knowledge Base Parameters

### ISSUE THREAD

**Issue by Angelxiaotao** [langgenius/dify#11137]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

In a conditional workflow setup, the code executor is configured to set the retrieval results of two knowledge bases as two parameters. Since our business logic requires selecting different knowledge bases based on conditions, when the if condition chooses only the A knowledge base (i.e., the code executor uses only the A parameter), the B parameter does not exist. This causes the code executor to throw an error.
I have already tried implementing default values in Node.js to handle the missing parameters, but the issue persists with the same error

1. Create a conditional workflow where the retrieval results of two knowledge bases are assigned as parameters A and B.
2. Configure an if condition in the workflow to select only the A knowledge base result.
3. During execution, the code executor attempts to access parameter B.
4. The code executor throws an error because parameter B does not exist.

### ✔️ Expected Behavior

When the conditional logic selects only the A knowledge base, the B parameter should not be required. The code executor should execute normally, using only the available parameter.

### ❌ Actual Behavior

The code executor throws an error when parameter B is not present, causing the entire workflow to fail.
![image](https://github.com/user-attachments/assets/37fe0b9e-b30d-4373-8353-ca49312d7171)
![image](https://github.com/user-attachments/assets/702eea6a-0d1e-48ce-b054-f0cf541a583c)

**Comment by crazywoola** [comment]
This has been fixed in later version.
