### ISSUE TITLE
error: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#11159]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

i need to help:
![image](https://github.com/user-attachments/assets/d8f6f678-4214-414f-8b42-7493f0fa03ff)

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/10865

**Comment by guxiyang** [comment]
Thank you, the problem has been resolved. It is possible that there were numbers in the content review configuration on our end, which caused the error. After making some modifications, it will work



***@***.***
 
From: crazywoola
Date: 2024-11-27 12:01
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] error: 'NoneType' object has no attribute 'lower' (Issue #11159)
Closed #11159 as completed.
