### ISSUE TITLE
When using the npm install command in the local execution guide, a warning message is displayed!

### ISSUE THREAD

**Issue by asemandeveloper** [langgenius/dify#11163]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When using the npm install command in the local execution [guide](https://docs.dify.ai/getting-started/install-self-hosted/local-source-code), a warning message is displayed!

npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

### ✔️ Expected Behavior

This message indicates that the **inflight@1.0.6** module, used by your project or one of its dependencies, is deprecated and no longer supported. It also mentions that this module has issues like memory leaks and advises against using it.

Instead, it recommends using **lru-cache**, which is designed for managing async requests in a safer and more robust manner.

If you don’t have direct control over this dependency (e.g., it’s part of another dependency), you can:

1. Check if a newer version of the main package (that depends on this module) has been released and update it.
2. If possible, directly remove or replace the problematic dependency.
3. Review the project’s documentation or GitHub repository to see if a solution is provided.

To proceed with the `npm install` command without warnings, you can use the `--legacy-peer-deps` flag, but note that this only suppresses the warning and doesn’t resolve the underlying issue.

**Comment by crazywoola** [comment]
```
yarn install v1.22.19
(node:57780) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "string-width@4.2.3" is incompatible with requested version "string-width@^5.1.2"
warning Resolution field "string-width@4.2.3" is incompatible with requested version "string-width@^5.0.1"
warning Resolution field "string-width@4.2.3" is incompatible with requested version "string-width@^5.0.0"
success Already up-to-date.
$ cd ../ && node -e "if (process.env.NODE_ENV !== 'production'){process.exit(1)} " || husky install ./web/.husky
husky - Git hooks installed
✨  Done in 1.49s.
```

I didn't get this warning.
