### ISSUE TITLE
Start Frontend Docker Container Separately migrates the web service to Docker, but there are some issues for API and Worker services!

### ISSUE THREAD

**Issue by asemandeveloper** [langgenius/dify#11164]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

With this [guide](https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container), the web service built locally will be moved to Docker, but there are some issues for API and Worker services!

Please provide a complete guide to porting API and Worker services built locally with this [guide ](https://docs.dify.ai/getting-started/install-self-hosted/local-source-code)to Docker so that they work well with other services available in Docker.

**Comment by crazywoola** [comment]
Not sure what you are talking about. Can you provide more details like the steps you have done?

**Comment by asemandeveloper** [comment]
Using this [guide](https://docs.dify.ai/getting-started/install-self-hosted/local-source-code), I successfully ran the API and WEB locally, and DIFY is working well. Now I want to move the API, Worker, and WEB services, which are currently running locally, into Docker. This [guide ](https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container)is suitable for migrating the WEB service to Docker, and it successfully transfers the WEB service to Docker while ensuring DIFY works correctly. However, there is no such guide available for the API and Worker services!

**Comment by crazywoola** [comment]
I see, actually you can checkout the github actions.
