### ISSUE TITLE
ZHIPU·AI LLM does not have a context size number of tokens label

### ISSUE THREAD

**Issue by MrXionGe** [langgenius/dify#11181]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

**First**
**Add the key of ZHIPU·AI.**

**Then**
**Settings --> Model Provider --> Find ZHIPU·AI --> Show Models**

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/daeba8b4-f05d-45ad-81fe-b1beb0d130e7)
On the right side of the LLM element, show the maximum number of tokens for each model label.
I would love to provide the maximum number of tokens per LLM if I can contribute to Dify.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/4537ecfa-dc83-4c70-8c72-75d0286013cb)
To the right of the LLM element, there is no label for the maximum number of tokens.
Also, the maximum number of tokens for GLM-4-Long is 1M, not 10K.

**Comment by crazywoola** [comment]
It seems this field is missing in `*.yaml` files.

```
model_properties:
  context_size: 131072
```

**Comment by MrXionGe** [comment]
@crazywoola  
ZHIPU·AI content size

| model | size |
| --- | --- |
| glm-4-0520 | 131072 |
| glm-4-air | 131072 |
| glm-4-airx | 8192 |
| glm-4-flash | 131072 |
| glm-4-flahx | 131072 |
| glm-3-trubo | 131072 |
| glm-4 | 131072 |
| glm-4-long | 1048576 |
| glm-4-plus | 131072 |
| glm-4v | 2048 |
| glm-4v-plus | 8192 |
