### ISSUE TITLE
set a conversational variable to type array[Object] and set the write mode of “Variable Assignment” to “Append” to append another array, the entire array is appended as a new element.

### ISSUE THREAD

**Issue by mihit** [langgenius/dify#11186]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Do as the title.

### ✔️ Expected Behavior

Merge two arrays.

### ❌ Actual Behavior

It produces a broken data.

**Comment by crazywoola** [comment]
Is this a feature request or a bug description?

**Comment by crazywoola** [comment]
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/cabdd1c8-0801-4126-afd8-b0b36d4f8101">
I tried with above workflow.  Is this what you want?
[Issue 11186.yml.zip](https://github.com/user-attachments/files/17944689/Issue.11186.yml.zip)

**Comment by crazywoola** [comment]
So I guess this should be a `extend` function right?  We will have it soon :)

**Comment by mihit** [comment]
@crazywoola 
Awesome, looking forward to it!

**Comment by crazywoola** [comment]
See v0.13.0 https://github.com/langgenius/dify/releases/tag/0.13.0

**Comment by mihit** [comment]
@crazywoola Thanks!
