### ISSUE TITLE
dify could not use ollama which is not deployed in the same pc.

### ISSUE THREAD

**Issue by lichq5** [langgenius/dify#11189]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. in one pc A, deploying Dify in docker;
2. in another pc B, deploying ollama in docker and set OLLAMA_HOST=0.0.0.0:11610, and IP of this pc is 172.18.168.29.  And in pc A, I can use curl to post request to ollama in pc B and get normal response:
curl http://172.18.168.29:11610/api/chat -d '{
  "model": "llama3.2:latest",
  "messages": [
    { "role": "user", "content": "你好" }
  ]
}'
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.371365037Z","message":{"role":"assistant","content":"您"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.388414713Z","message":{"role":"assistant","content":"好"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.40235031Z","message":{"role":"assistant","content":"！"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.415910858Z","message":{"role":"assistant","content":"怎么"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.434160199Z","message":{"role":"assistant","content":"可以"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.44787535Z","message":{"role":"assistant","content":"帮助"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.461592598Z","message":{"role":"assistant","content":"您"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.475252773Z","message":{"role":"assistant","content":"呢"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.488440675Z","message":{"role":"assistant","content":"？"},"done":false}
{"model":"llama3.2:latest","created_at":"2024-11-28T08:31:07.50166157Z","message":{"role":"assistant","content":""},"done_reason":"stop","done":true,"total_duration":6765367136,"load_duration":5102448527,"prompt_eval_count":27,"prompt_eval_duration":1512000000,"eval_count":10,"eval_duration":148000000}
which means pc A and pc B are accessable.
3. in pc A, entering baseURL: http:172.18.168.18:11610 and model name
4. save and failed with result:
code
: 
"invalid_param"
message
: 
"An error occurred during credentials validation: HTTPConnectionPool(host='172.18.168.29', port=11610): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f881caf5ee0>: Failed to establish a new connection: [Errno 113] No route to host'))"
status
: 
400

### ✔️ Expected Behavior

expecting saving success and model is added to Dify.

### ❌ Actual Behavior

saving failed with result:
code
: 
"invalid_param"
message
: 
"An error occurred during credentials validation: HTTPConnectionPool(host='172.18.168.29', port=11610): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f881caf5ee0>: Failed to establish a new connection: [Errno 113] No route to host'))"
status
: 
400

as I see: in docker-api-1, I failed to send the curl test to PC B, so may be it is the root cause  inside docker-api-1, we could not connect pc B, even though pc B and pc A is accessable. 
my question is how to modify the config of docker-api-1 so docker-api-1 can send request to pc B.

**Comment by crazywoola** [comment]
https://mp.weixin.qq.com/s/uyjpzIUzoMhYbmGxm1PolQ

**Comment by lichq5** [comment]
> https://mp.weixin.qq.com/s/uyjpzIUzoMhYbmGxm1PolQ

感谢[crazywoola](https://github.com/crazywoola)的回答。但是这个链接解决的并不是我的问题。设置
extra_hosts:
      - host.docker.internal:host-gateway
并不能使得pc A的dify能访问pc B的ollama 的api，只是允许dify docker访问pc A的网络服务。如果我理解有错，也希望能指出，谢谢！

**Comment by crispnoodles** [comment]
> 你好，我用vllm(B)+oneapi(A)+dify(A)也遇到了这个问题，在machine A上可通过requests.post访问oneapi获得模型输出，但在dify中配置时就会出现这个问题。请问你现在解决了吗？

我解决了我的问题：dify配置时，使用宿主机的ip地址+oneapi的端口（eg: http://192.168.56.108:3001/v1，不是localhost:3001/v1）

**Comment by maryhh** [comment]
> > > https://mp.weixin.qq.com/s/uyjpzIUzoMhYbmGxm1PolQ
> > 
> > 
> > 感谢[crazywoola](https://github.com/crazywoola)的回答。但是这个链接解决的并不是我的问题。设置 extra_hosts: - host.docker.internal:host-gateway 并不能使得pc A的dify能访问pc B的ollama 的api，只是允许dify docker访问pc A的网络服务。如果我理解有错，也希望能指出，谢谢！
> 
> 请问您解决了吗？我也遇到了同样的问题，改了host的配置也不生效

hello ，有人解决这个问题吗？我也碰到了 ，我觉得应该是该docker-compose.yaml里的内容，但是我不清楚改哪个

**Comment by lergliu** [comment]
> > > > https://mp.weixin.qq.com/s/uyjpzIUzoMhYbmGxm1PolQ
> > > 
> > > 
> > > 感谢[crazywoola](https://github.com/crazywoola)的回答。但是这个链接解决的并不是我的问题。设置 extra_hosts: - host.docker.internal:host-gateway 并不能使得pc A的dify能访问pc B的ollama 的api，只是允许dify docker访问pc A的网络服务。如果我理解有错，也希望能指出，谢谢！
> > 
> > 
> > 请问您解决了吗？我也遇到了同样的问题，改了host的配置也不生效
> 
> hello ，有人解决这个问题吗？我也碰到了 ，我觉得应该是该docker-compose.yaml里的内容，但是我不清楚改哪个

我是在同一台服务器上，dify和ollama都是容器部署，在dify页面增加模型时url填http://container_name:port，通过这种方式解决的
