### ISSUE TITLE
podcast workflow is bug at the PODCAST AUDIO GENERATOR node

### ISSUE THREAD

**Issue by Kokoabassplayer** [langgenius/dify#11184]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

step:
- create app from template NotebookLM by Dify.AI
- change llm model to gemini 1.5 flash 002
- click preview to test flow
- upload md file, here is the file: [output.md](https://github.com/user-attachments/files/17943286/output.md)
- click on "click me!" button
- everything run smooth until podcast node
- error

### ✔️ Expected Behavior

receive audio file of podcast

### ❌ Actual Behavior

got error at node: PODCAST AUDIO GENERATOR
error message: Run failed: None is not a valid FileType
![image](https://github.com/user-attachments/assets/b693da5c-7c6d-4964-8994-30742763bb94)

**Comment by Kokoabassplayer** [comment]
![image](https://github.com/user-attachments/assets/f6848dd1-dac8-4dcd-89c3-4efa80d0bc27)
1 host voices is specified
2 key is provided, it consume my credit 
![image](https://github.com/user-attachments/assets/049243fa-f04e-4a59-b9e3-609d6306c55e)

**Comment by crazywoola** [comment]
Fixed in (#11167)
