### ISSUE TITLE
"the parent_meesage_id is not valid uuid" while doing multi model compaire test

### ISSUE THREAD

**Issue by IceNiro** [langgenius/dify#11199]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

We encountered an error when doing a multi-model test on the web debug and preview page.

![image](https://github.com/user-attachments/assets/8e593d0e-abe7-4dd2-b724-a78bdd19d14c)
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/958f2757-a095-4cbf-be98-13b9bb2598ab">

We notice that when the opening statement setting is not present in the agent config, it is just fine, but an error occurs with the opening statement. 
With the error message shows up, the request parameter: parent_message_id is different, it requires a UUID string but looks like receive a timestamp number sequence when an error encountered

### ✔️ Expected Behavior

the multi-model test can run normally 

### ❌ Actual Behavior

encounter an exception

**Comment by crazywoola** [comment]
Please upgrade to latest version. This should been resolved in later version.
