### ISSUE TITLE
Custom file list variable, when asked questions, the file list variable is empty

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#11190]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I customized a file list variable named 'documentFiles' at the start node of chatflow, but when I asked about it, I couldn't pass' documentFiles' in. I don't know what's going on. Here are the steps to follow:

![image](https://github.com/user-attachments/assets/6410df3c-942a-49a3-8f9c-9b8e05495cce)
![image](https://github.com/user-attachments/assets/e3f63f8a-3eec-44c4-aa55-f3ebc8ac96bc)

The screenshot above shows that after I finished asking the first question, I followed up with a follow-up question and sent a picture. Then, I entered the message "Interpret the document report I uploaded". The reply was not what I wanted. Based on the logs, it was at the beginning node and the documentFiles were null
{
"documentFiles": null,
Sys. query ":" Interpret the document report I uploaded ",
"sys.files": [],
"sys.conversation_id": "980b8e22-eac3-4452-bce1-c9c6fb15d692",
"sys.user_id": "7eb59681-5390-4ca9-b96b-5c517edaabc7",
"sys.dialogue_count": 1,
"sys.app_id": "ff68535f-d5f5-48b9-87e4-43d41a4caa2f",
"sys.workflow_id": "2a411d33-e6f0-4371-8f97-2b46acbea5d3",
"sys.workflow_run_id": "4e5160df-a7e8-4817-8c45-cd0118a0f5cb"
}

**Comment by crazywoola** [comment]
This is a designed behavior, we won't pass it into the second round, in this case, you need to extract things in the first round and use a `variable assigner` to assign it to `conversational variable`.
However this is an old way, now you can refer the file parameter in the prompt, so you won't lose the information. But this feature only works in limited models.  https://github.com/langgenius/dify/releases/tag/0.12.0. 

The latest version is https://github.com/langgenius/dify/releases/tag/0.12.1

Checkout this article https://docs.dify.ai/guides/workflow/file-upload
