### ISSUE TITLE
payload in validate_credentials does not contain input_type

### ISSUE THREAD

**Issue by pohndorff** [langgenius/dify#11193]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. In Settings -> Model Provider -> OpenAI-API-compatible add new Model
2. Select Text Embedding, Model Name: "nvidia/nv-embedqa-mistral-7b-v2", API Key: XXX, API endpoint URL: http://<Base URL>/nim-embedding/v1, Model context size: 4096

### ✔️ Expected Behavior

200, configuration successful

https://github.com/langgenius/dify/blob/0f1133729f71dcc2ebe9921ebff6e996557b2efb/api/core/model_runtime/model_providers/openai_api_compatible/text_embedding/text_embedding.py#L148

probably correct payload
            `payload = {"input": "ping", "model": model, "input_type": "query"}`

### ❌ Actual Behavior

Error 400, configuration cannot finish

**Comment by yihong0618** [comment]
better choose here instead of OpenAI-API-compatible
![image](https://github.com/user-attachments/assets/489d2441-1fb3-4e27-b332-a81a594349e9)

**Comment by pohndorff** [comment]
@yihong0618 mistral is locally deployed on nim, not via NVIDIA cloud. difys NIM-connector does not support models other than LLM.

**Comment by pohndorff** [comment]
LLMs are working as intended. It's just embedding models.

**Comment by yihong0618** [comment]
> LLMs are working as intended. It's just embedding models.
> 
> EDIT: The additional parameter `"input_type"` will be mandatory for all embedding models that are retrieval optimized.

https://github.com/langgenius/dify/pull/11239
