### ISSUE TITLE
Dify is called through API interface, and the output content is continuously repeated

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#11213]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, we are calling through the dify console or the dify API interface and have found that the output content keeps repeating. We don't know what's going on. In order to solve a problem, we have configured the following output content. We don't know if it's a problem with dify or Alibaba. The large model we have configured is qwen-vl-max-0809, and the output content is as follows:

血压高，即高血压，是一种常见的慢性疾病，需要长期管理和治疗。以下是一些科学控制血压的建议：

1. **健康饮食**：
   - 限制钠盐摄入，每日摄入量不超过6克。
   - �血压高，即高血压，是一种常见的慢性疾病，需要长期管理和治疗。以下是一些科学控制血压的建议：

1. **健康饮食**：
   - 限制钠盐摄入，每日摄入量不超过6克。
   - 增加钾的摄入，如多吃香蕉、橙子和菠菜。
   - 选择低脂、高纤维食物，如全谷物、蔬菜和瘦肉。

2. **规律运动**：
   - �血压高，即高血压，是一种常见的慢性疾病，需要长期管理和治疗。以下是一些科学控制血压的建议：

1. **健康饮食**：
   - 限制钠盐摄入，每日摄入量不超过6克。
   - 增加钾的摄入，如多吃香蕉、橙子和菠菜。
   - 选择低脂、高纤维食物，如全谷物、蔬菜和瘦肉。

2. **规律运动**：
   - 每周至少150分钟的中等强度有氧运动，例如快走、骑自行车或游泳。
   - �血压高，即高血压，是一种常见的慢性疾病，需要长期管理和治疗。以下是一些科学控制血压的建议：

1. **健康饮食**：
   - 限制钠盐摄入，每日摄入量不超过6克。
   - 增加钾的摄入，如多吃香蕉、橙子和菠菜。
   - 选择低脂、高纤维食物，如全谷物、蔬菜和瘦肉。

2. **规律运动**：
   - 每周至少150分钟的中等强度有氧运动，例如快走、骑自行车或游泳。
   - 每周进行至少两次力量训练，帮助改善心血管健康。

3. **生活方式调整**：
   - 保持健康体重，BMI控制在18.5-24.9之间，男性腰围不超过90厘米，女性不超过85厘米。
   - 限制酒精摄入，男性每日不超过两杯，女性不超过一杯。
   - �血压高，即高血压，是一种常见的慢性疾病，需要长期管理和治疗。以下是一些科学控制血压的建议：

1. **健康饮食**：
   - 限制钠盐摄入，每日摄入量不超过6克。
   - 增加钾的摄入，如多吃香蕉、橙子和菠菜。
   - 选择低脂、高纤维食物，如全谷物、蔬菜和瘦肉。

2. **规律运动**：
   - 每周至少150分钟的中等强度有氧运动，例如快走、骑自行车或游泳。
   - 每周进行至少两次力量训练，帮助改善心血管健康。

3. **生活方式调整**：
   - 保持健康体重，BMI控制在18.5-24.9之间，男性腰围不超过90厘米，女性不超过85厘米。
   - 限制酒精摄入，男性每日不超过两杯，女性不超过一杯。
   - 戒烟，避免吸烟对血压的负面影响。

4. **减少压力**：
   - �血压高，即高血压，是一种常见的慢性疾病，需要长期管理和治疗。以下是一些科学控制血压的建议：

1. **健康饮食**：
   - 限制钠盐摄入，每日摄入量不超过6克。
   - 增加钾的摄入，如多吃香蕉、橙子和菠菜。
   - 选择低脂、高纤维食物，如全谷物、蔬菜和瘦肉。

2. **规律运动**：
   - 每周至少150分钟的中等强度有氧运动，例如快走、骑自行车或游泳。
   - 每周进行至少两次力量训练，帮助改善心血管健康。

3. **生活方式调整**：
   - 保持健康体重，BMI控制在18.5-24.9之间，男性腰围不超过90厘米，女性不超过85厘米。
   - 限制酒精摄入，男性每日不超过两杯，女性不超过一杯。
   - 戒烟，避免吸烟对血压的负面影响。

4. **减少压力**：
   - 学习放松技巧，如深呼吸、冥想或瑜伽。
   - 保持良好的睡眠习惯，每晚7-9小时。

5. **药物治疗**：
   - 如果生活方式调整后血压仍未达标，建议在医生指导下使用降压药物，例如ACE抑制剂或钙通道阻滞剂。

6. **定期监测**：
   - �血压高，即高血压，是一种常见的慢性疾病，需要长期管理和治疗。以下是一些科学控制血压的建议：

1. **健康饮食**：
   - 限制钠盐摄入，每日摄入量不超过6克。
   - 增加钾的摄入，如多吃香蕉、橙子和菠菜。
   - 选择低脂、高纤维食物，如全谷物、蔬菜和瘦肉。

2. **规律运动**：
   - 每周至少150分钟的中等强度有氧运动，例如快走、骑自行车或游泳。
   - 每周进行至少两次力量训练，帮助改善心血管健康。

3. **生活方式调整**：
   - 保持健康体重，BMI控制在18.5-24.9之间，男性腰围不超过90厘米，女性不超过85厘米。
   - 限制酒精摄入，男性每日不超过两杯，女性不超过一杯。
   - 戒烟，避免吸烟对血压的负面影响。

4. **减少压力**：
   - 学习放松技巧，如深呼吸、冥想或瑜伽。
   - 保持良好的睡眠习惯，每晚7-9小时。

5. **药物治疗**：
   - 如果生活方式调整后血压仍未达标，建议在医生指导下使用降压药物，例如ACE抑制剂或钙通道阻滞剂。

6. **定期监测**：
   - 定期测量血压，了解血压变化趋势。
   - 与医生保持沟通，根据血压变化调整治疗方案。

请记住，高血压的管理是一个长期的过程，需要您的持续努力和医生的指导。如果您的血压持续升高或出现其他不适症状，请及时就医。

**Comment by crazywoola** [comment]
<img width="453" alt="image" src="https://github.com/user-attachments/assets/a4a7a738-a9f6-43ae-be24-1c90cbcb5398">

**Comment by guxiyang** [comment]
Hello, we didn't understand the picture you sent and don't know what it means



***@***.***
 
From: crazywoola
Date: 2024-11-29 17:30
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] Dify is called through API interface, and the output content is continuously repeated (Issue #11213)
image.png (view on web)

**Comment by crazywoola** [comment]
This problem occurs when you don't set proper stop sequences. This is not raised by dify itself. Please do not open duplicated questions.
