### ISSUE TITLE
Duplicate returns from uploading images on the dify console

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#11217]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I created a workflow on the DIY workbench and uploaded a medical examination report. However, the DIY console returned a duplicate reply message. I hope you can help me clarify this. Thank you. The steps are as follows:
![image](https://github.com/user-attachments/assets/e9641720-e4bb-41ec-bea2-815fb186ef62)
![image](https://github.com/user-attachments/assets/b2ac7ffe-a506-40ba-a650-a523af2986c1)

**Comment by guxiyang** [comment]
I don't know if it's related to special characters, but from the information in the screenshot, there are some special characters inside



***@***.***
 
From: dosubot[bot]
Date: 2024-11-29 19:10
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] Duplicate returns from uploading images on the dify console (Issue #11217)
I couldn't find specific information about how the Dify console handles duplicate messages during image uploads. However, there are some configurations in the self-hosted Docker setup that might affect image upload handling, such as STORAGE_TYPE, STORAGE_LOCAL_PATH, UPLOAD_IMAGE_FILE_SIZE_LIMIT, and MULTIMODAL_SEND_IMAGE_FORMAT [1].
For the issue of duplicate messages, it might be helpful to check the logging and error handling mechanisms in your setup to see if there are any clues. Additionally, reviewing the code in the web/app/components/base/file-uploader/utils.ts file might provide insights into how files are processed and if there are any conditions that could lead to duplicate responses [2].
If the issue persists, consider checking for any updates or patches that might address this behavior in newer versions of Dify.
To continue talking to Dosu, mention @dosu.

**Comment by guxiyang** [comment]
I don't know if it's related to special characters, but from the information in the screenshot, there are some special characters inside


***@***.***
 
From: dosubot[bot]
Date: 2024-11-29 19:10
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] Duplicate returns from uploading images on the dify console (Issue #11217)
I couldn't find specific information about how the Dify console handles duplicate messages during image uploads. However, there are some configurations in the self-hosted Docker setup that might affect image upload handling, such as STORAGE_TYPE, STORAGE_LOCAL_PATH, UPLOAD_IMAGE_FILE_SIZE_LIMIT, and MULTIMODAL_SEND_IMAGE_FORMAT [1].
For the issue of duplicate messages, it might be helpful to check the logging and error handling mechanisms in your setup to see if there are any clues. Additionally, reviewing the code in the web/app/components/base/file-uploader/utils.ts file might provide insights into how files are processed and if there are any conditions that could lead to duplicate responses [2].
If the issue persists, consider checking for any updates or patches that might address this behavior in newer versions of Dify.
To continue talking to Dosu, mention @dosu.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/11213
