### ISSUE TITLE
not supported value type array[string]

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#11228]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I received an error message while operating on the DIY workbench, 'not supported value type array [string]'. What is the reason for this? We are using the Zhipu large model as our model, and the steps are as follows:
1. First uploaded an image, and then parsed it normally.
2. After completing the image analysis, we added an additional question
3. Then prompt: not supported value type array [string]
As shown in the figure:
![image](https://github.com/user-attachments/assets/215f07f4-4ce2-4e90-9bfc-772ae61f0f92)

**Comment by crazywoola** [comment]
The answer node in this version v0.11.2 doesn't support display array, this feature requires version greater than v0.12.0.

**Comment by guxiyang** [comment]
ok,thanks


***@***.***
 
From: crazywoola
Date: 2024-11-30 17:26
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] not supported value type array[string] (Issue #11228)
The answer node in this version v0.11.2 doesn't support display array, this feature requires version greater than v0.12.0.
