### ISSUE TITLE
TypeError: Object of type File is not JSON serializable

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#11236]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, we uploaded a document with the suffix. docx through the DIY backend. When we were in the document extractor node, we found that the DIY API backend reported a TypeError: Object of type File is not JSON serializable. We know if this is a bug or if there is a problem with the docx document itself. The content of the docx is as follows:

**Comment by crazywoola** [comment]
Please provide the DSL file and can you explain what is the 'DIY' backend?

**Comment by yihong0618** [comment]
@guxiyang @crazywoola please delete the pic in the issue content, there's been a leak of sensitive information.

**Comment by guxiyang** [comment]
Okay, it has been deleted


***@***.***
 
From: yihong
Date: 2024-12-02 09:14
To: langgenius/dify
CC: 顾夕旸; Mention
Subject: Re: [langgenius/dify] TypeError: Object of type File is not JSON serializable (Issue #11236)
@guxiyang @crazywoola please delete the pic in the issue content, there's been a leak of sensitive information.

**Comment by guxiyang** [comment]
Okay, I often refer to DIY's own preview page as DIY's backend. I don't know how you call it




***@***.***
 
From: crazywoola
Date: 2024-12-02 09:11
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] TypeError: Object of type File is not JSON serializable (Issue #11236)
Please provide the DSL file and can you explain what is the 'DIY' backend?

**Comment by yihong0618** [comment]
> Okay, I often refer to DIY's own preview page as DIY's backend. I don't know how you call it ***@***.*** From: crazywoola Date: 2024-12-02 09:11 To: langgenius/dify CC: 顾夕旸; Author Subject: Re: [langgenius/dify] TypeError: Object of type File is not JSON serializable (Issue #11236) Please provide the DSL file and can you explain what is the 'DIY' backend? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

its the api in the log, and tab in the chrome..

**Comment by laipz8200** [comment]
Could you kindly provide a screenshot of the backend server during the occurrence of this issue?

**Comment by guxiyang** [comment]
> Could you kindly provide a screenshot of the backend server during the occurrence of this issue?

ok,
![image](https://github.com/user-attachments/assets/15af4c67-be98-4015-b07a-b3a95d42db80)
