### ISSUE TITLE
Bug ollama model actions:  qwq:32b-preview-fp16, bug occur 'can only concatenate str (not "list") to str'

### ISSUE THREAD

**Issue by gigascake** [langgenius/dify#11247]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0, 0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

ollama model :  qwq:32b-preview-fp16
this models likes chatgpt-o1-preview

run this model on the dify. bug occur 'can only concatenate str (not "list") to str'

How to solve this problem?

### ✔️ Expected Behavior

this model say  'questions to answer'

### ❌ Actual Behavior

bug occur 'can only concatenate str (not "list") to str'

<img width="995" alt="image" src="https://github.com/user-attachments/assets/42bb5537-2224-4dc2-b368-8fc1910dbd5b">

<img width="247" alt="image" src="https://github.com/user-attachments/assets/78e3c9c8-f9ad-4a2b-88a7-4aa41f183d94">

**Comment by yihong0618** [comment]
can you provide your dsl? thanks

**Comment by gigascake** [comment]
[Text Summarization Workflow2.zip](https://github.com/user-attachments/files/17971889/Text.Summarization.Workflow2.zip)

**Comment by mhorijp** [comment]
I encounter the same bug when I use US Meta Llama 3.2 90B Instruct on AWS Bedrock.
I use Dify 0.12.1 (Self Hosted). I have attached dsl below.
[Llama.yml.zip](https://github.com/user-attachments/files/17975516/Llama.yml.zip)

Thanks.

**Comment by dino-collectiv** [comment]
Encountered this on 0.12.1 as well. 
Seems only happens on LLMs Configured with Completion Mode.

**Comment by gigascake** [comment]
this model, qwq mode change completion model to chat model, same message occur.
