### ISSUE TITLE
how to upload images in Custom tool

### ISSUE THREAD

**Issue by zqy22** [langgenius/dify#11249]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to create a new tool for image processing, but I am having trouble in the upload step, I have tried many ways but the files can not be uploaded to the "files" variable
![seg-image](https://github.com/user-attachments/assets/9c45d7cb-1764-4ea6-8749-a7a517181740)
How should I define the return structure so that variables can be correctly uploaded to "files"

### 2. Additional context or comments

My openapi file and client file are as follows:
openapi: 3.0.2
info:
  title: Image Segmentation Service
  description: A service for performing image segmentation using a Flask API.
  version: 1.0.0
servers:
  - url: http://localhost:6002
    description: Local development server

paths:
  /segment-image_6002:
    post:
      summary: Perform image segmentation
      description: Send an image URL to the service to perform image segmentation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageSegmentationRequest'
      responses:
        '200':
          description: Successful response with segmentation results and segmented image
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: The segmentation results in text format.
                  file:
                    type: string
                    format: binary
                    description: The segmented image file.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.

components:
  schemas:
    ImageSegmentationRequest:
      type: object
      properties:
        pic_need_judge:
          type: string
          format: uri
          description: The URL of the image to be segmented.
      required:
        - pic_need_judge

    SegmentationResult:
      type: object
      properties:
        category:
          type: string
          description: The category of the detected object.
        score:
          type: number
          format: float
          description: The confidence score of the detection.
        box:
          type: array
          items:
            type: integer
          description: The bounding box coordinates [x1, y1, x2, y2].
          
          
 
 
 from flask import Flask, request, jsonify
import os
import requests
import mimetypes

app = Flask(__name__)

@app.route('/segment-image_6002', methods=['POST'])
def segment_image():
    input_data = request.json
    print(f"Received input_data: {input_data}")

    if not input_data:
        return jsonify({"error": "Missing required parameter"}), 400

    image_path = input_data.get("pic_need_judge") 
    if not image_path:
        return jsonify({"error": "Missing pic_need_judge parameter"}), 400

    image_path = image_path.strip()  
    if not os.path.exists(image_path):
        return jsonify({"error": f"Invalid or missing image path: {image_path}"}), 400

    api_url = "http://localhost:6000/api/v1/depth-estimation"  
    data = {"image_path": image_path}

    try:
        response = requests.post(api_url, json=data)
    except requests.exceptions.RequestException as e:
        return jsonify({"error": f"Request failed: {str(e)}"}), 500

    if response.status_code == 200:
        result_data = response.json()
        message = result_data.get("result_text", "No message returned")
        processed_image_path = result_data.get("image_path", "") 
        json_path = result_data.get("json_path", "")  

        if not processed_image_path or not os.path.exists(processed_image_path):
            return jsonify({"error": f"Invalid or missing processed image path: {processed_image_path}"}), 400

        from werkzeug.datastructures import Headers
        from werkzeug.wrappers import Response

        def generate_multipart_response():
            boundary = '----WebKitFormBoundary7MA4YWxkTrZu0gW'
            headers = Headers()
            headers.add('Content-Type', f'multipart/form-data; boundary={boundary}')

            yield (f'--{boundary}\r\n'
                   'Content-Disposition: form-data; name="text"\r\n\r\n'
                   f'{message}\r\n')

            mime_type, _ = mimetypes.guess_type(processed_image_path)
            yield (f'--{boundary}\r\n'
                   f'Content-Disposition: form-data; name="file"; filename="segmented_image.{mimetypes.guess_extension(mime_type)}"\r\n'
                   f'Content-Type: {mime_type}\r\n\r\n')
            with open(processed_image_path, 'rb') as img:
                while True:
                    chunk = img.read(8192)
                    if not chunk:
                        break
                    yield chunk
            yield f'\r\n--{boundary}--\r\n'

        return Response(generate_multipart_response(), status=200)
    else:
        error_message = response.text
        print(f"Error response from depth estimation service: {error_message}")
        return jsonify(
            {"error": f"Request failed with status {response.status_code}: {error_message}"}), response.status_code

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=6002, debug=True)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by zqy22** [comment]
> Hey @zqy22, I'm here to assist with any bugs, questions, or contributions you might have. Let's work through this together!
> 
> To upload images to the "files" variable in your custom image processing tool using the provided Flask API, you need to adjust your API endpoint to accept file uploads. Here's a basic example of how you can modify your Flask route to handle file uploads:
> 
> 1. **Modify the Flask Route to Accept Files:**
>    Update your `segment_image` function to handle file uploads using `request.files`:
>    ```python
>    from flask import Flask, request, jsonify
>    import os
>    
>    app = Flask(__name__)
>    
>    @app.route('/segment-image_6002', methods=['POST'])
>    def segment_image():
>        if 'file' not in request.files:
>            return jsonify({"error": "No file part"}), 400
>    
>        file = request.files['file']
>        if file.filename == '':
>            return jsonify({"error": "No selected file"}), 400
>    
>        # Save the file to a temporary location
>        file_path = os.path.join('/tmp', file.filename)
>        file.save(file_path)
>    
>        # Process the file as needed
>        # For example, call your image processing function here
>    
>        return jsonify({"message": "File uploaded successfully"}), 200
>    
>    if __name__ == "__main__":
>        app.run(host='0.0.0.0', port=6002, debug=True)
>    ```
> 2. **Update the OpenAPI Specification:**
>    Ensure your OpenAPI specification reflects that the endpoint accepts `multipart/form-data` for file uploads:
>    ```yaml
>    paths:
>      /segment-image_6002:
>        post:
>          summary: Perform image segmentation
>          requestBody:
>            required: true
>            content:
>              multipart/form-data:
>                schema:
>                  type: object
>                  properties:
>                    file:
>                      type: string
>                      format: binary
>                      description: The image file to be segmented.
>          responses:
>            '200':
>              description: Successful response
>              content:
>                application/json:
>                  schema:
>                    type: object
>                    properties:
>                      message:
>                        type: string
>                        description: Success message.
>            '400':
>              description: Bad request
>              content:
>                application/json:
>                  schema:
>                    type: object
>                    properties:
>                      error:
>                        type: string
>                        description: Error message.
>    ```
> 3. **Client-Side Code to Upload Files:**
>    Use a client-side script to send the file to your Flask API. Here's an example using Python's `requests` library:
>    ```python
>    import requests
>    
>    url = 'http://localhost:6002/segment-image_6002'
>    files = {'file': open('path_to_your_image.jpg', 'rb')}  # Replace with your image path
>    
>    response = requests.post(url, files=files)
>    
>    if response.status_code == 200:
>        print('File uploaded successfully:', response.json())
>    else:
>        print('Failed to upload file:', response.status_code, response.text)
>    ```
> 
> This setup should allow you to upload images to your Flask API and process them as needed. Adjust the file handling and processing logic according to your specific requirements.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

You seem to have misunderstood me. In my code, I need to return a file to "files" in the output variable and hand this file over to the LLM to continue processing @dosu

**Comment by zqy22** [comment]
> To ensure that the processed image file is correctly included in the 'files' output variable and can be handed over to the LLM for further processing, you need to structure your API response to match the expected format for the 'files' variable in the Dify platform. Here's how you can do it:
> 
> 1. **Define the 'files' Output Structure:**
>    The 'files' output variable should be an array of file objects, each with the following structure:
>    ```json
>    {
>      "name": "segmented_image.jpg",
>      "size": 123456,
>      "type": "image",
>      "extension": "jpg",
>      "mime_type": "image/jpeg",
>      "transfer_method": "url",
>      "url": "http://localhost:6002/path/to/segmented_image.jpg"
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Ensure that each file object includes the file's name, size, type, extension, MIME type, transfer method, and URL [[1]](https://github.com/langgenius/dify/blob/main/web/app/components/workflow/constants.ts).
> 2. **Modify the Flask API to Return the File:**
>    Update your Flask API to return the processed image file in the correct format. Here's an example of how you can modify your `segment_image` function to include the file in the response:
>    ```python
>    from flask import Flask, request, jsonify, url_for
>    import os
>    
>    app = Flask(__name__)
>    
>    @app.route('/segment-image_6002', methods=['POST'])
>    def segment_image():
>        # Your existing code to process the image
>    
>        # Assuming processed_image_path is the path to the processed image
>        file_name = os.path.basename(processed_image_path)
>        file_size = os.path.getsize(processed_image_path)
>        mime_type, _ = mimetypes.guess_type(processed_image_path)
>    
>        file_info = {
>            "name": file_name,
>            "size": file_size,
>            "type": "image",
>            "extension": file_name.split('.')[-1],
>            "mime_type": mime_type,
>            "transfer_method": "url",
>            "url": url_for('static', filename=file_name, _external=True)  # Ensure the file is accessible via URL
>        }
>    
>        return jsonify({
>            "text": message,
>            "files": [file_info],
>            "json": result_data
>        }), 200
>    
>    if __name__ == "__main__":
>        app.run(host='0.0.0.0', port=6002, debug=True)
>    ```
> 3. **Ensure File Accessibility:**
>    Make sure that the processed image file is accessible via the URL you provide in the response. You might need to serve the file from a static directory or use a file hosting service.
> 
> By structuring your response this way, the Dify platform should be able to recognize and process the file in the LLM workflow.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

how could I upload local image in this example@dosu

**Comment by zqy22** [comment]
> To ensure that the processed image file is correctly included in the 'files' output variable and can be handed over to the LLM for further processing, you need to structure your API response to match the expected format for the 'files' variable in the Dify platform. Here's how you can do it:
> 
> 1. **Define the 'files' Output Structure:**
>    The 'files' output variable should be an array of file objects, each with the following structure:
>    ```json
>    {
>      "name": "segmented_image.jpg",
>      "size": 123456,
>      "type": "image",
>      "extension": "jpg",
>      "mime_type": "image/jpeg",
>      "transfer_method": "url",
>      "url": "http://localhost:6002/path/to/segmented_image.jpg"
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Ensure that each file object includes the file's name, size, type, extension, MIME type, transfer method, and URL [[1]](https://github.com/langgenius/dify/blob/main/web/app/components/workflow/constants.ts).
> 2. **Modify the Flask API to Return the File:**
>    Update your Flask API to return the processed image file in the correct format. Here's an example of how you can modify your `segment_image` function to include the file in the response:
>    ```python
>    from flask import Flask, request, jsonify, url_for
>    import os
>    
>    app = Flask(__name__)
>    
>    @app.route('/segment-image_6002', methods=['POST'])
>    def segment_image():
>        # Your existing code to process the image
>    
>        # Assuming processed_image_path is the path to the processed image
>        file_name = os.path.basename(processed_image_path)
>        file_size = os.path.getsize(processed_image_path)
>        mime_type, _ = mimetypes.guess_type(processed_image_path)
>    
>        file_info = {
>            "name": file_name,
>            "size": file_size,
>            "type": "image",
>            "extension": file_name.split('.')[-1],
>            "mime_type": mime_type,
>            "transfer_method": "url",
>            "url": url_for('static', filename=file_name, _external=True)  # Ensure the file is accessible via URL
>        }
>    
>        return jsonify({
>            "text": message,
>            "files": [file_info],
>            "json": result_data
>        }), 200
>    
>    if __name__ == "__main__":
>        app.run(host='0.0.0.0', port=6002, debug=True)
>    ```
> 3. **Ensure File Accessibility:**
>    Make sure that the processed image file is accessible via the URL you provide in the response. You might need to serve the file from a static directory or use a file hosting service.
> 
> By structuring your response this way, the Dify platform should be able to recognize and process the file in the LLM workflow.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

how could I upload local image in this example @dosu.

**Comment by zqy22** [comment]
> To upload a local image using the provided Flask API example, you can use the `upload_file` function. Here's how you can do it:
> 
> ```python
> import requests
> 
> def upload_file(file_path, user):
>     upload_url = "http://localhost:6002/segment-image_6002"
>     headers = {
>         "Authorization": "Bearer app-xxxxxxxx",  # Replace with your actual token if needed
>     }
>     
>     try:
>         print("Uploading file...")
>         with open(file_path, 'rb') as file:
>             files = {
>                 'file': (file_path, file, 'image/png')  # Adjust the MIME type according to your image format
>             }
>             data = {
>                 "user": user,
>                 "type": "IMG"  # Set the file type to IMG for images
>             }
>             
>             response = requests.post(upload_url, headers=headers, files=files, data=data)
>             if response.status_code == 200:
>                 print("File uploaded successfully")
>                 return response.json()  # Get the response data
>             else:
>                 print(f"File upload failed, status code: {response.status_code}")
>                 return None
>     except Exception as e:
>         print(f"Error occurred: {str(e)}")
>         return None
> 
> # Example usage
> file_path = 'path/to/your/image.png'  # Replace with the path to your local image
> user = 'abc-123'  # Replace with your user identifier
> response_data = upload_file(file_path, user)
> print(response_data)
> ```
> 
> Make sure to replace `'path/to/your/image.png'` with the actual path to your local image file and adjust the MIME type if your image is not a PNG. The `user` parameter should be a unique identifier for the user within your application. This setup should allow you to upload a local image to your Flask API and process it as needed.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

You seem to have misunderstood me. In my code, I need to return a local file to the output variable "files" and hand it over to the LLM to continue processing @dosu.

**Comment by zqy22** [comment]
I currently have a custom tool segment-image_6002_post, which defines some image processing functions, and what I want to achieve is to add the processed image files to the output variable of the tool "files", how should I achieve it?
Here is my OpenAPI docs:
openapi: 3.0.2
info:
  title: Image Segmentation Service
  description: A service for performing image segmentation using a Flask API.
  version: 1.0.0
servers:
  - url: http://localhost:6002
    description: Local development server

paths:
  /segment-image_6002:
    post:
      summary: Perform image segmentation
      description: Send an image URL to the service to perform image segmentation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageSegmentationRequest'
      responses:
        '200':
          description: Successful response with segmentation results and segmented image
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: The segmentation results in text format.
                  file:
                    type: string
                    format: binary
                    description: The segmented image file.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.

components:
  schemas:
    ImageSegmentationRequest:
      type: object
      properties:
        pic_need_judge:
          type: string
          format: uri
          description: The URL of the image to be segmented.
      required:
        - pic_need_judge

    SegmentationResult:
      type: object
      properties:
        category:
          type: string
          description: The category of the detected object.
        score:
          type: number
          format: float
          description: The confidence score of the detection.
        box:
          type: array
          items:
            type: integer
          description: The bounding box coordinates [x1, y1, x2, y2].
          
 Here is my tool Flask API:
 from flask import Flask, request, jsonify
import os
import requests
import mimetypes

app = Flask(name)

@app.route('/segment-image_6002', methods=['POST'])
def segment_image():
input_data = request.json
print(f"Received input_data: {input_data}")

if not input_data:
    return jsonify({"error": "Missing required parameter"}), 400

image_path = input_data.get("pic_need_judge") 
if not image_path:
    return jsonify({"error": "Missing pic_need_judge parameter"}), 400

image_path = image_path.strip()  
if not os.path.exists(image_path):
    return jsonify({"error": f"Invalid or missing image path: {image_path}"}), 400

api_url = "http://localhost:6000/api/v1/depth-estimation"  
data = {"image_path": image_path}

try:
    response = requests.post(api_url, json=data)
except requests.exceptions.RequestException as e:
    return jsonify({"error": f"Request failed: {str(e)}"}), 500

if response.status_code == 200:
    result_data = response.json()
    message = result_data.get("result_text", "No message returned")
    processed_image_path = result_data.get("image_path", "") 
    json_path = result_data.get("json_path", "")  

    if not processed_image_path or not os.path.exists(processed_image_path):
        return jsonify({"error": f"Invalid or missing processed image path: {processed_image_path}"}), 400

    from werkzeug.datastructures import Headers
    from werkzeug.wrappers import Response

    def generate_multipart_response():
        boundary = '----WebKitFormBoundary7MA4YWxkTrZu0gW'
        headers = Headers()
        headers.add('Content-Type', f'multipart/form-data; boundary={boundary}')

        yield (f'--{boundary}\r\n'
               'Content-Disposition: form-data; name="text"\r\n\r\n'
               f'{message}\r\n')

        mime_type, _ = mimetypes.guess_type(processed_image_path)
        yield (f'--{boundary}\r\n'
               f'Content-Disposition: form-data; name="file"; filename="segmented_image.{mimetypes.guess_extension(mime_type)}"\r\n'
               f'Content-Type: {mime_type}\r\n\r\n')
        with open(processed_image_path, 'rb') as img:
            while True:
                chunk = img.read(8192)
                if not chunk:
                    break
                yield chunk
        yield f'\r\n--{boundary}--\r\n'

    return Response(generate_multipart_response(), status=200)
else:
    error_message = response.text
    print(f"Error response from depth estimation service: {error_message}")
    return jsonify(
        {"error": f"Request failed with status {response.status_code}: {error_message}"}), response.status_code
if name == "main":
app.run(host='0.0.0.0', port=6002, debug=True)

Which file should I change @dosu.

**Comment by zqy22** [comment]
> ```python
> from flask import Flask, request, jsonify, url_for
> import os
> import mimetypes
> ```

The return value is still treated as text, which is the dify web tool output variable:
{
  "text": "{\"files\": [{\"extension\": \"png\", \"mime_type\": \"image/png\", \"name\": \"8_detected.png\", \"size\": 626827, \"transfer_method\": \"url\", \"type\": \"image\", \"url\": \"http://localhost:6002/static/8_detected.png\"}], \"json\": {\"result\": \"success\"}, \"text\": [\"Label: car 0.76, Score: 0.98, Depth: 72.04m\", \"Label: rail track 0.68, Score: 0.91, Depth: 58.71m\", \"Label: human 0.55, Score: 0.91, Depth: 13.03m\"]}",
  "files": [],
  "json": []
}
You can see that "files" is an empty array How to correctly return the file to "flies" in the output variable? @dosu.

**Comment by zqy22** [comment]
Here's my code:

import requests
from flask import Flask, request, jsonify, url_for
import os
import mimetypes

app = Flask(__name__)


@app.route('/segment-image_6002', methods=['POST'])
def segment_image():
    input_data = request.json
    print(f"Received input_data: {input_data}")

    if not input_data:
        return jsonify({"error": "Missing required parameter"}), 400

    image_path = input_data.get("pic_need_judge")
    if not image_path:
        return jsonify({"error": "Missing pic_need_judge parameter"}), 400

    image_path = image_path.strip()
    if not os.path.exists(image_path):
        return jsonify({"error": f"Invalid or missing image path: {image_path}"}), 400

    # 调用本地深度估计服务
    api_url = "http://localhost:6000/api/v1/depth-estimation"
    data = {"image_path": image_path}

    try:
        response = requests.post(api_url, json=data)
    except requests.exceptions.RequestException as e:
        return jsonify({"error": f"Request failed: {str(e)}"}), 500

    if response.status_code == 200:
        result_data = response.json()
        message = result_data.get("result_text", "No message returned")
        processed_image_path = result_data.get("image_path")

        if not processed_image_path or not os.path.exists(processed_image_path):
            return jsonify({"error": f"Invalid or missing processed image path: {processed_image_path}"}), 400

        # 准备文件信息
        file_name = os.path.basename(processed_image_path)
        file_size = os.path.getsize(processed_image_path)
        mime_type, _ = mimetypes.guess_type(processed_image_path)

        file_info = {
            "name": file_name,
            "size": file_size,
            "type": "image",
            "extension": file_name.split('.')[-1],
            "mime_type": mime_type,
            "transfer_method": "url",
            "url": url_for('static', filename=file_name, _external=True)  # 确保文件可以通过URL访问
        }

        # 构造返回值
        return jsonify({
            "text": message,
            "files": [file_info],
            "json": {"result": "success"}
        }), 200
    else:
        error_message = response.text
        print(f"Error response from depth estimation service: {error_message}")
        return jsonify(
            {"error": f"Request failed with status {response.status_code}: {error_message}"}), response.status_code


if __name__ == "__main__":
    app.run(host='0.0.0.0', port=6002, debug=True)

The result of the output variable is obtained after calling the API:
{
"text": "{"files": [{"extension": "png", "mime_type": "image/png", "name": "8_detected.png", "size": 626827, "transfer_method": "url", "type": "image", "url": "http://localhost:6002/static/8_detected.png"}], "json": {"result": "success"}, "text": ["Label: car 0.76, Score: 0.98, Depth: 72.04m", "Label: rail track 0.68, Score: 0.91, Depth: 58.71m", "Label: human 0.55, Score: 0.91, Depth: 13.03m"]}",
"files": [],
"json": []
}
You can see that "files" is an empty array How to correctly return the file to "flies" in the output variable? @dosu.

**Comment by vscv** [comment]
I'm encountering a problem where the agent cannot pass the user-uploaded image to the image segmentation tool (YOLO-seg). When the agent calls the segmentation API, the POST request sent by the tool doesn't contain the image data (the user-uploaded image).

<img width="453" alt="Image" src="https://github.com/user-attachments/assets/b398e4a6-c152-4155-a585-d90eab3c7bde" />

**Comment by GH-W5** [comment]
@vscv I encountered the same problem. Have you solved it?

**Comment by vscv** [comment]
> [@vscv](https://github.com/vscv) I encountered the same problem. Have you solved it?

@GH-W5 I haven't found a solution yet, but I'm still working on it.

**Comment by GH-W5** [comment]
@vscv You can try this, I can do it just fine
`{
    "openapi": "3.1.0",
    "info": {
        "title": "FastAPI",
        "version": "0.1.0"
    },
    "externalDocs": {
        "description": "**** docs",
        "url": "http://172.16.3.200:8084/docs"
    },
    "servers": [
        {
            "url": "http://172.16.3.200:8084",
            "description": "agent"
        }
    ],
    "tags": [
        {
            "name": "****,
            "description": "*******"
        }
    ],
    "paths": {
        "/extract_road/": {
            "post": {
                "summary": "****",
                "description": "*******",
                "operationId": "extract_road_extract_road__post",
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data; boundary=----WebKitFormBoundarydzemBAPhdeDfTCfR": {
                            "schema": {
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary",
                                        "title": "File"
                                    }
                                },
                                "type": "object",
                                "required": [
                                    "file"
                                ]
                            },
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Response"
                    }
                }
            }
        }
    }
}`

![Image](https://github.com/user-attachments/assets/d990dae4-66c9-45a6-a84f-4375a629a82a)

**Comment by vscv** [comment]
@GH-W5 Thanks. I appreciate you providing this method. Unfortunately, I'm having trouble with it. When I try to use it, the agent seems to be unable to find the API tool. Is there something I might be missing?

**Comment by GH-W5** [comment]
> [@GH-W5](https://github.com/GH-W5) Thanks. I appreciate you providing this method. Unfortunately, I'm having trouble with it. When I try to use it, the agent seems to be unable to find the API tool.
> 
> Can you use your extract_road API within the agent?

No

**Comment by MDDTGitHub** [comment]
> 你可以试试这个，我也能做得很好
> 
> ```
> {
>     "openapi": "3.1.0",
>     "info": {
>         "title": "FastAPI",
>         "version": "0.1.0"
>     },
>     "externalDocs": {
>         "description": "**** docs",
>         "url": "http://172.16.3.200:8084/docs"
>     },
>     "servers": [
>         {
>             "url": "http://172.16.3.200:8084",
>             "description": "agent"
>         }
>     ],
>     "tags": [
>         {
>             "name": "****,
>             "description": "*******"
>         }
>     ],
>     "paths": {
>         "/extract_road/": {
>             "post": {
>                 "summary": "****",
>                 "description": "*******",
>                 "operationId": "extract_road_extract_road__post",
>                 "requestBody": {
>                     "required": true,
>                     "content": {
>                         "multipart/form-data; boundary=----WebKitFormBoundarydzemBAPhdeDfTCfR": {
>                             "schema": {
>                                 "properties": {
>                                     "file": {
>                                         "type": "string",
>                                         "format": "binary",
>                                         "title": "File"
>                                     }
>                                 },
>                                 "type": "object",
>                                 "required": [
>                                     "file"
>                                 ]
>                             },
>                         }
>                     }
>                 },
>                 "responses": {
>                     "200": {
>                         "description": "Successful Response"
>                     }
>                 }
>             }
>         }
>     }
> }
> ```
> 
> ![Image](https://github.com/user-attachments/assets/d990dae4-66c9-45a6-a84f-4375a629a82a)

Bro， this is the input parameter setting. What we need is that the return value can identify the file information

**Comment by GH-W5** [comment]
@MDDTGitHub I'm sorry I don't quite understand what you mean, please tell us more about your needs, I hope I can help you.

**Comment by GH-W5** [comment]
@MDDTGitHub You mean you want to customize the tool to return specific file information, right? This is achievable.

**Comment by MDDTGitHub** [comment]
> [@MDDTGitHub](https://github.com/MDDTGitHub) You mean you want to customize the tool to return specific file information, right? This is achievable.

Yes, brother, I tried it, and the return value files in Dify is always empty. Can you tell me how to solve this? thank you

**Comment by GH-W5** [comment]
@MDDTGitHub 可以，加qq 1961879865
