### ISSUE TITLE
About api_key in AppApi

### ISSUE THREAD

**Issue by cubonguilty** [langgenius/dify#11256]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

To retrieve basic app information from AppApi, an ADMIN_API_KEY is required, but it cannot be accessed using the api_key from ChatApi. I would like to know if there are any plans to modify the authentication system or add a new endpoint to allow retrieving basic information using the api_key, and what changes would be necessary to implement this.

### 2. Additional context or comments

No issue

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
`ADMIN_API_KEY ` is internal use only, we do not have a plan for exposing it as public API. For questions, please use discussion instead.
