### ISSUE TITLE
本地部署卡在loading界面

### ISSUE THREAD

**Issue by vary** [langgenius/dify#1126]
按照这个流程部署：https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/local-source-code
所有的都没有报错，控制台一切都正常，启动后页面一直卡在loading转圈

**Comment by lingfengchencn** [comment]
看下你的配置和截图

**Comment by vary** [comment]
配置都是默认的没有修改
<img width="559" alt="image" src="https://github.com/langgenius/dify/assets/3312460/6a79c915-28bb-470f-85c8-7a56a733ffe9">
<img width="560" alt="image" src="https://github.com/langgenius/dify/assets/3312460/8db906e7-4101-4639-adde-fe86f1106c97">
<img width="561" alt="image" src="https://github.com/langgenius/dify/assets/3312460/06e89c02-431f-4398-9680-1154f5187385">

**Comment by leslie2046** [comment]
我也遇到了这个问题，我是nodejs 16，不知道是不是这个原因，但是我是 centos7没办法升级到nodejs18，因为glibc不支持
node -v
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)

**Comment by vary** [comment]
@crazywoola  
<img width="795" alt="image" src="https://github.com/langgenius/dify/assets/3312460/0cbf4a10-34e8-4a76-8c6a-bcbbdfa71ad9">

**Comment by vary** [comment]
@crazywoola 
<img width="1497" alt="image" src="https://github.com/langgenius/dify/assets/3312460/c3bc270d-c730-498b-9126-a5cc7f1743a0">

**Comment by leslie2046** [comment]
![图片](https://github.com/langgenius/dify/assets/10449699/e46978e3-866f-4e15-ba1d-b094eda9afd2)
@crazywoola

**Comment by vary** [comment]
> > @crazywoola <img alt="image" width="1497" src="https://user-images.githubusercontent.com/3312460/266892052-c3bc270d-c730-498b-9126-a5cc7f1743a0.png">
> 
> 看看pending 的原因，还有详细的报错信息。光看这图我没法判断是啥错误。主要看xhr，那几个接口没有请求到的原因。 不知道有没有看过这个[视频](https://www.xiaohongshu.com/explore/64d8e177000000001700cc93)

视频看过，除了访问http://127.0.0.1:5001/一直转圈，没有像视频里出现404，其他的没有任何报错信息

**Comment by leslie2046** [comment]
![图片](https://github.com/langgenius/dify/assets/10449699/3166f1b8-b92c-49b6-85ab-2a2c4778483a)
flask run --host 0.0.0.0 --port=5001 --debug
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.0.100:5001
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 932-135-047
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/apps?page=1 HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/workspaces/current HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/account/profile HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/apps?page=1 HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/workspaces/current HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/account/profile HTTP/1.1" 200 -
ERROR:app:Exception on /console/api/apps [GET]
Traceback (most recent call last):
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "dify_setups" does not exist
LINE 2: FROM dify_setups 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 80, in decorated
    if not get_setup_status():
  File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 90, in get_setup_status
    return DifySetup.query.first()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dify_setups" does not exist
LINE 2: FROM dify_setups 
             ^

[SQL: SELECT dify_setups.version AS dify_setups_version, dify_setups.setup_at AS dify_setups_setup_at 
FROM dify_setups 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
ERROR:app:Exception on /console/api/workspaces/current [GET]
Traceback (most recent call last):
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "dify_setups" does not exist
LINE 2: FROM dify_setups 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 80, in decorated
    if not get_setup_status():
  File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 90, in get_setup_status
    return DifySetup.query.first()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dify_setups" does not exist
LINE 2: FROM dify_setups 
             ^

[SQL: SELECT dify_setups.version AS dify_setups_version, dify_setups.setup_at AS dify_setups_setup_at 
FROM dify_setups 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
ERROR:app:Exception on /console/api/account/profile [GET]
Traceback (most recent call last):
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "dify_setups" does not exist
LINE 2: FROM dify_setups 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 80, in decorated
    if not get_setup_status():
  File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 90, in get_setup_status
    return DifySetup.query.first()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dify_setups" does not exist
LINE 2: FROM dify_setups 
             ^

[SQL: SELECT dify_setups.version AS dify_setups_version, dify_setups.setup_at AS dify_setups_setup_at 
FROM dify_setups 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "GET /console/api/apps?page=1 HTTP/1.1" 500 -
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "GET /console/api/workspaces/current HTTP/1.1" 500 -
INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "GET /console/api/account/profile HTTP/1.1" 500 -

**Comment by vary** [comment]
> > > @crazywoola <img alt="image" width="1497" src="https://user-images.githubusercontent.com/3312460/266892052-c3bc270d-c730-498b-9126-a5cc7f1743a0.png">
> > 
> > 
> > 看看pending 的原因，还有详细的报错信息。光看这图我没法判断是啥错误。主要看xhr，那几个接口没有请求到的原因。 不知道有没有看过这个[视频](https://www.xiaohongshu.com/explore/64d8e177000000001700cc93)
> 
> 视频看过，除了访问[http://127.0.0.1:5001/一直转圈，没有像视频里出现404，其他的没有任何报错信息](http://127.0.0.1:5001/%E4%B8%80%E7%9B%B4%E8%BD%AC%E5%9C%88%EF%BC%8C%E6%B2%A1%E6%9C%89%E5%83%8F%E8%A7%86%E9%A2%91%E9%87%8C%E5%87%BA%E7%8E%B0404%EF%BC%8C%E5%85%B6%E4%BB%96%E7%9A%84%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF)

我的问题重启电脑解决了，大意了，看到有另外一个小伙伴有报错的信息，我就先不关闭了 @crazywoola

**Comment by leslie2046** [comment]
@vary  是不是必须要node 18以上版本

**Comment by vary** [comment]
> @vary 是不是必须要node 18以上版本

我的是20.5

**Comment by leslie2046** [comment]
好吧，我可能是nodejs版本问题，先关了吧
@vary

**Comment by lilinrestart** [comment]
> > > > @crazywoola <img alt="图像" width="1497" src="https://user-images.githubusercontent.com/3312460/266892052-c3bc270d-c730-498b-9126-a5cc7f1743a0.png">
> > > 
> > > 
> > > 看看待处理的原因，还有详细的报错信息。光看这个图我没法判断是啥错误。主要看xhr，那几个接口没有请求到的原因。不知道有没有看过这个[视频](https://www.xiaohongshu.com/explore/64d8e177000000001700cc93)
> > 
> > 
> > 视频看到，除了访问[http://127.0.0.1:5001/一直转圈，没有像视频里出现404，其他的没有任何报错信息](http://127.0.0.1:5001/%E4%B8%80%E7%9B%B4%E8%BD%AC%E5%9C%88%EF%BC%8C%E6%B2%A1%E6%9C%89%E5%83%8F%E8%A7%86%E9%A2%91%E9%87%8C%E5%87%BA%E7%8E%B0404%EF%BC%8C%E5%85%B6%E4%BB%96%E7%9A%84%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF)
> 
> 我的问题重启电脑解决了，大意了，看到另外一个小伙伴报错的信息，我就先不关机了@crazywoola

所以最后到底是什么问题导致的呢，我也是一直加载不出来

**Comment by leslie2046** [comment]
flash db upgrade要先执行一下

**Comment by thinkinds** [comment]
> [@crazywoola](https://github.com/crazywoola) 麻烦帮忙看下，这个是本地源码启动，一直在loading的问题。截图是浏览器里的控制台截图，这个打印是API的打印 ![图片](https://github.com/langgenius/dify/assets/10449699/3166f1b8-b92c-49b6-85ab-2a2c4778483a) flask run --host 0.0.0.0 --port=5001 --debug
> 
> * Debug mode: on
>   INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
> * Running on all addresses (0.0.0.0)
> * Running on http://127.0.0.1:5001
> * Running on http://192.168.0.100:5001
>   INFO:werkzeug:Press CTRL+C to quit
>   INFO:werkzeug: * Restarting with stat
>   WARNING:werkzeug: * Debugger is active!
>   INFO:werkzeug: * Debugger PIN: 932-135-047
>   INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/apps?page=1 HTTP/1.1" 200 -
>   INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/workspaces/current HTTP/1.1" 200 -
>   INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/account/profile HTTP/1.1" 200 -
>   INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/apps?page=1 HTTP/1.1" 200 -
>   INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/workspaces/current HTTP/1.1" 200 -
>   INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "OPTIONS /console/api/account/profile HTTP/1.1" 200 -
>   ERROR:app:Exception on /console/api/apps [GET]
>   Traceback (most recent call last):
>   File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
>   self.dialect.do_execute(
>   File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
>   cursor.execute(statement, parameters)
>   psycopg2.errors.UndefinedTable: relation "dify_setups" does not exist
>   LINE 2: FROM dify_setups
>   ^
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request rv = self.dispatch_request() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/**init**.py", line 467, in wrapper resp = resource(*args, **kwargs) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 109, in view return current_app.ensure_sync(self.dispatch_request)(**kwargs) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/**init**.py", line 582, in dispatch_request resp = meth(*args, **kwargs) File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 80, in decorated if not get_setup_status(): File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 90, in get_setup_status return DifySetup.query.first() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first return self.limit(1)._iter().first() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter result = self.session.execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute result = conn._execute_20(statement, params or {}, execution_options) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20 return meth(self, args_10style, kwargs_10style, execution_options) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection return connection._execute_clauseelement( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement ret = self._execute_context( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context self._handle_dbapi_exception( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception util.raise_( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_ raise exception File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context self.dialect.do_execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dify_setups" does not exist LINE 2: FROM dify_setups ^
> 
> [SQL: SELECT dify_setups.version AS dify_setups_version, dify_setups.setup_at AS dify_setups_setup_at FROM dify_setups LIMIT %(param_1)s] [parameters: {'param_1': 1}] (Background on this error at: https://sqlalche.me/e/14/f405) ERROR:app:Exception on /console/api/workspaces/current [GET] Traceback (most recent call last): File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context self.dialect.do_execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cursor.execute(statement, parameters) psycopg2.errors.UndefinedTable: relation "dify_setups" does not exist LINE 2: FROM dify_setups ^
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request rv = self.dispatch_request() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/**init**.py", line 467, in wrapper resp = resource(*args, **kwargs) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 109, in view return current_app.ensure_sync(self.dispatch_request)(**kwargs) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/**init**.py", line 582, in dispatch_request resp = meth(*args, **kwargs) File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 80, in decorated if not get_setup_status(): File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 90, in get_setup_status return DifySetup.query.first() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first return self.limit(1)._iter().first() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter result = self.session.execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute result = conn._execute_20(statement, params or {}, execution_options) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20 return meth(self, args_10style, kwargs_10style, execution_options) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection return connection._execute_clauseelement( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement ret = self._execute_context( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context self._handle_dbapi_exception( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception util.raise_( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_ raise exception File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context self.dialect.do_execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dify_setups" does not exist LINE 2: FROM dify_setups ^
> 
> [SQL: SELECT dify_setups.version AS dify_setups_version, dify_setups.setup_at AS dify_setups_setup_at FROM dify_setups LIMIT %(param_1)s] [parameters: {'param_1': 1}] (Background on this error at: https://sqlalche.me/e/14/f405) ERROR:app:Exception on /console/api/account/profile [GET] Traceback (most recent call last): File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context self.dialect.do_execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cursor.execute(statement, parameters) psycopg2.errors.UndefinedTable: relation "dify_setups" does not exist LINE 2: FROM dify_setups ^
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request rv = self.dispatch_request() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/**init**.py", line 467, in wrapper resp = resource(*args, **kwargs) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 109, in view return current_app.ensure_sync(self.dispatch_request)(**kwargs) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/**init**.py", line 582, in dispatch_request resp = meth(*args, **kwargs) File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 80, in decorated if not get_setup_status(): File "/home/leslie/chatgpt/dify/api/controllers/console/setup.py", line 90, in get_setup_status return DifySetup.query.first() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first return self.limit(1)._iter().first() File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter result = self.session.execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute result = conn._execute_20(statement, params or {}, execution_options) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20 return meth(self, args_10style, kwargs_10style, execution_options) File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection return connection._execute_clauseelement( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement ret = self._execute_context( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context self._handle_dbapi_exception( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception util.raise_( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_ raise exception File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context self.dialect.do_execute( File "/home/leslie/anaconda3/envs/dify/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dify_setups" does not exist LINE 2: FROM dify_setups ^
> 
> [SQL: SELECT dify_setups.version AS dify_setups_version, dify_setups.setup_at AS dify_setups_setup_at FROM dify_setups LIMIT %(param_1)s] [parameters: {'param_1': 1}] (Background on this error at: https://sqlalche.me/e/14/f405) INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "GET /console/api/apps?page=1 HTTP/1.1" 500 - INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "GET /console/api/workspaces/current HTTP/1.1" 500 - INFO:werkzeug:192.168.0.162 - - [13/Sep/2023 11:28:18] "GET /console/api/account/profile HTTP/1.1" 500 -

为何我新拉的代码，用docker部署也出现同样的问题？

**Comment by zzc-ccccc** [comment]
重启解决90%的问题
