### ISSUE TITLE
the text-to-audio api not working when i use postman

### ISSUE THREAD

**Issue by ssrqm** [langgenius/dify#11263]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Send post to `/v1/text-to-audio` used postman , and zhe json data is：
```
{
    "text":"哈哈哈",
    "user": "abc-123",
    "streaming": false
}
```

then i got zhe response:
```
{
    "code": "invalid_param",
    "message": "TTS is not enabled",
    "status": 400
}
```

like that sc:
![image](https://github.com/user-attachments/assets/cdf4413b-ca9e-4453-9d3f-f20f16c5f842)

### ✔️ Expected Behavior

got a mp3 audio

### ❌ Actual Behavior

response error

**Comment by crazywoola** [comment]
Please check the settings here.
<img width="474" alt="image" src="https://github.com/user-attachments/assets/aec8e7dc-79d9-4408-aaf5-3177c047439d">

**Comment by sxk000** [comment]
config.json这个配置文件在哪里？where is the config.json?
