### ISSUE TITLE
All models with the same name will be disabled, when you add the same model name

### ISSUE THREAD

**Issue by dadastory** [langgenius/dify#11277]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I add models with the same name through the model provider configuration bar, such as the same (gpt-4o) model (another proxy provider), then when I disabled gpt4o model, the other model with the same model name gpt-4o will also be disabled, which I think is very unreasonable, regardless of whether I set the enterprise ID

### ✔️ Expected Behavior

When I disable a model, another model with the same name but a different configuration alias should not also be disabled, i think model configuration should support changing model's aliases rather than changing model's real name. i think add different model provider is more useful comparing with the loadbalance service for single ueser

### ❌ Actual Behavior

When I disable a gpt-4o model, all gpt-4o models with the same name will be disabled

**Comment by dadastory** [comment]
> The issue you're experiencing is related to how Dify handles models with the same name. When you disable a model, all models with the same name are also disabled, regardless of their configuration or provider. This behavior is due to the current logic in Dify's model provider configuration, which does not differentiate between models with the same name but different configurations or providers.
> 
> To address this, Dify would need a mechanism to assign unique identifiers or aliases to models, allowing them to be managed independently even if they share the same name. Unfortunately, there is no existing feature in Dify that allows for the assignment of unique identifiers or aliases to models to differentiate them beyond their names [[1]](https://github.com/langgenius/dify/blob/main/api/core/entities/provider_configuration.py).
> 
> This limitation means that any model with the same name will be affected by actions such as disabling, unless the system is updated to support more granular model identification and management.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

i absolutely agree with your explanation，i think maybe alias should be used to solve this question

**Comment by crazywoola** [comment]
Please use the `feature request` template to open it instead,  not bug report.
