### ISSUE TITLE
I think model configuration should support aliases

### ISSUE THREAD

**Issue by dadastory** [langgenius/dify#11273]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I add models with the same name through the model vendor, such as the same (gpt-4o) model, then when I turn off one model, the other model will also be disabled, which I think is very unreasonable, regardless of whether I set the enterprise ID

### ✔️ Expected Behavior

When I disable a model, another model with the same name but a different configuration alias should not also be disabled

### ❌ Actual Behavior

When I disable a gpt-4o model, all gpt-4o models with the same name will be disabled

**Comment by crazywoola** [comment]
Please use the right template to open a feature request.
