### ISSUE TITLE
Azure Connection Error

### ISSUE THREAD

**Issue by AmiyaLI** [langgenius/dify#11287]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After I set the deploy name,endpoint,api key,api version and model version, I get the connection error, how can I fix it?
![20241203-142206](https://github.com/user-attachments/assets/d735fb11-7b53-4a0b-876a-8663a5169aa7)

**Comment by crazywoola** [comment]
Please try to upgrade to a newer version. We had several fixes related to this provider.
