### ISSUE TITLE
Got "404 not found" when deploying with Docker Compose

### ISSUE THREAD

**Issue by zelevent** [langgenius/dify#11282]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Deploy dify step by step in Docker Compose mode following the doc, finally get "404 not found" when access to "http://you_server_ip/install"

**Comment by crazywoola** [comment]
For questions please read the docs first, you need to change the environment variables to make it work, those are all written in the docs.dify.ai. Use a write a template to open an issue, for questions, please use discussion instead.
