### ISSUE TITLE
The knowledge base query interface only returns the initial user's knowledge base list.

### ISSUE THREAD

**Issue by lackoxy** [langgenius/dify#11281]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. The current user creates an API key.
2. Use the API key to call the interface for querying the knowledge base list.

### ✔️ Expected Behavior

Users should only be able to view the list of knowledge bases they are authorized to access when calling the interface.
For example，these are what i can see in database list.
![image](https://github.com/user-attachments/assets/ebcdd623-d7c9-45fb-9861-c07937bd1d6f)

### ❌ Actual Behavior

Current users are seeing the initial user's accessible database list, and the databases created by the current user are not being returned.
The result returned from the API does not include "autotape测试用" Because this is created by the current user instead of the initial user.

**Comment by crazywoola** [comment]
Please upgrade to latest version.

**Comment by lackoxy** [comment]
> Please upgrade to latest version.

I upgraded the Dify version to 0.13.0 today, but I still encountered this bug after re-executing the steps.
I regenerated a new API key to call the interface.
