### ISSUE TITLE
'C:\\Program': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by fanliunian** [langgenius/dify#11280]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Open the project with pycharm
2. run app is normal
3. debug app error reporting
4. 
![image](https://github.com/user-attachments/assets/7942f1ba-731d-49e4-a3f9-2cb62e0c336e)

**Comment by crazywoola** [comment]
If you are using source code, please make sure you understand programming basics before getting started. We do not provide these support unless you get a business license.

**Comment by fanliunian** [comment]
Problems caused by the installation path of pycharm containing spaces
