### ISSUE TITLE
vllm support

### ISSUE THREAD

**Issue by OKC13** [langgenius/dify#11296]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have successfully deployed and started the service using vllm, and the API calls work fine. However, when I try to add it in dify, I get the following error message: 'base model was not found.
![image](https://github.com/user-attachments/assets/65c8f2fc-91d0-442a-8027-5a227d634f02)

**Comment by OKC13** [comment]
did not solved

**Comment by wsbao** [comment]
Consider **OpenAI-API-compatible** instead of Open AI.

Your model name is not in OpenAI's model list. Your can either restart vllm service with a spoofing OpenAI model name (e.g., gpt-4o) or use **OpenAI-API-compatible** interface.

**Comment by crazywoola** [comment]
This provider is intent for the official OpenAI keys.
