### ISSUE TITLE
dify is not supported wenxin function call?

### ISSUE THREAD

**Issue by wcccode** [langgenius/dify#11292]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/d2c78afb-9694-4e3d-9a75-eaf259ad8a03)

![image](https://github.com/user-attachments/assets/c2036c16-bfcf-455c-a494-6423dfd00722)

### ✔️ Expected Behavior

The official documentation states that function calling is supported.

![image](https://github.com/user-attachments/assets/347afce3-926f-40be-a0f0-b64889f5bb10)

**Comment by wcccode** [comment]
您好，您的来信我已收到，谢谢！！！

**Comment by crazywoola** [comment]
No, we do not support FC in wenxin, if you are interested, you can contribute to this feature.
