### ISSUE TITLE
Old Conversations in Dify Agent Still Use Removed Tools

### ISSUE THREAD

**Issue by MitraSafarinejad** [langgenius/dify#11291]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I created an agent in Dify and initially added Tavily Search as a tool. Later, I removed Tavily from my agent, but I noticed that ongoing conversations still rely on Tavily for searches.

Additionally, when I replace Tavily with Serper Search, old conversations continue using Tavily instead of the new tool.

1- Create an agent in Dify with Tavily Search as a tool.
2- Start a conversation using the Tavily tool.
3- Remove Tavily and add Serper Search as a replacement.
4- Continue the old conversation.
Result: The old conversation still uses Tavily instead of Serper Search.

### ✔️ Expected Behavior

Once I update or replace tools in my agent, all ongoing and new conversations should use the updated tools.

### ❌ Actual Behavior

conversations continue using Tavily instead of the new tool.

**Comment by crazywoola** [comment]
This is a by design behavior.

**Comment by MitraSafarinejad** [comment]
Thank you for the clarification @crazywoola. Just to confirm, does this mean the only way to replace tools in active use is to start a new conversation?
