### ISSUE TITLE
The Agent context is bound to the knowledge base, but no retrieval is performed after sending the question.

### ISSUE THREAD

**Issue by yunfeng13** [langgenius/dify#11293]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/a63d1c9c-346f-49a7-8cab-ddeba9e0764e)
t the beginning, the prompt word was not written like this, and I never did a knowledge base search. It was not until I added the requirements to the prompt word that I started to search the contextual knowledge base. Why is this? Is there an official explanation? Is there a better one? Writing method, I hope that every question will be contextualized for knowledge retrieval

### ✔️ Expected Behavior

t the beginning, the prompt word was not written like this, and I never did a knowledge base search. It was not until I added the requirements to the prompt word that I started to search the contextual knowledge base. Why is this? Is there an official explanation? Is there a better one? Writing method, I hope that every question will be contextualized for knowledge retrieval

### ❌ Actual Behavior

If the knowledge retrieval is not written in the Agent prompt word, the retrieval will not be performed.

**Comment by crazywoola** [comment]
See https://docs.dify.ai/guides/application-orchestrate/agent for more details.
Agent will do actions based on instructions, the prompt is a instruction list, so if you do want the agent to search the knowledge base, tell it to do it.

And you can not use variable to store things in agent it, this should leave to the end user to fill it.

If you don't know how to write a proper prompt, try the button 'AI generate' on top of the  prompt input area.
