### ISSUE TITLE
OTP Codes Not Sent in Cloud

### ISSUE THREAD

**Issue by nfaganelly** [langgenius/dify#11309]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When attempting to log in to the Dify.ai platform using the passwordless login method, the OTP (One-Time Password) codes are not being sent to the registered email address. This issue prevents users from accessing their accounts, causing inconvenience and making the platform unusable.

Go to the Dify.ai login page.
Enter the registered email address.
Click the button to receive the OTP code.
Check the email inbox and spam/junk folder.

### ✔️ Expected Behavior

An email containing the OTP code should be received to complete the login process.

### ❌ Actual Behavior

No email with the OTP code is received, making it impossible to log in to the platform.

**Comment by nfaganelly** [comment]
none of these steps are valid for cloud service

**Comment by nfaganelly** [comment]
![image](https://github.com/user-attachments/assets/6755b8c6-13e7-4f37-bd93-ac11292bd9b0)

Is there anything I can do to resolve this soon? This is a serious issue.

**Comment by crazywoola** [comment]
Please send an email to support@dify.ai to report this incident.

**Comment by crazywoola** [comment]
This should been resolved now :)

**Comment by flly-cliente-marketshop** [comment]
Thanks!
