### ISSUE TITLE
Start suggesting the next step of the problem, but do not display the suggested problem

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#11306]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I have enabled the "Next Question Suggestion" button in the feature settings, but when I tried to ask questions on the preview page, I did not see the attempt to ask, as shown in the picture
<img width="248" alt="cd55f8be9343a75a29033ade54e4b4d" src="https://github.com/user-attachments/assets/86dfb32b-84a1-464f-85e6-b58c05edc8bb">
<img width="253" alt="df423c3a964dd1b3a505d2469916e43" src="https://github.com/user-attachments/assets/5112bffa-40da-43cc-ad96-05a0c6a71da5">

**Comment by crazywoola** [comment]
Duplicated

**Comment by miver02** [comment]
控制生成建议的源码是哪些文件
