### ISSUE TITLE
downloaded image cannot be opened

### ISSUE THREAD

**Issue by AkisAya** [langgenius/dify#11310]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

upload a image in a conversation and download it
![图片下载](https://github.com/user-attachments/assets/3df7be56-8121-4bcb-a61a-938bff6b46c6)
and the download one cannot be open

### ✔️ Expected Behavior

downloaded image can be opened

### ❌ Actual Behavior

downloaded image can not be opened

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/11322
