### ISSUE TITLE
Failed to receive email after adding member's email address.

### ISSUE THREAD

**Issue by jingzl** [langgenius/dify#11315]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When adding a member in the settings and entering the email address, the email is not received.

.env config:

```
MAIL_TYPE=resend

MAIL_DEFAULT_SEND_FROM=no-reply@dify.ai
RESEND_API_KEY=re_C25VbtUK_xxxxxxxxxxxxxxxxxxx

SMTP_SERVER=smtp.qq.com
SMTP_PORT=465
SMTP_USERNAME=xxxx@qq.com
SMTP_PASSWORD=xxxxxxxxxxxxxxx
SMTP_USE_TLS=true
SMTP_OPPORTUNISTIC_TLS=false
```
**Regardless of choosing to resend or using SMTP, the email is not received.**

### ✔️ Expected Behavior

the email is received.

### ❌ Actual Behavior

Regardless of choosing to resend or using SMTP, the email is not received.

**Comment by crazywoola** [comment]
```
MAIL_DEFAULT_SEND_FROM=no-reply@dify.ai
```

You need to change this to your own email sender. Eg. If you choose the SMTP, set it to `xxxx@qq.com`.

**Comment by jingzl** [comment]
添加这个后，可以了。
MAIL_DEFAULT_SEND_FROM=xxxxx@163.com
