### ISSUE TITLE
better error handling for professional flows

### ISSUE THREAD

**Issue by lucaseatp** [langgenius/dify#11314]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

dify is a great tool, but it lacks one crucial thing for production: better error handling.

Straightforward things make a huge difference, like, when anthropic gives you a 529 error (overloaded), wait 15 seconds and try again, maybe you can do it 3 or 5 times.

if it doesn't work, we should have the option to choose another AI model to handle this data.

really simple things, but they make a huge difference to avoid errors in production flows.

and that's just for llm nodes... error handling should be a feature anytime soon

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by acauaferreira** [comment]
yes, very important!!
