### ISSUE TITLE
custom icon in chat

### ISSUE THREAD

**Issue by JanKeesSchakel** [langgenius/dify#11313]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I'm creating a chat-apps with a personality and would like each to have their own icon. That is already possible at the header of the app, but when chatting the icon of a robot is shown. Would be great if that could be customised!

<img width="246" alt="Screenshot 2024-12-03 at 19 05 18" src="https://github.com/user-attachments/assets/ad4939a9-8b8f-41bc-928a-9a19e349a327">

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We do have this feature as well.

Monitoring -> Settings -> Change the icon, you can turn the switch to replace the bot logo.
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/6da1b2b1-d19c-4224-b7b3-203f075794b2">

**Comment by JanKeesSchakel** [comment]
Thx for this explanation. I tried that option, and it works for the header of the chat. 
However, **the icon in front of each reply in the chat**  still contains the robot icon, as shown above.
