### ISSUE TITLE
A new account created in localhost/install and it overwrote the old account - can I undo?

### ISSUE THREAD

**Issue by d2clab** [langgenius/dify#11326]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I tried to upgrade to the latest version, and after restarting Docker, I came to the localhost/install interface. 
I entered my original username and password, and found that this operation would overwrite my original account. 

What should I do to roll back? Thanks!

### ✔️ Expected Behavior

To login into my account instead of creating a new account.

### ❌ Actual Behavior

this operation would overwrite my original account

**Comment by crazywoola** [comment]
The upgrade progress won't reset the whole application nor remove the application data, if you would like to restore the account. please run the command `flask reset-email`.
