### ISSUE TITLE
How to deploy dify-web on sub-domain like http://xxx/dify

### ISSUE THREAD

**Issue by SupremeMonster** [langgenius/dify#11335]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I want to deploy dify-web on sub-domain like http://xxx/dify,
step 1:
add basePath:'/dify' in next.config.js and build frontend again
step 2:
run docker-compose down & docker-compose up -d;
step 3:
modify nginx configuration

But the end result was a lot of 404s, and I would like to know how I can achieve my goal.

**Comment by SupremeMonster** [comment]
Some static resources have 'dify'  and another  don't have
![微信图片_20241204165337](https://github.com/user-attachments/assets/0492c800-2682-46df-8508-f63937afd3f6)

**Comment by SupremeMonster** [comment]
@dosu

**Comment by SupremeMonster** [comment]
next.config.js:
const { codeInspectorPlugin } = require("code-inspector-plugin");
const withMDX = require("@next/mdx")({
  extension: /\.mdx?$/,
  options: {
    // If you use remark-gfm, you'll need to use next.config.mjs
    // as the package is ESM only
    // https://github.com/remarkjs/remark-gfm#install
    remarkPlugins: [],
    rehypePlugins: [],
    // If you use `MDXProvider`, uncomment the following line.
    // providerImportSource: "@mdx-js/react",
  },

});

/** @type {import('next').NextConfig} */
const nextConfig = {
  basePath: '/dify',
  webpack: (config, { dev, isServer }) => {
    config.plugins.push(codeInspectorPlugin({ bundler: "webpack" }));
    return config;
  },

  productionBrowserSourceMaps: false, // enable browser source map generation during the production build
  // Configure pageExtensions to include md and mdx
  pageExtensions: ["ts", "tsx", "js", "jsx", "md", "mdx"],
  experimental: {},
  // fix all before production. Now it slow the develop speed.
  eslint: {
    // Warning: This allows production builds to successfully complete even if
    // your project has ESLint errors.
    ignoreDuringBuilds: true,
    dirs: [
      "app",
      "bin",
      "config",
      "context",
      "hooks",
      "i18n",
      "models",
      "service",
      "test",
      "types",
      "utils",
    ],
  },
  typescript: {
    // https://nextjs.org/docs/api-reference/next.config.js/ignoring-typescript-errors
    ignoreBuildErrors: true,
  },
  reactStrictMode: true,
  async redirects() {
    return [
      {
        source: "/",
        destination: "/apps",
        permanent: false,
      },
    ];
  },
  output: "standalone",
};

module.exports = withMDX(nextConfig);



nginx:
server {
    listen 80;
    server_name _;

    location /dify/console/api {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/api {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/v1 {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/files {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/ {
      proxy_pass http://web:3000/;
      include proxy.conf;
    }

    # placeholder for acme challenge location


    # placeholder for https config defined in https.conf.template

}
@dosu

**Comment by SupremeMonster** [comment]
nginx:

```
server {
    listen 80;
    server_name _;

    location /dify/console/api {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/api {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/v1 {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/files {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

    location /dify/ {
      proxy_pass http://web:3000/;
      include proxy.conf;
    }

    # placeholder for acme challenge location


    # placeholder for https config defined in https.conf.template

}
```

next.config.js
```
const { codeInspectorPlugin } = require("code-inspector-plugin");
const withMDX = require("@next/mdx")({
  extension: /\.mdx?$/,
  options: {
    // If you use remark-gfm, you'll need to use next.config.mjs
    // as the package is ESM only
    // https://github.com/remarkjs/remark-gfm#install
    remarkPlugins: [],
    rehypePlugins: [],
    // If you use `MDXProvider`, uncomment the following line.
    // providerImportSource: "@mdx-js/react",
  },

});

/** @type {import('next').NextConfig} */
const nextConfig = {
  basePath: '/dify',
  webpack: (config, { dev, isServer }) => {
    config.plugins.push(codeInspectorPlugin({ bundler: "webpack" }));
    return config;
  },

  productionBrowserSourceMaps: false, // enable browser source map generation during the production build
  // Configure pageExtensions to include md and mdx
  pageExtensions: ["ts", "tsx", "js", "jsx", "md", "mdx"],
  experimental: {},
  // fix all before production. Now it slow the develop speed.
  eslint: {
    // Warning: This allows production builds to successfully complete even if
    // your project has ESLint errors.
    ignoreDuringBuilds: true,
    dirs: [
      "app",
      "bin",
      "config",
      "context",
      "hooks",
      "i18n",
      "models",
      "service",
      "test",
      "types",
      "utils",
    ],
  },
  typescript: {
    // https://nextjs.org/docs/api-reference/next.config.js/ignoring-typescript-errors
    ignoreBuildErrors: true,
  },
  reactStrictMode: true,
  async redirects() {
    return [
      {
        source: "/",
        destination: "/apps",
        permanent: false,
      },
    ];
  },
  output: "standalone",
};

module.exports = withMDX(nextConfig);


@dosu
```

**Comment by SupremeMonster** [comment]
@dosu

**Comment by Davidwhw** [comment]
I had the same problem as you. How did you solve it?
Currently I have modified the `docker/nginx/conf.d/default.conf.template` and `web/next.config.js` program files. Then restart all containers.
Finally got a 404 error when visiting `http://xxx/dify/install`.
Looking forward to your reply.

**Comment by GitHub4LP** [comment]
use server workers for Forward Proxy, nginx for Reverse Proxy.
May solve it

**Comment by gq957534377** [comment]
https://github.com/langgenius/dify/issues/15591

**Comment by gq957534377** [comment]
https://github.com/langgenius/dify/pull/18658/files
