### ISSUE TITLE
Knowledge base node can not search when selecting knowledge base, it is too troublesome, can only slide down.

### ISSUE THREAD

**Issue by w969351379** [langgenius/dify#11345]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Knowledge base node selection of knowledge base can not search, too troublesome, can only slide down, the current project has more than 200 knowledge bases, can not search and choose to find the required knowledge base for a long time

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/11343, please do not spam issue list

**Comment by laipz8200** [comment]
I don't think it's necessary to search in the knowledgebase, but if you need to, you can write a detailed description for your scenario and submit a 'feature request' issue. We can discuss that.
