### ISSUE TITLE
How to modify the runtime of a custom tool in workflow

### ISSUE THREAD

**Issue by RXZD** [langgenius/dify#11340]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

sry, it's still the same issue I raised before. Since the previous question has been closed, I'm submitting a new one.

Here is my previous attempt：
The modification of TEXT_GENERATION_TIMEOUT_MS seems to be ineffective. I have set TEXT_GENERATION_TIMEOUT_MS=3600000, but when using the custom tool in the workflow, I encounter an error at the 15-minute mark: "Failed to invoke tool: Reached maximum retries (0) for URL." Here, I have already changed SSRF_DEFAULT_MAX_RETRIES=0.

### ✔️ Expected Behavior

I would like to be able to modify the runtime of the custom tool in the workflow. As stated in the issue, change the 15-minute limit for the custom tool in the workflow to 60 minutes.

**Comment by crazywoola** [comment]
Should be one of those

https://github.com/langgenius/dify/blob/1d8385f7ac8d71f21650ea22be720fe3f14db84c/docker/.env.example#L695-L715

For questions, please use discussion instead. This template is only for bug report.
