### ISSUE TITLE
Customized process nodes

### ISSUE THREAD

**Issue by leixiaoyuu** [langgenius/dify#11350]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I am choreographing processes, I often use some combination nodes (HTTP Requests+Code execution+Template 
 transform). Due to the frequent execution of these three nodes, the overall time consumption has significantly increased. Therefore, we want to customize the development of one node (to implement the logic of three nodes), and only need to call this customized node.

### 2. Additional context or comments
<img width="715" alt="image" src="https://github.com/user-attachments/assets/4a34b88b-a0dc-4275-8878-c3062b1a399f">

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can use a workflow to wrap them up and publish it as a tool, so in the main application, you can call this tool instead of this way.

**Comment by leixiaoyuu** [comment]
Thank you for your suggestion, it's great. But I really hope to be able to develop a feature in Dify similar to creating "custom components" in Langflow, where any Python function can be implemented in the "custom component".

> You can use a workflow to wrap them up and publish it as a tool, so in the main application, you can call this tool instead of this way.

Thank you for your suggestion, it's great. But I really hope to be able to develop a feature in Dify similar to creating "custom components" in Langflow, where any Python function can be implemented in the "custom component".
