### ISSUE TITLE
Inputs in difyChatbotConfig get lost if user clicks reset

### ISSUE THREAD

**Issue by polischool** [langgenius/dify#11366]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Config to send variables from where its embedded so can be used as reference in the chat.
Fields appear and populate fine (though making them hidden would be MOST ideal)
Conversation starts using the input variables
User clicks reset
All input values are gone.

Keeping the input values always active (and making them hidden), is turning out to be vital for it to be used as a customer support option that needs basic user and account information pre-set in the conversation.

Would also be VERY nice to have the option to NOT allow users to view / change the input values set by difyChatbotConfig

### ✔️ Expected Behavior

Values from inputs remain so user can start new chat with the input values from difyChatbotConfig

### ❌ Actual Behavior

Input values disappear so have to hard-refresh the web browser to get them back and use in the conversation.

**Comment by polischool** [comment]
This is Cloud hosted, so we have no control over the code (unless that is an option I'm not seeing when initializing)

**Comment by ShadowL360** [comment]
I have the same issue. I’ve already tried fixing this bug but haven’t had any success so far.

**Comment by polischool** [comment]
I can't see how to pull off using it as a help tool if it can't get input variables from the location on which the original script is embedded. Is there a secret out there I haven't found yet to accomplish what feels like a simple task: have the workflow start so that it includes the domain and a few more variables that are applicable to the user? (i've tried somehow using the ID of the script and adding data-domain, data-firstname, etc. and then getAttribute as a code block in the workflow, but that always makes the entire thing fail, so am at a total loss other than reliable (and hidden, and unchangeable) inputs. Hoping someone smarter than me knows the secret.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/11025
