### ISSUE TITLE
http node in workflow error

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#11371]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I call the agent's API through the HTTP node in the workflow, it returns an error, but it works correctly when using curl.

error:
![image](https://github.com/user-attachments/assets/77dee6b1-527a-4976-96a4-c6706775443e)

![image](https://github.com/user-attachments/assets/5d4f3bd7-90f8-42b5-a734-d6358f305c96)

success
![image](https://github.com/user-attachments/assets/c9e22545-978b-4a36-80f7-14d3030ae650)

**Comment by crazywoola** [comment]
Duplicated https://docs.dify.ai/learn-more/faq/install-faq
