### ISSUE TITLE
Improper file naming caused the code pull to fail on the Windows system.

### ISSUE THREAD

**Issue by alishangtian** [langgenius/dify#11377]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

filepath：https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/bedrock/rerank/cohere.rerank-v3-5%3A0.yaml
path contain  ：cause git pull error
![image](https://github.com/user-attachments/assets/27a89248-68df-472e-8097-ddcf78b06611)

### ✔️ Expected Behavior

fix

**Comment by yihong0618** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.13.0
> 
> ### Cloud or Self Hosted
> Self Hosted (Docker)
> 
> ### Steps to reproduce
> filepath：https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/bedrock/rerank/cohere.rerank-v3-5%3A0.yaml path contain ：cause git pull error ![image](https://private-user-images.githubusercontent.com/3463296/392647509-27a89248-68df-472e-8097-ddcf78b06611.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzM0NzQsIm5iZiI6MTczMzM3MzE3NCwicGF0aCI6Ii8zNDYzMjk2LzM5MjY0NzUwOS0yN2E4OTI0OC02OGRmLTQ3MmUtODA5Ny1kZGNmNzhiMDY2MTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDQzMjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2E5NTRiZjMyYWNlNzYzNDE1ZjA0NWNjODNkMjdjYzRmZjlhZjExZDA5NGI1NzQ5MzAxNDY4YTQ0ODRjMzg4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.aIxV-0X4stXB4W1nxx3RlU12qkoM7Adg4SGgG_rUp7c)
> 
> ### ✔️ Expected Behavior
> fix
> 
> ### ❌ Actual Behavior
> _No response_

git config --global core.protectNTFS false
https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows
