### ISSUE TITLE
webapp conversion project  did not address frequently asked questions

### ISSUE THREAD

**Issue by miapeng28** [langgenius/dify#11373]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

1. The api/parameters of the webapp conversion interface returned suggestions that were not processed.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Can you provide more details regarding this? Screenshots?

**Comment by crazywoola** [comment]
For questions please use discussion instead, for bug report please use bug report template.

**Comment by miapeng28** [comment]
ok
