### ISSUE TITLE
The next question suggests a language issue 

### ISSUE THREAD

**Issue by fsea** [langgenius/dify#11384]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The language suggested for the next question is always English, although I set the language to Chinese, but this feature still displays English

![image](https://github.com/user-attachments/assets/c0101a35-b1ed-4d4b-8172-6e752ee0b551)

### ✔️ Expected Behavior

The language suggested for the next question can be consistent with the system settings

### ❌ Actual Behavior

Displayed in English only

**Comment by crazywoola** [comment]
Duplicated
