### ISSUE TITLE
Local port 80 is mapped to a new port, but the link does not include the new port when published and running.

### ISSUE THREAD

**Issue by jingzl** [langgenius/dify#11399]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

 Local access to port 80 has been mapped, but when the chat assistant is published and the "Run" button is clicked, the page link that opens does not include the mapped port, causing the page to be inaccessible. However, adding the port manually allows for normal access.

### ✔️ Expected Behavior

I hope to automatically add the mapped port.

### ❌ Actual Behavior

the page link that opens does not include the mapped port, causing the page to be inaccessible

**Comment by crazywoola** [comment]
See https://docs.dify.ai/getting-started/install-self-hosted/environments

**Comment by jingzl** [comment]
thanks，update APP_WEB_URL，restart，it‘s ok
