### ISSUE TITLE
流式输出返回的节点数据太多以及并发时性能问题

### ISSUE THREAD

**Issue by zlei0251** [langgenius/dify#11393]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

流式输出时，输出的节点信息太多，能否配置一些节点的信息不通过接口输出出去
另外，当并发较大时，比如说单机20个并发时，每个节点的运行时间都会变长不少（如最简单的分支判断节点耗时达到了3s等，开始节点的耗时超过了1s），有没有性能优化的空间，亦或是只能使用集群

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
#1542
