### ISSUE TITLE
send sys.user_id when embedding in my website 

### ISSUE THREAD

**Issue by Namec999** [langgenius/dify#11396]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

i have embedded well my dify chatbot widget and i want when initialize add some values like sys.user_id value
    do i need to add it in window.difyChatbotConfig or else where
    
    also can you write me a sample script for this

**Comment by Namec999** [comment]
have added this as a sample user_id : 666-777 
but still have in my flow an autmatically generated user_id like : 9185b4b0-c391-445a-b0fe-a43729386650

**Comment by Namec999** [comment]
is there any specific template for me to use ?  @crazywoola

**Comment by metaFF** [comment]
I also encountered the same problem

<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <script>
    window.difyChatbotConfig = {
        token: 'xxxxxxxx',
        baseUrl: 'http://dify.xxxxxx.com',
            inputs: {
                'sys.user_id': 'apple',
        },
    }
    </script>
    <iframe
    src="http://dify.xxxxxx.com/chatbot/xxxxxxxx?sys.user_id=H4sIAKUlmWYA%2FwWAIQ0AAACDsl7gLuiv2PQEUNAuqQUAAAA%3D"
    style="width: 100%; height: 100%; min-height: 700px"
    frameborder="0"
    allow="microphone">
   </iframe>
</body>
</html>

**Comment by metaFF** [comment]
I also encountered the same problem

`
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <script>
    window.difyChatbotConfig = {
        token: 'xxxxxxxx',
        baseUrl: 'http://dify.xxxxxx.com',
            inputs: {
                'sys.user_id': 'apple',
        },
    }
    </script>
    <iframe
    src="http://dify.xxxxxx.com/chatbot/xxxxxxxx?sys.user_id=H4sIAKUlmWYA%2FwWAIQ0AAACDsl7gLuiv2PQEUNAuqQUAAAA%3D"
    style="width: 100%; height: 100%; min-height: 700px"
    frameborder="0"
    allow="microphone">
   </iframe>
</body>
</html>
`
