### ISSUE TITLE
Output order issue for multiple direct replies

### ISSUE THREAD

**Issue by fsea** [langgenius/dify#11416]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

There are two "direct replies" in the workflow to implement waiting, that is, "direct reply 2" always waits for the "direct reply 1" reply to end before output.
It can't be merged into a direct reply, as this results in non-streaming output.

### 2. Additional context or comments

![image](https://github.com/user-attachments/assets/ab73e8ce-af68-4d7e-b552-0cf37ebdab4b)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
The reason why is they are in different levels. For issue report, please use the right template and please provide the DSL.
