### ISSUE TITLE
The document parsing remains stuck in the indexing process, neither reporting errors nor proceeding.

### ISSUE THREAD

**Issue by Wei-ZZy** [langgenius/dify#11414]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

While parsing the document, it remains in the indexing state and has not progressed for an entire day. There are no error messages reported, and this includes the logs which also show no errors
![B6AAFD8A-7A41-4943-8EE1-90F4501E339B](https://github.com/user-attachments/assets/1e64299b-5e49-4960-a1d6-ac1684bad98e)

### ✔️ Expected Behavior

If the parsing cannot proceed, it should report an error after a certain period or terminate directly, rather than continue indefinitely and remain blocked.

### ❌ Actual Behavior

Even if there is an issue with the document, it does not report an error but remains blocked, causing a backlog and leading to continuous queuing of subsequent tasks.

**Comment by crazywoola** [comment]
Please consider upgrading to latest version and provide some container logs, sometimes a restart would resume the status.

**Comment by sugoh** [comment]
@Wei-ZZy I'm facing this issue too
