### ISSUE TITLE
Agentic rag

### ISSUE THREAD

**Issue by lucaseatp** [langgenius/dify#11419]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Integrate agentic rag with our current system. Could be optional. That would make rag really powerful.

### 2. Additional context or comments

https://weaviate.io/blog/what-is-agentic-rag
https://docs.phidata.com/agents/knowledge

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yawen-1010** [comment]
Hi, there. Thank you for bring up this topic. We have carefully studied the meaning and design of Agentic RAG. Dify RAG can currently perform agentic operations such as query rewriting, query classification, and calling tools. We will further improve this function in the future. If you need to use a third-party knowledge base, we strongly recommend that you use the external knowledge base API function to connect to the external knowledge base. There are some documents written here that may be helpful to you.https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation

**Comment by lucaseatp** [comment]
thanks yawen, a retriever tool would be great and really simplify the flow to build such agents
