### ISSUE TITLE
When I open Dify in docker, I can't register the anthropic API. (plz help)

### ISSUE THREAD

**Issue by cutemiru** [langgenius/dify#11429]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![docker_dify_connetion_error](https://github.com/user-attachments/assets/792e5375-1c37-41fa-9823-c9a839294944)

When I open Dify in docker, I can't register the anthropic API.

(A "connection error" message is called.)

Other APIs register fine.

Help!

**Comment by cutemiru** [comment]
Thanks. I looked it up, but I don't know what kind of network problem it is. It's happening to many people. If the admins see my post, please fix it.

**Comment by crazywoola** [comment]
I will forward this to the team regarding this.
