### ISSUE TITLE
Knowledge base documents that add segments do not set out to be re-vectorized or are simply not displayed on the segment preview.

### ISSUE THREAD

**Issue by Sunzhuoyi** [langgenius/dify#11420]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1 I add **"JAF是什么？
JAF作为***微服务统一研发框架，它统一产研开发技术规范、实现技术沉淀和复用，收口货拉拉所有核心基础组件，达到开箱即用、提高产研效率的目标。 "** at line 3, then I save them.
![截屏2024-12-06 11 51 11](https://github.com/user-attachments/assets/69264f52-08a4-4f42-8dd1-9b48ef5104f1)

2 I find this document again and click "Segment Settings"。the words didn't appear in the "Segment Preview"
![截屏2024-12-06 11 51 34](https://github.com/user-attachments/assets/13618cad-2e16-46f1-81e4-b1d25a86cc78)

### ✔️ Expected Behavior

the words I added appear in the "Segment Preview" and I can search them.

### ❌ Actual Behavior

The “Segment Preview” shows what was there before I edited it.

**Comment by crazywoola** [comment]
The preview only takes the sources you upload.  So you can not preview previous uploaded segements.
