### ISSUE TITLE
http request node upload big file fail

### ISSUE THREAD

**Issue by ospfrip** [langgenius/dify#11425]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The HTTP request node in the workflow, whether using form-data or binary mode to upload files, successfully uploads files of a few hundred kilobytes, but fails to upload larger files, close to 2MB. This issue has been present from version 0.11.1 to the latest version 0.13.1.

### ✔️ Expected Behavior

upload successful

### ❌ Actual Behavior

 Upload file successful.

**Comment by ospfrip** [comment]
Thanks,  Should the .env file also be copied to the API directory?

**Comment by ospfrip** [comment]
I have changed the configuration, but it didn't take effect. It can be turned off now.

**Comment by ospfrip** [comment]
I changed the configuration, restarted Dify, but uploading images still doesn't work.
![API log](https://github.com/user-attachments/assets/6c6eac03-d91f-4581-bd9e-aceab18d6d73)

**Comment by chace100** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.13.1
> 
> ### Cloud or Self Hosted
> Self Hosted (Docker)
> 
> ### Steps to reproduce
> The HTTP request node in the workflow, whether using form-data or binary mode to upload files, successfully uploads files of a few hundred kilobytes, but fails to upload larger files, close to 2MB. This issue has been present from version 0.11.1 to the latest 
> 
> ### ✔️ Expected Behavior
> upload successful
> 
> ### ❌ Actual Behavior
> Upload file successful.

Hello, I would like to ask how you set up the form data method for uploading files using HTTP nodes? When I use form data to upload files, the third-party API always returns a prompt stating that there is no file content.
