### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by fniu** [langgenius/dify#11438]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

A simple workflow to call an LLM.

### ✔️ Expected Behavior

Run normally.

### ❌ Actual Behavior

Application error: a client-side exception has occurred (see the browser console for more information).

![image](https://github.com/user-attachments/assets/b4cafe53-33a7-461f-80e8-ac242ec63768)

**Comment by Ellioben** [comment]
SAME Bug!  How to Fix it? bro😀😀

**Comment by crazywoola** [comment]
Can you provide the reproduceable steps?

**Comment by crazywoola** [comment]
> I think it has something to do with the (optional) input field. I have an example (attached yml DSL) that reproduce the error. In this example, the error is gone, if you remove the optional input from workflow or make sure the optional input is not empty.
> 
> You can try with any text as the input and leave the optional input empty.
> 
> [app_error.txt](https://github.com/user-attachments/files/18048646/app_error.txt)

I tried both empty and not empty, still can not reproduce this error.
·

**Comment by jpgsns** [comment]
Same thing here when i try to see the outputs of a Model step.

![Captura de Tela 2024-12-07 às 15 37 41](https://github.com/user-attachments/assets/d16ecc8a-52a0-49be-8b77-8b23ed9a340b)

**Comment by correlli** [comment]
I only experience this when I open the trace log of Extractin Parameter block.
It says client-side but does it so?

**Comment by JzoNgKVO** [comment]
Fixed in https://github.com/langgenius/dify/pull/11432

**Comment by correlli** [comment]
Still, I get this error only for the Extracting Parameter block.

**Comment by JzoNgKVO** [comment]
> Still, I get this error only for the Extracting Parameter block.

Today's new release will include PR #11438 . The new version has not been released yet.
