### ISSUE TITLE
build v0.13.1, report exception

### ISSUE THREAD

**Issue by zhudemiao** [langgenius/dify#11441]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

make build-api

### ✔️ Expected Behavior

build successfully

### ❌ Actual Behavior

```
report exception:
Step 14/40 : COPY pyproject.toml poetry.lock ./
 ---> b04a92c25834
Step 15/40 : RUN  poetry install --sync --no-cache --no-root
 ---> Running in 088e0657d45f
Creating virtualenv non-package-mode in /app/api/.venv
Installing dependencies from lock file

Package operations: 405 installs, 0 updates, 0 removals

  - Installing frozenlist (1.5.0)
  - Installing idna (3.10)
  - Installing multidict (6.1.0)
  - Installing pycparser (2.22)
  - Installing aiohappyeyeballs (2.4.4)
  - Installing aiosignal (1.3.1)
  - Installing attrs (23.2.0)
  - Installing cffi (1.17.1)
  - Installing charset-normalizer (3.4.0)
  - Installing certifi (2024.8.30)
  - Installing urllib3 (2.2.3)
  - Installing wrapt (1.17.0)
  - Installing yarl (1.9.11)
  - Installing zipp (3.21.0)

  TimeoutError

  The read operation timed out

  at /usr/local/lib/python3.12/ssl.py:1103 in read
      1099│         if self._sslobj is None:
      1100│             raise ValueError("Read on closed or unwrapped SSL socket.")
      1101│         try:
      1102│             if buffer is not None:
    → 1103│                 return self._sslobj.read(len, buffer)
      1104│             else:
      1105│                 return self._sslobj.read(len)
      1106│         except SSLError as x:
      1107│             if x.args[0] == SSL_ERROR_EOF and self.suppress_ragged_eofs:

The following error occurred when trying to handle this error:


  ReadTimeoutError

  HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

  at /usr/local/lib/python3.12/site-packages/urllib3/response.py:753 in _error_catcher
       749│
       750│             except SocketTimeout as e:
       751│                 # FIXME: Ideally we'd like to include the url in the ReadTimeoutError but
       752│                 # there is yet no clean way to get at it from this context.
    →  753│                 raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
       754│
       755│             except BaseSSLError as e:
       756│                 # FIXME: Is there a better way to differentiate between SSLErrors?
       757│                 if "read operation timed out" not in str(e):

The following error occurred when trying to handle this error:


  ConnectionError

  HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

  at /usr/local/lib/python3.12/site-packages/requests/models.py:826 in generate
       822│                     raise ChunkedEncodingError(e)
       823│                 except DecodeError as e:
       824│                     raise ContentDecodingError(e)
       825│                 except ReadTimeoutError as e:
    →  826│                     raise ConnectionError(e)
       827│                 except SSLError as e:
       828│                     raise RequestsSSLError(e)
       829│             else:
       830│                 # Standard file-like object.

Cannot install yarl.

The command '/bin/sh -c poetry install --sync --no-cache --no-root' returned a non-zero code: 1
make: *** [Makefile:16: build-api] Error 1
```

**Comment by zhudemiao** [comment]
if I modify api/Dockerfile from :
RUN  poetry install --sync --no-cache --no-root
TO
RUN poetry config repositories.pypi https://pypi.tuna.tsinghua.edu.cn/simple/ && poetry install --sync --no-cache --no-root.
BUT also report error。

**Comment by zhudemiao** [comment]
- Installing mdurl (0.1.2)
  - Installing isodate (0.7.2)
  - Installing packaging (24.2)
  - Installing proto-plus (1.25.0)
  - Installing msal (1.31.1)
  - Installing pyparsing (3.2.0)
  - Installing referencing (0.35.1)
  - Installing requests-oauthlib (2.0.0)
  - Installing portalocker (2.10.1)
  - Installing sniffio (1.3.1)
  - Installing markupsafe (3.0.2)
  - Installing opentelemetry-semantic-conventions (0.49b2)

  TimeoutError

  The read operation timed out

  at /usr/local/lib/python3.12/ssl.py:1103 in read
      1099│         if self._sslobj is None:
      1100│             raise ValueError("Read on closed or unwrapped SSL socket.")
      1101│         try:
      1102│             if buffer is not None:
    → 1103│                 return self._sslobj.read(len, buffer)
      1104│             else:
      1105│                 return self._sslobj.read(len)
      1106│         except SSLError as x:
      1107│             if x.args[0] == SSL_ERROR_EOF and self.suppress_ragged_eofs:

The following error occurred when trying to handle this error:


  ReadTimeoutError

  HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

  at /usr/local/lib/python3.12/site-packages/urllib3/response.py:753 in _error_catcher
       749│
       750│             except SocketTimeout as e:
       751│                 # FIXME: Ideally we'd like to include the url in the ReadTimeoutError but
       752│                 # there is yet no clean way to get at it from this context.
    →  753│                 raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
       754│
       755│             except BaseSSLError as e:
       756│                 # FIXME: Is there a better way to differentiate between SSLErrors?
       757│                 if "read operation timed out" not in str(e):

The following error occurred when trying to handle this error:


  ConnectionError

  HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

  at /usr/local/lib/python3.12/site-packages/requests/models.py:826 in generate
       822│                     raise ChunkedEncodingError(e)
       823│                 except DecodeError as e:
       824│                     raise ContentDecodingError(e)
       825│                 except ReadTimeoutError as e:
    →  826│                     raise ConnectionError(e)
       827│                 except SSLError as e:
       828│                     raise RequestsSSLError(e)
       829│             else:
       830│                 # Standard file-like object.

Cannot install botocore.

Warning: The file chosen for install of rpds-py 0.22.1 (rpds_py-0.22.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) is yanked. Reason for being yanked: https://github.com/PyO3/pyo3/issues/4757
The command '/bin/sh -c poetry config repositories.thu https://pypi.tuna.tsinghua.edu.cn/simple/ && poetry install --sync --no-cache --no-root' returned a non-zero code: 1
make: *** [Makefile:16: build-api] Error 1

**Comment by crazywoola** [comment]
We do not provide help for building from source code, please figure it out yourself or you can ask help in discussion.

**Comment by wnqnxbb** [comment]
The same question

**Comment by chlg** [comment]
The same question too
