### ISSUE TITLE
tts is not enable

### ISSUE THREAD

**Issue by acshmily** [langgenius/dify#11446]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I deployed Dify based on the Helm of Douban. When using the workflow preview function and turning on the "Text-to-Speech" feature, a prompt saying "TTS is not enable" popped up. Could you please tell me how to solve this problem? Besides, is it possible to specify an open-source TTS large model by myself?

**Comment by acshmily** [comment]
I'm using Helm for deployment. Could you please tell me where to modify the following configuration?

**Comment by acshmily** [comment]
@dosu I haven't found the place you suggested.

**Comment by acshmily** [comment]
Does Dify use OpenAI's TTS by default? And is it possible to replace it on one's own?

**Comment by crazywoola** [comment]
For questions please use discussion instead.

**Comment by yu921** [comment]
docker compose 部署的Dify，再哪个文件中启动TTS?

**Comment by DomoMKT** [comment]
you can actually find a free text-to-speech solution with low latency and high-quality speech at [www.nemesyslabs.com](https://www.nemesyslabs.com) that doesn't require an account or model lists, just pure conversion power!

**Comment by kfchandsome** [comment]
> docker compose 部署的Dify，再哪个文件中启动TTS?

请问你解决问题了吗
