### ISSUE TITLE
Knowledge file indexing 500 error

### ISSUE THREAD

**Issue by sugoh** [langgenius/dify#11454]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.13.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Upload document via API `https://api.dify.ai/v1/datasets/{inputs.dataset_id}/document/create-by-text`
with this request body:
```
{
   "name": "xxx",
   "text": "yyy",
   "indexing_technique": "high_quality",
   "process_rule": {
      "mode": "custom",
      "rules": {
         "pre_processing_rules":  [],
         "segmentation": {
            "separator": "\n",
            "max_tokens": 1000,
         }
      }     
   }
}
```

### ✔️ Expected Behavior

1. New file uploaded to Knowledge
2. File indexing complete

### ❌ Actual Behavior

1. New file uploaded to Knowledge
2. 500 error on indexing
<img width="271" alt="Screenshot 2024-12-07 at 10 56 20 PM" src="https://github.com/user-attachments/assets/5664c88f-14fa-443c-9fa1-06fb126956a3">

**Comment by sugoh** [comment]
To clarify, Model Provider has been setup and the API key is functioning. Our code was working all day until Dify suddenly stopped working

**Comment by crazywoola** [comment]
I can not reproduce this in our cloud environment. And I saw the original version you mentioned is v0.11.2, however we are using v0.13.1 in our cloud environment right now.
Can you clarify this?

<img width="841" alt="image" src="https://github.com/user-attachments/assets/68c1921c-502e-4524-8c97-8903587fdaac">

**Comment by sugoh** [comment]
@crazywoola sorry, copypasta error. it's `v0.13.1` indeed.

Network shows that the error response I'm getting is (I've scrubbed the exact dataset id):
```json
{
    "data": [
        {
            "id": "[xxx]",
            "indexing_status": "error",
            "processing_started_at": 1733626333,
            "parsing_completed_at": 1733626333,
            "cleaning_completed_at": 1733626334,
            "splitting_completed_at": 1733626334,
            "completed_at": 1733585155,
            "paused_at": null,
            "error": "Unexpected Response: 500 (Internal Server Error)\nRaw response content:\nb'{\"time\":4.1e-8,\"status\":{\"error\":\"Internal server error\"}}'",
            "stopped_at": 1733626338,
            "completed_segments": 0,
            "total_segments": 0
        },
        {
            "id": "[xxx]",
            "indexing_status": "error",
            "processing_started_at": 1733626347,
            "parsing_completed_at": 1733626347,
            "cleaning_completed_at": 1733626348,
            "splitting_completed_at": 1733626348,
            "completed_at": 1733585159,
            "paused_at": null,
            "error": "Unexpected Response: 500 (Internal Server Error)\nRaw response content:\nb'{\"time\":4.1e-8,\"status\":{\"error\":\"Internal server error\"}}'",
            "stopped_at": 1733626350,
            "completed_segments": 0,
            "total_segments": 0
        }
    ],
    "total": 2
}
```

Further maybe helpful information:
- Indexing only fails in high quality mode. Economical works just fine.
- We tried attaching a fresh Cohere API key but we're still facing this issue.

**Comment by sugoh** [comment]
@JohnJyong can confirm it's not an issue with our Cohere rate limit. It's only been hit once.
<img width="1445" alt="Screenshot 2024-12-08 at 11 54 53 AM" src="https://github.com/user-attachments/assets/122edcd6-86be-4cab-bb6d-ad1ca44ebbbf">

**Comment by sugoh** [comment]
@JohnJyong further update:
1. This is working for new knowledge bases that we create.
2. One knowledge based is cursed. the id is `f6d65374-31f3-4e86-a710-37721f8d33f0`. Suggestion: can you add more verbose error logging to determine why this is happening?

**Comment by sugoh** [comment]
@JohnJyong @crazywoola any updates?

Now every document in the knowledge base is stuck at queuing
<img width="293" alt="Screenshot 2024-12-12 at 12 43 18 PM" src="https://github.com/user-attachments/assets/2be101a8-a217-4937-9239-e8d40b0a1986" />

This is the same issue as reported in [Ticket 11414]( https://github.com/langgenius/dify/issues/11414) that is also unresolved

**Comment by crazywoola** [comment]
@sugoh Are you using OpenAI's embedding model yesterday, their API service was down yesterday.

**Comment by sugoh** [comment]
@crazywoola I was. However, this issue has existed since before they went down.

**Comment by ToX82** [comment]
I am having the same issue with embedding, both with cohere and huggingface. Those are both new accounts, so the rate limit is not being the issue

**Comment by sugoh** [comment]
@ToX82 Can confirm, I'm still facing the same issue in v0.14.1

It seems that once a knowledge base gets "corrupted" somehow, the only way to work around it is to create a new knowledge base and re-upload + re-index everything. Am hoping @JohnJyong or @crazywoola would either investigate the server logs or upgrade the error messages being passed to the client so we can report back. The current message is just so unhelpfully generic.

**Comment by crazywoola** [comment]
This should be fixed now. We have some issues with TiDB instances.

**Comment by sugoh** [comment]
@crazywoola thanks for investigating. however, the issue still persists. No files can be indexed for corrupted knowledge bases. An example is `f6d65374-31f3-4e86-a710-37721f8d33f0`
