### ISSUE TITLE
Cannot get streaming answer in workflow when that include branch node 

### ISSUE THREAD

**Issue by wxjttxs** [langgenius/dify#11477]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when the workflow has the if-else or code-execution,  then call its API， it only output blocking answer even it looks like streaming. this is my screenshot:
![image](https://github.com/user-attachments/assets/e4b1bb8b-e00d-48ca-83a1-80b16370f8dc)

### ✔️ Expected Behavior

streaming answer

### ❌ Actual Behavior

block answer

**Comment by crazywoola** [comment]
Some nodes can produce answers like blocking only, for example, you append a code node before the answer, then it should behave like this. Only LLM can produce streaming like event for now.

**Comment by wxjttxs** [comment]
> > Some nodes can produce answers like blocking only, for example, you append a code node before the answer, then it should behave like this. Only LLM can produce streaming like event for now.
> 
> Thank you for your reply. but My workflow just like this situation, if-else before and LLM after then output, but it still does not output the streaming answer. this is my screenshot of workflow : ![image](https://private-user-images.githubusercontent.com/12609388/393690226-26b83408-d761-4a97-8732-a25d49284e1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTUzMDksIm5iZiI6MTczMzcxNTAwOSwicGF0aCI6Ii8xMjYwOTM4OC8zOTM2OTAyMjYtMjZiODM0MDgtZDc2MS00YTk3LTg3MzItYTI1ZDQ5Mjg0ZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAzMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWE2MGNiZjY1ZWM3MDBhNTY3YmJjNDRkODE5OTE5NGZhMjQ0YWQyNTEyOGRhMTk2NDRkZDQ4OWE0MWFjOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.djcUk6aRz1AtXN9nyzUGBo-mM1BZh4H-5kH6-PKzYRM)

I have already sloved this problem by change the order of Variable assignment  and output .

**Comment by wxjttxs** [comment]
> Some nodes can produce answers like blocking only, for example, you append a code node before the answer, then it should behave like this. Only LLM can produce streaming like event for now.

Thank you so much!
