### ISSUE TITLE
How to input audio file. 

### ISSUE THREAD

**Issue by hsoftxl** [langgenius/dify#11499]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

i want create a flow as folow.
mp3 file -> audio modle -> llm modle -> text2speech modle

**Comment by DomoMKT** [comment]
you can achieve exactly what you're looking for by checking out [www.nemesyslabs.com](https://www.nemesyslabs.com), which provides high-quality text-to-speech conversion with super low latency and no need to create an account.
