### ISSUE TITLE
When bedrock's AKSK is left blank ( AWS environment configuration is automatically called), an error will be reported when using the rerank model

### ISSUE THREAD

**Issue by FelixFeli** [langgenius/dify#11494]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Deploy Dify on AWS EC2 and select Amazon Bedrock in Model Provider, Access Key and Secret Access Key Leave blank. At this time, the credentials owned by EC2 will be used by default to call bedrock. In the new version, when calling the newly added bedrock rerank model, an error will be reported without AKSK.
![image](https://github.com/user-attachments/assets/83ebd100-c286-4584-9d1d-2bbb685fcc7c)

### ✔️ Expected Behavior

Successfully called bedrock rerank model

### ❌ Actual Behavior

[bedrock] Error: Partial credentials foundin explicit, missing: aws_secret_access_key

**Comment by warren830** [comment]
@FelixFeli hi, I feel so confused how can you set bedrock without aksk? Can you provide some screenshots.

**Comment by FelixFeli** [comment]
> @FelixFeli hi, I feel so confused how can you set bedrock without aksk? Can you provide some screenshots.

![image](https://github.com/user-attachments/assets/c2d10f42-b29a-44e2-b0af-7e4866b906ed)

Just leave it blank, AKSK is not required. If not filled in, it will be read from the system environment
