### ISSUE TITLE
An error occurred using the Dify API

### ISSUE THREAD

**Issue by vank3f3** [langgenius/dify#11493]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am experiencing errors while using the DIFY API, and I have already created an API-KEY and used it in the headers, but I am getting different error messages when using APIFOX and directly requesting the API from Linux.
![image](https://github.com/user-attachments/assets/fa64d864-b56f-4384-bafd-acd796fa153b)
![image](https://github.com/user-attachments/assets/9d6ead20-1993-4e73-8b36-047d68187864)

Additional materials, my Nginx configuration is as follows:
```
server {
    listen 80;
    server_name _; # 可以更明确填写对应的域名

    return 301 https://$host$request_uri;  # 重定向到 https
}


server {
    listen 443 ssl;
    server_name _;
    
    ssl_certificate /etc/nginx/ssl/example.crt;
    ssl_certificate_key /etc/nginx/ssl/example.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;


    location /console/api {
      proxy_pass http://dify-api:5001;
      include proxy.conf;
    }

    location /api {
      proxy_pass http://dify-api:5001;
      include proxy.conf;
    }

    location /v1 {
      proxy_pass http://dify-api:5001;
      include proxy.conf;
    }

    location /files {
      proxy_pass http://dify-api:5001;
      include proxy.conf;
    }

    location / {
      proxy_pass http://dify-web:3000;
      include proxy.conf;
    }
}
```

### ✔️ Expected Behavior

Return the correct API response.

### ❌ Actual Behavior

The API cannot be used properly

**Comment by crazywoola** [comment]
Can you provide more details, cause I can not reproduce error based on the descripition.

**Comment by hjlarry** [comment]
in the `curl` command, you try to request with `http`, but nginx config  80 port redirect to 443,  it's a correct behavior.
you can check docker log for more details
