### ISSUE TITLE
Is this a bug for PdfExtractor in  ExtractProcessor

### ISSUE THREAD

**Issue by spytensor** [langgenius/dify#11495]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Why dify ETL type use the same pdf extractor with Unstructured ETL type? 
For pdf files Unstructured ETL can extractor image-only file better.
Unstructured ETL Pdf extractor in :https://github.com/langgenius/dify/blob/7f1b0288409626fcb87bee2fe12643ebfa0f3059/api/core/rag/extractor/extract_processor.py#L104
Dify ETL Pdf extractor in :https://github.com/langgenius/dify/blob/7f1b0288409626fcb87bee2fe12643ebfa0f3059/api/core/rag/extractor/extract_processor.py#L140.

I think Unstructured ETL should use UnstructuredPDFExtractor instead.

**Comment by crazywoola** [comment]
No actually it's the problem of Unstructured ETL which will consume lots of resources.
