### ISSUE TITLE
Add vision model for volcengine

### ISSUE THREAD

**Issue by deific** [langgenius/dify#11498]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Volcengine already has a multimodal model that supports image recognition: Doubao-vision-pro 32k. This model is not included in the model list of dify's volcengine model provider. When it is introduced in a custom way, the vision control switch cannot be turned on.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by eye8** [comment]
I also need to access Doubao-vision-pro 32k in Dify. Please support! Thank you.

**Comment by zhangever** [comment]
Expecting
