### ISSUE TITLE
It keeps spinning in circles and won't open.

### ISSUE THREAD

**Issue by Vampxgg** [langgenius/dify#11512]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![45b7458b-8373-4905-8ebd-9a0ffdf6d87d](https://github.com/user-attachments/assets/ff41bd1d-945b-41ef-a94c-7e531c028a38)
After I opened the PRO version, dify always pops up my account for no reason. When I open it, it keeps loading in circles and I just can't get in. Is this a bug?

### ✔️ Expected Behavior

---

### ❌ Actual Behavior

---

**Comment by crazywoola** [comment]
What's this page? Can you share the url? I can not guess what's happening based on this image.

**Comment by Vampxgg** [comment]
![70a3a4ec-cea4-42cb-8cf9-e0e322f9eee4](https://github.com/user-attachments/assets/f29115d9-6832-4fcd-8416-ea4dfc2c8406)
Like this, friend
