### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Alex-lsky** [langgenius/dify#11510]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The memory footprint of dify,api, and work containers deployed with docker is always monotonically increasing, and memory is not released when calls are stopped, I have verified this issue in multiple versions (0.8-0.13.1) and in multiple environments (docker, k8s)
![image](https://github.com/user-attachments/assets/2f5db6a4-9301-432e-9110-c942e22ab347)

### ✔️ Expected Behavior

When the call is stopped, the memory usage drops

### ❌ Actual Behavior

The memory of the api and work is always growing until it takes up about 6G and the LLM call efficiency becomes so low that the container must be restarted to alleviate it

**Comment by liangpeihuahua** [comment]
I also encountered this problem. The memory kept increasing and I had to restart the container to solve it. My version is 0.13.1
