### ISSUE TITLE
How to improve performance?

### ISSUE THREAD

**Issue by zlei0251** [langgenius/dify#11522]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

How to improve performance? For example, when there are 20 concurrent connections, the simplest conditional branch node also takes several seconds. In addition, is there any room for optimization of the code execution node? Currently, no matter how complex the code is, it takes at least 500ms to execute the code, which is a considerable time expenditure for our scenario.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
For questions, please use discusston instead.
