### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException:

### ISSUE THREAD

**Issue by mdxlCJ** [langgenius/dify#11548]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Request dify with parameter a, specific value R: 111, or token, value is: EAA25127B638EBE05A4D35561F7CF2FE， Then, dify this parameter and request the HTTP POST server again, but an error occurs, Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'EAA25127B638EBE05A4D35561F7CF2FE': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') 

### ✔️ Expected Behavior

Can you receive all parameters

### ❌ Actual Behavior

Partial business cannot be implemented

**Comment by crazywoola** [comment]
Please upgrade to latest version.

**Comment by mdxlCJ** [comment]
dify 上 http 请求 ，json解析错误，先不要给我closed
<img width="643" alt="WechatIMG95" src="https://github.com/user-attachments/assets/cee3494c-628a-450a-91df-0cb058455ac7" />

**Comment by crazywoola** [comment]
<img width="773" alt="image" src="https://github.com/user-attachments/assets/aa535152-8a1b-4e2e-b255-edeac0d28442" />
<img width="593" alt="image" src="https://github.com/user-attachments/assets/f6e6ad39-f26b-4266-b7c4-65fefacccb61" />
