### ISSUE TITLE
No identity authentication method configured

### ISSUE THREAD

**Issue by thymol-zzw** [langgenius/dify#11552]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![未配置身份认证方式](https://github.com/user-attachments/assets/3cc16e0c-2195-43aa-81d8-ce454649430c)

### ✔️ Expected Behavior

No identity authentication method configured，Help everyone？

### ❌ Actual Behavior

No identity authentication method configured，Help everyone？

**Comment by thymol-zzw** [comment]
Please help me, everyone

**Comment by lackoxy** [comment]
Do you have a admin account in dify？If yes, please connect to the owner of admin account. Let him to invite you to create a account. If the dify don't have a admin account, just create a admin account.
``` text
http://your_ip:port/install
```
