### ISSUE TITLE
Langfuse trace id does not equal to workflow_run_id

### ISSUE THREAD

**Issue by cpwan** [langgenius/dify#11555]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v2.75.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/2d85fd0c-719b-4c51-82f7-b65008a5b9a9)

### ✔️ Expected Behavior

https://docs.dify.ai/guides/monitoring/integrate-external-ops-tools/integrate-langfuse#trace-the-information-of-workflow-and-chatflow
![image](https://github.com/user-attachments/assets/9bde0b77-fb1a-478b-8272-d8d2a2a46bf7)

### ❌ Actual Behavior

I suspect that the trace id in Langfuse is the `workflow_app_log_id`, given the code at
https://github.com/langgenius/dify/blob/ceaa9f1101b03b94f6536bfa8a7381fb23fa3894/api/core/ops/langfuse_trace/langfuse_trace.py#L68
However, the `workflow_app_log_id` is not returned by the workflow run API. It makes the tracing difficult.

**Comment by cpwan** [comment]
@dosu points to the code where the `workflow_app_log_id` can be included in the API response.

**Comment by ZhouhaoJiang** [comment]
@cpwan 统一改为 workflow id 可以吗，workflow log Id 修改为 metadata 中的字段

**Comment by cpwan** [comment]
`workflow id` is the same for different runs
suggest to use `workflow_run_id` to be the trace id instead.

also support adding workflow log Id into metadata

**Comment by ZhouhaoJiang** [comment]
@cpwan I will make changes later and submit pr.

**Comment by ZhouhaoJiang** [comment]
I have updated it in #11585
