### ISSUE TITLE
How to add history message for optimize the question in knowledge-retrieval 

### ISSUE THREAD

**Issue by xy3xy3** [langgenius/dify#11573]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In multiple rounds of dialogue, there may be a reference problem of the person's name. You need to eliminate the reference according to the chat history and then search.
i found that in fastgpt (another program like dify),they have a node called Problem optimizer.
But I didn't found something same in dify.
And the workflow can't import a history message variable.So it seems I can't make a workflow to solve it.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can store things in conversation variables and remove unnecessary information based on your needs.

**Comment by xy3xy3** [comment]
> You can store things in conversation variables and remove unnecessary information based on your needs.

![image](https://github.com/user-attachments/assets/0ea0182c-9a46-46a8-a175-01de7730e7b9)
Is the session history variable deprecated now?
According to the documentation (https://docs.dify.ai/zh-hans/guides/workflow/node/variable-assigner), I seem to have to use a large model to retrieve the memory for variable assignment, which may consume tokens. I hope I can directly retrieve the memory content for variable assignment
