### ISSUE TITLE
knowledge base does not work, although it worked before

### ISSUE THREAD

**Issue by larkinmd7** [langgenius/dify#11598]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

There's an error 
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/195250fa-07bb-4c3e-9f78-8c730296386f" />

There's an error 
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/f2ca2a7b-6f34-4fb9-a255-0401ceec8de7" />

No error
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/67d582ef-7253-481f-b24d-07f86be26ab6" />

### ✔️ Expected Behavior

I expected that where there is an “error”, it will be the same as where there is no “error”.
It is necessary to show documents when testing and calling relevant sections of the document. 

### ❌ Actual Behavior

It gives an error and the documents themselves are not visible, the reason for the error is unknown to me.

**Comment by crazywoola** [comment]
This happens when the embedding models are not the same, at least some of them are not using the same model, check the settings of each document and try to reindex those documents.

**Comment by larkinmd7** [comment]
What exactly do you need to check? I'm a little confused? Is it possible to send screenshots?

**Comment by larkinmd7** [comment]
> Это происходит, когда модели внедрения не совпадают, по крайней мере некоторые из них не используют одну и ту же модель; проверьте настройки каждого документа и попробуйте переиндексировать эти документы.

что именно нужно проверить? немного не понял? есть возможность прислать скриншоты?

**Comment by crazywoola** [comment]
Here is the general settings for the dataset.

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/9f3f0fcb-0b1c-4e5f-8a09-c886915cef84" />

And here is the setting for the document in the dataset.

<img width="1848" alt="image" src="https://github.com/user-attachments/assets/6dc27d3d-c8d4-40e3-93b5-81b8159cc865" />
