### ISSUE TITLE
How to distinguish whether the return result is a security policy based on the return result

### ISSUE THREAD

**Issue by wwh-coder** [langgenius/dify#11597]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

How to distinguish between the return results of code execution nodes, which ones are due to security protection, and which ones may be non security protection errors? (For example, modules not imported, misspelled paths, or grammar errors, etc.)

**Comment by crazywoola** [comment]
For questions please use discussion instead, this is a bug report template.
