### ISSUE TITLE
本地部署，无法使用OpenAI 对文件进行向量嵌入

### ISSUE THREAD

**Issue by thetaworld** [langgenius/dify#1159]
### Dify version

0.3.15

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/36735442/13ff5cfa-7357-4dec-a72f-8cfa8df2a38b)
![image](https://github.com/langgenius/dify/assets/36735442/ed8fbee2-e75c-45aa-b251-faf1b206e365)
此外本地开了VPN,可以访问外网，且可以进行正常聊天
![image](https://github.com/langgenius/dify/assets/36735442/8e58dc70-c78e-4d81-bb30-f9742dc394c8)

### ✔️ Expected Behavior

可以进行正常OpenAI向量嵌入

### ❌ Actual Behavior

未能进行正确的OpenAI向量嵌入

**Comment by thetaworld** [comment]
> You can try to curl that API endpoint in your command line on your server.
thanks，I think that pycharm does not use VPN to connect to the network。I'm trying to solve this problem。

**Comment by thetaworld** [comment]
> > You can try to curl that API endpoint in your command line on your server.
> > thanks，I think that pycharm does not use VPN to connect to the network。I'm trying to solve this problem。
I've tried curl and pycharm to see if I can connect to /v1/embeddings, that's works
![image](https://github.com/langgenius/dify/assets/36735442/ab059ecd-9139-4075-8422-fa4f3cd111f6)
![image](https://github.com/langgenius/dify/assets/36735442/056fe80c-f4de-493b-a9fa-23dbb87172cc)
now i'm confused

**Comment by takatost** [comment]
You can try curling in the API container. From the error message, it seems that the Docker container is unable to connect to OpenAI. You should check if the network between Docker and OpenAI is working properly.

**Comment by thetaworld** [comment]
I solved this problem  by “http_proxy=http://127.0.0.1:7890 celery -A app.celery worker -P gevent -c 1 -Q dataset,generation,mail --loglevel INFO” 
![image](https://github.com/langgenius/dify/assets/36735442/c56f1042-ccb4-419b-974f-4998bd7d8e9d)
