### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException

### ISSUE THREAD

**Issue by mdxlCJ** [langgenius/dify#11591]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Request dify with parameter a, specific value R: 111, or token, value is: EAA25127B638EBE05A4D35561F7CF2FE， Then, dify this parameter and request the HTTP POST server again, but an error occurs, Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'EAA25127B638EBE05A4D35561F7CF2FE': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
<img width="643" alt="WechatIMG95" src="https://github.com/user-attachments/assets/c3febd4e-15f8-43c0-a6ea-a8f5bb9d3f63" />
<img width="729" alt="WechatIMG96" src="https://github.com/user-attachments/assets/eb2e03d3-ac6e-42c3-8ec0-8f41c6f10383" />
上面第一张图是本地请求正常，通过dify在input设置为string，将这个参数请求http post请求，json错误，请帮忙解决一下，不要再给我直接关闭了

### ✔️ Expected Behavior

帮忙解决

**Comment by mdxlCJ** [comment]
在dify里面，这个是一个参数，请看截图
<img width="729" alt="WechatIMG96" src="https://github.com/user-attachments/assets/e8ccff96-a666-4bfe-90ab-0b5684e8b2ca" />
![Uploading WechatIMG97.jpg…]()

**Comment by crazywoola** [comment]
图呢？

**Comment by crazywoola** [comment]
If you would like to ask for help, please use discussion instead.
