### ISSUE TITLE
Code Node Variables

### ISSUE THREAD

**Issue by Namec999** [langgenius/dify#11607]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Using the default Code Node, is there any way to make the code that need to be executed extracted from a variable

i mean a previous node store the code that need to be executed in a variable, then pass it to the code node

**Comment by Namec999** [comment]
greate news, how to achieve this from my workflow ui ?

**Comment by crazywoola** [comment]
No, we do not support dynamic code executing, this is a pretty dangerous behavior.
