### ISSUE TITLE
Escape issues of HTTP nodes

### ISSUE THREAD

**Issue by z331281772** [langgenius/dify#11600]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I found that the http  node request body is not automatically escaped when using the HTTP node 0.11.2, while it is automatically escaped in version 0.6.15

### ✔️ Expected Behavior

![CMC41E5 tmp](https://github.com/user-attachments/assets/2f8c5190-88c1-4420-9871-fad707be1a5c)

### ❌ Actual Behavior

![395091129-3287b144-f82a-4aa0-8757-ef4f81f19460](https://github.com/user-attachments/assets/182c97a2-fbc1-43be-9c8e-f62fd6c4b1fb)

**Comment by crazywoola** [comment]
Please upgrade to latest version.
