### ISSUE TITLE
Agent code Generation

### ISSUE THREAD

**Issue by Namec999** [langgenius/dify#11606]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Hello,

i am sharing  my case that i am stuck with.

maybe this is related to some misunderstanding or to the philosphy of Dify itself

currenlty, i asking my llm to do some analysis on some data (array of objects with some features) some of the arrays are related to each other by referencinf their id's

currently my llm cannot do some of the easiest thing like COUNT : please count how many assets i have
and things are more complicated when asking for some other aggregates

Questions :

- can this be solved only by prompt (using llama 3.3 70b currently)
- is there any way to make my flow generate some code dynamically depending on request and then do it's job, the right way (because i think if the llm excecute code, responses will be better)

best and let the force be with you

**Comment by Namec999** [comment]
can this be done using the workflow UI, i mean is there any nodes that make me able to achieve this

**Comment by Namec999** [comment]
i think there is a misunderstanding, when i say "achieve dynamic code generation and execution" i mean the code that need to be inserted, is generated by an LLM node before, and passed to the code Node as a variable

**Comment by crazywoola** [comment]
Duplicated
