### ISSUE TITLE
The APP_API_URL configured in the .env file does not take effect, and the http://localhost:5001/api is always requested

### ISSUE THREAD

**Issue by fsea** [langgenius/dify#11619]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The APP_API_URL configured in the .env file does not take effect, and the http://localhost:5001/api is always requested

### ✔️ Expected Behavior

Request an interface as configured in ENV

**Comment by crazywoola** [comment]
If you are using docker, you will not see a port available.
