### ISSUE TITLE
Internal Server Error when saving a document fragment

### ISSUE THREAD

**Issue by SpiderMkt1** [langgenius/dify#11614]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create Knowledge
2. Add Document
3. Add Fragment
4. Save Fragment
<img width="1365" alt="internal server error" src="https://github.com/user-attachments/assets/72d730fb-63f9-4ad1-92f2-f01450b04cc2" />

### ✔️ Expected Behavior

Add the fragment

### ❌ Actual Behavior

Internal Server Error
<img width="1365" alt="internal server error" src="https://github.com/user-attachments/assets/a202e3a9-adf6-4535-964f-09f811cd9b95" />

**Comment by crazywoola** [comment]
The version is outdated, if you encounter a 500 error, please attach the container logs.
