### ISSUE TITLE
怎么修改web页面的访问根路径

### ISSUE THREAD

**Issue by Prometheusxiao** [langgenius/dify#11622]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

修改前端访问的根路径

### ✔️ Expected Behavior

修改前端访问的根路径

### ❌ Actual Behavior

修改前端访问的根路径

**Comment by Wings-Fantasy** [comment]
解决了吗？我想搭到nginx后面，用/dify访问。要怎么修改？
