### ISSUE TITLE
dify is a Chinese company, we need to pay attention to information security！

### ISSUE THREAD

**Issue by Prometheusxiao** [langgenius/dify#11626]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

dify is a Chinese company, we need to pay attention to information security！

### ✔️ Expected Behavior

dify is a Chinese company, we need to pay attention to information security！

### ❌ Actual Behavior

dify is a Chinese company, we need to pay attention to information security！

**Comment by crazywoola** [comment]
https://docs.dify.ai/policies/agreement

**Comment by crazywoola** [comment]
Dify is the product of LangGenius,Inc., a company registered in the United States and headquartered in MOUNTAIN VIEW, CA.

**Comment by lalakii** [comment]
但愿你有朝一日能为你今日的所作所为感到羞耻。
