### ISSUE TITLE
chat API does not support user-defined conversation id

### ISSUE THREAD

**Issue by cyflhn** [langgenius/dify#11637]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. call API of /v1/chat-messages with parameter of "conversation_id"  which is not returned by previous API call

### ✔️ Expected Behavior

get a normal response

### ❌ Actual Behavior

if  the response will be "conversation not exists"

**Comment by laipz8200** [comment]
We can support a custom conversation_id, but it must meet the following requirements:

1. It should be a valid UUID.
2. It must not conflict with any existing data.
3. It should not expose information about other tenants, including whether another tenant is using the same conversation_id.

Can you implement this?

**Comment by cyflhn** [comment]
> We can support a custom conversation_id, but it must meet the following requirements:
> 
> 1. It should be a valid UUID.
> 2. It must not conflict with any existing data.
> 3. It should not expose information about other tenants, including whether another tenant is using the same conversation_id.
> 
> Can you implement this?

I can make sure that customized conversation_id is valid UUID.  Since it is a valid UUID, and also it is the primary key for table "conversations" in database, it is impossible to be conflicted with any existing data theoretically.

**Comment by cyflhn** [comment]
@laipz8200, Is there any problem with my PR?

**Comment by laipz8200** [comment]
Hi @cyflhn. We’re not sure what benefits customizable IDs might bring. In my opinion, when integrating with external systems, we can use the IDs generated by Dify or create a mapping table externally. Could you please elaborate on the motivation behind this proposal?

**Comment by cyflhn** [comment]
> mapping
hi @laipz8200. Glad to have a disscussion with dify team.
For agent app developers, we want to manage conversations by ourself. 
One of our particular cases, in one session, some user messages will be handled by dify, but some user messages may not be handled by dify. For example, some user messages will be handled by real customer service worker in real world. All the messages, whether they are handled by llm agent or human resource are in one session. 
I also check some other agent app develop tools, they also support user-defined session id.

**Comment by laipz8200** [comment]
Hi @cyflhn. After an internal discussion, we realized that evaluating whether to accept client-submitted primary keys might take some time. If possible, we’d appreciate it if you could keep this feature in your own repository for now and share your experiences with us as you use it. Thank you!

**Comment by xubihang** [comment]
@laipz8200 Hi. Any updates on the user-defined chatid feature? I'm working on a project right now and could really use this feature. Would be awesome if you guys could support it. Thanks!

**Comment by cyflhn** [comment]
> [@laipz8200](https://github.com/laipz8200) Hi. Any updates on the user-defined chatid feature? I'm working on a project right now and could really use this feature. Would be awesome if you guys could support it. Thanks!

My PR was closed as this feature was not planned to be accepted.
