### ISSUE TITLE
Custom Tool in Workflow: Unable to Pass File-Type Variables

### ISSUE THREAD

**Issue by bluefish-08** [langgenius/dify#11644]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I create a custom tool in Dify and use it in the workflow, it is unable to pass in a variable of the file type, which I need.
![image](https://github.com/user-attachments/assets/18771872-f1ec-4519-a3b2-8f0d4300a648)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by hjlarry** [comment]
seems you use a `File List` variable? how about connect a `list filter` node?

**Comment by bluefish-08** [comment]
> seems you use a `File List` variable? how about connect a `list filter` node?

i dont understand how to do

**Comment by hjlarry** [comment]
I can't reproduce your issue, please upload your dsl

**Comment by bluefish-08** [comment]
[dsl.zip](https://github.com/user-attachments/files/18138758/dsl.zip)
this is my dsl

**Comment by hjlarry** [comment]
![image](https://github.com/user-attachments/assets/0120c8cd-0eb1-48ec-9242-ad6f90213ac2)

it works

**Comment by bluefish-08** [comment]
i want use sys.files
![image](https://github.com/user-attachments/assets/0c91cdb6-b26c-4645-ab03-a144b7c01156)

**Comment by hjlarry** [comment]
add a list filter node,  it's an `Array[File]` variable, not `File`

**Comment by bluefish-08** [comment]
thank you,i think i know how to do

**Comment by bluefish-08** [comment]
![image](https://github.com/user-attachments/assets/8e1213a3-17f0-4c00-8cc8-7d198d0525f4)
![image](https://github.com/user-attachments/assets/6efba102-a5f9-471b-86e3-6428f3c3d871)
why
