### ISSUE TITLE
Iteration node with input array length>100 always fails saying 'Max submit count 100 of workflow thread pool reached'

### ISSUE THREAD

**Issue by kazuhisa-wada** [langgenius/dify#11668]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

The error 'ValueError: Max submit count 100 of workflow thread pool reached' easily happens if input to the iteration node is long to some extent. 

Example condition:
 - iteration node has parallel mode with maximum parallelism>= 2
 - input to the iteration node >=101
 - run the workflow, then terminates with error saying Max submit count 100 of workflow thread pool reached.
 
Please see captures.
![image](https://github.com/user-attachments/assets/a81ae487-8253-4043-895a-e7cfb61836c3)
![image](https://github.com/user-attachments/assets/9fcf7b90-0f2b-4520-a853-3bb52f4fe562)
![image](https://github.com/user-attachments/assets/60def1a3-d1f9-4ddc-83e6-db4ac83ed630)

This never happens for single thread mode.

Although I am not sure the role of max_submit_count, this behavior is obviously wired and should be enhanced so that all the thread is created simultaneously.

Attached is the very easy sample workflow.
[workflow.zip](https://github.com/user-attachments/files/18139742/workflow.zip)

### ✔️ Expected Behavior

Workflows should be successful even if input length is large.

### ❌ Actual Behavior

Input length to iteration node with parallel mode fails 100%.

**Comment by yihong0618** [comment]
yes max_submit_count is 100

**Comment by kazuhisa-wada** [comment]
Yes I know and it's too small. Let me change that configurable. I'll push the code change later.

**Comment by kazuhisa-wada** [comment]
also it's wired for this behavior for small parallelism case like 2. Why is it reasonable to create many of threadpool simultaneously?
