### ISSUE TITLE
How to customize an application's public access URL?

### ISSUE THREAD

**Issue by Davidwhw** [langgenius/dify#11675]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

As shown in the figure. When creating an application, a public access url with a random suffix is used. This makes the entire url difficult to remember and inconvenient to use. Can I customize this suffix to have a meaningful character?

![url with a random suffix](https://github.com/user-attachments/assets/077ce8d6-839d-426b-8510-caf5cc89664c)

Are there existing features that support my needs? 
Or tell me which programs or files I should focus on if I make the corresponding changes myself?
Look forward to any help and advice.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Sorry we don't have a plan for this.

**Comment by Davidwhw** [comment]
> Sorry we don't have a plan for this.
Can you provide an idea of what files and Settings I should focus on? I may be able to fulfill this requirement myself.

**Comment by crazywoola** [comment]
This is generated randomly by backend services, you can alter that function in this case.
