### ISSUE TITLE
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

### ISSUE THREAD

**Issue by bscz** [langgenius/dify#11688]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker ps -a
![image](https://github.com/user-attachments/assets/88e9a08d-d36d-4554-9309-16e3f517fa39)

exception1 None of PyTorch, TensorFlow >= 2.0, or Flax have been found.
![image](https://github.com/user-attachments/assets/18048ecf-de7c-4ebf-b19a-fbc618130a27)

exception2 502 Bad Gateway
![image](https://github.com/user-attachments/assets/c4300945-ca2b-457f-9f38-8da751562999)

### ❌ Actual Behavior

Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2024-12-16 07:22:18.710 INFO [MainThread] [utils.py:148] - Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-12-16 07:22:18.711 INFO [MainThread] [utils.py:160] - NumExpr defaulting to 8 threads.
[FATAL:partition_root.cc(863)] Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14)).
/entrypoint.sh: line 8:     7 Trace/breakpoint trap   (core dumped) flask upgrade-db

**Comment by crazywoola** [comment]
Please upgrade to v0.13.2 or v0.14.0. It might take some time to start the container when you migrating from older versions. This is a warning message as well.
