### ISSUE TITLE
Custome icon error : The requested resource isn't a valid image

### ISSUE THREAD

**Issue by kkjinping** [langgenius/dify#11693]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![QQ20241216-162710](https://github.com/user-attachments/assets/36636299-d45e-4ecc-a35a-571e892b3ec3)
![QQ20241216-162722](https://github.com/user-attachments/assets/4f3897af-bc74-4cee-87fe-27560abcd406)

**Comment by kkjinping** [comment]
It worked fine before version 0.14.

**Comment by crazywoola** [comment]
Can you try to upload the image again?
