### ISSUE TITLE
Create the knowledge failed

### ISSUE THREAD

**Issue by yuuufeng** [langgenius/dify#11691]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.10.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

New deployment and using Chinese. Knowledge -> Create Knowledge -> Import from file -> Next -> chunk Settings(Automatic),Index mode(High Quality) 

### ✔️ Expected Behavior

Create the knowledge successfully

### ❌ Actual Behavior

Create the knowledge failed
![rules](https://github.com/user-attachments/assets/0358893c-d57d-4def-aa43-731233219aca)
![traceback](https://github.com/user-attachments/assets/ff2d43e7-fa8f-4223-957d-2a8c23fd20aa)

**Comment by yihong0618** [comment]
can you offer your file(some data is enough) or the file ext?

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this persists.

**Comment by yuuufeng** [comment]
> can you offer your file(some data is enough) or the file ext?

just some test file  such as .txt 
[456.txt](https://github.com/user-attachments/files/18147728/456.txt)

**Comment by yuuufeng** [comment]
> Please upgrade to latest version to see if this persists.

I saw someone in discord had the same problem as me;
![image](https://github.com/user-attachments/assets/4931a389-f514-407d-bef0-1bb9933b4d05)
I looked at the latest version of the code and found that it had not been changed. I tried to change the code myself and then it worked.

**Comment by crazywoola** [comment]
Please feel free to open a pull request :)
