### ISSUE TITLE
All data in my team's workspace, which I subscribed to on an annual plan, has been reset.

### ISSUE THREAD

**Issue by MaikoKitamura** [langgenius/dify#11707]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

My entire workspace, which I've been paying for annually on a team plan, has been completely wiped clean. All settings and apps I created are gone.
When I looked into my billing history, I couldn't find any records, and the only option given was to update the plan.
Everything was working fine until yesterday, but now all my apps have vanished.
① What could have caused this?
② Will upgrading the plan again restore my lost apps and settings?

### ✔️ Expected Behavior

I would like to restore my account to its previous paid state.

### ❌ Actual Behavior

We are unable to assist you as you have already paid for an annual subscription.

**Comment by crazywoola** [comment]
Did you changed the workspace? Also please submit this report to support@dify.ai, we need your account email to take a look.

**Comment by MaikoKitamura** [comment]
@crazywoola 
No, I haven't made any changes to my workspace or login methods. 
I will try contacting support. Thank you for your assistance.
