### ISSUE TITLE
dify.ai/jp display bug

### ISSUE THREAD

**Issue by Winson-030** [langgenius/dify#11713]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

dify official web jp version

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![dify-web-bug](https://github.com/user-attachments/assets/57b699b0-55e0-4bff-8ae6-1a0860c101b6)

**Comment by crazywoola** [comment]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/b3dc0ba7-17a2-457b-a9f1-e972fff6eb06" />
I took a look at this can not see the duplicated logo.
