### ISSUE TITLE
Podcast audio generator fails, can't find "ffprobe"

### ISSUE THREAD

**Issue by shenhai-ran** [langgenius/dify#11714]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am use the example chatbot workflow `Notebook LLM by Dify.AI` and I have configured all the LLM and OpenAI TTS services. The generation of scripts works fine, but `Podcast audio generator` fails with the following error:
```
Error generating audio: [Errno 2] No such file or directory: 'ffprobe'
```
P.S.: sandbox version: 0.2.10

![image](https://github.com/user-attachments/assets/2af93604-58d4-4a27-8331-ed6dfff4dee1)

### ✔️ Expected Behavior

Generate audio files

### ❌ Actual Behavior

No file generated

**Comment by yihong0618** [comment]
you need to install ffmpeg in your local env!
the bot answer right.....I never thought it could be useful.....

**Comment by shenhai-ran** [comment]
@yihong0618 thanks for confirm. I am a bit confused. How can docker service access `ffmpeg` on my local host? I thought it needs to be installed in the Sandbox, as the bot said.... so it is not complete right

**Comment by yihong0618** [comment]
> @yihong0618 thanks for confirmation. I am a bit confused. How can docker service access `ffmpeg` on my local host? I thought it needs to be installed in the Sandbox, as the bot said.... so it is not complete right

https://github.com/langgenius/dify/pull/11768
