### ISSUE TITLE
Suggestions in English, although the message is in Chinese

### ISSUE THREAD

**Issue by yz00000000** [langgenius/dify#11723]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

Chat with the agent...
![image](https://github.com/user-attachments/assets/42900c36-e828-420d-8dfc-dd9fca7eb98c)

I think there is an issue with "SUGGESTED_QUESTIONS_AFTER_ANSWER_INSTRUCTION_PROMPT" in this code (https://github.com/langgenius/dify/blob/0.14.0/api/core/llm_generator/prompts.py), it should be written this.
`SUGGESTED_QUESTIONS_AFTER_ANSWER_INSTRUCTION_PROMPT = (
    "Please help me predict the three most likely questions that human would ask, "
    "and keeping each question under 20 characters.\n"
    "MAKE SURE your output is the SAME language as the Assistant's latest response"
    "You must answer in {language}, in a style that is clear and detailed in {language}."
    "The output must be an array in JSON format following the specified schema:\n"
    '["question1","question2","question3"]\n'
)`

### ✔️ Expected Behavior

Suggestions in Chinese

### ❌ Actual Behavior

Suggestions in English

**Comment by crazywoola** [comment]
Duplicated

**Comment by yz00000000** [comment]
@crazywoola 
Duplicated？ Two commits [https://github.com/langgenius/dify/commit/8cc9e683631e155e9c7c1c282e91f9933f2858ba](url) [https://github.com/langgenius/dify/commit/c013086e64033366d1c7baa84498c6ecfdf14965](url)     but the problem still exists.

**Comment by crazywoola** [comment]
By saying duplicated means this issue has been raised before for more than 1 times. Please search the existing issue. This is a known issue, currently we do not have a solution for it.
