### ISSUE TITLE
Using session variables in the workflow can cause the stream response to fail, and the reply node will only reply after LLM is fully generated

### ISSUE THREAD

**Issue by yg2024** [langgenius/dify#11725]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Using session variables in the workflow can cause the stream response to fail, and the reply node will only reply after LLM is fully generated

**Comment by crazywoola** [comment]
By the version number you provided, it seems you are not using a LLM node before the Answer node, I think this is the only way to generate streaming response.
We plan to support streaming to other node in v1.0 but not this version.
