### ISSUE TITLE
Upgrading to 0.14.0 broke the openai_api_compatible model provider connection

### ISSUE THREAD

**Issue by AugNSo** [langgenius/dify#11739]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

git pull
docker compose up -d

### ✔️ Expected Behavior

The previous version was 0.13.0 and the API worked.

### ❌ Actual Behavior

API Endpoint redacted for privacy.

[openai_api_compatible] Server Unavailable Error, HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://*.*.*.*:*/v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79e63d47eab0>: Failed to establish a new connection: [Errno 111] Connection refused')))

**Comment by crazywoola** [comment]
```
[openai_api_compatible] Server Unavailable Error, HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://...:*/v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79e63d47eab0>: Failed to establish a new connection: [Errno 111] Connection refused')))
```

According to the url you provided, I don't think we support this if you use older version or not.

```
http://host.docker.internal:11434
```

Try this instead.

**Comment by AugNSo** [comment]
> ```
> [openai_api_compatible] Server Unavailable Error, HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://...:*/v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79e63d47eab0>: Failed to establish a new connection: [Errno 111] Connection refused')))
> ```
> 
> According to the url you provided, I don't think we support this if you use older version or not.
> 
> ```
> http://host.docker.internal:11434
> ```
> 
> Try this instead.

Thanks for the reply, to make my question more clear, the model was deployed on another machine, and dify was able to connect the model from via API endpoint like http://62.200.100.5:12345/v1/chat/completion from 0.9.0 to 0.13.0.

**Comment by AugNSo** [comment]
> > ```
> > [openai_api_compatible] Server Unavailable Error, HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://...:*/v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79e63d47eab0>: Failed to establish a new connection: [Errno 111] Connection refused')))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > According to the url you provided, I don't think we support this if you use older version or not.
> > ```
> > http://host.docker.internal:11434
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Try this instead.
> 
> Thanks for the reply, to make my question more clear, the model was deployed on another machine, and dify was able to connect the model from via API endpoint like http://62.200.100.5:12345/v1/chat/completion from 0.9.0 to 0.13.0.

Update: I am able to connect to the API by unset the proxy on dify's host machine. Without doing so, even connecting the local xinference model using http://host.docker.internal:9997 returned an error.

**Comment by AugNSo** [comment]
pinpoint the problem to commit #11681, docker compose will read the system proxy env HTTP_PROXY and HTTPS_PROXY and in the case of HTTP_PROXY=127.0.0.1:7890, dify cannot access this endpoint. @crazywoola
