### ISSUE TITLE
The http requests in code node failed after upgrading to v 0.14.0

### ISSUE THREAD

**Issue by Halfknow** [langgenius/dify#11736]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Upgrading to version 0.14.0, the python code node to execute the requests code, the network error occur.

### ✔️ Expected Behavior

In the previous version from 0.8.0 to 0.13.2, the requests function in python code node works fine.

### ❌ Actual Behavior

Now in 0.14.0 version, the python code node to execute the http requests failed. The error message is below:

`Run failed: Failed to execute code, which is likely a network issue, please check if the sandbox service is running. ( Error: [Errno 111] Connection refused )`

**Comment by crazywoola** [comment]
If you are upgrading from older version, check the env settings suggested by the bot/
