### ISSUE TITLE
Persistent "Too many incorrect password attempts" lockout even after resetting credentials

### ISSUE THREAD

**Issue by skikkh** [langgenius/dify#11759]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Enter an incorrect password multiple times during login.
2. The error message "Too many incorrect password attempts. Please try again later." is displayed.
3. Use the Flask commands reset-email and reset-password to attempt to reset credentials.
4. After resetting, try logging in again.
5. The same "Too many incorrect password attempts" error message still appears, and you cannot log in.

### ✔️ Expected Behavior

After performing the reset actions (using reset-email and reset-password), the lockout should be cleared, allowing successful login without encountering the "Too many incorrect password attempts" error message.

### ❌ Actual Behavior

Even after performing the reset actions, the lockout persists indefinitely. The "Too many incorrect password attempts" message still appears, and the account cannot be accessed.

**Additional Information
A similar issue has been reported in [this discussion](https://github.com/langgenius/dify/discussions/10926).**

**Comment by crazywoola** [comment]
Try to remove things in the redis container.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/11775

**Comment by lvhuaizi** [comment]
您只需在 redis 中清算现金即可：
docker exec -it container-name redis-cli FLUSHAL

---------------

实测有用，给大佬点赞

**Comment by lin-nian** [comment]
thanks, it work

> you can simply clear the cash in redis: docker exec -it container-name redis-cli FLUSHALL

**Comment by sei-kou** [comment]
than you ,this save my day.
