### ISSUE TITLE
Unable to obtain URL for uploading images

### ISSUE THREAD

**Issue by Jaleel-zhu** [langgenius/dify#11769]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create file variable, unable to obtain the URL of the file
![image](https://github.com/user-attachments/assets/51dd04e0-b210-473c-9b53-84a3ffc868fe)
![image](https://github.com/user-attachments/assets/b6c80911-1a2f-47a8-8f21-0b1e997a96c8)
![image](https://github.com/user-attachments/assets/97644a78-6eaf-4c71-ad1b-dc3adff89172)

### ✔️ Expected Behavior

can obtain the URL of the file

### ❌ Actual Behavior

Unable to obtain URL for uploading images

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/discussions/10687
