### ISSUE TITLE
reset password failed

### ISSUE THREAD

**Issue by hsoftxl** [langgenius/dify#11775]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

lastest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker exec -it docker-api-1 flask reset-password

使用以上命令重置密码后， 登录报错

![image](https://github.com/user-attachments/assets/c93362b5-2b67-4094-af86-65a9dc1792be)

### ✔️ Expected Behavior

login

### ❌ Actual Behavior

fail tip

**Comment by crazywoola** [comment]
We use redis to check the expire time, you can connect to the redis container and run this command https://redis.io/docs/latest/commands/flushall/.

**Comment by shiliu2023** [comment]
这个问题处理的真费劲！何必如此！

**Comment by Milkboy131** [comment]
you can simply clear the cash in redis:
docker exec -it container-name redis-cli FLUSHALL

**Comment by uamyangel** [comment]
I'm concerned that using redis-cli FLUSHALL will delete all data and affect usage. You can use the method below to only clear locked user data.

```bash
docker exec -it docker-redis-1 sh
redis-cli
select 0
del login_error_rate_limit:xx@example.com
```
Replace ```xx@example.com``` with the actual email address.

![Image](https://github.com/user-attachments/assets/ff6b1faa-9944-49ba-a365-878e6aea85ed)
