### ISSUE TITLE
How canI support iframe or html in the answer box

### ISSUE THREAD

**Issue by yixin10709** [langgenius/dify#11777]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I searched the previous Issues and noticed that the LLM answer embedding iframe and html is not allowed, now I want to embed an interactive chart in the answer, possibly chartjs, how can I do this? Can you modify configurations that are not allowed? Now the presentation of the big model answers is very simple，I really want this feature

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
No you can not.

https://github.com/langgenius/dify/blob/284bb7ac71815223be440a83b77691ff1ff2ef60/web/app/components/base/markdown.tsx#L250
