### ISSUE TITLE
The model is qwen-plus. Dialog contains sensitive information (Server Unavailable Error, Failed to invoke model qwen-plus, status code: 500, message: Input data may contain inappropriate content), and then use this conversation_id to send any message will prompt you to contain sensitive information

### ISSUE THREAD

**Issue by ouguofeng** [langgenius/dify#11779]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![1734492488017](https://github.com/user-attachments/assets/ad0913f5-ba7b-43e7-b4b0-f7023fd50d8f)
When I use the api to have a conversation that contains sensitive information. The session id can no longer be used

The model I used was qwen-plus

### ✔️ Expected Behavior

I hope this conversation id has sensitive information that will allow me to continue using it. Dropping this session id will affect my context content

### ❌ Actual Behavior

/v1/chat-messages
{
    "inputs": {},
    "conversation_id": "4c990d67-5abd-4421-820f-44bcb30ebe73",
    "query": "亚洲有几个发达国家",
    "user": "2",
    "response_mode": "streaming"
}

**Comment by ouguofeng** [comment]
Well, thank you very much

**Comment by crazywoola** [comment]
If you turn on the llm memory switch, then it won't be removed until it moves to the start of the memory. In this case, you can not alter the memory in the web UI.
