### ISSUE TITLE
【classifier issue】 Run failed: [wenxin] Bad Request Error, The number of messages should be odd.

### ISSUE THREAD

**Issue by luciferYu** [langgenius/dify#11776]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I want to use a classifier to classify problems
but classifier always return “Run failed: [wenxin] Bad Request Error, The number of messages should be odd.“

following is my input
{
  "sys.query": "1+1=几？",
  "sys.files": [],
  "sys.conversation_id": "fdc4b4d2-ea19-4f4b-a29a-eb821277cb81",
  "sys.user_id": "6f3c4ffb-1b06-4aa2-860d-68f3fef96acb",
  "sys.dialogue_count": 0,
  "sys.app_id": "1d22e606-28d2-46ec-880f-36a465f80588",
  "sys.workflow_id": "904fc580-b948-4035-9403-fa7bbe39df3a",
  "sys.workflow_run_id": "1a80fe03-ece7-44b5-b6bf-c3ebee26d8af"
}

following is the screenshot

![image](https://github.com/user-attachments/assets/9f35fd32-b5e9-4c9d-baae-88fbae714b93)
![image](https://github.com/user-attachments/assets/43a65594-72b0-4f42-ab2f-ef96592f0ffa)
![issue01](https://github.com/user-attachments/assets/087ffada-f744-43aa-9925-695035e22343)
![issue02](https://github.com/user-attachments/assets/e3cf6fb4-ba6b-4080-8612-6418df7e0bf3)
![image](https://github.com/user-attachments/assets/171c61b1-b350-4f46-bec4-e914e7b59370)

### ✔️ Expected Behavior

I have set up two categories for Chinese language problems and math problems. When I input 1+1=what? I hope it can be classified as a mathematical problem

### ❌ Actual Behavior

It always raise an exception  that Run failed: [wenxin] Bad Request Error, The number of messages should be odd.“
![image](https://github.com/user-attachments/assets/6d921570-5ac9-4fe6-9701-fa9beb690942)

**Comment by luciferYu** [comment]
Hello dosu
          I noticed that this message cannot be odd, but I don't quite understand what message is?
I output the sys. query variable as input to the classifier at the start node. I see a selection model in the classifier node, set the classification. Afterwards, the variable class_name will be output to next node. But I don't know where the classifier node can control the parity of messages. Could you please tell me?

Best Regards

**Comment by luciferYu** [comment]
Hello dosu
          I noticed that this message cannot be odd, but I don't quite understand what message is?
I output the sys. query variable as input to the classifier at the start node. I see a selection model in the classifier node, set the classification. Afterwards, the variable class_name will be output to next node. But I don't know where the classifier node can control the parity of messages. Could you please tell me?

Best Regards

**Comment by luciferYu** [comment]
I have tried  to use gpt4-turbo model it worked, But baidu ERNIE model that didn't worked
![image](https://github.com/user-attachments/assets/39cc24aa-dd15-440f-90a2-8e258b4ba5d1)

**Comment by Cloud-Style** [comment]
So how did you solve this problem? I had a similar problem, bro @luciferYu

**Comment by jasonfish568** [comment]
Still encoutered the same problem.

**Comment by TingSty** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/6dc28862-3682-4fc3-89d3-e26b6e2739ad" />

as the picture show, modify add user role, and assistant role, assistant and system role can be blank
