### ISSUE TITLE
Retrieve Chunks from many Knowledge Bases

### ISSUE THREAD

**Issue by mryao199** [langgenius/dify#11772]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

curl --location --request GET 'https://api.dify.ai/v1/datasets/{dataset_id}/retrieve (https://docs.dify.ai/guides/knowledge-base/maintain-dataset-via-api#retrieve-chunks-from-a-knowledge-base)
just a dataset_id
i want to two dataset_id
how to do?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
No you can not. This should follow the practice of the RESTful API.
