### ISSUE TITLE
When starting v0.14.0 with Docker Compose, the docker-api-1 restart always

### ISSUE THREAD

**Issue by Jeffhop** [langgenius/dify#11788]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/99c42807-c517-4b19-8c07-b73adf7ba0e9)
![image](https://github.com/user-attachments/assets/26661fab-be79-4a0e-9254-350cc4f0744b)

### ✔️ Expected Behavior

how to fix it?

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/11534
https://github.com/langgenius/dify/pull/11535/files

You can add missing items in docker/.env, in you case it should be `CODE_EXECUTION_ENDPOINT=http://127.0.0.1:8194`

**Comment by Jeffhop** [comment]
> See #11534 https://github.com/langgenius/dify/pull/11535/files
> 
> You can add missing items in docker/.env, in you case it should be `CODE_EXECUTION_ENDPOINT=http://127.0.0.1:8194`

thanks,it works。

**Comment by orsenwork** [comment]
If we set CODE_EXECUTION_ENDPOINT to http://127.0.0.1:8194/, it will cause the sandbox to be unusable, leading to the failure of code execution and template conversion features. This error is due to the URL output by generate_docker_compose.py containing double quotes. To fix this issue, you only need to modify the code of the generate_shared_env_block function in that file, regenerate the docker_compose.yaml, and then reinstall:
def generate_shared_env_block(env_vars, anchor_name="shared-api-worker-env"):
    """
    Generates a shared environment variables block as a YAML string.
    """

    lines = [f"x-shared-env: &{anchor_name}"]

    for key, default in env_vars.items():
        # If default value is empty, use ${KEY:-}
        if default == "":
            lines.append(f" {key}: ${{{key}:-}}")
        else:
            # Remove possible quotes around the value
            if (default.startswith('"') and default.endswith('"')) or (
                default.startswith("'") and default.endswith("'")
            ):
                default = default[1:-1]

            # If default value contains special characters, wrap it in quotes
            if re.search(r"[:\s]", default):
                default = f'"{default}"'

            # Special handling for URL values to avoid adding extra quotes
            if re.match(r"^https?://", default):
                default = default.strip('"').strip("'")

            lines.append(f" {key}: ${{{key}:-{default}}}")

    return "\n".join(lines)
