### ISSUE TITLE
When I update to 0.14.0, it prompts an Internal Server Error

### ISSUE THREAD

**Issue by Qinz-shao** [langgenius/dify#11785]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker pull langgenius/dify-api:0.14.0
docker push harbor-devops.xxx.cn/ai/dify-api:0.14.0

I update to 0.14.0
then open my web

### ✔️ Expected Behavior

The previous version was 0.13.0 and its worked.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/0fd7b7ef-2258-4d30-8e8f-1cec033b5961)
![image](https://github.com/user-attachments/assets/17f01063-0147-44a3-9708-330dc3bde1cd)

**Comment by crazywoola** [comment]
This should be fixed in https://github.com/langgenius/dify/pull/11754

**Comment by laipz8200** [comment]
If you're using AWS managed IAM Role for S3, it should be fixed in #11754, otherwise please check if your private key still in your storage directory.
