### ISSUE TITLE
smtp send email not working

### ISSUE THREAD

**Issue by kbels** [langgenius/dify#11798]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

This is my configuration file：
ENV:

```
# Mail type, support: resend, smtp
MAIL_TYPE=smtp

# Default send from email address, if not specified
MAIL_DEFAULT_SEND_FROM=

# API-Key for the Resend email provider, used when MAIL_TYPE is `resend`.
RESEND_API_KEY=XXXXXXX

# SMTP server configuration, used when MAIL_TYPE is `smtp`
SMTP_SERVER=smtp.qq.com
SMTP_PORT=465
SMTP_USERNAME=XXXXXX@qq.com
SMTP_PASSWORD=XXXXXXX
SMTP_USE_TLS=false
SMTP_OPPORTUNISTIC_TLS=false
SMTP_ENABLE_SSL=true


Yaml:
SMTP_SERVER: ${SMTP_SERVER:-}
  SMTP_PORT: ${SMTP_PORT:-465}
  SMTP_USERNAME: ${SMTP_USERNAME:-}
  SMTP_PASSWORD: ${SMTP_PASSWORD:-}
  SMTP_USE_TLS: ${SMTP_USE_TLS:-false}
  SMTP_OPPORTUNISTIC_TLS: ${SMTP_OPPORTUNISTIC_TLS:-false}
```

**Comment by crazywoola** [comment]
Duplicated, please set the `MAIL_DEFAULT_SEND_FROM ` and you will be able to send the email.
