### ISSUE TITLE
Out of range float values are not JSON compliant: nan

### ISSUE THREAD

**Issue by luoyutao03** [langgenius/dify#11792]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I encountered this error while uploading the document to the knowledge base:Out of range float values are not JSON compliant: nan

![image](https://github.com/user-attachments/assets/24c2c874-9595-4240-b0bc-0fa4a2f836eb)
![image](https://github.com/user-attachments/assets/cb17fe99-8903-4d6e-93fa-127a8db13aca)

**Comment by crazywoola** [comment]
Can you provide the container logs of the api and worker.
