### ISSUE TITLE
When arranging the intelligent agent again, the TTS function cannot be found in the functional module

### ISSUE THREAD

**Issue by wangguichao** [langgenius/dify#11800]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/5b895adf-0710-48bd-b742-2c8d280baa1e)
TTS function is missing in the functional module

**Comment by crazywoola** [comment]
Please check the default system model settings.
