### ISSUE TITLE
webapp-conversation set inputs have 500 error

### ISSUE THREAD

**Issue by xs818818** [langgenius/dify#11811]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![2024-12-18 20-48-47屏幕截图](https://github.com/user-attachments/assets/a7a741cf-b693-4680-9779-ea91d1b72278)
![2024-12-18 20-48-58屏幕截图](https://github.com/user-attachments/assets/eec3acae-9c0c-4dc6-8f50-270c8a9b50a9)

**Comment by crazywoola** [comment]
Please provide the logs of the web page.

**Comment by xs818818** [comment]
![2024-12-19 16-37-04屏幕截图](https://github.com/user-attachments/assets/24e0f4ef-e1da-410e-a793-2105d53cdc79)
![2024-12-19 16-37-32屏幕截图](https://github.com/user-attachments/assets/c458dc4f-512b-4064-a468-e7c17b915940)

**Comment by crazywoola** [comment]
It seems you are running the project with source code? But you labeled with docker, so I am a little bit confused here. Can you clarify this?
The error code 502 suggest the backend does not start correctly, please check the backend logs.
