### ISSUE TITLE
Load files as a user input in an Agent

### ISSUE THREAD

**Issue by eliaccess** [langgenius/dify#11813]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Hi everyone,

Quick question. I want to create a chatbot that calls tools (so an Agent), but I cannot see in the documentation / interface how to allow the users to upload files, for instance a report that the agent will analyze using tools. Any idea / guideline to reach this goal ?

I am using the cloud version, and created an Agent from the Studio.

Thanks !

**Comment by crazywoola** [comment]
https://docs.dify.ai/guides/workflow/node/doc-extractor

**Comment by crazywoola** [comment]
See these docs
- https://docs.dify.ai/guides/workflow/node/doc-extractor
- https://docs.dify.ai/workshop/intermediate/article-reader

**Comment by eliaccess** [comment]
Hey @crazywoola,

I am talking about Agents, not workflows / chatflows. This type:
<img width="211" alt="Capture d’écran 2024-12-19 à 09 54 19" src="https://github.com/user-attachments/assets/9917a8ac-f656-4a74-9a89-b8fee8b9d3f4" />

I want the user to be able to upload some files there, for instance CSV. How can I do so?

**Comment by liyuinfo-wl** [comment]
> Hey @crazywoola (and @dosu ),
> 
> I am talking about Agents, not workflows / chatflows. This type: <img alt="Capture d’écran 2024-12-19 à 09 54 19" width="211" src="https://private-user-images.githubusercontent.com/39032467/397302445-9917a8ac-f656-4a74-9a89-b8fee8b9d3f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NTYyODgsIm5iZiI6MTczNjc1NTk4OCwicGF0aCI6Ii8zOTAzMjQ2Ny8zOTczMDI0NDUtOTkxN2E4YWMtZjY1Ni00YTc0LTlhODktYjhmZWU4YjlkM2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDA4MTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NDdiYWI5ZTY0MzQ4MWFmZWI4MTM1MDQ3ODQ5ZTBkNjVhZWVhMmNjYjEyZGY4Njc2NWQ2MzJkNWZjMmY2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bQbWx8gZLH59Anjahkd_eqX3liYm87JWUP1rGX1-5dc">
> 
> I want the user to be able to upload some files there, for instance CSV. How can I do so?

I also want to know

**Comment by crazywoola** [comment]
@eliaccess 

https://github.com/langgenius/dify/issues/12680#issuecomment-2586488079
