### ISSUE TITLE
UI remove connection between blocks

### ISSUE THREAD

**Issue by horw** [langgenius/dify#11821]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello, I have not found an easy way to remove the connection between blocks. I think clicking on the connection should open a dropdown where I can remove it.

![image](https://github.com/user-attachments/assets/6361fa5a-a01b-41ee-8910-6cc7bafb3ff9)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You just need to click and select and use the delete key. That's should be simple enough.

**Comment by horw** [comment]
> You just need to click and select and use the delete key. That's should be simple enough.

  You're right, it works, but how was I supposed to know that 'delete' button would work?

![image](https://github.com/user-attachments/assets/735df6f1-face-4c30-aeef-54f17999817d)
