### ISSUE TITLE
I modified the key for silicon-based flow, and as a result, an error occurred.

### ISSUE THREAD

**Issue by wurenxiaozu** [langgenius/dify#11844]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/f167c59f-d000-417d-bc33-986b30a7443b)

nginx log：
101.47.14.176 - - [19/Dec/2024:11:24:55 +0000] "POST /console/api/workspaces/current/model-providers/siliconflow HTTP/1.1" 400 106 "https://aitrain.uat.bloomage.com/apps" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"

I removed the original key and intended to replace it with a new one. The removal was successful, but I am unable to add the new key.

### ✔️ Expected Behavior

To resolve this issue.

### ❌ Actual Behavior

I removed the original key and intended to replace it with a new one. The removal was successful, but I am unable to add the new key.

**Comment by wurenxiaozu** [comment]
I am certain that the key is not at fault and it can be used normally.
 
curl --request POST \
>   --url https://api.siliconflow.cn/v1/chat/completions \
>   --header 'Authorization: Bearer sk-uihjunjsldlgvcjdvhacktatqqrlt*****************' \
>   --header 'Content-Type: application/json' \
>   --data '{
>   "model": "deepseek-ai/deepseek-vl2",
>   "messages": [
>     {
>       "role": "user",
>       "content": [
>         {
>           "type": "image_url",
>           "image_url": {
>             "url": "https://sf-maas-uat-prod.oss-cn-shanghai.aliyuncs.com/dog.png",
>             "detail": "auto"
>           }
>         }
>       ]
>     }
>   ],
>   "stream": false,
>   "max_tokens": 512,
>   "stop": [
>     "null"
>   ],
>   "temperature": 0.7,
>   "top_p": 0.7,
>   "top_k": 50,
>   "frequency_penalty": 0.5,
>   "n": 1,
>   "response_format": {
>     "type": "text"
>   }
> }'
{"id":"0193deb5e39125e3350779d69fed3195","object":"chat.completion","created":1734608282,"model":"deepseek-ai/deepseek-vl2","choices":[{"index":0,"message":{"role":"assistant","content":"What breed of dog is this?"},"finish_reason":"stop"}],"usage":{"prompt_tokens":2024,"completion_tokens":7,"total_tokens":2031},"system_fingerprint":""}

**Comment by wurenxiaozu** [comment]
![image](https://github.com/user-attachments/assets/2b51705a-7ad5-47e0-bff4-3313d475b02a)
![image](https://github.com/user-attachments/assets/71ddca9e-8c21-477b-a59e-afcc3a1ecb73)
I tried adding the models one by one manually, and it worked unexpectedly. However, setting the key for the entire setup still fails.

**Comment by yihong0618** [comment]
fix 
https://github.com/langgenius/dify/pull/11847

**Comment by JiXia830** [comment]
have you ever solved it?
i have the same problem

**Comment by yihong0618** [comment]
> have you ever solved it? i have the same problem

yes update your version is fine

**Comment by JiXia830** [comment]
> > have you ever solved it? i have the same problem
> 
> yes update your version is fine

佬，是更新dify版本就可以了吗？我是docker部署的dify，硅基流动模型供应商的apikey设置报错和您一样，但是我添加硅基流动部分模型又比较顺利

**Comment by yihong0618** [comment]
> > > have you ever solved it? i have the same problem
> > 
> > 
> > yes update your version is fine
> 
> 佬，是更新dify版本就可以了吗？我是docker部署的dify，硅基流动模型供应商的apikey设置报错和您一样，但是我添加硅基流动部分模型又比较顺利

just update the code from that commit and restart docker is also fine

**Comment by tuhao1020** [comment]
I have the same issue even I use the latest docker image 0.15.3
