### ISSUE TITLE
Failure to Upload Files with Specified Extensions in Custom File Types

### ISSUE THREAD

**Issue by spr-y** [langgenius/dify#11841]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Specify a single file in the input field of the start node, and set the extension to ".c" in other file types.
2. Set the file upload type to local.
![image](https://github.com/user-attachments/assets/32315f5f-ceb5-42da-a158-3a1f5227a25e)

3. Start the workflow and specify a local C language source file as the input file.

### ✔️ Expected Behavior

The C language source file should upload successfully.

### ❌ Actual Behavior

An error stating "File extension not supported" occurs, preventing the upload.
![image](https://github.com/user-attachments/assets/1e766f10-740a-4f44-a91a-a441bab2dc99)

The direct cause is that the getFileExtensionfunction (dify/web/app/components/base/file-uploader/utils.ts) prioritizes obtaining the extension from the MIME type. 
On the problematic PCenvironment (Windows 10), the MIME type for *.c was set to "text/plain". As a result, the file extension becomes ".txt" instead of ".c", causing isAllowedFileExtension to return false and triggering the error.

This issue doesnot occur on PCs where the MIME type for *.c is not set.

To resolve this, change the implementation of the getFileExtension function to retrieve from the file name if there's an extension and from the MIME type if there's not. 
Since the MIME type of local files is prone to differences depending on each user's environment, it is better to prioritize the file name extension. 
However, as the extent of the impact is unknown, this is being registered as an issue.

**Comment by spr-y** [comment]
Hello @dosu, 
I believe that fix will solve the problem. 
Unfortunately, I don't have a development environment, so I can't verify it. 
Is there anyone who can check?

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this persists.
