### ISSUE TITLE
I want my workflow to run once every day at 9 am. But I didn't see such a function.How can I do it?

### ISSUE THREAD

**Issue by weiweimaodetuzi** [langgenius/dify#11846]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Create a complete workflow
2. Let it run automatically at 9 am every day

### ✔️ Expected Behavior

Let a complete workflow run automatically at 9 am every day

### ❌ Actual Behavior

But I didn't see such a function

**Comment by crazywoola** [comment]
We do not have this feature yet.  But you could try things like this https://github.com/langgenius/dify-docs/pull/411.
Please use a discussion for questions.
