### ISSUE TITLE
Does the Knowledge Retreival + ChatFlow support question completion?

### ISSUE THREAD

**Issue by hepburnalex** [langgenius/dify#11867]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I use Knowledge Retreival + ChatFlow for Q&A, I found that Dify did not understand my question based on the chat history, but directly searched the knowledge base according to my question.
For example, I first asked about the technical architecture of a product, and then asked about the price. Dify would directly search the knowledge base for the prices of all products, rather than the price of the product I had previously asked about.
![屏幕截图 2024-12-20 101704](https://github.com/user-attachments/assets/cd4f9e1f-b0ab-4fe8-9b01-235a2b4f6059)

### ✔️ Expected Behavior

Before searching the knowledge base, Dify can automatically complete the question based on the chat history.

### ❌ Actual Behavior

Dify directly searches the knowledge base according to the user's questions

**Comment by crazywoola** [comment]
Chatflow will be executed after you posting a question each time, if you want to ask questions based on previous answer, you need to use.a question classifier and turn on the memory to distinguish the question is old or not and then you need to use if/else node to determine whether you should ask based on that.
