### ISSUE TITLE
SSL error without proxy on self hosted dify

### ISSUE THREAD

**Issue by lbbc1117** [langgenius/dify#11963]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Docker)

#### With proxy on the host machine:
![image](https://github.com/user-attachments/assets/61c6e42c-85cf-4bd5-98a1-50bac58dbc2e)
![image](https://github.com/user-attachments/assets/b71aaf55-2895-487d-9477-92eca28a7ede)

---------

#### Without proxy on the host machine:
![image](https://github.com/user-attachments/assets/9e012fa0-6ead-41fe-85fe-6e825be4d000)
![image](https://github.com/user-attachments/assets/479f1fe6-5b01-4186-bd46-32946bbc8ae4)

### ✔️ Expected Behavior

network be ok

### ❌ Actual Behavior

its blocking EVERY request

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/11906
Duplicated https://github.com/langgenius/dify/issues/11839
Duplicated https://github.com/langgenius/dify/issues/11739

**Comment by lbbc1117** [comment]
> Fixed in #11906 Duplicated #11839 Duplicated #11739

Reverting HTTP proxy settings as mentioned in #11906 not solving this issue

**Comment by lbbc1117** [comment]
It looks like a SSL issue, not proxy

**Comment by dingzhencong** [comment]
解决了吗？我也遇到了同样的问题。
