### ISSUE TITLE
The iterated item needs to be used as the body parameter of http

### ISSUE THREAD

**Issue by Vampxgg** [langgenius/dify#11983]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![1711a58e-54c4-4405-aa41-d487b41da435](https://github.com/user-attachments/assets/63f252b6-1a3f-486d-b2ad-bec445bd34f4)
I need to pass the iterated item as the body parameter of http.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
The body section accepts string only. Please do not forget add `"x[item]"`, this is not a valid json as well.
