### ISSUE TITLE
0.13.0 can not show dialogue in browser

### ISSUE THREAD

**Issue by happyallday** [langgenius/dify#11987]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

it's work fine when i use Firecrawl to download web Knowledge base，and not work anymore,charge os and browser not work too，could someboy help
![pic](https://github.com/user-attachments/assets/cb69ea06-bcef-4f7a-b19e-cdd87025f3d3)

**Comment by crazywoola** [comment]
The provided image does not container helpful information, I suggest you can upgrade to latest version to see if this works.

**Comment by happyallday** [comment]
thanks，i think i found the problem ，i delete  the web Knowledge base download by Firecrawl,everything be fine
