### ISSUE TITLE
Too many incorrect password!!!!

### ISSUE THREAD

**Issue by shiliu2023** [langgenius/dify#11986]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

lasted

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm using Docker to run Dify and I got the password wrong a few times and it's giving me this error "Too many incorrect password attempts. Please try again later."  Can anyone help me resolve it?

### ✔️ Expected Behavior

I want login

**Comment by crazywoola** [comment]
Duplicated
