### ISSUE TITLE
After upgrading Dify to version 014.1, Gemini 1.5 is still unable to parse videos.

### ISSUE THREAD

**Issue by hw872715125** [langgenius/dify#11980]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

​​
![img_v3_02hr_40a61b40-6707-46cd-9275-e93b9b0d944g](https://github.com/user-attachments/assets/3dd5d7e1-a8ca-45a2-8da5-b3c88e11ef4c)

### ✔️ Expected Behavior

Gemini 1.5 can read and parse video files for slicing.

### ❌ Actual Behavior

Gemini 1.5 still cannot read videos.

**Comment by hw872715125** [comment]
Why was 11590 directly closed? It’s clearly not addressing the same issue, is it?

**Comment by hjlarry** [comment]
use  `user prompts`  to insert video files,  the  `system prompts` will ignore all other type of files, only accept text

**Comment by crazywoola** [comment]
Some models just do not have `system` for example claude series and o1 series.

**Comment by hw872715125** [comment]
I attempted to insert a video file in the user prompts, but it still cannot be read. How can I correctly read the video file? @crazywoola @hjlarry 
![image](https://github.com/user-attachments/assets/951b44c6-3c46-4f45-863b-9ce46317d9bb)

**Comment by hjlarry** [comment]
you use the vertex cloud,  but I only add this features in gemini

**Comment by hw872715125** [comment]
> 你使用顶点云，但我只在 gemini 中添加了这个功能

Then which one should I choose? Please let me know, thank you. @hjlarry 
![image](https://github.com/user-attachments/assets/d9098aa5-f010-42ab-9ef6-a61750d534ca)

**Comment by hjlarry** [comment]
![image](https://github.com/user-attachments/assets/679f7b70-e216-4dce-9381-41dac88b593e)

**Comment by hw872715125** [comment]
> ![image](https://private-user-images.githubusercontent.com/25834719/398084904-679f7b70-e216-4dce-9381-41dac88b593e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzk2MTcsIm5iZiI6MTczNDkzOTMxNywicGF0aCI6Ii8yNTgzNDcxOS8zOTgwODQ5MDQtNjc5ZjdiNzAtZTIxNi00ZGNlLTkzODEtNDFkYWM4OGI1OTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MzUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNDVhOGY0OWM3NDE3MmQ3ODI1NGI2ZWEwNDZhN2JhYWZlMmY3ZjRjYjAwN2Y4MmFhN2VmMjNkZTgxZjg2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fOaQizyCWexj-FVm1sS-e4nGrDakPE43IQIlT8Nw5V4)

I haven't integrated Gemini 2.0 Flash Exp yet.
When using dify version 0.11, the Gemini 1.5 Flash 002 model was able to read video files and I was continuously using it. However, after upgrading the dify version, it stopped working. Could you please help me check this issue? @hjlarry

**Comment by hjlarry** [comment]
each gemini models can read video files.  But in dify 0.11,  it's impossible to read videos.

**Comment by hw872715125** [comment]
> each gemini models can read video files. But in dify 0.11, it's impossible to read videos.

When will other Gemini models also be able to read video files? @hjlarry

**Comment by hjlarry** [comment]
you mean vertex?  I haven't got a key,  you can submit a PR to support it
