### ISSUE TITLE
The content of the external knowledge base recalled by Dify is inconsistent with the original content of the external knowledge base.

### ISSUE THREAD

**Issue by ShenPW** [langgenius/dify#11992]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use RAGflow to create an external knowledge base. Use Dify to connect to the external knowledge base and recall the retrieved documents.

### ✔️ Expected Behavior

The content recalled by Dify should be exactly the same as the content in RAGflow.

### ❌ Actual Behavior

![screenshot-20241223-143926](https://github.com/user-attachments/assets/b9417e44-7767-4efe-826b-8560bf33dfec)

The actual content does not match, and there are the following problems:
1 Missing characters: For example, the content in RAGflow is 'description', while in Dify it is 'descript'.
2 Capital letters become lowercase.
3 Word segmentation occurs. Spaces appear between words.

**Comment by crazywoola** [comment]
> The issues you're experiencing with content discrepancies between Dify and the external knowledge base in RAGflow could be related to the text processing steps Dify uses. Dify performs text chunking and cleaning, which might lead to changes in the text format, such as missing characters, changes in capitalization, and word segmentation [[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/knowledge-base/create-knowledge-and-upload-documents.md).

**Comment by ShenPW** [comment]
> > The issues you're experiencing with content discrepancies between Dify and the external knowledge base in RAGflow could be related to the text processing steps Dify uses. Dify performs text chunking and cleaning, which might lead to changes in the text format, such as missing characters, changes in capitalization, and word segmentation [[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/knowledge-base/create-knowledge-and-upload-documents.md).

When linking to an external database, there is no place where data cleaning and chunk segmentation strategies can be selected. Everything is processed automatically.
My version is 0.11.0. Does a higher version support data - cleaning and - segmentation strategies?
