### ISSUE TITLE
Add a Component for Sub-Workflows as Independent Applications

### ISSUE THREAD

**Issue by EmiyaredA** [langgenius/dify#12007]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I was trying to design a complex workflow where some steps needed to be handled independently as smaller sub-workflows. However, Dify currently does not support adding sub-workflows that can function as standalone applications. It was frustrating because I had to manually manage these sub-workflows outside of the main workflow, which disrupted the modularity and scalability of the project.
Adding support for sub-workflows as components in the main workflow would make it easier to structure and manage complex processes. Additionally, having each sub-workflow open as an independent application would allow for better isolation and reusability across projects.

### 2. Additional context or comments

This feature could significantly improve modularity and organization for larger workflows. It would also align well with use cases where different teams need to handle specific parts of the workflow independently.
For example:
- Sub-workflow components could inherit input/output parameters from the main workflow but function as standalone processes.
- The ability to "open" a sub-workflow as an independent application would allow for easier testing, debugging, and reuse.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I think we do have sub-workflows here.

https://docs.dify.ai/guides/workflow/node/tools#publishing-workflow-applications-as-tools

You just need to publish existing workflow as a tool and use it in the main workflow.
