### ISSUE TITLE
Stop Streaming in API

### ISSUE THREAD

**Issue by Namec999** [langgenius/dify#12018]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Sometimes, the LLM stuck and keep sending the same Text several times

i am wondering if i can implement a STOP feature like in the Dify APP UI, to stop the streaming or send a kill signal to the workflow

**Comment by crazywoola** [comment]
Please use a right template for issue reporting.

**Comment by Namec999** [comment]
sorry i will
