### ISSUE TITLE
llama3.2 error when use images: "Doubao "Query or prefix prompt is too long“ error #4452"

### ISSUE THREAD

**Issue by FingerLiu** [langgenius/dify#12010]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. run ollama locally
2. config llama3.2 11b

<img width="646" alt="image" src="https://github.com/user-attachments/assets/18b3c976-a6a9-4c43-b8ee-3355645d4718" />

3. try chat with image

### ✔️ Expected Behavior

This should explain the image.

### ❌ Actual Behavior

This will give me the error if I upload image.
```
Query or prefix prompt is too long, you can reduce the prefix prompt, or shrink the max token, or switch to a llm with a larger token limit size.
```

I've search the code, and I guess there is something wrong when calculating prompt_tokens for ollama(maybe added base64 of image when calculating prompt_tokens)?

<img width="837" alt="image" src="https://github.com/user-attachments/assets/4a5bbafc-afb3-49f4-a953-ba59c357ba80" />

**Comment by crazywoola** [comment]
Images will be treated as base64 strings, this is a duplicated issue.
