### ISSUE TITLE
qdrant connection issue

### ISSUE THREAD

**Issue by akashengine** [langgenius/dify#12022]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Not able to connect with qdrant deployed in another instance, Tried to change the values in .env file but still getting the error.

**Comment by akashengine** [comment]
I have reverse proxied and the endpoint is a plain URL without any ports for qdrant deployment

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/488e3c3d565434bb6988d3d2120f0dfa9cb7fa4b/docker/ssrf_proxy/squid.conf.template
