### ISSUE TITLE
The administrator adds the user directly, rather than using the user after confirmation

### ISSUE THREAD

**Issue by zhengdechang** [langgenius/dify#12033]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When accessing the dify service, I have other user fields that need to be customized. Now we need to add, delete, modify and check the user of dify. This way I can manage users and still use dify normally

### 2. Additional context or comments

.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This should be an enterprise feature, I think you can contact business@dify.ai regarding this FR.
