### ISSUE TITLE
Version: 0.8.3 get workflow_log, keyword is useless when using Chinese characters

### ISSUE THREAD

**Issue by thisisagreatname** [langgenius/dify#12039]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

version:
![image](https://github.com/user-attachments/assets/1a7cd8e3-15a8-46b3-92d3-a1698a80cc10)

![image](https://github.com/user-attachments/assets/c340926c-b3f0-45e3-8dfc-a39013bb46b0)

the Chinese keyword, doesn't return anything:
![image](https://github.com/user-attachments/assets/cec1e20e-4f9e-45bf-b4d6-7a76c0ac5250)
without Chinese:
![image](https://github.com/user-attachments/assets/35bb3fdf-c425-4ea1-adc1-eb5a7abd14a6)

### ✔️ Expected Behavior

return the logs contain my keyword

### ❌ Actual Behavior

return nothing

**Comment by crazywoola** [comment]
Please upgrade to latest version, the version is outdated.
