### ISSUE TITLE
siliconflow 的netease-youdao/bce-reranker-base_v1模型提示添加成功但功能没开启

### ISSUE THREAD

**Issue by qikong333** [langgenius/dify#12040]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

按照正常流程添加siliconflow模型，提示是添加成功的，但模型列表里面启动不了
<img width="533" alt="image" src="https://github.com/user-attachments/assets/e2cb5d31-8a2f-41a5-a755-632f18fe7ceb" />

**Comment by crazywoola** [comment]
Please use English to report bugs.
