### ISSUE TITLE
/chat-message：400 invalid_param file is required in input form

### ISSUE THREAD

**Issue by XUANYUANRuins** [langgenius/dify#12049]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

this is postman test,but it fail:
![企业微信截图_20241224190216](https://github.com/user-attachments/assets/1eda1f8b-246d-46c1-8e33-7b689750ed5e)

The local test is successful, but an error is occured when it is published as an API call
I can't find which param is missing

### ✔️ Expected Behavior

give me correct response

### ❌ Actual Behavior

exception

**Comment by XUANYUANRuins** [comment]
I have no file to upload，but it's occured like this.

**Comment by TinsFox** [comment]
Which version are you in? When I was in v0.14.2, it could be an empty array or null.

API url is `${domain}/api/chat-messages`

I noticed that your API is prefixed with v1. Did you make any changes?

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/7df1469f-3ccb-4703-ac69-1de34e7abefc" />

**Comment by crazywoola** [comment]
You need to check the orchestration page to see if you have define a variable with `File` type.

**Comment by XUANYUANRuins** [comment]
> Which version are you in? When I was in v0.14.2, it could be an empty array or null.您使用的是哪个版本？当我在 v0.14.2 中时，它可能是一个空数组或 null。
> 
> API url is `${domain}/api/chat-messages`API 网址为 `${domain}/api/chat-messages`
> 
> I noticed that your API is prefixed with v1. Did you make any changes?我注意到您的 API 以 v1 为前缀。您做了什么更改吗？
> 
> <img alt="image" width="1067" src="https://private-user-images.githubusercontent.com/33956589/398408948-7df1469f-3ccb-4703-ac69-1de34e7abefc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwODgyOTUsIm5iZiI6MTczNTA4Nzk5NSwicGF0aCI6Ii8zMzk1NjU4OS8zOTg0MDg5NDgtN2RmMTQ2OWYtM2NjYi00NzAzLWFjNjktMWRlMzRlN2FiZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAwNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYTM5Mjg1ZTkwNTExMzY1Y2U4YWEwYjkwZTQ3YWZiNjk2ODEzOGNmOThhZGM5NWEzZGYyNWZiMzE5OWU4YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o4mgOLCqRfK3xcHzw66xX1FLm1-ZV1AjT4NLLKi-lH4">

Yet,I've got the reason why.  it's version is 0.13.2. I found the page showed API url is start with '/v1'.but actually start with '/api'.
TKS,friend~

**Comment by macheng1** [comment]
<img width="663" height="381" alt="Image" src="https://github.com/user-attachments/assets/4ff34a6b-2032-4f19-9f5c-5cb0ac1fba48" />我也是出现一下莫名的报错  请求参数都是对应的

**Comment by badshahlewani** [comment]
101902
