### ISSUE TITLE
When searching for apps in the studio interface, it is not possible to input Chinese characters.

### ISSUE THREAD

**Issue by Moiyu1998** [langgenius/dify#12050]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When entering Chinese characters in the search box, the input method cannot remain active and the page automatically refreshes, making it impossible to input Chinese. Since the page refreshes automatically and there are no error messages, it's not possible to provide a screenshot. However, this issue has been present for several versions.Please verify and resolve this issue.

**Comment by TinsFox** [comment]
Can you provide a screen recording of the complete process? I can't reproduce it in v0.14.2. Is there something wrong with my operation? If there is a complete enough screen recording, it will be easier to locate the problem. In fact, I didn't even get the steps to reproduce clearly.

https://github.com/user-attachments/assets/57dacdd9-9c35-4680-985e-b37346de6174

**Comment by crazywoola** [comment]
We might have a similar fix #11907 related to dataset in v0.14.2

**Comment by Moiyu1998** [comment]
https://github.com/user-attachments/assets/5927608b-b867-4144-8edc-6400d6cb70c0
