### ISSUE TITLE
TTS is Not Enabled Error when text-to-speech feature test

### ISSUE THREAD

**Issue by kevintsai1202** [langgenius/dify#12059]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I configure the text-to-speech feature and press play, the message "TTS is not enabled" appears. However, I have already set the OpenAI TTS model in the configuration.

![圖片](https://github.com/user-attachments/assets/2f6e5d31-3c7f-4fbf-9fec-66681c3fc89b)

![圖片](https://github.com/user-attachments/assets/17f6380e-2dc7-41c5-bba8-33592382861f)

**Comment by kevintsai1202** [comment]
@dosu This can only be used during an HTTP call. The current issue lies in the configuration.

> I found a similar issue that might help you resolve the "TTS is not enabled" error. The error typically indicates that the Text-to-Speech (TTS) feature is not activated in your application's configuration. To resolve this, ensure that the TTS feature is enabled in your configuration file. Here's a general approach:我發現了一個類似的問題，可能有助於你解決「TTS 未啟用」錯誤。這個錯誤通常表示你的應用程式配置中未啟用文字轉語音（TTS）功能。要解決這個問題，請確保在你的配置檔案中啟用 TTS 功能。以下是一般的做法：
> 
>     1. Check your application's configuration file and look for the `text_to_speech` section.檢查您的應用程式的配置檔案，並尋找 `text_to_speech` 區段。
> 
>     2. Ensure that the `enabled` key is set to `True`. Your configuration should look something like this:確保 `enabled` 鍵被設置為 `True` 。您的配置應該看起來像這樣：
>        ```python
>        config = {
>            "text_to_speech": {
>                "enabled": True,
>                "voice": "default_voice",  # Optional: specify the voice
>                "language": "en"           # Optional: specify the language
>            }
>        }
>        ```
> 
> 
> Additionally, if you are using OpenAI TTS, make sure that `FFmpeg` is installed on your system, as it is required for the TTS functionality to work properly [[1]](https://github.com/langgenius/dify/discussions/7656)[[2]](https://github.com/langgenius/dify/issues/11263).此外，如果您正在使用 OpenAI TTS，請確保您的系統上已安裝 `FFmpeg` ，因為這是 TTS 功能正常運作所需的 [[1]](https://github.com/langgenius/dify/discussions/7656) [[2]](https://github.com/langgenius/dify/issues/11263) 。
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu.要繼續與 Dosu 對話，請提及。_
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/717e858a-3f0d-4a04-ade9-b0885078b873?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/717e858a-3f0d-4a04-ade9-b0885078b873?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/717e858a-3f0d-4a04-ade9-b0885078b873?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/717e858a-3f0d-4a04-ade9-b0885078b873?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/717e858a-3f0d-4a04-ade9-b0885078b873?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/717e858a-3f0d-4a04-ade9-b0885078b873?feedback_type=other)

**Comment by crazywoola** [comment]
You need to publish to make this work.

**Comment by kevintsai1202** [comment]
> You need to publish to make this work.
> 
> https://github.com/langgenius/dify/blob/a1104ab97ee5822f6caac7321089aba6064efb0c/api/services/audio_service.py#L86-L100

Thanks.

**Comment by FaceBeleren** [comment]
of cource i can see that but what can i do when i use the Self Hosted? i dont know where to change the config "set text to speech to true" or something. all i did was docker compose up -d and i set a workflow, when i push that play button it failed. it says TTS is Not Enabled
i can change the python code but the question is ----where is the fxxking config???? gpt tells me i needn't to change anything, which i think is bullshit.  why the code don't set the default situation as i can use tts???

**Comment by kfchandsome** [comment]
> of cource i can see that but what can i do when i use the Self Hosted? i dont know where to change the config "set text to speech to true" or something. all i did was docker compose up -d and i set a workflow, when i push that play button it failed. it says TTS is Not Enabled i can change the python code but the question is ----where is the fxxking config???? gpt tells me i needn't to change anything, which i think is bullshit. why the code don't set the default situation so that i can use tts??? and why there are so few questions about this? do most of the people never met this bug? how can they pass through it ?

Have you solved the problem?

**Comment by kevintsai1202** [comment]
> of cource i can see that but what can i do when i use the Self Hosted? i dont know where to change the config "set text to speech to true" or something. all i did was docker compose up -d and i set a workflow, when i push that play button it failed. it says TTS is Not Enabled i can change the python code but the question is ----where is the fxxking config???? gpt tells me i needn't to change anything, which i think is bullshit. why the code don't set the default situation so that i can use tts??? and why there are so few questions about this? do most of the people never met this bug? how can they pass through it ?

I'm too lazy to communicate with them anymore. It's clearly a function that can't be executed on the system, yet they want me to modify the code

**Comment by FaceBeleren** [comment]
well, i found that all you need to do is press the button 'publish' before you test the play button......

**Comment by FaceBeleren** [comment]
before your workflow is published, the tts and speech to text button will always says 'not enabled'. once you publish your workflow, you can use those buttons @kfchandsome

**Comment by andyuan1000** [comment]
@dosubot
 关键在哪里做配置尼

**Comment by FaceBeleren** [comment]
so the guy above is a robot?

**Comment by sxk000** [comment]
config.json这个配置文件在哪里？where is the config.json?

**Comment by FaceBeleren** [comment]
> config.json这个配置文件在哪里？where is the config.json?

你滴，看我上面回复滴干活
before your workflow is published, the tts and speech to text button will always says 'not enabled'. once you publish your workflow, you can use those buttons

**Comment by sxk000** [comment]
> > config.json这个配置文件在哪里？where is the config.json?
> 
> 你滴，看我上面回复滴干活 before your workflow is published, the tts and speech to text button will always says 'not enabled'. once you publish your workflow, you can use those buttons

你滴真鬼子还是假鬼子？

看半天还是没有弄明白。。。。。。

**Comment by FaceBeleren** [comment]
> > > config.json这个配置文件在哪里？where is the config.json?
> > 
> > 
> > 你滴，看我上面回复滴干活 before your workflow is published, the tts and speech to text button will always says 'not enabled'. once you publish your workflow, you can use those buttons
> 
> 你滴真鬼子还是假鬼子？
> 
> 看半天还是没有弄明白。。。。。。

这里不让说中文滴干活，你滴，本来滴就没有TTS is not enabled，是因为你滴“发布”按钮没有按的原因，如果你发布了就没这个提示了，跟上面机器人说滴config没关系
all you need to do is to press the button 'publish' before you test the play button......

**Comment by sxk000** [comment]
> > > > config.json这个配置文件在哪里？where is the config.json?
> > > 
> > > 
> > > 你滴，看我上面回复滴干活 before your workflow is published, the tts and speech to text button will always says 'not enabled'. once you publish your workflow, you can use those buttons
> > 
> > 
> > 你滴真鬼子还是假鬼子？
> > 看半天还是没有弄明白。。。。。。
> 
> 这里不让说中文滴干活，你滴，本来滴就没有TTS is not enabled，是因为你滴“发布”按钮没有按的原因，如果你发布了就没这个提示了，跟上面机器人说滴config没关系 all you need to do is to press the button 'publish' before you test the play button......

好的，谢谢！
