### ISSUE TITLE
Internal Server Error When Clicking 'Like' in Chat Conversations

### ISSUE THREAD

**Issue by kevintsai1202** [langgenius/dify#12057]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![圖片](https://github.com/user-attachments/assets/3ca10e1d-b15a-4d3a-ba63-41732eff8a6a)
When I click "like" during a chat conversation, an "Internal Server Error" appears at the top of the screen.
However, clicking "like" in the conversation under the logs (admin feedback) works normally.

**Comment by yihong0618** [comment]
Thanks will check

**Comment by yihong0618** [comment]
sorry for that  bring by me and fixed https://github.com/langgenius/dify/pull/12058
