### ISSUE TITLE
File upload issue in conversation

### ISSUE THREAD

**Issue by Dongnc1017** [langgenius/dify#12066]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

If you delete the file uploaded in the first conversation and re-upload the second one, the result is still a question and answer based on the first file. Does the default support only support multiple rounds of conversations with a single file? Files cannot be deleted and re-uploaded in the middle of a conversation

### ✔️ Expected Behavior

The first conversation file is uploaded, and questions and answers can be conducted normally with the content of the file still intact. Delete the file and continue uploading, and answer based on the newly uploaded file.

### ❌ Actual Behavior

The first conversation file is uploaded, and questions and answers can be conducted normally with the content of the file still intact. If you delete the file and continue uploading, the contents of the first file will still be there.

**Comment by crazywoola** [comment]
This is not a bug actually, we have an https://github.com/langgenius/dify/discussions/10652 here. Not only you can not change the uploaded file but also other parameters at the beginning.
