### ISSUE TITLE
RETRY on FAILURE Feature

### ISSUE THREAD

**Issue by zydisney** [langgenius/dify#12063]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I'm self-hosting the server, version 0.14.0.
I cannot find "RETRY on FAILURE" feature in the documntation
![image](https://github.com/user-attachments/assets/dda1c437-7a0f-441f-9388-273945cb0fff)

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/releases/tag/0.14.2
