### ISSUE TITLE
0.3.23版本，新增Xinference类型的chatglm2模型的embedding能力，报错，但是text-generation正常

### ISSUE THREAD

**Issue by tjudadc** [langgenius/dify#1207]
### Dify version

0.3.23

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/42208489/cae994d0-fa4e-4a3c-9dca-86f760df9ff4)

![image](https://github.com/langgenius/dify/assets/42208489/1fa829a0-9e03-486c-b372-b54bc03a2763)

**Comment by tjudadc** [comment]
embedding参数：

**Comment by takatost** [comment]
ChatGLM is not a professional Embedding model. Based on the error message, it seems like xinference is unresponsive. 
Have you tried using specialized Embedding models such as `BAAI/bge-large-en-v1.5` or `sentence-transformers/all-MiniLM-L6-v2` for integration? 😊
