### ISSUE TITLE
Blank Page with Error When Adding Notion Configuration in Data Sources

### ISSUE THREAD

**Issue by SingleKey** [langgenius/dify#12080]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello,

When attempting to add a Notion configuration in the Data Sources section of the settings, I am redirected to a blank page. The page displays the following error message:

~~~Json
{
  "error": "invalid_request",
  "error_description": "query failed validation: query.client_id should be a string or `undefined`, instead was `0`.",
  "request_id": "4ce7caa0-10d3-4499-8618-39d8ddb8577e"
}
~~~
Could you please provide guidance on how to resolve this issue? Specifically, it seems that there is an issue with the client_id not being passed correctly as a string.

Thank you for your assistance.

Best regards,

### ✔️ Expected Behavior

My expectation is that after adding the Notion configuration, a popup window or another configuration interface should appear to guide me through the setup process. 

### ❌ Actual Behavior

I encounter this error and the process cannot be completed.

**Comment by crazywoola** [comment]
Check the settings of the notion.
