### ISSUE TITLE
Error occurred when calling through the API. Data in input form must be less than 999999 characters

### ISSUE THREAD

**Issue by hw872715125** [langgenius/dify#12113]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When calling the workflow through the API, an HTTP 400 error occurred with the code: invalid_param and the message: data in input form must be less than 999999 characters.
What needs to be done to lift this restriction?

**Comment by crazywoola** [comment]
This is set by your input type.
