### ISSUE TITLE
Agent tool process detail not displayed

### ISSUE THREAD

**Issue by leslie2046** [langgenius/dify#12125]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Enter to studio
2. Enter to a agent app
3. Ask a question to use tool

### ✔️ Expected Behavior

![图片](https://github.com/user-attachments/assets/80bdaddc-d9a6-41be-aa2e-60586dd2b00d)

### ❌ Actual Behavior

![图片](https://github.com/user-attachments/assets/02ac16c1-c70c-49bf-b7d0-a319c3c2dc38)

**Comment by hjlarry** [comment]
I can't reproduce it on the newest main branch
