### ISSUE TITLE
notebook is needed so that i can !pip install xxx，to realize my code

### ISSUE THREAD

**Issue by better319** [langgenius/dify#12145]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

i need to change docker sandbox to realize import xxxx

### 2. Additional context or comments

notebook is needed so that i can !pip install xxx，to realize my code

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by better319** [comment]
node of notebook  an alternative way to use code

**Comment by AugNSo** [comment]
You can modify the `docker/volumes/sandbox/dependencies/python-requirements.txt` to install custom packages.
