### ISSUE TITLE
show Error when thumb up in message 

### ISSUE THREAD

**Issue by happyallday** [langgenius/dify#12152]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![error](https://github.com/user-attachments/assets/61664925-cbab-4a67-b9ae-dfe9b5a0e044)

### ✔️ Expected Behavior

how can i do to fix this problem and show me the fix step ,thanks

**Comment by crazywoola** [comment]
Duplicated, please see the bot's reply, you need to wait for the next releases.
