### ISSUE TITLE
skip “start chat” page

### ISSUE THREAD

**Issue by kunlun122** [langgenius/dify#12153]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

webapp users want to go to chat page directly。how to skip “start chat” page？
![image](https://github.com/user-attachments/assets/c76db94e-a611-4602-bc73-4d70cd4d854b)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated
