### ISSUE TITLE
Add new workspace

### ISSUE THREAD

**Issue by duxiaoyang06** [langgenius/dify#12163]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [ ] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Does Dify currently support adding workspaces? Otherwise, there is a high risk of knowledge base information leakage, as there are strict isolation policies between different teams and departments. If not, will this feature be added in the future?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
> adding workspaces
This is a business feature, you can use one workspace only in ce version, please contact business@dify.ai to get a quota.
