### ISSUE TITLE
Sending inputs API Does not update on chatflow

### ISSUE THREAD

**Issue by juniorsereno** [langgenius/dify#12173]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Send a input variable via API to chatflow

### ✔️ Expected Behavior

The input need to change with new inputs variable

### ❌ Actual Behavior

somente o primeiro input é enviado, outros inputs não são enviados e o valor do input se mantem o mesmo infinitamente.

Se não enviar um input na primeira interação o input não poderá mais ser enviado pois continuará vazio.

**Comment by crazywoola** [comment]
Duplicated
