### ISSUE TITLE
supports structured knowledge Search

### ISSUE THREAD

**Issue by Luhuanz** [langgenius/dify#12176]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

First of all, I would like to thank the emergence of the tool dify, which made my LLM learning process smoother. One question is whether it supports structured knowledge base retrieval, not just PDF and txt. Similar to the structure of graphrag.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated #6230 not supported yet.
