### ISSUE TITLE
hit-testing  error

### ISSUE THREAD

**Issue by 1193700079** [langgenius/dify#12186]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4353eb5d-cde9-4664-8945-9eacc13b6be1)
When using the knowledge base, the model performs segmented retrieval normally, but an error occurs during hit-testing, and the cause is unclear. My machine is a Raspberry Pi 5B with 8GB of RAM, and I am running services like Docker as usual. This issue appeared during regular use. I have looked through related issues but haven't found a suitable solution.

### ✔️ Expected Behavior

run success

### ❌ Actual Behavior

hit-testing  error

**Comment by 1193700079** [comment]
![image](https://github.com/user-attachments/assets/30611848-0999-4bcb-9078-706fd6f74ef0)

**Comment by 1193700079** [comment]
![image](https://github.com/user-attachments/assets/bf113825-9f47-4f4b-9bb7-dc10d8eaf839)

**Comment by 1193700079** [comment]
![image](https://github.com/user-attachments/assets/2c0218bb-f57a-4332-91d1-360432a21476)

**Comment by crazywoola** [comment]
```
Meta endpoint! Unexpected status code: 502, with response body: None.
```
This error suggests you do not have the weaviate started correctly, please check the container status if this service is alive.
