### ISSUE TITLE
如何让知识库更精准一点呢？

### ISSUE THREAD

**Issue by skykiah** [langgenius/dify#122]
如何让索引更精准一点呢？比如命中了，只回复我设置的那条知识库的内容?

**Comment by takatost** [comment]
1. 每个分段尽可能保持整段语意的完整。若自动分段无法满足切分预期，可尝试自定义模式，自行在文件中插入分隔符，如："----"，以达到按自己的分段规则切分。
2. 针对用户问题进行预测，并收集用户经常提问的问题，配合命中测试，观察命中率，以及问题与实际数据集匹配程度，如果效果不理想，建议针对数据集内容进行优化。
    举个例子：
    用户提问：公司创立时间是什么时候
    预期匹配数据集内容：……XXX 公司（2020-2023）
    由于 `（2020-2023）`与创立时间语意相差较大，因此，最终获取到的分段大概率不符合预期，因此建议将 `（2020-2023）` 改为：`XXX 公司成立时间：2020年XX月XX日`。

暂时列举 2 个目前效果较为明显的优化方法。

**Comment by takatost** [comment]
目前是的，之后会开放人工编辑
