### ISSUE TITLE
Email Login Not Working: PIN Code Not Sent

### ISSUE THREAD

**Issue by fmobeireek** [langgenius/dify#12201]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Navigate to the cloud version of Dify (https://cloud.dify.ai/).
2. Click on the "Login" button.
3. Enter a valid email address and submit.
4. Check the associated email inbox for the PIN code.

### ✔️ Expected Behavior

A PIN code should be sent to the email address provided, allowing users to log in.

### ❌ Actual Behavior

No PIN code is received in the email inbox (including spam/junk folders), preventing login.

**Comment by douxc** [comment]
@fmobeireek it seems the issue was caused by a network problem, but it should be working fine now. Please try again.
