### ISSUE TITLE
Can't view knowledge bases on Dify's cloud though the account owner has granted me access to the workspace as an admin

### ISSUE THREAD

**Issue by blacktail** [langgenius/dify#12205]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

On the cloud platform,
1. Account owner granted admin access to another user
2. The user login to the Dify cloud
3. Go to the knowlege bases page https://cloud.dify.ai/datasets
4. Can't find any knowledge bases there, but if login using the owner email, i can see there are many knowledge bases.

### ✔️ Expected Behavior

The user can view and manage the knowledge bases after the owner granted the admin access to the user.

### ❌ Actual Behavior

The user can't view and manage the knowledge bases after the owner granted the admin access to the user.

**Comment by crazywoola** [comment]
There is another settings you should check.
<img width="999" alt="image" src="https://github.com/user-attachments/assets/ebbbc5e7-a2f8-4212-b16d-b94ee3dbd767" />

**Comment by Fedrickson00** [comment]
i just got assisted on TIKTOK with the assistance of Xiaospy1 Platform.
