### ISSUE TITLE
Dify reported an error when displaying file iterations, indicating "invalid iterator value: value_type=<SegmentType.ARRAY_FILE: 'array[file]'> ."

### ISSUE THREAD

**Issue by qkfm-97** [langgenius/dify#12219]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

this is the full error

invalid iterator value: value_type=<SegmentType.ARRAY_FILE: 'array[file]'> value=[File(dify_model_identity='__dify__file__', id=None, tenant_id='4d6d8447-60c2-4488-b6cd-e110602a1db5', type=<FileType.DOCUMENT: 'document'>, transfer_method=<FileTransferMethod.LOCAL_FILE: 'local_file'>, remote_url='', related_id='388974e9-df07-430b-91e8-b31aa058017a', filename='第01集知识点总结.pdf', extension='.pdf', mime_type='application/pdf', size=373038), File(dify_model_identity='__dify__file__', id=None, tenant_id='4d6d8447-60c2-4488-b6cd-e110602a1db5', type=<FileType.DOCUMENT: 'document'>, transfer_method=<FileTransferMethod.LOCAL_FILE: 'local_file'>, remote_url='', related_id='0f27b89f-bfaf-4460-8c37-c9e8a15f7a93', filename='第07集知识点总结.pdf', extension='.pdf', mime_type='application/pdf', size=509967)] id='80b1a8ed-9e84-470f-8ec5-69dac4a44951' name='filearr' description='' selector=['1735529468276', 'filearr'], please provide a list.

![11](https://github.com/user-attachments/assets/c8194e2b-ed3e-4591-a0dc-edf8473a94e3)

**Comment by crazywoola** [comment]
See above answer.
