### ISSUE TITLE
Dify cloud website timing out

### ISSUE THREAD

**Issue by sugoh** [langgenius/dify#12232]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Go to https://cloud.dify.ai/datasets
2. See bug

### ✔️ Expected Behavior

Access Dify website

### ❌ Actual Behavior

<img width="1006" alt="Screenshot 2024-12-30 at 11 53 54 PM" src="https://github.com/user-attachments/assets/4d93c7d4-07bc-4600-8add-9c22305eb910" />

**Comment by laipz8200** [comment]
It should be working now! 😊
