### ISSUE TITLE
向量查询时多传一个参数

### ISSUE THREAD

**Issue by xjw8396761** [langgenius/dify#1241]
### Provide a description of the help you need

在进行向量相关的文档查询时，我想多传一个conversation_id,代码如下：
![image](https://github.com/langgenius/dify/assets/7021196/1d9ee0e2-4761-42cf-b0ec-089b9b583764)

在api/core/tool/dataset_retriever_tool.py文件修改代码如下：
![image](https://github.com/langgenius/dify/assets/7021196/9459ef6f-8466-4e10-9237-5a9aaaad7702)

打印的日志没有任何输出，同时还报下面的错误：
![image](https://github.com/langgenius/dify/assets/7021196/4d4761c7-76c6-40bd-8bfe-8315654182d6)
请求大大帮忙

**Comment by xjw8396761** [comment]
> How do you start it If you are using source code startup. Try to set `LOG_LEVEL: DEBUG` then restart the application.

您好，是在api/config.py文件中修改log_level:debug吗？我修改了以后也看不到什么记录，另外我想问一下，如果上面添加字段的方式正确吗？

**Comment by takatost** [comment]
This API error should have detailed Traceback information in the log of the API service. Can you please paste it?
