### ISSUE TITLE
请问whisper模型如何在设置-模型供应商-语音转文本模型中加入呢？

### ISSUE THREAD

**Issue by YinSonglin1997** [langgenius/dify#1246]
我是通过Docker Compose部署的社区版

![1695801365515](https://github.com/langgenius/dify/assets/90330685/dfd3e86a-4d82-4d28-bd98-26123be0224a)

**Comment by takatost** [comment]
Just need to integrate OpenAI.

**Comment by YinSonglin1997** [comment]
> Just need to integrate OpenAI.

Thank you for your reply, but I don't quite understand how to do it. Can you explain how to implement it? Do you want to modify the code in the container?

**Comment by takatost** [comment]
No need, you just need to configure the `api key` of OpenAI provider to use it.
