### ISSUE TITLE
通义千问 API_KEY设置验证失败

### ISSUE THREAD

**Issue by ycoe** [langgenius/dify#1260]
### Dify version

0.3.23

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1. 点击用户头像
2. 设置
3. 模型供应商
4. 显示更多模型供应商
5. 通义千问 》设置
6. 输入 api key
7. 检测失败，报错：403

### ✔️ Expected Behavior

期望正确的 api key可以验证通过

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/985424/490d24ad-c836-4dce-b79e-41d503b1f3e9)
确认我的api key是有效的，且在 postman上调用正常

**Comment by klausxie** [comment]
升级到了 0.3.26，问题还是没解决，报同样的错误

**Comment by jiangxiaoshuaiya** [comment]
same problem

**Comment by hsiaoyang** [comment]
same problem

**Comment by zengxianming01** [comment]
same problem

**Comment by shaojun** [comment]
still see this problem at 2025.8.14, can't believe that:

<img width="1998" height="970" alt="Image" src="https://github.com/user-attachments/assets/059f0608-d810-4c36-8709-17e5a7c82d68" />

the key i'm using is like: `sk-acc1da6bad0099999999999999999999`

**Comment by fsinbad** [comment]
same problem, i remember before update the plugin, it was okay.

**Comment by diverHansun** [comment]
So how can we solve this problem? I can't use Tongyi models in Dify

**Comment by scc02** [comment]
We should reopen this issue.

**Comment by hmoji** [comment]
same problem，my version is 0.0.54
