### ISSUE TITLE
删除应用无反应

### ISSUE THREAD

**Issue by leslie2046** [langgenius/dify#1270]
### Dify version

0.3.24

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

我是管理员，“构建应用”里试图删除某个应用无反应，无论是自己部署的，还是公有云版https://cloud.dify.ai/apps里都是如此。

### ✔️ Expected Behavior

可以删除应用

**Comment by leslie2046** [comment]
![图片](https://github.com/langgenius/dify/assets/10449699/fe14ac69-f0d4-460d-896e-1296a1198f53)
firefox控制台信息如上，并且不会弹出“确认删除应用”的对话框。而chrome可以弹出并且能删除应用

**Comment by leslie2046** [comment]
@crazywoola 好的，感谢

**Comment by crazywoola** [comment]
Firefox seems doesn’t work.
