### ISSUE TITLE
支持使用Xorbits Inference作为Chat来源

### ISSUE THREAD

**Issue by Minamiyama** [langgenius/dify#1271]
### Description of the new feature / enhancement

It seems could not use Xorbits Inference as Chat type completion.

### Scenario when this would be used?

在“设置”中设置了Inference作为文本生成类型后，创建一个聊天应用，并选择刚才设置的Inference作为推断源，但是进行聊天时候无任何内容反馈，但是在Inference的web ui中可以正常进行聊天

**Comment by takatost** [comment]
Can you please explain what model has been deployed?

**Comment by Minamiyama** [comment]
> Can you please explain what model has been deployed?

I tried Baichuan2-chat and ChatGLM2

**Comment by datoujiejie** [comment]
检查一下XInference和requirements里的版本是否一致

**Comment by takatost** [comment]
We found out that the inference interface of xinference has a breaking change in version 0.5.1. So, we decided to update it to the latest version.

**Comment by Minamiyama** [comment]
> We found out that the inference interface of xinference has a breaking change in version 0.5.1. So, we decided to update it to the latest version.

yep, I've updated to the latest version, the problem is solved

**Comment by iamsk** [comment]
I think xinference-client need upgrade too?
