### ISSUE TITLE
上传文件报错：SSL: WRONG VERSION NUMBER] wrong version number ( ssl.c:1007)

### ISSUE THREAD

**Issue by Fsm000814** [langgenius/dify#1275]
### Dify version

0.3.23

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

正常上传文件
上传失败
![image](https://github.com/langgenius/dify/assets/74786133/8a3711b5-2c1a-43da-aabe-fa8f222bb003)

### ✔️ Expected Behavior

上传成功

### ❌ Actual Behavior

上传错误报错SSL: WRONG VERSION NUMBER] wrong version number ( ssl.c:1007)

**Comment by Fsm000814** [comment]
自己配置错了，http配置成了https

**Comment by MattCarneiro** [comment]
> 自己配置错了，http配置成了https

how did you fix that?
你是怎么解决这个问题的？
