### ISSUE TITLE
OPENLLM模型的输入长度限制提示

### ISSUE THREAD

**Issue by sjn920336697** [langgenius/dify#1280]
### Dify version

0.3.22

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

通过OPENLLM部署的ChatGLM2模型后端，通过Dify配置模板工程，测试的时候发现很容易提示prompt 或 query长度超限。

通过查看docker_api的日志发现，提示tokens长度超过该模型1024输入长度报错 token indices sequence is longer than the specified maximum sequence length。

但是OPENLLM部署的bentolm后端，通过直接访问chatglm2的接口，实际上是可以支持几K以上长度的输入文本，且本身glm2支持的长度也远不止1024。Dify工程是否在哪里有指定max-tokens的配置？？？

### ✔️ Expected Behavior

配置

**Comment by sjn920336697** [comment]
> > token indices sequence is longer than the specified maximum sequence length
> 
> 这个错误本身不是我们返回的，不知道你说的是不是 prompt 编辑那边右上角小齿轮里面的 max token 设置？
===
小齿轮那个是max_new_token（生成的最大字符长度），我是知道的。我指的是现在chatglm2的输入长度被限制在了1024，就是很奇怪，我直接请求OPENLLM部署之后的模型调试接口，长文本是可以处理的，然后dify配置的OPENLLM这个模型供应商，请求的时候好像就被限制在1024了，再长的文本dify页面就会提示 query or prompt is too long, 需要shrink 长度或者 调整模型的max tokens limit 之类的

**Comment by takatost** [comment]
https://github.com/langgenius/dify/blob/5003db987d6077a5430474a5f3b5f2349f20daa3/api/core/model_providers/providers/openllm_provider.py#L56

the `max_token` limit for OpenLLM is set to 4000. And this error is reported by OpenLLM, so theoretically there shouldn't be any problem. We'll test it out in practice later

**Comment by sjn920336697** [comment]
> https://github.com/langgenius/dify/blob/5003db987d6077a5430474a5f3b5f2349f20daa3/api/core/model_providers/providers/openllm_provider.py#L56
> 
> the `max_token` limit for OpenLLM is set to 4000. And this error is reported by OpenLLM, so theoretically there shouldn't be any problem. We'll test it out in practice later

===
Thank you for your reply. I deployed the dify service through Docker Compose instead of source code deployment. Does this mean that I cannot adjust this max_ Token parameter??

**Comment by takatost** [comment]
The "max tokens" here refers to the token length constraint for the model answer. I understand that "token indices sequence is longer than the specified maximum sequence length" means that the token length of the prompt exceeds the model's limit of 1024 tokens.

**Comment by sjn920336697** [comment]
> the `max_token` limit for OpenLLM is set to 4000.
===
You're right. What I want to know now is that my dify service is deployed through Docker Compose. Can I modify the  "max_token" limit in the OpenLLM call function, such as adjusting it from 4000 to 8000

**Comment by takatost** [comment]
> > the `max_token` limit for OpenLLM is set to 4000.
> > ===
> > You're right. What I want to know now is that my dify service is deployed through Docker Compose. Can I modify the  "max_token" limit in the OpenLLM call function, such as adjusting it from 4000 to 8000

This max tokens is hard-coded and cannot be modified temporarily. You can also modify the compilation yourself. In the future, we will consider adding a switch and dynamic configuration for this parameter.
