### ISSUE TITLE
提示词编排节目使用MiniMax token计数异常

### ISSUE THREAD

**Issue by rayzw-star** [langgenius/dify#1304]
### Dify version

0.3.25

### Cloud or Self Hosted

Cloud, Self Hosted

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/130547988/84be2d1a-9262-4e46-8400-ad2226cc393b)
在SaaS版本0.3.25与社区版0.3.24都存在相同现象。
提示词调试界面使用minimax模型返回token计数为0

**Comment by takatost** [comment]
we're using the implementation provided by MiniMax in LangChiain, called langchain.llms.minimax.Minimax. However, this implementation hasn't been integrated with the usage information returned by MiniMax yet, so we're seeing a token consumption of 0.
