### ISSUE TITLE
预览应用提示错误invalid url post /chat/complitions是咋回事啊？

### ISSUE THREAD

**Issue by daawen** [langgenius/dify#131]
compose文件里只是在api和worker里加了：

OPENAI_API_BASE: 'https://xxxx.xxx我自己的api代理'
DISABLE_PROVIDER_CONFIG_VALIDATION: 'True'

**Comment by daawen** [comment]
![image](https://github.com/langgenius/dify/assets/738285/fdbd76ed-2ee3-4ce1-9729-9df3bd67ba9e)

**Comment by daawen** [comment]
把OPENAI_API_BASE改成了OPENAI_API_BASE_URL
不报错了，但是没有回答内容出来，一直显示回复中

**Comment by takatost** [comment]
OPENAI_API_BASE 可能配错了，或许缺少 /v1 路由前缀
