### ISSUE TITLE
能否给chatbot应用提供除了“公开链接”以外的其他鉴权方式？

### ISSUE THREAD

**Issue by koyo922** [langgenius/dify#1318]
### Provide a description of the help you need

- dify+notion 打造知识库的功能非常好用！ 参考文档 https://docs.dify.ai/v/zh-hans/use-cases/build-an-notion-ai-assistant
- 但是当我想要把自己的一些隐私知识做成bot以后，发现默认的 访问URL是完全公开的；这会带来风险
- 我也知道可以通过API集成到自己的项目中，自己来做权限访问控制；但是我不会写前端代码（我只会写python）
- 建议在这里提供一些 密码/微信授权/飞书授权/短期token/ip白名单  等常用的鉴权方式
![image](https://github.com/langgenius/dify/assets/6063429/08e30c43-34f6-4a3d-a1fb-f73d4ec65bd8)

非常感谢你的支持！ 这会极大的拓展该应用的适用范围~

**Comment by wlbksy** [comment]
这个有计划了吗？能不能设置成 workspace 的成员可见

**Comment by simcyber** [comment]
迫切需要

**Comment by oabu** [comment]
同样需要，期待输入密码才能使用

**Comment by sangxgg** [comment]
同样需要
