### ISSUE TITLE
数据集如何格式化可以有更好的命中率

### ISSUE THREAD

**Issue by granken** [langgenius/dify#133]
我手头有个人介绍的数据集，数据集以怎样的格式化，可以获得更好的命中率效果呢？

**Comment by takatost** [comment]
1. 每个分段尽可能保持整段语意的完整。若自动分段无法满足切分预期，可尝试自定义模式，自行在文件中插入分隔符，如："----"，以达到按自己的分段规则切分。
2. 针对用户问题进行预测，并收集用户经常提问的问题，配合命中测试，观察命中率，以及问题与实际数据集匹配程度，如果效果不理想，建议针对数据集内容进行优化。
    举个例子：
    用户提问：公司创立时间是什么时候
    预期匹配数据集内容：……XXX 公司（2020-2023）
    由于 `（2020-2023）`与创立时间语意相差较大，因此，最终获取到的分段大概率不符合预期，因此建议将 `（2020-2023）` 改为：`XXX 公司成立时间：2020年XX月XX日`。

暂时列举 2 个目前效果较为明显的优化方法。

**Comment by skykiah** [comment]
> 

好的 谢谢详细解答，就是如何发现效果不好，我如何修改数据集呢？还是要删除重新上传计算呢？，这样是不是有点太麻烦了。。
