### ISSUE TITLE
数据集自动分段-高质量设置无效

### ISSUE THREAD

**Issue by chenkai126** [langgenius/dify#1333]
### Provide a description of the help you need

chatgpt账号余额充足，选择数据集自动分段-高质量时显示报错
![image](https://github.com/langgenius/dify/assets/131443030/bce0da55-7aea-491b-918b-b678dc7f2515)

**Comment by chenkai126** [comment]
![1697174116148](https://github.com/langgenius/dify/assets/131443030/aaf5ecf7-4332-43f6-adad-b98e36a24f9d)

**Comment by crazywoola** [comment]
我想问问这个是什么版本？是自己  deploy  的吗？如果是的话，是怎么启动的？
如果不是归档之后重新打开或者重试应该就行了。

**Comment by chenkai126** [comment]
0.3.26版本，社区版启动的

**Comment by crazywoola** [comment]
如果是 docker 容器启动的，需要提供详细的日志。
