### ISSUE TITLE
希望能增加上传图像这一个入口

### ISSUE THREAD

**Issue by MagicalAci** [langgenius/dify#1353]
### Description of the new feature / enhancement

ChatGPT4v即将开发API接口，他会支持对于图像的识别，这将对很对业务有极大的帮助，拜托了🙏
现在有了Dify，我真的再也回不去之前写代码，调APi的时候了😭

### Scenario when this would be used?

ChatGPT4v将于11月发售
目前通义千问等就支持图像输入，希望能11月前或更早，加入图像上传的功能，这样可以后面打造更多有意思的东西，就比如图像标注！！！

**Comment by crazywoola** [comment]
We will wait until the several API providers are stable enough to do this.

**Comment by waltcow** [comment]
Need this feature

**Comment by takatost** [comment]
Thanks a lot for the suggestion! We'll definitely need to do some thorough research before adding this feature. Rushing into it might go against standards. 😊

**Comment by crazywoola** [comment]
Close as done, see v0.3.30.
