### ISSUE TITLE
用户账号加解密问题

### ISSUE THREAD

**Issue by chenqhh** [langgenius/dify#1358]
### Provide a description of the help you need

由于这个项目的后端是用Python写的，我所看到的加密方式有Base64、pbkdf2_hmac等，但这些怎么用.Net解密呢，Python的Base64似乎与.Net的Base64不一样，我用.Net中的Base64方式去解密Python中的Base64加密行不通，有人处理过这个问题吗？

**Comment by crazywoola** [comment]
Close due to off-topic.
