### ISSUE TITLE
是否可以支持直接输出原始分段里的答案部分

### ISSUE THREAD

**Issue by leslie2046** [langgenius/dify#1359]
### Provide a description of the help you need

![图片](https://github.com/langgenius/dify/assets/10449699/c4d45b8e-4013-48f4-8732-789303f1a8a2)
如图所示，对于政府/银行客户等严肃的使用场景，不希望更改答案，因为大模型会基于原始文本给添油加醋，狗尾续貂。:)
我们给银行的知识库是已经整理好的问答对（是经过了银行审核认可的），我希望可以支持原始答案输出模式，即检索到最相似的问题，就直接输出原始文本作为答案，而且这个答案可能是富文本的（HTML/Markdown）.

**Comment by leslie2046** [comment]
有些场景（应用）是要求在知识库（即数据集）里找不到答案就直接输出“对不起，我不知道”，有些场景是要求超出知识库的部分能够用大模型来兜底回答。
1.所以我觉得从大的方面来说应用应该要能配置无答案的后处理流程（大模型直接回答/输出默认的话术）
2.从细节上来说，就是应用支持配置答案的来源（数据集/插件）
3.答案应该支持数据集中检索出的原始文本中的答案部分作为答案。（这种配置是在数据集或是应用中配置需要仔细考虑）
4.支持富文本的输出，因为可能需要展示图文混排的答案。

**Comment by crazywoola** [comment]
对了，你有加我微信吗 crazyphage

**Comment by lethe3000** [comment]
I think dify can provide an app model or an option named "retrieve only" that  just embedding user's query and show top-k results from vector db.

**Comment by leslie2046** [comment]
检索命中后处理：
1. 直接输出最高的答案
2.LLM生成答案
检索未命中后处理：
1.输出固定的话术
2.LLM生成答案

**Comment by crazywoola** [comment]
目前使用 Annotation 应该能够行了，加上数据集的全文检索。
