### ISSUE TITLE
[需求]对话式应用嵌入，没有变量的话可以直接开始对话

### ISSUE THREAD

**Issue by Jinkeycode** [langgenius/dify#1365]
### Description of the new feature / enhancement

嵌入到网页上使用的时候，要先点开始对话太麻烦了。一般客服智能机器人场景不需要额外设置参数，可以直接开始对话。如果开始对话的按钮是为了设置变量，那么没有变量的时候，就可以直接开始对话了

### Scenario when this would be used?

客服智能机器人场景

**Comment by crazywoola** [comment]
Sounds reasonable.

**Comment by chenggb123** [comment]
我也这么认为，有些对话场景，不需要左侧会话记录部分，可能就一个聊天窗就行了。

**Comment by Jinkeycode** [comment]
@crazywoola 补充说明y一下，一般自动嵌入到网站的智能客服，会在用户打开网站停留x秒之后自动展开并开始对话。建议可以设置该选项，不然嵌入网站之后，只有右下角一个小按钮，用户不容易发现
