### ISSUE TITLE
求助，源码部署方式升级版本的完整步骤？

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1368]
### Provide a description of the help you need

今天第一次升级版本操作就遇到了报错（已提交bug issue），因此想请教一下，完整正确的升级版本的步骤（命令）是什么？
     非开发小白一枚，感谢dify的老师和其他大佬们。

我执行的完整步骤是：
stop #直接重启云服务器
conda activate dify #进入dify虚拟python环境
cd dify #进入项目目录
git pull
cd api #进入api目录
flask db upgrade

然后再执行下面：
flask run --host 0.0.0.0 --port=5001 --debug
celery -A app.celery worker -P gevent -c 1 -Q dataset,generation,mail --loglevel INFO
npm run start（需要先执行npm run build吗）

**Comment by crazywoola** [comment]
> npm run start（需要先执行npm run build吗）

如果你前端源代码改动了你是需要重新 build 的。

`git pull` 本质上是为了更新代码，需要自行解决冲突合并之后就可以继续正常的使用了。我说的这些步骤在其他软件开发过程中也是适用的。

- `flask db upgrade` 是因为有些代码可能涉及到数据库层面的改动，所以你需要执行这个步骤，
- `pip install -r requirements.txt --upgrade --force-reinstall` 或者 ` pip install -r requirements.txt` 是因为有些代码引入了新的包，那么就需要重新安装依赖，后端通常需要检查 `requirements.txt`，前端需要检查 `package.json`。

首先作为非开发小白，我们并不推荐使用这种方式去部署，我们推荐使用 docker-compose 这种方式，这样会增加我们的沟通成本，因为我不了解你对于整个开发是否熟悉，而作为没有整个软件开发生命周期的人来说也是非常难熟悉整个流程的。

如果你确实希望可以通过这种方式启动，我希望你可以发邮件给 business@dify.ai 付费获取技术支持。
