### ISSUE TITLE
升级版本报错，如何回退到旧版本

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1369]
### Provide a description of the help you need

请教大佬们 回退旧版本的操作步骤

**Comment by crazywoola** [comment]
You can edit image versions in here https://github.com/langgenius/dify/blob/2feb16d957a179bbe9acd7b2fd9d855d51643751/docker/docker-compose.yaml#L5
Replace all the occurrences `0.3.28` to a older version number. 
The rest part can be done as same as the upgrade procedures.
