### ISSUE TITLE
How to pronounce 'Dify'

### ISSUE THREAD

**Issue by ufoym** [langgenius/dify#137]

**Comment by crazywoola** [comment]
It should pronounce like the rest part of 'mo-dify'

**Comment by takatost** [comment]
Check out our help docs for an intro to Dify 📖: https://docs.dify.ai/getting-started/intro-to-dify
it's got all the info you need.

**Comment by linweijiang** [comment]
hi @takatost , I couldn't find any information on the pronunciation of "Dify" in the provided link. 
I hope to get an official pronunciation guide because there are already several different pronunciations in the company team, which I believe could significantly hinder communication.
Thanks~

**Comment by yaoper** [comment]
The name Dify comes from "Define + Modify"
