### ISSUE TITLE
数据集的段无法禁用

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1370]
### Dify version

0.3.22

### Cloud or Self Hosted

Cloud

### Steps to reproduce

在文档段落页面，点击禁用某个分段。显示成功，过会刷新后，又变成了启用状态。查看了开源代码，大概率是在异步删除分段的向量数据时报错，导致状态又复原了。
具体删除分段的向量数据代码在：api/tasks/disable_segment_from_index_task.py

### ✔️ Expected Behavior

不需要复原状态。因为在从数据集中查询相关上下文时会过滤状态为false的分段。

### ❌ Actual Behavior

状态又复原了

**Comment by crazywoola** [comment]
Our cloud version is v0.3.28, is this self hosted? Can you try to upgrade to latest version?

**Comment by wangrg** [comment]
v0.3.28上也是一样的。包括api/tasks/remove_document_from_index_task，api/task/enable_segment_to_index_task.py都会在异常是恢复状态

**Comment by wangrg** [comment]
<img width="1047" alt="image" src="https://github.com/langgenius/dify/assets/1925650/6755b2bf-82e0-4835-a436-5c319e2cb80b">
就是这个异常导致一直无法禁用，会恢复状态。还有一疑问请教一下：什么情况下会导致整个数据集的分段都无法进行类似操作了，都报一样的错误。

**Comment by crazywoola** [comment]
> <img alt="image" width="1047" src="https://user-images.githubusercontent.com/1925650/277872746-6755b2bf-82e0-4835-a436-5c319e2cb80b.png"> 就是这个异常导致一直无法禁用，会恢复状态。还有一疑问请教一下：什么情况下会导致整个数据集的分段都无法进行类似操作了，都报一样的错误。

可能是删除文件成功了，但是其他删除步骤失败了。

**Comment by wangrg** [comment]
能否在删除weaviate向量时，如果抛出的错误是404的，直接捕获错误让其正常删除

**Comment by crazywoola** [comment]
> 能否在删除weaviate向量时，如果抛出的错误是404的，直接捕获错误让其正常删除

@JohnJyong
