### ISSUE TITLE
求助npm启动出错

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1371]
### Provide a description of the help you need

(dify) [root@VM-4-5-centos web]# npm run start
> dify-web@0.3.28 start
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /dify/web/.env.local
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
/bin/sh: yarn: command not found
info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 1976 ms (267 modules)
wait  - compiling...
event - compiled client and server successfully in 740 ms (267 modules)
wait  - compiling /middleware (client and server)...
event - compiled successfully in 185 ms (74 modules)
wait  - compiling /(commonLayout)/apps/page (client and server)...
event - compiled client and server successfully in 13.4s (5640 modules)
wait  - compiling...
event - compiled successfully in 1424 ms (2850 modules)
error - node_modules/@formatjs/intl-localematcher/abstract/CanonicalizeLocaleList.js (10:16) @ getCanonicalLocales
error - RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at getLocaleOnServer (./i18n/server.ts:38:94)
    at LocaleLayout (./app/layout.tsx:26:83)
    at stringify (<anonymous>)
null

**Comment by crazywoola** [comment]
Have you run ` npm install`?
This starts dev env, it's ok there are some errors and warnings.
