### ISSUE TITLE
结构化数据集 测试命中效果很差，寻求改善的方案

### ISSUE THREAD

**Issue by SaylorZhu** [langgenius/dify#1373]
### Provide a description of the help you need

下面是我的结构化数据格式
![image](https://github.com/langgenius/dify/assets/10814011/0a99c822-7dbc-4a2f-afa1-9f6c48a19c32)
当我的数据集分段为几万条的时候，命中效果很差，搜索出来的毫不相关。
![image](https://github.com/langgenius/dify/assets/10814011/376cb6d5-0603-4219-be0c-1c2552b4fc4b)
请问有什么方案可以改善吗

**Comment by SaylorZhu** [comment]
其他搜索也类似
![image](https://github.com/langgenius/dify/assets/10814011/7113ba10-d98b-4af5-b417-ec919b3babda)

**Comment by chenggb123** [comment]
我也发现了，功能界面做的挺好，但是用起来效果很差，几乎无法使用。

**Comment by crazywoola** [comment]
在chat completion 模式有一个  query parameter，可以缩小你这个搜索的范围，但是你不能把他当做传统的数据库去使用，这一点传统数据库显然做的更好，你应该在之前就搜索号这个答案，然后 AI 用于后续的操作。
