### ISSUE TITLE
requirements中的pypdfium2依赖包无法安装

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1382]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

提示：subp rocess -exited-with-error

### ✔️ Expected Behavior

目前在requirements.txt中将pypdfium2注释掉临时解决

**Comment by gtlYashParmar** [comment]
Hi @nickboyabc ,

I tried to reproduce the subprocess error you mentioned, but couldn't encounter the issue since pypdfium2 is already installed on my end. Can you share more specifics about the error you faced and the environment you're using? This might help clarify things.

Thanks

**Comment by nickboyabc** [comment]
感谢回复，是在腾讯云服务器(CentOS）跑的，python是官方文档推荐的3.10
下面是完整的报错截图
![](https://s2.loli.net/2023/10/20/XAnSsQ3JDOwolFk.png)

![](https://s2.loli.net/2023/10/20/hqvWuMcjlsCX6D4.png)

![](https://s2.loli.net/2023/10/20/jIJNPu4rfMA3DQn.png)

**Comment by nickboyabc** [comment]
@Yash-1511 老师，补充信息在上面

**Comment by nickboyabc** [comment]
@Yash-1511 老师还在吗

**Comment by HHHHHANS** [comment]
try `pypdfium==4.17.0`

**Comment by crazywoola** [comment]
> @Yash-1511 老师还在吗

I think you should speak English.
