### ISSUE TITLE
Https中嵌入应用代码（Http）出现"混合内容"报错，造成无法加载应用

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1388]
### Provide a description of the help you need

请教老师，有没有相对简单的解决这个问题的办法呢，网上搜了下可以使用代理来解决，但感觉这个方式对我来说还是有些复杂了（如果dify生成嵌入代码时直接就是https的规范就好了）

![](https://s2.loli.net/2023/10/20/OPfcuUnhkLD6Rps.png)

**Comment by crazywoola** [comment]
You should add a https cert to your domain. :) from any perspective.
