### ISSUE TITLE
请问多段问答有作为上下文发送吗

### ISSUE THREAD

**Issue by renguowen** [langgenius/dify#139]
我在prompt里让输出这是第几个问题，总是回这是第一个问题。
所以我猜想多次问答的内容是不是没有作为上下文，能否有一个地方比如模型设置那，设置多段问答同时作为上下文发送给openAI，当然token消耗会变大，不过可以按需选择

**Comment by takatost** [comment]
目前确实可能带了聊天记录，也会回答不知道，prompt 还需要进一步优化
