### ISSUE TITLE
没有从上下文中寻找答案

### ISSUE THREAD

**Issue by wangzuohao** [langgenius/dify#1391]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

我上传了一个txt文件，主要是公司流程文件，然后通过上下文进行问答，但是发现每次都不能得到答案，即使都能找到正确的引用信息

### ✔️ Expected Behavior

可以从引用的信息中归纳出正确的答案

### ❌ Actual Behavior

找到引用信息，但是不能总结出答案

**Comment by crazywoola** [comment]
See this #1359 
你的问题是没有从上下文中寻找答案，但是实际上是找到了。关于回答质量的问题取决于数据集本身的质量问题。
任何没有经过理解处理过的信息，哪怕是教科书，那也叫信息，而不叫做知识。
