### ISSUE TITLE
前端启动报错：RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1396]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

报错信息如下：
![](https://s2.loli.net/2023/10/23/bS1DBNAp7z8qM3C.png)

**Comment by crazywoola** [comment]
We will fix this in v0.3.29

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/1376
