### ISSUE TITLE
咨询：创建分享链接如何能带上外网IP，不用每次人工替换

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1397]
### Provide a description of the help you need

    需要改哪个配置文件的什么字段可以实现自动带上外网地址呢
![](https://s2.loli.net/2023/10/23/SW7CDw5ezBqP8su.png)

**Comment by crazywoola** [comment]
See https://docs.dify.ai/getting-started/install-self-hosted/environments#app_web_url
