### ISSUE TITLE
提示词编排使用spark V2.0调试报错

### ISSUE THREAD

**Issue by yuanhaishan** [langgenius/dify#1399]
### Dify version

0.3.19

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1.选择科大讯飞模型v2.0
![image](https://github.com/langgenius/dify/assets/53658688/84234533-34e4-4587-bce2-e5ba256c1bdc)
2.输入品牌
![image](https://github.com/langgenius/dify/assets/53658688/d09c42ef-572d-40c8-b3b6-7ee588751de8)
3.报错
![image](https://github.com/langgenius/dify/assets/53658688/18cc06e9-dcac-421e-8dbf-a0bf9740094b)

### ✔️ Expected Behavior

预期能正常返回问答

### ❌ Actual Behavior

报错

**Comment by crazywoola** [comment]
You need to upgrade to our latest version because the Spark team had upgraded their package as well. We have fixed this in later versions.

**Comment by yuanhaishan** [comment]
![image](https://github.com/langgenius/dify/assets/53658688/5cc3dbad-4527-46cc-b031-cf8f5eec8f84)
![image](https://github.com/langgenius/dify/assets/53658688/e06c68cd-4ec9-439e-8e60-f6f5d08a87e6)
我已更新到最新版本 但是报错还是一样的

**Comment by yuanhaishan** [comment]
这个可以帮忙回答下么
