### ISSUE TITLE
数据集文档上传大小及上传数量 不限制

### ISSUE THREAD

**Issue by yuanhaishan** [langgenius/dify#1401]
### Description of the new feature / enhancement

数据集文档上传大小及上传数量 不限制

### Scenario when this would be used?

![image](https://github.com/langgenius/dify/assets/53658688/694d2cd1-09e0-4881-9bed-fbc0adbe2ec3)
这个怎么配置才能不限制数量跟大小呢

**Comment by crazywoola** [comment]
You should and always do this kind of limitation in order to prevent the abuse of system.

**Comment by yuanhaishan** [comment]
那这两个环境变量只需要加到api跟work容器 里面就可以么  其他容器是否需要加这2个参数
