### ISSUE TITLE
本地docker部署，数据集创建上传pdf文件失败

### ISSUE THREAD

**Issue by lilinrestart** [langgenius/dify#1405]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted, Other (please specify in "Steps to Reproduce")

### Steps to reproduce

本地部署官方文档里的docker步骤，新建数据集然后上传文件

### ❌ Actual Behavior

5m以内的四个文件上传失败（带图片），另外2个几百kb的上传成功（纯文字），在线使用能上传成功。。
![image](https://github.com/langgenius/dify/assets/140720825/64b76dfa-b348-4864-9319-b401a3b237b4)

**Comment by crazywoola** [comment]
Need some detailed logs on the frontend upload api. Can you provide them. 
https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/environments#shu-ju-ji-pei-zhi
We set the default values to 15M, it seems the reverse proxy of your own  is not config correctly in your case.

**Comment by lilinrestart** [comment]
> 需要一些关于前端上传 api 的详细日志。你能提供一下吗？ https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/environments#shu-ju-ji-pei-zhi 我们设置默认值为15M，看来是反向代理在您的情况下，您自己的配置不正确。

我只修改了dockercompose.yaml里面的端口设置，其他没有动过

**Comment by lilinrestart** [comment]
> 需要一些关于前端上传 api 的详细日志。你能提供一下吗？ https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/environments#shu-ju-ji-pei-zhi 我们设置默认值为15M，看来是反向代理在您的情况下，您自己的配置不正确。

我发现pdf里面带了图片就无法上传成功，貌似是这个问题

**Comment by lilinrestart** [comment]
> 需要一些关于前端上传 api 的详细日志。你能提供一下吗？ https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/environments#shu-ju-ji-pei-zhi 我们设置默认值为15M，看来是反向代理在您的情况下，您自己的配置不正确。

出现了错误，我通过自己设置的代理访问的，我把7030使用nginx代理成dify.***出来访问的，是这个原因吗？
docker-nginx-1     | 2023/10/25 03:33:46 [error] 30#30: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 17       2.22.0.1, server: _, request: "GET /console/api/workspaces/current/models/model-type/embeddings HTTP/1.1", upstream: "http://172.22.0.7:5001/co       nsole/api/workspaces/current/models/model-type/embeddings", host: "dify.***", referrer: "http://dify****/datasets/cre       ate"

**Comment by lilinrestart** [comment]
前端的报错信息
![image](https://github.com/langgenius/dify/assets/140720825/eeb3aa21-d8fa-4b69-8721-f9837560851e)

**Comment by crazywoola** [comment]
> 前端的报错信息 ![image](https://user-images.githubusercontent.com/140720825/277867035-4049cd50-7fea-47c8-a2cd-e23765581dc0.png)

Entity too large  usually means 👇

> By default, NGINX® has a upload limit of 1 MB per file. By editing client_max_body_size, you adjust the file upload size.

**Comment by lilinrestart** [comment]
> > 前端的报错信息 ![图像](https://user-images.githubusercontent.com/140720825/277867035-4049cd50-7fea-47c8-a2cd-e23765581dc0.png)
> 
> 实体太大通常意味着👇
> 
> > 默认情况下，NGINX® 每个文件的上传限制为 1 MB。通过编辑client_max_body_size，您可以调整文件上传大小。

我大概是知道问题了，谢谢：）

**Comment by lilinrestart** [comment]
> > 前端的报错信息 ![image](https://user-images.githubusercontent.com/140720825/277867035-4049cd50-7fea-47c8-a2cd-e23765581dc0.png)
> 
> Entity too large usually means 👇
> 
> > By default, NGINX® has a upload limit of 1 MB per file. By editing client_max_body_size, you adjust the file upload size.

实际上当我的pdf是纯文字就可以上传（4m），ps：我手动把图片删除了
![image](https://github.com/langgenius/dify/assets/140720825/ce4344ce-4d0b-47cb-a1a4-077026eb5351)

**Comment by lilinrestart** [comment]
> > > 前端的报错信息 ![image](https://user-images.githubusercontent.com/140720825/277867035-4049cd50-7fea-47c8-a2cd-e23765581dc0.png)
> > 
> > 
> > Entity too large usually means 👇
> > > By default, NGINX® has a upload limit of 1 MB per file. By editing client_max_body_size, you adjust the file upload size.
> 
> 实际上当我的pdf是纯文字就可以上传（4m），ps：我手动把图片删除了 ![image](https://user-images.githubusercontent.com/140720825/277885910-ce4344ce-4d0b-47cb-a1a4-077026eb5351.png)

在线使用版没有这个限制，即使是带了图片也能上传上去。。。这是为什么呢

**Comment by lilinrestart** [comment]
> > > 前端的报错信息 ![图像](https://user-images.githubusercontent.com/140720825/277867035-4049cd50-7fea-47c8-a2cd-e23765581dc0.png)
> > 
> > 
> > 实体太大通常意味着👇
> > > 默认情况下，NGINX® 每个文件的上传限制为 1 MB。通过编辑client_max_body_size，您可以调整文件上传大小。
> 
> ![image](https://user-images.githubusercontent.com/140720825/277884579-897876ed-56e1-4540-b7f0-856069722852.png) 我设置的是1024m

对于此docker compose部署，我仅修改了配置文件中的映射端口，然后设置了nginx代理访问页面，并没有做其他任何改动....
