### ISSUE TITLE
创建完数据集后点删除没反应，添加数据集一直显示排队

### ISSUE THREAD

**Issue by Trangle** [langgenius/dify#1406]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1. 创建数据集，给个名字：此时无法删除
2. 添加文件，其余默认（或者采用QA模式打开），保存并处理：此时等待很久后开始显示一直在排队

### ✔️ Expected Behavior

1. 可正常删除数据集
2. 正确处理文档嵌入，显示进度

### ❌ Actual Behavior

1. 创建数据集，给个名字：此时无法删除
2. 添加文件，其余默认（或者采用QA模式打开），保存并处理：此时等待很久后开始显示一直在排队

### Related issue

1. https://github.com/langgenius/dify/issues/1466
2.

**Comment by crazywoola** [comment]
Can you provide detailed docker logs?

**Comment by randomStar** [comment]
Forget to run [job](https://github.com/langgenius/dify/blob/main/api/README.md?plain=1#L55)?

**Comment by Trangle** [comment]
> Can you provide detailed docker logs?

from: docker-api-1
<img width="1735" alt="image" src="https://github.com/langgenius/dify/assets/3235116/42d8d07f-22b4-41ba-a2d9-8dac1fcc92ee">

from: docker-web-1
<img width="1681" alt="image" src="https://github.com/langgenius/dify/assets/3235116/f7dc6ec8-7b83-4398-bfae-17a9b6f9eecd">

**Comment by Trangle** [comment]
> Forget to run [job](https://github.com/langgenius/dify/blob/main/api/README.md?plain=1#L55)?

do run in the web

**Comment by crazywoola** [comment]
I mean the logs from worker

**Comment by Trangle** [comment]
> I mean the logs from worker

<img width="1398" alt="image" src="https://github.com/langgenius/dify/assets/3235116/9ecabe6e-f9eb-4fce-8974-a3c221827633">
