### ISSUE TITLE
After upgrading xinference to 0.5.4, an error occurred when accessing model chat on the Dify platform

### ISSUE THREAD

**Issue by YinSonglin1997** [langgenius/dify#1408]
### Provide a description of the help you need

After upgrading xinference to 0.5.4, an error occurred when accessing the model chat on the Dify platform. When xinference==0.5.2, it was confirmed that there was no problem. Taking baichuan-2-chat as an example, the error was reported as follows:
![image](https://github.com/langgenius/dify/assets/90330685/9c9b070e-a136-40cb-86a4-6f612e116b27)
Is it because Dify uses an older version of xinference, which is incompatible with xinference 0.5.4?

**Comment by crazywoola** [comment]
If you are firing a bug report, please choose the right template to report an issue.
If you are using the latest CE version please wait for the week's release. We have already fix this.
https://github.com/langgenius/dify/commit/fb64fcb271caca9e3dc752ada3307ff1f2f50aaa

**Comment by YinSonglin1997** [comment]
> If you are firing a bug report, please choose the right template to report an issue. If you are using the latest CE version please wait for the week's release. We have already fix this. [fb64fcb](https://github.com/langgenius/dify/commit/fb64fcb271caca9e3dc752ada3307ff1f2f50aaa)

ok, it works.
