### ISSUE TITLE
移除模型密钥时，确认对话框被模型管理的弹出框覆盖，无法点击确认

### ISSUE THREAD

**Issue by syzjbs** [langgenius/dify#1409]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1.点击个人设置
2.选择模型供应商
3.选择一个AzureOpenAI Service的密钥点击移除

### ✔️ Expected Behavior

确认对话框可以弹出，点击确认移除模型的密钥

### ❌ Actual Behavior

确认对话框被个人设置页面覆盖，需要在浏览器修改个人设置界面的z-index和position属性才可以看见确认对话框

**Comment by zxhlyh** [comment]
fixed #1416
