### ISSUE TITLE
Conversational HuggingFace models?

### ISSUE THREAD

**Issue by lestrang1991** [langgenius/dify#1412]
### Description of the new feature / enhancement

are these models (conversational) something that you guys are considering? 

Have a user case for https://huggingface.co/facebook/blenderbot-400M-distill or https://huggingface.co/microsoft/GODEL-v1_1-large-seq2seq but these do not count as text2text gen nor text gen. 

### Scenario when this would be used?

Chatbot that impersonates known entities

**Comment by crazywoola** [comment]
Have you tried these 2 models? I have used some conversational huggging face models before. It worked for me.
