### ISSUE TITLE
Zilliz as vector db backend not work.

### ISSUE THREAD

**Issue by TheFu527** [langgenius/dify#1413]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted, Other (please specify in "Steps to Reproduce")

### Steps to reproduce

Self hosted but cloud version.

Use Zilliz as vector db.

### ✔️ Expected Behavior

It works.

### ❌ Actual Behavior

After uploading a file in the datasets, the file status is always indexing.

The log of dify-worker does not report any error information.

**Comment by JohnJyong** [comment]
pls set your zillizsetting as below：
```
MILVUS_HOST=*****.zillizcloud.com
MILVUS_PORT=19530
MILVUS_USER=your-user
MILVUS_PASSWORD=your-passwor
MILVUS_SECURE=True

```

**Comment by TheFu527** [comment]
Because MILVUS_USER, MILVUS_PASSWORD, MILVUS_PORT, etc. are not displayed on the web of zillizcloud.com. So I tried the Chinese version, but it didn't work.

```
  - name: MILVUS_HOST
    value: https://*******.ali-cn-hangzhou.vectordb.zilliz.com.cn
  - name: MILVUS_PORT
    value: "19530"
  - name: MILVUS_USER
    value: db_admin
  - name: MILVUS_PASSWORD
    value: MY_PWD
  - name: MILVUS_SECURE
    value: "true"
```
