### ISSUE TITLE
Set Default model provider using azure open AI env vars

### ISSUE THREAD

**Issue by ceq-abuzaid** [langgenius/dify#1414]
### Provide a description of the help you need

hello all , 
just wanted azure open AI to be the default model using the azure open ai env vars :
HOSTED_AZURE_OPENAI_ENABLED=True
HOSTED_AZURE_OPENAI_API_KEY=
HOSTED_AZURE_OPENAI_API_BASE=
HOSTED_AZURE_OPENAI_QUOTA_LIMIT=200
but got no changes although the values got read correctly from hosted_model_providers.azure_openai
so if you could help would be much appreciated

**Comment by crazywoola** [comment]
We designed these keys with the potential to implement this feature, but you've discovered it. ：）
