### ISSUE TITLE
文心一言构建对话应用回复有错误

### ISSUE THREAD

**Issue by deepslit** [langgenius/dify#1419]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/148514960/abf1f5c5-5fd3-4819-a2a2-607f36352ebb)
用completion的是正常的，但是用chat的时候一旦开始第二轮对话就会像这样。

### ✔️ Expected Behavior

human：你是谁
本应该回复：我是您的智能助手

### ❌ Actual Behavior

human：你是谁
实际回复：<chat> <histories> <history>
<user>Human</user>

<question>你是谁</question>

<response>我是您的智能助手</response>

</history>

**Comment by GarfieldDai** [comment]
Please paste your prompt message. @deepslit

**Comment by deepslit** [comment]
> Please paste your prompt message. @deepslit

I simply input "你是谁" twice in the web

**Comment by deepslit** [comment]
> > Please paste your prompt message. @deepslit
> 
> I simply input "你是谁" twice in the web

And no matter what I input, as long as it is a multiple round chat, it gives me the false output

**Comment by GarfieldDai** [comment]
@deepslit Please switch to 「Expert Mode」and try again.

**Comment by deepslit** [comment]
> @deepslit Please switch to 「Expert Mode」and try again.

SOLVED! Change the default template in expert mode to:
 {{#histories#}}
Human: {{#query#}}
Assistant: 

Now I can chat with ernie.
