### ISSUE TITLE
能否支持统一身份认证

### ISSUE THREAD

**Issue by luweizheng** [langgenius/dify#1420]
### Description of the new feature / enhancement

本地化的部署能否支持 LDAP、OAuth 之类的统一身份认证？

### Scenario when this would be used?

本地化部署

**Comment by waltcow** [comment]
我就加个logto 改下就可以了

**Comment by sevenjay** [comment]
> 我就加个logto 改下就可以了
How should it be modified to add?
請問要怎麼改呢？

**Comment by sevenjay** [comment]
> 我就加个logto 改下就可以了

@waltcow  How should it be modified to add?
請問要怎麼改呢？

**Comment by liudhzhyym** [comment]
同问
