### ISSUE TITLE
docker部署的服务，修改了上传文件的大小限制，上传失败

### ISSUE THREAD

**Issue by lilinrestart** [langgenius/dify#1421]
### Provide a description of the help you need

提示文件上传失败
![image](https://github.com/langgenius/dify/assets/140720825/ffea6346-e337-4071-babb-4415ab31a702)

**Comment by lilinrestart** [comment]
修改成50m限制也是上传失败...

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/1405

得看你的云平台是不是有限制，我不是很清楚的你的部署方式，如果默认使用我们的配置是没有问题的，但是你改了 70 端口，那么我猜测是你自己也有一个  nginx  或者什么东西在前面，你需要修改这个的配置，前端反向代理的那个上传的配置，修改我们这边 nginx 是没有用的。请勿重复提交   issue，你可以  reopen  之前的。
