### ISSUE TITLE
Integration With Amazon Bedrock

### ISSUE THREAD

**Issue by MirzaAreebBaig** [langgenius/dify#1422]
### Description of the new feature / enhancement

Integration with available models at "Amazon Bedrock" = https://aws.amazon.com/bedrock/claude/

### Scenario when this would be used?

This can be utilised to access models which are available or going to be available in near future with amazon bedrock

**Comment by crazywoola** [comment]
We are working hardly on this. 👍  See this in next few releases.

**Comment by MirzaAreebBaig** [comment]
Hey,
That's great to know about this & when can we expect the plugins feature? Because this would be a major problem solving feature for overall application.

**Comment by crazywoola** [comment]
> Hey, That's great to know about this & when can we expect the plugins feature? Because this would be a major problem solving feature for overall application.

Actually this have been discussed a lot inside/outside the team and we are reworking our fundamental  functions to support this feature. Hopefully this will be in future releases as well.

**Comment by MirzaAreebBaig** [comment]
Hello,
Is the Amazon Bedrock integration available now?
