### ISSUE TITLE
数据集文档上传是中文 解析出来是英文

### ISSUE THREAD

**Issue by yuanhaishan** [langgenius/dify#1423]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

数据集上传文档 文档中是中文的

### ✔️ Expected Behavior

解析出来是中文

### ❌ Actual Behavior

解析出来是英文
![image](https://github.com/langgenius/dify/assets/53658688/da1e1921-1e86-465b-89cc-d3557fba6300)

**Comment by quchenchen** [comment]
目前未修复。中英文混合现象。

**Comment by crazywoola** [comment]
Close due to the latest topic https://github.com/langgenius/dify/issues/1918
