### ISSUE TITLE
Datasets > linked apps：App icon displays abnormally  

### ISSUE THREAD

**Issue by Hickays** [langgenius/dify#1424]
### Dify version

0.3.28

### Cloud or Self Hosted

Cloud

### Steps to reproduce

数据集 > 关联应用列表: 应用图标显示异常
![image](https://github.com/langgenius/dify/assets/114720595/9a926ada-6030-4eda-893a-5c8f63c24d9c)
![image](https://github.com/langgenius/dify/assets/114720595/a8e695bf-4d0f-47c6-a5fd-7c9502df5f98)

**Comment by crazywoola** [comment]
Hello can you add my wechat: crazyphage 👍  I will add you to the chat group of developers.
