### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by Annonemus** [langgenius/dify#1430]
### Dify version

0.3.23

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

-host dify (in my case over google cloud)
-add multiple datasets (the context I used includes 32 datasets having between 10k-100k words)
-create a chat app, which is supposed to be a user assistant, using specific data provided by the context to answer complex questions about a product
-open the public URL for the WebApp
-ask a question, the error usually occurs when the answer provided by the AI is rather long

![image](https://github.com/langgenius/dify/assets/39418552/a773e71b-653b-4e19-830c-9319dc05d68f)

### ✔️ Expected Behavior

Question is answered and the answer stays in the chat.

### ❌ Actual Behavior

While streaming the answer to the question, an error sometimes occurs and the answer is deleted.
The error message is:
"APIError. The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. Please include the request ID 6885ee19ccf636428e6a45c5cec9c21f in your email.) (Error occured while streaming.)"

Note: i already contacted help.openai.com to no avail, which is why i am currently trying to disable streaming mode since this seems to be the cause of the issue.

**Comment by crazywoola** [comment]
Did you check your OpenAI account type and have access to your chosen model? Eg. gpt-4.
If you do have a blocking mode in the chat area, the page would be no response for a very long time because of the long answer takes more than 2-3 minutes to complete, which is not acceptable for the user experience.
