### ISSUE TITLE
Latin Characters on datasets not parsing

### ISSUE THREAD

**Issue by brunompicinini** [langgenius/dify#1431]
### Dify version

0.3.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Import files with latin characters such as Ã É Ê

### ✔️ Expected Behavior

Correctly read words such as "sofisticação"

### ❌ Actual Behavior

They show up like this: "sofisticao"

**Comment by takatost** [comment]
Sorry for not being able to fix the issue in a timely manner. It has been fixed now, and you can try upgrading after we create version v0.4.7. 😊
