### ISSUE TITLE
请问是否有开发文档？

### ISSUE THREAD

**Issue by lilinrestart** [langgenius/dify#1433]
### Provide a description of the help you need

我用docker部署项目，开启来源引用，但是不太正确；我是否能修改底层代码，在切片中添加文档的oss链接，在引用的地方直接跳转到文档中？如果能修改那是在哪个地方呢，不胜感激：）

**Comment by crazywoola** [comment]
We do not have such kind of documents right now. 
https://github.com/langgenius/dify/blob/42a5b3ec1754bc73cc369bbffc2dcac4c67fb8f9/api/core/tool/dataset_retriever_tool.py#L23
If you are interested in dataset retriever, you can have a look at codes above.

**Comment by lilinrestart** [comment]
> 我们目前没有此类文件。
> 
> https://github.com/langgenius/dify/blob/42a5b3ec1754bc73cc369bbffc2dcac4c67fb8f9/api/core/tool/dataset_retriever_tool.py#L23
> 
> 
> 如果您对数据集检索器感兴趣，可以查看上面的代码。

谢谢
