### ISSUE TITLE
Azure OpenAPI 配置成功，但是运行时提示：Incorrent API key provided

### ISSUE THREAD

**Issue by tonglei100** [langgenius/dify#144]
Dify version: Self Host

## Steps To Reproduce

1. 配置成功
![image](https://github.com/langgenius/dify/assets/530089/bf2c75c3-7af4-491e-8946-e2de325bb91b)

2. 创建App，运行，提示：
![image](https://github.com/langgenius/dify/assets/530089/1d36df4b-55fe-4ed1-9ebc-4fd5f94c6f20)

**Comment by takatost** [comment]
拉取一下最新版本镜像或者代码哦，这边已经做了修改，以及参考一下 faq 最后一条配置 Azure：https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq
