### ISSUE TITLE
Replace default OpenAI API base url with the custom one

### ISSUE THREAD

**Issue by Andywugh** [langgenius/dify#1442]
### Description of the new feature / enhancement

Hi there, just to confirm are there any existing functions that can modify the OpenAI API base URL so far? If not, can we support it? Or actually we just only recommend using Azure OpenAI API instead?

### Scenario when this would be used?

For some reason, like in some countries, we can't access OpenAI API services directly, so generally we only can access them by following:
1. Some similar OpenAI API proxy services built by someone in their countries for access instead;
2. Overseas VPN services;

**Comment by crazywoola** [comment]
Yes, see the docs here. https://docs.dify.ai/getting-started/install-self-hosted/environments#openai_api_base

**Comment by Andywugh** [comment]
I see, your guide is mainly for self-hosted deployments, but it isn't supported in the public cloud version, right? @crazywoola

**Comment by crazywoola** [comment]
> I see, your guide is mainly for self-hosted deployments, but it isn't supported in the public cloud version, right? @crazywoola

Yes because the cloud service requires VPN recent days as well.
