### ISSUE TITLE
zhipu ai model code need update

### ISSUE THREAD

**Issue by zmingchun** [langgenius/dify#1443]
### Description of the new feature / enhancement

need update the zhipu ai model code

### Scenario when this would be used?

update the zhipu ai model code

### Supporting information

智谱AI公告：
尊敬的用户，智谱 AI 开放平台标准版服务全面升级，上线 ChatGLM-Turbo 新模型，模型 API 调用价格再降50%至0.005元/千tokens；同时新模型推理速度提升2-3倍，推理成本降低一倍，推理效果更优。
为确保您的使用不受影响，我们预留了一个月的缓冲期。在2023年11月30日之前，您更换新的模型编码即可。在此日期后，Pro、Std、Lite 模型将完全下线，不再进行维护。因此，请您尽快更换模型编码，以确保服务的正常运行。

**Comment by takatost** [comment]
supported in #1460
