### ISSUE TITLE
npm run start本地源码启动，进入登录页面账号在哪里获取？请求帮助 谢谢

### ISSUE THREAD

**Issue by lilinrestart** [langgenius/dify#1445]
### Provide a description of the help you need

npm run start本地源码启动，进入登录页面账号在哪里获取？
![image](https://github.com/langgenius/dify/assets/140720825/8beeed61-a7e0-42c3-9f0f-5b04c77b52c1)

当我使用/install进去出现了错误
![image](https://github.com/langgenius/dify/assets/140720825/5ad0bd98-f8d9-4b48-90c8-d4136ae26e30)

请求帮助 谢谢

**Comment by crazywoola** [comment]
[See this for  details](https://docs.dify.ai/v/zh-hans/getting-started/faq/install-faq#1.-ben-di-bu-shu-chu-shi-hua-hou-mi-ma-cuo-wu-ru-he-zhong-zhi)
