### ISSUE TITLE
0.3.13 版本60S超时问题

### ISSUE THREAD

**Issue by zfno111** [langgenius/dify#1446]
### Provide a description of the help you need

目前版本是0.3.13
使用api 目前60s就会超时。  请问下这个配置需要如何修改呢？
（目前已经确定不是nginx问题  是api端主动断开的）

**Comment by crazywoola** [comment]
云端版本也是吗？

**Comment by ze00ro** [comment]
openai_model.py 里有个 request_timeout, 那里设置的 60s

**Comment by ze00ro** [comment]
不过我设置到240仍然偶尔 timeout, 
然后我加了个 retry=2, 但是程序走到retry的时候会报错. 说callback没有on_retry方法.
但是看langchain的callback接口里也没有on_retry啊?

**Comment by crazywoola** [comment]
To better assist you and to accurately reproduce the scenario you're facing, we would greatly appreciate it if you could provide us with a few more details regarding your setup.

Could you kindly share the following information:

The exact steps you followed leading up to the issue.
The parameters and arguments you used when encountering the problem.
The specific model and configuration you are utilizing.
Any other context or settings that might be relevant.

**Comment by zfno111** [comment]
openai_model.py 里有个 request_timeout, 那里设置的 60s 通过修改这个参数有效 希望后期版本把这个参数提炼到config里面， 目前docker 只能把这个配置映射出来处理 比较麻烦。
