### ISSUE TITLE
Support Spark V3.0 & Embedding

### ISSUE THREAD

**Issue by WinterOfBit** [langgenius/dify#1447]
### Description of the new feature / enhancement

Impl for Spark V3.0 & embedding

希望可以用上讯飞星火3.0和星火embedding

### Scenario when this would be used?

Model Provider

### Supporting information

https://console.xfyun.cn/services/bm3

https://console.xfyun.cn/services/aidoc

**Comment by crazywoola** [comment]
This is working in progress, we will release this feature later.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/1434
