### ISSUE TITLE
增加多个上下文

### ISSUE THREAD

**Issue by lilinrestart** [langgenius/dify#1449]
### Description of the new feature / enhancement

希望可以在这里添加多个上下文，不只是一个
![image](https://github.com/langgenius/dify/assets/140720825/79d5f9bc-4534-4087-9306-90ec37c9d8b4)

### Scenario when this would be used?

存储多套灵活使用的prompt模板

**Comment by crazywoola** [comment]
你可以切换到专家模式试试，的确是两个上下文。
