### ISSUE TITLE
The confirm modal for removing a model not showing

### ISSUE THREAD

**Issue by jsonjuri** [langgenius/dify#1456]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

When removing a model the confirm modal appears behind the settings modal and is not visible. The only way now is to remove the settings modal in developer toolbar.

Settings -> Model Provider -> Hugging Face -> Dots icon -> Remove

### ✔️ Expected Behavior

The modal to be in front of the settings modal.

### ❌ Actual Behavior

The modal opens behind the settings modal.

**Comment by crazywoola** [comment]
We will fix this in v0.3.29. :)
