### ISSUE TITLE
[Request For New Feature] Support InternLM Model 

### ISSUE THREAD

**Issue by crazysteeaam** [langgenius/dify#1457]
### Description of the new feature / enhancement

Do you have the plan to support InternLM-7B & InternLM-20B?
(https://github.com/InternLM/InternLM)

### Scenario when this would be used?

We'd love to provide technical support and other forms of assistance where needed.
Thanks!

**Comment by crazywoola** [comment]
Sorry, we do not have a plan for this yet. We are working on refactoring dify core for now. After this we will working on other LLMs.
