### ISSUE TITLE
星火，千问等非openai模型绑定本地数据集，回答时只会回答数据集内容

### ISSUE THREAD

**Issue by asdhq** [langgenius/dify#1458]
### Dify version

0.3.24

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/29561285/c78bd0dd-4242-46dd-91f6-0898eb957052)

**Comment by asdhq** [comment]
绑定openai，azure_openai模型可以正常回答，但是绑定其他大语言模型，添加本地数据后，只会回复本地数据集的内容。

**Comment by crazywoola** [comment]
> 绑定openai，azure_openai模型可以正常回答，但是绑定其他大语言模型，添加本地数据后，只会回复本地数据集的内容。

The answers are replied from LLMs, so you should open an issue there.
