### ISSUE TITLE
上传数据集后，一直没有正常切片，一直卡在排队中

### ISSUE THREAD

**Issue by ARESJIFANG** [langgenius/dify#1466]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

上传一个数据集文档。pdf文件或者docx文件。一直卡在排队中。

### ✔️ Expected Behavior

能够像在线版本正茬对文档进行向量化

### ❌ Actual Behavior

一直卡在排队中，可以删除任务。但是新建的任务一直都是排队中
<img width="1438" alt="Xnip2023-11-06_20-45-31" src="https://github.com/langgenius/dify/assets/124765247/d4fa90fd-63d7-41a5-b120-11e70b66a51c">

**Comment by crazywoola** [comment]
Are you using `docker compose up`?

**Comment by ARESJIFANG** [comment]
yes

**Comment by crazywoola** [comment]
Can you provide logs regarding to this issue
