### ISSUE TITLE
我想问下 API 可以只获取一个应用的数据吗？

### ISSUE THREAD

**Issue by skykiah** [langgenius/dify#147]
我想问下 API 可以只获取一个应用的数据吗，我看API文档，只有根据conversation_id 获取会话，但是没有区分应用的字段呀

**Comment by JohnJyong** [comment]
你好，每个应用生成的API密钥是不同，你可以使用不同应用的api token来获取不同应用的数据。
![image](https://github.com/langgenius/dify/assets/76649700/b92e39ea-a1f2-4b39-93cc-877dcef88010)
![image](https://github.com/langgenius/dify/assets/76649700/93747891-a8a4-4da8-8a53-5efd6df26061)

**Comment by skykiah** [comment]
> 你好，每个应用生成的API密钥是不同，你可以使用不同应用的api token来获取不同应用的数据。 ![image](https://user-images.githubusercontent.com/76649700/239837195-b92e39ea-a1f2-4b39-93cc-877dcef88010.png) ![image](https://user-images.githubusercontent.com/76649700/239837323-93747891-a8a4-4da8-8a53-5efd6df26061.png)

明白。。

**Comment by mjmkk** [comment]
能用api获取所有应用的apikey吗
