### ISSUE TITLE
openai模型列表中没有最新的gpt-4-1106-preview模型

### ISSUE THREAD

**Issue by seafarer2008** [langgenius/dify#1471]
### Dify version

0.3.29

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/17995251/2f0fe7f4-f9f9-44bd-bb0b-2f50e68dfb8f)
apikey更换重新配置过。

### ✔️ Expected Behavior

希望能尽快加上最新的gpt-4-1106-preview模型

### ❌ Actual Behavior

未列出gpt-4-1106-preview等最新发布的模型

**Comment by crazywoola** [comment]
We will add these models in later releases. Please be patient.

**Comment by TigrisRiva** [comment]
希望尽快添加。感谢开发者的努力

**Comment by chenyhd** [comment]
Dify is awesome, it helps us save a lot of time

If the administrator can add any model, that would be great. Currently, it seems that once a new model is released, the entire project needs to be updated.

Thank you!

**Comment by crazywoola** [comment]
> Dify is awesome, it helps us save a lot of time
> 
> If the administrator can add any model, that would be great. Currently, it seems that once a new model is released, the entire project needs to be updated.
> 
> Thank you!

Yes because some providers also have some breaking changes. It needs to update the deps as well.
