### ISSUE TITLE
When I integrate using the bubble chatbox, I cannot clear the history records.

### ISSUE THREAD

**Issue by chenyhd** [langgenius/dify#1475]
### Description of the new feature / enhancement

When Dify embeds into my website using the bubble chatbox style, I found it difficult to clear the chat history effectively. Even refreshing doesn't work. Can you add a reset session function?

If add a clean button, It would be greate
![image](https://github.com/langgenius/dify/assets/18431131/3932124b-6549-49d9-9449-2ebac2569267)

### Scenario when this would be used?

When customers want to ask a new question or refresh the page, they hope to start a new conversation.

**Comment by crazywoola** [comment]
Duplicate #1417
