### ISSUE TITLE
after upgrade to 0.3.29 智聊 cannot work

### ISSUE THREAD

**Issue by zmingchun** [langgenius/dify#1478]
### Dify version

0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/1988270/e7bc714e-19e7-4602-ae34-f25955eff377)
as the picture say

### ✔️ Expected Behavior

can use

**Comment by crazywoola** [comment]
Please provide the logs of the container.

**Comment by crazywoola** [comment]
I've tried reinstall the application, can't reproduce.
