### ISSUE TITLE
vector store是否支持milvus？

### ISSUE THREAD

**Issue by Single-noble** [langgenius/dify#1479]
### Provide a description of the help you need

.env.example 第53行注释中提到支持weaviate, qdrant, milvus
api/config.py 第127行注释中提到仅支持weaviate, qdrant
有些矛盾了

**Comment by crazywoola** [comment]
Yes, please checkout this [doc](https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/environments#xiang-liang-shu-ju-ku-pei-zhi)
