### ISSUE TITLE
Assistants Open ai 

### ISSUE THREAD

**Issue by ferstpetr777** [langgenius/dify#1481]
### Description of the new feature / enhancement

colleagues, can you please tell me if the Assistants will be integrated into the dify program? https://platform.openai.com/docs/assistants/overview
Update has been released Open ai

### Scenario when this would be used?

https://youtu.be/U9mJuUkhUzk

**Comment by crazywoola** [comment]
Yes

**Comment by Korayem** [comment]
Game changer!
