### ISSUE TITLE
Metadata of docment is not correctly displayed in detail page

### ISSUE THREAD

**Issue by lethe3000** [langgenius/dify#1483]
### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1. goto any document detail page
2. fill metadata form and save
3. refresh document detail page, the metadata panel remains empty and asks for "Please select a document type"

in step 3, I can see api: /console/api/datasets/<id:dataset_id>/documents/<id:doc_id>?metadata=only
is called with response
`
{
    "id": "<uuid>",
    "doc_type": "web_page",
    "doc_metadata": {
        "title": "<title of metadata>",
        "url": "https://www.example.com",
        "language": "zh"
    }
}
`

### ✔️ Expected Behavior

if metadata is set, metadata panel should display what I've filled.

### ❌ Actual Behavior

No metadata is displayed, the page still asks to fill in.

**Comment by crazywoola** [comment]
This bug has been fixed since v0.3.29 see this PR https://github.com/langgenius/dify/pull/1429
