### ISSUE TITLE
上传数据集后一直是排队中

### ISSUE THREAD

**Issue by yozyan** [langgenius/dify#1488]
### Dify version

0.3.29

### Cloud or Self Hosted

Cloud

### Steps to reproduce

上传本地文件，无论是使用openAI做矢量化，还是使用离线向量做矢量化，文件始终在排队中
<img width="1422" alt="image" src="https://github.com/langgenius/dify/assets/45024500/3bbdf898-f357-43e5-8aca-8a58f00e0ba0">

### ✔️ Expected Behavior

文件上传完成后，能从排队中的状态变为可使用状态，在应用中可以被使用到

### ❌ Actual Behavior

始终在排队

**Comment by Trangle** [comment]
你试试能不能删除，包括数据集能不能删除

**Comment by ViperGash** [comment]
我也是在排队。而且无法应用。返回始终是空的。

**Comment by tsiens** [comment]
可能是向量数据库卡了，docker restart dify-db-1就好了

**Comment by hparenas** [comment]
@yozyan 楼主问题有解决方案了吗？我也碰到了这个问题，您是用的Dify的云服务版本吧？

**Comment by Mingxiangyu** [comment]
> 可能是向量数据库卡了，docker restart dify-db-1就好了

重启了向量数据库还是不行，通过dockercompose启动的

**Comment by FVCSAV** [comment]
请问解决了吗

**Comment by Mingxiangyu** [comment]
> 请问解决了吗

解决了，我是嵌入模型选错了，用了qwen的chat模型，导致嵌入失败，所以一直排队，后来用了ollama跑的嵌入模型，就可以索引向量完成了。不过还是要吐槽下，dify的知识库更换嵌入模型太难找了，而且第一次选完后，后面在创建时候就没有选择项了，太难弄!! @cainiaokan

**Comment by xiahao90** [comment]
@Mingxiangyu 你好，我设置了文心一言和通义千问，在知识库进行了切换，等一会看还是排队中呢？麻烦看你的设置呢

**Comment by wentao-uw** [comment]
```
# ------------------------------
# Server Configuration
# ------------------------------

# The log level for the application.
# Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
LOG_LEVEL=INFO
# Log file path
LOG_FILE=/app/logs/server.log
# Log file max size, the unit is MB
LOG_FILE_MAX_SIZE=20
# Log file max backup count
LOG_FILE_BACKUP_COUNT=5
# Log dateformat
LOG_DATEFORMAT=%Y-%m-%d %H:%M:%S
```
可能是.env文件里面的LOG_FILE没有设置， @xiahao90

**Comment by charliex2** [comment]
> ```
> # ------------------------------
> # Server Configuration
> # ------------------------------
> 
> # The log level for the application.
> # Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
> LOG_LEVEL=INFO
> # Log file path
> LOG_FILE=/app/logs/server.log
> # Log file max size, the unit is MB
> LOG_FILE_MAX_SIZE=20
> # Log file max backup count
> LOG_FILE_BACKUP_COUNT=5
> # Log dateformat
> LOG_DATEFORMAT=%Y-%m-%d %H:%M:%S
> ```
> 
> 可能是.env文件里面的LOG_FILE没有设置， @xiahao90

设置了 LOG_FILE 的确就可以了，非常感谢

**Comment by Mingxiangyu** [comment]
> @Mingxiangyu 你好，我设置了文心一言和通义千问，在知识库进行了切换，等一会看还是排队中呢？麻烦看你的设置呢

你是不是没启动celery？

**Comment by ChaoGuo** [comment]
我遇到的原因是一个worker异常退出，重启后OK

**Comment by heshixiancn** [comment]
![Image](https://github.com/user-attachments/assets/d1731579-978d-4384-b49e-84296be9c1fe)

去除掉这段启动命令就可以了

**Comment by YoshuaBengio** [comment]
# ------------------------------
# Server Configuration
# ------------------------------

# The log level for the application.
# Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
LOG_LEVEL=INFO
# Log file path
LOG_FILE=/app/logs/server.log
# Log file max size, the unit is MB
LOG_FILE_MAX_SIZE=20
# Log file max backup count
LOG_FILE_BACKUP_COUNT=5
# Log dateformat
LOG_DATEFORMAT=%Y-%m-%d %H:%M:%S

配置了LOG_FILE，还是在排队，怎么整，大佬们，求帮忙

**Comment by wlpepsi** [comment]
也可能是pg migration的问题。我是按照如下步骤修复了

-- 进入 PostgreSQL 数据库容器
psql -U postgres
-- 切换到目标数据库
\c dify
-- 删除 alembic_version 表中的记录
DELETE FROM alembic_version;
-- 或者直接删除表（需谨慎）
DROP TABLE alembic_version;

worker容器中：
flask db upgrade
