### ISSUE TITLE
Route specific external apis based on user-specific tasks.

### ISSUE THREAD

**Issue by yuhaowin** [langgenius/dify#1489]
### Description of the new feature / enhancement

I experimented with the 'external_data_tool' feature and found that it's quite useful. However, I noticed that 'dify' consistently triggers external API calls whenever a user sends a message.

### Scenario when this would be used?

As above.

**Comment by crazywoola** [comment]
To better assist you and to accurately reproduce the scenario you're facing, we would greatly appreciate it if you could provide us with a few more details regarding your setup.

Could you kindly share the following information:

The exact steps you followed leading up to the issue.
The parameters and arguments you used when encountering the problem.
The specific model and configuration you are utilizing.
Any other context or settings that might be relevant.

**Comment by takatost** [comment]
Yeah, that's how it's currently designed. We'll add an Agent auto-selection strategy later.
