### ISSUE TITLE
chatglm_turbo与微软和claude的模型返回数据不一致

### ISSUE THREAD

**Issue by gnfy** [langgenius/dify#1495]
### Dify version

0.3.29

### Cloud or Self Hosted

Cloud

### Steps to reproduce

chatglm的返回：
![image](https://github.com/langgenius/dify/assets/726666/3b5b545d-b806-4ba7-a780-64aa2919ff00)
claude的返回：
![image](https://github.com/langgenius/dify/assets/726666/ac72e551-5bf4-4de3-972c-2088f60e86cb)
微软的返回：
![image](https://github.com/langgenius/dify/assets/726666/c91db545-a2a5-4ad2-b66c-45dc3730826b)

### ✔️ Expected Behavior

期待结果：
chatglm返回数据与其它的一致。

### ❌ Actual Behavior

无

**Comment by takatost** [comment]
Each model returns differently, so we need to design prompts for each model. This is as expected.
