### ISSUE TITLE
添加模型供应商 Xinference失败

### ISSUE THREAD

**Issue by wyyzhyx** [langgenius/dify#1499]
### Dify version

0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

我在本地的Windows上用docker部署了github上的dify项目https://github.com/langgenius/dify，用wsl部署了github上的Xinference项目https://github.com/xorbitsai/inference；两个项目单独部署都成功了。我在网页上打开的Xinference的UI地址是http://127.0.0.1:9997/8ec5d4b0-7eee-11ee-a323-b5ae4a93183e/。但是在Dify设置，接入模型供应商，选择Xinference的时候，总是报错：No connection adapters were found for '127.0.0.1:9997/v1/models/8ec5d4b0-7eee-11ee-a323-b5ae4a93183e'。我的hostname：172.31.48.14；我估计是我模型存储的位置不是默认的v1/models/位置，但是我不知道哪里去修改，最好是能在dify中修改，请帮帮我，谢谢

**Comment by charSLee013** [comment]
因为是用`docker`部署的dify，所以对于dify 来讲`127.0.0.1`就是容器内的本地地址而不是宿主机的`127.0.0.1`

尝试在wsl 中访问 [http://172.31.48.14:9997/](http://172.31.48.14:9997/ ) 是否能正常访问
如果可以则在设置Xinference的时候127.0.0.1 改为172.31.48.14 验证是否有效

**Comment by crazywoola** [comment]
Please read the [doc](https://docs.dify.ai/v/zh-hans/advanced/model-configuration/xinference#shi-yong-qian-zhu-yi-shi-xiang) for details
