### ISSUE TITLE
【需求】文本生成型应用增加变量的信息说明内容维护

### ISSUE THREAD

**Issue by chenshuobin** [langgenius/dify#15]
解决谁的问题：文本生成型应用的新用户
痛点：对于一个新用户来说，应用的概览介绍信息对于某些复杂场景下的应用——即变量自由度较高，对参数内容、格式有一定要求的应用来说，并不足以说明应用的使用方法，应该在应用提供服务时，提供精确到变量维度的文本说明信息配置功能。
需求内容：
以图片为例
![image](https://github.com/langgenius/dify/assets/65551832/c3a19008-be37-4d99-8ba7-2f6be37b2245)

**Comment by crazywoola** [comment]
We do not support such kinds of fields yet.
