### ISSUE TITLE
QA分割正则问题

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1501]
### Dify version

0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

<img width="626" alt="截屏2023-11-10 12 11 41" src="https://github.com/langgenius/dify/assets/1925650/d5b5b0e9-0295-43d8-86af-432f2bf58536">

这边正则对下面的QA内容会截取部分：
`
Q1:低碳饮食，需要补充的8种营养补充剂怎么吃
A1:1：苹果醋胶囊。（餐前吃）
2：B族维生素（营养性酵母）（餐前吃）
3：维生素D+K2（餐前吃）
4：益生菌（晚餐前吃）
5：钾片（缓释片）（餐前、睡前）
6：镁片（睡前吃）
7：维生素C（早餐前吃）
8；锌片（晚餐餐前吃）
`
结果变成：
`
question:低碳饮食，需要补充的8种营养补充剂怎么吃
answer:1：苹果醋胶囊。（餐前吃）
`

改成这样就正常：
`
regex = r"Q\d+:\s*(.*?)\s*A\d+:\s*([\s\S]*?)(?=Q\d+:|$)"
matches = re.findall(regex, text, re.UNICODE)
`

### ✔️ Expected Behavior

question:低碳饮食，需要补充的8种营养补充剂怎么吃
answer:1：苹果醋胶囊。（餐前吃）
2：B族维生素（营养性酵母）（餐前吃）
3：维生素D+K2（餐前吃）
4：益生菌（晚餐前吃）
5：钾片（缓释片）（餐前、睡前）
6：镁片（睡前吃）
7：维生素C（早餐前吃）
8；锌片（晚餐餐前吃）

### ❌ Actual Behavior

`
question:低碳饮食，需要补充的8种营养补充剂怎么吃
answer:1：苹果醋胶囊。（餐前吃）
`

**Comment by crazywoola** [comment]
You can open a pull request for this.
