### ISSUE TITLE
升级到0.3.29智聊报错

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1502]
### Dify version

0.3.29

### Cloud or Self Hosted

Cloud

### Steps to reproduce

代码：
<img width="777" alt="image" src="https://github.com/langgenius/dify/assets/1925650/41c7eed8-d8fc-441e-a1ce-e577988e6e5e">
<img width="706" alt="image" src="https://github.com/langgenius/dify/assets/1925650/45155d71-08de-4d4d-8d26-9d3aeff1eeb5">

错误日志：
<img width="758" alt="image" src="https://github.com/langgenius/dify/assets/1925650/dc441c8a-4ac8-409c-941c-3f6c63245470">

### ✔️ Expected Behavior

可以正常打开：
<img width="914" alt="image" src="https://github.com/langgenius/dify/assets/1925650/9c77542c-093e-4003-bc0a-1e4309426aa7">

### ❌ Actual Behavior

<img width="610" alt="image" src="https://github.com/langgenius/dify/assets/1925650/5bd3365d-8f34-4cd2-a5b0-e4153c25d1c0">

接口报错：/console/api/universal-chat/conversations?limit=100
<img width="394" alt="image" src="https://github.com/langgenius/dify/assets/1925650/51f814c2-cc94-46aa-b2d8-3d5afbae406d">

**Comment by takatost** [comment]
You're right, we have fixed this issue and it will be released in the next version. 
If you're in a hurry, you can directly replace the image version in the `docker-compose.yaml` file with the latest main `commit id`.
