### ISSUE TITLE
模型列表为空，无法“智聊”

### ISSUE THREAD

**Issue by qiankunli** [langgenius/dify#1504]
### Dify version

0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

![img_v3_0252_8be73c38-59e5-4bfe-9540-5dc130a6d64g](https://github.com/langgenius/dify/assets/8024725/1240b706-2c6e-454b-b0d6-54fd5cd4448c)

### ✔️ Expected Behavior

可以正常出现模型列表

### ❌ Actual Behavior

模型列表为空

**Comment by crazywoola** [comment]
Please config the provider first on the top right corner.

**Comment by qiankunli** [comment]
> Please config the provider first on the top right corner.

这个我是配了的
