### ISSUE TITLE
gpt-3.5-turbo-1106的单次回复限制上限值定义错误

### ISSUE THREAD

**Issue by WeeAris** [langgenius/dify#1505]
### Dify version

0.3.29

### Cloud or Self Hosted

Cloud

### Steps to reproduce

在应用设置中依次打开"提示词编排"，"模型及参数"

### ✔️ Expected Behavior

gpt-3.5-turbo-1106模型的单次回复限制的上限被错误得定义为16384

### ❌ Actual Behavior

根据[文档](https://platform.openai.com/docs/models/gpt-3-5)，正确值应为4096，即最大可以输入长达16384的内容，但输出和gpt-4-1106-preview一样被限制为4096，实测设置超过4096的值也确实会报错。

根据文档说明，自2023年12月11日起gpt-3.5-turbo和gpt-3.5-turbo-16k都将指向gpt-3.5-turbo-1106，建议暂时将gpt-3.5-turbo-0613和gpt-3.5-turbo-16k-0613单独列出，供暂时还有需求的用户使用，直至2024年6月其终止服务。

**Comment by crazywoola** [comment]
Duplicate https://github.com/langgenius/dify/issues/1497 we will fix this later.
