### ISSUE TITLE
浏览器窗口在左右半分屏和全屏之间切换时生成式应用会自动重新生成回复

### ISSUE THREAD

**Issue by WeeAris** [langgenius/dify#1507]
### Dify version

0.3.29

### Cloud or Self Hosted

Cloud

### Steps to reproduce

创建一个生成式应用，输入内容并生成结果（带必填参数的应用不输入任何内容也可以复现），此时拖动Google Chome浏览器窗口在左右半分屏和全屏之间切换，应用布局随之在竖屏和横屏间自动切换，进而触发重新生成结果的行为（如果参数为空也会发出警告，如果正在生成也会触发）。该行为也在Firefox中复现成功。

### ✔️ Expected Behavior

前端不应随浏览器窗口比例的变化而刷新已生成的结果，导致重复请求。

**Comment by iamjoel** [comment]
Fixed with #1908.
