### ISSUE TITLE
是否计划支持接入华为盘古大模型

### ISSUE THREAD

**Issue by DatumWorld** [langgenius/dify#1508]
### Description of the new feature / enhancement

华为盘古大模型已经开放。是否计划支持接入华为盘古大模型？
The panguLM developed by Huawei had been published. Is there the plan for it ?
 Refer to ：https://www.huaweicloud.com/product/pangu.html

### Scenario when this would be used?

For  NLP  CV etc.

**Comment by takatost** [comment]
Nah, no plans for that at the moment. But don't worry, we'll soon come up with a more convenient solution for integrating your own models.

**Comment by GoziKong** [comment]
Hello guys! Perhaps four days ago, I submitted a request for the new model. Would you like to check it? I felt it should come quickly. What are your thoughts? :)) 

check here: https://github.com/langgenius/dify/issues/1611

**Comment by ParseDark** [comment]
> Nah, no plans for that at the moment. But don't worry, we'll soon come up with a more convenient solution for integrating your own models.↳

I just read dify code. I think it's posiable for use the extension solution support the custom self-integrating model provider.  The extension solution is a great job in this project.
