### ISSUE TITLE
Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff994557160>, 'Connection to api.openai.com timed out. (connect timeout=5)'))

### ISSUE THREAD

**Issue by Hu-Pei** [langgenius/dify#1514]
### Provide a description of the help you need

本地部署，设置了代理为什么还是会报这个错啊？

**Comment by takatost** [comment]
Hey, can you please check if you can access the OpenAI API?

**Comment by Hu-Pei** [comment]
访问不了，但是我在服务器上请求google是成功的，不知道为什么！

**Comment by takatost** [comment]
You need to run Dify in an environment that has access to the OpenAI API. 😊

**Comment by Hu-Pei** [comment]
请问API 扩展怎么使用，我试了文档也没有成功！

**Comment by Hu-Pei** [comment]
(base) [root@cdh-2 docker]# uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/dfs/dify/dify-main/docker']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [2302573] using WatchFiles
INFO:     Started server process [2302576]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
我这也启动成功了访问不了

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/694#issuecomment-1659467959
