### ISSUE TITLE
0.3.21-->0.3.29升级后，原有数据集不可用，且无法编辑

### ISSUE THREAD

**Issue by sapipoZZZ** [langgenius/dify#1517]
### Dify version

0.3.21-->0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

本地docker版从0.3.21-->0.3.29升级后，（通过修改docker-compose.yaml 中的docker版本）

原有可用的数据集不再可用，且无法编辑，也没有添加文件按钮
![image](https://github.com/langgenius/dify/assets/19617283/a2a05e3c-a467-486c-81f5-f8fc3832bee5)
![image](https://github.com/langgenius/dify/assets/19617283/08eb4d46-7c06-4c7e-aeca-ef4837982b96)

另外2个问题：
1.每个应用中azure模型需要手动修改
2.使用原有的url对应用预览提示404，重新生成新的url后才能使用

### ✔️ Expected Behavior

实现无缝升级

**Comment by crazywoola** [comment]
Actually we can't provide such an approach, that's why it's start with 0.3.x not 1.0.x.

**Comment by sapipoZZZ** [comment]
> Actually we can't provide such an approach, that's why it's start with 0.3.x not 1.0.x.

Oh, what a pity~
