### ISSUE TITLE
在构建应用的列表页，点击某个应用的设置，再点击语言，会自动跳到该应用的详情页

### ISSUE THREAD

**Issue by rokpm** [langgenius/dify#1521]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1.在构建应用的列表页，点击某个应用的设置
2.再点击语言

### ✔️ Expected Behavior

修改语言成功，停留在设置页面

### ❌ Actual Behavior

自动跳到该应用的详情页

**Comment by crazywoola** [comment]
Which browser do you use? Chrome or Firefox?
