### ISSUE TITLE
无法填入openai的APIkey

### ISSUE THREAD

**Issue by MagicalAci** [langgenius/dify#1526]
### Dify version

0.3.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

输入API-key后，说配额不行

<img width="1378" alt="image" src="https://github.com/langgenius/dify/assets/77612408/d036fd18-cc1c-4b2e-9136-e750a2a8034a">
是原有配额用完了，需要使用openai 的api-key
<img width="786" alt="image" src="https://github.com/langgenius/dify/assets/77612408/3063abea-8376-4af7-b9c1-882e87c4b063">

### ✔️ Expected Behavior

预期能够输入API-key后，可以进行使用

### ❌ Actual Behavior

不能使用

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this problem still persists.
