### ISSUE TITLE
上传文件发生错误

### ISSUE THREAD

**Issue by lilinrestart** [langgenius/dify#1529]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

上传文件成功，清洗成功，但是在嵌入的时候发生错误（the ducuments has been processed.please refresh the page or go to ducument details）。当我把应用的语言设置成英文，有些上传失败的pdf就能够上传成功，但不是全部，并且还出现了一次前端报错（the ducuments has been processed.please refresh the page or go to ducument details），但是嵌入成功的例子。

### ✔️ Expected Behavior

期望嵌入成功

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/140720825/90cf2232-823d-4d0d-8188-0a18c7d58769)

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/1370 Please check this as well @JohnJyong

**Comment by lilinrestart** [comment]
> ### Dify version
> 0.3.30
> 
> ### Cloud or Self Hosted
> Self Hosted
> 
> ### Steps to reproduce
> 上传文件成功，清洗成功，但是在嵌入的时候发生错误（the ducuments has been processed.please refresh the page or go to ducument details）。当我把应用的语言设置成英文，有些上传失败的pdf就能够上传成功，但不是全部，并且还出现了一次前端报错（the ducuments has been processed.please refresh the page or go to ducument details），但是嵌入成功的例子。
> 
> ### ✔️ Expected Behavior
> 期望嵌入成功
> 
> ### ❌ Actual Behavior
> ![image](https://user-images.githubusercontent.com/140720825/283015403-90cf2232-823d-4d0d-8188-0a18c7d58769.png)

有些一开始上传失败的pdf在过一段时间后可以上传成功，搞不明白是什么问题

**Comment by crazywoola** [comment]
I have talked to the @JohnJyong about this issue. This happens because if you choose `economic` to process your documents, this could be very fast, while there is a preview area to preview the segments and this causes the  (the documents has been processed.please refresh the page or go to ducument details）

**Comment by lilinrestart** [comment]
> 我已经和@JohnJyong关于这个问题。发生这种情况是因为如果您选择`economic`处理文档，速度可能会非常快，而有一个预览区域可以预览片段，这会导致（文档已处理完毕，请刷新页面或转到文档详细信息）

那我试试使用另一个选项

**Comment by lilinrestart** [comment]
> 我已经和@JohnJyong这个问题。发生这种情况是如果您`economic`处理文档，速度可能会非常快，而有一个预览区域可以预览片段，这会导致（文档已处理完毕，请刷新有关页面或转到文档因为详细信息）

实际上我使用的就是高质量的处理，仍然是会上传报错
![img_v3_0258_0e677e0e-bd97-4ce9-beab-5aab3a9e2c7g](https://github.com/langgenius/dify/assets/140720825/2519149b-93b7-403f-b48e-0eaac0058009)
![img_v3_0258_1157c8f0-802d-4d0b-8dae-ed246985229g](https://github.com/langgenius/dify/assets/140720825/3d1b0b6b-11ab-440b-bc1d-c70829b2109e)

**Comment by crazywoola** [comment]
Anyway sometimes the `high quality` could be fast either. We are working on this. 
And try to use English to communicate please.

**Comment by lilinrestart** [comment]
> Anyway sometimes the `high quality` could be fast either. We are working on this. And try to use English to communicate please.
ok
