### ISSUE TITLE
社区版提示：当前分组上游负载已饱和

### ISSUE THREAD

**Issue by yuwojiusi** [langgenius/dify#1534]
### Dify version

0.3.30

### Cloud or Self Hosted

Cloud, Self Hosted, Other (please specify in "Steps to Reproduce")

### Steps to reproduce

![截屏2023-11-15 17 24 31](https://github.com/langgenius/dify/assets/4416813/8a1be093-8e4c-4dca-8872-4417abfeeeb5)

### ✔️ Expected Behavior

社区版配置openai的自定义 API 域名后也验证通过，但是在应用中切换到gpt-4的所有模型都提示“当前分组上游负载已饱和”。同一个key我拿到其他项目去配置可以正常使用

### ❌ Actual Behavior

社区版配置openai的自定义 API 域名后也验证通过，但是在应用中切换到gpt-4的所有模型都提示“当前分组上游负载已饱和”。同一个key我拿到其他项目去配置可以正常使用

**Comment by crazywoola** [comment]
Well you should ask the provider instead.

**Comment by yuwojiusi** [comment]
In other projects, my custom API domain and key are used without any issues or errors.
