### ISSUE TITLE
webapp-text-generator启动后，运行测试 报错。接口400  如图：

### ISSUE THREAD

**Issue by codingpaidaxing** [langgenius/dify#154]
![image](https://github.com/langgenius/dify/assets/122680363/fbb8e938-51f3-46d3-be14-87fb2540f6d0)

curl 'http://localhost:3000/api/completion-messages' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: session_id=20ce5964-e714-4cc7-b134-3194e4a79c90; Idea-2a7ee7f2=9f7752a9-24fc-4518-baac-a78a42123fc9; Webstorm-cf75a079=34492fae-0d14-4bd5-a825-d37fbb97945a; __gads=ID=8ab4189d737cd53d-22344386cad90076:T=1676431609:RT=1676431609:S=ALNI_MYm6Wi7VlrulhVMLOip9KhIVEHBlQ; __gpi=UID=00000bc3de44bcf1:T=1676431609:RT=1676465796:S=ALNI_MYV1jizS-d5DQqLftcrK-F6fE5F0w; locale=zh-Hans; session=24e54318-138e-4157-b532-c74ffab5e8fa.Dis3guaH_2Wi6k6OR_n3RNk2QTM; remember_token=f1e7f0d2-addf-413e-b1dd-7e8a2c5e3053|6c05025d42e05cc03aff2ddf17a5190367f173bcbf5b11f908de73ea8e2a5b2d3cd126677a6f9eed500c8c506505c9f24179b827b6783a1a38d7149df3d8fd7c; _ga=GA1.1.141319692.1684629236; _ga_DM9497FN4V=GS1.1.1684769643.4.1.1684769717.51.0.0; _ga_2MFWXK7WYT=GS1.1.1684769302.5.1.1684770402.0.0.0' \
  -H 'Origin: http://localhost:3000' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"inputs":{},"query":"hi","response_mode":"streaming"}' \
  --compressed

是不是没有Authorization。但是这个应该怎么设置呢？

**Comment by iamjoel** [comment]
你可以在 service/base.ts 里的  bufferObj = JSON.parse(message) 后面加一个log，bufferObj.message 里有报错信息。

**Comment by iamjoel** [comment]
你可以在 service/base.ts 里的  bufferObj = JSON.parse(message) 后面加一个log，bufferObj.message 里有报错信息。

**Comment by codingpaidaxing** [comment]
加了log，没什么意义。和接口一样，后台也没有明显的暴露出来
<img width="1102" alt="image" src="https://github.com/langgenius/dify/assets/122680363/d8e42613-79ce-4704-ac02-ebfe29f859e3">

**Comment by iamjoel** [comment]
可能是 apikey 填错了。你检查下， apikey 是在页面： `访问 API` 那拿的吗？

**Comment by JohnJyong** [comment]
有可能是持久化目录被清了，这个私钥文件是用来解密 OpenAI API-Key 的，目前数据需要全部清掉重新部署，重新初始化才行

**Comment by iamjoel** [comment]
还有一个可能是，你创建的是聊天类应用，这边是 文本生成类应用，这两种应用的接口不一样。

**Comment by codingpaidaxing** [comment]
感谢大佬们在百忙之中的回复，已解决。十分感谢
