### ISSUE TITLE
Frontend: Button "Upload from Computer" not clickable in chat with vision enabled (Firefox 119.0.1)

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#1540]
### Dify version

0.3.30

### Cloud or Self Hosted

Cloud, Self Hosted

### Steps to reproduce

- Use Firefox in version 119.0.1 (I was not able to reproduce it in chrome) and visit [dify](https://cloud.dify.ai/)
- Create a GPT (Chat Mode)
- Configure GPT-4-Vision-Preview and Publish
- Start a Chat 
- Click the Image-Icon to upload an image
- Click on "Upload from Computer"

### ✔️ Expected Behavior

- When I click in the middle of the button "Upload from Computer" it should open the open file dialog

### ❌ Actual Behavior

- When I click in the middle of the button "Upload from Computer" it does not open the open file dialog
- It opens the open file dialog, when I click in the bottom left corner

![grafik](https://github.com/langgenius/dify/assets/11357019/00fd1f50-2b8b-4de1-8d06-8a30c77b99d0)

**Comment by perzeuss** [comment]
It looks like the input styling is not explicitly set. Adding the `w-full` class resolves the issue.

**Comment by crazywoola** [comment]
Thanks, I will fix this bug later.
