### ISSUE TITLE
OPENAI_API_BASE .env 设置后不起作用

### ISSUE THREAD

**Issue by xsxs89757** [langgenius/dify#1543]
### Dify version

0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

.env 设置 OPENAI_API_BASE

### ✔️ Expected Behavior

使用代理请求

### ❌ Actual Behavior

还是请求了 https://api.openai.com/v1

**Comment by crazywoola** [comment]
Please use English to report issues. See our https://github.com/langgenius/dify/blob/main/.github/CODE_OF_CONDUCT.md
