### ISSUE TITLE
源码部署，创建一个管理员之后，无法再次创建新的管理员

### ISSUE THREAD

**Issue by lilinrestart** [langgenius/dify#1545]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

源码部署，创建一个管理员之后，无法再次创建新的管理员；地址加/install会重定向到登陆页面，无法创建新的租户

### ✔️ Expected Behavior

成功创建租户

### ❌ Actual Behavior

管理员设置页面重定向到登录页面，没用报错信息。

**Comment by crazywoola** [comment]
Please use English to report your issues. And this is a 'by design'. You can only have one account for self hosted version. Or you need to obtain an business license if you want to deploy multi-tenant version. Please contact business@dify.ai to obtain that license.

**Comment by lilinrestart** [comment]
> 请使用英语报告您的问题。这是“设计使然”。自托管版本您只能拥有一个帐户。或者，如果您想部署多租户版本，则需要获得商业许可证。请联系[business@dify.ai](mailto:business@dify.ai)获取该许可证。

好的 谢谢
