### ISSUE TITLE
APIError:HTTP code 403 from API 

### ISSUE THREAD

**Issue by xsxs89757** [langgenius/dify#1546]
### Dify version

0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

There is an error in requesting the official Hong Kong server of openai. I used OPENAI_BASE_URL. The address https://openai-dify.qfx.com/v1 still reports an error

### ✔️ Expected Behavior

Use a proxy

### ❌ Actual Behavior

No proxy used

**Comment by crazywoola** [comment]
https://community.openai.com/t/i-am-a-user-from-hong-kong-why-am-i-being-denied-access-to-chat-gpt/101207
HK is banned either.

**Comment by xsxs89757** [comment]
https://openai-dify.qfx.com/v1 The proxy address is a server in Tokyo

**Comment by xsxs89757** [comment]
The server has been migrated, no need to act
