### ISSUE TITLE
'Add Message' button missing on prompt eng page

### ISSUE THREAD

**Issue by Ps7ch3** [langgenius/dify#1547]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

Upgrade docker image from 0.3.29 to 0.3.30

### ✔️ Expected Behavior

Dify 0.3.29 -> Expert Mode and [the screenshot of the dify doc](https://docs.dify.ai/advanced/prompt-engineering#6.1-access-to-the-prompt-log). 

![image](https://github.com/langgenius/dify/assets/40332842/07b6375c-ae9d-402a-9ec0-bfc682d763f9)

### ❌ Actual Behavior

There's no 'Add Message' button after upgrading dify from 0.3.29 to 0.3.30

And I don't know if it's designed that way or if it's a bug.

 
![image](https://github.com/langgenius/dify/assets/40332842/276fa0a2-7f74-4fc2-9907-f53cff9e9a1e)

**Comment by takatost** [comment]
Maybe you chose a TEXT GENERATION Model instead of a CHAT Model.

**Comment by crazywoola** [comment]
Hello If you choose 
<img width="342" alt="image" src="https://github.com/langgenius/dify/assets/100913391/b5271dbe-fcd7-4f71-a7b0-5fac2d0b4175">
the input area will look like this. If you switch to 
<img width="321" alt="image" src="https://github.com/langgenius/dify/assets/100913391/7aa56ec5-95bc-4538-850f-0e5d9d7f42e6">
the input area should have the add message button.

**Comment by Ps7ch3** [comment]
But it seems that the chosen model (Azure GPT-4 8K) displayed with CHAT tag. 

![image](https://github.com/langgenius/dify/assets/40332842/8e094240-39f5-4494-adc6-d7fe61247f3a)

![image](https://github.com/langgenius/dify/assets/40332842/af801465-73b3-45d0-98fa-bf8414bce303)

**Comment by zxhlyh** [comment]
@Ps7ch3 Can you tell me how to reproduce this problem？

**Comment by Ps7ch3** [comment]
> @Ps7ch3 Can you tell me how to reproduce this problem？

Just started from scratch building v0.3.30 dify based on docker-compose and added the Azure GPT-4 model.

I think there's no special configuration to reproduce this issue.

If you need more details, feel free to ping me.

**Comment by zxhlyh** [comment]
@Ps7ch3 Thank you. Can you try it on our cloud version? And we will look into this issue.

**Comment by zxhlyh** [comment]
Thank you.  We will look into this issue.
