### ISSUE TITLE
Can not load models from OpenLLM

### ISSUE THREAD

**Issue by hahchenchen** [langgenius/dify#1550]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

按照教程上的，使用openllm启动模型：
openllm start opt --model_id facebook/opt-125m -p 3333

然后在dify上添加。报错
![image](https://github.com/langgenius/dify/assets/22194004/f04e72b0-a76a-46d7-8c2b-6e177f988892)

### ✔️ Expected Behavior

成功添加

### ❌ Actual Behavior

{"code": "invalid_param", "message": "'responses'", "status": 400}

**Comment by hahchenchen** [comment]
@crazywoola hi，can you help that？

**Comment by crazywoola** [comment]
Can you post the full parameters you filled in the form?

**Comment by hahchenchen** [comment]
![image](https://github.com/langgenius/dify/assets/22194004/e2c2aad8-34cf-40f6-9a76-8ca2961aa0d7)

**Comment by crazywoola** [comment]
<img width="676" alt="image" src="https://github.com/langgenius/dify/assets/100913391/fad33329-4017-466d-a444-8ef3475e5afd">
I see, we will fix this later.

**Comment by takatost** [comment]
It could be due to the incompatibility between the latest version of OpenLLM and the previous API. I tested the version we integrated at that time, 0.3.6, and it was working fine. However, the new version is throwing an error. Let's see how we can fix it.
