### ISSUE TITLE
Chatglm3-6B的api连接报错

### ISSUE THREAD

**Issue by Chencc01** [langgenius/dify#1553]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

使用dify添加模型的chatglm3的api接口，报错404，
![image](https://github.com/langgenius/dify/assets/151104876/8c2107cf-94d8-424e-ac2a-bd6acb86d000)
![image](https://github.com/langgenius/dify/assets/151104876/ac6807ab-73c0-49d2-a6ac-335de09446da)

**Comment by crazywoola** [comment]
Please see our language policy https://github.com/langgenius/dify/issues/1542
