### ISSUE TITLE
How to check the administrator account？

### ISSUE THREAD

**Issue by yzw7489757** [langgenius/dify#1555]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

Two months ago, I installed dify and tested it, then forgot my account and password. I ran docker rm in an attempt to reset the data, but I couldn't get to the '/install' screen to set up admin account
 
``` text
{"code": "unauthorized", "message": "Invalid email or password"}
```

I tried to reset my password

``` base
docker exec -it docker-api-1 flask reset-password
```

![image](https://github.com/langgenius/dify/assets/28922129/b1cd39e2-0fb8-4a2e-8e17-cc5ec490e197)

### ✔️ Expected Behavior

Ability to reset admin accounts

### ❌ Actual Behavior

Unable to login

**Comment by takatost** [comment]
You can use the PostgreSQL client to connect to localhost on port 5432 and access the "accounts" table to view your account.

**Comment by yzw7489757** [comment]
> You can use the PostgreSQL client to connect to localhost on port 5432 and access the "accounts" table to view your account.

![image](https://github.com/langgenius/dify/assets/28922129/4377e142-70f3-4372-a9b6-8c7cbad40683)
 
 ok, thx
