### ISSUE TITLE
QA分段选择的中文, 输出的数据还是英文

### ISSUE THREAD

**Issue by angular-moon** [langgenius/dify#1559]
### Dify version

0.3.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

知识库选择使用QA
上传一个 docx 文件 (文件中无英文内容)

### ✔️ Expected Behavior

输出中文内容

### ❌ Actual Behavior

输出英文内容

**Comment by crazywoola** [comment]
Close as duplicated https://github.com/langgenius/dify/issues/1423
