### ISSUE TITLE
request error, status_code: 400, content: Error in workflow

### ISSUE THREAD

**Issue by santiagoblanco22** [langgenius/dify#1561]
### Dify version

3.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Yesterday works perfectly in dify cloud but today I can see this error:
request error, status_code: 400, content: Error in workflow

### ✔️ Expected Behavior

chat with normality.

### ❌ Actual Behavior

can't chat. Awesome work guys!

**Comment by crazywoola** [comment]
Can you paste the command you are using? Please remove the key as well.
