### ISSUE TITLE
Local is not same to Cloud

### ISSUE THREAD

**Issue by arrowing** [langgenius/dify#1565]
### Provide a description of requested docs changes

Why do the functionalities differ between the locally deployed version and the one accessed in the cloud, both of which are version v0.3.30?

Is there a lack of certain features in the open-source code? I couldn't find relevant explanations in the documentation?

Who can help me?

Thanks in advance.

**Comment by crazywoola** [comment]
The differences between self hosted version and cloud version are simple
- the way you log into the account
- the model providers (some of them might need self deployed llm)
- the pricing section (upcoming feature) (This feature allows you increase the limit of file size and file quantities and other limitations by subscribe our plans). These environment variables are configurable in self hosted version by editing `.env` or `docker-compose.yml`
- Self hosted version might need our business license as well. 
Besides those things listed above, there are no actual differences in functionalities.

**Comment by loks666** [comment]
The fact that docker compose is deploying apps that are missing a lot of features, including Agent and workflow, can you explain if this is a difference between the open source and commercial versions, or is it because your compose builds a lower image than the current cloud platform version?
