### ISSUE TITLE
Enhancing Cohere Integration for Multiple Models in Dify

### ISSUE THREAD

**Issue by GoziKong** [langgenius/dify#1566]
### Description of the new feature / enhancement

I propose expanding the Cohere integration in Dify to include support for multiple models beyond just ReRank. Currently, when adding my API key in the Cohere section and navigating to system model settings, I only see Cohere under the ReRank model. I suggest adding functionality to use Cohere API models for reasoning, embedding, and ReRank within Dify.

### Scenario when this would be used?

This feature would be beneficial for users who want to leverage Cohere's various models, such as text generation, embedding, classification, chat, and summary, directly within Dify. For instance, it could be used when users want to enhance their reasoning capabilities, utilize advanced embedding features, or incorporate Cohere's API models for ReRanking content.

### Supporting information

To illustrate, on the Cohere website's docx & playground area, all model options are available, and users can view the code in Python or Curl. By implementing this feature, Dify users could enjoy a seamless experience, similar to Cohere's platform, unlocking the full potential of Cohere API models for various applications. This enhancement aligns with the broader goal of making Dify a versatile and powerful tool for its users.

**Comment by takatost** [comment]
Due to time constraints, we have only integrated  the cohere rerank model for now. We will support other models as soon as possible. 😊

**Comment by takatost** [comment]
The support for Cohere LLM and Text Embedding has been merged into the main branch, a new version will be released in the next couple of days.😉
