### ISSUE TITLE
Rerank model is always empty with no options to select from

### ISSUE THREAD

**Issue by Korayem** [langgenius/dify#1568]
### Dify version

0.3.30

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Click on `Profile` on top right corner
2. Click on `Settings`
3. Click on `Model Provider` in the right sidebar of popup window
4. Click on `System Model Settings`
5. Try to select a model under `Rerank Model`

### ✔️ Expected Behavior

A list of models options to select from should appear and I am allowed to select one

### ❌ Actual Behavior

No options show up
![image](https://github.com/langgenius/dify/assets/198332/767a21eb-897a-4250-951d-8db40a805837)

**Comment by zxhlyh** [comment]
Have you added cohere's api-key?

**Comment by Korayem** [comment]
No I am using openai api key

**Comment by rickythink** [comment]
You should set the cohere first, then you can select the rerank model

**Comment by Korayem** [comment]
Ok thanks. I dont have a cohere account, but will def check them out.

I assumed that Rerank input is generic that it isn't specific with cohere.
Maybe the UI can add a hint that this is only works with if you use Cohere
and add a link that explains what Cohere renak is
https://txt.cohere.com/rerank/

I will close this ticket for now
