### ISSUE TITLE
跪求支持ChatGLM-6B模型，支持本地私有化部署

### ISSUE THREAD

**Issue by yananliuyanjiang** [langgenius/dify#157]

**Comment by xusenlinzy** [comment]
可以通过实现openai接口的响应体，修改OPENAI_API_BASE，无缝接入dify，参考[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)

**Comment by willchen0729** [comment]
上面老哥的方案不错，另外最好可以配置，这样可以多模型一个平台上运行
