### ISSUE TITLE
App crash when chatting with Multi-path retrieval and Citations and Attributions enabled

### ISSUE THREAD

**Issue by rickythink** [langgenius/dify#1576]
### Dify version

latest cloud. commit hash d0456d0f

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. enable Multi-path retrieval
2. enable Citations and Attributions
3. start chat

https://github.com/langgenius/dify/assets/5317425/1533c987-5c56-478c-9b4d-fad560806676

### ✔️ Expected Behavior

function well as expected

### ❌ Actual Behavior

boom.. app crashed

**Comment by iamjoel** [comment]
Fixed by https://github.com/langgenius/dify/pull/1577
