### ISSUE TITLE
  when  create Xinference    click the button "save" web page report error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by hanksuper** [langgenius/dify#1580]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

<img width="624" alt="image" src="https://github.com/langgenius/dify/assets/58803/6344e18b-56bd-449d-b97b-0800caba39c1">

### ✔️ Expected Behavior

I have typed right information, it should accept.

**Comment by hanksuper** [comment]
> What version of xinference are you using?

Version 0.3.30。 installed by docker compose

**Comment by hanksuper** [comment]
> ### Dify version
> 0.3.30
> 
> ### Cloud or Self Hosted
> Self Hosted
> 
> ### Steps to reproduce
> <img alt="image" width="624" src="https://user-images.githubusercontent.com/58803/284483065-6344e18b-56bd-449d-b97b-0800caba39c1.png">
> ### ✔️ Expected Behavior
> I have typed right information, it should accept.
> 
> ### ❌ Actual Behavior
> _No response_

also I try through code , and get the same error， the same as problem:   https://github.com/xorbitsai/inference/issues/653 

>>> from xinference.client import Client
>>>
>>> client = Client("http://192.168.3.10:9997")
>>> model = client.get_model("2f8f51b0-8835-11ee-9143-b3125f2608d8")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/dist-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/dist-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 609, in get_model
    f"Failed to get the model description, detail: {response.json()['detail']}"
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by takatost** [comment]
> > What version of xinference are you using?
> 
> Version 0.3.30。 installed by docker compose

What I mean is the version of `xinference`. Have you updated `xinference` to the latest version?

**Comment by hanksuper** [comment]
> > > What version of xinference are you using?
> > 
> > 
> > Version 0.3.30。 installed by docker compose
> 
> What I mean is the version of `xinference`. Have you updated `xinference` to the latest version?

sorry!    previous version： xinference-0.6.3
 updated to the latest version :  use git  clone   master branch code.
The error is still exist.

**Comment by takatost** [comment]
I just tried it and couldn't reproduce this issue. I'm also using xinference version 0.6.3. Could you please run this command to check the specific version of xinference:

```
xinference-local -v
```

**Comment by hanksuper** [comment]
> <img alt="image" width="1562" src="https://user-images.githubusercontent.com/5485478/284519903-7bc4933d-7f41-45fb-a723-3ec6bce18323.png">
> I just tried it and couldn't reproduce this issue. I'm also using xinference version 0.6.3. Could you please run this command to check the specific version of xinference:
> 
> ```
> xinference -v
> ```

root@hanksuper-System:/# xinference -v
2023-11-21 11:49:57,244 - modelscope - INFO - PyTorch version 2.1.0 Found.
2023-11-21 11:49:57,245 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-11-21 11:49:57,276 - modelscope - INFO - Updating the files for the changes of local files, first time updating will take longer time! Please wait till updating done!
2023-11-21 11:49:57,284 - modelscope - INFO - AST-Scanning the path "/usr/local/lib/python3.10/dist-packages/modelscope" with the following sub folders ['models', 'metrics', 'pipelines', 'preprocessors', 'trainers', 'msdatasets', 'exporters']
2023-11-21 11:50:07,055 - modelscope - INFO - Scanning done! A number of 945 components indexed or updated! Time consumed 9.771240949630737s
2023-11-21 11:50:07,081 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 d0389350ebbf793241ae05eff02cc0d9 and a total number of 945 components indexed
xinference, version 0.6.3

**Comment by takatost** [comment]
How did you deploy dify? Did you use Docker Compose or deploy from source code? 
I guess it might be a source code deployment without updating the Python dependencies:

```
cd api
pip install -r requirements.txt
```

**Comment by hanksuper** [comment]
> How did you deploy dify? Did you use Docker Compose or deploy from source code? I guess it might be a source code deployment without updating the Python dependencies:
> 
> ```
> cd api
> pip install -r requirements.txt
> ```

git clone https://github.com/langgenius/dify.git
cd dify/docker
docker compose up -d


I do not use source code deployment.
Afternoon ,I also update   Dify version to  0.3.31.

**Comment by hanksuper** [comment]
>>> from xinference.client import Client
>>>
>>> client = Client("http://192.168.3.10:9997")
>>> model = client.get_model("b71260e2-886b-11ee-ba3f-07f2f6cbfea5")
>>>
>>> chat_history = []
>>> prompt = "What is the largest animal?"
>>> model.chat(
...     prompt,
...     chat_history=chat_history,
...     generate_config={"max_tokens": 1024}
... )
{'id': 'chatbb9bc29d-886c-11ee-ba3f-07f2f6cbfea5', 'object': 'chat.completion', 'created': 1700571108, 'model': 'b71260e2-886b-11ee-ba3f-07f2f6cbfea5', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': 'The largest animal on Earth is the蓝鲸 (Balaenoptera musculus), which can grow up to 100 feet long and weigh up to 74,000 pounds.'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 21, 'completion_tokens': 44, 'total_tokens': 65}}


xinference  is normal, but dify is abnormal.    Below is  a comparison image.

<img width="623" alt="image" src="https://github.com/langgenius/dify/assets/58803/9ebb2f51-f636-4853-ab8c-b3945c123f49">

**Comment by takatost** [comment]
> > > > from xinference.client import Client
> > > > client = Client("http://192.168.3.10:9997")
> > > > model = client.get_model("b71260e2-886b-11ee-ba3f-07f2f6cbfea5")
> > > > chat_history = []
> > > > prompt = "What is the largest animal?"
> > > > model.chat(
> > > > ...     prompt,
> > > > ...     chat_history=chat_history,
> > > > ...     generate_config={"max_tokens": 1024}
> > > > ... )
> > > > {'id': 'chatbb9bc29d-886c-11ee-ba3f-07f2f6cbfea5', 'object': 'chat.completion', 'created': 1700571108, 'model': 'b71260e2-886b-11ee-ba3f-07f2f6cbfea5', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': 'The largest animal on Earth is the蓝鲸 (Balaenoptera musculus), which can grow up to 100 feet long and weigh up to 74,000 pounds.'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 21, 'completion_tokens': 44, 'total_tokens': 65}}
> 
> xinference is normal, but dify is abnormal. Below is a comparison image.
> 
> <img alt="image" width="623" src="https://user-images.githubusercontent.com/58803/284584814-9ebb2f51-f636-4853-ab8c-b3945c123f49.png">

How about removing the slash at the end of the URL?

**Comment by hanksuper** [comment]
> > > > > from xinference.client import Client
> > > > > client = Client("http://192.168.3.10:9997")
> > > > > model = client.get_model("b71260e2-886b-11ee-ba3f-07f2f6cbfea5")
> > > > > chat_history = []
> > > > > prompt = "What is the largest animal?"
> > > > > model.chat(
> > > > > ...     prompt,
> > > > > ...     chat_history=chat_history,
> > > > > ...     generate_config={"max_tokens": 1024}
> > > > > ... )
> > > > > {'id': 'chatbb9bc29d-886c-11ee-ba3f-07f2f6cbfea5', 'object': 'chat.completion', 'created': 1700571108, 'model': 'b71260e2-886b-11ee-ba3f-07f2f6cbfea5', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': 'The largest animal on Earth is the蓝鲸 (Balaenoptera musculus), which can grow up to 100 feet long and weigh up to 74,000 pounds.'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 21, 'completion_tokens': 44, 'total_tokens': 65}}
> > 
> > 
> > xinference is normal, but dify is abnormal. Below is a comparison image.
> > <img alt="image" width="623" src="https://user-images.githubusercontent.com/58803/284584814-9ebb2f51-f636-4853-ab8c-b3945c123f49.png">
> 
> How about removing the slash at the end of the URL?

docker version updated to  [v0.3.31-fix3](https://github.com/langgenius/dify/releases/tag/0.3.31-fix3) is ok，so I could close this bug report.

**Comment by jay-jjwu** [comment]
i did test in new version, the URL is only allowed with IP, intead of domain name. Is that normal?
