### ISSUE TITLE
Multi-path retrieval doesn't work for docker build and source code build 

### ISSUE THREAD

**Issue by rickythink** [langgenius/dify#1594]
### Dify version

0.3.31, 0.3.31-fix1, 0.3.31-fix2 the docker build and lastest source code build

### Cloud or Self Hosted

Self Hosted and source code build

### Steps to reproduce

1. use [gitpod](https://gitpod.io) to create a new workspace for dify (ensure a fresh new environment)
2. cd docker & docker compose up -d as said in the README.md
3. add gpt key & cohere key
4. import a pdf and set the mode with `Multi-path retrieval` + `rerank multilingual-v2.0`
5. start with `Retrieval Testing`

[online reproduce gitpod link](https://80-langgenius-dify-gvif7m49efn.ws-us106.gitpod.io/datasets/0c7721b7-b0fb-4a58-9b6d-eee8991d889a/hitTesting)

--- 

1. use the lastest code turns out to get the same error

### ✔️ Expected Behavior

work well as the `cloud.dify.ai` does

### ❌ Actual Behavior

failed with error notify `doc_hash`

<img width="232" alt="image" src="https://github.com/langgenius/dify/assets/5317425/f1993fb2-6747-4e2c-936d-8af21656f0c6">

--- 

I debug the from my local machine and locate the error is directly caused by https://github.com/langgenius/dify/blob/caa330c91f27dce000b6b66af1867aec6335100c/api/core/model_providers/models/reranking/cohere_reranking.py#L42

However, I did not figure out why the doc_hash key is missing.
<img width="1543" alt="image" src="https://github.com/langgenius/dify/assets/5317425/0acec0eb-133f-46c3-9f31-587e7f76f344">

**Comment by limfoo** [comment]
I have same issue.

**Comment by rickythink** [comment]
#1600
