### ISSUE TITLE
use gpt-4-vision-preview model，failed to load image in message

### ISSUE THREAD

**Issue by qiang1218** [langgenius/dify#1598]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1. file saving mode: local
2. create an application and use gpt-4v model
3. upload file and chat
4. view chat history

### ✔️ Expected Behavior

correctly load pictures in chat history

### ❌ Actual Behavior

image url load failed,  status code: 404

**Comment by yuhao1118** [comment]
Hi, the nginx config was updated recently to support file accessing. Please check your docker nginx config, make sure this block exist:
<img width="616" alt="image" src="https://github.com/langgenius/dify/assets/26663836/7d51ce87-f137-49b5-b678-63f63e36c166">

**Comment by qiang1218** [comment]
Okay, I'll try it, thank you
