### ISSUE TITLE
Get errors" Temporary failure in name resolution" when configuring API keys for some model providers

### ISSUE THREAD

**Issue by zhiyicom** [langgenius/dify#1602]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

1) Get API key and secret key from Baichuan、Wenxinyiyan、Tongyiqianwen，etc；
2) Input API key and secret key in model provider page;

### ✔️ Expected Behavior

the key could be verified

### ❌ Actual Behavior

get error:

HTTPSConnectionPool(host='api.baichuan-ai.com', port=443): Max retries exceeded with url: /v1/chat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c4821beb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

![image](https://github.com/langgenius/dify/assets/29563513/89856d32-7886-452e-b307-eb5fb89e39ef)

Troubleshoot:
1) I checked the server's network configuration, I can telnet 443 port of api.baichuan-ai.com from server correctly;
2) I've captured the packets on server when I was veirfying keys, but havn't seen any trasaction between server and model providers.

**Comment by takatost** [comment]
This looks like a DNS resolution failure in the Docker container. Can you please check if you can access it properly within the container?

**Comment by zhiyicom** [comment]
yes, after configuring dns in /etc/docker/daemon.json, it works, thank you!
