### ISSUE TITLE
LocalAI Embedding is not working

### ISSUE THREAD

**Issue by UberIzual** [langgenius/dify#1605]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

在模型供应商已经添加localai的embedding模型，但是在应用页面无法选择该模型
![image](https://github.com/langgenius/dify/assets/100743282/88ae105d-a43c-483f-9040-d935ba9542d3)

![image](https://github.com/langgenius/dify/assets/100743282/6ccdf854-daac-4664-b168-218ac7e7115e)

**Comment by zxhlyh** [comment]
Can you try upgrading to the latest version? @UberIzual
