### ISSUE TITLE
vLLM作为模型供应商

### ISSUE THREAD

**Issue by zhuang-maowei** [langgenius/dify#1610]
### Description of the new feature / enhancement

希望增加vLLM作为模型供应商

### Scenario when this would be used?

通过对接vLLM的OpenAI接口，开源模型的本地化部署更方便

**Comment by crazywoola** [comment]
Before you contribute, please read our 'Language Policy'. #1542

**Comment by morning-hao** [comment]
Me too, I am a machine with my own 4090. I have one image using VLLM and another deploying the Dify framework. Then, I used PyCharm to debug VLLM, but Dify didn't work.
