### ISSUE TITLE
Dataset does't work for release 0.3.31-fix3, the same problem goes for cloud https://cloud.dify.ai/

### ISSUE THREAD

**Issue by L929333353** [langgenius/dify#1612]
### Dify version

0.3.31-fix3

### Cloud or Self Hosted

Cloud, Self Hosted

### Steps to reproduce

When i import my document into dify version 0.3.31-fix3, and add it to my app, when i ask of this document, the answer obviously not by this document, the same problem goes for cloud https://cloud.dify.ai/

**Comment by L929333353** [comment]
Sadly, I add 2 datasets to my app, but i got only 1 when function plan() calls at MultiDatasetRouterAgent

**Comment by L929333353** [comment]
Sadly, I add 2 datasets to my app, but i got only 1 DatasetRetrieveTool at MultiDatasetRouterAgent instance

**Comment by cexer** [comment]
Same. I tested on cloud.dify.ai.

**Comment by takatost** [comment]
let me check it out.
