### ISSUE TITLE
Conversation Title for Persian Language 

### ISSUE THREAD

**Issue by drupalshift** [langgenius/dify#1614]
### Dify version

0.3.31-fix3

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

Start a conversation in the Persian language for example say :

سلام حالت چطوره ؟

Which means Hi How are you doing?

### ✔️ Expected Behavior

Generate a short Conversation Title in Persian but it does it in Arabic

### ❌ Actual Behavior

Generates in Arabic
Seems it's due to api/core/prompt/prompts.py line 3 which mentions the Arabic language 

There are 20+ languages that use the same alphabet I tried different languages like Kurdish, it always generates the title in Arabic 

https://github.com/langgenius/dify/blob/ea35f1dce19faac572e0d39c973578e7fa017d8b/api/core/prompt/prompts.py#L3C1-L3C128

**Comment by takatost** [comment]
Oh, maybe these few-shots are not enough for the model. What model did you use for testing? Can GPT-4 generate output properly?

**Comment by ParseDark** [comment]
From my side. I think @takatost  is right. You also need to provide your model provider type. 

Another reason may be these example cases are not enough for your use case. One solution is to add more examples but it will cost all of the user token.

<img width="1060" alt="image" src="https://github.com/langgenius/dify/assets/26950370/5dd79fe6-f781-4b71-8604-fc292318267f">

**Comment by drupalshift** [comment]
> GPT-4

Yes, GPT4 does a better job but still is like a trial and error some times same introduction message generates a Persian title some time it does it in Arabic 

It would be nice if you could add flexibility for generating a title, add it in the app setting with a default value, and let users change it if it doesn't work well, cause other models like gpt3 almost always generate in Arabic

**Comment by crazywoola** [comment]
<img width="543" alt="image" src="https://github.com/langgenius/dify/assets/100913391/8c03e8b1-65e7-49a5-9314-5b1172bd994d">
Do you mean this one? We do support rename conversation in chat applications. I will close this one,  if you have more questions regarding this you can open another issue and refer this one.
