### ISSUE TITLE
Dataset still not work,  this bug has reported in issue #1612

### ISSUE THREAD

**Issue by L929333353** [langgenius/dify#1622]
### Dify version

0.3.32

### Cloud or Self Hosted

Cloud, Self Hosted

### Steps to reproduce

Dataset still not work for 0.3.32, this bug has reported in issue #1612.
I be notified it fixed in this version, and tried it in cloud, sadly, the problem still there.
I fix this in my local edition, 2 reason related:
1. The function to_dataset_retriever_tool() in OrchestratorRuleParser mix using retrieval_model cause only first dataset set to agent.
2. The #context# does not matched in PromptTransform, Even if it could be matched, PromptTemplateParser can't be used to parse context, I find JinjaPromptTemplate works in early version, witch being deleted recently, I don't know why, but this is the real reason cause this problem.

**Comment by takatost** [comment]
Sorry, I just tried both the normal and expert modes of the N-to-1 pattern in two different application type, and they both matched correctly. Can you please tell me how to reproduce this issue, or how you fixed it?
