### ISSUE TITLE
I set basePath prefix '/dify', but 404 occurs when I try to create dataset

### ISSUE THREAD

**Issue by L929333353** [langgenius/dify#1625]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

I set basePath prefix '/dify', but 404 occurs when I try to create dataset.
It seems basePath prefix '/dify' is not work.

**Comment by crazywoola** [comment]
What is a basePath?
How did you set it?

**Comment by L929333353** [comment]
> What is a basePath? How did you set it?

Config named nextConfig in web/next.config.js, where can set a global variable basePath to set a prefix path in URL, such as '/dify'

**Comment by L929333353** [comment]
> What is a basePath? How did you set it?

Config named nextConfig in web/next.config.js, where can set a global variable basePath to set a prefix path in URL, such as '/dify'.
There exists hard coding like <a href='/datasets/create' >, I think this is the reason.

**Comment by L929333353** [comment]
Config named nextConfig in web/next.config.js, where can set a global variable basePath to set a prefix path in URL, such as '/dify'.
There exists hard coding like 
```
<a href='/datasets/create'>
```
 I think this is the reason.

**Comment by crazywoola** [comment]
> Config named nextConfig in web/next.config.js, where can set a global variable basePath to set a prefix path in URL, such as '/dify'. There exists hard coding like
> 
> ```
> <a href='/datasets/create'>
> ```
> 
> I think this is the reason.

Well it might be more complex than expected, not only this hard code. The oauth redirect path also redirect to '/' and in api request, it will redirect to '/' if the request is invalid.
