### ISSUE TITLE
member role change feature request.

### ISSUE THREAD

**Issue by thingsflow-accadmin** [langgenius/dify#1628]
### Description of the new feature / enhancement

I need to change owner of a workspace which is not possible at the moment. 
Do you have a plan to add that feature? 

### Scenario when this would be used?

when a member of a dev team leaves the team.

**Comment by crazywoola** [comment]
If you are using SELF_HOSTED version. There is a way to do this:

```
# Source code
flask reset-email
# Docker compose
docker exec -it docker-api-1 flask reset-email
```

:)
