### ISSUE TITLE
模型返回空字符串。日志里也看不到信息

### ISSUE THREAD

**Issue by TigrisRiva** [langgenius/dify#1630]
### Dify version

0.3.32

### Cloud or Self Hosted

Cloud

### Steps to reproduce

无法准确复现，但是经常出现
据观察是在聊天上下文多了以后产生
环境：
1. 使用的是Dify官网
2. 使用的是AZURE OPENAI 接口
3. 对话ID: cd21cd707e09

### ✔️ Expected Behavior

不管是正确还是错误日志都应该返回

### ❌ Actual Behavior

模型返回空字符串。日志里也看不到信息
看不出是哪里出了问题

**Comment by crazywoola** [comment]
Please read our CODE OF CONDUCT before you contribute https://github.com/langgenius/dify/issues/1542
