### ISSUE TITLE
if multiple dataset were added to Context, the error occurred when use the ERNIE-Bot-4 Model 

### ISSUE THREAD

**Issue by Emirateyang** [langgenius/dify#1635]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

if multiple dataset were added to Context, you can't chat when use the ERNIE-Bot-4 Model, and it will throw the follow error:

Wenxin: Wenxin API 336003 error: field system too long

After read the document of Wenxin [(https://cloud.baidu.com/doc/WENXINWORKSHOP/s/clntwmv7t)](url)
the field system is not necessary as parameter, and it's for Model persona, mainly used for persona setting.

But when you delete these dataset from Context, the chat will work normally.

So, it seems that something wrong when give the value to the field system.

Btw, even if you add multiple dataset to Context, everything goes fine when use other Model, like GPT

### ✔️ Expected Behavior

can chat when use the ERNIE-Bot-4 Model, even multiple dataset were added to Context

**Comment by crazywoola** [comment]
@takatost Please take a look at this issue.
