### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Saul-BT** [langgenius/dify#1644]
### Description of the new feature / enhancement

Translation of the entire interface into Spanish

### Scenario when this would be used?

I think it is very useful to extend the use of this magnificent tool to more people (Spanish-speaking).

**Comment by Saul-BT** [comment]
I have created the issue because I haven't seen one about it.
It is something I can take care of (although it will take me some time) if there is no one working on it.

PS: I'm very impressed with this tool, congratulations on the great job! 😄 🎉

**Comment by crazywoola** [comment]
@Saul-BT Hello if you are interested in i18n you can follow [this guide](https://github.com/langgenius/dify/blob/f6e04389e44c64fa360e8bbef65577ea9b925fd7/web/i18n/README_EN.md#L1) to contribute.
If you encounter any questions, you are welcome to reach out to me any time. :)
