### ISSUE TITLE
hit testing failed

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1649]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

<img width="1576" alt="image" src="https://github.com/langgenius/dify/assets/1925650/706e108b-3800-49ca-928e-6c31bbe2b176">
召回测试失败。不管是向量检索，还是全文检索会发生。
代码：
hit_testing_service.py
<img width="633" alt="image" src="https://github.com/langgenius/dify/assets/1925650/97331578-3ae9-4dca-80ee-8966fa786fac">

### ✔️ Expected Behavior

正常返回命中结果

### ❌ Actual Behavior

<img width="1345" alt="image" src="https://github.com/langgenius/dify/assets/1925650/6bc29ad1-7c52-4557-ae10-255c617db539">

setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

**Comment by crazywoola** [comment]
This should be fixed in latest version. You can open another issue if this persists.
