### ISSUE TITLE
knowledge base does not work

### ISSUE THREAD

**Issue by arrowing** [langgenius/dify#1654]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1、create a dataset with same model and settings (same of both, local and cloud)
2、create a app
3、test the QA

### ✔️ Expected Behavior

![image](https://github.com/langgenius/dify/assets/9293244/d82836c3-56ec-4ef5-94ca-0a61f37a9e6c)

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/9293244/a7743802-5e75-4346-a317-0917dfee3d6a)

**Comment by crazywoola** [comment]
If you are using some variables in prompt you should switch to advanced prompt mode instead. 

- First make sure you have tested the question in retrieval testing and get the answer properly.
- You can also hover on the dialog chat bubble to see the detailed prompt you have just sent.

**Comment by arrowing** [comment]
> If you are using some variables in prompt you should switch to advanced prompt mode instead.
> 
> * First make sure you have tested the question in retrieval testing and get the answer properly.
> * You can also hover on the dialog chat bubble to see the detailed prompt you have just sent.

Exactly i had confirmed.

**Comment by arrowing** [comment]
> Can you switch to the advanced mode and try it again?

I have no enough of the advanced mode like that prompts how to set up. I will have a try.
But it works in the cloud environment, so could you give me some helps?
