### ISSUE TITLE
Unable to find information on env TENANT_DOCUMENT_COUNT

### ISSUE THREAD

**Issue by knowsnotmuch** [langgenius/dify#1655]
### Provide a description of requested docs changes

Hello - the app is easy to setup and get going. I am trying to change the value for TENANT_DOCUMENT_COUNT which somehow seems to be unchanged even when I add the env to the docker-compose.yaml 

Can you pl look into this ?

**Comment by crazywoola** [comment]
Hello I think you will need to add `TENANT_DOCUMENT_COUNT` to api and worker in the compose file.

**Comment by knowsnotmuch** [comment]
Thank you @crazywoola - I will try both. I tried one and the other but not both! Thanks again

**Comment by ashwindz** [comment]
it works! thanks!

**Comment by knowsnotmuch** [comment]
it works! thank you :)
