### ISSUE TITLE
Using the online version of Dify, uploading a PDF file, and using a custom cutting method resulted in failure during embedding.

### ISSUE THREAD

**Issue by mozeqiu123** [langgenius/dify#1659]
### Dify version

0.3.32

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I used the online version of Dify, uploaded my PDF file, and then customized the cutting method, an error occurred when embedding.
![image](https://github.com/langgenius/dify/assets/139750690/26ada004-f2cc-4a43-8275-662f4584c830)

### ✔️ Expected Behavior

Embedded successfully

### ❌ Actual Behavior

Embedding failed

**Comment by crazywoola** [comment]
Can you hover on the error and get the detailed message?

**Comment by mozeqiu123** [comment]
> Can you hover on the error and get the detailed message?

I placed the mouse on the error and there was no response
![image](https://github.com/langgenius/dify/assets/139750690/e377dade-e051-48ca-ba26-793be504d79d)

**Comment by crazywoola** [comment]
Can you attach the original file if that's ok? We need to something to test if possible.

**Comment by mozeqiu123** [comment]
> Can you attach the original file if that's ok? We need to something to test if possible.

yes,sure.
[2307.16789.pdf](https://github.com/langgenius/dify/files/13521459/2307.16789.pdf)
[Uploading bcgdeeplink.pdf…]()

**Comment by mozeqiu123** [comment]
> <img alt="image" width="1856" src="https://private-user-images.githubusercontent.com/100913391/288028807-0819581b-65dc-41bd-bde4-e135fb230e65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzQ3ODQsIm5iZiI6MTcwMTgzNDQ4NCwicGF0aCI6Ii8xMDA5MTMzOTEvMjg4MDI4ODA3LTA4MTk1ODFiLTY1ZGMtNDFiZC1iZGU0LWUxMzVmYjIzMGU2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMzQ4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzZjYTc3YWI3OWQwMjQ3ZWY1MDI0N2Y2MDYxMzFjZGY4MGJhMThiOGYxNzI1OGQyZjM3MDE4YTRkYzM0YmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OFNRUL5aycMEtvFrf0G9zAdrsnL1rCETnU_HvbZJmFA"> I have tested this file, seems ok to me, because I have run out of the tokens, can not finish the whole process, as you can see, there is an error message in the top left in this image. You can paste the error message here.
> And I change the embedding model back to openai and it's works for me <img alt="image" width="1847" src="https://private-user-images.githubusercontent.com/100913391/288029610-f8f80be9-1bfc-45d8-8a1e-5c3a1334f0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzQ3ODQsIm5iZiI6MTcwMTgzNDQ4NCwicGF0aCI6Ii8xMDA5MTMzOTEvMjg4MDI5NjEwLWY4ZjgwYmU5LTFiZmMtNDVkOC04YTFlLTVjM2ExMzM0ZjBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMzQ4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2ZlNTNjYTFkNDdiMDI5MDM0M2JkMDE3NTQzZDlhMTU1MzAxMDk3ZDY0MWJjMWU0MjRlY2U0NzI1OGIzN2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-YnCN3OVFFdWI_G418sJYdVxznfmRDFkCDUC0RArJis">

Okay, I will try again

**Comment by crazywoola** [comment]
We are using unstructure.io to process pdf data now, you could try this again in v0.3.34.
