### ISSUE TITLE
GPT-4V using bug,There is no image input but output. The image link was successfully uploaded, but an error message was reported that the URL does not exist

### ISSUE THREAD

**Issue by mozeqiu123** [langgenius/dify#1664]
### Dify version

0.3.32

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![img_v3_025n_f5f152be-226f-4dda-86d3-bcd46251b57g](https://github.com/langgenius/dify/assets/139750690/074fc33e-2603-44e1-944c-2b5876dc5cc3)
![img_v3_025n_563f82be-faa7-4702-99c4-2284912eeabg](https://github.com/langgenius/dify/assets/139750690/d091641a-359b-43eb-8c4c-c7bbd637bbb1)

### ✔️ Expected Behavior

When there is no image input, there is no output.
The output image link can correctly read the image.

### ❌ Actual Behavior

When there is no image input, there is error output.

**Comment by crazywoola** [comment]
Sorry can not reproduce this error, can you try to refresh this page and try it again?

**Comment by nguyenphan** [comment]
@crazywoola I am having the same issue, the url I submitted is a signed url from S3. Is there anything we need to look out for when using s3 signed url?
