### ISSUE TITLE
Support function definition and function callback in api

### ISSUE THREAD

**Issue by L929333353** [langgenius/dify#1670]
### Description of the new feature / enhancement

Support function definition on prompt edit,  and add function call parameters in chat message API response, so we can build wonderful agents by DIFY.

### Scenario when this would be used?

When we need build wonderful agents by DIFY.

**Comment by ifsheldon** [comment]
+1. After reading the doc, I still don't know how to define a function and then use it with dify.

**Comment by crazywoola** [comment]
I have record a video for this [BiliBili](https://www.bilibili.com/video/BV1UN4y1b7s1/)

**Comment by ifsheldon** [comment]
@crazywoola What you've done in the video is not function calling per se. I mean you did call a function, but what you've done is fetching external data into a prompt template. Please refer to https://platform.openai.com/docs/assistants/tools/function-calling and https://platform.openai.com/docs/guides/function-calling for function calling that is initiated by an assistant. We want assistants to be able to initiate function calls and return results to them.

**Comment by wlevene** [comment]
I had the same problem

**Comment by jianzhichun** [comment]
The same as me
