### ISSUE TITLE
Unable to set Together api

### ISSUE THREAD

**Issue by Adarsbhi126** [langgenius/dify#1676]
### Dify version

0.3.21

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Integrate Together API into Dify for a cost effective open-source model. Users gain seamless access to advanced functionality, enhancing workflow efficiency and resource management.

### ✔️ Expected Behavior

how to set this model service??*

### ❌ Actual Behavior

Noting is showing*

**Comment by crazywoola** [comment]
This is not a bug, please use the right template to fire an issue, also duplicated #1611
