### ISSUE TITLE
function-calling

### ISSUE THREAD

**Issue by xsxs89757** [langgenius/dify#1685]
### Description of the new feature / enhancement

Regarding of the new feature of OpenAI GTP [function-calling](https://platform.openai.com/docs/guides/gpt/function-calling)

### Scenario when this would be used?

Regarding of the new feature of OpenAI GTP [function-calling](https://platform.openai.com/docs/guides/gpt/function-calling)

**Comment by crazywoola** [comment]
See this [BiliBili](https://www.bilibili.com/video/BV1UN4y1b7s1/) for more details.
