### ISSUE TITLE
Paste function is not working on the web page

### ISSUE THREAD

**Issue by IDone1** [langgenius/dify#1687]
### Dify version

0.3.3.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Web page cannot paste text into the input box

### ✔️ Expected Behavior

It used to be pastable

### ❌ Actual Behavior

Now pasting is invalid

**Comment by crazywoola** [comment]
Can you provide more details? For example, which web browser do you use? Can you paste the error log in console?

**Comment by IDone1** [comment]
I am not a professional. After I use the web port to open the dialogue function, I have no problem using manual input in the input box, but there is no response when using the paste function.
![9c2cebe541f19a15cc86dd4c9d028a7](https://github.com/langgenius/dify/assets/128884991/73f8c6a9-0380-43c0-83d6-4c7a2972d394)

**Comment by IDone1** [comment]
in use Edg

**Comment by crazywoola** [comment]
Fixed in #1693
