### ISSUE TITLE
Sending messages can carry files

### ISSUE THREAD

**Issue by starboyate** [langgenius/dify#1688]
### Description of the new feature / enhancement

Is there a plan to support carrying files in messages, similar to OpenAI's assistant, which can upload files in messages

### Scenario when this would be used?

Users can upload files themselves and then inquire about AI assistant

**Comment by crazywoola** [comment]
The feature is still under discussion.

**Comment by abdullahbaa5** [comment]
> The feature is still under discussion.

Up = you can upload files but only use image which is a big disadvantage
