### ISSUE TITLE
Paste function can't work at webpage

### ISSUE THREAD

**Issue by TigrisRiva** [langgenius/dify#1689]
### Dify version

0.3.32

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The web client version of Dify does not allow the use of the Paste function in input fields. Using Chrome's F12 developer mode, I discovered that the PASTE event is triggered within the control (specific location: https://cloud.dify.ai/_next/static/chunks/2443530c-081569eda01ca754.js). After manually deleting it, I was able to paste.

Additionally, the Paste function is also not available in the debugging and preview within the APP.

**Comment by crazywoola** [comment]
What model provider do you choose? It should be gpt-4-vision. The rest of them do not support this feature.

**Comment by JunIce** [comment]
I found Line 200 is not ok. It will prevent the default text copy behavior. 
https://github.com/langgenius/dify/blob/b5dd948e56c496883918ff561d1011a2ee3da00b/web/app/components/base/image-uploader/hooks.ts#L199-L204

**Comment by yuhao1118** [comment]
> I found Line 200 is not ok. It will prevent the default text copy behavior. 
> 
> https://github.com/langgenius/dify/blob/b5dd948e56c496883918ff561d1011a2ee3da00b/web/app/components/base/image-uploader/hooks.ts#L199-L204

Looks like it is my commit. I will fix it soon.

**Comment by IDone1** [comment]
Hope this function can be repaired quickly.thanks~

**Comment by zxhlyh** [comment]
fixed https://github.com/langgenius/dify/pull/1693
