### ISSUE TITLE
⭐ Feature : adding of togeter API inference for a cost effective open source models ⭐

### ISSUE THREAD

**Issue by sabharaja3** [langgenius/dify#1692]
### Description of the new feature / enhancement

The proposed integration involves incorporating together API into our difyy, offering users a costeffective open source model alternative. This addition aims to enhance accessibility, enabling seamless utilization of Together.ai API within our dify ecosystem. ⭐

### Scenario when this would be used?

i think users would find this feature beneficial when seeking a more economical open source model like llama 2 and mistral, with the potential to replicate functionalities at a reduced cost. 

### Supporting information

This alternative model is particularly relevant for Dify users, as it could significantly impact workflow efficiency and resource management in a positive manner. 

![Screenshot 2023-12-04 183813](https://github.com/langgenius/dify/assets/139057295/3ab48b03-a4f8-4bde-a547-cd068b82bc21)

**Comment by crazywoola** [comment]
We do notice this new platform #1611

**Comment by Adarsh0127** [comment]
> We do notice this new platform #1611

are you guys adding?? when i think i just check its looks good model
