### ISSUE TITLE
wrong max base model token limit when using gpt-4 turbo

### ISSUE THREAD

**Issue by Ps7ch3** [langgenius/dify#1698]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Long user input message or prompt with Azure GPT-4 (1106-preview)

### ✔️ Expected Behavior

Add extra model option for Azure GPT-4 turbo

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/40332842/ad323c27-31a7-4807-9cd2-498d3bffa2f0)

**Comment by Ps7ch3** [comment]
I believe the root cause is that Azure gpt-4 turbo did not assign a new model name and only updated the model verison to "1106-preview" 

See [docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-preview-models) for details

And current gpt-4 base model max token is 8K

<img width="1854" alt="image" src="https://github.com/langgenius/dify/assets/40332842/31926f19-c9f7-487e-9569-4c06ecf28987">

**Comment by crazywoola** [comment]
This is a known issue. Because the gpt-4-preview has a 
```
Input: 128,000
Output: 4096
```
But we haven't split them into two parts in the backend code.

**Comment by crazywoola** [comment]
Yes.
