### ISSUE TITLE
非联网环境登录后无法进入dify主页面的问题

### ISSUE THREAD

**Issue by Kaimobile** [langgenius/dify#170]
Dify version: Self Host

## Steps To Reproduce

1. 在不能连接互联网的生产服务器的docker环境私有化部署dify，
2. 在登录认证通过后无法进入界面，卡在console/api/version?current_version=0.2.0请求最终500超时，系统无法使用。

## The current behavior

console/api/version?current_version=0.2.0请求500超时，查看后端日志发现是环境无法访问updates.dify.ai网址

![企业微信截图_20230523152843](https://github.com/langgenius/dify/assets/36190232/afb7a28d-85cf-4df8-a53e-437296965414)

![企业微信截图_20230523152925](https://github.com/langgenius/dify/assets/36190232/5b872f13-eb84-4020-9a78-4ebfcc6265d4)

## The expected behavior

不能连接互联网的生产环境，也能正常部署和使用Dify

**Comment by JohnJyong** [comment]
@iamjoel

**Comment by takatost** [comment]
可以拉下最新代码，并配置 api 服务的环境变量 `CHECK_UPDATE_URL=` 值为空即可
