### ISSUE TITLE
Error while deploying the webclient in my own server

### ISSUE THREAD

**Issue by TigrisRiva** [langgenius/dify#1700]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Using the code here:
https://github.com/langgenius/webapp-conversation
I've set the correct .env.local file correctly and after I run npm run dev
I got a 500 App is unavailable error on the localhost:3000.
I'm not sure where I went wrong with the configuration.
Can I see any logs?

**Comment by crazywoola** [comment]
Can you see the logs in the browser's console and set the filter to `xhr`?

**Comment by TigrisRiva** [comment]
I've checked the log in the browser's console.
When the program runs here, it reports an error:
**const isNotNewConversation = conversations.some(item => item.id === _conversationId)**
Error message:
**Error TypeError: Cannot read properties of undefined (reading 'some')
    at eval**

**Comment by TigrisRiva** [comment]
Screen shot of browser's console:
(I've added some "console.log" into the code to find out what happened)
![image](https://github.com/langgenius/dify/assets/149912251/86d0ec90-df95-4080-96b8-2b7fd5354c42)

**Comment by TigrisRiva** [comment]
I've set the .env.local correctly and I can see them in the browser's console.
However the promptConfig turns out to be null

**Comment by TigrisRiva** [comment]
I made a slight modification to the code for the conversations line, changing `const { data: conversations = [] } = conversationData as { data: ConversationItem[] }; `to `const { data: conversations = [] } = conversationData as { data?: ConversationItem[] };`. The interface came up. But there is an error when chatting:
**base.ts:229 POST http://138.128.221.243:3000/api/chat-messages 500 (Internal Server Error)**

**Comment by crazywoola** [comment]
@iamjoel Please take a look at this one.

**Comment by ParseDark** [comment]
Hi. @TigrisRiva  and @crazywoola . I think I found the root cause. on the template part. Here will block the Index page render. 

Solution 1: The template part needs to enhance this code. If not have upload image it should be made sure the code does not break down.

<img width="1891" alt="image" src="https://github.com/langgenius/dify/assets/26950370/6fc1f8ce-d63c-47f7-bc6b-000052fa95cd">

Solution 2: The backend should be make sure the API file_upload fields is "{}" 

<img width="1417" alt="image" src="https://github.com/langgenius/dify/assets/26950370/34a13a9d-9306-4381-8487-9aa2b3aa7d3f">

I will select solution 1 and create a PR later.

PS: 
And I am not sure why in here need to file_upload image. Maybe the "webapp-text-generator" version did not match the newest dify version.

**Comment by ParseDark** [comment]
> Hi. @TigrisRiva and @crazywoola . I think I found the root cause. on the template part. Here will block the Index page render.↳
> 
> Solution 1: The template part needs to enhance this code. If not have upload image it should be made sure the code does not break down.↳
> 
> <img alt="image" width="1891" src="https://private-user-images.githubusercontent.com/26950370/288457292-6fc1f8ce-d63c-47f7-bc6b-000052fa95cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Nzc0NjgsIm5iZiI6MTcwMTg3NzE2OCwicGF0aCI6Ii8yNjk1MDM3MC8yODg0NTcyOTItNmZjMWY4Y2UtZDYzYy00N2Y3LWJjNmItMDAwMDUyZmE5NWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE1MzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MjRlODMxZmQyMjZiODc5ZTkyOWUwNGM3ZjdmZGJlYTYzYzNjYjljMDIyNThlN2U5YzQyYzA5NjUxZjJlOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dTY0Cxmu3gRuoQTtu2XUi4IiW-vD1EXCKlYhsvX6pqc">
> Solution 2: The backend should be make sure the API file_upload fields is "{}"
> 
> <img alt="image" width="1417" src="https://private-user-images.githubusercontent.com/26950370/288458065-34a13a9d-9306-4381-8487-9aa2b3aa7d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Nzc0NjgsIm5iZiI6MTcwMTg3NzE2OCwicGF0aCI6Ii8yNjk1MDM3MC8yODg0NTgwNjUtMzRhMTNhOWQtOTMwNi00MzgxLTg0ODctOWFhMmIzYWE3ZDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE1MzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YmUyMTU3ZTE3ZTAyZTFjOGVmNGJhMGFkMTI2NTY1Mjg2YzE5Y2RlZDBiNGZjYmRkNzY0YjhlNmM5NTBjMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hQS7csoUBCw_Qax5LaJPSJJJ6UI38L6GwaiqtlnaPMU">
> I will select solution 1 and create a PR later.↳
> 
> PS: And I am not sure why in here need to file_upload image. Maybe the "webapp-text-generator" version did not match the newest dify version.↳

And also it's my first pr on the dify. Just get some feedback if i miss some key point.

**Comment by TigrisRiva** [comment]
> Hi. @TigrisRiva and @crazywoola . I think I found the root cause. on the template part. Here will block the Index page render.
> 
> Solution 1: The template part needs to enhance this code. If not have upload image it should be made sure the code does not break down.
> 
> <img alt="image" width="1891" src="https://private-user-images.githubusercontent.com/26950370/288457292-6fc1f8ce-d63c-47f7-bc6b-000052fa95cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzUwMTcsIm5iZiI6MTcwMTkzNDcxNywicGF0aCI6Ii8yNjk1MDM3MC8yODg0NTcyOTItNmZjMWY4Y2UtZDYzYy00N2Y3LWJjNmItMDAwMDUyZmE5NWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA3MzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OTFiNWJhYjVlMzdmNGE4ODNlMjkwZTlmNmE0YTc4ODlkZDRlNjViNzFlYmQxZWFlZmE4MmYyMmI4YWNmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gY8lwJckHvYwb1lYq85_e6NCEWbjwULoV28oPjt6Zpg">
> Solution 2: The backend should be make sure the API file_upload fields is "{}"
> 
> <img alt="image" width="1417" src="https://private-user-images.githubusercontent.com/26950370/288458065-34a13a9d-9306-4381-8487-9aa2b3aa7d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzUwMTcsIm5iZiI6MTcwMTkzNDcxNywicGF0aCI6Ii8yNjk1MDM3MC8yODg0NTgwNjUtMzRhMTNhOWQtOTMwNi00MzgxLTg0ODctOWFhMmIzYWE3ZDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA3MzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOTcwZTZjMWZiYjkxMzM0NWQ0MDg2YWIxY2IzM2QwZmIzMWVjZDhhMjgyYzI5ZGIwZmJkZWI0NDAxMGJjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K-oSjSHgi5ZyYxELvCYUk3ZF1AhTNuMcMU8DS2QcsW4">
> I will select solution 1 and create a PR later.
> 
> PS: And I am not sure why in here need to file_upload image. Maybe the "webapp-text-generator" version did not match the newest dify version.

Thanks for your reply.
But it seems that we're talking about 2 totally diffrent project.
I'm facing the issue in project here: https://github.com/langgenius/webapp-conversation
However the bug you fixed is located in the project https://github.com/langgenius/webapp-text-generator

**Comment by ParseDark** [comment]
> > Hi. @TigrisRiva and @crazywoola . I think I found the root cause. on the template part. Here will block the Index page render.↳
> > Solution 1: The template part needs to enhance this code. If not have upload image it should be made sure the code does not break down.↳
> > <img alt="image" width="1891" src="https://private-user-images.githubusercontent.com/26950370/288457292-6fc1f8ce-d63c-47f7-bc6b-000052fa95cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzUwMTcsIm5iZiI6MTcwMTkzNDcxNywicGF0aCI6Ii8yNjk1MDM3MC8yODg0NTcyOTItNmZjMWY4Y2UtZDYzYy00N2Y3LWJjNmItMDAwMDUyZmE5NWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA3MzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OTFiNWJhYjVlMzdmNGE4ODNlMjkwZTlmNmE0YTc4ODlkZDRlNjViNzFlYmQxZWFlZmE4MmYyMmI4YWNmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gY8lwJckHvYwb1lYq85_e6NCEWbjwULoV28oPjt6Zpg">
> > Solution 2: The backend should be make sure the API file_upload fields is "{}"
> > <img alt="image" width="1417" src="https://private-user-images.githubusercontent.com/26950370/288458065-34a13a9d-9306-4381-8487-9aa2b3aa7d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzUwMTcsIm5iZiI6MTcwMTkzNDcxNywicGF0aCI6Ii8yNjk1MDM3MC8yODg0NTgwNjUtMzRhMTNhOWQtOTMwNi00MzgxLTg0ODctOWFhMmIzYWE3ZDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA3MzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOTcwZTZjMWZiYjkxMzM0NWQ0MDg2YWIxY2IzM2QwZmIzMWVjZDhhMjgyYzI5ZGIwZmJkZWI0NDAxMGJjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K-oSjSHgi5ZyYxELvCYUk3ZF1AhTNuMcMU8DS2QcsW4">
> > I will select solution 1 and create a PR later.
> > PS: And I am not sure why in here need to file_upload image. Maybe the "webapp-text-generator" version did not match the newest dify version.↳
> 
> Thanks for your reply. But it seems that we're talking about 2 totally diffrent project. I'm facing the issue in project here: https://github.com/langgenius/webapp-conversation However the bug you fixed is located in the project https://github.com/langgenius/webapp-text-generator↳

Sorry. My bad.....But the [webapp-conversation](https://github.com/langgenius/webapp-conversation) has this issue too. So I just keep open this pr.

And also I try to re-produce your issue. But I can't reproduce it. One possible reason is you open the global mode on your VPN. localhost can't send the request to the flask endpoint. But here have one issue in the 

You can try to back up your volumes. And restart a clean backend.

And one thing can improve on the template repo. We shouldn't just ignore all of the errors. We should add some logger for the application template.

https://github.com/langgenius/webapp-text-generator/blob/085e9fe51088f155c9b898be4a3855c08b4232b8/app/components/index.tsx#L361

<img width="1470" alt="image" src="https://github.com/langgenius/dify/assets/26950370/a4eb5035-cb5a-408b-b654-1634a61d3587">

**Comment by TigrisRiva** [comment]
I did very careful tracking today. The error occurs at line 209, which says:
`const isNotNewConversation = conversations.some(item => item.id === _conversationId)`
**The reason for the error is that conversations is undefined.** 

I continued to look up, and found that at line 204, the following line
`const [conversationData, appParams] = await Promise.all([fetchConversations(), fetchAppParams()])  `
returns an empty conversationData array. 
And the empty array causes line 207, which says:
`const { data: conversations } = conversationData as { data: ConversationItem[] } `to return conversations as undefined.

Upon further investigation of fetchConversations, I found that this service accesses a local address:
http://localhost:3000/api/conversations (with parameters), and this address returns an empty array.

I have traced the issue up to this point but still haven't found the root cause. I am not very familiar with Node.js. This is all the information I can provide so far.

**Comment by TigrisRiva** [comment]
Simply put, the reason for the error in this program is because it needs to fetch the history of conversations at the start and display them on the sidebar, but it did not consider the situation when the history of conversations is empty.

**Comment by TigrisRiva** [comment]
Program sloved
