### ISSUE TITLE
Dify worker crash while processing documents for indexing in weaviate

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#1701]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Setup dify in k8s using the helm chart from https://github.com/BorisPolonsky/dify-helm
- Configure s3 storage
- Create a Dataset and add multiple documents to it
- Watch the worker crash

*Hint: I was not yet able to reproduce it on a non-k8s environment*

### ✔️ Expected Behavior

- The worker processes all documents successfully

### ❌ Actual Behavior

- The worker crashes without any information (no logs, no sentry issues)

**Comment by perzeuss** [comment]
Here are some debug logs from the worker process: https://gist.github.com/perzeuss/48bd4a8f8e88c43632704e22667c376c

And here is a screenshot of the dify console after the crash:
![grafik](https://github.com/langgenius/dify/assets/11357019/46ad3657-dfec-4d0e-ae83-5291765be302)

After restart of the worker, it did not resume the indexing.

**Comment by perzeuss** [comment]
Any hints about where I could add additional debug logging would be helpful. I already made some adjustments to the worker code for more logging, but that did not help to find the source of the problem.

**Comment by perzeuss** [comment]
While testing, I found another issue which I might have fixed by this change: https://github.com/langgenius/dify/commit/cd96d8ec57056e4e91f76cdd07f71bd0d195da21 let me know if you can confirm that's a bug.

**Comment by JohnJyong** [comment]
Your commit did fix a bug, but it probably wasn't the cause of the worker service crash.
