### ISSUE TITLE
The Rerank model encounters a 502 error during mixed retrieval for recall.

### ISSUE THREAD

**Issue by JiangYain** [langgenius/dify#1703]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="956" alt="2bd2fcc04d835576ddcd3075da2199b" src="https://github.com/langgenius/dify/assets/116129630/621d0657-ea46-4302-b41c-3a07e0ae667e">
<img width="1080" alt="deff84e5f8f5b0df69eac33ee989390" src="https://github.com/langgenius/dify/assets/116129630/f5769b9d-9927-4459-a02d-59e6dd3e2b98">

### ✔️ Expected Behavior

Displaying the recall paragraphs correctly.

### ❌ Actual Behavior

The Rerank model encounters a 502 error during mixed retrieval for recall.

**Comment by crazywoola** [comment]
<img width="1683" alt="image" src="https://github.com/langgenius/dify/assets/100913391/8abb5d58-48d9-4dde-9ecd-191335b5aba1">
<img width="1504" alt="image" src="https://github.com/langgenius/dify/assets/100913391/977d4e81-8ea6-4896-870a-67f9022f83de">
So I tested with the VPN on it seems to work as expected. But I turn off the VPN, it will get a 502 error.
