### ISSUE TITLE
对话内容超限 Query or prefix is too long

### ISSUE THREAD

**Issue by sjn920336697** [langgenius/dify#1705]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Dify框架报Query or prefix prompt is too long, you can reduce the prefix prompt, or shrink the max token, or switch to a llm with a larger token limit size。

后端模型基于Xinference进行本地部署的ChatGLM2，max_tokens 为8192（8K），直接在Xinference输入一段内容2000多字的中文文本，可以正常回答。

基于Dify构建的对话应用，max_tokens 设置为450，输入同一段内容就报上述错误。

### ✔️ Expected Behavior

正常回复

### ❌ Actual Behavior

Query or prefix prompt is too long, you can reduce the prefix prompt, or shrink the max token, or switch to a llm with a larger token limit size。

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
