### ISSUE TITLE
Local deployment(docker) and cloud-based deployment(cloud.dify.ai) yield different search results for the same document.

### ISSUE THREAD

**Issue by yecan** [langgenius/dify#1707]
### Dify version

0.3.32

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

The same document is deployed locally using Docker and using on the cloud platform, both using full-text search withsame parameter configurations. I had multiple items in the test. While the cloud platform can almost always find the corresponding document, many items are not found locally using Docker.
![POPO20231206-172925](https://github.com/langgenius/dify/assets/31817154/3d5482dd-b3fc-40f2-916e-76dc83c0351a)
![POPO20231206-173028](https://github.com/langgenius/dify/assets/31817154/c5dc66a9-a09f-4f1a-a609-2475598e38a5)

### ✔️ Expected Behavior

can find the corresponding document in Local deployment using Docker.

### ❌ Actual Behavior

can not find the corresponding document in Local deployment using Docker.But can in cloud-based deployment.

**Comment by crazywoola** [comment]
This should be fixed in v0.3.33 :) Please wait for the new version.

**Comment by yecan** [comment]
Great! Looking forward to!
