### ISSUE TITLE
Knowledge : Text clean and chunk error

### ISSUE THREAD

**Issue by sjn920336697** [langgenius/dify#1715]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Can I use the built-in Text cleaning and chunk function in the Knowledge for my offline deployed Dify? 
Every time I perform a Chunk operation, I get a ConnectionError about `openaipublic.blob.core.windows.net error.` and `max tretries exceeded with url:/gpt-2/encoding/main/vocab.bpe`

**Comment by crazywoola** [comment]
This seems to be a typical network issue to me #694 . You setup a VPN for the server.
