### ISSUE TITLE
Chunk cannot be recalled

### ISSUE THREAD

**Issue by JiangYain** [langgenius/dify#1717]
### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Mixed search error after brokering the project with Clash; The normal vector and full-text search did not work, the right side load ended in a second, nothing was displayed and no errors were reported；
It should be added that even if context is added when building the app, it cannot be recalled in the answer
The error for the mixed search is as follows
<img width="327" alt="661c76942c984fe4db347da690a15ea" src="https://github.com/langgenius/dify/assets/116129630/95fc985c-c1fe-4fc5-a6d9-693045f32f17">

### ✔️ Expected Behavior

Normal accurate recall testing

### ❌ Actual Behavior

Mixed search error after brokering the project with Clash; The normal vector and full-text search did not work, the right side load ended in a second, nothing was displayed and no errors were reported；

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/1649

**Comment by JohnJyong** [comment]
the issue has fixed by this PR： https://github.com/langgenius/dify/pull/1740
