### ISSUE TITLE
Can I use a  variable value automatically from user dialogue  ?

### ISSUE THREAD

**Issue by jingyuan2017** [langgenius/dify#1722]
### Provide a description of requested docs changes

I am using API tools, and I have created two variables in my agent. However, I need to ask the user to fill in these two variables before the dialogue starts in order for them to have data. If the user doesn't fill them, empty values will be passed.

Is it possible to automatically extract variable values from the dialogue content and make API requests?

Thanks !

**Comment by crazywoola** [comment]
The variables are meant to be input by users or agents, so it should be done in a workflow rather than put them into one agent. We are working on the agent flow at this moment.

**Comment by octopuslabs-fl** [comment]
@crazywoola, is there any documentation of how to use the agent variables in a workflow? I would like to understand how they are used inside the prompt.
Thank you
