### ISSUE TITLE
Need Creator Role

### ISSUE THREAD

**Issue by nsvrana** [langgenius/dify#1723]
### Description of the new feature / enhancement

There are currently three fundamental permissions:

1. Login/access apps
2. Create apps/datasets
3. Add/remove other users, configure LLM APIs

The "User" group can do 1 and "Admin" can do 1/2/3. There should be a permission which is able to do 1/2, but not 3.

### Scenario when this would be used?

I would like to be able to enable other people in the organization to create LLM powered apps, but not to add/remove other users or change key API configurations. I imagine this necessary in most company/corporate environments.

**Comment by Adarsh0127** [comment]
is it paid platform??

**Comment by crazywoola** [comment]
The SaaS version of dify is a paid platform several days ago, because of we have launched the pricing plan. If you deploy the platform yourself, it is free.

**Comment by nsvrana** [comment]
Still need this. Is it tracked if I let this close?
