### ISSUE TITLE
can we add "Custom API Domain" for cohere rerank api

### ISSUE THREAD

**Issue by leslie2046** [langgenius/dify#1724]
### Description of the new feature / enhancement

can we add Custom API Domain for cohere rerank api,because cohere is banned by GFW,
i want to access it by my reserve proxy.just like openai api
![eb0ad1b648f274ada51de1edf4efd2a](https://github.com/langgenius/dify/assets/10449699/514a8ca2-8f1d-4b57-a867-f041bd8452f8)

### Scenario when this would be used?

None

### Supporting information

None

**Comment by wangxing7714436** [comment]
It would be great if you guys can add custom proxy url for proxy.

**Comment by crazywoola** [comment]
> It would be great if you guys can add custom proxy url for proxy.

We do support proxy by add HTTP_PROXY and HTTPS_PROXY to api and worker in compose file.

**Comment by leslie2046** [comment]
> > It would be great if you guys can add custom proxy url for proxy.
> 
> We do support proxy by add HTTP_PROXY and HTTPS_PROXY to api and worker in compose file.

it works
![图片](https://github.com/langgenius/dify/assets/10449699/4fcd890f-c265-46eb-bc18-e7e46c731c79)
