### ISSUE TITLE
Please support local models with Ollama

### ISSUE THREAD

**Issue by Chronoz** [langgenius/dify#1725]
### Description of the new feature / enhancement

support Ollama backend

### Scenario when this would be used?

use Ollama as backend to server different models

### Supporting information

thanks

**Comment by defiways** [comment]
What local models are supported currently?

**Comment by Chronoz** [comment]
System Inference Models that support local models like:  OpenLLM, localAI. Since Ollama has been my default go to local llm server, it would be great if Dify support Ollama (really easy to use), or LiteLLM. Thanks

**Comment by goodfella2000** [comment]
Agreed. Ollama is so much easier to setup and run support would be very much appreciated. OpenLLM and LocalAI has had installation issues for me.

**Comment by countupPR** [comment]
It would be great to be able to use ollama with dify. For example using the API of a local ollama and then add the model we want to use.

**Comment by Namec999** [comment]
+1

**Comment by AndyMik90** [comment]
+1

**Comment by EmmaWebGH** [comment]
+1 for this, eagerly awaiting.

I have also tried adding the API for text-generation-webui (oobabooga) but can't get it to work,
as noted in my comment on https://github.com/langgenius/dify/issues/1886
This is also used by many people and would help bring more users into Dify.

**Comment by viktorbezdek** [comment]
@takatost Do you have development documentation somewhere? I'm considering implementing it, but I'd like to be able to evaluate necessary effort.

**Comment by takatost** [comment]
> @takatost Do you have development documentation somewhere? I'm considering implementing it, but I'd like to be able to evaluate necessary effort.

Yeah, we have a contribution document for the model integration: https://github.com/langgenius/dify/blob/main/api/core/model_runtime/README.md. 

btw, the integration of Ollama is already in the main branch and will be available in v0.4.6. 😄

**Comment by takatost** [comment]
> > @takatost Do you have development documentation somewhere? I'm considering implementing it, but I'd like to be able to evaluate necessary effort.
> 
> Yeah, we have a contribution document for the model integration: https://github.com/langgenius/dify/blob/main/api/core/model_runtime/README.md.
> 
> btw, the integration of Ollama is already in the main branch and will be available in v0.4.6. 😄

v0.4.6 released
https://github.com/langgenius/dify/releases/tag/0.4.6
