### ISSUE TITLE
类型错误

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1726]
### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

<img width="980" alt="截屏2023-12-09 16 03 24" src="https://github.com/langgenius/dify/assets/1925650/b5fd569d-832a-48e9-98a5-6b7c2da62ea5">

### ✔️ Expected Behavior

默认值类型是bool

### ❌ Actual Behavior

默认值类型不对

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/1542
