### ISSUE TITLE
本地部署版本 怎么添加或制作模版应用？

### ISSUE THREAD

**Issue by justinzm** [langgenius/dify#1727]
### Dify version

0.3.21

### Utility with translation issue

无

### 🌐 Language affected

无

### ❌ Actual phrase(s)

本地部署版本 怎么添加或制作模版应用？

### ✔️ Expected phrase(s)

本地部署版本 怎么添加或制作模版应用？

### ℹ Why is the current translation wrong

本地部署版本 怎么添加或制作模版应用？

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542, Please read the https://docs.dify.ai for getting business support for templates.
