### ISSUE TITLE
Local deployment by docker can't process installation properly

### ISSUE THREAD

**Issue by tomylab** [langgenius/dify#1729]
### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After deploying locally by docker image, the process remains stuck on the loading state of the install page.
![_tmp_dingtalkgov_qt_clipbord_pic_2](https://github.com/langgenius/dify/assets/134911115/959474bb-2fea-49b9-82ca-0e812c270bd5)

**Comment by crazywoola** [comment]
Please paste the logs in the browser's console.

**Comment by dmerriman11** [comment]
Exposing the port 3000 to bypass nginx has the same results however its a 404 error during the install process.

![image](https://github.com/langgenius/dify/assets/61134940/39dfc18f-5bd0-4f10-aa79-e380b867f5ac)

**Comment by crazywoola** [comment]
It seems your docker containers are not started correctly all. I guess you port 80  is conflict with the dify's nginx default port conf.  You can turn off the nginx and use the dify's configuration.

**Comment by MiiViiDynamics** [comment]
It works fine on my M1 macbook, which has no other docker.
But on my x86 server, save behavior happens even I disable nginx.
The faile log attached.

The log shows as below.
Also I tried to disable MIGRATION_ENABLED, but other failuer happens.
docker-worker-1    | OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
docker-worker-1    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
docker-worker-1    | OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted

docker-api-1       | Running migrations
docker-api-1       | OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
docker-api-1       | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
docker-api-1       | OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
docker-api-1       | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
docker-api-1       | OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not [permitte[](url)]([log.txt](https://github.com/langgenius/dify/files/13779005/log.txt))

**Comment by MiiViiDynamics** [comment]
I found it's my docker version related.
After I upgrade docker to the latest version, it works.
