### ISSUE TITLE
Embedding模型不生效

### ISSUE THREAD

**Issue by opsvr** [langgenius/dify#1730]
### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

对接xinference，推理模型：chatglm3-6b，embedding模型：bge-base-zh
在知识库上传文档后，右上角提示错误，HTTPSConnectionPool(host='openaipublic.blob.core.windows.net',port=443)，api日志有对应请求openaipublic.blob.core.windows.net日志，由于内网环境openaipublic.blob.core.windows.net无法访问。
似乎是在文档上传后进行向量化处理时使用的是外网openaipublic.blob.core.windows.net进行向量化，没有调用本地配置的embedding模型。

### ❌ Actual Behavior

在知识库上传文档后，右上角提示错误，HTTPSConnectionPool(host='openaipublic.blob.core.windows.net',port=443)，api日志有对应请求openaipublic.blob.core.windows.net日志，由于内网环境openaipublic.blob.core.windows.net无法访问。
似乎是在文档上传后进行向量化处理时使用的是外网openaipublic.blob.core.windows.net进行向量化，没有调用本地配置的embedding模型。

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
