### ISSUE TITLE
API service report :None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

### ISSUE THREAD

**Issue by wangxing7714436** [langgenius/dify#1733]
### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Normaly build the environment by instruction.

### ✔️ Expected Behavior

while doing document indexing, api service will report: None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used. however, the service works just fine but a little slow.

**Comment by crazywoola** [comment]
Try `pip install -r requirements.txt --upgrade --force-reinstall`.

**Comment by xsxs89757** [comment]
This has happened to me, and the service is still available.

**Comment by ZuzooVn** [comment]
> This has happened to me, and the service is still available.
@xsxs89757 
Have you discovered an approach to solve the problem?

**Comment by Halfknow** [comment]
> > This has happened to me, and the service is still available.
> 
> @xsxs89757 Have you discovered an approach to solve the problem?

Have you encounter the streaming output not character-by-character problem caused by this warning?
