### ISSUE TITLE
How to change the placeholder without changing the USER INPUT FIELD NAME

### ISSUE THREAD

**Issue by MEreee** [langgenius/dify#1734]
### Description of the new feature / enhancement

How to change the placeholder without changing the USER INPUT FIELD NAME?
![Placeholder](https://github.com/langgenius/dify/assets/51728755/a261c28c-1355-4ba3-82d2-d96ce2202856)

### Scenario when this would be used?

I want to show the format with the placeholder as an example so would like to change the placeholder to something different from the field name.

**Comment by crazywoola** [comment]
The fields are dynamic generated from the prompt. These input boxes offer a way to alias a field name. We haven't support editing a placeholder or setting default values.
