### ISSUE TITLE
local embedding model not support

### ISSUE THREAD

**Issue by opsvr** [langgenius/dify#1737]
### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Knowledge-->select or create knowledge db-->upload a file-->next-->select Economical

### ❌ Actual Behavior

After uploading a document to the knowledge base, there is an error message on the top right corner. The HTTPSConnectionPool(host='openaipublic.blob.core.windows.net',port=443) API log has a corresponding request to openaipublic.blob.core.windows.net log, but due to the intranet environment, openaipublic.blob.core.windows.net cannot be accessed. It seems that the vectorization process uses the external network openaipublic.blob.core.windows.net for vectorization after uploading the document, and does not call the locally configured embedding model.

![api_error_log](https://github.com/langgenius/dify/assets/149289196/a3813f52-b9d0-47ca-a676-1f5c289c45e8)
![model_set](https://github.com/langgenius/dify/assets/149289196/d1cc6b46-d035-4634-a686-c8a706d26545)
![error1](https://github.com/langgenius/dify/assets/149289196/680e140c-ca87-4a78-b58f-661052e92646)

**Comment by crazywoola** [comment]
Duplicate #1514 This is a network issue. You need to setup the VPN because we are using hugging face model to calculate the tokens.
