### ISSUE TITLE
Inquiry on Admin and User Account Creation in Dify, and Active Directory Integration

### ISSUE THREAD

**Issue by MrBrabus75** [langgenius/dify#1744]
### Provide a description of requested docs changes

Hello,

I've been using Dify locally for testing purposes and have created the initial account during the installation process, which I assume has admin privileges. I have a couple of queries regarding account management and integration:

Multiple Admin and User Accounts: Is it possible to create additional admin and user accounts in Dify? If so, could you guide me through the process or point me to the relevant documentation?

Integration with Active Directory: For future implementation in an enterprise environment, is there a way to link Dify accounts with an Active Directory? This feature would be crucial for streamlined user management and security. Any insights or resources on how to set this up would be greatly appreciated.

Looking forward to your guidance and suggestions on these matters.

Best regards

**Comment by crazywoola** [comment]
- We only support one admin account which is initialized when you setup the account. This account can invite multiple users as normal users.
- We will provide sso as a login method.

**Comment by MrBrabus75** [comment]
With SSO authentication, will it allow me to link authentication to AD? Will it not be blocked? 
Is it possible to create user and admin accounts later?

**Comment by crazywoola** [comment]
> With SSO authentication, will it allow me to link authentication to AD? Will it not be blocked? Is it possible to create user and admin accounts later?

Nope I think, when you linked an account in our platform, we will automatically create one user in our database.

**Comment by MrBrabus75** [comment]
Do you mean for the cloud version? And what about the self-hosted ?

**Comment by MrBrabus75** [comment]
? Sorry for re up the topic

**Comment by crazywoola** [comment]
Hello there,
This part `Admin and User Account Creation` need to be implemented from your side, so it needs some kind of modifications in code base and database itself.
This feature can be done, but we do not have capacity for the feature right now. To tell the truth, the logic user account part is quite simple now. So you can do whatever you like to implement, sso or something else.
Not sure if this answer your question.

**Comment by MrBrabus75** [comment]
Thank you for your response. You've addressed all of my questions. I'll start working on implementing this feature and will share the code on GitHub for those who are interested.
