### ISSUE TITLE
full text search not work

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1745]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Use weaviate's full-text search. For the same dataset, the full-text search results are different in hit testing and dialogue applications, and no context is found in the dialogue.
<img width="1743" alt="截屏2023-12-12 12 34 47" src="https://github.com/langgenius/dify/assets/1925650/65378341-5c2c-4103-87b2-566d7424afdd">
<img width="1535" alt="image" src="https://github.com/langgenius/dify/assets/1925650/f07db6e3-468e-4a1e-8054-1b805425c224">

### ✔️ Expected Behavior

It can retrieve results normally

### ❌ Actual Behavior

Currently, the results of full-text search are different in two places. And it seems that the search effect for Chinese is not very good.

**Comment by crazywoola** [comment]
<img width="765" alt="image" src="https://github.com/langgenius/dify/assets/100913391/546a51a8-8895-417e-bbfc-60ecfecd92d8">
Or edit the prompt by using `/` to add your context.
