### ISSUE TITLE
多轮对话，向量搜索只用用户最新输入的问题来搜索向量

### ISSUE THREAD

**Issue by xutengfei** [langgenius/dify#1755]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

比如用户搜索比亚迪是谁，第二轮搜索他的优势是什么。第二次问题搜索出来的向量跟比亚迪就没关系

### ✔️ Expected Behavior

多轮对话，应该把用户输入的内容拼起来做向量搜索

### ❌ Actual Behavior

第二，第三轮对话，内容不相关

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by cristianohello** [comment]
@xutengfei 

你这个我遇到了，已经解决了

**Comment by xutengfei** [comment]
> @xutengfei
> 
> 你这个我遇到了，已经解决了

怎么解决的？

**Comment by Garhorne0813** [comment]
> @xutengfei
> 
> 你这个我遇到了，已经解决了

请问您是如何解决的？能否提供一下思路？谢谢

**Comment by lonngxiang** [comment]
同问
