### ISSUE TITLE
multiple conversation, how to seach vector with all the user input 

### ISSUE THREAD

**Issue by xutengfei** [langgenius/dify#1756]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

first convesation i search "BYD company" , second conversation i search "what was it's advantages",the response of vector search was not about "BYD"

### ✔️ Expected Behavior

all response of vector search was about all the  user input

### ❌ Actual Behavior

the response of vector search was about user intends

**Comment by guchenhe** [comment]
Retrieval is done on a per-query basis by design, so it's expected that your second search won't return documents relevant to your first search. 

However, in an actual conversation the model does have knowledge on your previous queries and retrieval results, and will respond accordingly (how well it retains previous context also depends on how you've written your prompts & context window)

**Comment by xutengfei** [comment]
> Retrieval is done on a per-query basis by design, so it's expected that your second search won't return documents relevant to your first search.
> 
> However, in an actual conversation the model does have knowledge on your previous queries and retrieval results, and will respond accordingly (how well it retains previous context also depends on how you've written your prompts & context window)

we found if we use gtp4 in dify, it will change the second search query automaticlly, that very cool. But it won't work when use other llm model.

**Comment by VincePotato** [comment]
We use chat history as input context for chat model to better understand user query. That is not achieved through rewriting the user query.

**Comment by xutengfei** [comment]
> We use chat history as input context for chat model to better understand user query. That is not achieved through rewriting the user query.

this could not take advantage of Vector search，because  chat history is not similar to vector data
