### ISSUE TITLE
why gpt-4 could change the vector search keywords in the second conversation , by other LLM model can not do this

### ISSUE THREAD

**Issue by xutengfei** [langgenius/dify#1759]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.32

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

why gpt-4 could change the vector search keywords in the second conversation, by other LLM model could not chang the keyword（use whatever that user input）
<img width="1006" alt="image" src="https://github.com/langgenius/dify/assets/1303119/878bddb0-1ea8-4746-a475-c69458defa44">
<img width="867" alt="image" src="https://github.com/langgenius/dify/assets/1303119/6b01a552-842d-40b4-aec4-cfb8ea6dea03">

### ✔️ Expected Behavior

change the keywords to right intention of user, not the user input

### ❌ Actual Behavior

search vector with whatever user typed in the second conversation

**Comment by guchenhe** [comment]
Hi there,

could you provide more info, like embedding model and prompt used?

**Comment by xutengfei** [comment]
prompt: you are an analyst ，you will give a report about {{input}} 
embedding : text2vec
LLM: baichuan\chatglm\gpt4

**Comment by xutengfei** [comment]
> Hi there,
> 
> could you provide more info, like embedding model and prompt used?

prompt: you are an analyst ，you will give a report about {{input}}
embedding : text2vec
LLM: baichuan\chatglm\gpt4
