### ISSUE TITLE
Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by maxjeblick** [langgenius/dify#1760]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

c09184f

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When starting docker compose, I'm getting the error mentioned in the title.
Steps to reproduce:
- clone repository
- start docker compose

Output of `sudo lsof -i :80`
```
 max@max  ~/PycharmProjects/dify/docker   main  sudo lsof -i :80
COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
apache2    1247     root    4u  IPv6  35366      0t0  TCP *:http (LISTEN)
apache2    1249 www-data    4u  IPv6  35366      0t0  TCP *:http (LISTEN)
apache2    1250 www-data    4u  IPv6  35366      0t0  TCP *:http (LISTEN)
tailscale  1521     root   18u  IPv6  39312      0t0  TCP dynamic-2a01-0c22-7ac1-fb00-1ee9-7d77-ca38-4f28.c22.pool.telefonica.de:41942->[2a05:d014:386:202:30f5:de62:8eed:5c47]:http (ESTABLISHED)
firefox   23568      max   72u  IPv4 309931      0t0  TCP max:60426->82.221.107.34.bc.googleusercontent.com:http (ESTABLISHED)
firefox   23568      max  104u  IPv6 309928      0t0  TCP dynamic-2a01-0c22-7ac1-fb00-1ee9-7d77-ca38-4f28.c22.pool.telefonica.de:35548->[2600:1901:0:38d7::]:http (ESTABLISHED)
firefox   23568      max  106u  IPv6 309929      0t0  TCP dynamic-2a01-0c22-7ac1-fb00-1ee9-7d77-ca38-4f28.c22.pool.telefonica.de:35560->[2600:1901:0:38d7::]:http (ESTABLISHED)
```

### ✔️ Expected Behavior

Docker compose works without an issue.

### ❌ Actual Behavior

`Error response from daemon: driver failed programming external connectivity on endpoint docker-nginx-1 (a4c0b574f8d2b6bb91a0bd6c6371b17244fb057360eccafec97a5a39dba87f82): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
`

**Comment by maxjeblick** [comment]
I solved the issue by running `sudo /etc/init.d/apache2 stop` (see here: https://github.com/laradock/laradock/issues/16).

Might be useful to add this to FAQ. Otherwise I can close this issue.

**Comment by crazywoola** [comment]
Thanks, I have just update the docs. 👉 [here](https://docs.dify.ai/getting-started/faq/install-faq#13.-how-to-solve-listen-tcp4-0.0.0.0-80-bind-address-already-in-use). I will close this issue. Thanks bro.
