### ISSUE TITLE
Request for Redmine API Integration with Dify

### ISSUE THREAD

**Issue by MrBrabus75** [langgenius/dify#1762]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello,

Firstly, I would like to express my appreciation for Dify; it’s an incredible tool, and I’m grateful for the hard work that has gone into it.

However, I have a specific request. I’m interested in knowing if it’s feasible to implement an extension that would allow the use of Redmine’s API with Dify. The main purpose of this extension would be to enable searches within Redmine issues and responses, and to obtain relevant information through the LLM during these searches.

This functionality would greatly enhance the utility of Dify for users who frequently interact with Redmine for issue tracking and project management.

Looking forward to hearing your thoughts on this possibility.

Thank you.

**Comment by crazywoola** [comment]
Actually yes. see the [docs](https://docs.dify.ai/advanced/extension/api_based_extension) here. You can use this feature to implement a custom api to integrate with redmine and jira like task management system. This request payload might look like this to this endpoint.

```json
{
    "point": "app.external_data_tool.query",
    "params": {
        "app_id": "61248ab4-1125-45be-ae32-0ce91334d021",
        "tool_variable": "weather_retrieve",
        "inputs": {
            "location": "London"
        },
        "query": "How's the weather today?"
    }
}
```
