### ISSUE TITLE
Support same model with multiple providers

### ISSUE THREAD

**Issue by L929333353** [langgenius/dify#1765]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Support same model with multiple providers

### Scenario when this would be used?

Same model with multiple providers

**Comment by crazywoola** [comment]
Can you explain a little on this? Because I am not sure what you are going to achieve.

**Comment by L929333353** [comment]
I got same model named vicuna-13b, but in 2 different provider end point server.

**Comment by crazywoola** [comment]
You mean using hf and replicate?
