### ISSUE TITLE
if I deploy an chagpt like api by myself, can it be registered by openllm?

### ISSUE THREAD

**Issue by LCorleone** [langgenius/dify#1778]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

hi, i suppose that if i offer an api like chatgpt, no matter how, using openllm or localai or by myself,  it can be registered by dify. am i right?
i deploy an api by https://github.com/xusenlinzy/api-for-open-llm/tree/master, it offer apis like chatgpt, and then i want to register this api in dify, i try the openllm. but failed. it stuck in validating. any suggestions?

### ✔️ Expected Behavior

failed as discussed

### ❌ Actual Behavior

failed as discussed

**Comment by crazywoola** [comment]
Can you paste the logs in openllm? You can try to ask a issue in their reop. Seems a issue related to their code.

**Comment by LCorleone** [comment]
> Can you paste the logs in openllm? You can try to ask a issue in their reop. Seems a issue related to their code.

hello, I mean that I deploy an chatgpt style api by myself using [api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm/tree/master) , not using openllm, and my question is how it can be registered in dify? it seems no entrance other than openllm, localai and xinference (sorry for some reasons I cannot use them).  So I just try the openllm in model provider because both of them are chatgpt style apis, and i wish it can work but no. I think no matter how the api is deploy, if it is a chatgpt style api it can work.

**Comment by LCorleone** [comment]
update, it seems if i deploy an api following the openllm style (request and response) by myself, this api can rigister by openllm in the model provider?

**Comment by LCorleone** [comment]
yep, I successfully register an api deployed by myself, not using openllm or localai... close this issue
