### ISSUE TITLE
The Dify's Azure OpenAI need add gpt-35-turbo-instruct base model

### ISSUE THREAD

**Issue by laoya2003** [langgenius/dify#1779]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

The Dify's Azure OpenAI configure can not to find  then gpt-35-turbo-instruct base model, sometime ,we need to use the instructGPT with prompts。

### Scenario when this would be used?

The Dify's Azure OpenAI configure can not to find  then gpt-35-turbo-instruct base model, sometime ,we need to use the instructGPT with prompts。

**Comment by GarfieldDai** [comment]
<img width="675" alt="image" src="https://github.com/langgenius/dify/assets/28395549/fa64870a-5e41-43eb-a03a-dcac52237697">
Hi @laoya2003 , Dify supports it now.

**Comment by GarfieldDai** [comment]
#1858
