### ISSUE TITLE
I payed for the US$59.00/mon stategy, but can add more members to my team

### ISSUE THREAD

**Issue by markqiu** [langgenius/dify#1782]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.23

### Cloud or Self Hosted

Cloud

### Steps to reproduce

check my account information

**Comment by crazywoola** [comment]
Hello can you send a email to support@dify.ai and provide your account information (email using for dify)?

**Comment by markqiu** [comment]
ok，let me try

**Comment by crazywoola** [comment]
It has been fixed, you can refresh the page to see it.
