### ISSUE TITLE
Logs export to file

### ISSUE THREAD

**Issue by leslie2046** [langgenius/dify#1786]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

we need to export logs from apps(both Chat app and Text generator app) to file(eg:JSONL, csv).
include query,answer,like,dislike,annotation infomations with session id 

### Scenario when this would be used?

We can finetune or train some other models by these logs,and we alse can do big data statistics and analysis。

**Comment by VincePotato** [comment]
That is a reasonable suggestion, we'll consider adding that feature.

**Comment by izokimani** [comment]
I don't get it.  Where's the export log feature?

**Comment by JunIce** [comment]
#7968 Maybe this pr is useful

**Comment by VincePotato** [comment]
Thank you for the feedback. Log export has been included in the product roadmap.
