### ISSUE TITLE
api能否改成跟openai一样的格式？包括请求路径和入参？方便其它应用接入

### ISSUE THREAD

**Issue by vual** [langgenius/dify#1798]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

api能否改成跟openai一样的格式？包括请求路径和入参？方便其它应用接入

### Scenario when this would be used?

方便其它一些应用接入

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
