### ISSUE TITLE
前端代码的格式化规范统一

### ISSUE THREAD

**Issue by saifeiLee** [langgenius/dify#180]
你好，我想贡献代码，但是发现项目里没有统一代码格式化的配置。能否补充一下，方便我们以统一格式提交代码。

**Comment by JohnJyong** [comment]
@iamjoel @nite-knite

**Comment by iamjoel** [comment]
代码风格可以按 https://github.com/standard/standard 来，缩进两个。下面我们会加 lint 之类的配置。

**Comment by iamjoel** [comment]
Added: https://github.com/langgenius/dify/pull/242
