### ISSUE TITLE
Local Start Stuck At Install

### ISSUE THREAD

**Issue by MirzaAreebBaig** [langgenius/dify#1800]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Hello,
I have followed all the instructions for the local start but its stuck at install

![image](https://github.com/langgenius/dify/assets/45519744/bb512c28-7d98-476a-a315-52dfc03802fb)
![image](https://github.com/langgenius/dify/assets/45519744/3bf66030-1835-4b52-b5b2-17b32639cbed)

All the services are up & running but still its stuck.

**Comment by crazywoola** [comment]
https://docs.dify.ai/getting-started/install-self-hosted/local-source-code

There are couple of things you need to be aware of:

- `.env` file under the web directory.
- The install page you pasted in the image, I guess the url isn't like http://localhost:3000/install, maybe something like http://x.x.x.x:3000/install instead. So it won't be able to connect to the localhost as expected. You need to change this in the `.env` file.
- Make sure the backend service is available from the internet, eg: `curl -X http://x.x.x.x:5001/api` should return things and you can see the logs if you deployed to a server.

**Comment by MirzaAreebBaig** [comment]
Hello,
The error was solved by adjusting web env from SELF-HOSTED to CLOUD
But now i'm unable to see the login form it just loads the 2 SSO options how to get the login form?

![image](https://github.com/langgenius/dify/assets/45519744/5206d738-fe88-488c-8b5c-7f9a3279cece)

**Comment by omesh845** [comment]
> CLOUD

what exactly you changed in the Web Env can plz  you mention it, like `CLOUD: true` or something like that and did you able to solve other than SSO options?

**Comment by K8sKween** [comment]
They should really cover it in the docs here: [DOCS](https://docs.dify.ai/getting-started/install-self-hosted/environments)
But I don't see it so on mine it is set as `EDITION` with the options being `SELF_HOSTED` and `CLOUD`

**Comment by oristides** [comment]
This is related to the URL of the API..  The Web service cannot reach API Service So For testing in local+ docker compose you need to use on .env file.

CONSOLE_API_URL: http://localhost:5001
SERVICE_API_URL: http://localhost:5001

It worked for me.

**Comment by danielrosehill** [comment]
Dealing with the exact same issue.

**Comment by M4g3dd0** [comment]
I have encountered the same issue. Adding to oristides's response, API has to be accessible outside of docker, if you run it on a separate docker server. So port mapping is the way.
