### ISSUE TITLE
No gpt-4-vision-preivew in 0.3.34

### ISSUE THREAD

**Issue by zhangao0086** [langgenius/dify#1809]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I updated dify to the latest version 0.3.34:
<img width="270" alt="image" src="https://github.com/langgenius/dify/assets/7742344/6d65a4dc-25ef-4a4a-a969-d39ac23d0ad3">

but there is no 'gpt-4-vision-preivew' in the dropdown list of the Azure OpenAI Service Model:
<img width="616" alt="image" src="https://github.com/langgenius/dify/assets/7742344/7e392599-d2b8-43dd-b670-30a0e7d9d17d">

How can I enable the 'vision' feature?

### ✔️ Expected Behavior

There is a 'gpt-4-vision-preivew' option in the dropdown list.

### ❌ Actual Behavior

No option available.

**Comment by zhangao0086** [comment]
@crazywoola  Yes, the configuration looks fine:
<img width="420" alt="image" src="https://github.com/langgenius/dify/assets/7742344/28c2bbf3-49b0-4dd9-9a5f-27bc434aeaf2">

**Comment by zhangao0086** [comment]
@crazywoola Does the configuration of the web need to be updated?
https://github.com/langgenius/dify/blob/main/web/app/components/header/account-setting/model-page/configs/azure_openai.tsx#L118
<img width="655" alt="image" src="https://github.com/langgenius/dify/assets/7742344/3381aa06-8513-43cf-a56a-60abe6031ff9">

**Comment by ianZzzzzz** [comment]
0.3.34 Still no 'gpt-4-vision-preivew' in the dropdown list of the Azure OpenAI Service Model.
<img width="727" alt="截屏2023-12-23 19 01 32" src="https://github.com/langgenius/dify/assets/67948011/c8bdc90f-dccd-4321-b4c7-5ca68aae6083">
