### ISSUE TITLE
Can the API be changed to the same format as OpenAI? Including request path and input parameters? Convenient access for other applications

### ISSUE THREAD

**Issue by vual** [langgenius/dify#1817]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Can the API be changed to the same format as OpenAI? Including request path and input parameters? Convenient access for other applications

### Scenario when this would be used?

 Convenient access for other applications

**Comment by crazywoola** [comment]
No, because we are a platform for multiple model providers, each of them might have different format, so we can not just use the same format as OpenAI.

**Comment by waltcow** [comment]
Maybe we can provide a provider option for those openai compatible model provider
