### ISSUE TITLE
Hope to add Azure AI search function to Dify

### ISSUE THREAD

**Issue by showjiangnan** [langgenius/dify#1819]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Hope to add Azure AI search function to Dify

### Scenario when this would be used?

In the current version, Azure AI search service is not supported. I hope developers can update a more powerful related feature:
1. When we add the Azure GPT4 model, we can additionally input Azure AI to search for it_ Endpoint, search_ Key, search index name;
2. Combining the ability of Azure AI search, I found that GPT4 combined with the knowledge base resulted in more accurate responses;

### Supporting information

https://learn.microsoft.com/zh-CN/azure/search/retrieval-augmented-generation-overview

**Comment by rachaelsingleton** [comment]
Any updates on this?
