### ISSUE TITLE
Repeated batch running tasks in text generation applications get stuck（10 records）

### ISSUE THREAD

**Issue by Chackca** [langgenius/dify#1823]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1.Create an app like this
<img width="993" alt="image" src="https://github.com/langgenius/dify/assets/24273109/a45b01aa-a81a-431f-aaac-acf1168d22e8">

2.Rediret to the preview url

3.Upload a csv file like this（10 records！）
<img width="384" alt="image" src="https://github.com/langgenius/dify/assets/24273109/adbf3954-aa2c-4197-bd6e-5cdd37eb4c41">

4.First Run -> success（All 10 records were successfully exported）

5.Second(Repeat) Run -> （Only 5 record where exported, And the web is stuck after the first 5 records are generated, and keeps turning in circles ）

### ✔️ Expected Behavior

<img width="1229" alt="image" src="https://github.com/langgenius/dify/assets/24273109/138d7344-5f41-4d70-978d-030a4c9a5343">

### ❌ Actual Behavior

<img width="1254" alt="image" src="https://github.com/langgenius/dify/assets/24273109/086caf11-2c6c-4341-8e0d-783c27248a3e">

The web is stuck after the first 5 records are generated, and keeps turning in circles

**Comment by crazywoola** [comment]
I have tested in Cloud version and self hosted version, cant reproduce this problem? Can you try to upload them again? Or turn on the console to see the error there, that should be helpful to us to narrow down the issue.

**Comment by Chackca** [comment]
The first times touch run
<img width="2529" alt="image" src="https://github.com/langgenius/dify/assets/24273109/c626f24e-1044-46cc-ba7d-8d6119c17eea">

The second times touch run
<img width="2284" alt="image" src="https://github.com/langgenius/dify/assets/24273109/68200bdf-bdd6-4a02-ba8a-62c2fee382d5">

Cannot see error in console, try at 19:30~19:39

**Comment by Chackca** [comment]
Prompt below：
请将以下输入内容翻译成英文后输出，如果原本是英文，则不用翻译
```
{{query}}
```
File below

[template2.csv](https://github.com/langgenius/dify/files/13751981/template2.csv)

**Comment by zxhlyh** [comment]
#1945 fixed
