### ISSUE TITLE
通过docker本地部署dify，登录提示404

### ISSUE THREAD

**Issue by Jonathan-Wei** [langgenius/dify#1827]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

通过docker本地部署dify，配置好邮箱后登录dify，无法登录，提示http://127.0.0.1:3000/console/api/login 404
![image](https://github.com/langgenius/dify/assets/3073018/487a6960-d181-4c58-8707-726299684fb5)

**Comment by Jonathan-Wei** [comment]
重新刷新页面登录又可以了。

**Comment by LinightKira** [comment]
我也是相同的问题，刷新后还不行

**Comment by RyzeAngler** [comment]
> 我也是相同的问题，刷新后还不行

参照代码仓文档，需要先初始化，浏览器执行 http://localhost/install

**Comment by Tendo33** [comment]
> > 我也是相同的问题，刷新后还不行
> 
> 参照代码仓文档，需要先初始化，浏览器执行 http://localhost/install

docker compose 之后打不开这个

**Comment by xxz7909** [comment]
我卡在install这一步了，请求 URL
http://10.3.0.181:3000/console/api/setup
请求方法
GET
状态代码
404 Not Found
远程地址
10.3.0.181:3000
引用站点策略
strict-origin-when-cross-origin  怎么办

**Comment by gengpeip** [comment]
> 我卡在install这一步了，请求 URL http://10.3.0.181:3000/console/api/setup 请求方法 GET 状态代码 404 Not Found 远程地址 10.3.0.181:3000 引用站点策略 strict-origin-when-cross-origin 怎么办

你好，请问你解决了吗

**Comment by xxz7909** [comment]
还没有

**Comment by CCCCoral** [comment]
> 创建ollama模型报404各位知道什么原因吗,基础url我在cmd中是会响应ollama is running
> 
> ![Image](https://github.com/user-attachments/assets/59e089e4-4af4-4dd9-a324-0f16bbf73680)

我也碰到一样的问题，你解决了吗
