### ISSUE TITLE
Nginx's issue during local deployment

### ISSUE THREAD

**Issue by mikhasev** [langgenius/dify#1832]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Installed Docker Desktop (Win11 Pro)
Rebooted
Activated Docker
Ran docker_compose.yml

### ✔️ Expected Behavior

Able to run localhost/install

### ❌ Actual Behavior

[+] Running 6/0
 ✔ Container mikha-web-1       Running                                                                             0.0s
 ✔ Container mikha-db-1        Running                                                                             0.0s
 ✔ Container mikha-redis-1     Running                                                                             0.0s
 ✔ Container mikha-weaviate-1  Running                                                                             0.0s
 ✔ Container mikha-api-1       Running                                                                             0.0s
 ✔ Container mikha-worker-1    Running                                                                             0.0s
Attaching to api-1, db-1, nginx-1, redis-1, weaviate-1, web-1, worker-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/c/Users/mikha/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /run/desktop/mnt/host/c/Users/mikha/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by crazywoola** [comment]
I assume you only copied the `docker-compose.yml` right?
You should copy the whole docker directory instead. That will do the job.
