### ISSUE TITLE
创建 Xinference Embeddings 模型报错

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#1833]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- 截图
![124](https://github.com/langgenius/dify/assets/21255047/793c0b12-d755-40e1-9a5e-b3558f18f32e)

- 错误日志
`
CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus= CUDA call was originally invoked at: File "<string>", line 1, in <module> File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/forkserver.py", line 274, in main code = _serve_one(child_r, fds, File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one code = spawn._main(child_r, parent_sentinel) File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/spawn.py", line 125, in _main prepare(preparation_data) File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare _fixup_main_from_path(data['init_main_from_path']) File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path main_content = runpy.run_path(main_path, File "/home/miniconda3/envs/xinference/lib/python3.10/runpy.py", line 289, in run_path return _run_module_code(code, init_globals, run_name, File "/home/miniconda3/envs/xinference/lib/python3.10/runpy.py", line 96, in _run_module_code _run_code(code, mod_globals, init_globals, File "/home/miniconda3/envs/xinference/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/miniconda3/envs/xinference/bin/xinference-local", line 5, in <module> from xinference.deploy.cmdline import local File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/__init__.py", line 32, in <module> _install() File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/__init__.py", line 29, in _install install_model() File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/__init__.py", line 17, in _install from .llm import _install as llm_install File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/__init__.py", line 19, in <module> from .core import LLM File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/core.py", line 22, in <module> from ...core.utils import parse_replica_model_uid File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/__init__.py", line 15, in <module> from .model import ModelActor File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 49, in <module> from torch.cuda import OutOfMemoryError File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/__init__.py", line 1332, in <module> _C._initExtension(manager_path()) File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/cuda/__init__.py", line 244, in <module> _lazy_call(_check_capability) File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/cuda/__init__.py", line 241, in _lazy_call _queued_calls.append((callable, traceback.format_stack()))
`

**Comment by guchenhe** [comment]
Closed due to #1542.

**Comment by andylzming** [comment]
问题已经解决，xinference 升级到 0.7.3.1 版本可以正常使用。
