### ISSUE TITLE
Unable to connect to xinference

### ISSUE THREAD

**Issue by gubinjie** [langgenius/dify#1836]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![6de31b162e4e837e08b74ea25adb1fd4](https://github.com/langgenius/dify/assets/37869445/bfebbb7a-1027-41a0-a057-586ba730f9ba)
![09b09a3372121ecceb68d220196be4f2](https://github.com/langgenius/dify/assets/37869445/756179d8-2cfd-42ac-9b39-836be401e5ea)
![832d8db78c44b4d1a88673d77f72a18c](https://github.com/langgenius/dify/assets/37869445/bd7cfd43-d090-4038-86f8-3e494a4b8291)

### ✔️ Expected Behavior

In theory, differentiate should be able to connect to xinference, but it shows that the connection is refused.

### ❌ Actual Behavior

In theory, differentiate should be able to connect to xinference, but it shows that the connection is refused. I am not sure whether the path is wrong.

**Comment by crazywoola** [comment]
You should use machine ip instead of 127.0.0.1.

See this docs for details https://docs.dify.ai/v/zh-hans/guides/model-configuration/xinference 

Especially this one.
 > 当您使用 Docker 在本地部署一个私有模型时，您可能需要通过容器的 IP 地址而不是 127.0.0.1 来访问该服务。这是因为 127.0.0.1 或 localhost 默认指向您的主机系统，而不是 Docker 容器的内部网络。
