### ISSUE TITLE
使用xinference接入模型时报错

### ISSUE THREAD

**Issue by weipeng008005** [langgenius/dify#1837]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![微信图片_20231225162445](https://github.com/langgenius/dify/assets/67491226/97e98e8b-cd47-4d05-8fa5-60923b006910)
I have already deployed the model on xinference, but encountered an error when connecting to the locally deployed dify through Docker：
HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/models/dc8806e0-a2d5-11ee-a945-af9ec0ae1fcf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1e5750760>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by gubinjie** [comment]
I also have this abnormality, exactly the same

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542. Also it's duplicate quesion.

**Comment by crazywoola** [comment]
See #1836
