### ISSUE TITLE
Support file upload of document types in the chat window, similar to the capability of ChatPDF.

### ISSUE THREAD

**Issue by shelltea** [langgenius/dify#1842]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Support uploading document-type files in conversations and engage in interactive discussions around the content of the file.

### Scenario when this would be used?

In addition to uploading files as a knowledge base through the backend, sometimes it is necessary to temporarily upload a file for conversation. Users who use this feature may generally not have permission to upload files in the backend.

**Comment by VincePotato** [comment]
Good suggestion, we'll consider adding that feature.

**Comment by hponiang** [comment]
Suggest designing the functionality to be more flexible, allowing users to receive the upload address after uploading. This address can then be used as a parameter to call custom tools in subsequent operations.

**Comment by Yefori-Go** [comment]
Sorry to bother, just wanted to inquire about the current progress of this feature. I noticed that the "[files-uploader](https://github.com/langgenius/dify/tree/feat/files-uploader)" branch has not been updated for nine months. Is this feature still under development? If I want to implement this feature, where should I start?
@VincePotato

**Comment by tahitimoon** [comment]
请问现在这个问题解决了吗？现在还是只能上传图片
