### ISSUE TITLE
Chat models deployed on Xinference are recognized as Complete models

### ISSUE THREAD

**Issue by blackDZS** [langgenius/dify#1846]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

chatglm3 in xinference as a chat model:
![截屏2023-12-26 21 19 14](https://github.com/langgenius/dify/assets/38283850/bdd31b2e-b567-43cc-852e-afbc1e07cc1a)
and can be used normally: 
![截屏2023-12-26 21 20 43](https://github.com/langgenius/dify/assets/38283850/b864746c-605e-4e38-bbd1-26f1f5bd3e81)
but be recognized as Complete models in Dify:
![截屏2023-12-26 21 26 03](https://github.com/langgenius/dify/assets/38283850/ff79446b-91d5-46a9-9eba-a09441ac783a)

### ✔️ Expected Behavior

Categorized as Chat Model

### ❌ Actual Behavior

Categorized as Complete Model

**Comment by Yeuoly** [comment]
Already supported in v4.0.0

**Comment by takatost** [comment]
Chat mode models supported in v0.4.x, you can try upgrading to the latest version. 😊
