### ISSUE TITLE
QA分段的格式应该是什么样的？

### ISSUE THREAD

**Issue by itltf512116** [langgenius/dify#1847]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

按照template.csv格式产生文档后，提交分段时选择QA格式，产生的分段数都是0，这个是因为格式问题吗？正确的格式应该是什么样的？

### ✔️ Expected Behavior

产生正确的分段数

### ❌ Actual Behavior

产生的分段数一直是0

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
