### ISSUE TITLE
Local embedding service (provided by Xinference) already configured as default, though when indexing docs it still connects to OpenAI

### ISSUE THREAD

**Issue by xraywu** [langgenius/dify#1849]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Set up an Xinference embedding model as default embedding service
2. Upload a document for indexing
3. The indexing process times out and an error of '错误 HTTPSConnection Pool(host='openaipublic.blob.core.windows.net', port=443): Max retriesexceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f84e4c34730>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
' is displayed

![image](https://github.com/langgenius/dify/assets/2353828/75223d09-587c-4562-8a58-5a7b88788138)
![image](https://github.com/langgenius/dify/assets/2353828/fde2aea2-3646-4842-84ce-1ad204a2400c)
![image](https://github.com/langgenius/dify/assets/2353828/8826e097-9d0e-463f-b89a-bea6f0a72732)

 

### ✔️ Expected Behavior

It connects to local embedding service and the document can be indexed properly

### ❌ Actual Behavior

It connects to OpenAI endpoint and caused a timeout

**Comment by xraywu** [comment]
btw. I've checked this  pr e55dd13 but adding environmental variable does not seem to help

**Comment by sisuad** [comment]
I had the same promble. cause you chatbot already chose openai . You can change openai in you chatbox settings 

Seems v0.4.1 already fixed this problem but I can't ensure it cause I have another error

**Comment by xraywu** [comment]
> I had the same promble. cause you chatbot already chose openai . You can change openai in you chatbox settings
> 
> Seems v0.4.1 already fixed this problem but I can't ensure it cause I have another error

Not the same issue. Check #1876 , this issue should be resolved in next release

**Comment by takatost** [comment]
fixed in version 0.4.2
