### ISSUE TITLE
如何优化接口返回时间呢？ 请求一个7 8s 不太正常吧？

### ISSUE THREAD

**Issue by skykiah** [langgenius/dify#185]
如何优化接口返回时间呢？ 请求一个7 8s 不太正常吧？

**Comment by iamjoel** [comment]
具体是哪个接口呢？

**Comment by skykiah** [comment]
> 具体是哪个接口呢？

chat-messages

**Comment by skykiah** [comment]
2核 4G 压测 50就挂了。。请问如何优化

**Comment by takatost** [comment]
This interface is a long connection, which depends on the service capability of the LLM provider on one hand and the connection pool and gunicorn worker on the other. It hasn't been optimized yet, so it's just relying on horizontal scalability. I suggest you start from these aspects.

**Comment by takatost** [comment]
This interface is a long connection, which depends on the service capability of the LLM provider on one hand and the connection pool and gunicorn worker on the other. It hasn't been optimized yet, so it's just relying on horizontal scalability. I suggest you start from these aspects.
