### ISSUE TITLE
The number of segments generated(QA format) is 0

### ISSUE THREAD

**Issue by itltf512116** [langgenius/dify#1850]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After generating a document in template.csv format, and selecting the QA format when submitting the segments, the number of segments generated is 0. Is this because of formatting issues? What should be the correct format?

### ✔️ Expected Behavior

Correctly parses document content

### ❌ Actual Behavior

The number of segments generated is 0

**Comment by crazywoola** [comment]
Have you finished the whole process, can to make a screenshot of the datasets in this document?

**Comment by itltf512116** [comment]
@crazywoola  Thanks for your reply,the screenshot files is:
![14035](https://github.com/langgenius/dify/assets/3404388/e6b778d0-a3e7-4863-80a7-910efda05740)
![2046](https://github.com/langgenius/dify/assets/3404388/278314ff-7ffc-42af-bd70-4d8b1de7d50d)
[template.csv](https://github.com/langgenius/dify/files/13790517/template.csv)


> Have you finished the whole process, can to make a screenshot of the datasets in this document?

**Comment by crazywoola** [comment]
For example template.txt

> Q: question 1 A: answer 1
 Q: question 2 A: answer 2
 
 Since the document is already in Q&A format, you can turn off the Q&A switch. And use the format above.

**Comment by itltf512116** [comment]
> For example template.txt
> 
> > Q: question 1 A: answer 1
> > Q: question 2 A: answer 2
> 
> Since the document is already in Q&A format, you can turn off the Q&A switch. And use the format above. Also, you can use custom splitter`\n`.

Hi @crazywoola ,I've reorganized the contents of the file according to your formatting，
[knowledge.txt](https://github.com/langgenius/dify/files/13806581/knowledge.txt)
The screenshot is as follows：
![image](https://github.com/langgenius/dify/assets/3404388/f101ca8c-7a20-4406-b46c-777d75ca23e3)

The number of segments is now correct, but the format of the segment content doesn't seem to be in QA format:
![image](https://github.com/langgenius/dify/assets/3404388/dcc074bf-b722-44b1-a7ca-d529c154f508)

**Comment by JohnJyong** [comment]
QA format is to generate new questions based on your document segments.
