### ISSUE TITLE
Can the API be compatible with some native parameters?

### ISSUE THREAD

**Issue by Selenium39** [langgenius/dify#1862]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Can the API be compatible with some native parameters, such as I want to use 'response_format: json'? I think this parameter is quite important.

### Scenario when this would be used?

When I make an API call and expect the response to be in a strict JSON format

**Comment by takatost** [comment]
supported in version 0.4.x
