### ISSUE TITLE
A word of warning about tokenizers and An error regarding the local knowledge base

### ISSUE THREAD

**Issue by peizhaoH** [langgenius/dify#1880]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

### ✔️ Expected Behavior

Quick response in hit-testing of knowledge base

### ❌ Actual Behavior

![0bf5d5b3ffde9f46b607156907c1cda](https://github.com/langgenius/dify/assets/152850690/da2db60e-6c3c-4a90-ae7c-d6ea54ab925d) at the same time,hit-testing requests often time out without a recall result.

**Comment by crazywoola** [comment]
Please upgrade to use our latest version v0.4.1
