### ISSUE TITLE
The conversation name automatically changes from Chinese to English after refreshing.

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#1881]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34 and 0.4.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The language type is Simplified Chinese, and on the preview page of the conversational application, the conversation name automatically changes from Chinese to English after refreshing.

![123](https://github.com/langgenius/dify/assets/21255047/2da3a232-3c6c-4b2f-922a-0e25044749a7)

**Comment by crazywoola** [comment]
This 'New conversation' was generated in English mode, so it will be the original title. But after you switch to the Chinese mode, the '新的对话' is a placeholder string instead of a real conversation name.

**Comment by andylzming** [comment]
> This 'New conversation' was generated in English mode, so it will be the original title. But after you switch to the Chinese mode, the '新的对话' is a placeholder string instead of a real conversation name. Also the conversation name is auto generated from LLMs, anyway, you can rename this conversation anytime you want.

When I start a new conversation, it should be in Chinese, but after refreshing the page, it changes to English.
