### ISSUE TITLE
[1214] 参数非法，请检查文档

### ISSUE THREAD

**Issue by jellchou** [langgenius/dify#1882]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Setup the dialog application
2. select chatglm-turbo as chat llm.
3. chat with the bot.
<img width="384" alt="微信图片_20240103161848" src="https://github.com/langgenius/dify/assets/4926400/13ad47c7-4694-406e-98ba-ba589024d962">

### ✔️ Expected Behavior

Get response correctly.

### ❌ Actual Behavior

Nothing responesd and noticed that "[1214], [history参数非法，请检查文档]"

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
