### ISSUE TITLE
api调用比系统内调用速度慢

### ISSUE THREAD

**Issue by zhangchaolunha** [langgenius/dify#1889]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.0

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/63902798/73e6021b-83c7-4764-93b4-6d5092356d81)
![image](https://github.com/langgenius/dify/assets/63902798/8f384e70-ea58-40b0-affe-ae33fe365096)
同样的内容请求，console/api/apps/{appId} 会比v1/chat-messages快很多。目前不清楚原因，导致通过api请求平均时常过长

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by molinzhifeng** [comment]
Yes, I also had this problem, is it solved now?
