### ISSUE TITLE
Can't chat with chatglm-turbo

### ISSUE THREAD

**Issue by jellchou** [langgenius/dify#1891]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Setup the dialog application
2. select chatglm-turbo as chat llm.
3. chat with the bot.
<img width="384" alt="微信图片_20240103161848" src="https://github.com/langgenius/dify/assets/4926400/e9c9bf9a-9a40-4b72-a52c-ff73ac4767f1">

### ✔️ Expected Behavior

Response rightly.

### ❌ Actual Behavior

Nothing responesd and noticed that "[1214], [history参数非法，请检查文档]"

**Comment by crazywoola** [comment]
Can you try to remove the key and add it again?

**Comment by takatost** [comment]
fixed in version 0.4.2

**Comment by jellchou** [comment]
> fixed in version 0.4.2

0.4.2 version still noticed the same error

**Comment by jellchou** [comment]
it’s ok.
