### ISSUE TITLE
文本生成型应用 API，创建文本补全消息接口

### ISSUE THREAD

**Issue by easongfan** [langgenius/dify#1916]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

使用文本生成型应用 API
调用创建文本补全消息接口的时候，response_mode如果使用streaming 正常，但是使用blocking 阻塞型则会出现completion_request_error错误，之前版本都不会有这样的情况。
模型使用gpt-4-32k，其他模型比如百川不会有这样的情况
![23a20b651b7a3b4917088fda66102ed](https://github.com/langgenius/dify/assets/4918455/0d957f34-6e38-4520-9e1d-fcce96314e69)

调用接口报错信息：
![bd0ab81a96ba40150cba3d2ddf41348](https://github.com/langgenius/dify/assets/4918455/894e5bd1-4759-473e-874d-42fa7228b2a2)

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
