### ISSUE TITLE
Adopt Q&A segmentation mode, segmentation use option: simplified Chinese, or a large number of English segments will be generated.

### ISSUE THREAD

**Issue by supersnoopy** [langgenius/dify#1918]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

 0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Adopt Q&A segmentation mode, segmentation use option: simplified Chinese, or a large number of English segments will be generated.
![q1](https://github.com/langgenius/dify/assets/28731297/91dc1517-b9a8-48f2-88af-1aae2b125db3)
![q2](https://github.com/langgenius/dify/assets/28731297/01ea6eb0-bc90-4794-b9ef-e6d64adba488)

### ✔️ Expected Behavior

It can fix the problem of generating partitions in simplified Chinese.

**Comment by JohnJyong** [comment]
May I ask what model you are using? The quality of generated questions depends on the capabilities of the LLM model.

**Comment by supersnoopy** [comment]
The model I use is from azure openai.﻿
May I ask what model you are using? The quality of generated questions depends on the capabilities of the LLM model.

**Comment by JohnJyong** [comment]
I tested through openai gpt3.5, it works fine.
Anyway , I have emphasized the use of language above the prompt ， you can checkout the latest code to have a try . 
Any other problems , pls attach your testing files,  it will be easier for us to do some checks， thanks
