### ISSUE TITLE
Google登录提示404

### ISSUE THREAD

**Issue by saifeiLee** [langgenius/dify#193]
你好。
我在尝试本地运行dify, 并贡献代码。我已在Google Cloud 配置了OAuth ClientID和Secret ID。我的本地host改为 127.0.0.1 ->	dify.cvte.cn。当我进行google auth时，得到错误信息：
<img width="820" alt="image" src="https://github.com/langgenius/dify/assets/28710808/9d5636a3-6b90-4547-ab33-027d04a781a1">
服务端日志显示：
<img width="1341" alt="image" src="https://github.com/langgenius/dify/assets/28710808/5b060ec0-5b25-4286-9314-eb701bcbfc29">
请问我该如何分析该问题呢？
非常感谢帮助～❤️

**Comment by takatost** [comment]
要使用 CLOUD 的功能的话建议前后端同域哦，可以在前面配置一个 Nginx
