### ISSUE TITLE
Dify Xinference Integration Issue

### ISSUE THREAD

**Issue by Eng-AliKazemi** [langgenius/dify#1932]
![dify issue](https://github.com/langgenius/dify/assets/98425433/32221005-545d-435a-9907-54198e525b9e)
![xinference](https://github.com/langgenius/dify/assets/98425433/54053944-4d83-4969-9885-d80aaab6450b)
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Dify and Xinference are both running and working separately, but when I try to connect to Xinference through Dify, I get this error:

`Xinference credentials validate failed: get xinference model extra parameter failed, url: http://127.0.0.1:9997/v1/models/mistral-instruct-v0.2, error: HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/models/mistral-instruct-v0.2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb76ddeeb90>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Any help will be appreciated.

**Comment by crazywoola** [comment]
Please upgrade to 0.4.3, we have fixed this in latest releases.
