### ISSUE TITLE
External data tool not work

### ISSUE THREAD

**Issue by opsvr** [langgenius/dify#1934]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Adding external_data_tool to the API extension allows you to see the ping request. Adding external_data_tool works normally, but when you create an application and add a tool to it, the tool interface is not called.
1、API External add api；
2、create app；
3、add tools，set ver in prompt；
4、deploy；
5、test；

### ❌ Actual Behavior

Adding external_data_tool to the API extension allows you to see the ping request. Adding external_data_tool works normally, but when you create an application and add a tool to it, the tool interface is not called.

**Comment by crazywoola** [comment]
Can you paste the log you sent to the LLM? It's in the log&anno, you can hover the message to view the logs.

**Comment by opsvr** [comment]
I know what the problem is. I created a text generation application, and selecting the dialog type can call the API normally. Why doesn't the text generation application support calling the API? Is it a bug?
@crazywoola

**Comment by crazywoola** [comment]
Yes, we are working on this.

**Comment by GarfieldDai** [comment]
@opsvr #1942 Fixed.
