### ISSUE TITLE
chat model no self add models in settings

### ISSUE THREAD

**Issue by jaffe-fly** [langgenius/dify#1936]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/49515380/587c1b9b-2baf-4b7c-a4b6-5297ac622b94)
![image](https://github.com/langgenius/dify/assets/49515380/9c06a980-4314-4d63-9f8a-c4d676a6084b)
The model interface for self-deployment has been added to the settings. Do you need to add another one in Smart Chat?

**Comment by crazywoola** [comment]
Chat in explore only supports models listed in the page. It does not support the chatglm.

**Comment by jaffe-fly** [comment]
> Chat in explore only supports models listed in the page. It does not support the chatglm.

use xinference  deploy chatglm3,so the API URL is http://xxxxx:9997 or below
![image](https://github.com/langgenius/dify/assets/49515380/a1369bfd-12d6-4550-a772-c673fdeffc62)
