### ISSUE TITLE
Dify with OpenAI custom model is not working

### ISSUE THREAD

**Issue by santiagoblanco22** [langgenius/dify#1938]
f### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Fine tune a gpt-3 model in openAI and wait
2. Go to dify model provider and config openAI model
![Captura de pantalla 2024-01-04 a la(s) 11 30 39 p m](https://github.com/langgenius/dify/assets/109559178/03c8045f-c33a-4b1e-8088-1094cac561d4)
3. Then testing the chat doesn't answer well and with the openAI API with curl works well.

### ✔️ Expected Behavior

a large response. Not only 1 character.

### ❌ Actual Behavior

Only says rare words and only says words in completion mode.

**Comment by takatost** [comment]
<img width="1024" alt="image" src="https://github.com/langgenius/dify/assets/5485478/088f3580-0332-4e22-ac9e-5879d0ba880b">
If you want to add the OpenAI fine-tuned model, you can simply add the model in the OpenAI provider. The model name should be "fine tune model name" and you need to configure the corresponding credentials. This will ensure better compatibility.

**Comment by takatost** [comment]
#1944 fixed

**Comment by santiagoblanco22** [comment]
thanks a lot!!
