### ISSUE TITLE
Version Upgrade Command Help

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#1939]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm in the docker directory
I executed the
docker-compose down
docker-compose pull
docker-compose up
Why is the version not upgraded successfully?
It's Still stuck at 0.4.2, not upgraded to 0.4.3
Is there any other pre-setup work?

**Comment by crazywoola** [comment]
Please use the right issue template for getting help.
