### ISSUE TITLE
禁用/启用分段不成功

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1946]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

如果分段的状态不是completed，进行分段的禁用/启用操作没有效果。原因是在下面代码中有判断是否completed。
enable_segment_to_index_task.py
disable_segment_to_index_task.py
<img width="374" alt="image" src="https://github.com/langgenius/dify/assets/1925650/7a64f35e-7506-472e-bdad-7e5060ad2fd2">
表中分段状态：
<img width="668" alt="image" src="https://github.com/langgenius/dify/assets/1925650/79df2ded-a95a-479c-9c00-b15cc8d2829a">

### ✔️ Expected Behavior

修改这个判断，否则都无法进行分段的禁用/启用操作。但是web页面上却是成功的提示。

### ❌ Actual Behavior

无法进行分段的禁用/启用操作

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
