### ISSUE TITLE
Unsuccessful disabling/enabling segmentation

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#1949]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.33

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

If the status of the segment is not completed, disabling/enabling the segment has no effect. The reason is that in the code below, there is a judgment whether it is completed.
enable_segment_to_index_task.py
disable_segment_to_index_task.py
![image](https://github.com/langgenius/dify/assets/1925650/5758c1dd-3c0e-4fa9-89ef-0bb66a33b622)

Segmentation status in the database:
![image](https://github.com/langgenius/dify/assets/1925650/04084885-54a1-47f7-8baa-4cc51b2ceda4)

### ✔️ Expected Behavior

Modify this judgment, otherwise segmented disabling/enabling operations will not be possible. But there is a successful prompt on the web page.

### ❌ Actual Behavior

Unable to disable/enable segmentation

**Comment by JohnJyong** [comment]
uncompleted segment will not  be allowed enable and disable function.
PR link : https://github.com/langgenius/dify/pull/1954

**Comment by wangrg** [comment]
However, the front desk prompts the enabled status, but it is not available in implementation, and the hit test fails. It will be misleading.

**Comment by wangrg** [comment]
The real situation is that the embedding failed and the status changed to 'error'. Is it not allowed to operate again?

**Comment by JohnJyong** [comment]
if the segment is in error status, the disable/enable button will be disabled.

**Comment by wangrg** [comment]
If it is caused by embedding failure, after this process, embedding cannot be enabled again. Can the segment be deleted and re-created?

**Comment by wangrg** [comment]
Can be changed to judgment: status in ['waiting','updating','indexing','re_segment']

**Comment by JohnJyong** [comment]
We will consider adding a method of re-embedding error segments, thank you for your suggestion
