### ISSUE TITLE
Access address after docker compose

### ISSUE THREAD

**Issue by xietao105** [langgenius/dify#1950]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Currently used to access through http://localhost, can you use http://locahost/gpt to access through configuration

### Scenario when this would be used?

The current domain name is already in use, and I want to sink one level to access dify.

**Comment by takatost** [comment]
Currently, it is not supported. You can try configuring rewrite rules in an external reverse proxy to see if it works.

**Comment by xietao105** [comment]
来信收到。谢谢。。辛苦了

**Comment by linronghua921122** [comment]
I also encountered the same problem. Have you solved it.can you use http://locahost/gpt to access through configuration?
