### ISSUE TITLE
add model failed !!

### ISSUE THREAD

**Issue by chobits4** [langgenius/dify#1958]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

network request：api/workspaces/current/model-providers/openai

get error when add model：

![image](https://github.com/langgenius/dify/assets/33352251/51c08a48-565f-483d-a8d7-39e640585c62)

### ✔️ Expected Behavior

add model success

**Comment by crazywoola** [comment]
I guess you have input something like `127.0.0.1`?
