### ISSUE TITLE
qwen response content repeat ,can not config parmas like stream or incremental_output

### ISSUE THREAD

**Issue by xkkjiayou** [langgenius/dify#1960]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/38376865/701cd2c8-cee8-488b-ba83-2ce43966abfc)

look at the qwen response,

**Comment by JohnJyong** [comment]
Could you try the lastest version 0.4.3?

**Comment by xkkjiayou** [comment]
> Could you try the lastest version 0.4.3?

i tried 0.4.3 and 0.4.4, but the bug also exists ,when uese qwen.

i find a parameters in qwen docs(offical) maybe can fix this bug, the parameter is  "incremental_output",but in dify there is no place to set this parameter.
![image](https://github.com/langgenius/dify/assets/38376865/eeb9748c-f332-41dc-89b9-417cc4ed1356)

**Comment by xkkjiayou** [comment]
> Could you try the lastest version 0.4.3?

https://help.aliyun.com/zh/dashscope/developer-reference/api-details?spm=a2c4g.11186623.0.0.795864d12wmVw8

**Comment by xkkjiayou** [comment]
> Could you try the lastest version 0.4.3?

thank u for your reply.
