### ISSUE TITLE
Support function list with parameters , like openai document.

### ISSUE THREAD

**Issue by jingyuan2017** [langgenius/dify#1964]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Hi , can we set the function or a function list when edit the api-tools endpoint? 

And the function has it's pre-setting parameters , no need to write in the propmt .

https://platform.openai.com/docs/assistants/tools/function-calling

### Scenario when this would be used?

Sometimes an agent have some skill(functions) , we don't know which need be used , we just send the user message with functions declare , untill chatgpt return a function call. 

The  parameter values also automatically determined by chatgpt , not rely to the user's input in textbox.

This is a flexible and powerful method. Is there any way to support it? Are there any related plans?

Thx!

### Supporting information

https://platform.openai.com/docs/assistants/tools/function-calling

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/issues/1971
