### ISSUE TITLE
Does the API extension tool support extracting parameters from the conversation? For example, when querying the weather, does it support extracting the location city from the conversation?

### ISSUE THREAD

**Issue by dgo2dance** [langgenius/dify#1971]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

Does the API extension tool support extracting parameters from the conversation? For example, when querying the weather, does it support extracting the location city from the conversation?

**Comment by crazywoola** [comment]
Nope, it has to be pre-defined for now. We will support this feature in next few releases.

**Comment by joyjoyyo** [comment]
nice idea

**Comment by lujin1** [comment]
expect.

**Comment by lzk90s** [comment]
+1

**Comment by vontainment** [comment]
For what I saw the API extensions send all the variables and the query. So technically you should be able to extract on the endpoint side

**Comment by crazywoola** [comment]
We will release v0.5.0 today, it will support this one.
