### ISSUE TITLE
Provider  None does not exist.

### ISSUE THREAD

**Issue by newsouther** [langgenius/dify#1980]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.4

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Create an empty dataset and import the file

### ✔️ Expected Behavior

import success

### ❌ Actual Behavior

Provider  None does not exist.

**Comment by crazywoola** [comment]
You need to configure the embedding model first.
