### ISSUE TITLE
通过智谱AI的api-key接入智谱AI模型后，使用智谱AI的text_embedding报错

### ISSUE THREAD

**Issue by guyfar** [langgenius/dify#1982]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

在创建知识库导入文档时，使用智谱的text_embedding直接报错，报错如图所示：
![WechatIMG499](https://github.com/langgenius/dify/assets/3032483/1c022fc2-0d60-470c-9692-12f568d64a66)

### ✔️ Expected Behavior

我猜测应该是智谱的text_embedding.py中，not us ZhipuAiTokenizer to get num tokens 导致的，如下图所示
<img width="948" alt="SCR-20240110-keld" src="https://github.com/langgenius/dify/assets/3032483/c85ac77b-6f28-45f6-b508-aa76c7c8f510">

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
