### ISSUE TITLE
Encountered an error while using ZhipuAI's text-embedding model in Dify.

### ISSUE THREAD

**Issue by guyfar** [langgenius/dify#1984]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The error message when using ZhipuAi's text-embedding model is shown in the following image.

![WechatIMG499](https://github.com/langgenius/dify/assets/3032483/96b204f2-4940-4202-9f92-c831d0edfdd5)

### ✔️ Expected Behavior

I suspect it's caused by not using ZhipuAiTokenizer to get the number of tokens in the text_embedding.py of ZhipuAi, as shown in the following image.

<img width="948" alt="SCR-20240110-keld" src="https://github.com/langgenius/dify/assets/3032483/85600393-d57a-4723-92ac-e5f3cd58899c">

**Comment by jinghao2eebd** [comment]
same problem

**Comment by crazywoola** [comment]
We fixed this yesterday in this https://github.com/langgenius/dify/pull/1976/files
It will be released in v0.4.5
