### ISSUE TITLE
When using other applications, a word is generated and a word is returned, and the loading process is a little better. When our products are used in smart chat, all products are generated and then returned, so the experience is not as good as the native GPT. In addition, the answer does not support drawing the table and hopes to optimize it.

### ISSUE THREAD

**Issue by zicator** [langgenius/dify#1992]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.28

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

如描述

### ✔️ Expected Behavior

如描述

**Comment by Yeuoly** [comment]
It will support streaming output soon, and the smart chat will be converted into an agent assistant app in few days, you can look forward to it. 😊

**Comment by Yeuoly** [comment]
Resolved. #2086
