### ISSUE TITLE
The reasoning results are derived from the knowledge base. Can the sources of the results be listed?

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#1995]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The reasoning results are derived from the knowledge base. Can the sources of the results be listed?

like this

![123](https://github.com/langgenius/dify/assets/21255047/a29b0078-503f-4fcd-a817-8f9c23b9ffef)

**Comment by stevezhanggeek** [comment]
In your app, please click "Add Feature" and enable "Citations and Attributions"

**Comment by andylzming** [comment]
@Yeuoly Is there a schedule for this requirement?

**Comment by Yeuoly** [comment]
This feature will be released in the next version afters few days.

**Comment by andylzming** [comment]
Could you please explain why this issue was closed? Has this feature been implemented? @crazywoola @Yeuoly
