### ISSUE TITLE
cannot generate knowledge base cause error

### ISSUE THREAD

**Issue by zmingchun** [langgenius/dify#1999]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/1988270/ef46f320-3aeb-46ca-b1d7-200122d1641f)
![image](https://github.com/langgenius/dify/assets/1988270/ab9f5747-929a-46d7-8f30-52507cdcd3df)

### ❌ Actual Behavior

Rate Limit Error: Request too frequent, please try again later

**Comment by zmingchun** [comment]
have not retry entrance

**Comment by zmingchun** [comment]
Not yet

**Comment by takatost** [comment]
> Not yet

If there are large number of chunks, it's indeed easy to exceed the rate-limit of cohere. I suggest applying for a production-level cohere key to perform the operations.

**Comment by JohnJyong** [comment]
pls check your apikey, if you have any other questions, please contact us，thanks

**Comment by zmingchun** [comment]
My baichuan apikey is paid.
