### ISSUE TITLE
API Get Message not returning any result

### ISSUE THREAD

**Issue by ganeshbehera** [langgenius/dify#2002]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I trying to Get Messages by User, I am returning any message even though there is data, Here is the output I get

### ✔️ Expected Behavior

It should have returned this {
  "has_more": false,
  "data": [
    {
      "id": "WAz8eIbvDR60rouK",
      "conversation_id": "xgQQXg3hrtjh7AvZ",
      "inputs": {},
      "query": "...",
      "answer": "...",
      "feedback": "like",
      "created_at": 692233200
    },
    {
      "id": "hSIhXBhNe8X1d8Et"
      // ...
    }
  ]
}

### ❌ Actual Behavior

{
    "limit": 20,
    "has_more": false,
    "data": []
}

**Comment by crazywoola** [comment]
Can you paste the command you sent to the server without your api key included?
As far as I can tell, it seems that the conversation does not have a user right?

**Comment by ganeshbehera** [comment]
This was the command

curl --location --request GET 'https://yourdomain.com/v1/messages?user=16505551111&conversation_id='\
 --header 'Authorization: Bearer ENTER-YOUR-SECRET-KEY'

**Comment by crazywoola** [comment]
But I did not see the conversation id in the cmd.

**Comment by takatost** [comment]
> This was the command
> 
> curl --location --request GET '[https://yourdomain.com/v1/messages?user=16505551111&conversation_id='\](https://yourdomain.com/v1/messages?user=16505551111&conversation_id='%5C) --header 'Authorization: Bearer ENTER-YOUR-SECRET-KEY'

This route for the API is incorrect, it should be `/chat-messages` or `/completion-messages` instead.
