### ISSUE TITLE
No dark mode yet?

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2015]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

i couldnt find any dark mode and if i use dark reader in firefox it messup and make some frontend elements sometime transparent with dark bg idk for the first time its happening so if possible can you please add dark mode and save everyone precious eyes.
Thankyou

### Scenario when this would be used?

everytime

**Comment by HakaishinShwet** [comment]
not satisfied with bot response

**Comment by crazywoola** [comment]
> not satisfied with bot response

Sorry for this response, but this feature is still on our roadmap.

**Comment by takatost** [comment]
I love dark mode too.

**Comment by charli117** [comment]
Me like too [机智] @crazywoola

**Comment by HakaishinShwet** [comment]
@crazywoola no need for sorry devs you all are awesome i just wanted to see if bot reply back something to me or not haha . We all love dark mode alot and hope to see it in this awesome application as soon as possible till then dark reader + midnight lizard together are working great or alone midnight lizard addon/extension to support dark mode temporarily on this apps frontend till it gets native support :-))

**Comment by HenkDz** [comment]
Still no dark mode yet?

**Comment by psi4j** [comment]
Yes, dark mode is a necessity. Not everybody here enjoys a glaring white screen. This literally hurts people's eyes and wastes battery life on their laptops. Shouldn't that be a choice?

**Comment by joeBlockchain** [comment]
dark mode bump - cannot use light mode my eyes are burning

**Comment by cidiousx** [comment]
please.. it's 2024.. dark mode is really a must for most of us and should indeed be a choice as mentioned above.

**Comment by dineshbabu179** [comment]
+1

**Comment by VincePotato** [comment]
Dark mode development is in progress, though moving slowly😄. 

Dify is rapidly iterating, and new front-end pages are being developed based on the updated design guidelines. We'll fully switch over once the overall functionality stabilizes, maybe after dify v1.0.  

In any case, this work has not been forgotten.

**Comment by HeMuling** [comment]
+1

**Comment by longsfreedom** [comment]
+1

**Comment by Midasstart** [comment]
+1

**Comment by victorl1m** [comment]
+1

**Comment by huliangbing** [comment]
+1

**Comment by sienkus** [comment]
+1

**Comment by VincePotato** [comment]
Hey guys. It's already in testing now. I think it will be coming soon.

**Comment by AlgorithmicKing** [comment]
> Hey guys. It's already in testing now. I think it will be coming soon.

its been a month has it been released?

**Comment by cidiousx** [comment]
> > Hey guys. It's already in testing now. I think it will be coming soon.
> 
> its been a month has it been released?

I don't think they care at all. Official 1.0.0 has now been released and still no darkmode. They care about implementing all sorts of LLM suppliers mostly it seems. I guess those are what make money, I bet in the form of sponsorship but I'm just speculating. Our eye health doesn't matter much to the dev team that's for sure.
