### ISSUE TITLE
is there no control over content generation section in google gemini like settings to moderate the result according to our needs

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2016]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

As google gemini also have control over content generation options like we can control how much moderation we need while generating content so is there no option to change those 4 values of moderation from interface yet? because i couldnt find except able to change temperature and other minimal values so was asking :-) and if there is none then please add it devs to give more freedom of content generation else google censored nature will block alot of things and will make hard to use
Thanks for the hardwork

**Comment by guchenhe** [comment]
Gemini's block setting is already set to `BLOCK_NONE ` for maximal freedom :) We've noticed that Gemini's filtering interferes with normal usage as well, so likely not going to make it configurable at this point.

**Comment by tealeeseng** [comment]
Hi, vertex AI responsed with "Bad Request Error, 400 User has requested a restricted HarmBlockThreshold setting BLOCK_NONE."

Going into API docker instance and change BLOCK_NONE to BLOCK_MEDIUM_AND_ABOVE resolves the issue. Need to docker compose restart API instance though.
