### ISSUE TITLE
Please support Ollama Local Embeddings and in system chat (top-level chat)

### ISSUE THREAD

**Issue by victorwon** [langgenius/dify#2018]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

It's great to have ollama support since 0.4.6, but it doesn't seem to show up in the embedding model. Is there any way to do it?

Also, the ollama model doesn't show up in the system chat model selection either.

### Scenario when this would be used?

Make all dify features working offline.

**Comment by victorwon** [comment]
I figured the embedding part as it's just needed to create another instance of ollama as text-embedding provider.

However, in order to get ollama work in the system chat, do I have to create a model with ft: prefix? Or can I just use any model to rename it? Not very clear as I couldn't find any doc related.

**Comment by crazywoola** [comment]
@guchenhe @takatost

**Comment by takatost** [comment]
<img width="771" alt="image" src="https://github.com/langgenius/dify/assets/5485478/1efd4c1f-0308-40d8-8e7f-22eb0114895b">
<img width="683" alt="image" src="https://github.com/langgenius/dify/assets/5485478/dda2e8f9-3506-4805-a6f0-a0a8b6189b88">
<img width="370" alt="image" src="https://github.com/langgenius/dify/assets/5485478/f19aae8f-d80f-46e1-87b8-793e700196cc">
I tested it and there is no problem. Could you please check if there is any missing configuration according to the instructions in the screenshot? Thank you very much.

**Comment by victorwon** [comment]
Thanks @takatost and as I mentioned in the previous comment I figured the embedding part.

The one still not working is that the ollama model is not showing in the list of system default chat providers. It does show on the private apps created.

**Comment by takatost** [comment]
> Thanks @takatost and as I mentioned in the previous comment I figured the embedding part.
> 
> The one still not working is that the ollama model is not showing in the list of system default chat providers. It does show on the private apps created.

<img width="386" alt="image" src="https://github.com/langgenius/dify/assets/5485478/a19fbb91-ed07-49f1-9020-d21e61e3f62f">

Just double-checking, you're looking at the `Embedding Models` list within `System Model Settings`, right?

**Comment by victorwon** [comment]
No, not the embedding and not the system settings. I meant to use the default chat at the left navigation panel that above the custom apps. That chat has a configuration with a list of llm providers to choose from, but the ollama doesn’t appear in that dropdown list.

**Comment by takatost** [comment]
> No, not the embedding and not the system settings. I meant to use the default chat at the left navigation panel that above the custom apps. That chat has a configuration with a list of llm providers to choose from, but the ollama doesn’t appear in that dropdown list.

Oh, I get what you're saying now.
We'll support custom Agent apps within this week, and all LLMs will be available as base models for Agents (results may vary though).

**Comment by takatost** [comment]
Already merged into the main branch, will be released in v0.5.0.
