### ISSUE TITLE
hit-testing always failed with 400

### ISSUE THREAD

**Issue by chobits4** [langgenius/dify#2020]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1616" alt="image" src="https://github.com/langgenius/dify/assets/33352251/eb17d8f1-3b0c-4ec8-9b97-8cac79b08322">

**Comment by crazywoola** [comment]
Do you have access to the rerank model? It seems this can not be reachable to me.
