### ISSUE TITLE
用了Cohere的rerank API，对话没有产生回放

### ISSUE THREAD

**Issue by crybest** [langgenius/dify#2021]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

Claud

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/102134756/e2d04a1c-b610-483f-9cef-88ec68d9aca6)
![image](https://github.com/langgenius/dify/assets/102134756/fc435ffd-fbe7-4e94-a308-291b09bac549)
![image](https://github.com/langgenius/dify/assets/102134756/935de5b8-029c-4a49-bf09-7d79b0752287)

看cohere确实调用了，但是没有回答

### ✔️ Expected Behavior

有结果返回

### ❌ Actual Behavior

没有结果****

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
