### ISSUE TITLE
Failed to modify segment

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#2022]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.34

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

When I edit the segment content and submit it, the status of the segment becomes disabled.
<img width="393" alt="image" src="https://github.com/langgenius/dify/assets/1925650/ba21f647-166e-4f3e-8ca3-a94731103852">

error log：
<img width="383" alt="image" src="https://github.com/langgenius/dify/assets/1925650/2c917de1-8db3-4d9a-8f45-2cdf128476cc">

### ✔️ Expected Behavior

Modification of segment content successful

### ❌ Actual Behavior

Incorrect segment modification

**Comment by crazywoola** [comment]
I think you should upgrade to latest version. Since this version is quite outdated.

**Comment by wangrg** [comment]
There are some missing modifications in the latest version.
<img width="427" alt="截屏2024-01-15 09 43 30" src="https://github.com/langgenius/dify/assets/1925650/00358db4-94c5-444d-804f-ef92d9ac1d44">
