### ISSUE TITLE
Is it possible to add Regenerate the message button in Frontend to regenerate the message of AI

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2023]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

i mean i have used chatgpt and foss frontend program bettergpt web interface and in those we can regenerate the response with simple button click so can you add that same feature in normal chat and bot chats of dify so that we can regenerate the message from ai side to get better response or i should say expected response :-)) will be very helpful for continuous better conversation 
Thankyou

### Scenario when this would be used?

in bot chats and normal chat with ai.

**Comment by VincePotato** [comment]
Thanks! We are working on it.
