### ISSUE TITLE
Why not support by default for scrapingbee,serper.dev,serpstack api's for google searching instead of just giving one option as serp only

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2024]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Atleast devs please add more api support by default for google search, flowise has also given atleast serper.dev option with which we can easily cost effectively search with google as by default serp api is costly as compared to other mentioned options which have some decent free and paid options for google search so please add support atleast for serper.dev api if not the other ones so that we can easily put api key and use google search with that instead of only depending on serp api. I know there are api extension option but tbh i havent understood completely how to use it. i did try my best to get api from mentioned websites and i tried to create end point but was getting some issuesso couldnt understand how to solve it because putting api key is easy but connection with endpoint i couldnt understand and tried to set it up but got some different error codes :-)) so please for now atleast add support for serper.dev and if possible for others too and then make any small video or EASY GUIDE WITH PROPER WORKING COMPLETE EXAMPLE to make other understand how to use it in future to connect with other api services.
Again Thanks for the hardwork and hope to see this request get fulfilled as soon as possible :-)) btw you can take reference from how flowise implemented serper.dev api if you get any issues i have tested there and it worked like a charm but this foss solution truly is awesome and i want it to grow more so will try to contribute for now with ideas.

### Scenario when this would be used?

:-)

**Comment by crazywoola** [comment]
We will have the functions in next few releases. Not only the serp api, but also some other cool stuffs.

**Comment by hamxa0077** [comment]
I’m looking for a way to scrape data using the Serper.dev API,s there an existing integration for this, or would anyone have suggestions on how to achieve this using the Serperdev API?
