### ISSUE TITLE
How to do sft via dify? When will this feature be released?

### ISSUE THREAD

**Issue by realcarlos** [langgenius/dify#2027]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Is this an existing feature?

### Scenario when this would be used?

These annotations will be used for model fine-tuning in future versions of Dify to improve model accuracy and response style. The current preview version only supports annotations.

### Supporting information

These annotations will be used for model fine-tuning in future versions of Dify to improve model accuracy and response style. The current preview version only supports annotations.

**Comment by VincePotato** [comment]
Currently, there is no plan to support fine-tuning features on Dify. We now support export the annotation data from the application production process as JSONL format files for use in fine-tuning data preparation.
