### ISSUE TITLE
向量数据库选qdrant，创建知识库时异常

### ISSUE THREAD

**Issue by wpt1225** [langgenius/dify#2028]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

向量数据库选qdrant，创建知识库时选“高质量”索引时，报如下异常

部署方式：本地源码部署方式

qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Deserialize error in query parameters: invalid digit found in string"},"time":0.0}'

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542, Please use the right template.
