### ISSUE TITLE
Citations and attributions cannot be displayed on WebApp

### ISSUE THREAD

**Issue by huangchukun** [langgenius/dify#2029]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Enable citations and attributions of an app.

### ✔️ Expected Behavior

Citations and attributions can be displayed on webapp.

### ❌ Actual Behavior

Citations and attributions can't be displayed on webapp.
Citations and attributions can be displayed on debug and preview.

**Comment by crazywoola** [comment]
We will add this feature in future releases. We are still discussing it with the PM.
