### ISSUE TITLE
密钥校验失败

### ISSUE THREAD

**Issue by yinghanpeng** [langgenius/dify#203]
![image](https://github.com/langgenius/dify/assets/22876733/d47dc617-a89e-4157-86aa-2cf627e44d43)
![image](https://github.com/langgenius/dify/assets/22876733/09bb4f3f-e4d4-4e50-a3e6-090426201226)
密钥校验失败，服务部署在我的服务器上，可以访问api.openai.com，请问可能是什么原因

**Comment by takatost** [comment]
获取是代理在 docker 容器内没生效
