### ISSUE TITLE
Give MySQL Database Access As Knowledge

### ISSUE THREAD

**Issue by MirzaAreebBaig** [langgenius/dify#2031]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Description of the new feature / enhancement

Connecting MySql database for knowledge for the knowledge of the AI which as of now is only for documents uploading. I have tried giving data in real time using api but this creates another data of mysql which if user wants to delete any record they have to do it in MySql as well as dify database.

### Scenario when this would be used?

This would be a great feature to allow other softwares to integrate seamlessly

**Comment by VincePotato** [comment]
There is no plan to support this feature for now. Sorry for that.

**Comment by golangpkg** [comment]
I found the way to  support  mysql database . because the SQLAlchemy can support both mysql and PG
 database .  I want to commit a  PR .

**Comment by takatost** [comment]
We've been utilizing some features of PgSQL, like UUID, JSONB type fields. Directly replacing MySQL might lead to some hiccups.

**Comment by takatost** [comment]
We're gonna roll out the workflow feature in about a month, You'd be able to expand your toolset on your own, and even hook up with MySQL to get the data you need for context.

**Comment by golangpkg** [comment]
> We're gonna roll out the workflow feature in about a month, You'd be able to expand your toolset on your own, and even hook up with MySQL to get the data you need for context.

and push this PR: 
https://github.com/langgenius/dify/pull/2371/commits/dcb8a04e1f01e5c21875706a8c3678e9b7c7c7ea

use:
 default=lambda: uuid.uuid4() 
support mysql and postgres db.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/2371 Bump
