### ISSUE TITLE
 Qdrant  as vector store does not work

### ISSUE THREAD

**Issue by wpt1225** [langgenius/dify#2032]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I am using version 0.4.6 of dify and merged dify qdrant code. local deployment, not docker.
Qdrant version 1.7.3(local deployment, not Docker)
When I create a knowledge base and select "high quality" indexing，The following exception occurred：

qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Deserialize error in query parameters: invalid digit found in string"},"time":0.0}'

May I ask if there is a solution

**Comment by crazywoola** [comment]
We use https://github.com/langgenius/dify/blob/1fe4e3afde262e51621d4b388dd28c5e8fd91354/api/requirements.txt#L56 this version of qdrant in dify.
Seems we do not support the latest version of qdrant. Ca you try to downgrade the version to see if this is helpful.
We will upgrade this client in the future. @takatost

**Comment by takatost** [comment]
> We use
> 
> https://github.com/langgenius/dify/blob/1fe4e3afde262e51621d4b388dd28c5e8fd91354/api/requirements.txt#L56
> 
> this version of qdrant in dify.
> Seems we do not support the latest version of qdrant. Ca you try to downgrade the version to see if this is helpful.
> We will upgrade this client in the future. @takatost

@JohnJyong pls check it out.

**Comment by JohnJyong** [comment]
pls attach your qdrant setting in your env

**Comment by wpt1225** [comment]
my env setting

# Vector database configuration, support: weaviate, qdrant, milvus
VECTOR_STORE=qdrant
# Qdrant configuration, use `http://localhost:6333` for local mode or `https://your-qdrant-cluster-url.qdrant.io` for remote mode
QDRANT_URL=http://localhost:6333
#QDRANT_API_KEY=difyai123456
QDRANT_CLIENT_TIMEOUT=500

the os is windows

**Comment by wpt1225** [comment]
I try to downgrade the version to 1.6.1 and it work well

**Comment by wpt1225** [comment]
I have downgrade the qdrant version to 1.6.1 and it works well

**Comment by takatost** [comment]
> I have downgrade the qdrant version to 1.6.1 and it works well我已将 qdrant 版本降级到 1.6.1，效果很好

So you mean qdrant-client==1.6.4 is not compatible with qdrant server (v1.7.3), and qdrant server can be downgraded to 1.6.1 and works well, right?
@JohnJyong pls check it out.

**Comment by wpt1225** [comment]
> > I have downgrade the qdrant version to 1.6.1 and it works well
> 
> So you mean qdrant-client==1.6.4 is not compatible with qdrant server (v1.7.3), and qdrant server can be downgraded to 1.6.1 and works well, right? @JohnJyong pls check it out.

Yes, when I use the qdrant server (v1.7.3), the request error code is 400
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)

**Comment by JohnJyong** [comment]
it has fixed , pls fetch the latest code~ 
thanks for your feedback @wpt1225
