### ISSUE TITLE
keywords moderation

### ISSUE THREAD

**Issue by ShirohaUmi** [langgenius/dify#2034]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.6

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

/api/core/moderation/keywords/keywords.py-----moderation_for_inputs
```python
keywords_list = self.config['keywords'].split('\n')
```
if the keywords is "a\n",then the keywords_list will be "a" and "". Then each input will violate the rule because "" is in every string.

After that,when moderating ouput, "" is also in the response. So we will see the output is violated the rules instead of the input.

-----
关键词分割的时候会分割出来”“空字符串，然后输入过不了审查。可以分割之后判空，同时去掉空格。
输入审查不通过，然后输入审查不通过的预设语句也过不了输出审查，结果最后看到是输出审查失败，可以从业务层面思考一下如何处理这种情况

**Comment by GarfieldDai** [comment]
#2042 Fixed.

**Comment by ShirohaUmi** [comment]
the same situation will happen again when moderating output....
----
输出也要改的。
然后输入审查失败的预设回复过不了输出审查的情况是否需要考虑一下？

**Comment by GarfieldDai** [comment]
@ShirohaUmi Output moderation has been fixed. #2108

**Comment by GarfieldDai** [comment]
后输入审查失败的预设回复过不了输出审查的情况是否需要考虑一下？
