### ISSUE TITLE
 The effect of knowledge base rag is very poor after multiple rounds of dialogue.

### ISSUE THREAD

**Issue by Sunwc0** [langgenius/dify#2035]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

 The effect of knowledge base rag is very poor after multiple rounds of dialogue.

**Comment by takatost** [comment]
Can you share the details of how to reproduce the issue?
