### ISSUE TITLE
API Extentions not well explained

### ISSUE THREAD

**Issue by vontainment** [langgenius/dify#2046]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I have gone into settings and api extentions and tried to add one. Every api I have tried fails with a 404.. what exactly is it exspecting? what is an example of a compatable api?

**Comment by vontainment** [comment]
Now I'm even more confused... I'm not even sure the API extensions are what I thought they are...

**Comment by crazywoola** [comment]
The API extension on dify is a simple solution to call third-party services, which requires you pre-define the parameters in the extension, and config it in our application. It's not the same with the function calls like openai, it allows llm to decide when to call other services. We will support this way in our next version.


Also https://docs.dify.ai/advanced/extension/api_based_extension/cloudflare_workers check this out, this is much simpler than previous one.

**Comment by vontainment** [comment]
Okay thank you That helps a lot that actually that git repository example but understanding now thank you

**Comment by vontainment** [comment]
So I figured most of this out. but  What I'm confiused with is, what is 
"app_id": "______"
and
"tool_variable":"________"  
used for?  i noticed all variables in the app are added to input.

also if i turn on a tool... then it only seems to query it... is there a way to decisde when to query it and when not to?

**Comment by crazywoola** [comment]
> So I figured most of this out. but What I'm confiused with is, what is "app_id": "**" and "tool_variable":"**__" used for? i noticed all variables in the app are added to input.
> 
> also if i turn on a tool... then it only seems to query it... is there a way to decisde when to query it and when not to?

Try to use our latest version, it supports letting the llm itself to decide when and what to use tools.
