### ISSUE TITLE
Please add Export or download chats/full conversation of bots

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2056]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

i wanted to download the conversations with my bots in proper formatted way so that i can send those to others to let them see information which i produced with my bot but couldnt do that because there is not download/export option for conversations with bots.

### 2. Describe the feature you'd like to see

I actually wanted to download the conversations of me and bot and wanted to send that file to my friend but there is no option for that unfortunately so hope it gets added so that people can download there full conversations with AI/bot and maybe added support for downloading in multiple format (IF POSSIBLE like in beautiful pdf format maybe :-)) ) else atleast add to download in proper formated chats in txt file . I know conversations are saved in db and we can see them from frontend always but still if we wanna send those conversations in PROPER FORMATTED WAY without directly giving others direct access to our bot frontend then export/download chats/conversation is the best option which is missing but can be very helpful in these scenarios and must be included in this wonderful project :-)).

### 3. How will this feature improve your workflow or experience?

:-)

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
It's an old question https://feedback.dify.ai/from-dify/p/app-exportimport .
We have already add this feature to our roadmap, it should been done within next 2 releases.

**Comment by jtlz2** [comment]
> It's an old question https://feedback.dify.ai/from-dify/p/app-exportimport . We have already add this feature to our roadmap, it should been done within next 2 releases.

Link is dead?

**Comment by jack-yu-matrix** [comment]
link is dead, is this now done ?
