### ISSUE TITLE
recommended prompt is wrong

### ISSUE THREAD

**Issue by chengweiv5** [langgenius/dify#2059]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.7

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. follow dify document here (https://docs.dify.ai/v/zh-hans/guides/application-design/creating-an-application) to create an example application
2. goto prompt page
3. enter below words
![20240116171057](https://github.com/langgenius/dify/assets/689798/f3ab7466-e22f-4629-96da-d662f6aa3554)

5. click "生成" button
6. check the output at the bottom of page, like below
![20240116170932](https://github.com/langgenius/dify/assets/689798/d7b92a09-0a2b-4426-9c9d-951aad3f8128)

the prompt says something about letter of love, not exactly what I want.

### ✔️ Expected Behavior

the prompt generated should says something about student

### ❌ Actual Behavior

the prompt says something about letter of love

**Comment by takatost** [comment]
Maybe try switching the default LLM from the model provider to GPT-4 and see if it works?

**Comment by chengweiv5** [comment]
Not permitted to use.
![20240117094432](https://github.com/langgenius/dify/assets/689798/159a30b9-bb2c-4246-9141-513cf9115b21)

**Comment by takatost** [comment]
> Not permitted to use. ![20240117094432](https://private-user-images.githubusercontent.com/689798/297235032-159a30b9-bb2c-4246-9141-513cf9115b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODE5NjIsIm5iZiI6MTcwNTQ4MTY2MiwicGF0aCI6Ii82ODk3OTgvMjk3MjM1MDMyLTE1OWEzMGI5LWJiMmMtNDI0Ni05MTQxLTUxM2NmOTExNWIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwODU0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDQ3OGU5ZTJhZWRmZTM2NDM3NzE5NTcwMmJjMDdlYjNmYmYwZTZiODM4ZmMyMGRlYzgyZjhlZmMwY2QzOThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xcVwWeAi-rIJMT0YjEZ7OHeHLVNtDTW8kjkzCwUznck)

Currently, the trial credits provided by the platform do not support GPT-4. However, you can set up your own OpenAI API-Key to use it. 😊
