### ISSUE TITLE
Web reader not working or am i doing something wrong ?

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2064]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

![20240116_16h43m10s_grim](https://github.com/langgenius/dify/assets/55040435/24016fa2-dc65-4d1b-896e-dd2cd8ceab47)
![20240116_16h41m35s_grim](https://github.com/langgenius/dify/assets/55040435/c735ecbc-b4c0-461a-93a1-9b165cb23c34)
![20240116_16h43m28s_grim](https://github.com/langgenius/dify/assets/55040435/bce1f4d7-d906-463c-914a-f743c40732eb)

**Comment by HakaishinShwet** [comment]
web reader is not extracting information from link and showing me or summarizing. Am i doing something wrong? plus what all things can it do is what i wanna know.
I am attaching ss of what i tried with link and what google gemini pro showed so please see and guide if i am doing something wrong or missing it or is it gemini issue or application issue of not been able to scrape the data and feed in time to gemini

**Comment by crazywoola** [comment]
Wow cool browser theme. I think this site is protected from spiders, so it's reasonable that it won't work as expected.

**Comment by HakaishinShwet** [comment]
@takatost  thanks for that info hope you experiment more with google gemini pro as it is right now free plus hyped so lot many will be trying many things with it haha and if possible try to improve it so that  many can take advantage of that :-)) for now i am not closing from my side but you can close if you want but i request you at las to add this request of improvement to improvement category of your road map :-)
Thanks

**Comment by HakaishinShwet** [comment]
@takatost i dont know why it didnt worked for me will test with some settings change maybe

**Comment by HakaishinShwet** [comment]
will test and tell you after that you can close this one or i will close myself :-))

**Comment by HakaishinShwet** [comment]
@takatost right now i put this issue link to see if it detects or not and it did and i asked some questions altho answers were not that perfect but it was able to fetch some info. Maybe its not that perfect rn if i directly ask about link but if i do some conversation and then ask then it is able to tell me so its kinda weird haha but for now i will be closing it because it is working but still i insist you to atleast put this thing in your later testing and improvement phase (especially with google gemini pro) after adding major things and fixing major bugs.
arigato gozaimasu devs
