### ISSUE TITLE
添加智谱模型提示token过期

### ISSUE THREAD

**Issue by cqhaohao** [langgenius/dify#2066]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. 智普重新生成API key
2. dify > 设置 > 模型供应商 > 智谱AI > 设置，添加key，保存，提示
`Error Code: 1003, Message: Authorization Token已过期，请重新生成/获取。`
![image](https://github.com/langgenius/dify/assets/7911284/60c9e9d9-521b-4468-a7dd-4aaa74c7bd15)

### ✔️ Expected Behavior

1. 添加智谱成功

### ❌ Actual Behavior

1.无

**Comment by cqhaohao** [comment]
1.  0.3.32版本我成功添加过智谱ai，当时还参加过dify和智谱的活动，模型功能正常，现在删除智普后重建就不行了，更新到最新版本也不行

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by Sunwc0** [comment]
同样的问题解决了吗
