### ISSUE TITLE
can not change back to customized configuration any more

### ISSUE THREAD

**Issue by chengweiv5** [langgenius/dify#2067]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.7

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. create an application
2. goto prompt engineering page
3. goto model setting
4. change setting to anyone of other settings
5. now the "customized setting" can not be selected

![20240117094542](https://github.com/langgenius/dify/assets/689798/2043b204-9a83-4ee0-beae-d59137167f0b)

### ✔️ Expected Behavior

I can change back to customized setting

### ❌ Actual Behavior

I can't change back to customized setting

**Comment by crazywoola** [comment]
Can you try regenerate the api token at zhipu console to see if this persists.
