### ISSUE TITLE
add Model Provider：ZHIPU  error

### ISSUE THREAD

**Issue by cqhaohao** [langgenius/dify#2068]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. open settings > Model Provider , click ZHIPU.AI ' settting
![image](https://github.com/langgenius/dify/assets/7911284/20b932b4-939c-48fa-9980-f081665e5e5d)

2. add API KEY ，click save
![image](https://github.com/langgenius/dify/assets/7911284/5877e9cf-ff44-4b8f-beee-29f4cb988218)

error msg
`
Error Code: 1003, Message: Authorization Token已过期，请重新生成/获取。
`

### ✔️ Expected Behavior

1. add ZHIPU.AI model success

**Comment by crazywoola** [comment]
Can you try regenerate the api token at zhipu console to see if this persists?
