### ISSUE TITLE
There is typing delay while chatting with bot when we conversate too much with it in same chat.whenever we write in text area there is lag and words appear late in text area

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2071]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.7 latest updated today only 

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

i am using firefox with selfhosted latest version(updated today only before mentioning this issue) in previous version i didnt had any time to test so cant say if it is introduced in newer or was by default and never been reported yet. But i am facing typing delay in text area where we type our message when i conversate too much in that same chat window you first of .you have to chat for sometime. i basicially was asking for some coding things but main thing is big conversation in single chat window and then it starts to lag when we type message 

### ✔️ Expected Behavior

it shouldnt lag at all and should normally let me write in text area.

### ❌ Actual Behavior

whatever i type in text area i face lags and keyboard words are shown later in text area .this doesnt happen in starting when we create new chat but when we keep conversating with for some time say 1 hour or more and then we type any message to send there is big lag of text showing in text area which shouldnt happen but is happening and i have tested it with extensions/addons on and off both and i am not running any userscript or other thing so i dont know why it is happening please check it and resolve it.

**Comment by HakaishinShwet** [comment]
@iamjoel @zxhlyh  did you find what is causing this issue and were you able to resolve it? i thought to ask because it is serious issue for me as i am not able to do conversation conveniently because of the mentioned lag

**Comment by HakaishinShwet** [comment]
@takatost any updates on this one?

**Comment by zxhlyh** [comment]
@HakaishinShwet My guess is that there are too many messages, causing the number of DOM elements to increase. Can you check if the scroll bar is also stuck? The solution is to use virtual scrolling. We are working on this issue.

**Comment by zxhlyh** [comment]
fixed #2200

**Comment by HakaishinShwet** [comment]
@zxhlyh i was also thinking same and main issue was when i did start code generating with it there was serious delay in typing and the bigger code i generate and longer the conversation the more it lags and i was thinking it is related to dom rendering anyways will check new update and hope it is fixed :-)
