### ISSUE TITLE
celery_app 没有执行 beat_schedule 中的任务，clean_embedding_cache_task 和 clean_unused_datasets_task

### ISSUE THREAD

**Issue by lujin1** [langgenius/dify#2077]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker-compose.yaml 中缺少 celery beat 的容器，导致定时任务无法被执行

### ✔️ Expected Behavior

添加 Celery Bea 容器

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
