### ISSUE TITLE
The celery beat container is missing in docker-compose.yaml, causing scheduled tasks to fail to be executed.

### ISSUE THREAD

**Issue by lujin1** [langgenius/dify#2081]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

did not execute the tasks in beat_schedule
- clean_embedding_cache_tas
- clean_unused_datasets_task

**Comment by takatost** [comment]
Currently, these two scheduled tasks are specifically serving Dify SaaS to clear out expired data. 
Just curious, do you have any requirements in this field?

**Comment by lujin1** [comment]
What is expired data?
I just want to clear the embedings table data in the postgres database.
The data is already stored in weaviate vector database.

**Comment by takatost** [comment]
The next version v0.4.9 will deprecate the `embeddings` table, using redis cache for 1 hour as an alternative. Just FYI, you'll be able to directly truncate this table then.

**Comment by takatost** [comment]
v0.4.9 is out. No more using the embeddings table.
