### ISSUE TITLE
support for pgvector vector store

### ISSUE THREAD

**Issue by lujin1** [langgenius/dify#2082]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

cannot use existing pgvector

### 2. Describe the feature you'd like to see

support for pgvector vector store

### 3. How will this feature improve your workflow or experience?

use existing pgvector

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yash-1511** [comment]
Hello @crazywoola ,

I am writing to express my interest in contributing to the development of support for the pgvector vector store in the project.

I believe that enhancing and adding support for the pgvector vector store will greatly improve my workflow and experience with the project. 
I have already conducted thorough research, including searching for existing issues (including closed ones), and I have confirmed that I am using English to file this report, in line with the Language Policy.

Thank you for considering my request, and I look forward to contributing to the project's success.

**Comment by crazywoola** [comment]
@Yash-1511 Thank you very much for your interest and enthusiasm in contributing to the project. Your suggestion to enhance support for pgvector vector storage is intriguing and could have a significant impact on the project's development.

Please feel free to share any specific ideas or implementation plans you have. We are always open to new ideas and welcome new contributors, and your support will undoubtedly enhance the overall quality and user experience of the project. Also, if you need any assistance or would like to discuss your ideas further, both the members of our community and I are more than willing to help.

Thank you again for your support and contribution!

You can contact me through email banana@dify.ai or find pinkbanana in discord channel.

**Comment by Aurelius-Huang** [comment]
Is there any progress on pgvector storage support?
