### ISSUE TITLE
Help, can't download the project via git

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#2087]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

Have tried several times and have not been able to connect, is there a mirror address I can use?
![111](https://github.com/langgenius/dify/assets/120318135/63f69cb3-f299-4916-8e53-e891332f5c03)

**Comment by Yash-1511** [comment]
Hey @nickboyabc 

The problem you encountered is your network is not reachable to GitHub.com. check your internet connection or else check if firewall or something blocks.
