### ISSUE TITLE
Token Count for message creation

### ISSUE THREAD

**Issue by abdullahbaa5** [langgenius/dify#2088]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

I am unable to log token counts for creating application that want to monitor the amount of tokens used since the api call for create message does not return the token used (input and output)

### 2. Describe the feature you'd like to see

Token used Input and output in the Create Message Response

### 3. How will this feature improve your workflow or experience?

Answer 1

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
`usage` return was released in v0.4.8, expect its API docs to be updated in v0.5.0. You can try calling the API to check out the return structure of `usage`.

**Comment by abdullahbaa5** [comment]
> `usage` return was released in v0.4.8, expect its API docs to be updated in v0.5.0. You can try calling the API to check out the return structure of `usage`.

Awesome! I tried it and it works great.

Also i think you meant to say v0.4.9?

**Comment by takatost** [comment]
> > `usage` return was released in v0.4.8, expect its API docs to be updated in v0.5.0. You can try calling the API to check out the return structure of `usage`.
> 
> Awesome! I tried it and it works great.
> 
> Also i think you meant to say v0.4.9?
> 
> You may close the request as completed!

Added this feature in v0.4.8, sorry for the late reply btw 😅
