### ISSUE TITLE
AWS sagemaker LLM support

### ISSUE THREAD

**Issue by benjamin-code** [langgenius/dify#2092]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

We have some open source llm and embedded model running in AWS sagemaker.How can I access these models in dify?

### 2. Describe the feature you'd like to see

Access models running in AWS sagemaker

### 3. How will this feature improve your workflow or experience?

Sagemaker is enterprise LLM platform in our global company 

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Thx a lot for your interest in contributing to Dify! 😁👍 You can check out the following docs on how to integrate a new model provider:
https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md
https://github.com/langgenius/dify/blob/main/api/core/model_runtime/README.md
