### ISSUE TITLE
Introducing Function Calls for Enhanced API Tool Integration and Flexibility

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#2104]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Yes, many complex use cases are not currently possible to build with Dify apps. There are a lot of integrations which I would like to add in Dify apps, but if I just build an API tool, users which build Dify apps can just "enable" it to the app. They cannot low-code logic around it for example calling a tool with a parameter from variables. In addition, I would like to be able to develop Dify integration with API tool/function call support which users can use to build their own logic around integrations. Currently it is not possible because when I add API tools, I have to implement the whole logic in this external API and can only respond the content which gets added to the instructions.

### 2. Describe the feature you'd like to see

I propose adding a "function call" feature. This feature would allow developers to flag a REST resource as a function in the OpenAPI spec, which can then be transformed into a function call. This function call can be registered in the Dify prompt engineering interface, allowing users to build their own logic around integrations. 

Here's a more detailed breakdown of the proposed feature:

- When developing an API tool, I can flag a REST resource as a function in the OpenAPI spec.
- The OpenAPI spec can then be transformed to a function call. Example: https://cookbook.openai.com/examples/function_calling_with_an_openapi_spec
- In Dify, when I add the tool, it recognizes it as a function and registers it in the prompt engineering interface.
- Given the API "Event Management API" exposes the function "createEvent", in the Dify prompt engineering, below "Variables", I see "Functions" with an entry "Event Management API" that contains a card with title "createEvent". In this card there are inputs "name", "date", "location", a badge that displays the type (e.g. date-time, string, ...), a second input where I can link a variable for this field (from "Variables" above). In the card footer is a select for an output variable and a select for a trigger type (userMessage, assistantMessage, toolMessage).
- The trigger type userMessage triggers the function call when the user sends a message, making the variables which are linked to function parameters required. The Dify backend calls the API and writes the response (if successful) in this variable, which then can get injected into the prompt that is sent to the assistant.
- The trigger type assistantMessage triggers the function call when the assistant sends a response. The Dify backend tries to parse a JSON code block from the response, when the response does not contain anything else than a JSON code block. It writes the whole object into the linked variables to fill function parameters and then executes the API request. The response is written into a variable. The response can be used to call another function of type toolMessage, the response will also be added to the chat response in response_mode blocking and will be sent as the last message in response_mode streaming with a special JSON format, allowing consuming apps to work with the function call result.
- The trigger type functionCall triggers the function call when the user sends a message. The Dify backend executes an OpenAI Function call. It writes the response into the linked variable. This is only possible if a supported model is selected, e.g. Azure OpenAI or OpenAI. Dify makes a function call request with a simple "ping" function to verify that the model provider's API supports that.
- The trigger type toolMessage triggers the function call after another tool has been called, which can be a function call.
- The order of execution of the function calls can be changed by drag'n'drop in the UI.
- It is possible to use a special syntax in prompt engineering, e.g. $createEvent({{eventName}}, {{eventDate}}, {{eventLocation}}). When the user leaves the prompt input or saves, a validation is executed to ensure that all variables are defined, functions are defined and variables are linked to the functions. If not, it asks the user for permission to set up everything to make it work. If that is not possible, for example, because no functions are defined, the function will be marked red in the prompt input and the user cannot save.
- Variables can have default values.
- Function call results must be linked to a variable (Dify will create <functionName>Response as default variable, e.g. createEventResponse).
- Introducing objects in variables, allowing to do {{createEventResponse.status}},  {{createEventResponse.error}},  {{createEventResponse.body}}. createEventResponse.error can be an HTTP error message or an error message defined by Dify. createEventResponse.status will be -1 if Dify was not able to do the response. createEventResponse.body can be a nested object too, e.g. createEventResponse.body.id.
- Dify allows creating/syncing a variable which contains the function call schema (e.g. createEventSchema). This variable can be used in prompt engineering to tell a model how to send a function call response JSON.
- It is possible to define multiple functions with the same name. If two API tools have name conflicts, you need to prefix the function name and variables with the ID of the function (order in the list, which can be changed via drag'n'drop). The function name would then be e.g. $_1_createEvent() and variable names would be {{_1_createEventResponse}}, this will also work if there is no name conflict but one is enforced
- It is possible to define multiple functions with the same name. If two API tools have name conflicts, you need to prefix the function name and variables with the ID of the function (order in the list, which can be changed via drag'n'drop). The function name would then be e.g. $_1_createEvent() and variable names would be {_1_createEventResponse}, this will also work if there is no name conflict but one is enforced to use it if there are conflicts.
- You can use the response from previous function calls in function calls which are executed afterward, allowing chaining function calls.
- There is a timeout slider for the whole functions block, which can be configured via slider. You cannot go higher than the max timeout which is defined by Dify to prevent issues.
- There is a timeout slider for each function which can be used to set a timeout for the underlying API request, this has the same max value as the global one.

With that, users can define functions in the prompt, Dify will automatically define variables for you if an API containing the function has been added to the Dify app. You can use functions to fill variables before generating an LLM response, trigger actions based on the response and even chain function calls.

### 3. How will this feature improve your workflow or experience?

This feature will open up a huge amount of new use cases for Dify apps and make Dify more accessible to non-programmers. It will also allow me to develop integrations for Dify, such as creating an Outlook event based on a user prompt. This feature will significantly enhance the flexibility and control over the logic and parameters of API tools within Dify apps, enabling users to build their own logic around integrations.

### 4. Additional context or comments

This is a complex feature, and while I understand that the Dify team might not implement all aspects of it, I believe that even partial implementation would greatly enhance the functionality and flexibility of Dify apps.
Sure, let's wrap up your feature suggestion:

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by joyjoyyo** [comment]
@Dify team

**Comment by takatost** [comment]
Awesome suggestion! 
Function calling is on our roadmap. Current, we're streamlining our app structure. Our existing Chat App and Completion App are client-facing, with function calling integrated internally as an Agent solution.
Lately, we've been categorizing our App into Assistant (Chat/Agent) App and Workflow App. The LLM component of the Workflow App will support function calling.
Big thanks for your suggestion BTW! 🙌

**Comment by perzeuss** [comment]
> Awesome suggestion! Function calling is on our roadmap. Current, we're streamlining our app structure. Our existing Chat App and Completion App are client-facing, with function calling integrated internally as an Agent solution. Lately, we've been categorizing our App into Assistant (Chat/Agent) App and Workflow App. The LLM component of the Workflow App will support function calling. Big thanks for your suggestion BTW! 🙌

Thank you for your answer and reading my suggestion. Great to hear, that function calls are coming. However, my suggestion is a bit more complex than basic function calls and covers a great UX and integration in the promt engineering flow. Which parts of my feature suggestion are covered by the new agent solution?

- [ ] Will it be possible to fill variables for the system prompt based on function calls before the llm will be prompted?
- [ ] Will it be possible to use function call responses to fill the input for another function call without the need of another evaluation by ai? like allowing to low code a flow.
- [ ] Will it be possible to convert an openapi compatible api into a function without programming experience?
- [ ] Will it be possible to define timeouts for function calls?
- [ ] Will it be possible to use every llm for function callig or will it just support function calling apis like openai?
- [ ] Will it be possible to define fallback/default values for function call results?

Should I perhaps adapt and clarify this feature suggestion again after I have tested the agents feature?

**Comment by Yeuoly** [comment]
Glad to answer your questions here. 😊
1. The workflow will be released recently, it will support a tool call flow, allowing pass variables from a tool to another. 
2. I would love to know a little bit more about what use case do you have in mind for being able to base system prompt on function returns, do you mean support tool calls when organizing SYSTEM PROMPT like variables? if so, it's on way.
3. Timeouts of tool calls can be set when integrating of tools, you can refer to https://github.com/langgenius/dify/pull/2086/files#diff-c470fbfd618c853f48d423083671542533cc719453311186a2dfca1db58cec64
4. Adding function calling like openai to every LLM is a fantastic job, but it costs lots to do that, there is a relation between LLM and output parser of LLM, OpenAI's model supports a direction like <func>$name</func> when streaming out, and the output parser have the ability to parse function call based on it which is not supported by other model like base llama2, what we can do is use `react` mode in langchain
5. Openapi compatible api is already supported in v0.5.0, wish you like it!

**Comment by perzeuss** [comment]
Hi @Yeuoly, thanks for the reply. Sounds awesome!
>     2. I would love to know a little bit more about what use case do you have in mind for being able to base system prompt on function returns, do you mean support tool calls when organizing SYSTEM PROMPT like variables? if so, it's on way.

We are building a frontend code builder like v0.dev. I want to use an agent to analyze which component the AI should use from our UI library to build the code. The result is a list of components, I then want to modify the system prompt to something like "Only use the following components to build the app". I also want to gather information for these components from git repositories, so I need another function call where I fetch data from git and instead of just throwing it in RAG stile into the instructions for an agent which verifies if the component has been uses correctly, I want to define a custom instruction like "The component's source code is {{componentCode}} ..."

There are more use cases where prompt engineering leads to better result than basic reference to documents in context.


> Timeouts of tool calls can be set when integrating of tools, you can refer to https://github.com/langgenius/dify/pull/2086/files#diff-c470fbfd618c853f48d423083671542533cc719453311186a2dfca1db58cec64

Is it possible to define configurable fields for custom integrations? For example, that I can build a tool which allows entering variables in the UI? Let's say we build an advanced web crawler which extracts the URLs from the users prompt, fetches content but aborts the requests when the page does not load within a configured time. We don't know in which environment the tool will be used and if we hard-code timeouts, we will need source code changes and individual builds of dify to support specific use cases.

I would like to provide an input for that and tell users that they should increase the timeout if the tool does fail to fetch content, but still keep it as low as possible to reduce 


> Adding function calling like openai to every LLM is a fantastic job, but it costs lots to do that, there is a relation between LLM and output parser of LLM, OpenAI's model supports a direction like $name when streaming out, and the output parser have the ability to parse function call based on it which is not supported by other model like base llama2, what we can do is use `react` mode in langchain

I'm not sure if I get what you mean by "OpenAI's model supports a direction like $name when streaming out" but I would use blocking response or fully-streamed response from the LLM and fine tune the model to only respond with valid JSON. There already are fine-tuned models, e.g. https://huggingface.co/Trelis/Llama-2-7b-chat-hf-function-calling-v2. Then use a basic JSON parser to parse the fields. 

For me, it would be okay if the LLM fails to generate the JSON sometimes. It would be the user's responsibility to teach the model this correctly.

___
I can't wait to test the agents feature 🚀. Thanks for making dify such a great tool :)

**Comment by Yeuoly** [comment]
> We are building a frontend code builder like v0.dev. I want to use an agent to analyze which component the AI should use from our UI library to build the code. The result is a list of components, I then want to modify the system prompt to something like "Only use the following components to build the app". I also want to gather information for these components from git repositories, so I need another function call where I fetch data from git and instead of just throwing it in RAG stile into the instructions for an agent which verifies if the component has been uses correctly, I want to define a custom instruction like "The component's source code is {{componentCode}} ..."

Then you can wait for our Workflow! it will satisfy all your needs! and it's already in design and developing.

> Is it possible to define configurable fields for custom integrations? For example, that I can build a tool which allows entering variables in the UI? Let's say we build an advanced web crawler which extracts the URLs from the users prompt, fetches content but aborts the requests when the page does not load within a configured time. We don't know in which environment the tool will be used and if we hard-code timeouts, we will need source code changes and individual builds of dify to support specific use cases.

So, adding timeout to parameter in custom tools and allow it to be a variable in UI is what you want, is multiple reties also needed? 

> I'm not sure if I get what you mean by "OpenAI's model supports a direction like $name when streaming out" but I would use blocking response or fully-streamed response from the LLM and fine tune the model to only respond with valid JSON. There already are fine-tuned models, e.g. https://huggingface.co/Trelis/Llama-2-7b-chat-hf-function-calling-v2. Then use a basic JSON parser to parse the fields.


Yeah, you can see it's a fine-tuned model, not all models have the ability to follow instructions as we want, the models OpenAI providers are trained to follow tool calls instruction, and it will output like below
```plaintext
Okay, I should use dalle to draw an image
<func>
dalle
<arguments>
{"prompt": "a cute cat"}
</arguments>
</func>
```

OpenAI could use the \<func\> tag to detect if there is function call, but this depends on the ability of model. As you see, Dify supports almost all mainstream model provides, we have not enough energy and time to fine-tune models for every provider.

---

Thanks for your contributions! 😄
