### ISSUE TITLE
When setting the openai key, raise connetion error

### ISSUE THREAD

**Issue by bioinfotec** [langgenius/dify#2105]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

After start the project using `docker compose up -d `, I login in and begin to set the key, but when i submit it, i get "connection error". I checkd the log and found that /workspaces/current/model-providers/openai return 400 bad request. So is this problem caused by my network.
![image](https://github.com/langgenius/dify/assets/72746748/65614b8c-9511-47c3-87c9-a7f6f575aebb)
![image](https://github.com/langgenius/dify/assets/72746748/4e311f11-8634-449c-8900-7f576d877c8b)

**Comment by takatost** [comment]
Hey, could you pls check the connectivity to `api.openai.com`? Also, try performing the same action at https://cloud.dify.ai. It's the cloud version with the latest code.

**Comment by bioinfotec** [comment]
> Hey, could you pls check the connectivity to `api.openai.com`? Also, try performing the same action at https://cloud.dify.ai. It's the cloud version with the latest code.

Why need the connectivity to api.openai.com？I think the step setting oepnai key is just transfer the key from the front-end to the back-end, am i wrong?

**Comment by takatost** [comment]
> > Hey, could you pls check the connectivity to `api.openai.com`? Also, try performing the same action at https://cloud.dify.ai. It's the cloud version with the latest code.
> 
> Why need the connectivity to api.openai.com？I think the step setting oepnai key is just transfer the key from the front-end to the back-end, am i wrong?

Here we've done some evidence verification to prevent any error during actual use. 
BTW, we're also planning to optimize this interaction process, moving the 'test' function to the front-end, and it won't be mandatory.
