### ISSUE TITLE
云服务https://cloud.dify.ai/ 经常无法访问

### ISSUE THREAD

**Issue by qianbaidu1266** [langgenius/dify#2116]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of requested docs changes

云服务https://cloud.dify.ai/ 不稳定，经常无法访问

**Comment by takatost** [comment]
You need a magic. 😉
