### ISSUE TITLE
OpenAI Configuration Error on Locally Hosted Dify

### ISSUE THREAD

**Issue by MrMWith** [langgenius/dify#2118]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Dify fails to connect to OpenAI API.  Dify throws and error that the path is wrong... here is the OpenAI path I am using. Documentation appears to be unclear on this.

<img width="1684" alt="image" src="https://github.com/langgenius/dify/assets/139026767/fb57a0ad-9e04-425b-8464-d5d230e7683f">

Any ideas?

https://api.openai.com/v1

### ✔️ Expected Behavior

Expected an OpenAI API connection

### ❌ Actual Behavior

Error:  
<img width="1684" alt="image" src="https://github.com/langgenius/dify/assets/139026767/1ddf7570-7978-49fe-a50a-ad6b9b19e3f4">

**Comment by guchenhe** [comment]
hi, looks like `v1` is repeated twice, have you tried removing the `v1` from your input url

**Comment by RBKunnela** [comment]
I had the same problem but I resolved it by going to openai playground and in setting you have the organization id, copy the number there and instead of using the organization name, use the organization id. For me it accepted and now it is all good.
