### ISSUE TITLE
google gemini无法修改API地址，目前国内无法使用，需要使用代理

### ISSUE THREAD

**Issue by chenggb123** [langgenius/dify#2120]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.9

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/131222884/03a82aad-a344-4c00-89d1-b92c8209a9b9)
建议跟openai一样增加代理地址的输入框

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
