### ISSUE TITLE
Inaccessible 'Custom Mode' Selection in OpenAI Model Tone Configuration After Initial Change

### ISSUE THREAD

**Issue by Yash-1511** [langgenius/dify#2130]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.9

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1. Open the configuration settings for the model which parameter configuration(like topk,max token)
2. By default, the 'Custom Mode' is selected upon initial page load.
3. Change the tone setting from 'Custom Mode' to any other available option (e.g., Balanced, Creative, Precise).
4. Attempt to switch back to 'Custom Mode'.

### ✔️ Expected Behavior

The user should be able to switch between different tone settings, including returning to 'Custom Mode', seamlessly without any option becoming unresponsive or unclickable.

### ❌ Actual Behavior

Once the tone setting is changed from 'Custom Mode' to another option, the 'Custom Mode' option becomes unresponsive. It is not clickable, preventing the user from re-selecting it.
![Screencastfrom22-01-24055215PMIST-ezgif com-video-to-gif-converter](https://github.com/langgenius/dify/assets/82636823/6d86521d-ab49-4005-855e-7ad9216e4b2a)

**Comment by zxhlyh** [comment]
fixed. #2135
