### ISSUE TITLE
Has the community board considered supporting chatGLM-4?

### ISSUE THREAD

**Issue by yueliang-x** [langgenius/dify#2131]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

I realized that the community version doesn't work with chatGLM4.

### 2. Describe the feature you'd like to see

I would like to be able to add the GLM-4 modI would like to be able to add the GLM-4 model within the local versionel within the local version

### 3. How will this feature improve your workflow or experience?

This allows me to quickly and easily switch between different models to suit different jobs.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
The model has been merged into the main branch and will be released together in version v0.5.0.
