### ISSUE TITLE
support import obsidian vault as knowlege base

### ISSUE THREAD

**Issue by geosmart** [langgenius/dify#2133]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

all of my diary task, diary, note store in obsidian , with markdown format.

I want to use dify to import all of my notes in obsidian , and search by nature language

### 2. Describe the feature you'd like to see

datasource support import local obsidian vault，set exclude dirs by regexp

### 3. How will this feature improve your workflow or experience?

search personal knowledge base with qa style

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
But they are markdown right? You can simply upload all the markdown files to the knowledge base I think.

**Comment by geosmart** [comment]
now dify need to manual upload files,and does't support dir.
I have thousands of documents need to add to the knowledge base.

when my note update, how to dynamic update the knowledge base.
does dify's knowledge base has an api to do this?

eg. knowledge base have a webhook  to recieve a file url and import template, then auto finish build the vector index.

**Comment by geosmart** [comment]
ok,  I found  the datasets api...

**Comment by geosmart** [comment]
I write a shell to import my obsidian vault dir to dify dataset
```bash
#!/bin/bash

# dify nginx gateway
endpoint="http://192.168.68.100:18880"
dataset_id="a2139662-cf9b-1111-a75d-9d5de6ee2f02"
dataset_apikey="dataset-h1QJdjzI9Cbl3Vuj234RTCQh"

# import src dir
target_dir="/mnt/mind/data/kbase/obsidian"

# import all markdown file recurcely
function process_files {
  local dir="$1"
  for file in "$dir"/**/*.md; do
    if [ -f "$file" ]; then
      echo "Processing file: $file"
      filename=$(basename "$file")
      # 执行POST操作
      curl -X POST "$endpoint/v1/datasets/$dataset_id/document/create_by_file" \
      -H "Authorization: Bearer $dataset_apikey" \
      --form "data={\"name\":\"$filename\",\"indexing_technique\":\"economy\",\"process_rule\":{\"mode\":\"automatic\"}}" \
      --form 'type=text/plain' \
      --form "file=@$file"
    elif [ -d "$file" ]; then
      process_files "$file"
    fi
  done
}

process_files "$target_dir"
```

**Comment by replete** [comment]
@geosmart I am also looking at this use-case of importing a local obsidian vault (at least parts of it) as a knowledgebase to chat with. Are you still using this solution? I'm hoping to set something up that can automatically reindex notes without uploading thousands of files via a web UI.

It seems like it be best to import different folders as separate collections.

Phil
