### ISSUE TITLE
How to Upload .pptx file when running with docker?

### ISSUE THREAD

**Issue by 11208** [langgenius/dify#2134]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I have download and run dify using docker. Using Azure OpenAI as a Models. 
When I try to create a  Knowledge base AI, I cannot import .pptx? 
How to make a community version support .pptx file?
![Screenshot 2567-01-23 at 12 28 48](https://github.com/langgenius/dify/assets/38026488/7e987709-3689-4926-8de2-47d5befe5c0d)

**Comment by crazywoola** [comment]
This file format will be supported in v0.5.0.
