### ISSUE TITLE
Request for support to import Feishu documents

### ISSUE THREAD

**Issue by xmsz-stu** [langgenius/dify#2136]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

All of our documents are stored on Feishu, and Feishu provides APIs. 

### 2. Describe the feature you'd like to see

We hope that the current product can directly and automatically synchronize Feishu documents.

### 3. How will this feature improve your workflow or experience?

Efficiency

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/2137 @xmsz-stu 

You can continue discussing this topic in this thread.
