### ISSUE TITLE
What's the best document format for import?

### ISSUE THREAD

**Issue by xmsz-stu** [langgenius/dify#2137]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I want to import my existing documents into dify. My documents are in Feishu format, and I can only export them as PDF or Word. Which format would be better to choose, and what are the differences between them? 

Additionally, would it be better to export as Markdown？, Even though it requires manual conversion from Feishu documents, which adds to the development cost?

Furthermore, if I want to support more rich text types in the response content, such as links and images, how should I set up my documents?

**Comment by crazywoola** [comment]
For me, I would suggest using markdown files to store structured data. But the limitations of large models themselves lead to poor image recognition.
We use unstructureio to parse PDF and other file formats. So, it highly depends on the library itself.
