### ISSUE TITLE
Expert Prompt editing window not show after click "Expert Prompt"

### ISSUE THREAD

**Issue by wonca** [langgenius/dify#2138]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1917" alt="image" src="https://github.com/langgenius/dify/assets/314666/7691ae20-cb29-4a7f-9d92-5e2d95782e8a">

After created an App and go to "Prompt Eng." page (Text Generator type), when select "Expert Mode", the prompt window still show as normal mode. At this time if try to click "RUN", prompt error show up.
Then if publish this app, go out and come back to "Prompt Eng." page again, the page showed expert mode prompt window but no prompt there. After input expert prompt, the page behaved normally.

### ✔️ Expected Behavior

after click"Expert Mode", shows expert mode prompt window

### ❌ Actual Behavior

after click"Expert Mode", still show normal mode window, and the app goes as expert mode, lead to error, and make user confused.

**Comment by crazywoola** [comment]
Try to use the template below

```
Use the following context as your learned knowledge, inside <context></context> XML tags.
<context>
{{#context#}}
</context>
When answer to user:
- If you don't know, just say that you don't know.
- If you don't know when you are not sure, ask for clarification.
Avoid mentioning that you obtained the information from the context.
And answer according to the language of the user's question.
{{query}}
```
