### ISSUE TITLE
Increase API workers/ celery workers

### ISSUE THREAD

**Issue by vontainment** [langgenius/dify#2149]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I Deployed using docker. I that env var can be set to increase API workers and celery workers.

They just same number higher create more workers. Or even more to it. I was sure if do we have to make more API  containers? Do you have to change anything for more celery workers?

0 Also what is the exact difference  intype of workers

**Comment by vontainment** [comment]
Not sure how credible that answer is...
It's not in the repo but on the website it has these environment variables for containers.
Container Startup Related Configuration
Only effective when starting with docker image or docker-compose.
DIFY_BIND_ADDRESS
API service binding address, default: 0.0.0.0, i.e., all addresses can be accessed.
DIFY_PORT
API service binding port number, default 5001.
SERVER_WORKER_AMOUNT
The number of API server workers, i.e., the number of gevent workers. Formula: number of cpu cores x 2 + 1
Reference: https://docs.gunicorn.org/en/stable/design.html#how-many-workers
SERVER_WORKER_CLASS
Defaults to gevent. If using windows, it can be switched to sync or solo.
GUNICORN_TIMEOUT
Request handling timeout. The default is 200, it is recommended to set it to 360 to support a longer sse connection time.
CELERY_WORKER_CLASS
Similar to SERVER_WORKER_CLASS. Default is gevent. If using windows, it can be switched to sync or solo.
CELERY_WORKER_AMOUNT
The number of Celery workers. The default is 1, and can be set as needed.

**Comment by crazywoola** [comment]
> Not sure how credible that answer is... It's not in the repo but on the website it has these environment variables for containers.
> 
> ```
> Container Startup Related Configuration
> Only effective when starting with docker image or docker-compose.
> DIFY_BIND_ADDRESS
> API service binding address, default: 0.0.0.0, i.e., all addresses can be accessed.
> DIFY_PORT
> API service binding port number, default 5001.
> SERVER_WORKER_AMOUNT
> The number of API server workers, i.e., the number of gevent workers. Formula: number of cpu cores x 2 + 1
> Reference: https://docs.gunicorn.org/en/stable/design.html#how-many-workers
> SERVER_WORKER_CLASS
> Defaults to gevent. If using windows, it can be switched to sync or solo.
> GUNICORN_TIMEOUT
> Request handling timeout. The default is 200, it is recommended to set it to 360 to support a longer sse connection time.
> CELERY_WORKER_CLASS
> Similar to SERVER_WORKER_CLASS. Default is gevent. If using windows, it can be switched to sync or solo.
> CELERY_WORKER_AMOUNT
> The number of Celery workers. The default is 1, and can be set as needed.
> ```

Here is the original [link](https://docs.dify.ai/getting-started/install-self-hosted/environments#container-startup-related-configuration)
