### ISSUE TITLE
Azure 资料填写完成后点击 Save 无反应；OpenAI 显示 no quoto

### ISSUE THREAD

**Issue by daz2yy** [langgenius/dify#215]
Dify version: Cloud | Self Host

## Steps To Reproduce
1. 正常在setting 填写好 azure 的 gpt endpoint 和key，也确定对应的model 生成了，页面也没有报错信息，点击 save 的时候没有反应，查看控制台信息，也没有网络交互，是否还未实现 azure 的支持？
<img width="1173" alt="image" src="https://github.com/langgenius/dify/assets/3376580/6dea20a4-0a7e-4682-a2cc-1d75bb5994f4">

3. openai 的key 填了之后显示 no quoto 的红字，但实际这个 api 是可以请求，已经用在飞书、网页等多个场景
<img width="724" alt="image" src="https://github.com/langgenius/dify/assets/3376580/2b3f66d0-5498-407e-acf5-26a0b2951078">

4. docker log 输出如下
<img width="711" alt="image" src="https://github.com/langgenius/dify/assets/3376580/3b0ec640-d0db-4051-b55f-76c8a04bec15">

**Comment by zxhlyh** [comment]
社区版已修复@daz2yy

**Comment by daz2yy** [comment]
重新更新了代码的确可以了，感谢👍
