### ISSUE TITLE
[baichuan] Error: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by USTC-IMCL** [langgenius/dify#2151]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1173" alt="截屏2024-01-24 10 14 54" src="https://github.com/langgenius/dify/assets/113843291/35731491-892a-4ee2-abe8-024705440a9a">
I configure Baichuan app_key correctly, when chat with it, the web popup error message.
I have checked access.log/error.log and docker logs, cannot find any valuable information. Now I have no idea how to locate this issue.

**Comment by USTC-IMCL** [comment]
@dosu-bot I checked baichuan_turbo.py, it seems like 'choices' will be assigned an empty list [].
choices = resp.get('choices', [])
Any other suggession?

**Comment by USTC-IMCL** [comment]
@dosu-bot I checked baichuan_turbo.py, it seems like 'choices' will be assigned an empty list [].
choices = resp.get('choices', [])
Any other suggession?

**Comment by carllisicau** [comment]
大佬 0.5.2还有这个问题  你解决了吗 能否赐教

**Comment by crazywoola** [comment]
FIxed in v0.5.3, if this issue persists, you can reopen this.
