### ISSUE TITLE
git checkout error

### ISSUE THREAD

**Issue by Emirateyang** [langgenius/dify#2153]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When i checkout code from github, I got error below

Merge Error: invalid path 'api/core/model_runtime/model_providers/bedrock/llm/anthropic.claude-v2:1.yaml'

btw, my os is Windows

### ✔️ Expected Behavior

the file should not contain the ":" in file path when the os is Windows

**Comment by crazywoola** [comment]
Close due to not relevant.
