### ISSUE TITLE
Speech to text error

### ISSUE THREAD

**Issue by vontainment** [langgenius/dify#2158]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using the speech to text I get an error. The site encountered an internal error. And something about server might be busy.

### ✔️ Expected Behavior

Convert speech to text

### ❌ Actual Behavior

The site encountered an internal error. And something about server might be busy.

**Comment by takatost** [comment]
Thx a lot for the feedback, the issue is currently being fixed. It'll be sorted out in the next version, v0.5.1.
