### ISSUE TITLE
bad_request_key_error:The browser (or proxy) sent a request that this server could not understand.

### ISSUE THREAD

**Issue by xmsz-stu** [langgenius/dify#2164]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

code
```
const axios = require('axios');
const FormData = require('form-data');

// 替换为您自己的 dataset_id 和 api_key
const dataset_id = '{dataset_id}';
const api_key = '{api_key}';
const filePath = '/path/to/file';

// 创建一个新的 formData 实例
const formData = new FormData();

// 添加 JSON 数据到 formData
formData.append('data', JSON.stringify({
  name: "Dify",
  indexing_technique: "high_quality",
  process_rule: {
    rules: {
      pre_processing_rules: [
        { id: "remove_extra_spaces", enabled: true },
        { id: "remove_urls_emails", enabled: true }
      ],
      segmentation: {
        separator: "###",
        max_tokens: 500
      }
    },
    mode: "custom"
  }
}), { contentType: 'text/plain' });


formData.append('file', fs.createReadStream(filePath));


const config = {
  method: 'post',
  url: `https://api.dify.ai/v1/datasets/${dataset_id}/document/create_by_file`,
  headers: {
    Authorization: `Bearer ${api_key}`,
    ...formData.getHeaders()
  },
  data: formData
};

// 发起 Axios 请求
axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});

```

response
```

data: {
      code: 'bad_request_key_error',
      message: 'The browser (or proxy) sent a request that this server could not understand.',
      status: 400
    }
```

**Comment by JohnJyong** [comment]
Sorry, our document field is wrong, please follow the latest document field to request.
PR:https://github.com/langgenius/dify/pull/2174
curl --location POST 'https://api.dify.dev/v1/datasets/{dataset_id}/document/create_by_file' \
--header 'Authorization: Bearer {api_key}' \
--form 'data="{"name":"Dify","indexing_technique":"high_quality","process_rule":{"rules":{"pre_processing_rules":[{"id":"remove_extra_spaces","enabled":true},{"id":"remove_urls_emails","enabled":true}],"segmentation":{"separator":"###","max_tokens":500}},"mode":"custom"}}";type=text/plain' \
--form 'file=@"/path/to/file"'

**Comment by XUANYUANRuins** [comment]
> Sorry, our document field is wrong, please follow the latest document field to request.对不起，我们的文档字段错误，请按照最新的文档字段进行请求。 PR:[#2174](https://github.com/langgenius/dify/pull/2174)  PR： [#2174](https://github.com/langgenius/dify/pull/2174) curl --location POST '[https://api.dify.dev/v1/datasets/{dataset_id}/document/create_by_file](https://api.dify.dev/v1/datasets/%7Bdataset_id%7D/document/create_by_file)' curl --location POST '[https：//api.dify.dev/v1/datasets/{dataset_id}/document/create_by_file](https://api.dify.dev/v1/datasets/%7Bdataset_id%7D/document/create_by_file)' --header 'Authorization: Bearer {api_key}' --header“授权：承载{API_key}” --form 'data="{"name":"Dify","indexing_technique":"high_quality","process_rule":{"rules":{"pre_processing_rules":[{"id":"remove_extra_spaces","enabled":true},{"id":"remove_urls_emails","enabled":true}],"segmentation":{"separator":"###","max_tokens":500}},"mode":"custom"}}";type=text/plain' --form 'data="{“name”：“Dify”，“indexing_technique”：“high_quality”，“process_rule”：{“rules”：{“pre_processing_rules”：[{“id”：“remove_extra_spaces”，“enabled”：true}，{“id”：“remove_urls_emails”，“enabled”：true}]，“segmentation”：{“separator”：“#"，“max_tokens”：500}}，“mode”：“custom”}}";type=text/plain' --form 'file=@"/path/to/file"'--form 'file=@"/path/to/file”'

This error still exist in dify_v0.15.2
