### ISSUE TITLE
Please add support of plugins for normal bots too

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2165]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Please add support for plugins in normal bots too that we create and use because sometimes we do need google search or wikipedia or web reader with our bot which has custom system message and can respond better so to make normal bots more useful do add support for that not just in normal chat but with our custom bots too,We cant use system message to customize normal chat replies so the best solution is for you to add support for that in custom bots that are created by us.

### 2. Describe the feature you'd like to see

:-)

### 3. How will this feature improve your workflow or experience?

:-)

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
This feature will be supported in the next major release of `Workflow`.
