### ISSUE TITLE
Request to support a feature that can add Text Generator type applications as tools for other types of applications, thereby unlocking the powerful combinatorial capabilities of dify.

### ISSUE THREAD

**Issue by doucheng** [langgenius/dify#2166]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

I'd like to use the existing apps as tools in the agent, but now that I need to configure specs one by one, I hope there are easier ways to do this.

### 2. Describe the feature you'd like to see

Currently tools has Built-in and Custom categories, and I'd like to add an apps (or other name) category to support adding text-generation types to apps as tools.

### 3. How will this feature improve your workflow or experience?

unlocking the powerful combinatorial capabilities of dify.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
This feature is already scheduled, the Text Generation App will be upgraded to the Workflow App soon. And the Workflow App can also be used as an Agent Tool or a Workflow Component.
