### ISSUE TITLE
weaviate连接404报错

### ISSUE THREAD

**Issue by saifeiLee** [langgenius/dify#218]
你好，
我今天突然遇到一个问题，启动项目时报错：
![image](https://github.com/langgenius/dify/assets/28710808/4ee23148-6a64-4ff3-8b39-305a347670ee)
我确认了docker运行正常：
![image](https://github.com/langgenius/dify/assets/28710808/829fabfe-c902-4ae9-b690-1bc204baec30)
在之前从没遇到过，请问有什么分析定位的建议吗？

**Comment by saifeiLee** [comment]
<img width="346" alt="image" src="https://github.com/langgenius/dify/assets/28710808/12854c74-6eb9-4579-929f-3faa55fe6b35">
8080端口是通的

**Comment by takatost** [comment]
If the weaviate log check is ok, then it's probably that the port 8080 on your machine is already taken by another application. You can try to rule this out first

**Comment by saifeiLee** [comment]
> If the weaviate log check is ok, then it's probably that the port 8080 on your machine is already taken by another application. You can try to rule this out first

You are right. Nginx has taken 8080 port on my host machine. Shutdown nginx, all work fine.
