### ISSUE TITLE
URL not able to load in Wecom(Enterprise Wechat) browser starting 2024-01-24

### ISSUE THREAD

**Issue by Haisuuuu** [langgenius/dify#2192]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Starting 2024-01-24, the Dify App URL https://udify.app/chat/xxx could not be opened in the Wecom browser, either mobile phone or desktop client.
Returning error HTTP ERROR 500
I tested it in WeChat, the URL works fine.

### ✔️ Expected Behavior

URL opened

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/157666682/471abd31-b14f-46c5-95f2-f83557d529ca)

**Comment by crazywoola** [comment]
This is a general network issue. It's not related to the application itself.
