### ISSUE TITLE
Azure OpenAI API

### ISSUE THREAD

**Issue by cbqin** [langgenius/dify#22]
请问是否支持Azure OpenAI API？

**Comment by lethe3000** [comment]
api代码里面看起来是有相关实现的，估计近期会放出

**Comment by takatost** [comment]
暂时还没放出，由于 Azure 的模型（deployment）是自定义的，非 OpenAI 固定模型名称，需要界面上调整后才可用哈

**Comment by tairitian** [comment]
一样的问题，同在等待

**Comment by takatost** [comment]
已支持临时方案，注意事项见最后一条：
https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq
