### ISSUE TITLE
从腾讯企业微信连接报错500

### ISSUE THREAD

**Issue by triumph** [langgenius/dify#2218]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.50.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

从iphone手机版腾讯企业微信连接报错500，  从iphone浏览器连接虽然也有500报错，但是可以进入应用页面。web_1       | 2024-01-26T00:55:47.430040713Z ReferenceError: window is not defined
web_1       | 2024-01-26T00:55:47.430060621Z     at 3687 (/app/web/.next/server/chunks/6097.js:1:27551)
web_1       | 2024-01-26T00:55:47.430063446Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:55:47.430065338Z     at 67160 (/app/web/.next/server/chunks/7160.js:1:10468)
web_1       | 2024-01-26T00:55:47.430067113Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:55:47.430068852Z     at F (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
web_1       | 2024-01-26T00:55:47.430070660Z     at $ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
web_1       | 2024-01-26T00:55:47.430080255Z     at rC (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
web_1       | 2024-01-26T00:55:47.430082508Z     at n$ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)
web_1       | 2024-01-26T00:55:47.430084390Z     at nj (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64628)
web_1       | 2024-01-26T00:55:47.430086259Z     at nO (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64035)
nginx_1     | 2024-01-26T00:55:47.440466076Z 192.168.21.180 - - [26/Jan/2024:00:55:47 +0000] "GET /chat/FgZwKy3VHdLriEx5 HTTP/1.1" 500 4877 "https://aiworkbench.stone.test.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Language/zh ColorScheme/Light DistType/publish-website wxwork/4.1.15 (MicroMessenger/6.2) WeChat/2.0.4 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
web_1       | 2024-01-26T00:55:49.469844438Z ReferenceError: window is not defined
web_1       | 2024-01-26T00:55:49.469863020Z     at 3687 (/app/web/.next/server/chunks/6097.js:1:27551)
web_1       | 2024-01-26T00:55:49.469864460Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:55:49.469865423Z     at 67160 (/app/web/.next/server/chunks/7160.js:1:10468)
web_1       | 2024-01-26T00:55:49.469866380Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:55:49.469867659Z     at F (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
web_1       | 2024-01-26T00:55:49.469868782Z     at $ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
web_1       | 2024-01-26T00:55:49.469869810Z     at rC (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
web_1       | 2024-01-26T00:55:49.469870831Z     at n$ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)
web_1       | 2024-01-26T00:55:49.469871816Z     at nj (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64628)
web_1       | 2024-01-26T00:55:49.469872820Z     at nO (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64035)
nginx_1     | 2024-01-26T00:55:49.480631356Z 192.168.21.180 - - [26/Jan/2024:00:55:49 +0000] "GET /chat/FgZwKy3VHdLriEx5 HTTP/1.1" 500 4872 "https://aiworkbench.stone.test.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Language/zh ColorScheme/Light DistType/publish-website wxwork/4.1.15 (MicroMessenger/6.2) WeChat/2.0.4 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
web_1       | 2024-01-26T00:55:51.246393738Z ReferenceError: window is not defined
web_1       | 2024-01-26T00:55:51.246408436Z     at 3687 (/app/web/.next/server/chunks/6097.js:1:27551)
web_1       | 2024-01-26T00:55:51.246409892Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:55:51.246410883Z     at 67160 (/app/web/.next/server/chunks/7160.js:1:10468)
web_1       | 2024-01-26T00:55:51.246411860Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:55:51.246412853Z     at F (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
web_1       | 2024-01-26T00:55:51.246413850Z     at $ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
web_1       | 2024-01-26T00:55:51.246414827Z     at rC (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
web_1       | 2024-01-26T00:55:51.246416011Z     at n$ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)
web_1       | 2024-01-26T00:55:51.246417078Z     at nj (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64628)
web_1       | 2024-01-26T00:55:51.246418060Z     at nO (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64035)
nginx_1     | 2024-01-26T00:55:51.255989712Z 192.168.21.180 - - [26/Jan/2024:00:55:51 +0000] "GET /chat/FgZwKy3VHdLriEx5 HTTP/1.1" 500 4877 "https://aiworkbench.stone.test.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Language/zh ColorScheme/Light DistType/publish-website wxwork/4.1.15 (MicroMessenger/6.2) WeChat/2.0.4 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"

以上是从 苹果mac的企业微信从链接过来的日志。

web_1       | 2024-01-26T00:56:06.726451954Z ReferenceError: window is not defined
web_1       | 2024-01-26T00:56:06.726475655Z     at 3687 (/app/web/.next/server/chunks/6097.js:1:27551)
web_1       | 2024-01-26T00:56:06.726478751Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:56:06.726480758Z     at 67160 (/app/web/.next/server/chunks/7160.js:1:10468)
web_1       | 2024-01-26T00:56:06.726482506Z     at t (/app/web/.next/server/webpack-runtime.js:1:143)
web_1       | 2024-01-26T00:56:06.726484721Z     at F (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
web_1       | 2024-01-26T00:56:06.726486912Z     at $ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
web_1       | 2024-01-26T00:56:06.726488667Z     at rC (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
web_1       | 2024-01-26T00:56:06.726490361Z     at n$ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)
web_1       | 2024-01-26T00:56:06.726492105Z     at nj (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64628)
web_1       | 2024-01-26T00:56:06.726493904Z     at nO (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64035)
nginx_1     | 2024-01-26T00:56:06.734402994Z 192.168.21.180 - - [26/Jan/2024:00:56:06 +0000] "GET /chat/FgZwKy3VHdLriEx5 HTTP/1.1" 500 4877 "https://aiworkbench.stone.test.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:06.775184085Z 192.168.21.180 - - [26/Jan/2024:00:56:06 +0000] "GET /logo/logo-site.png HTTP/1.1" 304 0 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:06.923055029Z 192.168.21.180 - - [26/Jan/2024:00:56:06 +0000] "GET /api/parameters HTTP/1.1" 200 845 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:06.937944451Z 192.168.21.180 - - [26/Jan/2024:00:56:06 +0000] "GET /api/site HTTP/1.1" 200 885 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:06.945436878Z 192.168.21.180 - - [26/Jan/2024:00:56:06 +0000] "GET /api/meta HTTP/1.1" 200 19 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:06.951431750Z 192.168.21.180 - - [26/Jan/2024:00:56:06 +0000] "GET /api/conversations?limit=100 HTTP/1.1" 200 46 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:06.990989998Z 192.168.21.180 - - [26/Jan/2024:00:56:06 +0000] "GET /logo/logo-site.png HTTP/1.1" 304 0 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:07.005692748Z 192.168.21.180 - - [26/Jan/2024:00:56:07 +0000] "GET /api/conversations?limit=20&pinned=true HTTP/1.1" 200 45 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:07.009295473Z 192.168.21.180 - - [26/Jan/2024:00:56:07 +0000] "GET /api/conversations?limit=20&pinned=false HTTP/1.1" 200 45 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"
nginx_1     | 2024-01-26T00:56:07.046512472Z 192.168.21.180 - - [26/Jan/2024:00:56:07 +0000] "GET /api/conversations?limit=20&pinned=false HTTP/1.1" 200 45 "https://dify.stone.test.com/chat/FgZwKy3VHdLriEx5" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15" "124.74.138.218, 172.16.82.7, 124.74.138.218"

以上是苹果mac上的默认浏览器链接。虽然也有500错误，但是最终还是可以进入到应用。

**Comment by triumph** [comment]
升级到 0.5.1 错误解决了，  感谢。

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by crazywoola** [comment]
@triumph Please use English to report an issue.
