### ISSUE TITLE
200次试用不够了，加API Key不行

### ISSUE THREAD

**Issue by scsdlx** [langgenius/dify#222]
我直接使用的您的云服务，部署方便，效果很不错。问题是您提供的200次API调用很快就完了，我想加上自己的openai API Key，但加上后系统提示无响应。应该怎么解决？

**Comment by zxhlyh** [comment]
有截图吗？

**Comment by takatost** [comment]
Please fill out the issue template, we need to know if you're using cloud or self-hosted version, and any other info that might be helpful. Thx!
