### ISSUE TITLE
Please add support for the new models from OpenAI

### ISSUE THREAD

**Issue by richards199999** [langgenius/dify#2224]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

I was trying to test `gpt-4-0125-preview` and `gpt-3.5-0125` with my agents.

### 2. Describe the feature you'd like to see

Since OpenAI released new `gpt-4-0125-preview` and `gpt-3.5-0125` this morning, please add them in your model list.
![image](https://github.com/langgenius/dify/assets/142148415/4cdb53e4-4c9f-4e15-9962-75eb608cbb36)

### 3. How will this feature improve your workflow or experience?

These updated models fix many bugs which can significantly leverage the experience.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by guchenhe** [comment]
Hi @richards199999, feel free to submit a PR :)
