### ISSUE TITLE
After using the image recognition function and activating the smart assistant, I am unable to draw. It prompts a function error

### ISSUE THREAD

**Issue by leochen-g** [langgenius/dify#2229]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

<img width="1650" alt="image" src="https://github.com/langgenius/dify/assets/20028566/e58aee36-37f3-4b08-8a10-144e1c639c58">
1、choose model gpt-4-vision-preview    
2、open ai assistant, add dall-e3 tool
3、input：“帮我绘制一副雪人的场景”

### ✔️ Expected Behavior

After using the image recognition function, when I activate the intelligent assistant, I am unable to draw and receive an error message indicating a function error.

### ❌ Actual Behavior

error
```
[openai] Bad Request Error, Error code: 400 - {'error': {'message': '1 validation error for Request\nbody -> functions\n  extra fields not permitted (type=value_error.extra)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```
However, if you switch the model to another conversational model, such as gpt-3.5-turbo-16k, you will be able to successfully use the DALL-E3 tool for drawing.
<img width="1594" alt="image" src="https://github.com/langgenius/dify/assets/20028566/ff078e1a-23f6-4d7b-bb6a-d16595da0967">

**Comment by Yeuoly** [comment]
Function call is not supported by gpt-4-vision-preview currently, multimodal models will be converted into Tools recently, Thanks for your report.

**Comment by leochen-g** [comment]
> Function call is not supported by gpt-4-vision-preview currently, and multimodal models will be converted into Tools recently, Thanks for your report.

Thanks
