### ISSUE TITLE
Support Qwen multimodal LLMs

### ISSUE THREAD

**Issue by ifsheldon** [langgenius/dify#2236]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Yes, I'd like to use Qwen-VL and Qwen-audio in agents.

### 2. Describe the feature you'd like to see

Please support Qwen-VL and Qwen-audio models

### 3. How will this feature improve your workflow or experience?

We can replace GPT4-Vision with Qwen-VL and extend the capabilities of our agents using Qwen-audio.

### 4. Additional context or comments

For documentation, please see 
* https://help.aliyun.com/zh/dashscope/developer-reference/qwen-vl-plus/
* https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-vl/
* https://help.aliyun.com/zh/dashscope/developer-reference/qwen-audio-chat/

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
#2177
