### ISSUE TITLE
Multiple Models View - Removing one Model, resets chat

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#2245]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

- Create an Assistant App
- Go to Model Settings and click on "Debug as Multiple Models"
- Add up tp 4/4 models, select a model e.g. gpt-3.5-turbo 
- Send a chat message so that all 4 models start generating
![grafik](https://github.com/langgenius/dify/assets/11357019/af9a5ddb-4767-4852-a49c-9633d6a1bfb0)

- After all are done, delete the model at position **#** 3
![grafik](https://github.com/langgenius/dify/assets/11357019/919caa99-1388-4962-bab3-6ca24567cfff)

### ✔️ Expected Behavior

Chat history for # 1, # 2 and # 4 stays visible. Chats do not reset.
![grafik](https://github.com/langgenius/dify/assets/11357019/ad8d7518-9e93-4379-8b19-eb54842d4ae8)

### ❌ Actual Behavior

Chat history for all remaining 3 chat windows are empty. Chat have been reset (at least it looks like that in the UI)
![grafik](https://github.com/langgenius/dify/assets/11357019/8565c44c-c64a-4de2-9460-77d237b894b8)

**Comment by crazywoola** [comment]
Maybe it's related to the window resize. If the window resizes, it will regenerate the conversation as well even it's a single debug area. @zxhlyh

**Comment by zxhlyh** [comment]
fixed. @perzeuss
