### ISSUE TITLE
DALL-E Tool not responding with image

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#2246]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Create an Agent Assistant
- Add the Tool DALL-E 3 (Setup auth if you have not)
  - Same issue with DALLE-2, so you can also choose this to reproduce the bug
- Define the system prompt "You are an Agent capable of generating images with the tool DALL-E. Generated images will be sent to the user as an answer and not via mail."
  - you can keep the prompt empty, I did this just for debugging
- Choose the model "gpt-4-turbo-preview"  and select "Precise" preset
  - Same issue with other models e.g. gpt-3.5-turbo
- Send the message "generate an image with a desk"

### ✔️ Expected Behavior

Agent responds with an image generated by DALL-E 3

### ❌ Actual Behavior

Agend responds with an empty image.

Tool data:
```
Request to dalle3
{"dalle3": {"prompt": "desk"}}
Response from dalle3
image has been created and sent to user already, you should tell user to check it now.
```

Hint: I can see in https://platform.openai.com/usage that DALL-E api has been called and images have been generated.

![grafik](https://github.com/langgenius/dify/assets/11357019/36ea6c4d-5674-4f86-9fcb-9cbc9c204aff)

**Comment by perzeuss** [comment]
Another user faced this issue, see https://discord.com/channels/1082486657678311454/1107330913139970128/1200485873318383677

**Comment by perzeuss** [comment]
I tested it on cloud and the tool does respond with the same text, but the image is visible here:
![grafik](https://github.com/langgenius/dify/assets/11357019/d032626a-f557-4485-af13-07dc528af0fd)

**Comment by perzeuss** [comment]
I did more debugging.

API Logs:
```
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/images/generations "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
```

Looks like the image has been generated. I also see that the frontend tries to fetch the image `/files/tools/76e861ee-45b4-42d0-b412-dee37dea5f51.png?timestamp=1706289633&nonce=...&sign=...` but the server responds with 404.
I do not see files in the configured s3, should the tool place DALL-E images there?

**Comment by perzeuss** [comment]
fixed for me by adding missing

```
    location /files {
      proxy_pass http://api:5001;
      include proxy.conf;
    }
```

To my nginx proxy. I used https://github.com/BorisPolonsky/dify-helm to set up dify and the nginx setup is out of date there. I opened a PR to resolve this: https://github.com/BorisPolonsky/dify-helm/pull/29

**Comment by Kvieta1990** [comment]
Thank you so much for the quick fix and I can confirm that in my case it is working like a charm!

FYI, I was using the docker compose way to fire up the server and added in the missing section as suggested by @perzeuss in the `docker/nginx/conf.d/default.conf` file (following the directory structure of the main repo) and reran the docker composing.

**Comment by crazywoola** [comment]
> Define the system prompt "You are an Agent capable of generating images with the tool DALL-E. Generated images will be sent to the user as an answer and not via mail."

How about remove this from the system prompt, this seems unnecessary to me.

**Comment by perzeuss** [comment]
> > Define the system prompt "You are an Agent capable of generating images with the tool DALL-E. Generated images will be sent to the user as an answer and not via mail."
> 
> How about remove this from the system prompt, this seems unnecessary to me.

I just did that for testing, because I initially thought the image does the wrong thing because of the tool response "image has been created and sent to user already, you should tell user to check it now."

However, the issue can be closed, we just had to update the nginx config and there was no migration hint about that.
