### ISSUE TITLE
chat conversation name does not generated as expected

### ISSUE THREAD

**Issue by geosmart** [langgenius/dify#2249]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

always can not generate the conversation name

### ✔️ Expected Behavior

auto_generate_name should generate the conversation name

### ❌ Actual Behavior

with debug ,I found the auto_generate_conversation_name=false

INFO:root:s_first_message:True,conversation.mode=chat,extras: {"auto_generate_conversation_name": false}

https://github.com/langgenius/dify/blob/b9b692d71de6d3064065785b4c84b6838ac9d55b/api/events/event_handlers/generate_conversation_name_when_first_message_created.py#L15
```python

@message_was_created.connect
def handle(sender, **kwargs):
    message = sender
    conversation = kwargs.get('conversation')
    is_first_message = kwargs.get('is_first_message')
    extras = kwargs.get('extras', {})
    logging.info(f"is_first_message:{is_first_message},conversation.mode={conversation.mode},extras: {json.dumps(extras)}")

    auto_generate_conversation_name = True
    if extras:
        auto_generate_conversation_name = extras.get('auto_generate_conversation_name', True)

    if auto_generate_conversation_name and is_first_message:
        if conversation.mode == 'chat':
            app_model = conversation.app
            if not app_model:
                return

            # generate conversation name
            try:
                name = LLMGenerator.generate_conversation_name(app_model.tenant_id, message.query)
                conversation.name = name
            except:
                pass

            db.session.commit()

```

**Comment by geosmart** [comment]
```bash
      <Property name='auto_generate_name' type='bool' key='auto_generate_name'>
      Auto-generate title, default is `false`.
      Can achieve async title generation by calling the conversation rename API and setting `auto_generate` to true.
```
I found this ofr api

but in the dify UI, can't find the config for `auto_generate_name`

**Comment by geosmart** [comment]
may be we should add `auto_generate_name` option in the `WebApp config`

**Comment by takatost** [comment]
The current design is that, except for the `App OpenAPI`, the interaction on the Dify UI is initiated by the frontend requesting the `chat-messages` API. After receiving the response, the frontend then calls the `rename` API to automatically generate the title. 
This interaction ensures that there is no blocking sensation caused by the backend executing generate name LLM requests for `chat-messages`. 
As for the `App OpenAPI`, the `auto_generate_name` is set to true by default.
