### ISSUE TITLE
User types and long term memory

### ISSUE THREAD

**Issue by vontainment** [langgenius/dify#2251]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

No

### 2. Describe the feature you'd like to see

You think the regular self hosted version should be able to have multi workspaces using email password auth.

Then at an option to bots for long-term memory. It can either be attached to the workspace or attached to users. Basically have it store the conversations in the vector database. 

Should be an option to enable/disable public sign up. Should be an option to limit it to particular domain names for email or not. Then people can sign up with their email and a password. And it would save their conversations privately.

### 3. How will this feature improve your workflow or experience?

It allow for a more personalized bots

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
> You think the regular self hosted version should be able to have multi workspaces using email password auth.

For self-hosted version, multi-tenancy requires our business license, you could send an email to business@dify.ai to get an quota.

**Comment by takatost** [comment]
long term memory will be a part of our future roadmap , and currently we are in the process of building up that capability.
