### ISSUE TITLE
How to fetch data from a third-party API

### ISSUE THREAD

**Issue by fatcatloversknnymonkey** [langgenius/dify#2255]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

我想要调用三方的API，包括不限于自己服务器的接口API或者其他的API。返回的内容不可控，可能会返回一些数据集或者用户信息亦或者其他的内容。请问有什么办法集成进去吗？

**Comment by takatost** [comment]
<img width="738" alt="image" src="https://github.com/langgenius/dify/assets/5485478/55853961-0dd6-4849-bd1f-98b95e340b55">

You can now try using API-based Variable to fetch data from your own API and use it as a variable in your Prompt. In the next month, we'll be rolling out Workflow as a more powerful alternative.

**Comment by crazywoola** [comment]
See [this](https://docs.dify.ai/features/extension/api_based_extension/external_data_tool#api-response) and [this](https://docs.dify.ai/tutorials/cloudflare_workers) for how to build an API tool
