### ISSUE TITLE
自动编排的时候，如果上次设置好模型后，更换成另外一个模型，无法获取新模型，不能更换模型

### ISSUE THREAD

**Issue by yhxiong** [langgenius/dify#2264]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1:在开始页【创建应用】，假设应用是‘智能math助手’。
<img width="1110" alt="image" src="https://github.com/langgenius/dify/assets/44085182/96cde704-9575-4a3c-9110-f17c9fc1c8cf">

2:点击‘智能math助手’，进入详细设置页面，在【编排】的【前缀提示词】中选择【自动编排】模式。
<img width="1494" alt="image" src="https://github.com/langgenius/dify/assets/44085182/84ecda6c-8fea-4e85-a928-c5345af504c0">

3:在【自动编排】页面中填写好“目标用户是谁“和”希望AI为他们解决什么问题“之后，点击【生成】。
4:在上一个应用中我设置了”gemini pro  vision“模型，这个‘数学助理’应用选择了‘qwen-max‘。当上面第3步点击【生成】后，系统还是寻找了gemini pro vision模型，提示出错！出错信息见下图标号为4的红色区域。
![dify 自动编排出错](https://github.com/langgenius/dify/assets/44085182/a66b9be9-0d7c-4b95-bae5-adbdffe34c72)

### ✔️ Expected Behavior

期待调用新设置的qwen-max

### ❌ Actual Behavior

实际上调用的是上次设置的gemini pro vision模型

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
