### ISSUE TITLE
add zhipu glm3-turbo glm4-v error

### ISSUE THREAD

**Issue by Sunwc0** [langgenius/dify#2266]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![WeChat0c19525d4d6ce3427fd07429123de000](https://github.com/langgenius/dify/assets/31982984/4712e8f8-b4a9-4d61-a5dd-dc6a47122cf9)

**Comment by crazywoola** [comment]
Please check your key is correct. You can paste the request payload as well.

**Comment by Sunwc0** [comment]
两个问题：
1.宿主机的时区
2.dify的时区选择成中国时区
zhipu的token校验机制有时间戳校验逻辑

**Comment by SongSongK** [comment]
> 两个问题： 1.发起机的时区 2.dify的时区选择成为中国时区 zhipu的token验证机制有时间戳验证逻辑

1.dify的时区已设置为中国
2.宿主机也是上海时区
但是看docker-api容器的程序日志显示还是UTC的时间，你可以尝试下修改zhipu apikey ，看看有没有办法修改成功
![image](https://github.com/user-attachments/assets/ffc62048-e1fa-4de6-b90d-5383d3a0638a)
![image](https://github.com/user-attachments/assets/7a5593a2-a57f-4e7c-8d93-8625429c555d)
