### ISSUE TITLE
拉取dify的源码后，本地通过readme文件启动了api/web模块。然后打开网址localhost:3000的时候页面一直加载，控制台报错具体如下：

### ISSUE THREAD

**Issue by codingpaidaxing** [langgenius/dify#227]

**Comment by codingpaidaxing** [comment]
<img width="1463" alt="image" src="https://github.com/langgenius/dify/assets/122680363/e237cd45-88b6-49df-9fd7-0bc258e9d296">
主要修改的配置：
<img width="1476" alt="image" src="https://github.com/langgenius/dify/assets/122680363/595846aa-8d8f-4a2d-921b-310568b80f86">
同时在api下增加了.env文件
`# Server Edition
EDITION=SELF_HOSTED

# Your App secret key will be used for securely signing the session cookie
# Make sure you are changing this key for your deployment with a strong key.
# You can generate a strong key using `openssl rand -base64 42`.
# Alternatively you can set it with `SECRET_KEY` environment variable.
SECRET_KEY=arBLRmakjwW35VkmaV96IpKwsFI0bofhJ6phD6LTqjgeP2mbet2JK8Bt

# Console API base URL
CONSOLE_URL=http://localhost:5001

# Service API base URL
API_URL=http://localhost:5001

# Web APP base URL
APP_URL=http://localhost1:3000

# celery configuration
CELERY_BROKER_URL=redis://:difyai123456@localhost:6379/1

# redis configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=difyai123456
REDIS_DB=0

# PostgreSQL database configuration
DB_USERNAME=postgres
DB_PASSWORD=difyai123456
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=dify

# Storage configuration
# use for store upload files, private keys...
# storage type: local, s3
STORAGE_TYPE=local
STORAGE_LOCAL_PATH=storage
S3_ENDPOINT=https://your-bucket-name.storage.s3.clooudflare.com
S3_BUCKET_NAME=your-bucket-name
S3_ACCESS_KEY=your-access-key
S3_SECRET_KEY=your-secret-key
S3_REGION=your-region

# CORS configuration
# WEB_API_CORS_ALLOW_ORIGINS=http://127.0.0.1:3000,*
# CONSOLE_CORS_ALLOW_ORIGINS=http://127.0.0.1:3000,*
WEB_API_CORS_ALLOW_ORIGINS=http://localhost:3000,*
CONSOLE_CORS_ALLOW_ORIGINS=http://localhost:3000,*

# Cookie configuration
# COOKIE_HTTPONLY=true
# COOKIE_SAMESITE=None
# COOKIE_SECURE=true
COOKIE_HTTPONLY=true
COOKIE_SAMESITE=Lax
COOKIE_SECURE=false

# Session configuration
SESSION_PERMANENT=true
SESSION_USE_SIGNER=true

## support redis, sqlalchemy
SESSION_TYPE=redis

# session redis configuration
SESSION_REDIS_HOST=localhost
SESSION_REDIS_PORT=6379
SESSION_REDIS_PASSWORD=difyai123456
SESSION_REDIS_DB=2

# Vector database configuration, support: weaviate, qdrant
VECTOR_STORE=weaviate

# Weaviate configuration
WEAVIATE_ENDPOINT=http://localhost:8080
WEAVIATE_API_KEY=WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
WEAVIATE_GRPC_ENABLED=false

# Qdrant configuration, use `path:` prefix for local mode or `https://your-qdrant-cluster-url.qdrant.io` for remote mode
QDRANT_URL=path:storage/qdrant
QDRANT_API_KEY=your-qdrant-api-key

# Sentry configuration
SENTRY_DSN=

# DEBUG
DEBUG=false
SQLALCHEMY_ECHO=false
`

**Comment by yuhao1118** [comment]
不需要改config文件。把web文件夹下的.env.example复制一份到.env，然后正常启动api和web项目即可

**Comment by codingpaidaxing** [comment]
但是这样我看访问的不是自己本地的api。而是cloud.dify api。我是想本地启动

**Comment by takatost** [comment]
```
# CORS configuration
WEB_API_CORS_ALLOW_ORIGINS=*
CONSOLE_CORS_ALLOW_ORIGINS=*

# Cookie configuration
COOKIE_HTTPONLY=true
COOKIE_SAMESITE=Lax
COOKIE_SECURE=false
```

可配置如下跨域策略
