### ISSUE TITLE
阿里云 源码部署完 web api 时 需要修改哪些配置 才能访问到 api 服务 

### ISSUE THREAD

**Issue by LiSongRan** [langgenius/dify#2273]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of requested docs changes

阿里云 源码部署完 web api 时 需要修改哪些配置 才能访问到 api 服务

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
