### ISSUE TITLE
Dify assistant app stops generating when it takes long

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#2278]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Create a new "Basic Assistant"
- Define the system prompt: `Generate a long story about pandas. Respond with 10 parts, give each part a headline. Each part has at least 200 words.`
- Select GPT 4 Turbo (is a slow model currently)
  - Remove/Disable the Max Tokens
  - Load preset "Creative"
- Send "Go!" in the debug chat
- Wait until the generation stops
- Send "continue"

### ✔️ Expected Behavior

- The backend responses until it reaches the max tokens
- I see the duration and the token spend below the answer
- When I send a new message like "continue" the model continues because it gets the current chat history

### ❌ Actual Behavior

- The backend responses until it reaches a failure state
- I see `0.00s Token spent 0` below the answer
![grafik](https://github.com/langgenius/dify/assets/11357019/5f0d1c03-e72b-4f0d-87ce-a81620b00de9)

- When I send a new message like "continue" the model stars from the beginning, because it does not get the current chat history which contains the previous generated content

**Comment by perzeuss** [comment]
I was not able to reproduce it on cloud, only on my self-hosted instance in Kubernetes.

**Comment by perzeuss** [comment]
@dosu-bot I enabled debugging for the api and in the console I can see that the model completes the generation after it stops in the frontend. 
In additional tests, I found out that the frontend cancels the stream after ~60 seconds in 5 of 5 tests.

I found this 60s timeout in the frontend, could this be the issue? https://github.com/langgenius/dify/blob/9d072920da2af99573fe854c7f4175fd87820001/web/app/components/share/text-generation/result/index.tsx#L167

**Comment by takatost** [comment]
Maybe we can try replacing our main's latest code with the tag `34634bddf12701ee31c462711e60fab3d9a71e73` for the docker images `langgenius/dify-api` and `langgenius/dify-web`.

**Comment by takatost** [comment]
> > Maybe we can try replacing our main's latest code with the tag `34634bddf12701ee31c462711e60fab3d9a71e73` for the docker images `langgenius/dify-api` and `langgenius/dify-web`.
> 
> Same issue with this version. I assume it is a problem with our infrastructure. I'll do some additional tests in the next days to check which system in our infrastructure is the problem.
> 
> However, the bug that the frontend looses the message, could be fixed with a reconnect feature. The frontend would then try to reconnect when the response stream stopped without the `message_end` event. @takatost how do you think about that? It would also cover other scenarios like network disconnects.

That makes sense. Currently, we are using SSE as the streaming output solution, just like OpenAI. However, it's not the standard SSE, which means we can't achieve reconnection. To enable reconnection, we need to use standard SSE as a channel for each user or implement WebSocket. Additionally, the backend also needs to be modified to use a public queue (like Redis queue). This could be a future additional technical solution, but currently, there are no plans for it. For now, it is recommended to investigate the disconnection reasons from your own infrastructure.
