### ISSUE TITLE
Chat对话时提示前端出现json解析错误

### ISSUE THREAD

**Issue by CodeDevNinja** [langgenius/dify#228]
新开对话时偶尔出现json解析错误

**Comment by takatost** [comment]
Can u provide more info about the version and the error msg at that time?

**Comment by CodeDevNinja** [comment]
![image](https://github.com/langgenius/dify/assets/14970585/d5a38a83-db81-4f30-ad36-8d1df63aee28)
 dify 0.3.0

**Comment by CodeDevNinja** [comment]
> Can u provide more info about the version and the error msg at that time?

dify 0.3.0

**Comment by takatost** [comment]
Looks like a network issue, causing the streaming data transfer to be interrupted and unable to parse the JSON response content properly. 
btw, we'll add web page error sentry integration to help us better track the issue.

**Comment by CodeDevNinja** [comment]
[fix/parse-json-in-router-output](fix: raw json parse in llm router chain)https://github.com/langgenius/dify/pull/254
Has this problem been resolved?
@takatost

**Comment by takatost** [comment]
No, it's not an same issue, the front-end page issue is still being tracked, it's probably a network issue

**Comment by limfoo** [comment]
> No, it's not an same issue, the front-end page issue is still being tracked, it's probably a network issue

是，我遇到同样的问题，应该就是网络问题，部署在墙外VPS上，直连就会出现SyntaxError，打开代理就不会。

**Comment by takatost** [comment]
> > No, it's not an same issue, the front-end page issue is still being tracked, it's probably a network issue
> 
> 是，我遇到同样的问题，应该就是网络问题，部署在墙外VPS上，直连就会出现SyntaxError，打开代理就不会。

Yep, that's what I'm saying. It's related to the network quality between client and server

**Comment by CodeDevNinja** [comment]
Can you make it compatible with poor network conditions, at least without throwing errors?

**Comment by CodeDevNinja** [comment]
> 

Can you make it compatible with poor network conditions, at least without throwing errors?

**Comment by sam1am** [comment]
I am running into same issue. It seems to happen periodically. Perhaps related to api rate limits? 

Can it handle this gracefully or implement some delays maybe?

**Comment by zhangao0086** [comment]
我也遇到了同样的问题，response 里返回的数据是全的，但 console.log 出来的确实是不完整的 JSON，感觉是前端 bug？

<img width="1469" alt="image" src="https://github.com/langgenius/dify/assets/7742344/41830c73-5e1d-4ee7-91d9-06e5786f91b3">
