### ISSUE TITLE
Agent mode does not use streaming output, so the conversation experience seems slow

### ISSUE THREAD

**Issue by lzk90s** [langgenius/dify#2280]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

assistant_cot_runner.py
      

      # update prompt messages
            prompt_messages = self._originze_cot_prompt_messages(
                mode=app_orchestration_config.model_config.mode,
                prompt_messages=prompt_messages,
                tools=prompt_messages_tools,
                agent_scratchpad=agent_scratchpad,
                agent_prompt_message=app_orchestration_config.agent.prompt,
                instruction=app_orchestration_config.prompt_template.simple_prompt_template,
                input=query
            )

            # recale llm max tokens
            self.recale_llm_max_tokens(self.model_config, prompt_messages)
            # invoke model
            llm_result: LLMResult = model_instance.invoke_llm(
                prompt_messages=prompt_messages,
                model_parameters=app_orchestration_config.model_config.parameters,
                tools=[],
                stop=app_orchestration_config.model_config.stop,
                stream=False,                ////////////////////// stream false
                user=self.user_id,
                callbacks=[],
            )

Is there any good way to improve the experience?

**Comment by Yeuoly** [comment]
When using a model without function calling ability, `ReACT` mode is what Agent is going to use, it takes a while to wait for a full response so that we can parse an action from it. However, not all model supports it, we have already adapted almost all models for function calling in latest version in main branch, you can check if there is model you want.

**Comment by lzk90s** [comment]
> When using a model without function calling ability, `ReACT` mode is what Agent is going to use, it takes a while to wait for a full response so that we can parse an action from it. However, not all model supports it, we have already adapted almost all models for function calling in latest version in main branch, you can check if there is model you want.

thanks
