### ISSUE TITLE
Can a download feature be added to the knowledge source ?

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#2287]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Can a download feature be added to the knowledge source?

![12](https://github.com/langgenius/dify/assets/21255047/34e3f6e7-864b-4a58-b201-6fd515b4b0a6)

**Comment by crazywoola** [comment]
Consider the issue of data security, we might not add this feature. There might be a potential risk of data leak which allow the user to retrieve the data they shouldn't be able to get.

**Comment by andylzming** [comment]
> Consider the issue of data security, we might not add this feature. There might be a potential risk of data leak which allow the user to retrieve the data they shouldn't be able to get.

Could we add a setting feature that allows administrators to configure download capabilities based on actual needs?
