### ISSUE TITLE
下载后按文档部署，运行了前后端，对话无问题，但是知识库添加后一直是排队中

### ISSUE THREAD

**Issue by ajavaer** [langgenius/dify#229]

**Comment by takatost** [comment]
按照 README 最后一条启动 worker 即可
https://github.com/langgenius/dify/blob/main/api/README.md

**Comment by ajavaer** [comment]
> Follow the last instruction in the README to start the worker https://github.com/langgenius/dify/blob/main/api/README.md

可以了，但是每次启动成功概率只有30%，剩下的70%就是启动了，又没启动。半个小时了不走任务，一直排队中

**Comment by takatost** [comment]
If the problem persists, you can try the production-oriented startup command by using gevent: 
```
celery -A app.celery worker -P gevent -c 1 --loglevel INFO
```
