### ISSUE TITLE
开启【引用和归属】功能后，来自知识库的回答无法标记来源

### ISSUE THREAD

**Issue by wenhuiwu** [langgenius/dify#2295]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1、添加一个知识库
2、创建一个问答应用
3、问答应用添加这个知识库作为上下文
4、开启【引用和归属】功能
5、在应用中询问一个知识库中的内容
6、ai回到后，没有显示应有的引用信息

### ✔️ Expected Behavior

应该根据功能展示引用
<img width="224" alt="image" src="https://github.com/langgenius/dify/assets/10475862/8502dba7-8c11-469b-9583-dc93291aad4b">

### ❌ Actual Behavior

ai回到后，没有显示应有的引用信息

**Comment by guchenhe** [comment]
See #1542.
