### ISSUE TITLE
[BUG] Batch import failed

### ISSUE THREAD

**Issue by luzhouuu** [langgenius/dify#2300]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I try to batch Import annotations by csv file, it failed. I tired in the cloud and self hosted (Source), the log in self-hosted is:
```
DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for ep in entry_points().get(namespace, []):
  ```
<img width="380" alt="image" src="https://github.com/langgenius/dify/assets/43746574/f10acb4f-6714-47b6-af83-b39271a904fb">

### ✔️ Expected Behavior

The annotation was uploaded

### ❌ Actual Behavior

Upload Failed

**Comment by JohnJyong** [comment]
If possible, please provide your test files. We cannot reproduce the problem you mentioned. @luzhouuu

**Comment by luzhouuu** [comment]
@JohnJyong Thanks for your reply, the upload failure occurred because I attempted to upload more than 5000 annotations at once.
