### ISSUE TITLE
Xinference add embedding error

### ISSUE THREAD

**Issue by yoke233** [langgenius/dify#2305]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="874" alt="image" src="https://github.com/langgenius/dify/assets/2161917/cc4797eb-3555-4b2d-b802-ac768724d004">

**Comment by takatost** [comment]
https://docs.dify.ai/tutorials/model-configuration/xinference
Did you start the xinference server following these steps? And check the URL field you filled in with the right xinference server API URL.

**Comment by Yeuoly** [comment]
You can check if there is a / suffix in your server_url or just try the latest 5.3.0

**Comment by yoke233** [comment]
server url my input is http://xxx:39093/  change to http://xxx:39093 work ok
