### ISSUE TITLE
How to login with the newest version?

### ISSUE THREAD

**Issue by pyth0nb3st** [langgenius/dify#2307]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I set up the Dify latest update in GitHub codespaces and run locally. When I open the frontend page, it lets me login with github/gmail but when I input email, no code is received. Previously I could log in with a user account but now I can't. Do you know how I can login it?

![image](https://github.com/langgenius/dify/assets/132567133/e34a1c53-6fc7-40f9-822f-c806c4284ce7)

**Comment by takatost** [comment]
Is the environment variable EDITION modified? It should be SELF_HOSTED by default.

**Comment by pyth0nb3st** [comment]
> Is the environment variable EDITION modified? It should be SELF_HOSTED by default.

![image](https://github.com/langgenius/dify/assets/132567133/9e1d65fb-90a6-434f-8e61-479a97566221)

I just opened it with codespaces and no change is applied. But this env var should be a good hint for me to explore it. Thanks a lot  for the help!

**Comment by takatost** [comment]
Did you start it by running the source code? Have you copied the .env.example file under the web directory and renamed it as .env.local?

**Comment by pyth0nb3st** [comment]
> Did you start it by running the source code? Have you copied the .env.example file under the web directory and renamed it as .env.local?

sorry I forgot.. the code is just so smooth to start with yarn... solved by using `.env.local`.
