### ISSUE TITLE
确保正确的API KEY却一直校验失败

### ISSUE THREAD

**Issue by JiangYain** [langgenius/dify#232]
![image](https://github.com/langgenius/dify/assets/116129630/74b0b5e3-28ed-4c95-9d03-689d9d4fc356)

**Comment by JiangYain** [comment]
<img width="321" alt="e064dd9b27395992a90f3a549478a3c" src="https://github.com/langgenius/dify/assets/116129630/b603a2d4-f023-4da6-ba40-d5b56ed67f89">
重新部署后报错如上，是部署再虚拟机上的

**Comment by JohnJyong** [comment]
可以参考一下 #80

**Comment by kevinhorse** [comment]
我的也一样，参考了80修改了也不行，一摸一样
