### ISSUE TITLE
token limitation after some questions

### ISSUE THREAD

**Issue by lijutan0** [langgenius/dify#2320]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Utility with translation issue

ollama

### 🌐 Language affected

China

### ❌ Actual phrase(s)

<img width="1176" alt="截屏2024-01-31 22 04 30" src="https://github.com/langgenius/dify/assets/64645704/aa3449d1-1434-4406-8502-df3d8aecb35e">

### ✔️ Expected phrase(s)

dify could answer my question from ollama.

### ℹ Why is the current translation wrong

after some questions, the model of ollama could not answer questions.

**Comment by guchenhe** [comment]
Error seems self explanatory, what context size did you input when configuring the model?
