### ISSUE TITLE
ERROR: missing file upload_file_id

### ISSUE THREAD

**Issue by killpanda** [langgenius/dify#2321]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2 and other older versions

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. create a `text generator` type app
2. use the `gpt-4-vision-preview` model, and enable the `Vision` feature
3. when using app, select `uploading a file` choose a file, and click `run`. If the file does not finish uploading, it will show an error.

<img width="776" alt="image" src="https://github.com/langgenius/dify/assets/217538/a6e56262-9c12-4779-9489-46010fc73083">

### ✔️ Expected Behavior

show a friendly message, like `waiting for upload finished`.

### ❌ Actual Behavior

show error `missing file file_upload_id`

**Comment by iamjoel** [comment]
Fixed with https://github.com/langgenius/dify/pull/2388.
