### ISSUE TITLE
Can the user upload attachments on the front end?

### ISSUE THREAD

**Issue by hponiang** [langgenius/dify#2326]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

Can the user upload attachments on the front end?such as when I want to upload an audio recording file. It should then invoke the audio-to-text function and, following the prompted keywords, organize the content accordingly.

**Comment by crazywoola** [comment]
Duplicate https://github.com/langgenius/dify/issues/1842
