### ISSUE TITLE
Using a different Chinese expression fails to match the context.

### ISSUE THREAD

**Issue by carllisicau** [langgenius/dify#2328]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

Using a different Chinese expression fails to match the context.
for example:
context input: 什么是互联网，answer：aaaa
ask: 什么是互联网，output：aaaa
ask: 介绍下互联网，output：bbbb
I hope everyone can provide output 'aaaa' for both queries.

**Comment by crazywoola** [comment]
They are different literally, so the output of embedding should be different as well. Also it's not a bug related to dify itself. It's related to the embedding model provider you choose.
