### ISSUE TITLE
私有化部署版本，角色为正常人的用户，也可以编排构建应用

### ISSUE THREAD

**Issue by tonglei100** [langgenius/dify#233]
Dify version: Self Host

## Steps To Reproduce

1. 邀请用户，角色为正常人，在数据库中配置好密码等
2.使用新账号登录，发现可以编排构建应用

## The current behavior
权限不正确

## The expected behavior
正常人角色不应该有构建应用权限

**Comment by iamjoel** [comment]
Hmm, can't reproduce. Let's double check if the inviter's role is indeed normal. If there's still an issue, let's take a look at the user's specific role: print the rule in `web/app/components/explore/index.tsx`
```js
const currUser = accounts.find(account => account.id === userProfile.id)
// add the follow line
console.log(currUser?.role)
setHasEditPermission(currUser?.role !== 'normal')
``` 
:thinking:

**Comment by tonglei100** [comment]
我拉取最新的镜像，重启，邀请用户时，默认是管理员（数据库中也是admin），我在页面上配置成正常人，查看数据库也是normal，但是这个用户登录进去，还是有权限构建应用的

**Comment by iamjoel** [comment]
No control over the permissions of building apps yet. The control is over the permissions of customizing apps in Explore: normal users can't customize apps.

**Comment by iamjoel** [comment]
It's a feature, not a bug.
