### ISSUE TITLE
设置为中文，但是一轮回答之后自动切英文

### ISSUE THREAD

**Issue by PhenixZhang** [langgenius/dify#2338]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

第一轮问答之前
![image](https://github.com/langgenius/dify/assets/26118845/7da460eb-540a-45ca-bc59-2ec76bad279e)
第一轮问答之后
![image](https://github.com/langgenius/dify/assets/26118845/47df7c59-4dd0-4ab3-80f6-55905014dcd5)

### ✔️ Expected Behavior

能够不自动中文变换为英文

### ❌ Actual Behavior

在设置为中文语言之后，第一轮问答结束自动切换成英文

**Comment by PhenixZhang** [comment]
@dosu-bot 所以我修改这个配置之后直接重启就可以对不？

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by prometheus-ct** [comment]
在最新版本0.9.1中该问题依旧存在
## 问题分析
我（非官方）通过debug发现 第一轮对话结束后调用api   /installed-apps/uuid:installed_app_id/conversations/uuid:c_id/name 为对话重命名 ，调用路径ConversationService.rename->cls.auto_generate_name->LLMGenerator.generate_conversation_name
此时出错报invokeerror()报错处：
``` python
try:
name = LLMGenerator.generate_conversation_name(
app_model.tenant_id, message.query, conversation.id, app_model.id
)
conversation.name = name
```
此处为dify程序调用默认大模型为对话重命名，结果默认大模型无法使用出错返回默认结果即英文（new conversation）相关代码
``` python
model_instance = model_manager.get_default_model_instance(
tenant_id=tenant_id,model_type=ModelType.LLM,
)
default_model = (
db.session.query(TenantDefaultModel)
.filter(
TenantDefaultModel.tenant_id == tenant_id,
TenantDefaultModel.model_type == model_type.to_origin_model_type(),
)
.first()
)
```
#### 解决方案
在数据库中修改表(TenantDefaultModel将mode_name改为正常能调接口返回结果的model name即解决
如我的大模型使用的是星火接口 默认是spark4改为官方provider中的yaml文件spark-ultra-xxx

#### 正确返回结果
左边的标题应为最后一次对话的总结结果，如最后一次询问的问题是“DND中龙裔由什么技能”，回答问题后标题应为
“DND龙裔技能”，事实上标题为第一次问题的总结

**Comment by MrWangChong** [comment]
请问这个问题解决了吗？我在0.15.3上面遇到了同样的问题

**Comment by zhaojc** [comment]
2025.3.16号依然有这个问题

**Comment by 1765659645** [comment]
2025.3.24号依然有这个问题

**Comment by 1765659645** [comment]
目前发现在设置-模型供应商-系统模型设置-系统推理模型中如果用deepseek-R1会存在这个问题，切换为非推理模型正常
