### ISSUE TITLE
Could we add a setting feature that allows administrators to configure download capabilities based on actual needs?

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#2340]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Can a download feature be added to the knowledge source? Could we add a setting feature that allows administrators to configure download capabilities based on actual needs?

![12](https://github.com/langgenius/dify/assets/21255047/0cb58486-ab05-44dd-adad-b597efa7c1cc)

**Comment by crazywoola** [comment]
For feature request please use the right template to fire an issue. 
#2287 As I said, we do not have a plan to this feature due to the data security for now.
