### ISSUE TITLE
The robotic assistant answers questions it is unfamiliar with, why does it still display the source?

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#2343]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- The robotic assistant answers questions it is unfamiliar with, why does it still display the source?
- Additionally, the response will also display the question that was asked.

![1](https://github.com/langgenius/dify/assets/21255047/260b5850-4d18-49cc-92ca-a7c96071ec71)

- The programming mode uses the expert mode, with the following related prompts.

![2](https://github.com/langgenius/dify/assets/21255047/a3ea5be4-6b34-4139-9c25-609775250943)

`Use the following context as your learned knowledge, inside <context></context> XML tags.

<context>
{{#context#}}
</context>

<context>
如果用户提出的问题中包含查询电量，请根据用户户号、起止日期调用{{dianliang_api}}工具进行用户用电量查询。
</context>

When answer to user:
- If you don't know, just say that you don't know.不显示引用。
- If you don't know when you are not sure, ask for clarification.不显示引用。
Avoid mentioning that you obtained the information from the context.
And answer according to the language of the user's question.`

**Comment by crazywoola** [comment]
Try turn this on, answer below this value won't be retrieved.
<img width="583" alt="image" src="https://github.com/langgenius/dify/assets/100913391/398dbf27-f5cf-44c4-b509-59c5670fa6c6">
