### ISSUE TITLE
Docker deployment self-hosted versus cloud

### ISSUE THREAD

**Issue by vontainment** [langgenius/dify#2350]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I know it's in the documentation you can set cloud or self-hosted when you launch for docker. If we're able to set it for cloud which means we have to use GitHub or Google login, what are the URLs we have to authorize for that? For JavaScript and call back?

**Comment by crazywoola** [comment]
For cloud version deployment, please contact business@dify.ai, it requires our business license to get technical support of that.

**Comment by vontainment** [comment]
Ah. You should probably put a note in the documents for that.
