### ISSUE TITLE
关于知识库现在支持上传png和jpg图片吗？

### ISSUE THREAD

**Issue by abbnm2017** [langgenius/dify#2357]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of requested docs changes

我现在使用的是docker部署，用的都是latest镜像，
上传的图片点击下一步之后，后端接口indexing-estimate报错，langchain/document_loaders/helpers.py  detect_file_encodings raise RuntimeError(f"Could not detect encoding for {file_path}") 我需要怎么解决这个问题

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
