### ISSUE TITLE
请教 npm install 报错

### ISSUE THREAD

**Issue by GXKIM** [langgenius/dify#2358]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

后端是部署在服务器，前端是部署在windows本地

报错如下：
<img width="574" alt="image" src="https://github.com/langgenius/dify/assets/125621025/e7048946-1bc7-4d72-81b2-309ccb26c9fa">

后端如下：
<img width="511" alt="image" src="https://github.com/langgenius/dify/assets/125621025/0fdca1b7-7faa-4402-b866-486e44ab71bd">

ps:使用requirements 部署的

**Comment by crazywoola** [comment]
This is a general network question.
