### ISSUE TITLE
How do I add speech-to-text and text-to-speech models when using xinference?

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#2359]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

How do I add speech-to-text and text-to-speech models when using xinference? Xinference already supports Image model and Audio model.

![20](https://github.com/langgenius/dify/assets/21255047/80a3714c-0f1f-4a4b-9936-60237ebc7517)

![21](https://github.com/langgenius/dify/assets/21255047/cdcffa9c-3fad-44f9-9db9-ef8a156e312d)

![22](https://github.com/langgenius/dify/assets/21255047/e55f9228-7a1f-4a8b-82f7-e0f351e0c684)

**Comment by crazywoola** [comment]
See https://docs.dify.ai/tutorials/model-configuration/xinference#starting-xinference for more details.

**Comment by andylzming** [comment]
@crazywoola Is the functionality of adding Image models and Audit models (including speech-to-text, text-to-speech) through xinference set to be implemented in the next version?

**Comment by takatost** [comment]
> @crazywoola Is the functionality of adding Image models and Audit models (including speech-to-text, text-to-speech) through xinference set to be implemented in the next version?

We might integrate these models in our spare time, not sure though. If you're interested, you can contribute to us and we would really appreciate it!

**Comment by leslie2046** [comment]
#3045
