### ISSUE TITLE
Yi34B's 8k context capability on dify doesn't work

### ISSUE THREAD

**Issue by PhenixZhang** [langgenius/dify#2360]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

The model I use is Yi-34B (8k), and the openai-api interface is packaged through dify. The result shows that it can only receive <=2k token length, but if only the openai-api interface can receive 4k token length, I would like to ask what is the specific reason?

Here is 2k output：
![image](https://github.com/langgenius/dify/assets/26118845/f9b6882a-200d-4cc9-b701-eff1a3329ea4)
Here is 3k output：
![image](https://github.com/langgenius/dify/assets/26118845/95b118fb-e27a-4a6a-9d2f-340c01cee1e8)
Here is 6k（openai-api） output：
![image](https://github.com/langgenius/dify/assets/26118845/9f646036-0a60-4eff-9e3c-9764fb8f02aa)

Can ensure that the parameter given to dify is 8K.

### ✔️ Expected Behavior

Ability to give Yi34B's 8k context capability on dify doesn't work

### ❌ Actual Behavior

can't to give Yi34B 8k context capability on dify

**Comment by takatost** [comment]
Have you tried the `OpenAI compatible API` model provider?

**Comment by PhenixZhang** [comment]
> Have you tried the `OpenAI compatible API` model provider?

Yes， This is the config screenshot
![image](https://github.com/langgenius/dify/assets/26118845/2b678bea-9763-4ca1-b617-eae71497dda6)

And using openai server directly without dify is no problem.

**Comment by takatost** [comment]
Can you try changing the `max_tokens` parameter to 4K or larger and see if it works?

**Comment by PhenixZhang** [comment]
> Can you try changing the `max_tokens` parameter to 4K or larger and see if it works?

Of course~ I set the maximum number of tokens to 8K at the beginning, respectively in the following two places:
![image](https://github.com/langgenius/dify/assets/26118845/c859808d-96a3-4efc-9266-e01eb431bd6f)
![image](https://github.com/langgenius/dify/assets/26118845/66ff30fa-6c5c-45ef-a179-c265e6f8e90b)

**Comment by soulteary** [comment]
refs to https://github.com/langgenius/dify/pull/2865, When the function is online, the API can be output in the interface and the online model can be used directly.

Or configure the API of the internal testing platform.
