### ISSUE TITLE
Upload Image getting Failed When testing

### ISSUE THREAD

**Issue by ganeshbehera** [langgenius/dify#2367]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

05:12:02 0|dify-web  | RangeError: Incorrect locale information provided
05:12:02 0|dify-web  |     at Intl.getCanonicalLocales (<anonymous>)
05:12:02 0|dify-web  |     at o (/app/web/.next/server/chunks/4438.js:43:7624)
05:12:02 0|dify-web  |     at l (/app/web/.next/server/chunks/3983.js:92:138887)
05:12:02 0|dify-web  |     at k (/app/web/.next/server/chunks/3983.js:92:137599)
05:12:02 0|dify-web  |     at em (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128334)
05:12:02 0|dify-web  |     at /app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140034
05:12:02 0|dify-web  |     at Array.toJSON (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143612)
05:12:02 0|dify-web  |     at stringify (<anonymous>)
05:12:02 0|dify-web  |     at eE (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131997)
05:12:02 0|dify-web  |     at eR (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132440)
05:12:02 0|dify-web  | [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.]

THis is docker log of web

### ✔️ Expected Behavior

It should upload image while chating with Google Vision or GPT 4 vision

### ❌ Actual Behavior

Image Upload Faily
![Screenshot 2024-02-03 at 2 45 45 PM](https://github.com/langgenius/dify/assets/53637426/af3b6ebf-acf7-4cfc-9752-d2eddd593fb9)

**Comment by iamjoel** [comment]
@ganeshbehera Can you provide specific reproduction steps? I can't reproduce the problem.
<img width="1227" alt="image" src="https://github.com/langgenius/dify/assets/2120155/7717fc2c-57d3-4117-bc9f-a11673abc7f2">

**Comment by ganeshbehera** [comment]
It doesn't expect Image more than 1mb, this is what i found!

**Comment by takatost** [comment]
> It doesn't expect Image more than 1mb, this is what i found!

Can you try https://cloud.dify.ai to see if the issue persists? I suspect it might be related to the upload limit of the external proxy during self-deployment.
