### ISSUE TITLE
The max tokens of a model deployed using Xinference can only be set to 2048

### ISSUE THREAD

**Issue by lileiseven** [langgenius/dify#2368]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Deploy model chatglm-6b-32k using xinference
2. In the Dify application, I use the model chatglm-6b-32k deployed by xinference

### ✔️ Expected Behavior

In orchestrate,  the parameter max tokens can be set to  32k

### ❌ Actual Behavior

In orchestrate,  the parameter max tokens can only be set to  2048

**Comment by Yeuoly** [comment]
This issue has already been fixed in #2336

**Comment by crazywoola** [comment]
> I have upgraded to dify 0.5.3, but the max token can still only be set to 2048.

> BTW, max_tokens is different from context_size, max_tokens specifies a maximum limit for the maximum current output length, not a context limit.

It means output tokens is 2k, the whole context window is 32k

**Comment by crazywoola** [comment]
@lileiseven Something like this.
<img width="694" alt="image" src="https://github.com/langgenius/dify/assets/100913391/35e85ce5-9815-4734-ba17-b19221590559">

**Comment by Yeuoly** [comment]
> > @lileiseven Something like this. <img alt="image" width="694" src="https://private-user-images.githubusercontent.com/100913391/307484410-35e85ce5-9815-4734-ba17-b19221590559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDM2MjIsIm5iZiI6MTcwODg0MzMyMiwicGF0aCI6Ii8xMDA5MTMzOTEvMzA3NDg0NDEwLTM1ZTg1Y2U1LTk4MTUtNDczNC1iYTE3LWIxOTIyMTU5MDU1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQwNjQyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjg5OWQxZDMzMGU3NGExZDk4ZDg0ZjczODdkZjdkOTc2MGIwOTVlZWYzODY3N2FlZTg2M2VkM2NlOTVhODNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PCoDRKvMaTbFnf8mpUJxoDWUub6f9zfF7OuEZOQcs3I">
> 
> Thanks. Maybe that works on ollama, but the xinference don't have such options, I can only set less than 2048 in dify's interface, is that a problem about xinference?

Yes, there is not a context size options in xinference, however, dify will try to fetch it from xinference directly, you can visit http://your_xinference_endpoint/v1/models/model_uid to see the context size of your model.
