### ISSUE TITLE
Customization Option Should Also Be Available In Self Hosted Version

### ISSUE THREAD

**Issue by MirzaAreebBaig** [langgenius/dify#2369]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

It would be great if the customization option will be available by default in the self hosted version.

### 2. Describe the feature you'd like to see

The customization option available in the cloud version after the plan purchasing it would be great if we have it in the self hosted version.

### 3. How will this feature improve your workflow or experience?

It will helpful for self hosted versions to have a there own branding for the agents.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by GarfieldDai** [comment]
Plz refer this link https://docs.dify.ai/user-agreement/open-source
The customization is enterprise feature. You can contact us business@dify.ai to inquire about licensing matters.
