### ISSUE TITLE
validate_credentials does not contain stream parameter when add Open AI  Compatible models

### ISSUE THREAD

**Issue by LucisBaoshg** [langgenius/dify#2372]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

I'm using the Jan app on my mac to start a local server of type open ai. When I use dify to add a model of type Open AI Compatible, it fails to do so because the validate_credentials method doesn't contain a stream: true.

### 2. Describe the feature you'd like to see

Consider optional stream parameter when adding models

### 3. How will this feature improve your workflow or experience?

On mac Jan handles the local api that launches the various models. dify is responsible for building the application, a scenario that is very useful to me and I hope to support

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by LucisBaoshg** [comment]
> `validate_credentials` is only used to validate credentials. The `_invoke` method is used to execute LLM calls. Currently, both streaming and normal blocking calls are natively supported. Where did you encounter the problem?

![image](https://github.com/langgenius/dify/assets/5937220/1433aaca-1b70-4a6a-bd60-e5b667ae15e6)
![image](https://github.com/langgenius/dify/assets/5937220/13b9f3ac-9d4b-4fb7-a8f6-71f204763523)

**Comment by LucisBaoshg** [comment]
The problem occurred while attempting to add an OpenAI Compatible model. The addition was unsuccessful due to the "dify" tool's use of the validate_credentials method for validation during the first step of the addition process. However, this validation request did not explicitly include the stream parameter. This omission resulted in the inability to correctly obtain model returns from certain API servers, such as the local API server provided by Jan, leading to a verification timeout and the consequent failure to add the model.

**Comment by takatost** [comment]
> > `validate_credentials` is only used to validate credentials. The `_invoke` method is used to execute LLM calls. Currently, both streaming and normal blocking calls are natively supported. Where did you encounter the problem?
> 
> ![image](https://private-user-images.githubusercontent.com/5937220/302232263-1433aaca-1b70-4a6a-bd60-e5b667ae15e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTUwNDEsIm5iZiI6MTcwNzI5NDc0MSwicGF0aCI6Ii81OTM3MjIwLzMwMjIzMjI2My0xNDMzYWFjYS0xYjcwLTRhNmEtYmQ2MC1lNWI2NjdhZTE1ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMDgzMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM3OGNkYTFhODk3ZTZlOTU1ZTIwNzE2NTFjM2U1Nzk4ZmQ4NzY4ZTRhY2RjYmZjZGNjZTAwZWU0MDkzZjI4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IGZ-IkTP5aEvCjkqrao3gQ3MFM8vnL1qhRQqka0Ursc) ![image](https://private-user-images.githubusercontent.com/5937220/302232323-13b9f3ac-9d4b-4fb7-a8f6-71f204763523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTUwNDEsIm5iZiI6MTcwNzI5NDc0MSwicGF0aCI6Ii81OTM3MjIwLzMwMjIzMjMyMy0xM2I5ZjNhYy05ZDRiLTRmYjctYThmNi03MWYyMDQ3NjM1MjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMDgzMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNkNTY0ZTZjZDVjN2FlN2FhM2JjOWQxOTM4MDUxMjFiMTUzMWMxMDk0Yjk2ZWNhMjQ0MDQ4MzY1Mjc5MTNiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i2v7rvJfmdA2A0HEEkT19Dvai8QTqSQupmuQbCeRIzY)

This looks like http://host.docker.internal:1337 cannot be accessed within the container. Can you please check if this possibility can be ruled out within the container?
