### ISSUE TITLE
Dify的文本生成应用是基于RAG检索生成增强的吗？

### ISSUE THREAD

**Issue by qianbaidu1266** [langgenius/dify#2380]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

我在 dify云服务的文本生成应用的专家模式编排中发现提示词工程如下：

`
Use the following context as your learned knowledge, inside <context></context> XML tags.

<context>
{{#context#}}
</context>

When answer to user:
- If you don't know, just say that you don't know.
- If you don't know when you are not sure, ask for clarification.
Avoid mentioning that you obtained the information from the context.
And answer according to the language of the user's question.
{{input}}
`

这里面的context 上下文将整个文档都引入进去了，与Langchain先检索向量库相关文档片段作为上下文的方式不太相同，而且，我使用过相同的文档作为知识库问答，Langchain的回答与文档的相关度也的确更高一些。

我有个疑问：Dify的文本生成应用是基于RAG检索生成增强的吗？如果不是，dify的文本生成应用和聊天应用的本质区别又是什么呢？毕竟这两种应用都可以应用知识库文档。

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542
