### ISSUE TITLE
Dataset API has breaking changes but not reflected in changelog

### ISSUE THREAD

**Issue by ipv6sq** [langgenius/dify#2381]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of requested docs changes

1. This is quite frustrating because the dataset api has changed dramatically without any notice in change log. Updating to 0.5.3 from 0.5.2
2. The API url mismatched, on the title it's saying `/datasets/{dataset_id}/segments/{segment_id}` but in the curl command it's `datasets/{dataset_id}/documents/{document_id}/segments/{segment_id}' `, and the curl command is right

<img width="1225" alt="image" src="https://github.com/langgenius/dify/assets/146745120/1d35d997-6ab5-4c3c-9ba9-9717fe27ee19">

**Comment by zxhlyh** [comment]
fixed. #2389
