### ISSUE TITLE
Using custom tool if response is more than  10 seconds the response is time out.

### ISSUE THREAD

**Issue by myrulezzz** [langgenius/dify#2382]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Created a custom tool  that calls a fastapi to fetch results for an oracle database.
For some dbs the response is generated after 10-15 seconds with curl command however from dify i get time out error.

### 2. Describe the feature you'd like to see

Be able to tune the response wait time for custom tools

### 3. How will this feature improve your workflow or experience?

Will give control when creating custom tool to add max wait time for response

### 4. Additional context or comments

If you have a fastapi which the response gets 10-15 seconds to return  and you add it as a custom tool in dify you will get most probably time out error in the response of the api

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by lanelam** [comment]
For those who are bothered by the same problem, I tried bot's suggestion to modify local file [api/services/tools_manage_service.py](api/services/tools_manage_service.py) but it did not work.

The right place is at [api/core/tools/tool/api_tool.py](api/core/tools/tool/api_tool.py), and the relevant code snippet is:

```python
    def do_http_request(self, url: str, method: str, headers: dict[str, Any], parameters: dict[str, Any]) -> httpx.Response:
        """
            do http request depending on api bundle
        """

        # ...

        # do http request
        if method == 'get':
            response = ssrf_proxy.get(
                url, params=params, headers=headers, cookies=cookies, timeout=10, follow_redirects=True)
        elif method == 'post':
            response = ssrf_proxy.post(url, params=params, headers=headers,
                                       cookies=cookies, data=body, timeout=10, follow_redirects=True)
        elif method == 'put':
            response = ssrf_proxy.put(url, params=params, headers=headers,
                                      cookies=cookies, data=body, timeout=10, follow_redirects=True)
        elif method == 'delete':
            """
            request body data is unsupported for DELETE method in standard http protocol
            however, OpenAPI 3.0 supports request body data for DELETE method, so we support it here by using requests
            """
            response = ssrf_proxy.delete(url, params=params, headers=headers,
                                         cookies=cookies, data=body, timeout=10, allow_redirects=True)
        elif method == 'patch':
            response = ssrf_proxy.patch(url, params=params, headers=headers,
                                        cookies=cookies, data=body, timeout=10, follow_redirects=True)
        elif method == 'head':
            response = ssrf_proxy.head(
                url, params=params, headers=headers, cookies=cookies, timeout=10, follow_redirects=True)
        elif method == 'options':
            response = ssrf_proxy.options(
                url, params=params, headers=headers, cookies=cookies, timeout=10, follow_redirects=True)
        else:
            raise ValueError(f'Invalid http method {method}')

        return response
```

Change `timeout=10` to a timeout you seem fits.
