### ISSUE TITLE
Increase the limit of tokens for openai compatible llms

### ISSUE THREAD

**Issue by myrulezzz** [langgenius/dify#2383]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

The limit of tokens for openai compatible llms is 2000. If you use a tool with your custom llm there is a possibility not to get the full response. Try mixtral8x7b and it seems that the response is not fully generated as i reach the maximum number of tokens which is 2000.

### 2. Describe the feature you'd like to see

Add functionality for the openai compatible api llms to increase the token limit to 4000-10000

### 3. How will this feature improve your workflow or experience?

i will get a full response if i use a custom tool with open source llm like mixtral 8x7b

### 4. Additional context or comments

In the properties of openai compatible llms should be a functionality where i can limit max_tokens to a bigger number. 4000-10000 i suppose

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
@guchenhe pls check this out

**Comment by takatost** [comment]
duplicate #2360

**Comment by guchenhe** [comment]
<img width="607" alt="image" src="https://github.com/langgenius/dify/assets/13230914/9e467310-e5a0-4707-9937-23efed200ed4">

You're free to modify both context length and max output token in the model config to suit your model. I tried mixtral on together.ai's endpoint and had it return 6000+ tokens no problem.

**Comment by myrulezzz** [comment]
Hi i deployed the model with vllm on runpod so localai accepts only 2000

**Comment by takatost** [comment]
> Hi i deployed the model with vllm on runpod so localai accepts only 2000

Are you using `localAI` provider configuration?

**Comment by myrulezzz** [comment]
Yes i do. There is no other option for vLLM endpoint

**Comment by takatost** [comment]
> Yes i do. There is no other option for vLLM endpoint

Can we try using the OpenAI Compatible API to integrate your model?

**Comment by Kinark** [comment]
Nope, the issue persists.

**Comment by vivatakethat** [comment]
the issue persists， cannot overload 4096
