### ISSUE TITLE
let LLM return JSON response

### ISSUE THREAD

**Issue by badbye** [langgenius/dify#2385]
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Yes. For optimal integration with other systems, it's crucial for large models to provide outputs in JSON format.

### 2. Describe the feature you'd like to see

Specify the output format on the webpage, the server will transform it into a Pydantic model. Utilize [Pydantic parser](https://python.langchain.com/docs/modules/model_io/output_parsers/types/pydantic) to add instructions into the prompt, and interpret the results into a structured output.

### 3. How will this feature improve your workflow or experience?

Via API requests, it delivers a preset JSON format that can be seamlessly integrated with any other system.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by badbye** [comment]
BYW, I already implemented it. Just need time to better test it.
![image](https://github.com/langgenius/dify/assets/3295865/a78ef4a6-7e28-4cbc-9f9a-f948f0e24361)

**Comment by takatost** [comment]
So you want the API response to be an object instead of a JSON string when using the OpenAI model parameter `response_format` as `json_object`, right?

**Comment by badbye** [comment]
> So you want the API response to be an object instead of a JSON string when using the OpenAI model parameter `response_format` as `json_object`, right?

No. Only a few models(gpt-4-1106-preview and gpt-35-turbo-1106) support the json mode. However, given an instruction, almost all the models are able to return in JSON format. 

To elaborate further, writing the corresponding prompt for the model to return in a specific JSON structure is a challenge. Comparatively, defining the JSON structure is simpler.

So, my idea is to allow users to define the structure on the web page, and we inject the corresponding prompt on the server side. Given a model that does not  support `json` mode, if it has a strong ability to follow instructions, it can return in the expected format.

**Comment by takatost** [comment]
> > So you want the API response to be an object instead of a JSON string when using the OpenAI model parameter `response_format` as `json_object`, right?
> 
> No. Only a few models(gpt-4-1106-preview and gpt-35-turbo-1106) support the json mode. However, given an instruction, almost all the models are able to return in JSON format.
> 
> To elaborate further, writing the corresponding prompt for the model to return in a specific JSON structure is a challenge. Comparatively, defining the JSON structure is simpler.
> 
> So, my idea is to allow users to define the structure on the web page, and we inject the corresponding prompt on the server side. Given a model that does not support `json` mode, if it has a strong ability to follow instructions, it can return in the expected format.

Since the model is able to return a JSON string following the instructions, why do we still need Pydantic conversion? What is your scenario and purpose? 😊

**Comment by badbye** [comment]
> > > So you want the API response to be an object instead of a JSON string when using the OpenAI model parameter `response_format` as `json_object`, right?
> > 
> > 
> > No. Only a few models(gpt-4-1106-preview and gpt-35-turbo-1106) support the json mode. However, given an instruction, almost all the models are able to return in JSON format.
> > To elaborate further, writing the corresponding prompt for the model to return in a specific JSON structure is a challenge. Comparatively, defining the JSON structure is simpler.
> > So, my idea is to allow users to define the structure on the web page, and we inject the corresponding prompt on the server side. Given a model that does not support `json` mode, if it has a strong ability to follow instructions, it can return in the expected format.
> 
> Since the model is able to return a JSON string following the instructions, why do we still need Pydantic conversion? What is your scenario and purpose? 😊

I already said that, `writing the instructions for the model to return in a specific JSON structure is a challenge, defining the JSON structure is easy`.

**Comment by takatost** [comment]
> > > > So you want the API response to be an object instead of a JSON string when using the OpenAI model parameter `response_format` as `json_object`, right?
> > > 
> > > 
> > > No. Only a few models(gpt-4-1106-preview and gpt-35-turbo-1106) support the json mode. However, given an instruction, almost all the models are able to return in JSON format.
> > > To elaborate further, writing the corresponding prompt for the model to return in a specific JSON structure is a challenge. Comparatively, defining the JSON structure is simpler.
> > > So, my idea is to allow users to define the structure on the web page, and we inject the corresponding prompt on the server side. Given a model that does not support `json` mode, if it has a strong ability to follow instructions, it can return in the expected format.
> > 
> > 
> > Since the model is able to return a JSON string following the instructions, why do we still need Pydantic conversion? What is your scenario and purpose? 😊
> 
> I already said that, `writing the instructions for the model to return in a specific JSON structure is a challenge, defining the JSON structure is easy`.

I understand what you mean. Pydantic can make JSON return more standardized and stable output. What I don't quite understand is when we need to return JSON results during a **Chat conversation**. I'm more inclined to implement this feature in the current Text Generate App. BTW, the Text Generate App will be upgraded to a Workflow format in the future, and the JSON output functionality can be a feature of the LLM component in it.

**Comment by takatost** [comment]
Anyway, thanks a lot for the idea! If you're interested, we can continue the conversation on WeChat: crazyphage.

**Comment by badbye** [comment]
> > > > > So you want the API response to be an object instead of a JSON string when using the OpenAI model parameter `response_format` as `json_object`, right?
> > > > 
> > > > 
> > > > No. Only a few models(gpt-4-1106-preview and gpt-35-turbo-1106) support the json mode. However, given an instruction, almost all the models are able to return in JSON format.
> > > > To elaborate further, writing the corresponding prompt for the model to return in a specific JSON structure is a challenge. Comparatively, defining the JSON structure is simpler.
> > > > So, my idea is to allow users to define the structure on the web page, and we inject the corresponding prompt on the server side. Given a model that does not support `json` mode, if it has a strong ability to follow instructions, it can return in the expected format.
> > > 
> > > 
> > > Since the model is able to return a JSON string following the instructions, why do we still need Pydantic conversion? What is your scenario and purpose? 😊
> > 
> > 
> > I already said that, `writing the instructions for the model to return in a specific JSON structure is a challenge, defining the JSON structure is easy`.
> 
> I understand what you mean. Pydantic can make JSON return more standardized and stable output. What I don't quite understand is when we need to return JSON results during a **Chat conversation**. I'm more inclined to implement this feature in the current Text Generate App. BTW, the Text Generate App will be upgraded to a Workflow format in the future, and the JSON output functionality can be a feature of the LLM component in it.

I see, look forward for the workflow.
