### ISSUE TITLE
The Tools Only Work With OpenAI Models

### ISSUE THREAD

**Issue by MirzaAreebBaig** [langgenius/dify#2387]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

The tools section used in Agent Assistant works only with OpenAI Models i have tried using other models like Claude then AWS titan & Llama but it seems like the tools only work with OpenAI Models.

### 2. Describe the feature you'd like to see

It would be great if tools functionality work with other models.

### 3. How will this feature improve your workflow or experience?

As per my scenario the OpenAI model costs are little bit high compared to other models would like to use other models with the toolset provided.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
Tools dose work with Almost all models, but the real behavior of LLM is related to `instruction` and align of model. For example, Claude is not trained to follow instruction but summary of texts, just try your instruction on Anthropic, you can see that Claude will not follow your instruction. Maybe each model should have a custom `react` prompt, but it brings a complex to normal user. BTW, you can search `langchain react` to learn about what's `react`

**Comment by MirzaAreebBaig** [comment]
Hello,
Thank you for your reply on this. But whenever i'm using other models the tools are not even loading or initializing to get the answer.

**Comment by Yeuoly** [comment]
You can ask Gemini Pro what time is it as a test just like this 
<img width="797" alt="image" src="https://github.com/langgenius/dify/assets/45712896/343f8b30-34cf-4650-a9d4-5be80e0f732e">
And see if there is a tool call

**Comment by MirzaAreebBaig** [comment]
Yes, i have tested this & its working no doubt, But its not working with custom tool which is created by OpenAI Schema JSON. That is only working with OpenAI Models.

**Comment by Yeuoly** [comment]
Maybe a detailed description of your custom tool is what you need, other models cannot understand what your tool is designed for and how to use, you can read the standard OpenAPI schema docs to find a field named "summary", it helps LLM understand your apis.
