### ISSUE TITLE
support moonshot

### ISSUE THREAD

**Issue by jialeicui** [langgenius/dify#2397]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Moonshot has launched its open platform, which performs better and has faster access speed in China compared to many other models

### 2. Describe the feature you'd like to see

support moonshot apiAPI

### 3. How will this feature improve your workflow or experience?

Improve model inference performance

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by ifsheldon** [comment]
+1

The APIs are said to be compatible with OpenAI's. See https://platform.moonshot.cn . And I've read the doc, it seems the APIs are a subset of OpenAI's:
* No tool calls
* No role for tools
* No vision
* probably more?
