### ISSUE TITLE
数据集格式应该是什么样的，能否给一些例子

### ISSUE THREAD

**Issue by muxuan1978** [langgenius/dify#24]
我尝试传了几个文件，包括TEXT和JSON，都提示【嵌入发生错误】

**Comment by takatost** [comment]
如果是本地部署的话，可能需要拉下新的代码，清空数据库 volume 目录重新部署一下，之前挂载的目录有问题，导致文件没有持久化。

**Comment by kokais** [comment]
非本地部署，直接在dify上创建的应用，也出现了这个问题，上传了了好几次，采用高质量索引方式，但是都嵌入发生错误，用了自己的appkey还是一样会发生错误，如果能看到错误日志就好了。

**Comment by takatost** [comment]
> 非本地部署，直接在dify上创建的应用，也出现了这个问题，上传了了好几次，采用高质量索引方式，但是都嵌入发生错误，用了自己的appkey还是一样会发生错误，如果能看到错误日志就好了。

线上向量数据库有些压力，目前已恢复，您可以重新上传试一下
