### ISSUE TITLE
自定义数据集解析时，嵌入报错

### ISSUE THREAD

**Issue by thetaworld** [langgenius/dify#240]
分隔符选择\n,最大长度选择1000
环境：非本地环境
![image](https://github.com/langgenius/dify/assets/36735442/365d3d90-60e4-42b7-b6f5-33e69a49df2e)

![image](https://github.com/langgenius/dify/assets/36735442/26a64d0c-f1ad-422a-be28-ea54034bbabe)

文本example:
{"prompt":"Company: BHFF insurance\nProduct: allround insurance\nAd:One stop shop for all your insurance needs!\nSupported:", "completion":" yes"}
{"prompt":"Company: Loft conversion specialists\nProduct: -\nAd:Straight teeth in weeks!\nSupported:", "completion":" no"}

**Comment by JohnJyong** [comment]
Sorry for affecting your use, the server has returned to normal
