### ISSUE TITLE
ollama-type model, the conversation is missing, it's stuck, and can't return complete content.

### ISSUE THREAD

**Issue by XJALYN** [langgenius/dify#2401]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="633" alt="image" src="https://github.com/langgenius/dify/assets/15723090/71213d17-fc57-44e9-a622-208a48bfb3da">

ollama-type model, the conversation is missing, it's stuck, and can't return complete content.

**Comment by takatost** [comment]
How about setting `max_tokens` parameter to 1000 or a bit larger and give it a try?
