### ISSUE TITLE
从0.2升到0.3 为什么没有探索模块？

### ISSUE THREAD

**Issue by yangzhu6263736** [langgenius/dify#241]
从0.2升到0.3 为什么没有探索模块？

**Comment by takatost** [comment]
You can try pulling the image first with execute `docker-compose pull` in the `docker` directory, then deploy it with `docker-compose up -d`

**Comment by takatost** [comment]
Sorry about that, our issue, and has been fixed in version 0.3.1, you can pull the code and redeploy it
