### ISSUE TITLE
OpenAI argues that "functions" are outdated, so why comment on "tools" and still utilize "functions" in code?

### ISSUE THREAD

**Issue by highjim** [langgenius/dify#2410]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

OpenAI argues that "functions" are outdated, so why comment on "tools" and still utilize "functions" in code?

code:api\core\model_runtime\model_providers\openai\llm\llm.py
![image](https://github.com/langgenius/dify/assets/108568777/15cf173c-ae05-4c8d-aad6-cbd38620f00d)

**Comment by takatost** [comment]
We encountered some unicode encoding issues with the model we're developing that supports `tool_calls`. So for now, we've decided to put the support for `tool_calls` on hold. We'll get around to fixing it when we have some free time.

**Comment by freefish1218** [comment]
> We encountered some unicode encoding issues with the model we're developing that supports `tool_calls`. So for now, we've decided to put the support for `tool_calls` on hold. We'll get around to fixing it when we have some free time.

Is it possible to raise the priority of this issue as it causes the 'Smart Assistant' to be completely unusable?

**Comment by Yeuoly** [comment]
Why would it causes the 'Smart Assistant' to be completely unusable? Is there a use cause, I would love to know the detail.

**Comment by freefish1218** [comment]
> Why would it causes the 'Smart Assistant' to be completely unusable? Is there a use case? I would love to know the details.

The problem is model related, if you use the 1106-preview you get all sorts of freaked out

**Comment by Yeuoly** [comment]
It seems that function calling does work with gpt-4-1106-preview in my case
<img width="609" alt="image" src="https://github.com/langgenius/dify/assets/45712896/52a67e85-56fd-4423-9a20-79cec725eaef">

do you mean gpt-4-vision-preview? If so, both tool calls and function calling are not permitted by gpt-4-vision-preview currently.
