### ISSUE TITLE
chating record displays math expressions incorrectly

### ISSUE THREAD

**Issue by bowenliang123** [langgenius/dify#2413]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.4

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Query: `123+456*789*789`

Without tool:
![image](https://github.com/langgenius/dify/assets/1935105/1c01cca9-c27d-4d14-8fa4-dca865164a39)

With tool: maths

![image](https://github.com/langgenius/dify/assets/1935105/d7c8f2dc-c0c6-412b-ad3f-11371888ebcf)

### ✔️ Expected Behavior

Shows the expression correctly in `123+456*789*789`.

**Comment by bowenliang123** [comment]
cc @crazywoola

**Comment by takatost** [comment]
This seems to be parsed as Markdown syntax. Maybe we can add a sentence in the instructions, saying that mathematical expressions should be represented using `inline code block`.
