### ISSUE TITLE
Minified React error #185

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#2416]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Create a Basic Assistant
- Select GPT 3.5 Turbo
- Make the GPT generate a large text

### ✔️ Expected Behavior

Text is beeing generated normally

### ❌ Actual Behavior

Text generation aborts after 1 second and the frontend throws the error [Minified React error #185](https://react.dev/errors/185?invariant=185)..

**Comment by perzeuss** [comment]
Obvious Issue is, that the model is so fast that `setState` is called too often. @dosubot suggest a few solutions to prevent it ;)

**Comment by perzeuss** [comment]
Looks like this is a critical bug, we also get this error with GPT 4. We have to roll back and migrate the db to 0.5.3.

**Comment by perzeuss** [comment]
In case someone needs to roll back too: run `flask db downgrade 380c6aa5a70d` to migrate to 0.5.3 db schema.

**Comment by zxhlyh** [comment]
@perzeuss I'm sorry about the problem, could you try the latest main branch and see if that solves your problem?

**Comment by perzeuss** [comment]
> @perzeuss I'm sorry about the problem, could you try the latest main branch and see if that solves your problem?

The issue has been fixed with one of the recent releases.
