### ISSUE TITLE
The document with the extension .doc cannot be parsed when uploading to the knowledge base

### ISSUE THREAD

**Issue by bigzws** [langgenius/dify#2421]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、上传.doc文档
2、文本分段和清洗，内部服务错误
3、尝试上传空的.doc文档，复现错误

**Comment by JohnJyong** [comment]
the type doc is not support in out file support range, pls use docx instead
