### ISSUE TITLE
WolframAlpha tool cannot work

### ISSUE THREAD

**Issue by bigzws** [langgenius/dify#2424]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The WolframAlpha tool has added an authorization prompt for an invalid appid. Clicking the button multiple times allows for the addition of authorization, but the func calling process cannot be used.
![微信图片_20240208170605](https://github.com/langgenius/dify/assets/45476210/a15aad08-17c8-4e7f-a5a6-d58fb181ac9c)

**Comment by Yeuoly** [comment]
Could you please check your network and appid? it seems that everything is going fine in my case
<img width="765" alt="image" src="https://github.com/langgenius/dify/assets/45712896/5da0a25f-1962-4306-824d-4802f764431f">

**Comment by crazywoola** [comment]
Seems fixed right now. If you encounter the same problem, please reopen this or dm me in wechat.
