### ISSUE TITLE
Hide Tools usage on Agent Assistant App

### ISSUE THREAD

**Issue by dkintgen** [langgenius/dify#2427]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I have an Agent Assistant App using both the GoogleSearch and Web Scraper tools.  Most times, the GoogleSearch pops up in the chat window of the response like so:

![image](https://github.com/langgenius/dify/assets/11706704/bd3d37c7-6aa7-4b36-8142-d2f30ddc3a90)

Is there any way to hide this so the end user does not know about the GoogleSearch?

**Comment by crazywoola** [comment]
No plan for this, but you still can send a feedback at https://feedback.dify.ai.
