### ISSUE TITLE
Increase the number of tools allowed in an agent app.

### ISSUE THREAD

**Issue by myrulezzz** [langgenius/dify#2429]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

From my understanding currently you are allowed to use maximum 5 tools in an agent chat app. Is there any specific reason?

### 2. Describe the feature you'd like to see

It would be nice to add more than 5 tools in the same app. Why not having 10 for example?

### 3. How will this feature improve your workflow or experience?

Liked the functionality of custom tools and creating a lot of integrations with apis.

### 4. Additional context or comments

If you want to want to hard use dify then its easy to want to use more than 5 tools in an app

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
The limit of tools is set to get a better performance of Agent, in the ReAct agent mode, a long tool list could lead a context pollution.

**Comment by myrulezzz** [comment]
Ok got it.Also when having a custom tool with a bearer token:
1. Do i need to define anything in the openapi swagger i upload for bearer authendication?
2. If i go in the ui to the api keys i enter Bearer in the name and key in the key value?

**Comment by Yeuoly** [comment]
Dify will ignore all authorization information in openapi/swagger schema, you can just fill it within the header value if you want to have a Bearer prefix like "Authorization: Bearer xxxxxx"

**Comment by myrulezzz** [comment]
So from the ui i am not able to do this? Because if you go in to custom tools in ui there is an api key option however if i put Bearer and the value xxxxxx it will not authendicate

**Comment by myrulezzz** [comment]
Also another suggestion could be to have maximum allowed tools to 10 for example but then allowed to be used for each question only 3 max.This way you add more functionality to the agent but you limit the number of tools used per wuestion

**Comment by Yeuoly** [comment]
> So from the ui i am not able to do this? Because if you go in to custom tools in ui there is an api key option however if i put Bearer and the value xxxxxx it will not authendicate

why not, you can just put the Bearer in the prefix of your api-key

**Comment by myrulezzz** [comment]
![Screenshot 2024-02-12 at 8 30 00 AM](https://github.com/langgenius/dify/assets/43094013/356ea661-daa1-4f3e-87f9-66f0c7bd5792)
So here what do i need to add in order to use bearer?
I have tiried adding Bearer in the key and the token in the value but still not working

**Comment by myrulezzz** [comment]
i have also tried with bearer and the token

**Comment by Yeuoly** [comment]
You can type `Authorization` in the  key field, and `Bearer XXXXX` in the value field

**Comment by Yeuoly** [comment]
> You can type `Authorization` in the key field, and `Bearer XXXXX` in the value field

XXXXX is your token

**Comment by myrulezzz** [comment]
Thank you
