### ISSUE TITLE
Docker Compose Install - ERROR: missing signature key

### ISSUE THREAD

**Issue by lhyphendixon** [langgenius/dify#2430]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm trying to install via docker compose following the instructions on the guide below. When I try to run docker-compose up -d, I am getting: ERROR: missing signature key .  I have ensured I have an adequate version of docker-compose.  I'm using CentOS, if that helps at all. 

https://docs.dify.ai/getting-started/install-self-hosted/docker-compose

### ✔️ Expected Behavior

To complete the install.

### ❌ Actual Behavior

ERROR: missing signature key

**Comment by crazywoola** [comment]
See this for details https://github.com/louislam/uptime-kuma/issues/3777

**Comment by NasirUddinNasir** [comment]
didn't work
