### ISSUE TITLE
Chunk Size

### ISSUE THREAD

**Issue by MrBrabus75** [langgenius/dify#2438]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

How reproduce ?

Use a Embedding with <1000 dimensions.

### ✔️ Expected Behavior

Working ?

### ❌ Actual Behavior

Error chunk size 0 - 1000
![Problem chunk size](https://github.com/langgenius/dify/assets/146331353/226d3809-c28a-4af3-8759-5776a6a1a754)

How upgrade chunk size limite ? 0-1000 to 0-4096 or higher ?

**Comment by takatost** [comment]
Usually we don't recommend setting such a large chunk size. Below 1000 is a relatively appropriate size for semantic search. I guess you might want the chunk content as LLM context to be as complete as possible. Maybe you can try the QA splitting mode. If you're not satisfied, you can continue modifying the chunk content. Use Q as the semantic searching content and A as the context for LLM.

**Comment by MrBrabus75** [comment]
@takatost  The problem is that the Q/A model is available only in Chinese and English, and not at all in French, even though my model is multilingual, which is a shame… (That feature would be nice, haha).

Then, I thought it would be good to increase the chunk limit for embeddings with large dimensions like Jina, Voyager, SFR Mistral mteb.

And finally, if I embed 50 documents (installation guides), and each document is divided into 50 chunks, the LLM struggles a bit to provide me with a detailed installation guide.

Thank you for your responses; I hope you will help me find a solution for these points.

**Comment by takatost** [comment]
> @takatost The problem is that the Q/A model is available only in Chinese and English, and not at all in French, even though my model is multilingual, which is a shame… (That feature would be nice, haha).
> 
> Then, I thought it would be good to increase the chunk limit for embeddings with large dimensions like Jina, Voyager, SFR Mistral mteb.
> 
> And finally, if I embed 50 documents (installation guides), and each document is divided into 50 chunks, the LLM struggles a bit to provide me with a detailed installation guide.
> 
> Thank you for your responses; I hope you will help me find a solution for these points.

QA mode does not currently support French, and the effect is also not as expected. What I mean is that we can indirectly create a knowledge base for QA mode by generating QAs, and then add or modify QA chunks based on this. The chunk limit of 1000 or less means that the search content (query) and smaller chunk (Q) have a higher semantic match, while the context of LLM can be extended to larger chunk.

In the future, within a month perhaps, we will provide the Parent Document Index mode to support the indexing mode mentioned above. For example, a sentence can be used as a chunk, and the paragraph or the content of the current page where this sentence is located as the Parent can be used as context for LLM. 

If this answer doesn't meet your expectations, could you please provide some more detailed scenarios for us to refer to? Thank you very much! 😊

**Comment by MrBrabus75** [comment]
> > @takatost The problem is that the Q/A model is available only in Chinese and English, and not at all in French, even though my model is multilingual, which is a shame… (That feature would be nice, haha).
> 
> > 
> 
> > Then, I thought it would be good to increase the chunk limit for embeddings with large dimensions like Jina, Voyager, SFR Mistral mteb.
> 
> > 
> 
> > And finally, if I embed 50 documents (installation guides), and each document is divided into 50 chunks, the LLM struggles a bit to provide me with a detailed installation guide.
> 
> > 
> 
> > Thank you for your responses; I hope you will help me find a solution for these points.
> 
> 
> 
> QA mode does not currently support French, and the effect is also not as expected. What I mean is that we can indirectly create a knowledge base for QA mode by generating QAs, and then add or modify QA chunks based on this. The chunk limit of 1000 or less means that the search content (query) and smaller chunk (Q) have a higher semantic match, while the context of LLM can be extended to larger chunk.
> 
> 
> 
> In the future, within a month perhaps, we will provide the Parent Document Index mode to support the indexing mode mentioned above. For example, a sentence can be used as a chunk, and the paragraph or the content of the current page where this sentence is located as the Parent can be used as context for LLM. 
> 
> 
> 
> If this answer doesn't meet your expectations, could you please provide some more detailed scenarios for us to refer to? Thank you very much! 😊

Thank you for your time and your very detailed response.

However, I have a few questions:
- 1. Is it possible by me or by you to modify the language of questions generated during Q/A? Are they generated by the LLM model?
- 2. Would you recommend that I wait for the PDI (Parent Document Index) mode, which will arrive in about a month?
- 3. I am embedding about 50 documents or more, which are quite long, one or two pages, and are chunked into several pieces. Should I stick with a limit between 512 and 1000 in size? Won't this limit the result of the responses by the LLM?

Thank you for everything you do.

**Comment by takatost** [comment]
1. Yeah, they are generated by LLM. It's not a perfect solution, but it effectively allows for separate editing of Q&A content in each chunk, achieving the desired result of retrieving Q and returning A. Currently, language setting is not supported, but we plan to redesign this feature in the future. For now, we'll stick with the current design. 
2. To enhance the experience, we suggest waiting for about a month. Of course, you can also try the solution mentioned in 1 for now, although it might be a bit cumbersome.
3. As mentioned in 1, the QA mode separates the retrieval and content given to LLM. Regardless of how it's divided, this is just a general approach. Based on the principles of embedding, manual intervention or LLM involvement is needed to split/summarize and create chunks for retrieval, while the content serving as LLM context could be its parent (e.g., the corresponding page or the entire document).

Hope this can help you! 🤗

**Comment by takatost** [comment]
cc @VincePotato @JohnJyong

**Comment by MrBrabus75** [comment]
okay i see, thanks you for all
