### ISSUE TITLE
Manifest for Qdrant version

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2443]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.5

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Local source code deployment using Qdrant,    docker.compose.middleware.yaml on line 59:  image: qdrant/qdrant:1.7.3
should be 
     image: qdrant/qdrant:v1.7.3

### ❌ Actual Behavior

Error response from daemon: manifest for qdrant/qdrant:1.7.3 not found: manifest unknown: manifest unknown

**Comment by takatost** [comment]
@JohnJyong pls take a look.

**Comment by JohnJyong** [comment]
we are using `langgenius/qdrant:v1.7.3` , this image is built by outself. @AndyMik90
