### ISSUE TITLE
dify_client python

### ISSUE THREAD

**Issue by myrulezzz** [langgenius/dify#2447]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I got from pypi dify_client. however there is no parameter for url. Is this client available only for dify cloud?

from dify_client import CompletionClient

api_key = "your_api_key"

# Initialize CompletionClient
completion_client = CompletionClient(api_key)

# Create Completion Message using CompletionClient
completion_response = completion_client.create_completion_message(inputs={"query": "What's the weather like today?"},
                                                                  response_mode="blocking", user="user_id")
completion_response.raise_for_status()

result = completion_response.json()

print(result.get('answer'))

**Comment by takatost** [comment]
Thank you so much for your suggestion! 😊
Regarding the dify client, we will be updating it in version 0.6 and it will support the ability to input a custom API URL.

**Comment by myrulezzz** [comment]
Also another question. Do you have any guidelines how to handle streaming response? As of now each chunk is coming under previous one.Is it possible to make it come as a normal sentence?

**Comment by myrulezzz** [comment]
Or in general how do you handle format of streaming response? Any library that could help?? Thanks

**Comment by takatost** [comment]
> Also another question. Do you have any guidelines how to handle streaming response? As of now each chunk is coming under previous one.Is it possible to make it come as a normal sentence?

If you're using Python `requests` package for the request, you can use `for chunk in response.iter_lines()` to get the content of each chunk and then parse it.

**Comment by myrulezzz** [comment]
Do you have a quick sample that it could help?

**Comment by crazywoola** [comment]
> Do you have a quick sample that it could help?

If you are dealing with LLM application nowadays, it's fundamental to learn how to deal with steaming response. For god's sake, please google it.

**Comment by myrulezzz** [comment]
Thanks i ll check it out :)

**Comment by bk1d** [comment]
> Thank you so much for your suggestion! 😊非常感谢你的建议！😊 Regarding the dify client, we will be updating it in version 0.6 and it will support the ability to input a custom API URL.关于 dify 客户端，我们将在 0.6 版本中对其进行更新，并支持输入自定义 API URL 的功能。

Would you please update python SDK to latest, thank you!

https://pypi.org/project/dify-client/
