### ISSUE TITLE
Cannot Add openai-api-compatible model

### ISSUE THREAD

**Issue by andykaufseo** [langgenius/dify#2448]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I start a LMStudio Server, which works fine (tested with other apps), but when i add the details into dify, i get this error 

An error occurred during credentials validation: HTTPConnectionPool(host='localhost', port=5522): Max retries exceeded with url: /v1/completions/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e5c2d45e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

tried both completion (http://localhost:5522/v1/completions) and chat end points.

running on windows, also tried on linux (via docker), same thing...

**Comment by takatost** [comment]
If you're deploying dify on your local machine using Docker, it's actually deployed within a Docker virtual machine and not on the host machine. You can obtain the IP address of the host machine as a substitute for `localhost` using the following command:
```
docker network inspect bridge | grep Gateway
```

**Comment by andykaufseo** [comment]
strangely enough, i get the same error even when i try to add a local llm to the cloud version (cloud.dify.ai) - i have a public api address, i click save, it hangs for a while (not like before when it got the error immediately) and then i get the same error.

also tried, it with the docker ip (the bridge ip - i hope that's the one), i click save, it doesn't get the error instantly, but it gets that time out error after a 10-15 seconds

**Comment by takatost** [comment]
"172.17.0.1" is your host machine's IP.

This error means that the connection was refused. You can use tools like `curl` or `Postman` to simulate API calls and check if there are any network configuration issues.

**Comment by andykaufseo** [comment]
still trying to figure this out. i have docker installed on wsl (also tried with docker desktop for windows but i deleted it).

i'm running lmstudio on windows (no linux version) - also tried with ollama on linux wsl, but i still get the same error.

should i try to curl from the local machine (windows terminal) to the docker container? or the other way around? or what should i be testing here?

i don't understand if the connection won't go through from docker to the local host or the other way around...

**Comment by a10k** [comment]
What worked for me is using http://host.docker.internal:1234 instead of http://locahost:1234
