### ISSUE TITLE
多账号注册失败

### ISSUE THREAD

**Issue by sunny0315** [langgenius/dify#245]
SELF_HOSTED模式下，当前只能注册一个账号吗？使用新邮箱填完注册信息后（localhost/install）跳转到登录页面（signin）,输入新注册的邮箱密码后提示“Invalid email or password”。

**Comment by JohnJyong** [comment]
In the privatized deployment mode, the multi-account mode is not supported for now, please look forward to subsequent version iterations~

**Comment by sunny0315** [comment]
好的，感谢回复！

**Comment by dsazdf312** [comment]
> 私有化部署模式下，暂时不支持多账号模式，请期待后续的版本迭代~

大佬 请问现在支持了吗  或者说手动插表 需要插入哪几张表
