### ISSUE TITLE
RAG & Workflow & Knowledge Website

### ISSUE THREAD

**Issue by nguyenthanhtien** [langgenius/dify#2455]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Need create agent with workflow.
Need create Bot with multi agent.
Need add knowledge diverse data sources.

### 2. Describe the feature you'd like to see

Like Coze: 
- Workflow empowers users to process intricate task flows with a set of workflow nodes such as Large Language Models (LLM), codes, and conditions. Regardless of your coding expertise, its intuitive drag-and-drop interface facilitates workflow creation.
- Multi agents: run multiple tasks in one bot. The multi-agent mode allows you to handle complex user tasks. With multi-agent mode, you can add multiple agents, each of which is an intelligent entity capable of performing a specific task independently. And you can configure the connection between each node to design how each task is performed.
- Add knowledge from Website: Add online web content to the knowledge base via a specified URL.

### 3. How will this feature improve your workflow or experience?

Helpful for creator to create agent & bot.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We are working on this already. :) Please stay tuned.

**Comment by nguyenthanhtien** [comment]
@crazywoola when dify completed that features? I hope see that soon.
