### ISSUE TITLE
设置文心一言api key和Secret Key报错

### ISSUE THREAD

**Issue by jamesliu668** [langgenius/dify#2456]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

在模型供应商页面设置文心一言的api key和Secret Key报错。

### ✔️ Expected Behavior

设置正确

### ❌ Actual Behavior

返回错误信息如下：
Credentials validation failed: Failed to get access token from Baidu: HTTPSConnectionPool(host='aip.baidubce.com', port=443): Max retries exceeded with url: /oauth/2.0/token?grant_type=client_credentials&client_id={MY-api-key}&client_secret={my secret key} (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e635bfd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by jamesliu668** [comment]
版本写错了，我现在用的是最新版本，0.5.5

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by fuwj1994** [comment]
How to configure and test a proxy?
