### ISSUE TITLE
 how to use Xinference's rerank models in Dify ?

### ISSUE THREAD

**Issue by whoamiWo** [langgenius/dify#2457]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I use  Xinference's rerank models in Dify ,It not working
 "[xinference] Error: Failed to get the model description, detail: Not Found"
![BFC57F13-53E1-428e-85C1-5C629ACBFEF9](https://github.com/langgenius/dify/assets/160295799/f8d1be13-8f93-406b-a4bb-9b57fb9f1557)
but in console it working! why?
![9CB4F2A4-D21C-4a53-A82B-1B876BEEA3F4](https://github.com/langgenius/dify/assets/160295799/c00084bf-63d0-4acb-9aad-971fc4c9942e)

**Comment by whoamiWo** [comment]
yes, a public  IP  address

**Comment by whoamiWo** [comment]
> Is the masked ip address a public ip address?

yes , a public ip address

**Comment by whoamiWo** [comment]
XINFERENCE_MODEL_SRC=modelscope  /usr/local/bin/python38/bin/xinference-local -H 0.0.0.0

**Comment by Yeuoly** [comment]
`model_uid` should not contains "/". Xinference use `/v1/models/{model_uid}` to get the detailed information of a model, however, it leads to an incorrect path for retrieving the model, such as `/v1/models/chatglm` becoming `/v1/models/chat/glm`, removing "/" from your `model_uid` is a way to solve this, we will fix it in next release also.
