### ISSUE TITLE
Call order regarding "tools" and "contexts"

### ISSUE THREAD

**Issue by HelloEveryonehh** [langgenius/dify#2458]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

我的使用场景如图所示，我的知识库里面第一条就是我提问问题的答案，但是模型仍然是调用了工具来进行搜索
![image](https://github.com/langgenius/dify/assets/110333012/bb4f51dd-ae49-44ef-89a7-2c2858e890bc)
![image](https://github.com/langgenius/dify/assets/110333012/630dfd54-ed3c-40e0-832b-3515967d0883)
How does the model distinguish when to call the context from the tool？

**Comment by Yash-1511** [comment]
Hey @HelloEveryonehh, you can solve this problem in this ways. First,  write clear and crystal description of your knowledge base. Second, use prompt engineering to know when to use tools or your own knowledge. Using both methods should help you get the result you want.

- [How to write good knowledge description](https://docs.dify.ai/features/datasets#how-to-write-a-good-knowledge-description)
- [Agent Assistant prompt guide](https://docs.dify.ai/user-guide/creating-dify-apps/prompt-engineering/agent-assistant)

**Comment by crazywoola** [comment]
This highly depends on your description and the way you describe the knowledge. Also it depends on llm itself. If a llm is not that good to understand or misunderstand your question. It will use tools or knowledge base to answer your question randomly.
