### ISSUE TITLE
Ollama based models are "not" providing full tokens (stops around 150 or so)  on self-hosted docker(dify) based environment

### ISSUE THREAD

**Issue by ashmanpan** [langgenius/dify#2461]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. run models on Ollama , locally on Mac M3 
2.  Create app use Ollama based model, I used llama2
3.  use 2 model debugging view, use chat-gpt-4 as 2nd model to compare
4. set max tokens on both models as 4096  
5. ask questions which will relatively long answers, you will see ChatGPT giving full details of the question in the answer but Ollama based locale model stooped after 150 or so tokens 

### ✔️ Expected Behavior

Ollama based model also should give full long response like ChatGPT , till it reaches to max token 4096 

### ❌ Actual Behavior

Ollama based model using dify is stopping in between the response after 150 or so tokens . 

I tried Ollama same model on the terminal with the same questions and i can see full response from the model. it's not Ollama issues.

**Comment by ashmanpan** [comment]
detaiils and snpshot is avilable here - https://discord.com/channels/1082486657678311454/1206116751801327616

**Comment by takatost** [comment]
You can try adjusting the `Num Predict` model parameter to the appropriate tokens size for generating texts.

**Comment by ashmanpan** [comment]
I have already deployed dify on docker containers, which specific container this file has, how can I edit, or what's the way to change this? 

 Other question, why this kind low number as default , this is local llm no one is going to change because of the large no of tokens so why ?

**Comment by ashmanpan** [comment]
<img width="612" alt="image" src="https://github.com/langgenius/dify/assets/7510337/85e4fd87-f348-40e4-8165-12eb901ef63b">
<img width="1267" alt="image" src="https://github.com/langgenius/dify/assets/7510337/6cbeb377-3d2b-4e68-b931-e67d297881f0">

**Comment by ashmanpan** [comment]
below snapshot are after upgarde to 0.5.5

<img width="1927" alt="image" src="https://github.com/langgenius/dify/assets/7510337/67d9ffa1-6131-4816-bb9f-6985d4480265">

**Comment by ashmanpan** [comment]
<img width="1859" alt="image" src="https://github.com/langgenius/dify/assets/7510337/c750ce7d-93dd-47d5-b987-a862e2b65795">

**Comment by takatost** [comment]
<img width="597" alt="image" src="https://github.com/langgenius/dify/assets/5485478/95059438-9120-4a49-adac-472f83fe672f">
This number is set according to the default values provided in the Ollama API document, you can change this value here.

**Comment by ashmanpan** [comment]
Issue resolved . i will close soon after some testing

**Comment by akhilmadhumenon** [comment]
When we tend to set a limit on num_predict, the sentences get cut off mid way, and the model does not complete the sentence. How can we ensure that it will complete the sentence whilst maintaining the maximum token limit?

**Comment by sivertheisholt** [comment]
> When we tend to set a limit on num_predict, the sentences get cut off mid way, and the model does not complete the sentence. How can we ensure that it will complete the sentence whilst maintaining the maximum token limit?

Did you figure out this? I have the same problem, cutting off mid sentence when setting the num_predict to 64.
