### ISSUE TITLE
The configured knowledge base has already been referenced in the prompt as context, why doesn't the system display it as linked to the application?

### ISSUE THREAD

**Issue by koulas** [langgenius/dify#2462]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

The configured knowledge base has already been referenced in the prompt as context, why doesn't the system display it as linked to the application?
![image](https://github.com/langgenius/dify/assets/2045443/d9222054-8b15-4026-aac3-88dce30e5a27)
![image](https://github.com/langgenius/dify/assets/2045443/bfa3618c-7260-4a01-82bc-4bd00a30ce12)

**Comment by takatost** [comment]
@JohnJyong pls check it out.

**Comment by JohnJyong** [comment]
@koulas it has fixed by #2479 ，thanks for your feedback
