### ISSUE TITLE
Please increase the limit of tools we can use to min 10 plus if possible give us option to test and use higher number of tools without any limits 

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2464]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

only 5 tools are not sufficient, i have read one comment regarding this only but he closed his issue so i am opening it myself, please give user the chance to select more number of tools. DO NOT PUT LIMITATION ON IT EVEN IF PERFORMANCE MIGHT NOT BE GREAT. just put disclaimer that if you use more tools you might see tools conflict with each other and provide bad response, So its upto user if he wanna try more tools or not donot put limits by yourself because with time i believe we will understand what things and in what way conflict and how we can prevent that so yeah i hope in next upcoming version you will remove those limits and i know its not tough thing to remove those limits from code base but still the way i told you to handle this is much better then limiting users  :-)
Again Thankyou very much for this awesome solution  

### 2. Describe the feature you'd like to see

:-)

### 3. How will this feature improve your workflow or experience?

:-)

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
duplicate https://github.com/langgenius/dify/issues/2429

> The limit of tools is set in order to get a better performance of Agent, in the ReAct agent mode, a long tool list could lead a context pollution.

**Comment by HakaishinShwet** [comment]
@crazywoola i mentioned it is duplicated but this issue is solved yet i have most recent version and in that i can use only 5 tools at a time not more than that and the one this is duplicated of is also closed by user idk why so please reopen it and increase the limit

**Comment by crazywoola** [comment]
I do quote one thread.

> The limit of tools is set in order to get a better performance of Agent, in the ReAct agent mode, a long tool list could lead a context pollution.

**Comment by Yeuoly** [comment]
done. #2497
