### ISSUE TITLE
The code extension using "schema.json" with type select, the "options" is invalid for using dropdowns in the frontend.

### ISSUE THREAD

**Issue by onlywangyh** [langgenius/dify#2466]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

langgenius/dify-web   latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

this is schema.json:
{
    "label": {
        "en-US": "Weather Search",
        "zh-Hans": "天气查询"
    },
    "form_schema": [
        {
            "type": "select",
            "label": {
                "en-US": "Temperature Unit",
                "zh-Hans": "温度单位"
            },
            "variable": "temperature_unit",
            "required": true,
            "options": [
                {
                    "label": {
                        "en-US": "Fahrenheit",
                        "zh-Hans": "华氏度"
                    },
                    "value": "fahrenheit"
                },
                {
                    "label": {
                        "en-US": "Centigrade",
                        "zh-Hans": "摄氏度"
                    },
                    "value": "centigrade"
                }
            ],
            "default": "fahrenheit",
            "placeholder": "Please select temperature unit"
        }
    ]
}

### ✔️ Expected Behavior

![image](https://github.com/langgenius/dify/assets/16820412/54f95ba4-cdb1-41f2-8f83-8408d747db2f)
Options can choose Celsius or Fahrenheit.

### ❌ Actual Behavior

Options is gray and use the defaule value fahrenheit

**Comment by Yeuoly** [comment]
which version are you using? it seems that it's an old one.

**Comment by onlywangyh** [comment]
> which version are you using? it seems that it's an old one.

This issue still exists in version 0.5.5

**Comment by zxhlyh** [comment]
fixed. #2490
