### ISSUE TITLE
Please add serper as builtin tool which is google serp alternative but can be used for free for some limit and is much cheaper than serp this is second time i requesting for it btw plus educate users with PROPER STEP BY STEP GUIDE OR VIDEO TUTORIAL about each and everything Please

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2469]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

and if possible make tutorial of it like how we can create the tool with serper and langchain serper documentation and use it to give us better and practical idea/example which is NEEDED so we know how to create tool and convert to openai schema and run ourself because there are alot of tools supported by langchain already and people will be able to use the tutorial and use accordingly if you dont plan to add all supported tools in dify or you all are working on something other than tools and because of it there would be delay in tools update so till than instead of getting frustrated, people can built locally and use some other tools supported by langchain.
Tutorial with video is necessary OR very big written tutorial with ALL steps and IN MOST EASIEST WAY POSSIBLE then only it will solve the purpose. Rest i am attaching the source of serper and langchain integration with it now i hope you will do something about this asap because i am tbh not satisfied with the amount of tools we have plus want to add more but havent worked on open ai schema and stuff so dont know,i also have created python langchain mini programs to test stuffs  and i do know about litellm and it helps in running local server for python program and with this i guess we can create api server and feed the link to dify this is my rough idea but i still need perfect tutorial to perfectly understand and apply ATLEAST ONE TIME so that further i can add more, So with awesome foss project comes big responsibility to educate user about some advance things/new things which max have not practically done so this is my second time request i hope this doesnt go in vain and tbh  you wont need too much time for this because you already have implemented it and have tested it and similar thing is what i am asking for but in proper turorial step by step way so that it makes things easier :-))    
serper - https://serper.dev
langchain serper - https://python.langchain.com/docs/integrations/tools/google_serper

### 2. Describe the feature you'd like to see

:-)

### 3. How will this feature improve your workflow or experience?

:-)

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
The tutorial you are looking for is in [/api/core/tools/README.md](https://github.com/langgenius/dify/blob/main/api/core/tools/README.md), you can build a tool yourself by following this document.
As for a video tutorial, we are considering making one. btw, converting tools of langchain into dify format is what we are working on, you can look forward to it.
Thanks for your suggestions!

**Comment by HakaishinShwet** [comment]
@Yeuoly thankyou very much, will be waiting for proper step by step video with practical implementation on it and unlike some other project videos which just want to create shortest video possible to show things and skipping steps because of which user has to struggle alot to make it work if he has low experience (which is case for many) and is not nice experience by any mean, i hope this thing doesnt happen with this project. All the best to team
