### ISSUE TITLE
更新代码后出现大量前端异常

### ISSUE THREAD

**Issue by lemon-simple** [langgenius/dify#247]
<img width="1424" alt="image" src="https://github.com/langgenius/dify/assets/28141497/b8be871e-9863-403a-9d7a-ddc71b72841e">
更新代码后启动，大量异常报错，暂时找不到原因，接口数据确认了都是json格式。

**Comment by lemon-simple** [comment]
<img width="1440" alt="image" src="https://github.com/langgenius/dify/assets/28141497/9be2b96b-2dde-4b87-b17e-4ee17b9c40cf">

**Comment by iamjoel** [comment]
Try to restart nginx？docker restart docker-nginx-1

**Comment by takatost** [comment]
> Try to restart nginx？docker restart docker-nginx-1

If it still doesn't work, you can check the `api` service logs to locate the problem: `docker logs -n 200 docker-api-1`
