### ISSUE TITLE
[just question] web scraper not working for http based urls?

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2471]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

any reasons for scraper not working on http websites :-)

**Comment by Yeuoly** [comment]
Which website you are trying to crawl? could you please provide me with a reference link to it? so that I can have a test.

**Comment by HakaishinShwet** [comment]
http://www.jamessawyer.co.uk/pub/gpt_jb.html this was the website i was trying to see if scraper can fetch info and it did give certificate error

**Comment by Yeuoly** [comment]
Which model are you using? It does work in my local environment, the model you are using may transform the schema from http into https.
<img width="807" alt="image" src="https://github.com/langgenius/dify/assets/45712896/ffeb85b1-cd63-4bc9-8fb4-0378a40a9970">

**Comment by HakaishinShwet** [comment]
@Yeuoly i was using google gemini so i guess this is model issue. Thanks for testing and telling the cause of issue. If you want to add any more information from testing regarding this issue then you can add here in comment else you can close this issue :-)

**Comment by Yeuoly** [comment]
Thanks for your reports.
