### ISSUE TITLE
Please donot blindly mark as duplicate and close the issue of users, atleast read the full message and then take action accordingly

### ISSUE THREAD

**Issue by HakaishinShwet** [langgenius/dify#2474]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

i actually created issue #2464 in which i requested to increase the issue of max tool allowed to use to in dify to min 10 or limitless and i did provide one solution/idea there too that if you have feel like using more tool will create issue for better content generation then just use put  disclaimer or mini menu or text or mini icon in which if user hovers this text shows -  that you can use more than 5 tools but quality of content generation might not be good or conflicts between tools might arise if you use more than 5 so test and use yourself accordingly. So it will depend on user if they wanna test and try and make it work according to there own usecases, so this approach will be much better than completely limiting users.
This was my suggestion which i put there and i have literally mentioned in that issue i created yesterday #2464 that i have seen one comment regarding same issue which was #2429 but if you read the chats of it carefully it was closed by the user and chat was completely off to another topic so practically that issue was not resolved by team and was just closed by user and i have recently updated to latest version and those limits still present and So i recreated that issue so that you will work on it and what i got for that was blind response which i wasnt expecting after contributing in different way for more than a month.you all are working great tbh and number issues solved are pretty big and with consistency you all are doing which is big and so you want to minimize max number of issue which is 100% fine BUT please atleast read the full message first rather than directly seeing one word or sentence which reminds you of similar issue and you quickly mark that as duplicate and close the issue.i knew that this might happen and that is why i mentioned in that message start that i am recreating issue based on previous issue but you didnt read even that.
This is not something that i expect from a great team who have till date responded very well to my issues,suggestion,ideas,bug reporting.Mistakes happen sometime and its absolutely fine as long as you understand and improve ;-))
thats all from my side

**Comment by takatost** [comment]
@crazywoola Please wait until the issue is confirmed before closing it, this is basic respect. 😊

**Comment by crazywoola** [comment]
Proper use of punctuation and capitalization is respectful @HakaishinShwet

**Comment by HakaishinShwet** [comment]
@crazywoola no offence but you are trying to prove your actions right by saying this, I always try my best to explain the issue or suggestion or bug or anything I get you can see in past messages too and In many projects I do because I am not here to summarise thing but to explain you in detail about what I think or feel about any feature or other things of project and that is why I try to ask in detail or answer in detail, the issue I created previously which you blindly closed as duplicate, in that issue only only 159 words were used simply and in starting of that message I mentioned that it was kinda duplicate issue and why I created it and it was your fault to not read so accept your mistake instead of saying keep short,use punctuation and other thing. You as a dev must actually be very happy with detailed response so that you can easily understand what problem is there and what can be possible solution or how things can better implemented instead of reading short message and thinking alot that what the hell user actual want and drag conversation for days to understand that conversation. I hace tried my best to use as much as punctuation possible and I am here to create issue or suggestion or report bug I am not here to show off perfectly formatted text,I do try my best tho to seperate replies with , or . And use sometimes capital words.There is nothing disrespectful if user is not using perfect English or punctuations so don't bring that thing here and accept your fault I tried to be as polite as I can be while creating this issue and you are trying to find unnecessary thing to blame me.

**Comment by crazywoola** [comment]
Sorry for this mistake I made. Sincerely apologize for this behavior. 
You are right about you are trying to make some suggestions and trying to describe what you are encountering.
And 👆 is my true apology.

But I still suggest you can use some format to make things clear. I created the PR template at the first place and give them some basic categories, I am trying to gather information as much as we can and help us to identify and solve the questions and suggestions quicker. (as you can see the validation of each item is marked as **required**).

For example:

###  Describe the feature you'd like to see

Increase the tools length up to 10, and give a disclaimer message.

### How will this feature improve your workflow or experience?

Blah blah.

There are very few of us so we need to save as much time as possible.

**Comment by guchenhe** [comment]
Hey @HakaishinShwet, thanks so much for the input all along. I'm glad the issue is resolved and appreciate your continued patience in communicating with our team, as we're figuring things out as well. 

But I do want to make clear of our expectations moving forward. While we care about suggestions and community feedback, our time is precious. As much as you seem to make the case for it, it is not our responsibility to follow up and reply on every issue sent our way, as we need to evenly distribute attention among issues and community members. 

Sorry for not having established this sooner. From now on, please do follow the issue template and break down your message into digestable paragraphs to reduce the burden on those trying to help and maintain the project. If you have trouble with spelling or writing in general, here's a [dify bot](https://udify.app/chat/MK2kVSnw1gakVwMX) to use that does the formatting for you. This is the best way to ensure that we read your issue and handle it swiftly. It also demonstrates respect.

Thanks. Open to more questions if you got them. 

> @crazywoola I 100% understand your point about templates and about time saving thing and that too i mentioned in my messages previously that you all are doing great work as team to minimize many issues and because of that you are able to solve more and more issues and i appreciate that, This template solution is good for those who are too specific about things/bugs/features like what they want they simply write and thats all BUT exceptions are always there and i come under that and in my case no template actually satisfy my need because i connect my big messages with problem,example if possible,possible solutions,plus my past experience on something which can help in resolving that issue or to make you better understand this is my 100% priority because i cant be 100% active in github to reply back so i try to explain max things in one single message and then per day i follow up issue if needed.This is how i work but dont worry i will try to change myself little bit.Message will be one section only but i will try my best to split in my own way with spaces and use capital letters for before major things. But still i Request you as open source contributor to never ignore message no matter how big it is and even if it is little bit unformatted because person has spent his time to think in order to make you explain and make things easy for you at the end, he could also have written things in some words and leave as max do and again broken conversation issue arise and waste your precious time but he is spending time only for you as dev to get better idea and for this awesome project so please donot ignore message or mark message as duplicate without reading atleast some part of it.I know it is tempting to do this to reduce number of issues but see because of that this whole conversation happened anyways lets end this conversation here. All the best for future development :-))

**Comment by HakaishinShwet** [comment]
"it is not our responsibility to follow up and reply on every issue sent our way, as we need to evenly distribute attention among issues and community members."  @guchenhe if this is not yours or i should say team's responsibility to followup on issues to improve this project and your product which are created by contributors in hope to improve the solution or to make it different/unique from others so that it benefits whole community plus "Your startup" so that project earn more and develop more then who's responsibility is this may I know please? And this thing you mentioned regarding followup has nothing to do with this issue or the mistake he made of not even trying to read start of the line and he accepted it clearly too and we mutually closed the conversation and I mentioned that I will try to improve little bit then why drag this conversation further? I said that i don't always create issues in the way normal user do and so no template satisfy my need and I write in flow about whatever I am thinking about issue or example or possible solution BUT I always do give major hint about problem or anything else in title of issue so that you can easily assign someone to that who will read my whole point and then respond back if there are any further queries regarding that, You see things from different perspective you think it's "time waste in reading big message in which contributor tried his best to explain things and give possible solution or idea because he believes in not just opening issues like max do but also provide some possible solution or idea or example etc If possible because he has experience of many foss project which can help Dev's to solve or create something and he tried to write in detail so that no further time Is wasted on either broken conversations on daily basis in which dev is trying to understand what user want or to save time on thinking and exploration of how things can be better implemented with all possible case".I can try to use the bot you mentioned to format but if you simply see big messages as time waste and with formatted message you will just pick specific part and read and assign anyone and will ignore other part of message and won't reply/discuss about anything he discussed in his big message and in this way if you wanna save time then what's the point of writing big message and is it not disrespectful to contributor? I think I was in wrong place trying to contribute in any possible way,I am really sorry for that.
I still respected for what was asked from me and that's why I didn't deny but said I will try to improve in whatever way I can while writing my message and after this I am getting this kind of reply.
Fine by me Thankyou very much, This will be last issue from my side.
All the best for future

**Comment by guchenhe** [comment]
> "it is not our responsibility to follow up and reply on every issue sent our way, as we need to evenly distribute attention among issues and community members." @guchenhe if this is not yours or i should say team's responsibility to followup on issues to improve this project and your product which are created by contributors in hope to improve the solution or to make it different/unique from others so that it benefits whole community plus "Your startup" so that project earn more and develop more then who's responsibility is this may I know please? And this thing you mentioned regarding followup has nothing to do with this issue or the mistake he made of not even trying to read start of the line and he accepted it clearly too and we mutually closed the conversation and I mentioned that I will try to improve little bit then why drag this conversation further? I said that i don't always create issues in the way normal user do and so no template satisfy my need and I write in flow about whatever I am thinking about issue or example or possible solution BUT I always do give major hint about problem or anything else in title of issue so that you can easily assign someone to that who will read my whole point and then respond back if there are any further queries regarding that, You see things from different perspective you think it's "time waste in reading big message in which contributor tried his best to explain things and give possible solution or idea because he believes in not just opening issues like max do but also provide some possible solution or idea or example etc If possible because he has experience of many foss project which can help Dev's to solve or create something and he tried to write in detail so that no further time Is wasted on either broken conversations on daily basis in which dev is trying to understand what user want or to save time on thinking and exploration of how things can be better implemented with all possible case".I can try to use the bot you mentioned to format but if you simply see big messages as time waste and with formatted message you will just pick specific part and read and assign anyone and will ignore other part of message and won't reply/discuss about anything he discussed in his big message and in this way if you wanna save time then what's the point of writing big message and is it not disrespectful to contributor? I think I was in wrong place trying to contribute in any possible way,I am really sorry for that. I still respected for what was asked from me and that's why I didn't deny but said I will try to improve in whatever way I can while writing my message and after this I am getting this kind of reply. Fine by me Thankyou very much, This will be last issue from my side. All the best for future

"if this is not yours or i should say team's responsibility to followup on issues to improve this project and your product which are created by contributors in hope to improve the solution or to make it different/unique from others so that it benefits whole community plus "Your startup" so that project earn more and develop more then who's responsibility is this may I know please?"

There is a difference between making a best effort to address issues and owing a response to every issue being raised. It's a two-way street where we try to help you and dify gets better in the meantime. Nothing is obligatory.

Reading issues is not a waste of time. You have the privilege of being fluent in english. Maybe try to understand the time & energy needed to parse feedbacks for those who aren't. 

Sorry that you feel this way though.

**Comment by HakaishinShwet** [comment]
"There is a difference between making a best effort to address issues and owing a response to every issue being raised. It's a two-way street where we try to help you and dify gets better in the meantime. Nothing is obligatory."
@guchenhe  Please do not waste your time and my time in writing something which i and max already know.I knew it that you will say this thing just wanted to test out your response and see if you have something new to say. I and Everybody who is contributing in whatever way they can know that very well that it is not mandatory for you to respond back,it is not mandatory to complete the request of user,it is not mandatory to fix any thing.Nothing is mandatory in open source BUT you put "respect" thing in pretty bad way so i would like to correct you. if user is not writing in formatted way then it is disrespectful for you even tho it has nothing to do with respect or the user who is writing the issue in 2-3 lines in your template is more respectful, you are not reading issue properly even if it maybe small too and you are not seeing the effort person is putting and saying that indirectly that it is disrespectful and you are saying it is not mandatory for you to respond back to person effort, So in open source way you are the one who is clearly disrespecting by doing all this not me who has no intention of been disrespectful by any mean and have just noble thoughts for this project and just want it grow and differentiate itself from others in market.I never asked for any detailed response.Even in my issues i have thanked them for this project or for solving issue or understanding issue i have been much more respectful than others but see what i get at the end.Just wanted to clear things of what is been respectful in open source and what is not.
Open source project grows only when proper respectful communication is there between contributors and devs.It is not one sided thing by any mean if both communicate share idea,solution together in respectful way then much more can be achieved and many foss solutions have achieved that because some are just tester they test and use if they find something they report back that's all and you fix but this is not the limit of open source.People can share ideas,suggestions,solutions and much more and that is the true beauty of open source.Healthy detailed communication cost nothing except some time but that is what makes best solution.You have to pay and hire people to get this and in open source everyone is doing as much as possible for free and just want Respectful behavior and response in return.
 
Reading issue is not waste of time if you agree with this then did you read clearly what i wrote there? i tried to write in much Easier+detailed way possible so that you can understand in one go and so that we dont have to drag conversation for days because neither you nor me are free to always open github and reply back plus it helps only devs if i put some idea and example and other knowledge.It is not for fun that i write big message, i write in detail for anyone to understand better that is my whole purpose.For your kind information I am not foreigner who has too good english that i will throw big or difficult words for which you have to use google or dictionary to understand, you can go and read yourself see i have write messages in very basic way because i just want you to read it like a simple story and understand what all things i mentioned in easier way so that you get full idea of what i have in my mind  plus have better mindset to solve that issue or implement that issue. It saves time ,it doesnt waste your "precious" time even if you read in little unformatted way.I mentioned that i will still improve just because he requested and didnt deny or show any disrespect even in that message and still i had to see such messages is truly disappointing for me to be honest what else can i say.

**Comment by guchenhe** [comment]
Not here to bite. For our background, reading English in such 'little unformatted way' is actually super hard. Harder than reading big vocabs. I don't think you were being disrespectful with prior issues as you weren't in the know. In fact, I think it's on us for failing to properly communicate our expectations in time. Previous comment was just meant to make clear of what we think is respectful moving forward.

Much has been said and I think we both got more important things to do.

**Comment by HakaishinShwet** [comment]
@guchenhe Good thing atleast now you are admitting your mistake which wasted alot of time for me unfortunately but hopefully this will save atleast future contributors from feeling disrespectful from you/team side.Plus add what we in open source actually mean by respect which i described above in your/team dictionary too so that proper respectful communication can be established between both devs and contributors so that project can grow in healthy way.You have a startup with less people and so team is the one who needs contributors support for ideas,bugs,suggestions,solutions to save time,money and create better solution otherwise there is no point of been open source simply so please be respectful in "our" way too is what i will say in the end.
That's all from my side
