### ISSUE TITLE
[Features] Code interpreter

### ISSUE THREAD

**Issue by nguyenthanhtien** [langgenius/dify#2487]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

I want using Code interpreter in Dify.

### 2. Describe the feature you'd like to see

Code Interpreter allows you to run Python code in a live working environment. It’s basically a sandboxed Python environment where you can execute Python code to perform any task you like. It may sound like a feature built for coders, but it can also help general users with many tasks.

### 3. How will this feature improve your workflow or experience?

Code Interpreter can convert a PDF file using OCR, trim a video file or change the format, solve a mathematical problem, perform data analysis and visualization, and much more. As a result, Code Interpreter allows you to directly in multiple formats.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Thank you very much for your suggestion. 
Are you hoping for a code interpreter tool that can generate Python code for LLM and perform some offline operations in this Python sandbox? 
BTW, we have already implemented a Python/Node.js sandbox solution in our upcoming workflow feature, maybe the underlying technology solutions overlap.

**Comment by nguyenthanhtien** [comment]
@takatost thanks you reply and hope see features soon.
