### ISSUE TITLE
Looks like context is not retrieved when external data tool is enabled

### ISSUE THREAD

**Issue by ipv6sq** [langgenius/dify#2496]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a new app
2. create a new customized tool
3. set this app to smart mode and add the customized tool
4. add any random context from knowledge base

### ✔️ Expected Behavior

the context should be retrieved both from knowledge base and external tool(when necessary)

### ❌ Actual Behavior

knowledge base retrieval never happened, you can verify this from knowledge base retrieval log and actual response, the app acts like a retard

**Comment by crazywoola** [comment]
The LLM itself will determine when to use the contexts based on it's description. In this case, you can not just link some random text, you should refine it's description for LLM to retrieve. 
And choose a smarter LLM. eg OpenAI. Some of them just not smart enough to determine what to do.

**Comment by ipv6sq** [comment]
By random I mean choose any knowledge set and ask questions accordingly,
not non sense
i increased the context window but it didn't work
You can easily reproduce that I believe, by comparing to a simple agent

crazywoola ***@***.***>于2024年2月20日 周二下午7:47写道：

**Comment by ipv6sq** [comment]
with same prompt and knowledge set

Qi Sun ***@***.***>于2024年2月20日 周二下午8:42写道：

**Comment by Yeuoly** [comment]
Does your customized tool and datasets have a detailed description of themself? the quality of response of Agent deeply depends on the description of tools, so that Agent could choose the right tool, or you can just set strict instructions to tell Agent they has to use the tool to answer.

**Comment by ipv6sq** [comment]
Yes, I do have a customized tool description. 
Here is my example, omit details but should be good to demonstrate
prompt:
you are a helpful customer service bot
customized tool:
Return some recommended products of this shop
knowledge set
The refund policy is that customer can return their goods within 30 days.


Ask
1. recommend some products (this works fine, invoked customized tool)
2. what's your refund policy(this does not retrieve the knowledge set, can be verified from knowledge set log and this was  good on simple agent mode)

**Comment by Yeuoly** [comment]
What's the description of your datasets? you can find it here
<img width="901" alt="image" src="https://github.com/langgenius/dify/assets/45712896/42abbdee-009f-4e5e-a914-c75d64a415e5">
Smart Agent uses this to detect use the dataset or not.

**Comment by ipv6sq** [comment]
bingo, that's the reason why it's not retrieving, thanks man!
btw, can you point me to the code base around this so I can dive into it further to better understand it. It looks like dataset is also consider as a special "customized tool" in this case, while in simple agent mode it's like a must hit tool

**Comment by crazywoola** [comment]
> The LLM itself will determine when to use the contexts based on it's description. In this case, you can not just link some random text, you should refine it's description for LLM to retrieve. And choose a smarter LLM. eg OpenAI. Some of them just not smart enough to determine what to do.

Well, guess you didn't notice what I am saying. I am trying to say the same thing.

![image](https://github.com/langgenius/dify/assets/100913391/8b7d58e9-e3ac-404b-9849-875c601be737)

For codes related to this: https://github.com/langgenius/dify/blob/063191889d86a4d593337603321e6f785990809e/api/core/agent/agent/structed_multi_dataset_router_agent.py#L52

You can treat dataset as a tool as well.
