### ISSUE TITLE
文件拖拽功能不可用

### ISSUE THREAD

**Issue by yabea** [langgenius/dify#25]
【创建数据集】- 【选择数据源】

![image](https://github.com/langgenius/dify/assets/15773461/a68e9476-1eea-4088-a1cb-df1709676e16)

**Comment by takatost** [comment]
@JzoNgKVO

**Comment by JzoNgKVO** [comment]
> 【创建数据集】- 【选择数据源】
> 
> ![image](https://user-images.githubusercontent.com/15773461/238320875-a68e9476-1eea-4088-a1cb-df1709676e16.png)

可以提供一下具体复现步骤吗？

**Comment by yabea** [comment]
期待的是将文件拖拽至此便可以上传进行解析

@JzoNgKVO 但将文件拖拽到 “至此”区域，会在新窗口中打开文件
