### ISSUE TITLE
[Question] Is it possible to upload files in a chat channel?

### ISSUE THREAD

**Issue by luozhouyang** [langgenius/dify#2501]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I want to create a agent that can read files  uploaded by user in a chat channel, but I do not see any file uploading controlls in dify web ui.

**Comment by crazywoola** [comment]
Close as duplicated. Pleaser refer the sources.
