### ISSUE TITLE
The example code in the API documentation has JSON specification errors

### ISSUE THREAD

**Issue by fogdragon** [langgenius/dify#2503]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of requested docs changes

Dify version
0.5.2

Cloud or Self Hosted
Self Hosted (Docker)

Steps to reproduce
On the api document page: "/app/<app_id>/develop" there are a example command of "Send Chat Message" api.
<img width="1049" alt="image" src="https://github.com/langgenius/dify/assets/5158337/7f94b929-c9b1-4653-8f22-d05a80d940c3">
The command has JSON specification errors at green arrow.
if you copy the sample code and replace {app_key} with actual key you would get this error:
{"code": "bad_request", "message": "The browser (or proxy) sent a request that this server could not understand.", "status": 400}

✔️ Expected Behavior
fix this error on those docment: template.en.mdx, template.zh.mdx, template_chat.en.mdx, template_chat.zh.mdx

**Comment by iamjoel** [comment]
Fixed with https://github.com/langgenius/dify/pull/2505.
