### ISSUE TITLE
How to implement custom LLM model and use it in Dify?

### ISSUE THREAD

**Issue by ntvuongg** [langgenius/dify#2509]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Hi everyone, I have successfully self-hosted Dify. I want to use my custom llm model instead of using existing model which access through API. Any help?

**Comment by crazywoola** [comment]
Please refer the page https://github.com/langgenius/dify/tree/main/api/core/model_runtime to see how to implement your own provider.
Or you can use xinference and localai to deploy yours. See this https://docs.dify.ai/tutorials/model-configuration/xinference for details.
