### ISSUE TITLE
Shared web app can not be opened again in the same browser

### ISSUE THREAD

**Issue by KnaveM** [langgenius/dify#2510]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create an App and publish it, enable Ready-to-use AI WebApp
2. open the web app url in other tab, start conversation with the chat bot
3. open another tab, the browser display error

### ✔️ Expected Behavior

Should save the previous conversation in browser cache, and no error

### ❌ Actual Behavior

error
The web app url could only be used once, the next time you open the link will get an error.

![image](https://github.com/langgenius/dify/assets/33738071/b9a9b826-9c06-4a18-b0e7-3860fe171a55)

https://github.com/langgenius/dify/assets/33738071/1f335914-94de-417d-8a83-152110bcf1c0

**Comment by crazywoola** [comment]
Actually it's not a bug, if you open a new tab in same browser (not private mode) The conversations will shared across the tabs. If you open this url in private mode, you will be a totally new user and will not share the same data. It's by design.
We use cookies and localstorage to track these shared information locally. So you should check the settings in private mode.

**Comment by KnaveM** [comment]
THX in advance.

> It's related to https://github.com/langgenius/dify/issues/2502 I think.

Yes, the error message is the same.

FYI, if refresh the new tab, the bug sometimes disappear.

**Comment by crazywoola** [comment]
> THX in advance.
> 
> > It's related to #2502 I think.
> 
> Yes, the error message is the same.
> 
> FYI, if refresh the new tab, the bug sometimes disappear.

@KnaveM Yes I noticed this as well.
