### ISSUE TITLE
repack images but 502 bad gateway

### ISSUE THREAD

**Issue by carllisicau** [langgenius/dify#2511]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

i repackage images (web module)，and docker compose up ,but occur 502 badway 
this images is being rebuilt using the Dockerfile
i pull code and cd web folder and input docker build -t xx .
and push the images ,change docker-compose.yaml set web images to the new images
how to build images correctly?

**Comment by crazywoola** [comment]
For newly added images, please use this https://github.com/langgenius/dify/blob/df07fb595169dd57ae4cca9ce67febfcad00abe3/web/app/components/base/icons/script.js#L1 for generation.
For 502 bad gateway.
Can you attach the container's logs in this thread? 
The 502 means the backend does not start correctly, so it's another issue.

**Comment by carllisicau** [comment]
> For newly added images, please use this
> 
> https://github.com/langgenius/dify/blob/df07fb595169dd57ae4cca9ce67febfcad00abe3/web/app/components/base/icons/script.js#L1
> 
> for generation.
> For 502 bad gateway.
> Can you attach the container's logs in this thread?
> The 502 means the backend does not start correctly, so it's another issue.

1 i just make a few  changes in dify/web/app/layout.tsx,why do i need to modify dify/web/app/**/script.js, 
2 The following is web container logs 

2024-02-22 09:25:30 ./entrypoint.sh: set: line 3: illegal option -
: not found09:25:37 ./entrypoint.sh: line 2:

**Comment by carllisicau** [comment]
i try to  build the initial web module code( image ),and docker compose up , but still 502,dose  this mean there is an issue with my  images building process ?
