### ISSUE TITLE
Unable to connect dify to Ollama for Windows

### ISSUE THREAD

**Issue by jafrank88** [langgenius/dify#2516]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using Dify in Docker, I am unable to connect to Ollama running natively in Windows.  

Start Dify, go to Settings, Model Provider, Ollama and try to connect to Ollama running on Windows. Do I need to add -p when running Dify in docker, such as docker compose -p 3001:3001 up -d ?

I am able to connect to Ollama with AnythingLLM, so wonder if it is a Dify issue or because Dify is in a container.

### ✔️ Expected Behavior

I was expecting to be able to use the llm model (Mistral) and the embedding model from Ollama with my self-hosted instance of Dify.

### ❌ Actual Behavior

I received an error suggesting something was wrong, as seen here https://cdn.discordapp.com/attachments/1187025321447403530/1209926509368967259/image.png?ex=65e8b2df&is=65d63ddf&hm=3ecdaf1b9099b302287a9fb56b25e2529c21297a63aa8daff54cd04496024be3&

**Comment by jafrank88** [comment]
I am not having any problems reaching Dify, so I don't think it is a container issue, but wanted to raise it in case I am wrong.

**Comment by crazywoola** [comment]
@jafrank88 https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows Please try  this docs to see if this issue persists.
