### ISSUE TITLE
Agent Mode of gpt-3.5-turbo  have only Function Calling

### ISSUE THREAD

**Issue by xiangpingjiang** [langgenius/dify#2517]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Use the Agent Assistant and set the Agent Assistant. 
Agent Mode just has Function Calling

### ✔️ Expected Behavior

there are two options , Function Calling and ReAct

### ❌ Actual Behavior

just one option Function Calling

**Comment by crazywoola** [comment]
Can you add a screenshot as well? The information you provide seems not enough for us to infer what's going on here.

**Comment by xiangpingjiang** [comment]
<img width="1920" alt="Screenshot 2024-02-22 at 11 20 16" src="https://github.com/langgenius/dify/assets/45722758/8b8bfa07-cddd-47eb-ae0a-0a8ee5786ddb">

**Comment by xiangpingjiang** [comment]
hello @crazywoola 
What should I do if I want set the ReAct mode for my Agent Assistant?

**Comment by crazywoola** [comment]
> hello @crazywoola What should I do if I want set the ReAct mode for my Agent Assistant?

Well you should wait for the new version I think.

**Comment by xiangpingjiang** [comment]
@crazywoola 
Is there an issue to track the feature ?

**Comment by crazywoola** [comment]
cc @Yeuoly

**Comment by crazywoola** [comment]
> > hello @crazywoola What should I do if I want set the ReAct mode for my Agent Assistant?
> 
> Well you should wait for the new version I think.

Here it is.

**Comment by xiangpingjiang** [comment]
@Yeuoly 
Yes, I want to do a test. 
But Are you sure that  Function calling has better performance for all models?

**Comment by Yeuoly** [comment]
Then you can try to read our source code and do some simple modifications here https://github.com/langgenius/dify/blob/main/api/core/app_runner/assistant_app_runner.py#L205

You can just make all models use AssistantCotApplicationRunner

**Comment by xiangpingjiang** [comment]
so did you decide to abandone the ReAct feature ?

**Comment by Yeuoly** [comment]
It's not abandoned I thought, you can find React mode if you change the model to Gemini Pro if you want, people use Dify for production wants a better performance, and as for the model supports Function calling in Dify, Function Calling does have a better performance.

**Comment by xiangpingjiang** [comment]
@Yeuoly 
But Gemini Pro  supports also  Function calling  https://cloud.google.com/vertex-ai/docs/generative-ai/multimodal/function-calling .

**Comment by crazywoola** [comment]
> @Yeuoly But Gemini Pro supports also Function calling https://cloud.google.com/vertex-ai/docs/generative-ai/multimodal/function-calling .
> 
> Dify didn't support Function Calling for Gemini Pro?

It does support fc in Gemini Pro.

**Comment by xiangpingjiang** [comment]
ok, so which models we can use ReAct mode in dify ?

**Comment by Yeuoly** [comment]
> > @Yeuoly But Gemini Pro supports also Function calling https://cloud.google.com/vertex-ai/docs/generative-ai/multimodal/function-calling .
> > Dify didn't support Function Calling for Gemini Pro?
> 
> It does support fc in Gemini Pro.

There is an issue in generativeai causes function call does not work now https://github.com/langchain-ai/langchain/discussions/17621
