### ISSUE TITLE
tool  form parameters  not working

### ISSUE THREAD

**Issue by lujin1** [langgenius/dify#2522]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/33309882/1dcca021-0eec-45a7-a735-3a323eb3c943)

**Comment by Yeuoly** [comment]
You should change the timezone here
<img width="816" alt="image" src="https://github.com/langgenius/dify/assets/45712896/20dad89c-abbe-4a48-b0f8-96dc6a7c5f0d">
<img width="504" alt="image" src="https://github.com/langgenius/dify/assets/45712896/0791a5e2-e459-47ce-ace7-7f472c6d3451">
