### ISSUE TITLE
[Question] how to see the mid-process of ReAct Agent

### ISSUE THREAD

**Issue by xiangpingjiang** [langgenius/dify#2523]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I locally host dify in my pc, add llama as my LLM.

When I use ReAct mode, I can't see the mid-process 
<img width="1693" alt="Screenshot 2024-02-22 at 14 58 22" src="https://github.com/langgenius/dify/assets/45722758/48d5f5bf-dac6-4288-89d2-51e9ad7ff067">

If it is possible to see the whole  ReAct process to debug ?
Thoughts
Actions
Observations

**Comment by xiangpingjiang** [comment]
@dosu-bot

can I see the mid-process of ReAct in logs ?

**Comment by crazywoola** [comment]
For debugging agent step by step, it's in our development plan. We will release this feature soon.

**Comment by xiangpingjiang** [comment]
> For debugging agent step by step, it's in our development plan. We will release this feature soon.

@crazywoola 

Oh, that's cool, is there an issue to track the feature ?
