### ISSUE TITLE
how to rebuild an image

### ISSUE THREAD

**Issue by carllisicau** [langgenius/dify#2524]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

i want to change a few feature on web module,and follow the reference docker build -t xx . 
then change the docker-compose.yaml ,change web:image to the new image 
but when execute docker compose up -d ,the web module start failure
following is the container logs 
2024-02-22 14:37:05 ./entrypoint.sh: set: line 3: illegal option -
: not found14:37:06 ./entrypoint.sh: line 2: 
2024-02-22 14:37:06 ./entrypoint.sh: set: line 3: illegal option -
: not found14:37:07 ./entrypoint.sh: line 2:

how to rebuild an image correctly?

**Comment by kevinkelin** [comment]
> i use wsl docker desktop to make image ,is that have problem?

you should use `dos2unix entrypoint.sh` command to convert sh file to unix file when you clone this repo, because on windows system will change the Line Endings of sh file

**Comment by crazywoola** [comment]
Duplicate #2511
