### ISSUE TITLE
New provider added but not showing up

### ISSUE THREAD

**Issue by ntvuongg** [langgenius/dify#2525]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I want to use custom model LLM in Dify so followed the tutorial in model_providers/README.md but my new provider was not showed up. Here is my provider folder structure:
![Screenshot 2024-02-22 at 14 34 54](https://github.com/langgenius/dify/assets/65907920/6f9b1f65-3352-478e-bb96-9e1cbde0d477)

Here is my vinallama.yaml:
![Screenshot 2024-02-22 at 14 34 25](https://github.com/langgenius/dify/assets/65907920/2c9be22c-4f57-4378-9f86-97edd75d0996)

Note: I also try to add my new provider in _position.yaml but got nothing change
![Screenshot 2024-02-22 at 14 36 01](https://github.com/langgenius/dify/assets/65907920/5f99c0f8-ecfd-430e-bb5d-b6d5341b824b)

![Screenshot 2024-02-22 at 14 36 20](https://github.com/langgenius/dify/assets/65907920/23f42cc8-51a9-4739-ac50-ea375c1ab911)

Any help please?

**Comment by crazywoola** [comment]
You can see this pr https://github.com/langgenius/dify/pull/2003/files to see if there is something you might missed.

**Comment by ntvuongg** [comment]
I try to use another svg file to replace existing providers in _assets folder but the icon seems to be same as original. I'm using docker-compose
