### ISSUE TITLE
llama2 ReAct agent can't use wikipedia tool

### ISSUE THREAD

**Issue by xiangpingjiang** [langgenius/dify#2526]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

use ollama to run llama2 locally, and add llama2 to dify as LLM

### ✔️ Expected Behavior

llama2 ReAct agent  can use wikipedia tool.

### ❌ Actual Behavior

<img width="1866" alt="Screenshot 2024-02-22 at 17 33 53" src="https://github.com/langgenius/dify/assets/45722758/f13dc332-6041-4b58-a3fc-47de930c3425">

the prompt answer didn't use wikipedia tool,  but with "According to Wikipedia,"

If the agent use the wikipedia tool , it will appear  an icon like bellow
<img width="292" alt="Screenshot 2024-02-22 at 17 35 42" src="https://github.com/langgenius/dify/assets/45722758/28f5829f-411f-4c7c-a1aa-c4e7242f9734">

**Comment by ntvuongg** [comment]
@xiangpingjiang  Hi, can you share the code that you implement llm model locally please. I'm stucking at implement local model :((

**Comment by crazywoola** [comment]
This is a issue related to LLM itself. You could try mistral or something smarter. Because it needs extra work on models like llama2 which can not understand the questions correctly, we have no plan for this right now.

**Comment by xiangpingjiang** [comment]
@crazywoola 
But dify dosen't  support mistral now.
