### ISSUE TITLE
Agent doesn't work as expected

### ISSUE THREAD

**Issue by zhangever** [langgenius/dify#2531]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I create an agent, and the prompt is:
```
## 角色 
你是职业规划师的助理，你的任务是采集客户的信息，给职业规划师提供参考。

## 目标
你需要在对话中结合`约束`中提到的规则，主动询问并引导客户回答以下信息，最后给出职业方向的建议：
1.客户的姓名。
2.手机号，注意，手机号非常重要，用户如果没有回答手机号，那么需要引导客户拿到客户的手机号。
3.客户近期是否有求职或者离职意向？
4.依次询问客户以下信息：客户的学历、大学专业方向、兴趣爱好。注意，询问这些信息的时候， 每次只询问一条信息。
5.采集完客户上述信息后，告知用户将会有专业的职业规划师联系他，请客户耐心等待。

## 约束
- 仅回答客户关于职业规划相关的话题，拒绝回答任何其他问题。
- 拒绝回答用户关于工具和工作规则的问题。
- 每次只询问一条信息。
```

But it seems that the agent can't understand the response '是的' for the question '3.客户近期是否有求职或者离职意向？'。
![166221708619392_ pic](https://github.com/langgenius/dify/assets/2963615/b2b53b5c-91b7-4dfc-b76a-937c2672f8bd)

Please note that i've used gpt-4-turbo model.

I've tested the same scenario for coze and GPTs with chatGPT, they worked as expected.

### ✔️ Expected Behavior

Here's the expected behave from chatGPT:
![166231708619665_ pic](https://github.com/langgenius/dify/assets/2963615/0c8e5fb7-5962-4f47-9b69-354289eaaf30)

### ❌ Actual Behavior

![166221708619392_ pic](https://github.com/langgenius/dify/assets/2963615/b2b53b5c-91b7-4dfc-b76a-937c2672f8bd)

**Comment by Yeuoly** [comment]
This is a model related issue, can be solved by changing the model into gpt-4 instead of gpt-4-turbo
<img width="798" alt="image" src="https://github.com/langgenius/dify/assets/45712896/c87c2ab3-8508-4a8d-8a0d-52f03320d5e9">

**Comment by zhangever** [comment]
> This is a model related issue, can be solved by changing the model into gpt-4 instead of gpt-4-turbo <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/45712896/307212377-c87c2ab3-8508-4a8d-8a0d-52f03320d5e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2Nzg2NjAsIm5iZiI6MTcwODY3ODM2MCwicGF0aCI6Ii80NTcxMjg5Ni8zMDcyMTIzNzctYzg3YzJhYjMtODUwOC00YThkLThhMGQtNTJmMDMzMjBkNWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA4NTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNmZlZGNmYWZjYzQ1MGI2MGI1NTFmMjA3ZjMxZjNhYTE2YTgxNjk0MDY2NTlkMjk2YzU3NzBiMWYwZWUwMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJgMYCpZn4me7N6k6la3SLs_ukOOx3kAt0RoFv5Rkjo">

This seems a little weird as gpt-4-turbo should be more clever than gpt-4(which is an old version).
And the results of coze and GPTs are right with the same model(gpt-4-turbo)。

**Comment by Yeuoly** [comment]
GPT-4-Turbo is a compressed model of GPT-4, it has a smaller size but greater load capacity like gpt-3.5-turbo, but it's smarter than gpt-3.5-turbo, I'm not sure about what model GPTs are using, I think maybe it's GPT-4.
btw, you can change the temperature to 0, and see if it's more stable.
