### ISSUE TITLE
Azure Cognitive Search

### ISSUE THREAD

**Issue by rachaelsingleton** [langgenius/dify#2532]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, I have existing indexes and would like to utilize the same technology moving forward. 

### 2. Describe the feature you'd like to see

Would like the ability to use Azure Search as the vector db. 

### 3. How will this feature improve your workflow or experience?

Already familiar with the service / already using the service. 

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Thanks for reaching out, we are reworking on RAG recent days. We will take a look at `Azure Cognitive Search` and put it into our roadmap.  :0
