### ISSUE TITLE
The session name changes automatically and it is not a session issue.

### ISSUE THREAD

**Issue by Mxk-1** [langgenius/dify#2535]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

When the conversational assistant is opened for the first time, the session is labeled '**新的对话**'. After the first question is asked and a response is received, the session name changes to 'New conversation'. The function `auto_generate_name` located in `dify/api/services/conversation_service.py` does not work. Can you help solve this problem?

_Note that we have already set the default language to Chinese._

1. The first time it is opened, it looks like this.
![image](https://github.com/langgenius/dify/assets/56588847/cde44e30-a4aa-4df3-9ccc-ec7530a8fd9e)

2. After I ask the first question, it looks like this.
![image](https://github.com/langgenius/dify/assets/56588847/d02e2455-0453-47b8-8330-102a56dd288e)

### ✔️ Expected Behavior

The session correctly displays the question name.

### ❌ Actual Behavior

The session cannot correctly display the question name.

**Comment by Fucheng-Wu** [comment]
可以在设置里切换下默认模型（非推理模型），然后对dify/api/core/llm_generator/prompt.py文件中的提示词进行修改就可以了
