### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by yanzu888** [langgenius/dify#2541]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Access your own application by sharing the address and start a new conversation. Opening a new window to access will have a very high probability of popping up this error message. It seems that this malfunction is easy to occur in chat applications with historical conversations. Amazingly, if you keep refreshing the page after opening F12, this error will not occur.

![image](https://github.com/langgenius/dify/assets/20461842/65936980-dbd4-4bb5-b4ae-bd49239937bc)

**Comment by crazywoola** [comment]
Fixed in this pr https://github.com/langgenius/dify/pull/2513, we haven't release the new version. It should be fixed in v0.5.7.

**Comment by Upcreat** [comment]
> Fixed in this pr #2513, we haven't release the new version. It should be fixed in v0.5.7.

 The same problem occurred with version 0.6.7

**Comment by AlexSu1108** [comment]
The same problem occurred with version 0.6.12-fix1(current version) and 0.6.9
