### ISSUE TITLE
今天安装dify新版报错。

### ISSUE THREAD

**Issue by limuan123123** [langgenius/dify#2544]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

本地安装dify，在执行flask db upgrade是报错了：ValueError: RESEND_API_KEY is not set。
请问这个RESEND_API_KEY 参数需要填什么？ 谢谢
![Uploading 0c49cfbe9cf9e596493f84c19d85d1d.png…]()

**Comment by crazywoola** [comment]
Close. due to https://github.com/langgenius/dify/issues/1542, also set the `RESEND_API_KEY ` in `.env` in api/ folder.
