### ISSUE TITLE
Can't  send invitation email although environment variables have been set

### ISSUE THREAD

**Issue by 1622145167** [langgenius/dify#2551]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

![image](https://github.com/langgenius/dify/assets/54617326/f68264d5-1494-47a7-8d39-3ba2a2002f5e)
Part of my configuration in 'docker-compose.yaml' is as above. Then I deleted containers and recreated them. When I clicked "add" button in settings->members, none is sent to my email.

**Comment by 1622145167** [comment]
> _🤖_
> 
> Hello @1622145167! 👋 I'm [Dosu](https://dosu.dev), a bot here to help you solve bugs, answer questions, and become a contributor while you're waiting for a human maintainer to assist. I'm here to provide support and guidance on your journey. I'll take a look at your issue regarding the invitation email not being sent and will provide you with a full answer shortly. Let's get started!

What?!

**Comment by 1622145167** [comment]
The following is my log.

```
[2024-02-23 11:07:04,854: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[ed53744e-7465-445b-8411-619e0a789e06] received
[2024-02-23 11:07:04,869: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[ed53744e-7465-445b-8411-619e0a789e06] succeeded in 0.014574461005395278s: None
[2024-02-23 11:14:20,135: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[f89bb06a-9619-4144-8dc5-5ece5554684a] received
[2024-02-23 11:14:20,150: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[f89bb06a-9619-4144-8dc5-5ece5554684a] succeeded in 0.014414265999221243s: None
```

**Comment by 1622145167** [comment]
> _🤖_
> 
> Based on the information you've provided, it seems like the issue might be related to the mail configuration in your 'docker-compose.yaml' file.
> 
> In the 'api' and 'worker' services of your 'docker-compose.yaml' file, the mail configuration might not be properly set. The `MAIL_TYPE` is left empty, and the SMTP server details are also not provided.
> 
> Here is the relevant part of your configuration:
> 
> ```yaml
> # Mail configuration, support: resend, smtp
> MAIL_TYPE: ''
> # default send from email address, if not specified
> MAIL_DEFAULT_SEND_FROM: 'YOUR EMAIL FROM (eg: no-reply <no-reply@dify.ai>)'
> SMTP_SERVER: ''
> SMTP_PORT: 587
> SMTP_USERNAME: ''
> SMTP_PASSWORD: ''
> SMTP_USE_TLS: 'true'
> # the api-key for resend (https://resend.com)
> RESEND_API_KEY: ''
> RESEND_API_URL: https://api.resend.com
> ```
> 
> You need to specify the `MAIL_TYPE` as either 'smtp' or 'resend'. If you're using SMTP, you need to provide the `SMTP_SERVER`, `SMTP_USERNAME`, and `SMTP_PASSWORD`. If you're using Resend, you need to provide the `RESEND_API_KEY`.
> 
> For example, if you're using SMTP:
> 
> ```yaml
> MAIL_TYPE: 'smtp'
> SMTP_SERVER: 'smtp.example.com'
> SMTP_USERNAME: 'your-smtp-username'
> SMTP_PASSWORD: 'your-smtp-password'
> ```
> 
> Or if you're using Resend:
> 
> ```yaml
> MAIL_TYPE: 'resend'
> RESEND_API_KEY: 'your-resend-api-key'
> ```
> 
> After updating these configurations, you should be able to send invitation emails.
> 
> If you're still experiencing issues after making these changes, it would be helpful to know the exact error message or log output when you try to send an invitation email. This could provide more insight into what might be causing the issue.
> 
> For reference, the exact error message when the user tries to send an invitation email and it fails is "Send invite member mail to {} failed". This message is logged in the catch block of the try-except statement in the `send_invite_member_mail_task` function. The placeholder {} will be replaced with the email address to which the invitation was attempted to be sent. This error message is logged when any exception occurs during the process of sending the email.
> 
> Here is the relevant code:
> 
> ```python
> except Exception:
>     logging.exception("Send invite member mail to {} failed".format(to))
> ```
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [docker/docker-compose.yaml](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)
> * [api/tasks/mail_invite_member_task.py](https://github.com/langgenius/dify/blob/main/api/tasks/mail_invite_member_task.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

The following is my log. @dosu-bot

```
[2024-02-23 11:07:04,854: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[ed53744e-7465-445b-8411-619e0a789e06] received
[2024-02-23 11:07:04,869: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[ed53744e-7465-445b-8411-619e0a789e06] succeeded in 0.014574461005395278s: None
[2024-02-23 11:14:20,135: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[f89bb06a-9619-4144-8dc5-5ece5554684a] received
[2024-02-23 11:14:20,150: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[f89bb06a-9619-4144-8dc5-5ece5554684a] succeeded in 0.014414265999221243s: None
```

**Comment by 1622145167** [comment]
> _🤖_
> 
> Based on the information you've provided, it seems like your SMTP settings are correctly configured in your `docker-compose.yaml` file. However, the log output you've shared indicates that the `send_invite_member_mail_task` is completing very quickly (in about 0.014 seconds), which suggests that the email might not be getting sent out.
> 
> The `send_invite_member_mail_task` function in the `tasks.mail_invite_member_task` module is responsible for sending out the invitation emails. It's an asynchronous task that takes in parameters like the recipient's email address, a token, the name of the inviter, and the name of the workspace. It then constructs an email and sends it out.
> 
> Given that there are no error messages in your logs, it's possible that the function is not being called correctly, or that the email is being sent but is not being delivered for some reason. Here are a few things you could check:
> 
> 1. **Check the function call:** Make sure that the `send_invite_member_mail_task` function is being called with the correct parameters. You should be calling it like this: `send_invite_member_mail_task.delay(language, to, token, inviter_name, workspace_name)`. If any of these parameters are incorrect or missing, the email might not get sent.
> 2. **Check your SMTP server:** The issue might be with your SMTP server. Try sending an email directly from your SMTP server to see if it's working correctly. If you're not receiving the email, then the issue is likely with your SMTP server or your SMTP settings.
> 3. **Check your email spam folder:** Sometimes, emails sent via SMTP can end up in the spam folder. Check the spam folder of the email address you're trying to send the invitation to, to see if the email ended up there.
> 4. **Check your application logs:** There might be more information in your application logs that can help diagnose the issue. Look for any warnings or errors related to the `send_invite_member_mail_task` function or the SMTP settings.
> 
> If you've checked all of these and you're still having issues, it would be helpful if you could provide more information about your setup. For example, what version of the software are you using? Are you running it in a Docker container or directly on your machine? Are there any other relevant log messages? This additional information could help diagnose the issue.
> 
> For more information about the `send_invite_member_mail_task` function and how it works, you can refer to the [source code](https://github.com/langgenius/dify/blob/main/api/tasks/mail_invite_member_task.py).
> 
> ## Sources
> * [docker/docker-compose.yaml](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)
> * [api/tasks/mail_invite_member_task.py](https://github.com/langgenius/dify/blob/main/api/tasks/mail_invite_member_task.py)
> 
> #### About Dosu

But there's no error in the log. @dosu-bot

**Comment by 1622145167** [comment]
> We will take a look at this. #2409 This is the original pull request for this.

Do you have a wechat dev group or users group?

**Comment by crazywoola** [comment]
> > We will take a look at this. #2409 This is the original pull request for this.
> 
> Do you have a wechat dev group or users group?

@1622145167 my wechat crazyphage
