### ISSUE TITLE
[Need help] Create Custom Tools for Redmine

### ISSUE THREAD

**Issue by MrBrabus75** [langgenius/dify#2553]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Hello,

I would like to create a custom tool that allows the LLM to search for tickets in Redmine when I ask a question like: 

_"Have we ever had an Alpha network problem on Redmine?"_ 

With this question, the LLM would use OpenAPI Swagger to search for relevant tickets, then synthesize and send a response based on the tickets it has retrieved from Redmine, including the ticket numbers. 

However, I'm struggling with this. Could I get some help?

Here is my code.

`
openapi: "3.1.0"
info:
  title: "Redmine Project Ticket Search API"
  description: "API for searching tickets in the 'informatique' project on Redmine."
  version: "v1.0.0"
servers:
  - url: "http://172.21.0.2:3000"
paths:
  /projects/informatique/issues:
    get:
      summary: "Search tickets in 'informatique'"
      description: "Retrieve a list of tickets from the 'informatique' project by keywords."
      parameters:
        - name: "subject"
          in: "query"
          required: false
          description: "Subject to search for in the project's tickets"
          schema:
            type: "string"
      responses:
        "200":
          description: "A list of tickets matching the query in the 'informatique' project"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Issue"
components:
  schemas:
    Issue:
      type: "object"
      properties:
        id:
          type: "integer"
        subject:
          type: "string"
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "X-Redmine-API-Key"
      in: "header"
security:
  - api_key: []

`

![Screenshot_20240223_162058](https://github.com/langgenius/dify/assets/146331353/426e574c-d6e0-47bd-ba0d-89e9d45c0d7b)
![Screenshot_20240223_162133](https://github.com/langgenius/dify/assets/146331353/66843f72-8dbf-4ef1-931c-68da50a678f9)
![Screenshot_20240223_162200](https://github.com/langgenius/dify/assets/146331353/283b0678-dcab-4948-acc3-44715c6a360b)

 Thank you in advance.

**Comment by MrBrabus75** [comment]
When I test a ticket search request, I get this error: [Errno 99] Cannot assign requested address.

I thought that to create a custom tool, you just had to write the OpenAPI Swagger code in YAML and not use Python?

If Python script is required, where should I do it?

**Comment by MrBrabus75** [comment]
my port is open, is not a network problem :

(base) gpt-lab@gpt-lab-tower:~$ curl -H "X-Redmine-API-Key: b43cafdbdf667039bf920943b9f3ab281f1da1ef" "http://localhost:3000/projects/informatique/issues.json"
{"issues":[{"id":50,"project":{"id":1,"name":"Informatique"},"tracker":{"id":1,"name":"test"},"status":{"id":1,"name":"test","is_closed":false},"priority":{"id":2,"name":"test"},"author":{"id":1,"name":"Redmine Admin"},"subject":"Intégration d'un système de contrôle de version pour le code source","description":"Un système de supervision réseau doit être déployé pour surveiller l'état du réseau et détecter les anomalies de manière proactive.","start_date":"2024-02-23","due_date":null,"done_ratio":0,"is_private":false,"estimated_hours":null,"total_estimated_hours":null,"spent_hours":0.0,"total_spent_hours":0.0,"created_on":"2024-02-23T14:26:32Z","updated_on":"2024-02-23T14:35:04Z","closed_on":null},{"id":49,"project":{"id":1,"name":"Informatique"},"tracker":{"id":1,"name":"test"},"status":{"id":1,"name":"test","is_closed":false},"priority":{"id":2,"name":"test"},"author":{"id":1,"name":"Redmine Admin"},"subject":"Intégration d'un système de gestion de configuration","description":"Un tableau de bord de surveillance système doit être développé pour permettre aux administrateurs de suivre en temps réel les performances du réseau.","start_date":"2024-02-23","due_date":null,"done_ratio":0,"is_private":false,"estimated_hours":null,"total_estimated_hours":null,"spent_hours":0.0,"total_spent_hours":0.0,"created_on":"2024-02-23T14:26:32Z","updated_on":"2024-02-23T14:35:04Z","closed_on":null}

**Comment by MrBrabus75** [comment]
The issue here is resolved; it was a network problem. Now I have another problem: the output is not what I expected. I thought I would receive a ticket or tickets that would then be synthesized by the LLM, but I receive an HTML page. Can someone help me, please?
![Screenshot_20240223_182403](https://github.com/langgenius/dify/assets/146331353/3d0c70ba-c88a-4c31-a354-40deffa31550)

**Comment by crazywoola** [comment]
> I thought that to create a custom tool, you just had to write the OpenAPI Swagger code in YAML and not use Python?
> If Python script is required, where should I do it?
@MrBrabus75 Hello

OpenAPI code is just a documentation for LLM, it stills needs some third party service to retrieve it for you. 
For example, I wrote a cloudflare worker to generate and respond at the same time. The code is written in JavaScript, but it's quite simple.

https://github.com/crazywoola/dify-tools-worker

> The issue here is resolved; it was a network problem. Now I have another problem: the output is not what I expected. I thought I would receive a ticket or tickets that would then be synthesized by the LLM, but I receive an HTML page. Can someone help me, please?

And I think you need this tool(maybe not mine) to process the html code to you or you can just let the llm itself to parse it for you, but some tags will occupy the space in context window. So I suggest you to write a simpler API to get only required information for you.

**Comment by ZJ-CAI** [comment]
@dosu-bot  

how to use self.create_blob_message() to show the audio player in the frontpage?
