### ISSUE TITLE
The overlapping length of the segments seems to be ineffective. Please help, thank you

### ISSUE THREAD

**Issue by lhr1998** [langgenius/dify#2555]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need
I added segment overlap length when creating the knowledge base, but it doesn't seem to have much effect. The segment preview, including the retrieved paragraphs during use, does not contain contextual content
![image](https://github.com/langgenius/dify/assets/33489666/264f389d-d105-4cc1-8d11-4f62a574e47e)

**Comment by JohnJyong** [comment]
this issue has fixed in the latest code ，thanks  for your feedback @lhr1998
