### ISSUE TITLE
Upload 'Powered by Brand' image not showing up

### ISSUE THREAD

**Issue by wststone** [langgenius/dify#2559]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![iShot_2024-02-26_10 33 55](https://github.com/langgenius/dify/assets/42225395/edf1cecf-a7ba-4147-a3f8-601bfc62eff1)

### ✔️ Expected Behavior

Logo image showing up

### ❌ Actual Behavior

Logo image is not found

**Comment by zxhlyh** [comment]
what's the url of that image?

**Comment by wststone** [comment]
> what's the url of that image?

I uploaded the image from local machine by clicking the uploaded button, are you asking for the uploaded image address?
