### ISSUE TITLE
[FEATURE]Add support for APM-like chain tracing tools like LangSmith 

### ISSUE THREAD

**Issue by yuxizhe** [langgenius/dify#2561]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Currently dify dont supports tracking APM call links , which is difficult for low-code debugging of each step's output and building applications in production environments.

### 2. Describe the feature you'd like to see

Now APM-like chain tracing tools like LangSmith、langfuse、lunary are supported in langchain.  
Does dify has a plan to support APM-like chain tracing tool ?

### 3. How will this feature improve your workflow or experience?

Easy for low-code debugging of each step's output and building applications in production environments.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
This feature will be considered for integration after the stability of Dify's various business and technical architecture layers. For now, it is recommended to check in the Dify App Logs.
