### ISSUE TITLE
machine migration for dify

### ISSUE THREAD

**Issue by PhenixZhang** [langgenius/dify#2567]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I am ready to switch the dify machine, there are many applications on it, may I ask how to reduce the cost of migration?

**Comment by crazywoola** [comment]
- Copy the docker folder to another machine.
- You may encounter the key not found error, follow the docs to reset the key pair
- Restart the application

For further information, this requires our business license to provide technical support. Please send email to business@dify.ai :)
