### ISSUE TITLE
私优化部署，为啥进了localhost/install，可以成功设置管理密码，但是要跳到界面进行登陆，刚设置的管理账户和密码总是错的

### ISSUE THREAD

**Issue by kevinhorse** [langgenius/dify#257]

**Comment by zxhlyh** [comment]
Has it been set up before?

**Comment by kevinhorse** [comment]
第一次install进去的时候，设置成功，然后跳转进行登陆，登录提示邮箱和密码不对，但是我手动输入localhost首页访问，进去了，而且是已登录状态，可以用。但是后面再登陆，每次都是邮箱和密码不对。所以我就把docker停了，然后git代码重新pull下来再进install，就一直重复这个状态，登录失败

**Comment by kevinhorse** [comment]
已经可以了，我删除掉重新安装了，然后设置了管理账号密码就可以了
