### ISSUE TITLE
macOS Local Source Code Start  failed

### ISSUE THREAD

**Issue by xiangpingjiang** [langgenius/dify#2583]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

latest main

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

follow https://docs.dify.ai/getting-started/install-self-hosted/local-source-code 
In Server Deployment session, step 6, 
I got error, and the flask server didn't start
<img width="1681" alt="Screenshot 2024-02-27 at 17 38 56" src="https://github.com/langgenius/dify/assets/45722758/e73cb855-49ae-4e9e-9871-b0621768606d">

ValueError: RESEND_API_KEY is not set

When I set RESEND_API_KEY in .env file a random string,  the sever starts  successfully

### ✔️ Expected Behavior

api server can start successfully

### ❌ Actual Behavior

 the flask server didn't start on macOS

**Comment by crazywoola** [comment]
Try `brew install ffmpeg`

**Comment by xiangpingjiang** [comment]
@crazywoola 
The error is still there ValueError: RESEND_API_KEY is not set
