### ISSUE TITLE
这个功能有问题：回答结束后系统会给出 3 个建议

### ISSUE THREAD

**Issue by upseem** [langgenius/dify#2585]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

api/core/generator/llm_generator.py
这个文件第80行 questions = output_parser.parse(response.message.content) 
这个解析有问题，返回的是一个json型字符串，你这个解析有时候能解析成功，有时候会失败，我尝试修改了一下就可以了，
questions = json.loads(response.message.content)
直接将output_parser.parse 改成json.loads就解决了

### ✔️ Expected Behavior

返回三个问题

### ❌ Actual Behavior

空

**Comment by crazywoola** [comment]
Close due to #1542
