### ISSUE TITLE
对话返回内容突然中断。

### ISSUE THREAD

**Issue by Jas0nxlee** [langgenius/dify#2587]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

在与模型对话时，模型返回的内容突然中断，例如：
![WechatIMG46](https://github.com/langgenius/dify/assets/33084918/c1c87be7-3342-4ea1-b70a-b1b3a86e6b8f)

所有对话均有此问题。

**Comment by Jas0nxlee** [comment]
继续补充截图：
![WechatIMG47](https://github.com/langgenius/dify/assets/33084918/71588eeb-42d5-4e7f-a563-283cdc36b513)

**Comment by realcarlos** [comment]
同样的问题，我用的是0.4.6

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by trackcan** [comment]
这个bug修复了吗，我在0.8.3版本上还存在

**Comment by trackcan** [comment]
![图片](https://github.com/user-attachments/assets/3749db01-bf0f-4582-8a4c-0290e3450d17)

**Comment by keminar** [comment]
编排的LLM设置有个  最大标记  或 叫 最大长度，修改试下
