### ISSUE TITLE
Cannot POST using knowledge API

### ISSUE THREAD

**Issue by mcathena** [langgenius/dify#2589]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I'm trying to use /datasets/{dataset_id}/document/create_by_file API.
My method is
1. query knowledge list from API and get my dataset_id
2. copied and replace dataset_id and api_key with my own (I hided my key and id in scripts below but when I code these variables were correct)
```
curl --location POST 'https://api.dify.ai/v1/datasets/{dataset_id}/document/create_by_file' \
--header 'Authorization: Bearer {api_key}' \
--form 'data="{"indexing_technique":"high_quality","process_rule":{"rules":{"pre_processing_rules":[{"id":"remove_extra_spaces","enabled":true},{"id":"remove_urls_emails","enabled":true}],"segmentation":{"separator":"###","max_tokens":500}},"mode":"custom"}}";type=text/plain' \
--form 'file=@"/path/to/file"'
```
3. returned error
```
Warning: Trailing data after quoted form parameter
curl: (26) Failed to open/read local data from file/application
```
5. the curl command above returned error so I tried to modify it into a python script
```
import requests

url = "http://127.0.0.1:5001/v1/datasets/{my_dataset_id_hide}/document/create_by_file"

headers = {
    "Authorization": "Bearer dataset-my-api-key-hide"
}

data = {
    "indexing_technique": "high_quality",
    "process_rule": {
        "rules": {
            "pre_processing_rules": [
                {"id": "remove_extra_spaces", "enabled": True},
                {"id": "remove_urls_emails", "enabled": True}
            ],
            "segmentation": {
                "separator": "###",
                "max_tokens": 500
            }
        },
        "mode": "custom"
    }
}

files = {
    'data': ('', str(data), 'text/plain'),
    'file': ('assistant.txt', open('/Users/linspirit/Downloads/assistant.txt', 'rb'))
}

response = requests.post(url, headers=headers, files=files)

print(response.text)
```
6. at first it showed internal server error because my knowledge base was empty
7. after adding some files to knowledge base, I tried create_by_file api
8. return 
```
"POST /v1/datasets/{my_dataset_id_hide_here}/document/create_by_file HTTP/1.1" 400 -
{
    "code": "too_many_files",
    "message": "Only one file is allowed.",
    "status": 400
}
```
Am I doing anything wrong here?

**Comment by mcathena** [comment]
> _🤖_
> 
> Hello @mcathena! 🌟 I'm Dosu, a friendly bot here to sprinkle some assistance while you wait for a human maintainer. Whether you're squashing bugs, have questions, or looking to contribute, I'm your go-to bot for help in the meantime. Let's dive into your issue and see what's going on, shall we? 🛠️

sure

**Comment by mcathena** [comment]
> _🤖_
> 
> Based on the information you've provided and the context from the repository, it seems like there are a couple of issues with your current approach.
> 
> Firstly, the error "Only one file is allowed" is due to the `TooManyFilesError` exception being raised. This exception is raised when more than one file is attempted to be uploaded in a single request to the API endpoint that expects only a single file. In your Python script, you're trying to upload the 'data' and 'file' in the same request which is causing the issue. You should ensure that your Python script is configured to upload only one file per request to the specified API endpoint. You can find more details about this in the [error.py](https://github.com/langgenius/dify/blob/main/api/controllers/service_api/dataset/error.py) file.
> 
> Secondly, the 'data' field in your Python script seems to be incorrectly formatted. The correct format for the 'data' field when making a request to the `/datasets/{dataset_id}/document/create_by_file` API endpoint is a JSON object that includes at least the following keys: `doc_form`, `doc_language`, and `indexing_technique`. You can find more details about this in the [document.py](https://github.com/langgenius/dify/blob/main/api/controllers/service_api/dataset/document.py) file.
> 
> Lastly, based on a similar solved issue in the repository, it seems like the 'data' field should be sent as a string in the form data. You can refer to the [issue #2164](https://github.com/langgenius/dify/issues/2164) for more details.
> 
> Here's how you can modify your Python script:
> 
> ```python
> import requests
> import json
> 
> url = "http://127.0.0.1:5001/v1/datasets/{my_dataset_id_hide}/document/create_by_file"
> 
> headers = {
>     "Authorization": "Bearer dataset-my-api-key-hide"
> }
> 
> data = {
>     "doc_form": "text_model",
>     "doc_language": "English",
>     "indexing_technique": "high_quality",
>     "process_rule": {
>         "rules": {
>             "pre_processing_rules": [
>                 {"id": "remove_extra_spaces", "enabled": True},
>                 {"id": "remove_urls_emails", "enabled": True}
>             ],
>             "segmentation": {
>                 "separator": "###",
>                 "max_tokens": 500
>             }
>         },
>         "mode": "custom"
>     }
> }
> 
> files = {
>     'data': ('', json.dumps(data), 'text/plain'),
>     'file': ('assistant.txt', open('/Users/linspirit/Downloads/assistant.txt', 'rb'))
> }
> 
> response = requests.post(url, headers=headers, files=files)
> 
> print(response.text)
> ```
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [bad_request_key_error:The browser (or proxy) sent a request that this server could not understand.](https://github.com/langgenius/dify/issues/2164)
> * [api/controllers/service_api/dataset/error.py](https://github.com/langgenius/dify/blob/main/api/controllers/service_api/dataset/error.py)
> * [api/controllers/service_api/dataset/document.py](https://github.com/langgenius/dify/blob/main/api/controllers/service_api/dataset/document.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I referred to [issue 2164](https://github.com/langgenius/dify/issues/2164). However, I still wasn't able to get it to work. 
my curl is
```
curl --location POST 'http://127.0.0.1:5001/v1/datasets/{my_dataset_id}/document/create_by_file' \
--header 'Authorization: Bearer dataset-my-api-key' \
--form 'data="{"name":"assistant","indexing_technique":"high_quality","process_rule":{"rules":{"pre_processing_rules":[{"id":"remove_extra_spaces","enabled":true},{"id":"remove_urls_emails","enabled":true}],"segmentation":{"separator":"###","max_tokens":500}},"mode":"custom"}}";type=text/plain' \
--form 'file=@"/Users/linspirit/Downloads/assistant.txt"'
```
returned error 
```
{
    "code": "invalid_param",
    "message": "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)",
    "status": 400
}
```

**Comment by mcathena** [comment]
issue solved. should be 

curl --location POST 'http://127.0.0.1:5001/v1/datasets/{dataset_id}/document/create_by_file' \
--header 'Authorization: Bearer {api-key}' \
--form 'data={"name":"assistant","indexing_technique":"high_quality","process_rule":{"rules":{"pre_processing_rules":[{"id":"remove_extra_spaces","enabled":true},{"id":"remove_urls_emails","enabled":true}],"segmentation":{"separator":"###","max_tokens":500}},"mode":"custom"}};type=text/plain' \
--form 'file=@assistant.txt'

**Comment by zzw1123** [comment]
> issue solved. should be
> 
> curl --location POST '[http://127.0.0.1:5001/v1/datasets/{dataset_id}/document/create_by_file](http://127.0.0.1:5001/v1/datasets/%7Bdataset_id%7D/document/create_by_file)' --header 'Authorization: Bearer {api-key}' --form 'data={"name":"assistant","indexing_technique":"high_quality","process_rule":{"rules":{"pre_processing_rules":[{"id":"remove_extra_spaces","enabled":true},{"id":"remove_urls_emails","enabled":true}],"segmentation":{"separator":"###","max_tokens":500}},"mode":"custom"}};type=text/plain' --form 'file=@assistant.txt'

Perfect answer!

**Comment by lyh007** [comment]
Can you post the complete Python code?

**Comment by lyh007** [comment]
以下代码测试通过：
import json
import os
import requests
from core.utils.json_utils import format_json_str, format_json_obj
import time

"""
Dify知识库批量上传
"""
# 数据库标识
database_id = "d073dd00-6be2-4c78-81f0-6cd9ffc29054"
# 知识库上传URL
knowledge_upload_url = f"http://192.168.59.107//v1/datasets/{database_id}/document/create_by_file"
# secret key
secret_key = "dataset-iciuDYqDSpA0wiqYwZGAH9gM"
# 指定要上传的文件扩展名
file_extensions = ['.pdf', '.doc', '.docx']

# 请求头
headers = {
    "Authorization": f"Bearer {secret_key}"
}
request_param = {
    "indexing_technique": "high_quality",
    "process_rule": {
        "rules": {
            "pre_processing_rules": [
                {
                    "id": "remove_extra_spaces",
                    "enabled": True
                },
                {
                    "id": "remove_urls_emails",
                    "enabled": True
                }
            ],
            "segmentation": {
                "separator": "###",
                "max_tokens": 800,
                "chunk_overlap": 200
            }
        },
        "mode": "custom"
    }
}


# 上传文件到 Dify
def upload_file(file_path):
    print("线程停止50秒后继续执行")
    time.sleep(50)
    with open(file_path, 'rb') as f:
        files = {
            'file': (os.path.basename(file_path), f)
        }
        data = {
            'data': json.dumps(request_param)
        }
        response = requests.post(knowledge_upload_url, headers=headers, files=files, data=data)
        if response.status_code == 200:
            print(f"成功上传: {file_path}")
            print(format_json_obj(response.json()))
        else:
            print(f"上传失败: {file_path}, 状态码: {response.status_code}, 错误信息: {response.text}")


# 遍历目录及子目录，上传指定扩展名的文件
def upload_files_from_directory(root_dir):
    for root, dirs, files in os.walk(root_dir):
        for file in files:
            if any(file.endswith(ext) for ext in file_extensions):
                file_path = os.path.join(root, file)
                upload_file(file_path)


if __name__ == '__main__':
    root_directory = 'd://doctmp'  # 替换为实际的目录路径
    upload_files_from_directory(root_directory)

**Comment by lyh007** [comment]
`import json
import os
import requests
from core.utils.json_utils import format_json_str, format_json_obj
import time

"""
Dify知识库批量上传
"""
# 数据库标识
database_id = "d073dd00-6be2-4c78-81f0-6cd9ffc29054"
# 知识库上传URL
knowledge_upload_url = f"http://192.168.59.107//v1/datasets/{database_id}/document/create_by_file"
# secret key
secret_key = "dataset-iciuDYqDSpA0wiqYwZGAH9gM"
# 指定要上传的文件扩展名
file_extensions = ['.pdf', '.doc', '.docx']

# 请求头
headers = {
    "Authorization": f"Bearer {secret_key}"
}
request_param = {
    "indexing_technique": "high_quality",
    "process_rule": {
        "rules": {
            "pre_processing_rules": [
                {
                    "id": "remove_extra_spaces",
                    "enabled": True
                },
                {
                    "id": "remove_urls_emails",
                    "enabled": True
                }
            ],
            "segmentation": {
                "separator": "###",
                "max_tokens": 800,
                "chunk_overlap": 200
            }
        },
        "mode": "custom"
    }
}


# 上传文件到 Dify
def upload_file(file_path):
    print("线程停止50秒后继续执行")
    time.sleep(50)
    with open(file_path, 'rb') as f:
        files = {
            'file': (os.path.basename(file_path), f)
        }
        data = {
            'data': json.dumps(request_param)
        }
        response = requests.post(knowledge_upload_url, headers=headers, files=files, data=data)
        if response.status_code == 200:
            print(f"成功上传: {file_path}")
            print(format_json_obj(response.json()))
        else:
            print(f"上传失败: {file_path}, 状态码: {response.status_code}, 错误信息: {response.text}")


# 遍历目录及子目录，上传指定扩展名的文件
def upload_files_from_directory(root_dir):
    for root, dirs, files in os.walk(root_dir):
        for file in files:
            if any(file.endswith(ext) for ext in file_extensions):
                file_path = os.path.join(root, file)
                upload_file(file_path)


if __name__ == '__main__':
    root_directory = 'd://doctmp'  # 替换为实际的目录路径
    upload_files_from_directory(root_directory)
`

**Comment by lyh007** [comment]
`python`
import json
import os
import requests
from core.utils.json_utils import format_json_str, format_json_obj
import time

"""
Dify知识库批量上传
"""
# 数据库标识
database_id = "d073dd00-6be2-4c78-81f0-6cd9ffc29054"
# 知识库上传URL
knowledge_upload_url = f"http://192.168.59.107//v1/datasets/{database_id}/document/create_by_file"
# secret key
secret_key = "dataset-iciuDYqDSpA0wiqYwZGAH9gM"
# 指定要上传的文件扩展名
file_extensions = ['.pdf', '.doc', '.docx']

# 请求头
headers = {
    "Authorization": f"Bearer {secret_key}"
}
request_param = {
    "indexing_technique": "high_quality",
    "process_rule": {
        "rules": {
            "pre_processing_rules": [
                {
                    "id": "remove_extra_spaces",
                    "enabled": True
                },
                {
                    "id": "remove_urls_emails",
                    "enabled": True
                }
            ],
            "segmentation": {
                "separator": "###",
                "max_tokens": 800,
                "chunk_overlap": 200
            }
        },
        "mode": "custom"
    }
}


# 上传文件到 Dify
def upload_file(file_path):
    print("线程停止50秒后继续执行")
    time.sleep(50)
    with open(file_path, 'rb') as f:
        files = {
            'file': (os.path.basename(file_path), f)
        }
        data = {
            'data': json.dumps(request_param)
        }
        response = requests.post(knowledge_upload_url, headers=headers, files=files, data=data)
        if response.status_code == 200:
            print(f"成功上传: {file_path}")
            print(format_json_obj(response.json()))
        else:
            print(f"上传失败: {file_path}, 状态码: {response.status_code}, 错误信息: {response.text}")


# 遍历目录及子目录，上传指定扩展名的文件
def upload_files_from_directory(root_dir):
    for root, dirs, files in os.walk(root_dir):
        for file in files:
            if any(file.endswith(ext) for ext in file_extensions):
                file_path = os.path.join(root, file)
                upload_file(file_path)


if __name__ == '__main__':
    root_directory = 'd://doctmp'  # 替换为实际的目录路径
    upload_files_from_directory(root_directory)
