### ISSUE TITLE
moonshot bug

### ISSUE THREAD

**Issue by zfno111** [langgenius/dify#2590]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when i use moonshot test,i got error like that
![moonshot](https://github.com/langgenius/dify/assets/32893310/27b3efaa-f873-44b3-ae43-a9c8490fc57a)

**Comment by all4you** [comment]
I add moonshot-v1-32k/moonshot-v1-8k success, but it sees that something is wrong:
![image](https://github.com/langgenius/dify/assets/6661305/628b3bcf-2e84-401a-a100-cd4e44746279)
and when i do test in workflow, error occurred:
![image](https://github.com/langgenius/dify/assets/6661305/31e89e46-5519-4333-a5ba-087439b82f46)
