### ISSUE TITLE
The conversation with the large model was suddenly cut off.

### ISSUE THREAD

**Issue by Jas0nxlee** [langgenius/dify#2592]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The information returned during the conversation with the large model suddenly cut off. This situation occurs in every conversation.
![WechatIMG48](https://github.com/langgenius/dify/assets/33084918/09be9018-acbd-4c09-ad50-3ef7fe0d956f)

**Comment by crazywoola** [comment]
Please set the `num_predict` or `max tokens`.

**Comment by realcarlos** [comment]
> Please set the `num_predict` or `max tokens`.

could you please tell where to set?
