### ISSUE TITLE
Got bad results on OLLAMA Dify

### ISSUE THREAD

**Issue by ntvuongg** [langgenius/dify#2599]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Dify version: 0.5.6

Cloud or Self Hosted: Self Hosted (Docker)

Steps to reproduce: Input query string 

✔️ Expected Behavior

It should be as good as result of LMStudio or OLLAMA.

❌ Actual Behavior
Results repeating and not format as same as LM Studio or OLLAMA

Maybe it comes from params setting. Anyway to solve this?

**Comment by Yeuoly** [comment]
Could you pls provider a screenshot of it?
