### ISSUE TITLE
私有部署怎么注册账号？

### ISSUE THREAD

**Issue by CaesarC** [langgenius/dify#26]
只有开始的管理员设置
请问一下signup 和 Oauth哪里开启？

**Comment by charli117** [comment]
同问，这个问题，可以配置自有Oauth认证么？

**Comment by takatost** [comment]
EDITION 都改为 CLOUD 即可，暂时没有这块的文档，OAuth 相关配置可以在 config.py 可以看到。

**Comment by CaesarC** [comment]
CLOUD的话就没有账号密码注册了，是吗？

**Comment by takatost** [comment]
> CLOUD的话就没有账号密码注册了，是吗？

是，目前没有开发自助注册功能，只有团队邀请

**Comment by m199369309** [comment]
是否支持跟keycloak进行openid的sso认证对接？

**Comment by takatost** [comment]
> 是否支持跟keycloak进行openid的sso认证对接？

目前暂不支持，您可以二次开发，如果可以也希望能够贡献一份力量，感激不尽

**Comment by chengjuny1978** [comment]
只能注册 一个账号吗？？没有注册的入口了
