### ISSUE TITLE
there is no voice2text feature in Open source version?

### ISSUE THREAD

**Issue by WSDzju** [langgenius/dify#2611]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

feature enhancement

### 2. Describe the feature you'd like to see

this feature is equipped in the Cloud version

### 3. How will this feature improve your workflow or experience?

user experience
![image](https://github.com/langgenius/dify/assets/147698475/7bd4db56-0b26-4c18-91dd-feb8da25c5ff)

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by WSDzju** [comment]
> _🤖_
> 
> It seems like you've got this under control, if you want help or have specific questions, let me know what I can do for you!
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Will the voice2text feature currently  in Cloud version be added to the open source verison ?

**Comment by crazywoola** [comment]
We do have these 2 functions in our application. I think there might be something wrong with the configuration.

**Comment by WSDzju** [comment]
> We do have these 2 functions in our application. I think there might be something wrong with the configuration.

I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow

**Comment by crazywoola** [comment]
> > We do have these 2 functions in our application. I think there might be something wrong with the configuration.
> 
> I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow

I am not sure if this is a bug. You are not having voice to text on old application and new application both?

**Comment by WSDzju** [comment]
> > > We do have these 2 functions in our application. I think there might be something wrong with the configuration.
> > 
> > 
> > I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow
> 
> I am not sure if this is a bug. You are not having voice to text on old application and new application both?

both,

**Comment by crazywoola** [comment]
> > > > We do have these 2 functions in our application. I think there might be something wrong with the configuration.
> > > 
> > > 
> > > I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow
> > 
> > 
> > I am not sure if this is a bug. You are not having voice to text on old application and new application both?
> 
> both,

If delete the whole docker containers images and the everything under docker/volumnes is ok for you. Can you try to remove those and start it again?

**Comment by WSDzju** [comment]
> > > > > We do have these 2 functions in our application. I think there might be something wrong with the configuration.
> > > > 
> > > > 
> > > > I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow
> > > 
> > > 
> > > I am not sure if this is a bug. You are not having voice to text on old application and new application both?
> > 
> > 
> > both,
> 
> If delete the whole docker containers images and the everything under docker/volumnes is ok for you. Can you try to remove those and start it again?

I am in the middle of some sort of developement. you mean this issue may be solved by redeploying docker compose? here is the same issue https://github.com/langgenius/dify/issues/745

**Comment by crazywoola** [comment]
> > > > > > We do have these 2 functions in our application. I think there might be something wrong with the configuration.
> > > > > 
> > > > > 
> > > > > I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow
> > > > 
> > > > 
> > > > I am not sure if this is a bug. You are not having voice to text on old application and new application both?
> > > 
> > > 
> > > both,
> > 
> > 
> > If delete the whole docker containers images and the everything under docker/volumnes is ok for you. Can you try to remove those and start it again?
> 
> I am in the middle of some sort of developement. you mean this issue may be solved by redeploying docker compose? here is the same issue #745

Maybe, because we don't have restrictions on this feature in both versions.  And can you check the model provider config to see if you have any speech_to_text models?

**Comment by WSDzju** [comment]
> > > > > > > We do have these 2 functions in our application. I think there might be something wrong with the configuration.
> > > > > > 
> > > > > > 
> > > > > > I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow
> > > > > 
> > > > > 
> > > > > I am not sure if this is a bug. You are not having voice to text on old application and new application both?
> > > > 
> > > > 
> > > > both,
> > > 
> > > 
> > > If delete the whole docker containers images and the everything under docker/volumnes is ok for you. Can you try to remove those and start it again?
> > 
> > 
> > I am in the middle of some sort of developement. you mean this issue may be solved by redeploying docker compose? here is the same issue #745
> 
> Maybe, because we don't have restrictions on this feature in both versions. And can you check the model provider config to see if you have any speech_to_text models?

I have got the speech2text_model.py file:
import os
from abc import abstractmethod
from typing import IO, Optional

from core.model_runtime.entities.model_entities import ModelType
from core.model_runtime.model_providers.__base.ai_model import AIModel


class Speech2TextModel(AIModel):
    """
    Model class for speech2text model.
    """
    model_type: ModelType = ModelType.SPEECH2TEXT

    def invoke(self, model: str, credentials: dict,
               file: IO[bytes], user: Optional[str] = None) \
            -> str:
        """
        Invoke large language model

        :param model: model name
        :param credentials: model credentials
        :param file: audio file
        :param user: unique user id
        :return: text for given audio file
        """
        try:
            return self._invoke(model, credentials, file, user)
        except Exception as e:
            raise self._transform_invoke_error(e)

    @abstractmethod
    def _invoke(self, model: str, credentials: dict,
                file: IO[bytes], user: Optional[str] = None) \
            -> str:
        """
        Invoke large language model

        :param model: model name
        :param credentials: model credentials
        :param file: audio file
        :param user: unique user id
        :return: text for given audio file
        """
        raise NotImplementedError

    def _get_demo_file_path(self) -> str:
        """
        Get demo file for given model

        :return: demo file
        """
        # Get the directory of the current file
        current_dir = os.path.dirname(os.path.abspath(__file__))

        # Construct the path to the audio file
        return os.path.join(current_dir, 'audio.mp3')

**Comment by WSDzju** [comment]
> > > > > > > We do have these 2 functions in our application. I think there might be something wrong with the configuration.
> > > > > > 
> > > > > > 
> > > > > > I deploy using Docker Compose. How can I modify the configuration? or is there any tutorial to follow
> > > > > 
> > > > > 
> > > > > I am not sure if this is a bug. You are not having voice to text on old application and new application both?
> > > > 
> > > > 
> > > > both,
> > > 
> > > 
> > > If delete the whole docker containers images and the everything under docker/volumnes is ok for you. Can you try to remove those and start it again?
> > 
> > 
> > I am in the middle of some sort of developement. you mean this issue may be solved by redeploying docker compose? here is the same issue #745
> 
> Maybe, because we don't have restrictions on this feature in both versions. And can you check the model provider config to see if you have any speech_to_text models?

here is my another question: Since there are many models provided by Baidu cloud platform. Can I add some other models like xuanyuan-70b-chat. with the modificaiton when using docker compose? I have trie, seems does not work:
![image](https://github.com/langgenius/dify/assets/147698475/a97280d8-6f06-4a80-b1f8-04e130f600ce)
with "
class ErnieBotModel:
    api_bases = {
        'ernie-bot': 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions',
        'ernie-bot-4': 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro',
        'ernie-bot-8k': 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie_bot_8k',
        'ernie-bot-turbo': 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/eb-instant',
        'xuanyuan-70b-chat':'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/xuanyuan_70b_chat'
"

**Comment by crazywoola** [comment]
If you are using source code, it will load modified LLM models( based on your new json ) But if you use `docker compose up -d `. It needs to be built from scratch.

**Comment by WSDzju** [comment]
> If you are using source code, it will load modified LLM models( based on your new json ) But if you use `docker compose up -d `. It needs to be built from scratch.

THX, there seems lots of coding when using docker compose up -d  to modify models

**Comment by crazywoola** [comment]
> > If you are using source code, it will load modified LLM models( based on your new json ) But if you use `docker compose up -d `. It needs to be built from scratch.
> 
> THX, there seems lots of coding when using docker compose up -d to modify models Is there any guidelines for building from scatch when using docker compose up -d

This is a out-of-box solution, and it will stay as it is. You should always build things from source code. What I am saying about build from scratch means you code and you use `docker build . -t` like command and replace them in the `docker-compose.yaml` file. For more details, you should read [this](https://docs.dify.ai/) and official docker docs as well.

Did you solve this problem? Because I can not reproduce this issue.

**Comment by WSDzju** [comment]
> > > If you are using source code, it will load modified LLM models( based on your new json ) But if you use `docker compose up -d `. It needs to be built from scratch.
> > 
> > 
> > THX, there seems lots of coding when using docker compose up -d to modify models Is there any guidelines for building from scatch when using docker compose up -d
> 
> This is a out-of-box solution, and it will stay as it is. You should always build things from source code. What I am saying about build from scratch means you code and you use `docker build . -t` like command and replace them in the `docker-compose.yaml` file. For more details, you should read [this](https://docs.dify.ai/) and official docker docs as well.
> 
> Did you solve this problem? Because I can not reproduce this issue.

I tried to use `docker build . -t` , the container has built but cannot run. due to time constraint,  I will try later. THX!
