### ISSUE TITLE
Blank text on Tools

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2615]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After updating to 0.5.7, the tools do not show text:
![CleanShot 2024-02-28 at 20 54 48@2x](https://github.com/langgenius/dify/assets/119136210/ebf7a563-12f7-42b3-9d34-e66dbf623ca4)

### ✔️ Expected Behavior

Showing text description

### ❌ Actual Behavior

Blank text

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/2663
