### ISSUE TITLE
Language on API access tab

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2616]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After updating to 0.5.7 the API access tab on assistants are in not in English, even when language is set to English (United States):
![CleanShot 2024-02-28 at 20 59 08@2x](https://github.com/langgenius/dify/assets/119136210/8af4c5dd-592d-4425-9152-584d36fe85c9)

### ✔️ Expected Behavior

English language on the API access tab

### ❌ Actual Behavior

zh-Hans text

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/2615 Hello, Could you try to switch to another language and try it again? Also, clean the localstorage and cookies as well.

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/2663
