### ISSUE TITLE
Gemini pro return error

### ISSUE THREAD

**Issue by XiaoCC** [langgenius/dify#2617]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/7299222/4c55bddf-a552-4182-97ed-bb1849008a71)

```
[Google]Error: The response,parts quick accesor only works fora single candildate, butnone were retumed.Check the response,prompt feedback to seifthe prompt was blocked.
```
prompt：利用已有的工具，用中文回复用户的问题，你不知道的问题请联网搜索，可以利用用duckduckgo工具联网搜索，一定要用中文回复！回复尽量简单一点避免啰嗦。
![image](https://github.com/langgenius/dify/assets/7299222/749f894f-01d7-4cc4-b03e-e429785f7905)
![image](https://github.com/langgenius/dify/assets/7299222/ba4906c9-699b-4a0f-9722-69a7dc3ad502)

**Comment by Yeuoly** [comment]
What's your query to hit this error? I have no idea about how to reproduce it now, but it looks like your prompt was blocked by GeminiPro, you can check the error
```
but none were returned. Check the `response.prompt_feedback` to see if the prompt was blocked.
```

**Comment by guchenhe** [comment]
Hi! This may have been an [issue](https://github.com/google/generative-ai-python/issues/196) on gemini's side. I suggest also follow up on that issue.
