### ISSUE TITLE
Quick Tool Interation

### ISSUE THREAD

**Issue by ooclRico** [langgenius/dify#2618]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I have follow the instruction on the official document and try to add a quick tool interaction.
[https://docs.dify.ai/tutorials/quick-tool-integration](Quick Tool Intergration)

I am trying to test this function by just duplicate same file as the time and name it customize_time
![image](https://github.com/langgenius/dify/assets/151698755/a252f68b-004f-44b9-aec1-46dbd7ef5285)
![image](https://github.com/langgenius/dify/assets/151698755/27971c72-5988-4c51-b821-e2e987ed9e0e)

I try to run  `docker compose build`, but I cant find the tools from the tools pages

**Comment by Yeuoly** [comment]
Hello, the name of provider must be consistent with the module name, your module was named as `customized_time` but the name declared in the yaml was `time_new`
