### ISSUE TITLE
set openai key failed

### ISSUE THREAD

**Issue by LinightKira** [langgenius/dify#2619]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="521" alt="微信图片_20240229104016" src="https://github.com/langgenius/dify/assets/23732141/c80c2592-0318-432e-b8d7-a963952feb8c">
报错地址：
post:http://localhost/console/api/workspaces/current/model-providers/openai
无法设置openai key ，返回400  连接错误

### ✔️ Expected Behavior

set sucess

### ❌ Actual Behavior

400 ，connection error

**Comment by crazywoola** [comment]
Connection error means you need to have access api.openai.com

**Comment by LinightKira** [comment]
> Connection error means you need to have access api.openai.com

电脑开了全局代理，访问openai 很通畅

**Comment by 151819880412** [comment]
@LinightKira 我也遇到这个问题，使用阿里的到通义千问正常

**Comment by Imoke** [comment]
> > Connection error means you need to have access api.openai.com
> 
> 电脑开了全局代理，访问openai 很通畅
我也遇到这个问题，请问怎呢解决，也是全局代理
