### ISSUE TITLE
```An error occurred during credentials validation: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83cb7ee9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))``` when using ollama embedding

### ISSUE THREAD

**Issue by yongjer** [langgenius/dify#2624]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

select ollama text embedding:

model : nomic-embed-text
baseurl: http://localhost:11434/api/embeddings
context size:4096

### ✔️ Expected Behavior

successful add embedding model
successful generate result by curl:
```
curl http://localhost:11434/api/embeddings -d '{
  "model": "nomic-embed-text",
  "prompt": "the great kingdom of the world"
}'
```

### ❌ Actual Behavior

```An error occurred during credentials validation: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings/api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83cb7ee9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))```

**Comment by takatost** [comment]
https://docs.dify.ai/tutorials/model-configuration/ollama
Hi there, you can check out our help documentation to find a solution.

**Comment by yongjer** [comment]
Doesn't work whether using  http://localhost:11434/api/embeddings or  http://localhost:11434

**Comment by crazywoola** [comment]
It's not localhost. It should be your ip address. And please refer this answer as well.

> _🤖_
> 
> Based on the error message you provided, it seems like the Dify application is unable to establish a connection to the Ollama service running on localhost at port 11434. This could be due to several reasons, including Ollama not running, network misconfigurations, or firewall issues. Given that you are running Dify in a Docker environment, the most likely cause is a network misconfiguration between the Docker container where Dify is running and the host machine where Ollama is running.
> 
> Here are some steps you can follow to resolve this issue:
> 
> 1. **Ensure Ollama is Running**: First, make sure that Ollama is running and accessible at `http://localhost:11434` on the host machine. You can test this by using a tool like `curl` or by accessing the URL in a web browser.
> 2. **Use the Correct IP Address for Docker**: If Dify is deployed using Docker, `localhost` from within the Docker container will not point to the host machine. Instead, you need to use the Docker host's IP address. The documentation suggests using the local network IP address (e.g., `http://192.168.1.100:11434`) or the Docker host machine IP address (e.g., `http://172.17.0.1:11434`). Find out the correct IP address of your host machine from the Docker container's perspective and use that in the Dify Ollama configuration.
> 3. **Adjust Firewall Settings**: If there's a firewall running on your host machine, ensure that it allows incoming connections on port 11434.
> 4. **Set the `OLLAMA_HOST` Environment Variable**: If Ollama is binding to `127.0.0.1` by default, it won't be accessible from the Docker container. You need to change the bind address to `0.0.0.0` to make it accessible from other machines and Docker containers. This can be done by setting the `OLLAMA_HOST` environment variable to `0.0.0.0` before starting Ollama. The method to set this variable depends on your operating system.
> 
> After making these adjustments, restart Ollama and then try to add the model to Dify again. Ensure that you use the correct IP address in the Dify configuration for the Ollama Base URL.
> 
> For more information, you can refer to the [Dify documentation](https://github.com/langgenius/dify-docs/blob/main/en/tutorials/model-configuration/ollama.md) and this [similar solved issue](https://github.com/langgenius/dify/issues/2540) in the Dify repository.
> 
> Regarding the process to add a new text embedding model in Dify version 0.5.7, you can refer to the `text_embedding.py` file in the Dify repository. It provides a detailed guide on how to add a new text embedding model, including validating credentials, defining model invocation, customizing model schema, implementing text input key identification, implementing embeddings generation, calculating usage, and error handling. You can find the file [here](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/replicate/text_embedding/text_embedding.py).
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [Can't connect Dify with OLLAMA](https://github.com/langgenius/dify/issues/2540)
> * [en/tutorials/model-configuration/ollama.md](https://github.com/langgenius/dify-docs/blob/main/en/tutorials/model-configuration/ollama.md)
> * [api/core/model_runtime/model_providers/replicate/text_embedding/text_embedding.py](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/replicate/text_embedding/text_embedding.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
