### ISSUE TITLE
Questions about ReAct mode Agent

### ISSUE THREAD

**Issue by sunxichen** [langgenius/dify#2627]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

1. In ReAct mode, the Action prefix, Observation, Thought are also streamed. Is it by designed or a bug related to agent output parsing? Because user may only concern about final output, so I'm expecting only Final Answer should be streamed.
![截屏2024-02-29 15 34 59](https://github.com/langgenius/dify/assets/18310222/ba54cfd5-d47f-44a8-bda1-8e38fc24334c)

2. OpenAI/Azure OpenAI only support Function Calling mode, some other issues like #2517 also discussed this. I understand that function_calling may perform better than ReAct, maybe it would be better if it could be made changeable.

**Comment by takatost** [comment]
1. This should be related to the bug in ReACT and the output parse. The lack of precision in ReACT's output has caused many parsing issues.

   @Yeuoly, can you take a look at this issue? 🤔

3. As mentioned in 1, ReACT is not stable. Could you please explain why you prefer using ReACT instead of function calling?

**Comment by sunxichen** [comment]
> 2\. As mentioned in 1, ReACT is not stable. Could you please explain why you prefer using ReACT instead of function calling?

In my project, I can only use open-source LLMs to do reasoning using the ReAct mode. Sometimes, I need to use OpenAI models like gpt-3.5/gpt-4 to test the impact of different ReAct prompts, function/input parameter descriptions on agent performance first. But using the OpenAI model can only limit my use of function calling mode. Although I can temporarily bypass this limitation by using the openai_api_compatible model in Dify which actually connected to gpt-3.5/gpt-4, it still feels a bit inconvenient, so I think it might be better to switch between the two.

**Comment by Yeuoly** [comment]
> 1. This should be related to the bug in ReACT and the output parse. The lack of precision in ReACT's output has caused many parsing issues.
>    @Yeuoly, can you take a look at this issue? 🤔
> 2. As mentioned in 1, ReACT is not stable. Could you please explain why you prefer using ReACT instead of function calling?

1. It's actually a bug related to ReACT output parser. And as we known, different prompts and different LLMs could lead different output structures, such as 
```yaml
action: current_time
action_input:
```
```json
{"action":"current_time", "action_input":{}}
```
A simple output parser hardcoded could not handle a wide variety of prompts, the final result is what you saw, have you got any good idea of doing that?

**Comment by Yeuoly** [comment]
@vikeychen help take a look at this requirement?

**Comment by sunxichen** [comment]
> A simple output parser hardcoded could not handle a wide variety of prompts

I agree with you, It is hard to implement a general output parser. Now that I know this is not by designed, my doubts have been resolved.

> have you got any good idea of doing that?

You can consider using a guided generation library (like [Outlines](https://github.com/outlines-dev/outlines)) to implement ReAct, so that every step during the ReAct process is controllable. You can limit the output of LLM to be exactly the same as the format you want by using regex (and also limit the output of LLM to conform to the defined JSON format, which is important for action input), so you don't have to spend a lot of efforts on output parsers. Furthermore, you can refer to this implementation [example](https://github.com/outlines-dev/outlines/blob/main/examples/react.py).
