### ISSUE TITLE
Show「You have reached the limit of your subscription.」

### ISSUE THREAD

**Issue by xmsz-stu** [langgenius/dify#2629]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

```
data: {
      code: 'unauthorized',
      message: 'You have reached the limit of your subscription.',
      status: 401
    }
```

Why this happend?

**Comment by crazywoola** [comment]
Obviously :)
> You have reached the limit of your subscription.

**Comment by xmsz-stu** [comment]
> Contributor
> ###

<img width="694" alt="image" src="https://github.com/langgenius/dify/assets/139225486/7a8acc3c-c232-4250-a552-f8db9218f47c">

Which is the limit of subscription

**Comment by GarfieldDai** [comment]
Your vector space is out of limit. It seems the problem is frontend cache. Plz refresh browser and you can see true vector space.
@xmsz-stu

**Comment by xmsz-stu** [comment]
> Your vector space is out of limit. It seems the problem is frontend cache. Plz refresh browser and you can see true vector space. @xmsz-stu

ok

- How do I know the vector space size used by each article?
- I only have 135 articles now, and 58 thousand characters feel too few.
- How do I recover the vector space? Does deleting articles recover it?
- How do I control the size of my vector space, such as by limiting the character length of articles?

**Comment by GarfieldDai** [comment]
- How do I know the vector space size used by each article?
    > total_words_size = words * 3
    > total_vector_size = 1536 * 4 * document_segments_size
    > vector_size = (total_words_size + total_vector_size) / 1024 / 1024
- I only have 135 articles now, and 58 thousand characters feel too few.
    > Your total_vector_size is almost 4.8 MB（1536 * 4 * 822 / 1024 / 1024）. Because you have many document segments.
- How do I recover the vector space? Does deleting articles recover it?
    > Yes. You also can make a professional subscription to get 200 MB vector space.
- How do I control the size of my vector space, such as by limiting the character length of articles?
    > Refer above calculation, you should make your document segment more suitable.

**Comment by xmsz-stu** [comment]
> * How do I know the vector space size used by each article?
>   > total_words_size = words * 3
>   > total_vector_size = 1536 * 4 * document_segments_size
>   > vector_size = (total_words_size + total_vector_size) / 1024 / 1024
> * I only have 135 articles now, and 58 thousand characters feel too few.
>   > Your total_vector_size is almost 4.8 MB（1536 * 4 * 822 / 1024 / 1024）. Because you have many document segments.
> * How do I recover the vector space? Does deleting articles recover it?
>   > Yes. You also can make a professional subscription to get 200 MB vector space.
> * How do I control the size of my vector space, such as by limiting the character length of articles?
>   > Refer above calculation, you should make your document segment more suitable.

ok
I deleted files, but still can't upload
<img width="373" alt="image" src="https://github.com/langgenius/dify/assets/139225486/d1ed637a-fb37-4637-9113-72c5bd2ee880">
<img width="385" alt="image" src="https://github.com/langgenius/dify/assets/139225486/8853abc8-ef14-4060-9568-e6850acbb602">

**Comment by GarfieldDai** [comment]
The reason is that the size of documents is out of limit. Sandbox only have 50 quota for documents upload. There was a update yesterday.
![image](https://github.com/langgenius/dify/assets/28395549/dace9311-7d4a-4fd6-9a03-5ae0f04a79e7)

**Comment by xmsz-stu** [comment]
> The reason is that the size of documents is out of limit. Sandbox only have 50 quota for documents upload. There was a update yesterday. ![image](https://private-user-images.githubusercontent.com/28395549/309627818-dace9311-7d4a-4fd6-9a03-5ae0f04a79e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzI1NDEsIm5iZiI6MTcwOTUzMjI0MSwicGF0aCI6Ii8yODM5NTU0OS8zMDk2Mjc4MTgtZGFjZTkzMTEtN2Q0YS00ZmQ2LTlhMDMtNWFlMGYwNGE3OWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA2MDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZDRiYWU0MTIxNGJlOWQ2N2E0NzA5YzQwZGI2ZWIyM2VkNjNjZmE5NDY3Yjc4YzM3Nzc1ZDkyYjE2MWIxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHIBI7zaeGR3XOyM65CS8uJSWS1ZCbf3K1P-TPvzOn8)

Alright
