### ISSUE TITLE
how to configure nginx subpath proxy like: https://my.com/dify/

### ISSUE THREAD

**Issue by maoniangv5** [langgenius/dify#263]
如题，修改nginx和config都没有实现，目前占用根域名/导致其他系统异常，想配置以下访问入口https://my.com/dify/
比如以下配置
how to configure nginx subpath proxy like: https://my.com/dify/
the following config have no effect, and the static files redirect to root domain
```
        location /dify/ {
                proxy_pass  http://127.0.0.1:8899/;
                proxy_redirect off;
        }
```

**Comment by diaojunxian** [comment]
你好，能分享一下 nginx 下的 location 的配置和设置吗？我感觉都被搞懵了。对于 app url 和 web url 各种设置不知道怎么配置？

**Comment by yxtwl94** [comment]
修改源码next.config.js文件，修改
const nextConfig = {
  basePath: '/dify',
  assetPrefix: '/dify',
  webpack: (config, { dev, isServer }) => {
    config.plugins.push(codeInspectorPlugin({ bundler: 'webpack' }))
    return config
  },
。。。。
}
加上dify前缀，这样静态文件才能引用
