### ISSUE TITLE
The setting for "Agent Mode" in the smart assistant cannot be modified.

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#2630]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Because the default ReAct reasoning success rate for Agent Mode is too low, is it possible to modify Agent Mode? What are the modes available for Agent Mode?

- This is using Xinference to access ChatGLM3-6B.

![1](https://github.com/langgenius/dify/assets/21255047/452df678-5dec-4357-bc64-b13465d53f1c)

![2](https://github.com/langgenius/dify/assets/21255047/88cb0b08-464e-4eca-b535-604a4689902e)

![3](https://github.com/langgenius/dify/assets/21255047/b64325f9-56a0-40ac-be10-2dbe1698522b)

- This is using openai_api to access ChatGLM3-6B.

![4](https://github.com/langgenius/dify/assets/21255047/d4d18366-3b34-4c33-8df5-1bf8fb3f7286)

![5](https://github.com/langgenius/dify/assets/21255047/7cc0b964-c16d-4d93-9c8b-25ffafc77df6)

**Comment by crazywoola** [comment]
This is not a `bug`. :) Please use the right template to fire an issue.
