### ISSUE TITLE
login failed with no exception logs from both the api and the web pod

### ISSUE THREAD

**Issue by dbug-dk** [langgenius/dify#2633]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

i use the image to deploy some pods in my k8s cluster。after deploy complete and reset password，I am unable to log in, and I can only see error messages in the Chrome console. When I check the logs of the Nginx, API, and web pods using kubectl logs, there are no error outputs.
![image](https://github.com/langgenius/dify/assets/7811716/e7250de2-9082-4984-9ad6-3818664c121d)

I have created a service for each pod and use these services for communication, which also results in the web and API having different domain names. 

Is it necessary for the api and the web to use the same domain name?

To add on, I can successfully make a login request to the API using curl from the Nginx pod.

![image](https://github.com/langgenius/dify/assets/7811716/49c3cade-6af3-4898-8245-b0a5e65a3d99)

my nginx default.conf is as follows:
server {
    listen 80;
    server_name _;

    location /console/api {
      proxy_pass http://difyapi-api-service.difyapi.svc.cluster.local:5001;
      include proxy.conf;
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' '*';
      add_header 'Access-Control-Allow-Headers' 'Content-Type, Content-Length, Authorization, Accept, X-Requested-With';
      add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location /api {
      proxy_pass http://difyapi-api-service.difyapi.svc.cluster.local:5001;
      include proxy.conf;
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' '*';
      add_header 'Access-Control-Allow-Headers' 'Content-Type, Content-Length, Authorization, Accept, X-Requested-With';
      add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location /v1 {
      proxy_pass http://difyapi-api-service.difyapi.svc.cluster.local:5001;
      include proxy.conf;
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' '*';
      add_header 'Access-Control-Allow-Headers' 'Content-Type, Content-Length, Authorization, Accept, X-Requested-With';
      add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location /files {
      proxy_pass http://difyapi-api-service.difyapi.svc.cluster.local:5001;
      include proxy.conf;
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' '*';
      add_header 'Access-Control-Allow-Headers' 'Content-Type, Content-Length, Authorization, Accept, X-Requested-With';
      add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location / {
      proxy_pass http://difyapi-web-service.difyapi.svc.cluster.local:3000;
      include proxy.conf;
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' '*';
      add_header 'Access-Control-Allow-Headers' 'Content-Type, Content-Length, Authorization, Accept, X-Requested-With';
      add_header 'Access-Control-Allow-Credentials' 'true';
    }
}

### ✔️ Expected Behavior

login success

### ❌ Actual Behavior

can not login

**Comment by takatost** [comment]
If the front-end and back-end are not on the same domain, you need to set the corresponding URL as mentioned in the help document below:

https://docs.dify.ai/getting-started/install-self-hosted/environments#console_api_url

**Comment by dbug-dk** [comment]
> If the front-end and back-end are not on the same domain, you need to set the corresponding URL as mentioned in the help document below:
> 
> https://docs.dify.ai/getting-started/install-self-hosted/environments#console_api_url

Thank you for reply。I have already set all the environments on my pod。
CONSOLE_WEB_URL="http://difyapi-web-service.difyapi.svc.cluster.local:3000"
CONSOLE_API_URL="http://difyapi-api-service.difyapi.svc.cluster.local:5001"
SERVICE_API_URL="http://difyapi-api-service.difyapi.svc.cluster.local:5001"
APP_WEB_URL="http://difyapi-web-service.difyapi.svc.cluster.local:3000"

is there anything wrong or missing？

**Comment by dbug-dk** [comment]
CONSOLE_API_URL and CONSOLE_WEB_URL all set as the nginx service domain name can solve this problem
