### ISSUE TITLE
Keywords are not extracted in Farsi (Persian) documents

### ISSUE THREAD

**Issue by MitraSafarinejad** [langgenius/dify#2634]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

hello,
I work on Farsi documents and after I upload my documents, I check the document and at the bottom of each chunk I can not see any keywords (see the picture below)
unless I have some English words or numbers in my documents.
Does Dify support any language other than English or Chinese for extracting keywords?
![Untitled](https://github.com/langgenius/dify/assets/39375115/b8ea7f60-7923-4ca7-b13c-6e05a23fb6f3)

**Comment by JohnJyong** [comment]
Unfortunately, Jieba currently does not support Persian word segmentation. I think you can try the high-quality mode in the Knowledge module . It supports vector similarity matching, full-text retrieval and Rerank, which will make your retrieval more accurate. 
Of course, we will also introduce ES and support Persian word segmentation in the future, so stay tuned. @MitraSafarinejad

**Comment by MitraSafarinejad** [comment]
hello,
this issue is still there. Dify does not support Farsi for keyword extraction, and I used the high-quality mode in the Knowledge module as an alternative but it did not solve my problem.
I'd appreciate it if you could support the Farsi language

**Comment by crazywoola** [comment]
Hi there, we will try to fix this.

**Comment by d8rt8v** [comment]
@crazywoola hi, any updates on this? 

I've experienced the same issue with russian language (Enabling high-quality mode doesnt help neither)
