### ISSUE TITLE
Gemini Pro GCP Vertex support

### ISSUE THREAD

**Issue by ov3rload1ng** [langgenius/dify#2635]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Hi there! I would like to know if there are any plans to use the Gemini Pro model enterprise version of Google Cloud Vertex or if there is already a way to use it.

**Comment by takatost** [comment]
Hey, we currently don't have the capacity to integrate models from GCP Vertex provider at the moment. If you're interested, you can refer to this document to integrate them yourself. We would really appreciate it!

https://github.com/langgenius/dify/blob/main/api/core/model_runtime/README.md
