### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

### ISSUE THREAD

**Issue by heywiorld** [langgenius/dify#2637]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

hi team, we write self define  tool, but when test return error:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

yml content is as follow:
```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Webhook Test API
servers:
  - url: https://test.com/n8n
    variables:
      server:
        default: test.com
paths:
  /webhook/93b273e7-4b90-4d19-a8c2-690296e935f8/:
    post:
      summary: Get VT and Threat Book IP result
      operationId: VT and TB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                ip:
                  type: string
                  description: IP address for the test
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebhookTestResponse"
      security:
        - ApiKeyAuth: []
components:
  schemas:
    WebhookTestResponse:
      type: object
      properties:
        response_message:
          type: string
          description: Response message from the webhook execution
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-apikey
      in: header
security:
  - ApiKeyAuth: []
```

### ✔️ Expected Behavior

return webhook result.

### ❌ Actual Behavior

return error:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
![QQ截图20240301090523](https://github.com/langgenius/dify/assets/43668597/5dc002b3-3ca0-4bcd-83b1-784eb28e33ac)

**Comment by takatost** [comment]
Is the HTTPS certificate correct when accessing the API directly?

**Comment by heywiorld** [comment]
> Is the HTTPS certificate correct when accessing the API directly?

yes

**Comment by takatost** [comment]
> > Is the HTTPS certificate correct when accessing the API directly?
> 
> yes

Hey, could you please provide more details? Such as the provider of the certificate, the type, etc. It would help us to reproduce the issue.

**Comment by heywiorld** [comment]
> > > Is the HTTPS certificate correct when accessing the API directly?
> > 
> > 
> > yes
> 
> Hey, could you please provide more details? Such as the provider of the certificate, the type, etc. It would help us to reproduce the issue.

think key point is not cert of https://test.com, as error is unable to get local.
certificate for test.com is made by our company, valid.

**Comment by raccoonex** [comment]
@insistence-essenn see my answer [here](https://github.com/langgenius/dify/discussions/4600#discussioncomment-9580322)
