### ISSUE TITLE
Adding Google Maps Integration to Existing Google Tools Platform

### ISSUE THREAD

**Issue by Yash-1511** [langgenius/dify#2640]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

## Description
The current Tools integration in Google Tools only integrates with Google Search and requires a SERP API key for authorization. This issue proposes adding Google Maps functionality to the platform. This functionality would require a separate Google Maps API key for authorization. Ideally, users should be able to choose between using only Google Search, only Google Maps, or both simultaneously. However, the current platform design doesn't support managing multiple API keys and enabling selective tool usage.

## Proposed Solutions:

1. Enhance existing Google tools:

- Modify the platform to accept and manage both SERP API keys (for Google Search) and Google Maps API keys.
- Implement logic to allow users to choose between using either tool individually or both concurrently.

2. Create separate Google Maps tool:

- Develop a separate tool specifically for Google Maps integration, requiring its own Google Maps API key.
- Offer this tool alongside the existing Google Search tool, allowing users to choose based on their needs.

**Comment by Yeuoly** [comment]
You are right, GoogleSearch and GoogleMap are considered as two providers, but more than that, it's by design, maybe make them in the same group is a better solution.

**Comment by Yeuoly** [comment]
Managing multiple keys in the same provider is already in our plan, you can wait for it.

**Comment by Yash-1511** [comment]
@dosu-bot it is still relevant.
