### ISSUE TITLE
About LaTeX expression rendering issue

### ISSUE THREAD

**Issue by richards199999** [langgenius/dify#2646]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When the model want to type out an expression in LaTeX, the frontend will fail to do it, making the response unreadable.😢

![image](https://github.com/langgenius/dify/assets/142148415/450ae1ba-1a72-408e-9c10-1a85fbb6936e)

### 2. Describe the feature you'd like to see

Responses will render the equations correctly.

### 3. How will this feature improve your workflow or experience?

It can improve the experience when dealing math and science with LLMs via dify.

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by wststone** [comment]
Try telling llms about adding dollar sign before and after math expressions, or use markdown style output

**Comment by richards199999** [comment]
oh wait. it works. thank you!
