### ISSUE TITLE
About Authorization method in tool creating

### ISSUE THREAD

**Issue by richards199999** [langgenius/dify#2647]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I was trying to recreate tools in dify that I did in Custom GPTs. Everything is fine until I started to transfer the one that need authorization. I just can make things work right. I change several way, but all I get is 401 or 403 error; while the ones on GPTs just work as it should.

![A tool for executing code](https://github.com/langgenius/dify/assets/142148415/b098ff12-7e67-41d8-8da0-d94fc1192220)
![A tool for executing code](https://github.com/langgenius/dify/assets/142148415/f0e56e2d-bc6b-459b-b7e5-105081584251)

![Same tool in GPTs](https://github.com/langgenius/dify/assets/142148415/b55e6b67-4a3c-4ec9-916d-41ba7e0dbe27)
![Same tool in GPTs](https://github.com/langgenius/dify/assets/142148415/a5615b0c-256c-4961-af54-ed3d4b077887)

### 2. Describe the feature you'd like to see

Refine the experience of creating a tool.

### 3. How will this feature improve your workflow or experience?

Just greatly improve my experience.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
Thanks, this issue save been fixed #2668
