### ISSUE TITLE
Automated application orchestration is not working

### ISSUE THREAD

**Issue by crazywoola** [langgenius/dify#2648]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Cloud

### Steps to reproduce

<img width="1207" alt="image" src="https://github.com/langgenius/dify/assets/100913391/af6d6427-69d1-4d90-82d6-5cc41f70bbd2">

- Input some words
- Click the generate button

### ✔️ Expected Behavior

It should generate something.

### ❌ Actual Behavior

It generates nothing.

**Comment by takatost** [comment]
Try switching to a different default model, some models may not be compatible with this prompt.
