### ISSUE TITLE
Integration of Unstructured.io Pipeline for Automated Complex Data Preprocessing

### ISSUE THREAD

**Issue by Barrow-Boy** [langgenius/dify#2656]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, I am currently facing challenges with complex data preprocessing tasks, particularly when dealing with complex documents in PDF format and large Excel files in CSV format. The current capabilities of Dify, even with adjustments in high quality and custom chunking, as well as hybrid search, do not yield satisfactory results for complex tables.

### 2. Describe the feature you'd like to see

I propose the integration of an Unstructured.io pipeline for automated complex data preprocessing. Specifically, I would like to see a built-in toggle in the knowledge base creation process that enables preprocessing of the data via Unstructured.io before embedding. This would ensure better data quality for embedding.

### 3. How will this feature improve your workflow or experience?

This feature would drastically increase my workflow efficiency and broaden my use cases. It would enable me to feed in complex documents and tables and obtain better results, making Dify a more viable tool for production-grade knowledge solutions. Without this feature, I might have to consider other tools like LlamaIndex, which already have this functionality built-in.

### 4. Additional context or comments

Unstructured.io offers a local model and an API for preprocessing tasks, which could be leveraged to enhance Dify's capabilities. Here is the link to Unstructured.io for reference: [Unstructured.io](https://unstructured.io/product) While I may not be able to contribute code, I am open to providing feedback and participating in testing from an end-user perspective. I also suggest reaching out to Unstructured.io, as they might be willing to assist with this feature's development.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by FarVision2** [comment]
An Embedding API widget would work as well. Unstructured does not seem to have an OpenAI-API ability.
They have a page-gated free API, a SAAS paid API, and a locally hosted API.

https://github.com/Unstructured-IO/unstructured-api

I have a number of image heavy PDFs that I would love to pass through into a knowledge base.  

Langflow has a component for it but I don't know enough about Python to turn it into a yaml widget

https://js.langchain.com/docs/ecosystem/integrations/unstructured

**Comment by jay-jjwu** [comment]
this is a great advice, i agree and look forwad this feature to be grounded upcomming soom.
