### ISSUE TITLE
Issue with Incorrect Invitation Link: Uses Localhost Instead of Configured URL Prefix

### ISSUE THREAD

**Issue by mwnu** [langgenius/dify#2657]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Despite entering URL prefixes such as CONSOLE_WEB_URL in the settings, the invitation link received by the invitee's email when inviting others from the web interface still appears as "http://127.0.0.1:3000/activate?token=xxx".

### ✔️ Expected Behavior

CONSOLE_WEB_URL+/activate?token=xxx，like：http://cloud.dify.ai/activate?token=xxx

### ❌ Actual Behavior
![image](https://github.com/langgenius/dify/assets/45463732/d9c2924b-e3eb-4cfd-aac8-2961f3fb3461)

http://127.0.0.1:3000/activate?token=xxx

**Comment by crazywoola** [comment]
Where did you set this environment variable？
Because the service that sends the email needs to use `worker`.
So you should set this under `api` and `worker` in you env configuration . (docker-compose or .env file)

**Comment by mwnu** [comment]
> Where did you set this environment variable？ Because the service that sends the email needs to use `worker`. So you should set this under `api` and `worker` in you env configuration . (docker-compose or .env file)

I modified the docker-compose according to the template found at https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml. The template's worker service did not indicate the need for CONSOLE_API_URL. After adding it, the invitation link correctly displayed the domain prefix.

**Comment by gijigae** [comment]
For those who come to this issue because of the incorrect invitation link, you need to add `CONSOLE_WEB_URL` to the `worker` in the docker-compose.yaml. See the `mail_invite_member_task.py` file for the reference.

https://github.com/langgenius/dify/blob/a8e694c235758ddbc82fa426d5ed7cab4e160aa4/api/tasks/mail_invite_member_task.py#L32
