### ISSUE TITLE
Request for Enhanced Rerank Model Options Due to Inaccessibility of cohere.com

### ISSUE THREAD

**Issue by mwnu** [langgenius/dify#2658]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Cohere.com has high network requirements. I've tried multiple network environments and can't register or log in (Failed to fetch). 

### 2. Describe the feature you'd like to see

Requesting enhanced options for other Rerank models, such as local models.

### 3. How will this feature improve your workflow or experience?

Reduce reliance on third-party services

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by BluerAngala** [comment]
Xinference  需要GPU运行环境，且安装需要配置较高，如果只是需要部署 bge-reranker 是否过于浪费资源？
