### ISSUE TITLE
Cannot setup the Bing Web Search 

### ISSUE THREAD

**Issue by gijigae** [langgenius/dify#2665]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Go to Tools and select "Bing Web Search". Then, add a Bing subscription key.

### ✔️ Expected Behavior

Bing Web Search should be authorized with the given subscription key.

### ❌ Actual Behavior

Upon entering the subscription key, Dify returns the following error message. It might be something to do with recently added responseFilter in #2519 .

![image](https://github.com/langgenius/dify/assets/81459/03c9ee0f-6015-4cb7-aa6b-3bcb3943240c)

Confirmed the subscription key is working from Azure Portal as shown below.

![image](https://github.com/langgenius/dify/assets/81459/547ef918-a0ba-4640-9872-92ab11deee27)

**Comment by Yeuoly** [comment]
Thanks, everything is fine now. #2669

**Comment by gijigae** [comment]
Thanks @Yeuoly for the quick update! Confirmed it's working now.

![image](https://github.com/langgenius/dify/assets/81459/d4ec4291-27b0-4282-a2b0-384c19ecf0b4)
