### ISSUE TITLE
Add OpenRouter as a model provider

### ISSUE THREAD

**Issue by richards199999** [langgenius/dify#2679]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

[OpenRouter](https://openrouter.ai/) support [a large amount of models](https://openrouter.ai/docs#models), including many open source and several close source models. Even though we already have together.ai as a model provider, there still has a lot more models on OpenRouter.

![OpenRouter](https://github.com/langgenius/dify/assets/142148415/a335eebb-cca1-4956-b35f-bb4d41c20d4b)

### 2. Describe the feature you'd like to see

I hope dify.ai Team can consider adding OpenRouter as a new model provider.

### 3. How will this feature improve your workflow or experience?

It can let users have more options and more models to use.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Korayem** [comment]
@richards199999 wooot!
