### ISSUE TITLE
Embedding Error

### ISSUE THREAD

**Issue by amazingye** [langgenius/dify#268]
Dify version: Self Host | 0.3.1

This issue happens when using Self Host version. Every thins runs fine in cloud version.
I'm using a proxy api of openai, so I added `OPENAI_API_BASE` to the environment, could it be relevant to this issue?

## The current behavior
<img width="946" alt="scrrenshot_2023-05-31 13 19 37" src="https://github.com/langgenius/dify/assets/25100137/00400ac0-4e9f-427c-866d-7e82151da4ae">

<img width="757" alt="screenshot_2023-05-31 13 22 56" src="https://github.com/langgenius/dify/assets/25100137/bb480302-8f3a-4181-a1eb-5ec12967390e">

## The data source file I used
[](https://drive.google.com/file/d/1um0-ECKvnKUsvIyKnuNwZtg_bb8FLWFI/view?usp=sharing)

##Log
docker-worker-1    | [2023-05-29 11:34:24,708: INFO/MainProcess] celery@11784d463b96 ready.
docker-worker-1    | [2023-05-29 11:34:24,712: INFO/MainProcess] pidbox: Connected to redis://:**@redis:6379/1.
docker-worker-1    | /usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
docker-worker-1    | absolutely not recommended!
docker-worker-1    | 
docker-worker-1    | Please specify a different user using the --uid option.
docker-worker-1    | 
docker-worker-1    | User information: uid=0 euid=0 gid=0 egid=0
docker-worker-1    | 
docker-worker-1    |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
docker-worker-1    | [2023-05-31 05:09:07,995: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/kombu/utils/compat.py:82: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
docker-worker-1    |   for ep in importlib_metadata.entry_points().get(namespace, [])
docker-worker-1    | 
docker-worker-1    | [2023-05-31 05:09:08,036: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/utils/imports.py:145: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
docker-worker-1    |   for ep in entry_points().get(namespace, []):
docker-worker-1    | 
docker-worker-1    |  
docker-worker-1    |  -------------- celery@11784d463b96 v5.2.7 (dawn-chorus)
docker-worker-1    | --- ***** ----- 
docker-worker-1    | -- ******* ---- Linux-5.15.49-linuxkit-x86_64-with-glibc2.31 2023-05-31 05:09:08
docker-worker-1    | - *** --- * --- 
docker-worker-1    | - ** ---------- [config]
docker-worker-1    | - ** ---------- .> app:         app:0x4026e40790
docker-worker-1    | - ** ---------- .> transport:   redis://:**@redis:6379/1
docker-worker-1    | - ** ---------- .> results:     postgresql://postgres:**@db:5432/dify
docker-worker-1    | - *** --- * --- .> concurrency: 1 (gevent)
docker-worker-1    | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
docker-worker-1    | --- ***** ----- 
docker-worker-1    |  -------------- [queues]
docker-worker-1    |                 .> celery           exchange=celery(direct) key=celery
docker-worker-1    |                 
docker-worker-1    | 
docker-worker-1    | [tasks]
docker-worker-1    |   . tasks.add_document_to_index_task.add_document_to_index_task
docker-worker-1    |   . tasks.add_segment_to_index_task.add_segment_to_index_task
docker-worker-1    |   . tasks.clean_dataset_task.clean_dataset_task
docker-worker-1    |   . tasks.clean_document_task.clean_document_task
docker-worker-1    |   . tasks.deal_dataset_vector_index_task.deal_dataset_vector_index_task
docker-worker-1    |   . tasks.document_indexing_task.document_indexing_task
docker-worker-1    |   . tasks.generate_conversation_summary_task.generate_conversation_summary_task
docker-worker-1    |   . tasks.remove_document_from_index_task.remove_document_from_index_task
docker-worker-1    |   . tasks.remove_segment_from_index_task.remove_segment_from_index_task
docker-worker-1    | 
docker-worker-1    | [2023-05-31 05:09:08,162: INFO/MainProcess] Connected to redis://:**@redis:6379/1
docker-worker-1    | [2023-05-31 05:09:08,169: INFO/MainProcess] mingle: searching for neighbors
docker-worker-1    | [2023-05-31 05:09:09,217: INFO/MainProcess] mingle: all alone
docker-worker-1    | [2023-05-31 05:09:09,254: INFO/MainProcess] celery@11784d463b96 ready.
docker-worker-1    | [2023-05-31 05:09:09,264: INFO/MainProcess] pidbox: Connected to redis://:**@redis:6379/1.
docker-worker-1    | [2023-05-31 05:11:44,052: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[54a42dde-391d-4bb0-9b2f-54ef7d1f1530] received
docker-worker-1    | [2023-05-31 05:11:44,055: INFO/MainProcess] Start process document: 22d32099-399b-4f47-9f33-ef546e7776d6
docker-worker-1    | [2023-05-31 05:12:50,176: ERROR/MainProcess] consume document failed
docker-worker-1    | Traceback (most recent call last):
docker-worker-1    |   File "/app/api/tasks/document_indexing_task.py", line 41, in document_indexing_task
docker-worker-1    |     indexing_runner.run(document)
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 68, in run
docker-worker-1    |     self._build_index(
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 402, in _build_index
docker-worker-1    |     vector_index.add_nodes(chunk_nodes)
docker-worker-1    |   File "/app/api/core/index/vector_index.py", line 52, in add_nodes
docker-worker-1    |     embedding_results = index._get_node_embedding_results(
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 96, in _get_node_embedding_results
docker-worker-1    |     ) = self._service_context.embed_model.get_queued_text_embeddings()
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/llama_index/embeddings/base.py", line 155, in get_queued_text_embeddings
docker-worker-1    |     embeddings = self._get_text_embeddings(cur_batch_texts)
docker-worker-1    |   File "/app/api/core/embedding/openai_embedding.py", line 190, in _get_text_embeddings
docker-worker-1    |     embeddings = get_embeddings(texts, engine=engine, api_key=self.openai_api_key,
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
docker-worker-1    |     return self(f, *args, **kw)
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
docker-worker-1    |     do = self.iter(retry_state=retry_state)
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
docker-worker-1    |     raise retry_exc.reraise()
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
docker-worker-1    |     raise self.last_attempt.result()
docker-worker-1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
docker-worker-1    |     return self.__get_result()
docker-worker-1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
docker-worker-1    |     raise self._exception
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
docker-worker-1    |     result = fn(*args, **kwargs)
docker-worker-1    |   File "/app/api/core/embedding/openai_embedding.py", line 73, in get_embeddings
docker-worker-1    |     data = openai.Embedding.create(input=list_of_text, engine=engine, api_key=api_key, **kwargs).data
docker-worker-1    |   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 38, in create
docker-worker-1    |     for data in response.data:
docker-worker-1    | TypeError: 'NoneType' object is not iterable
docker-worker-1    | [2023-05-31 05:12:50,239: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[54a42dde-391d-4bb0-9b2f-54ef7d1f1530] succeeded in 66.184940114s: None

**Comment by takatost** [comment]
This looks like the response data returned by the proxy embedding API you're using isn't what you expected. I'd suggest connecting directly to OpenAI or trying use a different mirror.

**Comment by amazingye** [comment]
tried another mirror, still happens

**Comment by amazingye** [comment]
Maybe some mirror apis don't support embedding api, tried several api sites, finally found one that's usable

**Comment by JiangYain** [comment]
> 也许有些镜像 API 不支持嵌入 api，尝试了几个 api 站点，终于找到了一个可用的

您好，我遇到了和您一样的问题，可以请教一下您的可用站点是哪一个吗？感激不尽
