### ISSUE TITLE
Claude request error in configuration page chat

### ISSUE THREAD

**Issue by wststone** [langgenius/dify#2686]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![5C395021-AF5E-4F05-9EE5-CB497BA1B1BD](https://github.com/langgenius/dify/assets/42225395/c6bd4011-5af2-4d54-aa57-3054fe619c66)

### ✔️ Expected Behavior

Request to not error

### ❌ Actual Behavior

Request failed error as shown in the screenshot

**Comment by crazywoola** [comment]
You can restart conversation if you got this error.
