### ISSUE TITLE
 How to modify the API’s timeout duration

### ISSUE THREAD

**Issue by wurenxiaozu** [langgenius/dify#2688]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

When I call the API interface to access the configured Dify application, if the execution time exceeds 30 seconds, the API interface returns a 504 Gateway Time-out error, which is likely caused by a connection timeout leading to an interruption. How can I adjust the service configuration to extend the timeout to 360 seconds?

**Comment by wurenxiaozu** [comment]
The information you provided doesn’t seem to match the issue you’re experiencing, as you’re already using a 300-second timeout in your configuration, but the error occurs after 30 seconds. 
nginx info：
[root@iv-ycouwk8hs0qc6ilb0t58 nginx]# cat proxy.conf
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_buffering off;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;

**Comment by crazywoola** [comment]
Do you mean when you are calling the api.xxx.com and it turns out to be 504?

**Comment by wurenxiaozu** [comment]
Call http://XXXX.com/v1/completion-messages  meet 504 
![image](https://github.com/langgenius/dify/assets/146314582/e2350e2a-2702-42ad-a69f-d0064b08f953)

**Comment by crazywoola** [comment]
```
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_buffering off;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
```

As you mentioned here. We have already set the proxy read and send to 3600s. Can you check the nginx logs as well?

**Comment by wurenxiaozu** [comment]
![image](https://github.com/langgenius/dify/assets/146314582/ffef97c9-8709-46f6-be1c-f4ee9af6f70c)
No information was printed.

**Comment by crazywoola** [comment]
It seems this request can not reach to the nginx correct, so does the api server. I think there might be something wrong in your configuration.

**Comment by wurenxiaozu** [comment]
The issue has been resolved, and it was due to a timeout setting in the firewall, not related to the "dify" issue. The problem was solved after modifying the firewall configuration. Thank you for your support.

**Comment by allanpk716** [comment]
in case you have same issues, it work with me
![image](https://github.com/user-attachments/assets/9f1ba15b-a111-4ed5-8335-415ea3d2222e)
