### ISSUE TITLE
How to use k8s to deploy version 0.5.8

### ISSUE THREAD

**Issue by YYyp99** [langgenius/dify#2692]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I used the official provided help chart to deploy dify using k8s, version 0.4.9. How can I upgrade it to 0.5.8? Is there any need to modify or change the previous help chart

**Comment by YYyp99** [comment]
> 0.4.9

What changes have not been made to versions 0.5.8 and 0.4.9, and what variables have been added? Is there any problem with directly changing the version of the image?

**Comment by takatost** [comment]
Sorry, currently there is no official k8s deployment solution provided. If you want to know the differences between versions, you can check out: https://github.com/langgenius/dify/releases

**Comment by xiangpingjiang** [comment]
@takatost 
Will dify team support the k8s deployment solution in the future?

**Comment by YYyp99** [comment]
> @takatost Will dify team support the k8s deployment solution in the future?

https://github.com/BorisPolonsky/dify-helm   ,This is deploying dify through the help chart in k8s, but version 0.4.9 is not the latest version. You can change the image version to deploy it

**Comment by xiangpingjiang** [comment]
> > @takatost Will dify team support the k8s deployment solution in the future?
> 
> https://github.com/BorisPolonsky/dify-helm ,This is deploying dify through the helm chart in k8s, but version 0.4.9 is not the latest version. You can change the image version to deploy it

It's not official
