### ISSUE TITLE
Diffy - Web Error - RangeError: Incorrect locale information provided/An error occurred in the Server Components render

### ISSUE THREAD

**Issue by shibir** [langgenius/dify#2702]
<img width="719" alt="Screenshot 2024-03-05 at 8 49 11 PM" src="https://github.com/langgenius/dify/assets/4231945/3a12ef1d-f4f6-4fcb-a0e5-2911b4b318c5">
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Hey Team,

We are seeing below error message:

 **[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.]**
 
 **RangeError: Incorrect locale information provided**
 
 NOTE - we are running on ECS - Faragte  - AWS

**Comment by shibir** [comment]
We are using DockerImage - **"langgenius/dify-web:latest"**

**Comment by crazywoola** [comment]
Please use the bug template to fire a bug related issue. Please include the logs as well, either from the console or from the docker image. And it's Dify.

**Comment by AmberDengyy** [comment]
https://github.com/langgenius/dify/pull/3726#issuecomment-2812172493
