### ISSUE TITLE
Auto prompt not updating before hard refresh

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2704]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

[Loom video of bug](https://www.loom.com/share/14990e54a1bb4550ba1800bfd38179df)

When using the Automated application orchestration the prompt is not populated in the prompt field before a hard refresh.

### ✔️ Expected Behavior

Population of the prompt field without refreshing the site.

### ❌ Actual Behavior

Have to hard refresh the site before the prompt shows up.

**Comment by iamjoel** [comment]
I found the cause of the problem. When prompt changes, the value of prompt editor does not change accordingly. I'll fix it later.
