### ISSUE TITLE
采用 Q&A 分段模式出错

### ISSUE THREAD

**Issue by cq134cq** [langgenius/dify#2706]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

'NoneType' object has no attribute 'current_tenant'

### ✔️ Expected Behavior

'NoneType' object has no attribute 'current_tenant'

### ❌ Actual Behavior

'NoneType' object has no attribute 'current_tenant'

**Comment by GarciaLiu** [comment]
I have the same problem, I am using the community version of code deployment. The embedding model and LLM are chatglm3 API. When I use the Q&A segmentation method to create the database, the above error is reported. I think there is nothing wrong with my configuration, it should be a bug.

**Comment by cq134cq** [comment]
> * 于访问当前Flask应用的配置，特别是获取`FILES_URL`配置值。
> * `current_user`：用于获取当前登录用户的ID，以查询租户的角色。

我用0.5.6就没有这样的问题配置一样。。。。

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by LeePui** [comment]
I have the same problem in 0.5.8

**Comment by liningwangyi** [comment]
I have the same problem too

**Comment by cq134cq** [comment]
> I have the same problem in 0.5.8

我在用采用 Q&A 分段模式出错
在右上角出来红色字'NoneType' object has no attribute 'current_tenant'
我用同样的配置在0.5.6里是没问题的
我两个都是用DOCKER

**Comment by sweetcard** [comment]
I have the same problem in 0.5.8

**Comment by richardeee** [comment]
I have the same problem in 0.5.9, I upgrade from 0.5.8 to 0.5.9 and the error still occur
