### ISSUE TITLE
The developed application, called by api, will appear a record of calling the large model twice

### ISSUE THREAD

**Issue by dahaixingchen** [langgenius/dify#2708]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/44915308/6474e401-eb95-4ac1-bf91-d9d1388f837a)

**Comment by takatost** [comment]
The second LLM request is for automatically generating conversation title, controlled by the `auto_generate_name` parameter of the Send Message API. 
If you do not want it to be generated automatically, you can set it to `false`. If needed, you can use the `rename API` and set `auto_generate` to `true` to asynchronously generate the title.
