### ISSUE TITLE
After using the Jina embedding model, when processing the knowledge base, it would fully occupy the CPU performance and throw a 'NoneType' error

### ISSUE THREAD

**Issue by car9797** [langgenius/dify#2711]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/131245178/722dc381-1538-4cfc-8278-ddbd440b8911)
![image](https://github.com/langgenius/dify/assets/131245178/a797f96c-7528-4dfa-9d46-5e8f526f208f)
"After using the Jina embedding model, when processing the knowledge base, it would fully occupy the CPU performance and throw a 'NoneType' error."

**Comment by crazywoola** [comment]
@car9797 Do you have enough keys to complete this index job?

**Comment by car9797** [comment]
> @car9797 Do you have enough keys to complete this index job?

yes，enought

**Comment by takatost** [comment]
Hey, could you please provide the resource configuration of the container and the test cases for us to reproduce?
