### ISSUE TITLE
dify如何成功调用stable diffusion webui工具，展示图片

### ISSUE THREAD

**Issue by xspring14** [langgenius/dify#2712]
### Self Checks

- [ ] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [ ] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

我在工具中授权好了stable diffusion webui工具，并填对了本地模型名称。在对话llm中，它能正确调用webui工具，但是卡在了 please input model，最后无法调用后台的stable diffusion webui

**Comment by crazywoola** [comment]
#1542

**Comment by AuYuHui** [comment]
![image](https://github.com/langgenius/dify/assets/38815121/4b017037-b840-452c-bac1-402880b03b51)

将SD 得结果作为回复输出

**Comment by czslxk** [comment]
> ![image](https://private-user-images.githubusercontent.com/38815121/333515998-4b017037-b840-452c-bac1-402880b03b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzM4MjEsIm5iZiI6MTcxODA3MzUyMSwicGF0aCI6Ii8zODgxNTEyMS8zMzM1MTU5OTgtNGIwMTcwMzctYjg0MC00NTJjLWJhYzEtNDAyODgwYjAzYjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyMzg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTAyYzFkY2VhZTc2NjFhMmU3NjBlOTZiYTI0YzYwYTU2NGEyZDkxOTM1NWY4MWZhNTg4NDE3MzJlOTY4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ULlTEWx-u6ks9l4sD1eVqdChmaBoOoOZJI741QxgYvA)
> 
> 将SD 得结果作为回复输出

Why I got NULL in output??
#5028

**Comment by CharlesSong** [comment]
我这边正常返回了json数据，但是没办法把它给显示出来。

**Comment by CharlesSong** [comment]
创建项目：聊天机器人+工作流编排；调用 sd后直接回复files

**Comment by shatle** [comment]
我的是最新的0.6.15，没有直接回复的节点？

**Comment by sniper456** [comment]
调用后怎么展示图片，图片目录在哪里
