### ISSUE TITLE
本地PG、redis、qdrant都装了，如何初始化数据库中的相关数据呢？

### ISSUE THREAD

**Issue by moom-en** [langgenius/dify#2717]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

本地PG、redis、qdrant都装了，如何初始化本地数据库中的相关数据呢？

**Comment by crazywoola** [comment]
#1542
