### ISSUE TITLE
Request for Feature Development: Building Knowledge Base from URLs

### ISSUE THREAD

**Issue by taheritajar** [langgenius/dify#2724]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Hi there,
Firstly, I am grateful for your excellent application. I've been utilizing your open-source codes for a segment of my research, specifically to construct a knowledge base from a list of URLs. But it still is on "coming soon" status.

### 2. Describe the feature you'd like to see

To optimize the process of building the knowledge base automatically from URLs, I would like to request that you develop a feature within your application that facilitates this functionality.

### 3. How will this feature improve your workflow or experience?

Using this feature, everyone can import their data from exciting websites simply and efficiently, which can help them get better results and enhance user satisfaction.

### 4. Additional context or comments

Thank you for considering my suggestion.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We provide API for adding things into our vdb. You need to make some spider to do the real work.

For some reasons, urls always have anti-spider things which will not allow such kind tools to get correct things from the source, in this case, the accuracy should be very low I think.
