### ISSUE TITLE
Cannot add keywords.

### ISSUE THREAD

**Issue by paulchen180616** [langgenius/dify#2727]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Unable to properly add keywords in the dataset segment; they disappear automatically after being added.

### ✔️ Expected Behavior

success add

### ❌ Actual Behavior

add failed

**Comment by JohnJyong** [comment]
![image](https://github.com/langgenius/dify/assets/76649700/cea18515-8e3d-41a7-bee0-f844cb527d73)
![image](https://github.com/langgenius/dify/assets/76649700/8be2b65c-f26b-4b64-829d-2d9a4b47889e)
![image](https://github.com/langgenius/dify/assets/76649700/7ce22d1f-9a76-4d8c-ae76-0f066ef38a62)

Unfortunately, I can't reproduce it here. pls describe step by step how to trigger this issue, thanks @paulchen180616
