### ISSUE TITLE
构建前端镜像问题

### ISSUE THREAD

**Issue by zhouganglong** [langgenius/dify#2728]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

我在前端修改了部分功能，docker构建新的镜像跑起来。
报了
`2024-03-07 11:03:29 ./entrypoint.sh: set: line 3: illegal option -
: not found11:04:29 ./entrypoint.sh: line 2:`
然后我找了./entrypoint.sh文件，并没有这个文件，请问哪里获取这个文件然后才能构建新的镜像。

**Comment by crazywoola** [comment]
Close due to #1542
