### ISSUE TITLE
Support Function Calling for Anthropic Models in Dify

### ISSUE THREAD

**Issue by lroolle** [langgenius/dify#2740]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, I am currently facing compatibility issues between the Agent Assistant with ReACT and Claude models. The Agent Assistant does not work when using Claude models like claude-3-opus-20240229.

### 2. Describe the feature you'd like to see

I would like to see support for function calling for Claude models in Dify. This feature would allow the Agent Assistant to call the tools like the GPT models for Claude models. More information about this can be found in the following links:

[Claude Docs - Functions & External Tools](https://docs.anthropic.com/claude/docs/functions-external-tools)
[Anthropic Tools on GitHub](https://github.com/anthropics/anthropic-tools/)

### 3. How will this feature improve your workflow or experience?

 It will allow the Agent Assistant to utilize the capabilities of Claude models, enhancing its functionality.

### 4. Additional context or comments

None.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
Function calling of Anthropic is in alpha test and not ready to productive using.
