### ISSUE TITLE
No response for applications using tongyi tts

### ISSUE THREAD

**Issue by zhanaali** [langgenius/dify#2743]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

"Upon using Tongyi's TTS to convert text to speech, the application became unresponsive with no abnormalities in the logs. Subsequent requests also elicited no response. System: Windows 11 Python: 3.10"

**Comment by zhanaali** [comment]
I looked at the code, and it seems to have stopped at this line: "response = dashscope.audio.tts.SpeechSynthesizer.call(model=voice, sample_rate=48000, text=sentence.strip(), format=audio_type)".

**Comment by charli117** [comment]
> I looked at the code, and it seems to have stopped at this line: "response = dashscope.audio.tts.SpeechSynthesizer.call(model=voice, sample_rate=48000, text=sentence.strip(), format=audio_type)".

You have come to the tongyi tts SDK, if no response maybe network inaccessible, please make sure the connectedness of https://dashscope.aliyuncs.com

**Comment by charli117** [comment]
Also make sure the API dependencies are installed，No exception is found in the multi-environment verification

**Comment by zhanaali** [comment]
Copying the code and running it independently works fine, but I can't get a response inside dify. It's very strange.

**Comment by zhanaali** [comment]
There should be no issues with the SDK and the network
