### ISSUE TITLE
Llava chat with ollama not working

### ISSUE THREAD

**Issue by wrapss** [langgenius/dify#2746]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

9.5.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have literally reproduced your tutorial: 
https://docs.dify.ai/tutorials/model-configuration/ollama

my chat mode setting : 
![image](https://github.com/langgenius/dify/assets/7548882/636b8e0f-e09f-4df0-8908-d51edaa43556)

my completion mode setting: 
![image](https://github.com/langgenius/dify/assets/7548882/d7ae99e6-b6a2-45b4-89e7-f4216bda6023)

### ✔️ Expected Behavior

when i use completion mode : 
![image](https://github.com/langgenius/dify/assets/7548882/cb7f9d2b-ba1a-4cfd-8430-ea6914aa2952)

### ❌ Actual Behavior

When i use chat mode : 
![image](https://github.com/langgenius/dify/assets/7548882/0bd5fd74-3d77-427a-90c3-163ee6a273d5)

I tried increasing the size of the model context and changing other parameters but it didn't change anything

**Comment by wrapss** [comment]
Problem still present with llava:34b-v1.6 despite the use of an even larger context size

**Comment by takatost** [comment]
Maybe try reducing the `Num Predict` model parameters a bit?

**Comment by giovannicocco** [comment]
Hello everyone, I have a problem in my environment, as you can see in the screenshot, the information is not loading on the screen. I'm using a Mac, but I deployed with Docker, cloned the repo, accessed the /docker folder and ran the docker compose up -d command

Regarding Ollama, I installed it, it is running and I was able to add it to Dify without any problems using my network IP and the Ollama port.

Any suggestions?

![Captura de Tela 2024-03-16 às 10 17 20](https://github.com/langgenius/dify/assets/6585496/72135eb8-239f-4ffd-b744-cdd7d0eaf146)
![Captura de Tela 2024-03-16 às 10 17 42](https://github.com/langgenius/dify/assets/6585496/3812002f-fdc4-49d5-afed-f2252941e074)
![Captura de Tela 2024-03-16 às 10 19 08](https://github.
![Ollama Added Successful](https://github.com/langgenius/dify/assets/6585496/19872498-817b-43eb-8168-28ea41a4f1a4)
com/langgenius/dify/assets/6585496/cbf1c000-3d49-4664-b546-f9248b8dbe4b)
![Captura de Tela 2024-03-16 às 10 19 47](https://github.com/langgenius/dify/assets/6585496/b4280458-ab69-4a9c-991d-59a54be5cc07)

**Comment by wwjCMP** [comment]
yes, I encounter same issue
