### ISSUE TITLE
When selecting a model to set OpenAI Key, a connection error is prompted.

### ISSUE THREAD

**Issue by moom-en** [langgenius/dify#2755]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

![image](https://github.com/langgenius/dify/assets/35919845/29c37a49-2071-46b9-85bb-3354389844cd)
After the deployment is successful, log in to set up the model and fill in the OpenAI Key. After saving, it prompts a connection error, as shown in the picture above, and I can access OpenAI related websites locally.

**Comment by crazywoola** [comment]
Are you trying to fill `127.0.0.1:7890`? If you are using docker, this address should point to the localhost of the container itself. You can use the ip address of the computer instead.
