### ISSUE TITLE
the use of the fuction of create_blob_message

### ISSUE THREAD

**Issue by StawEndl** [langgenius/dify#2757]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

hi, i have some trobles of using this fuction.
when i want to show some videos, i have no idea what should be writen on the blob and meta.
or i want to show a audio, what should i fill?
could you give me some samples?
i just found there are just some sample of how to show picture(image).

**Comment by crazywoola** [comment]
Image and videos are the same. they are using <img /> or <video />. 
But when you are ask the LLM to reply with markdown, then it will use markdown syntax. 
So, you can just ask the llm to reply with 👆 2 methods to wrap the source link.
You can google it for more details.
