### ISSUE TITLE
Change/modify the input before sending it to OPENAI as prompt

### ISSUE THREAD

**Issue by CodinjaoftheWorld** [langgenius/dify#2762]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I have referred the documentation but not able to find the required functions.  
Need help for the documentation/reference for modifying/preprocessing the input before sending it to the LLM(OpenAI) as prompt.

**Comment by PandaAnshuman** [comment]
When interacting with the Language Model (LLM), you may find it beneficial to modify or preprocess your input data to enhance the quality of responses or adapt it to specific use cases. This documentation provides guidance on how to modify and preprocess input before sending it to the LLM. Examples and code snippets are included to illustrate the process.

Modifying/Preprocessing Techniques:
1:  Cleaning Text: Remove unnecessary characters, symbols, or special characters from the input to ensure that the LLM focuses on meaningful content.
2: Lowercasing: Convert all text to lowercase to maintain consistency and avoid the model treating the same word differently based on its case.

**Example for Cleaning Text (Solution #1):**

```python
import re

def clean_text(input_text):
    # Remove special characters, symbols, and non-alphanumeric characters
    cleaned_text = re.sub(r'[^A-Za-z0-9 ]+', '', input_text)
    return cleaned_text

# Example usage
input_text = "Remove !@#$ special characters from this text."
cleaned_text = clean_text(input_text)

print(f"Original Text: {input_text}")
print(f"Cleaned Text: {cleaned_text}")
```

This example defines a `clean_text` function that uses a regular expression to remove any characters that are not letters or numbers. The function is then applied to an example input text, and the original and cleaned texts are printed.

**Example for Lowercasing (Solution #2):**

```python
def lowercase_text(input_text):
    # Convert all text to lowercase
    lowercased_text = input_text.lower()
    return lowercased_text

# Example usage
input_text = "Convert This Text To Lowercase."
lowercased_text = lowercase_text(input_text)

print(f"Original Text: {input_text}")
print(f"Lowercased Text: {lowercased_text}")
```

This example defines a `lowercase_text` function that converts all characters in the input text to lowercase. The function is then applied to an example input text, and the original and lowercased texts are printed.
