### ISSUE TITLE
OpenAI compatible API JSON format error

### ISSUE THREAD

**Issue by KnaveM** [langgenius/dify#2769]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. add groq api `https://api.groq.com/openai/v1`
<img width="650" alt="image" src="https://github.com/langgenius/dify/assets/33738071/3d22b71f-1c92-4689-9e70-c3a1b4076b4c">
2. send message to model

### ✔️ Expected Behavior

Should work without problem.

### ❌ Actual Behavior

<img width="1022" alt="image" src="https://github.com/langgenius/dify/assets/33738071/d947d5d6-7a43-442f-8d0b-a4677ecdd9c4">
****

**Comment by KnaveM** [comment]
Toggle off those options and the api work fine

Could you help make these options off as default?

<img width="588" alt="image" src="https://github.com/langgenius/dify/assets/33738071/7888c1ab-c9b7-4118-8203-0fdc68ab0737">

**Comment by crazywoola** [comment]
@KnaveM We will tweak this later. Thanks for the heads up.
