### ISSUE TITLE
建了对话型应用后，没用几次就一直报the query is too long?

### ISSUE THREAD

**Issue by melisa81** [langgenius/dify#277]
建了对话型应用后，没用几次就一直报the query is too long?
怎么解决呀……

**Comment by takatost** [comment]
You can set the max tokens a bit lower if it's appropriate

**Comment by chllei** [comment]
能否考虑参考 ChatGPT-Next-Web 的做法，随着对话的进行，自动对上下文进行压缩？

**Comment by takatost** [comment]
Currently, the chat records are auto reduced based on the available tokens. Your question might be too long and the max token setting is too large,

**Comment by melisa81** [comment]
It works,3q!

> Currently, the chat records are auto reduced based on the available tokens. Your question might be too long and the max token setting is too large,

**Comment by melisa81** [comment]
from discord:
max tokens 是设置回答的 token 数，如果设置的很大，假设是 gpt-3.5-turbo 限制是 4097 token，max_tokens 设置 4000，那么问题中能输入的内容只有 97 tokens
[11:22]
这还没有算上 pre prompt 的内容和数据集的内容
