### ISSUE TITLE
Cannot open my apps: 3 validation errors for AgentToolEntity provider_type field required 

### ISSUE THREAD

**Issue by aipilotchina** [langgenius/dify#2776]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

When I click into the app in studio and want to change the settings, I get the following error:
3 validation errors for AgentToolEntity provider_type field required (type=value_error.missing) provider id field required (type=value _error.missing) tool_name field required (type=value_error.missing)
![0](https://github.com/langgenius/dify/assets/155522964/4e266032-ddf2-4142-b993-e7e2c786554b)

I have created 3 apps, but two of them have this error. They cannot be edited, and links that were working yesterday are now very slow to access.
If I use it in workspace (in Explore page), I also get the following error with no answer.
1 validation error for DatasetMultiRetrieverTool reranking_provider_name str type expected (type=type error.str)
<img width="970" alt="1" src="https://github.com/langgenius/dify/assets/155522964/ea6c60ad-5034-48f4-809a-8bc4e3f932c4">

I'm not sure if this has anything to do with the fact that I upgraded plan. I cannot edit my apps now. Hopefully I can find an answer here! Thanks!

**Comment by crazywoola** [comment]
Please make sure you have follow the instruction correctly. And provide more information as well, such as the url, port and which version, cloud or self-hosted.

**Comment by aipilotchina** [comment]
I have problems accessing this url:
https://cloud.dify.ai/app/974aa8e6-3cd0-4a32-8e7d-9c210b261f7f/configuration
Thanks!
<img width="866" alt="0" src="https://github.com/langgenius/dify/assets/155522964/974e60f3-da72-46ec-9456-f21d63bbd1ca">

**Comment by crazywoola** [comment]
What tools did you choose? Seems you have deleted it?

**Comment by Yeuoly** [comment]
fix #2782

**Comment by aipilotchina** [comment]
I used the studio in dify website. When I click into certain app that i didn't delete, however the problems I mentioned before still exist! 
<img width="895" alt="1" src="https://github.com/langgenius/dify/assets/155522964/debed26a-321a-4ca8-a359-84dc7732830e">

I have no idea with it. Thank you for your help!

**Comment by aipilotchina** [comment]
The problem is solved. Thank you!
