### ISSUE TITLE
An error occurred while deleting the dataset

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#2784]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

An error occurred while deleting the dataset：
<img width="855" alt="image" src="https://github.com/langgenius/dify/assets/1925650/dce9facb-18bf-4c51-a6ca-12a4874ca7bc">

dataset not exists doc_form field:
<img width="899" alt="截屏2024-03-11 19 12 58" src="https://github.com/langgenius/dify/assets/1925650/1de40c1c-77a6-4f8b-9f29-eae8aed9701b">

### ✔️ Expected Behavior

no error will occur

### ❌ Actual Behavior

error

**Comment by JohnJyong** [comment]
it has fix by the PR : https://github.com/langgenius/dify/pull/2789 , thanks for your feedback~ @wangrg

**Comment by wangrg** [comment]
In addition, the documents in the previous version of the data set supported different doc_form types (qa_model, text_model). Now the doc_form field value of the first document in the data set is inaccurate.

**Comment by wangrg** [comment]
The use of doc_form in the following files in the source code should be inaccurate:
api/tasks/clean_notion_document_task.py
api/tasks/add_document_to_index_task.py
api/tasks/create_segment_to_index_task.py
api/tasks/clean_dataset_task.py
api/schedule/clean_unused_datasets_task.py
api/core/indexing_runner.py -> batch_add_segments

**Comment by wangrg** [comment]
> it has fix by the PR : #2789 , thanks for your feedback~ @wangrg

The code snippet that determines whether the document list is empty is too early, otherwise the data in the DatasetProcessRule, DatasetQuery, and AppDatasetJoin tables may not be deleted.

**Comment by JohnJyong** [comment]
Thank you for your question. We have optimized the logic here: https://github.com/langgenius/dify/pull/3354
@wangrg
