### ISSUE TITLE
create langchainflow

### ISSUE THREAD

**Issue by tgbaoo** [langgenius/dify#2786]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

yes, when I go deeper about the prompt engineering, it is great if we bring langchain modules to UI and allow user config as flow by them self.

### 2. Describe the feature you'd like to see

something's like langflow or flowise opensource

### 3. How will this feature improve your workflow or experience?

yes, it is allow me to create or deep and advanced chatbot

### 4. Additional context or comments

hello, do dify team plan to create langchain flow on dify such as some open source like flowise(https://flowiseai.com/) or langflow(https://www.langflow.org/)

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This is under development right now. Please stay tuned.
