### ISSUE TITLE
本地跑项目报错

### ISSUE THREAD

**Issue by zhouganglong** [langgenius/dify#2791]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

当我在执行 flask db upgrade `将数据库结构迁移至最新版本，报了这个错误，找了很多问题都说没有dify数据库，可是docker运行docker compose -f docker-compose.middleware.yaml up -d` 之后应该会初始化，目前不知道哪里的问题
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "dify" does not exist`

**Comment by crazywoola** [comment]
Close due to #1542
