### ISSUE TITLE
gpt4 doesn't exist

### ISSUE THREAD

**Issue by catundchat** [langgenius/dify#280]
when I tried to create a web page with my gpt-4 openai api key and chose gpt-4 model, the problem occured: gpt4 doesn't exist. Does dify have connection to gpt-4?

**Comment by catundchat** [comment]
Thanks. That's mean even if I had the ChatGPT Plus subscription and could use GPT-4, I can't use gpt-4 model in Dify web page when I create an application?

**Comment by yuhao1118** [comment]
You are right. ChatGPT Plus subscription does not grant a GPT-4 API access. You will have to submit a waitlist request of GPT-4 API access on OpenAI website.
