### ISSUE TITLE
Is vectordb config mutually exclusive by design

### ISSUE THREAD

**Issue by BorisPolonsky** [langgenius/dify#2801]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

We are developers of `dify-helm` and we've received a feature request for enabling multiple vector db **simutaneously** via `.Values.yaml`. Our assumption is that only one vectordb (i.e. either `weaviate`, `qdrant` or `milvus`) would be utilized and we've designed our template like [this](https://github.com/BorisPolonsky/dify-helm/blob/master/charts/dify/templates/config.tpl#L201), where environment variables from non-selected vector db won't be added to `api` or `worker` for fool proof purpose. Please clarify if it is appropriate specifying environment variables for multiple vector db **simutaneously** by design.

**Comment by takatost** [comment]
Do you want the environment variables for vector db to be configured simultaneously? 

Currently, the design is that only one environment variable: `VECTOR_STORE` can be configured, while others like `WEAVIATE_ENDPOINT` and `QDRANT_URL` can be configured but their usage depends on `VECTOR_STORE`. This variable is used to specify which vector db is currently being used, and only one can be specified.

**Comment by BorisPolonsky** [comment]
> Do you want the environment variables for vector db to be configured simultaneously?
> 
> Currently, the design is that only one environment variable: `VECTOR_STORE` can be configured, while others like `WEAVIATE_ENDPOINT` and `QDRANT_URL` can be configured but their usage depends on `VECTOR_STORE`. This variable is used to specify which vector db is currently being used, and only one can be specified.

Can you please elaborate and clarify the user case? cc @bowenliang123

**Comment by BorisPolonsky** [comment]
> > Do you want the environment variables for vector db to be configured simultaneously?
> > Currently, the design is that only one environment variable: `VECTOR_STORE` can be configured, while others like `WEAVIATE_ENDPOINT` and `QDRANT_URL` can be configured but their usage depends on `VECTOR_STORE`. This variable is used to specify which vector db is currently being used, and only one can be specified.
> 
> Let's put it this way. We would like to know if it is considered a hack or a stable feature meant for production use to make multiple vector db (say `weaviate` and `milvus` working`) available in production environment with configuration like this
> 
> ```
> VECTOR_STORE: "milvus"
> # The Weaviate endpoint URL. Only available when VECTOR_STORE is `weaviate`.
> WEAVIATE_ENDPOINT: "some-authentic-endpoint-with-legacy-vector-data-given-previously-imported-knowledge"
> WEAVIATE_API_KEY: "api-key"
> 
> # The milvus host.
> MILVUS_HOST: "an-authentic-milvus-host-for-storing-new-vector-data"
> # The milvus host.
> MILVUS_PORT: "<port-associated-with-host-above>
> # The milvus username.
> MILVUS_USER: "<some-user-with-role-admin>"
> # The milvus password.
> MILVUS_PASSWORD: "<Milvus password>"
> # The milvus tls switch.
> MILVUS_SECURE: "<true/false>"
> ```
> 
> Could you elaborate and clarify the user case plz? @bowenliang123

@takatost Any update?

**Comment by bowenliang123** [comment]
The vdb migrate command introduced in (https://github.com/langgenius/dify/pull/2562) require keeping mulitple vector configs while migration. During the migration procedure, the index on existed vdb is still being used. If we have only one vdb config, we could never achieve this, WITH the helm chart by @BorisPolonsky .

I would suggest,
1. allow multiple configs for different vdb, eg.
- extraMilvus
- extraQudrant
...
2. set VECTOR_STORE into the last enabled vdb configs (the enabled field in extraXXXX)
3. introduce a dedicated optional config to setting VECTOR_STORE, and this overrides the final config

WDYT, cc @JohnJyong @takatost .

**Comment by BorisPolonsky** [comment]
It's been introduced since `0.5.7` as mentioned [here](https://github.com/langgenius/dify/pull/2610). We would add this feature after `0.5.*` enters archived state and overhaul core environment variable configuration design as well.
