### ISSUE TITLE
separate environment variables from docker-compose.yaml

### ISSUE THREAD

**Issue by bh1xaq** [langgenius/dify#2804]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, it is tedious to adjust the configuration every time.

### 2. Describe the feature you'd like to see

I will modify some parameters in docker-compose.yaml, but every time I upgrade, my custom parameters are overwritten.  What I expect is that upgrading components does not affect my specially configured docker-compose.yaml parameters.
My suggestion is to separate the environment variables from the docker-compose.yaml to the.env.

### 3. How will this feature improve your workflow or experience?

With this feature, if I can keep my original special configuration, I won't have to re-modify the docker-compose.yaml file every time I upgrade.

### 4. Additional context or comments

None

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This is a quite good one. We can take a look at this later.

**Comment by takatost** [comment]
Yeah, we've had this plan all along.
