### ISSUE TITLE
How to set waiting time > 60s for OpenAI compatible model?

### ISSUE THREAD

**Issue by PhenixZhang** [langgenius/dify#2806]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I use dify default config and returned result like this:
![image](https://github.com/langgenius/dify/assets/26118845/041f86e7-e25b-4b02-ab2f-2d2321a86a1e)

**Comment by takatost** [comment]
Could you please provide more details of the issue you encountered?
