### ISSUE TITLE
anyone has this problem when use  custom AI WebApp？

### ISSUE THREAD

**Issue by ImpChiang** [langgenius/dify#2812]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

[https://github.com/langgenius/webapp-conversation/issues/50](url)

**Comment by crazywoola** [comment]
Please report the bug in that repo.
