### ISSUE TITLE
LocalAI configuration embedded model is invalid

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#2814]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

The reason is that the get_customizable_model_schema function is not implemented

### ✔️ Expected Behavior

Implement the get_customizable_model_schema function

### ❌ Actual Behavior

LocalAI configuration embedded model is invalid

**Comment by wangrg** [comment]
here：
api/core/model_runtime/model_providers/localai/text_embedding/text_embedding.py

**Comment by liu3xing3long** [comment]
tried embedding models: jinaai/jina-embeddings-v2-base-zh + all-MiniLM-L6-v2, neither work, both curl-interfaces work

**Comment by Yeuoly** [comment]
fixed #2840
