### ISSUE TITLE
Dify Golang SDK not work

### ISSUE THREAD

**Issue by soulteary** [langgenius/dify#2815]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.59

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Using the SDK implementation in the warehouse, Dify cannot be called normally.

### ✔️ Expected Behavior

it work :D

**Comment by crazywoola** [comment]
I will close this one. I guess you are interested in contributing the new one. Told by @JohnJyong
