### ISSUE TITLE
i18n objects not showing for tools

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2824]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When changing the language from English to Portogues, the tools that have translations in their .yaml files are not showing the translated strings in the frontend.

For instance the Github Tool has pt_BR translated text, but it's showing english.
![CleanShot 2024-03-13 at 20 22 21@2x](https://github.com/langgenius/dify/assets/119136210/f9695bbd-cc4e-4305-94ef-cda975c0c232)
This is also true for other languages added, so there seems to be a logic that is not pulling the correct i18n objects.

### ✔️ Expected Behavior

If the tools have translations, the translated strings should show up in the frontend

### ❌ Actual Behavior

Seems to use fallback english strings for some of the labels/descriptions.

**Comment by crazywoola** [comment]
We haven't covered this part yet. Currently we are offering basic language support the the whole application. But tools' data comes from backend yaml files. I am still looking for a convenient way to do this.
