### ISSUE TITLE
一定要装docker才能部署吗

### ISSUE THREAD

**Issue by mashagua** [langgenius/dify#2826]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

我租用的服务器是容器类型的，每次拉取镜像总会报错，但是我想问这个不用docker，怎么源码启动

**Comment by crazywoola** [comment]
Close due to #1542
