### ISSUE TITLE
Completion Request Error

### ISSUE THREAD

**Issue by fabio13araujo** [langgenius/dify#2827]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Chats often fail to complete and give the error below. Tested with Gemini.

![image](https://github.com/langgenius/dify/assets/156973787/65b04595-7052-4f73-a5a2-389fab78a7b9)

### ✔️ Expected Behavior

In previous versions, the problem rarely occurred and when it did, it was usually a bottleneck of the chosen AI.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/156973787/65b04595-7052-4f73-a5a2-389fab78a7b9)

**Comment by Yeuoly** [comment]
#2617 Related
