### ISSUE TITLE
Deployment from an older version of the app fails

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#2828]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

<img width="1233" alt="截屏2024-03-14 11 20 22" src="https://github.com/langgenius/dify/assets/1925650/cdb6acf3-9e98-4c07-9615-e7714747ec97">
After upgrading v0.3.34 to v0.5.9, the old version of the application with associated data failed to click to publish.

code segment：
1.api/controllers/console/app/model_config.py 
2.api/controllers/console/app/app.py

<img width="570" alt="image" src="https://github.com/langgenius/dify/assets/1925650/aff52c30-6b06-4cb3-83f0-7b242ff35416">

### ✔️ Expected Behavior

Publish and edit apps successfully。
<img width="549" alt="截屏2024-03-14 11 32 08" src="https://github.com/langgenius/dify/assets/1925650/7f11a61f-dab0-4dc7-b36b-ed74c7774f31">

### ❌ Actual Behavior

Publishing and editing apps fails

**Comment by crazywoola** [comment]
Can you provide the detailed upgrade steps?

**Comment by Yeuoly** [comment]
fixed: #2839
