### ISSUE TITLE
i get “AccessDeniedException: You don't have access to the model with the specified model ID.” when i add aws bedrock 

### ISSUE THREAD

**Issue by yangzhu6263736** [langgenius/dify#2829]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1243" alt="image" src="https://github.com/langgenius/dify/assets/1215298/7fcabf8c-61f2-4365-883d-5ea5d4376bb4">
the same accessKey 
<img width="825" alt="image" src="https://github.com/langgenius/dify/assets/1215298/36a6dca4-6826-4420-8b4e-a7d000c78ebe">

When I added aws bedrock I got this error: "You do not have permission to access the model with the specified model ID." The same key I call with python code is ok. 
How to solve this problem?

**Comment by yangzhu6263736** [comment]
Perfect, solved, I only authorized a few models of claude before

**Comment by yangzhu6263736** [comment]
Another problem:
<img width="906" alt="image" src="https://github.com/langgenius/dify/assets/1215298/3a7592d0-760d-4848-8760-7f33c078a1af">
After adding it, I can only see a few models of claude V2, but not V3 models.
<img width="804" alt="image" src="https://github.com/langgenius/dify/assets/1215298/39dd1d01-8a07-4bc2-8ff1-fd2b191f601e">

**Comment by crazywoola** [comment]
Because we haven't got time add this new model to our provider. You can contribute to this feature if you like. :)

**Comment by soulteary** [comment]
refs to https://github.com/langgenius/dify/pull/2857, After waiting for this function to be officially launched, you can set the model you want to use for verification without applying for all models.

It should be particularly suitable for RAM accounts.
