### ISSUE TITLE
document/create_by_file 404

### ISSUE THREAD

**Issue by xiaoqingrong** [langgenius/dify#2830]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

use docker run dify,but,http://localhost/console/api/datasets/{dataset_id}/document/create_by_file，post。why 404？

**Comment by xiaoqingrong** [comment]
not mind host，it's run docker，other same use no problem，such as /console/api/datasets to create datasets，but use text to create document 404 error。

**Comment by crazywoola** [comment]
API start with `/console` is meant for the dify itself. You need to checkout the docs under knowledge tab.
