### ISSUE TITLE
Cannot Open Multiple Apps: 3 validation errors for AgentToolEntity provider_type field required (type=value_error.missing) provider_id field required (type=value_error.missing) tool_name field required (type=value_error.missing)

### ISSUE THREAD

**Issue by helena-yqs** [langgenius/dify#2834]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Click on App and then pop up the following error
3 validation errors for AgentToolEntity provider_type field required (type=value_error.missing) provider_id field required (type=value_error.missing) tool_name field required (type=value_error.missing)

### ✔️ Expected Behavior

Able to open my Apps

### ❌ Actual Behavior

Cannot open my apps and got the following error:
3 validation errors for AgentToolEntity provider_type field required (type=value_error.missing) provider_id field required (type=value_error.missing) tool_name field required (type=value_error.missing)

**Comment by Yeuoly** [comment]
fixed #2837
