### ISSUE TITLE
Dify API Issue while Retrieving and Displaying Responses (Cloud and API)

### ISSUE THREAD

**Issue by Eng-AliKazemi** [langgenius/dify#2838]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I’ve been using Dify with Google Gemini Pro API for some time, and the API calls and cloud 's “preview chat” started returning the following error, although previously everything was functioning correctly.

### ✔️ Expected Behavior

API's response as text.

### ❌ Actual Behavior

[google] Error: The `response.text` quick accessor only works for simple (single-`Part`) text responses. This response is not simple text.Use the `result.parts` accessor or the full `result.candidates[index].content.parts` lookup instead.

**Comment by fabio13araujo** [comment]
The same error is happening with Openai models.
