### ISSUE TITLE
Languages show up, even when supported set to false on activate page

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2842]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When a user gets invited they are linked to the /activate page, here the "interface language" has a complete list of the I18nText type, but should use the languages with the new "supported: false/true" so that only languages set to True show up in the list.

![CleanShot 2024-03-14 at 13 15 39@2x](https://github.com/langgenius/dify/assets/119136210/7aa9f1ba-d174-4f45-be72-96f43e946820)

### ✔️ Expected Behavior

The dropdown should show only the languages set to supported: true in the i18n languages.ts

### ❌ Actual Behavior

All languages show up.

**Comment by AndyMik90** [comment]
Thank you, this seems to work:

```typescript
              {/* language */}
              <div className='mb-5'>
                <label htmlFor="language" className="my-2 flex items-center justify-between text-sm font-medium text-gray-900">
                  {t('login.interfaceLanguage')}
                </label>
                <div className="relative mt-1 rounded-md shadow-sm">
                  <select
                    id="language"
                    value={language}
                    onChange={(e) => {
                      const selectedLanguage = e.target.value
                      setLanguage(selectedLanguage)
                      setLocaleOnClient(selectedLanguage, false)
                    }}
                    className="block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                  >
                    {LanguagesSupported.map((lang) => {
                      const langName = languages.find(languageItem => languageItem.value === lang)?.name
                      return (
                        <option key={lang} value={lang}>
                          {langName}
                        </option>
                      )
                    })}
                  </select>
                </div>
              </div>
``` 

The only thing now is that when the showSuccess is run, the language uses the fallback language and not the interface/set language.

**Comment by crazywoola** [comment]
It's a little bit tricky to set the interface language accordingly.  If you choose a different, it will do a hard refresh on the web browser, the previous input could lose.
