### ISSUE TITLE
Support custom reranker

### ISSUE THREAD

**Issue by soulteary** [langgenius/dify#2847]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

RAG is a scenario that often needs to be dealt with, and the reranker model currently only supports two solutions.

![image](https://github.com/langgenius/dify/assets/1500781/b9fa617a-bd4f-43eb-a0e8-8ce167a53c36)

### 2. Describe the feature you'd like to see

Is it possible to support setting local reranker model calls?

### 3. How will this feature improve your workflow or experience?

Existing pipelines can be painlessly migrated to Dify.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
You can use xinference to integrate with the rerank model deployed locally
