### ISSUE TITLE
Hope to add proxy options for most LLMs vendors

### ISSUE THREAD

**Issue by mwnu** [langgenius/dify#2849]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I use [oneapi](https://github.com/songquanpeng/one-api) to proxy the models of all vendors, providing a unified key and API URL, convenient for multiple users in different environments. 
Currently, dify only supports OpenAI using API Base. 
Anthropic also has an API URL, but if you use oneapi's proxy, it will prompt: Error code: `404 - {'error': {'message': 'Invalid URL (POST /v1/messages)', 'type': 'invalid_request_error', 'param': '', 'code': ''}}`.
other models do not support proxy base url.

### 2. Describe the feature you'd like to see

I can use oneapi to proxy Anthropic in other projects, but it can't be used in dify.
Hope to add proxy options for other LLMs vendors.

### 3. How will this feature improve your workflow or experience?

It makes it convenient for me to use a proxy in different network environments and to manage API accounts from different model vendors in a unified way.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by debugger24** [comment]
Having same issue with other models, can look into how to get it working for other models.

BTW, any specific reason for not having that option by default for all models @guchenhe @crazywoola ?

**Comment by debugger24** [comment]
Got it, not every package supports it. But yea, can raise PR for some of them which does support it. Will try having looking at the code and add.
