### ISSUE TITLE
MAC Ollama add model provider not working 

### ISSUE THREAD

**Issue by LLMR-boringtao** [langgenius/dify#2850]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

<img width="1284" alt="Screenshot 2024-03-15 at 09 06 22" src="https://github.com/langgenius/dify/assets/138439682/1ffdaeeb-bd99-42fd-b36a-64b9beab7c3b">

I checked the documentation and the issues and there are plenty of hints. Please have a look at the picture. I followed all the suggestions, but it still telling me the connection is incorrect, anyone can help? Thanks!

The error message:

An error occurred during credentials validation: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff98b81ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by LLMR-boringtao** [comment]
It is llama2-chinese by implementing Ollama. on the picture, you can see it is already running successfully. The issue is about the base_url, according to the documentation, I need to set the Ollama_host to 0.0.0.0:11434 to make it work, I did that as well, but it still not working.

**Comment by crazywoola** [comment]
Please follow the doc to set the environment variables correctlly.
