### ISSUE TITLE
step by step how to set up Ollama with Dify on a Mac?

### ISSUE THREAD

**Issue by LLMR-boringtao** [langgenius/dify#2854]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I already done the following steps:
1. installed Ollama successfully. running Ollama run llama2 and on localhost:11434, I can see: **Ollama is running**
2. set up OLLAMA_HOST and from echo $OLLAMA_HOST, I can see: **0.0.0.0:11434**
3. in Dify setting, I input: **llama2** as model name and **http://0.0.0.0:11434** as base url.

I got the following error:
An error occurred during credentials validation: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff98b81ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))

I disable firewall setting on Mac
I also try: 127.0.0.1 and localhost and OLLAMA_HOST, none of them works. Can anyone help? Thanks!

**Comment by LLMR-boringtao** [comment]
1. I confirmed that Ollama is successfully running;
2. I disabled all firewall and now all incoming calls are allowed;
3. I set OLLAMA_HOST to 0.0.0.0
4. I found the docker container IP is 172.19.0.1
5. I restarted Ollama and rerun Ollama run llama2
6. I input llama2 in diff backend ad model name and http://172.19.0.1:11434 as base_url

I still got the same error.

**Comment by crazywoola** [comment]
You should try to use the computer's ip address.

**Comment by crazywoola** [comment]
Because it's a basic network question. `localhost` points to docker container itself. You can think this is a separated computer. And you are trying to use this in another container. 

If you try to ping `host.docker.internal` you will get the computer's ip address as well. 

![image](https://github.com/langgenius/dify/assets/100913391/699b5c1e-a86a-4dc0-8a8a-1679d7096b9c)

**Comment by liuming-dev** [comment]
> http://host.docker.internal:11434/ works! This should be in the documentations!

fixed my problem
