### ISSUE TITLE
Bing Search always return Insufficient authorization to access requested resource

### ISSUE THREAD

**Issue by LLMR-boringtao** [langgenius/dify#2858]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

No matter what search query I tried, it always return:

unknown error: Error 403: {"_type": "ErrorResponse", "errors": [{"_type": "Error", "code": "InsufficientAuthorization", "message": "Insufficient authorization to access requested resource.", "moreDetails":"Only these values are allowed: Webpages,SpellSuggestions", "parameter": "responseFilter", "value": "Entities,WebPages" }]}

What might be the cause? Thanks!

**Comment by gijigae** [comment]
I'm using Bing Web Search too and it seems to me working fine. 

![image](https://github.com/langgenius/dify/assets/81459/cc5e16cf-9b90-40e4-9ece-071b09d6ea78)


Have you tried whether your setting returns correct search results from the Azure portal?

![image](https://github.com/langgenius/dify/assets/81459/6584bbf4-04e8-40f1-818e-639c61d35580)

**Comment by Yeuoly** [comment]
hello, this issue has fixed #2875
