### ISSUE TITLE
GITHUB_回调地址是什么

### ISSUE THREAD

**Issue by wanxiangsucai** [langgenius/dify#2859]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

GITHUB_CLIENT_ID: YOUR_GITHUB_CLIENT_ID_HERE
      GITHUB_CLIENT_SECRET: YOUR_GITHUB_CLIENT_SECRET_HERE

GITHUB_回调地址是什么
还有谷歌的回调地址是什么

**Comment by crazywoola** [comment]
Close due to #1542
