### ISSUE TITLE
API： def get_provider_api_key(self, model_id: Optional[str] = None, prefer_custom: bool = True) -> Union[str | dict]: TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by techflag** [langgenius/dify#286]
flask run --host 0.0.0.0 --port=5001 --debug 启动
然后报错
 def get_provider_api_key(self, model_id: Optional[str] = None, prefer_custom: bool = True) -> Union[str | dict]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
我的python版本
python：3.9.13

**Comment by zxhlyh** [comment]
Try to upgrade the Python version.

**Comment by techflag** [comment]
> 

which version works fine

**Comment by takatost** [comment]
Python 3.10 or above is better
