### ISSUE TITLE
Localhost preview does not work.

### ISSUE THREAD

**Issue by LLMR-boringtao** [langgenius/dify#2863]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Dify admin planner works properly on local. However, once I built an agent. I cannot preview it, such as using http://localhost/chat/sg52MLhzqyztDjKj

Anyone can help? Thanks!

**Comment by crazywoola** [comment]
Please provide more information, such as why and what did you get, better with some information from the web console.

**Comment by LLMR-boringtao** [comment]
Hi, Craztwoola

I followed exactly the same steps as I built on the Dify platform, on which once I build the agent, I click on the preview button, such as https://udify.app/chat/oFSTZX2eKGBAFSRa, I can chat with the agent. 
On the other hand, on my local Mac, after the agent has been built and running successfully, I click on the preview, which is http://localhost/chat/sg52MLhzqyztDjKj, it open a webpage showing "cannot connect to server", nothing shown on the docker terminal. 

Thanks!

**Comment by LLMR-boringtao** [comment]
@crazywoola 

Then I try customising steps using the following parameters:

# APP ID
NEXT_PUBLIC_APP_ID='2546cdfa-7d77-4748-a287-82acd37fe12b'
# APP API key
NEXT_PUBLIC_APP_KEY='app-ZAuvFOZL2ZNKuVA77NAyAngt'
# API url prefix
NEXT_PUBLIC_API_URL='http://localhost/v1'

Then after I nom run dev, and open localhost:3000, it shows: 500 App is unavailable. I confirm the DIFY backend is up running and working properly.

**Comment by crazywoola** [comment]
> @crazywoola
> 
> Then I try customising steps using the following parameters:
> 
> # APP ID
> NEXT_PUBLIC_APP_ID='2546cdfa-7d77-4748-a287-82acd37fe12b'
> 
> # APP API key
> NEXT_PUBLIC_APP_KEY='app-ZAuvFOZL2ZNKuVA77NAyAngt'
> 
> # API url prefix
> NEXT_PUBLIC_API_URL='http://localhost/v1'
> 
> Then after I nom run dev, and open localhost:3000, it shows: 500 App is unavailable. I confirm the DIFY backend is up running and working properly.


"cannot connect to server" this means there is something wrong in your configuration file. And above codes are not relevant at all. 



> Hi, Craztwoola @crazywoola
> 
> I followed exactly the same steps as I built on the Dify platform, on which once I build the agent, I click on the preview button, such as https://udify.app/chat/oFSTZX2eKGBAFSR, I can chat with the agent. On the other hand, on my local Mac, after the agent has been built and running successfully, I click on the preview, which is http://localhost/chat/sg52MLhzqyztDjKj, it open a webpage showing "cannot connect to server", nothing shown on the docker terminal.
> 
> Thanks!

And this should be a frontend error, in this case, you need paste the information from the web console.
