### ISSUE TITLE
laf 平台函数运行返回 return { message: '签名验证失败', code: 401 }

### ISSUE THREAD

**Issue by jiahuamld** [langgenius/dify#2868]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

按照文档操作
https://docs.dify.ai/v/zh-hans/learn-more/use-cases/integrate-with-wecom-using-dify#qian-zhi-zhun-bei 
最后函数运行返回 return { message: '签名验证失败', code: 401 }

**Comment by crazywoola** [comment]
Close due to #1542
