### ISSUE TITLE
Why is the locally deployed model Agent modal not functioning as Function calling in Xinference?

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#2871]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Why are the locally deployed models ChatGLM3-6b and qwen, as well as the Agent modal, not functioning as Function calling in Xinference?

- Please refer to the following screenshot.
![121](https://github.com/langgenius/dify/assets/21255047/3de51812-629e-44e0-8fd6-8ed41fe3cd09)
![122](https://github.com/langgenius/dify/assets/21255047/49455ba8-4f0c-4dd8-86c8-9ec30e406209)
![123](https://github.com/langgenius/dify/assets/21255047/4177604c-452e-4d73-8c32-abb5afc3e70a)

**Comment by Yeuoly** [comment]
hello, this is a frontend related issue, dify actually use `function calling` ability to invoke the tool

**Comment by andylzming** [comment]
> hello, this is a frontend related issue, dify actually use `function calling` ability to invoke the tool

Why is the Agent model Function calling when openai_api is used to access chatglm3-6b?

**Comment by andylzming** [comment]
> hello, this is a frontend related issue, dify actually use `function calling` ability to invoke the tool

Why is the Agent model Function calling when openai_api is used to access chatglm3-6b?

![121](https://github.com/langgenius/dify/assets/21255047/108237f9-2a21-45c3-813d-61da8a760f57)

![122](https://github.com/langgenius/dify/assets/21255047/67e21e1a-a8b0-4de7-b565-e72cbe99e5be)

![123](https://github.com/langgenius/dify/assets/21255047/0d0ddd7a-030e-411c-bd43-eec835546203)

**Comment by Yeuoly** [comment]
Sorry for the confusion. It seems I'm not fully understanding your point. If you're wondering why Dify uses the OpenAI standard to access chatglm3-6b, it's because its official repository supports OpenAI, and there's an OpenAI server demo provided. This allows us to quickly deploy services and integrate them with Dify.

**Comment by Yeuoly** [comment]
It's actually function calling if you have already upgraded your XInference to the latest version, Dify will fetch the model abilities from  XInference and use `function calling` if  it's available, could you please let me see the version of your deployed XInference?

**Comment by andylzming** [comment]
> It's actually function calling if you have already upgraded your XInference to the latest version, Dify will fetch the model abilities from XInference and use `function calling` if it's available, could you please let me see the version of your deployed XInference?

xinference is the latest version
![1212](https://github.com/langgenius/dify/assets/21255047/ac50e1b6-0ab1-4cea-94d5-d3b9015c2542)

**Comment by Air-duct** [comment]
Has this problem been resolved? I have also encountered a similar situation where errors occur when using the tool in Dify

**Comment by xs818818** [comment]
更新到0.9.4版本，使用qwen1.5，我成功了

**Comment by andylzming** [comment]
> 更新到0.9.4版本，使用qwen1.5，我成功了

已升级到 0.9.4，还是不行。
![12](https://github.com/langgenius/dify/assets/21255047/a871594e-7c94-4622-bbd7-4efb021ad67a)

**Comment by andylzming** [comment]
@Yeuoly Have you found out the reason for this?

**Comment by Yeuoly** [comment]
> > 更新到0.9.4版本，使用qwen1.5，我成功了
> 
> 已升级到 0.9.4，还是不行。 ![12](https://private-user-images.githubusercontent.com/21255047/316517351-a871594e-7c94-4622-bbd7-4efb021ad67a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjUwOTksIm5iZiI6MTcxMTQyNDc5OSwicGF0aCI6Ii8yMTI1NTA0Ny8zMTY1MTczNTEtYTg3MTU5NGUtN2M5NC00NjIyLWJiZDctNGVmYjAyMWFkNjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDZjMTZlNTMxOGQ1MWNkNDA3YzRkMzU3YjMwYTdjMDNhM2Q3NmEyNDJiZmIwYzcxMTcyNTI5OTAwN2ZkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sywexUREnoLhA8KoLKFcq8gW3uUAXhx4M2hYtfNIcfQ)

Remove the old credentials and setup again, it will be ok.

**Comment by andylzming** [comment]
> > > 更新到0.9.4版本，使用qwen1.5，我成功了
> > 
> > 
> > 已升级到 0.9.4，还是不行。 ![12](https://private-user-images.githubusercontent.com/21255047/316517351-a871594e-7c94-4622-bbd7-4efb021ad67a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjUwOTksIm5iZiI6MTcxMTQyNDc5OSwicGF0aCI6Ii8yMTI1NTA0Ny8zMTY1MTczNTEtYTg3MTU5NGUtN2M5NC00NjIyLWJiZDctNGVmYjAyMWFkNjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDZjMTZlNTMxOGQ1MWNkNDA3YzRkMzU3YjMwYTdjMDNhM2Q3NmEyNDJiZmIwYzcxMTcyNTI5OTAwN2ZkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sywexUREnoLhA8KoLKFcq8gW3uUAXhx4M2hYtfNIcfQ)
> 
> Remove the old credentials and setup again, it will be ok.

Does this refer to Dify or Xinference?

**Comment by Yeuoly** [comment]
> > > > 更新到0.9.4版本，使用qwen1.5，我成功了
> > > 
> > > 
> > > 已升级到 0.9.4，还是不行。 ![12](https://private-user-images.githubusercontent.com/21255047/316517351-a871594e-7c94-4622-bbd7-4efb021ad67a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjUwOTksIm5iZiI6MTcxMTQyNDc5OSwicGF0aCI6Ii8yMTI1NTA0Ny8zMTY1MTczNTEtYTg3MTU5NGUtN2M5NC00NjIyLWJiZDctNGVmYjAyMWFkNjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDZjMTZlNTMxOGQ1MWNkNDA3YzRkMzU3YjMwYTdjMDNhM2Q3NmEyNDJiZmIwYzcxMTcyNTI5OTAwN2ZkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sywexUREnoLhA8KoLKFcq8gW3uUAXhx4M2hYtfNIcfQ)
> > 
> > Remove the old credentials and setup again, it will be ok.
> 
> Does this refer to Dify or Xinference? How does it work?

Dify will fetch all the necessary meta info from Xinference while adding credentials, such as Dose the model supports function call, however, the old version of Xinference will not return it, that's why we should upgrade it to the latest and setup credentials again.

**Comment by andylzming** [comment]
model_ability 增加 tools
```
{
  "version": 1,
  "context_length": 8192,
  "model_name": "custom-chatglm-3",
  "model_lang": [
    "zh",
    "en"
  ],
  "model_ability": [
    "chat",
    "tools"
  ],
  "model_family": "chatglm3",
  "model_specs": [
    {
      "model_format": "pytorch",
      "model_size_in_billions": 6,
      "quantizations": [
        "4-bit",
        "8-bit",
        "none"
      ],
      "model_id": "THUDM/chatglm3-6b",
      "model_uri": "file:///home/models/chatglm3-6b"
    }
  ]
}
```

**Comment by Starlento** [comment]
> model_ability 增加 tools
> 
> ```
> {
>   "version": 1,
>   "context_length": 8192,
>   "model_name": "custom-chatglm-3",
>   "model_lang": [
>     "zh",
>     "en"
>   ],
>   "model_ability": [
>     "chat",
>     "tools"
>   ],
>   "model_family": "chatglm3",
>   "model_specs": [
>     {
>       "model_format": "pytorch",
>       "model_size_in_billions": 6,
>       "quantizations": [
>         "4-bit",
>         "8-bit",
>         "none"
>       ],
>       "model_id": "THUDM/chatglm3-6b",
>       "model_uri": "file:///home/models/chatglm3-6b"
>     }
>   ]
> }
> ```

Sorry to bother. It is my first time using xinference. My version is v0.11.1.
But I cannot see tools in model_ability in 9997 webui, where did you set it?
![image](https://github.com/langgenius/dify/assets/33574105/6b3d8f63-faa7-42b4-bee7-e96dd60e2868)
