### ISSUE TITLE
是否有计划开放api允许上传源文本或者文件到dify来构建知识库，然后再通过对话api根据文本问答？

### ISSUE THREAD

**Issue by johnsonwong666** [langgenius/dify#288]
是否有计划开放api允许上传源文本或者文件到dify来构建知识库，然后再通过对话api根据文本问答？

**Comment by JohnJyong** [comment]
We are currently working on dataset import  from Notion , service api  will be rolled out in a later iteration，thanks for your attention。

**Comment by johnsonwong666** [comment]
已经实现了嘛？
