### ISSUE TITLE
Can't perform flask db upgrade

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2880]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After latest commit on main branch, I get "ERROR [flask_migrate] Error: Can't locate revision identified by '417acfc005d6'" when trying to du db flask upgrade.

### ✔️ Expected Behavior

Normal migration behaviour

### ❌ Actual Behavior

Can't do flask db upgrade / flask does start, but knowledge tab is gone from the frontend.

**Comment by AndyMik90** [comment]
Can't find revision 417acfc005d6 in the migration folder.

**Comment by crazywoola** [comment]
> Can't find revision 417acfc005d6 in the migration folder.

@AndyMik90 I noticed these happens sometime. I think you need to manually create an empty migration for this or you will need to find a nearest version and edit the `alembic_version ` in database as the bot said.

**Comment by erigo** [comment]
I think it's as the bot mentioned:
Branching and merging issues: If migrations were created on different branches and then merged into the main branch without resolving the revision history, it could lead to missing revisions.

To address this, you should edit the `.env` file and set `MIGRATION_ENABLED` to `false`.

**Comment by frankchen121212** [comment]
> I think it's as the bot mentioned: Branching and merging issues: If migrations were created on different branches and then merged into the main branch without resolving the revision history, it could lead to missing revisions.
> 
> To address this, you should edit the `.env` file and set `MIGRATION_ENABLED` to `false`.

Problem solved with this suggestion, thank you 👍 💯
