### ISSUE TITLE
Deploying RAG Vector Search in Offline/Private Environments: A Solution Inquiry

### ISSUE THREAD

**Issue by kingke0620** [langgenius/dify#2882]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I want to deploy in a private domain environment, but it seems that the vector search of RAG requires an internet connection. How can I address this issue?

**Comment by takatost** [comment]
This requires your embedding model to be deployed locally.
