### ISSUE TITLE
如何支持本地开源GPT如OpenGLM-6B

### ISSUE THREAD

**Issue by forest520** [langgenius/dify#29]

**Comment by takatost** [comment]
在计划中，目前只支持 OpenAI

**Comment by Vickzhang** [comment]
需求+1

**Comment by goodyorkye** [comment]
需求+1

**Comment by wking1986** [comment]
大佬，支持ChatGLM有时间点吗？

**Comment by yananliuyanjiang** [comment]
需求 +1

**Comment by yananliuyanjiang** [comment]
求大佬适配

**Comment by xusenlinzy** [comment]
可以通过实现openai接口的响应体，只需要修改OPENAI_API_BASE，参考[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)

**Comment by qianxuemin** [comment]
需求+1

**Comment by coolnetboy** [comment]
为什么要用GLM

**Comment by cnhh-cyc** [comment]
需求+1 
对于知识库的应用场景不需要很高级的LLM来处理
而隐私保密性强的知识库，必然期望全局本地化部署

**Comment by youyajike** [comment]
chatGLM-6B + 1  全套完全本地化部署支持，有些企业是内网使用，不便于访问发布接口

**Comment by gaocegege** [comment]
通过 https://github.com/tensorchord/modelz-llm 在本地运行了一个 Bloomz（也支持 ChatGLM，FastChat T5 等），然后跟 dify 集成在一起，让 dify 使用本地的模型而不是 OpenAI，跑通了 text completion 的 demo，基本没有修改 dify 的代码：


https://github.com/langgenius/dify/assets/5100735/13e1a123-7914-4c7d-9e8d-f9022d065a08

**Comment by gaocegege** [comment]
OpenAI:

![image](https://github.com/langgenius/dify/assets/5100735/41614c66-5036-4e66-9803-d2fae9d92c8e)

Bloomz 560M 部署在 CPU 上：

![image](https://github.com/langgenius/dify/assets/5100735/e35703ad-82a8-4725-b5db-db49b5f82991)

**Comment by coolnetboy** [comment]
请问这个GLM-6B的支持哪里可以看到啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langgenius/dify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 下午5:18
***@***.***&gt;;
抄送:&nbsp;"Patrick ***@***.******@***.***&gt;;
主题:&nbsp;Re: [langgenius/dify] 如何支持本地开源GPT如OpenGLM-6B (Issue #29)





 
chatGLM-6B + 1  全套完全本地化部署支持，有些企业是内网使用，不便于访问发布接口
