### ISSUE TITLE
SyntaxError: Unterminated string in JSON at position 50

### ISSUE THREAD

**Issue by bhctest123** [langgenius/dify#290]
Dify version: Self Host

## Steps To Reproduce
I was using the self-hosted Dify 0.3.1 is the latest version available.

In the page /app/b25a76cd-9329-4ae4-947c-feeacfa36709/configuration

on each chat sent in i got this error: "SyntaxError: Unterminated string in JSON at position 50"

**Comment by JohnJyong** [comment]
This error seems to be disconnected from the interaction with openAI, pls check your local network status，thanks

**Comment by AShabana** [comment]
I am facing the same issue 
Could you please share more info about it's root cause or its fix
