### ISSUE TITLE
HTTPConnectionPool Max retries exceeded,  Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by xqinshan** [langgenius/dify#2905]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Environment:
WINDOWS，Edge,  OLLAMA(0.1.29)  Dify(0.5.9 community)

Ollama run llava in a CMD quit well. 

But Ollama cannot be integrated in Dify as Setting > Model Providers > Ollama  fill in
    Model Name: llava
    Base URL: http://127.0.0.1:11434
  '''
as https://docs.dify.ai/tutorials/model-configuration/ollama.  

The error message during validation is :
httpconnectionpool(host=127.0.0.1, port=11434): max retries exceeded with url:/cpi/chat  (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8562812c20>:  fail to establish a new connection:[Errno 111] Connection refused'))

The ollama_host has been set:
> set Ollama_host
OLLAMA_HOST=127.0.0.1:11434

How can I integrate Ollama in Dify? Thank you.

**Comment by crazywoola** [comment]
Please follow the instruction the bot provided 👆 you need to check the OLLAMA_HOST env is configured right. and make sure you are not using `127.0.0.1` if you are using docker to start the application.
