### ISSUE TITLE
What is the default username and password of the web login page

### ISSUE THREAD

**Issue by zhangningboo** [langgenius/dify#2906]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

What is the default username and password of the web login page? I check the docs, and can't find out the answer

**Comment by zhangningboo** [comment]
Thanks for reply! But, accounding the infomation, I can't solve my problem. I setup this server with docker command in the section [docker-compose](https://docs.dify.ai/getting-started/install-self-hosted/docker-compose)
- the `setAdminAccount ` doesn't in [login.ts](https://github.com/langgenius/dify/blob/main/web/i18n/pt-BR/login.ts) 
- [https://github.com/langgenius/dify/issues/1247](https://github.com/langgenius/dify/issues/1247) doesn't give a solution
- the [doc](https://doc.dify.ai/)  server may lost. I guess you probably mean `https://docs.dify.ai/`
<img src="https://github.com/langgenius/dify/assets/110680007/782033aa-5df9-49cf-b2e9-fdfc56482663" width="60%" />

**Comment by zhangningboo** [comment]
I find a solution in [https://docs.dify.ai](https://docs.dify.ai/getting-started/install-self-hosted/install-faq) section[How to reset the password if the local deployment initialization fails with an incorrect password?](https://docs.dify.ai/getting-started/install-self-hosted/install-faq#id-1.-how-to-reset-the-password-if-the-local-deployment-initialization-fails-with-an-incorrect-password) about , I am trying~~~

**Comment by zhangningboo** [comment]
It doesn't work~~~, I don't know the default email for login~~~
<img src="https://github.com/langgenius/dify/assets/110680007/f864a7ca-6bae-4f06-b279-488d18b1fd15" width="60%" />

**Comment by crazywoola** [comment]
After a fresh install. You should navigate to 'http://localhost/install' to setup your own email and password. In short it's up to you.

**Comment by miendinh** [comment]
> After a fresh install. You should navigate to 'http://localhost/install' to setup your own email and password. In short it's up to you.

that helps. thanks @crazywoola

**Comment by 812406210** [comment]
> > After a fresh install. You should navigate to 'http://localhost/install' to setup your own email and password. In short it's up to you.
> 
> that helps. thanks @crazywoola
I deployed it locally and it doesn't work to access this address， can u tell me how to fix it

**Comment by lins403** [comment]
> > > After a fresh install. You should navigate to 'http://localhost/install' to setup your own email and password. In short it's up to you.
> > 
> > 
> > that helps. thanks @crazywoola
> > I deployed it locally and it doesn't work to access this address， can u tell me how to fix it

run this in terminal: `docker exec -it docker-api-1 flask reset-password`
new password must be 8+ characters and include numbers and letters. see the [doc](https://docs.dify.ai/getting-started/install-self-hosted/install-faq#id-1.-how-to-reset-the-password-if-the-local-deployment-initialization-fails-with-an-incorrect-password)
Or you can also reset the email. see: https://github.com/langgenius/dify/blob/main/api/commands.py

**Comment by zhangwei5656** [comment]
> > > > After a fresh install. You should navigate to 'http://localhost/install' to setup your own email and password. In short it's up to you.
> > > 
> > > 
> > > that helps. thanks @crazywoola
> > > I deployed it locally and it doesn't work to access this address， can u tell me how to fix it
> 
> run this in terminal: `docker exec -it docker-api-1 flask reset-password` new password must be 8+ characters and include numbers and letters. see the [doc](https://docs.dify.ai/getting-started/install-self-hosted/install-faq#id-1.-how-to-reset-the-password-if-the-local-deployment-initialization-fails-with-an-incorrect-password) Or you can also reset the email. see: https://github.com/langgenius/dify/blob/main/api/commands.py

after runing this command, it still prompted me an error:
sorry. the account: [my email] not exist.

**Comment by duxh** [comment]
try docker exec -it docker-api-1 flask create-tenant with your email and password
