### ISSUE TITLE
api request error

### ISSUE THREAD

**Issue by m5314** [langgenius/dify#2908]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I already requested the chat-message api once, and I got a message-id .  But when I request the suggested api it returned 404 
`curl -X POST 'http://127.0.0.1:5001/v1/chat-messages' \
--header 'Authorization: Bearer app-W7VONpikFmcEnMinBTUhua8K' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "What are the specs of the iPhone 13 Pro Max?",
    "response_mode": "streaming",
    "conversation_id": "",
    "user": "abc-123",
    "files": [
      {
        "type": "image",
        "transfer_method": "remote_url",
        "url": "https://cloud.dify.ai/logo/logo-site.png"
      }
    ]
}'
`
`data: {"event": "message_end", "task_id": "535bf32f-338b-40e0-993b-aa9e85a10d55", "id": "cd9d7a95-5ab7-4aac-8e6e-7652d671c485", "message_id": "cd9d7a95-5ab7-4aac-8e6e-7652d671c485", "conversation_id": "5fcd73b6-0e4a-486b-8d28-bd23b75c0b6f", "metadata": {"usage": {"prompt_tokens": 228, "prompt_unit_price": "0.01", "prompt_price_unit": "0.001", "prompt_price": "0.0022800", "completion_tokens": 69, "completion_unit_price": "0.03", "completion_price_unit": "0.001", "completion_price": "0.0020700", "total_tokens": 297, "total_price": "0.0043500", "currency": "USD", "latency": 3.853132416988956}}}`

`curl 'http://127.0.0.1:5001/v1/messages/cd9d7a95-5ab7-4aac-8e6e-7652d671c485/suggested' --header 'Authorization: Bearer app-W7VONpikFmcEnMinBTUhua8K' --header 'Content-Type: application/json'
`
`{
    "code": "not_found",
    "message": "Message Not Exists.",
    "status": 404
}`

**Comment by takatost** [comment]
Sorry about that, we forgot to mention the `user` Query Param in the API documentation. We'll have that corrected ASAP.
