### ISSUE TITLE
The dockerfile is not compatible for podman-compose

### ISSUE THREAD

**Issue by hotsmile** [langgenius/dify#2912]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

i cd docker directory
use podman-compose 

### ✔️ Expected Behavior

the docker configuration is not  compatible for  podman-compose , i wish you can  fix it

### ❌ Actual Behavior

i use podman-compose to run it , but some errors are founded .

**Comment by crazywoola** [comment]
Please provide the errors, that would be helpful to solve the issu.e

**Comment by LeoQuote** [comment]
podman compose is not compatible with docker compose, read more at: https://www.redhat.com/sysadmin/podman-compose-docker-compose
