### ISSUE TITLE
ERROR:Maximum update depth exceeded.This can happen when a component repeatdly calls set State inside componentwillUpdate...

### ISSUE THREAD

**Issue by yangyubin1** [langgenius/dify#2915]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

<img width="818" alt="dify-issue" src="https://github.com/langgenius/dify/assets/26540663/63abae4f-c154-4977-8ba0-3c0c3e1d1ec0">

Hello, when I ask llm with files, sometimes chat window will show the bug above (eg:  the response will show some Code snippets)
then the answer can not be displayed 。 I make sure that api actually give the full response，but the bug shows in web。

thanks for finding the reason

### ✔️ Expected Behavior

Answer can be displayed

**Comment by yangyubin1** [comment]
Unfortunately, I am not familiar with REACT. So I need to spend some time for learning it, thanks for your reply....
If I can't solve this problem at last , I will provide more specific  information  or logs for your help.  thanks

**Comment by crazywoola** [comment]
It should be fixed in main branch now.
