### ISSUE TITLE
Hello team, I have a delay of 2 seconds when sending a streaming request through an AI application compared to a streaming return request from a cloud API. May I ask what the problem is?

### ISSUE THREAD

**Issue by wgq910668** [langgenius/dify#2916]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Hi, Tearm
Deploy Dify locally and configure the Qianwen API for the model. For applications built using Dify, there is a 2-second wait delay when requesting API requests. However, there is no delay when requesting Qianwen's native API interface. May I ask what the reason is? How to solve this problem?
I can see from the log that when sending a request, an event ping time is sent twice before the constructed AI application interface starts streaming back.

**Comment by tonglei856** [comment]
metoo, Please. Thank you.

**Comment by abdullahbaa5** [comment]
same issue when using openai gpt model as well.

ping is sent back initially causing delay in the start.

**Comment by crazywoola** [comment]
Set the `auto_generate_name` to false will solve this issue.

**Comment by abdullahbaa5** [comment]
> Set the `auto_generate_name` to false will solve this issue.

I set it as false and can confirm the name if not generating anymore:
![image](https://github.com/langgenius/dify/assets/38984510/1c5716c4-06fa-44a9-84bb-1dff868c06d9)

but the streaming still has a delay (sometimes does not even stream and sends full message)
