### ISSUE TITLE
dify request model has high latency

### ISSUE THREAD

**Issue by simzheng1001** [langgenius/dify#2917]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

There is a delay of 3 or 4 seconds between the request for dify and the model output

### ✔️ Expected Behavior

What configuration can be changed to reduce latency

### ❌ Actual Behavior

What configuration can be changed to reduce latency

**Comment by simzheng1001** [comment]
本地部署

**Comment by simzheng1001** [comment]
dify is deployed locally

**Comment by takatost** [comment]
Suggest upgrade to the latest version, Quite a few latency optimizations have been rolled out.

**Comment by crazywoola** [comment]
Set the `auto_generate_name` to false will solve this issue.

**Comment by CurtisONeal** [comment]
Can anyone confirm that auto_generate_name off will reduce the latency.
