### ISSUE TITLE
docker 私有化部署管理员账号密码登录提示

### ISSUE THREAD

**Issue by MeDeity** [langgenius/dify#292]
管理账号设置后，自动跳转到登录页面,但是总提示 Invalid email or password 参考#257 进行docker rm 后，重新docker-compose up -d仍无法修复问题

![image](https://github.com/langgenius/dify/assets/25357490/97d34f86-c283-4393-a778-d0c42eec8785)

![image](https://github.com/langgenius/dify/assets/25357490/a539af4a-dfc8-4b60-bfcb-0793834ccab2)

**Comment by takatost** [comment]
you can try 
```
docker exec -it docker-api-1 flask reset-password
```

**Comment by MeDeity** [comment]
its work,thx

**Comment by Jonny-Smith-GitHub** [comment]
> you can try following script to reset password
> 
> ```
> docker exec -it docker-api-1 flask reset-password
> ```

it works.

**Comment by angleboy8** [comment]
I put this command "docker exec -it docker-api-1 flask reset-password". However, the following error is still displayed.
![3](https://github.com/user-attachments/assets/a353385d-8c8c-425f-8fce-e41aac700edb)

**Comment by eatmore** [comment]
> I put this command "docker exec -it docker-api-1 flask reset-password". However, the following error is still displayed. ![3](https://private-user-images.githubusercontent.com/20549943/383458001-a353385d-8c8c-425f-8fce-e41aac700edb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTcxNzAsIm5iZiI6MTczMTU5Njg3MCwicGF0aCI6Ii8yMDU0OTk0My8zODM0NTgwMDEtYTM1MzM4NWQtOGM4Yy00MjVmLThmY2UtZTQxYWFjNzAwZWRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE1MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZDBiZWJkZWMwODQyNzFhOGVhM2Y4MTQ1NzUxMmE0M2QxODA4N2VkZGRmNTQ1NDU1YWI4ZDkxOWI5YzQ3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BPZjryaDvjEA85lajy3pEa6iNa5cWzOe2bzhXzK8JNo)

docker exec -it docker_api_1 flask reset-password

**Comment by noneback** [comment]
> I put this command "docker exec -it docker-api-1 flask reset-password". However, the following error is still displayed. ![3](https://private-user-images.githubusercontent.com/20549943/383458001-a353385d-8c8c-425f-8fce-e41aac700edb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDc1MDAsIm5iZiI6MTczMzQwNzIwMCwicGF0aCI6Ii8yMDU0OTk0My8zODM0NTgwMDEtYTM1MzM4NWQtOGM4Yy00MjVmLThmY2UtZTQxYWFjNzAwZWRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNjYzN2U0YzY5ZDRiMzA3NTkzODAzOWZmZDEzMmRjZWUyMGIyOWExOWZjYWQ5YmQwZDk5YTkwOGM1OTQ2YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JrTZ3cUn0qgNyBCBBlwGdtUZIgVUJhrRo54Ko2omEtU)
 Same problem

**Comment by joulong** [comment]
试了很多次都是出现以下讯息,在 1.0.0 版以前都正常
Account not found for email: xxxxxxx@gmail.com
