### ISSUE TITLE
how to setup rate limit when an app is published

### ISSUE THREAD

**Issue by isha13143** [langgenius/dify#2921]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

HI, i have built a QnA app in Dify. I have embedded the code in my simple website and want it to put it for  testing from users. I want to know their feedback but i want to put some rate limit on how much time and how many questions a user ask so that the app is not bombarded with lot of useless queries. So, please help me on how to set rate limit on the website. i am a  non technical person please provide is there any way how to do that in DIFY.

**Comment by isha13143** [comment]
ok

**Comment by isha13143** [comment]
But where in the dify dashboard i can change or customize this code? by the way i am a non technical person.

**Comment by crazywoola** [comment]
> But where in the dify dashboard i can change or customize this code? by the way i am a non technical person.

@isha13143 No, you can not actually. We did not support this feature.
