### ISSUE TITLE
The webscraper plugin cannot capture the full content of the webpage

### ISSUE THREAD

**Issue by Caixiaopig** [langgenius/dify#2924]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create an application, use Agent mode, and add the WEBSCRAPER tool
2. Publish the application and chat
3. Allow the chatbot to access the website and summarize the content, for example: https://mp.weixin.qq.com/s/Eq0VXGnD1JAI3UDcXS8Csg
The summary content is missing, open the response content of WEBSCRAPER, and find that it did not return the complete webpage text content.

### ✔️ Expected Behavior

Can the WEBSCRAPER capture all the content and provide it to the large model for subsequent dialogue?

### ❌ Actual Behavior

The summary content is missing, open the response content of WEBSCRAPER, and find that it did not return the complete webpage text content.

**Comment by crazywoola** [comment]
This webpage is too long to be retrieved and set them in the agent. This is a limitation of llm itself. Also, the web scrapper will be rejected due to the anti-spider policy, because this is a simple tool.
