### ISSUE TITLE
Add ComfyUI workflow api

### ISSUE THREAD

**Issue by vindia9** [langgenius/dify#2927]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am trying to use LLM in conjunction with controlling image generation, for which I need to use Stable Diffusion. However, the Stable Diffusion WebUI does not offer enough flexibility and cannot facilitate high degrees of creative freedom through workflows like Stable Diffusion ComfyUI can.

### 2. Describe the feature you'd like to see

Add API for Stable Diffusion ComfyUI in the Tools - Stable Diffusion.

### 3. How will this feature improve your workflow or experience?

I can create an assistant based on Stable Diffusion ComfyUI that uses JSON-formatted workflows for calls, allowing for image generation with a higher degree of freedom.

### 4. Additional context or comments

Stable Diffusion ComfyUI API Example
https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This is in alpha test right now.
