### ISSUE TITLE
Failed to add dataset segment

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#2930]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Creating an empty data set and adding an empty document will fail when adding segments later（weaviate）:
<img width="1354" alt="image" src="https://github.com/langgenius/dify/assets/1925650/68cf3818-e23c-49d4-a396-752fc4cefa73">
Need to catch exception：
<img width="740" alt="image" src="https://github.com/langgenius/dify/assets/1925650/dc42efdf-4980-43fd-af4b-e01cb0894e9a">

### ✔️ Expected Behavior

Added segment successfully

### ❌ Actual Behavior

Added segment failed

**Comment by JohnJyong** [comment]
fixed by PR #3021  @wangrg
