### ISSUE TITLE
Dify helm chart

### ISSUE THREAD

**Issue by LeoQuote** [langgenius/dify#2931]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Previously a helm chart was developed by @BorisPolonsky at #393, but this helm chart contains certain problems:
1. sensitive info like database password is passed by plain text and stored in configmap (which is also plain text)
2. extensive values file making people hard to just getting started, and no readme file to guide users.

### 2. Describe the feature you'd like to see

I developed a brand-new helm chart -> https://github.com/douban/charts/tree/master/charts/dify 

This new chart is friendly for newcomers, with a simple minimal values file less than 20 lines, you can have a dify up and running inside k8s.

For power users, you can set all your config with environment variables, using k8s native environment definition, which make it possible for you to use vault or other secret manager to predefine these sensitive data.

```
- name: DB_USERNAME
  value: "foo"
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: dify
      key: DB_PASSWORD
```

### 3. How will this feature improve your workflow or experience?

Summary, the new chart is simple yet powerful, the following are the advantages:
1. making use of ingress instead of the standalone nginx pod, no extra pods just for proxying
2. support native environment variable in k8s, making it possible to use predefined secret instead of password in plain text.
3. simple minimal config for experiment, and detailed guide for user to move it into production.

Disadvantage:
1. currently embedded vector database is not supported, you have to prepare one previously and set the environment
2. to avoid possible conflict when starting up API containers, the auto migration is disabled, users must execute `flask db upgrade` manully after installation and upgrade.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by BorisPolonsky** [comment]
Nice

**Comment by LeoQuote** [comment]
@BorisPolonsky Thanks for the support! You can try this chart or maybe submit new issues, thanks for your previous contribution!
