### ISSUE TITLE
Self Hosted (Docker), api call /chat-messages with response_mode: streaming, the message_end response lasts up to 5 seconds.

### ISSUE THREAD

**Issue by tonglei856** [langgenius/dify#2935]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a App in Dify, name A
2. Use api to call A: /chat-messages with response_mode: streaming
3. The response of the OpenAI has ended, but the message_end response of the last message is as long as 5 seconds.

### ✔️ Expected Behavior

Message_end responds as quickly as possible

### ❌ Actual Behavior

the message_end response of the last message is as long as 5 seconds.

**Comment by crazywoola** [comment]
Duplicate https://github.com/langgenius/dify/issues/2916
