### ISSUE TITLE
api name for api tool is not friendly

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#2939]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

![Screenshot 2024-03-22 085247](https://github.com/langgenius/dify/assets/5020396/44a1c106-b4fa-400f-866d-774dfbb14cf1)

Currently, the name of the API is generated using PATH_METHOD, as you can see in the attachment, the name quickly become unmeaningful. If we enable 'Reference' feature, this name will actually be shown to our end users which is un-acceptable for them.

### 2. Describe the feature you'd like to see

Is it possible for dify to use the 'summery' if it is present, and only when 'summery' is missing, then use this generated name?

### 3. How will this feature improve your workflow or experience?

Will give user a much clearer indication what is going on under the hook

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
You can declare an `operationId` on each path, so that Dify will use it instead, otherwise, Dify joins the path and method as a unique name tool.
