### ISSUE TITLE
Deleting a dataset while it indexes

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2941]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When a bigger PDF is indexing, if one deletes it, the API server continues trying to index it, giving 404:
console/api/datasets/63dc9133-3589-4985-991c-e864bd54ff6a/documents/8ce44fcf-085c-4b06-93f5-e0ac7dc1e110/indexing-status HTTP/1.1" 404 - and can sometime continue until it times out.

### 2. Describe the feature you'd like to see

Add some type of check/logic in the celery/api to prevent this from happending.

### 3. How will this feature improve your workflow or experience?

Reduces the possiblity for errors and elimitate que on server resources. 

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by JohnJyong** [comment]
@JzoNgKVO pls take a look.  for the 'console/api/datasets/63dc9133-3589-4985-991c-e864bd54ff6a/documents/8ce44fcf-085c-4b06-93f5-e0ac7dc1e110/indexing-status' endpoint, 
if this endpoint reports an error, the call should be stopped. 
@AndyMik90 thanks for your suggestion.

**Comment by JohnJyong** [comment]
@AndyMik90 support by this PR： https://github.com/langgenius/dify/pull/3156
