### ISSUE TITLE
Will dify add a feature like the multiagent mode of Coze?

### ISSUE THREAD

**Issue by csningli** [langgenius/dify#2950]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I design an application, I feel it natural to use a component-based style to construct the whole application piece by piece. Coze's multi-agent mode is thus very convenient.

### 2. Describe the feature you'd like to see

In Coze www.coze.com, they have a multi-agent mode which is conveninent to connect more than one chatbot. It will be useful if dify support this kind of architecture.

### 3. How will this feature improve your workflow or experience?

I thought the multi-agent mode is the best and necessary architecture to build a LLM application, as it is more flexible than the plugin feature, and will be enough to build any applications, together with the plugins

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Loading-m** [comment]
This proposal is very nice. I hope this feature's coming! 

Thanks to the Dify Team.

**Comment by takatost** [comment]
Hey there! We will be rolling out a more user-friendly Multi-Agent feature soon. Stay tuned!

**Comment by harrywang** [comment]
> Hey there! We will be rolling out a more user-friendly Multi-Agent feature soon. Stay tuned!

any update on this with link to documents？thanks!

**Comment by fastfading** [comment]
this feature has  not been implemented yet.   why close it ? 
any  ETA ?

**Comment by AllenWriter** [comment]
Please refer to this document: https://docs.dify.ai/guides/workflow/node/agent
