### ISSUE TITLE
新接入供应商，预定义模型，如何设置非流式，默认是流式的

### ISSUE THREAD

**Issue by Owen-MS** [langgenius/dify#2955]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

新接入供应商，预定义模型，如何设置非流式，默认是流式的，stream如何默认false

**Comment by crazywoola** [comment]
Close due to #1542
