### ISSUE TITLE
Does Dify support Multi-agent in LangGraph?

### ISSUE THREAD

**Issue by Loading-m** [langgenius/dify#2959]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Please refer to: https://python.langchain.com/docs/langgraph#multi-agent-examples

**Comment by Loading-m** [comment]
@dosu-bot
How to implement Multi-agent collaboration in Dify?

**Comment by Loading-m** [comment]
# https://github.com/langgenius/dify/issues/2950

# https://www.coze.com/docs/multiagent.html

That's what I'm saying.

**Comment by crazywoola** [comment]
Duplicate https://github.com/langgenius/dify/issues/2950
