### ISSUE TITLE
dify java调用400 bad request / 401

### ISSUE THREAD

**Issue by deepblue-star** [langgenius/dify#2960]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

在我把difyClientConstants.java中的URL改成http://localhost/v1，将API-KEY换成自己创建的助手的API-KEY之后，发送request仍然无法得到回复，得到的response返回的是400 bad request。
如果URL保持原本的，得到的response是401，response message为空。

应该如何正确调用java实现对话呢？

**Comment by deepblue-star** [comment]
> 你好 @deepblue-star！很高兴再次见到你在这里提问。希望你最近一切都好！
> 
> 根据您的描述，您在尝试使用Dify进行对话时遇到了400和401的HTTP响应代码。以下是一些可能的解决方案：
> 
> 1. **当将URL更改为`http://localhost/v1`时出现400 Bad Request**：这个错误表明`localhost`服务器可能没有正确设置来处理您发送的请求。请确保：
>    
>    * 您的本地服务器正在运行，并且可以在指定的URL上访问。
>    * 您正在尝试访问的端点（例如`/messages/{message_id}/feedbacks`，`/parameters`，`/files/upload`，`/completion-messages`，`/chat-messages`等）在您的本地服务器上已正确实现。
>    * 请求的有效负载和参数与您的本地服务器期望的匹配。
> 2. **使用原始URL时出现401 Unauthorized response**：这个错误表明服务器无法验证请求，可能是由于API密钥无效。请确保：
>    
>    * 您替换的API密钥是有效的，并且具有执行您试图执行的操作所需的权限。
>    * API密钥已正确包含在请求头中作为Bearer token。
> 
> 以下是一个基本的Java实现，它设置了一个类似于`DifyClient`的客户端：
> 
> ```java
> import okhttp3.OkHttpClient;
> import okhttp3.Request;
> import okhttp3.RequestBody;
> import okhttp3.MediaType;
> import okhttp3.Response;
> 
> public class DifyClient {
>     private String apiKey;
>     private String baseUrl;
>     private OkHttpClient client;
> 
>     public DifyClient(String apiKey) {
>         this.apiKey = apiKey;
>         this.baseUrl = "https://api.dify.ai/v1/"; // Change this to your desired base URL
>         this.client = new OkHttpClient();
>     }
> 
>     public Response sendRequest(String method, String endpoint, String jsonPayload) throws Exception {
>         RequestBody body = RequestBody.create(jsonPayload, MediaType.get("application/json; charset=utf-8"));
>         Request.Builder builder = new Request.Builder()
>                 .url(baseUrl + endpoint)
>                 .addHeader("Authorization", "Bearer " + apiKey)
>                 .addHeader("Content-Type", "application/json");
> 
>         Request request;
>         switch (method.toUpperCase()) {
>             case "POST":
>                 request = builder.post(body).build();
>                 break;
>             case "GET":
>                 request = builder.get().build();
>                 break;
>             // Add other HTTP methods as needed
>             default:
>                 throw new IllegalArgumentException("Unsupported HTTP method: " + method);
>         }
> 
>         return client.newCall(request).execute();
>     }
> 
>     // Implement other methods similar to the PHP version, using sendRequest
> }
> ```
> 
> 这个Java示例使用OkHttp进行HTTP请求。您需要将OkHttp添加到项目的依赖项中。另外，请记住在实际实现中正确处理异常和错误。
> 
> 如果您在`difyClientConstants.java`中将URL更改为`http://localhost/v1`，发送的请求的结构如下：
> 
> * **基本URL**：`http://localhost/v1/`
> * **头部**：
>   
>   * `Authorization`：`Bearer <api_key>`（其中`<api_key>`是在`DifyClient`类实例化时提供的API密钥）
>   * `Content-Type`：这可以是`application/json`用于JSON请求，或者`multipart/form-data`用于文件上传，具体取决于正在进行的请求类型。
> * **方法**：这取决于正在调用的特定函数（`GET`，`POST`，`PATCH`等）。
> * **端点**：这被附加到基本URL上，并指定正在访问的资源（例如，`messages/{message_id}/feedbacks`，`parameters`，`files/upload`，`completion-messages`，`chat-messages`，`messages`，`conversations`等）。
> * **主体**（对于`POST`和`PATCH`请求）：
>   
>   * 对于JSON请求（`Content-Type: application/json`），主体以JSON发送，根据`send_request`方法或正在调用的特定函数的数据参数进行结构化。
>   * 对于文件上传（`Content-Type: multipart/form-data`），主体以多部分表单数据的形式结构化，包括文件和任何指定的附加数据。
> * **查询参数**：对于`GET`请求，任何指定的参数都作为查询参数附加到URL上。
> 
> 希望这些信息能帮助您解决问题。如果您有任何其他问题或需要进一步的澄清，请随时提问。
> 
> ## Sources
> * [本地调试webapp-conversation api链接报401](https://github.com/langgenius/dify/issues/435)
> * [sdks/php-client/dify-client.php](https://github.com/langgenius/dify/blob/main/sdks/php-client/dify-client.php)
> * [api/controllers/console/app/message.py](https://github.com/langgenius/dify/blob/main/api/controllers/console/app/message.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

仍然不行，我这里是401错误，出现在：            Response chatResponse = chatClient.createChatMessage(inputs, query, user, true, null);
这一行中

**Comment by deepblue-star** [comment]
@dosu-bot 仍然不行，我这里还是401错误，出现在： Response chatResponse = chatClient.createChatMessage(inputs, query, user, true, null);
这一行中

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by crazywoola** [comment]
可以看看仓库里面 java sdk 代码
