### ISSUE TITLE
The content in the table is not included in the paragraph split by Dify.

### ISSUE THREAD

**Issue by YuMaiwen** [langgenius/dify#2963]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I uploaded a contract and asked for the total amount, but it could not answer this  simple questions accurately. I checked the paragraphs split by Dify automatically and found that they did not include the content in the table. 
Here is my document:
![image](https://github.com/langgenius/dify/assets/153471044/bc007d52-6035-4db1-a835-1b00bb087fbc)

 This is the paragraph, it skips the content in the table:
 
![image](https://github.com/langgenius/dify/assets/153471044/472e79ed-f2f5-4bf9-b7b3-34673da461a4)

I have tried to modify the Chunk settings and Index mode, but there is still no change

**Comment by crazywoola** [comment]
In this case you should implement your own extractor to extract the data from the source.

**Comment by YuMaiwen** [comment]
Sorry, I found it is success in the official trail site : https://cloud.dify.ai/  

![image](https://github.com/langgenius/dify/assets/153471044/103df1bd-535a-4a63-9d45-caf332d9e790)

In addition, the speed of document segmentation is much faster than my Self Hosted
