### ISSUE TITLE
自定义工具流式响应结果重复

### ISSUE THREAD

**Issue by 1102asd** [langgenius/dify#2972]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

当前最新代码

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

使自定义工具时，结果有2次返回，可以观察流式响应结果
![img_v3_029b_f4cbe3f8-e602-4352-8192-30f991fdb72g](https://github.com/langgenius/dify/assets/52064676/ca67325c-a372-4183-99f6-bc51cd0406ef)
怀疑是
![image](https://github.com/langgenius/dify/assets/52064676/79048903-67c4-4928-8008-16dfd935faf4)
ci此处有将最终的所有结果一次性吐出

**Comment by 1102asd** [comment]
![image](https://github.com/langgenius/dify/assets/52064676/2c90cd5f-444d-4cf2-9b94-cbc6073d8643)
而且会有乱码问题

**Comment by 1102asd** [comment]
![image](https://github.com/langgenius/dify/assets/52064676/c29099fe-1080-40e1-aee9-3b80699fdaed)
而且还会有乱码问题

**Comment by qianbaidu1266** [comment]
解决了吗，我也遇到这个问题了

**Comment by ZHQ98** [comment]
求问，我也遇到工作流封装成工具后重复返回问题
