### ISSUE TITLE
如何配置非流式调用！！！！

### ISSUE THREAD

**Issue by Owen-MS** [langgenius/dify#2978]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

如何配置非流式调用！！！！
class HMLargeLanguageModel(LargeLanguageModel):
 def _invoke(self, model: str, credentials: dict, 
                prompt_messages: list[PromptMessage], model_parameters: dict, 
                tools: list[PromptMessageTool] | None = None, stop: list[str] | None = None, 
                stream: bool = True, user: str | None = None) \
            -> LLMResult | Generator:
        return self._generate(model=model, credentials=credentials, prompt_messages=prompt_messages,
                                model_parameters=model_parameters, tools=tools, stop=stop, stream=stream, user=user)
默认的stream在哪里能配置为false

**Comment by Owen-MS** [comment]
我需要改的不是当前行代码，而是如何配置stream

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/4cf475680db459f985201678b156bb2439f248d2/api/core/model_runtime/model_providers/baichuan/llm/llm.py#L38

参考一下其他类型的 LLM
