### ISSUE TITLE
segments can save file？such as image,cavans...

### ISSUE THREAD

**Issue by xiaoqingrong** [langgenius/dify#2979]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

segments can save file？such as image,cavans，i want edit segment to save image or canvas

**Comment by crazywoola** [comment]
Nope. We have no plan for this feature.
