### ISSUE TITLE
stream如何配置为false

### ISSUE THREAD

**Issue by Owen-MS** [langgenius/dify#2980]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

在增加自定义供应商时，stream如何配置为false

**Comment by crazywoola** [comment]
你需要在什么地方关闭流？

**Comment by crazywoola** [comment]
还有，请使用英文提交 issue，并且格式化代码。

**Comment by Owen-MS** [comment]
好的， 下次会格式化提交。我新接入一个供应商，以及一个预定义模型，我的接口是一个非流式调用，所以想在初始化配置的时候关闭流
