### ISSUE TITLE
Spark V1.5 is not work

### ISSUE THREAD

**Issue by Kennytian** [langgenius/dify#2982]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. switch the model to Spark V1.5
2. ask any questions
3. output error message

### ✔️ Expected Behavior

outout the correct result

### ❌ Actual Behavior

![1](https://github.com/langgenius/dify/assets/2621619/ca0cb8dc-732d-4cfc-b6e0-b081b18d1bf2)

```
{
    "event": "error",
    "task_id": "9fab4f38-824c-4003-ad50-cbb74bdb03a2",
    "message_id": "5c174ba4-aa9c-4d75-8259-b6ba2f7139a1",
    "code": "completion_request_error",
    "status": 400,
    "message": "[spark] Error: [Spark] code: 400, error: Code: 10004, Error: SchemaCheckError:(16:00:49.554) '$.header.uid' length must be less or equal than 32; "
}
```

**Comment by crazywoola** [comment]
400 means there is something wrong with the params the api passed to the spark.
