### ISSUE TITLE
Indexing of PDF documents very slow

### ISSUE THREAD

**Issue by fabihoe** [langgenius/dify#2984]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I‘m running dify locally on a MacBook Pro 15“ from 2017 trough dockers. When indexing PDF files into the knowledge base, it takes hours to index a single file. In the dockers UI, I can see that I have 8 CPUs available but only seem to use between 60 and 140%. The application also has 12 GB of RAM of whom it uses about 1-2 GB. Do you have any idea for the reason of my issue? 

Thank you in advance for your help!

**Comment by crazywoola** [comment]
It depends on several things. How big is this file? 
- Your docker settings. 
- The embedding model api is slow
- File is too large

**Comment by crazywoola** [comment]
Then it's the problem with the api I think. You can tested with jina to see if this persists.

**Comment by fabihoe** [comment]
Thank you, that was indeed the problem. Now it is a lot faster.
