### ISSUE TITLE
workflow params max length limit increase

### ISSUE THREAD

**Issue by harryhan1989** [langgenius/dify#2985]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-preview-workflow.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/2442117/0b458698-9fc1-41bc-a074-34aa0d25720a)

### ✔️ Expected Behavior

1、add object field type
2、increate text field type length

### ❌ Actual Behavior

text field length limit 255

**Comment by crazywoola** [comment]
For features, please use feature template. If you are using text more than 255, then you need to use paragraph instead.
