### ISSUE TITLE
Dataset returns incorrect answer

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#2988]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

suppose I have a dataset with one line:
The password of our guest wifi is 88886666

and I added this dataset as a document, created an app which uses this dataset. Now when I ask my agent using Google Gemini:

```
guest wifi password
```

it returns

```
ok got it
```

I believe this is due to incorrect prompt message order. Currently, the dataset info will be appended to the end of the prompt_messages list, so the final promp is something like this:

0: {system general prompt}
1: guest wifi password
2.I am thinking about how to help you{"action": "dataset-xxx"}
3. The password of our guest wifi is 88886666

If I manually change this order into:

0: {system general prompt}
1.I am thinking about how to help you{"action": "dataset-xxx"}
2. The password of our guest wifi is 88886666
3: guest wifi password 

Gemini returns the correct answer.

I believe the user input message should always at the end.

And the info in dataset should play a role of 'assistant' instead of 'user' maybe? I have tested that if I change the role to assistant, the awnser from LLM is more consistent

### ✔️ Expected Behavior

returns the correct wifi password in my dataset

### ❌ Actual Behavior

returns 'ok I got it' as if I'm telling LLM some infomation instead of asking a question

**Comment by JohnJyong** [comment]
![image](https://github.com/langgenius/dify/assets/76649700/ccc0bce2-de23-47e7-bbe1-0cf4169d74e3)
you can try the expert mode to define your own prompt @lancemao
