### ISSUE TITLE
Workflow Issue in Self Host app

### ISSUE THREAD

**Issue by trongnichietsu** [langgenius/dify#2989]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

![image](https://github.com/langgenius/dify/assets/165017576/1b55fe06-34e1-4050-88da-5ada9e3f4a8a)

I have already put the context file in here, but I don't know why it just return an empty array.
Can anybody have a solution for this? Thank you!

**Comment by takatost** [comment]
Hey, could you please provide a screenshot of the execution result? It will help us pinpoint the issue.
