### ISSUE TITLE
How to config 'response_mode'?

### ISSUE THREAD

**Issue by XuZhichao1998** [langgenius/dify#2992]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

<img width="1600" alt="image" src="https://github.com/langgenius/dify/assets/34597955/27200ce0-58cb-478b-b650-51eea7929bbf">
生成回复时，调用chat-message接口，body参数里的response_mode参数是哪里来的，如何配置？
<img width="990" alt="image" src="https://github.com/langgenius/dify/assets/34597955/3fc4bd4d-7b2f-4000-bc0c-8453b845de02">

**Comment by crazywoola** [comment]
Yes, we do not offer blocking mode in console itself. Blocking mode is only available for the API.
