### ISSUE TITLE
How to integrate fine-tuned Tongyi models into DIFY

### ISSUE THREAD

**Issue by LLMR-boringtao** [langgenius/dify#2994]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I fine tuned both GPT 3.5 Turbo and Tongyi Turbo. 
For GPT, there is an option called "Add models" to add customised GPT models, but TongYi doesn't have this option. 
How can I add my customised Tongyi Models?

Thanks!

**Comment by takatost** [comment]
If the model supports the OpenAI API standard, you can try adding the model to OpenAI-API-compatible provider.
