### ISSUE TITLE
Unnecessary 'Action:' text when using dataset

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#2995]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When using dataset (with Gemini), it returns unnecessary 'Action:' text, please see attachment screenshot
![Screenshot 2024-03-27 020721](https://github.com/langgenius/dify/assets/5020396/77aa93b7-03e6-49af-bedb-4bdbf4e1a60d)

I think this is because we have 'Action:' in our prompt so LLM is returning it as per our request. Not sure if we can simply remove it from prompt or strip it after we get the response

### ✔️ Expected Behavior

don't show this 'Action:' text because this is an internal information, user won't care

### ❌ Actual Behavior

Unnecessary 'Action:' text is shown for each step

**Comment by Yeuoly** [comment]
You can use Basic Assistant Instead now

**Comment by lancemao** [comment]
This could be yet another issue or maybe a question

I can't use Basic Assistant, I need to use assistant agent since later I want to add function call. I found *function call* and *dataset* are exclusive, I can only use one of them, not both of them at the same time, as the code in assistant_app_runner.py

```python
        if agent_entity.strategy == AgentEntity.Strategy.CHAIN_OF_THOUGHT:
            assistant_cot_runner = AssistantCotApplicationRunner()
        elif agent_entity.strategy == AgentEntity.Strategy.FUNCTION_CALLING:
            assistant_fc_runner = AssistantFunctionCallApplicationRunner()
```

looks like they are exclusive?

Our requirement is a single super agent who can answer FAQ questions and call company API at the same time

**Comment by Yash-1511** [comment]
Hey @lancemao, you might find GPT models useful for your needs, particularly GPT-4, which excels at function calling. Improving your prompts or clarifying how to utilize these tools could enhance your outcomes. In terms of your requirements, an agent equipped with GPT-4 can handle FAQ queries and API calls simultaneously, offering more effective results.

You can use Mistral Large also.

**Comment by mr-v-v-v** [comment]
Hi, I think it's good idea for feature.
I also need to customize prompt for ReAct Agent.
It's simple prompt here,  and it's give extra not needed replies.
