### ISSUE TITLE
Dataset referencing is not working as expected

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#2996]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I didn't add *Show dataset reference* in my assistant setting, however, in my conversation answer, it still shows this 'reference' dropdown, please see attached screenshot

![Screenshot 2024-03-27 022334](https://github.com/langgenius/dify/assets/5020396/f65695e8-a6c6-4a86-b20d-340ee0a4609c)

One more thing, as you can see in the screenshot, the name of the dataset is not matching. My filename is '公司知识库.txt', but it says '知识库'. This is another issue to investigate.

### ✔️ Expected Behavior

should show dataset reference when I add reference tool
should hide when I didn't

### ❌ Actual Behavior

always shows

**Comment by Yeuoly** [comment]
Smart Assistant considers dataset as a tool, that's why you can see a tool invoke referencing.

**Comment by takatost** [comment]
Suggest optimizing the description of the knowledge base, so that Agents can use the description of the knowledge base as a reference to decide whether to use it or not.
