### ISSUE TITLE
Evem has not start its show exdeeded

### ISSUE THREAD

**Issue by cantoneseslang** [langgenius/dify#2997]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I m the free paln users,evem have not to start for using but when I put the gpt api its show[Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}]ist could not to start normally for start, hope its fix and start for the trail Thx

**Comment by crazywoola** [comment]
Please refer https://platform.openai.com/docs/guides/error-codes/api-errors, This error is raised by OpenAI api endpoint. Please check the billing there.

**Comment by cantoneseslang** [comment]
I think its not this issue cause the problem,I m using other services cursor for coding,and so on,dont show this error
Its could check the limit not exdeed of my limitation now
Thx
￼
