### ISSUE TITLE
how to use Citations in APIs

### ISSUE THREAD

**Issue by wwwzzz17** [langgenius/dify#2998]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

how to use Citations in APIs

**Comment by wwwzzz17** [comment]
<img width="818" alt="image" src="https://github.com/langgenius/dify/assets/37200340/13b02f3c-c801-4fd4-bcfd-e70d454beacb">

**Comment by wwwzzz17** [comment]
> Hey @wwwzzz17 ,
> 
> You can use citations and attributions using metadata from the api.
> 
> here is the guide:
> 
> ```shell
> ChatCompletionResponse
> Returns the complete App result, Content-Type is application/json.
> 
> message_id (string) Unique message ID
> conversation_id (string) Conversation ID
> mode (string) App mode, fixed as chat
> answer (string) Complete response content
> metadata (object) Metadata
>    -usage (Usage) Model usage information
>    -retriever_resources (array[RetrieverResource]) Citation and Attribution List
> created_at (int) Message creation timestamp, e.g., 1705395332
> ```

That's great! Thanks a lot. 
There is another question, how can I add doc's metadata for docs in datasets? So that I can get all I want from the API response `retriever_resources`.

**Comment by Yash-1511** [comment]
![Screenshot from 2024-03-27 13-00-38](https://github.com/langgenius/dify/assets/82636823/8735150f-43d7-4cf0-936e-9fee5bcaa291)

You can add docs metadata in dataset section. In Dataset select knowledge, after you can select document that you want to add metadata. here you can see above section.

**Comment by wwwzzz17** [comment]
> ![Screenshot from 2024-03-27 13-00-38](https://private-user-images.githubusercontent.com/82636823/317170815-8735150f-43d7-4cf0-936e-9fee5bcaa291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjYwMzgsIm5iZiI6MTcxMTUyNTczOCwicGF0aCI6Ii84MjYzNjgyMy8zMTcxNzA4MTUtODczNTE1MGYtNDNkNy00Y2YwLTkzNmUtOWZlZTViY2FhMjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA3NDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YTUwZDYyZjQ0OWU4ZTVmZTc2YTcyYmYyODBlZjQyMzdlYzlkN2E4YjlhYWZkNWY0YmRmNDFhMTg2NDViNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EpKu_oKgLytxy7hf-hakEbzoR8Q4866IR-8LuNf-M0Q)
> 
> You can add docs metadata in dataset section. In Dataset select knowledge, after you can select document that you want to add metadata. here you can see above section.

that's helpful! thanks😁

**Comment by Yash-1511** [comment]
> > ![Screenshot from 2024-03-27 13-00-38](https://private-user-images.githubusercontent.com/82636823/317170815-8735150f-43d7-4cf0-936e-9fee5bcaa291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjYwMzgsIm5iZiI6MTcxMTUyNTczOCwicGF0aCI6Ii84MjYzNjgyMy8zMTcxNzA4MTUtODczNTE1MGYtNDNkNy00Y2YwLTkzNmUtOWZlZTViY2FhMjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA3NDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YTUwZDYyZjQ0OWU4ZTVmZTc2YTcyYmYyODBlZjQyMzdlYzlkN2E4YjlhYWZkNWY0YmRmNDFhMTg2NDViNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EpKu_oKgLytxy7hf-hakEbzoR8Q4866IR-8LuNf-M0Q)
> > You can add docs metadata in dataset section. In Dataset select knowledge, after you can select document that you want to add metadata. here you can see above section.
> 
> that's helpful! thanks😁

Your Welcome!
