### ISSUE TITLE
Openai Token校验不通过

### ISSUE THREAD

**Issue by charli117** [langgenius/dify#30]
在添加Token提示校验不通过，本地测试openai的apikey是正常的
![image](https://github.com/langgenius/dify/assets/24435100/1bf3014c-bf01-4947-868c-c7ac2d3ed238)

**Comment by takatost** [comment]
可以使用 docker logs -n 500 docker-api-1 查看下有没有报错日志，猜测和网络有关，容器可能没走代理

**Comment by charli117** [comment]
确认了，果然是网络的问题，国际专线引流策略没覆盖到，已经解决了。期待Azure OpenAI尽快上线呀

**Comment by takatost** [comment]
好的，azure 对接在设计了
