### ISSUE TITLE
如何接入三方账号登录

### ISSUE THREAD

**Issue by hjxtclm** [langgenius/dify#3004]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

如何接入三方账号登录

**Comment by crazywoola** [comment]
请联系 business@dify.ai，该功能需要商业化协议的许可。
