### ISSUE TITLE
build a new tool to show the base64 data for image/png

### ISSUE THREAD

**Issue by xspring14** [langgenius/dify#3008]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

how to implement a tool for when request a http serve which returns the base64 data for a image/png, then show the image in the dialog

### ✔️ Expected Behavior

the tool created by the openai/swagger rule can handle the http response to decode the base64 data and show the image in the dialog, not just show  the response json in the dialog

**Comment by crazywoola** [comment]
This is a question not a bug, please use the right template to fire an report.
