### ISSUE TITLE
workflow ability

### ISSUE THREAD

**Issue by Frank-Zeng** [langgenius/dify#3009]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

![img_v3_029b_9a90885f-b7a8-404a-99bc-f25006264acg](https://github.com/langgenius/dify/assets/17022654/bfebd4b7-0ec1-44ef-b7ef-72546161c447)
I found some news about to introduce the LLMops workflow ability like bytedance coze product, but after I deploy the dify in local, seems not found the LLMops workflow function, are these function only  include in Enterprise Edition version?

**Comment by takatost** [comment]
Hey, the current workflow version is still in preview and has not been merged into the main branch. If you want to try it out, you can check out this release.

https://github.com/langgenius/dify/releases/tag/0.6.0-preview-workflow.1
