### ISSUE TITLE
是否可以并行处理embedding过程，对于上千万条数据处理，目前的速度太慢了

### ISSUE THREAD

**Issue by xinggonglie** [langgenius/dify#3010]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

我目前要处理5000万条数据，添加知识库，测试发现1万条需要3分钟，这个速度太慢了

### 2. Describe the feature you'd like to see

并行处理向量化过程

### 3. How will this feature improve your workflow or experience?

是的，极大的提升了效率

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
#1542
