### ISSUE TITLE
Is it possible to parallelize the embedding process for processing millions of data points? The current speed is too slow.

### ISSUE THREAD

**Issue by xinggonglie** [langgenius/dify#3011]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am currently dealing with 50 million records, adding to a knowledge base. Testing has shown that processing 10,000 records takes 3 minutes, which is too slow.

### 2. Describe the feature you'd like to see

Parallel processing of the vectorization process

### 3. How will this feature improve your workflow or experience?

it greatly improved efficiency.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by takatost** [comment]
In theory, it's feasible. We can add it to our roadmap. @VincePotato @JohnJyong

**Comment by JohnJyong** [comment]
it has supported in this PR : https://github.com/langgenius/dify/pull/3016
