### ISSUE TITLE
dify API 扩展发生错误，根据API扩展文档中实现了后端接口收到“ping“返回”pong“，但是仍然connection error: {'data': {'result': 'pong'}, 'requestId': '2072fc08-72212994'}

### ISSUE THREAD

**Issue by deepblue-star** [langgenius/dify#3014]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

我在使用https://docs.dify.ai/v/zh-hans/guides/application-design/extension/api_based_extension

这个网址中的构建自定义api扩展的指导中，应该是说新增dify api扩展时，dify会发送一个post请求，但是网页端拦截这个请求，发现请求格式和文档中规范不一致，请问如何看到最终发给我后端接口的post请求的真正形式呢，以便我写后端代码来处理。

现在就是新增api扩展功能那边，保存时会在前端页面跳出错误：connection error: {'data': {'result': 'pong'}, 'requestId': '2072fc08-72212994'}，但是我用postman发送post请求，并将请求体里的point参数设置为”ping“时，我的后端接口能正常返回响应，响应体中result为”pong”

**Comment by deepblue-star** [comment]
对了，前段浏览器拦截的请求里，发现请求的url并不是我设置的api end point，而是http://xxx.xxx.xxx.xxx/console/api/api-based-extension，其中xxx.xxx.xxx.xxx是我部署dify的机器的ip

**Comment by crazywoola** [comment]
请使用 英文提交 Issue #1542
