### ISSUE TITLE
Workflow API call, in streaming mode, expects the presence of `event_data["data"]["execution_metadata"]` in the message with event 'workflow_finished'

### ISSUE THREAD

**Issue by chuanzhubin-aiopx** [langgenius/dify#3018]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-preview-workflow.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```python
            elif event_data.get("event") == "workflow_finished":
                # status (string) 执行状态 running / succeeded / failed / stopped
                if event_data["data"]["status"] == "succeeded":
                    print(">|", end='\n')
                    print(event_data["data"]["outputs"]['text'])
                    print(event_data["data"]["execution_metadata"])
```
Expected execution_metadata present, but not found

### ✔️ Expected Behavior

Workflow API call, in streaming mode, expects the presence of `event_data["data"]["execution_metadata"]` in the message with event 'workflow_finished'

>execution_metadata (json) 元数据
>total_tokens (int) optional 总使用 tokens
>total_price (decimal) optional 总费用
>currency (string) optional 货币，如 USD / RMB

### ❌ Actual Behavior

Field missing

**Comment by chuanzhubin** [comment]
After reviewing the API documentation again, I found that in the case where event_data.get("event") == "workflow_finished", the event_data["data"]["execution_metadata"] is not defined. Instead, there is a different structure :
>elapsed_time (float) Optional 耗时(s)
>total_tokens (int) Optional 总使用 tokens
