### ISSUE TITLE
新安装系统无法登录界面 错误401/403

### ISSUE THREAD

**Issue by flyice8** [langgenius/dify#3023]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

本地部署，新安装，Ubuntu22.04，填写邮箱和用户名密码后提交提示创建用户成功。
登录界面时候，登录用户名又返回到注册新用户界面，具体设置请看附件
![屏幕截图 2024-03-28 201515](https://github.com/langgenius/dify/assets/164740348/c5cf6645-5e5c-4feb-9aca-94b647e5c6f8)
![屏幕截图 2024-03-28 201547](https://github.com/langgenius/dify/assets/164740348/3b7837c9-7914-4b49-b7ec-c71a25318e85)
![屏幕截图 2024-03-28 201651](https://github.com/langgenius/dify/assets/164740348/3ac22bc3-3cdb-4761-987b-91ca600ab8e8)

**Comment by flyice8** [comment]
改过了仍然无法解决问题，

**Comment by crazywoola** [comment]
Close due to #1542
