### ISSUE TITLE
使用Docker安装报告如下错误：yaml: line 4: did not find expected key   请参考附件

### ISSUE THREAD

**Issue by flyice8** [langgenius/dify#3027]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

使用Docker安装报告如下错误：yaml: line 4: did not find expected key   请参考附件
![1111](https://github.com/langgenius/dify/assets/164740348/040e75b7-c931-4c30-8dd8-90ca64889484)

**Comment by crazywoola** [comment]
Close due to #1542
