### ISSUE TITLE
When a markdown file contains image links, the segmentation cannot be recognized.

### ISSUE THREAD

**Issue by luozb** [langgenius/dify#3029]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a new knowledge base
2. Upload a markdown file that contains image links, but it can't recognize the image links and the content after them.

### ✔️ Expected Behavior

Keep the image links in separate paragraphs.

**Comment by crazywoola** [comment]
You can use custom segment symbols to split texts not let split them automatically.
