### ISSUE TITLE
在使用Gemini Pro模型對話時經常會出現 回復產出一直重複的錯誤

### ISSUE THREAD

**Issue by JuHuaEr** [langgenius/dify#3030]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.5.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

復現方法因爲只需要使用Gemini對話數次即可復現，參數為Version 0.5.8默認參數。

### ✔️ Expected Behavior

正常情況下回復不應該有無限重複部分段落回答的情況。

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/71249486/9ad603ce-9958-456b-9416-a307cbf4057c)

![image](https://github.com/langgenius/dify/assets/71249486/db86b7b9-ae02-4951-84ca-0c120d74d125)

**Comment by crazywoola** [comment]
Close due to #1542
