### ISSUE TITLE
create an empty knowledge and empty files, vector collection not created.

### ISSUE THREAD

**Issue by liuzhenghua** [langgenius/dify#3032]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

bugs occured after the following steps:
1. create an empty knowledge.
2. add an empty file in web page or using create_by_text API， the text remains empty
```
{
    "name": "demo.txt",
    "text": "",
    "indexing_technique": "high_quality",
    "process_rule": {
        "mode": "automatic"
    }
}
```
3. add chunk in web page or using add segments api

### ✔️ Expected Behavior

the segment should be enabled.
![image](https://github.com/langgenius/dify/assets/11787325/6c0ebf5e-88f4-46cf-8adf-b847c6843672)

### ❌ Actual Behavior

cause of the collection was not created when you upload an empty file, the chunk you created can't be successs.
![image](https://github.com/langgenius/dify/assets/11787325/d010307f-fb73-44d5-9598-d4c317c56a7e)

**Comment by liuzhenghua** [comment]
由于创建空文件时，没有创建collection，下次往这个文档新建chunk的时候，无法往向量库写入数据，导致报错：
"Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field \"Vector_index_3b5a7bd1_2cfb_4ae2_a89c_019472e90033_Node\" on type \"GetObjectsObj\". Did you mean \"Vector_index_6038789c_2c73_4190_809c_c170be45bb47_Node\"?', 'path': None}]"

**Comment by JohnJyong** [comment]
it has fix by below pr : https://github.com/langgenius/dify/pull/3021 , thanks for your feedback @liuzhenghua
