### ISSUE TITLE
FORGET PASSWORD!!!HELPPPPP!

### ISSUE THREAD

**Issue by JachinLan** [langgenius/dify#3035]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

![image](https://github.com/langgenius/dify/assets/154945381/371fc9e0-def2-4abf-b86c-39b3d1a09a9d)

**Comment by crazywoola** [comment]
If you use self-hosted version. Please read our docs https://docs.dify.ai/ to reset password.
