### ISSUE TITLE
When using sqlcoder-7b in dify, how to configure the database connection information?

### ISSUE THREAD

**Issue by daocaorenzzl** [langgenius/dify#3044]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I have installed Ollama locally and pulled large models such as Gemma and Sqlcoder. When I use Sqlcoder to implement text2sql, I can't find where I can configure the database connection information. Can someone help guide me on where I can configure it?

### 2. Describe the feature you'd like to see

![image](https://github.com/langgenius/dify/assets/20551179/25dda500-84df-4aaf-8173-38f5a5240974)
There is no place in the knowledge base to configure the database address, and the prompts are not appropriate.

### 3. How will this feature improve your workflow or experience?

We need to do data questions and answers based on documents and business tables in the database. Now we can test based on documents, but we haven't found a way to do so in the database documents in Dify.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yash-1511** [comment]
Hey @daocaorenzzl,

At the moment, Dify does not have the capability to incorporate databases as part of its knowledge base. It allows connections through Notion, or you have the option to upload your documents in various formats such as CSV, Excel, PDF, Docs, EML, among others. Unfortunately, integrating a database directly as a source of knowledge is not supported at this time.
