### ISSUE TITLE
What happened to the explore tab?

### ISSUE THREAD

**Issue by alfi4000** [langgenius/dify#3048]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Just install it locally tr go to the cloud the homepage of dify:  https://cloud.dify.ai/explore/apps?category=All%20Categories

<img width="1860" alt="Bildschirmfoto 2024-03-30 um 12 15 32" src="https://github.com/langgenius/dify/assets/149228038/41cadfd1-5ea0-40bc-b025-1bbf5a37d92f">

### ✔️ Expected Behavior

To find templates on the explore tab!

### ❌ Actual Behavior

There are no templates on the explore tab only white! it just shows on the left my workspaces but no templates!

**Comment by alfi4000** [comment]
<img width="1861" alt="Bildschirmfoto 2024-03-30 um 12 16 53" src="https://github.com/langgenius/dify/assets/149228038/c1851d06-1ca1-43c5-9b7a-98cd96feb5fa">
Same on self hosted docker!

**Comment by alfi4000** [comment]
<img width="1861" alt="Bildschirmfoto 2024-03-30 um 12 16 53" src="https://github.com/langgenius/dify/assets/149228038/e7899e92-6e68-42ae-8e0c-d6cf8a7cee7d">
same on self hosted docker!

**Comment by alfi4000** [comment]
in the cloud version do I need a special tier? I have the free plan that's mighty the issue!?

**Comment by Yash-1511** [comment]
Hey @alfi4000 ,

I can see templates in cloud version. in self hosted version you can not see any templates because it is sass feature. or may be in later version or in workflow release you will be able to see all templates in self hosted version that are in cloud versiion.

**Comment by alfi4000** [comment]
ok
