### ISSUE TITLE
Fakenamedeployment is not removed by modelname for Azure

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#3050]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When adding Azure models locally, it does not use the model name as the label, as it does on cloud instances.
![CleanShot 2024-03-30 at 23 36 18@2x](https://github.com/langgenius/dify/assets/119136210/638779e6-e41e-4b80-8e45-f7bea9432975)

it only says "fake-deployment-name-label". Added in the same way on both local source and on cloud. Cloud works, not local.

### ✔️ Expected Behavior

Model name is set as the label

### ❌ Actual Behavior

fake-deployment-name-label is set regardless of the modelname.

**Comment by Yeuoly** [comment]
how did you add the model? as usual, label should be the same as the model's name
