### ISSUE TITLE
It is not possible to upload images to AI in the smart assistant mode.

### ISSUE THREAD

**Issue by Dawdler-G** [langgenius/dify#3052]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![BUG2](https://github.com/langgenius/dify/assets/84848905/46cee706-4767-40f8-a6b5-07cff8e62227)
![BUG1](https://github.com/langgenius/dify/assets/84848905/52e353e0-e699-4a7f-84e0-91d48bace040)
It is not possible to upload images to AI in the smart assistant mode.

### ✔️ Expected Behavior

The smart assistant mode allows uploading images to AI.
![BUG1](https://github.com/langgenius/dify/assets/84848905/263914d9-d114-4aa8-9d32-90e04f66231e)

### ❌ Actual Behavior

It is not possible to upload images to AI in the smart assistant mode.
![BUG2](https://github.com/langgenius/dify/assets/84848905/499e6c3c-f99f-4033-af79-adb18e3fd0f8)

**Comment by crazywoola** [comment]
The vision capability is not supported in smart assistant mode at this moment.

**Comment by chaozZLF** [comment]
> 目前智能助手模式不支持视觉功能。

请问Dify的API：/files/upload能否支持多图片上传呢，如果支持该怎么使用呢
