### ISSUE TITLE
应用概览-分析-所有时间，页面报错，右上角出现系统错误，提示format

### ISSUE THREAD

**Issue by panfeng1900** [langgenius/dify#306]
Dify version: Cloud

## Steps To Reproduce
![0853cfbd81d83e5755a1b8b7a2c2604](https://github.com/langgenius/dify/assets/4971221/256abe05-a6ab-40cf-8dad-fcb7a98a4d78)

![7c989dc9e352b8c7d9f2477b8b0c2fc](https://github.com/langgenius/dify/assets/4971221/f61802ca-9026-4b09-93a1-3d35c565adbe)

应用概览-分析-所有时间，页面报错，右上角出现系统错误，提示format

**Comment by takatost** [comment]
https://cloud.dify.ai/console/api/apps/xxxxxxxx/statistics/daily-conversations?start=**Invalid%20Date**&end=2023-06-06%2017%3A27

Looks like the front-end passed the wrong params. Thx for the feedback, we'll fix it asap.
