### ISSUE TITLE
Audio to Text is not working locally

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#3060]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I added ASR in my app which uses Gemini Pro as LLM, when I tried to start audio recording (already granted permission in my browser), I got exception in app\components\base\voice-input\index.tsx

![Screenshot 2024-04-01 063507](https://github.com/langgenius/dify/assets/5020396/3cfb7c10-e568-4977-97b6-020b1a806dd2)

in console, I got 

![Screenshot 2024-04-01 063546](https://github.com/langgenius/dify/assets/5020396/076d6934-2c5b-418c-a459-1bf4c7ae5bd9)

Looks like js-audio-recorder is outdated and maintenance is ceased. 

Dify cloud works fine. So I have no idea what went wrong, please help me

**Comment by lancemao** [comment]
I guess this is due to React debug mode useEffect will be called twice. What's the suggested work-around?

**Comment by crazywoola** [comment]
@zxhlyh Please take a look at this.
