### ISSUE TITLE
Cannot use the same tool multiple times, prompt will fall into a dead loop

### ISSUE THREAD

**Issue by winstonsias** [langgenius/dify#3061]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

<=0.5.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

prompt: Directly use tools to generate images without answering useless content
![image](https://github.com/langgenius/dify/assets/2811245/266a1944-6635-4f7a-887d-be21543bc5b9)

### ✔️ Expected Behavior

Can call the tool normally every time to reply.

Or tell me how to set prompt to call the tool multiple times

### ❌ Actual Behavior

Only replied once

**Comment by deepblue-star** [comment]
是不是调用完一个工具就停住了不回复了，我现在用的是通义千问的模型，请问下你用的是什么模型呢，不知道是不是模型的问题

**Comment by winstonsias** [comment]
我也用的千问，各种prompt都试了也不行，感觉是调用链里面封装的prompt一直在重复。我提的issue也有截图。必须重新再开一个新会话。



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 1, 2024 18:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [langgenius/dify] Cannot use the same tool multiple times, promptwill fall into a dead loop (Issue #3061)




 
是不是调用完一个工具就停住了不回复了，我现在用的是通义千问的模型，请问下你用的是什么模型呢，不知道是不是模型的问题

**Comment by winstonsias** [comment]
![image](https://github.com/langgenius/dify/assets/2811245/020d9a25-2b9b-4493-87ed-a0cd067d27b0)
正常的action是直接再次调用sd，但是截图的地方看着是把thought也带进去了，  后面再提问 也同样的回复内容

**Comment by deepblue-star** [comment]
> ![image](https://private-user-images.githubusercontent.com/2811245/318405105-020d9a25-2b9b-4493-87ed-a0cd067d27b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Njg4NTMsIm5iZiI6MTcxMTk2ODU1MywicGF0aCI6Ii8yODExMjQ1LzMxODQwNTEwNS0wMjBkOWEyNS0yYjliLTQ0OTMtODdlZC1hMGNkMDY3ZDI3YjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTA0OTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzMyMjk1NDUxYzM5ODdmN2RjMDAyNTRhYjNmOTIxNzFlZWE4MzMzYzBiYzc5NDU1NTdlZTNkNzdiYjRmMzM5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GtnSRJRgsi0b3-6iXmTJ4RrD51R7SxvEgJQ-2taynlY) 正常的action是直接再次调用sd，但是截图的地方看着是把thought也带进去了， 后面再提问 也同样的回复内容

我刚刚换了gpt3.5，表现比千问好很多，之前千问连续调用多个工具会卡住，现在基本不会了

**Comment by Yeuoly** [comment]
I'm considering refactoring the ReACT Agent mode, as it always results a bad response, for now, use a model supports `Function Calling` is a better choice.

**Comment by mr-v-v-v** [comment]
When it is possible to customize logic of ReACT Agent.
at least change prompt?
For now it's required to use gpt-4 always, because there are no function calling for open-source models.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)

**Comment by czslxk** [comment]
I am using version 0.6.10 but has the same problem. I make a very simple Agent with only one tool, Stable Diffusion WebUI, but it cannot be used twice. But when I didn't use SD, it also had the same problem. I think there should be some problems about the Agent configuration. Here I have some screenshoots.
![image](https://github.com/langgenius/dify/assets/57351570/013f51a4-2962-4794-b20c-404e86d92020)
![image](https://github.com/langgenius/dify/assets/57351570/837c8d10-fde3-4851-b0f4-b3ac16f6a2f3)
