### ISSUE TITLE
The DIFY+Xinference architecture, through API invocation, does not provide an exception prompt when the GPU memory overflows.

### ISSUE THREAD

**Issue by PolarPeak** [langgenius/dify#3062]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="477" alt="企业微信截图_17119554973526" src="https://github.com/langgenius/dify/assets/44831329/3c719f7e-a6ce-4d27-98dc-2b1c633cd61c">
After the GPU memory overflows, the DIFU interface returns without exceptions.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
