### ISSUE TITLE
How to open the interface documentation for the console API

### ISSUE THREAD

**Issue by Air-duct** [langgenius/dify#3064]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I need to call the interface for creating the app in other applications, but I couldn't find the relevant interface documentation

**Comment by Air-duct** [comment]
@dosubot Thank you for your response, but it's not what I expected.
The document in the response explains how to call the already created app for dialogue.
What I want to know is how to open the interface document for creating an app. I need to call the creation interface in a third-party program to create a new app application

**Comment by crazywoola** [comment]
We do not provide api for creating applications.  You can read the source code written in blueprints in `dify/api/controllers/console/app` this folder.
