### ISSUE TITLE
The API service seems to have started normally, but cannot be accessed.

### ISSUE THREAD

**Issue by Dawdler-G** [langgenius/dify#3068]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/84848905/9b64a182-fbeb-425c-b055-a90de689805b)
![image](https://github.com/langgenius/dify/assets/84848905/f8a20900-9475-494f-97a0-5349283c11c0)
The API service seems to have started normally, but there is no response when accessing it either on the local machine or on another device.

This bug has been tormenting me all day. I have reinstalled it 7 times and tried various methods, but still cannot solve it.

### ✔️ Expected Behavior

![image](https://github.com/langgenius/dify/assets/84848905/4e5249af-81b6-4a2b-abfe-41780282d244)
API service started normally

### ❌ Actual Behavior

The API service seems to have started normally, but there is no response when accessing it either on the local machine or on another device.

**Comment by crazywoola** [comment]
This is a general question regarding Python programming basics. 
There is no endpoint exists on ` localhost:5001/` Please checkout the blueprint configuration in these files 👇
- https://github.com/langgenius/dify/blob/9f637ead3890ad07e6dba64d45424b5820817ae7/api/controllers/console/__init__.py#L4
- https://github.com/langgenius/dify/blob/1a6ad05a239ebba3678dfe817866e9630b6ad43b/api/controllers/service_api/__init__.py#L5
- https://github.com/langgenius/dify/blob/cc9e74123c65510d384756bb0539787cd9ef92cc/api/controllers/web/__init__.py#L5

Also you can start the web application to see it works.
