### ISSUE TITLE
Microphone not authorised

### ISSUE THREAD

**Issue by andsty** [langgenius/dify#3070]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When i enable speech to text in my chatbot app i get error microphone not authorised when i am pressing the microphone next to the chat box

### ✔️ Expected Behavior

Microphone to be activated

### ❌ Actual Behavior

I get error microphone no authorised. I have tested it with dify cloud and is working

**Comment by crazywoola** [comment]
Please check your web browser's setting.  (Chrome, Safari) :) Or you can google it how to change those settings.

**Comment by legaltextai** [comment]
chrome is dependent on the site requesting permission
