### ISSUE TITLE
SSO authentication for private WebApp

### ISSUE THREAD

**Issue by phamduyphuong251** [langgenius/dify#3074]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Hi, I want to ask about SSO authentication for my private WebApp

### 2. Describe the feature you'd like to see

Well, the chatbot needs to sign in because of private documentation. I want my users when sign in my WebApp, the Chatbot will have their information to log it.

### 3. How will this feature improve your workflow or experience?

My boss need it :(

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by phamduyphuong251** [comment]
I have one question: I want to embed a chatbot in my Web app by iframe. Is it possible for a chatbot to detect the user?

**Comment by crazywoola** [comment]
Hello there, the SSO function requires business license. Please contact business@dify.ai
