### ISSUE TITLE
Run failed: Node DuckDuckGo search run failed: Failed to invoke tool: local variable 'snippets' referenced before assignment

### ISSUE THREAD

**Issue by QIN2DIM** [langgenius/dify#3076]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

langgenius/dify-api:0.6.0-preview-workflow.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![图片](https://github.com/langgenius/dify/assets/62018067/dac34d5c-e6a8-4e9c-9c06-103dbccb8f34)

### ✔️ Expected Behavior

```python
class DuckDuckGoSearchResult:
    title: str
    href: str
    body: str


# Expected schema
class DuckDuckGoSearchResponse:
    results: List[DuckDuckGoSearchResult]
```

### ❌ Actual Behavior

duckduckgo-search 组件漏洞，ddgs.AnyMethod 返回空结果。

```python
import asyncio
from asyncio import WindowsSelectorEventLoopPolicy

asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())

# v5.1.0
from duckduckgo_search import DDGS


async def main():
    with DDGS(proxies="http://127.0.0.1:2081") as ddgs:
        print(ddgs.text("Chinese", max_results=1))


if __name__ == '__main__':
    asyncio.run(main())

```

**Comment by QIN2DIM** [comment]
相似问题：
- https://github.com/langgenius/dify/issues/3049

**Comment by QIN2DIM** [comment]
相对致命的漏洞，会引发 `Ratelimit` 以及 `keywords Could not extract vqd` 等一连串  **DuckDuckGoSearchException**。

**Comment by world4jason** [comment]
same issue occurs again, 
upgrade from 5.2.2 to 6.1.0 solve the issue

**Comment by iiidle** [comment]
> same issue occurs again, upgrade from 5.2.2 to 6.1.0 solve the issue

upgrade the duckduckgo in the container api-1 and worker-1, solve! Thank you!
