### ISSUE TITLE
Why do we always trigger many requests every time we focus on the page ?

### ISSUE THREAD

**Issue by Mxtzz** [langgenius/dify#3084]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Open any page
2. Blur the page
3. Focus the page
4. See the network in browser's console

### ✔️ Expected Behavior

The network page of console is very refreshing

### ❌ Actual Behavior

There are many requests.

The reason for the problem is the configuration of SWR: web/app/components/swr-initor.tsx, add revalidateOnFocus=false is better.

Is it a bug or feat?

**Comment by jianchaozhuang** [comment]
不管是本地部署的社区版还是官方的云版，都有这个问题。 而且是任意页面的切换都会触发很多请求。

**Comment by Mxtzz** [comment]
> I think we didn't noticed this scenario at the first place, It would be great if you could submit a PR for this. @Mxtzz

https://github.com/langgenius/dify/pull/3129

Here you are.
