### ISSUE TITLE
Where is the vector data from the uploaded PDF conversion stored locally?

### ISSUE THREAD

**Issue by wangshuai-wuhan** [langgenius/dify#3086]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

Where is the vector data from the uploaded PDF conversion stored locally? I want to find it and upload it to the cloud vector library myself

**Comment by wangshuai-wuhan** [comment]
@dosubot  i am using  wind11  ，put dify in docker .i jut upload on the web of  local defy

**Comment by crazywoola** [comment]
Please read the documents regarding the vector database on their own site. If you are using qdrant, please head to https://qdrant.tech/, etc.
