### ISSUE TITLE
Reduce the DB query

### ISSUE THREAD

**Issue by realjustinwu** [langgenius/dify#3088]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When make a requst to to v1/completion-messages, it will read/write DB 31 times,
<img width="708" alt="image" src="https://github.com/langgenius/dify/assets/3467850/90846506-13b4-491e-8fe5-de0685d7740c">

### 2. Describe the feature you'd like to see

The api_tokens, end_user, app, app_model_configs, data can be cached to redis to reduce DB operations.

### 3. How will this feature improve your workflow or experience?

.

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by realjustinwu** [comment]
Has anyone conducted a stress test on dify? I have a mock response from openai that delays for 5 seconds before returning data, and the QPS is only about 10, mainly because the DB operations are too time-consuming. I'm not sure if my results are correct.

**Comment by realjustinwu** [comment]
Also, add a chart of the number of database queries by the assistant.
With a plugin: Wikipedia.
Question: 'When were the Beijing Olympics held?'

![POST-v1-chat-messages-Transactions-lap-local-test-Services-APM-Observability-Elastic (1)](https://github.com/langgenius/dify/assets/3467850/71d5e11e-5e23-47d7-adb4-b5f28d7c6dec)

**Comment by VoVAllen** [comment]
How did you generate those traces?

**Comment by realjustinwu** [comment]
> How did you generate those traces?

Use elastic APM https://www.elastic.co/guide/en/apm/agent/python/current/flask-support.html
