### ISSUE TITLE
Where can I find workflow and AI Agent funtions as showed on the offical website

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3093]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

![image](https://github.com/langgenius/dify/assets/12423206/21397b03-fd82-4f99-82d8-3f7debd3a24e)
![image](https://github.com/langgenius/dify/assets/12423206/1bb0ced6-780f-429e-b733-43823f3cc318)

The two function showed aboved I cannot find in the self host version and SaaS version.

**Comment by aute** [comment]
You can refer to that： https://github.com/langgenius/dify/releases/tag/0.6.0-preview-workflow.1

**Comment by lx1054331851** [comment]
thank you for your reply!
