### ISSUE TITLE
If a Directed Cyclic Graph is configured within a workflow, it can cause the workflow to crash.

### ISSUE THREAD

**Issue by aute** [langgenius/dify#3097]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I can configure a Directed Cyclic Graph in the workflow.
<img width="1490" alt="截屏2024-04-03 15 51 29" src="https://github.com/langgenius/dify/assets/17873165/af9b12f8-415a-4a9a-935a-8712a7d81089">

But it won't function properly and will cause the page to crash.
<img width="1489" alt="截屏2024-04-03 15 58 00" src="https://github.com/langgenius/dify/assets/17873165/c74997db-aad6-4d0a-a120-737877ddec6f">

### ✔️ Expected Behavior

Expected Behavior: The system should support Directed Cyclic Graphs and function properly; Fallback solution: Prohibit the configuration of Directed Cyclic Graphs during setup.

### ❌ Actual Behavior

Directed Cyclic Graph configurations can be made, but they do not function properly and lead to page crashes.

**Comment by crazywoola** [comment]
It should be fixed in the latest preview.2.

**Comment by aute** [comment]
@crazywoola cloud.dify.ai With this configuration, the page still crashes

DSL：
`app:
  description: ''
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: "\u5DE5\u4F5C\u6D41\u6D4B\u8BD5"
workflow:
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: llm
        targetType: answer
      id: llm-answer
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
    - data:
        sourceType: answer
        targetType: llm
      id: answer-1712631599229
      source: answer
      sourceHandle: source
      target: '1712631599229'
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: llm
      id: 1712631599229-llm
      source: '1712631599229'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
    nodes:
    - data:
        desc: ''
        selected: false
        title: "\u5F00\u59CB"
        type: start
        variables: []
      height: 54
      id: '1712631571094'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        memory:
          window:
            enabled: false
            size: 10
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: ''
          provider: ''
        prompt_template:
        - role: system
          text: ''
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 54
      id: llm
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: "\u76F4\u63A5\u56DE\u590D"
        type: answer
        variables: []
      height: 107
      id: answer
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            frequency_penalty: 0
            max_tokens: 512
            presence_penalty: 0
            temperature: 0.7
            top_p: 1
          mode: chat
          name: gpt-4
          provider: openai
        prompt_template:
        - role: system
          text: '{{#sys.query#}}

            {{#llm.text#}}

            '
        selected: true
        title: LLM 2
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: '1712631599229'
      position:
        x: 980
        y: 282
      positionAbsolute:
        x: 980
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -107.42682239454302
      y: 174.42779870390524
      zoom: 0.7659653705592298
`

**Comment by Wahtes** [comment]
> It should be fixed in the latest preview.2.

Actually, this issue still exists in main branch with default configuration and cloud.dify.ai. Is it solved in any branch?

**Comment by WYY030903** [comment]
> It should be fixed in the latest preview.2.

I can still find this problem? Is there any fix way?
