### ISSUE TITLE
Speech to text feature documentation request

### ISSUE THREAD

**Issue by teodorpopescuQB** [langgenius/dify#3099]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Hi team, I am trying to enable speech to text functionality on the Dify chat interface but I can't find any pointers as to how to do this.

I only see a mention of speech to text here https://docs.dify.ai/user-guide/using-dify-apps/conversation-application#speech-to-text

### 2. Describe the feature you'd like to see

I would like to see a tutorial documentation page describing how to enable the speech to text functionality.

### 3. How will this feature improve your workflow or experience?

This will enable building products that have a voice interface

### 4. Additional context or comments

I think this will be of high value and I am also willing to pay for this feature if needed.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by perzeuss** [comment]
@crazywoolala as discussed in Discord, we should not hide the speech features if no language model (provider) has been configured. Instead we should display it with the switch disabled and add an error message that no language model is set up and link to the model settings.
