### ISSUE TITLE
Error status in knowledge file after finishing uploaded

### ISSUE THREAD

**Issue by trongnichietsu** [langgenius/dify#3102]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

- Uploading a knowledge file (Excel file)
- After finish upload, check the status of the knowledge file.

### ✔️ Expected Behavior

The knowledge is uploaded as AVAILABLE status.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/165017576/cbeb1421-a2e5-458b-be92-8ac40162c32f)
It shows ERROR status instead of AVAILABLE.

**Comment by JohnJyong** [comment]
Are you using our cloud service version? Can you pls retry this operation, 
we cannot reproduce this issue. thanks @trongnichietsu
