### ISSUE TITLE
Google search api save SerpApi key error:Nonetype Object is not iterable

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3103]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-preview-workflow.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/12423206/7e8b5b17-0021-4c11-9912-88140586b20e)

Nonetype Object is not iterable

**Comment by Yeuoly** [comment]
fixed
