### ISSUE TITLE
Support native function calling for Claude-3 models

### ISSUE THREAD

**Issue by richards199999** [langgenius/dify#3109]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Previously, Claude-3 models only support Vision; and other models, like gpt-4, have separated Vision and function-calling model. But now Claude-3 support native function calling.
Official Blog: [Tool Use for Anthropic Models](https://docs.anthropic.com/claude/docs/tool-use)

### 2. Describe the feature you'd like to see

Support function-calling for Claude-3 models.

### 3. How will this feature improve your workflow or experience?

Use vision and function-calling in one model.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
done #3111
