### ISSUE TITLE
[Workflow Issue] Knowledge Retrieval always return empty array result

### ISSUE THREAD

**Issue by trongnichietsu** [langgenius/dify#3110]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

![image](https://github.com/langgenius/dify/assets/165017576/95737ab0-52c3-4682-9491-8baea505dc7b)

![image](https://github.com/langgenius/dify/assets/165017576/db468294-c52d-4340-b963-c17373d7824f)

I put the knowledge file inside the Knowledge Retrieval part, but I always get an empty array result from it.
And LLM cannot generate data based on context.

Please instruct me how to set up the Knowledge Retrieval in the right way to get data from file.
Thank you.

**Comment by takatost** [comment]
What version are you deploying?

**Comment by FFinchR** [comment]
Have you configured the rerank model? If the rerank model is not configured, it will return empty data due to an error, even if the rerank model switch is turned off.
reference: https://github.com/langgenius/dify/issues/2954

**Comment by trongnichietsu** [comment]
> What version are you deploying?

I used the new version: [v0.6.0-preview-workflow.2](https://github.com/langgenius/dify/releases/tag/0.6.0-preview-workflow.2)

> Have you configured the rerank model? If the rerank model is not configured, it will return empty data due to an error, even if the rerank model switch is turned off. reference: #2954

So we need to put the rerank model to the knowledge files for the Workflow's Knowledge Retrieval to get the data, it is right?

**Comment by FFinchR** [comment]
> So we need to put the rerank model to the knowledge files for the Workflow's Knowledge Retrieval to get the data, it is right?

As far as i tested, yes.

**Comment by trongnichietsu** [comment]
@FFinchR Thank you, I will try out and check the result.

**Comment by trongnichietsu** [comment]
@FFinchR You are the best! Now I can get the data from the knowledge. 😊
I will close this issue, thank you very much.

**Comment by FFinchR** [comment]
> @FFinchR You are the best! Now I can get the data from the knowledge. 😊
> I will close this issue, thank you very much.

My pleasure. 😊
