### ISSUE TITLE
can not login dify on another computer after build docker dify on server

### ISSUE THREAD

**Issue by aixintiankong** [langgenius/dify#3113]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

After deploying diffy to the server through docker, I can login with my email address and password on the server. However, on another computer, when logging in through the server's intranet IP address, I can not login after entering the account number and password. It is invalid. What should I do? question? How to solve?

**Comment by crazywoola** [comment]
Please follow the docs.dify.ai to set correct env vars.
