### ISSUE TITLE
Was Dify Discord hacked? 

### ISSUE THREAD

**Issue by caioluis** [langgenius/dify#3115]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

I'm under the impression Dify Discord server was hacked. Perhaps it's better to review it and post a disclaimer. I suspect the hackers are trying to steal some crypto wallets information and balance.

**Comment by caioluis** [comment]
<img width="2012" alt="image" src="https://github.com/langgenius/dify/assets/30005368/d0775ea8-2266-4dcb-8f0f-feb70fe448cf">
A screenshot of the message posted today. They have repeatedly tagged everyone and redirected people to difypass.com, a website that seems to be a phishing model to connect to users' wallets.

**Comment by guchenhe** [comment]
This is to confirm our discord has been hacked. Trying to resolve this asap

**Comment by guchenhe** [comment]
We're all good now! Closing this
