### ISSUE TITLE
No Button to Start a new chat in page of Html Embedded 

### ISSUE THREAD

**Issue by DKAI99** [langgenius/dify#3123]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

03.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I use below code to embed App to my webpage.
But the sidebox is empty.
It's expected 
to display 'NEW Chat' button.
Now the user can not start a new chat, the conversation is endless.
Screenshot
![Not-sidebox-toStartChat](https://github.com/langgenius/dify/assets/166218684/20fd18e5-f5d2-447f-afa9-dedc84315756)
Link to reproduce bug
https://www.dankung.com/blogs/dankung-angler-mate-ai_3690

<iframe
 src="https://udify.app/chatbot/5wTmf2yYB3kt63XC"
 style="width: 100%; height: 100%; min-height: 700px"
 frameborder="0" 
 allow="microphone">
</iframe>

### ✔️ Expected Behavior

Show 'Start new chat' at sidebox in Html Embedded page.

### ❌ Actual Behavior

Now the user can not start a new chat, the conversation is endless.

**Comment by DKAI99** [comment]
thank you, I now use your code.
The DifyChat is at bottom right of my website, just a very small window. I want it embeded in center area of my web page.
How to do it?

**Comment by crazywoola** [comment]
Those answer is answered by the bot. You need to write you own css to center the application.
