### ISSUE TITLE
Create Custom Tool from example - Weather error

### ISSUE THREAD

**Issue by doucheng** [langgenius/dify#3125]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.0-preview-workflow.2 

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

https://github.com/langgenius/dify/assets/5676888/ecf150d4-9dba-4b23-aad2-1571542d214a

### ✔️ Expected Behavior

Create Custom Tool success.

### ❌ Actual Behavior

1 validation error for ApiBasedToolProviderController provider_id none is not an allowed value (type=type_error.none.not_allowed

**Comment by crazywoola** [comment]
Please this url. into an actual one.
<img width="311" alt="image" src="https://github.com/langgenius/dify/assets/100913391/0897eb51-79ab-4c1c-b597-426c9bd58245">

**Comment by kun321** [comment]
I get the same problem
My scheme is 
`
{
      "openapi": "3.1.0",
      "info": {
        "title": "Get weather data",
        "description": "Retrieves current weather data for a location.",
        "version": "v1.0.0"
      },
      "servers": [
        {
          "url": "https://api.cloudflare.com"
        }
      ],
      "paths": {
        "/accounts/XXX/ai/run/@cf/bytedance/stable-diffusion-xl-lightning": {
          "post": {
            "description": "Get temperature for a specific location",
            "operationId": "DrawWithLightning",
            "parameters": [],
            "deprecated": false
          }
        }
      }
    }`
    
![image](https://github.com/langgenius/dify/assets/124553455/8bd6cf8e-7440-4ac0-907e-51c8e5ca0745)
