### ISSUE TITLE
Workflow log has no content

### ISSUE THREAD

**Issue by FFinchR** [langgenius/dify#3135]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-preview-workflow.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Calling workflow through interface, no call log seen on the log page.
![image](https://github.com/langgenius/dify/assets/61258341/0bf34208-0a20-4cd8-ad2f-4fdf1ef8df63)
![image](https://github.com/langgenius/dify/assets/61258341/bda6085f-e471-4935-b209-a45116329965)

### ✔️ Expected Behavior

see the call log on the log page.

### ❌ Actual Behavior

 no call log seen on the log page.

**Comment by FFinchR** [comment]
I don't think it's a network issue because when I use a basic agent, it can collect logs.

![image](https://github.com/langgenius/dify/assets/61258341/0eda6f3f-b2b5-4ce1-a676-4737f6009473)

**Comment by crazywoola** [comment]
Fixed in v0.6.0.
