### ISSUE TITLE
How do I register a new user

### ISSUE THREAD

**Issue by Zuber0701** [langgenius/dify#3136]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

When I visit http://localhost/install for the first time, I will be redirected to localhost/signin. How do I create a new administrator? Or how do you clean up a previously created account?

**Comment by crazywoola** [comment]
Please read the docs to reset your account. => https://docs.dify.ai
