### ISSUE TITLE
The process of publishing bot to Enterprise WeChat through laf cloud function is not working

### ISSUE THREAD

**Issue by allen-studio** [langgenius/dify#3138]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

1、enter laf cloud function link here in documentation
<img width="1432" alt="image" src="https://github.com/langgenius/dify/assets/26627761/6f0b6a6e-6d25-4a6d-a0dc-559a1771f6ff">
2、In fact, Enterprise WeChat here requires that the registered domain name consistent with the enterprise entity must be entered
![image](https://github.com/langgenius/dify/assets/26627761/f12bf7fc-33e8-419d-85cc-fbf5e4cafad7)
Are there other ways to access Enterprise WeChat?

**Comment by crazywoola** [comment]
This is contributed by the community, we have no capacity to refine this doc at this moment.
