### ISSUE TITLE
ConnectionError: Vector database connection error

### ISSUE THREAD

**Issue by JackHu1120** [langgenius/dify#3139]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

ConnectionError: Vector database connection error
![image](https://github.com/langgenius/dify/assets/129717356/79581436-a5cb-403e-8980-859eecb0fdc0)

**Comment by crazywoola** [comment]
Please check your network connection to make sure the docker container or application can access the vector db.

**Comment by JackHu1120** [comment]
How to configure Weaviate?
