### ISSUE TITLE
Nested code blocks or other markdown blocks in the chat window need a copy button for easy code copying.

### ISSUE THREAD

**Issue by chuanzhubin** [langgenius/dify#3143]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I ask LLM a code question, LLM replies with a code snippet, and I find that there is only one large copy button. If I want to copy the code block, I can only select it and then press Ctrl+C.

### 2. Describe the feature you'd like to see

Nested code blocks or other markdown blocks in the chat window need a copy button for easy code copying.

### 3. How will this feature improve your workflow or experience?

Convenient for copying code blocks.

### 4. Additional context or comments

![image](https://github.com/langgenius/dify/assets/2813798/0584e9ad-e7a1-42c2-9a2c-3a515f5b55ea)

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/3104.
