### ISSUE TITLE
Support more storage vendors

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#3148]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

In our case, for security reason, dataset cannot be stored on Amazon or Azure

### 2. Describe the feature you'd like to see

Could you please add more storage like Huawei Cloud or Alicloud?

### 3. How will this feature improve your workflow or experience?

For domestic users, it is crucial to have data stored in a secure place, this is very important for large enterprises. Without this feature, we cannot go production

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by fatelei** [comment]
assign to me, i can add more extend storage

**Comment by LeoQuote** [comment]
I personally think there is no need to write additional code to support multiple storage engines. The current Dify supports the S3 protocol, and both Huawei Cloud and Alibaba Cloud you mentioned also support the S3 protocol. For Alibaba Cloud, you can clearly see in the documentation that you can use the AWS S3 SDK to call the relevant interfaces. Although there is no explicit documentation for Huawei Cloud, it also supports the S3 protocol. You can confirm this by raising a ticket with their customer service.

The only potential issue that may arise is that some vendors may not support the `auto` `S3_ADDRESS_STYLE`, only the `virtual` one. If this issue occurs, you just need to set the environment variables accordingly. This has already been implemented in #2934.

Personally, I suggest that unless you are a developer for a cloud vendor, there is no need to do this kind of development. S3 has already become the de facto standard, and if there are any incompatibilities, you can push the vendors to provide support.
