### ISSUE TITLE
Hello, do you have any plans to use the vLLM framework as a model provider? 

### ISSUE THREAD

**Issue by angenge** [langgenius/dify#3149]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I recently built an inference service using the vLLM framework. Now, I want to directly integrate it with Dify, but I’m facing difficulties and I’m not sure how to proceed.

### 2. Describe the feature you'd like to see

use the vLLM framework as a model provider

### 3. How will this feature improve your workflow or experience?

vLLM is an extremely concise inference framework that I’m currently focusing on. If it can be directly integrated with Dify, it would significantly reduce the development workload.

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
vLLM could be integrated by using OpenAI Compatible provider

**Comment by hiahia121** [comment]
using openAI compatible provider, get another error Credentials validation failed with status code 404

**Comment by bigbitbox** [comment]
When I use vLLM provide as a server,I can't user the function call Feature.

This is the vllm start script I used
```
python -m vllm.entrypoints.openai.api_server --model /home/chikii/models/Qwen2.5-7B-Instruct-AWQ --served-model-name qwen2.5 --trust-remote-code --max-model-len 10240 --host 0.0.0.0  --port 8060 --enable-auto-tool-choice --tool-call-parser hermes
```

<img width="1852" alt="image" src="https://github.com/user-attachments/assets/05528b53-a16c-4655-a53e-b3474bca6eb7">

And the error I got
`[openai_api_compatible] Error: API request failed with status code 400: {"object":"error","message":"[{'type': 'extra_forbidden', 'loc': ('body', 'functions'), 'msg': 'Extra inputs are not permitted', 'input': [{'name': 'ddgo_search', 'description': 'Perform searches on DuckDuckGo and get results.', 'parameters': {'type': 'object', 'properties': {'query': {'type': 'string', 'description': 'Key words for searching'}}, 'required': ['query']}}]}]","type":"BadRequestError","param":null,"code":400}`

**Comment by zhaifb** [comment]
> When I use vLLM provide as a server,I can't use the function call Feature.
> 
> This is the vllm start script I used
> 
> ```
> python -m vllm.entrypoints.openai.api_server --model /home/models/Qwen2.5-7B-Instruct-AWQ --served-model-name qwen2.5 --trust-remote-code --max-model-len 10240 --host 0.0.0.0  --port 8060 --enable-auto-tool-choice --tool-call-parser hermes
> ```
> 
> <img alt="image" width="1852" src="https://private-user-images.githubusercontent.com/60026827/371016137-05528b53-a16c-4655-a53e-b3474bca6eb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NjgxNjEsIm5iZiI6MTczNTk2Nzg2MSwicGF0aCI6Ii82MDAyNjgyNy8zNzEwMTYxMzctMDU1MjhiNTMtYTE2Yy00NjU1LWE1M2UtYjM0NzRiY2E2ZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA1MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OWFjYjMyNDBiYzUxZWJiZTBiNDYyNzEyOGMyMmExYTFmYmY1NWRhNmJjMzYxYmNmNTk0NmExNzE4NzU4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V3s_VHHVdoQWM8yVWwLNNKiJCiCacPgGoIPgNmX7KCE">
> And the error I got `[openai_api_compatible] Error: API request failed with status code 400: {"object":"error","message":"[{'type': 'extra_forbidden', 'loc': ('body', 'functions'), 'msg': 'Extra inputs are not permitted', 'input': [{'name': 'ddgo_search', 'description': 'Perform searches on DuckDuckGo and get results.', 'parameters': {'type': 'object', 'properties': {'query': {'type': 'string', 'description': 'Key words for searching'}}, 'required': ['query']}}]}]","type":"BadRequestError","param":null,"code":400}`

me too
