### ISSUE TITLE
create custom tool error: 1 validation error for ApiBasedToolProviderController provider_id none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by majian159** [langgenius/dify#3158]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-preview-workflow.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![3301712565444_ pic](https://github.com/langgenius/dify/assets/10176784/333a6454-5a70-4486-b107-2dd1751a7119)

**Comment by machgity** [comment]
got the same error with 0.6.0 preview version

**Comment by Yeuoly** [comment]
Already fixed, comming soon.
