### ISSUE TITLE
Weaviate端口映射

### ISSUE THREAD

**Issue by JackHu1120** [langgenius/dify#3164]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/129717356/a6bdc659-3261-431c-9285-3e4f87878909)
我将Weaviate的端口映射修改为42075，请问在web中需要怎么修改，或者是还需要修改其他相关的配置吗，现在向量数据库连接失败

### ✔️ Expected Behavior

连接成功

### ❌ Actual Behavior

向量数据库连接失败

**Comment by crazywoola** [comment]
<img width="667" alt="image" src="https://github.com/langgenius/dify/assets/100913391/a4d49253-75dc-4191-b6f8-d0c57693bf90">
