### ISSUE TITLE
Upgrade with docker-compose, execute database migration, PyTorch, TensorFlow >= 2.0, or flex not found.

### ISSUE THREAD

**Issue by mwnu** [langgenius/dify#3181]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.
docker-compose  down
docker-compose  pull
docker-compose  up -d
2.
 connect to PostgreSQL and execute the following SQL:
```
ALTER TABLE dataset_keyword_tables ADD COLUMN data_source_type VARCHAR(255) NOT NULL DEFAULT 'database';
ALTER TABLE embeddings ADD COLUMN provider_name VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE embeddings DROP CONSTRAINT embedding_hash_idx;
ALTER TABLE embeddings ADD CONSTRAINT embedding_hash_idx UNIQUE (model_name, hash, provider_name);
```
3.
Execute the below script to complete the migrate: 
```
docker compose exec api flask convert-to-agent-apps
```

### ✔️ Expected Behavior

complete the migrate

### ❌ Actual Behavior

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Start convert to agent apps.
Congratulations! Converted 0 agent apps.
![image](https://github.com/langgenius/dify/assets/45463732/38a17f01-1ce2-407d-9251-864854835068)

**Comment by crazywoola** [comment]
It depends on your application type, but this is a warning, you could ignore it.  

```
Start convert to agent apps.
Congratulations! Converted 0 agent apps.
```

As this suggests, this execution has no errors.

**Comment by takatost** [comment]
This is a warning message, you can ignore it.
