### ISSUE TITLE
Google search tool just return one search result

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3186]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/12423206/9e9d1d50-3189-4abe-bebf-4ae8b1ce8dcc)

Use build-in tool google search, when select the return type is text, it just returns one text result

**Comment by Yeuoly** [comment]
fixed #3215
