### ISSUE TITLE
Chat text box does not fit on the screen

### ISSUE THREAD

**Issue by SergioRico1** [langgenius/dify#319]
When starting a chat on mobile the textbox container does not adapt to the height of the screen to always appear, so the user must scroll to start typing.

Also when scrolling, the header part is lost. 

Tested on:
iPhone 11 Pro
Safari / Chrome
Cloud and Self-Host 

![image](https://github.com/langgenius/dify/assets/51226753/44a56f75-77cb-4aff-9b5b-97ff33e94640)
![image](https://github.com/langgenius/dify/assets/51226753/87b3c34d-4416-4b6e-b3cb-fa34d0570a4b)

**Comment by crazywoola** [comment]
Thanks, we are already working on this.
