### ISSUE TITLE
microphone not authorized

### ISSUE THREAD

**Issue by zps-509** [langgenius/dify#3190]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/109783453/7b7aa409-9a34-4399-8fc1-b22664a11a9d)
默认语音模型已设置好
![123](https://github.com/langgenius/dify/assets/109783453/d99b96e8-fe3d-449e-9fc7-99b927098b7e)
手机浏览器，怎么正确使用麦克风。

**Comment by crazywoola** [comment]
Please check the settings of the mobile phone.

**Comment by zps-509** [comment]
是不是非要https才能使用麦克风呀？ 有没这个限制。

**Comment by 1510386060** [comment]
这个问题得怎么解决，按照上面的方法修改了也没有用。
