### ISSUE TITLE
workflow: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bowenliang123** [langgenius/dify#3192]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Getting frontend errors when using workflow.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/1935105/0873be42-650b-4cc9-8948-cf41054e37fe)

The detailed message shown on Chrome console:
```
RangeError: Maximum call stack size exceeded
    at Object.vG (c37d3baf-28e3f72251fda642.js:1:562)
    at i (page-1b7d7714db188687.js:1:8088)
    at page-1b7d7714db188687.js:1:8128
    at Array.forEach (<anonymous>)
    at i (page-1b7d7714db188687.js:1:8111)
    at page-1b7d7714db188687.js:1:8128
    at Array.forEach (<anonymous>)
    at i (page-1b7d7714db188687.js:1:8111)
    at page-1b7d7714db188687.js:1:8128
    at Array.forEach (<anonymous>)
```

**Comment by bowenliang123** [comment]
@dosubot could you think again? "Maximum call stack size exceeded" seems more like an error in frontend code.

**Comment by zxhlyh** [comment]
fixed

**Comment by bowenliang123** [comment]
Thanks！
