### ISSUE TITLE
‌‌‌‌Inquiries regarding deployment through docker-compose

### ISSUE THREAD

**Issue by BANG88** [langgenius/dify#3195]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

https://docs.dify.ai/getting-started/install-self-hosted/docker-compose

Following these steps, I managed to get it running successfully. However, when I reached the login page and clicked on login, I got a 404 error. The documentation could actually be written better to allow users to get everything up and running directly in one go. It feels like the project is incredibly awesome, but it's frustrating when you can't even get it to run.What I expected was being able to run and log in without having to do anything extra. As for what needs to be configured in order to run it, that could be clearly stated in the documentation.What configurations are needed just so you can simply run this damn project?

- What is the default login email?
- balalalalaa
-

**Comment by crazywoola** [comment]
By default, if you installed successfully. You can access http://localhost/install to initialize your account. If you forget it, you can follow the docs to reset the password.

This is written in the homepage of the repo.

<img width="907" alt="image" src="https://github.com/langgenius/dify/assets/100913391/52de6271-3d21-4350-b42d-ca8bb49ead24">

**Comment by BANG88** [comment]
‌‌Thank you for your reply. Normally, local testing might be just as you said, solved with a single command. However, I used a VPS for installation, and port 80 was already occupied. Therefore, during installation, it should be mentioned how to proceed if services like nginx are already present. Is it possible to provide an approach similar to using `docker-compose.override.yml` to override the existing configuration? This could prevent many unnecessary issues and make it easier for more people to experience this project. Thank you.
