### ISSUE TITLE
chatglm3 with Triton Inference Server bad request

### ISSUE THREAD

**Issue by Huison** [langgenius/dify#3200]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![2024-04-09_11-37](https://github.com/langgenius/dify/assets/19699888/333220e5-26ff-4e51-ad8f-b66ba40408f7)

### ❌ Actual Behavior

![1](https://github.com/langgenius/dify/assets/19699888/373c71ff-6773-4710-8a25-9fc26eaf2bee)
![2](https://github.com/langgenius/dify/assets/19699888/d83a63cc-c42f-4e5f-8c2f-3e9e99459435)

**Comment by Huison** [comment]
![3](https://github.com/langgenius/dify/assets/19699888/405031bd-8d1e-4d32-ae76-b20b0460b50a)
it seems chatglm3 with Triton Inference Server works well

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
