### ISSUE TITLE
A huge of fail request indexing-status when upload knowledge file

### ISSUE THREAD

**Issue by trongnichi** [langgenius/dify#3207]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Go to Knowledge -> Upload file

### ✔️ Expected Behavior

The knowledge file can be uploaded with success message.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/165017576/8a7d53f1-2eae-4164-85b2-43f5add2fcdd)
- It sent multiple indexing-status requests parallel as a time and fail after that.

![image](https://github.com/langgenius/dify/assets/165017576/f22e757d-8521-48f0-94de-19c647ccb689)
- The knowledge was stopped upload, but it continued indexing and send error messages to the screen.

**Comment by trongnichietsu** [comment]
![image](https://github.com/langgenius/dify/assets/165017576/2658970b-961e-47b2-a971-ae99e5ad8e06)

Also happens in Cloud!!

**Comment by JohnJyong** [comment]
Are you using the econmy index type ? @trongnichietsu

**Comment by trongnichietsu** [comment]
> Are you using the econmy index type ? @trongnichietsu

I used High Quality index type to use re-rank model.

**Comment by trongnichi** [comment]
> I have the same problem when I upgrade Dify from 0.5.11 to 0.6.0-fix1

I don't know why they can release new version 0.6,1 without checking this, I have tested again on the cloud today, but still has this issue.

**Comment by JohnJyong** [comment]
Could you please provide more details, such as provide your files and embedding models? @trongnichi

**Comment by trongnichi** [comment]
> Could you please provide more details, such as provide your files and embedding models? @trongnichi

My files are all excel files from 300 - 700 kb, I use the default embedding models from OpenAI which is text-embedded-3-small.
The error happened when I clicked on "Go to document" after upload file --> Click to a file which is indexing and after 1 - 2s a huge of requests come.

**Comment by JohnJyong** [comment]
@JzoNgKVO

**Comment by iamjoel** [comment]
Fixed: https://github.com/langgenius/dify/pull/3411
