### ISSUE TITLE
Bing search tool always report error: {"bing_web_search": "tool invoke error: 'url'"}

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3208]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

{"bing_web_search": "tool invoke error: 'url'"}

Is this error caused by dify or bing search self?

**Comment by Yeuoly** [comment]
how to reproduce it? everything works as expected in my case
<img width="866" alt="image" src="https://github.com/langgenius/dify/assets/45712896/e1eae1de-e15f-4d26-bd90-5fb240d92d80">

**Comment by lx1054331851** [comment]
![image](https://github.com/langgenius/dify/assets/12423206/a1e8ba9b-e12f-44b5-a280-5269d4fda13f)

you can try this webapp url: http://20.255.59.22/chat/3mglEof1CCOKu1Np

**Comment by lx1054331851** [comment]
![image](https://github.com/langgenius/dify/assets/12423206/168b1972-41cd-4b8e-9cc8-3a7320a4c3ce)
![image](https://github.com/langgenius/dify/assets/12423206/daae8aff-24a2-4502-8164-fc3b764f26a8)

**Comment by Yeuoly** [comment]
it works 
<img width="616" alt="image" src="https://github.com/langgenius/dify/assets/45712896/7127146b-7a76-4bb7-bac5-7f3888de205c">

**Comment by lx1054331851** [comment]
How can I debug it, to find the problem?

**Comment by gaoliang-dl** [comment]
not use default bing url, use https://api.bing.microsoft.com/

**Comment by lx1054331851** [comment]
Is there something unkonw filters

input "美国大选”, the input is null as below

![image](https://github.com/langgenius/dify/assets/12423206/9ad4640a-28f8-4ee8-a0f7-3f24171bdaab)

But if I input "123美国大选", the problem does not exists
![image](https://github.com/langgenius/dify/assets/12423206/f681cd84-cc5b-4cf3-97af-111d8794a463)
![image](https://github.com/langgenius/dify/assets/12423206/f871a843-c8a1-43b8-bcc6-90fef9893b4f)

**Comment by ccsen** [comment]
云服务版也有同样的问题。感觉有敏感词审核。
使用敏感词会报错，换一个正常。

**Comment by lx1054331851** [comment]
I look into the soure code of bing search tool, I found the bing search base url is hard coded in the pyhton script, when enver you setting it 
![image](https://github.com/langgenius/dify/assets/12423206/7c25a7fd-f04b-44d7-a2be-3b04b553531d)

but bing search base url copied from azure portal is : 
```
https://api.bing.microsoft.com/bing/v7.0/search
```

**Comment by crazywoola** [comment]
It has been fixed right now.

**Comment by yyfrankyy** [comment]
> it works <img alt="image" width="616" src="https://private-user-images.githubusercontent.com/45712896/320733332-7127146b-7a76-4bb7-bac5-7f3888de205c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTExMzksIm5iZiI6MTcxMzk1MDgzOSwicGF0aCI6Ii80NTcxMjg5Ni8zMjA3MzMzMzItNzEyNzE0NmItN2E3Ni00YmI3LWJhYzUtN2YzODg4ZGUyMDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA5MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTExMTIxZDk0NzY1ZDNhZmU1YzYyYWRiZjk3ZDhkODg3YzU2MTIwMGYxNTRmYjgxNmRmMjkwMzgzODk1ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tzPspCv46Sj8RrDhhWoT4i6W4e8K8unk1Fk2W4lszfo">

same here at the official demo
