### ISSUE TITLE
The Chinese documentation about workflow is missing images of creation entry.

### ISSUE THREAD

**Issue by doucheng** [langgenius/dify#3209]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

https://docs.dify.ai/v/zh-hans/guides/workflow/key_concept
![image](https://github.com/langgenius/dify/assets/5676888/53a1e199-4afc-427e-8b08-f956cc2af253)

**Comment by VincePotato** [comment]
Fixed.
