### ISSUE TITLE
cant delete file

### ISSUE THREAD

**Issue by catundchat** [langgenius/dify#321]
Dify version: Cloud 

## Steps To Reproduce

1. create a dify dataset, then upload a file
2. wait for the embedding procedure

## The current behavior

After I uploaded a file, something strange occured to the embedding procedure, it can't finish. So I ended that and tried to delete it. As the picture shows, I can't delete it and says 'cant delete document during indexing'. But I have click the button “stop", this problem is still there.

![image](https://github.com/langgenius/dify/assets/62111484/5cd93a9b-5ac5-4abc-8496-ebf8b68ada70)

**Comment by zachariahtimothy** [comment]
Was there a resolution to this or a workaround? I had the same thing and they say "Indexing" indefinitely.

**Comment by catundchat** [comment]
I remembered that there are a lot of text to embed so that it took unexpected long time. After indexing, deleting file is possible.
