### ISSUE TITLE
Failed to execute code, this is likely a network issue, please check if the sandbox service is running

### ISSUE THREAD

**Issue by harryhan1989** [langgenius/dify#3211]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/2442117/c3c03f3d-8c22-4188-83f1-42488ac5ec10)

**Comment by Yeuoly** [comment]
there is a new service need to be started, pls check your middleware services.
