### ISSUE TITLE
incorrect transfer of image file in workflow.

### ISSUE THREAD

**Issue by CenturyOldGoblin** [langgenius/dify#3217]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

create any workflow
use image model

### ✔️ Expected Behavior

correct usage of image by LLM

### ❌ Actual Behavior

start:
{
  "sys.query": "这是什么书",
  "sys.files": [
    {
      "__variant": "FileVar",
      "tenant_id": "7767b646-820f-489e-85f2-83df6fecf57f",
      "type": "image",
      "transfer_method": "remote_url",
      "url": "https://s3proxy.cdn-zlib.se/covers400/collections/userbooks/adcfeeddedd2a11bb7a06c56c650cdeb1f4ec3518a51f75882c00dca68f95ed6.jpg",
      "related_id": null,
      "filename": null,
      "extension": null,
      "mime_type": null
    }
  ]
}
LLM:
{
  "model_mode": "chat",
  "prompts": [
    {
      "role": "system",
      "text": "你是一个乐于助人的助手。\n回答用户时：\n如果你不知道，就直说你不知道。如果你在不确定的时候不知道，就寻求澄清。\n避免提及你是从上下文中获取的信息。\n并根据用户问题的语言来回答。",
      "files": []
    },
    {
      "role": "user",
      "text": "这是什么书",
      "files": []
    }
  ]
}

**Comment by iamjoel** [comment]
Fixed in https://github.com/langgenius/dify/pull/3225

**Comment by LeeeeeeM** [comment]
Dify's files is not equal to LLM's files. They are different concepts.
