### ISSUE TITLE
Seeking Initial Guidance to Work on Bulk Upload

### ISSUE THREAD

**Issue by IAmStoxe** [langgenius/dify#322]
**Title**: Guidance for Bulk Document Upload to Specific Datasets in Dify

Hello Dify Team,

Thank you for the great work on Dify.

I'm looking into bulk uploading documents to a specific dataset. It's unclear if there are specific gotchas or best practices I should follow, hence, I'd appreciate any insights:

- Known issues or "gotchas" during this process.
- Specific paradigms or patterns for smooth integration.

In the meantime, I'm taking steps to achieve this:

1. Reverse Engineering: I'm trying to understand the existing upload functionality to guide the bulk upload process.
2. Python SDK: My goal is to replicate the bulk upload functionality in the Python SDK.

Thanks for your support.

Best regards.

**Comment by IAmStoxe** [comment]
Well I see that the SDK is where to implement this now. I will proceed with this in mind.

Something like the below (but significantly more robust)

```python

class DatasetClient(DifyClient):
    def init_dataset(self, indexing_technique: str, data_source: Dict[str, Any], process_rule: Dict[str, Any]) -> Dict[str, Any]:
        data = {
            "indexing_technique": indexing_technique,
            "data_source": data_source,
            "process_rule": process_rule
        }
        return self._send_request("POST", "/datasets/init")
       
```


More to follow

**Comment by takatost** [comment]
We're developing the bulk upload feature, and I understand that you need to be able to do it via the Service API, right? The Dataset Service API is also in our near-term development plan.
I took a look at your code and there may be some discrepancies. Our logic is to first upload the file through the /console/api/files/upload interface, and then import the file into the specified dataset through the /console/api/datasets/:dataset_id/documents interface.

**Comment by IAmStoxe** [comment]
Thank you for the reply and the insight! It is appreciated.

Based on your reply, I have another question if you don't mind.

1. Is it something that is close enough where I basically am duplicating effort / wasting time.
2. Is there an, even, hacky way to do this as of right now?

Still looking over the code base, but looking forward to jumping in. Thanks!

**Comment by takatost** [comment]
Right now, the only hacky way I can think of is to simulate the console session and api operations to achieve it, if u need it urgently.

**Comment by IAmStoxe** [comment]
Thanks. Will report back.

**Comment by bhctest123** [comment]
# Summary of the Proposed Feature

## 1. Description

The proposed feature is an API endpoint for bulk uploading of documents. The documents will be stored in a specified storage location, and their metadata will be recorded in a database.

## 2. Endpoint Specification

- **URL:** `/api/bulk-upload`
- **Method:** `POST`
- **Data Params:** `files[]`: An array of files to be uploaded.

## 3. Responses

### Success Response
- **Code:** `200`
- **Content:** 

```json
{
    "status": "success",
    "message": "Files have been uploaded successfully",
    "file_ids": ["<file_id_1>", "<file_id_2>", "...", "<file_id_n>"]
}
```

### Error Responses

- If there are no files in the request, or if the files are not in the allowed extensions:
  - **Code:** `400 BAD REQUEST`
  - **Content:** 

  ```json
  {
      "status": "error",
      "message": "<Appropriate error message>"
  }
  ```

- If the server encounters an error while trying to save the files:
  - **Code:** `500 INTERNAL SERVER ERROR`
  - **Content:** 

  ```json
  {
      "status": "error",
      "message": "An error occurred while uploading the files"
  }
  ```

## 4. Example Code

Here's a simplified example of how the endpoint might be implemented:

```python
from flask import Flask, request, jsonify
from werkzeug.utils import secure_filename
import os

app = Flask(__name__)

# Allowed file extensions
ALLOWED_EXTENSIONS = {'txt', 'html', 'md', 'xlsx', 'pdf'}

# Helper function to check if a file is allowed
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/api/bulk-upload', methods=['POST'])
def bulk_upload():
    # Check if the post request has the file part
    if 'files[]' not in request.files:
        return jsonify(status='error', message='No files in the request'), 400

    file_ids = []
    files = request.files.getlist('files[]')

    for file in files:
        # Check if the file is one of the allowed types
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

            # Get the ID of the file (e.g., from a database)
            # For this example, we'll just use the filename as the ID
            file_id = filename
            file_ids.append(file_id)

    return jsonify(status='success', message='Files have been uploaded successfully', file_ids=file_ids), 200

if __name__ == '__main__':
    app.run(debug=True)
```

In this example, uploaded files are saved to a local directory specified by `app.config['UPLOAD_FOLDER']`. However, in the actual Dify codebase, the `file.save()` method should be replaced with the appropriate file saving logic based on the storage solution used by Dify. Additionally, the logic to get the file ID would need to be updated to match the way Dify handles file metadata.

## 5. Database Considerations

When integrating this feature, it's important to consider how the file metadata will be stored in the database. In the above example, the filename is used as the file ID, but in the actual Dify codebase, you might want to generate a unique ID for each file and store additional metadata, such as the file size, upload date
