### ISSUE TITLE
我查看文档发现有计划支持本地模型，与多模型，那么请问会有支持应用设置使用的模型的计划吗？

### ISSUE THREAD

**Issue by liuzimu1995** [langgenius/dify#323]
目前微软的openai与官方openai在代码中是互斥的。因为get_default_provider的参数是tenant_id。
并且设置适配器是互斥的，不能同时生效。
那么未来会有计划支持其他模型的时候，能根据应用的设置来使用哪个适配器吗？

**Comment by takatost** [comment]
Hi there, it's planned. This part will be refactored later and you can choose the provider and model at any stage.

**Comment by liuzimu1995** [comment]
Thanks
