### ISSUE TITLE
When llm system prompt is relatively long, it seems that the workflow cannot be saved

### ISSUE THREAD

**Issue by Akifyss** [langgenius/dify#3231]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Add an llm node in the workflow. When the llm system prompt is relatively long, save fails, and upon reloading the page, it is found that modifications are lost.
<img width="1079" alt="image" src="https://github.com/langgenius/dify/assets/23567154/b6991376-30a8-44ab-9c0c-ccf67833d122">

**Comment by takatost** [comment]
Can you please provide the response of the request to `/console/api/apps/:app_id/workflows/draft` at that time?

**Comment by Akifyss** [comment]
The following information was returned
<img width="387" alt="image" src="https://github.com/langgenius/dify/assets/23567154/c4dfa92f-411f-480f-8ec5-f808ec748027">

```html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script type="7df4c55e98b1e061f7343fd6-text/javascript">
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> dify.ai</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">871a0bfe3d3e17ec</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">2602:feda:f1d6:12ac:44dc:bb99:752c:ff09</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script type="7df4c55e98b1e061f7343fd6-text/javascript">(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="7df4c55e98b1e061f7343fd6-text/javascript">
  window._cf_translation = {};
  
  
</script>

<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="7df4c55e98b1e061f7343fd6-|49" defer></script></body>
</html>
```

**Comment by Akifyss** [comment]
Longer texts will trigger an error, but if I delete parts of the original text, I can save it successfully and get the following information:{"result": "success", "updated_at": 1712661419}

**Comment by Akifyss** [comment]
I've found the real triggering reason; it should have nothing to do with the length of the prompt. As long as there is a "<script>" character in the prompt word, it cannot be saved.

**Comment by takatost** [comment]
> The following information was returned <img alt="image" width="387" src="https://private-user-images.githubusercontent.com/23567154/320825907-c4dfa92f-411f-480f-8ec5-f808ec748027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzEwNzYsIm5iZiI6MTcxMjY3MDc3NiwicGF0aCI6Ii8yMzU2NzE1NC8zMjA4MjU5MDctYzRkZmE5MmYtNDExZi00ODBmLThlYzUtZjgwOGVjNzQ4MDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEzNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OGM0MzcyMjJkOWRjYWMwNmM2NjdkNzY5M2ZjMzk4NjlhMjk3OTk0YjViNDg0ODgyYmRhODZhNDI2NDhiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FNDUO0VqVaqtkL1mPpfqll6oM10oT6_rO-ZkFTW_j3E">
> 
> ```
> <!DOCTYPE html>
> 
> 
> 
>  <html class="no-js" lang="en-US"> 
> <head>
> <title>Attention Required! | Cloudflare</title>
> <meta charset="UTF-8" />
> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
> <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
> <meta name="robots" content="noindex, nofollow" />
> <meta name="viewport" content="width=device-width,initial-scale=1" />
> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
> 
> <style>body{margin:0;padding:0}</style>
> 
> 
> 
> <script type="7df4c55e98b1e061f7343fd6-text/javascript">
>   if (!navigator.cookieEnabled) {
>     window.addEventListener('DOMContentLoaded', function () {
>       var cookieEl = document.getElementById('cookie-alert');
>       cookieEl.style.display = 'block';
>     })
>   }
> </script>
> 
> 
> 
> </head>
> <body>
>   <div id="cf-wrapper">
>     <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
>     <div id="cf-error-details" class="cf-error-details-wrapper">
>       <div class="cf-wrapper cf-header cf-error-overview">
>         <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
>         <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> dify.ai</h2>
>       </div>
> 
>       <div class="cf-section cf-highlight">
>         <div class="cf-wrapper">
>           <div class="cf-screenshot-container cf-screenshot-full">
>             
>               <span class="cf-no-screenshot error"></span>
>             
>           </div>
>         </div>
>       </div>
> 
>       <div class="cf-section cf-wrapper">
>         <div class="cf-columns two">
>           <div class="cf-column">
>             <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>
> 
>             <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
>           </div>
> 
>           <div class="cf-column">
>             <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>
> 
>             <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
>           </div>
>         </div>
>       </div>
> 
>       <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
>   <p class="text-13">
>     <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">871a0bfe3d3e17ec</strong></span>
>     <span class="cf-footer-separator sm:hidden">&bull;</span>
>     <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
>       Your IP:
>       <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
>       <span class="hidden" id="cf-footer-ip">2602:feda:f1d6:12ac:44dc:bb99:752c:ff09</span>
>       <span class="cf-footer-separator sm:hidden">&bull;</span>
>     </span>
>     <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
>     
>   </p>
>   <script type="7df4c55e98b1e061f7343fd6-text/javascript">(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
> </div>
> 
> 
>     </div>
>   </div>
> 
>   <script type="7df4c55e98b1e061f7343fd6-text/javascript">
>   window._cf_translation = {};
>   
>   
> </script>
> 
> <script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="7df4c55e98b1e061f7343fd6-|49" defer></script></body>
> </html>
> ```

It looks like you've been detected by CloudFlare as a risk and banned from accessing. Please make sure your network environment is clean. 👀

**Comment by Akifyss** [comment]
I guess it has nothing to do with the network, because I delete the <script> character in the prompt, and everything will return to normal.

**Comment by JokerQyou** [comment]
That just means the `<script>` tag is triggering cloudflare WAF protection, probably enabled by Dify dev teams.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
