### ISSUE TITLE
weaviate修改端口映射

### ISSUE THREAD

**Issue by HuQi1120** [langgenius/dify#3232]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

我将weaviate端口映射改成了8090::8080,那么还需要修改哪些配置才可以运行，请告诉需要修改的所有配置

**Comment by crazywoola** [comment]
Close due to #1542 If you have questions, please head to discussion channel. https://github.com/langgenius/dify/discussions
