### ISSUE TITLE
工作流的问题分类器后续步骤偶尔会错乱Workflow's issue classifier subsequent steps occasionally get messed up

### ISSUE THREAD

**Issue by chinesewebman** [langgenius/dify#3240]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

the running version on dify.ai by the date of April 9 2024

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![DIFY_bug_01](https://github.com/langgenius/dify/assets/62828980/8f6bdc00-091b-4c41-bf6a-ec5dd2b53718)
![DIFY_bug_02](https://github.com/langgenius/dify/assets/62828980/99fa50b2-ee33-47e3-ac33-7f1de34b03f2)

### ✔️ Expected Behavior

it should go to the direct reply block which is for the second result: express a negative attitude

### ❌ Actual Behavior

it goes to the steps for the first result.

**Comment by crazywoola** [comment]
Close due to #1542
