### ISSUE TITLE
Directly create app with flow can not use image upload function

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3248]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/12423206/84cc7575-330c-497b-987b-716e675c6018)

# showed as above image, the llm just not get any image , and the app was created directly with chatflow
![image](https://github.com/langgenius/dify/assets/12423206/9647e8d0-cff3-4d2d-bb80-c6b3a79ed65d)

# But if i create a basic app and convert to chatflow, the image upload function can be used and the llm can read the image

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/3228

**Comment by iamjoel** [comment]
Fixed with https://github.com/langgenius/dify/pull/3225
