### ISSUE TITLE
Wrong segment number when using api to add batch segments.

### ISSUE THREAD

**Issue by sunxichen** [langgenius/dify#3270]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

add batch segments using add segment API (http://{DIFY_URL}/v1/datasets/{DATASET_ID}/documents/{DOCUMENT_ID}/segments), and it assign same number to all segments within same batch.
request example:
```python
for i in tqdm(range(0, len(datas), 10)):
      batch_datas = datas[i : i + 10]
      response = requests.post(
            url=DIFY_ADD_SEGMENT_URL,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {DIFY_DATASET_API_KEY}"
                },
            json={"segments": batch_datas},
      )
```

### ✔️ Expected Behavior

Different segment should have different number although they are added in the same batch.
![1E27FF9D-53CA-4B71-8AA0-0A728009107C](https://github.com/langgenius/dify/assets/18310222/f1596dc5-1efc-44cf-8880-bc44bfa4e94d)

### ❌ Actual Behavior

Different segment have same number when they are added in the same batch
![1E27FF9D-53CA-4B71-8AA0-0A728009107C](https://github.com/langgenius/dify/assets/18310222/f1596dc5-1efc-44cf-8880-bc44bfa4e94d)

**Comment by JohnJyong** [comment]
issue fixed by pr：https://github.com/langgenius/dify/pull/3351, thanks for your feedback @sunxichen
