### ISSUE TITLE
Model gpt-3.5-turbo credentials is not initialized.

### ISSUE THREAD

**Issue by cq134cq** [langgenius/dify#3271]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![21BCFF97-1D9C-478b-A533-18B600522E34](https://github.com/langgenius/dify/assets/95132993/efc2c51a-68df-47a2-8841-db94a53e6684)?
3.5是正常可以使用的，可就是用这个出错不知为什么，是那里设错了吗?

### ✔️ Expected Behavior

3.5是正常可以使用的，可就是用这个出错不知为什么，是那里设错了吗?

### ❌ Actual Behavior

3.5是正常可以使用的，可就是用这个出错不知为什么，是那里设错了吗?

**Comment by cq134cq** [comment]
在线等

**Comment by crazywoola** [comment]
Please select default system reasoning model in model providers page.

**Comment by dashjim** [comment]
Today I am have the same error. And I choose the keywords search as the retrieval method, it should not require any LLM ability. So this error should not happen and the message is misleading.

**Comment by oriofdarkforest** [comment]
I'm having the same issue. I already set the default reasoning model (gpt4) in settings.
