### ISSUE TITLE
选框段落上限1024

### ISSUE THREAD

**Issue by ZaiQi-zq** [langgenius/dify#3278]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

希望可以消除1024限制或者加一个选框，不受1024段落输入上限的限制。

### 2. Describe the feature you'd like to see

希望可以消除1024限制或者加一个选框，不受1024段落输入上限的限制。

### 3. How will this feature improve your workflow or experience?

文稿需求

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Close due to #1542
