### ISSUE TITLE
Suspicious error appeared when upload knowledge file

### ISSUE THREAD

**Issue by trongnichi** [langgenius/dify#3280]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-preview-workflow.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Knowledge -> Upload CSV file (only 501 KB)

### ✔️ Expected Behavior

Upload file successfully without error

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/165017576/6a1a650b-a61d-44d1-95b5-624871131660)
The file suddenly caused error when it had loading 70% and show suspicious error message.

**Comment by crazywoola** [comment]
Please upgrade to latest version which is v0.6.1. Also please read the release logs in v0.6.0 & v0.6.1
