### ISSUE TITLE
Vision support selector is not visible in openapi-compatible-provider 

### ISSUE THREAD

**Issue by shing19** [langgenius/dify#3282]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![截屏2024-04-10 11 58 42](https://github.com/langgenius/dify/assets/38907754/c7542e50-de2e-4643-a1eb-ccee8d214b07)
![截屏2024-04-10 12 00 27](https://github.com/langgenius/dify/assets/38907754/264f4de1-9106-4c25-9dbb-5e56a7788bd3)
I've pull latest main branch. Be sure with that, I check file openai_api_compatible.yaml that it contain vision support options. However, it doesn't show on config page.

### ✔️ Expected Behavior

There should be a vision support selector on openapi-compatible-provider adding page.

### ❌ Actual Behavior

No vision support selector on openapi-compatible-provider adding page.

**Comment by takatost** [comment]
Supported in #3272, will be released in 0.6.2, or you can have an early access in SaaS.
