### ISSUE TITLE
Bing search tool option set not work at backend

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3289]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

At setting page, I just enable the web page search option

![image](https://github.com/langgenius/dify/assets/12423206/ab3eab38-7555-4a5d-8e61-9a1663b709cf)

But at the search parameters, other options all enabled
![image](https://github.com/langgenius/dify/assets/12423206/57085276-c57c-4d91-bf83-0f0a29adb96c)

**Comment by Yeuoly** [comment]
Got it, thx
