### ISSUE TITLE
When create knowledge, Maximum chunk length and retrieval top k can be more, give the max chioce to users

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3290]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I found, the default max value now can not meet my job.
With the default max value both max chunk length or retrieval top k, the retrieval result is bad.
I use other tools, set more max value of max chunk length and top k, the result is better than dify.

### 2. Describe the feature you'd like to see

increase the max chunk length to 5000 or more,
increate the retrieval top k to 50 or more

### 3. How will this feature improve your workflow or experience?

increate the rate of retrieval

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by JohnJyong** [comment]
we will add below function in our plan: Set the segment length according to the token size supported by the model
