### ISSUE TITLE
在国内 docker 部署 dify 如何修改 openai 的默认连接？ 文档上不清晰

### ISSUE THREAD

**Issue by aaronuu** [langgenius/dify#3292]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

在国内 docker 部署 dify 如何修改 openai 的默认连接？ 文档上不清晰

**Comment by crazywoola** [comment]
Close due to #1542
