### ISSUE TITLE
after Prview, rein this application ,got :Application error

### ISSUE THREAD

**Issue by lingfengchencn** [langgenius/dify#3294]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、create a new application "问题分类 + 知识库 + 聊天机器人" ；
2、click "Preview"
3、click "Studio" to go back application list;
4、click "问题分类 + 知识库 + 聊天机器人" application ;
5、perhaps you will get the error “ Application error: a client-side exception has occurred (see the browser console for more information).”

**Comment by crazywoola** [comment]
Please try the latest version v0.6.1
