### ISSUE TITLE
model embedding credentials is not initialized

### ISSUE THREAD

**Issue by talosL** [langgenius/dify#3295]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I was uploading a file using the knowledge base, the interface threw a 400 error with the message "model embedding credentials is not initialized". However, my model configuration is correct.

### ✔️ Expected Behavior

Calculate the consumed tokens correctly and segment them.

### ❌ Actual Behavior

model embedding credentials is not initialized

**Comment by crazywoola** [comment]
<img width="1121" alt="image" src="https://github.com/langgenius/dify/assets/100913391/747c697a-cce2-497d-b6c0-994337e727c8">
Please provide more details such as which embedding model.

**Comment by JohnJyong** [comment]
@talosL

**Comment by talosL** [comment]
Sorry, this is indeed empty. It will work normally once I set it correctly.
