### ISSUE TITLE
Preview with show PROMPT LOG at the same time

### ISSUE THREAD

**Issue by lingfengchencn** [langgenius/dify#3297]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、goto a appllication history and the it's Prompt log:
![image](https://github.com/langgenius/dify/assets/2757011/8fa0074f-caef-4cb8-9372-3ec3400e5cfb)

2、just go to studio （need click twice）
3、goto a workflow application,
4. click preview
![image](https://github.com/langgenius/dify/assets/2757011/d4fbc2ff-93ec-417a-9fc6-f25284724567)

### ✔️ Expected Behavior

close "PROMPT LOG" after leave  history log

**Comment by crazywoola** [comment]
It should be fixed in latest version.
