### ISSUE TITLE
azure openai service 绑定后提示provider token not initialize

### ISSUE THREAD

**Issue by tairitian** [langgenius/dify#33]
使用docker部署在硅谷节点的一台ecs上，web页面等都能正常，但绑定了azure openai key后，也没提示绑没绑定成功，在使用的时候提示provider token not initialize

**Comment by takatost** [comment]
azure 有些差异，界面需要调整，正在开发中
duplicate #22

**Comment by takatost** [comment]
已支持临时方案，注意事项见最后一条：
https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq
