### ISSUE TITLE
Can an ELIF logic be added to the IF/ELSE Node?

### ISSUE THREAD

**Issue by AAlexDing** [langgenius/dify#3305]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I have multiple options, I want different options to lead to different branches; the if/else node is not sufficient to make this logic simple to implement.

### 2. Describe the feature you'd like to see

Add ELIF logic in the IF/ELSE Node to allow the Node to support multiple conditional branches.

### 3. How will this feature improve your workflow or experience?

..

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes, just connect another if/else node.

<img width="491" alt="image" src="https://github.com/langgenius/dify/assets/100913391/19297916-0189-4d26-85fd-fc657f18a55f">

**Comment by desperado0807** [comment]
@crazywoola But not elegant at all...if the amount of conditions are big, the count of nodes would also be huge and hard to maintain

**Comment by kms9** [comment]
Yes , if it can customize the IF/else node by adding more else criteria it will be more better
