### ISSUE TITLE
Custom tool configuration is incorrect

### ISSUE THREAD

**Issue by cslcsl490** [langgenius/dify#3306]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/8390846/7a22bc03-ceee-44fc-8cd9-959ab2f73e20)
![image](https://github.com/langgenius/dify/assets/8390846/c0e19177-e57a-4556-8072-dd7c206761e0)
the type of the “distance” field is incorrect. The expected type is object, but the actual type is string.

### ✔️ Expected Behavior

object

### ❌ Actual Behavior

string

**Comment by Yeuoly** [comment]
sorry for that, but object type is not supported in function calling for most popular model providers now, it will confuse LLM and leads incorrect parameters reasoned.
