### ISSUE TITLE
The event-status API is being called frantically in document detail page while the document status is Indexing

### ISSUE THREAD

**Issue by liuzhenghua** [langgenius/dify#3313]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. create knowleage
2. upload a pdf
[薛兆丰经济学讲义xg.pdf](https://github.com/langgenius/dify/files/14930371/xg.pdf)
3. go to the document detail page and wait for a while

### ✔️ Expected Behavior

The event-status API is called every few seconds.

### ❌ Actual Behavior

The event-status API is being called frantically
![image](https://github.com/langgenius/dify/assets/11787325/5760455d-2dd1-4b0a-8b85-d811e1b3c818)

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
