### ISSUE TITLE
Workflow run code tool error: operation not permitted

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3331]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```python3
import re
import requests
def main(arg1) -> dict:
    urls = re.findall(r'http[s]?://[^\s)]+', arg1)
    return {
        "result": urls[0],
    }
```

```
error: operation not permitted
```

**Comment by takatost** [comment]
Pls remove this codes `import requests`.

**Comment by lx1054331851** [comment]
what is the restrictions using code tool

**Comment by Yeuoly** [comment]
Only native Python packages are allowed, and network/file/OS access are not permitted also.

**Comment by lx1054331851** [comment]
Got it. Thank you!

**Comment by cdll** [comment]
same issue here even i didnt change ang code in the repo

**Comment by programmermw1986** [comment]
I install numpy in sanbox container；  how to make it work in code node

**Comment by FWLamb** [comment]
> Only native Python packages are allowed, and network/file/OS access are not permitted also.

What should I do if I want to use third-party dependencies？

**Comment by filwu8** [comment]
> > 只允许使用本机 Python 包，并且不允许访问网络/文件/操作系统。
> 
> 如果我想使用第三方依赖项该怎么办？

我也遇到这个问题，使用第三方依赖，报错
