### ISSUE TITLE
openai 自定义模型无法通过

### ISSUE THREAD

**Issue by bincooo** [langgenius/dify#3332]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

RT

`API Base` 填写了中转地址，并且该中转地址的 `/v1/models` 也有自定义model的返回；
但是在添加模型时报错：`Base model coze not found`
<img width="649" alt="Screenshot 2024-04-11 at 00 45 54" src="https://github.com/langgenius/dify/assets/36452456/a3e391b6-72ba-42db-b74b-63c0a7d4ad7d">

<img width="441" alt="Screenshot 2024-04-11 at 00 47 53" src="https://github.com/langgenius/dify/assets/36452456/31071881-fcbf-41d2-aae6-ff909450ef2e">

**Comment by bincooo** [comment]
在docker-compose.yaml中配置`HOSTED_OPENAI_API_BASE`是否有效？

**Comment by bincooo** [comment]
? 咋关了

**Comment by JokerQyou** [comment]
> ? 咋关了

用英文，你提交issue的时候模板里面已经写了"I confirm that I am using English to submit this report"，非英文的issue会直接关闭。

**Comment by qianfeiqianlan** [comment]
可以直接修改源码里面 OpenAI client 初始化的地方跳过证书校验，可能是代理的证书生成的有问题

https://stackoverflow.com/questions/72858917/python-requests-throws-sslcertverificationerror-with-lets-encrypt-certificates

https://github.com/langgenius/dify/discussions/4600
