### ISSUE TITLE
我导入我的EXCEL发现信息不完全。  

### ISSUE THREAD

**Issue by srmyiming** [langgenius/dify#336]
我导入了我的EXCEL,一共100行，但是实际他只导入了22行

**Comment by JohnJyong** [comment]
![image](https://github.com/langgenius/dify/assets/76649700/137ac23a-31f3-41d0-b8c8-de12c96a00d7)
I tested a 128-line xlsx file, and it seems that I didn’t find the problem you mentioned. Please try again. If you still have problems, please send your file, and we can troubleshoot the problem together.
