### ISSUE TITLE
Segmented tasks unable to complete after platform idle

### ISSUE THREAD

**Issue by saber-sun** [langgenius/dify#3369]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After the platform has been idle for a period of time, there is an issue with completing segmented tasks in the knowledge base by uploading files. When trying to upload a file for a segmented task, the task fails to progress or complete as expected. This bug is preventing the successful completion of segmented tasks in the knowledge base after the platform has been idle for a certain duration.
![image](https://github.com/langgenius/dify/assets/108671937/c802f672-c990-47e1-b558-d9ede6bed2a7)

**Comment by crazywoola** [comment]
Please provide the logs.

**Comment by saber-sun** [comment]
[redis-connection-timeout - out.txt](https://github.com/langgenius/dify/files/14987502/redis-connection-timeout.-.out.txt)

**Comment by crazywoola** [comment]
Please upgrade to latest to see if this issue persists.
