### ISSUE TITLE
调用云服务的应用API时，总是显示：unauthorized

### ISSUE THREAD

**Issue by smallanything** [langgenius/dify#337]
curl --location --request POST 'https://api.dify.dev/v1/chat-messages' \
--header 'Authorization: Bearer app-zvdXk****************' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "eh",
    "response_mode": "streaming",
    "conversation_id": "1c7e55fb-1ba2-4e10-81b5-30addcea2276"
    "user": "abc-123"
}'

我通过这个在网页端进行调用，但一直反馈失败
"code": "unauthorized",
    "message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
    "status": 401
}

求问如何解决

**Comment by smallanything** [comment]
我直接用postman调用，反馈是：
{ "code": "bad_request", "status": 400, "message": "The browser (or proxy) sent a request that this server could not understand." }

**Comment by crazywoola** [comment]
Try to make `conversation_id: null` if you are call it first time.

**Comment by smallanything** [comment]
> 

thanks, but I have tried from your suggestion,but here is the result :(

curl --location --request POST 'https://api.dify.dev/v1/chat-messages' \
--header 'Authorization: Bearer app-***************' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "eh",
    "response_mode": "streaming",
    "conversation_id": null
    "user": “dify”
}'
{
    "code": "unauthorized",
    "message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
    "status": 401
}

**Comment by takatost** [comment]
I think I found that there's a missing comma after "conversation_id": null

**Comment by smallanything** [comment]
There is the same result：unauthorized

> 

curl --location --request POST 'https://api.dify.dev/v1/chat-messages' \
--header 'Authorization: Bearer app-**************' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "eh",
    "response_mode": "streaming",
    "conversation_id": null,
    "user": “dify”
}'
{
    "code": "unauthorized",
    "message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
    "status": 401
}

**Comment by takatost** [comment]
The domain you filled in is wrong, it should be `https://api.dify.ai/`

**Comment by smallanything** [comment]
> 

I have changed the domain, but the result is : { "code": "bad_request", "status": 400, "message": "The browser (or proxy) sent a request that this server could not understand." }

**Comment by kmfish** [comment]
> > 
> 
> I have changed the domain, but the result is : { "code": "bad_request", "status": 400, "message": "The browser (or proxy) sent a request that this server could not understand." }

me too...

**Comment by xmsz-stu** [comment]
The browser (or proxy) sent a request that this server could not understand. 有人解决了吗

**Comment by losdwind** [comment]
![Uploading Screenshot 2024-02-05 at 22.39.32.png…]()

**Comment by v-49** [comment]
every different app`s key is different, i think thats the key
