### ISSUE TITLE
Add support of new Rerank 3 from Cohere

### ISSUE THREAD

**Issue by richards199999** [langgenius/dify#3374]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Please add the support of this new rerank model. It perform better in RAG tasks comparing to the last version (Rerank 2).

Here is the official link: https://txt.cohere.com/rerank-3/

### 2. Describe the feature you'd like to see

Just add the support of the new rerank model.🤗

### 3. How will this feature improve your workflow or experience?

Make RAG experience even better.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yash-1511** [comment]
You can check this.  #3431

**Comment by richards199999** [comment]
wow, thank you!👍👍
