### ISSUE TITLE
Proposal to add Website Crawling to Dify 

### ISSUE THREAD

**Issue by bhctest123** [langgenius/dify#338]
@takatost

Here is my proposal

### Backend Changes:

1. Create a service for website crawling and scraping tasks in the `services` directory. This service will send HTTP requests, parse HTML, and convert extracted content to markdown. We'll add error handling and rate limiting to prevent overloading both our server and the target website.

2. Create an API endpoint in the `controllers/service_api` directory. This endpoint will call the new service, handle any errors, and return the scraped markdown text.

### Frontend Changes:

1. Create a new component in the `components` directory for the website crawler feature. This component will contain an input field for the URL, a button to initiate the crawling and scraping process, a progress indicator, and a display area for the results. We'll add error handling and user feedback during the crawling and scraping process.

Here's a more sophisticated code structure:

```python
# services/website_crawler.py

import requests
from bs4 import BeautifulSoup
import html2text
from ratelimiter import RateLimiter
from requests.exceptions import RequestException

# Rate limiting to 1 request per second
rate_limiter = RateLimiter(max_calls=1, period=1)

def crawl_and_scrape(url):
    with rate_limiter:
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
        except RequestException as e:
            # Handle different types of request exceptions
            raise Exception("Failed to fetch the webpage") from e

    soup = BeautifulSoup(response.text, 'html.parser')

    # Extract text from the webpage and handle potential parsing errors
    try:
        text = ' '.join([p.text for p in soup.find_all('p')])
    except Exception as e:
        raise Exception("Failed to parse the webpage") from e

    # Convert the text to markdown and handle potential conversion errors
    try:
        markdown_text = html2text.html2text(text)
    except Exception as e:
        raise Exception("Failed to convert the text to markdown") from e

    return markdown_text
```

```python
# controllers/service_api/website_crawler.py

from flask import Blueprint, request, jsonify
from services.website_crawler import crawl_and_scrape

bp = Blueprint('website_crawler', __name__)

@bp.route('/api/crawl', methods=['POST'])
def crawl_and_scrape_endpoint():
    url = request.json['url']
    try:
        markdown_text = crawl_and_scrape(url)
        return jsonify(status='success', markdown_text=markdown_text), 200
    except Exception as e:
        # Detailed error handling
        return jsonify(status='error', message=str(e)), 500
```

Here's frontend code for a version of the `WebsiteCrawler` component that uses TypeScript types and conforms to Dify general best practices:

```jsx
// web/app/components/website-crawler/WebsiteCrawler.tsx

import React, { FC, FormEvent, ChangeEvent, useState } from 'react';
import axios from 'axios';

// Define types for the state
type State = {
  url: string;
  markdownText: string;
  isLoading: boolean;
  error: string | null;
};

const WebsiteCrawler: FC = () => {
  const [state, setState] = useState<State>({
    url: '',
    markdownText: '',
    isLoading: false,
    error: null,
  });

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    setState(prevState => ({ ...prevState, isLoading: true }));
    try {
      const response = await axios.post('/api/crawl', { url: state.url });
      setState(prevState => ({
        ...prevState,
        markdownText: response.data.markdown_text,
        error: null,
      }));
    } catch (error) {
      setState(prevState => ({ ...prevState, error: `An error occurred: ${error.message}` }));
    }
    setState(prevState => ({ ...prevState, isLoading: false }));
  };

  const handleUrlChange = (event: ChangeEvent<HTMLInputElement>) => {
    const newUrl = event.target.value;
    setState(prevState => ({ ...prevState, url: newUrl }));
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <input type="text" value={state.url} onChange={handleUrlChange} required />
        <button type="submit" disabled={state.isLoading}>Crawl</button>
      </form>
      {state.isLoading ? <p>Loading...</p> : <div>{state.markdownText}</div>}
      {state.error && <p>Error: {state.error}</p>}
    </div>
  );
};

export default WebsiteCrawler;
```

This code now uses TypeScript types for the component and its state, and it uses a single state object instead of multiple state variables. The state updates are now done with a function that takes the previous state, which can help avoid potential issues with asynchronous state updates.

Please note that this code still needs to be tested and integrated within the Dify codebase. Depending on the Dify project's specific requirements and coding standards, further adjustments may be necessary.

For instance, the exact import statement for `axios` might need to be adjusted based on your project's setup, and the URL in the `axios.post` call might need to be adjusted based on the backend's configuration. The user interface design is also still very basic, and you might want to adapt it to fit the Dify project's design system.

**Comment by takatost** [comment]
Your code is really helpful for us, we'll take some of them into consideration and modify them to fit our code architecture, e.g. making it async. 
Thx so much for ur suggestion, and have a good day!
