### ISSUE TITLE
langgenius/dify-api:0.6.2-fix1-fix1 not found

### ISSUE THREAD

**Issue by ZaiQi-zq** [langgenius/dify#3386]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/129143636/0643cb8f-23d2-4e17-9911-c7d854c4cdf0)

### ✔️ Expected Behavior

success

### ❌ Actual Behavior

false

**Comment by takatost** [comment]
Sorry about that, due to a failed image build, the release has been rolled back to 0.6.2.

**Comment by ZaiQi-zq** [comment]
I can pull it again now, right?
