### ISSUE TITLE
嵌入花费问题

### ISSUE THREAD

**Issue by H-Sen1** [langgenius/dify#339]
哈喽，如我我要是导入一个数据量很大的数据集然后选择高质量索引模式，显示embedding的tokens花费要两刀，请问我在对话时每次命中该数据集然后从其中获取答案都需要两刀的花费吗？还是说我只有在一开始导入的时候花费两刀呢？每次对话显示的tokens消耗就是总tokens花费吗？   我知道这是一个很小白的问题，望解答！

**Comment by Jackerry-H** [comment]
应该是这样：在文档首次上传使用OpenAiEmbedding的时候token花费是2$；后续在对话中如果命中了该数据集，这时会把命中的数据内容添加到对话的问题
上下文中，调用OpenAi的接口，这个对话上显示的token消耗就是这个问题及产生答案的token消耗。
