### ISSUE TITLE
MILVUS_DATABASE has no effect, it still use default milvus database.

### ISSUE THREAD

**Issue by kerlion** [langgenius/dify#3391]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Set Docker ENV: MILVUS_DATABASE: **difydb**
2. clean up all docker volumnes
3. drop all collections in Milvus database.
4. pull docker image 0.61
5. startup all containers
6. create new knowlege and upload files
7. check Milvus database, vectors are still created in default database.

### ✔️ Expected Behavior

Create vectors in **difydb** database.

### ❌ Actual Behavior

Created vectors still in **default** database.

**Comment by crazywoola** [comment]
You
