### ISSUE TITLE
The application type “workflow orchestration” has several issues.

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#3396]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- When the next node after “Knowledge Retrieval” is “LLM”, it is necessary to add a USER message for “LLM”. Otherwise, an error will occur. 
- The “Dialogue Opening” feature is not enabled successfully. 
- After “Quotation and Attribution” is enabled, the source of the quote cannot be displayed in the dialogue information. 

![111](https://github.com/langgenius/dify/assets/21255047/2f9901ef-5156-4da3-b648-3ac34906071f)

![112](https://github.com/langgenius/dify/assets/21255047/3c62d7ae-a2fc-46c5-b31c-014a35495ebf)

**Comment by zxhlyh** [comment]
Have you published your app?

**Comment by andylzming** [comment]
> Have you published your app?

yes

**Comment by crazywoola** [comment]
Please upgrade to latest one to see if this persists.
