### ISSUE TITLE
Workflow LLM node Bedrock-Claude3 model compatibility issue 

### ISSUE THREAD

**Issue by lyg5597122** [langgenius/dify#3397]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

The same workflow and prompt word, when LLM node model selects gpt, it is normal. When selecting Claude3-Sonnet model, an error is reported: Node LLM run failed: [bedrock] Error: Error code: 400 - {'message': 'Malformed input request: #: subject must not be valid against schema {"required": ["messages"]} #/messages: expected minimum item count: 1, found: 0, please reformat your input and try again.'} --- The issue exists in both Private Deployment (docker-compose) env and Cloud SaaS env testing .
![img_v3_029s_2d57c35c-84b1-4385-8ebe-22e0c4891e1h](https://github.com/langgenius/dify/assets/30303982/65d8be31-10f6-4fbe-88ff-13da87401deb)
![img_v3_029s_1e61b378-2c31-4bdf-ad27-c4ad8c46b2eh](https://github.com/langgenius/dify/assets/30303982/95d3a36f-4862-425f-a0c6-7fb228527964)
![img_v3_029s_c95be885-6700-4fc0-9de5-c2475c66dabh](https://github.com/langgenius/dify/assets/30303982/c9878253-e8a8-45c9-902e-dd4acc4bbf89)
![img_v3_029s_5b6c2a92-6afa-42a8-94d8-2695cdd7682h](https://github.com/langgenius/dify/assets/30303982/631b0143-af29-4a0e-a1ab-1791a73e920a)

### ✔️ Expected Behavior

LLM nodes can use the Claude3 model to process tasks

**Comment by guchenhe** [comment]
claude API has different requirements in how it want message structured compared to OpenAI. I believe it's asking for a non-empty user message here - selecting USER prompt instead of SYSTEM prompt should make the API happy here.

**Comment by lyg5597122** [comment]
> claude API has different requirements in how it want message structured compared to OpenAI. I believe it's asking for a non-empty user message here - selecting USER prompt instead of SYSTEM prompt should make the API happy here.

This is great. Based on your prompt, I modified the LLM node and moved the prompt word to USER. Now it works normally.  It seems that the loading different models are different. Can you add some explanations in the official documentation? I think this can help more people like me. Thank you again!

**Comment by dashjim** [comment]
It should be a bug. Dify allows users to switch the model for an existing workflow. But it breaks due to the model compliance. The differences between models should be mitigated by the lower layer.
