### ISSUE TITLE
无法添加 Azure OpenAI 信息

### ISSUE THREAD

**Issue by chllei** [langgenius/dify#34]
网页版 https://cloud.dify.ai/ 中，`设置 - 模型供应商 - Azure OpenAI Service` 里按要求填完信息后，点 `保存` 显示保存成功，但界面仍是未添加服务的状态，app 里调用模型时仍然走的免费的 `托管 OpenAI` 的部分。

**Comment by takatost** [comment]
#33

**Comment by chllei** [comment]
这里能不能考虑顺便也支持一下 azure openai 的 embedding 模型？当前的 azure openai 信息只支持提供一个模型的信息

**Comment by takatost** [comment]
已支持临时方案，注意事项见最后一条：
https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq
