### ISSUE TITLE
[bug] Question Classifier working wrong in the workflow process

### ISSUE THREAD

**Issue by jiacheo** [langgenius/dify#3410]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. create a workflow from template by the name of 'Customer Review Analysis Workflow'
2. Run it in the studio
3. input a nagetive review text such like :'Bad experience of refunding'
4. then submit the text and see the workflow processing diagram
5. Check the trace, can  find that the LLM classfier the question as a 'Negative review' but the next step it goes to the 'Class1' (Positive review) brunch, this act a wrong brunch choosen.

<img width="1212" alt="image" src="https://github.com/langgenius/dify/assets/1650931/13ca32e0-2ff5-4584-bb20-f5428ed0b634">

### ✔️ Expected Behavior

Understand and go to the right brunch in the question classifier.

**Comment by crazywoola** [comment]
Please attach the exported yml file as well. @jiacheo

**Comment by jiacheo** [comment]
@crazywoola 
The DSL file here: 
[Customer Review Analysis Workflow .yml.txt](https://github.com/langgenius/dify/files/14955579/Customer.Review.Analysis.Workflow.yml.txt)

**Comment by crazywoola** [comment]
@JohnJyong Please take a look at this.

**Comment by Avuja** [comment]
What's the Classification tracing look like? After the most recent update my classification seems to have some hard coded customer service related prompts that I can't get rid of, wondering if maybe they're also being applied and messing things up (I think that's what's happening to my deployment, also having problems now)

I don't think these prompts were there before and not sure where they're coming from but they're always in my question classification tracing even in a workflow unrelated to customers - maybe unrelated and I'm just missing something figured would chime in though, here's what keeps getting added to my actual context:

      "role": "user",
      "text": "\n    { \"input_text\": [\"I recently had a great experience with your company. The service was prompt and the staff was very friendly.\"],\n    \"categories\": [\"Customer Service, Satisfaction, Sales, Product\"],\n    \"classification_instructions\": [\"classify the text based on the feedback provided by customer\"]}```JSON\n",
      "files": []
    },
    {
      "role": "assistant",
      "text": "\n    {\"keywords\": [\"recently\", \"great experience\", \"company\", \"service\", \"prompt\", \"staff\", \"friendly\"],\n    \"categories\": [\"Customer Service\"]}```\n",
      "files": []
    },
    {
      "role": "user",
      "text": "\n    {\"input_text\": [\"bad service, slow to bring the food\"],\n    \"categories\": [\"Food Quality, Experience, Price\" ], \n    \"classification_instructions\": []}```JSON\n",
      "files": []
    },
    {
      "role": "assistant",
      "text": "\n    {\"keywords\": [\"bad service\", \"slow\", \"food\", \"tip\", \"terrible\", \"waitresses\"],\n    \"categories\": [\"Experience\"\"]}```\n",
      "files": []
    },

**Comment by YidaHu** [comment]
> @crazywoola The DSL file here: [Customer Review Analysis Workflow .yml.txt](https://github.com/langgenius/dify/files/14955579/Customer.Review.Analysis.Workflow.yml.txt)

@jiacheo I noticed that you have an extra blank space in this category, resulting in conditions that do not match.

<img width="650" alt="image" src="https://github.com/langgenius/dify/assets/13404367/fc13e3dd-a058-48aa-bf55-b6bd5921e84b">

@crazywoola Of course, it is true that LLM output may also have problems, I have submitted PR #3449

**Comment by jiacheo** [comment]
> > @crazywoola The DSL file here: [Customer Review Analysis Workflow .yml.txt](https://github.com/langgenius/dify/files/14955579/Customer.Review.Analysis.Workflow.yml.txt)
> 
> @jiacheo I noticed that you have an extra blank space in this category, resulting in conditions that do not match.
> 
> <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/13404367/322210028-fc13e3dd-a058-48aa-bf55-b6bd5921e84b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjA0MTAsIm5iZiI6MTcxMzE2MDExMCwicGF0aCI6Ii8xMzQwNDM2Ny8zMjIyMTAwMjgtZmMxM2UzZGQtYTA1OC00OGFhLWJmNTUtYjZiZDU5MjFlODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjOWUwOGYyNTA0MjUwOGM1NTNlMGYyNzZiYTMyZDk1YzI0ZWYxYmQ5ZDE4MmVjMzY1YzEyY2Q1MThhMjQ3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WV4IqmqrTsdqPw2TPTDYwHUDYGwyP7kXbr2HcTM3l-k">
> @crazywoola Of course, it is true that LLM output may also have problems, I have submitted PR #3449

@YidaHu Wow! You must have golden eyes! After delete the extra space, it works fine now. (should we have a trim() before we choose brunches?)

**Comment by YidaHu** [comment]
> > > @crazywoola The DSL file here: [Customer Review Analysis Workflow .yml.txt](https://github.com/langgenius/dify/files/14955579/Customer.Review.Analysis.Workflow.yml.txt)
> > 
> > 
> > @jiacheo I noticed that you have an extra blank space in this category, resulting in conditions that do not match.
> > <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/13404367/322210028-fc13e3dd-a058-48aa-bf55-b6bd5921e84b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjA0MTAsIm5iZiI6MTcxMzE2MDExMCwicGF0aCI6Ii8xMzQwNDM2Ny8zMjIyMTAwMjgtZmMxM2UzZGQtYTA1OC00OGFhLWJmNTUtYjZiZDU5MjFlODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjOWUwOGYyNTA0MjUwOGM1NTNlMGYyNzZiYTMyZDk1YzI0ZWYxYmQ5ZDE4MmVjMzY1YzEyY2Q1MThhMjQ3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WV4IqmqrTsdqPw2TPTDYwHUDYGwyP7kXbr2HcTM3l-k">
> > @crazywoola Of course, it is true that LLM output may also have problems, I have submitted PR #3449
> 
> @YidaHu Wow! You must have golden eyes! After delete the extra space, it works fine now. (should we have a trim() before we choose brunches?)

@jiacheo I don't think trim() is necessary. The service should not modify user input. 
Of course that's what I think.

**Comment by jiacheo** [comment]
I would close this issue now.

**Comment by YidaHu** [comment]
> I would close this issue now.
> 
> Btw, I found this template from the cloud version( cloud.dify.ai ) also have the same 'blank space' behind the 'Negetive review' brunch, maybe you can notify the cloud platform team to update this template. @YidaHu

@crazywoola @JohnJyong When language='en-US', there is an error in the template "Customer Review Analysis Workflow", Question Classifier Node -> Category ->  Negative review (space here).
This results in an inability to properly execute the workflow.

I found a pull app template from https://tmpl.dify.ai' and I can't fix it.

<img width="1494" alt="image" src="https://github.com/langgenius/dify/assets/13404367/061ad113-0c2d-4990-b842-c654cedd035f">

**Comment by prhost** [comment]
> What's the Classification tracing look like? After the most recent update my classification seems to have some hard coded customer service related prompts that I can't get rid of, wondering if maybe they're also being applied and messing things up (I think that's what's happening to my deployment, also having problems now)
> 
> I don't think these prompts were there before and not sure where they're coming from but they're always in my question classification tracing even in a workflow unrelated to customers - maybe unrelated and I'm just missing something figured would chime in though, here's what keeps getting added to my actual context:
> 
> ```
>   "role": "user",
>   "text": "\n    { \"input_text\": [\"I recently had a great experience with your company. The service was prompt and the staff was very friendly.\"],\n    \"categories\": [\"Customer Service, Satisfaction, Sales, Product\"],\n    \"classification_instructions\": [\"classify the text based on the feedback provided by customer\"]}```JSON\n",
>   "files": []
> },
> {
>   "role": "assistant",
>   "text": "\n    {\"keywords\": [\"recently\", \"great experience\", \"company\", \"service\", \"prompt\", \"staff\", \"friendly\"],\n    \"categories\": [\"Customer Service\"]}```\n",
>   "files": []
> },
> {
>   "role": "user",
>   "text": "\n    {\"input_text\": [\"bad service, slow to bring the food\"],\n    \"categories\": [\"Food Quality, Experience, Price\" ], \n    \"classification_instructions\": []}```JSON\n",
>   "files": []
> },
> {
>   "role": "assistant",
>   "text": "\n    {\"keywords\": [\"bad service\", \"slow\", \"food\", \"tip\", \"terrible\", \"waitresses\"],\n    \"categories\": [\"Experience\"\"]}```\n",
>   "files": []
> },
> ```

I also wanted to know what these template prompts are that go along with the instruction, this is a problem
