### ISSUE TITLE
API_TOOL_DEFAULT_TIMEOUT need increase,or add to env 

### ISSUE THREAD

**Issue by harryhan1989** [langgenius/dify#3413]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

my custom tool need long request, but the timeout can not customize

**Comment by Yeuoly** [comment]
Looks reasonable, I will take it.
