### ISSUE TITLE
feedback add content,delete message

### ISSUE THREAD

**Issue by johnduan888** [langgenius/dify#3427]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

The current feedback interface may not capture specific details on what users like or dislike about the product.

### 2. Describe the feature you'd like to see

Add content to the feedback interface (add content request parameters to the interface, and add display content to the web)
Added deletion message interface (pass message_id, delete message, in order to realize the regeneration function)

### 3. How will this feature improve your workflow or experience?

This feature will enhance the quality of feedback received, providing more actionable insights for improving the product and user experience.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Do you mean the feature request template? 
Actually we suggest using https://github.com/langgenius/dify/discussions/categories/feedbacks to submit a feedback.

**Comment by dq7532183** [comment]
1. Yes, feedback in the console. PostgreSQL table message_feedbacks has a content field, but the API (/messages/: message_id/feedbacks) does not have a content parameter
2. I need to regenerate, so I need an API to delete messages.

**Comment by dq7532183** [comment]
Add an API to delete messages
delete  /message/:message_id

we can first call the delete message interface and then call the chat message interface to achieve the regeneration function
