### ISSUE TITLE
自定义外部向量库

### ISSUE THREAD

**Issue by groobyming** [langgenius/dify#343]
你好，如何指定外部向量库为qdrant，有没有文档参考

**Comment by takatost** [comment]
```
# Vector database configuration, support: weaviate, qdrant
VECTOR_STORE=qdrant

# Qdrant configuration
QDRANT_URL=https://your-qdrant-cluster-url.qdrant.io
QDRANT_API_KEY=your-qdrant-api-key
```

**Comment by groobyming** [comment]
你好，请问下这里只能使用qdrant的云服务，不能使用本地qdrant吗

**Comment by takatost** [comment]
Cloud and local configs are the same i think. is there anything that can't be configured?

**Comment by groobyming** [comment]
你好，我这边是本地用docker起的一个qdrant服务，看了下相关的文档，没有发现 QDRANT_API_KEY 的生成方式，所以我只用配置如下两项就可以了吗
# Vector database configuration, support: weaviate, qdrant
VECTOR_STORE=qdrant

# Qdrant configuration
QDRANT_URL=https://your-qdrant-cluster-url.qdrant.io

**Comment by groobyming** [comment]
@sepaci 测试失败，直接改这两个会导致服务启动失败，但是又没有报错内容

**Comment by JohnJyong** [comment]
May I ask whether your qdrant is using the cloud version or the local version？

**Comment by JohnJyong** [comment]
![image](https://github.com/langgenius/dify/assets/76649700/e87119ea-963d-4eab-bdb5-199dd994125d)
you can generate the api key in your cloud version

**Comment by JohnJyong** [comment]
for local devlop, you can try below
![image](https://github.com/langgenius/dify/assets/76649700/82f9b9df-0929-4a7e-87dc-d25c0db6c516)
