### ISSUE TITLE
Add workflow multitasking parallel support

### ISSUE THREAD

**Issue by richards199999** [langgenius/dify#3432]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When dealing with a flow of models, the speed and performance would decreased. So I hope there would be some solution around it.

### 2. Describe the feature you'd like to see

I hope the workflow could support something like the pic, which can reduce the time and performance.
![image](https://github.com/langgenius/dify/assets/142148415/8c9117a5-4e09-444f-8201-e01ab1c9c11e)

Currently, the one is kinda slow, since it need to wait for each model to response..
![image](https://github.com/langgenius/dify/assets/142148415/61e8b44d-b0e2-475b-92c5-5559ef6e116c)

### 3. How will this feature improve your workflow or experience?

It would make the experience much much faster and smoother.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Parallel in our roadmap, currently we are prioritizing resolving the bottlenecks in the process. Thanks for the suggestion! 😀

**Comment by richards199999** [comment]
sure, waiting for your iterations!🤗
