### ISSUE TITLE
docker compose deploy no have wrokflow？

### ISSUE THREAD

**Issue by loks666** [langgenius/dify#3440]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

![image](https://github.com/langgenius/dify/assets/33214035/260d8b21-9509-4e0f-a1ce-d1c98b42d7d3)
why my page only have assistant and text generate？
but in the https://cloud.dify.ai/，pages is have others option？for example like a Agent and wordflow？
![image](https://github.com/langgenius/dify/assets/33214035/e6325d81-d78e-4271-a493-079e19ef4646)
I wanna know this question just is the difference between open source and commercial？or my deploy method has some question?

**Comment by crazywoola** [comment]
Suggest use `docker ps` to see if you have downloaded the right image, which should be v0.6.2.  If not, try to read the release logs to upgrade from the older version.

**Comment by loks666** [comment]
fixed,thanks you~
