### ISSUE TITLE
Retival Module: Model gpt-3.5-turbo credentials is not initialized.

### ISSUE THREAD

**Issue by dashjim** [langgenius/dify#3451]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1 

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

This bug was reported before as Bug 3271, but it was closed with an invalid comment. The following is my reproduce and the knowledge base use keywords retrieval. It should not require LLM at all. So the error message is misleading and the solution provided in Bug 3271 didn't work.

<img width="1108" alt="Screenshot 2024-04-13 at 23 26 11" src="https://github.com/langgenius/dify/assets/271445/73828118-c62c-441a-ae5b-1dac9234e6da">
<img width="800" alt="Screenshot 2024-04-13 at 23 26 27" src="https://github.com/langgenius/dify/assets/271445/ad559329-5107-4720-9572-2f80d0ac0512">

### ✔️ Expected Behavior

Retrieval module to work properly.

### ❌ Actual Behavior

Confusing error.

**Comment by crazywoola** [comment]
Please set the default reasoning model in settings -> model providers.

**Comment by YidaHu** [comment]
@crazywoola I have also encountered this problem, setting the default model, occasionally.

**Comment by qiansc** [comment]
I also encountered the same problem. When I copied the DSL and imported it, the retrieval node could not complete the model switch. You can try exporting the DSL, modifying the configuration of the retrieval node, and then importing it back to solve the problem. At present, there is no interface to adjust this setting for the retrieval node.

**Comment by sinopec** [comment]
The same problem in 0.6.5 . 
I am confused as to why it is not possible to modify the model or retrieval configurations through the web UI, leading to this issue.

I dont want to modify the source code， If possible

**Comment by qiudywzh** [comment]
If you create a workflow from template, the "model name" is binded with the template, which is "gpt-3.5-turbo" here, so just recreate the nodes by yourself could solve this problem.
