### ISSUE TITLE
dify don't support one-api at present?

### ISSUE THREAD

**Issue by loks666** [langgenius/dify#3456]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I use one api deploied some models,I wish could calling myself models,but I found dify seem unsupport add customer model,so I wanna verify dify Specifies whether to configure user-defined models?

### ✔️ Expected Behavior

Large custom models can be added,support one api

### ❌ Actual Behavior

can't add user-defined models

**Comment by crazywoola** [comment]
We have several users succeed in using one api. So it's supported in our product.

**Comment by loks666** [comment]
but I don't find add one api path，could tell me how to do it?
