### ISSUE TITLE
not able to select reference in Answer Node

### ISSUE THREAD

**Issue by kkailaasa** [langgenius/dify#3462]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/138176796/19ffea14-877a-41e9-883a-6b737bbbe661)
Not able to click on any of the options under the Answer Node or even type in the option. I have tried in cloud and self hosted Docker both are the same.

### ✔️ Expected Behavior

I should be able to select the Options in the Answer Node after I put in '/' but click does not work on it

### ❌ Actual Behavior

I am not able to select the option after '/'

**Comment by crazywoola** [comment]
Tested in cloud version.  
<img width="1007" alt="image" src="https://github.com/langgenius/dify/assets/100913391/67ba4185-3f57-4b38-9c70-37018fc6876e">
Cant repro. Maybe you can attach the yml file here.

**Comment by kkailaasa** [comment]
I think that the Issue is with where you click. I am clicking on the {x} in the drop Down and only then it works.

**Comment by kkailaasa** [comment]
Thank you for your Prompt response

**Comment by crazywoola** [comment]
> I think that the Issue is with where you click. I am clicking on the {x} in the drop Down and only then it works.

Actually the whole option is clickable. I've tested it before.
