### ISSUE TITLE
使用移动端调用dify api 且使用 stream模式，似乎会丢掉部分内容

### ISSUE THREAD

**Issue by zangqilong198812** [langgenius/dify#347]
比如，我的问题“李白是谁”
回答总会丢掉‘李’，导致回答是这样的
"白是中国唐代的著名诗人xxxx"
我试了多个提问均有这样的问题，比如我问“who is kobe”
回答是"obe is American basketball player"
少了K

**Comment by crazywoola** [comment]
Can you provide  detailed logs of api response?
