### ISSUE TITLE
Expand image upload capabilities and add document type file uploads, such as PDF

### ISSUE THREAD

**Issue by a5223594** [langgenius/dify#3480]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am developing a file text parsing tool, which parses and passes it to the large model as the context. However, the existing image upload capability cannot meet the requirements

### 2. Describe the feature you'd like to see

Expand the image upload function, support non image types for uploading, and allow users to choose by themselves. It is not necessary to transfer files to LLM, but also to support transfer to tools. I have temporarily implemented this in the workflow, but other agents have not yet processed it

### 3. How will this feature improve your workflow or experience?

File uploading will enhance platform capabilities, similar to Kimi's file reading, and to a certain extent, better user experience than a fixed knowledge base

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by auok9527** [comment]
Hello, I am very interested in your file upload implementation in the workflow, can you reveal the specific implementation details? thx @a5223594

**Comment by jqhr** [comment]
Maybe similar to this issue https://github.com/langgenius/dify/issues/2501
