### ISSUE TITLE
Set the embbeding model at the knowlege level.

### ISSUE THREAD

**Issue by kerlion** [langgenius/dify#3485]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I want to create a knowlege, I need to:
- Go to system models, select the current embeding model
- Create the new knowlege.
- When I want to create a new knowlege with differrent embedding model.
- I need to change the curent system embedding model.
- Create another knowlege , but the old one is still using the old embedding model.

It does not make sense, it would be better to select embedding module at the knowlege level. Same as rerank model.

### 2. Describe the feature you'd like to see

Set the embbeding model at the knowlege level.

### 3. How will this feature improve your workflow or experience?

It makes it is more reasonable.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This should be included in #3342
