### ISSUE TITLE
Error when pressing Add variable in prompt interface (workflow node)

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#3489]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.2 EMERGENCY FIX

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Press the button "Insert Variable" inside the prompt interface on a node:
![CleanShot 2024-04-15 at 09 59 18](https://github.com/langgenius/dify/assets/119136210/268ba98c-ce98-4435-a2a7-9f3901ef274e)

### ✔️ Expected Behavior

Add variable, just as when you write / in the prompt.

### ❌ Actual Behavior

Error: rootNode.append: Only element or decorator nodes can be appended to the root node

app/components/base/prompt-editor/plugins/update-block.tsx (32:21) @ eval

  30 | editor.update(() => {
  31 |   const textNode = new CustomTextNode('/')
> 32 |   $insertNodes([textNode])
     |               ^
  33 |
  34 |   editor.dispatchCommand(CLEAR_HIDE_MENU_TIMEOUT, undefined)
  35 | })

**Comment by crazywoola** [comment]
@dosubot Give a fix to this error
