### ISSUE TITLE
An accident occurred to create the knowledge base

### ISSUE THREAD

**Issue by jingghe** [langgenius/dify#3492]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

v0.62

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Request failure, internal error when selecting alert high quality index mode when creating a new knowledge base
![image](https://github.com/langgenius/dify/assets/18381394/f78f9d36-614b-4518-8138-53fde8e0243b)
![image](https://github.com/langgenius/dify/assets/18381394/4b73d3f3-f12e-41f6-b17d-f24e25841d2a)
![image](https://github.com/langgenius/dify/assets/18381394/0fc83d11-7fa3-4111-a328-2ba0ca798ce2)
![image](https://github.com/langgenius/dify/assets/18381394/6ad8a19a-ba51-450f-81f0-36a03ebbeb81)

**Comment by JohnJyong** [comment]
pls provide the embedding model name , thanks @jingghe
