### ISSUE TITLE
Issue with React Error #185 on Preview Page

### ISSUE THREAD

**Issue by chalitbkb** [langgenius/dify#3498]
### Self Checks

- [x] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.610

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I encountered an issue while testing on the preview page at https://udify.app/chat/xxx. Below is the error message I received: "Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

This issue seems to occur occasionally, and it happens while the AI is in the process of generating a response on the streaming webpage. I'm not entirely sure what causes it, but it might be related to the length of the character limit.

The error appears to be a React-specific issue, as indicated by the error message. It suggests visiting the provided link for more information or using the non-minified development environment to get more detailed error messages and warnings.

Thank you..

### ✔️ Expected Behavior

Text is beeing generated normally

### ❌ Actual Behavior

As the messages are being generated on the frontend in a streaming manner, an error notification appears immediately as the character count begins to rise. Subsequently, everything is cleared and disappears. It seems that this issue occurs when the data size starts to increase, affecting both the testing in the "Studio" and the deployment via the "Public URL."

![image](https://github.com/langgenius/dify/assets/32437546/a5491943-5d55-4c8b-8540-75a8d925875f)

**Comment by chalitguza** [comment]
**This issue persists, please address it. It's frustrating to encounter this problem frequently. !!!!! **

**Comment by angular-moon** [comment]
I reproduced this problem when using ollama llama-3.
request:
```json
{"response_mode":"streaming","conversation_id":"2f07aee2-7c2b-4875-9e17-0faea0ecf0c9","query":"在 react hooks 中创建SSE的长连接，如果在不重新执行 effect 销毁连接和重新创建的前提下更新事件响应的执行方法","inputs":{},"model_config":{"pre_prompt":"作为一位程序员，你可能会遇到各种各样的编程问题。你的任务是利用大语言模型来解决编程相关的问题。你需要确保你的解决方案是清晰、准确、易于理解的，并且遵循最佳的编程实践。在提出问题时，请尽可能提供详细的上下文和相关信息，以便模型能够更好地理解你的问题。你可能会被要求提供代码示例、错误信息、需求等。你将不会被要求执行需要访问私有或敏感信息的任务。你将不会被要求执行可能违反伦理或法律规定的任务。请明确你的问题，以便我们能够为你提供最佳的解决方案。","prompt_type":"simple","chat_prompt_config":{},"completion_prompt_config":{},"user_input_form":[],"dataset_query_variable":"","opening_statement":"您好，我是您的人工智能编程助手。我可以在您遇到编程问题时提供帮助，并为您提供清晰、准确、易于理解的解决方案。","more_like_this":{"enabled":false},"suggested_questions":[],"suggested_questions_after_answer":{"enabled":false},"text_to_speech":{"enabled":false},"speech_to_text":{"enabled":false},"retriever_resource":{"enabled":false},"sensitive_word_avoidance":{"enabled":false,"type":"","configs":[]},"agent_mode":{"enabled":false,"max_iteration":5,"strategy":"react","tools":[]},"dataset_configs":{"retrieval_model":"single","datasets":{"datasets":[]}},"file_upload":{"image":{"enabled":false,"number_limits":3,"detail":"high","transfer_methods":["remote_url","local_file"]}},"annotation_reply":{"enabled":false},"supportAnnotation":true,"appId":"75e90efb-7fc5-4b33-8d83-3df643c21d83","supportCitationHitInfo":true,"model":{"provider":"ollama","name":"llama3","mode":"chat","completion_params":{"temperature":0.1,"top_p":0.9,"num_predict":512,"num_ctx":2048}}}}
```

response:
[response.txt](https://github.com/langgenius/dify/files/15051223/response.txt)

**Comment by jindanny** [comment]
同样的问题，在LLM输出代码后，会出现这个问题，必现
