### ISSUE TITLE
Bing search bug

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3503]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I always encounter invoke url error when using bing search.

So I dig into the source code. The search setting is as below:

<img width="417" alt="image" src="https://github.com/langgenius/dify/assets/12423206/f2d745f4-be0b-4466-8433-eef754e40121">

But the real thing is the filters are all setting as true, as below

<img width="401" alt="image" src="https://github.com/langgenius/dify/assets/12423206/12adf692-d4ff-4730-89ca-9c53ded99009">

So the backend request url is: 
```
https://api.bing.microsoft.com/v7.0/search?q={query_string}&mkt=en-US&count=5&responseFilter=Computation,Entities,News, RelatedSearches,WebPages
```

So if all the filters are true, bing will raise a error: 403 forbidden.

**Comment by Yeuoly** [comment]
Pls check your Bing Search subscription plan, for different subscription plans, different filters are permitted, I have tested a basic plan, which can only support webpage search.

**Comment by kaojistream** [comment]
+1, I also encountered same problem
![img_v3_02c1_4b298b0d-1f0d-40f2-ba47-a78499991d9g](https://github.com/langgenius/dify/assets/15082023/e609bc04-cf0a-436f-9f0b-aa56e7df72a7)

**Comment by kaojistream** [comment]
The temporary solution was that I switched to a different subscription group
