### ISSUE TITLE
request timeout after 60s when use blocking mode with ollama

### ISSUE THREAD

**Issue by jjzhoujun** [langgenius/dify#3523]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.2 EMERGENCY FIX

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I use dify to link my local ollama model. When I use  'blocking' response_model to request dify api, I occasionally a "Read timed out" when the content is long. This error doesn't occur if I shorten the content.
I had check the dify's nginx proxy.conf timeout configuration, it's 3600s, but why am I still encountering a timeout at 60s ? Is it settting in the code ?

### ✔️ Expected Behavior

When I use blocking mode , modify timeout=3600s, it should response normally .

### ❌ Actual Behavior

{'code': 'completion_request_error', 'message': "[ollama] Connection Error, HTTPConnectionPool(host='192.168.1.4', port=11434): Read timed out. (read timeout=60)", 'status': 400}

**Comment by takatost** [comment]
fixed in #3538
