### ISSUE TITLE
Extend API support for LocalAI

### ISSUE THREAD

**Issue by thiner** [langgenius/dify#3524]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

![image](https://github.com/langgenius/dify/assets/1897227/34e5b41f-4b29-4bb7-80a7-aaf07d39510b)
Dify recognizes LocalAI's LLM and embedding features only currently. But LocalAI supports many other features as well. See below screenshot.
![image](https://github.com/langgenius/dify/assets/1897227/6149eef2-36b9-44bf-aa8b-a88fc33b3746)
It supports `TTS`, `Speach-2-text`, `text-2-image` and `image-2-image`.

### 2. Describe the feature you'd like to see

Please allow choose LocalAI as the backend for `TTS`, `STT`, `text-2-image` and `image-to-image` features.

### 3. How will this feature improve your workflow or experience?

I use LocalAI as the all-in-one LLM backend for vary models, extends the support for LocalAI simplifies the maintenance work.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Hello there,
Feel free to contribute on this feature. You can find the guides here => https://github.com/langgenius/dify/blob/fd5c45ae104ae54ebd29906fda081d517ce4a36a/api/core/model_runtime/README.md#L1
Or you can search the merged pull requests to see if those help.
