### ISSUE TITLE
Adding knowledge throws error (PDF)

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#3535]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Adding new knowledge throws error and quitting api server.
I can't figure out if this is an error on my local machine as the same PDF can be upload to Dify Cloud. But it haven't happened until version 0.6.3

### ✔️ Expected Behavior

Upload PDF and embed it to vector db.the 

### ❌ Actual Behavior

`FO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:31] "POST /console/api/files/upload?source=datasets HTTP/1.1" 201 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "OPTIONS /console/api/workspaces/current/models/model-types/rerank HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "OPTIONS /console/api/workspaces/current/default-model?model_type=rerank HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "OPTIONS /console/api/datasets/process-rule HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "OPTIONS /console/api/datasets/indexing-estimate HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "OPTIONS /console/api/datasets/process-rule HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "OPTIONS /console/api/datasets/indexing-estimate HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "GET /console/api/datasets/process-rule HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "GET /console/api/workspaces/current/default-model?model_type=rerank HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "GET /console/api/datasets/process-rule HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "GET /console/api/workspaces/current/model-providers/cohere/icon_small/en_US?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGM0ZDRjMjUtNGYyMC00YWM0LTlkZDMtYWJlMzI3NTkyMmNjIiwiZXhwIjoxNzE1ODczMjgyLCJpc3MiOiJDTE9VRCIsInN1YiI6IkNvbnNvbGUgQVBJIFBhc3Nwb3J0In0.dZGDQXBOtu6yR5F2Z7h85KJbmVdf1KYCyqzNRC2GGmE HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2024 21:35:38] "GET /console/api/workspaces/current/models/model-types/rerank HTTP/1.1" 200 -
python(2929,0x2d8f07000) malloc: *** error for object 0x1272cdb08: pointer being freed was not allocated
python(2929,0x2d8f07000) malloc: *** set a breakpoint in malloc_error_break to debug`

`Unhandled Runtime Error
TypeError: Failed to fetch

Source
service/base.ts (299:17) @ fetch

  297 | }),
  298 | new Promise((resolve, reject) => {
> 299 |   globalThis.fetch(urlWithPrefix, options as RequestInit)
      |             ^
  300 |     .then((res) => {
  301 |       const resClone = res.clone()
  302 |       // Error handler`

**Comment by AndyMik90** [comment]
The error can be reproduced by having a knowledgebase with cohere reranking v3 as hybrid search. Then setting the embedding model to cohere ranking v2 in system model settings.

**Comment by JohnJyong** [comment]
I'm not sure what problem you are currently encountering. From the description, it seems that your PDF failed to be parsed into the knowledge base. However, judging from your last reply, it seems that you encountered a search error using coher reranking v3. @AndyMik90 
If it is a problem with PDF parsing, our cloud service uses the Unstructured tool. You need to configure Unstructured locally. For specific operations, please refer to our documentation.

**Comment by AndyMik90** [comment]
> I'm not sure what problem you are currently encountering. From the description, it seems that your PDF failed to be parsed into the knowledge base. However, judging from your last reply, it seems that you encountered a search error using coher reranking v3. @AndyMik90 If it is a problem with PDF parsing, our cloud service uses the Unstructured tool. You need to configure Unstructured locally. For specific operations, please refer to our documentation.

Hi JohnJyong, I have unstructured configured locally and have been working up until latest update. As I mentioned in the latest comment, it seems that the problem is happening on index-estimation where the reranking is triggered, and is a mismatch between v2 and v3 "
The error can be reproduced by having a knowledgebase with cohere reranking v3 as hybrid search. Then setting the embedding model to cohere ranking v2 in system model settings."

**Comment by JohnJyong** [comment]
<img width="1667" alt="image" src="https://github.com/langgenius/dify/assets/76649700/137401e7-591e-4762-955a-b5c5a05a6d7d">

@AndyMik90 is this model?

**Comment by AndyMik90** [comment]
> <img alt="image" width="1667" src="https://private-user-images.githubusercontent.com/76649700/323162677-137401e7-591e-4762-955a-b5c5a05a6d7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjc1MzgsIm5iZiI6MTcxMzM2NzIzOCwicGF0aCI6Ii83NjY0OTcwMC8zMjMxNjI2NzctMTM3NDAxZTctNTkxZS00NzYyLTk1NWEtYjVjNWEwNWE2ZDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE1MjAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOWQ1YzIxZmE2NDAwYmE4YTk0NGRhYTFlODg3YjEyODVjNjU4YmJhNjgyODllYWUyOGY5OTU4OTA0ODE0M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jq_AD9KEyJcdcd7g4EM_CQVu9x0TGj0v1n235-DnpKw">
> @AndyMik90 is this model?

Yes

**Comment by loganclark360** [comment]
Still an issue for me

W. Logan Clark

**Comment by stonebitsrl** [comment]
still a issue also for me. Cohere embed-multilingual-v3.0 cannot be used (I tried mostly with PDF documents and I have configured Milvus DB standalone). Selecting that model is causing an endless indexing process. Switching to OpenAI text-embedding-3-large is working as expected.

thanks 
loris luise
