### ISSUE TITLE
I can not  save the LLM's config (e.g.  MAX_TOKEN) in workflow  after publish   【v0.6.3】

### ISSUE THREAD

**Issue by sapipoZZZ** [langgenius/dify#3536]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I can not  save the LLM's config (e.g.  MAX_TOKEN) in workflow  after publish   【v0.6.3】

### ✔️ Expected Behavior

fix bug

**Comment by crazywoola** [comment]
Please provide more information regarding this issue? Which LLM do you use for that node. A screenshot is perferred.

**Comment by sapipoZZZ** [comment]
> Please provide more information regarding this issue? Which LLM do you use for that node. A screenshot is perferred.
Whether using GPT-4 or Qwen1.5, the setting for max tokens will be lost.

![image](https://github.com/langgenius/dify/assets/19617283/203b7fec-4586-4eda-9740-efc42ab1e70f)
![image](https://github.com/langgenius/dify/assets/19617283/66d0e9d3-5159-4dba-9278-cece1d42d140)

**Comment by upseem** [comment]
The default max-token of command-r is 128k, but the display is 4096. I modified - api/core/model_runtime/model_providers/cohere/llm/command-r.yaml and mapped it to docker. Dify can operate, but messages cannot be sent. Report an error.

![WX20240417-115224](https://github.com/langgenius/dify/assets/124853686/d71219fd-4a24-424d-a511-1454faa9f200)
![max-token](https://github.com/langgenius/dify/assets/124853686/ab594a07-1fd1-4df1-b88c-08f29cf36e3c)
![WX20240417-115121](https://github.com/langgenius/dify/assets/124853686/c10799ec-b87d-4b74-a864-f1fdd8f8802f)
![WX20240417-115224](https://github.com/langgenius/dify/assets/124853686/5f0ab00d-04c5-4cb8-bdce-0f291291f0d2)

**Comment by upseem** [comment]
![WX20240417-115224](https://github.com/langgenius/dify/assets/124853686/5c4714fc-1cd8-49fe-86ca-d734f52568f6)

**Comment by upseem** [comment]
![WX20240417-115151](https://github.com/langgenius/dify/assets/124853686/4d2233fa-0c6d-40f8-8eed-2fe941a6f81a)

**Comment by Yeuoly** [comment]
> ![WX20240417-115151](https://private-user-images.githubusercontent.com/124853686/323072578-4d2233fa-0c6d-40f8-8eed-2fe941a6f81a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMjkzOTcsIm5iZiI6MTcxMzMyOTA5NywicGF0aCI6Ii8xMjQ4NTM2ODYvMzIzMDcyNTc4LTRkMjIzM2ZhLTBjNmQtNDBmOC04ZWVkLTJmZTk0MWE2ZjgxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwNDQ0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTUxNDI3YjUxZmY0ODAxYjZhZWFlYTcwMmJiNTQxYjI3OWQxNzhhNTE0YTg5MzllYjk4MGViZGE5YWVlMjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zKKFlf_ev85bQbonRCmFb48dL-ghCwi1TWOUT2WrhCQ)

`Max tokens` is different from `context_size`, the first one take care of "at most how many tokens the model could output", and the second one means "how many tokens the model could accept as messages", the `max_tokens` is actually 4000, that's why you got this error.

**Comment by Yeuoly** [comment]
> > Please provide more information regarding this issue? Which LLM do you use for that node. A screenshot is perferred.
> > Whether using GPT-4 or Qwen1.5, the setting for max tokens will be lost.
> 
> ![image](https://private-user-images.githubusercontent.com/19617283/323055682-203b7fec-4586-4eda-9740-efc42ab1e70f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMjY0MDcsIm5iZiI6MTcxMzMyNjEwNywicGF0aCI6Ii8xOTYxNzI4My8zMjMwNTU2ODItMjAzYjdmZWMtNDU4Ni00ZWRhLTk3NDAtZWZjNDJhYjFlNzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDAzNTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNzQ2ZjBjZjdjNzJlMDZjNjY2ZThhNTZiYzA5Njc0NDgyN2NhY2U1ZWY0ZWJlMzgzOGMxYTJhNmNlN2VhOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vQD-bxzRZPdM2oYfq3tYZLtgKxoP-uOGjFKMWr6Ep6E) ![image](https://private-user-images.githubusercontent.com/19617283/323055914-66d0e9d3-5159-4dba-9278-cece1d42d140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMjY0MDcsIm5iZiI6MTcxMzMyNjEwNywicGF0aCI6Ii8xOTYxNzI4My8zMjMwNTU5MTQtNjZkMGU5ZDMtNTE1OS00ZGJhLTkyNzgtY2VjZTFkNDJkMTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDAzNTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZDM5YzFkZjliMjVlZjJjY2ZlYzA1MjdhYmViODQyMGIzNThmMDFjMzNjZjE5OGNlNmM5YjdhMmNhZWNhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MAm_MIP3x2YarDssGoK5KPCip7uBWqVAHMu-Bi_9Mzg)

I just cannot reproduce this issue, configs are saved correctly, is there any more detailed steps?
<img width="753" alt="image" src="https://github.com/langgenius/dify/assets/45712896/2c4db767-9332-423b-970e-b53628214b3f">

**Comment by upseem** [comment]
Gpt-4 turbo is a 128k context, and it is the same situation. I can only set it to 4096. This is restricted by Dify, but it is restricted by OpenAI.
![gpt-4-turbo](https://github.com/langgenius/dify/assets/124853686/0cfe05c4-5386-4e7a-b315-faf273053aef)
@Yeuoly  Please help me answer it, thank you very much.

**Comment by upseem** [comment]
This is restricted by Dify or OpenAI.

**Comment by crazywoola** [comment]
> > ![WX20240417-115151](https://private-user-images.githubusercontent.com/124853686/323072578-4d2233fa-0c6d-40f8-8eed-2fe941a6f81a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMjkzOTcsIm5iZiI6MTcxMzMyOTA5NywicGF0aCI6Ii8xMjQ4NTM2ODYvMzIzMDcyNTc4LTRkMjIzM2ZhLTBjNmQtNDBmOC04ZWVkLTJmZTk0MWE2ZjgxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwNDQ0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTUxNDI3YjUxZmY0ODAxYjZhZWFlYTcwMmJiNTQxYjI3OWQxNzhhNTE0YTg5MzllYjk4MGViZGE5YWVlMjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zKKFlf_ev85bQbonRCmFb48dL-ghCwi1TWOUT2WrhCQ)
> 
> `Max tokens` is different from `context_size`, the first one take care of "at most how many tokens the model could output", and the second one means "how many tokens the model could accept as messages", the `max_tokens` is actually 4000, that's why you got this error.

@upseem Already answered

**Comment by sapipoZZZ** [comment]
> > > Please provide more information regarding this issue? Which LLM do you use for that node. A screenshot is perferred.
> > > Whether using GPT-4 or Qwen1.5, the setting for max tokens will be lost.
> > 
> > 

In my workflow, I have 3 LLM nodes,
you can try:
step1: LLM1-->model--->change MAX_TOKENS
step2: publish--> update
step3: click LLM2's model, and switch to LLM1.   LLM1's model setting will be lost

**Comment by crazywoola** [comment]
> > > > Please provide more information regarding this issue? Which LLM do you use for that node. A screenshot is perferred.
> > > > Whether using GPT-4 or Qwen1.5, the setting for max tokens will be lost.
> 
> In my workflow, I have 3 LLM nodes, you can try: step1: LLM1-->model--->change MAX_TOKENS step2: publish--> update step3: click LLM2's model, and switch to LLM1. LLM1's model setting will be lost

Step 2

<img width="1121" alt="image" src="https://github.com/langgenius/dify/assets/100913391/4d02e59b-468c-422b-a7d3-e7d31362173c">

Step 3
<img width="1403" alt="image" src="https://github.com/langgenius/dify/assets/100913391/f66168be-7f85-4093-ab45-6fcf5221c561">

Cant repro

**Comment by sapipoZZZ** [comment]
@crazywoola I have recorded a video for you. It seems to always restore to the default LLM setting.

https://github.com/langgenius/dify/assets/19617283/5ff8367d-bf54-4a0c-88d7-61cac65bfa83

**Comment by tangxqa** [comment]
> @crazywoola I have recorded a video for you. It seems to always restore to the default LLM setting.
> 
>  2024-04-18.09-20-34.mp4

I encountered the same problem today
