### ISSUE TITLE
when editing workflow nodes name，if use delete button on keyboard to delete character, most of the time the node is deleted

### ISSUE THREAD

**Issue by KaiyoungYu** [langgenius/dify#3543]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when editing workflow nodes name，if use delete button on keyboard to delete character, most of the time the node is deleted

![image](https://github.com/langgenius/dify/assets/21034094/e676f4c7-8eed-46e2-b748-093d0131bec5)

### ✔️ Expected Behavior

only deletes character, not delete the node

### ❌ Actual Behavior

the node is deleted

**Comment by crazywoola** [comment]
We have. several fix in v0.6.2 and v0.6.3 related to shortcut keys. Please upgrade to those version to see if this persists.
