### ISSUE TITLE
In the AGENT mode, Zhipu seems to fail to process the prompt

### ISSUE THREAD

**Issue by WSDzju** [langgenius/dify#3555]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![310a50eb-d250-42a6-966d-c934bf34be52](https://github.com/langgenius/dify/assets/147698475/47bc4bd1-b535-4b10-b094-8d834a4d7cd9).

**Comment by WSDzju** [comment]
The error seems to sterm from the malfunctioning of embedding model

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)

**Comment by WSDzju** [comment]
thanks for your notice. I will try the new versions 
wangshaodong
浙江大学
***@***.***
---- Replied Message ----
***@***.***>Date05/28/2024 15:44 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [langgenius/dify] In the AGENT mode, Zhipu seems to fail to process the prompt (Issue #3555)
Please upgrade to latest version to see if this issue persists. :)
