### ISSUE TITLE
Users deleted from the workspace can still log in to Dify

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#3559]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I started the Dify service using docker and then accessed the Dify frontend through chrome. I then invite User A to my workspace via email. User A has registered an account through the invitation link and set a password. User A logs in to the Dify using the account and password set by user A and can use the Chatbot created by user A. I then removed user A from the workspace.

**It is believed that user A cannot log in to Dify. However, user A successfully logs in to Dify using the email address and password set previously.**. **And, he was entering his own workspace, not the one I had set up.
Although he cannot access my workspace, his own workspace is still stored in my volume folder. If he creates a large knowledge base, it will seriously waste my hard disk space, which is not what I want.**

### ✔️ Expected Behavior

User A is deleted from the workspace. User A cannot log in to Dify. so he doesn't waste my hardware and software resources.

### ❌ Actual Behavior

User A is deleted from the workspace. User A cant log in to Dify. so he can waste my hardware and software resources.

**Comment by liamjones-pw** [comment]
Does the PR really resolve this issue? There's still no way to delete users from a self-hosted DIFY instance as an 'Owner'.
