### ISSUE TITLE
Gemini 1.5 Pro Audio Input Support

### ISSUE THREAD

**Issue by ifsheldon** [langgenius/dify#3560]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, I'd like to input audio to Gemini 1.5 Pro

### 2. Describe the feature you'd like to see

Support audio input for Gemini 1.5 Pro

### 3. How will this feature improve your workflow or experience?

Now we don't need ASR models anymore, Gemini 1.5 Pro as I tested can understand English and Chinese speech

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by ottoradiologia** [comment]
Hi, @dosubot,

Thank you for managing the backlog. We would like to confirm that the audio input feature for Gemini 1.5 Pro is still highly relevant and important for us. We believe this enhancement would significantly improve the user workflow by eliminating the need for ASR models.

In particular, we are also interested in integrating the audio input with Whisper3 from Groq, which is multilingual and supports various languages. This feature would greatly enhance the versatility and usability of the system.

Could you please consider prioritizing this feature? We believe it would bring great value to the community and streamline the user experience.

Thank you for your attention and support.

Best regards,
Otto
