### ISSUE TITLE
Scroll inside chat window

### ISSUE THREAD

**Issue by rmmedia-pl** [langgenius/dify#3569]
### Self Checks

- [x] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

cloud

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Hi, 
I noticed a problem with the chat window when using the embedding method. When the window is opened, an additional scroll appears for the full height of the window (regardless of the browser). I noticed that it has to do with:
body, html {
    max-width: 100vw;
    overflow-x: hidden;
}

### ✔️ Expected Behavior

When we change overflow to global (overflow: hidden;) everything is ok. 
Is there a chance to correct this?

### ❌ Actual Behavior

overflow-x: hidden - it's not working well

**Comment by crazywoola** [comment]
Hello thanks for the bug catching. :)
You can open a pr for this. We are welcome to all kinds of contributions.
