### ISSUE TITLE
If llm prompt contains:`<script>`, the workflow cannot run

### ISSUE THREAD

**Issue by Akifyss** [langgenius/dify#3573]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

In the workflow mode, as long as the prompt word in llm contains: `<script>`, the workflow cannot run, hoping it can be fixed 🙏

**Comment by Yeuoly** [comment]
I cannot reproduce this issue? maybe you can share your DSL so that I can locate problems quickly, thx!

**Comment by Akifyss** [comment]
I recorded a GIF, and this should be related to this issue: #3231
![Apr-18-2024 11-45-01](https://github.com/langgenius/dify/assets/23567154/0df5419e-f0ec-4f19-aa0b-31923b08bf8a)
