### ISSUE TITLE
The code execution node in the workflow reports an error when parsing the knowledge base output result

### ISSUE THREAD

**Issue by smart-aiops** [langgenius/dify#3581]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/851243/307284ef-5c67-47c4-b092-e9d035c069a0)

### ✔️ Expected Behavior

![image](https://github.com/langgenius/dify/assets/851243/307284ef-5c67-47c4-b092-e9d035c069a0)

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/851243/307284ef-5c67-47c4-b092-e9d035c069a0)

**Comment by Yeuoly** [comment]
Could you pls provide a bit more detailed information? such as the code.

**Comment by smart-aiops** [comment]
> Could you pls provide a bit more detailed information? such as the code.

I found the cause of the problem. My knowledge base index mode is economical and "score" cannot be set. After the knowledge base search, the "score" in the output result is null, causing the subsequent code parsing node to report an error. If I select the knowledge base index mode When it is high quality, the knowledge base output result "score" is not null, and the entire process can be executed normally.

I personally suggest that when the knowledge base index mode is economical, a default value should be set for "score", or exception handling should be done for null values under code parsing node verification.

![image](https://github.com/langgenius/dify/assets/851243/79a6e048-b48f-4de7-b2c1-5243c0471273)

![image](https://github.com/langgenius/dify/assets/851243/01620c6f-4f8d-4f57-90c4-75236287d003)

![image](https://github.com/langgenius/dify/assets/851243/026edeb9-1615-4cc8-aa82-82e3bd20b57d)
