### ISSUE TITLE
cannot release a lock that's no longer owned

### ISSUE THREAD

**Issue by Billy11322** [langgenius/dify#3588]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![f661aaa2bdc19d73c08409893e5d561](https://github.com/langgenius/dify/assets/166583068/38efcad1-7e33-434c-bfaa-1c132008276b)
I'm trying to upload a txt file to build a knowledge base, but it's giving me the error: cannot release a lock that's no longer owned

### ✔️ Expected Behavior

no error

### ❌ Actual Behavior

it's giving me the error: cannot release a lock that's no longer owned

**Comment by takatost** [comment]
Is this screenshot relevant? 🤔

**Comment by Billy11322** [comment]
> Is this screenshot relevant? 🤔

I change the screenshot now. Can you see it? It is a screenshot about Dify now.

**Comment by JohnJyong** [comment]
thanks for your feedback , maybe some thread timeout caused this issue, you can retry to embedding this document  and we will optimize this issue later. @Billy11322

**Comment by Billy11322** [comment]
> thanks for your feedback , maybe some thread timeout caused this issue, you can retry to embedding this document and we will optimize this issue later. @Billy11322

thanks. if you fixed it please tell me.
but why this bug happen, I just upload a txt file. Maybe is because the txt is too big?

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)

**Comment by HaoyaoWang** [comment]
# Dify version
0.6.14

# Cloud or Self Hosted
Cloud

# Steps to reproduce
![image](https://github.com/user-attachments/assets/71ebf88d-3b16-4476-8462-80f1dba8c08d)
I'm trying to upload a xlsx file to build a knowledge base, but it's giving me the error: cannot release a lock that's no longer owned. I click retry and it's always queuing and now I can't upload any files. Please help me fix this. Thank you!
