### ISSUE TITLE
Bug:The issue with calling Zhipu AI is that in the chat assistant type, workflow orchestration is available, but errors occur when using the workflow type. 

### ISSUE THREAD

**Issue by ixujue** [langgenius/dify#3590]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The issue with the ZhiPu AI model arises when operating within the chat assistant type where workflow orchestration is functioning properly. However, errors are encountered when switching to the workflow type. Among the four available models, only one model operates correctly in the workflow type (chatglm_turbo). The other two models result in errors (glm-3-turbo, glm-4), and one model seems to be in a state of self-entertainment (glm-4v), consistently producing hallucinatory results. There are two specific error prompts that occur: "Node LLM run failed: [Zhipu] Error: Error code: 400, with error text {"error":{"code":"1214","message":"The messages parameter is illegal. Please check the document."}}. When this error appears, the functioning model remains unaffected, but selecting either of the other two models leads to the error.

![image](https://github.com/langgenius/dify/assets/48663394/48db728b-86c2-4e79-b932-f3c991c4b1ac)
**use glm-3-turbo, glm-4**
![image](https://github.com/langgenius/dify/assets/48663394/41536bb3-060c-4095-bd1c-10b9dd8377f1)
**use glm-4v**
![image](https://github.com/langgenius/dify/assets/48663394/14ece068-3423-4590-8fb4-0e8e1dffd7fe)
**use chatglm_turbo (correctly)**
![image](https://github.com/langgenius/dify/assets/48663394/92e09a38-0c66-465d-a91e-5ae1b5b840e7)

![image](https://github.com/langgenius/dify/assets/48663394/6e351ea2-4692-4968-b931-26841111b8fc)

### ✔️ Expected Behavior

All models are functioning properly.

### ❌ Actual Behavior

the four available models, only one model operates correctly in the workflow type (chatglm_turbo). The other two models result in errors (glm-3-turbo, glm-4), and one model seems to be in a state of self-entertainment (glm-4v), consistently producing hallucinatory results. There are two specific error prompts that occur: "Node LLM run failed: [Zhipu] Error: Error code: 400, with error text {"error":{"code":"1214","message":"The messages parameter is illegal. Please check the document."}}. When this error appears, the functioning model remains unaffected, but selecting either of the other two models leads to the error.

**Comment by Yeuoly** [comment]
This is a model related issue, pls check official documents of ZhipuAI.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
