### ISSUE TITLE
After the model deployed with openLLM was added withdify-0.63, more answers came from Human.

### ISSUE THREAD

**Issue by upseem** [langgenius/dify#3596]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

For a model deployed with openLLM, after adding it withdify-0.63, the answer will be "Human", or "Human </histories", but when I call the locally deployed api myself, the answer is normal.
![Openllm](https://github.com/langgenius/dify/assets/124853686/daa0d675-f94c-43b4-b290-e7b0c814b07b)
![human](https://github.com/langgenius/dify/assets/124853686/88e24e5d-6175-4614-aa0a-ced28bd04afb)
![no-Human](https://github.com/langgenius/dify/assets/124853686/79456587-a483-41d2-b5c1-f4cecd376268)

### ✔️ Expected Behavior

No human and other symbols

### ❌ Actual Behavior

human or "Human </histories"

**Comment by vccler** [comment]
There is same issue with huggingface Model and mistralai/Mistral-7B-Instruct-v0.2 API endpoints
![微信截图_20240418225530](https://github.com/langgenius/dify/assets/1812193/6b0c60e2-f2e2-45d7-95d3-7c5a9763a1cd)

**Comment by crazywoola** [comment]
Step the stop words maybe?

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
