### ISSUE TITLE
"Model Parameter max_tokens should be less than or equal to 1500.0." when enabling "Segmenting in Question & Answer format"

### ISSUE THREAD

**Issue by LazarusX** [langgenius/dify#3598]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Go to the settings of a document in a knowledge base with "Segmenting in Question & Answer format" disabled
2. Enable "Segmenting in Question & Answer format"
3. An error message saying "Model Parameter max_tokens should be less than or equal to 1500.0." pops up on the top right corner.
![20240418-152341](https://github.com/langgenius/dify/assets/716650/113f8f52-e823-4ec0-bb34-4d88469ece63)
4. The paragraph preview page is blank.

I am using Qwen's text-embedding-v2 model. I cannot find any place in the document or knowledge base settings where I can set the 'max_tokens' parameter mentioned in the error message.

### ✔️ Expected Behavior

No error message, and generated paragraphs are shown after building embedding.

### ❌ Actual Behavior

1. An error message saying "Model Parameter max_tokens should be less than or equal to 1500.0." pops up on the top right corner.
![20240418-152341](https://github.com/langgenius/dify/assets/716650/113f8f52-e823-4ec0-bb34-4d88469ece63)
2. The paragraph preview page is blank.

**Comment by JohnJyong** [comment]
pls reduce the max token setting when you splitter the document , you LLM model only support 1500 token ,  because we are using the LLM model to genarate the Q&A  @LazarusX

**Comment by LazarusX** [comment]
@JohnJyong Thanks for the response. I am using Tongyi's text-embedding-v2. I cannot find anywhere to set the max token, either in the model provider settings, knowledge base settings, or document settings.
![image](https://github.com/langgenius/dify/assets/716650/82235466-a8ca-43b9-ac07-d45b4fb48f61)
![image](https://github.com/langgenius/dify/assets/716650/653d648e-88ba-4c0c-88aa-737327f82111)
![image](https://github.com/langgenius/dify/assets/716650/628351ee-09b1-4e25-a6d0-12a11b36a605)

Could you point me to the right location?

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)

**Comment by StephenPCG** [comment]
I have encountered the same problem, I'm using the latest version 0.6.11, docker, self hosted, with qwen text-embedding-v2 model.

**Comment by kaojistream** [comment]
+1

**Comment by charliex2** [comment]
I have encountered the same problem, I'm using the latest version 0.6.16, docker, self hosted, with qwen text-embedding-v2 model.

**Comment by LazarusX** [comment]
@crazywoola Looks like the issue still exists. Please help take a look again.

**Comment by nadirvishun** [comment]
> Please upgrade to latest version to see if this issue persists. :)

The error still exists in version `0.8.2`, reason: 
- The model parameters set in QA mode are hardcoded in the program: `max_tokens : 2000`: 
https://github.com/langgenius/dify/blob/6dba68f62d5e34eca618d9c4a5008e5b54ddcf8a/api/core/llm_generator/llm_generator.py#L252-L254
- When calling the large model, the parameters will be checked first：`parameter_value` is the previous message max_tokens: `2000`, `parameter_rule.max` is get from llms config: 
https://github.com/langgenius/dify/blob/6dba68f62d5e34eca618d9c4a5008e5b54ddcf8a/api/core/model_runtime/model_providers/__base/large_language_model.py#L817-L820
- if use `qwen-turbo`, the `parameter_rule.max` is `1500`, so an error occurred: 
https://github.com/langgenius/dify/blob/6dba68f62d5e34eca618d9c4a5008e5b54ddcf8a/api/core/model_runtime/model_providers/tongyi/llm/qwen-turbo-chat.yaml#L22-L30

A temporary solution is to switch to other large models. like `qwen-long`,`qwen-max-1201`,`qwen-plus-chat`, moreover, this selection of the large model does not have additional parameters; instead, it directly uses the default model set in the system settings: 
![image](https://github.com/user-attachments/assets/3e62c270-742e-4233-97f7-d5f8890d66d2)

I hope the official team can resolve this issue as soon as possible：
- Why is the hardcoded max-tokens set to 2000?
- Can the option to choose which model to process the QA mode be added?
