### ISSUE TITLE
一个 bot 里无法选择多个数据集

### ISSUE THREAD

**Issue by chllei** [langgenius/dify#36]
如图，在“上下文”处添加数据集时，只能选择其中的一个数据集。这是本来就被设计成这样的，还是当前的一个bug？
<img width="328" alt="屏幕截图 2023-05-16 124048" src="https://github.com/langgenius/dify/assets/114857541/913f2d45-74cd-46f6-b426-21c38814e41b">

**Comment by takatost** [comment]
多个数据集目前由于采用 Agent 模式，耗时较长，体验不好，需要后续改进交互，目前暂时禁用。
