### ISSUE TITLE
私有化部署，登录首页后一直转圈

### ISSUE THREAD

**Issue by thinking-one-hour-everyday** [langgenius/dify#361]
因为安全要求，部署环境有上公网的限制。 部署完成后，发现服务部能正常使用，发现服务要去连接一些公网： 'https://api.dify.ai',
'API_URL': 'https://api.dify.ai','APP_URL': 'https://udify.app', 。是不部署的服务器没有公网，就不能使用？ 服务连接这些URL需要收集什么信息呢？

**Comment by crazywoola** [comment]
Please read this [compose](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml) for details
