### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by joshfeng** [langgenius/dify#3613]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

yarn build

### ✔️ Expected Behavior

no error

### ❌ Actual Behavior

dify\web>yarn build
yarn run v1.22.19
$ next build
  ▲ Next.js 14.2.2
  - Environments: .env.local

   Creating an optimized production build ...
Failed to compile.

./node_modules/mermaid/dist/mindmap-definition-57868176.js
Module not found: Package path ./dist/cytoscape.umd.js is not exported from package \dify\web\node_modules\cytoscape (see exports field in \dify\web\node_modules\cytoscape\package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/mermaid/dist/mermaid-768dc893.js
./node_modules/mermaid/dist/mermaid.core.mjs
./app/components/app/chat/mermaid/index.tsx
./app/components/base/markdown.tsx
./app/components/app/text-generate/saved-items/index.tsx
./app/components/share/text-generation/index.tsx

> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by qiansc** [comment]
Still have this problem.
add following to dify/web/node_modules/.pnpm/mermaid@10.4.0/node_modules/cytoscape/package.json as temporary resolution
```
    "./dist/cytoscape.umd.js": {
      "import": "./dist/cytoscape.umd.js",
      "require": "./dist/cytoscape.umd.js"
    }
```
