### ISSUE TITLE
Setting SearXNG base URL error

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#3616]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="470" alt="image" src="https://github.com/langgenius/dify/assets/12423206/06d0dfec-369a-4a02-8e98-c567e2f1ab31">

```
{
    "code": "invalid_param",
    "message": "HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77fb6b1018d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "status": 400
}
```

**Comment by crazywoola** [comment]
This error occurs because the SearchXNG service is not accessible from the docker container.`localhost` or `127.0.0.1` usually refers to the container itself, not the host machine or other containers. To resolve this issue, you need to expose the SearchXNG service to the network.

**Comment by forhonourlx** [comment]
Same with me. Windows 11 Docker Running `Dify` and `SearXNG` both successfully. I can visit SearXNG on `http://127.0.0.1:8080/`
When I authorize SearXNG with `http://127.0.0.1:8080`, error occurs:
```
HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f0a8dc970>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
@crazywoola Could you please kindly help?

**Comment by xm1085** [comment]
> 我也一样。Windows 11 Docker 运行并且两者都成功。我可以访问 SearXNG 当我授权 SearXNG 时，会发生错误：`Dify``SearXNG``http://127.0.0.1:8080/``http://127.0.0.1:8080`
> 
> ```
> HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f0a8dc970>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```
> 
> 你能帮忙吗？

请问你解决了吗，我跟你一样的问题

**Comment by xm1085** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  Pleas do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.6.3
> 
> ### Cloud or Self Hosted
> Self Hosted (Docker)
> 
> ### Steps to reproduce
> <img alt="image" width="470" src="https://private-user-images.githubusercontent.com/12423206/323657457-06d0dfec-369a-4a02-8e98-c567e2f1ab31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDA2NDksIm5iZiI6MTcyMzkwMDM0OSwicGF0aCI6Ii8xMjQyMzIwNi8zMjM2NTc0NTctMDZkMGRmZWMtMzY5YS00YTAyLThlOTgtYzU2N2UyZjFhYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEzMTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmU3ZmEzNDVkZWVjOTJkYTdmMWNjMGU2NWE2NzA5NjgyYzc0ZGY2ZTllYTI0N2IxODkzMDdkMDhhNmQ4YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vchAcEWWr5xohgA0CtFdlggSbm7PlXVFux6cTRX_sXA">
> ```
> {
>     "code": "invalid_param",
>     "message": "HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x77fb6b1018d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
>     "status": 400
> }
> ```
> 
> ### ✔️ Expected Behavior
> _No response_
> 
> ### ❌ Actual Behavior
> _No response_

searxn的base url应该是：http://host.docker.internal:8080 ，应该是容器内的地址host.docker.internal，而不是127.0.0.1

**Comment by forhonourlx** [comment]
> > ### Self Checks
> > 
> > * [x]   This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> > * [x]   I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> > * [x]   I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> > * [x]   Pleas do not modify this template :) and fill in all the required fields.
> > 
> > ### Dify version
> > 0.6.3
> > ### Cloud or Self Hosted
> > Self Hosted (Docker)
> > ### Steps to reproduce
> > <img alt="image" width="470" src="https://private-user-images.githubusercontent.com/12423206/323657457-06d0dfec-369a-4a02-8e98-c567e2f1ab31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDA2NDksIm5iZiI6MTcyMzkwMDM0OSwicGF0aCI6Ii8xMjQyMzIwNi8zMjM2NTc0NTctMDZkMGRmZWMtMzY5YS00YTAyLThlOTgtYzU2N2UyZjFhYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEzMTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmU3ZmEzNDVkZWVjOTJkYTdmMWNjMGU2NWE2NzA5NjgyYzc0ZGY2ZTllYTI0N2IxODkzMDdkMDhhNmQ4YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vchAcEWWr5xohgA0CtFdlggSbm7PlXVFux6cTRX_sXA">
> > ```
> > {
> >     "code": "invalid_param",
> >     "message": "HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))",
> >     "status": 400
> > }
> > ```
> > ### ✔️ Expected Behavior
> > _No response_
> > ### ❌ Actual Behavior
> > _No response_
> 
> searxn的base url应该是：http://host.docker.internal:8080 ，应该是容器内的地址host.docker.internal，而不是127.0.0.1

Yes! `dify` container could access `searxng` container by port on host `http://host.docker.internal:8080`.
There seems a misleading on [https://github.com/langgenius/dify-docs/blob/main/en/guides/tools/tool-configuration/searxng.md](url)
Suggest a fix please.
@crazywoola

**Comment by LuckinOvaltine** [comment]
+1，我的本地dify版本是0.15.3，而且在浏览器测试了可以访问http://localhost:8081/，但是在dify中部署就会出错。
报错信息为：Error 403: <!doctype html> <html lang=en> <title>403 Forbidden</title> <h1>Forbidden</h1> <p>You don&#39;t have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>
HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30303d88f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
