### ISSUE TITLE
Offline deployment in the intranet environment (configuration agent can access gpt) using openai gpt-4 Q&A background error reporting。Error：ERROR:root:HTTPSConnectionPool(host='openaipublic.blob.core.windows.net'

### ISSUE THREAD

**Issue by smart-aiops** [langgenius/dify#3635]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/851243/470c0c6d-c392-4d96-b544-db1b307d7b54)
![image](https://github.com/langgenius/dify/assets/851243/d61aef7f-1b68-40f2-a119-0bdcbfc56778)

![2881aac962236b162f15579141c63cb9_61220](https://github.com/langgenius/dify/assets/851243/0aa8e2fd-9a35-421d-b86e-106d472fc805)

### ✔️ Expected Behavior

![image](https://github.com/langgenius/dify/assets/851243/470c0c6d-c392-4d96-b544-db1b307d7b54)
![image](https://github.com/langgenius/dify/assets/851243/d897d6ad-9e86-4ca5-9d76-76a1e72ac8fe)

![2881aac962236b162f15579141c63cb9_61220](https://github.com/langgenius/dify/assets/851243/0aa8e2fd-9a35-421d-b86e-106d472fc805)

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/851243/470c0c6d-c392-4d96-b544-db1b307d7b54)
![image](https://github.com/langgenius/dify/assets/851243/6c6883fb-a591-4d56-bb81-014b83f29edf)

![2881aac962236b162f15579141c63cb9_61220](https://github.com/langgenius/dify/assets/851243/0aa8e2fd-9a35-421d-b86e-106d472fc805)

**Comment by crazywoola** [comment]
Can not resolve  `openaipublic.blob.core.windows.net` typical means it's a general network issue. Please use a proper proxy to deal with such kind of issues.

**Comment by liqilong2017** [comment]
![Image](https://github.com/user-attachments/assets/ab89f50b-e771-43ca-b6f7-c09d4b003d49)
like this~

**Comment by Celdrick** [comment]
> resolve [#1014](https://github.com/langgenius/dify/issues/1014)
> 
> Reason: In an offline environment, TikToken and Jieba need internet access to obtain the segmentation files, leading to connection failure.
> 
> Solution: In an environment with internet access, successfully execute the knowledge base indexing once. This will generate data-gym-cache and jieba.cache in the /tmp directory of the worker_1 docker container. Copy the /tmp folder to the offline docker containers (docker_worker_1 and docker_api_1) to resolve the issue.

docker-worker-1 /tmp/ only jieba.cache，don't have the data-gym-cache dir
And I already copy the jieba.cache to my offline machine ,but it doesn't work
