### ISSUE TITLE
run "import DSL"  Workflow,  not display finally information

### ISSUE THREAD

**Issue by DamonLong3912** [langgenius/dify#3643]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After a day of checking, I found that by importing DSL workflows, the final information is often not displayed at runtime, and the Workflow Process always shows loading.  This is most likely a problem with the way the DSL is imported, because I try not to use the import DSL, but to create a new workflow and run it without problems.

This problem occurs both in the cloud and source, and is extremely frequent.

> 
![1713579198970](https://github.com/langgenius/dify/assets/153148939/62e58c63-48e0-445c-8956-566a280f7645)

**Comment by crazywoola** [comment]
Could you paste the screenshot of Ending node? Or you can attach the whole DSL file here.
