### ISSUE TITLE
源码是完全开源的吗？

### ISSUE THREAD

**Issue by 983183947** [langgenius/dify#3644]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

源码是完全开源的吗，还是有些包不开放？

**Comment by crazywoola** [comment]
Some SaaS related packages and our code sandbox is not open source. Please reach out to business@dify.ai to get more information.

**Comment by bbcvc** [comment]
> Some SaaS related packages and our code sandbox is not open source. Please reach out to [business@dify.ai](mailto:business@dify.ai) to get more information.

dify的设计资源有计划开放吗？
