### ISSUE TITLE
cannot upload local images through the api

### ISSUE THREAD

**Issue by lyfeng001** [langgenius/dify#3645]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

when upload an image through the api, we need to post a json containing a upload_file_id, but it can be got after the image is uploaded, so that i can't upload the image, and there is no some keys like "contents" to upload the image directly.

### 2. Describe the feature you'd like to see

I'd like to upload pics directly or upload the pics in the form of base64.

### 3. How will this feature improve your workflow or experience?

that will help me to upload images directly when i get them from a camera or something.

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by Troublesis** [comment]
I think maybe you missed the  `/files/upload` API. It was written very nicely in the Dify API document.

<img width="874" alt="image" src="https://github.com/langgenius/dify/assets/40723560/a58f3a1a-7185-481c-bbbd-86b7a447a558"><br>

You suppose to upload the file with the `/files/upload` API first to get the `id` from this API, then use this `id` in `chat-messages` API. 
> [!IMPORTANT]
> Make sure the model you selected should support `Vision`.

<img width="1280" alt="image" src="https://github.com/langgenius/dify/assets/40723560/472edb30-0d71-4a1b-8f8c-511c2db23ab3"><br><br>

I am using [Bruno](https://github.com/usebruno/bruno)[^1] to test Dify API. I am able to send image and get response related to the image.
1. Get the file `id` first

<img width="1053" alt="image" src="https://github.com/langgenius/dify/assets/40723560/3be64302-ed1b-4aa3-866d-10959610ca21">

2. Use the `id` as `upload_file_id` in `chat-messages` API

<img width="1051" alt="image" src="https://github.com/langgenius/dify/assets/40723560/23b4eb65-f18c-4b19-8e3f-7f5a7beadaae">

Hope this resolves your question.
[^1]: Bruno - Open source IDE For Exploring and Testing Api's (lightweight alternative to postman/insomnia)

**Comment by StreamlinedStartup** [comment]
Is it possible to access the "batch run app" via api and thus, upload a file for the batch run? 

I have a `workflow` and there is no specific file upload input within the app itself. I'm guessing that's why I don't see `/files/upload` in my documentation?

**Comment by chaozZLF** [comment]
> 我想你可能错过了 API。它在 Dify API 文档中写得非常好。`/files/upload`
> 
> <img alt="image" width="874" src="https://private-user-images.githubusercontent.com/40723560/324187212-a58f3a1a-7185-481c-bbbd-86b7a447a558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzEwNzcsIm5iZiI6MTcyNzMzMDc3NywicGF0aCI6Ii80MDcyMzU2MC8zMjQxODcyMTItYTU4ZjNhMWEtNzE4NS00ODFjLWJiYmQtODZiN2E0NDdhNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA2MDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjBjY2MwMGZmNzMzYjZlZjlhMDEwZTBhMjNjNTNmYWQyNDEyMDJlNzc4ZTI1OWZkMjk1M2ZkMzdhZDJlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5UP5u6D7FFbHLRxuQqIlhh5D4YLK-6lOkmrvO6YRdEs">
> 
> 您应该先使用 API 上传文件以从此 API 获取，然后在 API 中使用它。`/files/upload``id``id``chat-messages`
> 
> 重要
> 
> 确保您选择的型号应支持 .`Vision`
> 
> <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/40723560/324187628-472edb30-0d71-4a1b-8f8c-511c2db23ab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzEwNzcsIm5iZiI6MTcyNzMzMDc3NywicGF0aCI6Ii80MDcyMzU2MC8zMjQxODc2MjgtNDcyZWRiMzAtMGQ3MS00YTFiLThmOGMtNTExYzJkYjIzYWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA2MDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMGY5NmQ1ZjFlZTdlODNiZTllMjhjOWYzNDU1ZjgzZGU4NTRmZDgyNjk0Y2RjNGRjZmYwOTdiNmIyYWViYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TGCa4SrtagDdVPhOMHAmfp0iFbNw3lZLuZRtPtPKsYU">
> 
> 我正在使用 [Bruno](https://github.com/usebruno/bruno)[1](#user-content-fn-1-9836dc5e6da68b946ed79e48b69a3ecb)测试 Dify API。我能够发送图像并获得与图像相关的响应。
> 
> 1. 首先获取文件`id`
> 
> <img alt="image" width="1053" src="https://private-user-images.githubusercontent.com/40723560/324187758-3be64302-ed1b-4aa3-866d-10959610ca21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzEwNzcsIm5iZiI6MTcyNzMzMDc3NywicGF0aCI6Ii80MDcyMzU2MC8zMjQxODc3NTgtM2JlNjQzMDItZWQxYi00YWEzLTg2NmQtMTA5NTk2MTBjYTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA2MDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZDM4ZDg5NDc2ZGQwZDQ3NjFkOTM3NzUyMGUzZDc2ZDk0M2MyODVjY2IyMjRhNjJiMzI4OGZlNzY5NTJlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y1R0Cmv-xMnfGiqr01FifWeHXseUg8J3TVKdQgsQrw0">
> 2. 使用 as in API`id``upload_file_id``chat-messages`
> 
> <img alt="image" width="1051" src="https://private-user-images.githubusercontent.com/40723560/324187786-23b4eb65-f18c-4b19-8e3f-7f5a7beadaae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzEwNzcsIm5iZiI6MTcyNzMzMDc3NywicGF0aCI6Ii80MDcyMzU2MC8zMjQxODc3ODYtMjNiNGViNjUtZjE4Yy00YjE5LThlM2YtN2Y1YTdiZWFkYWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA2MDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZDU5ZmRhNmRhNTI4ZTQwODA4YjkyMjMzYWQ1ZWNhOTY0ZjdiMzg0YWYyNjQwMDk5NzYzMjQyNDg2NTUzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OCCJt7FQrGGDIYyrrsdt6T8o0G1qEK2YIrkqU_ExRLA">
> 希望这能解决您的问题。
> 
> ## 脚注
> 1. Bruno - 用于探索和测试 API 的开源 IDE（postman/insomnia 的轻量级替代方案） [↩](#user-content-fnref-1-9836dc5e6da68b946ed79e48b69a3ecb)

As I know how to upload an image via file/upload,how to achieve upload multiple images like web-ui does 
![image](https://github.com/user-attachments/assets/c7d7b460-b361-4e17-a8fc-eb73fa213869)
