### ISSUE TITLE
Notion wont connect

### ISSUE THREAD

**Issue by Darren-A11att** [langgenius/dify#3650]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I try to Authorise Notion, I get this error:

Something went wrong
Missing or incomplete Client ID. See  for more help.

### ✔️ Expected Behavior

It would connext to notion

### ❌ Actual Behavior

Something went wrong
Missing or incomplete Client ID. See  for more help.

**Comment by Nick13928868100nn** [comment]
Similarly, the client id is incorrectly reported using notion internal.

**Comment by stevenluan007** [comment]
I meet the same problem. which env file? Did you mean some config parameters in docker-compose.yaml?  @dosu

**Comment by JohnJyong** [comment]
there is clearly setting descrition in : https://docs.dify.ai/features/datasets/sync-from-notion
@Nick13928868100nn @stevenluan007

**Comment by zer0yu** [comment]
The issue persists even when deploying the environment using docker-compose. Despite modifying the .env file in the relevant API directory, the internal integration method remains impossible.  I wonder if it is necessary to force the use of the public integration method?

**Comment by zer0yu** [comment]
It still doesn't work when deployed with docker-compose

**Comment by zer0yu** [comment]
It is recommended to refer to this article to update the corresponding documentation
https://note.com/jolly_dahlia842/n/n7b8b029316cd?sub_rt=share_pw
