### ISSUE TITLE
Model deletion is not possible. 

### ISSUE THREAD

**Issue by zero24345** [langgenius/dify#3657]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After adding a custom model in the style of OpenAI API, it cannot be deleted. Additionally, other OpenAI models that haven't been added will also be displayed. 

### ✔️ Expected Behavior

Bug fix

### ❌ Actual Behavior

bug

**Comment by crazywoola** [comment]
This is not a bug, actually a `by design` behavior. If you want to delete something that no longer needed. That's a feature request.
