### ISSUE TITLE
Multi-turn conversation that involve images are not supported when using the gpt-4-turbo model.

### ISSUE THREAD

**Issue by Weishan-0** [langgenius/dify#3659]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

![CleanShot 2024-04-21 at 17 27 18](https://github.com/langgenius/dify/assets/29089406/cd760341-3c45-44c0-8309-940708de543c)

**Comment by Weishan-0** [comment]
I noticed in the source code that when using the `gpt-4-turbo` and `gpt-4-turbo-2024-04-09` models, the user-uploaded images are replaced with the text `[IMAGE]`. But I don't understand why this is done.

```python
# clear illegal prompt messages
prompt_messages = self._clear_illegal_prompt_messages(model, prompt_messages)

# chat model
 response = client.chat.completions.create(
 messages=[self._convert_prompt_message_to_dict(m) for m in prompt_messages],
 model=model,
 stream=stream,
 **model_parameters,
 **extra_model_kwargs,
)
```

```python
 def _clear_illegal_prompt_messages(self, model: str, prompt_messages: list[PromptMessage]) -> list[PromptMessage]:
        """
        Clear illegal prompt messages for OpenAI API

        :param model: model name
        :param prompt_messages: prompt messages
        :return: cleaned prompt messages
        """
        checklist = ['gpt-4-turbo', 'gpt-4-turbo-2024-04-09']

        if model in checklist:
            # count how many user messages are there
            user_message_count = len([m for m in prompt_messages if isinstance(m, UserPromptMessage)])
            if user_message_count > 1:
                for prompt_message in prompt_messages:
                    if isinstance(prompt_message, UserPromptMessage):
                        if isinstance(prompt_message.content, list):
                            prompt_message.content = '\n'.join([
                                item.data if item.type == PromptMessageContentType.TEXT else
                                '[IMAGE]' if item.type == PromptMessageContentType.IMAGE else ''
                                for item in prompt_message.content
                            ])

        return prompt_messages
```

**Comment by Yeuoly** [comment]
> I noticed in the source code that when using the `gpt-4-turbo` and `gpt-4-turbo-2024-04-09` models, the user-uploaded images are replaced with the text `[IMAGE]`. But I don't understand why this is done.
> 
> ```python
> # clear illegal prompt messages
> prompt_messages = self._clear_illegal_prompt_messages(model, prompt_messages)
> 
> # chat model
>  response = client.chat.completions.create(
>  messages=[self._convert_prompt_message_to_dict(m) for m in prompt_messages],
>  model=model,
>  stream=stream,
>  **model_parameters,
>  **extra_model_kwargs,
> )
> ```
> 
> ```python
>  def _clear_illegal_prompt_messages(self, model: str, prompt_messages: list[PromptMessage]) -> list[PromptMessage]:
>         """
>         Clear illegal prompt messages for OpenAI API
> 
>         :param model: model name
>         :param prompt_messages: prompt messages
>         :return: cleaned prompt messages
>         """
>         checklist = ['gpt-4-turbo', 'gpt-4-turbo-2024-04-09']
> 
>         if model in checklist:
>             # count how many user messages are there
>             user_message_count = len([m for m in prompt_messages if isinstance(m, UserPromptMessage)])
>             if user_message_count > 1:
>                 for prompt_message in prompt_messages:
>                     if isinstance(prompt_message, UserPromptMessage):
>                         if isinstance(prompt_message.content, list):
>                             prompt_message.content = '\n'.join([
>                                 item.data if item.type == PromptMessageContentType.TEXT else
>                                 '[IMAGE]' if item.type == PromptMessageContentType.IMAGE else ''
>                                 for item in prompt_message.content
>                             ])
> 
>         return prompt_messages
> ```

yeah, but we have to do like this, you can try to invoke GPT-4-Turbo with muti-turn messages with images yourself, then you will find that an error has been raised like below.
![img_v3_029q_991091b9-e169-488f-9ca7-fb8616f867eg](https://github.com/langgenius/dify/assets/45712896/ec6d6303-fc11-4479-8113-5d3741bcc60e)
So far, message with both vision and tool-call ability is supported only in single-turn conversations.
