### ISSUE TITLE
If a JSON value is true or false, python code function will run into NameError.

### ISSUE THREAD

**Issue by Troublesis** [langgenius/dify#3661]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When you passed an `Array[Object]` variable into `Python3 Code Block`, if the `JSON` values has `true` or `false` as one of the JSON variable value, it will run into `NameError`.

<img width="972" alt="image" src="https://github.com/langgenius/dify/assets/40723560/359844d8-82c9-43ab-933b-583d38b2478e">

<img width="450" alt="image" src="https://github.com/langgenius/dify/assets/40723560/840582be-b881-491c-90be-36b3535fe69c"><br>
You can see the below code. I did not change the python code, but if the value has " mark, It will successfully run.
> [!NOTE]
> I am having this issue, because I am creating some workflows using Google Calendar API, the API value returns result which contains `true` and `false` (I didn't really intend to pass these values myself). Part of the API result example as below:
```
  "organizer": {
    "email": "test@gmail.com",
    "self": true
  }
```
<img width="415" alt="image" src="https://github.com/langgenius/dify/assets/40723560/2f0f152c-e2fc-4c86-807e-ab90de58e666">

### ✔️ Expected Behavior

It should successfully return the result as it is or at lease it should allow you to use `try` `except` to bypass the error, but even I tired to use `try` `expect`, i can not bypass this error.

### ❌ Actual Behavior

It shows NameError at the `Code Block`.
`Traceback (most recent call last): File "<string>", line 40, in <module> File "<string>", line 12, in <module> NameError: name 'false' is not defined error: exit status 255`

**Comment by crazywoola** [comment]
<img width="349" alt="image" src="https://github.com/langgenius/dify/assets/100913391/b6d6f6e4-7cb1-460d-8120-8abe24c15ac3">
This should be a array[object] as well right?

**Comment by Troublesis** [comment]
> <img alt="image" width="349" src="https://private-user-images.githubusercontent.com/100913391/324250870-b6d6f6e4-7cb1-460d-8120-8abe24c15ac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDY3NTAsIm5iZiI6MTcxMzcwNjQ1MCwicGF0aCI6Ii8xMDA5MTMzOTEvMzI0MjUwODcwLWI2ZDZmNmU0LTdjYjEtNDYwZC04MTIwLThhYmUyNGMxNWFjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxMzM0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTBkMWYwNWIyNmRlOTExMTU3NWE3ZTQwNjZhYjMwM2ViNDkzYmFjNGE0ZTNhN2IzNjhhZDJkZjJhMmZkZjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F_WYIBRlVE46xDTm5BOwyvOGTvdNT1byV95rEHFdhCU"> This should be a array[object] as well right?

No, because the simple python code is trying to get the value of `test`. If you change it to `array[object]` then the code block still shows same error. This is not really related to this question. I think it is something related to the source code where, when it runs the python code block, it is not able to take the `boolean data type` value properly. Maybe should convert and result as str?

Actually I just tried the same thing in [Coze](https://www.coze.com). It doesn't even allow you to input `true`, but I think if we can work around this it will be useful. Some APIs does include `boolean data type` in JSON result.

![image](https://github.com/langgenius/dify/assets/40723560/0ffee451-d9d0-4153-acfa-cc5bc9c5eedf)

**Comment by Yeuoly** [comment]
you should use `False` instead of `false` in Python, otherwise it will be considered as an undefined variable, or maybe you can use JavaScript
