### ISSUE TITLE
The text-to-speech model "Tongyi Qianwen" is not available.

### ISSUE THREAD

**Issue by mwnu** [langgenius/dify#3664]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

It can be set in the system or tried out in the application. However, if you click play during a conversation, an error will appear at the top of the page and in the log: "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by crazywoola** [comment]
Can you paste a screenshot of the tts support in debug mode.
