### ISSUE TITLE
Reproducible CORS policy issue.

### ISSUE THREAD

**Issue by mwnu** [langgenius/dify#3665]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. In the application log, open one of the conversation logs.
2. Add a label to one of the AI-generated responses.
3. Click "Remove" on this label, and a dialog box will pop up for confirmation.
4. Click "Add Annotation" again on this message.

The console shows a "blocked by CORS" error, and the message on the page has not been marked as removed.
```
Access to fetch at 'https://xxxxxx/console/api/apps/xxxxxxxx/annotations/' from origin 'https://xxxxxxxxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
5. Then refresh the page, and you will find that the tag has been removed.
The above errors can be replicated.

My Dify web(https://example.com:7650) service and API service(https://example.com:7655) are not on the same domain.Here are the configurations for my server.

```
WEB_API_CORS_ALLOW_ORIGINS: '*'
CONSOLE_CORS_ALLOW_ORIGINS: '*'
COOKIE_HTTPONLY: 'true'
COOKIE_SAMESITE: 'None'
COOKIE_SECURE: 'true'
```
Related issues：https://github.com/langgenius/dify/issues/3663

**Comment by crazywoola** [comment]
Please read the docs to resolve this issues.  The is the web development standards, if you use the source code to deploy, we assume you have the basic knowledge of these issues.
See `CONSOLE_WEB_URL` in https://docs.dify.ai/getting-started/install-self-hosted/environments

**Comment by mwnu** [comment]
> Please read the docs to resolve this issues. The is the web development standards, if you use the source code to deploy, we assume you have the basic knowledge of these issues. See `CONSOLE_WEB_URL` in https://docs.dify.ai/getting-started/install-self-hosted/environments

This issue should not be closed because the problem has not been resolved. You should look at the steps to reproduce it. Perhaps it's not a mistake in my configuration, but a problem with the project itself.
I know what CORS is. Although the documentation about these URLs is confusing, my configuration should be correct.

**Comment by mwnu** [comment]
> Please read the docs to resolve this issues. The is the web development standards, if you use the source code to deploy, we assume you have the basic knowledge of these issues. See `CONSOLE_WEB_URL` in https://docs.dify.ai/getting-started/install-self-hosted/environments
----
I have reproduced this error at xxx. Please reopen this issue.

<img width="1207" alt="PixPin_2024-04-22_05-46-28" src="https://github.com/langgenius/dify/assets/45463732/4eab7732-2e29-4da9-a308-31087ce3c700">

**Comment by wwwDESIGN-basti** [comment]
same here.

**Comment by Sololololo** [comment]
same here...
