### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by realjustinwu** [langgenius/dify#3668]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Start the service, keep it running for days, use the app consistently

### ✔️ Expected Behavior

The memory shold not increase

### ❌ Actual Behavior

<img width="857" alt="image" src="https://github.com/langgenius/dify/assets/3467850/11de9d82-7683-4b9d-93b3-507ed48384b6">

**Comment by crazywoola** [comment]
Noticed this is an outdated version. Please try to upgrade to latest one.

**Comment by takatost** [comment]
This is as expected, theoretically if all features are used, it will require 8GB of memory.

**Comment by realjustinwu** [comment]
> Noticed this is an outdated version. Please try to upgrade to latest one.

Do you mean that the recent version fixed this memory leak?

**Comment by realjustinwu** [comment]
> This is as expected, theoretically if all features are used, it will require 8GB of memory.

I'm not using all the features and the API calls aren't constant, memory should be going down when there are no API calls, right?

**Comment by nelsonkti** [comment]
@realjustinwu Has the upgrade been resolved? 0.15.3 still has this issue

**Comment by realjustinwu** [comment]
The memory keeps increasing, and it only decreases when it reaches 100%. I'm not sure which configuration allows the memory to decrease earlier.

> [@realjustinwu](https://github.com/realjustinwu) Has the upgrade been resolved? 0.15.3 still has this issue

**Comment by yihong0618** [comment]
will take a look next week

**Comment by Jonathan-Jyu** [comment]
Hi, is there any solution to solve the memory keeps increasing problem?
