### ISSUE TITLE
The answer always stops at about 1300 characters.

### ISSUE THREAD

**Issue by cmastro** [langgenius/dify#367]
I've created an app, but the response always stops at about 1300 characters.

The gunicorn log returns a "Closing Connection", but it seems that it is not a TimeOut problem.

Any idea what may be happening?

Thanks!

**Comment by crazywoola** [comment]
Which version do you use, have you set the max token in app settings?

**Comment by cmastro** [comment]
I have found how to set it. 
Thanks @crazywoola !!

**Comment by cmastro** [comment]
I find it! and now with 16k it's working... thanks!

**Comment by sam1am** [comment]
I am running into the same problem. I have adjusted the max tokens  and responses are still getting cut off. What's worse is that the response that has been given up to that point gets deleted. 

I see this error at the top of the page:  

![Screenshot from 2023-08-03 13-05-56](https://github.com/langgenius/dify/assets/127555/83ebd969-fb5c-4f3c-aa7f-ba0765f20237)

**Comment by LASTLINEK** [comment]
> I find it! and now with 16k it's working... thanks!

Could you please tell me how to set max tokens?  I can't find it's setting in '.env' or 'docker-compose.yaml'.
