### ISSUE TITLE
Remove the 2048 token limitation on API requests to Dify

### ISSUE THREAD

**Issue by LateralusAtCrezam** [langgenius/dify#3672]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I'm trying to generate long-form text using Dify agents pointed to an Xinference backend running mistral-instruct-0.2. The generation seems to be limited to 2048 tokens shared between prompt and completion. 

### 2. Describe the feature you'd like to see

Remove the 2048-token limit for requests, and make the max tokens configurable by user. 

### 3. How will this feature improve your workflow or experience?

This will allow me to generate long-form text which solves multiple prototyping and research use cases.

### 4. Additional context or comments

I'm running an Intel Core i7 12700 with 64GB of DDR5, paired with an Nvidia RTX A4500 GPU (20GB GDDR6) running Xinference with a model `mistral-instruct-0.2`. Dify is hosted on an AWS EC2 instance that is then pointed to my local GPU server. 

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
https://github.com/langgenius/dify/blob/9525ccac4f429cea9e3e263cb32ae7cee137a7e0/api/core/model_runtime/model_providers/xinference/llm/llm.py#L119

https://github.com/langgenius/dify/blob/9525ccac4f429cea9e3e263cb32ae7cee137a7e0/api/core/model_runtime/model_providers/xinference/llm/llm.py#L311

The model's max tokens and context size depend on the `context_length` returned by xinference when adding the model in Dify. You can check if xinference server returns correctly.
