### ISSUE TITLE
Code execution service is unavailable

### ISSUE THREAD

**Issue by shelltea** [langgenius/dify#3675]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

An error occurred while executing code with the code interpreter:
<img width="464" alt="image" src="https://github.com/langgenius/dify/assets/864375/f3bd21e5-5b25-4546-9314-a1bd632c7ab5">

The logs for docker-api-1 are as follows:
```log
2024-04-22 06:09:52.843 INFO [Thread-30 (_generate_worker)] [_client.py:1013] - HTTP Request: POST http://sandbox:8194/v1/sandbox/run "HTTP/1.1 503 Service Unavailable"
```

### ✔️ Expected Behavior

The code is running normally.

### ❌ Actual Behavior

Code execution service is unavailable

**Comment by Yeuoly** [comment]
Are you using sandbox at high frequency? just try to increase MAX_WORKERS in environment of sandbox service.

**Comment by shelltea** [comment]
I haven't been using the sandbox very frequently. The error occurred the first time I tried to use this feature, and there should have only been one concurrent instance.

**Comment by shelltea** [comment]
I've figured out where the problem lies. I configured the following environment variables for `docker-api-1`:

```docker-compose.yaml
HTTP_PROXY: 'http://xxx:xxx'
HTTPS_PROXY: 'http://xxx:xxx'
```

When `docker-api-1` tries to access `docker-sandbox-1`, the request is forwarded to a proxy node, causing network access issues. Therefore, it's necessary to add `sandbox` to `NO_PROXY`, like this:

```docker-compose.yaml
NO_PROXY: 'localhost,127.0.0.1,172.17.*.*, .local, weaviate, sandbox'
```

**Comment by selfuppen** [comment]
> I've figured out where the problem lies. I configured the following environment variables for `docker-api-1`:
> 
> ```miniyaml
> HTTP_PROXY: 'http://xxx:xxx'
> HTTPS_PROXY: 'http://xxx:xxx'
> ```
> 
> When `docker-api-1` tries to access `docker-sandbox-1`, the request is forwarded to a proxy node, causing network access issues. Therefore, it's necessary to add `sandbox` to `NO_PROXY`, like this:
> 
> ```miniyaml
> NO_PROXY: 'localhost,127.0.0.1,172.17.*.*, .local, weaviate, sandbox'
> ```

thanks, this help me a lot lot!!!

**Comment by blackbass64** [comment]
I encountered the same issue when handling a high volume of requests. By default, the sandbox container uses `MAX_WORKERS=4` and `MAX_REQUESTS=50`. I was able to fix the problem by adjusting these values and adding additional environment variables to better handle the load.

**Comment by magick93** [comment]
I've tried adding `NO_PROXY: 'localhost,127.0.0.1,172.17.*.*, .local, weaviate, sandbox'` to the api service, and restarted, but I'm still getting the `Code execution service is unavailable` error.
