### ISSUE TITLE
bedrock opus doesn't work

### ISSUE THREAD

**Issue by shing19** [langgenius/dify#3693]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After adding opus on AWS bedrock, try to call the model on Dify and got this error message:
[bedrock] Error: Error code: 400 - {'message': 'The provided model identifier is invalid.'}

**Comment by yamitzky** [comment]
@shing19 Which region are you using? It seems that Opus is [only supported in us-west-2 (Oregon)](https://aws.amazon.com/jp/blogs/aws/anthropics-claude-3-opus-model-on-amazon-bedrock/), so please try changing your region.

**Comment by shing19** [comment]
> @shing19 Which region are you using? It seems that Opus is [only supported in us-west-2 (Oregon)](https://aws.amazon.com/jp/blogs/aws/anthropics-claude-3-opus-model-on-amazon-bedrock/), so please try changing your region.

Thank you , it works after I change the region!

**Comment by shing19** [comment]
> @shing19 Which region are you using? It seems that Opus is [only supported in us-west-2 (Oregon)](https://aws.amazon.com/jp/blogs/aws/anthropics-claude-3-opus-model-on-amazon-bedrock/), so please try changing your region.

Thank you , it works after I change the region!
