### ISSUE TITLE
Version 0.6.4 encountered an error: "Worker (pid:67) was sent code 132!"

### ISSUE THREAD

**Issue by majian159** [langgenius/dify#3694]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgrading from version 0.6.3 to 0.6.4 of dify-api, the console log is flooded with error messages stating "[ERROR] Worker (pid:67) was sent code 132!" These errors appeared post-upgrade and are affecting the stability of the application. I am looking for guidance on how to resolve this issue or any workarounds to stabilize the system. Any assistance would be appreciated.

**Comment by takatost** [comment]
What's the architecture and version of your server?

**Comment by majian159** [comment]
> What's the architecture and version of your server?

I am running on Kubernetes, with Kubernetes version v1.22.17, the operating system is Ubuntu 20.04.3 LTS, and the container runtime is containerd://1.4.12.

**Comment by majian159** [comment]
I searched for information; could it be related to gunicorn? The commit d5448e07abd840580bb8ffa69d886cb559575fe6 for versions 0.6.3 to 0.6.4 is related to gunicorn.

**Comment by takatost** [comment]
Can you try switching the image version from 0.6.4 to the previous one `langgenius/dify-api:3aa182e26a134d11e0958141a5622df6e087124c` and see if it works fine? And the version you may think has problem: `langgenius/dify-api:d5448e07abd840580bb8ffa69d886cb559575fe6`?

**Comment by mwnu** [comment]
Perhaps it's related: https://github.com/langgenius/dify/issues/3741

**Comment by leslie2046** [comment]
In my side,i found same error log,and the method of reproduction as below:
Select any provider, enter the configuration, and then click save to reproduce the error message

![2a6853f221a3ed7b35ba7c3046f9af7](https://github.com/langgenius/dify/assets/10449699/c4165d2f-33c3-40d7-a183-37e2c259f30a)

And Upgrading gmpy2 to 2.2.0a1 will cause this error.
Restoring gmpy2 to 2.1.5 will not cause this error.

My enviroment:
| 配置 | 描述 |
| --- | --- |
|  CPU| Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz |
|  OS|  CentOS Linux release 7.9.2009 (Core)|
|python|Python 3.10.13|

**Comment by takatost** [comment]
This issue is caused by upgrading `gmpy2` from `2.1.5` to `2.2.0a1`. It seems that some CPU instructions are not compatible with `2.2.0a1`, leading to abnormal exits.

You can try replacing the image version to see if it fixes the issue:
Open `docker-compose.yaml`, change `langgenius/dify-api:0.6.4` to `langgenius/dify-api:ccaf335466e51a21160eb3d8c99f2992a5996b0d`.

**Comment by DoctrineAlanK** [comment]
> This issue is caused by upgrading `gmpy2` from `2.1.5` to `2.2.0a1`. It seems that some CPU instructions are not compatible with `2.2.0a1`, leading to abnormal exits.
> 
> You can try replacing the image version to see if it fixes the issue: Open `docker-compose.yaml`, change `langgenius/dify-api:0.6.4` to `langgenius/dify-api:ccaf335466e51a21160eb3d8c99f2992a5996b0d`.

tested with rocky linux9.3 and langgenius/dify-api:ccaf335466e51a21160eb3d8c99f2992a5996b0d and the error is fixed.

**Comment by majian159** [comment]
This seems to have solved my problem, looking forward to the release.
