### ISSUE TITLE
When I copied two start nodes in my workflow design, I couldn't remove one of them

### ISSUE THREAD

**Issue by lvyi21** [langgenius/dify#3698]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I copied two start nodes in my workflow design, I couldn't remove one of them

### ✔️ Expected Behavior

When I copied two start nodes in my workflow design, I couldn't remove one of them. I want to remove a start node. As a side note, I want to be able to drag and drop the input form components to reorder them
![1713851321392](https://github.com/langgenius/dify/assets/65033770/98efda0b-cd2f-4048-b3cd-f6456a7971ef)

**Comment by zxhlyh** [comment]
fixed #3701
