### ISSUE TITLE
When will Llama 3 be supported?

### ISSUE THREAD

**Issue by Caplost** [langgenius/dify#3702]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Now Llama 3 is out of the picture, and hopefully it will support Llama 3

### 2. Describe the feature you'd like to see

I want to use llama3 in my workflow

### 3. How will this feature improve your workflow or experience?

Ability to use more powerful local large models

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by thiner** [comment]
If you are asking for model runner, you can use ollama or llama-cpp-python to run llama-3 models in GGUF format. Both the model runners support OpenAI compatible API. You can then add the model in Dify model providers page.
