### ISSUE TITLE
Model providers are all disappeared in local Docker

### ISSUE THREAD

**Issue by trongnichi** [langgenius/dify#3707]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Settings -> Model Provider

### ✔️ Expected Behavior

Models are appeared.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/165017576/7e30f5e7-3c1a-4469-bc2b-3bd57e7fd6ff)

All models was gone.

**Comment by crazywoola** [comment]
Can you attach the screenshot of the frontend console. To see what's going on.

**Comment by trongnichi** [comment]
> Can you attach the screenshot of the frontend console. To see what's going on.

![image](https://github.com/langgenius/dify/assets/165017576/04c0bc54-fd33-4f25-8d78-8bb8deb79f1a)

**Comment by crazywoola** [comment]
Can you check `docker ps` to see api is started correctly?

**Comment by trongnichi** [comment]
> Can you check `docker ps` to see api is started correctly?

![image](https://github.com/langgenius/dify/assets/165017576/5e0369a6-5b48-4c79-a5fa-71966bfe300b)

**Comment by trongnichi** [comment]
I don't know why what happened with my old data when upgrade version. But when I clone new repo and put to Docker, it runs normally again.
