### ISSUE TITLE
Does RAG not support the epub file format?

### ISSUE THREAD

**Issue by cgoder** [langgenius/dify#3708]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Does RAG not support the epub file format?
![image](https://github.com/langgenius/dify/assets/5362274/16c0e83a-6630-4461-b5f7-678c100907f5)

### ✔️ Expected Behavior

docke version support epub file, same with cloud version.

### ❌ Actual Behavior

- [x] cloud version
[ ] docker version

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/ad65c891e7f38958095dce16584d641537993bd5/api/core/rag/extractor/extract_processor.py#L110

See here, if you config the ` if etl_type == 'Unstructured':`, then it should be supported.
