### ISSUE TITLE
OpenAI-API-compatible 添加第三方API失败！

### ISSUE THREAD

**Issue by BluerAngala** [langgenius/dify#3720]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![ea70e4ebc957c208858939f37ce831b](https://github.com/langgenius/dify/assets/49632180/a318f61b-2259-4385-912a-f06b258206d7)

按照提示添加第三方OpenAI-API，提示 `Credentials validation failed: invalid response object, must be 'chat.completion`。
已检查API接口，并无不妥，疑似 dify 接收数据错误。

### ✔️ Expected Behavior

希望接入第三方 API

### ❌ Actual Behavior

提示 `Credentials validation failed: invalid response object, must be 'chat.completion`。

**Comment by BBM-Freehub** [comment]
oneapi可以，但必须使用root帐号创建的API， Dify才能使用，普通用户生成的API就报Credentials validation failed with status code 403，似乎跟权限有关。

**Comment by robin12jbj** [comment]
dify在线版可以添加,但是本地dify添加同样的内容报错internal server error，如何解决

**Comment by kfchandsome** [comment]
> dify在线版可以添加,但是本地dify添加同样的内容报错internal server error，如何解决

请问解决问题了吗

**Comment by lininn** [comment]
请问解决问题了吗？工具调用报错，新增的也报错

**Comment by robin12jbj** [comment]
> 请问解决问题了吗？工具调用报错，新增的也报错

解决了，检查一下你的服务是否是openAI-API-Compatibale接口规范的，例如/v1/audio/speech
