### ISSUE TITLE
我要如何构建一个能通过多轮对话，不断收集用户信息的客服助手

### ISSUE THREAD

**Issue by 983183947** [langgenius/dify#3722]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

我要如何在多轮对话中，引导用户提供信息，并且通过调用外部接口进行保存。
场景：在业务办理过程中需要录入的信息比较多，用户很难通过一次性描述就把信息提供完整。我要如何让大模型引导用户将信息填写完整。

**Comment by yyyshhh** [comment]
同样的问题请教，如何在Dify中处理这个问题？谢谢

**Comment by yyyshhh** [comment]
谢谢@dosu. 有一个问题多请教一下。我在多轮对话中，对于每一轮收集到的参数会在后面的一些处理流程中用到。举个例子，我一共要收集三个参数：
1. 你的名字是什么？
2. 可以告诉我你的电子邮件地址吗？
3. 你对哪个产品感兴趣？
我每一轮会收集到一个反馈，之后在LLM里面处理这个反馈并提取参数，之后在收集到这三个参数后，我会进行一下后续的处理流程，这个流程中会用到这三个参数。请问在Dify中，如何能在多轮对话场景下，保存这三个参数的信息。

谢谢。

**Comment by lianghengyu** [comment]
@dosu 帮忙回答一下上面这个问题.
我要如何在多轮对话中，引导用户提供信息，并通过调用外部接口进行保存。
场景：在业务办理过程中需要记录的信息比较多，用户很难通过一次性描述来提供完整的信息。我要如何让大模型引导用户将信息填写完整。
