### ISSUE TITLE
different workflow draft state in a workflow in different tabs

### ISSUE THREAD

**Issue by VoidIsVoid** [langgenius/dify#3740]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. create a workflow: Worklow_A.
2. open Worklow_A in two tabs: tab_1, tab_2.
3. add llm node in tab_1, and wait it to auto saved.
4. refresh tab_1 and tab_2

### ✔️ Expected Behavior

tab_1 and tab_2 show the same workflow graph

### ❌ Actual Behavior

tab_1 has the llm node but tab_2 doesn't
![image](https://github.com/langgenius/dify/assets/22066703/950aaa06-c131-4f12-b0e4-8aa4dc9d54a5)
<img width="853" alt="image" src="https://github.com/langgenius/dify/assets/22066703/dbfc731a-fa3c-4e0d-9b35-789837289b2a">

**Comment by crazywoola** [comment]
Well this is not a real-time application, so it happens. And this is not persists in local storage as well. So we think we will remain this issue for a while.
