### ISSUE TITLE
v0.6.4 unable to load model

### ISSUE THREAD

**Issue by mwnu** [langgenius/dify#3741]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgrading to v0.6.4, the system fails to load the model, and the API log shows: "Worker (pid:26) was sent code 132!" Additionally, some console routes in the browser console are responding with a 503 error. If the API service and the web service are not under the same domain, CORS errors may also occur.
```
2024/04/24
05:07:03
[2024-04-23 21:07:03 +0000] [16] [INFO] Starting gunicorn 22.0.0
2024/04/24
05:07:03
[2024-04-23 21:07:03 +0000] [16] [INFO] Listening at: http://0.0.0.0:5001 (16)
2024/04/24
05:07:03
[2024-04-23 21:07:03 +0000] [16] [INFO] Using worker: gevent
2024/04/24
05:07:03
[2024-04-23 21:07:03 +0000] [26] [INFO] Booting worker with pid: 26
2024/04/24
05:07:16
[2024-04-23 21:07:16 +0000] [16] [ERROR] Worker (pid:26) was sent code 132!
2024/04/24
05:07:16
[2024-04-23 21:07:16 +0000] [28] [INFO] Booting worker with pid: 28
2024/04/24
05:07:25
[2024-04-23 21:07:25 +0000] [16] [ERROR] Worker (pid:28) was sent code 132!
```

<img width="692" alt="PixPin_2024-04-24_05-28-11" src="https://github.com/langgenius/dify/assets/45463732/c7192095-3146-42c9-9fe0-28a3149ee160">
<img width="140" alt="PixPin_2024-04-24_05-28-56" src="https://github.com/langgenius/dify/assets/45463732/7228b3a0-3c65-49ef-b712-239d023769dd">

![image](https://github.com/langgenius/dify/assets/45463732/73493254-f5c6-4d9f-9ede-8a66ff515f99)

### ✔️ Expected Behavior

Reverting to version 0.6.3 restores normal functionality.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/3707
