### ISSUE TITLE
Docker-compose Error!

### ISSUE THREAD

**Issue by tuhin37** [langgenius/dify#3748]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Download the [docker-compose.yml](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml) file in a local directory called `dify`

2.  `cd` into the `dify` directory 
3. Run `docker-compose up -d`

### ✔️ Expected Behavior

The docker-compose should have run all the containers in a healthy state and I should be able to access the frontend/dashboard on my local port 80 over `http` protocol

 

### ❌ Actual Behavior

```sh
Starting dify_db_1       ... done
Starting dify_redis_1    ... done
Starting dify_web_1      ... done
Starting dify_weaviate_1 ... done
Starting dify_sandbox_1  ... done
Starting dify_worker_1   ... done
Starting dify_api_1      ... done
Recreating dify_nginx_1  ... error

ERROR: for dify_nginx_1  Cannot start service nginx: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/drag/dify/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /home/drag/dify/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/drag/dify/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /home/drag/dify/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

**Comment by tuhin37** [comment]
I have done some digging around and found that the `nginx:latest` docker container expects `nginx/nginx.conf` to be a file but instead it is a folder.

**Comment by crazywoola** [comment]
Please check existing issues.
