### ISSUE TITLE
Node fix in Chatflow for multi-turn chat

### ISSUE THREAD

**Issue by edolele** [langgenius/dify#3765]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I designed a chatflow including multiple question classifier and LLMs. And I want users to chat with one specific user if the LLM has been chatted in the first talk. However, after the first turn talk, when user start the second turn talk. The chatflow still start from the "START" node. The second query could be redirected to the other LLMs that users don't want. Or even the right LLM was selected, it's too slow for the flow from "START" node to the right LLM node.
![14158](https://github.com/langgenius/dify/assets/16509883/874da99c-94b4-46f2-8964-97b18157d562)

### 2. Describe the feature you'd like to see

If a global variable could be set, which can be used in a IFELSE node, and let the second turn query directly go to the right LLM from the "START" node. For the first turn query, the global variable could be a default value, which are linked to the question classifier, after the node.

### 3. How will this feature improve your workflow or experience?

This feature will greatly improve my workflow, and make my application work. I have successfully tested this mode in AutoGen and Coze. I think it also works in Dify.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/3686
