### ISSUE TITLE
已经 docker 部署了，请问如何升级？

### ISSUE THREAD

**Issue by zhouyangtingwen** [langgenius/dify#377]
Dify version: Cloud | Self Host

## Steps To Reproduce

1.已经 docker 部署了，请问如何升级？git 拉最新代码然后重新跑 docker 吗？现在数据库里已经有数据了，会不会被刷新掉？
2.

**Comment by crazywoola** [comment]
```
docker compose stop
docker compose pull
docker compose up -d
```

**Comment by thinkingFrank** [comment]
历史的chatflow workflow还在吗？
