### ISSUE TITLE
[BUG]Text size is too large, max size is 0.1MB, but current size is 396.64 KB.

### ISSUE THREAD

**Issue by Caplost** [langgenius/dify#3777]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![截屏2024-04-24 16 55 33](https://github.com/langgenius/dify/assets/916463/4548559f-02bf-48dc-9259-1b8becfa6145)

### ✔️ Expected Behavior

when i crateing the workflow and adding the httprequest function it should work.

### ❌ Actual Behavior

got the err: Text size is too large, max size is 0.1MB, but current size is 396.64 KB.

**Comment by Caplost** [comment]
version is 0.6.4

**Comment by crazywoola** [comment]
This results will be store in pg. If it's too big, it's a waste of resources

https://github.com/langgenius/dify/blob/7753ba2d375beb0a5449042fbcbf5ade9a7cffb8/api/core/workflow/nodes/http_request/http_executor.py#L19

See this.
