### ISSUE TITLE
The system model has not yet been fully configured, and some functions may be unavailable.

### ISSUE THREAD

**Issue by shuther** [langgenius/dify#3784]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Using the self hosted version, I setup ollama with few models (chat, completion and embeddings); however, I still see the message:
The system model has not yet been fully configured, and some functions may be unavailable. But I can't select them for the system reasoning model or for the embedding model. Is it expected?

**Comment by takatost** [comment]
Could you please provide some detailed screenshots to help us better understand the issue?
