### ISSUE TITLE
error when testing built knowledge base

### ISSUE THREAD

**Issue by DemonDamon** [langgenius/dify#3789]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/20499644/7649aa6c-61f8-4d1a-a923-b716e979f15d)

### ✔️ Expected Behavior

should recall docs

### ❌ Actual Behavior

(psycopg2.errors.UndefinedColumn) column embeddings.provider_name does not exist LINE 1: ..., embeddings.created_at AS embeddings_created_at, embeddings... ^ [SQL: SELECT embeddings.id AS embeddings_id, embeddings.model_name AS embeddings_model_name, embeddings.hash AS embeddings_hash, embeddings.embedding AS embeddings_embedding, embeddings.created_at AS embeddings_created_at, embeddings.provider_name AS embeddings_provider_name FROM embeddings WHERE embeddings.model_name = %(model_name_1)s AND embeddings.hash = %(hash_1)s AND embeddings.provider_name = %(provider_name_1)s LIMIT %(param_1)s] [parameters: {'model_name_1': 'nomic-embed-text:latest', 'hash_1': '374d72e6b8572032bcce3ac837342d267d25937136abca29bef4883905facd31', 'provider_name_1': 'ollama', 'param_1': 1}] (Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by crazywoola** [comment]
Have you run `flask db migrate`? This seems you haven't run the migration process as expected.
