### ISSUE TITLE
can not save in the bedrock setting page.

### ISSUE THREAD

**Issue by freeword2020** [langgenius/dify#3799]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![error](https://github.com/langgenius/dify/assets/111511767/82bdab48-ba48-4b42-9fcf-8c1652650afa)
![can not save](https://github.com/langgenius/dify/assets/111511767/409798c8-503e-4c1a-968b-7cf83137877b)

### ✔️ Expected Behavior

when I save after inputting the wrong content, there will be an error info. 
But when I input the right content, the save button can not work. Can not save the settings of bedrock.

### ❌ Actual Behavior

But when I input the right content, the save button can not work. Can not save the settings of bedrock.

**Comment by guchenhe** [comment]
can you try starting afresh? can't seem to reproduce this

**Comment by kerlion** [comment]
leave the model name empty. It works for me.

**Comment by longzhihun** [comment]
wrong model id.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
