### ISSUE TITLE
期望回答内容尽可能是数据集

### ISSUE THREAD

**Issue by techflag** [langgenius/dify#38]
我上传了数据集，但是回答内容不能说错，但是能够直接从数据集中返回内容的话，回答的可信度会很高。如果要达到此效果，需要设置什么或者其他什么操作。

**Comment by takatost** [comment]
在应用中的上下文关联数据集即可，如果需要将数据集查到的原文返回，这个我们暂时没有最佳实践，可以自己写 prompt 测试一下，上下文的标识可以使用 `[CONTEXT]` 来指代。

**Comment by techflag** [comment]
已经关联了数据集，是在prompt中直接增加[CONTEXT]这个字符串？

**Comment by takatost** [comment]
这个不用，正常问题和数据集内容相关都会将数据集抽取最匹配的前几条作为上下文，给 AI 理解并返回给用户的。
这个 [CONTEXT] 的意思是指，如果你需要对上下文嵌入的方式或者逻辑在 prompt 做一定调优，可以用这个标识符来指代上下文。

**Comment by techflag** [comment]
大概了解了，做知识库准确度很重要，如果能够回复显示原文也方便做调试。

**Comment by takatost** [comment]
> 大概了解了，做知识库准确度很重要，如果能够回复显示原文也方便做调试。

之后会进一步优化调试页，丰富返回内容和可配置项
