### ISSUE TITLE
Add system role assignment in "Prompt eng" page

### ISSUE THREAD

**Issue by lethe3000** [langgenius/dify#380]
Tell chatGPT the role who it will play is very helpful and can give more precise answers.
So consider add an input `Role` to set the system message of a chat app, something like the `Pre Prompt` input.
The content in the `Role` will send to chatGPT via openai api

```
{
  "messages": [
    {"role": "system", "content": "<You are a helpful assistant.>"}
  ]
}
```

**Comment by takatost** [comment]
We found that the content in the system message (the pre prompt on the web page) often lost attention during our verification process, so that the rules in it were invalid. So we have now moved the pre prompt content to the user message, which works much better.

**Comment by lethe3000** [comment]
I think you are right.
In openai chat models(gpt-3, gpt-4) system message is not handled well as discussed in https://community.openai.com/t/gpt-3-5-turbo-vs-text-davinci-003-chatbot/82806.
I also tested it on playground.

**Comment by takatost** [comment]
No worries, we'll get it back to normal ASAP if OpenAI have messed up the attention system
