### ISSUE TITLE
Token consumption, timestamp is missing

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#3807]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

hover mouse on top of the answer

### ✔️ Expected Behavior

in older version, there is token info and timestamp, see image below:

![Screenshot 2024-04-25 021117](https://github.com/langgenius/dify/assets/5020396/e6949381-247d-4948-b944-e5e0da89921e)

### ❌ Actual Behavior

token info and timestamp is missing

we really like the old statisics and we promised to deliver this feature to our customer. Any chance to revert this or could you point me to the code?

**Comment by crazywoola** [comment]
These information only display in logs section according to our PM and UI. The original one was a bug.

**Comment by lancemao** [comment]
Well, for us this is a feature. Any chance to have a flag or env variable? Or where is the code, I can try to add it back myself
