### ISSUE TITLE
Rename app does not change app name on "run app" page

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#3821]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Cloud, Self Hosted (Source)

### Steps to reproduce

1. Rename an app 
![CleanShot 2024-04-25 at 06 20 13](https://github.com/langgenius/dify/assets/119136210/b26f8498-389c-498b-8c3f-82311d78c154) -> 
![CleanShot 2024-04-25 at 06 20 39](https://github.com/langgenius/dify/assets/119136210/39246e5b-8c52-4e8f-bf72-05348a6b9131)
2. Visit the "Run app" page. - Old name will still show:
![CleanShot 2024-04-25 at 06 20 57](https://github.com/langgenius/dify/assets/119136210/2c1e9a71-f45a-4080-8cb3-aa22ae857949)

### ✔️ Expected Behavior

The renamed app should show the new name on the front end of the app when visiting it with the "run-app."

### ❌ Actual Behavior

Old name is shown.

**Comment by crazywoola** [comment]
Hi there, Please notice that shared application has a separated config setting and you can find it here.

<img width="933" alt="image" src="https://github.com/langgenius/dify/assets/100913391/30dd5e23-a267-45c7-9069-9b0fd39b39fb">
