### ISSUE TITLE
部署后登录失败？

### ISSUE THREAD

**Issue by AKeCode** [langgenius/dify#383]
输入账号密码之后点登录就会重定向到登录页。
<img width="1418" alt="截屏2023-06-15 22 03 19" src="https://github.com/langgenius/dify/assets/46109359/c5ca8bbb-116d-4d4f-833a-19c808751d14">
>
<img width="731" alt="image" src="https://github.com/langgenius/dify/assets/46109359/b1bd079e-fd5d-475c-9418-3d31b85d2802">

**Comment by crazywoola** [comment]
It seems set cookie did not work, can you provide the url in this image?

**Comment by AKeCode** [comment]
> It seems set cookie did not work, can you provide the url in this image?

Yes, but problem solved.

**Comment by MrXWTe** [comment]
> > It seems set cookie did not work, can you provide the url in this image?
> 
> Yes, but problem solved.

你是如果解决的呢？我也发现了这个问题，本地部署后，本机访问成功，但相同局域网下的其他机器访问会出现 ”循环登录“ 的问题。
How did you solve it? I have also encountered this issue. After local deployment, I can access it successfully on my own machine, but when other machines on the same local network try to access it, they encounter a "looping login" problem.

**Comment by AKeCode** [comment]
> > > It seems set cookie did not work, can you provide the url in this image?
> > 
> > 
> > Yes, but problem solved.
> 
> 你是如果解决的呢？我也发现了这个问题，本地部署后，本机访问成功，但相同局域网下的其他机器访问会出现 ”循环登录“ 的问题。 How did you solve it? I have also encountered this issue. After local deployment, I can access it successfully on my own machine, but when other machines on the same local network try to access it, they encounter a "looping login" problem.

COOKIE_HTTPONLY: 'true'
COOKIE_SAMESITE: 'Lax'
COOKIE_SECURE: 'false'

**Comment by MrXWTe** [comment]
> > > > It seems set cookie did not work, can you provide the url in this image?
> > > 
> > > 
> > > Yes, but problem solved.
> > 
> > 
> > 你是如果解决的呢？我也发现了这个问题，本地部署后，本机访问成功，但相同局域网下的其他机器访问会出现 ”循环登录“ 的问题。 How did you solve it? I have also encountered this issue. After local deployment, I can access it successfully on my own machine, but when other machines on the same local network try to access it, they encounter a "looping login" problem.
> 
> COOKIE_HTTPONLY: 'true' COOKIE_SAMESITE: 'Lax' COOKIE_SECURE: 'false'

It works, thanks! ❤
