### ISSUE TITLE
maybe a good idea ! allow multiple front blocks for blocks in workflow editor

### ISSUE THREAD

**Issue by sEANzHAO622** [langgenius/dify#3832]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

It's too cumbersome for me to use the same sub workflow after multiple different preprocessing branches.
I must copy this sub workflow node by node multiple times, and connect and set parameters for them.
There are two solutions.
1. Allow nodes to have multiple entrances
2. Allow multiple nodes to be selected simultaneously for replication while maintaining their connections

当我需要将同一个子工作流用在多个不同的预处理分支后的时候太麻烦了。
我必须要将这个子工作流一个节点一个节点的抄写多遍，并且为他们连线和设置参数。

这有两个解决方案。
1 允许节点有多个入口
2 允许同时选中多个节点进行复制，并保持他们之间的连线

### 2. Describe the feature you'd like to see

1. Allow nodes to have multiple entrances
2. Allow multiple nodes to be selected simultaneously for replication while maintaining their connections

这有两个解决方案。
1 允许节点有多个入口
2 允许同时选中多个节点进行复制，并保持他们之间的连线

### 3. How will this feature improve your workflow or experience?

Significantly reduces workload when configuring complex business processes

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated in discussisons.
