### ISSUE TITLE
support rerank from localAI

### ISSUE THREAD

**Issue by shuther** [langgenius/dify#3839]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Need to support rerank with self hosted approach

### 2. Describe the feature you'd like to see

leverage localAI for rerank as an option

### 3. How will this feature improve your workflow or experience?

good for self hosted and experimentations around rerank

### 4. Additional context or comments

localAI will support this feture soon, see https://github.com/mudler/LocalAI/pull/2121

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Feel free to contribute! 😁
