### ISSUE TITLE
google-generativeai No matching distribution found

### ISSUE THREAD

**Issue by shuther** [langgenius/dify#3846]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

git latest

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce
follow the steps with conda from the documentation; fresh install
```
git pull
cd api
pip install -r requirements.txt   

```

### ✔️ Expected Behavior

every package can be installed

### ❌ Actual Behavior

```
ERROR: Ignored the following yanked versions: 0.1.0rc2
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.9; 0.1.0rc3 Requires-Python >=3.9; 0.1.1 Requires-Python >=3.9; 0.2.0 Requires-Python >=3.9; 0.2.1 Requires-Python >=3.9; 0.2.2 Requires-Python >=3.9; 0.3.0 Requires-Python >=3.9; 0.3.1 Requires-Python >=3.9; 0.3.2 Requires-Python >=3.9; 0.4.0 Requires-Python >=3.9; 0.4.1 Requires-Python >=3.9; 0.5.0 Requires-Python >=3.9; 0.5.1 Requires-Python >=3.9; 0.5.2 Requires-Python >=3.9; 1.4.0 Requires-Python >=3.9; 1.4.0rc1 Requires-Python >=3.9; 1.4.1.post1 Requires-Python >=3.9; 1.4.2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement google-generativeai==0.5.0 (from versions: 0.1.0rc1)
ERROR: No matching distribution found for google-generativeai==0.5.0
```

**Comment by crazywoola** [comment]
Try `pip install -r requirements.txt --upgrade`

**Comment by daxigua-888** [comment]
The error "ERROR: No matching distribution found for google-generative-ai" happens because that package name is an older version for the Gemini API that is no longer supported. The current official package is google-genai.
