### ISSUE TITLE
Ubuntu LTS using docker compose, pgsql pod cannot start and log says not pgsql user.

### ISSUE THREAD

**Issue by MapleEve** [langgenius/dify#3848]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Run a ubuntu LTS 20 ~ 22
use apt or aptitude install docker and docker compose
using docker compose command

BTW, following is the fix:

1. change the pgsql volume with an external volume, not created "root" volume

```yaml
    volumes:
      - pgdata:/var/lib/postgresql/data
```
2. register this volume

```yaml
volumes:
  pgdata:
    external: true
```

3. create a volume outside before run compose 
`docker volume create --name=pgdata`

### ✔️ Expected Behavior

automatic this by default.

### ❌ Actual Behavior

2024-04-25 11:53:41.887 UTC [52] FATAL: data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
2024-04-25 11:53:41.887 UTC [52] HINT: The server must be started by the user that owns the data directory.

**Comment by MapleEve** [comment]
This is related to https://github.com/langgenius/dify/issues/1572 with a solution.

**Comment by crazywoola** [comment]
Have you solved it?

**Comment by MapleEve** [comment]
> Have you solved it?

Soved it locally. But as for a official docker container compose example should specify it

**Comment by dockercore** [comment]
可以执行看下： docker volume ls

**Comment by MapleEve** [comment]
> 可以执行看下： docker volume ls

```
DRIVER    VOLUME NAME
local     pgdata
local     portainer_data

```

这个是本地机器已经创建的volume, 我看portainer这种就可以自动创建volume,如果是映射外部文件夹，文件夹的权限必须和docker的权限一样，但是pgsql本身是不允许root用户允许的，如果你的文件夹是直接被创建出来继承的母文件夹所属，那么pgsql必然会报错。

This refers to a storage volume that has been established on your local system. Tools such as Portainer are capable of automatically generating such volumes. Should you choose to link an external directory, it's crucial that the directory's permissions align with those of Docker. By design, PostgreSQL (referred to as pgsql) prohibits operations under the root user. If the directory in question is created directly and inherits the ownership from its parent directory, PostgreSQL will invariably encounter an error.
