### ISSUE TITLE
文本生成类型的助手无法自动保存

### ISSUE THREAD

**Issue by zxr3680166** [langgenius/dify#3853]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

文本生成类型的助手无法自动保存，经常忘记点发布，一刷新什么都没了，不像工作流会自动保存

### 2. Describe the feature you'd like to see

同样能自动保存

### 3. How will this feature improve your workflow or experience?

我是付费用户，希望体验加强，不出现工作丢失的情况

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by zhangruilin2020** [comment]
我也遇到这个问题，只要一点击其他的，写的prompt就是丢失，没有自动保存；必须点击发布更新才行

目前官方有修复吗？
