### ISSUE TITLE
Minified React error #31

### ISSUE THREAD

**Issue by insistence-essenn** [langgenius/dify#3856]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I just Launched the Dify in Docker and I am getting this error

### ✔️ Expected Behavior

Normal opening of preview Chat

### ❌ Actual Behavior

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btext%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nL (fd9d1056-d69088c1300c58eb.js:1:30216)
    at d (fd9d1056-d69088c1300c58eb.js:1:32122)
    at fd9d1056-d69088c1300c58eb.js:1:34527
    at s (fd9d1056-d69088c1300c58eb.js:1:34818)
    at u (fd9d1056-d69088c1300c58eb.js:1:35901)
    at lL (fd9d1056-d69088c1300c58eb.js:1:57087)
    at iU (fd9d1056-d69088c1300c58eb.js:1:119990)
    at o2 (fd9d1056-d69088c1300c58eb.js:1:94371)
    at fd9d1056-d69088c1300c58eb.js:1:94193
    at o1 (fd9d1056-d69088c1300c58eb.js:1:94200)
window.console.error @ 4938-d19c2f66aebab9fc.js:1
![image](https://github.com/langgenius/dify/assets/59498807/9c3d0db6-6876-4adb-973b-b252f837867f)

**Comment by crazywoola** [comment]
Please upgrade to v0.6.5

**Comment by insistence-essenn** [comment]
Hi Dify Support Team
I am still getting the same error message even after the update to the
specified version from your end.
