### ISSUE TITLE
Enable JSON Output Option for LLM Node

### ISSUE THREAD

**Issue by jicasada** [langgenius/dify#3860]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, this request stems from a specific challenge we have encountered in our current workflow. When utilizing the LLM node, all output data is produced as stringified JSON, which requires additional parsing when integrating with other systems that expect raw JSON format. 

### 2. Describe the feature you'd like to see

I would like to see an enhancement to the LLM node that allows it to output data directly as raw JSON objects, rather than stringified JSON. This feature should include a configurable option within the node's custom properties where users can choose the format of the output—either as a stringified JSON text or as a raw JSON object. 

### 3. How will this feature improve your workflow or experience?

Reduced Complexity: By eliminating the need to parse stringified JSON, we can streamline our data processing tasks. This reduction in complexity speeds up the integration with other systems and reduces the workload on developers who no longer need to write and maintain parsing code.

### 4. Additional context or comments

![image](https://github.com/langgenius/dify/assets/6273003/87bf12f0-8e9d-4800-a463-e9d79b4a7cd6)
This function becomes irrelevant if the output is always in text format.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
Use a code Node after LLM node would be a good choice for you, you can checkout our docs [here](https://docs.dify.ai/features/workflow/node/code#structured-data-processing)

**Comment by Yeuoly** [comment]
> Hey @Yeuoly, I have a similar question. I used the code block after LLM to convert the answer from string to an object. The issue is that **I'm unable to access this output object in other nodes**. I also tried using the variable assigned, but it is not there:
> 
> **BUG?**
> 
> ![image](https://private-user-images.githubusercontent.com/528501/327208264-7a663c71-965e-44d1-9ec2-2470e20a4724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Mjk5MDMsIm5iZiI6MTcxNDYyOTYwMywicGF0aCI6Ii81Mjg1MDEvMzI3MjA4MjY0LTdhNjYzYzcxLTk2NWUtNDRkMS05ZWMyLTI0NzBlMjBhNDcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwNjAwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjMzOGJlMjRmZWMyYWNjNWMzZGY0YjdlMmU4ODhhYWQzOThhZDVkZTA1NTA4YTU5NjUwN2Q4ZTVhMDJkNTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NBGkWVY9J3C-vdcWdtiYCxy4jZd-oqCMeJ0y2y2xid0)

I suggest defining a flat structure output instead of using Object, which means you need to destruct an object into several more basic parameters.
