### ISSUE TITLE
AttributeError: 'MilvusClient' object has no attribute 'create_collection_with_schema'. Did you mean: '_create_collection_with_schema'?

### ISSUE THREAD

**Issue by lizhongxiang12138** [langgenius/dify#3862]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

创建知识库的时候报错
docker-worker-1    |   df = pd.read_csv(csvfile, error_bad_lines=False, **self.csv_args)
docker-worker-1    | 
docker-worker-1    | [2024-04-26 01:53:03,518: DEBUG/MainProcess] Created new connection using: 3ff3aad5c5d44281b21eca3737145a9e
docker-worker-1    | [2024-04-26 01:53:03,540: ERROR/MainProcess] consume document failed
docker-worker-1    | Traceback (most recent call last):
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 73, in run
docker-worker-1    |     self._load(
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 677, in _load
docker-worker-1    |     tokens += future.result()
docker-worker-1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
docker-worker-1    |     return self.__get_result()
docker-worker-1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
docker-worker-1    |     raise self._exception
docker-worker-1    |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
docker-worker-1    |     result = self.fn(*self.args, **self.kwargs)
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 732, in _process_chunk
docker-worker-1    |     index_processor.load(dataset, chunk_documents, with_keywords=False)
docker-worker-1    |   File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 60, in load
docker-worker-1    |     vector.create(documents)
docker-worker-1    |   File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 147, in create
docker-worker-1    |     self._vector_processor.create(
docker-worker-1    |   File "/app/api/core/rag/datasource/vdb/milvus/milvus_vector.py", line 67, in create
docker-worker-1    |     self.create_collection(embeddings, metadatas, index_params)
docker-worker-1    |   File "/app/api/core/rag/datasource/vdb/milvus/milvus_vector.py", line 235, in create_collection
docker-worker-1    |     self._client.create_collection_with_schema(collection_name=collection_name,
docker-worker-1    | AttributeError: 'MilvusClient' object has no attribute 'create_collection_with_schema'. Did you mean: '_create_collection_with_schema'?

### ✔️ Expected Behavior

111

### ❌ Actual Behavior

1111

**Comment by crazywoola** [comment]
Please upgrade to v0.6.5
