### ISSUE TITLE
使用云服务创建的应用，查询内容的字数限制在哪里配置？

### ISSUE THREAD

**Issue by minixalpha** [langgenius/dify#387]
使用云服务部署了一个文本生成应用，模型使用了 gpt-3.5-turbo，最大 token 4000，但应用的“查询内容” 超过 90 个汉字，就提示 "Query is too long"，请问在哪里配置查询内容的字数限制？

**Comment by crazywoola** [comment]
Total Token = Max Token + query
You need to adjust max token to a smaller one eg: 2000
