### ISSUE TITLE
希望能循环调用某一个节点达成具体条件后退出

### ISSUE THREAD

**Issue by zxr3680166** [langgenius/dify#3872]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

如果一个节点需要运行多次就非常麻烦，比如谷歌搜索了 10 个链接，要全部给 jina-ai/reader 读取，就非常麻烦

### 2. Describe the feature you'd like to see

希望能循环调用某一个节点达成具体条件后退出

### 3. How will this feature improve your workflow or experience?

提升工作流效率

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by baojingyu** [comment]
+1

**Comment by HalloMelon** [comment]
+1

**Comment by bdqfork** [comment]
Support now？I can't find it...

**Comment by nicklhy** [comment]
+1

**Comment by lywy233** [comment]
+1
