### ISSUE TITLE
希望dify增加database功能

### ISSUE THREAD

**Issue by xiaoxuan220** [langgenius/dify#3873]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

需要将用户输入的自然语言内容通过LLM整理成结构化的内容以达到持久化

### 2. Describe the feature you'd like to see

将用户输入的自然语言内容通过LLM整理成结构化的内容存到database中，作为用户外挂到大模型外的信息。而不是RAG。类似Coze的database功能。

### 3. How will this feature improve your workflow or experience?

这个功能相比RAG比极大的减少了与大模型交互消耗的token，且可靠性较强，希 望官方大大指导一下是否已经实现，或是考虑是否未来会实现

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by xiaoxuan220** [comment]
没明白什么意思？为什么直接关了？我并没有恶意，因为coze是闭源的，很多接口不给开放，所以建议dify有这个功能，是感觉有什么冒犯吗？

**Comment by crazywoola** [comment]
<img width="641" alt="image" src="https://github.com/langgenius/dify/assets/100913391/efd91f64-8b34-4d91-a8cd-781273d72487">
#1542
