### ISSUE TITLE
The hit-test result is not right

### ISSUE THREAD

**Issue by saifeiLee** [langgenius/dify#388]
I use the original question in my document to test. But Dify can not hit the corresponding text chunk. Here is the original text chunk in dataset:
<img width="1069" alt="image" src="https://github.com/langgenius/dify/assets/28710808/88044f46-dd1b-4cc5-8094-0f50e825dcd8">

Here is the hitting-test result:
<img width="1225" alt="image" src="https://github.com/langgenius/dify/assets/28710808/36309588-4ddf-4a9f-9c04-8986ba922934">

Dify version: Cloud 

## Steps To Reproduce

1. The original dataset can be downloaded here: [Test Dataset](https://docs.google.com/spreadsheets/d/1Zy9Fag-DmadBeRU-Kur7KHRX4D3-gzSN/edit#gid=567952901)
2. Upload to dataset and test with keyword: "酒店找谁"

## The current behavior
The hit result is not what we expected.

## The expected behavior
Dify should hit the text chunk contains the keyword “酒店找谁”

**Comment by cmastro** [comment]
I have the same issue. If I use some dataset, the answer is wrong or incomplete.

**Comment by allentofight** [comment]
+1， the same issue

**Comment by saifeiLee** [comment]
I found that if we exclude redundant text in dataset. The query result can be more accurate.

**Comment by saifeiLee** [comment]
Here is the result of the comparison test.

1. With 'None':
![image](https://github.com/langgenius/dify/assets/28710808/4ab7a1f5-de24-4983-a642-84e495b88eaf)

2. Without 'None':
![image](https://github.com/langgenius/dify/assets/28710808/74ce52ef-9dbc-49e0-af70-4ff06acd7494)
