### ISSUE TITLE
Can the workflow support content vectorization models?

### ISSUE THREAD

**Issue by bravemay** [langgenius/dify#3891]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I have an external vector database with a substantial amount of data that is infeasible to migrate into the dify system. I am looking to integrate a process within the workflow that allows for the vectorization of queries and enables the search of the vector repository via an API interface.

### 2. Describe the feature you'd like to see

the workflow support content vectorization models

### 3. How will this feature improve your workflow or experience?

y

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can build an api tool for this. The workflow can call api instead.
Either use it as a custom tool or use a http block.
