### ISSUE TITLE
用docker部署失败

### ISSUE THREAD

**Issue by aA565169388** [langgenius/dify#390]
error pulling image configuration: download failed after attempts=6: dial tcp 104.18.123.25:443: i/o timeout

**Comment by aA565169388** [comment]
提示这个ip连接超时了

**Comment by crazywoola** [comment]
See this for details [Link](https://serverfault.com/questions/908141/docker-pull-tls-handshake-timeout)

**Comment by lucifer2859** [comment]
> error pulling image configuration: download failed after attempts=6: dial tcp 104.18.123.25:443: i/o timeout

我也遇到了这个问题，你怎么解决的？
