### ISSUE TITLE
Can not save model settings 

### ISSUE THREAD

**Issue by realcarlos** [langgenius/dify#3913]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="577" alt="image" src="https://github.com/langgenius/dify/assets/13853/6737a986-2565-4fbc-be4c-11664a9c14b2">

change max tokens from 512 to 2048, publish , it did not works.

### ✔️ Expected Behavior

keep the settings 

### ❌ Actual Behavior

not saved

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
