### ISSUE TITLE
OpenAI-API-compatible model can't support Perplexity api

### ISSUE THREAD

**Issue by Arbow** [langgenius/dify#3914]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Add Perplexity api model into OpenAI-API-compatible and save
<img width="647" alt="image" src="https://github.com/langgenius/dify/assets/14039/c5b9e8f6-b708-439e-9b39-2beaf47d7af5">

2. Use Perplexity model in workspace app, ASSISTANT's output always empty
<img width="342" alt="image" src="https://github.com/langgenius/dify/assets/14039/ee9107aa-6940-4a7f-afa6-5f9c06dbac69">

3. The browser API call received a response, but the answer field was empty
<img width="1090" alt="image" src="https://github.com/langgenius/dify/assets/14039/a877a08c-acb6-40e4-82bc-6150d7985cc1">

4. I tried using this Perplexity api key in python client, it's ok
5. 
<img width="543" alt="image" src="https://github.com/langgenius/dify/assets/14039/720ceb7b-e23e-419e-9851-ae3b68fa3629">
<img width="994" alt="image" src="https://github.com/langgenius/dify/assets/14039/fbb9c06c-fb1c-4662-93b0-d37eb2e3d1f8">

### ✔️ Expected Behavior

Perplexity model works 

### ❌ Actual Behavior

Perplexity model return empty response

**Comment by Arbow** [comment]
I suspect the problem is in the code api/core/model_runtime/model_providers/openai_api_compatible/llm/llm.py, which looks like it implements its own parsing of the OpenAI-compatible protocols, rather than using the OpenAI client directly.

**Comment by crazywoola** [comment]
> I suspect the problem is in the code api/core/model_runtime/model_providers/openai_api_compatible/llm/llm.py, which looks like it implements its own parsing of the OpenAI-compatible protocols, rather than using the OpenAI client directly.

OpenAI compatible is meant for models supported in the same format. So we didn't use the client directly.

**Comment by Arbow** [comment]
> > I suspect the problem is in the code api/core/model_runtime/model_providers/openai_api_compatible/llm/llm.py, which looks like it implements its own parsing of the OpenAI-compatible protocols, rather than using the OpenAI client directly.
> 
> OpenAI compatible is meant for models supported in the same format. So we didn't use the client directly.

OK, but I think there may be a bug in the code implementation, because the Perplexity api is also compatible with the OpenAI api protocol, but the call to Model did not return a valid result :(

**Comment by Yeuoly** [comment]
Pls specify the delimiter for streaming result to "\n" instead of "\n\n" by default while setup credentials, this issue is due to pplx api is not a standard OpenAI compatible interface.

**Comment by Arbow** [comment]
> Pls specify the delimiter for streaming result to "\n" instead of "\n\n" by default while setup credentials, this issue is due to pplx api is not a standard OpenAI compatible interface.

Cool, it works! Thanks.
