### ISSUE TITLE
For model series that do not yet support Function Calling, we provide a universal ReAct method for invocation.

### ISSUE THREAD

**Issue by myrulezzz** [langgenius/dify#3918]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

How to Achieve Agent Reasoning with Various LLMs?
To make these AI Agents smart, you need a solid base model for reasoning. That's where LLMs come in, with CoT (Chain of Thought) reasoning capabilities. Different model providers support different ways of making these models think, like '[Function calling](https://platform.openai.com/docs/guides/function-calling/function-calling)' and 'ReAct.' Those that use Function Calling usually work better.
Right now, models from OpenAI, ChatGLM, Tongyi, MiniMax, and ERNIE Bot support this Function calling feature.For model series that do not yet support Function Calling, we provide a universal ReAct method for invocation.
Can you explain more about the universal ReAct method and invovation?
For example LLama3 70b when running with Ollama, is there any functionality that i can use tools and custom tools with it?

**Comment by feiwofeifeixiaowo** [comment]
https://github.com/langgenius/dify/blob/661b30784eadb618e43c04809efbd52b33399637/api/core/tools/prompt/template.py#L1

**Comment by feiwofeifeixiaowo** [comment]
In Agent mode, dify will enable ReAct mode by default for models that do not support function calls, for the purpose of invoking tools. 
<img width="1456" alt="image" src="https://github.com/langgenius/dify/assets/4606937/553bcca4-492c-475a-ba60-a059c1e4fd07">

As far as I know, it is currently not possible to edit the ReAct prompts on the webpage, If there is a need, you can manually adjust the content in the following code.
[ReAct Prompt](https://github.com/langgenius/dify/blob/661b30784eadb618e43c04809efbd52b33399637/api/core/tools/prompt/template.py#L1)

You can customize tools from the agent configuration interface, through "tools add" and "custom tool add". Below is the tool I use for testing to obtain the weather.
```json
{
      "openapi": "3.1.0",
      "info": {
        "title": "一个输入城市名称查询天气的函数",
        "description": "一个输入城市名称查询天气的函数",
        "version": "v1.0.0"
      },
      "servers": [
        {
          "url": "http://host.docker.internal:8013"
        }
      ],
      "paths": {
        "/weather": {
          "get": {
            "description": "一个输入城市名称查询天气的函数",
            "operationId": "GetCurrentWeather",
            "parameters": [
              {
                "name": "location",
                "in": "query",
                "description": "一个你想查询的城市名称",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "deprecated": false
          }
        }
      },
      "components": {
        "schemas": {}
      }
    }
```

```Python
from flask import Flask, request, jsonify

app = Flask(__name__)

# Simulated weather data for example
weather_data = {
    "北京": {"temperature": "36°C", "condition": "Cloudy"},
    "巴黎": {"temperature": "24°C", "condition": "Sunny"},
    "Beijing": {"temperature": "36°C", "condition": "Cloudy"},
    "Paris": {"temperature": "24°C", "condition": "Sunny"},
    "Chicago, IL": {"temperature": "10°C", "condition": "Rainy"}
}

@app.route('/weather', methods=['GET'])
def get_current_weather():
    location = request.args.get('location')
    if location:
        weather_info = weather_data.get(location, "Weather data not available for the specified location.")
        if isinstance(weather_info, str):
            return jsonify({"error": weather_info}), 404
        return jsonify({
            "location": location,
            "temperature": weather_info['temperature'],
            "condition": weather_info['condition']
        })
    else:
        return jsonify({"error": "Location parameter is missing"}), 400
if __name__ == '__main__':
    app.run(debug=False)

```
[Custom Tools in Docs](https://docs.dify.ai/tutorials/quick-tool-integration)

**Comment by myrulezzz** [comment]
Ok thanks.So far i used custom tools only and add a swagger file and
chatgpt was able to perform task based in n the swagger file description.
But if i understand correctly the below code can be used to integrate apis
with other llms like llama3 70b correct?

**Comment by myrulezzz** [comment]
And also in custom tools you add the flask app or you are using
individually on the server eunning in a docler?

**Comment by feiwofeifeixiaowo** [comment]
sure. The example above is how I tested the llama3 8B groq API, and it also applies to the llama3 70B.
In the example, the custom tool essentially makes an HTTP request to its own API. I deployed a Flask app on a MacBook to test the custom tool. The version of Docker I used is deployed locally, so the request link for the custom tool uses host.docker.internal.
