### ISSUE TITLE
Can not use API extensions when creating a bot

### ISSUE THREAD

**Issue by Kryto614** [langgenius/dify#3923]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Configure this API in Dify
2. Select this API extension in the App.

reference: https://docs.dify.ai/v/zh-hans/guides/application-design/extension/api_based_extension

### ✔️ Expected Behavior

![1](https://github.com/langgenius/dify/assets/94790114/8b609f76-de0a-4694-84ef-15dd273fda97)

### ❌ Actual Behavior

![2](https://github.com/langgenius/dify/assets/94790114/866b0671-7520-466c-bd16-3ae1e29294ad)

When I load schema from http://192.168.xxx.xxx:8000/openapi.json:
![3](https://github.com/langgenius/dify/assets/94790114/a51ce583-5493-4360-8cd7-e384457a0fa8)

**Comment by Kryto614** [comment]
> It looks like the issue you're encountering with the "invalid schema" error when trying to load the schema from `http://192.168.xxx.xxx:8000/openapi.json` is due to Dify's inability to access internal network API services directly. To resolve this, you should use a tool like Ngrok to expose your local API service to the public internet. This will provide you with a public URL that forwards to your local service, which you can then use in Dify instead of the local network address.
> 
> If you've already set up Ngrok or a similar service and are still facing issues, please ensure that the public URL is correctly configured and accessible from outside your local network. Checking the logs or any specific error messages you receive when attempting to use the public URL in Dify could also offer more insights into what might be going wrong.
> 
> #### Details
> _To continue the conversation, mention @dosu._

Thank you for your detailed guidance, but using Ngrok to expose a local API service to the public network is an enterprise feature of Ngrok.

Is there another way for Dify to call a local API service ?

**Comment by szeng19** [comment]
do you find a way to solve this issue?
