### ISSUE TITLE
Copy button for outputted code

### ISSUE THREAD

**Issue by Woahai321** [langgenius/dify#3931]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When a user is using the chatbot app and the output is code, the user is required to highlight all of the text in the markdown-ed section.

### 2. Describe the feature you'd like to see

It would be great for there to be a "Copy" button in the top right hand corener of the markdown output. For example, when it outputs css, it says CSS in the top left and you could have a copy button in the top right. 
<img width="610" alt="Screenshot 2024-04-28 at 02 05 18" src="https://github.com/langgenius/dify/assets/115117306/915defca-2513-49bf-8a04-e9045433baeb">

### 3. How will this feature improve your workflow or experience?

This will make it easier to copy the outputted code and improve their process.

### 4. Additional context or comments

this kind of copy button is found in the majority of current applications

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
#3719 I have already add this button days ago. What's current version you are using?

**Comment by Woahai321** [comment]
Apologies i will update, this can be closed
