### ISSUE TITLE
When invoking the model plugin, my input is a list. I want to loop through the input content and call the same model. Is this currently supported?

### ISSUE THREAD

**Issue by show88118** [langgenius/dify#3932]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When invoking the model plugin, my input is a list. I want to loop through the input content and call the same model. Is this currently supported?

### 2. Describe the feature you'd like to see

In the workflow, the model plugin can be invoked in a loop with different inputs.

### 3. How will this feature improve your workflow or experience?

In the workflow, the model plugin can be invoked in a loop with different inputs.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Not yet, we are working on this at this moment. 
Duplicated #3634
