### ISSUE TITLE
text embedding error due to Requests rate limit exceeded

### ISSUE THREAD

**Issue by YanxingLiu** [langgenius/dify#3936]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I have added tongyi text embedding v1 & v2 models and I am going to add a knowledge base.
I am using the default setting, as the following figure shows.
<img width="805" alt="image" src="https://github.com/langgenius/dify/assets/42299757/944fdf81-82dc-40ea-a807-92bf46d7c163">

### ✔️ Expected Behavior

The document should be embedded into vector bases.

### ❌ Actual Behavior

But it reports error as the figure shows,
<img width="339" alt="image" src="https://github.com/langgenius/dify/assets/42299757/9e532f4c-d2d6-4e2a-ab6d-e2d01aee4654">
To figure out this error, I run dify locally. And I find the logs report that this is due to the reuqest error of tongyi embedding.
 The figure shows that, the first embedding result is right, but then it reaches the Requests rate limit. 
The none result is then processed and an error is thrown.
So, if there are some methods to process text embedding with in the request rate limit.

**Comment by CaptainDP** [comment]
I also encountered the same problem. Can I set a speed limit or concurrency control on the page to avoid triggering over-limit logic?

**Comment by crazywoola** [comment]
Nope, we have no plan for this feature at this moment.

**Comment by andrekutianski** [comment]
> I also encountered the same problem. Can I set a speed limit or concurrency control on the page to avoid triggering over-limit logic?

Your best option is to implement an LLM proxy server/LLM Gateway to limit the outbound requests to your provider.

Some options are:

* LiteLLM - https://docs.litellm.ai/docs/proxy/docker_quick_start
* Portkey-AI/gateway - https://github.com/Portkey-AI/gateway

Additional readings:
* Mastering LLM Gateway: A Developer’s Guide to AI Model Interfacing - https://mlengineering.medium.com/mastering-llm-gateway-a-developers-guide-to-ai-model-interfacing-630bdd6216cc
* Best LLM gateway on Reddit: https://www.reddit.com/r/LLMDevs/comments/1fdii62/best_llm_gateway/

Best,
Andre Kutianski
https://www.mimirtech.co
