### ISSUE TITLE
Does the Knowledge Base chat interface still not support uploading non-image files?

### ISSUE THREAD

**Issue by tahitimoon** [langgenius/dify#3937]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I have many files in other formats that need to be uploaded, such as word pdf excel。but only images are supported now

### 2. Describe the feature you'd like to see

Want to support more of this type of file upload

### 3. How will this feature improve your workflow or experience?

Parse the file I uploaded through a large model and rate it

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes not yet

**Comment by tahitimoon** [comment]
> Yes not yet

Is there a plan for that?
