### ISSUE TITLE
error: signal: bad system cal!

### ISSUE THREAD

**Issue by chuanzhubin** [langgenius/dify#3945]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Any code block will report this error

**Comment by chuanzhubin** [comment]
Why turn off, don't understand, can't it be reproduced? @crazywoola

**Comment by ArMiku** [comment]
I had this problem too, but I sloved it. You can refer to my solution.
- run `docker rmi` to delete all `langgenius/dify-sandbox` images
- rerun the `docker compose up -d`
