### ISSUE TITLE
Passing additional parameters to flow when embed chat widget on web site.

### ISSUE THREAD

**Issue by hanwayTech** [langgenius/dify#3955]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I create a chat flow and embed code on my site I need pass some parameter to the flow. For example I need pass the user name and the job title the user want to apply and I don't want to bother my customer to input these parameters in the chat window. How can I pass these parameters to my flow? Any way to pass the parameters in the embedded code (window.difyChatbotConfig)?

### 2. Describe the feature you'd like to see

Pass additional parameters to the flow when embed a widget on website.

### 3. How will this feature improve your workflow or experience?

This will convinient customers of website .

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Amandine95** [comment]
请问这个需求解决了吗？
