### ISSUE TITLE
添加 OpenAI-API-compatible时 connection refused

### ISSUE THREAD

**Issue by Alaya-Con** [langgenius/dify#3956]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/137168949/9bdc6610-16ec-4116-818d-c7fd8a0ec26b)
已经通过vllm的openai风格服务启动接口，python和curl调用均可以，但是网页上配置模型时不行。
![image](https://github.com/langgenius/dify/assets/137168949/3a05ff0c-34db-406e-a317-213220136a81)
![image](https://github.com/langgenius/dify/assets/137168949/a63bdb8f-3524-4912-8233-1d0557e8c94b)

### ✔️ Expected Behavior

需要一些帮助，解决以上问题。

**Comment by morning-hao** [comment]
Me too, I am a machine with my own 4090. I have one image using VLLM and another deploying the Dify framework. Then, I used PyCharm to debug VLLM, but Dify didn't work.

**Comment by SpartacusIn21** [comment]
> Me too, I am a machine with my own 4090. I have one image using VLLM and another deploying the Dify framework. Then, I used PyCharm to debug VLLM, but Dify didn't work.

use: http://172.17.0.1:8000/v1
