### ISSUE TITLE
Support MiniMax abab-6.5 family

### ISSUE THREAD

**Issue by ifsheldon** [langgenius/dify#3979]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I'd like to access MiniMax newly released Abab-6.5 models.

### 2. Describe the feature you'd like to see

Support Abab-6.5 and Abab-6.5s

### 3. How will this feature improve your workflow or experience?

We can use these new models which are claimed to have much better performance

### 4. Additional context or comments

The APIs remain the same, so I think we can just add two new entries for these models.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
implemented #4012
