### ISSUE TITLE
when the workflow is finished, the result fails to display

### ISSUE THREAD

**Issue by sapipoZZZ** [langgenius/dify#3993]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

More than 4 LLM nodes are required in the workflow. The total time cost exceeds 1 minute

![image](https://github.com/langgenius/dify/assets/19617283/06edaddc-afab-40a3-ac25-9ccda054dbf0)

**Comment by crazywoola** [comment]
Please attach the exported yml or you can attach the debug screen. Also make sure you have config the output for the end node.

**Comment by sapipoZZZ** [comment]
The problem is fixed in v0.6.6
【Text stream support for workflow app when using LLM node text as End node output by @takatost in https://github.com/langgenius/dify/pull/3798

If the END node in the workflow app contains the LLM text variable, it can support streaming output in typewriter form.】
