### ISSUE TITLE
Flaky tool calls, maybe missing authorization or auth out of sync

### ISSUE THREAD

**Issue by ifsheldon** [langgenius/dify#3999]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have implemented my own plugin with simple bearer authorization. I tested it's usable in the tool panel, but when using it in an agent, there's a chance the tool call fails due to 401 Unauthorized. It's really weird, since sometimes the tool call succeeds.

You can try with a simple plugin with a python backend. Or, I can share my plugin with you since it's just a demo only for testing.

I've check the logs in the api server(see below screenshot). The first 4 calls are produced by an agent I develop. The last two was produced by my testing in the tool panel with the same arguments, no modifications on authorizations.

### ✔️ Expected Behavior

Smooth tool calls when agents try to call a tool with correct authorization

### ❌ Actual Behavior

<img width="1588" alt="image" src="https://github.com/langgenius/dify/assets/39153080/fbc61600-eb02-40f9-a9be-a5cce2c3ec5f">

**Comment by Yeuoly** [comment]
have you added `Bearer` prefix in value field of authorization configuration? it will be added automatically.

**Comment by ifsheldon** [comment]
@Yeuoly Yes, I added the prefix in the tool panel, because when I didn't add it, the test run will fail with 401. 

So I guess it's due to behavior discrepancy between test runner in the tool panel and the tool caller in agent workflows?

**Comment by Yeuoly** [comment]
thanks for telling this, its really weird, I will check it AFAP

**Comment by ifsheldon** [comment]
@Yeuoly FYI, here is the code for the plugin. https://github.com/ifsheldon/gpt_plugin_template_rs

You can reproduce the error like below 
![image](https://private-user-images.githubusercontent.com/39153080/329485524-1f49920e-fd32-4c47-af27-da7896604c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjQ1NDIsIm5iZiI6MTcxNTMyNDI0MiwicGF0aCI6Ii8zOTE1MzA4MC8zMjk0ODU1MjQtMWY0OTkyMGUtZmQzMi00YzQ3LWFmMjctZGE3ODk2NjA0YzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2NTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MmY5NzMwMzYzNDQ5NjNlMWUwYmJjYWQyZjA1ZTNlNjU3ODJhMTA3YWNiOTFiOWZiMGM1ZmVlNDY0MmZkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5YWTh4BUxw0rYP9990bvo5XqiaXSk1FdQvEI5YflW4w)
