### ISSUE TITLE
中文pdf乱码

### ISSUE THREAD

**Issue by linling007** [langgenius/dify#4]
![image](https://github.com/langgenius/dify/assets/22077944/3d436f51-ca3d-4d69-aaa7-dbdec910a2ba)

**Comment by takatost** [comment]
少数PDF可能由于字体或者排版原因导致乱码，这个问题未来接入 OCR 或许可以改善，建议您目前可以使用别的工具导出为 txt 或 md 纯文本文件再进行导入，实在不好意思
