### ISSUE TITLE
更新资源版本到最新，更新不下来

### ISSUE THREAD

**Issue by jellzone** [langgenius/dify#400]
之前几次更新用docker compose pull就可以更新下来
这次版本是 0.3.1 想更新到最新，用docker compose pull命令更新不下来
也不报错，显示正常更新，但是看页面上的版本还是旧的
<img width="557" alt="image" src="https://github.com/langgenius/dify/assets/5356500/21768e0b-47d3-458e-9e0c-12cca3c80a26">
<img width="468" alt="image" src="https://github.com/langgenius/dify/assets/5356500/aa46d6fd-7249-4170-a53b-4230638b07dd">

**Comment by jellzone** [comment]
<img width="456" alt="image" src="https://github.com/langgenius/dify/assets/5356500/fef11297-dcb8-40ca-8feb-d23838181ae6">

**Comment by crazywoola** [comment]
Please check the digest in local environment, and pull it again.
https://hub.docker.com/r/langgenius/dify-api/tags
