### ISSUE TITLE
The Docker type deployment failed, the installation page cannot be opened, please help.

### ISSUE THREAD

**Issue by zidanereal5** [langgenius/dify#4007]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I only modified the mapping port of nginx in the yml file, but cannot open the page when accessing through IP address: 6000/install.
![image](https://github.com/langgenius/dify/assets/123045775/e5613817-c518-4bf6-9892-7dbf43e6168d)
![image](https://github.com/langgenius/dify/assets/123045775/b4058d83-2ae2-4e13-bf0a-7d8378ef9ee2)
![image](https://github.com/langgenius/dify/assets/123045775/99b60393-5509-46e7-b1c0-205902ebf52a)

### ✔️ Expected Behavior

open install page

**Comment by zidanereal5** [comment]
my brower‘s problem

**Comment by qiufeihong2018** [comment]
same question
