### ISSUE TITLE
回答没按训练集中的数据来【bug】

### ISSUE THREAD

**Issue by allentofight** [langgenius/dify#401]
数据传的 text，格式如下

```
问题:xxx
回答:xxx

问题:xxx
回答:xxx

问题:xxx
回答:xxx
```
使用自动模式分段后的问答有一段是下面这样的，
![image](https://github.com/langgenius/dify/assets/1235483/b7e4f2b7-bc1d-4575-8aec-d7c01139d3fd)

但在 preview 中提问却是下面这样这样的回答，不是训练数据中的回答
![image](https://github.com/langgenius/dify/assets/1235483/d76a1c29-c564-484d-9a64-2918abb28d6c)

**Comment by allentofight** [comment]
发现它命中的是下面这一条
![image](https://github.com/langgenius/dify/assets/1235483/1a9d6977-e9f0-4077-ab68-acecae9eb622)

**Comment by allentofight** [comment]
大概知道原因了，回答中最好要增加提问问题中关键词的权重，如在回答中增加几个"机器人掉线"这样的关键词就能命中了

**Comment by rocymp** [comment]
> 大概知道原因了，回答中最好要增加提问问题中关键词的权重，如在回答中增加几个"机器人掉线"这样的关键词就能命中了

向量匹配是按回答内容匹配的么？

**Comment by allentofight** [comment]
> > 大概知道原因了，回答中最好要增加提问问题中关键词的权重，如在回答中增加几个"机器人掉线"这样的关键词就能命中了
> 
> 向量匹配是按回答内容匹配的么？

实测是按切片中内容的匹配度来的
