### ISSUE TITLE
Workflow HTTP request node keeps resetting to default on its own - restore fails as well

### ISSUE THREAD

**Issue by sigvardt** [langgenius/dify#4011]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.5

### Cloud or Self Hosted

Cloud

### Steps to reproduce

See attached video. 

1. Define details of a HTTP request node
2. Save and publish
3. Reload the app
4. HTTP request node has now reset
5. Clicking the restore button shows old saved details of node, but clicking the restore button does not add it to the node again
6. Manually adding the details to the http request node again does not work either

https://github.com/langgenius/dify/assets/6000238/fc521a32-3bdd-4ae1-b63d-beb255459bfb

### ✔️ Expected Behavior

Setting are retained and visible in panel

### ❌ Actual Behavior

Setting selv delete/hide on page reload

**Comment by Yash-1511** [comment]
Same issue i am facing also!

**Comment by sigvardt** [comment]
Thanks for speaking up @Yash-1511! Hoping it will get some attention soon.

**Comment by sigvardt** [comment]
FYI still confirmed to be an issue on 0.6.6 on managed solution.

**Comment by hjlarry** [comment]
I face the same issue too

It seems a frontend issue, when you add this http request pannel once, it auto saved works. But when you re-opened this pannel, the http method always init to POST, body always  reset to None.

**Comment by hjlarry** [comment]
the new version 0.6.7 resolve this issue
