### ISSUE TITLE
support for ollama keep_alive parameter

### ISSUE THREAD

**Issue by bogan-FMA** [langgenius/dify#4024]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

yes

### 2. Describe the feature you'd like to see

support the keep_alive feature of ollama, detailed in https://github.com/ollama/ollama/pull/2146

### 3. How will this feature improve your workflow or experience?

currently the model will unload after 5 min idle, the next reload will take more than 30min for a 70b model.

### 4. Additional context or comments

no

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yash-1511** [comment]
Hey @bogan-FMA ,

You can check #4655 this.
