### ISSUE TITLE
[bug] Question Classifier - needs reconnnecting

### ISSUE THREAD

**Issue by nitrag** [langgenius/dify#4028]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I was trying to figure out why my question classifier was routing to the wrong (and same one everytime) node. When debugging only the Question Classifier step, it showed that it found the correct classification but the routing choice to the next node did not match the result. I am frequently having to disconnect and reconnect the proceeding nodes to fix the issue.

### ✔️ Expected Behavior

The Question Classifier routes to the next node appropriately.

### ❌ Actual Behavior

The Question Classifier returns a proper result but routes to the incorrect node.

**Comment by crazywoola** [comment]
It should be solve now I think, please upgrade to latest version to see if this issue persists. You can open a new issue for this.
