### ISSUE TITLE
增加使用历史对话内容作为新上下文的能力

### ISSUE THREAD

**Issue by johnnyshi1225** [langgenius/dify#403]
**Is your feature request related to a problem? Please describe.**
目前每个问题都是独立的，bot无法从之前的对话中学习，会话不连贯。

**Describe the solution you'd like**
引入langchain的memory能力，例如将历史对话内容summary后，作为context给到新对话的prompt。

**Describe alternatives you've considered**
-

**Additional context**
就像ChatGPT那样，能够将一个会话的历史对话中的内容应用到后续对话。

**Comment by crazywoola** [comment]
duplicate #139
