### ISSUE TITLE
VoyageAI Embedding/Reranker

### ISSUE THREAD

**Issue by semtex1987** [langgenius/dify#4034]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Not a challenge, would just be nice to be able to leverage VoyageAI's task specific embedding models

### 2. Describe the feature you'd like to see

Addition of VoyageAI as a model provider

### 3. How will this feature improve your workflow or experience?

VoyageAI has some useful task specific embedders and rerankers that are targeted for specific verticals

### 4. Additional context or comments

https://docs.voyageai.com/reference/embeddings-api

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by CXwudi** [comment]
To sad to see that Dify didn't plan to add this. Voyage text embedding and rerank models are impressive and I really want to use them in Dify
