### ISSUE TITLE
Where can I find the local file of the robots?

### ISSUE THREAD

**Issue by csningli** [langgenius/dify#4036]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I want to locate the file where the robots/agents/workflows saved, and can't find any information about this in the document and discussions. is it accessible as independent files or integrated into system files?

**Comment by crazywoola** [comment]
It can be download as DSL file in app list. It's not saved, it generated by api.

**Comment by Aaryan-Kapoor** [comment]
Hi, is there a way to automate regular backups for the DSL file? I'm willing to explore scripting routes
