### ISSUE TITLE
升级0.65版本后，上传文件会出现失败。

### ISSUE THREAD

**Issue by koulas** [langgenius/dify#4039]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.65

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

自部署的docker版本，升级0.65版本后，超过1m文件上传会出现上传文件失败，之前5.9版本都是正常的。本机用了nginx反代端口，文件配置上也已经加上client_max_body_size的设置了。
![035df09e39d87369505af5634a6a104](https://github.com/langgenius/dify/assets/2045443/d2ba52d6-3dda-43f0-a873-d6ac64fd5f83)
![264821d852e4f1cf37940ed7f2be28a](https://github.com/langgenius/dify/assets/2045443/976c3957-bf63-481e-9915-d7d636fc0c61)
页面报413错误。
本机nginx的配置
![a1c2dd966fc333fd5e3d0e7a668d4d1](https://github.com/langgenius/dify/assets/2045443/59d93659-8c5b-4bd5-a1df-1c38d1f38213)

### ✔️ Expected Behavior

希望能够上传超过1m文件

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by ganzi01234** [comment]
@koulas 解决了吗？我也遇到同样问题

**Comment by sycodedev** [comment]
I encountered the same error in version 1.8.0. Nginx has been configured with a new client_max_body_size, but it has not taken effect
