### ISSUE TITLE
[FR] Frontend - Customize theme color of chatbot app. 

### ISSUE THREAD

**Issue by dromerolovo** [langgenius/dify#4048]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

The colors of the chatbot app are static. For example, in the Header component, the class that sets the background color is `bg-gradient-to-r from-blue-600 to-sky-500`. This distinctively blue color,  doesn't blend well with some website's styles or doesn't adhere to the design requirements of the website.

### 2. Describe the feature you'd like to see

It would be ideal, without having to fork the chat app and manually change the code, to configure the colors in a way that the embedded frame blends better with the website's style without making the customization too complex. I was thinking of adding an extra field in the `SettingsModal` component, such as "Chat Color Theme".

![SettingsModal](https://github.com/langgenius/dify/assets/49217428/d7090be8-8a8b-40e3-875f-dcfb9cb51244)

### 3. How will this feature improve your workflow or experience?

It will improve the experience of developers and designers that want to include the iframe into a website that have clear or strict design requirements.

### 4. Additional context or comments

Examples using free templates of astro:

![Before_Tailcast](https://github.com/langgenius/dify/assets/49217428/d1a2ee6d-aac0-4d63-8a72-cc75a34b73e3)

![After_Tailcast](https://github.com/langgenius/dify/assets/49217428/d379f6a1-23f4-4810-aa69-f5b2003eadf4)

Inverted style:

![Inverted_Tailcast](https://github.com/langgenius/dify/assets/49217428/2259c1bd-1177-49ab-8e61-d05a9145e679)

![Before_Pinwheel](https://github.com/langgenius/dify/assets/49217428/949d3cf1-788d-459c-b48b-d3dab891245c)
![After_Pinwheel](https://github.com/langgenius/dify/assets/49217428/528ed6c9-0077-4854-a478-27ddc5012abb)

Inverted Style:

![Inverted_Pinwheel](https://github.com/langgenius/dify/assets/49217428/783b974a-9375-482f-94ea-fcb07356f8f5)

@iamjoel Wanted to know what you guys think or what the community, in general, thinks.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by ZuzooVn** [comment]
@dromerolovo Can you share your modification? Thanks

**Comment by dromerolovo** [comment]
@ZuzooVn I haven't had time yet. I'm going to make this this weekend and submit a PR to get feedback.

**Comment by dromerolovo** [comment]
@ZuzooVn https://github.com/langgenius/dify/pull/4767
