### ISSUE TITLE
batched data

### ISSUE THREAD

**Issue by aldopareja** [langgenius/dify#4049]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Sometimes you generate workflows that should be applied to many different datapoints or a whole `dataset` simil to `dataset.map(apply_workflow)` that you do with hf Dataset. You load a datapoint and you want to apply the same workflow to each datapoint (specifying a column like `prompt`). I don't think that is doable at the moment and it's a very basic use case of a workflow for data manipulation.

**Comment by takatost** [comment]
What's your use case and what do you need to do? 🤔

**Comment by galer7** [comment]
Not OP, but one of my use cases is:
- text input -> LLM to split into multiple strings e.g. ToC as input and I get an array with the chapters/subchapters 
- I want to apply a workflow to each generated section individually

**Comment by lazyFrogLOL** [comment]
This feature works like map reduce. After data input into the workflow, multiple LLMs generate multiple results, which are then aggregated through reduce to form a final result.

**Comment by crazywoola** [comment]
See this also, https://github.com/langgenius/dify/issues/4275, will close this one.
