### ISSUE TITLE
用Iframe嵌入到html页面中的web应用无法显示标题栏（包括重置对话按钮）

### ISSUE THREAD

**Issue by futureflare** [langgenius/dify#4054]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [ ] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

我将web应用嵌入到html页面中，不能显示标题栏，而F12以后，却可以看到蓝色的标题栏目。缺少标题栏，用户无法重置对话。
<img width="708" alt="dify发布的web应用无法正常显示标题栏" src="https://github.com/langgenius/dify/assets/16436725/60ed5ea3-214a-4f6d-b005-3e860137848a">
<img width="708" alt="放到html页面中的web应用不能显示标题栏" src="https://github.com/langgenius/dify/assets/16436725/a756627d-3eac-4c3f-af20-693ade3944b0">

### ✔️ Expected Behavior

正常应该显示标题栏目，或者是可以提供一个会话重置的按钮连接。

### ❌ Actual Behavior

web应用中，无法显示标题栏。
<img width="708" alt="放到html页面中的web应用不能显示标题栏" src="https://github.com/langgenius/dify/assets/16436725/4a2ea1a2-5bac-44dd-ad00-4aea1e08390b">

**Comment by dromerolovo** [comment]
Hi @futureflare You should adhere to "I confirm that I am using English to submit this report (我已阅读并同意 https://github.com/langgenius/dify/issues/1542). So everyone can understand this."

That behavior is expected, the header will only show if the window width is less than 640px, if is more is going to return null. So I'm guessing that you are using the first way to embed the frame: 

这种行为是预期的，标题栏只会在窗口宽度小于640像素时显示，如果宽度大于640像素，则会返回null。所以我猜你正在使用第一种方式嵌入框架。

![image](https://github.com/langgenius/dify/assets/49217428/3f549990-fb73-4dd9-af8c-cc85678c0f8f)

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by futureflare** [comment]
这个问题导致中文结果无法继续处理。



***@***.***
 
发件人： Diego Romero-Lovo
发送时间： 2024-05-02 20:40
收件人： langgenius/dify
抄送： futureflare; Mention
主题： Re: [langgenius/dify] 用Iframe嵌入到html页面中的web应用无法显示标题栏（包括重置对话按钮） (Issue #4054)
Hi @futureflare You should adhere to "I confirm that I am using English to submit this report (我已阅读并同意 #1542)." So everyone can understand this.
That behavior is expected, the header will only show if the window width is less than 640px, if is more is going to return null. So I'm guessing that you are using the first way to embed the frame:
这种行为是预期的，标题栏只会在窗口宽度小于640像素时显示，如果宽度大于640像素，则会返回null。所以我猜你正在使用第一种方式嵌入框架。
image.png (view on web)
