### ISSUE TITLE
I am unable to use the image generation function of stability properly.

### ISSUE THREAD

**Issue by moyudaduizhang** [langgenius/dify#4055]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/113818551/4eb1e62f-4eff-4bac-a225-65570cd8910b)

### ✔️ Expected Behavior

I would like to randomly generate some images.

**Comment by crazywoola** [comment]
You can expand the call step in the image to see what going on under hood, if the api can not return the image, then we can not neither.
