### ISSUE TITLE
Added Azure OpenAI Service Model, error when selecting base model "gpt-4-turbo-2024-04-09"

### ISSUE THREAD

**Issue by Caixiaopig** [langgenius/dify#4057]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Enter Settings -> Model Provider
2. Click Add Azure OpenAI Service Model
3. Fill in the required fields in the form, and select `gpt-4-turbo-2024-04-09` as the Base Model
4. **Alert error: `Base Model Name gpt-4-turbo-2024-04-09 is invalid`**
5. Bug change the `Base Model Name` to `gpt-4-0125-preview` and can successfully add it

![WX20240502-233838@2x](https://github.com/langgenius/dify/assets/659662/c612a197-3793-401e-aacf-b0970d219d4d)

### ✔️ Expected Behavior

`Base Model Name` selected `gpt-4-0125-preview` was successfully added

### ❌ Actual Behavior

Change the `Base Model Name` to `gpt-4-0125-preview` and can successfully add it

**Comment by nsvrana** [comment]
Same issue for me when using gpt-4-turbo-2024-04-09 on Azure OpenAI.

![image](https://github.com/langgenius/dify/assets/4226491/4481cdc7-ca65-4119-bf82-a091d8d0eb99)

**Comment by shelltea** [comment]
I encountered the same issue, and it was resolved by setting the base model to `gpt-4`. However, this setup results in the inability to use the `vision` feature. I hope it can be fixed as soon as possible.
<img width="596" alt="image" src="https://github.com/langgenius/dify/assets/864375/8faac6f0-f4e2-462e-9bda-6c43f3eaebae">

**Comment by nsvrana** [comment]
Use GPT-4-Vision and you will be able to use all of the functionality until this is fixed.

**Comment by shelltea** [comment]
In version 0.6.7, this issue has been fixed and can now be closed.
