### ISSUE TITLE
知识库检索 后出现的引用文档，点击后，能否可以直接预览文档或者可以下载该文档。

### ISSUE THREAD

**Issue by star562** [langgenius/dify#4069]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

有

### 2. Describe the feature you'd like to see

知识库检索 后出现的引用文档，点击后，能否可以直接预览文档或者可以下载该文档。

### 3. How will this feature improve your workflow or experience?

可以应用在文档检索场景。

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Stephenzza** [comment]
Any future plan?

**Comment by darkshine10086** [comment]
在使用知识库管理文档的时候，需要查找到原文（更多的上下文来看），目前来说，增加文档下载功能，直接到本地看可能是更简单的做法。同时我也需要在提示词包含图片，知识库找回时带上图片的功能。比如客服问答的时候，话术库中有联系方式和微信二维码

**Comment by xiasf** [comment]
可以实现，提示词：如果回答内容中有 `![image]()` 请输出图片。   Version 1.1.3

![Image](https://github.com/user-attachments/assets/efa99277-4b67-4428-a2eb-22a0e086ca15)
