### ISSUE TITLE
增加附加输出模块

### ISSUE THREAD

**Issue by blackwhite084** [langgenius/dify#4073]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

我需要在llm输出的回复后面增加一些信息，但不希望把这部分信息让llm保存在聊天记录里面，因为llm会继续模仿我增加的这些信息，所以希望能以一个新的card形式输出信息，而不仅仅只能从“直接回复”里面输出

### 2. Describe the feature you'd like to see

在ai的回复里面，可以增加多个card，显示一些自定义的附加信息

### 3. How will this feature improve your workflow or experience?

好用

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Close due to #1542
