### ISSUE TITLE
dify 0.6.6 fails to deploy local xinference model

### ISSUE THREAD

**Issue by lk1983823** [langgenius/dify#4074]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have docker built the update version of dify 0.6.6 . I follow the instructions to deploy a local qwen-vl-7b model under xinference. I have used my computer ip address and xinference's default ports 9997. But it failed.
My os version is Ubuntu 22.04

![dify_failed](https://github.com/langgenius/dify/assets/20237650/9614b447-42ba-49cf-9fbd-4b20c409a183)
![dify_failed2](https://github.com/langgenius/dify/assets/20237650/0844b5c9-bc98-48d1-b19d-2ed536fe0acd)
![dify_failed3](https://github.com/langgenius/dify/assets/20237650/4de49a03-2aea-400b-b6f9-12d5a9864fa6)

### ✔️ Expected Behavior

I am expecting to deploy the model successfully. 

### ❌ Actual Behavior

It shows 
`Xinference credentials validate failed: get xinference model extra parameter failed, url: http://192.168.31.191:9997/v1/models/qwen-vl-chat, error: HTTPConnectionPool(host='192.168.31.191', port=9997): Max retries exceeded with url: /v1/models/qwen-vl-chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe983bb11e0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by takatost** [comment]
You can directly curl the xinference API address inside the container to check if it's reachable. It might be a firewall issue.
