### ISSUE TITLE
Update knowledge base description via API

### ISSUE THREAD

**Issue by octopuslabs-fl** [langgenius/dify#4088]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am trying to automate the update of a knowledge base through API. This updates take into consideration file system changes.

### 2. Describe the feature you'd like to see

Given that the knowledge-base description is used by the LLMs to scrutinize if the knowledge base should be used, I would like to update the knowledge base description accordingly.

### 3. How will this feature improve your workflow or experience?

It will help me further automate dify

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by JohnJyong** [comment]
API for knowledge base settings modification will be added @octopuslabs-fl
