### ISSUE TITLE
When will the 'Sync from website' feature in 'Knowledge' be released?

### ISSUE THREAD

**Issue by leeumm** [langgenius/dify#4089]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

When will the 'Sync from website' feature in 'Knowledge' be released?

**Comment by guchenhe** [comment]
some work is under way :) what would you like to see?

**Comment by spencerwongfeilong** [comment]
> some work is under way :) what would you like to see?

Able to crawl content from website, with auto crawling and sync every few hours. Best if can performs hands off to a live agent like chatwoot
