### ISSUE TITLE
feature request: support receiving lark bot webhook to trigger workflow

### ISSUE THREAD

**Issue by cnwangjie** [langgenius/dify#4092]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I saw there is a feature request for triggering workflow by Slack webhook.
The Lark is also another popular IM for many people. It's very useful it is possible to receive a Lark bot webhook to trigger the workflow.

### 2. Describe the feature you'd like to see

Same as above.

### 3. How will this feature improve your workflow or experience?

Same.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by guchenhe** [comment]
It seems like you should be making a Slack / Lark app on their side that run Dify workflows🤔 slack was integrated as a tool instead of a workflow trigger.

**Comment by cnwangjie** [comment]
> It seems like you should be making a Slack / Lark app on their side that run Dify workflows🤔 slack was integrated as a tool instead of a workflow trigger.

I realize it after I submitted this issue. And it also shouldn't be a data source. 

Maybe making a Lark app with code is a solution by if I wrote code it will be unnecessary to use a no code tool like Dify. 😂

Still thank you for your great works. But making the Slack/Lark app as workflow trigger will be awesome.

**Comment by jaredliu233** [comment]
same requirement

**Comment by lvtujingji** [comment]
same requirement
