### ISSUE TITLE
Custom URL support variables

### ISSUE THREAD

**Issue by yipingxx** [langgenius/dify#4109]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I tried to introduce URL variables through {} when creating custom tools, but unfortunately, Dify does not recognize them.

### 2. Describe the feature you'd like to see

Many APIs are RestFul style, and supporting variables in URLs would be very helpful for users to use custom tools.

### 3. How will this feature improve your workflow or experience?

same  as 2.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by yipingxx** [comment]
<img width="643" alt="desc" src="https://github.com/langgenius/dify/assets/48935226/1886a026-15d0-4c7c-a374-b979302600d5">

**Comment by Yeuoly** [comment]
it's a frontend issue, Dify does support URL variables, just try it out :)
