### ISSUE TITLE
Not getting correct results with Classification (bug in 3+ categories)

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4111]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Create a classification node with 3 classes:
![CleanShot 2024-05-06 at 08 26 06](https://github.com/langgenius/dify/assets/119136210/57942f0b-8d88-4819-b4fa-418fcd5c4d92)

### ✔️ Expected Behavior

The flow goes into the correct node.

### ❌ Actual Behavior

The output from the classification is correct, but the flow continues in the wrong direction.

**Comment by AndyMik90** [comment]
The issue seems to be with double quotas, as removing them did make the classification go to the correct node.

**Comment by natarajan0007** [comment]
@AndyMik90 I am also facing the same issue. Can you explain in brief how you overcome with this?

**Comment by AndyMik90** [comment]
> @AndyMik90 I am also facing the same issue. Can you explain in brief how you overcome with this?

Check if you are using double quotes or single quotes in your class descriptions, I had "hi" in my class and the " was making the formatting of the class_name output wrong.

**Comment by JohnJyong** [comment]
optimized by below PR： https://github.com/langgenius/dify/pull/4147 @AndyMik90 @natarajan0007

**Comment by natarajan0007** [comment]
> > @AndyMik90 I am also facing the same issue. Can you explain in brief how you overcome with this?
> 
> Check if you are using double quotes or single quotes in your class descriptions, I had "hi" in my class and the " was making the formatting of the class_name output wrong.

Just saw your discord messages . I got it . let me try with that approach. @JohnJyong I am not when it will be released.

**Comment by natarajan0007** [comment]
I updated this code directly on docker still. I am facing issue with the classification in the api logs it shows correct clasification . However on the front end it still going to first class
<img width="1490" alt="image" src="https://github.com/langgenius/dify/assets/17359328/5b9743c1-cdde-4214-8c05-2051bbbde298">
<img width="1275" alt="image" src="https://github.com/langgenius/dify/assets/17359328/79c9b348-6f39-446f-85a3-9ab71d4c95af">
