### ISSUE TITLE
如何在工作流中使用工具

### ISSUE THREAD

**Issue by 983183947** [langgenius/dify#4113]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

在workflow中调用工具需要传入多个参数，但是LLM的输出只能输出一个text，我要如何提取参数或者能否直接调用我在本平台的Agent？

**Comment by crazywoola** [comment]
Close due to #1542
