### ISSUE TITLE
Credentials validation failed with status code 500

### ISSUE THREAD

**Issue by fuckqqcom** [langgenius/dify#4114]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

自己部署的docker服务，上周可以在这里添加自己封装的api,今天删除掉，再添加一直报错
![image](https://github.com/langgenius/dify/assets/9391575/d0317e7b-f775-4872-8ce1-c46edf3c7795)
很奇怪，刚部署完后登录正常，可以正常添加，中间没升级过任何版本，部署的2个dify服务今天测试的时候全出现这个问题

**Comment by takatost** [comment]
Could you please paste the error message you encountered (from the API service logs)?
