### ISSUE TITLE
cannot update enabled of segment with api

### ISSUE THREAD

**Issue by Gaocarri** [langgenius/dify#4117]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

* use api：/datasets/{dataset_id}/documents/{document_id}/segments/{segment_id}
* request body: {"segment":{"enabled":true,"content":"xxxxxxsssssssssxxxxxs"}}

enabled dosent work
when enabled is true，enabled of this segment cannot update, 
but when enabled is false,  enabled of this segment  will update, works fine

### ✔️ Expected Behavior

when enabled is true，enabled of this segment will update

### ❌ Actual Behavior

when enabled is true，enabled of this segment will not update

**Comment by JohnJyong** [comment]
fix by pr: https://github.com/langgenius/dify/pull/4151  @Gaocarri
