### ISSUE TITLE
本地部署出错按照教程来的，啥也没改Python-dotenv could not parse statement starting at line 25

### ISSUE THREAD

**Issue by luolin-ai** [langgenius/dify#412]
![image](https://github.com/langgenius/dify/assets/135555634/a350c9fa-134b-4a0d-8365-5599e495556b)
root@C20230408009359:/www/wwwroot/dify/api# flask db upgrade
Python-dotenv could not parse statement starting at line 25
WARNING:dotenv.main:Python-dotenv could not parse statement starting at line 25
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.

**Comment by crazywoola** [comment]
Did you copy `.env.example` to `.env` in /api?
If not, this will happen.
