### ISSUE TITLE
'Newline' not escaped when passed as string to HTTP request

### ISSUE THREAD

**Issue by sigvardt** [langgenius/dify#4122]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Pass a text with a newline char (not \n) to HTTP request block
2. Newline char is converted to \n
3. All other special chars are escaped, but not \n

### ✔️ Expected Behavior

- Expected newline to be escaped like \n and other special chars are 

### ❌ Actual Behavior

- All other special chars are escaped, but newline is just converted to \n without being escaped

**Comment by perzeuss** [comment]
In which field do you paste a new line? Could you please provide a screenshot?
