### ISSUE TITLE
New Workflow Block for Saving Data to Knowledge

### ISSUE THREAD

**Issue by patryk20120** [langgenius/dify#4129]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, I am looking for a way to enhance the functionality of the workflow diagrams by adding the ability to save additional documents into knowledge e.g. for personal assistants.

### 2. Describe the feature you'd like to see

I propose a new block that can take an input variable and save it directly into the knowledge base. This block would have an input variable and knowledge selection, and the input variable would be saved into the knowledge base, similar to manually adding a new document.

### 3. How will this feature improve your workflow or experience?

This feature would allow the application to directly write to the knowledge base, creating new possibilities for more personalized and interactive assistants. For example, it could enable the creation of personal assistants that can remember specific memories.

### 4. Additional context or comments

None. I would like to add that I would love to contribute to the development of this feature. I am ready to dive into the code and create this feature, only if Dify team will give a green light on this and confirm that this is not under development already.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by VincePotato** [comment]
This is a great idea. We are considering designing a temporary knowledge base feature that would allow end users to upload files, temporarily store the parsed content, and enable semantic search across the temporary knowledge base in subsequent conversations, similar to the ChatPDF. 

Unlike the current dify knowledge base, this temporary knowledge base would not require users to pre-create it, nor would it involve persistent storage. We plan to start designing this feature once the file upload version is released.

If you have any further suggestions, feel free to leave a message. Thanks!
