### ISSUE TITLE
Help:国内拉取镜像实在是太困难了，求助。

### ISSUE THREAD

**Issue by jinghai** [langgenius/dify#413]
试过加入各种国内docker镜像源，但依然无效
![image](https://github.com/langgenius/dify/assets/5433705/325553b6-4acb-412b-a17d-9b1a0f8ff78a)
为什么拉镜像总会到cloudflare：error pulling image configuration: Get https://production.cloudflare.docker.com/，有什么办法可以解决吗，2天了，镜像还没拉取下来，请各位大神指点，谢谢

**Comment by sweeyoyo** [comment]
我也是一直更新不成功

**Comment by takatost** [comment]
you can try changing the mirror source to pull the image:
```
{
    "registry-mirrors": [
        "http://hub-mirror.c.163.com",
        "https://docker.mirrors.ustc.edu.cn",
        "https://registry.docker-cn.com"
    ]
}
```

**Comment by aA565169388** [comment]
是的  我也是添加了各种加速源发现没有任何作用

**Comment by aA565169388** [comment]
成功了，答主可以登录这个网站https://dockerproxy.com/，通过这个网站代理拉取镜像然后重新命名就好了

**Comment by jinghai** [comment]
> 成功了，答主可以登录这个网站[https://dockerproxy.com/，通过这个网站代理拉取镜像然后重新命名就好了](https://dockerproxy.com/%EF%BC%8C%E9%80%9A%E8%BF%87%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E4%BB%A3%E7%90%86%E6%8B%89%E5%8F%96%E9%95%9C%E5%83%8F%E7%84%B6%E5%90%8E%E9%87%8D%E6%96%B0%E5%91%BD%E5%90%8D%E5%B0%B1%E5%A5%BD%E4%BA%86)

这个可以，拉取成功能，感谢

**Comment by sigkdd2024doubleblind** [comment]
确实镜像需要挂VPN不然下载不了。我自己挂了VPN一会儿就pull成功了。

**Comment by Feng-200** [comment]
![docker](https://github.com/user-attachments/assets/01fa2ebb-0a3f-40b2-9fe1-41b2610efda7)
我也是，一直waiting！！！

**Comment by wangjian0019** [comment]
我的是Ubuntu系统，有图形化界面。
一、我先安装了一个Clash，带图形化界面的，用于启动代理。
1.安装Clash：https://www.clashverge.dev/install.html#_1
2.解决无法安装deb的问题：https://blog.csdn.net/Listen2You/article/details/106909834和https://blog.csdn.net/weixin_43782998/article/details/128015878
附：进行Clash配置，可以自己了解下https://portal.shadowsocks.au/index.php。
能访问谷歌了，但是Docker还是无法pull镜像，因为终端、Docker、Docker镜像使用代理都需要单独配置。
二、先只配置Docker的代理就行
参考这个https://www.cnblogs.com/Chary/p/18096678，我是通过那个在/etc/docker/daemon.json中增加代理配置完成的。
"proxies": {
    "http-proxy": "http://127.0.0.1:7897",
    "https-proxy": "http://127.0.0.1:7897"
  }

还在下载，不知道后续有没有坑啊。
<img width="844" alt="image" src="https://github.com/user-attachments/assets/949f7919-4eee-4c2d-93b8-304d78adfe97">

**Comment by Liwx1014** [comment]
> 成功了，答主可以登录这个网站[https://dockerproxy.com/，通过这个网站代理拉取镜像然后重新命名就好了](https://dockerproxy.com/%EF%BC%8C%E9%80%9A%E8%BF%87%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E4%BB%A3%E7%90%86%E6%8B%89%E5%8F%96%E9%95%9C%E5%83%8F%E7%84%B6%E5%90%8E%E9%87%8D%E6%96%B0%E5%91%BD%E5%90%8D%E5%B0%B1%E5%A5%BD%E4%BA%86)
源镜像名称是什么啊

**Comment by liyunzhi1993** [comment]
"registry-mirrors": [
    "https://docker.1panel.live",
    "https://docker.nju.edu.cn",
    "https://docker.m.daocloud.io",
    "https://dockerproxy.com",
    "https://hub-mirror.c.163.com",
    "https://docker.mirrors.ustc.edu.cn",
    "https://registry.docker-cn.com",
    "https://registry.cn-hangzhou.aliyuncs.com"
  ]

用这个 来源https://blog.csdn.net/yangshangwei/article/details/146280509
