### ISSUE TITLE
Frontend - Running error

### ISSUE THREAD

**Issue by superVicc** [langgenius/dify#4130]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/167748286/b5347082-646d-4550-af61-f04db8fff06a)
and
![image](https://github.com/langgenius/dify/assets/167748286/b504f366-9521-40a3-8140-a0df76e2acb0)

**Comment by patryk20120** [comment]
What version of node do you use?

**Comment by superVicc** [comment]
> What version of node do you use?

v20.12.2

**Comment by JohnJyong** [comment]
@superVicc pls check your local postgresql , the table : 'tags' and 'tag_bindings'  are exist or not , thanks
