### ISSUE TITLE
When I set the segmentation of the knowledge base document to "use Q&A segmentation mode" and save it, clicking on the document preview results in a blank page and an interface error

### ISSUE THREAD

**Issue by dohkoxiaozu** [langgenius/dify#4132]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/48460761/e96faed8-e2dd-4287-9dfc-cf5e07ea5bef)

![image](https://github.com/langgenius/dify/assets/48460761/5fa46c6d-3abd-43c2-91c3-4fc3dab659f2)

![image](https://github.com/langgenius/dify/assets/48460761/69a9b95a-5f2e-42ee-a285-7cb972513135)

![image](https://github.com/langgenius/dify/assets/48460761/7df9bc38-8d73-4b84-b07f-27c74ff89bc9)

### ✔️ Expected Behavior

normal running.

### ❌ Actual Behavior

error happing, and the model is loading incorrect.

**Comment by JohnJyong** [comment]
what's error msg returned in the '/indexing-estimate' endpoint ? @dohkoxiaozu

**Comment by nhha1602** [comment]
I have same isssue with dify 0.7.0.

I tested with English or Vietnamse, it was same.

![image](https://github.com/user-attachments/assets/973d37e6-a99c-4b02-877d-f405cb307f64)

There is no error on dify-api.
