### ISSUE TITLE
Workflow http node is saved, click the node and the node will be reset.

### ISSUE THREAD

**Issue by SuperBugs** [langgenius/dify#4135]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![1](https://github.com/langgenius/dify/assets/24450930/58ffc05f-0477-4771-98da-3ae93a841bae)
![2](https://github.com/langgenius/dify/assets/24450930/9dd921dc-777e-4183-9da7-66d604e6aa4a)

**Comment by zxhlyh** [comment]
fixed https://github.com/langgenius/dify/pull/4127
