### ISSUE TITLE
Summarize context and generate new query before retrieval knowledge

### ISSUE THREAD

**Issue by sinomoe** [langgenius/dify#4139]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I was building a RAG bot using agent workflow and wanted to retrieve knowledge based on context and user input during Knowledge Retrieval, but I found that the Knowledge Retrieval node does not have contextual summarization capabilities, which causes Knowledge Retrieval to return unexpected results

### 2. Describe the feature you'd like to see

eg.

User: who is alex?
Knowledge Retrieval: who is alex?
Knowledge Retrieval Response: [chunks]
User: what did he major in?
Knowledge Retrieval *(summarize previous context and user input)* : what did alex major in?
Knowledge Retrieval Response: [chunks]

### 3. How will this feature improve your workflow or experience?

Make the results of knowledge retrieval more accurate and avoid generating incorrect answers

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Is the `query rewrite node` based on memory and query what you need?

**Comment by sinomoe** [comment]
> Is the `query rewrite node` based on memory and query what you need?

Sounds like it could work. Is it a new node in development?

**Comment by takatost** [comment]
In the roadmap, it's possible that support could be added as early as this month.
cc @VincePotato

**Comment by lhysdl** [comment]
I had the same issue，has the query rewrite node released already？or have any alternative solution ？Thanks
