### ISSUE TITLE
long-term memory feature. summarize text and store in a vector database

### ISSUE THREAD

**Issue by tianlongwang** [langgenius/dify#4149]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I'm trying to get the agent to remember long term events from previous conversations. I'm building a therapist. 

### 2. Describe the feature you'd like to see

![image](https://github.com/langgenius/dify/assets/1435138/d414e7c6-f482-48ce-9073-61c88b0085e4)
Summarize conversation in to a vector db. Looking up long term memory db with RAG before replying. 

### 3. How will this feature improve your workflow or experience?

The bot I'm building would be much more human. 

### 4. Additional context or comments

coze can do that. I hope you can do that as well. 

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by patryk20120** [comment]
I think this will be similar https://github.com/langgenius/dify/issues/4129

**Comment by vontainment** [comment]
I made this to be used with Dify: https://github.com/vontainment/v-gpt-qdrant-api
It is a tool that makes a save memory and recall memory tools. You can use a separate qdrant db or use difys qdrant db if that's what used for vector storage. It don't make it part of the knowlage base but its like mini sharable knowlage bases.

**Comment by cuckootan** [comment]
We also need this feature, is there a plan to support that?

**Comment by TianzeWang** [comment]
May I ask how is the status of this feature? Is it supported?

**Comment by VincePotato** [comment]
We are designing a feature within chatflow called "memory variables" to store information that the LLM needs to remember. Memory variable's scope can be set to either session-based or user-based, such as chat history, order ID, user preferences, etc. You can orchestrate the read and write logic of memory variables within chatflow, making it more flexible.I hope this helps with your issue.
