### ISSUE TITLE
can't run api with jieba error

### ISSUE THREAD

**Issue by cjdxhjj** [langgenius/dify#4150]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

according to the doc https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/local-source-code
![image](https://github.com/langgenius/dify/assets/5616997/a3373975-8aaf-4701-b5f6-11c27af68798)
i build python 3.10.14 with openssl 3.3.0, install the requirement.txt and install the pytorch then i install the ffmpeg
when i run the 
flask run --host 0.0.0.0 --port=5001 --debug
it report the jieba error

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/5616997/14e192d1-0bb3-45c2-85f0-7c835260db36)
![image](https://github.com/langgenius/dify/assets/5616997/5cd12e54-4f80-4120-8d4e-18a83dbfd524)

**Comment by cjdxhjj** [comment]
the celery -A app.celery worker -P gevent -c 1 -Q dataset,generation,mail --loglevel INFO command report the same error
![image](https://github.com/langgenius/dify/assets/5616997/793c206c-58a2-427d-919e-5dd50a923a39)

**Comment by JohnJyong** [comment]
pls use below command to reinstall your requirements 
```
pip install -r requirements.txt --upgrade --force-reinstall
```
@cjdxhjj

**Comment by cjdxhjj** [comment]
thanks very much, that works

**Comment by cjdxhjj** [comment]
i found the jieba version dosn't affected. but it run, maybe something else affect that

**Comment by cjdxhjj** [comment]
please figure out the issure and correct it.
