### ISSUE TITLE
初始化不了

### ISSUE THREAD

**Issue by zhang19523zhao** [langgenius/dify#416]
<img width="1478" alt="image" src="https://github.com/langgenius/dify/assets/77541540/9966c11c-7e68-447a-a357-26c12fc4ea94">

<img width="883" alt="image" src="https://github.com/langgenius/dify/assets/77541540/bfba112b-deb4-4748-8449-aa2466189fd6">

**Comment by takatost** [comment]
You deployed it via docker compose, right? Any config changes? Looks like the initial migration didn't execute or failed.
