### ISSUE TITLE
Add "Sentence Window Retrieval" and "Auto-Merging Retrieval"  

### ISSUE THREAD

**Issue by vccler** [langgenius/dify#4171]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Currently the RAG retrieval is very base by using Vector store with similarity searching or full-text searching. Please add some advanced retrieval methods like "Sentence Window Retrieval" and "Auto-Merging Retrieval". It will improve the RAG performance  metrics, like context relevance, answer relevance and Groundedness.

### 2. Describe the feature you'd like to see

please refer to the online course : https://learn.deeplearning.ai/courses/building-evaluating-advanced-rag/

### 3. How will this feature improve your workflow or experience?

Envolve some advanced RAG retrieval methods to improve  RAG performance 

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by patryk20120** [comment]
As of my knowledge, the team is working on more advanced RAG pipelines.
