### ISSUE TITLE
Customize the timeout for http request tools

### ISSUE THREAD

**Issue by LucisBaoshg** [langgenius/dify#4172]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes. When I'm using the http request tool, it's easier to encounter a request timeout, when in fact the remote service is still running just not returning the

### 2. Describe the feature you'd like to see

For the http request tool, add a setting to set the request timeout

### 3. How will this feature improve your workflow or experience?

Huge difference, improved stability, going from unavailable to available

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this is solved.
