### ISSUE TITLE
Dify 工作流中是否支持输出文字+图片的卡片消息

### ISSUE THREAD

**Issue by XinleZhou2018** [langgenius/dify#4176]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Dify 工作流的直接回复节点，只支持回复文本消息，有没有类似于文字+图片的卡片消息？

**Comment by zihjiang** [comment]
![image](https://github.com/langgenius/dify/assets/21021327/de0794d3-f20e-49b2-af65-cc4bc3385139)
类似于这样吧

**Comment by XinleZhou2018** [comment]
> ![image](https://private-user-images.githubusercontent.com/21021327/328779504-de0794d3-f20e-49b2-af65-cc4bc3385139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTAyNTMsIm5iZiI6MTcxNTE0OTk1MywicGF0aCI6Ii8yMTAyMTMyNy8zMjg3Nzk1MDQtZGUwNzk0ZDMtZjIwZS00OWIyLWFmNjUtY2M0YmMzMzg1MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2MzIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYmE2NjJlZDkyNjcwZGE3ZTM3ZDlhZWM2YWJiZGZlMTc3MWY2YjNlYmY0MjRlOTEyMTUwMWQ4YzNhODFjMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf1y3Ibv1NUtZu7UXZP_ImuKXlhs7VHPthIbOuskiDg) 类似于这样吧

我如何上传自己的图片（不是用户在聊天框左侧上传的图片）到dify上，然后直接回复里将这张图输出呢？

**Comment by aBner6667** [comment]
请问，上传的图片文件保存在了哪里？我在哪个文件夹可以找到他们？

**Comment by guohanli** [comment]
> > ![image](https://private-user-images.githubusercontent.com/21021327/328779504-de0794d3-f20e-49b2-af65-cc4bc3385139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTAyNTMsIm5iZiI6MTcxNTE0OTk1MywicGF0aCI6Ii8yMTAyMTMyNy8zMjg3Nzk1MDQtZGUwNzk0ZDMtZjIwZS00OWIyLWFmNjUtY2M0YmMzMzg1MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2MzIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYmE2NjJlZDkyNjcwZGE3ZTM3ZDlhZWM2YWJiZGZlMTc3MWY2YjNlYmY0MjRlOTEyMTUwMWQ4YzNhODFjMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf1y3Ibv1NUtZu7UXZP_ImuKXlhs7VHPthIbOuskiDg) 类似于这样吧
> 
> 我如何上传自己的图片（不是用户在聊天框左侧上传的图片）到dify上，然后直接回复里将这张图输出呢？

我也遇到了类似的需求，只是我是向用户展示我从别处获取到的图片，如果你只是想回复中带有图片，直接以Markdown图片语法 `![图片alt](图片url)` 写在回复里就行了

**Comment by violinday** [comment]
我也遇到了类似的问题

**Comment by dingshengqin** [comment]
@guohanli  您好，markdown的url是怎么embedding的？ 我要做一个私有知识库，我需要把图片单独保存起来并打上标签吗？

**Comment by dingshengqin** [comment]
收到，谢谢！

**Comment by ld-xy** [comment]
> 请问，上传的图片文件保存在了哪里？我在哪个文件夹可以找到他们？

大哥，你现在知道了吗

**Comment by lelele-1** [comment]
现在是不支持输出图片了吗，我在直接回复的输出里看到正常输出了markdown格式的图片，但对话框里没有图片。

![Image](https://github.com/user-attachments/assets/05a4efcf-43cd-4cfb-8965-b279f129bbd0)

**Comment by zx874561** [comment]
> 现在不支持输出图片了吗，我在直接回复的输出里看到输出正常了markdown格式的图片，但是对话框里没有图片。
> 
> ![Image](https://github.com/user-attachments/assets/05a4efcf-43cd-4cfb-8965-b279f129bbd0)

+1

**Comment by unihon** [comment]
+1

**Comment by Sos-Zachary** [comment]
> > [@guohanli](https://github.com/guohanli) 您好，markdown的url是怎么embedding的？ 我要做一个私有知识库，我需要把图片单独保存起来并打上标签吗？
> 
> 1. 通过提示词要求以markdown语法输出图片。2. 私有知识库中需要把图片上传到第三方图床变成可公网访问的链接，这样召回后前端才能正常显示。

请问如何将私有库的图片上传到图床，私有库图片的加密策略我不太明白，请问可以提供一些方向吗，感谢！

**Comment by Henrysu1998** [comment]
直接llm那里写system prompt 让模型以图文混排输出，不要过滤掉图片链接就行。

**Comment by hulongan** [comment]
> 直接llm那里写system prompt 让模型以图文混排输出，不要过滤掉图片链接就行。

写了貌似不起作用呀

<img width="515" height="165" alt="Image" src="https://github.com/user-attachments/assets/645be82b-b192-4516-8524-a40178ae2c77" />
