### ISSUE TITLE
API endpoint /chat-messages returning an empty answer when matching the Annotations question

### ISSUE THREAD

**Issue by kimtuo** [langgenius/dify#4180]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/23046989/94f2939e-a2cf-4a7a-a8a5-67c2c8b6e20c)
![image](https://github.com/langgenius/dify/assets/23046989/5102d4d5-ebd2-410e-b3b9-2e0165c052e6)

### ✔️ Expected Behavior

return the annotations  answer

### ❌ Actual Behavior

the answer is none

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)

**Comment by mihuajun** [comment]
遇到同样的问题,在0.6.12-fix1中,使用WEB页面访问聊天时,命中注释后返回准确的值,但是在API调用时,命中后answer属性返回空

**Comment by fallenleavesguy** [comment]
同样的问题，换了xinference, answer字段就永远是""了，实际xinference
已经正常响应了
