### ISSUE TITLE
API容器成功使用了代理,但是Gemini无法录入key

### ISSUE THREAD

**Issue by SAnBlog** [langgenius/dify#4186]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

录入点击没有反应,大概30s显示503错误,nginx日志中发现请求 400失败

**Comment by Scenx** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  Pleas do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.6.6
> 
> ### Cloud or Self Hosted
> Self Hosted (Docker)
> 
> ### Steps to reproduce
> 录入点击没有反应,大概30s显示503错误,nginx日志中发现请求 400失败
> 
> ### ✔️ Expected Behavior
> _No response_
> 
> ### ❌ Actual Behavior
> _No response_

我也是同样的问题

**Comment by alexlooks** [comment]
the same error, how to fix it ?

**Comment by BitBrewing** [comment]
同样问题，版本为 0.6.11
api和worker都使用了代理

**Comment by shelltea** [comment]
The same issue, still unable to use Gemini. Not sure if these codes have really been tested?

**Comment by shelltea** [comment]
This issue was resolved through the following methods:

Modify this file [llm.py](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/google/llm/llm.py#L192)

```
new_client_manager.configure(api_key=credentials["google_api_key"], transport='rest')
```

**Comment by SAnBlog** [comment]
> This issue was resolved through the following methods:
> 
> Modify this file [llm.py](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/google/llm/llm.py#L192)
> 
> ```
> new_client_manager.configure(api_key=credentials["google_api_key"], transport='rest')
> ```

确实可以,是什么原理呢?

**Comment by zengqingfu1442** [comment]
+1 我也遇到这个问题了，dify  0.12.1

**Comment by SAnBlog** [comment]
> +1 我也遇到这个问题了，dify 0.12.1

无解,官方不支持使用代理,只能使用方面的方案修改容器内源码并重启容器就可以使用了,麻烦就是每次更新版本都要修改,而且我修改后发现流式输出有点慢,已经改用oneapi转发了

**Comment by zhongxiao37** [comment]
> > This issue was resolved through the following methods:
> > Modify this file [llm.py](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/google/llm/llm.py#L192)
> > ```
> > new_client_manager.configure(api_key=credentials["google_api_key"], transport='rest')
> > ```
> 
> 确实可以,是什么原理呢?

原因是因为`transport`默认是`grpc_asyncio`，使用的是GenerativeServiceAsyncClient。

```python
class _ClientManager:
    client_config: dict[str, Any] = dataclasses.field(default_factory=dict)
    default_metadata: Sequence[tuple[str, str]] = ()
    clients: dict[str, Any] = dataclasses.field(default_factory=dict)

    def configure(
        self,
        *,
        api_key: str | None = None,
        credentials: ga_credentials.Credentials | dict | None = None,
        # The user can pass a string to choose `rest` or `grpc` or 'grpc_asyncio'.
        # See _transport_registry in the google.ai.generativelanguage package.
        # Since the transport classes align with the client classes it wouldn't make
        # sense to accept a `Transport` object here even though the client classes can.
        # We could accept a dict since all the `Transport` classes take the same args,
        # but that seems rare. Users that need it can just switch to the low level API.
        transport: str | None = None,
        client_options: client_options_lib.ClientOptions | dict[str, Any] | None = None,
        client_info: gapic_v1.client_info.ClientInfo | None = None,
        default_metadata: Sequence[tuple[str, str]] = (),
    ) -> None:
        """Initializes default client configurations using specified parameters or environment variables.

        If no API key has been provided (either directly, or on `client_options`) and the
        `GEMINI_API_KEY` environment variable is set, it will be used as the API key. If not,
        if the `GOOGLE_API_KEY` environement variable is set, it will be used as the API key.

        Note: Not all arguments are detailed below. Refer to the `*ServiceClient` classes in
        `google.ai.generativelanguage` for details on the other arguments.

        Args:
            transport: A string, one of: [`rest`, `grpc`, `grpc_asyncio`].
            api_key: The API-Key to use when creating the default clients (each service uses
                a separate client). This is a shortcut for `client_options={"api_key": api_key}`.
                If omitted, and the `GEMINI_API_KEY` or the `GOOGLE_API_KEY` environment variable
                are set, they will be used in this order of priority.
            default_metadata: Default (key, value) metadata pairs to send with every request.
                when using `transport="rest"` these are sent as HTTP headers.
        """
```

```python
    "grpc-async": {
          "libraryClient": "GenerativeServiceAsyncClient",
```

**Comment by zhyhang** [comment]
I have made much tests and revealed the root cause:  Dify invoke Gemini API by google.generativeai Python SDK which using gGRPC as commincation lib that requesting grpc_proxy, https_proxy or http_proxy env (must be lower-case, upper-case should not working)! 
Please see my blog for deail：https://blog.csdn.net/zhyhang/article/details/146140019

**Comment by shanghaobo** [comment]
已解决，在`plugin_daemon`下配置自己的代理即可

https://www.qinyu.cc/archives/266.html

**Comment by wuzaiyuan1998** [comment]
> plugin_daemon

可以发一下这个文件的路径吗？

**Comment by shanghaobo** [comment]
> > plugin_daemon
> 
> 可以发一下这个文件的路径吗？

就是`docker-compose.yml`文件里的配置项
