### ISSUE TITLE
I keep getting an error message when making API requests: "Incorrect API key provided."

### ISSUE THREAD

**Issue by IT-weicheng** [langgenius/dify#4191]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

Request context :
curl --location --request POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer xxxxxx' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: api.dify.ai' \
--header 'Connection: keep-alive' \
--data-raw '{
  "inputs": {},
  "query": "waht?",
  "response_mode": "blocking",
  "user": "111111-123",
  "files": [],
  "conversation_id":""
}'

Response context:
{
    "code": "completion_request_error",
    "message": "Incorrect API key provided",
    "status": 400
}

![image](https://github.com/langgenius/dify/assets/154573082/620dd557-749f-4bc3-851b-d8a7b28955e3)

### ✔️ Expected Behavior

I developed the application strictly following the API documentation, and the API KEY was just generated, so it should be able to execute successfully.

### ❌ Actual Behavior

I have generated many keys, but they all show this error message.

**Comment by IT-weicheng** [comment]
I have checked according to the above checkpoints, everything meets the requirements, but the request still returns an error.

curl --location --request POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer app-XXXXXXXXXXX' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: api.dify.ai' \
--header 'Connection: keep-alive' \
--data-raw '{
  "inputs": {},
  "query": "waht?",
  "response_mode": "blocking",
  "user": "111111-123",
  "files": [],
  "conversation_id":""
}'

{
    "code": "completion_request_error",
    "message": "Incorrect API key provided",
    "status": 400
}

**Comment by IT-weicheng** [comment]
Is it because I haven't subscribed to the service that I can't use the API call service?

**Comment by IT-weicheng** [comment]
I found the issue. When it mentioned the key expired, it was referring to the key of the large model, not the application key of Dify. I hope the prompt can be more comprehensive.

**Comment by madara1793** [comment]
I don't think so
