### ISSUE TITLE
create new app failed

### ISSUE THREAD

**Issue by flyice8** [langgenius/dify#4195]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![123123123](https://github.com/langgenius/dify/assets/164740348/b936e7ee-7446-425c-bae7-7d8f66577cde)

when i create new app, report picture error, please help me check. thanks!

### ✔️ Expected Behavior

N/A

### ❌ Actual Behavior

N/A

**Comment by crazywoola** [comment]
Please select a template

<img width="835" alt="image" src="https://github.com/langgenius/dify/assets/100913391/602ca00a-248e-4534-b7fb-2b2161164cb0">

**Comment by flyice8** [comment]
Actually mine has a choice, but the problem is the same.
Whether I select "assistant" or "Text Generator," the result is the same, "Please select a template."
![123123123](https://github.com/langgenius/dify/assets/164740348/6f69fc31-9128-447c-aaab-a7e8439d666a)
