### ISSUE TITLE
Workflow LLM node stop sequence to '\n' will be escape to '\\n'.

### ISSUE THREAD

**Issue by sagarey** [langgenius/dify#4197]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In workflow setting the stop sequence to '\n' in the LLM node will be escaped, LLM API receives it as '\\\n'.
![屏幕截图 2024-05-09 010741](https://github.com/langgenius/dify/assets/5120456/c54740ee-c517-43d2-b11f-837488207f0f)

OpenAI-API-compatible Model Provider:
![image](https://github.com/langgenius/dify/assets/5120456/7f970b83-030e-4870-be13-88864d345dab)

### ✔️ Expected Behavior

The stop sequence configured on the frontend same as finally called stop config.
<img width="974" alt="image" src="https://github.com/langgenius/dify/assets/5120456/4c4c4ff8-fc33-48ce-862f-c321abb07705">

### ❌ Actual Behavior

Configuration is escaped.
![屏幕截图 2024-05-09 011833](https://github.com/langgenius/dify/assets/5120456/0a30fda2-4d17-4888-9f0d-fdff3c821db9)

**Comment by iYaDongWang** [comment]
Has anyone been working on solving this issue? I have encountered the same problem.

**Comment by crazywoola** [comment]
Can you try the latest version?

**Comment by iYaDongWang** [comment]
In version 0.6.12-fix1, this issue still exists. I will try the latest version later.

**Comment by sagarey** [comment]
> Can you try the latest version?

same issue in 0.6.13
