### ISSUE TITLE
Support Newer Cohere Models on AWS Bedrock

### ISSUE THREAD

**Issue by skiski456** [langgenius/dify#4198]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I try to add cohere.command-r-plus-v1:0 as a model using AWS Bedrock, I get an error message ValidationException: Malformed input request: #: required key [message] not found#: extraneous key [stream] is not permitted#: extraneous key [prompt] is not permitted, please reformat your input and try again

### 2. Describe the feature you'd like to see

Add support for command-r-plus and the other newer cohere models that were recently added to AWS Bedrock (cohere.command-r-plus-v1:0, cohere.command-r-v1:0)

### 3. How will this feature improve your workflow or experience?

This is the model I installed Dify to use as it is the model that I use locally.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
