### ISSUE TITLE
有没有本地部署后非常卡的? 

### ISSUE THREAD

**Issue by yananliuyanjiang** [langgenius/dify#421]
有没有本地部署后非常卡的，很多业务需要很久才能访问成功，不知道什么情况

**Comment by lxm** [comment]
应该是由于`https://updates.dify.ai` 这个用于检查自动更新的域名在cf，最近几天cf在大陆屏蔽的比较严重的导致的，可以在api 的env配置里加上CHECK_UPDATE_URL: ""临时解决

**Comment by yananliuyanjiang** [comment]
> 

好的，我试试能不能解决访问卡顿问题

**Comment by crazywoola** [comment]
You can reopen this issue if this kind of situation still exists.
