### ISSUE TITLE
Language internationalization switching exception

### ISSUE THREAD

**Issue by TinsFox** [langgenius/dify#4216]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

The latest front-end code, as of commit `487ce7c82a3803b50`

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Switch language after entering the system

### ✔️ Expected Behavior

The value of lang on HTML should be the same as the current language value

https://github.com/langgenius/dify/assets/33956589/4248b412-2a9e-4110-924f-12bd8d97c9aa

### ❌ Actual Behavior

No matter how I switch, it will change to the language option I set before.

**Comment by patryk20120** [comment]
For me it is working fine, and the lang in HTML is changing. Isn't that an issue with Google translate? Did you tried without it or another browser?

**Comment by TinsFox** [comment]
@patryk20120 Oh, thanks for the reminder, I found the reason, it’s precisely because of Google Translate
