### ISSUE TITLE
open api的密钥是正确的但是会显示无效的openAI API密钥

### ISSUE THREAD

**Issue by aA565169388** [langgenius/dify#423]
error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/moderations (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc2d4d4b460>: Failed to establish a new connection: [Errno 111] Connection refused'))"

按照这报错信息看是连不上openai，这是被墙了吗

**Comment by crazywoola** [comment]
Yes, you are right.
