### ISSUE TITLE
[google] Server Unavailable Error, 504 Deadline Exceeded and Error: Minified React error #185

### ISSUE THREAD

**Issue by chalitbkb** [langgenius/dify#4232]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

It seems there is an issue; please check. When I use the Model Gemini-1.5-pro and the data I input into the prompt system is large, and when I begin to test debug, I receive the error message shown in the picture.
![image](https://github.com/langgenius/dify/assets/32437546/45c73c00-9696-4050-b1b3-3e5673a3b873)

Additional information: This problem occurs while the AI is generating responses, and as the character length increases, this error occurs.

And sometimes, this error also occurs:
Error: Minified React error 185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
https://github.com/langgenius/dify/issues/3498#issue-2244025161
![image](https://github.com/langgenius/dify/assets/32437546/304960ca-02e5-4bb3-8e58-7a048c6a31dc)

### ❌ Actual Behavior

[google] Server Unavailable Error, 504 Deadline Exceeded

**Comment by shelltea** [comment]
The same problem.Is there a solution?

**Comment by jamser** [comment]
同样的问题，在加gamini模型，输入key就出现了；

**Comment by mealcard** [comment]
same here

**Comment by lingfengchencn** [comment]
I have the same issue, on the" debug & preview" page, sometimes I will get this message and lose all of the generated tokens, but the logs have all generated messages.
