### ISSUE TITLE
Report "Not a valid PEM pre boundary" error when I add a model 

### ISSUE THREAD

**Issue by WhiteRoseinShangHai** [langgenius/dify#4238]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when I add a model, report "Not a valid PEM pre boundary" error, I try add Zhipu and deepseek model.![image](https://github.com/langgenius/dify/assets/25809831/52f1b13b-4a99-4363-be49-83015ec1b379)

**Comment by WhiteRoseinShangHai** [comment]
I use dify in private net，it don't have domain, so I doesn't use ssl, use http not https

**Comment by Hansen523** [comment]
@dosu I use dify in private net，it don't have domain, so I doesn't use ssl, use http not https

**Comment by zeroameli** [comment]
@WhiteRoseinShangHai Try checking the "encrypt_public_key" in table "tenants", it seem you got an invalid value.
