### ISSUE TITLE
The dataset_keyword_tables field exceeds 1GB due to the large volume of data.

### ISSUE THREAD

**Issue by intflag** [langgenius/dify#4243]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have a large dataset, and its size is as follows.

```
select count(1) from documents where dataset_id = 'my dataset_id';
result: 31258

select count(1) from document_segments where dataset_id = 'my dataset_id';
resul: 1288597
```
Due to the large volume of data, the 'keyword_table' field in the 'dataset_keyword_tables' table exceeds 1GB, causing an error during program execution. Can I delete that record?

![PostgreSQL-error01](https://github.com/langgenius/dify/assets/37425006/973a46e6-fbf5-4b1a-b5b9-5dc7547d363f)

### ✔️ Expected Behavior

When dealing with large datasets, errors are less likely to occur.

### ❌ Actual Behavior

print error：invalid memory alloc request size 1G

**Comment by crazywoola** [comment]
Yes you can.

**Comment by secsilm** [comment]
similar issue. how to reduce this table size? is this normal that occupy so large disk storage?

https://github.com/langgenius/dify/discussions/10152
