### ISSUE TITLE
IO Error After Upgrade

### ISSUE THREAD

**Issue by thiner** [langgenius/dify#4244]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I deployed Dify in K8s. Mount the 'api/storage/privatekeys' by PVC. I upgrade the Dify docker image to `0.6.7`.

### ✔️ Expected Behavior

Dify should work, all existing work flow, knowledge base, model providers remain as-is.

### ❌ Actual Behavior

Couldn't load knowledge base, model providers, the error log shows `libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id:...`. By attaching into the image console, an IO error pops up while `ls /app/api/storage/privatekeys`. Seems the folder "privatekeys" is corrupted. 
This error actually happens every time when I upgrade the docker image version. One observation might relevant to this issue is that the `tennant_id` was regenerated in every upgrades.

**Comment by crazywoola** [comment]
Maybe it's related to k8s itself. Since we testing in compose files, it doesn't need any further steps besides the `docker compose pull`.

**Comment by thiner** [comment]
is there any 

> Maybe it's related to k8s itself. Since we testing in compose files, it doesn't need any further steps besides the `docker compose pull`.

In what kind of condition the `tenant_id` will be regenerated?

**Comment by thiner** [comment]
Problem solved. The root cause is that `dify-api` and `dify-worker` were deployed to different nodes, thus the one of the deployment couldn't access path `/app/api/storage`. 
For anyone encountered this error while deploying on K8s, you should make sure `dify-api` and `dify-worker` are deployed to the same node. You can achieve the goal by setting the "nodeSelector" in deployment yaml file.
