### ISSUE TITLE
/api/datasets/indexing-estimate return error msg "Model Parameter max_tokens should be less than or equal to 1024.0."

### ISSUE THREAD

**Issue by zw620** [langgenius/dify#4259]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Under Knowledge tab:
1. Create Knowledge-->Choose data source-->upload a docx file and click next
2. Turn on "Segmenting in Question & Answer format"
3. Click "Switching to Q&A format" on top right
4. Show error "Model Parameter max_tokens should be less than or equal to 1024.0."
5. The req/res of /api/datasets/indexing-estimate:
Req:
{
    "info_list": {
        "data_source_type": "upload_file",
        "file_info_list": {
            "file_ids": [
                "cc80eec6-a9f6-416e-90de-d3c917e995ba"
            ]
        }
    },
    "indexing_technique": "high_quality",
    "process_rule": {
        "rules": {},
        "mode": "automatic"
    },
    "doc_form": "qa_model",
    "doc_language": "Chinese"
}
Res:
{
    "code": "invalid_param",
    "message": "Model Parameter max_tokens should be less than or equal to 1024.0.",
    "status": 400
}

**Comment by zw620** [comment]
Could you pls help to check this issue?
@crazywoola
@JohnJyong

**Comment by Nie-Yingying** [comment]
@zw620 
Did you solve it? I met this error, too.

**Comment by zw620** [comment]
Yes. I modified the value of max_tokens in the souce code and then fixed this issue.
