### ISSUE TITLE
配置了OPENAI_API_BASE，无法访问

### ISSUE THREAD

**Issue by jinghai** [langgenius/dify#427]
我在api和worker中配置OPENAI_API_BASE: http://58.215.177.xxx:6009/v1，调用时发现访问不到，日志如下：
```
Traceback (most recent call last):
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 596, in request_raw
docker-api-1       |     result = _thread_context.session.request(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
docker-api-1       |     resp = self.send(prep, **send_kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
docker-api-1       |     r = adapter.send(request, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
docker-api-1       |     raise ConnectionError(e, request=request)
docker-api-1       | requests.exceptions.ConnectionError: HTTPConnectionPool(host='58.215.177.xxx', port=6009): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c16992f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
http://58.215.177.xxx:6009/v1是好用的，其它程序可以正常访问。请问可能是哪些原因导致的呢？

**Comment by crazywoola** [comment]
Please refer [this article](https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url-in-requests) for help.

**Comment by jinghai** [comment]
> Please refer [this article](https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url-in-requests) for help.

这个文章对我没有帮助，我的问题是如何正确的配置OPENAI_API_BASE，我在api和worker配置OPENAI_API_BASE变量，但却不能正常调用我的API服务，不知道如何解决

**Comment by jinghai** [comment]
i dont konw why my problem is closed,saiding

**Comment by jinghai** [comment]
you can close this,what can you another

**Comment by jinghai** [comment]
Are you Chinese?

**Comment by jinghai** [comment]
Closing the issue in a hurry is really humiliating

**Comment by jinghai** [comment]
> Please refer [this article](https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url-in-requests) for help.

Closing the issue in a hurry is really humiliating

**Comment by ntfs32** [comment]
可以用呀
OPENAI_API_BASE: http://xxx.xx/v1
比如用cloudfare worker代理的

**Comment by liulijing3-tal** [comment]
check your API is list "http://58.215.177.xxx:6009/v1/chat/completions". if not, your OPENAI_API_BASE  is not useful; if same, curl "http://58.215.177.xxx:6009/v1/chat/completions" check this API connect

**Comment by jinghai** [comment]
问题已解决：原因是我的宿主机没有独立公网IP，是通过防火墙的公网IP转发到宿主机，而内网服务器又不能直接访问防火墙的公网IP导致docker无法正常调用。换成宿主机的内网IP一切正常。
@crazywoola @ntfs32 @liulijing3-tal 感谢提供了排查思路。

**Comment by zfno111** [comment]
> 问题已解决：原因是我的宿主机没有独立公网IP，是通过防火墙的公网IP转发到宿主机，而内网服务器又不能直接访问防火墙的公网IP导致docker无法正常调用。换成宿主机的内网IP一切正常。 @crazywoola @ntfs32 @liulijing3-tal 感谢提供了排查思路。

方便加个联系方式么？ 我也遇到了这个问题 我们也是自己搭建的代理，程序可以访问 dify不行。

**Comment by MichaelPorter0** [comment]
@jinghai 请问你的宿主机能访问互联网吗，如果是纯内网搭建该怎么办

**Comment by zfno111** [comment]
纯内网的做不了。



***@***.***
 
发件人： miporterg
发送时间： 2023-09-26 09:41
收件人： langgenius/dify
抄送： zfno111; Comment
主题： Re: [langgenius/dify] 配置了OPENAI_API_BASE，无法访问 (Issue #427)
@jinghai 请问你的宿主机能访问互联网吗，如果是纯内网搭建该怎么办
