### ISSUE TITLE
Question classifier proves to be ineffective

### ISSUE THREAD

**Issue by tigerun** [langgenius/dify#4273]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After many times of attempts, it is evident that the 0.6.7 version of the question classifier abysmal intellect for problem categorization, frequently failing to identify issues accurately.

### ✔️ Expected Behavior

 Urgent rectification

### ❌ Actual Behavior

Question classifier proves to be ineffective

**Comment by YidaHu** [comment]
What LLM do you use? A lot of it has to do with LLM performance. You can provide more information.

**Comment by Theysua** [comment]
Can you provide more evidence for the community to further investgate this issue please? 
It will be nice if you can provide an example of the problem you are encountering
Thanks!

**Comment by tigerun** [comment]
Deploying the Qwen 14b model locally on Xinference. If I use qwen-max-0403,everything looks ok

**Comment by tigerun** [comment]
Back to 0.6.6 version, the Question classifier still be ineffective

**Comment by YidaHu** [comment]
@tigerun I think it has to do with the LLM capability and the service is fine

**Comment by tigerun** [comment]
0.6.6 everything is ok，but when update to 0.6.7 ，Question classifier look like a idiot，do nothing except update.

**Comment by tigerun** [comment]
To resolve the issue with the question classifier version 0.6.7, follow these steps:

Locate services.api.image in your docker-compose.yaml file.
Replace the current image tag langgenius/dify-api:0.6.7 with langgenius/dify-api:897e07f63954d39a260d771a2d01b7932d005645
Similarly, find services.web.image within the same file and replace langgenius/dify-api:897e07f63954d39a260d771a2d01b7932d005645
After making these changes, run the command docker compose up -d to restart your services. By doing this, the issue with the question classifier should be resolved.
