### ISSUE TITLE
Dify Slackbot

### ISSUE THREAD

**Issue by gabilanbrc** [langgenius/dify#4278]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Unable to receive messages from Slack or use Slack as a Knowledge Base

### 2. Describe the feature you'd like to see

Hi Team, after installing the 0.6.7 version I am receiving messages in Slack (for example with the text answered by an Agent), thanks for the update. My plan is to create a Slackbot that interacts with Dify. 
So the question is how to implement the part of receiving messages from slack and then using is as inputs for the Agent? By the way another feature may be using Slack messages as a Knowledge Base 

### 3. How will this feature improve your workflow or experience?

Our Slack users will interact with our Knowledge Base without leaving Slack

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by gabilanbrc** [comment]
/

**Comment by ajaman190** [comment]
@gabilanbrc, is the feature you requested now available? I am also interested in integrating a Slack bot that interacts with Dify apps. This would allow our users to directly use custom Dify apps from our Slack workspace and query Slack chats as a knowledge base. Thank you!
