### ISSUE TITLE
Mac M1 arm64,conda activate dify, flask db upgrade error

### ISSUE THREAD

**Issue by 18810211910** [langgenius/dify#429]
ImportError: dlopen(/Users/nenezsnp/anaconda3/envs/py310/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so, 0x0002): tried: '/Users/nenezsnp/anaconda3/envs/py310/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nenezsnp/anaconda3/envs/py310/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (no such file), '/Users/nenezsnp/anaconda3/envs/py310/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by 18810211910** [comment]
按照README.md执行，5.Run migrate  Before the first launch, migrate the database to the latest version报错

**Comment by 18810211910** [comment]
使用 activate base启动报错ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/Users/nenezsnp/anaconda3/lib/python3.10/site-packages/watchdog/events.py)

**Comment by crazywoola** [comment]
`pip install --upgrade watchdog` or try to cleanup the python environment. and rerun pip install

**Comment by takatost** [comment]
Try adding `DEBUG=true` in the api/.env file
