### ISSUE TITLE
upload a file to a knowledge but the indexing_status always waiting and the progress is 0%

### ISSUE THREAD

**Issue by dwq370** [langgenius/dify#4295]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1 and later

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1) model provider is xinference and the embedding model is bge-large-zh-v1.5
2) create a knowledge
3) upload an file to knowledge
4) choice the policy to index
5) click the button Save & Process

### ✔️ Expected Behavior

the indexing_status always complete and the progress is 100%

### ❌ Actual Behavior

version 0.6.0-fix1:
![838a06db0ebf7ae6344839329ba59b9](https://github.com/langgenius/dify/assets/131581396/db722f2f-4ed6-40e1-beb9-2293201bfe7a)

version 0.6.4:
![image](https://github.com/langgenius/dify/assets/131581396/b7e3db7a-fe6f-4291-adfe-0964393ad69c)

**Comment by JohnJyong** [comment]
https://docs.dify.ai/getting-started/install-self-hosted/local-source-code

![image](https://github.com/langgenius/dify/assets/76649700/cb4aa70b-a316-4cfa-8704-181fd918dc3d)

pls check your worker service is started or not @dwq370

**Comment by dwq370** [comment]
i start dify with the flask cmd

flask run --host 0.0.0.0 --port 5001 --debug

**Comment by JohnJyong** [comment]
both flask and celery are need, the celery worker is used for deal async task

**Comment by dwq370** [comment]
OK ,i will try it
tks!!!

**Comment by dwq370** [comment]
i start both api and woker sevice, there is an error when i upload the file to the knowledge 
![image](https://github.com/langgenius/dify/assets/131581396/4da09eb4-f264-471c-affa-e7e2994cc248)

**Comment by dwq370** [comment]
an error whit version 0.6.4
![image](https://github.com/langgenius/dify/assets/131581396/6630ff5b-22aa-4e19-9956-e8a43c1a0332)
![img_v3_02ap_c283d0cb-2d58-46c1-8d84-8556892980ag](https://github.com/langgenius/dify/assets/131581396/bd5c14c0-9c58-4fce-b0a4-6c8fa3680062)

**Comment by dwq370** [comment]
i start weaviate with dify version 0.6.4, it's work 
![image](https://github.com/langgenius/dify/assets/131581396/147d5eb3-6df4-4b0f-908e-ff564d5a5154)

**Comment by dwq370** [comment]
i start weaviate with dify version 0.6.1-fix1, it's work too

thank you for your help

i will close the issue
