### ISSUE TITLE
安装成功后创建数据集，上传pdf，嵌入发生错误

### ISSUE THREAD

**Issue by liuzimu1995** [langgenius/dify#43]
![image](https://github.com/langgenius/dify/assets/17780568/13cdcf03-333a-4364-a3a5-3117ba704eca)

如题，请问如何解决？

**Comment by liuzimu1995** [comment]
错误是这样的
code
: 
"document_already_finished"
message
: 
"Document already finished."
status
: 
400

**Comment by takatost** [comment]
这应该是已经导入成功了的返回，可否稳定复现？
