### ISSUE TITLE
Add model provider Ollama fail

### ISSUE THREAD

**Issue by Minge-chen** [langgenius/dify#4307]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have followed the instruction on https://docs.dify.ai/tutorials/model-configuration/ollama#if-you-are-using-docker-to-deploy-dify-and-ollama-you-may-encounter-the-following-error

Then I start ollama serve works fine.

<img width="1305" alt="image" src="https://github.com/langgenius/dify/assets/39788401/f9b190e8-f639-4f8c-9c79-b67dd9f09f8b">

The following image error occurred when the model was finally add

<img width="1395" alt="image" src="https://github.com/langgenius/dify/assets/39788401/fe45b317-eb87-4d14-a232-97093979496e">

**Comment by santiagoblanco22** [comment]
I have it working!! I can help you to fix. write me to discord @santiblanko
