### ISSUE TITLE
Name change of app has no effect.

### ISSUE THREAD

**Issue by dancohen81** [langgenius/dify#4309]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Create and name an app
2. Rename the app
3. Publish the app  

### ✔️ Expected Behavior

App name should have changed in published location

### ❌ Actual Behavior

App name does not change in published location

**Comment by dancohen81** [comment]
Dosu!! Glad I can contribute a little thing here or there ;)

**Comment by crazywoola** [comment]
For published app, please go do overview -> setting.

<img width="1036" alt="image" src="https://github.com/langgenius/dify/assets/100913391/ca5b5f78-8638-4f48-9f7f-8ef6395963ae">
