### ISSUE TITLE
The chat page does not use translation

### ISSUE THREAD

**Issue by lvjiajjjlzy** [langgenius/dify#4313]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Publish -> Run APP

### ✔️ Expected Behavior

It should be switched to other languages, but in any case, only English is displayed

### ❌ Actual Behavior

only English

**Comment by crazywoola** [comment]
<img width="1024" alt="image" src="https://github.com/langgenius/dify/assets/100913391/e911a8d4-10ef-41fd-9707-ea61f1ee6964">
