### ISSUE TITLE
for/while loop in workflow

### ISSUE THREAD

**Issue by YingchaoX** [langgenius/dify#4317]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

now i need to repeat the llm node again and again

### 2. Describe the feature you'd like to see

for loop or while loop in workflow

### 3. How will this feature improve your workflow or experience?

i don't know to repeat the llm node again and again

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by mkaskov** [comment]
as I understood 
Duplicated https://github.com/langgenius/dify/issues/3634
but what is the status and deadline?

**Comment by VincePotato** [comment]
Hi，We're designing a new node in the dify workflow called "iteration." Its purpose is to perform multiple steps on a list object until all results are outputted. 

You can use this node for generating long texts, like first having an LLM create a story outline based on a user-inputted theme, then feeding the outline list into the Iteration and LLM nodes for multiple iterations until a complete story is generated. 

The Iteration node allows the AI workflow to handle more complex processing logic. This feature is coming soon in our recent  version.

**Comment by VincePotato** [comment]
The while loop node will be supported later, probably in June.

**Comment by TianzeWang** [comment]
Hi Vince @VincePotato

I am wondering will Dify support the while loop with **unknown array length**?

I have a scenario that, I want to have multiple round of conversation with LLM and finally rate the conversations with LLM. The # of rounds of conversation is not fixed #.

**Comment by mkaskov** [comment]
https://github.com/langgenius/dify/discussions/6248
