### ISSUE TITLE
is it possible to create file and enable Segmenting in Q&A format by via API by default?

### ISSUE THREAD

**Issue by kissyy16** [langgenius/dify#4319]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

is it possible to create file and enable Segmenting in Q&A format by via API by default?

### ✔️ Expected Behavior

Segmenting in Q&A format For API

### ❌ Actual Behavior

There is not a parameter for Segmenting in Q&A format

**Comment by crazywoola** [comment]
<img width="1267" alt="image" src="https://github.com/langgenius/dify/assets/100913391/26ebde01-97f5-4f4a-a056-1beee92438c9">
