### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by bladeliger12** [langgenius/dify#4321]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

v0,6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![スクリーンショット 2024-05-12 193913](https://github.com/langgenius/dify/assets/123956224/e9bd1a87-5992-4582-a1d1-c4fdc237c3dc)

An error messsage is occurring.
please tell me how to resolve this error

**Comment by patryk20120** [comment]
Isn't your account (OpenAI) out of credits?

https://platform.openai.com/docs/guides/error-codes/api-errors `You have run out of credits or hit your maximum monthly spend.`
