### ISSUE TITLE
Code block error: operation not permitted with dify-sandbox 0.2.0

### ISSUE THREAD

**Issue by gijigae** [langgenius/dify#4344]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

git clone the repository and run `docker compose up -d`. Create a workflow with a Code node and run the workflow.

### ✔️ Expected Behavior

Workflow should run and return an expected result.

### ❌ Actual Behavior

The code node returns the following error message.
`error: operation not permitted`

Confirmed the same workflow got executed successfully with an earlier sandbox.

I suspect `sandbox 0.2.0` might be a curlprit, which was added as part of #4231 .

https://github.com/langgenius/dify/pull/4231/files#diff-89fafc265c1fa601cf2364b20be83308031335fda9467fcf3249d5ec1c0c8172R373

**Comment by Yeuoly** [comment]
I cannot reproduce this issue, could you pls provide more information? such as `docker ps` `docker logs` and so on.
<img width="510" alt="image" src="https://github.com/langgenius/dify/assets/45712896/fbf605b5-575f-4bc9-93b8-a4ab664c7bd6">

**Comment by patryk20120** [comment]
Just to confirm, same (success) for me.
![image](https://github.com/langgenius/dify/assets/9155931/3dfab19b-b195-4165-819b-9f8056666d0c)

**Comment by Yeuoly** [comment]
I have fixed an issue and updated the image, try pull again? @gijigae

**Comment by gijigae** [comment]
Thanks @Yeuoly for the update! Upgraded to 0.6.8, which includes sandbox 0.2.0, and now everything is looking good.
