### ISSUE TITLE
docker部署之后，可以打开登录页面，但设置管理员页面无法打开，一直在加载中 

### ISSUE THREAD

**Issue by xaigogo** [langgenius/dify#4350]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21 最新版

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```
(base) xuser@ubunt:docker$ docker compose ps
WARN[0000] /home/xdata/llmprox/difydocker/docker/docker-compose.yaml: `version` is obsolete 
NAME                  IMAGE                              COMMAND                   SERVICE      CREATED         STATUS                          PORTS
docker-api-1          langgenius/dify-api:0.6.8          "/bin/bash /entrypoi…"   api          4 minutes ago   Up 6 seconds                    5001/tcp
docker-db-1           postgres:15-alpine                 "docker-entrypoint.s…"   db           4 minutes ago   Restarting (1) 12 seconds ago   
docker-nginx-1        nginx:latest                       "/docker-entrypoint.…"   nginx        4 minutes ago   Up 4 minutes                    0.0.0.0:80->80/tcp, :::80->80/tcp
docker-redis-1        redis:6-alpine                     "docker-entrypoint.s…"   redis        4 minutes ago   Up 4 minutes (healthy)          6379/tcp
docker-sandbox-1      langgenius/dify-sandbox:0.2.0      "/main"                   sandbox      4 minutes ago   Up 4 minutes                    
docker-ssrf_proxy-1   ubuntu/squid:latest                "entrypoint.sh -f /e…"   ssrf_proxy   4 minutes ago   Up 4 minutes                    3128/tcp
docker-weaviate-1     semitechnologies/weaviate:1.19.0   "/bin/weaviate --hos…"   weaviate     4 minutes ago   Up 4 minutes                    
docker-web-1          langgenius/dify-web:0.6.8          "/bin/sh ./entrypoin…"   web          4 minutes ago   Up 4 minutes                    3000/tcp
docker-worker-1       langgenius/dify-api:0.6.8          "/bin/bash /entrypoi…"   worker       4 minutes ago   Up 4 minutes                    5001/tcp
```

### **docker部署之后，可以打开登录页面，看到登录框，**

![image](https://github.com/langgenius/dify/assets/84646327/359a73d4-49ca-460b-a845-1ecc99b9f9e8)

### **但设置管理员页面无法打开，一直在加载中，无法看到任何输入框 ？？**

![image](https://github.com/langgenius/dify/assets/84646327/231131d6-ea57-4760-92d4-559945a87a8b)

docker compose ps 有一句警告： 
**WARN[0000] /home/xdata/llmprox/difydocker/docker/docker-compose.yaml: `version` is obsolete** 
不知道这个是不是有影响？ 但我安装的docker最新稳定版

```
 (base) xuser@ubunt:docker$ docker version
Client: Docker Engine - Community
 Version:           26.1.2
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        211e74b
 Built:             Wed May  8 13:59:58 2024
 OS/Arch:           linux/amd64
 Context:           default
```

### ❌ Actual Behavior

无

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by 563816752** [comment]
请问有解决办法吗？

**Comment by huoli4844** [comment]
通过docker安装后，初次进入设置管理员确实还是不行，报错：
<img width="841" alt="image" src="https://github.com/user-attachments/assets/64df155d-0c82-4808-8954-8c709cac9263">
然后在刷新后，就进不了install，总是自动跳回登录页

**Comment by PapaAlex** [comment]
#我的问题在这篇帖子有找到对应解决办法
https://insight.xiaoduoai.com/intelligent-frontiers/tech/how-to-install-dify-what-are-the-precautions-during-installation.html

#思路是查看日志，根据日志对症下药。日志查看命令
docker-compose logs api

**Comment by yangxuan21** [comment]
> 通过docker安装后，初次进入设置管理员确实还是不行，报错： <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/29205530/374462298-64df155d-0c82-4808-8954-8c709cac9263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTQ1NDcsIm5iZiI6MTczMTU1NDI0NywicGF0aCI6Ii8yOTIwNTUzMC8zNzQ0NjIyOTgtNjRkZjE1NWQtMGM4Mi00ODA4LTg5NTQtOGM3MDljYWM5MjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzMTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwN2VlZmZhZmRjNTUxODM1OGZiMWRmMjliOGQ3MzhiNjFmZGRlNzNlMDdiMjZmNDEyMTU2NjA0ODJiZmQzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N-Pr480xtLfuFz3rhV5GLgGmTBzmBiG17bnO70r4fTw"> 然后在刷新后，就进不了install，总是自动跳回登录页

我也是这个问题，最终如何解决的？求助

**Comment by wzhty86** [comment]
> 通过docker安装后，初次进入设置管理员确实还是不行，报错： <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/29205530/374462298-64df155d-0c82-4808-8954-8c709cac9263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTM2MDcsIm5iZiI6MTczNTgxMzMwNywicGF0aCI6Ii8yOTIwNTUzMC8zNzQ0NjIyOTgtNjRkZjE1NWQtMGM4Mi00ODA4LTg5NTQtOGM3MDljYWM5MjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDEwMjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZjc4NDRmZGZlMmFiNzg1MTM2MWRjYTcwNjc0ZDAzODI4MWNiMTJkZWUyMWYzMTZmNzViNWE1M2RjN2JmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cNCkn3y6YH24AmJk8Q4PX5LohaiL3TTDROv3guesoRI"> 然后在刷新后，就进不了install，总是自动跳回登录页


您这个出错，最后解决了吗？
