### ISSUE TITLE
After updating to the latest version, it keeps showing the message "Workflow graph might have been modified, please refresh and resubmit." And I am unable to save.

### ISSUE THREAD

**Issue by Mgrsc** [langgenius/dify#4354]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Open the created application, then click on "Publish Update" to trigger a pop-up.

![image](https://github.com/langgenius/dify/assets/118801216/c956eb22-ff07-4238-b661-efa71de5dcb1)

**Comment by takatost** [comment]
pls make sure the api and web service versions are consistent.

**Comment by hjlarry** [comment]
I encountered the same issue which was resolved by `docker pull langgenius/dify-web:latest` upgrade the web container

**Comment by Mgrsc** [comment]
> pls make sure the api and web service versions are consistent.请确保 API 和 Web 服务版本一致。

Thank you for indeed fixing it

**Comment by Mgrsc** [comment]
> I encountered the same issue which was resolved by `docker pull langgenius/dify-web:latest` upgrade the web container我遇到了同样的问题，通过 `docker pull langgenius/dify-web:latest` 升级 Web 容器解决了。

Thank you for indeed fixing it
