### ISSUE TITLE
when I updated to v0.6.7, the HTTP Node got invalid timeout error which could work fine in previous version

### ISSUE THREAD

**Issue by dwgeneral** [langgenius/dify#4356]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

the HTTP node in workflow
![截屏2024-05-14 10 20 10](https://github.com/langgenius/dify/assets/8654993/00f03d8f-c704-4dbf-ab2a-32d565fd2bcd)
![截屏2024-05-14 10 20 18](https://github.com/langgenius/dify/assets/8654993/ebd948fd-4d21-4cc7-a897-7c29ec806824)

### ✔️ Expected Behavior

http calling succeed

### ❌ Actual Behavior

http calling failed with invalid timeout error

**Comment by crazywoola** [comment]
We have just release the 0.6.8, please upgrade to the version to see if this issue persists.
