### ISSUE TITLE
Issue API 

### ISSUE THREAD

**Issue by TienLD-0801** [langgenius/dify#4358]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I don't fix it , however doing remove docker and start docker-compose !

<img width="1346" alt="Screenshot 2024-05-14 at 11 01 05" src="https://github.com/langgenius/dify/assets/112608271/76c4d4ef-9a31-4a7f-9046-402800c1ddae">

**Comment by crazywoola** [comment]
Please paste the original text message, so that the bot can help investigate this issue here.
