### ISSUE TITLE
怎么毙掉版本接口，因为每次访问这个接口都是504.求大佬们给个解决办法。

### ISSUE THREAD

**Issue by limuan123** [langgenius/dify#436]
Dify version: Cloud | Self Host

## Steps To Reproduce

1.
2.

**Comment by flaskeer** [comment]
docker-compose.yaml 里新增  CHECK_UPDATE_URL: ""

**Comment by monrat** [comment]
> > docker-compose.yaml 里新增 CHECK_UPDATE_URL: ""
> 
> 有用！！！

请教一下，是加到api组里面还是加到所有的内容下面？

**Comment by takatost** [comment]
> > > docker-compose.yaml 里新增 CHECK_UPDATE_URL: ""docker-compose.yaml 里新增 CHECK_UPDATE_URL: ""
> > 
> > 
> > 有用！！！
> 
> 请教一下，是加到api组里面还是加到所有的内容下面？

api service
