### ISSUE TITLE
The variable "sys.files" cannot be obtained in other nodes of the workflow.

### ISSUE THREAD

**Issue by BellMeng** [langgenius/dify#4363]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a LLM workflow.
2. Try to use the variable "sys.files" in second workflow node.
![image](https://github.com/langgenius/dify/assets/45488105/263aacb4-8f58-4edc-9a03-c9928db61ffc)
![image](https://github.com/langgenius/dify/assets/45488105/00a109f8-0df5-4ed0-a710-f6520ecc707b)

### ✔️ Expected Behavior

The variable "sys.files" can be used in overall workflow node.

### ❌ Actual Behavior

The variable "sys.files" only can be used in start and end node.

**Comment by iamjoel** [comment]
Now sys.files can be only used in LLM node for vision model.

**Comment by mmmmmmmgo** [comment]
I like to read or modify files passed to llm during workflow process.
Is there planned support?

**Comment by DavinciEvans** [comment]
> Now sys.files can be only used in LLM node for vision model.

I have used the LLM vision model, but it seems no sys.files appear in options.

![20240516103158](https://github.com/langgenius/dify/assets/45795384/c5a31b46-886e-4918-a131-fd2b7b9d39e7)

**Comment by wentaotang0** [comment]
![企业微信截图_52eb6f25-b7ed-484f-9ad7-0196eca165ce](https://github.com/user-attachments/assets/704bacad-3f31-43c2-834b-82396aa488f8)
![企业微信截图_508d6298-cd48-4639-9be0-84c7db6913c6](https://github.com/user-attachments/assets/7742b43f-b5f0-450e-ba1f-e3462a2d3102)
![企业微信截图_c23392be-0ca3-49aa-b4d9-e82f3ccb522b](https://github.com/user-attachments/assets/5daba5f7-2040-4bd5-ba70-9d539e2b46c9)

Hello, I also encountered the same problem, I want to reference the sys.files variable in other nodes, but I can't get it, including llm (gpt4o with Visual recognition), is there another way to help me?

My scenario is that I need to feed the text input to the llm output text as the input to the knowledge base
