### ISSUE TITLE
HTTP REQUEST NODE is always waiting but endpoint have responsed

### ISSUE THREAD

**Issue by Albedoww** [langgenius/dify#4386]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

the HTTP REQUEST NODE is always waiting but endpoint have responsed.
i checked the  HTTP REQUEST NODE singly running is successful
![{128724-x-21020669104275}](https://github.com/langgenius/dify/assets/150100827/6a7cf3cf-6195-4914-a6ce-9c93989f18d3)
![qq_pic_merged_1715704379616](https://github.com/langgenius/dify/assets/150100827/7594aa4c-0a0c-4e32-b3fc-b8149b5e782b)

**Comment by hjlarry** [comment]
@Albedoww please upgrade the latest version to see if it is resolved
