### ISSUE TITLE
对话返回的数据截断了

### ISSUE THREAD

**Issue by eggb4by** [langgenius/dify#440]
![image](https://github.com/langgenius/dify/assets/6998751/4ed07a0c-b652-4a55-96e1-bf6c490d5d85)
我用的Azure的GPT-3.5，刚才问了好几个问题，最后都类似截图中这样截断了

**Comment by eggb4by** [comment]
找到原因了，app里模型默认token 512，加多就好了

**Comment by jacksonwen001** [comment]
> 找到原因了，app里模型默认token 512，加多就好了

在哪里设置呢？

**Comment by eggb4by** [comment]
> 

提示词编排->选择模型
