### ISSUE TITLE
使用Dify.AI过程中总是出现  “应用程序错误：发生客户端异常（有关详细信息，请参阅浏览器控制台）”是怎么回事，怎么解决

### ISSUE THREAD

**Issue by shudan0722** [langgenius/dify#4407]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

没找到

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/169868809/b8194716-6b51-4197-85ab-e8b56836c325)

### ✔️ Expected Behavior

帮我解决用不了的问题

### ❌ Actual Behavior

用不了

**Comment by starmido** [comment]
0.6.8是目前最新的版本，也遇到这个问题了

**Comment by starmido** [comment]
> 0.6.8是目前最新的版本，也遇到这个问题了

我这边是通过0.6.5升级到0.6.8的

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by qqlww1987** [comment]
我也遇见了

**Comment by flyice8** [comment]
兄弟们什么解决的啊？
