### ISSUE TITLE
Layout error

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#4415]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1171" alt="image" src="https://github.com/langgenius/dify/assets/12423206/7e929daa-c6a5-486c-9605-9479f0151aea">

**Comment by iamjoel** [comment]
I can't reproduce it. You can upgrade to the latest version to see if it will be ok.
