### ISSUE TITLE
本地构建后端 server_api 容器启动失败

### ISSUE THREAD

**Issue by niceTeen84** [langgenius/dify#4417]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/31087234/452be898-ae12-47ba-9993-76caeb83c6f0)
构建完镜像后，启动报错。错误如上图

### ✔️ Expected Behavior

本地构建后正常运行

### ❌ Actual Behavior

本地构建后端 server_api 容器启动失败

**Comment by crazywoola** [comment]
Close due to #1542
