### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by KclearV** [langgenius/dify#4426]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Is there a suitable Weaviate image for the Red Hat (Linux) environment? I pulled the SemiTech/Weaviate:1.19.0 image from Docker on my Mac, saved it as a tar file, scp'd it to a Linux server, and then ran `docker run` but got an "exec format error" message.

**Comment by crazywoola** [comment]
Well I think you should post a question here https://github.com/weaviate/weaviate
