### ISSUE TITLE
Add Volcengine Doubao-embedding model error

### ISSUE THREAD

**Issue by dn833** [langgenius/dify#4430]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I add Volcengine Doubao-embedding ，got the error message
“2 validation errors for EmbeddingUsage tokens none is not an allowed value (type=type_error.none.not_allowed) total_tokens none is not an allowed value (type=type_error.none.not_allowed)”
![WechatIMG4163](https://github.com/langgenius/dify/assets/5283189/714a441e-8546-4514-80b6-fa9a214a633a)

**Comment by sinomoe** [comment]
fixed in #4431
