### ISSUE TITLE
Blank lines when writing code

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4434]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Make Gpt-4o or similar LLM's write long code. It looks like it just pushes a lot of blank lines when it reaches the context window? 

### ✔️ Expected Behavior

Either stop at the context window or finish writing the code.

### ❌ Actual Behavior

a lot of blank lines (see video)

https://github.com/langgenius/dify/assets/119136210/fc5bcb09-7af8-4522-8b81-a479c0b3c343

**Comment by iamjoel** [comment]
I use the gpt-4o but i can't reproduce the issue. Can you support more detail  to  reproduce?
<img width="700" alt="image" src="https://github.com/langgenius/dify/assets/2120155/541821e2-59f2-4621-87a3-ca45ac0d7c42">
