### ISSUE TITLE
私有云部署，OpenAI key检验失败

### ISSUE THREAD

**Issue by donttal** [langgenius/dify#444]
Dify version: Self Host

## Steps To Reproduce

1. 在私有云已经成功部署并访问
<img width="1549" alt="image" src="https://github.com/langgenius/dify/assets/30567352/1478214e-9292-4abd-8d9d-ab869adc4320">

3.在模型供应商输入可用且有效的API key会出现request timeout
<img width="460" alt="image" src="https://github.com/langgenius/dify/assets/30567352/ae07141e-c9e0-49f4-aa2a-37705d4bd487">

提问：
是否云有开启某些端口或者dify验证设置能修改？

**Comment by crazywoola** [comment]
The server should behind a proxy or locate in other countries
