### ISSUE TITLE
ChatApp streaming response not working as expected

### ISSUE THREAD

**Issue by lzs0603** [langgenius/dify#4440]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I used the example code to make a call to the chat app built in dify (the dify is installed with docker compose)

My data as follows: 
const dataNew = {
                inputs: {},
                query: "hello",
                response_mode: "streaming",
                conversation_id: "",
                user: "abc-123",
            }

### ✔️ Expected Behavior

For a normal streaming service, the streaming response should come in chunks, words by words. Like following
![Screenshot 2024-05-16 at 11 24 23 AM](https://github.com/langgenius/dify/assets/33793693/e240c663-57b6-4fa1-9990-a04bf395bc26)
![Screenshot 2024-05-16 at 11 24 36 AM](https://github.com/langgenius/dify/assets/33793693/f7fac42a-fbef-431f-8d48-fe00bd84e52f)

### ❌ Actual Behavior

Altho the response format is in text/event-stream, the event stream actually came in once, not in chunks. 
![Screenshot 2024-05-16 at 11 17 13 AM](https://github.com/langgenius/dify/assets/33793693/e2fe88a4-d9af-45ae-ab86-7611b57a9f2f)
![Screenshot 2024-05-16 at 11 17 23 AM](https://github.com/langgenius/dify/assets/33793693/345e939e-7631-47e1-88ce-d81044df9358)

**Comment by lzs0603** [comment]
Problem solved, thx

**Comment by richardcoder** [comment]
> Problem solved, thx

Sorry to bother you, but may I know how do you solve this problem? I face the same problem here, thanks in advance

**Comment by ocxers** [comment]
@richardcoder, for me, these settings help resolve the issue. 
![image](https://github.com/user-attachments/assets/41b67090-ee93-4e63-a3d1-4b1d727da5c5)
