### ISSUE TITLE
The problem of inability to access after docker-compose deployment.

### ISSUE THREAD

**Issue by LmhCcc** [langgenius/dify#4443]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I followed this document to carry out the deployment, but after the deployment was completed, I couldn't access it. [link](https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/docker-compose)
![image](https://github.com/langgenius/dify/assets/92771326/80bb4fcb-b259-435f-8e92-0ae33d61a899)

### ✔️ Expected Behavior

I believe I should be able to access it.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/92771326/7b50057f-c8bd-4155-8e4d-633ab1056215)

**Comment by LmhCcc** [comment]
I only modified the server_name in /nginx/conf.d/default.conf to my server address.

**Comment by patryk20120** [comment]
You should be able to access it on http://localhost:80

**Comment by KclearV** [comment]
@dosu Accessing the Application: If attempting to access the application from a machine different from where it's hosted, ensure you're using the server's IP address or domain name instead of localhost. which config should I change if i meet this situation
