### ISSUE TITLE
Why there is no direct reply node in the workflow after docker deployment?

### ISSUE THREAD

**Issue by yp94** [langgenius/dify#4446]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="297" alt="image" src="https://github.com/langgenius/dify/assets/28262260/7d2a88ac-8dc8-48a0-b71c-95cd671b947e">

**Comment by crazywoola** [comment]
"direct reply node" only lives in chatflow, not workflow.
