### ISSUE TITLE
After deploying the non-80 port, publish the application and jump to the new web page to carry the port.

### ISSUE THREAD

**Issue by kokojacket** [langgenius/dify#4449]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/74887370/934df12d-e77a-4f02-be96-ee94427a69ca)
![image](https://github.com/langgenius/dify/assets/74887370/1633d761-3a71-4a36-a39a-1035d04201cf)
![image](https://github.com/langgenius/dify/assets/74887370/2801837e-cbc4-41fa-8a3c-609e4cd8e003)

### ✔️ Expected Behavior

You should also need to carry port 3000 before you can use it after the jump__

### ❌ Actual Behavior

After deploying the non-80 port, publish the application and jump to the new web page to carry the port.
![image](https://github.com/langgenius/dify/assets/74887370/2801837e-cbc4-41fa-8a3c-609e4cd8e003)

**Comment by patryk20120** [comment]
I don't really get the issue here. Have you change something in docker-compose file?

**Comment by kokojacket** [comment]
![image](https://github.com/langgenius/dify/assets/74887370/90a958a7-2db1-4795-b4f1-19c12cd559ca)
 I only changed this

**Comment by patryk20120** [comment]
So you should access the web on that port http://localhost:10034

**Comment by kokojacket** [comment]
> So you should access the web on that port http://localhost:10034

 I used a reverse proxy tool to proxy http://localhost:10034/ to the public network. Then when I used "publish", the port would disappear when jumping.  __

**Comment by superstring** [comment]
may be web should add nginx expose-port config, rather than always use 80

**Comment by kuit123** [comment]
docker-compose.yml,needs to modify Api: environment variables, APP_WEB_URL，SERVICE_API_URL，fill in 'http://ip:<nginx port>'

**Comment by kokojacket** [comment]
Yes my problem is solved now__

**Comment by ml-dl-ysw** [comment]
> Yes my problem is solved now_

what is the method?

**Comment by torans** [comment]
> > 是的，我的问题现在解决了_
> 
> 方法是什么？

同问

**Comment by zhihuai1982** [comment]
> > > 是的，我的问题现在解决了_
> > 
> > 
> > 方法是什么？
> 
> 同问

docker-compose.yml,needs to modify Api: environment variables, APP_WEB_URL，SERVICE_API_URL，fill in 'http://ip:nginx/ expose-port'

**Comment by kuit123** [comment]
docker/docker-compose.yml中的
