### ISSUE TITLE
无法邀请用户登录

### ISSUE THREAD

**Issue by charlescui** [langgenius/dify#445]
Dify version: Self Host

## Steps To Reproduce

1. 管理员登录
2. 进入管理员设置
3. 进入工作空间-成员
4. 点击添加
5. 输入邮箱再点击添加

## The current behavior
无法邀请用户登录，导致只有一个初始化时候创建的管理员账号可用

## The expected behavior
希望可以邀请用户加入工作空间，希望有多个账号可用某个工作空间

**Comment by charlescui** [comment]
![image](https://github.com/langgenius/dify/assets/875374/cb200453-f5c9-45fe-a590-d9a97c5fc09d)

**Comment by crazywoola** [comment]
See #56
