### ISSUE TITLE
[Issue Report] Model Addition Failure: Local Models Not Displayed in System-Model Settings Search Results

### ISSUE THREAD

**Issue by LouisCan** [langgenius/dify#4450]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

During the following operations, I encountered an issue: I successfully deployed ReRank, Text Embedding, and Chat models on the server using XinFerence and OpenAI-API-compatible methods. The deployment process indicated that everything was completed successfully, suggesting that these models should be ready for use.

However, when attempting to locate these newly added local models within the System-Model Settings, they were not appearing in the search results. This situation hinders the intended workflow of directly accessing or managing these models from this interface.

**Reproduction Steps:**

Deploy the ReRank, Text Embedding, and Chat models using XinFerence and OpenAI-API-compatible tools.
After confirming successful deployment, access the system administration interface.
Navigate to the System-Model Settings section and attempt to search for the newly deployed models.

**Expected Result:**
Upon entering the model name in the search bar of the System-Model Settings, the relevant local models should promptly appear in the search results.

**Actual Result:**
The models were not retrieved; the search results were empty.

**Temporary Solution:**
Currently, to make these models visible and selectable in the System-Model Settings, additional steps are required:

Create a new application first.
Within this application, manually select the chat model that was previously deployed.
Only after launching the application do these models become visible within the System-Model Settings interface.
Desired Resolution:
Please investigate and fix this issue to ensure that future deployments of local models are instantly and accurately reflected in the System-Model Settings search results without necessitating further manual intervention.

### ✔️ Expected Behavior

Upon entering the model name in the search bar of the System-Model Settings, the relevant local models should promptly appear in the search results.

### ❌ Actual Behavior

The models were not retrieved; the search results were empty.

**Comment by wanshichenguang** [comment]
现在是否支持自定义ReRank模型？

**Comment by LouisCan** [comment]
@dosu irrelevant answer

**Comment by LouisCan** [comment]
@wanshichenguang can， Use the same interface protocol
