### ISSUE TITLE
After importing a third-party library into the Python sandbox container, the execution results are inconsistent between the container and the web interface

### ISSUE THREAD

**Issue by 115341chenzehao** [langgenius/dify#4463]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.I successfully imported the third-party Python library 'mysql-connector-python' into the sandbox container, and the execution of 'import mysql.connector' was successful.
![4](https://github.com/langgenius/dify/assets/61967670/74b7d10b-69f8-49f3-9b82-c0556a31479d)

2.However, when executing the script in the web interface, the prompt states 'in ModuleNotFoundError: No module named 'mysql' error'
![5](https://github.com/langgenius/dify/assets/61967670/870c7992-47de-452a-859d-ba5d413c55c5)

'dify-api' and 'sandbox' are network-connected, and the corresponding .py files will be generated within the sandbox container.
![6](https://github.com/langgenius/dify/assets/61967670/099f98c5-5963-486d-a4ef-8bc52df8faa0)

**Comment by 115341chenzehao** [comment]
1.I successfully imported the third-party Python library 'mysql-connector-python' into the sandbox container, and the execution of 'import mysql.connector' was successful.
![4](https://github.com/langgenius/dify/assets/61967670/53f4c6cf-90a0-49b3-bd72-b4cab4dde718)

**Comment by 115341chenzehao** [comment]
@dosubot I would like to inquire about how 'code execution' occurs within the sandbox container. I have noticed that the 'dify-sandbox' container comes with the Python library 'request' pre-installed, yet it still cannot be imported.
![7](https://github.com/langgenius/dify/assets/61967670/7294c2e7-cf38-4daa-adeb-f2bb35ee8d86)

![8](https://github.com/langgenius/dify/assets/61967670/b3402499-0791-468f-a94e-bbdb4815f3e2)

**Comment by 115341chenzehao** [comment]
> To resolve the issue with the 'requests' library not being imported in your Dify sandbox environment, despite it being pre-installed, you should ensure that your project is correctly set up to install external libraries. Here's a concise guide:
> 
> 1. **Create or Update `requirements.txt`**: In the `api` directory of your project, ensure there's a `requirements.txt` file listing `requests` and any other libraries you need. Format it like so:
>    ```
>    requests==2.25.1
>    ```
> 2. **Check Project Structure**: The `requirements.txt` should be in an `api` directory at your project's root.
> 3. **Restart Dify Sandbox**: Deploy your project or restart the sandbox. The `post_start_command.sh` script will run `pip install -r requirements.txt`, installing the specified libraries.
> 4. **Test Library Installation**: After restarting, test the `requests` library with a simple script to confirm it's working as expected.
> 
> This approach leverages Dify's mechanism for handling external libraries via a `requirements.txt` file, ensuring your scripts can use `requests` within the sandbox. If issues persist, ensure your project aligns with Dify's guidelines on allowed operations and library usage, as recent updates restrict certain activities. For more detailed guidance, refer to the Dify documentation and the `post_start_command.sh` script.
> 
> #### Details
> _To continue the conversation, mention @dosu._

I am also failing to call the Flask dependency from the requirements.txt file during 'code execution'
![9](https://github.com/langgenius/dify/assets/61967670/a458218f-699a-4962-af58-9d44e5f6d1bc)

**Comment by 115341chenzehao** [comment]
> To address the issue with libraries not being imported in your Dify sandbox environment, first ensure that `mysql-connector-python` and `requests` are correctly listed in your `requirements.txt` file, including specifying the versions if necessary. For example:
> 
> ```
> mysql-connector-python==8.0.23
> requests==2.25.1
> ```
> 
> After updating `requirements.txt`, rebuild the container to install these dependencies. If you're still facing issues, manually install them inside the container for testing:
> 
> ```
> pip install mysql-connector-python requests
> ```
> 
> This can help identify any potential errors not related to the `requirements.txt` file. Also, check the permissions and ensure the `pip` version inside the container is up to date to avoid installation issues.
> 
> Regarding accessing the "dify-sandbox" source code, since Dify is open-source, the code should be available on their official GitHub or GitLab repository. If you can't find it, consult the project's documentation or contact the maintainers for guidance.
> 
> Keep in mind, Dify's sandbox environment has limitations, such as restricted file system access, network calls, and operating system-level commands, which might lead to `ModuleNotFoundError` for some modules.
> 
> #### Details
> _To continue the conversation, mention @dosu._

I tried to successfully install mysql-connector-python in the sandbox container, but when "code_executor" ran the py script, import mysql.connector prompted ModuleNotFoundError, so I wanted to take a look at the source code of "dify-sandbox". I found it on dify's github. I haven't found the sandbox information. Can you help me consult?

**Comment by 865357384** [comment]
May I ask if this problem has been resolved?

**Comment by 115341chenzehao** [comment]
> May I ask if this problem has been resolved?

Not yet. Do you have similar problems?

**Comment by 865357384** [comment]
> > 请问这个问题解决了吗？
> 
> 还没有。您也有类似的问题吗？

yes

**Comment by 865357384** [comment]
I couldn't find the source code for "dify sandbox", so I have no way to start

**Comment by smartjx** [comment]
same issue here , please help

**Comment by Tim-Saijun** [comment]
up

**Comment by thibaudbrg** [comment]
Same issue here, just installed `beautifulsoup4` 

The `/dependencies/python-requirements.txt`:

```python
beautifulsoup4
requests
redis
openai
pydantic
atlassian-python-api
```


Logs of the `dify-sandbox` docker container:

```log
06/14/2024
02:39:27 PM
2024/06/14 12:39:27 nodejs.go:32: [INFO]initializing nodejs runner environment...
06/14/2024
02:39:28 PM
2024/06/14 12:39:28 setup.go:98: [INFO]Collecting beautifulsoup4
06/14/2024
02:39:28 PM
2024/06/14 12:39:28 setup.go:98: [INFO]  Downloading https://................../beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
.................
..............
06/14/2024
02:39:28 PM
2024/06/14 12:39:28 setup.go:98: [INFO]     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.9/147.9 kB 5.9 MB/s eta 0:00:00
06/14/2024
02:39:28 PM
2024/06/14 12:39:28 setup.go:98: [INFO]
06/14/2024
02:39:29 PM
2024/06/14 12:39:29 setup.go:98: [INFO]  Preparing metadata (setup.py): started
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]  Preparing metadata (setup.py): finished with status 'done'
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]Building wheels for collected packages: wrapt
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]  Building wheel for wrapt (setup.py): started
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]  Building wheel for wrapt (setup.py): finished with status 'done'
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]  Created wheel for wrapt: filename=wrapt-1.12.1-py3-none-any.whl size=19554 sha256=6b9f8c401aab3f77dce44fd6014d214b495668bcb1bac7df26f0a8414f0dc581
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]  Stored in directory: /root/.cache/pip/wheels/e6/69/b0/18c881879b8a9d8d903717d38a570abca52c70f32b26d850da
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]Successfully built wrapt
06/14/2024
02:39:30 PM
2024/06/14 12:39:30 setup.go:98: [INFO]Installing collected packages: wrapt, tqdm, soupsieve, six, pydantic, oauthlib, jmespath, distro, deprecated, async-timeout, requests-oauthlib, redis, beautifulsoup4, openai, atlassian-python-api
06/14/2024
02:39:32 PM
2024/06/14 12:39:32 setup.go:98: [INFO]Successfully installed async-timeout-4.0.3 atlassian-python-api-3.41.14 beautifulsoup4-4.12.3 deprecated-1.2.14 distro-1.9.0 jmespath-1.0.1 oauthlib-3.2.2 openai-1.33.0 pydantic-1.10.15 redis-5.0.3 requests-oauthlib-2.0.0 six-1.16.0 soupsieve-2.5 tqdm-4.66.4 wrapt-1.12.1
06/14/2024
02:39:32 PM
2024/06/14 12:39:32 setup.go:119: [INFO]Python dependency installed: beautifulsoup4 
```

The dependencies libraries are indeed available:

![image](https://github.com/langgenius/dify/assets/73235385/f8732a66-8d4c-490f-87df-cb18facb0fe4)

and my code imports them:

![image](https://github.com/langgenius/dify/assets/73235385/51113fcd-7d79-44d5-8331-3ab6f9240b51)

**But i get the error:**

![image](https://github.com/langgenius/dify/assets/73235385/5e347d26-c64a-48f3-b6f6-d30b4c9eca4d)

**Comment by thibaudbrg** [comment]
First discovery, 
Dify automatically adds some pre import lines for every executed code that looks like this:



```python
# cat /tmp/code/5c5fc6b0_76f1_49ec_bf35_87bc3723ee81.py
import ctypes
import os
import sys
import json
import time
import traceback
# setup sys.excepthook
def excepthook(type, value, tb):
    sys.stderr.write("".join(traceback.format_exception(type, value, tb)))
    sys.stderr.flush()
    sys.exit(-1)

sys.excepthook = excepthook

lib = ctypes.CDLL("./tmp/sandbox-python/python.so")
lib.DifySeccomp.argtypes = [ctypes.c_uint32, ctypes.c_uint32, ctypes.c_bool]
lib.DifySeccomp.restype = None


import requests
--> import beautifulsoup4 # ADDED FROM THE GUI DROPDOWN MENU
import functools
import binascii
import time
import hmac
import operator
import traceback
import hashlib
import random
import itertools
import datetime
from datetime import datetime
datetime.strptime('2021-01-01', '%Y-%m-%d')
import re
import math
import collections
import json
import string
import uuid
import sys
import os
import base64

lib.DifySeccomp(65537, 1000, 1)

# YOUR CODE FROM HERE
```

If I specify some libraries in the GUI via "ADVANCED DEPENDENCIES" then it will just add an import line in the precode, as you can see above with `ìmport beautifulsoup4`

![image](https://github.com/langgenius/dify/assets/73235385/1117bd57-ce7f-40bb-aee9-d52702e0d304)


**First problem:** BeautifulSoup is a great example as the import should be handled with this line `from bs4 import BeautifulSoup` and not `import beautifulsoup4` so this implementation might cause problem if the name of the dependency is not the name that should be used to import it.

**Second problem (main problem of the GitHub Issue):** So i decided to not use the GUI ADVANCED DEPENDENCIES dropdown menu and instead write manually my imports in the code. 
But even after writing the correct `from bs4 import BeautifulSoup` I get:

![image](https://github.com/langgenius/dify/assets/73235385/ebfe484e-afa9-4842-8cc1-d56cca14721c)
![image](https://github.com/langgenius/dify/assets/73235385/91e58ec0-2658-4b4a-972f-1438cce24b91)


But running the code directly from the terminal does work:

```shell
# python /tmp/code/d284b100_93dc_4832_852c_56e48a0cdc15.py
{'result': {'pages': {'...................................'}}}
```

So What does the ADVANCED DEPENDENCIES dropdown menu do more that just to add some pre-lines before the code that makes the code run correctly. 


What does this litteraly change if `requests` is written (see comments below):

```python
# cat /tmp/code/01b318a6_8b12_4374_9ae1_a1011ac41648.py
import ctypes
import os
import sys
import json
import time
import traceback
# setup sys.excepthook
def excepthook(type, value, tb):
    sys.stderr.write("".join(traceback.format_exception(type, value, tb)))
    sys.stderr.flush()
    sys.exit(-1)

sys.excepthook = excepthook

lib = ctypes.CDLL("./tmp/sandbox-python/python.so")
lib.DifySeccomp.argtypes = [ctypes.c_uint32, ctypes.c_uint32, ctypes.c_bool]
lib.DifySeccomp.restype = None

# HERE (IF USING DROPDOWN MENU IN GUI)
------------------> import requests
------------------> etc...

import functools
import binascii
import time
import hmac
import operator
import traceback
import hashlib
import random
import itertools
import datetime
from datetime import datetime
datetime.strptime('2021-01-01', '%Y-%m-%d')
import re
import math
import collections
import json
import string
import uuid
import sys
import os
import base64

lib.DifySeccomp(65537, 1000, 1)


# declare main function
# OR HERE IF WRITING THE IMPORTS IN THE CODE DIRECTLY
------------------> import requests
------------------> import urllib3
------------------> import re
------------------> from bs4 import BeautifulSoup

# the rest of my code
```

**Comment by smartjx** [comment]
any update?

**Comment by mai-group-labs** [comment]
I agree, the ability to add dependencies in the execution sandbox would be very helpful. 

@thibaudbrg which /dependencies/python-requirements.txt did you change? I am not able to find the Dockerfile for the execution sandbox, this makes it hard to reason about how to actually change anything.

**Comment by thibaudbrg** [comment]
@mai-group-labs on the sandbox container. This is the container used for python execution.

`docker exec -it sandbox_container_name /bin/sh`

And the every python code you write are located `/temp/code/`.

Also you can access the file `/dependencies/python requirements.txt` from the same container. But it is easier to directly bind the /dependencies/ folder as a volume in the sandbox docker compose:

```yaml
volumes:
      - ./volumes/sandbox/dependencies:/dependencies
```


I upgraded to sandbox container 0.2.1 but didn't tried if the problem was solved. It'd be nice to have an answer from someone involved at Dify.

**Comment by 26awen** [comment]
Same problem with sandbox 0.2.1, you can import third party package in the container(docker exec -it sandbox_container_name /bin/sh), but get a ModuleNotFound error in the web application. 
 Further more, the "ADVANCED DEPENDENCIES" ui function just add the import line in the code file is not always right for some package, for example :add a line like :import langchain-text-splitters will cause "import langchain-text-splitters ^ SyntaxError: invalid syntax error: exit status 1".

**Comment by fivem** [comment]
up

**Comment by triple-Mu** [comment]
Same problem.

**Comment by fivem** [comment]
Same problem.

**Comment by jerryleooo** [comment]
Same problem

**Comment by NKfairyland** [comment]
The same problem occurs when importing beautifulsoup4.
As @thibaudbrg analyzed, the way to import dependent libraries is confusing. To sum up, there are two questions:
1. Since selecting a dependent library in the "Advanced Dependencies" drop-down menu only adds a line of "import ..." when generating a .py file, why is it invalid to just add a line of "import ..." in the code block, and you must select the dependent library in the "Advanced Dependencies" drop-down menu?
2. If you must select a dependent library in the "Advanced Dependencies" drop-down menu, it only supports the form of "import requests", but cannot support forms such as "from bs4 import BeautifulSoup", which is really not flexible enough.
This problem does not occur at all in normal Python programming. I don't understand why an "advanced dependency" mechanism should be introduced. Instead, it complicates the problem, but I don't see any benefits.

**Comment by NKfairyland** [comment]
> @dosubot I would like to inquire about how 'code execution' occurs within the sandbox container. I have noticed that the 'dify-sandbox' container comes with the Python library 'request' pre-installed, yet it still cannot be imported. ![7](https://private-user-images.githubusercontent.com/61967670/331484354-7294c2e7-cf38-4daa-adeb-f2bb35ee8d86.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTA1NjAsIm5iZiI6MTcyMzI5MDI2MCwicGF0aCI6Ii82MTk2NzY3MC8zMzE0ODQzNTQtNzI5NGMyZTctY2YzOC00ZGFhLWFkZWItZjJiYjM1ZWU4ZDg2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDExNDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMjQ5Mzc0YmUzYWI2ZDcyZDJlMjk4NWNkMTg2M2MxNjBlZTlmMzM5ZjQxZDQ5M2M4ZDM5MTExM2E0NjI5MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.56Jvik-3wUcNp_J152eJRZCA7FyBQ0CcmHbeAg_PKPw)
> 
> ![8](https://private-user-images.githubusercontent.com/61967670/331484420-b3402499-0791-468f-a94e-bbdb4815f3e2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTA1NjAsIm5iZiI6MTcyMzI5MDI2MCwicGF0aCI6Ii82MTk2NzY3MC8zMzE0ODQ0MjAtYjM0MDI0OTktMDc5MS00NjhmLWE5NGUtYmJkYjQ4MTVmM2UyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDExNDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNDFiZjAxMTVmY2RjNTdkYTM5ODY3ZmU4NzVjYzIyZmViZTUzODFiMTcwNjRjMzkyN2E5M2U4ZGNkYTRhMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rXycM-7M2fV1Z7WzqnoVGDu_BrgljrB9yudqveiJj2c)

The requests library can be imported. You need to add an item in "Advanced Dependencies" and select "requests" in the drop-down menu.
However, the beautifulsoup4 library cannot be imported in the same way, because the correct format is "from bs4 import BeautifulSoup", not "import beautifulsoup4".

**Comment by mumugoah** [comment]
any update?

**Comment by lzzzzzzzzz** [comment]
> lsoup4 library cannot be importe

change sandbox:0.2.1 to sandbox 0.2.4

**Comment by FrancisVarga** [comment]
Is there any possible to create several environments with conda and manage it there too?

**Comment by prd-tuong-nguyen** [comment]
same problem

**Comment by ljw-612** [comment]
same problem

**Comment by farkoo** [comment]
Same Problem

**Comment by fivem** [comment]
any update?

**Comment by djoffrey** [comment]
Solution for install third-party library!
1. start dify
2. edit the dify/docker/volumes/sandbox/dependencies/python-requirements.txt
3. docker compose restart sandbox

use docker compose logs sandbox to check if your library is installed.

mine is : 
```
docker-sandbox-1  | 2025/01/24 07:45:08 setup.go:161: [INFO]Python dependency installed: requests
```

**Comment by Leeshy-star** [comment]
I have already added the required third-party libraries in the python-requirements.txt file. After restarting the sandbox, other libraries were imported and ran normally.
![Image](https://github.com/user-attachments/assets/fbf6ccf3-89a8-460b-b06c-28d04fe3d8dc)

However, as soon as I import import matplotlib.pyplot as plt, it throws the following error when running.

![Image](https://github.com/user-attachments/assets/0f42cd8c-167b-405f-a33e-383b33d5631e)

I have referred to https://github.com/brightwang/dify-sandbox-use-check-permissions and added system call permissions.

**Comment by Leeshy-star** [comment]
Before importing import matplotlib.pyplot as plt, I added directory configurations, but encountered the following error.
![Image](https://github.com/user-attachments/assets/6fcd4d8e-23b9-4179-aacd-ad6e3c4cbc90)
