### ISSUE TITLE
Extend Tool/Plugin Support to Include Chatbots, Agents, and Workflows

### ISSUE THREAD

**Issue by sunxichen** [langgenius/dify#4468]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, currently, Dify allows only functions (built-in or custom) to be used as tools (plugins) for the large language model. However, I face a limitation where I cannot integrate pre-built chatbots, agents, or orchestrated workflows as tools. This missing capability hinders the full potential of creating modular and collaborative Agent solutions, especially in scenarios where multi-agent cooperation is paramount.

### 2. Describe the feature you'd like to see

I would like to request an enhancement to Dify that extends the existing 'Tools' architecture to accommodate not just functions but also chatbots, agents, and workflows. The vision is to enable users to package their standalone, once developed and refined chatbots, intelligent agents, or complex workflows as plugins, making them seamlessly accessible to a 'master' or orchestrating agent. The 'master' agent can delegate different tasks to the appropriate "expert" based on the user's needs.

### 3. How will this feature improve your workflow or experience?

With this feature, I would be able to construct a highly modular and scalable system where multiple expert chatbots or agents, each focusing on specific tasks, or complex and complete workflows, can be deployed as needed. Developers could create and maintain task-specific chatbots, agents, or workflows independently, then easily plug them into more extensive systems, fostering a microservices-like approach to AI development. And developers can configure different 'expert' agents to a 'master' agent. This would not only enhance the capability of the master agent to handle a wide range of user requests efficiently but also pave the way for experimenting with multi-agent collaborative scenarios. BTW, I find that this is a bit like how Coze uses workflow some how.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by iis-MarkKuang** [comment]
Hi @sunxichen do you have a working branch right now? I'm also interested in making agents/workflows reusable by wrapping them to tools, is it okay to loop me in? Thanks.

**Comment by loganclark360** [comment]
[3 locations/dicy]no/...

W. Logan Clark

**Comment by loganclark360** [comment]
[3 locations/dicey]no extend Tool...

W. Logan Clark

**Comment by sunxichen** [comment]
> Hi @sunxichen do you have a working branch right now? I'm also interested in making agents/workflows reusable by wrapping them to tools, is it okay to loop me in? Thanks.

@iis-MarkKuang Sorry, as for now,  I don't have a working branch for this idea😢 My post was intended to see if any other developers look forward to these features as well and start a discussion within the community. I may start working on this when I have some spare time. If you decide to explore this concept and initiate a branch, please do let me know. I'd love to follow your progress, provide feedback where I can, and possibly contribute or test as things move forward.
