### ISSUE TITLE
When will dify support uploading documents for large model identification and summary, etc.

### ISSUE THREAD

**Issue by bighaidao** [langgenius/dify#4471]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

At present, all major models support document upload applications, but it seems that diffy does not have it yet.

### 2. Describe the feature you'd like to see

![image](https://github.com/langgenius/dify/assets/1301460/41fdffc9-7775-4a5e-a6d4-50b9e9625543)

### 3. How will this feature improve your workflow or experience?

Greatly improve the implementation of application scenarios

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by pjamessteven** [comment]
Better file handling in workflow mode, such as the ability to pass a file or image output from a previous node to the input of an LLM node,  would be amazing!

**Comment by crazywoola** [comment]
Duplicated
