### ISSUE TITLE
CoT agent token usage is empty

### ISSUE THREAD

**Issue by sinomoe** [langgenius/dify#4473]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

chat with a react agent
![image](https://github.com/langgenius/dify/assets/18367114/c3ce677c-a434-48fd-8b22-4f678e4475cb)

### ✔️ Expected Behavior

token usage should not be 0

### ❌ Actual Behavior

token usage is 0

**Comment by yyipkei123** [comment]
It appears that the issue still exist in the latest version (0.6.12-fix1).  Is there a possible workaround?

![image](https://github.com/langgenius/dify/assets/124754092/5e9b54f7-8527-410d-8670-acd16898d99d)

**Comment by Yeuoly** [comment]
which model are you using? It appears that you got 0 tokens when invoking a LLM node inside Chatflow instead of Agent, this could be possible if the model layer does not implemented get_num_tokens method, we need to look into the detailed implementation of this model.

**Comment by yyipkei123** [comment]
> which model are you using? It appears that you got 0 tokens when invoking a LLM node inside Chatflow instead of Agent, this could be possible if the model layer does not implemented get_num_tokens method, we need to look into the detailed implementation of this model.

I am using Gemini 1.5 pro.
