### ISSUE TITLE
聊天对话应用的APP页面，用户是否有登录身份信息？

### ISSUE THREAD

**Issue by charlescui** [langgenius/dify#448]
目前，用户进入对话APP的页面，并不需要登录，直接就可以使用。
我想咨询：
当前产品是否支持，用户登录后再使用。

![image](https://github.com/langgenius/dify/assets/875374/8afeac56-be5b-429f-96e2-a4847d54327b)

**Comment by crazywoola** [comment]
No we do not support this right now.
