### ISSUE TITLE
Agent-chat can't retrival data from ‘Knowledge’

### ISSUE THREAD

**Issue by sanmmm** [langgenius/dify#4481]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I created an agent chat. Then I added the Knowledge I had prepared and turned on 'Citations and Attributions'. But after I asked some questions, the corresponding answer was irrelevant, 'Citations' did not come up

### ✔️ Expected Behavior

After I asked, the answers returned were retrieved from the knowledge, and 'Citations' appear successfully

### ❌ Actual Behavior

After I asked some questions, the corresponding answer was irrelevant, 'Citations' did not come up

**Comment by crazywoola** [comment]
The
