### ISSUE TITLE
stable diffusion api error 404

### ISSUE THREAD

**Issue by olivielvs** [langgenius/dify#4482]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

connect your stable diffusion instance and tried to generate an image, I get a 404 error
log stable diff server v1.9.3 :
API 2024-05-17 10:56:48.558694 200 http/1.1 GET /sdapi/v1/sd-models xxx.xxx.xxx 0.0017
API 2024-05-17 10:56:48.743417 200 http/1.1 POST /sdapi/v1/options xxx.xxx.xxx 0.0012
API 2024-05-17 10:51:49.979496 404 http/1.1 POST /sdapi/v1/txt2img xxx.xxx.xxx 0.0043
log dify server:
{
  "prompt": "a dog",
  "model": "DreamShaperXL_Turbo_v2_1",
  "lora": "",
  "steps": 5,
  "width": 50,
  "height": 50,
  "negative_prompt": "bad art, ugly, deformed, watermark, duplicated, discontinuous lines"
}

{
  "text": "Failed to generate image\n",
  "files": []
}

### ✔️ Expected Behavior

image generation

### ❌ Actual Behavior

error 404

**Comment by olivielvs** [comment]
Thx chat gpt but my post request creates a generation without problem from my dify server. The problem comes from the use of the stable diffusion API by dify. @dosu

**Comment by Scenx** [comment]
我也遇到了同样的错误

**Comment by GiftLee** [comment]
in code  ``` 'sampler_index': 'DPM++ SDE Karras',``` is default
but webui  api not found  DPM++ SDE Karras
404 is sampler is not found

**Comment by olivielvs** [comment]
GG nice

modif "/dify/api/core/tools/provider/builtin/stablediffusion/tools/stable_diffusion.py" in your docker

**Comment by marco-qu** [comment]
how to locate the correct docker and the file? and how to modify?
