### ISSUE TITLE
microphone not authorized

### ISSUE THREAD

**Issue by deepeye** [langgenius/dify#4485]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

why after enabling voice-to-text, when clicking the microphone, it keeps saying that the microphone is not authorized? Both the operating system and the browser have released it.

Docker Compose Deployment for me。

### ✔️ Expected Behavior

support voice to text

### ❌ Actual Behavior

tips: microphone not authorized

**Comment by lancemao** [comment]
are you using https instead of http? AFAIK, web microphone works either for localhost or https websites

**Comment by zyh3826** [comment]
> are you using https instead of http? AFAIK, web microphone works either for localhost or https websites

@lancemao how to publish the `https` URL, mine always `http`

**Comment by lvxinliang** [comment]
> are you using https instead of http? AFAIK, web microphone works either for localhost or https websites

Using https can be recognized normally, but on the Android side, it often does not work properly, what is the reason for this, is clear？

**Comment by lonngxiang** [comment]
same error， Android side how to fixed？
