### ISSUE TITLE
'npm run start' fails on missing files

### ISSUE THREAD

**Issue by tholonia** [langgenius/dify#4500]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Follow the instructions from https://docs.dify.ai/getting-started/install-self-hosted/local-source-code.  The command to run is `npm run start`, which fails
```
> dify-web@0.6.8 start
> cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && cross-env PORT=$npm_config_port HOSTNAME=$npm_config_host node .next/standalone/server.js

cp: cannot stat '.next/static': No such file or directory
```the

### ✔️ Expected Behavior

the output 
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
```

### ❌ Actual Behavior

npm run start
```
> dify-web@0.6.8 start
> cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && cross-env PORT=$npm_config_port HOSTNAME=$npm_config_host node .next/standalone/server.js

cp: cannot stat '.next/static': No such file or directory
```

**Comment by loganclark360** [comment]
Ok do you want me to  stay off the computer

W. Logan Clark

**Comment by junonya** [comment]
@tholonia tholonia
Maybe you forgot the [npm install] command?

**Comment by crazywoola** [comment]
You should run `npm run build` first.
