### ISSUE TITLE
After adding the built-in application on the official website to the workspace, the model modification cannot be completed

### ISSUE THREAD

**Issue by mamacmm** [langgenius/dify#4505]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Add an application (problem classification+knowledge base+chatbot) that comes with the official website to the workspace, then modify the model inside and change it to the qwen model. Testing shows that there is an error, but the knowledge retrieval module still reads the gpt-3.5-turbo model, but the modified model cannot be found on the interface

![image](https://github.com/langgenius/dify/assets/836436/c93215d6-3b2b-46c8-acad-3d6267f439b7)

**Comment by crazywoola** [comment]
You need to setup the system reasoning model in the settings section.
