### ISSUE TITLE
Incorrect use of GPT-4 leads to increased costs

### ISSUE THREAD

**Issue by lvjiajjjlzy** [langgenius/dify#4511]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

选择GPT-4o并运行后，对话就可能会引发问题，问题位于生成标题。After selecting GPT-4o and running it, the conversation can trigger the problem

### ✔️ Expected Behavior

Use GPT-4o to generate the title.使用GPT-4o来生成标题。

### ❌ Actual Behavior

使用了GPT-4。is GPT-4.

**Comment by crazywoola** [comment]
Change this 
<img width="807" alt="image" src="https://github.com/langgenius/dify/assets/100913391/4d78796a-ca46-40d3-bd4b-1fa920a44924">

**Comment by ozeron** [comment]
Wow, GPT-4 is the most expensive one, please change default one to something else. 
I leaked about 10$ over couple of days due to this =(
