### ISSUE TITLE
docker-compose up -d success,but Attempting to telnet to the server at IP address x on port 80 failed.

### ISSUE THREAD

**Issue by KclearV** [langgenius/dify#4529]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.4.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I used docker to deploy dify on the linux server 1.1.1.1 and wanted to access dify from my windows desktop by visiting the http://1.1.1.1:80 page
docker-compose up -d 
docker-compose ps
All up
BUT I can not open the page
telnet 1.1.1.1 80 also failed

### ✔️ Expected Behavior

visit http://1.1.1.1:80 page to use dify

### ❌ Actual Behavior

BUT I can not open the page
windows cmd telnet 1.1.1.1 80 also failed

**Comment by KclearV** [comment]
@dosu I use other linx server 2.2.2.2 to telnet 1.1.1.1 22 ,which can connected to 1.1.1.1,however when i telnet 1.1.1.1 80,which still failed and the log is "No route to host".What's more,i telnet 1.1.1.1 22 in linux server 1.1.1.1 ,which is succeed.

**Comment by KclearV** [comment]
@dosu i telnet 1.1.1.1 80 in linux server 1.1.1.1 ,which is succeed.

**Comment by crazywoola** [comment]
I think you should access it using `1.1.1.1` instead of `1.1.1.1:80`
