### ISSUE TITLE
如何再后台管理再添加或注册新的管理员

### ISSUE THREAD

**Issue by ssseVennn** [langgenius/dify#453]
项目部署好以后，除了第一次访问localhost/install可以注册账号，还有其他途径注册账号吗？

**Comment by linchen111** [comment]
同问

**Comment by maryhp06** [comment]
我自己插数据库，account，tenants等几张表

**Comment by crazywoola** [comment]
> 我自己插数据库，account，tenants等几张表
You can do so.

**Comment by xcw931924821** [comment]
compoonse的你在哪里插入进去的啊

**Comment by xcw931924821** [comment]
> > 我自己插数据库，account，tenants等几张表
> > You can do so.
问下，你手动添加进去的，密码默认是啥加密的呢。
