### ISSUE TITLE
Uploaded file shows: File not found

### ISSUE THREAD

**Issue by kokojacket** [langgenius/dify#4531]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am preparing to build a knowledge base and uploaded a txt file, about 2KB. In the last step, File not found__ was displayed.
![image](https://github.com/langgenius/dify/assets/74887370/bea383ae-5daf-488c-9f64-391ee7cc66e1)
日志：
`
[2024-05-20 09:27:34,271: ERROR/MainProcess] consume document failed
2024-05-20
17:27:34
Traceback (most recent call last):
2024-05-20
17:27:34
  File "/app/api/core/indexing_runner.py", line 64, in run
2024-05-20
17:27:34
    text_docs = self._extract(index_processor, dataset_document, processing_rule.to_dict())
2024-05-20
17:27:34
  File "/app/api/core/indexing_runner.py", line 362, in _extract
2024-05-20
17:27:34
    text_docs = index_processor.extract(extract_setting, process_rule_mode=process_rule['mode'])
2024-05-20
17:27:34
  File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract
2024-05-20
17:27:34
    text_docs = ExtractProcessor.extract(extract_setting=extract_setting,
2024-05-20
17:27:34
  File "/app/api/core/rag/extractor/extract_processor.py", line 81, in extract
2024-05-20
17:27:34
    storage.download(upload_file.key, file_path)
2024-05-20
17:27:34
  File "/app/api/extensions/ext_storage.py", line 54, in download
2024-05-20
17:27:34
    self.storage_runner.download(filename, target_filepath)
2024-05-20
17:27:34
  File "/app/api/extensions/storage/local_storage.py", line 70, in download
2024-05-20
17:27:34
    raise FileNotFoundError("File not found")
2024-05-20
17:27:34
FileNotFoundError: File not found`

**Comment by JohnJyong** [comment]
seems your api service and worker service have different storage setting , pls check the variable `STORAGE_TYPE` @kokojacket

**Comment by kokojacket** [comment]
Thank you very much, it is indeed my deployment that has a problem.  __

**Comment by seeyou112d** [comment]
hi I got the same error, but I checked both api and worker has 
![image](https://github.com/user-attachments/assets/cc22190f-1bc2-43a4-9a66-df9587bbd2dd)
![image](https://github.com/user-attachments/assets/bf5a2bea-f4f5-4bc7-8a2d-dd223a5a0e8f)

STORAGE_TYPE configured as * 
log
![image](https://github.com/user-attachments/assets/1806fce5-eef0-4669-9d85-e0888b95e361)

I can see a file at api container though
![image](https://github.com/user-attachments/assets/c8e76e3d-a84a-4b01-a853-0ba3b6564809)


tried again with a txt file 
![image](https://github.com/user-attachments/assets/aa3c8900-6c39-4515-bc01-d8c783f642f1)
the content is correct 
log
![image](https://github.com/user-attachments/assets/51dba8e0-c39a-4e99-a48f-20df48d9748d)
