### ISSUE TITLE
Bug report: API access Base URLs are incorrect, resulting in inaccessible endpoints

### ISSUE THREAD

**Issue by tregu148** [langgenius/dify#4534]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Install Dify v0.6.8 via self-hosting, elestio
Check the API access Base URLs in the configuration
Observe that all the Base URLs use HTTP protocol instead of HTTPS
![スクリーンショット 2024-05-20 190746](https://github.com/langgenius/dify/assets/54461561/d083cf38-8599-40b9-b1be-822710dadfe6)

### ✔️ Expected Behavior

The API access Base URLs should be correct and allow for successful access to the API endpoints.

### ❌ Actual Behavior

The Base URL strings for API access are incorrect, resulting in the inability to access the API endpoints. When attempting to use the provided Base URLs, the endpoints cannot be reached.

**Comment by patryk20120** [comment]
You may want to change API URL to https

**Comment by tregu148** [comment]
Yes. By changing API URL to https, I could acccess apis.
