### ISSUE TITLE
The options of Chat Enhancement function disapear

### ISSUE THREAD

**Issue by mealcard** [langgenius/dify#4537]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The options of Chat Enhancement function: "Conversation Starters" will disapear even after saving the functions.
![WX20240520-233506@2x](https://github.com/langgenius/dify/assets/4889073/af832973-7392-4dea-b510-d05ee1fec9e6)

**Comment by perzeuss** [comment]
You cannot save opening questions without an opening message message. I think we should add a validation message which tells the user that an opening message is required.

https://github.com/langgenius/dify/assets/11357019/bf9f664b-2802-46bc-8454-1ddb14982db7
