### ISSUE TITLE
Q&A segmentation mode is not displayed

### ISSUE THREAD

**Issue by universfree** [langgenius/dify#4544]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I set the indexing mode in the knowledge base, there are only high-quality and economical modes, and no Q&A mode appears.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/148757607/0bcbc9ff-c5f7-4be4-96f2-b4bafaf62892)

**Comment by rennokki** [comment]
It might be because the Economical engine is not using LLMs. The QA sets are being generated by the default System reasoning model in the settings.

**Comment by universfree** [comment]
> 这可能是因为 Economical 引擎没有使用 LLM。QA 集由设置中的默认系统推理模型生成。

![image](https://github.com/langgenius/dify/assets/148757607/ed7c8368-1353-4fdf-a03f-daa6eea7c0de)
在云上也存在同样的问题，LLM模型都配置好了。

**Comment by universfree** [comment]
> It might be because the Economical engine is not using LLMs. The QA sets are being generated by the default System reasoning model in the settings.

**Comment by universfree** [comment]
> It might be because the Economical engine is not using LLMs. The QA sets are being generated by the default System reasoning model in the settings.

![image](https://github.com/langgenius/dify/assets/148757607/adc8afb6-8c69-489a-8fbb-b578736329c8)
After configuring the corresponding model on the cloud, there is still no Q&A mode.
