### ISSUE TITLE
Timeout Issue with HTTP Requests or Custom Tool API Calls in Workflows

### ISSUE THREAD

**Issue by opsvr202** [langgenius/dify#4545]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Add one or more HTTP request nodes or custom tool nodes in the workflow designer.
2. Save and publish the workflow.
3. Invoke the workflow using the API.
4. Observe if the API call times out after one minute and returns the aforementioned error message.

### ✔️ Expected Behavior

When invoking a workflow through the API, even if it contains HTTP request or custom tool nodes, it should complete as expected without timing out.

### ❌ Actual Behavior

When invoking a workflow through the API, if the workflow contains HTTP request or custom tool nodes, the interface times out after approximately one minute and returns an error message: "Node <node_name> run failed: Failed to invoke tool: timed out."

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this is solved.

**Comment by opsvr202** [comment]
This issue was first discovered in v0.6.8. I upgraded to v0.6.9, but the bug still exists。
![0f55388e4caf8ad4eba9ef86566775c](https://github.com/langgenius/dify/assets/67004564/f15a7023-13de-404a-8a5a-af7a8d305071)
![a24db17e9a2635a934c3a9518e50e53](https://github.com/langgenius/dify/assets/67004564/d0ca8576-fbb0-40dd-ac70-940413e451d3)
![Uploading bfffe5fca9f61a5eac5d3f610554632.jpg…]()
