### ISSUE TITLE
Support for Qwen-long

### ISSUE THREAD

**Issue by ifsheldon** [langgenius/dify#4547]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I'd like to use qwen-long in my agent.

### 2. Describe the feature you'd like to see

Support for qwen-long

### 3. How will this feature improve your workflow or experience?

This can enable super long context as Qwen-long is said to support 10M context window.

### 4. Additional context or comments

Here is the link to the [documentation](https://help.aliyun.com/document_detail/2788811.html)

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by AreChen** [comment]
Super low price, hope to be able to support!

**Comment by qqlww1987** [comment]
I think this is good

**Comment by yelemin** [comment]
I hope this feature soon come.

**Comment by jingminglang** [comment]
This can greatly reduce the cost of using LLM

**Comment by LiXuemin** [comment]
@Yeuoly Please assign this issuse to me.

**Comment by Yeuoly** [comment]
> @Yeuoly Please assign this issuse to me.

Done, look forward to your pull request!
