### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by LanShanPi** [langgenius/dify#4549]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

下面是执行npm install后输出的信息：

> dify-web@0.6.6 prepare
> cd ../ && node -e "if (process.env.NODE_ENV !== 'production'){process.exit(1)} " || husky install ./web/.husky

husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
npm ERR! code 1
npm ERR! path XXX/dify/web
npm ERR! command failed
npm ERR! command sh -c cd ../ && node -e "if (process.env.NODE_ENV !== 'production'){process.exit(1)} " || husky install ./web/.husky

npm ERR! A complete log of this run can be found in: XXX/.npm/_logs/2024-05-21T09_00_50_409Z-debug-0.log

### ✔️ Expected Behavior

None

### ❌ Actual Behavior

None

**Comment by crazywoola** [comment]
Which operating system do you use?
