### ISSUE TITLE
为什么我docker部署最新0.3.5版本

### ISSUE THREAD

**Issue by LumingMelody** [langgenius/dify#455]
探索里面没有其他类型的生成式ai啊 只有文本型和问答型 我看dify官网有好多类型的 比如SQL生成和代码生成器等等

**Comment by crazywoola** [comment]
SQL generator and code generator are completion as well.

**Comment by LumingMelody** [comment]
> SQL generator and code generator are completion as well.
My point is that there are many applications on the https://cloud.dify.ai/explore/apps section of Dify's official website, but I only have access to text generation and question-answering applications on my own Docker deployment
