### ISSUE TITLE
Error occurred when adding Doubao TEXT Embedding model

### ISSUE THREAD

**Issue by xiaohai-78** [langgenius/dify#4550]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

code
: 
"invalid_param"
message
: 
"2 validation errors for EmbeddingUsage\ntokens\n  none is not an allowed value (type=type_error.none.not_allowed)\ntotal_tokens\n  none is not an allowed value (type=type_error.none.not_allowed)"
status
: 
400
![image](https://github.com/langgenius/dify/assets/68817034/7e63ab72-c97c-4420-a14f-1795543692ee)

### ✔️ Expected Behavior

The Doubao TEXT Embedding model can be added normally

**Comment by JohnJyong** [comment]
@sinomoe pls help to check this issue

**Comment by JohnJyong** [comment]
it has fixed by below pr : https://github.com/langgenius/dify/pull/4431

**Comment by xiaohai-78** [comment]
> it has fixed by below pr : #4431它已修复以下 PR ： #4431

When will this bug be fixed and deployed?
