### ISSUE TITLE
使用 embed.min.js 嵌入ifarme中的页面，无法显示开场问题，如果基于当前页面的内容问答，如何从父页面传递参数到ifarme，无法操作子页面的dom元素，会有跨域的问题，打开新页面的方式运行的网页，无法隐藏工作流的展示步骤，

### ISSUE THREAD

**Issue by lbl1120** [langgenius/dify#4554]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

使用 embed.min.js 嵌入ifarme中的页面，无法显示开场问题，如果基于当前页面的内容问答，如何从父页面传递参数到ifarme，无法操作子页面的dom元素，会有跨域的问题，打开新页面的方式运行的网页，无法隐藏工作流的展示步骤，

### 2. Describe the feature you'd like to see

使用 embed.min.js 嵌入ifarme中的页面，无法显示开场问题，如果基于当前页面的内容问答，如何从父页面传递参数到ifarme，无法操作子页面的dom元素，会有跨域的问题，打开新页面的方式运行的网页，无法隐藏工作流的展示步骤，

### 3. How will this feature improve your workflow or experience?

使用 embed.min.js 嵌入ifarme中的页面，无法显示开场问题，如果基于当前页面的内容问答，如何从父页面传递参数到ifarme，无法操作子页面的dom元素，会有跨域的问题，打开新页面的方式运行的网页，无法隐藏工作流的展示步骤，

### 4. Additional context or comments

![屏幕截图 2024-05-21 190414](https://github.com/langgenius/dify/assets/152936427/4e7dfd24-082b-4ff9-ad07-9319f4f2dc5c)
使用 embed.min.js 嵌入ifarme中的页面，无法显示开场问题，如果基于当前页面的内容问答，如何从父页面传递参数到ifarme，无法操作子页面的dom元素，会有跨域的问题，打开新页面的方式运行的网页，无法隐藏工作流的展示步骤，

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by newlxj** [comment]
跨域你用nginx拉到同一个域解决

**Comment by taowang1993** [comment]
请问如何使用embed.min.js，具体代码可以分享吗？iframe会暴露url
