### ISSUE TITLE
Built-in Tool for Converting PDFs and Images to Markdown

### ISSUE THREAD

**Issue by ztthu15** [langgenius/dify#4555]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

No, this request is not related to a specific challenge, but rather an enhancement to the current capabilities of Dify.

### 2. Describe the feature you'd like to see

A built-in tool in Dify that can convert PDFs and images to Markdown. This would allow users to easily convert their data into a format that can be readily used by NLP modules.

### 3. How will this feature improve your workflow or experience?

This feature will streamline the process of feeding data from PDFs and images into NLP modules, making it easier and more efficient to work with these types of data in Dify.

### 4. Additional context or comments

This service is provided by Intsig Corporation. More details can be found at [Intsig Corporation](https://www.textin.com/market/detail/pdf_to_markdown).

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by murtaza-motorwala** [comment]
I added a similar enhancement request - https://github.com/langgenius/dify/issues/4896
