### ISSUE TITLE
API url error if the port is modified to other ports in the nginx part in docker-compose.yaml

### ISSUE THREAD

**Issue by buptsad** [langgenius/dify#4558]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Change the port in line 391 docker-compose.yaml in dify/docker. 
2. docker compose it
3. Add a chat assistant
4. go to the api pannel. The api is shown without the port.
5. Try to access the url by adding the port to the host. It will jump to the one without port automatically.
6. The web page url published is also without port, but this can be accessed if port number is added to the host.

### ✔️ Expected Behavior

Have access to the api no matter how the port changes.

### ❌ Actual Behavior

Cannot access to the api if the port is changed to neither 443 nor 80.

**Comment by kuit123** [comment]
docker-compose.yml,needs to modify Api: environment variables APP_WEB_URL，SERVICE_API_URL，fill in 'http://ip:nginx-port'

**Comment by kuit123** [comment]
@buptsad
