### ISSUE TITLE
Node Google Search run failed: Failed to invoke tool: 'snippet'. (Results with no "snippet" not accounted for)

### ISSUE THREAD

**Issue by RobIreland91** [langgenius/dify#4560]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. In workflow, create a Google Search Node from the Built-in Tool section
2. Set result type to "text". Run a search query that returns a result that does not have a snippet (result preview). For example "What is the parent company of Perry Elliss Inc?"
![image](https://github.com/langgenius/dify/assets/129052970/57a19902-4e2c-481d-8987-a054afc5dab2)

3. Note the tool returns an error Failed to invoke tool: 'snippet'. 
![image](https://github.com/langgenius/dify/assets/129052970/877728ed-d2be-40ef-bee4-652597707db9)

 My assumption is that this is due to the SERP API response containing a result which is missing a snippet, as I can see from the Google UI.

![image](https://github.com/langgenius/dify/assets/129052970/744032ed-d780-4333-85b9-5bf9b006ec69)

Proposed solution is to parse the SERP API results explicitly, checking for the presence of a "snippet" key in each result dictionary and only attempting to collect the snippet if it exists. It seems the current method assumes a snippet for each result, which is correct most of the time but will throw this error in some cases.

### ✔️ Expected Behavior

The concatenated snippets and links from each result are returned. In the case of a result with no snippet, only the link is included in the output.

### ❌ Actual Behavior

An error is returned, assuming because the tool was expecting a snippet key in the result dictionary within "organic_results". And the rare scenario where a result has no snippet was not accounted for.

**Comment by hjlarry** [comment]
I debug this issue and will make a PR later.

![20240522102705](https://github.com/langgenius/dify/assets/25834719/6a4c64b1-7d90-4335-a30d-d32535fc03dd)

**Comment by RobIreland91** [comment]
Thank you
