### ISSUE TITLE
RAG stuck in embedding with status 'indexing' when using Segmenting in Q&A Format

### ISSUE THREAD

**Issue by jafrank88** [langgenius/dify#4564]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Find 1000 files. Try to embed them when using "Segmenting in Question & Answer format". There is no way to tell when the process is complete, but when checking the log, it appears that some files get stuck with the status of 'indexing', rather than 'available'. See generally, https://discord.com/channels/1082486657678311454/1237858420351041576

### ✔️ Expected Behavior

All embedded RAG to be 'available' or to have a way to restart the process to fix those stuck in indexing status.

### ❌ Actual Behavior

All files 'available' after embedding.

**Comment by jafrank88** [comment]
Here is an example of the problem without Q-and-A embedding,
![image](https://github.com/langgenius/dify/assets/91024347/eac41c8f-6adb-4e0d-8e00-36242b6d4ccf)

**Comment by GitDakky** [comment]
Hi - I am having a similar problem, not exactly the same as mentioned above but when trying to index 499 OCR pdf docs. Dify attempts to index but we get an error. When clicking on any of the docs with the error message, one can see that the processes has been attempted as there are example chunks from the document. It is not clear what the error is. Here are the settings being used.
![image](https://github.com/langgenius/dify/assets/106489879/a15b7c3c-7082-46f8-a4c5-1133389f75c9)

**Comment by crazywoola** [comment]
Can you provide the logs of the container?

**Comment by GitDakky** [comment]
@crazywoola unfortunately not. My IT man is off and I don't hold server credentials. I am 99% sure that all docs are OCR searchable, but have you run in to issues where users have uploaded docs that have no text? How does Dify deal with these? Just skip them?

**Comment by jafrank88** [comment]
I posted my logs here and can provide more as needed - https://discord.com/channels/1082486657678311454/1237858420351041576

**Comment by GitDakky** [comment]
now its not liking docx - restarting server.
![image](https://github.com/langgenius/dify/assets/106489879/993c49ca-b99c-469d-8195-5b232c632e60)

**Comment by GitDakky** [comment]
Just a theory! OpenAI invalidated the API key we were using and I set up a new key under a project. The API key uses an updated structure using a brrivation to the project name: Eg : sk-difi-XXXXXXXXXXetc...

We updated the Key in the only place available, but I do recall needing to provide an API key sevral times for various OAI models during the setup. Is it possible that:
a) The new key is not being used by the various OAI models
b) The format of the new OAI key is conflicting with a validation check in the code?

![image](https://github.com/langgenius/dify/assets/106489879/3be810cc-e300-4151-9571-c6d1c553ce95)

**Comment by GitDakky** [comment]
I ran again using ada-002 and it indexed. Something up with text-embeddings-3-large - My guess is it is related to the new API key.

OK - I am outta here

**Comment by jafrank88** [comment]
I am running everything locally.

**Comment by jafrank88** [comment]
I am not seeing any text chunks after embedding using Q&A segmentation. Is it possible that feature is broken? When I turn it off and embed files, I can see the chunks and can retrieve them. I am not sure if Q&A is the issue or the way it sends the content to the embedding API is the issue.

**Comment by GitDakky** [comment]
Any update on this?

**Comment by ouyang-yuxuan** [comment]
> 使用 Q&A 分段嵌入后，我没有看到任何文本块。该功能是否有可能被破坏？当我关闭它并嵌入文件时，我可以看到块并可以检索它们。我不确定是问答是问题还是将内容发送到嵌入 API 的方式是问题。

我也是相同的问题Q&A无法使用，看日志也没有报错

**Comment by supuwoerc** [comment]
@dosu Does splitting indicate that embedding is being performed? My document processing progress has been 0 but index_status changed from waiting to splitting, I checked the logs of the worker in docker and there is no error and it shows Start process document: d77c40d1-4120-411a-8a4d- 6ea8520c0bca

**Comment by supuwoerc** [comment]
> @dosu Does splitting indicate that embedding is being performed? My document processing progress has been 0 but index_status changed from waiting to splitting, I checked the logs of the worker in docker and there is no error and it shows Start process document: d77c40d1-4120-411a-8a4d- 6ea8520c0bca

My problem was solved, it turned out to be just text-embedding-ada-002 processing was too slow, I was going to go to discord for help, when after pouring a glass of water, I found that the progress still started to change ....🤣
