### ISSUE TITLE
It is expected that Dify will support some open-source embedding and reranking models.

### ISSUE THREAD

**Issue by wencan** [langgenius/dify#4582]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Chinese users will be able to use the full range of RAG functionality on Dify.

### 2. Describe the feature you'd like to see

It is expected that Dify will support some open-source embedding and reranking models.

I am a Chinese user. On Dify, there is no suitable reranking model available for me to choose from.However, I learned from https://github.com/netease-youdao/QAnything that there are some excellent open-source embedding and reranking models.Can Dify support these models?

### 3. How will this feature improve your workflow or experience?

Chinese users will be able to use the full range of RAG functionality on Dify.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by takatost** [comment]
You can deploy local embedding/reranking models using xinference/LocalAI/OpenLLM.

**Comment by wencan** [comment]
@takatost 
Yes. 
Xinference works very well!
