### ISSUE TITLE
api smtp error

### ISSUE THREAD

**Issue by pt-cc** [langgenius/dify#4587]
### Self Checks

- [ ] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [ ] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [ ] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

https://github.com/langgenius/dify/blame/0.6.8/api/libs/smtp.py
```
cat libs/smtp.py
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


class SMTPClient:
    def __init__(self, server: str, port: int, username: str, password: str, _from: str, use_tls=False):
        self.server = server
        self.port = port
        self._from = _from
        self.username = username
        self.password = password
        self._use_tls = use_tls

    def send(self, mail: dict):
        smtp = smtplib.SMTP(self.server, self.port)
        if self._use_tls:
            smtp.starttls()
        if self.username and self.password:
            smtp.login(self.username, self.password)
        msg = MIMEMultipart()
        msg['Subject'] = mail['subject']
        msg['From'] = self._from
        msg['To'] = mail['to']
        msg.attach(MIMEText(mail['html'], 'html'))
        smtp.sendmail(self.username, mail['to'], msg.as_string())
        smtp.quit()
```
其中的
```
smtp.sendmail(self.username, mail['to'], msg.as_string())  代码有问题，应该是
smtp.sendmail(self._from, mail['to'], msg.as_string())
```

**Comment by crazywoola** [comment]
This has been fixed in main branch, please see https://github.com/langgenius/dify/blob/2eb468f8851802fd76a9d86899ce42ad90a0ed7a/api/libs/smtp.py#L31
