### ISSUE TITLE
Encountering an error with Azure's GPT-4o.

### ISSUE THREAD

**Issue by Mgrsc** [langgenius/dify#4593]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Using GPT-4o through the Azure channel.

### ✔️ Expected Behavior

Normal request

### ❌ Actual Behavior

When using Azure's gpt-4o model, an error occurred: Unknown parameter: 'stream_options'. When you address this issue, please be aware that the actual request format is in the style of OpenAI for Azure. You may encounter this when using one-api or new-api for Azure redirection.
![2024-05-22 223734](https://github.com/langgenius/dify/assets/118801216/c61712c7-9615-49fc-9889-6e6dbfc30cb7)

**Comment by dontbanmegithublol** [comment]
I encountered this problem today as well. It appears that Dify is using a new API, according to [this discussion](https://community.openai.com/t/usage-stats-now-available-when-using-streaming-with-the-chat-completions-api-or-completions-api/738156). However, the Azure API typically lags a bit and does not yet support the `stream_options` field. Here is the relevant [code](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-04-01-preview/inference.json).

Disabling the `stream_options` field should work, but I haven't tried it myself.

**Comment by dq7532183** [comment]
I must develop it in source code and delete this paragraph,I think this parameter can be used as a model configuration for users to choose whether to turn it on or off, rather than being written dead in the code.

Line 571 in api\core\model_runtime\model_providers\openai\llm.py 

        if stream:
            extra_model_kwargs['stream_options'] = {
                'include_usage': True
            }

**Comment by zhudongwork** [comment]
This is a bug that still exists; it is recommended to optimize！
