### ISSUE TITLE
希望可以自定义OpenAI的API接口

### ISSUE THREAD

**Issue by Aiayw** [langgenius/dify#46]
![image](https://github.com/langgenius/dify/assets/11790369/6a6a065f-068e-497f-89e3-8459e4b116a3)

这样可以支持在国内服务器部署或使用第三方代理商的接口，省去API的付费烦恼。

**Comment by takatost** [comment]
refer #41
已经有小伙伴提 pr 了

**Comment by Aiayw** [comment]
> refer #41 已经有小伙伴提 pr 了

收到，感谢~
