### ISSUE TITLE
Can the chat input box add file upload function, or add a plug-in for file reading

### ISSUE THREAD

**Issue by began-zhao** [langgenius/dify#4602]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Now the problem input box can not upload files (excel, csv, etc.), I hope to achieve the function of data analysis, the failure to upload files directly will lead to the analysis process is not smooth

### 2. Describe the feature you'd like to see

can upload and parse files to facilitate subsequent analysis

### 3. How will this feature improve your workflow or experience?

can upload files directly, and use the model to analyze the prompted words of the parsed files

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by godlzr** [comment]
is there a plan to support this function? It's really hard to add this custom function outside the Dify native RAG.

**Comment by crazywoola** [comment]
Yes we do.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/5346
