### ISSUE TITLE
支持语音输入

### ISSUE THREAD

**Issue by liduang** [langgenius/dify#4608]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

语音输入

### 2. Describe the feature you'd like to see

语音输入

### 3. How will this feature improve your workflow or experience?

语音输入

### 4. Additional context or comments

语音输入

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by zhangever** [comment]
这个本来就支持的吧？ 
![image](https://github.com/langgenius/dify/assets/2963615/010540ee-0bcb-4b64-b1b1-b912f1722fd0)
