### ISSUE TITLE
Sandbox doesn't support 3rd party python module

### ISSUE THREAD

**Issue by zhangever** [langgenius/dify#4612]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. add modul to docker/volumes/sandbox/dependencies/python-requirements.txt:
tiktoken~=0.6.0 
2. restart sandbox container, and verify that tiktoken is installed:
```
# pip list | grep tiktoken                                                                                                      
tiktoken           0.6.0
```
3. add a new codeNode to a workflow, with the following script:
```
import tiktoken
def main(arg1: str) -> dict:
    // import tiktoken
    encoding = tiktoken.get_encoding("cl100k_base")

    return {
        "result": len(encoding.encode(arg1))
    }
```
4. Run the node, it failed:
![image](https://github.com/langgenius/dify/assets/2963615/7a322e52-51e4-4408-a0b9-8f9d4477e736)

### ✔️ Expected Behavior

the code should be run and returns the length of the input text.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/2963615/11c199ae-7d58-47f0-a017-a8d9eec98032)

**Comment by zhangever** [comment]
> To resolve the issue where the `tiktoken` module is not recognized in your self-hosted Dify version 0.6.8 running on Docker, follow these steps:
> 
> 1. **Update `requirements.txt`:**
>    Ensure that the `tiktoken` module is listed in the `requirements.txt` file with the correct version. Update it to:
>    ```
>    tiktoken~=0.7.0
>    ```
> 2. **Rebuild Docker Image:**
>    After updating the `requirements.txt` file, rebuild your Docker image to ensure all dependencies are correctly installed. Run the following commands:
>    ```shell
>    docker-compose down
>    docker-compose build
>    docker-compose up -d
>    ```
> 3. **Verify Installation:**
>    Verify that the `tiktoken` module is installed in the sandbox environment:
>    ```shell
>    docker exec -it <sandbox_container_id> pip list | grep tiktoken
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace `<sandbox_container_id>` with the actual container ID of your sandbox environment.
> 4. **Check Environment Variables:**
>    Ensure that the `CODE_EXECUTION_ENDPOINT` and `CODE_EXECUTION_API_KEY` environment variables are correctly set, as these are crucial for the code execution service to function properly.
> 5. **Debugging and Logging:**
>    If the issue persists, use print statements and exception handling in your script to debug and log any errors:
>    ```python
>    import tiktoken
>    def main(arg1: str) -> dict:
>        try:
>            encoding = tiktoken.get_encoding("cl100k_base")
>            return {
>                "result": len(encoding.encode(arg1))
>            }
>        except ModuleNotFoundError as e:
>            print("ModuleNotFoundError:", str(e))
>            return {"error": "ModuleNotFoundError"}
>        except Exception as e:
>            print("Error:", str(e))
>            return {"error": str(e)}
>    ```
> 
> By following these steps, you should be able to resolve the issue and ensure that the `tiktoken` module is recognized and the script runs successfully.
> 
> #### Details
> **Sources**
> 
> * [api/requirements.txt](https://github.com/langgenius/dify/blob/main/api/requirements.txt)
> * [api/core/helper/code_executor/code_executor.py](https://github.com/langgenius/dify/blob/main/api/core/helper/code_executor/code_executor.py)
> * [en/features/workflow/nodes/code.md](https://github.com/langgenius/dify-docs/blob/main/en/features/workflow/nodes/code.md)
> * [en/features/workflow/node/code.md](https://github.com/langgenius/dify-docs/blob/main/en/features/workflow/node/code.md)
> 
> 
> **About Dosu** This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> _To continue the conversation, mention @dosu._

I've update the tiktoken version to 0.7.0, but it still reports the same error.

**Comment by crazywoola** [comment]
Duplicate see this thread https://github.com/langgenius/dify/discussions/3580

**Comment by ismtlee** [comment]
you can install these third python packages by append  the module name into python-requirements.txt, which can be found under 'dify/docker/volumes/sandbox/dependencies'. Then don't forget to run the command 'docker compose down; docker compose up --build -d'. Good luck!

**Comment by huy302** [comment]
@ismtlee This is exactly what I was looking for, thank you

**Comment by LONGZaixiang** [comment]
if the module name written in  python-requirements.txt is not the same as "import module_name" , what should i do?
for example:  aliyun-log-python-sdk==0.9.2   in  python-requirements.txt .   need to  "import aliyun.log"
![image](https://github.com/user-attachments/assets/734c9590-5964-4171-a279-6191b1b8f069)
