### ISSUE TITLE
windows11环境的docker部署方式，设置管理后跳转到登录页，输入登录信息又跳转到设置管理员页面，如此反复，不能登录

### ISSUE THREAD

**Issue by CaptainDP** [langgenius/dify#4614]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

windows11环境的docker部署方式：
1、设置管理后跳转到登录页，输入登录信息又跳转到设置管理员页面，如此反复，不能登录
2、删除镜像重新安装也不行
3、是否网络或者端口问题？在哪里能看到服务端报错日志呢？

### ✔️ Expected Behavior

正常登录

### ❌ Actual Behavior

登录跳转到设置管理员页面，设置后在调到登录页。。。

**Comment by Bannerli** [comment]
我也碰到这个问题，同问。

**Comment by goldeneave** [comment]
> 我也碰到这个问题，同问。

解决了吗

**Comment by CaptainDP** [comment]
> > 我也碰到这个问题，同问。
> 
> 解决了吗

需要清理后重新安装：
rm -rf ./volumes/app ./volumes/db ./volumes/redis ./volumes/weaviate

**Comment by goldeneave** [comment]
> > > 我也碰到这个问题，同问。
> > 
> > 
> > 解决了吗
> 
> 需要清理后重新安装： rm -rf ./volumes/app ./volumes/db ./volumes/redis ./volumes/weaviate

解决了 非常感谢！

**Comment by nakroy** [comment]
> > > 我也碰到这个问题，同问。
> > 
> > 
> > 解决了吗
> 
> 需要清理后重新安装： rm -rf ./volumes/app ./volumes/db ./volumes/redis ./volumes/weaviate
cd your_dify_dir
docker compose down
rm -rf ./volumes/app ./volumes/db ./volumes/redis ./volumes/weaviate
docker compose up -d
That works for me

**Comment by 1192603654** [comment]
The actual measurement is the front-end problem, the account key is missing when calling the interface, and it is OK to change the official docker startup

**Comment by ChengXiaotu** [comment]
那这样是不是只能用Docker启动，不能用源码启动了

> 实际测量是前端问题，调用接口时缺少账号密钥，改官方 docker 启动就可以了

**Comment by fanxingruocheng** [comment]
重装仍无法正常登录

**Comment by ZXHSunSalt** [comment]
我是将原来的dify目录重命名，新下了git文件，然后按照步骤重新走一遍，docker compose up -d很快就完成了，就不会出现这个问题了
