### ISSUE TITLE
执行”docker compose up -d“报/var/lib/postgresql/data/pgdata: Operation not permitted错误

### ISSUE THREAD

**Issue by ye-jeck** [langgenius/dify#4621]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

执行docker compose up -d

Data page checksums are disabled.

initdb: error: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
initdb: hint: If you want to create a new database system, either remove or empty the directory "/var/lib/postgresql/data/pgdata" or run initdb with an argument other than "/var/lib/postgresql/data/pgdata".
chmod: /var/lib/postgresql/data/pgdata: Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

### ✔️ Expected Behavior

希望能解决该错误
I hope this error can be resolved

### ❌ Actual Behavior

docker compose up -d

**Comment by lingaoan** [comment]
我也是这个错误，日志如下：
2024-06-17 11:53:11 fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... 2024-06-17T03:53:17.875129219Z The files belonging to this database system will be owned by user "postgres".
2024-06-17 11:53:17 This user must also own the server process.
2024-06-17 11:53:17 
2024-06-17 11:53:17 The database cluster will be initialized with locale "en_US.utf8".
2024-06-17 11:53:17 The default database encoding has accordingly been set to "UTF8".
2024-06-17 11:53:17 The default text search configuration will be set to "english".
2024-06-17 11:53:17 
2024-06-17 11:53:17 Data page checksums are disabled.
2024-06-17 11:53:17 
2024-06-17 11:53:17 fixing permissions on existing directory /var/lib/postgresql/data/pgdata ...
----------------------
@dosubot 按照你的操作尝试了以下，并重启docker service，还是一样的出现这个错误

**Comment by lingaoan** [comment]
问题已解决：
创建/home/<username>/volumes/db/data目录，并重新挂载即可

**Comment by StarDxxx** [comment]
The reason is you download the source code in your **Windows** system, but run docker in **wsl2**.
The correct opreation is:
- git clone in wsl2, not in windows
- docker pull
- dock compose

**Comment by Arcmoon-Hu** [comment]
> 问题已解决： 创建/home//volumes/db/data目录，并重新挂载即可

在wsl里，你这个才是正解

**Comment by KiraYoushikage** [comment]
I have found a new solution when using docker desktop in Window System

1.  create a volume where will exist in virtual machine, `docker volume create --name=pgdata`
2. replace with pgdata for your docker-compose.yaml
```
  services:
      db:
          image: postgres
          restart: unless-stopped
          env_file:
            - .env
          volumes:
            - pgdata:/var/lib/postgresql/data
          ports:
            - "5434:5432"
  volumes:
    pgdata:
      external: true
```

Reference from: https://github.com/docker-library/postgres/issues/558

**Comment by Tridu33** [comment]
> 问题已解决： 创建/home//volumes/db/data目录，并重新挂载即可

这个是wsl-ubuntu下touch还是compose.yml文件里面写命令？这里的挂载指的是重新docker compose up还是什么意思？

**Comment by Tridu33** [comment]
> The reason is you download the source code in your **Windows** system, but run docker in **wsl2**. The correct opreation is:
> 
> * git clone in wsl2, not in windows
> * docker pull
> * dock compose

合理，docker使用wsl2后端，【wsl环境的docker环境里面的程序】无权限访问【windows环境下载的dify文件夹】，重新在wsl下git就能拉起。

**Comment by mfjiang** [comment]
实际上在WSL2中这个问题我的解决方式：
修改compose文件中pg的volumes位置映射配置
   **volumes:
      - ./volumes/db/data:/home/{your path}/volumes/db/data**

```yaml
# The postgres database.
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      PGUSER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-???}
      POSTGRES_DB: ${POSTGRES_DB:-dify}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    command: >
      postgres -c 'max_connections=${POSTGRES_MAX_CONNECTIONS:-100}'
               -c 'shared_buffers=${POSTGRES_SHARED_BUFFERS:-128MB}'
               -c 'work_mem=${POSTGRES_WORK_MEM:-4MB}'
               -c 'maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-64MB}'
               -c 'effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-4096MB}'
    volumes:
      - ./volumes/db/data:/home/{your path}/volumes/db/data
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 1s
      timeout: 3s
      retries: 30
'''
