### ISSUE TITLE
将docker-compose.yaml配置中的地址改成了nginx的域名，访问报错404

### ISSUE THREAD

**Issue by dickpy** [langgenius/dify#4622]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

我修改了docker-compose.yaml中的配置，将api中的CONSOLE_WEB_URL、CONSOLE_API_URL、SERVICE_API_URL、APP_WEB_URL、FILES_URL以及web中的CONSOLE_API_URL、APP_API_URL都修改成了本机服务器的域名，https://xxx.cn/dify,启动服务后，请求dify，报错404
![微信图片_20240523192803](https://github.com/langgenius/dify/assets/38396890/31f80984-fff2-42d6-a071-6d99f6f7955f)

### ✔️ Expected Behavior

可以通过nginx的域名去访问dify

**Comment by FingerLiu** [comment]
this does not work due to this browser will try to find static files(_next/xxx  and *.css) from base url, and this make 404

**Comment by Davidwhw** [comment]
> this does not work due to this browser will try to find static files(_next/xxx and *.css) from base url, and this make 404

I also encountered this static files error, have you found a solution for it?
