### ISSUE TITLE
In the docker deployment method of Windows 11 environment, after setting up management, it jumps to the login page. After entering the login information, it jumps to the setting administrator page. This repeats and cannot log in.

### ISSUE THREAD

**Issue by CaptainDP** [langgenius/dify#4626]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Docker deployment method in windows11 environment:
1. After setting up the management, jump to the login page, enter the login information and then jump to the setting administrator page. Repeat this and you cannot log in.
2. Deleting the image and reinstalling it won’t work either.
3. Is there a network or port problem? Where can I see the server error log?

### ✔️ Expected Behavior

Log in normally

### ❌ Actual Behavior

Log in and jump to the administrator settings page. After setting, you will be redirected to the login page. . .

**Comment by crazywoola** [comment]
The data is persisted in `docker/volumnes` you should delete things under this folder. It should solve your problem, please be aware that the source code and.docker way share the same directory.
If you want to do a upgrade and is afraid of losing data, you can copy this folder as well.
