### ISSUE TITLE
重启docker后所有数据丢失

### ISSUE THREAD

**Issue by wu007kun** [langgenius/dify#4627]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

在win11上按照官方教程使用docker compose部署，第一次正常。重启电脑或重启docker后，发现有两个容器需要手动开启：docker-nginx-1和docker-ssrf_proxy-1。
同时，之前已经创建的账号和应用都清空了，访问localhost会从创建管理员账号这一步重新开始。
如何操作可以像普通软件一样数据持久化？

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by treblam** [comment]
@HiXiSi 想问下，你这个问题解决了吗？我最近遇到同样的问题。

**Comment by zybanss** [comment]
> [@HiXiSi](https://github.com/HiXiSi) 想问下，你这个问题解决了吗？我最近遇到同样的问题。

请问您解决了吗?看上去就是docker desktop开机自启的时候dify容器里有两个进程没有启动，重启一下dify容器就回来了。

**Comment by treblam** [comment]
我也解决了，好像是开机自启动时docker desktop要自动拉起WSL，但是WSL初始化有点慢导致某些docker容器启动失败了，后面开机后手动启动wsl，等一段时间再启动docker desktop好像就没问题了。
