### ISSUE TITLE
The simplest most game-changing feature to implement

### ISSUE THREAD

**Issue by vontainment** [langgenius/dify#4628]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Hey eyes don't know what time or date it is which can be very limiting.

### 2. Describe the feature you'd like to see

A default system variable that can be used in any of the prompts throughout Dify. Bots, agents and workflows that automatically outputs the exact date including the day of the week and the time as it is at the moment a message is sent through the api. It would allow us to create prompts that would make sure that I know is what time it is day of the week and date. This means it can look up recent articles online because it would know what date it is. I mean the uses are endless

### 3. How will this feature improve your workflow or experience?

Provide Endless Possibilities by allowing the AI to know when right now is

### 4. Additional context or comments

{{datetime}}

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by brightwang-igg** [comment]
You can set variables related to dates, and passing them when calling can also solve your problem.

**Comment by Asterovim** [comment]
> You can set variables related to dates, and passing them when calling can also solve your problem.

Yes but we can't put the dates via the chatbot interface (Web UI).

**Comment by brightwang-igg** [comment]
> > You can set variables related to dates, and passing them when calling can also solve your problem.您可以设置与日期相关的变量，在调用时传递它们也可以解决您的问题。
> 
> Yes but we can't put the dates via the chatbot interface (Web UI).是的，但我们无法通过聊天机器人界面（Web UI）输入日期。

Perhaps you can refer to this article. https://docs.dify.ai/features/ai-plugins/based-on-frontend-templates

**Comment by Asterovim** [comment]
> > > You can set variables related to dates, and passing them when calling can also solve your problem.您可以设置与日期相关的变量，在调用时传递它们也可以解决您的问题。
> > 
> > 
> > Yes but we can't put the dates via the chatbot interface (Web UI).是的，但我们无法通过聊天机器人界面（Web UI）输入日期。
> 
> Perhaps you can refer to this article. https://docs.dify.ai/features/ai-plugins/based-on-frontend-templates

Thanks you. can you provide an example with https://github.com/langgenius/webapp-conversation ? please

**Comment by vontainment** [comment]
Yeah but that is for the webapps. I'm meaning like a default system variable. {{datetime}} that can be set in the system prompt

**Comment by vontainment** [comment]
Example "It's {{datetime}}, act as my work assistant 9am to 5pm and my personal outside of that. As my work assistant...... as my personal....

**Comment by rainchen** [comment]
you can simply create a ChatFlow type chatbot to run a Code node before the LLM node to get the current date time, here is the example:

1. create a ChatFlow type chatbot to run a Code node before the LLM node 
<img width="773" alt="Screenshot 2024-06-04 at 11 23 29" src="https://github.com/langgenius/dify/assets/71397/75bd8811-0db0-4e1d-803d-17af6950f0ae">

2. run python script to get and return current date time

<img width="793" alt="Screenshot 2024-06-04 at 11 23 46" src="https://github.com/langgenius/dify/assets/71397/0ac60b18-2f3e-475a-b6c3-3eabf9baeaab">


3. use the Code node result in LLM node's system prompt:

<img width="949" alt="Screenshot 2024-06-04 at 11 24 00" src="https://github.com/langgenius/dify/assets/71397/06a7de3a-1258-436c-9702-7044ffed440f">

4. ask Bot about current date or time

<img width="698" alt="Screenshot 2024-06-04 at 11 29 24" src="https://github.com/langgenius/dify/assets/71397/00fd9829-5352-40c7-8c6f-5dc7257ee0ce">

**Comment by vontainment** [comment]
I'm more interested in using agents. that's where it would make a big difference. Also its easier to just tell it the time then to run python code to tell it the time lol. the point is for it to be temporally aware without having to tkae extra steps

**Comment by crazywoola** [comment]
Add this tool to the agent, and it will know what time is it. Just like you are bringing a watch with you.

<img width="399" alt="image" src="https://github.com/user-attachments/assets/81388460-609a-4a0f-a957-480d20df709b">
