### ISSUE TITLE
gpt-4模型调用参数不正确

### ISSUE THREAD

**Issue by harryhan1989** [langgenius/dify#4634]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[openai] Bad Request Error, Error code: 400 - {'error': {'message': 'Unrecognized request argument supplied: stream_options. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions. (request id: 2024052411424590132422884062136)', 'type': 'invalid_request_error', 'param': '', 'code': None}}

现在只有 gpt-4-0125-preview这个模型不报此错误

**Comment by harryhan1989** [comment]
请问你们可不可以编译一个临时解决此问题的docker，因为本地一直跟随你们官方docker升级，自己改这一行代码，下次升级又要变。或者你们添加一个临时的环境变量，可以在环境变量中配置关闭此选项。谢谢了

**Comment by crazywoola** [comment]
> 请问你们可不可以编译一个临时解决此问题的docker，因为本地一直跟随你们官方docker升级，自己改这一行代码，下次升级又要变。或者你们添加一个临时的环境变量，可以在环境变量中配置关闭此选项。谢谢了
Issue Close due to #1542 

Self checks 你已经勾选了

<img width="693" alt="image" src="https://github.com/langgenius/dify/assets/100913391/f4d5b226-2be2-425b-86f6-d4d377cfcf64">

**Comment by harryhan1989** [comment]
不勾选不行呀兄弟，语言是沟通的桥梁，能解决问题的人能理解，提问题的人能清楚就行，在意这些毫无意义，随处可见的翻译工具，我只是不想在国人发起的项目中用英语沟通而已

**Comment by NaMoCv** [comment]
> > 不勾选不行呀兄弟，中文或英文只是沟通的方式，能解决问题的人能理解，提问题的人能清楚就行，在意思这些毫无意义，随处可见的翻译工具。 给个docker用户临时的解决方法吧： 在docker的启动命令中添加上 ["sed","-i","s#extra_model_kwargs['stream_options']#test#g","core/model_runtime/model_providers/openai/llm/llm.py"]中文 命令，临时将stream_options参数去掉。 这个问题是要让azure的openai接口没有此参数，估计以后会有
> 
> 不是很懂在哪里加呢？官方一直不理会，也不去改这个bug

就是手动去掉api/core/model_runtime/model_providers/openai/llm/llm.py里设置stream_options的代码，如果是用docker compose的可以改了以后在直接挂载本地这个文件。
