### ISSUE TITLE
The application creation is completed and model debugging is possible. However, the created shared link cannot be accessed and a 404 "This page could not be found." message is displayed.

### ISSUE THREAD

**Issue by CaptainDP** [langgenius/dify#4635]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The application creation is completed and model debugging is possible. However, the created shared link cannot be accessed and a 404 "This page could not be found." message is displayed.

### ✔️ Expected Behavior

The shared link can be accessed normally

### ❌ Actual Behavior

404
This page could not be found.

**Comment by crazywoola** [comment]
Make sure you have turn the share function on & you have configured the right environments variables.
