### ISSUE TITLE
Have you considered supporting Tencent’s hunyuan model?

### ISSUE THREAD

**Issue by yumcc-com** [langgenius/dify#4639]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I want to create a low-cost application，I want to be able to use the Tencent’s Hunyuan-Lite in dify.

### 2. Describe the feature you'd like to see

Can choose to use Tencent’s Hunyuan-Lite.

### 3. How will this feature improve your workflow or experience?

Tencent’s Hunyuan-Lite version is free to call, which can help me reduce a lot of costs.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You could submit a PR for this if you like. :)

**Comment by xielong** [comment]
hi @crazywoola, 

I can start working on supporting the Hunyuan model next week.

**Comment by xielong** [comment]
I've already submitted a pull request for this requirement: [Pull Request #5013](https://github.com/langgenius/dify/pull/5013).

**Comment by crazywoola** [comment]
> I've already submitted a pull request for this requirement: [Pull Request #5013](https://github.com/langgenius/dify/pull/5013).

Hello @xielong Please add some tests to this provider as well.

**Comment by xielong** [comment]
> > I've already submitted a pull request for this requirement: [Pull Request #5013](https://github.com/langgenius/dify/pull/5013).
> 
> Hello @xielong Please add some tests to this provider as well.

Hi @crazywoola, the tests have been added to the provider.

**Comment by Luocy7** [comment]
please add poetry dependency to pyproject.toml 

```
poetry add tencentcloud-sdk-python-hunyuan
```

and i suggest  to use [poetry export plugins ](https://github.com/python-poetry/poetry-plugin-export) to generate requirements.txt. file from poetry
