### ISSUE TITLE
The MD5 function cannot be used to execute code

### ISSUE THREAD

**Issue by Geek-Bob** [langgenius/dify#4640]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

 CryptoJS.MD5(url).toString();

### ✔️ Expected Behavior

Code execution nodes, such as JS, can execute common functions, such as MD5. It is best to provide the import of custom package entry to improve the use of code nodes

### ❌ Actual Behavior

mistakeExecution code exception

**Comment by Geek-Bob** [comment]
The following methods can be used to run normally:
var crypto = require('crypto');
var md5 = crypto.createHash('md5');
But direct use:
`import CryptoJS from "crypto-js"; `
Importing the package and then `CryptoJS.MD5(' string to be encrypted ')` in the code will be abnormal
![image](https://github.com/langgenius/dify/assets/95834538/cd17464d-a096-4d40-a9d3-7bd16550b490)

**Comment by crazywoola** [comment]
Which version?

**Comment by Geek-Bob** [comment]
Okay, thank you.

**Comment by Geek-Bob** [comment]
> Which version? If you encounter this error, means it's not supported in our sandbox yet.

0.6.5
