### ISSUE TITLE
Parameter support for localstorage

### ISSUE THREAD

**Issue by xiaoxiaoliuzzZ** [langgenius/dify#4644]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I want to embed the dialogue into our own website. When I call the API of my website in the agent, a token will be passed in to the headers, Token can only be obtained after logging in. Can we add a feature to directly configure parameters from the browser's local storage?

### 2. Describe the feature you'd like to see

Directly configure parameters from the browser's local storage

### 3. How will this feature improve your workflow or experience?

Can be better utilized

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by thomaskral** [comment]
Any news on that feature? We would like to see such a feature, too.
Here is a related issue: #2841

**Comment by Amandine95** [comment]
> Any news on that feature? We would like to see such a feature, too. Here is a related issue: #2841

do you have a solution?
