### ISSUE TITLE
Chat workflow  API model,  the input parameters is lost when do a request!

### ISSUE THREAD

**Issue by rnthking** [langgenius/dify#4647]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

<img width="985" alt="image" src="https://github.com/langgenius/dify/assets/4058956/3281a117-4c3e-4395-b56c-9f1462608c55">

the input parameters "gpt4o" is lost as you can see on above screenshot

### ✔️ Expected Behavior

I can catch the parameter of input

### ❌ Actual Behavior

the "inputs parameter" is lost

**Comment by junonya** [comment]
@rnthking Please attach the workflow DSL file.

**Comment by rnthking** [comment]
I updated the lastest version, the problem is solved. @junonya  thx for your resp!
