### ISSUE TITLE
Response format for Gemini models is answering in json format with Vertex AI

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4649]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Use Gemini models and see response.
![CleanShot 2024-05-24 at 19 15 13](https://github.com/langgenius/dify/assets/119136210/56273f33-f61a-4f7c-870a-831049c24b31)

### ✔️ Expected Behavior

Normal response from Gemini models.

### ❌ Actual Behavior

Gemini 1.5 Flash and Pro answers back in json format.
Gemini 1.0 Vision gave error: [vertex_ai] Bad Request Error, 400 The input system_instruction is not supported.

**Comment by AndyMik90** [comment]
I also suggest setting HarmBlockThreshold to "BLOCK_ONLY_HIGH" as most will get "google.api_core.exceptions.InvalidArgument: 400 User has requested a restricted HarmBlockThreshold setting BLOCK_NONE."

**Comment by guchenhe** [comment]
`system_instruction` is a valid parameter according to Google's latest API doc: https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai.generative_models.GenerativeModel. I suspect its a server side bug, there's also a similar issue raised with the vertex AI's nodeJS SDK: https://github.com/googleapis/nodejs-vertexai/issues/350.

**Comment by hellof20** [comment]
#4971 remove Vertex AI gemini model default System Instructions prompt will fix this.
