### ISSUE TITLE
TTS is not enabled

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4651]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Press the audio button inside the feature panel in a workflow/chatflow
![CleanShot 2024-05-24 at 21 43 55](https://github.com/langgenius/dify/assets/119136210/285ed670-1012-4269-a5cb-2025ee65fe3b)

### ✔️ Expected Behavior

Response from TTS

### ❌ Actual Behavior

Error: TTS is not enabled

**Comment by crazywoola** [comment]
@AndyMik90 Hello this one is a little bit tricky here, if you change the voice or select a different tune, you will need to update first then you are able to hear the voice.

<img width="1919" alt="image" src="https://github.com/langgenius/dify/assets/100913391/103ad769-bde2-4330-92eb-7706be476453">

@charli117 and I have a discussion long time ago, and he is working on it these days.

**Comment by AndyMik90** [comment]
Thanls @crazywoola

**Comment by hwb96** [comment]
> @AndyMik90 Hello this one is a little bit tricky here, if you change the voice or select a different tune, you will need to update first then you are able to hear the voice.你好，这个在这里有点棘手，如果你改变声音或选择不同的曲调，你需要先更新，然后你才能听到声音。
> 
> <img alt="image" width="1919" src="https://private-user-images.githubusercontent.com/100913391/333769082-103ad769-bde2-4330-92eb-7706be476453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDE5OTEsIm5iZiI6MTcxOTI0MTY5MSwicGF0aCI6Ii8xMDA5MTMzOTEvMzMzNzY5MDgyLTEwM2FkNzY5LWJkZTItNDMzMC05MmViLTc3MDZiZTQ3NjQ1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNTA4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmM0OTBmNjU1OWU1OWY0YTNiNWUzYWQxNmEyZDJiNGYyYzQzYzRlMDI3ZDk5YWQ0ODk3YWY5YjAyOTk2MGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7OYPlbV0bMz-DNAGUFCKNx6k20cFBkc1dc7Pk-HjfhM">
> @charli117 and I had a discussion long time ago, and he is working on it these days.我很久以前就讨论过，他最近正在研究这个问题。
> 
> He created pr for this, see that pr link below.他为此创建了 pr，请参阅下面的 pr 链接。



> @AndyMik90 Hello this one is a little bit tricky here, if you change the voice or select a different tune, you will need to update first then you are able to hear the voice.
> 
> <img alt="image" width="1919" src="https://private-user-images.githubusercontent.com/100913391/333769082-103ad769-bde2-4330-92eb-7706be476453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDIyMjcsIm5iZiI6MTcxOTI0MTkyNywicGF0aCI6Ii8xMDA5MTMzOTEvMzMzNzY5MDgyLTEwM2FkNzY5LWJkZTItNDMzMC05MmViLTc3MDZiZTQ3NjQ1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNTEyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGIzMWIyYWY5NmNhMmEzYzdkNDZkMzBmNDBjNjg5MmQ3YjQwMmJmZmVjNDdkODY2ZTdmZDEzNzU2OTlhN2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HLD_6uplB7QwoKG7U-SSHtRiZ9Hn2fbDEhmelAYb4aU">
> @charli117 and I had a discussion long time ago, and he is working on it these days.
> 
> He created pr for this, see that pr link below.


This interaction logic is really confusing; I spent the entire afternoon trying to solve this problem. I kept thinking it was my fault, continuously modifying the code logic. It wasn’t until I saw the error message here that I realized.

**Comment by AndyMik90** [comment]
> > @AndyMik90 Hello this one is a little bit tricky here, if you change the voice or select a different tune, you will need to update first then you are able to hear the voice.你好，这个在这里有点棘手，如果你改变声音或选择不同的曲调，你需要先更新，然后你才能听到声音。
> > <img alt="image" width="1919" src="https://private-user-images.githubusercontent.com/100913391/333769082-103ad769-bde2-4330-92eb-7706be476453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDE5OTEsIm5iZiI6MTcxOTI0MTY5MSwicGF0aCI6Ii8xMDA5MTMzOTEvMzMzNzY5MDgyLTEwM2FkNzY5LWJkZTItNDMzMC05MmViLTc3MDZiZTQ3NjQ1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNTA4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmM0OTBmNjU1OWU1OWY0YTNiNWUzYWQxNmEyZDJiNGYyYzQzYzRlMDI3ZDk5YWQ0ODk3YWY5YjAyOTk2MGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7OYPlbV0bMz-DNAGUFCKNx6k20cFBkc1dc7Pk-HjfhM">
> > @charli117 and I had a discussion long time ago, and he is working on it these days.我很久以前就讨论过，他最近正在研究这个问题。
> > He created pr for this, see that pr link below.他为此创建了 pr，请参阅下面的 pr 链接。
> 
> > @AndyMik90 Hello this one is a little bit tricky here, if you change the voice or select a different tune, you will need to update first then you are able to hear the voice.
> > <img alt="image" width="1919" src="https://private-user-images.githubusercontent.com/100913391/333769082-103ad769-bde2-4330-92eb-7706be476453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDIyMjcsIm5iZiI6MTcxOTI0MTkyNywicGF0aCI6Ii8xMDA5MTMzOTEvMzMzNzY5MDgyLTEwM2FkNzY5LWJkZTItNDMzMC05MmViLTc3MDZiZTQ3NjQ1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNTEyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGIzMWIyYWY5NmNhMmEzYzdkNDZkMzBmNDBjNjg5MmQ3YjQwMmJmZmVjNDdkODY2ZTdmZDEzNzU2OTlhN2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HLD_6uplB7QwoKG7U-SSHtRiZ9Hn2fbDEhmelAYb4aU">
> > @charli117 and I had a discussion long time ago, and he is working on it these days.
> > He created pr for this, see that pr link below.
> 
> This interaction logic is really confusing; I spent the entire afternoon trying to solve this problem. I kept thinking it was my fault, continuously modifying the code logic. It wasn’t until I saw the error message here that I realized.

Ye, I'm hoping TTS is something that gets looked at when OpenAI releases their new API
