### ISSUE TITLE
Container docker-ssrf_proxy-1报错

### ISSUE THREAD

**Issue by JackHu1120** [langgenius/dify#4653]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

版本：0.6.8
在运行:docker compose -f docker-compose.middleware.yaml up -d报错
![image](https://github.com/langgenius/dify/assets/129717356/c69b8187-bd37-4397-9f21-25b242d459cb)

**Comment by o85757o** [comment]
i think you can copy the docker fold,and try again

**Comment by conglei1981** [comment]
好几个版本都有这个问题

2024/09/13 07:41:06| Configuring Parent sandbox
2024/09/13 07:41:06 pinger| Initialising ICMP pinger ...
2024/09/13 07:41:06 pinger| Open icmp_sock: (1) Operation not permitted
2024/09/13 07:41:06 pinger| ERROR: Unable to start ICMP pinger.
2024/09/13 07:41:06 pinger| Open icmp_sock: (1) Operation not permitted
2024/09/13 07:41:06 pinger| ERROR: Unable to start ICMPv6 pinger.
2024/09/13 07:41:06 pinger| FATAL: Unable to open any ICMP sockets.
2024/09/13 07:41:07| storeLateRelease: released 0 objects
2024/09/13 07:41:41| Recv recv: (111) Connection refused
2024/09/13 07:41:41| Closing Pinger socket on FD 15

**Comment by qyj19920704** [comment]
> 好几个版本都有这个问题
> 
> 2024/09/13 07:41:06| Configuring Parent sandbox2024/09/1307:41:06|配置父沙盒 2024/09/13 07:41:06 pinger| Initialising ICMP pinger ... 2024/09/1307:41:06 ping|初始化ICMP ping… 2024/09/13 07:41:06 pinger| Open icmp_sock: (1) Operation not permitted 2024/09/1307:41:06 pinger|打开icmp_sock：（1）不允许操作 2024/09/13 07:41:06 pinger| ERROR: Unable to start ICMP pinger. 2024/09/1307:41:06 ping|错误：无法启动ICMP ping。 2024/09/13 07:41:06 pinger| Open icmp_sock: (1) Operation not permitted 2024/09/1307:41:06 pinger|打开icmp_sock：（1）不允许操作 2024/09/13 07:41:06 pinger| ERROR: Unable to start ICMPv6 pinger. 2024/09/1307:41:06 ping|错误：无法启动ICMPv6 ping。 2024/09/13 07:41:06 pinger| FATAL: Unable to open any ICMP sockets. 2024/09/1307:41:06 ping|致命：无法打开任何ICMP插座。 2024/09/13 07:41:07| storeLateRelease: released 0 objects[ 重试    错误原因 ](javascript:void(0)) 2024/09/13 07:41:41| Recv recv: (111) Connection refused 2024/09/1307:41:41|Recv recv：（111）连接被拒绝 2024/09/13 07:41:41| Closing Pinger socket on FD 15 2024/09/1307:41:41|在FD 15上关闭Pinger插座

Have you solved it?

**Comment by wrchen-voxel** [comment]
> 2024/09/13 07:41:06| Configuring Parent sandbox
2024/09/13 07:41:06 pinger| Initialising ICMP pinger ...
2024/09/13 07:41:06 pinger| Open icmp_sock: (1) Operation not permitted
2024/09/13 07:41:06 pinger| ERROR: Unable to start ICMP pinger.
2024/09/13 07:41:06 pinger| Open icmp_sock: (1) Operation not permitted
2024/09/13 07:41:06 pinger| ERROR: Unable to start ICMPv6 pinger.
2024/09/13 07:41:06 pinger| FATAL: Unable to open any ICMP sockets.
2024/09/13 07:41:07| storeLateRelease: released 0 objects
2024/09/13 07:41:41| Recv recv: (111) Connection refused
2024/09/13 07:41:41| Closing Pinger socket on FD 15

I solved this problem by `docker pull ubuntu/squid:latest` and use this new container image. Maybe it works for you else.
