### ISSUE TITLE
wenxin's penalty_score range is incorrect

### ISSUE THREAD

**Issue by XiaoLey** [langgenius/dify#4657]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/46273173/82c66985-cde5-472b-9fb6-62a2ab344f75)

![image](https://github.com/langgenius/dify/assets/46273173/0b2c5148-082a-4984-9e18-2273d5622cb3)

**Comment by crazywoola** [comment]
Which one do you use.

https://github.com/langgenius/dify/blob/5becb4c43a42eb967801f42bb98a1882d76fa505/api/core/model_runtime/model_providers/wenxin/llm/ernie-speed-appbuilder.yaml#L21

You could check out this. And you can open a pr for this. :)

**Comment by XiaoLey** [comment]
> Which one do you use.
> 
> https://github.com/langgenius/dify/blob/5becb4c43a42eb967801f42bb98a1882d76fa505/api/core/model_runtime/model_providers/wenxin/llm/ernie-speed-appbuilder.yaml#L21
> 
> You could check out this. And you can open a pr for this. :)

Okay, I will conduct individual tests when I have time and provide the correct range values. I might make a pull request sometime this week.
