### ISSUE TITLE
About knowledge of dify

### ISSUE THREAD

**Issue by Yoshitaka-Nishimoto** [langgenius/dify#4658]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Dify's knowlege has the potential to promote the strengthening of its specialized field, but it could not be evaluated because the response process was not understood.

### 2. Describe the feature you'd like to see

No matter how dify's knowledge structures the data (id splitting) or rearranges it using rerank, I currently don't understand the process, and even just looking at the results, I can't understand it clearly. I'm an engineer, so I'd appreciate it if I could debug and trace the process.

### 3. How will this feature improve your workflow or experience?

If this function cannot be realized, Dify, although multifunctional,
It has low accuracy and may be considered unusable.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
@JohnJyong He is the lead engineer of this part. You can reach out to him on discord channel as well.  @jyongyeah
