### ISSUE TITLE
如何直接上传QA对信息，不需要大模型来帮我生成

### ISSUE THREAD

**Issue by 983183947** [langgenius/dify#4664]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

目前没有找到能直接导入QA对的地方。只有上传一个文件后，选择QA分段模式，但是此时我并不想通过大模型生成很多QA对。
<img width="1239" alt="image" src="https://github.com/langgenius/dify/assets/25240344/81edd29e-c258-4002-a916-4e6a9a3f0081">

**Comment by WalterZou** [comment]
The support of this function is needed. Currently, in many businesses, there is already a content library of QA pairs. There is no need for a large model to generate QA pairs. They can be directly uploaded to the knowledge base. Through Q, problems can be matched, and then the corresponding A can be handed over to the LLM as the query content of the knowledge base for processing.
