### ISSUE TITLE
The `latest` tag of dify-sandbox image is outdated

### ISSUE THREAD

**Issue by mrchi** [langgenius/dify#4672]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/16170578/82fe7573-980b-4427-9e6f-36533551f4ea)

### ✔️ Expected Behavior

keep the `latest` tag pointing to the latest image tag, now is `0.2.0`.

### ❌ Actual Behavior

the `latest` tag is not updated when `0.2.0` released.

**Comment by Yeuoly** [comment]
Oops, I will fix it

**Comment by Yeuoly** [comment]
fixed
