### ISSUE TITLE
Can I hide the workflow directory of the user's question and answer page?

### ISSUE THREAD

**Issue by liuxinxin2020** [langgenius/dify#4682]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

yes

### 2. Describe the feature you'd like to see

Hide the workflow directory on the page of user's question and answer.

### 3. How will this feature improve your workflow or experience?

Improve the user experience.

### 4. Additional context or comments

None

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by liuxinxin2020** [comment]
/
<img width="449" alt="image" src="https://github.com/langgenius/dify/assets/72063838/0ee8d18a-0797-443d-8b6d-4ae8275ac095">
![Uploading 000.png…]()

**Comment by wizd** [comment]
Sure it's a good idea to hide the loooong procedure which don't make much sense to users.
