### ISSUE TITLE
Error when using azure openai gpt4o with tool usage

### ISSUE THREAD

**Issue by AlexSu1108** [langgenius/dify#4686]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Preparation: 
1. set up the Azure openai gpt4o model in the model provider.
2. create an agent with a tool enabled (in my case, I use the 'current time' tool)

Reproduce:
chat with the agent using the function tool first, then upload a photo and ask about it.

### ✔️ Expected Behavior

The gpt4o model should be able to answer my question about this photo

### ❌ Actual Behavior

error message: [azure_openai] Bad Request Error, Error code: 400-{error:{'code: BadRequest, message: 'function' is not an allowed role. The allowed roles are [system, user, assistant], 'param':None, 'type': None}
![WechatIMG630](https://github.com/langgenius/dify/assets/143173584/1169c591-9428-4981-9750-682111f215d8)

**Comment by AlexSu1108** [comment]
update:
Although the release note of 0.6.9 mentioned the support of Azure OpenAI GPT4o, the same error was shown again.
<img width="1593" alt="image" src="https://github.com/langgenius/dify/assets/143173584/e26f9e85-d3c7-4724-ad53-329f8a3b35d0">

**Comment by ShaunXZ** [comment]
same problem here. any updates? I think it's caused by the Azure Dall-e 3 tool

**Comment by AlexSu1108** [comment]
> same problem here. any updates? I think it's caused by the Azure Dall-e 3 tool

No update. Other function tools also meet the same problem.
I think the problem is that, available 'roles' are restricted in dify. FUNCTION role is not included.

**Comment by sylar003** [comment]
The problem is still not solved

**Comment by laipz8200** [comment]
@ShaunXZ @AlexSu1108 @sylar003 Sorry for the wait. Could you please provide the `API version` configuration you're using?

**Comment by ShaunXZ** [comment]
> @ShaunXZ @AlexSu1108 @sylar003 Sorry for the wait. Could you please provide the `API version` configuration you're using?

We tried 2024-02-15-preview, 2024-03-01-preview, 2024-04-01-preview, 2024-05-01-preview, and all of them had the same issue.

**Comment by sylar003** [comment]
> @ShaunXZ @AlexSu1108 @sylar003 Sorry for the wait. Could you please provide the `API version` configuration you're using?对不起，久等了。您能否提供您正在使用的 `API version` 配置？

I used 2024-02-15-preview, thanks reply @laipz8200
