### ISSUE TITLE
工作流支持不同模块的并发执行和聚合

### ISSUE THREAD

**Issue by AInlpAbly** [langgenius/dify#4693]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

工作流中常常需要执行多个模型/知识库，某些操作是可以并发执行，从而降低整体耗时的

### 2. Describe the feature you'd like to see

工作流中支持多个组件的同步执行和结果聚合

### 3. How will this feature improve your workflow or experience?

提升agent整体的执行性能

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by jiewenshuaishuai** [comment]
我拉取了最新的docker镜像，然后本地部署，并不能并行创建两个节点
![image](https://github.com/langgenius/dify/assets/128024769/4c74fa22-1664-4ea9-8d87-d362590a3769)
