### ISSUE TITLE
When publishing workflow as tool, it does not show up in Tools

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4697]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

There seems to be an issue when publishing workflows as tools that they don't show up in the ProviderList:
![CleanShot 2024-05-27 at 20 31 40](https://github.com/langgenius/dify/assets/119136210/fa136b09-77ec-415d-a2a7-61e2e0403271)
But I can see them in the studio:
![CleanShot 2024-05-27 at 20 32 03](https://github.com/langgenius/dify/assets/119136210/ef881d89-af22-4a07-aa02-553e90807720)

### ✔️ Expected Behavior

Show workflow as tools, just as on cloud.

### ❌ Actual Behavior

Empty view. When adding debug to web/app/components/tools/provider-list.tsx there seem to be a mismatch between the 
useEffect for the active tab, and the Collection type
"Collection type: builtin Active tab: workflow"

**Comment by patryk20120** [comment]
Well, works for me. Try refresh and see the console logs (if any errors) - if not would be nice to see container logs (api).

**Comment by AndyMik90** [comment]
I don't know if it's related, but when I'm adding anything other then a builtin tool, the icon changes upon adding it:
![CleanShot 2024-05-27 at 23 55 26](https://github.com/langgenius/dify/assets/119136210/9d2e966f-7d3a-443c-9f94-cc9f158ebc77)
Then when I try access the "info and setting" for the tool, it just is in isLoading forever
![CleanShot 2024-05-27 at 23 58 01](https://github.com/langgenius/dify/assets/119136210/e7025431-2947-4469-9c43-ae567bf98d05)
It's no problem with builtin tools:
![CleanShot 2024-05-27 at 23 57 09](https://github.com/langgenius/dify/assets/119136210/cc7daa64-9759-469a-a712-77c90736a3e6)

I can see that the icon is correct in the DB.

**Comment by AndyMik90** [comment]
Found the error ,was something on my side.
