### ISSUE TITLE
Workflow: Wrong text for N-to-1 retrieval model select

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#4699]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

- Create a Chatflow/Workflow
- Add a Knowledge Retrieval block
- Click the N-to-1 retrieval select

### ✔️ Expected Behavior

I should see a select for the "N-to-1 retrieval select model" in the bottom, which is the model that decides which knowledge to query

### ❌ Actual Behavior

I see a select for the System Reasoning Model. I think we forgot to add a label and helper text for this view. We are reusing the ones from the workspace System Reasoning Model settings which are confusing.
![image](https://github.com/langgenius/dify/assets/11357019/cf9993d9-b8df-4347-ae27-69409e5bfd62)

**Comment by iamjoel** [comment]
@VincePotato Let’s see how we can optimize the description.
