### ISSUE TITLE
The Agent have two same Final answer

### ISSUE THREAD

**Issue by create-my** [langgenius/dify#4705]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/79892206/95852c52-b7e6-4f96-94d5-d87684153c62)
As the picture shows, the answer content has two identical answers, but the Agent output has only one. This phenomenon occurs many times.

### ✔️ Expected Behavior

The agent's answer should be unique, not the same answer twice.

### ❌ Actual Behavior

The Agent answers the same answer twice.

**Comment by crazywoola** [comment]
It should be a problem of model settings, not dify itself. Please double check your prompt and model settings.
