### ISSUE TITLE
Error when running local source code and setting OpenAI key

### ISSUE THREAD

**Issue by moom-en** [langgenius/dify#4708]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/35919845/75986496-3be2-40a8-b1c5-3096fd524c52)
![image](https://github.com/langgenius/dify/assets/35919845/2ec5286b-7662-48e7-ae77-cf24b029c4dc)
I have configured a proxy locally

**Comment by crazywoola** [comment]
This is a cors error, please check the  environment setting accordingly.

**Comment by moom-en** [comment]
> This is a cors error, please check the environment setting accordingly.

Are you sure this is the problem?

**Comment by moom-en** [comment]
> This is a cors error, please check the environment setting accordingly.

This error shows: network is unreachable
