### ISSUE TITLE
在LocalAI中增加的rerank模型不能被保存

### ISSUE THREAD

**Issue by czhcc** [langgenius/dify#4711]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

在LocalAI中添加了rerank的配置，点击保存后，没有被保存下来

**Comment by czhcc** [comment]
没有CredentialsValidateFailedError抛出，校验是通过的，只是保存后，rerank模型配置没有出现在LocalAI列表中

**Comment by currenttime** [comment]
Xinference部署rerank模型（bge-reranker-base）后也有同样的问题

**Comment by banianzr** [comment]
看上去好像是api router的问题，保存rerank模型时，localai接收到的请求是/rerank，但是localai例子里面提供的请求是/v1/rerank
![image](https://github.com/langgenius/dify/assets/5343481/531e4c57-e872-44e9-ab99-30f9518cdf1d)
