### ISSUE TITLE
Issue with the "Link Expiration Page" Displaying in Chinese Instead of Japanese

### ISSUE THREAD

**Issue by t-daisuke** [langgenius/dify#4712]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Utility with translation issue

Japan

### 🌐 Language affected

Japanese

### ❌ Actual phrase(s)

<img width="619" alt="スクリーンショット 2024-05-28 15 26 07" src="https://github.com/langgenius/dify/assets/50610194/1e6c13f1-a7be-4981-be97-d13faf19de83">

I selected Japanese from the language options in the top-right corner. However, the text remained in Chinese and did not change.Resolving this issue would make it easier for Japanese users to understand and use the system.

### ✔️ Expected phrase(s)

リンクの有効期限が切れています

### ℹ Why is the current translation wrong

This is because the words are in Chinese, which Japanese people cannot read. They cannot understand the meaning or the pronunciation.

**Comment by crazywoola** [comment]
<img width="1907" alt="image" src="https://github.com/langgenius/dify/assets/100913391/f015a83c-5907-4805-9a4b-82440d341856">
<img width="1904" alt="image" src="https://github.com/langgenius/dify/assets/100913391/d853dd99-53bf-4f0c-a2ee-a00688d2ed60">

I am trying to fix this problem you mentioned.  But it seems I can not reproduce the problem.
