### ISSUE TITLE
Error when running local source code and setting OpenAI key

### ISSUE THREAD

**Issue by moom-en** [langgenius/dify#4714]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/35919845/4b768239-702e-4a70-b19c-cc27c12fc819)

**Comment by crazywoola** [comment]
<img width="1296" alt="image" src="https://github.com/langgenius/dify/assets/100913391/10eef9ac-dbdb-4c7f-b4c5-c04c68e7c2ac">
This is a general network problem, please search previous issue to resolve this.

**Comment by moom-en** [comment]
> <img alt="image" width="1296" src="https://private-user-images.githubusercontent.com/100913391/334300424-10eef9ac-dbdb-4c7f-b4c5-c04c68e7c2ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODA2NjMsIm5iZiI6MTcxNjg4MDM2MywicGF0aCI6Ii8xMDA5MTMzOTEvMzM0MzAwNDI0LTEwZWVmOWFjLWRiZGItNGM3Zi1iNGM1LWMwNGM2OGU3YzJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNzEyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDU2OWQxZWE0NDAyZDRiMjVkZTI2YzA3ZTZkNmI1YjkzOGExZDUxMjk1ZDU3ZjYxYzA3NzM5NjNjOWY0MmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HehMQUPiJb0Jy9VuEW3P2nWFbN-0XoQmhr-3tfRI898"> This is a general network problem, please search previous issue to resolve this.
> If you are behind a proxy, please set `HTTP_PROXY` and `HTTPS_PROXY` in `.env`.
> 
> https://docs.dify.ai/v/zh-hans/learn-more/faq/install-faq#id-18.-wei-shi-mo-xu-yao-ssrfproxy
> 
> https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/environments
> 
> ```
> HTTP_PROXY
> 
> HTTP 代理地址，用于解决国内无法访问 OpenAI、HuggingFace 的问题。注意，若代理部署在宿主机(例如http://127.0.0.1:7890)，此处代理地址应当和接入本地模型时一样，使用docker容器内部的宿主机地址（例如http://192.168.1.100:7890或http://172.17.0.1:7890）。
> 
> HTTPS_PROXY
> 
> HTTPS 代理地址，用于解决国内无法访问 OpenAI、HuggingFace 的问题。同上。
> ```

Thank you, it has been processed, but the document states that it is only valid when starting with docker image or docker-compose. I thought that my local source code running was excluded.
