### ISSUE TITLE
Can't add model for api_key

### ISSUE THREAD

**Issue by weiyi88** [langgenius/dify#4725]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.69

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

i Can't add model by this error 
![image](https://github.com/langgenius/dify/assets/32037147/f81a7f13-eb75-458a-984e-0bf48b2dd88d)
please tell how to add model by api_key ,and how to fix

### ✔️ Expected Behavior

1

### ❌ Actual Behavior

1

**Comment by crazywoola** [comment]
Please provide the container logs as well.

**Comment by weiyi88** [comment]
how to get the log , docker container have 8  , i don't which one logs

**Comment by crazywoola** [comment]
This log should be in the api I think.
