### ISSUE TITLE
Public URL using domain not working

### ISSUE THREAD

**Issue by MyNameIsOka** [langgenius/dify#4728]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- deploy v0.6.9 to an AWS Lightsail instance and attach a domain to that instance.
- get the public URL (below screenshot) and replace `localhost` with the domain, e.g. `example.com`
![Screenshot 2024-05-28 at 17 35 34](https://github.com/langgenius/dify/assets/18796117/0dd74251-a7d8-41eb-9336-d1dc17a2e75e)

### ✔️ Expected Behavior

The chatbot is shown

### ❌ Actual Behavior

The chatbot doesn't show.
The page just shows `App unavailable`.

**Comment by crazywoola** [comment]
See the bot's reply, please set the env vars in `docker-compose.yaml`.

**Comment by emcgarcia101** [comment]
We just need to point the URL without any ports? The documentaion about using public URL is confusing....
