### ISSUE TITLE
TTS api 无法正常调用 文档不全

### ISSUE THREAD

**Issue by BoyYangzai** [langgenius/dify#4758]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

我这边试图使用 流式tts 的效果 没想到 tts 接口无法调用成功
1.TTS api 的 curl 无法执行 少个括号 
正确填写也无法调用成功  响应error code 同下 - fetch
2. 以下这是我调用官方示例的前端 fetch 代码
import { fetchEventSource } from "@microsoft/fetch-event-source";

const useStreamTTs = () => {
  const speak = async (text: string) => {
    const formData = new FormData();
    formData.append("text", text);
    formData.append("user", "abc-123");
    formData.append("streaming", "true");
    formData.append("voice", "nova");
    await fetch(`http://127.0.0.1/v1/text-to-audio`, {
      method: "POST",
      headers: {
        Authorization: "Bearer app-IbduTKIDQLJHN1P5dZF90Vdb",
      },
      body: formData,
    });
  };

  return { speak };
};

export default useStreamTTs;

响应：
{
    "code": "unsupported_media_type",
    "message": "Did not attempt to load JSON data because the request Content-Type was not 'application/json'.",
    "status": 415
}

### ✔️ Expected Behavior

和 web app 中的请求一样 正常 work 
以下是我从 web app 扒下来的可以work的请求
fetch("http://127.0.0.1/api/text-to-audio", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en;q=0.9,zh;q=0.8,zh-CN;q=0.7",
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5MDE3ZTkyYi03NTNiLTRjMzctODE1NC1hMjdiNzhkNTMzYmQiLCJzdWIiOiJXZWIgQVBJIFBhc3Nwb3J0IiwiYXBwX2lkIjoiOTAxN2U5MmItNzUzYi00YzM3LTgxNTQtYTI3Yjc4ZDUzM2JkIiwiYXBwX2NvZGUiOiJDQ3pUcGZWMTRQcWVWaGd1IiwiZW5kX3VzZXJfaWQiOiIwNTdjOWI0Mi1hOGVhLTQzNDYtOTM0ZS02NjhmZDcwMWNkZGIifQ.ox_7DAyCWcwjkqvt4vmGbgBukna38I5acTvDev6dERY",
    "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryzRZijEGd57VrZVa2",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "http://127.0.0.1/chat/CCzTpfV14PqeVhgu",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "------WebKitFormBoundaryzRZijEGd57VrZVa2\r\nContent-Disposition: form-data; name=\"text\"\r\n\r\n喵喵喵\r\n------WebKitFormBoundaryzRZijEGd57VrZVa2\r\nContent-Disposition: form-data; name=\"voice\"\r\n\r\nnova\r\n------WebKitFormBoundaryzRZijEGd57VrZVa2--\r\n",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});

### ❌ Actual Behavior

请求失败 并且文档不全
{
    "code": "unsupported_media_type",
    "message": "Did not attempt to load JSON data because the request Content-Type was not 'application/json'.",
    "status": 415
}

**Comment by BoyYangzai** [comment]
> @BoyYangzai Hello there! I'm here to help you with any bugs, questions, or contributions you have for the project. Just tag me and I'll jump right in! 😊
> 
> To resolve the issue with the TTS API returning a 415 Unsupported Media Type error, you need to ensure that the `Content-Type` header is set correctly. The TTS API expects the `Content-Type` to be `application/json`.
> 
> Here is how you can modify your fetch code to set the correct `Content-Type`:
> 
> ```ts
> import { fetchEventSource } from "@microsoft/fetch-event-source";
> 
> const useStreamTTs = () => {
>   const speak = async (text: string) => {
>     const payload = {
>       text: text,
>       user: "abc-123",
>       streaming: true,
>       voice: "nova"
>     };
> 
>     await fetch('http://127.0.0.1/v1/text-to-audio', {
>       method: "POST",
>       headers: {
>         "Content-Type": "application/json",
>         Authorization: "Bearer app-IbduTKIDQLJHN1P5dZF90Vdb",
>       },
>       body: JSON.stringify(payload),
>     });
>   };
> 
>   return { speak };
> };
> 
> export default useStreamTTs;
> ```
> 
> Ensure that the `Content-Type` header is set to `application/json` and the request body is a JSON string. This should resolve the 415 Unsupported Media Type error [[1]](https://github.com/langgenius/dify/blob/main/web/service/base.ts).
> 
> #### Details
> **About Dosu** This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> _To continue the conversation, mention @dosu._
辛苦修改一下文档 但似乎新的问题出现了
![image](https://github.com/langgenius/dify/assets/94534613/5e3e01d6-5d71-4bd6-8664-0c2578c92183)

**Comment by BoyYangzai** [comment]
@crazywoola 哈咯 问题好像并没有结束
streaming 为 true 不能正常work code 500
streaming 为 false 可以正常返回音频文件
server 500 这块我私有部署之后并没有做任何操作 只是简单调用 tts api 
方便排查下具体原因吗
```ts
import { fetchEventSource } from "@microsoft/fetch-event-source";

const useStreamTTs = () => {
  const speak = async (text: string) => {
    const payload = {
      text: text,
      user: "abc-123",
      streaming: false,
      voice: "nova",
    };

    await fetch("http://127.0.0.1/v1/text-to-audio", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer app-IbduTKIDQLJHN1P5dZF90Vdb",
      },
      body: JSON.stringify(payload),
    });
  };

  return { speak };
};

export default useStreamTTs;
```

**Comment by iamfoolberg** [comment]
@BoyYangzai 请问你的TTS调用成功了吗？我想能否直接在
https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/tongyi/tts/tts.py
中，替换为调用自己的TTS引擎——比如GPTSovits，可以参考：https://blog.csdn.net/zcxey2911/article/details/137041031中所述方式。

**Comment by wuxiaolianggit** [comment]
@BoyYangzai @iamfoolberg @crazywoola @appleboy @tomoyuki28jp 请问一下大佬们，
 "code": "unsupported_media_type",
    "message": "Did not attempt to load JSON data because the request Content-Type was not 'application/json'.",
    "status": 415
这个问题解决了吗？我这边一直出现这个问题？不知道怎么解决？
