### ISSUE TITLE
suggest support the file upload function

### ISSUE THREAD

**Issue by wangr0031** [langgenius/dify#4761]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Now the problem input box can not upload files (excel, csv, etc.)

### 2. Describe the feature you'd like to see

can upload and parse files to facilitate subsequent analysis and the result format can be defined with myself.

### 3. How will this feature improve your workflow or experience?

after upload files, the LLM will analyze the files with defined prompts

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated
