### ISSUE TITLE
Increase the maximum length of the "paragraph" variable of the workflow input field.

### ISSUE THREAD

**Issue by nne998** [langgenius/dify#4770]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I need to input a very long article.

<img width="454" alt="image" src="https://github.com/langgenius/dify/assets/148901/f28c915e-5b8b-4b4d-96aa-6e9c7ee92120">

### 2. Describe the feature you'd like to see

Increase the maximum length of the "paragraph" variable in the workflow.

### 3. How will this feature improve your workflow or experience?

 maximum length of the "paragraph" variable in the workflow.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Change this value is easy, but how long do you need.

**Comment by nne998** [comment]
I think, it can have a default value, but it can be set to unlimited if needed.

**Comment by hjlarry** [comment]
I encountered the definition `PARAGRAPH_MAX_LENGTH = 1032 * 32` in the code, and I'm puzzled by the rationale behind this specific value. It might be more meaningful to align this with the token capacity of GPT-4, which is 128K tokens. 1 token ~= 4 chars in English, It would be `PARAGRAPH_MAX_LENGTH = 128000 * 4`

**Comment by kawataki-yoshika** [comment]
I am using Gemini 1.5 Pro in Japanese.
This model can handle up to 2 million tokens, but I am not certain of the maximum length in characters.
Therefore, it would be beneficial if `PARAGRAPH_MAX_LENGTH` could be unlimited or adjustable at dify startup.

**Comment by Sakura4036** [comment]
> I think, it can have a default value, but it can be set to unlimited if needed.

yes, I agree.  We need the larger maximum length of the "paragraph" variable  and 'text' variable of the workflow input field.

**Comment by Sakura4036** [comment]
We desperately need this feature, as soon as possible.

> Since a workflow can be published as a tool, we need a larger input field maximum length. I think this config should be customizable by admin user via Settings web UI or environment variable of deployment.
