### ISSUE TITLE
Handling Iteration Node Failures Without Stopping Entire Workflow

### ISSUE THREAD

**Issue by shelltea** [langgenius/dify#4785]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a workflow with an iteration node.
2. Introduce an error in one of the iterations to cause it to fail.
3. Observe the behavior of the entire workflow.

### ✔️ Expected Behavior

When an error occurs in a specific iteration, the entire workflow should not be blocked and subsequent iterations should continue to execute.

### ❌ Actual Behavior

Currently, if an iteration fails, the entire iteration process stops, and subsequent iterations do not execute.

Is there any configuration or setting that allows the iteration node to continue executing subsequent iterations even if one iteration fails?

**Comment by wizd** [comment]
IMHO every tool should have an exception handling connection point.
