### ISSUE TITLE
When using 4o and DALL-E, two images appear, and one of the images cannot be displayed.

### ISSUE THREAD

**Issue by qhkabuqiluo** [langgenius/dify#4789]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

First, create a sketch of the layout in a 40x40 grid.
![image](https://github.com/langgenius/dify/assets/18694839/d4849c8a-f626-4286-81ea-90414297aba0)

Then, use DALL-E to generate the image based on the sketch
![image](https://github.com/langgenius/dify/assets/18694839/0eb53505-04c4-468a-a11d-281edf261a70)
![image](https://github.com/langgenius/dify/assets/18694839/f6170748-9558-42f7-97ee-d3d989da15d4)

### ✔️ Expected Behavior

just one image

### ❌ Actual Behavior

two images appear, and one of the images cannot be displayed.

**Comment by qhkabuqiluo** [comment]
My DALL-E configuration allows for generating one image.
![image](https://github.com/langgenius/dify/assets/18694839/decf7973-1b6a-466f-90b9-59327c8a456a)

**Comment by qhkabuqiluo** [comment]
My DALL-E configuration allows for generating one image.

**Comment by crazywoola** [comment]
You need to use the proper prompt to format the result then you should be able to get the right result.
