### ISSUE TITLE
 Error with GLM-4 Model in Question Classifier Node

### ISSUE THREAD

**Issue by qwe4815124** [langgenius/dify#4790]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Access the workflow software on the Dify Cloud platform.
Select the Question Classifier node.
Configure the node to use the Zhipu GLM-4 model.
Execute the node.
<img width="1285" alt="image" src="https://github.com/langgenius/dify/assets/21254472/45b51bc3-422d-43e3-8e40-015cc23d1355">

### ✔️ Expected Behavior

The node should classify the input data correctly using the selected GLM-4 model without errors.

### ❌ Actual Behavior

The node fails with an error, as described above.

**Comment by crazywoola** [comment]
Please notice, you need to leave the system prompt blank and input those prompt in user instead.

**Comment by qwe4815124** [comment]
Thank you for your response. However, I would like to clarify that the Question Classifier node, as currently implemented on the Dify Cloud platform, only allows for the selection of the model and does not provide an option to input or modify the system prompt or any other settings directly. Here are the available settings for this node as per my last interaction:

Model selection (only configurable option)
Given this, could you please provide further guidance on how to address the error mentioned earlier? If there is a specific approach to configure these settings indirectly or if the platform UI needs an update to expose these options, please let me know.

**Comment by qwe4815124** [comment]
> Please notice, you need to leave the system prompt blank and input those prompt in user instead.

Thank you for your response. However, I would like to clarify that the Question Classifier node, as currently implemented on the Dify Cloud platform, only allows for the selection of the model and does not provide an option to input or modify the system prompt or any other settings directly. Here are the available settings for this node as per my last interaction:

Model selection (only configurable option)
Given this, could you please provide further guidance on how to address the error mentioned earlier? If there is a specific approach to configure these settings indirectly or if the platform UI needs an update to expose these options, please let me know.
