### ISSUE TITLE
工作流运行访问的链接错误

### ISSUE THREAD

**Issue by Sakura4036** [langgenius/dify#4793]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Linux服务器按照教程源码部署，docker启动容器指定同一docker network， 配置`web/.env.local`中的`API PREFIX`为`192.168.1.5`
2. 本地PC访问服务器`192.168.1.5:3000`，配置dify
3. 工作室中任意创建workflow工具，点击发布，点击运行
4. 页面跳转到运行workflow工具页面

### ✔️ Expected Behavior

1. 工作室中任意创建workflow工具，发布成功，运行测试成功
2. 点击发布-运行，跳转workflow运行界面成功，运行成功

### ❌ Actual Behavior

1. 工作室中任意创建workflow工具，发布成功，运行测试成功
![image](https://github.com/langgenius/dify/assets/42060616/c42fae30-7a56-4082-8126-2dc36a407e00)

2. 点击发布-运行，跳转workflow运行界面失败
![image](https://github.com/langgenius/dify/assets/42060616/83c73202-f80f-4b5d-ad9c-437b2298f6ec)

![image](https://github.com/langgenius/dify/assets/42060616/f636d3f1-1d2f-47ef-8aca-66d96bfad22a)

3. 手动修改跳转链接为`192.168.1.5:3000`， 访问workflow运行界面成功
![image](https://github.com/langgenius/dify/assets/42060616/72f15e89-7893-443f-833e-972ba05a6bbb)

为什么会跳转到`127.0.0.1:4000`？而不是`192.168.1.5:3000`或者`127.0.0.1:3000`.  

是不是还有哪里没有配置正确？

**Comment by Sakura4036** [comment]
但是我的flask启动端口是`5001`，这意味着我的API URL是`http://192.168.1.5:5001`,因此我在docker-compose.yml中配置为
```
CONSOLE_API_URL: 'http://192.168.1.5:5001'
APP_API_URL: 'http://192.168.1.5:5001'
NEXT_PUBLIC_DEPLOY_ENV: 'DEVELOPMENT'
NEXT_PUBLIC_EDITION: 'SELF_HOSTED'
NEXT_PUBLIC_API_PREFIX: 'http://192.168.1.5:5001/console/api'
NEXT_PUBLIC_PUBLIC_API_PREFIX: 'http://192.168.1.5:5001/api'
```
在web/.env.local中配置为：
```
# For production release, change this to PRODUCTION
NEXT_PUBLIC_DEPLOY_ENV=DEVELOPMENT
# The deployment edition, SELF_HOSTED
NEXT_PUBLIC_EDITION=SELF_HOSTED
# The base URL of console application, refers to the Console base URL of WEB service if console domain is
# different from api or web app domain.
# example: http://cloud.dify.ai/console/api
NEXT_PUBLIC_API_PREFIX=http://localhost:5001/console/api
# The URL for Web APP, refers to the Web App base URL of WEB service if web app domain is different from
# console or api domain.
# example: http://udify.app/api
NEXT_PUBLIC_PUBLIC_API_PREFIX=http://localhost:5001/api
```

**Comment by Mxk-1** [comment]
我的dify启动在服务器，但是我通过本地访问<服务器地址>/install
总是报错跨域问题，请问这种应该如何设置呢？比如我本地局域网服务器地址为192.168.2.xxx
