### ISSUE TITLE
Will 工作流编排对话型应用 API compatible with OpenAI's API?

### ISSUE THREAD

**Issue by zhanghuanhuanlive** [langgenius/dify#4799]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yep

### 2. Describe the feature you'd like to see

Will 工作流编排对话型应用 API compatible with OpenAI's API?

### 3. How will this feature improve your workflow or experience?

Other platforms provide this compatibility, allowing me to implement business logic using a specific programming language and code without the need to develop separate code for this API.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by zhanghuanhuanlive** [comment]
Can't we discuss this issue?
The reason why everyone is now aligning with OpenAI's API is to make their work easier and simpler. As an open platform, we shouldn't let work become complicated or difficult because of technical or other reasons.

**Comment by edisonzf2020** [comment]
Cool work,
Same question, can this be compatible with OpenAI's API?
