### ISSUE TITLE
阿里云部署问题

### ISSUE THREAD

**Issue by shuhongwu** [langgenius/dify#48]
请问如果是阿里云，实例，该如何修改这份文件: https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml

尝试了一下，在阿里云的部署，访问一直失败，但是docker里面启动日志都是成功的

**Comment by takatost** [comment]
可以测试下在服务器 curl 是否能访问：
```
curl -H "Host: <your-domain>" http://127.0.0.1/console/api/apps
```

正常应该返回 401 没有授权的信息

**Comment by shuhongwu** [comment]
curl -H "Host:52.188.205.**" http://127.0.0.1/console/api/apps

返回:

{"code": "not_setup", "message": "Application not setup.", "status": 401}

**Comment by takatost** [comment]
> curl -H "Host:52.188.205.**" http://127.0.0.1/console/api/apps
> 
> 返回:
> 
> {"code": "not_setup", "message": "Application not setup.", "status": 401}

嗯，这是还未初始化安装的信息，也是对的，能访问通，那么基本可以确定是服务器到外部的网络问题，您可以自查一下

**Comment by shuhongwu** [comment]
再补充一下，换了一台服务器部署成功之后，设置了管理员，然后登录，一直重定向回 login页面
![20230516-180117](https://github.com/langgenius/dify/assets/674674/6eb2396b-5b23-4a51-9a6d-da9a80328dce)

**Comment by shuhongwu** [comment]
> 再补充一下，换了一台服务器部署成功之后，设置了管理员，然后登录，一直重定向回 login页面 ![20230516-180117](https://user-images.githubusercontent.com/674674/238608719-6eb2396b-5b23-4a51-9a6d-da9a80328dce.jpg)

怀疑不是我哪里配置没改呢？因为我是按照readme直接操作的，yaml文件没做任何修改

**Comment by takatost** [comment]
https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq
可以看下这边的 FAQ，看截图猜测可能是域名变化导致的，默认的配置只适用于 localhost，换了地址需要更换配置中所有的域名，以及 nginx 中的配置。
这边配置我再优化一下，可以适应任何同域的吧

**Comment by takatost** [comment]
已优化默认配置，可拉一下最新代码，并拉取最新 `dify-api` 镜像重新部署一下，域名配置已宽松处理：
```
git pull
docker pull langgenius/dify-api:latest
```

**Comment by hwiwang** [comment]
请问默认域名修改哪个变量？env中好几个URL，都写上留空则为默认域名，但留空后dify系统的通知邮件发出后URL不全
