### ISSUE TITLE
docker search langgenius/base:1.0.0-bullseye-slim

### ISSUE THREAD

**Issue by HeroBarry** [langgenius/dify#480]
没有搜索到呢，这个里面是什么 就是python环境么？

**Comment by takatost** [comment]
Image here: https://hub.docker.com/layers/langgenius/base/1.0.1-bullseye-slim/images/sha256-0c1542a82e160ab55b28f3526e2fc0cc316e0e77a253deb1b4a09eb4f22181ad 
Dockerfile here: https://github.com/langgenius/dify/blob/main/docker/Dockerfile.base
