### ISSUE TITLE
Can't find the conversation history ({{#histories#}}) in the llm node

### ISSUE THREAD

**Issue by luzhouuu** [langgenius/dify#4801]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I read the document and found there was a **conversation history** variable in the llm node, but I can't find this variable in the latest version, have you delete the variable?
![image](https://github.com/langgenius/dify/assets/43746574/3fdd33c9-bc16-43eb-aab6-c4d538050f03)

**Comment by crazywoola** [comment]
Please use the write template to submit an issue and provide the details for better understanding.

**Comment by timur-nocodia** [comment]
How to accsess Conversation history variable?
![image](https://github.com/langgenius/dify/assets/120160081/b5a4f961-c2b9-432c-8920-10085760eb75)

**Comment by danialcheung** [comment]
> How to accsess Conversation history variable? ![image](https://private-user-images.githubusercontent.com/120160081/340340667-b5a4f961-c2b9-432c-8920-10085760eb75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDIxMTUsIm5iZiI6MTcxOTIwMTgxNSwicGF0aCI6Ii8xMjAxNjAwODEvMzQwMzQwNjY3LWI1YTRmOTYxLWMyYjktNDMyYy04OTIwLTEwMDg1NzYwZWI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNDAzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQzNzY5ODhjMWRiNTU2OTViYmFhMzliMGNhNDhlMGEzZDkzN2I3ZjMxZWVmZDQzNTBjNjI2MzJiYTZlNDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.53hNMrLz2ZGKkQKyZ9Cj1YKExgSJiWEELBOQrEi3EAQ)

As the [documentation](https://docs.dify.ai/guides/workflow/node/llm) states, you'll need to opt for 'completion' mode for the 'Conversation History' variable block to appear. Have you set your model settings to Completion mode?
![image](https://github.com/langgenius/dify/assets/11480213/c8b07688-5477-4559-bb4b-4f4473cf5ad1)

**Comment by timur-nocodia** [comment]
> > How to accsess Conversation history variable? ![image](https://private-user-images.githubusercontent.com/120160081/340340667-b5a4f961-c2b9-432c-8920-10085760eb75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDIxMTUsIm5iZiI6MTcxOTIwMTgxNSwicGF0aCI6Ii8xMjAxNjAwODEvMzQwMzQwNjY3LWI1YTRmOTYxLWMyYjktNDMyYy04OTIwLTEwMDg1NzYwZWI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNDAzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQzNzY5ODhjMWRiNTU2OTViYmFhMzliMGNhNDhlMGEzZDkzN2I3ZjMxZWVmZDQzNTBjNjI2MzJiYTZlNDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.53hNMrLz2ZGKkQKyZ9Cj1YKExgSJiWEELBOQrEi3EAQ)
> 
> As the [documentation](https://docs.dify.ai/guides/workflow/node/llm) states, you'll need to opt for 'completion' mode for the 'Conversation History' variable block to appear. Have you set your model settings to Completion mode? ![image](https://private-user-images.githubusercontent.com/11480213/342198465-c8b07688-5477-4559-bb4b-4f4473cf5ad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDgzMDgsIm5iZiI6MTcxOTI0ODAwOCwicGF0aCI6Ii8xMTQ4MDIxMy8zNDIxOTg0NjUtYzhiMDc2ODgtNTQ3Ny00NTU5LWJiNGItNGY0NDczY2Y1YWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZjlhMDAwM2NkZGI4NzBhZTVhNmU5YzU0ZmQ0Mzg1Yjc2MWQyY2RlNzNlMTVkYWRkMzY5ODE2MzQ3ZTJlYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gb7smt5dN9IV0F260Q1MZJKOOBIzYtL-b8ClNU0MAzE)

I have no ideia how to do that, actually

**Comment by danialcheung** [comment]
@timur-nocodia It should be in the settings that can be found by clicking your icon located on the top-right of the dashboard. You can choose whether your model is in 'chat' or 'completion' mode when adding a [model provider](https://docs.dify.ai/guides/model-configuration). You can find out about how to do this in the rest of the [docs](https://docs.dify.ai/guides/model-configuration/new-provider).

**Comment by jiandanfeng** [comment]
@danialcheung How to set completion mode in qwen
![image](https://github.com/langgenius/dify/assets/24525960/e484ca8a-a6a0-4280-b725-52fc5e8c4e1d)
![image](https://github.com/langgenius/dify/assets/24525960/b9250306-c902-4d47-95d2-54042e4b91da)
