### ISSUE TITLE
when it does support databases?

### ISSUE THREAD

**Issue by njhouse365** [langgenius/dify#4805]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

when it does support databases?

### ✔️ Expected Behavior

when it does support databases?

### ❌ Actual Behavior

when it does support databases?

**Comment by crazywoola** [comment]
Please use the right template to submit a feature request. This template is bug only.
