### ISSUE TITLE
Prompt role types set

### ISSUE THREAD

**Issue by linliyuan** [langgenius/dify#4806]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When using LangChain, I can set different chat roles such as human, AI, and system, allowing multiple messages to work together. This makes it easier for OpenAI to clearly understand the meaning of my paragraphs. Currently, everything is included in a single human message, which seems to significantly reduce the effectiveness, as OpenAI cannot understand the prompts as well.

### 2. Describe the feature you'd like to see

Support set different chat roles
https://docs.dify.ai/v/zh-hans/guides/application-design/prompt-engineering/prompt-engineering-1/prompt-engineering-template

### 3. How will this feature improve your workflow or experience?

OpenAI cannot understand the prompts as well

### 4. Additional context or comments

I believe that Dify, as a competitor to LangChain, should also have the same functionality as an alternative. This would be an advantage.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
<img width="512" alt="image" src="https://github.com/langgenius/dify/assets/100913391/bc8dd7f5-49be-4c03-91a8-77c9f85a23c7">
We did support this actually.
