### ISSUE TITLE
Categorization of applications

### ISSUE THREAD

**Issue by yangzw586** [langgenius/dify#4807]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

It's hard to find management after creating more apps

### 2. Describe the feature you'd like to see

Applications in the workspace can be managed by category, searchable and queried, and displayed through the classification tree

### 3. How will this feature improve your workflow or experience?

After creating a lot of apps, it is difficult to find and manage, and I want to have a categorized group

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
What version do you use? We have implemented this feature already.

**Comment by crazywoola** [comment]
<img width="527" alt="image" src="https://github.com/langgenius/dify/assets/100913391/4df1ac38-3446-4be4-b281-b6ce209a6c7b">

**Comment by yangzw586** [comment]
I use 0.6.9.
It is currently in this state of direct enumeration
[cid:f58a9b03-4eef-456a-8cce-0cb7865666b1]
________________________________
发件人: crazywoola ***@***.***>
发送时间: 2024年5月30日 16:02
收件人: langgenius/dify ***@***.***>
抄送: yangzw586 ***@***.***>; Author ***@***.***>
主题: Re: [langgenius/dify] Categorization of applications (Issue #4807)


What version do you use? We have implemented this feature already.

―

**Comment by yangzw586** [comment]
It's not in the Studio tab, it's under the Explore page
