### ISSUE TITLE
What redis/celery is used for?

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#4825]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

redis is listed at https://docs.dify.ai/getting-started/install-self-hosted/environments as follows. But it's not clear what exactly redis is used for. For example, what "pub/sub during conversation" means? Where celery is used in Dify?

We want to know how much storage redis may take to decide whether we should use a separate 3rd party redis database or just put redis in the same EC2 as the main dify app. 

Thanks!

<img width="827" alt="Screenshot 2024-05-30 at 9 44 26 PM" src="https://github.com/langgenius/dify/assets/595772/e7b19dcd-49d6-418d-b4ab-6f282b8a6132">

**Comment by crazywoola** [comment]
Our workers is build upon redis to execute embedding tasks.
