### ISSUE TITLE
HTTP timeout issues

### ISSUE THREAD

**Issue by 139qaz6** [langgenius/dify#4826]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I use a code execution node to invoke an HTTP request, when the HTTP request takes too long, something like error: timeout error: signal: killed occurs。
![屏幕截图 2024-05-27 153354](https://github.com/langgenius/dify/assets/81690063/71bb510a-164d-4462-9af4-125de1694c48)
![屏幕截图 2024-05-31 094115](https://github.com/langgenius/dify/assets/81690063/3d05690c-1da9-4ccb-8f91-0c0656be13d6)
![屏幕截图 2024-05-31 094947](https://github.com/langgenius/dify/assets/81690063/b2242eb5-78c9-4eaa-adc4-5b20ad142a7b)

### ✔️ Expected Behavior

Please relax the timeout to avoid error: timeout error: signal: killed

### ❌ Actual Behavior

Timeout condition at code execution node

**Comment by 139qaz6** [comment]
Is it possible to stretch this timeout in the next upgrade version?

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/16d47923c33633aec9ce812ad85c4981c5bc6970/api/core/workflow/nodes/http_request/entities.py#L8

You can set this environment variable according to your needs.
