### ISSUE TITLE
run failed: error: operation not permitted

### ISSUE THREAD

**Issue by sunbopython** [langgenius/dify#4837]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

工作流中 运行代码执行模块的时候  有时候会报 run failed: error: operation not permitted
有大佬遇到这个问题吗 怎么解决的

### ✔️ Expected Behavior

大家是如何解决这个问题的？有大佬告知一下吗谢谢

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/21340635/cef7be71-e994-4e39-ad2b-7dd2c439315c)

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/discussions/3580

**Comment by chalvern** [comment]
@crazywoolala We also encountered the same error reporting and found that it might be returned by the docker-sandbox-1 (langgenius/dify-sandbox:0.2.1) service. Especially when the response time in the log is relatively long, it will appear：

```
[GIN] 2024/06/06 - 09:41:35 | 200 |   43.662857ms |      172.18.0.4 | POST     "/v1/sandbox/run"  // ok😄
[GIN] 2024/06/06 - 09:41:41 | 200 |   44.015436ms |      172.18.0.4 | POST     "/v1/sandbox/run"   // ok😄
[GIN] 2024/06/06 - 09:41:45 | 200 |  113.269529ms |      172.18.0.4 | POST     "/v1/sandbox/run"  // bad 😭
[GIN] 2024/06/06 - 09:44:52 | 200 |   47.213844ms |      172.18.0.4 | POST     "/v1/sandbox/run"   // ok😄
```

**Comment by evanchenhi** [comment]
I encountered the same problem

**Comment by evanchenhi** [comment]
> @crazywoolala We also encountered the same error reporting and found that it might be returned by the docker-sandbox-1 (langgenius/dify-sandbox:0.2.1) service. Especially when the response time in the log is relatively long, it will appear：
> 
> ```
> [GIN] 2024/06/06 - 09:41:35 | 200 |   43.662857ms |      172.18.0.4 | POST     "/v1/sandbox/run"  // ok😄
> [GIN] 2024/06/06 - 09:41:41 | 200 |   44.015436ms |      172.18.0.4 | POST     "/v1/sandbox/run"   // ok😄
> [GIN] 2024/06/06 - 09:41:45 | 200 |  113.269529ms |      172.18.0.4 | POST     "/v1/sandbox/run"  // bad 😭
> [GIN] 2024/06/06 - 09:44:52 | 200 |   47.213844ms |      172.18.0.4 | POST     "/v1/sandbox/run"   // ok😄
> ```

Exactly the same situation

**Comment by crazywoola** [comment]
We designed this node as a lightweight solution rather than a time consumption node. So if the request body is very long, this could happen. 

See this line: https://github.com/langgenius/dify/blob/2a0f03a5114c0d9ec8d2012234d2682f685d083b/api/core/helper/code_executor/code_executor.py#L24

**Comment by almassolarenrgi** [comment]
> > @crazywoolala We also encountered the same error reporting and found that it might be returned by the docker-sandbox-1 (langgenius/dify-sandbox:0.2.1) service. Especially when the response time in the log is relatively long, it will appear：
> > ```
> > [GIN] 2024/06/06 - 09:41:35 | 200 |   43.662857ms |      172.18.0.4 | POST     "/v1/sandbox/run"  // ok😄
> > [GIN] 2024/06/06 - 09:41:41 | 200 |   44.015436ms |      172.18.0.4 | POST     "/v1/sandbox/run"   // ok😄
> > [GIN] 2024/06/06 - 09:41:45 | 200 |  113.269529ms |      172.18.0.4 | POST     "/v1/sandbox/run"  // bad 😭
> > [GIN] 2024/06/06 - 09:44:52 | 200 |   47.213844ms |      172.18.0.4 | POST     "/v1/sandbox/run"   // ok😄
> > ```
> 
> Exactly the same situation
