### ISSUE TITLE
Can multiple bots be embedded in a floating window mode into third-party applications at the same time?

### ISSUE THREAD

**Issue by galenss** [langgenius/dify#4838]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

 I want to use multiple types of bots in an application, but currently, an application can only embed one bot. I don't know what to do.

### 2. Describe the feature you'd like to see

I want like that:
![Snipaste_2024-05-31_17-51-58](https://github.com/langgenius/dify/assets/140889055/7c5bda43-25d8-4986-a980-738c91982175)

### 3. How will this feature improve your workflow or experience?

 If so, I can create bots for different departments within the application to serve them.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
No, as far as I know, the icon is `position: fixed`.
