### ISSUE TITLE
Error running docker installation

### ISSUE THREAD

**Issue by chibexme** [langgenius/dify#4842]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker-compose up

### ✔️ Expected Behavior

Complete installation without error

### ❌ Actual Behavior

Creating network "defy-studio_default" with the default driver
Creating network "defy-studio_ssrf_proxy_network" with driver "bridge"
Creating defy-studio_ssrf_proxy_1 ... error
Creating defy-studio_sandbox_1    ... done
Creating defy-studio_web_1        ... 
Creating defy-studio_weaviate_1   ... 
Creating defy-studio_db_1         ... 
Creating defy-studio_redis_1      ... 

Creating defy-studio_web_1        ... done
Creating defy-studio_weaviate_1   ... done
Creating defy-studio_db_1         ... done
Creating defy-studio_redis_1      ... done
Creating defy-studio_api_1        ... done
Creating defy-studio_worker_1     ... done
Creating defy-studio_nginx_1      ... error

ERROR: for defy-studio_nginx_1  Cannot start service nginx: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/srv/users/john/defy-studio/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for ssrf_proxy  Cannot start service ssrf_proxy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/srv/users/john/defy-studio/volumes/ssrf_proxy/squid.conf" to rootfs at "/etc/squid/squid.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/srv/users/john/defy-studio/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by crazywoola** [comment]
This is a duplicate question.
Please make sure you have copied the whole docker directory instead of copying a single compose file.

**Comment by chibexme** [comment]
Thanks, working now, I copied only the docker-compose.yaml before.
