### ISSUE TITLE
HTTP Request with DELETE method errors in any way

### ISSUE THREAD

**Issue by th3n00b13** [langgenius/dify#4852]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Use HTTP Request with DELETE method on workflow.
![image](https://github.com/langgenius/dify/assets/57221812/9b90d01d-f5db-400e-8eff-d762411822cc)
Regardless of its status(this time, the URL will not work because it has not opened), it returns `Node (node-name) run failed: argument of type 'NoneType' is not iterable`.
This might relate to how http(or ssrfproxy) request handles DELETE inside source code, as only DELETE uses `requests` library with some polyfills while all other methods use `httpx`.

### ✔️ Expected Behavior

Should return a response, or corresponding error.

### ❌ Actual Behavior

Request is sent, but causes error regardless of response.

**Comment by crazywoola** [comment]
Regarding the ssrf proxy, you can disabled it by leaving these blank.
https://github.com/langgenius/dify/blob/a325a294bd4a3aca827fe5f693f2aa433a2b51fc/docker/docker-compose.yaml#L172-L173
