### ISSUE TITLE
Issue variable not working api workflow run 

### ISSUE THREAD

**Issue by TienLD-0801** [langgenius/dify#4857]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

The response variable is string but the api doesn't work when the variable is a volatile variable, but if passed hard it works. Please resolve the above issue !

<img width="517" alt="Screenshot 2024-06-01 at 22 34 53" src="https://github.com/langgenius/dify/assets/112608271/85d76ec2-c31e-44a6-99e4-91f1cd0a8996">
<img width="517" alt="Screenshot 2024-06-01 at 22 35 07" src="https://github.com/langgenius/dify/assets/112608271/ae4736b4-8e47-45f8-9007-64c8ce1c8eb9">

**Comment by crazywoola** [comment]
Hello, this service [https://demo4.ai.bnksolution.com/] is changing the logo of our product which violates our open source policy.  

You should contact our business@dify.ai **as soon as possible** to obtain our business license.

Our rights and interests are protected by Tianyuan Law Firm
