### ISSUE TITLE
希望我们的系统能集成进ChatTTS，让ai回复直接是语音

### ISSUE THREAD

**Issue by lonrencn** [langgenius/dify#4859]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

https://github.com/jianchang512/ChatTTS-ui         有api接口，有调用格式

### 2. Describe the feature you'd like to see

可以用配置文件，也可以单独使用http调用

### 3. How will this feature improve your workflow or experience?

可以用配置文件，也可以单独使用http调用

### 4. Additional context or comments

用户直接点击就可以听到语音回复，或者设置成自动播放语音对话的

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Close due to #1542
