### ISSUE TITLE
ERROR: manifest for docker.io/langgenius/dify-web:0.3.6 not foun

### ISSUE THREAD

**Issue by chenxingbao** [langgenius/dify#486]
环境: centos 7 
docker: Docker version 1.13.1, build 7d71120/1.13.1
docker-compose: docker-compose version 1.27.4, build 40524192
启动dify时报错：
[root@EagleOS docker]# docker-compose up -d
Pulling web (langgenius/dify-web:0.3.6)...
Trying to pull repository docker.io/langgenius/dify-web ... 
ERROR: manifest for docker.io/langgenius/dify-web:0.3.6 not found
请问这个要怎么处理

**Comment by takatost** [comment]
https://hub.docker.com/layers/langgenius/dify-web/0.3.6/images/sha256-4a6c1069a12bfd7b4ae70c335d12117401399e60873208fe006c40deea8d856e?context=explore
langgenius/dify-web:0.3.6 was already exists, Please check your network connection to DockerHub or verify if the system architecture is amd64/arm64.

**Comment by chenxingbao** [comment]
系统版本是Linux version 5.5.3-1.el7.elrepo.x86_64，是不是装不了？

**Comment by chenxingbao** [comment]
![image](https://github.com/langgenius/dify/assets/13250140/702f5dfc-6348-4136-8ac4-c9af1bbd7d6a)
我的网络是正常的
