### ISSUE TITLE
Strengthen security for embedded apps

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4874]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When embedding apps on different sites, the URL to the app is exposed on the client side trough the iframe.

### 2. Describe the feature you'd like to see

Since many like the simplisity of an iFrame embedding, I suggest creating some type of hash or generating the URL on the serverside that can be used in the source for the iFrame url. 

### 3. How will this feature improve your workflow or experience?

Remove the possibility for people to take chatbots/embedded apps and "steal" the URL to embed it on their own site or use a subscription that is not theirs.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I have forwarded this to our dev team. :)

**Comment by taowang1993** [comment]
> I have forwarded this to our dev team. :)

Are we going to have another embed option? like flowise's <flowise-fullchat> approach plus Allowed Domains.

In that way, we won't expose the url or api key.
