### ISSUE TITLE
Integration of Vanna.AI for Text-to-SQL Feature in Dify

### ISSUE THREAD

**Issue by luxmus** [langgenius/dify#4877]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, I am looking for a way to automate SQL writing and running in Dify.

### 2. Describe the feature you'd like to see

I would like to see an integration of Vanna.AI into Dify. Specifically, I am interested in a feature where I can input text and have Vanna.AI generate SQL queries for me.

### 3. How will this feature improve your workflow or experience?

This feature would significantly speed up the process of extracting insights from my database. Instead of manually writing SQL queries, I could simply ask questions in natural language and have Vanna.AI generate the queries for me.

### 4. Additional context or comments

None

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Where do you want to put it into? 
A node in workflow or a generic model runtime?

**Comment by luxmus** [comment]
builtin tool

**Comment by arthurjinhui** [comment]
Is it possible to use local LLMs and vector store without relying on online vanna.ai?
