### ISSUE TITLE
我手动创建的一个自定义工具，创建完成后这些信息存到了哪里？另外能否通过API方式创建自定义工具呢？

### ISSUE THREAD

**Issue by wangyao123456a** [langgenius/dify#4887]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1

### ✔️ Expected Behavior

1

### ❌ Actual Behavior

1

**Comment by crazywoola** [comment]
Close due to #1542
