### ISSUE TITLE
Add support for unstructured.io

### ISSUE THREAD

**Issue by murtaza-motorwala** [langgenius/dify#4896]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I was trying to extract the unstructured content using some APIs from unstructured.ai but could not do it successfully. I tried using the "HTTP request" node module but it does not take image as an input. Hence its frustrating to be not able to use a service.

### 2. Describe the feature you'd like to see

Either enhance the HTTP request module to accept Image as a form-data and pass it on to the next module or provide support for 3rd party services like [Unstructured API.](https://github.com/Unstructured-IO/unstructured-api?tab=readme-ov-file)

### 3. How will this feature improve your workflow or experience?

This will help build robust pipelines for OCR text extraction, NLP etc.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by dajianguo** [comment]
Is there a planned time for this？

**Comment by dajianguo** [comment]
Do you have an initial outcome? I plan to improve on this basis

**Comment by yufeiyohi** [comment]
please add UNSTRUCTURED_API_KEY in docker env, then I can use official unstructured services.
