### ISSUE TITLE
cannot exit from debug and preview view

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#4899]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

choose an agent the choose "debug as multiple models"
<img width="487" alt="Screenshot 2024-06-03 at 4 33 58 PM" src="https://github.com/langgenius/dify/assets/595772/1980b0b3-d4dc-4623-af26-5a9b2cd00063">

then, you should see
<img width="2550" alt="Screenshot 2024-06-03 at 4 32 34 PM" src="https://github.com/langgenius/dify/assets/595772/7a40252b-bd4a-4720-b252-14472f54b6e4">

I have no idea how to exit from this debug view. Please help.

### ✔️ Expected Behavior

can exit to the normal vew 

### ❌ Actual Behavior

cannot find how to exit.

**Comment by crazywoola** [comment]
<img width="1113" alt="image" src="https://github.com/langgenius/dify/assets/100913391/21b4c294-1fd1-401a-84ae-4e9d32afb4c7">
Just select which one you would like to remain.

**Comment by harrywang** [comment]
Thanks. I also figured this out - it's hard to find anyway ;).
<img width="1635" alt="Screenshot 2024-06-03 at 9 42 55 PM" src="https://github.com/langgenius/dify/assets/595772/8dc7f84c-32f1-4f9e-ae3c-a944b1f7ada5">
