### ISSUE TITLE
been stuck on the web page of “http://localhost:3000/install”

### ISSUE THREAD

**Issue by ViesLink** [langgenius/dify#4903]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

【Has tried many times, including re-pulling the image】
① https://hub.docker.com/r/langgenius/dify-web
② docker pull langgenius/dify-web
③ Run a new containers from the image on port 3006
④ http://localhost:3000/signin  and  click the "[Setting up an admin account](http://localhost:3006/install)"
⑤  stuck on the web page of “http://localhost:3000/install”

### ✔️ Expected Behavior

It can smoothly adjust to the configuration interface of the administrator account, complete the administrator registration and log in to the system

### ❌ Actual Behavior

Been going around in circles without any new tips
![Uploading 2024-06-04 085932.png…]()

**Comment by crazywoola** [comment]
Please provider container logs and check if you have setup the right env variables.

**Comment by NCZkevin** [comment]
I encountered  the same issue, are there any solutions available?

**Comment by leechs** [comment]
NEXT_PUBLIC_API_PREFIX=http://localhost:5001/console/api
NEXT_PUBLIC_PUBLIC_API_PREFIX=http://localhost:5001/api
I got the same issue. But it looks both variables look good to me...
