### ISSUE TITLE
An error occurred during credentials validation: HTTPConnectionPool(host='localhost', port=6337): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79235a8b7130>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by quzx** [langgenius/dify#4904]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

curl http://ip:7004/api/chat -d '{
"model": "qwen:32b-chat-v1.5-q5_K_M",
"messages": [
{
"role": "user",
"content": "hello"
}
]
}'
It works well.

When add ollama model provider from UI, i get "An error occurred during credentials validation: HTTPConnectionPool(host='localhost', port=6337): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79235a8b7130>: Failed to establish a new connection: [Errno 111] Connection refused'))"

But it work fine 5 days ago.

### ✔️ Expected Behavior

can add ollama

**Comment by crazywoola** [comment]
Duplicated. You are trying to access Ollama from docker container. In this case, `localhost` means the container itself. Please use the readable and proper style to format error.

**Comment by quzx** [comment]
my ip is not localhost. its  http://124.221.66.xxx
my installation:
git clone https://github.com/langgenius/dify.git
cd dify/docker
docker compose up -d

**Comment by crazywoola** [comment]
```
HTTPConnectionPool(host='localhost', port=6337)
```

**Comment by emptystack1024** [comment]
> ```
> HTTPConnectionPool(host='localhost', port=6337)
> ```

请问这个应该如何使用呢？
