### ISSUE TITLE
token usage by model and by input and output?

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#4907]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

We try to calculate the cost based on token usage of input/output and for different models.

The current token usage seems to be a lump sum:

<img width="1299" alt="Screenshot 2024-06-03 at 10 24 31 PM" src="https://github.com/langgenius/dify/assets/595772/abd20417-7fd9-4450-b0c6-de3522f81f23">

### 2. Describe the feature you'd like to see

token usage separated into input and output and for different models.

### 3. How will this feature improve your workflow or experience?

better calculate cost

### 4. Additional context or comments

none

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by harrywang** [comment]
@crazywoola is this not planned? I think this feature is quite important for accurate cost calculation.

**Comment by MJSanfelippo** [comment]
@crazywoola Any update here? It is weird that it doesn't do this - input and output tokens pricing are quite a bit different for basically every model.
