### ISSUE TITLE
Chat mode. Work choreography, api call, tag reply returned empty

### ISSUE THREAD

**Issue by SLHE135** [langgenius/dify#4909]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Chat mode. Work choreography, api call, tag reply returned empty
![image](https://github.com/langgenius/dify/assets/86449824/2a5fc4c7-0e10-4a58-b382-a4195d84d2a1)

### ✔️ Expected Behavior

Repair, or troubleshoot

### ❌ Actual Behavior

Unable to get the data returned by api

**Comment by crazywoola** [comment]
Streaming or block, if you use streaming mode, you need to handle the streaming calls, concat them into a complete result, vice verse, you will expect to get full answer by using blocking mode.

**Comment by SLHE135** [comment]
![image](https://github.com/langgenius/dify/assets/86449824/1852a7ca-a193-42d1-a1f1-276fdb1f2a07)
There will be no problem with changing the chat mode, but there will be a problem with the chat arrangement mode.
