### ISSUE TITLE
[Cloud] Missing added pages when trying to add a new page to Knowledge Base with Notion integration

### ISSUE THREAD

**Issue by davidphamle** [langgenius/dify#4921]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Go to Knowledge on Dify Cloud
2. Select a Knowledge Base that has Notion integration
3. Click on `Add Page`
4. Select a page and click on `Save`
5. Click on `Add Page`
6. Unselect the previous page and select another page, click on `Save`

### ✔️ Expected Behavior

The new page is added and the previous page is still in the knowledge base

### ❌ Actual Behavior

The new page is added and the previous page disappeared from the knowledge page

**Comment by davidphamle** [comment]
Any human maintainer here? @perzeuss

**Comment by perzeuss** [comment]
> Any human maintainer here? @perzeuss 

A maintainer has already been assigned, but the team is very busy. It could take a while until they have time for this.

The problem is that Dify does not remove notion pages from knowledge when you deselect them in the sync settings, right?
But you can manually remove them from knowledge and the notion sync stops for this page? Or does Dify still sync the removed page when you make changes?

**Comment by davidphamle** [comment]
1. The problem is that whenever I try to add a new page, it will remove all the previous one
2. If I try to select all page and resync, it will stop with an error of `Batch limit exceed 20 ...`
In the end, I am unable to have more than 20 pages in my knowledge base connected to Notion

**Comment by davidphamle** [comment]
Please respond @perzeuss

**Comment by perzeuss** [comment]
> Please respond @perzeuss 

The problem is clear, but someone has to have time to look at it.

**Comment by iamjoel** [comment]
I will fix it.
