### ISSUE TITLE
Use LLM to decide whether RAG query should be sent

### ISSUE THREAD

**Issue by lschaupp** [langgenius/dify#4923]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

RAG

### 2. Describe the feature you'd like to see

I tried to use the RAG feature. However it could be better. I was wondering if you are planning the functionality that during a RAG query, another query goes to the chat LLM asking it whether a query to the embedding model is actually necessary. If so, it should extract the necessary information from the user chat. This feature should be optional but it would improve the RAG.

### 3. How will this feature improve your workflow or experience?

It will improve the RAG.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by AndyMik90** [comment]
I believe you can achieve this by using Chatflow and having a question classifier to make the decision to retrieve from RAG or answer without.

**Comment by lschaupp** [comment]
@AndyMik90 Thanks for the info. However it would be nice to have an integrated solution for this.

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/issues/6019
