### ISSUE TITLE
Error in "Deploy the frontend page"

### ISSUE THREAD

**Issue by asemandeveloper** [langgenius/dify#4938]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I use the Local Source Code Start guide. At the stage of Deploy the frontend page and when executing the npm run start command, I get the following message. My computer's operating system is Windows 11. How do I solve the problem?

### ❌ Actual Behavior

D:\dify\web>npm run start

> dify-web@0.6.10 start
> cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && cross-env PORT=$npm_config_port HOSTNAME=$npm_config_host node .next/standalone/server.js

'cp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by asemandeveloper** [comment]
Your advice was very helpful.
But when executing the  "celery -A app.celery worker -P solo --without-gossip --without-mingle -Q dataset,generation,mail --loglevel INFO" command, I get the following error message!

[2024-06-04 22:47:42,554: ERROR/MainProcess] consumer: Cannot connect to redis://:**@localhost:6379/1: Error 10061 connecting to localhost:6379. [WinError 10061] No connection could be made because the target machine actively refused it...
Trying again in 2.00 seconds... (1/100)

What is the solution to this problem? Guide me.

**Comment by asemandeveloper** [comment]
I suggest you rewrite the "Local Source Code Start" guide for Windows users. And explain more precisely how to set environment variables in the web folder.
Thank you.

**Comment by sorehadokanajw** [comment]
> here
`redis-cli`
`config set requirepass xxx`

**Comment by crazywoola** [comment]
Please upgrade to 0.6.12 to see it this works for windows systems.
