### ISSUE TITLE
使用docker compose部署后，探索一栏数据是空的，如何向探索中加类别和具体应用？

### ISSUE THREAD

**Issue by wanglianyu** [langgenius/dify#494]
文档我翻过一遍了，没有找到

**Comment by wanglianyu** [comment]
我理解应该是有个专门维护推荐app的地方
不会是要手动往数据库里加数据吧，这两张表：apps、recommended_apps

**Comment by chenxingbao** [comment]
请问使用docker compose安装有没有碰到ERROR: manifest for docker.io/langgenius/dify-web:0.3.6 not found吗？

**Comment by wanglianyu** [comment]
> > 我理解应该是有个专门维护推荐app的地方 不会是要手动往数据库里加数据吧，这两张表：apps、recommended_apps
> 
> You are right, we have already record this feature.



> 请问使用docker compose安装有没有碰到ERROR: manifest for docker.io/langgenius/dify-web:0.3.6 not found吗？

我这没有报错，我是用的0.3.6这个tag直接部署的

**Comment by wanglianyu** [comment]
> #238

谢谢，我现在也是这么处理的，把apps表的public设置成true，然后手动insert一条数据到recommended_apps，不知道含义的字段设置成空的了，可以正常显示
INSERT INTO recommended_apps (app_id,description,copyright,privacy_policy,category,position,is_listed,install_count) VALUES ('14de4a08-6c5c-493d-9d76-78e58390903f','{}','','','写作',0,TRUE,1);
