### ISSUE TITLE
duckduckgo search does not work

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#4940]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud

### Steps to reproduce

not working:
<img width="1230" alt="Screenshot 2024-06-04 at 7 26 38 PM" src="https://github.com/langgenius/dify/assets/595772/69fb20a8-6c25-4ea0-a354-783219db8549">

### ✔️ Expected Behavior

can search and return results

### ❌ Actual Behavior

not working

**Comment by harrywang** [comment]
<img width="2559" alt="Screenshot 2024-06-04 at 7 31 04 PM" src="https://github.com/langgenius/dify/assets/595772/7e2dbd0c-93a3-4a9f-b0af-e8ecce10de2c">

**Comment by crazywoola** [comment]
@Yash-1511 Hello could you take a look at this tool?

**Comment by XiaoLey** [comment]
I also encountered this problem. I always thought it was only happening to me, but it turns out that no one can use it.

**Comment by hjlarry** [comment]
I also encountered the problem of duckduckgo.

In `https://cloud.dify.ai/` , It raise this error:
![20240605141231](https://github.com/langgenius/dify/assets/25834719/c865c1f2-3de8-4740-ba2b-a3df4cf50149)

In my local windows dev env,  it blocked entire process.

I upgrade the `duckduckgo-search` pkg verison to 6.1.5 can resolve the problem,  the 6.x version use a new request library `pyreqwest_impersonate` which is written in RUST.

I will take a PR later.
