### ISSUE TITLE
Baichuan conversation error

### ISSUE THREAD

**Issue by lvjiajjjlzy** [langgenius/dify#4943]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![屏幕截图 2024-06-05 112652](https://github.com/langgenius/dify/assets/103650510/8454b752-0a87-4fae-98f5-560a5d7796f0)

When the Baichuan model uses tools, errors may occur during the conversation.

### ✔️ Expected Behavior

Answer questions and dialogues normally.

### ❌ Actual Behavior

Unknown message type <class 'core.model_runtime.entities.message_entities.ToolPromptMessage'>

**Comment by lvjiajjjlzy** [comment]
> 若要解决错误“未知消息，请键入 <class 'core.model_runtime.entities.message_entities.ToolPromptMessage'>“，当百川模型在自托管 Dify 版本 0.6.10 （Docker） 中的对话中使用工具时，请确保百川模型不会收到任何与工具相关的消息。百川模型不支持工具。
> 
> 调用百川模型时，应确保参数为“非此即彼”或“空列表”。下面是一个示例，说明如何修改代码以避免传递与工具相关的消息：`tools``None`
> 
> ```python
> # Ensure tools is None or an empty list
> tools = None  # or tools = []
> 
> # Invoke the model without tools
> result = baichuan_model._invoke(
>     model=model_name,
>     credentials=credentials,
>     prompt_messages=prompt_messages,
>     model_parameters=model_parameters,
>     tools=tools,  # Ensure this is None or an empty list
>     stop=stop,
>     stream=stream,
>     user=user
> )
> ```
> 
> 通过确保参数未传递或设置为空列表，可以避免与不受支持的消息类型相关的错误`tools``None`[[1]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/baichuan/llm/llm.py)[[2]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/baichuan/llm/baichuan_turbo.py).
> 
> _要继续与 [Dosu](https://dosu.dev) 交谈，请提及 ._

然而百川本身是支持function call的。。。

**Comment by lvjiajjjlzy** [comment]
baichuan4 和 baichuan3 turbo 支持 tool
Baihuan4 and baihuan3 turbo support tool

**Comment by yanghx-git** [comment]
我使用localai 调用 agent 出现同样错误。看代码发现是`_convert_prompt_message_to_dict` 中缺少 ToolPromptMessage 的处理。从别处粘来一份就可以正常使用了。麻烦开发者改一下，小问题就不提pr了。谢谢。
api/core/model_runtime/model_providers/localai/llm/llm.py
![image](https://github.com/langgenius/dify/assets/30469680/e9680d13-a8e3-4a06-86cb-994ccf1cb74e)

**Comment by lvjiajjjlzy** [comment]
> 我使用localai 调用 agent 出现同样错误。看代码发现是`_convert_prompt_message_to_dict` 中缺少 ToolPromptMessage 的处理。从别处粘来一份就可以正常使用了。麻烦开发者改一下，小问题就不提pr了。谢谢。
> api/core/model_runtime/model_providers/localai/llm/llm.py
> ![image](https://github.com/langgenius/dify/assets/30469680/e9680d13-a8e3-4a06-86cb-994ccf1cb74e)
> 

你还是提个pr吧，不然他们可能不会管的
