### ISSUE TITLE
Add a confirmation dialog in workflow

### ISSUE THREAD

**Issue by lancemao** [langgenius/dify#4947]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

currently for most agents, we can do only trivial tasks like FAQ, query the weather, generate an image (most likely cannot be used in production), or write an article (highlights and paragraph). If we want the agent to do something serious, say transfer some cash to my wife, we lack a mechanism to interact with user for confirmation

### 2. Describe the feature you'd like to see

So, let's start by adding a simple 'Yes' or 'No' option in workflow and developer can hook up consecutive nodes

### 3. How will this feature improve your workflow or experience?

we can open up more business-crucial scenario.

I think ChatGPT supports this feature in their chat UI, if dify supports it in workflow, the good thing is that user can define the behavior in a very flexible way

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Razbolt** [comment]
Is there any updates regarding this feature ? I think these kind of features would boost dify platform. Currently it seems like lacking user interfaces and can only execture all operations defined in the workflow, with  showing outputs to user after the end of workflow.
