### ISSUE TITLE
Dify does not recognize this openapi requestBody when add self tools, Does it meet expectations?

### ISSUE THREAD

**Issue by rongway777** [langgenius/dify#4951]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

"requestBody": {
				"content": {
				  "text/plain": {
					"schema": {
					  "type": "string"
					}
				  }
				},
				"required":true
			  },

### ✔️ Expected Behavior

The corresponding requestBody can be identified

### ❌ Actual Behavior

Unable to identify

![image](https://github.com/langgenius/dify/assets/54027013/2496b820-4e68-43bb-8c00-0e1c63535614)

**Comment by crazywoola** [comment]
Do you have a full schema?

**Comment by rongway777** [comment]
> Do you have a full schema?

{
	"openapi": "3.1.0",
	"info": {
		"title": "",
		"description": "",
		"version": "1.0.0"
	},
	"tags": [],
	"servers": [
        {
          "url": "http://"
        }
      ],
	"paths": {
		"/": {
			"post": {
				"summary": "Test",
				"deprecated": false,
				"description": "Test",
                "operationId": "QuerySQL",
				"tags": [],
				"parameters": [
					{
						"name": "Ks-Auth-Principal",
						"in": "header",
						"description": "",
						"required": true,
						"example": "locallife_client/project",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "Ks-Auth-Token",
						"in": "header",
						"description": "",
						"required": true,
						"example": "",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "Ks-Task-Group-Id",
						"in": "header",
						"description": "",
						"required": true,
						"example": "1695",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "Ks-Query-Id",
						"in": "header",
						"description": "",
						"required": true,
						"example": "hbg5kz39-yqdh-v1zy-xhkz-j2cgo9uuinme",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "Content-type",
						"in": "header",
						"description": "",
						"required": true,
						"example": "text/plain",
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"content": {
						"text/plain": {
							"schema": {
							  "type": "string"
							}
						  }
					},
					"required":true
				  },
				"responses": {
					"200": {
						"description": "成功",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										
									}
								}
							}
						}
					}
				},
				"security": []
			}
		}
	},
	"components": {
		"schemas": {
			
		},
		"securitySchemes": {
			
		}
	}
}

@crazywoola this is my full schema
