### ISSUE TITLE
The install（Account registration） page keeps getting stuck， verions: 0.6.8, 0.6.9, 0.6.10

### ISSUE THREAD

**Issue by dyh2024** [langgenius/dify#4957]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8, 0.6.9, 0.6.10

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Deploy dify strictly follow the document of https://docs.dify.ai/getting-started/install-self-hosted/local-source-code ， or strictly follow the document of https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container,  Both appear the install（Account registration） page keeps getting stuck。  But succeed follow the document of https://docs.dify.ai/getting-started/install-self-hosted/docker-compose on the same Tencent Cloud Server 。

### ✔️ Expected Behavior

User registration page

### ❌ Actual Behavior

![1](https://github.com/langgenius/dify/assets/171358568/3ea4c17e-c3ca-445e-8b4d-3b40c85448b4)

**Comment by crazywoola** [comment]
Please check your env vars.

**Comment by dyh2024** [comment]
> Please check your env vars.

My env vars consistent with the documentation（ https://docs.dify.ai/getting-started/install-self-hosted/local-source-code，https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container）, and keep the same with default values, no modifications . for examples：api/.env , web/.env.local .  Do I need to modify the default vars? for example :CONSOLE_API_URL=http://127.0.0.1:5001 and NEXT_PUBLIC_API_PREFIX=http://localhost:5001/console/api

**Comment by dyh2024** [comment]
![图片2](https://github.com/langgenius/dify/assets/171358568/aa823eb3-2564-4327-8633-f3458f3815ff)
> > To configure the environment variables when starting from the local source, you should modify the `.env` files for the API and web services. Here are the steps:
> > 
> > 1. **API Service Configuration:**
> >    
> >    * Navigate to the `api` directory:
> >      ```shell
> >      cd api
> >      ```
> >    * Copy the environment variable configuration file:
> >      ```shell
> >      cp .env.example .env
> >      ```
> >    * Modify the `.env` file to include the necessary environment variables:
> >      ```dotenv
> >      CONSOLE_API_URL=http://127.0.0.1:5001
> >      CONSOLE_WEB_URL=http://127.0.0.1:3000
> >      SERVICE_API_URL=http://127.0.0.1:5001
> >      APP_API_URL=http://127.0.0.1:5001/api
> >      APP_WEB_URL=http://127.0.0.1:3000
> >      ```
> > 2. **Web Frontend Configuration:**
> >    
> >    * Navigate to the `web` directory:
> >      ```shell
> >      cd web
> >      ```
> >    * Create a file named `.env.local` and copy the contents from `.env.example`. Modify the values of these environment variables:
> >      ```dotenv
> >      NEXT_PUBLIC_API_PREFIX=http://localhost:5001/console/api
> >      NEXT_PUBLIC_PUBLIC_API_PREFIX=http://localhost:5001/api
> >      ```
> > 3. **CORS Configuration:**
> >    
> >    * Ensure that the CORS settings are properly configured in your `.env` files:
> >      ```dotenv
> >      CONSOLE_CORS_ALLOW_ORIGINS=*
> >      WEB_API_CORS_ALLOW_ORIGINS=*
> >      ```
> > 
> > After modifying these files, you need to rebuild and restart your services for the changes to take effect.
> > For more detailed configuration options, you can refer to the `environments.md` file in the Dify documentation [[1]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/environments.md)[[2]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/local-source-code.md).
> > _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
> 
> Configure the environment variables as same as above-mentioned, but the problem remain!
![图片1](https://github.com/langgenius/dify/assets/171358568/3b2441c7-e357-44de-aa63-76fa010e1234)
![图片2](https://github.com/langgenius/dify/assets/171358568/5d898e4e-0c94-42c0-96c9-a1b7a598bcba)

**Comment by dyh2024** [comment]
> Please check your env vars.

Maybe I found the cause of the problem. When I deploy the server according to the document  https://docs.dify.ai/getting-started/install-self-hosted/local-source-code#server-deployment, And start then frontend service according to the document https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container, by then command 'docker run -it -p 3000:3000 -e CONSOLE_URL=http://127.0.0.1:5001 -e APP_URL=http://127.0.0.1:5001 langgenius/dify-web:latest' .   My environment is Tencent Cloud Server and opened the ports: 3000,5001, When I visit http://127.0.0.1:3000 and http://(Internal IP):3000, no problem. But when I visit  http://(Public IP):3000, The problem arose(the install（Account registration） page keeps getting stuck).  The vars of CORS in  api/.env : WEB_API_CORS_ALLOW_ORIGINS=*, CONSOLE_CORS_ALLOW_ORIGINS=*.

**Comment by crazywoola** [comment]
> > Please check your env vars.
> 
> Maybe I found the cause of the problem!
> 
> After I deployed the server according to the document https://docs.dify.ai/getting-started/install-self-hosted/local-source-code#server-deployment, And start then frontend service according to the document https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container, by then command 'docker run -it -p 3000:3000 -e CONSOLE_URL=http://127.0.0.1:5001 -e APP_URL=http://127.0.0.1:5001 langgenius/dify-web:latest' .
> 
> My environment is Tencent Cloud Server and opened the ports: 3000,5001.
> 
> When I visit http://127.0.0.1:3000 and http://(Internal IP):3000, no problem. But when I visit http://(Public IP):3000, The problem arose(the install（Account registration） page keeps getting stuck).
> 
> The vars of CORS in api/.env : ![image](https://private-user-images.githubusercontent.com/171358568/337221650-c346afc0-e9e3-4fd9-91c3-134b817c208c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTM3NTUsIm5iZiI6MTcxODU5MzQ1NSwicGF0aCI6Ii8xNzEzNTg1NjgvMzM3MjIxNjUwLWMzNDZhZmMwLWU5ZTMtNGZkOS05MWMzLTEzNGI4MTdjMjA4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMzA0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjk1NzY3NWM2NGUzNjAwOWM1MjdjMGFjZWNiNjNkNjU2Y2I0Y2QyZjE4NzE0MGVhOTk1MDk0NDM3NWVlMDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rMKqF9h4jzfoSwQz1ckHdyn2hEuaC_ATYgFS6q0fYNI)
> 
> Is there any solution to this problem？

If you deploy the application to your public severs. 

You need to change this as well.

```
CONSOLE_URL=http://public-ip:5001/ -e APP_URL=http://public-ip:5001/
```

Because you are trying to access the  localhost(your computer) in your public server and it doesn't know.

**Comment by dyh2024** [comment]
> > > Please check your env vars.
> > 
> > 
> > Maybe I found the cause of the problem!
> > After I deployed the server according to the document https://docs.dify.ai/getting-started/install-self-hosted/local-source-code#server-deployment, And start then frontend service according to the document https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container, by then command 'docker run -it -p 3000:3000 -e CONSOLE_URL=http://127.0.0.1:5001 -e APP_URL=http://127.0.0.1:5001 langgenius/dify-web:latest' .
> > My environment is Tencent Cloud Server and opened the ports: 3000,5001.
> > When I visit http://127.0.0.1:3000 and http://(Internal IP):3000, no problem. But when I visit http://(Public IP):3000, The problem arose(the install（Account registration） page keeps getting stuck).
> > The vars of CORS in api/.env : ![image](https://private-user-images.githubusercontent.com/171358568/337221650-c346afc0-e9e3-4fd9-91c3-134b817c208c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTM3NTUsIm5iZiI6MTcxODU5MzQ1NSwicGF0aCI6Ii8xNzEzNTg1NjgvMzM3MjIxNjUwLWMzNDZhZmMwLWU5ZTMtNGZkOS05MWMzLTEzNGI4MTdjMjA4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMzA0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjk1NzY3NWM2NGUzNjAwOWM1MjdjMGFjZWNiNjNkNjU2Y2I0Y2QyZjE4NzE0MGVhOTk1MDk0NDM3NWVlMDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rMKqF9h4jzfoSwQz1ckHdyn2hEuaC_ATYgFS6q0fYNI)
> > Is there any solution to this problem？
> 
> If you deploy the application to your public severs.
> 
> You need to change this as well.
> 
> ```
> CONSOLE_URL=http://public-ip:5001/ -e APP_URL=http://public-ip:5001/
> ```
> 
> Because you are trying to access the localhost(your computer) in your public server and it doesn't know.

Thanks! This done!
