### ISSUE TITLE
[FeatureRequest] Add Zhipu's latest release models

### ISSUE THREAD

**Issue by jiacheo** [langgenius/dify#4959]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes

### 2. Describe the feature you'd like to see

Add the latest models of ZhipuAI like: glm-4-0520, glm-4-air, glm-4-airx and glm-4-flash, you can refer this document: https://open.bigmodel.cn/dev/api#glm-4

### 3. How will this feature improve your workflow or experience?

We can use the cheapest model and others.

### 4. Additional context or comments

No

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by orangeclk** [comment]
It has been fixed by #5089 
This issue can be closed.
