### ISSUE TITLE
为什么数据集要限制在15mb，那我要是有100mb大小的pdf该如何导入，是切分开成7个文件一个一个导入吗

### ISSUE THREAD

**Issue by jiangming-cmyk** [langgenius/dify#496]

**Comment by jiangming-cmyk** [comment]
并且上下文中多选数据集时会出现没有命中相关数据集的问题，直接调用的就是chatgpt的接口生成他的答案

**Comment by takatost** [comment]
Yup, files that are too big may cause memory issues

**Comment by eggb4by** [comment]
Can we make it so users can choose the file size limit by adding it as a configurable option? @takatost

**Comment by takatost** [comment]
Got it, we'll add the config soon.
