### ISSUE TITLE
会话标题生成异常

### ISSUE THREAD

**Issue by sunny0315** [langgenius/dify#497]
Dify version: Self Host （0.3.6 docker）

## Steps To Reproduce

1.创建“对话型”应用后，“预览”开启会话  （“概览”-->"设置"-->"语言"选择“简体中文”）
2.点击“新对话”后进行聊天

## The current behavior
不同会话生成的会话标题相同，且为英文，如下图
![image](https://github.com/langgenius/dify/assets/5812332/effafb5b-d7b6-4e4c-b133-d540686d8000)

## The expected behavior
1.生成与会话内容相符的标题
2.与会话语言相同
请问需要改动哪些代码修复上面的问题

**Comment by hutao562** [comment]
同样的问题，求解

**Comment by sunny0315** [comment]
> 同样的问题，求解

问题解决了，version=0.3.6，将api/core/prompt/prompts.py中的CONVERSATION_TITLE_PROMPT 进行修改
![image](https://github.com/langgenius/dify/assets/5812332/ae94ab39-ceb8-494f-bd09-ae53d57e4d8e)
{{query}} 修改为{query}

**Comment by takatost** [comment]
Thx so much for ur feedback! The issue has been fixed in #476
