### ISSUE TITLE
After upgrading dify-sandbox to 0.2.1, code node throws network error

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4979]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

After upgrading the sandbox to 0.2.1 I can't reach the sandbox. Downgrading to 0.2.0 it works fine.

The dockerfile has the new env:       SANDBOX_PORT: 8194

### ✔️ Expected Behavior

Work as 0.2.0

### ❌ Actual Behavior

Throws network error when using code excecution, also throws error when trying to GET manually with API request to the sandbox.

Works fine with 0.2.0

**Comment by xiaoxiao9992** [comment]
@dosu 更改配置后
ERROR: Network "docker_ssrf_proxy_network" needs to be recreated - internal has changed
