### ISSUE TITLE
Input value in Start Block changed when retrieved in other Blocks

### ISSUE THREAD

**Issue by philipdeng** [langgenius/dify#4983]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create a variable in Start Block, and retrieve it in the other block.

### ✔️ Expected Behavior

Variable input in Start Block reach custom tool Block correctly.

### ❌ Actual Behavior

The input value in Start Block become different value when reached a custom tool Block.
![image](https://github.com/langgenius/dify/assets/22946991/fdfa1305-f3c9-4e4e-9a18-1cb80354ed3a)
![image](https://github.com/langgenius/dify/assets/22946991/b35fd7a1-de78-493e-9ffe-294f2a0b2deb)

**Comment by crazywoola** [comment]
<img width="424" alt="image" src="https://github.com/langgenius/dify/assets/100913391/68becb0e-cfc0-41a8-a719-9bc10fc106cb">

Can you paste a screenshot of this block in edit mode?
<img width="445" alt="image" src="https://github.com/langgenius/dify/assets/100913391/24406529-fa27-41eb-8e8d-b415bb6bd541">

**Comment by philipdeng** [comment]
> <img alt="image" width="424" src="https://private-user-images.githubusercontent.com/100913391/337085961-68becb0e-cfc0-41a8-a719-9bc10fc106cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQwNjQsIm5iZiI6MTcxNzY0Mzc2NCwicGF0aCI6Ii8xMDA5MTMzOTEvMzM3MDg1OTYxLTY4YmVjYjBlLWNmYzAtNDFhOC1hNzE5LTliYzEwZmMxMDZjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwMzE2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjFmYzllOTVhOGI0YjkxYzU2YjI3YjYyZmYxYjE2MWJlMDcxMmYxYmI4YTMzMmQyNjNmMGU1ZGZiM2M4M2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XokUInRnrVEy3c3nbs6GKOzdofdhMuJe3wXzP7q8V-g">
> Can you paste a screenshot of this block in edit mode? <img alt="image" width="445" src="https://private-user-images.githubusercontent.com/100913391/337087520-24406529-fa27-41eb-8e8d-b415bb6bd541.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQwNjQsIm5iZiI6MTcxNzY0Mzc2NCwicGF0aCI6Ii8xMDA5MTMzOTEvMzM3MDg3NTIwLTI0NDA2NTI5LWZhMjctNDFlYi04ZThkLWI0MTViYjZiZDU0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwMzE2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWJlNmE4MTM0M2RhOTYzMDFmODU0MTk5MjVlODI5YmRkMjJmNWFkZDc1YzMyM2E2ZGRmODM2YzYzOWEwYWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WkyJTbTMDIMQOSsQ5eRo_C1h3z_Iv8kRvCLeAYY71hs">

Here is the screenshot
![image](https://github.com/langgenius/dify/assets/22946991/8a47aade-cf1c-4a49-9d7e-38634aa48a32)
