### ISSUE TITLE
Add Support Files for Newly Released GLM Models in chatglm/llm

### ISSUE THREAD

**Issue by Fzkin** [langgenius/dify#4984]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I encountered a problem when trying to use the functionality within api/core/model_runtime/model_providers/chatglm/llm. It lacks support files for the newly released models: GLM-4-9B, GLM-4-9B-Chat, GLM-4-9B-Chat-1M, and GLM-4V-9B.

### 2. Describe the feature you'd like to see

I would like to see support files added for the above-mentioned models so that they can operate and integrate smoothly within our existing system architecture.

### 3. How will this feature improve your workflow or experience?

Adding support for these models will allow me and other users to leverage the capabilities of these new models, enhancing the performance and flexibility of our current systems, and better facilitating large-scale language model training and inference.

### 4. Additional context or comments

Given the features and potential applications of these models, I believe it is crucial to support them on our platform. The current absence limits our ability to explore and implement more complex model applications.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by orangeclk** [comment]
Maybe you can try to run the chatglm models with Xinference, which is integrated with Dify.
