### ISSUE TITLE
when release to V0.6.9，there wasn't log in docker compose

### ISSUE THREAD

**Issue by skylong5257** [langgenius/dify#4990]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1，docker-compose.yaml
1）had set LOG_LEVEL: DEBUG
2，DEBUG : true。had tried to enable it or disable it.

2，entrypoint.sh
tried to add log-level in gunicorn
else
  if [[ "${DEBUG}" == "true" ]]; then
    echo "DEBUG is on"
    flask run --host=${DIFY_BIND_ADDRESS:-0.0.0.0} --port=${DIFY_PORT:-5001} --debug
  else
    echo "DEBUG is off"
    gunicorn \
      --log-level debug \
      --bind "${DIFY_BIND_ADDRESS:-0.0.0.0}:${DIFY_PORT:-5001}" \
      --workers ${SERVER_WORKER_AMOUNT:-1} \
      --worker-class ${SERVER_WORKER_CLASS:-gevent} \
      --timeout ${GUNICORN_TIMEOUT:-200} \
      --preload \
      app:app
  fi
  
3，add some log for testing in current code 
class LoginApi(Resource):
    """Resource for user login."""

    @setup_required
    def post(self):
        """Authenticate user and login."""
        logging.info("LoginApi test info")
        logging.debug("LoginApi test debug")
        parser = reqparse.RequestParser()
        parser.add_argument('email', type=email, required=True, location='json')
        parser.add_argument('password', type=valid_password, required=True, location='json')
        parser.add_argument('remember_me', type=bool, required=False, default=False, location='json')
        args = parser.parse_args()

        # todo: Verify the recaptcha

        try:
            logging.info("test ------ login with email: %s", args['email'])
            
4，below is the output（based on: DEBUG : true）
docker-api-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
docker-api-1  | WARNING:root:MAIL_TYPE is not set
docker-api-1  |  * Serving Flask app 'app.py'
docker-api-1  |  * Debug mode: on
docker-api-1  | INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
docker-api-1  |  * Running on all addresses (0.0.0.0)
docker-api-1  |  * Running on http://127.0.0.1:5001
docker-api-1  |  * Running on http://172.31.0.7:5001
docker-api-1  | INFO:werkzeug:Press CTRL+C to quit
docker-api-1  | INFO:werkzeug: * Restarting with stat
docker-api-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
docker-api-1  | WARNING:root:MAIL_TYPE is not set
docker-api-1  | WARNING:werkzeug: * Debugger is active!
docker-api-1  | INFO:werkzeug: * Debugger PIN: 743-061-682
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:28:52] "GET /console/api/logout HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:28:52] "GET /console/api/system-features HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:09] "POST /console/api/login HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/apps?page=1&limit=30&name= HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/account/profile HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/workspaces/current HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/version?current_version=0.6.9 HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/tags?type=app HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/features HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/workspaces HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/apps?page=1&limit=30&name= HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/datasets/retrieval-setting HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/workspaces/current/model-providers HTTP/1.1" 200 -
docker-api-1  | INFO:werkzeug:172.31.0.10 - - [05/Jun/2024 23:29:10] "GET /console/api/workspaces/current/models/model-types/llm HTTP/1.1" 200 -

**Comment by skylong5257** [comment]
@dosu Thanks for your quick response.
I think the code in my space was same with your renmensioned.
1，docker-compose.yaml
version: '3.1'
services:
  # API service
  api:
    image: dify-api:latest
    #image: langgenius/dify-api:0.5.6
    restart: always
    environment:
      # Startup mode, 'api' starts the API server.
      MODE: api
      # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
      LOG_LEVEL: DEBUG
      # enable DEBUG mode to output more logs
      DEBUG : true

2，app.py
def create_app() -> Flask:
    app = DifyApp(__name__)
    app.config.from_object(Config())

    app.secret_key = app.config['SECRET_KEY']

    log_handlers = None
    log_file = app.config.get('LOG_FILE')
    if log_file:
        log_dir = os.path.dirname(log_file)
        os.makedirs(log_dir, exist_ok=True)
        log_handlers = [
            RotatingFileHandler(
                filename=log_file,
                maxBytes=1024 * 1024 * 1024,
                backupCount=5
            ),
            logging.StreamHandler(sys.stdout)
        ]
    logging.basicConfig(
        level=app.config.get('LOG_LEVEL'),
        format=app.config.get('LOG_FORMAT'),
        datefmt=app.config.get('LOG_DATEFORMAT'),
        handlers=log_handlers
    )

    initialize_extensions(app)
    register_blueprints(app)
    register_commands(app)

    return app

After my reading the historical version, I will try to use below code for the testing:
logging.basicConfig(level=app.config.get('LOG_LEVEL', 'INFO'))

**Comment by yaohongfenglove** [comment]
It maybe a bug, I also encountered it. The problem is that before the execution of the logging.basicConfig() in create.app(), other log configurations were executed, as a result, the configuration was overwritten.
﻿
I solved it temporarily like this:
Add a line of code to the app. py,  to import a class from a_fix_logger.py

**app.py** 
add "from a_fix_logger import LogInitializer" before "from commands import register_commands"
```python
import json
import logging
import sys
import threading
import time
import warnings
from logging.handlers import RotatingFileHandler

from flask import Flask, Response, request
from flask_cors import CORS
from werkzeug.exceptions import Unauthorized

from a_fix_logger import LogInitializer  # add
from commands import register_commands
from config import Config
```


**a_fix_logger.py**
```python

import logging
import os
import sys
from logging.handlers import RotatingFileHandler

from config import Config


class LogInitializer:

    config = Config()

    log_handlers = None
    log_file = config.LOG_FILE
    if log_file:
        log_dir = os.path.dirname(log_file)
        os.makedirs(log_dir, exist_ok=True)
        log_handlers = [
            RotatingFileHandler(
                filename=log_file,
                maxBytes=1024 * 1024 * 1024,
                backupCount=5
            ),
            logging.StreamHandler(sys.stdout)
        ]

    logging.basicConfig(
        level=config.LOG_LEVEL,
        format=config.LOG_FORMAT,
        datefmt=config.LOG_DATEFORMAT,
        handlers=log_handlers
    )

```

**Comment by skylong5257** [comment]
Thanks @yaohongfenglove , it was working based on your workaround.
@dosu could you please push to fix this issue? hope your updated version.

**Comment by zhangever** [comment]
Anyone help on this??

**Comment by crazywoola** [comment]
@zhangever Have you try the latest version?
