### ISSUE TITLE
When starting the web locally, encountering the "Fatal JavaScript invalid size error 169220804" during the run build process.

### ISSUE THREAD

**Issue by qizhiyuan** [langgenius/dify#4994]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![532DA239-97C9-48A6-8309-A76715683F19](https://github.com/langgenius/dify/assets/31427646/9becc091-3ccf-4ddd-99a2-8e2814779ff3)

### ✔️ Expected Behavior

build success

### ❌ Actual Behavior

Fatal JavaScript invalid size error 169220804

**Comment by qizhiyuan** [comment]
I have tried versions 18.17.0 and 18.17.1, but the same issue persists.

**Comment by qizhiyuan** [comment]
How to configure the local env.local.

**Comment by crazywoola** [comment]
> How to configure the local env.local.

`cp .env.example .env.local`. But I think there is something wrong with you local machine. You can ignore the  bot's reply except this one https://github.com/langgenius/dify/issues/4994#issuecomment-2151560523.

**Comment by lzwaiwai** [comment]
install with yarn
