### ISSUE TITLE
Adding python requirements to sandbox gives Github Action error

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4997]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Add dependencies to docker/volumes/sandbox/dependencies/python-requirements.txt
"requests
jinja2
httpx"

When API Test 3.10 and 3.11 run in github action, it gives error on the code excecution:
=========================== short test summary info ============================
FAILED api/tests/integration_tests/workflow/nodes/code_executor/test_code_javascript.py::test_javascript_plain - core.helper.code_executor.code_executor.CodeExecutionException: Failed to execute code, which is likely a network issue, please check if the sandbox service is running. ( Error: Failed to execute code, got status code 502, please check if the sandbox service is running )

### ✔️ Expected Behavior

The sanbox works locally and on AWS ECS with these dependencies, and we are relying on them in the python-requirements.txt since our sandbox is deployed by itself and not with docker.

### ❌ Actual Behavior

Gives code excecution errors on api checks

**Comment by crazywoola** [comment]
@bowenliang123

**Comment by bowenliang123** [comment]
It may require @Yeuoly 's review and futher solutions, since the dify-sandox is not yet part of the open-source project.

**Comment by Yeuoly** [comment]
We should check the logs for these actions I guess. It seems the sandbox service didn't start successfully. The logs might help

**Comment by AndyMik90** [comment]
@Yeuoly So the sandbox itself seems to be running:

 36446b6ba251 Pull complete 
 sandbox Pulled 
 Network docker_ssrf_proxy_network  Creating
 Network docker_ssrf_proxy_network  Created
 Network docker_default  Creating
 Network docker_default  Created
 Container docker-ssrf_proxy-1  Creating
 Container docker-sandbox-1  Creating
 Container docker-sandbox-1  Created
 Container docker-ssrf_proxy-1  Created
 Container docker-ssrf_proxy-1  Starting
 Container docker-sandbox-1  Starting
 Container docker-sandbox-1  Started
 Container docker-ssrf_proxy-1  Started
docker-compose is up

when I removed the dependencies from the docker/volumes/sandbox/dependencies/python-requirements.txt, the GitHub action goes through with no problem.
