### ISSUE TITLE
docker-compose 容器启动都正常，install 404

### ISSUE THREAD

**Issue by luefei** [langgenius/dify#50]
使用 https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml 启动后，
访问  http://xxxxx/install    404

是需要修改 docker-compose.yaml 什么地方么？

**Comment by takatost** [comment]
可以检查 nginx 配置文件域名是否匹配 `docker/nginx/conf.d/default.conf`
默认为 localhost，改动后重启 nginx 容器生效

**Comment by luefei** [comment]
这里是使用 IP 直接进行访问
default.conf 的 server_name 也是修改成 IP 了的
还是 404，错误日志如下：
[16/May/2023:10:11:41 +0000] "GET /install HTTP/1.1" 404 555 "-" "Mozilla/5.0

**Comment by takatost** [comment]
已优化默认配置，可拉一下最新代码，并拉取最新 `dify-api` 镜像重新部署一下：
```
git pull
docker pull langgenius/dify-api:latest
```

**Comment by luefei** [comment]
已解决，感谢

**Comment by liulijing3-tal** [comment]
> 已解决，感谢

请问是如何解决的？遇到相同的问题更新代码无效。nginx收到请求，web收不到转发的请求。容器内均无报错日志

**Comment by Secnobe** [comment]
需要在default.conf.template配置文件中，将proxy_pass代码中域名端口号后加入斜杠，例：proxy_pass http://api:3000/；

**Comment by ZZZ2999** [comment]
可能端口被占用了 要修.env中的EXPOSE_NGINX_PORT 修改docker-compose.yaml没用
