### ISSUE TITLE
dify 在创建工作流时，是否支持并行执行两个或多个分支，最终将多个分支的结果合并起来输出

### ISSUE THREAD

**Issue by wangyao123456a** [langgenius/dify#5003]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1

### ✔️ Expected Behavior

1

### ❌ Actual Behavior

1

**Comment by wangyao123456a** [comment]
追问：如果支持并行执行多个分支，那么节点选择哪个呢？条件分支？

**Comment by Leonard-Li777** [comment]
我也想要这个功能，不过目前看起来不支持，还有条件循环分支也不支持

**Comment by wangyao123456a** [comment]
条件分支之间不是互斥的吗？一个条件下只能走其中一个分支吧？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月06日 19:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [langgenius/dify] dify 在创建工作流时，是否支持并行执行两个或多个分支，最终将多个分支的结果合并起来输出 (Issue #5003) |

Dify 确实支持在工作流中并行执行多个分支，并且节点的选择是基于条件分支的。具体来说，Dify 使用条件分支（如 IF/ELSE 节点）来决定执行路径。

例如，IfElseNode 类展示了如何使用条件分支来确定执行路径：

classIfElseNode(BaseNode):
    _node_data_cls=IfElseNodeDatanode_type=NodeType.IF_ELSEdef_run(self, variable_pool: VariablePool) ->NodeRunResult:
        node_data=self.node_datanode_data=cast(self._node_data_cls, node_data)

        node_inputs= {
            "conditions": []
        }

        process_datas= {
            "condition_results": []
        }

        try:
            logical_operator=node_data.logical_operatorinput_conditions= []
            forconditioninnode_data.conditions:
                actual_value=variable_pool.get_variable_value(
                    variable_selector=condition.variable_selector
                )

                expected_value=condition.valueinput_conditions.append({
                    "actual_value": actual_value,
                    "expected_value": expected_value,
                    "comparison_operator": condition.comparison_operator
                })

            node_inputs["conditions"] =input_conditionsforinput_conditionininput_conditions:
                actual_value=input_condition["actual_value"]
                expected_value=input_condition["expected_value"]
                comparison_operator=input_condition["comparison_operator"]
                ifcomparison_operator=="contains":
                    compare_result=self._assert_contains(actual_value, expected_value)
                elifcomparison_operator=="not contains":
                    compare_result=self._assert_not_contains(actual_value, expected_value)
                elifcomparison_operator=="start with":
                    compare_result=self._assert_start_with(actual_value, expected_value)
                elifcomparison_operator=="end with":
                    compare_result=self._assert_end_with(actual_value, expected_value)
                elifcomparison_operator=="is":
                    compare_result=self._assert_is(actual_value, expected_value)
                elifcomparison_operator=="is not":
                    compare_result=self._assert_is_not(actual_value, expected_value)
                elifcomparison_operator=="empty":
                    compare_result=self._assert_empty(actual_value)
                elifcomparison_operator=="not empty":
                    compare_result=self._assert_not_empty(actual_value)
                elifcomparison_operator=="=":
                    compare_result=self._assert_equal(actual_value, expected_value)
                elifcomparison_operator=="≠":
                    compare_result=self._assert_not_equal(actual_value, expected_value)
                elifcomparison_operator==">":
                    compare_result=self._assert_greater_than(actual_value, expected_value)
                elifcomparison_operator=="<":
                    compare_result=self._assert_less_than(actual_value, expected_value)
                elifcomparison_operator=="≥":
                    compare_result=self._assert_greater_than_or_equal(actual_value, expected_value)
                elifcomparison_operator=="≤":
                    compare_result=self._assert_less_than_or_equal(actual_value, expected_value)
                elifcomparison_operator=="null":
                    compare_result=self._assert_null(actual_value)
                elifcomparison_operator=="not null":
                    compare_result=self._assert_not_null(actual_value)
                else:
                    continueprocess_datas["condition_results"].append({
                    **input_condition,
                    "result": compare_result
                })
        exceptExceptionase:
            returnNodeRunResult(
                status=WorkflowNodeExecutionStatus.FAILED,
                inputs=node_inputs,
                process_data=process_datas,
                error=str(e)
            )

        iflogical_operator=="and":
            compare_result=Falsenotin [condition["result"] forconditioninprocess_datas["condition_results"]]
        else:
            compare_result=Truein [condition["result"] forconditioninprocess_datas["condition_results"]]

        returnNodeRunResult(
            status=WorkflowNodeExecutionStatus.SUCCEEDED,
            inputs=node_inputs,
            process_data=process_datas,
            edge_source_handle="false"ifnotcompare_resultelse"true",
            outputs={
                "result": compare_result
            }
        )

这个类通过条件分支来决定执行路径，确保每个分支根据条件的结果来执行 [1][2][3][4].

To continue talking to Dosu, mention @dosu.

**Comment by frankzqy** [comment]
请问并行执行多个分支的能力大约什么时候推出来

**Comment by jianhuatu** [comment]
请问多个if判断后，其中有部分判断后的结果会走向一个节点。比如我会对3个if后的某些条件走到最后一个llm节点来生成一些内容。目前能支持吗，我用的时候多个节点指向一个llm节点只能连接一个。

**Comment by Mofangbao** [comment]
> 候

这个使用变量聚合器节点来实现就可以的。

**Comment by Mofangbao** [comment]
> 请问多个if判断后，其中有部分判断后的结果会走向一个节点。比如我会对3个if后的某些条件走到最后一个llm节点来生成一些内容。目前能支持吗，我用的时候多个节点指向一个llm节点只能连接一个。

@jianhuatu  这个可以使用变量聚合器节点来实现。

**Comment by huangzhenhao90** [comment]
这个 issue 咋还关了，是不准备加这个功能呗，最典型的一个场景就是对比相同的 prompt 不同的大模型出来的结果啊

**Comment by land007** [comment]
啥时间出这个功能

**Comment by r600a-code** [comment]
变量聚合仍然不支持，会跳过去到下一个节点
