### ISSUE TITLE
Integration of Baidu Search for Enhanced Information Retrieval

### ISSUE THREAD

**Issue by ironartisan** [langgenius/dify#5008]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, when searching for information, especially in Chinese, having results from multiple search engines can enhance the credibility and comprehensiveness of the results.

### 2. Describe the feature you'd like to see

I propose the integration of Baidu search into Dify. This feature should be accessible from the tool's menu, and the display of results should be consistent with other tools in Dify.

### 3. How will this feature improve your workflow or experience?

This feature will improve my workflow by providing a more comprehensive set of search results. By integrating results from multiple search engines, I can ensure the credibility of the information I retrieveNone.

### 4. Additional context or comments

None

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by lvjiajjjlzy** [comment]
百度那搜索结果，垃圾一堆，也没API
