### ISSUE TITLE
Chinese encoding issue

### ISSUE THREAD

**Issue by aiping312** [langgenius/dify#5010]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I turned the workflow into a tool, but the Chinese output from this tool  converted to Unicode encoding. In the original workflow, the Chinese output was normal.

![image](https://github.com/langgenius/dify/assets/7221616/2aeb9035-daf9-410d-9bb2-47f50d6cd257)

**Comment by aiping312** [comment]
我做了个简单的workflow，功能就是把输入的内容原样输出，发布成工具后调用还是出现中文unicode编码问题。
![image](https://github.com/langgenius/dify/assets/7221616/4f1a1176-3d34-49a9-a4c4-21bbbc113047)

**Comment by hjlarry** [comment]
> 我做了个简单的workflow，功能就是把输入的内容原样输出，发布成工具后调用还是出现中文unicode编码问题。 ![image](https://private-user-images.githubusercontent.com/7221616/337539227-4f1a1176-3d34-49a9-a4c4-21bbbc113047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDExMzcsIm5iZiI6MTcxNzc0MDgzNywicGF0aCI6Ii83MjIxNjE2LzMzNzUzOTIyNy00ZjFhMTE3Ni0zZDM0LTQ5YTktYTRjNC0yMWJiYmMxMTMwNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDYxMzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgwMWQzOTk3N2NkM2JlNzFhNDM1NDBlYzk4MTNjNDIwYzcyM2RjNTk0ZDAwZGY4OWNlMGFjZDE1YjBlNmYwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fdg3v0gbNctZKzfX50wgiRbZp7VCHSRJ3aVRADTiapc)

I can't reproduce your issue, please upload the `tool测试` part,  snapshot or the DSL file

**Comment by aiping312** [comment]
> > 我做了个简单的workflow，功能就是把输入的内容原样输出，发布成工具后调用还是出现中文unicode编码问题。 ![image](https://private-user-images.githubusercontent.com/7221616/337539227-4f1a1176-3d34-49a9-a4c4-21bbbc113047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDExMzcsIm5iZiI6MTcxNzc0MDgzNywicGF0aCI6Ii83MjIxNjE2LzMzNzUzOTIyNy00ZjFhMTE3Ni0zZDM0LTQ5YTktYTRjNC0yMWJiYmMxMTMwNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDYxMzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgwMWQzOTk3N2NkM2JlNzFhNDM1NDBlYzk4MTNjNDIwYzcyM2RjNTk0ZDAwZGY4OWNlMGFjZDE1YjBlNmYwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fdg3v0gbNctZKzfX50wgiRbZp7VCHSRJ3aVRADTiapc)
> 
> I can't reproduce your issue, please upload the `tool测试` part, snapshot 
[DSL.txt](https://github.com/user-attachments/files/15720306/DSL.txt)
or the DSL file
已上传，后缀改成了txt。

**Comment by aiping312** [comment]
Issue resolved

**Comment by July791** [comment]
> Issue resolved

遇到了同样的问题，请教下是如何解决的？

**Comment by HoneyJoe** [comment]
> > Issue resolved
> 
> 遇到了同样的问题，请教下是如何解决的？

我是http模块调接口遇到的。

**Comment by HoneyJoe** [comment]
> > Issue resolved
> 
> 遇到了同样的问题，请教下是如何解决的？

我是http模块调接口时遇到的。返回类型 改为'text/pain; charset=utf-8' 就可以了

**Comment by pinsily** [comment]
> > > Issue resolved 问题已解决
> > 
> > 
> > 遇到了同样的问题，请教下是如何解决的？
> 
> 我是http模块调接口时遇到的。返回类型 改为'text/pain; charset=utf-8' 就可以了

请教下，http模块，如何在返回时设置返回类型
