### ISSUE TITLE
Database writing and reading, like coze database

### ISSUE THREAD

**Issue by tianlongwang** [langgenius/dify#5022]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes. I need a way to automatic track chat report and refer to older chat report. 

### 2. Describe the feature you'd like to see

exactly like coze database node

### 3. How will this feature improve your workflow or experience?

It would automate the process of reading and writing databases, hence automating data pipelines. 

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated
