### ISSUE TITLE
An error occurs when using Gemini if ​​the response format is JSON and an image is uploaded.

### ISSUE THREAD

**Issue by otty0507** [langgenius/dify#5031]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![スクリーンショット 2024-06-07 21 38 29](https://github.com/langgenius/dify/assets/12377287/a6d2bbcb-474f-4bf4-a205-8c3fb488f472)

### ✔️ Expected Behavior

Can be used normally without errors

### ❌ Actual Behavior

An error occurs

**Comment by takatost** [comment]
Could you please provide more details about the error for our reference?
