### ISSUE TITLE
In the "Add Model" dialog box of Azure OpenAI Service, the "Base Model" list will be obscured.

### ISSUE THREAD

**Issue by breakstring** [langgenius/dify#5037]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Log in to the console.
2. Click the drop-down menu in the upper right corner, select "Settings," and then choose "Model Provider" from the left navigation.
3. Find "Azure OpenAI Service" and click the "Add Model" button.
4. Scroll through the content of the pop-up dialog box and expand the "Base Model" list.

### ✔️ Expected Behavior

Able to see all the list items in the "Base Model" completely and select the items without any obstruction.

### ❌ Actual Behavior

<img width="630" alt="image" src="https://github.com/langgenius/dify/assets/14105911/cb4a1b95-02a2-467a-9084-d2114af0bef6">
The list items in the "Base Model" are obscured, and when the type is something like tts or embedding, the obscured area happens to cover the items that need to be selected, making it impossible to select them.

**Comment by takatost** [comment]
The configuration method of Azure OpenAI is different from OpenAI. 
For Azure OpenAI, you need to manually add a custom named Deployment in the Azure console and select a base model. The same goes for Dify, you need to choose a base model and enter the corresponding Deployment name.

**Comment by breakstring** [comment]
> The configuration method of Azure OpenAI is different from OpenAI. For Azure OpenAI, you need to manually add a custom named Deployment in the Azure console and select a base model. The same goes for Dify, you need to choose a base model and enter the corresponding Deployment name.

What I discussed above is not about how to use the Azure OpenAI Service Node, but rather an out-of-the-box UI bug in Dify related to the Azure OpenAI node.

**Comment by gijigae** [comment]
@takatost it would be a lot easier to understand the bug if you look at the video clip below. :) When you click on the Base Model dropdown box, the text, "Get your API key from Azure", is on top of the base model list.

![2024-06-11_11-19-03 (1)](https://github.com/langgenius/dify/assets/81459/e1c0a0df-78cf-411a-a44d-2faec0384ff5)

**Comment by kurokobo** [comment]
@breakstring @gijigae @takatost 
This issue is addressed in 0.6.11 so we can close this😀 
![image](https://github.com/langgenius/dify/assets/2920259/74af4784-1583-4604-b12c-b7d49b659be4)

**Comment by breakstring** [comment]
> @breakstring @gijigae @takatost This issue is addressed in 0.6.11 so we can close this😀 ![image](https://private-user-images.githubusercontent.com/2920259/339948416-74af4784-1583-4604-b12c-b7d49b659be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzU1NTUsIm5iZiI6MTcxODQzNTI1NSwicGF0aCI6Ii8yOTIwMjU5LzMzOTk0ODQxNi03NGFmNDc4NC0xNTgzLTQ2MDQtYjEyYy1iN2Q0OWI2NTliZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTVUMDcwNzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdkOTQwYTA0ODEzOTY5NmIxMDkxMmMzYjE4NjlmOWQ4NWFmNjhiNmQ4YjQ5Y2I1YmNhNGMzMjc4ODM4MDliOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9PjmzceUE4cGG2RZpDabtM2dGXMNsGSUar3aO-ObP5E)

Just quick checked and this issue was fixed. Thank you.
