### ISSUE TITLE
Flexibility to change the file upload size on Embedding

### ISSUE THREAD

**Issue by kailasa-ai** [langgenius/dify#5045]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I tried to increase the file upload size in the Docker Compose file, it shows the size has increased but it does not let me upload larger file size.

### 2. Describe the feature you'd like to see

It would be helpful if there was an easy way to set this to a higher file size upload limit.

### 3. How will this feature improve your workflow or experience?

I have multiple large files exceeding 15MB, and I'm not alone in this challenge. It would be incredibly helpful to have an option to upload larger files, ideally with a customizable upload size limit.

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Other than changing the `UPLOAD_FILE_SIZE_LIMIT` environment variable, you may also need to modify the `client_max_body_size` in the nginx configuration to the corresponding maximum file limit, ensuring that the upload size limit for the entire chain from the browser to the Dify API backend is correct.

**Comment by kailasa-ai** [comment]
This solution worked for me, thank you.
