### ISSUE TITLE
/console/api/version?current_version=0.3.1 这个接口特别慢，需要1分多钟

### ISSUE THREAD

**Issue by flyowl** [langgenius/dify#505]
导致页面打开特别慢，基本打开一下1分钟起步，存在严重的问题
![image](https://github.com/langgenius/dify/assets/49393051/95bf9cd2-6bd5-421c-85a3-97fc33917344)

**Comment by syhleo** [comment]
我也有这个问题

**Comment by syhleo** [comment]
![image](https://github.com/langgenius/dify/assets/26354748/231d1eb1-cc4a-4aa2-91c0-01ebea5d5d32)

**Comment by iamjoel** [comment]
Fixed. https://github.com/langgenius/dify/pull/520
