### ISSUE TITLE
'Exception Catch' and 'Status Feedback' suggested to add for each 'Tool'

### ISSUE THREAD

**Issue by Eelahne** [langgenius/dify#5051]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

While building iteration in workflow, there always be interruptions while calling for tools like JinaReader or Web_scraper due to timeout or network issue, but workflow itself couldn't address error raised by tools, only have to stop process and re-tune the workflow. Anyhow, LLM output is not stable as we thought, there's somehow irrelated output, it is not possible to solve it by re-tuning.

### 2. Describe the feature you'd like to see

I noticed there's no 'try...catch...' loop in tools' code, there should be, and better to feedback status via tool output.

### 3. How will this feature improve your workflow or experience?

If tools feedback error via output fields, at least the entire workflow designing could be much more robust

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by perzeuss** [comment]
I like the idea. I also thought about a way to implement error handling in chatflows. It would be great if we could catch errors with a node and be able to retry just one node based on the error.

Being able to handle errors for error tracking would also be beneficial. For example, sending a Sentry log when the workflow fails would allow me to track issues, improve chatflows, and monitor workflow performance.

I think it would be advantageous if every node had an error output where we could handle the error state. Additionally, a catch-all error handler would be useful to prevent the need for adding the same error-handling node multiple times. This catch-all handler could act as a fallback for tools that don't have built-in error handling.

**Comment by Eelahne** [comment]
Yap, besides of LLM setting, most of workflow interruption comes from tools.

**Comment by shanzhaigege** [comment]
this is a eager need

**Comment by shanzhaigege** [comment]
I like the idea, do you have a plan to implement it
