### ISSUE TITLE
Using the jinareader tool, BUG in multi-round conversations

### ISSUE THREAD

**Issue by burniceberg** [langgenius/dify#5055]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1276" alt="0" src="https://github.com/langgenius/dify/assets/72774035/92c128b1-cebf-4263-8887-b46c692bc566">
<img width="1275" alt="1" src="https://github.com/langgenius/dify/assets/72774035/833e7f45-db9d-4dfb-a497-f46b9028f0a9">

**Comment by sinomoe** [comment]
the issue has been fixed in #5245
