### ISSUE TITLE
请支持下Xinference 的TTS模型类型

### ISSUE THREAD

**Issue by liduang** [langgenius/dify#5065]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

 
![image](https://github.com/langgenius/dify/assets/37337756/9bed921c-41ab-4cae-88f6-0d589a566cae)

### ✔️ Expected Behavior

Xinference 的v0.12.0支持了text2speech模型ChatTTS，但是目前dify支持的Xinference模型类型还没有text2speech，请更新下，谢谢

**Comment by link-king** [comment]
已经支持了吗

**Comment by crazywoola** [comment]
<img width="779" alt="image" src="https://github.com/langgenius/dify/assets/100913391/13bafaaf-9218-4e2f-8c9e-a5ba5537c404">
@liduang
