### ISSUE TITLE
Full text search keyword search enhancement

### ISSUE THREAD

**Issue by xiearthur** [langgenius/dify#5076]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am currently conducting knowledge base related functional testing and have used several retrieval modes and mixed retrieval modes. I have found that keyword retrieval often fails to recall. I have noticed that we are currently using Python Jieba for full-text retrieval. Is there any enhancement in this area
I think full-text retrieval is a supplement to vector retrieval, and poor quality of full-text retrieval will inevitably affect the accuracy of recall
Note: I have attempted to use high-quality vector mode but cannot recall it

### 2. Describe the feature you'd like to see

More accurate keyword retrieval

### 3. How will this feature improve your workflow or experience?

Reduce knowledge base segmentation and keyword modifications

### 4. Additional context or comments

I am currently conducting knowledge base related functional testing and have used several retrieval modes and mixed retrieval modes. I have found that keyword retrieval often fails to recall. I have noticed that we are currently using Python Jieba for full-text retrieval. Is there any enhancement in this area
I think full-text retrieval is a supplement to vector retrieval, and poor quality of full-text retrieval will inevitably affect the accuracy of recall
Note: I have attempted to use high-quality vector mode but cannot recall it

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by jiandanfeng** [comment]
When searching for "新增订单入口", the "新增订单 功能入口" cannot be retrieved,it seems like there is no word segmentation.

**Comment by chenylong** [comment]
keyword search not work, Unable to recall content normally
