### ISSUE TITLE
工作流作为工具后用户输入参数不能使用变量

### ISSUE THREAD

**Issue by vary** [langgenius/dify#5081]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

工作流可以作为工具是一个非常好改进，极大的提升了使用的可能性，不过在作为工具后，如果配置为用户输入，那么在agent中配置时无法使用变量，如下图所示：
<img width="409" alt="image" src="https://github.com/langgenius/dify/assets/3312460/4ee84654-788b-4ffb-82e8-91953a1f964b">

### 2. Describe the feature you'd like to see

希望能够支持变量，可以很好的补充无需LLM推理生成变量的场景

### 3. How will this feature improve your workflow or experience?

支持变量后，那么agent的变量就可以和工作流的变量打通，那么就可以极大的扩展很多场景，如果只能通过LLM推理或者用户固定的配置局限性会很大，没办法处理很多动态的场景

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by allen-x233** [comment]
我碰到了一样的问题，怎么没有后续了呢
