### ISSUE TITLE
misspelling `LocalAILarguageModel`

### ISSUE THREAD

**Issue by algorithmx** [langgenius/dify#5082]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am reading the source code and spotted this typo.

### 2. Describe the feature you'd like to see

change LocalAILarguageModel to LocalAILanguageModel (larguage to language :smiley: )

### 3. How will this feature improve your workflow or experience?

I can make better use of LLM to understand the Dify source code

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Hello could your send a pr to fix this issue? We are appreciate all kinds of contribution.

**Comment by HiChen404** [comment]
@crazywoola I replaced this word globally.
