### ISSUE TITLE
 document indexing cannot be properly completed.

### ISSUE THREAD

**Issue by jiaolongxue** [langgenius/dify#5087]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The document indexing cannot be properly completed. When the file size exceeds 10MB, the process of creating the document index gets stuck and cannot end normally. Even after restarting the API service and worker, it remains stuck.

### ✔️ Expected Behavior

document indexing  properly completed

### ❌ Actual Behavior

The document indexing cannot be properly completed. When the file size exceeds 10MB, the process of creating the document index gets stuck and cannot end normally. Even after restarting the API service and worker, it remains stuck.

**Comment by crazywoola** [comment]
Can you provide more details such as LLM, embedding models?

**Comment by jiaolongxue** [comment]
> Can you provide more details such as LLM, embedding models?

use xinference bge-m3-large and ollama qwen1.5-13b

The previous dify version 0.6.8 was fine.

**Comment by Nordpolar** [comment]
Similar Problem here we also have that issue with our hosted version.

**Comment by NicoXcc** [comment]
Guys 
We are using Self Hosted Dify. It is deployed via Helm charts. 
We are also experiencing the same issue on vs 0.6.3 .

Steps to replicate:
1. Try to upload any document ( pdf ) in the knowledge section.
2. Setup the chunk sizes.
3 Save next 
Sometimes the document is not uploading and stuck in indexing. Once this happens no other document can be uploaded. We saw waeviate logs and it says 
Error: Could not load or initialize schema
