### ISSUE TITLE
Can we have a Snowflake connector? Most organisation will have their data in snowflake and create a bot is essential based on the rich data we have there.

### ISSUE THREAD

**Issue by jaydeepc** [langgenius/dify#5091]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes

### 2. Describe the feature you'd like to see

In the knowledge base section, have an option to add snowflake connection details to use that as a knowledgebase. When we provide connection details, it should fetch the database to choose one and then the normal workflow of creating the bot

### 3. How will this feature improve your workflow or experience?

Most organisation will have their data in snowflake and create a bot is essential based on the rich data we have there.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We do not have the official tool for snowflake, but we are welcome the PRs :). We do have http node which can gather some data from the snowflake service.
