### ISSUE TITLE
Local vs code starts, but gets a bad request?

### ISSUE THREAD

**Issue by luoan7248** [langgenius/dify#5092]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

The error message is as follows. The app.py in the api directory for startup.

/data/Anaconda3/envs/dify/bin/python /home/ai/luoan/dify/dify-main/api/app.py
(dify) (dify) [ai@localhost api]$ /data/Anaconda3/envs/dify/bin/python /home/ai/luoan/dify/dify-main/api/app.py
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
/data/Anaconda3/envs/dify/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
WARNING:root:MAIL_TYPE is not set
 * Serving Flask app 'app'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.2.242:5001
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [12/Jun/2024 03:18:20] "GET / HTTP/1.1" 404 -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:12] code 400, message Bad request version ('\x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:12] "\x01\x00\x00ýÎú\x0b° \x00\x00\x00MMS\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x01\x00\x03\x00ðððð\x0b\x00\x04\x00\x1c\x00\x03\x00N\x00S\x00P\x00l\x00a\x00y\x00e\x00r\x00/\x009\x00.\x000\x00.\x000\x00.\x002\x009\x008\x000\x00;\x00 \x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:17] code 400, message Bad request version ('GetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:17] "\x00\x00\x00\x1f\x00\x00\x00\x00\x00\x00\x00\x0cGetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00" HTTPStatus.BAD_REQUEST -
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:17] "GET / HTTP/1.0" 404 -
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:17] "OPTIONS / HTTP/1.0" 404 -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:17] code 400, message Bad request version ('RTSP/1.0')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:17] "OPTIONS / RTSP/1.0" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:22] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:22] "\x80\x00\x00(rþ\x1d\x13\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86 \x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:27] code 400, message Bad HTTP/0.9 request type ('\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:27] "\x00\x1e\x00\x06\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x07version\x04bind\x00\x00\x10\x00\x03" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:32] code 400, message Bad HTTP/0.9 request type ('\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:20:32] "\x00\x0c\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:18] code 400, message Bad request version ('\x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:18] "\x01\x00\x00ýÎú\x0b° \x00\x00\x00MMS\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x01\x00\x03\x00ðððð\x0b\x00\x04\x00\x1c\x00\x03\x00N\x00S\x00P\x00l\x00a\x00y\x00e\x00r\x00/\x009\x00.\x000\x00.\x000\x00.\x002\x009\x008\x000\x00;\x00 \x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:23] code 400, message Bad request version ('GetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:23] "\x00\x00\x00\x1f\x00\x00\x00\x00\x00\x00\x00\x0cGetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00" HTTPStatus.BAD_REQUEST -
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:23] "GET / HTTP/1.0" 404 -
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:23] "OPTIONS / HTTP/1.0" 404 -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:23] code 400, message Bad request version ('RTSP/1.0')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:23] "OPTIONS / RTSP/1.0" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:28] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:28] "\x80\x00\x00(rþ\x1d\x13\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86 \x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:33] code 400, message Bad HTTP/0.9 request type ('\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:33] "\x00\x1e\x00\x06\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x07version\x04bind\x00\x00\x10\x00\x03" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:38] code 400, message Bad HTTP/0.9 request type ('\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:22:38] "\x00\x0c\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:23:57] code 400, message Bad request version ('\x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:23:57] "\x01\x00\x00ýÎú\x0b° \x00\x00\x00MMS\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x01\x00\x03\x00ðððð\x0b\x00\x04\x00\x1c\x00\x03\x00N\x00S\x00P\x00l\x00a\x00y\x00e\x00r\x00/\x009\x00.\x000\x00.\x000\x00.\x002\x009\x008\x000\x00;\x00 \x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:02] code 400, message Bad request version ('GetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:02] "\x00\x00\x00\x1f\x00\x00\x00\x00\x00\x00\x00\x0cGetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00" HTTPStatus.BAD_REQUEST -
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:02] "GET / HTTP/1.0" 404 -
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:02] "OPTIONS / HTTP/1.0" 404 -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:02] code 400, message Bad request version ('RTSP/1.0')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:02] "OPTIONS / RTSP/1.0" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:07] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:07] "\x80\x00\x00(rþ\x1d\x13\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86 \x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:12] code 400, message Bad HTTP/0.9 request type ('\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:12] "\x00\x1e\x00\x06\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x07version\x04bind\x00\x00\x10\x00\x03" HTTPStatus.BAD_REQUEST -
ERROR:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:17] code 400, message Bad HTTP/0.9 request type ('\x00')
INFO:werkzeug:192.168.1.141 - - [12/Jun/2024 03:24:17] "\x00\x0c\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00" HTTPStatus.BAD_REQUEST -
![image](https://github.com/langgenius/dify/assets/91407577/205fbbb7-7d17-442f-947a-272cfb913dc2)

### ✔️ Expected Behavior

I want to make a request via postman and then dubug on vscode

**Comment by luoan7248** [comment]
request：http://127.0.0.1:5001/console/api/apps/a63814fb-3307-47d0-9038-0be44843f74b/chat-messages

response:
{
    "code": "not_setup",
    "message": "Dify has not been initialized and installed yet. Please proceed with the initialization and installation process first.",
    "status": 401
}

**Comment by luoan7248** [comment]
> request：http://127.0.0.1:5001/console/api/apps/a63814fb-3307-47d0-9038-0be44843f74b/chat-messages
> 
> response: { "code": "not_setup", "message": "Dify has not been initialized and installed yet. Please proceed with the initialization and installation process first.", "status": 401 }

I installed it by deploying the official documentation locally.
The steps used are as follows:

cd docker
docker compose -f docker-compose.middleware.yaml up -d

I don't really want to use front-end tools, just api a back-end service.

**Comment by crazywoola** [comment]
> request：http://127.0.0.1:5001/console/api/apps/a63814fb-3307-47d0-9038-0be44843f74b/chat-messages
> 
> response: { "code": "not_setup", "message": "Dify has not been initialized and installed yet. Please proceed with the initialization and installation process first.", "status": 401 }

You need to use the frontend application to setup an admin account. Then you should be able to use it's service.  Neither the public API for the backend application nor the docs of console api are provided in our service.
