### ISSUE TITLE
[enhancement] Prompt description of question classifier

### ISSUE THREAD

**Issue by 0xff-dev** [langgenius/dify#5111]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

No

### 2. Describe the feature you'd like to see

https://github.com/langgenius/dify/blob/25b0a97851c143a9252594d9949f38334a5b06cb/api/core/workflow/nodes/question_classifier/template_prompts.py#L59

https://github.com/langgenius/dify/blob/25b0a97851c143a9252594d9949f38334a5b06cb/api/core/workflow/nodes/question_classifier/template_prompts.py#L76

According to the description, the input text is in the variable `input_text` not `text_filed`

```diff
- The input text is in the variable text_field. 
+ The input text is in the variable input_text. 
```

### 3. How will this feature improve your workflow or experience?

I am testing the `question classifier` in dify, the function is normal, but I think the description here can be improved.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
:) PR is welcome.
