### ISSUE TITLE
Add support for Xinference ChatTTS 

### ISSUE THREAD

**Issue by lbt981** [langgenius/dify#5118]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Add support for Xinference ChatTTS 

### 2. Describe the feature you'd like to see

Add support for Xinference ChatTTS 

### 3. How will this feature improve your workflow or experience?

Add support for Xinference ChatTTS 

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by liduang** [comment]
+1

**Comment by SotaWork-Tech** [comment]
+1

**Comment by calwang414** [comment]
+1

**Comment by lujin1** [comment]
+1

**Comment by lbt981** [comment]
demands were ignored

**Comment by lbt981** [comment]
Dify only support speech-to-text for Xinference,                 not support text-to-speech for Xinference

**Comment by liduang** [comment]
Please add support for Xinference's TTS models.
