### ISSUE TITLE
Knowledge Retrieval Settings Not Working Correctly

### ISSUE THREAD

**Issue by mdwoicke** [langgenius/dify#5119]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Create a new Knowledge document and select Hybrid Search. Rerank model shows Deprecated and will not allow you to continue without selecting one even though no selection is possible.
 
![image](https://github.com/langgenius/dify/assets/55119044/8c48f4ba-82f7-4e62-9767-ca4aff375d8f)

### ✔️ Expected Behavior

Allow user to select a Rerank Model if selected.

### ❌ Actual Behavior

 Rerank model shows Deprecated and will not allow you to continue without selecting one even though no selection is possible.
 
![image](https://github.com/langgenius/dify/assets/55119044/fec7e802-16c7-4bc0-9ad6-8b787604ff70)

**Comment by crazywoola** [comment]
In this case you should add one or close the switch.

**Comment by mdwoicke** [comment]
Do I add one elsewhere because I cannot add one here?
