### ISSUE TITLE
Error on Conversation with Knowledge Base Agent in Private Deployment Environment

### ISSUE THREAD

**Issue by tonyjiang88215** [langgenius/dify#5120]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a new knowledge base and upload the following document:
```markdown
# 问答示例
Question: 1 + 1 = ?
Anser: 2
```
(It`s pretty simple.)

2. Create a new agent application with the following prompt:
```
# Context #
用户正在使用 使用自然语言来描述自己的需求。

# Objective #
你的任务是理解用户意图，一步一步分析如何达成用户的要求。对每一步分析的过程，要处理的操作，按照以下格式返回：
Thought: 基于当前状态结论分析的接下来的目标。
Action: 结合可用工具，将目标转换为工具的调用。
Observation: 获取工具调用结果以供后续使用。

根据执行结果再进行下一步分析，直至完成要求或终止。

```
(The general idea is to follow the Chain of Thought (CoT) approach to analyze and solve the problem step by step.)

3. Conduct a conversation debug with two interactions:
First input: 5 + 7 = ?
Second input: 1 + 2?

This error does not occur on the Dify site (as shown in the image below).
![image](https://github.com/langgenius/dify/assets/8650041/45378065-f5fb-4b36-8fb3-83dc4f4986a4)

This error occurs in the private local deployment (as shown in the image below).
![image](https://github.com/langgenius/dify/assets/8650041/d48a2bc5-7d20-4ab3-9a41-225dfae25e18)

### ✔️ Expected Behavior

We expect the same behavior as on the Dify site, where multiple rounds of conversation do not result in errors.

### ❌ Actual Behavior

Get an error with ”Got unknown type role=<PromptMessageRole.TOOL: 'tool'>“

**Comment by crazywoola** [comment]
Can you try zhipu in cloud as well?

**Comment by wade30822** [comment]
you used two different models: gpt3.5 in dify.cloud, glm4 in local. the result may be different

**Comment by tonyjiang88215** [comment]
I tried the Zhipu model on the cloud and encountered the same issue. I tried gpt4o locally, and continuous conversations worked without issues. I will close this issue. Appreciate with your reply. 😘
