### ISSUE TITLE
Tool Invoke Error when calling workflow tool from Agent

### ISSUE THREAD

**Issue by PowerBootWS** [langgenius/dify#5134]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Call custom workflow tool from agent.

### ✔️ Expected Behavior

When using an Agent to call a tool, the tool should return a result to the Agent.

### ❌ Actual Behavior

The agent is calling the getAppointmentSlots tool, which is a "workflow" tool.  The variables required by the tool and accurately being provided by the Agent are:
{
  "locationId": "mh0TJaU5Om79BccJXp8k",
  "startDate": "2024-06-17T00:00:00-06:00",
  "endDate": "2024-06-18T00:00:00-06:00",
  "userId": "n7KwEwpkDrl2jpunSZTJ",
  "calendarId": "s3Qj0llo52XLMIvzKN7S",
  "timezone": "America/Edmonton"
}

These are the correct values needed.  The debug is showing the following error when the agent tries to call the tool:

'NoneType' object has no attribute 'items'

When running the tool manually and entering the same provided inputs, the tool returns the expected results.

This has proven to occur with all "workflow" tools, but does not encounter errors with "custom" tools created using an OpenAPI JSON.  Unfortunately, as other steps are required, this tool needs to be a workflow and cannot be created as just a custom tool with a JSON.

**Comment by laipz8200** [comment]
@PowerBootWS Hi! Thanks for reporting the issue. Can you let us know which provider and model you used with this agent? It will help us pinpoint the problem.

**Comment by PowerBootWS** [comment]
The model was GPT-4o with OpenAI.  I did find though that I had the variable defined properly in the agent but not in the tool start point.  Once corrected, the issue was resolved.  Thanks!
