### ISSUE TITLE
localhost don't have the workflow tools

### ISSUE THREAD

**Issue by careylzy** [langgenius/dify#5135]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

<img width="507" alt="image" src="https://github.com/langgenius/dify/assets/37956285/685abaa2-928b-4c49-8e23-8851b12dff9c">
when I use docker to run dify, there is no workflow tools

**Comment by crazywoola** [comment]
You need to make one and publish it as a tool.
