### ISSUE TITLE
The OPENAI configuration is incorrect

### ISSUE THREAD

**Issue by liuyuf** [langgenius/dify#5143]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

curl 'http://localhost/console/api/workspaces/current/model-providers/openai' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: locale=zh-Hans' \
  -H 'Origin: http://localhost' \
  -H 'Referer: http://localhost/apps' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYzRjZTFmMmUtOTMxYi00N2JhLTg0Y2ItNjQ2MTEzYjI4NjNhIiwiZXhwIjoxNzIwODQxMDY2LCJpc3MiOiJTRUxGX0hPU1RFRCIsInN1YiI6IkNvbnNvbGUgQVBJIFBhc3Nwb3J0In0.gtYAzHMV1O3fg-lGRigxpU9cJdtGSGQaQP0hwwdo5gY' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"config_from":"predefined-model","credentials":{"openai_api_key":"sk-3AhfADoAZj3MrnNwhGDIS9IiodFFE24***********","openai_api_base":"https://api.fe8.****"},"load_balancing":{"enabled":false,"configs":[]}}'

The openai_api_key and openai_api_base shown here are encrypted, and the actual openai_api_key and openai_api_base are available in the actual project

### ❌ Actual Behavior

api return：
{
    "code": "invalid_param",
    "message": "Error code: 404 - {'message': ''}",
    "status": 400
}

**Comment by laipz8200** [comment]
It looks like you're directly using our backend API. We haven't found any bugs related to setting the OpenAI API Key, so I'm going to close this issue. If you still have problems, you can provide more details and reopen it.
