### ISSUE TITLE
迭代调用。报错：调用工具失败：达到最大工作流调用深度5。

### ISSUE THREAD

**Issue by dontlove14** [langgenius/dify#5144]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

我写了两个工作流（A,B），然后我将两个工作流发布为工具。然后我在A,B中分别有逻辑会相互调用。但是我可以控制调用的次数。

### ✔️ Expected Behavior

我希望可以相互调用处理问题，以最终输出

### ❌ Actual Behavior

但是实际上我发现相互只能调用一次，如果我让调用两次以上就会报这个异常。再次之前我记得在docker-compose.yml中是有关于循环迭代次数上限的环境变量的设置的，但是现在我怎么找不到了？是删除了吗？如果我想修改这个最大迭代循环次数应该怎么做？
![image](https://github.com/langgenius/dify/assets/54974888/0a3b57b3-5217-483a-9380-c6bbdd5515c0)

**Comment by seasoncool** [comment]
请问这个问题解决了吗？ 我也想将最大迭代次数从5设置到50，不知道在哪里修改。
按照这里的改法，也不起作用，还是5.
https://github.com/langgenius/dify/issues/8692#issuecomment-2368774077

**Comment by vinartis** [comment]
.env 配置里面的WORKFLOW_CALL_MAX_DEPTH=5 ，这个配置
