### ISSUE TITLE
A piece of optimized layout and mouse box selection for batch dragging

### ISSUE THREAD

**Issue by Geek-Bob** [langgenius/dify#5145]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When the volume of business is large, the layout will be a very large effort, and once there is a small change, the entire layout will be moved

### 2. Describe the feature you'd like to see

Recommended flow choreography, add a piece of optimized layout and mouse box selection batch drag. Because when the volume of business is large, the layout will be a very large effort, once there is a small change, the entire layout will be moved. Function can refer to the mind brain map

### 3. How will this feature improve your workflow or experience?

Improve scheduling efficiency

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We have supported it already.
