### ISSUE TITLE
Segment overlap length does not work

### ISSUE THREAD

**Issue by jiandanfeng** [langgenius/dify#5151]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The clips in the preview do not overlap
![image](https://github.com/langgenius/dify/assets/24525960/4a14082c-f72e-49ad-88e0-7f3c19578b50)

**Comment by JohnJyong** [comment]
The delimiter takes precedence. If the length of the divided segment exceeds maxtoken, overlap will only take effect when splitting by maxtoken. @jiandanfeng
