### ISSUE TITLE
Default model not found for ModelType.TEXT_EMBEDDING

### ISSUE THREAD

**Issue by ltm920716** [langgenius/dify#5153]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10-53-gecc7f13

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![1718263587638](https://github.com/langgenius/dify/assets/12007227/18dab856-0c8f-4696-b73e-0f581ddd47cc)

### ✔️ Expected Behavior

run normal

### ❌ Actual Behavior

Default model not found for ModelType.TEXT_EMBEDDING

**Comment by crazywoola** [comment]
Please configure the default embedding model in settings -> model provider -> system models.

**Comment by ltm920716** [comment]
hi @crazywoola ，
thanks for your reply！

I am configuring the inverted index as the screenshot shows, so do I have to configure a vector model？

**Comment by ltm920716** [comment]
> Please configure the default embedding model in settings -> model provider -> system models.

I have verified that it is true that I must configure the embedding model first， even if I do not use it
