### ISSUE TITLE
bug: user cannot normally open the invitation link

### ISSUE THREAD

**Issue by drummerglen** [langgenius/dify#5154]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The URL address for splicing the login invitation email of users must also be configured in the worker environment under services.worker.environment.CONSOLE_WEB_URL in docker-compose.yaml file, as users cannot normally open the invitation link.

### ✔️ Expected Behavior

user normally open the invitation link

### ❌ Actual Behavior

user cannot normally open the invitation link

**Comment by crazywoola** [comment]
So what ddi you get regarding the link?

**Comment by chazzhou** [comment]
The `CONSOLE_WEB_URL` is already under the suggested env variables in the docker-compose.yaml for the worker. A PR to the documents regarding SMTP configuration would be more helpful for this.

**Comment by Jasonon** [comment]
me too
