### ISSUE TITLE
Agent does not do ReAct and not use tools

### ISSUE THREAD

**Issue by ltm920716** [langgenius/dify#5159]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10-53-gecc7f13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

here please
https://github.com/langgenius/dify/discussions/5147

### ✔️ Expected Behavior

Agent does do ReAct and use tools

### ❌ Actual Behavior

Agent does not do ReAct and not use tools

**Comment by crazywoola** [comment]
Can you share the model settings and the ReACT template settings?

**Comment by cuenca7** [comment]
> Can you share the model settings and the ReACT template settings?

I've run into this issue as well. I'm using the SPARK_AI model and the default prompts for ReACT. But, everything works fine when I switch to using gpt.
![微信截图_20240614171600](https://github.com/langgenius/dify/assets/33489228/3fec2def-e4a5-4396-9066-61a4cd027711)

**Comment by ltm920716** [comment]
hi @crazywoola and @cuenca7 ，  
thanks，I think the reason for different ReAct's behavior is that the model's understanding ability，what LLM I use is also spark-lite，and the agent will do better by better model
