### ISSUE TITLE
Can the HTTP interface of self-developed models become a model in Dify model suppliers

### ISSUE THREAD

**Issue by wangyao123456a** [langgenius/dify#5162]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.3.21

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I want to add the HTTP interface of the LLM to the model supplier. Can it be implemented？

### ✔️ Expected Behavior

1

**Comment by crazywoola** [comment]
Yes please refer this readme for more details 
https://github.com/langgenius/dify/blob/793f0c1dd6c38bd5f899bc14eb45d955edf833d3/api/core/model_runtime/README.md#L1

**Comment by wangyao123456a** [comment]
Can the interface be registered and used as LLM？？
