### ISSUE TITLE
glm-4 multi-round session error reporting

### ISSUE THREAD

**Issue by cjdxhjj** [langgenius/dify#5165]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

use glm-4 model, talk with llm several times

### ❌ Actual Behavior

Got unknown type role=<PromptMessageRole.TOOL: 'tool'> content='{"code": "0", "errMsg": null, "data": [{"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3556, "indexName": "猪瘟", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3557, "indexName": "流感", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3558, "indexName": "猪口蹄疫", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3559, "indexName": "圆环病", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3560, "indexName": "猪伪狂犬病", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3561, "indexName": "蓝耳病", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3562, "indexName": "猪流行性腹泻", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3563, "indexName": "猪链球菌病", "indexValue": "0.6667", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3564, "indexName": "猪传染性胸膜肺炎", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3565, "indexName": "发病指数", "indexValue": "0.0000", "dataDate": "2024-06-02"}, {"catalogId": 106, "catalogName": "猪病发病指数", "indexId": 3592, "indexName": "发病指数", "indexValue": "0.66670000", "dataDate": "2024-06-02"}]}' name='get_aigcbasic_pighealth_widthdata_list_all' tool_call_id='95cdb6fe-5735-43bb-9461-3499c37147a3'

**Comment by crazywoola** [comment]
I think it should be fixed in v0.6.11

**Comment by cjdxhjj** [comment]
@crazywoola it appear in 0.6.11, the bug not fixed!
