### ISSUE TITLE
HTTP 请求时，提示403错误

### ISSUE THREAD

**Issue by manoen5** [langgenius/dify#5166]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

使用HTTP节点时，无论配置什么样的API接口地址，都提示403错误。API接口确认是正常可访问的。谢谢！

### ✔️ Expected Behavior

能通过HTTP调有外部API接口

### ❌ Actual Behavior

发生了错误
![image](https://github.com/langgenius/dify/assets/43712256/ad60c05e-f43e-44dd-be66-be69341c6178)

![QQ截图20240613215418](https://github.com/langgenius/dify/assets/43712256/26e3b77c-e504-4834-a185-543c92f70232)

**Comment by crazywoola** [comment]
Close due to #1542
