### ISSUE TITLE
Encountering Errors During `flask db upgrade` After Latest Pull

### ISSUE THREAD

**Issue by XiaoLey** [langgenius/dify#5173]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After creating a new conda environment and pulling the latest code from the main branch of Dify in an empty directory, I encountered the following error when executing `flask db upgrade`:

```
/home/xiaoley/anaconda3/envs/dify/lib/python3.10/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_type" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
...
error: 2 validation errors for WebscraperTool
parameters.2.options.0.value
  Input should be a valid string [type=string_type, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
parameters.2.options.1.value
  Input should be a valid string [type=string_type, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
...
error: 1 validation error for BingSearchTool
parameters.8.options.24.value
  Input should be a valid string [type=string_type, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
...
```

**Steps to Reproduce:**

1. Create a new conda environment:

   ```bash
   conda create -n dify python=3.10
   conda activate dify
   ```

2. Clone the latest main branch code of Dify in an empty directory:

   ```bash
   git clone https://github.com/langgenius/dify.git
   cd dify/api
   ```

3. Install project dependencies:

   ```bash
   pip install -r requirements.txt
   ```

4. Execute the database migration command:

   ```bash
   flask db upgrade
   ```

### ✔️ Expected Behavior

The database migration command should execute successfully without any errors.

### ❌ Actual Behavior

As described above, Pydantic field validation errors and namespace conflict warnings were encountered.

## Additional Information:

This issue did not occur previously and is suspected to be related to a recent commit that updated the Pydantic version (potentially PR #4592). However, this has not been confirmed yet.

I hope this issue can be resolved soon as I was planning to start enhancing the Jina tool integration but am currently unable to proceed due to this issue.

Thank you very much!

**Comment by bowenliang123** [comment]
Hi, the db migration commands works well in CI jobs with the latest fixes for Pydantic 2.x migration in #5171.
CI logs:
https://github.com/langgenius/dify/actions/runs/9507160967/job/26205995254?pr=5176#step:8:1

Would you like to try again on the latest commit of the main branch?

**Comment by crazywoola** [comment]
Can not produce this, I just tried this morning.

```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2024-06-14 00:36:14.908 WARNING [MainThread] [extensible.py:71] - Missing cloud_service.py file in /Users/Li.Zheng/Program/dify/api/core/moderation/cloud_service, Skip.
2024-06-14 00:36:14.912 WARNING [MainThread] [extensible.py:71] - Missing weather_search.py file in /Users/Li.Zheng/Program/dify/api/core/external_data_tool/weather_search, Skip.
2024-06-14 00:36:14.916 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

**Comment by XiaoLey** [comment]
> Can not reproduce this problem, I just tried this command morning.
> 
> ```
> None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> 2024-06-14 00:36:14.908 WARNING [MainThread] [extensible.py:71] - Missing cloud_service.py file in /Users/Li.Zheng/Program/dify/api/core/moderation/cloud_service, Skip.
> 2024-06-14 00:36:14.912 WARNING [MainThread] [extensible.py:71] - Missing weather_search.py file in /Users/Li.Zheng/Program/dify/api/core/external_data_tool/weather_search, Skip.
> 2024-06-14 00:36:14.916 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set
> INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
> INFO  [alembic.runtime.migration] Will assume transactional DDL.
> ```

It appears that this issue has already been fixed a few hours ago. I have now pulled the latest code from the main branch and it works fine.

Thanks!

**Comment by bowenliang123** [comment]
👍🏻 Credit goes to @takatost .
