### ISSUE TITLE
Problem classifier, cannot classify by context

### ISSUE THREAD

**Issue by Geek-Bob** [langgenius/dify#5182]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create two categories and turn on memory:
 1. Timing function
 2. Other

Steps to reproduce:
The first time you say: "I say minutes, you help me to uniformly convert to seconds", chatflow will classify to "other".
The second time you say "5 minutes", chatflow classifies to "timing function".

### ✔️ Expected Behavior

Comprehensive classification based on historical dialogue and context, rather than simply based on current text. Because it would lose the charm of the LLM.

### ❌ Actual Behavior

On the conversation alone, the experience is very poor

**Comment by seamys** [comment]
This component only takes last mesage with no context. it needs to get enhancement

**Comment by kun321** [comment]
![image](https://github.com/langgenius/dify/assets/124553455/7a32c72f-fb1c-44a7-84bc-2224e4cf3348)
you can find the memory option, visit https://docs.dify.ai/v/zh-hans/guides/workflow/node/question_classifier

**Comment by JokerQyou** [comment]
What are you talking about? There's no memory option in advanced settings, also there is no `sys.query` variable for workflows' start block. This is from latest (`main` branch on `00b4cc3cd44439d933a38d0ca28fde9b5c350a05`) and using latest images (`langgenius/dify-web:0.6.12-fix1`).
![image](https://github.com/langgenius/dify/assets/1465267/b0cb94d7-8ad2-4415-b890-3a4ccdd01c97)

Care to share your version? @kun321

**Comment by crazywoola** [comment]
Is this issue resolved?

**Comment by JokerQyou** [comment]
I think so.

**Comment by Geek-Bob** [comment]
> 这个问题解决了吗？

This problem still exists, even though I write prompt words and turn on memory in the advanced level, requiring classification based on historical conversations, it still doesn't work

**Comment by Geek-Bob** [comment]
I guess the reason is that the classifier only classifies based on the most recent tasks and doesn't refer to the history of the conversation within the <histories>XML tags
