### ISSUE TITLE
知识库添加文档一直在排队

### ISSUE THREAD

**Issue by superbread93a** [langgenius/dify#5184]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![Image_20240614101627](https://github.com/langgenius/dify/assets/46621371/d571f5da-e115-4950-b909-2c524768bb7b)
![image](https://github.com/langgenius/dify/assets/46621371/08c05970-8c74-414f-a49f-889afdccd735)
知识库添加文档一直在排队和等待
![image](https://github.com/langgenius/dify/assets/46621371/74dc3db6-2518-4d41-bd7c-1f9fddf85855)
平台一直在发送这个请求，且智能体无法进行对话

### ✔️ Expected Behavior

如何解决问题，重启服务还是无法解决

**Comment by doufa** [comment]
@superbread93a Have you started the worker service as referenced in api/README.md?

9. If you need to debug local async processing, please start the worker service by running 
`celery -A app.celery worker -P gevent -c 1 --loglevel INFO -Q dataset,generation,mail`.
The started celery app handles the async tasks, e.g. dataset importing and documents indexing.

**Comment by piwawa** [comment]
> Ensure that the `BATCH_UPLOAD_LIMIT` and vector space limits are configured correctly in your `current_app.config`. Additionally, check the logs for any exceptions that might be causing the documents to remain in a queued state [[1]](https://github.com/langgenius/dify/blob/main/api/tasks/document_indexing_task.py).

怎么修改这个 vector_space.limit ？在 `dify/docker/.env.example` 里没有相关设置
