### ISSUE TITLE
The OpenAPI description of the custom tool does not seem to support JSON arrays.

### ISSUE THREAD

**Issue by naonaolerobi** [langgenius/dify#5191]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I was trying to define a custom tool which has a array jsonbody. But the tool simlator cannot recongnized as a array jsonbody request. Has anyone encountered a similar scenario? If you have a solution, it would be greatly appreciated.
The openapi description as delow:
openapi: 3.1.0
info:
  title: test LLM to fulfill the json
  description: test LLM to fulfill the json
  version: v1.0.0
servers:
  - url: http://x.x.x.x:80
paths:
  /println:
    post:
      description:  test LLM to fulfill the json
      operationId:  test LLM to fulfill the json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  component:
                    type: string
                    example: "MYSQL"
                  cpu:
                    type: string
                    example: "4"
                  ip:
                    type: string
                    example: "127.0.0.1"
                  memory:
                    type: string
                    example: "16"
                  storage:
                    type: string
                    example: "20"
But the tool looks like not work.
![image](https://github.com/langgenius/dify/assets/12195757/ae80ef57-3ddd-4ecb-9ce6-fe3ac6f4591d)

**Comment by crazywoola** [comment]
Do not support array[object] I think, you could change to array[number] or array[string] to see if it works.

**Comment by naonaolerobi** [comment]
> Do not support array[object] I think, you could change to array[number] or array[string] to see if it works.

And then still cannot support even use the array[string]. Any other ideas for this issue?：)

**Comment by elvis-cai** [comment]
+1 had the same issue

**Comment by soichisumi** [comment]
Even array[string], it doesn't work.
This api is not recognized as input of custom tool.
![image](https://github.com/user-attachments/assets/cc52e385-7043-43ed-a9a8-a00b0993c840)

**Comment by hh2712** [comment]
Has this problem been sorted out in the latest version? I had same issue as posted where custom tool variable in array of string cannot be identified in the canvas tool node. Please kindly let us know if there is a way around it.
