### ISSUE TITLE
Workflows created using customization cannot be published as tools, showing validation errors for ToolParameter

### ISSUE THREAD

**Issue by Sakura4036** [langgenius/dify#5192]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10+ latest commit: ed53ef29f4bbe0333a131c408881b458c1d3be68

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1.  Creating a workflow: using Google search tool
2. Click on "Publish"
3. Select "Publish as Tool"
4. Fill in the tool information
5. Click "Save" button

### ✔️ Expected Behavior

1. save workflow as tool success

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/42060616/6b6ee558-76a0-4a3a-8937-7aae7fc56e94)

**Comment by Sakura4036** [comment]
@dosu workfolw as tool works fine in Dify version 0.6.10, not in commit ed53ef29f4bbe0333a131c408881b458c1d3be68. I  think this is a bug that needs to be fixed. 
I think this is a bug that needs to be fixed. And the workflow tools I published in version 0.6.10 are missing!
![image](https://github.com/langgenius/dify/assets/42060616/e157ee4d-cfd3-40f7-9b30-5e54e60a9984)

**Comment by Sakura4036** [comment]
Rolled back to version 0.6.10, everything is working fine and my workflow tools are back!

**Comment by crazywoola** [comment]
The main branch is not ready for prod, please keep using the latest v0.6.10.

**Comment by Sakura4036** [comment]
yes, but this bug need to be fixed.

**Comment by crazywoola** [comment]
We are working on this.
