### ISSUE TITLE
Load balancer has conflict

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#5193]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

UserWarning: Field "model_load_balancing_enabled" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.

**Comment by takatost** [comment]
Already fixed, thx!
 https://github.com/langgenius/dify/blob/8e2f8ffb9e2e96d54f43b7038363cbe82ee166b0/api/services/feature_service.py#L23-L35
