### ISSUE TITLE
系统模型设置中部分类型模型：no model found for "",不能选择模型

### ISSUE THREAD

**Issue by chenqp** [langgenius/dify#5199]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

添加了Xinference模型，LLM:glm4-chat, embedding : bge-large-zh-1.5 , 但在系统模型设置中系统推理模型一直是：no model found for "",不能选择模型。语音转文本也有这种情况。然后在编排界面就提示LLM提供着密钥未设置
![1](https://github.com/langgenius/dify/assets/8595915/ca78f9c7-40d5-4c16-af06-4848edbac3fe)
![2](https://github.com/langgenius/dify/assets/8595915/25fa933f-2d24-444f-aacd-700d3ba45c45)
![3](https://github.com/langgenius/dify/assets/8595915/d6088f25-d2e6-48a6-b64c-5b4a2aba213e)

**Comment by alanpeng** [comment]
0.6.10和0.6.11都有这个问题，机器人回复的没关联性吧？以前的版本部署好，不做任何设定，系统模型菜单里是能列出所有可配置的模型条目的。现在全部提示no model found for ""

**Comment by Johnnydaszhu** [comment]
0.8.1 也有这个问题了
