### ISSUE TITLE
点击设置，弹框无法关闭，其它 TAB 无法点击

### ISSUE THREAD

**Issue by yabea** [langgenius/dify#52]
【个人】-【设置】，弹框无法正常关闭，其它 TAB 无法点击。

![image](https://github.com/langgenius/dify/assets/15773461/1c0121fc-2b00-4313-aa1b-8ec9e707c7e7)

**Comment by yabea** [comment]
没有报错哈，应该是适配的问题，我缩小浏览器比例之后发现了关闭按钮。
可能需要前端同学看下是否需要调整优化下。

![image](https://github.com/langgenius/dify/assets/15773461/aa12ad16-d298-402d-8fd4-4d14e3542d74)

**Comment by zxhlyh** [comment]
> 没有报错哈，应该是适配的问题，我缩小浏览器比例之后发现了关闭按钮。 可能需要前端同学看下是否需要调整优化下。
> 
> ![image](https://user-images.githubusercontent.com/15773461/238639946-aa12ad16-d298-402d-8fd4-4d14e3542d74.png)

好的，感谢。近期会做优化。

**Comment by zxhlyh** [comment]
已修复
