### ISSUE TITLE
publish workflow report an error

### ISSUE THREAD

**Issue by cjdxhjj** [langgenius/dify#5204]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

click the publish button at workflow design page

### ❌ Actual Behavior

2 validation errors for ToolParameter label Input should be a valid dictionary or instance of I18nObject [type=model_type, input_value=I18nObject(zh_Hans='input...xt', en_US='input Text'), input_type=I18nObject] For further information visit https://errors.pydantic.dev/2.7/v/model_type human_description Input should be a valid dictionary or instance of I18nObject [type=model_type, input_value=I18nObject(zh_Hans='用...', en_US='用户问题'), input_type=I18nObject] For further information visit https://errors.pydantic.dev/2.7/v/model_type

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5192
