### ISSUE TITLE
workflow query did not return results,but recall test was successful.

### ISSUE THREAD

**Issue by tzdmwwdz** [langgenius/dify#5207]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

 Sometimes in the workflow, the query did not return any results, but the backend knowledge base received the query and there was no issue with the recall during testing.

### ✔️ Expected Behavior

The query information in the workflow and the recall results from the knowledge base are consistent.

### ❌ Actual Behavior

![图片](https://github.com/langgenius/dify/assets/16332159/dfd89d64-0d30-4ed4-b67f-4ac0d28274fe)
![图片](https://github.com/langgenius/dify/assets/16332159/d9d8736f-0384-4e03-a70d-048df39992b6)

**Comment by tzdmwwdz** [comment]
![图片](https://github.com/langgenius/dify/assets/16332159/733a44d2-cf6b-4212-b12b-31d2e4168dcb)
The multi-path recall is already in use.

**Comment by tzdmwwdz** [comment]
The configuration should not be the problem. This is because some queries are able to return correct results from the knowledge base.
![图片](https://github.com/langgenius/dify/assets/16332159/e07babbb-6c07-46be-821a-b6c63c9559cb)

**Comment by jinec** [comment]
@tzdmwwdz  问题解决了吗？我也遇到了这个问题。。一点头绪没有啊
