### ISSUE TITLE
raise err when run workflow as tool

### ISSUE THREAD

**Issue by hjlarry** [langgenius/dify#5211]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. create a simplest workflow
2. config the workflow as tool
3. click save btn

Like my screenshot:
![test_parameter - Dify](https://github.com/langgenius/dify/assets/25834719/5dc37819-3021-4109-b704-d00fbd013f45)

It will raise:
```
{
    "code": "invalid_param",
    "message": "2 validation errors for ToolParameter\nlabel\n  Input should be a valid dictionary or instance of I18nObject [type=model_type, input_value=I18nObject(zh_Hans='p1', en_US='p1'), input_type=I18nObject]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nhuman_description\n  Input should be a valid dictionary or instance of I18nObject [type=model_type, input_value=I18nObject(zh_Hans='test_... en_US='test_parameter'), input_type=I18nObject]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type",
    "status": 400
}
```

I upgrade my dify to the newest github version and raise this issue.

**Comment by hjlarry** [comment]
It seems maybe the pydanic upgrade causes, can you reproduce it?   @takatost @bowenliang123

**Comment by crazywoola** [comment]
It has been fixed in this pr https://github.com/langgenius/dify/pull/5205
