### ISSUE TITLE
Weaviate outdated server and client version

### ISSUE THREAD

**Issue by agonbina** [langgenius/dify#5214]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Trying to use some new native Weaviate features is not possible in combination with Dify because Dify is using v1.19.0 but there is already v1.25 available.

### 2. Describe the feature you'd like to see

Upgrade the weaviate server version, which requires upgrading the `weaviate-client` from v3 to v4 (see guide: https://weaviate.io/developers/weaviate/client-libraries/python/v3_v4_migration#installation)

### 3. How will this feature improve your workflow or experience?

Use new features of Weaviate and keep Dify updated with important security updates etc from Weaviate.

### 4. Additional context or comments

I tried upgrading the weaviate-client myself but unfortunately I don't have any experience with Python and failed miserably :( 

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by breakstring** [comment]
Please consider upgrading the Qdrant version as well. 
Additionally, I noticed you are using a custom-built image(langgenius/qdrant:v1.7.3) in the Docker Compose file, . What are the differences between this image and the official image of the same version(qdrant/qdrant:v1.7.3)? Are there any modifications made by the Dify team? 
@crazywoola @takatost

**Comment by crazywoola** [comment]
@JohnJyong
