### ISSUE TITLE
Azure供应商进行高质量文档嵌入报错

### ISSUE THREAD

**Issue by yslhellolsy** [langgenius/dify#522]
1.模型供应商: Azure
2.数据集中进行文档上传高质量嵌入

错误提示: AzureOpenAI InvalidRequestError: Too many inputs. The max number of inputs is 1

**azure 不支持批量嵌入 chunk_size 设置为 1**

azure 文档
https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/faq#i-am-trying-to-use-embeddings-and-received-the-error--invalidrequesterror--too-many-inputs--the-max-number-of-inputs-is-1---how-do-i-fix-this-
![image](https://github.com/langgenius/dify/assets/37207412/ae2e1767-c177-4e8d-ad35-869e72649898)

**Comment by takatost** [comment]
We've solved the problem by modifying the Azure embedding batch size to 1, thanks for your feedback 
refer: #530
