### ISSUE TITLE
KB original file dont delete

### ISSUE THREAD

**Issue by zyc130130** [langgenius/dify#5220]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Delete the knowledge base files, but the original files are still present in the "docker" directory under the "volumes" section.

**Comment by JohnJyong** [comment]
mark it to the feature list

**Comment by JohnJyong** [comment]
@zyc130130  it has fixed， pr below：
https://github.com/langgenius/dify/pull/5882
