### ISSUE TITLE
Call knowledge Base delete api got error in workflow

### ISSUE THREAD

**Issue by dwgeneral** [langgenius/dify#5221]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. I build a HTTP node in workflow
2. add knowledge retrieval node and hit the record successfully
3. add the python code node to parse the database_id, document_id, segment_id,
4. add delete knowledge base segments with api call
5. got error: Node knowledge 1 run failed: argument of type 'NoneType' is not iterable
6. I confirmed that the database_id, document_id, segment_id are correct
![Screenshot 2024-06-14 at 7 19 56 PM](https://github.com/langgenius/dify/assets/8654993/42d00c32-3131-4f59-9979-8370e2d155dd)

### ✔️ Expected Behavior

should delete the segment in knowledge base successfully

### ❌ Actual Behavior

got error: Node knowledge 1 run failed: argument of type 'NoneType' is not iterable

**Comment by crazywoola** [comment]
I think this should be fixed today #5179
