### ISSUE TITLE
Sandbox cuts off part of the response

### ISSUE THREAD

**Issue by dailydaniel** [langgenius/dify#5231]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Creating a work flow with a code block (Python) and as input variable string with large text

### ✔️ Expected Behavior

Сorrect code execution in the sandbox and response parsing

### ❌ Actual Behavior

Сutting off part of the response from the sandbox, which is why the regular expression in the transform_response function does not work (the part of the response with the closing RESULT tag is cut off) and the error “CodeBlock_name run failed: Failed to parse result” appears. 
Problem in sandbox.

**Comment by dailydaniel** [comment]
There is no CODE_MAX_STRING_LENGTH in docker-compose.yaml in the sandbox section. I also increased this variable everywhere (in the environment and other files), the result did not change.

**Comment by mkaskov** [comment]
I have the same issue with long data

**Comment by xixici** [comment]
same +1

**Comment by crazywoola** [comment]
Try set this environment variable

https://github.com/langgenius/dify/blob/c436454cd45d208c2494556d1d21311aaaaa3494/api/configs/app_config.py#L60

**Comment by xixici** [comment]
It doesn't work well.

**Comment by orangeclk** [comment]
I think it has been fixed by https://github.com/langgenius/dify-sandbox/pull/41. This issue can be closed. @crazywoola

**Comment by hxuaj** [comment]
same issue here, it's not fixed

**Comment by hxuaj** [comment]
Just so anyone interested, I resolved long data restraint issue by setting CODE_MAX_STRING_LENGTH in /docker/.env file. After setting it, restart the service.

**Comment by LeeeeeeM** [comment]
It doesn't work well.
