### ISSUE TITLE
Documents cannot be deleted when 'clean_dataset_task' is executed.

### ISSUE THREAD

**Issue by chubxu** [langgenius/dify#524]
Dify version: Self Host

## Steps To Reproduce

1. Delete a dataset, and then check documents data table, the data has not been deleted.
2. The problem may occur in `clean_dataset_task.py`, line 35

## The current behavior
```py
documents = db.session.query(DocumentSegment).filter(DocumentSegment.dataset_id == dataset_id).all()
```

## The expected behavior
```py
documents = db.session.query(Document).filter(Document.dataset_id == dataset_id).all()
```

I do not know if it's a bug or there is something I do not notice?

**Comment by JohnJyong** [comment]
We've fixed the issue. Thanks for using and spotting it! 🙏
