### ISSUE TITLE
Added the function of calling the same LLM multiple times in one process

### ISSUE THREAD

**Issue by lins0621** [langgenius/dify#5241]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Example:
### **Normal Process:**
For example:

-  ask about the weather in city A today. The process calls LLM, and LLM feedbacks that it cannot search and what it needs to search for. The process calls the search engine to obtain knowledge. The process brings the knowledge and then calls LLM, and finally feedbacks the weather.

- If the user asks again: What about city B? . In the same way, the process calls LLM, and LLM feedbacks that it cannot search, and **combines historical message feedback with what it needs to search for**. The process calls the search engine to obtain knowledge. The process brings the knowledge and then calls LLM, and finally feedbacks the weather.

### **DIFY common processes:**

- For example, ask about the weather in city A today. The process calls the process search to obtain the weather. The process brings the knowledge and then calls LLM, and finally the weather is fed back.

- However, if the user asks, what about city B? If the search engine is called and the weather results cannot be obtained, multiple rounds of dialogue will fail.

### 2. Describe the feature you'd like to see

Added the function of calling the same LLM multiple times in one process, and multiple calls can still carry historical information

### 3. How will this feature improve your workflow or experience?

When the LLM model cannot answer a question well, the LLM model assembles the questions that require the information it wants to know, calls plug-ins, knowledge bases, tools, etc. to obtain the information and output accurate answers. Can complete tasks better

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I think you can turn on the memory in the LLM node.
<img width="432" alt="image" src="https://github.com/user-attachments/assets/19e1e0b3-55c7-461f-a62c-44bc6120c77c">
