### ISSUE TITLE
Error when using DuckDuckGo image search tool

### ISSUE THREAD

**Issue by shelltea** [langgenius/dify#5244]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Use Dify version 0.6.11.
2. Use the DuckDuckGo image search tool.
3. Set the image search count to 10 or more.
4. Observe the error message.

### ✔️ Expected Behavior

The tool should return the requested number of images without error.

### ❌ Actual Behavior

An error occurs:

```
2024-06-15 04:35:17.235 ERROR [Thread-15 (_generate_worker)] [app_generator.py:207] - Unknown Error when generating
Traceback (most recent call last):
  File "/app/api/core/app/apps/agent_chat/app_generator.py", line 186, in _generate_worker
    runner.run(
  File "/app/api/core/app/apps/agent_chat/app_runner.py", line 247, in run
    self._handle_invoke_result(
  File "/app/api/core/app/apps/base_app_runner.py", line 266, in _handle_invoke_result
    self._handle_invoke_result_stream(
  File "/app/api/core/app/apps/base_app_runner.py", line 300, in _handle_invoke_result_stream
    for result in invoke_result:
  File "/app/api/core/agent/fc_agent_runner.py", line 254, in run
    message_file_id=message_file.id
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 796, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1603, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <MessageFile at 0xffff6ca65840> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2024-06-15 04:35:17.382 ERROR [Dummy-16] [base_app_generate_response_converter.py:128] - Instance <MessageFile at 0xffff6ca65840> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
```

**Comment by crazywoola** [comment]
@hjlarry Please take a look at this.

**Comment by hjlarry** [comment]
Hi, I have tried set 10 images.
In the workflow mode, it works well.
In the agent mode, it often raise errors.

I reviewed the entire agent logic,  and not found clear reasons for what cause this db session lost issue, maybe the download process waste too much time?
But when I add this code at the error occurs place , it works.
```
try:
    message_file.id
except:
    message_file = db.session.merge(message_file)
# publish message file
self.queue_manager.publish(QueueMessageFileEvent(
    message_file_id=message_file.id
), PublishFrom.APPLICATION_MANAGER)
```
![1718508146954](https://github.com/langgenius/dify/assets/25834719/fb18f476-a477-4aeb-accf-43bb1cead33b)


BTW, I don't think it is a good way to fix this. When I develop this tool, I found that the api of Tool like `create_image_messages` is friendly for the image gen of LLM. But here duckduckgo is an image search tool, use this api will download each search results like a crawler, and the search result is often not reliable, it maybe very big, maybe not allow user to download, maybe expired. So I'd like to add more api of tool like `create_json_messages`, What do you guys think about this?

**Comment by shelltea** [comment]
> Hi, I have tried set 10 images.你好，我已经尝试设置 10 张图像。 In the workflow mode, it works well.在工作流模式下，效果很好。 In the agent mode, it often raise errors.在代理模式下，经常会出现错误。
> 
> I reviewed the entire agent logic, and not found clear reasons for what cause this db session lost issue, maybe the download process waste too much time?我检查了整个代理逻辑，没有找到导致此数据库会话丢失问题的明确原因，也许下载过程浪费了太多时间？ But when I add this code at the error occurs place , it works. 但是当我在错误发生的地方添加这段代码时，它就起作用了。
> 
> ```
> try:
>     message_file.id
> except:
>     message_file = db.session.merge(message_file)
> # publish message file
> self.queue_manager.publish(QueueMessageFileEvent(
>     message_file_id=message_file.id
> ), PublishFrom.APPLICATION_MANAGER)
> ```
> 
> ![1718508146954](https://private-user-images.githubusercontent.com/25834719/340063501-fb18f476-a477-4aeb-accf-43bb1cead33b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODYwMzIsIm5iZiI6MTcxODU4NTczMiwicGF0aCI6Ii8yNTgzNDcxOS8zNDAwNjM1MDEtZmIxOGY0NzYtYTQ3Ny00YWViLWFjY2YtNDNiYjFjZWFkMzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAwNTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OWY5N2NjMjE3YWFmZTlhZmY5OTY5MmFhNmMxYWRiZTM3NThhODVkNGFmNTk4M2I2MDk2NmIzYWE2OGViMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TqKutrdhvNsY0rLwH0Ucr-b-hrEDVnDRywpzhK25u0U)
> 
> BTW, I don't think it is a good way to fix this. When I develop this tool, I found that the api of Tool like `create_image_messages` is friendly for the image gen of LLM. But here duckduckgo is an image search tool, use this api will download each search results like a crawler, and the search result is often not reliable, it maybe very big, maybe not allow user to download, maybe expired.顺便说一句，我认为这不是解决这个问题的好方法。当我开发这个工具时，我发现像 `create_image_messages` 这样的Tool api对于LLM的图像生成是友好的。但这里的duckduckgo是一个图片搜索工具，使用这个api会像爬虫一样下载每个搜索结果，而搜索结果往往不可靠，可能很大，可能不允许用户下载，可能过期了。 So I'd like to add more api of tool like `create_json_messages`, What do you guys think about this? 所以我想添加更多像 `create_json_messages` 这样的工具 API，你们对此有何看法？

 I agree with your opinion, this tool only needs to return the search results and does not need to download the images that are found.
