### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by kokojacket** [langgenius/dify#5255]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

![image](https://github.com/langgenius/dify/assets/74887370/4c518227-4097-41b8-b9da-93400d917d16)
It should be dify instead of docker

**Comment by kebotbmfl** [comment]
# #

**Comment by crazywoola** [comment]
It depends how you name the container actually.
