### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Guirds** [langgenius/dify#526]
I'm unable to access the API, I receive this message every time I attempt to connect: 

{"status":"rejected","reason":{"message":"500 - \"{\\\"message\\\": \\\"Internal Server Error\\\", \\\"code\\\": \\\"unknown\\\"}\\n\"","name":"Error","stack":"Error: 500 - \"{\\\"message\\\": \\\"Internal Server Error\\\", \\\"code\\\": \\\"unknown\\\"}\\n\"\n    at createError (/app/code/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/code/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/code/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:525:35)\n    at RedirectableRequest.emit (node:domain:489:12)\n    at RedirectableRequest._processResponse (/app/code/node_modules/follow-redirects/index.js:356:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/code/node_modules/follow-redirects/index.js:62:10)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)"}}

Dify version: Cloud

## Steps To Reproduce

I'm using this POST request:
curl --location --request POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer MY-API-KEY' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "query": "New Chat",
    "response_mode": "streaming",
    "conversation_id": "",
    "user": "abc-123"
}'

**Comment by takatost** [comment]
Sorry about that, according to the time you mentioned, it might be that our database was full at that time, and we have already upgraded to solve it.
