### ISSUE TITLE
When running Python code through a code execution tool, passing in an excessively long string can cause parsing to fail.

### ISSUE THREAD

**Issue by wdmzjxzl** [langgenius/dify#5261]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After accessing an interface using an HTTP request to get data, I passed the body as a variable to a code execution tool (Python) and used Python's json library to parse the JSON data. However, the variable string is too long, approximately 1 million in length. I adjusted the CODE_MAX_STRING_LENGTH value in the docker-compose.yaml file, but it still doesn't take effect. Why is this happening? How should I handle this situation?
error_msg is：Node 代码执行 run failed: Failed to parse result
![截图 2024-06-15 21-47-45](https://github.com/langgenius/dify/assets/36881585/aed898d6-f43a-4c55-86c9-0ba692682a92)
![截图 2024-06-15 21-57-58](https://github.com/langgenius/dify/assets/36881585/e7782d44-7a82-4334-82da-5c7c37e81aca)
![截图 2024-06-15 21-58-38](https://github.com/langgenius/dify/assets/36881585/e657d855-253b-4fab-9fb3-87968c9530fc)

### ✔️ Expected Behavior

I hope to pass in the extremely long string and still be able to parse it normally in Python code.

### ❌ Actual Behavior

An error occurred, and the Python code could not execute properly.

**Comment by wdmzjxzl** [comment]
@dosu
The Python code in the code execution tool is:

def main(arg1):
    import json
    return {
        "result": json.loads(arg1)
    }
The input variable is the string from the HTTP response body, which is a string in the format list[dict]. I need to parse it using Python.

However, when I execute json.loads(arg1), I get the error: Node code execution run failed: Failed to parse result.

But when I execute str(len(long_string)), I am able to print out the length of the string, so it might not be an issue of the input string being too long. How should I solve this problem?

**Comment by wdmzjxzl** [comment]
@dosu
I don't want the code to run in a sandbox environment, what should I do?

**Comment by wdmzjxzl** [comment]
@dosu
In the code execution tool, my code body looks like this:

def main(arg1):
    return {
        "result": arg1
    }
I set the input variable as a string with a length of over 700,000 characters. Then, I use this method to return the passed variable. The output variable is result. After executing the code, the console still reports an error: Node code execution run failed: Failed to parse result.

**Comment by shengbox** [comment]
I encountered the same issue with the Book Translation example on https://cloud.dify.ai/. It occurs occasionally, with an error appearing roughly once every 10 runs.
<img width="913" alt="截屏2024-06-15 23 14 31" src="https://github.com/langgenius/dify/assets/3329461/010c0aac-8bf8-4399-a29e-1d82db768c06">

**Comment by shengbox** [comment]
I did not use the Docker environment; instead, I encountered the same issue while using https://cloud.dify.ai. Additionally, the same data does not always result in an error. @dosu.

**Comment by crazywoola** [comment]
We do not suggest passing a such long context to our code node, because it's meant to be a lightweight solution. You should breakdown the complex tasks into smaller one.

**Comment by achenglike** [comment]
> We do not suggest passing a such long context to our code node, because it's meant to be a lightweight solution. You should breakdown the complex tasks into smaller one.

It's not that the code is long, but that the returned data is long.
