### ISSUE TITLE
can not build web project

### ISSUE THREAD

**Issue by lichengwu** [langgenius/dify#5269]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

 npm run build

> dify-web@0.6.11 build
> next build

   ▲ Next.js 14.1.0
   - Environments: .env.local

   Creating an optimized production build ...

 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
 ✓ Collecting page data
   Generating static pages (1/14)  [=== ]
ReferenceError: window is not defined
    at /Users/lichengwu/Codes/ai/dify/web/.next/server/chunks/232.js:1:22278
    at 93316 (/Users/lichengwu/Codes/ai/dify/web/.next/server/chunks/232.js:1:22686)
    at t (/Users/lichengwu/Codes/ai/dify/web/.next/server/webpack-runtime.js:1:142)
    at 73339 (/Users/lichengwu/Codes/ai/dify/web/.next/server/chunks/1794.js:133:10459)
    at t (/Users/lichengwu/Codes/ai/dify/web/.next/server/webpack-runtime.js:1:142)
    at 58084 (/Users/lichengwu/Codes/ai/dify/web/.next/server/app/(commonLayout)/tools/page.js:1:11693)
    at t (/Users/lichengwu/Codes/ai/dify/web/.next/server/webpack-runtime.js:1:142)
    at F (/Users/lichengwu/Codes/ai/dify/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94693)
    at /Users/lichengwu/Codes/ai/dify/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:97108
    at W._fromJSON (/Users/lichengwu/Codes/ai/dify/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:97546)

Error occurred prerendering page "/tools". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: window is not defined
    at /Users/lichengwu/Codes/ai/dify/web/.next/server/chunks/232.js:1:22278
    at 93316 (/Users/lichengwu/Codes/ai/dify/web/.next/server/chunks/232.js:1:22686)
    at t (/Users/lichengwu/Codes/ai/dify/web/.next/server/webpack-runtime.js:1:142)
    at 73339 (/Users/lichengwu/Codes/ai/dify/web/.next/server/chunks/1794.js:133:10459)
    at t (/Users/lichengwu/Codes/ai/dify/web/.next/server/webpack-runtime.js:1:142)
    at 58084 (/Users/lichengwu/Codes/ai/dify/web/.next/server/app/(commonLayout)/tools/page.js:1:11693)
    at t (/Users/lichengwu/Codes/ai/dify/web/.next/server/webpack-runtime.js:1:142)
    at F (/Users/lichengwu/Codes/ai/dify/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94693)
    at /Users/lichengwu/Codes/ai/dify/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:97108
 ✓ Generating static pages (14/14)

> Export encountered errors on following paths:
	/(commonLayout)/tools/page: /tools

### ✔️ Expected Behavior

build success

### ❌ Actual Behavior

build fail

**Comment by from2001** [comment]
Hi, @guchenhe @crazywoola @iamjoel
Thank you for the great project. I love it so much.

I also couldn't build the web project on the main branch. (Source code of the latest v0.6.11 release worked.)

How about changing the default branch to develop, asking contributors to make pull requests to the develop branch, and keeping the main branch the same as the latest release code? This way, developers can choose to clone the working release code or the latest development code.

I appreciate your great work and would like to contribute more to the project. Thank you.

**Comment by crazywoola** [comment]
Hello @from2001 @lichengwu What is your current node version?

I tested it can be built by using 20.14.0.
It fails in 21.x.

I suggest you guys use 20.14 LTS version to build it.

Ref: https://github.com/langgenius/dify/blob/5f7321ea28155982be9370bc84791d62163352b5/web/Dockerfile#L2

**Comment by from2001** [comment]
My node version is v20.10.0
I'll try it with the supported version.
Thanks.

**Comment by lichengwu** [comment]
> Hello @from2001 @lichengwu What is your current node version?
> 
> I tested it can be built by using 20.14.0. It fails in 21.x.
> 
> I suggest you guys use 20.14 LTS version to build it.
> 
> Ref:
> 
> https://github.com/langgenius/dify/blob/5f7321ea28155982be9370bc84791d62163352b5/web/Dockerfile#L2

v22.0.0

**Comment by crazywoola** [comment]
Please try this `FROM node:20.11-alpine3.19 AS base` to build project again. We will support higher node version later.

**Comment by wangzihchao** [comment]
> > Hello @from2001 @lichengwu What is your current node version?
> > I tested it can be built by using 20.14.0. It fails in 21.x.
> > I suggest you guys use 20.14 LTS version to build it.
> > Ref:
> > https://github.com/langgenius/dify/blob/5f7321ea28155982be9370bc84791d62163352b5/web/Dockerfile#L2
> 
> v22.0.0

可以跟我说下是怎么拉去基础镜像的吗: node:20.11-alpine3.19，我在重新构建web镜像的时候报错找不到这个基础镜像

Could you tell how to pull the base imatge: node:20.11-alpine3.19. I got the error :  failed to solve: node:20.11-alpine3.19: failed to resolve source met
adata for docker.io/library/node:20.11-alpine3.19: failed to copy: httpRead
Seeker: failed open: failed to do request: Get "https://production.cloudfla
re.docker.com/registry-v2/docker/registry/v2/blobs/sha256/ae/ae7f6c370720be
0fd4120606ee84f6170037f6c163b91522eea08cbe574d78ff/data?verify=1719025235-jJaSr%2BtUDiFTeAyGMgtcUApLXCQ%3D": net/http: TLS handshake timeout

**Comment by 115341chenzehao** [comment]
> > > Hello @from2001 @lichengwu What is your current node version?
> > > I tested it can be built by using 20.14.0. It fails in 21.x.
> > > I suggest you guys use 20.14 LTS version to build it.
> > > Ref:
> > > https://github.com/langgenius/dify/blob/5f7321ea28155982be9370bc84791d62163352b5/web/Dockerfile#L2
> > 
> > 
> > v22.0.0
> 
> 可以跟我说下是怎么拉去基础镜像的吗: node:20.11-alpine3.19，我在重新构建web镜像的时候报错找不到这个基础镜像
> 
> Could you tell how to pull the base imatge: node:20.11-alpine3.19. I got the error : failed to solve: node:20.11-alpine3.19: failed to resolve source met adata for docker.io/library/node:20.11-alpine3.19: failed to copy: httpRead Seeker: failed open: failed to do request: Get "https://production.cloudfla re.docker.com/registry-v2/docker/registry/v2/blobs/sha256/ae/ae7f6c370720be 0fd4120606ee84f6170037f6c163b91522eea08cbe574d78ff/data?verify=1719025235-jJaSr%2BtUDiFTeAyGMgtcUApLXCQ%3D": net/http: TLS handshake timeout

I encountered the same issue, how did you resolve it?

**Comment by 115341chenzehao** [comment]
@crazywoola
Hello, esteemed project initiator,
I encountered some issues while rebuilding the web image, Could you please provide me with some valuable advice?

【Reason】: I modified the max value in top-k-item.tsx to increase the number of knowledge matches, and then attempted to rebuild the web image using docker build.

【Problem】:
```
[+] Building 54.6s (2/2) FINISHED                                                                                                                  docker:default
 => [internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 1.45kB                                                                                                                       0.0s
 => ERROR [internal] load metadata for docker.io/library/node:20.11-alpine3.19                                                                              54.5s
------
 > [internal] load metadata for docker.io/library/node:20.11-alpine3.19:
------
Dockerfile:2
--------------------
   1 |     # base image
   2 | >>> FROM node:20.11-alpine3.19 AS base
   3 |     LABEL maintainer="takatost@gmail.com"
   4 |
--------------------
ERROR: failed to solve: node:20.11-alpine3.19: failed to resolve source metadata for docker.io/library/node:20.11-alpine3.19: failed to copy: httpReadSeeker: failed open: unexpected status code https://zj7lxt8j.mirror.aliyuncs.com/v2/library/node/blobs/sha256:ae7f6c370720be0fd4120606ee84f6170037f6c163b91522eea08cbe574d78ff?ns=docker.io: 500 Internal Server Error - Server message: unknown: unknown error
```

【Request】: How can I successfully pull node:20.11-alpine3.19?

I appreciate your great work and would like to contribute more to the project. Thank you.

**Comment by 115341chenzehao** [comment]
Maybe you could tell me the Docker registry you are using, and I will try to switch to it.

**Comment by 115341chenzehao** [comment]
> Thank you for replying. I have already asked my classmates to download it.&nbsp;But for the sake of future learning, I still hope that I can download it I am in China, so I use some registry mirror in my docker.&nbsp; Here is the image I used: { &nbsp; "builder": { &nbsp; &nbsp; "gc": { &nbsp; &nbsp; &nbsp; "defaultKeepStorage": "20GB", &nbsp; &nbsp; &nbsp; "enabled": true &nbsp; &nbsp; } &nbsp; }, &nbsp; "experimental": false, &nbsp; "registry-mirrors": [ &nbsp; &nbsp; "http://hub-mirror.c.163.com", &nbsp; &nbsp; "https://mirror.baidubce.com", &nbsp; &nbsp; "https://ccr.ccs.tencentyun.com", &nbsp; &nbsp; "https://dockerproxy.com", &nbsp; &nbsp; "http://f1361db2.m.daocloud.io", &nbsp; &nbsp; "https://docker.mirrors.ustc.edu.cn/", &nbsp; &nbsp; "https://reg-mirror.qiniu.com", &nbsp; &nbsp; "https://registry.docker-cn.com" &nbsp; ] } 超越 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "langgenius/dify" ***@***.***&gt;; 发送时间:&nbsp;2024年6月26日(星期三) 下午3:31 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [langgenius/dify] can not build web project (Issue #5269) Maybe you could tell me the Docker registry you are using, and I will try to switch to it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你好，我还没有找到这个问题的解决方案，我换了好多docker源都没法下载这个镜像，你的同学是如何成功下载到这个镜像的呢？
另外可以麻烦将"node:20.11-alpine3.19"这个镜像发给我吗？
万分感谢！！邮箱地址：875645784@qq.com
