### ISSUE TITLE
chart display support when use code interpreter to run python code to plot data

### ISSUE THREAD

**Issue by yc3231996** [langgenius/dify#5270]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am trying to build a data analysis agent, which is capable of visualize data. Currently I can only use build-in chart tools, which is too simple.

### 2. Describe the feature you'd like to see

I'd like to leverage python and code interpreter to achieve comprehensive data visualization. Similar like current ChatGTP, which can display the chart images created by Matplotlib.  ChatGPT can even support responsive chart instead of static image. 

In Dify, I will meet the exception says " no module named Matplotlib ". 
![image](https://github.com/langgenius/dify/assets/20618176/82b96899-52bc-4752-80f8-8e897751e8bf)

### 3. How will this feature improve your workflow or experience?

With python and code interpreter support, the data visualization step can be much more flexible and powerful. 
First, can support more types of charts, witch flexible configuration. Secondly, we can use the LLM coding capability to manipulate the visualization in an interactive way. 

### 4. Additional context or comments

I think this request of enhancement is common in data analysis scenarios.
The basic feature is just to support displaying the chart images in conversation front-end, the static images created by Matplotlib.
Further, if can support interactive charts, similar like ChatGPT, that will be great.

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by yc3231996** [comment]
anyone pay attention to this?

**Comment by yc3231996** [comment]
> Options and timlikts faster workflow

what?

**Comment by garyfeng** [comment]
any updates?

**Comment by crazywoola** [comment]
Can you try https://github.com/langgenius/dify/pull/6961 this one?
