### ISSUE TITLE
Azure Dall-E 3 Tool failed

### ISSUE THREAD

**Issue by breakstring** [langgenius/dify#5281]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Add the official built-in Azure DALL-E3 Tool in the workflow or Agent. The error when generating images is as follows:
**"tool invoke error: name 'random' is not defined"**
![image](https://github.com/langgenius/dify/assets/14105911/3398dd74-4686-4042-a39c-e26c0f01701c)

### ✔️ Expected Behavior

Generate image as wish.

### ❌ Actual Behavior

Error in pic.

**Comment by crazywoola** [comment]
@charli117 Please take a look at this.

**Comment by charli117** [comment]
@ breakstring @crazywoola This bug has been fixed, the commit code was missing a dependency
#5288
