### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by jerlinn** [langgenius/dify#5289]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have followed the setting about '.env', '.env.local' and 'docker-compose.yaml'.
**Still unable to sign in**

Not help:
- pull the latest version or reinstall
- reset pasword

![CleanShot 2024-06-17 at 09 29 30@2x](https://github.com/langgenius/dify/assets/91647085/54cad9bf-6e58-4bca-9353-5d768e972022)

### ✔️ Expected Behavior

finish building

### ❌ Actual Behavior

ERR_CONNECTION_REFUSED

**Comment by crazywoola** [comment]
See the image, it tries to access the localhost:5001. This indicates you are not setting the right env variables.

```
  CONSOLE_API_URL: "http://your-domain.com/api"
  CONSOLE_WEB_URL: "http://your-domain.com"
  SERVICE_API_URL: "http://your-domain.com/service"
  APP_API_URL: "http://your-domain.com/app"
  APP_WEB_URL: "http://your-domain.com"
```
Please the the settings above.

**Comment by jerlinn** [comment]
It works, I'm so confused but it works 😂.

```
docker-compose down
docker-compose up -d
```

**Comment by yong2khoo-lm** [comment]
> > It works, I'm so confused but it works 😂.
> > ```
> > docker-compose down
> > docker-compose up -d
> > ```
> 
> Do you mind sharing your solution?
> 
> ### Here with default yaml:
> the `sandbox-1`, `web-1`, `api-1`, `worker-1` keep restarting
> 
> ### After uncommenting:
> ```
> api:
>    ports:
>      - "5001:5001"
> 
> web:
>    ports:
>      - "3000:3000"
> ```
> 
> the `sandbox-1`, `api-1`, `worker-1` keep restarting (at least `web-1` is fine)
> 
> ### With URL (i assume api is consistent with above: 5001)
> ```
>   CONSOLE_API_URL: "http://localhost:5001/api"
>   CONSOLE_WEB_URL: "http://localhost:3000"
>   SERVICE_API_URL: "http://localhost:5001/service"
>   APP_API_URL: "http://localhost:5001/app"
>   APP_WEB_URL: "http://localhost:3000"
> ```
> 
> still, `api-1` keep restarting. not sure what i missed

clear everything and redo again it magically works ..... (without even specifying the ports)
