### ISSUE TITLE
How to retry the latest response

### ISSUE THREAD

**Issue by FingerLiu** [langgenius/dify#5296]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I'm not satisfied with the llm reply, or even the. reply is broken, this is no button, and no API to retry the latest reply. When will we support this?

### 2. Describe the feature you'd like to see

I expect a "retry" button under the latest reply.

### 3. How will this feature improve your workflow or experience?

With no this I can not integrate to my website. 

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please use the right template to ask for help :)
