### ISSUE TITLE
Is it possible to provide a form recognition tool in the toolbar?

### ISSUE THREAD

**Issue by qihanghou726** [langgenius/dify#5306]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Is it possible to provide a form recognition tool in the toolbar?I

### 2. Describe the feature you'd like to see

 think there is a huge demand for form recognition, or the recognition of complex forms.

### 3. How will this feature improve your workflow or experience?

solve my problem

### 4. Additional context or comments

null

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Can you give us more details about this issue.
