### ISSUE TITLE
Support for glm-4-9b-chat  

### ISSUE THREAD

**Issue by lesrose** [langgenius/dify#5313]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Our group is preparing to use the newly released ChatGLM4 model

### 2. Describe the feature you'd like to see

![image](https://github.com/langgenius/dify/assets/48045297/dcfbce5c-ee69-4936-84a9-d5c0ba96e935)
ChatGLM includes more new models like GLM-4-9B,GLM-4-9B-Chat,GLM-4V-9B

### 3. How will this feature improve your workflow or experience?

most people can use chatglm new model to improve their works

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by beijingtl** [comment]
Don't understand, does that mean we need to wait for new feature updated?

**Comment by zhihai-tu** [comment]
I need this feature too
wish to support glm-4 local

**Comment by orangeclk** [comment]
You can load glm4-9b using tools like ollama or xinference.
