### ISSUE TITLE
Fix everything enable my agent to make changes

### ISSUE THREAD

**Issue by kebotbmfl** [langgenius/dify#5317]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Fix everything

### 2. Describe the feature you'd like to see

I won’t to start now

### 3. How will this feature improve your workflow or experience?

It will help me get to work fast

### 4. Additional context or comments

Fix auto merge for me

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please reach out to me banana@dify.ai if you have further quesions.
