### ISSUE TITLE
SrplyApi tool not working

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#5338]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Source)

### Steps to reproduce

Trying to add API key to Serply.io tool gives: "Expecting value: line 1 column 1 (char 0)"

### ❌ Actual Behavior

Expecting value: line 1 column 1 (char 0)

**Comment by crazywoola** [comment]
@googio @laipz8200 Can you guys take a look at this?

**Comment by laipz8200** [comment]
This tool hasn't been officially released yet, but it should be usable. If you're deploying from the source code, please make sure to run `flask db upgrade`. You can refer to our [Upgrade Guide](https://github.com/langgenius/dify/releases/tag/0.6.11) for more details.

**Comment by googio** [comment]
@AndyMik90 @crazywoola 
This is most likely because the API Key isn’t active or our system flagged the account during signup.
Please send an email to support@serply.io and mention authentication errors. We will review the account. Thank you

**Comment by googio** [comment]
@AndyMik90 Sorry about the issue. We've identified the error and pushed out an update. You should be able to Authenticate now. Please mark this as closed if this has resolved your issue.

**Comment by laipz8200** [comment]
I've checked the fix. If anyone still has issues, just reopen this.
