### ISSUE TITLE
Add Oracle23ai as a vector datasource

### ISSUE THREAD

**Issue by tmuife** [langgenius/dify#5344]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I am an employee of Oracle China. We have some customers who are very interested in your awesome product dify, but they want to use Oracle 23 AI to store their vector data. So i want to add Oracle as a vector datasouce.

### 2. Describe the feature you'd like to see

We can use Oracle 23 as a datasouce of vector store.

### 3. How will this feature improve your workflow or experience?

Some Oracle users may also can use dify

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/5342
