### ISSUE TITLE
LLM dialogue can only upload images at present? How to upload other types of files such as txt,doc, etc

### ISSUE THREAD

**Issue by xddcode** [langgenius/dify#5346]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Here's the scenario: I want to pass in a pdf or doc and have LLM summarize the key points for me and give me an analysis

### 2. Describe the feature you'd like to see

Dialogue upload there is support for multiple types of files

### 3. How will this feature improve your workflow or experience?

Powerful, better experience

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This is already in our dev plan.

**Comment by egenchen** [comment]
> This is already in our dev plan.

Is there any information on when this feature will be ready? Thank you.

**Comment by crazywoola** [comment]
We will support it next month.

**Comment by yaohongfenglove** [comment]
Does the start node of the workflow also support file upload, or does it only support chat

**Comment by crazywoola** [comment]
Close due to #5346

**Comment by YYL1999** [comment]
> Close due to #5346

when can use the new node now？

**Comment by tangyoha** [comment]
> Close due to #5346 由于以下原因 #5346 关闭

why close？

**Comment by tangyoha** [comment]
> Close due to #5346由于以下原因 #5346 关闭

hi @crazywoola ,why close?

**Comment by xs818818** [comment]
已经8月了，请问实现了吗

**Comment by joyjoyyo** [comment]
I'm really looking forward to it

**Comment by 18758976569** [comment]
请问文件对话的功能，这个月可以上嘛，十分需要

**Comment by crazywoola** [comment]
It will be released in next month. @18758976569

**Comment by 18758976569** [comment]
> It will be released in next month. @18758976569

thanks,looking forward to it

**Comment by bingbing6** [comment]
> 它将于下个月发布。
请问大概还需要多久发布呢？

**Comment by bingbing6** [comment]
> 它将于下个月发布。

请问大概还要多久发布呢？

**Comment by zfno111** [comment]
09/10  8.0 The version has been iterated but there is no such feature yet

**Comment by AAEE86** [comment]
This month will be supported.

**Comment by xs818818** [comment]
0.8.2 is ont support

**Comment by 18075717849** [comment]
0.8.3 is also not supported

**Comment by MRKINKI** [comment]
Hehe

**Comment by ClementeGao** [comment]
the api not support audio at request body , have plan?

**Comment by xs818818** [comment]
![2024-10-01 18-05-07屏幕截图](https://github.com/user-attachments/assets/16dce85c-5b86-48e6-b29a-564e8ba90485)
The latest version can upload files, but the URL of the files cannot be obtained

**Comment by muhanstudio** [comment]
Thank you very much for the hard work of the team, but would like to ask, has the feature been updated? I guess you guys shouldn't have to go to China's National Day. Hahahahahaha

**Comment by muhanstudio** [comment]
> Thank you very much for the hard work of the team, but would like to ask, has the feature been updated? I guess you guys shouldn't have to go to China's National Day. Hahahahahaha

Okay, let's not kidding now, uploading files in conversations is a very basic and important function, and losing it would directly make web conversations completely uncompetitive, as countless experiments have shown. Even weaker models, if the corresponding documentation information can be obtained during conversation, are much better than stronger models alone with a vague and broad vector knowledge base. Hope the hard-working team can work harder, and look forward to your great performance.

**Comment by selenasun2024** [comment]
支持上传文档，可以让工作流运用的场景更丰富一些。

**Comment by selenasun2024** [comment]
非常期待这个功能能够使用

**Comment by 18075717849** [comment]
Does the latest version of the LLM dialog of the dify workflow support adding attachment files?
@muhanstudio @dosu

**Comment by G81192** [comment]
@crazywoola Hello, has this issue been resolved? I’m currently using the latest version (0.10.2), but the issue still persists. I’m not sure if this is due to my configuration or if the feature is still unsupported?

**Comment by hiiamboris** [comment]
2026. Still not working. You specify an extension, but the uploader mechanism blocks it as "File validation failed". Pathetic.
