### ISSUE TITLE
Error in using knowledge base recall test

### ISSUE THREAD

**Issue by xddcode** [langgenius/dify#5350]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. A pdf file was uploaded
2. 
![image](https://github.com/langgenius/dify/assets/48708512/027c16e3-c1b1-421e-bc2c-27f5c94adfe1)
![image](https://github.com/langgenius/dify/assets/48708512/fc478e11-0e50-445c-a745-c7f6962b99d3)

### ✔️ Expected Behavior

normal

### ❌ Actual Behavior

error

**Comment by xddcode** [comment]
@dosu，Now in full-text search mode, no error. The above error occurs in vector retrieval mode

**Comment by luckylhb90** [comment]
plz see #5640 
I ran into the same problem, and I used a lower version of qdrant to fix the problem.

**Comment by JohnJyong** [comment]
duplicate with #5640
