### ISSUE TITLE
completion-messages api returns with no conversation_id 

### ISSUE THREAD

**Issue by huxiaoxi1992** [langgenius/dify#5356]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. curl with completion-messages 
```bash
curl 'http://localhost:3000/chat/v1/completion-messages' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{"inputs":{"query":"hello!"},"user":"mobile","response_mode":"streaming"}'
 ```

### ✔️ Expected Behavior

onData should show as below
```plain
data: {"id": "5ad4cb98-f0c7-4085-b384-88c403be6290", "answer": " I", "created_at": 1679586595, "conversation_id":  "3a69cb96-eec6-4eeb-b1ea-3297eaa7f17c"}
data: {"id": "5ad4cb98-f0c7-4085-b384-88c403be6290", "answer": " I", "created_at": 1679586595, "conversation_id":  "3a69cb96-eec6-4eeb-b1ea-3297eaa7f17c"}
```

### ❌ Actual Behavior

```plain
data: {"event": "message", "message_id": "3a69cb96-eec6-4eeb-b1ea-3297eaa7f17c", "created_at": 1718701490, "task_id": "9b03f72e-a3c7-4df7-aaa7-7f701999f812", "id": "3a69cb96-eec6-4eeb-b1ea-3297eaa7f17c", "answer": "\u53f2"}
```

**Comment by crazywoola** [comment]
I think you can open a pull request to remove `conversation_id` in the mdx files. Because there is no `conversation_id` in this type `completion-messages`
