### ISSUE TITLE
已经启动了，但无法访问，是为啥？

### ISSUE THREAD

**Issue by vual** [langgenius/dify#536]
![image](https://github.com/langgenius/dify/assets/25891219/2b49f5b8-9d34-4f5c-86b6-ab78b6568dee)
![image](https://github.com/langgenius/dify/assets/25891219/28d6b24c-b811-492a-aa57-9ca187809c60)

**Comment by mr-kelly** [comment]
Any logs?

**Comment by LL992716783** [comment]
您好，请问是如何解决的呢
