### ISSUE TITLE
Is there a plan to support multiple agent

### ISSUE THREAD

**Issue by mboo2005** [langgenius/dify#5361]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Scenario of multiple agent, for instance, in a brand operation project, where there is a need to create copywriting ---> review of the copywriting ---> release of the copywriting.

### 2. Describe the feature you'd like to see

In the context of multiple agent, similar to how Coze supports multiple agents, agents can interact with each other

### 3. How will this feature improve your workflow or experience?

To implement the reuse of agents 

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes

**Comment by mboo2005** [comment]
> Yes

Thank you. When will the feature be added in which version, and approximately when will it be available?
