### ISSUE TITLE
Image as a Markdown format is setting in 'assistan' chat history

### ISSUE THREAD

**Issue by AQFU** [langgenius/dify#5368]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![20240618-192756](https://github.com/langgenius/dify/assets/10356357/0f344632-dab1-40b7-bd0c-349c08f94244)
<img width="407" alt="image" src="https://github.com/langgenius/dify/assets/10356357/2a50562a-045c-4458-b775-04ed4aa1834c">
When I set dalle-3 output as a reply, the markdown format image path became chat memory.
Will make LLM output markdown code like ![image]xxxxx

### ✔️ Expected Behavior

maybe let user edit the chat memory?

**Comment by crazywoola** [comment]
Sorry, but we do not have this plan for editing memory right now.

**Comment by AQFU** [comment]
What if we only filter out the image or audio path information in markdown format from memory?
