### ISSUE TITLE
When will the sys.files property be supported in the workflow of ordinary LLM models?

### ISSUE THREAD

**Issue by violinday** [langgenius/dify#5369]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

The custom LLM API interface supports image recognition, but sys.files fails to transmit.

### 2. Describe the feature you'd like to see

The sys.files property be supported in the workflow of ordinary LLM models

### 3. How will this feature improve your workflow or experience?

use custom llm api will be easy.

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes we will introduce a new type of node which supports upload files.

**Comment by violinday** [comment]
> Yes we will introduce a new type of node which supports upload files.

@crazywoola  
👍, when will this feature be available?  ：）

**Comment by wizd** [comment]
I'd like tool to process sys.files. e.g. to extract EXIF data from user images. looking forward for the new feature!

**Comment by StarDxxx** [comment]
Emm, it means, user can upload the files, and LLM can use these files to generate the content?
Acutally now I don't know how to do this. :(
