### ISSUE TITLE
企业微信工具有BUG，自动多了一个$造成UUID不合法

### ISSUE THREAD

**Issue by oiuv** [langgenius/dify#5377]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/13300261/ade643df-13a1-49d3-a8aa-22ef755282e2)

无法用企业微信webhook，示例如上图。

### ✔️ Expected Behavior

正常情况应该是通过webhook发消息到企业微信

### ❌ Actual Behavior

报以下问题：

{"wecom_group_bot": "Invalid parameter hook_key $24********************************d4, not a valid UUID"}

实际UUID是`24********************************d4`，这里显示多了一个`$`造成UUID错误。

**Comment by crazywoola** [comment]
Close due to #1542
