### ISSUE TITLE
output node error, show empty

### ISSUE THREAD

**Issue by lzzzzzzzzz** [langgenius/dify#5381]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.show empty as follow
![微信图片编辑_20240619140205](https://github.com/langgenius/dify/assets/30173938/59a6578f-be93-4c58-b0e2-ecf34ea23197)

**Comment by crazywoola** [comment]
It can not display the array object of the iteration, you should use jinja or code to format the output response.
