### ISSUE TITLE
The Qwen2-72B-Instruct model cannot return results using the OpenAI-API-compatible configuration

### ISSUE THREAD

**Issue by zengyunda** [langgenius/dify#5383]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I deployed the Qwen2-72B-Instruct model using one-api, and deployed the model using OpenAI-API-compatible on dify. When setting one of the fields Completion mode, I cannot select "Dialogue" (an error will be reported), and can only select "Complete" by pulling down. After successful deployment, I select this model in the chat assistant, and there is no content output in the window dialogue. Is there something wrong when the model is deployed?
I can call this model normally using Python code, confirming that this model is deployed successfully.
But the chat assistant using dify cannot return content.
I checked the logs, and this model returns an empty string when requested on dify

### ✔️ Expected Behavior

Return normal model output results

### ❌ Actual Behavior

![ecf30001647e7af7f64453a158b17fb](https://github.com/langgenius/dify/assets/38974755/49e16523-d178-408d-9bf7-499fd4e30802)
Workflow logs returned by using chatglm3 and using the Qwen2-72B-Instruct model respectively

**Comment by jay-jjwu** [comment]
@zengyunda , is this issue resloved? i use OpenAI-API-compatible on dify to integrate in one-api models, but only can set to chat, instead of completion (always error...see the screenshots), how you resovled this?
![image](https://github.com/langgenius/dify/assets/78014320/89d10f35-2537-4be2-abf2-bacecc6d3ff4)
![1720317288120_d](https://github.com/langgenius/dify/assets/78014320/ca91631f-e298-49ea-b88f-818133692549)

**Comment by zengyunda** [comment]
> @zengyunda , is this issue resloved? i use OpenAI-API-compatible on dify to integrate in one-api models, but only can set to chat, instead of completion (always error...see the screenshots), how you resovled this? ![image](https://private-user-images.githubusercontent.com/78014320/346307041-89d10f35-2537-4be2-abf2-bacecc6d3ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTc3NjEsIm5iZiI6MTcyMDMxNzQ2MSwicGF0aCI6Ii83ODAxNDMyMC8zNDYzMDcwNDEtODlkMTBmMzUtMjUzNy00YmUyLWFiZjItYmFjZWNjNmQzZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDAxNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OTA2ZjQ4YjkyNTljYTJiYmFkMzVmNDA5OGJmZDlkZmI3Y2NmY2YzOGZmN2RkZjEwODcwMzJiMjU4MjBjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h0ZpHP13H95WtBlljdsNjguh78QljMnkXXm95jxXO5w) ![1720317288120_d](https://private-user-images.githubusercontent.com/78014320/346307049-ca91631f-e298-49ea-b88f-818133692549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTc3NjEsIm5iZiI6MTcyMDMxNzQ2MSwicGF0aCI6Ii83ODAxNDMyMC8zNDYzMDcwNDktY2E5MTYzMWYtZTI5OC00OWVhLWI4OGYtODE4MTMzNjkyNTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDAxNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZThiZmEzY2YyZjZjZjNmNWE3M2U4MmI4YjNlOTUzY2VmNTg0NzkyMjA0ODI1ZWNlZmYwOGNiODdhZTg1NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAW8af1d3VkbYgrCfMcB9nyZlleEwyySBVmm9nmmXWk)

没有解决，官方没有给出解决方案，根据在官方群的回复，这个应该是底层代码不支持

**Comment by jay-jjwu** [comment]
好的，谢谢
