### ISSUE TITLE
Provide options to avoid storing document embedding to local postgresql?

### ISSUE THREAD

**Issue by lpdink** [langgenius/dify#5385]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I was trying to import large amount of document, while I noticed that dify always save document embedding to local postgresql dataset even if I have already used certain vdb service for vector storage and retrieval.

### 2. Describe the feature you'd like to see

Need an option to avoid adding embedding to local postgresql.

### 3. How will this feature improve your workflow or experience?

It could save extra disk storage used by dify.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by secsilm** [comment]
> dify always save document embedding to local postgresql dataset even if I have already used certain vdb service for vector storage and retrieval.

What's the design purpose of this?

**Comment by secsilm** [comment]
Is this feature implemented?
