### ISSUE TITLE
When starting to set the parameter variables, can set a hidden mode be added?

### ISSUE THREAD

**Issue by ripotala** [langgenius/dify#5386]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When setting parameter variables at the very beginning of the workflow, can an option be added to set whether the parameter variables are visible or not? 

### 2. Describe the feature you'd like to see

![image](https://github.com/langgenius/dify/assets/5178773/537d34ee-4138-4e21-b770-461e22460016)

### 3. How will this feature improve your workflow or experience?

Currently, there are only "required" or "optional" choices, but there might be another situation. When the workflow calls external tools, some internal states do not need to be obtained from user input. Therefore, we hope to have such an option. Thank you.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by simpsonyang** [comment]
I need this feature.
