### ISSUE TITLE
After the application is published, the site name cannot be changed following the editing information

### ISSUE THREAD

**Issue by JayHsu5** [langgenius/dify#5389]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. edit info 
2. run app

### ✔️ Expected Behavior

same name display

### ❌ Actual Behavior

Not the same name
-
may be caused by the **sites** table

**Comment by kurokobo** [comment]
See: https://github.com/langgenius/dify/issues/5180#issuecomment-2167001095
