### ISSUE TITLE
seems that some variables are lost after the Parameter Extraction node.

### ISSUE THREAD

**Issue by mrbaowei** [langgenius/dify#5393]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11 latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

#  Phenomenon:
When using the Parameter Extraction node, its next node is not always able to correctly obtain the variables on the process. Sometimes it cannot be found, and sometimes it can be found, but the variables are empty. 
# Reproduction method: 
Just add a Parameter Extraction node after the LLM node, and then add a DirectReply node to try to find variables, and some variables will be found to be missing.

### ✔️ Expected Behavior

Variables should be found at any point in the process.

**Comment by crazywoola** [comment]
<img width="1504" alt="image" src="https://github.com/langgenius/dify/assets/100913391/237d89db-bece-4ad3-8f55-1734dd0f3f58">
Cant reproduce that. Do you have a screenshot or do you have more details?

**Comment by mrbaowei** [comment]
@crazywoola 
<img width="1265" alt="image" src="https://github.com/langgenius/dify/assets/16350494/cdecedfd-f5c6-4ac1-af89-4983514aa021">

it seems  output null in first Direct Reply node.  must set up two direct reply nodes in order to output the content in the Parameter Extraction node.

**Comment by mrbaowei** [comment]
> reproduce

Hi @crazywoola, could you please try to reproduce the issue with my method?

**Comment by crazywoola** [comment]
Can you export a DSL here.
