### ISSUE TITLE
Chat chat, can you add or delete a specific message in the specified conversation and regenerate the specified message?

### ISSUE THREAD

**Issue by zealerFT** [langgenius/dify#5394]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

yes

### 2. Describe the feature you'd like to see

yes

### 3. How will this feature improve your workflow or experience?

yes

### 4. Additional context or comments

just like chatgpt,can Regenerate

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by liuquanqing** [comment]
![image](https://github.com/user-attachments/assets/76422348-b4a9-4bd7-9f45-4251cbf5cd9e)
![image](https://github.com/user-attachments/assets/0f2900d6-41cf-4252-b0b1-29f39ff363e8)
![image](https://github.com/user-attachments/assets/3afa4fe6-81d7-4a4d-a6e3-360d40872655)

"This need to re-edit the previous input is extremely common. Even less sophisticated solutions support deletion, and many lightweight open-source products include this feature. But it's surprising that Dify lacks it... hard to imagine. Do you really engage in long-term conversations with AI?"
