### ISSUE TITLE
wrong response when delete conversation by api

### ISSUE THREAD

**Issue by chivalry1314** [langgenius/dify#5400]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

when I use the api of deleting conversation, the content of response is empty, and http response code is 204.
![image](https://github.com/langgenius/dify/assets/16643409/f9bdf650-e7a0-4881-94e7-7be5ba06c968)
![image](https://github.com/langgenius/dify/assets/16643409/d4ec1a8f-f010-4a39-958a-fd72a07a8f5d)

### ✔️ Expected Behavior

I need the content of response is as the document says
![image](https://github.com/langgenius/dify/assets/16643409/d4ec1a8f-f010-4a39-958a-fd72a07a8f5d)

### ❌ Actual Behavior

the content of response is empty, and http response code is 204.
![image](https://github.com/langgenius/dify/assets/16643409/f9bdf650-e7a0-4881-94e7-7be5ba06c968)

**Comment by crazywoola** [comment]
Could you open a pull request to fix this?
