### ISSUE TITLE
The error "104" occurred when trying to add Google search. What if I modify the authorization key for Google?

### ISSUE THREAD

**Issue by bokey003** [langgenius/dify#5403]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

The error "104" occurred when trying to add Google search. What if I modify the authorization key for Google?

![image](https://github.com/langgenius/dify/assets/173264400/68d5a9d8-18b5-47e6-b656-b2122fd77bd0)

**Comment by crazywoola** [comment]
Can you provide more details regarding this issue,  a exported DSL would be great.
