### ISSUE TITLE
Error build Dockerfile api

### ISSUE THREAD

**Issue by TienLD-0801** [langgenius/dify#5407]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

<img width="1256" alt="Screenshot 2024-06-20 at 01 29 59" src="https://github.com/langgenius/dify/assets/112608271/e8bb88d8-85c3-4220-9ffb-5345f68d497d">

### ✔️ Expected Behavior

It seems like the python version does not match and the pip install command cannot be run

**Comment by crazywoola** [comment]
We have updated this API dockerfile over 3 months, so if this generates errors, you won't be able to see the v0.6.11.

**Comment by TienLD-0801** [comment]
@crazywoola  Because I update over time, while updating the v0.6.11 api folder, there was a change in the lib that caused me to get a wrong version number. Surely the Dockerfile is not responsive enough.

**Comment by crazywoola** [comment]
I guess you need to try to use the latest poetry to install dependencies.

**Comment by bowenliang123** [comment]
Which system and chip architecture are you using? Is that Linux on arm64?

**Comment by crazywoola** [comment]
<img width="1246" alt="image" src="https://github.com/langgenius/dify/assets/100913391/a1957eba-9cde-4a30-9e82-b065fc495cde">

After upgrading to 2.4, Milvus cannot successfully install dependencies on the ARM architecture of Linux. Therefore, if you want to proceed with the use of Poetry/mirror construction, you might need to consider rolling back Milvus.

**Comment by TienLD-0801** [comment]
@bowenliang123  I'm using macos m3 and want to build arm64 and amd64 but I get an error .

**Comment by bowenliang123** [comment]
Please rebase to latest commit of the master branch and try again.
As #5414 reverted the #3795, the `pymilvus` is now downgraded to 2.3.x, which does not requires `milvus-lite` pakcage.

**Comment by TienLD-0801** [comment]
@crazywoolala , @bowenliang123  I confirm the patch works fine, so I consider closing this issue
