### ISSUE TITLE
Option to Hide Workflow Steps for Embedded Application

### ISSUE THREAD

**Issue by ZimaBlueee** [langgenius/dify#5411]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![图片](https://github.com/langgenius/dify/assets/53747502/8c0e8a4e-0936-487c-92b9-39ca00a4bbb6)

When embedding the Dify application into a website, the workflow steps are also displayed to the user when answering questions. Regular users are not concerned with this and it may cause confusion. Could there be an option to hide the workflow steps and only display the answers?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by iamjoel** [comment]
Workflow may return the first byte in a long time. The workflow steps can let users know that the workflow is running.

**Comment by kurokobo** [comment]
Here is the same RFE: https://github.com/langgenius/dify/issues/4682

**Comment by ZimaBlueee** [comment]
> Workflow may return the first byte in a long time. The workflow steps can let users know that the workflow is running.

My business is cached and the response speed is very fast. Can I add a switch to control whether the process is displayed to ordinary users?

**Comment by laelhalawani** [comment]
it's not present in the latest version. please reopen

**Comment by laelhalawani** [comment]
actually it's present, my bad. 

How to find it:
1) open your app in the editor
2) on the left side you have a panel, click your app name there
3) you will see a new panel with more settings including both running services for this app (application and backend), under the application service you have settings button 
4) after clicking the settings button you'll finally have the option to disable the workflow details

**Comment by WenruiYu** [comment]
![Image](https://github.com/user-attachments/assets/3f798ddf-cfa3-4e9d-b6e0-4bf4631ccd59)
The option is locked on.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/59b89b99716be19550eb342d50c6f535bc6df3c4/web/app/components/app/overview/settings/index.tsx#L330-L334

Only Chatflow/Workflow can use this setting.
