### ISSUE TITLE
Docs link not found. https://docs.dify.ai/getting-started/faq/install-faq

### ISSUE THREAD

**Issue by simplast** [langgenius/dify#5417]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

  # ssrf_proxy server
  # for more information, please refer to
  # https://docs.dify.ai/getting-started/install-self-hosted/install-faq#id-16.-why-is-ssrf_proxy-needed
  
  link from docker-compose.yaml

**Comment by crazywoola** [comment]
We are re-editing the maintenance help document, please be patient and wait for our work to finish, you can switch to Chinese first.
