### ISSUE TITLE
纯工作流模式的输出为json格式，而不是期望的直接回复

### ISSUE THREAD

**Issue by harryhan1989** [langgenius/dify#5424]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

纯工作流模式的输出为json格式，而不是期望的直接回复

### ✔️ Expected Behavior

期望的直接回复

### ❌ Actual Behavior

不希望输出json

**Comment by harryhan1989** [comment]
关键是聊天工作流就可以有直接回复的选项，而单独的工作流却没有，我记得以前版本是有的，为什么要这么干呢，或者2个都提供出来选择不好吗

**Comment by harryhan1989** [comment]
为什么纯工作流的结果组件就只能是下面这个？
![image](https://github.com/langgenius/dify/assets/2442117/bc371ac5-cc80-42f8-b72f-37c340988615)
而聊天工作流的结束组件却是这个：
![image](https://github.com/langgenius/dify/assets/2442117/3eba0cc2-9caa-4043-b7d5-84d4aca8f443)

**Comment by DoiiarX** [comment]
的确。这个设计很难。而且没有文档。如果不是擅长在github问的，根本没资料说明怎么回事。

而且新人也不知道聊天类型程序无法发布为工作流。

dify这点文档做的的确不好。

**Comment by DoiiarX** [comment]
都没有修复，这个问题怎么被关了。

**Comment by crazywoola** [comment]
违反 language policy

**Comment by crazywoola** [comment]
Cloud 版本已经上线了，工作流可以输出 result。

**Comment by crazywoola** [comment]
> 关键是聊天工作流就可以有直接回复的选项，而单独的工作流却没有，我记得以前版本是有的，为什么要这么干呢，或者2个都提供出来选择不好吗

没有，工作流中就是 End 节点，Chatflow 是 Answer 节点。

**Comment by DoiiarX** [comment]
> Cloud 版本已经上线了，工作流可以输出 result。

社区版不更新这个吗

**Comment by luisxin** [comment]
![image](https://github.com/user-attachments/assets/5be23073-92fa-4134-a6b0-2634a0946623)
cloud的工作流也是没有直接回复的选项。

**Comment by Yuis1** [comment]
自己在中间插入个代码节点咯
<img width="931" alt="image" src="https://github.com/user-attachments/assets/7163e7fe-29de-4310-9cb0-def264948ba9">

`
import json

def main(answer: str ) -> dict:
    data = json.loads(answer)
    # 提取 answer 的值
    text = data.get("answer", "")
    return {
        "result": text
    }
`

**Comment by rowstop** [comment]
> 自己在中间插入个代码节点咯 <img alt="image" width="931" src="https://private-user-images.githubusercontent.com/6207017/387788315-7163e7fe-29de-4310-9cb0-def264948ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE3NTAzMTAsIm5iZiI6MTc0MTc1MDAxMCwicGF0aCI6Ii82MjA3MDE3LzM4Nzc4ODMxNS03MTYzZTdmZS0yOWRlLTQzMTAtOWNiMC1kZWYyNjQ5NDhiYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTJUMDMyNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkyNTBhZjQwZTBmMDczN2MwMDIwNzg1ZmZhNGYwOTZkNDhjOTkzODM5YjFjNjJmODk4MzViYjRjODcwN2U0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sZg2_bzaV1z6SGwkHuBh8I6CIj3crVtHtGiKoYiW6OQ">
> 
> ```
> import json
> 
> def main(answer: str ) -> dict:
>     data = json.loads(answer)
>     # 提取 answer 的值
>     text = data.get("answer", "")
>     return {
>         "result": text
>     }
> ```
> 
> https://aiflow.tools/dify%e5%b7%a5%e5%85%b7%e5%8f%aa%e6%94%af%e6%8c%81%e8%be%93%e5%87%bajson/

这样做不是特别好
