### ISSUE TITLE
Support for File Upload and Processing in Workflow Code Blocks

### ISSUE THREAD

**Issue by truc0** [langgenius/dify#5432]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes, I am currently building a workflow that translates user-uploaded files. For this, I need to access and process the content of the uploaded files in the code blocks of the workflow. However, Dify currently does not support referencing the `sys.files` variable in workflow blocks, and the integrated webapp do not support uploading `.pdf` files.

### 2. Additional context or comments

Core requirements:
- allow referencing `sys.files` in `Code Execution` block in workflow
- add a `feature` called `File upload` that allowing user uploads file in the integrated web app
- add a widget for uploading file(s) in the integrated web app

There has been a related discussion (https://github.com/langgenius/dify/discussions/4233). I am very willing to contribute code if needed.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by rainchen** [comment]
+1 for file uploading feature, since there is already an Image Upload feature, and this feature is quite useful for a chatbot app.

**Comment by zhangzw16** [comment]
+1 **uploading pdf** is a very useful feature

**Comment by hponiang** [comment]
That is great，we need the feat

**Comment by VincePotato** [comment]
Yeah, we plan to support file upload in 2024 Q3.
