### ISSUE TITLE
Anthropic Claude 3 API error:403

### ISSUE THREAD

**Issue by stephonye** [langgenius/dify#5445]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I select Anthropic in the model provider settings and enter the API Key, an error message appears: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}. The model cannot be added normally. Background: The network I am on can access the Anthropic API, and I can access Anthropic Claude 3 normally using the same API Key in other ways.

### ✔️ Expected Behavior

Anthropic model added successfully

### ❌ Actual Behavior

Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}
![2024-06-20 14 44 41](https://github.com/langgenius/dify/assets/6421173/a406960d-503d-41aa-8d52-8ad7eab89e12)

**Comment by perzeuss** [comment]
The Antrophic API is probably not available where you host your Dify instance. See https://docs.anthropic.com/en/api/supported-regions
