### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by chenj133** [langgenius/dify#5448]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

当我打开一个之前创建的工作流时，报错Application error: a client-side exception has occurred (see the browser console for more information).控制台报错是：
Error in event handler: TypeError: Cannot read properties of undefined (reading 'join')
    at Object.getPageLang (chrome-extension://hlppekcioiicbfafmmgikkdkljnjpiao/content.js:2:9377)
    at chrome-extension://hlppekcioiicbfafmmgikkdkljnjpiao/content.js:2:260344
VM40:1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
V @ VM40:1
QBMiniVideo @ VM40:1
（匿名） @ VM40:1
8069-3c33bdf50ac3eeb0.js:1 TypeError: e.prompt_template.some is not a function
    at Object.checkValid (http://123.56.203.118/_next/static/chunks/app/(commonLayout)/app/(appDetailLayout)/%5BappId%5D/workflow/page-4ae9741f67eeba1f.js:1:512130)
    at http://123.56.203.118/_next/static/chunks/app/(commonLayout)/app/(appDetailLayout)/%5BappId%5D/workflow/page-4ae9741f67eeba1f.js:1:49550
    at Object.r5 [as useMemo] (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at t.useMemo (/_next/static/chunks/8069-3c33bdf50ac3eeb0.js:1)
    at tp (http://123.56.203.118/_next/static/chunks/app/(commonLayout)/app/(appDetailLayout)/%5BappId%5D/workflow/page-4ae9741f67eeba1f.js:1:49052)
    at http://123.56.203.118/_next/static/chunks/app/(commonLayout)/app/(appDetailLayout)/%5BappId%5D/workflow/page-4ae9741f67eeba1f.js:1:61082
    at rk (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at lI (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at lO (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at iB (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at o4 (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at /_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1
    at o3 (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at oQ (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at n2 (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at /_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1
    at o7 (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at oH (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at oj (/_next/static/chunks/fd9d1056-3d0b44fc34e7e5d4.js:1)
    at MessagePort.M (/_next/static/chunks/8069-3c33bdf50ac3eeb0.js:1)
window.console.error @ 8069-3c33bdf50ac3eeb0.js:1
![1718887415778](https://github.com/langgenius/dify/assets/55866399/5106d033-5bf2-4522-b001-9dcce9b4f3e5)

**Comment by AndyMik90** [comment]
Was able to reproduce a same type of error when I try to visit a Workflow Run History in studio.

![CleanShot 2024-06-20 at 15 20 18](https://github.com/langgenius/dify/assets/119136210/5bb1294e-8ee1-4283-aa4d-f8374b18b268)

**Comment by iamjoel** [comment]
Can you share your app DSL to help me reproduce the issue? @chenj133 @AndyMik90

**Comment by iamjoel** [comment]
@chenj133 Do you use the self host version？I search the error method "prompt_template.some" in main branch code. But I can't find it. Try to update the code, and test it again.

**Comment by chenj133** [comment]
I find a error in my dsl,but I don't know how does it happened.(GitHub does not support yml files, so I manually changed the suffix to txt)
[0620new1.txt](https://github.com/user-attachments/files/15922150/0620new1.txt)

**Comment by chenj133** [comment]
![image](https://github.com/langgenius/dify/assets/55866399/ce095a9f-6f30-4605-a081-d9190dd86cbd)
This is where some information is lost @iamjoel

**Comment by iamjoel** [comment]
@chenj133 I can reproduce the problem. But there are some problems in DSL.
1. It is a workflow app. There is no variable: {{#sys.query#}}.  {{#sys.query#} is only available in chatflow app.
2. In LLM node, it use the gpt-4o, which is a chat model. The value of prompt_template should be array instead of object.

How did you generate the DSL? I can't generate above problem in workflow Orchestrate page.

**Comment by chenj133** [comment]
When I configured it, it was normal, just a few simple texts. I don't know why it turned out like this

**Comment by chenj133** [comment]
While using it normally, during the process of adjusting model parameters, it suddenly became like this. The prompt_template I set on the page is just a text list, and I don't have direct permission to modify the YAML file.

**Comment by iamjoel** [comment]
I correct your yaml DSL. 
[布鲁姆分类0620new.txt](https://github.com/user-attachments/files/15922473/0620new.txt)
You can create an new app and import above DSL.

**Comment by iamjoel** [comment]
> Was able to reproduce a same type of error when I try to visit a Workflow Run History in studio.
> 
> ![CleanShot 2024-06-20 at 15 20 18](https://private-user-images.githubusercontent.com/119136210/341426083-5bb1294e-8ee1-4283-aa4d-f8374b18b268.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTI4NDQsIm5iZiI6MTcxODk1MjU0NCwicGF0aCI6Ii8xMTkxMzYyMTAvMzQxNDI2MDgzLTViYjEyOTRlLThlZTEtNDI4My1hYTRkLWY4Mzc0YjE4YjI2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNjQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjBiMGU5MDMyNzE5ZGQzZTkyZTIyOTY4NWQ5ZWNjMTU1NDI2YmNiODhjODE1MTRiOTZlMmM4MmFlZTY2NGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yO9-BV26yrpp_rIVxtBqctd5Q_ndQa4LhC8lFrYAuV8)

Fixed by https://github.com/langgenius/dify/pull/5474.

**Comment by BiyuHuang** [comment]
I have encountered same issue too. but I'm not sure about root cause of it. maybe you guys could help to figure out the root cause. 

![image](https://github.com/user-attachments/assets/08e9e987-2ff4-4b7a-b753-2e95c9fbedb4)
![image](https://github.com/user-attachments/assets/2ed2da9d-b79b-4394-aac5-eed2bb8a88e9)

**Comment by iamjoel** [comment]
> I have encountered same issue too. but I'm not sure about root cause of it. maybe you guys could help to figure out the root cause.
> 
> ![image](https://private-user-images.githubusercontent.com/14238518/366272637-08e9e987-2ff4-4b7a-b753-2e95c9fbedb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzA5NjYsIm5iZiI6MTcyNjAzMDY2NiwicGF0aCI6Ii8xNDIzODUxOC8zNjYyNzI2MzctMDhlOWU5ODctMmZmNC00YjdhLWI3NTMtMmU5NWM5ZmJlZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA0NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDhkMzBiMmEyNjVmYzg4NWZlZGM2M2VmODliNmRmOWQ2MTVjNWM5MzI2MGZhNzgyN2QyNGRjOGJhOGJlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dzOh4flq6t4wsuf6UePe2iDuYERz7GuFFyhBDJ1O-0) ![image](https://private-user-images.githubusercontent.com/14238518/366272615-2ed2da9d-b79b-4394-aac5-eed2bb8a88e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzA5NjYsIm5iZiI6MTcyNjAzMDY2NiwicGF0aCI6Ii8xNDIzODUxOC8zNjYyNzI2MTUtMmVkMmRhOWQtYjc5Yi00Mzk0LWFhYzUtZWVkMmJiOGE4OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA0NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNWYwODFlMmFiMDFhMDAzYWFiYjhlODBkODdjYjNlZjg0ZjYyZTgxNjNiOGYxZTYwY2JiZjVmYmMwYWQ5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp8Azozakm9n_Oi3RQ0By4NVOrbx3K8t7EncNxEYgLU)

@BiyuHuang please provide the app DSL.

**Comment by BiyuHuang** [comment]
> > I have encountered same issue too. but I'm not sure about root cause of it. maybe you guys could help to figure out the root cause.
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/14238518/366272637-08e9e987-2ff4-4b7a-b753-2e95c9fbedb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzA5NjYsIm5iZiI6MTcyNjAzMDY2NiwicGF0aCI6Ii8xNDIzODUxOC8zNjYyNzI2MzctMDhlOWU5ODctMmZmNC00YjdhLWI3NTMtMmU5NWM5ZmJlZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA0NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDhkMzBiMmEyNjVmYzg4NWZlZGM2M2VmODliNmRmOWQ2MTVjNWM5MzI2MGZhNzgyN2QyNGRjOGJhOGJlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dzOh4flq6t4wsuf6UePe2iDuYERz7GuFFyhBDJ1O-0) ![image](https://private-user-images.githubusercontent.com/14238518/366272615-2ed2da9d-b79b-4394-aac5-eed2bb8a88e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzA5NjYsIm5iZiI6MTcyNjAzMDY2NiwicGF0aCI6Ii8xNDIzODUxOC8zNjYyNzI2MTUtMmVkMmRhOWQtYjc5Yi00Mzk0LWFhYzUtZWVkMmJiOGE4OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA0NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNWYwODFlMmFiMDFhMDAzYWFiYjhlODBkODdjYjNlZjg0ZjYyZTgxNjNiOGYxZTYwY2JiZjVmYmMwYWQ5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp8Azozakm9n_Oi3RQ0By4NVOrbx3K8t7EncNxEYgLU)
> 
> 
> 
> @BiyuHuang please provide the app DSL.

em, it works now
it seems like I setup an empty property
