### ISSUE TITLE
werkzeug.exceptions.InternalServerError: 500 Internal Server Error

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#5457]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I get an error when using an agent for RAG Q&A.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/explore/wraps.py", line 39, in decorated
    return view(installed_app, *args, **kwargs)
  File "/app/api/controllers/console/explore/message.py", line 152, in get
    raise InternalServerError()
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by yuhp-zts** [comment]
The service versions in my docker-compose.yaml file are as follows:
web:
    image: langgenius/dify-web:0.6.10
 worker:
    image: langgenius/dify-api:0.6.10
api:
    image: langgenius/dify-api:0.6.10

**Comment by yuhp-zts** [comment]
> The "werkzeug.exceptions.InternalServerError: 500 Internal Server Error" in your self-hosted Dify version 0.6.10 setup is likely due to a version mismatch between the `web` and `api` services in your Docker setup. Specifically, your `web` service is using `langgenius/dify-web:0.6.10`, while your `api` service is using `langgenius/dify-api:0.6.11`. This mismatch can cause compatibility issues.
> 
> To resolve this, ensure both services use the same version. Update the `web` service to use `langgenius/dify-web:0.6.11` in your `docker-compose.yaml`:
> 
> ```yaml
> # Frontend web application.
>   web:
>     image: langgenius/dify-web:0.6.11
>     restart: always
>     environment:
>       CONSOLE_API_URL: ''
>       APP_API_URL: ''
>       SENTRY_DSN: ''
>     # uncomment to expose dify-web port to host
>     # ports:
>     #   - "3000:3000"
> ```
> 
> This should help avoid the internal server error by ensuring compatibility between the `web` and `api` services [[1]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

The service versions in my docker-compose.yaml file are as follows:
web:
image: langgenius/dify-web:0.6.10
worker:
image: langgenius/dify-api:0.6.10
api:
image: langgenius/dify-api:0.6.10

**Comment by crazywoola** [comment]
Can you upgrade to latest version to see if this issue persists?

**Comment by yuhp-zts** [comment]
> Can you upgrade to latest version to see if this issue persists?

This issue is not present in the latest version.
