### ISSUE TITLE
embedded chatbot 需要重置会话的按钮

### ISSUE THREAD

**Issue by yanghx-git** [langgenius/dify#5458]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

抱歉，英语实在不好。我我看到 #4054 提出类似问题。在iframe 嵌入的模式下。web页面不显示header，是没办法重置会话的，只能手动删除`localstorage ` 。希望能提供一个重置会话的按钮。
**现在的界面**

<img width="1247" alt="image" src="https://github.com/langgenius/dify/assets/30469680/8e24c828-9e27-459c-8ace-193822127875">

**希望的效果**<img width="1338" alt="image" src="https://github.com/langgenius/dify/assets/30469680/88311e86-89d8-454f-ba3c-43a20b2266d0">

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by yanghx-git** [comment]
怎么直接关了，是不能做这个功能吗 @crazywoola

**Comment by crazywoola** [comment]
违法 Language Policy #1542
