### ISSUE TITLE
Run failed: 1 validation error for KnowledgeRetrievalNodeData single_retrieval_config

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#5459]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I get an error when calling the knowledge base retrieval node in chatflow.
Run failed: 1 validation error for KnowledgeRetrievalNodeData
single_retrieval_config -> model -> mode
field required (type=value_error.missing)
![Uploading 微信图片_20240621095250.png…]()

**Comment by yuhp-zts** [comment]
> The error message indicates that the `mode` field in the `model` configuration for the `KnowledgeRetrievalNodeData` is missing. You need to configure the retrieval strategy, which includes setting the retrieval mode.
> 
> To resolve this issue, ensure that you have specified the retrieval mode in your configuration. Here is an example of how you might configure the retrieval mode:
> 
> ```json
> {
>   "single_retrieval_config": {
>     "model": {
>       "mode": "N-choose-1"  // or "Multi-way"
>     }
>   }
> }
> ```
> 
> Make sure to replace `"N-choose-1"` with the appropriate mode you intend to use. This should be done in the configuration settings of your knowledge base retrieval node.
> 
> Additionally, ensure that the `model` configuration includes all necessary fields such as `name`, `provider`, and `completion_params` as shown in the `_fetch_model_config` method:
> 
> ```python
> def _fetch_model_config(self, node_data: KnowledgeRetrievalNodeData) -> tuple[
>         ModelInstance, ModelConfigWithCredentialsEntity]:
>     model_name = node_data.single_retrieval_config.model.name
>     provider_name = node_data.single_retrieval_config.model.provider
>     model_mode = node_data.single_retrieval_config.model.mode
>     completion_params = node_data.single_retrieval_config.model.completion_params
> 
>     if not model_mode:
>         raise ValueError("LLM mode is required.")
> 
>     # Additional code to fetch and validate model configuration
> ```
> 
> Ensure that all these fields are correctly set in your configuration to avoid validation errors [[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/workflow/node/knowledge-retrieval.md)[[2]](https://github.com/langgenius/dify/blob/main/api/core/workflow/nodes/knowledge_retrieval/knowledge_retrieval_node.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

the mode i choose is "Multi-way"
![image](https://github.com/langgenius/dify/assets/150892078/2cb4572a-aeae-40f8-a842-e3699cd8c3b9)
![image](https://github.com/langgenius/dify/assets/150892078/3949e362-481b-4216-b538-644bd76d058d)

**Comment by JohnJyong** [comment]
pls provide more details about the issue , such as the error logs in your docker container, thanks @yuhp-zts

**Comment by mikegong** [comment]
I encountered the same problem. I can see the rerank model name in graph filed of workflow_runs table. But somehow the knowledge retrieval just did not work, including preview mode. Have no clue what's going on.

**Comment by zxk777** [comment]
Maybe it is because that you added a knowledge base before in the workflow, but you then deleted that knowledge base. In this situation, the references in the workflow will not be removed and the error will occur. Try to remove the nodes which reference the deleted knowledge base.

![Image](https://github.com/user-attachments/assets/0e86637d-c846-4c12-89fc-21e46c84fae4)
