### ISSUE TITLE
Knowledge base does not show up for collaborators

### ISSUE THREAD

**Issue by jnc-nj** [langgenius/dify#5464]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create workspace -- create knowledge base -- add collaborator to workspace

### ✔️ Expected Behavior

Collaborators can see created knowledge base

### ❌ Actual Behavior

Collaborators can't see created knowledge base

**Comment by jnc-nj** [comment]
Got it.

**Comment by chunbaisikio** [comment]
when I use Api to create a knowledge base,Can I change the permission using api?
