### ISSUE TITLE
Support for AWS multi-region select

### ISSUE THREAD

**Issue by shing19** [langgenius/dify#5466]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

So far we can choose one region from bedrock, yet claude sonnet 3.5 is hold on us-east and claude opus is hold on us-west. We cannot use both models at same time. 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by colemvnio** [comment]
I'd like to add, that Canada is not offered as a region, although it is available.
