### ISSUE TITLE
Claude 3.5 Sonnet is not supported in AWS bedrock

### ISSUE THREAD

**Issue by shing19** [langgenius/dify#5467]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

First of all, a huge thank you to the Dify team for the prompt update supporting Claude 3.5 Sonnet! As AWS cloud service users, we are excited about the addition of Anthropic's new model and hope to see AWS Bedrock model configuration implemented alongside it. We have already enabled the Claude 3.5 Sonnet model in the US-East region on our backend, but we haven't spotted it in Dify's configuration interface. We kindly request that you add this option. Thank you!

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/5461
