### ISSUE TITLE
Add slot nodes dedicated to collecting critical information

### ISSUE THREAD

**Issue by Geek-Bob** [langgenius/dify#5471]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

For example:
The user said, "Share whiteboard."   The DMS recognizes that the user's intention is to "share the whiteboard."
Agents (DMS) : Ask users who to share with.
The user said: "Share to ***".   The DMS extracts the name of the person to share from the user's response.
Agent (DMS) : Calls the API to query a list of possible sharers based on the name provided by the user.   This API call can be pre-programmed, or a specialized query service needs to be developed.   If multiple users are queried, the agent generates a display list, asks the user for specific responses to share, and determines the sharing person with the user.
User: Complete confirmation, e.g. say "Yes"
Agents (DMS) : Perform actions to share whiteboards, which may include updating databases, API, and so on.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by van51** [comment]
Hello! Sorry for bumping this closed issue, but I don't see how this is supported in a chatflow. Could you point me in the right direction?
