### ISSUE TITLE
"Modified Unsuccessfully"  when modifying RAG config in "Knowledge Settings" tab

### ISSUE THREAD

**Issue by thibaudbrg** [langgenius/dify#5473]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have theses versions installed in my docker compose:

docker.io/langgenius/dify-web             0.6.11
docker.io/langgenius/dify-api               0.6.11
docker.io/ubuntu/squid                        latest
docker.io/langgenius/dify-sandbox      0.2.1
docker.io/library/redis                          6-alpine
docker.io/library/postgres                   15-alpine 

docker.io/langgenius/qdrant               v1.7.3
docker.io/semitechnologies/weaviate  1.19.0

I encounter the same problem no matter if I use Weaviate or Qdrant for the Vector database.

After having susccefully created a RAG and added a document to it:

![image](https://github.com/langgenius/dify/assets/73235385/46759c43-46bc-4463-837f-fc5626fd4d23)

When i want to edit the embedding model or any other parameters in the tab "knowledge settings"

![image](https://github.com/langgenius/dify/assets/73235385/64865e3a-7524-4949-bb42-92ec7aea8896)

I get the error Modified unsuccessfully for any changes in this tab (e.g. If I modify the description, the embedding model, the retrieval settings, the index methods, etc... etc...) :

![image](https://github.com/langgenius/dify/assets/73235385/e4214f81-453d-482e-acc4-a40654fbfc0e)
![image](https://github.com/langgenius/dify/assets/73235385/9ee29792-4560-47c8-a066-d5ed4dd44ace)

No logs flag this behaviour in any container, even in DEBUG. 
By looking at the code I think the catch error is coming from here:

https://github.com/langgenius/dify/blob/92ddb410cdaaeca6c6a8b2de542211c0efbcf9a2/web/app/components/app/configuration/dataset-config/settings-modal/index.tsx#L115

### ✔️ Expected Behavior

Behing able to modify the Knowledge retrieval settings in the "Knowledge Settings" tab.

### ❌ Actual Behavior

An error "Modified Unsuccessfully" is flagged.

**Comment by crazywoola** [comment]
I looked at the code and I might need you to provide some payload and response for the network request to continue looking at it, as I didn't reproduce the issue after the main branch was uploaded
