### ISSUE TITLE
Get segments of a knowledge base via APIs

### ISSUE THREAD

**Issue by ifsheldon** [langgenius/dify#5477]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes. I'd like to fetch segments in a knowledge base to edit and add new segments. How can I get these via APIs? I saw in the documentation that we can add segments via APIs, but I didn't see how to fetch them.

Probably we've already had this API but not documented it?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated feature request. We have added this to our dev plan already.
