### ISSUE TITLE
Workflow published application does not display output

### ISSUE THREAD

**Issue by Shivak11** [langgenius/dify#5479]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I created a workflow (not chatflow) based on the Long story generator. When published as an application, the output is blank. This same problem does not exist in chatflow, only in workflow.

![image](https://github.com/langgenius/dify/assets/121174127/6c9d7ce5-0af5-47b4-99b5-e083102f8b85)

Here is the workflow: 
![image](https://github.com/langgenius/dify/assets/121174127/29dca69f-6482-42ea-b6fc-756f59d8fbf8)

### ✔️ Expected Behavior

The published application should show the complete output.

### ❌ Actual Behavior

The published application does not show any output.

**Comment by crazywoola** [comment]
https://udify.app/workflow/qoAnyufJMowzALiz Can't reproduce on Cloud.

**Comment by Shivak11** [comment]
On my MacBook also it runs the workflow but does not show an output. It works perfectly on the workflow debugging screen. The logs show that the report has been generated but the user application does not show the output.

![image](https://github.com/langgenius/dify/assets/121174127/43b4f2b4-a7c5-41c2-9ea6-733d94528c72)

![image](https://github.com/langgenius/dify/assets/121174127/72f62a1b-f4a8-4995-a074-7798fc050ead)

**Comment by crazywoola** [comment]
Can you export and. DSL and paste things in the end node of tracing?
