### ISSUE TITLE
0.6.11升级失败，镜像拉取超时问题

### ISSUE THREAD

**Issue by dming519** [langgenius/dify#5481]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

超时了，尝试了几种方法都没解决，求救一下大神。
![bug1](https://github.com/langgenius/dify/assets/28173211/91f30ac1-4f61-413d-b895-1b90fdfa71ca)
![bug2](https://github.com/langgenius/dify/assets/28173211/d706555c-e673-41ae-91d9-50c1f3ce8f19)
![bug3](https://github.com/langgenius/dify/assets/28173211/129c19e0-94d6-44c1-9da0-361d31d57a13)

**Comment by hxgqh** [comment]
貌似是最近国内的所有docker镜像集体停了？能否加一个国内源的docker-compose.yml？

**Comment by dming519** [comment]
我根据上面的解决方案进行设置：export COMPOSE_HTTP_TIMEOUT=200，把超时时间设置到2000，最后还是i/o timeout问题。如果有成功解决的朋友麻烦分享一下解决的方案，非常感谢。

**Comment by nickboyabc** [comment]
关注中，好像要改配置文件？

**Comment by xinzhics** [comment]
我也是，更改了阿里云的镜像地址也不管用，不知道这个镜像是否仅在docker hub上，国内这个网，太头疼了

**Comment by ycdhqzhiai** [comment]
有解决的吗

**Comment by dming519** [comment]
看这个https://github.com/imashen/docker-aio，配置docker的加速源

**Comment by lichunnan** [comment]
> 看这个https://github.com/imashen/docker-aio 配置docker的加速源

这个方法好用！感谢

**Comment by macqueen09** [comment]
@lichunnan  @dming519  链接失效了打不开呀， 有新链接嘛 thanks
