### ISSUE TITLE
Model Configuration Failure and Inability to Save

### ISSUE THREAD

**Issue by RGHuang** [langgenius/dify#5482]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![Screenshot 2024-06-21 at 4 17 12 PM](https://github.com/langgenius/dify/assets/55523307/013e8cf8-14cd-4972-a445-81df7de12115)

### ✔️ Expected Behavior

Can save parameter rule as expected

### ❌ Actual Behavior

Cannot save parameter rule as expected

**Comment by crazywoola** [comment]
Can you provide more details regarding this issue? The error log and the error code with details in the web console.

**Comment by laipz8200** [comment]
This issue is happening because you didn't enable the parameter switch. We don't save unused parameter values.
