### ISSUE TITLE
LLM node Support function calling

### ISSUE THREAD

**Issue by DomKing** [langgenius/dify#5486]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to orchestrate workflow by using agent node. The essence of an agent is also function calling. Currently, LLM only supports reasoning but not support function calling. In case of support, there are more ways to play with the workflow.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by MrOrz** [comment]
@dosu-bot if we want to contribute to the codebase so that Agents can be added to Workflows, where can we start?
