### ISSUE TITLE
The LLM Node change my input {variable} unexpectly

### ISSUE THREAD

**Issue by forrestsocool** [langgenius/dify#5493]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

when there are some special text in the  {variable} ，the LLM node will change id unexpectly during the data processing.  
the sepcial text is like "\<id:123123\>" it is useful when we need to append some additional information.

### ✔️ Expected Behavior

don't change the {variable}

### ❌ Actual Behavior

the sepcial text is like "\<id:123123\>" is deleted unexpectly

**Comment by forrestsocool** [comment]
sepcial text is like "/<id:123123/>"

**Comment by iamjoel** [comment]
I can't find the way to create a variable which includes special text like <id:123123>. Can you tell me way to create it? @forrestsocool

**Comment by forrestsocool** [comment]
> I can't find the way to create a variable which includes special text like id:123123. Can you tell me way to create it? @forrestsocool

there are several ways In my case, the variable is generated by a LLM node, which is used to distinguish from normal character and used by the downstream code node. For convenient, you can use the test ui of any node, and just input what u want directly.

**Comment by forrestsocool** [comment]
@iamjoel

**Comment by iamjoel** [comment]
> > I can't find the way to create a variable which includes special text like id:123123. Can you tell me way to create it? @forrestsocool
> 
> there are several ways In my case, the variable is generated by a upstream LLM node, which is used to distinguish from normal character and used by the downstream LLM/code node. For convenient, you can use the test ui of any node, and just input what u want directly.

@forrestsocool Can you provide a App DSL?

**Comment by forrestsocool** [comment]
DSL yml:
[test (1).zip](https://github.com/user-attachments/files/16154375/test.1.zip)


To Use:
1.click run
2.input variable as described in the pic
3.check result

**intput:**
![image](https://github.com/langgenius/dify/assets/3960433/fab64c4a-4e15-4524-8b28-b6765e2e1442)


**output:**
![image](https://github.com/langgenius/dify/assets/3960433/a1504817-3221-4c17-9045-4aa4e45c7aa6)

@iamjoel

**Comment by forrestsocool** [comment]
@iamjoel Anything progress？

**Comment by bslml** [comment]
same issue

**Comment by iamjoel** [comment]
@takatost some variable value includes special letters  would be ignored in prompt. 

**Prompt:**
<img width="395" alt="image" src="https://github.com/user-attachments/assets/36027d6f-dff3-4862-bc87-a83ef42443de">  

**Result:** 
<img width="403" alt="image" src="https://github.com/user-attachments/assets/f565f254-53f8-4d3f-a92d-f8354a789069">
<img width="408" alt="image" src="https://github.com/user-attachments/assets/56b1f918-fe61-421d-a9ab-272f1fa3018f">
