### ISSUE TITLE
Can't Connect to Firecrawl API (Data Source)

### ISSUE THREAD

**Issue by king-of-the-grackles** [langgenius/dify#5497]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Settings -> Data Source -> Website

1. Grab Firecrawl API Key from Firecrawl Dashboard
2. Paste API key into API Key Field
3. Leave Base URL field blank
4. CLick Save

### ✔️ Expected Behavior

Dify validates and saves API key config for FireCrawl

### ❌ Actual Behavior

Error - API key should start with "fc-"

API Key doesn't have fc- appended in their API dashboard

Tested appending fc- to API key and got this error: Failed to authorize. Status code: 401. Error: Unauthorized: Invalid token

**Comment by crazywoola** [comment]
We are working on it.
