### ISSUE TITLE
HTTP请求，到底应该怎么填？

### ISSUE THREAD

**Issue by lukefan** [langgenius/dify#5501]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

我有mailgun的账号，通过curl也可以成功跑起来。
想用咱们的HTTP请求节点，永远是401，文档，极其简陋，啥也没写。
curl -s --user 'api:<PRIVATE_API_KEY>' \
	 https://api.mailgun.net/v3/<Doman>/messages \
	 -F from='Mailgun Sandbox <postmaster@example.com>' \
	 -F to='name <name@example.com>' \
	 -F subject='Hello name' \
	 -F text='Congratulations name, you just sent an email with Mailgun! You are truly awesome!'

这个key死活不认啊。
我尝试了放在各种地方，都不对。

**Comment by lukefan** [comment]
我试过了，不行。
![未命名的设计1](https://github.com/langgenius/dify/assets/3324749/e713c7dd-2205-4a6e-b5d7-1bd5e5252e52)
![未命名的设计](https://github.com/langgenius/dify/assets/3324749/c2fd719b-d0e1-496a-b3c9-8294f1e37b45)

**Comment by lukefan** [comment]
我们有什么建议的发邮件方式吗？

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by lukefan** [comment]
做了base64的编码之后，终于获得了200的回复。
但是信依然没有收到。
你们是不是应该把这个转换，放到功能里面去？而不是让我到外面再去转换一次手填进去？
