### ISSUE TITLE
Issue warning Dockerfile for web 

### ISSUE THREAD

**Issue by TienLD-0801** [langgenius/dify#5512]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I don't know if this has any effect on the results of the website, but in the build area I see a warning
- the as keyword in the Dockerfile I can change to AS has been accepted
- Environment variables with the keyword ENV, I don't understand why they are waring, I still haven't been able to fix it
<img width="1254" alt="Screenshot 2024-06-23 at 00 08 37" src="https://github.com/langgenius/dify/assets/112608271/5c6454b4-c830-4ee7-a44c-087f13ff71f3">

**Comment by crazywoola** [comment]
I didn't see the warnings in our actions https://github.com/langgenius/dify/actions/runs/9626335852/job/26552194930.
Can you provide more details about the build enviroment?

**Comment by TienLD-0801** [comment]
@crazywoola 

Maybe each environment will be different because you are deploying using github's tool or a tool running under a virtual machine, ubuntu or linux, and you will not be notified, but because I am experimenting with my personal machine, it is so it will have some notice ?
Machine information:
MacOS : 14.5
Chip: M3pro

=> Hopefully in the future it can be fixed for local users! thank you !

**Comment by kurokobo** [comment]
These validations are introduced in BuildKit 0.14.0: 

> Default Dockerfile frontend has been updated to v1.8.0
> https://github.com/moby/buildkit/releases/tag/v0.14.0

> Many new validation rules have been added to verify that your Dockerfile is using best practices. These rules are validated during build and new "lint" subrequest can be used to only trigger validation without completing the whole build. 
> https://github.com/moby/buildkit/releases/tag/dockerfile/1.8.0

@crazywoola 

> I didn't see the warnings in our actions https://github.com/langgenius/dify/actions/runs/9626335852/job/26552194930.

Current GHA uses the latest BuildKit 0.14.1, so we can already see these warnings in GHA logs: 
 https://github.com/langgenius/dify/actions/runs/9626335852/job/26552194930#step:7:415


If we want to suppress these warnings, we should follow these rules:

- https://docs.docker.com/reference/build-checks/from-as-casing/
- https://docs.docker.com/reference/build-checks/legacy-key-value-format/

In addition to web, maybe the Dockerfile for the `api` should also be fixed. I can send PRs for this later, but of course if you are interested, you can have your PR made before mine :)

F.Y.I., patch for `web`:

```diff
diff --git a/web/Dockerfile b/web/Dockerfile
index f2fc4af2f..56957f092 100644
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -9,7 +9,7 @@ RUN apk add --no-cache tzdata
 
 
 # install packages
-FROM base as packages
+FROM base AS packages
 
 WORKDIR /app/web
 
@@ -22,7 +22,7 @@ COPY yarn.lock .
 RUN yarn install --frozen-lockfile
 
 # build resources
-FROM base as builder
+FROM base AS builder
 WORKDIR /app/web
 COPY --from=packages /app/web/ .
 COPY . .
@@ -31,17 +31,17 @@ RUN yarn build
 
 
 # production stage
-FROM base as production
+FROM base AS production
 
-ENV NODE_ENV production
-ENV EDITION SELF_HOSTED
-ENV DEPLOY_ENV PRODUCTION
-ENV CONSOLE_API_URL http://127.0.0.1:5001
-ENV APP_API_URL http://127.0.0.1:5001
-ENV PORT 3000
+ENV NODE_ENV=production
+ENV EDITION=SELF_HOSTED
+ENV DEPLOY_ENV=PRODUCTION
+ENV CONSOLE_API_URL=http://127.0.0.1:5001
+ENV APP_API_URL=http://127.0.0.1:5001
+ENV PORT=3000
 
 # set timezone
-ENV TZ UTC
+ENV TZ=UTC
 RUN ln -s /usr/share/zoneinfo/${TZ} /etc/localtime \
     && echo ${TZ} > /etc/timezone
 
@@ -59,7 +59,7 @@ COPY docker/pm2.json ./pm2.json
 COPY docker/entrypoint.sh ./entrypoint.sh
 
 ARG COMMIT_SHA
-ENV COMMIT_SHA ${COMMIT_SHA}
+ENV COMMIT_SHA=${COMMIT_SHA}
 
 EXPOSE 3000
 ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]
kuro@kuro-dev01:~/work/kurokobo/dify/web$ git diff --raw -p
:100644 100644 f2fc4af2f 000000000 M    web/Dockerfile

diff --git a/web/Dockerfile b/web/Dockerfile
index f2fc4af2f..56957f092 100644
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -9,7 +9,7 @@ RUN apk add --no-cache tzdata
 
 
 # install packages
-FROM base as packages
+FROM base AS packages
 
 WORKDIR /app/web
 
@@ -22,7 +22,7 @@ COPY yarn.lock .
 RUN yarn install --frozen-lockfile
 
 # build resources
-FROM base as builder
+FROM base AS builder
 WORKDIR /app/web
 COPY --from=packages /app/web/ .
 COPY . .
@@ -31,17 +31,17 @@ RUN yarn build
 
 
 # production stage
-FROM base as production
+FROM base AS production
 
-ENV NODE_ENV production
-ENV EDITION SELF_HOSTED
-ENV DEPLOY_ENV PRODUCTION
-ENV CONSOLE_API_URL http://127.0.0.1:5001
-ENV APP_API_URL http://127.0.0.1:5001
-ENV PORT 3000
+ENV NODE_ENV=production
+ENV EDITION=SELF_HOSTED
+ENV DEPLOY_ENV=PRODUCTION
+ENV CONSOLE_API_URL=http://127.0.0.1:5001
+ENV APP_API_URL=http://127.0.0.1:5001
+ENV PORT=3000
 
 # set timezone
-ENV TZ UTC
+ENV TZ=UTC
 RUN ln -s /usr/share/zoneinfo/${TZ} /etc/localtime \
     && echo ${TZ} > /etc/timezone
 
@@ -59,7 +59,7 @@ COPY docker/pm2.json ./pm2.json
 COPY docker/entrypoint.sh ./entrypoint.sh
 
 ARG COMMIT_SHA
-ENV COMMIT_SHA ${COMMIT_SHA}
+ENV COMMIT_SHA=${COMMIT_SHA}
 
 EXPOSE 3000
 ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]
```

**Comment by kurokobo** [comment]
Warnings for `api`: https://github.com/langgenius/dify/actions/runs/9626335852/job/26552194791#step:7:500

**Comment by crazywoola** [comment]
@kurokobo Thanks for the detailed information. I saw those warnings, PRs are always welcome :)
