### ISSUE TITLE
Support syncing knowledge from Confluence (Atlassian)

### ISSUE THREAD

**Issue by murtaza-motorwala** [langgenius/dify#5522]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Most companies use confluence to store knowledge like Kbase articles, policies, product support docs, workflows, management updates etc. Dify introduced "sync from website" option which is great but it would be nice if we could sync from websites like Confluence. 

### 2. Additional context or comments

Here's the link to their API documentation - https://docs.atlassian.com/atlassian-confluence/REST/6.6.0

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by lydqc** [comment]
+1

**Comment by VincePotato** [comment]
Sounds reasonable, I will add this requirement to the RAG backlog.

**Comment by cah-jonathan-cachat01** [comment]
was this integrated into Dify, or was it just added t othe RAG Backlog?? is the backlog available publically??

**Comment by murtaza-motorwala** [comment]
@VincePotato - Hey, can you please let us know if this has been implemented? You have closed the ticket but I suspect that this feature is still not added.

**Comment by em-le-ts** [comment]
+1

**Comment by 51ISI** [comment]
+1

**Comment by kylianhe** [comment]
+1

**Comment by Flouho** [comment]
any progress ?

**Comment by chenzhiqiang0518** [comment]
Expect dify to integrate with Confluence knowledge base.

**Comment by chenzhiqiang0518** [comment]
+1

**Comment by trend-ching-yi-ng** [comment]
+1

**Comment by cyng93** [comment]
+1

**Comment by US579** [comment]
+1

**Comment by kibarik** [comment]
+1
