### ISSUE TITLE
HTTP request module does not process files through form-data in its body.

### ISSUE THREAD

**Issue by murtaza-motorwala** [langgenius/dify#5530]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In the HTTP request module, there is no way to add a file. I am trying to use "form-data" in the body, but it does not seem to upload the file for processing.

<img width="1439" alt="image" src="https://github.com/langgenius/dify/assets/171589201/d54f92a4-97f4-4fa8-a0c1-af5d6b13e49f">

Note - And if we can get the file for processing from the "start" module, then that would be awesome.

### ✔️ Expected Behavior

The file should be uploaded in the HTTP request for further processing down the pipeline.

### ❌ Actual Behavior

It does not process the file. It only processes the JSON body.

**Comment by murtaza-motorwala** [comment]
@dosu - This is helpful. Thank you. Is there a way you can provide an option in the GUI to upload the files for HTTP request? I am trying to create a pipeline where I would let the user upload the file and then I would use it to extract the text using OCR which will be use further down the pipeline for different purposes.

**Comment by murtaza-motorwala** [comment]
@dosu - Can this be added an an enhancement in the next release please ?

**Comment by crazywoola** [comment]
We will use a unique node to process files in the future.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/5432
