### ISSUE TITLE
[Cloud] You have reached the batch upload limit of 20

### ISSUE THREAD

**Issue by davidphamle** [langgenius/dify#5532]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Click on `Knowledge`
2. Click on a Knowledge Base connecting to Notion
3. Click `Add Page`
4. Select a few checkboxes (total of uploaded page + newly selected page > 20)
5. Click on `Save`

### ✔️ Expected Behavior

- Able to add new page with more than 20 pages in Total Uploaded page, no limitation

### ❌ Actual Behavior

- See the error "You have reached the batch upload limit of 20"
- Cannot add more than 20 pages totally to the knowledge base
![image](https://github.com/langgenius/dify/assets/121055794/f658c725-31cd-47ef-a985-2ecf8eb6ccbe)

**Comment by crazywoola** [comment]
Please upgrade your account to Pro or team to upload more documents.

**Comment by davidphamle** [comment]
Dear @crazywoola, 

I am a Pro customer and I got this issue. Do you actually review the issue????

**Comment by crazywoola** [comment]
![image](https://github.com/langgenius/dify/assets/121055794/f658c725-31cd-47ef-a985-2ecf8eb6ccbe)
I think it's because the error message is overlapping the account type badge. :)

**Comment by zli06160** [comment]
Got the same error `"You have reached the batch upload limit of 50"` on Dify Cloud(Pro Plan == 59$/month), with a tiny table of 300 rows.

Getting around it was easy: just export to csv(or xlsx) file and upload the file directly when creating knowledge base.
