### ISSUE TITLE
git pull origin main is running with an error

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#5537]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.5.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Please commit your changes or stash them before you merge.
Aborting
What is the correct way to exit without the option?

**Comment by crazywoola** [comment]
Please read the git docs to resolve this issue. :) This is a general git usage issue. You should be able to goole it or use gpt to resolve this by yourself.
