### ISSUE TITLE
The code execution module in the workflow reports an error:Failed to parse result

### ISSUE THREAD

**Issue by Sakura4036** [langgenius/dify#5546]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I called the literature search API to get the titles and abstracts of the relevant literature, and the resulting json string needs to be parsed by the code execution module.

I tried to modify the `CODE EXECUTION CONFIGURATION` in the `env` (as shown below), however, the code execution module is still unable to process the large amount of data.
![image](https://github.com/langgenius/dify/assets/42060616/b76eaa6a-67a2-4f89-9acd-1b45e048478d)

### ✔️ Expected Behavior

The code execution module successfully parses the string obtained from the API.

I call the literature search API to get the titles and abstracts of the relevant literature, if I only get the abstract information of 20 literature, the code execution module parses and executes successfully.
![image](https://github.com/langgenius/dify/assets/42060616/b0cf2fac-27f9-4808-be2b-147679ea07c3)

### ❌ Actual Behavior

however, due to the fact that the number of literature searched is too large (1,000 articles, about 2 million characters), the parsed data can not be parsed and output.

![image](https://github.com/langgenius/dify/assets/42060616/c6144e3c-69b4-4bbd-9ed6-145605f62345)

**Comment by xixici** [comment]
same +1

**Comment by forrestsocool** [comment]
same +1
too many limitation in the cloud version

**Comment by xwwxyd** [comment]
same +1
I'm using https://cloud.dify.ai/, in the platform workflow code Execution node, it can't output long text
how can I solve it ?

**Comment by m0o0scar** [comment]
> same +1 I'm using https://cloud.dify.ai/, in the platform workflow code Execution node, it can't output long text how can I solve it ?

same here 😡

**Comment by 948024326** [comment]
> > same +1 I'm using https://cloud.dify.ai/, in the platform workflow code Execution node, it can't output long text how can I solve it ?
> 
> same here 😡

do u solve this question? i meet the sam - - ||

**Comment by Sakura4036** [comment]
> > > same +1 I'm using https://cloud.dify.ai/, in the platform workflow code Execution node, it can't output long text how can I solve it ?
> > 
> > 
> > same here 😡
> 
> do u solve this question? i meet the sam - - ||

no, i didn't. I no longer output excessively long strings in nodes
