### ISSUE TITLE
Streamed printing of data returned by the tool

### ISSUE THREAD

**Issue by kiedeng** [langgenius/dify#5547]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I customize tools, they can only return data using return, and the data can only be returned after the tool has completely finished. However, I have some tools that take a long time and return data in a streamed fashion, meaning they return some data after each process completes. How can I send the streamed return values from the tool to the front end? Can this be achieved using something like queuemanager.publish()? Is there a related demo I can refer to?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by ricemouse** [comment]
Seems currrently only LLM node can return streamd data. I want this feature for http node as well.
