### ISSUE TITLE
listen_timeout=600, causes flow stop

### ISSUE THREAD

**Issue by yaohongfenglove** [langgenius/dify#5548]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

api/core/app/apps/base_app_queue_manager.py: AppQueueManager: listen: **listen_timeout** is limited to 600 seconds, causing the  flow to stop responding after 600 seconds, even though **WORKFLOW_MAX_EXECUTION_TIME**  is set to 1200 seconds. 

### ✔️ Expected Behavior

When **WORKFLOW_MAX_EXECUTION_TIME** is set to 1200 seconds, the flow can run for 20 minutes.

### ❌ Actual Behavior

in reality, it only runs for 10 minutes before stopping.

**Comment by laipz8200** [comment]
We've made this timeout configurable in the latest version. Please upgrade and set `APP_MAX_EXECUTION_TIME`.

**Comment by danialcheung** [comment]
> We've made this timeout configurable in the latest version. Please upgrade and set `APP_MAX_EXECUTION_TIME`.

I'm experiencing the same issue with the 0.6.11 docker container as well, although the default is set to `1200` seconds, it will stop running at `600` seconds. I even tried replacing `listen_timeout = APP_MAX_EXECUTION_TIME` with `listen_timeout = 10000` in `core/app/apps/base_app_queue_manager.py` and it still times out at `600` seconds. I don't believe this was an issue with 0.6.10 as I was able to change the `timeout` duration and it functioned correctly.
