### ISSUE TITLE
Inconsistency across deployment mediums regarding Anthropic's Sonnet 3.5 model. 

### ISSUE THREAD

**Issue by sid-newby** [langgenius/dify#5549]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The new Sonnet model ( claude-3-5-sonnet-20240620 ) is successfully returned as an option when configuring the provider (Anthropic API) after entering an API key in the cloud edition. 

After performing the same operation with the docker deployment, all models except claude-3-5-sonnet-20240620 return.  Google Chrome console reports 404, the web app throws an error modal at the top of the page. 

Source code included with git repo contains /app/api/core/model_runtime/model_providers/anthropic/llm/claude-3-5-sonnet-20240620.yaml and _position.yaml contains definition for claude-3-5-sonnet-20240620. 

Docker image does not contain the model's .yaml and the definition is missing from the position.yaml. 

I was able to resolve this by simply modifying and saving the _position.yaml file and uploading my git source provided claude-3-5-sonnet-20240620.yaml to the llm directory under /anthropic. 

###

In the same vein, I noticed the docker distribution has a number of vulnerabilities that i'd like to patch out. Do you guys maintain the image in that respect, or should I wait for updates and pull? 

Thanks. 

### ✔️ Expected Behavior

Consistency across web hosted, containerized and distributed source code and functionality. 

### ❌ Actual Behavior

Troubleshooting and inconsistency across the mediums, leading to 3 hours of my life gone. 
![1  Localhost-Docker OpenAI Compatible Config Response](https://github.com/langgenius/dify/assets/10550908/92eecc50-597a-4555-b56e-841767140b81)
![2  Localhost-Docker Anthropic Successful Configuration](https://github.com/langgenius/dify/assets/10550908/1d6cac48-38ea-4e63-b989-91a98ba35fb2)
![3  Localhost-Docker Anthropic Fails to Return claude-3-5-sonnet-20240620](https://github.com/langgenius/dify/assets/10550908/ea17c031-670d-4939-97e7-a25fc6555cc7)
![4  Cloud Hosted Model Anthropic Successfully Returns claude-3-5-sonnet-20240620](https://github.com/langgenius/dify/assets/10550908/9736b0c6-fa23-413b-9334-04417467f3a1)
![5  GitHub Source Code_ Model Definition _position yaml for Anthropic Configured for claude-3-5-sonnet-20240620](https://github.com/langgenius/dify/assets/10550908/5ad8e200-9b6d-4c92-9fd4-7c8f58b68f72)
![6  Docker Source Code_ Model Definition Anthropic Not Configured for claude-3-5-sonnet-20240620](https://github.com/langgenius/dify/assets/10550908/37196a01-8303-40d4-a01e-06628808aa15)
![7  Localhost-Docker Anthropic Now Returns claude-3-5-sonnet-20240620](https://github.com/langgenius/dify/assets/10550908/9f4244e9-cf84-44e7-b109-25a11573af9b)

**Comment by crazywoola** [comment]
> After performing the same operation with the docker deployment, all models except claude-3-5-sonnet-20240620 return. Google Chrome console reports 404, the web app throws an error modal at the top of the page.

Hello, that's because we haven't tagged the new version. So it won't be able to display the the 3.5-sonnet as expected.  That way you resolve this issue looks good to me.

> In the same vein, I noticed the docker distribution has a number of vulnerabilities that i'd like to patch out. Do you guys maintain the image in that respect, or should I wait for updates and pull?

And we are working on it already.
