### ISSUE TITLE
Error: An error occurred in the Server Components render. 

### ISSUE THREAD

**Issue by elroystar** [langgenius/dify#5551]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

web-1         | 11:37:39 0|dify-web  | RangeError: Incorrect locale information provided
web-1         | 11:37:39 0|dify-web  |     at Intl.getCanonicalLocales (<anonymous>)
web-1         | 11:37:39 0|dify-web  |     at f (/app/web/.next/server/chunks/4445.js:43:36660)
web-1         | 11:37:39 0|dify-web  |     at b (/app/web/.next/server/chunks/2518.js:119:54047)
web-1         | 11:37:39 0|dify-web  |     at D (/app/web/.next/server/chunks/2518.js:119:46997)
web-1         | 11:37:39 0|dify-web  |     at em (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226)
web-1         | 11:37:39 0|dify-web  |     at /app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142926
web-1         | 11:37:39 0|dify-web  |     at Array.toJSON (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146504)
web-1         | 11:37:39 0|dify-web  |     at stringify (<anonymous>)
web-1         | 11:37:39 0|dify-web  |     at eR (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134889)
web-1         | 11:37:39 0|dify-web  |     at eP (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135332)
web-1         | 11:37:39 0|dify-web  | [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
web-1         | 11:37:39 0|dify-web  |   digest: '4268659373'
web-1         | 11:37:39 0|dify-web  | }

**Comment by iamjoel** [comment]
Can you provide more detail to reproduce this issus? @elroystar
