### ISSUE TITLE
core.model_runtime.errors. invoke. InvokeError: xinferencel Error: Invalid URL

### ISSUE THREAD

**Issue by qjy706** [langgenius/dify#5552]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Configured xinference embedding and rerank interfaces  and the model is bce_embedding and bce_rerank
2. Two model interfaces are configured in the model configuration interface
3. The URL I filled in at the beginning was http://xxxx:9997
4. During document vectorization, the log shows that the URL is invalid
5. When I go back and open the configuration interface, I find that the URL has become secret text, but the previously configured Ollama is still readable.
6. 
![0bf2fa0d8aba23a32c9830da99bd75ad9ef7497c3ae24f76499bb40bb50e31d2](https://github.com/langgenius/dify/assets/43703581/ed1be8c8-5d8d-4271-aff2-1a19e9a9a74a)
![2b93165a14dc454912fac5f7baf098c00a1ceb499828920ee50112fb751e56a6](https://github.com/langgenius/dify/assets/43703581/90662d04-e8c0-4e0b-a08a-f905bfe55a8e)

### ✔️ Expected Behavior

The document is successfully vectorized and can be retrieved

### ❌ Actual Behavior

url is invaild

**Comment by qjy706** [comment]
@dosu, Thanks for your reply. I have configured the backend request address of flask, and other functions are running normally. The only problem is this API interface, because from the error log, the stored characters in the data table may be encrypted?

**Comment by laipz8200** [comment]
Could you try upgrading to version 0.6.11 and see if the issue still occurs?

**Comment by qjy706** [comment]
> Could you try upgrading to version 0.6.11 and see if the issue still occurs?您可以尝试升级到0.6.11版本看看问题是否仍然存在？
Unfortunately, this problem still exists. It seems that there is a problem in the encryption and decryption process of the URL.

**Comment by laipz8200** [comment]
@qjy706 Sorry, we couldn’t reproduce the issue. Could you please check if the problem occurs on [our cloud service](https://cloud.dify.ai)? If the issue persists, feel free to reopen this issue.

**Comment by fzxs8** [comment]
我也遇到了同样的问题， v0.10.0 
![企业微信截图_17296529062066](https://github.com/user-attachments/assets/86728273-9c97-4c26-8485-45d5cf4226d1)
