### ISSUE TITLE
images download failed

### ISSUE THREAD

**Issue by Tekkaman-HB** [langgenius/dify#5557]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

error pulling image configuration: download failed after attempts=6: net/http: TLS handshake timeout
<img width="1502" alt="image" src="https://github.com/langgenius/dify/assets/48499574/114b332d-13fe-494d-80d5-8623742e72d9">

### ✔️ Expected Behavior

download 0.6.11 images

### ❌ Actual Behavior

download failed

**Comment by crazywoola** [comment]
This is a general network issue.
