### ISSUE TITLE
Q&A分段数据集格式应该是怎样的？

### ISSUE THREAD

**Issue by lingaoan2024** [langgenius/dify#5560]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

我用了多种格式，都无法正常显示分段，但索引正常创建了，在召回测试中无法查询
第一种格式：txt文本中一行Q，一行A，用两行作为一个分段，在A结束后面加上一个|，方便分段
例如：Q:XXXXX?
A:XXXXX|
或者Q XXXXX?
A XXXXX|
第二种格式：csv，分为两列，一列问题，一列答案
以上两种都不行，请教各位大神，应该如何配置

**Comment by jokerElsa** [comment]
请问这个问题有解决吗，分段标识符支持正则表达式吗？
