### ISSUE TITLE
Invalid recall test

### ISSUE THREAD

**Issue by lingaoan2024** [langgenius/dify#5564]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/172566511/8d1dfdcb-94b4-47bc-a0c8-449d800389a8)
As shown in the figure, the corresponding results can be directly queried through keywords in the files of the knowledge base.However, in the recall test, the same query result was incorrect. The configuration information and query result are shown in the following figure
![image](https://github.com/langgenius/dify/assets/172566511/b73c5702-9a25-4f2b-a567-71899b8b7c0d)
![image](https://github.com/langgenius/dify/assets/172566511/9d1e6319-70bf-4cd9-a169-dcd65ba7ad53)

**Comment by crazywoola** [comment]
The keyword query is different from recall test, the first one use the keyword  to do a full text search directly in the database while it do a vector query in vector database. So this is a expected behavior.
