### ISSUE TITLE
Markdown file parsing error, chunk is not good.

### ISSUE THREAD

**Issue by blankbro** [langgenius/dify#5569]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

import https://github.com/blankbro/mqtt-storm/blob/master/README.md

![image](https://github.com/langgenius/dify/assets/31715758/cb32383d-45ea-4401-b602-501a013578c4)

### ✔️ Expected Behavior

<img width="877" alt="md截图" src="https://github.com/langgenius/dify/assets/31715758/d1c3258a-8feb-4f9a-90ee-4f475710e12c">

Keep the picture link in markdown.
Keep markdown format.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/31715758/3a659f45-2706-4eae-bbdb-c5f7960defaf)
![image](https://github.com/langgenius/dify/assets/31715758/8455023f-d0d4-45c5-88df-32768f18fd6f)

**Comment by crazywoola** [comment]
Please use the custom separate identifier to do it. :)

**Comment by blankbro** [comment]
> Please use the custom separate identifier to do it. :)

![image](https://github.com/langgenius/dify/assets/31715758/45efa4b4-cb58-40e8-8bf4-1236a82135c1)
![image](https://github.com/langgenius/dify/assets/31715758/df182f11-f34d-481c-af55-4bd63b9f64d9)

Is that it? But my problem still exists.

**Comment by crazywoola** [comment]
Yes, you need to choose which identifier you would like to use. For example, you could fill in ` ###`

**Comment by blankbro** [comment]
> Yes, you need to choose which identifier you would like to use. For example, you could fill in ` ###`

<img width="941" alt="image" src="https://github.com/langgenius/dify/assets/31715758/1b13948a-8767-46e1-bd4a-d4d2298bfad9">

problem still exists.

**Comment by crazywoola** [comment]
<img width="844" alt="image" src="https://github.com/langgenius/dify/assets/100913391/ff0c282d-5a55-4e23-8fba-9a83c2d7e329">
You doc is segementing by `##`, I mean for example `###`, you should change it according to your needs.

**Comment by blankbro** [comment]
> <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/100913391/344442393-ff0c282d-5a55-4e23-8fba-9a83c2d7e329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MjA1NTgsIm5iZiI6MTcxOTcyMDI1OCwicGF0aCI6Ii8xMDA5MTMzOTEvMzQ0NDQyMzkzLWZmMGMyODJkLTVhNTUtNGUyMy04ZmJhLTlhODNjMmQ3ZTMyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNDA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2UxYThmMDcyYjFhNmE1OGUzODE4YmNkNjdkYzNlYWVlYWZiYWRkMGE4ZjY2NGE4NWZjNzI0MmY4YmIzMjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IroAPHJPnsgBD5ZcK5oP2FquTiNxljQbmNNymvWfy38"> Your doc is segmenting by `##`, I mean for example `###`, you should change it according to your needs.

<img width="1417" alt="image" src="https://github.com/langgenius/dify/assets/31715758/ad2f5b84-e6c0-4d3f-be70-485cd076a2c2">
problem still exists.

**Comment by tangyoha** [comment]
@crazywoola hi, After my investigation, I found that it was caused by the commit https://github.com/langgenius/dify/pull/2528. The md file was processed and the pictures and links were automatically removed.  
![image](https://github.com/langgenius/dify/assets/39958403/219bdc20-a3b3-4609-9954-e50ac61a978d)

**Comment by blankbro** [comment]
I have upgraded to version 0.6.14, and the issue with image links being removed has been resolved.
However, at the same time, a new problem has been discovered: the code blocks have been cut off.

![image](https://github.com/user-attachments/assets/9e399788-9df4-4027-9462-4f527e6545b6)

**Comment by tangyoha** [comment]
@blankbro hi， can you give me a example？

**Comment by blankbro** [comment]
> @blankbro hi， can you give me a example？

this md file https://github.com/blankbro/mqtt-storm/blob/master/README.md

**Comment by tangyoha** [comment]
@blankbro hi, can you show me the result?

**Comment by blankbro** [comment]
> @blankbro hi, The code is split. Are you using this split document?

@tangyoha Yes, you can to try.

**Comment by tangyoha** [comment]
@blankbro hi, The problem does exist, please raise another issue.

**Comment by blankbro** [comment]
> @blankbro hi, The problem does exist, please raise another issue.

new issue is https://github.com/langgenius/dify/issues/6421
