### ISSUE TITLE
Claude 3.5 Sonnet is not yet available through AWS Bedrock

### ISSUE THREAD

**Issue by YYyp99** [langgenius/dify#5571]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We access the Claude series models through AWS Bedrock. Recently, Claude 3.5 Sonnet was newly released, and we have already enabled the model in Bedrock. However, I cannot find the Claude 3.5 Sonnet model in the Bedrock model configuration within Dify.
![image](https://github.com/langgenius/dify/assets/120240141/0639dad9-d9d4-47b3-8700-39dcaaf90d76)
![image](https://github.com/langgenius/dify/assets/120240141/3c7fb540-6b4a-49da-9563-333c854ccf4c)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This pr has been merged into main already, if you you using self-hosted docker version, please wait until our new release. :)
