### ISSUE TITLE
Suggested questions after answer feature is not available in some large language models. 

### ISSUE THREAD

**Issue by KinWang130** [langgenius/dify#5572]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When the system reasoning model uses Wenxin Yiyan or Zhipu AI, the next step problem suggestion function cannot be used, and the system reports an error. This is because the code has added parameter validation, in which the temperature parameter is set to 0 and cannot be less than the minimum value of the model. However, the temperature range of Wenxin Yiyan and Zhipu AI is (0, 1.0]. Moreover, the minimum value for Wenxin Yiyan is configured as 0.1.

The specific error and verification are as follows:

![image](https://github.com/langgenius/dify/assets/33823007/b0f15013-cabe-4e5c-9582-7b77a471cdcb)
![image](https://github.com/langgenius/dify/assets/33823007/caffeaa0-b641-45ca-aed9-f0681869ac10)
![image](https://github.com/langgenius/dify/assets/33823007/4c24eaa0-2395-4418-b8bc-c231ff29c325)
<img width="1220" alt="image" src="https://github.com/langgenius/dify/assets/33823007/cb55e1f9-2fa3-4405-9671-2a27a4b9043d">

### ✔️ Expected Behavior

I hope the default value of temperature in api.core.llm_generator.llm_generator.LLMGenerator.generate_suggested_questions_after_answer can be modified to 0.1 or other methods can be used to fix this bug.

The goal is to ensure that the "Next Question Suggestion" function can work normally.

  response = model_instance.invoke_llm(
      prompt_messages=prompt_messages,
      model_parameters={
          "max_tokens": 256,
          "temperature": 0.1
      },
      stream=False
  )

### ❌ Actual Behavior

ValueError: Model Parameter temperature should be greater than or equal to 0.1.

<img width="1350" alt="image" src="https://github.com/langgenius/dify/assets/33823007/b6e0f55e-a972-4591-b52a-1ae9a586dd3d">

**Comment by ouyang-yuxuan** [comment]
**I have the same problem with function calls.**
![image](https://github.com/user-attachments/assets/fd1f4285-3f18-46ee-99c2-6643ff18380d)
![image](https://github.com/user-attachments/assets/12f47cf1-c255-4881-9612-6ffd8cb8c94a)
**But it works fine in ordinary applications.**
![image](https://github.com/user-attachments/assets/2b16bc0c-edd2-4822-aec1-a348008f690a)
![image](https://github.com/user-attachments/assets/9f4609d5-9a19-41e8-8493-3f83c8c5d78d)
**The models involved are Wenxin Yiyan and qwen（百炼）.**

**Comment by 94163677** [comment]
The same problem with:
1. Create Knowledge.
2. "Segmenting in Question & Answer format" set to true.

error message:
 ERROR [Dummy-137] [app.py:838] - Exception on /console/api/datasets/indexing-estimate [POST]
 Traceback (most recent call last):
   File "/app/api/controllers/console/datasets/datasets.py", line 388, in post
     response = indexing_runner.indexing_estimate(current_user.current_tenant_id, extract_settings,
   File "/app/api/core/indexing_runner.py", line 305, in indexing_estimate
     response = LLMGenerator.generate_qa_document(current_user.current_tenant_id, preview_texts[0],
   File "/app/api/core/llm_generator/llm_generator.py", line 291, in generate_qa_document
     response = model_instance.invoke_llm(
   File "/app/api/core/model_manager.py", line 123, in invoke_llm
     return self._round_robin_invoke(
   File "/app/api/core/model_manager.py", line 302, in _round_robin_invoke
     return function(*args, **kwargs)
   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 66, in invoke
     model_parameters = self._validate_and_filter_model_parameters(model, model_parameters, credentials)
   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 782, in _validate_and_filter_model_parameters
     raise ValueError(
 ValueError: Model Parameter temperature should be greater than or equal to 0.1.

SourceCode: dify\api\core\llm_generator\llm_generator.py, line 291, it was set temperature to 0.01
![image](https://github.com/user-attachments/assets/e3645639-c673-4499-a70e-d2ff227d786e)

**Comment by Lyeluo** [comment]
i use some model like doubao、qwen got suggested is empty 。。like this
'{"result": "success", "data": []}'

**Comment by thepush2** [comment]
Hello, could you please tell me how to add the model on Aliyun Bailian platform? thank you。 (如何添加阿里云百炼平台上的模型到dify~)

**Comment by thepush2** [comment]
are the same, change the corresponding key can be
