### ISSUE TITLE
node single run panel show the node panel scrollbar

### ISSUE THREAD

**Issue by xinghuo-assistant** [langgenius/dify#5573]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

node single run panel show the node panel scrollbar

### ✔️ Expected Behavior

when node single run panel show, the node panel should be overflow-hidden.

### ❌ Actual Behavior

node single run panel show the node panel scrollbar
![scrollbar show error](https://github.com/langgenius/dify/assets/143053515/c415a6a8-c86c-4156-917e-5ca0b525de1d)
![scrollbar](https://github.com/langgenius/dify/assets/143053515/2e738643-a901-4e84-9545-02acfb64d8c9)

**Comment by xinghuo-assistant** [comment]
![image](https://github.com/langgenius/dify/assets/143053515/06c0e413-64fd-4fab-9f7b-e261f6daea8e)

![image](https://github.com/langgenius/dify/assets/143053515/52b62961-9e71-4740-9e93-54597aa35275)

**Comment by zxhlyh** [comment]
fixed #5574
