### ISSUE TITLE
Pass input parameters to iframe

### ISSUE THREAD

**Issue by jarednieder** [langgenius/dify#5575]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Same request as [this closed issue](https://github.com/langgenius/dify/issues/2841), there seems to be no simple way to pass data to user input fields when embedding an iframe. The current implementation has poor user experience as the user must type in some text which could be easily pre-filled.

### 2. Additional context or comments

Even better than pre-filling inputs would be to pre-fill inputs _and_ start the chat if all required inputs are present.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by ivanseidel** [comment]
This is an awesome feature. Receiving this context as "hidden" params would benefit more complex and specific purpose applications using dify's workflow

**Comment by diegotiemann** [comment]
I need this feeature too!

**Comment by charli-polo** [comment]
+1 😄
