### ISSUE TITLE
docker-compose up -d 系统macos报错

### ISSUE THREAD

**Issue by GallantZhangYu** [langgenius/dify#5576]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

nginx_1       | 2024/06/25 09:35:48 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (1: Operation not permitted)
nginx_1       | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (1: Operation not permitted)

ssrf_proxy_1  | 2024/06/25 09:35:50| FATAL: Unable to open configuration file: /etc/squid/squid.conf: (1) Operation not permitted

### ✔️ Expected Behavior

docker-compose up -d后正常启动

### ❌ Actual Behavior

nginx_1       | 2024/06/25 09:35:48 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (1: Operation not permitted)
nginx_1       | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (1: Operation not permitted)

ssrf_proxy_1  | 2024/06/25 09:35:50| FATAL: Unable to open configuration file: /etc/squid/squid.conf: (1) Operation not permitted

**Comment by GallantZhangYu** [comment]
使用以上修改后，问题没有解决

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by GallantZhangYu** [comment]
已经解决，最后发现是文件权限问题，当前拉取直接在macos的Download里面，当在Desktop里的一个文件夹下，拉取后，运行正常。
