### ISSUE TITLE
Parameter Extractor not working (Query not found)

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#5577]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce
![CleanShot 2024-06-25 at 12 00 34](https://github.com/langgenius/dify/assets/119136210/d975f401-cba8-48e8-9e4d-d52964040128)

Use the Paramater Extractor

### ✔️ Expected Behavior

Worked in previous versions

### ❌ Actual Behavior

Gives now has the error "Node Parameter Extractor run failed: Query not found"

**Comment by AndyMik90** [comment]
@takatost maybe related to the commit https://github.com/langgenius/dify/commit/4a031de0d9932aa0dde354fad47b4dbbfbe9d79a ?

**Comment by takatost** [comment]
This error message is a bit misleading, it's actually checking the content of the Input variable configured. Could you please check if there is a value for this Input variable in the Log?
