### ISSUE TITLE
glm-4-chat 添加后有问题

### ISSUE THREAD

**Issue by zps-509** [langgenius/dify#5579]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/109783453/55b22151-05d9-45b9-95ca-16477d9dd78e)

### ✔️ Expected Behavior

![img_v3_02bi_ca3a774d-e0e1-4f8a-bd02-94192893c68g](https://github.com/langgenius/dify/assets/109783453/a9dac1ec-b5ea-4cbe-bd4b-2bb4f4874ab8)

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/109783453/38602895-4a85-4460-9038-1af1d60ba8ea)

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by zps-509** [comment]
![image](https://github.com/langgenius/dify/assets/109783453/10aaa1ec-f04c-428f-a4a2-da8035b433fd)
hai还是不行呀，我直接掉 glm-4是可以的，到DIFY里面就是使用不了
