### ISSUE TITLE
Does the chat assistant support inputting images?

### ISSUE THREAD

**Issue by liu391447823** [langgenius/dify#5580]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We want to implement an intelligent customer service scenario, where customers often ask questions by providing both images and text. With the help of OCR technology, the intelligent customer service is able to analyze the content of the images and determine how to respond to the users. We also hope that the intelligent customer service can reply to images as well.

### 2. Additional context or comments

We want to implement an intelligent customer service scenario, where customers often ask questions by providing both images and text. With the help of OCR technology, the intelligent customer service is able to analyze the content of the images and determine how to respond to the users. We also hope that the intelligent customer service can reply to images as well.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes it does.

<img width="1368" alt="image" src="https://github.com/langgenius/dify/assets/100913391/c7b05e08-471e-4061-9e89-c329c9f81ffd">

**Comment by liu391447823** [comment]
thank you
