### ISSUE TITLE
Firecrawl gets stuck

### ISSUE THREAD

**Issue by murtaza-motorwala** [langgenius/dify#5584]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have been trying to scrape a website. I have the right API keys from the firecrawl.dev and enough credits. It starts to find the pages and says - Total pages scraped 312/312 but does not display the pages or title for actually scraping them. I have been struggling with it for past 2 days. Tried to clear the cache, restarted the containers etc but this doesnt work. Not sure what's preventing the pages to load. Is this some kind of timeout issue?

![image](https://github.com/langgenius/dify/assets/171589201/de0fd03a-25e6-4eb9-973f-04a379cbfc10)

### ✔️ Expected Behavior

Firecrawl should be able to load and scrape these pages and covert them into knowledge.

### ❌ Actual Behavior

The page kinda freezes and does not show the URLs it scraped.

![image](https://github.com/langgenius/dify/assets/171589201/15f756bc-53b8-4da3-b006-da2970fa94af)

**Comment by crazywoola** [comment]
Please provider the container logs of api and worker. Without this information, we could not do any further investigations.

**Comment by murtaza-motorwala** [comment]
@crazywoola - Please find the attached logs. I dont see any errors though.
[api.log](https://github.com/user-attachments/files/15971463/api.log)
[worker.log](https://github.com/user-attachments/files/15971464/worker.log)

**Comment by crazywoola** [comment]
It seems it's still trying to get things back from firecrawl. I tested this [Link](https://www.smiledigitalhealth.com/) on Cloud without encountering errors.

**Comment by murtaza-motorwala** [comment]
If I scrape only 5 pages, the results are shown properly - 

![image](https://github.com/langgenius/dify/assets/171589201/94e31d50-3a99-4bb3-a02d-2a63d02f0ae1)

**Comment by crazywoola** [comment]
We do not have that parameter to set that. Since it seems to be a minute gap before hitting another rate limit.

You check checkout their pricing page. https://www.firecrawl.dev/pricing
