### ISSUE TITLE
Forbidden CSRF cookie not set. 

### ISSUE THREAD

**Issue by luisbrandao** [langgenius/dify#5587]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

"clean run of docker compose trows this error, nothing on the docs on how to disable this check.
i tried:

      - WEB_API_CORS_ALLOW_ORIGINS='*'
      - CONSOLE_CORS_ALLOW_ORIGINS='*'
      - COOKIE_HTTPONLY='true'
      - COOKIE_SAMESITE='Lax'
      - COOKIE_SECURE='false'
      
      
![image](https://github.com/langgenius/dify/assets/25795753/5ec3c27e-eed8-4feb-bca9-6c405d1c7b73)

### ✔️ Expected Behavior

Docker composer up with the example docker compose should work out of the box.

**Comment by laipz8200** [comment]
Hi @luisbrandao! We recently made some updates to our `docker-compose.yaml` file, which might have caused a few issues. Could you please check out `0.6.11` and give it another try? We'd love to hear your feedback!
