### ISSUE TITLE
about "refactor: extract cors configs into dify config and cleanup the confi… …g class (#5507)"

### ISSUE THREAD

**Issue by hymvp** [langgenius/dify#5589]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

After my testing, deleting config.py may cause custom file storage errors (/api/extensions/storage)
docker compose logs -f  api
api-1 | return self._emit(event_name, kwargs)
api-1 | File "/app/api/.venv/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
api-1 | response = handler(**kwargs)
api-1 | File "/app/api/.venv/lib/python3.10/site-packages/botocore/handlers.py", line 278, in validate_bucket_name
api-1 | if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
api-1 | TypeError: expected string or bytes-like object

### ✔️ Expected Behavior

Upload files to s3 bucket

### ❌ Actual Behavior

After my testing, deleting config.py may cause custom file storage errors (/api/extensions/storage)
api-1 | return self._emit(event_name, kwargs)
api-1 | File "/app/api/.venv/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
api-1 | response = handler(**kwargs)
api-1 | File "/app/api/.venv/lib/python3.10/site-packages/botocore/handlers.py", line 278, in validate_bucket_name
api-1 | if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
api-1 | TypeError: expected string or bytes-like object

**Comment by crazywoola** [comment]
Link #5507

**Comment by bowenliang123** [comment]
Hi @hymvp , could you have a try with #5590 manually in your code to see whether the problem still occurs?

**Comment by bowenliang123** [comment]
also cc @takatost

**Comment by hymvp** [comment]
hi @bowenliang123, i refer to https://github.com/langgenius/dify/pull/5590 modify app.py ,the problem still occurs

**Comment by bowenliang123** [comment]
Is that possible to
1. debug to see the `bucket` value where the exception thrown at "botocore/hooks.py" L278
2. attach full messages and traceback of the exception
?
