### ISSUE TITLE
如何增加成员?

### ISSUE THREAD

**Issue by babyfacehl** [langgenius/dify#56]
在设置-成员中点击邀请，输入邮箱，对方无法收到邮件。

**Comment by takatost** [comment]
时间关系，暂时还未对接邮件服务，对方成员可直接使用邀请邮箱对应的 GitHub 或 Google 授权进入您的团队

**Comment by nandao66** [comment]
直接使用邀请邮箱对应的 GitHub 或 Google 授权进入您的团队
这个要如何操作？

**Comment by takatost** [comment]
邀请的成员填的邮箱，需要是他的 GitHub 或者 Google 账号对应的邮箱地址，他才能够用他的邮箱对应第三方账号进行授权登录

**Comment by yuhao1118** [comment]
> 直接使用邀请邮箱对应的 GitHub 或 Google 授权进入您的团队 这个要如何操作？

本地部署的话，要把api/worker/web三个服务的 EDITION 环境变量改成 CLOUD，才能看到oauth登录的 选项

**Comment by takatost** [comment]
是的，我以为你说的是我们的云服务

**Comment by takatost** [comment]
在 config.py 中有这几个配置是给 CLOUD 用的，可从环境变量获取，是 GITHUB 和 GOOGLE 授权登录的凭据，需要自行申请：
```
        self.GITHUB_CLIENT_ID = get_env('GITHUB_CLIENT_ID')
        self.GITHUB_CLIENT_SECRET = get_env('GITHUB_CLIENT_SECRET')
        self.GOOGLE_CLIENT_ID = get_env('GOOGLE_CLIENT_ID')
        self.GOOGLE_CLIENT_SECRET = get_env('GOOGLE_CLIENT_SECRET')
        self.OAUTH_REDIRECT_PATH = get_env('OAUTH_REDIRECT_PATH')
```

**Comment by Caixiaopig** [comment]
请问上文涉及到的几个配置香，是在docker-compose.yaml的哪几个地方做修改呢？

**Comment by takatost** [comment]
> 请问上文涉及到的几个配置香，是在docker-compose.yaml的哪几个地方做修改呢？

是新增这些环境变量，我们模式是 SELF_HOSTED 的配置

**Comment by Caixiaopig** [comment]
是的，我在docker-compose.yaml的web/api/worker都新增了两个参数：GITHUB_CLIENT_ID和GITHUB_CLIENT_SECRET。但跳转到github授权的时候，网址上的APPID=None

**Comment by takatost** [comment]
EDITION=CLOUD 吗

**Comment by Caixiaopig** [comment]
不是CLOUD，EDITION=SELF_HOSTED。因为我不想在登陆的时候启用github oauth，而只是在“集成”的地方用到。

**Comment by takatost** [comment]
暂时不支持这样的用法哈，OAUTH 是 CLOUD 的功能，建议等我们后续为 SELF_HOSTED 加上多账户支持

**Comment by Caixiaopig** [comment]
我把EDITION改为CLOUD后，依然出现跳转到github出现404的情况：https://github.com/login/oauth/authorize?client_id=None
，看上述链接的前半部份，client_id没有值。

**Comment by takatost** [comment]
> 我把EDITION改为CLOUD后，依然出现跳转到github出现404的情况：https://github.com/login/oauth/authorize?client_id=None ，看上述链接的前半部份，client_id没有值。

应该是不会的，EDITION=CLOUD 配置在 api 服务的环境变量中，GITHUB 相关配置也是，配置完毕 docker-compose up -d 重新部署一下，最好也重启一下 nginx: `docker restart docker-nginx-1`

**Comment by Caixiaopig** [comment]
> > 我把EDITION改为CLOUD后，依然出现跳转到github出现404的情况：https://github.com/login/oauth/authorize?client_id=None ，看上述链接的前半部份，client_id没有值。
> 
> 应该是不会的，EDITION=CLOUD 配置在 api 服务的环境变量中，GITHUB 相关配置也是，配置完毕 docker-compose up -d 重新部署一下，最好也重启一下 nginx: `docker restart docker-nginx-1`

找到问题的原因了，官方给出的 docker-compose.yaml 中把 `EDITION` 变量写在了 `web`模块下，经过你的提示改到 `api`模块下，并添加了 `GITHUB_CLIENT_ID` 和 `GITHUB_CLIENT_SECRET` 变量及其值以后，能够通过GitHub第三方登录了。

**Comment by takatost** [comment]
嗯，因为 EDITION 默认是 SELF_HOSTED，CLOUD 也不是我们推荐的模式，特意不写出来的

**Comment by sunsssyc** [comment]
github的回调地址怎么配呢，github授权后还是登陆不进去dify

**Comment by mcgrimm** [comment]
本地部署，用户收不到邮件。所发出来的邀请激活地址好像也没有用。最后让用户用其邮箱地址，随便输入密码即可登录成。不需要做别的事情。不知道这是个bug还是个方便本地安装的方法。

**Comment by kbels** [comment]
请问社区版邀请用户出现Cannot operate self是因为什么呢，docker本地部署的，前边数据库换成了milvus
