### ISSUE TITLE
output var validate keyAlreadyExists. This behavior prevent input. when outputs have same prefix.

### ISSUE THREAD

**Issue by aixgeek** [langgenius/dify#5615]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

output var validate keyAlreadyExists. This behavior prevent input. when outputs have same prefix.
e.g.
result
result_b

I can't input result_b, because result is exists. Normally, the validation should be after blur confirm, not in input changing.

### ✔️ Expected Behavior

validate in blur, not in change.

### ❌ Actual Behavior

validate in change. I can't change, delete, input...
![image](https://github.com/langgenius/dify/assets/9697715/3ce9b6f5-ab38-4e59-bc79-64d80ccd9830)

**Comment by crazywoola** [comment]
You just input 2 arg1 in the image.

**Comment by aixgeek** [comment]
I mean output var, not input var.
