### ISSUE TITLE
TTS on iOS Safari not work

### ISSUE THREAD

**Issue by wizd** [langgenius/dify#5617]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

enable speech, test on iPHone, try to play the output voice.

### ✔️ Expected Behavior

the tts/voice works good on pc/macos/android phone, but none borwser on iPhone.

### ❌ Actual Behavior

the voice loading icon spin forever.

**Comment by crazywoola** [comment]
Please help me clarify several questions:
- Is this self-deployed application using HTTPS not HTTP?
- Did you enable system settings regarding voice and microphone on your phone?

**Comment by wizd** [comment]
> Please help me clarify several questions:
> 
> * Is this self-deployed application using HTTPS not HTTP?
> * Did you enable system settings regarding voice and microphone on your phone?

self hosted, via Cloudflare https, all browser tested ok except iPhone

**Comment by myrulezzz** [comment]
if is http the microphone will not work? I am also facing issues with microphone on any browser on my mac. I have deployed latest version using docker

**Comment by xinzhics** [comment]
I've encountered a similar issue with my self-hosted Dify application using HTTPS. When trying to use the text-to-speech (TTS) feature on iOS Safari, the voice loading icon keeps spinning indefinitely without any audio output.

Here are the details I've confirmed:
1. My deployment environment is using HTTPS, served through Cloudflare.
2. I have enabled the necessary system settings for voice and microphone permissions.

I hope the official team can take note of this issue and provide a fix. If more information or logs are needed to diagnose the problem, please let me know.

Thank you!

**Comment by YongjinHuang** [comment]
I've also encountered this issue. I have two phones, one for iOS and one for Android. The Android device can work as expected, while the iOS device can't.

**Comment by likenamehaojie** [comment]
i have the same issus, before not autoplay version ,  after add load() method  the ios can play audio ,since autoplay fetches added , the audio cant play
