### ISSUE TITLE
Call Get /v1/datasets error: missing 1 required positional argument: 'tenant_id'

### ISSUE THREAD

**Issue by Schumpeterx** [langgenius/dify#5629]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Create a new flask project, copy api/controllers/service_api/dataset/dataset.py and other related .py files to the new flask project. Make sure the flask project can running. 

Then call GET /v1/datasets or POST  /v1/datasets use postman. And will encounter a error said : missing 1 required positional argument: 'tenant_id'

I guess the reason is because the route less a positional argument in file api/controllers/service_api/dataset/dataset.py 

```
class DatasetListApi(DatasetApiResource):
    """Resource for datasets."""

    def get(self, tenant_id): # here require a positional argument
```
while the route is 
```
api.add_resource(DatasetListApi, '/datasets') # dose not define a  positional argument
```

**Comment by laipz8200** [comment]
Hi! We couldn't reproduce this issue. Please report only problems related to the original codebase rather than copying the code elsewhere.

If you need further help, please feel free to reopen this issue.
