### ISSUE TITLE
最新的对话方式，嵌入页面功能错误

### ISSUE THREAD

**Issue by ntfs32** [langgenius/dify#563]
Dify version: Cloud | Self Host

## Steps To Reproduce

1.
<img width="674" alt="image" src="https://github.com/langgenius/dify/assets/16149313/005ecf31-24d5-44f6-adc4-dd16780ec97f">

2. 

## The current behavior
使用上面的js嵌入页面
js文件中的指定的地址是你们云服务的地址是错误的
可以增加 
window.difyChatbotConfig = { token: 'Bh1eLLPxSuHpWBVg', app_url: 'http://app.xxxx/chatbot/'}

**Comment by ntfs32** [comment]
#564

**Comment by iamjoel** [comment]
Use  difyChatbotConfig.baseUrl to conifg custom domain. See : https://github.com/langgenius/dify/commit/2f9de2229fa26c2b0348415bb9119beba9a18552

**Comment by 0utman1** [comment]
> Use difyChatbotConfig.baseUrl to conifg custom domain. See : [2f9de22](https://github.com/langgenius/dify/commit/2f9de2229fa26c2b0348415bb9119beba9a18552)

我们应该在复制Embed代码的时候增加默认的配置
We should add default configurations when copying Embed code，just like ` window.difyChatbotConfig = { token: 'PI0Jxxxx',baseUrl:'https://www.example.com' }
`
