### ISSUE TITLE
need multiple branch supported

### ISSUE THREAD

**Issue by akan** [langgenius/dify#5632]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/langgenius/dify/assets/170169/87208ee4-51da-4ca7-bc66-7174557b420f)
Sometimes I don't need the second classify node instead of a simple node with multiple branch nodes following, then I simplely merge the result, that's what I want. Maybe Iterator node is similar to the solution, but it is not the same.

### 2. Additional context or comments

the workflow graph need to  handle the situation like that: multiple steps with no order index, then merge the results
希望工作流可以处理这种一个节点后，有多个相似的步骤都需要处理，结果还要汇总的。这个地方总分总应该是最清晰的。循环或者串行都不太符合期望的结构。虽然估计也能做。

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We are working on parallel feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/4275
