### ISSUE TITLE
Troubleshooting Docker Configuration Issues After Modifying Files

### ISSUE THREAD

**Issue by litetoooooom** [langgenius/dify#5636]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I modified a file in the web directory, but the changes did not take effect when I ran `docker-compose up`. What should I do? It seems I need to modify something in the configuration file.

**Comment by crazywoola** [comment]
Actually the bot is right, you need to rebuild the image after your did some modifications in web/ .

The ` docker compose up ` does not rebuild the image, typically you can use `docker compose up -t` to rebuild the image, but not in our repo. 
For more information, please read our github actions to manage rebuild this image. FYI, if you want to change the Logo, you should contact our business@dify.ai as well :)
