### ISSUE TITLE
Knowledge：Retrieval Testing->5 validation errors for ParsingModel[InlineResponse20015]

### ISSUE THREAD

**Issue by luckylhb90** [langgenius/dify#5640]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1.Knowledge：Retrieval Testing：
<img width="1482" alt="image" src="https://github.com/langgenius/dify/assets/6822397/9990b285-865f-4046-bfb2-0acb92fb1f62">

2.My configuration：
<img width="841" alt="image" src="https://github.com/langgenius/dify/assets/6822397/5fa41f7e-c08b-407d-be71-43e49963119a">

3.Exception：
5 validation errors for ParsingModel[InlineResponse20015] (for parse_as_type) obj.result.0.order_value Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden obj.result.1.order_value Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden obj.result.2.order_value Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden obj.result.3.order_value Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden obj.result.4.order_value Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden

**Comment by luckylhb90** [comment]
It's not solved yet. Why is it Closed?

**Comment by luckylhb90** [comment]
<img width="1494" alt="image" src="https://github.com/langgenius/dify/assets/6822397/ac83121a-ffba-4774-817f-1434d75b6fc3">
I deployed the latest code, still this error...
I also configured the rerank model, but it still doesn't work. Vector retrieval.

**Comment by laipz8200** [comment]
Seems it's not the same error, let's check it.

**Comment by luckylhb90** [comment]
**1. I tried to do some debugging, and I found that there was an order_value field in the vector data I got, and I saw that the exception was also caused by this field.**
<img width="837" alt="image" src="https://github.com/langgenius/dify/assets/6822397/e9217217-b253-4b28-a9e5-a1c09fe24c4b">

**2.I suspect that the above exception is caused by importing this package. Because it ends up calling InlineResponse20015, which causes an error because it configs extra="forbid", but I'm not familiar with this code and don't know how to change it. Hope to get some advice.**
<img width="848" alt="image" src="https://github.com/langgenius/dify/assets/6822397/c41c715b-9a36-46d4-bea0-898b06b65df6">

<img width="764" alt="image" src="https://github.com/langgenius/dify/assets/6822397/75305d0d-c022-4f55-8fbd-5f4a140701bc">

**Comment by JohnJyong** [comment]
pls provider the qdrant version ,thanks @luckylhb90

**Comment by luckylhb90** [comment]
> pls provider the qdrant version ,thanks @luckylhb90

Qdrant v1.9.5

thanks.

**Comment by luckylhb90** [comment]
I used a lower version of Qdrant and it is now working fine.

**Comment by JohnJyong** [comment]
May be there is any breaking change in qdrant version 1.9, we provide below version， pls try again
![image](https://github.com/langgenius/dify/assets/76649700/8b072f85-641b-4e62-9530-2a38220d9a6b)
@luckylhb90

**Comment by luckylhb90** [comment]
> May be there is any breaking change in qdrant version 1.9, we provide below version， pls try again

Ok, thank you for your help.
