### ISSUE TITLE
Batch run BUG

### ISSUE THREAD

**Issue by gyk185yyds** [langgenius/dify#5660]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When the text generation application runs CSV files in batches, a message is displayed indicating that the content and structure of the uploaded file do not match when the file contains Chinese characters

**Comment by JohnJyong** [comment]
Your problem cannot be reproduced. If you deploy it by self-host , pls provide the corresponding error logs.
test attach below ：
![image](https://github.com/langgenius/dify/assets/76649700/aeff2e77-c8d4-44e0-81b0-72097f2896f5)
@gyk185yyds

**Comment by yaohongfenglove** [comment]
When using WPS software, the problem reoccurs. Many Chinese users use WPS's Excel software instead of Microsoft's Excel software. When the front-end reads CSV files, it is better to perform encoding judgment and automatic conversion
