### ISSUE TITLE
Sandbox is not open source, but can it be opened to allow python to introduce third-party packages or node to allow third-party packages to be loaded

### ISSUE THREAD

**Issue by yyong-brs** [langgenius/dify#5664]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need to connect to oracle and other databases through code execution. Unfortunately, python is also good in sandbox and nodejs is not allowed to load libraries other than built-in libraries.

### 2. Additional context or comments

This is not enough for open. It is important to consider security, but can it be controlled by the administrator switch?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/pull/5513, we will add some tool to connect database rather than use sandbox.

**Comment by yyong-brs** [comment]
> See this #5513, we will add some tools to connect database rather than using sandbox.

not support oracle, use  http request util solve my problem
