### ISSUE TITLE
"Invalid value selector" occurred when pass textarea input params to code execute node

### ISSUE THREAD

**Issue by all4you** [langgenius/dify#5666]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I create a workflow,and make several input params, some of them are textarea:
![image](https://github.com/langgenius/dify/assets/6661305/029e43f9-d1fb-45dd-a2e7-8c52ca9cf252)
![image](https://github.com/langgenius/dify/assets/6661305/de2ca77c-b400-4a92-843d-916656536315)

I find when the textarea params contains line break, the code execute node get error:
![image](https://github.com/langgenius/dify/assets/6661305/8a6b493d-8ca8-473a-9494-cfc7866ba13e)

![image](https://github.com/langgenius/dify/assets/6661305/84f33774-4118-494a-8d22-2a4c1013dc50)

![image](https://github.com/langgenius/dify/assets/6661305/db6dc517-21af-44c4-910f-73c791856103)

after i remove systemMessage param,everything goes ok
![image](https://github.com/langgenius/dify/assets/6661305/7366f169-cc02-404b-8889-6314db099b49)

### ✔️ Expected Behavior

code execute node run successfully

### ❌ Actual Behavior

code execute node occurred error:Invalid value selector

**Comment by all4you** [comment]
I found a very wired thing, when I naming the textarea input params start with 'sysXX' like : systemMessage,sysMessage, it cause the bug, when I change the name to prompt , it is ok.
![image](https://github.com/langgenius/dify/assets/6661305/913e1d67-9591-4148-8630-f52a541e15b0)
when I change it to systemPrompt:
![image](https://github.com/langgenius/dify/assets/6661305/196feeab-595a-46ee-ac6d-c97feef7ca27)
the 'start' node is missing:
![image](https://github.com/langgenius/dify/assets/6661305/65a94bc1-a0ef-41a2-bf8e-78993ec8b3f1)

**Comment by Sakura4036** [comment]
1. `message` in Code execution node and end node work fine
![image](https://github.com/langgenius/dify/assets/42060616/5f4a97dc-de3a-4132-b19f-259e1396b376)

2. `sys_messgae`  in Code execution node work fail
![image](https://github.com/langgenius/dify/assets/42060616/925b185f-161a-48af-87d9-360cde014fce)

3. `sysmessge` in Code execution node work fail
![image](https://github.com/langgenius/dify/assets/42060616/40a83bef-5e55-47b7-a057-c2914839da26)

4. `systemMessage` in Code execution node work fail
![image](https://github.com/langgenius/dify/assets/42060616/9fa0d52c-f1c8-4457-b0ba-482ca74dada6)

5. `message` in code execution work fine, `systemMessage` in end node, work fail
![image](https://github.com/langgenius/dify/assets/42060616/20200b21-f09a-4095-b826-fd1217e46e03)
