### ISSUE TITLE
Node LLM run failed: Model moonshot-v1-32k credentials is not initialized.

### ISSUE THREAD

**Issue by all4you** [langgenius/dify#5668]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I create the moonshot model successfully:
![image](https://github.com/langgenius/dify/assets/6661305/2e5aee34-ce9c-4814-b7d1-71d1f028d76d)
![image](https://github.com/langgenius/dify/assets/6661305/557b915c-9946-4723-a3f8-7e9e9411ef2c)

but when I use moonshot model
![image](https://github.com/langgenius/dify/assets/6661305/2e30a7f0-59bb-4e5f-827c-723f4457d173)

error occurred
![image](https://github.com/langgenius/dify/assets/6661305/4632443f-f6a2-4d3a-af09-62c34e103e75)

**Comment by all4you** [comment]
@dosu please talk concisely and give something useful

**Comment by all4you** [comment]
> Please set default reasoning model in settings page, then it should work as expected. And I saw you have two 32k model,I think you can turn on the first one.

Unfortunately it doesn't help.
![image](https://github.com/langgenius/dify/assets/6661305/f8746e09-1272-4c3c-9d26-0a4e541fe7c2)
![image](https://github.com/langgenius/dify/assets/6661305/2ee8cb80-7f06-45fd-bb98-499060ec7fcc)
![image](https://github.com/langgenius/dify/assets/6661305/175342a9-eb4d-4e73-bd33-647128dec58c)

**Comment by all4you** [comment]
> Please set default reasoning model in settings page, then it should work as expected. And I saw you have two 32k model,I think you can turn on the first one.

"I think you can turn on the first one." this is another bug which I haven't report, I can't remove or turn off the top3 models in moonshot model provider cause it's readonly

**Comment by bluereena** [comment]
你的配置环节有问题，应该点击设置去配置API Key，不是点添加模型
![image-5](https://github.com/langgenius/dify/assets/140619748/aff7839a-5e4d-4801-92a1-465403566839)

**Comment by bluereena** [comment]
> 你的配置环节有问题，应该点击设置去配置API Key，不是点添加模型 ![image-5](https://private-user-images.githubusercontent.com/140619748/344964289-aff7839a-5e4d-4801-92a1-465403566839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTI4MzQsIm5iZiI6MTcxOTkxMjUzNCwicGF0aCI6Ii8xNDA2MTk3NDgvMzQ0OTY0Mjg5LWFmZjc4MzlhLTVlNGQtNDgwMS05MmExLTQ2NTQwMzU2NjgzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwOTI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2YyZjA0NWNhYjdkMDFlYjFhZjA5N2NiMTY4N2I0ZmY3OTQ2OGJkYWU3ZDQ3YWIyOGFhOGNjODdiOGIxN2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HMnHTK66x_hx5yTijx2rSoNsdtYBwlWEJNTPCCj15wg)

正确配置好以后是这样的

**Comment by bluereena** [comment]
> 你的配置环节有问题，应该点击设置去配置API Key，不是点添加模型 ![image-5](https://private-user-images.githubusercontent.com/140619748/344964289-aff7839a-5e4d-4801-92a1-465403566839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTI4MzQsIm5iZiI6MTcxOTkxMjUzNCwicGF0aCI6Ii8xNDA2MTk3NDgvMzQ0OTY0Mjg5LWFmZjc4MzlhLTVlNGQtNDgwMS05MmExLTQ2NTQwMzU2NjgzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwOTI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2YyZjA0NWNhYjdkMDFlYjFhZjA5N2NiMTY4N2I0ZmY3OTQ2OGJkYWU3ZDQ3YWIyOGFhOGNjODdiOGIxN2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HMnHTK66x_hx5yTijx2rSoNsdtYBwlWEJNTPCCj15wg)
正确配置之后应该是这样的
![temp](https://github.com/langgenius/dify/assets/140619748/cc3a7359-d950-424d-a42c-9e3d17a0622a)

**Comment by bluereena** [comment]
> 你的配置环节有问题，应该点击设置去配置API Key，不是点添加模型 ![image-5](https://private-user-images.githubusercontent.com/140619748/344964289-aff7839a-5e4d-4801-92a1-465403566839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTI4MzQsIm5iZiI6MTcxOTkxMjUzNCwicGF0aCI6Ii8xNDA2MTk3NDgvMzQ0OTY0Mjg5LWFmZjc4MzlhLTVlNGQtNDgwMS05MmExLTQ2NTQwMzU2NjgzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwOTI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2YyZjA0NWNhYjdkMDFlYjFhZjA5N2NiMTY4N2I0ZmY3OTQ2OGJkYWU3ZDQ3YWIyOGFhOGNjODdiOGIxN2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HMnHTK66x_hx5yTijx2rSoNsdtYBwlWEJNTPCCj15wg)

正确配置好之后应该是这样的
![Uploading temp.png…]()

**Comment by bluereena** [comment]
> 你的配置环节有问题，应该点击设置去配置API Key，不是点添加模型 ![image-5](https://private-user-images.githubusercontent.com/140619748/344964289-aff7839a-5e4d-4801-92a1-465403566839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxODUsIm5iZiI6MTcxOTkxMjg4NSwicGF0aCI6Ii8xNDA2MTk3NDgvMzQ0OTY0Mjg5LWFmZjc4MzlhLTVlNGQtNDgwMS05MmExLTQ2NTQwMzU2NjgzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwOTM0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzY4NjIxOWY1OTdmYzUxODY4NWY1N2UxNWE4ZGEwMmI3NDhjMDRhN2U0ZTM0MDUwZDJhYmViODI4Yzg2MDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lCyLyg-5389kaFF_fNj1tF6RgI1SkNqezoAAyMDEJDg)

正确配置好之后应该是这样的
![temp](https://github.com/langgenius/dify/assets/140619748/099ac2ce-2397-4030-bd40-462234ded5e8)

**Comment by all4you** [comment]
> > 你的配置环节有问题，应该点击设置去配置API Key，不是点添加模型 ![image-5](https://private-user-images.githubusercontent.com/140619748/344964289-aff7839a-5e4d-4801-92a1-465403566839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMxODUsIm5iZiI6MTcxOTkxMjg4NSwicGF0aCI6Ii8xNDA2MTk3NDgvMzQ0OTY0Mjg5LWFmZjc4MzlhLTVlNGQtNDgwMS05MmExLTQ2NTQwMzU2NjgzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwOTM0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzY4NjIxOWY1OTdmYzUxODY4NWY1N2UxNWE4ZGEwMmI3NDhjMDRhN2U0ZTM0MDUwZDJhYmViODI4Yzg2MDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lCyLyg-5389kaFF_fNj1tF6RgI1SkNqezoAAyMDEJDg)
> 
> 正确配置好之后应该是这样的 ![temp](https://private-user-images.githubusercontent.com/140619748/344966790-099ac2ce-2397-4030-bd40-462234ded5e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjYzNzEsIm5iZiI6MTcxOTkyNjA3MSwicGF0aCI6Ii8xNDA2MTk3NDgvMzQ0OTY2NzkwLTA5OWFjMmNlLTIzOTctNDAzMC1iZDQwLTQ2MjIzNGRlZDVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMzE0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjliMzhiYWNmZTdlNDAyYzMzZTMxZjU4ZGFmYzRhNjM3MDE4YjcyYTNjNjgxNDNkNGRjYWE5NjFmNDY2MDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fxFeWDa0V-TS2Tx2QU0ifR8-v6HLHyPERKyPtm18R5A)

I have already tried this:
![image](https://github.com/langgenius/dify/assets/6661305/bac5e179-f75e-4b9f-bc8d-5e044bd5ef8b)
but remains the same error:
![image](https://github.com/langgenius/dify/assets/6661305/02d2d497-052b-4755-99a7-9c3f5f3c0021)

**Comment by all4you** [comment]
Maybe we should explain the difference between "add model" and "setting and activate the default model".

**Comment by Sakura4036** [comment]
Why you need to add Moonshot models manually？Want to use multiple API keys? I'm not sure if dify can currently use multiple API keys for the same model provider

**Comment by all4you** [comment]
> Why you need to add Moonshot models manually？Want to use multiple API keys? I'm not sure that dify can currently use multiple API keys for the same model provider

I don't want to add moonshot model manually either, but it provide the choice so I added the model, if moonshot model provider doesn't support those models added manually, it should hide the add button so that user don't get confused.
