### ISSUE TITLE
my server is on proxy, but dify can't access the big model api, reporting an error:“Connection to dashscope.aliyuncs.com timed out.”

### ISSUE THREAD

**Issue by JunDaTang** [langgenius/dify#5669]
### Self Checks

- [ ] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [ ] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [ ] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [ ] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

api_1         | ERROR:dashscope:HTTPSConnectionPool(host='dashscope.aliyuncs.com', port=443): Max retries exceeded with url: /api/v1/services/aigc/text-generation/generation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f61280f0340>, 'Connection to dashscope.aliyuncs.com timed out. (connect timeout=300)'))

![image](https://github.com/langgenius/dify/assets/15319232/2ad1025f-99c9-404a-a125-e107baae99f3)

**Comment by crazywoola** [comment]
I don't think there is a need for using proxy for `dashscope.aliyuncs.com`.

**Comment by zhangzw16** [comment]
I encountered the same problem and solved it using the following method. You can try it too.

Create the `~/.docker/config.json` file as follows:
```
{
    "proxies":
    {
      "default":
      {
        "httpProxy": "http://172.17.0.1:9998",
        "httpsProxy": "http://172.17.0.1:9998",
        "noProxy": "localhost,127.0.0.1,.example.com,weaviate"
      }
    }
}
```
The `weaviate` part may or may not be needed, but directly using `http://weaviate:8080` in `docker-compose.yaml` line 114 might cause connection errors to the vector DB if not included. Also, `9998` is the **VPN port number** and might need to be modified accordingly. `http://172.17.0.1` is the default host's internal Docker network address.

After editing the file, then restart docker by
``` bash
docker compose down
dcoker compose up -d
```

**Comment by crazywoola** [comment]
See this also https://github.com/langgenius/dify/issues/5686#issuecomment-2198395207
