### ISSUE TITLE
Better user roles

### ISSUE THREAD

**Issue by lschaupp** [langgenius/dify#5670]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently there are only 2 options for user management

1) Admin 
2) Only me

We need better user management. E.g. Someone should be able to create chatbots but not be an admin.

I would propose to introduce another "Creator" Role that has rights to create bots but is not an admin.
Created chatbots should also be visible to specified users. (however this would be another ticket)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by dq7532183** [comment]
Can only view and edit assistants created by oneself
