### ISSUE TITLE
Iteration component get stucked, and can't iterate

### ISSUE THREAD

**Issue by forrestsocool** [langgenius/dify#5673]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

put a llm node in a iteratation node,  the input list is about 20 lenth, after sevaral iterates, it get stucked, and do nothing...

here is the task which stuck over 30 min:
![image](https://github.com/langgenius/dify/assets/3960433/092c8a72-6e16-4864-9a13-d2521c0c70cf)

6 iterations have been done successfully:
![image](https://github.com/langgenius/dify/assets/3960433/1f17de56-b371-421d-83dd-89588137cd0f)

no any other iterate is processing... and nothing shows in the last node:
![image](https://github.com/langgenius/dify/assets/3960433/2a05d058-21a7-4668-b359-a8054597a5dd)

### ✔️ Expected Behavior

iteratation should finish its input

### ❌ Actual Behavior

stucked, no reason, no output.

**Comment by forrestsocool** [comment]
three hour passed, and it is still get stucked, would you please add a "timeout" or something like to make components more robust?
![image](https://github.com/langgenius/dify/assets/3960433/93d0e100-ee52-4d1f-aafa-29691bad35f6)

**Comment by crazywoola** [comment]
Can you provide the logs of the containers?

**Comment by Edison-A-N** [comment]
> Can you provide the logs of the containers?
I encountered the same issue, and the worker logs are as follows:
`api_1                    | workflow_run_id
api_1                    |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
api_1                    |     For further information visit https://errors.pydantic.dev/2.7/v/string_type
api_1                    | [2024-06-30 08:49:01 +0000] [78] [ERROR] Error handling request /console/api/apps/0320f105-33d6-4ee5-9f20-6a25a96711b2/workflows/draft/iteration/nodes/1719727405937/run
api_1                    | Traceback (most recent call last):
api_1                    |   File "/app/api/.venv/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 55, in handle
api_1                    |     self.handle_request(listener_name, req, client, addr)
api_1                    |   File "/app/api/.venv/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 128, in handle_request
api_1                    |     super().handle_request(listener_name, req, sock, addr)
api_1                    |   File "/app/api/.venv/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 115, in handle_request
api_1                    |     for item in respiter:
api_1                    |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
api_1                    |     return self._next()
api_1                    |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
api_1                    |     for item in iterable:
api_1                    |   File "/app/api/.venv/lib/python3.10/site-packages/flask/helpers.py", line 113, in generator
api_1                    |     yield from gen
api_1                    |   File "/app/api/libs/helper.py", line 162, in generate
api_1                    |     yield from response
api_1                    |   File "/app/api/core/app/apps/base_app_generate_response_converter.py", line 28, in _generate
api_1                    |     for chunk in cls.convert_stream_full_response(response):
api_1                    |   File "/app/api/core/app/apps/workflow/generate_response_converter.py", line 45, in convert_stream_full_response
api_1                    |     for chunk in stream_response:
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 159, in _to_stream_response
api_1                    |     yield WorkflowAppStreamResponse(
api_1                    |   File "/app/api/.venv/lib/python3.10/site-packages/pydantic/main.py", line 176, in __init__
api_1                    |     self.__pydantic_validator__.validate_python(data, self_instance=self)
api_1                    | pydantic_core._pydantic_core.ValidationError: 1 validation error for WorkflowAppStreamResponse
api_1                    | workflow_run_id
api_1                    |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
api_1                    |     For further information visit https://errors.pydantic.dev/2.7/v/string_type
`

**Comment by AndyMik90** [comment]
Same issue here. The iteration just gets stuck/timeout when running with actual iterations.

When you debug it with just one item in the iteration, it works for the first item but then gets stuck on the second.

**Comment by AndyMik90** [comment]
@takatost @crazywoola  Here is log from a workflow where the iteration node executed 3/6 times, where it suddenly said "The read operation timed out". It can happen on the first iteration, second, third. depending on the time it takes to excute the node. Looks these things can happend with tools that use a long time to respond like Jina Reader, Firecrawl etc.

![CleanShot 2024-06-30 at 18 57 58](https://github.com/langgenius/dify/assets/119136210/3f592e77-df22-4907-8581-c3ff54bf3399)

Maybe the solution is to just increase the Workflow runtime configuration env?

**Comment by FBR65** [comment]
Here the same problem.

Iteration works with 1 chunk.

Iteration get stuck with iteration > 1. But not always at the same time. Sometimes it iterates until 3 and sometimes it get stuck at 2 iterations.

**Comment by crazywoola** [comment]
> Here the same problem.
> 
> Iteration works with 1 chunk.
> 
> Iteration get stuck with iteration > 1. But not always at the same time. Sometimes it iterates until 3 and sometimes it get stuck at 2 iterations.
> 
> Using docker container 0.7.1

Can you paste a screenshot of the iteration.

**Comment by FBR65** [comment]
Hi,

thanks for the support. 

In the meanwhile I could figure out, that the problem was lying in the tested Text.
It was chunked in a bad manor so that there were parts like ":IPOD (2023/05/23)" which could not be translated.
I've tested the Iteration today and it works fine.

Sorry for reopening this issue.
