### ISSUE TITLE
Add tool Doc2X-OCR

### ISSUE THREAD

**Issue by Menghuan1918** [langgenius/dify#5675]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

A general document OCR tool that can convert images or pdfs into markdown/LaTeX text with formulas and text formatting.

- Use case 1: to build a math problem solving workflow that converts an input image to LaTeX text for LLm processing/ RAG searching/ passing to WolframAlpha.

- Use Case 2: Generic OCR for parsing input images into markdown text for subsequent processing.

- Use Case 3: Parsing input form images for subsequent processing.

### 2. Additional context or comments

https://github.com/Menghuan1918/pdfdeal?tab=readme-ov-file#summary

https://doc2x.com/

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by laipz8200** [comment]
Is this service available internationally?

It seems that registration requires a mainland China phone number, and there is no English support. Can you confirm if this service is available for international users?

**Comment by Menghuan1918** [comment]
> Is this service available internationally?
> 
> It seems that registration requires a mainland China phone number, and there is no English support. Can you confirm if this service is available for international users?

It can only sign up for mainland China cell phones at the moment, but I asked their customers and they said it will be open to the world in the near future.

**Comment by laipz8200** [comment]
I prefer to wait until their support is internationalized before adding this tool.
