### ISSUE TITLE
I could no longer log in

### ISSUE THREAD

**Issue by cello331** [langgenius/dify#5678]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

On the 25th, after making the payment, I could no longer log in, and there was no login button on the top right corner of the homepage.

### ✔️ Expected Behavior

On the 25th, after making the payment, I could no longer log in, and there was no login button on the top right corner of the homepage.

### ❌ Actual Behavior

On the 25th, after making the payment, I could no longer log in, and there was no login button on the top right corner of the homepage.

**Comment by crazywoola** [comment]
Please go to https://cloud.dify.ai/ to login.The login button is not on top right of the corner, it's in the middle. 
Please provide your email used to login, I will check that with our team.

**Comment by cello331** [comment]
@crazywoola Thank you very much, your method solved the problem.
