### ISSUE TITLE
Cannot connect to redis://:**@redis:6379/1: Error -3

### ISSUE THREAD

**Issue by HakunamatataLeo** [langgenius/dify#5680]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

<img width="978" alt="image" src="https://github.com/langgenius/dify/assets/4550421/aa6dea59-a003-4693-8d2f-6f3b25f23b8a">

### 2. Additional context or comments

Cannot connect to redis

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by HakunamatataLeo** [comment]
<img width="372" alt="image" src="https://github.com/langgenius/dify/assets/4550421/091d3f3f-df08-4771-9e99-33ed293fbc45">
is doesn't work ,i'm config this @dosubot

**Comment by HakunamatataLeo** [comment]
An error occurred during credentials validation: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/chat (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff37e92740>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))

**Comment by HakunamatataLeo** [comment]
@dosubot

**Comment by HakunamatataLeo** [comment]
docker server  how to config  the  ’dns‘ @dosubot

**Comment by HakunamatataLeo** [comment]
Run failed: Node LLM run failed: [ollama] Server Unavailable Error, HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/chat (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff3d9cc5e0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))

**Comment by HakunamatataLeo** [comment]
@dosubot

**Comment by HakunamatataLeo** [comment]
how to connect local ollama
@dosubot

**Comment by crazywoola** [comment]
@HakunamatataLeo Please check your env variables in `docker-compose.yaml`. And make sure there is no other redis server running in this machine. `redis://:**@redis:6379/1` this suggests there is no host information provided to redis client.

Please not not modify network bridge, if you want to disable the proxy https://github.com/langgenius/dify/issues/5686#issuecomment-2198395207

> Run failed: Node LLM run failed: [ollama] Server Unavailable Error, HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/chat (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff3d9cc5e0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))

For bug report, please use bug template to report an issue. This is a feature request template. Thanks :)

**Comment by Eugene-Zh** [comment]
@crazywoola Hello, if there is a need to open other redis server on the server or I want to deploy two dify on one machine, how should I set or modify the redis port and other conflicting containers because they are the same? Thank you！

**Comment by lichengyang666** [comment]
I also encountered the problem of connecting to Redis, "Cannot connect to redis://:**@localhost:6379/1: invalid password." I started a flask service locally and then started Celery, but I got the error, and the password configuration has not changed and is difya123456. I am very confused by this issue. Looking forward to your answer.
