### ISSUE TITLE
api and web service stucked after upload large documet

### ISSUE THREAD

**Issue by SeesawLiu** [langgenius/dify#5683]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

use docker-compose.yaml to launch dify,when upload documents with 10000 lines,api and web stucks

### ✔️ Expected Behavior

api should be called,web can visit

### ❌ Actual Behavior

api and web can't visit.
configured the docker compose yaml according to #5540, but it still doesn't work. I configured unstructured, and after uploading the file, 1. First, api cpu 100%, unstructured cpu usage is low, worker_general cpu usage is low, and the front end cannot be used. 2. Then worker_general execution 100%, worker_api cpu usage is low, and the front end can be used. 3. worker_general cpu 50% worker_api cpu 100% @dosu

**Comment by SeesawLiu** [comment]
the question maybe not the size of document,because the document uploaded success and handled after few minitues,not throw exception @dosu

**Comment by SeesawLiu** [comment]
not the size and storage of the document,the point is the dify api service sucked @dosu

**Comment by SeesawLiu** [comment]
as i mention above,when web service not reponse the api service cpu 100%,the worker service cpu low.the worker resource is enough,there is no phenomenon indicating that it is a worker problem@dosu

**Comment by SeesawLiu** [comment]
not work @dosu

**Comment by SeesawLiu** [comment]
i found the api /console/api/datasets/indexing-estimate handle too long @dosu

**Comment by gooplle** [comment]
添加了设置文件大小及超时的语句
  UPLOAD_FILE_SIZE_LIMIT: 50M  # Increase the file size limit as needed
  UPLOAD_FILE_BATCH_LIMIT: 10  # Adjust the batch limit if necessary
  GUNICORN_TIMEOUT: 360  # Increase the timeout to support longer processing times
保存docker-compose.yaml文件，并重启docker或compose后，上传文件，系统仍然提示15M文件大小的限制。

**Comment by gooplle** [comment]
Added statements to set the file size and timeout
UPLOAD_FILE_SIZE_LIMIT: 50M # Increase the file size limit as needed
UPLOAD_FILE_BATCH_LIMIT: 10 # Adjust the batch limit if necessary
GUNICORN_TIMEOUT: 360 # Increase the timeout to support longer processing times
Save the docker-compose.yaml file, and after restarting docker or compose, upload the file, the system still prompts the 15M file size limit.

**Comment by yujunhui** [comment]
Seems the proble fixed in the latest version.
I run the latest version on my PC, upload the 250K character file to the KB, and didn't get stuck.

**Comment by crazywoola** [comment]
@SeesawLiu Have you tried this in latest version.

**Comment by crazywoola** [comment]
Link #5663 and close this one
