### ISSUE TITLE
There is not dotenv under docker directory.

### ISSUE THREAD

**Issue by 4t8dd** [langgenius/dify#5684]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I deploy dify locally with docker compose following the docs. 
When to customize, I found this segment in docs.
```
Customize Dify
The full set of environment variables can be found under docker/dotenvs. To change their values, delete the .example suffix from the corresponding .env.example file name and edit the values in file directly. Then, restart Dify with:

```

But I did not find docker/dotenv, nor .env.example.

**Comment by 4t8dd** [comment]
api/tests/integration_tests/.env.example
 is good.

The docs should be updated.

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/blob/f9e4b4e74c0b902cc3cc1a87b59942d0d094a8e8/api/README.md#L18

**Comment by 4t8dd** [comment]
@crazywoola I followed your [offical doc](https://docs.dify.ai/getting-started/install-self-hosted/docker-compose). You may update it too.
