### ISSUE TITLE
NO_PROXY does not work on docker-api-1

### ISSUE THREAD

**Issue by potofo** [langgenius/dify#5686]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Since the problem does not recur once the NO_PROXY environment variable is set in the Docker container, it is assumed that the problem is during the creation of the Docker image.
It is reproduced by following the steps below:

**1.  Remode Docker image for docker-api-1**

   ```
   docker rmi <IMAGE ID>
   ```
**2. Setting corporate proxy for Docker Daemon**
   ```
   # vi /etc/systemd/system/docker.service.d/http-proxy.conf
   
   -----
   [Service]
   Environment="HTTP_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080"
   Environment="HTTPS_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080"
   Environment="NO_PROXY=localhost, 127.0.0.1, aoai.corporate.co.jp, ollama.corporate.co.jp"
   -----
   
   # ​systemctl daemon-reload
   # systemctl restart docker
   
   confirm proxy for Docker Daemon 
   
   # systemctl show --property=Environment docker
   Environment=HTTP_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080 HTTPS_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080 "NO_PROXY=localhost, 127.0.0.1, aoai.corporate.co.jp, ollama.corporate.co.jp"
   ```

**3. Confirm proxy setting in container**
   ```
   # docker exec -it docker-api-1 bash
   root@b4e1b418b30c:/app/api# env | grep PROXY
   SSRF_PROXY_HTTP_URL=http://ssrf_proxy:3128
   HTTPS_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080
   HTTP_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080
   SSRF_PROXY_HTTPS_URL=http://ssrf_proxy:3128
   root@b4e1b418b30c:/app/api#
   ```
   => No NO_PROXY environment variable found in docker-api-1 container

**4. Confirm error message on curl command**
   ```
   curl "https://aoai.corporate.co.jp/openai/deployments/gpt-35-turbo-16k/chat/completions?api-version=2024-02-15-preview" \
    -H "Content-Type: application/json" \
    -H "api-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
    -d "{
    \"messages\": [{\"role\":\"system\",\"content\":\"You are an AI assistant that helps people find information.\"}],
    \"max_tokens\": 800,
    \"temperature\": 0.7,
    \"frequency_penalty\": 0,
    \"presence_penalty\": 0,
    \"top_p\": 0.95,
    \"stop\": null
    }"
    ```
   => Result message:
      Error code:403:　-{'error':{'code':'403',"messages': 'Access denied due to Virtual Network Network/Firewall rules.'}}
   
   This message is the same as what is displayed on the GUI screen.
   ```
**5. Workaround**
   As a workaround, you can avoid this issue by setting NO_PROXY in the api section of docker-compose.yaml.


**Since the Docker version does not include a Docker file, we suspect that there is a NO_PROXY issue with the distributed Docker image.
I would like this bug fixed.
Thank you.**


### ✔️ Expected Behavior

_No response_

### ❌ Actual Behavior

As a workaround, you can avoid this issue by setting NO_PROXY in the api section of docker-compose.yaml.

**Comment by zhangzw16** [comment]
maybe this would help https://github.com/langgenius/dify/issues/5669#issuecomment-2195052423

**Comment by potofo** [comment]
Thank you for your swift reply and good advice.
The problem was solved by setting NO_PROXY in Docker Client according to #5569

**Comment by crazywoola** [comment]
I checked this with @Yeuoly once, you could also leave these two environments blank. Then it will not use this proxy while sending requests.

```
SSRF_PROXY_HTTP_URL=
SSRF_PROXY_HTTPS_URL=
```

https://github.com/langgenius/dify/blob/843280f82be614f1ed47e2aee3fba986b50c30a9/api/core/extension/api_based_extension_requestor.py#L32-L38
