### ISSUE TITLE
No requirement.txt file under api for local deployment

### ISSUE THREAD

**Issue by zanderjiang** [langgenius/dify#5687]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Tried to host dify from source code, followed the steps in the self host guide, there is no file called "requirements.txt" under the api directory.

### ✔️ Expected Behavior

use pip installer to install required libraries

### ❌ Actual Behavior

no "requirements.txt" file

**Comment by zanderjiang** [comment]
Thank you, I was able to resolve the issue. Now, when I have the self hosted server up, it requires me to enter an email and password, which I don't have, where are the log-in info stored? When I try to initialize a new account, it gets stuck at the page.

**Comment by crazywoola** [comment]
See this

https://github.com/langgenius/dify/blob/f9e4b4e74c0b902cc3cc1a87b59942d0d094a8e8/api/README.md#L6
