### ISSUE TITLE
User Input - Display Buttons / Textfields within chat

### ISSUE THREAD

**Issue by digitaldesaster** [langgenius/dify#5694]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

please consider adding a block that supports buttons and text fields for the user to click / fill in. similar to the start of the flow this should be supported during the chat flow. its just way simpler and faster then make unecessary llm calls. not sure if this could be achieved if we would be able to add buttons / fields into the jinja templates and register ids to react if a button is clicked. if someone could point me to the part of the code i would like to take a look into it. i am good at python but unfortunately not good at react / js. but i would even consider hiring someone on fivver to implement this. my point is, that i think we will have a much better, cleaner and faster user experience for usecases where the user needs to make a choice or needs to put in some data. 

### 2. Additional context or comments

I am aware that someone has asked for user input and i understand that follow up questions are an option. anyway i think that we are overcomplicating things here and buttons just work better / faster. 
https://github.com/langgenius/dify/discussions/5021

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by jeanffee** [comment]
I need same ability, that be able to get user input during the chat flow, without have to start from beginning as a new round of conversation

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/4947
