### ISSUE TITLE
Add function/tool call support in Workflow

### ISSUE THREAD

**Issue by davinwang** [langgenius/dify#5710]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I was trying to use function/tool call in Workflow, however I can only find it in Agent page. I need to access function/tool call in workflow in either way: add Agent to workflow,or add function/tool call in Workflow. Thx

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Sumkor** [comment]
Is there a plan to support function calling in workflow? @crazywoola

**Comment by Nduy2k** [comment]
This is a very much needed feature
