### ISSUE TITLE
Lack of documentation on how to use API-Based variables in Orchestrator agent instruction

### ISSUE THREAD

**Issue by akkaz** [langgenius/dify#5717]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

While the documentation for creating API-based variables is clear [API-based docs](https://docs.dify.ai/guides/extension/api-based-extension), the guidance on how to effectively use these variables within agent conversations is lacking. We are able to create API-based variables successfully, but we counter difficulties when trying to access and consume them as API-base variable in input variable for agent instruction.

In our scenario we want to use the API-based variable in the Orchestrator agent instruction. We are at the point that we can insert the variable as instruction, but we don't know how to use the API we just created to fetch our instructions outside dify.

![Screenshot from 2024-06-28 15-05-53](https://github.com/langgenius/dify/assets/42849856/dad1a951-5c1b-46ce-9f04-f3fcdd752441)

**Comment by crazywoola** [comment]
Please refer these 2 docs as well. 
https://docs.dify.ai/guides/extension/api-based-extension/cloudflare-workers
https://github.com/crazywoola/dify-extensions-worker

<img width="1374" alt="image" src="https://github.com/langgenius/dify/assets/100913391/a3751454-f9de-490d-9222-5e189e6abf5d">

Here is the result of the API Based variables.

It's used in basic agent originally to give the bot ability to interact with other services, and it will be called every time you talk to the bot, vise versa, the agent will choose tools it needs to answer the questions accordingly.

In you case you should let the api return the prompt.

**Comment by crazywoola** [comment]
I think there might be a bug as well https://github.com/langgenius/dify/issues/5734

**Comment by crazywoola** [comment]
<img width="1429" alt="image" src="https://github.com/langgenius/dify/assets/100913391/e402686e-4a72-4a89-9bde-5c8e3965506f">

See this image above, my api endpoint `getQuotes` support getting a variable called `count`, if you would like to add this parameter to that endpoint, just add another textbox to hold this parameter like I do in this image. This depends how you code you api extension.

For example, if you would like to use different prompt by different platform(facebook, x, instagram)

You just need to pass the`platform` to the api endpoint, and it will be injected in the system prompt. FYI, it will send both inputs and query to the endpoint.

```
{
  query: 'user's questions',
  inputs: {  platform: ''facebook'  }
}
```

**Comment by akkaz** [comment]
After more than a month of working without issues, I’ve recently encountered some problems.

It seems that the _API-based Variable_  has stopped functioning as expected in the last few days. Unfortunately, I'm unable to pinpoint exactly when this issue started, though it might have occurred around the update to version 0.7 or shortly after.

I’ve verified that the endpoint is correct and accessible through Insomnia, where everything works as expected. However, according to the Cloudflare logs, it appears that Dify isn't even attempting to reach the endpoint.

**Comment by akkaz** [comment]
@crazywoola sorry for tagging you again, but i think that new version (0.7) bug this feature.

**Comment by aiwinapp** [comment]
@crazywoola sorry for me to, but in new version Dify isn't even attempting to reach the endpoint.
