### ISSUE TITLE
OpenApi 3.1.0 ArrayType is recognized as StringType unexpectly

### ISSUE THREAD

**Issue by forrestsocool** [langgenius/dify#5720]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Import this openapi schema as custom tool, add it into a workflow later, the "article_ids" parameter of ApiInsertArticleInsert is recognized as StringType instead of ArrayType[StringType ] (which Coze workflow can recognize correctly, though it only support 3.0.0 openApi schema, u can convert it ):

the openapi 3.1.0 schema generated by LiteStar

[openapi (4).json](https://github.com/user-attachments/files/16032615/openapi.4.json)

### ✔️ Expected Behavior

type of paramerter article_ids should be list[str]

### ❌ Actual Behavior

type of paramerter article_ids is str

**Comment by laipz8200** [comment]
Our tool currently doesn't support array-type parameters, we might add this feature in the future.

**Comment by qdaoming** [comment]
> Our tool currently doesn't support array-type parameters, we might add this feature in the future.

@laipz8200  This is an important missing feature. Do you know when will it be implemented?

**Comment by laipz8200** [comment]
> > Our tool currently doesn't support array-type parameters, we might add this feature in the future.
> 
> @laipz8200 This is an important missing feature. Do you know when it will be implemented?

Since not all models have the capability to generate complex structured parameters, this feature is not a high priority for our team. However, you are welcome to try implementing it yourself.

**Comment by qdaoming** [comment]
> > > Our tool currently doesn't support array-type parameters, we might add this feature in the future.
> > 
> > 
> > @laipz8200 This is an important missing feature. Do you know when it will be implemented?
> 
> Since not all models have the capability to generate complex structured parameters, this feature is not a high priority for our team. However, you are welcome to try implementing it yourself.

The input of tools can be from several sources, not only from LLM.
As said above, coze workflow works well for it.
If I can find available time, I might check this issue.
