### ISSUE TITLE
add team member window display bug

### ISSUE THREAD

**Issue by Winson-030** [langgenius/dify#5729]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="399" alt="dify-bug_2024-06-29_01-17-29" src="https://github.com/langgenius/dify/assets/100707097/19259372-403e-41ab-988b-82629fc215f7">

Role select display bug

**Comment by Winson-030** [comment]
@dosu can please give some fix advices?

**Comment by crazywoola** [comment]
It has been fix in latest branch.
