### ISSUE TITLE
Fail to upgrade to 0.6.12

### ISSUE THREAD

**Issue by paulcx** [langgenius/dify#5730]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Copy the docker/.env.example file to a new file named .env and customize it as needed.
Run docker compose up to start the services.

### ✔️ Expected Behavior

upgrade

### ❌ Actual Behavior

redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

**Comment by paulcx** [comment]
does it related to env file? i used the default env file middleware.env

**Comment by paulcx** [comment]
what is the difference of use between docker-compose.middleware.yaml and docker-compose.yaml? which one should be use to upgrade?

**Comment by damadorPL** [comment]
also have similar issue - docker @ windows run with 

@echo off
cd dify/docker
call git pull origin main
call docker compose down
call docker compose pull
call docker compose up -d --remove-orphans

then output bunch of warnings 


 * branch              main       -> FETCH_HEAD
Already up to date.
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"TENCENT_COS_BUCKET_NAME\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"MILVUS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"ORACLE_USER\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"CHROMA_DATABASE\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"CELERY_WORKER_CLASS\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"VECTOR_STORE\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"SECRET_KEY\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"UPLOAD_FILE_BATCH_LIMIT\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"NOTION_CLIENT_SECRET\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"INVITE_EXPIRY_HOURS\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"CHROMA_AUTH_CREDENTIALS\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"AZURE_BLOB_ACCOUNT_URL\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"AZURE_BLOB_ACCOUNT_KEY\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"CONSOLE_CORS_ALLOW_ORIGINS\" variable is not set. Defaulting to a blank string."
time="2024-06-28T22:01:53+02:00" level=warning msg="The \"GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64\" variable is not set. Defaulting to a blank string."

(...)

**Comment by damadorPL** [comment]
using default env file warning gone but now 

2024-06-28 22:30:39 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:41 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:44 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:46 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:48 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:50 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:54 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:31:01 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:31:14 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:31:40 ssrf_proxy-1  | sh: 1: /docker-entrypoint.sh: not found

and 

2024-06-28 22:30:46 nginx-1     | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:47 nginx-1     | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:49 nginx-1     | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:53 nginx-1     | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:30:59 nginx-1     | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:31:12 nginx-1     | sh: 1: /docker-entrypoint.sh: not found
2024-06-28 22:31:38 nginx-1     | sh: 1: /docker-entrypoint.sh: not found

2 volumes are created but are 0 byte files

**Comment by listelin** [comment]
I also could not start DIFY 0.6.12 with the following error.
```
 /docker-entrypoint.sh: not found
```

I was able to start it successfully by using docker-legacy.
```
cd docker-legacy
docker compose -p dify up -d
```
Since docker-legacy/volumes is the initial state, DIFY will start on the first signup screen.

**Comment by xd845217xd** [comment]
@damadorPL 

"docker\nginx\docker-entrypoint.sh"
"docker\ssrf_proxy\docker-entrypoint.sh"

Converting these two files from CRLF to LF will resolve the issue.

You can use "Notepad++". Open the file, go to Edit, EOL Conversion, select UNIX (LF), and save the file. 
Don't forget to run "docker compose up -d" again.

I spent quite some time figuring this out; not sure if it counts as a bug?

**Comment by crazywoola** [comment]
> what is the difference of use between docker-compose.middleware.yaml and docker-compose.yaml? which one should be used to upgrade?
> 
> Actually, redis server works fine but somehow worker can connect redis server. it should be something wrong with the config?

`docker-compose.middleware.yaml` is used for self hosted (source code).
In your case, you should use `docker-compose.yaml` to start the container instead.

**Comment by jerryandjune** [comment]
> @damadorPL
> 
> “docker\nginx\docker-entrypoint.sh” “docker\ssrf_proxy\docker-entrypoint.sh”
> 
> 将这两个文件从 CRLF 转换为 LF 将解决该问题。
> 
> 您可以使用“Notepad++”。打开文件，转到编辑、EOL 转换，选择 UNIX (LF)，然后保存文件。 别忘了再次运行“docker compose up -d”。
> 
> 我花了很长时间来解决这个问题，不确定这是否算是一个错误？

可以解决nginx，ssrf_proxy的docker无法启动问题

**Comment by listelin** [comment]
On windows, if git config core.autocrlf is true (default), the above problem occurs and DIFY cannot be started.

You can manually change CRLF -> LF as described above, but changing the git config and pulling should solve the problem.
git config --global core.autocrlf false

**Comment by MWang-TS** [comment]
> @damadorPL
> 
> "docker\nginx\docker-entrypoint.sh" "docker\ssrf_proxy\docker-entrypoint.sh"
> 
> Converting these two files from CRLF to LF will resolve the issue.
> 
> You can use "Notepad++". Open the file, go to Edit, EOL Conversion, select UNIX (LF), and save the file. Don't forget to run "docker compose up -d" again.
> 
> I spent quite some time figuring this out, not sure if it counts as a bug?

It works finally, great !   Thanks a lot !

**Comment by MWang-TS** [comment]
all 0.6.12 containers are started but got this issue at (http://localhost/install) page ?
![Screenshot 2024-06-29 121951](https://github.com/langgenius/dify/assets/76930061/779f733f-daf1-436b-80ef-f34d955af11f)

**Comment by crazywoola** [comment]
I guess @MWang-TS you need to attach the screenshot of web console.

**Comment by MWang-TS** [comment]
> I guess @MWang-TS you need to attach the screenshot of web console.

The screenshot above is the interface for initializing the administrator user password ，after I click [Setting up an admin account] from signin page.

**Comment by KevinLoveGitHub** [comment]
+1  

❌ Actual Behavior
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

**Comment by crazywoola** [comment]
> +1
> 
> ❌ Actual Behavior redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

@KevinLoveGitHub It happens when you have other redis server started in you machine. You can turn this off. And start the application again.

**Comment by KevinLoveGitHub** [comment]
> > +1
> > ❌ Actual Behavior redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
> 
> @KevinLoveGitHub It happens when you have other redis server started in you machine. You can turn this off. And start the application again. Also please pull the latest code.

The server is not running redis service. It will be correct if it is reduced to 0.6.11
