### ISSUE TITLE
Unable to register text-embedding-3-large model under corporate proxy

### ISSUE THREAD

**Issue by potofo** [langgenius/dify#5732]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Unable to register Azure OpenAI text-embedding-3-large model under corporate proxy.
Does anyone know how to isolate and solve the issues?

**1. Add corporate proxy to Docker Deamon**
```
# vi /etc/systemd/system/docker.service.d/http-proxy.conf
```
```
[Service]
Environment="HTTP_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080"
Environment="HTTPS_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080"
Environment="NO_PROXY=localhost, 127.0.0.1, aoai.corporate.co.jp, ollama.corporate.co.jp"
```

```
# ​systemctl daemon-reload
# systemctl restart docker

confirm proxy for Docker Daemon 

# systemctl show --property=Environment docker
Environment=HTTP_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080 HTTPS_PROXY=http://hogehoge:hogepage@proxy.corporate.co.jp:8080 "NO_PROXY=localhost, 127.0.0.1, aoai.corporate.co.jp, ollama.corporate.co.jp"
```

**2. Add corporate proxy to Docker Client**
```
# vi ~/.docker/config.json
```
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://hogehoge:hogepage@proxy.corporate.co.jp:8080",
     "httpsProxy": "http://hogehoge:hogepage@proxy.corporate.co.jp:8080",
     "noProxy": "localhost, 127.0.0.1, aoai.corporate.co.jp, ollama.corporate.co.jp"
   }
 }
}
```
**3. Add Text Embedding Model Provider**
[Dify]->[Settings]->[Model Provider]->[Azure OpenAI Service]->[Add model]
The Azure OpenAI embedding models added are as follows:

```
Model Type:Text Embedding
Deployment Name:text-embedding-3-large
API Endpoint URL:https://aoai_corporate.openai.azure.com/
API Key:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
API Version:2024-02-15-preview
Base Model:text-embedding-3-large
```
Deployment Name, API Endpoint URL, API Key, API Version, and Base Model are proven models without corporate proxies.   
However, adding the text-embedding-3-large model fails with the following error.  

Error code: 400 - {'error': {'code': 'Operation Not Supported', 'message': The embeddings operation does not work with the specified model, gpt-4. Please choose different model and try again. You
Can learn more about which models can beused with each operation here: https://go.microsoft.com/fwIink/?Iinkid=2197993.'}}
```


### ✔️ Expected Behavior

_No response_

### ❌ Actual Behavior

_No response_

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5733
