### ISSUE TITLE
Input is missing in API based extensions

### ISSUE THREAD

**Issue by crazywoola** [langgenius/dify#5734]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

<img width="1370" alt="image" src="https://github.com/langgenius/dify/assets/100913391/c3b7cad3-9a8d-46e5-9b25-e06d53c7bd7f">

### ✔️ Expected Behavior

There should be a input box.

### ❌ Actual Behavior

No input box displayed.

**Comment by takatost** [comment]
API-based extensions variable is for easily getting data from external APIs and then putting it into the prompt. It's not sth the user fills in.
Lack of doc @VincePotato

**Comment by akkaz** [comment]
> API-based extensions variable is for easily getting data from external APIs and then putting it into the prompt. It's not sth the user fills in. Lack of doc @VincePotato

Anyway the API-base variables miss a place where you can put your input (not the use input for prompting, but **the input you have to pass during API call**)

**Comment by VincePotato** [comment]
> API-based extensions variable is for easily getting data from external APIs and then putting it into the prompt. It's not sth the user fills in. Lack of doc @VincePotato

https://docs.dify.ai/v/zh-hans/guides/knowledge-base/external_data_tool
