### ISSUE TITLE
Icons missing in model settings interface after upgrading to Dify-0.6.12

### ISSUE THREAD

**Issue by lukefan** [langgenius/dify#5735]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgrading to Dify-0.6.12, I've successfully started the application by modifying the .env file. However, I've encountered an issue where the icons in the model settings interface are missing. Please see the attached image for reference.
![1661719626891_ pic](https://github.com/langgenius/dify/assets/3324749/32c2d7ef-02f9-4ce8-b27d-d40337cc86c4)
Environment details:

Dify version: 0.6.12
Storage: Local storage
Database: Local PostgreSQL (for both main database and vector database)
Cache: Local Redis
Steps to reproduce:

Upgraded to Dify-0.6.12
Modified the .env file to ensure proper startup
Accessed the model settings interface
Expected behavior:
Icons should be visible in the model settings interface.

Actual behavior:
Icons are missing from the model settings interface.

Questions:

Is it possible that I've made an incorrect modification to the .env file that could cause this issue?
Are there any specific configuration settings related to icon display that I should check?
Could this be a known issue with the 0.6.12 version?
Additional information:
I'm using local storage for file management. Both PostgreSQL (for main and vector databases) and Redis are running on the local host.

Any assistance or guidance on resolving this issue would 
be greatly appreciated. Thank you in advance for your help.

**Comment by crazywoola** [comment]
Please attach the screenshot of the icons' request url. If you got direct to https://cloud.dify.ai/. Yes, you need to check the `.env` settings.

**Comment by Anrunlu** [comment]
I encountered the same problem. It was indeed an issue with the URL. Modifying `CONSOLE_API_URL=http://localhost` in the .env file solved my problem.

before
![screenshot-20240629-103058](https://github.com/langgenius/dify/assets/41146980/f202abe4-2f53-4a3a-a4b2-755e07726fb7)

after 
![screenshot-20240629-105107](https://github.com/langgenius/dify/assets/41146980/438a38b8-0af5-4b5b-b37f-38ee83d2903e)

**Comment by lukefan** [comment]
# Specifies the allowed origins for cross-origin requests to the console API,
# e.g. https://cloud.dify.ai or * for all origins.
CONSOLE_CORS_ALLOW_ORIGINS=*

I haven't changed anything.

and I tried 
CONSOLE_CORS_ALLOW_ORIGINS=http://localhost
and
CONSOLE_CORS_ALLOW_ORIGINS=‘’

don't work.

**Comment by crazywoola** [comment]
```
CONSOLE_API_URL=http://localhost
```

You should change this one, not `CONSOLE_CORS_ALLOW_ORIGINS `.

**Comment by lukefan** [comment]
> ```
> CONSOLE_API_URL=http://localhost
> ```
> 
> You should change this one, not `CONSOLE_CORS_ALLOW_ORIGINS `.

After further investigation, I've discovered that this appears to be a bug. Here are the details:

When I set CONSOLE_API_URL=http://localhost, the application runs correctly, but it can only be accessed through http://localhost. Attempting to access it via the internal IP address fails.
When I set CONSOLE_API_URL='' (empty string), I can successfully access the application through the internal IP address. However, this causes the icons to point to https://cloud.dify.ai/.
These findings suggest that there might be an issue with how the application handles the CONSOLE_API_URL setting and icon loading.

**Comment by crazywoola** [comment]
```
CONSOLE_API_URL=http://your ip address
```
Then you should change to above, or you can change the dns record to point localhost to your ip addres.

**Comment by lukefan** [comment]
Update:

I've found a temporary workaround for this issue:

Directly modify the docker-compose.yaml file:
web:
  image: langgenius/dify-web:0.6.12
  restart: always
  environment:
    CONSOLE_API_URL: ''
    APP_API_URL: ${APP_API_URL:-}
    SENTRY_DSN: ${SENTRY_DSN:-}
  # # # uncomment to expose dify-web port to host
  # ports:
  #   - "80:80"
  #   - "3000:3000"
Set the CONSOLE_API_URL to an empty string ('') directly in the docker-compose.yaml file.
With this configuration, I can now access the application through both localhost and the internal IP address, and the icons are loading correctly.

**Comment by guchenhe** [comment]
hi,

> Update:
> 
> I've found a temporary workaround for this issue:
> 
> Directly modify the docker-compose.yaml file:
> 
> ```
> web:
>   image: langgenius/dify-web:0.6.12
>   restart: always
>   environment:
>     CONSOLE_API_URL: ''
>     APP_API_URL: ${APP_API_URL:-}
>     SENTRY_DSN: ${SENTRY_DSN:-}
>   # # # uncomment to expose dify-web port to host
>   # ports:
>   #   - "80:80"
>   #   - "3000:3000"
> ```
> 
> Set the CONSOLE_API_URL to an empty string ('') directly in the docker-compose.yaml file. With this configuration, I can now access the application through both localhost and the internal IP address, and the icons are loading correctly.

Hmm, that's weird, `CONSOLE_API_URL` should default to empty string from the get go. can i see the output of `docker compose config | grep -A 10 web | grep CONSOLE_API_URL` before and after you make the change?

**Comment by edisonzf2020** [comment]
CONSOLE_API_URL: ''
Even if I set it up like this, the model still has no icon, whether I modify the .env file or the docker-compose.yaml file.

**Comment by lukefan** [comment]
> hi,
> 
> > Update:
> > I've found a temporary workaround for this issue:
> > Directly modify the docker-compose.yaml file:
> > ```
> > web:
> >   image: langgenius/dify-web:0.6.12
> >   restart: always
> >   environment:
> >     CONSOLE_API_URL: ''
> >     APP_API_URL: ${APP_API_URL:-}
> >     SENTRY_DSN: ${SENTRY_DSN:-}
> >   # # # uncomment to expose dify-web port to host
> >   # ports:
> >   #   - "80:80"
> >   #   - "3000:3000"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Set the CONSOLE_API_URL to an empty string ('') directly in the docker-compose.yaml file. With this configuration, I can now access the application through both localhost and the internal IP address, and the icons are loading correctly.
> 
> Hmm, that's weird, `CONSOLE_API_URL` should default to empty string from the get go. can i see the output of `docker compose config | grep -A 10 web | grep CONSOLE_API_URL` before and after you make the change?

It's quite interesting that although both settings end up with the same command: "docker compose config | grep -A 10 web | grep CONSOLE_API_URL" and the output is "CONSOLE_API_URL: "", the actual running results are indeed different.
