### ISSUE TITLE
Add 'sync from aws s3 bucket' as data source for Knowledge

### ISSUE THREAD

**Issue by whpen** [langgenius/dify#5738]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

My team uses AWS S3 to maintain the documents. It would be great if the documents in S3 bucket can be directly synced to the Dify Knowledge. 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Hi @whpen, sry but this request isn’t on our roadmap rn. You can try using the Knowledgebase API to implement it yourself tho. 😕
