### ISSUE TITLE
Error retrieving the icon image of the large model provider in the workspace.

### ISSUE THREAD

**Issue by yancyuu** [langgenius/dify#5740]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![difY_error](https://github.com/langgenius/dify/assets/56645657/021268b6-d7df-4420-a262-6d45082c419b)

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5735
