### ISSUE TITLE
Unable to delete empty knowledge base

### ISSUE THREAD

**Issue by XiaoLey** [langgenius/dify#5747]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Description:

When attempting to delete an empty knowledge base, I encountered an error that states, "The dataset is being used by some apps. Please remove the dataset from the apps before deleting it." Previously, this knowledge base was associated with some apps, but the associations have since been removed. Despite this, the knowledge base cannot be deleted.

I believe this issue might be a rare occurrence, as I have successfully deleted knowledge bases under similar circumstances in the past.

![Snipaste_2024-06-29_19-40-27](https://github.com/langgenius/dify/assets/46273173/6805a90a-fbc7-4607-af6a-82389dd4a638)

1. Create a new knowledge base.
2. Associate the knowledge base with some apps.
3. Remove the associations from the apps.
4. Ensure the knowledge base is empty.
5. Try to delete the empty knowledge base.
6. Observe the error message preventing the deletion.

### ✔️ Expected Behavior

The empty knowledge base, having no associations with apps, should be deletable without errors.

### ❌ Actual Behavior

An error message is shown, preventing the deletion of the empty knowledge base as if it is still being used by some apps.

**Comment by JohnJyong** [comment]
pls double confirm are there any apps linked this Knowledge 
<img width="245" alt="image" src="https://github.com/langgenius/dify/assets/76649700/87bfb603-9f9b-44ac-9b81-0ddfdb041a71">
@XiaoLey

**Comment by XiaoLey** [comment]
![image](https://github.com/langgenius/dify/assets/46273173/4eb67863-8bee-4d04-8660-08f23009a652)

@JohnJyong

**Comment by kkailaasa** [comment]
facing a similar issue, not able to delete a knowledge base. Getting error saying this knowledge base is associated to an app even though that app has been deleted

**Comment by JohnJyong** [comment]
it has been opimized by below pr:
https://github.com/langgenius/dify/pull/5810
https://github.com/langgenius/dify/pull/5787
@kkailaasa @XiaoLey  thanks for your feedback

**Comment by kkailaasa** [comment]
have pulled the latest docker image, this issue has been fixed, thank you
