### ISSUE TITLE
新系统部署后，启动install页面F12开发者工具显示502请求，发现API和worker容器一直在重启

### ISSUE THREAD

**Issue by kissyy16** [langgenius/dify#5756]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[362f4299979a9b769169d93ece61471ccc7c278857f95b7962386a9e1169eeb5-json.log](https://github.com/user-attachments/files/16040963/362f4299979a9b769169d93ece61471ccc7c278857f95b7962386a9e1169eeb5-json.log)
[f461be62d77efbfc41d48f6203165eb6533b2e7d300400e555d2221f707c184c-json.log](https://github.com/user-attachments/files/16040964/f461be62d77efbfc41d48f6203165eb6533b2e7d300400e555d2221f707c184c-json.log)

这个是日志

### ✔️ Expected Behavior

正常运行

### ❌ Actual Behavior

API和worker容器一直在重启，页面加载不出初始化用户名和密码，F12开发工具显示请求502错误

**Comment by t1804330987** [comment]
can you tell me this answer, I also get this problem. I need you help ,pleas ,ku boy
