### ISSUE TITLE
Can I move start chat button？I want to directly to chat

### ISSUE THREAD

**Issue by shiliu2023** [langgenius/dify#5757]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Can I move start chat button？I want to directly to chat

### 2. Additional context or comments

Can I move start chat button？I want to directly to chat

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by VincePotato** [comment]
This suggestion is reasonable. We will consider redesigning the webapp in dify, and making the START guidance a configurable option would be better.

**Comment by shiliu2023** [comment]
👍

**Comment by ZimaBlueee** [comment]
> This suggestion is reasonable. We will consider redesigning the webapp in dify, and making the START guidance a configurable option would be better.这个建议是有道理的。我们会考虑重新设计 dify 中的 webapp，并将 START 指南设为可配置选项会更好。

Please!!This extra step seems unnecessary for the user experience.
It's a similar issue：#5410

**Comment by crazywoola** [comment]
Close as duplicated https://github.com/langgenius/dify/issues/5410
