### ISSUE TITLE
API based plugin get null input but the variable is not null

### ISSUE THREAD

**Issue by forrestsocool** [langgenius/dify#5763]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Cloud

### Steps to reproduce

api based plugin in the workflow, the input "article_ids" is not null, but server recieve null.
![image](https://github.com/langgenius/dify/assets/3960433/033db388-90b5-4997-a72b-eea6b3bc0717)

### ✔️ Expected Behavior

plugin should post it's input, regardless of it's special character or something, it's user's stuff. 

### ❌ Actual Behavior

 server recieve null

**Comment by forrestsocool** [comment]
@dosu "article_ids" is included in this property as described in the picture, even you input the variable directly, it's still get null.  `[\"39277\", \"39287#39130\", \"38976#39087#38801\", \"39016#39060#38995#38768\", \"38923#39110#38880\", \"39289\", \"38924\", \"38967\", \"39017#39017\"]`

**Comment by forrestsocool** [comment]
哪个大聪明负责的Node输入输出的代码，bug真是多，还有好多没提的:  
不同Node之间传输的变量也会被撸掉好多字符、
输出数组莫名其妙限制长度100、
输出字符串限制80k，
到处都是拍脑袋。。

**Comment by huu3301** [comment]
@forrestsocool 
@dosu
The same problem occur when I use the workflow as tool, that is because the output type of the tool is string, so the next block can not get the value of the parameter. 
I'm not sure if this is an issue.
![2](https://github.com/langgenius/dify/assets/44219645/2429e8a8-44e4-4004-b71c-ec600891b507)

**Comment by Sakura4036** [comment]
yes, the output type of workflow tools is string. If you want to get the output of the tool, you need to manually extract the variable using the code execution node as shown below, where `output` is the name of the variable output by the end node of the workflow tool:
![image](https://github.com/langgenius/dify/assets/42060616/bc9f4324-d7a9-43f8-8c81-e3ed67f849aa)
