### ISSUE TITLE
Q&A format choose chinese. Shows 0 paragraphs. Other languages work normally.

### ISSUE THREAD

**Issue by kissyy16** [langgenius/dify#5764]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Default paragraph preview displays normally, but when I select the Q&A segment format and switch to Q&A mode, it shows nothing.

1. 
![image](https://github.com/langgenius/dify/assets/76425775/64fb63a3-2193-4011-b914-9c0ed848d845)

2. 
![image](https://github.com/langgenius/dify/assets/76425775/af029cfa-f0fe-4a48-88eb-7240e0b8a4f0)

3. 
![image](https://github.com/langgenius/dify/assets/76425775/3174a37d-e115-4a73-8c00-0e28ea214479)

4. 
![image](https://github.com/langgenius/dify/assets/76425775/d1f6b0c2-51f1-4c4f-b121-96726b651797)

### ✔️ Expected Behavior

Correctly splitting Q&A format

**Comment by kissyy16** [comment]
I use the local LLM and embedding model

**Comment by kissyy16** [comment]
![image](https://github.com/langgenius/dify/assets/76425775/ef6ec048-4828-4679-88da-9edc443ca087)

**Comment by kissyy16** [comment]
The English-language document can be properly segmented, but when uploading a Chinese content document, it defaults to the "Chinese" option. The dropdown menu offers both Simplified and Traditional Chinese as options. Choosing either Simplified or the default "Chinese" does not allow for segmentation.

Please note that this appears to describe a software feature in terms of language selection and text formatting issues.

![image](https://github.com/langgenius/dify/assets/76425775/f4962dc3-8a10-4ca5-9db1-4ee280219887)

![image](https://github.com/langgenius/dify/assets/76425775/074f4f1d-1ad3-4a24-8aae-6ab980fd9d34)

**Comment by kissyy16** [comment]
Documents using Chinese content can also be segmented when choosing English, but it doesn't work if Chinese is selected. Could this be a bug?
![image](https://github.com/langgenius/dify/assets/76425775/5c5b91ff-5d5a-41e9-973d-e5cfa8da7cc3)

**Comment by kissyy16** [comment]
@JohnJyong Only choose Chinese or Chinese Simplified or Chinese Traditional will be empty. The other languages are worked

**Comment by kissyy16** [comment]
@JohnJyong modify request params doc_language="ch" works.  You can try.

**Comment by JohnJyong** [comment]
When the language mark is Chinese, it seems that your llm does not perform very well when generating qa.

**Comment by JohnJyong** [comment]
could you pls try other models, such as gpt4 ?

**Comment by sdlszjb** [comment]
too. 
I use qwen:32b as llm model, and use bge-large-zh-v1.5 as embedding model.

about mouth ago, it still work correct.

but it does't work now.

**Comment by sdlszjb** [comment]
Now i use qwen2-7b llm model and bge-large-zh-v1.5 embedding model, in Q&A item, I use Chinese Traditional mod word correct.

**Comment by CharlesSong** [comment]
I 

> Now i use qwen2-7b llm model and bge-large-zh-v1.5 embedding model, in Q&A item, I use Chinese Traditional mod word correct.

indexing too slow,how to improve?

**Comment by silence-pan84** [comment]
Has the problem been solved at last? I am also using the "BGE-base-en-V1.5" embedded model, and the segmented use of English normal simplified Chinese failed @kissyy16

**Comment by silence-pan84** [comment]
> @JohnJyong修改请求参数 doc_language="ch" 是可行的。你可以试试。

请问这个参数怎么修改，感谢！

**Comment by silence-pan84** [comment]
Has the problem been solved at last? I am also using the "BGE-base-zh-V1.5" embedded model, and the segmented use of English normal simplified Chinese failed

**Comment by roki1031** [comment]
> @JohnJyong modify request params doc_language="ch" works. You can try.修改请求参数 doc_language="ch" 有效。你可以试试。

请问怎么修改？

**Comment by Mingxiangyu** [comment]
我也一样遇到了这种问题
![image](https://github.com/user-attachments/assets/2405ce01-4dc3-4a88-9577-d84d9e12929c)
![image](https://github.com/user-attachments/assets/5ce47e29-cc3d-4d58-9eac-8b05e0d13058)
嵌入模型是
![image](https://github.com/user-attachments/assets/aa94616a-d5a3-41ec-9438-2320b33893b1)

**Comment by Mingxiangyu** [comment]
我也遇到了同样的问题，简体中文没法实现QA分段，嵌入模型是：chevalblanc/acge_text_embedding，dify版本是：0.6.14
但是我一个月前是可以正常使用的。

I also encountered the same problem. Simplified Chinese cannot implement QA segmentation. The embedding model is: chevalblanc/acge_text_imbedding, and the dify version is 0.6.14
But I was able to use it normally a month ago.
@CharlesSong @crazywoola

**Comment by nhha1602** [comment]
I had same issue.
This issue caused by _format_split_text & format_split_text. If the input text have special character as "*" (some LLM model returns result in markdown format), these function will return empty list -> qa_preview will be empty. And one more thing, if the output not in format: Q1:\nA1:\nQ2:\nA2:... qa_preview also empty.
