### ISSUE TITLE
Stuck while creating administrator account

### ISSUE THREAD

**Issue by Shuming-Cheng** [langgenius/dify#5765]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After the normal installation steps, enter the interface and prepare to create an administrator account. Unable to load
![image](https://github.com/langgenius/dify/assets/60544052/fd644463-b573-4f17-acc6-9820080c7a09)

### ✔️ Expected Behavior

Creating an account normally

### ❌ Actual Behavior

Unable to create account

**Comment by potofo** [comment]
Hi @Shuming-Cheng 

Please confiem the following three points.
I sccesfull to execute Dify-0.6.12-fix1 with this temporary measure.

1. Create the dify/docker/.env file (#5744)
cp dify/docker/.env.example dify/docker/.env
2. Set CONSOLE_API_URL (#5735)
vi dify/docker/.env
```
# The backend URL of the console API,
# used to concatenate the authorization callback.
# If empty, it is the same domain.
# Example: https://api.console.dify.ai
CONSOLE_API_URL=http://localhost
```
3. Set CONSOLE_API_URL in the web section of docker-compose.yaml (#5735)
```
# Frontend web application.
web:
image: langgenius/dify-web:0.6.12-fix1
restart: always
environment:
#CONSOLE_API_URL: ${CONSOLE_API_URL:-}
CONSOLE_API_URL: ''
``

**Comment by Shuming-Cheng** [comment]
![image](https://github.com/langgenius/dify/assets/60544052/81450ae7-f79b-494f-bdcf-c201fedeccbe)
![image](https://github.com/langgenius/dify/assets/60544052/b1380a00-06f5-47c8-b07f-a48adf7a6b48)
Created a new. env file
The following changes have been made to Docker Compose.yaml
docker compose up -d
The problem is still unresolved

**Comment by Shuming-Cheng** [comment]
hello @potofo , I still can't fix this problem.

**Comment by takatost** [comment]
Hey @Shuming-Cheng 😃, thx a lot for your feedback! You can help us pinpoint the issue by following these steps:

1. Open your browser’s dev tools, switch to the Network tab, and refresh the page. Check if there are any requests still loading or failing. If you see any suspicious requests, take a screenshot of the request list and the details of those requests 
   
2. Have you made any changes to the `docker-compose.yaml` and `.env` configuration files? Especially configs related to addresses and ports like the nginx port, `CONSOLE_API_URL`, and CORS settings, etc.

Thx!

**Comment by potofo** [comment]
hello @Shuming-Cheng 

Have you confirmed the fix in the dify/docker/docker-compose.yaml file?
You huve to  change following line 307.

before 
  307  **CONSOLE_API_URL: ${CONSOLE_API_URL:-}**
after
  307  **CONSOLE_API_URL: ''**
  
  ```
303   web:
304     image: langgenius/dify-web:0.6.12-fix1
305     restart: always
306     environment:
307       #CONSOLE_API_URL: ${CONSOLE_API_URL:-}
308       CONSOLE_API_URL: ''
309       APP_API_URL: ${APP_API_URL:-}
310       SENTRY_DSN: ${SENTRY_DSN:-}
  ```

**Comment by Tomuncle1** [comment]
same question,hope to solve it

**Comment by 0sengseng0** [comment]
> Hey @Shuming-Cheng 😃, thx a lot for your feedback! You can help us pinpoint the issue by following these steps:嘿@Shuming-Cheng 😃，非常感谢您的反馈！您可以按照以下步骤帮助我们查明问题：
> 
> 1. Open your browser’s dev tools, switch to the Network tab, and refresh the page. Check if there are any requests still loading or failing. If you see any suspicious requests, take a screenshot of the request list and the details of those requests打开浏览器的开发工具，切换到“网络”选项卡，然后刷新页面。检查是否有任何请求仍在加载或失败。如果您发现任何可疑请求，请截取请求列表以及这些请求的详细信息
> 2. Have you made any changes to the `docker-compose.yaml` and `.env` configuration files? Especially configs related to addresses and ports like the nginx port, `CONSOLE_API_URL`, and CORS settings, etc.您是否对 `docker-compose.yaml` 和 `.env` 配置文件进行了任何更改？特别是与地址和端口相关的配置，例如 nginx 端口、 `CONSOLE_API_URL` 和 CORS 设置等。
> 
> Thx! 谢谢！
I deployed dify on the server and got a CORS error when initializing on the client:
![image](https://github.com/langgenius/dify/assets/73268510/3f446da3-0232-4322-9362-08b476749718)
![image](https://github.com/langgenius/dify/assets/73268510/0e6c002a-db78-4451-bfe8-fde6db76878f)
![image](https://github.com/langgenius/dify/assets/73268510/3b434a71-b166-4375-935b-518259feb67d)
![image](https://github.com/langgenius/dify/assets/73268510/ce33e4a6-1085-428b-a49c-1056a3c81b3d)
![image](https://github.com/langgenius/dify/assets/73268510/fae57371-e901-40ca-a4f5-3391653e3e94)
# milvus-standalone log
![image](https://github.com/langgenius/dify/assets/73268510/429f779a-3577-4792-b003-a616c0423ff2)
![image](https://github.com/langgenius/dify/assets/73268510/36871a54-64c3-4b74-a39e-b50ed0707b60)

**Comment by crazywoola** [comment]
<img width="282" alt="image" src="https://github.com/langgenius/dify/assets/100913391/61f3c249-ecfd-4a24-b47a-c134edd4f978">
See this, you are trying to access localhost from public ip address. @0sengseng0 
You should set this `CONSOLE_API_URL` to your ip address instead.
