### ISSUE TITLE
Has not a  'Add Ollama' UI on my local dify web page

### ISSUE THREAD

**Issue by kylezhang** [langgenius/dify#5766]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. I installed Ollama and Llava on WSL, and Ollama can run Llava for a normal conversation.
2. I followed this tutorial to complete the deployment of Dify: [Docker Compose Deployment | Dify](https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/docker-compose), and I am now able to log in and access it normally.
3. In the web interface under "Settings" -> "Model Providers," I can't find an entry to add Ollama.
![image](https://github.com/langgenius/dify/assets/3679798/b1134835-08b3-498b-bb5b-2b7444b8c21f)

### ✔️ Expected Behavior

I can normally add models that are locally deployed with Ollama.

### ❌ Actual Behavior

Has not a  'Add Ollama' UI on my local dify web page

**Comment by takatost** [comment]
So sorry about that! We've fixed the issue with the model provider icon not showing up. You can upgrade to `0.6.12-fix1` now.

**Comment by kylezhang** [comment]
> So sorry about that! We've fixed the issue with the model provider icon not showing up. You can upgrade to `0.6.12-fix1` now.

Thanks, now it 's okay.
![image](https://github.com/langgenius/dify/assets/3679798/d637c5ea-7014-41d1-b886-47b812f6fc3f)
![image](https://github.com/langgenius/dify/assets/3679798/cdc1c709-36de-4d06-98fb-4ed6556d67f5)
