### ISSUE TITLE
Can‘t save Xinference model on setting page

### ISSUE THREAD

**Issue by Arcmoon-Hu** [langgenius/dify#5770]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use docker complete deploy and open the web ui.
![image](https://github.com/langgenius/dify/assets/50002441/3047349b-769d-43fe-a72e-77ab1ffce437)

### ✔️ Expected Behavior

Can click save

### ❌ Actual Behavior

Can't click save

**Comment by leslie2046** [comment]
try http://127.0.0.1:9997 ?

**Comment by Arcmoon-Hu** [comment]
> try http://127.0.0.1:9997 ?

The key point is the "save" button can't click

**Comment by takatost** [comment]
Hi @Arcmoon-Hu, you can scroll to the bottom of this pop-up. There’s a “Model uid” parameter there. You might wanna tweak the resolution to show more content.

**Comment by Arcmoon-Hu** [comment]
> Hi @Arcmoon-Hu, you can scroll to the bottom of this pop-up. There’s a “Model uid” parameter there. You might wanna tweak the resolution to show more content.

cool
