### ISSUE TITLE
Add Stable Diffusion ComfyUI as a tool in Dify

### ISSUE THREAD

**Issue by drfenixlinghu** [langgenius/dify#5772]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Stable DIffusion ComfyUI can do a lot more than WebUI and it's easier to to use (queue follow the established workflow) , so I think it would be great to add SD-ComfyUI to the tool list in Dify. Users will be able to high quality image/video via DIfy that cannot be done using SD-WebUI.

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by lbt981** [comment]
+1

**Comment by dwgeneral** [comment]
I can contribute for this, will do it when free

**Comment by pzc163** [comment]
+1

**Comment by zhiqunlin** [comment]
i think  if workflows http-node  support condition wait for response（comfyui queue  img for reply）will be enough

**Comment by jackeldestripat** [comment]
Example script to get img from comfyui
https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py

This one with the Login extension install on the Comfy server
https://github.com/liusida/ComfyUI-Login/blob/main/script_examples/websockets_api_example.py

**Comment by av8dtop** [comment]
https://github.com/StableCanvas/comfyui-client
不知道這個有沒有幫助?

**Comment by crazywoola** [comment]
(#8385)
