### ISSUE TITLE
Accept `CODE_EXECUTION_API_KEY` as alias of `API_KEY` in `sandbox`

### ISSUE THREAD

**Issue by BorisPolonsky** [langgenius/dify#5773]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The divergence between https://github.com/langgenius/dify/blob/eab0ac3a13bea3a2f952fa42eccf2a12cd3e2508/docker/docker-compose.yaml#L248 and
https://github.com/langgenius/dify/blob/eab0ac3a13bea3a2f952fa42eccf2a12cd3e2508/docker/docker-compose.yaml#L345 makes it harder to maintain these configurations in a single template for multiple components(i.e. `api` and `sandbox`) in helm chart.

### 2. Additional context or comments

I'm contributor of `dify-helm` and the riddance of this divergence would definitely simplify helm chart definition. Since `sandbox` is close-sourced, I could not make a PR and would like to request that `dify` consider this compatibility enhancement. 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by takatost** [comment]
Thx for the feedback! I'm merging the two parameters.
