### ISSUE TITLE
After deploying the project with Docker, the administrator registration page cannot be opened and it keeps loading. An error is reported:None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

### ISSUE THREAD

**Issue by t1804330987** [langgenius/dify#5777]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

dify-0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/56469737/6d28474a-67bf-4d19-9229-0ff3bde31a37)
![image](https://github.com/langgenius/dify/assets/56469737/bd2055bc-c3db-4553-9636-235d15987530)

```plaintext
api-1 | Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str]
api-1 | For further information visit https://errors.pydantic.dev/2.7/v/int_parsing
worker-1 exited with code 0
api-1 exited with code 0
worker-1 | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
api-1 | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

### ✔️ Expected Behavior

Correctly display the administrator registration page，I can registry account.

### ❌ Actual Behavior

The page keeps loading without displaying any content.

**Comment by t1804330987** [comment]
Is it necessary to load Conda again after setting up the Docker environment?

**Comment by takatost** [comment]
Hi @t1804330987 , can you copy the `.env.example` in the docker dir to `.env` and try again?

```
cd docker
cp .env.example .env
```

**Comment by t1804330987** [comment]
> Is it necessary to load Conda again after setting up the Docker environment?

Thanks , it solve my solution. I hope can add "cp .env.example .env" in https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/docker-compose

**Comment by takatost** [comment]
> > Is it necessary to load Conda again after setting up the Docker environment?
> 
> Thanks , it solve my solution. I hope can add "cp .env.example .env" in https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/docker-compose

Thank you for the heads-up! We'll add it ASAP!
