### ISSUE TITLE
Nginx is listening on port 80 instead of the value of ${NGINX_PORT} that I set in the .env file.

### ISSUE THREAD

**Issue by Caixiaopig** [langgenius/dify#5783]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Execute `git checkout main` or similar operations to upgrade to the latest version
2. Unable to access Dify started through Docker
3. Investigate the issue and find that Dify's Nginx is listening on port 80 instead of the `${NGINX_PORT}` set in the `.env` file.

### ✔️ Expected Behavior

The Nginx server in Dify is listening on the port specified by the `${NGINX_PORT}` environment variable from the `.env` file.

### ❌ Actual Behavior

Nginx is listening on port 80 for Dify.

**Comment by guchenhe** [comment]
fixed! thanks for the feedback
