### ISSUE TITLE
The tool returns json results but there are no json output variables available in the front-end page tool.

### ISSUE THREAD

**Issue by Sakura4036** [langgenius/dify#5798]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Creating a workflow that uses the GoogleSearch tool.

![image](https://github.com/langgenius/dify/assets/42060616/5fdb8da3-be3c-433a-8dfd-68a898233b35)

### ✔️ Expected Behavior

The tool output variable contains text, files, and json.

Wish the front-end could be modified immediately to accommodate the [JSON Message API in the tool](https://github.com/langgenius/dify/pull/5440). 

### ❌ Actual Behavior

The tool output variable only contains text, files.

**Comment by hjlarry** [comment]
OK, I will try to fix this later.
