### ISSUE TITLE
http request error

### ISSUE THREAD

**Issue by suxuanning** [langgenius/dify#5799]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

HTTP request error
![image](https://github.com/langgenius/dify/assets/29285431/fc5b4d5a-c20e-43e8-93bf-c9d2ff4f9083)
![image](https://github.com/langgenius/dify/assets/29285431/d5546b24-34d4-411b-8bb1-a18f7b320533)

### ✔️ Expected Behavior

Responding correctly to HTTP requests

### ❌ Actual Behavior

I am using an HTTP request and cannot access the HTTP address properly, whether it is a local address or a public network address. Please confirm if the HTTP server can access the local address?

**Comment by suxuanning** [comment]
I hope this issue can be fixed

**Comment by crazywoola** [comment]
We do support using json in request payload.

**Comment by suxuanning** [comment]
@crazywoola Understood, it seems that formatted JSON is not yet supported
