### ISSUE TITLE
Consider using gptcache for caching

### ISSUE THREAD

**Issue by prs1022** [langgenius/dify#5801]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Recalling LLM APIs can be expensive, and the response speed may slow down during LLMs’ peak times, I think dify needs a cache system to deal with this.Now open source gptcache can be considered for use within the supported model range.What do you think？

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by prs1022** [comment]
https://github.com/zilliztech/GPTCache

**Comment by crazywoola** [comment]
Duplicated #848
