### ISSUE TITLE
Failed to get tool runtime: tool parameter require_summary not found in tool config

### ISSUE THREAD

**Issue by 0sengseng0** [langgenius/dify#5805]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/73268510/feb2d739-3ca8-4b66-b75b-354b39de0465)
![image](https://github.com/langgenius/dify/assets/73268510/ef84d45f-82a2-4d87-a617-26d502fc4205)

### ✔️ Expected Behavior

DuckDuckSearch doesn't work in my workflow

### ❌ Actual Behavior

Failed to get tool runtime: tool parameter require_summary not found in tool config

**Comment by Sakura4036** [comment]
this error fixed by https://github.com/langgenius/dify/pull/5303 in dify v0.6.12,  you could upgrade to the latest version.

**Comment by Lz020316** [comment]
![Image](https://github.com/user-attachments/assets/f1db8ec9-b8b1-4e70-b2d7-1da117767141)

![Image](https://github.com/user-attachments/assets/d10afdc8-74ce-4268-8119-f795d173c137)

dify version：0.15.3

**Comment by Lz020316** [comment]
> ![Image](https://github.com/user-attachments/assets/f1db8ec9-b8b1-4e70-b2d7-1da117767141)
> 
> ![Image](https://github.com/user-attachments/assets/d10afdc8-74ce-4268-8119-f795d173c137)
> 
> dify version：0.15.3
