### ISSUE TITLE
Error in workflow using the Claude model in Bedrock in version 0.6.12

### ISSUE THREAD

**Issue by YYyp99** [langgenius/dify#5808]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

We deployed Dify using k8s, which was not a problem before. However, after updating the new version, using the model provided by Bedlock will result in an error in the problem selector of the workflow

### ✔️ Expected Behavior

Previously, our entire workflow was fine, but now the problem classifier will have issues, and using the model directly in the workflow also requires selecting User

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/120240141/879150cc-fe15-4dc6-b499-8c2b78aa00ba)
![image](https://github.com/langgenius/dify/assets/120240141/06d19798-1bf6-4394-9248-05e3a9a51ff0)
The problem selector will report an error, and using the system directly from the model will also report an error

**Comment by YYyp99** [comment]
![image](https://github.com/langgenius/dify/assets/120240141/6eef6add-b6db-49da-b710-deb28f462e09)
Writing prompt will result in an error message

**Comment by luckylhb90** [comment]
<img width="1326" alt="image" src="https://github.com/langgenius/dify/assets/6822397/83bbaace-4ce1-4fa3-90c8-e6cc321446fc">
0.6.12，
I used the same model and the tests worked fine.

**Comment by christiancenti** [comment]
Same problem here

**Comment by YYyp99** [comment]
> Same problem here

Are you also unable to use prompt at 0.6.12?

**Comment by YYyp99** [comment]
> <img alt="image" width="1326" src="https://private-user-images.githubusercontent.com/6822397/344695579-83bbaace-4ce1-4fa3-90c8-e6cc321446fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODI0ODQsIm5iZiI6MTcxOTg4MjE4NCwicGF0aCI6Ii82ODIyMzk3LzM0NDY5NTU3OS04M2JiYWFjZS00Y2UxLTRmYTMtOTBjOC1lNmNjMzIxNDQ2ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDEwMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzUwM2FjM2Y4YTQwYjM5YzE5NTY2NGUzYjZkOGNlNmM2OThhNGQyMGM4MzlhODNjNGQ4ZGE5ZThmM2RjZTQyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.myRK-XcUcaDKMEj6BHtBnTsQZe__E3-xSZOF4g0b4VE"> 0.6.12， I used the same model and the tests worked fine.

I don't know why, 0.6.11 can be used, but after upgrading, it keeps reporting errors. However, I deployed it using k8s, and my upgrade method is to directly pull the latest image

**Comment by crazywoola** [comment]
Possible fix in workflow:
- Leave the system blank
- Add a user prompt
- Edit this prompt
- Test it again

**Comment by YYyp99** [comment]
> Possible fix in workflow:
> 
> * Leave the system blank
> * Add a user prompt
> * Edit this prompt
> * Test it again

This is possible in the workflow, but the problem selector will report an error, and other agents will also report an error when writing prompts. Is this caused by my deployment issue, or is it because other users will also experience similar situations

**Comment by luckylhb90** [comment]
#5768 
I had the same problem today. I then rolled back the local code to before this version, and now it works fine.

**Comment by christiancenti** [comment]
I use both dify in the cloud and locally. With the same version (0.6.12-fix1), locally it works but in cloud it doesn't.

**Comment by longzhihun** [comment]
fixed please refer to the PR.
