### ISSUE TITLE
400 BAD REQUEST

### ISSUE THREAD

**Issue by xkcp008** [langgenius/dify#5809]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![微信截图_20240701152622](https://github.com/langgenius/dify/assets/6188585/4724b1b1-c883-47ee-adf1-c490aa279563)
http://********/console/api/workspaces/current/model-providers/openai   
Error 400 BAD REQUEST invalid_param encountered while setting up the model

**Comment by xkcp008** [comment]
Do I need to climb over a wall to successfully set up ChatGPT? I am using the latest version of GitHub, which should be the latest version

**Comment by crazywoola** [comment]
Please check your openai provider, I can not reproduce this problem with OpenAI apikey.


> How can ordinary users use my website services without VPN ？ Whether to deploy the website abroad ？

You can deploy in Aliyun or Tencent Cloud.
