### ISSUE TITLE
0.6.12 Docker No updates have been seen for #5436

### ISSUE THREAD

**Issue by suxuanning** [langgenius/dify#5815]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/29285431/dd4d6ff1-10b6-4581-af31-263281566f61)

### ❌ Actual Behavior

Docker 0.6.12 No updates have been seen for #5436

**Comment by crazywoola** [comment]
What application type do you choose?

**Comment by suxuanning** [comment]
> 您选择哪种应用程序类型？

Chatbot

**Comment by suxuanning** [comment]
@

**Comment by crazywoola** [comment]
This one？
<img width="1221" alt="image" src="https://github.com/langgenius/dify/assets/100913391/17bba1a9-c0e6-4299-bdf4-5487a2713bfd">
