### ISSUE TITLE
os.environ.get takes None

### ISSUE THREAD

**Issue by xupeng135** [langgenius/dify#5816]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

file code_executor.py at line 21 when useing os.environ.get returns None

**Comment by crazywoola** [comment]
Please set this variable in `.env`

**Comment by xupeng135** [comment]
actually,i already set the variable in .env file。
i finally found that .env variable was set in app.py, but os.environ.get is before app.py set, so it returns None
