### ISSUE TITLE
dify local deployment using docker, can't set OPENAI provider

### ISSUE THREAD

**Issue by rackerxu** [langgenius/dify#5817]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In llm provider,I tried to add OPENAI, but after I provide the key and endpoint, it shows "connection error". But it works when I use a jupyter notebook using requests to access the openai.
![925ea4d683e0e32ca8adf58a0c27cdc](https://github.com/langgenius/dify/assets/166899918/20665e8b-35f4-422b-9c8d-51aa222fcb5b)
![1e768f4fb5122d3a0a0831b86f367b4](https://github.com/langgenius/dify/assets/166899918/11f7894a-b953-4473-ac37-d1b3e1371311)

### ✔️ Expected Behavior

Openai is added

### ❌ Actual Behavior

connection error

**Comment by crazywoola** [comment]
Please config a proper VPN to resolve this issue.
