### ISSUE TITLE
The direct reply block disappeared from the workflow.

### ISSUE THREAD

**Issue by fre2d0m** [langgenius/dify#5818]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a new workflow

2. Add Block

3. Directly Reply has disappeared, and I can't show the reply of LLM to users.

You can still see the blocks of Answer in the documents of Github and Dify.ai.

<img width="257" alt="image" src="https://github.com/langgenius/dify/assets/25602863/451e0094-8b0a-4d37-89a0-1aec48586cdf">

### ✔️ Expected Behavior

I can use Direct Reply to output the large language model to the user.

### ❌ Actual Behavior

Only the End block can be used, and the user only sees a JSON string.

**Comment by crazywoola** [comment]
Yes, this is 'by design'. 
> Only the End block can be used, and the user only sees a JSON string.
You need to set an string typed result in End node, then the user should be able to see the text result. If you have some json result, you just need to use jinja to extract something from this result.

**Comment by fre2d0m** [comment]
Sorry, I found Answer Block. When creating a new Bot, choose chatflow instead of workflow.
