### ISSUE TITLE
for loop in workflow

### ISSUE THREAD

**Issue by liuqingyang1996** [langgenius/dify#5824]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Once I need to get back to previous node and repeat the workflow nodes in the loop until it outputs the correct result, and then continue to execute the remaining nodes.

### 2. Additional context or comments

I find the issue https://github.com/langgenius/dify/issues/4317 has been closed, but the feature is still not supported.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by liuqingyang1996** [comment]
Hi, Vince @VincePotato
will this be supported soon or in progress?

**Comment by crazywoola** [comment]
Afaik, we will not support this feature in this year..

**Comment by VincePotato** [comment]
Loop node is in progress.
