### ISSUE TITLE
Reporting "KeyError: 'app_id' " while send request to api `/api/chat-messages`

### ISSUE THREAD

**Issue by Gitttttttt** [langgenius/dify#5825]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

First, login with email and password;
Then, send a request to the api `/api/chat-messages` with the token (or other login_required apis), it will show follow error:
ERROR:app:Exception on /api/chat-messages [POST]
Traceback (most recent call last):
  File "D:\miniconda3\envs\dify\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\miniconda3\envs\dify\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\miniconda3\envs\dify\lib\site-packages\flask_restful\__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "D:\miniconda3\envs\dify\lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "D:\miniconda3\envs\dify\lib\site-packages\flask_restful\__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "D:\GitProject\wanwei\test\ww-dify\api\controllers\web\wraps.py", line 18, in decorated
    app_model, end_user = decode_jwt_token()
  File "D:\GitProject\wanwei\test\ww-dify\api\controllers\web\wraps.py", line 46, in decode_jwt_token
    app_model = db.session.query(App).filter(App.id == decoded['app_id']).first()
KeyError: 'app_id'
INFO:werkzeug:172.16.60.73 - - [01/Jul/2024 20:02:28] "POST /api/chat-messages HTTP/1.1" 500 -

And the debug info for the method `decode_jwt_token()` in the file `api/controllers/web/wraps.py ` like this(Decoded has not key 'app_id'):
![image](https://github.com/langgenius/dify/assets/38375081/726d50d1-dd2d-41ed-9150-b0da4fbad829)

So why does it get app_id from decoded? Is there anything wrong? 
Thanks for help

### ✔️ Expected Behavior

request correctly

### ❌ Actual Behavior

show errors

**Comment by crazywoola** [comment]
This is not a public an api. If you would like to get technical support on this part, please reach out to our business@dify.ai .
