### ISSUE TITLE
Rewrite the firecrawl custom API url 

### ISSUE THREAD

**Issue by ahasasjeb** [langgenius/dify#5840]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

#5839 

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by laipz8200** [comment]
I’ve reviewed the changes, and unfortunately, `firecrawl-py` is licensed under AGPL-3, which means we won’t be able to use it.

**Comment by laipz8200** [comment]
I noticed that their SDK does not provide a clear LICENSE file, and there are discrepancies between the LICENSE information in the [README](https://github.com/mendableai/firecrawl/blob/main/apps/python-sdk/README.md), [pyproject.toml](https://github.com/mendableai/firecrawl/blob/main/apps/python-sdk/pyproject.toml), and [PyPI](https://pypi.org/project/firecrawl-py/). We need to confirm whether we can use this SDK.

**Comment by ahasasjeb** [comment]
oh
---- Replied Message ----
From ***@***.***> Date 07/02/2024 14:13 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [langgenius/dify] Rewrite the firecrawl custom API url (Issue #5840) 
I noticed that their SDK does not provide a clear LICENSE file, and there are discrepancies between the LICENSE information in the README, pyproject.toml, and PyPI. We need to confirm whether we can use this SDK.

**Comment by ahasasjeb** [comment]
I see that the README.MD file uses the MIT license. ---- Replied Message ---- From ***@***.***> Date 07/02/2024 13:56 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [langgenius/dify] Rewrite the firecrawl custom API url  (Issue #5840) I’ve reviewed the changes, and unfortunately, firecrawl-py is licensed under AGPL-3, which means we won’t be able to use it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by laipz8200** [comment]
They've labeled different licenses in various locations. One of our team members is reaching out to the Firecrawl team to confirm if we can use this SDK.

**Comment by ahasasjeb** [comment]
o
---- Replied Message ----
From ***@***.***> Date 07/02/2024 15:25 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [langgenius/dify] Rewrite the firecrawl custom API url (Issue #5840) 
They've labeled different licenses in various locations. One of our team members is reaching out to the Firecrawl team to confirm if we can use this SDK.

**Comment by ericciarla** [comment]
Hi @ahasasjeb, I am Eric from the Firecrawl team! To confirm, our whole repo and SDKs are released under the [AGPL License](https://www.gnu.org/licenses/agpl-3.0.en.html).

**Comment by ahasasjeb** [comment]
> Hi @ahasasjeb, I am Eric from the Firecrawl team! To confirm, our whole repo and SDKs are released under the [AGPL License](https://www.gnu.org/licenses/agpl-3.0.en.html).

Then you need to modify the license in the Python SDK

**Comment by ericciarla** [comment]
@ahasasjeb It is updated: https://github.com/mendableai/firecrawl/tree/main/apps/python-sdk
