### ISSUE TITLE
Docker compose pull image failed

### ISSUE THREAD

**Issue by qinlei95** [langgenius/dify#5842]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[root@ecs-5001-0313810 docker]# docker compose pull
[+] Pulling 10/41
 ✔ worker Skipped - Image is already being pulled by api                                                                                                                                                                0.0s 
 ⠹ web 13 layers [⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                9.2s 
 ⠹ nginx 7 layers [⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                     9.2s 
 ⠹ redis 8 layers [⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                    9.2s 
 ⠹ db 10 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                    9.2s 
 ⠹ ssrf_proxy 3 layers [⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                    9.2s 
 ⠹ api 10 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                   9.2s 
 ⠹ sandbox 11 layers [⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                              9.2s 
                                                                                                                                                                        
error pulling image configuration: download failed after attempts=6: dial tcp 162.220.12.226:443: connect: connection refused

**Comment by crazywoola** [comment]
Duplicated #5557
