### ISSUE TITLE
Error code: 429, with error text {"error":{"code":"1113","message":"您的账户已欠费，请充值后重试。"}}

### ISSUE THREAD

**Issue by silver0919** [langgenius/dify#5850]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I configured the API of zhipu in the settings, and the following error occurred after clicking save
![bug](https://github.com/langgenius/dify/assets/170061902/b605be8f-5830-4155-a554-a2e5469565b2)

### ✔️ Expected Behavior

Complete the model configuration

### ❌ Actual Behavior

Error code: 429, with error text {"error":{"code":"1113","message":"您的账户已欠费，请充值后重试。"}}

**Comment by crazywoola** [comment]
Please check your api provider and charge that bill.

> 您的账户已欠费，请充值后重试。
