### ISSUE TITLE
No place for UNSTRUCTURED_API_KEY

### ISSUE THREAD

**Issue by JSemc2** [langgenius/dify#5860]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/50313378/adda536b-cf5c-4602-a1a7-69dd5d8bb8fe)

### ✔️ Expected Behavior

There is no place to write a API key for UNSTRUCTURED.

**Comment by crazywoola** [comment]
In `docker/.env`

```
ETL_TYPE=
UNSTRUCTURED_API_URL=
UNSTRUCTURED_API_KEY=
```

**Comment by JSemc2** [comment]
Thanks.
