### ISSUE TITLE
How do I set the address in the URL when I deploy my workflow

### ISSUE THREAD

**Issue by karterotte** [langgenius/dify#5871]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

How do I set the address in the URL when I deploy my workflow。
like the red box in the image below, and specify the name I want
![image](https://github.com/langgenius/dify/assets/9114743/03db40b5-0e43-4d3a-9c05-308288b8d015)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by 0sengseng0** [comment]
My test request is simple and curl like this:    
curl --location 'http://192.168.111.111:9993/translate?text=%E5%88%86%E5%8C%BA%E6%90%9C%E7%B4%A2%E5%B0%86%E6%90%9C%E7%B4%A2%E8%8C%83%E5%9B%B4%E7%BC%A9%E5%B0%8F%E5%88%B0%E9%9B%86%E5%90%88%E7%9A%84%E7%89%B9%E5%AE%9A%E5%AD%90%E9%9B%86%E6%88%96%E5%88%86%E5%8C%BA'

It successfully returns one sentence.
But when I call it in workflow, it always has a status code of 403. This request is simple, did I misconfigure something?
Both services are on a single server.
![image](https://github.com/langgenius/dify/assets/73268510/632a1a52-45ec-4afe-a31d-3735e3258575)

![image](https://github.com/langgenius/dify/assets/73268510/e2ebbcf4-f166-48e9-a14b-695a3d92c266)

**Comment by crazywoola** [comment]
See docs or the bot's answer.

**Comment by karterotte** [comment]
@crazywoola 
Thanks for your reply, I would also like to ask how to set the name of the subnet segment if I publish multiple workflows,not the domain segment.
The example like: I have the url "http://myname.com:8000" and I have 2 or more workflow deployed. It should like "http://myname.com/AAAA:8000" and "http://myname.com/CCCC:8000", "AAAA" and "CCCC" I can set by myself,
It's not set by the system itself like "/v1" or "/v2".
