### ISSUE TITLE
[feat]Deactivate Published Workflow

### ISSUE THREAD

**Issue by thiner** [langgenius/dify#5876]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I have published a workflow, but I then noticed that it's open to internet without any access control. I want to deactivate it, not remove it. 

### 2. Additional context or comments

The other possible way is that add access control for published chat bot and workflow. 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
<img width="733" alt="image" src="https://github.com/langgenius/dify/assets/100913391/77ff2577-2167-4582-9a57-1a3a91efbd7c">
