### ISSUE TITLE
The AI agent uses the SearXNG tool to search for information. The information has been found, but the model responded incorrectly.

### ISSUE THREAD

**Issue by 13428116504** [langgenius/dify#5885]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![8ca1573336791f6e974d4242dbe47f6](https://github.com/langgenius/dify/assets/64519449/3140a10c-3621-4fc8-b350-b6c81557c263)

**Comment by crazywoola** [comment]
Please check the agent log to see if you have used a proper prompt.

**Comment by 13428116504** [comment]
> Please check the agent log to see if you have used a proper prompt.
how to check the agent log? thanks

**Comment by 13428116504** [comment]
> Please check the agent log to see if you have used a proper prompt.

yes, you are right，it is prompt problem, thanks，you can close this issue
