### ISSUE TITLE
Failed to execute code, which is likely a network issue, please check if the sandbox service is running. ( Error: [Errno 113] No route to host )

### ISSUE THREAD

**Issue by allentern** [langgenius/dify#5887]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.12-fix1, v0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Pulled the latest code,
2. Changed port 443 to 4443,
3. Started Docker,
4. Configured all system models,
5. Created a new flow, added a code node with Python, but encountered an error upon execution.
`Failed to execute code, which is likely a network issue, please check if the sandbox service is running. ( Error: [Errno 113] No route to host )`

log:
`(base) root@iplus-s1:/home/rag/dify/docker# docker logs -f docker-ssrf_proxy-1
[ENTRYPOINT] re-create snakeoil self-signed certificate removed in the build process
[ENTRYPOINT] replacing environment variables in the template
2024/07/02 11:08:39| NETDB state saved; 0 entries, 1 msec
2024/07/02 11:49:21| Logfile: opening log stdio:/var/spool/squid/netdb.state
2024/07/02 11:49:21| Logfile: closing log stdio:/var/spool/squid/netdb.state
2024/07/02 11:49:21| NETDB state saved; 0 entries, 0 msec
2024/07/02 12:41:21| Logfile: opening log stdio:/var/spool/squid/netdb.state
2024/07/02 12:41:21| Logfile: closing log stdio:/var/spool/squid/netdb.state
2024/07/02 12:41:21| NETDB state saved; 0 entries, 0 msec
2024/07/02 13:37:31| Logfile: opening log stdio:/var/spool/squid/netdb.state
2024/07/02 13:37:31| Logfile: closing log stdio:/var/spool/squid/netdb.state
2024/07/02 13:37:31| NETDB state saved; 0 entries, 0 msec
2024/07/02 14:10:23| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/squid.conf (depth 0)
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
2024/07/02 14:10:23| Created PID file (/run/squid.pid)
2024/07/02 14:10:23| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/squid.conf (depth 0)
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
2024/07/02 14:10:23| Created PID file (/run/squid.pid)
2024/07/02 14:10:23| Set Current Directory to /var/spool/squid
2024/07/02 14:10:23| Set Current Directory to /var/spool/squid
2024/07/02 14:10:23| Creating missing swap directories
2024/07/02 14:10:23| No cache_dir stores are configured.
2024/07/02 14:10:23| Creating missing swap directories
2024/07/02 14:10:23| No cache_dir stores are configured.
2024/07/02 14:10:23| Removing PID file (/run/squid.pid)
2024/07/02 14:10:23| Removing PID file (/run/squid.pid)
[ENTRYPOINT] starting squid
2024/07/02 14:10:23| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/squid.conf (depth 0)
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| aclIpParseIpData: IPv6 has not been enabled.
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
2024/07/02 14:10:23| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
2024/07/02 14:10:23| Created PID file (/run/squid.pid)
2024/07/02 14:10:23| Set Current Directory to /var/spool/squid
2024/07/02 14:10:23| Starting Squid Cache version 6.6 for x86_64-pc-linux-gnu...
2024/07/02 14:10:23| Service Name: squid
2024/07/02 14:10:23| Process ID 45
2024/07/02 14:10:23| Process Roles: master worker
2024/07/02 14:10:23| With 1024 file descriptors available
2024/07/02 14:10:23| Initializing IP Cache...
2024/07/02 14:10:23| DNS IPv4 socket created at 0.0.0.0, FD 8
2024/07/02 14:10:23| Adding nameserver 127.0.0.11 from /etc/resolv.conf
2024/07/02 14:10:23| Adding ndots 1 from /etc/resolv.conf
2024/07/02 14:10:23| Logfile: opening log daemon:/var/log/squid/access.log
2024/07/02 14:10:23| Logfile Daemon: opening log /var/log/squid/access.log
2024/07/02 14:10:23| Local cache digest enabled; rebuild/rewrite every 3600/3600 sec
2024/07/02 14:10:23| Store logging disabled
2024/07/02 14:10:23| Swap maxSize 0 + 262144 KB, estimated 20164 objects
2024/07/02 14:10:23| Target number of buckets: 1008
2024/07/02 14:10:23| Using 8192 Store buckets
2024/07/02 14:10:23| Max Mem  size: 262144 KB
2024/07/02 14:10:23| Max Swap size: 0 KB
2024/07/02 14:10:23| Using Least Load store dir selection
2024/07/02 14:10:23| Set Current Directory to /var/spool/squid
2024/07/02 14:10:23| Finished loading MIME types and icons.
2024/07/02 14:10:23| HTCP Disabled.
2024/07/02 14:10:23| Pinger socket opened on FD 14
2024/07/02 14:10:23| Squid plugin modules loaded: 0
2024/07/02 14:10:23| Adaptation support is off.
2024/07/02 14:10:23| Accepting HTTP Socket connections at conn2 local=0.0.0.0:3128 remote=[::] FD 11 flags=9
    listening port: 3128
2024/07/02 14:10:23| Accepting reverse-proxy HTTP Socket connections at conn4 local=0.0.0.0:8194 remote=[::] FD 12 flags=9
    listening port: 8194
2024/07/02 14:10:23| Configuring Parent sandbox
2024/07/02 14:10:23| ERROR: Connection to sandbox failed
2024/07/02 14:10:23| Detected DEAD Parent: sandbox
2024/07/02 14:10:23 pinger| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
2024/07/02 14:10:23 pinger| Initialising ICMP pinger ...
2024/07/02 14:10:23 pinger| ICMP socket opened.
2024/07/02 14:10:23 pinger| ICMPv6 socket opened
2024/07/02 14:10:24| storeLateRelease: released 0 objects`

### ✔️ Expected Behavior

Python code can be executed.

### ❌ Actual Behavior

I've been going through issues and documentation for a whole day, from sandbox to various configuration files, without success. I'm on the verge of frustration and really hope you can help resolve this issue. Thanks u.

**Comment by uamyangel** [comment]
我同样的问题，通过下面操作解决。

在 sandbox 镜像下，networks配置增加 default。如下：
```
networks:
  - ssrf_proxy_network
  - default
```

然后重新启动 `docker compose up -d`。

**Comment by JacobDu** [comment]
> 我同样的问题，通过下面操作解决。
> 
> 在 sandbox 镜像下，networks配置增加 default。如下：
> 
> ```
> networks:
>   - ssrf_proxy_network
>   - default
> ```
> 
> 然后重新启动 `docker compose up -d`。

I encountered the same issue on version 0.7.1 and successfully bypassed it through the same operation. This seems to be a bug.

**Comment by zhaozhao777** [comment]
> 我同样的问题，通过下面操作解决。
> 
> 在 sandbox 镜像下，networks配置增加 default。如下：
> 
> ```
> networks:
>   - ssrf_proxy_network
>   - default
> ```
> 
> 然后重新启动 `docker compose up -d`。

你这个方法实测有用，应该是个bug，我找了一下午就你这个好使。

**Comment by shawjay87** [comment]
dify1.6.0版本有同样的问题，有遇到过吗

**Comment by fredwu999** [comment]
> 我同样的问题，通过下面操作解决。
> 
> 在 sandbox 镜像下，networks配置增加 default。如下：
> 
> ```
> networks:
>   - ssrf_proxy_network
>   - default
> ```
> 
> 然后重新启动 `docker compose up -d`。

管用，我折腾了两天了，各种配置文件都快翻烂了，怎么就没想到这里加上试试呢

**Comment by tianlianjie** [comment]
> 我同样的问题，通过下面操作解决。
> 
> 在 sandbox 镜像下，networks配置增加 default。如下：
> 
> ```
> networks:
>   - ssrf_proxy_network
>   - default
> ```
> 
> 然后重新启动 `docker compose up -d`。

我在docker-compose.yaml中加上了这个配置  ， compose up后， 还是不行

**Comment by tianlianjie** [comment]
> 我同样的问题，通过下面操作解决。
> 
> 在 sandbox 镜像下，networks配置增加 default。如下：
> 
> ```
> networks:
>   - ssrf_proxy_network
>   - default
> ```
> 
> 然后重新启动 `docker compose up -d`。

我在docker-compose.yaml中加上了这个配置 ， compose up后， 还是不行
