### ISSUE TITLE
Feature Request: Support for Local Embedding Models(Deployed by Xinference) in Knowledge Base Indexing

### ISSUE THREAD

**Issue by Q-Ot** [langgenius/dify#5905]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I've deployed some embedding models(like bge-large-zh* and bge-m3) by Xinference and I am currently working on creating my knowledge base. 

I have a substantial volume of text that I need to compile into a knowledge base, and I require the ability to frequently update and test the retrieval and answer result through modifications such as segmentation or embedding model. This implies that my knowledge base will undergo very frequent changes and will require the processing of a large amount of text for segmentation and embedding.Currently, being limited to using a paid API for embedding is a source of frustration, as it imposes constraints on the scalability and flexibility of my knowledge base development. 

Dify now provide three indexing methods, High-Quality Mode, Economy Mode and Q&A Mode . I have identified that the current methods do not fully meet my requirements for knowledge base indexing. 
1、High-Quality Mode
When utilizing the high-quality mode, I have discovered from your document and source code that it is not possible to employ a locally deployed embedding model and can only use OpenAI's embedding api. This limitation hinders my ability to customize the embedding process for my specific needs.
2、Economy Mode
Upon reviewing the issues, I noticed that the eco mode employs a keyword-based inverted index maybe base on Jieba segmentation, which does not involve the vectorization of text. While this keyword-based approach could serve as a supplementary reranking mechanism, adding a low-weight score to the retrieved documents, the absence of an embedding score is a critical shortfall.
3、Q&A Mode
I have not yet fully read the source code for the Q&A mode, but based on my current documentation, it seems that the Q&A mode may not be suitable for implementing my requirements.

It would be highly beneficial if the project could support the following features:
1、At least in High-Quality Mode, Supporting the integration of locally deployed embedding models to provide more flexibility and customization for users with specific indexing needs.
2、Improving the eco mode(by adding a new mode or element like switch) to include text vectorization capabilities, which would significantly enhance the search and retrieval process.

### 2. Additional context or comments

I am reaching out to inquire if there is any available information regarding the integration of local deployed embedding models in the current version of the project. Additionally, I would like to know if there are any development plans to support such integration in future releases.

I am a beginner in the field of RAG  and I apologize for any inconvenience caused by my limited proficiency in English. I have made efforts to translate the sections according to my original intent and the terminology used in dify provided documentation. If there are any descriptions that may seem confusing to you, please feel free to reply, and I will do my best to convey my thoughts clearly and accurately.

Thank you for your understanding and support.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
<img width="269" alt="image" src="https://github.com/langgenius/dify/assets/100913391/a7d4d043-97bd-4b8b-b348-502933bfaaab">
As you can see in this image, Xinference do support text-embedding and other kind of models like rerank.

If you would like to change the text-embedding model, you should set things here. 

<img width="545" alt="image" src="https://github.com/langgenius/dify/assets/100913391/199958d6-088f-4e7e-8c68-795f8bd14326">

**Comment by Q-Ot** [comment]
Thank you for your response, but it did not address my issue. 
I‘ve already deployed and configured several embedding models, but I have not found a way to utilize them in either the workflow or the knowledge base.
![p_17200632842642](https://github.com/langgenius/dify/assets/174573649/c7c68523-e7b0-4ac5-a0ec-6cddcd8edf06)

In the workflow, the knowledge retrieval node uses an LLM for the n-select-1 retrieval and a rerank model for multi-retrieval. I am unable to use an embedding model for vector retrieval and then apply the rerank model for reordering.
![p_1720063240990](https://github.com/langgenius/dify/assets/174573649/e6e6a4fe-d8ce-4397-aae4-86fb3bc4fbc4)
![p_17200640459372](https://github.com/langgenius/dify/assets/174573649/4a5bce99-fa8d-48c2-bf9e-d9b8235d89c1)

In the knowledge base, the eco mode does not provide options related to the model, and the high-quality mode, whether it is vector retrieval, full-text retrieval, or hybrid retrieval, only offers choices for the rerank model.
![p_17200641604613](https://github.com/langgenius/dify/assets/174573649/2b8fed31-6832-449b-9079-de3a0d661168)

What I would like to know is whether Dify can provide the following capabilities:
1、In the workflow, the ability to set which embedding model to use for vector recall or multi-recall. Or just automatically switch embedding model to the one which used for making selected knowledge base.
2、When creating or using a knowledge base, the ability to set which embedding model to use for converting segmented text into vectors and storing them in the vector database.

**Comment by Q-Ot** [comment]
> If you would like to change the text-embedding model, you should set things here.

Thank you for your response, but it did not address my issue. 
I‘ve already deployed and configured several embedding models, but I have not found a way to utilize them in either the workflow or the knowledge base.
![p_17200632842642](https://github.com/langgenius/dify/assets/174573649/c7c68523-e7b0-4ac5-a0ec-6cddcd8edf06)

In the workflow, the knowledge retrieval node uses an LLM for the n-select-1 retrieval and a rerank model for multi-retrieval. I am unable to use an embedding model for vector retrieval and then apply the rerank model for reordering.
![p_1720063240990](https://github.com/langgenius/dify/assets/174573649/e6e6a4fe-d8ce-4397-aae4-86fb3bc4fbc4)
![p_17200640459372](https://github.com/langgenius/dify/assets/174573649/4a5bce99-fa8d-48c2-bf9e-d9b8235d89c1)

In the knowledge base, the eco mode does not provide options related to the model, and the high-quality mode, whether it is vector retrieval, full-text retrieval, or hybrid retrieval, only offers choices for the rerank model.
![p_17200641604613](https://github.com/langgenius/dify/assets/174573649/2b8fed31-6832-449b-9079-de3a0d661168)

What I would like to know is whether Dify can provide the following capabilities:
1、In the workflow, the ability to set which embedding model to use for vector recall or multi-recall. Or just automatically switch embedding model to the one which used for making selected knowledge base.
2、When creating or using a knowledge base, the ability to set which embedding model to use for converting segmented text into vectors and storing them in the vector database.
