### ISSUE TITLE
Added the notion integration, which keeps showing 0 authorized pages, but I already authorized the integrated page on notion

### ISSUE THREAD

**Issue by jiegod** [langgenius/dify#5906]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Added the notion integration, which keeps showing 0 authorized pages, but I already authorized the integrated page on notion
<img width="1125" alt="image" src="https://github.com/langgenius/dify/assets/22976415/bed60eea-d599-4cd9-9cee-0c179647effd">

<img width="1350" alt="image" src="https://github.com/langgenius/dify/assets/22976415/8c6ec4fd-63cb-4812-8ae0-71e2bd9b9a1a">

### ✔️ Expected Behavior

dify integrates the notion page and displays notion files normally

### ❌ Actual Behavior

<img width="1162" alt="image" src="https://github.com/langgenius/dify/assets/22976415/9e5d8062-cf91-434a-859d-772149e6c50e">
<img width="799" alt="image" src="https://github.com/langgenius/dify/assets/22976415/eed66932-4149-404f-b255-78a3f988ece6">

**Comment by jiegod** [comment]
> have you clicked the `sync` button ？@jiegod

yes i click. But the effect is still no authorization page

**Comment by yst-one** [comment]
你解决好了吗？我也是这个情况

**Comment by Tendo33** [comment]
Same issue here.

**Comment by JohnJyong** [comment]
pls follow below setting：
```
# Notion import configuration, support public and internal
NOTION_INTEGRATION_TYPE=internal
NOTION_INTERNAL_SECRET=secret_***********
```

@jiegod @Tendo33 @yst-one

**Comment by Tendo33** [comment]
> pls follow below setting：
> 
> ```
> # Notion import configuration, support public and internal
> NOTION_INTEGRATION_TYPE=internal
> NOTION_INTERNAL_SECRET=secret_***********
> ```
> 
> @jiegod @Tendo33 @yst-one

That's exactly what I did.

**Comment by lucaseatp** [comment]
same issue

**Comment by chriswhite5918** [comment]
Same

**Comment by thuanha-groove** [comment]
Same here. Why is this issue closed? @jiegod

**Comment by thuanha-groove** [comment]
After working through the issue, we need to manually share each page with the integration and click "Sync" again. It's Integration permissions section of this official document - https://developers.notion.com/docs/authorization#integration-permissions

> Before an integration can interact with your Notion workspace page(s), the page must be manually shared with the integration. To share a page with an integration, visit the page in your Notion workspace, click the ••• menu at the top right of a page, scroll down to Add connections, and use the search bar to find and select the integration from the dropdown list.

@Tendo33 , @lucaseatp , @chriswhite5918

**Comment by JirehC** [comment]
What about incomplete syncing?
For instance, a database full page has 100 sub pages but it only managed to find 12.

**Comment by SteveMoribe** [comment]
I will include a case that I resolved as well.
I experienced the same issue, and upon carefully re-checking the NOTION_INTERNAL_SECRET, I found a typo. Even though there was a typo, Dify and Notion displayed a successful connection, which delayed the resolution of the problem. In reality, the SECRET was incorrect, so the connection was not actually successful. Please double-check for any typos.

**Comment by JirehC** [comment]
> I will include a case that I resolved as well. I experienced the same issue, and upon carefully re-checking the NOTION_INTERNAL_SECRET, I found a typo. Even though there was a typo, Dify and Notion displayed a successful connection, which delayed the resolution of the problem. In reality, the SECRET was incorrect, so the connection was not actually successful. Please double-check for any typos.

Thanks for the input, but ours are different. Ours are incomplete sync. I have like 100 subpages in a each database page, but only 10 are shown.

**Comment by duylddev** [comment]
same issue
always show 0 page permission

![Image](https://github.com/user-attachments/assets/627ba402-1989-47c8-9b94-5026e91d5bea)

**Comment by limuyuan** [comment]
> After working through the issue, we need to manually share each page with the integration and click "Sync" again. It's Integration permissions section of this official document - https://developers.notion.com/docs/authorization#integration-permissions
> 
> > Before an integration can interact with your Notion workspace page(s), the page must be manually shared with the integration. To share a page with an integration, visit the page in your Notion workspace, click the ••• menu at the top right of a page, scroll down to Add connections, and use the search bar to find and select the integration from the dropdown list.
> 
> [@Tendo33](https://github.com/Tendo33) , [@lucaseatp](https://github.com/lucaseatp) , [@chriswhite5918](https://github.com/chriswhite5918)

Thank you! You solved my issue. I didn't expect such operations to be done in Notion... Big thumbs up 👍

**Comment by limuyuan** [comment]
> same issue always show 0 page permission
> 
> ![Image](https://github.com/user-attachments/assets/627ba402-1989-47c8-9b94-5026e91d5bea)

Did you try the solution provided by [thuanha-groove](https://github.com/thuanha-groove)?
