### ISSUE TITLE
The dataset is being used by some apps. Please remove the dataset from the apps before deleting it.

### ISSUE THREAD

**Issue by Liupuzhuo** [langgenius/dify#5907]
### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Maybe someone can help me this issue?

When I delete the knowledge base, dify gets an error: The dataset is being used by some apps. Please remove the dataset from the apps before deleting it.

I have cleared all associations for this dataset and delete all data in it.

And I have restart docker, it was useless....

### ✔️ Expected Behavior

I want to delete the knowledge dataset

**Comment by crazywoola** [comment]
See image below
<img width="1149" alt="image" src="https://github.com/langgenius/dify/assets/100913391/eaf06637-12fb-4234-833c-91ebd4c70368">

**Comment by Liupuzhuo** [comment]
> 见下图 <img alt="image" width="1149" src="https://private-user-images.githubusercontent.com/100913391/345297220-eaf06637-12fb-4234-833c-91ebd4c70368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODY0ODAsIm5iZiI6MTcxOTk4NjE4MCwicGF0aCI6Ii8xMDA5MTMzOTEvMzQ1Mjk3MjIwLWVhZjA2NjM3LTEyZmItNDIzNC04MzNjLTkxZWJkNGM3MDM2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNTU2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzdlYzRhZmQ0MDM4NGE3YWIzMzM5NDJlZTI3ZmM5NGJkOWNmZDYyMzA0MTU5OTc3ZTVkZjI5MWJmZTAwZjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MHCwvYvXc21XXbpCFFLs-vB-qvXamDwzQ9gBKlopRms">

![image](https://github.com/langgenius/dify/assets/112631106/d00ace33-748c-4641-9c9e-ce6a13d5de9b)
seems like it was cleared all associations

**Comment by 617450941** [comment]
问题依然存在 无任何关联应用 0.6.12
