### ISSUE TITLE
Langfuse is configured to use only https and not http

### ISSUE THREAD

**Issue by DavinciEvans** [langgenius/dify#5909]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am using langfuse with self-host. when I setup Langfuse configuration, I filled all the configuration items correctly. But when I submit it, the top right corner prompts a popup box: `1 validation error for LangfuseConfig host Value error, host must start with https:// [type=value_error, input_value='http://4*. **. **. *5:3000', input_type=str] For further information visit https://errors.pydantic.dev/2.7/v/value_error`

It seems to be a service that must require https. Is it a case of not supporting http?

**Comment by DavinciEvans** [comment]
Can't I change it to support http openings because I'm testing it locally for development?

**Comment by crazywoola** [comment]
Duplicated we already fixed in #5846
