### ISSUE TITLE
xlsx can recognize the same amount of data exported from the knowledge base, but csv cannot

### ISSUE THREAD

**Issue by JayHsu5** [langgenius/dify#5910]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a knowledge base
2. Csv file import
3. Copy csv data to xlsx

### ✔️ Expected Behavior

Both csv and xlsx files can count characters

### ❌ Actual Behavior

csv cannot

**Comment by JohnJyong** [comment]
pls attach some screenshot about this issue @JayHsu5

**Comment by JayHsu5** [comment]
![image](https://github.com/langgenius/dify/assets/35866219/4d6fa092-0de9-4449-80c2-369b538a9a9a)

**Comment by JohnJyong** [comment]
If it is convenient, you can upload the desensitized version of your csv file.
because form your screenshot and desc ， I can't figure out what the problem is ， thanks
@JayHsu5
