### ISSUE TITLE
the interface very slow

### ISSUE THREAD

**Issue by cjdxhjj** [langgenius/dify#5911]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

refresh the web ui

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/5616997/c786d8e2-611c-4b45-ac29-8277b3c4eb66)

**Comment by crazywoola** [comment]
If you are using `yarn dev` to start the application, yes, it will be slow, because it's development mode.
