### ISSUE TITLE
Incorrect validation rules for TENCENT_VECTOR_DB_REPLICAS

### ISSUE THREAD

**Issue by jianglin1008** [langgenius/dify#5912]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![图片](https://github.com/langgenius/dify/assets/4667567/d52eee14-83d4-4203-a726-42a90ca6aeb4)

### ✔️ Expected Behavior

Env `TENCENT_VECTOR_DB_REPLICAS` can be set to 0

### ❌ Actual Behavior

TENCENT_VECTOR_DB_REPLICAS must gt 0

**Comment by crazywoola** [comment]
Can you open a pr to fix this?

**Comment by jianglin1008** [comment]
Certainly! I'll create a pull request to fix this issue. I'll work on it and submit the PR as soon as possible.
