### ISSUE TITLE
Bing search tool always add entities to responseFilter

### ISSUE THREAD

**Issue by qkxie** [langgenius/dify#5922]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use Bing search tool

### ✔️ Expected Behavior

answer search result.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/134578340/4ccc0dc8-a338-4875-aca9-1587ab6e846f)
![image](https://github.com/langgenius/dify/assets/134578340/e5f5e239-1c1a-42bb-99ce-28a52840a2b4)

In Bing search tool, I only choose webpage to search, but the api request always add entities to responseFilter, this make my api call error. Because my Bing API subscribtion doesn't include entities search, so responseFilter should not include entities

**Comment by qkxie** [comment]
I have already make sure that enable_entities ui false

![image](https://github.com/langgenius/dify/assets/134578340/c2bd854d-b25b-4a17-9507-2d42aff4eec0)

**Comment by qkxie** [comment]
Now I have to fix the code of dify/api/core/tools/provider/builtin/bing/tools/tools/bing_web_search.py

**Comment by keita69** [comment]
In 0.6.12-fix, it is expected to work properly only if the FEATURES of the [Bing Search API v7 Pricing Details](https://www.microsoft.com/en-us/bing/apis/pricing) include "Bing Entity Search".

In other words, it is expected to work properly if the INSTANCE of the Bing Search API v7 Pricing Details is as follows:
- Free
- S1
- S7
