### ISSUE TITLE
Error response from daemon and 401 Unauthorized

### ISSUE THREAD

**Issue by mouse33333** [langgenius/dify#5924]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/4304174/28747c58-b311-42db-bdba-2b64730bc52a)
I follow the step on official website:
1. cd dify/docker
2. cp .env.example .env
3. docker compose up -d

However, when trying to load the docker compose, it always occured "401 unauthorized" error. 

I work on Windows 11, Docker Desktop. 

### ✔️ Expected Behavior

update the compose of the project

### ❌ Actual Behavior

Error response from daemon: failed to resolve reference "docker.io/library/redis:6-alpine": failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Alibrary%2Fredis%3Apull&service=registry.docker.io: 401 Unauthorized

**Comment by crazywoola** [comment]
This is not related to our code base, instead it's a problem of basic docker usage.

**Comment by mouse33333** [comment]
Thank you! I finlally found it's the network problem that failed updating the compose.
