### ISSUE TITLE
missing argument retriever_resources in api response

### ISSUE THREAD

**Issue by zyc130130** [langgenius/dify#5927]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The argument retriever_resources is not in api's response

**Comment by crazywoola** [comment]
Which api are you talking about? Please provide a detailed example in description.

**Comment by crazywoola** [comment]
Have you turn the feature flag (retriever_resources) on?

**Comment by zyc130130** [comment]
> retriever_resources

yes，the flag is FALSE，turn on the flag， it work

**Comment by zhukefucn** [comment]
> Have you turn the feature flag (retriever_resources) on?

which config file or how to change the feature flag ？

**Comment by zhukefucn** [comment]
> > retriever_resources
> 
> yes，the flag is FALSE，turn on the flag， it work
which config file or how to change the feature flag ？

**Comment by zhukefucn** [comment]
which config file or how to change the feature flag ？

**Comment by yzztin** [comment]
> which config file or how to change the feature flag ？

hi, you can have a try here:
![image](https://github.com/user-attachments/assets/2d6b17d5-e4d6-4464-a7d1-4a4362ced489)
