### ISSUE TITLE
API Server 404

### ISSUE THREAD

**Issue by fevolq** [langgenius/dify#5932]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

My application has been created and published, but a 404 error occurs when calling the API. I deployed it through docker, and the exposed ports are 180 and 1443 (EXPOSE_NGINX_PORT is set in .env). I tried to set NGINX_PORT to 80 and 180, but both returned 404. If the host's NGINX (port 80) is turned off, an exception occurs directly. It was not until I set both NGINX_PORT and EXPOSE_NGINX_PORT to port 80 that it succeeded, but this will occupy port 80 of the host.

![image](https://github.com/langgenius/dify/assets/49370176/718f80ea-c056-4821-ac57-c0c3799df8d3)
![image](https://github.com/langgenius/dify/assets/49370176/733f1836-68af-4e11-962f-c11d7e5f2247)

**Comment by crazywoola** [comment]
Make sure you have set those variables correctly. 
```
ONSOLE_WEB_URL: ${CONSOLE_WEB_URL:-}
CONSOLE_API_URL: ${CONSOLE_API_URL:-}
SERVICE_API_URL: ${SERVICE_API_URL:-}
APP_WEB_URL: ${APP_WEB_URL:-}
```

**Comment by fevolq** [comment]
I have not changed these variables in .env file. Now I am accessing through ip:port, so should these variables be set to http://0.0.0.0 or http://127.0.0.1, or something else?
