### ISSUE TITLE
Cuold not delete empty knowledge

### ISSUE THREAD

**Issue by nhha1602** [langgenius/dify#5935]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I tried to delete an empty knowledge but not OK. I check the log dify-api & on the screen, and get below information:

On dify-api:

`2024-07-03 10:35:41,330.330 INFO [Thread-606 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [03/Jul/2024 10:35:41] "GET /console/api/datasets/**26b17ea7-e3ca-4bbe-98c2-a915863d11ca**/use-check HTTP/1.1" 404 -
`
I checked on DB, the id: **26b17ea7-e3ca-4bbe-98c2-a915863d11ca** still exist on datasets table.

On the screen of dify GUI:

![image](https://github.com/langgenius/dify/assets/48270582/7b5d5dc7-93d8-4f46-87b4-d2c9ee8a17f1)

There is no document in this knowledge:

![image](https://github.com/langgenius/dify/assets/48270582/6c77a80d-ebd7-403a-9047-09f1b4cc9159)

Please help to check it.

### ✔️ Expected Behavior

Delete an empty knowledge successfully

### ❌ Actual Behavior

Cuold not delete an empty knowledge

**Comment by crazywoola** [comment]
Unfortunately I can't reproduce the issue in the Cloud version.

**Comment by nhha1602** [comment]
> Unfortunately I can't reproduce the issue in the Cloud version.
> 
> ```
> /console/api/datasets/**26b17ea7-e3ca-4bbe-98c2-a915863d11ca**/use-check
> ```
> 
> This one looks strange to me, because there are two '*' in front of the id and in the end of it.

Hi, I set it as BOLD characters, so it has "**".

**Comment by nhha1602** [comment]
> * **Check for Active Dependencies**: Ensure that there are no active dependencies or references to this knowledge entry that might prevent its deletion. The deletion process checks for dependencies and will not proceed if any are found [[1]](https://github.com/langgenius/dify/blob/main/web/i18n/en-US/dataset.ts).
> * **API Endpoint Validation**: Confirm that the `use-check` endpoint is correctly implemented and accessible. The 404 error suggests that the endpoint might not be correctly set up or the request URL might be incorrect.
> * **Fronten**

Hi,

Let me check your comments and updates.

**Comment by nhha1602** [comment]
Hi,

Base on the log below in dify-api, then:
- The URL is correct
- it just happened with use-check - I confirmed that I already delete the pipeline that use this knowledge


**2024-07-04 01:14:19,488.488 INFO [Thread-615 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [04/Jul/2024 01:14:19] "GET /console/api/datasets/26b17ea7-e3ca-4bbe-98c2-a915863d11ca/error-docs HTTP/1.1" 200 -
2024-07-04 01:14:19,497.497 INFO [Thread-617 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [04/Jul/2024 01:14:19] "GET /console/api/datasets/26b17ea7-e3ca-4bbe-98c2-a915863d11ca/related-apps HTTP/1.1" 200 -
2024-07-04 01:14:19,503.503 INFO [Thread-616 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [04/Jul/2024 01:14:19] "GET /console/api/datasets/26b17ea7-e3ca-4bbe-98c2-a915863d11ca/documents?page=1&limit=15&keyword=&fetch= HTTP/1.1" 200 -
2024-07-04 01:14:19,532.532 INFO [Thread-614 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [04/Jul/2024 01:14:19] "GET /console/api/datasets/26b17ea7-e3ca-4bbe-98c2-a915863d11ca HTTP/1.1" 200 -
2024-07-04 01:15:24,376.376 INFO [Thread-618 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [04/Jul/2024 01:15:24] "GET /console/api/tags?type=knowledge HTTP/1.1" 200 -
2024-07-04 01:15:24,428.428 INFO [Thread-619 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [04/Jul/2024 01:15:24] "GET /console/api/datasets?page=1&limit=30 HTTP/1.1" 200 -
2024-07-04 01:15:26,424.424 INFO [Thread-620 (process_request_thread)] [_internal.py:97] - 127.0.0.6 - - [04/Jul/2024 01:15:26] "GET /console/api/datasets/26b17ea7-e3ca-4bbe-98c2-a915863d11ca/use-check HTTP/1.1" 404 -**

**Comment by nhha1602** [comment]
Hi,

I just found that, this knowledge relates to the logs of hitting test and app testing in Retrieval Testing. If that, how to delete these logs on the GUI ?

**Comment by nhha1602** [comment]
I tried to create a new knowledge whit following senario:
- a new knowledge with empty document, then I delete it. it still failed with use-check - 404 error
- a new knowledge with a document, dont test anything, delete the document and then delete knowledge. it still failed with use-check - 404 error

**Comment by nhha1602** [comment]
Hi,

The issue is caused by there is no API: 
api.add_resource(DatasetUseCheckApi, '/datasets/<uuid:dataset_id>/use-check') in /api/controllers/console/datasets/datasets.py of dify-api 0.6.12.
