### ISSUE TITLE
The access APIs for multiple text generation applications are same

### ISSUE THREAD

**Issue by zhoux72** [langgenius/dify#5936]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Multiple text generation applications have been developed using Dify, and each application's access API is"https://base_url/v1/completion-messages",How can I determine which application I actually want to call when calling?

### ✔️ Expected Behavior

Each application has a separate access API. For example, the access API for application A is "https://base_url/v1/completion-messages/a". The access API for application B is "https://base_url/v1/completion-messages/b". This can confirm which application is being called

### ❌ Actual Behavior

All text generation applications access APIs are "https://base_url/v1/completion-messages"

**Comment by crazywoola** [comment]
We use api keys see https://docs.dify.ai/guides/application-publishing/developing-with-apis#text-generation-application
