### ISSUE TITLE
Cannot Link Node to start in iteration node  

### ISSUE THREAD

**Issue by WeepsDanky** [langgenius/dify#5939]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/50621638/f49f26d2-2eca-4e43-a7e0-77fe981df5d2)
1. Add a iteraction node and add a few llm nodes inside iteraction 
2. disconnect the first one so it would look like the situation in the image
3. ideally you should be able to connect it back but you cannot 

### ✔️ Expected Behavior

The node within iteraction node should be able to connect back to the start of iteraction node after disconnected. 

### ❌ Actual Behavior

Once disconnect it cannot connect back to the start
![image](https://github.com/langgenius/dify/assets/50621638/781865ed-421d-4f9b-961b-735c1ae400cc)

**Comment by JokerQyou** [comment]
Why was this closed as not planned? This is still an issue in the latest version, and clearly a design problem. Once the first node in an Iteration block is deleted, you cannot connect any remaining nodes back to the start of Iteration. This basically makes Iteration un-editable.

**Comment by JokerQyou** [comment]
Just tested this and it's fixed (at least in `0.10.2`, probably released in an earlier version).
