### ISSUE TITLE
LLM model is not available

### ISSUE THREAD

**Issue by buddypia** [langgenius/dify#5940]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Generate a chatbot
2. Select gpt-4o model
3. say 'hi'

Docker Error
<img width="1035" alt="スクリーンショット 2024-07-03 22 10 15" src="https://github.com/langgenius/dify/assets/743904/6d1975e2-d50f-42a4-ac9a-20130630c61d">

The API key is correct, but it has changed for some reason.
<img width="471" alt="スクリーンショット 2024-07-03 22 10 35" src="https://github.com/langgenius/dify/assets/743904/bc10f90a-35ba-4a3e-aba9-8483186fa8e0">

### ✔️ Expected Behavior

Response from OpenAI's gpt-4o model

### ❌ Actual Behavior

no response

**Comment by greycodee** [comment]
Please check if your openai api key is correct.

**Comment by buddypia** [comment]
It was fixed when I updated it.
