### ISSUE TITLE
docker安装完成后 localhost/install 账号密码是什么？

### ISSUE THREAD

**Issue by DemonDamon** [langgenius/dify#5941]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.2-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I set my .env as follow

```
# Server Edition
EDITION=SELF_HOSTED

# Your App secret key will be used for securely signing the session cookie
# Make sure you are changing this key for your deployment with a strong key.
# You can generate a strong key using `openssl rand -base64 42`.
# Alternatively you can set it with `SECRET_KEY` environment variable.
SECRET_KEY=<your_value>

# Console API base URL
CONSOLE_API_URL=http://127.0.0.1:5001
CONSOLE_WEB_URL=http://127.0.0.1:3000

# Service API base URL
SERVICE_API_URL=http://127.0.0.1:5001

# Web APP base URL
APP_WEB_URL=http://127.0.0.1:3000

# Files URL
FILES_URL=http://127.0.0.1:5001

... （no change）
```

and i turn on the port in docker compose

```
  x-shared-env: &shared-api-worker-env
  LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
  DEBUG: ${DEBUG:-false}
  FLASK_DEBUG: ${FLASK_DEBUG:-false}
  SECRET_KEY: ${SECRET_KEY:-sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U}
  INIT_PASSWORD: ${INIT_PASSWORD:-}
  CONSOLE_WEB_URL: ${CONSOLE_WEB_URL:-http://127.0.0.1:3000}
  CONSOLE_API_URL: ${CONSOLE_API_URL:-http://127.0.0.1:5001}
  SERVICE_API_URL: ${SERVICE_API_URL:-http://127.0.0.1:3000}
  APP_WEB_URL: ${APP_WEB_URL:-http://127.0.0.1:3000}
  ... (no change)

services:
  # API service
  api:
    ... （no change）
    ports:
      - "5001:5001"

  web:
    image: langgenius/dify-web:0.6.12-fix1
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL:-http://127.0.0.1:5001}
      APP_API_URL: ${APP_API_URL:-http://127.0.0.1:5001}
      SENTRY_DSN: ${WEB_SENTRY_DSN:-}
      ports:
         - "3000:3000"

  db:
     ... （no change）
     ports:
       - "5432:5432"

  redis:
     ... （no change）
     ports:
        - "6379:6379"

  weaviate:
     ... （no change）
    ports:
     - "8080:8080"

  qdrant:
     ... （no change）
    ports:
     - "6333:6333"

... （no change）
```

### ✔️ Expected Behavior

register first or provide an admin accout

### ❌ Actual Behavior

when compose up whole service, i request localhost/install will route to http://localhost:3000/signin

and i could not register first

**Comment by DemonDamon** [comment]
now it stills here
![image](https://github.com/langgenius/dify/assets/20499644/3e5d9313-5087-4fb6-bf4f-252edfcf3094)
and the log stills here
![image](https://github.com/langgenius/dify/assets/20499644/97e20fd8-36eb-4818-ab89-93a43519dd3f)
what should i do?

**Comment by DemonDamon** [comment]
![image](https://github.com/langgenius/dify/assets/20499644/b92a2db5-9385-4cdb-9dc3-e9fe82a3001e)
![image](https://github.com/langgenius/dify/assets/20499644/533a8473-8a6b-432d-ad41-d8cd543c5a97)
![image](https://github.com/langgenius/dify/assets/20499644/7ff63a8e-b016-47cd-8960-1d15e3de6f2b)
![image](https://github.com/langgenius/dify/assets/20499644/c741cffc-780a-403a-96ef-9debb87fdb63)
![image](https://github.com/langgenius/dify/assets/20499644/0fadd339-a098-4def-b728-25e738862589)
![image](https://github.com/langgenius/dify/assets/20499644/16517cae-05a2-4641-8ace-de1248fa59c8)
![image](https://github.com/langgenius/dify/assets/20499644/34c82800-dc53-4bdc-8ec6-9a1cc37179cd)
![image](https://github.com/langgenius/dify/assets/20499644/4325af53-6a09-4eed-b61a-907bc2094625)
![image](https://github.com/langgenius/dify/assets/20499644/de799e77-1d25-429e-841a-32fbacf234a7)


please take a look, i still couldn't locate the problem

**Comment by DemonDamon** [comment]
by the way, i deploy on win11

**Comment by DemonDamon** [comment]
please dont repeat answer, take a look carefully

**Comment by crazywoola** [comment]
请使用英文提交 Issue。

```
# Console API base URL
CONSOLE_API_URL=http://127.0.0.1:5001
CONSOLE_WEB_URL=http://127.0.0.1:3000

# Service API base URL
SERVICE_API_URL=http://127.0.0.1:5001

# Web APP base URL
APP_WEB_URL=http://127.0.0.1:3000
```

如果使用公网 ip 这里也应该填写公网 ip 地址

**Comment by DemonDamon** [comment]
it is not working, how to solve?

**Comment by DemonDamon** [comment]
我现在重新回滚到最初，啥也没设置，点开http://localhost，直接调到signin，然后有这么一串
![image](https://github.com/langgenius/dify/assets/20499644/99fa6187-b494-4ac9-a1e7-29e9a4004506)

或者哪里设置admin邮箱吗

**Comment by DemonDamon** [comment]
> 请使用英文提交 Issue。
> 
> ```
> # Console API base URL
> CONSOLE_API_URL=http://127.0.0.1:5001
> CONSOLE_WEB_URL=http://127.0.0.1:3000
> 
> # Service API base URL
> SERVICE_API_URL=http://127.0.0.1:5001
> 
> # Web APP base URL
> APP_WEB_URL=http://127.0.0.1:3000
> ```
> 
> 如果使用公网 ip 这里也应该填写公网 ip 地址

大佬，help！

**Comment by mouse33333** [comment]
你好啊，我之前遇到过401和502等localhost/install的错误，我也全部都清空了重新安装了一下。后来在官网找到了一个类似的回答，在这个页面搜索502，不知道是不是能帮助你：https://docs.dify.ai/v/zh-hans/learn-more/faq/install-faq

**Comment by DemonDamon** [comment]
> 你好啊，我之前遇到过401和502等localhost/install的错误，我也全部都清空了重新安装了一下。后来在官网找到了一个类似的回答，在这个页面搜索502，不知道是不是能帮助你：https://docs.dify.ai/v/zh-hans/learn-more/faq/install-faq
> 
> 反正就是在.env里啥变量都不用改，直接访问即可。但是有个ngix的权限问题，需要修改一下IP地址。之后就解决了。

我能打开localhost/install， 但是一直在打转，
![image](https://github.com/langgenius/dify/assets/20499644/d051aea0-85c4-4a4c-81db-181b5c76d987)

然后如果这时候点开localhost/signin，点击跳转 `[设置管理员账户](http://localhost/install)` 也会闪跳回 localhost/signin
![image](https://github.com/langgenius/dify/assets/20499644/da4337fb-ef6d-4906-98d2-098058f6219d)


版本是0.6.12-fix1

**Comment by SmartComprasOnLine** [comment]
I am facing the same issue!

**Comment by dxtbrave** [comment]
这是因为已经设置了管理员账号和密码吧

**Comment by faye25tom** [comment]
> 这是因为已经设置了管理员账号和密码吧

但是原来的管理员账号和密码登录的时候没有反应。版本是从v0.6.8直接升级到v0.7.1。不知道是.env的环境变量设置的不对还是哪里造成的。

**Comment by 1193700079** [comment]
> 你好啊，我之前遇到过401和502等localhost/install的错误，我也全部都清空了重新安装了一下。后来在官网找到了一个类似的回答，在这个页面搜索502，不知道是不是能帮助你：https://docs.dify.ai/v/zh-hans/learn-more/faq/install-faq
> 
> 反正就是在.env里啥变量都不用改，直接访问即可。但是有个ngix的权限问题，需要修改一下IP地址。之后就解决了。

Hello, according to this tutorial, I have set the following command:

```
docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }}: {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
```

The output I got is:

```
docker-nginx-1: 172.30.0.7
/docker-api-1: 172.30.0.6172.31.0.4
/docker-worker-1: 172.30.0.5172.31.0.5
/docker-sandbox-1: 172.31.0.2
/docker-redis-1:
/docker-web-1: 172.30.0.4
/docker-weaviate-1: 172.30.0.3
/docker-ssrf_proxy-1: 172.30.0.2172.31.0.3
/docker-db-1:
```

For `/docker-api-1`, I have two IP addresses. How should I resolve this? `172.30.0.6172.31.0.4`

I have set the following in `nginx/conf.d`:

```
Please do not directly edit this file. Instead, modify the .env variables related to NGINX configuration.

server {
    listen 80;
    server_name _;

    location /console/api {
      proxy_pass http://172.30.0.6:5001;
      include proxy.conf;
    }

    location /api {
      proxy_pass http://172.30.0.6:5001;
      include proxy.conf;
    }

    location /v1 {
      proxy_pass http://172.30.0.6:5001;
      include proxy.conf;
    }

    location /files {
      proxy_pass http://172.30.0.6:5001;
      include proxy.conf;
    }

    location / {
      proxy_pass http://172.30.0.4:3000;
      include proxy.conf;
    }

    # placeholder for acme challenge location

    # placeholder for https config defined in https.conf.template
}
```

---

There is still a 502 error.

---

**Comment by superlbr** [comment]
对于忘记管理账户的，可以navicat进postgres查看
