### ISSUE TITLE
When using the Chat Assistant, the model uses openai, which works properly, and the conversation message is empty

### ISSUE THREAD

**Issue by shutter-cp** [langgenius/dify#5949]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Starting mode `docker compose up -d ` There is no other operation

<img width="1744" alt="image" src="https://github.com/langgenius/dify/assets/37921589/2df37efe-c16d-46b3-9b45-b9c0a63458fb">

```text
/api/apps/74667fdb-6d82-48aa-8ec0-86cfa4c2cc75/chat-messages
data: {"event": "message", "conversation_id": "0abe9a6d-5066-42f6-918c-ed2bf3fd4439", "message_id": "23bed9f7-e9d9-4296-bd14-e4a1e58032cc", "created_at": 1720061592, "task_id": "f3c50e89-1533-4e82-a8a3-46d99108a5a2", "id": "23bed9f7-e9d9-4296-bd14-e4a1e58032cc", "answer": ""}

data: {"event": "message_end", "conversation_id": "0abe9a6d-5066-42f6-918c-ed2bf3fd4439", "message_id": "23bed9f7-e9d9-4296-bd14-e4a1e58032cc", "created_at": 1720061592, "task_id": "f3c50e89-1533-4e82-a8a3-46d99108a5a2", "id": "23bed9f7-e9d9-4296-bd14-e4a1e58032cc", "metadata": {"usage": {"prompt_tokens": 8, "prompt_unit_price": "5.00", "prompt_price_unit": "0.000001", "prompt_price": "0.0000400", "completion_tokens": 18, "completion_unit_price": "15.00", "completion_price_unit": "0.000001", "completion_price": "0.0002700", "total_tokens": 26, "total_price": "0.0003100", "currency": "USD", "latency": 3.0238079169939738}}}

```

```json
/console/api/apps/74667fdb-6d82-48aa-8ec0-86cfa4c2cc75/chat-messages?conversation_id=0abe9a6d-5066-42f6-918c-ed2bf3fd4439

{
    "limit": 20,
    "has_more": false,
    "data": [
        {
            "id": "23bed9f7-e9d9-4296-bd14-e4a1e58032cc",
            "conversation_id": "0abe9a6d-5066-42f6-918c-ed2bf3fd4439",
            "inputs": {},
            "query": "\u4f60\u597d",
            "message": [
                {
                    "role": "user",
                    "text": "\u4f60\u597d",
                    "files": []
                }
            ],
            "message_tokens": 8,
            "answer": "",
            "answer_tokens": 18,
            "provider_response_latency": 3.0075898240029346,
            "from_source": "console",
            "from_end_user_id": null,
            "from_account_id": "c8fa35b7-1e95-4177-bd24-fff4240a6388",
            "feedbacks": [],
            "workflow_run_id": null,
            "annotation": null,
            "annotation_hit_history": null,
            "created_at": 1720061592,
            "agent_thoughts": [],
            "message_files": [],
            "metadata": {},
            "status": "normal",
            "error": null
        }
    ]
}
```
日志
<img width="1569" alt="image" src="https://github.com/langgenius/dify/assets/37921589/7999e09d-3fa3-4cc6-9aa2-54efd084f74c">

**Comment by shutter-cp** [comment]
There are no error messages，But the dialog is empty

**Comment by LiuHaodongdong** [comment]
I got the same result as yours. The dialog is empty. But when I use ApiFox to test the OpenAI service, I can get a correct response. Have you solved this problem?

**Comment by shutter-cp** [comment]
> 我得到了和你的一样的结果。对话框是空的。但当我使用ApiFox测试OpenAI服务时，我可以得到正确的响应。你解决这个问题了吗？

使用OpenAI-API-compatible 手动配置openai服务能用

**Comment by LiuHaodongdong** [comment]
我通过设置流模式返回结果的分隔符为* /n， 去掉一个/n解决了这个问题

**Comment by luxinfeng** [comment]
> 我通过设置流模式返回结果的分隔符为* /n， 去掉一个/n解决了这个问题

请问是在什么地方设置的啊？修改了源代码吗？

**Comment by hwb96** [comment]
> > 我通过设置流模式返回结果的分隔符为* /n， 去掉一个/n解决了这个问题
> 
> 请问是在什么地方设置的啊？修改了源代码吗？

![image](https://github.com/user-attachments/assets/885e96b3-4ac3-49eb-b216-9e399d535751)
