### ISSUE TITLE
Provide some system variables such as Current_Date, Current_time

### ISSUE THREAD

**Issue by zhangever** [langgenius/dify#5951]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

As most of the LLM models don't know the time of the real world. When users ask some questions related to the time, such as   what's the weather like tomorrow? LLMs likely will report a wrong date.
So if some system variables are provided, and could be used as  context variables within the  prompt of the llms, it could help.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please use this tool to get time and date.

<img width="449" alt="image" src="https://github.com/langgenius/dify/assets/100913391/47ab9464-5966-43f4-b890-a53f9ef65e52">

**Comment by zhangever** [comment]
> Please use this tool to get time and date.
> 
> <img alt="image" width="449" src="https://private-user-images.githubusercontent.com/100913391/345697255-47ab9464-5966-43f4-b890-a53f9ef65e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODUyNTcsIm5iZiI6MTcyMDA4NDk1NywicGF0aCI6Ii8xMDA5MTMzOTEvMzQ1Njk3MjU1LTQ3YWI5NDY0LTU5NjYtNDNmNC1iODkwLWE1M2Y5ZWY2NWU1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwOTIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDZkMjJlMzkzOWYyYTMwOTg4MTNkNWM5NWU3YmY1YWI1YjdlZTZlZjE1YjMyNDI1NjVhNTYwNWI5NjAxNDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MUjGHq2ntD4Tx-yubLdw8eukbR3FBd458MagxF3vfMI">

It's not so native, and still can't put the current time to the end of the prompt.
