### ISSUE TITLE
the segmentation results are empty

### ISSUE THREAD

**Issue by silence-pan84** [langgenius/dify#5952]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

The Nomic-embed-text embedding model uses the Q&A segmentation pattern, and the segmentation results are empty
![image](https://github.com/langgenius/dify/assets/174668054/58c27564-6c6b-469a-b6a0-0970c70a1274)

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5764 see this for the follow-up.
