### ISSUE TITLE
The format returned by the get conversation log API is not fixed when status is error

### ISSUE THREAD

**Issue by chenyhd** [langgenius/dify#5953]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Enter bot app
2. Go to logs&Ann. from the side bar
3. check the conversations
4. I found that when some steps execute failed, the fields will return empty string instead of array

API: 
GET https://{domain}/console/api/apps/{appId}/chat-messages?conversation_id={conversationId}&limit=10

Error response:
```
response.data[x] ->
{
    ....
    "message": "", // String
    "status": "error",
    "error": "[openai] Error: peer closed connection without sending complete message body (incomplete chunked read)"
}
```

Normal response:
```
response.data[x] ->
{
    ...
    "message": [ // Array
        {
            "role": "system",
            "text": "xxxxx",
            "files": []
        },
        {
            "role": "user",
            "text": "yyyyy",
            "files": []
        }
    ],

    "status": "normal",
    "error": null
},

```

### ✔️ Expected Behavior

Hi Dify team, Thank you for creating this amazing app! It's fantastic. I'm currently analyzing the logs and noticed some unusual API responses.

The message format should remain consistent regardless of whether the status is normal or an error.

By default, the message could return an empty array like `message: []` instead of `message:""`.

### ❌ Actual Behavior

The message field returns in a different format when something execute failed

**Comment by crazywoola** [comment]
I think you could do a check here.

```
"status": "normal",
"error": null
```

```
if result.error === null
  do something
else
  do nothing
```

**Comment by chenyhd** [comment]
Hi @crazywoola ,

Maybe different json libs have different deserialization  behaviors, I use Java Jackson lib , it will deserialize entire json string to object, instead of check each individual fields

I will try to find another way to handle this situation
