### ISSUE TITLE
Applications of the agent type couldn't stream return results when xinference was used as the model provider

### ISSUE THREAD

**Issue by liuzhenghua** [langgenius/dify#5954]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Create an application with the type "agent."
2. Set the model to be provided by xinference.
3. Engage in a conversation using the application.

### ✔️ Expected Behavior

![期待](https://github.com/langgenius/dify/assets/11787325/84c8592b-4f6d-461e-ae7b-6c3da9b686f1)

### ❌ Actual Behavior

![实际](https://github.com/langgenius/dify/assets/11787325/e54d5a43-59ff-4ae5-9394-7afdd6f9a61b)

**Comment by EnzoLiang** [comment]
i test the llm by xinference ,it can stream return results

**Comment by liuzhenghua** [comment]
> i test the llm by xinference ,it can stream return results

Did you create an app of the agent type?
