### ISSUE TITLE
The URL of the API generated by deploying multiple workflows is the same

### ISSUE THREAD

**Issue by karterotte** [langgenius/dify#5957]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I deployed 2 workflows like below,but they have same url
![image](https://github.com/langgenius/dify/assets/9114743/f0e56417-1139-465f-a199-3d8720a81573)

![image](https://github.com/langgenius/dify/assets/9114743/49318569-4bab-4dcc-be28-419ee38f7ceb)

If I want to call through the http interface, how to distinguish them？

### ✔️ Expected Behavior

They should have different url,and I can set or rename them.

### ❌ Actual Behavior

They have the same url, like "http://localhost/v1"

**Comment by Sakura4036** [comment]
The base url of all workflow and tools api are the same, dify use `API-Key`  for authentication and workflow api. 

![image](https://github.com/langgenius/dify/assets/42060616/55c4fe11-d47c-43d8-94ca-22202d8090a7)

**Comment by karterotte** [comment]
@Sakura4036 This way of using it feels weird. If I show that I have several workflow APIs can be called, it will probably all be the same url (I can't show the apikey)

**Comment by crazywoola** [comment]
Duplicated, we use api to distinguish the workflows.
