### ISSUE TITLE
I've been using it for a while, and it's a white screen.,What's the problem?No matter how you refresh it, you can't get in.

### ISSUE THREAD

**Issue by robin536180** [langgenius/dify#5959]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I've been using it for a while, and it's a white screen.,What's the problem?No matter how you refresh it, you can't get in.

### ✔️ Expected Behavior

I just want to get in successfully

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/8565176/06edbbf4-65c7-48cb-9141-a7b7c6967fe3)

**Comment by Sakura4036** [comment]
Most likely it's a version mismatch. i meet the same problem when i pull some commit beyond the latest release version from main branch.
You can try upgrading to the latest version `0.6.12-fix1` or going back to version `0.6.11`.

**Comment by robin536180** [comment]
My bad, I have write the wrong version, the version is 0.6.11 actually

**Comment by Sakura4036** [comment]
did you try restarting all difyrelated dockers?

**Comment by crazywoola** [comment]
Please provide more details regarding this issue. The provided information seems not helpful for us to resolve this issue.
What's page's link?
For steps to reproduce, please provide detailed steps instead of pasting an image.

**Comment by robin536180** [comment]
> did you try restarting all difyrelated dockers?

I am trying to update to 0.6.12.Restarting can resolve the problem, but it refresh too low when  I first visit, you known that.

**Comment by robin536180** [comment]
> Please provide more details regarding this issue. The provided information seems not helpful for us to resolve this issue.
> 
> What's page's link?
> 
> For steps to reproduce, please provide detailed steps instead of pasting an image.

All pages can not be visited.I guess the local cache or token expired caused the problem, because it can't refresh automatically.I clear all my seesion,cookie, local storage, and so on, I refresh the page can visit again.

**Comment by robin536180** [comment]
I have updated to 0.6.12 just now, but it still can not visit. I think the problem is still exists.
[
[dify_visit_record.zip](https://github.com/user-attachments/files/16096079/dify_visit_record.zip)
](url)

**Comment by robin536180** [comment]
I have record my operation, you can checkout now.
[https://dev-static.allpo.com.au/temp/dify_visit_failed.gif?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vZGV2LXN0YXRpYy5hbGxwby5jb20uYXUvdGVtcC9kaWZ5X3Zpc2l0X2ZhaWxlZC5naWYiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MjA2OTIyNzJ9fX1dfQ__&Signature=e4DiDmLQdwZ0S5w4Qs4sIfNnKWJIrUYZidfKbWc55e6bwJ-Zi6WueeEng4fH1Ex6UFcJX8onxDCviFXD9G1XhvIA0NQ0ITkBugk6H4e0JXj4NT4nMyte45LL-G83tw5vemZ7JhPMAPszAVxcqMf3VIJtZBGvVjmFFATizfMXIXvt4EtQFNfeeJK00nE571tOBI7vV2xfsDtxwwyuW2HJR5Q4kZhVAKFTIsmZnuHzmVP3scjp5S08WPShmCU3eXbsLOPjpNzSxnQqLxWhgydOHxABKkq-v61hkfRqLA67vtB-IGBHReFtZLqX~EODsm-sVgO7NiSYgkf-AHlQQ--Zrw__&Key-Pair-Id=K1YR7QWVR0BHQX](url)

**Comment by crazywoola** [comment]
Try to remove things in docker/volumns/db and restart the container again. @robin536180
