### ISSUE TITLE
邀请链接复制失效，没有复制成功

### ISSUE THREAD

**Issue by leochen-g** [langgenius/dify#596]
Dify version: Self Host

## Steps To Reproduce

1. 后台已经配置好地址，在添加成员后的邀请链接，点击复制，去粘贴的时候无效
2.
<img width="601" alt="image" src="https://github.com/langgenius/dify/assets/20028566/0c4fb4ff-cb5a-4cc3-8f7f-8ac7a089ed3d">

## The current behavior
现在是粘贴不成功的

**Comment by leochen-g** [comment]
补充环境：
chrome:
<img width="737" alt="image" src="https://github.com/langgenius/dify/assets/20028566/37fb89fc-8e60-4fb8-aa2c-5f710c7c9421">

mac:
<img width="255" alt="image" src="https://github.com/langgenius/dify/assets/20028566/7ed60979-db84-4bf7-9c69-bdddba8f1e9d">


部署版本：v0.3.10 docker-compose 部署

操作步骤：添加成员时

**Comment by yinhaixiang** [comment]
我这边也遇到了, "复制"按钮功能都没用的, 无论在哪个地方的"复制"
