### ISSUE TITLE
RAG Knowledge Base Search Requirement: Filtering Function Based on Document Name

### ISSUE THREAD

**Issue by sinosong** [langgenius/dify#5961]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When searching in the RAG knowledge base, it is hoped that filtering by document name will be supported. This way, when using API integration, the specified version of the document can be queried by passing in the document name.

知识库检索时，希望能支持根据文档名称进行筛选过滤。这样在使用API对接时，通过传入文档名称查询指定版本的文档

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by sinosong** [comment]
Retrieval can also be performed through metadata.

**Comment by GarciaLiu** [comment]
Why is such an important and commonly used feature listed as obsolete?

**Comment by sinosong** [comment]
> Why is such an important and commonly used feature listed as obsolete?

用langchain实现一个"dify-api"服务，以api工具的形式接入dify，基本上能满足使用场景了，可以按这种“外挂”的方式实现
