### ISSUE TITLE
How to make the workflow params of start node be optional

### ISSUE THREAD

**Issue by robin536180** [langgenius/dify#5963]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I create a workflow, I just want my own params, I don't want the default params sys.files and sys.user_id to be optional
![image](https://github.com/langgenius/dify/assets/8565176/78f97469-ef52-4723-9209-83fd26834e8b)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
No, you can not make sys.files and sys.user_id optional
