### ISSUE TITLE
Zhipu AI model name and model ID

### ISSUE THREAD

**Issue by silver0919** [langgenius/dify#5971]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I get the api-key of Zhipu AI about the modle named ChatGLM-12B，but I cant find the field of model name and model ID. Can you add the input field of model name and ID? So I can use my api-key in the web page. Thanks a lot!

### 2. Additional context or comments

1

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I am not seeing this model in their official documentations here. https://open.bigmodel.cn/dev/howuse/glm-4.
So if you are talking about Zhipu open source models, please use ChatGLM provider.
