### ISSUE TITLE
Files in the i18n directory are missing

### ISSUE THREAD

**Issue by silence-pan84** [langgenius/dify#5976]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/langgenius/dify/assets/174668054/27636241-391e-4ad8-a356-81857eea184a)
Docker deployed but missing file in container under i18n directory

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We're sorry, but we only keep some compiled content in our container service.
