### ISSUE TITLE
Please provide a docker-compose.yaml file tailored for users in China.

### ISSUE THREAD

**Issue by lepangdan** [langgenius/dify#5981]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

code/dify/docker$ docker compose up -d
[+] Running 1/24
 ⠙ worker 11 layers [⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                    285.2s
 ⠙ weaviate 1 layers [⠀]      0B/0B      Pulling                                             285.2s
 ⠙ sandbox 11 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                   285.2s
 ⠙ web 13 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                     285.2s
 ⠙ api 1 layers [⠀]      0B/0B      Pulling                                                  285.2s

error pulling image configuration: download failed after attempts=6: dial tcp 128.121.146.109:443: connect: connection refused

### ✔️ Expected Behavior

Everything is ok  after running `docker compose up -d`

### ❌ Actual Behavior

Cannot pull docker images correctly after running `docker compose up -d`,   occurs connection refused.

**Comment by breakstring** [comment]
Maybe you can try this:
[public-image-mirror](https://github.com/DaoCloud/public-image-mirror)

**Comment by merthmagic** [comment]
```
{
  "registry-mirrors": [
	  "https://noohub.ru",
	  "https://do.nark.eu.org"
  ]
}
```

It might work
