### ISSUE TITLE
longrun workflow api call got cut off by Dify's Cloudflare gateway

### ISSUE THREAD

**Issue by OCboy5** [langgenius/dify#5982]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

[mylog.txt](https://github.com/user-attachments/files/16098467/mylog.txt)
My call to https://api.dify.ai/v1/workflows/run is a longrun call, typically lasts about 130s. I used to be able do that call successfully, but today I got cut off by the gateway after about 100 seconds. Here is the response record in my logfile. Apparently it's the Cloudflare who cut off the connection. Is this a new configuration change or an unexpected event?

### ✔️ Expected Behavior

the llm-based workflow takes a long time to complete. I would like to be able to do longrun call to the workflow api

### ❌ Actual Behavior

the longrun call was cut off in about 100 seconds by Dify's Cloudflare gateway.

**Comment by OCboy5** [comment]
Thanks! Can you show me an example of "asynchronous processing capabilities using Celery for task queueing" in Dify?

**Comment by OCboy5** [comment]
Thanks! Can you show me an example of "asynchronous processing capabilities using Celery for task queueing" in Dify? @dosu

**Comment by OCboy5** [comment]
@dosu thanks. Do I have to use an asynchronous HTTP client like aiohttp or httpx for doing requests.post to dify api server? otherwise it will still wait on the api connection and get cut off eventually.

**Comment by OCboy5** [comment]
thank you. is gevent necessary for making celery work on windows VSCode virtual env? @dosu

**Comment by OCboy5** [comment]
@dosu thanks. further question, if I want to implement a polling mechanism to check the api request status, and after it reports back SUCCESSFUL then retrieve the result. how should I make that happen?

**Comment by OCboy5** [comment]
@dosu thanks. what would the code be like if I want to implement the polling mechanism in javascript code?

**Comment by OCboy5** [comment]
@dosu thanks. what is the exact url to use to check the status of certain dify api request  of a task_id?

**Comment by Zigngit** [comment]
I am confusing what are you guys talking about?
Is this about SaaS dify at https://api.dify.ai/v1/ or a local-deployed dify?
If it is about a SaaS dify, this call will not retun immediately until the whole workflow is over and finally lead to a timeout by cloudflare

>     url = 'https://api.dify.ai/v1/workflows/run'
>     response = requests.post(url, headers=headers, json=data)

is there any way to start workflow asynchronously?
