### ISSUE TITLE
Only at most 3 LLMs results can be in Answer component, so weird bug

### ISSUE THREAD

**Issue by Aryavui** [langgenius/dify#5983]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I chained more than 3 LLMs (with an Answer component at the last) in the Chatflow app, it is so weried that I can choose at most 3 variables (LLMs outputs) in the Answer component. This is a very basic bug

**Comment by Aryavui** [comment]
This robot is very annoying. Don't you realize that? The probability that the robot can solve the problem is very low

**Comment by iamjoel** [comment]
<img width="401" alt="image" src="https://github.com/langgenius/dify/assets/2120155/dd46c484-44b2-46ea-a6fa-cc24d800ebbe">
@Aryavui I can't reproduction it. Can you provide an app DSL?
