### ISSUE TITLE
【bug】prompt is too long 

### ISSUE THREAD

**Issue by zengxiangqi1031** [langgenius/dify#5988]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when i use claude3.5-sonnet(support 200k) to tag a photo about 1.5MB  as agent ， dify said prompt tokens are 1500000+ tokens much bigger than 200k; 
 when i debug api module, i found than prompt tokens are caculated by the photo‘s bytes

### ✔️ Expected Behavior

prompt tokens should be calculated correctly.

**Comment by zengxiangqi1031** [comment]
fixed?

**Comment by zengxiangqi1031** [comment]
up

**Comment by crazywoola** [comment]
You can zip the image to smaller ones.
