### ISSUE TITLE
There are both Chinese and English

### ISSUE THREAD

**Issue by silence-pan84** [langgenius/dify#5994]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

![image](https://github.com/langgenius/dify/assets/174668054/863ced9e-83ae-4486-ad2f-30a5714f030e)
Docker deployment, running language Settings are simplified Chinese. But there is still English on the interface.

**Comment by crazywoola** [comment]
There are 2 languages settings in the application.

1. System language settings
2. Shared application language settings.

In your case, you need to change the second one instead of the first one.

**Comment by silence-pan84** [comment]
Could you tell me where to set the shared application language? 
@crazywoola

**Comment by silence-pan84** [comment]
Could you tell me where to set the shared application language? @crazywoola

**Comment by Jimmy0769** [comment]
> There are 2 languages settings in the application.
> 
> 1. System language settings
> 2. Shared application language settings.
> 
> In your case, you need to change the second one instead of the first one.

Please tell me where to set the language of the shared application!
