### ISSUE TITLE
忘记管理员密码怎么办

### ISSUE THREAD

**Issue by xiaoqiqiya** [langgenius/dify#5997]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

忘记管理员密码怎么办

### ✔️ Expected Behavior

可以看到密码

### ❌ Actual Behavior

忘记管理员密码怎么办

**Comment by weiweizwc98** [comment]
@dosu 如果管理员账户也忘记了怎么办
