### ISSUE TITLE
本地，全局代理，校验密钥的时候报：“无效的 OpenAI API 密钥”

### ISSUE THREAD

**Issue by jingxiang** [langgenius/dify#60]
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f94b259dbd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /v1/moderations

**Comment by takatost** [comment]
可能没有代理上 docker 容器内部的请求，可以额外配置 OPENAI_API_BASE 为 OpenAI 镜像地址，如: https://xxx.com/v1

**Comment by goodyorkye** [comment]
> 可能没有代理上 docker 容器内部的请求，可以额外配置 OPENAI_API_BASE 为 OpenAI 镜像地址，如: https://xxx.com/v1

请问OPENAI_API_BASE参数配置在哪里？

**Comment by guanman** [comment]
> > 可能没有代理上 docker 容器内部的请求，可以额外配置 OPENAI_API_BASE 为 OpenAI 镜像地址，如: https://xxx.com/v1
> 
> 我试用OPENAI的key，请问OPENAI_API_BASE参数配置在哪里？

同问，我也遇到了同样的问题“无效的 OpenAI API 密钥”，也没找到OPENAI_API_BASE配置在哪里

**Comment by takatost** [comment]
OPENAI_API_BASE 可以直接作为环境变量设置的

**Comment by Huiguorou12** [comment]
请问如何直接作为环境变量设置，我尝试使用export OPENAI_API_BASE="http://4xxx"，但是没有效果，是我的方式错了吗

**Comment by takatost** [comment]
可以在 docker-compose.yaml 中的 api 和 worker 服务加一条 environments 记录
```
OPENAI_API_BASE: 'https://<your-openai-mirror-domain>/v1'
```

**Comment by hw95031** [comment]
如何查看我的镜像地址在哪里啊OPENAI_API_BASE: 'https://<your-openai-mirror-domain>/v1'
