### ISSUE TITLE
Runtime Error occurs when running  `poetry shell` 

### ISSUE THREAD

**Issue by lepangdan** [langgenius/dify#6001]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Runtime Error occurs when running  `poetry shell`  in api/readme.md.

> Dify API service uses [Poetry](https://python-poetry.org/docs/) to manage dependencies. You can execute poetry shell to activate the environment.

### ✔️ Expected Behavior

The thing is ok.

### ❌ Actual Behavior

/dify/api$ poetry shell

 RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group', 'package-mode' were unexpected)
    - 'version' is a required property
    - 'description' is a required property

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]

**Comment by crazywoola** [comment]
Please google how to use poetry instead of submitting a bug report.

**Comment by lepangdan** [comment]
> Please google how to use poetry instead of submitting a bug report.

As a developer of the open-source repository, you have the authority to close an issue directly or to simply overlook it if you see fit. However, rather than suggesting non-informative responses and discouraging users from reporting issues after they have strictly adhered to the instructions in the provided README.

**Comment by uply23333** [comment]
Upgrade poetry from 1.7.x to 1.8.x work for me.
