### ISSUE TITLE
Supported When the agent calls workflow tools, the workflow settings directly return the output of the workflow, rather than letting the agent process it based on the return of the tools

### ISSUE THREAD

**Issue by Hisir0909** [langgenius/dify#6007]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I'm trying to use the workflow tool to output some formatted content. I used the direct output mode of the workflow end node in coze, but I don't seem to find this output mode in dify.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
In workflow, you should use End node.
I am not quite understand what you described in the title, can you explain it with more details.

**Comment by Hisir0909** [comment]
The output of the workflow I designed is:  {"operate":"add","agrs":{"id":1,"balance":2}}
This is actually constructing a request parameter to modify the system data. At this time, I hope that the agent will directly return the result of the workflow, rather than letting it think again based on the results of the tool.

**Comment by Hisir0909** [comment]
I know that I should actually initiate an http request in the workflow using these parameters and finally return only the result of the request. However, due to some previous reasons, I cannot directly initiate an http request. Instead, I have to accept the return value of AI and then the caller can initiate the request himself.

**Comment by crazywoola** [comment]
You published the workflow as a tool, and call it in an agent right?
I think if you want to make sure you get the results correctly from the workflow tool, you should not use agent in this case, you need to use a chatflow to make sure there is no agent call. 
It has some limitations, because it depends on what flow you make.

**Comment by Hisir0909** [comment]
@crazywoola  In chatflow I can use Question Classifier to achieve the effect of function_call, right?

**Comment by crazywoola** [comment]
> @crazywoola In chatflow I can use Question Classifier to achieve the effect of function_call, right?

Yes, because the Classifier can direct to different tools.  You can do it like this. But it's not a mature way. I guess we will support built-in way to do fc.

**Comment by Hisir0909** [comment]
Now I should be fine, it seems my demand is an unreasonable demand
