### ISSUE TITLE
400 invalid_param  keyword is required in input form

### ISSUE THREAD

**Issue by karterotte** [langgenius/dify#6008]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The local test is successful, but an error is reported when it is published as an API call
I can't find which param is missing

Test passed in local mode:
![image](https://github.com/langgenius/dify/assets/9114743/c461f6b9-df8f-4eb0-8233-cbf63840bc7f)

Postman test fail:
![image](https://github.com/langgenius/dify/assets/9114743/ecbf5942-a763-48a2-baa4-bd7def2ec181)

**I'm sure that the api-key is right**

### ❌ Actual Behavior

I want know what to do next

**Comment by karterotte** [comment]
Another api works well

![image](https://github.com/langgenius/dify/assets/9114743/9eb40cf6-83c7-47c0-abc7-3bbe0e26326d)

**Comment by karterotte** [comment]
![image](https://github.com/langgenius/dify/assets/9114743/6ab20714-05fa-4566-9e82-507f046274f1)

like above

**Comment by crazywoola** [comment]
Have you published this workflow?

**Comment by karterotte** [comment]
I'm sure yes

![image](https://github.com/langgenius/dify/assets/9114743/64fb0662-57e8-42b3-b980-a06651468979)

**Comment by karterotte** [comment]
I'm sorry!
I redeploy the workflow,now It worked fine.
Maybe sth changed after my first deploy.
Thanks!
