### ISSUE TITLE
When I use a Japanese PDF as a knowledge, It garbled.

### ISSUE THREAD

**Issue by mihit** [langgenius/dify#6012]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Prepare a Japanese PDF contains "の".
Use it as a knowledge.

### ✔️ Expected Behavior

Never garbled.

### ❌ Actual Behavior

Bah, it garbled as "䛾".
There appears to be more than this.

**Comment by JohnJyong** [comment]
hi @mihit ,after testing, some Japanese characters may be recognized incorrectly. If it is convenient, can you send us your document for testing? thanks in advace~

**Comment by mihit** [comment]
[太宰治 走れメロス.pdf](https://github.com/user-attachments/files/16185686/default.pdf)
@JohnJyong Thank you for reply. My file is private one so I can’t share it. But I send an other Japanese PDF of literary works in the public domain for testing. Hope this helps!
