### ISSUE TITLE
Embedding Search can‘t recall the right answer

### ISSUE THREAD

**Issue by cdg1921** [langgenius/dify#6026]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When using the Embedding Search(the vector base is  Weaviate)，it's recall item always can't match the exact answer.
Economic search and full-text-search can easily get the right answer, while embedding search(semantic search) can't. 
We've tried many different queries, the same problem.

**Comment by cdg1921** [comment]
@dosu Hi, dosu. Thank you for your advises.  
We create a new knowledge base in Weaviate, and use the same document segmentations from Dify's backen database in table document_segments using the same dataset_id. And the embedding model   keep in the same as bge-large-zh-v1.5. We write the recall codes independently，we also can easily recall the right item in top5, but in Dify, the top10 items are all failed.

**Comment by cdg1921** [comment]
We've found the reason, the embedding model bge-large-zh-v1.5 from ollama is a quantitative version, which performers pool. Thank you all the same!

**Comment by lingaoan2024** [comment]
@cdg1921 So you didn't use Ollama in the end, what plan did you use?
