### ISSUE TITLE
error message：authorization config header is required

### ISSUE THREAD

**Issue by DDDU123** [langgenius/dify#6033]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I got this error message when running the HTTP node: "authorization config header is required." But everything was working fine before yesterday, and I haven't made any changes to the authorization.
![企业微信截图_20240706163352](https://github.com/langgenius/dify/assets/148761774/a81131c9-001a-4351-a4d0-1fdb660db49d)![企业微信截图_20240706163345](https://github.com/langgenius/dify/assets/148761774/e57da0c1-4ef2-4a10-a4b5-b42b80401c51)

**Comment by 75py** [comment]
I found a workaround for this issue. Instead of setting the Bearer authorization as shown in the first image, configure it using the Custom option as shown in the second image. This method works successfully.

| Configuration Method   | Image                                      |
|------------------------|--------------------------------------------|
| Bearer Authorization (does not work) | <img width="464" alt="bearer" src="https://github.com/langgenius/dify/assets/3153211/080cd1bd-69f6-47db-a2ff-eaaac2aa8d83"> |
| Custom Authorization (works)  | <img width="464" alt="custom" src="https://github.com/langgenius/dify/assets/3153211/2ad80854-0d2e-44c9-8772-88551d6abf4f"> |

**Comment by DDDU123** [comment]
> 我找到了解决此问题的方法。不要像第一张图所示那样设置 Bearer 授权，而是使用第二张图所示的自定义选项进行配置。此方法成功运行。
> 
> 配置方法	图像
> 持有人授权（无效）	<img alt="持票人" width="464" src="https://private-user-images.githubusercontent.com/3153211/346266201-080cd1bd-69f6-47db-a2ff-eaaac2aa8d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjA4MDcsIm5iZiI6MTcyMDI2MDUwNywicGF0aCI6Ii8zMTUzMjExLzM0NjI2NjIwMS0wODBjZDFiZC02OWY2LTQ3ZGItYTJmZi1lYWFhYzJhYThkODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDZUMTAwODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRmMDI4YWVkMmNlZjMyYzZhNDliZGZjOWJiNTZhOWNiZjVhNDMzODg0MDgxMTIzYThiOTg0MWRlYWFlNDk1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fcmxK9jxo9Circi6v4PwRtHtszw_nYbW_Cw4cEqrAa0">
> 自定义授权（作品）	<img alt="风俗" width="464" src="https://private-user-images.githubusercontent.com/3153211/346266213-2ad80854-0d2e-44c9-8772-88551d6abf4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjA4MDcsIm5iZiI6MTcyMDI2MDUwNywicGF0aCI6Ii8zMTUzMjExLzM0NjI2NjIxMy0yYWQ4MDg1NC0wZDJlLTQ0YzktODc3Mi04ODU1MWQ2YWJmNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDZUMTAwODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUzNjdiMjVkNDY2Mjg2N2E5ODdkY2JkOWJjZjNiMzJjMzdkMDBjMDczYTc4MGNhY2E0NTBiOGFmYmM4ZGQ5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y-LGWnh705taTJqkZnPNa_mSQ5QLDLY9zcwTNhqm9Gs">

Yes, it worked fine after I followed your instructions. Thanks! But what puzzles me is that it used to work with Bearer Authorization before. Maybe a new version of Dify introduced a bug.
