### ISSUE TITLE
The code execution unit in the workflow of dify cloud Version 0.6.12-fix1 is unable to use the "requests" library properly

### ISSUE THREAD

**Issue by ouni3** [langgenius/dify#6037]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

```python
import requests

def main() -> dict:
    response = requests.get('https://www.baidu.com/')
    if response.status_code == 200:
        result = "123"
    else:
        result="  "
    return {
        "result": result,
    }
```
<img width="478" alt="搜狗截图20240706230904" src="https://github.com/langgenius/dify/assets/37970859/3d8cf8af-70a4-44b0-b41e-9e6d4cea81b6">
<img width="482" alt="搜狗截图20240706230931" src="https://github.com/langgenius/dify/assets/37970859/f3d133fb-6177-4745-8e48-9bb64e3ef37d">

### ✔️ Expected Behavior

success work

### ❌ Actual Behavior

runtime error:/usr/local/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer). warnings.warn(

**Comment by Yeuoly** [comment]
Does this issue exists in earlier version?

**Comment by ouni3** [comment]
> Does this issue exists in earlier version?
no,i can use it correctly in 2024/06/28.

**Comment by elvis-cai** [comment]
get the same issue on 0.6.14
<img width="399" alt="image" src="https://github.com/user-attachments/assets/b27b2cf3-796e-4346-b60f-c034679b3f3e">

**Comment by hiyasichuka** [comment]
Is the only way to modify the Dockerfile as an OSS contributor to resolve this error on Dify Cloud?

**Comment by hanhaiszw** [comment]
Version 0.7.0 has the same problem

**Comment by Kevin9703** [comment]
I had the same problem. Any way to figure it out?

**Comment by pyxsqbs** [comment]
Get the same issue on api-0.7.1 and sandbox-0.2.6 @Yeuoly TOT

**Comment by Yeuoly** [comment]
> Get the same issue on api-0.7.1 and sandbox-0.2.6 @Yeuoly TOT

I suggest using httpx instead, it's a requests alternative solution and it works better.

**Comment by X4tar** [comment]
Why this issue be closed, I have the same problem.
