### ISSUE TITLE
Agent bot was lack of history conversation messages

### ISSUE THREAD

**Issue by Colstuwjx** [langgenius/dify#6046]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Hi team, thanks for creating this great platform, I've tried out Dify on my local and found an issue that I'm not sure if it's document issue or need to be enhanced:

If I define a LLM bot and set prompt like: "You're an infra troubleshooting bot, if user has already given enough information, you can do the check and generate analysis report, otherwise you should ask users to input the required information". And the conversation would be like:

```
Bot (Conversation Opener): What can I help you ?
User: this ticket failed, please check.
Bot (1st time response from the agent): Please provide the detail ticket information so that I can help you to check.
User: 12345
Bot (2st time response without the previous conversation messages): Sorry, I don't know the meaning of this number.
```

It's expected to have a kind of reply like below if it's an end user chat with ChatGPT:

```
Bot (Conversation Opener): What can I help you ?
User: this ticket failed, please check.
Bot (1st time response from the agent): Please provide the detail ticket information so that I can help you to check.
User: 12345
Bot (2st time response with these previous messages): Sure, checking ticket 12345 failure reason for you (calling ticket-query-tool).
```

Is there any reference variable that we can use as the context of each time agent query ?  Or it's a kind of configuration on somewhere?

**Comment by simplast** [comment]
History variable not working. that’s only for completion models, USELESS

**Comment by Colstuwjx** [comment]
Yes, seems like ONLY work for text completion models, see docs: https://docs.dify.ai/guides/workflow/node/llm#explanation-of-special-variables

<img width="826" alt="截屏2024-07-09 08 54 29" src="https://github.com/langgenius/dify/assets/3972545/8c12802f-61bc-4911-b177-8caf614c4c6c">

**Comment by liuminxuan** [comment]
I also have this problem. If I only deploy web and api to use it. It happens. Seems like agent cannot remember what I said before. But if I use docker-compose to run dify. It works!
How did you deploy your dify?

**Comment by liuminxuan** [comment]
It seems like my pre-prompt is too long. It will not happens if I use a short pre-prompt. Hope it can help you.

**Comment by yinxulai** [comment]
I have the same problem
