### ISSUE TITLE
API Request Issue

### ISSUE THREAD

**Issue by asrguru20** [langgenius/dify#6047]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

when I try to use Postman to send message and get response via api url and key it always says method not supported:

https://api.dify.ai/v1/completion-messages
{
    "inputs": {},
    "response_mode": "streaming",
    "user": "asrguru@gmail.com"
}

I dont even sure what us the user value is that my registered email or what please help

### ✔️ Expected Behavior

to return a chat response 

### ❌ Actual Behavior

405 Method Not Allowed

**Comment by crazywoola** [comment]
> I dont even sure what us the user value is that my registered email or what please help

This is documented in our API access.

> user:  User identifier, used to define the identity of the end-user for retrieval and statistics. Should be uniquely defined by the developer within the application.

Which means, you can input whatever you like to meet your needs.

**Comment by prasannjeet** [comment]
In case someone else facing this issue: It could just be due to the protocol used. The documentation says `http`, since most of us are using it locally. However, if you have put it behind some reverse proxy with `https`, don't forget to change it in your request. Most likely this should resolve the issue.
