### ISSUE TITLE
Add summarize the long-content feature

### ISSUE THREAD

**Issue by cysummer** [langgenius/dify#6050]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I'm trying to get the agent to summarize the document in knowledge base，contains long document.

### 2. Additional context or comments

langchain has already implemented this feature, and I hope Dify can also have this feature.
[https://python.langchain.com/v0.1/docs/use_cases/summarization/](url)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by iguoli** [comment]
I really also need this feature! I'm using python code to chunk the long-content into several pieces and transfer them to an iteration to implement the feature for now, but the performance was not good and iteration was limited to 30 elements maximum.

**Comment by luizcarvalho** [comment]
I really also need this feature!!

**Comment by MMTE** [comment]
it would be much useful

**Comment by MMTE** [comment]
it would be much useful
