### ISSUE TITLE
management of metadata in the knowledge base

### ISSUE THREAD

**Issue by kingslyChen** [langgenius/dify#6051]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

management of metadata in the knowledge base

### 2. Additional context or comments

When will the management of metadata in the knowledge base become available? Does the knowledge base support third-party API data import? The imported data needs to be accompanied by a unique ID identifier of a third-party API, and the specific information of these metadata can be returned when querying

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6020
