### ISSUE TITLE
Feature Request: Support for Local Embedding Models(Deployed by Xinference) in Knowledge Base and WorkFlow

### ISSUE THREAD

**Issue by Q-Ot** [langgenius/dify#6056]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I am currently in the process of creating my knowledge base and workflow, and I wish to utilize the embedding models that I have deployed through Xinference. However, I have not been able to find any components in either the knowledge base or the workflow where I can select which embedding model to use.
![p_17200632842642](https://github.com/langgenius/dify/assets/174573649/57343d0c-06d3-478b-901f-4415ba2e6e6d)

In the workflow, the knowledge retrieval node uses an chat-LLM for the n-select-1 retrieval and a rerank model for multi-retrieval. I am unable to use an embedding model for vector retrieval and then apply the rerank model for reordering.
![p_1720063240990](https://github.com/langgenius/dify/assets/174573649/e36a6498-2e58-4240-9327-8a79c60b1b0f)

In the knowledge base, the eco mode does not provide options related to the model, and the high-quality mode, whether it is vector retrieval, full-text retrieval, or hybrid retrieval, only offers choices for the rerank model.
![p_17200641604613](https://github.com/langgenius/dify/assets/174573649/dfae7c55-c68d-4e9b-970a-c44ef12a9d2b)

What I would like to know is whether Dify can provide the following capabilities:
1、At least in High-Quality Mode, Supporting the integration of locally deployed embedding models to provide more flexibility and customization for users with specific indexing needs.
2、In the knowledge retrieval node, I would like to have the option to use the vector similarity of text segments (such as Euclidean distance or cosine similarity) as the sole or primary sorting criterion. The top K similar text segments, based on this similarity measure, should then be provided as context to the other node in the workflow.

### 2. Additional context or comments

It is possible that my previous issue #5905 contains supplementary information relevant to this one, which may assist in a better understanding of my requirements.  
I appreciate your support and the responses provided thus far.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
In knowledge settings
<img width="752" alt="image" src="https://github.com/langgenius/dify/assets/100913391/425f15f7-dc0a-4876-8176-13d0b517457e">
Or you can configure the system embedding model as well, then all the documents will use that model as default.

**Comment by Q-Ot** [comment]
> In knowledge settings <img alt="image" width="752" src="https://private-user-images.githubusercontent.com/100913391/346475120-425f15f7-dc0a-4876-8176-13d0b517457e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjU2MjYsIm5iZiI6MTcyMDQyNTMyNiwicGF0aCI6Ii8xMDA5MTMzOTEvMzQ2NDc1MTIwLTQyNWYxNWY3LWRjMGEtNDg3Ni04MTc2LTEzZDBiNTE3NDU3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzU1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGM2OTM3YmI2NDBhODVjYzZhZGFiZjhkY2I2ZDg3MmZmYWU1ZTZiODJhNmFlNmM5NzViNmJiNmQ0YzY4NzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sN3mGAXCkLNDRGhRvtJCrR0GNS3x7NS_xc6AGhUGItU"> Or you can configure the system embedding model as well, then all the documents will use that model as default.

@crazywoola  Thank you for your response and the illustrative images, I found this page in knowledge base settings.

I have two new questions regarding your answer that I hope to get answers to:
1、If a knowledge base is initially set up in eco mode and later switched to high-quality mode with an embedding model configured, will the already segmented text be re-vectorized and re-indexed accordingly?
2、I've noticed that this page is accessible only after the knowledge base has been created. Can I understand it this way: If I have configured a default embedding model, even though there is no option at the time of creating the knowledge base, the vectorization of the text segments is still carried out through my configured default embedding model?
![p_20240708161750](https://github.com/langgenius/dify/assets/174573649/348a8aa8-9de3-47a3-8ac6-c659d79a23a0)

**Comment by crazywoola** [comment]
> will the already segmented text be re-vectorized and re-indexed accordingly? 

Yes

> I've noticed that this page is accessible only after the knowledge base has been created. Can I understand it this way: If I have configured a default embedding model, even though there is no option at the time of creating the knowledge base, the vectorization of the text segments is still carried out through my configured default embedding model? 

Yes
