### ISSUE TITLE
I need a changeable Global Variable To Control Workflow, like variable "stage", after certain work, change the global variable "stage" from 0 to 1 and route to different path of workflow. 

### ISSUE THREAD

**Issue by tianlongwang** [langgenius/dify#6060]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes, I'm working on a workflow with different stage. I need a **changeable global variable** that can be accessed and modified by all other node. For example, the variable "stage", after certain work, change the global variable "stage" from 0 to 1 and route to different path of worflow. 

### 2. Additional context or comments

Let me know if I'm not using this right. 

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Curlyfuu** [comment]
I'm having the same problem when executing an iteration.

**Comment by crazywoola** [comment]
See conversation variables.
