### ISSUE TITLE
docker-compose up -d failed

### ISSUE THREAD

**Issue by qiwangzi** [langgenius/dify#6061]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/21352350/944ad1a9-21f6-41c8-9961-497cf87ea60c)

### ✔️ Expected Behavior

success

### ❌ Actual Behavior

failed

**Comment by qiwangzi** [comment]
![image](https://github.com/langgenius/dify/assets/21352350/754b3acb-59fd-40bd-ae42-a3352fdbea13)
Docker and Docker Compose versions meet the prerequisites，but I'm still encountering issues

**Comment by crazywoola** [comment]
Make sure you have ran `cp .env.example .env` before `docker compose up -d`
