### ISSUE TITLE
redis.exceptions.AuthenticationError

### ISSUE THREAD

**Issue by MuLoo** [langgenius/dify#6067]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Start according to [documentation](https://docs.dify.ai/getting-started/install-self-hosted/local-source-code)

### ✔️ Expected Behavior

It is hoped that Redis can connect to the local database without reporting errors. The console/api/login returns 200. 

### ❌ Actual Behavior

The project initialization at http://localhost:3000/install was successful.   
When I accessed http://localhost:3000/signin for login, an error occurred.     
The error message:
```
ERROR [Thread-7 (process_request_thread)] [app.py:838] - Exception on **/console/api/login** [POST]
Traceback (most recent call last):
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/user/mine/GitHub/dify/api/controllers/console/setup.py", line 86, in decorated
    return view(*args, **kwargs)
  File "/Users/user/mine/GitHub/dify/api/controllers/console/auth/login.py", line 40, in post
    token = AccountService.login(account, ip_address=get_remote_ip(request))
  File "/Users/user/mine/GitHub/dify/api/services/account_service.py", line 211, in login
    redis_client.set(_get_login_cache_key(account_id=account.id, token=token), '1', ex=int(exp.total_seconds()))
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/redis/commands/core.py", line 2342, in set
    return self.execute_command("SET", *pieces, **options)
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/redis/client.py", line 542, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 1109, in get_connection
    connection.connect()
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 288, in connect
    self.on_connect()
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 354, in on_connect
    auth_response = self.read_response()
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/Users/user/mine/GitHub/dify/api/.venv/lib/python3.10/site-packages/redis/_parsers/hiredis.py", line 133, in read_response
    raise response
**redis.exceptions.AuthenticationError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?**
```

In the docker/docker-compose.middleware.yaml file:
```yaml
  # The redis cache.
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      # Mount the redis data directory to the container.
      - ./volumes/redis/data:/data
    # Set the redis password when startup redis server.
    command: redis-server --requirepass difyai123456
    ports:
      - "6379:6379"
```
In the local api/.env file, there is `REDIS_PASSWORD=difyai123456`.   
I print the password infomation in `api/extensions/ext_redis.py` it shows `difyai123456`,
But the console/api/login interface still returns error.   
Did I miss something? 

btw, I'm using a Mac M2.

**Comment by crazywoola** [comment]
If you want to connect redis which not provided by the docker-compose. You need to setup these variables:

https://github.com/langgenius/dify/blob/00b4cc3cd44439d933a38d0ca28fde9b5c350a05/docker/.env.example#L148-L152

**Comment by MuLoo** [comment]
> If you want to connect redis which not provided by the docker-compose. You need to setup these variables:
> 
> https://github.com/langgenius/dify/blob/00b4cc3cd44439d933a38d0ca28fde9b5c350a05/docker/.env.example#L148-L152
> 
> These changes are not necessary.
> 
> ```
>   # The redis cache.
>   redis:
>     image: redis:6-alpine
>     restart: always
>     volumes:
>       # Mount the redis data directory to the container.
>       - ./volumes/redis/data:/data
>     # Set the redis password when startup redis server.
>     command: redis-server --requirepass difyai123456
>     ports:
>       - "6379:6379"
> ```

I might not have expressed myself clearly.   
I started it using docker compose as shown in the local source code [document](https://docs.dify.ai/getting-started/install-self-hosted/local-source-code#clone-dify)
```ymal
cd docker
cp middleware.env.example middleware.env
docker compose -f docker-compose.middleware.yaml up -d
```

And in the `api/.env file`,  
```ymal 
REDIS_PASSWORD=difyai123456
```

In this case, what should I do?
If the Redis password is cancelled, it will be another kind of error.

**Comment by ihaichao** [comment]
I also encountered a similar error. My error message is redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set. I tried according to the following method, but there is still this error.

> @MuLoo Hello there! I'm here to help you with any bugs, questions, or contributions while waiting for a human maintainer.
> 
> The `redis.exceptions.AuthenticationError` you're encountering suggests that there might be a mismatch or misconfiguration in the Redis password setup. Here are a few steps to ensure everything is correctly configured:
> 
> 1. **Verify Redis Password in `docker-compose.middleware.yaml`**:
>    Ensure the Redis password is correctly set in the `docker-compose.middleware.yaml` file:
>    ```yaml
>    redis:
>      image: redis:6-alpine
>      restart: always
>      volumes:
>        - ./volumes/redis/data:/data
>      command: redis-server --requirepass difyai123456
>      ports:
>        - "6379:6379"
>    ```
> 2. **Verify Redis Password in `api/.env`**:
>    Ensure the Redis password in the `api/.env` file matches the one in the `docker-compose.middleware.yaml` file:
>    ```dotenv
>    REDIS_PASSWORD=difyai123456
>    ```
> 3. **Check Environment Variable Handling**:
>    Ensure that the environment variable `REDIS_PASSWORD` is correctly loaded and used in your application. The `command` directive in the `docker-compose.middleware.yaml` file should enforce the password requirement:
>    ```yaml
>    command: redis-server --requirepass ${REDIS_PASSWORD:-difyai123456}
>    ```
> 4. **Restart Docker Containers**:
>    After verifying the configurations, restart your Docker containers to apply the changes:
>    ```shell
>    docker compose down
>    docker compose up -d
>    ```
> 5. **Check Redis Connection in Code**:
>    Ensure that the Redis client in your code is using the correct password. The `redis_client` should be initialized with the password from the environment variable:
>    ```python
>    import os
>    from redis import Redis
>    
>    redis_client = Redis(
>        host=os.getenv('REDIS_HOST', 'localhost'),
>        port=int(os.getenv('REDIS_PORT', 6379)),
>        password=os.getenv('REDIS_PASSWORD', 'difyai123456')
>    )
>    ```
> 
> By following these steps, you should be able to resolve the `redis.exceptions.AuthenticationError` and ensure that Redis connects successfully with the correct password [[1]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.middleware.yaml)[[2]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.middleware.yaml).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

**Comment by erigo** [comment]
remove the default value in docker-compose.yaml
from `REDIS_PASSWORD: ${REDIS_PASSWORD:-difyai123456}` to `REDIS_PASSWORD: ${REDIS_PASSWORD:-}`

**Comment by jqhr** [comment]
The reason is new redis docker image  AUTH need both username and password.But dify default `REDIS_USERNAME` was None.
So, just set `REDIS_USERNAME` to `default`, and work out
