### ISSUE TITLE
get access to llm returned usage data inside a workflow

### ISSUE THREAD

**Issue by OCboy5** [langgenius/dify#6068]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Inside a workflow, the llm request returns a json object of { "text", "usage"}, but the llm node only output the "text". How can I access the "usage" part outside of the llm node?

### ✔️ Expected Behavior

I want to know the cost of the llm request from it's returned usage[total_price] field. 

### ❌ Actual Behavior

I don't have a way to access that returned data outside of the llm node.

**Comment by crazywoola** [comment]
This is a bug report template, if you want to bring up something new, please use the right template to open a feature request.
