### ISSUE TITLE
About using langchain in enhanced dependencies in python code

### ISSUE THREAD

**Issue by vipspecial** [langgenius/dify#6074]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In the actual scenario, I will add some code functions of Langchain on Dify. Can I add the reference of Langchain in the "Enhance Dependency" of the code module in the orchestration? I can't find the relevant document. Does anyone know?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We have removed langchain since v0.4.1 See blogs here https://dify.ai/blog/the-model-runtime-restructure

If you want to use in Code Node, you can add it as dependency here.

https://github.com/langgenius/dify/blob/0f8625cac25405f8cf3043b43b9c7d18afb6a4d7/docker/docker-compose.middleware.yaml#L30-L47

**Comment by vipspecial** [comment]
> 自 v0.4.1 以来，我们已删除了 langchain，请参阅此处的博客https://dify.ai/blog/the-model-runtime-restructure
> 
> 如果您想在代码节点中使用，您可以在这里将其添加为依赖项。
> 
> https://github.com/langgenius/dify/blob/0f8625cac25405f8cf3043b43b9c7d18afb6a4d7/docker/docker-compose.middleware.yaml#L30-L47

非常感谢
