### ISSUE TITLE
Support to delete message in a shared chat

### ISSUE THREAD

**Issue by k8scat** [langgenius/dify#6082]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

delete message in a shared chat

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Delete those messages from where?

**Comment by k8scat** [comment]
> Delete those messages from where? It seems a little bit vague to us.

![a748bb5d94aa1376480c3be48074a7dc](https://github.com/user-attachments/assets/7fc0c974-55f9-4926-a456-73f7d5a03023)
