### ISSUE TITLE
Add file upload tool to workflow

### ISSUE THREAD

**Issue by xw2723** [langgenius/dify#6093]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I now have a lot of workflows that need to use files, especially Excel and CSV. The current status of the file upload tool in the official documentation is (coming soon). I would like to know a specific time so that I can better evaluate my work.

### 2. Additional context or comments

Thanks to the Dify team for their efforts and dedication！

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated
