### ISSUE TITLE
DeepSeek now supports 128k context size

### ISSUE THREAD

**Issue by BryceWG** [langgenius/dify#6095]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, the DeepSeek official API supports a context size of 128k, which is a significant enhancement over the previous 32k limit.

### 2. Additional context or comments

![Clip_2024-07-09_15-19-08](https://github.com/langgenius/dify/assets/87651641/5fd251bd-9f46-4df7-bc08-95628a943ef3)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can open a pr to change configuration files accordingly.

https://github.com/langgenius/dify/blob/c163521b9e5e1a4dc69dbb3042020990aab1d9b5/api/core/model_runtime/model_providers/deepseek/llm/deepseek-chat.yaml#L10

https://github.com/langgenius/dify/blob/c163521b9e5e1a4dc69dbb3042020990aab1d9b5/api/core/model_runtime/model_providers/deepseek/llm/deepseek-coder.yaml#L10
