### ISSUE TITLE
导入数据后，建立索引时服务器崩溃，建立不成功。

### ISSUE THREAD

**Issue by caolixiang** [langgenius/dify#61]
【环境】腾讯云 日本服务器
【问题】通过docker可以正常启动，可以校验api-key。但是导入数据集时，使用Chat-gpt，系统崩溃。
【尝试次数】2

**Comment by liuzimu1995** [comment]
有可能是worker进程在postgres中没有找到文件，我昨天也遇到过。
请检查一下如果是本地postgres下，/app/api/postgres 是否正确映射。
worker 和 api 映射这同一个文件夹。

**Comment by caolixiang** [comment]
> 有可能是worker进程在postgres中没有找到文件，我昨天也遇到过。 请检查一下如果是本地postgres下，/app/api/postgres 是否正确映射。 worker 和 api 映射这同一个文件夹。

能否参考下您的docker/docker-compose.yaml

**Comment by caolixiang** [comment]
找到原因了，是太吃配置了。导入一个文档要半个小时。
