### ISSUE TITLE
what does sandbox==0.2.4 update?

### ISSUE THREAD

**Issue by DAAworld** [langgenius/dify#6106]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I found that sandbox had updated to 0.2.4.what did it update in this version ?

### 2. Additional context or comments

no

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify-sandbox. This is a feature request template, if you would like to ask a question, please go to https://github.com/langgenius/dify/discussions
