### ISSUE TITLE
How to save user entered data in a form for personalizations?

### ISSUE THREAD

**Issue by lheng18** [langgenius/dify#6108]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Need to create a web site that allow users register and enter their own data through forms. How to integrate a regular database to the tool? Thanks!

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See this repo https://github.com/crazywoola/dify-tools-worker. You can create an external service to store user related data.
