### ISSUE TITLE
Uploaded data status keep queuing

### ISSUE THREAD

**Issue by vekrumk** [langgenius/dify#6112]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Upload documents in knowledge, they do not get processed just keep queuing. 
![image](https://github.com/langgenius/dify/assets/13925050/3abe1297-874c-4b12-8ef8-9d725bba509f)

### ✔️ Expected Behavior

Expected file to process.

### ❌ Actual Behavior

Keeps queuing and never processes. This issue was closed last year year as Issue  #696 but is happening again.

**Comment by crazywoola** [comment]
Please provide the containers' logs if you are using docker.

**Comment by vekrumk** [comment]
Yes using Docker. Logs for which container?

**Comment by crazywoola** [comment]
In this case you should check api and worker.

**Comment by vekrumk** [comment]
For Weaviate:
 docker logs 1254bd8e9b33
{"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2024-07-09T14:33:33Z"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2024-07-09T14:33:33Z"}
{"action":"grpc_startup","level":"info","msg":"grpc server listening at [::]:50051","time":"2024-07-09T14:33:33Z"}
{"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2024-07-09T14:33:33Z"}

**Comment by vekrumk** [comment]
Does the default_vectorizer_module need to be set to something other than none? None is the default setting int he .env. 
![image](https://github.com/langgenius/dify/assets/13925050/984f4bad-ead5-403f-9112-c3b9a1ffab74)

**Comment by crazywoola** [comment]
I mean the logs of api and worker not the vector db. 

> Does the default_vectorizer_module need to be set to something other than none? None is the default setting int he .env.

If you choose to use weaviate, you can leave all those variables untouched. They have already configured as a template.

**Comment by vekrumk** [comment]
Looks like it was a wrong Redis password in the Celery config in the .env file. The logs said it was not able to connect to Redis and started working now. But it doesn't process the old queued docs, should I delete them and re-upload?

**Comment by vekrumk** [comment]
BTW, what is the limit on how many documents in a knowledge store?

**Comment by crazywoola** [comment]
> Looks like it was a wrong Redis password in the Celery config in the .env file. The logs said it was not able to connect to Redis and started working now. But it doesn't process the old queued docs, should I delete them and re-upload?

Yes



> BTW, what is the limit on how many documents in a knowledge store?

It depends on your computer. We don't have a limitations of how many documents can be uploaded in CE version.
