### ISSUE TITLE
Credentials validation failed with status code 403

### ISSUE THREAD

**Issue by Kyrie-LiuX** [langgenius/dify#6114]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

7.1st download

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In Dify, when adding the Grog API key, an error occurs: "Credentials validation failed with status code 403".I add 讯飞星火 API key success,but grog don't work.Please help me.

### ✔️ Expected Behavior

I want you to analysis why this happen and solve it.

**Comment by Kyrie-LiuX** [comment]
I need people to help me.Your advice doesn't work.

**Comment by pei55** [comment]
I had the same problem.

**Comment by crazywoola** [comment]
Can not reproduce this on latest branch

**Comment by Wanghn233** [comment]
This is an error caused by networking issues. You can use Deno to proxy access to Groq and then add a model of the OpenAI-API-compatible type.

**Comment by badspider7** [comment]
use openrouter plugin has the same issue
