### ISSUE TITLE
prompt str is null .lose

### ISSUE THREAD

**Issue by zhiqunlin** [langgenius/dify#6119]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/langgenius/dify/assets/10475902/4b909ad7-2b6f-4b2d-9870-6e1404136d9c)

output textString  in LLM  input to sdwebui-node .after sdwebui-ui node  execute . i get this output textString  in answer node,it is null

### ✔️ Expected Behavior

. i get this output textString  in answer node,it is not null

### ❌ Actual Behavior

. i get this output textString  in answer node,it is null
![image](https://github.com/langgenius/dify/assets/10475902/4f6339c5-3399-4c1e-967b-66b569519c31)

**Comment by crazywoola** [comment]
It should be resolved now.
