### ISSUE TITLE
Error configuring groq's key: Credentials validation failed with status code 403

### ISSUE THREAD

**Issue by nickboyabc** [langgenius/dify#6121]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

key is newly created

**Comment by nickboyabc** [comment]
![1](https://github.com/langgenius/dify/assets/120318135/6bc364fc-8763-4325-a242-4d6a60e8b1c1)

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/6114
