### ISSUE TITLE
Variable Cannot Be Set in System Prompt When Using Claude Models

### ISSUE THREAD

**Issue by luanluandehaobaoman** [langgenius/dify#6131]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- When using the Claude series models, if you use variables in the system prompt, it will cause an error. 
<img width="1704" alt="image" src="https://github.com/langgenius/dify/assets/25606868/84c4cb49-1c8d-4a68-a69f-60b74a3d06e1">
<img width="1852" alt="image" src="https://github.com/langgenius/dify/assets/25606868/794a79e7-8e1c-4b75-9b3a-5fadcebda9cc">
error：
"Node 翻译 run failed: [bedrock] Error: Error code: 400 - {'message': 'Malformed input request: #: subject must not be valid against schema {"required":["messages"]}#/messages: expected minimum item count: 1, found: 0, please reformat your input and try again.'}
"

- When place the variables in the user prompt for it to work.
<img width="1790" alt="image" src="https://github.com/langgenius/dify/assets/25606868/5d4fabd3-b4cc-4434-b270-5835a2eae724">

### ✔️ Expected Behavior

 Although this is due to the difference between the Anthropic and OpenAI APIs, I think this issue should be addressed from the model runtime perspective.

**Comment by sinomoe** [comment]
The empty user prompt caused this issue, it's not a bug

**Comment by crazywoola** [comment]
Yes it's because only user and assistant are supported in Claude series.

**Comment by crazywoola** [comment]
> When using the Claude series models, if you use variables in the system prompt, it will cause an error.
> When place the variables in the user prompt for it to work.

The variables are worked only if you add one user message. Otherwise there should be a 400 error.

See this example here

<img width="655" alt="image" src="https://github.com/langgenius/dify/assets/100913391/34ac6314-bee8-472b-83e1-9170a263b598">
