### ISSUE TITLE
Can Dify retrival structured dataset? for example, .csv? and answer questions from nature language. 

### ISSUE THREAD

**Issue by AmyHei** [langgenius/dify#6140]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to upload structured data and retrival, answer question based my data. for example, which customer is the most profit one? 

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Consider you have something like

```
1,a,b,c
2,d,e,f
```

If you upload the csv file to embedding service, and split those lines by `\n`. Yes, you can ask questions regarding the data.

But for more complex situation, like fetching multiple records from this file. Then you should use the traditional way to get data from an api which is well-structured.

A common scenario is, you can upload csv file to a database, and use LLM to parse natural language to SQL and get the data accordingly.

**Comment by mboo2005** [comment]
![image](https://github.com/user-attachments/assets/8f498689-e51d-42a7-82d9-780b198e85c8)
@crazywoola Does Dify support filtering during vector search, similar to the syntax used in Weaviate as shown above? In certain scenarios, it is necessary to deterministically filter data, as relying solely on vector search is not sufficient.
