### ISSUE TITLE
The workflow will report an error as long as it is connected to the end node.

### ISSUE THREAD

**Issue by Hisir0909** [langgenius/dify#6145]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[生成一周的菜单.txt](https://github.com/user-attachments/files/16158293/default.txt)
The above is the DSL file of the workflow. Since it does not support yml, the suffix is ​​changed to txt.
As long as the end node is disconnected, it will be normal, but an error will occur if it is connected.

### ✔️ Expected Behavior

All processes except end are running normally, and end only outputs the previous content

### ❌ Actual Behavior

Once connected to end, it will be displayed **"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."**

**Comment by crazywoola** [comment]
Hello can you try using Cloud SaaS version to see if it works. Maybe it's related to the configuration of UnstructureIO

**Comment by Hisir0909** [comment]
@crazywoola  In fact, this strange bug originally came from the cloud version, but I found that after exporting it and running it in the docker version, the same error occurred.   😆

**Comment by crazywoola** [comment]
I guess the template is wrong somehow.
