### ISSUE TITLE
Adding a 'model' parameter to API requests, allowing users to dynamically choose among various models

### ISSUE THREAD

**Issue by gaotong2055** [langgenius/dify#6160]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Our aspiration is for users to have the autonomy to select their preferred models, such as between GPT3 and GPT4. Under the current paradigm, implementing this choice necessitates the creation of duplicate APIs, differentiated solely by their associated model configurations. Ideally, we would incorporate a 'model' parameter within the API request structure, thereby enabling the dynamic selection of distinct models. While it's true that the current setup allows for some level of configurability regarding the model linked to each API, this arrangement falls short in terms of flexibility.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
[Chatbot.txt](https://github.com/user-attachments/files/16163957/Chatbot.txt)

Please download this template and rename it into `Chatbot.yml`. You can test it in Cloud, because there is a new function hasn't been released yet.

I think this could solve your problem.
