### ISSUE TITLE
support chart display in conversation

### ISSUE THREAD

**Issue by yc3231996** [langgenius/dify#6164]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In data analysis scenario, I would like data displayed as interactive charts for better user experience. The build-in chart tools only generates chart images, but not interactive chart.

### 2. Additional context or comments

By extending the Markdown component to recognize custom chart code blocks and render them using ECHARTS, then we can display dynamic charts within the conversation responses. 
 leverages the flexibility of markdown while integrating powerful charting capabilities directly into web frontend.

I have implemented in my own project, looks good.
![image](https://github.com/langgenius/dify/assets/20618176/d3ac3ab4-1901-44fc-ad0c-5931e5994192)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
How does the generated code looks like?

**Comment by yc3231996** [comment]
Implemented a ChartComponent, which draws Echart using provided options.
and used blow code in app/components//base/markdown.tsx to handle ChartComponent.
![image](https://github.com/langgenius/dify/assets/20618176/c6089109-820f-4b03-a5a5-ccdadf7b6981)
then prompt LLM to use below format for chart display.
```chart
{
  "chartType": "pie",
  "data": [
    { "name": "Apple", "value": 400 },
    { "name": "Banana", "value": 300 },
  ]
}


I can create a PR for this.

**Comment by xw2723** [comment]
This feature is really important, absolutely practical. In the development of webapp, the use of Markdown for Echarts chart presentation is already a mature scheme (syntax: "```echarts {//echarts option}```"), looking forward to seeing in dify as soon as possible, which greatly strengthened the ability of data dialogue.

**Comment by Surrin1999** [comment]
> This method is so useful that I think we should learn how to introduce it, and I think it would be better to support the data table approach

Can’t aggre more

**Comment by crazywoola** [comment]
It is introduced in #6385
