### ISSUE TITLE
Unable to display images generated by Dall-E 3

### ISSUE THREAD

**Issue by Weishan-0** [langgenius/dify#6168]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create a Chatflow or Workflow app and then incorporate a Dall-E 3 node to generate an image. 

### ✔️ Expected Behavior

![CleanShot 2024-07-11 at 09 53 26](https://github.com/langgenius/dify/assets/29089406/1e0c4ff3-d593-45b0-bcc9-cca47b2742a3)

### ❌ Actual Behavior

![CleanShot 2024-07-11 at 09 42 41](https://github.com/langgenius/dify/assets/29089406/91580a49-4490-4002-ade4-699fb7c4fa63)

**Comment by Purextreme** [comment]
I am also experiencing an issue where DALL-E-3 only returns a broken icon and fails to display the image. However, when I check the backend of DALL-E-3, it shows that the image was generated successfully. I am using the DALL-E-3 tool node on the web page.
![微信截图_20240718192411](https://github.com/user-attachments/assets/f164cb51-9504-4d6d-a29d-b47b61401332)
