### ISSUE TITLE
Can not add use an API base extension as a tool

### ISSUE THREAD

**Issue by sbkkalex** [langgenius/dify#6170]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Following the document, I create an example API base extension:
https://docs.dify.ai/guides/extension/api-based-extension#for-example

As this document shows, after add the API base extension, it should be selected as a tool. 
https://docs.dify.ai/guides/knowledge-base/external-data-tool

However, the UI of tool selection seems to be totally different, and can not find the API base extension added before.
<img width="601" alt="image" src="https://github.com/langgenius/dify/assets/146330508/b61bfa4c-eb7d-4fd4-99d6-fa88e9e7666d">

### ✔️ Expected Behavior

Somehow use the extension to get weather information.

### ❌ Actual Behavior

The extension cannot be selected.

**Comment by crazywoola** [comment]
Hello actually the api based ext is differ from the tools, See these two repos.
[Extension](https://github.com/crazywoola/dify-extensions-worker). 
[Tools](https://github.com/crazywoola/dify-tools-worker). 

API based ext is a legacy solution to make the basic chatbot to interact with the internet, so you need to use an api based variable in prompt edit box. See [this](https://docs.dify.ai/guides/extension/api-based-extension/cloudflare-workers
) for more information. 

However, if you want to create a custom tools, you need to navigate to /tools page and create a custom tool instead. See [this](https://docs.dify.ai/guides/tools) instead.
