### ISSUE TITLE
Cannot upload documents to the knowledge base

### ISSUE THREAD

**Issue by monotykamary** [langgenius/dify#6176]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Upgrade from 0.6.11 to 0.6.13, try uploading any empty file and it will not progress:
<img width="1127" alt="image" src="https://github.com/langgenius/dify/assets/1130103/19c132fd-15e7-44be-b791-0e13a8c64bc9">

### ✔️ Expected Behavior

Be able to upload a file and proceed to the next step.

### ❌ Actual Behavior

Stuck on the same page with the progress bar at 0%.

**Comment by crazywoola** [comment]
See the bot's reply.
