### ISSUE TITLE
Bad Request Error "messages: at least one message is required" when trying to use Claude in Workflow

### ISSUE THREAD

**Issue by ymurota** [langgenius/dify#6179]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When specifying claude-3-5-sonnet-20240620 as the model for the LLM block in a Workflow, I receive a `messages: at least one message is required` error as shown in the attached image. A similar issue occurs with OpenAI-API-compatible llama-3-sonar-large-32k-online, resulting in a `Last message must have role user.` error. These errors do not occur in chatbot chatflows. I suspect that these errors might be happening because there is no message with a user role in the API request to the LLM.

![スクリーンショット 2024-07-11 13 53 58](https://github.com/langgenius/dify/assets/2988614/c13b4a87-fc6f-478d-a311-4f7083c48402)

### ✔️ Expected Behavior

The LLM API should return a normal response without any errors.

### ❌ Actual Behavior

A `Bad Request Error, Error code: 400` is returned.

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/issues/6131 for details
