### ISSUE TITLE
files output parameters (ie. from image generation) not passed to a next block (ie. Code)

### ISSUE THREAD

**Issue by dominikra** [langgenius/dify#6185]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Add a image generation block ie. DALEE3 or DALEE2 with some prompt
2. Add a next block ie. CODE
3. Select context parameter in CODE BLOCK
4. There is no files parameter coming from the previous block

![image](https://github.com/langgenius/dify/assets/7000898/22857d1b-164b-4ae9-8e4d-86ddf20df288)
![image](https://github.com/langgenius/dify/assets/7000898/4be7d765-7c93-4142-bf3d-e1e23aaf57b2)

### ✔️ Expected Behavior

When adding image generation block (ie. DALEE3) i expect to be able to make a use of generated image in a next block (ie. CODE block) by having this parameter available in a next block. Currently only Parameter Aggregator block can properly receive files output parameter form DALEE block.

### ❌ Actual Behavior

There is no way to select files output from DALEE as an input parameter for Code or LLM or almost all other blocks. By looking at tracing it seems that this parameter is not being passed through making it impossible to generate image and then process it by LLM as a next step.

**Comment by crazywoola** [comment]
We haven't support this yet.

**Comment by garyfeng** [comment]
related to #5270. Any update on when this can be supported?

**Comment by zhujinle** [comment]
> related to #5270. Any update on when this can be supported?

I think this will be difficult to handle because some blocks or LLM models do not support file input or have different calling methods. If you want to process the file, you need to add a lot of conditional code. In the current version, if you need to splice output, you can try to use the direct output block. If you need to get the file in the code, try to publish the previous file generation process as a tool and call the dify API in the code to get the file.

**Comment by crazywoola** [comment]
It will be introduced in file upload feature. Please see https://github.com/langgenius/dify/issues/5346 for update
