### ISSUE TITLE
Error in text segmentation and cleaning of dify local knowledge base

### ISSUE THREAD

**Issue by RR0810** [langgenius/dify#6188]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I tried to segment and clean the text of the uploaded local knowledge base, and selected the custom mode. There was a segment identifier, and the maximum length of the segment was set to 1000. However, the result was segmented in places that did not meet 1000, and a sentence was Separate incomplete words.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
@JohnJyong Please take a look at this
