### ISSUE TITLE
Upgrade Tutorial is wrong

### ISSUE THREAD

**Issue by pourmand1376** [langgenius/dify#6189]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Hi. Thanks for creating this great platform.

Today, I upgraded my Dify Docker Installation and I came along with the issue that `docker compose down` didn't delete my docker containers. 

I think the problem is that first we update the repo, and then we use `docker compose down` which should be the opposite. 

If we make any changes to `docker-compose.yaml`, docker compose wouldn't know it is related to the services.

**Comment by crazywoola** [comment]
The  docs below only applies to a normal upgrade process.

```bash
cd dify/docker
git pull origin main
docker compose down
docker compose pull
docker compose up -d
```

For detailed information regarding how to upgrade. Please see our release logs, for example in our v0.6.12 https://github.com/langgenius/dify/releases/tag/0.6.12, we have highlighted those actions need to be done already.

**Comment by pourmand1376** [comment]
OK. I am saying that if you guide people to do:
```
cd dify/docker
docker compose down
git pull origin main
docker compose pull
docker compose up -d
```

A lot less people would have issues!
