### ISSUE TITLE
tencent_vector has a bug for knowledge retrieval

### ISSUE THREAD

**Issue by lennydou** [langgenius/dify#6205]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

use tencent vector db as vector db
1. create a Knowledge and upload a text file
2. copy a sentence from the file directly and make knowledge hit-testing
3. you will find no doc segments is retrieved

REASON
![1_WechatIMG74](https://github.com/langgenius/dify/assets/1836988/b0be6069-a0ab-4974-9cce-cc50ce537988)
in the pasted picture, i found the score in results searched from tencent db maybe bigger than 1, that makes 

score = 1 - result.get("score", 0.0)
if core > score_threshold: 
    NOTICE: not entered here

the code file:
core/rag/datasource/vdb/tencent/tencent_vector.py

### ✔️ Expected Behavior

 copy a sentence from the file directly and make knowledge hit-testing, we surely can get doc segments retrieved

### ❌ Actual Behavior

sometimes we cannot

**Comment by lennydou** [comment]
score = 1 - result.get("score", 0.0)
        score = min(score, 1.0)  # Ensure the score does not exceed 1
        if score > score_threshold:
        
        This still does not work。 The code should be changed as follow:
        score = 1 - min(result.get("score", 0.0), 1.0)  # Ensure the score does not < 0
        if score >= score_threshold:

**Comment by LeoLiuYan** [comment]
Why the tencent db returns scores more than 1, is it better to ask the tecent vector db?  @lennydou
