### ISSUE TITLE
when adding xinference model, save button wont work

### ISSUE THREAD

**Issue by berton1982** [langgenius/dify#6206]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When adding xinference models，something goes wrong，the url is invisiable:
![image](https://github.com/langgenius/dify/assets/9823821/4c935e83-522e-48d7-8bd8-a19cdd8b52e4)

when checking the request from the f12 interface, it shows that the connectiong cant be established
![image](https://github.com/langgenius/dify/assets/9823821/c5bc124a-bfc0-49ba-bcc0-2f8ba8a4aa46)

I tried the url, it seems ok
![image](https://github.com/langgenius/dify/assets/9823821/1bca2604-6d49-4c6f-a232-6d3d06111ce8)

I dont know what's going on here. need help.

### ✔️ Expected Behavior

i expect to add an embedding model.

**Comment by berton1982** [comment]
i've found out. it is because of the firewall of the host. it has been blocked. when turning off the firewall, the model has been added. thanks a lot.

**Comment by njzfw1024** [comment]
> 我找到了，是主机防火墙的问题，被屏蔽了，关掉防火墙后模型就添加上了，谢谢

May I ask which content has been modified in docker-compose.yaml. I have encountered a similar issue, I suspect it was caused due to my configuration file.
