### ISSUE TITLE
Is it possible to integrate tools (like Bing search) with the LLM knowledge base within the workflow, and then rerank the results before outputting them?

### ISSUE THREAD

**Issue by kolagood** [langgenius/dify#6207]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When using a workflow, is it possible to simultaneously search the internal knowledge base and call the Bing API when a user inputs a question? Then, can these two sets of results be unified and reranked, or simply integrated, and finally have the combined content processed by the large model to generate an answer for the user?

Since in most cases I want to utilize the content of the knowledge base, but due to insufficient data in the internal knowledge base, I need to supplement it with the latest internet data. Therefore, I want to proceed integrate together in this way.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes you can put a knowledge retrieve node before the LLM use a if/else node to determine whether you should do a bing search.
