### ISSUE TITLE
chatbot support file stream upload ,

### ISSUE THREAD

**Issue by zhiqunlin** [langgenius/dify#6214]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

it will be more  perfect  to support file stream ，like  doc  PDF DOC, PPT, XLS.TXT. . audio 

### 2. Additional context or comments

like  this 
![image](https://github.com/user-attachments/assets/508e9161-1cb2-41c1-ac3b-36b4ea5849e7)

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated, we will start working on this next month.

**Comment by Dofine-dufei** [comment]
Our project ,desperately looking for this feature...

**Comment by Dofine-dufei** [comment]
We hope that chat supports file upload, and then function-calling to parse the file for rag.

**Comment by Dofine-dufei** [comment]
My current solution is to add a file upload function option in model_config, then click the upload button in the chat, upload the file and return the file link, then send the file information to llm with the message, and pass the file link to tool when llm fc, so as to realize the RAG of file upload parsing...

**Comment by jaxonister** [comment]
I also need this feature, is it online?
