### ISSUE TITLE
When I try to retrieve the conversation history via the API, it always returns an empty result.

### ISSUE THREAD

**Issue by nb75km** [langgenius/dify#6216]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am trying to retrieve the conversation history through the HTTP request block on Dify.

## Steps to Reproduce

1. Use the HTTP request block on Dify to send the following request:

GET http://locallhost/v1/conversations HTTP/1.1
Authorization: ***********************************

2. The following response is returned as a result of the request:

{
"status_code": 200,
"body": "{"limit": 20, "has_more": false, "data": []}\n",
"headers": {
"server": "nginx/1.27.0",
"date": "Fri, 12 Jul 2024 01:48:52 GMT",
"content-type": "application/json",
"content-length": "45",
"access-control-allow-origin": "*",
"set-cookie": "remember_token=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/",
"x-version": "0.6.13",
"x-env": "PRODUCTION",
"cache-status": "863e0002c72b;detail=mismatch",
"via": "1.1 863e0002c72b (squid/6.6)",
"connection": "keep-alive"
},
"files": []
}

3. Although there is conversation data in PostgreSQL, the `data` field is always empty in the response.

These steps reproduce the issue where the conversation history is always returned empty.

**Comment by crazywoola** [comment]
Can you paste the payload as well? 
According to the code, you need to provide a user_id as well.

https://github.com/langgenius/dify/blob/f599f41336e5f72e88cc9cf4ae50e365e8076672/api/controllers/service_api/app/conversation.py#L31

**Comment by nb75km** [comment]
I tried sending the user_id, but it did not improve the situation. 
Is this payload correct?

![payload](https://github.com/user-attachments/assets/91f84de6-c4aa-4b25-9487-32e1d9a5c936)

**Comment by nb75km** [comment]
I see. I hadn't checked that. Thank you.
