### ISSUE TITLE
Better user roles

### ISSUE THREAD

**Issue by silver0919** [langgenius/dify#6217]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Our workspace has multiple editors，if anyone create an app，other editors can change some contents in the page of that app. Can dify limits the permissions of editor? If someone deploy an app, only that editor can revise the contents in the page of that app.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/5670

**Comment by ML-ZXF** [comment]
this is a problem , omeone in same workspace may have modified my workflow, but I don't know this ,we may need a version control system, or "only me can modify it"

**Comment by yaohongfenglove** [comment]
+1
