### ISSUE TITLE
Cannot receive inputs parameter in API interface

### ISSUE THREAD

**Issue by suxuanning** [langgenius/dify#6220]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/cb936f4e-5017-4206-a0b0-6c0b6a57b271)
![image](https://github.com/user-attachments/assets/3f3b39de-45c6-4d03-970b-a38818778b24)
![image](https://github.com/user-attachments/assets/2f2c6c88-b1df-43fb-a93e-862e897a5c4e)

### ✔️ Expected Behavior

Received this parameter

### ❌ Actual Behavior

No parameters received

**Comment by crazywoola** [comment]
<img width="200" alt="image" src="https://github.com/user-attachments/assets/08b223e1-9d36-4153-af45-f73ea926d2d4">
From this image you provided, you could delete it and enter it again. That should solve your problem.

**Comment by suxuanning** [comment]
What I want to accept is the text in the input, but it hasn't returned yet, which should be: Hello, how are you?

**Comment by suxuanning** [comment]
> <img alt="image" width="200" src="https://private-user-images.githubusercontent.com/100913391/348114671-08b223e1-9d36-4153-af45-f73ea926d2d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTQ5NDUsIm5iZiI6MTcyMDc1NDY0NSwicGF0aCI6Ii8xMDA5MTMzOTEvMzQ4MTE0NjcxLTA4YjIyM2UxLTlkMzYtNDE1My1hZjQ1LWY3M2VhOTI2ZDJkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwMzI0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGUxYWFlYjA5MTA0ZDk3ZDEyMDlmYjZiZThiYjQ1NWY0NjEzMDgxNWZkMTc2NTAyNzU2MGYwMmI2NGY1ODU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2EZAx5rlVELd7epSeW_b1-fXodZ4XmR-94TNKeqdlSU"> From this image you provided, you could delete it and enter it again. That should solve your problem.

What I want to accept is the text in the input, but it hasn't returned yet, which should be: Hello, how are you?
