### ISSUE TITLE
next suggest question need support chinese

### ISSUE THREAD

**Issue by Jalylnn** [langgenius/dify#6231]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Utility with translation issue

next suggest question 

### 🌐 Language affected

chinese

### ❌ Actual phrase(s)

next suggest question  not support chinese,only generate english question
![image](https://github.com/user-attachments/assets/0de9c6f3-0539-4050-86cd-c7a779eb364a)

### ✔️ Expected phrase(s)

support chinese question generate
![image](https://github.com/user-attachments/assets/a974b2c6-25aa-46af-99c1-f797ae2da88f)

### ℹ Why is the current translation wrong

when chinese user use it，this function can not use

**Comment by likenamehaojie** [comment]
set your appliction chinese the next suggest is chinese

**Comment by tangyoha** [comment]
I think we should explicitly tell llm the current language.

**Comment by Jalylnn** [comment]
![image](https://github.com/user-attachments/assets/707a1224-c860-4385-b38c-5c23f706fc0d)
![image](https://github.com/user-attachments/assets/103e3ad1-1ee5-40d8-a431-4ae9fff3071d)
it show chinese，because i change the source code，force add language  chinaese in prompt.

**Comment by Sakura4036** [comment]
> set your appliction chinese the next suggest is chinese

Sometimes the first few question suggestions are in Chinese, but after several uses they become English, and sometimes the first question suggestion is directly in English.

**Comment by EvenYan** [comment]
I have fix the problem locally, and I am happy to contribute my code. [https://github.com/crazywoola](@crazywoola)[https://github.com/guchenhe](https://github.com/guchenhe)
