### ISSUE TITLE
Let AI decide which APIs to call

### ISSUE THREAD

**Issue by chrischjh** [langgenius/dify#6235]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

For my scenario, I got multiple APIs to call, I'd like to let AI decide which one to call based on user's prompt, specifically, LLM would extract the input fields from user's prompt, and call the most aproperiate API from the given API list (such as an OpenAPI spec).

The idea is doable as proved where I just let the LLM to dicrectly generate the Python or JavaScript scripts, then pass it to a code runner to execute with `eval()`.

Before execute the `eval()`, I even have to remove the markdown tags (which returned by the LLMs along with the scripts) with another code runner ... LoL.

There must be a more graceful way to do it, please help me, thanks  a lot.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
For automatically call the api, you can use agent type to fulfill this feature. See this [link](https://docs.dify.ai/guides/application-orchestrate/agent) for more details.
