### ISSUE TITLE
base64 image show

### ISSUE THREAD

**Issue by qiuban007** [langgenius/dify#6239]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I attempted to use the platform to execute an HTTP request to access a third-party interface, but the interface responded with an image in Base64 format. I am unable to convert this Base64 image to a file on the platform because the reply only supports files. During the process, I attempted to use a code node to convert this Base64 image to a file, but found that the code node output does not support files. This is frustrating because I am unable to process and use the required image files.May I ask how I can solve this

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by qiuban007** [comment]
May I ask how I can solve this

**Comment by crazywoola** [comment]
We will add file support next month. See this for more information.

**Comment by qiuban007** [comment]
> 我们将在下个月添加文件支持。请参阅此处了解更多信息。
ok, thank you
