### ISSUE TITLE
The generation of api_base_url parameter value is inconsistent with the browser

### ISSUE THREAD

**Issue by haoqi6677** [langgenius/dify#6240]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The page addresses opened after clicking these buttons are the same problem
![image](https://github.com/user-attachments/assets/27f71763-36b4-4cae-a04b-d40907006d78)

![image](https://github.com/user-attachments/assets/270800e0-d4ad-4a0f-91e0-ec0a6266534b)

### ✔️ Expected Behavior

The address connection generated by api_base_url is consistent with the browser

### ❌ Actual Behavior

The generation of api_base_url parameter value is inconsistent with the browser

**Comment by crazywoola** [comment]
See
