### ISSUE TITLE
HTTP Request utility does not work (timeout) on a self-hosted environment. 

### ISSUE THREAD

**Issue by saendu** [langgenius/dify#6244]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Setup: 
- Use the Terraform Template described in the readme: https://github.com/langgenius/dify?tab=readme-ov-file#using-terraform-for-deployment

1. Create a workflow
2. Use a HTTP Request (GET) e.g. https://jsonplaceholder.typicode.com/todos/1
3. Run the workflow

### ✔️ Expected Behavior

- HTTP request working correctly
- Get response from the HTTP request
- Not falling into a timeout

### ❌ Actual Behavior

Node HTTP Request run failed: [Errno 110] Connection timed out

![image](https://github.com/user-attachments/assets/132c9e52-d6eb-450a-8270-795905bc7cbb)

**Comment by crazywoola** [comment]
I guess this is not related to terraform settings.

Maybe you can try to set these 2 variables to blank. 

https://github.com/langgenius/dify/blob/079583eaa474e5c26716f093b9a821cad82b80c5/docker/docker-compose.yaml#L267-L268

**Comment by saendu** [comment]
Hi guys. Thank you so much for the prompt reply. I can confirm that removing ``SSRF_PROXY_HTTP_URL`` and ``SSRF_PROXY_HTTPS_URL ``  from the api container did indeed work. 

In the codebase I can see that they are used to avoid SSRF (see ssrf_proxy.py). Would be great if anybody could confirm that is is not necessary when using Azure infrastructure. I guess the ssrfproxy container then would be obsolete.

**Comment by crazywoola** [comment]
@saendu @gijigae 
[Workflow Timeout In Details.yml.zip](https://github.com/user-attachments/files/16249666/Workflow.Timeout.In.Details.yml.zip)
These variables confuse me as well, So I made a example workflow with some notes in it. Hope this could help.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6304

**Comment by saendu** [comment]
Not sure if it is related to the ssrf proxy issue, but creating 'knowledge' (embeddings) do also not work.

**Comment by crazywoola** [comment]
> Not sure if it is related to the ssrf proxy issue, but creating 'knowledge' (embeddings) do also not work.
> 
> ** UPDATE 2: 25.7. ** Issue resolved again. The above problem was only temporary.
> 
> **UPDATE 1: ** My tests showed that creating embeddings is stuck, with or without the SSRF_PROXY_HTTPS_URL variables.

I guess the embedding server is not responding somehow.
