### ISSUE TITLE
Use ollama model "moondream" to do a vision predition , dify returns an  error :<DETAIL.LOW: 'low'>)] is not valid

### ISSUE THREAD

**Issue by nne998** [langgenius/dify#6247]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Use ollama model "moondream" to do a vision predition , dify got this error : 

<DETAIL.LOW: 'low'>)] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

### 2. Additional context or comments

model url : https://ollama.com/library/moondream

DSL file :
[moondream_1.8b_test.yml.zip](https://github.com/user-attachments/files/16192544/moondream_1.8b_test.yml.zip)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by nne998** [comment]
F**K  the dosu bot 👎 ?

**Comment by crazywoola** [comment]
Please be kind to the bot.
