### ISSUE TITLE
App times out that does not display output

### ISSUE THREAD

**Issue by chenqianhe** [langgenius/dify#6256]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The expected output of short text is output normally in the App, but the expected output of long text workflow has no output in the App after running normally, while the log is normal.

<img width="1707" alt="image" src="https://github.com/user-attachments/assets/94bb6c89-3405-4188-ad69-db3efb6fe9a2">

[Translate (Long Text).yml.zip](https://github.com/user-attachments/files/16201661/Translate.Long.Text.yml.zip)

### ✔️ Expected Behavior

Normal output

### ❌ Actual Behavior

No output

**Comment by crazywoola** [comment]
I used this DSL to test it out, but it seems I can not reproduce this problem.

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/d8611d88-1872-4a95-a9c7-8ff8e6715b2d">

**Comment by chenqianhe** [comment]
> I used this DSL to test it out, but it seems I can not reproduce this problem.
> 
> <img alt="image" width="1679" src="https://private-user-images.githubusercontent.com/100913391/348467537-d8611d88-1872-4a95-a9c7-8ff8e6715b2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjkyMzYsIm5iZiI6MTcyMDg2ODkzNiwicGF0aCI6Ii8xMDA5MTMzOTEvMzQ4NDY3NTM3LWQ4NjExZDg4LTE4NzItNGE5NS1hOWM3LThmZjhlNjcxNWIyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxMTA4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmI4MmYxODM1MDdlOTU5OWY3MjllZWExNTc2ZGVjYzIxNWUyNjY0MzkwNzMwZDZiNzhjMTZmN2JlOWNlOGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KN_384N5SC9qtolMdfghUvjRCoevcmKtWbpj012qaKs">

Use long long long content. Maybe thousand words

**Comment by chenqianhe** [comment]
> I used this DSL to test it out, but it seems I can not reproduce this problem.
> 
> 
> 
> <img width="1679" alt="image" src="https://github.com/user-attachments/assets/d8611d88-1872-4a95-a9c7-8ff8e6715b2d">
> 
> 

Have you tried long long content or do you need more information？

**Comment by crazywoola** [comment]
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/c3c6bf26-cc80-4b86-a7ae-33a3b85894bf">
I guess some of them are timeout. It could lead to this error.

**Comment by chenqianhe** [comment]
> <img alt="image" width="1291" src="https://private-user-images.githubusercontent.com/100913391/349112986-c3c6bf26-cc80-4b86-a7ae-33a3b85894bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDA4MDMsIm5iZiI6MTcyMTE0MDUwMywicGF0aCI6Ii8xMDA5MTMzOTEvMzQ5MTEyOTg2LWMzYzZiZjI2LWNjODAtNGI4Ni1hN2FlLTMzYTNiODU4OTRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxNDM1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTJjNjU0MTUxM2QwZGU1N2M1MzIzZjllM2JhMWY4OWU1ZDUxZGFiYzFjZGY4YjhiNWVjYjhiMTJmYzNiMjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHm4UaccCF7ztqUwuogi8ZTdv7-YIL1N29KSFl6gywQ"> I guess some of them are timeout. It could lead to this error.

I'm not sure if your reply is mixed up.

**Comment by chenqianhe** [comment]
> > <img alt="image" width="1291" src="https://private-user-images.githubusercontent.com/100913391/349112986-c3c6bf26-cc80-4b86-a7ae-33a3b85894bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDA4MDMsIm5iZiI6MTcyMTE0MDUwMywicGF0aCI6Ii8xMDA5MTMzOTEvMzQ5MTEyOTg2LWMzYzZiZjI2LWNjODAtNGI4Ni1hN2FlLTMzYTNiODU4OTRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxNDM1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTJjNjU0MTUxM2QwZGU1N2M1MzIzZjllM2JhMWY4OWU1ZDUxZGFiYzFjZGY4YjhiNWVjYjhiMTJmYzNiMjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHm4UaccCF7ztqUwuogi8ZTdv7-YIL1N29KSFl6gywQ"> I guess some of them are timeout. It could lead to this error.
> 
> I'm not sure if your reply is mixed up.

Oh I see. So what should we do to fix this?

**Comment by crazywoola** [comment]
There is no way to fix this on Cloud version I guess. See #6244 in self-hosted version you could achieve it by changing those environment variables. However, we do not support editing those environment variables on Cloud version.
Anyway, I will keep trying to see current process's duration is necessary to change in this case.

Can I ask how long do you take for completing the empty response workflow run in avg?

**Comment by chenqianhe** [comment]
> There is no way to fix this on Cloud version I guess. See #6244 in self-hosted version you could achieve it by changing those environment variables. However, we do not support editing those environment variables on Cloud version. Anyway, I will keep trying to see current process's duration is necessary to change in this case.
> 
> Can I ask how long do you take for completing the empty response workflow run in avg?

Generally, more than 120s

**Comment by chenqianhe** [comment]
I don't understand why the online cloud service timeout is not longer after allowing loop nodes. Loop nodes allow for more complex operations, so the timeout should be longer. Or should payment be allowed in exchange for a longer timeout?

**Comment by crazywoola** [comment]
See this discord thread https://discord.com/channels/1082486657678311454/1261378430780571808 @iamjoel @iamjoel @zxhlyh

**Comment by shuai-huaman** [comment]
@chenqianhe 请问最后解决了吗，云版本怎么处理这个超时时间
