### ISSUE TITLE
Missing line break for multiple workflow end results

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#6264]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I have three results in the End node, each is a text output. When running the test AND the published workflow, there is a missing line break between the three text outputs, making it hard to tell one output from another:

<img width="374" alt="Screenshot 2024-07-14 at 7 34 21 AM" src="https://github.com/user-attachments/assets/68d1e341-dd68-4e67-9764-e35af85215d5">

<img width="964" alt="Screenshot 2024-07-14 at 7 35 40 AM" src="https://github.com/user-attachments/assets/f27b0582-33dd-4f68-a23d-2f79ece14f97">

<img width="2321" alt="Screenshot 2024-07-14 at 7 30 14 AM" src="https://github.com/user-attachments/assets/acf56f92-e079-4b4f-942f-32813937fe53">

<img width="2356" alt="Screenshot 2024-07-14 at 7 30 22 AM" src="https://github.com/user-attachments/assets/edd6098f-b2e9-448f-ae36-fdd0b5f557c5">

### ✔️ Expected Behavior

there should be a line break between different outputs.

### ❌ Actual Behavior

missing line break.

**Comment by crazywoola** [comment]
Thanks for this suggestion, however you can use [jinja](https://docs.dify.ai/guides/workflow/node/template) template to fulfill this need.  In this case , you could achieve more complex layout design.

**Comment by harrywang** [comment]
> Thanks for this suggestion, however you can use [jinja](https://docs.dify.ai/guides/workflow/node/template) template to fulfill this need. In this case , you could achieve more complex layout design.

Thanks - any example on how to do this using jinja?

**Comment by harrywang** [comment]
<img width="586" alt="Screenshot 2024-07-15 at 7 24 04 AM" src="https://github.com/user-attachments/assets/3352eb8a-00ee-43d8-9cde-2b6a07546333">

@crazywoola I used the jinjia template to format the results - it works but the result only shows once the workflow completes. The LLM nodes won't stream results while running. A line break is still needed for streaming results I guess.
