### ISSUE TITLE
Rapidly calling the create_by_text API to synchronize large amounts of data can result in slow synchronization and a sudden increase in disk storage usage.

### ISSUE THREAD

**Issue by kolagood** [langgenius/dify#6269]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

This is the second time I’ve called the API endpoint (/datasets/{dataset_id}/document/create_by_text) in bulk to synchronize over 30,000 records. After waiting for nearly 24 hours for the knowledge base indexing to complete, the storage usage suddenly skyrocketed, filling up my hard drive. My data partition previously had 600GB of free space. The entire dataset to be synchronized consists of TXT files, totaling no more than 20GB.

The first time, when I tried to synchronize over 20,000 records, the same issue occurred. After freeing up some space and allowing it to grow slowly, it completed synchronization. About a day later, the storage usage automatically decreased. Is this because some logs were deleted?

Upon investigation, I found that the large storage usage is located here.
![image](https://github.com/user-attachments/assets/dd2844ae-47f9-4159-88ac-2bb63770762c)
![image](https://github.com/user-attachments/assets/d463dd94-bb16-43f0-a444-ebac34e53144)

### ✔️ Expected Behavior

Disk storage usage must not be too large  and  build embedding fast.

### ❌ Actual Behavior

build emb slowly and  disk too large to 100%

**Comment by kolagood** [comment]
Can I delete these pgdata files without affecting the data I am currently indexing into the database?

**Comment by JohnJyong** [comment]
pls provide the vector db you are using and confirm the storage is used by the vdb or other program

**Comment by kolagood** [comment]
> pls provide the vector db you are using and confirm the storage is used by the vdb or other program

I use docker-compose to start up, the  vector db is "semitechnologies/weaviate:1.19.0"，pg is "postgres:15-alpine"，redis is “redis:6-alpine”。 The largest size of folder is in pgdata.

**Comment by secsilm** [comment]
same issue. why is this closed?
