### ISSUE TITLE
squid版本存在漏洞

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#6270]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

我使用ubuntu/squid:latest docker镜像，但其中的squid版本为6.1，官方版本6.4之前存在安全漏洞

### ✔️ Expected Behavior

是否有squid>6.4的镜像，或者如何修复该镜像中的漏洞

**Comment by crazywoola** [comment]
Close due to #1542 for security report please send email to security@dify.ai.
