### ISSUE TITLE
There is a vulnerability in the Squid version

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#6272]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I use Ubuntu/Squid: latest Docker image, but the Squid version is 6.1, which has a security vulnerability before the official version 6.4

### ✔️ Expected Behavior

Is there an image with Squid>6.4, or how to fix vulnerabilities in that image

**Comment by 401557122** [comment]
It seems that there is no Docker image named Ubuntu/Squid: 6.4@dosu

**Comment by crazywoola** [comment]
Please contact security@dify.ai to submit this report.
