### ISSUE TITLE
The created knowledge base is not visible

### ISSUE THREAD

**Issue by leeyis** [langgenius/dify#6275]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Step 1: Enter the knowledge base page and create a knowledge base.
- Step 2: Upload local documents, totaling approximately 2000 Markdown documents, uploaded in two batches, this process will be very lengthy.
- Step 3: Refresh the knowledge base page, but the knowledge base list is empty.
- Step 4: Enter the studio page, after creating a new blank application, in the context settings section, choose the knowledge base, you can see that the knowledge base created in step 1 can be selected (over 14 million words).

### ✔️ Expected Behavior

A knowledge base with over ten million words is still visible and accessible as normal.

### ❌ Actual Behavior

A knowledge base containing an excessively large number of characters is not visible.

**Comment by leeyis** [comment]
1.The knowledge base has been successfully created but it is not visible.
![image](https://github.com/user-attachments/assets/7328a024-3b43-4c2a-903b-59244b6d3609)
2.When creating an application, the invisible knowledge base can be selected.
![image](https://github.com/user-attachments/assets/e4e73531-31d3-40ec-a08b-7ea60d677ef6)

**Comment by crazywoola** [comment]
Can you provide the logs of the api and worker? I can not reproduce this problem.

**Comment by leeyis** [comment]
Here is a screenshot of the current issue, and additionally, an important piece of information: my vector database is `pgvector`.
![image](https://github.com/user-attachments/assets/ebcacf30-1208-4276-9883-5cd6a807c9a5)
