### ISSUE TITLE
Abnormal display of node variables in workflow

### ISSUE THREAD

**Issue by jx2011** [langgenius/dify#6276]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Cloud

### Steps to reproduce

- step1: Create a workflow with only a start node and an answer node.
- step2: Insert variables into the answer node content.
- step3: Switch browser tab pages to other pages and then back again.
<img width="1080" alt="variables error" src="https://github.com/user-attachments/assets/4704af15-538a-41c7-9258-c3a5c5b23e09">

### ✔️ Expected Behavior

Variable display normal

### ❌ Actual Behavior

Variable display exception

<img width="1080" alt="variables error" src="https://github.com/user-attachments/assets/f27a212d-4dc1-40e0-819b-748f0626780d">

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/6277

**Comment by Bruse-Lee** [comment]
Has this issue been resolved? What's the solution?
