### ISSUE TITLE
Request for Asynchronous Interface in Python Client

### ISSUE THREAD

**Issue by imgaojun** [langgenius/dify#6285]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello Dify team,

I'm a Python developer and a user of your API. I really appreciate the work you've done in providing a Python client for interacting with your services. However, I've noticed that the current implementation lacks support for asynchronous operations, which can be beneficial in certain scenarios, especially when dealing with long-running tasks or high concurrency.

I would like to request the addition of an asynchronous interface to your Python client. This could be implemented as a separate class or as an optional mode within the existing client. The asynchronous interface should support all the existing methods, allowing developers to make non-blocking requests and handle responses asynchronously.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by StudyingLover** [comment]
Do you mean async? I think you can send a http req by this way
```python
import aiohttp

url = your_url
data = your_data

class ClientSessionSingleton:
    _session = None

    @classmethod
    def get_session(cls):
        if cls._session is None or cls._session.closed:
            cls._session = aiohttp.ClientSession()
        return cls._session

    @classmethod
    async def close_session(cls):
        if cls._session is not None:
            await cls._session.close()
            cls._session = None


def session():
    return ClientSessionSingleton.get_session()

async with session().post(url, data=data) as resp:
    try:
            response = await resp.json()
        except Exception as error:
            pass
    # do some thing
```
