### ISSUE TITLE
RetryError state=finished raised APIReachLimitError when validate the zhipu ai

### ISSUE THREAD

**Issue by Onelevenvy** [langgenius/dify#6289]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Step 1: Set the API key for Zhipu AI.
Step 2: Wait for the validation result.
![image](https://github.com/user-attachments/assets/c4460060-7dc2-4910-b467-d94919d5a83f)
Step 3: Raise an "APIReachLimitError" exception. However, when I use the same API key in LangChain, it works.

The reason is that the zhipu ai api key for the new account may not support chatglm_turbo. https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/zhipuai/zhipuai.py  line 23
![image](https://github.com/user-attachments/assets/6f788989-e8cd-47bf-bf11-ee28b444419d)
![image](https://github.com/user-attachments/assets/801ea0b7-7020-4063-b931-4da0bbeb9a58)

I changed the model to glm4, it works.
![image](https://github.com/user-attachments/assets/535b36e4-556b-4db3-a72c-bcda926e4d0a)

### ✔️ Expected Behavior

validate success

### ❌ Actual Behavior

validate failed

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/pull/5469

**Comment by Onelevenvy** [comment]
Perhaps this issue Link #5850  is also caused by the same reason.
