### ISSUE TITLE
The document in the knowledge base has picture information. Why is the picture information not in the paragraph when it is segmented?

### ISSUE THREAD

**Issue by TonyChenBS** [langgenius/dify#6296]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Upload a document with images and then segment it into sections

### ✔️ Expected Behavior

Images can be divided into paragraphs

### ❌ Actual Behavior

The image was not divided into paragraphs

**Comment by crazywoola** [comment]
This is a known issue, we haven't support extract image from PDF yet.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6280

**Comment by VincePotato** [comment]
Please provide more background information on this requirement, such as specific use cases or scenarios. This will help the dify product team better understand the user stories.

**Comment by create-my** [comment]
The explanatory power of text is not enough, and images can be better used as help documents.
