### ISSUE TITLE
Invalid interpolation format for "LOG_LEVEL" option in service "x-shared-env": "${LOG_LEVEL:-INFO}"

### ISSUE THREAD

**Issue by WHG555** [langgenius/dify#6297]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

smile@pc:~/git$ git clone https://github.com/langgenius/dify.git
正克隆到 'dify'...
remote: Enumerating objects: 69934, done.
remote: Counting objects: 100% (14273/14273), done.
remote: Compressing objects: 100% (1396/1396), done.
remote: Total 69934 (delta 13413), reused 12970 (delta 12876), pack-reused 55661
接收对象中: 100% (69934/69934), 38.59 MiB | 9.71 MiB/s, 完成.
处理 delta 中: 100% (50800/50800), 完成.
smile@pc:~/git$ cd dify/
smile@pc:~/git/dify$ git checkout 0.6.13
注意：正在切换到 '0.6.13'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
中添加参数 -c 来实现（现在或稍后）。例如：

  git switch -c <新分支名>

或者撤销此操作：

  git switch -

通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议

HEAD 目前位于 17f22347a bump to 0.6.13 (#6078)
smile@pc:~/git/dify$ cd docker
smile@pc:~/git/dify/docker$ la
docker-compose.middleware.yaml  docker-compose.yaml  middleware.env.example  README.md   startupscripts
docker-compose.png              .env.example         nginx                   ssrf_proxy  volumes
smile@pc:~/git/dify/docker$ docker-compose up -d
ERROR: Invalid interpolation format for "LOG_LEVEL" option in service "x-shared-env": "${LOG_LEVEL:-INFO}"
smile@pc:~/git/dify/docker$ 

### ✔️ Expected Behavior

start run

### ❌ Actual Behavior

Invalid interpolation format for "LOG_LEVEL" option in service "x-shared-env": "${LOG_LEVEL:-INFO}"

**Comment by crazywoola** [comment]
Please provide docker version and docker compose version.

**Comment by WHG555** [comment]
```
smile@pc:~$ docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

```
smile@pc:~$ docker version
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:29 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:29 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by crazywoola** [comment]
Please upgrade to latest docker compose.
