### ISSUE TITLE
Webhook 的想法很好诶，做的咋样了？

### ISSUE THREAD

**Issue by Toby21UnderStars** [langgenius/dify#63]
如果 webhook 优先级比较低的话，我可以帮忙写写。

**Comment by yuhao1118** [comment]
> 如果 webhook 优先级比较低的话，我可以帮忙写写。

你好toby，如果有需要，我也可以一块儿写写

**Comment by takatost** [comment]
可以说说你们的使用场景哈😁

**Comment by yuhao1118** [comment]
> 可以说说你们的使用场景哈😁

想要gitlab/github push代码触发webhook生成代码数据集。然后可以定制一个应用，回答代码仓库里的问题或者可以让gpt帮忙写api文档

**Comment by takatost** [comment]
> > 可以说说你们的使用场景哈😁
> 
> 想要gitlab/github push代码触发webhook生成代码数据集。然后可以定制一个应用，回答代码仓库里的问题或者可以让gpt帮忙写api文档

很好的场景，代码是希望以纯文本形式发送到 webhook 吗

**Comment by yuhao1118** [comment]
> > > 可以说说你们的使用场景哈😁
> > 
> > 想要gitlab/github push代码触发webhook生成代码数据集。然后可以定制一个应用，回答代码仓库里的问题或者可以让gpt帮忙写api文档
> 
> 很好的场景，代码是希望以纯文本形式发送到 webhook 吗 

- 短期可以用 webhook 直接发送纯文本代码到数据集。
- 长期是否可以考虑在导入数据集的位置新增“从git仓库导入”的功能，这样很多开源项目的文档就可以一键导入了

**Comment by ChangeHow** [comment]
如果需要帮助我也可以参与开发，我这边也有遇到这种场景，非常困扰，如果能够实现，而且代码安全啥的能做的好些，文档就不会严重落后于代码了～ 😄

**Comment by qianxuemin** [comment]
> 如果需要帮助我也可以参与开发，我这边也有遇到这种场景，非常困扰，如果能够实现，而且代码安全啥的能做的好些，文档就不会严重落后于代码了～ 😄

文档落后于代码这个问题通过AI会以什么形式解决诶，想请教下思路

**Comment by coolnetboy** [comment]
> > > > > 可以说说你们的使用场景哈😁
> > > > 
> > > > 
> > > > 想要gitlab/github push代码触发webhook生成代码数据集。然后可以定制一个应用，回答代码仓库里的问题或者可以让gpt帮忙写api文档
> > > 
> > > 
> > > 很好的场景，代码是希望以纯文本形式发送到 webhook 吗
> > 
> > 
> > 
> > * 短期可以用 webhook 直接发送纯文本代码到数据集。
> > * 长期是否可以考虑在导入数据集的位置新增“从git仓库导入”的功能，这样很多开源项目的文档就可以一键导入了
> 
> 嗯，应该 OK 的，导入配合 webhook 实现了自动同步，我们先写到需求池

我也可以参与开发啊

**Comment by MercuryLiRC** [comment]
看起来这个需求还没有实现，是否需要reopen这个issue?

**Comment by TangSY** [comment]
看起来这个需求还没有实现，是否需要reopen这个issue?

**Comment by DoiiarX** [comment]
我觉得需要？
