### ISSUE TITLE
Timeout Issue When Uploading .txt File to Dataset via API

### ISSUE THREAD

**Issue by oeleitorai** [langgenius/dify#6308]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I am encountering a timeout error when uploading a .txt file to a dataset via API on Dify.Ai. The Get Document Embedding Status API call returns an error, and I encounter the same issue when using the platform directly.

To Reproduce

## Steps to reproduce the behavior:
1. Upload a .txt file via the API.
2. Use the Get Document Embedding Status API to check the status.
3. Encounter a timeout error with the following response:

```
[
  {
    "data": [
      {
        "id": "3d209c53-c5d2-4b0c-9f7e-df5f47c6b687",
        "indexing_status": "error",
        "processing_started_at": 1721087282,
        "parsing_completed_at": 1721087283,
        "cleaning_completed_at": 1721087284,
        "splitting_completed_at": 1721087284,
        "completed_at": null,
        "paused_at": null,
        "error": "timed out",
        "stopped_at": 1721098004,
        "completed_segments": 0,
        "total_segments": 79
      }
    ]
  }
]
```
Screenshots

Desktop (please complete the following information):

OS: [e.g. Windows 10, macOS Catalina]
Browser [e.g. Chrome, Firefox]

## Additional context

The .txt file size is 69180
The connection to the internet is stable.

### ✔️ Expected Behavior

The .txt file should be successfully uploaded and embedded without a timeout error.

### ❌ Actual Behavior

s

**Comment by jiaruisong** [comment]
I ran into the same issue while uploading a 0.60MB csv file. Timed out while Embedding. Here's the file for reference.
[API_IND_DS2_en_csv_v2_750757.csv](https://github.com/user-attachments/files/16242923/API_IND_DS2_en_csv_v2_750757.csv)

**Comment by crazywoola** [comment]
> I ran into the same issue while uploading a 0.60MB csv file. Timed out while Embedding. Here's the file for reference. [API_IND_DS2_en_csv_v2_750757.csv](https://github.com/user-attachments/files/16242923/API_IND_DS2_en_csv_v2_750757.csv)

Are you using the HTTP node to upload this file as well?

**Comment by jiaruisong** [comment]
> > I ran into the same issue while uploading a 0.60MB csv file. Timed out while Embedding. Here's the file for reference. [API_IND_DS2_en_csv_v2_750757.csv](https://github.com/user-attachments/files/16242923/API_IND_DS2_en_csv_v2_750757.csv)
> 
> Are you using the HTTP node to upload this file as well?

No I'm using dify.ai website. And the website doesn't have timeout message so it was a bit more tricky to figure out what was wrong.
