### ISSUE TITLE
Save generated content in local

### ISSUE THREAD

**Issue by silver0919** [langgenius/dify#6312]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I use the workflow to generate some content including sheet，and I want to copy the generated content into the word file，but the sheet cant keep original format. How can I save the content in a file(like word) and keep the original format of sheet.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can use an external http service to receive the payload from the node and create a download url.
