### ISSUE TITLE
Using the knowledge base as context, the bot will do not respond.

### ISSUE THREAD

**Issue by louis-redotpay** [langgenius/dify#6316]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The app ID:cfabe94d-1fa7-4c20-8f71-debc27f99ac6
Test Conversation ID1: a93d66f3-eb67-4f1e-a412-66b6fce2877d
Used the knowledge base, the bot did not respond.
Test Conversation ID2: da3b78af-831a-4348-be53-517c6e12a3e7
Deleted the knowledge base, the bot responded.
This situation only occurred on 7/16; it was working normally before that.I am not sure if it is related to upgrading to version 0.6.14.If the official team could conduct an inspection, I would be very grateful.

**Comment by crazywoola** [comment]
We are investigating this issue.

**Comment by crazywoola** [comment]
It has been fixed now.
