### ISSUE TITLE
Starting from July 15th, the Jina model in the knowledge base is unavailable. Is it due to the Dify upgrade or what causes the Jina model to be unavailable? Thanks

### ISSUE THREAD

**Issue by Sam-gz** [langgenius/dify#6322]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Jina not work

**Comment by crazywoola** [comment]
It's related to https://github.com/langgenius/dify/issues/6316.

**Comment by Sam-gz** [comment]
![Jina](https://github.com/user-attachments/assets/b985de05-6a86-437e-aedb-0e1bc26f50d4)

I chose Jina as the Embedding Model, and the created knowledge base is displayed in the queue. I checked the method you provided above, and I confirmed that it was a fault in the Dify backend.
