### ISSUE TITLE
Invoke AWS Bedrock Mistral model have issues

### ISSUE THREAD

**Issue by SIN1109** [langgenius/dify#6323]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create chatbot agent in Studio without any PE, just type in "hello" in the chat. It will response errror:

[bedrock] Error: An error occurred (validationException) when calling the InvokeModelWithResponseStream operation: Validation Error

It will have issues for both

mistral.mistral-7b-instruct-v0:2
mistral.mixtral-8x7b-instruct-v0:1

Also tested Claude3 Sonnet and Titan amazon.titan-text-express-v1 without issues.

The AK/SK and region also been validated.

### ✔️ Expected Behavior

Can use Mistral model in dify.ai via bedrock integrations

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/b7b05a8d-1bbb-4dd1-9dd6-534eff8c3558)

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/pull/6299
