### ISSUE TITLE
I want to add an executor node, and after everything is set up, the next node cannot reference the output of this node.

### ISSUE THREAD

**Issue by likenamehaojie** [langgenius/dify#6331]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/b5e40fe4-2c6e-42c7-aebc-1c9d6c4e9e21">
I want to add an executor node, and after everything is set up, the next node cannot reference the output of this node.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
What's the result of the `SQL Node`? I guess it's neither `string` type nor `Array[file] `type. So in this case, you need to flatten this node's result into a string by using a jinja node or code node to extract the results.

**Comment by likenamehaojie** [comment]
<img width="738" alt="image" src="https://github.com/user-attachments/assets/d8dea05e-f064-492d-94fc-0a03adc38193">
I have resolved the issue of configuring whether a node has output properties in the frontend code.@crazywoola
