### ISSUE TITLE
I chose Jina as the Embedding Model, and the created knowledge base is displayed in the queue. I checked the method you provided above, and I confirmed that it was a fault in the Dify backend.

### ISSUE THREAD

**Issue by Sam-gz** [langgenius/dify#6336]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![Jina](https://github.com/user-attachments/assets/504578d3-7a1c-47e1-a883-e67189fd7528)

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6322

**Comment by crazywoola** [comment]
Fixed, our storage is full, we have cleaned some old data to make sure things going well.
