### ISSUE TITLE
Flutter: text-to-audio api is not working: Error: The status code of 500 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"

### ISSUE THREAD

**Issue by abdullah432** [langgenius/dify#6339]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I implemented dify API for chat, vision, audio-to-text. It's all work good.

When I try to do text-to-audio then it's throwing following Exception.
```
This exception was thrown because the response has a status code of 500 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 500 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```

I'm working on this from second day, so tried 100's of different ways, will share two below, which I think should work good.

First: Pass data with FormData as documentation mentioned it.
```
  Future<void> textToAudio({
    required String text,
    required String user,
    required bool streaming,
  }) async {
    const String url = 'https://api.dify.ai/v1/text-to-audio';
    var secretKey = "app-RaxAShID6WHEcy8PUo9PRuKY";

    try {
      var _dio = Dio();
      final response = await _dio.post(
        url,
        options: Options(
          headers: {
            'Authorization': 'Bearer $secretKey',
            'Content-Type': 'multipart/form-data',
          },
        ),
        data: FormData.fromMap({
          'text': text,
          'user': user,
          'streaming': streaming.toString(),
        }),
      );
      print(response.data);
    } on DioException catch (e) {
      print('Request failed with status: ${e.response?.statusCode}');
      print('Error: ${e.message}');
    }
  }
```

Second: with simple map form, in case server expect it that way. Also test with ` "Content-Type": "audio/wav" ` but it didn't help.
```
  Future<void> textToAudio({
    required String text,
    required String user,
    required bool streaming,
    required String secretKey,
  }) async {
    const String url = 'https://api.dify.ai/v1/text-to-audio';
    
    try {
      final response = await _dio.post(
        url,
        options: Options(
          headers: {
            'Authorization': 'Bearer $secretKey',
            'Content-Type': 'application/json',
          },
        ),
        data: {
          'text': text,
          'user': user,
          'streaming': streaming,
        },
      );
      print(response.data);
    } on DioException catch (e) {
      print('Request failed with status: ${e.response?.statusCode}');
      print('Error: ${e.message}');
      if (e.response != null) {
        print('Response data: ${e.response?.data}');
      }
    }
  }
```

### A look into my dify console.
<img width="1512" alt="Screenshot 2024-07-16 at 3 08 09 PM" src="https://github.com/user-attachments/assets/8a696dc2-b492-44f0-b459-2b96ecfb05b4">

Can you help me what could be the problem. At dify console text to voice is working good.

### ✔️ Expected Behavior

Text should get converted to audio.

### ❌ Actual Behavior

I'm getting Exception while calling the API.

**Comment by crazywoola** [comment]
@charli117 Could you take a look at this one?

**Comment by charli117** [comment]
@crazywoola I'll fix a small problem

**Comment by abdullah432** [comment]
@crazywoola I'm still getting same problem, can you help me fixed it. Am I doing something wrong the way I'm calling the API?

**Comment by abdullah432** [comment]
@crazywoola @charli117 there is no way to mark this un-completed, should I file new issue because issue is not solved for me yet?
