### ISSUE TITLE
How can I add some blocking of user input during workflow execution? Just like autogen

### ISSUE THREAD

**Issue by fwasdfw** [langgenius/dify#6343]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In the process of performing my work, due to my limited local LLM capabilities, I hope to be able to add human blocking when executing in some of these places, and improve the execution process through human input
Of course, I'm also looking for ways to show some of the results of the execution in the middle when executing the workflow. Instead of just giving me some results

### 2. Additional context or comments

![e55db29c4242ea1199cc0c3c7a11716](https://github.com/user-attachments/assets/27023e88-f108-4b18-b90f-c4c58eb88f89)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by nhha1602** [comment]
Do we support it ?
