### ISSUE TITLE
How to use the Embedding Model and rerank model deployed with docker in dify

### ISSUE THREAD

**Issue by MdcGIt** [langgenius/dify#6358]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

How to use the Embedding Model and rerank model deployed with docker in dify？ 

I deployed the m3e model and bge-reranker model using docker. How to integrate them into dify?

**Comment by crazywoola** [comment]
Wrong template, for questions, please head to discussions.
