### ISSUE TITLE
docker compose deploy, no Weaviate container

### ISSUE THREAD

**Issue by npe2023** [langgenius/dify#6363]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

local docker compose deploy, not found Weaviate container, what went wrong?

### ✔️ Expected Behavior

should have Weaviate container

### ❌ Actual Behavior

<img width="804" alt="image" src="https://github.com/user-attachments/assets/88f4dd6d-7773-4d6d-9b28-ec0db65299eb">

**Comment by npe2023** [comment]
fixed. 

your document never mention to copy the `.env.example` file in the docker folder. please update the document when u have time. 

thanks.

**Comment by crazywoola** [comment]
Which do

**Comment by npe2023** [comment]
check the chinese edition

**Comment by npe2023** [comment]
https://docs.dify.ai/getting-started/install-self-hosted/local-source-code

this section doesn't mention

**Comment by npe2023** [comment]
@crazywoola one more thing , is there any GUI IDE to connect to weaviate, like any other database so i can view、query the data ?
