### ISSUE TITLE
Assist multi-space users in quickly searching spaces.

### ISSUE THREAD

**Issue by crtan7** [langgenius/dify#6364]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When you have a lot of space, finding trouble one by one can become convenient by adding a search at the top.

![image](https://github.com/user-attachments/assets/db2647bd-1938-496f-b32e-53ff859adc67)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Which version are you referring to? Cloud or self-hosted. We do not have multiple workspace for self-hosted version. I guess you are talking about the Cloud version?

**Comment by crtan7** [comment]
yep&nbsp;


crtan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月17日(星期三) 中午1:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [langgenius/dify] Assist multi-space users in quickly searching spaces. (Issue #6364)














 
Which version are you referring to? Cloud or self-hosted. We do not have multiple workspace for self-hosted version. I guess you are talking about the Cloud version?

**Comment by Hanfee** [comment]
如何部署云版本？
