### ISSUE TITLE
【bug】failed to load response data:No data found for resource with given  identifier

### ISSUE THREAD

**Issue by ForgetThatNight** [langgenius/dify#6365]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud

### Steps to reproduce

None of the interfaces received any request after open website  
My web/docker-compose.middleware.yaml/ api are installed in remote server. 
open website http://gpu-2088:3000/install in my computer
![image](https://github.com/user-attachments/assets/4ae35adf-3a82-4056-8907-831bf340ff63)
![image](https://github.com/user-attachments/assets/cb4ba5b2-02d4-45fc-965f-61352da61da0)

### ✔️ Expected Behavior

I expected to create account to login in,but Page not responding and the daemon did not receive any error logs
this is website console 

### ❌ Actual Behavior

this is the web log
![image](https://github.com/user-attachments/assets/1ba9b9d8-67c1-46c4-8c76-c0f0f9a4106c)

**Comment by ForgetThatNight** [comment]
> The issues you're encountering seem to be related to server connectivity and potential problems in the JavaScript code handling API responses. Here are some steps to diagnose and resolve these issues:

> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I used the docker-compose.middleware.yaml instead of docker-compose.yaml
This is my step https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/local-source-code
There were no errors in the deployment process, nothing was changed, and it was done exactly as it was on the link。

**Comment by crazywoola** [comment]
Duplicated question. Please make sure you have set the right environment variables in `.env`. Especially those ends with `URL`.

Also this is not Cloud version.

**Comment by Sololololo** [comment]
Hello, I am very confused now. I deployed it locally. Should I modify the .env file or the docker-compose.yaml file? Or are the two modified simultaneously?
