### ISSUE TITLE
Knowledge base AI not allowed to execute with changed port 

### ISSUE THREAD

**Issue by jianwen095** [langgenius/dify#6367]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

We are using the API of knowledge base, but some problems occur when we follow the introduction of API website to execute it because of computer port (we had already changed our port from 80 to 8080, set EXPOSE_NGINX_PORT=8080)

### ✔️ Expected Behavior

In our backend server  we could execute API to create a empty file and get a response like this:
{
  "document": {
    "id": "",
    "position": 1,
    "data_source_type": "upload_file",
    "data_source_info": {
        "upload_file_id": ""
    },
    "dataset_process_rule_id": "",
    "name": "text.txt",
    "created_from": "api",
    "created_by": "",
    "created_at": 1695690280,
    "tokens": 0,
    "indexing_status": "waiting",
    "error": null,
    "enabled": true,
    "disabled_at": null,
    "disabled_by": null,
    "archived": false,
    "display_status": "queuing",
    "word_count": 0,
    "hit_count": 0,
    "doc_form": "text_model"
  },
  "batch": ""
}

### ❌ Actual Behavior

With recommended computer port we are not allowed to execute API
![image1](https://github.com/user-attachments/assets/5e3963f0-8218-42a3-8130-f6384089de0b)

**Comment by crazywoola** [comment]
See the bot's reply. You need to change `SERVICE_API_URL` regarding your question.
