### ISSUE TITLE
Individual link to share an app

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#6397]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to have an individual link to share an app. Currently, there is no way to point to an app by a URL, I can only tell a user to search for the app's name. It would be useful to share an app so that other users can quickly access the app. 
<img width="1546" alt="Screenshot 2024-07-17 at 11 16 13 AM" src="https://github.com/user-attachments/assets/6b053da3-58a9-43ca-baeb-b691ccd2561e">

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by harrywang** [comment]
@faye1225

**Comment by crazywoola** [comment]
Do you mean this?
<img width="938" alt="image" src="https://github.com/user-attachments/assets/780a2aec-79e6-41d6-86a4-d408928c5627">

**Comment by harrywang** [comment]
No. I want to share the template so that other users can add to their workspace, not the running app:

<img width="1546" alt="Screenshot 2024-07-17 at 11 16 13 AM" src="https://github.com/user-attachments/assets/69cf28b5-0849-44cf-8e58-d847ebcccf11">

**Comment by ethan-fly** [comment]
@harrywang If you host the Dify Service yourself, You can set your app as a template, and others can create their own apps in their workspaces using this template.
See the api `/console/api/admin/insert-explore-apps` for more details, which located in `dify/api/controllers/console/admin.py`
