### ISSUE TITLE
消息对答时会带出</histories>

### ISSUE THREAD

**Issue by xietao105** [langgenius/dify#640]
<img width="811" alt="image" src="https://github.com/langgenius/dify/assets/52532413/e3e8ddf4-f253-45b4-8f6e-12f44ada1343">

**Comment by xietao105** [comment]
> Can you share your prompt config?

default config

**Comment by kmfish** [comment]
me too

**Comment by takatost** [comment]
We've fixed and optimized the issue in the upcoming version. We also added "</histories>" as stop words, so it shouldn't happen again.

**Comment by xietao105** [comment]
> We've fixed and optimized the issue in the upcoming version. We also added "" as stop words, so it shouldn't happen again.

thank you so much!

**Comment by NonePro** [comment]
how to fix this? I split the prompt into list to fix this. I think azure's gpt-3.5 has some difference with openai.
 
<img width="772" alt="image" src="https://github.com/langgenius/dify/assets/5492842/1c6b0552-7fc3-4797-a340-020ee27a6c76">

**Comment by NonePro** [comment]
因为dif把消息历史合并到了一个用户消息的content里，这导致大模型对这个history产生了误解。azxure存在这个问题，openai没遇到这个问题。
![image](https://github.com/langgenius/dify/assets/5492842/82f29285-effc-493d-8956-eaac49c8aa96)

我们遇到的问题更夸张，大模型认为它需要生成一段对话。

所以把用户历史消息拆成了列表给大模型。想这像claude这种不支持的可以在后面再合并。
