### ISSUE TITLE
The agent chat application files were not passed in the prompt words

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#6405]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

In chat applications, if visual multimodal llm is used, the image in question (local or link) is correctly passed to llm. However, in agent chat, I correctly passed the image files parameter when calling chat message, but the back-end code seems to only contain user problems
query_messages = UserPromptMessage(content=self._ query)
Not organizing files into prompt words, nor directly passing files to visual multimodal LLM parsing

### ✔️ Expected Behavior

How can I add this file in the prompt words of the agent chat

**Comment by crazywoola** [comment]
Can you share the screenshot of the whole orchestration view?

**Comment by 401557122** [comment]
![微信截图_20240718100147](https://github.com/user-attachments/assets/784140b2-76bc-4c5a-bf1d-3c3e3a47e16e)
![微信截图_20240718100502](https://github.com/user-attachments/assets/17fde68a-000b-4747-b235-ab39b1daafee)
The first one is a chat, and the second one is an agent chat@crazywoola

**Comment by crazywoola** [comment]
Both images will not be presented in prompt. I tried upload an image and it seems fine to me as well.

**Comment by 401557122** [comment]
It seems to be in API/core/agent/cot_chat_agent_runner.py

query_messages = UserPromptMessage(content=self._ query)  
if assistant_messages:
    messages = [
        system_message,
        *historic_messages,
        query_messages,
        *assistant_messages,
        UserPromptMessage(content='continue')
]
else:
    messages = [system_message, *historic_messages, query_messages]

UserPromptMessage only contains query information and does not include the URL of files@crazywoola

**Comment by 401557122** [comment]
I have reviewed the latest version of the code and added the prompt 'files'. However, my version has not yet implemented it@crazywoola

**Comment by crazywoola** [comment]
Well, you should upgrade it to the latest version in this case. I guess this is resolved.

**Comment by MarkYangKp** [comment]
> I have reviewed the latest version of the code and added the prompt 'files'. However, my version has not yet implemented it @crazywoola

I pulled the latest version to run, but I still can't send pictures to Agent.
