### ISSUE TITLE
 The language has been set to Chinese, but English is still displayed in some places.

### ISSUE THREAD

**Issue by guanyouhui** [langgenius/dify#6406]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The dependent environment and front-end are deployed with docker. The back-end is executed using source code. The language has been set to Chinese during runtime, but English is still displayed in some places, as shown in the figure

![image](https://github.com/user-attachments/assets/fd0d4007-3323-4f60-a83d-0262634f862a)
![image](https://github.com/user-attachments/assets/17023c3c-2a56-4ee0-9089-17f56a60f0ba)
![image](https://github.com/user-attachments/assets/8e9a50ac-34d4-4e0b-87f1-274d7cc6ffd3)
how show to resolve this?

**Comment by crazywoola** [comment]
It has a separated setting Monitoring -> Settings -> Language
<img width="660" alt="image" src="https://github.com/user-attachments/assets/a16978e6-bd14-4070-bc8a-05e3a1fafa15">

**Comment by guanyouhui** [comment]
thanks,i found the setting
