### ISSUE TITLE
Can ollama support adding Rerank and TTS type models?

### ISSUE THREAD

**Issue by ByePastHub** [langgenius/dify#6407]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I can't use the Rerank model to enhance search in the knowledge base, but Hugging Face has a Rerank that can be added to Ollama, so I hope to have the option to select Rerank-type models. It would be best if TTS-type models could also be made available as an option.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Weaxs** [comment]
maybe should monitor these issues.

https://github.com/ollama/ollama/issues/5451
https://github.com/ollama/ollama/issues/5399
