### ISSUE TITLE
messages log not fully displayed

### ISSUE THREAD

**Issue by taibaiyunshen** [langgenius/dify#6414]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The following image is the conversation page.
![image](https://github.com/user-attachments/assets/9862affb-a3c2-49bc-927c-38fab4f05d23)
The image below represents the logs or history page.
![image](https://github.com/user-attachments/assets/f47ba9fb-8af9-4207-98f9-a784b7a762f5)
As shown in the screenshot, after completing a series of conversations, I found that my conversation history was lost when I wanted to review it. However, I did receive responses during the conversations; they are simply not visible in the conversation log anymore.

### ✔️ Expected Behavior

My desire is that each dialogue entry be faithfully saved and promptly exhibited for my review.

### ❌ Actual Behavior

Alas, a regrettable lapse has occurred, resulting in the unaccounted disappearance of segments of our conversational history.

**Comment by crazywoola** [comment]
What's your model provider and it's setting?

**Comment by taibaiyunshen** [comment]
> What's your model provider and it's setting?

The issue at hand is not contingent upon the specific model in use, as I have encountered this problem across various models I've switched between.

**Comment by taibaiyunshen** [comment]
I apologize for any confusion; I am running a local deployment of Dify.
