### ISSUE TITLE
Markdown file parsing error, code blocks are split.

### ISSUE THREAD

**Issue by blankbro** [langgenius/dify#6421]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. import this md file https://github.com/blankbro/mqtt-storm/blob/master/README.md
2. auto split or custom split

then you can look the bug

![image](https://github.com/user-attachments/assets/9e399788-9df4-4027-9462-4f527e6545b6)

### ✔️ Expected Behavior

code blocks into a single chunk.

### ❌ Actual Behavior

code blocks are being split into multiple chunk.

**Comment by blankbro** [comment]
from https://github.com/langgenius/dify/issues/5569#issuecomment-2235717865

**Comment by crazywoola** [comment]
What's your custom segment settings.

**Comment by blankbro** [comment]
> What's your custom segment settings.

# ,##, ### all try
