### ISSUE TITLE
chunk size N seems always produce chunks whose length is smaller than N/2

### ISSUE THREAD

**Issue by KaiyoungYu** [langgenius/dify#6422]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I find it that chunks's length are always smaller than the half of the max-chunk-size I set in GUI.

185 + 186 = 370, which is smaller than 500
<img width="983" alt="image" src="https://github.com/user-attachments/assets/086ec69f-470f-4c9b-9387-680507c9c38f">

373 + 364 = 737, which is smaller than 900
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/796c4e1b-8bff-4806-9ae2-361a3387ee37">

### ✔️ Expected Behavior

chunk size as expected

### ❌ Actual Behavior

chunk size N seems always produce chunks whose length is smaller than N/2

**Comment by KaiyoungYu** [comment]
I created a fake file, with 52 characters on first line (including Chinese words), 200 english characters on 5th line. Segmentation performs as expected. Maybe only real-world txt files with  too many \n can't chunk as expected.

<img width="1007" alt="image" src="https://github.com/user-attachments/assets/3967731c-c695-4822-b4cc-34341de8ea03">


<img width="999" alt="image" src="https://github.com/user-attachments/assets/a85e68f3-d6ce-4042-adca-d8799a6994a5">

**Comment by JohnJyong** [comment]
the field is max-length but not chunk length , the chunks with be splited by the spliter  characters first, after this step , if the chunk's length is over max length, it will be spliter by the max-length @KaiyoungYu

**Comment by midooqaq** [comment]
[啊.docx](https://github.com/user-attachments/files/16654571/default.docx)
I encountered the same issue. I also created a dummy file, as shown in the attachment, but it cannot be split according to the rules.
![image](https://github.com/user-attachments/assets/07a22058-c581-4d40-befb-a6718cc8ad2e)
