### ISSUE TITLE
Subsequent nodes cannot set Google tool output variables, and Google search does not seem to work in existing examples

### ISSUE THREAD

**Issue by wj1017090777** [langgenius/dify#6425]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/ddb99488-28b1-487f-b225-dbb852357ff1)
In the SEO blog generation workflow, I noticed that there is a Google search tool, but the variables of the Google search tool are not passed in the subsequent nodes, and the answer results are not answered according to the results of Google search.
And I tried to add variables, but the Google search variable only has text, and the results are actually stored in json. Please help me check, thank you.
![image](https://github.com/user-attachments/assets/acdeddfa-2191-418f-9c7f-240943f06346)

### ✔️ Expected Behavior

Correct use of Google search tools

### ❌ Actual Behavior

Subsequent nodes cannot set Google tool output variables, and Google search does not seem to work in existing examples

**Comment by crazywoola** [comment]
Use a jinja template tool or code block to format results from google could solve your problem.
