### ISSUE TITLE
I cannot change the email for local deployment.

### ISSUE THREAD

**Issue by MarisaDAZA** [langgenius/dify#6428]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I forgot the email I entered when I installed. I was searching in the existing issues. But I only found out how to change password. Even though I reinstalled the container it didn't change.

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
`flask reset-email`
