### ISSUE TITLE
Set the default value of the myscale vector db in DifyConfig.

### ISSUE THREAD

**Issue by laipz8200** [langgenius/dify#6429]
It's better to set the MyScale vector database's default in the Dify Config.

https://github.com/langgenius/dify/blob/c8f5dfcf17b0522789d0bff814c315bd2018a0a2/api/core/rag/datasource/vdb/myscale/myscale_vector.py#L162

**Comment by ox01024** [comment]
Can you give me this thread?

**Comment by laipz8200** [comment]
@ox01024 Have fun!
