### ISSUE TITLE
The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead

### ISSUE THREAD

**Issue by likenamehaojie** [langgenius/dify#6430]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead

### ✔️ Expected Behavior

The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead

### ❌ Actual Behavior

The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead

**Comment by likenamehaojie** [comment]
now i cant start speech-to-text function

**Comment by crazywoola** [comment]
This is a warning I think, can you provide more details regarding this issue?

Steps to reproduce and Expected Behavior and Actual Behavior are the same together with the tittle, this doesn't seem helpful to us to solve this problem.
