### ISSUE TITLE
glm4v not get the response

### ISSUE THREAD

**Issue by Frank-Zeng** [langgenius/dify#6433]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have workflow with local glm4v to read upload image, and I have see the logs from the glm4v server, it has normal response,but the Dify workflow node, it didn't get the glm4v response and return empty string. when I use gpt4o instead of the glm4v, it's works fine, but the glm4v server is compatiable OpenAI restful API, all of the interface and parameter is compatiable, so how to debug or resolve this issue? Thx.
![image](https://github.com/user-attachments/assets/17a4ac7d-5552-4991-a398-b8139ad950d5)

### ✔️ Expected Behavior

GLM4V response has correct show in dify workflow.

### ❌ Actual Behavior

GLM4V response show empty string in dify workflow.

**Comment by Frank-Zeng** [comment]
the LLM node get empty text in the response like below:
![image](https://github.com/user-attachments/assets/0d56ae90-7dbf-4fb2-9777-7bb487ed3d99)

**Comment by crazywoola** [comment]
Can you paste a screenshot of the LLM itself.

**Comment by Frank-Zeng** [comment]
> Can you paste a screenshot of the LLM itself.
![image](https://github.com/user-attachments/assets/30d8d3b8-c565-4d55-ae06-6f4dd94e186e)

**Comment by crazywoola** [comment]
How did you deploy the glm4v? openai-competiable?

**Comment by Frank-Zeng** [comment]
> How did you deploy the glm4v? openai-competiable?

I reference this repo to deploy glm4v: https://github.com/xusenlinzy/api-for-open-llm
