### ISSUE TITLE
Add Support for DeepInfra and gemma-2-27b-it Model

### ISSUE THREAD

**Issue by sevenjay** [langgenius/dify#6437]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I tried using OpenAI-API-compatible in dify with deploying models provided by deepinfra.
All models return empty. 
![image](https://github.com/user-attachments/assets/1bab09bc-700a-498c-9528-9209ca0f32a9)

I'd like to request that Dify add support for the DeepInfra platform and specifically the gemma-2-27b-it model.

Reasoning:
Multilingual Excellence: gemma-2-27b-it is currently considered one of the best open-source models for multilingual tasks. Integrating it would significantly enhance Dify's capabilities in understanding and generating code across various languages.

Technical Details:
Model: gemma-2-27b-it
Platform: DeepInfra (https://deepinfra.com/google/gemma-2-27b-it/api)

I'd be happy to provide any additional information or assistance to help with this integration.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by sevenjay** [comment]
DeepInfra supports Llama 3.1 70B in a good price.
please support DeepInfra, too.

**Comment by shinebarbhuiya** [comment]
Please add support for DeepInfra

**Comment by miclosgyjf** [comment]
#5725

**Comment by decentropy** [comment]
Ditto... please add DeepInfra

**Comment by srvo** [comment]
ditto -- we <3 DeepInfra
