### ISSUE TITLE
The email login interface of version 0.6.14 is gone

### ISSUE THREAD

**Issue by litetoooooom** [langgenius/dify#6439]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/1bdfd088-44fe-4852-a2f1-03c99457afbe)

**Was the original email login interface dropped? If so, from which version?**

**Comment by crazywoola** [comment]
Check the env variables are correctly defined. If you were upgrading from older versions, make sure you have run cp.env.example .env
