### ISSUE TITLE
Error on using Anthropic’s API for all Agents on Dify

### ISSUE THREAD

**Issue by bguzela** [langgenius/dify#6446]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

All my agents that were running with the anthropic API (Claude Sonnet and Claude Haiku), now show the following error: “[anthropic] Error: Messages.create()
got an unexpected keyword argument
'headers'”. All of them, that once were perfectly working, now show this error, does not matter what I write in the prompt.
![IMG_9759](https://github.com/user-attachments/assets/80728055-481d-445b-89a4-3b55e3c9540f)

### ✔️ Expected Behavior

I was just expecting the agents to work as they were before.

### ❌ Actual Behavior

The agents with anthropic’s LLM are not working.

**Comment by ottoradiologia** [comment]
I also encountered an issue when attempting to insert a new Anthropic API key on the Dify platform. Upon trying to save the new key, the following error message appears:

"Messages.create() got an unexpected keyword argument 'headers'"

Steps to Reproduce:

Navigate to the model configuration section.
Select "Model Provider" and choose Anthropic.
Enter the new API key and click "Save."
The error message appears.

**Comment by crazywoola** [comment]
Fixed we will upgrade the cloud later.

**Comment by bguzela** [comment]
> Fixed we will upgrade the cloud later.

Sure! Thank you very much! If possible, please prioritize this, as we are running many of the company's applications on Dify using Anthropic's LLM, and at the moment they are on hold.

Thank you very much!

**Comment by crazywoola** [comment]
If this is resolved, please close this PR. :)

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/6843. Will release it tonight.

**Comment by briangladu** [comment]
I'm not able to add Anthropic on the hosted version. Get this error:

Error code: 404 - {'type': 'error', 'error': {'type': 'not_found_error', 'message': 'Not Found'}}
