### ISSUE TITLE
Base model gpt-4o-mini not found

### ISSUE THREAD

**Issue by allseeworld** [langgenius/dify#6448]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/dd83ff3f-9804-4b96-89f1-ee6f06de1cfb)
![image](https://github.com/user-attachments/assets/18906292-309f-44b7-b423-bff80f57bfc3)
Base model gpt-4o-mini not found

**Comment by Weaxs** [comment]
it will be supported in latest version.

https://github.com/langgenius/dify/pull/6442

**Comment by allseeworld** [comment]
Ok, thank you very much
