### ISSUE TITLE
Make text generation timeout duration configurable

### ISSUE THREAD

**Issue by gijigae** [langgenius/dify#6449]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, text generation timeout duration is hard-coded as 60 seconds. With the advent of various tools in Chat/Workflow, often the duration exceeds 60 seconds. When that happens, the text result is not shown (see the image below) in the End node even though the response is correctly found in the log. I feel it's time to make text generation timeout configurable to accommodate more diverse requirements.

<img width="1575" alt="image" src="https://github.com/user-attachments/assets/678a3701-7b98-4a29-a634-eb6fcf4edd0f">

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6256

**Comment by shuai-huaman** [comment]
If it is a cloud service, how to modify this timeout period
