### ISSUE TITLE
About developing a tool to display files

### ISSUE THREAD

**Issue by guanyouhui** [langgenius/dify#6452]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I developed a tool that obtains remote files and then displays them. This tool has been successfully run through the source code and accessed in the workflow. The test found that if the file is a picture, it can be displayed normally. If the file is a word file, etc., debugging found that the returned content is text content, not files. I would like to ask if this is the case,if there anythint about the setting problem?
![image](https://github.com/user-attachments/assets/999823b1-550b-42cf-9b39-de7c62affa05)
![image](https://github.com/user-attachments/assets/4ffbe6e9-fe94-400e-bc83-c8480b8da4bc)
![image](https://github.com/user-attachments/assets/e490cb2b-0c9b-4691-b517-d77ba8c1fa3b)
![image](https://github.com/user-attachments/assets/932027f8-8e96-483e-a75f-0e5613d5a78b)
![image](https://github.com/user-attachments/assets/dde4e8dc-0425-4067-bb9e-4fa8fc1f5afa)
![image](https://github.com/user-attachments/assets/fe3facd6-9f22-4a6c-9296-b0a489d6229b)

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/issues/5346. We do not support display other file format yet.

**Comment by guanyouhui** [comment]
thanks for response,and  look forward to this feature being launched as soon as possible
