### ISSUE TITLE
Support Querying Temporary File

### ISSUE THREAD

**Issue by applepieiris** [langgenius/dify#6462]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, the chatbot only supports uploading the documents into the knowledge-base using owner account. 
Is there any enhancement plan to allow normal user to upload temporary file and ask the questions related to it. The document will not be put into the knowledgebase. 
[Langchain-Chatchat](https://github.com/chatchat-space/Langchain-Chatchat) support this function.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated, see https://github.com/langgenius/dify/issues/5346
We will introduce an new node type to support this feature.
