### ISSUE TITLE
When the Tool within the Agent uses the secret-input type parameter and is automatically replaced with "***", it will cause the API request to fail. 

### ISSUE THREAD

**Issue by coldstone** [langgenius/dify#6463]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

The parameter type in Tool is `secret-input`: 
![image](https://github.com/user-attachments/assets/d81b07f9-23e0-4f0d-869c-a8d8f5f0f731)

Add this tool in Agnet and fill in the parameters manually: 
![image](https://github.com/user-attachments/assets/ca7fc925-c311-49d6-b33b-9b8e2cc03d7b)

Start the test conversation: 
![image](https://github.com/user-attachments/assets/0e373b0f-cc0b-43eb-a070-08da7b2d1b95)

### ✔️ Expected Behavior

Sometimes, parameters are sent normally during API requests and the results are correct : 
![image](https://github.com/user-attachments/assets/74e4a434-fe1c-408e-9094-812b1f652a3c)

### ❌ Actual Behavior

Sometimes, parameters will be replaced with ****, and the requests received by the server are also masked parameters, and the request results are incorrect: 
![image](https://github.com/user-attachments/assets/a7634b42-5a6a-4fbe-8b95-6da4f30a6d69)

This situation does not occur inevitably, and no occasional pattern can be found. It just happened! Moreover, when it occurred, even if I immediately re-filled these parameters and saved them, when requesting again, the parameters were still replaced with ****. 

By the way, My Dify has pulled the latest version of the code (0.6.14-2024/07/19, [f2004ad](https://github.com/langgenius/dify/pull/6257/commits/f2004ad89f4a9bb0e90acaf0a1c2e3091bf9bca7))

**Comment by crazywoola** [comment]
@takatost @Yeuoly
