### ISSUE TITLE
Import and overwrite the original app using DSL on the original app.

### ISSUE THREAD

**Issue by xiaonan-rick** [langgenius/dify#6466]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Functional requirements:
Import and overwrite the original app using DSL on the original app, with the original app key unchanged.
Application scenarios:
Customer demand: Data security requirements, all applications deployed locally.
Current issue: When updating the Dify APP, applications uploaded through DSL will create new applications, resulting in changes to the API key.
Impact: Need to synchronize updates of keys in Dify APP and business systems, increasing update complexity.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
![QQ_1721380249971](https://github.com/user-attachments/assets/6bf9ea69-9476-4333-87a3-1c6fa47dcf59)
![QQ_1721380269082](https://github.com/user-attachments/assets/88912756-37f0-4365-a907-5db00f6ad2ba)

**Comment by xiaonan-rick** [comment]
Thank you, this will be of great help to us

**Comment by xiaonan-rick** [comment]
In which version is this feature available？

**Comment by crazywoola** [comment]
Several versions ago, maybe 0.6.13

**Comment by kenneth-bro** [comment]
where is the feature?
