### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by zhangyuanjun20000** [langgenius/dify#6479]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![微信图片_20240719181419](https://github.com/user-attachments/assets/874e6e81-728d-46d4-b098-e364463b7ef7)

**Comment by crazywoola** [comment]
Please provider the container logs

**Comment by felipebortoli-dev** [comment]
In here i've solved it now by backing up my custom configs , updating the full env with the latest version on branch and the docker-compose.yaml it worked fine , even loaded my old configs and keys , with no problem i just had to install the LLM provider plugin for the providers i was using. hope it helps someone else
