### ISSUE TITLE
Is there a plan for the community edition to support SSO? If so, when specifically will it be supported?

### ISSUE THREAD

**Issue by JokerRun** [langgenius/dify#6481]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

[workspace](https://docs.dify.ai/v/zh-hans/guides/workspace)

![image](https://github.com/user-attachments/assets/65e5a286-153d-4cc7-b26e-1c077c33b1eb)

the documents here show that dify will support SSO, however, some closed ticket  
https://github.com/langgenius/dify/discussions/3261
https://github.com/langgenius/dify/issues/3074

confuse me that it will not be support SSO in the community edition 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Hello there, we do not have a plan for this at this moment,  however it's in our enterprise commercial version.
Please contact [business@dify.ai](mailto:business@dify.ai)

Related https://github.com/langgenius/dify/issues/6475

**Comment by TechWithTy** [comment]
Hello i have contacted the business email still have not heard anything

**Comment by yaohongfenglove** [comment]
Have you considered creating a document that clearly outlines the differences between the community version and the cloud service version? For example, login methods, multiple workspaces, ...

**Comment by crazywoola** [comment]
> Have you considered creating a document that clearly outlines the differences between the community version and the cloud service version? For example, login methods, multiple workspaces, ...

This is a great suggestion, I will talk to the team regarding this topic to see if you can make a table there.

**Comment by joestump** [comment]
Another entry for https://sso.tax/
