### ISSUE TITLE
Issue with Increased API Call Time When Using Code Execution in Workflow

### ISSUE THREAD

**Issue by hzho2000** [langgenius/dify#6491]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I really like the code execution feature within the workflow. This feature allows me to freely write Python code to check if the current generated data is reasonable. However, I have noticed that even for very simple functions, if there is a node used in the workflow, it results in an increased API call time of 100ms. I want to understand whether there is a **persistent Python service** when I enable the workflow service or if a new Python instance is started each time I call the API.

### 2. Additional context or comments

This feature is very useful for data validation and quality checks, and the delay in API response time can impact performance significantly. Any documentation or explanation about the underlying mechanism would be greatly appreciated.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Regarding the service, I guess you are referring to this one https://github.com/langgenius/dify-sandbox. This is a standalone service which runs in background and accepts the data from the api. 

Here is the call stack. `api -> ssrf_proxy -> code_sandbox`
