### ISSUE TITLE
HTTP Request Node Accessing HTTPS with Non-443 Port Returns 403 Error

### ISSUE THREAD

**Issue by wayneg123** [langgenius/dify#6499]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Use the HTTP Request node.
2. Set the API method to GET.
3. Set the URL to https://www2.medicareaustralia.gov.au:5447/.
4. Send the request.

![image](https://github.com/user-attachments/assets/4b32f4cb-3238-4a65-8742-2682e70de632)
![image](https://github.com/user-attachments/assets/c71d35a3-5646-48d0-bf09-4c25d7392b27)

> Using requests in code node will cause 403 error too.

![image](https://github.com/user-attachments/assets/3a9e60e4-4b66-4442-85d3-c784767967db)
![image](https://github.com/user-attachments/assets/6afadc72-8974-439e-92bb-efadac8e2c89)

### ✔️ Expected Behavior

The request should successfully connect to the server and retrieve the expected response

### ❌ Actual Behavior

The request returns a 403 Forbidden error code.

- Error message from code node.

```
ov.au', port=5447): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))) 'Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/code/65ce1c33_503d_4fa8_897c_0d29d57c8ea2.py", line 65, in <module> File "/tmp/code/65ce1c33_503d_4fa8_897c_0d29d57c8ea2.py", line 54, in main File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 694, in send requests.exceptions.ProxyError: HTTPSConnectionPool(host='www2.medicareaustralia.gov.au', port=5447): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))) 'Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/tmp/code/65ce1c33_503d_4fa8_897c_0d29d57c8ea2.py", line 65, in <module> File "/tmp/code/65ce1c33_503d_4fa8_897c_0d29d57c8ea2.py", line 54, in main File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 694, in send requests.exceptions.ProxyError: HTTPSConnectionPool(host='www2.medicareaustralia.gov.au', port=5447): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))) error: exit status 255
```

**Comment by crazywoola** [comment]
There are few options that you can choose.
The simplest way is you can turn of the ssrf_proxy by setting 
```

# SSRF Proxy server HTTP URL
SSRF_PROXY_HTTP_URL=http://ssrf_proxy:3128 => SSRF_PROXY_HTTP_URL=
# SSRF Proxy server HTTPS URL
SSRF_PROXY_HTTPS_URL=http://ssrf_proxy:3128 => SSRF_PROXY_HTTPS_URL=
```

Which will turn off the proxy.

**Comment by wayneg123** [comment]
I've found the solution. Simply add the following line to `docker/ssrf_proxy/squid.conf.template`, and it works:

```
acl SSL_ports port YOUR_HTTPS_PORT
```

**Comment by Modas-Li** [comment]
> I've found the solution. Simply add the following line to `docker/ssrf_proxy/squid.conf.template`, and it works:
> 
> ```
> acl SSL_ports port YOUR_HTTPS_PORT
> ```

then found issue:[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled
(ssl.c:1007)
help!
