### ISSUE TITLE
The operation failed to set up the OpenRouter API

### ISSUE THREAD

**Issue by xixia123** [langgenius/dify#6500]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The operation failed to set up the OpenRouter API. The error message received was: 
![image](https://github.com/user-attachments/assets/5d764439-4225-42dd-a1d5-673089b474e2)

**Comment by crazywoola** [comment]
https://openrouter.ai/docs/limits

> If your account has a negative credit balance, you may see 402 errors, including for free models. Adding credits to put your balance above zero allows you to use those models again.
