### ISSUE TITLE
Console api 502 error when deploying with docker using customized port

### ISSUE THREAD

**Issue by squirrelfeng** [langgenius/dify#6502]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I want to use customized port into 8000 to run dify, by changing CONSOLE_API_URL,CONSOLE_WEB_URL,SERVICE_API_URL,APP_API_URL,APP_WEB_URL into 'ip:8000', and  EXPOSE_NGINX_PORT into '8000'. then dify report 502.
it first tries to open 'http://10.12.12.31:8000/10.12.12.31:8000/console/api/setup'.

Then I changed CONSOLE_API_URL to '', still report 502 bad gateway.

### ❌ Actual Behavior

First set all related url to http://10.12.12.31:8000:
![ss1](https://github.com/user-attachments/assets/9837d878-6f3c-4f77-92ce-7aeec851d3be)

Change CONSOLE_API_URL to empty:
![ss2](https://github.com/user-attachments/assets/ba2d3a04-7620-424b-bafe-37cc2a100704)

**Comment by xuwengen0909** [comment]
文档和代码都不一致，狗屎一样的
