### ISSUE TITLE
Segments added through API get stucked at 'indexing' state.

### ISSUE THREAD

**Issue by racerxdl** [langgenius/dify#6504]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a document with any text (via API)
2. Add segments to it (via API)
3. Wait for the document to change from Queued/Indexing -> Available
4. Try enable/disable a added segment or check the API for segment status

### ✔️ Expected Behavior

Segments to be indexed/ready after some time, being able to enable/disable a segment.

### ❌ Actual Behavior

All segments stuck at "indexing" state.

![image](https://github.com/user-attachments/assets/059594c3-d274-4b57-9ee1-59e6ae1a34e1)
![image](https://github.com/user-attachments/assets/896dac99-04b7-42d6-a344-78c3f0529c42)
![image](https://github.com/user-attachments/assets/275349d7-b1ce-4f1e-b8c9-5c86e02d50db)
![image](https://github.com/user-attachments/assets/0c481651-4bbc-41dc-9fb6-036b90d1999e)

This doesn't happen if I add the entire text to process when creating the document. But then the chunker messes it up and doesn't create the segments properly. So I manually separated the segments for QA and added them via API.

**Comment by JohnJyong** [comment]
pls share the api curl , so we can check the real promble. @racerxdl

**Comment by racerxdl** [comment]
Sorry for the delay @JohnJyong, here is a small example:

```bash
    curl -X POST https://dify/v1/datasets/b384e948-2a1a-4c6a-9379-e05094d54ef5/documents/26a7498f-9539-4de4-a894-7a96139dafc4/segments \
    -H "Authorization: Bearer dataset-XXXXXXXXXX" \
    -H "Content-Type: application/json" \
    -d '{
    "segments": [
        {
            "content": "Tell me about Spell - Precision Shot",
            "answer": "# Spell - Precision Shot\nChannels for 2.5 seconds to shoot a powerful arrow. Deals 300% Weapon Power weapon damage to the target. Casting time is reduced by 0.5 seconds per 10 Aether consumed.\n\n* Agressive: True\n* Archetype: Archery\n* Channeling: Yes\n* Cooldown: 30.0 seconds\n* Cost: 5% of mana\n* Needs Target: Yes\n* Skill Points: 3\n* Range: 6 tiles\n* Aether: -50\n* Self Target: No",
            "keywords": [
                "ravendawn",
                "skill",
                "spell",
                "precision shot"
            ]
        }
    ]
}'```

**Comment by crazywoola** [comment]
It should be fix in latest version.

**Comment by racerxdl** [comment]
Hey @crazywoola which version it has been fixed? I'm testing on 0.7.3 and its still happens

![image](https://github.com/user-attachments/assets/9b8d1999-983b-4c1e-8038-ec5d8cdf443e)
![image](https://github.com/user-attachments/assets/7839dd9d-b418-4c1f-9d99-8f130a464c49)

**Comment by crazywoola** [comment]
Hello, it seems to be another problem, I will reopen this issue.

**Comment by JohnJyong** [comment]
There is a conflict between segment creation during document generation and  create segment by api . New segment creation will be prohibited during document processing.

**Comment by racerxdl** [comment]
Just to be sure @crazywoola is the patch for this issue applied in 0.7.3? (Not the issue @JohnJyong mentioned). Because if I check the API, its still stuck at indexing:
![image](https://github.com/user-attachments/assets/787e9057-fef1-4914-a3dc-0309cc25c26d)

Thats stuff I added after upgrading to 0.7.3

**Comment by racerxdl** [comment]
Seens to be working on 0.8.0
