### ISSUE TITLE
App port no change after change the EXPOSE_NGINX_PORT

### ISSUE THREAD

**Issue by tiomfree** [langgenius/dify#6505]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I can access and create app via the new port & URL after changed the port number in .env file:
# HTTP port
NGINX_PORT=8056
# ------------------------------
# Docker Compose Service Expose Host Port Configurations
# ------------------------------
EXPOSE_NGINX_PORT=8056

For example: http://192.168.50.144:8056/

but the new APP can not access when publish as I find the access URL keep default 80 port no change when I click the publish and "Run App" button.
For example: 
The published App URL keeps as below so can't access at all:
http://192.168.50.144/chat/ssflXZpobXQo4JDlWd

it works if I change the port to 8056 as below manually:
http://192.168.50.144:8056/chat/ssflXZpobXQo4JDlWd

### ✔️ Expected Behavior

Expect the port of new App should be changed from default 80 as well when changed the nginx port in .ENV. 
for example: when create new APP, and click the publish and "Run App" button.
http://192.168.50.144:8056/chat/ssflXZpobXQo4JDlWd

### ❌ Actual Behavior

the published App URL keeps as default 80 port as below so can't access at all:
http://192.168.50.144/chat/ssflXZpobXQo4JDlWd

**Comment by tiomfree** [comment]
I don't think it works with the two items, are you sure it's defined? 
NEXT_PUBLIC_API_PREFIX=http://192.168.50.144:8056/console/api
NEXT_PUBLIC_PUBLIC_API_PREFIX=http://192.168.50.144:8056/api

**Comment by crazywoola** [comment]
This variable doesn't related to the feature you would like to change. You should read [this doc](https://docs.dify.ai/getting-started/install-self-hosted/environments) instead.
