### ISSUE TITLE
got-4o-mini not available in a list of OpenAI models - docker compose installation 

### ISSUE THREAD

**Issue by amatiytsiv** [langgenius/dify#6507]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Clean VM alpine linux
clean install of dify 0.6.14 using docker compose
using OpenAI API key. - hit show models

### ✔️ Expected Behavior

All models  are displayed

### ❌ Actual Behavior

All models except got-4o-mini are displayed

**Comment by amatiytsiv** [comment]
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/9cb047fb-8701-4d47-aede-e2550668c547">

**Comment by amatiytsiv** [comment]
@dosu in clean install based on previous commits it expected to be in the list once you added api key, no custom adding of some models has to be executed. so that's  a bug on clean setup

**Comment by crazywoola** [comment]
It's already added in this PR, https://github.com/langgenius/dify/pull/6442 it's available in Cloud version, and it will be released in v0.6.15.
