### ISSUE TITLE
【help】langgenius/base:1.0.0-bullseye-slim 这个怎么构建？

### ISSUE THREAD

**Issue by jinghai** [langgenius/dify#651]
项目中web/Docker中指定了 FROM langgenius/base:1.0.0-bullseye-slim，请问 langgenius/base:1.0.0-bullseye-slim镜像是怎么构建出来的呢？

**Comment by takatost** [comment]
The base image is built through docker/Dockerfile.base.

**Comment by jinghai** [comment]
@takatost 打包的命令怎么写？
