### ISSUE TITLE
Can you add a timer node to trigger a workflow at regular intervals?

### ISSUE THREAD

**Issue by yifeiaaa** [langgenius/dify#6511]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Proposal Functionality:
Add timer nodes to Dify for automated workflows with timed execution, such as data synchronization, report generation, etc.

Expected Functions:
1.Users can set schedules for one-time or recurring execution.
2.Supports daily, weekly, monthly or customized intervals.
3.Ensures robustness of workflow execution, even during network outages or maintenance.

Use Cases:
For example, automatically perform database synchronization at night without manual intervention.

Benefits:
1.Automate repetitive tasks.
2.Improve efficiency and reliability of data processing.
3.Reduce the need for manual operations.

This feature will enhance Dify's automation capabilities and fulfill users' needs for timed operations.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5697

**Comment by leochen-g** [comment]
You can use this project to make schedule. https://github.com/leochen-g/dify-schedule @jmorata-waby
