### ISSUE TITLE
Cannot Load Custom Moderation extension

### ISSUE THREAD

**Issue by qjy706** [langgenius/dify#6528]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I configured Custom Modulation based on the document in the reference link, but it doesn't work https://docs.dify.ai/guides/extension/code-based-extension/moderation
![微信图片_20240722165131](https://github.com/user-attachments/assets/eee95868-2874-4728-b1fc-b95667b6e3a0)
![微信图片_20240722165138](https://github.com/user-attachments/assets/27bbc3df-5af8-4814-9400-0cebecbf970c)
I added a __builtin__ file inside and wrote a 4 in it because if I don't create the __builtin__ file, the value of Cloud_Service in the position_map variable on line 114 of api-core/extension/extensible. py is None
#3981 This is the same problem, but it does not have a solution

### ✔️ Expected Behavior

Can load Cloud_Service extension

### ❌ Actual Behavior

Cannot load extension

**Comment by linfey90** [comment]
I encountered the same issue; the cloud service I added according to the example did not appear on the page.How to solve this?
