### ISSUE TITLE
Fire crawl duplicate pages

### ISSUE THREAD

**Issue by djav1985** [langgenius/dify#6532]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Crawl your website

### ✔️ Expected Behavior

To get one copy of eachpage

### ❌ Actual Behavior

Some life pages show up twice in a list. Like it's picking up duplicates. Has anyone else experienced this problem? Or know why it's doing this is it something to do the way dify is using it or is it something with the project itself?

**Comment by crazywoola** [comment]
I don't think it's related to our side, because we only call apis to get data from firecrawl.
