### ISSUE TITLE
Workflow add-ons

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#6552]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Will the workflow later support file input (pictures and files) in the basic configuration and the following functions?
![image](https://github.com/user-attachments/assets/d903e29e-e2c8-4f56-9d11-84372bf638fb)
![image](https://github.com/user-attachments/assets/cb8024bc-8185-45d9-b09a-86194f1c0b25)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
The workflow you mention is Chatflow or Workflow. This features are only available for Chatflow.
