### ISSUE TITLE
I deployed dify locally with source code.However, the external_data_tools field in the app_model_configs table has always been empty. I have added the tools to the agent and enabled them, but the model cannot call the tools.

### ISSUE THREAD

**Issue by qihanghou726** [langgenius/dify#6558]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

<img width="859" alt="Snipaste_2024-07-23_14-18-56" src="https://github.com/user-attachments/assets/f39f8c6d-f7fc-4e95-9619-68e5fe6cb3fa">

### ✔️ Expected Behavior

Ability to correctly use agent tool functions

### ❌ Actual Behavior

nothing

**Comment by crazywoola** [comment]
What LLM do you use?

**Comment by qihanghou726** [comment]
> What LLM do you use?

gpt 4o I also tried engre and glm-4 but neither worked. I saw that the external_data_tools field in app_model_configs was queried in the code, but it was always empty in my database. Is it related to this?

**Comment by crazywoola** [comment]
> > What LLM do you use?
> 
> gpt 4o I also tried engre and glm-4 but neither worked. I saw that the external_data_tools field in app_model_configs was queried in the code, but it was always empty in my database. Is it related to this?

Yes I guess so.

**Comment by qihanghou726** [comment]
> > > What LLM do you use?
> > 
> > 
> > gpt 4o I also tried engre and glm-4 but neither worked. I saw that the external_data_tools field in app_model_configs was queried in the code, but it was always empty in my database. Is it related to this?
> 
> Yes I guess so.

So what should I try to solve this problem?

**Comment by qihanghou726** [comment]
> > > What LLM do you use?
> > 
> > 
> > gpt 4o I also tried engre and glm-4 but neither worked. I saw that the external_data_tools field in app_model_configs was queried in the code, but it was always empty in my database. Is it related to this?
> 
> Yes I guess so.


Or can you tell me the meaning of the external_data_tools field? Is it used to record tools?

**Comment by crazywoola** [comment]
#6569 You mentioned you can correctly get the answers from the cloud version? 



> > > > What LLM do you use?
> > > 
> > > 
> > > gpt 4o I also tried engre and glm-4 but neither worked. I saw that the external_data_tools field in app_model_configs was queried in the code, but it was always empty in my database. Is it related to this?
> > 
> > 
> > Yes I guess so.
> 
> So what should I try to solve this problem?

In this case you should update the code to latest on main branch.

**Comment by crazywoola** [comment]
> > > > What LLM do you use?
> > > 
> > > 
> > > gpt 4o I also tried engre and glm-4 but neither worked. I saw that the external_data_tools field in app_model_configs was queried in the code, but it was always empty in my database. Is it related to this?
> > 
> > 
> > Yes I guess so.
> 
> Or can you tell me the meaning of the external_data_tools field? Is it used to record tools?

See this doc https://docs.dify.ai/guides/extension/api-based-extension/external-data-tool
