### ISSUE TITLE
When calling the API to update segments, the answer field cannot be updated correctly.

### ISSUE THREAD

**Issue by dc-vin** [langgenius/dify#6563]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When calling the API to update segments, the answer field cannot be updated correctly.

![QQ_1721717982523](https://github.com/user-attachments/assets/5cebe816-cfa9-4873-88fa-998a4b4ea105)

**Comment by crazywoola** [comment]
What is your knowledge base mode? QA or Normal?

**Comment by dc-vin** [comment]
> What is your knowledge base mode? QA or Normal?

QA model

**Comment by crazywoola** [comment]
It should be resolved in v0.7.1
