### ISSUE TITLE
Knowledge base api documentation problem

### ISSUE THREAD

**Issue by silence-pan84** [langgenius/dify#6565]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Whether the create_by_file interface in the knowledge base api can be added to the doc_form parameter，

**Comment by crazywoola** [comment]
@JohnJyong

**Comment by crazywoola** [comment]
And I am not sure what you are try to do, can you add a curl example as well? @silence-pan84

**Comment by silence-pan84** [comment]
> And I am not sure what you are try to do, can you add a curl example as well? @silence-pan84

![image](https://github.com/user-attachments/assets/989799ba-9416-47f9-9e1e-b293523d6137)
Is it possible to add "doc_form: "qa_model" to the request parameter of this section?

**Comment by crazywoola** [comment]
In cloud version we do not support `qa_model`. Only self hosted version can support this.
