### ISSUE TITLE
Some qwen llm can not invoke function-call

### ISSUE THREAD

**Issue by Dofine-dufei** [langgenius/dify#6567]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

on 2024.07.23，I can not invoke fc with some qwen llm，like qwen-max... But actually,it work last week.
![6fc774a5c3857d1cd156496fc140f6f](https://github.com/user-attachments/assets/2bf81fc3-5f86-4213-8056-871bb4ecaa2a)

### ✔️ Expected Behavior

I hope it invoke fc correctly
![d5d4eed8762fc1bd2d1f7ab531f2338](https://github.com/user-attachments/assets/60050782-4caf-4720-bcee-b4df83b7567b)

### ❌ Actual Behavior

However, qwen-max can not invoke correctly

**Comment by Dofine-dufei** [comment]
![d5d4eed8762fc1bd2d1f7ab531f2338](https://github.com/user-attachments/assets/1e05be5a-4d21-4701-bb2c-7e3c202cf16a)

**Comment by Dofine-dufei** [comment]
**LOG**
`
data: {"event": "error", "conversation_id": "5d74e70a-bcf9-4a76-bc6f-ad91db9b9b2f", "message_id": "aeccf4a0-399f-499b-a1ea-49c7afceb939", "created_at": 1721690363, "code": "completion_request_error", "status": 400, "message": "[tongyi] Server Unavailable Error, Failed to invoke model qwen-max, status code: 500, message: messages with role \"tool\" must be a response to a preceeding message with \"tool_calls\"."}
`

**Comment by Dofine-dufei** [comment]
I fixed it！！！

**Comment by laipz8200** [comment]
> I fixed it！！！

Congrats! Are you interested in making a PR?
