### ISSUE TITLE
[feat]  Embed Workflow in webapp by embed.min.js

### ISSUE THREAD

**Issue by Weaxs** [langgenius/dify#6568]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to embed workflow in website.
Embed the workflow into the website, with parameters taken from values on the web page, such as the current page.

### 2. Additional context or comments

 I see [web/app/components/app/overview/embedded/index.tsx](https://github.com/langgenius/dify/blob/main/web/app/components/app/overview/embedded/index.tsx).

It is only support `${url}/chatbot/${token}`,  maybe should be  compatible with workflow？

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Weaxs** [comment]
I want to use workflow and embed it in webapp, like kimi Copilot
![image](https://github.com/user-attachments/assets/92c66dd5-937f-44d4-bff7-8aa401054a4f)

**Comment by Weaxs** [comment]
Agent is already supported by embed.min.js script, but workflow only can be used by iframe.

**Comment by taowang1993** [comment]
> web/app/components/app/overview/embedded/index.tsx

I don't like iframe either since it will expose url. 

How are you embedding the chatbot/agent/workflow currently?

**Comment by Weaxs** [comment]
I have not solved it.

I wanted  try to support before, but not started development yet.

maybe you can help to support it If you have spare time ?  👀

> > web/app/components/app/overview/embedded/index.tsx
> 
> I don't like iframe either since it will expose url.
> 
> How are you embedding the chatbot/agent/workflow currently?

**Comment by taowang1993** [comment]
where is the embed.min.js? you said we can embed agent with this script.
where is this script?

**Comment by Weaxs** [comment]
> where is the embed.min.js?
> 
> <script src="${url}/embed.min.js" id="${token}" defer> </script>
> is this approach going to expose the api key?

https://github.com/langgenius/dify/blob/main/web/public/embed.min.js

`token` is `SiteConfig.access_token` at https://github.com/langgenius/dify/blob/main/web/types/app.ts I guess.

It's different with api key.
