### ISSUE TITLE
 The tool function cannot be called

### ISSUE THREAD

**Issue by qihanghou726** [langgenius/dify#6569]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I added and enabled the tool correctly, but the agent just doesn't call it, but the dify in the official website can.

### ✔️ Expected Behavior

The agent can call the tool correctly

### ❌ Actual Behavior

Agent does not call tools

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/6558
