### ISSUE TITLE
Xinference credentials validate failed

### ISSUE THREAD

**Issue by Modas-Li** [langgenius/dify#6582]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```
Xinference credentials validate failed: get xinference model extra parameter failed, url: http:/ /v1/models/qwen1.5-chat, error: HTTPConnection Pool(host= port= Max retries exceeded with url: /v1/models/qwen1.5-chat (Causedby ConnectTimeoutError(<urllib3.connection.HTTP Connection obietat at Ox7fc4f8376c80>, 'Connection to timed out. (connect timeout=10)'))
```
![image](https://github.com/user-attachments/assets/fc8518c4-6478-44c1-9dad-a4d7181e4595)
![image](https://github.com/user-attachments/assets/721ea8be-1d7c-4c34-83d0-6418e2b43560)

### ✔️ Expected Behavior

add xinference model qwen1.5-chat

### ❌ Actual Behavior

come up with error in image

**Comment by crazywoola** [comment]
Please use a proper markdown syntax to format error code instead of put this in the title.

**Comment by crazywoola** [comment]
Have you add other llms in xinference?

**Comment by Modas-Li** [comment]
> Have you add other llms in xinference? If not, please follow the instructions here. https://docs.dify.ai/guides/model-configuration/xinference

already add several llms in xinference, and use well in other repository, is there anything i forgot to set?

**Comment by crazywoola** [comment]
> > Have you add other llms in xinference? If not, please follow the instructions here. https://docs.dify.ai/guides/model-configuration/xinference
> 
> already add several llms in xinference, and use well in other repository, is there anything i forgot to set?

I mean have you added other llms provided by xinference to dify successfully?

**Comment by Modas-Li** [comment]
> > > Have you add other llms in xinference? If not, please follow the instructions here. https://docs.dify.ai/guides/model-configuration/xinference
> > 
> > 
> > already add several llms in xinference, and use well in other repository, is there anything i forgot to set?
> 
> I mean have you added other llms provided by xinference to dify successfully?

No.
![image](https://github.com/user-attachments/assets/ae5d6f56-40aa-4e38-b1c3-749abb2bd3b6)
![image](https://github.com/user-attachments/assets/ac587991-4a3c-44fc-9f08-d8480eadfdee)
Thx for help

**Comment by Modas-Li** [comment]
need internal ip

**Comment by michaelChe956** [comment]
## Dify version
main
## Cloud or Self Hosted
Self Hosted (Docker)

i have the same problem.
i find that there is not set the authorization in the func (_get_xinference_extra_parameter)
![图片](https://github.com/user-attachments/assets/6183bf1f-8f87-46af-b383-f8a41a3ca725)

when do you plan to add this func.

**Comment by Liguoz** [comment]
我的原因是在Dify配置用了openai_compatible的类型，其实dify有对应的**Xinference的接口** 

![Image](https://github.com/user-attachments/assets/110466fc-144c-45d2-90e2-f533fbae770b)
