### ISSUE TITLE
Custom Tool Error: Request Body Issue with Post Interface

### ISSUE THREAD

**Issue by joyatcloudfall** [langgenius/dify#6586]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Generate the API client using the provided OpenAPI schema.
Attempt to make a POST request to the /batch endpoint with the required parameters.
Observe that the request fails due to an apparent misinterpretation of the parameters as the request body.
![image](https://github.com/user-attachments/assets/f9fd4fd7-63ce-4f93-aba6-768e01fea982)
Following is my schema:

```
openapi: 3.1.0
info:
  title: test
  description: ''
  version: 1.0.0
tags: []
paths:
  /batch:
    post:
      summary: Get IP Info
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: key
          in: query
          description: ''
          required: true
          schema:
            type: string
        - name: query
          in: requestBody
          description: ''
          required: true
          schema:
            type: string
        - name: fields
          in: requestBody
          description: ''
          required: true
          schema:
            type: string
        - name: lang
          in: requestBody
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  query:
                    type: string
                  fields:
                    type: string
                  lang:
                    type: string
                required:
                  - query
                  - fields
                  - lang
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security: []
  securitySchemes: {}
servers: 
- url: https://xxx-ip-api.com

```

By the way, if I don't mention requestBody params in "parameters", I couldn't even input values while testing.

### ✔️ Expected Behavior

The POST request should be sent successfully with the correct payload structure.

### ❌ Actual Behavior

The request fails, possibly due to incorrect handling of the request body.

**Comment by joyatcloudfall** [comment]
I don't get it. How can I input my request body?
![image](https://github.com/user-attachments/assets/f391c7be-481b-4c8b-bcf3-bc9c0ef7033f)

**Comment by crazywoola** [comment]
For example tools, please see this repo instead. https://github.com/crazywoola/dify-tools-worker
