### ISSUE TITLE
Conditional Branch IF/ELSE number compare error

### ISSUE THREAD

**Issue by viviov** [langgenius/dify#6591]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

if $param <= constant 1

### ✔️ Expected Behavior

if or else 

### ❌ Actual Behavior

1 validation error for IfElseNodeData conditions.1.comparison_operator Field required [type=missing, input_value={'id': '1721309606808', '...ector': [], 'value': ''}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by viviov** [comment]
![image](https://github.com/user-attachments/assets/7178f481-7f14-49e6-aded-b9e8f361a067)
{
  "result": 4
}

**Comment by crazywoola** [comment]
I've checked this issue, but it seems can not reproduce on our latest version, please upgrade to v0.6.15 to see if this issue persists.

**Comment by viviov** [comment]
> I've checked this issue, but it seems can not reproduce on our latest version, please upgrade to v0.6.15 to see if this issue persists.

![image](https://github.com/user-attachments/assets/26a5fa38-e4cb-4894-856d-db072dfea02f)
![image](https://github.com/user-attachments/assets/641feb9f-0ce6-4f5e-9fd9-069d4845c232)
![image](https://github.com/user-attachments/assets/e661e976-629e-4fa0-b1f1-62d63657a951)

same error
