### ISSUE TITLE
Error creating release vis workflow (_ssl.c:1000)

### ISSUE THREAD

**Issue by bruno5barros** [langgenius/dify#6593]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use the code below to test it:
name: keyword-releaser
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: bruno5barros/custom_action@main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                args: 'FIXED'

### ✔️ Expected Behavior

Create the release.

### ❌ Actual Behavior

http: error: SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/bruno5barros/github_action/releases?access_token=*** (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))) while doing a POST request to URL: https://api.github.com/repos/bruno5barros/github_action/releases?access_token=***

**Comment by crazywoola** [comment]
This is not relevant to dify itself.
