### ISSUE TITLE
Feature Request: Application marketplace

### ISSUE THREAD

**Issue by LeslieLeung** [langgenius/dify#66]
Since the applications is prompt based, is it possible to have a marketplace where Dify Cloud users can share applications(and even datasets if they choose to opensource them)?

**Comment by takatost** [comment]
Yes! Our marketplace is already in development.

**Comment by LeslieLeung** [comment]
I am a backend developer, how can I help? (I write mostly golang, but I can do python.)

**Comment by takatost** [comment]
This feature has been written almost completely and is in the process of being integrated. Thank you very much for your kind offer. :)
