### ISSUE TITLE
SandBox import boto3 ModuleNotFoundError

### ISSUE THREAD

**Issue by XDongo** [langgenius/dify#6601]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I added boto3 in sandbox dependencies/python-requirements.txt And it worked

`cat python-requirements.txt
--index-url https://pypi.tuna.tsinghua.edu.cn/simple
--extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
boto3`

But I can't use it
The screenshot shows the results of piplist
![20240724105637](https://github.com/user-attachments/assets/d79346d6-c5d8-44c0-8781-1feb5f960904)
![20240724105819](https://github.com/user-attachments/assets/cf198201-ad6c-4dc0-8c9b-6cb02102eb6e)

**Comment by XDongo** [comment]
But I can run this py in sandbox :
![20240724110024](https://github.com/user-attachments/assets/037d58d9-36a0-461a-8bbe-f992cecb3eef)

**Comment by XDongo** [comment]
Execute the result using python sys.path
![20240724110216](https://github.com/user-attachments/assets/3f9a35b2-00fe-445a-b731-77c878936660)
![20240724110359](https://github.com/user-attachments/assets/1e86ddf2-6184-43f4-91ce-1a1f082b6f1f)

**Comment by crazywoola** [comment]
<img width="413" alt="image" src="https://github.com/user-attachments/assets/d41dfc78-a29f-4d8c-a155-d80d99b01051">
