### ISSUE TITLE
help: how to use alembic to build migrations versions

### ISSUE THREAD

**Issue by hanqingwu** [langgenius/dify#6602]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I want to add some db column,   how to  use alembic to build migrations versions.
I can not find any document about it .
Thanks.

**Comment by hanqingwu** [comment]
which work path in dify use alembic?  can you give me a example ?

**Comment by hanqingwu** [comment]
when I use `alembic revision -m "add new columns" `  under  api/migrations
`  FAILED: No 'script_location' key found in configuration.`

**Comment by crazywoola** [comment]
You can either goolge it or ask chatgpt regarding this topic. This is off topic.

**Comment by tealeeseng** [comment]
> when I use `alembic revision -m "add new columns" ` under api/migrations ` FAILED: No 'script_location' key found in configuration.`

Hi, @hanqingwu , Do you have any solution? :)

I set "script_location = ./migrations" inside alembic.ini

and run command:
dify-dev/api$ alembic -c migrations/alembic.ini revision -m "initial Access Codes feature"

I encountered error:
  File "/home/XXXX/dify-dev/api/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/XXXX/dify-dev/api/migrations/versions/03f98355ba0e_add_workflow_tool_label_and_tool_.py", line 11, in <module>
    import models as models
ModuleNotFoundError: No module named 'models'

**Comment by hanqingwu** [comment]
My solution:
1.  mv alembic.ini from migrations  to api
2.  set "script_location = migrations" inside alembic.ini
3.  run  alembic revision -m "add xx"  under api

**Comment by lcgash** [comment]
> > when I use `alembic revision -m "add new columns" ` under api/migrations ` FAILED: No 'script_location' key found in configuration.`
> 
> Hi, [@hanqingwu](https://github.com/hanqingwu) , Do you have any solution? :)
> 
> I set "script_location = ./migrations" inside alembic.ini
> 
> and run command: dify-dev/api$ alembic -c migrations/alembic.ini revision -m "initial Access Codes feature"
> 
> I encountered error: File "/home/XXXX/dify-dev/api/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py spec.loader.exec_module(module) # type: ignore ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 995, in exec_module File "", line 488, in _call_with_frames_removed File "/home/XXXX/dify-dev/api/migrations/versions/03f98355ba0e_add_workflow_tool_label_and_tool_.py", line 11, in import models as models ModuleNotFoundError: No module named 'models'

我也遇到了这个问题，参考上面那个也没有解决，请问你是怎么解决的

**Comment by shihaoLiua** [comment]
> > > when I use `alembic revision -m "add new columns" ` under api/migrations ` FAILED: No 'script_location' key found in configuration.`
> > 
> > 
> > Hi, [@hanqingwu](https://github.com/hanqingwu) , Do you have any solution? :)
> > I set "script_location = ./migrations" inside alembic.ini
> > and run command: dify-dev/api$ alembic -c migrations/alembic.ini revision -m "initial Access Codes feature"
> > I encountered error: File "/home/XXXX/dify-dev/api/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py spec.loader.exec_module(module) # type: ignore ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 995, in exec_module File "", line 488, in _call_with_frames_removed File "/home/XXXX/dify-dev/api/migrations/versions/03f98355ba0e_add_workflow_tool_label_and_tool_.py", line 11, in import models as models ModuleNotFoundError: No module named 'models'
> 
> 我也遇到了这个问题，参考上面那个也没有解决，请问你是怎么解决的

我也遇到了，为什么呀，网上没有找到相关的办法。

**Comment by samt42** [comment]
> > > > when I use `alembic revision -m "add new columns" ` under api/migrations ` FAILED: No 'script_location' key found in configuration.`
> > > 
> > > 
> > > Hi, [@hanqingwu](https://github.com/hanqingwu) , Do you have any solution? :)
> > > I set "script_location = ./migrations" inside alembic.ini
> > > and run command: dify-dev/api$ alembic -c migrations/alembic.ini revision -m "initial Access Codes feature"
> > > I encountered error: File "/home/XXXX/dify-dev/api/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py spec.loader.exec_module(module) # type: ignore ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 995, in exec_module File "", line 488, in _call_with_frames_removed File "/home/XXXX/dify-dev/api/migrations/versions/03f98355ba0e_add_workflow_tool_label_and_tool_.py", line 11, in import models as models ModuleNotFoundError: No module named 'models'
> > 
> > 
> > 我也遇到了这个问题，参考上面那个也没有解决，请问你是怎么解决的
> 
> 我也遇到了，为什么呀，网上没有找到相关的办法。

export PYTHONPATH=.
