### ISSUE TITLE
Helicone Observability option in Dify

### ISSUE THREAD

**Issue by chitalian** [langgenius/dify#6604]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello! I am the CEO and Co-founder of Helicone.ai, an LLM observability platform. We love Dify and added a an [integration here](https://docs.helicone.ai/other-integrations/dify#dify), however, we noticed you had a tighter integration wth LangFuse and LangSmith. We were wondering if you would be open to a similar integration as well?

### 2. Additional context or comments

N/A

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes, PRs are welcome :)
