### ISSUE TITLE
Output json string automatically get escaped in Code

### ISSUE THREAD

**Issue by xubuild** [langgenius/dify#6605]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In Code block:
```
import json


def main(arg1: str) -> dict:
    
    req = {
        "arg1": arg1        
    }
    return {
        "req_str": json.dumps(req)

    }

```

### ✔️ Expected Behavior

the output req_str should be the orginal json text
```
{"arg1":"abc"}
```

### ❌ Actual Behavior

the output req_str's value will be automatically escaped and pass to next block:
```
{\"arg1\":\"abc\"}
```

**Comment by crazywoola** [comment]
See docs here. https://docs.python.org/zh-cn/3/library/json.html
