### ISSUE TITLE
Custom tool json array output is parsed as string

### ISSUE THREAD

**Issue by elvis-cai** [langgenius/dify#6606]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

deploy a custom tool to return json array and test the custom tool to see the output, it's returning text string instead of json format 
<img width="460" alt="image" src="https://github.com/user-attachments/assets/cf1f254a-81bd-4263-a0b1-5400fc140a6c">

### ✔️ Expected Behavior

json output is parsed correctly instread of text string format

### ❌ Actual Behavior

```
{
  "text": "[{\"description\": \"The image depicts a scenic view of a grassy field with a wooden walkway or boardwalk leading through it. The sky above is mostly clear with some clouds, and there are trees and shrubs visible on either side of the walkway. The overall scene conveys a peaceful, natural environment, likely in a wetland or meadow area.\"}]",
  "files": [],
  "json": []
}

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6605
