### ISSUE TITLE
Uploading PDFs to the knowledge bank can disrupt other users' regular usage

### ISSUE THREAD

**Issue by wmcde** [langgenius/dify#6607]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I deployed DiFY on a local server using Docker, running on Ubuntu 22 with an Intel Xeon Gold 5320*2 CPU, and 256GB of memory. I encountered an issue where uploading approximately ten PDF files, each roughly 10 megabytes in size (totalling approximately 100 megabytes) to the knowledge base takes a significant amount of time; during this period, other users are unable to access DiFY normally. Upon checking the server, I found that system resource usage was at typical levels; only a few CPU cores were at 100% utilization while most remained underutilized. Is there an issue with how DiFY is configured for resource consumption? How should I tweak the configuration settings to maximize server performance and ensure uninterrupted access for all users?

**Comment by crazywoola** [comment]
@takatost Could you take a look at this one?
