### ISSUE TITLE
About  in “What’s New in v0.6.15”，I've confirmed that my Dify version is the latest. In the prompt generator interface, why does my interface lack the parameter listing inputs as mentioned in your updated documentation's screenshot, while mine is blank? What could be the reason for this discrepancy?

### ISSUE THREAD

**Issue by Sam-gz** [langgenius/dify#6608]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

![屏幕截图 2024-07-24 125957](https://github.com/user-attachments/assets/57a37f33-9927-4930-bd54-a16d2197bb39)
![屏幕截图 2024-07-24 130241](https://github.com/user-attachments/assets/999e193c-e7e8-4b52-a209-480d275c7a06)

**Comment by crazywoola** [comment]
You need to input something and run generate.
