### ISSUE TITLE
40 VARCHAR Limit on Model Name

### ISSUE THREAD

**Issue by mbbyn** [langgenius/dify#6615]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

First, add an OpenAI API compatible model with a long name.

![image](https://github.com/user-attachments/assets/5d5b970b-3328-46f5-8cad-4e393478ddc1)

Then, try to use the model in a Knowledge Base settings. Observe the failure and error logs.

### ✔️ Expected Behavior

It should work with long model names.

### ❌ Actual Behavior

It fails to save the model name since it's >40 VARCHAR.

```python
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(40)
dify_api.1
all values are hidden
dify_api.1
[SQL: INSERT INTO dataset_collection_bindings (provider_name, model_name, type, collection_name) VALUES (%(provider_name)s, %(model_name)s, %(type)s, %(collection_name)s) RETURNING dataset_collection_bindings.id, dataset_collection_bindings.created_at]
dify_api.1
[parameters: {'provider_name': 'openai_api_compatible', 'model_name': 'sentence-transformers/distiluse-base-multilingual-cased-v1', 'type': 'dataset', 'collection_name': 'Vector_index_df1864b1_1392_456d_ad1f_0ec6030969a3_Node'}]
```

![image](https://github.com/user-attachments/assets/067e897d-d131-4219-bed0-f5e6ce678d00)

**Comment by mbbyn** [comment]
For those interested, we are hosting HuggingFace Text Embedding Inference server, which exposes an OpenAI compatible API. In order to ask it to infer on a certain model, we pass the model name to the server, which are usually very long names.

**Comment by mbbyn** [comment]
Related #1857 @crazywoola

**Comment by crazywoola** [comment]
Actually, it's pretty easy to fix this, I will upgrade the migrations later.

**Comment by mbbyn** [comment]
I have tested this change, but the issue still persists, unfortunately. The PR updates `provider_name` in `embeddings` table, but we would want to update `model_name` in `dataset_collection_bindings` instead. It is also worth increading the limit of `model_name` in other tables, such as `embeddings`.

**Comment by HiroshigeAoki** [comment]
@mbbyn 
I ran into the same issue. So I fixed it.
