### ISSUE TITLE
Option to Import original APP Key Along with DSL Application Import.

### ISSUE THREAD

**Issue by xiaonan-rick** [langgenius/dify#6618]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The products I offer are locally deployed on our clients’ servers, so each new client has their own dedicated Dify deployment. Currently, when importing a DSL application, a new APP key is generated, which requires us to reconfigure the APP Key. This results in the keys for the same application being inconsistent across different clients, greatly increasing the operational burden.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
According to our open source license https://github.com/langgenius/dify?tab=License-1-ov-file, multi-tenant service is prohibited, you need to obtain our business license and then you can reach our support via email support@dify.ai.

Also we use the api key to distinguish the user's application. So if it's the same key, it will be navigated to the same application.

For more questions, please reach out to business@dify.ai, you should stop the service before obtain a business license.

**Comment by xiaonan-rick** [comment]
> According to our open source license https://github.com/langgenius/dify?tab=License-1-ov-file, multi-tenant service is prohibited, you need to obtain our business license and then you can reach our support via email [support@dify.ai](mailto:support@dify.ai).
> 
> Also we use the api key to distinguish the user's application. So if it's the same key, it will be navigated to the same application.
> 
> For more questions, please reach out to [business@dify.ai](mailto:business@dify.ai), you should stop the service before obtain a business license.

Thank you, we have not yet started the actual service and are currently in the conceptual stage.
