### ISSUE TITLE
anthropic-sonnet3.5 max_token wrong

### ISSUE THREAD

**Issue by wxsunwzx** [langgenius/dify#6626]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

the eewest version Dify and cloud version 0.6.15 have bug that while using  anthropic-sonnet3.5 model will report "[anthropic]Bad Request Error,Error code:400-[type' invalid request error [ message : max tokens 8192> 4096,which is the maximum allowed number of output tokens for claude-3-5-sonnet-20240620)]",i found that the file claude-3-5-sonnet-20240620.yaml in 0.6.15 have wrong max token set and the previous version 0.6.14 was correct,please fix it 

### ✔️ Expected Behavior

fix the problem that can use claude3.5 sonnet in cloud

**Comment by crazywoola** [comment]
Hello this is a beta feature. We introduced this one in this pr https://github.com/langgenius/dify/issues/6335 by @richards199999 .

I guess we still need some time to use 8k tokens in applications.

In the mean time, you could adjust the numbers down to 4096 in order to get things up and running.

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/6843. Will release it tonight.

**Comment by ivanberry** [comment]
on 0.6.15 dify version of self host with docker. the problems is still.

and I check through lobeChat with same model and it worked, but not dify
