### ISSUE TITLE
number variable transfer between nodes raise errors

### ISSUE THREAD

**Issue by hjlarry** [langgenius/dify#6633]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Workflow:
1. in the startnode set a number variable 
2. add a tool node which contains a param like this:
```
  - name: test_number
    type: number
    required: false
    label:
      en_US: Test Number
    form: llm
```
3. set the variable to this tool node, and then run the whole workflow

raise exception `The tool parameter value test_number is not in correct type of number.`

**Comment by baojje** [comment]
The bugs still exist.

**Comment by Sakura4036** [comment]
+1, number variable transfer to tool node raise error

![image](https://github.com/user-attachments/assets/aaede6e2-c62c-442f-85a9-98d78005aa99)

**Comment by hjlarry** [comment]
![image](https://github.com/user-attachments/assets/960a5dc8-2422-47fe-8a87-899e0b363919)
@baojje @Sakura4036  I can't reproduce it, I tried both buildin and custom tools

**Comment by Sakura4036** [comment]
@hjlarry  Did you change the “max_results” parameter in `ddgoo_search` from “form” to “llm”?  I did and then passed the numeric parameter to node error:

![image](https://github.com/user-attachments/assets/1a8afb32-e21e-45fb-bea3-1da73b7d960b)

**Comment by hjlarry** [comment]
@Sakura4036 sure, I tried that, please make sure your current version is the newest from main branch?

**Comment by Sakura4036** [comment]
@hjlarry @baojje   I pull the newest from main branch, and it works fine.

**Comment by baojje** [comment]
> @Sakura4036 sure, I tried that, please make sure your current version is the newest from main branch?

my version is newest ,but it`s work bad, custom tool
![bug](https://github.com/user-attachments/assets/fe693ded-bde1-424e-9dda-34cf3048b591)

**Comment by Sakura4036** [comment]
the newest main branch works fine for me. @baojje 
![image](https://github.com/user-attachments/assets/391d25ae-9c6b-4627-b408-b1073e46ed55)
