### ISSUE TITLE
Cannot set model provider's configurate_methods to "fetch-from-remote"

### ISSUE THREAD

**Issue by jasonhp** [langgenius/dify#6641]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

In any model provider’s yaml config. Set `configurate_methods` to `fetch-from-remote` and start the backend server.

### ✔️ Expected Behavior

According to the doc `api/core/model_runtime/docs/en_US/provider_scale_out.md`, dify supports fetching model list from remote. The server should fetch model list from the provider if `configurate_methods` is set to `fetch-from-remote`.

### ❌ Actual Behavior

The server cannot start. With error: Input should be 'predefined-model' or 'customizable-model' [type=enum, input_value='fetch-from-remote', input_type=str].

**Comment by Sky6662025** [comment]
我也遇到这个问题了：
1 validation error for PluginDaemonBasicResponse[PluginUploadResponse] data.manifest.model.configurate_methods.2 Input should be 'predefined-model' or 'customizable-model' [type=enum, input_value='fetch-from-remote', input_type=str] For further information visit https://errors.pydantic.dev/2.11/v/enum
