### ISSUE TITLE
The browser cannot access the external IP address of the input server and returns 502！

### ISSUE THREAD

**Issue by wsy00** [langgenius/dify#6642]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Deploy according to Docker compose without any modifications.
![1111111111](https://github.com/user-attachments/assets/69e67592-a7c6-46c7-9ca4-ae279a8de192)
Using the external IP address in the bottom left corner of the image, it cannot be accessed through a browser. Is there anything that needs to be set?

**Comment by crazywoola** [comment]
See docs here https://docs.dify.ai/learn-more/faq/self-host-faq#how-to-customize-the-proxy-behavior

**Comment by wsy00** [comment]
> Hello, @wsy00! 👋 I'm here to help you with any bugs, questions, or contributions you have for [Dosu](https://dosu.dev) 🤖
> 
> The 502 error when accessing the external IP address of your input server is likely due to Nginx forwarding the service to the wrong location. To resolve this, follow these steps:
> 
> 1. Ensure the containers are running.
> 2. Run the following command with root privileges to get the IP addresses of the containers:
>    ```shell
>    docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }}: {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
>    ```
> 3. In the output, find the lines corresponding to your web and API containers, for example:
>    ```
>    /docker-web-1: 172.19.0.5
>    /docker-api-1: 172.19.0.7
>    ```
> 4. Note the IP addresses. Then, open the `dify/docker/nginx/conf.d` directory where your Nginx configuration files are stored.
> 5. Replace `http://api:5001` with `http://172.19.0.7:5001` and `http://web:3000` with `http://172.19.0.5:3000` in the Nginx configuration file.
> 6. Restart the Nginx container or reload the configuration.
> 
> Make sure to use the IP addresses obtained from the command and not the exemplary ones provided here. You may need to reconfigure the IP addresses if you restart the related containers [[1]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/learn-more/faq/install-faq.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
Why does the IP display of docker-api-1 seem a bit strange when using this command?
Also, I configured it according to your instructions and restarted it, but the external network still cannot access it
<img width="798" alt="1111111111" src="https://github.com/user-attachments/assets/cace11f2-c24e-4f04-ac97-46295f400d53">
