### ISSUE TITLE
0.6.15 + Iterator invoke tool: Failed to invoke tool: model_name in input form must be one of the following: ['claude-3.5-sonnet', 'gpt-4o', 'gemini-1.5-pro']

### ISSUE THREAD

**Issue by onlyfish79** [langgenius/dify#6643]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. **Workflow**
2. **version 0.6.14 no problem; 0.6.15 report error.**
3. **Iterator input:** models list: ['claude-3.5-sonnet', 'gpt-4o', 'gemini-1.5-pro']
4. Iterator invoke tool, tool requres input model list: ['claude-3.5-sonnet', 'gpt-4o', 'gemini-1.5-pro']
![img_v3_02d3_9a48c4c6-99eb-4911-93e7-7098ea2b813g](https://github.com/user-attachments/assets/ddc8c563-3fc0-4f16-8eb2-41e96007e744)

5. **0.6.14 vs 0.6.15 excute result**

- 0.6.15  invoke tool model_name format: **['1721820680007', 'item']**, report error:

 `Failed to invoke tool: model_name in input form must be one of the following: ['claude-3.5-sonnet', 'gpt-4o', 'gemini-1.5-pro']`

- 0.6.14 invoke tool model_name format: **"claude-3.5-sonnet" (right)**

![img_v3_02d3_9d11a9ca-ffb2-49d2-88d0-c53d090a891g](https://github.com/user-attachments/assets/7ba19e81-1b5f-4472-8336-3f34f41e7480)

**Comment by onlyfish79** [comment]
1. I'm sure the model configuration is correct.

3. In invoke tool(workflow), any model of the following: ['claude-3.5-sonnet', 'gpt-4o', 'gemini-1.5-pro'], can return the correct result. (both 0.6.15 and 0.6.14)

4. Between 0.6.14 and 0.6.15, all configurations are the same. No change.

**Your reply doesn't solve my problem.**

**Comment by crazywoola** [comment]
Hello please stay tuned on this PR. https://github.com/langgenius/dify/pull/6635 :) 
Already working on it.
