### ISSUE TITLE
TTS voice cannot be changed with OpenAI

### ISSUE THREAD

**Issue by monotykamary** [langgenius/dify#6655]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. In a `Chatbot`
1.1. Press the `ADD FEATURE`
1.2. Enable `Text to Speech`
1.3. Select any voice other than `Alloy` and play it

<img width="672" alt="image" src="https://github.com/user-attachments/assets/23aa97dd-5a3e-4d31-964d-73ecab0f5032">

### ✔️ Expected Behavior

Hear different voices after selecting them in the dropdown.

### ❌ Actual Behavior

Only hearing Alloy's voice.

**Comment by crazywoola** [comment]
The voice you chose only works for the old conversation.

If you want to have another voice, you should restart the conversation and make sure you published the application.

**Comment by monotykamary** [comment]
> The voice you chose only works for the old conversation.
> 
> If you want to have another voice, you should restart the conversation and make sure you published the application.

I have restarted the conversation and published the application and the error still persists. It persists across a few deployments I have as well as my local machine.

**Comment by crazywoola** [comment]
Indeed it's a bug actually.

**Comment by crazywoola** [comment]
@charli117 and @ic-xu Could you guys take a look at this one.

**Comment by ic-xu** [comment]
Thank you very much for discovering this phenomenon. I will confirm whether there is this bug today. If so, a fixed version will be released tomorrow.
