### ISSUE TITLE
When importing the knowledge base in batches, I import it according to the specified csv file, but an error keeps appearing. How can I solve this problem?

### ISSUE THREAD

**Issue by 19157681683** [langgenius/dify#6661]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. 知识库
2. 添加分段
3. 批量添加
4. 导入csv文件
[智能报销pdf的分段添加.csv](https://github.com/user-attachments/files/16371462/pdf.csv)

### ✔️ Expected Behavior

answer

### ❌ Actual Behavior

yes

**Comment by crazywoola** [comment]
It seems there is something wrong in your file.

```
"error": "'utf-8' codec can't decode byte 0x87 in position 10: invalid start byte"
```

@dosu Give me a fix based on this error

**Comment by 19157681683** [comment]
明白了，我之前使用wps打开保存csv文件，后面使用Excel保存csv文件就可以了

**Comment by yaohongfenglove** [comment]
Many Chinese users use WPS's Excel software instead of Microsoft's Excel software. When the front-end reads CSV files, it is better to perform encoding judgment and automatic conversion
