### ISSUE TITLE
Regarding the issue that the published iframe cannot reset the session

### ISSUE THREAD

**Issue by 809388027** [langgenius/dify#6664]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I currently want to use an iframe to embed the published chatbot into another web application of mine, but each time I re-enter my application and open the AI, the context still remains, which is quite troublesome for me. Can this be resolved?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We have fulfilled this feature request in this pull request https://github.com/langgenius/dify/pull/6611 however we haven;t released it.
