### ISSUE TITLE
duckduckgo_search error when adding Agent Tools

### ISSUE THREAD

**Issue by imdevopx** [langgenius/dify#6670]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create App > Create from Blank > in Tools click Add..
Internal Server Error appears
and then in logs we saw this.

> ERROR [Dummy-32] [module_import_helper.py:32] - Failed to load module core.tools.provider.builtin.duckduckgo.tools.duckduckgo_search from /app/api/core/tools/provider/builtin/duckduckgo/tools/duckduckgo_search.py: A non-annotated attribute was detected: `name = 'duckduckgo_search'`. All model fields require a type annotation; if `name` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

### ✔️ Expected Behavior

no error and can add tool as expected

### ❌ Actual Behavior

Internal Server Error then Add tool tab keeps on loading

**Comment by crazywoola** [comment]
<img width="487" alt="image" src="https://github.com/user-attachments/assets/0f70f287-8cfe-4c0b-a1f8-923c5a8147c3">
I can not reproduce this problem on Cloud version and latest main branch. Do you have any screenshots of the application configuration.

**Comment by imdevopx** [comment]
@crazywoola i tried replacing https://github.com/langgenius/dify/blob/main/api/core/tools/provider/builtin/duckduckgo/tools/ddgo_search.py

with the one @dosu suggested. but i still got the error.

here's also my screenshot to the said error when you click Create App > Create from Blank > Choose Agent > in Tools click Add.

<img width="953" alt="image" src="https://github.com/user-attachments/assets/1d5e3705-c900-4cbe-83c8-9860d24d8660">
