### ISSUE TITLE
Failed to pull latest main branch due to unsupported filename

### ISSUE THREAD

**Issue by Sakura4036** [langgenius/dify#6676]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

git pull origin main

### ✔️ Expected Behavior

pull success

### ❌ Actual Behavior

```shell
$ git pull origin main
From https://github.com/Sakura4036/dify
 * branch                main       -> FETCH_HEAD
error: invalid path 'api/core/model_runtime/model_providers/bedrock/llm/meta.llama3-1-70b-instruct-v1:0.yaml'
error: invalid path 'api/core/model_runtime/model_providers/bedrock/llm/meta.llama3-1-8b-instruct-v1:0.yaml'
Updating 85a883e28..5e4ac11df
```

**Comment by crazywoola** [comment]
A temp fix for this kind of  problems. https://github.com/langgenius/dify/issues/3704#issuecomment-2071597361

@longzhihun will rename this name later.

**Comment by Sakura4036** [comment]
OK, thanks

**Comment by crazywoola** [comment]
I saw you already open a pr for this. Thanks, I will merge it later.
