### ISSUE TITLE
Knowledge page broken link and bug

### ISSUE THREAD

**Issue by pili-rod** [langgenius/dify#6686]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

The following screenshot is from the Knowledge database. 
- I synced a Notion page to use as knowledge, and the knowledge page is showing this unexpected text. I already checked Notion and everything seems to be ok. I don't know if this is a bug or an unclear error.
- The link linked on `[View documentation](https://docs.dify.ai/user-guide/creating-dify-apps/prompt-engineering)` is not working, the entire session is not listed I think.
<img width="214" alt="Screenshot 2024-07-25 at 4 52 35 PM" src="https://github.com/user-attachments/assets/e7637d64-273e-4949-8ed0-a3b31d364eca">

**Comment by crazywoola** [comment]
Hello this documentation is deprecated. If you would like to read the content there, please use this link.

https://github.com/langgenius/dify-docs/blob/235d2df858bda840017d47a59932b3fc1146896a/en/guides/application-orchestrate/prompt-engineering/prompt-engineering-expert-mode.md

In several releases ago, we replaced advanced mode with the new workflow. 

And yes, this link goes to a wrong place, I will fix it later.

**Comment by pili-rod** [comment]
Looks good now. Thank you!
