### ISSUE TITLE
Prompt generator stops generating text at around 2500 characters

### ISSUE THREAD

**Issue by gijigae** [langgenius/dify#6692]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Prompt generator stops generating text at around 2500 characters. This is due to the [max_tokens](https://github.com/langgenius/dify/blob/bd97ce94895facb59cec14ba398fa8ec10270a46/api/core/llm_generator/llm_generator.py#L133) set to 512 in llm_generator.py.

<img width="2178" alt="image" src="https://github.com/user-attachments/assets/22505920-08f2-482e-aecf-5601afcfb2ad">

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by ZhouhaoJiang** [comment]
Thanks for your contribution! We've reviewed your pull request #6693.
