### ISSUE TITLE
Can the file type of the starting node support MP3 format files

### ISSUE THREAD

**Issue by ykdoit** [langgenius/dify#6711]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We are doing voice to text conversion, and the text is provided to LLM for summary;
1. Convert the audio file to text first
2. Copy the text to the DIY configured workflow and start running it again
We want to configure the first step into dify's workflow, but found that it is not supported

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5346
