### ISSUE TITLE
Text to speach voice issue

### ISSUE THREAD

**Issue by djav1985** [langgenius/dify#6731]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When selecting a text to speech voice no matter what you select it seems only use one of two different options. For example onyx is definitely not the right voice for the selection.

### ✔️ Expected Behavior

Selective voice get the voice

### ❌ Actual Behavior

Selective voice get the wrong one

**Comment by crazywoola** [comment]
Fixed in #6696
