### ISSUE TITLE
Docker compose up fail. "docker-entrypoint-mount.sh" mounted as a directory

### ISSUE THREAD

**Issue by msxfXF** [langgenius/dify#6755]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker compose up

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/c404675a-0e72-430e-91e3-2a2fcb013145">
<img width="920" alt="image" src="https://github.com/user-attachments/assets/9f45a6ff-e99b-4503-ad00-238f33d92d65">

### ✔️ Expected Behavior

docker-entrypoint-mount.sh should be a file

### ❌ Actual Behavior

docker-entrypoint-mount.sh mounted as a directory

**Comment by crazywoola** [comment]
Please copy the whole  `docker` directory instead of copying a single docker-compose file.

**Comment by msxfXF** [comment]
thanks！it&nbsp;works！


---Original---
From: ***@***.***&gt;
Date: Mon, Jul 29, 2024 13:15 PM
To: ***@***.***&gt;;
Cc: &quot;Haofei ***@***.******@***.***&gt;;
Subject: Re: [langgenius/dify] Docker compose up fail.&quot;docker-entrypoint-mount.sh&quot; mounted as a directory (Issue #6755)




 
Please copy the whole  docker directory instead of copying a single docker-compose file.
 
&mdash;

**Comment by neon9809** [comment]
Two more things on this situation:

1. macOS does care upper letter or lower letter by default APFS partition, but Docker Engine on macOS does!!!!!!!!
    for this situation, add /user (lower letter) at Docker Desktop - settings - resources - file sharing - locations
    part of those dead container would start successfully.

2. check docker-compose.yaml - service - dead-container-apps - entrypoint
    those dead containers still cannot wake up after step 1, the value of entry point must be a long config
    just use the mount config from VOLUMES:
       volumes:
    - ./ssrf_proxy/docker-entrypoint.sh:/**### docker-entrypoint.sh**
    - using /docker-entrypoint.sh directly!

**Comment by dannyxu2015** [comment]
> 我也遇到相同问题，请问你的问题解决了吗，是怎么解决的

@fang231291 整个项目clone下来，在docker目录下启动容器组就没有问题的

**Comment by tlintqz** [comment]
> > 我也遇到相同问题，请问你的问题解决了吗，是怎么解决的
> 
> [@fang231291](https://github.com/fang231291) 整个项目clone下来，在docker目录下启动容器组就没有问题的

非常感谢，单独copy docker-compose.yaml不行
