### ISSUE TITLE
Automatic addition of all Ollama models 

### ISSUE THREAD

**Issue by gakugaku** [langgenius/dify#6756]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When selecting Ollama as a model provider and adding models, it is necessary to configure each model individually. If there is only one model registered in Ollama, this is not an issue, but when there are multiple models (e.g., more than 10), it becomes a very tedious task. One of Ollama's attractions is the ability to easily manage multiple models, which makes this problem more significant.

### 2. Additional context or comments

Other tools integrated with Ollama have implemented this feature.

#### Example: [OpenWebUI](https://github.com/open-webui/open-webui)
When the application is started, all models present in Ollama are available for selection.
Sequence: `/api/models` API → [`backend.main.get_models`](https://github.com/open-webui/open-webui/blob/82079e644a291349926008adffe8fe2fc3b33566/backend/main.py#L1061) → [`backend.main.get_all_models`](https://github.com/open-webui/open-webui/blob/82079e644a291349926008adffe8fe2fc3b33566/backend/main.py#L935) → [`ollama.main.get_all_models`](https://github.com/open-webui/open-webui/blob/82079e644a291349926008adffe8fe2fc3b33566/backend/apps/ollama/main.py#L211)
Ollama API: [ollama/docs/api.md List Local Models](https://github.com/ollama/ollama/blob/main/docs/api.md#list-local-models)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Sakura4036** [comment]
+1, Automatic updating of the ollama model list should be done in the settings, requiring the **administrator** to select which models can be used in the application, not all of them!

**Comment by JokerQyou** [comment]
This should be reopened.
