### ISSUE TITLE
The knowledge base contains images and adopts a Q&A segmentation mode. Robot responds with abnormal preview of content images

### ISSUE THREAD

**Issue by Hwting** [langgenius/dify#6763]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

 1. Create a knowledge base.docx content with images
2. Adopt Q&A segmentation mode
3. IA requires answers to the knowledge base with graphics

### ✔️ Expected Behavior

 Using Q&A segmentation mode, AI with images can preview answers normally (knowledge base images display normally when Q&A is not turned on)

### ❌ Actual Behavior

The knowledge base contains images and adopts a Q&A segmentation mode. Robot responds with abnormal preview of content images

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/6672

**Comment by Hwting** [comment]
> Duplicated #6672

It doesn't seem like the same question, as the preview is displayed normally without using Q&A segmentation mode
