### ISSUE TITLE
[Feature Request] Dynamic Authentication Parameter Support in HTTP Interface of Custom Tools

### ISSUE THREAD

**Issue by verigle** [langgenius/dify#6764]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

**Summary:**
I would like to request the addition of a feature that allows the authentication parameters in the HTTP interface to be dynamically set through external variables, rather than being restricted to a single, fixed value.

**Current Behavior:**
Currently, the HTTP interface of custom tool for authentication only supports a fixed value for the authentication parameters, which limits the flexibility and adaptability of the system when dealing with different environments or use cases.

![Uploading image.png…](only support static parameter for auth)

**Desired Behavior:**
The ability to pass authentication parameters as external variables would greatly enhance the flexibility of the system. This would allow users to configure the authentication parameters according to their specific needs without having to hardcode values into the system.

**Use Case:**
In our current setup, we often need to switch between different authentication mechanisms or tokens based on the environment (development, staging, production) or other conditions. Having the ability to set these parameters dynamically would streamline our workflow and reduce the risk of errors associated with manual updates.

**Benefits:**
- Increased flexibility in authentication configuration.
- Improved adaptability to different environments and use cases.
- Reduced risk of errors and manual intervention.

**Technical Details:**
- The feature could potentially be implemented by allowing users to specify an environment variable or a configuration file key that the system would read at runtime to obtain the authentication parameters.
- It would be beneficial if the system could support multiple authentication mechanisms (e.g., Basic Auth, Bearer Tokens, OAuth) and switch between them based on the provided parameters.

### 2. Additional context or comments

**Additional Information:**
- [Any additional context or screenshots that could be helpful in understanding the request.]

Thank you for considering this feature request. I believe it would greatly benefit the user experience and the overall functionality of the system.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Hello the image link is broken.

**Comment by crazywoola** [comment]
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/9f1e3eb5-37c8-480a-a4b9-7b84aa3b13a1">. 
As you can see from above image. It supports using parameters to set it dynamically.

**Comment by 1t5j0y** [comment]
@crazywoola This feature request appears to be to support dynamic authentication parameters in **Custom Tools** whereas the screenshot in the previous comment is for the 'HTTP Request' Chatflow Node.

Requesting a fresh look at this. Thanks.

<img width="846" height="533" alt="Image" src="https://github.com/user-attachments/assets/53c40c58-0a03-4464-a1bd-ee933339530b" />

**Comment by ombhardwajj** [comment]
@1t5j0y Looks like we can use a custom auth token from our work flow by providing an OpenAPI schema that accepts 
`auth-token` in headers and choosing authorization method as none in the tools window.
