### ISSUE TITLE
Failed to load YAML file

### ISSUE THREAD

**Issue by muckthaa-ss** [langgenius/dify#6776]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0..15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/d076ada9-d0a7-432b-9c3f-7bc8b2441af1)
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openai/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openai/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openai/speech2text/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openai/speech2text/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openai/moderation/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openai/moderation/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openai/tts/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openai/tts/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/speech2text/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/speech2text/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/tts/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/azure_openai/tts/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/google/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/google/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/vertex_ai/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/vertex_ai/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/vertex_ai/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/vertex_ai/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/nvidia/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/nvidia/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/nvidia/rerank/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/nvidia/rerank/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/nvidia_nim/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/nvidia_nim/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/togetherai/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/togetherai/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/ollama/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/ollama/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/ollama/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/ollama/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/replicate/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/replicate/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/replicate/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/replicate/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/huggingface_hub/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/huggingface_hub/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/huggingface_hub/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/huggingface_hub/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/rerank/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/rerank/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/speech2text/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/xinference/speech2text/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/triton_inference_server/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/triton_inference_server/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/zhipuai/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/zhipuai/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/zhipuai/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/zhipuai/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/baichuan/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/baichuan/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/baichuan/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/baichuan/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/minimax/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/minimax/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/minimax/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/minimax/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/tongyi/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/tongyi/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/tongyi/tts/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/tongyi/tts/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/tongyi/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/tongyi/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/wenxin/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/wenxin/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/tencent/speech2text/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/tencent/speech2text/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/jina/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/jina/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/chatglm/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/chatglm/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openllm/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openllm/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openllm/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openllm/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/localai/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/localai/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/localai/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/localai/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/localai/rerank/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/localai/rerank/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/localai/speech2text/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/localai/speech2text/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/volcengine_maas/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/volcengine_maas/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/volcengine_maas/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/volcengine_maas/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openai_api_compatible/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openai_api_compatible/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/openai_api_compatible/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/openai_api_compatible/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/perfxcloud/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/perfxcloud/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/novita/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/novita/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/llm/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/llm/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/rerank/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/rerank/_position.yaml'
2024-07-29 19:51:58,771.771 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set

### ✔️ Expected Behavior

flask upgrade 

### ❌ Actual Behavior

error

**Comment by muckthaa-ss** [comment]
but the same retaines

**Comment by crazywoola** [comment]
What commands did you run to upgrade to the v0.6.15?

You could check these files in that directory. I guess you failed to merge the code by running the `git pull` command.
```
/home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/text_embedding/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/text_embedding/_position.yaml'
Failed to load YAML file /home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/rerank/_position.yaml: [Errno 2] No such file or directory: '/home/ubuntu/dify/api/core/model_runtime/model_providers/sagemaker/rerank/_position.yaml'
```

**Comment by muckthaa-ss** [comment]
There is no such path available in the github repository like "dify/api/core/model_runtime/model_providers/sagemaker/text_embedding/_position.yaml" and similarly for other failed to load YAML messages also. There is a _position.yaml in the "dify/api/core/model_runtime/model_provider" path.

**Comment by yuy12** [comment]
Hello, I'm encountering the same issue. Has this problem been resolved? How was it resolved? Thank you very much.

**Comment by muckthaa-ss** [comment]
@yuy12 the isssue still persists but does not affect the dify working. Thank You

**Comment by Kimi-Gao** [comment]
same issue
