### ISSUE TITLE
Bug report template

### ISSUE THREAD

**Issue by iplayfast** [langgenius/dify#6778]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When submitting a bug report, some Chinese text needs to be checked, translating it says that chinese will not be accepted in bug reports. Stop being so cute, it's annoying. I don't speak or read Chinese so this is just a stupid thing to make me check, since I have to translate it to see what it says. 

Secondly, you force me to type in the dify version which isn't obvious since it's already there. Either allow the default to be accepted or force the user to look it up. 

### ✔️ Expected Behavior

asdf

### ❌ Actual Behavior

asdf

**Comment by crazywoola** [comment]
> When submitting a bug report, some Chinese text needs to be checked, translating it says that chinese will not be accepted in bug reports. Stop being so cute, it's annoying. I don't speak or read Chinese so this is just a stupid thing to make me check, since I have to translate it to see what it says.

But someone else would do that.  In case non-english users look up the issues, so that don't have to translate them. :)

> Secondly, you force me to type in the dify version which isn't obvious since it's already there. Either allow the default to be accepted or force the user to look it up.

That's a placeholder, we don't modify this template often, when we upgrade the version, it will remain the same for a while, besides other developers would use the older version. 

Last but not least, I am cute.

**Comment by guchenhe** [comment]
hi @iplayfast, thanks for the feedback - as @crazywoola said, this is since we have many chinese users submitting issues in chinese. But i do see your point and have modified the issue templates accordingly. @crazywoola can you review it please?
