### ISSUE TITLE
Added intent recognition node

### ISSUE THREAD

**Issue by Geek-Bob** [langgenius/dify#6783]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Similar to the current problem classifier, but instead of simply classifying the current text, you need to determine the user's intent according to the context, and then go through the defined intent flow branch.

For example, check the express, this process requires multiple rounds of dialogue to complete, it requires the user to provide mobile phone number, single number, express company and other information, and these information need to guide the user through multiple rounds of questions and answers to complete the information input, and extract the information, after the completion of all the information through multiple rounds of dialogue, and confirm the correctness of the information with the user, in order to carry out the final execution of the query action.

### 2. Additional context or comments

Example:

User: Check express logistics information
Assistant: Please provide the mobile phone number, tracking number and express company
User: My mobile number is **********
Assistant: Thank you for providing your mobile phone number, but also need to provide, tracking number and Courier company
User: I forgot the order number
Assistant: You can view your order information
User: Yes, my tracking number is ********
Assistant: Glad you found it. You also need to provide a Courier company
User: ****
Assistant: Thank you for your patience with all the information. I need to confirm with you again: your mobile phone number: *******, tracking number: ******, express company: ****
User: I gave you the wrong phone number. It's *****
Assistant: OK, the revised information your mobile number: *******, tracking number: ******, express company: ****
User: That's right
Assistant: According to the information you provided, the logistics information found is as follows: ******

This is only one process in the entire AI assistant, but a good AI assistant should cover hundreds of similar processes. Therefore, an intention recognition node is needed to control the flow of the process. Even if the user suddenly changes the conversation content and then continues, this node still supports the remaining process execution

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by alterxyz** [comment]
Hi,

customer service conversation intent classification is one of the [Question Classifier's](https://docs.dify.ai/guides/workflow/node/question-classifier#advanced-settings) feature.
<https://docs.dify.ai/guides/workflow/node/question-classifier#advanced-settings>

![image](https://github.com/user-attachments/assets/f74c5728-4044-417a-b5e8-bca02521c8e0)

Add your instruction (prompt) and open Memory for Question Classifier

**Comment by crazywoola** [comment]
@Geek-Bob @alterxyz 

With the ability of the conversational variable, it can be integrated with classifier as well. Hope this solves your problem.

**Comment by Geek-Bob** [comment]
> @Geek-Bob @alterxyz
> 
> 凭借会话变量的能力，它也可以与分类器集成。希望这能解决您的问题。

I tried, but it's very easy to get categorized into incorrect categories, especially when it comes to multiple conversations, even when memory is turned on and prompt words are added. The current classifiers are more like keyword matching of the latest text, and do not have comprehensive analysis and classification according to context information

**Comment by Geek-Bob** [comment]
I tried, but it's very easy to get categorized into incorrect categories, especially when it comes to multiple conversations, even when memory is turned on and prompt words are added. The current classifiers are more like keyword matching of the latest text, and do not have comprehensive analysis and classification according to context information

**Comment by MrNiebit** [comment]
确实不太准，是大模型的问题么
