### ISSUE TITLE
the node "Knowledge Search" return empty

### ISSUE THREAD

**Issue by HaiShin** [langgenius/dify#6789]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I found that when I used the node "Knowledge Search" and this node was associated with multiple knowledge bases, the search results returned empty. At the same time, I could not see my search operation on the backtest page of the knowledge base.

### ✔️ Expected Behavior

The knowledge search node should return results, and I can see my search operation on the backtest page of the knowledge base.

### ❌ Actual Behavior

the search results returned empty. At the same time, I could not see my search operation on the backtest page of the knowledge base.

**Comment by HaiShin** [comment]
> Hello @HaiShin! I'm here to help you with any bugs, questions, or contributions while you wait for a human maintainer. Let's tackle this issue together!
> 
> The "Knowledge Search" node in Dify version 0.6.13 returning empty results and not showing search operations on the backtest page when associated with multiple knowledge bases is likely due to improper configuration of the retrieval strategy and recall mode.
> 
> To resolve this issue, follow these steps:
> 
> 1. **Select Query Variable**: Ensure that the correct query variable is chosen, typically `sys.query` for dialogue applications.
> 2. **Choose Knowledge Bases**: Verify that the knowledge bases to be queried are correctly selected and pre-created in Dify.
> 3. **Configure Recall Mode and Knowledge Base Settings**: Properly configure the recall mode and knowledge base settings. Dify offers different recall strategies such as "N-choose-1 Recall" and "Multi-way Recall" which need to be appropriately set based on the retrieval scenario.
> 4. **Connect and Configure Downstream Nodes**: Ensure that the downstream nodes, usually LLM nodes, are correctly connected and configured to use the output variable `result` from the knowledge retrieval node.
> 
> Supporting evidence from the document:
> 
> * "选择查询变量，用于作为输入来检索知识库中的相关文本分段，在常见的对话类应用中一般将开始节点的 `sys.query` 作为查询变量；"
> * "选择需要查询的知识库，可选知识库需要在 Dify 知识库内预先创建；"
> * "配置召回模式和知识库设置；"
> * "连接并配置下游节点，一般为 LLM 节点；"
> 
> Ensure that each knowledge base associated with the node has its retrieval strategy correctly configured and that the appropriate recall strategy is selected [[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/workflow/node/knowledge-retrieval.md)[[2]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/guides/workflow/node/knowledge_retrieval.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Yes, I confirmed that I completed the above check, and it still returns null. At the same time, I ran the node alone and it also returned null.

**Comment by HaiShin** [comment]
I am very sure that I have completed the above checks. In addition, I have also done related tests in the Dify cloud version and found that they all return empty.

**Comment by HaiShin** [comment]
> I also have the same problem. When my application is only associated with one knowledge base, it takes effect, associates with two knowledge bases, and the search result is empty.

I found that the above phenomenon is because of the recall setting.
[https://docs.dify.ai/v/zh-hans/guides/knowledge-base/integrate_knowledge_within_application#guan-lian-zhi-shi-ku-bing-zhi-ding-zhao-hui-mo-shi](url)

**Comment by thepush2** [comment]
谢谢

**Comment by crazywoola** [comment]
Is this issue resolved?

**Comment by HaiShin** [comment]
> Is this issue resolved?

I haven't had time to try it yet, and I'm closing this issue after two days of verification
