### ISSUE TITLE
Bug in API /workflows/run

### ISSUE THREAD

**Issue by amitshuklabag** [langgenius/dify#6809]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Use the Docker tag "main" to deploy a new application.
2. Set up a new workflow as required by your application.
3. API Request the /workflows/run API endpoint.
API returns a response with the following error message: `{
    "message": "Internal Server Error",
    "code": "unknown"
}
`

4. Log Error Details: The logs show the following error trace:

```
app-api-1         | 2024-07-30 14:14:49,236.236 ERROR [Dummy-27] [app.py:838] - Exception on /v1/workflows/run [GET]
app-api-1         | Traceback (most recent call last):
app-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
app-api-1         |     rv = self.dispatch_request()
app-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
app-api-1         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
app-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
app-api-1         |     resp = resource(*args, **kwargs)
app-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
app-api-1         |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
app-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
app-api-1         |     resp = meth(*args, **kwargs)
app-api-1         |   File "/app/api/controllers/service_api/wraps.py", line 75, in decorated_view
app-api-1         |     return view_func(*args, **kwargs)
app-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 696, in wrapper
app-api-1         |     resp = f(*args, **kwargs)
app-api-1         | TypeError: WorkflowRunApi.get() missing 1 required positional argument: 'workflow_id'
```

**Note**: According to the documentation, the `workflow_id` parameter is not required when calling the API. Instead, it should be returned in the response. This discrepancy suggests that there might be an issue with how the API is handling requests or responses.

### ✔️ Expected Behavior

Response from the API  based on the doc.

### ❌ Actual Behavior

{
    "message": "Internal Server Error",
    "code": "unknown"
}

**Comment by amitshuklabag** [comment]
I have tried to call the CURL after your update from the DOC.

`curl -X POST 'http://xxxxxxxxxxxxxxxxxxxx/v1/workflows/run' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "response_mode": "streaming",
    "user": "abc-123"
}'
`

It returns an error response
`{
    "code": "method_not_allowed",
    "message": "The method is not allowed for the requested URL.",
    "status": 405
}`

I'm calling the API Execute workflow POST `/workflows/run`

**Comment by amitshuklabag** [comment]
Thanks for the quick fix; I appreciate it.

**Comment by smlHao** [comment]
> workflow_id

hi,  How to pass the workflow_id parameter， i don`t find the workflow_id in url or request body

**Comment by smlHao** [comment]
> > workflow_id
> 
> hi, How to pass the workflow_id parameter， i don`t find the workflow_id in url or request body

@amitshuklabag
