### ISSUE TITLE
hope that ordinary chat rooms will add Internet screening functions

### ISSUE THREAD

**Issue by Lxx-c** [langgenius/dify#6813]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When we used Dify, we found that if there was no relevant content in the knowledge base, we would go back to LLM to search. However, if the data trained in LLM was not the latest, the answers given would be inaccurate or outdated. In addition, the tool plug-in can only be used in Agent mode. However, after using the Internet tool, I found that it did not seem to screen the knowledge base. I hope to add Internet queries to ordinary chat rooms, especially when the knowledge base recall data is empty, it will get data from the Internet and then answer through LLM.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You could do that by using workflow.
<img width="744" alt="image" src="https://github.com/user-attachments/assets/1538a776-2e63-4f72-85e0-f09b16ab70d2">
