### ISSUE TITLE
I need that Dify supports Xinference authentication feature.

### ISSUE THREAD

**Issue by michaelChe956** [langgenius/dify#6820]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

My Xinference server requires SK authentication. When integrating Xinference LLM with Dify, I need that Dify supports this authentication feature.
## Dify version
main
## Cloud or Self Hosted
Self Hosted (Docker)

i find that there is not set the authorization in the func (_get_xinference_extra_parameter) when i set the sk in the fontend.I think it is the same in use Xinference llm.
![图片](https://github.com/user-attachments/assets/317262c1-5230-467b-9cb7-732fcd68ea5b)
<img width="631" alt="图片" src="https://github.com/user-attachments/assets/0fb12844-28ef-4cee-833b-5512623d1bcd">

i also find this issue(https://github.com/langgenius/dify/issues/6415),but i think it can not solve my issue.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by elepherai** [comment]
+1

**Comment by GarfieldDai** [comment]
@michaelChe956 You can begin to make a PR.

**Comment by ethan-fly** [comment]
I have fixed this issue. Please refer to #7369 for details.

This PR is currently open. You can temporarily disable Xinference's authentication by running the following command: `xinference-local -H 0.0.0.0 -p 9997`
