### ISSUE TITLE
number  transfer data incorrectly in custom tool nodes

### ISSUE THREAD

**Issue by baojje** [langgenius/dify#6821]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

no 
![bug](https://github.com/user-attachments/assets/1f4b50db-e4c0-4821-8361-17bb7e6c458b)

**Comment by crazywoola** [comment]
I don't know why you input a no in steps to reproduce. This is not helpful to us to investigate the issue, at lease you could provide the DSL file.

**Comment by Sakura4036** [comment]
try update to the newest main branch again. @baojje 
The code in docker is not up to date with the latest fixes, you need to go into the container and update the code, or use `source deployment` instead of docker.
