### ISSUE TITLE
After upgrade dify version Add model fail

### ISSUE THREAD

**Issue by Jesean** [langgenius/dify#6827]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I upgrade the dify backend, and restart it. 
Then I found the models I added before was lost. 
And when I tried to readd them, got the error like"An error occurred during credentials validation: API request failed with status code 503:"
Also, the flask app log occurred "POST /console/api/workspaces/current/model-providers/ollama/models HTTP/1.1" 400 -"
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/3ef89244-96b6-4127-a915-0ace41692b77">

**Comment by crazywoola** [comment]
If you failed to add the model, you can run `flask reset-keypair`. And try to add those providers again.
