### ISSUE TITLE
There is no output when the workflow ends

### ISSUE THREAD

**Issue by wj1017090777** [langgenius/dify#6831]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

There is no output when the workflow ends.  I noticed that the interface was completed and the content was returned.My output is quite long. I don't know if this is the reason. If so, how can I solve it?
![1722412344644](https://github.com/user-attachments/assets/395c407c-37d1-4269-a0cb-198084c20e6f)

But there is output during workflow orchestration testing
![1722412588629](https://github.com/user-attachments/assets/5f79fcab-7b79-4fce-b5ef-6895752af6da)

### ✔️ Expected Behavior

Get the output content

**Comment by crazywoola** [comment]
If a workflow execution time exceeds 60s, then there will be no response, this is known issue, please do not open duplicated bug report. 

This is addressed by this PR https://github.com/langgenius/dify/pull/6450, yet we haven't decide how to deal with this issue.

**Comment by MingqianZhang** [comment]
does the script "/vs/loader.js" handle the display of result? the script is executed for workflow returning the result but not for workflow requiring long execution

**Comment by shuai-huaman** [comment]
If it is a cloud service, how to modify this timeout period
