### ISSUE TITLE
When cleaning documents in the knowledge base, the CPU is too high

### ISSUE THREAD

**Issue by wuminghui-coder** [langgenius/dify#6832]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Cloud

### Steps to reproduce

If there is too much text to be cleaned, the interface processing will be very slow, causing the interface to be blocked. After consulting relevant knowledge, API blockage in the Flask framework can lead to CPU spikes

API interface for cleaning api.add_resource(DatasetIndexingEstimateApi, '/datasets/indexing-estimate')
![image](https://github.com/user-attachments/assets/3f5ccd74-f2cc-4a02-bb1b-0e8cdd6785c1)

**Comment by 13428116504** [comment]
是本地部署，不是云端的

**Comment by 13428116504** [comment]
This text segmentation and cleaning interface task was not processed by Celery, and the processing is very slow. The interface is like blocking, and the system performance has become extremely poor. When can the backend experts optimize it

**Comment by yfz123456** [comment]
We also encountered a similar problem, uploading more than 10M files, the entire dify application stuck. Looking forward to the official reply, how to effectively deal with this problem

**Comment by 13428116504** [comment]
> We also encountered a similar problem, uploading more than 10M files, the entire dify application stuck. Looking forward to the official reply, how to effectively deal with this problem我们也遇到过类似的问题，上传超过10M的文件，整个dify应用卡住了。期待官方回复，如何有效处理这个问题

I have now placed the cleaning task for this interface on Celery for asynchronous execution, which will not cause any lag

**Comment by yfz123456** [comment]
That sounds great. How do you handle it? Can you tell me how to handle it

**Comment by yfz123456** [comment]
> > We also encountered a similar problem, uploading more than 10M files, the entire dify application stuck. Looking forward to the official reply, how to effectively deal with this problem我们也遇到过类似的问题，上传超过10M的文件，整个dify应用卡住了。期待官方回复，如何有效处理这个问题
> 
> I have now placed the cleaning task for this interface on Celery for asynchronous execution, which will not cause any lag

That sounds great. How do you handle it? Can you tell me how to handle it

**Comment by loki-keroro** [comment]
> > We also encountered a similar problem, uploading more than 10M files, the entire dify application stuck. Looking forward to the official reply, how to effectively deal with this problem我们也遇到过类似的问题，上传超过10M的文件，整个dify应用卡住了。期待官方回复，如何有效处理这个问题
> 
> I have now placed the cleaning task for this interface on Celery for asynchronous execution, which will not cause any lag



> > We also encountered a similar problem, uploading more than 10M files, the entire dify application stuck. Looking forward to the official reply, how to effectively deal with this problem我们也遇到过类似的问题，上传超过10M的文件，整个dify应用卡住了。期待官方回复，如何有效处理这个问题
> 
> I have now placed the cleaning task for this interface on Celery for asynchronous execution, which will not cause any lag

你好，能请教一下，如何解决的吗？
