### ISSUE TITLE
Encountered 'Internal Server Error' when setting NOTION_INTEGRATION_TYPE to 'internal' and providing a SECRET. Binding Notion resulted in 'Internal Server Error

### ISSUE THREAD

**Issue by da-peng** [langgenius/dify#6840]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4097f5e0-e38e-415f-9e1f-21d06eed8c4c)
![image](https://github.com/user-attachments/assets/5aa83e3e-179b-4431-a260-583043190da1)

### ✔️ Expected Behavior

Binding Notion sccessfull

### ❌ Actual Behavior

Binding Notion resulted in 'Internal Server Error

**Comment by crazywoola** [comment]
Fixed in #6836, will release it tonight.
