### ISSUE TITLE
Running workflow cannot specify workflow ID

### ISSUE THREAD

**Issue by smlHao** [langgenius/dify#6841]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Dify 0.6.11 

curl -X POST 'https://xxxxxxxxx/v1/workflows/run' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {},
    "response_mode": "streaming",
    "user": "abc-123"
}'

hi,   want to run the specified workflow , how to pass the parameter  workflow_id ， i don`t find the workflow_id in url or request body, 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by smlHao** [comment]
> Hey @smlHao, I'm here to help you with any issues or questions you have about Dify. I can assist with bug fixes, answer any technical questions, and guide you on how to become a contributor. Let me know how I can assist you!
> 
> To run a specified workflow in Dify 0.6.11, you need to include the `workflow_id` parameter in the request body. Here is how you can modify your cURL request to include the `workflow_id`:
> 
> ```shell
> curl -X POST 'https://xxxxxxxxx/v1/workflows/run' \
> --header 'Authorization: Bearer {api_key}' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "workflow_id": "your_workflow_id",
>     "inputs": {},
>     "response_mode": "streaming",
>     "user": "abc-123"
> }'
> ```
> 
> Make sure to replace `"your_workflow_id"` with the actual ID of the workflow you want to run [[1]](https://github.com/langgenius/dify/blob/main/web/app/components/develop/template/template_workflow.zh.mdx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

thanks !!!   I had tried this, works fine

**Comment by crazywoola** [comment]
The ` workflow_id` is return in response body, and it can not be specified.

**Comment by yuzh2001** [comment]
@smlHao after digging through tons of codes, find out that dify use `api-key` to identify which workflow you are using. Each workflow/completion has unique api key(which is not intuitive at all and against the normal concept of apikey).

**Comment by smlHao** [comment]
> @smlHao after digging through tons of codes, find out that dify use `api-key` to identify which workflow you are using. Each workflow/completion has unique api key(which is not intuitive at all and against the normal concept of apikey).

Yeah !!!!     the request body can still function normally without the workflow_id, and the result is also correct ,
api-key and workflow_id are one-to-one

**Comment by yuzh2001** [comment]
> > @smlHao after digging through tons of codes, find out that dify use `api-key` to identify which workflow you are using. Each workflow/completion has unique api key(which is not intuitive at all and against the normal concept of apikey).
> 
> 
> 
> Yeah !!!!     the request body can still function normally without the workflow_id, and the result is also correct ,
> 
> api-key and workflow_id are one-to-one

the workflow_id is useless(try remove it). it should be the api key that matters

**Comment by smlHao** [comment]
> > > @smlHao after digging through tons of codes, find out that dify use `api-key` to identify which workflow you are using. Each workflow/completion has unique api key(which is not intuitive at all and against the normal concept of apikey).
> > 
> > 
> > Yeah !!!!     the request body can still function normally without the workflow_id, and the result is also correct ,
> > api-key and workflow_id are one-to-one
> 
> the workflow_id is useless(try remove it). it should be the api key that matters

yes, had remove it ,thanks !!!

**Comment by posssss** [comment]
我测试发现使用的是API key区分工作流
