### ISSUE TITLE
Spider.cloud tool throws error on API key authorization ('NoneType' is not iterable)

### ISSUE THREAD

**Issue by akramer-zibra** [langgenius/dify#6842]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Spider.cloud tool is not yet authorized
- Add a "Web Scraper & Crawler" into a workflow (Studio)
- Click "To authorize"
- Add a valid API key for spider.cloud
- Click "Save"

### ✔️ Expected Behavior

A saved API key AND a spider.cloud workflow component, which works.

### ❌ Actual Behavior

The UI shows an error "argument of type 'NoneType' is not iterable". The API key is not saved.

![image](https://github.com/user-attachments/assets/ac929083-c376-4b3c-9fdd-ee1e108d2595)

Any idea how to fix this? I would be pleased to share a fix for this.

**Comment by crazywoola** [comment]
Already fixed in https://github.com/langgenius/dify/pull/6835 will release it tonight.

**Comment by akramer-zibra** [comment]
Oh, yes. Perfect. Thank you very much for this information @crazywoola

Am 31. Juli 2024 13:00:55 MESZ schrieb crazywoola ***@***.***>:
