### ISSUE TITLE
"Error with 'Sonnet 3.5' model on Dify: '>' not supported between instances of 'NoneType' and 'int'"

### ISSUE THREAD

**Issue by ottoradiologia** [langgenius/dify#6851]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Access the Dify console.
Set up the agent with the "Sonnet 3.5" model.
Send a request to the agent.
Encounter error: "'>' not supported between instances of 'NoneType' and 'int'".

### ✔️ Expected Behavior

The 'Sonnet 3.5' model should process the request without errors.

### ❌ Actual Behavior

![bug](https://github.com/user-attachments/assets/b95bd464-834f-4b2a-ac91-50a71be71017)
An error occurs when calling the 'Sonnet 3.5' model.

It seems there is an issue with the API call for the 'Sonnet 3.5' model. This problem might have started after a recent update.

**Comment by tamanobi** [comment]
I also encountered the same error. I was able to avoid the error by setting the max_tokens value, which was optional.
