### ISSUE TITLE
Add support for third-party AI API (https://deepbricks.ai)

### ISSUE THREAD

**Issue by kson34** [langgenius/dify#6856]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I can use deepbricks api to add claude3.5 on lobehub, but I can't add claude in dify. In addition, I can use deepbricks api to add GPT4o to dify. Can this be solved?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by greycodee** [comment]
Because deepbricks.ai supports the openai interface specification, you can use deepbricks.ai by changing the Api Base.
![Xnip2024-08-01_11-51-06](https://github.com/user-attachments/assets/32fdb2a8-ce73-45d0-819a-9d78bf0f4ae8)

**Comment by kson34** [comment]
As I described, openAI is supported, but claude is not.
![bug00](https://github.com/user-attachments/assets/8a9636aa-4b44-4b3a-91e1-0764d22b659f)
