### ISSUE TITLE
Unable to Display Duckduckgo Image Search

### ISSUE THREAD

**Issue by imdevopx** [langgenius/dify#6857]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create from Blank > Chatbot > Chatflow. Start > DuckduckGo Image Search > Answer.  (Displays Blank Image with url: /files/tool/image.jpg?...)
My FILES_URL var is empty, is this the reason? if yes, what value should i input? i am using weaviate also.

### ✔️ Expected Behavior

Displays photo based on my query in chat.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/cb4a3693-5e99-4b53-901c-1e28b644ad49)

**Comment by imdevopx** [comment]
may i know which service runs on port 8000? seems i don't remember any ports using this on my docker-compose.

**Comment by crazywoola** [comment]
Run `docker compose ps`

**Comment by imdevopx** [comment]
@crazywoola sorry forgot we run it on ecs. here's the ff services:
- api -> port: 5001
- worker
- web -> port: 3000
- weaviate -> port 8080
- nginx -> port 80
- sandbox -> port 8195
- ssrf_proxy -> 3128

**Comment by hjlarry** [comment]
@imdevopx this issue is not your config problem, please try later again when the PR is merged
