### ISSUE TITLE
When setting ETL_TYPE to Unstructured, the local docker runs and reports an error when creating the knowledge base.

### ISSUE THREAD

**Issue by biofer** [langgenius/dify#6872]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

dify-api:0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/eee6574f-da97-480a-b7b9-ccabece90071">

Local docker run, set environment variables `.env` 

```
ETL_TYPE=Unstructured
UNSTRUCTURED_API_URL=https://api.unstructuredapp.io/general/v0/general
UNSTRUCTURED_API_KEY=*****
```
The above error occurs when creating the knowledge base and starting the setup.

**Comment by biofer** [comment]
I followed the official tutorial to start docker, if there is something wrong with the docker image, why don't you provide the latest docker image?

**Comment by biofer** [comment]
Any plans or details to divulge, my friend? @JohnJyong 
After the local image goes in, following this fails, so hopefully I can release the official integrated image.
```
import nltk
nltk.download('punkt')
```

**Comment by biofer** [comment]
I would think that since the official docs give instructions, shouldn't they be followed and shouldn't it just work silky smooth?
Or is the experience of the domestic user unimportant and untested?

**Comment by crazywoola** [comment]
He is currently on vacation. Here is a similar issue raised long time ago. https://github.com/langgenius/dify/issues/4659

**Comment by biofer** [comment]
> Any plans or details to divulge, my friend? @JohnJyong After the local image goes in, following this fails, so hopefully I can get the official integrated image.
> 
> ```
> import nltk
> nltk.download('punkt')
> ```

So hopefully I can get a mirror image with no problems.
