### ISSUE TITLE
ai completion result not shown

### ISSUE THREAD

**Issue by MingqianZhang** [langgenius/dify#6874]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

<img width="429" alt="Screen Shot 2024-08-01 at 1 53 01 PM" src="https://github.com/user-attachments/assets/2a315ccb-ea8d-4ed0-a14c-7edefa8fd17c">

when running workflow, the frontend did not show result although the result is already generated in backend (i can see it in logs). Also when click on result (结果), the result content still not shown. 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated #6831
