### ISSUE TITLE
Run failed: Node Knowledge Retrieval run failed: 'score'

### ISSUE THREAD

**Issue by muckthaa-ss** [langgenius/dify#6875]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I have created the knowledge and also done the retrieval testing. While I have used the knowledge in the chatflow, the knowledge retrieval block is throwing an error message saying "Run failed: Node Knowledge Retrieval run failed: 'score'". I have used an embedding model and a rerank model in the hybrid method for retrieval.
![Screenshot 2024-08-01 113442](https://github.com/user-attachments/assets/13bdfe3b-7b28-4242-8d43-002ce8fec8d3)

### ✔️ Expected Behavior

The chatflow is completed and the response for the query is obtained after retrieving from the knowledge.

### ❌ Actual Behavior

error

**Comment by muckthaa-ss** [comment]
I have checked the above mentioned and also verified it but I get the same error.

**Comment by muckthaa-ss** [comment]
I have checked these too. The issue still persists.

**Comment by JohnJyong** [comment]
if you are using the source code deployment , pls update the latest code , restart both api and web service , thanks @muckthaa-ss
