### ISSUE TITLE
I can't use tools in agent using Ollama Llama3.1:8b 

### ISSUE THREAD

**Issue by cowcomic** [langgenius/dify#6879]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

use ollama run llama3.1:8b
create agent use llama3.1 use tools: simple_code
ask: 使用python程序计算1000以内除11余5的数的个数

![image](https://github.com/user-attachments/assets/a3999a98-76ca-4a12-8e13-9bc610ea29d1)

### ✔️ Expected Behavior

run code and echo the result

### ❌ Actual Behavior

just print code and no action

**Comment by cowcomic** [comment]
Has it been resolved? Cant find in release feature
@crazywoola

**Comment by hoang-shakudo** [comment]
@cowcomic Correct me if I'm wrong but I think they haven't support function calling from Ollama yet. Have been waiting for this since the release of llama3.1 and Mistral Nemo

**Comment by cowcomic** [comment]
llama3.1 has "tools" tag on describe page, so I thought it support tools call
@hoang-shakudo 

![image](https://github.com/user-attachments/assets/c8c25293-87d4-4aaf-abc3-b1d607b45afe)

what is the meaning of this "tools",  I'm confused
