### ISSUE TITLE
Inquiry: Full-Text Search Support in Dify Supported Vector DBs

### ISSUE THREAD

**Issue by Q-Ot** [langgenius/dify#6880]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello, I am currently using Weaviate as a vector database and have encountered an issue where the full-text search portion consistently returns an empty list when performing full-text or hybrid searches.
In this issue #6508 regarding full-text search, I noticed that contributors to dify pointed out that Weaviate does not support full-text search and recommended switching to Qdrant.

In the Dify Chinese documentation, I found that Dify supports vector databases such as Weaviate, Qdrant, Milvus, Zilliz, MyScale, and TiDB_Vector (btw, TiDB_Vector is not mentioned in the English documentation).
I would like to know which of those above-mentioned vector databases support full-text search.
Additionally, is the lack of full-text search support in Weaviate due to the vdb itself not providing such functionality?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Qdrant does support full-text search.

**Comment by Q-Ot** [comment]
@dosu Thank you for your response. May I assume that Qdrant, MyScale, TiDB_Vector, and Milvus (versions >= 2.3.x) all support full-text search? 
Additionally, in Weaviate, after conducting some tests, the search_by_full_text method always returns an empty list.

**Comment by mzh1996** [comment]
> ```python
> "Error during query:
> ```

+1 
The returned list is empty even when I copy a sentence from the doc in the corresponding dataset.

**Comment by mzh1996** [comment]
> @dosu @crazywoola Thank you for your response. I've search search_by_full_text in code repo. May I assume that only Qdrant, MyScale, OpenSearch, Analyticdb_vector,oraclevector, Weaviate support full-text search? Additionally, in Weaviate, I've done some tests, the search_by_full_text method always returns an empty list.

+1
The returned list is empty even when I copied a sentence as the query from the doc in the corresponding dataset.
