### ISSUE TITLE
Migrate `volcengine_maas` from v2 to v3.

### ISSUE THREAD

**Issue by jianglin1008** [langgenius/dify#6881]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Volcano Ark has upgraded model invocation to a new version, which is now V3, supporting more parameters. An error occurred during the use of V2, which needs to be resolved by upgrading to V3. For example:
`[volcengine_maas] Error: Detailed exception information is listed below.\nreq_id: 20240801032331000050830874F6132DBE\ncode_n: 1709602\ncode: FunctionCallPostProcessError\nmessage: model generated content is invalid`

### 2. Additional context or comments

[SDK V3](https://www.volcengine.com/docs/82379/1263482)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by LeoLiuYan** [comment]
+1
