### ISSUE TITLE
The basic chat studio answer extraction is incomplete, resulting in interrupted answers.

### ISSUE THREAD

**Issue by Lxx-c** [langgenius/dify#6898]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Hello, during the question-and-answer process of the basic chat function, the answer will be interrupted. The following is the LLM answer processing information I extracted from the log. This log is obtained from line `576` of the `core\model_runtime\model_providers\openai_api_compatible\llm\llm.py` file. The specific code is as follows:
```python 
        # transform response
        result = LLMResult(
            model=response_json["model"],
            prompt_messages=prompt_messages,
            message=assistant_message,
            usage=usage,
        )
        logger.info(f"阻塞问答LLM回复: {result}")
```
From here on, the log information starts. The answer to the specific interruption is at the bottom of the log, and the information is `content='种植玉米的步骤如下：\n\n1. **土壤准备**：选择疏松'`,You can use this to quickly locate log information.

```log
阻塞问答LLM回复: model='qwen2-7b-instruct' prompt_messages=[SystemPromptMessage(role=<PromptMessageRole.SYSTEM: 'system'>, content="Use the following context as your learned knowledge, inside <context></context> XML tags.\n\n<context>\n问题: 如何实现玉米种植过程中的节水灌溉？;答案: (1)改变传统的玉米灌水方法-地面灌溉。20世纪80年代后期,推广了一些新的灌水方法,如水平畦(沟)灌、波涌灌、长畦分段灌等，节水效果有很大提高。(2)喷灌和滴灌。喷灌技术具有输水效率高、地形适应性强和改善田间小气候的特点,且能够和喷药、除草等农业技术措施相配合,节水、增产效果良好。对水资源不足、透水性强的地区尤为适用\n问题: 春夏玉米间南瓜 秋冬雪菜接两茬这个种植模式如何栽培管理玉米？;答案: 玉米双行种植，每隔1.7米栽2行玉米，行距30厘米，株距20厘米，每亩栽3200株。做好施肥和防病工作，具体措施同常规栽培。\n问题: 如何进行鲜食玉米的播种?;答案: 鲜食玉米可依据种植类型、品质特性、自然条件及市场需求和加工需要，确定不同的播种时间和采取相应的种植形式。一是根据市场行情确定播期，可春播或夏播。春播要在地温稳定通过10摄氏度左右播种；二是采用地膜覆盖或育苗移栽形式，可提早上市，取得较好经济效益。另外，为了及早上市，防止集中上市,错开上市高峰，使新鲜玉米果穗均衡上市，可采用分期播种，错期最少10天以上\n问题: 如何实现玉米播种的苗全、苗齐、苗壮？;答案: 首先早整地、整好地、保持良好的墒情，其次精选种子并在播种前晒种提高发芽势和发芽率，采用多功能种子包衣剂进行包衣，保证播种深浅一致及覆土厚度一致，并合理增加种植密度。\n问题: 玉米与大豆之间如何进行间作种植？;答案: 一）选用适宜品种玉米应选用叶片紧凑、秆硬抗倒、发育整齐、适于密植的良种；大豆应选用早熟性或耐荫结荚多的品种。（二）种植方式一般2行玉米间作2行大豆，或2行玉米间作4行大豆，或6行玉米间作2行大豆。（三）水肥管理一般亩施复合肥5～7千克，保证苗全苗壮。幼苗期这两种作物都比较耐旱，一般不干旱可不必灌溉，有利蹲苗，促根深扎\nquestion:种植玉米的步骤是什么？ answer:种植玉米的步骤包括选择合适的种子、准备土壤、播种、浇水、施肥、除草和病虫害防治。首先，选择适合当地气候和土壤条件的玉米品种。然后，对土壤进行深耕和施肥，以提供充足的养分。播种时，按照推荐的行距和株距进行，确保适当的密度。播种后，保持土壤湿润，适时施肥以促进生长。在生长过程中，定期除草并监控病虫害，采取必要的防治措施。\n问题: 让我查找有关如何种植玉米的信息;答案: 种植玉米的步骤如下：\\n1.土壤准备：选择疏松、肥沃、排水良好的土壤，并进行充分的排水和松土工作。\\n2.种植时间：玉米是夏季作物，一般要在春季末或夏季初进行种植。具体种植时间根据气候条件和当地的种植经验而定。\\n3.播种：在土壤表面开沟，将种子均匀地撒在沟内，然后轻轻覆盖土壤，并稍微压实。每个种子之间应保持一定的间隔距离。\\n4.浇水：在播种后，及时进行浇水，保持土壤湿润，但不要过度浇水\n问题: 让我查找有关如何种植玉米的信息;答案: 种植玉米的步骤如下：\\n1. 土壤准备：选择疏松、肥沃、排水良好的土壤，并进行充分的排水和松土工作。\\n2. 种植时间：玉米是夏季作物，一般要在春季末或夏季初进行种植。具体种植时间根据气候条件和当地的种植经验而定。\\n3. 播种：在土壤表面开沟，将种子均匀地撒在沟内，然后轻轻覆盖土壤，并稍微压实。每个种子之间应保持一定的间隔距离。\\n4. 浇水：在播种后，及时进行浇水，保持土壤湿润，但不要过度浇水\n问题: 玉米在地里如何种植;答案: (1)玉米的播种播前种子准备（1）选用良种:根据各地自然条件和种植制度等不同，选用不同良种。（2） 精选种子:一般采用穗选和机械、风力粒选等。穗选应在玉米制种的种子田里或晒场上进行，对所选果穗脱粒做到去两头、留中间，然后用风力或机械进行粒选,达到粒大、饱满，生命力强。对选好的种子，播前应做发芽试验,尤其是从外地调入的种子,更应把好种子发芽试验关,保证种子发芽率达到90%以上\n</context>\n\nWhen answer to user:\n- If you don't know, just say that you don't know.\n- If you don't know when you are not sure, ask for clarification.\nAvoid mentioning that you obtained the information from the context.\nAnd answer according to the language of the user's question.\n\n", name=None), AssistantPromptMessage(role=<PromptMessageRole.ASSISTANT: 'assistant'>, content='种植玉米的步骤如下：\n\n1. **土壤准备**：选择疏松、肥沃、排水良好的土壤，并进行充分的排水和松土工作。确保土壤pH值在6.0到7.0之间，以利于玉米生长。\n\n2. **种植时间**：玉米是夏季作物，一般在春季末或夏季初进行种植。具体时间根据当地的气候条件和种植经验而定。\n\n3. **播种**：在土壤表面开沟，将种子均匀地撒在沟内，然后轻轻覆盖土壤，并稍微压实。每个种子之间应保持一定的间隔距离，通常为30-45厘米，具体取决于品种和预期的密度。\n\n4. **浇水**：在播种后，及时进行浇水，保持土壤湿润，但不要过度浇水，以避免种子腐烂。\n\n5. **施肥**：播种前或播种后，施用适量的肥料，以提供玉米生长所需的养分。通常使用复合肥，根据土壤测试结果和当地推荐的施肥量进行施用。\n\n6. **除草**：在玉米幼苗阶段，定期除草，以减少杂草对水分和养分的竞争。\n\n7. **病虫害防治**：定期检查玉米植株，注意病虫害的迹象，如玉米螟、蚜虫等。根据需要使用合适的农药进行防治。\n\n8. **灌溉**：在干旱条件下，需要定期灌溉，保持土壤湿润，尤其是在玉米生长的关键时期，如抽雄期和灌浆期。\n\n9. **收获**：玉米成熟后，根据品种的不同，通常在玉米穗的基部叶片开始变黄、干枯时进行收获。使用收割机或人工收割，将玉米穗从植株上割下。\n\n通过遵循这些步骤，可以有效地种植玉米并获得丰收。', name=None, tool_calls=[]), UserPromptMessage(role=<PromptMessageRole.USER: 'user'>, content='玉米如何种植？', name=None)] message=AssistantPromptMessage(role=<PromptMessageRole.ASSISTANT: 'assistant'>, content='种植玉米的步骤如下：\n\n1. **土壤准备**：选择疏松', name=None, tool_calls=[]) usage=LLMUsage(prompt_tokens=1604, prompt_unit_price=Decimal('0'), prompt_price_unit=Decimal('0'), prompt_price=Decimal('0E-7'), completion_tokens=16, completion_unit_price=Decimal('0'), completion_price_unit=Decimal('0'), completion_price=Decimal('0E-7'), total_tokens=1620, total_price=Decimal('0E-7'), currency='USD', latency=1.0444217156618834) system_fingerprint=Non
```

### ✔️ Expected Behavior

Hopefully the answer is complete, because the data that LLM responds to is complete, and the data that should not be answered is incomplete.

### ❌ Actual Behavior

I have been asking the same question multiple times in the same session which has led to this issue. It is important to note that the chat room is tied to the knowledge base.

**Comment by crazywoola** [comment]
Have you set the max_tokens?

**Comment by Lxx-c** [comment]
At the beginning, the default 'max_tokens'=4096 was used,After the robot prompted me to adjust the parameter, the problem temporarily resolved. I am not sure if there will be any issues in the future.However, as shown in the figure below, when I adjusted it to 8000, it exceeded that value when requested, and then OpenAI reported an error.
![image](https://github.com/user-attachments/assets/efc91420-8f55-4273-b577-74791b3f0e63)

**Comment by Lxx-c** [comment]
@crazywoola Hello, I still have the same problem. After setting the maximum context and maximum token in the model settings, through testing, the maximum tokens have little effect on the answer, almost no effect, and the parameter with the greatest impact is the context. If the context is set too small, the answer content will be interrupted. But if it is set too large, when the value of total_tokens reaches the maximum context I set after multiple answers, it will also be interrupted. After one interruption, this value seems to be initialized, and the answer will be normal after initialization. The `total_tokens` in the above description comes from line 442 of the `core\model_runtime\model_providers\openai_api_compatible\llm\llm.py` file. The JSON fragment is as follows:
```
{
    "id": "01915035c8940356dc50c6abfd5a97e0",
    "object": "chat.completion.chunk",
    "created": 1723627587,
    "model": "Qwen/Qwen2-7B-Instruct",
    "choices": [
        {
            "index": 0,
            "delta": {
                "content": "管理"
            },
            "finish_reason": None,
            "content_filter_results": {
                "hate": {
                    "filtered": False
                },
                "self_harm": {
                    "filtered": False
                },
                "sexual": {
                    "filtered": False
                },
                "violence": {
                    "filtered": False
                }
            }
        }
    ],
    "system_fingerprint": "",
    "usage": {
        "prompt_tokens": 1747,
        "completion_tokens": 2,
        "total_tokens": 1749
    }
}
```
