### ISSUE TITLE
EN language chat occur Chinese

### ISSUE THREAD

**Issue by ThousandsStars** [langgenius/dify#6899]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

**The chat history summary sometimes in Chinese, but the setting or chatlog don't have any Chinese word.**

![image](https://github.com/user-attachments/assets/2afac09b-98e9-4383-bb44-295ea1a05b06)

### ✔️ Expected Behavior

All the chat history in English

### ❌ Actual Behavior

Some the chat history in Chinese

**Comment by WeepsDanky** [comment]
Can you please share your chat history to help me fix this? The prompt of chat history summary depends on the first query you ask. It specifies if there is a mix of chinese and english words in your query, it will output a chinese title.
