### ISSUE TITLE
可不可以支持一下国内的OpenAI的API代理，例如 https://api2d.com/

### ISSUE THREAD

**Issue by goodyorkye** [langgenius/dify#69]
本地部署要一直保持稳定的梯子挺难

**Comment by takatost** [comment]
可以在 docker-compose.yaml 中的 api 和 worker 服务加一条 environments 记录
```
OPENAI_API_BASE: 'https://<your-openai-mirror-domain>/v1'
```

**Comment by yuhao1118** [comment]
> 可以在 docker-compose.yaml 中的 api 和 worker 服务加一条 environments 记录
> 
> ```
> OPENAI_API_BASE: 'https://<your-openai-mirror-domain>/v1'
> ```

这个pr还没有merge吧？

**Comment by lethe3000** [comment]
> > 可以在 docker-compose.yaml 中的 api 和 worker 服务加一条 environments 记录
> > ```
> > OPENAI_API_BASE: 'https://<your-openai-mirror-domain>/v1'
> > ```
> 
> 这个pr还没有merge吧？

在自己的docker-compose.yaml中设置环境变量，不需要改动代码

**Comment by killpanda** [comment]
> > > 可以在 docker-compose.yaml 中的 api 和 worker 服务加一条 environments 记录
> > > ```
> > > OPENAI_API_BASE: 'https://<your-openai-mirror-domain>/v1'
> > > ```
> > 
> > 
> > 这个pr还没有merge吧？
> 
> pr 只是声明下参数，openai 的包可以直接读环境变量

但现在有个问题，就是在系统后台变更`key`的时候，使用的 `/moderations` 接口，很多第三方API代理都不支持这个接口。导致第三方key无法配置成功

**Comment by dsbruce** [comment]
请问, 用国内的镜像代理有测试成功的吗?我试了还是不行

**Comment by killpanda** [comment]
@dsbruce  我用的aiproxy.io，成功了

**Comment by Huiguorou12** [comment]
> @dsbruce 我用的aiproxy.io，成功了

请问aiproxy.io是什么？可以了解一下吗？（我原来的代理突然不能用了）
