### ISSUE TITLE
add function of direct vectorization for Q&A pairs file, eg. csv

### ISSUE THREAD

**Issue by ja3592** [langgenius/dify#6904]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

If  Q&A data pairs have been already prepared, the user prefers to upload them without further dividing the content, and proceed directly with vectorization, we would appreciate it if you could provide the functionality for this. Thank you!

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by nadirvishun** [comment]
One of the current methods is to upload a random document of a few words, and then open this document, in the "Add chunk" -> "Batch Add" to upload the qa csv file has been prepared, and then the original automatically generated segement deleted!

**Comment by dajianguo** [comment]
+1

**Comment by dajianguo** [comment]
I have a modify. like this,you can try:
![image](https://github.com/user-attachments/assets/d31c81b6-7b13-40f7-b50e-ff9390da00db)

![image](https://github.com/user-attachments/assets/e9dc8b98-938a-4392-86b9-6d112de188e9)

![image](https://github.com/user-attachments/assets/8f25a106-e493-4f6e-922e-879c078266c1)

![image](https://github.com/user-attachments/assets/9b4f4f50-2fca-4d9b-8b50-1721c07ef70c)

**Comment by dajianguo** [comment]
@crazywoola    I have a same problem, so i modify the code.  Can i commit it?   
Like question #4664, i think it's a common requirement。
