### ISSUE TITLE
The workflow has ended, but there is no output on the front end of the page, and the workflow keeps spinning.

### ISSUE THREAD

**Issue by xiaoxuanyo** [langgenius/dify#6906]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. After creating a workflow and publishing it, use the front-end page to access and run it.
![image](https://github.com/user-attachments/assets/d13f93cc-3159-4df1-8f94-0476b7857111)
![image](https://github.com/user-attachments/assets/fd15cf8d-3dc0-4f71-a4e6-60c76b6bcc2e)

### ✔️ Expected Behavior

The front-end page displays the running results

### ❌ Actual Behavior

There is no output on the front end of the page, and the workflow keeps spinning.

**Comment by crazywoola** [comment]
Duplicated
