### ISSUE TITLE
When will the community version support multiple workspaces？

### ISSUE THREAD

**Issue by xin0815** [langgenius/dify#6914]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

When will the community version support multiple workspaces？

**Comment by crazywoola** [comment]
Multi-tenant is enterprise version feature, we will not introduce this into community version. :) If you do have a feature request please reach out to business@dify.ai.
