### ISSUE TITLE
Code tool fails when null property exists in object

### ISSUE THREAD

**Issue by dnyg** [langgenius/dify#6915]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a `Code` block
2. Set output variable to be object
3. Add following code:

```
function main() {
    return {
        result: {
            a: null
        }
    }
}
```

### ✔️ Expected Behavior

That the code block returns the result object with the a property set to null

### ❌ Actual Behavior

I get the error:

>Output .result.a is not a valid type.

**Comment by rhardih** [comment]
Same behaviour for Python as well, setting the output to be an Object as well.

```python
def main():
    return {
        "result": {
            "prop": None
        }
    }
  ```

**Comment by greycodee** [comment]
I'm trying to fix that.
