### ISSUE TITLE
can not get knowledge database ||无法获取知识库列表

### ISSUE THREAD

**Issue by marsDes** [langgenius/dify#6923]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

creat a new app and use context 
can not get knowledge databases 
----------------------
新建应用并使用上下文功能，新建知识库后 

### ✔️ Expected Behavior

在顶部知识库tab可以查看已上传的的知识库

### ❌ Actual Behavior

can not get knowledge databases  on tage?type=knowledge
-----------
在顶部的知识库tab 无法查看。导致无法重复引用

/console/api/datasets?page=1&limit=30 
return  []

**Comment by crazywoola** [comment]
A screenshot of the page would be appreciated.

**Comment by marsDes** [comment]
> 如果您能提供该页面的截图我们将非常感激。

![image](https://github.com/user-attachments/assets/e2f152c0-8123-4141-bf3a-113f0699d8b2)

在[cloud.dify.ai](https://cloud.dify.ai/apps)，我创建应用的时候 使用上下文功能新增一个知识库。可以下次新建应用的时候选中

**Comment by marsDes** [comment]
> A screenshot of the page would be appreciated.
i think It might be an issue with the development environment or permissions. After I redeployed the application, it is now working normally.
