### ISSUE TITLE
json output property is empty when a workflow is used as tool in another workflow

### ISSUE THREAD

**Issue by akramer-zibra** [langgenius/dify#6924]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

(1) Create a workflow (A) which gets a simple string `input` parameter at start and provides this as `result` when this workflow ends.

<img width="319" alt="Screenshot Workflow-A" src="https://github.com/user-attachments/assets/f567ec6b-fb64-408c-b022-1c05bea30a7d">

(2) Create a second workflow (B) which gets a simple `input` parameter at start, passes this parameter as input into workflow A. This parent workflow provides `text`, `files` and `json` as final output, when it ends.

<img width="443" alt="Screenshot Workflow-B" src="https://github.com/user-attachments/assets/1f89cd3a-8537-4eb5-8f1b-6473a8cefe96">

(3) Run the parent workflow (B) with the input `Hello World!`

### ✔️ Expected Behavior

The `json` property in the result of the parent workflow (B) contains the result of the integrated workflow (A): 
```json
{
    "text": "...",
    "files": [],
    "json": {
        "result": "Hello World!"
    }
}
```

### ❌ Actual Behavior

The `json` property in the result of the parent workflow (B) is an empty array. And there is also a wrong stringified version of the expected result in the `text` property.
```json
{
  "text": "{\"result\": \"1722627351591.name\"}",
  "files": [],
  "json": []
}
```

**Comment by crazywoola** [comment]
In fact, the content returned by another workflow will be returned in 'text', although there is a field called 'json', but it is only used in some cases

**Comment by akramer-zibra** [comment]
Oh, I see. This behaviour may confuse some users, because it breaks with common api expectations. Providing json-data in a stringified variant inside a json-object leads to extra data transformation afterwards. Receiving the output-data of such embedded workflow, would simplify the data access and also decrease error probability (due to the extra data transformation). 

So I'd like to propose the following change: Let's provide the output-data of an embedded workflow also in the `json` property of this tool.

If the maintainers are okay with this, I am open to provide a PR for this @crazywoola .

**Comment by akramer-zibra** [comment]
@dosu please show me the code, which runs a workflow as a tool within the api service.

**Comment by akramer-zibra** [comment]
Okay. Thank you @dosu . I see the `outputs` variable in context of `WorkflowNodeExecution` is set on `SUCCEEDED` status with `json.dumps` function. Please show me the python code, where a workflow is executed as a "tool" like the other builtin tools, for example searxng, stable diffusion, jina etc.

**Comment by akramer-zibra** [comment]
Beautiful @dosu ! How do I need to change `_invoke` method of `WorkflowTool` class, so the returned `result` variable will also contain the `outputs` data in json format?

**Comment by akramer-zibra** [comment]
Hmm @dosu . Your suggestion looks very like the original code. Please tell me if there is a `create_json_message` method on `Tool` class and if so, how to use it.

**Comment by akramer-zibra** [comment]
Perfect. I think this is a 95% solution for this issue. Never expected this quality of support from a chatbot. Thank you very much for your untiring help dosubot !
