### ISSUE TITLE
X-App-Code header is missing

### ISSUE THREAD

**Issue by zslswlw** [langgenius/dify#6938]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

My browser runs in a proxy environment to access the internet， After deploying and running the application, upon redirecting to the application page, the page displays a 404 error indicating the application is not available. There is an error message in the top right corner stating "X-App-Code header is missing".

**Comment by crazywoola** [comment]
Please follow the instructions as the bot said, you are running behind a proxy which could lead you haven't set the headers correctly. Once you add something like below should resolve your problem.

```
server {
    listen 80;
    server_name your_domain.com;

    location / {
        proxy_pass http://your_dify_container:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-App-Code your_app_code;  # Add this line to include the X-App-Code header
    }
}
```
