### ISSUE TITLE
Fail to Set Up Authorization of SearXNG base url

### ISSUE THREAD

**Issue by forhonourlx** [langgenius/dify#6942]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When setting up Authorization of SearXNG base url, get error:
```
HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a0636fa00>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
![image](https://github.com/user-attachments/assets/155f4b0b-af33-41b8-8f40-1cbea14d73a9)

`settings.yml` is already set to:
```
search:
  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - json    # <-- add this line 
```
`http://[localhost:8080/search?q=SearXNG&format=json&categories=general](http://localhost:8080/search?q=SearXNG&format=json&categories=general)` and html web page could be access successfully.
So, what's reason of this problem and how to slove?
Could somebody kindly help? Thanks inadvance.

### ✔️ Expected Behavior

Success setting up Authorization of SearXNG base url

### ❌ Actual Behavior

```
HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a0636fa00>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by hjlarry** [comment]
It seems your 8080 port is occupied,  try another port instead?
By default,  the weaviate vector db use the 8080 port

**Comment by hjlarry** [comment]
you can enter the docker container, try to see if the url can be accessed,  or try another port like 8081

**Comment by forhonourlx** [comment]
I retried with searxng installation `docker run -d -p 8083:8080 -v "${PWD}/searxng:/etc/searxng" -e "BASE_URL=http://0.0.0.0:8080/" -e "INSTANCE_NAME=searxng" searxng/searxng`
Still got:
`HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /?q=SearXNG&format=json&categories=general (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1318374b80>: Failed to establish a new connection: [Errno 111] Connection refused'))`

![image](https://github.com/user-attachments/assets/fab288b1-5191-4225-897c-7315571946a7)

HELP!

> you can enter the docker container, try to see if the url can be accessed, or try another port like 8081

**Comment by forhonourlx** [comment]
Tried for days...
searxng on localhost:8083 could be access successfully. 
So what's wrong with my config? 
![image](https://github.com/user-attachments/assets/2a1c19d1-5e84-4c47-a9c2-8b3462d5c1c9)
@hjlarry

**Comment by forhonourlx** [comment]
Any way to diagnosis?

**Comment by hjlarry** [comment]
enter the docker container to try curl the url,  the error is your python code request the url not work

**Comment by forhonourlx** [comment]
Thanks inadvance.

I notice that 9 containers in dify project, I tried on `nginx-1` container, is that right?
![image](https://github.com/user-attachments/assets/16b9b5fa-8a16-46f9-bcb7-64355a2d4c0d)

docker gets results:
```
 docker exec -it a0b265ab7b1d735d3958820cfb4bd63374596411fa0c08bf61830735eef664e3 /bin/bash
root@a0b265ab7b1d:/# curl http://127.0.0.1:8083
curl: (7) Failed to connect to 127.0.0.1 port 8083 after 0 ms: Couldn't connect to server
root@a0b265ab7b1d:/# curl http://localhost:8083
curl: (7) Failed to connect to localhost port 8083 after 0 ms: Couldn't connect to server
```

and windows gets results:
```
C:\Users\simon>curl http://localhost:8083
<!DOCTYPE html>
<html class="no-js theme-auto center-aligment-no" lang="en-EN" >
<head>
  <meta charset="UTF-8" />
  <meta name="description" content="SearXNG — a privacy-respecting, open metasearch engine">
  <meta name="keywords" content="SearXNG, search, search engine, metasearch, meta search">
  <meta name="generator" content="searxng/2024.7.29+7d47c961c">
  <meta name="referrer" content="no-referrer">
  <meta name="robots" content="noarchive">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="HandheldFriendly" content="True">
  <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
  <title>searxng</title>
......
```

> enter the docker container to try curl the url, the error is your python code request the url not work

**Comment by hjlarry** [comment]
the `api-1` container is your python codes execute container
`localhost` usually means container self,  try `http://host.docker.internal:8083` instead,  or ask the LLM why can't connect to local computer from docker inside

**Comment by forhonourlx** [comment]
Many thanks.
If using docker searxng,  Setting Up Authorization of SearXNG base url `http://host.docker.internal:8083` is the answer.

**Comment by eakkawat** [comment]
Changing from http://localost:8081 to http://host.docker.internal:8083  works for me.

**Comment by galatanovidiu** [comment]
using https://github.com/searxng/searxng-docker

Make sure you set:
`SEARXNG_HOSTNAME=http://host.docker.internal:8082` on `.env` 

On docker-compose.yml
```
searxng:
    ports:
      - "8082:8080"
```

On dify set the `SearXNG base URL` to 
http://host.docker.internal:8082

Replace the port with whatever port you want.
