### ISSUE TITLE
Add memory capability to Agents

### ISSUE THREAD

**Issue by hehedahehe** [langgenius/dify#6944]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I found the project https://docs.mem0.ai/, and I think memory capability is essential for an agent.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
<img width="416" alt="image" src="https://github.com/user-attachments/assets/6761c840-abb2-451d-a5ab-57626651b1fd">

**Comment by AugustLHHHHHH** [comment]
> <img alt="image" width="416" src="https://private-user-images.githubusercontent.com/100913391/354954642-6761c840-abb2-451d-a5ab-57626651b1fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk3NzQwNjUsIm5iZiI6MTczOTc3Mzc2NSwicGF0aCI6Ii8xMDA5MTMzOTEvMzU0OTU0NjQyLTY3NjFjODQwLWFiYjItNDUxZC1hNWFiLTU3NjI2NjUxYjFmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxN1QwNjI5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmMyNTg3NTkwOGM5OGFmNWNjNzQwOGM3MWUwYmZiNmZjYjA5NmIyYWUzYWMyY2NmOGRlZWExZTBmNGUyZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P6aVXQFnjCjd4BuPD5B9Yud4bXmyf-2AfGxKyTIBpXc">

Set memory window is incoming short term memory, right? Where mem0 support long term memory. @crazywoola
