### ISSUE TITLE
Docker Compose deploy Max Token setting failure

### ISSUE THREAD

**Issue by HAjiMa666** [langgenius/dify#6947]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="479" alt="image" src="https://github.com/user-attachments/assets/9a2a728e-d248-49e0-a7cd-2d7bab76e92c">
<img width="459" alt="image" src="https://github.com/user-attachments/assets/027aafa2-6369-4e6b-9a1f-3d020fb82e81">
<img width="476" alt="image" src="https://github.com/user-attachments/assets/3386e24f-f5ca-41e8-8153-4e09bda94f51">

this are steps
when I have set maxToekn, close and open again.
it restore.
Please fix it

### ✔️ Expected Behavior

can update successfully

### ❌ Actual Behavior

restore origin value

**Comment by crazywoola** [comment]
You need to publish it. Then it will be saved to the new conversation.

**Comment by HAjiMa666** [comment]
> You need to publish it. Then it will be saved to the new conversation.

It still restore.
I use local code to run , it has not the problem
