### ISSUE TITLE
The model results in the workflow keep returning empty

### ISSUE THREAD

**Issue by zxzxde** [langgenius/dify#6957]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

使用worklfow执行模型返回的是内容一直是空，如果换成对话流程是可以正常返回的。
![image](https://github.com/user-attachments/assets/23c8ff63-88b0-4d2b-bf4e-848c28d31eba)
![image](https://github.com/user-attachments/assets/2d8d0a5f-6d32-4143-8a03-7b7ff65396f5)

**Comment by Pranav-Official** [comment]
Hi..... Seems like i am getting the same error 

![image](https://github.com/user-attachments/assets/6450b710-575c-48b4-86b9-50746233e941)


am I missing something?.. on the latest pull
