### ISSUE TITLE
Allowing users to set and manage multiple keys themselves.

### ISSUE THREAD

**Issue by chalitbkb** [langgenius/dify#6958]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Is it possible to set up multiple API keys from providers like OpenAI or Gemini? Sometimes my API key hits its limit, and I'd like to automatically switch to another key from a backup list instead of manually setting each one. I feel like I'm wasting time having to set a new API key every time it exceeds the usage limit.

Additionally, it would be great if users could set multiple keys themselves as mentioned above. Even better, if possible, it would be fantastic to allow users to specify a personal API endpoint to fetch external API lists for use.
![image](https://github.com/user-attachments/assets/2a99ba8f-36c2-40cf-98aa-18ef428d7a90)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/6921#issuecomment-2265249998

This feature is only available for SaaS Pro and Team user. We will not introduced this feature in CE version at this moment.
