### ISSUE TITLE
Number type input parameter not parsed correctly in workflow tool invocation

### ISSUE THREAD

**Issue by NiXuebing** [langgenius/dify#6959]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

We encountered an error while calling a custom tool within our workflow. The tool is defined as follows in our OpenAPI specification:

```
openapi: 3.0.0
info:
  title: Log Analysis API
  version: 1.0.0
  description: API for analyzing log differences and logs.
paths:
  /api/v1/log-analysis-to-markdown:
    post:
      summary: Analyze logs within a specified time range and output in markdown format.
      operationId: log_analysis_to_markdown
      requestBody:
        description: Log analysis to markdown request payload.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisRequest'
      responses:
        '200':
          description: Log analysis to markdown completed successfully.
components:
  schemas:
    AnalysisRequest:
      type: object
      properties:
        start_time:
          type: integer
          example: 1622505600
        end_time:
          type: integer
          example: 1622591999
        app_name:
          type: string
          example: example_app
        comp_name:
          type: string
          example: example_component
      required:
        - start_time
        - end_time
        - app_name
        - comp_name

```

Define the custom tool using the above OpenAPI specification.
Invoke the tool within a workflow.
Encounter an error during the workflow execution.
![image](https://github.com/user-attachments/assets/8bf1075e-41f3-43fa-8c52-0ab7b7f80022)

![image](https://github.com/user-attachments/assets/cdae8644-25e4-4933-8954-e1e58ba78816)

Specifically, the start_time parameter is passed as ["1715911915996", "start_time"], which cannot be parsed correctly.
![image](https://github.com/user-attachments/assets/10cd68d8-579d-4458-82c1-edd4c3ee7ea7)

### ✔️ Expected Behavior

The workflow should call the custom tool successfully and complete the log analysis, returning the output in markdown format.

### ❌ Actual Behavior

The workflow fails when attempting to call the custom tool.

**Comment by hjlarry** [comment]
https://github.com/langgenius/dify/pull/6646 This PR has fixed this, please try 0.6.16
