### ISSUE TITLE
Uploaded data status keep queuing

### ISSUE THREAD

**Issue by yuqiliao** [langgenius/dify#696]
Dify version: Cloud

## Steps To Reproduce

The issue as mentioend in #483 seems recurring as of today: when I uploaded a few .md or .txt files, the status column keeps saying it's queuing without making any progress. Could anyone kindly point out if I'm missing anything here? Thanks! Please see the screenshot below.

## The current behavior

![image](https://github.com/langgenius/dify/assets/11021157/bd48ba7b-e813-4feb-a469-5b475a95df0d)

## The expected behavior

I was expecting to see all progress bar to be 100% and I can then see the chatbot reference the newly uploaded data.

**Comment by takatost** [comment]
We have already optimized for this situation. The reason is that some teams' OpenAI api-key quotas are insufficient, causing constant retries and blocking queue consumption.

**Comment by GeoZhanglw** [comment]
I am also confused about the same problem. I uploaded a few txt files, and Dify kept telling me they were queuing. Is there anything I missed?
![image](https://github.com/langgenius/dify/assets/131643794/7702afdf-8798-490f-b7dd-b26174295af2)

**Comment by robertobalestri** [comment]
Me 2too, i have the same problem

**Comment by mandado** [comment]
same problem here

**Comment by simplast** [comment]
me too
