### ISSUE TITLE
<MilvusException: (code=2, message=Fail connecting to server on 127.0.0.1:19530. Timeout)>

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#6960]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The configuration of the env is as follows:
VECTOR_STORE=milvus
# Milvus configuration Only available when VECTOR_STORE is `milvus`.
# The milvus host.
MILVUS_HOST=127.0.0.1
# The milvus host.
MILVUS_PORT=19530
# The milvus username.
MILVUS_USER=root
# The milvus password.
MILVUS_PASSWORD=Milvus
# The milvus tls switch.
MILVUS_SECURE=false

when I create the knowledge base, I encounter an error：
<MilvusException: (code=2, message=Fail connecting to server on 127.0.0.1:19530. Timeout)>

![image](https://github.com/user-attachments/assets/744f112b-3b38-4991-900c-ccd1c85d156e)

**Comment by awangB** [comment]
Have you solved this problem？

**Comment by taowang1993** [comment]
I also have this problem!

**Comment by yuhp-zts** [comment]
> Have you solved this problem？
add  milvus  networks in worker and api
    networks:
      - ssrf_proxy_network
      - default
      - milvus

**Comment by yuhp-zts** [comment]
> I also have this problem!

add  milvus  networks in worker and api
    networks:
      - ssrf_proxy_network
      - default
      - milvus
