### ISSUE TITLE
Updated the App but Still seeing the Old Version

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#6979]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Updated the app by following the docs:
cd dify/docker
docker compose down
git pull origin main
docker compose pull
docker compose up -d

But still seeing the older version number when opening the app.
<img width="492" alt="image" src="https://github.com/user-attachments/assets/079afe27-9a6e-49cb-b8fc-674b8e622168">

But the images are all up to date.
<img width="773" alt="image" src="https://github.com/user-attachments/assets/dc5741de-ca75-47c0-9d3c-ea6377ba2872">

**Comment by shelltea** [comment]
The same issue, after the upgrade, the interface still shows version 0.6.15.

**Comment by wizd** [comment]
Docker images are wrong also.

**Comment by crazywoola** [comment]
Please pull the code and image from latest branch and run the upgrade process again. We have rebuilt the v0.6.16. https://github.com/langgenius/dify/releases/tag/0.6.16

**Comment by takatost** [comment]
Big sorry about that, due to unknown reasons, the target branch for the new 0.6.16 release was wrong, I've recreated the release and docker images, could you please pull down the images and try again?

**Comment by kurokobo** [comment]
Confirmed that the latest image is truly 0.6.16 with the latest changes 🎉
![image](https://github.com/user-attachments/assets/f2cc77a7-7a64-40ef-9929-357b2f118439)

@crazywoola @takatost 
Thanks for working on this!

**Comment by taowang1993** [comment]
Thanks for the quick fix. Now my app is updated. Thank you Dify team.
