### ISSUE TITLE
he install（Account registration） page keeps getting stuck，Version 0.6.15

### ISSUE THREAD

**Issue by Gogoworks** [langgenius/dify#6981]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### **Dify Version 0.6.15 Self Hosted，Incident Report or Problem Report**

**Alibaba Cloud ECS (Elastic Compute Service)，Public network access**

**Environmental conditions**

**dify/api/.env**

_39.100.*.*  Public network access_

`
CONSOLE_API_URL=http://39.100.*.*:5001

CONSOLE_WEB_URL=http://39.100.*.*:3058

SERVICE_API_URL=http://39.100.*.*:5001

APP_WEB_URL=http://39.100.*.*:3058

FILES_URL=http://39.100.*.*:3058`

--------------------------------------------------------------------------------------------------------------------
**Environmental conditions**
**dify/web/.env.local**

`
NEXT_PUBLIC_DEPLOY_ENV=DEVELOPMENT

NEXT_PUBLIC_EDITION=SELF_HOSTED

NEXT_PUBLIC_API_PREFIX=http://localhost:5001/console/api

NEXT_PUBLIC_PUBLIC_API_PREFIX=http://localhost:5001/api

NEXT_PUBLIC_SENTRY_DSN=`

**Start command.**
flask run --host 0.0.0.0 --port=5001 --debug

npm run start --port=3058 --host=0.0.0.0

**服务器防火墙完成放行：5001,3058**

Remote access to http://39.100.*.*:3058/install
 (Note: * represents any character, this is an IP address with some numbers omitted)

**he install（Account registration） page keeps getting stuck**

![image](https://github.com/user-attachments/assets/a4520dc5-31ce-42ff-b948-c32d81f9f2ed)

### ✔️ Expected Behavior

**I believed it was due to incorrect URL settings in environment variables, I hope someone can help me access this service remotely.**

**Comment by crazywoola** [comment]
```
NEXT_PUBLIC_API_PREFIX=http://localhost:5001/console/api

NEXT_PUBLIC_PUBLIC_API_PREFIX=http://localhost:5001/api
```

These two should be the same as 

```
CONSOLE_API_URL=[http://39.100.*.*:5001](http://39.100.%2A.%2A:5001/)

CONSOLE_WEB_URL=[http://39.100.*.*:3058](http://39.100.%2A.%2A:3058/)

```

**Comment by Gogoworks** [comment]
> ```
> NEXT_PUBLIC_API_PREFIX=http://localhost:5001/console/api
> 
> NEXT_PUBLIC_PUBLIC_API_PREFIX=http://localhost:5001/api
> ```
> 
> These two should be the same as
> 
> ```
> CONSOLE_API_URL=[http://39.100.*.*:5001](http://39.100.%2A.%2A:5001/)
> 
> CONSOLE_WEB_URL=[http://39.100.*.*:3058](http://39.100.%2A.%2A:3058/)
> ```

Sorry, I don't quite understand this explanation.
Is it...?

NEXT_PUBLIC_API_PREFIX=http://39.100.%2A.%2A:5001/console/api
NEXT_PUBLIC_PUBLIC_API_PREFIX=http://39.100.%2A.%2A:3058

CONSOLE_API_URL=http://39.100.%2A.%2A:5001/

CONSOLE_WEB_URL=http://39.100.%2A.%2A:3058/


Is this correct?

It's so frustrating..........


Wishing for an answer！
