### ISSUE TITLE
Simultaneous execution of two nodes in parallel

### ISSUE THREAD

**Issue by mdxlCJ** [langgenius/dify#6991]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

How to make two nodes run in parallel after a node, and then accumulate the results after completion

**Comment by crazywoola** [comment]
Duplicate question, wrong template for feature request as well. We are working on it.
