### ISSUE TITLE
chattts cannot autoplay

### ISSUE THREAD

**Issue by tsiens** [langgenius/dify#6997]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、Add tts to workflow functionality，And turn on autoplay
![image](https://github.com/user-attachments/assets/e2799d7f-92f3-4181-a6dc-ac248ec1dae7)
2、Running tasks in the workflow，chattts cannot autoplay，And I didn't see any tts requests
![image](https://github.com/user-attachments/assets/ca94d689-326c-4a56-a4ec-88dee6974186)

**Comment by crazywoola** [comment]
You need to publish it and create a new conversation to make it work.

**Comment by tsiens** [comment]
> You need to publish it and create a new conversation to make it work.
i publish it and create a new conversation，but it doesn't play automatically.I still need to manually click the play button
![image](https://github.com/user-attachments/assets/0f695d10-b1a1-4c34-85f9-76df03418892)

**Comment by crazywoola** [comment]
@ic-xu Could you take a look at this?

**Comment by ic-xu** [comment]
Can you check if there are any messages similar to 'tts-message' in the 'chat-message' interface?

**Comment by greycodee** [comment]
I'm trying to fix it.

**Comment by greycodee** [comment]
I'm not reproducing it locally
I can play the voice automatically on my locally.

**Comment by Freya0214** [comment]
hi,"I encountered the same issue and found that the 'audio' field in the client chat-message response is empty. My Dify version is 0.70, and my Xinference version is 0.14.3."
[
![WX20240827-175549@2x](https://github.com/user-attachments/assets/139a0a61-3a8e-4871-ba33-d90880883625)
](url)

**Comment by Freya0214** [comment]
I noticed that in my chat-message, between message_end and tts_message_end, there seems to be a missing tts_message response data."

data: {"event": "message_end", "conversation_id": "4b36121c-d9bb-4bf2-86d3-b86c624d2b62", "message_id": "fc4f6ed4-e50d-418d-a779-fe15cb44155c", "created_at": 1724728736, "task_id": "1652232e-38d5-4de3-ada9-1fed6c855093", "id": "fc4f6ed4-e50d-418d-a779-fe15cb44155c", "metadata": {"usage": {"prompt_tokens": 7521, "prompt_unit_price": "0.0", "prompt_price_unit": "0.0", "prompt_price": "0.0", "completion_tokens": 1183, "completion_unit_price": "0.0", "completion_price_unit": "0.0", "completion_price": "0.0", "total_tokens": 8704, "total_price": "0.0", "currency": "USD", "latency": 38.93568039796082}}}

data: {"event": "tts_message_end", "conversation_id": "4b36121c-d9bb-4bf2-86d3-b86c624d2b62", "message_id": "fc4f6ed4-e50d-418d-a779-fe15cb44155c", "created_at": 1724728736, "task_id": "1652232e-38d5-4de3-ada9-1fed6c855093", "audio": ""}

**Comment by sxhai18** [comment]
do you fix the problem？I have the same problem, too

**Comment by sxhai18** [comment]
hello,friend，do you solve the problem？I have the same problem, too. Now I don't know how to solve it  @tsiens
