### ISSUE TITLE
Dify studio become very slow after uploading and embedding a large number of files

### ISSUE THREAD

**Issue by ddnoodle** [langgenius/dify#6998]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

This issue has been met for two times.
Create a knowledge base and upload a large number of files in one time, say 500 files. Choose high quality to using embedding model.
After the upload and embedding is done 100%, the Dify become very slow, respond very slow when openning an app to edit or running a app.
Issue can only be recovered by restart Dify dockers.

### ✔️ Expected Behavior

Dify respond normally after uploading/embedding large number of files are done.

### ❌ Actual Behavior

Dify respond very very sloe after uploading/embedding large number of files are done.

**Comment by ddnoodle** [comment]
This reply does not answer my question.

**Comment by crazywoola** [comment]
Can your provide the container logs of api? Actually I am not sure about if this is related to frontend or backend.

**Comment by ddnoodle** [comment]
OK, I will provide when the issue was reproduced.

**Comment by ddnoodle** [comment]
> Can your provide the container logs of api? Actually I am not sure about if this is related to frontend or backend.

I reproduced and found one abnormal that is overload of gunicorn. Once the system is stuck, the gunicorn cpu usage will become 100% for ever. The only way is to reboot the containers to recover. Please see below screen:
<img width="448" alt="gunicorn stuck" src="https://github.com/user-attachments/assets/4adee85f-6dcd-411d-8546-a38302370786">

For containers logs, I dont see any obvious error logs.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/7677#issue-2487894362
