### ISSUE TITLE
终端运行 docker -compose up -d报错

### ISSUE THREAD

**Issue by neverbiasu** [langgenius/dify#70]
<img width="565" alt="image" src="https://github.com/langgenius/dify/assets/90372299/77eb3955-5194-4f7c-82c9-f724199f5d53">
rt，对docker的了解只是入门。按照步骤做了，但是报了这个错。查了一下，是说运行的层数过多导致，那我把yml的文件里的几行命令用“ && “合并可行吗？大佬捞一捞🥹

**Comment by crazywoola** [comment]
Can you try to clone the latest code and rebuild it.again.
Also are you using something other than docker desktop.
Can you provide more infomation.
