### ISSUE TITLE
0.3.12 文本生成型 后台报错list index out of range

### ISSUE THREAD

**Issue by eggb4by** [langgenius/dify#700]
之前是0.3.10，今天升级了0.3.12，然后文本生成型的app提交后报错，信息如下
docker-api-1        | ERROR:root:list index out of range
docker-api-1        | ERROR:root:Unknown Error in completion
docker-api-1        | Traceback (most recent call last):
docker-api-1        |   File "/app/api/services/completion_service.py", line 205, in generate_worker
docker-api-1        |     Completion.generate(
docker-api-1        |   File "/app/api/core/completion.py", line 104, in generate
docker-api-1        |     cls.run_final_llm(
docker-api-1        |   File "/app/api/core/completion.py", line 166, in run_final_llm
docker-api-1        |     response = final_llm.generate([prompt], stop_words)
docker-api-1        |   File "/app/api/core/llm/wrappers/openai_wrapper.py", line 14, in wrapper
docker-api-1        |     return func(*args, **kwargs)
docker-api-1        |   File "/app/api/core/llm/streamable_azure_open_ai.py", line 65, in generate
docker-api-1        |     return super().generate(prompts, stop, callbacks, **kwargs)
docker-api-1        |   File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 281, in generate
docker-api-1        |     output = self._generate_helper(
docker-api-1        |   File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 225, in _generate_helper
docker-api-1        |     raise e
docker-api-1        |   File "/usr/local/lib/python3.10/site-packages/langchain/llms/base.py", line 212, in _generate_helper
docker-api-1        |     self._generate(
docker-api-1        |   File "/usr/local/lib/python3.10/site-packages/langchain/llms/openai.py", line 312, in _generate
docker-api-1        |     stream_resp["choices"][0]["text"],
docker-api-1        | IndexError: list index out of range
docker-api-1        | ERROR:root:internal server error.
docker-api-1        | Traceback (most recent call last):
docker-api-1        |   File "/app/api/controllers/console/app/completion.py", line 158, in generate
docker-api-1        |     for chunk in response:
docker-api-1        |   File "/app/api/services/completion_service.py", line 415, in generate
docker-api-1        |     cls.handle_error(result)
docker-api-1        |   File "/app/api/services/completion_service.py", line 519, in handle_error
docker-api-1        |     raise Exception(description)
docker-api-1        | Exception: list index out of range
docker-api-1        | ERROR:app:Exception on /console/api/apps/d8383796-5797-499c-9c06-9497f48490e6/completion-messages [POST]
docker-api-1        | Traceback (most recent call last):
docker-api-1        |   File "/app/api/controllers/console/app/completion.py", line 158, in generate
docker-api-1        |     for chunk in response:
docker-api-1        |   File "/app/api/services/completion_service.py", line 415, in generate
docker-api-1        |     cls.handle_error(result)
docker-api-1        |   File "/app/api/services/completion_service.py", line 519, in handle_error
docker-api-1        |     raise Exception(description)
docker-api-1        | Exception: list index out of range
我用的azure api
<img width="528" alt="image" src="https://github.com/langgenius/dify/assets/6998751/91c6fbee-aca1-4b1e-86d1-be064226eb88">

**Comment by takatost** [comment]
You can do a `pip install -r requirements.txt` to update the dependencies.

**Comment by eggb4by** [comment]
> You can do a `pip install -r requirements.txt` to update the dependencies.

I use docker compose to start the app, and it seems that there is no way to manually run pip install -r requirements .txt because it is all packaged in the image.

**Comment by eggb4by** [comment]
The upgrade process is to change the three "v0.3.10" to "v0.3.12" in the docker-compose.yaml in the docker directory, re-image pull, docker compose up

**Comment by takatost** [comment]
This issue is caused by the presence of empty choices in the response from the Azure OpenAI completion interface. It has been fixed in the recent LangChain update, and we have promptly followed up on it. The latest version of LangChain is 0.3.12.
Reference: https://github.com/langchain-ai/langchain/pull/8241
I have tested the Azure OpenAI invocation on both amd64 and arm64 machines, and there were no issues. Please confirm if you are using the dify-api image with version 0.3.12.

**Comment by eggb4by** [comment]
Yes, I looked at the container environment on the server
![image](https:github.com/langgenius/dify/assets/6998751/3d8d8f32-095a-4ffb-b168-afaa2210517e)
Then I went into container 01708653e551 and looked into the requirement .txt
```langchain==0.0.239```

**Comment by eggb4by** [comment]
I wonder if it's because I'm running by docker compose and the langchain version in the image hasn't been updated

**Comment by takatost** [comment]
Can you enter the dify-api container and execute pip show langchain to check the specific installed version? It should return the following result if everything is normal:
```
# pip show langchain
Name: langchain
Version: 0.0.239
Summary: Building applications with LLMs through composability
Home-page: https://www.github.com/hwchase17/langchain
Author: 
Author-email: 
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires: aiohttp, async-timeout, dataclasses-json, langsmith, numexpr, numpy, openapi-schema-pydantic, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by:
```

Or is it possible that the program has entered another container or was launched from the source code?

**Comment by eggb4by** [comment]
docker ps like this:
```
CONTAINER ID   IMAGE                                                           COMMAND                  CREATED        STATUS       PORTS                                                                                            NAMES
2be3f1e6c906   nginx:latest                                                    "/docker-entrypoint.…"   5 hours ago    Up 5 hours   0.0.0.0:80->80/tcp, :::80->80/tcp                                                                docker-nginx-1
01708653e551   langgenius/dify-api:0.3.12                                      "/bin/bash /entrypoi…"   5 hours ago    Up 5 hours   80/tcp, 5001/tcp                                                                                 docker-api-1
e424c0c011f6   langgenius/dify-api:0.3.12                                      "/bin/bash /entrypoi…"   5 hours ago    Up 5 hours   80/tcp, 5001/tcp                                                                                 docker-worker-1
0a59c112fa5d   langgenius/dify-web:0.3.12                                      "/bin/bash /entrypoi…"   5 hours ago    Up 5 hours   80/tcp, 3000/tcp                                                                                 docker-web-1
b889dcd963b5   postgres:15-alpine                                              "docker-entrypoint.s…"   5 hours ago    Up 5 hours   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                        docker-db-1
826912888a51   redis:6-alpine                                                  "docker-entrypoint.s…"   5 hours ago    Up 5 hours   6379/tcp                                                                                         docker-redis-1
5781c4ccc01a   semitechnologies/weaviate:1.18.4                                "/bin/weaviate --hos…"   5 hours ago    Up 5 hours                                                                                                    docker-weaviate-1
```
and in ```docker exec -it 01708653e551 /bin/bash```
```
root@01708653e551:/app/api# pip show langchain
Name: langchain
Version: 0.0.239
Summary: Building applications with LLMs through composability
Home-page: https://www.github.com/hwchase17/langchain
Author: 
Author-email: 
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires: aiohttp, async-timeout, dataclasses-json, langsmith, numexpr, numpy, openapi-schema-pydantic, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: 
```

**Comment by takatost** [comment]
I just tried on several other amd64 / arm64 machines and didn't find any issues. Can you check if the request really reached this container or provide more details?

**Comment by takatost** [comment]
I think I've found an issue. You're using the deprecated text-davinci-003 model from Azure, and I checked langchain and there's no fix for empty choices returned for completion type.
Currently, I suggest switching to the gpt 3.5 or gpt 4 models. Both text-davinci-003 from OpenAI and Azure OpenAI have been deprecated, although the OpenAI one is still functional.

**Comment by eggb4by** [comment]
> I think I've found an issue. You're using the deprecated text-davinci-003 model from Azure, and I checked langchain and there's no fix for empty choices returned for completion type. Currently, I suggest switching to the gpt 3.5 or gpt 4 models. Both text-davinci-003 from OpenAI and Azure OpenAI have been deprecated, although the OpenAI one is still functional.

Thanks so much. I swithed to gpt 3.5 and it works with no error😊

**Comment by takatost** [comment]
reference #708
I tried fixing this issue. You can try switching to this commit id for the mirrored version.
