### ISSUE TITLE
Stronger Parameter Exactor needed

### ISSUE THREAD

**Issue by cherry0411** [langgenius/dify#7000]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello everyone, I would like to dynamically parse parameters from text, such as product model, brand, and size. Different products have different parameters, which may be passed in from the starting node or obtained through the HTTP node. Current parameter extractor can only support fixed parameters and cannot meet my needs. For example, I can pass in the following parameters at the start node: {"product_fields": [{"key": "field_1", "name": "brand", "description": "brand of the product", "type": "enum", "range": ["Nike", "Adidas", "Puma"]}, {"key": "field_2", "name": "size", "description": "size of the shoes of clothes", "type": "number"}}, and then use these parameters directly in the parameter extractor

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I guess you want to parse some json string in the start node? If so, you can use text type which supports long context. Then you can use a code node to parse these parameters to meet your requirements. Does this solves your problem?

**Comment by cherry0411** [comment]
No, it doesn't. Sorry for the confusion. I need function calling to extract parameters and values from text through LLM, which exactly Parameter Extractor node does. but currently parameters are fixed values we can only setup in the workflow editor, that's my problem, I need to dynamically setup parameters to be extract, on the runtime.

**Comment by crazywoola** [comment]
So this problem should be you need an agent during the workflow and it can call third-party services by it's own decision?

**Comment by cherry0411** [comment]
Emmm... I don't think agent in workflow can solve this problem' cos tools in agent still have fixed parameters.

Simplest way, I think, is supporting variables in Parameter Extractor's parameter.

![Weixin Screenshot_20240806161945](https://github.com/user-attachments/assets/aabc2852-eacc-4aa8-88f9-53659ef8d36f)
