### ISSUE TITLE
can't auto generate conversation name,always is New conversation

### ISSUE THREAD

**Issue by Lyeluo** [langgenius/dify#7001]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when i use workflow for chat api to create a conversation ,whether i set **auto_generate_name** true or false . when i get conversations histroy , got conversation name is "New conversation". Is this a bug?
![image](https://github.com/user-attachments/assets/8312648b-057f-438f-8b80-ce9f0c4ddde3)

### ✔️ Expected Behavior

get model generated conversation name

**Comment by crazywoola** [comment]
I think this is a deprecated parameter here, we found it will make the whole conversation slower and  consume more tokens.
Please use this api `/conversations/:conversation_id/name`  instead. We will phase out this parameter in the future. :)

**Comment by Lyeluo** [comment]
i got it,thx~

**Comment by anjingyong** [comment]
i use 1.0.0 version has this bugs，use this api/conversations/:conversation_id/name with parameter  "auto_generate": true,

**Comment by yjing86** [comment]
This bug still exists to this day in 1.0.1 version

**Comment by hlwz5735** [comment]
This is because you can't use reasoning LLM model(like DeepSeek-R1). The auto rename feature will invoke system default LLM and expect that it will return a JSON string. Because Reasoning LLM will append `<think>...</think>` blocks, Dify can't match the output with current regxp.

The relevant code is located at: `api/core/llm_generator/llm_generator.py`，line 56:
```python
        answer = cast(str, response.message.content)
        cleaned_answer = re.sub(r"^.*(\{.*\}).*$", r"\1", answer, flags=re.DOTALL)
        if cleaned_answer is None:
            return ""
        result_dict = json.loads(cleaned_answer)
        answer = result_dict["Your Output"]
        name = answer.strip()
```

I think we can solve this problem by cutting the string to get a clean substring. Such as:

```python
if ('</think>' in answer):
  answer = answer.split('</think>')[-1] # just for demostration, not robbust

cleaned_answer = re.sub(r"^.*(\{.*\}).*$", r"\1", answer, flags=re.DOTALL)
```
