### ISSUE TITLE
Setting the voice of text to speech does not work

### ISSUE THREAD

**Issue by cycwll** [langgenius/dify#7003]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I used the cosyvoice model via xinference, dify use it as text to speech model.  No matter what I configure the voice for Text to Speech, the value of the voice passed from dify to xinference is always empty

{'intput': '记得联系技术支持寻求进一步的帮助。', 'voice': '', 'response_format': 'mp3', 'speed': 1.0, 'stream': False}

**Comment by ic-xu** [comment]
<img width="2159" alt="image" src="https://github.com/user-attachments/assets/7f43996c-2a65-45ad-9101-47e692ddb925">


Xinference not tts model  ?

**Comment by cycwll** [comment]
I am dify running by docker compose。The network from dify to xinference is not a problem. The interface can be called and text can be converted to speech, but only the voice parameter has not been passed.

1. I entered the docker-api-1 container, and modify the file /app/api/core/model_runtime/model_providers/xinference/xinference_helper.py  according to your guidance.
2. And then, restarted the docker-api-1 container by: docker  restart docker-api-1
3. After restarting, I confirmed that the files inside the container were still modified files

I see the log of xinference, the voice parameter still is empty.
2024-08-07 01:02:20,162 xinference.core.model 479 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7fdad4bc0a40>,), kwargs: {'input': '请联系技术支持团队获取帮助。', 'voice': '', 'response_format': 'mp3', 'speed': 1.0, 'stream': False}

**Comment by cycwll** [comment]
@dosu thanks for you help!

I upgraded to v0.7.0, but the situation has become worse. The "voice" parameter has been became to "default", and causing the xinference error: 

xinference.core.model 479 DEBUG Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7fdad4bc0a40>,), kwargs: {'input': '请联系技术支持团队获取帮助。', 'voice': 'default', 'response_format': 'mp3', 'speed': 1.0, 'stream': False}

"AssertionError: [address=0.0.0.0:43313, pid=467] Invalid voice default, CosyVoice available speakers: ['中文女', '中文男', '日语男', '粤语女', '英文女', '英文男', '韩语女']"

**Comment by cycwll** [comment]
@dosu.
After adding the "function" in my application, I did not set the voice, and the default voice I used would be "voice": "default". And then I set the voice to "Chinese" - "Chinese male", but the problem goes back to the beginning and "voice" is empty
{'intput': '记得联系技术支持寻求进一步的帮助。', 'voice': '', 'response_format': 'mp3', 'speed': 1.0, 'stream': False}

**Comment by ic-xu** [comment]
Can you give me a temporary Xinference key to verify?

**Comment by cycwll** [comment]
@ic-xu  My xinference is deployed locally

**Comment by hunterhome** [comment]
文字转语音 自动播放 开启  在xinference控制台出现：

 Invalid voice default, CosyVoice available speakers: ['中文女', '中文男', '日语男', '粤语女', '英文女', '英文男', '韩语女']"

**Comment by crazywoola** [comment]
Should be fixed in #7958
