### ISSUE TITLE
新建用户的邀请链接不能复制

### ISSUE THREAD

**Issue by ZQianyan** [langgenius/dify#701]
在用docker进行本地化部署后不能建立新的账户，能够正常弹出链接邀请弹窗但是不能复制链接。网页检查显示不支持剪切板，但是更换游览器依旧不能复制，同时还显示没有可聚焦的元素。即显示“Clipboard not supported”和“There are no focusable elements inside the <FocusTrap />”。

**Comment by ZQianyan** [comment]
邀请链接不能复制是不用“：3000”尾缀进入网页后产生的bug，在从“：3000”尾缀进入的网页里，“：3000/install”和“：3000/signin”都能进，但是“：3000/install”不能设立管理员账户，输入设置后点击建立账户按钮无反应，同时“：3000/apps”页面一直处于加载中。控制台报错信息是“Failed to load resource: the server responded with a status of 404 (Not Found)“和” GET http://172.22.1.147:3000/console/api/account/profile 404 (Not Found)”

**Comment by ZQianyan** [comment]
邀请链接不能复制是不用“：3000”尾缀进入网页后产生的bug，在从“：3000”尾缀进入的网页里，“：3000/install”和“：3000/signin”都能进，但是“：3000/install”不能设立管理员账户，输入设置后点击建立账户按钮无反应，同时“：3000/apps”页面一直处于加载中。控制台报错信息是“Failed to load resource: the server responded with a status of 404 (Not Found)“和” GET http://172.22.1.147:3000/console/api/account/profile 404 (Not Found)”

**Comment by ZQianyan** [comment]
邀请链接不能复制这个bug是不用“：3000”尾缀进入网页后产生的bug。在从“：3000”尾缀进入的网页里，“：3000/install”和“：3000/signin”都能进，但是“：3000/install”不能设立管理员账户，输入设置后点击建立账户按钮无反应，同时“：3000/apps”页面一直处于加载中。控制台报错信息是“Failed to load resource: the server responded with a status of 404 (Not Found)“和“install:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON”

**Comment by JunIce** [comment]
我没看懂。不用3000你进的是docker内启动的web，最新的版本是0.3.12，这个问题应该改过。 另外你访问的3000端口是你本地启动的dev服务，但是dev访问代理的是5001端口，5001端口并没有暴露，推断你访问的接口没通。

**Comment by ZQianyan** [comment]
非常感谢！但我搞了一上午好像还是不行，不知道问题到底出在哪里了。


使用的就是0.3.12版本，5001端口也是接通的，但是具体到docker-api-1里就出现404错误。
***@***.*** docker]# docker ps
CONTAINER ID&nbsp; &nbsp;IMAGE&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; COMMAND&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; CREATED&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; STATUS&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; PORTS&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;NAMES
3d24607ab50b&nbsp; &nbsp;nginx:latest&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"/docker-entrypoint.…"&nbsp; &nbsp;12 minutes ago&nbsp; &nbsp;Up 12 minutes&nbsp; &nbsp;0.0.0.0:80-&gt;80/tcp, :::80-&gt;80/tcp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;docker-nginx-1
18615ea79aaf&nbsp; &nbsp;langgenius/dify-web:0.3.12&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"/bin/bash /entrypoi…"&nbsp; &nbsp;12 minutes ago&nbsp; &nbsp;Up 12 minutes&nbsp; &nbsp;3000/tcp, 0.0.0.0:3000-&gt;80/tcp, :::3000-&gt;80/tcp&nbsp; &nbsp; &nbsp;docker-web-1
85f7548b0cd7&nbsp; &nbsp;langgenius/dify-api:0.3.12&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"/bin/bash /entrypoi…"&nbsp; &nbsp;54 minutes ago&nbsp; &nbsp;Up 54 minutes&nbsp; &nbsp;80/tcp, 0.0.0.0:5001-&gt;5001/tcp, :::5001-&gt;5001/tcp&nbsp; &nbsp;docker-api-1
18c02af42e9f&nbsp; &nbsp;langgenius/dify-api:0.3.12&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"/bin/bash /entrypoi…"&nbsp; &nbsp;54 minutes ago&nbsp; &nbsp;Up 54 minutes&nbsp; &nbsp;80/tcp, 5001/tcp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; docker-worker-1
630f506ce8bc&nbsp; &nbsp;postgres:15-alpine&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"docker-entrypoint.s…"&nbsp; &nbsp;54 minutes ago&nbsp; &nbsp;Up 54 minutes&nbsp; &nbsp;0.0.0.0:5432-&gt;5432/tcp, :::5432-&gt;5432/tcp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;docker-db-1
b3188e0ea1f0&nbsp; &nbsp;semitechnologies/weaviate:1.18.4&nbsp; &nbsp;"/bin/weaviate --hos…"&nbsp; &nbsp;54 minutes ago&nbsp; &nbsp;Up 54 minutes&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;docker-weaviate-1
6b5646e03670&nbsp; &nbsp;redis:6-alpine&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"docker-entrypoint.s…"&nbsp; &nbsp;54 minutes ago&nbsp; &nbsp;Up 54 minutes&nbsp; &nbsp;6379/tcp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; docker-redis-1



***@***.*** docker]# curl -v http://172.22.1.147:5001 * About to connect() to 172.22.1.147 port 5001 (#0) *   Trying 172.22.1.147... * Connected to 172.22.1.147 (172.22.1.147) port 5001 (#0) &gt; GET / HTTP/1.1 &gt; User-Agent: curl/7.29.0 &gt; Host: 172.22.1.147:5001 &gt; Accept: */* &gt;  < HTTP/1.1 404 NOT FOUND < Server: gunicorn < Date: Thu, 03 Aug 2023 02:01:52 GMT < Connection: keep-alive < Content-Type: text/html; charset=utf-8 < Content-Length: 207 < X-Version: 0.3.12 < X-Env: PRODUCTION < Set-Cookie: session=d211506b-828e-4059-abdf-8a096a89f933.w-7_TC_kAQkDqvg4WqD1YDypijA; Expires=Thu, 10 Aug 2023 02:01:52 GMT; HttpOnly; Path=/; SameSite=Lax <  <!doctype html&gt; <html lang=en&gt; <title&gt;404 Not Found</title&gt; <h1&gt;Not Found</h1&gt; <p&gt;The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p&gt; * Connection #0 to host 172.22.1.147 left intact


然后就是我说的剪切板问题，就是像这样：

能进入页面，各种功能也都能用，就是到发送邀请后的这个邀请链接还是不能复制下来。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langgenius/dify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月2日(星期三) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langgenius/dify] 新建用户的邀请链接不能复制 (Issue #701)





 
我没看懂。不用3000你进的是docker内启动的web，最新的版本是0.3.12，这个问题应该改过。 另外你访问的3000端口是你本地启动的dev服务，但是dev访问代理的是5001端口，5001端口并没有暴露，推断你访问的接口没通。

**Comment by MatriQ** [comment]
> 非常感谢！

该问题已经修复，建议关闭此issue
