### ISSUE TITLE
duck duckgo Image search output issues

### ISSUE THREAD

**Issue by leoleelxh** [langgenius/dify#7014]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Regarding the issue with the DDG image search tool, the output parameter 'files' can be seen at the end node, but in fact, only this parameter has content.
![image](https://github.com/user-attachments/assets/1af2dff2-8d33-4d95-b755-0430675a3487)
The other nodes cannot see the input of this parameter.
![image](https://github.com/user-attachments/assets/34935e53-40e4-4ccf-be71-8608fdf62352)
Both JSON and text do not have content output.
![image](https://github.com/user-attachments/assets/7d87f41b-d392-4c48-a588-d8b1444beeff)

关于ddg图片搜索工具的问题，在结束节点可以看到有files的输出参数，事实上只有这个参数才有内容。
![image](https://github.com/user-attachments/assets/1af2dff2-8d33-4d95-b755-0430675a3487)

另外的节点，是没办法看到这个参数的传入的。
![image](https://github.com/user-attachments/assets/34935e53-40e4-4ccf-be71-8608fdf62352)

而json和text均没有内容输出。
![image](https://github.com/user-attachments/assets/7d87f41b-d392-4c48-a588-d8b1444beeff)

### ✔️ Expected Behavior

Optimize image search tool

### ❌ Actual Behavior

Not outputting as expected or parameters are not callable.

**Comment by leoleelxh** [comment]
> @leoleelxh你好！我来这里是为了帮你解决错误、回答你的问题，并帮助你开始成为一名贡献者。让我们一起解决这些错误吧！🤖
> 
> 为了解决 Dify 版本 0.6.16 中的 DuckDuckGo (DDG) 图像搜索工具的问题，其中“文件”输出参数对其他节点不可见，并且 JSON 和文本输出均不包含内容，您需要确保实例`ToolInvokeMessage`正确填充并且结果格式正确并返回。
> 
> 以下是相关的代码片段`ddgo_img.py`：
> 
> ```python
> from typing import Any
> 
> from duckduckgo_search import DDGS
> 
> from core.tools.entities.tool_entities import ToolInvokeMessage
> from core.tools.tool.builtin_tool import BuiltinTool
> 
> 
> class DuckDuckGoImageSearchTool(BuiltinTool):
>     """
>     Tool for performing an image search using DuckDuckGo search engine.
>     """
> 
>     def _invoke(self, user_id: str, tool_parameters: dict[str, Any]) -> list[ToolInvokeMessage]:
>         query_dict = {
>             "keywords": tool_parameters.get('query'),
>             "timelimit": tool_parameters.get('timelimit'),
>             "size": tool_parameters.get('size'),
>             "max_results": tool_parameters.get('max_results'),
>         }
>         response = DDGS().images(**query_dict)
>         result = []
>         for res in response:
>             msg = ToolInvokeMessage(type=ToolInvokeMessage.MessageType.IMAGE_LINK,
>                                     message=res.get('image'),
>                                     save_as='',
>                                     meta=res)
>             result.append(msg)
>         return result
> ```
> 
> 要解决该问题，请确保以下事项：
> 
> 1. **正确填充`ToolInvokeMessage`**：确保`ToolInvokeMessage`实例正确填充了必要的数据。字段`message`应包含图像链接，字段`meta`应包含任何其他元数据。
> 2. **返回格式正确的结果**：确保结果格式正确并以`ToolInvokeMessage`实例列表的形式返回。
> 
> 此外，请验证`ToolDefault`Dify 工作流中的节点是否正确配置以处理`files`输出参数。根据`web/app/components/workflow/constants.ts`文件，该`Tool`节点应支持`files`输出结构：
> 
> ```ts
> export const TOOL_OUTPUT_STRUCT: Var[] = [
>   {
>     variable: 'text',
>     type: VarType.string,
>   },
>   {
>     variable: 'files',
>     type: VarType.arrayFile,
>   },
> ]
> ```
> 
> 确保`Tool`正确设置节点以将`files`输出传递给工作流中的后续节点。如果问题仍然存在，您可能需要检查`ToolInvokeMessage`其他节点使用这些实例的集成点，以确保它们正确处理`files`输出参数[[1] ](https://github.com/langgenius/dify/blob/main/api/core/tools/provider/builtin/duckduckgo/tools/ddgo_img.py)[[2]](https://github.com/langgenius/dify/blob/main/web/app/components/workflow/constants.ts)。
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_

Thank you very much for your answer! I am a beginner and do not know where to modify this file?

**Comment by leoleelxh** [comment]
> To modify the necessary files, follow these steps:
> 
> 1. **Locate the `ddgo_img.py` File**:
>    
>    * Navigate to the `api/core/tools/provider/builtin/duckduckgo/tools/` directory in your Dify repository.
>    * Open the `ddgo_img.py` file.
> 2. **Ensure `ToolInvokeMessage` Instances are Correctly Populated**:
>    
>    * Verify that the `_invoke` method in the `DuckDuckGoImageSearchTool` class is correctly populating the `ToolInvokeMessage` instances. The `message` field should contain the image link, and the `meta` field should contain any additional metadata.
>    
>    ```python
>    from typing import Any
>    from duckduckgo_search import DDGS
>    from core.tools.entities.tool_entities import ToolInvokeMessage
>    from core.tools.tool.builtin_tool import BuiltinTool
>    
>    class DuckDuckGoImageSearchTool(BuiltinTool):
>        """
>        Tool for performing an image search using DuckDuckGo search engine.
>        """
>    
>        def _invoke(self, user_id: str, tool_parameters: dict[str, Any]) -> list[ToolInvokeMessage]:
>            query_dict = {
>                "keywords": tool_parameters.get('query'),
>                "timelimit": tool_parameters.get('timelimit'),
>                "size": tool_parameters.get('size'),
>                "max_results": tool_parameters.get('max_results'),
>            }
>            response = DDGS().images(**query_dict)
>            result = []
>            for res in response:
>                msg = ToolInvokeMessage(type=ToolInvokeMessage.MessageType.IMAGE_LINK,
>                                        message=res.get('image'),
>                                        save_as='',
>                                        meta=res)
>                result.append(msg)
>            return result
>    ```
> 3. **Verify `ToolDefault` Node Configuration**:
>    
>    * Navigate to the `web/app/components/workflow/` directory in your Dify repository.
>    * Open the `constants.ts` file.
>    * Ensure that the `TOOL_OUTPUT_STRUCT` is correctly defined to include the `files` output parameter.
>    
>    ```ts
>    export const TOOL_OUTPUT_STRUCT: Var[] = [
>      {
>        variable: 'text',
>        type: VarType.string,
>      },
>      {
>        variable: 'files',
>        type: VarType.arrayFile,
>      },
>    ]
>    ```
> 
> By following these steps, you can ensure that the `ToolInvokeMessage` instances are correctly populated and that the `Tool` node is configured to handle the `files` output parameter [[1]](https://github.com/langgenius/dify/blob/main/api/core/tools/provider/builtin/duckduckgo/tools/ddgo_img.py)[[2]](https://github.com/langgenius/dify/blob/main/web/app/components/workflow/constants.ts).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention 

@dosu.Thank you again! Now I know where to make the modifications. Because I am deploying with Docker, do I need to rebuild Docker after modifying files? This morning, I was worried that I couldn't recover my data because I upgraded to the dify version.

**Comment by leoleelxh** [comment]
> Yes, you need to rebuild the Docker image after modifying the files. Here are the steps to do so:
> 
> 1. **Rebuild the Docker Images**:
>    
>    * Navigate to the directory containing your `docker-compose.yml` file.
>    * Run the following command to rebuild the Docker images:
>    
>    ```shell
>    docker compose build
>    ```
> 2. **Restart the Services**:
>    
>    * Stop the running containers:
>    
>    ```shell
>    docker compose down
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    
>    * Start the containers again:
>    
>    ```shell
>    docker compose up -d
>    ```
> 
> Regarding data recovery, it is recommended to back up your data before performing the upgrade to avoid potential data loss. The recommended backup procedures for a self-hosted Dify deployment include:
> 
> 1. **Backup the Database**.
> 2. **Backup the Configured Storage**.
> 3. **Backup the Vector Database Data**.
> 
> If you are using Docker Compose mode, you can directly back up all data content in the `dify/docker/volumes` directory [[1]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/docker-compose.md)[[2]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/install-faq.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I just backed up my data in the morning before upgrading to the new version and then restored, but as a result, the old data is gone, not sure what the problem is.
![PixPin_2024-08-06_20-27-11](https://github.com/user-attachments/assets/aa736a7f-aac8-441f-b9ac-3249692477a0)

**Comment by leoleelxh** [comment]
The problem remains, the person who originally replied to me was a robot~

**Comment by crazywoola** [comment]
This is a known issue, or a feature regarding the limitation of the file process ability of a LLM node. We plan to support this feature in next month. See https://github.com/langgenius/dify/issues/5346 for update.
