### ISSUE TITLE
Process rule is required error when call create_by_file to create document in a dataset！

### ISSUE THREAD

**Issue by bnuzhouwei** [langgenius/dify#7018]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![微信截图_20240806213428](https://github.com/user-attachments/assets/b1cbd5ed-ba01-4f70-872e-8bd36a0274d4)

### ❌ Actual Behavior

{
    "code": "invalid_param",
    "message": "Process rule is required",
    "status": 400
}

**Comment by crazywoola** [comment]
See bot's reply.

**Comment by bnuzhouwei** [comment]
Thanks, problem sovled, but if create new file the original_document_id can't be set, otherwise will got an error.

Can we set the document_id in the api so that the the docuemnt can be create or update adaptively.
