### ISSUE TITLE
workflow only support one node?

### ISSUE THREAD

**Issue by suwubee** [langgenius/dify#7024]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Each node in workflow only supports one connection, unlike coze where one node can support multiple lines in parallel.
<img width="458" alt="1722963042017" src="https://github.com/user-attachments/assets/b33243df-dc23-4723-94cd-0997865d7b0b">

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We do not support run workflow in parallel at this moment, only 'variable aggregator' supports multiple lines from others branch.
