### ISSUE TITLE
CORS issue on a fresh install

### ISSUE THREAD

**Issue by ruzzzz6312** [langgenius/dify#7028]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Installation method
Self-hosted using Docker

Steps to Reproduce
Installation as per https://docs.dify.ai/getting-started/install-self-hosted/docker-compose
All good.
Then proceeding to http://localhost:8080/install (using SSH tunneling) or to http://domain.....com/install

Seeing this blank screen with CORS errors.

Tried accessing here:
http://localhost:8080/signin, I see the page but I have to initialize first, so when I click, I see same as in step #2.

Console logs:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.console.dify.xxx.com/console/api/system-features. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.console.dify.xxx.com/console/api/system-features. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. 

Please help, thanks!

P.S. I checked both github and discord search

My ENV.
[ec2-user@xxx docker]$ cat .env | grep "URL"
The backend URL of the console API,
CONSOLE_API_URL=https://api.console.dify.xxx.com/
The front-end URL of the console web,
CONSOLE_WEB_URL=https://console.dify.xxx.com/
SERVICE_API_URL=https://api.dify.xxx.com/
used to declare the back-end URL for the front-end API.
APP_API_URL=https://api.app.dify.xxx.com/
APP_WEB_URL=https://app.dify.xxx.com/
FILES_URL=https://app.dify.xxx.com/
CHECK_UPDATE_URL=https://updates.dify.ai/ 

<img width="1496" alt="Screenshot 2024-08-06 at 2 00 37 PM" src="https://github.com/user-attachments/assets/8b3e4e35-851e-4f0a-810d-bdbc492dc36e">

### ✔️ Expected Behavior

Expected Behavior
I was execting to continue installation process

### ❌ Actual Behavior

Actual Behavior
I see an infinite loader with CORS errors in console

**Comment by ruzzzz6312** [comment]
OMG, fixed. 
Very hard to figure out how to deploy HTTPS.
It took some time. 

Key is in .ENV:
CERTBOT_DOMAIN to include all
NGINX_HTTPS_ENABLED=true
NGINX_ENABLE_CERTBOT_CHALLENGE=true

PLease update instructions for future users

**Comment by taowang1993** [comment]
I also struggled with these url configs. In the end, I configured only one which is the APP_WEB_URL. 

I am not really sure why we need to configure so many urls....

Are you using all of them?

> OMG, fixed. Very hard to figure out how to deploy HTTPS. It took some time.
> 
> Key is in .ENV: CERTBOT_DOMAIN to include all NGINX_HTTPS_ENABLED=true NGINX_ENABLE_CERTBOT_CHALLENGE=true
> 
> PLease update instructions for future users
