### ISSUE TITLE
OpenAI is supported, but claude is not.(api.deepbricks.ai)

### ISSUE THREAD

**Issue by kson34** [langgenius/dify#7039]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![354444240-8a9636aa-4b44-4b3a-91e1-0764d22b659f](https://github.com/user-attachments/assets/4c1eec99-7dad-457a-8ed8-c6df48ab8359)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Hello other providers other than OpenAI do not support using a proxy url to add new models.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6856
