### ISSUE TITLE
“404 page not found”  when trying to access port 80

### ISSUE THREAD

**Issue by 0sengseng0** [langgenius/dify#7053]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I migrated this service to a server without a network.
The image and code are packaged and transferred. From the startup logs, you don't seem to see any error messages.
But when I try to access this server on port 80, I get a 404 error, and the server doesn't log any errors.

## error image
![image](https://github.com/user-attachments/assets/be81ad1b-0ba1-4b44-a2db-fe9849beb18b)

## logs
[root@node172 docker]# docker compose up
[+] Running 11/1
 ✔ Network docker_default             Created                                                                                                                                                                                      0.1s 
 ✔ Network docker_ssrf_proxy_network  Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-db-1              Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-web-1             Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-ssrf_proxy-1      Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-weaviate-1        Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-redis-1           Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-sandbox-1         Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-worker-1          Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-api-1             Created                                                                                                                                                                                      0.0s 
 ✔ Container docker-nginx-1           Created                                                                                                                                                                                      0.0s 
Attaching to api-1, db-1, nginx-1, redis-1, sandbox-1, ssrf_proxy-1, weaviate-1, web-1, worker-1
sandbox-1     | 2024/08/07 09:04:09 setup.go:29: [INFO]initializing nodejs runner environment...
sandbox-1     | 2024/08/07 09:04:09 setup.go:85: [INFO]nodejs runner environment initialized
sandbox-1     | 2024/08/07 09:04:09 setup.go:31: [INFO]initializing python runner environment...
sandbox-1     | 2024/08/07 09:04:09 setup.go:43: [INFO]python runner environment initialized
sandbox-1     | 2024/08/07 09:04:09 config.go:86: [INFO]network has been enabled
sandbox-1     | 2024/08/07 09:04:09 config.go:102: [INFO]using https proxy: http://ssrf_proxy:3128
sandbox-1     | 2024/08/07 09:04:09 config.go:111: [INFO]using http proxy: http://ssrf_proxy:3128
sandbox-1     | 2024/08/07 09:04:09 server.go:19: [INFO]config init success
sandbox-1     | 2024/08/07 09:04:09 server.go:25: [INFO]runner dependencies init success
sandbox-1     | 2024/08/07 09:04:09 server.go:41: [INFO]installing python dependencies...
sandbox-1     | 2024/08/07 09:04:09 server.go:47: [INFO]python dependencies installed
sandbox-1     | 2024/08/07 09:04:09 cocrrent.go:31: [INFO]setting max requests to 50
sandbox-1     | 2024/08/07 09:04:09 cocrrent.go:13: [INFO]setting max workers to 4
redis-1       | 1:C 07 Aug 2024 09:04:09.967 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1       | 1:C 07 Aug 2024 09:04:09.967 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1       | 1:C 07 Aug 2024 09:04:09.967 # Configuration loaded
redis-1       | 1:M 07 Aug 2024 09:04:09.967 * monotonic clock: POSIX clock_gettime
redis-1       | 1:M 07 Aug 2024 09:04:09.968 * Running mode=standalone, port=6379.
redis-1       | 1:M 07 Aug 2024 09:04:09.968 # Server initialized
redis-1       | 1:M 07 Aug 2024 09:04:09.968 * Loading RDB produced by version 6.2.14
redis-1       | 1:M 07 Aug 2024 09:04:09.968 * RDB age 545 seconds
redis-1       | 1:M 07 Aug 2024 09:04:09.968 * RDB memory usage when created 0.79 Mb
redis-1       | 1:M 07 Aug 2024 09:04:09.969 # Done loading RDB, keys loaded: 37, keys expired: 0.
redis-1       | 1:M 07 Aug 2024 09:04:09.969 * DB loaded from disk: 0.000 seconds
redis-1       | 1:M 07 Aug 2024 09:04:09.969 * Ready to accept connections
db-1          | 
db-1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1          | 
ssrf_proxy-1  | [ENTRYPOINT] re-create snakeoil self-signed certificate removed in the build process
db-1          | 2024-08-07 09:04:10.210 UTC [1] LOG:  starting PostgreSQL 15.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
db-1          | 2024-08-07 09:04:10.210 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1          | 2024-08-07 09:04:10.210 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1          | 2024-08-07 09:04:10.211 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1          | 2024-08-07 09:04:10.214 UTC [29] LOG:  database system was shut down at 2024-08-07 08:55:04 UTC
db-1          | 2024-08-07 09:04:10.218 UTC [1] LOG:  database system is ready to accept connections
weaviate-1    | {"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2024-08-07T09:04:10Z"}
weaviate-1    | {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2024-08-07T09:04:10Z"}
weaviate-1    | {"action":"grpc_startup","level":"info","msg":"grpc server listening at [::]:50051","time":"2024-08-07T09:04:10Z"}
weaviate-1    | {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2024-08-07T09:04:10Z"}
web-1         | 
web-1         |                         -------------
web-1         | 
web-1         | __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
web-1         |  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
web-1         |   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
web-1         |    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
web-1         |     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
web-1         |      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
web-1         |       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
web-1         |        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
web-1         |         _\///______________\///______________\///__\///////////////__
web-1         | 
web-1         | 
web-1         |                           Runtime Edition
web-1         | 
web-1         |         PM2 is a Production Process Manager for Node.js applications
web-1         |                      with a built-in Load Balancer.
web-1         | 
web-1         |                 Start and Daemonize any application:
web-1         |                 $ pm2 start app.js
web-1         | 
web-1         |                 Load Balance 4 instances of api.js:
web-1         |                 $ pm2 start api.js -i 4
web-1         | 
web-1         |                 Monitor in production:
web-1         |                 $ pm2 monitor
web-1         | 
web-1         |                 Make pm2 auto-boot at server restart:
web-1         |                 $ pm2 startup
web-1         | 
web-1         |                 To go further checkout:
web-1         |                 http://pm2.io/
web-1         | 
web-1         | 
web-1         |                         -------------
web-1         | 
web-1         | pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
worker-1      | Running migrations
api-1         | Running migrations
web-1         | 2024-08-07T09:04:10: PM2 log: Launching in no daemon mode
ssrf_proxy-1  | [ENTRYPOINT] replacing environment variables in the template
web-1         | 2024-08-07T09:04:10: PM2 log: [PM2][WARN] Applications dify-web not running, starting...
web-1         | 2024-08-07T09:04:10: PM2 log: App [dify-web:0] starting in -cluster mode-
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/squid.conf (depth 0)
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
ssrf_proxy-1  | 2024/08/07 09:04:10| Created PID file (/run/squid.pid)
ssrf_proxy-1  | 2024/08/07 09:04:10| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/07 09:04:10| Creating missing swap directories
ssrf_proxy-1  | 2024/08/07 09:04:10| No cache_dir stores are configured.
ssrf_proxy-1  | 2024/08/07 09:04:10| Removing PID file (/run/squid.pid)
ssrf_proxy-1  | [ENTRYPOINT] starting squid
web-1         | 2024-08-07T09:04:10: PM2 log: App [dify-web:0] online
web-1         | 2024-08-07T09:04:10: PM2 log: App [dify-web:1] starting in -cluster mode-
web-1         | 2024-08-07T09:04:10: PM2 log: App [dify-web:1] online
web-1         | 2024-08-07T09:04:10: PM2 log: [PM2] App [dify-web] launched (2 instances)
web-1         | 2024-08-07T09:04:10: PM2 log: ┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
web-1         | │ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
web-1         | ├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
web-1         | │ 0  │ dify-web    │ default     │ 0.6.12… │ cluster │ 18       │ 0s     │ 0    │ online    │ 0%       │ 52.2mb   │ root     │ disabled │
web-1         | │ 1  │ dify-web    │ default     │ 0.6.12… │ cluster │ 25       │ 0s     │ 0    │ online    │ 0%       │ 48.1mb   │ root     │ disabled │
web-1         | └────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
web-1         | 2024-08-07T09:04:10: PM2 log: [--no-daemon] Continue to stream logs
web-1         | 2024-08-07T09:04:10: PM2 log: [--no-daemon] Exit on target PM2 exit pid=7
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: using the "epoll" event method
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: nginx/1.25.5
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: built by gcc 12.2.0 (Debian 12.2.0-14) 
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: OS: Linux 5.10.0-136.75.0.155.oe2203sp1.x86_64
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker processes
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 19
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 20
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 21
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 22
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 23
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 24
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 25
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 26
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 27
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 28
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 29
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 30
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 31
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 32
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 33
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 34
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 35
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 36
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 37
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 38
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 39
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 40
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 41
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 42
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 43
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 44
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 45
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 46
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 47
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 48
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 49
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 50
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 51
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 52
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 53
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 54
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 55
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 56
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 57
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 58
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 59
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 60
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 61
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 62
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 63
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 64
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 65
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 66
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 67
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 68
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 69
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 70
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 71
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 72
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 73
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 74
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 75
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 76
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 77
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 78
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 79
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 80
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 81
nginx-1       | 2024/08/07 09:04:10 [notice] 10#10: start worker process 82
web-1         | 09:04:11 0|dify-web  |   ▲ Next.js 14.2.4
web-1         | 09:04:11 0|dify-web  |   - Local:        http://c832ed6033ae:3000
web-1         | 09:04:11 0|dify-web  |   - Network:      http://172.28.0.6:3000
web-1         | 09:04:11 0|dify-web  |  ✓ Starting...
web-1         | 09:04:11 1|dify-web  |   ▲ Next.js 14.2.4
web-1         | 09:04:11 1|dify-web  |   - Local:        http://c832ed6033ae:3000
web-1         | 09:04:11 1|dify-web  |   - Network:      http://172.28.0.6:3000
web-1         | 09:04:11 1|dify-web  |  ✓ Starting...
web-1         | 09:04:11 0|dify-web  |  ✓ Ready in 120ms
web-1         | 09:04:11 1|dify-web  |  ✓ Ready in 118ms
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/squid.conf (depth 0)
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
ssrf_proxy-1  | 2024/08/07 09:04:10| Created PID file (/run/squid.pid)
ssrf_proxy-1  | 2024/08/07 09:04:10| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/07 09:04:10| Creating missing swap directories
ssrf_proxy-1  | 2024/08/07 09:04:10| No cache_dir stores are configured.
ssrf_proxy-1  | 2024/08/07 09:04:10| Removing PID file (/run/squid.pid)
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/squid.conf (depth 0)
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
ssrf_proxy-1  | 2024/08/07 09:04:10| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
ssrf_proxy-1  | 2024/08/07 09:04:10| Created PID file (/run/squid.pid)
ssrf_proxy-1  | 2024/08/07 09:04:10| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/07 09:04:10| Starting Squid Cache version 6.6 for x86_64-pc-linux-gnu...
ssrf_proxy-1  | 2024/08/07 09:04:10| Service Name: squid
ssrf_proxy-1  | 2024/08/07 09:04:10| Process ID 45
ssrf_proxy-1  | 2024/08/07 09:04:10| Process Roles: master worker
ssrf_proxy-1  | 2024/08/07 09:04:10| With 1024 file descriptors available
ssrf_proxy-1  | 2024/08/07 09:04:10| Initializing IP Cache...
ssrf_proxy-1  | 2024/08/07 09:04:10| DNS IPv6 socket created at [::], FD 8
ssrf_proxy-1  | 2024/08/07 09:04:10| DNS IPv4 socket created at 0.0.0.0, FD 9
ssrf_proxy-1  | 2024/08/07 09:04:10| Adding nameserver 127.0.0.11 from /etc/resolv.conf
ssrf_proxy-1  | 2024/08/07 09:04:10| Adding ndots 1 from /etc/resolv.conf
ssrf_proxy-1  | 2024/08/07 09:04:10| Logfile: opening log daemon:/var/log/squid/access.log
ssrf_proxy-1  | 2024/08/07 09:04:10| Logfile Daemon: opening log /var/log/squid/access.log
ssrf_proxy-1  | 2024/08/07 09:04:10| Local cache digest enabled; rebuild/rewrite every 3600/3600 sec
ssrf_proxy-1  | 2024/08/07 09:04:10| Store logging disabled
ssrf_proxy-1  | 2024/08/07 09:04:10| Swap maxSize 0 + 262144 KB, estimated 20164 objects
ssrf_proxy-1  | 2024/08/07 09:04:10| Target number of buckets: 1008
ssrf_proxy-1  | 2024/08/07 09:04:10| Using 8192 Store buckets
ssrf_proxy-1  | 2024/08/07 09:04:10| Max Mem  size: 262144 KB
ssrf_proxy-1  | 2024/08/07 09:04:10| Max Swap size: 0 KB
ssrf_proxy-1  | 2024/08/07 09:04:10| Using Least Load store dir selection
ssrf_proxy-1  | 2024/08/07 09:04:10| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/07 09:04:10| Finished loading MIME types and icons.
ssrf_proxy-1  | 2024/08/07 09:04:10| HTCP Disabled.
ssrf_proxy-1  | 2024/08/07 09:04:10| Pinger socket opened on FD 15
ssrf_proxy-1  | 2024/08/07 09:04:10| Squid plugin modules loaded: 0
ssrf_proxy-1  | 2024/08/07 09:04:10| Adaptation support is off.
ssrf_proxy-1  | 2024/08/07 09:04:10| Accepting HTTP Socket connections at conn3 local=[::]:3128 remote=[::] FD 12 flags=9
ssrf_proxy-1  |     listening port: 3128
ssrf_proxy-1  | 2024/08/07 09:04:10| Accepting reverse-proxy HTTP Socket connections at conn5 local=[::]:8194 remote=[::] FD 13 flags=9
ssrf_proxy-1  |     listening port: 8194
ssrf_proxy-1  | 2024/08/07 09:04:10| Configuring Parent sandbox
ssrf_proxy-1  | 2024/08/07 09:04:10 pinger| Initialising ICMP pinger ...
ssrf_proxy-1  | 2024/08/07 09:04:10 pinger| ICMP socket opened.
ssrf_proxy-1  | 2024/08/07 09:04:10 pinger| ICMPv6 socket opened
ssrf_proxy-1  | 2024/08/07 09:04:11| storeLateRelease: released 0 objects
worker-1      | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
api-1         | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
sandbox-1     | [GIN] 2024/08/07 - 09:04:48 | 401 |        3.03µs |              :: | GET      "/squid-internal-dynamic/netdb"
worker-1      | Preparing database migration...
worker-1      | Start database migration.
worker-1      | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
worker-1      | INFO  [alembic.runtime.migration] Will assume transactional DDL.
api-1         | Preparing database migration...
api-1         | Database migration skipped
worker-1      | Database migration successful!
api-1         | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
worker-1      | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
api-1         | [2024-08-07 09:05:13 +0000] [147] [INFO] Starting gunicorn 22.0.0
api-1         | [2024-08-07 09:05:13 +0000] [147] [INFO] Listening at: http://0.0.0.0:5001 (147)
api-1         | [2024-08-07 09:05:13 +0000] [147] [INFO] Using worker: gevent
api-1         | [2024-08-07 09:05:13 +0000] [286] [INFO] Booting worker with pid: 286
worker-1      | /app/api/.venv/lib/python3.10/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
worker-1      | absolutely not recommended!
worker-1      | 
worker-1      | Please specify a different user using the --uid option.
worker-1      | 
worker-1      | User information: uid=0 euid=0 gid=0 egid=0
worker-1      | 
worker-1      |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker-1      |  
worker-1      |  -------------- celery@8889da14a391 v5.3.6 (emerald-rush)
worker-1      | --- ***** ----- 
worker-1      | -- ******* ---- Linux-5.10.0-136.75.0.155.oe2203sp1.x86_64-x86_64-with-glibc2.36 2024-08-07 09:05:14
worker-1      | - *** --- * --- 
worker-1      | - ** ---------- [config]
worker-1      | - ** ---------- .> app:         app:0x7f8e6ad4ea70
worker-1      | - ** ---------- .> transport:   redis://:**@redis:6379/1
worker-1      | - ** ---------- .> results:     postgresql://postgres:**@db:5432/dify
worker-1      | - *** --- * --- .> concurrency: 1 (gevent)
worker-1      | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker-1      | --- ***** ----- 
worker-1      |  -------------- [queues]
worker-1      |                 .> dataset          exchange=dataset(direct) key=dataset
worker-1      |                 .> generation       exchange=generation(direct) key=generation
worker-1      |                 .> mail             exchange=mail(direct) key=mail
worker-1      |                 .> ops_trace        exchange=ops_trace(direct) key=ops_trace
worker-1      | 
worker-1      | [tasks]
worker-1      |   . schedule.clean_embedding_cache_task.clean_embedding_cache_task
worker-1      |   . schedule.clean_unused_datasets_task.clean_unused_datasets_task
worker-1      |   . tasks.add_document_to_index_task.add_document_to_index_task
worker-1      |   . tasks.annotation.add_annotation_to_index_task.add_annotation_to_index_task
worker-1      |   . tasks.annotation.batch_import_annotations_task.batch_import_annotations_task
worker-1      |   . tasks.annotation.delete_annotation_index_task.delete_annotation_index_task
worker-1      |   . tasks.annotation.disable_annotation_reply_task.disable_annotation_reply_task
worker-1      |   . tasks.annotation.enable_annotation_reply_task.enable_annotation_reply_task
worker-1      |   . tasks.annotation.update_annotation_to_index_task.update_annotation_to_index_task
worker-1      |   . tasks.batch_create_segment_to_index_task.batch_create_segment_to_index_task
worker-1      |   . tasks.clean_dataset_task.clean_dataset_task
worker-1      |   . tasks.clean_document_task.clean_document_task
worker-1      |   . tasks.clean_notion_document_task.clean_notion_document_task
worker-1      |   . tasks.deal_dataset_vector_index_task.deal_dataset_vector_index_task
worker-1      |   . tasks.delete_segment_from_index_task.delete_segment_from_index_task
worker-1      |   . tasks.disable_segment_from_index_task.disable_segment_from_index_task
worker-1      |   . tasks.document_indexing_sync_task.document_indexing_sync_task
worker-1      |   . tasks.document_indexing_task.document_indexing_task
worker-1      |   . tasks.document_indexing_update_task.document_indexing_update_task
worker-1      |   . tasks.duplicate_document_indexing_task.duplicate_document_indexing_task
worker-1      |   . tasks.enable_segment_to_index_task.enable_segment_to_index_task
worker-1      |   . tasks.mail_invite_member_task.send_invite_member_mail_task
worker-1      |   . tasks.ops_trace_task.process_trace_tasks
worker-1      |   . tasks.recover_document_indexing_task.recover_document_indexing_task
worker-1      |   . tasks.remove_document_from_index_task.remove_document_from_index_task
worker-1      |   . tasks.retry_document_indexing_task.retry_document_indexing_task
worker-1      |   . tasks.sync_website_document_indexing_task.sync_website_document_indexing_task
worker-1      | 
worker-1      | [2024-08-07 09:05:14,359: INFO/MainProcess] Connected to redis://:**@redis:6379/1
worker-1      | [2024-08-07 09:05:14,365: INFO/MainProcess] mingle: searching for neighbors
worker-1      | [2024-08-07 09:05:15,378: INFO/MainProcess] mingle: all alone
worker-1      | [2024-08-07 09:05:15,400: INFO/MainProcess] celery@8889da14a391 ready.
worker-1      | [2024-08-07 09:05:15,405: INFO/MainProcess] pidbox: Connected to redis://:**@redis:6379/1.

### ✔️ Expected Behavior

The web page can be accessed normally

### ❌ Actual Behavior

404 page not found

**Comment by 0sengseng0** [comment]
I found this bug in other issues, but they all had access to the web page, which I couldn't: None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used

#  docker-api-1   log
[root@node172 ~]# docker logs docker-api-1
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Preparing database migration...
Database migration skipped
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[2024-08-07 09:05:13 +0000] [147] [INFO] Starting gunicorn 22.0.0
[2024-08-07 09:05:13 +0000] [147] [INFO] Listening at: http://0.0.0.0:5001 (147)
[2024-08-07 09:05:13 +0000] [147] [INFO] Using worker: gevent
[2024-08-07 09:05:13 +0000] [286] [INFO] Booting worker with pid: 286

**Comment by crazywoola** [comment]
This log seems good to me, didn't report any errors. I guess you have configured the environment wrongly. 

I suggest you could upgrade to the latest version and modify the environment variables accordingly.

Not a bug to me as well.
