### ISSUE TITLE
how to close renegotiation?

### ISSUE THREAD

**Issue by Modas-Li** [langgenius/dify#7054]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

V0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

request for https server without renegotiation.

### ✔️ Expected Behavior

Steps for close renegotiation.

### ❌ Actual Behavior

nothing related

**Comment by crazywoola** [comment]
This is bug report template only. If you have questions regarding this. Please go to https://github.com/langgenius/dify/discussions
