### ISSUE TITLE
Can the studio have the same permissions as the knowledge?

### ISSUE THREAD

**Issue by dgedanke** [langgenius/dify#7055]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

You can set three permissions for the knowledge:

* Only me
* All team members
* Partial team members

I want the studio part to have similar permissions to the knowledge.
In the future, is there any official plan or arrangement to implement this function?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/6217

**Comment by IciestEconomist** [comment]
Take me to your leader :) 
Which state is pm?

**Comment by ddnoodle** [comment]
I just want to post the same enhancement to request this feature. Now I saw this one.
Yes, the role based App management in studio is very important to us as we have a team work in the same space.

**Comment by VincePotato** [comment]
Thank you for your suggestion. We will include it in our product roadmap.
