### ISSUE TITLE
Unable to log in with a local email account.

### ISSUE THREAD

**Issue by qiuqi** [langgenius/dify#7065]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After the local deployment is completed, the login interface only allows logging in through GitHub or Gmail, and the option to log in using your own email account is no longer available

### ✔️ Expected Behavior

The previous version supported logging in with a local email account.

### ❌ Actual Behavior

After the upgrade, there is no place for the previous accounts to log in.

**Comment by crazywoola** [comment]
Check this line
https://github.com/langgenius/dify/blob/8bca908f1571bca85860425c7b3b4b314315d666/web/.env.example#L4

**Comment by qiuqi** [comment]
NEXT_PUBLIC_EDITION=SELF_HOSTED 

resolved with this change.
