### ISSUE TITLE
Can't connect OpenAI compatible api because no gpt-3.5 found

### ISSUE THREAD

**Issue by imkebe** [langgenius/dify#7068]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

It's an regresion of #4460 or a variant with custom model.

Just add a OpenAI configuration or model.

Model Name:
custom-model-name

API Key:
sk-custom-one

Org:
Ecma Org

API Base:
http://your.litellm.hostname:4000

Hostname is accesible from the container. Other services are using the same LiteLLM Proxy without issue

### ✔️ Expected Behavior

While LiteLLM is proivding compatible Proxy with custom model list it should be able to add a custom model.

### ❌ Actual Behavior

Base model custom-model-name not found.

**Comment by imkebe** [comment]
I know i'm replaying to bot, however the model name in liteLLM can be custom and without of any version of gpt-3.5 exposed. I've tried with multiple model names the LiteLLM is exposing and other services are using but only Dify is in responce showing an error that the gpt-3.5 not found.

**Comment by imkebe** [comment]
LocalAI cannot be used as a Dify backend because there is no field to put the access key. However all mentioned points are correct. The issue seems to be a default unnecessary dependency of gpt-3.5 model in response of OpenAI endpoint.

**Comment by crazywoola** [comment]
Hello we do not have `2.19.4` this version. Can you edit that again?

**Comment by imkebe** [comment]
> Hello we do not have `2.19.4` this version. Can you edit that again?

It's 0.6.15

**Comment by Lorde627** [comment]
The newly launched GitHub Models also encountered the same situation, as GitHub Models do not provide the GPT-3.5 model, making it unusable. Since OpenAI announced that 3.5 will be phased out, it is recommended to change the default verification model to GPT-4o-mini.

**Comment by luxinfeng** [comment]
We're still facing this issue now.

**Comment by crazywoola** [comment]
> We're still facing this issue now.

Fixed today #9387
