### ISSUE TITLE
The service for text indexing is too laggy

### ISSUE THREAD

**Issue by Lxx-c** [langgenius/dify#7074]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

As shown in the question, the service is stuck when indexing documents. It is not clear what the reason is, especially when the uploaded documents are large. However, according to the documentation, the main service and worker services are separate, and documents should not affect the main service when indexing. I deployed it using the source code, and the main service mentioned above mainly refers to the studio session.

**Comment by 401557122** [comment]
The same problem seems to be very common. Even if I use different celeries and set the concurrency of each one to 128, when uploading particularly large files, it still blocks all services, not just the dataset service @JohnJyong

**Comment by Lxx-c** [comment]
@401557122 Hi, have you solved this problem? @JohnJyong @crazywoola May I ask if you have located the cause? This problem has a serious impact on the use process, and it has been raised for 2 weeks.

**Comment by JohnJyong** [comment]
No logs and error information are provided, making it impossible to troubleshoot. you can reopen it  with more detail
