### ISSUE TITLE
The input variable in the http node in the workflow does not have the result of the knowledge_retrieval node

### ISSUE THREAD

**Issue by youqugit** [langgenius/dify#7077]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

The input variable in the http node in the workflow does not have the result of the knowledge_retrieval node.
![image](https://github.com/user-attachments/assets/82e1174d-33f5-407c-88eb-f7ff2a832966)

### ✔️ Expected Behavior

There should be this option knowledge retrieval
result
Array[Object]
![image](https://github.com/user-attachments/assets/2b41b2a1-df65-4ced-b533-c0445f96eeb5)

**Comment by crazywoola** [comment]
Because the output of the Knowledge retrieval is not plain text, it return results in array, so you could use a code node or jinja node to extract things as you want, then they are able to be referenced node.
