### ISSUE TITLE
Unable to change the Embedding Model

### ISSUE THREAD

**Issue by dc-vin** [langgenius/dify#7078]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After changing the Embedding Model in Knowledge settings and clicking save, the Embedding Model reverts to the original model upon the next login.
![image](https://github.com/user-attachments/assets/403b1ded-6f8d-4cb1-8fc3-cbe793c27412)
When I change the model from 002 to small and click save, upon logging in again, the model reverts to 002.

**Comment by dc-vin** [comment]
Will this issue be fixed in future versions?

**Comment by crazywoola** [comment]
I can not reproduce this in latest version.
