### ISSUE TITLE
The Qwen2-72B-Instruct model tool calling error 400 with "Currently only named tools are supported"

### ISSUE THREAD

**Issue by YvanCheng** [langgenius/dify#7080]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

like #6793 , It's closed, but I don't think this is the same issue, and the error codes are also different. I upgraded to 0.6.16, but still receive the same issue.

I deployed Dify through Docker and deployed the Qwen2-72B-Struct and GLM-4 models. When using the Agent function, I found that GLM-4 could call Tools normally, but Qwen2 always prompted 400, The error message is as follows:

[openai_api_compatible] Error: API request failed with status code 400: {"object":"error","message":"[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, Currently only named tools are supported.', 'input': {'model': 'Qwen2', 'stream': True, 'messages': [{'role': 'system', 'content': '用户输入：\\n查询[具体地区]\\n的天气情况。'}, {'role': 'user', 'content': '你好'}], 'tool_choice': 'auto', 'tools': [{'type': 'function', 'function': {'name': 'GetCurrentWeather', 'description': 'Get temperature for a specific location', 'parameters': {'type': 'object', 'properties': {'location': {'type': 'string', 'description': 'The city and state to retrieve the weather for'}}, 'required': ['location']}}}], 'user': '9fa31c2a-db1c-406f-b4a3-e9be5b1dcf81'}, 'ctx': {'error': ValueError('**Currently only named tools are supported**.')}}]","type":"BadRequestError","param":null,"code":400}
![agent-error](https://github.com/user-attachments/assets/a7c69857-2e31-4b81-b443-5a925d96c3f5)

tools json as follows:

{
      "openapi": "3.1.0",
      "info": {
        "title": "Get weather data",
        "description": "Retrieves current weather data for a location.",
        "version": "v1.0.0"
      },
      "servers": [
        {
          "url": "https://wttr.in"
        }
      ],
      "paths": {
        "/{location}": {
          "get": {
            "description": "Get temperature for a specific location",
            "operationId": "GetCurrentWeather",
            "parameters": [
              {
                "name": "location",
                "in": "path",
                "description": "The city and state to retrieve the weather for",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "deprecated": false
          }
        }
      },
      "components": {
        "schemas": {}
      }
    }

At first, I knew that there was a problem with deploying the Qwen2, but Dify was able to call Qwen2 normally, but could not call Tools:
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/b77b4a63-40a5-40d8-8ef2-b3f775a03cbd">

### ✔️ Expected Behavior

call  tools normally

### ❌ Actual Behavior

call tools error

**Comment by YvanCheng** [comment]
<img width="231" alt="image" src="https://github.com/user-attachments/assets/3f088f32-c70c-4c9f-afc9-582e00c5cfc3">
I did not use YAML format, I used JSON format, and directly referenced the content in the example, which appears to be the recognized operationId as the tool name, without passing in the name

**Comment by wltj920** [comment]
## Problem description

I meet the same bug in 0.7.1, when I use vllm to deploy a qwen2-72b model, and config the model in `OpenAI-API-compatible`, the bug will reappear.

And I test when I use ollama to deploy  qwen2-72b model, and config a `Ollama` model in dify, the bug will disappeared.

## Problem check

I found the log in vllm, it said vllm received a request with wrong parameters like this:

```json
[
    {
        "type": "value_error",
        "loc": ("body",),
        "msg": "Value error, Currently only named tools are supported.",
        "input": {
            "model": "gzwy2s",
            "stream": True,
            "messages": [
                {
                    "role": "system",
                    "content": "You are a powerful AI assistent, please help user.\n"
                },
                {
                    "role": "user",
                    "content": "Who are you?"
                }
            ],
            "tool_choice": "auto",
            "tools": [
                {
                    "type": "function",
                    "function": {
                        "name": "VendorSalesDataQA",
                        "description": "A vendor quality assurance tool for sales data.",
                        "parameters": {
                            "type": "object",
                            "properties": {
                                "query": {
                                    "type": "string",
                                    "description": "A question for QA."
                                }
                            },
                            "required": [
                                "query"
                            ]
                        }
                    }
                },
                {
                    "type": "function",
                    "function": {
                        "name": "dataset_512e2889_77d0_460e_8755_a5efe1eed5ac",
                        "description": "useful for when you want to answer queries about the vendor.pdf",
                        "parameters": {
                            "type": "object",
                            "properties": {
                                "query": {
                                    "type": "string",
                                    "description": "Query for the dataset to be used to retrieve the dataset."
                                }
                            },
                            "required": [
                                "query"
                            ]
                        }
                    }
                }
            ],
            "user": "dd56a2db-da80-4050-839c-44728a072a99"
        },
        "ctx": {
            "error": ValueError("Currently only named tools are supported.")
        }
    }
]
```

you can paste the join into VSCode IDE, you will find a json syntax error:

**Comment by wltj920** [comment]
I try to use the same parameter to request a llm deployed by `vllm`, the same problem will appear again. @takatost

**Comment by XUANYUANRuins** [comment]
Have you resolved this issue? It also occurred in version 1.0.1
