### ISSUE TITLE
Installed text generation app icon incorrect

### ISSUE THREAD

**Issue by xuzuodong** [langgenius/dify#7091]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

- Under "Explore" tab, fork any "COMPLETION" app
- In the "Create app from  ..." dialog, change the default App icon, then click "Create". For example:
<img width="882" alt="image" src="https://github.com/user-attachments/assets/d9f4b9d8-e184-442f-b3ec-abda9c672c94">
- Go back to "Explore" tab, click the app on the left sidebar that just created
- Check the app logo displayed at main panel is incorrect:
<img width="686" alt="image" src="https://github.com/user-attachments/assets/86ae509b-78b1-4e60-8ae4-e26eead57d4d">

### ✔️ Expected Behavior

The app logo displayed at main panel should be the same as displayed on left sidebar

### ❌ Actual Behavior

The app logo displayed at main panel is incorrectly displaying default icon style

**Comment by crazywoola** [comment]
Each application has two icon, an icon displayed in the list, and an icon displayed in shared application which you can find in application -> monitoring , they have different settings.

<img width="747" alt="image" src="https://github.com/user-attachments/assets/c7d2c3ee-e63b-491b-8378-b69c652789b2">

**Comment by xuzuodong** [comment]
> Each application has two icon, an icon displayed in the list, and an icon displayed in shared application which you can find in application -> monitoring , they have different settings.

I'm aware of that, the problem is that settings is `monitoring` page still won't affect installed text generation app. 

I've submitted a PR to fix it.
