### ISSUE TITLE
when publish new workflow tool provider failed with existed name or app_id

### ISSUE THREAD

**Issue by zhuqingchao** [langgenius/dify#7099]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1.  create a workflow. then publish a workflow tool with "Tool call name" what ever.
2. delete the workflow. then the tool will be deleted too. （Here is the key, not really deleted or soft deleted）
3. repeat 1 step. publish with same "Tool call name".
4. failed with "Tool with name xxx or app_id xxx already exists"

### ✔️ Expected Behavior

the old one tool should be deleted. 
the new one should bu published sucessful

### ❌ Actual Behavior

the old one tool not really be deleted.
the new one with same tool call name publish failed

**Comment by zhuqingchao** [comment]
![image](https://github.com/user-attachments/assets/37699dc3-1bb9-49fc-93d2-6380a119274b)
1. the table fileds has no soft delete flag
2. maybe other tool has same problem. maybe should check too.

**Comment by crazywoola** [comment]
I notice you are using source code to deploy, have you started the celery worker?

**Comment by zhuqingchao** [comment]
there nothing with celery.  can u delete first  and create with the same  "Tool call name". not the name
1. create a workflow. then publish a workflow tool with "Tool call name" what ever.
2. delete the workflow. then the tool will be deleted too. （Here is the key, not really deleted or soft deleted）
3. repeat 1 step. publish with same "Tool call name".
4. failed with "Tool with name xxx or app_id xxx already exists"
![image](https://github.com/user-attachments/assets/31ff18fe-e5f4-4e51-8fc2-5dc0b052033c)

**Comment by zhuqingchao** [comment]
![image](https://github.com/user-attachments/assets/993302d5-daa2-4263-b9a6-ec7589398ce0)
workflow_tools_manage_service.py  source code
