### ISSUE TITLE
Claude model can not change Max Tokens

### ISSUE THREAD

**Issue by mjjjjjjjjjjy** [langgenius/dify#7104]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Claude model can not change Max Tokens
![Snipaste_2024-08-08_16-48-47](https://github.com/user-attachments/assets/0cd96202-722e-49d6-95fb-e8311fc109b9)

**Comment by crazywoola** [comment]
`max tokens ` is required in it's api. So you can not turn off it by default.
