### ISSUE TITLE
Can Multiple Branches Directly Lead to the Same Node?

### ISSUE THREAD

**Issue by linliyuan** [langgenius/dify#7108]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

As shown below, there are two branches whose final results both lead to a single model review. However, because a model can only be connected to one branch, it necessitates copying the model, making it difficult to manage.

![image](https://github.com/user-attachments/assets/0dee5191-066d-4480-9dd5-e94fd0503f66)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes you can use https://docs.dify.ai/guides/workflow/node/variable-assigner to do it.
