### ISSUE TITLE
Input parameter don't change while I provide the conversation_id in /chat-messages API

### ISSUE THREAD

**Issue by delvin-sparkle** [langgenius/dify#7120]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I created a workflow in Dify and configured an input parameter called pet_story at the start node. I use the /chat-messages API for the chat, and since I need to continue the conversation based on previous chat records, I have to pass the conversation_id from earlier messages. However, I’ve found that as long as I provide the conversation_id, the value of the pet_story parameter in the workflow never changes, regardless of what value I pass for pet_story—it always stays the same as the first value I provided.

### ✔️ Expected Behavior

input parameter can be changed while I provide the conversation_id in /chat-messages API

### ❌ Actual Behavior

input parameter don't change while I provide the conversation_id in /chat-messages API

**Comment by crazywoola** [comment]
This is a known issue, or by design. We do not support modify those parameters in this way.
