### ISSUE TITLE
 Add Gemini Pro Experimental

### ISSUE THREAD

**Issue by Yatima-Kagurazaka** [langgenius/dify#7121]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Google [added the experimental Gemini 1.5 Pro](https://x.com/OfficialLoganK/status/1819041453978357899) last week.

It's an open question to add experimental models to Dify, but I think we should do it this time for the following reasons;
- The model got 1st place in Chatbot Arena
- The users can't add new Gemini models to Dify manually

I already prepared the yaml file, but I open this issue because I saw that I should do so in the contribution guide and I think I should hear comments from others.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by CXwudi** [comment]
Any progress?

**Comment by CXwudi** [comment]
I added the PR
