### ISSUE TITLE
Use dataset api create a dataset, but i can not see this dataset in dify control desk

### ISSUE THREAD

**Issue by LoveleeKay** [langgenius/dify#7134]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. dataset api create a dataset
2. look at the dify dataset view, cannot find the dataset
![image](https://github.com/user-attachments/assets/f3f661d2-06c5-4e44-9dcd-186eea93033e)
![image](https://github.com/user-attachments/assets/2f8a149a-9a36-4e14-9cae-f7870c341426)

### ✔️ Expected Behavior

can find the dataset

### ❌ Actual Behavior

can not see the dataset

**Comment by crazywoola** [comment]
<img width="733" alt="image" src="https://github.com/user-attachments/assets/8039954b-7a46-4222-bd25-e76e2874f072">
<img width="853" alt="image" src="https://github.com/user-attachments/assets/a453bdcb-316f-4d54-adb9-3d49d1433a8a">

Hello I was not able to reproduce this issue on latest cloud version, maybe you can try to upgrade to the latest version.

**Comment by LoveleeKay** [comment]
@crazywoola  our dify ,owner can see my created dataset, but i (myself) can not see.

**Comment by crazywoola** [comment]
I see your point. It's because the API key is available for all users.

**Comment by LoveleeKay** [comment]
@crazywoola  i use the latest 16 version ，also cannot see my created dataset, but when i created one same name dataset, it occurs one error promt
![image](https://github.com/user-attachments/assets/36541ffa-9f9a-45cf-b9c3-965a7e3d14b4)![image](https://github.com/user-attachments/assets/9811daf1-94e0-4a2a-a255-cee7a5ad9d72)

**Comment by crazywoola** [comment]
It's a permission issue, I have talked to our team members regarding this to see what we can do.

**Comment by LoveleeKay** [comment]
@crazywoola  i am looking forward to this being resolved in the next version. thank you

**Comment by whshang** [comment]
> @crazywoola i use the latest 16 version ，also cannot see my created dataset, but when i created one same name dataset, it occurs one error promt ![image](https://private-user-images.githubusercontent.com/35088017/356519366-36541ffa-9f9a-45cf-b9c3-965a7e3d14b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDgxNzUsIm5iZiI6MTcyNDY0Nzg3NSwicGF0aCI6Ii8zNTA4ODAxNy8zNTY1MTkzNjYtMzY1NDFmZmEtOWY5YS00NWNmLWI5YzMtOTY1YTdlM2QxNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA0NTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNDVhM2Y4ZTEzMjNlYzNiMDQ1NjAyNDE2YjRmZDVmOGI4ZWE3MTc1YjRhOTg3NzAzYzIzOTdlMzkwNTRkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8xkYtoo70wchqNprDn8y8NDx52f11mxmzFbG0lsUZGk)![image](https://private-user-images.githubusercontent.com/35088017/356519492-9811daf1-94e0-4a2a-a255-cee7a5ad9d72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDgxNzUsIm5iZiI6MTcyNDY0Nzg3NSwicGF0aCI6Ii8zNTA4ODAxNy8zNTY1MTk0OTItOTgxMWRhZjEtOTRlMC00YTJhLWEyNTUtY2VlN2E1YWQ5ZDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA0NTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NTMxNzFiNGQyZWM1YTlkNjNiODc1ZTA2N2Q1NjBiNWM5MzVjZDlhOGYzNDk1ZjI0YzU2OTY1MmI5YTU5YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Fq22AhQf1xZTUkTx0NouyGiPlkRzso0xWMNyMeC2ZY)

same issue, latest version 20240826

**Comment by CongTang** [comment]
HI @whshang  and @LoveleeKay 

I get the same issue and I resolve them by deleting all the existing datasets and recreating those datasets via API, and it works.

Hope this will help you.

Kind regards
Cong
