### ISSUE TITLE
Unable to access a knowledge base because of some version issue

### ISSUE THREAD

**Issue by PeriwigXu** [langgenius/dify#7136]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I was trying to config my knowledge base, but it told me there was a client-side exception.
![knowledgebase-exception](https://github.com/user-attachments/assets/937b8ec5-425a-49ab-8498-0e4a5cbd71f9)
I guess it was caused by some version mistakes of certain python packages, but I'm not sure how to solve it.
The error message is below.

### ❌ Actual Behavior

difyapi       | /app/api/core/workflow/nodes/llm/llm_node.py:305: DeprecationWarning: This method is deprecated, use `get` instead.
difyapi       |   variable_value = variable_pool.get_any(variable_selector.value_selector)
difyapi       | /app/api/core/workflow/nodes/llm/llm_node.py:353: DeprecationWarning: This method is deprecated, use `get` instead.
difyapi       |   context_value = variable_pool.get_any(node_data.context.variable_selector)
difyapi       | /app/api/.venv/lib/python3.10/site-packages/pydantic/main.py:1282: PydanticDeprecatedSince20: The `copy` method is deprecated; use `model_copy` instead. See the docstring of `BaseModel.copy` for details about how to handle `include` and `exclude`. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
difyapi       |   warnings.warn(
difyapi       | /app/api/.venv/lib/python3.10/site-packages/pydantic/main.py:1358: PydanticDeprecatedSince20: The `validate` method is deprecated; use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
difyapi       |   warnings.warn(

**Comment by crazywoola** [comment]
Hello can you paste the errors in web console? It seems to be a frontend issue.

**Comment by PeriwigXu** [comment]
> Hello can you paste the errors in web console? It seems to be a frontend issue.

Sure
![frontend_err](https://github.com/user-attachments/assets/cfec85b5-f104-4fb8-86bf-3bea552a0a60)

**Comment by crazywoola** [comment]
@dosu.Generate a fix for this

> > Hello can you paste the errors in web console? It seems to be a frontend issue.
> 
> Sure ![frontend_err](https://private-user-images.githubusercontent.com/35323725/356508762-cfec85b5-f104-4fb8-86bf-3bea552a0a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTIyMzgsIm5iZiI6MTcyMzE5MTkzOCwicGF0aCI6Ii8zNTMyMzcyNS8zNTY1MDg3NjItY2ZlYzg1YjUtZjEwNC00ZmI4LTg2YmYtM2JlYTU1MmEwYTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMDYzMDAwODVhMTRlMTY1ZmQ0ODAwMWMyOGFmYmQ5ZGZjNThkM2E0YWQyZDQzZTNmOTVkNzUxZjM4YmMyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qq35Ao7IesL9MbM717stX8AcGOaLT8POAK570r37NPM)

**Comment by yinlianggood** [comment]
升级到最新版本，可以解决这个问题？ 昨天新建的知识库还是正常的， 今天就打开报这个错了

**Comment by crazywoola** [comment]
It should be fixed in 0.8.x
