### ISSUE TITLE
Setup Authorization for Searxng is terrible.

### ISSUE THREAD

**Issue by iplayfast** [langgenius/dify#7157]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Try to use the tool searxng

### ✔️ Expected Behavior

text prompt asking for the url to access it. (Authorisation is not part of it).
text input that can be typed into with out it being hidden.
When an error occurs the error remains in a second block under the text input.

### ❌ Actual Behavior

Says "To Authorise" when is should be "To configure"
When going it the button
It gives the title "SearXNG base URL" which is fine, but then the input is hidden as though it were a password. This is very frustrating because they url is easily mistyped, and if you can't see what you are doing you don't know if the resulting error is from what you typed or something else.
Any error reported shows for half a second, barely giving time to read it, then it disappears. It should be put in the display without disappearing.

**Comment by crazywoola** [comment]
Sorry for the late response.  I need to clarify several things

<img width="806" alt="image" src="https://github.com/user-attachments/assets/819db31b-78b5-4f00-9e24-a5297cb99076">

- Are you able to access the searxng after running the docker command? 
- Have you check the settings.yml in the container which might has the line `- json` 

<img width="486" alt="image" src="https://github.com/user-attachments/assets/b9e8d52c-8b3a-4bca-9f19-3a578340cfa8">

Things I changed according to your requirements:

- I changed the secret-input to text-input
- I checked the settings.yml in container, if the `- json` is missing, it will have a 403 issue as you described in https://github.com/langgenius/dify/issues/6777
