### ISSUE TITLE
After dify is started for the first time, the localhost/install page keeps spinning in circles, and the admin administrator password cannot be entered.

### ISSUE THREAD

**Issue by lizhanyang505** [langgenius/dify#7159]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

git clone main

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Follow the following document to install and start: https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/local-source-code The parameters have not been changed. But when I enter local/install, I cannot set up an administrator account and it keeps spinning.
2. docker and flask ，celery start succed
3. current proejct use git clone https://github.com/langgenius/dify.git. please help me . 
![image](https://github.com/user-attachments/assets/6cf22e69-2d13-437d-980f-a0a8fd033a80)

### ✔️ Expected Behavior

how to fix it?

**Comment by crazywoola** [comment]
Duplicated. Please set the environment variables accodingly.

**Comment by lizhanyang505** [comment]
@crazywoola  After following your operation, I found that the same situation still exists. The following is the docker log information.
![image](https://github.com/user-attachments/assets/999f790d-082a-43e8-8486-6bcf2350ca42)
redis-1  | 1:C 10 Aug 2024 05:35:29.567 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1  | 1:C 10 Aug 2024 05:35:29.567 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1  | 1:C 10 Aug 2024 05:35:29.567 # Configuration loaded
redis-1  | 1:M 10 Aug 2024 05:35:29.568 * monotonic clock: POSIX clock_gettime
redis-1  | 1:M 10 Aug 2024 05:35:29.568 * Running mode=standalone, port=6379.
redis-1  | 1:M 10 Aug 2024 05:35:29.568 # Server initialized
redis-1  | 1:M 10 Aug 2024 05:35:29.568 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-1  | 1:M 10 Aug 2024 05:35:29.570 * Loading RDB produced by version 6.2.14
redis-1  | 1:M 10 Aug 2024 05:35:29.570 * RDB age 46 seconds
redis-1  | 1:M 10 Aug 2024 05:35:29.570 * RDB memory usage when created 0.78 Mb
redis-1  | 1:M 10 Aug 2024 05:35:29.570 # Done loading RDB, keys loaded: 5, keys expired: 0.
redis-1  | 1:M 10 Aug 2024 05:35:29.570 * DB loaded from disk: 0.000 seconds
redis-1  | 1:M 10 Aug 2024 05:35:29.570 * Ready to accept connections
ssrf_proxy-1  | [ENTRYPOINT] re-create snakeoil self-signed certificate removed in the build process
ssrf_proxy-1  | [ENTRYPOINT] replacing environment variables in the template
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/squid.conf (depth 0)
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
ssrf_proxy-1  | 2024/08/10 05:35:30| Created PID file (/run/squid.pid)
ssrf_proxy-1  | 2024/08/10 05:35:30| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/10 05:35:30| Creating missing swap directories
ssrf_proxy-1  | 2024/08/10 05:35:30| No cache_dir stores are configured.
ssrf_proxy-1  | 2024/08/10 05:35:30| Removing PID file (/run/squid.pid)
ssrf_proxy-1  | [ENTRYPOINT] starting squid
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/squid.conf (depth 0)
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
ssrf_proxy-1  | 2024/08/10 05:35:30| Created PID file (/run/squid.pid)
db-1          | 
db-1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
ssrf_proxy-1  | 2024/08/10 05:35:30| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/10 05:35:30| Creating missing swap directories
sandbox-1     | 2024/08/10 05:35:29 setup.go:29: [INFO]initializing nodejs runner environment...
sandbox-1     | 2024/08/10 05:35:29 setup.go:85: [INFO]nodejs runner environment initialized
sandbox-1     | 2024/08/10 05:35:29 setup.go:31: [INFO]initializing python runner environment...
sandbox-1     | 2024/08/10 05:35:29 setup.go:43: [INFO]python runner environment initialized
weaviate-1    | {"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2024-08-10T05:35:29Z"}
weaviate-1    | {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2024-08-10T05:35:29Z"}
db-1          | 
ssrf_proxy-1  | 2024/08/10 05:35:30| No cache_dir stores are configured.
weaviate-1    | {"action":"grpc_startup","level":"info","msg":"grpc server listening at [::]:50051","time":"2024-08-10T05:35:29Z"}
weaviate-1    | {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2024-08-10T05:35:29Z"}
ssrf_proxy-1  | 2024/08/10 05:35:30| Removing PID file (/run/squid.pid)
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/squid.conf (depth 0)
db-1          | 2024-08-10 05:35:29.543 UTC [1] LOG:  starting PostgreSQL 15.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
db-1          | 2024-08-10 05:35:29.543 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1          | 2024-08-10 05:35:29.543 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1          | 2024-08-10 05:35:29.543 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1          | 2024-08-10 05:35:29.546 UTC [29] LOG:  database system was shut down at 2024-08-10 05:34:43 UTC
db-1          | 2024-08-10 05:35:29.551 UTC [1] LOG:  database system is ready to accept connections
sandbox-1     | 2024/08/10 05:35:29 config.go:86: [INFO]network has been enabled
sandbox-1     | 2024/08/10 05:35:29 config.go:102: [INFO]using https proxy: http://ssrf_proxy:3128
sandbox-1     | 2024/08/10 05:35:29 config.go:111: [INFO]using http proxy: http://ssrf_proxy:3128
sandbox-1     | 2024/08/10 05:35:29 server.go:19: [INFO]config init success
sandbox-1     | 2024/08/10 05:35:29 server.go:25: [INFO]runner dependencies init success
sandbox-1     | 2024/08/10 05:35:29 server.go:41: [INFO]installing python dependencies...
sandbox-1     | 2024/08/10 05:35:29 server.go:47: [INFO]python dependencies installed
sandbox-1     | 2024/08/10 05:35:29 cocrrent.go:31: [INFO]setting max requests to 50
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/conf.d/debian.conf (depth 1)
ssrf_proxy-1  | 2024/08/10 05:35:30| Processing Configuration File: /etc/squid/conf.d/rock.conf (depth 1)
ssrf_proxy-1  | 2024/08/10 05:35:30| Created PID file (/run/squid.pid)
ssrf_proxy-1  | 2024/08/10 05:35:30| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/10 05:35:30| Starting Squid Cache version 6.6 for x86_64-pc-linux-gnu...
ssrf_proxy-1  | 2024/08/10 05:35:30| Service Name: squid
sandbox-1     | 2024/08/10 05:35:29 cocrrent.go:13: [INFO]setting max workers to 4
ssrf_proxy-1  | 2024/08/10 05:35:30| Process ID 45
sandbox-1     | [GIN] 2024/08/10 - 05:35:57 | 401 |        4.06µs |              :: | GET      "/squid-internal-dynamic/netdb"
ssrf_proxy-1  | 2024/08/10 05:35:30| Process Roles: master worker
ssrf_proxy-1  | 2024/08/10 05:35:30| With 1024 file descriptors available
ssrf_proxy-1  | 2024/08/10 05:35:30| Initializing IP Cache...
ssrf_proxy-1  | 2024/08/10 05:35:30| DNS IPv6 socket created at [::], FD 8
ssrf_proxy-1  | 2024/08/10 05:35:30| DNS IPv4 socket created at 0.0.0.0, FD 9
ssrf_proxy-1  | 2024/08/10 05:35:30| Adding nameserver 127.0.0.11 from /etc/resolv.conf
ssrf_proxy-1  | 2024/08/10 05:35:30| Adding domain . from /etc/resolv.conf
ssrf_proxy-1  | 2024/08/10 05:35:30| Adding ndots 1 from /etc/resolv.conf
ssrf_proxy-1  | 2024/08/10 05:35:30| Logfile: opening log daemon:/var/log/squid/access.log
ssrf_proxy-1  | 2024/08/10 05:35:30| Logfile Daemon: opening log /var/log/squid/access.log
ssrf_proxy-1  | 2024/08/10 05:35:30| Local cache digest enabled; rebuild/rewrite every 3600/3600 sec
ssrf_proxy-1  | 2024/08/10 05:35:30| Store logging disabled
ssrf_proxy-1  | 2024/08/10 05:35:30| Swap maxSize 0 + 262144 KB, estimated 20164 objects
ssrf_proxy-1  | 2024/08/10 05:35:30| Target number of buckets: 1008
ssrf_proxy-1  | 2024/08/10 05:35:30| Using 8192 Store buckets
ssrf_proxy-1  | 2024/08/10 05:35:30| Max Mem  size: 262144 KB
ssrf_proxy-1  | 2024/08/10 05:35:30| Max Swap size: 0 KB
ssrf_proxy-1  | 2024/08/10 05:35:30| Using Least Load store dir selection
ssrf_proxy-1  | 2024/08/10 05:35:30| Set Current Directory to /var/spool/squid
ssrf_proxy-1  | 2024/08/10 05:35:30| Finished loading MIME types and icons.
ssrf_proxy-1  | 2024/08/10 05:35:30| HTCP Disabled.
ssrf_proxy-1  | 2024/08/10 05:35:30| Pinger socket opened on FD 15
ssrf_proxy-1  | 2024/08/10 05:35:30| Squid plugin modules loaded: 0
ssrf_proxy-1  | 2024/08/10 05:35:30| Adaptation support is off.
ssrf_proxy-1  | 2024/08/10 05:35:30| Accepting HTTP Socket connections at conn3 local=[::]:3128 remote=[::] FD 12 flags=9
ssrf_proxy-1  |     listening port: 3128
ssrf_proxy-1  | 2024/08/10 05:35:30| Accepting reverse-proxy HTTP Socket connections at conn5 local=[::]:8194 remote=[::] FD 13 flags=9
ssrf_proxy-1  |     listening port: 8194
ssrf_proxy-1  | 2024/08/10 05:35:30| Configuring Parent sandbox
ssrf_proxy-1  | 2024/08/10 05:35:30 pinger| Initialising ICMP pinger ...
ssrf_proxy-1  | 2024/08/10 05:35:30 pinger| ICMP socket opened.
ssrf_proxy-1  | 2024/08/10 05:35:30 pinger| ICMPv6 socket opened
ssrf_proxy-1  | 2024/08/10 05:35:31| storeLateRelease: released 0 objects

**Comment by lizhanyang505** [comment]
this is my computer configuration:  total        used        free      shared  buff/cache   available
内存：      188Gi       2.3Gi       175Gi        18Mi       9.9Gi       184Gi
交换：      2.0Gi       1.3Gi       688Mi

**Comment by lizhanyang505** [comment]
flask db upgrade

/opt/data1/app/anaconda3/envs/py3.10_tfm/lib/python3.10/site-packages/gevent/os.py:426: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = fork()
2024-08-10 05:39:19,491.491 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 64b051264f32, init
INFO  [alembic.runtime.migration] Running upgrade 64b051264f32 -> 9f4e3427ea84, add created by role
INFO  [alembic.runtime.migration] Running upgrade 9f4e3427ea84 -> a45f4dfde53b, add language to recommend apps
INFO  [alembic.runtime.migration] Running upgrade a45f4dfde53b -> 614f77cecc48, add last active at
INFO  [alembic.runtime.migration] Running upgrade 614f77cecc48 -> e32f6ccb87c6, e08af0a69ccefbb59fa80c778efee300bb780980
INFO  [alembic.runtime.migration] Running upgrade e32f6ccb87c6 -> d3d503a3471c, add is_deleted to conversations
INFO  [alembic.runtime.migration] Running upgrade d3d503a3471c -> a5b56fb053ef, app config add speech_to_text
INFO  [alembic.runtime.migration] Running upgrade a5b56fb053ef -> 2beac44e5f5f, add is_universal in apps
INFO  [alembic.runtime.migration] Running upgrade 2beac44e5f5f -> 7ce5a52e4eee, add tool providers
INFO  [alembic.runtime.migration] Running upgrade 7ce5a52e4eee -> 8d2d099ceb74, add_qa_model_support
INFO  [alembic.runtime.migration] Running upgrade 8d2d099ceb74 -> 16fa53d9faec, add provider model support
INFO  [alembic.runtime.migration] Running upgrade 16fa53d9faec -> e35ed59becda, modify quota limit field type
INFO  [alembic.runtime.migration] Running upgrade e35ed59becda -> bf0aec5ba2cf, add provider order
INFO  [alembic.runtime.migration] Running upgrade bf0aec5ba2cf -> 5022897aaceb, add model name in embedding
INFO  [alembic.runtime.migration] Running upgrade 5022897aaceb -> 2c8af9671032, add_qa_document_language
INFO  [alembic.runtime.migration] Running upgrade 2c8af9671032 -> e8883b0148c9, add_dataset_model_name
INFO  [alembic.runtime.migration] Running upgrade e8883b0148c9 -> 853f9b9cd3b6, add message price unit
INFO  [alembic.runtime.migration] Running upgrade 853f9b9cd3b6 -> 4bcffcd64aa4, update_dataset_model_field_null_available
INFO  [alembic.runtime.migration] Running upgrade 4bcffcd64aa4 -> 6dcb43972bdc, add_dataset_retriever_resource
INFO  [alembic.runtime.migration] Running upgrade 6dcb43972bdc -> 77e83833755c, add_app_config_retriever_resource
INFO  [alembic.runtime.migration] Running upgrade 77e83833755c -> 6e2cfb077b04, add_dataset_collection_binding
INFO  [alembic.runtime.migration] Running upgrade 6e2cfb077b04 -> ab23c11305d4, add dataset query variable at app model configs.
INFO  [alembic.runtime.migration] Running upgrade ab23c11305d4 -> 2e9819ca5b28, add_tenant_id_in_api_token
INFO  [alembic.runtime.migration] Running upgrade 2e9819ca5b28 -> b3a09c049e8e, add advanced prompt templates
INFO  [alembic.runtime.migration] Running upgrade b3a09c049e8e -> 968fff4c0ab9, add_api_based_extension
INFO  [alembic.runtime.migration] Running upgrade 968fff4c0ab9 -> a9836e3baeee, add external_data_tools in app model config
INFO  [alembic.runtime.migration] Running upgrade a9836e3baeee -> 8fe468ba0ca5, add gpt4v supports
INFO  [alembic.runtime.migration] Running upgrade 8fe468ba0ca5 -> fca025d3b60f, add-dataset-retrival-model
INFO  [alembic.runtime.migration] Running upgrade fca025d3b60f -> e1901f623fd0, add-annotation-reply
INFO  [alembic.runtime.migration] Running upgrade e1901f623fd0 -> 46976cc39132, add-annotation-histoiry-score
INFO  [alembic.runtime.migration] Running upgrade 46976cc39132 -> f2a6fc85e260, add_anntation_history_message_id
INFO  [alembic.runtime.migration] Running upgrade f2a6fc85e260 -> 714aafe25d39, add_anntation_history_match_response
INFO  [alembic.runtime.migration] Running upgrade 714aafe25d39 -> 246ba09cbbdb, add_app_anntation_setting
INFO  [alembic.runtime.migration] Running upgrade 246ba09cbbdb -> 88072f0caa04, add custom config in tenant
INFO  [alembic.runtime.migration] Running upgrade 88072f0caa04 -> 187385f442fc, modify provider model name length
INFO  [alembic.runtime.migration] Running upgrade 187385f442fc -> 89c7899ca936, empty message
INFO  [alembic.runtime.migration] Running upgrade 89c7899ca936 -> 3ef9b2b6bee6, add_assistant_app
INFO  [alembic.runtime.migration] Running upgrade 3ef9b2b6bee6 -> ad472b61a054, add api provider icon
INFO  [alembic.runtime.migration] Running upgrade ad472b61a054 -> 8ec536f3c800, rename api provider credentials
INFO  [alembic.runtime.migration] Running upgrade 8ec536f3c800 -> 00bacef91f18, rename api provider description
INFO  [alembic.runtime.migration] Running upgrade 00bacef91f18 -> f25003750af4, add created/updated at
INFO  [alembic.runtime.migration] Running upgrade f25003750af4 -> c71211c8f604, add tool_invoke_model_log
INFO  [alembic.runtime.migration] Running upgrade c71211c8f604 -> 114eed84c228, remove tool id from model invoke
INFO  [alembic.runtime.migration] Running upgrade 114eed84c228 -> 4829e54d2fee, change message chain id to nullable
INFO  [alembic.runtime.migration] Running upgrade 4829e54d2fee -> 053da0c1d756, add api tool privacy
INFO  [alembic.runtime.migration] Running upgrade 053da0c1d756 -> 4823da1d26cf, add tool file
INFO  [alembic.runtime.migration] Running upgrade 4823da1d26cf -> 9fafbd60eca1, add message file belongs to
INFO  [alembic.runtime.migration] Running upgrade 9fafbd60eca1 -> 8ae9bc661daa, add tool conversation variables idx
INFO  [alembic.runtime.migration] Running upgrade 8ae9bc661daa -> 23db93619b9d, add message files into agent thought
INFO  [alembic.runtime.migration] Running upgrade 23db93619b9d -> de95f5c77138, migration serpapi_api_key
INFO  [alembic.runtime.migration] Running upgrade de95f5c77138 -> b24be59fbb04, empty message
INFO  [alembic.runtime.migration] Running upgrade b24be59fbb04 -> dfb3b7f477da, add-tool-index
INFO  [alembic.runtime.migration] Running upgrade dfb3b7f477da -> 380c6aa5a70d, add tool labels to agent thought
INFO  [alembic.runtime.migration] Running upgrade 380c6aa5a70d -> 16830a790f0f, empty message
INFO  [alembic.runtime.migration] Running upgrade 16830a790f0f -> a8f9b3c45e4a, add_tenant_id_db_index
INFO  [alembic.runtime.migration] Running upgrade a8f9b3c45e4a -> 17b5ab037c40, add-keyworg-table-storage-type
INFO  [alembic.runtime.migration] Running upgrade 17b5ab037c40 -> a8d7385a7b66, add-embeddings-provider-name
INFO  [alembic.runtime.migration] Running upgrade a8d7385a7b66 -> b289e2408ee2, add workflow
INFO  [alembic.runtime.migration] Running upgrade b289e2408ee2 -> cc04d0998d4d, set model config column nullable
INFO  [alembic.runtime.migration] Running upgrade cc04d0998d4d -> f9107f83abab, add desc for apps
INFO  [alembic.runtime.migration] Running upgrade f9107f83abab -> 42e85ed5564d, conversation columns set nullable
INFO  [alembic.runtime.migration] Running upgrade 42e85ed5564d -> b5429b71023c, messages columns set nullable
INFO  [alembic.runtime.migration] Running upgrade b5429b71023c -> 563cf8bf777b, enable tool file without conversation id
INFO  [alembic.runtime.migration] Running upgrade 563cf8bf777b -> e2eacc9a1b63, add status for message
INFO  [alembic.runtime.migration] Running upgrade e2eacc9a1b63 -> c3311b089690, add tool meta
INFO  [alembic.runtime.migration] Running upgrade c3311b089690 -> 3c7cac9521c6, add-tags-and-binding-table
INFO  [alembic.runtime.migration] Running upgrade 3c7cac9521c6 -> 47cc7df8c4f3, modify default model name length
INFO  [alembic.runtime.migration] Running upgrade 47cc7df8c4f3 -> 5fda94355fce, Custom Disclaimer
INFO  [alembic.runtime.migration] Running upgrade 5fda94355fce -> 7bdef072e63a, add workflow tool
INFO  [alembic.runtime.migration] Running upgrade 7bdef072e63a -> 3b18fea55204, add tool label bings
INFO  [alembic.runtime.migration] Running upgrade 3b18fea55204 -> 9e98fbaffb88, add workflow tool version
INFO  [alembic.runtime.migration] Running upgrade 9e98fbaffb88 -> 03f98355ba0e, add workflow tool label and tool bindings idx
INFO  [alembic.runtime.migration] Running upgrade 03f98355ba0e -> 64a70a7aab8b, add workflow run index
INFO  [alembic.runtime.migration] Running upgrade 64a70a7aab8b -> 4e99a8df00ff, add load balancing
INFO  [alembic.runtime.migration] Running upgrade 4e99a8df00ff -> 7b45942e39bb, add-api-key-auth-binding
INFO  [alembic.runtime.migration] Running upgrade 7b45942e39bb -> 4ff534e1eb11, add workflow to site
INFO  [alembic.runtime.migration] Running upgrade 4ff534e1eb11 -> b69ca54b9208, add chatbot color theme
INFO  [alembic.runtime.migration] Running upgrade 4ff534e1eb11 -> 04c602f5dc9b, update AppModelConfig and add table TracingAppConfig
INFO  [alembic.runtime.migration] Running upgrade 04c602f5dc9b -> c031d46af369, remove app model config trace config and rename trace app config
INFO  [alembic.runtime.migration] Running upgrade c031d46af369 -> 2a3aebbbf4bb, add app tracing
INFO  [alembic.runtime.migration] Running upgrade 2a3aebbbf4bb, b69ca54b9208 -> 63f9175e515b, merge branches
INFO  [alembic.runtime.migration] Running upgrade 63f9175e515b -> b2602e131636, add workflow_run_id index for message
INFO  [alembic.runtime.migration] Running upgrade b2602e131636 -> 7e6a8693e07a, add table dataset_permissions
INFO  [alembic.runtime.migration] Running upgrade 7e6a8693e07a -> 161cadc1af8d, add dataset permission tenant id
INFO  [alembic.runtime.migration] Running upgrade 161cadc1af8d -> 408176b91ad3, 'add_max_active_requests'
INFO  [alembic.runtime.migration] Running upgrade 408176b91ad3 -> fecff1c3da27, remove extra tracing app config table and add idx_dataset_permissions_tenant_id
INFO  [alembic.runtime.migration] Running upgrade fecff1c3da27 -> 6e957a32015b, add-embedding-cache-created_at_index
INFO  [alembic.runtime.migration] Running upgrade 6e957a32015b -> 8e5588e6412e, add environment variable to workflow model
INFO  [alembic.runtime.migration] Running upgrade 8e5588e6412e -> 53bf8af60645, update model
INFO  [alembic.runtime.migration] Running upgrade 53bf8af60645 -> eeb2e349e6ac, increase max model_name length

**Comment by lizhanyang505** [comment]
tail -f ../logs/flask.log 
/opt/data1/app/anaconda3/envs/py3.10_tfm/lib/python3.10/site-packages/gevent/os.py:426: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = fork()
2024-08-10 05:40:45,671.671 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set
 * Debug mode: on
2024-08-10 05:40:46,047.047 INFO [MainThread] [_internal.py:97] - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.12.76:5001
2024-08-10 05:40:46,047.047 INFO [MainThread] [_internal.py:97] - Press CTRL+C to quit
2024-08-10 05:40:46,048.048 INFO [MainThread] [_internal.py:97] -  * Restarting with stat
/opt/data1/app/anaconda3/envs/py3.10_tfm/lib/python3.10/site-packages/gevent/os.py:426: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = fork()
/opt/data1/app/anaconda3/envs/py3.10_tfm/lib/python3.10/site-packages/gevent/os.py:426: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = fork()
2024-08-10 05:40:55,062.062 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set
2024-08-10 05:40:55,440.440 WARNING [MainThread] [_internal.py:97] -  * Debugger is active!
2024-08-10 05:40:55,440.440 INFO [MainThread] [_internal.py:97] -  * Debugger PIN: 628-286-20

**Comment by lizhanyang505** [comment]
tail -f ../logs/celery.log 
/opt/data1/app/anaconda3/envs/py3.10_tfm/lib/python3.10/site-packages/gevent/os.py:426: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = fork()
2024-08-10 05:41:55,837.837 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set
/opt/data1/app/anaconda3/envs/py3.10_tfm/lib/python3.10/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2024-08-10 05:41:56,547: WARNING/MainProcess] /opt/data1/app/anaconda3/envs/py3.10_tfm/lib/python3.10/site-packages/gevent/os.py:426: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = fork()

 
 -------------- celery@a-Super-Server v5.3.6 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.5.0-44-generic-x86_64-with-glibc2.35 2024-08-10 05:41:56
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         app:0x76e87757cd00
- ** ---------- .> transport:   redis://:**@localhost:6379/1
- ** ---------- .> results:     postgresql://postgres:**@localhost:5432/dify
- *** --- * --- .> concurrency: 64 (solo)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> dataset          exchange=dataset(direct) key=dataset
                .> generation       exchange=generation(direct) key=generation
                .> mail             exchange=mail(direct) key=mail
                .> ops_trace        exchange=ops_trace(direct) key=ops_trace

[tasks]
  . schedule.clean_embedding_cache_task.clean_embedding_cache_task
  . schedule.clean_unused_datasets_task.clean_unused_datasets_task
  . tasks.add_document_to_index_task.add_document_to_index_task
  . tasks.annotation.add_annotation_to_index_task.add_annotation_to_index_task
  . tasks.annotation.batch_import_annotations_task.batch_import_annotations_task
  . tasks.annotation.delete_annotation_index_task.delete_annotation_index_task
  . tasks.annotation.disable_annotation_reply_task.disable_annotation_reply_task
  . tasks.annotation.enable_annotation_reply_task.enable_annotation_reply_task
  . tasks.annotation.update_annotation_to_index_task.update_annotation_to_index_task
  . tasks.batch_create_segment_to_index_task.batch_create_segment_to_index_task
  . tasks.clean_dataset_task.clean_dataset_task
  . tasks.clean_document_task.clean_document_task
  . tasks.clean_notion_document_task.clean_notion_document_task
  . tasks.deal_dataset_vector_index_task.deal_dataset_vector_index_task
  . tasks.delete_segment_from_index_task.delete_segment_from_index_task
  . tasks.disable_segment_from_index_task.disable_segment_from_index_task
  . tasks.document_indexing_sync_task.document_indexing_sync_task
  . tasks.document_indexing_task.document_indexing_task
  . tasks.document_indexing_update_task.document_indexing_update_task
  . tasks.duplicate_document_indexing_task.duplicate_document_indexing_task
  . tasks.enable_segment_to_index_task.enable_segment_to_index_task
  . tasks.mail_invite_member_task.send_invite_member_mail_task
  . tasks.mail_reset_password_task.send_reset_password_mail_task
  . tasks.ops_trace_task.process_trace_tasks
  . tasks.recover_document_indexing_task.recover_document_indexing_task
  . tasks.remove_app_and_related_data_task.remove_app_and_related_data_task
  . tasks.remove_document_from_index_task.remove_document_from_index_task
  . tasks.retry_document_indexing_task.retry_document_indexing_task
  . tasks.sync_website_document_indexing_task.sync_website_document_indexing_task

[2024-08-10 05:41:56,581: INFO/MainProcess] Connected to redis://:**@localhost:6379/1

**Comment by crazywoola** [comment]
You need to set the frontend environments as well. https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/local-source-code Please read this through before you start.

**Comment by discovery219** [comment]
I have the same question, still don't know how fix, when debugging install page using developer tools in Firefox, there are JavaScript errors in the console. Could this be due to a mirroring issue?
![20240903174610](https://github.com/user-attachments/assets/d877ea9b-28a4-480d-96b3-30b3342c9e7e)
