### ISSUE TITLE
Chat Enhance Edit and Retry/Regenerate button

### ISSUE THREAD

**Issue by alterxyz** [langgenius/dify#7161]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Sometimes I am not satisfied with the AI's response, and I want to modify my message or regenerate it to give it a second chance. However, there are no such options that allow me to do so.

### 2. Additional context or comments

![image](https://github.com/user-attachments/assets/e30ee5d5-4ecd-4706-bc9c-9f635649c06d)
Here is a screenshot with my handcrafted mockup icons showing where and what it would look like.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
@xuzuodong
