### ISSUE TITLE
Issue with Setting Up Admin Account: Long Loading Time without Success #4553

### ISSUE THREAD

**Issue by lizhanyang505** [langgenius/dify#7163]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

issuse #4553 can't help.

**Comment by lizhanyang505** [comment]
![image](https://github.com/user-attachments/assets/a00bd703-59cc-481e-9399-44cb54e03e7c)

**Comment by lizhanyang505** [comment]
CONSOLE_API_URL: The backend URL of the console API.  
CONSOLE_WEB_URL: The front-end URL of the console web.
SERVICE_API_URL: Service API URL.
APP_API_URL: WebApp API backend URL.
APP_WEB_URL: WebApp URL.

**Comment by lizhanyang505** [comment]
![image](https://github.com/user-attachments/assets/2d2ddaf8-4022-4691-94d1-8f413e109bb2)
If you install the official configuration for local startup, please ask how to change the above configuration. The following are the docker ports and processes after startup. For example, the local IP is: 192.168.11.66

**Comment by lizhanyang505** [comment]
Tried, but failed, the answer you gave is wrong!

**Comment by crazywoola** [comment]
Duplicated

**Comment by crazywoola** [comment]
First of all, you need to paste the environment settings instead of a picture. It's not helpful at all. 
And you are trying to access localhost:5001 from your picture, which is definitely wrong. 

```
CONSOLE_API_URL: The backend URL of the console API.
CONSOLE_WEB_URL: The front-end URL of the console web.
SERVICE_API_URL: Service API URL.
APP_API_URL: WebApp API backend URL.
APP_WEB_URL: WebApp URL.
```

The bot's answer is correct. Those variables are located in .env.example, which is documented in our readme.

If you can not read the docs https://github.com/langgenius/dify/blob/4ae4895ebeb6f267ee660121d42e61810e04699f/web/README.md, please do not use the source to start the application for god's sake.

**Comment by lizhanyang505** [comment]
@crazywoola  docker/.env # Environment Variables for API service & worker
# ------------------------------

# ------------------------------
# Common Variables
# ------------------------------

# The backend URL of the console API,
# used to concatenate the authorization callback.
# If empty, it is the same domain.
# Example: https://api.console.dify.ai
CONSOLE_API_URL=http://192.168.12.76:5001/console/api

# The front-end URL of the console web,
# used to concatenate some front-end addresses and for CORS configuration use.
# If empty, it is the same domain.
# Example: https://console.dify.ai
CONSOLE_WEB_URL=http://192.168.12.76:5001/console

# Service API Url,
# used to display Service API Base Url to the front-end.
# If empty, it is the same domain.
# Example: https://api.dify.ai
SERVICE_API_URL=http://192.168.12.76:5001/service/api

# WebApp API backend Url,
# used to declare the back-end URL for the front-end API.
# If empty, it is the same domain.
# Example: https://api.app.dify.ai
APP_API_URL=http://192.168.12.76:5001/app/api

# WebApp Url,
# used to display WebAPP API Base Url to the front-end.
# If empty, it is the same domain.
# Example: https://app.dify.ai
APP_WEB_URL=http://192.168.12.76:5001

# File preview or download Url prefix.
# used to display File preview or download Url to the front-end or as Multi-model inputs;
# Url is signed and has expiration time.
FILES_URL=

**Comment by crazywoola** [comment]
As a programmer, you should learn how to format your code.

You are using `Self Hosted (Source)` to start the application, please read the documents, you shouldn't set .env  in this directory `docker/.env ` instead you should set them accordingly in their own directory, `api` & `web`.
