### ISSUE TITLE
Hope to add support for the hunyuan-vision and Spark Pro 128K two models

### ISSUE THREAD

**Issue by qidianlinjin1990** [langgenius/dify#7165]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hope to add support for the hunyuan-vision and Spark Pro 128K two models

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by laipz8200** [comment]
Hello! Welcome to contributing to this feature. You can find [here](https://docs.dify.ai/guides/model-configuration/predefined-model) how to integrate a new model.

**Comment by qidianlinjin1990** [comment]
I'm just an ordinary user, made a wrong choice, not very good at these things. 🥹 I just hope to add these two models, thank you.

**Comment by muzea** [comment]
Spark Pro 128K is already supported in #8078.


I want to add support for hunyuan-vision, but there are some problem I don't quite understand.

[In the introduction of the document](https://cloud.tencent.com/document/product/1729/104753), hunyuan-vision is a multimodal model. In dify, should it be classified as LLM?

**Comment by laipz8200** [comment]
A normal LLM supports vision by getting image inputs and then returning text outputs.

**Comment by muzea** [comment]
Hi, can you please check if this PR #8529 is OK?
@laipz8200
