### ISSUE TITLE
Sporadic Failure When Sending Request to Dify API

### ISSUE THREAD

**Issue by ottoradiologia** [langgenius/dify#7166]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Steps to reproduce:

Initiate a request to the Dify API.
Monitor the steps executed in the tracking console.
Observe the sporadic failure in certain requests.

### ✔️ Expected Behavior

The request should be processed correctly, with all steps completed without showing any errors.

### ❌ Actual Behavior

In some cases, the request fails, returning an error. I have attached an example of a failure and a success for comparison.

![image](https://github.com/user-attachments/assets/0d364312-cde6-4945-9149-b278701bfb76)
![image](https://github.com/user-attachments/assets/7eebe43d-ca77-47b3-b82b-8b67aadb7b4b)

**Comment by crazywoola** [comment]
What LLM did you use in this picture?

**Comment by ottoradiologia** [comment]
Hi! Sonnet 3.5 direct from Anthropic.
