### ISSUE TITLE
How to set ENV?

### ISSUE THREAD

**Issue by Leonard-Li777** [langgenius/dify#7172]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Whether I set.env in the api directory or the docker directory, the configuration does not take effect

docker compose down
docker compose up -d

![1723395548256_d](https://github.com/user-attachments/assets/8f4b839c-b2e0-4c45-9afb-a732b4f261f7)
![1723395599486_d](https://github.com/user-attachments/assets/4eb9eef6-5121-4cda-97f4-d5d13c8b3792)
![1723395791080_d](https://github.com/user-attachments/assets/d59346b1-ead2-43f2-8344-f1a9336b9644)

**Comment by Leonard-Li777** [comment]
我的问题任然没有解决！我就是按照这个方式去做的，但是没有生效的，我的截图已经说明情况了！

**Comment by crazywoola** [comment]
Your image doesn't give any useful information, the API environment variables you modify won't work for Docker, and if you follow the documentation, your environment variables won't have just 4 lines. And you didn't say what you were going to do with the environment variables

**Comment by Leonard-Li777** [comment]
Environment variables As I understand it, the ones that are not set will use the default value, right? I just want to set the maximum workflow execution time to 1 hour instead of the current 20 minutes, and it doesn't actually work whether I set the .env file in docker or the .env file in api

> Your image doesn't give any useful information, the API environment variables you modify won't work for Docker, and if you follow the documentation, your environment variables won't have just 4 lines. And you didn't say what you were going to do with the environment variables
