### ISSUE TITLE
Environment Variables about `MILVUS_DATABASE` has no document

### ISSUE THREAD

**Issue by lordk911** [langgenius/dify#7180]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

If we do not specify the MILVUS_DATABASE environment variable, milvus' default DATABASE will be used, which is not easy to manage.
Changing `MILVUS_DATABASE` after this will result in an error: the corresponding collection cannot be found in the corresponding database: 

`RPC error: [insert_rows], <DescribeCollectionException: (code=100, message=can't find collection[database=dify][collection=Vector_index_76b027c1_9d46_403f_af38_d8a1a976b899_Node])>`

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/c436454cd45d208c2494556d1d21311aaaaa3494/api/configs/middleware/vdb/milvus_config.py#L1-L40

These are required if you are setting the milvus vector db.

**Comment by lordk911** [comment]
> https://github.com/langgenius/dify/blob/c436454cd45d208c2494556d1d21311aaaaa3494/api/configs/middleware/vdb/milvus_config.py#L1-L40
> 
> These are required if you are setting the milvus vector db.

What I means is this no document about this Environment Variables: 
https://docs.dify.ai/getting-started/install-self-hosted/environments

**Comment by crazywoola** [comment]
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/861b5edb-93bb-44a8-bb17-26fbabdf819b">

**Comment by lordk911** [comment]
![475fee8e-f5b0-4e01-ba44-a362c8c349cd](https://github.com/user-attachments/assets/fbd85bfd-cece-4a3f-b8df-592a38a8d0de)
