### ISSUE TITLE
Unable to turn off "Citations and Attribution"

### ISSUE THREAD

**Issue by hackingchen** [langgenius/dify#7188]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1742" alt="微信图片_20240812153557" src="https://github.com/user-attachments/assets/9ddeab32-f294-4ab3-ada5-375e250cb289">

### ✔️ Expected Behavior

The feature is not enabled, but citations appear in all related responses
![image](https://github.com/user-attachments/assets/c9ca506a-5d97-46fc-8a62-7fb509bf11f7)

**Comment by crazywoola** [comment]
The function will be disabled for the new conversation.

**Comment by hackingchen** [comment]
No success.
![image](https://github.com/user-attachments/assets/0fef2e54-8ff7-4c9f-897f-72d959037dc2)


> @hackingchen Hello there! 👋 I'm here to help you with bug fixes, answer questions, and guide you to become a contributor. Let's squash those bugs together!你好啊！👋我在这里帮助你修复错误，回答问题，并指导你成为贡献者。我们一起把虫子踩扁！
> 
> To disable the "Citations and Attribution" feature in Dify version 0.6.16 when using the self-hosted version with Docker, you need to edit the environment variable values in your `.env` file. Specifically, you should set the `ENABLE_ATTRIBUTION` variable to `false`.要在Dify 0.6.16版本中禁用“引用和归属”功能，当使用Docker的自托管版本时，您需要编辑`.env`文件中的环境变量值。具体来说，您应该将`ENABLE_ATTRIBUTION`变量设置为`false`。
> 
> Here are the steps: 以下是步骤：
> 
> 1. Navigate to the `dify/docker` directory in your Dify source code.导航到Dify源代码中的`dify/docker`目录。
> 2. Open the `.env` file for editing.打开`.env`文件进行编辑。
> 3. Add or modify the following line:
>    添加或修改以下行：```dotenv
>    ENABLE_ATTRIBUTION=false
>    ```
> 4. Save the `.env` file.保存`.env`文件。
> 5. Restart Dify with the following commands:
>    使用以下命令重新启动Dify：```shell
>    docker compose down
>    docker compose up -d
>    ```
> 
> This will disable the "Citations and Attribution" feature in your Dify instance [[1]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/docker-compose.md).这将禁用Dify实例中的“引用和归属”功能[[1]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/docker-compose.md)。
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu.要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_

**Comment by crazywoola** [comment]
This is documented in our official docs https://docs.dify.ai/guides/knowledge-base/retrieval-test-and-citation#id-2.-citation-and-attribution. Please make sure you have read the docs before opening a question here.
