### ISSUE TITLE
Support pg_vector full text search 

### ISSUE THREAD

**Issue by jasonkang14** [langgenius/dify#7190]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I noticed that Dify currently does not support pg_vector for full-text search. However, with the release of [pg_vector version 0.7](https://github.com/pgvector/pgvector/issues/508) in late April, support for sparse vectors has been introduced.

I would like to inquire if you would be open to accepting a pull request that integrates this functionality into Dify.

Thank you for considering this enhancement. I look forward to your thoughts.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Appreciate if you can submit a pr for this feature.
