### ISSUE TITLE
api /messages/{message_id}/suggested throw "Message Not Exists." error 

### ISSUE THREAD

**Issue by Lyeluo** [langgenius/dify#7192]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

after a chat work flow ,use suggested api. i get error "Message Not Exists." i sure my message_id is exits and user is right . 
![image](https://github.com/user-attachments/assets/853a8ae1-118e-4831-9cb8-a46ff91d77f3)

### ✔️ Expected Behavior

get some suggested by api 

### ❌ Actual Behavior

{
    "code": "bad_request",
    "message": "Message Not Exists.",
    "status": 400
}

**Comment by crazywoola** [comment]
```
        except services.errors.message.MessageNotExistsError:
            raise NotFound("Message Not Exists.")
        except SuggestedQuestionsAfterAnswerDisabledError:
            raise BadRequest("Message Not Exists.")
```

According to this implementation, I think you need to turn on the function in your application and publish it.
