### ISSUE TITLE
Add Interactive User Node to Workflow for Confirmation and Feedback

### ISSUE THREAD

**Issue by tonyzaizai** [langgenius/dify#7193]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In our current workflow system, there are critical points where user confirmation or feedback is essential to ensure accuracy and increase the success rate of important processes. However, the existing workflow nodes do not provide a mechanism for direct interaction with users during execution. This limitation can lead to errors or missed opportunities for improvement. By introducing a node type that allows for user interaction, we can gather confirmations, suggestions, or other inputs from users at key stages, ultimately enhancing the workflow’s effectiveness and reducing the risk of errors.

similar to the "Q&A" node in the Coze platform

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by xjose97x** [comment]
why was this issue closed?

**Comment by shutcode** [comment]
because of circular reference with #7202

> why was this issue closed?
