### ISSUE TITLE
No success.

### ISSUE THREAD

**Issue by hackingchen** [langgenius/dify#7195]
No success.
![image](https://github.com/user-attachments/assets/0fef2e54-8ff7-4c9f-897f-72d959037dc2)

_Originally posted by @hackingchen in https://github.com/langgenius/dify/issues/7188#issuecomment-2283408374_

**Comment by crazywoola** [comment]
It is not added in the environment variables, but added here. Please do not modify the template when submitting an issue.

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/7b280df8-cb24-4c38-8817-d09c655fd3c1">
