### ISSUE TITLE
在dify.ai上创建了一个项目，并设置了自己的API，但似乎还是在使用你们的api...不知道应该去哪里设置？

### ISSUE THREAD

**Issue by freetosmash** [langgenius/dify#72]
如题，感谢

**Comment by takatost** [comment]
你好，在右上角头像设置中

**Comment by ares0x** [comment]
<img width="824" alt="image" src="https://github.com/langgenius/dify/assets/53114112/89da9e0a-ca97-4758-a24e-b76b336d1701">
点击 api 密钥即可创建

> 如题，感谢

**Comment by takatost** [comment]
> <img alt="image" width="824" src="https://user-images.githubusercontent.com/53114112/238914956-89da9e0a-ca97-4758-a24e-b76b336d1701.png"> 点击 api 密钥即可创建
> > 如题，感谢

我觉得应该是在说 OpenAI API-Key 吧

**Comment by freetosmash** [comment]
> > <img alt="image" width="824" src="https://user-images.githubusercontent.com/53114112/238914956-89da9e0a-ca97-4758-a24e-b76b336d1701.png"> 点击 api 密钥即可创建
> > > 如题，感谢
> 
> 我觉得应该是在说 OpenAI API-Key 吧

的确，您说得没错。事实上我遇到了两个问题：
1，Azure的API设置完，保存之后并没有看到这个API
2，Openai api设置完后，依然还在用Dify 提供的免费api ……不确定应该从哪里启用自己的Openai api

感谢🙏

**Comment by takatost** [comment]
1. azure 暂未支持。
2. 在右上角头像 -> 设置 -> 模型提供商

**Comment by freetosmash** [comment]
> * azure 暂未支持。
> * 在右上角头像 -> 设置 -> 模型提供商

感谢
搞定

**Comment by joshzhong66** [comment]
> > <img alt="图像" width="824" src="https://user-images.githubusercontent.com/53114112/238914956-89da9e0a-ca97-4758-a24e-b76b336d1701.png">点击 api 轴即可创建
> > > 如题，谢谢
> 
> 我觉得应该是在说 OpenAI API-Key 吧



> <img alt="图像" width="824" src="https://private-user-images.githubusercontent.com/53114112/238914956-89da9e0a-ca97-4758-a24e-b76b336d1701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTU3ODIsIm5iZiI6MTcxNDM1NTQ4MiwicGF0aCI6Ii81MzExNDExMi8yMzg5MTQ5NTYtODlkYTllMGEtY2E5Ny00NzU4LWEyNGUtYjc2YjMzNmQxNzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAxNTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTA3NjA2YWM1N2YzYjAxZDYyOTMzMmNlMzgxMzIyNjhhMDQwNzNhMjJlZDVmNmZjNjBlMzViZGI2MGQ1YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IoKqHIHqBo4vbVhoNd-IAqRgbHrESWeKgd_P3KeFkG0"> 点击 api 轴即可创建
> > 如题，谢谢

创建的api key如何保存使用呀

**Comment by JasonJasonzh** [comment]
添加embedding向量模型总是失败，不论是本地ollama的模型还是接入api全都失败，提示Failed to parse:http://weaviate:8080:80/v1/meta，有人遇到过这个问题吗

![Image](https://github.com/user-attachments/assets/c84c0f42-34da-4a67-8623-919bc75c18f4)
