### ISSUE TITLE
How to set ENV? （问题没有解决）

### ISSUE THREAD

**Issue by Leonard-Li777** [langgenius/dify#7201]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

我就是按照这个步骤操作的，但是没有生效，见截图
https://github.com/langgenius/dify/issues/7172

**Comment by crazywoola** [comment]
Please use the https://github.com/langgenius/dify/discussions for help, this template is meant for things needs to be changed in docs.
