### ISSUE TITLE
Load balancing cannot be configured by clicking on it, displaying gray disabled

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#7208]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Load balancing cannot be configured by clicking on it, displaying gray disabled
![image](https://github.com/user-attachments/assets/5cb6fc30-4b8c-4893-9ad1-e2afc2d7c76b)

**Comment by crazywoola** [comment]
This feature is SaaS and Enterprise only.
