### ISSUE TITLE
dify and VANNA.AI

### ISSUE THREAD

**Issue by renjiarui021020** [langgenius/dify#7217]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Node Vanna.AI run failed: Failed to invoke tool: 3 validation errors for ToolInvokeMessage message.str Input should be a valid string [type=string_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/string_type    message.bytes Input should be a valid bytes [type=bytes_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/bytes_type    message.dict[any,any] Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/dict_type
![4015f96d3c0eafe36661d07db905c3a](https://github.com/user-attachments/assets/021c3ff9-ca35-4537-8a5a-6980c96b52f1)
[新建 Text Document.txt](https://github.com/user-attachments/files/16595131/Text.Document.txt)

**Comment by renjiarui021020** [comment]
@dosu. I used your code but still got the same error

**Comment by renjiarui021020** [comment]
I am VANNA in the workflow Is there a problem with the configuration filled in by AI

**Comment by crazywoola** [comment]
I left a comment in #4878 , maybe @luxmus could help with this issue.

**Comment by renjiarui021020** [comment]
Thank you for your help, but I carefully read the article and did not find any mistakes on my part

**Comment by renjiarui021020** [comment]
@laipz8200 Thank you for your help. But I made the modifications according to your code, and still got the same error.

**Comment by WWei0728** [comment]
vanna的API key 填写无效报错，什么原因
