### ISSUE TITLE
Delete all URLs and email addresses option does not work when uploading Markdown documents

### ISSUE THREAD

**Issue by Menghuan1918** [langgenius/dify#7228]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Check Delete all URLs and email addresses option when uploading Markdown file
![图片](https://github.com/user-attachments/assets/b235db75-17eb-4ae9-8703-3282712742ab)
- Wait for the file to be processed and view the text

### ✔️ Expected Behavior

When the uploaded text is in txt format and the same preprocessing rules are used, the URL link is preserved
![图片](https://github.com/user-attachments/assets/c8ecb5cd-3014-491b-a4c3-520c0b5c78de)

### ❌ Actual Behavior

When the uploaded text was in md format and the same preprocessing rules were used, the URL links were all cleaned up
![图片](https://github.com/user-attachments/assets/594bf0a7-38ff-44af-84db-81f9ea74795c)

**Comment by devhero** [comment]
same issue with .doc files
