### ISSUE TITLE
Dify Version 0.6.16  fails to pass the API verification when calling the Xinference model.

### ISSUE THREAD

**Issue by lonnys** [langgenius/dify#7230]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Step1. Create Xinference API verification file：userauth.json
`{
    "auth_config": {
        "algorithm": "HS256",
        "secret_key": "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7",
        "token_expire_in_minutes": 30
    },
    "user_config": [
        {
            "username": "user1",
            "password": "secret1",
            "permissions": [
                "admin"
            ],
            "api_keys": [
                "sk-72tkvudyGLPMi",
                "sk-ZOTLIY4gt9w11"
            ]
        },
        {
            "username": "user2",
            "password": "secret2",
            "permissions": [
                "models:list",
                "models:read"
            ],
            "api_keys": [
                "sk-35tkasdyGLYMy",
                "sk-ALTbgl6ut981w"
            ]
        }
    ]
}`
Step2. Launch Xinference：xinference-local -H  0.0.0.0 -p 9997 --auth-config  userauth.json
Step3. Configure Dify
<img width="1087" alt="image" src="https://github.com/user-attachments/assets/99e074ed-a0ec-4036-9159-27e3f069e2b8">

Other instructions: Xinference is running normally

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/4b180526-4f08-4d17-b6c5-0900a7c9121d">

### ✔️ Expected Behavior

Dify supports the verification of Xinference API key

### ❌ Actual Behavior

Dify failed to pass the verification and prompted the following error

Failed to get the model description, detail: Not authenticated

**Comment by lonnys** [comment]
1. **Yes, I configured and ran it according to this step.**
2. **But in the end, the API KEY still couldn't be verified.**
3. **And the API Key of xinference is working normally. The following are the test results.**

``` curl -H"Authorization: Bearer sk-72tkvudyGLPMi" http://10.8.148.133:9997/v1/models      OUTPUT: {"object":"list","data":[{"id":"bge-reranker","object":"model","created":0,"owned_by":"xinference","model_type":"rerank","address":"0.0.0.0:61848","accelerators":[],"type":"normal","model_name":"bge-reranker","language":["en","zh"],"model_revision":null,"replica":1}]}%```

**4. In addition, if the API KEY is not verified, the Dify container can access the Xinference endpoint**

**Comment by lonnys** [comment]
hello! Can anyone help me?

**Comment by ethan-fly** [comment]
I have fixed this issue. Please refer to #7369 for details.

This PR is currently open. You can temporarily disable Xinference's authentication by running the following command: `xinference-local -H 0.0.0.0 -p 9997`

**Comment by lonnys** [comment]
Great! Looking forward to the release of the next version!

**Comment by ethan-fly** [comment]
> Great! Looking forward to the release of the next version!

Yes, 0.7.1 was released just now!
Hope you enjoy it！

**Comment by crazywoola** [comment]
Fixed in 0.7.1
