### ISSUE TITLE
The sys.files attribute that cannot be retrieved in other nodes

### ISSUE THREAD

**Issue by wentaotang0** [langgenius/dify#7233]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello, I also encountered the same problem, I want to reference the sys.files variable in other nodes, but I can't get it, including llm (gpt4o with Visual recognition), is there another way to help me?

### 2. Additional context or comments

My scenario is that I need to feed the image and text input to the llm and output the text as input to the knowledge base

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by wentaotang0** [comment]
![Uploading 企业微信截图_52eb6f25-b7ed-484f-9ad7-0196eca165ce.png…]()

**Comment by wentaotang0** [comment]
![企业微信截图_c23392be-0ca3-49aa-b4d9-e82f3ccb522b](https://github.com/user-attachments/assets/7f8d711a-02dd-4d66-8e21-2b7aadeaf790)

**Comment by wentaotang0** [comment]
![企业微信截图_52eb6f25-b7ed-484f-9ad7-0196eca165ce](https://github.com/user-attachments/assets/4b0660ac-f158-44cb-97c4-c1905725d3c5)
![Uploading 企业微信截图_508d6298-cd48-4639-9be0-84c
![企业微信截图_c23392be-0ca3-49aa-b4d9-e82f3ccb522b](https://github.com/user-attachments/assets/49199157-036e-4558-b2e1-2d5766c88711)
7db6913c6.png…]()

**Comment by crazywoola** [comment]
Duplicated, it's not supported yet.

**Comment by wentaotang0** [comment]
> Duplicated, it's not supported yet.

Thank you for your reply. Do you have a schedule to support it? When is it expected to be online
