### ISSUE TITLE
In the model configuration, ollama is configured with three, but the filtered model only displays two.

### ISSUE THREAD

**Issue by lizhanyang505** [langgenius/dify#7237]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![img_v3_02dn_b5ad2e85-c81f-4df9-b2bd-ab2d796c33eg](https://github.com/user-attachments/assets/496b9521-3f9c-40ac-947a-fda6cef637e3)
![img_v3_02dn_57bd71cb-73e7-47f2-9e44-41d9fb5b9b8g](https://github.com/user-attachments/assets/07a3cc5f-4342-45dc-ae96-f7df2fd8a4b1)

**Comment by lizhanyang505** [comment]
I saw that the two model configurations "gemma2:27b" and "qwen2:72b" are not found in _position.yaml, but they can be retrieved. The following is the content in the configuration file
- deepseek-v2-chat
- qwen2-72b-instruct
- qwen2-57b-a14b-instruct
- qwen2-7b-instruct
- yi-1.5-34b-chat
- yi-1.5-9b-chat
- yi-1.5-6b-chat
- glm4-9B-chat
![image](https://github.com/user-attachments/assets/d4bdcf2b-b6ea-4dc5-b4d7-284f535169a4)

**Comment by lizhanyang505** [comment]
After waiting for about 5m, it was time to screen. Why is the delay relatively high?

**Comment by crazywoola** [comment]
I think Ollama is different from other llms, it doesn't use yaml to load things, instead it reads things from the database I think.

> After waiting for about 5m, it was time to screen. Why is the delay relatively high?

And I am not sure I have understand correctly, can you explain more on this?

I think this issue could be resolved by refresh the page?
