### ISSUE TITLE
Attempt to use xinference model failed

### ISSUE THREAD

**Issue by njzfw1024** [langgenius/dify#7245]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、dify deployed in docker
2、xinfernence doployed without docker, and use -H 0.0.0.0, and the port is opened
3、both dify and xinference setted in one machine
![1723599282415](https://github.com/user-attachments/assets/1b22819f-05be-437f-a484-659ca5b719de)

### ✔️ Expected Behavior

success loaded

### ❌ Actual Behavior

failed

**Comment by crazywoola** [comment]
Duplicated, please search existing issues to resolve this.
