### ISSUE TITLE
docker compose up -d failed

### ISSUE THREAD

**Issue by lastsong0328** [langgenius/dify#7246]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Linux VM-28-9-centos 3.10.0-1160.119.1.el7.x86_64
docker compose up -d failed：

docker --version
Docker version 26.1.4, build 5650f9b

### ✔️ Expected Behavior

app installed successfully

### ❌ Actual Behavior

[+] Running 20/28
 ✘ api Error          manifest for langgenius/dify-api:0.7.0 not found: manifest unknown: manifest unknown                             4.2s 
 ⠹ sandbox [⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀] Pulling                                                                                                       4.2s 
 ⠹ nginx [⣿⣿⣿⣿⣿⠀⠀] Pulling                                                                                                             4.2s 
 ⠹ ssrf_proxy [⣿⣿⣿]  70.3MB / 73.17MB Pulling                                                                                          4.2s 
 ✘ worker Error       context canceled                                                                                                 4.2s 
 ✘ web Error          context canceled                                                                                                 4.2s 
 ⠹ db [⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿] 89.66MB / 92.39MB Pulling

**Comment by crazywoola** [comment]
Please use tag v0.6.16, we haven't release v0.7.0 yet.

**Comment by lastsong0328** [comment]
how  to set the tag to v0.6.16?  i did this installation according with the doc in mainpage:
1. git clone  to  download src package to local linux host
2. cd docker
3. cp .env.example .env
4. docker compose up -d
