### ISSUE TITLE
Openai Model importing reported "Connection error"

### ISSUE THREAD

**Issue by awangB** [langgenius/dify#7253]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker-api-1 unable to connect www.openai.com and www.google.com
how to set proxy paragraph in docker file .env

**Comment by crazywoola** [comment]
This is a general network question. Please search existing issue.
