### ISSUE TITLE
WenXin ERNIE model does not support fuction calling

### ISSUE THREAD

**Issue by Devi1k** [langgenius/dify#7259]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

cloud

### Cloud or Self Hosted

Cloud

### Steps to reproduce

In the studio agent mode, configure the Wenxin model to conduct a tool invocation test with the query, "苹果最新的手机是什么" and display the results：[wenxin] Bad Request Error, function calling is not supported yet.

### ✔️ Expected Behavior

Call the Google search tool normally and return：

已使用
google_search
苹果最新的手机是 iPhone 15 Pro 和 iPhone 15 Pro Max。这两款手机在2023年发布，采用了新的钛金属中框，重量更轻，并且在摄像头方面进行了显著升级，主摄像头为4800万像素，支持2400万像素的超高默认分辨率。

如果你想了解更多详细信息，可以查看以下链接：

[苹果发布iPhone 15 Pro 和iPhone 15 Pro Max](https://www.apple.com.cn/newsroom/2023/09/apple-unveils-iphone-15-pro-and-iphone-15-pro-max/)
[苹果2023年新品汇总](https://www.sohu.com/a/741017051_222118)

### ❌ Actual Behavior

[wenxin] Bad Request Error, function calling is not supported yet.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/3e63abd3352832c0494a07a7660800672f5fd1bd/api/core/model_runtime/model_providers/openai/llm/gpt-3.5-turbo-16k-0613.yaml#L6-L9

If you are interested in contributing to this feature, you can open a pull request then.
