### ISSUE TITLE
Please support for an interface similar to OpenAI's multi-turn dialogue

### ISSUE THREAD

**Issue by bswaterb** [langgenius/dify#7261]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When calling OpenAI's Chat-Message API, you can pass session information using the "messages" parameter, allowing me to manually construct a historical context to include, such as:

```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-4o-mini",
     "messages": [{"role": "user", "content": "Here is the content"}, {"role": "assistant", "content": "OK"}, {"role": "user", "content": "what are we talking about?"}],
     "temperature": 0.7
   }'
```

However, in the external API interface or Workflow provided by Dify, it is not possible to complete tasks based on context provided externally; you can only initiate a conversation and maintain the context of that conversation through Dify itself.

Therefore, I request that Dify support an interface that allows users to construct their own historical context for conversation generation.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You should use Chatflow or Agent. Workflow is designed as a one-off task.
