### ISSUE TITLE
知识库文件上传后一直在排队中

### ISSUE THREAD

**Issue by Hemonn** [langgenius/dify#7263]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0fad0578-a3a2-4e03-bab3-c213382a4aee)

**Comment by chenGIEGIE** [comment]
I also encountered this problem, how to solve it?

**Comment by Hemonn** [comment]
您发给我的信件已经收到，阅读后回复您。This is an automatic reply, confirming that your e-mail was received. Thank you.
