### ISSUE TITLE
Unable to Access sys.files Variable in Custom Tool Initialization

### ISSUE THREAD

**Issue by ZZY19980203** [langgenius/dify#7264]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/user-attachments/assets/12487b60-ae18-4686-87f1-56691d5ea8c8)
![image](https://github.com/user-attachments/assets/af26e755-9c79-4f0f-a001-003be686195b)
I am trying to pass images received at the start into a custom tool for processing, but the tool is unable to access the sys.files property. If accessing the sys.files property is not possible, an alternative solution involving passing the image URLs to the custom tool would also work for my use case. Any guidance on how to achieve this would be appreciated.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/7260
