### ISSUE TITLE
arm64 docker image exception

### ISSUE THREAD

**Issue by CNWann** [langgenius/dify#727]
The dify-api and dify-web docker image on arm64 server unable to start normally, and an error is reported “exec /bin/bash: exec format error”, the same docker-compose.yml on x86 server is normally！

Docker version 23.0.3
Docker Compose version v2.17.2
langgenius/dify-api:0.3.12
langgenius/dify-web:0.3.12

![图片](https://github.com/langgenius/dify/assets/26641645/b11af55e-ea0c-4eb1-9913-f64f68b10a69)

**Comment by CNWann** [comment]
docker image inspect screenshot below:

langgenius/dify-api:0.3.12
![图片](https://github.com/langgenius/dify/assets/26641645/6058e94b-09d7-4dc3-8105-585b0bb6c234)
![图片](https://github.com/langgenius/dify/assets/26641645/a7a43efa-427b-4b7a-b829-a698a507b2e5)

langgenius/dify-web:0.3.12
![图片](https://github.com/langgenius/dify/assets/26641645/78fc94a4-9e16-4cbb-a962-d87d762f067a)
![图片](https://github.com/langgenius/dify/assets/26641645/21c504b6-ef4f-4878-b1aa-aefcf51328cd)

**Comment by CNWann** [comment]
I suspect that the base image compiled automatically is wrong. I found in the jobs log of actions that the base image used by the arm64 architecture is base:1.0.0-bullseye-slim. In dockerhub, this image shows that it does not support arm64

[https://github.com/langgenius/dify/actions/runs/5699779175/job/15449022919#step:7:277](url)


![图片](https://github.com/langgenius/dify/assets/26641645/bec6dc44-439d-4d7f-9784-88db5001fbb4)

![图片](https://github.com/langgenius/dify/assets/26641645/ef3665f7-63ed-4d1f-8a03-30dc7f96f127)

**Comment by takatost** [comment]
<img width="893" alt="image" src="https://github.com/langgenius/dify/assets/5485478/f7892c12-3ab5-4655-b4d0-5042b4025a88">
base image is also support arm64 platform.

**Comment by takatost** [comment]
Sorry about that. We might have forgotten to update the base image version after building it.
And first time building a web service arm64 image might take quite some time.

**Comment by takatost** [comment]
We've rebuilt a new image to support the arm64 architecture. You can try replacing the docker image tag for the api/worker/web services with `51554361fcfad028168280f5e0d3858cf126c545` and start it up.

**Comment by CNWann** [comment]
Thx, it's work normal.
