### ISSUE TITLE
A new system variable, `dialogue_count`, to record the number of conversation rounds.

### ISSUE THREAD

**Issue by laipz8200** [langgenius/dify#7278]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

To control the maximum number of rounds in the chat flow.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by zard1152** [comment]
HI, Why the dialogue_count is no effect, it's 0, I have tried to send 2 messages to chatbot, but the number keep at 0
![Image](https://github.com/user-attachments/assets/e729f22c-a861-4513-8fb8-e3b44f46bdbf)
