### ISSUE TITLE
sandbox execute python with Module not exist error

### ISSUE THREAD

**Issue by lzzzzzzzzz** [langgenius/dify#7288]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. add "python-docx" in python-requirements.txt , import error when select "python-docx"
![1723688220193](https://github.com/user-attachments/assets/4ced2965-fa57-474e-9798-59caf5079b93)

3. import error when select "python-docx"

### ✔️ Expected Behavior

1. when dependencies in requirements.txt not same as module name in python code, it can correct import
2. or it display correct module name list in python code node

**Comment by lzzzzzzzzz** [comment]
由于依赖名称与模块名称不一致导致的import 错误, 有什么办法可以临时将docx 依赖加到默认依赖中呢, 所有的依赖都是必须在python.so 文件中才可以正常导入么, sandbox的go源码很难理解

**Comment by nightzjp** [comment]
python-doc这个包，引入的时候是直接from docx import XX把。我看你的报错是import python-docx

**Comment by crazywoola** [comment]
See FAQ https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md

**Comment by lzzzzzzzzz** [comment]
> python-doc这个包，引入的时候是直接from docx import XX把。我看你的报错是import python-docx

依赖名称和模块名称不一样的, 勾选了高级依赖就会报错,不勾选就是module不存在, 页面勾选的高级依赖最终硬编码到py脚本中就是 import python-docx, 合理的应该是import docx

**Comment by mumugoah** [comment]
这个最好是能支持包名和模块名称分离

**Comment by nightzjp** [comment]
类似的功能我是这样实现的；
单独启一个web服务，在工作流中直接通过http接口的方式调用。感觉会更加灵活

**Comment by lzzzzzzzzz** [comment]
@dosu 这并不是因为pip install python-docx失败导致的, 实际上 pip install python-docx已经成功, 但是由于python-docx依赖的模块名称是docx, 所以导致代码节点运行错误,这个如何解决

**Comment by lzzzzzzzzz** [comment]
> See FAQ https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md

实际上是因为依赖是python-docx,但是模块名是docx 不一致导致的, 我按照机器人回复的, 重新构建了镜像, docx并没有作为默认依赖添加到每次运行的py脚本中

**Comment by NiXuebing** [comment]
@lzzzzzzzzz 
我这边使用的 beautifulsoup4，按照的依赖是 beautifulsoup4==4.12.3， Python 代码是 from bs4 import BeautifulSoup，
在 langgenius/dify-sandbox:0.2.1 下出现了相同的问题，镜像升的 0.2.4 可以使用了

**Comment by lzzzzzzzzz** [comment]
> @lzzzzzzzzz 我这边使用的 beautifulsoup4，按照的依赖是 beautifulsoup4==4.12.3， Python 代码是 from bs4 import BeautifulSoup， 在 langgenius/dify-sandbox:0.2.1 下出现了相同的问题，镜像升的 0.2.4 可以使用了

升级版本后可以了,就是还存在一个so缺失的问题,还是需要自己重新build镜像
