### ISSUE TITLE
After upgrade to latest docker image 0.7.0, Answer Node cannot reply files

### ISSUE THREAD

**Issue by cherry0411** [langgenius/dify#7294]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

A HTTP Node accept image URL which send GET request download the image as files output variable, then an Answer Node reference files variable, to write image to response, then I got this error: Node (Image Response) run failed: 'FileVar' object has no attribute 'markdown'.

Before I upgrade to latest version, should be 0.6.7, is working normally.

![issues_1](https://github.com/user-attachments/assets/fc5bd5f0-1ce3-498f-a99d-81b18319ab0b)

![issues_2](https://github.com/user-attachments/assets/4139b27a-2db1-45c3-b7f2-9134bb1255ec)

### ✔️ Expected Behavior

Answer Node should process files variable correctly, as previous version did.

### ❌ Actual Behavior

Node (Image Response) run failed: 'FileVar' object has no attribute 'markdown'.

**Comment by crazywoola** [comment]
Fixed in this PR https://github.com/langgenius/dify/pull/7293

**Comment by cherry0411** [comment]
thanks, is there any plan for a hotfix release?

**Comment by crazywoola** [comment]
Not yet, I have just merged that PR. We will see later, I have pinned this issue, you can keep an eye on this.

**Comment by 141qq** [comment]
stable diffusion也是同样问题
![9437ff30-e647-470e-9854-85ac472ca904](https://github.com/user-attachments/assets/930834fa-c164-4499-b01e-265d02004bc2)
![image](https://github.com/user-attachments/assets/0e13368b-91af-4eef-bde4-6cd421176568)
