### ISSUE TITLE
webapp not response

### ISSUE THREAD

**Issue by walkbird** [langgenius/dify#7295]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Select a workflow, enter the corresponding webapp page, input the content, and wait for the workflow to finish running.
2. In the initial testing, if the runtime exceeds 1 minute, such as 65 seconds, the results will not be displayed on the interface. However, if it finishes within 5 seconds, the results will be displayed normally.
3. Please refer to the screenshot I provided for detailed information. 

No Output
![no_output](https://github.com/user-attachments/assets/cc4423ce-6b42-4ef2-b353-b3c2bedabd10)

With Output
![with_output](https://github.com/user-attachments/assets/d8d3f7da-a682-467a-8ef6-c860edc75cdc)

[delay_output.yml.zip](https://github.com/user-attachments/files/16621800/delay_output.yml.zip)

### ✔️ Expected Behavior

Regardless of the duration, the results will return normally. Sometimes, the LLM may require more time to process.

### ❌ Actual Behavior

When the duration is approximately longer than 1 minute, the results will not be displayed.

**Comment by crazywoola** [comment]
This is a known issue, we have a limit of 60s in frontend. We will adjust it later. https://github.com/langgenius/dify/commit/a5fcd91ba5e669806672de54a3be62f0bb2eeea8

**Comment by libukai** [comment]
It's because of this reason, it has been bothering me for a long time, so many complex processes cannot be executed in this case. I hope for a quick adjustment.

**Comment by walkbird** [comment]
I temporarily resolved this issue by modifying the TEXT_GENERATION_TIMEOUT_MS configuration in the web/config/index.ts file and then rebuilding a Docker image. Maybe in the future, we could move the TEXT_GENERATION_TIMEOUT_MS parameter to the .env configuration?

Here is my modification:

```shell
dify % git diff
diff --git a/web/config/index.ts b/web/config/index.ts
index 6b0e551e3..084a6738d 100644
--- a/web/config/index.ts
+++ b/web/config/index.ts
@@ -246,4 +246,4 @@ Thought: {{agent_scratchpad}}

 export const VAR_REGEX = /\{\{(#[a-zA-Z0-9_-]{1,50}(\.[a-zA-Z_][a-zA-Z0-9_]{0,29}){1,10}#)\}\}/gi

-export const TEXT_GENERATION_TIMEOUT_MS = 60000
+export const TEXT_GENERATION_TIMEOUT_MS = 3600000
```

**Comment by libukai** [comment]
> This is a known issue, we have a limit of 60s in frontend. We will adjust it later. [a5fcd91](https://github.com/langgenius/dify/commit/a5fcd91ba5e669806672de54a3be62f0bb2eeea8)

Is there a specific version plan for the fix?

**Comment by shuai-huaman** [comment]
If it is a cloud service, how to modify this timeout period？
