### ISSUE TITLE
Add the input of system_dempt in the API: v1/chat-messages

### ISSUE THREAD

**Issue by njzfw1024** [langgenius/dify#7298]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need to customize roles during use

### 2. Additional context or comments

Attempt to add a system prompt key in the request field. If seted, overwrite the initialized prompt.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can achieve this by store system prompt in conversational variables, and set it later. https://docs.dify.ai/guides/workflow/node/variable-assignment
