### ISSUE TITLE
An error occurred when adding a new user

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#7299]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

An error occurred when adding a new user, the error message is as follows

Traceback (most recent call last):
  File "/app/api/tasks/mail_invite_member_task.py", line 40, in send_invite_member_mail_task
    mail.send(to=to, subject="立即加入 Dify 工作空间", html=html_content)
  File "/app/api/extensions/ext_mail.py", line 61, in send
    raise ValueError('mail from is not set')
ValueError: mail from is not set

**Comment by crazywoola** [comment]
See bot's reply.

**Comment by Oragold** [comment]
I still meet the same problem . I use QQ email but it still shows ' ValueError: mail from is not set' .
