### ISSUE TITLE
Questions when using Rerank of huggingface text-embeddings-inference

### ISSUE THREAD

**Issue by upskyy** [langgenius/dify#7310]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have a question about using **rerank** of huggingface text-embeddings-inference(TEI).
[text-embeddings-inference(TEI) repo](https://github.com/huggingface/text-embeddings-inference#using-re-rankers-models) uses `query(str)` and `texts(list of str)` as arguments when calling the server with curl, and the code uses `query` and `docs`. 
Is this compatible with text-embeddings-inference server?

https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/huggingface_tei/rerank/rerank.py#L21-L35

```bash
curl 127.0.0.1:8080/rerank \
    -X POST \
    -d '{"query":"What is Deep Learning?", "texts": ["Deep Learning is not...", "Deep learning is..."]}' \
    -H 'Content-Type: application/json'
```

**Comment by crazywoola** [comment]
@liuyanyi Could you take a look at this?

**Comment by liuyanyi** [comment]
Hi, the query and doc in L31~L35 are the parameter names used by the abstract methods in base_rerank_model of dify.

The code that actually calls TEI is located in tei_helper.py, and you can see that the actual request sent in the invoke_rerank method is correct

https://github.com/langgenius/dify/blob/c7df6783dffac516643038ad12633bd6ba45ff3f/api/core/model_runtime/model_providers/huggingface_tei/tei_helper.py#L176

**Comment by upskyy** [comment]
I have confirmed that TEI works well.
Thank you for checking.
