### ISSUE TITLE
VANNA.AI 

### ISSUE THREAD

**Issue by guhao17** [langgenius/dify#7311]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0348cef5-8584-4c90-94e9-8bf91eb08358)
![image](https://github.com/user-attachments/assets/2c6bd798-bc80-44a2-8772-d29b5c0f261e)
When I use the same configuration in my code, I can connect to the database. However, the same parameter configuration does not work in the Dify tool. What should I do?
![image](https://github.com/user-attachments/assets/29e3b954-d579-4103-ab77-fb1c9fa64425)

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/0348cef5-8584-4c90-94e9-8bf91eb08358)
![image](https://github.com/user-attachments/assets/2c6bd798-bc80-44a2-8772-d29b5c0f261e)
When I use the same configuration in my code, I can connect to the database. However, the same parameter configuration does not work in the Dify tool. What should I do?
![image](https://github.com/user-attachments/assets/29e3b954-d579-4103-ab77-fb1c9fa64425)

### ❌ Actual Behavior

11

**Comment by crazywoola** [comment]
> When I use the same configuration in my code, I can connect to the database. However, the same parameter configuration does not work in the Dify tool. What should I do?

You should not access the db via `127.0.01`. That's basically the same question as I ask what's your address, and you told me you told me localhost.
