### ISSUE TITLE
How to extract variables in the conversation starter?

### ISSUE THREAD

**Issue by shixud** [langgenius/dify#7319]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to display the user's name in the opening dialogue. This user name is set through an input value embedded in the website.
`window.difyChatbotConfig = {
  token: 'xxxx',
  baseUrl: 'https://xxxxx.com',
  inputs: {
    username: 'michael',
  }
}`
For example: "Hello, michael"

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
<img width="869" alt="image" src="https://github.com/user-attachments/assets/da665aef-ea8c-4a19-9e39-12c16c96d880">
