### ISSUE TITLE
【API Tools】new version not show api tools

### ISSUE THREAD

**Issue by kenneth-bro** [langgenius/dify#7321]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

upgrade new version, the web not show api tools, database existed.
![image](https://github.com/user-attachments/assets/819ace27-446e-4d17-b3a1-f75fedbe6a52)

### ✔️ Expected Behavior

show custom api tools

**Comment by crazywoola** [comment]
Fixed in v0.7.1
