### ISSUE TITLE
Ollama's embedding model api support error

### ISSUE THREAD

**Issue by i220319** [langgenius/dify#7322]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.70

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using Ollama's embedding model, your code should have hardcoded http://localhost:11434/api/embeddings instead of http://localhost:11434/api/embed. The correct endpoint is api/embeddings, not api/embed.

### ✔️ Expected Behavior

fix this bug

### ❌ Actual Behavior

wait for fixed

**Comment by crazywoola** [comment]
This is introduced in #6878

- https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings
- https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embedding

See their docs:

> Note: this endpoint has been superseded by /api/embed
```
POST /api/embeddings
```

**Comment by daocoder2** [comment]
This is a problem with the ollama API documentation.

I modified this code locally, and it works.

api/core/model_runtime/model_providers/ollama/text_embedding/text_embedding.py

```python
  endpoint_url = endpoint_url.replace("api/embed", "api/embeddings")
  # Make the request to the OpenAI API
  response = requests.post(
      endpoint_url, headers=headers, data=json.dumps(payload), timeout=(10, 300)
  )

  response.raise_for_status()  # Raise an exception for HTTP errors
  response_data = response.json()

  # Extract embeddings and used tokens from the response
  embeddings = response_data["embedding"]
```

**Comment by crazywoola** [comment]
You need to upgrade the Ollama client instead of doing this.
