### ISSUE TITLE
The toolConfig field must be defined when using toolUse and toolResult content blocks

### ISSUE THREAD

**Issue by fsatsuki** [langgenius/dify#7328]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I Use Amazon Bedrock and Claude3.5 Sonnet in the Agent. 

Agent uses 5 tools
- webscraperwebscraper
- codesimple_code
- timecurrent_time
- githubgithub_repositories
- firecrawlscrape
- googlegoogle_search

Some time Agent was failed because the above error will occur when switching from having a tool to without a tool after using the tool.
```
[bedrock] Error: ValidationException: The toolConfig field must be defined when using toolUse and toolResult content blocks.
```

This is log stream of Bedrock API on the Cloudwatch logs.
```
{
    "schemaType": "ModelInvocationLog",
    "schemaVersion": "1.0",
    "timestamp": "2024-08-16T00:10:39Z",
    "accountId": "account_id",
    "identity": {
        "arn": "arn:aws:sts::account_id:assumed-role/DifyOnAwsStack-ApiServiceTaskTaskRole06F87EBE-aaRvf0jNQata/34b83c25d18a449a88a67efd56d05b73"
    },
    "region": "us-west-2",
    "requestId": "50f42cca-5c85-499c-8957-d11761ed95cd",
    "operation": "ConverseStream",
    "modelId": "anthropic.claude-3-5-sonnet-20240620-v1:0",
    "errorCode": "ValidationException"
}
```

### ✔️ Expected Behavior

Amazon Bedrock Converse API was succeeded

### ❌ Actual Behavior

I got this error on the browser.
```
data: {"event": "error", "conversation_id": "a33d622c-9789-4549-8624-f1a0b55b05a2", "message_id": "e8c15ca2-2d84-49fd-844d-b3a2659a42ac", "created_at": 1723768034, "code": "completion_request_error", "status": 400, "message": "[bedrock] Error: ValidationException: The toolConfig field must be defined when using toolUse and toolResult content blocks."}
```

**Comment by JerrZhang** [comment]
Is this issue resolved?

**Comment by kangjianhua** [comment]
![image](https://github.com/user-attachments/assets/5b024a67-f2fc-432b-ad2b-b848e97e132b)
 I have encountered the same problem, please fix it as soon as possible, thank you！！！！

**Comment by lalalarabbit** [comment]
same problem and happens a lot

**Comment by laipz8200** [comment]
This issue is caused by the Agent exceeding the maximum limit of 5 tool calls. The same problem occurs with Anthropic's model. We're currently looking into how we can make adjustments.
