### ISSUE TITLE
 The workflow execution result does not output any content if executed through the runtime interface in the deployment. If the output content time exceeds 60 seconds, there is no content output. How can this be resolved?

### ISSUE THREAD

**Issue by bjev-xie** [langgenius/dify#7332]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The workflow execution result does not produce any output when executed through the runtime interface in the deployment. If the output content takes longer than 60 seconds, there is no content output. However, the content is output when using the debugging interface. My requirement is to have the content output normally through the runtime interface in the deployment.

### ✔️ Expected Behavior

 My requirement is to have the content output normally through the runtime interface in the deployment.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/6831

**Comment by bjev-xie** [comment]
hao to solve ?

**Comment by bjev-xie** [comment]
how to solve？
