### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by imdevopx** [langgenius/dify#7340]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create from Template > Patient Intake Chatbot > Click the newly created App > then this appears "Application error: a client-side exception has occurred"

### ✔️ Expected Behavior

like every created App able to see config/settings

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/b65d2a90-1591-49c6-b042-c4ac657b2477)

**Comment by crazywoola** [comment]
I have tried this but it's not reproducible.

**Comment by imdevopx** [comment]
hi @crazywoola i deleted and recreated the said App from template. and seems i am able to access it now.. thanks.

**Comment by imdevopx** [comment]
hi @crazywoola i have additional info.. the user run the said app from template a couple of times, maybe that triggers the error. but yeah i will monitor this. thanks

**Comment by Sakura4036** [comment]
Creating an application from a template may result in this error if the version of the dify `api` and `worker` is different from the dify `web` version!
