### ISSUE TITLE
Is it necessary to upload a file when creating a knowledge ?

### ISSUE THREAD

**Issue by wwuddan123** [langgenius/dify#7347]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I want to create knowledge, I must upload a local file first.
But, I just want to batch add chunks by local CSV file. So I hava to upload an empty file first.
Can I skip the first upload step?
Because my product environment is K8S and docker, which do not allow for persistent file mapping. 
Therefore, once I redeploy the container, the previously uploaded files will be lost. the knowledge will be disabled.
By the way, the workflows are not lost because they are save in database.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Actually you can create an empty dataset by API which contains nothing.

**Comment by wwuddan123** [comment]
> Actually you can create an empty dataset by API which contains nothing.

thanks.

Sure, but you said creating an emtpy dataset , not document. I want to create an empty document without a file.
With a document ID, I can proceed to batch create segments.

**Comment by wwuddan123** [comment]
> Actually you can create an empty dataset by API which contains nothing.

Could you develop a button to implement this API on web please?
API:  /datasets/{dataset_id}/document/create_by_text

![image](https://github.com/user-attachments/assets/19a01a34-3c22-4c63-9f4c-ce5aa39e7860)
