### ISSUE TITLE
Supports multi-version management

### ISSUE THREAD

**Issue by jiegod** [langgenius/dify#7350]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

<img width="1291" alt="image" src="https://github.com/user-attachments/assets/55b88a15-05fc-4bd1-9a98-c10b6b243b45">
I found that we had version stored in our workflow table but could not restore it to the specified version on the page. When can we support multiple versions of the arbitrary switch? This is multi-versioning

### 2. Additional context or comments

Hope you can support  multi-version management

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by wellCh4n** [comment]
Is this in project's roadmap? I've been using Dify for a little time, and sometimes I do need to rollback workflows after publish because of some cases.

**Comment by crazywoola** [comment]
I will close this, please see the newest one https://github.com/langgenius/dify/issues/7614.
This is already in our roadmap. @wellCh4n .However it's hard to guarantee the delivery time.
