### ISSUE TITLE
retry index after interruption

### ISSUE THREAD

**Issue by backlux** [langgenius/dify#7353]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

If indexing somehow got interrupted, it won't auto retry.  It's a huge dataset and there's no control from frontend to manually retry.
Retry seems to be controlled by background tasks, but when it's in a hurry and I do need a retry...

### ✔️ Expected Behavior

Need control to retry index.

### ❌ Actual Behavior

No control, no auto retry.

**Comment by crazywoola** [comment]
We do have a retry button, in knowledge -> Documents, you can see. the button on the top left corner.
