### ISSUE TITLE
The retry index button?

### ISSUE THREAD

**Issue by backlux** [langgenius/dify#7354]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

If indexing somehow got interrupted, it won't auto retry. It's a huge dataset and there's no control from frontend to manually retry (the whole process).

So, the previous issue got closed without clarification:

"We do have a retry button, in knowledge -> Documents, you can see. the button on the top left corner."

1. This happens when the knowledge base is created and not ready. 
2. I can stop and restart for single document in the dataset. but how to do restart for all

I can't find the button at top left? to retry, looked everywhere
Please help, thanks.

<img width="771" alt="image" src="https://github.com/user-attachments/assets/1e9bae98-fc9b-4243-a3c7-f587d9eb2c88">

No button here?
<img width="640" alt="image" src="https://github.com/user-attachments/assets/a2180c1c-5665-47a3-863a-6129e248c6ca">

### ✔️ Expected Behavior

Have retry button

### ❌ Actual Behavior

No retry button

**Comment by backlux** [comment]
@dosu. How do mark one document as failed? Status is indexing, but it's not actually doing indexing.

**Comment by backlux** [comment]
@dosu Or is there any way to trigger the index retry process via api endpoint?

**Comment by crazywoola** [comment]
As the bot's said, the retry button is only available for the failed tasks. So if you want to have a retry button then it should be a feature request other than bug report.

**Comment by backlux** [comment]
The way you talk is so ...

It stuck in indexing for over an hour... "the retry button is only available for the failed tasks"

And you say, ok, it should be a feature request.

Just think, if you really want to push this product to a larger audience, and so many more people will face this. And all this is such an **easy bug to fix**, just add timeout to make it "FAIL"...  That's all you need, instead of saying it's not even a bug.

What are you even talking about???

**Comment by backlux** [comment]
The retry logic is shit, if it works ,you make it better, then it's a feature.
When it is not working, you call it a bug!

**Comment by backlux** [comment]
I guess that's just how you want your product to be.

**Comment by crazywoola** [comment]
Sorry for the misunderstanding,  however https://github.com/langgenius/dify/issues/7353 you didn't provide much useful information.  Not like this one. So based on the information you provide, I can only tell you that there is a 'retry button'. 

> And all this is such an easy bug to fix, just add timeout to make it "FAIL"... That's all you need, instead of saying it's not even a bug.

I agree with this one, I am aware we do lack a timeout task to mark them as 'FAIL'. 

We do want to make it better. I will try to fix it later.

**Comment by backlux** [comment]
I did find out what the problem really is, it's because when using ollama to do embed, if you set the url to something like http://docker.internal.host, then it never timeout, and all task will stuck.  (maybe a dns error from docker I don't know)

A walk around would be use IP addr, temp fixed for me.
