### ISSUE TITLE
Integrate Composio

### ISSUE THREAD

**Issue by Karthikeya-Meesala** [langgenius/dify#7358]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We've got a user request for [Composio](https://docs.composio.dev/) support on Dify.ai. We're pretty excited about the idea, but we wanted to check with you folks first before moving forward.

<img width="689" alt="image" src="https://github.com/user-attachments/assets/b17418ba-0c48-47cb-9129-1a47cb7e62c6">

We recently raised a PR on Langflow to integrate Composio, feel free to check it out [here](https://github.com/langflow-ai/langflow/pull/3034).

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Hello, you are always welcome to submit new tools. :)
