### ISSUE TITLE
绑定Notion，如果是database页面，如何访问database下的页面

### ISSUE THREAD

**Issue by law-key** [langgenius/dify#736]
绑定Notion后，清洗的数据都只是database表格的内容，并没有表格每一行下的页面内容。要如何加载真正的页面内容呢？

**Comment by JohnJyong** [comment]
The subpage permissions of the database failed to sync over. Please go to the settings page and click on sync permissions.
![image](https://github.com/langgenius/dify/assets/76649700/92b7667a-6b76-4f6c-a8b6-fdea7a0b3ed5)

**Comment by law-key** [comment]
> 数据库的子页面权限同步失败。请转到设置页面，然后单击同步权限。 ![图像](https://user-images.githubusercontent.com/76649700/258060191-92b7667a-6b76-4f6c-a8b6-fdea7a0b3ed5.png)

谢谢，同步后授权页面数量增加了，但是在数据集清洗数据里，仍然只能看到子页面的标题，看不到内容，应当如何处理呢

**Comment by law-key** [comment]
> 数据库的子页面权限同步失败。请转到设置页面，然后单击同步权限。 ![图像](https://user-images.githubusercontent.com/76649700/258060191-92b7667a-6b76-4f6c-a8b6-fdea7a0b3ed5.png)

感谢，可以了
