### ISSUE TITLE
Sometimes `Secret` in ENV will not be fully masked when it contains `.` in the middle

### ISSUE THREAD

**Issue by RockChinQ** [langgenius/dify#7366]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

SaaS 0.7 / self-hosted 0.16.6

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

Enter the editor of any flow-type app, click to `env` and add a `Secret`.
<img width="406" alt="image" src="https://github.com/user-attachments/assets/6f041b24-e03f-4abe-b98f-8d832020450f">

<img width="410" alt="image" src="https://github.com/user-attachments/assets/94be0ef4-93d3-48f0-baf8-e7d3da25fb12">

### ✔️ Expected Behavior

The whole secret value should be masked.

### ❌ Actual Behavior

When the secret value contains a '.' in the middle, only a portion will be masked.

<img width="406" alt="image" src="https://github.com/user-attachments/assets/4ed06365-f918-40a2-abf6-0966fa63e105">

<img width="410" alt="image" src="https://github.com/user-attachments/assets/52dc906c-1ef0-4eaf-8c4d-6310f7bc2e01">

Tested:

- 12345.abc
- abc.,12345

**Comment by wellCh4n** [comment]
I happen to know this. This desensitization logic has nothing to do with `.`.
If you are familiar with Python, you can take a look at `api.core.helper.encrypter.obfuscated_token`.
```python
def obfuscated_token(token: str):
    if not token:
        return token
    if len(token) <= 8:
        return '*' * 20
    return token[:6] + '*' * 12 + token[-2:]
```
The following is ChatGPT's explanation of this code segment.
> This Python function takes a string called token and returns an obfuscated version of it. If the token is empty, it returns the token as is. If the token is 8 characters or shorter, it returns a string of 20 asterisks (*). If the token is longer than 8 characters, it returns the first 6 characters of the token, followed by 12 asterisks, and the last 2 characters of the token.

So the result is in line with expectations. **I don't think it is a bug.**

**Comment by RockChinQ** [comment]
@wellCh4n Okay, I see. It's a little bit counterintuitive, I think it should be fully masked or let the masked string length the same as original.

**Comment by wellCh4n** [comment]
> @wellCh4n Okay, I see. It's a little bit counterintuitive, I think it should be fully masked or make the masked string length the same as original.

@RockChinQ I'm not the author of this feature. But I guess this is a balance between security and ease of use.

**Comment by laipz8200** [comment]
> @wellCh4n Okay, I see. It's a little bit counterintuitive, I think it should be fully masked or make the masked string length the same as original.

This design aims to securely prevent the leakage of the key's actual length.
