### ISSUE TITLE
Dont run time import upload file knowledge

### ISSUE THREAD

**Issue by hebum** [langgenius/dify#7367]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

<img width="959" alt="image" src="https://github.com/user-attachments/assets/0c8182e0-1daa-4fee-9b28-cda4cc8242e2">

### ✔️ Expected Behavior

Please fix bug code on dify local => dont run knowledge upload file ? Help me. Tks u
<img width="959" alt="image" src="https://github.com/user-attachments/assets/467ca542-868d-498c-9c68-8068dba703ce">

### ❌ Actual Behavior

<img width="959" alt="image" src="https://github.com/user-attachments/assets/de2c5c1e-f4c1-45e0-a216-cc3603b8112b">

**Comment by crazywoola** [comment]
Duplicated, see https://github.com/langgenius/dify/issues/7368
