### ISSUE TITLE
Multi-lingual build-in prompts

### ISSUE THREAD

**Issue by chenlujia888** [langgenius/dify#7379]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I connect with some Chinese based LLMs, such like ZhipuAI glm-4, the build-in prompts ( located in api/core/llm_generator/prompts.py ) is in English, the llm will response in English. even the context is in Chinese. It's better to have multi-lingual prompts, especially in Chinese.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by alterxyz** [comment]
Thank you for your valuable feedback and willingness to contribute! We appreciate your insight regarding multi-lingual prompts, especially for Chinese-based LLMs like ZhipuAI glm-4.

Our built-in prompts ecosystem is still evolving. We're exploring various possibilities for future development, including different types of built-in generators. Your suggestion for multi-lingual prompts is an interesting idea that we'll keep in mind as we continue to improve our platform.

If you're interested in exploring this further, you might want to check out the [Cookbook Prompt repository](https://github.com/alterxyz/easy-dify-cookbook/tree/main/prompt). While this is a personal project and not officially affiliated with Dify, it's a great place to experiment with and share Chinese prompts.

Once again, we appreciate your feedback and your interest in improving our project!
