### ISSUE TITLE
智聊 Unrecognized request argument supplied: functions

### ISSUE THREAD

**Issue by lingfengchencn** [langgenius/dify#738]
Dify version: Cloud | Self Host
 `git pull `

## The current behavior
环境： azure openai， 配置成功
模型：gpt-3.5-turbo

输入任意内容，会在右上角提示：`Unrecognized request argument supplied: functions`

不知道什么原因。

**Comment by takatost** [comment]
Please upgrade the base Model of your Azure OpenAI `gpt-35-turbo` deployment to the latest version.

**Comment by lingfengchencn** [comment]
> Please upgrade the base Model of your Azure OpenAI `gpt-35-turbo` deployment to the latest version.

OK，upgrade version to 0613 ,and it worked 
![企业微信截图_16911139776105](https://github.com/langgenius/dify/assets/2757011/343b4556-18ba-4dc2-b05b-22c030e43f5e)
