### ISSUE TITLE
Prompt Caching by Anthropic Claude

### ISSUE THREAD

**Issue by amatiytsiv** [langgenius/dify#7382]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

anthropic  announced support for caching it would be nice to have it in model config options: https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by amatiytsiv** [comment]
any plans on implementing this possibility into dify core and tools as by other tools I can see a significant profit from using these as money saving

**Comment by dnyg** [comment]
It is a bit of a complicated feature to implement, because cache is not set in model config options - but per prompt.

So we need a way through the UI to specify that a certain prompt should be cached - similar to how you can enable jinja templates with a slider.

I have made a working version that just uses specific tags to trigger caching, but I don't think Dify would be interested in this solution, as it's a poor UX solution

**Comment by amatiytsiv** [comment]
> It is a bit of a complicated feature to implement, because cache is not set in model config options - but per prompt.
> 
> 
> 
> So we need a way through the UI to specify that a certain prompt should be cached - similar to how you can enable jinja templates with a slider.
> 
> 
> 
> I have made a working version that just uses specific tags to trigger caching, but I don't think Dify would be interested in this solution, as it's a poor UX solution

I believe conversational checkbox next to send button is way to go for now.
But most importantly it also has to be implemented as configurable variable in workflow and agents, it can serve as quick job done avoiding or even preparing good RAG
