### ISSUE TITLE
Cannot link Notion

### ISSUE THREAD

**Issue by sweetkey** [langgenius/dify#7383]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

click this "Add workspace" to create a dataset by importing data from Notion, but an error message shows up. 
![image](https://github.com/user-attachments/assets/126ec73d-5973-4c6a-93ee-6a77d25fafa8)

### ✔️ Expected Behavior

https://docs.dify.ai/learn-more/use-cases/build-an-notion-ai-assistant

### ❌ Actual Behavior

{"error":"invalid_request","error_description":"query failed validation: query.client_id should be a string or `undefined`, instead was `0`.","request_id":"2cae3411-0e34-49d2-9474-17c0218eec06"}

**Comment by sweetkey** [comment]
Thanks, I went to Notion Integration Page to enable Integration with an app, and copied & pasted the secret code back to Notion section in ".env", now it solves the error message issue.

**Comment by niko2020** [comment]
sorry to bump that but a warning message instead of an error would be awesome
