### ISSUE TITLE
Shall we have a Completion Tab in Apps category?

### ISSUE THREAD

**Issue by wellCh4n** [langgenius/dify#7387]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I have lot of Completion Apps and lot of Workflow Apps. But Workflow tab fetch Completion Apps & Workflow Apps both now.
Since they were separated when we created them, is it possible that we could separate them when we filtered them?

> <img width="687" alt="image" src="https://github.com/user-attachments/assets/9cf6fb9e-8b1e-414c-8cc5-aa14e6a4a9ba">

> <img width="1394" alt="image" src="https://github.com/user-attachments/assets/e8ff0664-27b8-44d7-a4b9-4d9f0311dc96">

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Good idea.
