### ISSUE TITLE
The connection in the conditional branch node was not updated after the conditional drag was sorted

### ISSUE THREAD

**Issue by jx2011** [langgenius/dify#7400]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

- step1: Add a conditional branch node to the workflow.
- step2: Add multiple conditions to the conditional branch node.
- step3: Each condition of a branch node connects to a different node.
- step4: Drag-and-drop sort the conditions of the conditional branch node.
![sort](https://github.com/user-attachments/assets/4e46d471-6fb4-44e7-817f-ba6c6c82bb92)

### ✔️ Expected Behavior

It is expected that the line in the conditional branch node is also updated after the condition drag-and-drop is sorted

### ❌ Actual Behavior

The connection in the conditional branch node was not updated after the conditional drag was sorted
![sort](https://github.com/user-attachments/assets/18165fea-1434-4c71-a2d3-ed8e0d1951c0)

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/7303
