### ISSUE TITLE
[Knowledge Base] Q&A retrieval mode response is not as expected

### ISSUE THREAD

**Issue by simcoehsieh** [langgenius/dify#7402]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

According to [this guide](https://docs.dify.ai/guides/knowledge-base/create-knowledge-and-upload-documents) on Q&A mode, when comparing document similarity, it should match the user question with the question in the segment and then return the answer to the LLM. However, in reality, it returns both the question and answer.

Here's the [source code](https://github.com/langgenius/dify/blob/0.7.0/api/core/rag/retrieval/dataset_retrieval.py#L201)

### ✔️ Expected Behavior

In Q&A mode, the retrieved document should only include the answer section.

### ❌ Actual Behavior

It returns both the question and answer when I use the Q&A mode knowledge base in my app.

**Comment by crazywoola** [comment]
You can remove the question in prompts, or let the LLM answer based on the retrieved answers.
