### ISSUE TITLE
someting wrong with configure Claude model

### ISSUE THREAD

**Issue by XeonSid** [langgenius/dify#7405]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/c3a236a5-7f48-45f1-9444-c1846ddca79c)

### ✔️ Expected Behavior

configuration is done

### ❌ Actual Behavior

Error code: 401 - {'message': '暂不支持指定的模型 (request id: 66c318b2441c54614ca430b073f8a200)', 'type': 'chat_api_error'}

**Comment by crazywoola** [comment]
This should check your model provider, this 'claude provider' only works for the official api.
