### ISSUE TITLE
Need minio file support for dify/api/core/file /message_file_parser.py

### ISSUE THREAD

**Issue by han1666** [langgenius/dify#7411]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hi, I am using minio as my image data source, so I need this feature to make it happen

### 2. Additional context or comments

I see the AWS S3 is supported by checking txt in url, should be a quick fix for minio also, thanks

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by WenhanJiang** [comment]
> Well, you can just input the minio configurations in the s3 fields, it should work as well.

Hi there thanks for the reply, is there a tutorial for this?

![image](https://github.com/user-attachments/assets/0766669d-7e9b-4efb-8729-f1aaf8a43547)

by looking at this code, it's just looking for 'amazonaws.com' in the URL tho

**Comment by crazywoola** [comment]
@laipz8200 Could you help with this issue?

**Comment by laipz8200** [comment]
We plan to support more object storage options in the future. In the meantime, feel free to try implementing it yourself!

**Comment by laipz8200** [comment]
> > Well, you can just input the minio configurations in the s3 fields, it should work as well.
> 
> Hi there thanks for the reply, is there a tutorial for this?
> 
> ![image](https://private-user-images.githubusercontent.com/34637693/359115341-0766669d-7e9b-4efb-8729-f1aaf8a43547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzI5NzEsIm5iZiI6MTcyNjEzMjY3MSwicGF0aCI6Ii8zNDYzNzY5My8zNTkxMTUzNDEtMDc2NjY2OWQtN2U5Yi00ZWZiLTg3MjktZjFhYWY4YTQzNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA5MTc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOGM3YjIzZjJkZjA3NDI2ZjI3YTdhYjYyNGU5M2MzYTFhYjNmZjdkOTkxMGIxNDY5NDljM2M5MmI3MTNkODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJQ2gwO3qkvq6AI_eWG3sOJdOZunuSfMECnzH9DoB8w)
> 
> by looking at this code, it's just looking for 'amazonaws.com' in the URL tho

If this check doesn't pass, it will try to make a 'HEAD' request to your service; it should still work.
