### ISSUE TITLE
Follow-up questions don't show up in a agent

### ISSUE THREAD

**Issue by fniu** [langgenius/dify#7413]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

In a agent setting, just add the "Follow-up" feature. Try to talk to the agent in either "Debug an preview" or the app, there are no follow-up questions and one can see an error on the top right corner, saying
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

### ✔️ Expected Behavior

Follow-up questions show up after the responses.

### ❌ Actual Behavior

No follow-up questions and see an error message.

**Comment by crazywoola** [comment]
Which model do you use?

**Comment by crazywoola** [comment]
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

So it should be a problem with OpenAI's api endpoint.

**Comment by dylanhsiao2** [comment]
May I ask what LLM successful people use? I've tried several models but haven't succeeded. I'm not sure if I'm missing any steps.
