### ISSUE TITLE
Logs do not include current day

### ISSUE THREAD

**Issue by nsvrana** [langgenius/dify#7420]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Filter logs in the log viewer does not show the current day for any option unless "All time" is selected.

### ✔️ Expected Behavior

Users would expect options to go up to the current moment, not to the beginning of the day.

### ❌ Actual Behavior

Logs from the current date are not shown unless "all time" is selected.

**Comment by crazywoola** [comment]
Was it included in the previous version?
