### ISSUE TITLE
File size is too large

### ISSUE THREAD

**Issue by CrankGentleman** [langgenius/dify#7425]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. create a chatbot
2. add llm，line to http tool
3. http request image url
4. file size error

![1](https://github.com/user-attachments/assets/fa2d8302-91d1-4fc5-9fdb-0f08def3ccfa)
![2](https://github.com/user-attachments/assets/f932a67b-08e5-40c6-ae32-9d0cdb704070)

### ✔️ Expected Behavior

I want to know where this configuration can be changed

### ❌ Actual Behavior

Run failed: Node HTTP 请求 run failed: File size is too large, max size is 10.00MB, but current size is 24.81 MB.

**Comment by fuwj1994** [comment]
> [@CrankGentleman](https://github.com/CrankGentleman) Hello there! I'm here to help you with any bugs, questions, or contributions you may have for the project. Let me know how I can assist you while you wait for a human maintainer.
> 
> To change the configuration to allow a larger file size for HTTP requests in Dify version 0.7.1, you need to modify the values of `HTTP_REQUEST_NODE_MAX_BINARY_SIZE` and `HTTP_REQUEST_NODE_MAX_TEXT_SIZE` in the `.env` file.
> 
> Here is the relevant part of the `.env` file where these configurations are used:
> 
> # HTTP Node configuration
> HTTP_REQUEST_MAX_CONNECT_TIMEOUT=300
> HTTP_REQUEST_MAX_READ_TIMEOUT=600
> HTTP_REQUEST_MAX_WRITE_TIMEOUT=600
> HTTP_REQUEST_NODE_MAX_BINARY_SIZE=10485760 # 10MB
> HTTP_REQUEST_NODE_MAX_TEXT_SIZE=1048576 # 1MB
> To allow a larger file size, you should update these configuration values in the `.env` file. For example:
> 
> # HTTP Node configuration
> HTTP_REQUEST_MAX_CONNECT_TIMEOUT=300
> HTTP_REQUEST_MAX_READ_TIMEOUT=600
> HTTP_REQUEST_MAX_WRITE_TIMEOUT=600
> HTTP_REQUEST_NODE_MAX_BINARY_SIZE=26214400 # 25MB
> HTTP_REQUEST_NODE_MAX_TEXT_SIZE=26214400 # 25MB
> Adjust the values as needed to fit your requirements [[1]](https://github.com/langgenius/dify/blob/main/api/.env.example).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu)._

okkkkkk!!

please remember modify the .env file
