### ISSUE TITLE
redis port error

### ISSUE THREAD

**Issue by guangzhaituang** [langgenius/dify#7433]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/api/commands.py", line 588, in upgrade_db
    if lock.acquire(blocking=False):
  File "/app/api/.venv/lib/python3.10/site-packages/redis/lock.py", line 210, in acquire
    if self.do_acquire(token):
  File "/app/api/.venv/lib/python3.10/site-packages/redis/lock.py", line 226, in do_acquire
    if self.redis.set(self.name, token, nx=True, px=timeout):
  File "/app/api/.venv/lib/python3.10/site-packages/redis/commands/core.py", line 2333, in set
    return self.execute_command("SET", *pieces, **options)
  File "/app/api/.venv/lib/python3.10/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:65035. Connection refused.
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.`
```

I followed the process git clone to download dify. Executed
`cd docker
cp .env.example .env
docker compose up -d`

But an error occurs as shown in the picture above. I used to have redis 65035 locally. I don't know why it's still like this. I only modify the nginx port in the .env file. No other configuration has been changed.My container keeps restarting and reporting the above error
![image](https://github.com/user-attachments/assets/3e64cbee-fc04-4d5b-9225-2b1ab742c52b)

[](url)

### ✔️ Expected Behavior

success run

### ❌ Actual Behavior

My container keeps restarting and reporting the above error

**Comment by guangzhaituang** [comment]
The above error occurred when I executed `docker logs <container name>`  .This problem has really bothered me for a long time and I need your help. thank you all

**Comment by crazywoola** [comment]
Check the configurations in your .env file

https://github.com/langgenius/dify/blob/c7df6783dffac516643038ad12633bd6ba45ff3f/docker/.env.example#L206-L215

Our container start the redis on port 6379. And you should have modified things in the `.env` file. otherwise it won't access that from `127.0.0.1:65035`.

**Comment by guangzhaituang** [comment]
> 检查 .env 文件中的配置
> 
> https://github.com/langgenius/dify/blob/c7df6783dffac516643038ad12633bd6ba45ff3f/docker/.env.example#L206-L215
> 
> 我们的容器在端口 6379 上启动 redis。并且您应该已经修改了文件中的内容`.env`。否则它将无法从中访问它`127.0.0.1:65035`。

Thanks for your help, I haven't modified the configuration anywhere.
![image](https://github.com/user-attachments/assets/6ed31f78-3436-4147-9489-222f8060d5ae)

**Comment by guangzhaituang** [comment]
> To resolve the Redis connection error (Error 111 connecting to 127.0.0.1:65035) that causes your Docker container to keep restarting, follow these steps:
> 
> 1. **Check Redis Configuration:**
>    Ensure that the Redis service is correctly configured in your `docker-compose.yaml` file. The Redis service should be defined as follows:
>    ```yaml
>    redis:
>      image: redis:6-alpine
>      restart: always
>      volumes:
>        - ./volumes/redis/data:/data
>      command: redis-server --requirepass ${REDIS_PASSWORD:-difyai123456}
>      healthcheck:
>        test: [ "CMD", "redis-cli", "ping" ]
>    ```
> 2. **Verify Environment Variables:**
>    Ensure that the environment variables for Redis are correctly set. Specifically, check the `REDIS_HOST` and `REDIS_PORT` variables:
>    ```yaml
>    REDIS_HOST: ${REDIS_HOST:-redis}
>    REDIS_PORT: ${REDIS_PORT:-6379}
>    ```
> 3. **Check Redis Service Health:**
>    Verify that the Redis service is healthy and running. You can do this by checking the health status of the Redis container:
>    ```yaml
>    healthcheck:
>      test: [ "CMD", "redis-cli", "ping" ]
>    ```
> 4. **Update Connection Settings in Your Application:**
>    Ensure that your application is connecting to the correct Redis host and port. The connection string should match the Redis service configuration:
>    ```yaml
>    CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://:difyai123456@redis:6379/1}
>    ```
> 5. **Initialize Redis in Your Application:**
>    Make sure your application initializes the Redis client correctly. Based on the `ext_redis.py` file, your application should use the following initialization code:
>    ```python
>    import redis
>    from redis.connection import Connection, SSLConnection
>    
>    redis_client = redis.Redis()
>    
>    def init_app(app):
>        connection_class = Connection
>        if app.config.get("REDIS_USE_SSL"):
>            connection_class = SSLConnection
>    
>        redis_client.connection_pool = redis.ConnectionPool(
>            **{
>                "host": app.config.get("REDIS_HOST"),
>                "port": app.config.get("REDIS_PORT"),
>                "username": app.config.get("REDIS_USERNAME"),
>                "password": app.config.get("REDIS_PASSWORD"),
>                "db": app.config.get("REDIS_DB"),
>                "encoding": "utf-8",
>                "encoding_errors": "strict",
>                "decode_responses": False,
>            },
>            connection_class=connection_class,
>        )
>    
>        app.extensions["redis"] = redis_client
>    ```
> 6. **Ensure Docker and Docker Compose Versions:**
>    Make sure you are using the correct versions of Docker and Docker Compose as specified in the Dify documentation:
>    
>    * Docker 19.03 or later
>    * Docker Compose 1.25.1 or later
>    
>    You can check your versions with the following commands:
>    ```shell
>    docker --version
>    docker-compose --version
>    ```
> 7. **Restart Docker Services:**
>    After verifying and updating the configuration, restart your Docker services to apply the changes:
>    ```shell
>    docker-compose down
>    docker-compose up -d
>    ```
> 
> By following these steps, you should be able to resolve the Redis connection error and prevent your Docker container from restarting [[1]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)[[2]](https://github.com/langgenius/dify/blob/main/api/extensions/ext_redis.py)[[3]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/getting-started/install-self-hosted/local-source-code.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Thanks for your help, I haven't modified the configuration anywhere.
![image](https://github.com/user-attachments/assets/6ed31f78-3436-4147-9489-222f8060d5ae)
