### ISSUE TITLE
docker compose with CUDA support

### ISSUE THREAD

**Issue by FrancisVarga** [langgenius/dify#7439]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Running dify on GPU Server doesnt have CUDA support.

### 2. Additional context or comments

Since latest version we can install any python libraries, cant utilize GPU.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Hisir0909** [comment]
Does dify have any parts that require the use of a GPU?

**Comment by FrancisVarga** [comment]
we ca install 3rd party python packages like pytorch which would makes things even much more easier if sandbox would have cuda support

**Comment by alterxyz** [comment]
Regarding the sandbox, please refer to this:
https://github.com/langgenius/dify-sandbox

This would be a significant change, and I personally would be eager to see you or someone else implement this feature.
