### ISSUE TITLE
pip install regex resulting in ImportError: libpthread.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pyxsqbs** [langgenius/dify#7448]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I just want to try import the regex package because there are always problems with import the python package with dify. TOT
![image](https://github.com/user-attachments/assets/201c963f-5ee9-4a9e-83bd-5815b86e69fd)
Dify-api version is 0.7.1 and dify-sandbox version is 0.2.6.

code snippet:
```python
import regex
def main() -> dict:
    return {
        "result": "",
    }
```

Click to run and the following error appears：
![image](https://github.com/user-attachments/assets/6930adfa-5681-434e-9163-c6063ff73acc)

error snippet:
```
Traceback (most recent call last): File "/var/sandbox/sandbox-python/tmp/2e9531ad_be8f_45b5_b8f8_7827bc32f797.py", line 48, in <module> File "<string>", line 3, in <module> File "/usr/local/lib/python3.10/site-packages/regex/__init__.py", line 1, in <module> from .regex import * File "/usr/local/lib/python3.10/site-packages/regex/regex.py", line 417, in <module> import regex._regex_core as _regex_core File "/usr/local/lib/python3.10/site-packages/regex/_regex_core.py", line 21, in <module> import regex._regex as _regex ImportError: libpthread.so.0: cannot open shared object file: No such file or directory error: exit status 255
```

### ✔️ Expected Behavior

Run success!

### ❌ Actual Behavior

ImportError: libpthread.so.0: cannot open shared object file: No such file or directory

**Comment by crazywoola** [comment]
If you would like to add third-party libs, you need to add things here first.

https://github.com/langgenius/dify/blob/bbef964eb5caaca6df74b21a596900f31faff677/docker/volumes/sandbox/dependencies/python-requirements.txt

And sandbox is a system wrapper for executing codes, which means it needs some native libs like your case, so make sure you can run this code in the sandbox container.

See FAQ 1 here.

https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md

**Comment by pyxsqbs** [comment]
@Yeuoly Could you kindly review this, please?

**Comment by Yeuoly** [comment]
> @Yeuoly Could you kindly review this, please?

Are you interested in contributing this? Just add libpthread.so.0 into DEFAULT_PYTHON_LIB_REQUIREMENTS and do some tests for it.
