### ISSUE TITLE
Convesation title not generated

### ISSUE THREAD

**Issue by lx1054331851** [langgenius/dify#7449]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0, 0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/a0d61f54-b7ff-4e6b-b1cb-c85b59d4acd8)

can not generate conversation title automaticly.

**Comment by crazywoola** [comment]
What LLM do you use.

**Comment by lx1054331851** [comment]
gpt 4o

> What LLM do you use.

**Comment by wupeisheng** [comment]
> gpt 4o
> 
> > What LLM do you use.

So what is the problem?

**Comment by wupeisheng** [comment]
> The conversation title is not generated automatically in the self-hosted Dify versions 0.7.0 and 0.7.1 because the code does not include any logic to automatically generate a conversation title. The title is set based on the `site.title` and `customConfig` properties, but there is no implementation for generating a title dynamically based on the conversation content [[1]](https://github.com/langgenius/dify/blob/main/web/app/components/base/chat/embedded-chatbot/index.tsx).在自托管的Dify版本0.7.0和0.7.1中，会话标题不会自动生成，因为代码不包含任何自动生成会话标题的逻辑。标题是基于和属性设置的，但是没有实现基于对话内容 [[1]](https://github.com/langgenius/dify/blob/main/web/app/components/base/chat/embedded-chatbot/index.tsx) 动态生成标题。
> 
> However, there is existing functionality in the Dify codebase that attempts to generate conversation titles dynamically based on the conversation content. The method `generate_conversation_name` in the `LLMGenerator` class is responsible for this functionality. Additionally, the `MessageCycleManage` class includes a method `_generate_conversation_name` that initiates the title generation process in a separate thread if the conversation is new and the `auto_generate_conversation_name` flag is set to true [[2]](https://github.com/langgenius/dify/blob/main/api/core/llm_generator/llm_generator.py)[[3]](https://github.com/langgenius/dify/blob/main/api/core/app/task_pipeline/message_cycle_manage.py).但是，Dify代码库中有一些现有的功能，可以尝试根据对话内容动态地生成对话标题。类中的方法负责此功能。此外，类包含一个方法，如果会话是新的，并且标志设置为true  [[2]](https://github.com/langgenius/dify/blob/main/api/core/llm_generator/llm_generator.py)[[3]](https://github.com/langgenius/dify/blob/main/api/core/app/task_pipeline/message_cycle_manage.py) ，则该方法在单独的线程中启动标题生成过程。
> 
> _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu).要继续跟嘟嘟说话，提提。_

I also can't display the title on version 0.15. Is this resolved
