### ISSUE TITLE
When Dify logs in, some requested URLs return the 401 status code.

### ISSUE THREAD

**Issue by lonnys** [langgenius/dify#7452]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When Dify logs in, it will prompt ```Invalid Authorization header format. Expected 'Bearer <api-key>' format.```
![image](https://github.com/user-attachments/assets/c4d2fe87-d185-4153-80d9-2a0bdb6b1cc7)
and some requested URLs return the 401 status code.
![image](https://github.com/user-attachments/assets/47644c6a-e8fe-4f90-a9d9-cc09c1ff166e)
Although this does not affect the final login, if I use the Nginx proxy and use LDAP to verify the intranet users, these three 401 errors will cause the LDAP verification to fail. Is there any way to avoid this problem and make the server return a normal status?

### ✔️ Expected Behavior

During the request process, the URL returns normal status codes instead of abnormal status codes

### ❌ Actual Behavior

The following three URLs returned the 401 abnormal status code
/console/api/apps?page=1&limit=30&name=
/console/api/account/profile
/console/api/workspaces/current?

**Comment by lonnys** [comment]
The above-mentioned Nginx configuration method was tried, but it still didn't work.

**Comment by laipz8200** [comment]
Hi @lonnys,

Could you please check if the signin request (the second one in the image) is returning the correct token? It seems like the login failure might be causing this issue.

Thanks!

**Comment by lonnys** [comment]
Before logging in, the correct token cannot be obtained. When I first visited the domain name, in the request list, these three URLs directly returned the 401 status code without performing the login operation. But if the login is successful, these three URLs can obtain the correct token. My requirement is: When visiting Dify for the first time, even without logging in, the status code of these three URLs should be 200 instead of other abnormal status codes, without affecting the LDAP verification before accessing the host.

**Comment by laipz8200** [comment]
Based on the image you provided, it seems that you were unable to successfully log into the system after signing in. However, we haven't been able to reproduce this issue on our end.

Could you please check your deployment environment, try again, and provide us with more details? For example, the specifics of the response from the sign-in request.

By the way, we also offer LDAP in our enterprise version.

**Comment by ricky977** [comment]
> 在未登录前无法获取正确的token。我第一次访问域名时，在请求列表中，这三个URL直接返回了401状态码，没有执行登录操作。但是如果登录成功，这三个URL就可以获取到正确的token。我的要求是：第一次访问Dify时，即使没有登录，这三个URL的状态码也应该是200，而不是其他异常状态码，并且不影响访问主机前的LDAP验证。

你好，请问这个问题解决了吗，登录返回的是正常的，这三个请求也是401

**Comment by laipz8200** [comment]
We offer LDAP support in the Enterprise Edition. For other scenarios, we welcome you to submit a PR.
