### ISSUE TITLE
Increasing Agent Tools Limit

### ISSUE THREAD

**Issue by ingrivia** [langgenius/dify#7456]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Thank you so much for all the amazing work you’ve put into this project!

I have a question regarding the current limitation on the number of tools an agent can support. Currently, the maximum limit is set at 10, but I have some requirements that would exceed this limit.

Is there any way to increase this limit? I’d really appreciate any advice or suggestions you might have on how to make this possible.

**Comment by crazywoola** [comment]
Please use the feature request template, and we have a similar issue before.

**Comment by ganeshbehera** [comment]
@dosu How edit docker version export const MAX_TOOLS_NUM = 20;  ?

**Comment by ganeshbehera** [comment]
How can increase the MAX_TOOLS_NUM on docker version?

**Comment by yanwei007** [comment]
@crazywoola How can increase the MAX_TOOLS_NUM on docker version?

**Comment by crazywoola** [comment]
> [@crazywoola](https://github.com/crazywoola) How can increase the MAX_TOOLS_NUM on docker version?

@dashing9527 No you can't

**Comment by firstcomeuropeag** [comment]
i dont know but limiting tools count is not good.
PUSH!

**Comment by ries9112** [comment]
Agreed, would be really nice to have a straightforward way of adjusting things like this

**Comment by Michael-ZE** [comment]
Hi. I'm using the Web version of Dify.
Can the tools number be increased there? Only 10 is quite restrictive.
Thank you.
