### ISSUE TITLE
The score of all results retrieved from the knowledge base is null

### ISSUE THREAD

**Issue by Bulua** [langgenius/dify#7468]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/96869c40-234e-44d0-94b0-ace1819cb2d9)

**Comment by Bulua** [comment]
![image](https://github.com/user-attachments/assets/db0e5657-2c97-4adf-9c9d-85711bdb14dc)
This is the setting of my knowledge base, and the score in the search results is still null

**Comment by crazywoola** [comment]
Are you referring to the knowledge API?

**Comment by leoterry-ulrica** [comment]
> Are you referring to the knowledge API?

I’m also experiencing the same issue, and the text blocks with score=null are being sorted to the front.
