### ISSUE TITLE
cannot save the code in code block

### ISSUE THREAD

**Issue by MartinBTM** [langgenius/dify#7469]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when I fill in some code in code block, it can not save when I switch to other page, I try to publish, also not work
see the pic below
![20240821104303](https://github.com/user-attachments/assets/64a9b8f0-78d0-4d88-9d48-25ef34cfc40f)
![20240821104229](https://github.com/user-attachments/assets/4990eb37-b94c-42a5-b7bd-6fcfbbb66d63)

### ✔️ Expected Behavior

save my code 

### ❌ Actual Behavior

Return to the initial status

**Comment by crazywoola** [comment]
Please upgrade to v0.7.1 to see if this is resolved.
