### ISSUE TITLE
Error when adding Notion data source in the community version of Dify

### ISSUE THREAD

**Issue by Bourne-alt** [langgenius/dify#7479]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I add a Notion data source on the community version of Dify, I encounter the following error when clicking the ‘Add Workspace’ button:
{"error":"invalid_request","error_description":"query failed validation: query.client_id should be a string or `undefined`, instead was `0`.","request_id":"6bb41008-4f72-41e5-b84a-825add13f49b"}

.env file parameters have already been configured:
NOTION_INTEGRATION_TYPE=internal 
NOTION_INTERNAL_SECRET=secret_******

Please help to resolve this.
<img width="1425" alt="截屏2024-08-21 12 08 28" src="https://github.com/user-attachments/assets/17a1acbb-0b66-42fe-988a-1c31f659c4ef">

**Comment by d2clab** [comment]
If I am using internal integration, then I don't need a Notion Cliend_ID, is that right?
