### ISSUE TITLE
File Upload Integration in chat

### ISSUE THREAD

**Issue by sanzhar-rakhimkul** [langgenius/dify#7480]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We would like to request the addition of a file upload button in the chat interface. This new feature would allow users to upload files directly within the conversation flow and use the content of those files as context for the ongoing discussion.
![Annotation 2024-08-21 091620](https://github.com/user-attachments/assets/86cd5cd9-96bd-40cd-a7bf-bbf497ef524b)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated
