### ISSUE TITLE
Setting up AWS Bedrock: ValidationException: Operation not allowed

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [langgenius/dify#7488]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I want to setup the AWS Bedrock Connector with my AWS Key und SecKey.
The AWS User has already the BedrockFullAccess Role.
Everytime i try to save the credentials: ValidationException: Operation not allowed

In the Dev Console (Network Tab) of Chrome:
POST: https://<domain>/console/api/workspaces/current/model-providers/bedrock - 400 Bad Request
`{
    "code": "invalid_param",
    "message": "ValidationException: Operation not allowed",
    "status": 400
}`

### ✔️ Expected Behavior

A success Saving.

**Comment by ybalbert001** [comment]
1.  Please tell me the model_id you provided.
2. Please make sure you grant the model access, you can change it through "Bedrock -> Bedrock configurations -> model access"

**Comment by ybalbert001** [comment]
I tried it, but can't reproduce this issue on 0.7.1 (on my ec2)

**Comment by wwwDESIGN-basti** [comment]
@ybalbert001 
Thanks for your comments.
I had to reconfigure my AWS Bedrock connection after swapping my AWS key. The new key includes the BedRockFullAccess policy. I have requested and been granted model access for the North Virginia region. During the configuration in Dify, I didn’t enter a model name (which I hadn’t done before either). However, recently, AWS notified me of a security incident. Could it be that this incident is affecting my ability to access AWS services while the issue remains unresolved?

**Comment by nsvrana** [comment]
I needed the model name (e.g. anthropic.claude-3-sonnet-20240229-v1:0) to verify the first time.

**Comment by ybalbert001** [comment]
> @ybalbert001 Thanks for your comments. I had to reconfigure my AWS Bedrock connection after swapping my AWS key. The new key includes the BedRockFullAccess policy. I have requested and been granted model access for the North Virginia region. During the configuration in Dify, I didn’t enter a model name (which I hadn’t done before either). However, recently, AWS notified me of a security incident. Could it be that this incident is affecting my ability to access AWS services while the issue remains unresolved?

If you can invoke model through AWS console, this issue should not be the root cause for your problem. You may check the 
 your AK/SK and its binded policy, if possible please provide some snapshots for us. 

An another suggestion is to contact SA of aws to ask help.
