### ISSUE TITLE
Firefox browser cannot play TTS audio.

### ISSUE THREAD

**Issue by gjfmlj** [langgenius/dify#7492]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Opening the webapp URL with Firefox, the AI's response will not be automatically played through voice, and the response content cannot be manually played either.

### ✔️ Expected Behavior

I hope to play TTS audio normally in the Firefox browser.

### ❌ Actual Behavior

The error message in the Firefox browser console is as follows:.

Uncaught DOMException: MediaSource.addSourceBuffer: Type not supported in MediaSource
    NextJS 37
6343-c531cfd2e942ddac.js:1
无法播放媒体。没有相应格式的解码器：audio/mpeg

**Comment by wellCh4n** [comment]
This issue has nothing to do with dify, I'll try to answer it.

1. In dify tts api, the audio returned is in audio/mpeg(aka mp3) format. e.g. OpenAI
```python
  if len(content_text) > word_limit:
      sentences = self._split_text_into_sentences(content_text, max_length=word_limit)
      executor = concurrent.futures.ThreadPoolExecutor(max_workers=min(3, len(sentences)))
      futures = [executor.submit(client.audio.speech.with_streaming_response.create, model=model,
                                 response_format="mp3",
                                 input=sentences[i], voice=voice) for i in range(len(sentences))]
      for index, future in enumerate(futures):
          yield from future.result().__enter__().iter_bytes(1024)

  else:
      response = client.audio.speech.with_streaming_response.create(model=model, voice=voice,
                                                                    response_format="mp3",
                                                                    input=content_text.strip())
```
2. On the dify page, playing audio uses [MediaSource](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource)
```typescript
private listenMediaSource(contentType: string) {
  this.mediaSource?.addEventListener('sourceopen', () => {
    if (this.sourceBuffer)
      return

    this.sourceBuffer = this.mediaSource?.addSourceBuffer(contentType)
  })
}
```
3. Not support `audio/mpeg` in Firefox `MediaSource`
<img width="702" alt="image" src="https://github.com/user-attachments/assets/bbd236bd-2482-4c2f-9bed-99ffbb568130">

> refer: [All MIME types supported by MediaRecorder in Firefox and Chrome?](https://stackoverflow.com/questions/41739837/all-mime-types-supported-by-mediarecorder-in-firefox-and-chrome)

**Possible solution**
1. Return other format audio. e.g. "opus", "aac", "flac", and "pcm" [OpenAI Format](https://platform.openai.com/docs/guides/text-to-speech/supported-output-formats)
2. Switch to another way of playing audio.
3. Use Chrome. 🤣

**Comment by zscxc** [comment]
Timbre and tts are turned on, but it cannot play automatically, and the stream is also empty, the timbre switch is not effective, and all the voices are female
![image](https://github.com/user-attachments/assets/a1cb0221-a47a-4eaa-a9ba-73d9ba191da5)
![image](https://github.com/user-attachments/assets/88d173ef-95f7-463a-92d0-44dc1f06ade4)
