### ISSUE TITLE
Chatbot Content moderation support AWS Bedrock Guardrails API

### ISSUE THREAD

**Issue by SIN1109** [langgenius/dify#7499]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently Studio chatbot do not support AWS Bedrock guardrails ApplyGuardrail API. 

![image](https://github.com/user-attachments/assets/a1c7d551-e6d2-4899-b497-d9ba59b45322)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by alterxyz** [comment]
You can find it at "Tools".
![image](https://github.com/user-attachments/assets/04c0885d-8376-4b15-afbf-0934b7383641)
