### ISSUE TITLE
The Chat Page's title isn't updated after updating the app's name

### ISSUE THREAD

**Issue by ysq-yq** [langgenius/dify#7502]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. update the name of the app
2. open the Chat Page

### ✔️ Expected Behavior

The Chat Page's title is expected to be updated

### ❌ Actual Behavior

The Chat Page's title isn't updated

**Comment by crazywoola** [comment]
The app and shared app have 2 different entries to setup their name. So you need to setup the name in monitoring -> settings.
