### ISSUE TITLE
please add support change chatbot icon to app icon

### ISSUE THREAD

**Issue by oiuv** [langgenius/dify#7504]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/user-attachments/assets/9f083bc6-b773-45ed-9d04-5d57bf6db6bb)
please add support change chatbot icon to app icon

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by massif-01** [comment]
+1

**Comment by diginovo** [comment]
Totally agreed!! The chatbot icon should be able to be customized as well.

**Comment by leslie2046** [comment]
+1

**Comment by jujuju102** [comment]
+1

**Comment by kurokobo** [comment]
@crazywoola or team,
I'd like to implement this, but I want to hear your opinion to know which is the most appropreate design to follow your design policy.

- A) Change the default behavior to always use the app icon as the answer icon
- B) Add switch to use the app icon as the answer icon. If this option is disabled, the default answer icon (🤖 ) is used.
- C) Allow answer icon to be set independently from app icon. Add setting modals for both the Shared Apps and Installed Apps screens, therefore along with the app icon, users have to change settings in four places.

**Comment by crazywoola** [comment]
Hello @kurokobo 

I would like to choose the B. This sounds more appropriate to me. :)


![QQ_1725072784669](https://github.com/user-attachments/assets/d1c70034-35ea-435e-b32e-2a7bd6cf2d07)

**Comment by kurokobo** [comment]
@crazywoola 
Hi, thanks for your rapid reply. Will try to implement this😃

**Comment by oiuv** [comment]
> @crazywoola or team, I'd like to implement this, but I want to hear your opinion to know which is the most appropreate design to follow your design policy.
> 
> * A) Change the default behavior to always use the app icon as the answer icon
> * B) Add switch to use the app icon as the answer icon. If this option is disabled, the default answer icon (🤖 ) is used.
> * C) Allow answer icon to be set independently from app icon. Add setting modals for both the Shared Apps and Installed Apps screens, therefore along with the app icon, users have to change settings in four places.

A or B，A is easy，B is flexible
