### ISSUE TITLE
Exception output after the workflow was published as a tool 

### ISSUE THREAD

**Issue by skywolf123** [langgenius/dify#7505]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. I did a workflow that was very simple. I started typing a string, passed through an LLM, and the result was the text output by the LLM 
2. Then I published this workflow as a tool
3. In a new workflow, I started typing a string, connecting an LLM, and then connecting the tool that was just released. The output text of the LLM is given to the tool, and then the output of the tool is given to the result.
4. However, the output at this time is {"text": "XXXX"} instead of normal XXXXX
![image](https://github.com/user-attachments/assets/bf80c802-15ae-427f-8c59-58de18b48cf2)

**Comment by skywolf123** [comment]
To be honest, I didn't understand this AI reply

**Comment by crazywoola** [comment]
It's expected behavior, if you don't want the text key, you could use a jinja or code node to extract it. It's the same as retrieving things from HTTP. It should answer with a structure.

I noticed you have already submit a bug report but actually it's not and this one. So next time, please make sure search existing issue or use the discussion to ask a question.

**Comment by skywolf123** [comment]
@crazywoola 
I got normal text in the editing interface by adding a jinja node (which I manipulated directly with strings due to not supporting fromjson filter), but no text was displayed on the published page.
![image](https://github.com/user-attachments/assets/9cbc3809-ec41-4c56-8b0e-00bea5351637)
![image](https://github.com/user-attachments/assets/1adf9dc9-63b9-42d3-abee-f22952bbe1a2)
![image](https://github.com/user-attachments/assets/23843a3b-b919-4094-b537-f251e632fff5)
![image](https://github.com/user-attachments/assets/e108f62c-7b25-407c-a768-4c1edf7fade3)

**Comment by yuweimian-shy** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.7.1
> 
> ### Cloud or Self Hosted
> Self Hosted (Docker)
> 
> ### Steps to reproduce
> 1. I did a workflow that was very simple. I started typing a string, passed through an LLM, and the result was the text output by the LLM
> 2. Then I published this workflow as a tool
> 3. In a new workflow, I started typing a string, connecting an LLM, and then connecting the tool that was just released. The output text of the LLM is given to the tool, and then the output of the tool is given to the result.
> 4. However, the output at this time is {"text": "XXXX"} instead of normal XXXXX
>    ![image](https://private-user-images.githubusercontent.com/34243902/359862585-bf80c802-15ae-427f-8c59-58de18b48cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTI1NjMsIm5iZiI6MTcyNDMxMjI2MywicGF0aCI6Ii8zNDI0MzkwMi8zNTk4NjI1ODUtYmY4MGM4MDItMTVhZS00MjdmLThjNTktNThkZTE4YjQ4Y2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3Mzc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZmM0OTA0ZDMxZTJiOTQzN2Y2MWEzY2UzMzA0OWFlYmI3NmJhZGY2ZmQyN2Q1NDkwMTI0ZjRkNDQ0ZGU3MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hylt5SCzAbvc8ekxTz2DHiuRrHKAaRU8hn3j9mw3s3k)
> 
> ### ✔️ Expected Behavior
> _No response_
> 
> ### ❌ Actual Behavior
> _No response_

can you tell me how to publish workflow to tools, Why is the button for my publishing tool grayed out
![微信图片_20240822154101](https://github.com/user-attachments/assets/3a221524-ee53-4a71-8072-d6dd5a1286f6)

**Comment by skywolf123** [comment]
I don't know why you're graying out here, I released this workflow first, and it works normally as a publishing page, and then I click on publishing as a tool, and I haven't encountered your situation.

You can open an issue or a discussion. The maintainers of this seem to be quite busy, they don't like us to ask questions in the form of issues, and they don't like to explain to novice users like me, you can ask people to see if they have encountered your situation.

**Comment by crazywoola** [comment]
> You can open an issue or a discussion. The maintainers of this seem to be quite busy, they don't like us to ask questions in the form of issues, and they don't like to explain to novice users like me, you can ask people to see if they have encountered your situation.

For questions, it's better to open them in discussions. We already highlighted it in the self checks.  But I already answered your questions. :)
