### ISSUE TITLE
The published web page is not in Chinese

### ISSUE THREAD

**Issue by skywolf123** [langgenius/dify#7506]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

My language selection is Chinese, but the web page after the workflow is published is in English

![image](https://github.com/user-attachments/assets/8ff7ae65-6da0-4e50-9ed2-c276c2315130)

**Comment by crazywoola** [comment]
<img width="586" alt="image" src="https://github.com/user-attachments/assets/1862375b-e5d3-46a8-9805-3fc6aea0f320">
