### ISSUE TITLE
Support for multiple context imports for LLM nodes

### ISSUE THREAD

**Issue by fniu** [langgenius/dify#7509]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently a LLM node can only import one variable under "CONTEXT".  It would be great to support multiple variables. 
As example, along one flow, user may have retrieved knowledge multiple times which would be needed to include for one LLM node.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We can select multiple datasets into one LLM, however we handle it differently, we use multi-path retrieval to achieve this.
