### ISSUE TITLE
Code Execution python print or any log visible in the frontend

### ISSUE THREAD

**Issue by FrancisVarga** [langgenius/dify#7511]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Debugging code is hard, possible to have the print or anything returned to the frontend or any form of logging.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by alterxyz** [comment]
Currently you can use Python `Try Except`, the return format only in dict with few format.

```python
def main():
    try:
        x = 1 / 0
    except Exception as e:
        x = 0
        error_message = str(e)
    
    return{
        "number": x,
        "debug": error_message
    }
```

I hope this helps. Please let me know if you have any other questions.

Regarding the sandbox(the engine for Code Execution), please refer to this:
https://github.com/langgenius/dify-sandbox
