### ISSUE TITLE
'NoneType' object has no attribute 'provider'

### ISSUE THREAD

**Issue by sataliulan** [langgenius/dify#7513]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hi, there . I've create a chatflow followed by the [tutorial](https://docs.dify.ai/v/zh-hans/guides/workflow/node/knowledge_retrieval), it went failed when ran knowledge retrival, as shown in picture. 
![image](https://github.com/user-attachments/assets/2d0e21f3-a64e-47a7-83e1-7dfc4c6ce3ea)

I saw the docker log reported the bug, as follows pic, any ideas?
![image](https://github.com/user-attachments/assets/6e479e21-1913-4ded-80d3-c6308892a80c)

### ✔️ Expected Behavior

any idea to slove the bug is helpful, thx anyway.

**Comment by JohnJyong** [comment]
the logs you attached is the login error message, but not the correct konwledge retrival node error message , pls double check , thanks @sataliulan

**Comment by sataliulan** [comment]
> the logs you attached is the login error message, but not the correct konwledge retrival node error message , pls double check , thanks @sataliulan

got it, thx

**Comment by sataliulan** [comment]
@JohnJyong ，hi John，I've reproduced the bug twice today，then I saw no logs changed or updated, all latest container logs was printed by yesterday. I dont know why

**Comment by JohnJyong** [comment]
@sataliulan  pls try to run the single node， both Knowledg node and LLM node ， if  there are any problems?
and pls double comfirm your docker image tag,  there is no successful or error icon showed in your attached pic

**Comment by sataliulan** [comment]
> @sataliulan pls try to run the single node， both Knowledg node and LLM node ， if there are any problems? and pls double comfirm your docker image tag, there is no successful or error icon showed in your attached pic example: ![image](https://private-user-images.githubusercontent.com/76649700/360234151-63e980fd-cdb7-4bd2-b4f7-15324430f2c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODMwMDAsIm5iZiI6MTcyNDM4MjcwMCwicGF0aCI6Ii83NjY0OTcwMC8zNjAyMzQxNTEtNjNlOTgwZmQtY2RiNy00YmQyLWI0ZjctMTUzMjQ0MzBmMmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZjU4YjRiMTgxOTcwOGRlMTMxMmVjYWU3N2QwZDUxZGZiMTA4NjA5N2U3NmIzNDJhNDQzNGEyYzU1NDgxMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wkbRwwMQysyct35nXRcPVS5AZIDEgfilSHx_ZGykaCg)

hi, Jhon, I've rerun the workflow as your instruction. got the same err, as shown in the picture.
![image](https://github.com/user-attachments/assets/4dd897ba-fcd6-4930-bd8a-826b075f9885)
I wonder there might be something wrong with my knowledge base, so I double checked it. My knowledgebase seems runing well（as shown ）.
![image](https://github.com/user-attachments/assets/bf1e66eb-eac5-48ab-aa28-3e524660273c)
![image](https://github.com/user-attachments/assets/a748cb3a-5f65-4f4a-ab28-feb416eff8a2)
so，I built a  chat demo with the knowledge base，none errs found，it ran very well.(
![image](https://github.com/user-attachments/assets/ab5b22d7-4565-41c6-914b-3a6109e5335c)

**Comment by sataliulan** [comment]
@JohnJyong ，therefore, I double checked the docker log to see if there is any err like 'provider', and I got this(shown in pic). 
![image](https://github.com/user-attachments/assets/6c8cdb57-f08e-4ede-a868-3fb009c1f0ae)
Is that helpful?

**Comment by sataliulan** [comment]
@JohnJyong @laipz8200 @tomoyuki28jp @rainchen ，Now, I try to avoid the bug that I metioned above. So, I created a new chat workflow from a template（Question Classifier +Knowledge+Chatbot）, I changed the question classes, and added a test knowledge base ,it went well when I asked a question about deep learning,
![image](https://github.com/user-attachments/assets/fb702b90-4c0a-4a5d-b4c9-183444a79ee2)
but got the same error (NoneType object has no attribute 'provider') when I asked question about phm which would result to local knowledge base retrieval. 
Now , I am prety sure there is a bug hiden.
waiting for your reply, thx

**Comment by chrislaupama** [comment]
I had the same issue and found a fix.

First, ensure that the permissions is set to "All team members" for the knowledge.

<img width="665" alt="Screenshot 2024-08-26 at 3 31 12 PM" src="https://github.com/user-attachments/assets/227d4c76-efac-4168-a373-c7fd39511686">

Then remove the Knowledge Retrieval node and add it back again with the knowledge.

Seems to work for me.

**Comment by sataliulan** [comment]
@chrislaupama , it seems the permissions issue, it works, thanks!

**Comment by wangjian0019** [comment]
Online version, turn on this and preview/run once, it will notice error. Then turn off this, preview/run once, no error.
![image](https://github.com/user-attachments/assets/0d7cf32f-034a-4e6c-98da-c50058234ab9)

Docker version, switch to this then no error.
![image](https://github.com/user-attachments/assets/7b7e5df3-4d1a-46eb-a2a7-4b4ea2674b34)

**Comment by sataliulan** [comment]
@wangjian0019 you mean when rerank is turned on, but no model selected, it'll notice the same error, right? I'll recheck that.
