### ISSUE TITLE
Error in "Text Preprocessing and Cleaning" stage when adding new files to existing knowledge base

### ISSUE THREAD

**Issue by cht-k** [langgenius/dify#7516]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.7.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When attempting to add additional documents to an existing Knowledge in Dify Cloud, an error occurs during the "Text Preprocessing and Cleaning" stage. The error message suggests that there's an issue with NLTK (Natural Language Toolkit) being unable to locate a resource named "punkt_tab".

Steps to Reproduce:
1. Navigate to an existing Knowledge base
2. Click the "Add file" button
3. On the "Upload file" page, upload a new document and click "Next"
4. Error occurs upon entering the "Text Preprocessing and Cleaning" page

![image](https://github.com/user-attachments/assets/2f2049d1-bb4a-40fc-bb87-1763c9ff02d3)

```json
{
    "code": "indexing_estimate_error",
    "message": "\n**********************************************************************\n  Resource \u001b[93mpunkt_tab\u001b[0m not found.\n  Please use the NLTK Downloader to obtain the resource:\n\n  \u001b[31m>>> import nltk\n  >>> nltk.download('punkt_tab')\n  \u001b[0m\n  For more information see: https://www.nltk.org/data.html\n\n  Attempted to load \u001b[93mtokenizers/punkt_tab/english/\u001b[0m\n\n  Searched in:\n    - '/root/nltk_data'\n    - '/app/api/.venv/nltk_data'\n    - '/app/api/.venv/share/nltk_data'\n    - '/app/api/.venv/lib/nltk_data'\n    - '/usr/share/nltk_data'\n    - '/usr/local/share/nltk_data'\n    - '/usr/lib/nltk_data'\n    - '/usr/local/lib/nltk_data'\n**********************************************************************\n",
    "status": 500
}
```

### ✔️ Expected Behavior

Ability to embed new documents and add them to an existing Knowledge base.

### ❌ Actual Behavior

Error message appears when entering the "Text Preprocessing and Cleaning" page.

**Comment by crazywoola** [comment]
What system processing LLM did you choose?

**Comment by cht-k** [comment]
I'm not entirely sure what specific information you're requesting here, but I can provide some details that might be relevant:

- The embedding model I'm using is OpenAI's `text-embedding-3-large`.

From my observation, this issue mainly affects the process when the chunk settings are set to "automatic". 

It's worth noting that I'm using the Dify Cloud version, and these error messages appear to be generated by Dify Cloud's backend. Therefore, I don't believe my local system information is relevant to this issue. 

Could you please clarify if you need any other specific information about the LLM or system settings? I'd be happy to provide more details if I can locate them in the Dify Cloud interface.

**Comment by tamanobi** [comment]
I am also facing the same error. I use Dify Cloud. When I create an empty knowledge database, Dify always happens the error.

I was able to avoid the punk_tab error by following these steps:
* Create a non-empty knowledge database
* Set chunk settings to custom

If you create an empty database, you will always get a punk_tab error because the chunk setting is automatic.
