### ISSUE TITLE
Error in displaying pop-up menu in LLM model settings in workflow.

### ISSUE THREAD

**Issue by asemandeveloper** [langgenius/dify#7517]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

In creating an APP from the 'Workflow Planning Assistant' template, when I place the LLM node at the end of the workflow and before the last output and enter the / character in the LLM settings box in the system section, pop-up menus are shown with scrolling! and this makes it difficult to choose menu items.
See the image below.

![image](https://github.com/user-attachments/assets/4b011f62-9ad3-459e-ab8b-157825d808af)

### ✔️ Expected Behavior

Display menus without scrolling.

### ❌ Actual Behavior

Displaying the menu with a scroll that causes problems.

**Comment by asemandeveloper** [comment]
> ```tsx
> LLMNodeType
> ```

Unfortunately, the problem was not solved!

**Comment by iamjoel** [comment]
It has been fixed.
