### ISSUE TITLE
Error is displayed in selecting the tool for the node.

### ISSUE THREAD

**Issue by asemandeveloper** [langgenius/dify#7518]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I run DIFY as Local Source Code. In the workflow, when selecting the tool for the node an error is displayed in selecting the tool for the node.
See the pictures below.

![image](https://github.com/user-attachments/assets/6e9de492-506c-4bb6-8c5b-8a11a0bd047c)

![image](https://github.com/user-attachments/assets/44f1fdc3-ea70-4577-90af-859792006755)

**Comment by asemandeveloper** [comment]
The installed node.js version is version 18.17.0

**Comment by crazywoola** [comment]
Can't reproduce this problem in latest main branch.

<img width="624" alt="image" src="https://github.com/user-attachments/assets/5d84da42-a244-40ac-882e-ebb360014ecb">

We recommend using node version >= v21.

**Comment by asemandeveloper** [comment]
Unfortunately, the problem was not solved!

**Comment by crazywoola** [comment]
But I can not reproduce this either. Is there any errors in console?

**Comment by crazywoola** [comment]
Any errors in frontend console?

**Comment by asemandeveloper** [comment]
> آیا در کنسول frontend خطایی وجود دارد؟

no
There is no error in the console
