### ISSUE TITLE
Error is displayed in selecting the tool for the Agent APP

### ISSUE THREAD

**Issue by asemandeveloper** [langgenius/dify#7519]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I run DIFY as Local Source Code. In the agent APP, when selecting the tools for add a tool, an error is displayed in selecting.
See the pictures below.

![image](https://github.com/user-attachments/assets/26cba0ac-9a8d-43ab-89a1-85086fffe232)

**Comment by crazywoola** [comment]
Can't reproduce this one as well.

<img width="1300" alt="image" src="https://github.com/user-attachments/assets/45d93f59-9a55-493f-861c-d0ffd9d8e930">
