### ISSUE TITLE
API-based Variable stopped working 

### ISSUE THREAD

**Issue by akkaz** [langgenius/dify#7520]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

After more than a month of working without issues, I’ve recently encountered some problems.

It seems that the _API-based Variable_ has stopped functioning as expected in the last few days. Unfortunately, I'm unable to pinpoint exactly when this issue started, though it might have occurred around the update to version 0.7 or shortly after.

I’ve verified that the endpoint is correct and accessible through Insomnia, where everything works as expected. However, according to the Cloudflare logs, it appears that Dify isn't even attempting to reach the endpoint.

The context of this bug is referenced here:
#5717

**Comment by sepa85** [comment]
Same here.

**Comment by aiwinapp** [comment]
Same problem after update

**Comment by mir134** [comment]
Same problem after update

**Comment by oiuv** [comment]
API-based Variable stopped working  after updating to version 0.7.3.

**Comment by gaoyue1989** [comment]
I think this issue is due to this codehttps://github.com/langgenius/dify/blob/c5b3777d93dfbdfc0da338e1e93e909efa461548/api/core/agent/cot_agent_runner.py#L328-L338

**Comment by laipz8200** [comment]
<img width="2222" alt="image" src="https://github.com/user-attachments/assets/2df8917e-c6a9-4478-8ee8-2848061341c7">

Hello, I tried this feature on the latest version of our code. It works well. Can this issue still be reproduced?

**Comment by oiuv** [comment]
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/16485841/371831972-2df8917e-c6a9-4478-8ee8-2848061341c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTI0ODgsIm5iZiI6MTcyNzU5MjE4OCwicGF0aCI6Ii8xNjQ4NTg0MS8zNzE4MzE5NzItMmRmODkxN2UtYzZhOS00NDc4LThlZTgtMjg0ODA2MTM0MWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA2NDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMzdjZjY0N2E1OWMzYjZlYjgyMDE1NTUyMGVkZjlmZjhjOTM1NGY4YWJkYzdlNzY5MTBhMWQ0NzgwYjFlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6EaB_-4U62hCydSh7W3f4cejkak2ObjgC-yjPRZwZAE">
> Hello, I tried this feature on the latest version of our code. It works well. Can this issue still be reproduced?

yes, It works, but why? who fixed this bug?
![image](https://github.com/user-attachments/assets/605efcfa-1acd-400d-bc14-dbc35daf319d)

**Comment by akkaz** [comment]
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/16485841/371831972-2df8917e-c6a9-4478-8ee8-2848061341c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTYxMDQsIm5iZiI6MTcyNzc5NTgwNCwicGF0aCI6Ii8xNjQ4NTg0MS8zNzE4MzE5NzItMmRmODkxN2UtYzZhOS00NDc4LThlZTgtMjg0ODA2MTM0MWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE1MTY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNjRmZWIzOTNmMTg2OGRiZjk2MmQ1OTMwOTQyZDI4ZjA5ZTVhZDIwZDMzNjhkZGQ3NGVjYWViNjdhZmNiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C8m2rrba5ldTQEF0FY8f1Dd8t361NS8ZO4TQE9qYRow">
> Hello, I tried this feature on the latest version of our code. It works well. Can this issue still be reproduced?

I'm following up on this functionality. While it was working well in our latest code version, we've encountered a recurring timeout issue.

Details:

Previously Working: As @laipz8200 mentioned, the feature functioned correctly in recent days.
Current Issue: Today, the feature stopped working again and resulted in a request timeout.
Environment: We're using Hosted Dify (PRO subscription) on version 0.8.3 (signed as latest even if 0.9.1 is released on github).

![image](https://github.com/user-attachments/assets/8daeff97-2199-4f3d-aaa6-c69d2d09d42b)
