### ISSUE TITLE
The hyperlink is displaying incorrectly

### ISSUE THREAD

**Issue by jim1997** [langgenius/dify#7523]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The hyperlink is displaying incorrectly. i am guessing that the comma next to the link  causes the entire sentence to be interpreted as a link. So when I clicked it, it didn't link to the correct location.The link below functions correctly. Is this a bug?
![Selection_020](https://github.com/user-attachments/assets/1d48bbdf-fe08-443d-951d-2380f47f9506)

### ✔️ Expected Behavior

The link above functions correctly. 

### ❌ Actual Behavior

The link above functions incorrectly.

**Comment by crazywoola** [comment]
It's related to the markdown output. It's not a but, for more structured output, you can use workflow to format links in content.
