### ISSUE TITLE
How to correctly operate the input and output of images in chatflow

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#7529]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/1a2e022c-f1c1-4360-aae0-eaea9bfe4604)
How to correctly operate the input and output of images in chatflow

**Comment by 401557122** [comment]
When the QR code tool is connected to the direct reply, entering the file object generated by the QR code in the direct reply will result in an error message: Run failed: Node. Directly reply with 2 run failed: 'FileVar' object has no attribute 'markdown'@dosu.

**Comment by 401557122** [comment]
Is this a bug because only direct replies to nodes can use files as input, even if file upload is enabled, files are not an optional input for nodes such as LLM. However, using files in direct replies still generates an error message@dosu.

**Comment by crazywoola** [comment]
This is resolved in v0.7.1 also this is a duplicated question.
