### ISSUE TITLE
Qdrant does not support full-text search for numbers or letters

### ISSUE THREAD

**Issue by leoterry-ulrica** [langgenius/dify#7543]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Recall Test，select full text search
2. input numbers or letters，forexample：3+；or：3；or：X
3. click test, return empty data

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/12539ca6-6e20-46e1-ba64-47c2c9cedc2d)

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/b95ab899-8a57-4c46-9ff3-837044e68734)

**Comment by JohnJyong** [comment]
Word segmentation rule restrictions cannot be met for the time being.
