### ISSUE TITLE
the result is null when i choose rerank instead of weight

### ISSUE THREAD

**Issue by Linnnkkk** [langgenius/dify#7547]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

the result is null when i choose rerank instead of weight

**Comment by crazywoola** [comment]
Please describe the issue you are facing with more details. A single sentence with the same tittle and description are not helpful at all.

**Comment by Linnnkkk** [comment]
> Please describe the issue you are facing with more details. A single sentence with the same tittle and description are not helpful at all.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/69ac5e2a-f219-4dbe-9612-1547b83890fa">
as pic shown, i adjust TopK value and Score Threshold in rerank, but return is still null, while i choose weight, it return some values to me.

**Comment by crazywoola** [comment]
Fixed in v0.8.x
