### ISSUE TITLE
Integrability of tenant admin API

### ISSUE THREAD

**Issue by MatriQ** [langgenius/dify#755]
**Is your feature request related to a problem? Please describe.**
I want to integrate Dify into my backend and make Dify exposes a tenant's admin APIs(like: /apps, I'm not sure there are how many endpoints currently).

**Describe the solution you'd like**
* Dify can flag if expose admin APIs af a tenant via env or provide a setting UI for it.
* Dify provides a callback API `POST /api/:tenantId/integration` (TBC). Calling this endpoint will generate a JWT token that will be output. Users can access Dify endpoints with the token.

I can contribute this functionality when everything is confirmed.

**Comment by takatost** [comment]
Great suggestion! We have plans to deprecate the cookie login method and switch to using JWT. However, this requirement has a lower priority, and our team currently doesn't have the resources to work on it. If you can contribute this feature, it would be greatly appreciated.

Our initial idea was to replace the logic of the `login` interface, which carries the cookie, with returning a JWT token. The frontend page can then store this token in local storage. Do you think the `integration` interface you mentioned can be considered the same as the `login` interface?

**Comment by MatriQ** [comment]
My idea of `integration` is different from `Login`, but It's based on JWT authorization.  I would like to think about it more after the authorization refactor. So, let me close this ticket temporarily.
