### ISSUE TITLE
Embeding Chatbot Will Expose URL

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#7551]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

If I embed this chatbot, advanced users can just inspect the code and find the url.
Then, they can bypass paywall and use the chatbot. 
How to prevent this?

<iframe
 src="https://udify.app/chatbot/xxxxxxxxxxxxxxxxxx"
 style="width: 100%; height: 100%; min-height: 700px"
 frameborder="0"
 allow="microphone">
</iframe>

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by taowang1993** [comment]
???

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/7742
