### ISSUE TITLE
Split the parameter configuration of embedding and rerank

### ISSUE THREAD

**Issue by cowcomic** [langgenius/dify#7557]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

After testing, in the current RAG process, TopK and Score will act on the embedding and reranking links at the same time, which is equivalent to the two links sharing the same parameters. This is relatively useless, and in most cases it can only be used for one reranking. It is best to set TopK and Score respectively in the two links, so that the ability of rerank can be truly brought into play.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by lamkacheong** [comment]
I think this is a very important feature. Make rerank really useful
