### ISSUE TITLE
how to modify the workspace name

### ISSUE THREAD

**Issue by fzhou223** [langgenius/dify#7561]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

once I install the Dify using docker, and set up a user information.
but I set a wrong workspace name, how to modify it?

or is it any way to reset the whole Dify, so that I can set it from begining.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This feature is not supported yet. We plan to add this later.
