### ISSUE TITLE
Any plan on supporting openai structured outputs

### ISSUE THREAD

**Issue by cnqdztp** [langgenius/dify#7610]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

As for Augest 2024, OpenAI introduced Structured Outputs, add a new option in response_format, allowing user to give a predefined schema. This is particularly useful, as it solved many issue when using llm response as data source for parsing.
However, the LLM block in workflow now only support json_object as response format.
![image](https://github.com/user-attachments/assets/45e5c85d-4578-4715-a35c-262afc72d9d0)
Any plan on updating this?

### 2. Additional context or comments

Please refer to this documentation for information regarding openai's new feature:
[Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs/structured-outputs)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/releases/tag/0.7.1

> OpenAI Structured Outputs Support: Now supporting OpenAI's Structured Outputs by @hjlarry in https://github.com/langgenius/dify/pull/7258.

Only gpt-4o-mini and gpt-4o-2024-08-06 can use this feature.

**Comment by liaopenghui-tal** [comment]
> See https://github.com/langgenius/dify/releases/tag/0.7.1
> 
> > OpenAI Structured Outputs Support: Now supporting OpenAI's Structured Outputs by @hjlarry in #7258.
> 
> Only gpt-4o-mini and gpt-4o-2024-08-06 can use this feature.

This feature is not available with the gpt-4o-mini and gpt-4o-2024-08-06 models from other model vendors, such as Azure and OpenRouter

**Comment by liaopen123** [comment]
> See https://github.com/langgenius/dify/releases/tag/0.7.1
> 
> > OpenAI Structured Outputs Support: Now supporting OpenAI's Structured Outputs by @hjlarry in #7258.
> 
> Only gpt-4o-mini and gpt-4o-2024-08-06 can use this feature.

This feature is not available with the gpt-4o-mini and gpt-4o-2024-08-06 models from other model vendors, such as Azure and OpenRouter
