### ISSUE TITLE
can't complete sync with notion

### ISSUE THREAD

**Issue by suredream** [langgenius/dify#7611]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Follow https://docs.dify.ai/v/zh-hans/guides/knowledge-base/sync-from-notion

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/b4b9a6a1-45c9-41ac-8db7-16746205bfcf)

### ❌ Actual Behavior

notion workspace display empty, however, I do have pages in it.

<img width="670" alt="image" src="https://github.com/user-attachments/assets/784179ec-f54b-41bb-ac02-c78a1d2f6531">

**Comment by crazywoola** [comment]
We have several fixes related to notion since this version, please try the latest version to see if this issue persists.

**Comment by suredream** [comment]
@crazywoola tks. I followed the instruction here:

https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/docker-compose#geng-xin-dify

After the updates, the issues are still the same.

**Comment by sweetkey** [comment]
I had the similar incompleted sync issue on some pages in Notion as well, at verson 0.7.1. It seems the import function of dify cannot recognize the "Toggled section" or embedded page in the Notion. I had to export the pages in the Notion then imported to dify knowledge. Just FYI.

**Comment by suredream** [comment]
@sweetkey then it is not "sync", right? What if you have updated the pages in the notion later?

**Comment by danatechgithub1** [comment]
same issue

**Comment by lumenghz** [comment]
Same issue. Complete all setting following the documentation, connect integrations in Notion page.

'0 Pages authorized' in dify

**Comment by suredream** [comment]
@lumenghz can you sync pages from notion now? I can `link` a notion, no errors report but no pages founded.

**Comment by suredream** [comment]
It is. Many thanks! Life saver.

**Comment by SteveMoribe** [comment]
I will include a case that I resolved as well.
I experienced the same issue, and upon carefully re-checking the NOTION_INTERNAL_SECRET, I found a typo. Even though there was a typo, Dify and Notion displayed a successful connection, which delayed the resolution of the problem. In reality, the SECRET was incorrect, so the connection was not actually successful. Please double-check for any typos.
