### ISSUE TITLE
Prompt Management and Versioning Feature

### ISSUE THREAD

**Issue by Teirizheng** [langgenius/dify#7614]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes, I frequently need to adjust the prompts to optimize the performance of my chatbot. Currently, I have to do this manually which is time-consuming and inefficient.

### 2. Additional context or comments

I would like to see a feature that allows me to:

1. Draft prompts.
2. Save prompts with tags and descriptions, and also save test data.
3. Download the conversation using the saved prompts.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by ifsheldon** [comment]
@crazywoola We offer to upstream our extension on Dify. Will you accept and review a related PR? Or, do you want to just implement this yourself?
