### ISSUE TITLE
A significant bug when processing in batch mode that includes multiple LLM results.

### ISSUE THREAD

**Issue by NirvanaProduct** [langgenius/dify#7617]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Design a workflow where the output variable at the end contains the results of multiple LLM runs, and then run batches.
![screenshot-20240825-200151](https://github.com/user-attachments/assets/65595f49-a5f5-4784-94b7-715a66d8ac7c)
![screenshot-20240825-161327](https://github.com/user-attachments/assets/f7a24d05-6040-44bb-baba-113b63beaff5)

### ✔️ Expected Behavior

Get the sum of multiple LLM output results.

### ❌ Actual Behavior

Only received the content from one of the LLM outputs.

**Comment by NirvanaProduct** [comment]
![screenshot-20240825-161942](https://github.com/user-attachments/assets/9ba7f656-6271-46b7-8926-3bacd0859a1b)

**Comment by NirvanaProduct** [comment]
I am using the workflow mode, not the chat assistant model. In the workflow mode, there is no "direct reply", only "end", and "end" cannot appear multiple times

**Comment by NirvanaProduct** [comment]
Using workflow mode because only workflow mode can use batch processing functionality. In workflow mode, content can only be output through "end".

**Comment by NirvanaProduct** [comment]
![screenshot-20240825-161327](https://github.com/user-attachments/assets/985ea231-9b37-44b4-b37b-909e3301a1dd)

**Comment by crazywoola** [comment]
I guess this works for you.

<img width="1712" alt="image" src="https://github.com/user-attachments/assets/972b2ef1-d1f9-44d7-a433-2bb26250c3cc">

**Comment by NirvanaProduct** [comment]
@crazywoola Thank you very much for your answer, but there are still unresolved errors.
When my output is short enough, the method you mentioned works. (As shown in Figure 1)
However, the content I need to output is very long and requires more than 300 seconds to complete. During the waiting process, it will be judged as output timeout by batch processing, and I will still be unable to complete my task. (As shown in Figure 2)
![screenshot-20240826-182213](https://github.com/user-attachments/assets/7e2ec22f-b447-42ce-b810-4c02a686e217)
![screenshot-20240826-181832](https://github.com/user-attachments/assets/4903c4d7-791f-43e3-ac37-8932509288eb)

**Comment by NirvanaProduct** [comment]
![screenshot-20240826-181832](https://github.co@crazywoola /user-attachments/assets/005c00ff-f357-4c7c-ba19-68c45eadf794)
@

**Comment by NirvanaProduct** [comment]
![screenshot-20240826-182528](https://github.com/user-attachments/assets/0f26a550-4c2d-407a-830a-7f582d831bfe)

**Comment by NirvanaProduct** [comment]
run batch mode
