### ISSUE TITLE
The downstream node files parameter of DALL-E 3 tool cannot be obtained

### ISSUE THREAD

**Issue by StrangeXin** [langgenius/dify#7618]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The files variable output by the DALL-E 3 tool node cannot be used in downstream nodes, such as obtaining image links from files and processing them in the code execution node
<img width="1062" alt="iShot_2024-08-25_20 18 00" src="https://github.com/user-attachments/assets/abfef6da-b993-4ce9-a1ba-fe6e73cd72cd">
<img width="1011" alt="iShot_2024-08-25_20 18 16" src="https://github.com/user-attachments/assets/78da6232-08f0-49c6-9cbe-c776d2007083">

### ✔️ Expected Behavior

The code execution node can obtain the files variable of DALL-E 3 node

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5346
