### ISSUE TITLE
Text2speech auto play cannot work

### ISSUE THREAD

**Issue by YangXuepei** [langgenius/dify#7620]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

 In the text2speech setting, auto play is switched open. 
Run the workflow or chat-assistant.
The assistant message can not be play automatically.

### ✔️ Expected Behavior

When the auto play is switched open,

**Comment by YangXuepei** [comment]
@dosu I'm using cloud. Thanks a lot but this is not helping : )

**Comment by crazywoola** [comment]
We have several similar issues here. Close as duplicated https://github.com/langgenius/dify/issues/6997

**Comment by YangXuepei** [comment]
@crazywoola On cloud, not self-hosted as #6997 .

**Comment by YangXuepei** [comment]
@takatost
