### ISSUE TITLE
Confront problems when using "Run App" and "Batch Run App"

### ISSUE THREAD

**Issue by athmey** [langgenius/dify#7633]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[configs.zip](https://github.com/user-attachments/files/16743514/configs.zip)
The ".env" file and the "docker-compose.yaml" were attached in the "configs.zip".
Replace the corresponding file in /docker dir to reproduce the issue.

Changes in ".env" file:
EXPOSE_NGINX_PORT=8888  (change from 80 to 8888)

Changes in "docker-compose.yaml":
Change Image source to make docker image accessible in China mainland 

### ✔️ Expected Behavior

![1](https://github.com/user-attachments/assets/faf3e28f-4b1e-40d4-80b7-3aecaafd2007)
![3](https://github.com/user-attachments/assets/1c0cb9d8-d469-453f-81c1-136f568e47fa)
![4](https://github.com/user-attachments/assets/c888651e-a925-4f82-8a09-a1b74b127dc5)

Expecting after click the "Run App" and "Batch Run App", system automatically direct to the url containing the changed port 8888

### ❌ Actual Behavior

![2](https://github.com/user-attachments/assets/5d098f67-edeb-4de3-a4d8-a45b39e5e5d8)
![5](https://github.com/user-attachments/assets/463c15fb-81a3-47ac-bc5f-7e6b8b83d020)

**Comment by crazywoola** [comment]
<img width="809" alt="image" src="https://github.com/user-attachments/assets/fbc05fea-86c2-49b7-b4c4-7cbdf43132c8">
See this https://docs.dify.ai/getting-started/install-self-hosted/environments#app_web_url
