### ISSUE TITLE
is_s3_presigned_url function is faulty

### ISSUE THREAD

**Issue by jiegod** [langgenius/dify#7657]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

this function has bug.     
        def is_s3_presigned_url(url):
                try:
                    parsed_url = urlparse(url)
                    if 'amazonaws.com' not in parsed_url.netloc:
                        return False
                    query_params = parse_qs(parsed_url.query)
                    required_params = ['Signature', 'Expires']
                    for param in required_params:
                        if param not in query_params:
                            return False
                    if not query_params['Expires'][0].isdigit():
                        return False
                    signature = query_params['Signature'][0]
                    if not re.match(r'^[A-Za-z0-9+/]+={0,2}$', signature):
                        return False
                    return True
                except Exception:
                    return False
i change to this will be work. 
            def is_s3_presigned_url(url):
                try:
                    parsed_url = urlparse(url)
                    if 'amazonaws.com' in parsed_url.netloc:
                        return True
                    query_params = parse_qs(parsed_url.query)
                    required_params = ['Signature', 'Expires']
                    for param in required_params:
                        if param not in query_params:
                            return False
                    if not query_params['Expires'][0].isdigit():
                        return False
                    signature = query_params['Signature'][0]
                    if not re.match(r'^[A-Za-z0-9+/]+={0,2}$', signature):
                        return False
                    return True
                except Exception:
                    return False

### ✔️ Expected Behavior

if i use s3 presigned url, i this this function will success but now this return 'URL does not exist'

### ❌ Actual Behavior

normal presigned url will show URL does not exist

**Comment by crazywoola** [comment]
Please use proper markdown syntax to format this code.
