### ISSUE TITLE
Congrats on 0.7.2, would you like to "upgrade" to 0.7.1

### ISSUE THREAD

**Issue by edferr** [langgenius/dify#7671]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

updated from 0.7.1 to 0.7.2 from website docker instructions.
Resulting in this dialog (hopefully the image gets attached to this properly i am new to github bug reports):

![image](https://github.com/user-attachments/assets/31e71a32-28d3-490d-87fb-7f069257b39f)

### ✔️ Expected Behavior

should have said version is 0.7.2 and is the latest

### ❌ Actual Behavior

says i'm on 0.7.2, but advertises i could "upgrade" to 0.7.1. nothing serious, but still something unexpected.

In other notes, GREAT WORK. i use it every day now. THANK YOU!!

**Comment by crazywoola** [comment]
Because we will read the address of the online version, but we have not updated the online version yet, so this will happen, thank you for the feedback ：）
Once we update the Cloud version it will be the v0.7.2.
