### ISSUE TITLE
我要授权dalle3, 但是他却去检测dalle2模型, 我没有dalle2模型

### ISSUE THREAD

**Issue by KamiPasi** [langgenius/dify#7672]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

我要授权dalle3, 但是他却去检测dalle2模型, 我没有dalle2模型只有dalle3模型, 于是我连dalle3都没法用...

### ✔️ Expected Behavior

我要授权dalle3, 但是他却去检测dalle2模型, 我没有dalle2模型只有dalle3模型, 于是我连dalle3都没法用...

### ❌ Actual Behavior

我要授权dalle3, 但是他却去检测dalle2模型, 我没有dalle2模型只有dalle3模型, 于是我连dalle3都没法用...

**Comment by KamiPasi** [comment]
> @KamiPasi Hello there! I'm [Dosu](https://dosu.dev), a bot here to help you with bug reports, questions, and contributions while you wait for a human maintainer.
> 
> 系统通过在模型名称后附加版本标识符来区分不同版本的模型。例如，`dalle2` 和 `dalle3` 是通过名称中的版本号来区分的[[1]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/bedrock/llm/_position.yaml)。
> 
> 请确保在配置文件中正确指定了 `dalle3` 模型的版本。你可以在 **Settings --> Model Providers** 中添加和配置你要使用的 LLM 模型[[2]](https://github.com/langgenius/dify-docs/blob/main/en/guides/model-configuration/README.md)。如果配置正确但仍然出现问题，可能需要检查代码中是否有硬编码的模型名称或版本。
> 
> 如果问题依然存在，建议检查相关的错误处理和日志记录，以确定是否有任何异常情况导致系统错误地检测了 `dalle2` 模型[[3]](https://github.com/langgenius/dify/blob/main/api/services/model_provider_service.py)[[4]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/bedrock/text_embedding/text_embedding.py)[[5]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/localai/rerank/rerank.py)[[6]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/sagemaker/text_embedding/text_embedding.py)。
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

在下图这里无论选择授权dalle2还是授权dalle3, 系统都是会去监测dalle2的可用性, 如果我只有dalle3没有dalle2, 那就会用不了dalle3
![image](https://github.com/user-attachments/assets/0eeb8e66-e938-4a60-9af4-a26dec2342af)
`
Error code: 503 - {'error': {'message': '当前分组 default 下对于模型 dall-e-2 无可用渠道 
`

**Comment by piwawa** [comment]
咋解决啊哥，我甚至跑去 new api 重定向了 dalle2 到 dalle3，结果又报新错误！

![image](https://github.com/user-attachments/assets/b25dc53c-2e79-47eb-8b46-8d9a080cdf47)
