### ISSUE TITLE
Dify - Knowledge Base - Status  Queuing

### ISSUE THREAD

**Issue by PubliBrasil** [langgenius/dify#7675]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I started to encounter problems when uploading any file to the knowledge base to Cloud Dify, manually or via API.
![Captura de Tela 2024-08-26 às 15 39 29](https://github.com/user-attachments/assets/64a50b61-88e4-4285-a698-95fb61bad554)
I checked and found no limitations on the account.
![Captura de Tela 2024-08-26 às 15 41 06](https://github.com/user-attachments/assets/4705ca5c-2af1-4bb4-9821-6dc4adae6f12)

**Comment by PubliBrasil** [comment]
@dosu I have already checked Dify's limits, as shown in the image I sent previously, and they were not reached.
I analyzed the Embedding Model API - Cohere - which is paid - I also did not reach the limit.

**Comment by crazywoola** [comment]
We are currently working on it

**Comment by crazywoola** [comment]
It's resolved now.

**Comment by AoChem** [comment]
<img width="331" height="299" alt="Image" src="https://github.com/user-attachments/assets/63f46a10-8ae3-4af4-91ec-97435bd92f8e" />
Is this issue coming again? I changed the embedding model and still it's in queuing...
