### ISSUE TITLE
Could not add LangFuse (regression of PR #7571)

### ISSUE THREAD

**Issue by CXwudi** [langgenius/dify#7676]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a random App,
2. Go to the Monitoring tab
3. Setup Langfuse

### ✔️ Expected Behavior

Langfuse config should work given the valid secret/public key pairs and the domain.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/6cdd281a-98b4-472a-b1d6-f995a3589f82)

**Comment by CXwudi** [comment]
PR https://github.com/langgenius/dify/pull/7571/ added a new field called `project_key`. However, this is not automatically popped when setting up Langfuse. Hence I believe this is a regression.

**Comment by huangying-just** [comment]
same question occurred.  need to be fixed.

**Comment by gaoyue1989** [comment]
I think this occurred when the front-end API call was made and the "project_key" field was not passed. When I manually invoked the API, it returned success.

**Comment by CXwudi** [comment]
@gaoyue1989 I figured that as well. But I am not sure if the `project_key` should be needed when setting up a brand new LangFuse tracing
