### ISSUE TITLE
Should we add a default value of `MAX_LIFETIME_SECONDS` to the unstructured docker container in docker compose file

### ISSUE THREAD

**Issue by CXwudi** [langgenius/dify#7677]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

If you self-host Unstructured, you might experience memory leak issue from https://github.com/Unstructured-IO/unstructured-api/issues/197

Fortunately, based on the [dev's reply](https://github.com/Unstructured-IO/unstructured-api/issues/197#issuecomment-2311136573) and the [README](https://github.com/Unstructured-IO/unstructured-api?tab=readme-ov-file#controlling-server-life-time). You can set `MAX_LIFETIME_SECONDS` to some value to shut down the server to work around the memory leak issue with `restart=always` docker flag.

Hence, I am wondering, should we add `MAX_LIFETIME_SECONDS` to the docker compose file? If not, maybe shall we mention the memory leak issue in a documentation or a comment in the docker compose file to let the user aware?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
> Hence, I am wondering, should we add MAX_LIFETIME_SECONDS to the docker compose file? If not, maybe shall we mention the memory leak issue in a documentation or a comment in the docker compose file to let the user aware?

Thanks for the suggestion, I will add it later.
