### ISSUE TITLE
Can the tool's input parameters support object inputs?

### ISSUE THREAD

**Issue by haike-1213** [langgenius/dify#7680]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

To enhance the flexibility and usability of our tools, I would like to propose a feature request:
Feature Request: Support Object Parameters for Tool Inputs
Objective: Allow the tool to accept object parameters as inputs, providing more structured and versatile data handling capabilities.
Rationale:
Enhanced Flexibility: Object parameters can encapsulate multiple values and configurations in a single input, making the tool more flexible and adaptable.
Improved Usability: Structured data formats (like JSON objects) are widely used and understood, making it easier for users to interact with the tool.
Better Data Management: Objects can provide a clear structure for input data, improving data management and reducing errors.
Implementation Details:
Object Structure Definition:
Define the required properties and their data types within the object.
Provide clear documentation on the expected object structure.
Documentation Update:
Update the tool's documentation to include details about the supported object parameters.
Include examples demonstrating how to use object parameters effectively.
Error Handling:
Implement robust error handling mechanisms to handle invalid or missing properties.
Provide clear error messages to guide users in correcting issues.
Testing:
Develop comprehensive unit tests to ensure the tool functions correctly with object parameters.
Test edge cases and error conditions to validate robustness.
Example Usage:
{
  "name": "John Doe",
  "age": 30,
  "preferences": {
    "language": "English",
    "theme": "Dark"
  }
}

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
There is a pr for this already https://github.com/langgenius/dify/pull/6845

**Comment by itzhoujun** [comment]
Hi, the pr is closed. would you reopen this issue?

> There is a pr for this already [#6845](https://github.com/langgenius/dify/pull/6845)

**Comment by Seelly** [comment]
@crazywoola so，did the problem solved?
