### ISSUE TITLE
前端使用nextjs ,在开发环境编译相当慢 ,比便秘还让人痛苦 ,你们有什么办法

### ISSUE THREAD

**Issue by yu99233** [langgenius/dify#7685]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

前端使用nextjs ,在开发环境编译相当慢 ,比便秘还让人痛苦 ,你们有什么办法解决开发环境相当慢的问题 ,编译至少要等10分钟以上才能出现页面

**Comment by nadirvishun** [comment]
I'm also having this problem and I'm crushed!
