### ISSUE TITLE
The front-end uses nextjs, and the compilation in the development environment is very slow. It is more painful than constipation. What can you do?

### ISSUE THREAD

**Issue by yu99233** [langgenius/dify#7686]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

The front-end uses nextjs, and compilation in the development environment is very slow. It is more painful than constipation. Do you have any solutions to the problem that the development environment is very slow? It takes at least 10 minutes for the page to appear after compilation.

**Comment by crazywoola** [comment]
Yes, you are right, it's painful. However it seems less then 1mins to me for each page. I think this is tolerable. Just grab a cup of tea and have some rest. :)

**Comment by haiminovo** [comment]
> Yes, you are right, it's painful. However it seems less then 1mins to me for each page. I think this is tolerable. Just grab a cup of tea and have some rest. :)

Yeah, you're right. I drank all the water in the Pacific, and it finally took effect.
