### ISSUE TITLE
Occasional errors occur in the dify-sandbox

### ISSUE THREAD

**Issue by yuxizhe** [langgenius/dify#7687]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After deploying with Docker, the sandbox (docker 0.2.6) occasionally reports errors, with a probability of about 0.4%.

for example:
- Run failed: Node checkxx stringfiy run failed: 20.11.1\ndbox-afd80081-4a6b-4ab6-82c6-31079c52bedc/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/node_modules/koffi/index.js:562\n  let lib = load(...args);\n            ^\n\nError: Failed to load shared library: cannot open shared object file: No such file or directory\n    at module.exports.load (/tmp/sandbox-afd80081-4a6b-4ab6-82c6-31079c52bedc/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/node_modules/koffi/index.js:562:13)\n    at Object.<anonymous> (/tmp/sandbox-afd80081-4a6b-4ab6-82c6-31079c52bedc/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/test.js:4:19)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.11.1\nerror: exit status 1\n

- Run failed: Node xx run failed: 20.11.1\ndbox-2427c7e1-d57a-45dc-8519-d987dd8f5006/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/node_modules/koffi/index.js:562\n  let lib = load(...args);\n            ^\n\nError: Failed to load shared library: cannot open shared object file: No such file or directory\n    at module.exports.load (/tmp/sandbox-2427c7e1-d57a-45dc-8519-d987dd8f5006/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/node_modules/koffi/index.js:562:13)\n    at Object.<anonymous> (/tmp/sandbox-2427c7e1-d57a-45dc-8519-d987dd8f5006/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/test.js:4:19)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.11.1\nerror: exit status 1\n

- Run failed: Node xxx run failed: Failed to invoke tool: Node xxx run failed: Traceback (most recent call last):\n  File \"/var/sandbox/sandbox-python/tmp/a6b19d1f_17ba_4ed8_8c40_9870b5adacc4.py\", line 13, in <module>\n    lib = ctypes.CDLL(\"./var/sandbox/sandbox-python/[python.so](http://python.so/)\")\n  File \"/usr/local/lib/python3.10/ctypes/__init__.py\", line 374, in __init__\n    self._handle = _dlopen(self._name, mode)\nOSError: ./var/sandbox/sandbox-python/[python.so](http://python.so/): cannot open shared object file: No such file or directory\nerror: exit status 255\n

### ✔️ Expected Behavior

Operates normally.

### ❌ Actual Behavior

sandbox occasionally reports errors, with a probability of about 0.4%.

**Comment by crazywoola** [comment]
This is because it can not locate some required deps `.so` files.

See FAQ here https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md

Duplicated https://github.com/langgenius/dify/issues/7448

**Comment by yuxizhe** [comment]
> This is because it can not locate some required deps `.so` files.
> 
> See FAQ here https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md
> 
> Duplicated #7448

@crazywoola Thanks a lot.  But I am using the Docker version of dify-sandbox, but the FAQ covers the locally deployed version. How can I resolve this issue with the Docker version?

**Comment by Cuihongsen** [comment]
```
Run failed: Node xxx run failed: Failed to invoke tool: Node xxx run failed: Traceback (most recent call last):
 File "/var/sandbox/sandbox-python/tmp/a6b19d1f_17ba_4ed8_8c40_9870b5adacc4.py", line 13, in 
 lib = ctypes.CDLL("./var/sandbox/sandbox-python/python.so")
 File "/usr/local/lib/python3.10/ctypes/init.py", line 374, in init
 self._handle = _dlopen(self._name, mode)
OSError: ./var/sandbox/sandbox-python/python.so: cannot open shared object file: No such file or directory
error: exit status 255
```

I am experiencing the same issue intermittently. The bug seems to originate from the template component and appears to be an inherent issue.  Unfortunately, the existing FAQs do not offer a viable solution.

**Comment by Yeuoly** [comment]
Fixed https://github.com/langgenius/dify-sandbox/pull/63
