### ISSUE TITLE
A breaking change, Output variable length limit of workflow Code Node

### ISSUE THREAD

**Issue by cherry0411** [langgenius/dify#7688]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgrade to 0.7.2, If Code Node results an string variable that longer than 30 characters, it will cause an error:  The length of output variable res must be less than 30 characters. In my most use cases 30 characters is not very enough, like image path extract, construct prom
![issues_3](https://github.com/user-attachments/assets/562e07fd-3f59-41a2-a9ce-e813f51dde2a)
pt, etc. So may I ask why we should have this limit?

### ✔️ Expected Behavior

String output variable should have longer limit, like 1000.

### ❌ Actual Behavior

Node report an error.

**Comment by crazywoola** [comment]
Already fixed in https://github.com/langgenius/dify/pull/7683
