### ISSUE TITLE
Output Variable Length Restriction Causing Workflow Failures After Latest Version Upgrade

### ISSUE THREAD

**Issue by neotize** [langgenius/dify#7689]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgrading to the latest version, we have encountered an issue where the "Code" module now imposes a strict limit on the length of output variables. This new restriction has caused several workflows, which were created in the previous versions, to fail during execution.

Error Message:
`Run failed: Node 代码执行 run failed: The length of output variable recommendTaskText must be less than 30 characters
Impact:`

Existing workflows that were functioning correctly in previous versions are now unable to run successfully due to this new limitation.
The sudden enforcement of this restriction disrupts operations, requiring potentially extensive modifications to existing workflows to comply with the new constraints.

### ✔️ Expected Behavior

The "Code" module should ideally allow workflows created in previous versions to execute without errors, maintaining backward compatibility.

### ❌ Actual Behavior

- Upon executing workflows that were built in previous versions, the system throws an error when the output variable length exceeds the newly imposed limit of 30 characters.
- The workflows that previously executed successfully are now failing, halting automated processes and requiring manual intervention.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/7688 Already fixed in https://github.com/langgenius/dify/pull/7683
