### ISSUE TITLE
Login succeeded, but redirect failed, Err code 401

### ISSUE THREAD

**Issue by conghaoyuan** [langgenius/dify#769]
### deploy：
**docker：**

- nginx
- web
- postgres
- redis
- weaviate

and deploy `api` service  locally.
```
cd dify/api
........
flask run --host 0.0.0.0 --port 5001 --debug
```

### run

<img width="1203" alt="image" src="https://github.com/langgenius/dify/assets/12544104/4098c25e-158b-49ec-9ef4-6c9ed2f6d9e3">

and login succeeded, redirect failed .

<img width="615" alt="image" src="https://github.com/langgenius/dify/assets/12544104/c4dd7704-6daf-4641-ba4f-b5572f742473">

**Comment by conghaoyuan** [comment]
COOKIE_HTTPONLY=true
COOKIE_SAMESITE=Lax
COOKIE_SECURE=false

resolved

**Comment by conghaoyuan** [comment]
resolved

**Comment by weirhp** [comment]
> COOKIE_HTTPONLY=true COOKIE_SAMESITE=Lax COOKIE_SECURE=false
> 
> resolved

where add the config  ?

**Comment by conghaoyuan** [comment]
> 
copy .env.example to .env
set the parameter in .env file

**Comment by linphy** [comment]
why?
