### ISSUE TITLE
E: Version '2.5.18+dfsg-2' for 'libldap-2.5-0' was not found

### ISSUE THREAD

**Issue by imdevopx** [langgenius/dify#7691]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker build --file api-Dockerfile --tags dify-api:v0.7.1 .

### ✔️ Expected Behavior

successful build

### ❌ Actual Behavior

unsuccessful build. E: Version '2.5.18+dfsg-2' for 'libldap-2.5-0' was not found

**Comment by crazywoola** [comment]
We can not reproduce this as it's already v0.7.2.

Maybe you can provide more details.

**Comment by imdevopx** [comment]
@crazywoola hmmm i even manually installed in on my ubuntu 22 server.. and still not found, however i tried to remove the specific version and seems it is working now.
<img width="650" alt="image" src="https://github.com/user-attachments/assets/d40aa553-48b0-463a-b7bb-d5b89b9ef419">

**Comment by crazywoola** [comment]
I guess it's resolved?

**Comment by imdevopx** [comment]
yes, but yeah i tried @dosu suggestions and works. not sure why you guys can still install that specific version and mine won't. it doesn't matter if i have different libldap-2.5-0 version? seems mine is 2.5.18+dfsg-0ubuntu0.22.04.2.

**Comment by jhlia0** [comment]
Update to libldap-2.5-0=2.5.18+dfsg-3 can solve this problem.

https://packages.debian.org/zh-cn/testing/libldap-dev

**Comment by imdevopx** [comment]
seems working fine on my end now.. thank you all
