### ISSUE TITLE
How to migrate data from version 0.6.9 to system 0.7.0

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#7712]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

How to migrate data from version 0.6.9 to system 0.7.0

**Comment by 401557122** [comment]
I need to migrate data, but the data table structure is different in these two versions. I copied the volume directly and encountered an error when starting @dosu

**Comment by 401557122** [comment]
I changed the account password in env, how to change it in volume @dosu.

**Comment by 401557122** [comment]
Including the account password for Postgres, the volume I migrated seems to have a password, but the new version of env wants to change it @dosu.

**Comment by crazywoola** [comment]
Please use Discussion for asking help. This is a template for issue report.
