### ISSUE TITLE
"Internal Server Error" on Dify Cloud Pro account multiple times today, making it not possible to use account

### ISSUE THREAD

**Issue by CodingDane** [langgenius/dify#7713]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Issue happened after uploading files to Knowledge through API earlier today. 

### ✔️ Expected Behavior

Knowledge being uploaded and vectorized.

### ❌ Actual Behavior

![Screenshot 2024-08-27 at 19 28 12](https://github.com/user-attachments/assets/c9ffae06-818a-48e0-9905-271c242af41f)

After doing the above, multiple times during today, I have been unable to use my account. Even now, I cannot use my account.
Experiencing the following issues:

- Cannot use the chatbots (even through API access)
- Knowledge tab disappeared
- Plan is shown as Sandbox (even though I have the Professional plan)

**Comment by CodingDane** [comment]
The database limits being exceeded might be the issue. 
But I cannot access the knowledge tab to delete the excess knowledges, because the account is reverted to Sandbox.

**Comment by CodingDane** [comment]
(update) As of this morning (JST), the account is still reverted from PRO to sandbox, and we still cannot use the chatbots even when accessing through the API.

**Comment by crazywoola** [comment]
What's your current plan?

**Comment by CodingDane** [comment]
Sorry for the very late response.
I am using the PRO plan. 
However, I was able to access the knowledge tab, and delete the excess knowledges.
This fixed the issue, which I then assume happened because of uploading excess knowledge for indexing via the API.

Thank you for your response!
