### ISSUE TITLE
 [WinError 10053] An established connection was aborted by the software in your host machine 

### ISSUE THREAD

**Issue by Yaghnesh** [langgenius/dify#7716]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When trying to upload a large document into knowledge base it is throwing an error that  [WinError 10053] An established connection was aborted by the software in your host machine.

A bit Larger document is  divided into chunks and trying to upload the embeddings it into qdrant vector DB .
It is processing only a limited amount of chunks and after that it is throwing this error. Here in this case the whole document is divided into around 383 chunks it is working fine for upto 350 chunks after that it is halting the process and throwing this error
![Screenshot 2024-08-27 171043](https://github.com/user-attachments/assets/8c5543af-b9c7-45f8-a759-ef96a579ce10)
![Screenshot 2024-08-27 171120](https://github.com/user-attachments/assets/a17323c1-bd0a-40bc-b3be-0b69f1d01205)
 

### ✔️ Expected Behavior

To upload all chunks into qdrant DB without any issue.

### ❌ Actual Behavior

Halting before complete upload of the document.

**Comment by Yaghnesh** [comment]
I have tried changing the timeout settings but  it is again throwing the same error. Is there any other way to resolve this issue?

**Comment by Yaghnesh** [comment]
I was not using docker set up. I was using the local set up of dify. Now, help me solve this error 
[WinError 10053] An established connection was aborted by the software in your host machine

**Comment by Yaghnesh** [comment]
@dosu I tried all the above mentioned steps but i was facing the same issue again and again

**Comment by Yaghnesh** [comment]
Hi, I was still facing this issue even after updating timeout variable and reducing chunk size. can you help me in this?

**Comment by crazywoola** [comment]
https://stackoverflow.com/questions/51562067/connectionabortederror-winerror-10053-an-established-connection-was-aborted-b
