### ISSUE TITLE
use dataset api add segment to slowly

### ISSUE THREAD

**Issue by kenneth-bro** [langgenius/dify#7717]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use a data set API to write code to edit the knowledge base, so that the upload is too slow. 20 texts were uploaded for a while, so it was impossible to use API for business data for data set maintenance. DIFY-API and DIFY-works have no error.

### ✔️ Expected Behavior

fast and correct to put segment to document

**Comment by crazywoola** [comment]
What LLM model and Embedding Model are you using?

**Comment by kenneth-bro** [comment]
> What LLM model and Embedding Model are you using?

beg-large-zh-v1.5, use xinference build, other system is not problem.

**Comment by fedecompa** [comment]
In the 0.7.3 version of Dify the following API gives 404, indeed there is no the batch_import API in the documentation. 

curl --location --request POST 'https://api.dify.ai/v1/datasets/{dataset_id}/documents/{document_id}/segments/batch_import' \
--header 'Authorization: Bearer {api_key}' \
--form 'file=@/path/to/your/file.csv'
