### ISSUE TITLE
Full-text entry support for the knowledge base rather than being divided into several paragraphs

### ISSUE THREAD

**Issue by jiaqianjing** [langgenius/dify#7720]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

 have many articles, but none of them are too long, about more than 1,000 characters. However, I hope they can be retrieved separately instead of being split into several fragments. Because they are all independently and identically distributed. And the current model context has long supported characters at the million-level. There is no need to limit it so strictly (no more than 1,000 for each paragraph). This is very inconvenient and will bring errors, because the retrieved things may be omitted or pieces of different articles may be spliced together, which is not allowed.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Weaxs** [comment]
I thought you do not want Chinese text  segmentation ?

If 1,000 characters are Chinese and use Qdrant as vector db, maybe you can try the follow solution:

1.  User Qdrant official Image like [qdrant/qdrant](https://hub.docker.com/r/qdrant/qdrant), not dify Qdrant [langgenius/qdrant](https://hub.docker.com/r/langgenius/qdrant). Official Qdrant do not support Chinese text segmentation. 

2. Maybe you can update full-text index after create knowledge by Dify ? —— not recommend


![image](https://github.com/user-attachments/assets/3b9556f6-19d2-4798-93db-2c921cfb4a56)
![image](https://github.com/user-attachments/assets/62918aba-49ae-409d-b6ec-2895831cf4a0)

**Comment by jiaqianjing** [comment]
> I thought you do not want Chinese text segmentation ?我以为您不想进行中文文本分词？
> 
> If 1,000 characters are Chinese and use Qdrant as vector db, maybe you can try the follow solution:
> 
> 1. User Qdrant official Image like [qdrant/qdrant](https://hub.docker.com/r/qdrant/qdrant), not dify Qdrant [langgenius/qdrant](https://hub.docker.com/r/langgenius/qdrant). Official Qdrant do not support Chinese text segmentation.用户 Qdrant 官方图片如[qdrant/qdrant](https://hub.docker.com/r/qdrant/qdrant)，非 dify Qdrant [langgenius/qdrant](https://hub.docker.com/r/langgenius/qdrant)。官方 Qdrant 不支持中文文本分词。
> 2. Maybe you can update full-text index after create knowledge by Dify ? —— not recommend
> 
> ![image](https://private-user-images.githubusercontent.com/20680212/362101815-3b9556f6-19d2-4798-93db-2c921cfb4a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzI0MTUsIm5iZiI6MTcyNTAzMjExNSwicGF0aCI6Ii8yMDY4MDIxMi8zNjIxMDE4MTUtM2I5NTU2ZjYtMTlkMi00Nzk4LTkzZGItMmM5MjFjZmI0YTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE1MzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZTliNzc1M2E1YzNmNzQzOGM2OGM1Nzc2ODgxYTBjZTMzYzEwZmMwZmIxY2JkM2E0ZDFkNDQ0OGY5ZTZkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DtRMLmbZq7OqHfyG4VysMzerFH-LJhWvjUMjMPX6x7M) ![image](https://private-user-images.githubusercontent.com/20680212/362101958-62918aba-49ae-409d-b6ec-2895831cf4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzI0MTUsIm5iZiI6MTcyNTAzMjExNSwicGF0aCI6Ii8yMDY4MDIxMi8zNjIxMDE5NTgtNjI5MThhYmEtNDlhZS00MDlkLWI2ZWMtMjg5NTgzMWNmNGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE1MzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZmUyOTZjZDRiN2ViOTFmNTFiOGZjNzVkYmUwOTlkNTE5N2IzMDA5YzlmMjUzYWJiYTVlZGZhODJiMTljMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DlQUEItUHGkBWNovTphW1uK3ZzT3nQUTLwsEt3N-p-E)

First of all, thank you very much for your reply. I really don't want my Chinese documents to be segmented. I want the whole document to be retrieved and used as context, along with the prompt as an input to LLM. At the moment I think the easiest way to do this would be to relax the 1000 limit, say to 5000. I haven't looked at the dify implementation, and I don't know what the reason is for this limit.
<img width="656" alt="image" src="https://github.com/user-attachments/assets/2d6d7b51-d2c9-461b-ae01-f87b6d696c9e">

**Comment by Weaxs** [comment]
> > I thought you do not want Chinese text segmentation ?我以为您不想进行中文文本分词？
> > If 1,000 characters are Chinese and use Qdrant as vector db, maybe you can try the follow solution:
> > 
> > 1. User Qdrant official Image like [qdrant/qdrant](https://hub.docker.com/r/qdrant/qdrant), not dify Qdrant [langgenius/qdrant](https://hub.docker.com/r/langgenius/qdrant). Official Qdrant do not support Chinese text segmentation.用户 Qdrant 官方图片如[qdrant/qdrant](https://hub.docker.com/r/qdrant/qdrant)，非 dify Qdrant [langgenius/qdrant](https://hub.docker.com/r/langgenius/qdrant)。官方 Qdrant 不支持中文文本分词。
> > 2. Maybe you can update full-text index after create knowledge by Dify ? —— not recommend
> > 
> > ![image](https://private-user-images.githubusercontent.com/20680212/362101815-3b9556f6-19d2-4798-93db-2c921cfb4a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzI0MTUsIm5iZiI6MTcyNTAzMjExNSwicGF0aCI6Ii8yMDY4MDIxMi8zNjIxMDE4MTUtM2I5NTU2ZjYtMTlkMi00Nzk4LTkzZGItMmM5MjFjZmI0YTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE1MzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZTliNzc1M2E1YzNmNzQzOGM2OGM1Nzc2ODgxYTBjZTMzYzEwZmMwZmIxY2JkM2E0ZDFkNDQ0OGY5ZTZkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DtRMLmbZq7OqHfyG4VysMzerFH-LJhWvjUMjMPX6x7M) ![image](https://private-user-images.githubusercontent.com/20680212/362101958-62918aba-49ae-409d-b6ec-2895831cf4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzI0MTUsIm5iZiI6MTcyNTAzMjExNSwicGF0aCI6Ii8yMDY4MDIxMi8zNjIxMDE5NTgtNjI5MThhYmEtNDlhZS00MDlkLWI2ZWMtMjg5NTgzMWNmNGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE1MzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZmUyOTZjZDRiN2ViOTFmNTFiOGZjNzVkYmUwOTlkNTE5N2IzMDA5YzlmMjUzYWJiYTVlZGZhODJiMTljMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DlQUEItUHGkBWNovTphW1uK3ZzT3nQUTLwsEt3N-p-E)
> 
> First of all, thank you very much for your reply. I really don't want my Chinese documents to be segmented. I want the whole document to be retrieved and used as context, along with the prompt as an input to LLM. At the moment I think the easiest way to do this would be to relax the 1000 limit, say to 5000. I haven't looked at the dify implementation, and I don't know what the reason is for this limit. <img alt="image" width="656" src="https://private-user-images.githubusercontent.com/16071449/363243792-2d6d7b51-d2c9-461b-ae01-f87b6d696c9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDYwNzQsIm5iZiI6MTcyNTI0NTc3NCwicGF0aCI6Ii8xNjA3MTQ0OS8zNjMyNDM3OTItMmQ2ZDdiNTEtZDJjOS00NjFiLWFlMDEtZjg3YjZkNjk2YzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAyNTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTA4M2M3MWM1MDJkOGE5OWFkYmMzNjIwN2NjYjY2OTYzOGFlZjBiMmMyY2YwMmUzY2U2MjhhNjdmMjQwNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMUthEJDPB2CyW6uL10sYsqDMij5W05RRea6ONR4Qi8">

oh, sorry I misunderstood before.

If you want to change max segement tokens length for self-host dify, you can set `INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH`  in .env, like:

```
INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH=5000
```

If you use dify cloud, hmmmm.. maybe ask for @takatost

**Comment by Weaxs** [comment]
@jiaqianjing you use in cloud or self host ?

**Comment by jiaqianjing** [comment]
dify cloud @Weaxs

**Comment by Weaxs** [comment]
> dify cloud @Weaxs

`INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH` in dify cloud has raised to 4000 tokens already.

but maybe have no plan to raise to 5000 tokens I gusses...

![image](https://github.com/user-attachments/assets/9e366d50-f2ca-4fbc-ae7c-bcd3e8eaa8a6)
