### ISSUE TITLE
Set Maximum chunk length to be more than 500 in self hosted version

### ISSUE THREAD

**Issue by iray1991** [langgenius/dify#7722]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Dify 0.7.0 

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

how to Set Maximum chunk length to be more than 500 in self hosted version?

### ✔️ Expected Behavior

how to Set Maximum chunk length to be more than 500 in self hosted version?

### ❌ Actual Behavior

how to Set Maximum chunk length to be more than 500 in self hosted version?

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/85fc0fdb51e38c1c9efae0d3556393b098d64853/docker/.env.example#L502-L503
