### ISSUE TITLE
开场白的apikey 生成方式是什么，会不会过期？

### ISSUE THREAD

**Issue by haike-1213** [langgenius/dify#7729]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

开场白的apikey 生成方式是什么，会不会过期？

**Comment by haike-1213** [comment]
/api/parameters  里面的 authorization 会过期吗？

**Comment by crazywoola** [comment]
I confirm that I am using English to submit report (我已阅读并同意 https://github.com/langgenius/dify/issues/1542).

**Comment by crazywoola** [comment]
你好，提问之前请查看我们相关的语言政策，为了更好的交流请使用英语并且使用相应的模版进行提交，有疑问可以使用 Discussion，我注意到你这边已经多次违反我们的语言政策，如果后续还是不遵守我们相关政策，我们会进行相关封禁处理。
