### ISSUE TITLE
The length of output variable `kb_content` must be less than 30 characters 

### ISSUE THREAD

**Issue by Thinking80s** [langgenius/dify#7732]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The length of output variable `kb_content` must be less than 30 characters 

### ✔️ Expected Behavior

The length of output variable `kb_content` must be less than 30 characters 

### ❌ Actual Behavior

The length of output variable `kb_content` must be less than 30 characters

**Comment by crazywoola** [comment]
Duplicated, we already fixed this yesterday in this PR https://github.com/langgenius/dify/pull/7683
