### ISSUE TITLE
Add support for custom Q&A in the knowledge base

### ISSUE THREAD

**Issue by AAEE86** [langgenius/dify#7735]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need to import some Q&A content that has been identified, but I can only switch to Q&A form through Dify, which will cause a difference from the Q&A content I provided, and I also need to manually edit and rebuild, I hope this can be improved.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can create a blank dataset with Q&A enabled, then you can upload custom Q&A pairs through API, this is the only way to do it at this moment.

**Comment by AAEE86** [comment]
> You can create a blank dataset with Q&A enabled, then you can upload custom Q&A pairs through API, this is the only way to do it at this moment.

I am aware. I still maintain the anticipation that this function be taken into consideration.

**Comment by AAEE86** [comment]
> You can create a blank dataset with Q&A enabled, then you can upload custom Q&A pairs through API, this is the only way to do it at this moment.

And to create a Q&A type knowledge base, I must first import some files and then convert it to the Q&A mode.

Please support the creation of empty Q&A documents .

**Comment by nhha1602** [comment]
I also care about this. One more thing, the GENERATOR_QA_PROMPT is fixed.
Please help to show me the way to create prompt for each of Document or each of Data set ?
