### ISSUE TITLE
Add display of historical Retrieval Testing results

### ISSUE THREAD

**Issue by AAEE86** [langgenius/dify#7736]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently Retrieval Testing can display Recents but not record historical Retrieval Testing results, hopefully this feature can be enhanced.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Can you describe why you need to retrieve all this historical results?

**Comment by AAEE86** [comment]
> Can you describe why you need to retrieve all this historical results?

It is convenient to check the relevance of the knowledge base in the user's historical sessions for improving the knowledge base.
