### ISSUE TITLE
Code block max result length 30

### ISSUE THREAD

**Issue by BrianAndersen78** [langgenius/dify#7737]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use the code block with python code, to return a string value longer than 30 chars. Choose "String" as return type.

I think you have mixed up the use of env vars in your code. 

When changing env var in docker-compose.yaml: CODE_MAX_STRING_LENGTH: 80000
My return is still limited to 30

When i change CODE_MAX_STRING_ARRAY_LENGTH: 80000
My return is limited to 80000  

### ✔️ Expected Behavior

CODE_MAX_STRING_LENGTH to modify the allowed length of returned string 

### ❌ Actual Behavior

CODE_MAX_STRING_ARRAY_LENGTH modifies the length of return string.

**Comment by crazywoola** [comment]
Duplicated, we already fixed this yesterday in this PR https://github.com/langgenius/dify/pull/7683

In the meantime you could downgrade to v0.7.1. We will release this fix in v0.7.3
