### ISSUE TITLE
Json file as dataset

### ISSUE THREAD

**Issue by arash-bizcover** [langgenius/dify#774]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that currently, there is only a Text loader available. I'm always frustrated when I cannot load datasets in JSON format which is essential for real-life applications.

**Describe the solution you'd like**
I would like a JSON loader to be added to Dify, enabling users to easily load datasets in JSON format.

**Describe alternatives you've considered**
One could consider converting their JSON datasets to text format for compatibility with the current Text loader, but this is not efficient or practical for real-life use cases.

**Additional context**
The inclusion of a JSON loader will make Dify more versatile and cater to a wider range of dataset formats, hence making it more relevant for real-life applications.

---

**Comment by arash-bizcover** [comment]
@crazywoola bro, text is not an option, What is needed is a JSON loader.
putting big json files as text will cause them to be split into different Documents and the json structure gets corrupted.

**Comment by crazywoola** [comment]
We have support load data from external api. I think this issue can be closed.
https://docs.dify.ai/advanced/api_based_extension
