### ISSUE TITLE
need to upgrade cohere sdk version

### ISSUE THREAD

**Issue by mingu-song** [langgenius/dify#7743]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I tested a large pdf file with cohere embedding.

### ✔️ Expected Behavior

no error

### ❌ Actual Behavior

cohere server error (500)

So, I ask to the Cohere development team and was advised to use the latest SDK version. 
However, since the current Dify source cannot accommodate the latest version, modifications are needed on the provider side.

**Comment by crazywoola** [comment]
You could submit a PR for this :)
