### ISSUE TITLE
Button link does not include the port

### ISSUE THREAD

**Issue by Allamss** [langgenius/dify#7761]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

code: /web/app/components/app/app-publisher/index.tsx#190 appURL

env EXPOSE_NGINX_PORT 8082
and link of workflow `Run App` buttom does not include the port 8082
![image](https://github.com/user-attachments/assets/56da721d-1bf3-44f6-a340-2a904b9f987f)
![image](https://github.com/user-attachments/assets/29f6de61-aa51-42a1-a8bf-967e7f2bb837)
![image](https://github.com/user-attachments/assets/813edb62-a527-4f85-8298-0e4931107ec4)

### ✔️ Expected Behavior

The link supports the port for correct navigation

### ❌ Actual Behavior

wrong navigation

**Comment by AAEE86** [comment]
You need to configure it in the .env file.

**Comment by AAEE86** [comment]
You'd better change all URIs in Common Variables to yours.
