### ISSUE TITLE
Sort tools alphabetically 

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#7766]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The build-in tools should be sorted alphabetically as in the add node in the workflow:
![Screenshot 2024-08-28 at 8 37 57 AM](https://github.com/user-attachments/assets/9b88a2ee-da07-4ca7-8b38-faf91a6d3c74)

![Screenshot 2024-08-28 at 8 47 31 AM](https://github.com/user-attachments/assets/182b66c4-8dfc-4eee-a886-37d9cff999c8)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by harrywang** [comment]
@faye1225

**Comment by Sakura4036** [comment]
It would be nice to have sorting options, such as name and creation time, etc.
