### ISSUE TITLE
Enable Conversion Between Workflow and Chatflow in Dify without Compatibility Issues

### ISSUE THREAD

**Issue by cubxxw** [langgenius/dify#7772]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, Dify allows users to modify the type of a flow between Workflow and Chatflow using the DSL format. While this modification allows the flow to function correctly within Dify, it seems to cause compatibility issues with API calls. Specifically, when switching a flow’s type from Workflow to Chatflow (or vice versa), the API interactions do not fully align, leading to potential issues when invoking Dify’s APIs or third-party monitoring APIs.

### 2. Additional context or comments

**Steps to Reproduce:**

1. Create a Workflow in Dify using the DSL format.
2. Convert the Workflow to a Chatflow by modifying the type in the DSL.
3. Attempt to use Dify's API or a third-party monitoring API with the modified flow.
4. Observe any compatibility issues or errors that arise.

**Expected Behavior:**

When converting between Workflow and Chatflow, the flow should be fully compatible with Dify's API and any third-party APIs without requiring additional adjustments.

**Actual Behavior:**

Although the converted flow works within Dify, there are compatibility issues with API calls, leading to potential errors or unexpected behavior.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by lachinhan** [comment]
Thanks . I changed the Mode to mode: advanced-chat . And it's Done
