### ISSUE TITLE
0.7.2 CODE_MAX_STRING_ARRAY_LENGTH Implementation does not meet expectations

### ISSUE THREAD

**Issue by qkzsky** [langgenius/dify#7773]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![5201724875220_ pic](https://github.com/user-attachments/assets/48815e90-8eae-48dd-90b7-fef866df3a68)

The modification here adjusts the logic originally used to determine the length of the array to determine the length of the value in the array
This does not meet the expectations of the CODE_MAX_STRING_ARRAY_LENGTH configuration item and will result in an error when processing array values greater than 30 characters. I hope the development team members recheck the merge and fix this issue

**Comment by crazywoola** [comment]
We already fixed this yesterday in this PR https://github.com/langgenius/dify/pull/7683

In the meantime you could downgrade to v0.7.1. We will release this fix in v0.7.3

You can define this variable in docker/.env
