### ISSUE TITLE
Code Node Runs Successfully but Output does not show up in End Node

### ISSUE THREAD

**Issue by kingdavidph** [langgenius/dify#7789]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/291c96d5-0f4e-406b-82a9-43a507407ab7)

Input:
{
  "arg1": "{\"filename\": \"20240829_123714_painters_resumes_7447e9f0.csv\", \"response\": \"Found 186 matching records for 'painters'.\"}"
}

Code Node:
import json
import os

def main(arg1):
    def parse_text_string(input_string):
        try:
            input_data = json.loads(input_string)
            text_json = json.loads(input_data['arg1'])
            return text_json['filename'], text_json['response']
        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"Error parsing: {e}")  # For debugging
            return '', ''

    # Parse the input
    filename, response = parse_text_string(arg1)

    # Method 1: Set as global variables
    globals()['filename'] = filename
    globals()['response'] = response

    # Method 2: Set as environment variables
    os.environ['filename'] = filename
    os.environ['response'] = response

    # Method 3: Print in a specific format that the system might recognize
    print(f"OUTPUT_filename={filename}")
    print(f"OUTPUT_response={response}")

    # Method 4: Return as a dictionary
    return {
        "filename": filename,
        "response": response
    }

# Method 5: Set variables outside the main function
filename = ''
response = ''

End Node:
![image](https://github.com/user-attachments/assets/918ca725-8bbf-4b57-a41d-6322c8946b93)

Successful run in the individual code node:
![image](https://github.com/user-attachments/assets/ab89e177-aa73-41aa-b5a7-c44f88642666)

Tracing for Code Node:
Input:
{
  "arg1": "{\"filename\": \"20240829_123714_painters_resumes_7447e9f0.csv\", \"response\": \"Found 186 matching records for 'painters'.\"}"
}
Output:
{
  "filename": "",
  "response": ""
}

![image](https://github.com/user-attachments/assets/8f581b5d-2cf9-44fb-b0ee-353ec613072b)

I dont understand why this is happening, the code node runs perfectly individually however the output variables are not making it to the end node.

### ✔️ Expected Behavior

End Node should have the correct output.
![image](https://github.com/user-attachments/assets/65ee0f0e-6415-4e32-b33f-4e5c89e3825c)

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/291c96d5-0f4e-406b-82a9-43a507407ab7)

Input:
{
  "arg1": "{\"filename\": \"20240829_123714_painters_resumes_7447e9f0.csv\", \"response\": \"Found 186 matching records for 'painters'.\"}"
}

Code Node:
import json
import os

def main(arg1):
    def parse_text_string(input_string):
        try:
            input_data = json.loads(input_string)
            text_json = json.loads(input_data['arg1'])
            return text_json['filename'], text_json['response']
        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"Error parsing: {e}")  # For debugging
            return '', ''

    # Parse the input
    filename, response = parse_text_string(arg1)

    # Method 1: Set as global variables
    globals()['filename'] = filename
    globals()['response'] = response

    # Method 2: Set as environment variables
    os.environ['filename'] = filename
    os.environ['response'] = response

    # Method 3: Print in a specific format that the system might recognize
    print(f"OUTPUT_filename={filename}")
    print(f"OUTPUT_response={response}")

    # Method 4: Return as a dictionary
    return {
        "filename": filename,
        "response": response
    }

# Method 5: Set variables outside the main function
filename = ''
response = ''

End Node:
![image](https://github.com/user-attachments/assets/918ca725-8bbf-4b57-a41d-6322c8946b93)

Successful run in the individual code node:
![image](https://github.com/user-attachments/assets/ab89e177-aa73-41aa-b5a7-c44f88642666)

Tracing for Code Node:
Input:
{
  "arg1": "{\"filename\": \"20240829_123714_painters_resumes_7447e9f0.csv\", \"response\": \"Found 186 matching records for 'painters'.\"}"
}
Output:
{
  "filename": "",
  "response": ""
}

![image](https://github.com/user-attachments/assets/8f581b5d-2cf9-44fb-b0ee-353ec613072b)

**Comment by kingdavidph** [comment]
@dosu I upgrade to 0.7.2. Had to rebuild everything.

- Code Node is working but I had to limit the response and the filename strings on the API to be 30 characters or less.
- End Node still doesn't show the results.

Code Used (used yours):
`def main(arg1):
    def parse_text_string(input_string):
        try:
            input_data = json.loads(input_string)
            text_json = json.loads(input_data['arg1'])
            return text_json['filename'], text_json['response']
        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"Error parsing: {e}")  # For debugging
            return '', ''

    # Parse the input
    filename, response = parse_text_string(arg1)

    return {
        "filename": filename,
        "response": response
    }`

Code Node Works:
![image](https://github.com/user-attachments/assets/0e032ef0-6139-4e7a-977c-e75028a7a1f2)

However It Still does not output on the end of the node:
![image](https://github.com/user-attachments/assets/8bb54463-35ea-45e0-82f3-0b8dae46ab62)

**Comment by kingdavidph** [comment]
why would we have to adjust source when this is so elementary?

**Comment by kingdavidph** [comment]
@dosu why would we have to adjust source when this is so elementary?

I had to use a workaround using LLMs and prompt engineering to extract the filename and response. This is a lot more costly and not convenient.

**Comment by kingdavidph** [comment]
I was able to use the Parameter Extractor to pull out the variables I needed although it's a bummer that the code node didn't work out.

**Comment by Sakura4036** [comment]
don't need json parse twice!  you input is `{"filename":xxx}` not `{"arg1":\"{xxx}\"}`.
