### ISSUE TITLE
api extension not call 

### ISSUE THREAD

**Issue by kenneth-bro** [langgenius/dify#7790]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Configure API Extension, but this variable is not called when debugging. The variable is out of the original output, and there is no replacement
![image](https://github.com/user-attachments/assets/aea73cdd-c662-4aaa-a059-ff84246ac05f)

![image](https://github.com/user-attachments/assets/45195d52-b647-4b3f-8f75-f286a61f72c0)

![image](https://github.com/user-attachments/assets/abd68427-d9a2-400e-83ae-2a80f3639e4c)

### ✔️ Expected Behavior

Replace variable

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/7520
