### ISSUE TITLE
Minified React error #31 - Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by danialcheung** [langgenius/dify#7793]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1, 0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

`Application error: a client-side exception has occurred` shows up after an LLM has given its reply to a user. This occurs during a workflow preview, as well as at the 'explore' section. Frequency is undetermined as sometimes it will take a few messages for it to show an error, whereas other times it will output an error instantly after the first message has been replied to.

Upgraded from `0.7.1` to `0.7.2` and the error persists.
![image](https://github.com/user-attachments/assets/f931fcb7-d55f-480d-b63d-b5436cc26e49)

### ✔️ Expected Behavior

An error to not occur.

### ❌ Actual Behavior

`Application error: a client-side exception has occurred` caused by `Minified React error #31`.

**Comment by danialcheung** [comment]
*Update*: I have found that disabling the "Follow-up" feature has solved the issue for now.

**Comment by iamjoel** [comment]
Could you please give me the app DSL to reproduce it? @danialcheung

**Comment by danialcheung** [comment]
@iamjoel Sure, I've made a simple workflow that causes the error. Nothing special about it other than having the 'Follow-up' feature enabled. Just rename the extension back to `.yml`
[For Debugging.yml.txt](https://github.com/user-attachments/files/16842906/For.Debugging.yml.txt)

**Comment by iamjoel** [comment]
Maybe the issue is caused by qwen2:72b to generate the 'Follow-up' suggestions. I don't have the api key of  qwen2:72b . I can't reproduce the issue when  I use models of openai with 'Follow-up' feature enabled. 
When the issue happens, see if the `suggested-questions` api return the errror info. @danialcheung 

<img width="460" alt="image" src="https://github.com/user-attachments/assets/8cfb245d-b745-49ed-8cf4-8d37a037bc66">
