### ISSUE TITLE
Handling None Values in installed_app Causes Frontend Display Issues

### ISSUE THREAD

**Issue by YidaHu** [langgenius/dify#7798]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Navigate to the application installation page.
2. Ensure there is at least one installed application with its app attribute set to None.
3. Observe the list of installed applications displayed on the page.

![image](https://github.com/user-attachments/assets/6ee9d93a-f67c-4801-837a-2dbc49691a71)

![image](https://github.com/user-attachments/assets/be26e2f8-3908-43cd-be3b-95d95b41550a)

![image](https://github.com/user-attachments/assets/cf58bbc1-e6f6-471a-a8b1-ba2946a63620)

### ✔️ Expected Behavior

The page should display correctly without any errors or blank sections.

### ❌ Actual Behavior

When installed_app.app is None, this None value is directly passed to the frontend, leading to incomplete or erroneous display.

**Comment by crazywoola** [comment]
Here are few things needs to be clarified
- Is this application removed or deleted?
- Have you started the celery worker?
