### ISSUE TITLE
Part of the output results disappear

### ISSUE THREAD

**Issue by toshikk** [langgenius/dify#7802]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.12

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When outputting text for three items, only the last item is displayed, and the other items are not shown.

### ✔️ Expected Behavior

All items of text are output.

### ❌ Actual Behavior

Only the text for the last item (LLM3) is output.

**Comment by crazywoola** [comment]
![QQ_1724929599586](https://github.com/user-attachments/assets/a913c6da-3fba-4c93-b434-5174a9a88427) Already supported this feature in latest version.

**Comment by crazywoola** [comment]
> ![微信图片_20240829173055](https://private-user-images.githubusercontent.com/13914936/362619730-3cc8e5dd-020e-4305-a848-100ff143b49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjk2OTcsIm5iZiI6MTcyNDkyOTM5NywicGF0aCI6Ii8xMzkxNDkzNi8zNjI2MTk3MzAtM2NjOGU1ZGQtMDIwZS00MzA1LWE4NDgtMTAwZmYxNDNiNDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDExMDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZWFjMWZmNGU3Njg1ZDYzNjNjMWFhZGE2ZTRjMmFhZjM4ZmM2MGQzZThlY2Q1NmQ4MTBiMGE2MGMwODNhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JrJY-_wl8kVoc4e0959gRMOD9aNZSUF52i_-p-81u0c) http request: Internal Server Error

If you encounter 500 error, please provide container logs.
