### ISSUE TITLE
In the workflow, the question hits  annotation, but the reply is empty

### ISSUE THREAD

**Issue by YangCY1995** [langgenius/dify#7804]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

configured a chat agent in the form of a workflow and maintained question annotations, but when a question hits an annotation, the robot's response is empty。
![微信图片_20240829172255](https://github.com/user-attachments/assets/f8161983-3681-4e24-ada8-339cfc269e76)

### ✔️ Expected Behavior

The answer associated with the annotation

### ❌ Actual Behavior

empty

**Comment by crazywoola** [comment]
![QQ_1724930402243](https://github.com/user-attachments/assets/d39f440a-5de8-4593-a6b0-e9f62496f8ad)
Cant reproduce this on latest version.
