### ISSUE TITLE
The knowledge base document requires an API that can be enabled and disabled

### ISSUE THREAD

**Issue by 1596941391qq** [langgenius/dify#7821]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I am designing a role-playing AI, for which various character-related documents are stored in the knowledge base. I need to control whether the documents are enabled to make the AI play the corresponding roles.

### 2. Additional context or comments

like this but api
![Uploading 微信图片_20240830044531.png…]()

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This image is broken.
