### ISSUE TITLE
When I upgraded version 0.6.16 to version 0.7.2, I found that the upgrade was invalid. What should I do? Do I need to modify the env file

### ISSUE THREAD

**Issue by dingidng** [langgenius/dify#7825]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I upgraded version 0.6.16 to version 0.7.2, I found that the upgrade was invalid. What should I do? Do I need to modify the env file

```
cd dify/docker
docker compose down
git pull origin main
docker compose pull
docker compose up -d
```

### ✔️ Expected Behavior

Upgrade to version 0.7.2, and save the previous version information. Such as: data, account information, etc

### ❌ Actual Behavior

```
cd dify/docker
docker compose down
git pull origin main
docker compose pull
docker compose up -d
```
After following the above information, the docker-compose.yaml file does not get the latest version

 * branch              main       -> FETCH_HEAD
Already up to date.

Hope to give a detailed update dify tutorial, rich in details

**Comment by crazywoola** [comment]
You should read the release logs. Try to upgrade versions one by one instead of upgrading to the latest https://github.com/langgenius/dify/releases

Hence there is no useful information indicates what kind of errors you are encountering.
