### ISSUE TITLE
If I set the "score" Slider to the far left, the value of "score" will change to 0.8.

### ISSUE THREAD

**Issue by MrXionGe** [langgenius/dify#7827]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14 | 7.0.0 | 7.0.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

**1. Select an app (chatbot with workflow)
2. Enter the workflow editing page
3. Select the Knowledge Retrieval component
4. Recall Settings
5. Change the "score" value**
![微信截图_20240830103236](https://github.com/user-attachments/assets/7f94c577-690e-4095-9485-56c29a7d2850)

### ✔️ Expected Behavior

If I set the "score" Slider to the far left, the value of "score" should be 0.
Because in the knowledge base settings, retrieval settings, the "score" value is like this.

### ❌ Actual Behavior

If I set the "score" Slider to the far left, the value of "score" will change to 0.8.

https://github.com/user-attachments/assets/6e3beb86-3928-481d-ae5a-24b2f42c3ef9

**Comment by MrXionGe** [comment]
@dosu 
Thanks you. 
Knowledge Base --> Settings --> Search Settings
On this page, the minimum value of "score" is 0. If I slide the slider to the far left, the value of "score" is 0.
![image](https://github.com/user-attachments/assets/069632be-f6b2-4ba1-ad47-22a29e955447)


It would be best if the rules for the "score" parameter are the same on the "workflow" page and on the "knowledge base settings" page.

**Comment by MH4GF** [comment]
@JzoNgKVO @crazywoola 
I am interested in contributing to this issue! If you haven't already worked on yours, may I get started?
