### ISSUE TITLE
dify知识库文件上传报错

### ISSUE THREAD

**Issue by 18075717849** [langgenius/dify#7829]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

提示上传文件太大，但是文件大小远远小于上限
![lQLPJxiAoiYg2PPNAT7NBhewBSnN4-NDQhwGufX8QSvhAA_1559_318](https://github.com/user-attachments/assets/0a239417-53f4-459d-800d-d212935ea95a)

### ✔️ Expected Behavior

应该上传成功

### ❌ Actual Behavior

但是上传失败了

**Comment by 18075717849** [comment]
已解决

**Comment by zengqingfu1442** [comment]
> 已解决

请问怎么解决的？我也遇到这个问题了，0.12.2版本。

**Comment by yenslife** [comment]
更新到 0.15.1 也有遇到相同的問題，當上傳帶有圖片的 pdf 時會出現 upload failed 錯誤，沒有圖片的 pdf 可以正常上傳，我是本地 docker compose 部署的

**Comment by xiwei26** [comment]
> 已解决

请问怎么解决的呀
