### ISSUE TITLE
ElasticSearchConfig Validation Error: Missing Required 'HOST' Configuration

### ISSUE THREAD

**Issue by Cod1ng** [langgenius/dify#7837]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. git clone https://github.com/langgenius/dify.git
2. cp .env.example .env
3. modify .env, set VECTOR_STORE=elasticsearch
4. docker compose up
5. then setup in http://localhost/install, configure siliconflow api
6. add some docs to doc_store, The error occurs during the indexing stage.

<img width="312" alt="image" src="https://github.com/user-attachments/assets/98b41374-dc75-4b17-9481-bf115ce2fc0a">

### ✔️ Expected Behavior

Everything goes fine during the indexing stage

### ❌ Actual Behavior

1 validation error for ElasticSearchConfig: Value error, config HOST is required [type=value_error, input_value={'host': None, 'port': None, 'username': None, 'password': None}, input_type=dict]. For further information visit https://errors.pydantic.dev/2.8/v/value_error

**Comment by Cod1ng** [comment]
I tested using OpenSearch, and it also reported an error：
ConnectionError([SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)) caused by: SSLError ([SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007))

**Comment by Sapna-Tech** [comment]
Instead of using localhost or the IP address of the Elasticsearch container, access it by its container name within your API container. This ensures reliable communication regardless of container IP assignment.

Explanation:

localhost inside a container refers to the container itself, not the host machine or other containers. This can lead to connection errors if you use it to reach Elasticsearch.
Container IP addresses are dynamic and can change when containers are restarted. Using the container name provides a more stable reference.

**Comment by abhishekmathada** [comment]
@Sapna-Tech 
Using container name, i.e., ELASTICSEARCH_HOST=elasticsearch worked for me.
Thanks a lot :)

**Comment by baiyi-os** [comment]
我也是相同的错误，但是我配置了ELASTICSEARCH_HOST，但是work节点仍然显示host错误
[2024-09-09 04:19:23,853: INFO/MainProcess] Start retry document: 1dd70a00-9139-45d1-9052-d0a77e1e46a3
[2024-09-09 04:19:23,869: INFO/MainProcess] 1 validation error for ElasticSearchConfig
  Value error, config HOST is required [type=value_error, input_value={'host': None, 'port': No... None, 'password': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
