### ISSUE TITLE
use dify datasets api in workflow http requests 444

### ISSUE THREAD

**Issue by silverWolf818** [langgenius/dify#7841]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="2303" alt="image" src="https://github.com/user-attachments/assets/1729cff2-d872-4f32-9e09-0a7a37374704">
http return 444 why

same use  curl --location --request POST 'http://dify.xxxx/v1/datasets' \
--header 'Authorization: Bearer {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{"name": "name"}'
can work well

**Comment by crazywoola** [comment]
I don't think this is return by our application, I guess there is something wrong with the request itself or the nginx configuration file is not correct.

**Comment by silverWolf818** [comment]
ok , try it
