### ISSUE TITLE
variable does not work

### ISSUE THREAD

**Issue by HAL9KKK** [langgenius/dify#7843]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

after adding the variable to the prompt, the result of the execution show the variable has never been taken

![image](https://github.com/user-attachments/assets/48048573-c160-41a9-b4cc-72d8513689ea)

### ✔️ Expected Behavior

execute the flow with the expected variable

### ❌ Actual Behavior

the execution show the variable data is missing

**Comment by HAL9KKK** [comment]
I am not using Ollama, the LLM is based on Azure OpenAI

**Comment by crazywoola** [comment]
What the type of the appliation?

**Comment by HAL9KKK** [comment]
Google search return both text and json, the problem seems to be the variable in text, never appear in the prompt even thought i set it up. 
I have tried to change Googlesearch tool with Wikipediasearch tool and the text output variable of wikipedia is working fine!
So the proble is related to Googlesearch tool
