### ISSUE TITLE
The function of the 'inputs' parameter in the robot configuration embedded in the web page, and what scenarios it is mainly used for.

### ISSUE THREAD

**Issue by PlatonaBoy** [langgenius/dify#7848]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes
```
window.difyChatbotConfig = {
    // Required, automatically generated by Dify
    token: 'YOUR_TOKEN',
    // Optional, default is false
    isDev: false,
    // Optional, when isDev is true, default is 'https://dev.udify.app', otherwise default is 'https://udify.app'
    baseUrl: 'YOUR_BASE_URL',
    // Optional, It can accept any valid HTMLElement attribute other than `id`, such as `style`, `className`, etc
    containerProps: {},
    // Optional, If or not the button is allowed to be dragged, default is `false`
    draggable: false,
    // Optional, The axis along which the button is allowed to be dragged, default is `both`, can be `x`, `y`, `both`
    dragAxis: 'both',
    // Optional, An object of inputs that set in the dify chatbot
    inputs: {
        // key is the variable name
        // e.g.
        // name: "NAME"
    }
}
```

What is the function of the 'inputs' parameter in the robot configuration embedded in the web page, and what scenarios is it mainly used for? I want to select text with the mouse and talk to the robot directly. Is it feasible?

**Comment by crazywoola** [comment]
See this PR https://github.com/langgenius/dify/pull/6376

> I want to select text with the mouse and talk to the robot directly. Is it feasible?

This is another question, yes it is, you can see kimi's chrome extension. But it's not available in dify yet.
