### ISSUE TITLE
Add default input value for Start Node

### ISSUE THREAD

**Issue by harrywang** [langgenius/dify#7849]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I cannot set default input value:
![Screenshot 2024-08-30 at 5 47 52 PM](https://github.com/user-attachments/assets/fb4f9794-7c97-45da-a48b-590d5e5ecd50)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by EvenYan** [comment]
maybe add a code node with if/else can solve you problem @harrywang

**Comment by harrywang** [comment]
> maybe add a code node with if/else can solve you problem @harrywang

Thanks for the suggestion but I still think the default values are better options.

**Comment by keaixiao-svg** [comment]
default value is a better idea
