### ISSUE TITLE
Recall Issues in multiple Journal Impact Factor Queries

### ISSUE THREAD

**Issue by iray1991** [langgenius/dify#7855]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Dify 0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Querying the journal impact factor knowledge base in bulk: When querying a single journal name, the recall results are correct (as shown in Figure 1). However, when sending multiple journals at once, the recall results are incomplete. It seems that not every journal is queried individually in the knowledge base, but rather multiple journal names are combined into one query, resulting in some journal names not being recalled (as shown in Figure 2).

<img width="1200" alt="企业微信截图_17251006752742" src="https://github.com/user-attachments/assets/f3dd6c38-b7a8-4ec2-ac53-42d755a611e6">
<img width="1192" alt="企业微信截图_17251006776260" src="https://github.com/user-attachments/assets/1f7393cb-778b-46e6-a0b4-0daef31b23d9">

**Comment by crazywoola** [comment]
This is an expected behavior.
