### ISSUE TITLE
How to modify the content in the bottom right corner when publishing as a public web site?

### ISSUE THREAD

**Issue by iray1991** [langgenius/dify#7856]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

How to modify the content in the bottom right corner when publishing as a public web site?
<img width="884" alt="企业微信截图_1725101000657" src="https://github.com/user-attachments/assets/5f117f4d-2957-4670-b6f8-e4feb5a82192">

**Comment by iray1991** [comment]
> To modify the content in the bottom right corner when publishing as a public website, you need to update the settings related to the embedded chat application. Specifically, you can customize the copyright information, privacy policy, and custom disclaimer, which are displayed on the client side.
> 
> Here is the relevant section from the provided document:
> 
> ```tsx
> {/* copyright */}
> <div className={cn(
>   isInstalledApp ? 'left-[248px]' : 'left-8',
>   'fixed  bottom-4  flex space-x-2 text-gray-400 font-normal text-xs',
> )}>
>   <div className="">© {siteInfo.copyright || siteInfo.title} {(new Date()).getFullYear()}</div>
>   {siteInfo.privacy_policy && (
>     <>
>       <div>·</div>
>       <div>{t('share.chat.privacyPolicyLeft')}
>         <a
>           className='text-gray-500 px-1'
>           href={siteInfo.privacy_policy}
>           target='_blank' rel='noopener noreferrer'>{t('share.chat.privacyPolicyMiddle')}</a>
>         {t('share.chat.privacyPolicyRight')}
>       </div>
>     </>
>   )}
> </div>
> ```
> 
> To modify the content, you can update the `siteInfo` object with your desired text:
> 
> * **Copyright**: Update the `siteInfo.copyright` with the name of the author or organization.
> * **Privacy Policy**: Update the `siteInfo.privacy_policy` with the link to your privacy policy.
> 
> These settings will allow you to customize the content displayed in the bottom right corner of your public website [[1]](https://github.com/langgenius/dify/blob/main/web/i18n/it-IT/app-overview.ts)[[2]](https://github.com/langgenius/dify/blob/main/web/app/components/share/text-generation/index.tsx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

tried that, but this powed by Dify info seems not changebable in the setting you mentioned

**Comment by iray1991** [comment]
> web/i18n/it-IT/custom.ts

- if I am using docker, how can I find the web/i18n/it-IT/custom.ts and  remove the "Powered by Dify" branding

**Comment by iray1991** [comment]
> To find the `web/i18n/it-IT/custom.ts` file and remove the "Powered by Dify" branding in Docker, follow these steps:
> 
> 1. **Access the Docker container**:
>    Use the `docker exec` command to access the Docker container where your application is running.
>    ```shell
>    docker exec -it <container_id> /bin/sh
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace `<container_id>` with the actual ID of your Docker container.
> 2. **Navigate to the file location**:
>    Once inside the container, navigate to the directory where the `custom.ts` file is located. This is typically within the application's directory structure.
>    ```shell
>    cd /path/to/your/application/web/i18n/it-IT/
>    ```
> 3. **Edit the `custom.ts` file**:
>    Use a text editor available in the container to open and edit the `custom.ts` file. For example, you can use `vi` or `nano`.
>    ```shell
>    vi custom.ts
>    ```
> 4. **Remove the "Powered by Dify" branding**:
>    Locate the line containing `removeBrand: 'Rimuovi Powered by Dify'` and modify or remove it as needed. Here is the relevant part of the file:
>    ```ts
>    const translation = {
>      custom: 'Personalizzazione',
>      upgradeTip: {
>        prefix: 'Aggiorna il tuo piano per',
>        suffix: 'personalizzare il tuo marchio.',
>      },
>      webapp: {
>        title: 'Personalizza il marchio WebApp',
>        removeBrand: 'Rimuovi Powered by Dify', // Modify or remove this line
>        changeLogo: 'Cambia immagine del marchio Powered by',
>        changeLogoTip: 'Formato SVG o PNG con una dimensione minima di 40x40px',
>      },
>      app: {
>        title: 'Personalizza l\'intestazione del marchio dell\'app',
>        changeLogoTip: 'Formato SVG o PNG con una dimensione minima di 80x80px',
>      },
>      upload: 'Carica',
>      uploading: 'Caricamento in corso',
>      uploadedFail: 'Caricamento dell\'immagine fallito, per favore ricarica.',
>      change: 'Cambia',
>      apply: 'Applica',
>      restore: 'Ripristina Impostazioni Predefinite',
>      customize: {
>        contactUs: ' contattaci ',
>        prefix:
>          'Per personalizzare il logo del marchio all\'interno dell\'app, per favore',
>        suffix: 'per aggiornare alla versione Enterprise.',
>      },
>    }
>    
>    export default translation
>    ```
> 5. **Save the changes**:
>    Save the changes and exit the text editor. For `vi`, you can do this by pressing `Esc`, typing `:wq`, and pressing `Enter`.
> 6. **Restart the Docker container**:
>    Finally, restart the Docker container to apply the changes.
>    ```shell
>    docker restart <container_id>
>    ```
> 
> By following these steps, you can find the `web/i18n/it-IT/custom.ts` file in your Docker container and remove the "Powered by Dify" branding [[1]](https://github.com/langgenius/dify/blob/main/web/i18n/it-IT/custom.ts).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

which of below should I find the container_id?
![image](https://github.com/user-attachments/assets/4982dacb-901a-4aab-b1ba-b7cb594c8181)

**Comment by iray1991** [comment]
how to upgrade dify to 0.7.2 in docker?

**Comment by iray1991** [comment]
> To find the `container_id`, look for the container running the `dify-web` image. The `container_id` is the alphanumeric string listed in the first column of the Docker container list. Use that ID in the `docker exec` command to access the container.
> 
> For example, if the `container_id` for `dify-web` is `abc123`, you would use:
> 
> ```shell
> docker exec -it abc123 /bin/sh
> ```
> 
> This will give you access to the container where you can navigate to the `web/i18n/it-IT/` directory and make the necessary changes.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._


how to upgrade dify to 0.7.2 in docker?

**Comment by crazywoola** [comment]
You need to upgrade account to Pro or Team on cloud.dify.ai. This feature requires paid plan.
If you are using Self Hosted version, remove Logo is prohibited unless you obtain a business license from us, if you would like to obtain that, please react out to business@dify.ai.

**Comment by moymoussan** [comment]
@crazywoola if i have a pro account in dify cloud but im also self hosting, would i be able to remove the logo from the self hosted as well?

**Comment by iray1991** [comment]
Dear Mr./Ms. , Thanks for your email. You may have sent to the wrong email Have a great day! Kind Regards TopTalents Group

**Comment by a173030685** [comment]
> To find the `web/i18n/it-IT/custom.ts` file and remove the "Powered by Dify" branding in Docker, follow these steps:
> 
> 1. **Access the Docker container**:
>    Use the `docker exec` command to access the Docker container where your application is running.
>    docker exec -it <container_id> /bin/sh
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace `<container_id>` with the actual ID of your Docker container.
> 2. **Navigate to the file location**:
>    Once inside the container, navigate to the directory where the `custom.ts` file is located. This is typically within the application's directory structure.
>    cd /path/to/your/application/web/i18n/it-IT/
> 3. **Edit the `custom.ts` file**:
>    Use a text editor available in the container to open and edit the `custom.ts` file. For example, you can use `vi` or `nano`.
>    vi custom.ts
> 4. **Remove the "Powered by Dify" branding**:
>    Locate the line containing `removeBrand: 'Rimuovi Powered by Dify'` and modify or remove it as needed. Here is the relevant part of the file:
>    const translation = {
>      custom: 'Personalizzazione',
>      upgradeTip: {
>        prefix: 'Aggiorna il tuo piano per',
>        suffix: 'personalizzare il tuo marchio.',
>      },
>      webapp: {
>        title: 'Personalizza il marchio WebApp',
>        removeBrand: 'Rimuovi Powered by Dify', // Modify or remove this line
>        changeLogo: 'Cambia immagine del marchio Powered by',
>        changeLogoTip: 'Formato SVG o PNG con una dimensione minima di 40x40px',
>      },
>      app: {
>        title: 'Personalizza l\'intestazione del marchio dell\'app',
>        changeLogoTip: 'Formato SVG o PNG con una dimensione minima di 80x80px',
>      },
>      upload: 'Carica',
>      uploading: 'Caricamento in corso',
>      uploadedFail: 'Caricamento dell\'immagine fallito, per favore ricarica.',
>      change: 'Cambia',
>      apply: 'Applica',
>      restore: 'Ripristina Impostazioni Predefinite',
>      customize: {
>        contactUs: ' contattaci ',
>        prefix:
>          'Per personalizzare il logo del marchio all\'interno dell\'app, per favore',
>        suffix: 'per aggiornare alla versione Enterprise.',
>      },
>    }
>    
>    export default translation
> 5. **Save the changes**:
>    Save the changes and exit the text editor. For `vi`, you can do this by pressing `Esc`, typing `:wq`, and pressing `Enter`.
> 6. **Restart the Docker container**:
>    Finally, restart the Docker container to apply the changes.
>    docker restart <container_id>
> 
> By following these steps, you can find the `web/i18n/it-IT/custom.ts` file in your Docker container and remove the "Powered by Dify" branding [[1]](https://github.com/langgenius/dify/blob/main/web/i18n/it-IT/custom.ts).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu)._

After making such changes, there is no effect after restarting. @dosubot
