### ISSUE TITLE
docker的nginx起不来，报错如下，请问应该怎么处理？

### ISSUE THREAD

**Issue by lhplol** [langgenius/dify#787]
Error: (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/d/d3d/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /run/desktop/mnt/host/d/d3d/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by NankinXH** [comment]
same issue

**Comment by THWJ** [comment]
我也出现了这个错误。出现的原因是把proxy.conf nginx.conf两个文件当文件夹建了，然后启动不成功，修改后再启动也不成功。解决方法是删掉已经建立的nginx容器，重新用docker-compose up -d 命令启动就好了。

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/3257

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/1832

**Comment by dingshanliang** [comment]
> 我也出现了这个错误。出现的原因是把proxy.conf nginx.conf两个文件当文件夹建了，然后启动不成功，修改后再启动也不成功。解决方法是删掉已经建立的nginx容器，重新用docker-compose up -d 命令启动就好了。

遇到了同样的问题，还是没有解决。可不可以说的清楚一点？ 我做了以下操作，依然不行。
1.  `docker rm nginx:latest`;
2.  删除文件夹 nginx.conf 和 proxy.conf；
3. 重新启动: `docker compose up -d` 。

**Comment by red-wu5** [comment]
> > > 我也出现了这个错误。出现的原因是把proxy.conf nginx.conf两个文件当文件夹建了，然后启动不成功，修改后再启动也不成功。解决方法是删掉已经建立的nginx容器，重新用docker-compose up -d 命令启动就好了。
> > 
> > 
> > 遇到了同样的问题，还是没有解决。可不可以说的清楚一点？ 我做了以下操作，依然不行。
> > 
> > 1. `docker rm nginx:latest`;
> > 2. 删除文件夹 nginx.conf 和 proxy.conf；
> > 3. 重新启动: `docker compose up -d` 。
> 
> 1. 删除文件夹 nginx.conf 和 proxy.conf；
> 2. 按照仓库里的 NGINX 配置文件 新建 nginx.conf 和 proxy.conf；和 conf.d 文件夹里的 default.conf
> 3. 重新启动: `docker compose up -d`

一样的，Mac M1环境，完完全全clone dify仓库下来，在docker目录里直接up，在我的Mac Inter能启动成功，在M1上启动不成功，我不觉得这是代码上的问题，更像环境上的不兼容？
