### ISSUE TITLE
 ValidationError 2 validation errors for DifyConfig

### ISSUE THREAD

**Issue by gisleisters** [langgenius/dify#7876]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

flask start   
HTTP_REQUEST_NODE_MAX_BINARY_SIZE
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='10485760 # 10MB', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/int_parsing
HTTP_REQUEST_NODE_MAX_TEXT_SIZE
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='1048576 # 1MB', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/int_parsing

**Comment by crazywoola** [comment]
I think this already fixed in this pr https://github.com/langgenius/dify/pull/7508/files
```
# HTTP Node configuration
HTTP_REQUEST_NODE_MAX_BINARY_SIZE=10485760  # 10MB
HTTP_REQUEST_NODE_MAX_TEXT_SIZE=1048576  # 1MB
```

You should remove '# 10MB' and '# 1MB' from your `.env` file because it will interpreted as string value.
