### ISSUE TITLE
Get conversation_id in custom tools

### ISSUE THREAD

**Issue by hllshiro** [langgenius/dify#7885]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The tool I'm currently working on needs to bind some data through the conversation_id, such as the user identity, points, etc. I've consulted all the docs and there's no mention of how to get conversation_id in custom tools, I'd like to ask if there is currently such a feature, and if not, is there a plan to implement it?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by alterxyz** [comment]
Is that OpenAPI or Workflow as tools or something else?

**Comment by hllshiro** [comment]
Something else, a widget developed by yourself, used in as chat bot in wechat. I've circumvented this issue in other ways at the moment. see [issue 8054](https://github.com/langgenius/dify/discussions/8054#discussioncomment-10585330)

**Comment by tyoh-love** [comment]
I'm having a hard time to get the messages/conversations API working. 
the api always gives me below result, even though i had conversation on web app. 
{
    "limit": 20,
    "has_more": false,
    "data": []
}
