### ISSUE TITLE
code block:

### ISSUE THREAD

**Issue by Bourne-alt** [langgenius/dify#7886]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/89e30357-ee30-44c5-87c6-7f0092b87d80)
My .env file CODE_MAX_STRING_LENGTH  is also set to 80000, but I still get an error

**Comment by crazywoola** [comment]
Close as Duplicated. Please search existing issues first. :0
