### ISSUE TITLE
Need the feature of try ... catch

### ISSUE THREAD

**Issue by qkxie** [langgenius/dify#7891]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes. I have an array of string. And in an iteration, I will pass each string as argument to a LLM module.

One of the input string will cause the LLM module crash. 

I'd like to have a try ... except feature just like what it does in Python, so that I can skip the crash item and continue to the next item.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/7143

**Comment by sattosan** [comment]
How is the progress？

**Comment by crazywoola** [comment]
![image](https://github.com/user-attachments/assets/450924cf-1985-4678-89ce-2a905503c28f)
We introduced this function in v0.11.0, please try our latest version.
