### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by flyice8** [langgenius/dify#7893]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

after I upgrade dify to 0.7.2, The following problems are encountered:
The following error occurs during the recall test in the knowledge base
![22222](https://github.com/user-attachments/assets/170469ac-00fb-4845-bdf6-8884d1f8a9c8)
![11111](https://github.com/user-attachments/assets/bfc2fdcc-f99b-4d1f-a18a-2fef37c01ae1)

### ✔️ Expected Behavior

Hope to solve this problem.

### ❌ Actual Behavior

recall test failed

**Comment by crazywoola** [comment]
I can not reproduce this problem, can you provide more details such as steps to reproduce?

**Comment by flyice8** [comment]
The problem remains unresolved. I found this problem when upgrading from 6.14 to 6.15 or later
