### ISSUE TITLE
Knowledge base Notion Intergration err

### ISSUE THREAD

**Issue by iray1991** [langgenius/dify#7894]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Dify 0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When linking Notion to dify in the knowlege base seesion , the link went to 
https://[api.notion.com/v1/oauth/authorize?client_id=&response_type=code&redirect_uri=%2Fconsole%2Fapi%2Foauth%2Fdata-source%2Fcallback%2Fnotion&owner=user](https://api.notion.com/v1/oauth/authorize?client_id=&response_type=code&redirect_uri=%2Fconsole%2Fapi%2Foauth%2Fdata-source%2Fcallback%2Fnotion&owner=user)

showes

{
    "error": "invalid_request",
    "error_description": "query failed validation: query.client_id should be a string or `undefined`, instead was `0`.",
    "request_id": "d765f8e9-96bd-41a7-8fcb-4bd5595c1a55"
}

**Comment by crazywoola** [comment]
What does your client id look like?
