### ISSUE TITLE
DeepSeekLargeLanguageModel inherits from OpenAILargeLanguageModel causing it to not be able to use tools_calls.

### ISSUE THREAD

**Issue by listeng** [langgenius/dify#7898]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

It seems like it should inherit from OAIAPICompatLargeLanguageModel in order to have tools_calls? Configuring a DeepSeek interface with a key to be a OpenAI-API-compatible is possible with tools_calls. But configure it as DeepSeekLargeLanguageModel and it won't call tools. MoonshotLargeLanguageModel works fine with tools, it also inherits from OAIAPICompatLargeLanguageModel.

**Comment by crazywoola** [comment]
Can you take a look at this @soulteary

**Comment by taowang1993** [comment]
Why did this get closed? The problem still exists. 

The tool/function call is currently not working. 

I have to add deepseek via the openai compatible model provider in order to use deepseek for tool/function calling.
