### ISSUE TITLE
Docker installation failed. Tip: unexpected EOF

### ISSUE THREAD

**Issue by jivaklong** [langgenius/dify#7900]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

When running docker compose up -d in Windows 11, an unexpected EOF error always occurs. I have installed it many times, tried running docker compose down, and then running docker compose up -d. The same problem occurs. The default configuration information is used after the configuration file is copied. The following is the error message:
docker compose up -d
[+] Running 12/15
 - worker Pulling                                                                                               1699.7s
 - api 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 292.2MB/292.2MB Pulling                                                        1699.7s
   ✔ e4fff0779e6d Already exists                                                                                   0.0s
   ✔ 05ca1eb4c21a Already exists                                                                                   0.0s
   ✔ 7be92ad65ca3 Already exists                                                                                   0.0s
   ✔ 7ef3acb059e5 Already exists                                                                                   0.0s
   ✔ a81861217e67 Already exists                                                                                   0.0s
   ✔ 7da61ad91274 Pull complete                                                                                    1.9s
   ✔ 925d318bdcb0 Pull complete                                                                                   83.1s
   ✔ 4f4fb700ef54 Pull complete                                                                                    2.0s
   ✔ d8cc2c59b8b8 Pull complete                                                                                  438.9s
   - 5eb857f49232 Downloading     [==================================================>]...                      1695.6s
   ✔ 9df1c9e38950 Download complete                                                                              361.7s
   ✔ 74d04cd4d827 Download complete                                                                              422.9s
   ✔ 300274facfe8 Download complete                                                                              426.2s
unexpected EOF

**Comment by jivaklong** [comment]
I use VPN

**Comment by crazywoola** [comment]
This is a general network issue.

**Comment by jivaklong** [comment]
Is there anything I need to modify in the configuration file? Every time I download to the point of completion, an unexpected EOF message appears.
