### ISSUE TITLE
Can't Find Workflow as Tools While Creating Agent

### ISSUE THREAD

**Issue by thiner** [langgenius/dify#7907]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have created two workflows, and exported as tool. I can find them from Tools --> Workflow. I can find them while creating new agent previously.  But I couldn't find them anymore after upgrade to 0.7.3. 
![image](https://github.com/user-attachments/assets/d7b3b4ea-c64b-4f5f-a7a8-1e950ca6512a)
Please note, this is not only occur in 0.7.3, I have observed at version 0.7.2 and 0.7.1 at least after upgrade. The only way to fix the issue is that recreate the workflows and configure it as tool. 

### ✔️ Expected Behavior

The existing workflow tools should be selectable while creating new agent after Dify upgrading.

### ❌ Actual Behavior

Not able to see workflows while creating agent after Dify upgrading.

**Comment by crazywoola** [comment]
<img width="652" alt="image" src="https://github.com/user-attachments/assets/f276409a-f327-4b70-927c-61802779835d">

**Comment by thiner** [comment]
I don't know how you tried, but in my environment, all the **existing** workflows are not visible from the tools list after upgrade to new version while creating agent. The steps you need to take to reproduce:
1. Deploy a previous version of Dify, e.g. v0.7.2. Create a workflow and configure it as tool.
2. Upgrade the Dify version to newer one, say v0.7.3 in this example. Try to create an agent to use the workflow tool. You will not be able to find it.
