### ISSUE TITLE
Error in Dify Framework with Qwen Model: Session Exceeds Input Length Limit

### ISSUE THREAD

**Issue by BingFrost** [langgenius/dify#7909]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.71

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Initialize a conversation session using the Dify framework.
Conduct a series of consecutive question-answer interactions, ensuring that the cumulative text exceeds 6000 characters.

### ✔️ Expected Behavior

The framework should handle or truncate the input to comply with the model's limitations without causing a server error, allowing the conversation to proceed smoothly.

### ❌ Actual Behavior

An error is thrown, indicating that the input length has exceeded the acceptable range, resulting in a failed model invocation.

**Comment by crazywoola** [comment]
What's the error message?
