### ISSUE TITLE
Spark's large language model token calculation error

### ISSUE THREAD

**Issue by cherryhuahua** [langgenius/dify#7911]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. The first step is to create a chat app
2. The second step is to write an 800-word essay about my mother
3. Step 3: Check the number of tokens
4. 
![Uploading lQLPKHAmPJ_nM5fNBF3NB7qwQWmsGwhW100GvxXajNsaAA_1978_1117.png…]()

### ✔️ Expected Behavior

The actual number of tokens may be several hundred

### ❌ Actual Behavior

The number of tokens calculated by the platform is only 18

**Comment by crazywoola** [comment]
This image is broken.

**Comment by AAEE86** [comment]
> This image is broken.

![QQ截图20240907153253](https://github.com/user-attachments/assets/583bf061-e18d-40b4-b62f-4b59be943d66)

It is indeed incorrect.

**Comment by AAEE86** [comment]
> This image is broken.

There may be an error here.
https://github.com/langgenius/dify/blob/0cef25ef8c3892e50fb47395a16b8096e7685511/api/core/model_runtime/model_providers/spark/llm/llm.py#L50
