### ISSUE TITLE
调大模型，提示输入长度超过限制如何解决？

### ISSUE THREAD

**Issue by tianfengliu** [langgenius/dify#7913]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

输入几个问题后，就会提示如下信息
[tongyi] Server Unavailable Error, Failed to invoke model qwen-max-0428, status code: 500, message: <400> InternalError.Algo.InvalidParameter: Range of input length should be [1, 6000]

### ✔️ Expected Behavior

如何解决这个问题

**Comment by tianfengliu** [comment]
没有找到这个参数，麻烦告知一下，谢谢

**Comment by tianfengliu** [comment]
如果配置了这个最大令牌数，那么用户多问几个问题就超过这个最大数，是有提示信息吗？还是系统自动丢弃之前问的问题，只保留最近问的信息？

**Comment by tianfengliu** [comment]
麻烦问一下，这个参数是在选择模型中参数的最大标记配置吗？

**Comment by tianfengliu** [comment]
glm-4-airx.yaml  这个文件在那个目录下?

**Comment by tianfengliu** [comment]
我们目前用的通义千问的，不是智普的。麻烦说一下通义千问改哪个文件的哪个参数？

**Comment by crazywoola** [comment]
Close due to https://github.com/langgenius/dify/issues/1542

**Comment by lumixraku** [comment]
> 要解决调大模型时输入长度超过限制的问题，可以在编排页面的参数设置中将“最大令牌”的值调小。
> 
> 例如，将 `max_tokens` 参数设置为较小的值，以确保输入长度在可接受的范围内。此外，可以考虑将长文本分成较小的段落，以适应模型的输入长度限制。
> 
> {
>   "max_tokens": 500
> }
> 这样可以避免超过输入长度限制的错误 [[1]](https://github.com/langgenius/dify-docs/blob/main/en/learn-more/faq/use-llms-faq.md)[[2]](https://github.com/langgenius/dify-docs/blob/main/jp/learn-more/faq/llms-use-faq.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu)._

如果是长文本分段了,   要如何交给大模型呢?
