### ISSUE TITLE
When embedding a website, add configuration whether to start a conversation directly

### ISSUE THREAD

**Issue by 1192603654** [langgenius/dify#7917]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/user-attachments/assets/eea66fb5-b481-4f3c-bdd1-70b10e462e6f)
When embedding a website, add configuration whether to start a conversation directly
![image](https://github.com/user-attachments/assets/fed02d5e-c0d3-4db0-90bd-39d9e1cf1e22)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated

**Comment by GoulartNogueira** [comment]
@crazywoola what's the link to the duplicated issue?
Was that solved? I can't find it.

**Comment by EcoleKeine** [comment]
@GoulartNogueira 
#5410
