### ISSUE TITLE
Logs&Anns page “created_at”  field is not displayed correctly by timezone

### ISSUE THREAD

**Issue by cesar-blog** [langgenius/dify#7939]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. setting->language-> display language  set 简体中文 ; timezone set +8 shanghai/beijing
2. start a chat session
3. go to Logs&Anns page to view records
4. created_at field is not displayed correctly by timezone

### ✔️ Expected Behavior

 created_at & updated_at field can be correctly displayed by timezone

**The local environment is displayed correctly but the production environment is not**

SETTING
<img width="810" alt="image" src="https://github.com/user-attachments/assets/6de84b17-9d86-4875-861a-cc939abb8340">

**The local environment：**
DB
<img width="529" alt="image" src="https://github.com/user-attachments/assets/a8a6cc47-dc5f-4497-a539-1243e1824edd">

SYSTEM
<img width="915" alt="image" src="https://github.com/user-attachments/assets/3cfbb905-226e-4875-8875-7da275f799fa">

**The production environment：**
DB
<img width="353" alt="image" src="https://github.com/user-attachments/assets/a9b5c7aa-f18f-46fe-b335-82f056010534">

SYSTEM
<img width="505" alt="image" src="https://github.com/user-attachments/assets/8962fc7b-3e03-43cd-82ac-6e48ee48c962">

### ❌ Actual Behavior

**The production environment：**

<img width="818" alt="image" src="https://github.com/user-attachments/assets/70836a55-3a54-42f1-9ada-fd661a528029">

**Comment by cesar-blog** [comment]
The local environment interface has returned +8 hours

<img width="801" alt="image" src="https://github.com/user-attachments/assets/3ff8f5c4-2fb3-44b0-9fdd-7bd01b3c0ef0">

<img width="924" alt="image" src="https://github.com/user-attachments/assets/df569535-a310-47ab-85ba-238896195a86">

**Comment by cesar-blog** [comment]
@dusubot

**Comment by cesar-blog** [comment]
@dosu.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/d7aa4076c9972b8e881c311dfdc4f2aa17277a3f/web/app/components/app/log/list.tsx#L717-L718

I took a look at this code, it seems to use the right function to format time already.

**Comment by cesar-blog** [comment]
> https://github.com/langgenius/dify/blob/d7aa4076c9972b8e881c311dfdc4f2aa17277a3f/web/app/components/app/log/list.tsx#L717-L718
> 
> I took a look at this code, it seems to use the right function to format time already.

It shouldn't be the front end. Look at the interface return.

**The local environment interface has returned +8 hours but the production environment is not**

**Comment by cesar-blog** [comment]
Changing the timezone(UTC) of the container where the api resides solves the problem

<img width="353" alt="image" src="https://github.com/user-attachments/assets/d119ffaf-ac7d-4df4-9eb0-96ee5d05b019">
