### ISSUE TITLE
Add page number to the segments

### ISSUE THREAD

**Issue by ebursztein** [langgenius/dify#7944]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently the segment do not track which page of the document it is originate from -- this makes it impossible to point users to the exact page to look for or open a pdf/doc to the right page in an app. The proposal is to add to segment a new field `page: int` that will allow to track segment to page.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/pull/7749
