### ISSUE TITLE
Run failed: 2 validation errors for KnowledgeRetrievalNodeData

### ISSUE THREAD

**Issue by lin1shu** [langgenius/dify#7946]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Build a knowledge with a PDF document
2. Choose the default "Knowledge Retrieval + Chatbot" from "Explore", choose the knowledge. 
3. Preview the "Knowledge Retrieval" Step with any keyword
4. UI shows following error: 

Run failed: 2 validation errors for KnowledgeRetrievalNodeData **multiple_retrieval_config.weights.vector_setting.embedding_provider_nam**e Field required [type=missing, input_value={'vector_weight': 1}, input_type=dict]  For further information visit https://errors.pydantic.dev/2.8/v/missing **multiple_retrieval_config.weights.vector_setting.embedding_model_name** Field required [type=missing, input_value={'vector_weight': 1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.8/v/missing

**Comment by crazywoola** [comment]
Can you paste your configurations here?

<img width="771" alt="image" src="https://github.com/user-attachments/assets/bd354b97-364a-4a61-9f1b-591c47bff4b5">

**Comment by lin1shu** [comment]
Thanks @crazywoola . Please see the screenshot below. Also, I tried the same settings as you posted and still got the same error message. 

<img width="721" alt="Screenshot 2024-09-03 at 10 08 36 PM" src="https://github.com/user-attachments/assets/c78d1ada-9d67-4303-b11c-302f05c82da0">
![Screenshot 2024-09-03 at 10 08 58 PM](https://github.com/user-attachments/assets/c41f3171-80f3-4f6b-a5e2-aa681405965f)

**Comment by Howe829** [comment]
I have the same problem.

**Comment by Howe829** [comment]
> I have the same problem.

I delete the Knowledge Retrieval node and create a new one, it works. Hope it will help you!

**Comment by shintaro-amaike** [comment]
If I delete and recreate the knowledge node created from the Knowledge Retreival + Chatbot template, the error no longer occurs.

<img width="412" alt="スクリーンショット 2024-09-10 14 16 51" src="https://github.com/user-attachments/assets/b15e925c-0646-4916-8539-9e8117f1bc2b">

**Comment by CooCooRiku** [comment]
I'm trying to build a simple chatbot but having the same issue.  Here is the error I'm getting

Run failed: 2 validation errors for KnowledgeRetrievalNodeData multiple_retrieval_config.reranking_model.provider Field required [type=missing, input_value={'reranking_provider_name...ranking_model_name': ''}, input_type=dict] For further information visit https://errors.pydantic.dev/2.9/v/missing multiple_retrieval_config.reranking_model.model Field required [type=missing, input_value={'reranking_provider_name...ranking_model_name': ''}, input_type=dict] For further information visit https://errors.pydantic.dev/2.9/v/missing

I've tried the deleting and recreating knowledge node suggested above but only got it to work in Preview and not when I go to Run App.

![image](https://github.com/user-attachments/assets/5e0fd403-58e5-47a4-8d5c-555b1bf13fde)

![image](https://github.com/user-attachments/assets/a7250d13-6a48-42a0-97ec-9d68882380ef)

Tried everything but couldn't get it to work.  Can anyone give me some pointers?  Thank you!
