### ISSUE TITLE
The end node in workflow mode does not support line breaks between llm variable outputs.

### ISSUE THREAD

**Issue by Modas-Li** [langgenius/dify#7951]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

V0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

workflow mode with several llm nodes, when output content, there is no line break between each llm output.

### ✔️ Expected Behavior

fix it

**Comment by crazywoola** [comment]
Use a jinja or code node to format the answer.

**Comment by Modas-Li** [comment]
the two node you mentioned does not support stream outputting


------------------ Original ------------------
From: crazywoola ***@***.***&gt;
Date: Wed,Sep 4,2024 0:36 PM
To: langgenius/dify ***@***.***&gt;
Cc: Modas Li ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [langgenius/dify] The end node in workflow mode does not supportline breaks between llm variable outputs. (Issue #7951)





 
Use a jinja or code node to format the answer.
