### ISSUE TITLE
after upgrade to 0.7.3 the worker container keeep restart

### ISSUE THREAD

**Issue by lordk911** [langgenius/dify#7954]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I've deploy dify on k8s by helm : https://github.com/douban/charts/tree/master/charts/dify
after I upgrade from 0.7.1 to 0.7.3, the dify-worker keep CrashLoopBackOff
the log of the worker pod is : 
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2024-09-04 03:43:10,417.417 WARNING [MainThread] [ext_mail.py:51] - MAIL_TYPE is not set
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: Invalid value for '-l' / '--loglevel': '-Q' is not one of 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', 'FATAL'.
```

### ✔️ Expected Behavior

Running

### ❌ Actual Behavior

CrashLoopBackOff

**Comment by crazywoola** [comment]
See the bot's answer, check the `LOG_LEVEL` in you .env files.

**Comment by jumpei-tsutsui** [comment]
Since the documentation states that ‘Default is INFO’, shouldn’t this be fixed as a bug?
