### ISSUE TITLE
Cannot Add Huggingface Models

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#7956]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

I cannot add this model. Removed api key for posting the following image.
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/bdf51ac2-7f76-4d36-8c43-c3caca9b85cd">

https://huggingface.co/dunzhang/stella_en_1.5B_v5

**Comment by crazywoola** [comment]
You should use models in this [category](https://huggingface.co/models?pipeline_tag=feature-extraction&sort=trending)

**Comment by holyvslin** [comment]
1.Choose model in Huggingface
https://huggingface.co/models?pipeline_tag=text-generation&sort=trending
![image](https://github.com/user-attachments/assets/ccc8798e-a226-439d-a980-fb05916bb186)

2.Add Models in Dify
Settings > Model Provider > Hugging Face > Model Type
![image](https://github.com/user-attachments/assets/6fcc9055-aa1c-4f43-bf87-918f63c31187)

**Stuck in adding Huggingface Models**, but solved by grant permission of Huggingface Access Tokens:
https://huggingface.co/settings/tokens Edit Access Token Permissions
**Repositories** -> select all
**Inference** -> select all
![image](https://github.com/user-attachments/assets/39caf9d6-8607-4b46-a393-599645b683fd)

3. Add successfully
![image](https://github.com/user-attachments/assets/288432cf-d74b-46d5-b28a-9c5106a5c475)
