### ISSUE TITLE
add agent node to worflow and chatflow

### ISSUE THREAD

**Issue by tianlongwang** [langgenius/dify#7963]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In my actual usage of dify, i found out i need to link up several agent out side of dify. I want to do it within dify. For example, an agent that talks to user and another llm summarize chat history into chat summary. 

### 2. Additional context or comments

problem with current chatflow llm node is it cannot use tools via functional call or react. 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated
