### ISSUE TITLE
logs list doesn't maintain a consistent count across pages

### ISSUE THREAD

**Issue by rickythink** [langgenius/dify#7964]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.7.3 & cloud version

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1. Navigate to the /<app_id>/logs page.
2. Enter a simple keyword, for example, 1.
3. The number of results across different pages will not maintain a consistent count.

### ✔️ Expected Behavior

Should be a consistent count acrocss different pages

### ❌ Actual Behavior

Not a consistent count

**Comment by Gaocarri** [comment]
it seems backend query multiple messages with unique conversationId
