### ISSUE TITLE
In basic Orchestrate mode, Debug and Preview do not have LLM reply information

### ISSUE THREAD

**Issue by youqugit** [langgenius/dify#7969]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/d5cd3a6f-df5d-47e8-8948-0057904901c9)

I checked the backend log and found no errors. I also checked the frontend response and found that the answer field was empty,`"answer": ""`. This confirms that LLM is working properly.LLM is provided by OpenAI-API-compatible.

**backend log**
```
2024-09-04 08:15:04,191.191 INFO [Thread-302 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:04] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
2024-09-04 08:15:05,200.200 INFO [Thread-303 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:05] "POST /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
2024-09-04 08:15:05,266.266 INFO [Thread-306 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:05] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
2024-09-04 08:15:05,315.315 INFO [Thread-307 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:05] "GET /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
2024-09-04 08:15:27,226.226 INFO [Thread-308 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:27] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
2024-09-04 08:15:28,518.518 INFO [Thread-309 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:28] "POST /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
2024-09-04 08:15:28,580.580 INFO [Thread-312 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:28] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
2024-09-04 08:15:28,635.635 INFO [Thread-313 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:28] "GET /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
```
**frontend**
```
data: {"event": "message", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "created_at": 1725437800, "task_id": "6d584cd5-9035-40aa-9cd3-942de0ddfdec", "id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "answer": ""}

data: {"event": "message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "created_at": 1725437800, "task_id": "6d584cd5-9035-40aa-9cd3-942de0ddfdec", "id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "metadata": {"usage": {"prompt_tokens": 1, "prompt_unit_price": "0", "prompt_price_unit": "0", "prompt_price": "0E-7", "completion_tokens": 0, "completion_unit_price": "0", "completion_price_unit": "0", "completion_price": "0E-7", "total_tokens": 1, "total_price": "0E-7", "currency": "USD", "latency": 0.8760251626372337}}}

data: {"event": "tts_message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "created_at": 1725437800, "task_id": "6d584cd5-9035-40aa-9cd3-942de0ddfdec", "audio": ""}


data: {"event": "message", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "7afff110-b087-4f15-a7d1-7caf3309debb", "created_at": 1725437975, "task_id": "c8e0d836-fc21-407f-875c-5d5bed4aea20", "id": "7afff110-b087-4f15-a7d1-7caf3309debb", "answer": ""}

data: {"event": "message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "7afff110-b087-4f15-a7d1-7caf3309debb", "created_at": 1725437975, "task_id": "c8e0d836-fc21-407f-875c-5d5bed4aea20", "id": "7afff110-b087-4f15-a7d1-7caf3309debb", "metadata": {"usage": {"prompt_tokens": 3, "prompt_unit_price": "0", "prompt_price_unit": "0", "prompt_price": "0E-7", "completion_tokens": 0, "completion_unit_price": "0", "completion_price_unit": "0", "completion_price": "0E-7", "total_tokens": 3, "total_price": "0E-7", "currency": "USD", "latency": 1.7923474870622158}}}

data: {"event": "tts_message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "7afff110-b087-4f15-a7d1-7caf3309debb", "created_at": 1725437975, "task_id": "c8e0d836-fc21-407f-875c-5d5bed4aea20", "audio": ""}


```

**Comment by youqugit** [comment]
new bug: Create Knowledge-----Text Preprocessing and Cleaning----Custom Rule 
`TextSplitter._merge_splits() missing 1 required positional argument: 'lengths'`

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/7950

https://github.com/langgenius/dify/blob/14af87527f219d5bbbc04f47af5d16f56adec1fb/api/core/rag/splitter/text_splitter.py#L111

@JzoNgKVO

**Comment by youqugit** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.7.3
> 
> ### Cloud or Self Hosted
> Self Hosted (Source)
> 
> ### Steps to reproduce
> ![image](https://private-user-images.githubusercontent.com/55398814/364282210-d5cd3a6f-df5d-47e8-8948-0057904901c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTYyMzksIm5iZiI6MTcyNTUxNTkzOSwicGF0aCI6Ii81NTM5ODgxNC8zNjQyODIyMTAtZDVjZDNhNmYtZGY1ZC00N2U4LTg5NDgtMDA1NzkwNDkwMWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA1NTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1N2RmZjc1ZDRmZDM4YjAxM2VmODcxMjg4ZDYyOTc3OTczMzkxNGU0YmJiY2VkZDQ4ZmMwNzY3NWQwODAyMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-H0zbsBi62_NevByUzH4NzxVn7auRjeDuDmVVdnC8A)
> 
> I checked the backend log and found no errors. I also checked the frontend response and found that the answer field was empty,`"answer": ""`. This confirms that LLM is working properly.LLM is provided by OpenAI-API-compatible.
> 
> **backend log**
> 
> ```
> 2024-09-04 08:15:04,191.191 INFO [Thread-302 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:04] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
> 2024-09-04 08:15:05,200.200 INFO [Thread-303 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:05] "POST /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
> 2024-09-04 08:15:05,266.266 INFO [Thread-306 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:05] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
> 2024-09-04 08:15:05,315.315 INFO [Thread-307 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:05] "GET /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
> 2024-09-04 08:15:27,226.226 INFO [Thread-308 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:27] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
> 2024-09-04 08:15:28,518.518 INFO [Thread-309 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:28] "POST /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages HTTP/1.1" 200 -
> 2024-09-04 08:15:28,580.580 INFO [Thread-312 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:28] "OPTIONS /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
> 2024-09-04 08:15:28,635.635 INFO [Thread-313 (process_request_thread)] [_internal.py:97] - 10.133.132.1 - - [04/Sep/2024 08:15:28] "GET /console/api/apps/764d1817-4d26-4cbf-b379-9dc9cda73b38/chat-messages?conversation_id=d55b4aee-baa3-436d-bdd5-49e9b5b8271b HTTP/1.1" 200 -
> ```
> 
> **frontend**
> 
> ```
> data: {"event": "message", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "created_at": 1725437800, "task_id": "6d584cd5-9035-40aa-9cd3-942de0ddfdec", "id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "answer": ""}
> 
> data: {"event": "message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "created_at": 1725437800, "task_id": "6d584cd5-9035-40aa-9cd3-942de0ddfdec", "id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "metadata": {"usage": {"prompt_tokens": 1, "prompt_unit_price": "0", "prompt_price_unit": "0", "prompt_price": "0E-7", "completion_tokens": 0, "completion_unit_price": "0", "completion_price_unit": "0", "completion_price": "0E-7", "total_tokens": 1, "total_price": "0E-7", "currency": "USD", "latency": 0.8760251626372337}}}
> 
> data: {"event": "tts_message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "f497ad7c-a1e3-4fca-83f4-c7ccd3a19019", "created_at": 1725437800, "task_id": "6d584cd5-9035-40aa-9cd3-942de0ddfdec", "audio": ""}
> 
> 
> data: {"event": "message", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "7afff110-b087-4f15-a7d1-7caf3309debb", "created_at": 1725437975, "task_id": "c8e0d836-fc21-407f-875c-5d5bed4aea20", "id": "7afff110-b087-4f15-a7d1-7caf3309debb", "answer": ""}
> 
> data: {"event": "message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "7afff110-b087-4f15-a7d1-7caf3309debb", "created_at": 1725437975, "task_id": "c8e0d836-fc21-407f-875c-5d5bed4aea20", "id": "7afff110-b087-4f15-a7d1-7caf3309debb", "metadata": {"usage": {"prompt_tokens": 3, "prompt_unit_price": "0", "prompt_price_unit": "0", "prompt_price": "0E-7", "completion_tokens": 0, "completion_unit_price": "0", "completion_price_unit": "0", "completion_price": "0E-7", "total_tokens": 3, "total_price": "0E-7", "currency": "USD", "latency": 1.7923474870622158}}}
> 
> data: {"event": "tts_message_end", "conversation_id": "d55b4aee-baa3-436d-bdd5-49e9b5b8271b", "message_id": "7afff110-b087-4f15-a7d1-7caf3309debb", "created_at": 1725437975, "task_id": "c8e0d836-fc21-407f-875c-5d5bed4aea20", "audio": ""}
> ```
> 
> ### ✔️ Expected Behavior
> _No response_
> 
> ### ❌ Actual Behavior
> _No response_

i check the code,the chunk variable has a value but the if judgment fails, so it returns empty. I don't understand why.

https://github.com/langgenius/dify/blob/14af87527f219d5bbbc04f47af5d16f56adec1fb/api/core/model_runtime/model_providers/openai_api_compatible/llm/llm.py#L433-L437


chunk value:
```
data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"role":"assistant"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"你好"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"！"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"很高兴"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"能"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"为你"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"提供"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"帮助"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"。"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"如果有"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"任何"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"问题"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"，请"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"随时"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"告诉我"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":"。"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-41147ad50d5c464a80642bc3c74c2e0d","object":"chat.completion.chunk","created":1725515847,"model":"Qwen-72B-Chat-Int4","choices":[{"index":0,"delta":{"content":""},"finish_reason":"stop"}],"usage":{"prompt_tokens":20,"total_tokens":36,"completion_tokens":16}}

data: [DONE]
```

**Comment by youqugit** [comment]
更新代码，重新部署解决不显示问题
