### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by Sf-teacherspace** [langgenius/dify#7970]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![Skærmbillede 2024-09-04 kl  09 15 16](https://github.com/user-attachments/assets/92261ea2-cbe3-4e85-9ad8-9f0c00c2821d)
![Skærmbillede 2024-09-04 kl  09 21 06](https://github.com/user-attachments/assets/c3dc56f8-69ba-48ac-8a2e-6465d76e0a1d)

### ✔️ Expected Behavior

I’m working on creating a chatbot in your program. I’ve built a knowledge base that the chatbot draws information from. Previously, it cited the sources it took from the knowledge base, but it no longer does that. Is this something I’ve done? I’ve been experimenting a bit with the prompt, but could that be where the issue lies? I would like the chatbot to indicate where it gets its information from. It should primarily take it from the knowledge base. What has gone wrong?

### ❌ Actual Behavior

It has stopped making citations from the knowledge base

**Comment by Sf-teacherspace** [comment]
@dosu
How could the settings look like:
Verify Retrieval Settings:

Ensure that the retrieval method and parameters (TopK value and recall threshold) are appropriately configured. These settings significantly impact the recall of relevant segments from the knowledge base.
Adjusting these parameters can improve the quality and relevance of the retrieved segments.

**Comment by Sf-teacherspace** [comment]
![Skærmbillede 2024-09-04 kl  11 20 55](https://github.com/user-attachments/assets/19736358-b879-4891-9567-b7dd56ede4d3)
It still doesn't apply citations :/

**Comment by Sf-teacherspace** [comment]
@dosu

**Comment by Sf-teacherspace** [comment]
@takatost please view the historic and help me solve the issue

**Comment by Sf-teacherspace** [comment]
@dosu I need more help! the testing doesnt work

**Comment by Sf-teacherspace** [comment]
It seems like it doesnt take knowledge from the base, put outside the base. What car I do to ensure it takes from the base?

**Comment by Sf-teacherspace** [comment]
@dosu

**Comment by Sf-teacherspace** [comment]
![Skærmbillede 2024-09-04 kl  14 08 40](https://github.com/user-attachments/assets/844a7841-91ec-481c-8fc8-d3eccd3b2b7f)
It says 0 tokens at knowledge - thats the problem??

**Comment by crazywoola** [comment]
Hello, can you make a minimal reproducable DSL, so we can take a look at.

**Comment by ArnaudGardille** [comment]
Hi! Same issue as original poster with basic chatbot and agent. Still works well with Chatflow.
