### ISSUE TITLE
Integrating Langsmith occurs an internal error  with selfhosted 0.7.3

### ISSUE THREAD

**Issue by iray1991** [langgenius/dify#7973]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Dify 0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/8a59f2c5-a245-4072-b766-253fae4eb29d)

**Comment by crazywoola** [comment]
Please provide the container logs.

**Comment by crazywoola** [comment]
docker compose logs

**Comment by crazywoola** [comment]
@charli117  Can you take a look at this? It seems there is a 500 error in backend.

**Comment by charli117** [comment]
> @charli117 Can you take a look at this? It seems there is a 500 error in backend.

Ok, let me have a look

**Comment by charli117** [comment]
![image](https://github.com/user-attachments/assets/3418dc23-26d0-4862-8b94-6720d473c230)
@iray1991 
I did not find any problem according to your parameter configuration. Please confirm whether  network is normal

**Comment by iray1991** [comment]
@charli117 I tried local host in my Windows, Alibaba cloud, Tencent Cloud, all the same err; maybe I can send you Langsmith API so you can have a try on your version?

**Comment by iray1991** [comment]
2024-09-05 00:03:10 api-1         |     project_key = OpsTraceManager.get_trace_config_project_key(tracing_config, tracing_provider)
2024-09-05 00:03:10 api-1         |   File "/app/api/core/ops/ops_trace_manager.py", line 265, in get_trace_config_project_key
2024-09-05 00:03:10 api-1         |     return trace_instance(tracing_config).get_project_key()
2024-09-04 18:18:54 worker-1      | [2024-09-04 10:18:54,620: INFO/MainProcess] HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-09-05 00:03:10 api-1         | AttributeError: 'LangSmithDataTrace' object has no attribute 'get_project_key'

**Comment by charli117** [comment]
@iray1991 LangSmith  does not complete the project link generation method. Therefore,It caused a configuration exception, use #7996  temporary fix
