### ISSUE TITLE
The Markdown multi-table rendering in the chat interface often gets misaligned or fails to render

### ISSUE THREAD

**Issue by GeorgeGalway** [langgenius/dify#7974]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7~0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/abe9e54d-a044-4f9e-b989-9bb813cc8958)

### ✔️ Expected Behavior

To render correctly and differentiate based on tables.

### ❌ Actual Behavior

Incorrect rendering or failure to render properly.

**Comment by crazywoola** [comment]
Can you provide the texts?

**Comment by GeorgeGalway** [comment]
> Can you provide the texts?

{
  "text": "### 1.1.1 页面描述：\n\n页面名称：用户信息配置页面\n\n页面用途：用于展示和管理系统中的用户详细信息，包括查看、编辑和筛选用户数据。\n\n页面入口：主菜单 > 用户管理 > 用户信息配置\n\n初始页面：默认展示所有用户数据，按注册日期降序排列。\n\n分页机制：每页显示20条记录，支持跳转到指定页码。\n\n样式布局：金额字段（如账户余额）需有千位符号，并保留两位小数右对齐。其他字段根据内容自适应宽度。\n\n### 1.1.2 列表字段：\n\n| 字段表头名称           | 字段解释               | 字段样例                |\n|------------------------|------------------------|-------------------------|\n| 用户ID                 | 系统生成的唯一标识     | 123456                  |\n| 用户名                 | 用户的登录名           | johndoe                 |\n| 密码哈希               | 加密后的密码           | $2a$10$...              |\n| 电子邮件               | 用户的邮箱地址         | johndoe@example.com     |\n| 联系电话               | 用户的联系电话         | +8613800138000          |\n| 注册日期               | 用户注册时间           | 2023-01-01              |\n| 最近登录时间            | 上次登录时间           | 2023-10-01 12:00        |\n| 用户状态               | 当前状态（启用/禁用）   | 启用                    |\n| 用户角色               | 分配的角色权限         | 管理员                  |\n| 证件类型               | 身份证、护照等类型     | 身份证                  |\n| 证件号码               | 对应证件号码           | 110101199003076512      |\n| 开户银行               | 银行名称               | 中国银行                |\n| 银行卡号               | 银行账号               |-                        |-                        |-                        |-                        |-                        |-                        |-                        |-                        |-                        |-                        |-                        |-                        |-                        |\n\n### 1.1.3 筛选和排序：\n\n筛选条件：\n\n| 筛选项               \t\t| 默认值   \t\t| 筛选框类型   \t\t| 输入限制   \t\t|-关联约束       \t\t\t|\n|-|-|-|-|-|\n注册日期    \t\t\t空        \t\t日期选择器  \t\t不超过当前日期    \t 无              \n用户状态    \t\t 全部      \t 下拉选择框  \t 启用/禁用          无              \n用户角色    \t\t 全部      \t 多选下拉框   -                   -                \n性别        \t\t 全部      \t 单选按钮      男/女/其他          无              \n手机号码认证状态 \t 全部      \t 下拉选择框  \t 已认证/未认证       无 \n\n默认排序规则：按注册日期降序排列。\n\n### 1.1.4 交互和操作：\n\n描述用户可以对列表数据进行哪些操作，如选择、删除、编辑等。\n\n#### 编辑用户信息：\n\n允许管理员编辑用户基本信息，如用户名、电子邮件等。\n\n表单字段说明：\n\n- **用户名**: 文本输入框, 默认值: johndoe, 输入限制: 50字符以内, 是否必填: 是\n- **电子邮件**: 文本输入框, 默认值: johndoe@example.com, 输入限制: 邮箱格式验证, 是否必填: 是\n- **联系电话**: 文本输入框, 默认值: +8613800138000, 输入限制: 电话号码格式验证, 是否必填: 否\n\n验证规则：\n- 邮箱格式必须符合标准邮箱格式。\n- 联系电话需符合国际电话号码格式。\n\n操作异常：\n错误消息以红色字体显示在对应字段下方，例如“请输入有效的邮箱地址”。\n\n#### 删除用户：\n\n允许管理员删除不再需要的用户记录。删除前需确认操作，以防误删。\n\n### 1.1.5 性能要求：\n\n在处理大量数据时，列表加载时间不超过3秒，支持快速分页切换与筛选结果实时更新。",
  "usage": {
    "prompt_tokens": 1402,
    "prompt_unit_price": "2.50",
    "prompt_price_unit": "0.000001",
    "prompt_price": "0.0035050",
    "completion_tokens": 863,
    "completion_unit_price": "10.00",
    "completion_price_unit": "0.000001",
    "completion_price": "0.0086300",
    "total_tokens": 2265,
    "total_price": "0.0121350",
    "currency": "USD",
    "latency": 13.259290382266045
  },
  "finish_reason": "stop"
}

![image](https://github.com/user-attachments/assets/4d1bcda6-6256-4cc0-8dbd-a438b0cba45b)
THX

**Comment by GeorgeGalway** [comment]
> Can you provide the texts?

Could you help me? This bug has already affected the output of our large documents, and for now, we can only temporarily replace it with FastGPT

**Comment by GeorgeGalway** [comment]
> Can you provide the texts?

I tested it and found that this issue is quite severe in the GPT-4o model. It's slightly better in GPT-4o-0806, but there are still occurrences of serializing issues.

**Comment by 2019YKL** [comment]
I'm having the same problem, I'm sure there's nothing wrong with my format.

**Comment by crazywoola** [comment]
> I'm having the same problem, I'm sure there's nothing wrong with my format.

Can you provide the texts as well?

**Comment by 2019YKL** [comment]
> > I'm having the same problem, I'm sure there's nothing wrong with my format.
> 
> Can you provide the texts as well?

| GPT-4o | Llama-70b | DeepSeek |
|-----|-------|---------|
|{{#llm.text#}}|{{#17261508557390.text#}}|{{#17261524414940.text#}}|

**Comment by iamjoel** [comment]
> > > I'm having the same problem, I'm sure there's nothing wrong with my format.
> > 
> > 
> > Can you provide the texts as well?
> 
> ```
> | GPT-4o | Llama-70b | DeepSeek |
> |-----|-------|---------|
> |{{#llm.text#}}|{{#17261508557390.text#}}|{{#17261524414940.text#}}|
> ```

I can't reproduce. 
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/ac603d1a-5a97-4252-bc2a-6350d91a2310">

**Comment by GeorgeGalway** [comment]
> > > > I'm having the same problem, I'm sure there's nothing wrong with my format.我遇到了同样的问题，我确定我的格式没有问题。
> > > 
> > > 
> > > Can you provide the texts as well?您能提供文本吗？
> > 
> > 
> > ```
> > | GPT-4o | Llama-70b | DeepSeek |
> > |-----|-------|---------|
> > |{{#llm.text#}}|{{#17261508557390.text#}}|{{#17261524414940.text#}}|
> > ```
> 
> I can't reproduce. 我无法复制。 <img alt="image" width="1393" src="https://private-user-images.githubusercontent.com/2120155/367136732-ac603d1a-5a97-4252-bc2a-6350d91a2310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTc4ODYsIm5iZiI6MTcyNjE5NzU4NiwicGF0aCI6Ii8yMTIwMTU1LzM2NzEzNjczMi1hYzYwM2QxYS01YTk3LTQyNTItYmMyYS02MzUwZDkxYTIzMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDMxOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzBjNjMyNGI2OWRjZTFlNjMyNGZlN2EyODkwYjk1Yzc5ZjIzNGVkMWUwMmE4MmVlMjk0ZDQ2OGQxN2JkMTlmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TZF7ljEEkBI4Tgub19ufD9S_F_CRJlqOPJtfZvdFSL4">

Please use the GPT4O model and generate tables with more rows. It would be preferable if a single response includes multiple table outputs.

**Comment by iamjoel** [comment]
> > Can you provide the texts?
> 
> { "text": "### 1.1.1 页面描述：\n\n页面名称：用户信息配置页面\n\n页面用途：用于展示和管理系统中的用户详细信息，包括查看、编辑和筛选用户数据。\n\n页面入口：主菜单 > 用户管理 > 用户信息配置\n\n初始页面：默认展示所有用户数据，按注册日期降序排列。\n\n分页机制：每页显示20条记录，支持跳转到指定页码。\n\n样式布局：金额字段（如账户余额）需有千位符号，并保留两位小数右对齐。其他字段根据内容自适应宽度。\n\n### 1.1.2 列表字段：\n\n| 字段表头名称 | 字段解释 | 字段样例 |\n|------------------------|------------------------|-------------------------|\n| 用户ID | 系统生成的唯一标识 | 123456 |\n| 用户名 | 用户的登录名 | johndoe |\n| 密码哈希 | 加密后的密码 | $2a$10$... |\n| 电子邮件 | 用户的邮箱地址 | [johndoe@example.com](mailto:johndoe@example.com) |\n| 联系电话 | 用户的联系电话 | +8613800138000 |\n| 注册日期 | 用户注册时间 | 2023-01-01 |\n| 最近登录时间 | 上次登录时间 | 2023-10-01 12:00 |\n| 用户状态 | 当前状态（启用/禁用） | 启用 |\n| 用户角色 | 分配的角色权限 | 管理员 |\n| 证件类型 | 身份证、护照等类型 | 身份证 |\n| 证件号码 | 对应证件号码 | 110101199003076512 |\n| 开户银行 | 银行名称 | 中国银行 |\n| 银行卡号 | 银行账号 |- |- |- |- |- |- |- |- |- |- |- |- |- |\n\n### 1.1.3 筛选和排序：\n\n筛选条件：\n\n| 筛选项 \t\t| 默认值 \t\t| 筛选框类型 \t\t| 输入限制 \t\t|-关联约束 \t\t\t|\n|-|-|-|-|-|\n注册日期 \t\t\t空 \t\t日期选择器 \t\t不超过当前日期 \t 无 \n用户状态 \t\t 全部 \t 下拉选择框 \t 启用/禁用 无 \n用户角色 \t\t 全部 \t 多选下拉框 - - \n性别 \t\t 全部 \t 单选按钮 男/女/其他 无 \n手机号码认证状态 \t 全部 \t 下拉选择框 \t 已认证/未认证 无 \n\n默认排序规则：按注册日期降序排列。\n\n### 1.1.4 交互和操作：\n\n描述用户可以对列表数据进行哪些操作，如选择、删除、编辑等。\n\n#### 编辑用户信息：\n\n允许管理员编辑用户基本信息，如用户名、电子邮件等。\n\n表单字段说明：\n\n- **用户名**: 文本输入框, 默认值: johndoe, 输入限制: 50字符以内, 是否必填: 是\n- **电子邮件**: 文本输入框, 默认值: [johndoe@example.com](mailto:johndoe@example.com), 输入限制: 邮箱格式验证, 是否必填: 是\n- **联系电话**: 文本输入框, 默认值: +8613800138000, 输入限制: 电话号码格式验证, 是否必填: 否\n\n验证规则：\n- 邮箱格式必须符合标准邮箱格式。\n- 联系电话需符合国际电话号码格式。\n\n操作异常：\n错误消息以红色字体显示在对应字段下方，例如“请输入有效的邮箱地址”。\n\n#### 删除用户：\n\n允许管理员删除不再需要的用户记录。删除前需确认操作，以防误删。\n\n### 1.1.5 性能要求：\n\n在处理大量数据时，列表加载时间不超过3秒，支持快速分页切换与筛选结果实时更新。", "usage": { "prompt_tokens": 1402, "prompt_unit_price": "2.50", "prompt_price_unit": "0.000001", "prompt_price": "0.0035050", "completion_tokens": 863, "completion_unit_price": "10.00", "completion_price_unit": "0.000001", "completion_price": "0.0086300", "total_tokens": 2265, "total_price": "0.0121350", "currency": "USD", "latency": 13.259290382266045 }, "finish_reason": "stop" }
> 
> ![image](https://private-user-images.githubusercontent.com/24989842/364593328-4d1bcda6-6256-4cc0-8dbd-a438b0cba45b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTQ1MjQsIm5iZiI6MTcyNjE5NDIyNCwicGF0aCI6Ii8yNDk4OTg0Mi8zNjQ1OTMzMjgtNGQxYmNkYTYtNjI1Ni00Y2MwLThkYmQtYTQzOGIwY2JhNDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAyMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2N2JiNzQzMzFhZDkxMmFiMWQ0MjBkMGIwMTQ4MmYzZDdiNDMwOTkzODU2Mzg5MGY0Yjk2YmU0MTNlMGQwYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5lrGwinGYv8uZtssThmCzNnbplK-nlqsyZJF-jUjdog) THX

Could you give the only markdown text without \n like chars and then put it around with ```. Eq:
```
| GPT-4o | Llama-70b | DeepSeek |
|-----|-------|---------|
|{{#llm.text#}}|{{#17261508557390.text#}}|{{#17261524414940.text#}}|
```

So that I can know the issue is caused by markdown parser or the wrong markdown format. @GeorgeGalway

**Comment by iamjoel** [comment]
I have use the GPT4O model and generate tables with more rows. Still can't reproduce.
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/7308c1ee-d848-4a0e-bd8f-aaa6ef118983">

**Comment by GeorgeGalway** [comment]
> I have use the GPT4O model and generate tables with more rows. Still can't reproduce. <img alt="image" width="1679" src="https://private-user-images.githubusercontent.com/2120155/367138636-7308c1ee-d848-4a0e-bd8f-aaa6ef118983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTkzMTksIm5iZiI6MTcyNjE5OTAxOSwicGF0aCI6Ii8yMTIwMTU1LzM2NzEzODYzNi03MzA4YzFlZS1kODQ4LTRhMGUtYmQ4Zi1hYWE2ZWYxMTg5ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDM0MzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI4YzA5MWYzZjhlOWY0OTUzNjUxYzBiNTYwYmZhZGE0Y2U4MDdlYTY2Yjk3OWVmZjJlZDI0ODM0NjhjMThlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Poyn5rXGjo_5iOcLwRDpsLRnwakZ1tiFWfKs1RQ0-CU">

I will send you a DSL file. Could you try it out and choose 'List Requirements'? The prompt is: 'Please design a user login form with at least 10 fields.'
![image](https://github.com/user-attachments/assets/fa11f378-e63b-41a4-8d10-cbfaa6d3b3aa)
[DSL.zip](https://github.com/user-attachments/files/16988239/DSL.zip)

**Comment by iamjoel** [comment]
Ok, I'll try it later.

**Comment by iamjoel** [comment]
I can reproduce it by your DSL. I find the problem is caused by LLM output the wrong markdown table format.
<img width="352" alt="image" src="https://github.com/user-attachments/assets/aad50777-fffc-4978-92e3-be44b3f78216">

**Comment by GeorgeGalway** [comment]
> I can reproduce it by your DSL. I find the problem is caused by LLM output the wrong markdown table format. <img alt="image" width="352" src="https://private-user-images.githubusercontent.com/2120155/367166883-aad50777-fffc-4978-92e3-be44b3f78216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDc5MjMsIm5iZiI6MTcyNjIwNzYyMywicGF0aCI6Ii8yMTIwMTU1LzM2NzE2Njg4My1hYWQ1MDc3Ny1mZmZjLTQ5NzgtOTJlMy1iZTQ0YjNmNzgyMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDYwNzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjdkNDc0N2Y2NzhhYTNkM2MwNTEzYzBkNTQxYWQ4OGYyYjNhZTgwNTdiNzY1MTUwYjRiNDVlMWZlOWRiYmViNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9WzL-Fiz4tgsN-Kb3GgjFmH4XfP_CWY_6rh_yqBKWE0">

With the same model and the same prompt, FastGPT just works better. Anyway, thank you, I'll look for the reason myself.
