### ISSUE TITLE
Modifying document segmenting in Question & Answer format leads to all data being erased

### ISSUE THREAD

**Issue by dc-vin** [langgenius/dify#7977]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Modifying document segmenting in Question & Answer format leads to all data being erased
![image](https://github.com/user-attachments/assets/11b65dcc-67dc-4a13-812e-0efde9cfd8e6)
By the way, have you considered supporting the setting of QA mode when creating a document through an API?

**Comment by crazywoola** [comment]
> By the way, have you considered supporting the setting of QA mode when creating a document through an API?

I think this is a good idea, maybe you can open a pr to fulfill this feature, because we are a little bit busy these days.

**Comment by dc-vin** [comment]
> This 'erased' behavior is expected, because we will let LLM to split original texts into Q&A pairs.

A colleague modified the QA mode a couple of days ago, which resulted in the deletion of long-term maintained data without any backup. This led to criticism from our supervisor. I suggest notifying users that their data will be erased when modifying the mode.

**Comment by dc-vin** [comment]
> > By the way, have you considered supporting the setting of QA mode when creating a document through an API?
> 
> I think this is a good idea, maybe you can open a pr to fulfill this feature, because we are a little bit busy these days.

If I have time this month, I will try to open a PR.

**Comment by dc-vin** [comment]
> This 'erased' behavior is expected, because we will let LLM to split original texts into Q&A pairs.

I discovered a new bug.
when I set the QA mode and change the language type, it automatically reverts to English after saving.
