### ISSUE TITLE
Performance Degradation after Load Testing on Dify - Low Throughput and Concurrency

### ISSUE THREAD

**Issue by yancyuu** [langgenius/dify#7978]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After conducting load testing on Dify, we noticed significant performance degradation. Below are the details:

	•	System Specs:
	•	8 cores, 16 GB RAM
	•	2 pods deployed
	•	Load Testing Results:
	•	Without model integration:
	•	Concurrency: Low
	•	Throughput: Only reaching up to 11 requests per second
	•	With model integration:
	•	Concurrency: Even lower
	•	Throughput: Only 6 requests per second
	
	This performance seems unexpectedly low for the given system specifications. Could there be an issue with the configuration or is there any optimization suggestion to improve the throughput and concurrency?

Any guidance on this would be appreciated. Thank you!

This issue summary outlines the performance problems and requests guidance for potential fixes or optimizations.

### ✔️ Expected Behavior

并发达到200

### ❌ Actual Behavior

吞吐量只能到6
<img width="726" alt="1" src="https://github.com/user-attachments/assets/860d363d-9fba-4f97-8303-d790911f8ea9">
<img width="927" alt="2" src="https://github.com/user-attachments/assets/83cfeed5-5de7-4afb-8316-083c53c95f8b">

**Comment by Seayon** [comment]
Have you configured the SERVER_WORKER_AMOUNT parameter in your environment setting? @yancyuu
