### ISSUE TITLE
HTTPConnectionPool(host='weaviate', por 8080): Read timed out. (read timeout=60) when creating knowledge base

### ISSUE THREAD

**Issue by iray1991** [langgenius/dify#7997]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Dify 0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/645c24ca-a475-4a18-a34e-247accf46131)

**Comment by crazywoola** [comment]
Please attach the logs of the vector db container.

Maybe you can try `docker compose --profile weaviate -p dify up -d`.
