### ISSUE TITLE
OpenAi Key输入后报错

### ISSUE THREAD

**Issue by Laggar** [langgenius/dify#80]
![image](https://github.com/langgenius/dify/assets/4003608/cbf2efec-7e48-449c-adf1-554c50ef8c60)
肯定是有效得，本地代码 API调用都是通得

{"result": "error", "error": "Invalid response object from API: '{\"object\":\"error\",\"message\":\"Only /v1/chat/completions && /v1/embeddings allowed now , your path {/moderations}\",\"code\":40301}' (HTTP response code was 403)"}

**Comment by takatost** [comment]
看着不像 OpenAI 返回的信息

**Comment by killpanda** [comment]
这个像是国内代理封装的API，然后没有开放`/moderations`接口

**Comment by takatost** [comment]
免费的接口为啥不代理呢

**Comment by killpanda** [comment]
我试了两家都有这个问题，不知道原因。
我也是一步一步走近科学发现的。。。

**Comment by dsbruce** [comment]
> 封装的API

请问有找到原因吗? 我的也是同样的问题

**Comment by takatost** [comment]
可以按照这位同学提交 PR #85 中的配置项来规避这一问题，增加环境变量配置：
```
DISABLE_PROVIDER_CONFIG_VALIDATION: 'true'
```

**Comment by 2023Felix** [comment]
是不是因为是在国内服务器部署的，无法直接连到openai认证？需要科学上网？

**Comment by kevinhorse** [comment]
要修改了代码也不起作用，是不是生效需要修改后有权限的人构造修改镜像才行，能不能有权限的构造一个DISABLE_PROVIDER_CONFIG_VALIDATION: 'True'的 image，

**Comment by yxzu** [comment]
> 

蹲个后续

**Comment by 2023Felix** [comment]
当时就想自己搭在微信上玩，然后摸索着使用下国内的服务器。
现在没有在玩这个了
谢谢你的帮助😊

---------------------


________________________________
发件人: yxzu ***@***.***>
发送时间: 2023年6月13日 1:42
收件人: langgenius/dify ***@***.***>
抄送: 2023Felix ***@***.***>; Comment ***@***.***>
主题: Re: [langgenius/dify] OpenAi Key输入后报错 (Issue #80)


蹲个后续

**Comment by isunkit** [comment]
使用的API必须得是plus的吗？我的不是plus，绝对原生API，输入后报错
