### ISSUE TITLE
When the condition node appears before the iteration node, the LLM node will not be able to output the stream

### ISSUE THREAD

**Issue by cowcomic** [langgenius/dify#8005]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Build a workflow like this

![image](https://github.com/user-attachments/assets/297e5269-772e-4caa-89f3-2dbc8f7a66b7)

### ✔️ Expected Behavior

LLM can output stream

### ❌ Actual Behavior

LLM do not output stream

**Comment by crazywoola** [comment]
<img width="1456" alt="image" src="https://github.com/user-attachments/assets/8e8556d1-9ce8-4c28-977b-7b4664d82485">

Can not reproduce this on latest version.

**Comment by cowcomic** [comment]
> <img alt="image" width="1456" src="https://private-user-images.githubusercontent.com/100913391/364621543-8e8556d1-9ce8-4c28-977b-7b4664d82485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTQ2ODIsIm5iZiI6MTcyNTUxNDM4MiwicGF0aCI6Ii8xMDA5MTMzOTEvMzY0NjIxNTQzLThlODU1NmQxLTljZTgtNGMyOC05NzdiLTdiNDY2NGQ4MjQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNTMzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjZhYWM5YzJhZDEwY2EyZDgxYTI4YmQ2MmQxZDk1NWFkNWE3YzIwNTY2Njk3ZWRiZDg2ZDA3ZTY1ZTFjNDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z9w0JgVppqc7wcDZIpxlGdKzVg-W4tCxG0HrhLILtxc">
> Can not reproduce this on latest version.

@crazywoola 
There needs to be an iteration node after the condition node. The process you posted is fine on 0.16.13, but it won't work after adding the iteration node.

> <img alt="image" width="1456" src="https://private-user-images.githubusercontent.com/100913391/364621543-8e8556d1-9ce8-4c28-977b-7b4664d82485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTQ5NjgsIm5iZiI6MTcyNTUxNDY2OCwicGF0aCI6Ii8xMDA5MTMzOTEvMzY0NjIxNTQzLThlODU1NmQxLTljZTgtNGMyOC05NzdiLTdiNDY2NGQ4MjQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNTM3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTU4NTE0OGQxMjhlNTRmYzIyYzk4MmM1NmE2ZjliNGU3NmNlMjk0MmFkZDc5NzNiYzAzYTdlNjlkZWU3ODhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._vYCBq1A9Hm9UHmvXE-TCbBn3TzNSa95pY0Ct8tLRXs">
> Can not reproduce this on latest version.

@crazywoola 
There needs to be an iteration node after the condition node. The process you posted is fine on 0.16.13, but it won't work after adding the iteration node.

**Comment by cowcomic** [comment]
![image](https://github.com/user-attachments/assets/31f3db77-4ec0-432e-a9ec-8880fc96c3de)
