### ISSUE TITLE
The `requests` module in sandbox doesn't function well

### ISSUE THREAD

**Issue by rickythink** [langgenius/dify#8008]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3 

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1. Create a sandbox node
2. Add such code below
```
import requests

def main() -> dict:
    url = "https://google.com"
    response = requests.get(url)
```
<img width="376" alt="image" src="https://github.com/user-attachments/assets/b4d34fa1-e79b-456e-9a59-99a8df5583b1">

3. Get error
<img width="360" alt="image" src="https://github.com/user-attachments/assets/f0239fdb-d154-41aa-9b0f-97df00f5df0a">

### ✔️ Expected Behavior

This happens both on Cloud & self-host

**Comment by rickythink** [comment]
Could this issue be related to the removal of “Advanced Dependencies” from the panel?

**Comment by rickythink** [comment]
And the pic below shows the site-packages of sandbox v0.2.6 in `/usr/local/lib/python3.10/site-packages`

<img width="1900" alt="image" src="https://github.com/user-attachments/assets/1ba13cf9-264d-4ab6-b74e-cf70c095a513">

It does contain `requests` and `charset_normalizer`, but I have no idea why it fails

**Comment by crazywoola** [comment]
FYI, In 0.2.6, we no longer need to include it in advance settings. I think you can try httpx.

**Comment by rickythink** [comment]
closed by https://github.com/langgenius/dify/pull/8397
