### ISSUE TITLE
hit-testing suddenly became very slow

### ISSUE THREAD

**Issue by ryanwong2023** [langgenius/dify#8009]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Without modifying anything, hit-testing suddenly became very slow

### ✔️ Expected Behavior

As fast as before

### ❌ Actual Behavior

I will wait for more than 60 seconds…

**Comment by crazywoola** [comment]
Well this is not help for investigating what's really going on.
