### ISSUE TITLE
show "console/api/apps/" not found , when add annotations 

### ISSUE THREAD

**Issue by baibm** [langgenius/dify#8011]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1484" alt="image" src="https://github.com/user-attachments/assets/6340f2e4-0cca-4970-b2bb-c8ae6a5ac40f">

### ✔️ Expected Behavior

add annations success

### ❌ Actual Behavior

add annations failed

**Comment by crazywoola** [comment]
Can not reproduce this in latest cloud version. Make sure you have set the correct environment variables.
