### ISSUE TITLE
The numpy library doesn't work in sandbox.

### ISSUE THREAD

**Issue by yuweimian-shy** [langgenius/dify#8016]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. I have write the third package in the dependencies/python-requirements.txt and rebuild the sandbox image. The following is my dockerfile to rebuild sandbox image.
```
# FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/ubuntu:20.04
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/python:3.10.14

RUN apt-get clean \
    && echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian testing main" > /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y pkg-config libseccomp-dev wget xz-utils \
    && apt-get install -y --no-install-recommends zlib1g=1:1.3.dfsg+really1.3.1-1 expat=2.6.2-1 perl=5.38.2-5 libsqlite3-0=3.46.0-1

# copy main binary to /main
COPY main /main

# copy initial env
COPY env /env

# copy cmd
COPY cmd /cmd/


# copy config file
COPY conf/config.yaml /conf/config.yaml
# copy python dependencies
COPY dependencies/python-requirements.txt /dependencies/python-requirements.txt
RUN pip3 install -r /dependencies/python-requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN rm -rf /var/lib/apt/lists/* \
    && chmod +x /main \
    && chmod +x /env \
    && pip3 install jinja2 requests numpy httpx PySocks httpx[socks] -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && wget -O /opt/node-v20.11.1-linux-x64.tar.xz https://npmmirror.com/mirrors/node/v20.11.1/node-v20.11.1-linux-x64.tar.xz \
    && tar -xvf /opt/node-v20.11.1-linux-x64.tar.xz -C /opt \
    && ln -s /opt/node-v20.11.1-linux-x64/bin/node /usr/local/bin/node \
    && rm -f /opt/node-v20.11.1-linux-x64.tar.xz \
    && /env \
    && rm -f /env

ENTRYPOINT ["/main"]
```
the following is my python-requirements.txt
```
tabulate
numpy
tqdm
pandas
```
2. I replaced the sandbox image source in docker-compose with my own sandbox image and run docker compose up -d.
3. when i import the numpy , it occur the following error; but  When I import other libraries like tqdm and tabulate, there is no problem. Can you tell me is it a bug?
![1](https://github.com/user-attachments/assets/a0ff69ff-985f-4b8d-b355-3af625fd2b8b)
4. I found the dify 0.7.3 remove the python dependencies selector, then how can i install these dependencies?

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md

This is a known issue, we have no plan for fix this in this repo.
