### ISSUE TITLE
llm call tools error

### ISSUE THREAD

**Issue by kenneth-bro** [langgenius/dify#8018]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/c57b42b5-b697-4a68-9e7f-21c427505be9)
After the LLM is equipped with the tool Current_time, the tool call error will often appear, and the frequency will be relatively high. Why is this?

**Comment by crazywoola** [comment]
Try to use a smarter LLM. For those providers which do not support FC will use ReACT by default. So this happens.

**Comment by kenneth-bro** [comment]
> Try to use a smarter LLM. For those providers which do not support FC will use ReACT by default. So this happens.

Deepseek is to support Tools Call.must be support the function call?
