### ISSUE TITLE
In the created Agent application, when using custom tools (with both tool names and parameters in Chinese), the agent's thinking process occasionally encounters issues with Chinese character encoding, resulting in garbled text.

### ISSUE THREAD

**Issue by FAFUuser** [langgenius/dify#8021]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

In the created Agent application, when using custom tools (with both tool names and parameters in Chinese), the agent's thinking process occasionally encounters issues with Chinese character encoding, resulting in garbled text.

Through debugging, I found that the garbled text appears in the resp within llm.py (api/core/model_runtime/model_providers/stepfun/llm/llm.py). Additionally, even when there is garbled text, the parameters are not correctly parsed during tool invocation. For example, the parameter '中坤' goes through the process: '中坤' --> garbled text --> '中金', which leads to errors.

### ✔️ Expected Behavior

Action: {"action": "企业信息查询", "action_input": {"enterprise_name": "中坤化学"}

### ❌ Actual Behavior

Action: {"action": "\u4f01\u4e1a\u4fe1\u606f\u67e5\u8be2", "action_input": {"enterprise_name": "\u4e2d\u91d1\u5316\u5b66"}

**Comment by 1999single** [comment]
兄弟，你解决了吗

**Comment by FAFUuser** [comment]
在0.7.0版本我好像没有解决，这个是在工具调用过程中对工具名称编码和解码不一致出现的问题，有点难改，后面版本升级后，好像解决了。
