### ISSUE TITLE
An error occurred while using the tool, and the code is displayed

### ISSUE THREAD

**Issue by jlokys** [langgenius/dify#8022]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

There is a chance that the following problem will occur during the conversation. I don’t know where the problem is. I hope you can provide support.
![image](https://github.com/user-attachments/assets/94973b46-13ae-49a2-a5da-a0bba3344e7c)
![image](https://github.com/user-attachments/assets/3f397f68-c12b-40fb-9fd4-87537517a404)

I used langfuse to track it, specifically:
https://us.cloud.langfuse.com/project/cm0oz7lv5009ypumffzba18lf/traces/4488678d-8558-40c9-8681-2245a3db4f1e

**Comment by crazywoola** [comment]
What LLM do you use?

**Comment by crazywoola** [comment]
I think this is a similar question, change it to a smarter model should solve your problem. => https://github.com/langgenius/dify/issues/8018

**Comment by jlokys** [comment]
I'm using zhipu GLM-4-Flash, you should be right, I'm using a higher quality model, it hasn't appeared yet.  I need to continue testing and see.
