### ISSUE TITLE
It is necessary to upgrade the weaviate client.

### ISSUE THREAD

**Issue by jiandanfeng** [langgenius/dify#8034]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It is necessary to upgrade the weaviate client. When using Chinese full-text search, the current weaviate version does not support Chinese word segmentation, so the effect is not good. It needs to be upgraded to version 1.24. The gse or trigram word segmentation method is used to support Chinese word segmentation and improve the ability of weaviate Chinese full-text search.
weaviate tokenization link: https://weaviate.io/developers/weaviate/config-refs/schema#tokenization
weaviate client update link: https://weaviate.io/developers/weaviate/client-libraries/python/v3_v4_migration#installation

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by fujita-h** [comment]
I agree with this suggestion.
With the current (default) tokenizer settings, full-text search for Japanese barely works.
I tested the following steps and confirmed that the performance of full-text search in Japanese improved significantly.

1. Set the weaviate version to `1.24.25`
2. Add `USE_GSE: true` to the weaviate container's environment variables
3. Edit `weaviate-vectory.py` as follows
```
    def _default_schema(self, index_name: str) -> dict:
        return {
            "class": index_name,
            "properties": [
                {
                    "name": "text",
                    "dataType": ["text"],
                    "tokenization": "gse", # <- added this
                }
            ],
        }
```

When implementing, we also need to create a UI that switches the tokenizer depending on whether the document to be registered is in a language suitable for GSE.

**Comment by Scallions** [comment]
https://weaviate.io/developers/weaviate/search/similarity#named-vectors Named-vectors is also needed.

**Comment by fujita-h** [comment]
I'm focused on #12223.
