### ISSUE TITLE
Requires a simple retrieval model

### ISSUE THREAD

**Issue by jiandanfeng** [langgenius/dify#8036]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Added a new retrieval mode, the existing retrieval mode: "N-of-1 retrieval Mode"
 and "Multi-Path retrieval Mode", which are not friendly to simple RAG with only one knowledge base. 
 If choose "N-of-1 retrieval Mode", it will go through a large model judgment. If you choose "Multi-Path retrieval Mode", you will need to configure the rerank model. If the knowledge base itself has already configured the rerenk model, it will be repeated. Therefore, a simple retrieval mode is required, which requires neither large model judgment nor rerank model.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://docs.dify.ai/guides/knowledge-base/integrate-knowledge-within-application

- N-to-1 will be deprecated.
- You choose weighted score which does not need to configure the rerank model.
