### ISSUE TITLE
How do I start a container with docker run？

### ISSUE THREAD

**Issue by sunyclj** [langgenius/dify#8038]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0-beta1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The operating system version of the local computer is too low, so docker toolbox can only be installed and docker can be used, but Docker-compose up is not in line and various unsupported errors are reported. May I ask how to start the container through docker run after I pull down all the images?
The error information is as follows
"ERROR: The Compose file '.\docker-compose.yaml' is invalid because:
Unsupported config option for x-shared-env: 'CELERY_WORKER_AMOUNT'
Unsupported config option for networks: 'milvus'
Unsupported config option for volumes: 'oradata'
Unsupported config option for services: 'pgvecto-rs'"

**Comment by crazywoola** [comment]
You should upgrade your docker compose version.
