### ISSUE TITLE
BUG: The agent uses a tool, and if the tool returns a link, the final link replied by the agent is incorrect

### ISSUE THREAD

**Issue by xiaohuihuige** [langgenius/dify#8040]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [ ] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [ ] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [ ] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![02aa977d1339561b92cdd91ddce7bae](https://github.com/user-attachments/assets/3bb59671-3489-4727-be07-609bb131f491)
正确的链接http://m801.music.126.net/20240906113456/af23cec22bbd6df43053095b60b83af7/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/18708866715/5eb8/dad6/61f5/42c7fc29510cc3e521bb285c54489852.flac

**Comment by wuminghui-coder** [comment]
回复的错误链接http://m801.music.126.net/20240906113456/af23cec22bbd6df43053095b60b83af7/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/18708866715/5eb8/dad6/61f5/42c7fc29510cc3e521bb285c54454489852.flac

**Comment by wuminghui-coder** [comment]
左边日志追踪输出的链接是正常的，右边回复的链接不对

**Comment by crazywoola** [comment]
Can you provide the tool's configuration?

Please attach the original output of the answer as well.

**Comment by wuminghui-coder** [comment]
![1725601053457](https://github.com/user-attachments/assets/4c3db625-e20b-486c-b08f-903788b557db)


> Can you provide the tool's configuration?您能提供该工具的配置吗？
> 
> Please attach the original output of the answer as well.请附上答案的原始输出。

**Comment by wuminghui-coder** [comment]
![1725601081884](https://github.com/user-attachments/assets/77462a27-f117-4050-90fb-abb7972f03b2)


> Can you provide the tool's configuration?您能提供该工具的配置吗？
> 
> Please attach the original output of the answer as well.请附上答案的原始输出。

**Comment by wuminghui-coder** [comment]
![1725601110675](https://github.com/user-attachments/assets/615bf029-e3b8-41c8-ad48-452746f4457d)


> Can you provide the tool's configuration?您能提供该工具的配置吗？
> 
> Please attach the original output of the answer as well.请附上答案的原始输出。

**Comment by wuminghui-coder** [comment]
这是原始输出

🎵 遇见一曲，叙述着命运和相遇的美丽篇章。

你可以通过点击 [这里](http://m801.music.126.net/20240906140436/744e04c5a5d7f462531841884bb68677/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/18708866766715/5eb8/dad6/61f5/42c7fc29510cc3e521bb285c54489852.flac) 聆听这首歌曲。享受音乐带来的温暖，仿佛在悠长的岁月中，邂逅了一段尘封已久的缘分。

**Comment by wuminghui-coder** [comment]
![1725601319865](https://github.com/user-attachments/assets/0f38521a-40fe-4a78-ba8a-ab126a9ce82e)

**Comment by wuminghui-coder** [comment]
这是日志详情输出
![1725601319865](https://github.com/user-attachments/assets/ef652026-4736-4f1c-97c1-9bcdbadeff38)
"🎵 遇见一曲，叙述着命运和相遇的美丽篇章。\n\n你可以通过点击 [这里](http://m801.music.126.net/20240906140436/744e04c5a5d7f462531841884bb68677/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/18708866715/5eb8/dad6/61f5/42c7fc29510cc3e521bb285c54489852.flac) 聆听这首歌曲。享受音乐带来的温暖，仿佛在悠长的岁月中，邂逅了一段尘封已久的缘分。"

**Comment by wuminghui-coder** [comment]
原始输出和日志详情的歌曲链接不一样，日志详情是正常的，原始对话输出错误


> Can you provide the tool's configuration?您能提供该工具的配置吗？
> 
> Please attach the original output of the answer as well.请附上答案的原始输出。

**Comment by wuminghui-coder** [comment]
![1725601519525](https://github.com/user-attachments/assets/0d381322-d6b7-4f4c-9658-896d88ac7b41)
# 日志详情输出：
🎵 遇见一曲，叙述着命运和相遇的美丽篇章。\n\n你可以通过点击 [这里](http://m801.music.126.net/20240906140436/744e04c5a5d7f462531841884bb68677/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/18708866715/5eb8/dad6/61f5/42c7fc29510cc3e521bb285c54489852.flac) 聆听这首歌曲。享受音乐带来的温暖，仿佛在悠长的岁月中，邂逅了一段尘封已久的缘分。

# 原始输出:
🎵 遇见一曲，叙述着命运和相遇的美丽篇章。

你可以通过点击 [这里](http://m801.music.126.net/20240906140436/744e04c5a5d7f462531841884bb68677/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/18708866766715/5eb8/dad6/61f5/42c7fc29510cc3e521bb285c54489852.flac) 聆听这首歌曲。享受音乐带来的温暖，仿佛在悠长的岁月中，邂逅了一段尘封已久的缘分。

# 你可以看这个两个输出结果的链接不一样

**Comment by crazywoola** [comment]
`18708866715 `
`18708866766715 `

看起来是这里解析出错了，我不太确是哪儿的问题，可能是 markdown 那边？

**Comment by wuminghui-coder** [comment]
> `18708866715 ` `18708866766715 `
> 
> 看起来是这里解析出错了，我不太确是哪儿的问题，可能是 markdown 那边？
![6b0dee84afb9789dc808b3a9af398be](https://github.com/user-attachments/assets/f0b5689e-e74a-4513-aed2-d9169306b221)

是前端的问题，我看到后台的API消息，回复的消息是正确的，前端显示有问题
