### ISSUE TITLE
In the same conversation, modifying variables in inputs does not take effect.

### ISSUE THREAD

**Issue by dc-vin** [langgenius/dify#8050]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I created a knowledge base workflow and defined a variable called "type." Each time the user asks a question, they can choose a different "type," but I found that modifying the "type" on subsequent questions does not work.

**Comment by dc-vin** [comment]
The inputs variable for each conversation only takes effect the first time it is passed in. Continuous questioning and updating the variable value does not take effect.

**Comment by dc-vin** [comment]
Removing non-mandatory fields will cause this issue.

![image](https://github.com/user-attachments/assets/4037a8aa-9178-446d-ba86-7d9932edd016)

**Comment by crazywoola** [comment]
Please use the conversational variables instead. If you need to modify something, you need the conversational variables.

https://docs.dify.ai/guides/workflow/node/variable-assignment

**Comment by dc-vin** [comment]
> Please use the conversational variables instead. If you need to modify something, you need the conversational variables.
> 
> https://docs.dify.ai/guides/workflow/node/variable-assignment
@crazywoola 

I used variable assignment and passed the response_type field through the API. However, when switching options via the dropdown menu, I found that it did not take effect and still followed the old branch, resulting in the same response.



![image](https://github.com/user-attachments/assets/8d113248-9e54-4d43-af6b-76ea3e6d6014)
![image](https://github.com/user-attachments/assets/e6aeeb71-0e7e-487a-9ed9-8a1069651233)

**Comment by dc-vin** [comment]
![image](https://github.com/user-attachments/assets/1a25baf9-27f7-417b-a0ab-3b4fc1718a90)
