### ISSUE TITLE
When uploading files through the api interface(create_by_file), there will be a success and a failure?

### ISSUE THREAD

**Issue by PsycheJ** [langgenius/dify#8052]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When the create interface is called, there is one success and one failure; in the case of failure, the interface returns File not found.
![image](https://github.com/user-attachments/assets/16f70b52-4224-498e-90f0-58ab59e91488)

**Comment by crazywoola** [comment]
There is one thing needs to be clarified.
- Are those 2 files the same? If these 2 files are identical, the I guess it will happen.

**Comment by PsycheJ** [comment]
> There is one thing needs to be clarified.
> 
> * Are those 2 files the same? If these 2 files are identical, the I guess it will happen.

不，是不同的文件

**Comment by PsycheJ** [comment]
> There is one thing needs to be clarified.
> 
> * Are those 2 files the same? If these 2 files are identical, the I guess it will happen.

No, it's a different file.

**Comment by crazywoola** [comment]
Can you provide the container logs as well.
