### ISSUE TITLE
API responses return Unicode escape sequences instead of non-ASCII characters

### ISSUE THREAD

**Issue by zwbao** [langgenius/dify#8056]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Setup Dify using the provided instructions in the repository.
2. Make a request that generates a response containing non-ASCII characters (e.g., Chinese characters) via the Dify API.
3. Observe the response containing Unicode escape sequences instead of actual non-ASCII characters (e.g., `\u60a3\u8005` instead of `患者`).

#### Example request:

```
curl -X POST 'http://your-dify-instance/v1/workflows/run' \
--header 'Authorization: Bearer your-api-key' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {"input": "没事"},
    "response_mode": "blocking",
    "user": "test-user"
}'
```

#### Example response:

```
{"task_id": "425b967c-2d14-4258-971f-663ed7fa9538", "workflow_run_id": "16f459fd-8c85-46b3-851b-b093486315c5", "data": {"id": "16f459fd-8c85-46b3-851b-b093486315c5", "workflow_id": "0e5e69c6-ebb4-4f3f-8161-030dced6140d", "status": "succeeded", "outputs": {"text": "\u6ca1\u4e8b"}, "error": null, "elapsed_time": 0.0038245338946580887, "total_tokens": 0, "total_steps": 2, "created_at": 1725614787, "finished_at": 1725614787}}
```

### ✔️ Expected Behavior

The API should return the response with actual non-ASCII characters (e.g., Chinese characters) directly in the output without Unicode escape sequences. For example:
```
{"task_id": "425b967c-2d14-4258-971f-663ed7fa9538", "workflow_run_id": "16f459fd-8c85-46b3-851b-b093486315c5", "data": {"id": "16f459fd-8c85-46b3-851b-b093486315c5", "workflow_id": "0e5e69c6-ebb4-4f3f-8161-030dced6140d", "status": "succeeded", "outputs": {"text": "没事"}, "error": null, "elapsed_time": 0.0038245338946580887, "total_tokens": 0, "total_steps": 2, "created_at": 1725614787, "finished_at": 1725614787}}
```

### ❌ Actual Behavior

The API returns the response with non-ASCII characters encoded as Unicode escape sequences, making it difficult to read directly:

```
{"task_id": "425b967c-2d14-4258-971f-663ed7fa9538", "workflow_run_id": "16f459fd-8c85-46b3-851b-b093486315c5", "data": {"id": "16f459fd-8c85-46b3-851b-b093486315c5", "workflow_id": "0e5e69c6-ebb4-4f3f-8161-030dced6140d", "status": "succeeded", "outputs": {"text": "\u6ca1\u4e8b"}, "error": null, "elapsed_time": 0.0038245338946580887, "total_tokens": 0, "total_steps": 2, "created_at": 1725614787, "finished_at": 1725614787}}
```

**Comment by Hisir0909** [comment]
I think this is fine, unless you curl directly, most programs will automatically handle this problem

**Comment by Sos-Zachary** [comment]
@dosu  where dify to get the last sse back using unicode form, how can I modify this code so that it returns Chinese not unicode?

**Comment by Sos-Zachary** [comment]
@dosu in this project, Where is the backend code file that performs SSE via API, I need to modify it to not do Unicode escape sequences
