### ISSUE TITLE
Wrong image

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8058]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/ede32ef0-726e-4a91-a409-2c96d0913f08">

**Comment by AllenWriter** [comment]
Updated: https://docs.dify.ai/learn-more/extended-reading/retrieval-augment/retrieval
