### ISSUE TITLE
the search input box of  the document page  cannot input

### ISSUE THREAD

**Issue by deific** [langgenius/dify#8060]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/d361e8fc-ce88-4fb4-90ba-0b470471ac9f)
1.On the document page of the knowledge base, the search input box cannot input

### ✔️ Expected Behavior

The search input box allows you to input and search for matching results

### ❌ Actual Behavior

the search input box cannot input

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/pull/7782
