### ISSUE TITLE
The inputs variable set through the API can only take effect once.

### ISSUE THREAD

**Issue by dc-vin** [langgenius/dify#8063]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The inputs variable set through the API can only take effect once. 

![msedge_4ruTFLH14P](https://github.com/user-attachments/assets/7a905b60-af1d-4424-88ed-b8afb371edd5)

![msedge_fo63gbxlUE](https://github.com/user-attachments/assets/db9cf5c7-5f42-4431-8186-fec5e1b3b766)

**Comment by crazywoola** [comment]
Duplicated
- https://github.com/langgenius/dify/issues/7952
- https://github.com/langgenius/dify/issues/7846
