### ISSUE TITLE
Exception Handling in Workflow Design

### ISSUE THREAD

**Issue by lukefan** [langgenius/dify#8069]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It would be highly beneficial to incorporate an exception handling mechanism into the workflow design process.

Currently, certain large language models (LLMs) encounter errors when they are unable to answer a question. Additionally, there are instances where network errors or concurrency limits occur during API calls to these models' servers. When these issues arise, the workflow is immediately terminated.

I propose adding an exception handling feature that allows for retries or alternative actions when an error occurs. For example, if a model fails to respond, the system could either retry using the same model after a short delay or switch to a backup model for another attempt. This approach could follow a similar pattern to the try-catch-finally syntax in programming.

By implementing this feature, we could significantly improve the robustness and reliability of the workflow, ensuring smoother and more resilient processes.

Thank you for considering this enhancement!

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by lukefan** [comment]
I don't want to implement exception handling through code. Instead, I hope that exception handling functionality is included in the workflow of Dify.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/7891

**Comment by MrKenknight** [comment]
Not only try-except with the LLM block, suppose we have a workflow operating with many nodes. If one node fails, the entire workflow stops working. So, what needs to be try-excepted here is the workflow itself
