### ISSUE TITLE
Can the input fields for workflow customization be set to be hidden？

### ISSUE THREAD

**Issue by Aaron-YYH** [langgenius/dify#8073]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need to go through:
window.difyChatbotConfig = {
token: 'XXXXXXXXXXXXXXXX',
baseUrl: ' http://XXXXX ',
inputs: {
"XXX": "XXX"
},
When I was there, I found that I could only pass variables to custom input fields, but I didn't want to show the parameter content to the user. Can we add a field hiding function to hide custom fields

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This is duplicated question, I guess you need to skip the input parameters panel.

**Comment by xjose97x** [comment]
+1

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/8180
