### ISSUE TITLE
Knowledge base interface parameters are missing

### ISSUE THREAD

**Issue by 18075717849** [langgenius/dify#8074]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

/console/api/datasets/indexing-estimate This interface is the knowledge base segment preview and consumption interface, but why did you find that token consumption was canceled in the recent update?

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/72dfe73d-c754-4c79-bfa3-656fef10cfce)
I hope get reason!

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/22cfd66d-db3c-4d07-af7f-3994b6890797)

**Comment by crazywoola** [comment]
@JzoNgKVO

**Comment by 18075717849** [comment]
Why have master and 0.8.0 been removed?

**Comment by 18075717849** [comment]
@JzoNgKVO 
What is the reason for deleting it

**Comment by crazywoola** [comment]
> Cancel the cost estimation of Embedding in the knowledge base, inaccurate calculation will mislead users and waste resources, Embedding actual consumption cost is very small, it is recommended that users go to their own bills to see the accurate deduction

Feedback from our PM @18075717849
