### ISSUE TITLE
404 error has occurred when registering Azure AI Cohere rerank model

### ISSUE THREAD

**Issue by potofo** [langgenius/dify#8081]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1) Deploy Cohere-rerank-v3-multilingual to the Azure AI Service Model Catalog
2) Register the model provider with Dify
[Model Provider]->[Azure AI Studio]

Model Type: Rerank
Model Name: Cohere-rerank-v3-multilingual-xx
Azure AI Studio Endpoint:
https://Cohere-rerank-v3-multilingual-xx.eastus.models.ai.azure.com
API Key:************************

Error On Web screen: HTTP Error 404:Not Found 

![Error404_on_register_rerankmodel](https://github.com/user-attachments/assets/f46dcd99-1775-4f77-a5e7-c7f44fde82f6)

If you set the Model Type to LLM, you can register it, but it will not work and will not be recognized as a Rerank model.

### ✔️ Expected Behavior

Azure AI Studio's Cohere-rerank-v3-multilingua can be registered

### ❌ Actual Behavior

Error On Web screen: HTTP Error 404:Not Found 

![Error404_on_register_rerankmodel](https://github.com/user-attachments/assets/f46dcd99-1775-4f77-a5e7-c7f44fde82f6)

If you set the Model Type to LLM, you can register it, but it will not work and will not be recognized as a Rerank model.

**Comment by jumpei-tsutsui** [comment]
I am encountering the same issue.
Why is a JWT token required instead of an API token for the Rerank model?
How can I obtain a persistent JWT token from Azure AI Studio?

![s](https://github.com/user-attachments/assets/7ded70f7-c502-4d32-8f50-5a8e8f6d1457)

**Comment by grapswiz** [comment]
I alse see in https://github.com/langgenius/dify/pull/7549#issuecomment-2325557714
