### ISSUE TITLE
completion-messages api got error

### ISSUE THREAD

**Issue by vkiller** [langgenius/dify#8083]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

official version

### Cloud or Self Hosted

Cloud

### Steps to reproduce

According [https://github.com/langgenius/dify/blob/b1918dae5ecc4270266dcbcfad493f265d5f907a/web/app/components/develop/template/template.zh.mdx#L145](https://github.com/langgenius/dify/blob/b1918dae5ecc4270266dcbcfad493f265d5f907a/web/app/components/develop/template/template.zh.mdx#L145)

```
curl -X POST 'https://api.dify.ai/v1/completion-messages' \
--header 'Authorization: Bearer app-xxxxxxxxxxxxxxxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "inputs": {
      "query": "Hello, world!"
    },
    "response_mode": "streaming",
    "user": "abc-123"
}'
```
Then got below
```
{"code": "app_unavailable", "message": "App unavailable, please check your app configurations.", "status": 400}
```

and post man also get the same error
<img width="840" alt="Screen Shot 2024-09-07 at 10 13 51 PM" src="https://github.com/user-attachments/assets/a99b3237-13f1-4836-a925-5cba70c60787">

### ✔️ Expected Behavior

should show response

### ❌ Actual Behavior

400 error

**Comment by vkiller** [comment]
the two endpoint api have some different [https://github.com/langgenius/dify-docs/blob/main/jp/guides/application-publishing/developing-with-apis.md ](https://github.com/langgenius/dify-docs/blob/main/jp/guides/application-publishing/developing-with-apis.md )
and 
[https://github.com/langgenius/dify/blob/main/web/app/components/develop/template/template.en.mdx](https://github.com/langgenius/dify/blob/main/web/app/components/develop/template/template.en.mdx)

```
data = {
    "inputs": {"text": 'Hello, how are you?'},
    "response_mode": "streaming",
    "user": "abc-123"
}
```
parameter `text` or `query`?

but both got wrong

**Comment by vkiller** [comment]
As your guide above,Im sure got error
```
{
  "inputs": {
    "text": "Hello, world!"
  },
  "response_mode": "streaming",
  "user": "abc-123"
}
```
response
```
{
    "code": "app_unavailable",
    "message": "App unavailable, please check your app configurations.",
    "status": 400
}
```
should be a bug,the doc should be clarified about `query` and `text`

**Comment by crazywoola** [comment]
This error `AppUnavailableError` is raised 4 times in our code repo.

<img width="841" alt="image" src="https://github.com/user-attachments/assets/403556ac-b15e-4103-bf31-c1b57cb4769f">

```
if app_model.mode != "completion":
    raise AppUnavailableError()

# And this one
except services.errors.app_model_config.AppModelConfigBrokenError:
            logging.exception("App model config broken.")
            raise AppUnavailableError()
```

So either you have choose the wrong type of application, or you haven't publish the application of the configuration is broken.

**Comment by vkiller** [comment]
> This error `AppUnavailableError` is raised 4 times in our code repo.
> 
> <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/100913391/365415298-403556ac-b15e-4103-bf31-c1b57cb4769f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODI0NDcsIm5iZiI6MTcyNTc4MjE0NywicGF0aCI6Ii8xMDA5MTMzOTEvMzY1NDE1Mjk4LTQwMzU1NmFjLWIxNWUtNDEwMy1iZjMxLWMxYjU3Y2I0NzY5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNzU1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTZlNDkxNThlNGZiZDFhYWM4NTY2OTZhYTNlYzAxMjkwYmY2ZjQ3ODg0MDVjN2ZiYzRlNGJiNmY1ZmI5YWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8LMlGNRQa6-IrylBnpKWBG93q1xJuZJAHzLvGMdZLsY">
> ```
> if app_model.mode != "completion":
>     raise AppUnavailableError()
> 
> # And this one
> except services.errors.app_model_config.AppModelConfigBrokenError:
>             logging.exception("App model config broken.")
>             raise AppUnavailableError()
> ```
> 
> So either you have chosen the wrong type of application, or the configuration is broken.

I use officail `https://cloud.dify.ai/` service,form postman test it,what do you mean `wrong type of application`?also the configuration is working,because the chat api goes well
