### ISSUE TITLE
Number input starting with 0 don't work.

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#8086]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Create input field with number, start the number with 0 and any other number, the input registered will be without the 0.

![CleanShot 2024-09-07 at 22 21 27@2x](https://github.com/user-attachments/assets/8d30297c-00f7-4214-885e-afbeaef264fd)
![CleanShot 2024-09-07 at 22 23 07@2x](https://github.com/user-attachments/assets/187cc25e-b8fe-4f38-af1f-32c9bc1b4e43)

I'm aware that we can use string to make it work, but wanted to report the problem.

### ✔️ Expected Behavior

Certain numbers can start with 0, like Zip-code, this should be able to be included?

### ❌ Actual Behavior

0 is removed from the number.

**Comment by laipz8200** [comment]
The "Number" type variable will be converted to an integer or a float object in Python, so it cannot start with 0.
