### ISSUE TITLE
workflow Code node bug: Got error code: -500. Got error msg: fork/exec /usr/local/bin/python3: too many open files

### ISSUE THREAD

**Issue by double-Dou** [langgenius/dify#8096]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I use code nodes to convert the results of the previous LLM. After a long period of running, the following errors appear: Got Error Code: -500. Got Error MSG: Fork/EXEC/USR/LOCAL/BIN/Python33 : Too Many Open Files

After the errors, the code nodes of all workflow can not run

**Comment by crazywoola** [comment]
See this for help https://stackoverflow.com/questions/18280612/ioerror-errno-24-too-many-open-files

**Comment by double-Dou** [comment]
I did not open the file or access the network in my code, just a simple JSON format data conversion;
If the file descriptor limit is raised, will it just postpone the time when the problem is delayed and cannot fundamentally solve the problem

**Comment by dnyg** [comment]
We have the exact same issue
