### ISSUE TITLE
Failed to jump to the response page after clicking " Setting up an admin account"

### ISSUE THREAD

**Issue by einherjar9527** [langgenius/dify#8097]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. After docker deployment, the default page is "ip/signin".
2. Failed to jump to the response page after clicking " Setting up an admin account"
![1725801250923-20240908_205723](https://github.com/user-attachments/assets/815432d5-3f5c-42af-906b-65d57073c1a6)
![image](https://github.com/user-attachments/assets/bec023fb-a5db-4c2d-a9be-bd020ecc4c36)

### ✔️ Expected Behavior

Successful to jump to the response page after clicking " Setting up an admin account"

### ❌ Actual Behavior

Failed to jump to the response page after clicking " Setting up an admin account"

**Comment by crazywoola** [comment]
Please check the environment settings https://docs.dify.ai/getting-started/install-self-hosted/environments

**Comment by einherjar9527** [comment]
First of all, thank you for your reply and then check ENV in docker-compose.yaml？

**Comment by einherjar9527** [comment]
> Please check the environment settings https://docs.dify.ai/getting-started/install-self-hosted/environments
Are the public variables in this document required to be in env in each docker container?

**Comment by crazywoola** [comment]
This behavior indicates you have an account already.  You could verify it by checking the `tenants` table in postgres.

You could run `docker exec -it docker-api-1 flask reset-password`

Or

- Stop the container.
- Remove things in `docker/volumes/db` `docker/volumes/app` ``docker/volumes/redis`
- Restart the container

**Comment by Saber-YangZi** [comment]
win11       
刚试了下，搜Dify从官网那里能直接进去，然后发现dify这个账号是自己的github账号。之前没设置过管理员账户，可能是已有github账号的缘故相当于已设置管理员账户
