### ISSUE TITLE
Request the author's support to view the contents of the recall

### ISSUE THREAD

**Issue by liulian3564** [langgenius/dify#8099]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Does dify support viewing recalled content in rag scenarios? I added the corpus and asked the model some questions in the corpus, but the model still gave wrong answers. I want to know whether there was a problem in the retrieval or a problem in the generation, which requires me to check the contents recalled in the middle.This is the recall result from my experiment with flashrag, "intermediate_data.jsonl."
![微信图片_20240908221117](https://github.com/user-attachments/assets/5c2efa1e-5b94-4b73-9778-725b82048a24)

### 2. Additional context or comments

I want to look at the results of the different model retrieval, as well as the results of generating the responses, and then explore why the hallucinations/answer errors occur.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by liulian3564** [comment]
@dosu

> 是的，Dify 支持在 RAG 场景下查看认知内容，以诊断检索或生成问题。您可以使用文本搜索测试功能调试不同的检索方式和参数配置下的认知效果。认知结果可以在认知场景部分查看**，也可以在****最近查询**部分查看查询记录历史。另外，启用引文精准功能可以让您在响应内容底部查看特定引文段落信息，包括原始句段文本、句段编号、匹配度等详细信息。您还可以在测试阶段调整搜索方式和参数以优化回调结果，这些更改仅在调试会话期间生效。对于永久性更改，您需要在**知识库设置 > 搜索设置** [[1] ](https://github.com/langgenius/dify-docs/blob/main/en/guides/knowledge-base/retrieval-test-and-citation.md)[[2]](https://github.com/langgenius/dify-docs/blob/main/jp/guides/knowledge-base/retrieval-test-and-citation.md)中更新设置。
> 
> 有关如何执行这些操作的更多步骤，可以参考[搜索测试和引用指南](https://github.com/langgenius/dify-docs/blob/main/en/guides/knowledge-base/retrieval-test-and-citation.md) [[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/knowledge-base/retrieval-test-and-citation.md)。
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_

@dosu Want to know if the retrieval tests/references are consistent with what the model ultimately retrieves? How reliable is it? Also, is the retrieval model used for retrieval tests/references consistent with the system model Settings? Because my experiment is to test the model retrieval ability and generation ability, and then find the wrong answer to the question. So you need reliable search results.

**Comment by VincePotato** [comment]
Knowledge Citation feature: https://docs.dify.ai/guides/knowledge-base/retrieval-test-and-citation#id-2.-citation-and-attribution
