### ISSUE TITLE
reindex error: delete object: store is read-only

### ISSUE THREAD

**Issue by ukhack** [langgenius/dify#8104]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

29 files index failed, reindex but lots of store is read-only error.

2024-09-09 08:55:15 [2024-09-09 00:55:15,980: INFO/MainProcess] Delete object! Unexpected status code: 500, with response body: {'error': [{'message': 'could not delete object from vector repo: delete from index "vector_index_9a365934_d1a6_495b_a0c2_4b6cf0f6d2e7_node": delete object: store is read-only'}]}.

### ✔️ Expected Behavior

reindex success

**Comment by ukhack** [comment]
because of 90% disk size used.close

**Comment by PolarPeak** [comment]
> because of 90% disk size used.close

How to remove this restriction:
{"action":"read_disk_use","level":"warning","msg":"disk usage currently at 89.52%, threshold set to 80.00%","path":"/var/lib/weaviate","time":"2024-09-26T04:52:31Z"}
