### ISSUE TITLE
Knowledge base interface parameters are missing

### ISSUE THREAD

**Issue by 18075717849** [langgenius/dify#8106]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

/console/api/datasets/indexing-estimate This interface is the knowledge base segment preview and consumption interface, but why did you find that token consumption was canceled in the recent update?
![image](https://github.com/user-attachments/assets/7c83f1c4-1525-47d7-82a4-2ca0142d0bf5)

### ✔️ Expected Behavior

I hope get reason!

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/5866c6b0-6867-4ddf-b751-6cfcb6289009)

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8074
