### ISSUE TITLE
API hit-testing not working knowledge

### ISSUE THREAD

**Issue by tienldbnk** [langgenius/dify#8117]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

<img width="982" alt="image" src="https://github.com/user-attachments/assets/0fe4367a-9a66-476f-8666-fff2f6626783">
<img width="1789" alt="image" src="https://github.com/user-attachments/assets/8e32bc20-c765-4ad1-992d-b6f033278ed9">

### ❌ Actual Behavior

Testing API hiting not working

**Comment by crazywoola** [comment]
I guess you need to reindex the documents.

- What kinds of documents do you have?
- Can you paste the settings of the KB?

**Comment by tienldbnk** [comment]
> I guess you need to reindex the documents.
> 
> * What kinds of documents do you have?
> * Can you paste the settings of the KB?
1. Is there a way to reset the index of all apps without affecting them?
2. I would like to know where the specific KB config is because I use the default of dify

**Comment by crazywoola** [comment]
1. You can reset the index by change the embedding model and change it back.
2. See the image below
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/fb9dd729-a36e-4eaa-83cc-e6b2d225ea80">

**Comment by tienldbnk** [comment]
> 1. You can reset the index by change the embedding model and change it back.
> 2. See the image below
> 
> <img alt="image" width="1059" src="https://private-user-images.githubusercontent.com/100913391/365524868-fb9dd729-a36e-4eaa-83cc-e6b2d225ea80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjIwMDcsIm5iZiI6MTcyNTg2MTcwNywicGF0aCI6Ii8xMDA5MTMzOTEvMzY1NTI0ODY4LWZiOWRkNzI5LWEzNmUtNGVhYS04M2NjLWU2YjJkMjI1ZWE4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNjAxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTkyNzkxMjlmMjE3NDNmYTJhZjM1MDU1MWIyZDY1MTc5ZDYwYWU1YTBhZjQwZTYyMzJiYWIzYzg0MGU0NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6il3P5Af0zfg3e7KoXC13VIFur60cKCbZQlECh1U05E">

I tried the same as you, but the result is still unable to query even though I'm running locally but on dify's official website it works normally. I discovered it had a query error when using the model. If I don't use the model but use the traditional one, it still works normally. Please guide me to refresh the index of these documents

**Comment by tienldbnk** [comment]
@crazywoola  

I got a fix, if I add a file to change the index and delete that file it will work, what is the cause?

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/8211 for updates
