### ISSUE TITLE
Return the answer but continue the workflow

### ISSUE THREAD

**Issue by FrancisVarga** [langgenius/dify#8118]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

If Answer node is triggered it wont return the answer it continues the flow.

### 2. Additional context or comments

We wanna provide as fast as possible the answer but wanna run other nodes after.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can append an Answer node before other nodes and give it something to reply, it should work. The other nodes should work as well.
[Demo.yml.zip](https://github.com/user-attachments/files/16925459/Demo.yml.zip)

**Comment by FrancisVarga** [comment]
I mean it should respond only the first answer nothing more but continue executing the flow.
