### ISSUE TITLE
v0.7.3  can not add text-embedding models  ( start up  by  ' docker-compose up -d ' )

### ISSUE THREAD

**Issue by kuschzzp** [langgenius/dify#8125]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

**1. download 0.7.3 in `Releases`
2. start up  by  ' docker-compose up -d '
3. add text-embedding models  by ollama**  

### ✔️ Expected Behavior

add success

### ❌ Actual Behavior

error message:

`
An error occurred during credentials validation: 404 Client Error: Not Found for url: http://xx.xx.xx.xx:11434/api/embed
`

i am sure  the model `quentinz/bge-large-zh-v1.5` existing.

i had successfully added the chat model `qwen2:7b`.

<img width="642" alt="image" src="https://github.com/user-attachments/assets/5d4974a7-daa7-4db8-8aec-18336a00978f">

**Comment by crazywoola** [comment]
You need to upgrade Ollama's client version. See https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings
