### ISSUE TITLE
配置上了支持GPT-4的openai api key，历史应用选择gpt-4 model时报错，新建立应用可以使用gpt-4

### ISSUE THREAD

**Issue by MartinGuo** [langgenius/dify#813]
配置上了支持GPT-4的openai api key.
1.openai 的api key支持 gpt-4模型
2.dify的模型供应商已经配置上了对应的api key 并生效。
3.历史应用原来是用的gpt-3.5,再选择gpt-4 model时报错，新建立应用可以使用gpt-4。

## The current behavior

历史应用重新选择model报错
![image](https://github.com/langgenius/dify/assets/9604808/9be35d2f-415c-443f-a985-82df40e5630e)

模型已经配置上生效
![image](https://github.com/langgenius/dify/assets/9604808/c8eb3fc1-d828-448b-a92e-da91392ac9db)
新建立的应用可以使用GPT-4 
![image](https://github.com/langgenius/dify/assets/9604808/a0beff61-b87c-4e5a-9a04-1f90465ef129)

## The expected behavior
历史应用可以自由切换model

**Comment by iamjoel** [comment]
Fixed： https://github.com/langgenius/dify/pull/815
