### ISSUE TITLE
DIFY Sandbox import requests ERROR

### ISSUE THREAD

**Issue by mhanne0915** [langgenius/dify#8130]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

since 0.7.1 up to latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Steps to reproduce:
- update to latest DIFY/Dify-sandbox version
- python code block that uses requests library

### ✔️ Expected Behavior

Requests code should be successful.

### ❌ Actual Behavior

Error:

Node Query Page run failed: Traceback (most recent call last): File "/tmp/code/73cdfa03_cbde_46de_a70a_ff9b8622b952.py", line 26, in <module> ModuleNotFoundError: No module named 'requests' error: exit status 255

**Comment by crazywoola** [comment]
What's your sandbox version?

**Comment by mhanne0915** [comment]
> What's your sandbox version?

Hi @crazywoola, im using this version 0.2.6.

I havent tried yet the suggestion above to fix the issue. Will let you know once i tried the fix ;)

**Comment by yzning** [comment]
> What's your sandbox version?

meet the same problem in 0.2.7. Here is the error log:
/usr/local/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer). warnings.warn( meout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. json, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 768, in urlopen conn = self._get_conn(timeout=pool_timeout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. error: exit status 255

**Comment by mhanne0915** [comment]
just a quick update, i tried to update the sandbox to 0.2.7 and now im getting this error:

"/usr/local/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer). warnings.warn( open conn = self._get_conn(timeout=pool_timeout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. rams, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 768, in urlopen conn = self._get_conn(timeout=pool_timeout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. error: exit status 255
"

**Comment by mhanne0915** [comment]
> > What's your sandbox version?
> 
> meet the same problem in 0.2.7. Here is the error log: /usr/local/lib/python3.10/site-packages/requests/**init**.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer). warnings.warn( meout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. json, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 768, in urlopen conn = self._get_conn(timeout=pool_timeout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. error: exit status 255

I also updated from 0.2.6 to 0.2.7 and i got the same problem.

**Comment by blankbro** [comment]
> What's your sandbox version?你的沙盒版本是什么？

我是 0.2.7

**Comment by prd-tuong-nguyen** [comment]
same problem

**Comment by Yeuoly** [comment]
Trying dify-sandbox:17bb213f2df4d34849e01ead55e6225be9e634a8 as a temporary solution.

**Comment by omarsoufiane** [comment]
hello @Yeuoly , I'm the founder of bountyhub which is a new platform that aims to incentivize issue solving on GitHub, since you already fixed the issue, you can create an account and claim the bounty above.
let me know if you need any support.

**Comment by ZPerling** [comment]
meet the same problem in 0.2.9. Here is the error log:
```
n error (_ssl.c:3093)
 call last):
  File \"/var/sandbox/sandbox-python/tmp/20fdff25_2f1d_4173_84b6_57e1b78327b9.py\", line 48, in <module>
  File \"<string>\", line 3, in <module>
  File \"/usr/local/lib/python3.10/site-packages/requests/__init__.py\", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File \"/usr/local/lib/python3.10/site-packages/requests/api.py\", line 11, in <module>
    from . import sessions
  File \"/usr/local/lib/python3.10/site-packages/requests/sessions.py\", line 15, in <module>
    from .adapters import HTTPAdapter
  File \"/usr/local/lib/python3.10/site-packages/requests/adapters.py\", line 80, in <module>
    _preloaded_ssl_context = create_urllib3_context()
  File \"/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 292, in create_urllib3_context
    context = SSLContext(PROTOCOL_TLS_CLIENT)
  File \"/usr/local/lib/python3.10/ssl.py\", line 496, in __new__
    self = _SSLContext.__new__(cls, protocol)
ssl.SSLError: [SSL] unknown error (_ssl.c:3093)
error: exit status 255
```

**Comment by NAMEs** [comment]
Run failed: Traceback (most recent call last):
File "/var/sandbox/sandbox-python/tmp/cc1e92ba_db4b_4ea7_bf76_33bf3fbd7117.py", line 48, in
File "", line 17, in
File "", line 7, in main
TypeError: string indices must be integers
error: exit status 255
