### ISSUE TITLE
The response of Website Generator Chatbot effect the whole dify website's style

### ISSUE THREAD

**Issue by fifteen42** [langgenius/dify#8133]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Cloud

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image.png](https://s2.loli.net/2024/09/09/n4qGyD3WVs6RjOb.png)

**Comment by crazywoola** [comment]
Can you attach the code here?

**Comment by iamjoel** [comment]
Can't be reproduced.
![img_v3_02ei_3afc118f-f656-4aef-bdf2-1588c06f2f9g](https://github.com/user-attachments/assets/e1249419-ea56-4115-b78a-9c447355876b)
