### ISSUE TITLE
Change “EXPOSE_NGINX_PORT:-30000”， cause running application failed because of the website address without 30000 but 80

### ISSUE THREAD

**Issue by turndown** [langgenius/dify#8136]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/2f79a718-4f4f-44d1-b235-ebc5159b2bc0)

**Comment by crazywoola** [comment]
Please read https://docs.dify.ai/getting-started/install-self-hosted/environments and set the environment variables accordingly.

**Comment by turndown** [comment]
> Please read https://docs.dify.ai/getting-started/install-self-hosted/environments and set the environment variables accordingly.

Thank you so much.
I have made some changes below and they are currently being used normally. Is there anything that has been missed?
![image](https://github.com/user-attachments/assets/39ff0dd0-dd16-4f2f-9469-ef5e52780b3f)
