### ISSUE TITLE
Version upgrade error：ERROR [root] Database migration failed

### ISSUE THREAD

**Issue by linronghua921122** [langgenius/dify#8137]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

My current version is 0.6.11, and when trying to upgrade to version 0.7.3, an error occurs:
ERROR [root] Database migration failed, error: (psycopg2.OperationalError) connection to server at "db" (172.17.53.3), port 5432 failed: FATAL:  password authentication failed for user "postgres"
But I have confirmed that the database password is correct. Could you please help me check what the reason may be?

**Comment by crazywoola** [comment]
see https://github.com/langgenius/dify/releases/tag/0.6.12-fix1
