### ISSUE TITLE
应用发布可以展示发布历史记录以及回滚能力

### ISSUE THREAD

**Issue by MartinGuo** [langgenius/dify#814]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by takatost** [comment]
Hey, our release history is stored in a database. We've noted down your request and we'll add this feature when we have extra capacity.

**Comment by dragon0311** [comment]
Is there any release come out related with this feature?
