### ISSUE TITLE
"The admin account setup page won't open. How can I register an account?"

### ISSUE THREAD

**Issue by Nand-Lu** [langgenius/dify#8150]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

"The admin account setup page won't open. How can I register an account?"

**Comment by crazywoola** [comment]
Check the logs of the chrome console, you should be able to see some red errors, these indicate you haven't setup the environment variables correctly. Please check the environment settings in `docker/.env` file.

See [the docs](https://docs.dify.ai/getting-started/install-self-hosted/environments#common-variables) for more details, this is a duplicated questions as well. 

```
docker exec -it docker-api-1 flask reset-password

docker exec -it docker-api-1 flask reset-encrypt-key-pair
```
