### ISSUE TITLE
Unable to execute python code block `base64` module not found

### ISSUE THREAD

**Issue by siddhantprateek** [langgenius/dify#8151]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Insert a code block
2. Attempt to run it. 

### ✔️ Expected Behavior

The code should get executed.

### ❌ Actual Behavior

 
![Screenshot 2024-09-09 at 3 05 18 PM](https://github.com/user-attachments/assets/f1fa7f42-e809-4890-9049-c221e7a8d1f3)
![Screenshot 2024-09-09 at 3 05 02 PM](https://github.com/user-attachments/assets/9bcd9ff9-7e33-42ef-b08a-4a57ff3c869b)

I'm assuming that base64 is installed by default and there are no external dependencies in the code I am running. However, I'm still encountering the following error: `ModuleNotFoundError: No module named 'base64'`

**Comment by crazywoola** [comment]
Please upgrade sandbox to v0.2.6
