### ISSUE TITLE
Please check the environment settings https://docs.dify.ai/getting-started/install-self-hosted/environments

### ISSUE THREAD

**Issue by einherjar9527** [langgenius/dify#8152]
Please check the environment settings https://docs.dify.ai/getting-started/install-self-hosted/environments

_Originally posted by @crazywoola in https://github.com/langgenius/dify/issues/8097#issuecomment-2336688204_
            
env in the app-web has been checked and is fine
![image](https://user-images.githubusercontent.com/111212248/365600661-a84867f9-bcfe-4e00-aa87-a8bcf3887cc2.png)

**Comment by einherjar9527** [comment]
![image](https://github.com/user-attachments/assets/f15c9dde-4b52-48a4-bd5b-2353e86cf57f)

**Comment by crazywoola** [comment]
Reopen https://github.com/langgenius/dify/issues/8097

**Comment by einherjar9527** [comment]
![image](https://github.com/user-attachments/assets/a47e4d73-ec55-4fb5-b2fc-7f75bb06e3db)

**Comment by crazywoola** [comment]
You docker-api failed to start. Check the logs.

**Comment by einherjar9527** [comment]
> You docker-api failed to start. Check the logs.

it's done，I upgraded from 0.7.2 to 0.7.3
