### ISSUE TITLE
Integration of Redis Tool for Efficient Token Caching

### ISSUE THREAD

**Issue by G81192** [langgenius/dify#8153]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Yes, I frequently need to request tokens for third-party API calls. This process can be time-consuming and inefficient.
I would like to see a Redis tool integrated into Dify. This tool would allow users to cache tokens, reducing the need for repeated token requests.
By caching tokens, I can save time and resources, making my workflow more efficient. This feature would eliminate the need to request a new token for each API call, thereby speeding up the development process.

### 2. Additional context or comments

I have developed a function in my local code that implements this feature. I am willing to share this function with the Dify community.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by laipz8200** [comment]
Have you considered using conversation variables to store the token and its expiration time? I’d love to know if there are any challenges in implementing this in your specific scenario.

**Comment by G81192** [comment]
@laipz8200  I have a requirement that involves the following scenarios:
1. Some nodes in the process require calling internal system APIs, but the internal system uses an authentication token. This token needs to be retrieved from an endpoint and has an expiration time. As a result, I need to obtain the token each time the process runs, which leads to performance degradation.
2. Certain third-party information, such as tenant resource details, changes infrequently. Since querying these details is slow, caching is desired for handling this information.

Additionally, can the conversation variables you mentioned address this issue? I haven't found a better solution during my debugging so far.

**Comment by laipz8200** [comment]
By using the conversation variable, you only need to gather the necessary information once at the beginning of each conversation. This information will be stored within the conversation until it is deleted.

**Comment by G81192** [comment]
> By using the conversation variable, you only need to gather the necessary information once at the beginning of each conversation. This information will be stored within the conversation until it is deleted.

Conversation variables seem to be derived from user-provided information, but the information that needs to be cached is not provided by the user.
