### ISSUE TITLE
How can I bring historical chat records to Dify through API?

### ISSUE THREAD

**Issue by hanhaiszw** [langgenius/dify#8159]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In our application scenario, the chat data is stored in the business database and needs to be filled to dify through the API. Currently, the /chat-messages interface has no parameters for filling the historical chat data.

### 2. Additional context or comments

Carrying historical chat data to diffify is very important for LLM and business integration.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://docs.dify.ai/guides/knowledge-base for details.
You could import historical messages via knowledge api here https://docs.dify.ai/guides/knowledge-base/maintain-dataset-via-api.
Then you would be able to refer the knowledge in our application.

**Comment by hanhaiszw** [comment]
Thanks for your answer, but this is not what I need. 
I need to dynamically fill in the historical chat data through the API, rather than relying on the knowledge base. 
The data in the knowledge base is difficult to maintain dynamically, and the Dify application cannot dynamically switch the knowledge base.

**Comment by New-King** [comment]
你说出了我的心声，我希望可以像openai api那样将聊天记录存在message字段里

**Comment by New-King** [comment]
You spoke my heart. I hope I can send my chat history in the message field like openai api.
