### ISSUE TITLE
When a React agent invokes a tool, the tool response is exceptionally repeated twice.

### ISSUE THREAD

**Issue by lixiangtiandashen** [langgenius/dify#8168]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I use a React-formatted agent to call a tool, it unusually repeats the returned result twice.
![5534619383](https://github.com/user-attachments/assets/afa76b80-1d70-4c95-9eea-4e79a693eb88)

**Comment by crazywoola** [comment]
I suggest you switching to a smarter agent, or if you are using ReAct, change the max_iteration to 1 to ensure  there is only one tool call .

**Comment by yuhp-zts** [comment]
> I suggest you switching to a smarter agent, or if you are using ReAct, change the max_iteration to 1 to ensure there is only one tool call .

My agent only calls one tool, the model uses Qwen-32B, the agent iteration count is 1, and I do not receive duplicate replies when running the tool separately, but duplicates occur when called through the agent.

**Comment by yuhp-zts** [comment]
> I suggest you switching to a smarter agent, or if you are using ReAct, change the max_iteration to 1 to ensure there is only one tool call .

I found that this issue occurs when the agent calls a tool converted from a workflow; tools that are not part of a workflow do not exhibit duplication.

**Comment by yuhp-zts** [comment]
Perhaps the reason is here.
![image](https://github.com/user-attachments/assets/18eb7f2c-8a2b-4e7b-a815-640683d87d28)

**Comment by crazywoola** [comment]
In this case you could try to return the text or json only in the workflow end node to see if you can get two same records. @yuhp-zts

**Comment by EcoleKeine** [comment]
@crazywoola How to "return the text or json only" ? 
I dont see any selector in workflow end node

I think the problem is still exists in v0.15.3
