### ISSUE TITLE
Ollama vision is not working

### ISSUE THREAD

**Issue by ruzzzz6312** [langgenius/dify#8170]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Add Ollama "Llava" model (visual)

### ✔️ Expected Behavior

To be able to chat about the image

### ❌ Actual Behavior

2 options, either:
<img width="567" alt="Screenshot 2024-09-09 at 3 22 45 PM" src="https://github.com/user-attachments/assets/0fdba97c-68b4-4bdf-b588-a9ecea4dbb27">
[ollama] Error: API request failed with status code 400: {"error":"illegal base64 data at input byte 5"}

Or:
<img width="1884" alt="Screenshot_2024-09-06_at_6 09 13_PM" src="https://github.com/user-attachments/assets/55dc5830-6a71-4cc8-bf12-537979630dc4">

Query or prefix prompt is too long, you can reduce the prefix prompt, or shrink the max token, or switch to a lim with a larger token limit size.

**Comment by ruzzzz6312** [comment]
Ollama IS ACCESSIBLE, text / chat works just fine

**Comment by ruzzzz6312** [comment]
model is 'LLAVA:13B' and 'LLAVA:34B'

**Comment by crazywoola** [comment]
This is because tokens will be calculated as tokens as well, so a image should be base64 strings and filled into the prompt which might lead to this error `query or prefix is too long`. You can reduce the image's size to make it pass.

**Comment by ruzzzz6312** [comment]
so I have 2 issues, both never appear when working on the same workflow with GPT-4o, so the problem is related to ollama's module (I guess)

> This is because tokens will be calculated as tokens as well, so a image should be base64 strings and filled into the prompt which might lead to this error `query or prefix is too long`. You can reduce the image's size to make it pass.

**Comment by crazywoola** [comment]
The vision function in ollama is not quite same as the gpt-4o, gpt-4o supports adding files by a parameter while the ollama does not, so it will be translated as base64 string.

**Comment by ruzzzz6312** [comment]
sorry guys, why completed? Error is still there, any workaround to use vision with ollama?

**Comment by kwiksher** [comment]
ollama with image_url fails.  Paste image link fails "https://cloud.dify.ai/logo/logo-site.png"
