### ISSUE TITLE
How to resolve the issue where the agent tool invocation returns duplicate response content. 

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#8172]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I create a workspace using the agent, I encounter the following issue and would like to consult on the possible cause. In the tool invocation response, there are two pieces of information:

{"GetCrmServerList": "{"response_out":”……"}

and

tool response: {"response_out":”……"}.

GetCrmServerList is a tool I defined, and response_out is the result returned by the tool. However, an additional tool response message appears afterward, and its content is identical to what is in the {"GetCrmServerList": "{"response_out":”……"}.

When the content returned in response_out is relatively long, the data returned through the agent tool invocation is doubled.

How can I ensure that only {"GetCrmServerList": "{"response_out":”……"} is retained?

![1725928415748](https://github.com/user-attachments/assets/9f0a6cd1-3797-4c5a-a4c3-84a12dbf439b)

![image](https://github.com/user-attachments/assets/e9c8ee95-3e3e-4a6f-8e78-eb24446cc546)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
It depends on the LLM you chose, seems duplicated as https://github.com/langgenius/dify/issues/8168

I suggest you switching to a smarter agent, or if you are using ReAct, change the max_iteration to 1 to ensure  there is only one tool call .

**Comment by yuhp-zts** [comment]
> It depends on the LLM you chose, seems duplicated as #8168
> 
> I suggest you switching to a smarter agent, or if you are using ReAct, change the max_iteration to 1 to ensure there is only one tool call .

The model I am using is qwen-32B, and the number of agent iterations chosen is 1.
