### ISSUE TITLE
List out of range error using big prompt with sonnet 3.5

### ISSUE THREAD

**Issue by lucaseatp** [langgenius/dify#8173]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

doesn't work with bigger prompts sometimes (60k characters)

### ✔️ Expected Behavior

llm response

### ❌ Actual Behavior

[anthropic] Error: list index out of range

**Comment by crazywoola** [comment]
Can you paste the configurations here?

<img width="691" alt="image" src="https://github.com/user-attachments/assets/83ffbe37-77ac-4665-82c5-5ff41b36eb34">

**Comment by lucaseatp** [comment]
sure, here it is

![image](https://github.com/user-attachments/assets/5a3c49de-e908-46bd-8a2c-ebf2e05105f1)

**Comment by crazywoola** [comment]
I tried but I can not reproduce this.

**Comment by goradawid** [comment]
I found the same issue - Claude 3.5 sonnet, input tokens 4481. 
This is my config: 

![image](https://github.com/user-attachments/assets/6f11d0a3-5405-4c41-a94b-d77689592c5f)

**Comment by IbukiMoriya** [comment]
Same occurrence.
- claude-3-5-sonnet-20241022
- input tokens 20k
- config
    ![image](https://github.com/user-attachments/assets/10b72e5d-5750-4784-941a-59ab3eaffec1)
