### ISSUE TITLE
When using the Function Calling, ToolCall.id will be randomly generated instead of the set value

### ISSUE THREAD

**Issue by HeyDorvin** [langgenius/dify#8174]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

- set model_providers config:
```yaml
features:
  - agent-thought
  - tool-call
  - multi-tool-call
  - stream-tool-call
 ```

1. first round
```
[{'role': 'user', 'content': 'What day is today'}]
```
2. second round
```
[{'role': 'user', 'content': 'What day is today'}, {'role': 'assistant', 'tool_calls': [{'id': 'call_66aa5915-79bf-4853-a843-33bc60ead235_0', 'type': 'function', 'function': {'name': 'weekday', 'arguments': '{"year": 2023, "month": 4, "day": 14}'}}]}, {'role': 'tool', 'content': 'April 14, 2023 is Friday.', 'name': 'weekday', 'tool_call_id': 'call_66aa5915-79bf-4853-a843-33bc60ead235_0'}]
```
3. third round
```
[{'role': 'user', 'content': 'What day is today'}, {'role': 'assistant', 'tool_calls': [{'id': '2235c7b1-1b77-42f1-a0d8-6b4be977be3d', 'type': 'function', 'function': {'name': 'weekday', 'arguments': '{"year": 2023, "month": 4, "day": 14}'}}]}, {'role': 'tool', 'content': 'April 14, 2023 is Friday.', 'name': 'weekday', 'tool_call_id': '2235c7b1-1b77-42f1-a0d8-6b4be977be3d'}, {'role': 'assistant', 'content': 'According to the information in API-REPONSE, today is Friday.'}]
```
ToolCall.id changed during the third session.

### ✔️ Expected Behavior

Keep the tool_call_id in the third round consistent with that in the second round
```
[{'role': 'user', 'content': 'What day is today'}, {'role': 'assistant', 'tool_calls': [{'id': 'call_66aa5915-79bf-4853-a843-33bc60ead235_0', 'type': 'function', 'function': {'name': 'weekday', 'arguments': '{"year": 2023, "month": 4, "day": 14}'}}]}, {'role': 'tool', 'content': 'April 14, 2023 is Friday.', 'name': 'weekday', 'tool_call_id': 'call_66aa5915-79bf-4853-a843-33bc60ead235_0'}, {'role': 'assistant', 'content': 'According to the information in API-REPONSE, today is Friday.'}]
```
I noticed what the document said "Tool ID, effective only in OpenAI tool calls. It's the unique ID for tool invocation and the same tool can be called multiple times." Does this mean it is only effective for model provider OpenAI? If yes, how to keep the tool_call_id ?

### ❌ Actual Behavior

tool_call_id changed in the third round.

**Comment by HeyDorvin** [comment]
`organize_agent_history` function generate a uuid for tool call, instead of keeping the tool call id. @dosu

**Comment by HeyDorvin** [comment]
`organize_agent_history` function generate a uuid for tool call, instead of keeping the tool call id. @dosu

**Comment by HeyDorvin** [comment]
This is why ToolCall.id changed. How to keep the old ToolCall.id, instead using uuid. @dosu

**Comment by HeyDorvin** [comment]
This doesn't work. The doc saied "Tool ID, effective only in OpenAI tool calls. It's the unique ID for tool invocation and the same tool can be called multiple times.", why my ToolCall.id changed?

**Comment by HeyDorvin** [comment]
This doesn't work. The doc saied "Tool ID, effective only in OpenAI tool calls. It's the unique ID for tool invocation and the same tool can be called multiple times.", why my ToolCall.id changed? @dosu

**Comment by HeyDorvin** [comment]
I have set the TooCall.id, but it changed.
```python
function = AssistantPromptMessage.ToolCall.ToolCallFunction(
       name=response_function_call["name"],
       arguments=response_function_call["arguments"],
)

tool_call = AssistantPromptMessage.ToolCall(
       id=response_function_call["id"], type="function", function=function
)
```

**Comment by HeyDorvin** [comment]
I have set the TooCall.id, but it changed. @dosu
```python
function = AssistantPromptMessage.ToolCall.ToolCallFunction(
       name=response_function_call["name"],
       arguments=response_function_call["arguments"],
)

tool_call = AssistantPromptMessage.ToolCall(
       id=response_function_call["id"], type="function", function=function
)
```

**Comment by crazywoola** [comment]
I think it should be changed by design.

**Comment by HeyDorvin** [comment]
> I think it should be changed by design.

But the API uses this search parameter. If changed, it can't work.

**Comment by crazywoola** [comment]
According to our dev:

> It should be the same toolcall.id if this is completion (one round)
> It will have different if this is a multi-round conversation

I think the api will use the content but id to make the call.

Different providers does not have this id field. I guess it's not that crucial.

**Comment by HeyDorvin** [comment]
> According to our dev:
> 
> > It should be the same toolcall.id if this is completion (one round)
> > It will have different if this is a multi-round conversation
> 
> I think the api will use the content but id to make the call.
> 
> Different providers does not have this id field. I guess it's not that crucial.

Thank you for your reply.

**Comment by kiendn1** [comment]
> > According to our dev:
> > > It should be the same toolcall.id if this is completion (one round)
> > > It will have different if this is a multi-round conversation
> > 
> > 
> > I think the api will use the content but id to make the call.
> > Different providers does not have this id field. I guess it's not that crucial.
> 
> Thank you for your reply.

Dify currently uses function calling instead of tool calling. The key difference between functions and tools is that tools support parallel function calling, which allows the model to output multiple tool calls in a list, enabling the user to execute them in parallel. On the other hand, Dify executes only one function at a time. Therefore, tool call IDs are not necessary in Dify, as they are primarily useful for distinguishing outputs from multiple tool calls

![Image](https://github.com/user-attachments/assets/1eaf37e8-1dd0-4548-852d-1d6a0cf0ff0f)
