### ISSUE TITLE
The embedding model isn't saved while creating a Knowledge

### ISSUE THREAD

**Issue by Howe829** [langgenius/dify#8175]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Create a Knowledge using the ZhipuAi embedding-3
<img width="744" alt="image" src="https://github.com/user-attachments/assets/ff208235-cf44-4c24-b399-825badba3ee8">

2.Click "Save and process"

3.Check the knowledge, it is unavailable
<img width="830" alt="image" src="https://github.com/user-attachments/assets/ee295d6b-de75-46b1-92fa-69d01dda1f07">
4. Go to the Knowledge settings, then you'll see the embedding model hasn't been configured.
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/764b3727-d9ac-4fc1-9487-ac6da8e92050">
5.The Retrieval Testing failed even though I configured the right embedding model
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/e2ebf818-a3c6-46a2-abec-e28ab2564f6e">

logs:
```
2024-09-10 02:13:46,990.990 ERROR [Thread-158 (process_request_thread)] [app.py:838] - Exception on /console/api/datasets/c981bc7f-4a3a-42b5-b942-43d66b05162c/hit-testing [POST]
Traceback (most recent call last):
  File "/Users/howard/workspace/dify/api/controllers/console/datasets/hit_testing.py", line 55, in post
    response = HitTestingService.retrieve(
  File "/Users/howard/workspace/dify/api/services/hit_testing_service.py", line 38, in retrieve
    all_documents = RetrievalService.retrieve(
  File "/Users/howard/workspace/dify/api/core/rag/datasource/retrieval_service.py", line 90, in retrieve
    raise Exception(exception_message)
Exception: Error during query: [{'locations': [{'column': 45959, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_c981bc7f_4a3a_42b5_b942_43d66b05162c_Node".', 'path': None}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/howard/workspace/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/howard/workspace/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/howard/workspace/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/howard/workspace/dify/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/Users/howard/workspace/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/howard/workspace/dify/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/Users/howard/workspace/dify/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/howard/workspace/dify/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/Users/howard/workspace/dify/api/controllers/console/datasets/hit_testing.py", line 83, in post
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 45959, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_c981bc7f_4a3a_42b5_b942_43d66b05162c_Node".', 'path': None}]
```
### ✔️ Expected Behavior

Work as normal

### ❌ Actual Behavior

Work failed

**Comment by Howe829** [comment]
I can fix it, PTAL [fix:Saving embedding model info while createing a knowledge dataset #8181 ](https://github.com/langgenius/dify/pull/8181)

**Comment by Howe829** [comment]
The problem No.5 still exists.PTAL @JohnJyong

**Comment by soulzzz** [comment]
> The problem No.5 still exists.PTAL @JohnJyong

the problem occurs when changed embedding models, and restore to the old embedding model can't fix it tho

**Comment by Howe829** [comment]
> > The problem No.5 still exists.PTAL @JohnJyong
> 
> the problem occurs when changed embedding models, and restore to the old embedding model can't fix it tho
> 
> ```
> 2024-09-10 07:29:54,540.540 INFO [Thread-848 (process_request_thread)] [_internal.py:97] - 10.8.8.141 - - [10/Sep/2024 07:29:54] "OPTIONS /console/api/datasets/215b4a42-64db-4081-a055-bcf48361de51/hit-testing HTTP/1.1" 200 -
> 2024-09-10 07:29:54,574.574 ERROR [Thread-849 (process_request_thread)] [hit_testing.py:82] - Hit testing failed.
> Traceback (most recent call last):
>   File "/home/sky/Second/dify/api/controllers/console/datasets/hit_testing.py", line 55, in post
>     response = HitTestingService.retrieve(
>   File "/home/sky/Second/dify/api/services/hit_testing_service.py", line 38, in retrieve
>     all_documents = RetrievalService.retrieve(
>   File "/home/sky/Second/dify/api/core/rag/datasource/retrieval_service.py", line 90, in retrieve
>     raise Exception(exception_message)
> Exception: Error during query: [{'locations': [{'column': 22859, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_215b4a42_64db_4081_a055_bcf48361de51_Node".', 'path': None}]
> 2024-09-10 07:29:54,575.575 ERROR [Thread-849 (process_request_thread)] [app.py:838] - Exception on /console/api/datasets/215b4a42-64db-4081-a055-bcf48361de51/hit-testing [POST]
> Traceback (most recent call last):
>   File "/home/sky/Second/dify/api/controllers/console/datasets/hit_testing.py", line 55, in post
>     response = HitTestingService.retrieve(
>   File "/home/sky/Second/dify/api/services/hit_testing_service.py", line 38, in retrieve
>     all_documents = RetrievalService.retrieve(
>   File "/home/sky/Second/dify/api/core/rag/datasource/retrieval_service.py", line 90, in retrieve
>     raise Exception(exception_message)
> Exception: Error during query: [{'locations': [{'column': 22859, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_215b4a42_64db_4081_a055_bcf48361de51_Node".', 'path': None}]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
>   File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 110, in view
>     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
>   File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/home/sky/Second/dify/api/controllers/console/setup.py", line 65, in decorated
>     return view(*args, **kwargs)
>   File "/home/sky/Second/dify/api/libs/login.py", line 93, in decorated_view
>     return current_app.ensure_sync(func)(*args, **kwargs)
>   File "/home/sky/Second/dify/api/controllers/console/wraps.py", line 22, in decorated
>     return view(*args, **kwargs)
>   File "/home/sky/Second/dify/api/controllers/console/datasets/hit_testing.py", line 83, in post
>     raise InternalServerError(str(e))
> werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 22859, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_215b4a42_64db_4081_a055_bcf48361de51_Node".', 'path': None}]
> ```

I create the Knowledge and retrieval it with the same embedding model, but the problem still exists.
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/df23105d-4178-4f84-912f-d34fe7116950">
<img width="1401" alt="image" src="https://github.com/user-attachments/assets/51871d92-225d-490b-b1a2-fa3700ce1ee3">
I am so confused, but thanks for reply anyway.

**Comment by Howe829** [comment]
I maybe there is some dirty data when using the same file to create a new Knowledge dataset. It works well with another file.
