### ISSUE TITLE
Support Switch Node to simplify the workflow with multiple branches

### ISSUE THREAD

**Issue by tobegit3hub** [langgenius/dify#8178]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We have some workflows which contains multiple branches and using the If-Else node makes the workflow complex to read.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See this [If/elsif/else](https://docs.dify.ai/guides/workflow/node/ifelse)

**Comment by tobegit3hub** [comment]
Thanks @crazywoola and it matches our requirements.
