### ISSUE TITLE
 Create Knowledge-----Text Preprocessing and Cleaning----Custom Rule TextSplitter._merge_splits() missing 1 required positional argument: 'lengths'

### ISSUE THREAD

**Issue by sherryxie1** [langgenius/dify#8179]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.8.0-beta1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/a627eb69-0343-44c9-bdd2-91dffd1a8a81)

### ✔️ Expected Behavior

创建知识库

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/a627eb69-0343-44c9-bdd2-91dffd1a8a81)

**Comment by crazywoola** [comment]
Already fixed in https://github.com/langgenius/dify/issues/7987
