### ISSUE TITLE
Ollama's Embedding endpoint is wrong

### ISSUE THREAD

**Issue by killkli** [langgenius/dify#8184]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Ollama's embedding's endpoint should be 
/api/embeddings

However, Dify's implementation uses
/api/embed
This cause embedding model unusable with ollama
Please fix~

Code in current git:
https://github.com/langgenius/dify/blob/85ff82a69461ce45388996907af7705bfa1b5e51/api/core/model_runtime/model_providers/ollama/text_embedding/text_embedding.py#L62

### ✔️ Expected Behavior

Use correct endpoint

### ❌ Actual Behavior

Use wrong endpoint, always result in 404

**Comment by killkli** [comment]
No, https://github.com/langgenius/dify/pull/8131 Doesn't fix the code~ Bot your text is right but thr reference pull req is wrong XD

**Comment by crazywoola** [comment]
> Ollama's embedding's endpoint should be /api/embeddings

This endpoint is deprecated. See https://github.com/langgenius/dify/issues/7322

You need to upgrade your ollama client version.

https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings
https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embedding

See their docs:

Note: this endpoint has been superseded by /api/embed

POST /api/embeddings
