### ISSUE TITLE
index += 0 useless

### ISSUE THREAD

**Issue by realjustinwu** [langgenius/dify#8186]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

last version

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

index += 0 useless in https://github.com/langgenius/dify/blob/2d690801d19257a0c3dd01a56c4ee105dabe2826/api/core/model_runtime/model_providers/azure_openai/llm/llm.py#L419

**Comment by crazywoola** [comment]
：（ I guess you can open a pr for this.
