### ISSUE TITLE
post tool provider not show array body

### ISSUE THREAD

**Issue by kenneth-bro** [langgenius/dify#8189]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/aa002f1e-d77e-4ebf-a371-7ba0f7ff28c3)
![image](https://github.com/user-attachments/assets/45fd982e-c7e4-4877-9da2-894fc978d3c4)

When TOOL Provider is not a body passing parameter when request body is an array, causing the parameter when using tools to use tools

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/5720
