### ISSUE TITLE
Support for Uploading and Referencing Other File Types in Dify Application Workflows

### ISSUE THREAD

**Issue by xinjiprincess** [langgenius/dify#8196]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In the current version of Dify, it appears that users can upload and reference only specific types of files within workflows. It would be beneficial for broader use cases if the application could support uploading a wider variety of file types (e.g., PDFs, spreadsheets, images, etc.) and allow these files to be referenced directly within the workflow.

Request:

File Upload Support: Expand the range of file types that users can upload into the Dify platform.
Workflow Integration: Provide functionality to reference these uploaded files as variables within workflows, enabling automation and more dynamic content usage in workflows.
Benefit:

This feature would increase the flexibility of Dify and enhance its utility for users who need to process or reference different types of content within their workflows. It will also streamline workflows by eliminating the need to externally manage files and manually reference them, making Dify a more comprehensive solution for various business needs.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5346
