### ISSUE TITLE
Ollama reports an error when adding Text Embedding.

### ISSUE THREAD

**Issue by AAEE86** [langgenius/dify#8209]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

An error occurred during credentials validation: Session.request() got an unexpected keyword argument 'options'

**Comment by AAEE86** [comment]
```
During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/app/api/controllers/console/workspace/models.py", line 151, in post

    model_provider_service.save_model_credentials(

  File "/app/api/services/model_provider_service.py", line 249, in save_model_credentials

    provider_configuration.add_or_update_custom_model_credentials(

  File "/app/api/core/entities/provider_configuration.py", line 375, in add_or_update_custom_model_credentials

    provider_model_record, credentials = self.custom_model_credentials_validate(model_type, model, credentials)

  File "/app/api/core/entities/provider_configuration.py", line 352, in custom_model_credentials_validate

    credentials = model_provider_factory.model_credentials_validate(

  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 123, in model_credentials_validate

    model_instance.validate_credentials(model, filtered_credentials)

  File "/app/api/core/model_runtime/model_providers/ollama/text_embedding/text_embedding.py", line 146, in validate_credentials

    raise CredentialsValidateFailedError(f'An error occurred during credentials validation: {str(ex)}')

core.model_runtime.errors.validate.CredentialsValidateFailedError: An error occurred during credentials validation: Session.request() got an unexpected keyword argument 'options'
```

**Comment by kksmi** [comment]
你好请问你解决这个问题了吗，我感觉是ollama升级换了options

**Comment by AAEE86** [comment]
@crazywoola The rebuilt version 0.8.0 still has this problem. It may be related to this submission of #7624.

**Comment by kksmi** [comment]
Hi. Did you solve the problem?

**Comment by racerxdl** [comment]
Same here. :'(

**Comment by Howe829** [comment]
I think the cause is this line:
https://github.com/langgenius/dify/blob/2a3d8c25bc4104f1da65bf045bb732fd9551725a/api/core/model_runtime/model_providers/ollama/text_embedding/text_embedding.py#L87

**Comment by Howe829** [comment]
> I think the cause is this line:
> 
> https://github.com/langgenius/dify/blob/2a3d8c25bc4104f1da65bf045bb732fd9551725a/api/core/model_runtime/model_providers/ollama/text_embedding/text_embedding.py#L87

I summit a pr #8236

**Comment by algorithmx** [comment]
Can you please update the docker images?

**Comment by racerxdl** [comment]
@algorithmx working now. Thanks :D

**Comment by tigflanker** [comment]
Same issue. 0.8.0
Can not use qwen2-embedding model in Ollama

[ollama] Error: Session.request() got an unexpected keyword argument 'options'

**Comment by GlitCher50** [comment]
Tried updating the docker images still the same. Is the docker images being updated with this fix?

- Removed the images from docker desktop
- Did "docker compose pull"
- Then tried with force-recreate "docker compose up --force-recreate --build -d"

Still not working.

**Comment by AAEE86** [comment]
@GlitCher50 docker image has not been updated.

**Comment by racerxdl** [comment]
I changed to `main` tag to avoid issues with caching (because there is cache on dockerhub as well for images).

**Comment by kksmi** [comment]
> Tried updating the docker images still the same. Is the docker images being updated with this fix?
> 
> * Removed the images from docker desktop
> * Did "docker compose pull"
> * Then tried with force-recreate "docker compose up --force-recreate --build -d"
> 
> Still not working.

You should start it after pull, then modify text_embedding.py in the folder corresponding to the docker-worker-1 and docker-api-1 respectively, remove options, and after that don't start it via command, start it in docker desktop.

**Comment by ther3zz** [comment]
> I changed to `main` tag to avoid issues with caching (because there is cache on dockerhub as well for images).



> I changed to `main` tag to avoid issues with caching (because there is cache on dockerhub as well for images).



> I changed to `main` tag to avoid issues with caching (because there is cache on dockerhub as well for images).

Thanks, this corrected it for me!

The docs on the website has the versions hardcoded and I failed to notice that before you mentioned :main

**Comment by julianShi** [comment]
There is a typo on https://github.com/langgenius/dify/blame/main/api/core/model_runtime/model_providers/ollama/text_embedding/text_embedding.py#L68 

The url should be `api/embeddings`.
