### ISSUE TITLE
css style is ugly. [0.8.0]

### ISSUE THREAD

**Issue by Alixxxxxxx** [langgenius/dify#8216]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce
demo: https://dify.airapp.run/chat/FNrS0b0RUO3YEDqV

![image](https://github.com/user-attachments/assets/1bfe391e-6f15-47b1-b9b8-a3fffbc655d3)

### ✔️ Expected Behavior

having a margin ?

### ❌ Actual Behavior

margin 0

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8201
