### ISSUE TITLE
[Chatflow] All classes with "Answer" block are triggered in "Knowledge Classifier"

### ISSUE THREAD

**Issue by AnotiaWang** [langgenius/dify#8222]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a Chatflow chatbot
2. Create the following chatflow:
<img width="809" alt="截屏2024-09-10 19 40 40" src="https://github.com/user-attachments/assets/675db930-c746-40d0-85a0-8cb3614df5e4">
3. Preview the chatbot, and ask anything, e.g. "2".

### ✔️ Expected Behavior

The bot should answer "Response from 2".

### ❌ Actual Behavior

The bot answered "Response from 1Response from 2Response from 3".

<img width="1216" alt="截屏2024-09-10 19 43 41" src="https://github.com/user-attachments/assets/4c0674da-9e28-4517-b7f3-a4a83907a143">

I'm not sure whether all classes are triggered in the classifier, or just the ones that have Answers, since other classes are not shown in the log.

**Comment by AnotiaWang** [comment]
Maybe #8221 fixes this issue

**Comment by crazywoola** [comment]
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/6f2661eb-13c8-460a-8b79-91c9544bcdf7">
Seems fixed in latest branch.
