### ISSUE TITLE
base64 error

### ISSUE THREAD

**Issue by Sbazar-GmbH** [langgenius/dify#8224]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/ea2165da-3321-46ca-88d2-6e719fe4e0a3)

We are experiencing a ModuleNotFoundError: No module named 'base64' in our self-hosted DIFY AI setup using Docker. This error occurs despite base64 being part of Python's standard library. The issue arises when running a Python script, and it persists across different environments. We've verified the Python version and rebuilt the Docker image, but the problem remains unresolved. Assistance in identifying potential misconfigurations or overlooked steps would be appreciated.

### ✔️ Expected Behavior

this code block should work properly

### ❌ Actual Behavior

every time i do something it shows me this error only in the code block, if i try out the javascript then also it doesnt work:

![image](https://github.com/user-attachments/assets/dee91ac6-95c7-4c2e-a33a-a139adbd364b)

**Comment by cubxxw** [comment]
Thank you. I've taken care of it

**Comment by truc0** [comment]
I got the same issue when upgrading `dify` from `0.6.x` to the latest `0.8.2`, the docker image of `sandbox` is version `0.2.7` which should satisfy the requirements.

The error occurs when running a code block in an app created before upgrade.

I found the following logs from `docker compose logs -f` while calling the workflow:

```
sandbox-1     | 2024/09/15 15:52:43 env.go:30: [WARN]python lib path /usr/lib/python3.10 is not available
sandbox-1     | 2024/09/15 15:52:43 env.go:30: [WARN]python lib path /usr/lib/python3 is not available
sandbox-1     | 2024/09/15 15:52:43 env.go:30: [WARN]python lib path /run/systemd/resolve/stub-resolv.conf is not available
sandbox-1     | 2024/09/15 15:52:43 env.go:30: [WARN]python lib path /run/resolvconf/resolv.conf is not available
sandbox-1     | 2024/09/15 15:52:53 server.go:75: [INFO]python dependencies updated
```

**Comment by zhenghaolun** [comment]
My sandbox image version is latest (0.2.10), however, it also cannot work.
I also tried version 0.2.6 and it still doesn't work.
