### ISSUE TITLE
Add Parallel and Loop Module Functionality to Iteration Block + Support Donation Feature

### ISSUE THREAD

**Issue by zhangeden** [langgenius/dify#8226]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I upgraded to V0.8.0 immediately, and I really appreciate the new parallel processing feature. It's a fantastic improvement—thank you for your hard work! However, I noticed that while the parallel processing works well in general, it doesn’t currently apply to workflows within the iteration module.

My suggestion is to add an option in the iteration module that allows users to toggle between two modes: parallel processing and the default linear processing (as it was before). In parallel mode, the iteration module could distribute the array of information received from the previous node and spawn multiple tasks that can be processed simultaneously. This could further speed up the execution of complex workflows, making them more efficient.

Additionally, I would suggest adding a "Loop" module where users can set conditions for exiting the loop. As long as the condition isn’t met, the workflow inside the loop would keep running. Once the condition is met, it would proceed to the next node. This would be a basic yet powerful tool to expand the options available when building workflows and enable more complex functionality.

### 2. Additional context or comments

Lastly, I would like to suggest adding a way to support the project, such as a "Buy me a coffee" option. I believe that a sustainable financial model will help the project thrive in the long term. If a commercial model hasn’t been decided yet, this could allow us, the users, to make small contributions to support its development.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Thanks for your suggestion :)

> Lastly, I would like to suggest adding a way to support the project, such as a "Buy me a coffee" option. I believe that a sustainable financial model will help the project thrive in the long term. If a commercial model hasn’t been decided yet, this could allow us, the users, to make small contributions to support its development.

Well the best way to support us is contributing something to our repo, refine the docs, typos, bug fixes, features are always welcome. :)

**Comment by crazywoola** [comment]
> it doesn’t currently apply to workflows within the iteration module.

On its way :)

**Comment by VincePotato** [comment]
Thank you for your suggestion. Iterative support for parallel and loop nodes is already in the product roadmap, and we expect to support these features around Q4.
