### ISSUE TITLE
Unavailable Text-embedding model in Knowledge

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#8227]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![CleanShot 2024-09-10 at 15 53 22](https://github.com/user-attachments/assets/6d52e6b4-e455-4339-85e4-be64c042007c)

### ✔️ Expected Behavior

Use the model that was set in step two of creating the knowledge. 

### ❌ Actual Behavior

Have to go into the knowlegde after it's created and set the embedding model again.

**Comment by crazywoola** [comment]
@AndyMik90 https://github.com/langgenius/dify/issues/8175 Did you encounter something like this issue?

**Comment by AndyMik90** [comment]
@crazywoola could this have something to do with the  "deprecated" field for models?

**Comment by crazywoola** [comment]
Please try v0.8.3, it seems @JohnJyong had fixed this issue.
