### ISSUE TITLE
workflow tool not stream output in chat workflow

### ISSUE THREAD

**Issue by kenneth-bro** [langgenius/dify#8232]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The workflow tool does not need to be output in a stream in the Chat workflow. It can only be output by blocking.
![image](https://github.com/user-attachments/assets/c18aa4e0-8a85-427a-84e1-6baf531407b1)

### ✔️ Expected Behavior

Can be stream output

**Comment by crazywoola** [comment]
This is by design.
