### ISSUE TITLE
Add name: dify at the top of docker-compose.yaml

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8233]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Add name: dify at the top of docker-compose.yaml

So that docker desktop shows "dify" instead of "docker"

<img width="568" alt="image" src="https://github.com/user-attachments/assets/30ee5854-a1b6-430f-beea-08ac9ea6c196">

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/fb5e3662d50130d672821293ede40e0863ee6f14/api/README.md#L16
