### ISSUE TITLE
Unstructure service is not being pulled due to wrong image address

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8234]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

should be downloads.unstructured.io/unstructured-io/unstructured:latest

should not be downloads.unstructured.io/unstructured-io/unstructured-api:latest

official docs: https://docs.unstructured.io/open-source/installation/docker-installation

**Comment by taowang1993** [comment]
The image has been changed to unstructured downloads.unstructured.io/unstructured-io/unstructured:latest

without -api 

please read the docs

and i already set the variables to 
ETL_TYPE=Unstructured
UNSTRUCTURED_API_URL=http://unstructured:8000/general/v0/general

it is still not pulling the image

**Comment by crazywoola** [comment]
You can change the url in docker-compose.yml to see if this works and you can open a pr for this as well.

**Comment by taowang1993** [comment]
I have to use this command, right? If so, please add notes in the docs. Thanks~
docker-compose --profile unstructured up
