### ISSUE TITLE
How to change all dify templates to Chinese

### ISSUE THREAD

**Issue by lizhanyang505** [langgenius/dify#8243]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

How to change all dify templates to Chinese？
![image](https://github.com/user-attachments/assets/0711f719-54df-4fb7-bf27-b0d59632944b)
![image](https://github.com/user-attachments/assets/3ac494d1-2c9d-4f09-85b6-2c3dd9132e9e)

### ✔️ Expected Behavior

plase help me how to config

**Comment by crazywoola** [comment]
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/0aac4ee8-6a74-44a8-80b8-32d573b9693a">
