### ISSUE TITLE
GUI for monitoring and view progress of task

### ISSUE THREAD

**Issue by nhha1602** [langgenius/dify#8248]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Do we support a GUI that we can see the progress of task processing or monitor of task processing on worker ? It is helpful for the task that take time to handle when we use API to add file for a Knowledge ...

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I don't think it's a feature request to Dify itself. Try this one. https://github.com/mher/flower
