### ISSUE TITLE
How to change all dify templates to Chinese

### ISSUE THREAD

**Issue by lizhanyang505** [langgenius/dify#8250]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/318e222e-c7b6-4e27-b3b1-6b62873b11e6)
![image](https://github.com/user-attachments/assets/2eca23b8-7f57-4dd7-85e9-b6e8c7ed05d6)
![image](https://github.com/user-attachments/assets/348c74e2-d100-4f37-b96a-8cfd8a5826e8)

**Comment by crazywoola** [comment]
Have you read the last post? https://github.com/langgenius/dify/issues/8243

**Comment by lizhanyang505** [comment]
![image](https://github.com/user-attachments/assets/d4373b57-c5b7-47ff-afd0-8f6cbf947a17)
It's not possibale

**Comment by lizhanyang505** [comment]
@crazywoola Thank you, I have configured it according to the above, but it is still in Chinese?

**Comment by kunlun122** [comment]
I solved the issue by changing the language setting twice. 
1.set the language to English. refresh the system.
2.set the language to Chinese . All template will be changed to chinese.
Hope this helps you.

> ![image](https://private-user-images.githubusercontent.com/49928490/366314151-d4373b57-c5b7-47ff-afd0-8f6cbf947a17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NTYxODksIm5iZiI6MTczNTQ1NTg4OSwicGF0aCI6Ii80OTkyODQ5MC8zNjYzMTQxNTEtZDQzNzNiNTctYzViNy00N2ZmLWFmZDAtOGY2Y2JmOTQ3YTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDA3MDQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZmM3ZjE4MDE4MTVjNGY2MzFmMDA3NGE3N2MxZDVkZjc0YWVlZTY1MGEwZDUzZDI2OWJiNTljYzAyMjNhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZWPsDqfAwRyxVzeYh5BfVdOyOu6xvl9N0DzuTZhpAr4) It's not possibale
