### ISSUE TITLE
ZhiPu APIReachLimitError

### ISSUE THREAD

**Issue by XinleZhou2018** [langgenius/dify#8251]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![企业微信20240911-134333](https://github.com/user-attachments/assets/8e8b6870-b4ee-4c1d-aa94-01028ac42d47)

Today, I registered a new zhipu ai key. 
As screenshot shows, it shows APIReachLimitError.
When I changed the new key with the old key which I registered several days before. It works.

### ✔️ Expected Behavior

the new zhipu key works.

### ❌ Actual Behavior

the new zhipu key not works.

**Comment by crazywoola** [comment]
If you encounter a rate-limit error, please upgrade your billing or contact their support to upgrade the limit. We can do nothing but report an error.
