### ISSUE TITLE
Plan to deprecate some of OpenAI’s models

### ISSUE THREAD

**Issue by laipz8200** [langgenius/dify#8254]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

<img width="603" alt="image" src="https://github.com/user-attachments/assets/6ba7aee3-45bd-4b48-a9a6-6c9a1686d4a9">

This work should be done this week to be released next week.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by xiangpingjiang** [comment]
@laipz8200 hello, Can I work on this issue?

**Comment by laipz8200** [comment]
> @laipz8200 hello, Can I work on this issue? 

Of course, have fun!

**Comment by laipz8200** [comment]
Hi, @xiangpingjiang! Are you ready to complete this? Could you share your plan?

**Comment by laipz8200** [comment]
Hi @xiangpingjiang. We need to apply this change now, so I'll unassign this from you.
