### ISSUE TITLE
var-picker not update when edges change in node panel

### ISSUE THREAD

**Issue by HiChen404** [langgenius/dify#8258]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When focusing on a node and changing the connection, the variables in the `var-picker` will not be updated to the latest.

https://github.com/user-attachments/assets/d51d62e5-0c65-4aee-822d-b91d6b268a56

### ✔️ Expected Behavior

 var list updated to the latest when connected edges change.

### ❌ Actual Behavior

Refresh only when switching node panel.

**Comment by iamjoel** [comment]
Fixed: https://github.com/langgenius/dify/pull/8259
