### ISSUE TITLE
Any way to log request content to/ response from LLM directly

### ISSUE THREAD

**Issue by xinyual** [langgenius/dify#8260]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hi team, I have a really excited experience using dify. But I'm very confused whether I can get real response/request content in the lowest level LLM API? For example, If I use anthropic, can I get the real prompt I send to claude 3?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://docs.dify.ai/guides/monitoring/integrate-external-ops-tools
