### ISSUE TITLE
How to generate agent prompt in Chinese

### ISSUE THREAD

**Issue by BBaconjack** [langgenius/dify#8267]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

<img width="1143" alt="截屏2024-09-11 17 22 06" src="https://github.com/user-attachments/assets/6ea0aa05-b29a-46dd-ae9d-d267e4393a2a">
I've already set language option = Chinese as following steps, but when I use LLM ( I've tried GLM-4 series)for agent prompt generating, it only give me prompt templates in English
<img width="515" alt="截屏2024-09-11 17 22 36" src="https://github.com/user-attachments/assets/b50a042f-97d4-4a44-9f54-90687e94e989">
<img width="1024" alt="截屏2024-09-11 17 22 58" src="https://github.com/user-attachments/assets/086423c8-e690-4f5a-bdb5-a961bf80bf17">

**Comment by crazywoola** [comment]
Well this is not supported yet.

**Comment by BBaconjack** [comment]
> Well this is not supported yet.

<img width="1142" alt="截屏2024-09-11 17 43 25" src="https://github.com/user-attachments/assets/b19f465a-2e3c-4314-aa44-4b3abb5c8922">
but i tried cloud.dify.ai and it seems like supported already

**Comment by crazywoola** [comment]
> > Well this is not supported yet.
> 
> <img alt="截屏2024-09-11 17 43 25" width="1142" src="https://private-user-images.githubusercontent.com/73780794/366397750-b19f465a-2e3c-4314-aa44-4b3abb5c8922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDg1MTUsIm5iZiI6MTcyNjA0ODIxNSwicGF0aCI6Ii83Mzc4MDc5NC8zNjYzOTc3NTAtYjE5ZjQ2NWEtMmUzYy00MzE0LWFhNDQtNGIzYWJiNWM4OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5NTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NDExZDU1ZDIyNzg2OGRmZDc0MmUzNTQzM2I3MjRjZDg3Mjk3MjMzNGFlODMxZTUzMzc4NWYxZmIzMjMxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6JX9g2RBQYfcR-Q7uzMJxzxDhoOjI5AqlaTAVHe8UFM"> but i tried cloud.dify.ai and it seems like supported already

Actually it depends how the LLM responds, the prompt should be English, I think you can try to force it to Chinese by telling it to do so.

**Comment by VincePotato** [comment]
Prompt Generator supports multiple languages and includes built-in prompts that contain relevant instructions, requiring the model to follow the user's input language when generating prompts. However, since this feature relies on the instruction-following capabilities of the selected model, the output quality depends on the chosen model. 

Therefore, we recommend switching to a more capable inference model within the application for better results.
