### ISSUE TITLE
Application Configuration with Ollama Causes the Model to Run on CPU

### ISSUE THREAD

**Issue by BingFrost** [langgenius/dify#8268]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.71

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Ollama is running on a GPU server, and when using default parameters in an application created with Dify, the model runs correctly and GPU utilization remains unaffected. However, when changing certain parameters, such as Size of context window = 102400, the model that was previously running on the GPU switches to running on the CPU instead.

This issue significantly affects performance and seems to be related to how Ollama handles the modified configuration parameters.

![image](https://github.com/user-attachments/assets/e3495622-789e-4612-bb3c-df827f191f62)
![image](https://github.com/user-attachments/assets/e3495622-789e-4612-bb3c-df827f191f62)
![image](https://github.com/user-attachments/assets/e3495622-789e-4612-bb3c-df827f191f62)

![image](https://github.com/user-attachments/assets/ede652cf-a85f-493d-b5aa-2f948f7601dd)
![image](https://github.com/user-attachments/assets/ede652cf-a85f-493d-b5aa-2f948f7601dd)
![image](https://github.com/user-attachments/assets/ede652cf-a85f-493d-b5aa-2f948f7601dd)

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/2cf1187b32c0885e9f9b987d57c6ca9da4508a2c/api/core/model_runtime/model_providers/ollama/llm/llm.py#L580-L592

See above codes.

**Comment by BingFrost** [comment]
I think the answer is error. The GPU's memory is sufficient to run。

> Changing the "Size of context window" parameter to 102400 in an application created with Dify causes the model to switch from running on the GPU to running on the CPU because the context window size exceeds the memory capacity of the GPU. The GPU cannot handle such a large context window, so the computation falls back to the CPU, which can handle larger memory requirements but at the cost of significantly reduced performance [[1]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/ollama/llm/llm.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

**Comment by crazywoola** [comment]
@BingFrost Only above codes involves GPU related stuff, we didn't do much modification on their api :)
