### ISSUE TITLE
dify configure frp and access abnormality after intranet penetration

### ISSUE THREAD

**Issue by lizhanyang505** [langgenius/dify#8274]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Access to the internal network is normal, but the external network penetration report fails to pre-check.
[[proxies]]
name = "dify"    # 应用名，自定义
type = "tcp"        # 连接方式：有http,https,UDP等
localIP = "192.168.12.76"   # 本地连接地址
localPort = 3000        # 本地端口
remotePort = 3005 
![image](https://github.com/user-attachments/assets/2813c12c-547a-4efe-be64-c1d6324be6b4)
![image](https://github.com/user-attachments/assets/c3a8dee8-6811-42cc-8526-ee555d5c6d07)
![image](https://github.com/user-attachments/assets/7f3c048d-46ba-4f8b-ad17-3c052a2dd8ab)

**Comment by crazywoola** [comment]
> If my local IP is 192.168.12.76, how can I configure the information to solve the problem of cors without using nginx?

If you need to access from a public address, the env settings should be that as well.

**Comment by lizhanyang505** [comment]
@crazywoola I followed the above operation, but the result failed. Could you please provide a link or explanation to the complete operation document? Thanks~。
