### ISSUE TITLE
Can not drag second line to build parellel workflow

### ISSUE THREAD

**Issue by realcarlos** [langgenius/dify#8276]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="732" alt="image" src="https://github.com/user-attachments/assets/01e25305-5956-4f91-9c1d-65be80647b5c">

**Comment by crazywoola** [comment]
I suggest refreshing the page to see if this persists.
