### ISSUE TITLE
Knowledge base image recall cannot be accessed

### ISSUE THREAD

**Issue by 401557122** [langgenius/dify#8279]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The markdown file link returned by the knowledge base storage file is as follows, but it seems that this link cannot be displayed or accessed in the intelligent agent
image_map[rel.target_part] = (
f"! [image]({dify_config.CONSOLE_API_URL}/files/{upload_file.id}/image-preview)"

![image](https://github.com/user-attachments/assets/9c89fc23-9abd-464a-8c9a-2fd241472135)

### ✔️ Expected Behavior

The markdown link that needs to be saved can be accessed so that the agent can display recommendations for the user

**Comment by crazywoola** [comment]
If you would like to let the agent to understand the image. You need to make sure below things:

- The LLM is vision ready
- You need to to turn on the image uploading feature
- You need to upload image or insert the link in the UI

<img width="415" alt="image" src="https://github.com/user-attachments/assets/53637267-b852-496b-bed4-f80bdc9ce7b5">
