### ISSUE TITLE
The chat dialog box is too wide, how to adjust the scale

### ISSUE THREAD

**Issue by liduang** [langgenius/dify#8280]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The chat dialog box is too wide, how to adjust the scale？
![image](https://github.com/user-attachments/assets/a9ef3070-2cc9-4ee0-947e-5e4594c77538)

**Comment by liduang** [comment]
Why is the size of chatbot's dialog box different from that of chat's dialog box?

**Comment by liduang** [comment]
Why was the width of chatbot and chat the same in the previous version, and how can I change it back in this version?
![image](https://github.com/user-attachments/assets/3104e4f7-56e3-46d3-8763-5d9bbe28d467)

**Comment by liduang** [comment]
It's useless, you're adjusting the chatbot's dialog box size, not the chat's dialog box size

**Comment by crazywoola** [comment]
We will take a look at this.

**Comment by liduang** [comment]
style="width: 50px; height: 100%; min-height: 700px"，error!

**Comment by liduang** [comment]
不懂前端代码，我就想改回去，一样宽度太丑了

**Comment by liduang** [comment]
I don't understand front-end code, so I want to change it back. The same width is too ugly!
