### ISSUE TITLE
error occurred when I used dify to integrate the embedding model deployed by ollama

### ISSUE THREAD

**Issue by hanyimei** [langgenius/dify#8281]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

An error occurred when I used dify to integrate the embedding model deployed by ollama：
An error occurred during credentials validation: Session.request() got an unexpected keyword argument 'options'
This is not an issue when using dify v0.7.2, and the same error occurs when replacing the embedding model deployed in ollama

### ✔️ Expected Behavior

Integrate the embedding model deployed by ollama on dify

### ❌ Actual Behavior

An error occurred during credentials validation: Session.request() got an unexpected keyword argument 'options'

**Comment by crazywoola** [comment]
This has been fixed. See above discussions.

**Comment by hanyimei** [comment]
It worked fine when I used the same url to integrate large models deployed by ollama

**Comment by hanyimei** [comment]
I don't understand your solution, please explain it in detail
