### ISSUE TITLE
The problem classifier will output all the strings in the directly replied nodes of the connection

### ISSUE THREAD

**Issue by MIM1993** [langgenius/dify#8282]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/8ec5f6e7-cdbf-4366-86d4-00b674bbd92c)

### ✔️ Expected Behavior

Only output the string corresponding to the direct reply

### ❌ Actual Behavior

All the strings in the direct replies have been printed out

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/8225
