### ISSUE TITLE
The latest release version 0.8 is incorrect.

### ISSUE THREAD

**Issue by haike-1213** [langgenius/dify#8283]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

The latest release version 0.8 is incorrect.

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/46d2eecb-bcaa-4f22-98ef-0aa55c92f452)

### ❌ Actual Behavior

ImportError: cannot import name 'GenerateTaskStoppedException' from 'core.app.apps.base_app_queue_manager'

**Comment by crazywoola** [comment]
<img width="671" alt="image" src="https://github.com/user-attachments/assets/3e48f263-59d3-4947-9ef2-b872985fe902">

**Comment by haike-1213** [comment]
![image](https://github.com/user-attachments/assets/c2001ad5-6be9-467d-b4a6-7ddf8f116c09)
