### ISSUE TITLE
When the model is changed, the parameters are not automatically adjusted, resulting in an error

### ISSUE THREAD

**Issue by wonca** [langgenius/dify#8290]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The maximum output length of the same LLM node will not change with the adjustment of the model after the model is changed. If the maximum output length of the current model is greater than the maximum output length of the replaced model, an error will be reported.
![7801726113100_ pic](https://github.com/user-attachments/assets/b379c772-77a9-45dc-b6db-cfdaae05c38d)
![7811726113100_ pic](https://github.com/user-attachments/assets/fe1951d1-862f-4a4c-b3b9-cbdf0f35fb5f)
![7831726113101_ pic](https://github.com/user-attachments/assets/fc2c4a00-e487-4f12-86dc-975b4d158952)

### ✔️ Expected Behavior

When changing the model, the relevant parameters can be automatically modified to the legal range

### ❌ Actual Behavior

The maximum model output length was not automatically modified to the legal range, resulting in an error when the model was changed and run.

**Comment by crazywoola** [comment]
Some model providers doesn't have `max_tokens`, they have `num_predict` instead, so it's hard to cover all scenarios. So we leave those red error messages to indicates the parameter is wrong.
