### ISSUE TITLE
Using the qwen2-7B-q8 model, the GPU can reach 14-15GB when accessed with the API

### ISSUE THREAD

**Issue by bingbing6** [langgenius/dify#8294]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/20f82e23-34e1-40b0-9b00-4a1b19383a76)
![image](https://github.com/user-attachments/assets/c782e1a3-0518-4a31-98f3-9edcd4d77e6f)
![image](https://github.com/user-attachments/assets/e4a7b62b-f3e6-4cfb-8475-11066267abd2)
A chatbot was released on Dify, using the LLM Qwen2-7b-8q, which is accessed via an API

### ✔️ Expected Behavior

Normally it should be 9GB

### ❌ Actual Behavior

But with an API call it goes up to 15GB

**Comment by bingbing6** [comment]
What causes this to happen? How to fix it?

**Comment by bingbing6** [comment]
> 您确定这是我们的问题吗？我们也调用 Ollama API。我们在这里没有做任何神奇的事情。
我用qwen2-7b-q4的话，dify网页访问和api调用，他都是6GB显存，但是我用q8的话，网页是9GB，一旦使用api就马上升到15GB。哪怕重启只使用api也是马上升到15GB，我如果单独调ollama的api接口，就还是9GB。所以下问问为啥用dify的api，用qwen2-7b-q8时，他会增加到15GB呢，按道理是9GB.下图是我直接用ollama的api接口截图
![image](https://github.com/user-attachments/assets/2dbc8f53-a8ce-43cf-806d-9255686757a5)

**Comment by crazywoola** [comment]
<img width="281" alt="image" src="https://github.com/user-attachments/assets/47bb4d0a-5fe5-441a-8847-f87fbd8612d8">
It depends the settings here I guess?

**Comment by bingbing6** [comment]
> <img alt="图像" width="281" src="https://private-user-images.githubusercontent.com/100913391/366753029-47bb4d0a-5fe5-441a-8847-f87fbd8612d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjQyNjgsIm5iZiI6MTcyNjEyMzk2OCwicGF0aCI6Ii8xMDA5MTMzOTEvMzY2NzUzMDI5LTQ3YmI0ZDBhLTVmZTUtNDQxYS04ODQ3LWY4N2ZiZDg2MTJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwNjUyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzM2ZmRhZmZkYzI0ZTY3NjMwMzBjMjJlOGZhMDNkNGI4M2RiYmNlODI0MzcxZTNkMDAyOGYxZjZlZmQ0YmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SnQgdBUZnSvhTcKDDXT2nDA28RSynrS1IZtXEUNDIQU">我猜这取决于这里的设置？

![image](https://github.com/user-attachments/assets/6543c964-1062-4249-8b70-2c7e51a19a43)
![image](https://github.com/user-attachments/assets/d3c19613-f1a2-4399-b532-5957568a8082)
我只给了名称和URL、上下文长度，其他的都是默认的。请问应该怎么设置呢？

**Comment by crazywoola** [comment]
Sorry I dont think this is a problem raised by us.

**Comment by bingbing6** [comment]
> 抱歉，我不认为这是我们提出的问题。

可是我用的是默认的呀，按道理默认的不应该这样呀

**Comment by crazywoola** [comment]
I think you can post an issue on their repo as well.

**Comment by bingbing6** [comment]
> 我认为您也可以在他们的 repo 上发布问题。

您指的是去qwen发布问题吗？

**Comment by crazywoola** [comment]
No I mean https://github.com/ollama/ollama

**Comment by bingbing6** [comment]
> 不，我是说 https://github.com/ollama/ollama

可是我直接用ollama的api，GPU是正常的9GB。用dify的api才上升到15GB的。这个应该去他们那发布问题吗？不过我也可以去他们那问一下咯

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/c69f5b07ba241e6ef08c7028c12b1125c93c1d01/api/core/model_runtime/model_providers/ollama/llm/llm.py#L225-L235

**Comment by bingbing6** [comment]
> https://github.com/langgenius/dify/blob/c69f5b07ba241e6ef08c7028c12b1125c93c1d01/api/core/model_runtime/model_providers/ollama/llm/llm.py#L225-L235

发这个是干啥的？需要我做什么吗？

**Comment by crazywoola** [comment]
我的意思是我们也是调用的 API 除了请求参数不同，没有任何的不同。

**Comment by bingbing6** [comment]
> 我的意思是我们也是调用的 API 除了请求参数不同，没有任何的不同。

谢谢，那我去ollama提问看看

**Comment by bingbing6** [comment]
> 我的意思是我们也是调用的 API 除了请求参数不同，没有任何的不同。

我好像知道为什么了，调用api时他把7b那个也启动了。但我选的是7b-q8。是不是使用api时，你们对name进行了模糊匹配之类的启动，所以把两个都启动了？
![image](https://github.com/user-attachments/assets/454b1d3b-98fe-4559-9c2f-9330bc636a2b)

**Comment by bingbing6** [comment]
![image](https://github.com/user-attachments/assets/b0706825-0034-4c2e-ae3e-562e741272bc)

**Comment by bingbing6** [comment]
![image](https://github.com/user-attachments/assets/9821a080-a3da-4872-9f39-ab8260846889)
关闭开关，暂时也可以解决这个问题
![image](https://github.com/user-attachments/assets/c421ba36-4cb7-43b0-aa98-9252530b0d48)
