### ISSUE TITLE
 Error reported when using knowledge base embedding model text-embedding-3-large

### ISSUE THREAD

**Issue by 18075717849** [langgenius/dify#8295]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

An error is reported when using the knowledge base embedding model text-embedding-3-large, but it actually has a token, and switching to other embedding models does not report an error.
![image](https://github.com/user-attachments/assets/b7d2cde8-29cf-4422-8932-936b07652f3c)

### ✔️ Expected Behavior

Find the reason why the index fails, but it will be fine if you change the model

### ❌ Actual Behavior

text-embedding-3-large model error

**Comment by crazywoola** [comment]
Is is an official key from OpenAI?

**Comment by 18075717849** [comment]
> 这是来自 OpenAI 的官方密钥吗？

No, it’s the secret key provided by the transfer platform

**Comment by crazywoola** [comment]
This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.

See duplicated question here. https://github.com/langgenius/dify/issues/7351

**Comment by imxieqing** [comment]
从0.6版本到0.8版本 dify还是没有兼容这个问题

**Comment by imxieqing** [comment]
There is still no compatibility issue with dify from version 0.6 to version 0.8
