### ISSUE TITLE
LangSmith config Weird checker leads to error (0.8.0 problem)

### ISSUE THREAD

**Issue by dchang10** [langgenius/dify#8298]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I tried adding a langsmith config to a project, but the newly added get_project_url() function keeps returning "LangSmith get run url failed: xyz" error.

### ✔️ Expected Behavior

It is supposed to be an easy link to langsmith. 

### ❌ Actual Behavior

LangSmith get run url failed: xyz

**Comment by dchang10** [comment]
What dosu commented does not help with this bug. Yes, it is an error thrown by the get_run_url() function. However, it is not clear why that check is even needed, and why the behavior of this simple langsmith config setup deviates from previous dify versions.

**Comment by charli117** [comment]
@dchang10 The test did not reproduce your problem, make sure that the https://smith.langchain.com network is reachable

**Comment by dchang10** [comment]
@charli117 When you are setting config for langsmith, do you have to match the project name with something? Or could I name it anything? https://smith.langchain.com is reachable.

**Comment by charli117** [comment]
The project name must be the same as the langsmith project name, otherwise the project address will not be obtained

**Comment by dchang10** [comment]
@charli117 Langsmith project creation is done when the first log is sent in. The only "name" that is specified is the "Description" you enter on Langsmith when an API key is created.

**Comment by charli117** [comment]
Project value correspond to the following fields
![image](https://github.com/user-attachments/assets/a83a9ef8-f353-4c21-b3cf-3d29c09506dc)

**Comment by crazywoola** [comment]
Please try to upgrade to v0.8.3 to see if this persists.
