### ISSUE TITLE
Dialogue output in card format

### ISSUE THREAD

**Issue by wjmgyn** [langgenius/dify#8300]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In the dialog window, you can customize output cards, such as the binding cards in Coze, to achieve the following effects.![20240912153833](https://github.com/user-attachments/assets/4de04e2f-41e2-4b74-b4ec-bc200c969b2c)
![20240912153817](https://github.com/user-attachments/assets/97c499eb-aebe-4e29-80c4-67d2e93e87dd)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by wjmgyn** [comment]
This is quite different from what I need. It’s not simply about combining text and images. I need to place the output results into a custom card template.

**Comment by wjmgyn** [comment]
![image](https://github.com/user-attachments/assets/38bf3812-6c57-49a4-81d7-ce15500bf6c4)
Desired effect

**Comment by crazywoola** [comment]
This feature seems like a lot of work, and I'll give feedback to the team, but I don't think we have the energy to do this at the moment

**Comment by wjmgyn** [comment]
Alright, thank you! If developers can define various dialogue templates themselves, is there a way to bind the return results to their designed templates, and finally display them in the dialogue box? I believe that expanding this type of interaction can make the dialogue form more diverse and colorful.

**Comment by crazywoola** [comment]
If we could allow render HTML tag in the conversation, that could achieve what you wanna do. We are evaluating the risks of render raw HTML.

**Comment by wjmgyn** [comment]
Thank you! Looking forward to your evaluation results.

**Comment by crazywoola** [comment]
![QQ_1729854146800](https://github.com/user-attachments/assets/bb4d88b5-d857-4a3a-9463-2631969d3897)
@KS-OTO @wjmgyn
