### ISSUE TITLE
How to configure related files to solve web access CORS problems. If the local ip is 192.168.11.11, please give a specific example?

### ISSUE THREAD

**Issue by lizhanyang505** [langgenius/dify#8302]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

How to configure related files to solve web access COS problems. If the local ip is 192.168.11.11, please give a specific example?

**Comment by crazywoola** [comment]
Please notice that this is a bug report template, for getting help please open a discussion here https://github.com/langgenius/dify/discussions to see if there is someone could help.
