### ISSUE TITLE
All apps show as unpublished

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#8304]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Publish any app.

<div>
    <a href="https://www.loom.com/share/29738cd7e1cb47eeac7fc5ee1d5f39fd">
      <p>Studio - Dify - 12 September 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/29738cd7e1cb47eeac7fc5ee1d5f39fd">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/29738cd7e1cb47eeac7fc5ee1d5f39fd-43b0907e69510814-full-play.gif">
    </a>
  </div>

### ✔️ Expected Behavior

Saved publish state

### ❌ Actual Behavior

Apps stay as unpublished

**Comment by crazywoola** [comment]
Can you @vicoooo26 take a look at this?
