### ISSUE TITLE
Bedrock load balancing configuration error

### ISSUE THREAD

**Issue by jianbo-wu-20230331** [langgenius/dify#8305]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.8.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Settings -> Model Provider -> Bedrock - > Load Balance

### ✔️ Expected Behavior

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/cc262a34-b57e-4ced-af99-aa7cc5fc81cc">

### ❌ Actual Behavior

Bedrock supports IAM role authentication, eliminating the need to check AK/SK.

**Comment by crazywoola** [comment]
We do not support Loading balancing in this version `Self Hosted (Source)`. This is a SaaS only feature.
