### ISSUE TITLE
invalid node type value iteration-start

### ISSUE THREAD

**Issue by tangjinhan** [langgenius/dify#8308]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0-beat1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/332cc3b2-0077-4251-b3d7-44aac753f8b4)
When the workflow on the diagram is executed, the message "invalid node type value iteration-start" is displayed.

**Comment by crazywoola** [comment]
Please attach the dsl here.

**Comment by tangjinhan** [comment]
参见附件的压缩文件

**Comment by crazywoola** [comment]
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/20c0d278-852d-4de9-94f8-6d07943b9eb5">
Can't reproduce in latest branch, please upgrade to latest to see if this persists.

**Comment by tangjinhan** [comment]
The issue was resolved after updating to the latest version
