### ISSUE TITLE
Stream api issue: chatbot-workflow cannot response with 'message' event in certain situation.

### ISSUE THREAD

**Issue by qdyujiang002** [langgenius/dify#8309]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/e41e4f7e-bfa1-43a0-9982-4fc62abbc70d">
1. create chatbot-workflow
2. add LLM node
3. then add Iteration node or Template node after LLM node
4. add End node
5. publish this workflow
6. request stream api for this workflow
7. got SSE response

### ✔️ Expected Behavior

when stream coming to LLM node, then it should be response with event type 'message' between event type 'node_start' and 'node_finish' like this:
<img width="431" alt="image" src="https://github.com/user-attachments/assets/357029de-01e2-4a44-bdbc-16a66f0e1c9d">

### ❌ Actual Behavior

When chatbot-workflow using certain node(such like 'Template node' or 'Iteration node') after 'LLM node', then the stream api response coming to LLM node has no event type 'message', only have event type 'node_start' and 'node_finish', the stream response the LLM answer give all the answers at once in event type 'node_finish' like this:
<img width="412" alt="image" src="https://github.com/user-attachments/assets/30e1e714-bf98-43db-be37-9faf785b599e">

**Comment by qdyujiang002** [comment]
This problem occurs on 'LLM node' whenever there is a 'Template node' or other specific node after the LLM node, no matter how many nodes are separated in between

**Comment by fly0311** [comment]
![WX20240913-195714@2x](https://github.com/user-attachments/assets/563e0e10-118b-4821-a6f5-34a295d067f6)

I've encountered a similar issue, but my problem is exactly the opposite, where two unexpected messages are output immediately after the first node ends.

**Comment by laipz8200** [comment]
Is this issue still present in the latest version (0.8.3)? I'd love to hear your feedback.

**Comment by qdyujiang002** [comment]
> Is this issue still present in the latest version (0.8.3)? I'd love to hear your feedback.

yes, it still present in the newest version.

**Comment by laipz8200** [comment]
After some testing, I believe there are a few key points to share:

1. If the output of the LLM Node is not used in the Template Node, the stream of the Answer Node will not be blocked. You can create a minimal workflow to verify this.
2. If there is an Iteration Node before the Answer Node, it will be blocked. This is because the Iteration Node can also contains the Answer Node, and we currently do not have a way to determine this.
3. If you don't want the Iteration Node to block unrelated Answer Nodes, you can place the Answer Node before the Iteration Node.

I hope this helps resolve your issue!

**Comment by qdyujiang002** [comment]
> After some testing, I believe there are a few key points to share:
> 
> 1. If the output of the LLM Node is not used in the Template Node, the stream of the Answer Node will not be blocked. You can create a minimal workflow to verify this.
> 2. If there is an Iteration Node before the Answer Node, it will be blocked. This is because the Iteration Node can also contains the Answer Node, and we currently do not have a way to determine this.
> 3. If you don't want the Iteration Node to block unrelated Answer Nodes, you can place the Answer Node before the Iteration Node.
> 
> I hope this helps resolve your issue!

Sorry, my expression may be inaccurate. The Node stream that is blocked is not the Answer Node, but the streaming of LLM Node itself. The overall meaning is that if LLM Node exists in a workflow and there are other nodes behind LLM Node, For example, in the case of Template Node, when the stream api of this workflow is executed to LLM Node, the steam of LLM Node itself is blcok, instead of the final Answer node is blocked.

**Comment by laipz8200** [comment]
> > After some testing, I believe there are a few key points to share:
> > 
> > 1. If the output of the LLM Node is not used in the Template Node, the stream of the Answer Node will not be blocked. You can create a minimal workflow to verify this.
> > 2. If there is an Iteration Node before the Answer Node, it will be blocked. This is because the Iteration Node can also contains the Answer Node, and we currently do not have a way to determine this.
> > 3. If you don't want the Iteration Node to block unrelated Answer Nodes, you can place the Answer Node before the Iteration Node.
> > 
> > I hope this helps resolve your issue!
> 
> Sorry, my expression may be inaccurate. The Node stream that is blocked is not the Answer Node, but the streaming of LLM Node itself. The overall meaning is that if LLM Node exists in a workflow and there are other nodes behind LLM Node, For example, in the case of Template Node, when the stream api of this workflow is executed to LLM Node, the steam of LLM Node itself is blcok, instead of the final Answer node is blocked.

Our message event is generated by the whole workflow, not the output from the LLM Node.

**Comment by qdyujiang002** [comment]
> > > After some testing, I believe there are a few key points to share:
> > > 
> > > 1. If the output of the LLM Node is not used in the Template Node, the stream of the Answer Node will not be blocked. You can create a minimal workflow to verify this.
> > > 2. If there is an Iteration Node before the Answer Node, it will be blocked. This is because the Iteration Node can also contains the Answer Node, and we currently do not have a way to determine this.
> > > 3. If you don't want the Iteration Node to block unrelated Answer Nodes, you can place the Answer Node before the Iteration Node.
> > > 
> > > I hope this helps resolve your issue!
> > 
> > 
> > Sorry, my expression may be inaccurate. The Node stream that is blocked is not the Answer Node, but the streaming of LLM Node itself. The overall meaning is that if LLM Node exists in a workflow and there are other nodes behind LLM Node, For example, in the case of Template Node, when the stream api of this workflow is executed to LLM Node, the steam of LLM Node itself is blcok, instead of the final Answer node is blocked.
> 
> Our message event is generated by the whole workflow, not the output from the LLM Node.

Oh I see, thanks
