### ISSUE TITLE
Question Classifier + Knowledge + Chatbot Demo bug！！

### ISSUE THREAD

**Issue by zzkzzk1984** [langgenius/dify#8312]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using problem classification, each time before entering branch 1, branch 3 will be triggered once, and the process does not show its triggering, and the reason for the trigger is not known.

![image](https://github.com/user-attachments/assets/c824321f-f324-48d6-9d2a-d060d05e66ba)

**Comment by crazywoola** [comment]
Duplicated, this is resolved in main branch.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/8225
