### ISSUE TITLE
The image size parameter in the cogvlm tool does not match the parameter provided on the official Zhipu website, which can cause interface errors.

### ISSUE THREAD

**Issue by jiaolongxue** [langgenius/dify#8315]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The image size parameter in the cogvlm tool does not match the parameter provided on the official Zhipu website, which can cause interface errors.
## cogvlm tool

![image](https://github.com/user-attachments/assets/b5208c6d-eaa0-4d29-9a76-492de97d2a7f)

## zhipu website

![image](https://github.com/user-attachments/assets/ebf9c1f2-cf1e-4e69-a2be-e3e5616761d4)

## error

![image](https://github.com/user-attachments/assets/d01c215e-73ca-457f-aa25-972e465c6976)

### ✔️ Expected Behavior

success

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/40c71ca4-e3b2-4151-a83d-2150e2804ffb)

**Comment by crazywoola** [comment]
@ox01024 Hello can you update this tool?

**Comment by ox01024** [comment]
Leave it to me. I'll take care of him as soon as possible. Don't worry.

> @ox01024 Hello can you update this tool?

Leave it to me. I'll take care of him as soon as possible. Don't worry.
