### ISSUE TITLE
stable difussion can't generate correct picture in agent with llama model

### ISSUE THREAD

**Issue by marco-qu** [langgenius/dify#8316]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

SD & DIFY docker configured in  local computer.
create a new agent using stable difussion  tools, want to generate picture according by user input text.
Although created a picture successfully, there is error occured at the same time, some information as below:
<img width="809" alt="a93b8a10c4d0f594e92c0ba4096c6b6" src="https://github.com/user-attachments/assets/2f6ef720-7d13-487f-b2e6-049589dee51d">
<img width="927" alt="2c58499d5fcbd5444d8287bfabb29d8" src="https://github.com/user-attachments/assets/f469b690-5d3e-433c-9d59-5a91fdcb1a70">
when 1 picture created, the program crached, exit and refresh the page, I can see the picture as above.

### ✔️ Expected Behavior

get correct picture and program no crach

### ❌ Actual Behavior

program crached and need reopen the page.

**Comment by marco-qu** [comment]
actually, I only input 1 time "a cute dog" just as above image,  but it call the SD more than 1 time, and  when it created the picture successfully, the process didn't exit, it still call the SD second time and the parameters are not corrected, and the process crashed. 
![image](https://github.com/user-attachments/assets/8c5e95e7-04d7-401e-97f3-e3be12043042)

**Comment by danni-cool** [comment]
Same issue, and more worse, the stalbe diffusion tool started a generate task but with no output image
