### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by janglichao** [langgenius/dify#8319]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

run in my macbookpro.
when I run dock-compose command in docker folder path,
it shows :
WARN[0000] The "CERTBOT_EMAIL" variable is not set. Defaulting to a blank string.
WARN[0000] The "CERTBOT_DOMAIN" variable is not set. Defaulting to a blank string.

### ❌ Actual Behavior

WARN[0000] The "CERTBOT_EMAIL" variable is not set. Defaulting to a blank string.
WARN[0000] The "CERTBOT_DOMAIN" variable is not set. Defaulting to a blank string.

**Comment by crazywoola** [comment]
These are 2 warnings. Once you input something in `.env`, these should be gone.

**Comment by Orange-C01** [comment]
This works, the warning does not affect the restart.
