### ISSUE TITLE
toast says '>' not supported between instances of 'float' and 'NoneType' on knowlege retereval testing

### ISSUE THREAD

**Issue by TaylorHere** [langgenius/dify#8330]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Retrieval testing any database in my account, will reproduce this bug.

**Comment by GabrielBaumerIA** [comment]
I'm having the same issue when retrieving knowledge or testing the retrieval. Also use cloud version.

**Comment by Midasstart** [comment]
Here too, the same error.

**Comment by crazywoola** [comment]
I reproduced this problem in Cloud version.

Please take a look at this issue. :) @JohnJyong

**Comment by TaylorHere** [comment]
another error says when run knowlege retereval testing
`shapes (1536,) and (3072,) not aligned: 1536 (dim 0) != 3072 (dim 0)`
