### ISSUE TITLE
Failed to invoke tool: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by ericksvasc** [langgenius/dify#8333]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![Captura de Tela 2024-09-12 às 18 40 53](https://github.com/user-attachments/assets/4216115d-c706-403a-9a40-8299747a3b92)
![Captura de Tela 2024-09-12 às 18 41 03](https://github.com/user-attachments/assets/70cf4700-6938-4f82-a2a5-a1026982d531)
![Captura de Tela 2024-09-12 às 18 41 27](https://github.com/user-attachments/assets/c4d17bca-6a4d-4f45-93cd-5d8637fecf59)
![Captura de Tela 2024-09-12 às 18 44 02](https://github.com/user-attachments/assets/d1831d91-0dd8-452b-9be8-9b52482e886b)

### ✔️ Expected Behavior

I expected it to run the flow smoothly

### ❌ Actual Behavior

it presents the error: Failed to invoke tool: 'NoneType' object has no attribute 'items'

**Comment by zolgear** [comment]
Duplicated #8330
