### ISSUE TITLE
One of Direct Replies behind Question Classifier is alway exported on the top of regular LLM answer.

### ISSUE THREAD

**Issue by mikegong** [langgenius/dify#8334]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create a Question Classifier with 3 Classes, 2 of them are direct reply and one will go to LLM. Even the Classifier decided the class to LLM but one of the Direct Reply will respone first and then LLM answer will be displayed. If the showed Direct Reply is removed, then the other Direct Reply will be showed first and then LLM answer.

### ✔️ Expected Behavior

LLM answer only instead of mixed answer.

### ❌ Actual Behavior

Direct Reply is always displayed even the class that Question Classifier decided is other one.

**Comment by crazywoola** [comment]
Duplicated, please upgrade to v0.8.1. Fixed in https://github.com/langgenius/dify/pull/8225
