### ISSUE TITLE
The corresponding index.tsx file cannot be found in the docker-web-1 container

### ISSUE THREAD

**Issue by sf9ehf9fe** [langgenius/dify#8337]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use the file "index.tsx" to change the port of the URL of a web page
![Snipaste_2024-09-13_09-02-25](https://github.com/user-attachments/assets/59cba471-bade-4c78-81fd-280aa38e7ead)

### ✔️ Expected Behavior

You need to change the jump port of a URL to 8000, see the picture for the specific location
<img width="1039" alt="Snipaste_2024-09-13_09-05-55" src="https://github.com/user-attachments/assets/38e460df-039d-4b46-9e6b-ebf3b599fcf3">

### ❌ Actual Behavior

The location of this file cannot be found in the container, and the jump port of this URL cannot be modified

**Comment by sf9ehf9fe** [comment]
The first picture looks like this
![Uploading Snipaste_2024-09-13_09-17-03.png…]()

**Comment by crazywoola** [comment]
Things in docker container are packed. You will not be able to see the `index.tsx` file. If you want to change the port please read the docs.

**Comment by sf9ehf9fe** [comment]
> Things in docker container are packed. You will not be able to see the `index.tsx` file. If you want to change the port please read the docs.

It means I change the front-end code, rebuild the image, and then launch the image
