### ISSUE TITLE
An error occurred during credentials validation: Session.request() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by wmcde** [langgenius/dify#8339]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I encountered the following error message when deploying a Text Embedding model using ollama: An error occurred during credentials validation: Session. request() got an unexpected keyword argument 'options'. The previous version has been normal, but this issue occurred when I upgraded to the latest 0.8.0.
![屏幕截图 2024-09-13 093643](https://github.com/user-attachments/assets/baddfb48-d617-4e9e-b32b-6b6f3194a131)

**Comment by crazywoola** [comment]
Please upgrade to v0.8.1 see https://github.com/langgenius/dify/pull/8252 for more details.
