### ISSUE TITLE
Knowledge base hit test failed

### ISSUE THREAD

**Issue by ricky977** [langgenius/dify#8340]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Upgraded from version 0.6.8 to 0.7.3. Since a lot of data from the previous version needed to be migrated, the docker/volumes directory of the previous version was directly replaced with the docker directory of the current 0.7.3 version. Other functions were normal and the data was transferred. However, the hit test failed when searching the knowledge base, and the workflow knowledge search also failed.
<img width="1011" alt="微信图片_20240913095259" src="https://github.com/user-attachments/assets/14d8bc42-1abb-4902-b369-8893929f5113">
后端报错如下：Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/hit_testing.py", line 83, in post
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_44d58b7d_0ae9_47b2_9add_5ce534372b9f_Node" on type "GetObjectsObj". Did you mean "Vector_index_f1b959b7_2e57_44a2_be9d_56c723b385b7_Node", "Vector_index_ce8f0fb7_ca67_4ca8_af44_ec922eed20a4_Node", or "Vector_index_47073f27_289c_41ba_b67d_31dfa94bfbb0_Node"?', 'path': None}]
![后端报错](https://github.com/user-attachments/assets/9a226dd2-15a1-4474-b750-b96786b73843)

### ✔️ Expected Behavior

The retrieval is successful and the hit test result is returned

### ❌ Actual Behavior

werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_44d58b7d_0ae9_47b2_9add_5ce534372b9f_Node" on type "GetObjectsObj". Did you mean "Vector_index_f1b959b7_2e57_44a2_be9d_56c723b385b7_Node", "Vector_index_ce8f0fb7_ca67_4ca8_af44_ec922eed20a4_Node", or "Vector_index_47073f27_289c_41ba_b67d_31dfa94bfbb0_Node"?', 'path': None}]

**Comment by crazywoola** [comment]
Please upgrade to v0.8.1

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/pull/8217

**Comment by ricky977** [comment]
> 请升级到 v0.8.1

请问升级后数据迁移怎么操作
