### ISSUE TITLE
When calling the chatbot api service, the metadata field in the "event": "message_end" block is an empty dictionary when calling the stream return.

### ISSUE THREAD

**Issue by NDBXQ** [langgenius/dify#8341]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/7b95b42c-fc95-4de0-8ec8-c6c1a68eca5a">

### ✔️ Expected Behavior

<img width="552" alt="image" src="https://github.com/user-attachments/assets/1c444d4c-56ab-49fa-9970-afe0a6ad4f61">

### ❌ Actual Behavior

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/d11feee8-ab20-4de2-a636-dbbac5421ef1">

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8264
