### ISSUE TITLE
Can I print a detailed request log？

### ISSUE THREAD

**Issue by liutao-python** [langgenius/dify#8357]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It is hoped that the request log can be printed in the service, including the request view function, request method and other information. When the request ends, printing takes time.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by liutao-python** [comment]
Yes, I know it can be extended, but I would prefer to have these things built into the project, I think it is a basic function of a service

**Comment by crazywoola** [comment]
Please open a issue here https://github.com/langgenius/dify-sandbox instead.
