### ISSUE TITLE
An error "context length exceeded" occurred during the conversation.

### ISSUE THREAD

**Issue by StantonStetler** [langgenius/dify#8360]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.8.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Create agent
Configure knowledge base
Debug dialogue chat on input box page
Error appears at the top of the page
<img width="497" alt="企业微信截图_17262105991870" src="https://github.com/user-attachments/assets/5ac3f6d8-33e6-424c-b8a1-0cb7a7262573">
<img width="308" alt="企业微信截图_17262107076651" src="https://github.com/user-attachments/assets/56097a64-860b-4e77-9b6e-a46c39495358">

### ✔️ Expected Behavior

Normal conversation

### ❌ Actual Behavior

Error occurred and no response

**Comment by crazywoola** [comment]
Try to adjust the max_tokens to a smaller one.

**Comment by StantonStetler** [comment]
> Try to adjust the max_tokens to a smaller one.

The current max_token is the default 512, which is not very large, and in some cases, the length exceeds the limit. May I ask if this is due to the code? If so, which class should be modified?

**Comment by crazywoola** [comment]
Then I think the prompt is too long. \

> Context = prompt + memory(2k) + max_tokens
