### ISSUE TITLE
occurred in <module> import _ssl # if we can't import it, let the error propagate ImportError: libzstd.so.1: cannot open shared object file: No such file or directory error: exit status 255

### ISSUE THREAD

**Issue by chenjin19** [langgenius/dify#8362]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I use httpx to request another interface, I encounter the following error. I have checked that libzstd exists in the Docker environment, and I have also set response = httpx.post(url, headers=headers, timeout=60, json=data, verify=False). What should I do?"

If you need any further assistance or more context regarding how to resolve the issue, feel free to provide additional details about the err

The error message is：

```
10/site-packages/httpx/_multipart.py", line 8, in <module> from ._types import ( File "/usr/local/lib/python3.10/site-packages/httpx/_types.py", line 5, in <module> import ssl File "/usr/local/lib/python3.10/ssl.py", line 99, in <module> import _ssl # if we can't import it, let the error propagate ImportError: libzstd.so.1: cannot open shared object file: No such file or directory "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 12, in <module> from ._auth import Auth, BasicAuth, FunctionAuth File "/usr/local/lib/python3.10/site-packages/httpx/_auth.py", line 12, in <module> from ._models import Cookies, Request, Response File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 11, in <module> from ._content import ByteStream, UnattachedStream, encode_request, encode_response File "/usr/local/lib/python3.10/site-packages/httpx/_content.py", line 17, in <module> from ._multipart import MultipartStream File "/usr/local/lib/python3.10/site-packages/httpx/_multipart.py", line 8, in <module> from ._types import ( File "/usr/local/lib/python3.10/site-packages/httpx/_types.py", line 5, in <module> import ssl File "/usr/local/lib/python3.10/ssl.py", line 99, in <module> import _ssl # if we can't import it, let the error propagate ImportError: libzstd.so.1: cannot open shared object file: No such file or directory error: exit status 255
```

### ✔️ Expected Behavior

I need the function to be able to call the API successfully.
ps:When I downgraded the Python sandbox environment to version 0.2.6, it worked, but version 0.2.7 reports the above error

**Comment by Scenx** [comment]
me too! please

**Comment by Scenx** [comment]
> @chenjin19 Hello! I'm here to help you with bugs, questions, and contributions. Let's work on resolving your issue together.
> 
> The error you're encountering, `ImportError: libzstd.so.1: cannot open shared object file: No such file or directory`, indicates that the `libzstd` library is missing in your Docker environment. This issue seems to be specific to the Python sandbox environment version 0.2.7, as you mentioned it works with version 0.2.6.
> 
> To resolve this issue, you can try the following steps:
> 
> 1. **Install `libzstd` in the Docker Container**:
>    Ensure that `libzstd` is installed in your Docker container. You can do this by adding the installation command to your Dockerfile or running it manually inside the container.
>    ```dockerfile
>    RUN apt-get update && apt-get install -y libzstd1
>    ```
> 2. **Verify the Installation**:
>    After installing `libzstd`, verify that it is correctly installed by running the following command inside the Docker container:
>    ```shell
>    ldconfig -p | grep libzstd
>    ```
> 3. **Rebuild the Docker Image**:
>    If you modified the Dockerfile, rebuild the Docker image and restart the container.
>    ```shell
>    docker-compose build
>    docker-compose up -d
>    ```
> 4. **Check for Compatibility Issues**:
>    Since the issue does not occur in version 0.2.6, there might be compatibility issues introduced in version 0.2.7. Review the changes between these versions to identify any potential causes.
> 
> If the issue persists, you may need to further investigate the changes between the Python sandbox environment versions 0.2.6 and 0.2.7 to identify any additional dependencies or modifications that could be causing the problem. Unfortunately, specific details about the changes between these versions are not available in the provided information.
> 
> For more detailed troubleshooting, you might want to check the Dify repository or related documentation for any updates or known issues regarding this specific problem.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

The robot is wrong; this has already been installed in the container, and it's useless.

**Comment by crazywoola** [comment]
See https://www.stats.gov.cn/sj/ndsj/2023/indexch.htm
