### ISSUE TITLE
My Dify conversation page cannot render successfully LaTex formula

### ISSUE THREAD

**Issue by BryceWG** [langgenius/dify#8379]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Recently, I found that my Dify conversation page cannot render latex formulas properly, but markdown format can be rendered normally. I am not sure if I changed any settings that caused this issue, and there are no clear errors in the docker logs. Below is the display situation of latex in my current conversation:
![Clip_2024-09-13_19-39-00](https://github.com/user-attachments/assets/d5655bea-0859-42b6-af3e-b389b363b78e)
I have been waiting for several versions to fix this issue, but I have not found any users with the same situation, and there is no clear relevant setting found in the env configuration. 
I should not have modified any files other than .env and nginx configuration.

### ✔️ Expected Behavior

In the conversation page, the latex formula can be rendered correctly

### ❌ Actual Behavior

The latex formula in the dialogue page is not rendered, but the markdown rendering seems fine:
![Clip_2024-09-13_19-49-21](https://github.com/user-attachments/assets/825d2e24-9a58-4973-9647-f1dc926c7713)

**Comment by BryceWG** [comment]
> The issue with LaTeX formulas not rendering on your Dify conversation page might be related to the dependencies responsible for LaTeX rendering. Dify uses the following libraries for this purpose:
> 
> * `katex`: "^0.16.10"
> * `rehype-katex`: "^6.0.2"
> * `remark-math`: "^5.1.1" [[1]](https://github.com/langgenius/dify/blob/main/web/package.json).
> 
> Here are a few steps you can take to troubleshoot and potentially resolve the issue:
> 
> 1. **Check Dependencies**: Ensure that these dependencies are correctly installed in your environment. You can verify this by checking your `package.json` file and running `npm install` or `yarn install` to reinstall the dependencies.
> 2. **Configuration**: Verify if there are any specific configurations required for these libraries in your project. Sometimes, additional configuration might be needed to enable LaTeX rendering.
> 3. **Inspect Logs**: Although you mentioned there are no clear errors in the Docker logs, it might be helpful to increase the logging verbosity or check the browser console for any client-side errors related to LaTeX rendering.
> 4. **Update Dify**: Ensure you are using the latest version of Dify. Sometimes, issues are resolved in newer releases.
> 5. **Custom Modifications**: Since you mentioned modifying `.env` and `nginx` configurations, double-check these changes to ensure they do not interfere with the rendering process.
> 
> If the issue persists after these steps, it might be helpful to provide more detailed logs or error messages to further diagnose the problem.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I found that my node.js version is 16 and my os is centos 7. It's hard for me to upgrade node.js to 18

**Comment by kevinl1210** [comment]
I encountered similar issues and found the workaround.
For docker deployment, you need to connect to the web docker container, update the package.json and then restart the node js server.
1. docker exec -it docker-web-1 sh

2. vi package.json
Add the following libraries to devDependencies:
"katex": "^0.16.10",
"rehype-katex": "^6.0.2",
"remark-math": "^5.1.1"

3. node /usr/local/bin/pm2 restart ./pm2.json


Then you can see the latex rendered correctly.
![image](https://github.com/user-attachments/assets/4d5d9932-f125-4462-ba3a-d84f2d1d618d)

**Comment by BryceWG** [comment]
My server's /use/local/bin folder does not contain the pm2 file, so I can't restart the node service using this command. Additionally, I noticed that these three libraries are also listed in the dependencies section of the package.json file. I'm not sure if they match your file content.

**Comment by jindanny** [comment]
Same issue, unable to render LaTeX formulas correctly on Dify's conversation page
![image](https://github.com/user-attachments/assets/35e5e1e4-e82f-497d-ba00-61b28d8c9bbb)

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/9206 for updates
