### ISSUE TITLE
Severe problem in OpenAI model (gpt-4o)

### ISSUE THREAD

**Issue by QichangZheng** [langgenius/dify#8398]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have just switched from FastGPT to Dify. I developed an application and use API to request it. I configured OpenAI and Ollama models. When I use Ollama local models, my OpenAI tokens were consumed! I am sure that I published the model and updated the configuration. In this case, I disabled my OpenAI apikey, and I can still use the application. Moreover, in development, for OpenAI models, I only used gpt-4o-mini, and never used gpt-4o, but it showed on the OpenAI offical API board that I consumed gpt-4o tokens instead of gpt-4o-mini.

**Comment by crazywoola** [comment]
<img width="407" alt="image" src="https://github.com/user-attachments/assets/a2edf315-d52e-4547-90d0-1a1476f83a5d">

**Comment by QichangZheng** [comment]
> <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/100913391/367477445-a2edf315-d52e-4547-90d0-1a1476f83a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODY5ODcsIm5iZiI6MTcyNjI4NjY4NywicGF0aCI6Ii8xMDA5MTMzOTEvMzY3NDc3NDQ1LWEyZWRmMzE1LWQ1MmUtNDU0Ny05MGQwLTFhMTQ3NmY4M2E1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwNDA0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGU4NmVmNTkzMTBhOTBmMTk4MjhkMmEyY2ViYzhmZTBjNjg4ZWMwNGQzMzI0NjJhZTk5YTBiZThiODhlNTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VTSEQLKxDuEKyickb7Otxqqlwzi0-YU8dLpQ0HpXAmc">

But when I disabled my OpenAI apikey, my Dify application still works well. 
Here is my application structure:
![image](https://github.com/user-attachments/assets/222c84d6-b851-4a58-9ccb-f15c85ebaf16)
