### ISSUE TITLE
The table 'dataset_keyword_tables' is too large, resulting in insufficient server storage

### ISSUE THREAD

**Issue by starweavingdream** [langgenius/dify#8399]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I am using a PG database and there is a table named 'dataset_keyword_tables' in the database with a large amount of data; Through testing, uploading a file of about 1M, the size increment of this table can reach 300M, which is strange. Now my table has 300 GB, and I want to know what specific use this table has? Can I clean it up? Otherwise, as more and more knowledge base documents are uploaded, this table will become larger and larger.

**Comment by Scallions** [comment]
Same problem. Did you find any solution? I found that this table is only used by keyword search. When indexing document, this table will slow down the process.

**Comment by starweavingdream** [comment]
@Scallions I found the answer in other issues. They said that this table is cleaned up regularly, that is, data can be deleted manually. After I cleared the data, there were no particularly obvious problems. If you want to adopt my method, I suggest you back up your data first.

**Comment by glacierck** [comment]
@starweavingdream I need you! I'm going nuts!
![image](https://github.com/user-attachments/assets/c4b32d43-9da0-425c-b0cc-bc999cac2b6e)

**Comment by luckylhb90** [comment]
same problems. ....
so difficult.....
The system has a lot to change.....

**Comment by glacierck** [comment]
This is my solution, disable the data of this table！

https://github.com/langgenius/dify/issues/8513#issuecomment-2606650048

**Comment by gemchen** [comment]
> [@Scallions](https://github.com/Scallions) I tried the solution given by the robot, and there were no particularly obvious problems after I cleared the data. If you want to try my method, I suggest you back up your data first.

Did it work? 好使吗？

**Comment by mabywyg** [comment]
vacuum full verbose dataset_keyword_tables 我测试一下好像是物理地址没有删除该内容

**Comment by mabywyg** [comment]
vacuum full verbose dataset_keyword_tables  可以删除，但是会不会产生影响不确定，如果没有办法可以使用这个
