### ISSUE TITLE
When I need to use tools, llm use two tools simultaneously, and then an error occurs.

### ISSUE THREAD

**Issue by YYyp99** [langgenius/dify#8400]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I use the search tool and the web scraping tool, it uses them together, calling both tools simultaneously. Afterwards, the LLM throws an error.   [bedrock] Error: ValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.
![image](https://github.com/user-attachments/assets/6e37ea8f-b69d-45e4-9e9c-ddc92d4ecb4f)
![image](https://github.com/user-attachments/assets/ac049618-cc19-4d50-a13b-a8c02170a999)

**Comment by crazywoola** [comment]
Claude does not support system role.  Try to switch to another one.

**Comment by YYyp99** [comment]
> Claude does not support system role. Try to switch to another one.

I'm using Claude from Bedrock, and this issue is caused by calling two different tools simultaneously, right? When I used it before, writing it this way didn't cause any problems.

**Comment by crazywoola** [comment]
We have a PR 2 days ago. https://github.com/langgenius/dify/pull/8317 maybe you can check with @ybalbert001

**Comment by YYyp99** [comment]
> 我们两天前有一个 PR。#8317也许你可以查看一下@ybalbert001

I'm not using a Bedrock cross-region inference model.
![image](https://github.com/user-attachments/assets/13909955-5557-4001-b735-45b48cc82bfa)
 I just tried it on the cloud version as well, and it also experienced this issue where calling two tools simultaneously results in an error.

**Comment by YYyp99** [comment]
> We have a PR 2 days ago. #8317 maybe you can check with @ybalbert001

I'm not using a Bedrock cross-region inference model.
![image](https://github.com/user-attachments/assets/4cd23a66-b2ff-4585-bc72-bd7b38806021)
 I just tried it on the cloud version as well, and it also experienced this issue where calling two tools simultaneously results in an error.

**Comment by ybalbert001** [comment]
@YYyp99  how to reproduce you problem? share DSL?

**Comment by YYyp99** [comment]
> @YYyp99 how to reproduce you problem? share DSL? This issue seems have no relationship with Bedrock Cross Region Inference

![image](https://github.com/user-attachments/assets/1a3cd8a9-faea-4ddc-b72f-93cfc93b6bc5)
GoogleSearchPoint is my custom Google search tool, while the other two are official tools. When I ask a question, both tools are used together, causing an error.
![image](https://github.com/user-attachments/assets/d9f8e0fc-d26b-42fd-86ab-841b37e190be)
