### ISSUE TITLE
error when create embedding model: An error occurred during credentials validation: Session.request() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by victorming666** [langgenius/dify#8404]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

settings  -> ollama -> create model -> embedding model：
ollama + smartcreation/bge-large-zh-v1.5:latest
![image](https://github.com/user-attachments/assets/56744fe0-b448-4088-a350-613f276c12ce)

### ✔️ Expected Behavior

create the embedding model hosted by ollama

### ❌ Actual Behavior

An error occurred during credentials validation: Session.request() got an unexpected keyword argument 'options'

**Comment by crazywoola** [comment]
Please upgrade to v0.8.2
