### ISSUE TITLE
How to obtain uploaded images in the workflow?

### ISSUE THREAD

**Issue by nilgpt2024** [langgenius/dify#8406]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

How to obtain uploaded images in the workflow? For example, I have enabled the ability to upload images, but I am unable to retrieve the variable 'sys. files' in any node.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by nilgpt2024** [comment]
I have enabled the ability to upload images, but I am unable to retrieve the variable 'sys. files' in any node.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/5346

**Comment by dyan1992** [comment]
<img width="697" alt="image" src="https://github.com/user-attachments/assets/7fadd601-bf7a-41af-83ae-e02c0149da0e">
i want to use api to upload files but i got an error like this
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/4e2f5767-7841-436b-a915-5c556ffa0b5a">
