### ISSUE TITLE
Enhancing the management of datasets and documents

### ISSUE THREAD

**Issue by yuhaowin** [langgenius/dify#8415]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We need to manage multiple documents in bulk, such as deleting outdated documents in batches. It should allow selecting multiple files for management at the same time.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yawen-1010** [comment]
Thank you for your request. This is a valid and reasonable suggestion, and it will be incorporated into future product planning.
