### ISSUE TITLE
Request to add a timed run feature to the workflow.

### ISSUE THREAD

**Issue by AAEE86** [langgenius/dify#8417]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I created an automated check-in workflow, but because it didn't run regularly, I had to run it manually.

In addition to check-in, there are many functions that can be used to run regularly, such as sending messages, weather queries, and so on.

This function can make the usage scenarios of Dify more diverse.  

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by AAEE86** [comment]
@crazywoola Is this feature planned?

**Comment by Yevanchen** [comment]
> @crazywoola Is this feature planned? 这个功能有计划吗？

We are evaluating this feature

**Comment by crazywoola** [comment]
See this https://github.com/langgenius/dify/issues/9168 for updates

**Comment by leochen-g** [comment]
You can use this project to make schedule. https://github.com/leochen-g/dify-schedule
