### ISSUE TITLE
Why can the variable aggregator only output the result of the first variable?

### ISSUE THREAD

**Issue by seasoncool** [langgenius/dify#8420]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am using a parallel approach to have each role analyze the product I provided. 

I want to combine the analysis results from the large models and output them together uniformly.

Why is it that each time I can only see the output of the first variable at the endpoint?

![Variable Aggregator](https://github.com/user-attachments/assets/038a1e87-329a-4d74-9669-c2507ab7ea7d)

### ✔️ Expected Behavior

I hope the analysis results from each large model can be organized together through a variable aggregator.

### ❌ Actual Behavior

only one output

**Comment by crazywoola** [comment]
Please upgrade to v0.8.3. We have fixed several issues related to the output.

**Comment by seasoncool** [comment]
@crazywoola 

Thank you for your quick response. I see that currently only version 0.8.2 is available for download. 
Do you mean we need to wait until version 0.8.3 is released?

**Comment by crazywoola** [comment]
Actually I reproduced this problem, I need to take a deep look at the code.

**Comment by crazywoola** [comment]
A workaround might be 

![QQ_1726299330026](https://github.com/user-attachments/assets/3e51cb7f-6e98-4996-9210-dbaa6a80f385)
![QQ_1726299369598](https://github.com/user-attachments/assets/8b3ecdb9-7fbb-4bf2-8500-228ebc308053)

**Comment by AAEE86** [comment]
> @crazywoola
根据测试是变量聚合器的问题，他只会输出变量赋值中的第一个LLM内容

**Comment by AAEE86** [comment]
聚合分组并没有作用

**Comment by crazywoola** [comment]
> 将多路分支的变量聚合为一个变量，以实现下游节点统一配置。

> 变量聚合节点（原变量赋值节点）是工作流程中的一个关键节点，它负责整合不同分支的输出结果，确保无论哪个分支被执行，其结果都能通过一个统一的变量来引用和访问。这在多分支的情况下非常有用，可将不同分支下相同作用的变量映射为一个输出变量，避免下游节点重复定义。

I checked with our team, this seems to be an expected behavior, actually it equals to 'choose 1 from n'.   @seasoncool @AAEE86

**Comment by AAEE86** [comment]
明白了。 要想都输出。必须将每个LLM都放到一个分组并输出。

**Comment by crazywoola** [comment]
> 明白了。 要想都输出。必须将每个LLM都放到一个分组并输出。
No need to do this, actually an answer node is enough.

`变量聚合` I think we will change the name in the near future.

**Comment by AAEE86** [comment]
Ok. thanks.@crazywoola

**Comment by seasoncool** [comment]
> > 将多路分支的变量聚合为一个变量，以实现下游节点统一配置。
> 
> > 变量聚合节点（原变量赋值节点）是工作流程中的一个关键节点，它负责整合不同分支的输出结果，确保无论哪个分支被执行，其结果都能通过一个统一的变量来引用和访问。这在多分支的情况下非常有用，可将不同分支下相同作用的变量映射为一个输出变量，避免下游节点重复定义。
> 
> I checked with our team, this seems to be an expected behavior, actually it equals to 'choose 1 from n'.   @seasoncool @AAEE86 

感谢，还是不太明白怎么使用？还有别的办法能将多个的大模型推理的结果合并一起吗？

**Comment by crazywoola** [comment]
![QQ_1726321654580](https://github.com/user-attachments/assets/06b937c9-52cd-401a-8622-147ceebc7d80)

**Comment by AAEE86** [comment]
In fact, you can create three variables directly in END to output the result of the LLM.

**Comment by seasoncool** [comment]
> In fact, you can create three variables directly in END to output the result of the LLM.

I tried the method you suggested, outputting three variables at the endpoint, but in the end, only the value of the first one is displayed.

**Comment by seasoncool** [comment]
> ![QQ_1726321654580](https://private-user-images.githubusercontent.com/100913391/367518865-06b937c9-52cd-401a-8622-147ceebc7d80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjQwMzcsIm5iZiI6MTcyNjMyMzczNywicGF0aCI6Ii8xMDA5MTMzOTEvMzY3NTE4ODY1LTA2YjkzN2M5LTUyY2QtNDAxYS04NjIyLTE0N2NlZWJjN2Q4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxNDIyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzc4ODhiNjQyMTBmN2NkYWRkOTZhNzc0ZmE4N2YzYWFkZjY1YTM3ZWRiYjczZTI3MzhkMDAyOTUwMjkxMzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aEVnFxgkMLy7jwmzdXb1n8M4JSPVr_x3txVEzsRFueg)

Could you show how the code inside the template conversion is written? I would like to learn from it. Thank you.

**Comment by AAEE86** [comment]
![屏幕截图 2024-09-14 225134](https://github.com/user-attachments/assets/41bebe48-92e8-4cf4-9270-100cdc9109a0)
Are you sure your settings are correct?

**Comment by AAEE86** [comment]
> > ![QQ_1726321654580](https://private-user-images.githubusercontent.com/100913391/367518865-06b937c9-52cd-401a-8622-147ceebc7d80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjQwMzcsIm5iZiI6MTcyNjMyMzczNywicGF0aCI6Ii8xMDA5MTMzOTEvMzY3NTE4ODY1LTA2YjkzN2M5LTUyY2QtNDAxYS04NjIyLTE0N2NlZWJjN2Q4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxNDIyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzc4ODhiNjQyMTBmN2NkYWRkOTZhNzc0ZmE4N2YzYWFkZjY1YTM3ZWRiYjczZTI3MzhkMDAyOTUwMjkxMzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aEVnFxgkMLy7jwmzdXb1n8M4JSPVr_x3txVEzsRFueg)
> 
> Could you show how the code inside the template conversion is written? I would like to learn from it. Thank you.

![屏幕截图 2024-09-14 225501](https://github.com/user-attachments/assets/ad4439f5-3b6d-4a25-b2ca-73f200e6a987)

A simple example. You can view the official documentation to understand Jinja template syntax.

**Comment by seasoncool** [comment]
thanks a lot ... I will learn from that.

**Comment by seasoncool** [comment]
> ![屏幕截图 2024-09-14 225134](https://private-user-images.githubusercontent.com/33052466/367522950-41bebe48-92e8-4cf4-9270-100cdc9109a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjU4OTIsIm5iZiI6MTcyNjMyNTU5MiwicGF0aCI6Ii8zMzA1MjQ2Ni8zNjc1MjI5NTAtNDFiZWJlNDgtOTJlOC00Y2Y0LTkyNzAtMTAwY2RjOTEwOWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE0NTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMDk2YjJkOTdkM2UwYTI2MjE1ZTFiZDJkYzZkYzA0OTQ3MDY1MTI4YWVlMDlhMDZkNGM5MDc3ZTk4OTFlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ftMow9YJZbFatlpHHwaWmvX_IrP61lyYC3LzAz1Lj3E) Are you sure your settings are correct?

You're right. All three of my output variables are named "text," so the last one is likely overwriting the previous results, which makes it look like there's only one result. Thank you for the image that helped me understand.
