### ISSUE TITLE
Render HTML tag in conversation of LLM output

### ISSUE THREAD

**Issue by sfyumi** [langgenius/dify#8431]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Claude 3.5 sonnet is good at coding, and it can generate very good svg code. So people can use it to generate image.
But dify can only display plain svg text.
Do you have a plan to support html tag rendering?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/pull/8387

**Comment by sfyumi** [comment]
@crazywoola Thank you so much for your work. It really helped me.
