### ISSUE TITLE
 How can I add the response_format attribute setting for the LLM node when making prompt words?

### ISSUE THREAD

**Issue by zzkzzk1984** [langgenius/dify#8434]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, it is very unstable if LLM outputs JSON format simply based on prompt words.
![image](https://github.com/user-attachments/assets/378e5690-e7ad-476f-8f75-80f1a756c5fb)
I hope to add the ability to set the response_format parameter
![a7131ede3318b7c7817c413da7793af](https://github.com/user-attachments/assets/a44bdbd3-d366-4c17-a524-28f31856af65)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Only limited models support this feature.

https://github.com/langgenius/dify/blob/153807f243952f3a5fd50e9969c4826080d0fbd2/api/core/model_runtime/model_providers/openai/llm/gpt-4o-mini-2024-07-18.yaml#L41-L42

**Comment by zzkzzk1984** [comment]
I want to add this option to localai, how should I do it?
