### ISSUE TITLE
The published application wants to be able to change the language type

### ISSUE THREAD

**Issue by Alex-lsky** [langgenius/dify#8439]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

We utilize Dify to develop applications for users across multiple countries; however, the language setting logic for publishing these applications defaults to the current language of Dify and remains unchangeable. Typically, we create agents or workflows under the system's default language setting of Simplified Chinese before making them accessible to global users, with buttons labeled '开始对话' and '新对话' After changing Dify's default language to English and updating the workflow, it still defaults to Simplified Chinese, which cannot be modified. We hope this feature can be enhanced in future updates.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
![QQ_1726308135606](https://github.com/user-attachments/assets/41281bc7-a6d9-4d4a-8d59-b41103f3e3c8)
