### ISSUE TITLE
Using a parallel connection to connect two code executors after LLM can cause problems

### ISSUE THREAD

**Issue by massif-01** [langgenius/dify#8453]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I use LLM to write outline, output json, and use two code executors in parallel after LLM to separately extract different contents in json, Dify reports error as follows: Node beginning extraction related parallel not found or incorrectly connected to multiple parallel branches. After testing, there is no problem with the code, because Dify will not report errors when not using parallel mode. And in 0.8.1, such an orchestration design does not report an error and can run normally.
<img width="486" alt="截屏2024-09-15 02 59 27" src="https://github.com/user-attachments/assets/8807a15e-67b5-4e27-bdb2-8e75de34ca0f">
<img width="422" alt="截屏2024-09-15 02 59 38" src="https://github.com/user-attachments/assets/8e689dcb-a1f3-4c8f-994f-10c91f8efd51">

**Comment by crazywoola** [comment]
We fixed in latest branch. See Cloud.

Link #8378 #8440

![QQ_1726363133641](https://github.com/user-attachments/assets/00cabf87-a50e-408a-a942-589514cec507)
