### ISSUE TITLE
How to remove the scrollbar? It doen't look good.

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8454]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

I want to disable the scrollbar, but still be able to scroll. 
How to achieve this? This doesn't look good.
<img width="897" alt="image" src="https://github.com/user-attachments/assets/4c0eb45a-599a-412d-b88f-cd2b0799d4ff">

**Comment by taowang1993** [comment]
I am referring to the vertical scrollbar

**Comment by crazywoola** [comment]
Can you paste a full screenshot.

**Comment by taowang1993** [comment]
> Can you paste a full screenshot.

This is the iframe embed chatbot 

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/ac0c4b3b-dac1-4e27-8623-0a3eb0822803">
