### ISSUE TITLE
chat-messages API is taking more time compared to test run in dify

### ISSUE THREAD

**Issue by AugNSo** [langgenius/dify#8455]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Build a workflow that involves a LLM node.
Access the workflow via chat-message API. 
[So far we observe this problem regardless of which LLM used or response mode]

### ✔️ Expected Behavior

The total response time is expected to be about the same to how much preview run takes in dify.

### ❌ Actual Behavior

The total response time can be up to two times of how much preview run takes. 
This problem is very obvious when the LLM is given a long prompt such as performing RAG task.

**Comment by yg1031** [comment]
> Try set `auto_generate_name ` to false.

Not working, the chat_messages API takes more than 5 seconds before the first token come when conversation_id is set.

**Comment by AugNSo** [comment]
> > Try set `auto_generate_name ` to false.
> 
> Not working, the `chat_messages` API takes more than 5 seconds before the first token come when `conversation_id` is set. However, if `conversation_id` is set to empty, it takes less than 2 seconds, but without chat history. Moreover, `auto_generate_name` does not affect first token delay. Dify version is 1.1.3, deployed on docker.

I would suggest that you open a separate issue. You are replying to an issue that was opened a long time ago, was properly addressed at the time, and has a different cause. Please make it easier for developers to track issues.
