### ISSUE TITLE
dify升级3.13后，无法绑定原微软的model，是否需要把azure的api-version可支持配置

### ISSUE THREAD

**Issue by MartinGuo** [langgenius/dify#846]
<img width="1273" alt="image" src="https://github.com/langgenius/dify/assets/9604808/b588eeb7-9bf2-423b-8c43-76e7fd831a9a">
<img width="1159" alt="image" src="https://github.com/langgenius/dify/assets/9604808/637d0098-fde8-4bad-a12b-f7fe0cd7c36a">

怀疑和 api-version版本有关，微软部署的model和api-version有关系
<img width="707" alt="image" src="https://github.com/langgenius/dify/assets/9604808/57f225ff-813f-4d55-a009-907c5fd69986">

**Comment by takatost** [comment]
In theory, this api-version should not be related to the deployment. Can you take a screenshot of your Azure OpenAI deployment list page?

**Comment by MartinGuo** [comment]
> 

![image](https://github.com/langgenius/dify/assets/9604808/41229559-ef2c-4171-83fa-9faf4bc55aa7)
微软后台的截图如下。

dify绑定时截图
<img width="693" alt="image" src="https://github.com/langgenius/dify/assets/9604808/f6da743b-d2b3-4e9d-97c9-f5a498761673">

**Comment by lingfengchencn** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/9604808/260642578-41229559-ef2c-4171-83fa-9faf4bc55aa7.png) 微软后台的截图如下。
> 
> dify绑定时截图 <img alt="image" width="693" src="https://user-images.githubusercontent.com/9604808/260642914-f6da743b-d2b3-4e9d-97c9-f5a498761673.png">

确认一下你的 `deployment` , 你输入的是*dddd* ，那么在Azure openai里面也是 *dddd*

**Comment by MartinGuo** [comment]
原来部署名称是需要和微软后台一致啊，我以为只是dify这快的一个标识。🙏，那现在已经配置部署上了

**Comment by takatost** [comment]
> 原来部署名称是需要和微软后台一致啊，我以为只是dify这快的一个标识。🙏，那现在已经配置部署上了

exactly
