### ISSUE TITLE
support Azure tts models (not openai tts)

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8464]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Azure has really cheap tts models.
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/rest-text-to-speech?tabs=streaming
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/adb0f749-d8b0-4ffd-9b56-fad6ba6efa3c">

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
![QQ_1729246884253](https://github.com/user-attachments/assets/22d9c976-33d6-4e16-9ea2-9ea3d18eea64)

**Comment by taowang1993** [comment]
> You mean Azure AI Studio

yes azure tts models. I wil try to add it in a pr.
