### ISSUE TITLE
Can't I turn on polling for model vendors in Community Edition? No introduction to this was found, and version 0.8.2 could not be opened.

### ISSUE THREAD

**Issue by itq5** [langgenius/dify#8466]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/bd22ed94-ace6-4def-b4d9-93aa72bc46e7)
![image](https://github.com/user-attachments/assets/cdeb2406-d15c-496e-8ee6-0f3632875c51)

**Comment by crazywoola** [comment]
https://docs.dify.ai/guides/model-configuration/load-balancing

> Model load balancing is a paid feature. You can enable it by [subscribing to SaaS paid services](https://docs.dify.ai/getting-started/cloud#subscription-plan) or purchasing the enterprise edition.
