### ISSUE TITLE
Persian/farsi translation for README.md

### ISSUE THREAD

**Issue by hos715** [langgenius/dify#8467]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I would like to contribute by translating the README file into Persian (Farsi). The translation would make the project more accessible to Persian-speaking users, allowing them to better understand the purpose and usage of the project.

### 2. Additional context or comments

I plan to create a separate file named `README_FA.md` for the Persian translation, which can be linked in the main README file if needed.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Thanks, that would be great :) Feel free to contribute.

**Comment by hos715** [comment]
https://github.com/langgenius/dify/issues/8467
