### ISSUE TITLE
FRONT-END INTERFACE BUG

### ISSUE THREAD

**Issue by Pnut-GGG** [langgenius/dify#847]
When clicking on settings, the set interface will fill the entire screen, making it impossible to click on the close button and main menu (explore, build applications, plugins, datasets)

Dify version: Self Host v3.13

## Steps To Reproduce

1.Open Settings
2.Unable to close settings

## The current behavior
Normally close the settings and click on the main menu

## The expected behavior
Unable to close the settings menu, only the page can be refreshed

**Comment by zxhlyh** [comment]
fixed: https://github.com/langgenius/dify/pull/849
