### ISSUE TITLE
Please support rerank model from infinity

### ISSUE THREAD

**Issue by shizidushu** [langgenius/dify#8475]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to use rerank model that deployed with infinity (https://github.com/michaelfeil/infinity).

### 2. Additional context or comments

Here is an example of how to send request to infinity rerank model:

```
curl -X 'POST' \
  'http://localhost:7997/rerank' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "like",
  "documents": [
    "like", "love", "hate"
  ],
  "return_documents": false,
  "model": "BAAI/bge-reranker-v2-m3"
}'
```

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by michaelfeil** [comment]
I second this. Potentially could be done best with a new moded that is similar to text-embeddings-inference.
