### ISSUE TITLE
After dify is started for the first time, the localhost/install page keeps spinning in circles,and error tip:Internal Server Error

### ISSUE THREAD

**Issue by zjzkiss** [langgenius/dify#8481]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

git clone main

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Follow the following document to install and start:https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/docker-compose
2. when I enter local/install, I cannot set up an administrator account and it keeps spinning.and get error:Internal Server Error
![无标题](https://github.com/user-attachments/assets/9def9bea-c732-4033-8d17-edb85f57f847)
3.[postgres]DB is not starting,docker logs:
![屏幕截图 2024-09-16 135818](https://github.com/user-attachments/assets/b92e8e5c-9f5d-42cc-8a37-bee1bc13c4f8)

### ✔️ Expected Behavior

how to fix it?

**Comment by crazychengmm** [comment]
How to initdb? Would you describe initdb for more detail
