### ISSUE TITLE
Make chat logs available for download

### ISSUE THREAD

**Issue by yusuke-ten** [langgenius/dify#8492]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I would like to be able to download logs on the log and announce screen.
It would also be nice to be able to use the following features
- Filter function
- Download in csv and json

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by FrancisVarga** [comment]
You can use this api (found it over inspect and then request):
```console/api/apps/1b0856bf-46aa-4ee1-90cc-bf53db65d5f7/chat-conversations?page=1&limit=10&start=2024-09-10%2000%3A00&end=2024-09-17%2023%3A59&sort_by=-created_at&annotation_status=all``

In the return the id attribute is the conversation id
You can fetch the conversation via:
```console/api/apps/1b0856bf-46aa-4ee1-90cc-bf53db65d5f7/chat-messages?conversation_id=c3d6d8a4-9661-42dc-b441-db68e12a05fe&limit=10```

Apps Id:
![image](https://github.com/user-attachments/assets/cd4f127b-06d0-49b5-9fc0-1a8aa268e358)

With this u can build and workflow to get the data.

**Comment by emerson-proenca** [comment]
So, as of 07/2025 is it possible to download Logs in Dify? How did you do it @yusuke-ten
