### ISSUE TITLE
本地部署0.3.13版本后，登录不了，设置管理员提示403

### ISSUE THREAD

**Issue by syhleo** [langgenius/dify#850]
installer界面报错
部署成功之后，在注册管理员账户时日志返回 "POST /console/api/setup HTTP/1.1" 403 -错误
![image](https://github.com/langgenius/dify/assets/26354748/9cfe8144-84ad-48ac-94dd-1a1891a3d16c)

## The current behavior
# CORS configuration
WEB_API_CORS_ALLOW_ORIGINS=*
CONSOLE_CORS_ALLOW_ORIGINS=*

# Cookie configuration
COOKIE_HTTPONLY=true
COOKIE_SAMESITE=Lax
COOKIE_SECURE=false
我在.env文件中是上面这样配置的

**Comment by syhleo** [comment]
后来我手动清空数据库账号信息后，提示“RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.”，请问这个如何解决

**Comment by kowinner123** [comment]
如果是docker部署的话，
1.  docker compose down -v ,执行前先确保备份了volumes目录。
2.  docker compose up -d
3.  看看问题是否解决，应该是volumes目录的权限不对应的问题。
