### ISSUE TITLE
How to count the number of messages in an app, not the number of sessions

### ISSUE THREAD

**Issue by liduang** [langgenius/dify#8507]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

At present, the monitoring only has statistics on the number of sessions
![image](https://github.com/user-attachments/assets/847cf0f9-e1c7-4e36-a0ab-84c7dedd4cb9)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You can use the raw sql to count things in the database.
