### ISSUE TITLE
Knowledge base keyword storage design issues

### ISSUE THREAD

**Issue by yunfeng13** [langgenius/dify#8513]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![1726637080635](https://github.com/user-attachments/assets/8f4f7019-d51a-402c-b8de-17f02514611a)
Every time a new document is uploaded to the knowledge base, the keyword_table field will be fully updated, resulting in low efficiency, and the field data will be very large, resulting in errors and read and write congestion.

### ✔️ Expected Behavior

Is this the design or are we discussing solutions?

### ❌ Actual Behavior

A large number of files in a single knowledge base will cause blockage of modifications to the knowledge base and new embedded files, resulting in errors.

**Comment by glacierck** [comment]
@Yawen-1010 Is there any new progress?
The storage size of a single record in this table is almost 500g, and I only uploaded a 2GB document.

**Comment by glacierck** [comment]
This is my solution, disable the data of this table！
`
CREATE OR REPLACE FUNCTION delete_on_insert()
RETURNS TRIGGER AS $$
BEGIN
    -- 删除新插入的记录
    DELETE FROM dataset_keyword_tables WHERE id = NEW.id;
    -- 返回NULL，表示触发器已成功处理事件，不需要进一步处理
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER before_insert_delete
BEFORE INSERT ON dataset_keyword_tables
FOR EACH ROW
EXECUTE FUNCTION delete_on_insert();


SELECT tgname AS trigger_name,
       pg_get_triggerdef(oid) AS trigger_definition
FROM pg_trigger
WHERE tgrelid = 'dataset_keyword_tables'::regclass;
`
