### ISSUE TITLE
Currently, single-document dialogue is not achievable. It is recommended to add a workflow node and API interface that can enable single-document RAG (Retrieval-Augmented Generation) responses based on the document selected by the user.

### ISSUE THREAD

**Issue by Clint-chan** [langgenius/dify#8524]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, single-document dialogue is not achievable. It is recommended to add a workflow node and API interface that can enable single-document RAG (Retrieval-Augmented Generation) responses based on the document selected by the user.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by VincePotato** [comment]
Thank you for the suggestion, this feature in on our roadmap.
