### ISSUE TITLE
memory windows size params missing in basic chat app

### ISSUE THREAD

**Issue by nadirvishun** [langgenius/dify#8526]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I create a basic chat application, due to the lack of a place to configure the memory windows size, the default size of 500 is used, which results in exceeding the total token limit of LLMS after multiple conversations.
But in chatflow app, in LLMS node, then there is a parameter configuration for the memory windows size: 
![image](https://github.com/user-attachments/assets/4eb25351-cd87-44fe-8044-a4f504f58c72)
Can the parameter to configure the memory windows size also be added to the basic app?

### 2. Additional context or comments

None

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by gravity2013** [comment]
I also strongly need this feature.
