### ISSUE TITLE
Why doesn't the output of the workflow orchestration API include metadata like the Agent does

### ISSUE THREAD

**Issue by Clint-chan** [langgenius/dify#8530]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Why doesn't the output of the workflow orchestration API include metadata like the Agent does:
metadata (object)
retriever_resources (array[RetrieverResource]) A list of referenced and attributed segments
This retriever_resources is very important for RAG (Retrieval-Augmented Generation) applications, as users need to know which documents were referenced to answer their questions.
![image](https://github.com/user-attachments/assets/eeff293f-0bf6-4d5d-91bb-c42f61d2f605)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See linked pr for updates.
