### ISSUE TITLE
If Node Breaks Workflow or ChatFlow

### ISSUE THREAD

**Issue by FrancisVarga** [langgenius/dify#8534]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After clicking to if node it displayed this:
![image](https://github.com/user-attachments/assets/44dd2270-c451-443c-b47e-81391214614e)

How to replicate:
- create new app form template
- use template: Personalized Memory Assistant
- click on the if node

### ✔️ Expected Behavior

Shouldnt Break entire App

### ❌ Actual Behavior

Breaks entire app

**Comment by crazywoola** [comment]
This is resolved in v0.8.3
