### ISSUE TITLE
Dify with OIlama keeps restarting

### ISSUE THREAD

**Issue by dougpiv** [langgenius/dify#8536]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am experiencing a strange behavior when I run the workflow in Dify. It makes the call to Ollama, but it is restarting the model at each iteration. It didn’t do this in the previous version 7.3. The model is llama3.1.

![image](https://github.com/user-attachments/assets/a8045139-32d1-4e65-ab99-1ea20d6e8605)

![image](https://github.com/user-attachments/assets/3820ca3a-6fa5-4e2d-9d40-e90342131350)

### ✔️ Expected Behavior

I expect that the memory on gpu keeps full and dont restart de model every iteration

### ❌ Actual Behavior

Every iteration the model restarts on ollama

**Comment by dougpiv** [comment]
I am already using host.docker.internal and the connection is working. What is happening is that it seems to be restarting the model on the GPU with every request in a cycle in Dify.

**Comment by crazywoola** [comment]
> I am already using host.docker.internal and the connection is working. What is happening is that it seems to be restarting the model on the GPU with every request in a cycle in Dify.

Do you have other information regarding this behavior, I can not reproduce this.

**Comment by Howe829** [comment]
I think dify can add 'keep_live' parameter to keep the model loaded in the memory.
See the Ollama docs:
https://github.com/ollama/ollama/blob/450acb71a6366ca22eada96ab08c0527a6914c5e/docs/faq.md?plain=1#L246

**Comment by Howe829** [comment]
> I think dify can add 'keep_live' parameter while making request to Ollama server to keep the model loaded in the memory. See the Ollama docs: https://github.com/ollama/ollama/blob/450acb71a6366ca22eada96ab08c0527a6914c5e/docs/faq.md?plain=1#L246

Ok,I think dify has already support the 'keep_alive' parameter. see #4655

**Comment by dougpiv** [comment]
Sorry for the long time without an answer. Here is what is happening: I am using a simple flow:
![image](https://github.com/user-attachments/assets/78f7cf8e-0cb3-4e41-bf7b-5ca0e780d938)

And here is my model config:
![image](https://github.com/user-attachments/assets/379684b1-4d36-40b6-a432-3e234f681298)

In early versions of Dify, it didn't keep reloading the model in Ollama. Now, it seems that it loads the embedding model and after that loads the LLM model (I am using an 8GB GPU).

**Comment by Lanticee** [comment]
Hi
I am using 0.11.2 , and this status is still happens. event I set keep a live in setting.
