### ISSUE TITLE
【bug】返回结果直接把切片返回了

### ISSUE THREAD

**Issue by allentofight** [langgenius/dify#854]
如图，在dify中测试对话效果如下:

![image](https://github.com/langgenius/dify/assets/1235483/28357fb3-d8bb-49d2-b4da-dc8ee4cdc765)

直接把切片返回过来了，之前还可以，今天测试突然不行了

在设置中配置的 openai 的 apikey 是有效的

**Comment by zxhlyh** [comment]
what's your prompt?

**Comment by allentofight** [comment]
> what's your prompt?

prompt is empty, i use two github account to login, one works well in dify, but the other is not, the dataset they used is the same, the openapi key is also same, but one works well while the other is not

**Comment by allentofight** [comment]
[AI认知研习社知识库v1.1.txt](https://github.com/langgenius/dify/files/12343139/AI.v1.1.txt)
这是我上传的数据集，选择的切片方式如下
![image](https://github.com/langgenius/dify/assets/1235483/4ac13f69-29a6-4b1c-805e-58306f17ab05)

**Comment by milesking** [comment]
0.3.13 存在相同的问题

**Comment by allentofight** [comment]
> what's your prompt?

prompt is empty, you can see the previous settings I put

**Comment by allentofight** [comment]
我看最新版本已解决
