### ISSUE TITLE
the parameters, of chat workflow, cannot be changed in one chat conversation

### ISSUE THREAD

**Issue by memorylorry** [langgenius/dify#8546]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

none

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Here is an easy chat workflow, built like this picture. This bug is at the input parameters of workflow.
![image](https://github.com/user-attachments/assets/4f4fa9d6-e825-44f6-8ed8-5cd9430ecbda)

Firstly, I request chat workflow by `postman` with the following parameters, as shown in next picture. It is fine.
```json
{
    "conversation_id": "",
    "inputs": {
        "content": "你好啊，content"
    },
    "query": "万科的利润?",
    "response_mode": "streaming",
    "user": "1300000000"
}
```

![image](https://github.com/user-attachments/assets/67a7e84b-967e-4dd3-ab45-9c25ecc08c70)

Secondly, I request again with conversationId. The parameters is as follow. The problem is occured.
```json
{
    "conversation_id": "a833fb3c-2265-4e92-b78e-7ac1519787e4",
    "inputs": {
        "content": "你好啊，content is not null"
    },
    "query": "你好?",
    "response_mode": "streaming",
    "user": "1300000000"
}
```

![image](https://github.com/user-attachments/assets/fa82de49-d25c-4445-a7d9-307013428805)
**You can nontice it that the parameters of `content` is the same as the first one call.** I think that it must be a bug.

**Comment by crazywoola** [comment]
Duplicated, the is a by design behavior.

**Comment by Wu-Jiayang** [comment]
You can try this:
https://github.com/langgenius/dify/pull/7955
this may be helpful for you
