### ISSUE TITLE
unable to see collections after upload in Qdrant SaaS

### ISSUE THREAD

**Issue by imdevopx** [langgenius/dify#8551]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

 VECTOR_STORE: qdrant
  QDRANT_URL: <qdrant saas endpoint>
  QDRANT_API_KEY: <qdrant api key>
  
  Create Knowlodge > Import From File > upload Markdown or CSV file. (upload successful)
  
  Check Qdrant collections in SaaS but it's empty.. instead seems it's in my local ./volumes/app/storage
  
  means Qdrant not in used?

### ✔️ Expected Behavior

After upload file it will go to Qdrant collections or i misunderstood it?

### ❌ Actual Behavior

Empty Qdrant Collections

**Comment by Anush008** [comment]
Hey @imdevopx. I was unable to reproduce the issue and the points loaded fine for me in the Qdrant collection.

Please look for any failure messages in your Dify Docker logs.

**Comment by imdevopx** [comment]
hi @Anush008 hmmm there's no error on docker logs and the .md file upload actually went successful.. i'm just confused why the .md file i uploaded was in the ./volumes/app/storage path instead on my Qdrant collections:
<img width="740" alt="image" src="https://github.com/user-attachments/assets/836a964c-5c1d-4f26-bd51-188cbc04314d">

**Comment by Anush008** [comment]
Could be a mis-config. Can you re-confirm if the .env for the vector store is set up right?

**Comment by imdevopx** [comment]
hmm i don't have .env. i only have env for docker-compose.yaml below:
```
VECTOR_STORE: qdrant
QDRANT_URL: <qdrant saas endpoint>
QDRANT_API_KEY: <qdrant api key>
```

**Comment by imdevopx** [comment]
hi @Anush008 can you please guide me on how you uploaded the files that goes through qdrant collections? maybe that one i'm missing. thanks

**Comment by Anush008** [comment]
I set Qdrant as the vectorstore at https://github.com/langgenius/dify/blob/64baedb48429bf7332feab61d7a83cf1b7c91cda/docker/.env.example#L350-L360

and uploaded files like so
https://docs.dify.ai/guides/knowledge-base/create-knowledge-and-upload-documents

**Comment by imdevopx** [comment]
hi @Anush008 for index mode it should be High Quality not Economical? Economical, files wouldn't upload to qdrant?

**Comment by Anush008** [comment]
I had high quality selected.

**Comment by imdevopx** [comment]
seems this High Quality option will send the file to Qdrant collections. been selecting Economical before.. thanks for your help @Anush008

**Comment by Anush008** [comment]
Awesome.
