### ISSUE TITLE
Custom Disclaimer Not Displaying in WebApp Embed Modes

### ISSUE THREAD

**Issue by alterxyz** [langgenius/dify#8560]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The Custom Disclaimer is not visible in any of the embedded WebApp modes, including:

1. iframe
2. Bottom right widget
3. Chatbot Chrome Extension

However, the disclaimer is properly displayed on the main website: https://udify.app/chat/

Expected behavior: The Custom Disclaimer should be consistently visible across all embed modes, matching its appearance on the main website.

Steps to reproduce:
1. Visit an embedded version of the WebApp (iframe, bottom right widget, or Chrome Extension)
2. Look for the Custom Disclaimer
3. Note that the disclaimer is not visible

![image](https://github.com/user-attachments/assets/2ec07e42-c117-4480-afa8-237b8a382979)
![image](https://github.com/user-attachments/assets/1ec8f242-d994-40e4-9395-55900a471435)
![image](https://github.com/user-attachments/assets/8a80a6c4-7b2c-4723-a434-29dc64ad806e)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by emadellaloggia** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by cmastro-ixiam** [comment]
Hello,

I'm also interested in this bug. Could we please reopen it?
