### ISSUE TITLE
milvus local uri does not work

### ISSUE THREAD

**Issue by zc277584121** [langgenius/dify#8562]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```shell
git clone https://github.com/langgenius/dify.git
```

```shell
cd dify/docker
```
 the environment configuration file

```shell
cp .env.example .env
```

Change the value `VECTOR_STORE` in the `.env` file 
```shell
VECTOR_STORE=milvus
```
Change the Milvus configuration in the `.env` file
```shell
MILVUS_URI=http://127.0.0.1:19530
```

For the `MILVUS_URI` setting, `127.0.0.1` or `localhost` does not work. However, if I set the it as an external uri of the server  e.g.`http://172.16.70.6:19530`, it works.

I tried to enter the `api` and `worker` container, and then tried to ping 127.0.0.1:19530, but it failed. This means that the two containers and the milvus standalone container do not share the same IP 127.0.0.1 .  But when I change it to an external IP format, it worked, because every container can successfully ping the external IP.

I don't know much about network settings. I'm not sure if this is a bug, but it looks like a bug.

**Comment by AmjedKhaled165** [comment]
install this

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by zc277584121** [comment]
It seems AmjedKhaled165 's link is a fraudulent link, can someone delete it?
