### ISSUE TITLE
Dify APIServer:   Not applying SDK defaults from location

### ISSUE THREAD

**Issue by Enchante503** [langgenius/dify#8563]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

dify-web@0.8.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

`sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/uer/.config/sagemaker/config.yaml
WARNING [MainThread] [ext_mail.py:51] - MAIL_TYPE is not set
`
When I launch DifyAPIServer, I get a warning message. How can I solve this?

### ✔️ Expected Behavior

Dify　APIServer starts normally

### ❌ Actual Behavior

When I launch DifyAPIServer, I get a warning message.

**Comment by kurokobo** [comment]
As stated in the logs, the message about `sagemaker` is just `INFO` instead of `WARNING`. You can safely ignore that.

```bash
sagemaker.config 👉INFO👈 - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config 👉INFO👈 - Not applying SDK defaults from location: /home/uer/.config/sagemaker/config.yaml
WARNING [MainThread] [ext_mail.py:51] - MAIL_TYPE is not set
```

The only `WARNING` you can see is for `MAIL_TYPE`, this is completely different from sagemaker-thing. If you want to suppress this, please ensure that you have `MAIL_TYPE` env configured: https://github.com/langgenius/dify/blob/0.8.2/docker/.env.example#L523
