### ISSUE TITLE
Error when I using the [zhipuai] LLM in the workflow.

### ISSUE THREAD

**Issue by albert9yang** [langgenius/dify#8566]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.Create any new workflow,
2.Use the configured [zhipuai] large model (this large model has been verified to be usable in the chatbot),
3.An error occurs during runtime.
[zhipuai] Error: RetryError[<Future at 0x7fed8d8abac0 state=finished raised APIRequestFailedError>]

![image](https://github.com/user-attachments/assets/b36c939d-a9be-4312-8754-023470ac41b1)

### ✔️ Expected Behavior

I expect the workflow to run normally.

### ❌ Actual Behavior

The result is an error.

[zhipuai] Error: RetryError[<Future at 0x7fed8d8abac0 state=finished raised APIRequestFailedError>]

**Comment by albert9yang** [comment]
Hello,[dosubot]，https://github.com/langgenius/dify/discussions/3579#discussioncomment-10155286 -This issue is different from my question. The specific error is different. Thank you for providing the information, but the information you provided cannot solve my problem. Please ask a real person to help solve it. Thank you very much.

**Comment by QiongsK** [comment]
I have the same question when I use zhipu api. 
Now I change to kimi api to run my workflow.
