### ISSUE TITLE
Invalid upload file

### ISSUE THREAD

**Issue by jiegod** [langgenius/dify#8573]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

i use upload api upload file then use file id post chat-message,return Invalid upload file
![image](https://github.com/user-attachments/assets/2e4f9702-4a40-4289-9107-31da061f1e35)
![image](https://github.com/user-attachments/assets/6914e128-6720-4a9a-a9eb-a4b0e066e0af)

### ✔️ Expected Behavior

return success

### ❌ Actual Behavior

{
    "code": "invalid_param",
    "message": "Invalid upload file",
    "status": 400
}

**Comment by crazywoola** [comment]
![QQ_1726912155814](https://github.com/user-attachments/assets/e5b25089-febb-4487-9fcb-a78c5282a510)

The `user` is missing in this api request.

**Comment by chaozZLF** [comment]
你需要在最后传入userid而且两者要一致

**Comment by zhangrenliang1** [comment]
哈哈，我也遇到这个问题。捣鼓了半天原来要userid一样。我还以为有bug的
