### ISSUE TITLE
Load balancing prompt parameter missing using jina model

### ISSUE THREAD

**Issue by 18075717849** [langgenius/dify#8574]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Using jina model load balancing, when adding key to save, it prompts that base_url is a required parameter, but it is missing.
![iwEcAqNwbmcDAQTRAlwF0QCsBrCdGjZ8jZcOnQbU7Fx1G_EAB9IcvYxiCAAJomltCgAL0SP1 png_720x720q90](https://github.com/user-attachments/assets/88e8909d-d351-4744-aa62-f711615e950b)

### ✔️ Expected Behavior

What is the problem that causes base_url to be lost?

### ❌ Actual Behavior

What is the problem that causes base_url to be lost?

**Comment by 18075717849** [comment]
Logically speaking, the default path should be used if it is not configured. I can configure it successfully when configuring the global model, but when configuring the load balancing, it prompts that base_url is missing.

**Comment by crazywoola** [comment]
See  #8591 for updates.
