### ISSUE TITLE
Added global variables in workflow orchestration mode of Chat Assistant

### ISSUE THREAD

**Issue by Asonxw** [langgenius/dify#8582]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

**Requirement:** Add session-level variables to workflow orchestration.
**Scenario:** In the same session, this user conversation generates some global data that I want the user to use in the next conversation.
**My current implementation:** by encapsulating an http interface for storage and reading, but the performance is relatively poor, there is network overhead.

This function can be used in multiple scenarios, which helps to enrich the capabilities of dify. Hope to support it, thank you!

If you already have this function, please tell me how to use it, because I did not see the relevant introduction in the document, thank you!

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by xingxingstars123** [comment]
It seems that + Add Block→ Transform:Variable Assigner can meet your needs.

**Comment by crazywoola** [comment]
https://docs.dify.ai/guides/workflow/node/variable-assignment
