### ISSUE TITLE
After the parallel results are passed into the variable aggregator, only one result is displayed.

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#8585]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After the parallel results are passed into the variable aggregator, only one result is displayed.
The result of Code Executor 3 is missing in the diagram below
![image](https://github.com/user-attachments/assets/0c4b41cb-3ed2-4951-a452-0a55fb88b76d)

![image](https://github.com/user-attachments/assets/6d004c9f-d005-4e47-ae4f-a795c58db592)

**Comment by xrenaissance** [comment]
I also had same issues on version 0.8.2

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8420

See https://github.com/langgenius/dify/issues/8420#issuecomment-2350899774
