### ISSUE TITLE
Error in Java Multi-modal Tongyi

### ISSUE THREAD

**Issue by yanghangxl** [langgenius/dify#8589]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After uploading an image to dify using Java and obtaining the image ID, I passed the image ID through the calling process to the Tongyi multi-modal model, but encountered an error: [tongyi] Error: list index out of range.

**Comment by crazywoola** [comment]
Please upgrade to the latest version to see if this persists.
