### ISSUE TITLE
Support baidu vector db

### ISSUE THREAD

**Issue by WayneCao** [langgenius/dify#8592]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Dify doesn't support baidu vector db(https://cloud.baidu.com/product/vdb.html) yet, it has rich features and high performance:
- support vector search && bm25 search && hybrid search
- support rich index types, FLAT && HNSW && PQ && PUCK
- higher performance

would you guys be willing to accept a PR if i were to implement this with pymochow?

### 2. Additional context or comments

No response

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Feel free to open a pr for this.

**Comment by yaoice** [comment]
@WayneCao Have you completed this? Sorry, I just saw this issue of yours now. I wonder if we can cooperate to complete this pull request. I have written a first version: https://github.com/yaoice/dify/commit/9ce7a2b63a3586e97c4bce09b4c223d137118fc1. The basic functions have all been tested and run smoothly.

**Comment by WayneCao** [comment]
> @WayneCao Have you completed this? Sorry, I just saw this issue of yours now. I wonder if we can cooperate to complete this pull request. I have written a first version: [yaoice@9ce7a2b](https://github.com/yaoice/dify/commit/9ce7a2b63a3586e97c4bce09b4c223d137118fc1). The basic functions have all been tested and run smoothly.

yeah，I've submitted a pr for this issue
