### ISSUE TITLE
The enable_search parameter item for the Tongyi model is invalid

### ISSUE THREAD

**Issue by BryceWG** [langgenius/dify#8594]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The enable_search parameter option in the parameter settings of the Tongyi model is invalid. This issue has been tested with multiple versions of the models.
![Clip_2024-09-20_19-10-26](https://github.com/user-attachments/assets/ae91bc0e-b385-4b3d-b335-6a09de68282d)
![Clip_2024-09-20_19-10-19](https://github.com/user-attachments/assets/76385134-c906-4e5e-be49-8f13369e02b1)

### ✔️ Expected Behavior

Fix the enable_search parameter for Tongyi models

### ❌ Actual Behavior

The Tongyi platform refused the request parameter

**Comment by AAEE86** [comment]
This model does not enable search
