### ISSUE TITLE
Tools with Ollama

### ISSUE THREAD

**Issue by andsty** [langgenius/dify#8596]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It seems when using a model with grok and you use the same with ollama, and integrating tools is not the same outcome. with grok it respond perfect with ollama it call the tool but no response is there.

### 2. Additional context or comments

Use Llama3.1:70b with grok and ollama

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
There are two reasons for this.

- We use ReACT in Ollama
- The LLM itself, if it's not smart enough, then this could happen.

**Comment by myrulezzz** [comment]
But i use same model with grok and ollama different result. Might be the inference difference?
