### ISSUE TITLE
Magic link to create a user account

### ISSUE THREAD

**Issue by kkailaasa** [langgenius/dify#8600]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

the feature that is missing is the magic link feature to create a account. as many of us developers dont have a email domain or have the need to setup a smtp server it would be grate to have that feature back soon. thank you for your consideration. 

### 2. Additional context or comments

no

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/bf63c5d1e3aae2b6ed424255715e8db059e7ea3e/api/tasks/mail_invite_member_task.py#L45-L52
The magic link can be retrieved in Self Hosted version. The email did nothing but send the link to others.

**Comment by kkailaasa** [comment]
Thank you
