### ISSUE TITLE
Workflow knowledge retrieval node is very slow

### ISSUE THREAD

**Issue by 18075717849** [langgenius/dify#8601]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![iwEdAqNwbmcDAQTRA04F0QMqBrD735TeLu2d8QbVrEbRHTEAB9IMp1rYCAAJomltCgAL0gACM_g png_720x720q90](https://github.com/user-attachments/assets/f1cdf0ba-b9cb-4fff-9c6f-7609f27c5cac)
The workflow knowledge retrieval node is very slow, and it takes 2 minutes to retrieve it. I want to know what the principle of knowledge retrieval is, and why the recall test is very fast, but the knowledge retrieval node is very slow. Even if I restart the service, it is still very slow.

### ✔️ Expected Behavior

I want to know the principle of the knowledge retrieval node of the workflow, and what are the reasons for the slowness?

### ❌ Actual Behavior

Workflow knowledge retrieval node is very slow

**Comment by crazywoola** [comment]
Close as off topic.
