### ISSUE TITLE
An agent can only be configured with 10 tools at most?

### ISSUE THREAD

**Issue by BingGo-1** [langgenius/dify#8605]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I have an agent, and I want to use it to access an internal system, so the internal system provides many APIs to query different business data. Later I found that the agent can only be configured with 10 tools at most. Is there a way to break through or support more than the limit?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes

**Comment by BingGo-1** [comment]
> Yes

Hi，Is there a way to break through or support more than the limit?

**Comment by crazywoola** [comment]
> > Yes
> 
> Hi，Is there a way to break through or support more than the limit?

Yes, you can modify the code.

**Comment by BingGo-1** [comment]
> > > Yes
> > 
> > 
> > Hi，Is there a way to break through or support more than the limit?
> 
> Yes, you can modify the code.

OK，thanks
