### ISSUE TITLE
Can't get usage info in metadata object

### ISSUE THREAD

**Issue by joneqian** [langgenius/dify#8608]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I can't get usage info in metadata object。
![image](https://github.com/user-attachments/assets/b61be064-cdbc-498f-804e-d5a71948f028)
![image](https://github.com/user-attachments/assets/51199c4b-86fd-4ca2-a026-c599a379f911)

The workflow is very simple：
![image](https://github.com/user-attachments/assets/8de4f83b-49a4-480e-b734-fe4d5dd75dfb)

### ✔️ Expected Behavior

I want to get usage info in metadata object from response data

_No response_

**Comment by crazywoola** [comment]
Duplicated

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/8544
