### ISSUE TITLE
Can code node execute the python code generate by LLM？

### ISSUE THREAD

**Issue by epicblue** [langgenius/dify#8613]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I get some code from LLM, for example sort function and test case, but i need run it and check it's right or wrong, until i am sure the LLM output code is OK.
I try to eval() function in code Node, but it don't work, I checked https://docs.dify.ai/, i am not find out, Maybe there is exists solution i dont find, i am still search, thanks.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Eval is not allowed.
