### ISSUE TITLE
I succeeded when configuring openai_api_compatible, but I get an error when using it

### ISSUE THREAD

**Issue by skywolf123** [langgenius/dify#8615]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I succeeded when configuring openai_api_compatible, but I get an error when using it.
I looked at the config of the openai_api_compatible and there was no config item for stream.

[openai_api_compatible] Error: API request failed with status code 400: {"error":{"message":"Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported. (request id: 202409210905172535451920nkD7l6j) (request id: 20240921210516980735533ipJvo1yK) (request id: 20240921210516931134794Yvyhulv4) (request id: 2024092121051685044612833J0l3AL)","type":"invalid_request_error","param":"stream","code":"unsupported_value"}}

**Comment by crazywoola** [comment]
That's the problem with your service provider, it doesn't support the stream format of our platform.

**Comment by skywolf123** [comment]
I don't think it supports a certain stream format, but it doesn't support the stream mode, but the lack of support for the stream mode should not affect the execution of the dify workflow.

Or does dify have to use streaming mode to work?

**Comment by skywolf123** [comment]
If dify supports non-stream mode, is there any way to configure "stream" to "false"?

**Comment by crazywoola** [comment]
Sorry, we do not have a plan for this. But if you want to submit a pr for this, you are always welcome :)
