### ISSUE TITLE
"Knowledge retrieval" encounters errors when multiple knowledge bases are added.

### ISSUE THREAD

**Issue by massif-01** [langgenius/dify#8620]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I add multiple knowledge bases (around 20) in "Knowledge Retrieval," it generates errors during execution. However, if I add only 5-6, there are no errors.
[xinference] Server Unavailable Error, Failed to rerank documents, detail: Remote server 0.0.0.0:42547 closed

**Comment by crazywoola** [comment]
> [xinference] Server Unavailable Error, Failed to rerank documents, detail: Remote server 0.0.0.0:42547 closed

You need to check the logs from  xinference side to see what's going on.

**Comment by massif-01** [comment]
> > [xinference] Server Unavailable Error, Failed to rerank documents, detail: Remote server 0.0.0.0:42547 closed
> 
> You need to check the logs from xinference side to see what's going on.

When I fell back to version 0.8.2, this issue did not occur, and the deployment environment did not change
