### ISSUE TITLE
The knowledge base paging query is confused

### ISSUE THREAD

**Issue by lvxinliang** [langgenius/dify#8623]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When multiple documents are upload at the same time, confusion occurs when the Document is queried

### ✔️ Expected Behavior

There are no duplicate records for different pages

### ❌ Actual Behavior

Different pages have the same result

**Comment by lvxinliang** [comment]
The new version has been resolved： https://github.com/lvxinliang/dify/commit/2fe2e350ce55c85cf63d94fd3f5596bd781f7f17

**Comment by crazywoola** [comment]
Please close the issue if this is resolved.
