### ISSUE TITLE
When I configure OpenAI-API-compatible, I get an error when I add the o1-mini model

### ISSUE THREAD

**Issue by skywolf123** [langgenius/dify#8625]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I configure OpenAI-API-compatible, I get an error when I add the o1-mini model.

Because my o1-mini proxy is different from the gpt-4o proxy, I need to configure it through OpenAI-API-compatible, but the configuration can be used but the error is reported, and when I configure the o1-mini proxy to the OpenAI channel, it is normal, indicating that the configuration of OpenAI's o1-mini and OpenAI-API-compatible channels is different. How do I configure it to use o1-mini in OpenAI-API-compatible?

The following error message is displayed:
```
[openai_api_compatible] Error: API request failed with status code 400: {"error":{"message":"Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported. (request id: 202409210905172535451920nkD7l6j) (request id: 20240921210516980735533ipJvo1yK) (request id: 20240921210516931134794Yvyhulv4) (request id: 2024092121051685044612833J0l3AL)","type":"invalid_request_error","param":"stream","code":"unsupported_value"}}
```

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8615

OpenAI's new models indeed have this issue. Currently, we only have the resources to maintain official mainstream model providers. For compatibility modes, we hope the community can contribute PRs. Additionally, our page uses default streaming output, so it doesn't support the statement mentioned in the previous issue.
