### ISSUE TITLE
Qwen 2.5 doesn't work with prompt.

### ISSUE THREAD

**Issue by diginovo** [langgenius/dify#8629]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Tested with workflows using qwen2.5, didn't work with RAG or direct chat with defined prompt.
Worked well with Qwen2.

**Comment by crazywoola** [comment]
Qwen 2.5 doesn't support system prompt, so you can try Chatflow instead.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/8709
