### ISSUE TITLE
Hope to add the large model Spark Max-32K

### ISSUE THREAD

**Issue by qidianlinjin1990** [langgenius/dify#8650]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hope to add the large model Spark Max-32K

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This one?

https://github.com/langgenius/dify/blob/fa34b9aed672cb3df59361b01459941e2f357c1e/api/core/model_runtime/model_providers/spark/llm/spark-max.yaml#L1

**Comment by qidianlinjin1990** [comment]
不是，是最新的32k，Spark Max-32K，那个链接是8K的
