### ISSUE TITLE
Add an option to stream for Gemini.

### ISSUE THREAD

**Issue by Hisir0909** [langgenius/dify#8652]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/user-attachments/assets/56d7b445-a5f9-4139-ade6-7ab380cad4be)
It is possible that the gemini interface's review mechanism causes the stream interface to have a duration that is three times longer than the no stream interface. 
Model: gemini-1.5-flash

### 2. Additional context or comments

Someone told me how to add whether to use stream configuration for LLM nodes. 

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by AAEE86** [comment]
Sorry, I didn't notice that you checked the third item. If you submit a pull request, I can close it.

**Comment by Hisir0909** [comment]
![image](https://github.com/user-attachments/assets/3e02f0ca-8663-4040-b83d-c97a5950ffad)
![image](https://github.com/user-attachments/assets/8e1156db-0de1-47eb-ae0f-610b63ac4d70)
In fact, @AAEE86 ‘s pr is incorrect. Simply adding the `stream` flag in the YAML file is ineffective; it's passed to the model's internal parameters, not to the `stream` flag itself.

**Comment by AAEE86** [comment]
I found this problem and created a new issue #8998 
Can you solve this problem?
