### ISSUE TITLE
Issues with Spark Pro

### ISSUE THREAD

**Issue by qidianlinjin1990** [langgenius/dify#8658]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Spark Pro has an issue with screenshots
![IMG_20240923_121922](https://github.com/user-attachments/assets/bbec8ca1-fa3f-491d-b630-9f10626bbbf4)

### ✔️ Expected Behavior

None

### ❌ Actual Behavior

None

**Comment by crazywoola** [comment]
Check the app id has the correct permission to access this model.

https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html#_8-%E9%94%99%E8%AF%AF%E7%A0%81%E8%AF%B4%E6%98%8E

<img width="753" alt="image" src="https://github.com/user-attachments/assets/d73ed085-ec4b-4f33-b079-980c94d2cc63">
