### ISSUE TITLE
Max submit count 100 of workflow thread pool reached.

### ISSUE THREAD

**Issue by hwb96** [langgenius/dify#8659]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After updating to version 0.8.3, the previous workflow no longer works properly and displays: "Run failed: Failed to invoke tool: Max submit count 100 of workflow thread pool reached."
![image](https://github.com/user-attachments/assets/6b80e28d-73ca-4a73-a0d4-8ad27cc58191)

This used to work fine before.

**Comment by crazywoola** [comment]
Because of the introduction of parallelism, we have put some restrictions on the number of nodes that can be processed

**Comment by fishisnow** [comment]
the same bug i meet, the iteration node can not work as 0.8.3

**Comment by johnpccd** [comment]
> Because of the introduction of parallelism, we have put some restrictions on the number of nodes that can be processed

Hi @crazywoola, can we make this configurable through an env var?

I am having this issue on 0.10.2.. using nested parallel iterations (the nesting still doesn't add up to a 100 yet am getting the error)

**Comment by detongz** [comment]
same error here:
`api-1         | 2024-12-11 23:49:45,878.878 INFO [ThreadPoolExecutor-7_0] [_client.py:1038] - HTTP Request: POST http://sandbox:8194/v1/sandbox/run "HTTP/1.1 200 OK"
api-1         | 2024-12-11 23:49:45,881.881 ERROR [ThreadPoolExecutor-7_0] [graph_engine.py:186] - Unknown Error when graph running
api-1         | Traceback (most recent call last):
api-1         |   File "/app/api/core/workflow/graph_engine/graph_engine.py", line 145, in run
api-1         |     for item in generator:
api-1         |                 ^^^^^^^^^
api-1         |   File "/app/api/core/workflow/nodes/end/end_stream_processor.py", line 29, in process
api-1         |     for event in generator:
api-1         |                  ^^^^^^^^^
api-1         |   File "/app/api/core/workflow/graph_engine/graph_engine.py", line 379, in _run
api-1         |     for item in parallel_generator:
api-1         |                 ^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/core/workflow/graph_engine/graph_engine.py", line 432, in _run_parallel_branches
api-1         |     future = self.thread_pool.submit(
api-1         |              ^^^^^^^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/core/workflow/graph_engine/graph_engine.py", line 59, in submit
api-1         |     self.check_is_full()
api-1         |   File "/app/api/core/workflow/graph_engine/graph_engine.py", line 68, in check_is_full
api-1         |     raise ValueError(f"Max submit count {self.max_submit_count} of workflow thread pool reached.")
api-1         | ValueError: Max submit count 100 of workflow thread pool reached.`

**Comment by billwj2023-prog** [comment]
> > 由于引入了并行性，我们对可处理的节点数量进行了一些限制
> 
> 你好[@crazywoola](https://github.com/crazywoola)，我们可以通过环境变量来实现这一点吗？
> 
> 我在 0.11.0 上遇到了这个问题..使用嵌套并行迭代（嵌套仍然没有达到 100 但出现了错误）

Can the same issue be relaxed setting the envrionment variable(.env)file?
