### ISSUE TITLE
The `main` branch doesn't match the latest tag, leading to possible problems if you follow the upgrade guide for release

### ISSUE THREAD

**Issue by nadirvishun** [langgenius/dify#8660]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

example the the release v0.8.3 upgrade guid:
```
git checkout main
git pull origin main
```
but the `main` branch doesn't match `v0.8.3` tag, the code chagne `v0.8.3` is 3 days ago, but `main` is 4 hours ago, If I pull the `main` branch, it doesn't actually necessarily match version `0.8.3`.

### 2. Additional context or comments

Nope

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
When you are trying to upgrade to the latest version, keep in mind, you should switch to that tag instead of use the main branch.

**Comment by nadirvishun** [comment]
@crazywoola
Maybe you can change the upgrade guide description in the release, it was always assumed that the main branch was the same as the latest tag branch: 
![image](https://github.com/user-attachments/assets/7aa1bcde-f155-4bd8-901b-aee3c06982f8)

**Comment by crazywoola** [comment]
Thanks for the suggestion, we will do it later. @laipz8200
