### ISSUE TITLE
How do I make the red box display different text than the black box?

### ISSUE THREAD

**Issue by dosnshcu** [langgenius/dify#8661]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

How do I make the red box display different text than the black box?
https://img.picui.cn/free/2024/09/23/66f0ffad4445f.png

**Comment by crazywoola** [comment]
No you can't.
