### ISSUE TITLE
When using the knowledge base API to repeatedly delete and re upload files, after a certain number of times, it will cause the knowledge base node to be unable to query any data

### ISSUE THREAD

**Issue by lzzzzzzzzz** [langgenius/dify#8667]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using the knowledge base API to repeatedly delete and re upload files, after a certain number of times, it will cause the knowledge base node to be unable to query any data, butcan be found in the knowledge base retrieval test

[知识库清空重传.yml.txt](https://github.com/user-attachments/files/17093891/yml.txt)

![image](https://github.com/user-attachments/assets/79e71c4f-f250-43e2-b4ee-ae0c6f3088d2)
![image](https://github.com/user-attachments/assets/ce7c8167-0482-401a-a82a-87dfb4470ee3)

**Comment by JohnJyong** [comment]
pls run the single node (knowledge-retrieval-node),  is the issue still exist ?

**Comment by PolarPeak** [comment]
> 请运行单个节点（知识搜索节点），问题仍然存在吗？

I have some differences with him. I am unable to retrieve paragraphs added to the existing knowledge base. I checked the API logs, which show the following messages:
```
{"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2024-09-26T04:52:02Z"}
{"action":"read_disk_use","level":"warning","msg":"disk usage currently at 89.52%, threshold set to 80.00%","path":"/var/lib/weaviate","time":"2024-09-26T04:52:31Z"}
```

```
[2024-09-26 03:16:43,377: INFO/MainProcess] Start process document: ce79ecce-445b-4835-9052-720c7491dc5b
[2024-09-26 03:16:47,939: WARNING/MainProcess] {'error': [{'message': 'store is read-only'}]}
[2024-09-26 03:16:47,993: INFO/MainProcess] Processed dataset: 896b6e41-8c92-4090-96cf-50bd643e1c7c latency: 4.618616024963558
[2024-09-26 03:16:48,008: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[9423068a-d1c4-48a9-9730-d1519d697d6d] succeeded in 4.634086176753044s: None
```
https://github.com/langgenius/dify/issues/8768

**Comment by lzzzzzzzzz** [comment]
> pls run the single node (knowledge-retrieval-node), is the issue still exist ?

yes, and no error show in docker log( dify-api )

**Comment by PolarPeak** [comment]
> > 请运行单个节点（知识搜索节点），问题仍然存在吗？
> 
> I have some differences with him. I am unable to retrieve paragraphs added to the existing knowledge base. I checked the API logs, which show the following messages:
> 
> ```
> {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2024-09-26T04:52:02Z"}
> {"action":"read_disk_use","level":"warning","msg":"disk usage currently at 89.52%, threshold set to 80.00%","path":"/var/lib/weaviate","time":"2024-09-26T04:52:31Z"}
> ```
> 
> ```
> [2024-09-26 03:16:43,377: INFO/MainProcess] Start process document: ce79ecce-445b-4835-9052-720c7491dc5b
> [2024-09-26 03:16:47,939: WARNING/MainProcess] {'error': [{'message': 'store is read-only'}]}
> [2024-09-26 03:16:47,993: INFO/MainProcess] Processed dataset: 896b6e41-8c92-4090-96cf-50bd643e1c7c latency: 4.618616024963558
> [2024-09-26 03:16:48,008: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[9423068a-d1c4-48a9-9730-d1519d697d6d] succeeded in 4.634086176753044s: None
> ```
> 
> I'm not sure if these errors are related. #8768

https://github.com/weaviate/weaviate/issues/5912

**Comment by lzzzzzzzzz** [comment]
> > > 请运行单个节点（知识搜索节点），问题仍然存在吗？
> > 
> > 
> > I have some differences with him. I am unable to retrieve paragraphs added to the existing knowledge base. I checked the API logs, which show the following messages:
> > ```
> > {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2024-09-26T04:52:02Z"}
> > {"action":"read_disk_use","level":"warning","msg":"disk usage currently at 89.52%, threshold set to 80.00%","path":"/var/lib/weaviate","time":"2024-09-26T04:52:31Z"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > [2024-09-26 03:16:43,377: INFO/MainProcess] Start process document: ce79ecce-445b-4835-9052-720c7491dc5b
> > [2024-09-26 03:16:47,939: WARNING/MainProcess] {'error': [{'message': 'store is read-only'}]}
> > [2024-09-26 03:16:47,993: INFO/MainProcess] Processed dataset: 896b6e41-8c92-4090-96cf-50bd643e1c7c latency: 4.618616024963558
> > [2024-09-26 03:16:48,008: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[9423068a-d1c4-48a9-9730-d1519d697d6d] succeeded in 4.634086176753044s: None
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not sure if these errors are related. #8768
> 
> [weaviate/weaviate#5912](https://github.com/weaviate/weaviate/issues/5912)

The temporary solution is to create a new knowledge base and modify your workflow

**Comment by lzzzzzzzzz** [comment]
> pls run the single node (knowledge-retrieval-node), is the issue still exist ?

same problem occurs angin, dify-api logs show as follow, Is it enough to help you locate bugs

![image](https://github.com/user-attachments/assets/7179d290-7505-46f2-9005-805be5c4c3bb)

workflow as follow
![image](https://github.com/user-attachments/assets/2be2a560-328b-4470-b7c3-4e2f48c2bc6f)
