### ISSUE TITLE
Don't we need an API key for Unstructured? I don't see the env variable.

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8670]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

Don't we need an API key for Unstructured? I don't see the env variable in the .env file.

I think dify team should add UNSTRUCTURED_API_KEY

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/c8df92d0eb9afa5638e2a65b1b8f2d134959b2aa/api/.env.example#L233-L235
