### ISSUE TITLE
Request user input multiple times for a multi-step flow

### ISSUE THREAD

**Issue by paolocambria** [langgenius/dify#8672]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Creating multi-step flows that involve multiple user inputs and processing steps in Dify can be challenging. For example, consider a flow that requests user input, processes it using an LLM, makes a decision using an if/else statement, then requests additional user input, processes that input again, and finally returns the result. Currently you can only go straightforward and the flow has to start over from the beginning. Additionally, there's the risk of prompt injection in the subsequent "iterations".
I suggest to implement is a multi-step flow which requests for user input, shows llm answer and continues and keeps the flow status active, by requesting again additional input. Right now you can emulate a similar behavior in the safest way possible with if blocks and variables, but it's a tricky workaround.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by vatsaldrc** [comment]
Is this feature implemented in dify? If so, how to use it?

**Comment by wuxudong** [comment]
Why is it closed? I can't find this feature anywhere.

**Comment by wuxudong** [comment]
I found the corresponding feature in Coze: https://www.coze.com/open/docs/guides/input_node
