### ISSUE TITLE
Support Unstructured partition PDF (extracting images)

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8673]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

<img width="731" alt="image" src="https://github.com/user-attachments/assets/63e6c9ef-0268-45cf-ac4c-981ecd675747">

https://docs.unstructured.io/open-source/core-functionality/partitioning#partition-pdf

**Comment by crazywoola** [comment]
This template is for requesting document changes not features.
