### ISSUE TITLE
 direct response node only prints the value of the first variable.

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#8680]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When passing multiple variables to the direct response node, the frontend only prints the value of the first variable.

![1727083630073](https://github.com/user-attachments/assets/ee5ea58a-4908-4a53-bd2a-1e05d229a8c7)

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8420, this is an expected behavior if you append a Variable Aggregator.

**Comment by yuhp-zts** [comment]
> Duplicated #8420, this is an expected behavior if you append a Variable Aggregator.

可能我表述的不清楚，简单的场景就是，if else 下有四个链路，四个链路的结果我最后通过直接回复节点。直接回复节点中的顺序是执行器1，执行器2，执行器3，执行器4。当流程到执行器3时直接回复节点没有值。如果将执行器3放在第一位可以，但是后面的就不行了。针对这个场景，我每个执行器结果指定一个直接回复吗？可是我间介绍文档里面是可以将多个链路的结果都对接到一个直接回复节点呀
![image](https://github.com/user-attachments/assets/e1af6458-500b-42eb-9c4a-dc1b0c29f4d7)
