### ISSUE TITLE
Follow-up Questions Appear in Chinese Instead of the Query Language

### ISSUE THREAD

**Issue by NourKhdour** [langgenius/dify#8684]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3 

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Enable the follow-up feature.
Submit a query in a language other than Chinese (e.g., English or Arabic).
Observe that the follow-up question is displayed in Chinese, not in the query language.

### ✔️ Expected Behavior

The follow-up question should be displayed in the same language as the original query.

### ❌ Actual Behavior

The follow-up question is displayed in Chinese, regardless of the original query language.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8609
