### ISSUE TITLE
GPT usage

### ISSUE THREAD

**Issue by SavioR0** [langgenius/dify#8689]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am using blocks that utilize GPT models, selecting only the GPT-4o-mini.

### ✔️ Expected Behavior

Do not use the GPT-4 model.

### ❌ Actual Behavior

I am using a chaflow and, as part of the configuration, I disabled all available ChatGPT models, leaving only the GPT-4o-mini.
![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/613ea3f8-bc8e-4ff0-bc79-244f02910a48/0fb114a1-88bf-4d79-a023-ad687bb97912/image.png)
I am still experiencing a billing issue with my GPT-4 account. In none of the nodes am I using GPT-4, I am not using the API key in another project, yet it is consuming the largest portion of my expenses, as illustrated.
![Screen_Shot_2024-09-18_at_16.50.52.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/613ea3f8-bc8e-4ff0-bc79-244f02910a48/7fc03be7-356c-44e5-bc93-2396691bfa93/Screen_Shot_2024-09-18_at_16.50.52.png)

**Comment by crazywoola** [comment]
Duplicated questions, some parts of the workflow will use the system model for some tasks. You need to change that as well.

**Comment by crazywoola** [comment]
![QQ_1727097769416](https://github.com/user-attachments/assets/da7f09f9-c089-4120-ad46-838d3230caca)
