### ISSUE TITLE
Run Batch -  Failed executions - Logs show Success

### ISSUE THREAD

**Issue by corbanb** [langgenius/dify#8696]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Create workflow
2. Add 4 steps passing context from each to different models
3. Run in Batch App

### ✔️ Expected Behavior

Batch editing succeeds properly. 

### Batch editor fails
<img width="864" alt="Screenshot 2024-09-23 at 4 58 27 PM" src="https://github.com/user-attachments/assets/f5accbde-31fe-43e0-bf36-0d8fffeaf374">

Logs show success
<img width="1272" alt="Screenshot 2024-09-23 at 4 59 15 PM" src="https://github.com/user-attachments/assets/29b1144a-08ee-4a9e-81ba-088eb3b60264">

**Comment by crazywoola** [comment]
Can you provide a minimal reproducible DSL
