### ISSUE TITLE
the code error "text in input form must be less than 48 characters"

### ISSUE THREAD

**Issue by jiagoumengxiang** [langgenius/dify#8697]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="656" alt="微信图片_20240924083033" src="https://github.com/user-attachments/assets/fdbc6f3d-9105-4554-9cec-4bd5b9bc72da">
<img width="239" alt="微信图片_20240924083242" src="https://github.com/user-attachments/assets/f15cabbf-8d00-408a-a48b-4ed9360d53ad">

I also modified the env configuration file
![image](https://github.com/user-attachments/assets/33a3a036-9923-4dab-ac5e-8290cf1fd186)

rebuild all docker compose
![image](https://github.com/user-attachments/assets/40a8bf4e-0d9a-4026-b70b-c1e237818bac)

### ✔️ Expected Behavior

Expand character limits

### ❌ Actual Behavior

<img width="611" alt="微信图片_20240924083039" src="https://github.com/user-attachments/assets/d795f03f-3149-4ff0-b180-4ea2d20e7e47">

**Comment by jiagoumengxiang** [comment]
The start node has a default 48-character limit that I didn't notice

**Comment by 669zzj** [comment]
> 开始节点有一个默认的 48 个字符限制，我没有注意到

start节点有默认的字符限制吗？我没找到，方便截个图吗？

**Comment by wyywangyuyang** [comment]
修改了起始节点默认的 48 个字符限制，还是出现这个问题
