### ISSUE TITLE
pycharm Run/Debug Configurations Problem

### ISSUE THREAD

**Issue by Patientrookie** [langgenius/dify#8703]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I started locally with source code, using Pycharm's Debug Configurations, the following error occurred
![image](https://github.com/user-attachments/assets/500b5071-3596-4482-8780-0e428c1fbe36)
this is problem：
FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 1
In folder /Users/qixiaodong/project/dify/api
/Users/qixiaodong/.pyenv/versions/3.10.0/bin/python3 -X pycache_prefix=/Users/qixiaodong/Library/Caches/JetBrains/PyCharm2024.2/cpython-cache /Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py --module --multiprocess --qt-support=auto --client 127.0.0.1 --port 61722 --file flask run --host 0.0.0.0 --port=5001 
Connected to pydev debugger (build 242.21829.153)
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/qixiaodong/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/qixiaodong/project/dify/api/app.py", line 4, in <module>
    from gevent import monkey
ModuleNotFoundError: No module named 'gevent'

Process finished with exit code 2

but when i change environment variables ,this is new problem:
FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 1
In folder /Users/qixiaodong/project/dify/api
/Users/qixiaodong/.pyenv/versions/3.10.0/bin/python3 -X pycache_prefix=/Users/qixiaodong/Library/Caches/JetBrains/PyCharm2024.2/cpython-cache /Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py --module --multiprocess --qt-support=auto --client 127.0.0.1 --port 61992 --file flask run --host 0.0.0.0 --port=5001 
Connected to pydev debugger (build 242.21829.153)
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/qixiaodong/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/qixiaodong/project/dify/api/app.py", line 21, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'

Process finished with exit code 2

What causes this problem? Is there any good solution

Looking forward to your reply

### ✔️ Expected Behavior

* Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 695-801-919

### ❌ Actual Behavior

FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 1
In folder /Users/qixiaodong/project/dify/api
/Users/qixiaodong/.pyenv/versions/3.10.0/bin/python3 -X pycache_prefix=/Users/qixiaodong/Library/Caches/JetBrains/PyCharm2024.2/cpython-cache /Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py --module --multiprocess --qt-support=auto --client 127.0.0.1 --port 61992 --file flask run --host 0.0.0.0 --port=5001 
Connected to pydev debugger (build 242.21829.153)
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/qixiaodong/.pyenv/versions/3.10.0/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/qixiaodong/project/dify/api/app.py", line 21, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'

Process finished with exit code 2

**Comment by Patientrookie** [comment]
I've installed all the dependencies locally with poetry, so there's still the problem of missing modules
qixiaodong@qixiaodongdeMacBook-Pro api % poetry show         
aiohappyeyeballs                         2.4.0           Happy Eyeballs for asyncio
aiohttp                                  3.10.5          Async http client/server framework (asyncio)
aiohttp-retry                            2.8.3           Simple retry client for aiohttp
aiosignal                                1.3.1           aiosignal: a list of registered asynchronous callbacks
alembic                                  1.13.2          A database migration tool for SQLAlchemy.
alibabacloud-credentials                 0.3.5           The alibabacloud credentials module of alibabaCloud Python SDK.
alibabacloud-endpoint-util               0.0.3           The endpoint-util module of alibabaCloud Python SDK.
alibabacloud-gateway-spi                 0.0.2           Alibaba Cloud Gateway SPI SDK Library for Python
alibabacloud-gpdb20160503                3.8.3           Alibaba Cloud AnalyticDB for PostgreSQL (20160503) SDK Library for Python
alibabacloud-openapi-util                0.2.2           Aliyun Tea OpenApi Library for Python
alibabacloud-openplatform20191219        2.0.0           Alibaba Cloud OpenPlatform (20191219) SDK Library for Python
alibabacloud-oss-sdk                     0.1.0           Aliyun Tea OSS SDK Library for Python
alibabacloud-oss-util                    0.0.6           The oss util module of alibabaCloud Python SDK.
alibabacloud-tea                         0.3.9           The tea module of alibabaCloud Python SDK.
alibabacloud-tea-fileform                0.0.5           The tea-fileform module of alibabaCloud Python SDK.
alibabacloud-tea-openapi                 0.3.11          Alibaba Cloud openapi SDK Library for Python
alibabacloud-tea-util                    0.3.13          The tea-util module of alibabaCloud Python SDK.
alibabacloud-tea-xml                     0.0.2           The tea-xml module of alibabaCloud Python SDK.
aliyun-python-sdk-core                   2.15.2          The core module of Aliyun Python SDK.
aliyun-python-sdk-kms                    2.16.5          The kms module of Aliyun Python sdk.
amqp                                     5.2.0           Low-level AMQP client for Python (fork of amqplib).
aniso8601                                9.0.1           A library for parsing ISO 8601 strings.
annotated-types                          0.7.0           Reusable constraint types to use with typing.Annotated
anthropic                                0.23.1          The official Python library for the anthropic API
anyio                                    4.4.0           High level compatibility layer for multiple asynchronous event loop implementations
arxiv                                    2.1.0           Python wrapper for the arXiv API: https://arxiv.org/help/api/
asgiref                                  3.8.1           ASGI specs, helper code, and adapters
async-timeout                            4.0.3           Timeout context manager for asyncio programs
attrs                                    23.2.0          Classes Without Boilerplate
authlib                                  1.3.1           The ultimate Python library in building OAuth and OpenID Connect servers and clients.
azure-ai-inference                       1.0.0b4         Microsoft Azure Ai Inference Client Library for Python
azure-ai-ml                              1.20.0          Microsoft Azure Machine Learning Client Library for Python
azure-common                             1.1.28          Microsoft Azure Client Library for Python (Common)
azure-core                               1.30.2          Microsoft Azure Core Library for Python
azure-identity                           1.16.1          Microsoft Azure Identity Library for Python
azure-mgmt-core                          1.4.0           Microsoft Azure Management Core Library for Python
azure-storage-blob                       12.13.0         Microsoft Azure Blob Storage Client Library for Python
azure-storage-file-datalake              12.8.0          Microsoft Azure File DataLake Storage Client Library for Python
azure-storage-file-share                 12.17.0         Microsoft Azure Azure File Share Storage Client Library for Python
backoff                                  2.2.1           Function decoration for backoff and retry
bcrypt                                   4.2.0           Modern password hashing for your software and your servers
beautifulsoup4                           4.12.2          Screen-scraping library
billiard                                 4.2.0           Python multiprocessing fork with improvements and bugfixes
blinker                                  1.8.2           Fast, simple object-to-object and broadcast signaling
boto3                                    1.35.17         The AWS SDK for Python
botocore                                 1.35.17         Low-level, data-driven core of boto 3.
bottleneck                               1.4.0           Fast NumPy array functions written in C
brotli                                   1.1.0           Python bindings for the Brotli compression library
bs4                                      0.0.2           Dummy package for Beautiful Soup (beautifulsoup4)
build                                    1.2.2           A simple, correct Python build frontend
cachetools                               5.3.3           Extensible memoizing collections and decorators
celery                                   5.3.6           Distributed Task Queue.
certifi                                  2024.8.30       Python package for providing Mozilla's CA Bundle.
cffi                                     1.17.1          Foreign Function Interface for Python calling C code.
chardet                                  5.1.0           Universal encoding detector for Python 3
charset-normalizer                       3.3.2           The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
chroma-hnswlib                           0.7.3           Chromas fork of hnswlib
chromadb                                 0.5.1           Chroma.
circuitbreaker                           2.0.0           Python Circuit Breaker pattern implementation
click                                    8.1.7           Composable command line interface toolkit
click-didyoumean                         0.3.1           Enables git-like *did-you-mean* feature in click
click-plugins                            1.1.1           An extension module for click to enable registering CLI commands via setuptools entry-points.
click-repl                               0.3.0           REPL plugin for Click
clickhouse-connect                       0.7.19          ClickHouse Database Core Driver for Python, Pandas, and Superset
clickhouse-driver                        0.2.9           Python driver with native interface for ClickHouse
cloudpickle                              2.2.1           Extended pickling support for Python objects
cloudscraper                             1.2.71          A Python module to bypass Cloudflare's anti-bot page.
cohere                                   5.2.6           
colorama                                 0.4.6           Cross-platform colored terminal text.
coloredlogs                              15.0.1          Colored terminal output for Python's logging module
contourpy                                1.3.0           Python library for calculating contours of 2D quadrilateral grids
cos-python-sdk-v5                        1.9.30          cos-python-sdk-v5
crcmod                                   1.7             CRC Generator
cryptography                             42.0.8          cryptography is a package which provides cryptographic recipes and primitives to Python developers.
cssselect                                1.2.0           cssselect parses CSS3 Selectors and translates them to XPath 1.0
cycler                                   0.12.1          Composable style cycles
dashscope                                1.17.1          dashscope client sdk library
dataclass-wizard                         0.22.3          Marshal dataclasses to/from JSON. Use field properties with initial values. Construct a dataclass schema with JSON input.
dataclasses                              0.6             A backport of the dataclasses module for Python 3.6
dataclasses-json                         0.6.7           Easily serialize dataclasses to and from JSON.
db-dtypes                                1.3.0           Pandas Data Types for SQL systems (BigQuery, Spanner)
defusedxml                               0.7.1           XML bomb protection for Python stdlib modules
deprecated                               1.2.14          Python @deprecated decorator to deprecate old python classes, functions or methods.
dill                                     0.3.8           serialize all of Python
distro                                   1.9.0           Distro - an OS platform information API
docker                                   7.1.0           A Python library for the Docker Engine API.
docstring-parser                         0.16            Parse Python docstrings in reST, Google and Numpydoc format
duckdb                                   1.1.0           DuckDB in-process database
duckduckgo-search                        6.2.12          Search for words, documents, images, news, maps and text translation using the DuckDuckGo.com search engine.
elastic-transport                        8.15.0          Transport classes and utilities shared among Python Elastic client libraries
elasticsearch                            8.14.0          Python client for Elasticsearch
emoji                                    2.12.1          Emoji for Python
environs                                 9.5.0           simplified environment variable parsing
esdk-obs-python                          3.24.6.1        OBS Python SDK
et-xmlfile                               1.1.0           An implementation of lxml.xmlfile for the standard library
exceptiongroup                           1.2.2           Backport of PEP 654 (exception groups)
fastapi                                  0.114.1         FastAPI framework, high performance, easy to learn, fast to code, ready for production
fastavro                                 1.9.7           Fast read/write of AVRO files
feedfinder2                              0.0.4           Find the feed URLs for a website.
feedparser                               6.0.10          Universal feed parser, handles RSS 0.9x, RSS 1.0, RSS 2.0, CDF, Atom 0.3, and Atom 1.0 feeds
filelock                                 3.16.0          A platform independent file lock.
filetype                                 1.2.0           Infer file type and MIME type of any file/buffer. No external dependencies.
flask                                    3.0.3           A simple framework for building complex web applications.
flask-compress                           1.14            Compress responses in your Flask app with gzip, deflate or brotli.
flask-cors                               4.0.2           A Flask extension adding a decorator for CORS support
flask-login                              0.6.3           User authentication and session management for Flask.
flask-migrate                            4.0.7           SQLAlchemy database migrations for Flask applications using Alembic.
flask-restful                            0.3.10          Simple framework for creating REST APIs
flask-sock                               0.7.0           WebSocket support for Flask
flask-sqlalchemy                         3.1.1           Add SQLAlchemy support to your Flask application.
flatbuffers                              24.3.25         The FlatBuffers serialization format for Python
fonttools                                4.53.1          Tools to manipulate font files
frozendict                               2.4.4           A simple immutable dictionary
frozenlist                               1.4.1           A list-like structure which implements collections.abc.MutableSequence
fsspec                                   2024.9.0        File-system specification
gevent                                   23.9.1          Coroutine-based network library
gmpy2                                    2.2.1           gmpy2 interface to GMP, MPFR, and MPC for Python 3.7+
google-ai-generativelanguage             0.6.1           Google Ai Generativelanguage API client library
google-api-core                          2.18.0          Google API client core library
google-api-python-client                 2.90.0          Google API Client Library for Python
google-auth                              2.29.0          Google Authentication Library
google-auth-httplib2                     0.2.0           Google Authentication Library: httplib2 transport
google-cloud-aiplatform                  1.49.0          Vertex AI API client library
google-cloud-bigquery                    3.25.0          Google BigQuery API client library
google-cloud-core                        2.4.1           Google Cloud API client core library
google-cloud-resource-manager            1.12.5          Google Cloud Resource Manager API client library
google-cloud-storage                     2.16.0          Google Cloud Storage API client library
google-crc32c                            1.6.0           A python wrapper of the C library 'Google CRC32C'
google-generativeai                      0.5.0           Google Generative AI High level API client library and tools.
google-pasta                             0.2.0           pasta is an AST-based Python refactoring library
google-resumable-media                   2.7.2           Utilities for Google Media Downloads and Resumable Uploads
googleapis-common-protos                 1.63.0          Common protobufs used in Google APIs
greenlet                                 3.1.0           Lightweight in-process concurrent programming
grpc-google-iam-v1                       0.13.1          IAM API client library
grpcio                                   1.66.1          HTTP/2-based RPC framework
grpcio-status                            1.62.3          Status proto mapping for gRPC
grpcio-tools                             1.62.3          Protobuf code generator for gRPC
gunicorn                                 22.0.0          WSGI HTTP Server for UNIX
h11                                      0.14.0          A pure-Python, bring-your-own-I/O implementation of HTTP/1.1
h2                                       4.1.0           HTTP/2 State-Machine based protocol implementation
hiredis                                  3.0.0           Python wrapper for hiredis
hpack                                    4.0.0           Pure-Python HPACK header compression
html5lib                                 1.1             HTML parser based on the WHATWG HTML specification
httpcore                                 1.0.5           A minimal low-level HTTP client.
httplib2                                 0.22.0          A comprehensive HTTP client library.
httptools                                0.6.1           A collection of framework independent HTTP protocol utils.
httpx                                    0.27.2          The next generation HTTP client.
huggingface-hub                          0.16.4          Client library to download and publish models, datasets and other repos on the huggingface.co hub
humanfriendly                            10.0            Human friendly output for text interfaces using Python
hyperframe                               6.0.1           HTTP/2 framing layer for Python
idna                                     3.8             Internationalized Domain Names in Applications (IDNA)
importlib-metadata                       6.11.0          Read metadata from Python packages
importlib-resources                      6.4.5           Read resources from Python packages
isodate                                  0.6.1           An ISO 8601 date/time/duration parser and formatter
itsdangerous                             2.2.0           Safely pass data to untrusted environments and back.
jieba                                    0.42.1          Chinese Words Segmentation Utilities
jieba3k                                  0.35.1          Chinese Words Segementation Utilities
jinja2                                   3.1.4           A very fast and expressive template engine.
jmespath                                 0.10.0          JSON Matching Expressions
joblib                                   1.4.2           Lightweight pipelining with Python functions
jsonpath-ng                              1.6.1           A final implementation of JSONPath for Python that aims to be standard compliant, including arithmetic and binary comparison operators and providing c...
jsonschema                               4.23.0          An implementation of JSON Schema validation for Python
jsonschema-specifications                2023.12.1       The JSON Schema meta-schemas and vocabularies, exposed as a Registry
kaleido                                  0.2.1           Static image export for web-based visualization libraries with zero dependencies
kiwisolver                               1.4.7           A fast implementation of the Cassowary constraint solver
kombu                                    5.4.1           Messaging library for Python.
kubernetes                               30.1.0          Kubernetes python client
langdetect                               1.0.9           Language detection library ported from Google's language-detection.
langfuse                                 2.48.0          A client library for accessing langfuse
langsmith                                0.1.118         Client library to connect to the LangSmith LLM Tracing and Evaluation Platform.
llvmlite                                 0.43.0          lightweight wrapper around basic LLVM functionality
lxml                                     5.3.0           Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
lz4                                      4.3.3           LZ4 Bindings for Python
mailchimp-transactional                  1.0.56          Mailchimp Transactional API
mako                                     1.3.5           A super-fast templating language that borrows the best ideas from the existing templating languages.
markdown                                 3.5.2           Python implementation of John Gruber's Markdown.
markdown-it-py                           3.0.0           Python port of markdown-it. Markdown parsing, done right!
markupsafe                               2.1.5           Safely add untrusted strings to HTML/XML markup.
marshmallow                              3.22.0          A lightweight library for converting complex datatypes to and from native Python datatypes.
matplotlib                               3.8.4           Python plotting package
mdurl                                    0.1.2           Markdown URL utilities
milvus-lite                              2.4.10          A lightweight version of Milvus wrapped with Python.
mmh3                                     4.1.0           Python extension for MurmurHash (MurmurHash3), a set of fast and robust hash functions.
mock                                     4.0.3           Rolling backport of unittest.mock for all Pythons
monotonic                                1.6             An implementation of time.monotonic() for Python 2 & < 3.3
mpmath                                   1.3.0           Python library for arbitrary-precision floating-point arithmetic
msal                                     1.31.0          The Microsoft Authentication Library (MSAL) for Python library enables your app to access the Microsoft Cloud by supporting authentication of users wi...
msal-extensions                          1.2.0           Microsoft Authentication Library extensions (MSAL EX) provides a persistence API that can save your data on disk, encrypted on Windows, macOS and Linu...
msg-parser                               1.2.0           This module enables reading, parsing and converting Microsoft Outlook MSG E-Mail files.
msrest                                   0.7.1           AutoRest swagger generator Python client runtime.
multidict                                6.1.0           multidict implementation
multiprocess                             0.70.16         better multiprocessing and multithreading in Python
multitasking                             0.0.11          Non-blocking Python methods using decorators
mypy-extensions                          1.0.0           Type system extensions for programs checked with the mypy type checker.
newspaper3k                              0.2.8           Simplified python article discovery & extraction.
nltk                                     3.8.1           Natural Language Toolkit
novita-client                            0.5.7           novita SDK for Python
numba                                    0.60.0          compiling Python code using LLVM
numexpr                                  2.9.0           Fast numerical expression evaluator for NumPy
numpy                                    1.26.4          Fundamental package for array computing in Python
oauthlib                                 3.2.2           A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
oci                                      2.133.0         Oracle Cloud Infrastructure Python SDK
odfpy                                    1.4.1           Python API and tools to manipulate OpenDocument files
olefile                                  0.47            Python package to parse, read and write Microsoft OLE2 files (Structured Storage or Compound Document, Microsoft Office)
onnxruntime                              1.19.2          ONNX Runtime is a runtime accelerator for Machine Learning models
openai                                   1.29.0          The official Python library for the openai API
opencensus                               0.11.4          A stats collection and distributed tracing framework
opencensus-context                       0.1.3           OpenCensus Runtime Context
opencensus-ext-azure                     1.1.13          OpenCensus Azure Monitor Exporter
opencensus-ext-logging                   0.1.1           OpenCensus logging Integration
openpyxl                                 3.1.5           A Python library to read/write Excel 2010 xlsx/xlsm files
opensearch-py                            2.4.0           Python client for OpenSearch
opentelemetry-api                        1.27.0          OpenTelemetry Python API
opentelemetry-exporter-otlp-proto-common 1.27.0          OpenTelemetry Protobuf encoding
opentelemetry-exporter-otlp-proto-grpc   1.27.0          OpenTelemetry Collector Protobuf over gRPC Exporter
opentelemetry-instrumentation            0.48b0          Instrumentation Tools & Auto Instrumentation for OpenTelemetry Python
opentelemetry-instrumentation-asgi       0.48b0          ASGI instrumentation for OpenTelemetry
opentelemetry-instrumentation-fastapi    0.48b0          OpenTelemetry FastAPI Instrumentation
opentelemetry-proto                      1.27.0          OpenTelemetry Python Proto
opentelemetry-sdk                        1.27.0          OpenTelemetry Python SDK
opentelemetry-semantic-conventions       0.48b0          OpenTelemetry Semantic Conventions
opentelemetry-util-http                  0.48b0          Web util for OpenTelemetry
oracledb                                 2.2.1           Python interface to Oracle Database
orjson                                   3.10.7          Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
oss2                                     2.18.5          Aliyun OSS (Object Storage Service) SDK
overrides                                7.7.0           A decorator to automatically detect mismatch when overriding a method.
packaging                                24.1            Core utilities for Python packages
pandas                                   2.2.2           Powerful data structures for data analysis, time series, and statistics
pathos                                   0.3.2           parallel graph management and execution in heterogeneous computing
peewee                                   3.17.6          a little orm
pgvecto-rs                               0.2.1           Python binding for pgvecto.rs
pgvector                                 0.2.5           pgvector support for Python
pillow                                   10.4.0          Python Imaging Library (Fork)
platformdirs                             4.3.2           A small Python package for determining appropriate platform-specific dirs, e.g. a `user data dir`.
plotly                                   5.24.0          An open-source, interactive data visualization library for Python
ply                                      3.11            Python Lex & Yacc
portalocker                              2.10.1          Wraps the portalocker recipe for easy usage
posthog                                  3.6.5           Integrate PostHog into any python application.
pox                                      0.3.4           utilities for filesystem exploration and automated builds
ppft                                     1.7.6.8         distributed and parallel Python
primp                                    0.6.2           HTTP client that can impersonate web browsers, mimicking their headers and `TLS/JA3/JA4/HTTP2` fingerprints
prompt-toolkit                           3.0.47          Library for building powerful interactive command lines in Python
proto-plus                               1.24.0          Beautiful, Pythonic protocol buffers.
protobuf                                 4.25.4          
psutil                                   6.0.0           Cross-platform lib for process and system monitoring in Python.
psycopg2-binary                          2.9.9           psycopg2 - Python-PostgreSQL Database Adapter
pyarrow                                  17.0.0          Python library for Apache Arrow
pyasn1                                   0.6.1           Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)
pyasn1-modules                           0.4.1           A collection of ASN.1-based protocols modules
pycparser                                2.22            C parser in Python
pycryptodome                             3.19.1          Cryptographic library for Python
pydantic                                 2.8.2           Data validation using Python type hints
pydantic-core                            2.20.1          Core functionality for Pydantic validation and serialization
pydantic-extra-types                     2.9.0           Extra Pydantic types.
pydantic-settings                        2.4.0           Settings management using Pydantic
pydash                                   8.0.3           The kitchen sink of Python utility libraries for doing "stuff" in a functional way. Based on the Lo-Dash Javascript library.
pygments                                 2.18.0          Pygments is a syntax highlighting package written in Python.
pyjwt                                    2.8.0           JSON Web Token implementation in Python
pymilvus                                 2.4.6           Python Sdk for Milvus
pymysql                                  1.1.1           Pure Python MySQL Driver
pyopenssl                                24.2.1          Python wrapper module around the OpenSSL library
pypandoc                                 1.13            Thin wrapper for pandoc.
pyparsing                                3.1.4           pyparsing module - Classes and methods to define and execute parsing grammars
pypdfium2                                4.17.0          Python bindings to PDFium
pypika                                   0.48.9          A SQL query builder API for Python
pypng                                    0.20220715.0    Pure Python library for saving and loading PNG images
pyproject-hooks                          1.1.0           Wrappers to call pyproject.toml-based build backend hooks.
python-calamine                          0.2.3           Python binding for Rust's library for reading excel and odf file - calamine
python-dateutil                          2.9.0.post0     Extensions to the standard Python datetime module
python-docx                              1.1.2           Create, read, and update Microsoft Word .docx files.
python-dotenv                            1.0.0           Read key-value pairs from a .env file and set them as environment variables
python-iso639                            2024.4.27       ISO 639 language codes, names, and other associated information
python-magic                             0.4.27          File type identification using libmagic
python-pptx                              0.6.23          Generate and manipulate Open XML PowerPoint (.pptx) files
pytz                                     2024.2          World timezone definitions, modern and historical
pyxlsb                                   1.0.10          Excel 2007-2010 Binary Workbook (xlsb) parser
pyyaml                                   6.0.2           YAML parser and emitter for Python
qdrant-client                            1.7.3           Client library for the Qdrant vector search engine
qrcode                                   7.4.2           QR Code image generator
rank-bm25                                0.2.2           Various BM25 algorithms for document ranking
rapidfuzz                                3.9.7           rapid fuzzy string matching
readabilipy                              0.2.0           Python wrapper for Mozilla's Readability.js
redis                                    5.0.8           Python client for Redis database and key-value store
referencing                              0.35.1          JSON Referencing + Python
regex                                    2024.9.11       Alternative regular expression module, to replace re.
replicate                                0.22.0          Python client for Replicate
requests                                 2.31.0          Python HTTP for Humans.
requests-file                            2.1.0           File transport adapter for Requests
requests-oauthlib                        2.0.0           OAuthlib authentication support for Requests.
requests-toolbelt                        1.0.0           A utility belt for advanced users of python-requests
resend                                   0.7.2           Resend Python SDK
rich                                     13.8.1          Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
rpds-py                                  0.20.0          Python bindings to Rust's persistent data structures (rpds)
rsa                                      4.9             Pure-Python RSA implementation
s3transfer                               0.10.2          An Amazon S3 Transfer Manager
safetensors                              0.4.5           
sagemaker                                2.231.0         Open source library for training and deploying models on Amazon SageMaker.
sagemaker-core                           1.0.4           An python package for sagemaker core functionalities
schema                                   0.7.7           Simple data validation library
scikit-learn                             1.5.2           A set of python modules for machine learning and data mining
scipy                                    1.14.1          Fundamental algorithms for scientific computing in Python
sentry-sdk                               1.44.1          Python client for Sentry (https://sentry.io)
setuptools                               74.1.2          Easily download, build, install, upgrade, and uninstall Python packages
sgmllib3k                                1.0.0           Py3k port of sgmllib.
shapely                                  2.0.6           Manipulation and analysis of geometric objects
shellingham                              1.5.4           Tool to Detect Surrounding Shell
simple-websocket                         1.0.0           Simple WebSocket server and client for Python
six                                      1.16.0          Python 2 and 3 compatibility utilities
smdebug-rulesconfig                      1.0.1           SMDebug RulesConfig
sniffio                                  1.3.1           Sniff out which async library your code is running under
socksio                                  1.0.0           Sans-I/O implementation of SOCKS4, SOCKS4A, and SOCKS5.
soupsieve                                2.6             A modern CSS selector implementation for Beautiful Soup.
sqlalchemy                               2.0.34          Database Abstraction Library
sqlparse                                 0.5.1           A non-validating SQL parser.
starlette                                0.38.5          The little ASGI library that shines.
strictyaml                               1.7.3           Strict, typed YAML parser
sympy                                    1.13.2          Computer algebra system (CAS) in Python
tabulate                                 0.9.0           Pretty-print tabular data
tblib                                    3.0.0           Traceback serialization library.
tcvectordb                               1.3.2           Tencent VectorDB Python SDK
tenacity                                 9.0.0           Retry code until it succeeds
tencentcloud-sdk-python-common           3.0.1230        Tencent Cloud Common SDK for Python
tencentcloud-sdk-python-hunyuan          3.0.1230        Tencent Cloud Hunyuan SDK for Python
threadpoolctl                            3.5.0           threadpoolctl
tidb-vector                              0.0.9           A Python client for TiDB Vector
tiktoken                                 0.7.0           tiktoken is a fast BPE tokeniser for use with OpenAI's models
tinysegmenter                            0.3             Very compact Japanese tokenizer
tldextract                               5.1.2           Accurately separates a URL's subdomain, domain, and public suffix, using the Public Suffix List (PSL). By default, this includes the public ICANN TLDs...
tokenizers                               0.15.2          
toml                                     0.10.2          Python Library for Tom's Obvious, Minimal Language
tomli                                    2.0.1           A lil' TOML parser
tos                                      2.7.1           Volc TOS (Tinder Object Storage) SDK
tqdm                                     4.66.5          Fast, Extensible Progress Meter
transformers                             4.35.2          State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
twilio                                   9.0.5           Twilio API client and TwiML generator
typer                                    0.12.5          Typer, build great CLIs. Easy to code. Based on Python type hints.
types-requests                           2.32.0.20240907 Typing stubs for requests
typing-extensions                        4.12.2          Backported and Experimental Type Hints for Python 3.8+
typing-inspect                           0.9.0           Runtime inspection utilities for typing module.
tzdata                                   2024.1          Provider of IANA time zone data
tzlocal                                  5.2             tzinfo object for the local timezone
ujson                                    5.10.0          Ultra fast JSON encoder and decoder for Python
unstructured                             0.10.30         A library that prepares raw documents for downstream ML tasks.
uritemplate                              4.1.1           Implementation of RFC 6570 URI Templates
urllib3                                  2.2.2           HTTP library with thread-safe connection pooling, file post, and more.
uvicorn                                  0.30.6          The lightning-fast ASGI server.
uvloop                                   0.20.0          Fast implementation of asyncio event loop on top of libuv
validators                               0.21.0          Python Data Validation for Humans™
vanna                                    0.5.5           Generate SQL queries from natural language
vine                                     5.1.0           Python promises.
volcengine-python-sdk                    1.0.100         Volcengine SDK for Python
watchfiles                               0.24.0          Simple, modern and high performance file watching and code reload in python.
wcwidth                                  0.2.13          Measures the displayed width of unicode strings in a terminal
weaviate-client                          3.21.0          A python native Weaviate client
webencodings                             0.5.1           Character encoding aliases for legacy web content
websocket-client                         1.7.0           WebSocket client for Python with low level API options
websockets                               13.0.1          An implementation of the WebSocket Protocol (RFC 6455 & 7692)
werkzeug                                 3.0.4           The comprehensive WSGI web application library.
wikipedia                                1.4.0           Wikipedia API for Python
wrapt                                    1.16.0          Module for decorators, wrappers and monkey patching.
wsproto                                  1.2.0           WebSockets state-machine based protocol implementation
xinference-client                        0.13.3          Client for Xinference
xlrd                                     2.0.1           Library for developers to extract data from Microsoft Excel (tm) .xls spreadsheet files
xlsxwriter                               3.2.0           A Python module for creating Excel XLSX files.
xmltodict                                0.13.0          Makes working with XML feel like you are working with JSON
yarl                                     1.9.11          Yet another URL library
yfinance                                 0.2.43          Download market data from Yahoo! Finance API
zhipuai                                  1.0.7           A SDK library for accessing big model apis from ZhipuAI
zipp                                     3.20.1          Backport of pathlib-compatible object wrapper for zip files
zope-event                               5.0             Very basic event publishing system
zope-interface                           7.0.3           Interfaces for Python
zstandard                                0.23.0          Zstandard bindings for Python
This is what I get back after executing the command, and you can clearly see that the module is fully loaded

**Comment by Patientrookie** [comment]
Thank you very much for your reply. I will follow your same configuration as follows
![image](https://github.com/user-attachments/assets/7e39e446-32c0-4a32-8e3f-3f23c5d1e23d)
Then a Warning is displayed: Flask &gt; = 1.0 is required, but the project is ready to tun.
Another question is about the configuration of worker service. You can send it to me.
Looking forward to your reply, thank you very much.

**Comment by kuschzzp** [comment]
Here is my config :

i use python not flask

![WeChatca8b8976fc044b984aed465c955620d7](https://github.com/user-attachments/assets/bc9f0559-96dc-4574-a6c5-9afead93b3b4)
![WeChat950e21bf81871eb88f58532c42a975ee](https://github.com/user-attachments/assets/e1844be0-d556-4ebd-b817-f26d4ccc2952)
![WeChat0b174ea1b6f05af9052816a308705da2](https://github.com/user-attachments/assets/e23554ed-f79c-4418-8cc3-318976bdff3e)

**Comment by Patientrookie** [comment]
Thank you very much for your sharing

**Comment by Patientrookie** [comment]
Thank you very much for your sharing, but 
![image](https://github.com/user-attachments/assets/ac9f99c0-d270-40c7-8897-86733a924e0e)
The exact same configuration
![image](https://github.com/user-attachments/assets/8f3cd00c-7f8c-4330-93a6-86ce9c2820fe)
I tried to change the folder name of Crypto to crypto, but it didn't work.

**Comment by Patientrookie** [comment]
@kuschzzp How do you install dependencies, if using python
![image](https://github.com/user-attachments/assets/eef09ae3-6536-4a46-ae83-9e003daef449)
Manually installing dependencies one by one is cumbersome

**Comment by Patientrookie** [comment]
This issue has been resolved and I have modified site-packages crypto in the folder is Crypto.
