### ISSUE TITLE
Qwen2.5 deployed with ollama is not available in dify

### ISSUE THREAD

**Issue by sunzao413** [langgenius/dify#8709]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/6714a203-b373-430c-b234-bfd35f1f4a67)
![image](https://github.com/user-attachments/assets/7424558a-2ee9-4d9d-936f-36a7eb13c5f3)
1. When using QWEN2.5 through the LLM module, the input information is normal, but it cannot be transmitted to the model interface normally, the model cannot be output according to the context, and the QWEN2 model can be output normally if the QWEN2 model is replaced in the same process.
2. The left side of the picture is the QWEN2 model, the input is 885 tokens, and the right side is replaced by the QWEN2.5 model, and the input is only 12 tokens, and the actual input has not changed.
3. The model has been reconfigured several times, and the model server has been restarted, but the problem is still the same.

**Comment by AAEE86** [comment]
This issue cannot be reproduced. Please provide more LLM configuration information.

**Comment by sunzao413** [comment]
> This issue cannot be reproduced. Please provide more LLM configuration information.

![333](https://github.com/user-attachments/assets/b1a1c26d-0ccc-49f8-8537-44f84b285a0f)
![444](https://github.com/user-attachments/assets/1281a9db-3b8c-4345-b303-c92f7375a3f4)
![555](https://github.com/user-attachments/assets/8097080b-c719-4567-9220-6bd026ada039)

知识库搜索作为上下文，输入不止12个token，实际有好几百字的输入，放system里作为上下文时就没法识别，放user里面就能正常识别

**Comment by AAEE86** [comment]
依旧无法重现此问题
