### ISSUE TITLE
LLM cannot upload files when calling large models

### ISSUE THREAD

**Issue by 18075717849** [langgenius/dify#8711]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

LLM cannot upload files when calling large models. Our current requirement is to be able to upload files, but why is there no corresponding upload file found on diffy? The large model can only upload images.

### ✔️ Expected Behavior

LLM cannot upload files when calling large models. Our current requirement is to be able to upload files, but why is there no corresponding upload file found on diffy? The large model can only upload images.

### ❌ Actual Behavior

LLM cannot upload files when calling large models. Our current requirement is to be able to upload files, but why is there no corresponding upload file found on diffy? The large model can only upload images.

**Comment by 18075717849** [comment]
@StudyingLover  @dosu My question is does dify support LLM uploading files? Now I only find uploaded images.

**Comment by crazywoola** [comment]
First of all, this is bug only report. 
Secondly, you should search existing issues before opening it. 
Thirdly, https://github.com/langgenius/dify/issues/5346 this issue is pinned in the issues pages.
