### ISSUE TITLE
HTTP Request: Text size is too large, max size is 1.00 MB, but current size is 1.69 MB.

### ISSUE THREAD

**Issue by zhuiyue132** [langgenius/dify#8713]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8,3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/15d763c0-6f11-4118-8378-c05bf5b87832)

I noticed that there is an HTTP_REQUEST_NODE_MAX_TEXT_SIZE environment variable when starting with source code, but this variable does not exist when starting with Docker.

Please synchronize this environment variable to the docker deployment method.

**Comment by crazywoola** [comment]
Feel free to open a pr for this.
