### ISSUE TITLE
The images in the WebClient client are not displaying.

### ISSUE THREAD

**Issue by liubaiwu** [langgenius/dify#8720]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/1a26fd46-317f-4127-ae9d-fa534431a4f1)
When I use Dify WebClient, after a normal deployment to the local environment, I am able to have normal chat output. However, if the output content includes images, the images cannot be displayed properly. This is because when accessing the WebClient locally, the address starts with localhost, but the images are stored on the server side of our deployed open-source Dify. How can I make the images display correctly?

### ✔️ Expected Behavior

In the configuration file of our WebClient client, we have already set the value for NEXT_PUBLIC_API_URL, and other functionalities are working normally. However, it seems that the image URLs are not using this address to obtain the full image URLs. We hope to have the images display correctly.

### ❌ Actual Behavior

When I use Dify WebClient, after a normal deployment to the local environment, I am able to have normal chat output. However, if the output content includes images, the images cannot be displayed properly. This is because when accessing the WebClient locally, the address starts with localhost, but the images are stored on the server side of our deployed open-source Dify. How can I make the images display correctly?

**Comment by crazywoola** [comment]
3001 is frontend service, and the image link is generated by the backend, it's obvious that the url isn't correct. You need to config the `CONSOLE_API_URL ` and  `FILES_URL` id `.env`
