### ISSUE TITLE
For path has requests dependency, why can't import, sandbox image: langgenius/dify-sandbox:latest

### ISSUE THREAD

**Issue by rosehuynh92** [langgenius/dify#8722]
For path has requests dependency, why can't import, sandbox image: langgenius/dify-sandbox:latest
![image](https://github.com/langgenius/dify/assets/14178306/da99544c-30ff-4173-b4f0-3c2f4d86d3e4)

![image](https://github.com/langgenius/dify/assets/14178306/ee63475e-7be7-4dc2-a0cd-b3f8add5c857)

_Originally posted by @EvanGerry in https://github.com/langgenius/dify/discussions/4854_

**Comment by crazywoola** [comment]
Please use 0.2.9
