### ISSUE TITLE
Parameters and query cannot be changed for different sessions

### ISSUE THREAD

**Issue by dabaicai123** [langgenius/dify#8723]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

step1:new a chat bot flow，set one paramter
step2:run
step3:new two conversations and set different parameters

![搜狗截图20240924185318](https://github.com/user-attachments/assets/2533b66e-0760-42e5-b1e6-6fd42756c540)
![搜狗截图20240924185823](https://github.com/user-attachments/assets/af2126ec-59fa-44c0-9d93-69410fbdf221)

### ✔️ Expected Behavior

command match log

**Comment by crazywoola** [comment]
I am not quite sure what you are talking about.  Can you explain it again?

**Comment by dabaicai123** [comment]
I created a chat workflow, new click run set different parameters in the log view of the upload participation my actual upload inconsistent. The same is true with apis, where parameters cannot be changed from session to session

**Comment by dabaicai123** [comment]
In my screenshot, I pass hello1, but view log is hello5. I'm not sure which part is wrong, whether the log will prevail or if my parameters is not valid

**Comment by dabaicai123** [comment]
The dialog log is the record of the last round of viewing, because I only have one dialog, click on the dialog to pop up the dialog log box by default, I mistook it for the transmission of the current dialog, in fact, I need to view the log in the chat record again.  thanks

**Comment by crazywoola** [comment]
<img width="202" alt="image" src="https://github.com/user-attachments/assets/4f410e5a-e1b0-41de-94e6-8e63dd72680b">

Did you publish the application. If not, the conversation will use previous version to handle the calls.

If you modified something, you need to make sure:
- publish it
- use a new conversation to start new call
- you will not be able to change the session B's parameter in session A
- you will not be able to change the inputs in later conversations
