### ISSUE TITLE
Failed to connect to Milvus

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8725]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="835" alt="image" src="https://github.com/user-attachments/assets/8f0a972c-96bd-4572-b830-4e953e8a3c29">

VECTOR_STORE=milvus
MILVUS_URI=http://127.0.0.1:19530
MILVUS_TOKEN=
MILVUS_USER=root
MILVUS_PASSWORD=Milvus

**Comment by taowang1993** [comment]
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/600403de-6fef-491b-aa31-610084bc91db">

**Comment by taowang1993** [comment]
the milvus-standalone is running, but not connecting

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/pull/8019

**Comment by taowang1993** [comment]
> See #8019

I added networks to the worker and api containers. Now it is working.
And I specified the URI as MILVUS_URI=http://milvus-standalone:19530

# docker-compose.override.yaml (I think it is good to have this file because the default docker-compose.yaml file will be overriden when updating Dify)

name: dify

services:
  api:
    image: langgenius/dify-api:latest
    networks:
      - ssrf_proxy_network
      - default
      - milvus

  worker:
    image: langgenius/dify-api:latest
    networks:
      - ssrf_proxy_network
      - default
      - milvus

  web:
    image: langgenius/dify-web:latest

**Comment by applepieiris** [comment]
> MILVUS_URI

so should I also change the `MILVUS_URI: http://127.0.0.1:19530` defined in docker-compose.yaml to `MILVUS_URI=http://milvus-standalone:19530/` ?
localhost -> milvus-standalone?

**Comment by KyrieWang7** [comment]
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:38 +0000] "GET /console/api/workspaces/current/models/model-types/text-embedding HTTP/1.1" 200 13 "http://47.236.184.186:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
worker-1      | 2024-11-29 12:36:40.098 INFO [MainThread] [strategy.py:161] - Task tasks.document_indexing_task.document_indexing_task[dc6873e7-1ddd-44a0-a7ad-67bd52376bb5] received
worker-1      | 2024-11-29 12:36:40.098 DEBUG [MainThread] [base.py:149] - TaskPool: Apply <function fast_trace_task at 0x7f38f3a8a8e0> (args:('tasks.document_indexing_task.document_indexing_task', 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', {'lang': 'py', 'task': 'tasks.document_indexing_task.document_indexing_task', 'id': 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', 'parent_id': None, 'argsrepr': "('85e9d18e-c95c-403f-bb3e-be573f35ac63', ['1d0cd930-a3b6-49cc-9a79-deaf4ac4b13a'])", 'kwargsrepr': '{}', 'origin': 'gen62@304be3797814', 'ignore_result': True, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}, 'properties': {'correlation_id': 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', 'reply_to': '82838031-1f18-39d3-8605-975e17322089', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'dataset'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': 'b4967e74-3c9d-4ae6-9b1a-7954693d6f2c'}, 'reply_to': '82838031-1f18-39d3-8605-975e17322089',... kwargs:{})
worker-1      | 2024-11-29 12:36:40.102 INFO [Dummy-10] [document_indexing_task.py:59] - Start process document: 1d0cd930-a3b6-49cc-9a79-deaf4ac4b13a
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:40 +0000] "POST /console/api/datasets/init HTTP/1.1" 200 1272 "http://47.236.184.186:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:40 +0000] "GET /console/api/datasets/85e9d18e-c95c-403f-bb3e-be573f35ac63/batch/20241129123640865508/indexing-status HTTP/1.1" 200 349 "http://47.236.184.186:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:40 +0000] "GET /console/api/datasets/process-rule?document_id=1d0cd930-a3b6-49cc-9a79-deaf4ac4b13a HTTP/1.1" 200 232 "http://47.236.184.186:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
worker-1      | Building prefix dict from the default dictionary ...
worker-1      | 2024-11-29 12:36:41.238 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:113] - Building prefix dict from the default dictionary ...
worker-1      | Dumping model to file cache /tmp/jieba.cache
worker-1      | 2024-11-29 12:36:41.747 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:146] - Dumping model to file cache /tmp/jieba.cache
worker-1      | Loading model cost 0.567 seconds.
worker-1      | Prefix dict has been built successfully.
worker-1      | 2024-11-29 12:36:41.805 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:164] - Loading model cost 0.567 seconds.
worker-1      | 2024-11-29 12:36:41.805 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:166] - Prefix dict has been built successfully.
worker-1      | 2024-11-29 12:36:41.973 INFO [Dummy-10] [document_indexing_task.py:76] - Processed dataset: 85e9d18e-c95c-403f-bb3e-be573f35ac63 latency: 1.8738773688673973
worker-1      | 2024-11-29 12:36:41.992 INFO [Dummy-10] [trace.py:128] - Task tasks.document_indexing_task.document_indexing_task[dc6873e7-1ddd-44a0-a7ad-67bd52376bb5] succeeded in 1.8937109746038914s: None
sandbox-1     | [GIN] 2024/11/29 - 12:36:42 | 200 |      23.263µs |             ::1 | GET      "/health"
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:42 +0000] "GET /console/api/datasets/85e9d18e-c95c-403f-bb3e-be573f35ac63/batch/20241129123640865508/indexing-status HTTP/1.1" 200 369 "http://47.236.184.186:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
sandbox-1     | [GIN] 2024/11/29 - 12:37:12 | 200 |      36.206µs |             ::1 | GET      "/health"



I have configured the vector storage as Milvus, using Alibaba Cloud’s Milvus. Why is the data not written into Milvus when I create a knowledge base?

**Comment by KyrieWang7** [comment]
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:38 +0000] "GET /console/api/workspaces/current/models/model-types/text-embedding HTTP/1.1" 200 13 "http://xxxxxx:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
worker-1      | 2024-11-29 12:36:40.098 INFO [MainThread] [strategy.py:161] - Task tasks.document_indexing_task.document_indexing_task[dc6873e7-1ddd-44a0-a7ad-67bd52376bb5] received
worker-1      | 2024-11-29 12:36:40.098 DEBUG [MainThread] [base.py:149] - TaskPool: Apply <function fast_trace_task at 0x7f38f3a8a8e0> (args:('tasks.document_indexing_task.document_indexing_task', 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', {'lang': 'py', 'task': 'tasks.document_indexing_task.document_indexing_task', 'id': 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', 'parent_id': None, 'argsrepr': "('85e9d18e-c95c-403f-bb3e-be573f35ac63', ['1d0cd930-a3b6-49cc-9a79-deaf4ac4b13a'])", 'kwargsrepr': '{}', 'origin': 'gen62@304be3797814', 'ignore_result': True, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}, 'properties': {'correlation_id': 'dc6873e7-1ddd-44a0-a7ad-67bd52376bb5', 'reply_to': '82838031-1f18-39d3-8605-975e17322089', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'dataset'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': 'b4967e74-3c9d-4ae6-9b1a-7954693d6f2c'}, 'reply_to': '82838031-1f18-39d3-8605-975e17322089',... kwargs:{})
worker-1      | 2024-11-29 12:36:40.102 INFO [Dummy-10] [document_indexing_task.py:59] - Start process document: 1d0cd930-a3b6-49cc-9a79-deaf4ac4b13a
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:40 +0000] "POST /console/api/datasets/init HTTP/1.1" 200 1272 "http://xxxxxx:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:40 +0000] "GET /console/api/datasets/85e9d18e-c95c-403f-bb3e-be573f35ac63/batch/20241129123640865508/indexing-status HTTP/1.1" 200 349 "http://xxxxxx:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:40 +0000] "GET /console/api/datasets/process-rule?document_id=1d0cd930-a3b6-49cc-9a79-deaf4ac4b13a HTTP/1.1" 200 232 "http://xxxxxx:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
worker-1      | Building prefix dict from the default dictionary ...
worker-1      | 2024-11-29 12:36:41.238 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:113] - Building prefix dict from the default dictionary ...
worker-1      | Dumping model to file cache /tmp/jieba.cache
worker-1      | 2024-11-29 12:36:41.747 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:146] - Dumping model to file cache /tmp/jieba.cache
worker-1      | Loading model cost 0.567 seconds.
worker-1      | Prefix dict has been built successfully.
worker-1      | 2024-11-29 12:36:41.805 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:164] - Loading model cost 0.567 seconds.
worker-1      | 2024-11-29 12:36:41.805 DEBUG [Thread-11 (_process_keyword_index)] [__init__.py:166] - Prefix dict has been built successfully.
worker-1      | 2024-11-29 12:36:41.973 INFO [Dummy-10] [document_indexing_task.py:76] - Processed dataset: 85e9d18e-c95c-403f-bb3e-be573f35ac63 latency: 1.8738773688673973
worker-1      | 2024-11-29 12:36:41.992 INFO [Dummy-10] [trace.py:128] - Task tasks.document_indexing_task.document_indexing_task[dc6873e7-1ddd-44a0-a7ad-67bd52376bb5] succeeded in 1.8937109746038914s: None
sandbox-1     | [GIN] 2024/11/29 - 12:36:42 | 200 |      23.263µs |             ::1 | GET      "/health"
nginx-1       | 183.90.191.61 - - [29/Nov/2024:12:36:42 +0000] "GET /console/api/datasets/85e9d18e-c95c-403f-bb3e-be573f35ac63/batch/20241129123640865508/indexing-status HTTP/1.1" 200 369 "http://xxxxxx:8090/datasets/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
sandbox-1     | [GIN] 2024/11/29 - 12:37:12 | 200 |      36.206µs |             ::1 | GET      "/health"



I have configured the vector storage as Milvus, using Alibaba Cloud’s Milvus. Why is the data not written into Milvus when I create a knowledge base?
