### ISSUE TITLE
使用chatglm2模型对话时，suggestionList.map报错。

### ISSUE THREAD

**Issue by ifdown** [langgenius/dify#873]
Dify version: Cloud | Self Host

## Steps To Reproduce

1. 在选择chatglm2模型进行推理时，接口/console/api/universal-chat/messages/{id}/suggested-questions 返回的结果非预期的list，而是如下的结构：
            {
                "data": {
                    "question1": "What is the capital of France?",
                    "question2": "What is your favorite color?",
                    "question3": "What is your favorite type of music?"
                }
            }
 
应该是模型对prompt的理解不及chatgpt, 修改prompts.py的：
SUGGESTED_QUESTIONS_AFTER_ANSWER_INSTRUCTION_PROMPT = (
    "Please help me predict the three most likely questions that human would ask, "
    "and keeping each question under 20 characters.\n"
    "The output must be in JSON format following the specified schema:\n"
    "[\"question1\",\"question2\",\"question3\"]\n"
)
为：
SUGGESTED_QUESTIONS_AFTER_ANSWER_INSTRUCTION_PROMPT = (
    "Please help me predict the three most likely questions that human would ask, "
    "and keeping each question under 20 characters.\n"
    "The output must be **a array** in JSON format following the specified schema:\n"
    "[\"question1\",\"question2\",\"question3\"]\n"
)
，即在in JSON前面加上单词 a array 即可。

**Comment by takatost** [comment]
Thanks for feedback! It's been fixed.
