### ISSUE TITLE
After editing variables within an LLM node, some variables are lost when reopening the LLM node.

### ISSUE THREAD

**Issue by huangyafei** [langgenius/dify#8734]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

After editing variables within an LLM node, some variables are lost when reopening the LLM node.

https://lomohuang-image-hosting.s3.ap-northeast-1.amazonaws.com/uPic/Screen+Recording+2024-09-24+at+22.22.45.mov

**Comment by crazywoola** [comment]
Can not view this video. :)

**Comment by huangyafei** [comment]
@crazywoola  sorry, I have reconfigured the S3 permissions, and you should now be able to view the video.
