### ISSUE TITLE
0.8.0 also raise error  validation error for VariableAssignerNodeData

### ISSUE THREAD

**Issue by yuhp-zts** [langgenius/dify#8738]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Iteration node in chatflow:an error occurs.
{
  "iterator_selector": [
    {
      "company": "company 1",
      "tools": {
        "tool1": "tool 1",
        "tool2": "tool 2"
      }
    },
    {
      "company": "company 2",
      "tools": {
        "tool2": "tool2"
      }
    }
  ]
}

![image](https://github.com/user-attachments/assets/988c6d7f-1dac-4969-b4d9-04e42e8294ef)

![image](https://github.com/user-attachments/assets/92099364-b334-49c8-89b1-a7bca1baf12a)

2024-09-25 01:42:10,831.831 ERROR [Thread-96 (_generate_worker)] [graph_engine.py:184] - Unknown Error when graph running
Traceback (most recent call last):
  File "/app/api/core/workflow/graph_engine/graph_engine.py", line 145, in run
    for item in generator:
  File "/app/api/core/workflow/nodes/answer/answer_stream_processor.py", line 30, in process
    for event in generator:
  File "/app/api/core/workflow/graph_engine/graph_engine.py", line 233, in _run
    node_instance = node_cls(  # type: ignore
  File "/app/api/core/workflow/nodes/base_node.py", line 48, in __init__
    self.node_data = self._node_data_cls(**config.get("data", {}))
  File "/app/api/.venv/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for VariableAssignerNodeData
advanced_settings.groups.0.output_type
  Input should be 'string', 'number', 'object', 'array[string]', 'array[number]' or 'array[object]' [type=literal_error, input_value='any', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/literal_error

**Comment by yuhp-zts** [comment]
When I export the workflow and reload it, the error is gone.

**Comment by reatang** [comment]
1.1.0 Problems remain

<img width="1131" alt="Image" src="https://github.com/user-attachments/assets/e46d055d-67b5-4c2f-afa7-fdd4aef95bae" />

```
1 validation error for VariableAssignerNodeData advanced_settings.groups.0.output_type Input should be 'string', 'number', 'object', 'array[string]', 'array[number]' or 'array[object]' [type=literal_error, input_value='any', input_type=str] For further information visit https://errors.pydantic.dev/2.9/v/literal_error
```
