### ISSUE TITLE
When there are multiple pages in the knowledge base, an error is returned after entering the segment list

### ISSUE THREAD

**Issue by deific** [langgenius/dify#8742]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

When there are multiple pages in the knowledge base, an error is returned after entering the segment list
1、There are multiple pages and the third page has been redirected
![image](https://github.com/user-attachments/assets/1fccdd9f-eb90-48bc-bd25-b5b900c883fc)
2、entering the segment list of one document
![image](https://github.com/user-attachments/assets/dbbcf14f-5716-4450-8801-6b9366a37c99)
3、When returning, it did not return to the third page before entering, but directly returned to the first page
![image](https://github.com/user-attachments/assets/55c400d0-97e6-48ad-90ff-70b8b78b35cc)

### ✔️ Expected Behavior

Return to the page where you enter the segmented list of the document

### ❌ Actual Behavior

Fixed return to page 1

**Comment by crazywoola** [comment]
Thanks for the feedback, however we do not have much time on refining this part, we will take a look at this later.
