### ISSUE TITLE
The /v1/chat-messages interface is very slow

### ISSUE THREAD

**Issue by rechardwang** [langgenius/dify#8746]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Given that the issue of slow response times with the /v1/chat-messages API endpoint began after upgrading to version 0.8.2, it's likely that the upgrade introduced changes affecting performance

When using the console page for debugging, the speed is very fast.
![image](https://github.com/user-attachments/assets/8f480d45-f191-4bb6-a963-618660acb710)

It seems that when you use the /v1/chat-messages API endpoint, the response is slow, and this slowness is also reflected in the console logs. This indicates that the issue is likely not related to network. 

![image](https://github.com/user-attachments/assets/5a133119-6514-48a7-a566-c1d9152f93fe)

**Comment by rechardwang** [comment]
所以 /v1/chat-messages 速度提不起来吗？

**Comment by crazywoola** [comment]
不行，LLM 那边应该生成很快，但是计算token会变慢，暂时应该没有时间修复。

**Comment by njuptpz** [comment]
@crazywoola 这个问题最终是修复了还是没有修复？ 不修复压测都过不了。压测的时候加入dify chat-messages这个api封装是直通的2倍时间。

**Comment by yg2024** [comment]
同样遇到了这个问题，直接访问大模型与通过dify访问的时间差别有两倍

**Comment by Jimmy-L99** [comment]
现在怎么样了，我用的还是老版本0.15.3，貌似也遇到相同情况#16602。

**Comment by miser** [comment]
如果有解决 期待留言 我也遇到这个问题

**Comment by zfno111** [comment]
any response? 有人知道要如何解决么？0.15.3 运行半年后 速度由原来的10S变成了60S~
