### ISSUE TITLE
Change the default PDF parser to Unstructured PDF Partitioner

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#8751]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The Unstructured PDF Partitioner is a more advanced approach for parsing PDFs.

It can extract tables and images from PDFs. 

I propose changing the default parser to Unstructured approach.

https://docs.unstructured.io/open-source/core-functionality/partitioning#partition-pdf

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link #8695

**Comment by spencerwongfeilong** [comment]
Is this enhancement work in progress? It be great if unstructured can be used for pdf extraction. #8695 which is linked to this issue has been closed but it seems that is no longer worked upon.
