### ISSUE TITLE
Suggestion to Enable Conversation Log Viewing for Empty String Responses and Model Execution Exceptions

### ISSUE THREAD

**Issue by neotize** [langgenius/dify#8758]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It is suggested to support viewing the conversation logs in scenarios where the LLM replies with an empty string or when an exception occurs during LLM run execution. In some cases, such as when the LLM replies with an empty string after multiple 'goodbye' exchanges to end the conversation (as in the example), the logs are not viewable on the page, making it impossible to understand the details of each step.

### 2. Additional context or comments

{"event": "message", "task_id": "bc380e64-97e4-45a3-9c23-e1461e95098f", "id": "898c2daf-d2fa-408f-82d6-41464808053f", "message_id": "898c2daf-d2fa-408f-82d6-41464808053f", "conversation_id": "acd514bd-0383-4164-b34d-471d1f59951a", "mode": "advanced-chat", "answer": "", "metadata": {}, "created_at": 1727251867}
![下载](https://github.com/user-attachments/assets/eb9831d2-bd5a-4f1f-aaf0-1b19c6d54865)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by iamjoel** [comment]
We have changed a lot of chat codes in next coming feature. To avoid code conflicts, we'll solve this issus after the feature is  merged into main.
