### ISSUE TITLE
docker compose up -d does not start weaviate

### ISSUE THREAD

**Issue by ronnybox2000** [langgenius/dify#8760]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker-compose up -d cannot start weaviate. need to start docker-compose up -d weaviate manually. 
There is no problem clone a new project from github.

- The current environment docker compose up - d has not started weaviate
![image](https://github.com/user-attachments/assets/22d777be-3609-4f1e-9297-21766623eda7)

**Comment by crazywoola** [comment]
Duplicated
