### ISSUE TITLE
Dify knowledge base new paragraphs cannot be recalled

### ISSUE THREAD

**Issue by PolarPeak** [langgenius/dify#8768]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After the upgrade, historical knowledge base entries can be recalled, but newly added knowledge base paragraphs cannot be recalled, although annotated data can be retrieved.

![image](https://github.com/user-attachments/assets/d89db831-4f9f-4b8b-aa06-e20a16fb1d63)
Historical knowledge base entries can be recalled normally.

![image](https://github.com/user-attachments/assets/b2f0beb6-8e08-4a7a-b1a6-c3336cd22209)
![image](https://github.com/user-attachments/assets/d00cb72f-9e4e-431a-a9c4-11555edcb616)
Newly added paragraphs cannot be recalled properly.

### ✔️ Expected Behavior

I hope that both newly added and historical paragraphs can be recalled properly, as they were before.

### ❌ Actual Behavior

After the upgrade, historical knowledge base entries can be recalled, but newly added knowledge base paragraphs cannot be recalled, although annotated data can be retrieved.

**Comment by PolarPeak** [comment]
@dosu How do I do that specifically?

**Comment by PolarPeak** [comment]
Creating a new knowledge base also fails to recall entries.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8667
