### ISSUE TITLE
405 Method Not Allowed Error - POST Request Being Sent as GET in Axios

### ISSUE THREAD

**Issue by lucelsbyleverageAI** [langgenius/dify#8769]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Setup a self-hosted Dify version using elestio self hosting
2. Forked the conversation web apo repo to self host my own web app
3. Deployed locally and tried to have a conversation using my Dify web app API
4. When using the chat-messages endpoint, I get an error as the API request appears to be sent as a GET request and not a POST request, resulting in a 405 error

**Error Log:**
⨯ [AxiosError]: Request failed with status code 405
    at eL (/app/.next/server/chunks/110.js:1:48728)
    at y.<anonymous> (/app/.next/server/chunks/110.js:3:8818)
    at y.emit (node:events:513:28)
    at y._processResponse (/app/.next/server/chunks/110.js:1:19843)
    at ClientRequest._onNativeResponse (/app/.next/server/chunks/110.js:1:14452)

**Initial Request Config:**
method: 'POST',
url: '/v1/chat-messages',
headers: {
  Authorization: 'Bearer [REDACTED]',
  'Content-Type': 'application/json'
},
data: {
  "inputs": {},
  "query": "hello",
  "user": "user_[REDACTED]",
  "response_mode": "streaming",
  "files": null
}

**Actual Request**: Despite the configuration explicitly setting the method as POST, the actual request being sent looks like this:
GET /v1/chat-messages HTTP/1.1
Host: dify-ll9md-u18694.vm.elestio.app
Authorization: Bearer [REDACTED]
User-Agent: axios/1.7.7
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive

### ✔️ Expected Behavior

The POST request should be sent to /v1/chat-messages, and a successful response should be returned.

### ❌ Actual Behavior

The request is being sent as GET instead of POST, resulting in a 405 Method Not Allowed error from the API.

**Comment by crazywoola** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405, please check the nginx settings.
