### ISSUE TITLE
TavilySearch Unable to connect, reporting a 400 error

### ISSUE THREAD

**Issue by ceozyg3** [langgenius/dify#8772]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Hello,
I am using your DIY to create an AI application. I intend to call TavilySearch in dify.ai. But after multiple attempts, the following errors were displayed.
========
Failed to invoke tool: 400 Client Error: Bad Request for url:  https://api.tavily.com/search
========
At present, I cannot find the reason. How can I use this API correctly?

Attached is the attached image:
![Tavi搜索报错](https://github.com/user-attachments/assets/f564ef5f-4b88-422f-b7a0-9e0d307056f1)

Thank!

### ✔️ Expected Behavior

Can use TavilySearch's search function normally in DifyAI

### ❌ Actual Behavior

Failed to invoke tool: 400 Client Error: Bad Request for url: https://api.tavily.com/search

**Comment by ceozyg3** [comment]
Thank you for your reply!
But I couldn't find any further adjustments on the page. Obviously, these configurations are clear at a glance. Could you please help me take a look and guide me on how to adjust them?
√The API key is correct
√ Has not exceeded the speed limit of TavilySearch API
√The TavilySearch official website shows that these deductions were successful, but they all reported an error of 400

![搜索错误2](https://github.com/user-attachments/assets/3870c1d2-cab3-4f05-bfc0-f0bfe68b98cb)

**Comment by ceozyg3** [comment]
May I ask if there is a human customer service available? I have already set up everything you said correctly, is there still an error

**Comment by hjlarry** [comment]
I can't reproduce your problem, and I also use the cloud version of dify:

![image](https://github.com/user-attachments/assets/4b62168c-e7b5-4fc9-b5b2-0addebf4d15a)

**Comment by ceozyg3** [comment]
I just inputted Tavi-API without making any other configurations. What configurations do I need to make to succeed?

**Comment by ceozyg3** [comment]
![搜索测试1](https://github.com/user-attachments/assets/819f661b-e8b5-4ae3-bd16-c5dccc07a71f)
![搜索测试2](https://github.com/user-attachments/assets/60258ab5-017a-4596-85b5-7a690386aa68)
![搜索测试3](https://github.com/user-attachments/assets/9dc9c046-81f2-4a9d-b22d-53e9ca511a47)

**Comment by hjlarry** [comment]
I haven't do anything else, just use the default settings

**Comment by ceozyg3** [comment]
That's too strange. It's been like this since yesterday

**Comment by ceozyg3** [comment]
Are you using Tavi's free API? A plan of free month/1000?

**Comment by hjlarry** [comment]
> Are you using Tavi's free API? A plan of free month/1000?

yes
