### ISSUE TITLE
Support Contextual Retrieval

### ISSUE THREAD

**Issue by Weaxs** [langgenius/dify#8776]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

https://www.anthropic.com/news/contextual-retrieval

```
<document> 
{{WHOLE_DOCUMENT}} 
</document> 
Here is the chunk we want to situate within the whole document 
<chunk> 
{{CHUNK_CONTENT}} 
</chunk> 
Please give a short succinct context to situate this chunk within the overall document for the purposes of improving search retrieval of the chunk. Answer only with the succinct context and nothing else. 
```

![image](https://github.com/user-attachments/assets/ac1fa0c5-3066-45cb-b926-f748bae6229d)

### 2. Additional context or comments

have 2 problem:

1. should support change llm for explaining the chunks, maybe can use system llm in the beginning.
2. If file content context large than max context size which llm supported, maybe not explain/summarize automatically ?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by tobegit3hub** [comment]
What is the current implementation progress of contextual retrieval? @Weaxs 

We are really interested in this feature and we would like to help to implement this.

**Comment by FreshLucas-git** [comment]
@Weaxs Hi. Is any update in this feature?

**Comment by Weaxs** [comment]
> @Weaxs Hi. Is any update in this feature?

sorry, I do not start this feature yet.

I will try to figure it out before Nov. , and submit pr and review maybe ... Dec.
I’ll try as soon as possible. 🥺

**Comment by Weaxs** [comment]
### user chooses support contextual-retrieval 
1. user chooses to enabel [contextual-retrieval] in front-end step-two
2.  save rule in DatasetProcessRule (table: dataset_process_rules)

![image](https://github.com/user-attachments/assets/b2f7b77e-e623-4317-9166-8bc0d3492671)

### document upload and process
1. add `ContextualRecursiveCharacterTextSplitter` for contextual-retrieval text splitter  (call `_text_splitter_instance.split_text`)
2. text splitter by _text_splitter_instance with token - 50~100
3. assemble prompt with total document and chunk, and call `summarize_model_instance` for summarize contextual message (this will consume system llm tokens)
4. joint the summary with the chunk to form a new chunk

![image](https://github.com/user-attachments/assets/f1dedb8a-c716-4d4b-843a-43da3d1b113d)


### other problems

-  user edit and update chunk after upload and index
Without processing. 
The chunk will change to appear as edited by the user, with no additional processing.

- tokens which joint the whole document and chunk exceeds summarize model max_tokens
maybe call a new api in front-end step-two for telling user can not support  contextual-retrieval when use current system llm
