### ISSUE TITLE
Using Vision model "minicpm-v:8b-2.6-q4_K_M" with ollama, chat message raised error message

### ISSUE THREAD

**Issue by HorseLuke** [langgenius/dify#8777]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Deploy ollama 0.3.12 
2. Pull Vision model "minicpm-v:8b-2.6-q4_K_M"
```
ollama run minicpm-v:8b-2.6-q4_K_M
```
3. Go to dify 0.8.3 -> add new provider, add this vision model with ollama definition. 
4. Create blank app using this vision model.
5. In "Studio" "Orchestrate" page, change vision setting -> Resolution to Low.
6. Upload image, then chat in "Debug and Preview"

### ✔️ Expected Behavior

Chat will output normal from start to end.

### ❌ Actual Behavior

Chat output normal at first time, but then stop and clear output text, then it raised error at the top right of the page, saying:

```
Error: Input [TextPromptMessageContent(type=<PromptMessageContentType.TEXT: 'text'>, data='图片表述什么内容？'), ImagePromptMessageContent(type=<PromptMessageContentType.IMAGE: 'image'>, data='data:image/jpeg;base64,/9j/4AAQSkZJRgA...[ignore]...', detail=<DETAIL.LOW: 'low'>)] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.
```

Attach is from docker logs after setting DEBUG=true

[dify-ollama-error-minicpm-v.zip](https://github.com/user-attachments/files/17134057/dify-ollama-error-minicpm-v.zip)

**Comment by HorseLuke** [comment]
@dosu Based on your context, I can not find anything that can change ```content``` field in "Orchestrate" page.

However, if I add a sentense in "Instructions" textarea, then the error disappear.  "Instructions" textarea is described as these text:

```
Prompts guide AI responses with instructions and constraints. Insert variables like {{input}}. This prompt won't be visible to users.
```

What does "Instructions" textarea used in ```content``` field? Is this a bug when "Instructions" textarea is empty?

**Comment by Kimdow220807** [comment]
I also encountered the same problem
