### ISSUE TITLE
Error Processing Requests Containing curl Commands in Code Blocks

### ISSUE THREAD

**Issue by daigo38** [langgenius/dify#8790]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

<img width="1170" alt="スクリーンショット 2024-09-26 15 05 41" src="https://github.com/user-attachments/assets/d10b0f34-7d68-4057-a802-1aaf8d1e3e33">

1. Open the Web UI or use the API.
2. Submit a request that contains a `curl` command within a code block, such as:
   ```
   curl -X hello world
   ```
3. Observe that the request is not processed.

#### API Response:

```
Response {
  status: 403,
  statusText: 'Forbidden',
  headers: Headers {
    date: 'Thu, 26 Sep 2024 05:57:18 GMT',
    'content-type': 'text/html; charset=UTF-8',
    'transfer-encoding': 'chunked',
    connection: 'keep-alive',
    'x-frame-options': 'SAMEORIGIN, DENY',
    'referrer-policy': 'same-origin',
    'cache-control': 'max-age=15',
    expires: 'Thu, 26 Sep 2024 05:57:33 GMT',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=23xvFL%2F%2FN2D77cVRqkH9%2FyNEYZMh1hThyhJHI7WQZNcXZ0FIlKMSoO%2FirUvxB%2B4zwPxjQ2J3CHxzEULSbnLNK3F9EwWbDMh2ZZPuF2EfB9S5wWCdaYhdiHMX5VjV"}],"group":"cf-nel","max_age":604800}',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    vary: 'Accept-Encoding',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    'x-content-type-options': 'nosniff',
    server: 'cloudflare',
    'cf-ray': '8c9104046a211a19-KIX',
    'content-encoding': 'br'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: false,
  redirected: false,
  type: 'basic',
  url: 'https://api.dify.ai/v1/chat-messages'
}

```

### ✔️ Expected Behavior

Requests containing `curl` commands within code blocks should be processed successfully, or a clear error message should be displayed in the Web UI explaining why the request cannot be processed.

### ❌ Actual Behavior

Requests that include `curl` commands in a code block fail to be processed, with no error message displayed in the Web UI. When using the API, the request returns a 403 Forbidden error.

**Comment by crazywoola** [comment]
I think it's block by the Cloudflare side, it will ban some dangerous actions that contain harmful content like sql injections and direct curl command.
