### ISSUE TITLE
API interface to get the next round of problem suggestions, the interface sometimes returns a different structure

### ISSUE THREAD

**Issue by 1192603654** [langgenius/dify#8795]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/90ea1c3f-9825-4b55-97ec-f53fd285b1b1)

The JSON structure may appear when the actual call is made

![1727339198788](https://github.com/user-attachments/assets/0cf5ae44-b43a-4892-afa1-b90e30f7e6ac)

**Comment by crazywoola** [comment]
It depends on what llm you choose.

**Comment by 1192603654** [comment]
![image](https://github.com/user-attachments/assets/575408f1-bc17-4748-83de-1a2351266cd5)
It uses workflow orchestration, ChatGPT-4O's LLM
