### ISSUE TITLE
The pg database running inside docker container  fails to start up after  Host computer restarting

### ISSUE THREAD

**Issue by GangLiCN** [langgenius/dify#8796]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Issue:  
    I have a local dify web app running on windows based VM instance(Ubuntu 22.04 for WSL2), 
Unfortunately this env is not ready after the VM box restarts(because Host laptop shuts down every day)

Error logs:
    From the output of "docker-compose logs",  it appears that postgreSQL database fails to start up
due to invalid checkpoint record .

Analysis:
     It looks that this is caused by pgdb's abnormal shutdown.  But  I can't find any official document talking
about this.  So, Does it mean  "
User must shutdown database(for container "dify_db" usage) normally and do
a full backup in case  the database may not start up correctly " ?

### ✔️ Expected Behavior

Better pg database backup and recovery strategy especically for docker or k8s env.

### ❌ Actual Behavior

    The PostgreSQL database used by app is crashed and can not be recovered unless 
you have a full database backup or have correct and complete WAL log files for recovery.

![dify_docker_pgdb_env_crashed_after_reboot](https://github.com/user-attachments/assets/71505017-c12a-4407-9c0e-da414b3f0816)

**Comment by crazywoola** [comment]
You can manually backup the db by using the pgdump or other tools. 
Sorry we do not provide a. backup strategy for community version.
This is a system-specific problem, we only make sure it can pass the the CI.

**Comment by GangLiCN** [comment]
No, I still think this is a very "bad"  stability issue.   Is it a must-to-do job that user must shutdown pg database 
 before closing VM ?   If yes. I would say this is a very "bad"  architecure...

**Comment by kurokobo** [comment]
@crazywoola @GangLiCN 
Hi, sorry for adding a new comment to the closed issue, but what do you think about making `stop_grace_period` configurable, since Docker sends `SIGKILL` 10 seconds after `SIGTERM` by default?

- https://docs.docker.com/reference/compose-file/services/#stop_grace_period

I mean, during the shutdown of your PC, if your PSQL takes more than 10 seconds to shut down, it will be killed by `SIGKILL`, which may cause data corruption. Docker can wait more than 10 seconds before sending `SIGKILL` by increasing `stop_grace_period`.
