### ISSUE TITLE
how to import the third packages，ModuleNotFoundError: No module named 'pymysql' error: exit status 255

### ISSUE THREAD

**Issue by dingidng** [langgenius/dify#8797]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.First I went into the sanbox container and installed mysql
pip install pymysql

```
anyio              4.4.0
certifi            2024.8.30
charset-normalizer 3.3.2
exceptiongroup     1.2.2
h11                0.14.0
httpcore           1.0.5
httpx              0.27.2
idna               3.8
Jinja2             3.1.4
MarkupSafe         2.1.5
pip                23.0.1
PyMySQL            1.1.1
PySocks            1.7.1
requests           2.32.3
setuptools         65.5.1
sniffio            1.3.1
socksio            1.0.0
typing_extensions  4.12.2
urllib3            2.2.2
wheel              0.44.0
```
2.Entering python verifies that import pymysql is OK

3.But I went to the front-end page, used the code execution module, and reported an error：

No module named 'pymysql' error: exit status 255

### ✔️ Expected Behavior

How to solve please give me a detailed case

### ❌ Actual Behavior

No module named 'pymysql' error: exit status 255

**Comment by dingidng** [comment]
```
Run failed: Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
sock = socket.create_connection(
File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
raise err
File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/sandbox/sandbox-python/tmp/41da4196_adf7_4fa0_a725_50afabb2ed90.py", line 48, in <module>
File "<string>", line 7, in <module>
File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 361, in init
self.connect()
File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '10.80.2.195' ([Errno 101] Network is unreachable)")
error: exit status 255
```
I encountered a new error, remote mysql cannot be linked, but it can be successfully operated on my local computer

**Comment by Victoriaheiheihei** [comment]
can it work with the method mentioned before?

**Comment by Modas-Li** [comment]
> Duplicated

duplicated with which issue, please give us a link, thx
