### ISSUE TITLE
Could answer node support preview multiple images (now support only one image) ?

### ISSUE THREAD

**Issue by nadazero** [langgenius/dify#8804]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![2024-09-26_105351](https://github.com/user-attachments/assets/c3dd3b86-ef27-40c8-b9c5-10b1ec7914d7)
Now I use stable_diffusion tool to produce multiple images in one time,  and answer node could receive array[File] params, 
but I find it could support show only one image, it is inconvenient for generating previews of multiple images.
I hope Dify could support this function.
In another way, could you tell me which code file related with this function? I think I could support it on my local dev environment first.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/445497cf892ee0caaba80c55032810e579a4507e/web/app/components/base/markdown.tsx
