### ISSUE TITLE
Suggestions for making model safety levels adjustable

### ISSUE THREAD

**Issue by Smashhhhhhhhhh** [langgenius/dify#8805]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Following the configuration of Gemini, I consistently encounter security errors. I request the implementation of configurable security levels, allowing users to adjust the security level to the minimum possible setting. This would effectively minimize model invocation errors.

Furthermore, Gemini has recently introduced numerous cost-effective models, including Gemini 1.5 flash 002. I urge your company to expedite the release of configuration options enabling the utilization of these new models. Thank you.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We have a fix regarding this similar issue https://github.com/langgenius/dify/issues/8717
