### ISSUE TITLE
Need to add a prefix  (passage) for embedding model (NIM)

### ISSUE THREAD

**Issue by lschaupp** [langgenius/dify#8807]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Deploy NIM as a container with a embedding model
Setup Dify -> NIM requires "passage" variable as part of the query

### ✔️ Expected Behavior

The embedding model API works

**Comment by crazywoola** [comment]
What's the error message?

**Comment by lschaupp** [comment]
More information:
- NIM API endpoints require a specific parameterization as part of the request including "passage" parameter.
- Currently DIFY does not support to customize how the request is sent to the endpoint.

Dify needs to implement a filed to customize the request that is being made to the custom endpoint.
