### ISSUE TITLE
Cannot add openai compatible stt model.

### ISSUE THREAD

**Issue by tetyoka** [langgenius/dify#8811]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Just add OpenAI-API-compatible Speech2text model.

I'm using [faster-whisper-server](https://github.com/fedirz/faster-whisper-server) for local OA-compatible API server.
This server is running on another docker container in same computer.

It looks like every API request was succeeded. However, Speech2text model does not appear in model list.
![image](https://github.com/user-attachments/assets/65be23aa-3537-4ce1-9297-fead04328849)

It may be caused by my local whisper server. But since Dify app tells me "Operation successful", it should be Dify's bug.
![image](https://github.com/user-attachments/assets/e64d5ce3-35dc-45a6-839d-bb361dcb931b)

### ✔️ Expected Behavior

STT model appear in model list. If operation failed, I get notification.

### ❌ Actual Behavior

All process looks like succeeded. STT model does not appear.

**Comment by crazywoola** [comment]
I think you need to refresh the page to see the newly added model.

**Comment by tetyoka** [comment]
I did. The model does not appear.

**Comment by crazywoola** [comment]
![QQ_1727361096875](https://github.com/user-attachments/assets/c63a9423-d4ef-4dbe-9bd1-c56a84b88c9f)

Here？

**Comment by tetyoka** [comment]
![image](https://github.com/user-attachments/assets/aca7c2c7-6bfb-4b70-aaf4-6f7d8d1a2097)

**Comment by tetyoka** [comment]
Despite my STT situation, I can add OA-compatible LLM API.
![image](https://github.com/user-attachments/assets/b2182537-f57c-4fd2-a745-413aa7abd185)
LLM API is running on another computer.

**Comment by tetyoka** [comment]
I updated Dify to 0.9.1. It still happen.

**Comment by zhao85** [comment]
that's because current openai-api-compatible/openai code of speech2text has not implement get_customizable_model_schema method. I have copy the code from localai to fix it.

**Comment by tetyoka** [comment]
I will try your patch!

**Comment by andresvidal** [comment]
Thanks for the awesome project! I'm not sure if this is related, but I keep getting an error from OpenAI models host in a different base_url. When I run the same "workflow" with Ollama it works but when I swap it out for an OpenAi version I get this: 

**using OpenAi with a different host api**
[openai] Error: 1 validation error for LLMResultChunk model Input should be a valid string [type=string_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.9/v/string_type

**Using Ollama with a different host**
{ "text": "", ..., "finish_reason": "Non-JSON encountered.", ...}

**Comment by sean-escaped** [comment]
> Thanks for the awesome project! I'm not sure if this is related, but I keep getting an error from OpenAI models hosted in a different base_url. When I run the same "workflow" with Ollama Llama3.2 it works but when I swap it out for an OpenAi version I get this:
> 
> **using OpenAi with a different host api** [openai] Error: 1 validation error for LLMResultChunk model Input should be a valid string [type=string_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.9/v/string_type
> 
> **Using Ollama with a different host api** { "text": "", ..., "finish_reason": "Non-JSON encountered.", ...}

I have the same issue
