### ISSUE TITLE
Why file type data cannot be processed between nodes?

### ISSUE THREAD

**Issue by HaiShin** [langgenius/dify#8812]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I use drawing tools, such as chart; DALL-E, the output file type data cannot directly extract the URL, which makes it impossible for me to convert it into markdown format data output. At the same time, when these drawing tools are embedded in the workflow, they cannot be used as results in the end node, which is very difficult to use.

### 2. Additional context or comments

I think file type data can be converted to json to facilitate subsequent operations.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/5346 

I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
