### ISSUE TITLE
Output Variables are not available to all node

### ISSUE THREAD

**Issue by rabbitrepo** [langgenius/dify#8813]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

<img width="1047" alt="Screenshot 2567-09-26 at 21 45 58" src="https://github.com/user-attachments/assets/3100754e-a28a-49d3-9bf9-02fae6c77102">
-- The entire flow --

<img width="886" alt="Screenshot 2567-09-26 at 21 53 13" src="https://github.com/user-attachments/assets/11cdf76a-7a66-4dff-8114-173bdd834f48">
Having the CODE node at the start of the flow. Set the Output Variables.

<img width="887" alt="Screenshot 2567-09-26 at 21 53 29" src="https://github.com/user-attachments/assets/e924e92a-75ec-4cec-88f5-ff87766fd5dd">
The Output Variables are not accessible to other nodes.

<img width="889" alt="Screenshot 2567-09-26 at 21 54 21" src="https://github.com/user-attachments/assets/3aae5e92-01ab-4803-809d-96defd2d692f">
The Output Variables only accessible to the END node.

### ✔️ Expected Behavior

The Output Variable should be available to all node afterwards.

### ❌ Actual Behavior

The Output Variables only accessible to the END node.

**Comment by rabbitrepo** [comment]
Allowing this would make more complex workflows possible and improve Dify's capability by a lot. Hopefully, we can support this soon! 🥺

**Comment by crazywoola** [comment]
This is not a bug, actually it is by design feature. For example, the LLM node accepts the string as prompt, but somehow you passed an image or a file to it in the prompt(it should be in other parameters), then it will not be recognized at all, and it will introduce more complex scenarios.
