### ISSUE TITLE
If user input too long, the conversation can not display all the input

### ISSUE THREAD

**Issue by sideef5ect** [langgenius/dify#8815]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

send a long text with code, the user message can not be displayed correctly, the response from AI is good.
<img width="1348" alt="image" src="https://github.com/user-attachments/assets/f44e6a97-2920-4b45-9120-bbf13099422c">
<img width="873" alt="image" src="https://github.com/user-attachments/assets/ec0e333e-799d-4f55-a731-3f1ccbfb46ee">

### ✔️ Expected Behavior

The user message should also be well formatted.
<img width="879" alt="image" src="https://github.com/user-attachments/assets/fd13cff2-f5fc-40e3-b76e-7adba72b68e7">

BTW, is it possible to also have the copy button for user messages? the user message should be treated as the same of the ai messages? Why there is no copy button and the play button for user messages?

### ❌ Actual Behavior

can not review the user messages because of bad formatting.

**Comment by crazywoola** [comment]
Can you provide some example texts?

**Comment by sideef5ect** [comment]
```
fields = "31,55,58,70,71,73,74,75,76,77,78,79,80,82,83,84,85,86,87,88,6004,6008,6070,6072,6073,6119,6457,6508,6509,7051,7057,7058,7059,7068,7084,7085,7086,7087,7088,7089,7094,7184,7219,7220,7221,7280,7281,7282,7283,7284,7285,7286,7287,7288,7289,7290,7291,7292,7293,7294,7295,7296,7308,7309,7310,7311,7607,7633,7635,7636,7637,7638,7639,7644,7655,7671,7672,7674,7675,7676,7677,7678,7679,7724,7681,7682,7683,7684,7685,7686,7687,7688,7689,7690,7694,7695,7696,7697,7698,7699,7700,7702,7703,7704,7705,7706,7707,7708,7714,7715,7718,7720,7741,7762,7768,7920,7921"

```

example
