### ISSUE TITLE
Issue with DIFY When Orchestrating Workflows Involving Visual VL Models and Standard Text Models

### ISSUE THREAD

**Issue by svcvit** [langgenius/dify#8824]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm trying to implement a branching logic in the workflow where regular text content is processed by a standard large language model (LLM), and image content is processed by a visual VL model. However, the system parameter sys.files cannot be referenced within the if branch.

To work around this, I added a keyword "image" to sys.query. If this keyword is present, the workflow will use the visual VL model.

The workflow functions correctly during the first round of conversation. However, in the second round, which only involves text, an error occurs: Run failed: 'TextPromptMessageContent' object has no attribute 'text'.

Reference image for the first round of conversation:

![Xnip2024-09-27_10-29-21](https://github.com/user-attachments/assets/fcafb944-33e5-4e44-8370-19dd6b7d460d)

Reference image for the second round of conversation:

![Xnip2024-09-27_10-29-38](https://github.com/user-attachments/assets/520d505a-2487-475c-b402-c45bb65e529a)

### ✔️ Expected Behavior

Enhancement Request: I would like the if condition to support sys.files so that image-related tasks can be processed using different models.
Bug Fix: I'm also seeking a fix for the current bug.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/8777, not sure if is resolved.

**Comment by svcvit** [comment]
I tried pulling the latest merged code and switched to developer mode, but the error still persists.

If I first send an image with text, it follows the visual processing branch and responds correctly. However, when I then send a text-only message, it throws this error.

Additionally, there's another issue—sys.files can't be used as a condition in an if statement. Is there any way to optimize this?

![Xnip2024-09-27_12-33-14](https://github.com/user-attachments/assets/ab0946aa-8abc-42b6-b5ac-155bb0d0d526)

**Comment by free-cx** [comment]
> Link #8777, not sure if is resolved.

This bug is related to enabling memory in the node.

**Comment by laipz8200** [comment]
We'll provide full file-type support in future versions.
