### ISSUE TITLE
I want workflows to be annotated or saved without a connection

### ISSUE THREAD

**Issue by bingbing6** [langgenius/dify#8836]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I want to have the ability to comment nodes.Or it can be successfully saved when there is an unconnected node

### 2. Additional context or comments

![image](https://github.com/user-attachments/assets/7607505e-81c6-4602-8861-b86f793427a9)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Since we have introduce the parallel feature, it's hard to distinguish whether it's needed to be executed.  This will lead to contradiction behavior.

**Comment by bingbing6** [comment]
![image](https://github.com/user-attachments/assets/99ba5215-7554-433a-8ae9-f9524339f905)
Like ComfyUI is also a workflow, but it has a function to comment the current node, similar to comment code, or comment nodes such a function, should we consider adding comment function?

**Comment by bingbing6** [comment]
> Since we have introduced the parallel feature, it's hard to distinguish whether it's needed to be executed. This will lead to contradiction behavior.

Comment node functionality similar to ComfyUI
