### ISSUE TITLE
If input contains specific content when testing a single block, the test do not work

### ISSUE THREAD

**Issue by cowcomic** [langgenius/dify#8839]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

create a block test
input as "=1 group by"
the pattern of the string as "={num}{space}group{space}by{space}"
start run
it seems to be running, but not a really running. The result is still the result of the last valid input

![image](https://github.com/user-attachments/assets/74f06534-394f-4a9b-9b75-ae23edd11c05)

### ✔️ Expected Behavior

The result is still the result of the last valid input

**Comment by Wu-Jiayang** [comment]
You can try this:
https://github.com/langgenius/dify/pull/7955

**Comment by Wu-Jiayang** [comment]
This can solve your problem

**Comment by cowcomic** [comment]
> This can solve your problem

any plan for merge it to a version?

**Comment by Wu-Jiayang** [comment]
> > This can solve your problem
> 
> any plan for merge it to a version?

I opened a PR, but I'm not sure when they will merge it.

**Comment by Wu-Jiayang** [comment]
Maybe they will merge it only if we give them a push.
