### ISSUE TITLE
Share the answers/responses as links 

### ISSUE THREAD

**Issue by murtaza-motorwala** [langgenius/dify#8853]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Dify is great in creating RAG pipelines and chatflows. One thing that I feel missing is the ability to share the chat responses. Often users query for different things and once they get their answers (either from the RAG they built or just the LLMs), they want to share it with others. One way to do it right now is to simply copy/paste but that looses formatting especially the code blocks and introduces *** asterisk etc.. 

If we had the option to share the response (like how its done with ChatGPT), then that would be awesome. It would solve atleast two things - 
1st - Keep the formatting of the answers and share the whole chat/thread as is.
2nd - Save the time, effort and cost for the other user(s) to do the same task.

### 2. Additional context or comments

Sample link - 
https://chatgpt.com/share/66f6c3f8-0bb4-8004-808c-c6ffb2b3d253

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by dosnshcu** [comment]
how to use?

**Comment by dosnshcu** [comment]
Is it possible to achieve this effect in workflow? How should I do it?
