### ISSUE TITLE
bug in jinja2 join

### ISSUE THREAD

**Issue by Eternity714** [langgenius/dify#8856]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/e3db9dca-d795-44d6-ab9c-6216caaddbea)
1. use template node
2. add input var arg1 as Array[String]
3. set code as "{{ arg1|join('\n') }}"
4. set arg1 as [
    "123",
    "456",
    "789"
]
5. run node

### ✔️ Expected Behavior

output arg1 value with \n, example is 123\n456\n789

### ❌ Actual Behavior

error: operation not permitted

**Comment by Eternity714** [comment]
I have been set user: 1000:1000 in docker-compose.yaml，and set all folders as 777

**Comment by Eternity714** [comment]
{{ arg1|join }} is work and will output orrect answer, but in {{ arg1|join(‘\n’) }}, it is fail, also in {{ arg1|join(‘ ’) }} or {{ arg1|join(‘|’) }}

**Comment by Eternity714** [comment]
> Hey @Eternity714, I'm here to help you with any coding issues or questions you have! Let's tackle this together.
> 
> The issue you're encountering with the `join` filter in Jinja2 seems to be related to the specific characters used as separators. While `{{ arg1|join }}` works correctly, using `{{ arg1|join('\n') }}`, `{{ arg1|join(' ') }}`, or `{{ arg1|join('|') }}` results in an error.
> 
> This could be due to how the Jinja2 environment is configured or how the input is being processed within Dify. Here are a few steps to troubleshoot and potentially resolve the issue:
> 
> 1. **Check Jinja2 Version**: Ensure that the version of Jinja2 being used is compatible with the `join` filter. There might be known issues or limitations with certain versions.
> 2. **Environment Configuration**: Verify if there are any custom configurations or restrictions in the Jinja2 environment within Dify that might affect the `join` filter. The `DifySandbox` environment uses a whitelist strategy for system calls, file system isolation, and network isolation, which might impact template execution [[1]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/development/backend/sandbox/README.md)[[2]](https://github.com/langgenius/dify-docs/blob/main/jp/development/backend/sandbox/README.md).
> 3. **Template Syntax**: Ensure that the syntax used in the template is correct and that there are no hidden characters or encoding issues. Sometimes, copying and pasting code can introduce invisible characters that cause errors.
> 4. **Permissions and Execution Context**: Since you mentioned setting user permissions and folder access, double-check that the Docker container has the necessary permissions to execute the templates. The error "operation not permitted" might indicate a permissions issue.
> 
> If these steps do not resolve the issue, consider providing more detailed logs or error messages to help diagnose the problem further.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Based on the point 2, what steps should I follow to solve it?

**Comment by kkjinping** [comment]
It's still the same even in the latest version.
