### ISSUE TITLE
Issues with conversation_id in Dify API – Error "Conversation does not exist"

### ISSUE THREAD

**Issue by evertonresende** [langgenius/dify#8858]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to Reproduce
1. I set up an automation in **n8n** to send requests to the **/chat-messages** endpoint of the Dify API.
2. The first request is sent without a `conversation_id`, and I successfully receive a response with a valid `conversation_id`.
3. I capture this `conversation_id` and use it in a second request to continue the conversation.
4. The second request fails with a **404 - Conversation does not exist** error, even though the `conversation_id` is visible in the Dify dashboard.

#### First Request (works as expected):

```bash
curl -X POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer {API_KEY}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "What are the specs of the iPhone 13 Pro Max?",
    "response_mode": "streaming",
    "user": "user-id-example"
}' 
```

Response from First Request:
```
{
  "message_id": "1234",
  "conversation_id": "30082f1d-0a67-4bc7-9e5a-7907d1835cd2",
  "answer": "The iPhone 13 Pro Max has a 6.7-inch display, etc..."
}
```

Second Request (returns error):

```
curl -X POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer {API_KEY}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "Tell me more about the iPhone's camera?",
    "conversation_id": "30082f1d-0a67-4bc7-9e5a-7907d1835cd2",
    "response_mode": "streaming",
    "user": "user-id-example"
}'
```

Response from Second Request:

```
{
  "error": {
    "message": "Conversation does not exist",
    "code": "conversation_not_found"
  }
}
```
![Captura de tela 2024-09-27 222030](https://github.com/user-attachments/assets/37480dd7-ede0-47cd-a1f6-94ea57a843e4)
![Captura de tela 2024-09-27 220549](https://github.com/user-attachments/assets/a83257d1-9f4c-4384-babd-e9f4b62a87af)

### ✔️ Expected Behavior

The conversation_id should allow the conversation to continue, with the response based on the previous context.

### ❌ Actual Behavior

The API returns a 404 - Conversation does not exist error, even though the conversation_id is valid and visible in the Dify dashboard.

**Comment by crazywoola** [comment]
<img width="1627" alt="image" src="https://github.com/user-attachments/assets/15732652-39cb-4eb6-9c80-508659a3559c">
Still can not reproduce it. I am using both postman and curl command.

**Comment by evertonresende** [comment]
> <img alt="image" width="1627" src="https://private-user-images.githubusercontent.com/100913391/371720697-15732652-39cb-4eb6-9c80-508659a3559c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjMyMjQsIm5iZiI6MTcyNzUyMjkyNCwicGF0aCI6Ii8xMDA5MTMzOTEvMzcxNzIwNjk3LTE1NzMyNjUyLTM5Y2ItNGViNi05YzgwLTUwODY1OWEzNTU5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQxMTI4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmNjMjcxMzI0NWE0NzZmYmNiNDAwMmY0MmIwYWFiZTEzMDYzNzhiYmJkMGNhMjAzNmViNjIzZTAzYzgyMjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5PVyKl08xw8eIps7-3IuC6tdMSsYx3KuRtDKTNGO_cg"> Still can not reproduce it. I am using both postman and curl command.

![postmantest](https://github.com/user-attachments/assets/90a7d569-72db-44fc-8d74-d47495022cd9)

I tested the call in postman and unfortunately it doesn't work.

**Comment by crazywoola** [comment]
Are those 2 messages both send by postman or one is sent by postman and another is sent by the UI?
