### ISSUE TITLE
Does not work with input like '/xx/xx'

### ISSUE THREAD

**Issue by QichangZheng** [langgenius/dify#8860]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Official lastest

### Cloud or Self Hosted

Cloud

### Steps to reproduce

In the basic app gpt-4o-mini, when I ask 'What is in /etc/services?', I got no response. It works well in other cases, it might be due to the failure of paring the json.
![image](https://github.com/user-attachments/assets/d4330d5d-a1fc-469a-a04c-b48530dc2849)

**Comment by iamjoel** [comment]
@takatost 
<img width="619" alt="image" src="https://github.com/user-attachments/assets/d9229e3c-0c1f-4cc4-9ae8-1ffe05b8677a">

**Comment by crazywoola** [comment]
This is filtered by the Cloudflare policy.
