### ISSUE TITLE
The API call results for the workflow orchestration dialogue application cannot properly display the consumed token values and prices.

### ISSUE THREAD

**Issue by cabinai** [langgenius/dify#8873]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The API call results for the workflow orchestration dialogue application cannot properly display the consumed token values and prices.

**Comment by cabinai** [comment]
I use the formula blocking

**Comment by crazywoola** [comment]
Which model do you use? The provided information isn’t enough for us to investigate

**Comment by cabinai** [comment]
![image](https://github.com/user-attachments/assets/ea23c52c-8eaa-4419-a687-d9e778d5d96f)
![image](https://github.com/user-attachments/assets/ec782967-b022-4fc3-94f3-a1f970747f62)

**Comment by crazywoola** [comment]
Duplicated, we already fixed it, please wait for next release

**Comment by cabinai** [comment]
Can you give me an estimated time? Our dify-based product is coming soon and needs this feature. Or, can I pull now
