### ISSUE TITLE
Stopped by user.

### ISSUE THREAD

**Issue by 18600709862** [langgenius/dify#8874]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I created a long text generation workflow application and then ran it,
and the application stopped automatically.
log display:  Stopped by user.

timeout set:
docker-compose.xml
GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-3600}
API_TOOL_DEFAULT_CONNECT_TIMEOUT: ${API_TOOL_DEFAULT_CONNECT_TIMEOUT:-6000}
API_TOOL_DEFAULT_READ_TIMEOUT: ${API_TOOL_DEFAULT_READ_TIMEOUT:-3600}
environment
HTTP_REQUEST_MAX_CONNECT_TIMEOUT: 6000

### ✔️ Expected Behavior

run complete

### ❌ Actual Behavior

Start
43.843 ms
Generate Subtitles and Outlines
1.517K tokens · 31.743 s
Extract Subtitles and Outlines
139.945 ms
Iteration
19 m 28.879 s

3个迭代
Stopped by user.
LLM 3
41.141 s
Stopped by user.
![2024-09-29 08-02-06屏幕截图](https://github.com/user-attachments/assets/c86872d1-5788-4198-8e75-f13a1979f787)

**Comment by massif-01** [comment]
I had the same problem

**Comment by crazywoola** [comment]
Can you guys provide a minimal DSL to reproduce this issue?

**Comment by yuncengshangdepingyuan** [comment]
<img width="638" alt="屏幕截图 2024-10-10 172939" src="https://github.com/user-attachments/assets/0d5dc5d8-0067-4897-9f06-1a9c9f932413">
<img width="335" alt="屏幕截图 2024-10-10 173033" src="https://github.com/user-attachments/assets/dcf1ae92-c6ff-4837-9264-8ad1ddd26b14">
There seems to be a 20 minute\1200s run limit, what should I do with it?

**Comment by massif-01** [comment]
> <img alt="屏幕截图 2024-10-10 172939" width="638" src="https://private-user-images.githubusercontent.com/141716071/375315206-0d5dc5d8-0067-4897-9f06-1a9c9f932413.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjQwMTEsIm5iZiI6MTcyODU2MzcxMSwicGF0aCI6Ii8xNDE3MTYwNzEvMzc1MzE1MjA2LTBkNWRjNWQ4LTAwNjctNDg5Ny05ZjA2LTFhOWM5ZjkzMjQxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMjM1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTM1MjUwNWE2ZTQyODJkMGI3Y2YzMzNlZjY1NzllZGZjMmMzNjk1NDcwODM2YzE2MDJlZDViMDQzYTVjYzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BthmAV1MncuJczQhTeJy7o_1KPtDv086MS60Fk-D_0s"> <img alt="屏幕截图 2024-10-10 173033" width="335" src="https://private-user-images.githubusercontent.com/141716071/375315276-dcf1ae92-c6ff-4837-9264-8ad1ddd26b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjQwMTEsIm5iZiI6MTcyODU2MzcxMSwicGF0aCI6Ii8xNDE3MTYwNzEvMzc1MzE1Mjc2LWRjZjFhZTkyLWM2ZmYtNDgzNy05MjY0LThhZDFkZGQyNmIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMjM1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODQ0MWViNWJjMWYxZTI4NTE4NzFmMzMxZjgxODdlZjQ4ZDE4YTFhNGY0ZDcxMzE4ZmYyZDkyMzE5MTNiNGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dX0LLLtN2d_bkfIap8nl0GU8MdGl4AlMVFwn3zMyDEE"> There seems to be a 20 minute\1200s run limit, what should I do with it?

I've solved this problem by add "APP_MAX_EXECUTION_TIME: ${APP_MAX_EXECUTION_TIME:-12000}" in docker-compose.yaml

https://github.com/massif-01/dify/blob/main/docker/docker-compose.yaml

**Comment by yuncengshangdepingyuan** [comment]
> 

<img width="666" alt="屏幕截图 2024-10-11 100125" src="https://github.com/user-attachments/assets/74054dea-ed41-42f4-83cd-f2fb4ef47cb5">
thank you,and may be I can change this one ?

**Comment by massif-01** [comment]
> > 
> 
> <img alt="屏幕截图 2024-10-11 100125" width="666" src="https://private-user-images.githubusercontent.com/141716071/375600925-74054dea-ed41-42f4-83cd-f2fb4ef47cb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjk3MjgsIm5iZiI6MTcyODYyOTQyOCwicGF0aCI6Ii8xNDE3MTYwNzEvMzc1NjAwOTI1LTc0MDU0ZGVhLWVkNDEtNDJmNC04M2NkLWYyZmI0ZWY0N2NiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwNjUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWI2ZDI3MzNjYjRjY2MyYzk4MThkOWMzNTYxZWE4YjNhODIzM2ZmNDBjMTJhYTUzYTkwNmI5MGZiNmQ2OTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2v5OvFBh3lLwTx6GjO5i_6KwXvDAIZPZiDyVdzEKsp4"> thank you,and may be I can change this one ?

i have also changed this

**Comment by yuncengshangdepingyuan** [comment]
It's useless.I found that it has been written here:
<img width="293" alt="5" src="https://github.com/user-attachments/assets/eb5704ef-c776-410d-8732-ef607b55d70a">
<img width="434" alt="1" src="https://github.com/user-attachments/assets/9fbb0b1f-b0f8-4596-bc0a-27818fb9b9df">
it's ok now for me.

**Comment by detongz** [comment]
After changing env config, 'Stopped by user' still exists and stops my workflow.
![image](https://github.com/user-attachments/assets/8794af38-f104-4d0b-9dce-1736f61c4811)
![image](https://github.com/user-attachments/assets/669371df-ca86-4dbe-9353-edb3d8044fb5)

**Comment by yuncengshangdepingyuan** [comment]
Ensure that there is no work_flow_max_Execution_time=1200 elsewhere; Ensure that the container is restarted. If it doesn't work, there's nothing I can do.

**Comment by RandalTeng** [comment]
Found solution: you should **recreate** you container after change .env file. Like this:
``` shell
cd /path/to/dify/docker
vi .env
{change the (APP|WORKFLOW)_MAX_EXECUTION_TIME to as bigger enough you wished.}
```
And then, run command blow:
> docker compose up -d --force-recreate api worker worker_beat nginx

OR you have specific project name: 
> docker compose [-p dify] up -d --force-recreate api worker worker_beat nginx

Wait for seconds, run you workflow or chat apps.
