### ISSUE TITLE
unable to use sys.files in nodes of a workflow

### ISSUE THREAD

**Issue by delvin-sparkle** [langgenius/dify#8881]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

the same issue with

https://github.com/langgenius/dify/discussions/3370

 I selected the vision model gpt-4-turbo，and turned the vision switch at the bottom of LLM node on，but I still cannot use sys.files
 
 
![image](https://github.com/user-attachments/assets/ee6cda02-9fb1-4a9c-b5a6-7a780f136a70)

### ✔️ Expected Behavior

be able to use sys.files in a node

### ❌ Actual Behavior

unable to use sys.files in nodes of a workflow

**Comment by crazywoola** [comment]
See pinned issue, we are working on it
