### ISSUE TITLE
API function(variable call) maybe abnormal in general application

### ISSUE THREAD

**Issue by tigflanker** [langgenius/dify#8887]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I have set up the API in the web API extension, but it seems that it is not being effectively referenced when calling it.

This is the API code, service, and test call situation:
![微信截图_20240929161942](https://github.com/user-attachments/assets/dda894bb-17af-4279-b39d-f99ce20ad39a)

This is the API extension setup interface:
![微信截图_20240929163003](https://github.com/user-attachments/assets/8851e6b8-f525-4bac-83da-e00b7a13b410)

This is the general application's invocation interface, where I have not been able to successfully invoke it in the opening remarks and prompts:
![微信截图_20240929162013](https://github.com/user-attachments/assets/a5d3efc4-fdd8-4e21-822a-49171a2d7ad4)

**Comment by tigflanker** [comment]
@dosu I have already tested "point": "ping" and successfully received a response with "result": "pong". 
Now it appears that the service can pass the test, and the API can be set up successfully. 
The issue might be with the API invocation (variable reference) in the large language model application step.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/7520
