### ISSUE TITLE
Multi person collaborative workflow will be lost

### ISSUE THREAD

**Issue by mdxlCJ** [langgenius/dify#8888]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When multiple people collaborate on a DIY workflow, if others view and one person modifies, the person viewing will overwrite the modified content and lose it

### ✔️ Expected Behavior

When multiple people collaborate on a DIY workflow, if others view and one person modifies, the person viewing will overwrite the modified content and lose it

**Comment by mdxlCJ** [comment]
多人协同的时候，其他人查看日志，一人修改，会把修改的内容丢失

**Comment by mdxlCJ** [comment]
或者其他人看工作流的时候，会突然闪一下，导致更新的流程数据丢失

**Comment by Sakura4036** [comment]
It's currently designed to update pages automatically, so don't collaborate with multiple people or use a workflow at the same time.

**Comment by mdxlCJ** [comment]
是进入工作流应用的流程编排、包括查看日志也会处罚自动更新吗，目前有什么方式避免吗

**Comment by Sakura4036** [comment]
sorry, I don't know about that.
