### ISSUE TITLE
Rich text empty lines will be rendered as strings after introducing label switching nodes.

### ISSUE THREAD

**Issue by Bruse-Lee** [langgenius/dify#8899]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

<img width="718" alt="image" src="https://github.com/user-attachments/assets/b5febfd7-396f-41f5-a48a-51a04cae22a1">

### ✔️ Expected Behavior

The input label still renders normally after switching nodes back and forth.

### ❌ Actual Behavior

Enter labels in a blank line. After switching nodes back and forth, some labels will be rendered as strings.
<img width="718" alt="image" src="https://github.com/user-attachments/assets/8231ee39-f95c-4e70-b084-3625c6f22adb">

**Comment by Bruse-Lee** [comment]
> 嘿@Bruse-Lee！👋 我在这里帮助您解决错误、问题并成为贡献者。在等待人工维护者时，您可以随时问我任何问题。
> 
> 我找到了一个类似的问题，可能与您的问题有关。标题为“[工作流中节点变量显示异常](https://github.com/langgenius/dify/issues/6276)”的问题已关闭，最后更新于 2024 年 7 月 15 日。建议的解决方案是使用该`setWorkflowRunningData`函数重置工作流运行数据，这可能有助于正确重新渲染节点。
> 
> 以下是如何使用此功能的示例：
> 
> ```ts
> import { useWorkflowStore } from 'path/to/workflow/store';
> 
> const resetWorkflowRunningData = () => {
>   const setWorkflowRunningData = useWorkflowStore(state => state.setWorkflowRunningData);
>   setWorkflowRunningData({
>     resultTabActive: false,
>     resultText: '',
>     // Add other necessary fields here
>   });
> };
> 
> // Call this function when you detect the issue
> resetWorkflowRunningData();
> ```
> 
> 此外，在 Dify 0.8.3 版的工作流编辑器中来回切换节点后，您遇到的标签呈现为字符串的问题很可能是由于该`getHistoryLabel`函数造成的。当无法识别事件类型时，该函数会默认直接返回一个字符串，这可能导致标签呈现为字符串。
> 
> ```ts
> const getHistoryLabel = useCallback((event: WorkflowHistoryEvent) => {
>     switch (event) {
>       // ... other cases
>       default:
>         return 'Unknown Event'
>     }
>   }, [t])
> ```
> 
> 如果遇到未在 switch 语句中处理的事件类型，函数将返回字符串`'Unknown Event'`，这就是为什么有些标签被渲染为字符串[[1] ](https://github.com/langgenius/dify/issues/6276)[[2]](https://github.com/langgenius/dify/blob/main/web/app/components/workflow/hooks/use-workflow-history.ts)。
> 
> _[要继续与Dosu](https://dosu.dev)交谈，请提及@dosu。_

It seems that the related issues you mentioned have not been resolved.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8900
