### ISSUE TITLE
key 认证提示无效的key

### ISSUE THREAD

**Issue by dsbruce** [langgenius/dify#89]
您好, 我的open ai key 在dify 上验证提示无效, 但这个key是正常的, 请问这个是什么问题呢?

**Comment by takatost** [comment]
是云端版还是自部署的

**Comment by 2023Felix** [comment]
部署在ubuntu上的
<img width="530" alt="image" src="https://github.com/langgenius/dify/assets/127803749/b13c5b87-95cc-4f1b-adc1-c3bd081968ef">

**Comment by takatost** [comment]
https://github.com/langgenius/dify/issues/80#issuecomment-1552429998
可以看下这里，一般都是用了国内镜像地址导致的

**Comment by 2023Felix** [comment]
> [#80 (comment)](https://github.com/langgenius/dify/issues/80#issuecomment-1552429998) 可以看下这里，一般都是用了国内镜像地址导致的

谢谢，我试试
