### ISSUE TITLE
When using code node, I got an error. Got error code: -400. Got error msg: network is disabled, please enable it in the configuration

### ISSUE THREAD

**Issue by stephenlzc** [langgenius/dify#8900]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[exa_search.yml.zip](https://github.com/user-attachments/files/17179578/exa_search.yml.zip)
When I run the workflow, I got an error in the code.**Got error code: -400. Got error msg: network is disabled, please enable it in the configuration**.

Here is the tracing pics:

<img width="420" alt="image" src="https://github.com/user-attachments/assets/810d446e-fdde-4039-9adb-6b29dac0f9b1">

Obviously, it can be confirmed that my network is smooth when I use ChatGPT for operations, and it is also obvious that my python code does not need to be connected to the internet, so why am I still getting this error?

```
import json

def main(query: str, startPublishedDate: str) -> dict:
    json_data = {
        "query": query,
        "type": "neural",
        "category": "research paper",
        "numResults": 10,
        "useAutoprompt": True,
        "startPublishedDate": startPublishedDate,
        "contents": {
            "text": {
                "maxCharacters": 1000
            },
            "highlights": {
                "numSentences": 3,
                "highlightsPerUrl": 3
            }
            }
    }
    return {
        "result": json.dumps(json_data)
    }
```

Can you help me th clarify this issue?

**Comment by stephenlzc** [comment]
Thanks, after I revising the env file and docker compose file, I try to `docker compose down && docker compose up -d`, and i found the issue still exsit.

**Comment by stephenlzc** [comment]
And I tried to re-install all the docker by using a new folder, the issue still exist. @dosu

**Comment by crazywoola** [comment]
The network between containers and the network to the internet is quite different :)

> The error "network is disabled, please enable it in the configuration" persists because the `ENABLE_NETWORK` environment variable for the `sandbox` service is set to `true`, but the network configuration might not be correctly set up or enabled in the Docker Compose file.
> 
> Here is the relevant part of the `docker-compose.yaml`:
> 
> ```yaml
> sandbox:
>   image: langgenius/dify-sandbox:0.2.1
>   restart: always
>   environment:
>     ENABLE_NETWORK: 'true'
>     HTTP_PROXY: 'http://ssrf_proxy:3128'
>     HTTPS_PROXY: 'http://ssrf_proxy:3128'
>   networks:
>     - ssrf_proxy_network
> ```
> 
> Ensure that the `ssrf_proxy_network` is correctly defined and not causing any issues. The network is defined as:
> 
> ```yaml
> networks:
>   ssrf_proxy_network:
>     driver: bridge
>     internal: true
> ```
> 
> The `internal: true` setting means that the network is isolated and cannot access external networks. If the sandbox service needs to access external networks, you should remove the `internal: true` setting:
> 
> ```yaml
> networks:
>   ssrf_proxy_network:
>     driver: bridge
> ```
> 
> After making this change, restart your Docker Compose services to apply the new network configuration. Additionally, ensure that the `HTTP_PROXY` and `HTTPS_PROXY` environment variables are correctly set to allow network access through the proxy.
> 
> If the issue persists, ensure that your Docker environment meets the prerequisites for running Dify, as outlined in the Dify documentation. Specifically, verify that your Docker and Docker Compose versions are up to date and that your system meets the minimum requirements. Follow these steps to start the Docker containers:
> 
> 1. Navigate to the Docker directory in the Dify source code:
>    ```shell
>    cd dify/docker
>    ```
> 2. Copy the environment configuration file:
>    ```shell
>    cp .env.example .env
>    ```
> 3. Start the Docker containers:
>    
>    * If you have Docker Compose V2, use the following command:
>      ```shell
>      docker compose up -d
>      ```
>    * If you have Docker Compose V1, use the following command:
>      ```shell
>      docker-compose up -d
>      ```
> 
> Finally, check if all containers are running successfully:
> 
> ```shell
> docker compose ps
> ```
> 
> This includes 3 core services: `api / worker / web`, and 6 dependent components: `weaviate / db / redis / nginx / ssrf_proxy / sandbox`. Ensure that all services are up and running as expected [[1]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)[[2]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.yaml)[[3]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/docker-compose.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Try this answer.

**Comment by stephenlzc** [comment]
I have removed the setting like:
<img width="683" alt="image" src="https://github.com/user-attachments/assets/36bb3d65-fdef-442c-a6db-e599c29b019e">

<img width="637" alt="image" src="https://github.com/user-attachments/assets/4298d09a-8470-44e0-bfbf-b7c23455c73f">


But the promble still existed.
<img width="398" alt="image" src="https://github.com/user-attachments/assets/b698f969-33ef-4b66-8391-0c24dcddeb6d">

here is my docker-compose file:
[docker-compose.yaml.zip](https://github.com/user-attachments/files/17270031/docker-compose.yaml.zip)
