### ISSUE TITLE
DifY API is not bringing the conversation/session history

### ISSUE THREAD

**Issue by edrizo** [langgenius/dify#8910]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When we click view through DiFy itself, the conversation is complete. The session is being considered in the conversation.

However, when using the API call, this does not happen.

![image](https://github.com/user-attachments/assets/e290be73-0155-4746-81c1-27269846d94c)

![image](https://github.com/user-attachments/assets/0f9618ca-94e3-433e-995a-fee91bcbd402)

![image](https://github.com/user-attachments/assets/34a8115a-3b75-42ee-8533-6c1da0a10994)

### ✔️ Expected Behavior

API calls working with the conversation session being respected.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/d3b3e425-99f0-4466-a115-d3119ffd9f01)

All previous conversations do not appear in the session history.

**Comment by edrizo** [comment]
Endpoint used:

![image](https://github.com/user-attachments/assets/56f2b0d4-2e00-480b-b344-a59694ebd9e8)
![image](https://github.com/user-attachments/assets/ffe8c0e0-d7c6-4155-8bf0-2ac635e4c8b4)

**Comment by edrizo** [comment]
Chatbot:
![image](https://github.com/user-attachments/assets/32bd74f5-11d2-4485-9a1f-0ae75c5f36d5)

**Comment by edrizo** [comment]
> * **Retrieve the `conversation_id`** after the initial chat request.
> * **Use the same `conversation_id`** for subsequent requests to maintain the context of the conversation.

"Retrieve the conversation_id after the initial chat request.
Use the same conversation_id for subsequent requests to maintain the context of the conversation."

I'm doing this. The conversation_id is corret. But still have the issue.

**Comment by edrizo** [comment]
1) This is the first call:
![image](https://github.com/user-attachments/assets/e80c83b2-0429-4f16-bff9-62f246b9698a)
Then i get the conversation_id generated.

2) Now, with the id:

![image](https://github.com/user-attachments/assets/e7bf6349-9ac3-4944-af22-7b68ef085cd1)
![image](https://github.com/user-attachments/assets/e2d7096b-aeb0-4464-a57c-1522c4ea2b8f)
![image](https://github.com/user-attachments/assets/7bbfdfbd-92eb-43af-98e4-b842d50d2f8a)

3) Still the same

![image](https://github.com/user-attachments/assets/ea825322-f768-4211-851d-e9c2d4a8a61d)

**Comment by edrizo** [comment]
@dosu

**Comment by edrizo** [comment]
> 1. This is the first call:
>    ![image](https://private-user-images.githubusercontent.com/17660901/371938299-e80c83b2-0429-4f16-bff9-62f246b9698a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Njg4MjYsIm5iZiI6MTcyNzY2ODUyNiwicGF0aCI6Ii8xNzY2MDkwMS8zNzE5MzgyOTktZTgwYzgzYjItMDQyOS00ZjE2LWJmZjktNjJmMjQ2Yjk2OThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzE4NjkzMDY0ZjRlYjZkNGUwNTNlMTczYjc4MjIyNTQ3ZDEwODY0Nzg5MjY1MmZmMDNhYzE3N2Q3MmU3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EY9vb4EQHHODwt7MqjRO2FOLWQlDhoKOVYRFcFnIhkU)
>    Then i get the conversation_id generated.
> 2. Now, with the id:
> 
> ![image](https://private-user-images.githubusercontent.com/17660901/371938588-e7bf6349-9ac3-4944-af22-7b68ef085cd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Njg4MjYsIm5iZiI6MTcyNzY2ODUyNiwicGF0aCI6Ii8xNzY2MDkwMS8zNzE5Mzg1ODgtZTdiZjYzNDktOWFjMy00OTQ0LWFmMjItN2I2OGVmMDg1Y2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMTQ5M2ZhZmVhMzdkMWE4NWI2Nzc3MGJiZWIzNzE0MzFhMWE1MjAxMTZhZDBhNzkxNmEwYjQzM2UzZTFkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b77bi5b3902iT3Gv20AebCJSVKt0TG_swRp17-uAMrA) ![image](https://private-user-images.githubusercontent.com/17660901/371938727-e2d7096b-aeb0-4464-a57c-1522c4ea2b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Njg4MjYsIm5iZiI6MTcyNzY2ODUyNiwicGF0aCI6Ii8xNzY2MDkwMS8zNzE5Mzg3MjctZTJkNzA5NmItYWViMC00NDY0LWE1N2MtMTUyMmM0ZWEyYjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOThhN2YwZjZlNWIzMTg1ZDYyZTJjNzE1M2Y3MDE5ZmMwNDhmNWNhMzY0ZTU1YTQ5MjFmNjNkZTY2NTVkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gwrf9MTpglM_q74U2YzYNEbAUtUNBEUHcSQyJzhF8UA) ![image](https://private-user-images.githubusercontent.com/17660901/371939042-7bbfdfbd-92eb-43af-98e4-b842d50d2f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Njg4MjYsIm5iZiI6MTcyNzY2ODUyNiwicGF0aCI6Ii8xNzY2MDkwMS8zNzE5MzkwNDItN2JiZmRmYmQtOTJlYi00M2FmLTk4ZTQtYjg0MmQ1MGQyZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNjU3ZmRhOWU2MzNjZDQwMDExNWUyNTU5Y2E5ZmU1OWFiN2M0ZTk0NDlmOGE5ODA0NTdkZDVjNmIxZTA4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bS2Qi4gqD--UG_rzy8xLFVakRSWFmZj7JKVRdyARugk)
> 
> 3. Still the same
> 
> ![image](https://private-user-images.githubusercontent.com/17660901/371939309-ea825322-f768-4211-851d-e9c2d4a8a61d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Njg4MjYsIm5iZiI6MTcyNzY2ODUyNiwicGF0aCI6Ii8xNzY2MDkwMS8zNzE5MzkzMDktZWE4MjUzMjItZjc2OC00MjExLTg1MWQtZTljMmQ0YThhNjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YjQxYjVkMzE0YTA5ZDZhMjRjYjkxOThkMGRhYjM2ZTE4N2ZlOWQ1NThmZDgzZDNiN2M5ZmNhYzYwZTE1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C8YxAHw4vaV1-7xXa4-zSK4hDmtzgP4rNKaV7D1KZwE)

@dosu

**Comment by edrizo** [comment]
I did it. And still remains the issue.

**Comment by ramishi** [comment]
I have the same issue, not happening in the previous version. whats has changed?

**Comment by edrizo** [comment]
> I have the same issue, not happening in the previous version. whats has changed?

Which version?

I'm using cloud version. Not self hosted.

Weird.

**Comment by cuongphamduc** [comment]
I am having this problem too...

**Comment by ramishi** [comment]
confirm its only in cloud version. self-host version working fine even with the latest 0.8.3

**Comment by fujita-h** [comment]
I also confirmed this problem with the cloud version.
When looking at communications in the developer console, all history seems to remain, but it doesn't seem to be displayed on the history screen.

There was a difference in the way `parent_message_id` was assigned between the history in the regular chat UI and the history data in the API. I suspect this is due to a change in the way `parent_message_id` is handled.

**Comment by edrizo** [comment]
> confirm its only in cloud version. self-host version working fine even with the latest 0.8.3

Did you self hosted it? And the issue is not happening?

**Comment by eduardochaves1** [comment]
Also having the same problem, I'll buy a server so I self-host Dify due to this problem.

**Comment by braiaagency** [comment]
> Endpoint used:
> 
> ![image](https://private-user-images.githubusercontent.com/17660901/371936498-56f2b0d4-2e00-480b-b344-a59694ebd9e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDMxNzQsIm5iZiI6MTcyNzcwMjg3NCwicGF0aCI6Ii8xNzY2MDkwMS8zNzE5MzY0OTgtNTZmMmIwZDQtMmUwMC00ODBiLWIzNDQtYTU5Njk0ZWJkOWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEzMjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNTlkMjdhMTJhNWEzOTkyN2ViY2RiMWFlMWYyNjAxYTcwYzUxNGI2MTg0OTg0NjgwNzBmODlkNTNmZjIzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yuCULLHNcG_JkRRJVIM1B6XQ3YppTXN1XSvxxOYrcFk) ![image](https://private-user-images.githubusercontent.com/17660901/371936587-ffe8c0e0-d7c6-4155-8bf0-2ac635e4c8b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDMxNzQsIm5iZiI6MTcyNzcwMjg3NCwicGF0aCI6Ii8xNzY2MDkwMS8zNzE5MzY1ODctZmZlOGMwZTAtZDdjNi00MTU1LThiZjAtMmFjNjM1ZTRjOGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEzMjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYWIxOGZiY2UwMWQ4N2I4MjcwOGVhNmM5NWE3NjViOTQ1ZTYxZWMzOGNkNWI2NGRkMjk3N2YyNWNiMGY0MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c8SsKLzVcnciN_S1GyPm5QxHr-lw-2A-5EHsKvqynEM)

"How did you make the conversation_Id appear before the HTTP Request from Dify? In mine, it only appears in the output."

**Comment by xd845217xd** [comment]
This is it! After upgrading the Docker version from 0.8.3 to 0.9.0, I encountered the same issue. Is there any way to roll back to version 0.8.3?😭

**Comment by fujita-h** [comment]
selfhosted v0.8.3 (7f3282ec04d87cfb8fcff892e824c96094b92636) -> issue **NOT** happened
self-hosted v0.9.0 (d2ce4960f121783ff970c9ffe7183a7bdb1b9e01) -> issue happened
cloud ->issue happened

**Comment by fujita-h** [comment]
I tested the cloud version about 2 hours ago and found that a problem had occurred, and when I checked just now, the history was displayed normally.
However, when I tried the same test just now, the problem was still occurring.

I have experienced the problem going away after a certain amount of time has passed.

Either way, the history where the problem occurred has a `parent_message_id` of `null`.

**Comment by edrizo** [comment]
Complicated.

What to do now?

**Comment by edrizo** [comment]
> This is it! After upgrading the Docker version from 0.8.3 to 0.9.0, I encountered the same issue. Is there any way to roll back to version 0.8.3?😭

I don't know how to do it.

**Comment by xd845217xd** [comment]
> > This is it! After upgrading the Docker version from 0.8.3 to 0.9.0, I encountered the same issue. Is there any way to roll back to version 0.8.3?😭
> 
> I don't know how to do it.

"Alright, I got it.
Go to the folder and find 'docker-compose.yaml.'
Edit that file and change the image versions for api, worker, and web from `0.9.0` to `0.8.3`.

Then,
```
docker compose down
docker compose pull
docker compose up -d
```
At this point, just hope that the developers or other users will also notice the issue.

Is using Dify through the API really that uncommon? The missing conversation history should be pretty obvious..."

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/pull/8749, this is a follow-up pr to display the regenerated things.

**Comment by edrizo** [comment]
> > > > This is it! After upgrading the Docker version from 0.8.3 to 0.9.0, I encountered the same issue. Is there any way to roll back to version 0.8.3?😭
> > > 
> > > 
> > > I don't know how to do it.
> > 
> > 
> > Alright, I got it. Go to the folder and find 'docker-compose.yaml.' Edit that file and change the image versions for api, worker, and web from `0.9.0` to `0.8.3`.
> > Then,
> > ```
> > docker compose down
> > docker compose pull
> > docker compose up -d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > At this point, just hope that the developers or other users will also notice the issue.
> > Is using Dify through the API really that uncommon? The missing conversation history should be pretty obvious...
> 
> I use Dify with N8N and Z-API and the only solution I found for this issue is to pay for Redis and save the information inside their server (or something like that), which is not optimal for something that is a bug, hopefully they will fix it.

Mine also have 
-sandbox (latest), and
-weviate (latest)

they also should be 0.8.3?

**Comment by edrizo** [comment]
> @edrizo
> 
> > Mine also have -sandbox (latest), and -weviate (latest)
> > they also should be 0.8.3?
> 
> ```
>   api:
>     image: langgenius/dify-api:0.8.3
>     
>   worker:
>     image: langgenius/dify-api:0.8.3
>     
>   web:
>     image: langgenius/dify-web:0.8.3  
> ```
> 
> As for the others, like the sandbox and such, I didn’t make any changes. Keeping them as they are should be fine.

![image](https://github.com/user-attachments/assets/020cba51-9f03-40b3-8dac-b0d5889325a4)

**Comment by xd845217xd** [comment]
That's strange, but I did roll back to version 0.8.3.

![螢幕擷取畫面 2024-09-30 231654](https://github.com/user-attachments/assets/26f917bc-53ab-402d-9150-98a1a15657af)

**Comment by edrizo** [comment]
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml
INFO:matplotlib.font_manager:generated new fontManager
Preparing database migration...
Start database migration.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [flask_migrate] Error: Can't locate revision identified by '33f5fac87f29'

![image](https://github.com/user-attachments/assets/bf033e35-3004-4370-a8d7-e2e65cfad980)

**Comment by edrizo** [comment]
![image](https://github.com/user-attachments/assets/94a69b3d-f29e-4de4-999f-8076fbc91d25)

**Comment by edrizo** [comment]
@crazywoola

**Comment by edrizo** [comment]
> Running migrations None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used. sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml INFO:matplotlib.font_manager:generated new fontManager Preparing database migration... Start database migration. INFO [alembic.runtime.migration] Context impl PostgresqlImpl. INFO [alembic.runtime.migration] Will assume transactional DDL. ERROR [flask_migrate] Error: Can't locate revision identified by '33f5fac87f29'
> 
> ![image](https://private-user-images.githubusercontent.com/17660901/372155384-bf033e35-3004-4370-a8d7-e2e65cfad980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTc4MzUsIm5iZiI6MTcyNzcxNzUzNSwicGF0aCI6Ii8xNzY2MDkwMS8zNzIxNTUzODQtYmYwMzNlMzUtMzAwNC00MzcwLWE4ZDctZTJlNjVjZmFkOTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE3MzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjE3NTUwMTZlYmIyNDcxMzhmYTY2NzliNzU4YzcwNTEwNjhmOWUxZWZiNDZjZmFhZTRhNGM4MDkzMzhjMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OVtA20QZDoizRtMU5QoIB7EPPOHGywVXMguXyJ-9bBg)

@xd845217xd this is the error  when trying to use 0.8.3

**Comment by edrizo** [comment]
Anyone?

**Comment by perzeuss** [comment]
I am able to reproduce this. Looks like Dify overwrites the history on every message. The conversation id remains the same when new messages come in, but the last message-answer pair replaces the whole conversation history.

that's a @takatost critical issue, that's breaking a lot of applications right now.

**Comment by perzeuss** [comment]
> See #8749, this is a follow-up pr to display the regenerated things.

@crazywoola That's another issue. Using the Advanced Chat App API results in conversation history being lost and LLM calls do not contain the history. I assume the breaking change coming with the regeneration feature broke the Advanced Chat App API.

**Comment by IsraelHenriquee** [comment]
Same problem here!!!!

**Comment by fujita-h** [comment]
@edrizo Once you upgrade from 0.8.3 to 0.9.0, the database contents will be upgraded for 0.9.0, so even if you revert only the Docker image to 0.8.3, it will not start.

You will also need to write back the contents of the `volumes` directory obtained following the steps in the Upgrade Guide at https://github.com/langgenius/dify/releases.

**Comment by edrizo** [comment]
> @edrizo Once you upgrade from 0.8.3 to 0.9.0, the database contents will be upgraded for 0.9.0, so even if you revert only the Docker image to 0.8.3, it will not start.
> 
> You will also need to write back the contents of the `volumes` directory obtained following the steps in the Upgrade Guide at https://github.com/langgenius/dify/releases.

I hadn't installed it on the VPS yet. When I did it, the "latest" version is 0.9.1, and the same bug also happened.

The devs are already working on it. I'll wait for the repair!

**Comment by yadavvikash7171** [comment]
I wants to remove last conversation item, and then make api call, 
Can i do that using dify, can anyone please help in this

**Comment by alexhmyang** [comment]
太扯了，宝塔上 装的最新的是0.9 版本， api 没有记忆功能

**Comment by crazywoola** [comment]
> 太扯了，宝塔上 装的最新的是0.9 版本， api 没有记忆功能

实际上我们并没有在宝塔上面发布过。

**Comment by toybot1981** [comment]
我也有同样的问题，现在还没有解决是吗？API 依然没有记忆
