### ISSUE TITLE
Azure model security risk control issues

### ISSUE THREAD

**Issue by lixc123** [langgenius/dify#8916]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I use azure gpt4o mini to make workflows. The security risk control has been adjusted to the lowest level. However, there is still a chance that azure risk control will be triggered, which will cause the workflow to be interrupted in the middle. 
What I want to ask is whether the workflow can be continued without interruption, so that if can judge and switch the model to respond correctly.
![0FCAF11E-C3AE-48c2-A2DE-5CCC7C8E2014](https://github.com/user-attachments/assets/386db9ac-92a4-4d0b-a378-5fb0abdc55bf)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by JR-DDATA** [comment]
I'm facing the same issue as the previous user. I'm using Azure GPT4O Mini to create workflows, and even with security risk control set to the lowest level, there's still a chance that Azure's risk control will be triggered, interrupting the workflow.
I'm also curious if there's a way to make the workflow automatically detect and switch models when a risk control is triggered, so the workflow can continue running.
Have you encountered a similar situation? If so, let's discuss how to address this issue.
![Uploading 屏幕截图 2024-09-30 153500.png…]()
