### ISSUE TITLE
how to show image in Direct Reply node 

### ISSUE THREAD

**Issue by dtMndas** [langgenius/dify#8919]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、upload the file which contain some images to the **knowledge Base**,and after chunk ,just like  :
![image](https://github.com/user-attachments/assets/d4fd5121-2142-4ebe-9a7e-c48a927d0129)

2、when i get this chunk by **Knowledge Retrieval** node and  get the image url by **Code Execution** node, like : 
![image](http://127.0.0.1:5001/files/c36add4b-9463-40a8-bfb3-5e80320064e9/image-preview?timestamp=1727683001&nonce=6fe75e15a4234659e299f9a9845d365a&sign=SsdIgFwgJ5MmMSx--Bp95gyA05w-gyViHKtyH4JO3-g=

3、user de **Code Execution node** output ,which is the image url 

### ✔️ Expected Behavior

it can show the full image by **Direct Reply code** 

### ❌ Actual Behavior

i get a black show 
![image](https://github.com/user-attachments/assets/50ab984d-b5fe-45c4-bfd9-808684250994)

**Comment by crazywoola** [comment]
See examples here. https://github.com/crazywoola/dify-101-workflows

Please use the discussion to ask for help instead of opening a bug report.
