### ISSUE TITLE
对话界面，如果置顶了，无法删除和取消，应该是界面层级的问题，被盖住了。

### ISSUE THREAD

**Issue by ba370921** [langgenius/dify#892]
Dify version: Cloud | Self Host

## Steps To Reproduce

- [](url)

**Comment by ba370921** [comment]
![WX20230818-091429@2x](https://github.com/langgenius/dify/assets/16890445/c98e50de-be7e-4dc6-ae9f-061304d046d2)

**Comment by iamjoel** [comment]
Fixed: https://github.com/langgenius/dify/pull/1061
