### ISSUE TITLE
Jina fail  to crawl - Unknown error

### ISSUE THREAD

**Issue by damadorPL** [langgenius/dify#8934]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

select Jina add key - type any url

### ❌ Actual Behavior

An exception occurred while running crawling job:
Unknown error

ReferenceError: DataSourceProvider is not defined
    at ts (layout-4ee0e1eb4478d6bf.js:1:8274)
    at 4340-39749c4cf15ab253.js:1:55145
    at 4340-39749c4cf15ab253.js:1:42544
    at Object.a_ (fd9d1056-7863749520a823c0.js:1:72147)
    at aR (fd9d1056-7863749520a823c0.js:1:72301)
    at fd9d1056-7863749520a823c0.js:1:139240
    at sF (fd9d1056-7863749520a823c0.js:1:139339)
    at sM (fd9d1056-7863749520a823c0.js:1:139753)
    at fd9d1056-7863749520a823c0.js:1:145896
    at o4 (fd9d1056-7863749520a823c0.js:1:93336)

![Screenshot 2024-09-30 143818](https://github.com/user-attachments/assets/b2aef82c-c120-4c5d-a0e5-1222204b2159)
![Screenshot 2024-09-30 143836](https://github.com/user-attachments/assets/15ba9778-19d8-4296-b408-d134418ccf68)

**Comment by BryceWG** [comment]
I have the same issue as you

**Comment by 74sistemas** [comment]
me too

**Comment by damadorPL** [comment]
local variable 'api_key' referenced before assignment 

Now this error :)
