### ISSUE TITLE
After the initial startup, the localhost/install page keeps spinning and the admin password cannot be entered.

### ISSUE THREAD

**Issue by Analyst1981** [langgenius/dify#8952]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After the initial startup, the localhost/install page keeps spinning and the admin password cannot be entered.
![微信图片_20241001082513](https://github.com/user-attachments/assets/e43567d0-1d8e-4818-94b9-ef0cb4175cc0)

**Comment by crazywoola** [comment]
See https://www.bilibili.com/video/BV1R84y1Z7SP
