### ISSUE TITLE
Knowledgebase economic index, Chat retrieval throws error, errors.pydantic.dev/2.8/v/float_type

### ISSUE THREAD

**Issue by tealeeseng** [langgenius/dify#8957]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Chat in Knowledgebase with economical index will have this error. 
Reindexing not helping.
Removing the knowledgebase and error no longer happens in the chat. 

### ✔️ Expected Behavior

knowledgebase returns result and LLM generate chat response accordingly.

### ❌ Actual Behavior

UI shows error message: 1 validation error for DocumentContext score Input should be a valid number [type=float_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/float_type

Error in api docker:
```
api-1         | 2024-10-01 01:56:57,580.580 ERROR [Thread-86 (_generate_worker)] [app_generator.py:216] - Validation Error when generating
api-1         | Traceback (most recent call last):
api-1         |   File "/app/api/core/app/apps/chat/app_generator.py", line 203, in _generate_worker
api-1         |     runner.run(
api-1         |   File "/app/api/core/app/apps/chat/app_runner.py", line 159, in run
api-1         |     context = dataset_retrieval.retrieve(
api-1         |   File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 198, in retrieve
api-1         |     DocumentContext(
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
api-1         |     self.__pydantic_validator__.validate_python(data, self_instance=self)
api-1         | pydantic_core._pydantic_core.ValidationError: 1 validation error for DocumentContext
api-1         | score
api-1         |   Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
api-1         |     For further information visit https://errors.pydantic.dev/2.8/v/float_type
```

**Comment by Dheyvidj** [comment]
I'm experiencing the same issue in my setup. The error occurs when trying to chat in the knowledgebase, with economic indices.

**Comment by zheng013** [comment]
how to fix it ? if no change code.

**Comment by Dheyvidj** [comment]
> how to fix it ? if no change code.

For me, it worked to use version 0.8.2 of the Dify docker images

**Comment by Frank-Ge** [comment]
> > how to fix it ? if no change code.
> 
> For me, it worked to use version 0.8.2 of the Dify docker images

What are the tags for the other modules?

**Comment by Dheyvidj** [comment]
> > > how to fix it ? if no change code.
> > 
> > 
> > For me, it worked to use version 0.8.2 of the Dify docker images
> 
> What are the tags for the other modules? I tried changing api and web module from 0.9.1 to 0.8.2, but it didn't work.

Did you change the worker version?

**Comment by Frank-Ge** [comment]
> > > > how to fix it ? if no change code.
> > > 
> > > 
> > > For me, it worked to use version 0.8.2 of the Dify docker images
> > 
> > 
> > What are the tags for the other modules? I tried changing api and web module from 0.9.1 to 0.8.2, but it didn't work.
> 
> Did you change the worker version?

yes, I changed the worker's config. Now it's already ok, the page kept showing the loading screen yesterday. thx
