### ISSUE TITLE
search on database through api

### ISSUE THREAD

**Issue by xy3xy3** [langgenius/dify#8959]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I'm looking for a rag repository platform that supports API calls, and I found this feature available in dify's congeneric product fastgpt (https://doc.fastgpt.cn/docs/development/openapi/dataset/#%E6%90%9C%E7%B4%A2%E6%B5%8B%E8%AF%95).
I didn't find this feature in dify's API documentation (https://docs.dify.ai/guides/knowledge-base/maintain-dataset-via-api).

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/8477
