### ISSUE TITLE
Add new rerank models on Voyage

### ISSUE THREAD

**Issue by kevintsai1202** [langgenius/dify#8961]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Add new rerank models rerank-2(max 4000 tokens), rerank-2-lite(max 2000 tokens) to voyage or let users add their own models API: [https://docs.voyageai.com/reference/reranker-api](https://docs.voyageai.com/reference/reranker-api)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by JohnJyong** [comment]
Voyage is already exit in Dify model runtime
