### ISSUE TITLE
API based variable stopped working (again).

### ISSUE THREAD

**Issue by akkaz** [langgenius/dify#8977]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The agent feature "API based variable" is stopped to work after few days of working since last bug as referred here:
 #7520 

I’ve verified that the endpoint is correct and accessible through Insomnia, where everything works as expected. However, according to the Cloudflare logs, it appears that Dify isn't even attempting to reach the endpoint.

![image](https://github.com/user-attachments/assets/8daeff97-2199-4f3d-aaa6-c69d2d09d42b)

Dify agent don't respond to user message and return an "request timout" error.

Environment: We're using Hosted Dify (PRO subscription) on version 0.8.3 (signed as latest even if 0.9.1 is released on github).

### ✔️ Expected Behavior

It worked correctly for a couple of days.

**Comment by crazywoola** [comment]
This is a different one, we are having troubles with send requests not only in api_based_variable but also some nodes in workflow.

**Comment by crazywoola** [comment]
Fixed

**Comment by KevinZhang19870314** [comment]
Today, I encountered a similar issue where the agent response isn't calling the api-base extension API endpoint. Is this the same issue?

Will it be fixed in the next release? @crazywoola 

![image](https://github.com/user-attachments/assets/ef69507f-160b-4271-b535-483708a438e9)
