### ISSUE TITLE
json_schema support in Dify 0.9.1

### ISSUE THREAD

**Issue by ivanberry** [langgenius/dify#8994]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

0. Use Azure OpenAI gpt model
1. Create a new workflow
2. use a LLM block
3. Change the model to gpt-4o-mini-2024-07-18 or gpt-4o-2024-08-06 as [How to Use JSON Schema Output in Dify?](https://docs.dify.ai/learn-more/extended-reading/how-to-use-json-schema-in-dify )
4. set up the response_format to json_schema and add a json_schema

### ✔️ Expected Behavior

JSON response

[openai] Bad Request Error, Error code: 400 - {'error': {'message': 'response_format value as json_schema is enabled only for api versions 2024-08-01-preview and later (request id: 2024100312073850903022739187310)', 'type': '', 'param': '', 'code': 'BadRequest'}}

### ❌ Actual Behavior

Error shows:

How to Use JSON Schema Output in Dify?

**Comment by ivanberry** [comment]
As I method in the [Steps to reproduce] section. I am test the gpt-4o-mini-2024-07-18 , and gpt-4o-2024-08-06

**Comment by vannhann-intel** [comment]
i'm actually having the same issue, previously work just fine. only today have this problem

**Comment by crazywoola** [comment]
```
[openai] Bad Request Error, Error code: 400 - {'error': {'message': 'response_format value as json_schema is enabled only for api versions 2024-08-01-preview and later (request id: 2024100312073850903022739187310)', 'type': '', 'param': '', 'code': 'BadRequest'}}
```

See the docs here. 

> However, Structured Outputs with response_format: {type: "json_schema", ...} is only supported with the gpt-4o-mini, gpt-4o-mini-2024-07-18, and gpt-4o-2024-08-06 model snapshots and later.
> gpt-4o-mini, gpt-4o-2024-08-06, and later

https://platform.openai.com/docs/guides/structured-outputs/structured-outputs-vs-json-mode

This error is pretty obvious, you need to change to another model, the docs might be outdated in this case.

For questions please use discussions instead of posting an issue.

**Comment by dabrodev** [comment]
I switched to another model: gpt-4o-2024-08-06. Yesterday it worked, today it does not.

**Comment by ivanberry** [comment]
@dabrodev @vannhann-intel 

is it worked now? 

The comment they response is useless. I know the model limitation. and I have said I am use the model **gpt-4o-mini-2024-07-18** or **gpt-4o-2024-08-06** as [How to Use JSON Schema Output in Dify?](https://docs.dify.ai/learn-more/extended-reading/how-to-use-json-schema-in-dify).

**Comment by ofekby** [comment]
> @dabrodev @vannhann-intel
> 
> is it worked now?
> 
> The comment they response is useless. I know the model limitation. and I have said I am use the model **gpt-4o-mini-2024-07-18** or **gpt-4o-2024-08-06** as [How to Use JSON Schema Output in Dify?](https://docs.dify.ai/learn-more/extended-reading/how-to-use-json-schema-in-dify).

I have experienced a similar issue, not using Dify, but using Azure Open AI. Changing `api_version` to `2024-08-01-preview`, solved the issue. Based on this doc https://devblogs.microsoft.com/semantic-kernel/using-json-schema-for-structured-output-in-net-for-openai-models/#supported-models-for-structured-outputs

Note, you should have both requirements - a model supporting structured responses and use the **API** version `2024-08-01-preview`

**Comment by tuoxiansp** [comment]
It seems to be a bug in the Azure model provider.

https://github.com/langgenius/dify/issues/8451#issuecomment-2402979446
