### ISSUE TITLE
Retrieval Failure After Indexing New Files into Knowledge Base

### ISSUE THREAD

**Issue by NourKhdour** [langgenius/dify#8996]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3 

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am encountering an issue with my knowledge base after adding new files. The files are successfully indexed and enabled in the system, but when I test the retrieval process, no results are returned for queries that should match the newly indexed content.

### ✔️ Expected Behavior

Relevant results from the newly added files should be retrieved when querying the knowledge base.

### ❌ Actual Behavior

No results are returned during the retrieval testing.

**Comment by crazywoola** [comment]
Please upgrade to v0.9.1 to see if this is resolved.
