### ISSUE TITLE
How do i know that unstructured is working as intended?

### ISSUE THREAD

**Issue by spencerwongfeilong** [langgenius/dify#9000]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.91

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In the environment file, set the following configuration:

VECTOR_STORE=weaviate
COMPOSE_PROFILES=${VECTOR_STORE:-weaviate},unstructured
ETL_TYPE=Unstructured
UNSTRUCTURED_API_URL=http://unstructured:8000/general/v0/general
Upload a document, such as a .docx file.

Observe that the file indexes successfully.

Check the logs of the unstructured container and note that there is no output.

Inspect the storage for unstructured data and find it empty.

![image](https://github.com/user-attachments/assets/9356f907-0fa9-4ddb-91a1-cb7c49079bf1)
The above steps suggest a potential issue with the unstructured container functioning correctly, despite the ETL being set to unstructured successfully.

### ✔️ Expected Behavior

I think, files should be written to the unstructured volume.

### ❌ Actual Behavior

No clue on what to expect if unstructured really is working as intended.

**Comment by taowang1993** [comment]
If you were extracting .docx files, then the Unstructured.io container is not used. 

Instead, the default Dify extractor is used. 

The following file will explain which extractor will be used for which file type:

api/core/rag/extractor/extract_processor.py

**Comment by spencerwongfeilong** [comment]
Hello, thanks for the response.

I understood dify self hosted does not support the unstructured serverless api. Is that right?

Also, the env file doesn't mention an unstructured API key variable to enter. Is that correct? I'm unsure if an API key is needed to use the docker unstructured container. 

Could you provide clarity please.

**Comment by taowang1993** [comment]
You need to mannually include the api key variable in your docker/.env file as follows:

```
ETL_TYPE=Unstructured
UNSTRUCTURED_API_URL=
UNSTRUCTURED_API_KEY=
```

If you are using the paid unstructured api, you need to use the corresponding URL and API key.

**Comment by Wsine** [comment]
> If you were extracting .docx files, then the Unstructured.io container is not used.
> 
> Instead, the default Dify extractor is used.
> 
> The following file will explain which extractor will be used for which file type:
> 
> api/core/rag/extractor/extract_processor.py

It seems that Dify consistently uses its default PdfExtractor rather than using unstructured's pdf extraction feature (with data cleaning feature?) even when configured with `ETL_TYPE=Unstructured`. Is it a bug?

https://github.com/langgenius/dify/blob/bf048b8d7c709035f23cbb6bd20bc772bbb0d766/api/core/rag/extractor/extract_processor.py#L101-L105
