### ISSUE TITLE
To upload file in the http request block in workflow 

### ISSUE THREAD

**Issue by muckthaa-ss** [langgenius/dify#9004]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Cloud

### Steps to reproduce

To upload file in the http request block in workflow 

### ✔️ Expected Behavior

Upload option in http request block 
![image](https://github.com/user-attachments/assets/e566ac00-0064-4df4-9d44-d9e3b3b2029f)

### ❌ Actual Behavior

i cant upload any file in the http block

**Comment by crazywoola** [comment]
Checkout v0.10.x-beta
