### ISSUE TITLE
Dify 0.9.1 - Agent - Using via API session problem

### ISSUE THREAD

**Issue by wilsonfe** [langgenius/dify#9005]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I created an Agent and I am accessing the agent via API. When I start the conversation with the bot, the message history session does not remain. The bot always starts the conversation from the beginning. This same error does not occur when I test the bot within Dify. The problem occurs when I use it via API. Webhook.

### ✔️ Expected Behavior

That the bot would continue with the memory without restarting the conversation.

### ❌ Actual Behavior

The bot should continue to respond to messages as the user converses with it and not restart the conversation.

Do not test with chatflow and this problem only started to occur in version 0.9.1, the same problem does not occur in version 0.8.3.

**Comment by JVini0166** [comment]
I'm experiencing the same thing for version 1.9.0

**Comment by averyyan** [comment]
me too

**Comment by crazywoola** [comment]
Duplicated fixed in #8965
