### ISSUE TITLE
When using parallel execution of nodes in workflows, can it wait for all nodes are finished and then do somothing else?

### ISSUE THREAD

**Issue by minggg98** [langgenius/dify#9011]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In order to save time, I am using a parallel workflow to complete some tasks, but the workflow will not wait for all parallel nodes to finish before executing the next node, which will cause some variables of the next node to be unavailable. So, does Dify support the ability for parallel nodes to execute simultaneously and wait for completion?

### 2. Additional context or comments

![dify issuse](https://github.com/user-attachments/assets/d5f04509-15e5-4b25-a67a-883864689c1c)
As shown in the picture, I have multiple nodes executing in parallel, and then their results are connected to the same node, and when the execution is done, the parallel nodes are not all finished, and the workflow goes to the next node. In the picture, I tried to use the variable aggregator node to try to wait them finished. Unfortunately, it failed. Is there any good solution? Or can you provide that capability?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See this issue https://github.com/langgenius/dify/issues/8420 for more information.

**Comment by minggg98** [comment]
> See this issue #8420 for more information.
After seeing the issue you provided, it seems do not figure out my problem. What I need is that behind some parallel workflow nodes there will be  another node that can wait all parallel nodes finished and then use these parallel nodes result to do something else.In addition to connecting to the same end node, can you provide other solutions? Thk you.
