### ISSUE TITLE
Could you please remove the validate for "sys.query in user message is required" in llm node

### ISSUE THREAD

**Issue by gaozhengzhou** [langgenius/dify#9013]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Before calling the LLM, I parse the sys.query and pass the processed results to the LLM node. However, the LLM node checks that the user message must contain sys.query, which prevents me from doing this，so could you please remove the validate for "sys.query in user message is required" in llm node?
![image](https://github.com/user-attachments/assets/8e683991-a48c-4258-a9e2-deb06fae33a8)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
If you turn on the memory, then it's required.

**Comment by sweetkey** [comment]
Can this sys.query be changed to be optional? In a LLM block, the function is to summarize the input of the pre-define text at the start, regardless what the user enters as query (or stored as sys.query). But LLM block always consider the query as the primary text source. I don't need the input of sys.query for this perticular case.

**Comment by aandis** [comment]
+1 on this. Please implement this. The function of an LLM block is to summarise text from any preceding step or any static text. It does not necessarily have to be related to `sys.query`.

**Comment by nadirvishun** [comment]
If I add a step LLM after the user's question to process the user's question, turn the user's  question into similar multiple questions `llm_result`, then go through the knowledge base and another LLM, at that point what I need subsequently is not `sys.query` but `llm_result`.

**Comment by 00drdelius** [comment]
+1. Strongly needed this feature.

**Comment by zhangdazhuang** [comment]
+1. Strongly needed this feature.
I use ~~{{#sys.query#}}~~ to make LLM ignore this message.

**Comment by Silow9** [comment]
+1. Strongly needed this feature.

**Comment by Sos-Zachary** [comment]
+1. Strongly needed this feature.
i use a code_node to help me to preprocess the query string to get a well-structed input,but finally i also need to input sys.query,that is too inflexible. (

**Comment by allenhsu** [comment]
In my case, the first block is using a local vision model to do OCR. The output of the OCR step will be used in the next block which calls a non-vision deep thinking model.

**Comment by MaoJianwei** [comment]
+1. Strongly needed this feature.

**Comment by Sagiri-12** [comment]
+1. Strongly needed this feature. Because I have already wrapper the query at certain nodes, but I am unable to use it.

**Comment by guopeng1994** [comment]
+1. Any updates?
