### ISSUE TITLE
Add a "CodeGenerator" to Code Nodes

### ISSUE THREAD

**Issue by Kota-Yamaguchi** [langgenius/dify#9021]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

As a user of Dify, I have personally experienced the challenges of writing code directly on the platform. Unlike in local environments where tools like GitHub Copilot or Cursor can assist me in generating code, Dify currently lacks similar features. This makes it difficult to efficiently implement functionalities, particularly for users like me who may not have advanced programming skills. Writing code from scratch without assistance can be time-consuming and discouraging, which limits productivity and creativity.
My company used to do a Dify course for people who couldn't write code, and they had a very hard time with code blocks. I wish I could get them to face LLM more.
So I suggest adding a code generator to the code node. I made a demo to give you an idea.

https://github.com/user-attachments/assets/44d4e9f5-b5de-4f7d-9c6e-784c2a70fbe3

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This is cool, sorry for the late response.

**Comment by Kota-Yamaguchi** [comment]
I imagine you must have been busy with v0.10.0. Thank you for taking the time to review it
