### ISSUE TITLE
The advanced workflow orchestration of the chat assistant can automatically connect to the context when used in Dify, but not when using the API

### ISSUE THREAD

**Issue by cabinai** [langgenius/dify#9027]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

The advanced workflow orchestration of the chat assistant can automatically connect to the context when used in Dify, but not when using the API
1.Create an advanced workflow orchestration for the chat assistant
2.Directly carry out the preview test, the first message is "Hello", the second message is "What I said in the last sentence", and the AI successfully returns "Hello in the previous sentence"
3.Using the API test (bring in conversation_id), the first message is "Hello", the second message is "What did I say in the last sentence", and the AI returns "I can't know the content of your last sentence"
![image](https://github.com/user-attachments/assets/0df29589-1bfd-4bd1-a314-ee38dd8c9bcc)

**Comment by xiaocuanChina** [comment]
Whether there is a suitable solution to the problem in question
