### ISSUE TITLE
Follow-up (suggested questions) does not refer to the most recent message

### ISSUE THREAD

**Issue by fujita-h** [langgenius/dify#9041]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a simple LLM chatbot with Chatflow
2. Enable follow-ups
3. Publish the app
4. Chat and see the suggested questions

### ✔️ Expected Behavior

Suggested questions should be reference including the content of the last message.

### ❌ Actual Behavior

Suggested questions do not reference the content of the most recent message, but are based only on previous information.

**Comment by fujita-h** [comment]
Question suggestions are generated by the following methods:
https://github.com/langgenius/dify/blob/2571b0c4e36b7ce7a3ada94aac751ad20f319e1f/api/services/message_service.py#L205

When we look at the processing of this function, we see that in the process of referencing messages, it skips the most recent message.
https://github.com/langgenius/dify/blob/2571b0c4e36b7ce7a3ada94aac751ad20f319e1f/api/core/memory/token_buffer_memory.py#L61

This was added in #7661

**Comment by Kevin9703** [comment]
I encountered the same issue, and it also seems to affect the conversation's historical context.

**Comment by xuzuodong** [comment]
Sorry for causing this bug, I will try to fix it.

**Comment by xuzuodong** [comment]
> I encountered the same issue, and it also seems to affect the conversation's historical context. 

Are you using API in self-hosted environment?

**Comment by xuzuodong** [comment]
> > > I encountered the same issue, and it also seems to affect the conversation's historical context.
> > 
> > 
> > Are you using API in self-hosted environment?
> 
> Yeah, using API to call the app

The conversation's historical context bug has been fixed by https://github.com/langgenius/dify/pull/8965, but they haven't released a new version

**Comment by Kevin9703** [comment]
> > > > I encountered the same issue, and it also seems to affect the conversation's historical context.
> > > 
> > > 
> > > Are you using API in self-hosted environment?
> > 
> > 
> > Yeah, using API to call the app
> 
> The conversation's historical context bug has been fixed by #8965, but they haven't released a new version yet

Thank you for the update.

**Comment by xuzuodong** [comment]
If it's convenient for you , can you pull #9122 and test to see if it's fixed?  @Kevin9703

**Comment by Kevin9703** [comment]
> If it's convenient for you , can you pull #9122 and test to see if it's fixed? @Kevin9703

Looks like it's working now. Thanks for the fix
