### ISSUE TITLE
Knowledgebase upload file stay in Queue

### ISSUE THREAD

**Issue by qadeerikram-art** [langgenius/dify#9043]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.8.0-beta1

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

Create New knowledge base and upload file. File upload will segment and index will stay in Queue.

### ✔️ Expected Behavior

It should complete segmentation and indexing

### ❌ Actual Behavior

knowledgebase file segment and index stays in Queue. Dont't get completed

**Comment by qadeerikram-art** [comment]
@dosu I have hosted dify  and two days ago it was working fine.  And also i am not getting any error that your  limit has reached. There is an api which checks the index status and it kepps calling this api and indexing_status stays in waiting. It does not complete. Below is the api
https://dev.middleware.cova.ai/console/api/datasets/4c147e2d-31b8-4b0e-9a3d-a57888e4b680/batch/20241007105705479217/indexing-status

**Comment by crazywoola** [comment]
Please provide the container logs.

**Comment by JohnJyong** [comment]
have you started the celery worker? @qadeerikram-art
