### ISSUE TITLE
Variable Aggregator not aggregating/synchronising

### ISSUE THREAD

**Issue by RyanxLowz** [langgenius/dify#9057]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0a6ca93d-008b-4e6f-a473-8b5e65cdb11f)

### ✔️ Expected Behavior

After the variable aggregator should have synchronised and run as a single branch

### ❌ Actual Behavior

After the variable aggregator, all branches continued to run parallel

**Comment by crazywoola** [comment]
Duplicated, this is an expected behavior.  https://github.com/langgenius/dify/issues/8420

**Comment by RyanxLowz** [comment]
@dosubot @crazywoola 

I don't think its an expected behaviour, I have used the aggregate group flag  
![image](https://github.com/user-attachments/assets/73c5ac29-c9a6-419c-bdde-764fa6e2e495)
![image](https://github.com/user-attachments/assets/8e406933-d607-4beb-86c9-fbbabbaafaff)

but i think the issue might be because i am trying to aggregate within a branch which doesn't seem to be supported yet. Could this be supported in later versions?
