### ISSUE TITLE
Dify sends  <Context> tags with all instructions inside when it is the first interaction and the Conversation Id is not passed.

### ISSUE THREAD

**Issue by dimitrihartt** [langgenius/dify#9064]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Latest

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Dify keeps sending CONTEXT tags with all instructions inside when it is the first interaction and the Conversation_Id is not passed (because we don't have it yet) and only the user field is passed.

### ✔️ Expected Behavior

That the CONTEXT tags with all the chatbot's instructions inside doesn't come as a response for the first interaction, instead we want to have the initial welcoming message.

### ❌ Actual Behavior

The response is like this

CONTEXT TAG
*****a lot content goes in here, showing off all the chatbot's instructions and not the welcoming message.*****
CONTEXT TAG

**Comment by dimitrihartt** [comment]
The /<Context/> tags keeps coming!

**Comment by crazywoola** [comment]
What is the LLM in this workflow.
