### ISSUE TITLE
Support azure openai api version 2024-09-01-preview

### ISSUE THREAD

**Issue by Allamss** [langgenius/dify#9069]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

ye, I wanna try the o1 model

### 2. Additional context or comments

![image](https://github.com/user-attachments/assets/f70828bd-6640-4840-a8ab-ceaf9ece44d3)

https://learn.microsoft.com/zh-cn/azure/ai-services/openai/api-version-deprecation#latest-preview-api-releases

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/9040
