### ISSUE TITLE
Knowledge base stays in queuing mode, nothing happens, edition 18-10-2024....

### ISSUE THREAD

**Issue by JanvanHout** [langgenius/dify#9072]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Create New knowledge base and upload file (or files). File upload will segment and index will stay in Queue.
also adding new files to existing knowledge base fails.... again

### ✔️ Expected Behavior

creating a working knowledge base, It should complete segmentation and indexing

### ❌ Actual Behavior

knowledgebase file segment and index stays in Queue. Dont't get completed, even with 'top-priority'. same as yesterday...... it worked for a couple of hours....

**Comment by crazywoola** [comment]
Fixed again, sorry for the inconvienece, we have some issue with our redis cluster in our server.
