### ISSUE TITLE
Images do not appear in the logs

### ISSUE THREAD

**Issue by murtaza-motorwala** [langgenius/dify#9079]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0-beta2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Steps to reproduce - 
1. Create a chat workflow
2. I have configured the new files array variable.
3. Using ChatGPT 4o as the LLM.
4. Published the app and asked a question by attaching a png image.
5. When I looked at the logs, I do not see the image, instead it shows a blank icon with 0.
6. In the chat as well, the image is really tiny (but visible). I hope we can enlarge it as it used to be before.

<img width="634" alt="image" src="https://github.com/user-attachments/assets/57d208b0-944e-4c92-978f-7ae8516897bf">

<img width="1451" alt="image" src="https://github.com/user-attachments/assets/ba36af1b-676c-4ff3-afa7-84c4a7a72b02">

<img width="876" alt="image" src="https://github.com/user-attachments/assets/98d900d9-e0e2-4548-93ab-6051a3f9b166">

### ✔️ Expected Behavior

The image(s) should be shown in the logs so the administrators can look for what questions were asked and in what context.
Also helps to remove any obscene or inappropriate content.

### ❌ Actual Behavior

Images do not appear.

**Comment by laipz8200** [comment]
Fixed in v0.10.0-beta3.
