### ISSUE TITLE
Incorrect any Type Annotations in the Codebase

### ISSUE THREAD

**Issue by laipz8200** [langgenius/dify#9080]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

It has been identified that there are several occurrences of incorrect any type annotations in the codebase. Specifically, instead of using the proper Any type from typing, the lowercase any is being used (e.g. [here](https://github.com/langgenius/dify/blob/2cf1187b32c0885e9f9b987d57c6ca9da4508a2c/api/core/model_runtime/model_providers/fishaudio/tts/tts.py#L49)).

To improve type safety and consistency throughout the repository, these should be replaced with Any from the typing module.

### 2. Additional context or comments

If you’re interested in helping improve this issue, please leave a comment below the issue!

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by ronaksingh27** [comment]
@laipz8200  could you please assign this issue to me? I would also appreciate any suggestions you might have on where to begin

**Comment by ronaksingh27** [comment]
@laipz8200 I did the changes in tts_model.py and raised the pr for that

**Comment by ronaksingh27** [comment]
@laipz8200 I corrected all files in `model_providers `folder , could you please review and provide feedback
