### ISSUE TITLE
add node to transfer PDF to images for LLM use

### ISSUE THREAD

**Issue by toptalentsgpt** [langgenius/dify#9091]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

10.0.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Some pdfs have many images , prefer to convert pdf pages to images rather than Document Extractor Node

**Comment by crazywoola** [comment]
Please use the right template to submit a feature request together with more details about why would you like to have it.
