### ISSUE TITLE
`Parameter Extraction` docs link is breaking

### ISSUE THREAD

**Issue by AprilNEA** [langgenius/dify#9092]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

live

### Cloud or Self Hosted

Cloud

### Steps to reproduce

<img width="873" alt="image" src="https://github.com/user-attachments/assets/297f47da-b855-43ee-a797-52ece6f84810">

### ✔️ Expected Behavior

Correct link: 
https://docs.dify.ai/guides/workflow/node/parameter-extractor
https://docs.dify.ai/zh-hans/guides/workflow/node/parameter-extractor

In addition to revising the correct links, setting up redirects is also recommended

### ❌ Actual Behavior

Current Link:
https://docs.dify.ai/v/zh-hans/guides/workflow/node/parameter_extractor

**Comment by AllenWriter** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/3f8a53e2-af76-4fd5-84d0-04d1d7d54d78">
The URL of the documentation is now available.
