### ISSUE TITLE
imeages batch uploads in workflow

### ISSUE THREAD

**Issue by toptalentsgpt** [langgenius/dify#9094]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

10.0.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Seems user can only upload one imeags each time, any possiblity that we modify the code to change this setting ?

**Comment by crazywoola** [comment]
<img width="818" alt="image" src="https://github.com/user-attachments/assets/3daad6d3-889b-4dfa-a2df-d7f04da0737b">
