### ISSUE TITLE
历史会话清除

### ISSUE THREAD

**Issue by sunny0315** [langgenius/dify#91]
对话型应用中，聊天界面中如何清除聊天界面左侧历史会话列表
![image](https://github.com/langgenius/dify/assets/5812332/4e994a80-f968-470b-a164-544b7daad85f)
随着自己不断新建会话或者分享给其他人使用时，这个列表会一直累积，显得有点乱。
另外当前通过分享链接打开会携带历史会话信息，这个是否可以在分享时增加一个是否携带历史会话记录的选项（在一些场景下可能体验会更好些）。

**Comment by JohnJyong** [comment]
谢谢你的建议，我们会记录到需求池中，看后续安排

**Comment by Williamzxn** [comment]
大概什么时候可以完成呀，期待

**Comment by renguowen** [comment]
给加一个删除按钮吧，要不好几个会话好乱啊

> 谢谢你的建议，我们会记录到需求池中，看后续安排

**Comment by qjing666** [comment]
遇到一个新的问题，当聊天数量到达20个的时候，"new chat"按钮就消失了

**Comment by seiriosPlus** [comment]
> 遇到一个新的问题，当聊天数量到达20个的时候，"new chat"按钮就消失了

20是后端有最大个数的判断，这个值来源于：  前端调用 /api/conversations时传了参数 limit=20

可以 修改前端的默认值, 也可以从后端进行hack.
