### ISSUE TITLE
There is no "usage" in the "metadata"

### ISSUE THREAD

**Issue by joneqian** [langgenius/dify#9106]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After I updated to 0.9.1, the "usage" data still does not return in the "metadata." 
I mentioned this bug before [#8544](https://github.com/langgenius/dify/issues/8544) and you said it had been fixed.

### ✔️ Expected Behavior

The "usage" data should in the "metadata."

**Comment by joneqian** [comment]
![image](https://github.com/user-attachments/assets/839db5ae-10dc-4813-adac-f5083c1a8cbd)
![image](https://github.com/user-attachments/assets/f60a701a-7cf8-4606-bdc4-fc7a81dbbe16)

**Comment by crazywoola** [comment]
It seems to have `metadata` in `streaming` mode.
