### ISSUE TITLE
Knowledge base indexing causes service lag

### ISSUE THREAD

**Issue by starweavingdream** [langgenius/dify#9109]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When uploading too many large files to the knowledge base for indexing, the entire service will be slow, causing the question-and-answer service to be unavailable.

### ✔️ Expected Behavior

I expect the API service and worker service to run on two machines, but I don't know if this is possible, or if the API service can be used normally when indexing the knowledge base.

**Comment by crazywoola** [comment]
Duplicated, see for details. https://github.com/langgenius/dify/issues/7677
