### ISSUE TITLE
Image Display Issues in Chatbot Responses After Updating to Version 0.9.1

### ISSUE THREAD

**Issue by Howardhn** [langgenius/dify#9120]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After updating Dify from version 0.5.x to 0.9.1, we've encountered the following issues with image display in chatbot responses:
1. Images are not displaying properly in chatbot responses.
2. When using Markdown syntax for images with embedded links, clicking on the image redirects to the specified link, but the image itself is not visible. Markdown Format：[![alt text](image url)](link url)
3. Images without embedded links display correctly.Markdown Format：![alt text](image url)
Their resolution appears to be significantly lower compared to the previous version (0.5.x).
4. These issues were not present in the older version (0.5.x), where all image functionalities worked as expected.
The issue can be demonstrated in the following images：
![image](https://github.com/user-attachments/assets/d93f73d5-17d3-4d3c-bf3b-3828e3a8ed79)

### ✔️ Expected Behavior

 The following images is OK in the older version (0.5.x)：
![image](https://github.com/user-attachments/assets/f5609a8b-f9c6-45d3-99db-ca078d2a43c9)

**Comment by crazywoola** [comment]
Might happens in this version as well https://github.com/langgenius/dify/issues/9079

**Comment by ClementeGao** [comment]
![image](https://github.com/user-attachments/assets/4ea28fbf-9dce-4b5f-a1a7-79c44a5ee659)
@crazywoola  hi，same issue, The image disappears immediately after it appears.

**Comment by Howardhn** [comment]
The image shows a split-screen view of a web development environment. On the left side, there's a template editor with input variables and a code section. The code section contains two cases: Case1 and Case2, both referencing an image URL. The center of the image displays a preview with a light blue rectangle labeled "Remove Shadow" and "Case2" text below it. On the right side, there's a code inspector showing HTML and CSS details.
Case1 successfully displays an image, while Case2 does not show the image and only displays text.
![image](https://github.com/user-attachments/assets/0ed5403d-bfeb-4b8a-bc9b-678f283c684e)

**Comment by Howardhn** [comment]
Potential Issues:
1. Empty Anchor: The <a> tag contains no content, making it invisible to users unless styled with CSS.
2. Image Display: Despite linking to an image, the code uses an anchor tag instead of an <img> tag, which may prevent the image from rendering.
3. CSS Classes: The use of "!decoration-primary-700" suggests Tailwind CSS usage, but this might cause unintended styling effects.

Recommendations:
While a clickable image is desired, nest the <img> tag within the <a> tag:
 
![image](https://github.com/user-attachments/assets/af353ae4-b3f9-4b32-b094-e12e7413fcc5)

![image](https://github.com/user-attachments/assets/3ff425a0-d8f0-4f8a-ba86-019b20eac194)

@douxc

**Comment by laipz8200** [comment]
Fixed in v0.10.0-beta3.
