### ISSUE TITLE
Unable to use `Array[String]` in `HTTP Request`

### ISSUE THREAD

**Issue by AprilNEA** [langgenius/dify#9125]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Live

### Cloud or Self Hosted

Cloud

### Steps to reproduce

<img width="761" alt="image" src="https://github.com/user-attachments/assets/3a688bb8-55c3-42dc-8145-af084c4852d7">
<img width="269" alt="image" src="https://github.com/user-attachments/assets/5ed70547-8cb3-43e9-823d-9b476b4d0a07">
<img width="549" alt="image" src="https://github.com/user-attachments/assets/42a71f16-b7f4-4beb-818f-1026de8afc80">

### ✔️ Expected Behavior

<img width="773" alt="image" src="https://github.com/user-attachments/assets/1c402904-340e-4cff-9c87-d6e59d74d0c3">

### ❌ Actual Behavior

<img width="308" alt="image" src="https://github.com/user-attachments/assets/18619667-9b71-407d-ad00-21407de7e754">

**Comment by AprilNEA** [comment]
Workflow App: https://udify.app/workflow/UvtkopWluBtN4Ekw

**Comment by AprilNEA** [comment]
> The issue you're encountering with the "Unexpected token" error is likely due to the use of single quotes in your JSON input. JSON requires double quotes for strings.
> 
> To resolve this, ensure that your JSON body in the HTTP request is formatted with double quotes, like this:
> 
> ```json
> {
>   "result": ["1", "2"]
> }
> ```
> 
> Make sure your request body is correctly set up in the HTTP request configuration interface. If you're using a variable, ensure it outputs the JSON in the correct format with double quotes.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@docu	That's the crux of the problem, but obviously it's not in the user's control

**Comment by yunchi0921** [comment]
I encounter the same issue in version 0.11.0. Is this issue got fixed in latest version?

**Comment by phoenixor** [comment]
I encounter the same issue in version 0.15.3, how can i use jsonarray in post body like [{"name": "jack", "age": 20}, {"name": "alice", "age": 18}]
