### ISSUE TITLE
 'Suggested-question'  doesn't respond with Chinese while chatting with Chinese

### ISSUE THREAD

**Issue by wy96f** [langgenius/dify#9128]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create a simple LLM chatbot with Chatflow
Enable follow-ups
Publish the app
Chat with Chinese and see the suggested questions

### ✔️ Expected Behavior

"In Chinese conversations, 'Suggested-question' always gives answers in Chinese."

### ❌ Actual Behavior

"In Chinese conversations, 'Suggested-question' rarely gives answers in Chinese."

**Comment by wy96f** [comment]
![image](https://github.com/user-attachments/assets/8f8c6ccf-748d-483f-b0fe-2992007a2f73)
It seems that the modification of this prompt has affected the language of the output.

**Comment by crazywoola** [comment]
Duplicated

**Comment by internet5** [comment]
this problem is still here
