### ISSUE TITLE
Dify forget the conversation history when working through the API

### ISSUE THREAD

**Issue by aiwinapp** [langgenius/dify#9130]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I’m working with the Dify API. I include the conversation_id with my request, but Dify treats it as if it’s the first message in the conversation, even though it should be a continuation. As a result, I receive responses as if each message is the initial query. Everything works fine on the web interface, but the API has this issue. This error starts from update to 0.9.1.

**Comment by aiwinapp** [comment]
Fixed, but I dont see it in my build. I have error.

**Comment by EitanWong** [comment]
I've encountered the same issue; when calling the API, the response doesn't include history, yet conversations in Dify work fine. The version is 0.9.1.

**Comment by aiwinapp** [comment]
I have fix this error. Just a add to 

`/api/controllers/service_api/app/completion.py
`
add line:
`args ["parent_message_id"] = UUID_NIL
`

this help to me:
https://github.com/langgenius/dify/pull/8984/commits/fd1c85d8b683e883d89e4215b98e0145f676c009
