### ISSUE TITLE
Problems occurred when using openai's tts

### ISSUE THREAD

**Issue by Uhao-P** [langgenius/dify#9131]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Add model provider and set system model: openai
![image](https://github.com/user-attachments/assets/95a4a72f-9222-4269-af6f-39486a3523c7)

2. Test tts
![image](https://github.com/user-attachments/assets/f70719b3-8c5e-4328-8538-856f00f8b871)

### ✔️ Expected Behavior

None

### ❌ Actual Behavior

None

**Comment by crazywoola** [comment]
![QQ_1728482228725](https://github.com/user-attachments/assets/43a69566-18f4-40ab-ab34-3e47994921a1)
It should be HTTPS

**Comment by dianshu** [comment]
@dosu Hi, Which system do you mean about "Make sure FFmpeg is installed on your system."? Docker image? The machine where I open my browser?
