### ISSUE TITLE
filter the  markdown image block for TTS input

### ISSUE THREAD

**Issue by verigle** [langgenius/dify#9133]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

for tts, expect remove TTS  input  text of markdown image url .

### 2. Additional context or comments
llm output example
```
this is a new picture:
![picture1](http://www.test.com/test.jpg)
```
it is not need to use TTS to audio for image markdown block (`![picture1](http://www.test.com/test.jpg)`), is there has any way to  remove image url for TTS input

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Not sure what you are trying to say, what do you expect?

**Comment by verigle** [comment]
I expect the tts don't read the markdown block
  of image url.

example for llm output:
```
this is a new picture:
![picture1](http://www.test.com/test.jpg)
```

for tts, it only required to read  the word of  `this is a new picture`, 
however, the current tts will read the url of `picture1](http://www.test.com/test.jpg)`, ehich is not useful audio for user

**Comment by verigle** [comment]
I expect the tts don't read the markdown block
  of image url.

example for llm output:
```
this is a new picture:
![picture1](http://www.test.com/test.jpg)
```

for tts, it only required to read  the word of  `this is a new picture`, 
however, the current tts will read the url of `picture1](http://www.test.com/test.jpg)`, ehich is not useful audio for user

**Comment by verigle** [comment]
is there any plan to filter the markdown image block for TTS input?

**Comment by FerretAngel** [comment]
+1
