### ISSUE TITLE
Query or prefix prompt is too long, you can reduce the prefix prompt, or shrink the max token, or switch to a llm with a larger token limit size.

### ISSUE THREAD

**Issue by zuco1111** [langgenius/dify#9136]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I add models by Ollama, I have tried llava:13b and minicpm-v. I can talk to it without any files. When I try to upload an image and let models to describe it, the models can't work. I have tried to set `max token` to `128` and other parameters are default values, it still not work, but I can use it in OPEN-WEBUI.
![QQ图片20241009230532](https://github.com/user-attachments/assets/38ad734f-2b3b-4cbd-8b55-bd9f7a9f7e47)

### ✔️ Expected Behavior

The LLM can describe image

### ❌ Actual Behavior

It can't run, and give me this tip "Query or prefix prompt is too long, you can reduce the prefix prompt, or shrink the max token, or switch to a llm with a larger token limit size."

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8531
Because the uploaded image will be decoded as base64 string which might be super long. This is is because the limitations of some provides such as Ollama.

**Comment by zuco1111** [comment]
> Duplicated #8531 Because the uploaded image will be decoded as base64 string which might be super long. This is is because the limitations of some provides such as Ollama.

Is there some way to fix it?

**Comment by xieyuy** [comment]
I was encountering the same issue when trying to use gemma 3's visual capabilities. How did you manage to resolve it?

**Comment by h2appy** [comment]
me too

**Comment by Hel5ing** [comment]
same issue with any vision model

**Comment by neocosmic2** [comment]
same issue with gemma 3's visual capabilities

**Comment by Hel5ing** [comment]
> same issue with gemma 3's visual capabilities

I raise the "Model context size" to 409600, then the issue is gone
