### ISSUE TITLE
Increase vision files limit

### ISSUE THREAD

**Issue by Yusaney** [langgenius/dify#9137]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I'm trying to create an OCR tool to read from images, but vision API has a six-image limit. I get this error: "Number of image files exceeds the maximum limit 6". I'm passing the images as URLs in the request to dify, for example:

```
{
    "inputs": {
        "tracking": "xxxxxxxxxxxxxxx"
    },
    "response_mode": "blocking",
    "user": "yyyyyyyyyyyyyyyyyyyyy",
    "files": [
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        },
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        },
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        },
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        },
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        },
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        },
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        },
        {
            "type": "image",
            "transfer_method": "remote_url",
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.webp"
        }
    ]
}
```

Today, Most Vision LLMs can read up to 100 images. This value should be configurable for the user, as six images is a meager limit right now.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Yusaney** [comment]
> You can upload the images one after the other, why do you have to upload more than 6 at once? If your OCR tool allows the user to upload more than 6 images, you can split them into chunks and upload them one by one, or in parallel by calling multiple workflows via API.

Because the images are from the same context, for example, you have an order on SHEIN (they usually make a lot of invoices), and you bought 20 items. You'll probably get 10-15 invoices (10-15 images). The OCR tool that we use checks all the invoices and calculates the values, so they need to be passed in the same context so the numbers match the total calculations.

**Comment by perzeuss** [comment]
> > You can upload the images one after the other, why do you have to upload more than 6 at once? If your OCR tool allows the user to upload more than 6 images, you can split them into chunks and upload them one by one, or in parallel by calling multiple workflows via API.
> 
> Because the images are from the same context, for example, you have an order on SHEIN (they usually make a lot of invoices), and you bought 20 items. You'll probably get 10-15 invoices (10-15 images). The OCR tool that we use checks all the invoices and calculates the values, so they need to be passed in the same context so the numbers match the total calculations.
> 
> And you mentioned the word "upload", which I guess you mean Dify uploads them internally, but remember I'm passing the images as URLs, they are already uploaded to an external server, and the LLMs accept URLs from external sources.

You can still achieve this by sending multiple messages with images to a specific conversation and then asking the LLM to extract information. The images will all be added to a context and the LLM will be able to extract information from previously sent images, just like any other text you've sent before.

Just try it. Send 5 invoices and tell the LLM that you'll need them later. Repeat until you've sent all and then prompt the LLM to perform calculations.

**Comment by Yusaney** [comment]
> > > You can upload the images one after the other, why do you have to upload more than 6 at once? If your OCR tool allows the user to upload more than 6 images, you can split them into chunks and upload them one by one, or in parallel by calling multiple workflows via API.
> > 
> > 
> > Because the images are from the same context, for example, you have an order on SHEIN (they usually make a lot of invoices), and you bought 20 items. You'll probably get 10-15 invoices (10-15 images). The OCR tool that we use checks all the invoices and calculates the values, so they need to be passed in the same context so the numbers match the total calculations.
> > And you mentioned the word "upload", which I guess you mean Dify uploads them internally, but remember I'm passing the images as URLs, they are already uploaded to an external server, and the LLMs accept URLs from external sources.
> 
> You can still achieve this by sending multiple messages with images to a specific conversation and then asking the LLM to extract information. The images will all be added to a context and the LLM will be able to extract information from previously sent images, just like any other text you've sent before.
> 
> Just try it. Send 5 invoices and tell the LLM that you'll need them later. Repeat until you've sent all and then prompt the LLM to perform calculations.

Sorry, maybe I'm missing something, but I don't see how I access a conversation ID in the API when running a workflow scenario. This is not an Agent or Chatbot... The tool is a Workflow with multiple LLMs and a question classifier that chooses the LLM based on the input from my database...

Also, does the proposed solution involve running five times tokens just to tell the LLM not to do anything yet?

**Comment by perzeuss** [comment]
> Sorry, maybe I'm missing something, but I don't see how I access a conversation ID in the API when running a workflow scenario. This is not an Agent or Chatbot... The tool is a Workflow with multiple LLMs and a question classifier that chooses the LLM based on the input from my database...

Ah okay, you're right, the suggested approach wouldn't work with a workflow. You'd have to use a chatflow for this and parse the text answer as JSON.

> Also, does the proposed solution involve running five times tokens just to tell the LLM not to do anything yet?

No, chatflow messages are added to a conversation regardless of whether they are sent to an LLM. You can wait for images and then send the images to the LLM later with just one request. I've shared an example here: https://difyshare.com/flow/6706c7a700024e88036e

However, this is of course relatively cumbersome. A possibility to upload more images directly would definitely be a better solution.

Your scenario is completely valid and the requested feature would definitely be an enhancement. I just wanted to demonstrate that it also works with the current version of Dify.

**Comment by laipz8200** [comment]
Thank you for your suggestion. We will discuss this issue and get back to you once we have made any progress.

**Comment by laipz8200** [comment]
Hi, since our logs and messages pages are not designed to display a large number of files, this change may take longer than expected. If you are self-hosting Dify and only using the service API, you can modify the code yourself to adjust the limits.

**Comment by Yusaney** [comment]
> Hi, since our logs and messages pages are not designed to display a large number of files, this change may take longer than expected. If you are self-hosting Dify and only using the service API, you can modify the code yourself to adjust the limits.

Wow, what super bad news! So, right now, Dify is only usable for niche chats/conversations? If I want to build a workflow that does OCR, is it just not the right platform, as, for some reason, Dify doesn't support multiple images? As said, I run this as a workflow so I don't see why not disabling logs if that's the issue...?


> > Sorry, maybe I'm missing something, but I don't see how I access a conversation ID in the API when running a workflow scenario. This is not an Agent or Chatbot... The tool is a Workflow with multiple LLMs and a question classifier that chooses the LLM based on the input from my database...
> 
> Ah okay, you're right, the suggested approach wouldn't work with a workflow. You'd have to use a chatflow for this and parse the text answer as JSON.
> 
> > Also, does the proposed solution involve running five times tokens just to tell the LLM not to do anything yet?
> 
> No, chatflow messages are added to a conversation regardless of whether they are sent to an LLM. You can wait for images and then send the images to the LLM later with just one request. I've shared an example here: https://difyshare.com/flow/6706c7a700024e88036e
> 
> However, this is of course relatively cumbersome. A possibility to upload more images directly would definitely be a better solution.
> 
> Your scenario is completely valid and the requested feature would definitely be an enhancement. I just wanted to demonstrate that it also works with the current version of Dify.

I tried this workaround. It works with Chatflow but has a huge con: It's a memory-ram killer. Every time I send a request, memory usage increases by 100 MB. After 3 hours of testing, I had about ~25 GB of RAM usage, slowing the whole instance, and I had to reboot the docker to free up space. Is it possible to clear the conversation after the "END" block? Or delete everything? Like I don't want the logs at all..

**Comment by laipz8200** [comment]
Hi @Yusaney! I created a PR to allow changing the upload file limit by setting an environment variable. You can try it out before it gets merged.
