### ISSUE TITLE
[Feature Request]files upload api and chat-messages api allows different file type,not just image

### ISSUE THREAD

**Issue by cskkx1** [langgenius/dify#9144]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

0.10.0-beta Now relase a file upload feature.But not available for using api to upload files or chat-messages.
#9075 
#9110 
Also there are 2 new bugs in beta version

### 2. Additional context or comments

Thanks a lot!

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by laipz8200** [comment]
When uploading a file using the API, you need to first call the /upload endpoint, then construct a structure that includes the file ID. Please refer to the API Access section in your app for details.

**Comment by cskkx1** [comment]
> When uploading a file using the API, you need to first call the `/files/upload` endpoint, then construct a structure that includes the file ID. Please refer to the API Access section in your app for details.

But the endpoint you refered can only upload image file in 0.10.0-beta version.It seems that the beta version didn't update the api.

**Comment by laipz8200** [comment]
Got it! We'll have it fixed in the next version. 😊

**Comment by laipz8200** [comment]
> > When uploading a file using the API, you need to first call the `/files/upload` endpoint, then construct a structure that includes the file ID. Please refer to the API Access section in your app for details.
> 
> But the endpoint you refered can only upload image file in 0.10.0-beta version.It seems that the beta version didn't update the api.

This interface also allows the upload of other file formats, but they have different size limits compared to image files. If you receive an ‘unsupported_file_type’ message, please check whether your request includes the file type (i.e., whether Dify can retrieve the file’s mime_type from the form you submitted).

**Comment by cskkx1** [comment]
> > > When uploading a file using the API, you need to first call the `/files/upload` endpoint, then construct a structure that includes the file ID. Please refer to the API Access section in your app for details.
> > 
> > 
> > But the endpoint you refered can only upload image file in 0.10.0-beta version.It seems that the beta version didn't update the api.
> 
> This interface also allows the upload of other file formats, but they have different size limits compared to image files. If you receive an ‘unsupported_file_type’ message, please check whether your request includes the file type (i.e., whether Dify can retrieve the file’s mime_type from the form you submitted).

Thanks a lot.It was my fault that I didn't  include the file type.The interface works well.
