### ISSUE TITLE
Enhance RAG Capabilities with RAGFlow's DeepDoc Integration

### ISSUE THREAD

**Issue by Howe829** [langgenius/dify#9145]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Since [Ragflow](https://github.com/infiniflow/ragflow/tree/main) has enhanced document-handling capabilities, particularly with [DeepDoc](https://github.com/infiniflow/ragflow/blob/main/deepdoc/README.md), it could be beneficial for Dify to integrate some of these features via Ragflow’s [APIs](https://ragflow.io/docs/dev/api) or [SDK](https://github.com/infiniflow/ragflow/blob/main/sdk/python/README.md). This integration could leverage Ragflow's advanced document processing to improve Dify's performance and functionality.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Yawen-1010** [comment]
Hi, @taowang1993. RAGflow has supported Dify KB API in there latest version. (See https://x.com/infiniflowai/status/1851950422069776644)
You can try connecting to RAGflow's Knowledge using our new feature -- External Knowledge API. Here are the documents that might be helpful:
- https://docs.dify.ai/guides/knowledge-base/connect-external-knowledge
- https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation

**Comment by Yawen-1010** [comment]
I will close this issue as completed. If you encounter any problem during connecting to external knowledge with Dify, you can create a new issue. Again, thank you for your contribution for your community !
