### ISSUE TITLE
[FeatureRequest] Add the option to download the Results of a workflow as a FILE

### ISSUE THREAD

**Issue by Emasoft** [langgenius/dify#9147]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [https://github.com/langgenius/dify/issues/1542](https://github.com/langgenius/dify/issues/1542)).
- [X] \[FOR CHINESE USERS\] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1\. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently the result of a workflow is displayed in the "Result" tab of the test run box. This Result tab only shows the result if it is in json format. But very often that is not the case. Many different output formats can be generated by the workflows, including binaries, XML files, markdown files, html pages, PDFs, rst files, docs, xls, web fonts, svg images, geo files, logs, epubs, csv, css, ssh keys, jupyter notebooks, guf, audio files, etc. Those files are not correctly displayed in the Result tab, and doing copy/paste would damage the content formatting. For example I created a workflow that generated as output XML files, but the Result tab returned an XML that was all escaped wrong, ruining the entire workflow and wasting my money.

PROPOSED SOLUTION:

**Add the option to download the Results (or the 'Results' if it is an Array of files) of a workflow as a FILE or a Zip archive of many files, no matter what is the output format.**

### 2\. Additional context or comments

It would also be useful to be able to download all temp files of a workflow, even if the workflow was interrupted for an error and never completed.
See the following related issues for more on this:

#9121

#9127

### 3\. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by laipz8200** [comment]
We plan to support files in workflows starting from version 0.10.0. After that, you will be able to convert results into files and download them using official or third-party nodes/tools.

**Comment by wuhen8** [comment]
0.10.0 doesn't address which version is expected to add this feature
