### ISSUE TITLE
External Knowledge API Documentation looks wrong

### ISSUE THREAD

**Issue by MrXionGe** [langgenius/dify#9162]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Doc URL
https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation
### Screenshot
![image](https://github.com/user-attachments/assets/7b09e12d-5522-42cd-9d6c-b0efcd6685c1)
### My opinion
“records”. A list of records from querying the knowledge base.
It should be an array. Typically, there are multiple results for knowledge base recall.
An example response would be: 
``` json
{
    "records": [
        {
            "content": "text",
            "score": 0,
            "title": "text",
            "metadata": "text"
        },
        {
            "content": "text",
            "score": 0,
            "title": "text",
            "metadata": "text"
        },
        {
            "content": "text",
            "score": 0,
            "title": "text",
            "metadata": "text"
        }
    ]
}
```

**Comment by AllenWriter** [comment]
Gitbook's issue is that it cannot render the OpenAPI code correctly; 
I have already provided feedback to the Gitbook team.
