### ISSUE TITLE
Knowledge Retrieval Token Limit Clarification

### ISSUE THREAD

**Issue by NourKhdour** [langgenius/dify#9176]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I would like clarification and additional documentation regarding the maximum token length for Knowledge Retrieval queries, Is it the same as Retrieval Testing up to 200 characters or  it follows the same constraints as the model’s token limit?

**Questions:**
Is it better to pass a long document as one chunk or split it into smaller pieces for more effective retrieval?
If splitting is required, what is the optimal chunk size (in tokens or characters) for accurate and complete retrieval?

**Comment by Yawen-1010** [comment]
The maximum length for Knowledge Retrieval queries is the same as Retrieval Testing up to 200 characters. We will specify it in our product document. Thanks for raising this question. @NourKhdour

**Comment by Yawen-1010** [comment]
Document has been updated. 
https://docs.dify.ai/guides/workflow/node/knowledge-retrieval
