### ISSUE TITLE
请问dify有类似fastapi的swagger文档地址吗？

### ISSUE THREAD

**Issue by 948024326** [langgenius/dify#9178]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

请问dify有类似fastapi的swagger文档地址吗？类似如下的， 但我看dify好像是基于flask的，求解答
![image](https://github.com/user-attachments/assets/f32fd238-c672-4984-b080-cea5630e9340)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
#1542

**Comment by asukaminato0721** [comment]
yes, now it has swagger UI.
