### ISSUE TITLE
(Again) Dify forget the conversation history when working through the API.

### ISSUE THREAD

**Issue by mihit** [langgenius/dify#9179]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Call the dify Api, get conversation_id, call the Api again with conversation_id, the dify forget my conversation.

I know this fix.
https://github.com/langgenius/dify/pull/8965
And also this.
https://github.com/langgenius/dify/pull/9132
And this. (Thanks for appropriate title I borrowed.)
https://github.com/langgenius/dify/issues/9130

I confirmed they merged into the main, then pull it, confirmed local code is modified, down and up docker. But they are not helped me.
It's a screenshot of Logs interface. The message count is 3, but conversation memory is only one.

![スクリーンショット 2024-10-10 19 14 27](https://github.com/user-attachments/assets/bae068f4-0268-4dc9-bc7e-701c5eb0bdbb)

### ✔️ Expected Behavior

Forget me not.

### ❌ Actual Behavior

Forgotten.

**Comment by crazywoola** [comment]
These fixes aren't included in v0.9.1.
Pulling code from main branch wont' affect things in docker, it only takes effect in source code development.

The version in our main branch is still v0.9.1.
https://github.com/langgenius/dify/blob/68107fe3554a7af28622fc379eaf7016a78115bb/docker/docker-compose.yaml#L216-L217

**Comment by braiaagency** [comment]
> These fixes aren't included in v0.9.1. Pulling code from main branch won't affect things in docker, it only takes effect in source code development.
> 
> The version in our main branch is still v0.9.1. So you need to rebuild the image then you should be able to use it. If you would like to know how to rebuild image, you need to read docker's docs.
> 
> https://github.com/langgenius/dify/blob/68107fe3554a7af28622fc379eaf7016a78115bb/docker/docker-compose.yaml#L216-L217
> 
> We have a temporary fix in our cloud version, you can verify this in our Cloud environment.
> 
> Please wait until for our next release.

I'm still getting this error on Cloud tough

**Comment by mihit** [comment]
@crazywoola Thanks to you I now know what I did wrong.
