### ISSUE TITLE
change the voice during a chatflow

### ISSUE THREAD

**Issue by remisharrock** [langgenius/dify#9186]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I have a scenario where I want to have multiple voices, different voices for different LLM nodes

### 2. Additional context or comments

it would be nice to be able to change the voice during the chatflow

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
I guess you can implement a demo version to see it.

**Comment by remisharrock** [comment]
This issue is still relevant. I actually implemented it outside of dify for a demo but would to see it inside of dify.
