### ISSUE TITLE
API losing message

### ISSUE THREAD

**Issue by ip2cloud** [langgenius/dify#9187]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

From 0.9.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Until version 0.8.3, communication via the API works without losing messages.

As of 0.9.0, messages are being lost despite the counter confirming that the number of messages is growing.

The attached image shows:

message counter: 4 

but only the last one is registered.

This is causing the flow to restart the conversation every time because there is no memory of the conversation.

This is preventing the use of the API via the WEB only

![Captura de Tela 2024-10-10 às 12 47 25](https://github.com/user-attachments/assets/ebe68da4-3851-4ecd-9167-ddc9e6c25639)

### ✔️ Expected Behavior

Save the previous message to have the flow memory

### ❌ Actual Behavior

Only the last message remains in memory, this is causing the flow to restart

**Comment by ip2cloud** [comment]
in fact the problem is https://github.com/langgenius/dify/discussions/8974 the same but I saw that there was no solution. I am sending the queries as requested by the API. I need help with this bug.

**Comment by ip2cloud** [comment]
As I said before... in the previous version (0.8.3) it is working normally. As of 0.9.0 (0.9.1, 0.10.0-beta1 and 0.10.0-beta2) it is not working. I need help from a human.

**Comment by crazywoola** [comment]
Duplicated, we haven’t released the new version yet together with the fix.

**Comment by ip2cloud** [comment]
Thank you... just to help anyone who arrives here, the version is release-0.9.2. I already tested it and it is resolved
