### ISSUE TITLE
Model Down! I Repeat Model Down!!

### ISSUE THREAD

**Issue by Iamtheoldman** [langgenius/dify#9191]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Git clone https://github.com/langgenius/dify.git

cd docker
cp .env.example .env
docker compose up -d

### ✔️ Expected Behavior

To be able to change out the model from GPT-3.5-Turbo to anything else image below 
<img width="1484" alt="Screenshot 2024-10-10 at 2 51 12 PM" src="https://github.com/user-attachments/assets/77bb559e-e5e2-40aa-8828-00069fb055ef">

### ❌ Actual Behavior

what is going on is you cant edit it or add any type of models 

<img width="1508" alt="Screenshot 2024-10-10 at 2 49 31 PM" src="https://github.com/user-attachments/assets/9a02eb8e-c7ff-43af-b1d1-bb72866b6b99">

**Comment by crazywoola** [comment]
Can't reproduce it.

**Comment by Iamtheoldman** [comment]
Fixed thank you Guys for the help and support never seen anything like it
