### ISSUE TITLE
[BUG] Code Block fails with error: The length of output variable `result` must be less than 80000 characters

### ISSUE THREAD

**Issue by Emasoft** [langgenius/dify#9193]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Create a code block and add it to the workflow.
2. Write any code that generates a string with more than 80000 characters.
3. execute the code block

### ✔️ Expected Behavior

The code block should be able to output more than a measly 80Kb (I hope!) to the next block.

### ❌ Actual Behavior

The code block task fails with the error: "The length of output variable `result` must be less than 80000 characters". 
That doesn’t make any sense. Nothing serious that can be done with just a negligible 80Kb output. Maybe it intended 80Mb? And an error made the limit be reduced by a factor of 10? Even so, it would be too limiting.

**Comment by Emasoft** [comment]
Then you shiuld open a Feature Request to make the value CODE_MAX_STRING_LENGTH customizable at runtime for each workflow. Different workflows have different needs. This limit must be set by the user according to what kind of data he processes.

**Comment by crazywoola** [comment]
We do not plan to adjust this value in our cloud version.

**Comment by mcwongaagpt** [comment]
I use docker compose down
After change .env, 
docker compose -f docker-compose.yaml up -d

The issue is still occur
What is the reason

**Comment by fernvenue** [comment]
I think that will be great if it can be no limit when we set it to `0`.
