### ISSUE TITLE
希望能有官方的QQ群或者微信群

### ISSUE THREAD

**Issue by yummyship** [langgenius/dify#92]
希望能有官方的QQ群或者微信群

**Comment by JohnJyong** [comment]
![screenshot-20230518-175600](https://github.com/langgenius/dify/assets/76649700/bf31df98-b201-44a3-9f7a-ce2c920e0154)
你好，我们现在是有Dify 体验官交流群的哦，欢迎进来交流使用体验和提建议 ，因为每个群都上限了，你可以添加我 然后我将你拉入群中~
