### ISSUE TITLE
Dify has a Swagger document address similar to FastAPI?

### ISSUE THREAD

**Issue by 948024326** [langgenius/dify#9204]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

May I ask if DIY has a Swagger document address similar to FastAPI that i can import to the postman? Similar to the following, but it seems that dify is based on Flask. Please provide an answer
![image](https://github.com/user-attachments/assets/6e559597-f347-45ce-a527-309cf8aa2080)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by 948024326** [comment]
> Yes, Dify provides a Swagger document that can be imported into Postman. The address is `../../.gitbook/assets/Dify-test.openapi.json` [[1]](https://github.com/langgenius/dify-docs/blob/main/jp/guides/knowledge-base/external-knowledge-api-documentation.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

No, i mean, all the Backend API interface，like following
![image](https://github.com/user-attachments/assets/e871f535-3dd3-4f3e-9a74-b506ebbf00a2)

**Comment by crazywoola** [comment]
No we don't have it.
