### ISSUE TITLE
1 validation error for DocumentContext score Input should be a valid number [type=float_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/float_type

### ISSUE THREAD

**Issue by zzzer1** [langgenius/dify#9208]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Issue 1: After the new application is orchestrated, the test error is as follows：

> 1 validation error for DocumentContext score Input should be a valid number [type=float_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/float_type

Issue 2: Click publish-run, the page reports error 404, click back to the home page, it is the home page of ragflow (ragflow is deployed on the same server)
![1728614717492](https://github.com/user-attachments/assets/2296bce3-15c1-41c9-94ea-45b1a86f548f)

### ✔️ Expected Behavior

Ability to answer questions after adding context in a new application

### ❌ Actual Behavior

Unable to answer questions,

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/8957

**Comment by xiayi0409** [comment]
> Duplicated #8957

![image](https://github.com/user-attachments/assets/16b66816-ec84-412a-99a1-dac9760ddf96)
sorry but I still missed this problem
![image](https://github.com/user-attachments/assets/de31425f-ce39-447f-b9bf-06e3310ad911)
and My dify has been updated to the latest version.

**Comment by wuxiulike** [comment]
> > 重复#8957
> 
> ![图像](https://private-user-images.githubusercontent.com/108136801/375701513-16b66816-ec84-412a-99a1-dac9760ddf96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDI5NTYsIm5iZiI6MTcyODY0MjY1NiwicGF0aCI6Ii8xMDgxMzY4MDEvMzc1NzAxNTEzLTE2YjY2ODE2LWVjODQtNDEyYS05OWExLWRhYzk3NjBkZGY5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMDMwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzAwN2I1OGNhYTU5NDk2MmUzZmE4YTMwNjJjMTU3YjllNzE5YzI1Y2JlMWEyNDViNDk0NTM1ZmYzNjRmZjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T6UvTNuQWlkTbeLoB_ZrGZb1TQvho6yHnTm26j4g7G8) 抱歉，但我仍然忽略了这个问题 ，并且我的 dify 已更新到最新版本。 ![图像](https://private-user-images.githubusercontent.com/108136801/375701763-de31425f-ce39-447f-b9bf-06e3310ad911.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDI5NTYsIm5iZiI6MTcyODY0MjY1NiwicGF0aCI6Ii8xMDgxMzY4MDEvMzc1NzAxNzYzLWRlMzE0MjVmLWNlMzktNDQ3Zi1iOWJmLTA2ZTMzMTBhZDkxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMDMwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTExNjZkYjk2MDk1YzU3YTI4MzFmZWQxMTU4ZWQyNTI2MjMyZDg4ZGFkYTI5YzJjMWUwYjRkZWM5MWM0ZGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fjCzNHvvUJHRVE5CADb1PCcTYuL0_Um4sZJmCUxldf4)

me too

**Comment by sanjin1985** [comment]
同样的问题，你解决了吗

**Comment by ymfwjt520** [comment]
同样的问题

**Comment by iquanzhan** [comment]
同样的问题，添加知识库后，就会出现。删除掉知识库就没有错误了

**Comment by bamhill** [comment]
我也是这个问题，发起了一个issue被关联到这里，但貌似还没解决啊。
