### ISSUE TITLE
Cannot see the task_id in workflow log, and hope to support search by task_id

### ISSUE THREAD

**Issue by yippp** [langgenius/dify#9209]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I call the API, I want to find the detail of workflow using task_id, but found that Dify currently do not support search by task_id, and cannot see the task_id in workflow log page.
<img width="1868" alt="image" src="https://github.com/user-attachments/assets/f4f259ce-06cc-4fe9-87e4-69a60a974a36">

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by lyc101011** [comment]
+1
