### ISSUE TITLE
The parameter 'name' in the 'update-by_file' API is incorrectly overwritten by the file name of 'file'.

### ISSUE THREAD

**Issue by glacierck** [langgenius/dify#9211]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

send
`
curl --location --request POST 'http://192.168.1.210/v1/datasets/{dataset_id}/documents/{document_id}/update_by_file' \
--header 'Authorization: Bearer {api_key}' \
--form 'data="{"name":"A.txt","indexing_technique":"high_quality"}";type=text/plain' \
--form 'file=@"/B.txt"'
`

### ✔️ Expected Behavior

The document is named A.txt

### ❌ Actual Behavior

The document is named B.txt

**Comment by glacierck** [comment]
@dosu After determining the format, there is still an error overwrite

**Comment by crazywoola** [comment]
Is this a duplicated https://github.com/langgenius/dify/issues/9177 issue?

**Comment by crazywoola** [comment]
This is an expected behavior according to our dev team.

**Comment by glacierck** [comment]
@crazywoola Not the same one，https://github.com/langgenius/dify/issues/9177 is related to the issue with the 'creat-by_file' interface, while the current issue is related to the 'update-by_file', where the parameter 'name' is invalid.

**Comment by glacierck** [comment]
> This is an expected behavior according to our dev team.

I can't imagine what the expected design goal is. If I only expect to overlay content onto existing documents through files as a carrier, the most basic thing is not to simply provide content overlay, rather than overwriting the name of the original file? Even when I don't submit a 'name', I should keep the original file name instead of being overwritten by a new file name.
