### ISSUE TITLE
API Bug.The 'indexing_status' API cannot query the batch of the' update_by_file 'API

### ISSUE THREAD

**Issue by glacierck** [langgenius/dify#9221]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.Use the 'update_by_file' API to follow the new document and return the batch normally.
2.Use the 'indexing_status' API to query' batch 'progress information.

### ✔️ Expected Behavior

progress info.

### ❌ Actual Behavior

```
{
    "code": "not_found",
    "message": "Documents not found.",
    "status": 404
}
```

Ps. The 'batch' returned by the `create_by_file` api query does not have this issue.

**Comment by glacierck** [comment]
@dosu The update upload has been successfully checked in the web, but the progress information of the update cannot be queried.

**Comment by glacierck** [comment]
@dosu The update has been confirmed to be successful, but the issue is that the 'batch' returned by the API cannot retrieve progress information. 
The 'batch' returned by the new operation does not have this issue

**Comment by glacierck** [comment]
@dosu After testing, I found that it is possible to query the progress of the update through the 'batch' when adding, and once again confirm that the 'batch' returned during the update is invalid. The progress information of the document can only be retrieved through the initial 'batch'.
This should be a serious bug！

**Comment by glacierck** [comment]
@dosu The progress information of 'update-by_file' is incorrectly overwritten by the progress information of 'creat-by_file', and progress can only be queried through the 'batch' returned by 'creat-by_file'

**Comment by imaben** [comment]
+1
