### ISSUE TITLE
Qwen via “TONGYI” is not working in workflow type

### ISSUE THREAD

**Issue by sweellan** [langgenius/dify#9223]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2-beta2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Setup TONGYI as a Model provider.
Create any workflow type of app, select qwen-max in a LLM node. I uploaded an example when testing document extractor but that  is not necessary.
[Testing document extractor - for bug report.zip](https://github.com/user-attachments/files/17338890/Testing.document.extractor.-.for.bug.report.zip)
Test run it.

### ✔️ Expected Behavior

Qwen via "TONGYI” works in all types of app.

### ❌ Actual Behavior

Qwen via "TONGYI” does not work in workflow type of app, as shown in the screenshot. Works fine in chatbot type. Works fine in both types via Siliconflow.
![qwen not working in workflow](https://github.com/user-attachments/assets/185fdebc-3b63-49e3-b6a3-613cf2e9b205)

**Comment by crazywoola** [comment]
Duplicated, please make sure you have searched the issues before posting another one. 
You just need to set the prompt in the `user` instead of `system`.
