### ISSUE TITLE
Why are all descriptions and options blank ? 

### ISSUE THREAD

**Issue by bestofrv66** [langgenius/dify#9227]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

???

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I click on tools, and for exemple select duckduckgo, all descriptions are blank / missing
![2024-10-11_091350](https://github.com/user-attachments/assets/a47eb4b7-1be9-445c-b111-70546267bcb3)

### ✔️ Expected Behavior

to have all descriptions texts available

### ❌ Actual Behavior

Nothing is showing. see screenshot

**Comment by crazywoola** [comment]
![QQ_1728631639190](https://github.com/user-attachments/assets/9174c2d2-68a8-423f-9aed-1d7e71b43961)
Can't reproduce in our cloud.

**Comment by crazywoola** [comment]
Fixed in #8999

**Comment by crazywoola** [comment]
We will upgrade the cloud later.

**Comment by crazywoola** [comment]
It should be fixed now.

**Comment by bestofrv66** [comment]
Transformez votre entreprise grâce à l'IA - Webinaire exclusif le 19 novembre

Bonjour  ,

Imaginez un instant : Chaque jour, vous constatez que la concurrence s'intensifie. Vos équipes sont motivées, mais elles peinent à répondre aux exigences croissantes du marché. Vous savez que l'intelligence artificielle (IA) pourrait être la clé pour débloquer de nouvelles opportunités, mais comment faire le premier pas ?

👉 >S'inscrire au webinaire IA 4 Business (https://djSb8r04.eu1.hubspotlinksfree.com/Ctc/UD+113/djSb8r04/VWBF4h7RTgsjW83hlHw5tzZHdW8Ny6Rt5n7np7N5VHnVn3lcq-W95jsWP6lZ3pTW6RSlVW5n8yWrW1YPF4d9h8wtnW6Sd4vg3rPhpMW5lGz338r2kV9W59YF532c6K8xW2gnd0X64lrlnMb9_9YWv2MKW8k2btt97LWFTW7wxBsf3XX82HW3H9vNT7hYLCKW7LLb1C3zcr3wW5n28pT8R29Z5W7y-8Mt8x_X9vW53m4XV9hdrqbW5FFsN81MRY6zVLRjKG8wbYwSW6LpP_r7fKSzCN2tXRMy9D31wW2m8n0w2nFLkTW3YH7DH7mVbMRW7f8HGh9k1Fk6W5HRT_r3mfd19V3Ht-p53Hc5MW8PNt2y47Xr_lVfbP2B7sL0wRV3FVf43WNW1wN6XhDsKs2kWZW7s7D774r5RhKW3CkBgt2Bh1tKN9c9Cl_GpkkWf9cyFfY04 )

C'est exactement la situation à laquelle de nombreux dirigeants font face aujourd'hui. Les questions fusent :

- Comment choisir les solutions d'IA adaptées à votre marketing, vos ventes, ou vos ressources humaines ?
- Comment préparer vos équipes à cette transformation sans perturber le fonctionnement quotidien ?

Ne laissez pas l'incertitude vous freiner. Rejoignez-nous le mardi 19 novembre 2024 de 11h00 à 12h00 (https://djSb8r04.eu1.hubspotlinksfree.com/Ctc/UD+113/djSb8r04/VWBF4h7RTgsjW83hlHw5tzZHdW8Ny6Rt5n7np7N5VHnVn3lcq-W95jsWP6lZ3pTW6RSlVW5n8yWrW1YPF4d9h8wtnW6Sd4vg3rPhpMW5lGz338r2kV9W59YF532c6K8xW2gnd0X64lrlnMb9_9YWv2MKW8k2btt97LWFTW7wxBsf3XX82HW3H9vNT7hYLCKW7LLb1C3zcr3wW5n28pT8R29Z5W7y-8Mt8x_X9vW53m4XV9hdrqbW5FFsN81MRY6zVLRjKG8wbYwSW6LpP_r7fKSzCN2tXRMy9D31wW2m8n0w2nFLkTW3YH7DH7mVbMRW7f8HGh9k1Fk6W5HRT_r3mfd19V3Ht-p53Hc5MW8PNt2y47Xr_lVfbP2B7sL0wRV3FVf43WNW1wN6XhDsKs2kWZW7s7D774r5RhKW3CkBgt2Bh1tKN9c9Cl_GpkkWf9cyFfY04 )   pour ce webinaire exclusif intitulé "IA 4 Business - Comment s'approprier et déployer l’IA dans votre entreprise ?", animé par vos experts  :

- Hervé Gonay, CEO fondateur de Zenbaia : La première plateforme conçue pour les experts métiers dans la digitalisation via l'intelligence artificielle.

- Christian Jumelet, CEO fondateur de Guid4ai : Le réseau dédié à l’intelligence artificielle éthique responsable collaborative au service de l’humanité

- Didier Serrat, CEO fondateur de Zeebra : Expert en accompagnement des équipes dans l’adoption de l’IA, en mettant l'accent sur la culture d'entreprise et le changement de mindset.

- Philippe Weil - Expert Zeebra : Spécialiste en business développement et en management de la transformation

👉 >S'inscrire au webinaire IA 4 Business (https://djSb8r04.eu1.hubspotlinksfree.com/Ctc/UD+113/djSb8r04/VWBF4h7RTgsjW83hlHw5tzZHdW8Ny6Rt5n7np7N5VHnVn3lcq-W95jsWP6lZ3pTW6RSlVW5n8yWrW1YPF4d9h8wtnW6Sd4vg3rPhpMW5lGz338r2kV9W59YF532c6K8xW2gnd0X64lrlnMb9_9YWv2MKW8k2btt97LWFTW7wxBsf3XX82HW3H9vNT7hYLCKW7LLb1C3zcr3wW5n28pT8R29Z5W7y-8Mt8x_X9vW53m4XV9hdrqbW5FFsN81MRY6zVLRjKG8wbYwSW6LpP_r7fKSzCN2tXRMy9D31wW2m8n0w2nFLkTW3YH7DH7mVbMRW7f8HGh9k1Fk6W5HRT_r3mfd19V3Ht-p53Hc5MW8PNt2y47Xr_lVfbP2B7sL0wRV3FVf43WNW1wN6XhDsKs2kWZW7s7D774r5RhKW3CkBgt2Bh1tKN9c9Cl_GpkkWf9cyFfY04 )

Voici trois raisons de participer :

1. Décodez les solutions d'IA : Apprenez à identifier les outils d'IA qui répondront spécifiquement aux besoins de votre entreprise, que ce soit pour améliorer le marketing, dynamiser les ventes, ou optimiser les ressources humaines.

2. Engagez vos équipes efficacement : Découvrez des stratégies éprouvées pour former et motiver vos collaborateurs dans cette transition, afin qu'ils deviennent des ambassadeurs de l'IA au sein de votre organisation.

3. Assurez un déploiement harmonieux : Obtenez des conseils pratiques pour intégrer l'IA dans vos opérations sans perturber votre activité, en garantissant une transition fluide qui ne laissera personne sur le bord du chemin.

Ne laissez pas la peur de l'inconnu vous paralyser. Chaque jour qui passe sans action, c'est une occasion perdue pour votre entreprise. L'IA n'attend pas : elle est déjà en train de transformer le paysage commercial.

Inscrivez vous dès aujourd'hui à notre webinaire et prenez le contrôle de l'avenir de votre entreprise. Cliquez sur le lien ci-dessous pour réserver votre place :

👉 >S'inscrire au webinaire IA 4 Business (https://djSb8r04.eu1.hubspotlinksfree.com/Ctc/UD+113/djSb8r04/VWBF4h7RTgsjW83hlHw5tzZHdW8Ny6Rt5n7np7N5VHnVn3lcq-W95jsWP6lZ3pTW6RSlVW5n8yWrW1YPF4d9h8wtnW6Sd4vg3rPhpMW5lGz338r2kV9W59YF532c6K8xW2gnd0X64lrlnMb9_9YWv2MKW8k2btt97LWFTW7wxBsf3XX82HW3H9vNT7hYLCKW7LLb1C3zcr3wW5n28pT8R29Z5W7y-8Mt8x_X9vW53m4XV9hdrqbW5FFsN81MRY6zVLRjKG8wbYwSW6LpP_r7fKSzCN2tXRMy9D31wW2m8n0w2nFLkTW3YH7DH7mVbMRW7f8HGh9k1Fk6W5HRT_r3mfd19V3Ht-p53Hc5MW8PNt2y47Xr_lVfbP2B7sL0wRV3FVf43WNW1wN6XhDsKs2kWZW7s7D774r5RhKW3CkBgt2Bh1tKN9c9Cl_GpkkWf9cyFfY04 )

Ne manquez pas cette chance de donner à votre entreprise les moyens de s'épanouir dans un monde où l'IA est incontournable.

Hervé Gonay, 54 rue Greneta, Paris, PARIS 75002, France, 0682518221

Se désabonner (https://hs-143164391.s.hubspotfree-eu1.net/preferences/fr/unsubscribe?data=W2nVjwf3Y2x9hW30CDWZ4rmXcxW2Yshc04hdq6cW2nHW521Bsw_bW49D2v52FG4t_W34B09P3ZNjCGW2vKPKn32FXwVW2HKfTr3XJlvsW3BV_bl2FFJN9W1Nx5qB1L999DW2Yf3gQ3jqHF6W25gXlL1NFlmVW3QWsMG47MLLMW30qBVV3ZYX1xW36457q4pbF6RW1Vbrbn3QKPv9W32CSd72zJ7pQW4kfXG03LFLFdW3ZV6KB36CvTtW4mH-8_2WgvKsW3ZP9YD3N-MVSW1Sj1QK2CHyZCW1XvP4r2w1rlPW43zmsZ3z2_7bW38vR9b1BfJz6W2-fK1d3P0rpCW45VH523dcVKgW3dgpZN32DjfDW3_WJqW43y3k1W3K6jD-2RL5h7W3ZvLFT4fM7vjW2-kXN72w4r1YW3P8N3w3XyvsNW4kmlJr3C0gSQW32hpGL2t6jX4W2vw6W330FlxjW32ywf82t5X2FW3h--Q43GQQy2W2qFd5J2qWNvjW214ZQB3JVqCmW1L5nQF3VyfpdW3LXHKf2WPNSpW1_9RM91SsNJSW24QbM31St5wzW43K9RQ2HT-MMW2WyWWm2zvhRhW1Qy8d52Krs3RW3R60xj3R5BHNW36xkdN3GQTfFW2xQ7V32Kr5b1W4rfhLX36jbyYW2vyfDK3djPXrW1_dGP141z_LqW1_jV8b3VQqSh0&_hsenc=p2ANqtz-_APYkyumwdOT1m3fkqeOGd_6U1vEXWPd-VULpG4G68sTEOEr_K8cda7cu0Od0pijn4w6I4HacZeI5PGx1NizjsWIYcVhGskjbRqZCLJIPm825FfPA3A8LyrE4ZvNoHmbqnDFAqMWCVwxsdJdtHYKeuFNIqmg&_hsmi=98379368 )
Gérer les préférences (https://hs-143164391.s.hubspotfree-eu1.net/preferences/fr/manage?data=W2nVjwf3Y2x9hW30CDWZ4rmXcxW2Yshc04hdq6cW2nHW521Bsw_bW49D2v52FG4t_W34B09P3ZNjCGW2vKPKn32FXwVW2HKfTr3XJlvsW3BV_bl2FFJN9W1Nx5qB1L999DW2Yf3gQ3jqHF6W25gXlL1NFlmVW3QWsMG47MLLMW30qBVV3ZYX1xW36457q4pbF6RW1Vbrbn3QKPv9W32CSd72zJ7pQW4kfXG03LFLFdW3ZV6KB36CvTtW4mH-8_2WgvKsW3ZP9YD3N-MVSW1Sj1QK2CHyZCW1XvP4r2w1rlPW43zmsZ3z2_7bW38vR9b1BfJz6W2-fK1d3P0rpCW45VH523dcVKgW3dgpZN32DjfDW3_WJqW43y3k1W3K6jD-2RL5h7W3ZvLFT4fM7vjW2-kXN72w4r1YW3P8N3w3XyvsNW4kmlJr3C0gSQW32hpGL2t6jX4W2vw6W330FlxjW32ywf82t5X2FW3h--Q43GQQy2W2qFd5J2qWNvjW214ZQB3JVqCmW1L5nQF3VyfpdW3LXHKf2WPNSpW1_9RM91SsNJSW24QbM31St5wzW43K9RQ2HT-MMW2WyWWm2zvhRhW1Qy8d52Krs3RW3R60xj3R5BHNW36xkdN3GQTfFW2xQ7V32Kr5b1W4rfhLX36jbyYW2vyfDK3djPXrW1_dGP141z_LqW1_jV8b3VQqSh0&_hsenc=p2ANqtz-_APYkyumwdOT1m3fkqeOGd_6U1vEXWPd-VULpG4G68sTEOEr_K8cda7cu0Od0pijn4w6I4HacZeI5PGx1NizjsWIYcVhGskjbRqZCLJIPm825FfPA3A8LyrE4ZvNoHmbqnDFAqMWCVwxsdJdtHYKeuFNIqmg&_hsmi=98379368 )

Envoyez un e-mail gratuit aujourd'hui (https://djSb8r04.eu1.hubspotlinksfree.com/Ctc/UD+113/djSb8r04/VWBF4h7RTgsjW83hlHw5tzZHdW8Ny6Rt5n7np7N5VHnTv7lFdnW7lD3J86lZ3mYVSMXGY3l_LRKN8QLHyWmLBNwW7PwCGz1qm8nbW7JBx801tX9WHW8Rx6R81cPGs9M7PC9-XJ5GlW2t852Z5PRj_ZW2QwzB9720VLLW8wBW5f3-DlWkVjTtbZ8Prl3FW6TS1Yj7JztdsM8vZSmmQ9zVW1f_DR76H5pPLW30YxDW6H7763W2hb87Q2P6wwkW2w934J71Dm88W7hzMGY57YQC3W2qcQ958Xbdl3W8z3h6n4-7T4BW3JHyQq86z8b0W3Zy-Pf5Dx4MLW5sBqYL2ysDrdW864Zf96d6Sx3W1TFmcD4sb7FTW44qrc25D14rwW58yS-s7Y1XW9W1N3_bZ8xRS3fW45f11l824QS2W47smfP7-XJ_RW29qJyQ2l8cRvW7-5Rw57b5H7HVp1t5K6DdjPRW5v5kDs4VKHkjW4FNLqd5vwG8WW9561854-fLF2N2VTh12CcN5sW5GTfqP2tXVwRW3BmGbJ4KkTtdW8Ngbnb3ly7rLW1NJ8Lq4J0mHbW4Zn6Gy8d-wByW7NGr0V5t5WCwW8nmFBJ9drPlFW29WDNP5XdflmW9grSY-7mHXjhVC0Q5j2yjqJNW6c3LN56cMxgmW2XLgXk4KpMqVW73SpPx8F6B-jW6lZHLY65qffQW7fLthQ4-vVTZN6V4BB_N-M1GMp003jqh8pDW2S-08F8qxtLwN3hLMKwQxsCxW8xnGP27X-hxYf2-Xrn-04 )

HubSpot (https://djSb8r04.eu1.hubspotlinksfree.com/Ctc/UD+113/djSb8r04/VWBF4h7RTgsjW83hlHw5tzZHdW8Ny6Rt5n7np7N5VHnTv7lFdnW7lD3J86lZ3mYVSMXGY3l_LRKN8QLHyWmLBNwW7PwCGz1qm8nbW7JBx801tX9WHW8Rx6R81cPGs9M7PC9-XJ5GlW2t852Z5PRj_ZW2QwzB9720VLLW8wBW5f3-DlWkVjTtbZ8Prl3FW6TS1Yj7JztdsM8vZSmmQ9zVW1f_DR76H5pPLW30YxDW6H7763W2hb87Q2P6wwkW2w934J71Dm88W7hzMGY57YQC3W2qcQ958Xbdl3W8z3h6n4-7T4BW3JHyQq86z8b0W3Zy-Pf5Dx4MLW5sBqYL2ysDrdW864Zf96d6Sx3W1TFmcD4sb7FTW44qrc25D14rwW58yS-s7Y1XW9W1N3_bZ8xRS3fW45f11l824QS2W47smfP7-XJ_RW29qJyQ2l8cRvW7-5Rw57b5H7HVp1t5K6DdjPRW5v5kDs4VKHkjW4FNLqd5vwG8WW9561854-fLF2N2VTh12CcN5sW5GTfqP2tXVwRW3BmGbJ4KkTtdW8Ngbnb3ly7rLW1NJ8Lq4J0mHbW4Zn6Gy8d-wByW7NGr0V5t5WCwW8nmFBJ9drPlFW29WDNP5XdflmW9grSY-7mHXjhVC0Q5j2yjqJNW6c3LN56cMxgmW2XLgXk4KpMqVW73SpPx8F6B-jW6lZHLY65qffQW7fLthQ4-vVTZN6V4BB_N-M1GMp003jqh8pDW2S-08F8qxtLwN3hLMKwQxsCxW8xnGP27X-hxYf2-Xrn-04 )
