### ISSUE TITLE
When the api is called after 0.8.3 is updated to 0.9.1, only the last item is displayed in the view log

### ISSUE THREAD

**Issue by aileen5150** [langgenius/dify#9231]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When the api is called after 0.8.3 is updated to 0.9.1, only the last item is displayed in the view log

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/pull/8965
See this for updates https://github.com/langgenius/dify/pull/8984
Follow-up pr https://github.com/langgenius/dify/pull/8749

**Comment by aileen5150** [comment]
Update to 0.9.1-fix1 can view the log normally, thank you
