### ISSUE TITLE
how to setup ngnix config,now call api got Bad Getway

### ISSUE THREAD

**Issue by tonyliu088** [langgenius/dify#9238]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }}: {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
when i use this command ,got ip like /docker-api-1: 192.168.192.7192.168.208.4
how to setup in default.conf ?

### ❌ Actual Behavior

docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }}: {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
when i use this command ,got ip like /docker-api-1: 192.168.192.7192.168.208.4
how to setup in default.conf ?

location /v1 {
      proxy_pass http://api:5001;
      include proxy.conf;
    }

**Comment by crazywoola** [comment]
This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
