### ISSUE TITLE
How to modify dify's web page in docker？

### ISSUE THREAD

**Issue by Bulua** [langgenius/dify#9259]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I started the dify project using docker compose. I want to modify the front-end page, for example, hide the ExploreNav option. How should I do it?
![image](https://github.com/user-attachments/assets/e04fc4a5-fafd-422c-8da9-8c0cb553b650)

**Comment by crazywoola** [comment]
Off topic
