### ISSUE TITLE
Can the conversational application API add more parameter?

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#9261]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

- Can the "http://127.0.0.1/v1" interface add a model_config parameter?
- Currently, the interface parameters are too limited to meet the requirements, such as selection of prompts and tools.
- In order to meet the complex usage scenarios of the interface, the community team is urged to consider the matter carefully.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated, we do not plan to add this parameter, we only offer a orchestrated application api to end users.
