### ISSUE TITLE
Cannot find the new api version(2024-09-01-preview) on Azure OpenAI Service Model after upgrade to the newest version

### ISSUE THREAD

**Issue by mrFranklin** [langgenius/dify#9263]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. The old dify version is 0.8.3. It is not contain api version "2024-09-01-preview" on  Azure OpenAI Service Model.
2. Upgrade dify version to 0.9.1-fix1 
3. Still can not find the api version  "2024-09-01-preview" on  Azure OpenAI Service Model.

Is there a cache for the the api version?  So even if I upgrade to the new dify version, It still read the cache.

### ✔️ Expected Behavior

Contains the api version: 2024-09-01-preview on Azure OpenAI Service Model after upgrade to 0.9.1-fix1

### ❌ Actual Behavior

Cannot find the new api version(2024-09-01-preview) on Azure OpenAI Service Model

**Comment by crazywoola** [comment]
This is bug report. For new models please use feature request template.
This model is merged in this pr #9141, which is not included in `0.9.1-fix1`
