### ISSUE TITLE
Add IFRAME_ORIGINS as a New Env Variable

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#9268]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Please add an IFRAME_ORIGINS env variable. 

With this env variable, users can prevent bad actors from embedding their Chatbot.

For example, my website is https://www.example.com

Then setting

IFRAME_ORIGINS=https://www.example.com

will allow only my own website to embed my own chatbot.

Other origins won't be able to embed my chatbot.

Thanks you Dify team!

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This should be enough https://github.com/langgenius/dify/blob/f4ce08211d3c614f6fbffb47d55e3a96678fb78d/docker/.env.example#L33-L37

**Comment by taowang1993** [comment]
> This should be enough
> 
> https://github.com/langgenius/dify/blob/f4ce08211d3c614f6fbffb47d55e3a96678fb78d/docker/.env.example#L27-L37

Sorrry, I don't quite understand how this works.

So if I want to only allow https://embed.example.com to be able to embed my chatbot, I would need to set:

APP_WEB_URL=https://embed.example.com

Then, all other domains will not be able to embed my chatbot. 

Am I right?

**Comment by crazywoola** [comment]
You can set this `WEB_API_CORS_ALLOW_ORIGINS`, if you set this variable, then all requests should be requested from that value you set.
