### ISSUE TITLE
Concurrent API requests to Gemini vision model cause non-responsive behavior and block all tasks forever

### ISSUE THREAD

**Issue by Allamss** [langgenius/dify#9273]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1 / 0.9.2 / 0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.  Configure Gemini  1.5  Pro 001
2.  Create  a  new workflow  using  LLM  with  visual  capabilities to  briefly  analyze  images
3.  Upload  an  image  via  API,  then  make  50  concurrent  API calls  to  execute  the image  analysis  workflow (I m using java, and 20 concurrent calls is fine). The  API  calls  will hang  indefinitely  without returning,  and  all LLM  operations on  the  site  will become  blocked
image:
![31z2b5uzm9](https://github.com/user-attachments/assets/56f132b6-a5c3-4f53-9d5d-2fce6c8c7b79)

4.  According  to the  workflow  logs, LLM  requests are  successfully  returned
 ![image](https://github.com/user-attachments/assets/7c62a7c2-4211-4318-aa90-59397d2c5f65)

5. This  issue  does not  occur  with  GPT vision model

### ✔️ Expected Behavior

Results should be returned normally

### ❌ Actual Behavior

Results are not returned as expected, and the entire site becomes globally blocked. The site can only be restored by restarting

**Comment by Allamss** [comment]
> The issue you're experiencing with the Gemini vision model might be related to how it handles concurrency. Here are a few steps you can take to troubleshoot and potentially resolve the problem:
> 
> 1. **Concurrency Limits**: Check if there are any concurrency limits configured for the Gemini model. If not documented, you might need to experiment with reducing the number of concurrent requests to see if it alleviates the issue.
> 2. **Error Handling**: Ensure that your application is correctly handling any errors returned by the API. The Gemini model has specific error handling mechanisms that map various errors to unified types [[1]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/minimax/llm/llm.py).
> 3. **Resource Allocation**: Compare the resource allocation settings between the Gemini and GPT models. Differences in resource handling might be causing the blockage.
> 4. **Logs and Monitoring**: Utilize Dify's logging and monitoring features to diagnose the issue. The logs can provide insights into what happens during the API calls and why they might be hanging [[2]](https://github.com/langgenius/dify-docs/blob/main/jp/guides/biao-zhu/logs.md).
> 5. **Timeouts and Retries**: Implement timeouts and retries in your API requests to prevent indefinite hanging. This can help manage requests that take too long to process.
> 6. **Version and Configuration**: Ensure that your Dify version and configuration are up to date and correctly set up for high-concurrency scenarios.
> 
> If these steps don't resolve the issue, consider isolating the problem by testing with fewer concurrent requests or different configurations to pinpoint the cause.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

1. The Gemini model has no extra configuration. Crucially, the logs show that Dify's requests to Gemini are returning (with execution time and token usage parameters), indicating that the issue is not caused by limitations.

2. Firstly, the API requests don't return at all but remain blocked indefinitely. I've checked the logs for the web, API, and sandbox containers, and there are no error messages.

3. As per point 1.

4. As per point 1.

5. After the blockage occurs, any API or site LLM requests become blocked as well.

6. I'll try this suggestion later.
@dosu

**Comment by Allamss** [comment]
I’ve tried the latest version 0.9.2, and the issue is still reproducible @crazywoola

**Comment by hw872715125** [comment]
I also encountered this problem

**Comment by Allamss** [comment]
@dosu, In the latest version 0.11.2, the problem can still be reproduced
