### ISSUE TITLE
Received response with content-encoding: gzip, but failed to decode it.

### ISSUE THREAD

**Issue by 397688551** [langgenius/dify#9275]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Self-deployed xinference, self-deployed dify, dify adds embeddings model to display internal server error,
(1) xinference deployed rerank model, audio model can be successful
(2) Only embeddings model can't work. I tried both bge and jina, but it didn't work

<img width="1290" alt="image" src="https://github.com/user-attachments/assets/70f6557f-ec9b-4a07-940e-02b4ed65c903">

Log display：
api-1         | 2024-10-12 08:10:35,383.383 ERROR [Dummy-6635] [app.py:838] - Exception on /console/api/workspaces/current/model-providers/xinference/models [POST]
api-1         | Traceback (most recent call last):
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/response.py", line 481, in _decode
api-1         |     data = self._decoder.decompress(data)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/response.py", line 127, in decompress
api-1         |     ret += self._obj.decompress(data)
api-1         | zlib.error: Error -3 while decompressing data: incorrect header check
api-1         | 
api-1         | The above exception was the direct cause of the following exception:
api-1         | 
api-1         | Traceback (most recent call last):
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/requests/models.py", line 816, in generate
api-1         |     yield from self.raw.stream(chunk_size, decode_content=True)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/response.py", line 1060, in stream
api-1         |     data = self.read(amt=amt, decode_content=decode_content)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/response.py", line 970, in read
api-1         |     decoded_data = self._decode(data, decode_content, flush_decoder)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/response.py", line 485, in _decode
api-1         |     raise DecodeError(
api-1         | urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
api-1         | 
api-1         | During handling of the above exception, another exception occurred:
api-1         | 
api-1         | Traceback (most recent call last):
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1         |     rv = self.dispatch_request()
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1         |     resp = resource(*args, **kwargs)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1         |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1         |     resp = meth(*args, **kwargs)
api-1         |   File "/app/api/controllers/console/setup.py", line 65, in decorated
api-1         |     return view(*args, **kwargs)
api-1         |   File "/app/api/libs/login.py", line 93, in decorated_view
api-1         |     return current_app.ensure_sync(func)(*args, **kwargs)
api-1         |   File "/app/api/controllers/console/wraps.py", line 22, in decorated
api-1         |     return view(*args, **kwargs)
api-1         |   File "/app/api/controllers/console/workspace/models.py", line 151, in post
api-1         |     model_provider_service.save_model_credentials(
api-1         |   File "/app/api/services/model_provider_service.py", line 250, in save_model_credentials
api-1         |     provider_configuration.add_or_update_custom_model_credentials(
api-1         |   File "/app/api/core/entities/provider_configuration.py", line 390, in add_or_update_custom_model_credentials
api-1         |     provider_model_record, credentials = self.custom_model_credentials_validate(model_type, model, credentials)
api-1         |   File "/app/api/core/entities/provider_configuration.py", line 370, in custom_model_credentials_validate
api-1         |     credentials = model_provider_factory.model_credentials_validate(
api-1         |   File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 123, in model_credentials_validate
api-1         |     model_instance.validate_credentials(model, filtered_credentials)
api-1         |   File "/app/api/core/model_runtime/model_providers/xinference/text_embedding/text_embedding.py", line 139, in validate_credentials
api-1         |     self._invoke(model=model, credentials=credentials, texts=["ping"])
api-1         |   File "/app/api/core/model_runtime/model_providers/xinference/text_embedding/text_embedding.py", line 54, in _invoke
api-1         |     embeddings = handle.create_embedding(input=texts)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/xinference_client/client/restful/restful_client.py", line 120, in create_embedding
api-1         |     response = requests.post(url, json=request_body, headers=self.auth_headers)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
api-1         |     return request("post", url, data=data, json=json, **kwargs)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
api-1         |     return session.request(method=method, url=url, **kwargs)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
api-1         |     resp = self.send(prep, **send_kwargs)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/requests/sessions.py", line 747, in send
api-1         |     r.content
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/requests/models.py", line 899, in content
api-1         |     self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/requests/models.py", line 820, in generate
api-1         |     raise ContentDecodingError(e)
api-1         | requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

### ✔️ Expected Behavior

I want to add the embeddings model successfully

### ❌ Actual Behavior

I want to add the embeddings model successfully

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this persists.

**Comment by houhongxu** [comment]
same issue in web

"message": "('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"

**Comment by houhongxu** [comment]
curl 'https://cloud.dify.ai/console/api/workspaces/current/model-providers/langgenius/openai_api_compatible/openai_api_compatible/models' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  -H 'authorization: ***
  -H 'baggage: sentry-environment=production,sentry-public_key=c0bcc0e36783694f41e4fb1e6a3efea9,sentry-trace_id=aca87c69e01b435bb4ffe4d9a3171a86,sentry-sample_rate=0.1,sentry-sampled=false' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -b 'cookieyes-consent=consentid:ZUZMV1BoWnU4enFaUDhpMlJKQk0xS3ZISmxBSXBNOVQ,consent:yes,action:yes,necessary:yes,functional:yes,analytics:yes,performance:yes,advertisement:yes,other:yes; _ga=GA1.1.771065353.1745474398; _ga_VDCLZ7W3S5=GS2.1.s1746867994$o2$g0$t1746867997$j57$l0$h0; locale=en-US' \
  -H 'origin: https://cloud.dify.ai' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://cloud.dify.ai/apps?category=chat&isCreatedByMe=true' \
  -H 'sec-ch-ua: "Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sentry-trace: aca87c69e01b435bb4ffe4d9a3171a86-ac896a70369f5aef-0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36' \
  --data-raw '{"model":"text-embedding-ada-002","model_type":"text-embedding","credentials":{"mode":"chat","context_size":"4096","max_tokens_to_sample":"4096","agent_though_support":"not_supported","function_calling_type":"no_call","stream_function_calling":"not_supported","vision_support":"no_support","structured_output_support":"not_supported","stream_mode_delimiter":"\\n\\n","voices":"alloy","display_name":"text-embedding-ada-002","endpoint_model_name":"text-embedding-ada-002","endpoint_url":"https://api.***.ai/apis/v1","api_key":"***"},"load_balancing":{"enabled":false,"configs":[]}}'
