### ISSUE TITLE
Batch call to upload document interface resulted in incorrect document numbering, with duplicate numbering.

### ISSUE THREAD

**Issue by glacierck** [langgenius/dify#9276]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Call 'create_by_file' to upload ten documents

2. Check the upload results on the web

![image](https://github.com/user-attachments/assets/740bce0d-e460-410f-9da4-425aec195e3b)

### ✔️ Expected Behavior

Obtain documents from 1 to 10

### ❌ Actual Behavior

Number 4 is repeated.

ps.Is the serial number meaningful? Why is it necessary to assign a fixed serial number without ensuring uniqueness?

**Comment by glacierck** [comment]
@dosu Additionally, information on the total number of documents should also be provided on the document list view.

**Comment by Blubiubiu** [comment]
> @dosu Additionally, information on the total number of documents should also be provided on the document list view.此外，还应在文档列表视图中提供有关文档总数的信息。

I have not been able to reproduce the issue with duplicate indices. Could you provide more detailed steps to reproduce the problem? The changes for counting the total have been submitted in a PR #9321
