### ISSUE TITLE
I have written a custom API tool that returns a PNG file, but it does not display images on dify

### ISSUE THREAD

**Issue by baiyi-os** [langgenius/dify#9283]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![5F8DFC36-2FD4-4442-88AB-6DA215D232A0](https://github.com/user-attachments/assets/b8acb6ad-57fb-41b3-9c10-7c610ebee50d)
![DB82637F-A181-48d1-8DB3-884155C98A4F](https://github.com/user-attachments/assets/284c2e3c-d701-4da3-aab1-88d62406c0ca)

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
You need to return it as a url

**Comment by baiyi-os** [comment]
Can be used, thank you very much

**Comment by FAFUuser** [comment]
Hello, I would like to ask about a file parsing service I developed. The service accepts a file as a parameter. When publishing this as a custom tool, does it support file uploads? If it does support file uploads, how should I write the OpenAPI specification?

**Comment by Sakura4036** [comment]
> Hello, I would like to ask about a file parsing service I developed. The service accepts a file as a parameter. When publishing this as a custom tool, does it support file uploads? If it does support file uploads, how should I write the OpenAPI specification?

@crazywoola  i have the same question! How to write the OpenAPI specification to support file uploads?
