### ISSUE TITLE
Application Displaying Abnormally After Upgrading to Dify 0.9.1-fix1 - What Could Be the Cause?

### ISSUE THREAD

**Issue by Yi-Lyu** [langgenius/dify#9285]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[WowStudio-pipeline-workflow.yml.txt](https://github.com/user-attachments/files/17350231/WowStudio-pipeline-workflow.yml.txt)

<img width="929" alt="image" src="https://github.com/user-attachments/assets/f67b804e-6dc4-4ae1-966c-33bf4a771a3c">

I'm experiencing an issue with my application after upgrading Dify from version 0.8.3 to 0.9.1-fix1. Previously, my application was functioning normally in the 0.8.3 environment. However, after the upgrade, I'm encountering abnormal behavior when accessing the application.

To provide more context, I've exported the DSL (Domain Specific Language) of my application and converted it to a text file, which I've attached to this issue for reference.

Could someone please help me understand why this is happening and how to resolve it? Any insights or suggestions would be greatly appreciated.

**Comment by iamjoel** [comment]
@Yi-Lyu The app is created by https://github.com/langgenius/dify/releases/tag/0.10.0-beta1. And it's not compatible in 0.9.1-fix1.

**Comment by Yi-Lyu** [comment]
> @Yi-Lyu I run the app and found that the app is created by https://github.com/langgenius/dify/releases/tag/0.10.0-beta1. And it's not compatible in 0.9.1-fix1. Run the app in 0.10.0-beta1 would be ok.

thanks
