### ISSUE TITLE
loops in workflow

### ISSUE THREAD

**Issue by Namec999** [langgenius/dify#9291]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

currently i want to ask the parameter extractor node 3 times at max, if the result found is not correct, 

i tried to attach and IFELSE node to a previous node in the workflow, but no connection can be made

any solutions for ?

thank you 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9121
