### ISSUE TITLE
CosyVoice audio service bug with xinference

### ISSUE THREAD

**Issue by 00drdelius** [langgenius/dify#9299]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I was deploying Cosyvoice for tts with xinference in dify. However, I encountered two unexpected errors as followed:
1. raised from api/services/audio_service.py:
```
AssertionError: The setup method 'after_request' can no longer be called on the blueprint 'service_api'.
It has already been registered at least once, any changes will not be applied consistently.
Make sure all imports, decorators, functions, etc. needed to set up the blueprint are done before registering it.
```
![image](https://github.com/user-attachments/assets/a998d283-0346-4240-a72c-110d48b74a01)

I just commented `from app import app` and `with app.app_context():` and the error gone.
I'm not familiar with flask, but I think it's not really necessary to `import app` here?

2. raised from api/core/model_runtime/model_providers/xinference/tts/tts.py
```
Parallel generation is not supported by llama-cpp-python
```
![image](https://github.com/user-attachments/assets/873bbfaf-3914-4968-842b-6a86f337b062)

CosyVoice deployed by xinference dose not support parallel generation currenly, so it's not appropriate to use ThreadPoolExecutor here.
Related issue: https://github.com/xorbitsai/inference/issues/2386

And btw, according to Line 21, [cosyvoice.yaml](https://huggingface.co/model-scope/CosyVoice-300M/blob/main/cosyvoice.yaml), max text token is 51866. Hence I think it's not so precise as marked below:

api/core/model_runtime/model_providers/xinference/tts/tts.py
![image](https://github.com/user-attachments/assets/45813c29-b877-40b6-9b1f-7be61349b326)

**Comment by kkjinping** [comment]
Same question.

**Comment by songleipu123** [comment]
same problem
