### ISSUE TITLE
私有化部署账号密码存在哪里了？

### ISSUE THREAD

**Issue by lcm1475** [langgenius/dify#93]
目前好像只支持cloud的注册登录
install时候设置的账号密码是写死的吗？ 如果不是写死的话 能不能开放个api出来 就可以做注册登录的逻辑了

**Comment by takatost** [comment]
不是写死的，EDITION=SELF_HOSTED 模式是支持登录注册的

**Comment by yuhao1118** [comment]
> 不是写死的，EDITION=SELF_HOSTED 模式是支持登录注册的

请问这个功能有规划什么时候上线吗？

**Comment by takatost** [comment]
您是说上线我们的云端版吗

**Comment by yuhao1118** [comment]
> 您是说上线我们的云端版吗

不是的。在SELF_HOSTED版私有部署时，似乎只能注册一个帐号(在访问/install的时候），install之后就没有办法注册新的帐号了（同时也不能拉人进workspace）。不知道这是bug还是产品设计逻辑就是这样？

**Comment by lcm1475** [comment]
目前打算走install的setup api方法 再继续创建其他用户 但是要修改里面的单次注册逻辑

**Comment by takatost** [comment]
> 

暂未实现哈，后续补上

**Comment by seiriosPlus** [comment]
遇到了同样的问题， 关注中.

**Comment by tongxiaolong01** [comment]
cd api 目录，
```
flask reset-password 
```

**Comment by DemonDamon** [comment]
为啥我进去直接就是登录，邮箱是啥都不知道

**Comment by ge2001** [comment]
忘记管理员邮箱怎么办，要到哪里看我曾经填写的邮箱

**Comment by Mazhenjie9** [comment]
> 怎么办，要到哪里看我曾经填写的邮箱

同问啊 头大

**Comment by ltx0633** [comment]
> 忘记管理员邮箱怎么办，要到哪里看我曾经填写的邮箱

进数据库中查看

```
 psql -U postgres

 \c dify;
select email from accounts;
```

**Comment by dsazdf312** [comment]
> > 
> 
> 暂未实现哈，后续补上

大佬 现在多用户可以注册了吗
