### ISSUE TITLE
Conversation_id does not maintain the conversation context

### ISSUE THREAD

**Issue by eduardocodes** [langgenius/dify#9304]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm using n8n + Dify to integrate a chat flow into WhatsApp.

1. Send a message without conversation_id

![image](https://github.com/user-attachments/assets/ff82f0f1-27fa-42d4-87f7-32311f64f875)

2. Send a message with conversation_id

![image](https://github.com/user-attachments/assets/5f2651a6-a842-4072-953d-52bc1c5d7d17)

3. Send a message with the same conversation_id again. Reply to the same answer as step 1

![image](https://github.com/user-attachments/assets/2936a0dd-a771-4d00-b593-97c73dc4109b)
![image](https://github.com/user-attachments/assets/e7e6dbc0-b404-4922-9df5-12d4479b5954)

Always LLMs in chat flow have memory:

![image](https://github.com/user-attachments/assets/99af57e7-2116-425a-a663-627608c7fa77)

### ✔️ Expected Behavior

The chat should ask the user what he feels (it is a chatbot for a clinic).

### ❌ Actual Behavior

The chat does not maintaining the conversation context even I passing the conversation_id.

**Comment by crazywoola** [comment]
See fix1
