### ISSUE TITLE
Add "fetch_from_remote"

### ISSUE THREAD

**Issue by taowang1993** [langgenius/dify#9306]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

The docs says:
```
These three configuration methods can coexist, meaning a provider can support predefined-model + customizable-model or predefined-model + fetch-from-remote, etc. This allows using predefined models and models fetched from remote with unified provider credentials, and additional custom models can be used if added.
```

But all model providers are not configured with the "fetch from remote" feature.

Is this a paid feature? 

Or 

Do we need to add this feature mannually by adding FETCH_FROM_REMOTE = "fetch-from-remote" inside api/core/model_runtime/entities/model_entities.py

```
class FetchFrom(Enum):
    """
    Enum class for fetch from.
    """

    PREDEFINED_MODEL = "predefined-model"
    CUSTOMIZABLE_MODEL = "customizable-model"
```

Then add it to the provider yaml file?

```
configurate_methods:
  - predefined-model
  - fetch-from-remote
```

How does this work?

Thanks you, Dify Team.

**Comment by crazywoola** [comment]
This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).

**Comment by crazywoola** [comment]
In future releases
