### ISSUE TITLE
I am a beginner. I used docker to deploy dify. I hope to add the packages I want, such as pandas, in the sanbox environment so that I can use them in the code node. I hope to get a more detailed step.

### ISSUE THREAD

**Issue by Monster-Beast** [langgenius/dify#9307]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/2818f48f-3836-49ef-b0c5-29ecb3390dd5)

I have entered the sandbox and executed pip install pandas. I can also see the version of pandas in the environment, but when I import pandas, an error occurs: error: operation not permitted. In addition, I have read many issues and found that I can modify the dockerfile to do it, but I am a novice. Can you give me a detailed step-by-step guide? Thank you.

**Comment by crazywoola** [comment]
Duplicated
