### ISSUE TITLE
Multiple Simultaneous HTTP Requests Triggered in Dify v0.9/v0.10

### ISSUE THREAD

**Issue by Yi-Lyu** [langgenius/dify#9312]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0-beta2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgrading from Dify v0.8 to v0.9 or v0.10, I've encountered an issue with the HTTP request component when calling API endpoints of other Dify applications. The problem manifests as each HTTP request component initiating multiple requests simultaneously, which is unexpected behavior.

Steps to Reproduce:

1.Set up two Dify applications: Application A and Application B.
2.In Application A, configure three HTTP request components to call Application B's API.
3.Trigger the workflow in Application A.

Expected Behavior: Application B should receive three separate requests from Application A, one for each HTTP request component.

Actual Behavior: Application B receives nine requests from Application A. The logs from Application B show that for each incoming request from A, three simultaneous requests are initiated at the same time.

Additional Information:

- This issue did not occur in Dify v0.8, where the behavior was normal.
- I have attached a screenshot of Application B's logs showing the multiple requests.
- The DSL file for Application A is also attached for reference.

Environment:

- Dify version: v0.9 or v0.10 (please specify the exact version)
- Deployment method: (e.g., Docker, cloud service, etc.)
- Operating system: (if applicable)

Impact: This issue is affecting our production environment and needs to be addressed urgently.

<img width="2384" alt="image" src="https://github.com/user-attachments/assets/2ef998ee-1a66-4535-a832-d7c68d636d75">

[temp @ 吕毅.yml.txt](https://github.com/user-attachments/files/17359803/temp.%40.yml.txt)

**Comment by Yi-Lyu** [comment]
<img width="2302" alt="image" src="https://github.com/user-attachments/assets/b40c9a0d-e800-436e-8675-0f27f634cf0b">

From the screenshot, it appears that after initiating multiple requests, one of them actually succeeded. Does the new version of Dify keep connecting until it gets one successful result?

**Comment by Yi-Lyu** [comment]
When I change 3 http concurrent requests to 1 in my A application, the error is reported as in the screenshot below:

<img width="2702" alt="image" src="https://github.com/user-attachments/assets/466255ee-c921-4655-b9c0-d1e23becb9c9">

The logs of application B show that it is still being requested by A four times, with three failures and one success. As shown in the screenshot below.

<img width="2333" alt="image" src="https://github.com/user-attachments/assets/0f5b7a3c-e31e-478c-a689-0418ac39cfee">

**Comment by Yi-Lyu** [comment]
helllo ?

**Comment by laipz8200** [comment]
This may be caused by retries of the request, check ssrf_proxy.py and if necessary you can set SSRF_DEFAULT_MAX_RETRIES=0
