### ISSUE TITLE
use azure o1-mini o1-preivew model save error and use chat error

### ISSUE THREAD

**Issue by zbjlala** [langgenius/dify#9327]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1.add o1-mini o1-preivew model in azure save error 
error msg:Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}
 param temperature=0,max_tokens=20 not support

2.use o1-mini o1-preivew error
_num_tokens_from_messages use tiktoken 0.7.0 not support o1 model 0.8.0support

### ✔️ Expected Behavior

azure o1 model use

### ❌ Actual Behavior

error and can't use

**Comment by somethingwentwell** [comment]
Check this PR: https://github.com/langgenius/dify/pull/9326
