### ISSUE TITLE
We can't use the Docker environment

### ISSUE THREAD

**Issue by lymanzhao** [langgenius/dify#9329]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Hello! We can't use the Docker environment. Could you please tell me how to install Dify in a clean Ubuntu Linux environment? I haven't found the help document.

**Comment by crazywoola** [comment]
https://docs.dify.ai/getting-started/install-self-hosted/local-source-code Read the docs please.
