### ISSUE TITLE
Firecrawl Tool：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by louisLiu1004** [langgenius/dify#9337]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Using Firecrawl (Self Hosted Docker) to request any website from any node.

### ✔️ Expected Behavior

Crawl and read the returned webpage content.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/d4a85dca-0044-4dc0-9040-75da2e64ea7b)

**Comment by ujway** [comment]
I have the same issue. Currently I use JinaReader instead at this moment.
It seems to be not reproduced in Cloud version.

This cloud be related:
https://github.com/langgenius/dify/issues/8792

**Comment by hjlarry** [comment]
can't reproduce,  I also use a self-host firecrawl,  it works well

**Comment by hjlarry** [comment]
> @hjlarry So any suggestions?

I think you can try the scrape tool of firecrawl first, because it is simpler than the crawl tool.
if it not works, try to debug this [line](https://github.com/langgenius/dify/blob/7d3dad3d1d2c64379c24184faa22e2ce1ad26490/api/core/tools/provider/builtin/firecrawl/firecrawl_appx.py#L40) to check what is the response
the firecrawl also supply admin panel `http://localhost:3002/admin/@/queues`, you can get more information here.

**Comment by TChengZ** [comment]
> can't reproduce, I also use a self-host firecrawl, it works well

do u self-host firecrawl in your computer or in the service, it works well when i self-hosted in my computer,but once i publish it on the service, it won't work

**Comment by hjlarry** [comment]
> do u self-host firecrawl in your computer or in the service, it works well when i self-hosted in my computer,but once i publish it on the service, it won't work

dify just send a simple http request to the firecrawl server,  so the key point to solve this issue is to check what's the response of this request from dify's api server
