### ISSUE TITLE
In chat mode, the conversation hits the knowledge base search error

### ISSUE THREAD

**Issue by jlokys** [langgenius/dify#9338]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Upgraded version to 0.9.2
In chat mode, the conversation hits the knowledge base search error, as follows:
```
Traceback (most recent call last):
  File "E:\wsm\dify\api\core\app\apps\chat\app_generator.py", line 203, in _generate_worker
    runner.run(
  File "E:\wsm\dify\api\core\app\apps\chat\app_runner.py", line 159, in run
    context = dataset_retrieval.retrieve(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\wsm\dify\api\core\rag\retrieval\dataset_retrieval.py", line 235, in retrieve
    retrieval_resource_list = sorted(retrieval_resource_list, key=lambda x: x.get("score"), reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

The index mode of the knowledge base settings is set to Economical, and there is no score field in the search results, and an error is reported during subsequent execution.
![image](https://github.com/user-attachments/assets/8cd15b02-8ad9-4ad5-9bd0-972be52172a0)

**Comment by zykee** [comment]
I miss the same problem, and I deploy it with docker.

**Comment by tearfulDalvik** [comment]
same problem
