### ISSUE TITLE
After updating to 0.9.2, workflow with knowledge retrieval became unexecutable due to lack of rerank model

### ISSUE THREAD

**Issue by mabuchs** [langgenius/dify#9341]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [ ] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. In model setup, only setup LLM models. (without any rerank models)
2. Create workflow and include knowledge retrieval node
3. Try \[Run\]

DSL for the workflow is attatched.
[sampleflow.yml.txt](https://github.com/user-attachments/files/17366557/sampleflow.yml.txt)

### ✔️ Expected Behavior

Workflow can be executed even if rerank model is not enabled on Dify.

### ❌ Actual Behavior

After reproduction steps, it shows error "Rerank model is required". This didn't occur until v0.9.1.
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/0cda3320-535f-4bbd-8e2e-dcb18c673c3e">

**Comment by crazywoola** [comment]
Set a rerank model here.

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/04f9609a-82f2-4bbe-b1a3-3e7d1d23185c">

**Comment by mabuchs** [comment]
Thank you for response. 

Yes, I know how to set rerank model. But I want to know if I can use knowledge retrieval node in an environment without rerank model (due to restirction of model selection in company).

Let me confirm: using knowledge retrieval without rerank model became completely unsupported (even if using Weighted Score)? 
(In v0.9.1, I could use it if I use only one knowledge and weighted score)

**Comment by mabuchs** [comment]
@crazywoola Could you kindly confrim the question above?

**Comment by fniu** [comment]
This issue remains. I cannot run my app from the workflow editor due to this error, while the app can be published without any problem. @crazywoola Could you please reconsider this issue? I have also sent an email for support.

**Comment by kurokobo** [comment]
@mabuchs @fniu 
Hi, could you please change the setting of the knowledge retrieval node back to Weighted Score again and check if it works as it did before?
![image](https://github.com/user-attachments/assets/a38e9be0-a7ff-4774-8feb-2fd3d7eac4ee)

**Comment by fniu** [comment]
> @mabuchs @fniu Hi, could you please change the setting of the knowledge retrieval node back to Weighted Score again and check if it works as it did before? 

I think this issue may only exist for workflows that are created before 0.9.2. I have tested it with new workflows which seem to work fine. For existing workflows, I have changed different settings back and forth, and the issue still remains. One action may be able to fix it though (I came across by accident), which is to click tab "Monitoring" and then back to "Orchestrate" and the error was gone.

**Comment by kkjinping** [comment]
@crazywoola @kurokobo There is still this problem in the external knowledge

**Comment by MengXiangyu0624** [comment]
seem problem we meet😭

**Comment by mabuchs** [comment]
I tried creating new workflow on latest version, then I confirmed this has been resolved. thank you!
