### ISSUE TITLE
Model text-embedding-3-large credentials is not initialized

### ISSUE THREAD

**Issue by hugoaaviana** [langgenius/dify#9345]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.92

### Cloud or Self Hosted

Cloud

### Steps to reproduce

"When I upload a file to DIFY's knowledge base during the Preprocessing and Text Cleaning stage, it generates the following error: 'Model text-embedding-3-large credentials is not initialized.'"

### ✔️ Expected Behavior

Fix the bug.

### ❌ Actual Behavior

Stop

**Comment by hugoaaviana** [comment]
![image](https://github.com/user-attachments/assets/e0aacabf-8a65-444d-948d-d72f0e512852)

**Comment by crazywoola** [comment]
Few things need to be clarifeid:
- Did you try to embed knowledge before successfully?
- Did you set the model in the system model providers?
<img width="803" alt="image" src="https://github.com/user-attachments/assets/6065ecc0-46ef-49ab-88de-95f8d27dfdd3">
