### ISSUE TITLE
Workflows that need a long time to produce output time out

### ISSUE THREAD

**Issue by infinitnet** [langgenius/dify#9346]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When running a workflow as an app, if the workflow takes a long time to stream output, it times out and the workflow output is only accessible through workflow logs. This is an issue with workflows that need a long execution time before they produce output.

### ✔️ Expected Behavior

It should be possible to get output from workflows that take a long time to send output. Long and complex loops, data processing, etc can take time.

### ❌ Actual Behavior

Instead of output, there's an error message that the workflow timed out and the output is only accessible through workflow logs.

**Comment by crazywoola** [comment]
Try to set this environment variable 
https://github.com/langgenius/dify/blob/d15ba3939d39c14fd52cd2566bc3bf04cdf5f1f2/docker/docker-compose.yaml#L276

**Comment by infinitnet** [comment]
> Try to set this environment variable
> 
> https://github.com/langgenius/dify/blob/d15ba3939d39c14fd52cd2566bc3bf04cdf5f1f2/docker/docker-compose.yaml#L276

This makes the error message disappear, but the output canvas still stays empty after the workflow finished and does out display the output. That's only visible in the logs.

<img width="1233" alt="Screenshot at Oct 15 08-42-31" src="https://github.com/user-attachments/assets/9322020e-2c32-4e49-8f24-87ea3393f9f6">

**Comment by infinitnet** [comment]
`WORKFLOW_MAX_EXECUTION_TIME` seems to be the right setting.

**Comment by clickflow1** [comment]
> `WORKFLOW_MAX_EXECUTION_TIME` seems to be the right setting.

Did it work in your case?

**Comment by infinitnet** [comment]
> > `WORKFLOW_MAX_EXECUTION_TIME` seems to be the right setting.
> 
> Did it work in your case?

Yes, but I also increased `TEXT_GENERATION_TIMEOUT_MS` together with `WORKFLOW_MAX_EXECUTION_TIME`

**Comment by shengxianli** [comment]
> > > `WORKFLOW_MAX_EXECUTION_TIME`似乎是正确的设置。
> > 
> > 
> > 就你的情况来说它有用吗？
> 
> 是的，但我也增加`TEXT_GENERATION_TIMEOUT_MS`了`WORKFLOW_MAX_EXECUTION_TIME`

I adjusted the WORKER-TIMEOUT of the. evn and docker-compose.yaml file to 180, but it doesn't seem to work
I am using Docker Compose deployment, what do I need to do after modifying it

**Comment by Lisiyuan233** [comment]
I meet the same problem with you，it need to restart your Docker containers to apply the new settings:
docker compose stop
docker compose up -d
