### ISSUE TITLE
It would be great if LLM nodes could specify the model through variables

### ISSUE THREAD

**Issue by GaoXianSheng132** [langgenius/dify#9347]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I have been developing user-friendly applications smoothly and flexibly, but the only limitation I feel is that LLM nodes cannot modify parameters such as model name and temperature through variables. I hope to make nodes more flexible and support variable configuration

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated, we do not have a plan for this.
