### ISSUE TITLE
1 validation error for DocumentContext score Input should be a valid number [type=float_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/float_type

### ISSUE THREAD

**Issue by sanjin1985** [langgenius/dify#9351]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![dify_bug](https://github.com/user-attachments/assets/18c75fa8-4a80-4943-9dec-788cc0714b9c)

### ✔️ Expected Behavior

how to resolve the problem？

**Comment by crazywoola** [comment]
Duplicated
