### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by sofs2005** [langgenius/dify#9353]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have successfully run the Dify server using Docker Compose, and I can connect to external APIs. However, I also deployed an API server on my local network, and when I tried to add it in the OpenAI-API-compatible section, I received an error stating that the route could not be obtained. This api can work on other applications with the same settings

### ✔️ Expected Behavior

can connect to api on LAN network

### ❌ Actual Behavior

Raise error message:
An error occurred during credentials validation: HTTPConnectionPool(host='10.6.6.89', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x147930c8c5e0>: Failed to establish a new connection: [Errno 113] No route to host')).

**Comment by crazywoola** [comment]
Try to figure out the networks between containers.

**Comment by sofs2005** [comment]
> Try to figure out the networks between containers.
i tried to discribe it:
<img width="476" alt="20241015115911" src="https://github.com/user-attachments/assets/a373d82d-d825-4d7d-a1b3-22c6dd7da505">

**Comment by sofs2005** [comment]
> > Try to figure out the networks between containers.
> > i tried to discribe it:
> 
> <img alt="20241015115911" width="476" src="https://private-user-images.githubusercontent.com/14013284/376451957-a373d82d-d825-4d7d-a1b3-22c6dd7da505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjUxNjEsIm5iZiI6MTcyODk2NDg2MSwicGF0aCI6Ii8xNDAxMzI4NC8zNzY0NTE5NTctYTM3M2Q4MmQtZDgyNS00ZDdkLWExYjMtMjJjNmRkN2RhNTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA0MDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZjQ4NTRiNDdiNDZjMTBlY2JjMTk2ODg2OGEzNmNjZDM4ZTA3MTgyZDJkMTRjZTMyMDNhZDAxMGEzMDEwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2PwuV5ZHJ32zwVpE8lT-HMp6Ss27Vv_SyvYt6piKzn4">

For other Docker containers, I assigned LAN network addresses using the ipvlan method. However, I haven't figured out how to modify the network access for Dify, which uses Docker Compose, to connect to my LAN. I suspect this is the reason.

**Comment by sofs2005** [comment]
OK， I fixed it by adding dify docker in to my network.

**Comment by SilverUnicorn** [comment]
hey i've met the same problem, may i ask how to add dify docker in to server network?
