### ISSUE TITLE
When the knowledge base deletes a document, it does not clean up the index results created with the document

### ISSUE THREAD

**Issue by boHam-wang** [langgenius/dify#9354]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I created a knowledge base using the document 'test01.txt', then I created a workflow using the knowledge base, and then used this workflow to start a conversation, the answer has the reply with the right related document 'test01.txt'.
Now, I update the knowledge using another similar document 'test02.txt', and delete the old document. Then start the chat again. I found the answer has two re
![企业微信截图_17289623371727](https://github.com/user-attachments/assets/58aa2b6f-8177-4592-9ea4-79a4d854a423)
lated documents, including not only the new document but also the old one.

### ✔️ Expected Behavior

I expected only the new document in the knowledge base to be related, the old document has been deleted which is not expected to appear in the answer.

### ❌ Actual Behavior

Both the new and old documents appear in the answer

**Comment by crazywoola** [comment]
Is this a new conversation?

**Comment by boHam-wang** [comment]
> Is this a new conversation?

Yes, I start a new conversation and have the same problem.

**Comment by boHam-wang** [comment]
Add: I can still query the old document records in the PostgreSQL database.

**Comment by boHam-wang** [comment]
Add: All my upload files are stored in s3 cos, I found that all the files were stored in the cos bucket, including the files that had been deleted

**Comment by crazywoola** [comment]
The deletion is handled by celery workers. I suggest you to upgrade to latest version to see if this persists. Because we are not going to create a diverted branch for legacy versions.
