### ISSUE TITLE
Less flexibility in studio configuration

### ISSUE THREAD

**Issue by starweavingdream** [langgenius/dify#9359]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

How can I enable the file upload function of Dify's studio on the page? Or is it only the workflow that has the function of uploading files? I traced the code and found that the file upload configuration of the studio is hard-coded in the `service_api\app\app.py` file. Can some configurations be placed on the page for dynamic configuration?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
See things in v0.10 not beta, we will release that next week.
