### ISSUE TITLE
v0.9.2 can't connect to vector database

### ISSUE THREAD

**Issue by kandada** [langgenius/dify#9364]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

连不上向量数据库

### ✔️ Expected Behavior

--

### ❌ Actual Behavior

--

**Comment by crazywoola** [comment]
Please provide more information when you open a issue. A single sentence is not enough to guess what's going on. Hence, you need to use English to submit a report.
