### ISSUE TITLE
Variable assignement from Code node

### ISSUE THREAD

**Issue by Namec999** [langgenius/dify#9372]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

How to assign a value to a variable directly usi,g the Code node (from my python code i mean)
because i have multiple variables and want only one code node, for better management

**Comment by crazywoola** [comment]
I think you can create a object for multiple values, this is the only way to fulfill your request for now.
