### ISSUE TITLE
Cannot find module 'lodash/camelCase' when try generating icons

### ISSUE THREAD

**Issue by HJrookie** [langgenius/dify#9376]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. add icons to  dify\web\app\components\base\icons\assets\vender\other\  
2. run command `pnpm gen-icons` in directory `dify\web`  
3. console show error  `Error: Cannot find module 'lodash/camelCase'`

this is the icons new added:  
![image](https://github.com/user-attachments/assets/9a699ab4-db0e-43c5-993f-ef010c14d33d)

console error : 
![image](https://github.com/user-attachments/assets/ebda42d8-656b-43c5-b0aa-dec95807e1fe)

script.js file :  
![image](https://github.com/user-attachments/assets/eae41bab-d76b-4916-aa28-7ecc5c4e0245)

### ✔️ Expected Behavior

after running `pnpm gen-icons`  ,all  icons will be regenerated and no error occur

### ❌ Actual Behavior

after running `pnpm gen-icons`, console show error   `Error: Cannot find module 'lodash/camelCase'`

**Comment by HJrookie** [comment]
thanks . I try to  replace   
```
const camelCase = require('lodash/camelCase')
const template = require('lodash/template')
```
to  
```
import {camelCase,template} from "lodash-es"
```
and   replace  
```
const path = require('node:path')
```
to 
```
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const path = require('node:path')
import { dirname } from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
```
, and I add `    "type":"module",` to package.json , 
finally , `pnpm gen-icons` can run successfully

**Comment by HJrookie** [comment]
That's ok , But I don't know why . And `pnpm dev` will show error

**Comment by crazywoola** [comment]
Usually you don't modify these things, which icons you modify here?
