### ISSUE TITLE
Using pandas on code block: error: operation not permitted

### ISSUE THREAD

**Issue by hyojunada** [langgenius/dify#9377]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I added pandas in advanced dependencies in code block

This is a dummy code I wrote. 

```
import pandas as pd

def main(a: int, b: int) -> dict:
    df = pd.DataFrame({'a':[a], 'b':[b]})
    return {'result':a+b}
```
whenever I use pandas in the main function I get an error that says error:operation not permitted

### ✔️ Expected Behavior

pandas to be imported

### ❌ Actual Behavior

got error: operation not permitted

**Comment by hyojunada** [comment]
I am using pandas in cloud, how can I check sandbox environment?

**Comment by hyojunada** [comment]
But I am using Dify in cloud enviornment

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md
Our cloud environment is a cluster environment, we do not modify the default settings to suit for `pandas`. And sandbox is designed for lightweight tasks, I think you can implement a serverless function to use it.

**Comment by hyojunada** [comment]
@crazywoola 
So, I'm a novice in clouds/server stuff. I'm more of an end user. 
I would appreciate if you can explain in more laymans term, is dify is not suitable for pandas? why does it have a drop down for pandas on the advanced import? I used pandas last week and it did not give me any errors. 

Thanks

<img width="391" alt="Screenshot 2024-10-16 at 10 00 44 AM" src="https://github.com/user-attachments/assets/c45576a1-4191-4eed-bdd9-c5abc7f036cd">
