### ISSUE TITLE
Change OpenAI default testing model to gpt-4o-mini

### ISSUE THREAD

**Issue by jasonkang14** [langgenius/dify#9384]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The current Dify configuration mandates enabling GPT-3.5-turbo to add an API key. However, GPT-3.5-turbo has been deprecated and is costlier compared to GPT-4o-mini, which offers superior performance at a lower cost. It would be beneficial to consider updating the configuration to support GPT-4o-mini, optimizing both performance and cost efficiency

### 2. Additional context or comments

It would be advantageous if Dify utilized GPT-4o-mini for integrating OpenAI's models instead of GPT-3.5-turbo. GPT-4o-mini not only offers enhanced performance but also provides a more cost-effective solution compared to the now deprecated GPT-3.5-turbo.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by telmoss7** [comment]
I'm having the same problem, but after the changes that u put it remains still the same model on default.
Shouldn't the default model be upgraded to gpt-4o-mini with that changes?
Or should be something more changed ?
