### ISSUE TITLE
Run failed: Failed to invoke tool: Object of type FileVar is not JSON serializable

### ISSUE THREAD

**Issue by hufangdong86** [langgenius/dify#9386]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3-0.9.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/97efb7ff-24f6-4e93-9f9e-13ae72397724)
![image](https://github.com/user-attachments/assets/6ef6fd59-dbfb-4c92-b16b-ff20e1c043d4)
![image](https://github.com/user-attachments/assets/e0edd62e-225c-476d-bdc7-1b13a489f2fb)

**Comment by hufangdong86** [comment]
Version 0.6.11 is normal, but it becomes abnormal from version 0.8.2 onwards.

**Comment by hufangdong86** [comment]
> Hello, @hufangdong86! I'm here to assist you with any bugs, questions, or contributions. I can help you while waiting for a human maintainer.
> 
> To resolve the error "Object of type FileVar is not JSON serializable" in Dify version 0.8.3-0.9.2, you need to ensure that `FileVar` objects are converted to a JSON-serializable format before serialization. This can be done by modifying the `_convert_tool_messages` method to convert `FileVar` objects to dictionaries using a method like `to_dict()` before returning them. Here's an example of how you might adjust the code:
> 
> ```python
> def _convert_tool_messages(self, messages: list[ToolInvokeMessage]) -> tuple[str, list[dict], list[dict]]:
>     """
>     Convert ToolInvokeMessages into tuple[plain_text, files, json]
>     """
>     # transform message and handle file storage
>     messages = ToolFileMessageTransformer.transform_tool_invoke_messages(
>         messages=messages,
>         user_id=self.user_id,
>         tenant_id=self.tenant_id,
>         conversation_id=None,
>     )
>     # extract plain text and files
>     files = self._extract_tool_response_binary(messages)
>     plain_text = self._extract_tool_response_text(messages)
>     json = self._extract_tool_response_json(messages)
> 
>     # Convert FileVar objects to dictionaries
>     files_as_dicts = [file_var.to_dict() for file_var in files]
> 
>     return plain_text, files_as_dicts, json
> ```
> 
> This change ensures that the `files` list contains dictionaries instead of `FileVar` objects, making it JSON serializable [[1]](https://github.com/langgenius/dify/blob/main/api/core/workflow/nodes/tool/tool_node.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

But the chart is not displayed.

![image](https://github.com/user-attachments/assets/89cdc0d7-f762-4253-bc3b-f981f5f8eee7)

**Comment by hufangdong86** [comment]
@dosu

**Comment by hufangdong86** [comment]
@dosu  def _convert_tool_messages(self, messages: list[ToolInvokeMessage]) -> tuple[str, list[dict], list[dict]]:
    """
    Convert ToolInvokeMessages into tuple[plain_text, files, json]
    """
    # transform message and handle file storage
    messages = ToolFileMessageTransformer.transform_tool_invoke_messages(
        messages=messages,
        user_id=self.user_id,
        tenant_id=self.tenant_id,
        conversation_id=None,
    )
    # extract plain text and files
    files = self._extract_tool_response_binary(messages)
    plain_text = self._extract_tool_response_text(messages)
    json = self._extract_tool_response_json(messages)

    # Convert FileVar objects to dictionaries
    files_as_dicts = [file_var.to_dict() for file_var in files]

    return plain_text, files_as_dicts, json

But the chart is not displayed.

![image](https://github.com/user-attachments/assets/74a11f9e-a0fc-4f13-9b45-738c48d4b10e)

**Comment by laipz8200** [comment]
Hello! Could you provide the minimal DSL that can reproduce this issue?

**Comment by hufangdong86** [comment]
[llm.txt](https://github.com/user-attachments/files/17388617/llm.txt)
[charts.txt](https://github.com/user-attachments/files/17388619/charts.txt)

charts is a workflow 

@laipz8200

**Comment by hufangdong86** [comment]
@laipz8200 Hello, have you located the issue?

**Comment by laipz8200** [comment]
It will be fixed in v0.10.0. If you want, you can try [v0.10.0-beta3](https://github.com/langgenius/dify/releases/tag/0.10.0-beta3) before we release it.
