### ISSUE TITLE
The basic chatbot which has knowledge input failed to give any response.

### ISSUE THREAD

**Issue by kkjinping** [langgenius/dify#9388]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0-beta3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a basic chatbot.
2. Add ecological knowledge to the context.
3. Talk to the bot about something related to the knowledge.
4. The bot has no response.

### ✔️ Expected Behavior

normal response

### ❌ Actual Behavior

no response

### DDL

[TestBot.yml.zip](https://github.com/user-attachments/files/17393127/TestBot.yml.zip)

**Comment by crazywoola** [comment]
Please provide a DSL to reproduce the problem.

**Comment by kkjinping** [comment]
> Please provide a DSL to reproduce the problem.

Added in the original text already.

**Comment by kkjinping** [comment]
@crazywoola

**Comment by kkjinping** [comment]
0.10.0 can‘’t reproduce
