### ISSUE TITLE
q&a adds split sources

### ISSUE THREAD

**Issue by silence-pan84** [langgenius/dify#9390]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Can we add the source of the current q&a in the document to the results returned by the q&a

### 2. Additional context or comments

The q&a is generated from those parts of the document, or paragraphs, so that Operations can easily check the accuracy of the q&a.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
What kind of source do you want to add? Can you provide more details?

**Comment by silence-pan84** [comment]
> What kind of source do you want to add? Can you provide more details?

The q&a is generated from those parts of the document, or paragraphs, so that Operations can easily check the accuracy of the q&a.

**Comment by silence-pan84** [comment]
> What kind of source do you want to add? Can you provide more details?



> ### Self Checks
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### 1. Is this request related to a challenge you're experiencing? Tell me about your story.
> Can we add the source of the current q&a in the document to the results returned by the q&a
> 
> ### 2. Additional context or comments
> The q&a is generated from those parts of the document, or paragraphs, so that Operations can easily check the accuracy of the q&a.
> 
> ### 3. Can you help us with this feature?
> * [ ]  I am interested in contributing to this feature.

**Comment by silence-pan84** [comment]
Question and answer pairs are generated from those parts of the document or paragraph so that the operator can easily check the accuracy of the question and answer.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langgenius/dify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月16日(星期三) 上午10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langgenius/dify] q&amp;a adds split sources (Issue #9390)





 
What kind of source do you want to add? Can you provide more details?
