### ISSUE TITLE
“Tokens maximum recursion depth exceeded while calling a Python object”

### ISSUE THREAD

**Issue by Jas0nxlee** [langgenius/dify#9397]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0beta3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="839" alt="image" src="https://github.com/user-attachments/assets/d036a265-be4a-4ee9-a141-fe83531594e0">

**Comment by kkjinping** [comment]
I find that only when the variable is set to the Context will this problem occur. Setting the variable directly to the SYSTEM will not.

**Comment by fniu** [comment]
Came across the same issue. Any progress on this? Thanks!

**Comment by leoterry-ulrica** [comment]
also encountering the same issue

**Comment by SimonUTD** [comment]
it seems because the file is tooo big and the content is toooo long. i upload a 1.5mb txt file and get the same issue, but after i shorter the file, it works

**Comment by fniu** [comment]
> it seems because the file is tooo big and the content is toooo long. i upload a 1.5mb txt file and get the same issue, but after i shorter the file, it works

I don't think this is the reason. It fails for me with normal size context. FYI, I am using the Cloud service.

This issue is getting quite annoying. Could you please prioritize this issue? Thanks @crazywoola or someone else I should ping.

**Comment by fniu** [comment]
After some debugging, I suspect that this has something to do with the content of the retrived trunks. When there are long sequences of dots, such as "............." (also present in the screenshot by the original author of this issue), LLMs tend to fail with this error. Hope this helps.

**Comment by ip2cloud** [comment]
Hi.. it's still running even in version 0.10.0 of 10/21/24
![image](https://github.com/user-attachments/assets/d6e3e4b4-24ed-42df-aafe-ccc862ab2a63)
