### ISSUE TITLE
Environment variable "INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH" configuration is not available

### ISSUE THREAD

**Issue by Alven-yx** [langgenius/dify#9399]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.9.1-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have changed the value of "INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH" in the environment variable to 4000：
And set the segment length to 3000。
When recording：![image](https://github.com/user-attachments/assets/3766bca6-49ed-44ab-ba31-1c6f9d8359e5)
Submit:
![image](https://github.com/user-attachments/assets/eed4c87b-c5fb-4194-884b-69d7766e2ac2)

### ✔️ Expected Behavior

Successfully enter a document whose segments are custom segments in the knowledge base

### ❌ Actual Behavior

Throwing an exception

**Comment by crazywoola** [comment]
I think you need to inspect the docker container to see if it's actually working.

**Comment by Alven-yx** [comment]
> 我认为您需要检查 docker 容器以查看它是否真的正常工作。

I think I know why this is happening，I use k8s deployment, this environment variable is not added to the dify-worker by default, only included in the dify-api。
The modification worked，Thanks。I will close this issue

**Comment by Alven-yx** [comment]
> I think you need to inspect the docker container to see if it's actually working.

I found the cause of the problem.，I use k8s deployment, this environment variable is not added to the dify-worker by default, only included in the dify-api。
The modification worked，Thanks。I will close this issue
