### ISSUE TITLE
api service alway restart

### ISSUE THREAD

**Issue by jonzha9527** [langgenius/dify#9403]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Docker Compose version v2.21.0
docker compose start api service, and console log as below:

```
docker-api-1  | Running migrations
docker-api-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
docker-api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
docker-api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml
docker-api-1  | INFO:matplotlib.font_manager:generated new fontManager
docker-api-1  | /entrypoint.sh: line 8:     7 Killed                  flask upgrade-db
docker-api-1  | Running migrations
docker-api-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
docker-api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
docker-api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml
docker-api-1  | Preparing database migration...
docker-api-1  | /entrypoint.sh: line 8:     7 Killed                  flask upgrade-db
docker-api-1 exited with code 0
```

### ✔️ Expected Behavior

api serivce running normally

### ❌ Actual Behavior

api service restart again and again, cpu be used by celery and gunicorn more than 50%.

**Comment by wangsl1997** [comment]
@jonzha9527 I have the same problem, have you solved it, and what is the method?
![Snipaste_2024-10-23_16-59-48](https://github.com/user-attachments/assets/cf4d6cd6-0ab6-4ae0-a1fe-62909d156f0a)
