### ISSUE TITLE
When I generate a picture directly and return it, the operation page will freeze.

### ISSUE THREAD

**Issue by sunxiaojia123** [langgenius/dify#9415]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

<img width="1942" alt="image" src="https://github.com/user-attachments/assets/619f5b34-317b-442c-9729-6509846ad117">
# Description
Hello, the problem is that after the workflow is completed and the results are output, it still shows "Running" and the page is stuck here.

### ✔️ Expected Behavior

I want to directly output a generated image, and it is already displayed in the file format. The content of the file is as follows:
<img width="356" alt="image" src="https://github.com/user-attachments/assets/0697fa26-9df5-4ff8-898a-1cbe8e4a9fc7">
The image I want to output is already displayed in the field, which is the image below:
https://upload.dify.ai/files/tools/44d69fa1-f4a6-47c4-99b9-5b298f414baa.png?timestamp=1729069628&nonce=3c8894836fed9df98737e88b79e0008a&sign=jY4zmoZX71ZrBhHl1AFBwacf922N1QQ31IZl9PlUXP4=

### ❌ Actual Behavior

1. Why can the output image be accessed temporarily, but will be 403 after a while ({"code":"forbidden","message":"Invalid request.","status":403})
2. Why does it keep getting stuck after the output is displayed, and the status keeps showing "running", and I can't stop it

**Comment by crazywoola** [comment]
> Why can the output image be accessed temporarily, but will be 403 after a while ({"code":"forbidden","message":"Invalid request.","status":403})

This is simple to save the cost of cloud platform.

> Why does it keep getting stuck after the output is displayed, and the status keeps showing "running", and I can't stop it
Need to investigate it.
