### ISSUE TITLE
function update_text lack created_by_role

### ISSUE THREAD

**Issue by LoveUAsEver** [langgenius/dify#9418]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0-beta3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

use create datasets document api

### ✔️ Expected Behavior

create success

### ❌ Actual Behavior

server 500

**Comment by crazywoola** [comment]
This is resolved in v0.10.1, but you need to remove the old v0.10.1 containers and pull it again.
https://github.com/langgenius/dify/discussions/9748
