### ISSUE TITLE
Unexpected Response: 500 (Internal Server Error) Raw response content: b'{"status":{"error":"Service internal error: 1 of 1 read operations failed:\\n Service internal error: Tonic status error: status: Unavailable, message: \\"Failed to connect to http://lg-qdrant-node- ...'

### ISSUE THREAD

**Issue by YehChengLin** [langgenius/dify#9420]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Unexpected Response: 500 (Internal Server Error) Raw response content: b'{"status":{"error":"Service internal error: 1 of 1 read operations failed:\\n Service internal error: Tonic status error: status: Unavailable, message: \\"Failed to connect to http://lg-qdrant-node- ...'; Unexpected Response: 500 (Internal Server Error) Raw response content: b'{"status":{"error":"Service internal error: 1 of 1 read operations failed:\\n Service internal error: Tonic status error: status: Unavailable, message: \\"Failed to connect to http://lg-qdrant-node- ...'

### ✔️ Expected Behavior

Unexpected Response: 500 (Internal Server Error) Raw response content: b'{"status":{"error":"Service internal error: 1 of 1 read operations failed:\\n Service internal error: Tonic status error: status: Unavailable, message: \\"Failed to connect to http://lg-qdrant-node- ...'; Unexpected Response: 500 (Internal Server Error) Raw response content: b'{"status":{"error":"Service internal error: 1 of 1 read operations failed:\\n Service internal error: Tonic status error: status: Unavailable, message: \\"Failed to connect to http://lg-qdrant-node- ...'

### ❌ Actual Behavior

Unexpected Response: 500 (Internal Server Error) Raw response content: b'{"status":{"error":"Service internal error: 1 of 1 read operations failed:\\n Service internal error: Tonic status error: status: Unavailable, message: \\"Failed to connect to http://lg-qdrant-node- ...'; Unexpected Response: 500 (Internal Server Error) Raw response content: b'{"status":{"error":"Service internal error: 1 of 1 read operations failed:\\n Service internal error: Tonic status error: status: Unavailable, message: \\"Failed to connect to http://lg-qdrant-node- ...'

**Comment by YehChengLin** [comment]
@dosu The version I am using is the online version of Dify, not the Docker version.

**Comment by lvshuaigg** [comment]
I also encountered the same problem. When I registered an account on our public network and uploaded the document for vectorization, it kept showing a queue. At the same time, the same error message appeared during the recall test. Please take a look at our public network system. How can I solve it?

**Comment by JohnJyong** [comment]
Due to some network fluctuations, the service is currently running normally. thanks for your feedback~
