### ISSUE TITLE
Display the icon/image of an app in the published version

### ISSUE THREAD

**Issue by jasonkang14** [langgenius/dify#9429]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, users can update the application icon during testing; however, after publishing, the default robot emoji is displayed during chat interactions. Would you be interested in a feature that allows the uploaded custom icon to be used in place of the default robot emoji after the app is published, should the user choose to modify their app icon?

<img width="1055" alt="Screenshot 2024-10-17 at 9 28 42 AM" src="https://github.com/user-attachments/assets/07612233-887d-4f66-b1fe-72ef2cccd2c1">

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/ab27b8c8-88d8-4c77-81eb-a6bb32ecf0e8">
