### ISSUE TITLE
How to upload third-party packages to the cloud dify 

### ISSUE THREAD

**Issue by Bourne-alt** [langgenius/dify#9432]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When running Python code to access a database on Cloud Dify, importing the third-party package mysql.connector will result in the following error:Traceback (most recent call last): File "/var/sandbox/sandbox-python/tmp/9645b516_83cb_48d8_803d_8bb8ac5218f7.py", line 48, in <module> File "<string>", line 4, in <module> ModuleNotFoundError: No module named 'mysql' error: exit status 255
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/0ac3c680-6336-49ae-a81e-9f54bb3525d1">

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Please use HTTP service to call custom external services instead.
