### ISSUE TITLE
Switching from local storage to cloud storage solutions, such as Amazon S3 or Alibaba Cloud OSS.

### ISSUE THREAD

**Issue by yaohongfenglove** [langgenius/dify#9434]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

This will benefit developers who initially use local storage but later want to switch to cloud storage ([#1513](https://github.com/langgenius/dify/issues/1513)), I'd like to contribute code by adding Flask commands. The code would look something like this:

# code
api/commands.py
```python
@click.command("upload-private-key-file-to-cloud-storage", help="upload private key file to cloud storage")
@click.option("--tenant_id", prompt=False, help="tenant_id")
def upload_private_key_file_cloud_storage(tenant_id: Optional[str] = None):
    """
    upload private.pem to cloud storage
    """
    click.echo(
        click.style(
            "Start upload private.pem to cloud storage",
            fg="green",
        )
    )

    if not tenant_id:
        click.echo(click.style("Warning: did not provide an tenant_id, it will be auto queried in the database", fg="yellow"))
        tenants_list: List[Tenant] = Tenant.query.all()
        tenants = [item.id for item in tenants_list]
    else:
        tenants = [tenant_id, ]

    for tenant_id in tenants:
        click.echo(
            click.style(
                f"Current tenant_id is: {tenant_id}",
                fg="green",
            )
        )

        file_key = f"privkeys/{tenant_id}/private.pem"
        with open(f"{os.environ.get('STORAGE_LOCAL_PATH', 'storage')}/{file_key}", "rb") as f:
            file_content = f.read()
        storage.save(filename=file_key, data=file_content)
        click.echo(
            click.style(
                "Congratulations! file uploaded. link: {}".format(f'https://{os.environ.get("OSS_BUCKET_DOMAIN_NAME", "galaxy-spiders.oss-cn-shenzhen.aliyuncs.com")}/{file_key}'),
                fg="green",
            )
        )


@click.command("upload-local-files-to-cloud-storage", help="upload local files to cloud storage")
def upload_local_files_to_cloud_storage():
    """
    upload local files to cloud storage
    """
    click.echo(
        click.style(
            "Start upload local files to cloud storage",
            fg="green",
        )
    )

    # TODO 2024-10-9 If the amount of data is large, it must be queried in batches
    files: List[UploadFile] = UploadFile.query.filter_by(storage_type="local").all()

    click.echo(
        click.style(
            f"files count: {len(files)}",
            fg="green",
        )
    )

    for file in files:
        target_filepath = f"{os.environ.get('STORAGE_LOCAL_PATH', 'storage')}/{file.key}"

        # if the file exists
        if not os.path.exists(target_filepath):
            click.echo(
                click.style(
                    f"Warning! file not exist. filepath: {target_filepath}, ignore this, continue",
                    fg="yellow",
                )
            )
            continue

        # Upload to cloud storage
        with open(target_filepath, "rb") as f:
            file_content = f.read()
        storage.save(filename=file.key, data=file_content)
        click.echo(
            click.style(
                f"File uploaded. file.key: {file.key}",
                fg="green",
            )
        )

        # Update database record
        file.storage_type = os.environ["STORAGE_TYPE"]
        db.session.commit()
        click.echo(
            click.style(
                f"file.storage_type updated to database. file.key: {file.key}",
                fg="green",
            )
        )

    click.echo(
        click.style(
            "Congratulations! finish files uploaded.",
            fg="green",
        )
    )


def register_commands(app):
    # other code
    app.cli.add_command(upload_private_key_file_cloud_storage)
    app.cli.add_command(upload_local_files_to_cloud_storage)
```

# add to docs 
[Self-Host Related](https://docs.dify.ai/learn-more/faq/install-faq)

**17.1 Migrating from Local Storage to Cloud Storage**

If you want to migrate files from local storage to cloud storage, such as Alibaba Cloud OSS, you need to migrate data from the 'upload_files' and 'privkeys' folders within your local storage directory. Here are the steps:

### Steps:
1. Modify environment variables
    If you start from local source code, modify the environment variables in the .env file to the cloud storage you want to migrate to. For example: STORAGE_TYPE=aliyun-oss，then configure the Alibaba Cloud OSS storage settings.

    If you start from docker-compose, modify the environment variables in the docker-compose.yaml file to the cloud storage you want to migrate to, For example: STORAGE_TYPE=aliyun-oss，then configure the Alibaba Cloud OSS storage settings.

2. Execute the following commands:
   For uploading private key files:
   start from local source code：```flask upload-private-key-file-to-cloud-storage```
   start from docker-compose: ```docker exec -it docker-api-1 flask upload-private-key-file-to-cloud-storage```

   For uploading local files:
   start from local source code：```flask upload-local-files-to-cloud-storage```
   start from docker-compose: ```docker exec -it docker-api-1 flask upload-local-files-to-cloud-storage```

### 2. Additional context or comments

https://github.com/langgenius/dify/issues/1513

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Cool, free free to open a pull request. :)
