### ISSUE TITLE
Start Frontend Docker Container Separately

### ISSUE THREAD

**Issue by janglichao** [langgenius/dify#9435]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.92

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I followed guide book to start frontend docker separately,but cannot login ,it show some errors like this:
![image](https://github.com/user-attachments/assets/d782e8a5-00ea-4f2c-b833-8ce0dde8f649)

### ✔️ Expected Behavior

working well

### ❌ Actual Behavior

errors

**Comment by janglichao** [comment]
here is log:
![image](https://github.com/user-attachments/assets/66945ec9-4b13-4cdd-8cbf-b3866829cd70)

**Comment by crazywoola** [comment]
This log seems good to me, please check the environment variables you passed to the frontend docker image.

**Comment by janglichao** [comment]
> This log seems good to me, please check the environment variables you passed to the frontend docker image.

which variables?I only run command to start docker then visit frontend page :docker run -it -p 3000:3000 -e CONSOLE_API_URL=http://127.0.0.1:5001 -e APP_API_URL=http://127.0.0.1:5001 langgenius/dify-web:0.9.2
