### ISSUE TITLE
How to abandon interface permission authentication？

### ISSUE THREAD

**Issue by 948024326** [langgenius/dify#9440]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

now i want to give up the auth, like bear token
![image](https://github.com/user-attachments/assets/00c3602e-6308-4e6f-b8e6-0a8a7abd4f1e)

i delete all the decorators of api auth, and rebuild the project, but it still the same
![image](https://github.com/user-attachments/assets/056fa026-2be0-4a5c-b97a-435084727b11)

Is there a simple method or config to solve my question?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
No you should not abandon it.

**Comment by 948024326** [comment]
> No you should not abandon it.

OK
