### ISSUE TITLE
External knowledge base succedded in "Retrieval Testing" but failed after attach it to an agent

### ISSUE THREAD

**Issue by nicklhy** [langgenius/dify#9448]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Add a external knowledge base (RAGFlow) and test it with the "Retrieval Testing".
- Attach it to an agent and ask a question.

The test in "Retrieval Testing" works well like below.
![Screenshot from 2024-10-17 17-28-16](https://github.com/user-attachments/assets/80548d2c-fc9c-4f48-b6bd-a63bbe48e3c5)

But after attach it to an agent, it failed even with the exactly same query.
![Screenshot from 2024-10-17 17-29-28](https://github.com/user-attachments/assets/61949611-cabc-4178-af4b-5856e193680d)

### ✔️ Expected Behavior

The agent should works well with an external knowledge base.

### ❌ Actual Behavior

The agent failed to retrieve info from the external knowledge base.

**Comment by nicklhy** [comment]
PS, the external RAGFlow knowledge base was connected with the latest RAGFlow. RAGFlow's dify compatible api was defined [here](https://github.com/infiniflow/ragflow/blob/396bb4b6889b4cbd329fab729e02c453a5f1842f/api/apps/sdk/dify_retrieval.py#L13).

Since the "Retrieval Testing" succeeded after adding this external knowledge base in dify, I guess the problem might be in the dify side ?

**Comment by JohnJyong** [comment]
@nicklhy  hi nicklhy, would you pls provide some log info and pls try it in basic-chat app or workflow ?

**Comment by nicklhy** [comment]
I build a simple workflow which use the same query to call an external RAGFlow dataset and an internal dataset (created directly in dify). Both datasets are created with the same document files. However, the external one always return empty results and the internal dataset works well as below.

![Screenshot from 2024-10-18 09-36-13](https://github.com/user-attachments/assets/48ad3b43-2b9f-46e9-89a3-ba9baa700af3)

The basic-chat app looks similar. It works well with an internal knowledge base as below.
![Screenshot from 2024-10-18 09-49-30](https://github.com/user-attachments/assets/42defcc2-11f5-48d8-b76a-3b9d6fb2b1db)

After changing to the external RAGFlow knowledge base. There are no query results showed in chat log.
![Screenshot from 2024-10-18 09-51-30](https://github.com/user-attachments/assets/6d2667b9-0af0-4b85-89dd-3a66684bf0c3)

I checked the logs of docker-api-1, there is an error when query the external RAGFlow knowledge base.

```
2024-10-18 01:53:13,138.138 INFO [Thread-386 (_retriever)] [_client.py:1038] - HTTP Request: POST http://10.88.11.238:9380/api/v1/dify/retrieval "HTTP/1.1 200 OK"
Exception in thread Thread-386 (_retriever):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 472, in _retriever
    document = Document(
  File "/app/api/.venv/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Document
metadata
  Input should be a valid dictionary [type=dict_type, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/dict_type
```

**Comment by JohnJyong** [comment]
thanks for your feedback @nicklhy , it's the gitbook document rendering error,
we are very sorry about this , the `metadata` field is not `text`, 
In fact, the correct is `dict`.
the wrong document:
![image](https://github.com/user-attachments/assets/075e36f4-bfef-4d9d-9ea8-b171df2b12e9)
the correct document:
![image](https://github.com/user-attachments/assets/c4b196be-fffc-449c-8fb0-b8458e4f163d)

**Comment by Yawen-1010** [comment]
We have corrected the help documentation, thanks for the correction.
https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation
