### ISSUE TITLE
Occasionally "Operation not permitted"

### ISSUE THREAD

**Issue by Kain-90** [langgenius/dify#9449]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Create the example code execution block
2. Rapidly click "Run this step" multiple times (about 10 to 30 times)

### ✔️ Expected Behavior

No error

### ❌ Actual Behavior

Operation not permitted

![image](https://github.com/user-attachments/assets/c8ecb959-befe-4dd5-85a4-f5e92bcd5380)
![image](https://github.com/user-attachments/assets/c9639536-a8ed-4061-8de8-7b180a84fd11)

**Comment by Kain-90** [comment]
I've read related issues, and some people have encountered the same problem as me, that is, **occasional errors, not every time**, this [issue](https://github.com/langgenius/dify/issues/4993) is marked as complete, but in fact, [FAQ](https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md) does not solve my problem.

**Comment by crazywoola** [comment]
Please upgrade the sandbox to 0.2.10.

**Comment by Kain-90** [comment]
> Please upgrade the sandbox to 0.2.10.

It's been upgraded to 0.2.10, but i encountered the same issue again, and under the same reproduction conditions, another problem also emerged.

<img width="970" alt="image" src="https://github.com/user-attachments/assets/7ff7194c-b6c9-4c5e-b020-012a5df48cfa">
<img width="807" alt="image" src="https://github.com/user-attachments/assets/c9840877-9b0d-4f2f-82f9-77691cb90f62">
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/0ae970e7-030d-44c6-93d6-7460f3be4f30">

---
another problem

<img width="1360" alt="image" src="https://github.com/user-attachments/assets/5d74ea51-a7ae-4898-83be-dcc38e7d506e">
<img width="780" alt="image" src="https://github.com/user-attachments/assets/763601b6-109a-43b3-a185-7e49679715b4">

**Comment by Kain-90** [comment]
Is there any progress?

**Comment by Kain-90** [comment]
> Please upgrade the sandbox to 0.2.10.

Is there any progress?

**Comment by Kain-90** [comment]
@crazywoola Hi, is it solved?

**Comment by filwu8** [comment]
我也遇到同样的问题，无法在节点中执行代码

报错如下：

![Image](https://github.com/user-attachments/assets/1255344c-35c8-4e0c-abfd-03937a98f2eb)

使用环境 ，win11 + Docker
