### ISSUE TITLE
Bedrock Cohere embedding limitation

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#9456]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Use automatic text embedding rule when running embedding with cohere models from AWS bedrock gives max length errors

### ✔️ Expected Behavior

The normal cohere embedding model works for the same content with the same rules.

### ❌ Actual Behavior

![CleanShot 2024-10-17 at 15 22 03](https://github.com/user-attachments/assets/3a8fd95a-fa3b-4347-99f5-2593b2f6d1cf)

Gives error on multiple text chunks.

**Comment by ybalbert001** [comment]
That issue is thrown from bedrock. Dify can't handle that, I recommend you use smaller chunk to remediate it.

**Comment by Yawen-1010** [comment]
The error is caused by the Cohere embedding model's limitation of maximum chunk length not Dify's code.
