### ISSUE TITLE
Add supabase as a new vector database provider 

### ISSUE THREAD

**Issue by hwzhuhao** [langgenius/dify#9460]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Add supabase as a new vector database provider 

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by taowang1993** [comment]
Supabase is using pgvector, isn't it?
If so, you can just use the pgvector env variables to connect to Supabase.

**Comment by lhyphendixon** [comment]
I'm so glad this is an option! Can anyone confirm how it's done?  Do I simply use the instructions at the link below and set VECTOR_STORE=supabase ?

And does it support hybrid search?  Thanks!

https://docs.dify.ai/learn-more/faq/install-faq#id-17.-migrate-weaviate-to-another-vector-database
