### ISSUE TITLE
When can the files argument support image base64 when requesting the dify /chat_message interface?

### ISSUE THREAD

**Issue by zhai5191** [langgenius/dify#9471]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I currently call the dify /chat_message interface, the image parameter passed by the mobile side is base64. I don't want to convert the base64 data to image_url

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Off topic

**Comment by crazywoola** [comment]
Not planned https://github.com/langgenius/dify/issues/9430
