### ISSUE TITLE
Add http request node to workflow, how to configure and add local files

### ISSUE THREAD

**Issue by wangyingle666** [langgenius/dify#9484]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

Add http request node to workflow, how to configure and add local files
![image](https://github.com/user-attachments/assets/3443a946-9b3c-49de-a766-7cf115b64c36)

**Comment by guoshiqiufeng** [comment]
现在好像不支持

**Comment by crazywoola** [comment]
v0.10 beta
