### ISSUE TITLE
Can't embed multi-dimension array inside Object in result of Code execution node

### ISSUE THREAD

**Issue by JokerQyou** [langgenius/dify#9485]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Create a workflow app.
- Add a code execution node, select Python3 as language.
- In "return" statement, return an object with array, see the following code.
- In "Output variables" section, select type "Object" for `result` variable.
- Run this workflow.

```python

def main() -> dict:
    return {
        "result": {
            "hey": [
                [1, 2, 3],
                [4, 5, 6],
            ]
        },
    }

```

### ✔️ Expected Behavior

Workflow should run without error.

### ❌ Actual Behavior

Code execution block runs into an error saying `Node 代码执行 run failed: Output .result.hey is not a valid array. make sure all elements are of the same type.`.

It is not clear what are the restrictions on `Object` type of output variables. One would assume that it's just a normal `dict` instance in Python or anything that can pass `JSON.stringify` in Javascript. But as this error indicates it is not.

**Comment by JokerQyou** [comment]
There is no mentioning on any specific type in Dify documentation. Also I think `[[1,2,3], [4,5,6]]` does not break the rule "all elements are of the same type", since all elements are arrays with 3 integers. If this code runs off Dify I would type hint like this: `List[List[int]]`. Or I could write `[(1,2,3), (4,5,6)]` which satisfies an even more strict type hint: `List[Tuple[int, int, int]]`. But both the array and tuple example would fail with the same error.

**Comment by crazywoola** [comment]
https://docs.dify.ai/guides/workflow/node/code#usage-scenarios
I think implementing something that can check the type recursively could help, we do have limitations on the but it's not by purpose, just because we are lack of time,  so feel free to open a pull request.

**Comment by hwb96** [comment]
Today, I also encountered the same problem as you, and I have the same structure, but it reported an error. I am really very puzzled.
