### ISSUE TITLE
Error:  baidu obs storage

### ISSUE THREAD

**Issue by chop2** [langgenius/dify#9491]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. .env config
![image](https://github.com/user-attachments/assets/665d7fd7-2fb1-41ba-b5c7-a7e792578a82)

2. cmd：docker compose up -d
![image](https://github.com/user-attachments/assets/4252797b-faab-4398-87a2-f98d6a303a78)

error occur when service startup

### ✔️ Expected Behavior

server startup success.

### ❌ Actual Behavior

error occur

**Comment by chop2** [comment]
it was wrong obs_endpoint

**Comment by hwzhuhao** [comment]
@chop2 pls add baidu-obs configuration in docker-compose.yaml to quickly solve the error.
![baidu-bos-1](https://github.com/user-attachments/assets/0e74a6bd-1013-49d6-a6a1-3a9e9d809fef)
