### ISSUE TITLE
Azure OpenAI支持問題

### ISSUE THREAD

**Issue by charli117** [langgenius/dify#95]
發現https://github.com/openai/openai-python 0.27.6已經添加了Azure OpenAI幾個場景的支持，Dify什麼時候可以兼容呀
Using Azure completions
Using Azure fine-tuning
Using Azure embeddings

**Comment by takatost** [comment]
azure 唯一的问题是 deployment_name 是自定义的，和 OpenAI 有固定的模型不同，以至于我们需要额外设计交互来支持选择自定义的 deployment_name，这个需求我们已经是高优先支持了

**Comment by charli117** [comment]
有没有临时方案呀，比如在环境变量中写死？

**Comment by takatost** [comment]
目前除了改代码暂时没有临时方案，不好意思

**Comment by takatost** [comment]
已支持临时方案，注意事项见最后一条：
https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted#faq

**Comment by charli117** [comment]
获取了最新的代码，Azure OpenAI前端配置没问题了，但是发送消息还是会报错
![image](https://github.com/langgenius/dify/assets/24435100/6302ddb7-bc61-4be5-8dce-11df03f2c412)
![image](https://github.com/langgenius/dify/assets/24435100/62b4458b-73b4-4195-b35e-74c0766e13ea)
![image](https://github.com/langgenius/dify/assets/24435100/52536db3-f99a-477d-b32a-2a39ae67b4f8)

**Comment by takatost** [comment]
看起来像是 tiktoken 包里的模块没加载上，找不到这个 token 算法，重新拉下包试试

**Comment by charli117** [comment]
另外如果是新会话，首次消息发送报错会有差异，如下图：
<img width="1661" alt="image" src="https://github.com/langgenius/dify/assets/24435100/ea35ee51-85fc-46c2-97c9-285df09dbdf3">
