### ISSUE TITLE
About workflows API Issues

### ISSUE THREAD

**Issue by green-dalii** [langgenius/dify#9513]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

About Dify's workflow, when it is published as an API, the documentation lacks clarity. If multiple workflows are active simultaneously, the documented request URL (e.g.: `curl -X POST 'http://mydokcerhost.dify/v1/workflows/run'`) does not provide any distinction. How does Dify determine which specific workflow to execute?

**Comment by crazywoola** [comment]
> Authentication
The Service API uses API-Key authentication. Strongly recommend storing your API Key on the server-side, not shared or stored on the client-side, to avoid possible API-Key leakage that can lead to serious consequences.
