### ISSUE TITLE
Providing a means to GET all user, all conversations via API

### ISSUE THREAD

**Issue by daigo38** [langgenius/dify#9533]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In order to manage Dify in a production environment, I want to export all chat logs and analyze them.
Dify has an API for retrieving a list of conversations, but it is necessary to include the user ID in the query parameters, and there is no API for retrieving a list of users, so it is not possible to retrieve all conversations for all users.
Either an API for retrieving a list of users should be provided, or the user specification should be made optional in the API for retrieving a list of conversations.

### 2. Additional context or comments

The inability to export chat logs is a major barrier to the practical use of Dify.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
> Either an API for retrieving a list of users should be provided, or the user specification should be made optional in the API for retrieving a list of conversations.

It's not safe to list all users.

**Comment by rchlz** [comment]
I guess he meant to get all users' conversations, not all users.
I also have this requirement.
 but why not safe? It is just an api
