### ISSUE TITLE
The conversion_id parameter affects the calling of the tool

### ISSUE THREAD

**Issue by panla** [langgenius/dify#9535]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1, create agent app
2, config tool
3, generate api key
4, use api send message
5, delete tool
6, update
7, use api send message with conversation_id param
8, the response with tools included

### ✔️ Expected Behavior

use api send message after delete tool, the response without tools included

### ❌ Actual Behavior

use api send message after delete tool, the response with tools included

**Comment by waTErMo0n** [comment]
Suggest support for setting the expiration time as a decimal

**Comment by crazywoola** [comment]
If you use the conversation_id, the rest conversations would remain the same snapshot when you start the chat.
