### ISSUE TITLE
Add file download function to chat assistant

### ISSUE THREAD

**Issue by Erincrying** [langgenius/dify#9547]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I hope to add a download function to the reference files in the answers after adding the context of the knowledge base to the chat assistant.
When others add the knowledge base to the context, the agent will provide me with corresponding answers and referenced files. However, when I tried to download the specific files, I found that this feature was not available. I hope it can be provided

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by Yawen-1010** [comment]
Hello @Erincrying, can you specify the scenarios and use case of this features. Because for documents that are public on the Internet, there is no permission problem when downloading, such as papers on arxiv. When it comes to the knowledge base, there will be a permissions issue.

**Comment by Erincrying** [comment]
> Hello @Erincrying, can you specify the scenarios and use case of this features. Because for documents that are public on the Internet, there is no permission problem when downloading, such as papers on arxiv. When it comes to the knowledge base, there will be a permissions issue.

I hope to use it together in the team. When the team leader uploads the file to the knowledge base, others can add the knowledge base through the chat assistant to query relevant knowledge. At this point, the robot's answer will reference relevant files and prompt which file is being referenced. I hope to download the files uploaded by the leader locally by clicking on the reference file, without having to request the files from the leader

**Comment by Erincrying** [comment]
> > Hello @Erincrying, can you specify the scenarios and use case of this features. Because for documents that are public on the Internet, there is no permission problem when downloading, such as papers on arxiv. When it comes to the knowledge base, there will be a permissions issue.
> 
> I hope to use it together in the team. When the team leader uploads the file to the knowledge base, others can add the knowledge base through the chat assistant to query relevant knowledge. At this point, the robot's answer will reference relevant files and prompt which file is being referenced. I hope to download the files uploaded by the leader locally by clicking on the reference file, without having to request the files from the leader

Wait a moment, I am currently re deploying dify. I can send a screenshot later to illustrate the scenario I want to express

**Comment by Yawen-1010** [comment]
Currently, when you open the Citation&attribution feature, retrieved chunks will be displayed. Click Link to knowledge to jump to the knowledge base with one click. Do you have permission to this knowledge base? If you do not have permission at this step, you will have the same problem with document download.

**Comment by Erincrying** [comment]
> Hello @Erincrying, can you specify the scenarios and use case of this features. Because for documents that are public on the Internet, there is no permission problem when downloading, such as papers on arxiv. When it comes to the knowledge base, there will be a permissions issue.



> > > Hello @Erincrying, can you specify the scenarios and use case of this features. Because for documents that are public on the Internet, there is no permission problem when downloading, such as papers on arxiv. When it comes to the knowledge base, there will be a permissions issue.
> > 
> > 
> > I hope to use it together in the team. When the team leader uploads the file to the knowledge base, others can add the knowledge base through the chat assistant to query relevant knowledge. At this point, the robot's answer will reference relevant files and prompt which file is being referenced. I hope to download the files uploaded by the leader locally by clicking on the reference file, without having to request the files from the leader
> 
> Wait a moment, I am currently re deploying dify. I can send a screenshot later to illustrate the scenario I want to express

![image](https://github.com/user-attachments/assets/32770194-0d7d-40db-b616-49a56b6b7582)
Just like in the picture, I can click on the txt file to download it to my local computer

**Comment by Erincrying** [comment]
> > Hello @Erincrying, can you specify the scenarios and use case of this features. Because for documents that are public on the Internet, there is no permission problem when downloading, such as papers on arxiv. When it comes to the knowledge base, there will be a permissions issue.
> 
> > > > Hello @Erincrying, can you specify the scenarios and use case of this features. Because for documents that are public on the Internet, there is no permission problem when downloading, such as papers on arxiv. When it comes to the knowledge base, there will be a permissions issue.
> > > 
> > > 
> > > I hope to use it together in the team. When the team leader uploads the file to the knowledge base, others can add the knowledge base through the chat assistant to query relevant knowledge. At this point, the robot's answer will reference relevant files and prompt which file is being referenced. I hope to download the files uploaded by the leader locally by clicking on the reference file, without having to request the files from the leader
> > 
> > 
> > Wait a moment, I am currently re deploying dify. I can send a screenshot later to illustrate the scenario I want to express
> 
> ![image](https://private-user-images.githubusercontent.com/65204363/380055158-32770194-0d7d-40db-b616-49a56b6b7582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDE3NjMsIm5iZiI6MTcyOTg0MTQ2MywicGF0aCI6Ii82NTIwNDM2My8zODAwNTUxNTgtMzI3NzAxOTQtMGQ3ZC00MGRiLWI2MTYtNDlhNTZiNmI3NTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA3MzEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGUxYjUzYzA3MTZiZTk0Y2RmN2M5NmM1YmYxNzExOTljNjhhYzAzNTk2NjAwOTdlMTRkMDY5NTgyOTk5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KkXTBGkyujXrsNckroQzY06iO0px5PwGMoZ7toKDySM) Just like in the picture, I can click on the txt file to download it to my local computer
![image](https://github.com/user-attachments/assets/09791731-94ba-44b9-b655-114d7f1b9b84)

**Comment by Erincrying** [comment]
> Currently, when you open the Citation&attribution feature, retrieved chunks will be displayed. Click Link to knowledge to jump to the knowledge base with one click. Do you have permission to this knowledge base? If you do not have permission at this step, you will have the same problem with document download.

This knowledge base is set to be visible to certain team members. Do these team members have this permission? I hope that the authorized team members who click on it will not show me the segmented file fragments, but can choose to download the original file directly. Authorized members can click on the reference file to download the source file

**Comment by Yawen-1010** [comment]
Yes, that's the permissions issue we're concerned about. Because there are specific documents which are not shown to everyone. For authorized members, you can click into the knowledge base to see the full text. But for users without permission, we are unable to provide complete documentation in this case.

**Comment by Erincrying** [comment]
> Yes, that's the permissions issue we're concerned about. Because there are specific documents which are not shown to everyone. For authorized members, you can click into the knowledge base to see the full text. But for users without permission, we are unable to provide complete documentation in this case.

The current method is that for members who do not have permission, clicking to jump to the knowledge base will prompt a permission error. Consistency can be maintained here, where unauthorized members are still unable to download source files and receive error prompts, while authorized members (i.e. those who can jump to the knowledge base) can provide a method for downloading source files

**Comment by Yawen-1010** [comment]
In response to this demand, we may add a document download function to the knowledge base in the future. The priority is not very high at the moment.

**Comment by Erincrying** [comment]
> In response to this demand, we may add a document download function to the knowledge base in the future. The priority is not very high at the moment.

Okay, I hope the reference files in the chat assistant can also be downloaded directly because we plan to open the application as an API and return the download stream of the source file directly in the response. It is said that RAGflow has a similar function. If this function is added, please let me know. Thank you very much！！

**Comment by Erincrying** [comment]
> In response to this demand, we may add a document download function to the knowledge base in the future. The priority is not very high at the moment.

@Yawen-1010 I'm sorry to bother you again, but I urgently need to fulfill this request. Can you tell me how to debug front-end code and some files I started using? I haven't developed front-end and back-end code yet, but I urgently need to implement it, so I'm sorry to bother you
