### ISSUE TITLE
Parallel branches are wrongly displayed in the Tracing UI and one step keeps running forevever

### ISSUE THREAD

**Issue by fniu** [langgenius/dify#9556]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

A set of parallel branches (1-B, 1-C and 1-D) comes at a Template node. Everythings works fine except for the UI, e.g., the Template node is missing for Branch-1-B, the steps for the Template node keeps running forever.

![Screenshot 2024-10-21 114536](https://github.com/user-attachments/assets/84a82eaf-436c-418e-9c02-990afcd36fd8)

### ✔️ Expected Behavior

Every branch should end with the node "TEMPLATE", and should stop showing "Running" when the workflow is ended.

### ❌ Actual Behavior

Explained above and with a screenshot.

**Comment by crazywoola** [comment]
Can you provide a minimal DSL for us to reproduce this issue.

**Comment by fniu** [comment]
After upgraded to 0.10.0, the same workflows run into another error:

_Variable ans0 not found in variable pool_



I suspect it has been fixed, by #9646. Could you confirm? (or I can re-check this issue when 0.10.1 is avaiable)

**Comment by fniu** [comment]
With 0.10.1, the error still exists. The error has something to do with the knowledge retrieval. When I remove the knowledge retrieval steps, the error is gone and the UI error is also gone (which is a good news). For this reason, sharing the DSL to you will not help reproduce the error. The screenshot is given below. Note that the error "Variable ans0 not found in variable pool", where ans0 is one of the inputs to node "TEMPLATE".

![Screenshot 2024-10-23 215647](https://github.com/user-attachments/assets/58d3b4e3-edde-42ba-a34d-0d423a22c03b)

![Screenshot 2024-10-23 220145](https://github.com/user-attachments/assets/6d6bc7b5-7d18-4a31-a1cb-63a27159bff1)

**Comment by laipz8200** [comment]
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/9a2547b6-53eb-4c0f-965b-8350857b3ff2">


I can't reproduce this problem. Can you try again to see if it can work properly?

**Comment by fniu** [comment]
@laipz8200 
> I can't reproduce this problem. Can you try again to see if it can work properly?

The error would show if you add knowledge retrieval for each branch before the LLM step. At least this is what happened to me.
FYI, I see someone else has reproted the same issue in #9844.

**Comment by laipz8200** [comment]
<img width="266" alt="image" src="https://github.com/user-attachments/assets/6813acb9-b394-4ccb-99cb-ecb26227c914">

Currently, the situation shown in the image is not supported. Deleting this branch can resolve the issue.
