### ISSUE TITLE
Validation error in HttpRequestNodeData in production

### ISSUE THREAD

**Issue by nfaganelly** [langgenius/dify#9569]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

last

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Create a workflow that uses the HttpRequestNodeData module.
2. Configure the HTTP request body with data in string format.
3. Run the workflow in the test environment (it works normally).
4. Run the same workflow in the production environment.
5. Observe the error generated.

```json
{
  "nome": "{{#17246...2038442.guests#}}"
}
```

### ✔️ Expected Behavior

The workflow should work correctly in production, just as it does in the test environment, without generating validation errors.

### ❌ Actual Behavior

In production, the workflow generates the following validation error:
```
1 validation error for HttpRequestNodeData
body.data 'str' instances are not allowed as a Sequence value [type=sequence_str, input_value='{\n "nome": "{{#17246...2038442.guests#}}"\n }', input_type=str]
```

**Comment by 74sistemas** [comment]
I'm going through this same problem

**Comment by laipz8200** [comment]
Who can provide me with the smallest DSL that can reproduce this problem?

**Comment by 74sistemas** [comment]
![image](https://github.com/user-attachments/assets/9ada6c39-b7eb-4e68-837c-c25a94abec13)
After the update, the error appeared, in the other tools I deleted it and did it again and kept updating until I got it right, see the last one the problem continues so I must delete the tool and do it again while updating... that's why I think it could be a chache something like that

**Comment by 74sistemas** [comment]
![image](https://github.com/user-attachments/assets/3bd5b6d9-b671-4185-a1c5-d9e69663daab)
See, I deleted the json provided and saved the tool. I went back and inserted the json and the error in the chatbot disappeared and the flow returned normally.

**Comment by laipz8200** [comment]
Sorry, we encountered a small issue with historical data migration.

1. For users who are using Docker for self-deployment, you can wait for the next version or delete and rebuild the node.
2. For users who are using source code deployment, you can pull the latest code from the main branch, which should work.
3. For Cloud users, we are restoring the service. Please try again later.

If the above responses solve your issue, please let me know (along with the deployment method you are using).

**Comment by IvanHenrique** [comment]
A workflow that was working stopped working for me too.

Now I'm getting this error when passing a number parameter in the body of the JSON request:

![image](https://github.com/user-attachments/assets/e5c9ddb0-dc46-45f8-b4be-90e3b06b9f23)

**Comment by IvanHenrique** [comment]
> A workflow that was working stopped working for me too.
> 
> Now I'm getting this error when passing a number parameter in the body of the JSON request:
> 
> ![image](https://private-user-images.githubusercontent.com/38106907/378637557-e5c9ddb0-dc46-45f8-b4be-90e3b06b9f23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjExMzEsIm5iZiI6MTcyOTU2MDgzMSwicGF0aCI6Ii8zODEwNjkwNy8zNzg2Mzc1NTctZTVjOWRkYjAtZGM0Ni00NWY4LWI0YmUtOTBlM2IwNmI5ZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAxMzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NTZiZmRmMjY2Y2NjZTQ1MTQyYjdjOGJiOTUyNTJjZmM0NjNjZjM1ODRiM2RkMzZlMjI0NjgwZDdmMGE0NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rR35S4tbhA7pVIxv_CcHf3nW-W21134DYuAfwYQzMqI)

I opened a new issue about this problem here:

https://github.com/langgenius/dify/issues/9590

**Comment by valneimelo** [comment]
Hi @IvanHenrique 
I'm facing the same issue as you are. 

"tool invoke error: 1 validation error for HttpRequestNodeData\nbody.data\n 'str' instances are not allowed as a Sequence value [type=sequence_str, input_value='', input_type=str]"}

Did find any solution for that?

Thank you

**Comment by nfaganelly** [comment]
Here, I duplicated and deleted the old one, then it worked again.
