### ISSUE TITLE
Variable Aggregator gets parallel parameter exceptions.

### ISSUE THREAD

**Issue by kkjinping** [langgenius/dify#9570]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、Two knowledge base nodes are in parallel.
2、Variable Aggregator gets the output parameters of two nodes.
3、Finally, only the parameters of one node are obtained.

### ✔️ Expected Behavior

Wait and obtain the parameters of all nodes.

### ❌ Actual Behavior

Only the parameters of one node are obtained

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9057 and https://github.com/langgenius/dify/issues/8420 see the second one for more details. we do not have a plan to support parallel execution in variable aggregator, this is an expected behavior.
