### ISSUE TITLE
LLM Run failed: file type document is not supported

### ISSUE THREAD

**Issue by kkjinping** [langgenius/dify#9582]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce
0、Create a workflow
1、Upload a PDF document and ask a question.
2、Continue to ask questions.
3、LLM Node show **Run failed: file type document is not supported**

DDL：
[DocAi.zip](https://github.com/user-attachments/files/17464471/DocAi.zip)

### ✔️ Expected Behavior

llm node is normal

### ❌ Actual Behavior

llm node is error

**Comment by likenamehaojie** [comment]
+1 i have the same problem

**Comment by hjlarry** [comment]
see the doc here https://docs.dify.ai/zh-hans/guides/workflow/file-upload
the `sys.files` can't remember file,   create a file var seems not raise this issue
