### ISSUE TITLE
HTTP Node JSON Body Handling Issue

### ISSUE THREAD

**Issue by kltng** [langgenius/dify#9587]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

1. Create an HTTP node in a Dify workflow.
2. Set the method to POST.
3. Set Content-Type header to application/json.
4. In the body section, select JSON and input a valid JSON object (either directly or using a variable).
Execute the workflow.

### ✔️ Expected Behavior

Send standardized JSON as the body of the HTTP Request node. Get or post request with 200 response.

### ❌ Actual Behavior

The HTTP node in Dify is not correctly handling JSON bodies, especially when using variables. This leads to malformed requests and API errors.

When attempting to send a JSON body in the HTTP node, particularly when using variables, the following issues occur:

**For standard JSON input:**
![CleanShot 2024-10-21 at 15 56 00@2x](https://github.com/user-attachments/assets/1b136207-a1d2-4716-8e1a-c043cb54bdf1)
Error message: "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"
![CleanShot 2024-10-21 at 15 59 55@2x](https://github.com/user-attachments/assets/2f8ac137-2b08-4238-b572-57b244b73ec5)
This suggests the JSON is not being properly escaped or formatted when sent.

**Workaround attempt:**
When enclosing the JSON in double quotes, the request is sent successfully.
![CleanShot 2024-10-21 at 15 58 07@2x](https://github.com/user-attachments/assets/537df78e-bb55-4522-92d7-328b646b3b93)
However, this results in a 400 error from the API, indicating the JSON is not properly formatted.
![CleanShot 2024-10-21 at 15 58 38@2x](https://github.com/user-attachments/assets/f38b04b5-bef9-4665-ad35-f5103150eeff)

**Comment by crazywoola** [comment]
You need to use regex parse things in extracted response, for example you need to use it to remove duplicated '\' characters.

**Comment by monotykamary** [comment]
The bug in question is getting the raw string as a JSON output to feed into the HTTP request node. This was not a bug prior to v0.10.0. For instance, this would no longer work:

```
function main({ type, repo_url, branch, git_token, file_patterns } = {}) {
    return {
        result: JSON.stringify({
            ...(type && { type }),
            ...(repo_url && { repo_url }),
            ...(branch && { branch }),
            ...(git_token && { git_token }),
            ...(file_patterns && { file_patterns })
        })
    };
}
```

<img width="395" alt="image" src="https://github.com/user-attachments/assets/99f3ec22-3106-4d4d-8db1-28660a4f16dd">

<img width="398" alt="image" src="https://github.com/user-attachments/assets/4a69043c-8cd0-4809-8c95-6507b6b32536">
