### ISSUE TITLE
No clear way to use datasets as inputs

### ISSUE THREAD

**Issue by wbhob** [langgenius/dify#9588]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I am building an app where each client has their own dataset(s) and needs to use the same RAG pipeline with different data sets. There is no clear way to do this from the docs.

### 2. Additional context or comments

Ideally, I can tell my Chatbot to accept any dataset as context, instead of defining it at Chatbot creation time and having to create a different Chatbot for each client.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/9630
