### ISSUE TITLE
Did not display file url in run mode despite still having url in the tracing 

### ISSUE THREAD

**Issue by 1linedata** [langgenius/dify#9589]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="573" alt="Screenshot 2024-10-22 053326" src="https://github.com/user-attachments/assets/f51f05ad-a574-406c-ad7b-880ca1f8c835">
<img width="569" alt="Screenshot 2024-10-22 053342" src="https://github.com/user-attachments/assets/636eef35-a9f3-4c77-96e1-5e468b7a1495">
<img width="563" alt="Screenshot 2024-10-22 053316" src="https://github.com/user-attachments/assets/97f81a4b-a39a-4812-bfaa-8f05fde6b302">

Did not display file url in run mode despite still having url in the tracing 

### ✔️ Expected Behavior

display file url in run mode (same with url in the tracing) 

### ❌ Actual Behavior

Did not display file url in run mode despite still having url in the tracing

**Comment by 1linedata** [comment]
sorry for mistaken 1 info above, I'm currently using cloud version not self hosted (docker)

**Comment by hjlarry** [comment]
duplicated with  https://github.com/langgenius/dify/issues/9567
