### ISSUE TITLE
After updating to version v0.10.0, I'm getting this error when passing a number parameter in the request body in json.

### ISSUE THREAD

**Issue by IvanHenrique** [langgenius/dify#9590]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.10.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

variable input node with all the variables passed in the cal.com scheduleBooking API, in the CURL below:

curl --request POST \
  --url 'https://api.cal.com/v1/bookings?apiKey=TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
  "eventTypeId": 1290514,
  "start": "2024-10-22T15:00:00-03:00",
  "responses": {
    "name": "Ivan Melo",
    "email": "teste@teste.com",
    "location": {
      "value": "Endereço",
      "optionValue": "teste"
    },
    "description": "teste"
  },
  "timeZone": "America/Sao_Paulo",
  "language": "pt-BR",
  "metadata": {}
}'

But informing the input variables in json, including the eventTypeId which is of type number and is causing this error, according to my tests.

{
  "eventTypeId": {{#1729122527484.eventTypeId#}},
  "start": "{{#1729122527484.startTime#}}",
  "responses": {
    "name": "{{#1729122527484.name#}}",
    "email": "{{#1729122527484.email#}}",
    "description": "{{#1729122527484.description#}}",
    "location": {
      "value": "Endereco",
      "optionValue": "{{#1729122527484.address#}}"
    }
  },
  "timeZone": "{{#1729122527484.timezone#}}",
  "metadata": {},
  "language": "pt-BR"
}

The request is not even executed by dify, giving the error below:

![error_body_json_number_parameter](https://github.com/user-attachments/assets/f70a473b-1806-4447-9e99-73cf58852b79)

### ✔️ Expected Behavior

Request executed successfully, as it was doing normally until yesterday.

### ❌ Actual Behavior

![error_body_json_number_parameter](https://github.com/user-attachments/assets/9fe33c57-31ba-4ccd-a178-79390836e4fd)

**Comment by IvanHenrique** [comment]
@dosu First of all, thanks for the answer.

eventTypeId is a numeric field.

https://cal.com/docs/api-reference/v1/bookings/creates-a-new-booking

![image](https://github.com/user-attachments/assets/e1e42f9c-2fcc-4a4e-80ce-ad2067a1ea30)

everything is in double quotes.

If I pass the eventTypeId with quotes, the API doesn't accept it.

And all the variables are being passed normally.

Until yesterday, this flow was working normally.

**Comment by IvanHenrique** [comment]
![image](https://github.com/user-attachments/assets/e65678c4-a120-4107-9f1b-21df236b0ee0)

Here is the filled input variable.

If I remove this "eventTypeId" field from the json it will stop giving this error, but since it is mandatory the API will criticize it.

And no, this workflow has not changed since yesterday!

**Comment by EcoleKeine** [comment]
number in http request body json change to null when requesting
```json
{"page":{"start":0,"limit":10}, ...}
```
```
...
Content-Length: 4060\r\n\r\n{\"page\": {\"start\": null, \"limit\": null}, ...
```

**Comment by boboboss** [comment]
> 请求时http请求体json中的数字变为null
> 
> ```json
> {"page":{"start":0,"limit":10}, ...}
> ```
> 
> ```
> ...
> Content-Length: 4060\r\n\r\n{\"page\": {\"start\": null, \"limit\": null}, ...
> ```

这个问题解决了么。

**Comment by boboboss** [comment]
> 请求时http请求体json中的数字变为null
> 
> ```json
> {"page":{"start":0,"limit":10}, ...}
> ```
> 
> ```
> ...
> Content-Length: 4060\r\n\r\n{\"page\": {\"start\": null, \"limit\": null}, ...
> ```

0.10.0的问题好多呀，再http请求这一块儿
