### ISSUE TITLE
Internal Server Error when using Get Conversation History Messages API endpoint

### ISSUE THREAD

**Issue by nfaganelly** [langgenius/dify#9593]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.10.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Use the following cURL command to retrieve messages from the Dify API:
    ```bash
    curl --location 'https://api.dify.ai/v1/messages?user=5522XXXXX279&conversation_id=bb0a4XXXXXXX-4149-8ef0-6204eed28ef7&limit=30' \
    --header 'Authorization: Bearer app-oEXXXXXXXXXXnGp' 
    ```
2. Observe the response from the API.

### ✔️ Expected Behavior

The API should return the list of messages for the specified user and conversation ID.

### ❌ Actual Behavior

The API returns the following error message:
```json
{
    "message": "Internal Server Error",
    "code": "unknown"
}
```

**Comment by nfaganelly** [comment]
The first error was more than 12 hours ago, I have already changed the token and I still have the same error.

**Comment by crazywoola** [comment]
Please provide the container logs as well.

**Comment by nfaganelly** [comment]
The log is not reaching the agent. How do I pull the logs of requests to the Cloud that were not processed?

**Comment by crazywoola** [comment]
Can you provide the time range you sent this request?

**Comment by leochen-g** [comment]
While using the Sass service, I encountered the same issue when calling this API. It's not related to a private deployment.
<img width="583" alt="image" src="https://github.com/user-attachments/assets/da5f910e-8e2f-46d9-8eab-9248f864027f">

@crazywoola
