### ISSUE TITLE
HTTP Node seems losing meta data

### ISSUE THREAD

**Issue by crazywoola** [langgenius/dify#9599]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

- Create a workflow, see provided one.
- Upload a `audio/wav` file
[Speech to Text.yml.txt](https://github.com/user-attachments/files/17469303/Speech.to.Text.yml.txt)
[d4d67190-c26e-44fd-acf1-aa8fb32a8fd0.wav.zip](https://github.com/user-attachments/files/17469311/d4d67190-c26e-44fd-acf1-aa8fb32a8fd0.wav.zip)

### ✔️ Expected Behavior

Get get the results from API endpoind

### ❌ Actual Behavior

```
{
"error": {
"message": "Unrecognized file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
```

**Comment by saendu** [comment]
Same problem here. Getting file not supported error from whisper api.

**Comment by ugyuji** [comment]
Same problem with the HTTP Request block.
I'm getting "Unrecognized file format" error from whisper.

**Comment by saendu** [comment]
Here some context:
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/743c56be-8702-42c3-b650-796f6e9f47a2">
