### ISSUE TITLE
In "update document segment" interface  at Knowledge API Page

### ISSUE THREAD

**Issue by nameIsNoPublic** [langgenius/dify#9600]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

response should be a object but document write data is a "list" struct

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9162

**Comment by nameIsNoPublic** [comment]
Are you sure you have thoroughly checked it?
