### ISSUE TITLE
Bug Report: Duplicate Segment Numbers and Scrolling Issue in Frontend UI

### ISSUE THREAD

**Issue by Angelxiaotao** [langgenius/dify#9601]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Description:
While using the POST /datasets/{dataset_id}/documents/{document_id}/segments API, I encountered an issue when adding a large number of segments. Although the total number of segments is correctly reflected in the dataset, the frontend UI displays duplicate segment numbers. As a result, the displayed segment numbers do not correspond to the actual segments, and the page does not scroll properly. This inconsistency makes it difficult to browse through the segments effectively.

Steps to Reproduce:

1. Use the API to add a large number of segments to a document.
2. Visit the frontend UI to view the added segments.
3. Observe that the segment numbers are duplicated.
4. Try scrolling through the segments; the page does not behave as expected.

### ✔️ Expected Behavior

Each segment should have a unique number, and the frontend UI should allow smooth scrolling according to the total number of segments added.

### ❌ Actual Behavior

Segment numbers appear duplicated.
Scrolling is broken or limited, not matching the actual segment count.
![image](https://github.com/user-attachments/assets/5f7a4dec-46ee-43bd-9672-e529e881775b)

**Comment by crazywoola** [comment]
Seems. duplicated with https://github.com/langgenius/dify/issues/9276
