### ISSUE TITLE
How to Enable LLM node stream output in workflow mode?

### ISSUE THREAD

**Issue by applepieiris** [langgenius/dify#9615]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

in the official document: [LLM node introduction](https://docs.dify.ai/zh-hans/guides/workflow/node/llm#shi-yong-an-li)
It only introduces how to configure the LLM node before the "Direct Answer Node"，I see in most of the examples you provide in your guidebook, there is no where to find how to enable LLM stream output. I construct a RAG based chatbot under workflow mode and when I debug the chatbot, it provides me the LLM answer as a complete text which is a bit slow.

Where can I change the LLM node or the Direct answer node into stream mode?

**Comment by crazywoola** [comment]
The LLM streaming is enabled by default. There is no place to configure it.
The only thing you need to do is connect a LLM node to an End or Answer node.
I don't have enough information to guess what's happening there. There are few possible scenarios could lead to this.

- The LLM is not support this feature.
- The Nginx configuration file is wrong.
