### ISSUE TITLE
The tool "Podcast audio generator" should add an api_base parameter option

### ISSUE THREAD

**Issue by YoungWWan** [langgenius/dify#9621]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The openai proxy service I use, the base url is inconsistent with the official one and cannot be used.
<img width="417" alt="image" src="https://github.com/user-attachments/assets/7101e042-2ef1-4425-a1da-ff14f1d1d08a">

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by laipz8200** [comment]
This tool is intended for basic demo use only. We will provide more flexible and customizable methods for handling files in the future.
