### ISSUE TITLE
It is not possible to send mail via Python code

### ISSUE THREAD

**Issue by fatcatloversknnymonkey** [langgenius/dify#9625]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/9b8b620a-6384-4ca7-9dff-c172335e0603)
![image](https://github.com/user-attachments/assets/7de5fa23-bea7-42d2-a259-106360f78fd3)

**Comment by crazywoola** [comment]
Please use a third-party service instaed.

**Comment by kkTea** [comment]
I got the issue too, so sad...
