### ISSUE TITLE
Add Fields Input Re Order option

### ISSUE THREAD

**Issue by asrguru20** [langgenius/dify#9628]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When I add many input fields sometimes I make mistake then I have to delete all input fields and re add again But if I could Re order inputs fields by drag and drop method This solve this UX issue 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by libukai** [comment]
I am experiencing the same scenario.The reorder feature will be very useful.
