### ISSUE TITLE
Chatbot dialog width too small after uprade to 0.10.0

### ISSUE THREAD

**Issue by ziyu4huang** [langgenius/dify#9637]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Use "Run App", and start chat . 

### ✔️ Expected Behavior

Expect the dialog take all space of browser

### ❌ Actual Behavior

the dialog looks too small.  

I try to hack div , make the max-w-720  to  1280px ,  it looks OK.
class="px-8 mx-auto pt-6 w-full max-w-[1280px] false"

How can we fix it  ?

**Comment by crazywoola** [comment]
Do you have a screenshot?

**Comment by ziyu4huang** [comment]
Sorry, due to company's policy , I have difficut to upload image.  I will try it late outside company.

**Comment by crazywoola** [comment]
I see
