### ISSUE TITLE
Missing upload size limit configuration in docker-compose.yaml.

### ISSUE THREAD

**Issue by caiyuanhangDicp** [langgenius/dify#9639]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.Deploy Dify Version 0.10.0 using Docker.
2.Attempt to change the upload file size limits.

In the latest Version 0.10.0, the docker-compose.yaml file lacks the following upload configuration fields:
`# Upload configuration
UPLOAD_FILE_SIZE_LIMIT=15
UPLOAD_FILE_BATCH_LIMIT=5
UPLOAD_IMAGE_FILE_SIZE_LIMIT=10
UPLOAD_VIDEO_FILE_SIZE_LIMIT=100
UPLOAD_AUDIO_FILE_SIZE_LIMIT=50
`
This omission prevents users from adjusting these limits when deploying with Docker. Currently, only the following parameters can be modified:
`# Upload file size limit, default 15M.
UPLOAD_FILE_SIZE_LIMIT=15

# The maximum number of files that can be uploaded at a time, default 5.
UPLOAD_FILE_BATCH_LIMIT=5
`

### ✔️ Expected Behavior

Users should be able to configure all relevant upload size limits.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9633
