### ISSUE TITLE
Environment variables for ModelProvider and Tool Position are not working

### ISSUE THREAD

**Issue by tkoshida** [langgenius/dify#9645]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Set the value of POSITION_TOOL_INCLUDES in the .env file (e.g., bing, google).
2. Restart Dify
```
docker compose down
docker compose up -d
```

### ✔️ Expected Behavior

The toolset on the following screen is limited to the specified tools
http://localhost/tools

### ❌ Actual Behavior

Nothing changes

**Comment by crazywoola** [comment]
Fell free to open a pr for this.
