### ISSUE TITLE
When creating a new workflow, the front-end reports an error

### ISSUE THREAD

**Issue by Erincrying** [langgenius/dify#9647]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0d4ac94d-e2ab-4fc7-8d10-616a76ac6574)
![image](https://github.com/user-attachments/assets/014a0d2f-d158-4c1e-9720-231bc441cf47)

### ✔️ Expected Behavior

When creating a new workflow or opening a previous workflow, the page can be opened normally

### ❌ Actual Behavior

When creating a new workflow or opening a previous workflow, the console reports an error and the front-end page cannot be opened properly

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9594

**Comment by Erincrying** [comment]
> Duplicated #9594 
After updating the code, the same problem still exists when deploying through source code

**Comment by firefoxwang** [comment]
If a user is on Windows 7, Chrome may not function properly; We  use the Firefox (Extended Support Release) version instead.
