### ISSUE TITLE
Stream options are not available for Azure openAI

### ISSUE THREAD

**Issue by dale22** [langgenius/dify#9653]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

 have  upgrade to v0.10.0.   but also options Streaming true
![image](https://github.com/user-attachments/assets/5a6a37f4-5203-4633-a97b-a4909cb5448e)

**Comment by crazywoola** [comment]
Duplicated

**Comment by leslie2046** [comment]
please provide more details
1.model name
2.azure openai api version
3.dsl
4.The  reproduce step

**Comment by crazywoola** [comment]
This error is more like the model itself does not support streaming, and I remember that if I used structure output, there would be a similar error, no matter it's OpenAI or Azure OpenAI

**Comment by dale22** [comment]
use api can be set streaming . but ui not set , so is error 
model name:gpt-4o-2024-05-13
azure openai api version:2024-05-01-preview
step
1,set model is ok，so API Key and Endpoint and deployment name is ok
![image](https://github.com/user-attachments/assets/047318e5-7c8a-49b1-870b-4f38282fcbc5)
2,but dify chat is error, and ui not set streaming false， docker-api logs:403
![image](https://github.com/user-attachments/assets/9181fd98-946f-41be-b6a8-62986dfc02d8)

**Comment by Moiyu1998** [comment]
This is not an issue with dify. The o1 series models currently do not support streaming output, and many parameters cannot be changed. The only adjustable parameter is the maximum length, but the parameter names have also changed from before.
