### ISSUE TITLE
Document stuck in queue - "poetry run flask db upgrade" command returned "None of PyTorch, TensorFlow >= 2.0, or Flax have been found" 

### ISSUE THREAD

**Issue by AcacioAraujo** [langgenius/dify#9655]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Tried to add knowledge base but document is stuck in queue
Worker log: mind attached file
![worker log](https://github.com/user-attachments/assets/e217261b-d3b2-4342-a306-26877efe2d3c)

tried to run "poetry run flask db upgrade" command, but returned message "None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used."
mind attached file
![poetry log](https://github.com/user-attachments/assets/1b2134a5-a085-4868-9182-c67f2399c4b4)

### ✔️ Expected Behavior

Document should be processed

### ❌ Actual Behavior

document stuck in queue

**Comment by crazywoola** [comment]
This is not the root cause of the problem.
> None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
This is a warning message, the problem is you can not locate the migration file, please cleanup the database and recreate the containers or upgrade to a higher version, this happens when you try to downgrade the version.

**Comment by AcacioAraujo** [comment]
> This is not the root cause of the problem.
> 
> > None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> 
> This is just a warning message, the problem is that you can not locate the migration file, please clean up the database and recreate the containers or upgrade to a higher version, this happens when you try to downgrade the version.

Hi! I´ve found the root of the problem here. I changed a docker compose file configuration and now it´s working properly.

**Comment by Halfknow** [comment]
> > This is not the root cause of the problem.
> > > None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> > 
> > 
> > This is just a warning message, the problem is that you can not locate the migration file, please clean up the database and recreate the containers or upgrade to a higher version, this happens when you try to downgrade the version.
> 
> Hi! I´ve found the root of the problem here. I changed a docker compose file configuration and now it´s working properly.

Hi! I wonder how to solve this problem, could you specify what needs to be changed in the docker compose file?

**Comment by pratikchandrani** [comment]
I am also facing the same problem. Please share the changes you made to docker compose file so that we can learn from it. Thanks in advance.

**Comment by pratikchandrani** [comment]
> > This is not the root cause of the problem.
> > > None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> > 
> > 
> > This is just a warning message, the problem is that you can not locate the migration file, please clean up the database and recreate the containers or upgrade to a higher version, this happens when you try to downgrade the version.
> 
> Hi! I´ve found the root of the problem here. I changed a docker compose file configuration and now it´s working properly.

I am also facing the same problem. Please share the changes you made to docker compose file so that we can learn from it. Thanks in advance.
