### ISSUE TITLE
TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'

### ISSUE THREAD

**Issue by luotian2020** [langgenius/dify#9656]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I was using dify version 0.10.0 and calling the Knowledge Base API - Upload by Text Interface (/datasets/{dataset_id}/document/create_by_text), I encountered the following error: TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'. However, there was no issue when uploading through a file.
![image](https://github.com/user-attachments/assets/0c37c9b4-fc8e-4476-aca3-e3a452bae173)
![image](https://github.com/user-attachments/assets/d8589ab3-395a-4605-b2be-f3eb856da48f)

### ✔️ Expected Behavior

a successful  json

### ❌ Actual Behavior

an error json

**Comment by crazywoola** [comment]
Have you searched the existing issues?
