### ISSUE TITLE
Doc Extractor only extracts first sheet from XLS

### ISSUE THREAD

**Issue by infinitnet** [langgenius/dify#9661]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Upload XLS file with multiple sheet tabs in it and run Doc Extactor.

### ✔️ Expected Behavior

Doc Extractor should extract all sheets (tabs) within the XLS.

### ❌ Actual Behavior

Doc Extractor only extracts the first sheet (tab) in the XLS file.

**Comment by yujchn** [comment]
<img width="380" alt="image" src="https://github.com/user-attachments/assets/448f3c88-2ea2-48b9-aaf9-d22fa49eb1d6">
only 1 sheet extracted
