### ISSUE TITLE
2-byte languages cannot be entered in the Start block

### ISSUE THREAD

**Issue by atakamizawa** [langgenius/dify#9663]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

2-byte languages cannot be correctly entered in the START block. It behaves as if characters that have only been entered once appear multiple times.
This problem does not occur after Start Chat, so I believe this is an issue that only arises at the very beginning of starting the app.
The attached gif shows the behavior when trying to enter "test message" in Japanese.
![0 10 0](https://github.com/user-attachments/assets/e6f57c6d-927c-45de-a709-e9f3682c4ca1)

**Comment by atakamizawa** [comment]
I'm sorry for submitting an incomplete issue. Thank you for addressing it.

**Comment by kurokobo** [comment]
@atakamizawa 
Oh, I'm sorry too, I opened a duplicate issue. I couldn't find this properly while searching: #9671 

This issue should be fixed in my PR #9672, so I hope it gets merged 😌
