### ISSUE TITLE
Partial info retrieving info from Excel knowledge

### ISSUE THREAD

**Issue by danielgimeno** [langgenius/dify#9669]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have created a knowledge with an excel,  with fake data with next structure: 
OrderDate	Region	Rep	Item	Units	Unit Cost	Total
1/6/21	East	Jones	Pencil	95	 1,99 	 189,05 
1/23/21	Central	Kivell	Binder	50	 19,99 	 999,50 
2/9/21	Central	Jardine	Pencil	36	 4,99 	 179,64 
2/26/21	Central	Gill	Pen	27	 19,99 	 539,73 
3/15/21	West	Sorvino	Pencil	56	 2,99 	 167,44 
...

IT has arounf 50 rows,  with several selling values for all users.  every user has many lines

1/6/21	East	Jones	Pencil	95	 1,99 	 189,05 
4/1/21	East	Jones	Binder	60	 4,99 	 299,40 
6/8/21	East	Jones	Binder	60	 8,99 	 539,40 
8/15/21	East	Jones	Pencil	35	 4,99 	 174,65 
9/18/21	East	Jones	Pen Set	16	 15,99 	 255,84 
10/22/21	East	Jones	Pen	64	 8,99 	 575,36 
2/18/22	East	Jones	Binder	4	 4,99 	 19,96 
7/4/22	East	Jones	Pen Set	62	 4,99 	 309,38 

Then  when I ask simple questions like what are the Jones sells and I get next output:

The sales completed by Jones are as follows:

1. Order Date: June 8, 2021
   - Region: East
   - Item: Binder
   - Units: 60
   - Unit Cost: $8.99
   - Total: $539.4

2. Order Date: January 6, 2021
   - Region: East
   - Item: Pencil
   - Units: 95
   - Unit Cost: $1.99
   - Total: $189.05

Citations: sampledata.xlsx

### ✔️ Expected Behavior

1/6/21	East	Jones	Pencil	95	 1,99 	 189,05 
4/1/21	East	Jones	Binder	60	 4,99 	 299,40 
6/8/21	East	Jones	Binder	60	 8,99 	 539,40 
8/15/21	East	Jones	Pencil	35	 4,99 	 174,65 
9/18/21	East	Jones	Pen Set	16	 15,99 	 255,84 
10/22/21	East	Jones	Pen	64	 8,99 	 575,36 
2/18/22	East	Jones	Binder	4	 4,99 	 19,96 
7/4/22	East	Jones	Pen Set	62	 4,99 	 309,38 

### ❌ Actual Behavior

only a few lines of selling actions have been found

**Comment by crazywoola** [comment]
This could happen because we have a `top_k` setting in our retrieval results. The actual results you got depends on this setting. For example,  you have 50 lines, but the `top_k` is 5, in this case, you will only get 5 results.

I think we could try parent-child retrieval in later versions.

**Comment by danielgimeno** [comment]
But now I have increased the Top_k value to 10 and now I only getting 4 rows. This is the complete data regarding Jones:
1/6/21	East	Jones	Pencil	95	 1,99 	 189,05 
4/1/21	East	Jones	Binder	60	 4,99 	 299,40 
6/8/21	East	Jones	Binder	60	 8,99 	 539,40 
8/15/21	East	Jones	Pencil	35	 4,99 	 174,65 
9/18/21	East	Jones	Pen Set	16	 15,99 	 255,84 
10/22/21	East	Jones	Pen	64	 8,99 	 575,36 
2/18/22	East	Jones	Binder	4	 4,99 	 19,96 
7/4/22	East	Jones	Pen Set	62	 4,99 	 309,38 

And this is the output from Dify, when I ask Jones's sells (sorry is in Spanish), I'm only getting 4 results:
Las ventas realizadas por Jones son:

95 unidades de lápices el 6 de enero de 2021, con un costo unitario de 1.99yuntotalde189.05 en la región Este.
35 unidades de lápices el 15 de agosto de 2021, con un costo unitario de 4.99yuntotalde174.65 en la región Este.
16 unidades de juegos de bolígrafos (Pen Set) el 18 de septiembre de 2021, con un costo unitario de 15.99yuntotalde255.84 en la región Este.
60 unidades de carpetas (Binder) el 8 de junio de 2021, con un costo unitario de 8.99yuntotalde539.4 en la región Este.
Thank you for your atention,
Daniel.

**Comment by JohnJyong** [comment]
Would you pls provide more  screen-shot of the `hit-testing` in knowledge ? @danielgimeno

**Comment by JohnJyong** [comment]
mark the issue as closed, if you have any problem , you can reopen it.
