### ISSUE TITLE
After updating the code, the frontend new workflow still cannot be displayed properly

### ISSUE THREAD

**Issue by Erincrying** [langgenius/dify#9677]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. Update dify code
2. Deploy front-end and back-end services, where dependencies are reinstalled and the front-end is repackaged for deployment
3. Start front-end and back-end services
4. Create a new workflow task, but still cannot be opened properly
![image](https://github.com/user-attachments/assets/64097c86-2550-4acd-aa4e-7200aad3b560)
![image](https://github.com/user-attachments/assets/84abbdc1-b032-4c71-a1eb-e40fee7a4905)
![image](https://github.com/user-attachments/assets/c2dc1252-be1d-499b-922f-a5656ef0faad)

### ✔️ Expected Behavior

Can open workflow normally

### ❌ Actual Behavior

After updating the code and redeployment, the problem was not resolved

**Comment by crazywoola** [comment]
Please provide the DSL
