### ISSUE TITLE
Custom "File" variable can not read props in workflows

### ISSUE THREAD

**Issue by nne998** [langgenius/dify#9678]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Custom "File" variable can not read props in workflows:

<img width="721" alt="image" src="https://github.com/user-attachments/assets/8476ad38-bc3a-48aa-aa4a-7012cdce9213">

<img width="864" alt="image" src="https://github.com/user-attachments/assets/0f995d59-da05-44f4-9340-07497a5c1e0a">
<img width="427" alt="image" src="https://github.com/user-attachments/assets/a84f9363-eef4-457b-bd31-2a6696699a80">

Check out the DSL export below:
[test.yml.zip](https://github.com/user-attachments/files/17484107/test.yml.zip)

### ✔️ Expected Behavior

fix bug

**Comment by crazywoola** [comment]
Some node can not read files.

**Comment by nne998** [comment]
> Some node can not read files.

not file ,is the file 's props
