### ISSUE TITLE
conversations delete api response and documentation are different

### ISSUE THREAD

**Issue by good2luck** [langgenius/dify#9680]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I used Docker for private deployment and found that the response did not meet expectations when deleting conversations through API calls。

at the same time，i saw this commit：https://github.com/langgenius/dify/pull/767/files，but it didn't work

![image](https://github.com/user-attachments/assets/6af9d32e-8278-48ab-af87-dc9972e81ade)

### ✔️ Expected Behavior

return ：
{
  "result": "success"
}

### ❌ Actual Behavior

return：
{
    "id": null,
    "name": null,
    "inputs": null,
    "status": null,
    "introduction": null,
    "created_at": null
}

**Comment by Yusaney** [comment]
I have the same issue. I get the same response:
```
{
  "id": null,
  "name": null,
  "inputs": null,
  "status": null,
  "introduction": null,
  "created_at": null
}
```

and the conversations are not being deleted.

**Comment by BenjaminX** [comment]
Reproduce, review code inspection this issue.

**Comment by BenjaminX** [comment]
Rename API the same issue

**Comment by BenjaminX** [comment]
It is recommended that the rename API be called when a new session is created and the first conversation is completed.
