### ISSUE TITLE
[BUG] Script Node in Custom Workflow Cannot Access Properties of Custom File Uploaded URL—Input Argument Returns NULL

### ISSUE THREAD

**Issue by nne998** [langgenius/dify#9681]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a custom workflow.
2. Add a custom file (image) input variable in the "start" node.
3. Add a script node and set the image's URL property as an input argument. Print the input argument for debugging.

### ✔️ Expected Behavior

Got the url

### ❌ Actual Behavior

Got null

**Comment by nne998** [comment]
[example.zip](https://github.com/user-attachments/files/17484259/example.zip)

**Comment by crazywoola** [comment]
See #9567 for details, this is not a bug, this is still under our UI/UX review.
