### ISSUE TITLE
Dynamically set the knowledge base during workflow execution

### ISSUE THREAD

**Issue by Lyeluo** [langgenius/dify#9683]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In many scenarios during our usage, we need to switch the knowledge base based on the user. Can this functionality be achieved by dynamically passing the knowledge base ID when calling the API to execute the workflow? Or is there a plan for this in the future?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Duplicated

**Comment by hmilyxtl2018** [comment]
which one？

**Comment by RAJAVARDHAN6094** [comment]
Did you get solution for the above mentioned issue?
