### ISSUE TITLE
Calling claude-3-5-sonnet-2 via the dedify api Exception

### ISSUE THREAD

**Issue by xiaoshenl** [langgenius/dify#9691]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

WEB:
![image](https://github.com/user-attachments/assets/2a5b4df8-c724-46d2-9947-e28ac6b54574)
![image](https://github.com/user-attachments/assets/4bc8c2c7-822a-4f57-bccc-bc258fa8ede2)
API:
![image](https://github.com/user-attachments/assets/6a011fea-f899-4e4b-9a19-13a21d70ad13)
{
    "code": "completion_request_error",
    "message": "[openai_api_compatible] Error: 'model'",
    "status": 400
}

**Comment by xiaoshenl** [comment]
@dosu
Now, I am using the text-generated application API. because I added a new text-generated application, where I specified the model as claude-3-5-sonnet-2, and the request was successful in the web. But when requesting the api for this app, it returns an exception. api request could not specify the model.

**Comment by crazywoola** [comment]
Either upgrade to latest version or use our latest official provider.
