### ISSUE TITLE
 Unable to extract table data from word document

### ISSUE THREAD

**Issue by naked34501** [langgenius/dify#9693]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

10.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The word document I uploaded contains table data, but the document extractor cannot extract the table data. The entire table data is lost, and the table data in the word document cannot be extracted.

### ✔️ Expected Behavior

The word document I uploaded contains table data, but the document extractor cannot extract the table data. The entire table data is lost, and the table data in the word document cannot be extracted.

### ❌ Actual Behavior

The word document I uploaded contains table data, but the document extractor cannot extract the table data. The entire table data is lost, and the table data in the word document cannot be extracted.

**Comment by crazywoola** [comment]
Duplicated
