### ISSUE TITLE
Unable to log in to dify after updating code and redeployment

### ISSUE THREAD

**Issue by Erincrying** [langgenius/dify#9694]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Unable to successfully store console_token after successful login

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/0f49846e-c5db-48fb-85a3-8dbcd14185e5)
![1729664522143](https://github.com/user-attachments/assets/8a23eab8-5f62-4207-a776-e477e05057be)

**Comment by Erincrying** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.10.0
> 
> ### Cloud or Self Hosted
> Self Hosted (Source)
> 
> ### Steps to reproduce
> Unable to successfully store console_token after successful login
> 
> ### ✔️ Expected Behavior
> _No response_
> 
> ### ❌ Actual Behavior
> ![image](https://private-user-images.githubusercontent.com/65204363/379128120-0f49846e-c5db-48fb-85a3-8dbcd14185e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjU4NjIsIm5iZiI6MTcyOTY2NTU2MiwicGF0aCI6Ii82NTIwNDM2My8zNzkxMjgxMjAtMGY0OTg0NmUtYzVkYi00OGZiLTg1YTMtOGRiY2QxNDE4NWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MzkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjhkYzk2MDdmM2ZlNjNjNDdjNDIzZjJhNDA3M2E2NGJiMjU4ZGZjZDEyOTQ0YmFiNDRmODU0NjBkOTJjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wrIs-XDU6WydFBReGKwuCWV838wsmP4Ag5ClPSUCU6k) ![1729664522143](https://private-user-images.githubusercontent.com/65204363/379128260-8a23eab8-5f62-4207-a776-e477e05057be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjU4NjIsIm5iZiI6MTcyOTY2NTU2MiwicGF0aCI6Ii82NTIwNDM2My8zNzkxMjgyNjAtOGEyM2VhYjgtNWY2Mi00MjA3LWE3NzYtZTQ3N2UwNTA1N2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MzkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MzE4NGEzMmRkZjU0MDY0NjQwMDkwZDRmMTFjZTYxZGRhODBjYzdlOTcwZjAxMTRlNGMzZGNiOTlmYTE2NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RsZvqB5ZK9_t0WQBR9C72dwHClN9xglQ8jF1FZINFos)

postman加上console_token可以调试通，但是页面不行

**Comment by crazywoola** [comment]
Please check the env settings under `./api`. If you are using source code, you should be able to handle it yourself.

**Comment by flyice8** [comment]
> Please check the env settings under `./api`. If you are using source code, you should be able to handle it yourself.

how to do this, thanks!

**Comment by flyice8** [comment]
搞定了吗？我本地源码部署的，也是一样的问题。

**Comment by Erincrying** [comment]
> 搞定了吗？我本地源码部署的，也是一样的问题。

Updating the latest code and redeployment will solve the problem
