### ISSUE TITLE
Error in File ingestion in external api using HTTP Request node

### ISSUE THREAD

**Issue by muckthaa-ss** [langgenius/dify#9695]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I upload a file in the HTTP request body, but it returns an error saying unsupported file format.
Example, I upload a .pdf file and the external api for ingestion handles .pdf and .txt files and for other formats, it throws the "unsupported file format." message.
![Screenshot 2024-10-23 115238](https://github.com/user-attachments/assets/29f5db30-7fb5-43ad-bea3-202065b654a9)

### ✔️ Expected Behavior

File is ingested successfully message in the output.

### ❌ Actual Behavior

Unsupported file format error.

**Comment by muckthaa-ss** [comment]
It is a valid .pdf file and the file is just 422kb. 
I have also verified the API endpoint and the header and it is correct.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9599
