### ISSUE TITLE
HTTP Request Node JSON body error

### ISSUE THREAD

**Issue by qkxie** [langgenius/dify#9696]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. create a http request node
2. set request method to post, and set body to json
3. make a request

### ✔️ Expected Behavior

get the response

### ❌ Actual Behavior

http request node change my json body. the field of `top_k` should be `8`, but in the log, it becomes to `null`, so the request failed.
 
![image](https://github.com/user-attachments/assets/71a2b4fc-78de-41ca-8fb2-bba672ca3c76)
![image](https://github.com/user-attachments/assets/bcd2e368-295f-480c-9160-79a0732a8826)

**Comment by qkxie** [comment]
You can reproduce this bug by just simply set url to `https://xxx.com/a`, and set body to 

```
{
"test1": true,
"test2": 5
}
```

just like below:
![image](https://github.com/user-attachments/assets/1b4d2563-d77c-47ba-a423-2225d68c4779)
![image](https://github.com/user-attachments/assets/76a1b401-cddb-42c3-908f-9e7cf0d01443)

**Comment by qkxie** [comment]
As I use docker-compose to launch Dify, should I build a docker image by myself and replace the image url in docker compose yaml? When will you release a new version which include the patch?

**Comment by crazywoola** [comment]
![image](https://github.com/user-attachments/assets/f51f10e3-a3f7-445c-8080-79529147a7ef)
@qkxie
