### ISSUE TITLE
Application error: a clinet-side exception has occurred(see the browser console for more information)

### ISSUE THREAD

**Issue by liuliwei91** [langgenius/dify#9697]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![无标题](https://github.com/user-attachments/assets/d20bcb84-1dfe-494f-83e1-c97809843915)
`http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/7023-22d2def46e6e81aa.js:1 
        
       

TypeError: Cannot read properties of undefined (reading 'checkValid')
    at http://

[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/app/(commonLayout)/app/(appDetailLayout)/%5BappId

%5D/workflow/page-f5ac00022b31de16.js:1:49502
    at Object.lt [as useMemo] (http://

[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:46775)
    at t.useMemo 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/7023-22d2def46e6e81aa.js:2:31804)
    at eM 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/app/(commonLayout)/app/(appDetailLayout)/

%5BappId%5D/workflow/page-f5ac00022b31de16.js:1:48952)
    at http://

[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/app/(commonLayout)/app/(appDetailLayout)/%5BappId

%5D/workflow/page-f5ac00022b31de16.js:1:61692
    at rE (http://

[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:40344)
    at l$ (http://

[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:59319)
    at lU (http://

[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:58164)
    at iZ (http://

[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:121876)
    at ia 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:95165)
    at 

http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:94987
    at il 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:94994)
    at oJ 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:92350)
    at nb 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:26836)
    at 

http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:108300
    at is 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:108308)
    at o1 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:93000)
    at oZ 

(http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/fd9d1056-7863749520a823c0.js:1:92155)
    at 

MessagePort.T (http://[2409:8a00:6c44:5bc0:3fc4:6a20:23bc:44d1]:8000/_next/static/chunks/7023-22d2def46e6e81aa.js:1:84205)`

**Comment by crazywoola** [comment]
Duplicated, please upgrade to latest version.
