### ISSUE TITLE
Multiple Prompts Testing

### ISSUE THREAD

**Issue by mkeari** [langgenius/dify#9700]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

While developing a new workflow we frequently experiment with the system prompts. Chaning them sometimes improves the results but other times you might want to get back to the previous one. In some cases it is beneficial to have multiple runs with outputs side-by-side for comparison. And keeping track of each of them in a separate notetaking app is frustrating. 

Therefore, is it possible to add support for 2 (or more) different versions of system prompt running simultaneously? With side-by-side display of their outputs (similar to ChatGPT's suggested 2 versions). Maybe a special mode or button near the "Preview".

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by mkeari** [comment]
I just realized that Dify has something similar but for models comparison ("Debug as Multiple Models"). But now it would be great to have the analog for prompts, and preferably not only in basic chatbot but chatflow as well

**Comment by nickjfrench** [comment]
I mentioned a similar request in #9055 but about Debug as Multiple Models in Workflow/Chatflow mode. Having multiple prompts testing and multiple models testing would help a great load in early development.
