### ISSUE TITLE
Provide a method to set data volume on host using environment variable for postgres and redis

### ISSUE THREAD

**Issue by jter** [langgenius/dify#9701]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Can't specific host volumes for postgres and redis through .env file, though we can change it in compose file but it would be better if we can configure this by env.

Change in`docker/docker-compose.middleware.yaml` file like this:
`- ${PGDATA_HOST_VOLUME:-./volumes/db/data}:/var/lib/postgresql/data`
Add `PGDATA_HOST_VOLUME=./volumes/db/data` to `docker/middleware.env.example`

What do you think? I can write a PR for this.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
LGTM 
`docker/middleware.env.example` Since you are modifying things here, you might need to edit the docs in readme as well.
