### ISSUE TITLE
Adding else condition branch error

### ISSUE THREAD

**Issue by luxi001-aaa** [langgenius/dify#9719]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![1729676672827](https://github.com/user-attachments/assets/3bcc0d60-7ec5-4cd4-a993-7a52f6aa8147)
![1729676672833](https://github.com/user-attachments/assets/c5064cd8-2a0f-4a29-b0b9-2fe0d8d63e17)

**Comment by crazywoola** [comment]
Please provide the DSL

**Comment by luxi001-aaa** [comment]
I found a rule that in the process of workflow orchestration, the preview debugging robot functions normally when it is opened, and cannot add else functions when it is closed, which is the case in any process

> 请提供 DSL

**Comment by GeorgeCaoJ** [comment]
> I found a rule that in the process of workflow orchestration, the preview debugging robot functions normally when it is opened, and cannot add else functions when it is closed, which is the case in any process

I encountered the same issue. Specifically, the IfElseNode can add the ELIF condition only when the preview debugging window is opened first.
