### ISSUE TITLE
After deleting the data set, the preview fails

### ISSUE THREAD

**Issue by wangrg** [langgenius/dify#972]
Dify version: Cloud | Self Host

## Steps To Reproduce

1. Associate the dataset with the application first
2. The next step is to go to the dataset control panel to delete the dataset.
3. The next step is to go to preview the application.

## The current behavior
The reason is that the 'agent_mode' field in the 'app_model_configs' table was not modified, which caused the issue.

## The expected behavior
After deleting the dataset, modify the 'agent_mode' field in the 'app_model_configs' table at the same time.

**Comment by wangrg** [comment]
It's not a table creation issue, but rather running agent_executor.run after deleting the dataset causing a crash.

**Comment by crazywoola** [comment]
It should fix in latest versions. If this question persists, you can reopen this issue.
