### ISSUE TITLE
Add description and indexing_technique parameters for creat empty datasets api

### ISSUE THREAD

**Issue by rchlz** [langgenius/dify#9723]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

No specific challenge, but I believe this feature can enhance the flexibility and customization capabilities of Dify.

### 2. Additional context or comments

In Dify's Knowledge Base API, there is an interface for creating an empty knowledge base. I would like to add description and indexing_technique parameters to this interface. This way, users can specify these two parameters when creating an empty knowledge base.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/9d221a5e19f8613fa1a47984649378b22a0fd66e/api/controllers/service_api/dataset/dataset.py#L59-L121

I checked the code, we do have the abilities to add the parameters, but it isn't reflected in the API docs, you could open a PR for this.

**Comment by rchlz** [comment]
> https://github.com/langgenius/dify/blob/9d221a5e19f8613fa1a47984649378b22a0fd66e/api/controllers/service_api/dataset/dataset.py#L59-L121
> 
> I checked the code, we do have the abilities to add the parameters, but it isn't reflected in the API docs, you could open a PR for this.

Yes, I found that the new version has added many parameters, but there is still no description parameter. Can I add this parameter?
At the same time, I will update the api docs

**Comment by rchlz** [comment]
finished
