### ISSUE TITLE
Gemini bug with function call

### ISSUE THREAD

**Issue by lichao4Java** [langgenius/dify#9725]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Gemini bug with function call

### ✔️ Expected Behavior

Can be used normally when configuring function call

### ❌ Actual Behavior

Select the Gemini model and configure the function call tool. Error reported during use
![image](https://github.com/user-attachments/assets/a44ac92b-e7b7-4c0d-ac78-a78e0fa30441)

No error when function call is not configured
![image](https://github.com/user-attachments/assets/ac758e49-f788-4f53-96f8-559d78ac14e8)

**Comment by lichao4Java** [comment]
choose  time  tools  then  Error reported during use

**Comment by hjlarry** [comment]
this issue is caused by  some tools like `current_time` which don't have parameters,  but send google with empty parameters

but when I tried to fix this,  I found that all other tools with parameters,  google will response http 500
![243807b9cd1679dba14a395ebfd8e64](https://github.com/user-attachments/assets/9a6431ed-8225-42d3-8a23-d45d17b3a3d8)
even when I tried to use the default example in the google AI web console platform,  this error occasionally occurs.
@lichao4Java have you encountered this issue?

**Comment by hjlarry** [comment]
> but when I tried to fix this, I found that all other tools with parameters, google will response http 500 ![243807b9cd1679dba14a395ebfd8e64](https://private-user-images.githubusercontent.com/25834719/379633903-9a6431ed-8225-42d3-8a23-d45d17b3a3d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODc1ODEsIm5iZiI6MTczMDE4NzI4MSwicGF0aCI6Ii8yNTgzNDcxOS8zNzk2MzM5MDMtOWE2NDMxZWQtODIyNS00MmQzLThhMjMtZDQ1ZDE3YjNhM2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MzdmMmNjOGJiZGFhOGIzNjU5YzExNjliYzY4MGRjMzU4OGI2OGY2ZDg5NDllNDYxNGQwMjY5ZmVjNDU2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4pXrqLE3TJXVChcpvFUJEZAFzJREqWcdhuFLWvKWKHM) even when I tried to use the default example in the google AI web console platform, this error occasionally occurs. @lichao4Java have you encountered this issue?

Now Google suddenly stops reporting 500 errors.
