### ISSUE TITLE
Error when setting parameters for the Azure OpenAI o1 series model.

### ISSUE THREAD

**Issue by Moiyu1998** [langgenius/dify#9729]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The o1 series models have many parameters that cannot be modified, so they do not need to be displayed in the UI. The only parameter that can be changed is the maximum output length, but the parameter name has changed. Please refer to the error message in the image below and fix this promptly.
![image](https://github.com/user-attachments/assets/0c602118-2ef7-4a62-9710-618f1e731c94)

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9746
