### ISSUE TITLE
What is the local API format for ChatGLM responses?

### ISSUE THREAD

**Issue by sichehu** [langgenius/dify#9734]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/73f4d563-3392-4bda-945c-3b3ce4d6afef)

The localized deployment of the ChatGLM model can receive diverse inputs, but the responses returned are always in the wrong format. Is there any documentation for reference?

### ✔️ Expected Behavior

normal

### ❌ Actual Behavior

it is none

**Comment by crazywoola** [comment]
Please provide the correct version information.

**Comment by sichehu** [comment]
the dify version is 0.7.3
![image](https://github.com/user-attachments/assets/4ae7f021-81d5-4917-bcf4-9821237bef16)


> 请提供正确的版本信息。

**Comment by sichehu** [comment]
> 请提供正确的版本信息。
Could you provide me with the default response interface format for ChatGLM2-6B?  I use it but it is  wrong.
{
  "response": "你好！我是人工智能助手 ChatGLM2-6B，很高兴见到你，欢迎问我任何问题。",
  "history": [
    ["你好", "你好！我是人工智能助手 ChatGLM2-6B，很高兴见到你，欢迎问我任何问题。"]
  ],
  "status": 200,
  "time": "2024-01-26 16:20:04"
}

**Comment by crazywoola** [comment]
Please upgrade to the latest version.
