### ISSUE TITLE
Ability to control logs. 

### ISSUE THREAD

**Issue by Yusaney** [langgenius/dify#9747]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I have some intensive workflows that run many times a day (some translate without LLM, and some run an LLM vision). I have configured my Tracing backend, so I don't need the logs in Dify for anything. However, storing each log in Dify causes a very high memory usage in my Dify instance.

![Captura de pantalla 2024-10-23 185142](https://github.com/user-attachments/assets/8ff2dcbc-1fdf-4072-87de-53ea59c690bd)

It would be great to completely disable logs for a conversation/workflow or set up a deletion period after its execution to keep healthy and fresh log files, but deleting old files (prune)

Thanks.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by JVini0166** [comment]
I was searching for something like that, it's not good to store millions of conversations without deleting

**Comment by qkzsky** [comment]
I am also encountering this issue, and I have been trying to clear the logs by deleting the app. However, after deleting the app, I noticed that the records in the workflow_app_log table did not decrease. I suggest adding a log retention period setting and a feature to clean up app logs. Thank you very much.

**Comment by Yusaney** [comment]
I'm still having issues with this. Hopefully, we'll get a fix soon. As the app keeps growing, I have hundreds of thousands of logs that I don't need.

**Comment by crazywoola** [comment]
We have update the navigation component, I think you can try it out.
