### ISSUE TITLE
When talk to chatflow again, error prompt: variable size 5350 exceeds limit 5120

### ISSUE THREAD

**Issue by jenkin2120** [langgenius/dify#9749]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.Designed a chatflow with two steps of qwen2.5, and chat memory settings is disable;
2.The first LLM prompt length is 3300+ characters, the second LLM prompt length is more 4000+;
3.When start a new conversation，first question is replayed perfectly， but second question prompt: variable size 5350 exceeds limit 5120 in the dialog page, Retry third、forth question prompt same error.
4.I searched content: 'raise VariableError(f"variable size {result.size} exceeds limit {dify_config.MAX_VARIABLE_SIZE}")' in the file 'variable_factory.py'  should matching above error, but MAX_VARIABLE_SIZE is set in .env, and the value is 204800.
5.I searched all files with content 5120, but nothing found related to it. 

### ✔️ Expected Behavior

pls check the reson of the error:  variable size 5350 exceeds limit 5120, and fix the bug

### ❌ Actual Behavior

![1](https://github.com/user-attachments/assets/a86bbb4f-38a3-420d-8b22-d2eadb5e6018)

**Comment by crazywoola** [comment]
For docker, please check the `.env` in this folder `docker/`.

**Comment by jenkin2120** [comment]
Thanks!
I did as Dosu @dosu says, It works, I am continuously monitoring the operation status.
I hope MAX_VARIABLE_SIZE variable can be writen into the section 'api' of docker-compose.yaml file explicitly later.
Thank you once again.
