### ISSUE TITLE
The workflow run failed after updated to version 1.10+

### ISSUE THREAD

**Issue by zhaojunfeng** [langgenius/dify#9753]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0-0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The workflow could run well in version 0.8-0.9,  but in version 0.10+,   got this error:  Query not found

The Error message code snippet: 
    workflow/nodes/llm/node.py,  line 118.

The dsl: 
[OneStep售前助手wf.zip](https://github.com/user-attachments/files/17500826/OneStep.wf.zip)

### ✔️ Expected Behavior

run the workflow well

### ❌ Actual Behavior

get error "Query not found"

**Comment by crazywoola** [comment]
We do not have this version/

**Comment by zhaojunfeng** [comment]
[OneStep售前助手wf.zip](https://github.com/user-attachments/files/17500572/OneStep.wf.zip)

lastestion version 0.10.1
