### ISSUE TITLE
Doc Extractor does not support the parsing of markdown format files

### ISSUE THREAD

**Issue by yaoice** [langgenius/dify#9757]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1. upload markdown file named `test1.md`
2. talk to the bot
<img width="1876" alt="image" src="https://github.com/user-attachments/assets/8da876e7-78de-44ce-b151-f5f5862b389a">
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/671cfe14-3eab-4aa7-925c-e50944623a1e">

### ✔️ Expected Behavior

Properly parse markdown files.

### ❌ Actual Behavior

Return `Run failed: Unsupported MIME type: application/octet-stream`

**Comment by crazywoola** [comment]
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/b22168df-ab80-447b-a6fd-9435ac643d7e">
It seems working  for me on Cloud version.

**Comment by yaoice** [comment]
> <img alt="image" width="1167" src="https://private-user-images.githubusercontent.com/100913391/379541924-b22168df-ab80-447b-a6fd-9435ac643d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDg5NzEsIm5iZiI6MTcyOTc0ODY3MSwicGF0aCI6Ii8xMDA5MTMzOTEvMzc5NTQxOTI0LWIyMjE2OGRmLWFiODAtNDQ3Yi1hNmZkLTk0MzVhYzY0M2Q3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwNTQ0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWJmNTI0ZmY5NWVjMzE4MDE4NzE3ZDNjNDhmNTMzYjliMGEyZWIyMGMyZWQxYjY5MWI2ZjE4YWM1NjZmOWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yDkAhNPjHlsM2hSMxDaqO2tGhBZWZIQyjeocE4fS7gE"> <img alt="image" width="1328" src="https://private-user-images.githubusercontent.com/100913391/379542344-3d9f21bf-6094-4164-a425-fcdc42fe77d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDg5NzEsIm5iZiI6MTcyOTc0ODY3MSwicGF0aCI6Ii8xMDA5MTMzOTEvMzc5NTQyMzQ0LTNkOWYyMWJmLTYwOTQtNDE2NC1hNDI1LWZjZGM0MmZlNzdkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwNTQ0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGI1ZDAwZDUwMTcwMGRiMDk1M2U4NWFmZDE5ZDBhNjhmMjk1MzE1YjNlMTg3MzllYmQ4OGVlYzM0MTMxZTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZDG9begvJUR_46ApnUekhnhhqWgeH75iNKeukyh8a8g">
> It seems working for me on Cloud version.

@crazywoola I use the docker-compose version and the source code version for testing. Can you try it?

**Comment by crazywoola** [comment]
Can you try https://github.com/langgenius/dify/pull/9543 this pr? If you have further questions you can DM my wechat crazyphage.
