### ISSUE TITLE
file type document is not supported

### ISSUE THREAD

**Issue by wangshiyang** [langgenius/dify#9760]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. upload pdf file: test.pdf
2. run workflow.
3. 
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/1bae3c0a-4039-48c4-ae03-89fc4372edb6">
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/4e947cec-73a1-43f3-8dda-a01bb89cd94b">

### ✔️ Expected Behavior

Properly parse pdf files.

### ❌ Actual Behavior

Return Run failed: file type document is not supported

**Comment by crazywoola** [comment]
Please read the docs https://docs.dify.ai/guides/workflow/node/doc-extractor

**Comment by wangshiyang** [comment]
> Please read the docs https://docs.dify.ai/guides/workflow/node/doc-extractor
In that case, does it mean the vision functionality can't be used anymore? If we want to continue using vision, we must upload an image, right?

<img width="912" alt="image" src="https://github.com/user-attachments/assets/a92b0caf-e68b-4e3a-bceb-46953319e0d8">

**Comment by duy1851999** [comment]
How about handle Run failed: file type parameter input not supported in agent
