### ISSUE TITLE
azure openai api Stream options UI CHAT ERROR

### ISSUE THREAD

**Issue by dale22** [langgenius/dify#9762]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

use api can be set streaming . but ui not set , so is error 
model name:gpt-4o-2024-05-13
azure openai api version:2024-05-01-preview
step
1,set model is ok，so API Key and Endpoint and deployment name is ok
![image](https://github.com/user-attachments/assets/46058437-7c27-4ab0-ae89-3b17be7096b1)
2,but dify chat is error, and ui not set streaming false， docker-api logs:403
![image](https://github.com/user-attachments/assets/ee8e1f26-356b-4c98-b16d-a4f2b5c35340)
![image](https://github.com/user-attachments/assets/bfc6e0b0-7296-42ac-8c80-6bc5ee64e9de)

How I can ui chat ,close streaming

**Comment by crazywoola** [comment]
> This error is more like the model itself does not support streaming, and I remember that if I used structure output, there would be a similar error, no matter it's OpenAI or Azure OpenAI

**Comment by dale22** [comment]
I don't need structural output, how to configure UI chat
