### ISSUE TITLE
Syntax error: Unexpected token, expected "from"

### ISSUE THREAD

**Issue by likenamehaojie** [langgenius/dify#9763]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

 ⨯ ./middleware.ts:1:12
Syntax error: Unexpected token, expected "from"

> 1 | import type { NextRequest } from 'next/server';
    |             ^
  2 | import { NextResponse } from 'next/server'
  3 |
  4 | const NECESSARY_DOMAIN = '*.sentry.io http://localhost:* http://127.0.0.1:* https://analytics.google.com googletagmanager.com *.googletagmanager.com https://www.google-analytics.com https://api.github.com'        
TypeError: The "path" argument must be of type string. Received undefined

### ✔️ Expected Behavior

 ⨯ ./middleware.ts:1:12
Syntax error: Unexpected token, expected "from"

> 1 | import type { NextRequest } from 'next/server';
    |             ^
  2 | import { NextResponse } from 'next/server'
  3 |
  4 | const NECESSARY_DOMAIN = '*.sentry.io http://localhost:* http://127.0.0.1:* https://analytics.google.com googletagmanager.com *.googletagmanager.com https://www.google-analytics.com https://api.github.com'        
TypeError: The "path" argument must be of type string. Received undefined

### ❌ Actual Behavior

 ⨯ ./middleware.ts:1:12
Syntax error: Unexpected token, expected "from"

> 1 | import type { NextRequest } from 'next/server';
    |             ^
  2 | import { NextResponse } from 'next/server'
  3 |
  4 | const NECESSARY_DOMAIN = '*.sentry.io http://localhost:* http://127.0.0.1:* https://analytics.google.com googletagmanager.com *.googletagmanager.com https://www.google-analytics.com https://api.github.com'        
TypeError: The "path" argument must be of type string. Received undefined

**Comment by likenamehaojie** [comment]
@crazywoola

**Comment by crazywoola** [comment]
Not able to reproduce this problem

```bash
~/Program/dify/web (main) » yarn dev                                                                                                                                
yarn run v1.22.19
$ next dev
  ▲ Next.js 14.2.10
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
   Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
   automatically enabled Fast Refresh for 1 custom loader
 ✓ Ready in 5.1s
```

**Comment by likenamehaojie** [comment]
要访问下页面才会报错
localhost:3000
@crazywoola

**Comment by mayiming0708** [comment]
the same problem when run `npm build` , delete `babel.config.js` success
