### ISSUE TITLE
The problem classifier using AWS Bedrock's claude model will report an error

### ISSUE THREAD

**Issue by YYyp99** [langgenius/dify#9764]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

In the workflow, I used a problem classifier and chose AWS Bedrock's Claude model. I used Claude 3.5 Sonnet, but when I ran it, an error occurred

### ✔️ Expected Behavior

Successfully run

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/2c0a0e21-66be-47b5-b5a9-950c639a2ed8)
error message：
Run failed: [bedrock] Error: ValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.

**Comment by crazywoola** [comment]
This is because Claude doesn't have a system role, if you change to anther series such as openai, then it should work. In advance mode, everything you typed should be set in the system role, so this could happen.

**Comment by YYyp99** [comment]
> This is because Claude doesn't have a system role, if you change to anther series such as openai, then it should work. In advance mode, everything you typed should be set in the system role, so this could happen.

Previously, there was no problem with using it, but after upgrading, this issue occurred. Will this bug be fixed? Because the model I am currently using is mainly claude

**Comment by ma77022** [comment]
I have also encountered this problem, have you solved it?

**Comment by fsatsuki** [comment]
I have this problem. version is v0.11.0

**Comment by nadazero** [comment]
I meet same issue on v0.10.2 ,
When can the official fix this bug？

**Comment by sunhui0608** [comment]
same here

**Comment by AVLISkun** [comment]
I'm also observing the same issue in Amazon Bedrock.
I believe this is a critical problem for tasks involving question classification.

**Comment by nadazero** [comment]
This issue has seriously affected our project. 
When could the official plan to fix it？

**Comment by sunhui0608** [comment]
Same to us.

**Comment by nadazero** [comment]
This issue has seriously affected our project.
When could the official plan to fix it？

**Comment by YYyp99** [comment]
It seems that version 0.11.2 still hasn't fixed this issue

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/10976 for updates.

**Comment by nadazero** [comment]
Close?

**Comment by fsatsuki** [comment]
It doesn't look like there's any new information on the #10976, so I wonder why this ticket was closed.

**Comment by sunhui0608** [comment]
@crazywoola  no extra information and solution provided, pls help to fix the showstop issue of classifier.

> See #10976 for updates.

**Comment by FelixFeli** [comment]
> This is because Claude doesn't have a system role, if you change to anther series such as openai, then it should work. In advance mode, everything you typed should be set in the system role, so this could happen.

That should be the reason, but whether I turn on the advanced model or not. None of the classifiers using Claude's model work properly, which is obviously a bug. Please keep an eye on this, thanks.
