### ISSUE TITLE
http node in chat workflow catch error when test upload file

### ISSUE THREAD

**Issue by guogeer** [langgenius/dify#9769]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. create chat workflow
2. add http node
3. only execute http node
![image](https://github.com/user-attachments/assets/e9c63a3b-13e3-4bf7-a5cd-2884a543b497)
use chat page can upload
![image](https://github.com/user-attachments/assets/943c77e8-d2ea-4382-a0c3-dace39c18ef8)

### ✔️ Expected Behavior

can upload file

### ❌ Actual Behavior

tips 文件类型不支持

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9599
