### ISSUE TITLE
Issue with Image Uploads Using “remote_url” on Dify Cloud Solution Post v0.10 Release

### ISSUE THREAD

**Issue by nguyenphan** [langgenius/dify#9776]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1.	Use Dify GUI or API to send a request to a Text Generation app or Workflow app.
2.	Use an image file that references a “remote_url” rather than uploading directly to Dify.
3.	Observe that the request fails regardless of the app type (e.g., Text Generation, Workflow).

Prior to the release of version 0.10, the same apps worked correctly without any issues. Direct requests to Google Gemini through the Google JS SDK using the same image URL work without problems, suggesting the issue is specific to Dify’s handling of “remote_url” after the update.

These problems do not occur if I use the "Upload from Computer" option.

### ✔️ Expected Behavior

Image uploads using “remote_url” should work seamlessly as they did prior to version 0.10, allowing apps like Google Gemini Pro and GPT-4o to process requests without errors.

### ❌ Actual Behavior

•	Google Gemini Pro: Returns [google] Server Unavailable Error, 500 An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting.
•	GPT-4o: Returns [openai] Bad Request Error, Error code: 400 - {'error': {'message': 'Invalid MIME type. Only image types are supported.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_image_format'}}.
•	Dify GUI: Image uploads consistently fail, as shown in the attached screenshot (image error and network console logs).

This is the error from the GUI:
![Screenshot 2024-10-22 at 5 08 12 PM](https://github.com/user-attachments/assets/db6c170f-fb18-46ab-ab6e-914b49ccd287)

**Comment by nguyenphan** [comment]
its detected mime is `image/jpeg`. So please allow dev to look at this and fix this asap. Given the amount of issue filed post 0.10 regarding file handling, there might be some major hole in the codebase

**Comment by laipz8200** [comment]
Before v0.10.0, we only supported images. Now, for files using remote_url, we send a HEAD request to this URL and use the returned Content-Type. For the provided URL, S3 returned `application/octet-stream`.

**Comment by nguyenphan** [comment]
@laipz8200 so, how should you recommend me to fix this?

**Comment by nguyenphan** [comment]
@laipz8200 explicitly setting ContentType when upload to s3 will fix this problem.

**Comment by laipz8200** [comment]
I created a PR to optimize the guessing of file mimetypes, which will make using files via remote_url more stable. However, this will not resolve the issue with file uploads on the web, as that problem is caused by CSP.

**Comment by nguyenphan** [comment]
@laipz8200 sure, thanks for the follow up, you can reopen the issue if you want, it is true that the website issue is still there.

**Comment by nguyenphan** [comment]
> I created a PR to optimize the guessing of file mimetypes, which will make using files via remote_url more stable. However, this will not resolve the issue with file uploads on the web, as that problem is caused by CSP.

hopefully you guys can update this flow, since all of the images I upload to s3 were not explicitly set with ContentType...

**Comment by lzfxxx** [comment]
I've developed a solution for this CSP issue - a simple Image Downloader Plugin for Dify.

This plugin solves the problem by downloading images from external domains and returning them as blobs, which bypasses the CSP restrictions in udify.app.

Key features:
- Downloads images from any public URL
- Automatically detects image type and sets correct MIME types
- Simple to use with just one parameter (image_url)
- Works with common image formats (JPG, PNG, GIF, BMP, WebP, etc.)

For a practical workflow, you can use a Python runtime node to extract image URLs from AI-generated markdown content, then pass those URLs to this plugin to display the images properly.

<img width="867" alt="Image" src="https://github.com/user-attachments/assets/02b1563a-a27b-409a-900f-8b0c143fd4c8" />

Here's the source code if you're interested: https://github.com/lzfxxx/image-downloader

Hope this helps others facing the same issue!
