### ISSUE TITLE
usage in openai compatiable api' llm update from  upstream

### ISSUE THREAD

**Issue by guogeer** [langgenius/dify#9787]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

usage in openai compatiable api' llm count by tiktoken, but response data may include field usage

### ✔️ Expected Behavior

usage is same with response 

### ❌ Actual Behavior

usage is not same with response

**Comment by crazywoola** [comment]
Sorry we do not have a plan for this, if you are interested, please open a pull request.
