### ISSUE TITLE
400 | Bad Request.

### ISSUE THREAD

**Issue by Homura00** [langgenius/dify#9807]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am upgrading from version 0.8.3 to version 0.10.1 and encountering a 400 bad request issue.
![image](https://github.com/user-attachments/assets/1da4556e-feae-4a99-a2a8-1beeaca43022)

I enabled the log level to debug and set debug to true, and then I got the following logs.
[web.txt](https://github.com/user-attachments/files/17506975/web.txt)
[worker.txt](https://github.com/user-attachments/files/17506976/worker.txt)
[api.txt](https://github.com/user-attachments/files/17506977/api.txt)

And in the API log, I get a specific error.

![Imagem do WhatsApp de 2024-10-24 à(s) 09 25 46_0fe8e5f3](https://github.com/user-attachments/assets/30fae481-e035-4c52-812d-53c18fe5f174)

But if I switch from version 0.8.3 to 0.9.1 prefix1, it also works fine. However, after version 0.10.x, I get this error.

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/341c9621-7fbd-4c0b-a4ab-3c7397b64fed)

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/cc61fbcc-c611-4135-b875-cc20121723f6)

**Comment by Homura00** [comment]
Thank you for your response. I checked the logs and also the environment variables, and everything seems fine. There's nothing related to app_unavailable, not_completion_app, not_chat_app, or provider_not_initialize.

**Comment by crazywoola** [comment]
Please read this before you are upgrading to latest version. 
- I think you need to clear the browser cache.
From the images you provided, I can not tell which part is wrong. I think you need to provide more information for the 400 page.

**Comment by Homura00** [comment]
@crazywoolala 

I cleared it, tried incognito browsers, installed new browsers to test, and it remains... If you could tell me what other types of information I need to provide, I will be happy to bring them...

Some, if it helps... link: df.abraoesilvaadvogados.com.br
console error...

![image](https://github.com/user-attachments/assets/bf857a9b-fcf8-429c-b8be-ddb82a367582)

network response header...

<!DOCTYPE html>
<html>
    <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width"/>
        <title>400: Bad Request</title>
        <meta name="next-head-count" content="3"/>
        <noscript data-n-css=""></noscript>
        <script defer="" nomodule="" src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js"></script>
        <script src="/_next/static/chunks/webpack-24620237a0778e64.js" defer=""></script>
        <script src="/_next/static/chunks/framework-08aa667e5202eed8.js" defer=""></script>
        <script src="/_next/static/chunks/main-dc8c4a618d5ceef0.js" defer=""></script>
        <script src="/_next/static/chunks/pages/_app-f870474a17b7f2fd.js" defer=""></script>
        <script src="/_next/static/chunks/pages/_error-c66a4e8afc46f17b.js" defer=""></script>
        <script src="/_next/static/xVbExYD4JNj8mT3ukWNDv/_buildManifest.js" defer=""></script>
        <script src="/_next/static/xVbExYD4JNj8mT3ukWNDv/_ssgManifest.js" defer=""></script>
    </head>
    <body>
        <div id="__next">
            <div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center">
                <div style="line-height:48px">
                    <style>
                        body {
                            color: #000;
                            background: #fff;
                            margin: 0
                        }

                        .next-error-h1 {
                            border-right: 1px solid rgba(0,0,0,.3)
                        }

                        @media (prefers-color-scheme: dark) {
                            body {
                                color:#fff;
                                background: #000
                            }

                            .next-error-h1 {
                                border-right: 1px solid rgba(255,255,255,.3)
                            }
                        }
                    </style>
                    <h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">400</h1>
                    <div style="display:inline-block">
                        <h2 style="font-size:14px;font-weight:400;line-height:28px">Bad Request
                        
                        .</h2>
                    </div>
                </div>
            </div>
        </div>
        <script id="__NEXT_DATA__" type="application/json">
            {
                "props": {
                    "pageProps": {
                        "statusCode": 400
                    }
                },
                "page": "/_error",
                "query": {
                },
                "buildId": "xVbExYD4JNj8mT3ukWNDv",
                "isFallback": false,
                "isExperimentalCompile": false,
                "gip": true,
                "scriptLoader": [
                ]
            }</script>
    </body>
</html>


header

![image](https://github.com/user-attachments/assets/e4d959a1-c4f2-44d4-b0e4-d1e66ad90ea9)

**Comment by crazywoola** [comment]
I checked your website, it's really weird. I will check with the team again tmr.

**Comment by devmiro** [comment]
I also upgrade from 0.8.3 to latest and got this error.

need to rollback

**Comment by Homura00** [comment]
This is my first installation. I also tried with version 0.9.1 prefix, and it works fine for me, but when I move to 0.10.x, I get the same problem.

**Comment by vinifonz** [comment]
Same here for 0.10.1 and I have other reports of the same error.

**Comment by Homura00** [comment]
I've tried changing versions of traefik, I've tried reinstalling in other ways and only up to version 0.9.1 prefix1 has it worked well, but if I update beyond 0.10.x, I get error 400.

**Comment by felipeautomacao** [comment]
Same here for 0.10.2 and I have other reports of the same error.

**Comment by poneisbr** [comment]
Same here for 0.10.2 and I have other reports of the same error.
O mesmo acontece com a versão 0.10.2 e tenho outros relatos do mesmo erro.

**Comment by mtcoliveira** [comment]
I've been struggling with this issue since the beta version of 0.10.x
I'm currently running v0.10.2 on top of Traefik 3x

**Comment by Homura00** [comment]
@mtcoliveira which traefik 3? cuz i try 3.2 and same error....

**Comment by mtcoliveira** [comment]
> @mtcoliveira which traefik 3? cuz i try 3.2 and same error....

@Homura00 My Traefik is at v3.1.2
Have you solved your problem?

**Comment by Homura00** [comment]
yes, I re-installed using easypanel and it worked fine for me, but using the portainer it wasn't working.

**Comment by mtcoliveira** [comment]
> yes, I re-installed using easypanel and it worked fine for me, but using the portainer it wasn't working.

Can you send me the .yaml files that were generated by easypanel?

**Comment by crazywoola** [comment]
I guess this can be closed, we haven't test it with platform like easy panel nor the portainer.

**Comment by poneisbr** [comment]
Boa noite, se estiver usando a stack, basta comentar a variável  hostname da stack web, assim o erro 400 some.: 
 dify_web:
    # Define a imagem do Dify
    # https://hub.docker.com/r/langgenius/dify-web
    image: langgenius/dify-web:0.11.2
    # Define o Hostname
   ** hostname: "{{.Service.Name}}.{{.Task.Slot}}"** comentar essa variável !!!!
    **# hostname: "{{.Service.Name}}.{{.Task.Slot}}"** fica assim !!!!
    # Configura a rede do Serviço
AGORA NÃO APARECE MAIS O ERRO 400, PODE ATUALIZAR QUE NÃO APARECE MAIS O ERRO, ABRAÇOS A TODOS FICAM COM DEUS!!!!
----------------------------
Good evening, if you are using the stack, just comment out the hostname variable of the web stack, so the 400 error disappears.:
dify_web:
# Define the Dify image
# https://hub.docker.com/r/langgenius/dify-web
image: langgenius/dify-web:0.11.2
# Define the Hostname
** hostname: "{{.Service.Name}}.{{.Task.Slot}}"** comment out this variable !!!!
**# hostname: "{{.Service.Name}}.{{.Task.Slot}}"** it looks like this !!!!
# Configure the Service network
NOW THE ERROR 400 DOES NOT APPEAR ANYMORE, YOU CAN UPDATE AND THE ERROR WILL NOT APPEAR ANYMORE, HUGS TO ALL, GOD BE WITH YOU !!!!
