### ISSUE TITLE
Can the community version add a speech-to-text function? Currently, when the community version opens voice in the browser, it shows that it is not authorized.

### ISSUE THREAD

**Issue by chiefluo** [langgenius/dify#9808]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, when the community version opens voice in the browser, it shows that it is not authorized.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
We do support `speech-to-text` in CE version, you need to check you browser settings and use `https`.

**Comment by chiefluo** [comment]
The dify project on my server has opened the https access right, but the microphone on the browser is grayed out and cannot be set. I opened the shared URL with my phone and other browsers, and it also showed that the voice was not authorized.

**Comment by chiefluo** [comment]
> 我们确实支持`speech-to-text`CE 版本，您需要检查您的浏览器设置并使用`https`。

The dify project on my server has opened the https access right, but the microphone on the browser is grayed out and cannot be set. I opened the shared URL with my phone and other browsers, and it also showed that the voice was not authorized.

**Comment by chiefluo** [comment]
> 我们确实支持`speech-to-text`CE 版本，您需要检查您的浏览器设置并使用`https`。

我服务器上面的dify项目已经打开了https的访问权限，浏览器那里的麦克风是灰色状态，不能设置。我用手机和其他浏览器打开分享的网址，同样显示语音未授权

**Comment by chiefluo** [comment]
> 我们确实支持`speech-to-text`CE 版本，您需要检查您的浏览器设置并使用`https`。
<img width="580" alt="337be70d68de918f6cc047ce62c7568" src="https://github.com/user-attachments/assets/7ea9b776-a938-44e1-8f41-01abeecd065f">

<img width="424" alt="832a1f75696d0cddd50f1fe2a12a390" src="https://github.com/user-attachments/assets/aac8b404-3c8a-4045-8dc0-c7fb146c234e">

**Comment by chiefluo** [comment]
![image](https://github.com/user-attachments/assets/5b752141-eddd-4c9a-9609-63a2572596ac)

**Comment by chiefluo** [comment]
> We do support `speech-to-text` in CE version, you need to check you browser settings and use `https`.

![image](https://github.com/user-attachments/assets/071f2371-f3d2-48d9-84c6-92585ffc90c0)
