### ISSUE TITLE
API return NULL answer

### ISSUE THREAD

**Issue by cmastro** [langgenius/dify#981]
If we have huge Datasets, the API return NULL in the answer:

<img width="794" alt="image" src="https://github.com/langgenius/dify/assets/8320554/7e22d475-3d09-4e75-9be4-db75d7d3eb4e">

Answer: NULL
```
{
    "event": "message",
    "task_id": "c48e77ea-86a5-4e22-bfc9-XXXXXXXX",
    "id": "ff486c91-7c74-4003-a96f-XXXXXXXX",
    "answer": null,
    "created_at": 1692807434,
    "conversation_id": "7a7c3509-1297-487e-b4a7-XXXXXXXX"
}
```

![image](https://github.com/langgenius/dify/assets/8320554/19a0cf6c-ddfb-4c0c-ac2a-4a2b9338164e)

```
{
    "event": "message",
    "task_id": "6cdc8ef8-eb00-45c0-af76-XXXXXXXX",
    "id": "6a88f3c5-794b-4214-9527-XXXXXXXX",
    "answer": "¡Hola! ¿En qué puedo ayudarte hoy?",
    "created_at": 1692807632,
    "conversation_id": "16f1dd05-86c5-4dee-a7f3-XXXXXXXX"
}
```

Dify version: 0.3.16 Self Host

Web chat works as expected.

**Comment by tandangfei** [comment]
![image](https://github.com/langgenius/dify/assets/22535127/47d24fef-ad76-48a4-b676-6527050d34b9)
![image](https://github.com/langgenius/dify/assets/22535127/ec86e648-d1a3-4aba-be81-17d1c827692a)
This is the new version of the bug, change these two places, can be solved

**Comment by cmastro** [comment]
@takatost thanks for taking a look at this, but once I pull the fix, the issue still there.

**Comment by cmastro** [comment]
@takatost thanks for taking a look at this, but once I pull the fix, the issue still there.

**Comment by tandangfei** [comment]
![image](https://github.com/langgenius/dify/assets/22535127/25ec2747-93ae-4228-9429-adb0bf3d2266)

Finally, the reason was found, because there was a run on the redis queue, and making a judgment could completely solve the problem

**Comment by takatost** [comment]
> ![image](https://user-images.githubusercontent.com/22535127/265639517-2417b3d5-47dd-46d6-a9ee-64d1294fceab.png)
> 
> Finally, the reason was found, because there was a run on the redis queue, and making a judgment could completely solve the problem

**Agent thought**'s answer only has a value in the final answer of last iteration, which is expected and different from the answer of the **message**.
