### ISSUE TITLE
event: ping

### ISSUE THREAD

**Issue by WThirteen** [langgenius/dify#9813]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

* get response, split using the split method as described in the documentation
```
res = response.text.split('data:')
res1 =res[1:]
```
* Receive a response in JSON format.
```
import json
for chunk in res1:
    print(chunk)
    chunk_json = json.loads(chunk) 
    if chunk_json['event'] == 'message':
        print(chunk_json['answer'])
        delta = chunk_json['answer']
```
### There is an error message appearing.
* Scanning in bulk reveals that one of them has an extra character at the end.
![{16B6E83B-2EA5-46B4-99DB-448A2E9279D4}](https://github.com/user-attachments/assets/63cbb0b6-904a-419c-9a67-117f76b6c4e5)

### ✔️ Expected Behavior

* Get a ChunkChatCompletionResponse object flow sequence.

### ❌ Actual Behavior

* There are additional characters in it

**Comment by crazywoola** [comment]
It seems the code that handle the stream is wrong, the `event: ping` is an expected behavior.

**Comment by WThirteen** [comment]
> It seems the code that handle the stream is wrong, the `event: ping` is an expected behavior.

Okay, thank you for your response.
have a nice day

**Comment by axolo** [comment]
```js
fetchEventSource('/chat-messages', {
  method: 'POST',
  onmessage: e => {
    try {
      const data = JSON.parse(e.data)
      console.log(data)
    } catch {
       // do nothing for event: ping
    }
  }
}
```
