### ISSUE TITLE
HTTP request failes when file is not upload in the multipar/form-data

### ISSUE THREAD

**Issue by muckthaa-ss** [langgenius/dify#9817]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

when i use multipart/form-data in http block while calling Api
the associated value in the form-data are not sent when the file is not upload 
vice versa is working fine when the file is uploaded then the associated form data value are sent 
but in the source code file of Api is not expecting the file 

**source code of post Api of http block**

```
@app.route('/askform', methods=['POST'])
def askform():
    print("formdata",request.form)
    print("headers",request.headers)
    collection_id = request.form.get('collection_id')
    question = request.form.get('question')
    print("collection_id------------------",collection_id)
    print("question:---------------------",question)
    if not collection_id or not question:
        return jsonify({"error": "Both collection_id and question are required."}), 400
    else:
        return jsonify({"message": "Form data received successfully"}), 200 
```

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/ff4575fa-d5ea-4b54-8c1f-e60d0cae11bb)
![image](https://github.com/user-attachments/assets/b5583b1a-8498-4dc0-9e84-62f9dcfaca42)

### ❌ Actual Behavior

now file is not uploaded 
![image](https://github.com/user-attachments/assets/6795b6dc-786e-41ee-bc9b-fff9d4062039)
![image](https://github.com/user-attachments/assets/28251ffe-abd2-43b0-8814-1b82cbf9613d)

**Comment by muckthaa-ss** [comment]
@dosu 
![image](https://github.com/user-attachments/assets/b6b72480-ae3f-467c-bb0d-574b025168b2)
in above images i have attached file block in form data and mentioned the content-type eventhough is not uploaded but the file key is present in the form data it works 
![image](https://github.com/user-attachments/assets/4e6603d1-fccd-433e-80e0-8d6c1392725a)
in the above i just remove the file key from the form data but not upload the file it not working properly 
i have the server side and its work very fine in the postman too

**Comment by muckthaa-ss** [comment]
@dosu but from the dify side When the file key is present in the multipart/form-data request but no file is uploaded, Dify's server-side code is not  raise a NoFileUploadedError in screen and the workflow works perfectly

**Comment by crazywoola** [comment]
I guess you are going to send the second message in the same conversation right?

https://docs.dify.ai/guides/workflow/node/doc-extractor

Either you store the result of the first upload or you could use a if/else node to distinguish if there is no file at all.
