### ISSUE TITLE
Error providing an image

### ISSUE THREAD

**Issue by 74sistemas** [langgenius/dify#9818]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4d915126-492c-4e22-92e2-36f565865fa4)

### ❌ Actual Behavior

answer-placeholder-1729802138035 is not a valid uuid.
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by crazywoola** [comment]
Please provide the DSL as well/

**Comment by Erincrying** [comment]
I have encountered the same problem as you, have you solved it？

**Comment by boboboss** [comment]
Also ask, send pictures error:  The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.

**Comment by lokiwizard** [comment]
I encountered this problem too，the error log：
self.created_by_role = created_by_role.value
AttributeError: 'str' object has no attribute 'value'

**Comment by lokiwizard** [comment]
I try to remove the dify-api-0.10.1 image and pull the image again, this problem can be solved.

**Comment by 74sistemas** [comment]
> Please provide the DSL as well.

[https://drive.google.com/file/d/1CXYuIdIzY95ZYQgxiHHQzThBUnKSf-Qw/view?usp=sharing](url)

**Comment by 74sistemas** [comment]
> Please provide the DSL as well.

`app:
  description: teste
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: teste
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: true
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 1
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: start
        targetType: llm
      id: 1729801617106-llm
      source: '1729801617106'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: answer
      id: llm-answer
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
    nodes:
    - data:
        desc: ''
        selected: false
        title: Iniciar
        type: start
        variables: []
      height: 53
      id: '1729801617106'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        memory:
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 10
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-4o-mini
          provider: openai
        prompt_template:
        - id: 2a8c3eb1-30d0-4a54-a931-c5844270c921
          role: system
          text: 'sua função é pedi uma imagem do equipamento fotográfico e extrair
            as informações:

            Marca, Modelo, Tipo de equipamento'
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          configs:
            detail: high
            variable_selector:
            - sys
            - files
          enabled: true
      height: 97
      id: llm
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: Resposta
        type: answer
        variables: []
      height: 102
      id: answer
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: 195.60096271748455
      y: 72.02864938709189
      zoom: 0.7663099801038916
`

**Comment by laipz8200** [comment]
Please try removing version 0.10.1 images and pull them again.

**Comment by 74sistemas** [comment]
will wait for a new update considering that it still needs a lot of adjustments. I appreciate your attention.
