### ISSUE TITLE
Json Parse tool can not work to run a expression

### ISSUE THREAD

**Issue by jiusi9** [langgenius/dify#9825]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I input json data to **Json Parse** from http request, and want to extract some data, but it always say **Unexpected character**.

Do not allow to input special strings?
 I had test in jsonpath tool online using the following expression.

`
$..environments[?(@.stage=='staging')]
`

![image](https://github.com/user-attachments/assets/1dfe4279-07c4-47e1-9be8-69c4b7349abb)

![image](https://github.com/user-attachments/assets/b19ad1b8-009b-4859-b0a2-0b4f1771955d)

**Comment by crazywoola** [comment]
Yes, we have fixed a bunch of errors in v0.10.1

**Comment by jiusi9** [comment]
I found root cause.
This tool **json_process** did not import jsonpath_ng.ext.
`/api/core/tools/provider/builtin/json_process/tools/parse.py`


This expression `$..environments[?(@.stage=='staging')]` is a filter extension.

**To use the extensions below you must import from _jsonpath_ng.ext_.**

I have done this test. It worked very well.
![image](https://github.com/user-attachments/assets/fe22152c-d09a-4219-83bf-2ad9ea2e5428)

**Comment by jiusi9** [comment]
So, Would support this feature and import jsonpath_ng.ext module?
