### ISSUE TITLE
The previous application encountered various variable errors after upgrading to version 0.10.0.

### ISSUE THREAD

**Issue by Moiyu1998** [langgenius/dify#9826]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The workflow application that was working fine in the previous version encountered errors with most variables after updating to version 0.10.0.

<img width="1385" alt="lQLPJxdbxn4UecfMxM0K0rByKCqfh4X0VQcA9i-UWK4A_2770_196" src="https://github.com/user-attachments/assets/09907d97-8e87-48af-b370-8e304c45c5ee">

<img width="380" alt="ca1173b379e35b6fffb70727b41f51c0" src="https://github.com/user-attachments/assets/c439965a-a418-43dc-8972-f86fe8b9f413">

**Comment by Moiyu1998** [comment]
The error occurs in one personal space but not in another. Why is that?

**Comment by crazywoola** [comment]
Please upgrade to v0.10.1, this version should resolve those errors.
