### ISSUE TITLE
Chat with Agent using Knowledge(images in docx), but some images don't display correctly on the page

### ISSUE THREAD

**Issue by yhchang520** [langgenius/dify#9829]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1、upload files in knowledge(with images)
![image](https://github.com/user-attachments/assets/47098140-fcce-4e3a-8713-6760e1a6944b)
![image](https://github.com/user-attachments/assets/065161cd-0f4a-4839-a5e1-311a6fcd9df5)

2、create an agent with context
![image](https://github.com/user-attachments/assets/ff179695-b130-4ad1-b815-da799d2ed9e0)

3、chat with the agent, but some images display incorrectly
![image](https://github.com/user-attachments/assets/383713d2-4212-4e9a-a353-114359354348)
![image](https://github.com/user-attachments/assets/13d20068-1a67-4a55-8d48-acae005b6de1)

### ✔️ Expected Behavior

When I chat with the agent, all the images from the knowledge can display correctly

### ❌ Actual Behavior

 some images display incorrectly
![image](https://github.com/user-attachments/assets/13d20068-1a67-4a55-8d48-acae005b6de1)

**Comment by yhchang520** [comment]
All the images are extracted and saved correctly from DOCX files. The question is: the earlier images display correctly, but the later images do not.

**Comment by crazywoola** [comment]
> All the images are extracted and saved correctly from DOCX files. The question is: the earlier images display correctly, but the later images do not.

Which version can display it correctly. Also is this url accessible?
