### ISSUE TITLE
Why does the knowledge base always show "in queue"?

### ISSUE THREAD

**Issue by Han-Huaqiao** [langgenius/dify#9830]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

So far (all times are Beijing time), the files in the knowledge base have been shown as "in queue"：
![2024-10-25 11-01-39屏幕截图](https://github.com/user-attachments/assets/3ac05a48-5ca7-41b7-bce4-bc577d0d9444)

### ✔️ Expected Behavior

Complete the construction of the knowledge base normally

### ❌ Actual Behavior

The files in the knowledge base have been shown as "in queue"

**Comment by Han-Huaqiao** [comment]
The model I use is the model deployed locally in Ollama, and when I check it through Ollama PS, the Dify knowledge base has not called the embedded model.@dosu

**Comment by crazywoola** [comment]
Check the container logs.
