### ISSUE TITLE
Invalid variables not validated

### ISSUE THREAD

**Issue by linfey90** [langgenius/dify#9838]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When we have two parallel lines, the reference variable of one branch is on the other branch. Since the backend is in the same variable pool and invalid variables can still run, it can still output values, which can lead to unexpected errors.
![image](https://github.com/user-attachments/assets/cc590609-3aac-483c-b6f7-8528e10b886f)

### ✔️ Expected Behavior

Cannot debug or run errors.

### ❌ Actual Behavior

Everything is normal now

**Comment by laipz8200** [comment]
Could you share this DSL? Every node has a unique ID that is used in the backend.

**Comment by laipz8200** [comment]
Thank you for the report. This is a known issue; currently, our canvas cannot detect this situation.
