### ISSUE TITLE
Data loss caused by redeployment of Docker

### ISSUE THREAD

**Issue by Erincrying** [langgenius/dify#9840]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1.Deploy two sets of services according to the official documentation, and then pull the code for v0.10.0
2. Restart Docker and execute the following command
docker-compose -f mysql-docker-compose.yaml up -d
docker-compose -f mysql-docker-compose.yaml down
3.flask db upgrade
4.Reinstall front-end and back-end dependency packages
5. When starting the front-end and back-end services, change the port number of the second system
6. Some data has been lost.

**Comment by crazywoola** [comment]
We do not have `mysql-docker-compose.yaml `.

**Comment by Erincrying** [comment]
> We do not have `mysql-docker-compose.yaml `. And we have no idea what's inside, if you are using the source code, please try to figure it out yourself. We do not support custom database yet. If you would like to have technical support on this, please reach out to [business@dify.ai](mailto:business@dify.ai).

docker/docker-compose.middleware.yaml
This is the file, I only changed the occupied port number, nothing else was changed
