### ISSUE TITLE
Workflow parallel httpRequest error

### ISSUE THREAD

**Issue by itiwant** [langgenius/dify#9841]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

![error_dify](https://github.com/user-attachments/assets/f9ee9fc3-4156-48ec-87bd-cbdd6793d613)

I run on the old version 0.9.1/0.8.3 it runs well, but on version 0.10.1 it runs with errors. And it is much slower than the 2 old versions, it feels like it is not parallel.

**Comment by Yi-Lyu** [comment]
Also upgraded to v0.10.1 and encountered a similar problem, help.

**Comment by crazywoola** [comment]
Please upgrade to v0.10.2
