### ISSUE TITLE
Run failed: Variable #xxx not found in variable pool

### ISSUE THREAD

**Issue by huu3301** [langgenius/dify#9844]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Set an optional input parameter.
![image](https://github.com/user-attachments/assets/d176b9ca-900d-43a4-b51c-644f9fd81107)
2. Add a IF/ELSE block.
3. Add a LLM Block for the if branch.
4. Add a variable aggregator block  for the LLM Block and else branch.
![image](https://github.com/user-attachments/assets/6cecc5a5-d982-471f-b51a-d2548d679b37)
5. Add a template block.
![image](https://github.com/user-attachments/assets/85493830-ad6b-4da4-9dd4-5f3a0788a052)
6.Add a LLM block and an ANSWER block.
![image](https://github.com/user-attachments/assets/30563902-78f7-4f5e-aa9b-05e89973d5c2)

This is the YAML file：
[test.txt](https://github.com/user-attachments/files/17516998/test.txt)

### ✔️ Expected Behavior

Can run normally.
Additionally, can I directly use the output of variable aggregator in the LLM prompt instead of using a template block?

### ❌ Actual Behavior

Running error in v0.10.1：
![企业微信截图_17298359658659](https://github.com/user-attachments/assets/406f8f34-60ba-43d2-8b99-a0da264175b4)

but running normally in v0.9.2：
![企业微信截图_17298358034736](https://github.com/user-attachments/assets/dd516c9a-dcba-49de-861b-a22583741393)

**Comment by laipz8200** [comment]
This is expected behavior. The VariableAggregator is designed to select the truly completed branch among several preceding ones. In your example, VLM wasn’t executed, and the subsequent Template tried to use the output of VLM… It couldn’t access this value, which led to an error.

> but running normally in v0.9.2:

That might have been unintended behavior.

> Additionally, can I directly use the output of VariableAggregator in the LLM prompt instead of using a template block?

You can use all variables of types string, number, array[string], and array[number] in the LLM.

**Comment by J2ephyr** [comment]
Similar issues were encountered in version 0.10.2.
<img width="1459" alt="image" src="https://github.com/user-attachments/assets/3ec57c05-4f94-4d9c-b888-05b146218c00">
[dsl.txt](https://github.com/user-attachments/files/17552176/dsl.txt)

**Comment by laipz8200** [comment]
> Similar issues were encountered in version 0.10.2. <img alt="image" width="1459" src="https://private-user-images.githubusercontent.com/21029973/380995748-3ec57c05-4f94-4d9c-b888-05b146218c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODIxOTMsIm5iZiI6MTczMDE4MTg5MywicGF0aCI6Ii8yMTAyOTk3My8zODA5OTU3NDgtM2VjNTdjMDUtNGY5NC00ZDljLWI4ODgtMDViMTQ2MjE4YzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA2MDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMGUyZGFjMTYyMDgyYzFlZjg4ZTI4NTY4NWM4ZDUxNmVmNjk4N2Y1MDRmZDU0YjA3MzUxNmFiZTg1YmYxNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mKb5agRJ_3KoL0VIaNFLw2rcDWJJwEmdwtUCTCpTZOc"> [dsl.txt](https://github.com/user-attachments/files/17552176/dsl.txt)

Please check if the node where the variable you referenced is actually executed. If it hasn’t been, it’s best to use an aggregator to adjust your workflow.

**Comment by LMJOK** [comment]
Variable #1749624841670.text# not found，请问这个怎么解决？
