### ISSUE TITLE
Create_by_Text doesn't work anymore since 0.10.0

### ISSUE THREAD

**Issue by FBR65** [langgenius/dify#9848]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

curl --location --request POST 'http://10.84.0.7/v1/datasets/ae661cd9-c1b4-4b9b-938a-80413a9a496a/document/create_by_text' \
--header 'Authorization: Bearer dataset-kQmCGzpSzhvg8R3kGW7XPmNK' \
--header 'Content-Type: application/json' \
--data-raw '{"name": "text","text": "text","indexing_technique": "high_quality","process_rule": {"mode": "automatic"}}'

### ✔️ Expected Behavior

Create a Document in the Knowledge

### ❌ Actual Behavior

{"message": "Internal Server Error", "code": "unknown"}

**Comment by FBR65** [comment]
There are no local images used. The redeploy  with 0.10.1 was made 2 h ago and it still doesn't work.

**Comment by FBR65** [comment]
The files are uploaded to uploaded_files, but the error still exist

**Comment by crazywoola** [comment]
Please provide the error logs of the api container as well.

**Comment by FBR65** [comment]
api-1  | Running migrations
api-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml
api-1  | /app/api/.venv/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
api-1  |   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
api-1  | Preparing database migration...
api-1  | Database migration skipped
api-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
api-1  | sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml
api-1  | /app/api/.venv/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
api-1  |   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
api-1  | [2024-10-25 06:02:57 +0000] [1] [INFO] Starting gunicorn 22.0.0
api-1  | [2024-10-25 06:02:57 +0000] [1] [INFO] Listening at: http://0.0.0.0:5001 (1)
api-1  | [2024-10-25 06:02:57 +0000] [1] [INFO] Using worker: gevent
api-1  | [2024-10-25 06:02:57 +0000] [134] [INFO] Booting worker with pid: 134
api-1  | [2024-10-25 06:02:57 +0000] [135] [INFO] Booting worker with pid: 135
api-1  | [2024-10-25 06:02:57 +0000] [136] [INFO] Booting worker with pid: 136
api-1  | [2024-10-25 06:02:57 +0000] [137] [INFO] Booting worker with pid: 137
api-1  | [2024-10-25 06:02:57 +0000] [138] [INFO] Booting worker with pid: 138
api-1  | [2024-10-25 06:02:57 +0000] [139] [INFO] Booting worker with pid: 139
api-1  | [2024-10-25 06:02:57 +0000] [140] [INFO] Booting worker with pid: 140
api-1  | [2024-10-25 06:02:57 +0000] [141] [INFO] Booting worker with pid: 141
api-1  | [2024-10-25 06:02:58 +0000] [142] [INFO] Booting worker with pid: 142
api-1  | [2024-10-25 06:02:58 +0000] [143] [INFO] Booting worker with pid: 143
api-1  | [2024-10-25 06:02:58 +0000] [144] [INFO] Booting worker with pid: 144
api-1  | [2024-10-25 06:02:58 +0000] [145] [INFO] Booting worker with pid: 145
api-1  | [2024-10-25 06:02:58 +0000] [146] [INFO] Booting worker with pid: 146
api-1  | [2024-10-25 06:02:58 +0000] [147] [INFO] Booting worker with pid: 147
api-1  | [2024-10-25 06:02:58 +0000] [148] [INFO] Booting worker with pid: 148
api-1  | [2024-10-25 06:02:58 +0000] [149] [INFO] Booting worker with pid: 149
api-1  | [2024-10-25 06:02:58 +0000] [150] [INFO] Booting worker with pid: 150
api-1  | [2024-10-25 06:02:58 +0000] [151] [INFO] Booting worker with pid: 151
api-1  | [2024-10-25 06:02:58 +0000] [152] [INFO] Booting worker with pid: 152
api-1  | [2024-10-25 06:02:58 +0000] [153] [INFO] Booting worker with pid: 153
api-1  | [2024-10-25 06:02:58 +0000] [154] [INFO] Booting worker with pid: 154
api-1  | [2024-10-25 06:02:58 +0000] [155] [INFO] Booting worker with pid: 155
api-1  | [2024-10-25 06:02:58 +0000] [156] [INFO] Booting worker with pid: 156
api-1  | [2024-10-25 06:02:59 +0000] [157] [INFO] Booting worker with pid: 157
api-1  | 2024-10-25 06:05:13,821.821 ERROR [Dummy-1] [app.py:838] - Exception on /v1/datasets/13effc06-1bc7-48d6-8bb4-01255b73b2ed/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:06:45,384.384 ERROR [Dummy-1] [app.py:838] - Exception on /v1/datasets/13effc06-1bc7-48d6-8bb4-01255b73b2ed/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:12:41,448.448 ERROR [Dummy-2] [app.py:838] - Exception on /v1/datasets/13effc06-1bc7-48d6-8bb4-01255b73b2ed/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:13:29,215.215 INFO [Dummy-1] [_client.py:1038] - HTTP Request: POST http://10.84.0.10:8100/tokenize "HTTP/1.1 200 OK"
api-1  | 2024-10-25 06:16:46,261.261 ERROR [Dummy-3] [app.py:838] - Exception on /v1/datasets/ae661cd9-c1b4-4b9b-938a-80413a9a496a/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:34:16,434.434 ERROR [Dummy-4] [app.py:838] - Exception on /v1/datasets/ae661cd9-c1b4-4b9b-938a-80413a9a496a/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:54:53,636.636 ERROR [Dummy-5] [app.py:838] - Exception on /v1/datasets/ae661cd9-c1b4-4b9b-938a-80413a9a496a/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:55:16,227.227 ERROR [Dummy-6] [app.py:838] - Exception on /v1/datasets/ae661cd9-c1b4-4b9b-938a-80413a9a496a/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:59:06,664.664 ERROR [Dummy-1] [app.py:838] - Exception on /v1/datasets/ae661cd9-c1b4-4b9b-938a-80413a9a496a/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'
api-1  | 2024-10-25 06:59:57,142.142 ERROR [Dummy-2] [app.py:838] - Exception on /v1/datasets/ae661cd9-c1b4-4b9b-938a-80413a9a496a/document/create_by_text [POST]
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
api-1  |     rv = self.dispatch_request()
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1  |     resp = resource(*args, **kwargs)
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
api-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1  |   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1  |     resp = meth(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 163, in decorated
api-1  |     return view(api_token.tenant_id, *args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/wraps.py", line 109, in decorated
api-1  |     return view(*args, **kwargs)
api-1  |   File "/app/api/controllers/service_api/dataset/document.py", line 58, in post
api-1  |     upload_file = FileService.upload_text(args.get("text"), args.get("name"))
api-1  |   File "/app/api/services/file_service.py", line 112, in upload_text
api-1  |     upload_file = UploadFile(
api-1  | TypeError: __init__() missing 1 required keyword-only argument: 'created_by_role'

**Comment by crazywoola** [comment]
This is resolved in v0.10.1, but you need to remove the old v0.10.1 containers and pull it again.

**Comment by FBR65** [comment]
Thanks, it was of cause an layer 8 Problem. I didn't switched everything to 0.10.1. Sorry for opening the issue.
