### ISSUE TITLE
Custom file cannot be determined whether it is empty

### ISSUE THREAD

**Issue by chaojiniubi** [langgenius/dify#9854]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I configure a file at the first node, it cannot be determined whether the file exists or not. It can only be judged by file.name, file.size, etc., but the file is not required
![file2](https://github.com/user-attachments/assets/f0d6692d-9ed0-44b0-be1a-3ce132dcff23)

**Comment by crazywoola** [comment]
This should be fixed in #9699
It will be replaced with 
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/4a74ffc3-b88c-46f5-85ec-fc51ca4c2cd8">
