### ISSUE TITLE
workflow api how to upload pdf？No method is found in the document.

### ISSUE THREAD

**Issue by llama-factory** [langgenius/dify#9857]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

This issue was closed before it was resolved：https://github.com/langgenius/dify/issues/9839

**Comment by crazywoola** [comment]
For questions, please use discussion instead.
For docs, please refer this https://github.com/langgenius/dify/pull/9832 later.
