### ISSUE TITLE
Can't pass number to workflow tool

### ISSUE THREAD

**Issue by JokerQyou** [langgenius/dify#9861]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a workflow, add an input variable of number type, the publish this workflow as a tool.
2. Create another workflow, also add an input variable of number type, then add a tool node, select previous workflow as tool, in tool input variable section, pass the input number to this tool.
3. Run the second workflow with a random number.

Here is these two workflows (file extension changed to `.txt` due to GitHub issue restriction): `test-tool` is the tool workflow, `test` is the workflow to reproduce this bug.

[test.yml.txt](https://github.com/user-attachments/files/17519392/test.yml.txt)
[test-tool.yml.txt](https://github.com/user-attachments/files/17519393/test-tool.yml.txt)

Screenshot of variable passing to tool workflow:
![image](https://github.com/user-attachments/assets/ccb479e9-dce9-4faf-b8e1-5728fcb1e611)

Screenshot of type error during workflow execution:
![image](https://github.com/user-attachments/assets/0c82a270-c4d6-4eea-a024-33239ddb1a8e)

The error text is:
```
1 validation error for ToolNodeData tool_parameters.i.type Value error, value must be a string, int, float, or bool [type=value_error, input_value='constant', input_type=str] For further information visit https://errors.pydantic.dev/2.9/v/value_error
```

I checked multiple times that this is not due to my app code bug like mismatched variable type configured on the UI or something like that. This seems to be a dify bug.

[test.yml.txt](https://github.com/user-attachments/files/17519392/test.yml.txt)
[test-tool.yml.txt](https://github.com/user-attachments/files/17519393/test-tool.yml.txt)

### ✔️ Expected Behavior

The `test` workflow runs fine.

### ❌ Actual Behavior

Errors out with `1 validation error for ToolNodeData tool_parameters.i.type Value error, value must be a string, int, float, or bool [type=value_error, input_value='constant', input_type=str]`.

**Comment by JokerQyou** [comment]
Of course I passed it as number. You can import the workflows I uploaded (in the first comment) to check it yourself. Also I'm on a docker installation so there is no easy way to tweak dify source code, so can't verify what you suggested.

**Comment by laipz8200** [comment]
This issue was caused by a validation error from a long time ago. We will fix it in the next version, and at that time, you will need to re-add the tool node.

**Comment by JokerQyou** [comment]
> This issue was caused by a validation error from a long time ago. We will fix it in the next version, and at that time, you will need to re-add the tool node.

By `re-add the tool node` do you mean the tool node in the caller workflow or the nodes of the workflow being called as tool?

**Comment by laipz8200** [comment]
@JokerQyou You only need to modify the caller.

**Comment by KevinZhang19870314** [comment]
@laipz8200 I'm encountering the same error when using the Feishu-related tools. I'd like to know in which version this issue will be fixed. Thanks!
![image](https://github.com/user-attachments/assets/368f1897-811f-4d0b-99ba-ce591a800356)

**Comment by laipz8200** [comment]
> @laipz8200 I'm encountering the same error when using the Feishu-related tools. I'd like to know in which version this issue will be fixed. Thanks! ![image](https://private-user-images.githubusercontent.com/13794286/381842871-368f1897-811f-4d0b-99ba-ce591a800356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTUzNzIsIm5iZiI6MTczMDM1NTA3MiwicGF0aCI6Ii8xMzc5NDI4Ni8zODE4NDI4NzEtMzY4ZjE4OTctODExZi00ZDBiLTk5YmEtY2U1OTFhODAwMzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA2MTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NmJjYzc0YzJhZTQwNzBjMjAyZGU0ZTA4ZDBhMjYwZGU0NjUzMGVjNmY0MzM3ZjIxYmJiMmQ1NGM3OWVhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Enn9Bhxc9sjUa59uEEGP2zv5cWIdU3vFuqfptJ5od1M)

v0.10.2, remember to re-add your tools.
