### ISSUE TITLE
About Dify Node Style Location For User Community Building

### ISSUE THREAD

**Issue by green-dalii** [langgenius/dify#9863]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hi Dify official,

I am a loyal user and passionate enthusiast of Dify. I would like to request the code location information for the node graph style files from Dify for community building.

I have created an open-source community for Dify users and enthusiasts to share and host Workflows: [Diflowy](https://diflowy.greenerai.top/) , all website code is open-source at [Github](https://github.com/green-dalii/diflowy), where users can upload, share, search, and host their own Workflow files. 

The community website has a Workflow node preview feature. Since I could not find the file information regarding the ReactFlow node style definition in the Dify open-source code, the current style is self-customized by myself. I would like to maintain consistency with the official Dify style. Could Dify provide the specific location of the official node style code file? Thank you!

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
All nodes related stuffs are located here

https://github.com/langgenius/dify/blob/c28d709d7f303809e8c392e9176a579d8aecc2d4/web/app/components/workflow/nodes/index.tsx

**Comment by green-dalii** [comment]
Thanks! Get it!
