### ISSUE TITLE
[Model Provider] Support both domestic and international site of Tongyi models

### ISSUE THREAD

**Issue by native98Mu** [langgenius/dify#9867]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Alibaba Cloud Tongyi model has different API Base for domestic and international sites. 
Currently, Dify does not provide URL configuration like OpenAI or Anthropic when configuring the Tongyi model provider.
![iShot_2024-10-25_17 14 29](https://github.com/user-attachments/assets/660c66bd-df2e-409a-ad5a-a2b48c51b56f)

### ✔️ Expected Behavior

Dify could provide URL configuration like OpenAI or Anthropic when configuring the Tongyi model provider. 
So Dify can support both domestic and international site of Tongyi models.

### ❌ Actual Behavior

Users cannot call Tongyi on Dify using the API key of the international site

**Comment by crazywoola** [comment]
You could add links according to `en_US` and `zh_Hans`

https://github.com/langgenius/dify/blob/5c76131d3dc1e4a5719cc828ba5a485e97024d90/api/core/model_runtime/model_providers/tongyi/tongyi.yaml#L16
