### ISSUE TITLE
docker compose up api service is stuck

### ISSUE THREAD

**Issue by prosscode** [langgenius/dify#9874]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

run docker compose up, cannot access the api service and find that the api service has not been started through the log as follows

Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml
findfont: Font family ['PingFang SC'] not found. Falling back to DejaVu Sans.
findfont: Font family ['SimHei'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Microsoft YaHei'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STSong'] not found. Falling back to DejaVu Sans.
findfont: Font family ['SimSun'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial Unicode MS'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Noto Sans CJK SC'] not found. Falling back to DejaVu Sans.
/app/api/.venv/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
  
 

### ✔️ Expected Behavior

Expect to output:
...
[2024-10-25 09:58:30 +0000] [1] [INFO] Starting gunicorn 22.0.0
[2024-10-25 09:58:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:5001 (1)
[2024-10-25 09:58:30 +0000] [1] [INFO] Using worker: gevent
[2024-10-25 09:58:30 +0000] [101] [INFO] Booting worker with pid: 101

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9755
