### ISSUE TITLE
can't call all LLMs: error code 401

### ISSUE THREAD

**Issue by Megadeth9919** [langgenius/dify#9877]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

## Yesterday I was able to use dify normally, but overnight all the LLMs couldn't be called
![image](https://github.com/user-attachments/assets/75aaf5f7-aa21-41d4-8f9a-ceeae33cb8b2)
![image](https://github.com/user-attachments/assets/8e56ffe8-eae6-442d-86b0-dd6a97c02a32)

**Comment by shisaru292** [comment]
@crazywoola #10047 Please have a look. I think these are the same issue.
