### ISSUE TITLE
In udify.app, can't display external images because of CSP

### ISSUE THREAD

**Issue by andrebalza** [langgenius/dify#9878]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

	1.	Have the udify.app load an image from any external source (ex. loaded from markdown).
	2.	Attempt to load the image, and observe the CSP error in the browser console.

### ✔️ Expected Behavior

External images should load without CSP violations, allowing for integration of external image sources as needed.

### ❌ Actual Behavior

External images are currently blocked by the CSP, preventing them from loading.
Browser console error message: 
Refused to load the image 'https://omitted.omitted.fi/Cover/Show?id=kyyti.639346&index=0&size=large' because it violates the following Content Security Policy directive: "img-src 'self' data: mediastream: blob: filesystem: 'nonce-MDdlNWNlZjYtMzg0MS00ZjI0LTk0ZDAtNWZiNzM5ZjQwNmM3' *.dify.ai *.udify.app udify.app *.cloudflareinsights.com *.sentry.io http://localhost:* http://127.0.0.1:* https://analytics.google.com googletagmanager.com *.googletagmanager.com https://www.google-analytics.com https://api.github.com".

**Comment by lzfxxx** [comment]
I've developed a solution for this CSP issue - a simple Image Downloader Plugin for Dify.

This plugin solves the problem by downloading images from external domains and returning them as blobs, which bypasses the CSP restrictions in udify.app.

Key features:
- Downloads images from any public URL
- Automatically detects image type and sets correct MIME types
- Simple to use with just one parameter (image_url)
- Works with common image formats (JPG, PNG, GIF, BMP, WebP, etc.)

For a practical workflow, you can use a Python runtime node to extract image URLs from AI-generated markdown content, then pass those URLs to this plugin to display the images properly.

<img width="867" alt="Image" src="https://github.com/user-attachments/assets/02b1563a-a27b-409a-900f-8b0c143fd4c8" />

Here's the source code if you're interested: https://github.com/lzfxxx/image-downloader

Hope this helps others facing the same issue!
