### ISSUE TITLE
Tracing app performace setting keep loading after the server address of langfuse changed

### ISSUE THREAD

**Issue by fdb02983rhy** [langgenius/dify#9883]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Using a self hosted langfuse, set up in dify via http in 'Tracing app performance'.
Changed the ip address of langfuse server.
![image](https://github.com/user-attachments/assets/f142ae90-25b8-4c5b-acf4-128bbfada0cd)

### ✔️ Expected Behavior

The setting can be loaded

### ❌ Actual Behavior

Keep loading

**Comment by ZhouhaoJiang** [comment]
check if your self-deployed langfuse is available

**Comment by fdb02983rhy** [comment]
> check if your self-deployed langfuse is available

It works. What I am trying to do is change the current langfuse setting from old address to the new one in dify. However, the UI keeps loading so I am not able to do that.

**Comment by ZhouhaoJiang** [comment]
This problem has been fixed in  #8361

**Comment by fdb02983rhy** [comment]
The fix doesnt works on me, could you please advice me how can I modify the configuration?

**Comment by ZhouhaoJiang** [comment]
I recommend two methods, you can choose either one
1. Enter the database, look for the `trace_app_config` table, delete the record, and then look for the `apps` table to find the `tracing` field to delete
![CleanShot 2024-10-28 at 11 26 44@2x](https://github.com/user-attachments/assets/71cfbc12-8dd7-4562-a968-00ea78a1cc1b)
2. Re-pull the image and re-build the service, but pay attention to the database backup

**Comment by fdb02983rhy** [comment]
Thank you!
