### ISSUE TITLE
What is this error message?

### ISSUE THREAD

**Issue by ottopan** [langgenius/dify#9885]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

wrokflow:https://framerusercontent.com/assets/CP8RAHx05qlIt1CValGTCaLj9g.txt
Every time it runs to this node, such an error occurs, making it difficult to read and understand what the error is.
![image](https://github.com/user-attachments/assets/94a9b205-e63e-4c00-8678-b64b0f8eb230)

**Comment by crazywoola** [comment]
It seems the text is exceed the block's length. Please check the env vars.
