### ISSUE TITLE
question classifier doesn't work with anthropic model(bedrock)

### ISSUE THREAD

**Issue by ybalbert001** [langgenius/dify#9887]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

use claude3 haiku as question classifier model
<img width="869" alt="Screenshot 2024-10-26 at 13 12 38" src="https://github.com/user-attachments/assets/516f761d-68b6-4843-9ce7-1bc138e24739">

### ✔️ Expected Behavior

Don't throw error when using question classifier

### ❌ Actual Behavior

throw error

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/9764
