### ISSUE TITLE
 Android phone, recognition failure often occurs and no content is recognized

### ISSUE THREAD

**Issue by likenamehaojie** [langgenius/dify#9892]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

 Android phone, recognition failure often occurs and no content is recognized

### ✔️ Expected Behavior

 Android phone,

### ❌ Actual Behavior

 Android phone

**Comment by likenamehaojie** [comment]
@crazywoola android phone  voice input bug

**Comment by likenamehaojie** [comment]
第一次可以录音 ,但是当打开第二次或者第三次时 ,没有音波变化,同时也没有录音文件发送

**Comment by likenamehaojie** [comment]
@zxhlyh

**Comment by likenamehaojie** [comment]
只在android设备中发现,这个问题从 0.6版本就开始有了,请问可以解决么?

**Comment by likenamehaojie** [comment]
之前是有一个issus的,不知道什么原因给关闭了,当时以为解决了但是,现在的测试来看并没有解决,@dosu

**Comment by likenamehaojie** [comment]
第二次时完全没有录音文件发生,也没有接收到任何录音数据,所以录音波形也不显示

**Comment by lvxinliang** [comment]
> 第二次时完全没有录音文件发生,也没有接收到任何录音数据,所以录音波形也不显示

和你遇到一样的问题了，你那里解决了吗？可以分享下吗？
