### ISSUE TITLE
Adding a embedding error in ollama

### ISSUE THREAD

**Issue by liberalchang** [langgenius/dify#9895]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.92

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Prompt when adding：An error occurred during credentials validation: 404 Client Error: Not Found for url: http://ip:11434/api/embed，Adding chat models is normal
![image](https://github.com/user-attachments/assets/88d0e7ff-8230-44e1-8a42-cf674eb88deb)
![image](https://github.com/user-attachments/assets/a20d43b9-2f11-40ed-bcd8-ec10c5e4e884)
And I can add it normally in ragflow
![image](https://github.com/user-attachments/assets/ce0f32f0-077d-4ba3-954b-024905405a02)

**Comment by crazywoola** [comment]
Duplicated  https://github.com/langgenius/dify/issues/8184

See their docs https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embedding

`An error occurred during credentials validation: 404 Client Error: Not Found for url: [http://ip:11434/api/embed](http://ip:11434/api/embed)`

**Comment by liberalchang** [comment]
@crazywoola Thanks a lot for your answer.
