### ISSUE TITLE
大佬你好，我有多个chatgpt密钥该如何分配至不同的应用？

### ISSUE THREAD

**Issue by lin-xiaosheng** [langgenius/dify#99]
如题，想将VIP密钥和普通密钥分配至不同的应用

**Comment by GarfieldLucy** [comment]
> 如题，想将VIP密钥和普通密钥分配至不同的应用

hi，目前暂无打算。

**Comment by lin-xiaosheng** [comment]
> > 如题，想将VIP密钥和普通密钥分配至不同的应用
> 
> hi，目前暂无打算。

想二次开发实现这个功能合并进来。您可以为我提供一些在现有代码体系中入手的方向或思路嘛？

**Comment by takatost** [comment]
可能和我们目前产品方向不一致，需要内部讨论后给您回复

**Comment by crazywoola** [comment]
We will reopen this if this is possible.
