### ISSUE TITLE
Max Tokens Parameter Not Functioning Correctly

### ISSUE THREAD

**Issue by MitraSafarinejad** [langgenius/dify#9902]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

max_tokens parameter is supposed to limit the number of tokens processed, it appears not to be functioning correctly. For instance, in the Claude 3.5 Sonnet model, the official maximum token limit is indicated as 8192 tokens. However, I was able to input more than 10,000 tokens without encountering any errors or warnings, and the model responded without enforcing the token limit.  In models like Sonnet or Gemini, we cannot activate the max token parameter, but in OpenAI models, we canAdditionally, could you please provide clarification on what the maximum token limit is and how I can change it?

![image](https://github.com/user-attachments/assets/db87cb70-f3c1-41ec-bffe-2fcbf9aa65a8)
![image](https://github.com/user-attachments/assets/dd4d1fa4-fa64-4ae6-b106-4fe09023a464)

### ✔️ Expected Behavior

The model should show an error message indicating "You have reached the limit of max tokens" and should not provide a response if the token limit is exceeded.

### ❌ Actual Behavior

I was able to input more than 10,000 tokens, and the model operated normally without any indication of exceeding the limit.
![image](https://github.com/user-attachments/assets/cc9f816b-3bef-42f2-a7eb-96aba678ba3b)

**Comment by crazywoola** [comment]
Same here https://github.com/langgenius/dify/issues/9904
You are mixing it with the context size, the claude models have very large context size, typically you can not exceed it without transferring a large file. You can hover it to the question mark to see it's meaning.
