### ISSUE TITLE
GLM-4-Long context supports 1M, why is dify set to 4096?

### ISSUE THREAD

**Issue by jaxonister** [langgenius/dify#9904]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/b7eec16a-391a-4c79-9f57-0339d2e314f7">

### ✔️ Expected Behavior

 context supports 1M

### ❌ Actual Behavior

 context 4096

**Comment by ox01024** [comment]
<img width="983" alt="image" src="https://github.com/user-attachments/assets/409c5bd4-c8bb-4c22-a4c0-2fdc1575bd41">
In fact, it is 1M. Have you encountered any problems in using it? Do you have any evidence?

**Comment by crazywoola** [comment]
Because the context is different from the `output tokens` you thought.
