### ISSUE TITLE
Error DuckDuckGo Image Search

### ISSUE THREAD

**Issue by marioalexandreantunes** [langgenius/dify#9914]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Using DuckDuckGo Image Search got an error and doesn't get any image.

### ✔️ Expected Behavior

5 image files

### ❌ Actual Behavior

```
(psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type uuid: "visiophone-tactile-et-connecte-image-3k-2592x1944-welcomeeye-connect-3-philips-531046-P-59217-133106162_1" LINE 3: WHERE tool_files.id = 'visiophone-tactile-et-connecte-image-... ^ [SQL: SELECT tool_files.id, tool_files.user_id, tool_files.tenant_id, tool_files.conversation_id, tool_files.file_key, tool_files.mimetype, tool_files.original_url, tool_files.name, tool_files.size FROM tool_files WHERE tool_files.id = %(id_1)s::UUID] [parameters: {'id_1': 'visiophone-tactile-et-connecte-image-3k-2592x1944-welcomeeye-connect-3-philips-531046-P-59217-133106162_1'}] (Background on this error at: https://sqlalche.me/e/20/9h9h)
```

**Comment by hjlarry** [comment]
already fix in this PR https://github.com/langgenius/dify/pull/9821
please wait the new version
