### ISSUE TITLE
The filtering conditions for querying records in Feishu's multi-dimensional table tool have become ineffective

### ISSUE THREAD

**Issue by WUXM5** [langgenius/dify#9915]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (I have read and agree to the [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] Please make sure to use English to submit the Issue, otherwise it will be closed. Thank you! :)
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

I have followed the document https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/record-filter-guide to write the filter code: "{"filter": {"conjunction": "and", "conditions": [{"field_name": "是否取卡", "operator": "is", "value": ["否"]}]}}
"The workflow runs normally, but the filter does not execute, and no error appears.
I tested the same code in Feishu's debug platform and it works fine.

```
{
  "app_token": "XXXXX",
  "table_id": "XXXXX",
  "field_names": "[\"文本\",\"类型\"]",
  "view_id": "XXXXXX",
  "table_name": "",
  "sort": "[{\"field_name\":\"文本\",\"desc\":false}]",
  "filter": "{\"filter\": {\"conjunction\": \"and\", \"conditions\": [{\"field_name\": \"是否取卡\", \"operator\": \"is\", \"value\": [\"否\"]}]}}",
  "page_token": ""
}
```
### ✔️ Expected Behavior

Data filtering is effective.

### ❌ Actual Behavior

Data filtering is not effective.

**Comment by zhongAllen** [comment]
when in fill filter JSON in the blank , use case like below( dont beginning with  "filter:" )
----------
{
    "conjunction": "or",
    "conditions": [
      {
        "field_name": "name1",
        "operator": "is",
        "value": [
          "aa"
        ]
      },
      {
        "field_name": "name2",
        "operator": "is",
        "value": [
          "bb"
        ]
      }
    ]
  }
