### ISSUE TITLE
Customize "try for ask"

### ISSUE THREAD

**Issue by liuw518** [langgenius/dify#9916]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

How to customize the content generated in "try for ask."
<img width="385" alt="image" src="https://github.com/user-attachments/assets/9d2d10d2-0775-4861-b74f-5ba3346d049b">

### 2. Additional context or comments

I need to generate recommended questions according to some special requirements. Are there any corresponding APIs or methods for this?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
What are the special requirements?

**Comment by liuw518** [comment]
> What are the special requirements?
> 
> #9916

The requirement is that the content in "Next Suggested Question" is not generated randomly, but rather recommended after retrieving similar questions from the QA knowledge base. If the similarity is low, no recommendation will be made.

**Comment by liuw518** [comment]
> What are the special requirements?
> 
> #9916

The requirement is that the content in "Next Suggested Question" is not generated randomly, but rather recommended after retrieving similar questions from the QA knowledge base. If the similarity is low, no recommendation will be made.

**Comment by crazywoola** [comment]
You can try to return some custom buttons in the answer with any texts you want.

**Comment by liuw518** [comment]
> You can try to return some custom buttons in the answer with any texts you want.

How to return custom buttons？Are there any code examples or explanations?

**Comment by Fudeveloper** [comment]
mark

**Comment by kimdungg** [comment]
Does anyone have an example of how to create a custom render button in the answer?
