### ISSUE TITLE
The  log cannot be displayed complete？

### ISSUE THREAD

**Issue by sfioifs** [langgenius/dify#9920]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

The  log cannot be displayed complete. There are multiple messages in a conversation, but only one message is displayed in the background, and some conversations are not even displayed.What happened?

**Comment by sfioifs** [comment]
@dosu but the latest version is  0.10.1 now

**Comment by crazywoola** [comment]
Duplicated, we will fix it in v0.10.2
