### ISSUE TITLE
When I upload a document via the API, I will get the following error message: File not found

### ISSUE THREAD

**Issue by shengxiagit** [langgenius/dify#9938]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2 - 0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I did not capture any error logs in docker.
I use aliyun-oss as file storage.

### ✔️ Expected Behavior

process document success

### ❌ Actual Behavior

I use aliyun-oss as file storage. 
When I upload a document via the API, I will get the following error message: File not found. 
But When I click the retry button it works fine.

**Comment by shengxiagit** [comment]
> I found a similar closed issue regarding a "File not found" error when uploading a file in a self-hosted Dify setup using Docker. The suggested solution involves ensuring that the local storage path is correctly configured and mounted. Here are the steps you can follow:
> 
> 1. **Set the `STORAGE_TYPE` to `local`:**
>    ```shell
>    export STORAGE_TYPE=local
>    ```
> 2. **Define the `STORAGE_LOCAL_PATH`:**
>    ```shell
>    export STORAGE_LOCAL_PATH=/path/to/local/storage
>    ```
> 3. **Mount the storage directory in your Docker setup:**
>    Ensure that the `/app/api/storage` directory in both containers is mounted to the same local directory. This can be done by adding the following volume configuration in your `docker-compose.yml` file:
>    ```yaml
>    volumes:
>      - /path/to/local/storage:/app/api/storage
>    ```
> 4. **Restart your Docker containers:**
>    ```shell
>    docker-compose down
>    docker-compose up -d
>    ```
> 
> Additionally, ensure that the storage directory has the appropriate permissions and ownership settings to allow the Docker container to read from and write to it. Another user mentioned that attaching a NAS as a PVC solved the problem, indicating that shared storage between containers is necessary [[1]](https://github.com/langgenius/dify/issues/8649).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

But I am using aliyun-oss, not local. And the file has been successfully uploaded to aliyun-oss

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/10069

This one can call it but it doesn't get the file.
