### ISSUE TITLE
Unexpect File Object

### ISSUE THREAD

**Issue by Jalen-Zhong** [langgenius/dify#9948]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I use HTTP node to upload a file by posting my api. I find the "file object" is unexpected by print "file". The file is upload by local file.

- HTTP node define:
![image](https://github.com/user-attachments/assets/7119ebd6-9081-4c03-9d2c-f2cf90ee03af)

- My server define(using "FastAPI"):
![image](https://github.com/user-attachments/assets/381fd941-6449-4c47-80ed-558c509d368e)

- print result:
![image](https://github.com/user-attachments/assets/29eb184b-7866-452a-9b1d-6813fa92c8cf)

### ✔️ Expected Behavior

”filename“ fields should be real file name. But the result display "upload".

**Comment by Jalen-Zhong** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.10.1
> 
> ### Cloud or Self Hosted
> Self Hosted (Docker)
> 
> ### Steps to reproduce
> I use HTTP node to upload a file by posting my api. I find the "file object" is unexpected by print "file"
> 
> * HTTP node define:
>   ![image](https://private-user-images.githubusercontent.com/83332942/380661747-7119ebd6-9081-4c03-9d2c-f2cf90ee03af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDk2NzEsIm5iZiI6MTczMDEwOTM3MSwicGF0aCI6Ii84MzMzMjk0Mi8zODA2NjE3NDctNzExOWViZDYtOTA4MS00YzAzLTlkMmMtZjJjZjkwZWUwM2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNTU5NGJhNWMxM2RjMGJjNDEwZWUyYzg4Y2ZiMzg0MDU0NDFlY2Y2ZjliZGRmNmI5ZjU3OGYwODgwZjMyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RRSJS1jnD2wqMHrnxewoBUEBKNN2BsBENbiAlQx3p-M)
> * My server define(using "FastAPI"):
>   ![image](https://private-user-images.githubusercontent.com/83332942/380661323-381fd941-6449-4c47-80ed-558c509d368e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDk2NzEsIm5iZiI6MTczMDEwOTM3MSwicGF0aCI6Ii84MzMzMjk0Mi8zODA2NjEzMjMtMzgxZmQ5NDEtNjQ0OS00YzQ3LTgwZWQtNTU4YzUwOWQzNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NzNjZGI4NDE1MWVkNmM1MWJmYmZiYzVjN2JiYTBkZTMzY2E4NzY0OWJhZjFjOGI4NDJiMjc1NjM2N2I1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LhTOzmrwL_A4P4I4hlRrfAM7pmNzRDFz-bFqpjMREFQ)
> * print result:
>   ![image](https://private-user-images.githubusercontent.com/83332942/380662558-29eb184b-7866-452a-9b1d-6813fa92c8cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDk2NzEsIm5iZiI6MTczMDEwOTM3MSwicGF0aCI6Ii84MzMzMjk0Mi8zODA2NjI1NTgtMjllYjE4NGItNzg2Ni00NTJhLTliMWQtNjgxM2ZhOTJjOGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OWY1NGE3NmVkNTkwOWFlNzgwMGEwNjIwYWI5NjZkMWU3YmZmOGQ5NDhkMjg3NjJkODJlZDA2ODg1OGJlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KPvkfNH0SG3uXIISVFp4TcVCcwS62BA1DElfv8AnXW8)
> 
> ### ✔️ Expected Behavior
> ”filename“ fields should be real file name. But the result display "upload".
> 
> ### ❌ Actual Behavior
> _No response_

**Comment by crazywoola** [comment]
This should be fixed in v0.11.0
