### ISSUE TITLE
api-token use performance enhance

### ISSUE THREAD

**Issue by aconeshana** [langgenius/dify#9950]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Our team frequently relies on the API for batch usage, but we’ve encountered performance issues. Specifically, the API authentication performs poorly under high QPS cauz too many database io.

I will contribute a pr for this issue.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by aconeshana** [comment]
In a single API call, there are typically 3 or more database IO. This issue is merely proposing a direction for optimization. We aim to contribute further or look forward to more work about it.

**Comment by aconeshana** [comment]
btw, why main thread blocking wait for name? This logic is a disaster when calling the API. We commented this out in production but I want to know why did this. @takatost 
`        if self._conversation_name_generate_thread:
            self._conversation_name_generate_thread.join()`

**Comment by aconeshana** [comment]
btw, Another question is why conversation reload from db when AppRunner#run such as AgentChatAppRunner. 
`
def run(
        self,
        application_generate_entity: AgentChatAppGenerateEntity,
        queue_manager: AppQueueManager,
        conversation: Conversation,
        message: Message,
    ) -> None:
    
        if {ModelFeature.MULTI_TOOL_CALL, ModelFeature.TOOL_CALL}.intersection(model_schema.features or []):
            agent_entity.strategy = AgentEntity.Strategy.FUNCTION_CALLING

        conversation = db.session.query(Conversation).filter(Conversation.id == conversation.id).first()
        message = db.session.query(Message).filter(Message.id == message.id).first()
        db.session.close()
` 


This method receives a conversation parameter, but reads it from the database again before runer_cls is instantiated. However, I think there is almost no non-real-time data in the same conversation, and it is meaningless to change the configuration or concurrency of the ongoing session.There is no consistency issue here, any suggestion? @takatost

**Comment by crazywoola** [comment]
> btw, why main thread blocking wait for name? This logic is a disaster when calling the API. We commented this out in production but I want to know why did this. @takatost ` if self._conversation_name_generate_thread: self._conversation_name_generate_thread.join()`

I checked with @takatost 
> You can decide wether you turn it on or off for generating the conversation name

**Comment by crazywoola** [comment]
Please add my wechat: crazyphage. I can setup a group chat with our backend guys.

**Comment by dajianguo** [comment]
Yes the database is a limit,I have a test，100/s can accomplish。
You can refer to the following, but I haven't tried it for higher performance

postgre:
ALTER SYSTEM SET max_parallel_workers = 60;
ALTER SYSTEM SET shared_buffers='80GB';
ALTER SYSTEM SET log_min_duration_statement = 2000;
ALTER SYSTEM SET max_connections = 10000;
SELECT pg_reload_conf();
SHOW shared_buffers
SHOW max_connections

dify:
SQLALCHEMY_POOL_SIZE: 1000
SQLALCHEMY_POOL_TIMEOUT: 20
SQLALCHEMY_POOL_RECYCLE: 240
SERVER_WORKER_AMOUNT: 12
![image](https://github.com/user-attachments/assets/d4424cae-9e53-4e01-b049-6045d5301acb)

the appache jmeter test
![image](https://github.com/user-attachments/assets/8e7b464d-c842-4258-a945-13dcd63c3fe7)
