### ISSUE TITLE
The API endpoint /conversations does not include an 'update_at' field

### ISSUE THREAD

**Issue by rchlz** [langgenius/dify#9953]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I've found the pr for the 'updated_at' sorting in pull request https://github.com/langgenius/dify/pull/7348. This feature is great, but the response fields do not include 'updated_at'. I need to decide whether to start a new conversation based on the latest 'updated_at'. Is it possible to implement this functionality
also，pr #7348 didn't get the api docs updated

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Feel free to adjust the docs, we are kind of busy these days.
