### ISSUE TITLE
Would it also be possible to return the file name

### ISSUE THREAD

**Issue by 74sistemas** [langgenius/dify#9958]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When the image is shared it is saved directly to the supabase store via S3.
The return has the subdirectory:
"tenant_id": "cc9e8cb8-5153-44e5-ad73-7f9d587ba91f",

Would it also be possible to return the file name?
4aae1ed7-c3c0-4179-955f-35ee91e7b66d.jpg
So at the end of the flow I can use it to save a budget in another table, for example. 
Avoiding in the future to show an image I have to juggle to show a photo.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/154f0c8c-9ea5-4b22-85a3-5258483dbc25">
You can get the file name here.

**Comment by 74sistemas** [comment]
Hi friend, thank you.
But if I refer to the name of the file that is saved in the bank, see:
f53c8bfd-de03-43e4-9e94-135a0ca3beab.jpg

It's different...
