### ISSUE TITLE
 Could you please tell me how to achieve concurrent access for multiple users?

### ISSUE THREAD

**Issue by lihan-hub** [langgenius/dify#9967]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

During the deployment testing process, we found that the workflow stalled when multiple people used it simultaneously. How can we support multiple people using it at the same time?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Each call should be processed individually, maybe you should enlarge your CPU and Memory to suit this situation.

**Comment by lihan-hub** [comment]
> Each call should be processed individually, maybe you should enlarge your CPU and Memory to suit this situation.

I am deployed on the server and after configuring the workflow, I found that it cannot be used by multiple users simultaneously during the process of multiple users using it. What is the reason for this?
