### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by ouzhijian** [langgenius/dify#9968]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Hope to use file types correctly

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/fc2ad5b3-ba7e-4f72-ac74-5207a669b005)
![image](https://github.com/user-attachments/assets/01c7ea40-7a73-4202-afc4-30a46b7f1c22)

### ✔️ Expected Behavior

There is an issue with the file type

### ❌ Actual Behavior

Hope to use file types correctly

**Comment by crazywoola** [comment]
This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).

**Comment by ouzhijian** [comment]
This is the problem,
I only checked the 'Supported file types' in the file upload section of the' Function 'in the workflow for documents
2. Then publish
3. Go to the application and select file upload. Here, only the image type can be selected as the file type. Even if I change to all types and select the document type file, there will still be a file type error when uploading the file

**Comment by ouzhijian** [comment]
﻿
﻿
﻿
This is the problem:
A. I only checked the 'Supported file types' in the file upload section of the' Function 'in the workflow for documents
B. Then publish
C. Go to the application and select file upload. Here, only the image type can be selected as the file type. Even if I change to all types and select the document type file, there will still be a file type error when uploading the file
