### ISSUE TITLE
Object of type File is not JSON serializable

### ISSUE THREAD

**Issue by Jalen-Zhong** [langgenius/dify#9969]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hi developers, 
    Thanks for your nice work! 
    Here is my issuse blow:
    We konw that `openai api swagger` rule only support binary to transfer files. So a common path is transforming `File` object to `binary`, then invoke self-define tools. But the code node is error.

- workflow:
![image](https://github.com/user-attachments/assets/997e4f74-fa9d-48ec-9adf-d78f5c323c41)

- code run and error:
![image](https://github.com/user-attachments/assets/d73bee50-8e3d-410b-a6f1-a34bc8525844)

**Comment by crazywoola** [comment]
Please upgrade to v0.10.2

**Comment by qishibo** [comment]
> ```python
> to_dict
> ```

v0.10.2 still exists this issue

**Comment by qishibo** [comment]
> Please upgrade to v0.10.2

v0.10.2 still exists this issue
![image](https://github.com/user-attachments/assets/caadacd3-1150-49cb-a2d5-db76391e74da)
![image](https://github.com/user-attachments/assets/1d5b39be-4bfe-4fc9-bfaf-77c1165fa49d)

**Comment by qishibo** [comment]
and I want to know if I can create a new file by script? when I try `open("xxx.txt", "w") and write()` I got error like `permission denied` wherever I place the temp file

**Comment by lovingliferwj** [comment]
> > Please upgrade to v0.10.2
> 
> v0.10.2 still exists this issue ![image](https://private-user-images.githubusercontent.com/5136418/382636392-caadacd3-1150-49cb-a2d5-db76391e74da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MTM4NTMsIm5iZiI6MTczNjQxMzU1MywicGF0aCI6Ii81MTM2NDE4LzM4MjYzNjM5Mi1jYWFkYWNkMy0xMTUwLTQ5Y2ItYTJkNS1kYjc2MzkxZTc0ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDlUMDkwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNkNjZiNjQ5NDIwMzAyNmZhNmI3YmY3YmNiN2Y5ZWE1ZjMzMjJkNTQ1MTNhM2JjNmZkMGE4ZjIxNTBkMGFjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-8P6vJavEnXxsgXtJfTbG0_kcTU3leBYkzEIExjNh-E) ![image](https://private-user-images.githubusercontent.com/5136418/382636417-1d5b39be-4bfe-4fc9-bfaf-77c1165fa49d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MTM4NTMsIm5iZiI6MTczNjQxMzU1MywicGF0aCI6Ii81MTM2NDE4LzM4MjYzNjQxNy0xZDViMzliZS00YmZlLTRmYzktYmZhZi03N2MxMTY1ZmE0OWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDlUMDkwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU3MmFiMGM1ZTE0YTg4Yzk5YWNhZGQ1M2FlNGFhM2VlZGJmNTZlNmY3YTljZjMwYTNlZmM5NDQzNTI3YTExYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9BchGn1H-WsBJL0SbsAgbHWjo_7WAlSVKogWqZBN26Y)

I meet the same problem, have you solved this?
