### ISSUE TITLE
Agent Setting

### ISSUE THREAD

**Issue by nameIsNoPublic** [langgenius/dify#9973]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

Create an agent in the studio, click on agent settings, unable to switch to ReAct

**Comment by crazywoola** [comment]
If the LLM is able to use the function call then it won't use ReAct.
ReAct is suit for those LLMs which do not support function call.
