### ISSUE TITLE
Is it necessary to point out it will not support BM25 search if user uses milvus as the vector store?

### ISSUE THREAD

**Issue by applepieiris** [langgenius/dify#9984]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

When I check the backend code I see in the `api\core\rag\datasource\vdb\milvus\milvus_vector.py` file, the fuction `search_by_full_text` is not implemented cause it comments that `# milvus/zilliz doesn't support bm25 search`.
I wonder if I use milvus as the vector store, and in the knowledge retrieval setting, I choose the Full-text search or Hybrid search, Is that mean I cannot search anything under the full-text retrieval? 
In the hybrid search, although I set the 0.3 weight score for the keyword search, because milvus does not support this BM25 algorithm, so it actually does not search the full text. Am I right? If it's the situation, I think the document should point out that feature or give a warning other than just list the vector stores you support.

**Comment by Yawen-1010** [comment]
Yes, Dify knowledge retrieval currently does not support Milvus' bm25. Because its implementation does not quite match our functions. If you need to use full-text search or hybrid search, we recommend that you use other databases.
