### ISSUE TITLE
There exists the chunk whose length is more than the size I set in parameter "maximum chunk length" in custion mode of Chunk setting

### ISSUE THREAD

**Issue by applepieiris** [langgenius/dify#9985]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

When I create an empty knowledge base and upload a PDF file into the knowledge-base, I choose the custom mode in chunk settings like this: 
![image](https://github.com/user-attachments/assets/ee342d6b-8f0f-4d06-851a-d1a4fc792479)
I remain the "maximum chunk length" parameter as the default value: 500 and click the button "confirm and preview"， I see the chunk details on the right side. You can see it exists some chunks that have more than 500 characters? Why?

### ✔️ Expected Behavior

It should make every chunk size smaller than 500 characters

### ❌ Actual Behavior

it exists some chunks that have more than 500 characters

**Comment by crazywoola** [comment]
> Delimiter: Specify a delimiter for text segmentation. For example, \n (newline character in [regex](https://regexr.com/)) will chunk text at each line break.
Maximum chunk length: Set the maximum character count per segment. Chunk exceeding this limit will be forcibly divided. The maximum length for a segment is 4000 tokens.
Chunk overlap: Define the overlap between adjacent chunks. This overlap enhances information retention and analysis accuracy, improving recall effectiveness. Recommended setting is 10-25% of the segment length in tokens.

Because, one of them is tokens not characters.

**Comment by applepieiris** [comment]
> > Delimiter: Specify a delimiter for text segmentation. For example, \n (newline character in [regex](https://regexr.com/)) will chunk text at each line break.
> > Maximum chunk length: Set the maximum character count per segment. Chunk exceeding this limit will be forcibly divided. The maximum length for a segment is 4000 tokens.
> > Chunk overlap: Define the overlap between adjacent chunks. This overlap enhances information retention and analysis accuracy, improving recall effectiveness. Recommended setting is 10-25% of the segment length in tokens.
> 
> Because one of them is `tokens` not `characters`.

I want to know what the meaning of the parameter "Maximum chunk length"? I see in your official document it writes "maximum character count per segment" ?　it is quite confusing you use the word "character" here.
