### ISSUE TITLE
Document are re-indexed without stopping

### ISSUE THREAD

**Issue by Qiuzg** [langgenius/dify#9986]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Upload more than 100 files each time, and repeat this step multiple times, RabbitMQ unacked count will not reduce to 0
Some documents will be re-indexed even if they had already been indexed

### ✔️ Expected Behavior

All documents are indexed successfully

### ❌ Actual Behavior

Some documents will be re-indexed even if they had already been indexed

**Comment by crazywoola** [comment]
Sorry we do not use RabbitMQ.

**Comment by wy96f** [comment]
> Sorry we do not use RabbitMQ.

@crazywoola This has nothing to do with the use of RabbitMQ or Redis. This is a mechanism of Celery, and you can refer to https://github.com/celery/celery/blob/main/docs/getting-started/backends-and-brokers/redis.rst#visibility-timeout
